### ISSUE TITLE
Erro during build

### ISSUE THREAD

**Issue by hadim** [OpenShot/openshot-qt#1]
See the following : 

```sh
 $ /usr/bin/python3 setup.py install  --prefix= /opt/local/openshot
       setup:INFO Execution path: /opt/local/openshot/openshot-qt/setup.py
running install
running build
running build_py
package init file 'src/__init__.py' not found (or not a regular file)
package init file 'src/classes/__init__.py' not found (or not a regular file)
package init file 'src/images/__init__.py' not found (or not a regular file)
package init file 'src/locale/__init__.py' not found (or not a regular file)
package init file 'src/settings/__init__.py' not found (or not a regular file)
package init file 'src/timeline/__init__.py' not found (or not a regular file)
package init file 'src/windows/__init__.py' not found (or not a regular file)
package init file 'src/windows/ui/__init__.py' not found (or not a regular file)
package init file 'src/__init__.py' not found (or not a regular file)
package init file 'src/classes/__init__.py' not found (or not a regular file)
package init file 'src/images/__init__.py' not found (or not a regular file)
package init file 'src/locale/__init__.py' not found (or not a regular file)
package init file 'src/settings/__init__.py' not found (or not a regular file)
package init file 'src/timeline/__init__.py' not found (or not a regular file)
package init file 'src/windows/__init__.py' not found (or not a regular file)
package init file 'src/windows/ui/__init__.py' not found (or not a regular file)
running build_scripts
error: file '/opt/local/openshot/openshot-qt/bin/openshot' does not exist
```

Any idea ?

**Comment by Jhackler** [comment]
I have this same problem in arch

**Comment by Algomorph** [comment]
+1

**Comment by Algomorph** [comment]
I got it down to:
```sudo python3 setup.py install
       setup:INFO Execution path: /home/myusername/Garage/openshot-qt/setup.py
running install
running build
running build_py
running build_scripts
error: file '/home/algomorph/Garage/openshot-qt/bin/openshot' does not exist```

I simply added __init__.py files. I am simply trying to apply the patch from [here](https://bugs.launchpad.net/openshot/+bug/499739), so using the installer is not an option.

**Comment by Algomorph** [comment]
Now reported at https://bugs.launchpad.net/openshot/+bug/1502966

**Comment by olielvewen** [comment]
Just two or three ideas:
1) try to run openshot-qt going to the src folder and open a console and type python launch.py
What do you have ? Did OSQT is running or not ? 
2) I'm mainly on Manjaro an derivative of Archlinux.
A user told me that you must remove some lines on two files. Here my notes about this issue
Note : At first look, you must remove the first 25 lines in 
1. src/libopenshot/src/bindings/python/openshot.i
2. src/libopenshot/src/bindings/ruby/openshot.i
3) A new version of libopenshot is out since one week around. Could you update it and try again.

**Comment by Algomorph** [comment]
Per (3), I have pulled and re-compiled libopenshot to the most current upstream version.
After this, for (1) running with python3, I am getting the following output:
```
Loaded modules from current directory: /home/algomorph/Garage/OpenShot/openshot-qt/src
      launch:INFO ------------------------------------------------
      launch:INFO    OpenShot (version 2.0.0)
      launch:INFO ------------------------------------------------
    language:INFO Qt Detected Languages: ['en-US']
    language:INFO LANG Environment Variable: en_US.UTF-8
    language:INFO LOCALE Environment Variable: en_US
    language:INFO Skipping English language (no need for translation): en_US.UTF-8
    language:INFO Skipping English language (no need for translation): en_US
link SVGID_18_-5 hasn't been detected!
link SVGID_18_-5 hasn't been detected!
link SVGID_22_-5 hasn't been detected!
link SVGID_24_-2 hasn't been detected!
link SVGID_24_-2 hasn't been detected!
     ui_util:INFO Initializing UI for MainWindow
     ui_util:INFO Binding event MainWindow:actionNew_trigger
     ui_util:INFO Binding event MainWindow:actionOpen_trigger
     ui_util:INFO Binding event MainWindow:actionSave_trigger
     ui_util:INFO Binding event MainWindow:actionUndo_trigger
     ui_util:INFO Binding event MainWindow:actionSaveAs_trigger
     ui_util:INFO Binding event MainWindow:actionImportFiles_trigger
     ui_util:INFO Binding event MainWindow:actionImportImageSequence_trigger
     ui_util:INFO Binding event MainWindow:actionImportTransition_trigger
     ui_util:INFO Binding event MainWindow:actionRedo_trigger
     ui_util:INFO Binding event MainWindow:actionRemoveClip_trigger
     ui_util:INFO Binding event MainWindow:actionRemoveTransition_trigger
     ui_util:INFO Binding event MainWindow:actionExportVideo_trigger
     ui_util:INFO Binding event MainWindow:actionUploadVideo_trigger
     ui_util:INFO Binding event MainWindow:actionAddTrack_trigger
     ui_util:INFO Binding event MainWindow:actionPreferences_trigger
     ui_util:INFO Binding event MainWindow:actionPlay_trigger
     ui_util:INFO Binding event MainWindow:actionJumpStart_trigger
     ui_util:INFO Binding event MainWindow:actionRewind_trigger
     ui_util:INFO Binding event MainWindow:actionFastForward_trigger
     ui_util:INFO Binding event MainWindow:actionJumpEnd_trigger
     ui_util:INFO Binding event MainWindow:actionArrowTool_trigger
     ui_util:INFO Binding event MainWindow:actionSnappingTool_trigger
     ui_util:INFO Binding event MainWindow:actionAddMarker_trigger
     ui_util:INFO Binding event MainWindow:actionPreviousMarker_trigger
     ui_util:INFO Binding event MainWindow:actionNextMarker_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowAll_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowVideo_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowAudio_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowImage_trigger
     ui_util:INFO Binding event MainWindow:actionTransitionsShowAll_trigger
     ui_util:INFO Binding event MainWindow:actionTransitionsShowCommon_trigger
     ui_util:INFO Binding event MainWindow:actionEffectsShowAll_trigger
     ui_util:INFO Binding event MainWindow:actionEffectsShowVideo_trigger
     ui_util:INFO Binding event MainWindow:actionEffectsShowAudio_trigger
     ui_util:INFO Binding event MainWindow:actionTimelineZoomIn_trigger
     ui_util:INFO Binding event MainWindow:actionTimelineZoomOut_trigger
     ui_util:INFO Binding event MainWindow:actionTitle_trigger
     ui_util:INFO Binding event MainWindow:actionAnimatedTitle_trigger
     ui_util:INFO Binding event MainWindow:actionFullscreen_trigger
     ui_util:INFO Binding event MainWindow:actionExit_Fullscreen_trigger
     ui_util:INFO Binding event MainWindow:actionAbout_trigger
     ui_util:INFO Binding event MainWindow:actionThumbnailView_trigger
     ui_util:WARNING Icon theme view-preview not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionDetailsView_trigger
     ui_util:WARNING Icon theme view-list-details not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionReportBug_trigger
     ui_util:INFO Binding event MainWindow:actionAskQuestion_trigger
     ui_util:INFO Binding event MainWindow:actionTranslate_trigger
     ui_util:INFO Binding event MainWindow:actionDonate_trigger
     ui_util:INFO Binding event MainWindow:actionHelpContents_trigger
     ui_util:INFO Binding event MainWindow:actionSimple_View_trigger
     ui_util:INFO Binding event MainWindow:actionAdvanced_View_trigger
     ui_util:WARNING Icon theme get-hot-new-stuff not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionFreeze_View_trigger
     ui_util:INFO Binding event MainWindow:actionUn_Freeze_View_trigger
     ui_util:INFO Binding event MainWindow:actionShow_All_trigger
     ui_util:INFO Binding event MainWindow:actionProfile_trigger
     ui_util:INFO Binding event MainWindow:actionPreview_File_trigger
     ui_util:INFO Binding event MainWindow:actionRemove_from_Project_trigger
     ui_util:INFO Binding event MainWindow:actionRemoveTrack_trigger
     ui_util:INFO Binding event MainWindow:actionRemoveMarker_trigger
     ui_util:INFO Binding event MainWindow:actionAddTrackAbove_trigger
     ui_util:INFO Binding event MainWindow:actionAddTrackBelow_trigger
     ui_util:INFO Binding event MainWindow:actionRemoveEffect_trigger
 files_model:INFO updating files model.
transition_model:INFO updating transitions model.
terminate called after throwing an instance of 'Magick::ErrorCoder'
  what():  Magick: WriteBlob Failed `/home/algomorph/.openshot_qt/cache/circle_in_to_out.png' @ error/png.c/MagickPNGErrorHandler/1645
Aborted (core dumped)
```
For (2), the first 25 lines of these two files are comments and don't seem related to the issue at hand. The python bindings are loading fine, i.e. 'import openshot' loads the module correctly from a python console.

P.S. I am on Ubuntu 15.10.

**Comment by olielvewen** [comment]
I'm on Linux Mint Rafaela 17.2 based on Ubuntu 14.04 LTS and I've not had this issue. However, I've updated the openshot qt and my previous test was a bit .....strange.

Here my output :  
olivier@siriel ~/OpenshotDev/openshot-qt/src $ python3 launch.py 
Loaded modules from current directory: /home/olivier/OpenshotDev/openshot-qt/src
      launch:INFO ------------------------------------------------
      launch:INFO    OpenShot (version 2.0.0)
      launch:INFO ------------------------------------------------
    language:INFO Qt Detected Languages: ['fr-FR']
    language:INFO LANG Environment Variable: fr_FR.UTF-8
    language:INFO LOCALE Environment Variable: fr_FR
    language:INFO Attempting to load qt_fr_FR.UTF-8 in '/usr/share/qt5/translations'
    language:INFO Attempting to load qt_fr in '/usr/share/qt5/translations'
    language:INFO Attempting to load fr_FR.UTF-8/LC_MESSAGES/OpenShot in '/home/olivier/OpenshotDev/openshot-qt/src/locale'
    language:INFO Attempting to load fr/LC_MESSAGES/OpenShot in '/home/olivier/OpenshotDev/openshot-qt/src/locale'
    language:INFO Successfully loaded fr/LC_MESSAGES/OpenShot in '/home/olivier/OpenshotDev/openshot-qt/src/locale'
    language:INFO Exiting translation system (since we successfully loaded: fr_FR.UTF-8)
link SVGID_18_-5 hasn't been detected!
link SVGID_18_-5 hasn't been detected!
link SVGID_22_-5 hasn't been detected!
link SVGID_24_-2 hasn't been detected!
link SVGID_24_-2 hasn't been detected!
     ui_util:INFO Initializing UI for MainWindow
     ui_util:INFO Binding event MainWindow:actionNew_trigger
     ui_util:WARNING Icon theme document-new not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionOpen_trigger
     ui_util:WARNING Icon theme document-open not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionSave_trigger
     ui_util:WARNING Icon theme document-save not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionUndo_trigger
     ui_util:WARNING Icon theme edit-undo not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionSaveAs_trigger
     ui_util:WARNING Icon theme document-save-as not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionImportFiles_trigger
     ui_util:WARNING Icon theme list-add not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionImportImageSequence_trigger
     ui_util:WARNING Icon theme list-add not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionImportTransition_trigger
     ui_util:WARNING Icon theme list-add not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionRedo_trigger
     ui_util:WARNING Icon theme edit-redo not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionRemoveClip_trigger
     ui_util:WARNING Icon theme list-remove not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionRemoveTransition_trigger
     ui_util:WARNING Icon theme list-remove not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionExportVideo_trigger
     ui_util:WARNING Icon theme media-record not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionUploadVideo_trigger
     ui_util:WARNING Icon theme folder-remote not found. Will use backup icon.
     ui_util:WARNING Icon theme gtk-quit not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAddTrack_trigger
     ui_util:WARNING Icon theme list-add not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionPreferences_trigger
     ui_util:WARNING Icon theme document-properties not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionPlay_trigger
     ui_util:WARNING Icon theme media-playback-start not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionJumpStart_trigger
     ui_util:WARNING Icon theme go-first not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionRewind_trigger
     ui_util:WARNING Icon theme media-seek-backward not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionFastForward_trigger
     ui_util:WARNING Icon theme media-seek-forward not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionJumpEnd_trigger
     ui_util:WARNING Icon theme go-last not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionArrowTool_trigger
     ui_util:INFO Binding event MainWindow:actionSnappingTool_trigger
     ui_util:INFO Binding event MainWindow:actionAddMarker_trigger
     ui_util:INFO Binding event MainWindow:actionPreviousMarker_trigger
     ui_util:WARNING Icon theme go-first not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionNextMarker_trigger
     ui_util:WARNING Icon theme go-last not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionFilesShowAll_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowVideo_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowAudio_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowImage_trigger
     ui_util:WARNING Icon theme edit-clear not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionTransitionsShowAll_trigger
     ui_util:INFO Binding event MainWindow:actionTransitionsShowCommon_trigger
     ui_util:WARNING Icon theme edit-clear not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionEffectsShowAll_trigger
     ui_util:INFO Binding event MainWindow:actionEffectsShowVideo_trigger
     ui_util:INFO Binding event MainWindow:actionEffectsShowAudio_trigger
     ui_util:WARNING Icon theme edit-clear not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionTimelineZoomIn_trigger
     ui_util:WARNING Icon theme zoom-in not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionTimelineZoomOut_trigger
     ui_util:WARNING Icon theme zoom-out not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionTitle_trigger
     ui_util:WARNING Icon theme font not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAnimatedTitle_trigger
     ui_util:WARNING Icon theme font not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionFullscreen_trigger
     ui_util:WARNING Icon theme view-fullscreen not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionExit_Fullscreen_trigger
     ui_util:WARNING Icon theme view-restore not found. Will use backup icon.
     ui_util:WARNING Icon theme zoom-in not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAbout_trigger
     ui_util:WARNING Icon theme help-about not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionThumbnailView_trigger
     ui_util:WARNING Icon theme view-preview not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionDetailsView_trigger
     ui_util:WARNING Icon theme view-list-details not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionReportBug_trigger
     ui_util:WARNING Icon theme dialog-error not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAskQuestion_trigger
     ui_util:WARNING Icon theme im-message-new not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionTranslate_trigger
     ui_util:WARNING Icon theme stock_person not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionDonate_trigger
     ui_util:WARNING Icon theme bookmark-new not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionHelpContents_trigger
     ui_util:WARNING Icon theme help not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionSimple_View_trigger
     ui_util:WARNING Icon theme go-home not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAdvanced_View_trigger
     ui_util:WARNING Icon theme get-hot-new-stuff not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionFreeze_View_trigger
     ui_util:WARNING Icon theme locked not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionUn_Freeze_View_trigger
     ui_util:WARNING Icon theme locked not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionShow_All_trigger
     ui_util:WARNING Icon theme zoom-in not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionProfile_trigger
     ui_util:WARNING Icon theme video-x-generic not found. Will use backup icon.
     ui_util:WARNING Icon theme list-add not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionPreview_File_trigger
     ui_util:WARNING Icon theme media-playback-start not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionRemove_from_Project_trigger
     ui_util:WARNING Icon theme list-remove not found. Will use backup icon.
     ui_util:WARNING Icon theme video-x-generic not found. Will use backup icon.
     ui_util:WARNING Icon theme edit-clear not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionRemoveTrack_trigger
     ui_util:WARNING Icon theme list-remove not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionRemoveMarker_trigger
     ui_util:WARNING Icon theme list-remove not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAddTrackAbove_trigger
     ui_util:WARNING Icon theme list-add not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAddTrackBelow_trigger
     ui_util:WARNING Icon theme list-add not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionRemoveEffect_trigger
     ui_util:WARNING Icon theme list-remove not found. Will use backup icon.
 files_model:INFO updating files model.
transition_model:INFO updating transitions model.
timeline_webview:INFO Qt Found!
timeline_webview:INFO $scope.Qt = true;
effects_model:INFO updating effects model.
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
properties_model:INFO updating clip properties model.
preview_thread:INFO QThread Start Method Invoked
preview_thread:INFO initPlayer
Reader SET: 0x24b9230
PLAY() on QTPlayer
preview_thread:INFO onPositionChanged
 main_window:INFO 1
timeline_webview:INFO $scope.MovePlayheadToFrame to frame 1
timeline_webview:INFO $scope.MovePlayhead to seconds 0
preview_thread:INFO onModeChanged
 files_model:INFO updating files model.
 main_window:INFO Loaded project /home/olivier/Vidéos/Honey Bees 96fps In 4K (ULTRA HD)(4ksamples.com).mp4
effects_model:INFO updating effects model.
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO updating effects model.
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO updating effects model.
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
 files_model:INFO updating files model.
 main_window:INFO Loaded project /home/olivier/Vidéos/Honey Bees 96fps In 4K (ULTRA HD)(4ksamples.com).mp4

I've informed by email to Jonathan about several issues and linked to this bug too.

**Comment by jonoomph** [comment]
I'm going to close this ticket, since so many things have been fixed and this ticket is a bit old. Please try again and create a new ticket if you still run into issues. Thanks!
