### ISSUE TITLE
Bug: Clip can be placed between Layers

### ISSUE THREAD

**Issue by DerGenaue** [OpenShot/openshot-qt#100]
When dragging carefully, the clip sometimes be placed between the layers.
Saving and reopening the project file makes the Clip return to a layer.

BTW: The windows installer should register the file extension
![os](https://cloud.githubusercontent.com/assets/7558512/13049358/aa2501a0-d3ec-11e5-9d64-6b8cf9cd87cf.png)

**Comment by jarlarntzen** [comment]
Yup. I've found the same thing.

**Comment by jonoomph** [comment]
Please retest this with our latest daily build. I am unable to reproduce this on recent builds, but I know we had that issue a while back. If you can find a way to reproduce it, please let me know and reopen this issue. Thanks!

**Comment by jarlarntzen** [comment]
Works well now. 😄
