### ISSUE TITLE
Rotate picture

### ISSUE THREAD

**Issue by katriin123** [OpenShot/openshot-qt#1000]
**System Details:**
* Operating System / Distro: Windows 10 Home x64 
* OpenShot Version: 2.4.0-dev3
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
I have a picture which is in portrait mode and when I have to rotate it, it goes to the left side of the video (all other side of the video is black). I think the middlepoint just disappears
![hoiva 1](https://user-images.githubusercontent.com/25430575/32268590-6c1a66cc-bef8-11e7-9ba9-5cc0cec1493b.PNG)
![hoiva1](https://user-images.githubusercontent.com/25430575/32268591-6c3887ce-bef8-11e7-9eed-4afd449778bc.PNG)
![hoiva2](https://user-images.githubusercontent.com/25430575/32268592-6c65c2e8-bef8-11e7-99cc-842f4cfa625d.PNG)

.

**Comment by katriin123** [comment]
Second picture is before rotate.
Third one is after I have it rotated

**Comment by DylanC** [comment]
Dup of #928
