### ISSUE TITLE
"Runtime to terminate it in an unusual way" error

### ISSUE THREAD

**Issue by aluminoids** [OpenShot/openshot-qt#1001]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

Windows 10; OpenShot 2.4.0-x86_64; don't know how to generate a log file

Help! :-)

When I open OpenShot, I get a message window with the header "Microsoft Visual C++ Runtime Library." The message says, "Runtime Error!  Program:C:\Program Files\OpenShot Video Editor\launch.exe  This application has requested the Runtime to terminate it in an unusual way.  Please contact the application's support team for more information."

I've tried turning my computer off and on.  I've tried uninstalling and reinstalling OpenShot.  I've uninstalled and reinstalled Java.  I've downloaded and installed the latest free copy of visual studio.

Nothing seems to help.  I still get the error message when the program starts.

So . . . . What steps should I take to solve this problem; how do I continue to enjoy OpenShot?

**Comment by DylanC** [comment]
@aluminoids - I would recommend to try some of the solutions here:

https://answers.microsoft.com/en-us/windows/forum/all/microsoft-visual-c-runtime-library-error-message/79f01db9-6bb5-424c-aca1-ab5174df0bc9?auth=1
