### ISSUE TITLE
Animated title - blender

### ISSUE THREAD

**Issue by Bl4ckPh4ntom** [OpenShot/openshot-qt#1002]
Hello. How can I use animated titles? I've got blender, but don't know what to do next. Any ideas?

**Comment by DylanC** [comment]
@Bl4ckPh4ntom - In the preferences you need to set the blender path. The path will be the location of the blender executable. 

I don't know your operating system but here are some examples:

**Windows**
64-bit - C:\Program Files\Blender Foundation\Blender\blender.exe
32-bit - C:\Program Files (x86)\Blender Foundation\Blender\blender.exe

**Linux**
/usr/lib/blender/blender
