### ISSUE TITLE
adjusting volume to minimum or maximum still not enough

### ISSUE THREAD

**Issue by thomaslp** [OpenShot/openshot-qt#1003]
**System Details:**
* Operating System / Distro: linux mint 18.3
* OpenShot Version: 2.4.0
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
i have speech on one track and music on another. some of the speech is too soft, so would like to raise the volume but that does not seem possible (1.00 max). and some parts the music is generally still too loud, even after having adjusted it to minimum, which is 10% (0.10). i tried manually in the properties window to change to below 0.10, but that did not work, it just reverted to 0.10. am i doing something wrong or is it impossible to achieve what i'm aiming for?

**Comment by DylanC** [comment]
@thomaslp - It does not sound very possible to me but I will leave this open in case someone else has a good idea.

**Comment by N3WWN** [comment]
What has worked for me is running the clip through ffmpeg's compand filter manually to adjust the audio gain properties.

https://ffmpeg.org/ffmpeg-filters.html#compand

Here's some detailed info on different ways to apply audio normalization:
https://superuser.com/questions/323119/how-can-i-normalize-audio-using-ffmpeg

Also, regarding the maximum volume, check your preferences and make sure that the Audio is set to 100 in the General tab.

**Comment by PASTJL** [comment]
Or Workaround possible with Audacity to create an audio track mixing your 2 audio tracks. Audacity allows "keyframed" effect  on sound volume.
Problem : You must synchronize  your volume turning with the video clip using the time elapsed on timeline ...

**Comment by ThirstyGeo** [comment]
This is still broken in 2.4.4
