### ISSUE TITLE
OpenShot not opening on Macbook Air

### ISSUE THREAD

**Issue by godtierhuman** [OpenShot/openshot-qt#1004]
**System Details:**
* Operating System / Distro: OSX 10.10.5
* OpenShot Version: 2.4.0
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

**Comment by DylanC** [comment]
@godtierhuman - Is v2.4.1 the same?

**Comment by DylanC** [comment]
@godtierhuman - Opens fine for me on Mac. Try the v2.4.1 release.
