### ISSUE TITLE
First steps learning LibOpenShot?

### ISSUE THREAD

**Issue by Rasulbek1996** [OpenShot/openshot-qt#1006]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

Hi Everyone! I`m new in libopenshot, so how can find tutorials for learning the library as fast as possiple including effectively?
Thanks in advance!

**Comment by Rasulbek1996** [comment]
Hi Everyone! I`m new in libopenshot, so how can find tutorials for learning the library as fast as possiple including effectively?
Thanks in advance!

**Comment by DylanC** [comment]
@Rasulbek1996 - Documentation link is here:
http://openshot.org/files/libopenshot/

**Comment by peanutbutterandcrackers** [comment]
@Rasulbek1996 - [Just in case you were talking about openshot](https://gist.github.com/peanutbutterandcrackers/f0f666243133e0ed25abbc12a4ba23d7) and not really libopenshot. :) :+1:
