### ISSUE TITLE
openshot 2.4 can not be installed on Ubuntu 17.10

### ISSUE THREAD

**Issue by sysmaster1** [OpenShot/openshot-qt#1007]
**System Details:**
* Operating System / Distro: Ubuntu 17.10
* OpenShot Version: 2.4.0
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
sudo add-apt-repository ppa:openshot.developers/ppa
sudo apt-get update

Err:9 http://ppa.launchpad.net/openshot.developers/ppa/ubuntu artful Release
  404  Not Found
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/openshot.developers/ppa/ubuntu artful Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

sudo apt-get install openshot-qt

Package openshot-qt is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'openshot-qt' has no installation candidate

best regards

**Comment by PASTJL** [comment]
I have 17.10 Kubuntu, and i use the AppImage instead ppa package.

**Comment by sysmaster1** [comment]
Hi Pastjl,

Thanks for the tip, works perfectly...
I was already using the 2.4.0 version in 17.04, but after upgrading to 17.10, it was gone.
Just when I was getting used to the new features of 2.4.0...

Best regards,

**Comment by PASTJL** [comment]
This week End, CDylan makes a lot of job, so use the daily build ( 2.4.0-11 available today)

**Comment by parq** [comment]
Hi!

Still can't be installed on Ubuntu 17.10: the artful directory is missing.

Despite of this, I tried to install the zesty version, but there is a problem with python:

python3-openshot:
 Depende: python3 (<3.6) pero se va a instalar 3.6.3-0ubuntu2
 Depende: libopenshot-audio6 pero no va a ser instalado
 Depende: libopenshot14 pero no va a ser instalado
 Depende: libpython3.5 (>=3.5.0~b1) but it is not installable

python3-openshot requieres python3 < 3.6, but Ubuntu has installed version 3.6.3-0ubuntu2.

Can you, please, reopen this bug and solve it?

Thank you in advance!

**Comment by flowck** [comment]
I got the same error. Is there any update on this topic.

Thanks.

**Comment by hollowdoor** [comment]
Me too. The appimage seems to work, but it's much nicer to have a package installed generally. The ppa only goes up to Ubuntu 17.04

**Comment by sbrl** [comment]
I can confirm that there's still a packaging issue for Ubuntu 17.10. Here's a transcript of me trying to install it:

```
sbrl@UbuntuArtful:~$ sudo apt update
Get:16 http://ppa.launchpad.net/openshot.developers/ppa/ubuntu zesty InRelease [15.4 kB]     
Get:27 http://ppa.launchpad.net/openshot.developers/ppa/ubuntu zesty/main amd64 Packages [3,500 B]                    
Get:29 http://ppa.launchpad.net/openshot.developers/ppa/ubuntu zesty/main i386 Packages [3,488 B]
Get:30 http://ppa.launchpad.net/openshot.developers/ppa/ubuntu zesty/main Translation-en [892 B]
Fetched 355 kB in 2s (176 kB/s)                                    
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up-to-date.
sbrl@UbuntuArtful:~$ sudo apt install openshot-qt
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 openshot-qt : Depends: python3-openshot but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
sbrl@UbuntuArtful:~$ sudo apt install python3-openshot
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 python3-openshot : Depends: python3 (< 3.6) but 3.6.3-0ubuntu2 is to be installed
                    Depends: libpython3.5 (>= 3.5.0~b1) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

....some parts have been altered / removed for privacy reasons. From this, I can conclude that the following issues are occurring:

1. There isn't a package being built directly for artful (Ubuntu 17.10), so one has to use the zesty (17.04) ppa instead.
2. The version of `python3` installed on 17.10 machines is slightly newer than the overly-specific version specified as a dependency in the `openshot-qt` package.

**Comment by james3mc** [comment]
This may be a stupid question, but, if I install the Appimage for now and then this ppa/artful issue is fixing at some time in the future, will I end up with two installations?

**Comment by hollowdoor** [comment]
@james3mc Yes that's technically two installs. You can probably just delete the AppImage file after the ppa is updated.

But you can use both the AppImage, and the ppa installed version. The only thing to worry about is if both instances of the program are manipulating the same file at the same time you might have problems.

Also the ppa will automatically update the ppa installed app so it's likely to be ahead in versions over the AppImage.

**Comment by james3mc** [comment]
@hollowdoor Thanks for clearing that up. Appimage for now and I'll delete it if ever the ppa gets sorted.

**Comment by hollowdoor** [comment]
@james3mc Cool. I'm hoping we'll get a proper ppa soon.

**Comment by rolandixor** [comment]
Has this been abandoned?

**Comment by peanutbutterandcrackers** [comment]
Ubuntu 18.04 will be out next week. And OpenShot has been confirmed to be in the repositories for Ubuntu 18.04. So... I think this isn't really on the priority list...

Just 1 more month!!!
