### ISSUE TITLE
[Archlinux] Openshot 2.4 cannot export video because SIGSEGV on Qt

### ISSUE THREAD

**Issue by heavysink** [OpenShot/openshot-qt#1008]
**System Details:**
* Operating System / Distro: Archlinux / Qt 5.9.2
* OpenShot Version: Either 2.4 or git version
* _Please attach log files if crash_
Caught signal 11 (SIGSEGV)
---- Unhandled Exception: Stack Trace ----
  /usr/lib/python3.6/site-packages/_openshot.so (                                           + 0xe5646)  [0x7f1f2477a646]
  /usr/lib/python3.6/site-packages/_openshot.so (                                           + 0xe5e4d)  [0x7f1f2477ae4d]
  /usr/lib/libpython3.6m.so.1.0  ( PyCFunction_Call                          + 0x5f  )  [0x7f1f442ccdef]
  /usr/lib/libpython3.6m.so.1.0  ( _PyEval_EvalFrameDefault                  + 0x57aa)  [0x7f1f4426703a]
  /usr/lib/libpython3.6m.so.1.0  (                                           + 0x1062b4)  [0x7f1f4425f2b4]
  /usr/lib/libpython3.6m.so.1.0  (                                           + 0x122c4f)  [0x7f1f4427bc4f]
  /usr/lib/libpython3.6m.so.1.0  (                                           + 0x12314e)  [0x7f1f4427c14e]
  /usr/lib/libpython3.6m.so.1.0  ( _PyEval_EvalFrameDefault                  + 0x30a )  [0x7f1f44261b9a]
  /usr/lib/libpython3.6m.so.1.0  (                                           + 0x106496)  [0x7f1f4425f496]
  /usr/lib/libpython3.6m.so.1.0  ( _PyFunction_FastCallDict                  + 0x1bc )  [0x7f1f4427b5cc]
  /usr/lib/libpython3.6m.so.1.0  ( _PyObject_FastCallDict                    + 0x26f )  [0x7f1f442baf5f]
  /usr/lib/libpython3.6m.so.1.0  ( _PyObject_Call_Prepend                    + 0x63  )  [0x7f1f442bbcd3]
  /usr/lib/libpython3.6m.so.1.0  ( PyObject_Call                             + 0x4b  )  [0x7f1f442bbdbb]
  /usr/lib/python3.6/site-packages/PyQt5/QtCore.so (                                           + 0x1ea5d1)  [0x7f1f36edf5d1]
  /usr/lib/python3.6/site-packages/PyQt5/QtCore.so (                                           + 0x1eaac1)  [0x7f1f36edfac1]
  /usr/lib/python3.6/site-packages/PyQt5/QtCore.so (                                           + 0x1ead53)  [0x7f1f36edfd53]
  /usr/lib/python3.6/site-packages/PyQt5/QtCore.so (                                           + 0x1eb6e8)  [0x7f1f36ee06e8]
  /usr/lib/libQt5Core.so.5       ( QMetaObject::activate(QObject*, int, int, void**)  + 0x952 )  [0x7f1f3d222ce2]
  /usr/lib/libQt5Widgets.so.5    (                                           + 0x2e4e01)  [0x7f1f3e0a9e01]
  /usr/lib/libQt5Core.so.5       ( QMetaObject::activate(QObject*, int, int, void**)  + 0x886 )  [0x7f1f3d222c16]
  /usr/lib/libQt5Widgets.so.5    ( QAbstractButton::clicked(bool)            + 0x43  )  [0x7f1f3e005ff3]
  /usr/lib/libQt5Widgets.so.5    (                                           + 0x24120c)  [0x7f1f3e00620c]
  /usr/lib/libQt5Widgets.so.5    (                                           + 0x24264c)  [0x7f1f3e00764c]
  /usr/lib/libQt5Widgets.so.5    ( QAbstractButton::mouseReleaseEvent(QMouseEvent*)  + 0xf5  )  [0x7f1f3e007845]
  /usr/lib/python3.6/site-packages/PyQt5/QtWidgets.so (                                           + 0x2cc8d4)  [0x7f1f3e8e08d4]
  /usr/lib/libQt5Widgets.so.5    ( QWidget::event(QEvent*)                   + 0x1f8 )  [0x7f1f3df50a08]
  /usr/lib/python3.6/site-packages/PyQt5/QtWidgets.so (                                           + 0x2cd184)  [0x7f1f3e8e1184]
  /usr/lib/libQt5Widgets.so.5    ( QApplicationPrivate::notify_helper(QObject*, QEvent*)  + 0x9c  )  [0x7f1f3df10f2c]
  /usr/lib/libQt5Widgets.so.5    ( QApplication::notify(QObject*, QEvent*)   + 0x821 )  [0x7f1f3df18f81]
  /usr/lib/python3.6/site-packages/PyQt5/QtWidgets.so (                                           + 0x15050f)  [0x7f1f3e76450f]
  /usr/lib/libQt5Core.so.5       ( QCoreApplication::notifyInternal2(QObject*, QEvent*)  + 0x120 )  [0x7f1f3d1f3060]
  /usr/lib/libQt5Widgets.so.5    ( QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool)  + 0x1da )  [0x7f1f3df17f0a]
  /usr/lib/libQt5Widgets.so.5    (                                           + 0x1a6d81)  [0x7f1f3df6bd81]
  /usr/lib/libQt5Widgets.so.5    (                                           + 0x1a94c1)  [0x7f1f3df6e4c1]
  /usr/lib/libQt5Widgets.so.5    ( QApplicationPrivate::notify_helper(QObject*, QEvent*)  + 0x9c  )  [0x7f1f3df10f2c]
  /usr/lib/libQt5Widgets.so.5    ( QApplication::notify(QObject*, QEvent*)   + 0x2a6 )  [0x7f1f3df18a06]
  /usr/lib/python3.6/site-packages/PyQt5/QtWidgets.so (                                           + 0x15050f)  [0x7f1f3e76450f]
  /usr/lib/libQt5Core.so.5       ( QCoreApplication::notifyInternal2(QObject*, QEvent*)  + 0x120 )  [0x7f1f3d1f3060]
  /usr/lib/libQt5Gui.so.5        ( QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*)  + 0x704 )  [0x7f1f3d7523d4]
  /usr/lib/libQt5Gui.so.5        ( QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*)  + 0x136 )  [0x7f1f3d753f36]
  /usr/lib/libQt5Gui.so.5        ( QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>)  + 0xac  )  [0x7f1f3d72b48c]
  /usr/lib/libQt5XcbQpa.so.5     (                                           + 0x9a4b1)  [0x7f1f175c74b1]
  /usr/lib/libglib-2.0.so.0      ( g_main_context_dispatch                   + 0x310 )  [0x7f1f3b07f270]
  /usr/lib/libglib-2.0.so.0      (                                           + 0x6cf69)  [0x7f1f3b080f69]
  /usr/lib/libglib-2.0.so.0      ( g_main_context_iteration                  + 0x2e  )  [0x7f1f3b080fae]
  /usr/lib/libQt5Core.so.5       ( QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>)  + 0x61  )  [0x7f1f3d24dcd1]
  /usr/lib/libQt5Core.so.5       ( QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>)  + 0x13b )  [0x7f1f3d1f148b]
  /usr/lib/libQt5Widgets.so.5    ( QDialog::exec()                           + 0x21b )  [0x7f1f3e104e8b]
  /usr/lib/python3.6/site-packages/PyQt5/QtWidgets.so (                                           + 0x18d0f9)  [0x7f1f3e7a10f9]
  /usr/lib/libpython3.6m.so.1.0  ( _PyCFunction_FastCallDict                 + 0x90  )  [0x7f1f442ccaf0]
  /usr/lib/libpython3.6m.so.1.0  (                                           + 0x12308b)  [0x7f1f4427c08b]
  /usr/lib/libpython3.6m.so.1.0  ( _PyEval_EvalFrameDefault                  + 0x30a )  [0x7f1f44261b9a]
  /usr/lib/libpython3.6m.so.1.0  ( _PyFunction_FastCallDict                  + 0x11b )  [0x7f1f4427b52b]
  /usr/lib/libpython3.6m.so.1.0  ( _PyObject_FastCallDict                    + 0x26f )  [0x7f1f442baf5f]
  /usr/lib/libpython3.6m.so.1.0  ( _PyObject_Call_Prepend                    + 0x63  )  [0x7f1f442bbcd3]
  /usr/lib/libpython3.6m.so.1.0  ( PyObject_Call                             + 0x4b  )  [0x7f1f442bbdbb]
  /usr/lib/python3.6/site-packages/PyQt5/QtCore.so (                                           + 0x1ea5d1)  [0x7f1f36edf5d1]
  /usr/lib/python3.6/site-packages/PyQt5/QtCore.so (                                           + 0x1eaac1)  [0x7f1f36edfac1]
  /usr/lib/python3.6/site-packages/PyQt5/QtCore.so (                                           + 0x1ead53)  [0x7f1f36edfd53]
  /usr/lib/python3.6/site-packages/PyQt5/QtCore.so (                                           + 0x1eb6e8)  [0x7f1f36ee06e8]
---- End of Stack Trace ----

**Issue Description and steps to reproduce:**
Openshot cannot export video anymore. It will give SIESEGV on Qt.

**Comment by heavysink** [comment]
Appimage version is also crashing. 
Caught signal 11 (SIGSEGV)
---- Unhandled Exception: Stack Trace ----
  /tmp/.mount_kkdmkj/usr/bin/_openshot.so (                                           + 0xdf633)  [0x7f55a7ad2633]
  /tmp/.mount_kkdmkj/usr/bin/_openshot.so (                                           + 0xdfdce)  [0x7f55a7ad2dce]
  /tmp/.mount_kkdmkj/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalFrameEx                        + 0x654b)  [0x7f55bc86af7b]
  /tmp/.mount_kkdmkj/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalCodeEx                         + 0x886 )  [0x7f55bc86e936]
  /tmp/.mount_kkdmkj/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalFrameEx                        + 0x6742)  [0x7f55bc86b172]
  /tmp/.mount_kkdmkj/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalCodeEx                         + 0x886 )  [0x7f55bc86e936]
  /tmp/.mount_kkdmkj/usr/bin/libpython3.4m.so.1.0 (                                           + 0x209f66)  [0x7f55bc86ef66]
  /tmp/.mount_kkdmkj/usr/bin/libpython3.4m.so.1.0 ( PyObject_Call                             + 0x68  )  [0x7f55bc7d0718]
  /tmp/.mount_kkdmkj/usr/bin/libpython3.4m.so.1.0 (                                           + 0x15155d)  [0x7f55bc7b655d]
  /tmp/.mount_kkdmkj/usr/bin/libpython3.4m.so.1.0 ( PyObject_Call                             + 0x68  )  [0x7f55bc7d0718]
  /tmp/.mount_kkdmkj/usr/bin/libpython3.4m.so.1.0 ( PyEval_CallObjectWithKeywords             + 0x47  )  [0x7f55bc846977]
  /tmp/.mount_kkdmkj/usr/bin/PyQt5.QtCore.so ( PyQtSlot::invoke(_object*, _object*) const  + 0x50  )  [0x7f55b294b840]
  /tmp/.mount_kkdmkj/usr/bin/PyQt5.QtCore.so ( PyQtSlot::invoke(void**, _object*, void*) const  + 0xcf  )  [0x7f55b294bcaf]
  /tmp/.mount_kkdmkj/usr/bin/PyQt5.QtCore.so ( PyQtSlotProxy::unislot(void**)            + 0x62  )  [0x7f55b2956762]
  /tmp/.mount_kkdmkj/usr/bin/PyQt5.QtCore.so ( PyQtSlotProxy::qt_metacall(QMetaObject::Call, int, void**)  + 0x57  )  [0x7f55b29570d7]
  /tmp/.mount_kkdmkj/usr/bin/libQt5Core.so.5 ( QMetaObject::activate(QObject*, int, int, void**)  + 0x8ad )  [0x7f55b7ca036d]
  /tmp/.mount_kkdmkj/usr/bin/libQt5Core.so.5 ( QMetaObject::activate(QObject*, int, int, void**)  + 0x7e6 )  [0x7f55b7ca02a6]
  /tmp/.mount_kkdmkj/usr/bin/libQt5Widgets.so.5 ( QAbstractButton::clicked(bool)            + 0x32  )  [0x7f55b8babe42]
  /tmp/.mount_kkdmkj/usr/bin/libQt5Widgets.so.5 (                                           + 0x231096)  [0x7f55b8935096]
  /tmp/.mount_kkdmkj/usr/bin/libQt5Widgets.so.5 (                                           + 0x231bae)  [0x7f55b8935bae]
  /tmp/.mount_kkdmkj/usr/bin/libQt5Widgets.so.5 ( QAbstractButton::mouseReleaseEvent(QMouseEvent*)  + 0xd4  )  [0x7f55b8935d24]
  /tmp/.mount_kkdmkj/usr/bin/PyQt5.QtWidgets.so ( sipQPushButton::mouseReleaseEvent(QMouseEvent*)  + 0x7b  )  [0x7f55b92b4fab]
  /tmp/.mount_kkdmkj/usr/bin/libQt5Widgets.so.5 ( QWidget::event(QEvent*)                   + 0x405 )  [0x7f55b8879ea5]
  /tmp/.mount_kkdmkj/usr/bin/PyQt5.QtWidgets.so ( sipQPushButton::event(QEvent*)            + 0x7b  )  [0x7f55b92b69ab]
  /tmp/.mount_kkdmkj/usr/bin/libQt5Widgets.so.5 ( QApplicationPrivate::notify_helper(QObject*, QEvent*)  + 0x8c  )  [0x7f55b883ec8c]
  /tmp/.mount_kkdmkj/usr/bin/libQt5Widgets.so.5 ( QApplication::notify(QObject*, QEvent*)   + 0x10e1)  [0x7f55b8844b61]
  /tmp/.mount_kkdmkj/usr/bin/PyQt5.QtWidgets.so ( sipQApplication::notify(QObject*, QEvent*)  + 0x86  )  [0x7f55b9214426]
  /tmp/.mount_kkdmkj/usr/bin/libQt5Core.so.5 ( QCoreApplication::notifyInternal(QObject*, QEvent*)  + 0x6d  )  [0x7f55b7c78c2d]
  /tmp/.mount_kkdmkj/usr/bin/libQt5Widgets.so.5 ( QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool)  + 0x391 )  [0x7f55b88429e1]
  /tmp/.mount_kkdmkj/usr/bin/libQt5Widgets.so.5 (                                           + 0x192bbf)  [0x7f55b8896bbf]
  /tmp/.mount_kkdmkj/usr/bin/libQt5Widgets.so.5 (                                           + 0x1949bb)  [0x7f55b88989bb]
  /tmp/.mount_kkdmkj/usr/bin/libQt5Widgets.so.5 ( QApplicationPrivate::notify_helper(QObject*, QEvent*)  + 0x8c  )  [0x7f55b883ec8c]
  /tmp/.mount_kkdmkj/usr/bin/libQt5Widgets.so.5 ( QApplication::notify(QObject*, QEvent*)   + 0x3d6 )  [0x7f55b8843e56]
  /tmp/.mount_kkdmkj/usr/bin/PyQt5.QtWidgets.so ( sipQApplication::notify(QObject*, QEvent*)  + 0x86  )  [0x7f55b9214426]
  /tmp/.mount_kkdmkj/usr/bin/libQt5Core.so.5 ( QCoreApplication::notifyInternal(QObject*, QEvent*)  + 0x6d  )  [0x7f55b7c78c2d]
  /tmp/.mount_kkdmkj/usr/bin/libQt5Gui.so.5 ( QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*)  + 0x39c )  [0x7f55b819825c]
  /tmp/.mount_kkdmkj/usr/bin/libQt5Gui.so.5 ( QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*)  + 0x115 )  [0x7f55b8199925]
  /tmp/.mount_kkdmkj/usr/bin/libQt5Gui.so.5 ( QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>)  + 0x28  )  [0x7f55b8182858]
  /tmp/.mount_kkdmkj/usr/bin/platforms/libqxcb.so (                                           + 0x4f5b0)  [0x7f559fe535b0]
  /usr/lib/libglib-2.0.so.0      ( g_main_context_dispatch                   + 0x310 )  [0x7f55b6f69270]
  /usr/lib/libglib-2.0.so.0      (                                           + 0x6cf69)  [0x7f55b6f6af69]
  /usr/lib/libglib-2.0.so.0      ( g_main_context_iteration                  + 0x2e  )  [0x7f55b6f6afae]
  /tmp/.mount_kkdmkj/usr/bin/libQt5Core.so.5 ( QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>)  + 0x5c  )  [0x7f55b7cc598c]
  /tmp/.mount_kkdmkj/usr/bin/libQt5Core.so.5 ( QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>)  + 0x11b )  [0x7f55b7c7796b]
  /tmp/.mount_kkdmkj/usr/bin/libQt5Widgets.so.5 ( QDialog::exec()                           + 0x20d )  [0x7f55b8a25e0d]
  /tmp/.mount_kkdmkj/usr/bin/PyQt5.QtWidgets.so (                                           + 0x374c35)  [0x7f55b92a1c35]
  /tmp/.mount_kkdmkj/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalFrameEx                        + 0x6d79)  [0x7f55bc86b7a9]
  /tmp/.mount_kkdmkj/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalCodeEx                         + 0x886 )  [0x7f55bc86e936]
  /tmp/.mount_kkdmkj/usr/bin/libpython3.4m.so.1.0 (                                           + 0x209f66)  [0x7f55bc86ef66]
  /tmp/.mount_kkdmkj/usr/bin/libpython3.4m.so.1.0 ( PyObject_Call                             + 0x68  )  [0x7f55bc7d0718]
  /tmp/.mount_kkdmkj/usr/bin/libpython3.4m.so.1.0 (                                           + 0x15155d)  [0x7f55bc7b655d]
  /tmp/.mount_kkdmkj/usr/bin/libpython3.4m.so.1.0 ( PyObject_Call                             + 0x68  )  [0x7f55bc7d0718]
  /tmp/.mount_kkdmkj/usr/bin/libpython3.4m.so.1.0 ( PyEval_CallObjectWithKeywords             + 0x47  )  [0x7f55bc846977]
  /tmp/.mount_kkdmkj/usr/bin/PyQt5.QtCore.so ( PyQtSlot::invoke(_object*, _object*) const  + 0x50  )  [0x7f55b294b840]
  /tmp/.mount_kkdmkj/usr/bin/PyQt5.QtCore.so ( PyQtSlot::invoke(void**, _object*, void*) const  + 0xcf  )  [0x7f55b294bcaf]
  /tmp/.mount_kkdmkj/usr/bin/PyQt5.QtCore.so ( PyQtSlotProxy::unislot(void**)            + 0x62  )  [0x7f55b2956762]
  /tmp/.mount_kkdmkj/usr/bin/PyQt5.QtCore.so ( PyQtSlotProxy::qt_metacall(QMetaObject::Call, int, void**)  + 0x57  )  [0x7f55b29570d7]
  /tmp/.mount_kkdmkj/usr/bin/libQt5Core.so.5 ( QMetaObject::activate(QObject*, int, int, void**)  + 0x8ad )  [0x7f55b7ca036d]
  /tmp/.mount_kkdmkj/usr/bin/libQt5Widgets.so.5 ( QAction::triggered(bool)                  + 0x32  )  [0x7f55b8837a52]
  /tmp/.mount_kkdmkj/usr/bin/libQt5Widgets.so.5 ( QAction::activate(QAction::ActionEvent)   + 0xe8  )  [0x7f55b8839f38]
---- End of Stack Trace ----

It seems that it is a glib problem...glib version: 2.54.2

**Comment by DylanC** [comment]
@heavysink - Also happens on v2.4.1?

**Comment by DylanC** [comment]
@heavysink - I recommend to try the AppImage instead.
