### ISSUE TITLE
How to achieve smooth operation?

### ISSUE THREAD

**Issue by braaap247** [OpenShot/openshot-qt#1009]
**System Details:**
* Operating System / Distro: Windows 10 build 17025
* OpenShot Version: current
* System specs: i5 2500s, GTX 580, 5gb ram

My question is: what makes open shot run smoother- more ram or a faster CPU? My cpu runs at 2.77ghz under load and I have allocated 2gb ram for open shot to use. Additionally, i have been editing off a USB 3.0 HDD. the problem I have been having is my CPU is pinned and my memory starts going into swap when I am editing video resulting in slow scrubbing, 20+ second waits when I slice a clip and it makes it very hard to adjust audio. Would it be more beneficial to import video to my SSD? Would adding more ram help? Can I enable GPU rendering? Should I try and increase my CPU clock speed? I need to figure this out because I love open shot and want to continue to use it, however, if I can not make the program run smoothly then I may need to find new software.

**Comment by DylanC** [comment]
@braaap247 - I think CPU and RAM would be the answer here but definitely RAM.  We do not have GPU acceleration currently.
