### ISSUE TITLE
No need to change filenames in export

### ISSUE THREAD

**Issue by seindal** [OpenShot/openshot-qt#101]
Openshot 2 changes the name of the file in the export dialog. It seems to capitalise and replace special characters with spaces.

If my project is "SomeOddName 2016-01-05" then openshot exports to a video named "Someoddname 2016 01 05".

The program should not presume to know better than me how I want my files names.

**Comment by ankitpati** [comment]
No repro on OpenShot 1.4.3 from Ubuntu 16.04 repositories.

**Comment by jonoomph** [comment]
This is just the default name suggested after the name of the project. I'm open to suggestions. Closing ticket for now.
