### ISSUE TITLE
Windows 10 large mp3 soundfile: after 1 minute hear just "prrrrrrrrrrrrrrrrrr".

### ISSUE THREAD

**Issue by mediumtrivia** [OpenShot/openshot-qt#1011]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: newest for windows 10 hp laptop ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

**Comment by mediumtrivia** [comment]
Okay. I just installed Open Shot the newest version on my Windows 10 HP laptop. I uploaded a mp3 file. After a minute i hear just "prrrrrrrrrrrrrrrrrrrrrrrrrr".  The file is a recording from my voice recording. I got audiacity: should I convert the file to WAV? Did not try that out yet. It is a pretty long file. What do you recommend? Can you send the answer to paashaas70@gmail.com please? Thanks!

**Comment by DylanC** [comment]
@mediumtrivia - Try the latest daily build for Windows. There was a problem with mp3 files that should be resolved now.
