### ISSUE TITLE
Save files from newest Version won't open

### ISSUE THREAD

**Issue by nhzgrip** [OpenShot/openshot-qt#1013]
**System Details:**
* Operating System / Distro: Windows 7
* OpenShot Version: 2.4.0.
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
Since i updated to the new Open Shot Version, save files that i saved in the new version, are not opening anymore. Files that i created before updating i can open normally. 
I tried saving different files, and all with the same result. Restarted Open Shot and Windows, same problem. 
I get no error message or signal that something is wrong, or that something is being processed.
It just remains in the open project without doing anything when i open a Projectfile saved in the newest OpenShot version.

**Comment by nhzgrip** [comment]
ARRg, i've tried installing older versions and now they have the same bug. Complete Unistall before, same thing. i can still open files saved previously, but not even files saved just a second ago....

**Comment by DylanC** [comment]
@nhzgrip  - Did you move the project file to a new location?

**Comment by DylanC** [comment]
If its a setup problem. I will close. I would try to delete the preferences folder if you still have issues.
