### ISSUE TITLE
Problem with mp3 file

### ISSUE THREAD

**Issue by mediumtrivia** [OpenShot/openshot-qt#1014]
**System Details:**
* Operating System / Distro: HP Laptop Windows 10
* OpenShot Version: Open Shot 2.4.0
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
I would like to project the entire mp3 file under the photograph. Should I convert the mp3 to wav or another kind of file? Please, be so kind to send the answer to paashaas70@gmail.com. I was used to moviemaker. This looks just as good: but I guess nothing can be compared to the quality MovieMaker had!

**Comment by DylanC** [comment]
Dup of #1011
