### ISSUE TITLE
open project problem

### ISSUE THREAD

**Issue by rj684810** [OpenShot/openshot-qt#1016]
nothing happen when I "right-click" my "Project.ops" and I "open it with" Openshot.
I think it doesn't find the folder because it's the desktop but if someone have an other idea, I take it.

ps: Openshot start running but it's empty and start the tutorial

Windows 10

**Comment by DylanC** [comment]
@rj684810 - Did you move the project file?

**Comment by DylanC** [comment]
Closed due to lack of activity.
