### ISSUE TITLE
Export Dialog never comes up

### ISSUE THREAD

**Issue by Bryan76** [OpenShot/openshot-qt#1017]
**System Details:**
* Operating System / Distro: Ubuntu 17.10, fresh install
* OpenShot Version: 2.4 AppImage
* _Please attach log files if crash_

Any time I go to export the video, the export dialog never comes up.

[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/1459339/openshot-qt.log)

**Comment by DylanC** [comment]
@Bryan76 - I can see you have spaces in the project filename (.osp file). The daily build has fixes in for this issue. I would recommend to download and try a daily build from the downloads page.

**Comment by Bryan76** [comment]
The nightly solved that issue.  Now I get the export dialog.  However, now it crashes on export, which is a separate issue, so I think this Issue can be closed.
