### ISSUE TITLE
importing image seq starts from 1001

### ISSUE THREAD

**Issue by ohiro26** [OpenShot/openshot-qt#1019]
**System Details:**
* Operating System / Distro: ?
Linux Mint 17.1 Rebecca 64bit

* OpenShot Version: ?
v2.40

* _Please attach log files if crash_

When I try to import the image sequence starts from 1001, it says
"*** is not valid video,audio, or image file"

**Comment by DylanC** [comment]
@ohiro26 - Try the v2.4.1 release. People have confirmed it as working.

**Comment by DylanC** [comment]
@ohiro26 - Also try to use your files with simple numbers:

file1, file2, etc...

Image sequence has only a simple implementation so far.
