### ISSUE TITLE
no import sequence?

### ISSUE THREAD

**Issue by ravencrowe** [OpenShot/openshot-qt#1020]
i can't import image sequence and my openShot dont have the "import image sequence" menu?

win10
openShot 2.40
intel I7
mem16gig
geforce gtx770

**Comment by DylanC** [comment]
@ravencrowe - I think if you import as normal it works.

**Comment by DylanC** [comment]
@ravencrowe 

Choose Import Files and select the first image in your sequence. If there are more files in the sequence, OpenShot asks if you want to import them as an image sequence and turns them into a video clip.
