### ISSUE TITLE
all audio getting mashed up 

### ISSUE THREAD

**Issue by krishnaTORQUE** [OpenShot/openshot-qt#1021]
**System Details: RAM 16 GB, NVIDIA GPU 4GB**
* Operating System / Distro: Ubuntu 16.04
* OpenShot Version: 2.4

**all audio getting mashed up. Tried with mp3, ogg, wav, m4a. All are not playing as it is.**

**Comment by DylanC** [comment]
@krishnaTORQUE - Try the v2.4.1 release. It has fixes for audio in it.
