### ISSUE TITLE
no audio fade in/out at exported video

### ISSUE THREAD

**Issue by TimUx** [OpenShot/openshot-qt#1022]
**System Details:**
* Operating System / Distro: Ubuntu 17.04
* OpenShot Version: OpenShot-v2.4.0-13-g542f432-56-654-x86_64

**Issue Description and steps to reproduce:**
I've added several mp3 song as background music.
I've added "fade in / fade out" to the songs and overlap two songs. at the beginning / end.
In the preview everything is fine, the exported video has no fade.
The songs just stops and the other starts with no fade.

**Comment by DylanC** [comment]
@TimUx - Thanks for the report.

**Comment by TimUx** [comment]
Hi,
i did some more Tests.

When i did'nt overlap mp3 songs, the fade in/out works as aspekted.

I have generally some issues, when i add some mp3 songs as backgroud music.
One song as background music is no problem but when i add another song behind, the export crashed with the double link error, I've reported in the issue #937  and #1028

Regards
Timo

**Comment by N3WWN** [comment]
Are you placing both mp3 on the same track and physically overlapping them?  

If so, try putting one mp3 per track and logically overlap them on separate tracks.

The tracks can be reused if you have more than 2 mp3s, so you'll probably only need 2 tracks total.

**Comment by TimUx** [comment]
Hi,
i put the mp3s on two different tracks (track 0 and track 1), videos, pictures and titles are on track 2 and 3.

And i hvae still the problem, when i put more than one mp3 to the projekt, most time the video export crashes with the double link error.

I've to complete my information, at the moment I'am on version 2.4.1-dev1

**Comment by DylanC** [comment]
@TimUx - Do the mp3 files have album art?

**Comment by TimUx** [comment]
Hi,
the most of them have album arts, yes.

**Comment by DylanC** [comment]
@TimUx - I think that is the source of the problem. Openshot does currently have trouble with album art.

**Comment by TimUx** [comment]
So,
I've checked the mp3 file of my last Project.

No one of them habe an album art, so it ist no album art issue.

Now i will convert the mp3 to an other audioformat, to test if the issue still exists.

**Comment by TimUx** [comment]
OK,
still have issues, also when using WAV files.

At the moment, i got the double link error.

*** Error in `/usr/bin/python3': corrupted double-linked list: 0x00007f8912fdc300 ***

When I'am removing all audio files, the export crashes with:

Caught signal 11 (SIGSEGV)
---- Unhandled Exception: Stack Trace ----
  /usr/lib/x86_64-linux-gnu/libopenshot.so.14 (                                           + 0x111739)  [0x7f3461cd4739]
  /usr/lib/x86_64-linux-gnu/libgomp.so.1 (                                           + 0x16e16)  [0x7f345e5e2e16]
  /lib/x86_64-linux-gnu/libpthread.so.0 (                                           + 0x76da)  [0x7f347b8916da]
  /lib/x86_64-linux-gnu/libc.so.6 ( clone                                     + 0x5f  )  [0x7f347b5cbd7f]
---- End of Stack Trace ----

**Comment by DylanC** [comment]
@jonoomph - Any ideas?
