### ISSUE TITLE
Video goes black, sound continues

### ISSUE THREAD

**Issue by ZahidIsAGit** [OpenShot/openshot-qt#1023]
**System Details:**
* Operating System / Distro: Ubuntu 16.04
* OpenShot Version: 2.4
* CPU: Intel Core i5-2400 CPU @ 3.10GHz × 4
* RAM: 8 GB
* Log files:
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/1465317/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/1465318/openshot-qt.log)

**Issue Description and steps to reproduce:**
I'm attempting to string together a bunch of old .dv files so I can burn a video DVD. If I click on one from the OS file manager, it plays fine using the default Ubuntu "Videos" app, so I *think* the source file is not corrupted.

If, however, I import that same file into a new OpenShot project, I run into problems. It plays fine for about 24 seconds, then the screen goes black. The sound continues to play. If I repeat the steps, the same thing happens every time at the same point in the video. If I click later in the video, I get a still picture for a second, then the sound starts up (at the new location) but the picture goes black again.

What would cause this behavior? And, any ideas on what I can do to fix it? In case it might help, I've uploaded log files. They capture the import of the .dv file, adding it to a track, and playing through about 30 seconds of the video, the last several seconds of which display as black.

What would cause this behavior? And, any ideas on what I can do to fix it?

**Comment by esasarkama** [comment]
I have the same problem.
With 2.4.0 it takes about 50secs to go blank.
With OpenShot-v2.4.1-1-g152b629-57-656-x86_64.AppImage it goes blank almost immediately.
Preview works fine with 2.3.4.
Attached is output from 2.4.1-1...... 
[openshot-4.1.1-1.log](https://github.com/OpenShot/openshot-qt/files/1495314/openshot-4.1.1-1.log)

**Comment by DylanC** [comment]
@ZahidIsAGit - Try v2.4.1 and report the results. Thanks.

**Comment by ZahidIsAGit** [comment]
@DylanC Same result. New logs attached. Any help would be appreciated.

[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/1503641/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/1503642/openshot-qt.log)

**Comment by DylanC** [comment]
@ZahidIsAGit - Thanks.

**Comment by SquareKnight** [comment]
Same here on 2.4.2 
I have three clips: an intro, the actual video and an outro; all of these are put into one MP4 for Youtube HD @ 60fps. The middle part is ~19mins long, and after about 15 minutes it goes dark, audio continues. The outtro clip is displayed properly.

**Comment by DylanC** [comment]
Marking as confirmed by multiple users.
