### ISSUE TITLE
Feature Request: Frame-accurate video

### ISSUE THREAD

**Issue by OctagonHex** [OpenShot/openshot-qt#1024]
**System Details:**
* Operating System / Distro: Win 7 x64
* OpenShot Version: 2.4.1

I would like to be able to work on videos with single-frame accuracy. This is needed to analyse slow-motion videos and technical editing. To support this, I it would be great if OpenShot would add these features:
- Controls to advance or rewind in single-frame increments (i.e. Go +1 Frame, Go -1 Frame)
- If I zoom into the video-timeline, the maximum zoom is 1 second. Please increase this to at least 0.1 second. It would be great, you zoomed in enough then the frames are displayed as individual pictures.
-Display the current position in frames instead of fractional seconds.
- The cut-tool should snap-in on frame beginnings and ends.

**Comment by DylanC** [comment]
Dup of #891

**Comment by peanutbutterandcrackers** [comment]
You can go +1 frame and -1 frame by using the arrowed keys on your keyboard. But yeah, frame-by-frame mode would be super awesome!
