### ISSUE TITLE
file names query

### ISSUE THREAD

**Issue by Smokeyone** [OpenShot/openshot-qt#1026]
Hello

As a newbie to openshot this might not be an openshot type question but I am sure someone knows the answer - how do you keep a simple record of the video contents - I tried making the file name cover the contents but it's too long - for example a short clip of a moving car - how would you store the location/make of car/car model and engine type - am I missing something here

Many thanks

**Comment by N3WWN** [comment]
I would use directories to categorize the contents and/or include a text file in each project directory that has more detailed information.

In your example of location/make/model/engine, with entries of:

US/Pittsburgh/Ford/F150/8cyl
US/LosAngles/Chevy/Suburban/hybrid
UK/London/Citroen/2CV/petrol

You could make directories like:

```
US
 L Pittsburgh
     L Ford
         L F150
            L 8cyl
               L video29837.mp4
 L LosAngles
     L Chevy
         L Suburban
            L hybrid
               L video98796.mp4
UK
 L London
     L Citroen
         L 2CV
            L petrol
               L video13565.mp4
```

I don't know if that's useful for you or not...

**Comment by Smokeyone** [comment]
Many thanks for the advice - from my understanding of your advice do you mean put each video file in a folder and in the same folder put a text file with the details -
Thanks

**Comment by DylanC** [comment]
@Smokeyone - Yes, that is what he is saying.

**Comment by Smokeyone** [comment]
Many thanks for the help
