### ISSUE TITLE
Any chance getting an Ubuntu 17.10 version in the repository

### ISSUE THREAD

**Issue by dkeats** [OpenShot/openshot-qt#1027]
Ubuntu 17.10

Hello,

Just wondering if there is any chance of getting Ubuntu 17.10 version in the Ubuntu repository ppa:openshot.developers/ppa

Great software, I use it a lot.
THanks
Derek

**Comment by DylanC** [comment]
@dkeats - Sounds like a good idea. Once we have a more polished and very stable version we can focus on this.
