### ISSUE TITLE
smallbin double linked list corrupted

### ISSUE THREAD

**Issue by TimUx** [OpenShot/openshot-qt#1028]
**System Details:**
* Operating System / Distro: Ubuntu 17.04
* OpenShot Version: 2.4.1 PPA + AppImage

Still have Problems with "double linked list corrupted"

[mp3 @ 0x7fbca5367180] max_analyze_duration reached
*** Error in `/tmp/.mount_8M83zM/usr/bin/launch': malloc(): smallbin double linked list corrupted: 0x00007fbca58405e0 ***

It also happens at preview playback, not only on exporting a Video.

Regards Timo

**Comment by DylanC** [comment]
Related to #937. @jonoomph
