### ISSUE TITLE
Impossible to add files - not_allowed

### ISSUE THREAD

**Issue by xerollo** [OpenShot/openshot-qt#1029]
**System Details:**
W7home64 8gb intern gtx660
2.4.1 x64
* _Please attach log files if crash_

Have installed 2.4.1 for w7x64 
impossible to drag and drop or otherwise (import etc) any jpg, avi, mp3 or mp4
when trying to dragdrop under file is a "not allowed"sign
thank you

**Comment by DylanC** [comment]
@xerollo - Do you have a screenshot?

**Comment by xerollo** [comment]
Hi, sending you a screenshot. Cannot show the the "not allowed" sign cause
it appears only under the file if i want to drag to the
mentioned field in OpenShot. Deleted and installed OpenShot a few times, no
success. Tried launch.exe, works fine. Simple fact: no way to get a file to
OpenShot.
Thanks,

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusvrij.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-11-16 12:55 GMT+01:00 DylanC <notifications@github.com>:

**Comment by DylanC** [comment]
@xerollo - Ok no problem. Thanks.

**Comment by DylanC** [comment]
@xerollo - Can you try a daily build please?
