### ISSUE TITLE
Export Crashes at 38%

### ISSUE THREAD

**Issue by ClutchTVFapz** [OpenShot/openshot-qt#1030]
HI. Using OpenShot on a Mac. The export will run smoothly and then just stop at 38% then will be Application Not Responding for like 20 minutes and I have to force quit. Trying to put out content so I need a quick fix if there is one. Thanks.,

**Comment by DylanC** [comment]
@ClutchTVFapz - What version of OpenShot?

**Comment by ClutchTVFapz** [comment]
Latest version that came out for mac v2.4.1

**Comment by DylanC** [comment]
@ClutchTVFapz - What video and audio formats did you use? Also what export profile? I will try on my own Mac.

**Comment by ClutchTVFapz** [comment]
Oh I got it to work again. I just deleted and reinstalled everything.

**Comment by DylanC** [comment]
@ClutchTVFapz - Great news! Thanks.
