### ISSUE TITLE
Putting a video one after the other creates a gap of blank frame

### ISSUE THREAD

**Issue by ezra100** [OpenShot/openshot-qt#1031]
**System Details:**
* Operating System / Distro: Windows 10 64 bit
* OpenShot Version: 2.4.1

**Issue Description and steps to reproduce:**
So I'm trying to merge 2 video files which are actually one video split into 2.
1. Open OpenShot and insert 2 video files
2. Put the 1st one in the time line
3. Put the 2nd video right next to him (the software would show a line between them indicating that they right next to each other).
4. Play the preview

Results: The videos play one after the other but there's a few ms of a blank frame between them.
Expected behavior - the videos should  play smoothly, the 1st frame of the 2nd video right after the last frame of the 1st video.

**Comment by croco3008** [comment]
What was your video frame rate? This could be related with that. I know exactly opposite effect. If you put two images side by side - those images will overlap one frame.

**Comment by ezra100** [comment]
My frame rate is 25, here's the full codec info from VLC.
![image](https://user-images.githubusercontent.com/3751364/32995350-a00f8b60-cd7b-11e7-9ba2-64eff319cbf3.png)

**Comment by peanutbutterandcrackers** [comment]
One thing worth a shot would be to disable snapping (un-click the 'magnet' icon above the timeline) and try pushing the clip as close to the previous clip as possible. I think that might do the trick?

Or else, you might try using an actual transition instead.

Hope that helps.
