### ISSUE TITLE
Openshot Crashes when starting up

### ISSUE THREAD

**Issue by Zeke24** [OpenShot/openshot-qt#1033]
**System Details:**
* Operating System Windows 10
* OpenShot Version: Current
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
I was making a video using photos I took and in the middle of working it crashed. And now it crashes everytime I try to open it. I really want to use this software. You'd think a video editing software that's this old would have that taken care of already.

**Comment by DylanC** [comment]
@Zeke24 - What version of OpenShot?

**Comment by DylanC** [comment]
@Zeke24 - Maybe delete your preferences folder (openshot_qt) and delete backup.osp

**Comment by Koko321** [comment]
Hi, I'm new here, and had the same problem, but removing of the openshot_qt map has solved the problem for me ! Thanks !

**Comment by DylanC** [comment]
@Koko321 - Excellent. Thanks for letting us know.

**Comment by Nogotogon** [comment]
I can not find the openshot_qt or backup.osp, could someone tell me where they save by default?

**Comment by peanutbutterandcrackers** [comment]
In you home folder (the one that contains your 'My Documents' etc), there should be one called `.openshot_qt`. perhaps there? Hoepfully?
