### ISSUE TITLE
Ongoing Error For My Windows 10 - Cx_freeze

### ISSUE THREAD

**Issue by IAmSofaKingStewPid** [OpenShot/openshot-qt#1035]
Windows 10 Home 64 bit
Intel Core 2 Quad Q6600
8GB DDR2 RAM
250GB HDD

Windows 10 Home 64 bit

* OpenShot Version:2.4.1

*
![error ove](https://user-images.githubusercontent.com/33672853/32810694-2424e0be-c96a-11e7-80e2-08ec5e4c6647.PNG)

This has been ongoing for about a year now, tried troubleshooting myself. It ALWAYS crashes with this error above, everytime I attempt to launch it from my main system.  Ive reinstalled it, updated it, uninstalled it, moved it, you name it. I installed it on a second Windows 10 system, and it ran fine. I copied those working files to a flash drive. tried to run it on my main system...NOPE! Right off the bat it crashed when launched, with the same error. I instantly plugged it into the secondary system, and it worked like nothing happened at all. I do wish for a reply to my email if this requires any additional information to assist, and for troubleshooting help from the great and wise creator of Openshot (lol).

ronjlawson3@gmail.com

**Comment by DylanC** [comment]
@IAmSofaKingStewPid - I would recommend to delete your settings folder.

**Comment by IAmSofaKingStewPid** [comment]
Honestly I think my system is rejecting me. xD

**Comment by DylanC** [comment]
@IAmSofaKingStewPid - Hmm.. Possibly. :) Not sure what else you could try.

**Comment by IAmSofaKingStewPid** [comment]
well im guessing i have the most unique error ever....not sure if i should
be proud of it or not...

**Comment by DylanC** [comment]
@IAmSofaKingStewPid - Maybe try to delete backup.osp. I think it keeps trying to open your backup.

**Comment by IAmSofaKingStewPid** [comment]
attempted, and yet failed again...sorry...

**Comment by peanutbutterandcrackers** [comment]
Hey there! 

It has been reported that this issue affects only certain users in the computer, and thus, it is a user-related issue. Some report that the admin could run OpenShot while the standard user could not, and vice-versa. 

A user recently reported that he [resolved](https://github.com/OpenShot/openshot-qt/issues/1244#issuecomment-365036861) this issue by copying openshot.settings file from the standard user (or whichever user can use OpenShot in your windows machine) to the admin user (or whichever user can NOT use OpenShot). He also recommends having a backup made of the openshot.settings file.

Please note that the solution is edited in at the very end of the comment.

Hope this helps. :)
All the very best!

**Comment by laellsr** [comment]
Hello, guys!

I solved the problem by deleting the following directory:

_> C:\Users\**yourUSER**\.openshot_qt_

**Then just open the program and enjoy! :)**

**Comment by peanutbutterandcrackers** [comment]
@laellsr - Thank you for sharing. I hope this helps others with the same issue too. :)

**Comment by EBW1** [comment]
It still happens for me because i totally delete that file from recycling bin, then i open OpenShot, then it pops back up. HELP!!!

**Comment by EBW1** [comment]
Thank you peanutbutterandcrackers, the running as administrator works!!

Thank You!!!

**Comment by laellsr** [comment]
@peanutbutterandcrackers 

OpenShot worked fine, so any night after months that same problem happened to me :'(

1. Looking for solutions I found that another user solved the problem by installing Windows again.

I realized that uninstalling OpenShot did not solve the problem, it was necessary to clean the system.

2. Then I thought that all the program logs were not being deleted. Some configuration file (and customization) was causing problems.

3. Check mate. Date files remain on every user of the system even after uninstalling the program.

4. I simply deleted my user's OpenShot date folder :)

**_Thanks to all of you who make OpenShot a better open source editor every day! =D_**

**Comment by peanutbutterandcrackers** [comment]
@laellsr - Awesome! I'm glad that it has worked for you. You're welcome. We're just doing our part.

However, I have a question. When you say "OpenShot date folder", what exactly do you mean? o.O Is it the .openshot_qt folder (as many have reported the issue being resolved once this folder was deleted) or is it sth else? I'd like to know, for future references. Thanks!

Hope you make awesome videos with OpenShot!

**Comment by peanutbutterandcrackers** [comment]
Please do look forward to v2.4.2. This issue has been put on the list of the 'critical bugs to be fixed' for the release. OpenShot should finally work quite well on Windows Machines with v2.4.2. Please, do however continue to support OpenShot. Perhaps test the latest [daily build](https://github.com/OpenShot/openshot-qt/releases/tag/daily) if you have the time and report the issues as you encounter them. Thanks!

**Comment by laellsr** [comment]
@peanutbutterandcrackers 

Yes! Sorry for taking so long to respond. I did not see the message in my email.

I believe that this folder is from the OpenShot data cache, it specifies for each user of the system. This folder is neither excluded nor refreshed when you reinstall the program.

Some intervention on the files in this folder causes an error. This is a tip for programmers.

I have not yet studied Python, just C, so I do not know what I can help ...

**Comment by peanutbutterandcrackers** [comment]
@laellsr - Yes. This issue has been brought to Mr. Thomas's attention. Hopefully, this will be resolved completely by v2.4.2. Please do keep on supporting OpenShot!
