### ISSUE TITLE
Huge memory consumption during export

### ISSUE THREAD

**Issue by TataMata** [OpenShot/openshot-qt#1039]
**System Details:** HP Z420 with 32Gb RAM
* Operating System / Distro: Arch Linux 4.13.12-1-ARCH 
* OpenShot Version: 2.4.0 or git version

I have downloaded some mp3 files from http://freemusicarchive.org/ (any of http://freemusicarchive.org/search/?quicksearch=Golden+Duck+Orchestra) to use it as the background music.
When I tried to export video I have noticed constant memory growth to the point that all my memory was consumed and the program crashed. I have experimented  a bit and discovered that it is easy reproducible using single mp3 file, but not with some other mp3 files I have. These mp3 files have png file attached as the cover photo and this png seems to cause the memory growth.
I used EasyTag to remove png images from mp3 files and now everything works fine.

So, this report might help some developers to save some time when hit this problem.

**Comment by DylanC** [comment]
@TataMata - Can you try this with v2.4.1? The v2.4.0 release is out of date now.

**Comment by TataMata** [comment]
I have experimented with git version either. I think the problem is with libopenshot. I even tried to dig into the source code, but I didn't seems confident enough to mess with the allocation/deallocation part. Even this is C++ code and this things should be managed using RAII pattern, things aren't as clean as they should be. At first I suspected on the audio writing part of the library - FFmpegWriter::write_audio_packets method, but I couldn't spot any problem there. Then I spotted that mp3 file has video-like icon in the project view, and some other audio files has note icon and I get suspicious about the file content. When I deleted this png cover art image from the mp3, everything worked without any memory leak. Now I see the the memory leak even during clip preview.
Maybe I'm wrong, but it seems to me that this mp3 file is somehow recognized as video file, and the leak occurs when the video should be processed and it is missing. I'll try to look again into the source and play with the log output and see if I could come with some meaningful conclusion.

**Comment by TataMata** [comment]
Another observation.
I have added some debug output into FFMpegReader class and this is what I found:

FFmpegReader::Open: found codec -  (png=1.0000, PNG (Portable Network Graphics) image=1.0000)
FFmpegReader::UpdateVideoInfo (info.duration=231.6832, info.video_length=5560.0000, info.file_size=13875334.0000, info.width=1801.0000, info.height=1801.0000, info.has_single_image=0.0000)

This log appears after I add single mp3 file to the project. File is: http://freemusicarchive.org/music/Golden_Duck_Orchestra/Golden_Duck_Orchestra_1st_EP/Golden_Duck_Orchestra_-_04_-_Dynamite
When i start preview of this file, memory starts to leak.

**Comment by TataMata** [comment]
I'm, sorry, in the previous post i didn't specified my debug interventions:
I have added code to the FFMpegReader.cpp at the line 159:
`ZmqLogger::Instance()->AppendDebugMethod("FFmpegReader::Open: found codec - ", pCodec->name, 1, pCodec->long_name, 1, "", -1, "", -1, "", -1, "", -1);`

and at the line 393:
`ZmqLogger::Instance()->AppendDebugMethod("FFmpegReader::UpdateVideoInfo", "info.duration", info.duration, "info.video_length", info.video_length, "info.file_size", info.file_size, "info.width", info.width, "info.height", info.height, "info.has_single_image", info.has_single_image);`

**Comment by DylanC** [comment]
@TataMata - Thanks for the info. Very helpful for the devs.

**Comment by HFTrader** [comment]
I can confirm this only works with MP3 (with a single image). My solution has been to convert to OGG using Audacity prior to importing into the project. Otherwise a 5 min video eats +60GB

**Comment by DylanC** [comment]
@TataMata - Try v2.4.3 and let us know if you still have a problem.

**Comment by ezonakiusagi** [comment]
i'm also here to confirm that export eats up all my ram then freezes my system until the Linux kernel kills Openshot. This is on a system with 32GB and another with 64GB of RAM. seems way too excessive...
