### ISSUE TITLE
Rotate then transform

### ISSUE THREAD

**Issue by moneill4068** [OpenShot/openshot-qt#1040]
Whenever I rotate an image within a video then try to transform it to get it to the right position the effect and the transformation icons disappear.  Do I have to transform it then rotate it?  If so, any advice on ensuring the rotated image was moved to the correct location?   Thank you.

**Comment by DylanC** [comment]
@moneill4068 - Do you want to rotate while keeping the center in the same position?

**Comment by moneill4068** [comment]
Ok, here is the situation.  I have a downloaded special effect that is a fireball going from left to right.  I need to have that same effect also go from right to left.  So I load the image and rotate 180degrees so it is now heading in the right direction.  I then attempt to hit transform to drag the fireball so it leaves from the correct position.  I click on transform and I get the icons with the boxes in the corner and the circle in the center.  I then try to drag it to the correct location and the fireball and the transform circle/boxes disappear.

**Comment by moneill4068** [comment]
The original effect (going from left to right) can be transformed and moved easily.

**Comment by moneill4068** [comment]
https://www.youtube.com/watch?v=cmGcOgdpLYk&app=desktop

**Comment by DylanC** [comment]
@moneill4068 - Thanks.

**Comment by peanutbutterandcrackers** [comment]
@moneill4068 - Hey! This is a very easy issue to resolve! You should use the 'Location X' and 'Location Y' parameters in the special effect's clip-properties. The transform tool is apparently a new addition and it isn't that mature yet. And also, it's just a GUI wrapped around the actual parameter-setting, which is what makes openshot such a beloved video editor.

So, here's what you should do: After you rotate that thing, go to it's properties and drag the handle of the 'Location X' parameter. It'll move the clip along x-axis. Leave the 'Location Parameter' to 0. [I kinda' nicked it (screenshot) by a 0.01. 😆 ]
![screenshot from 2018-02-12 16 22 14](https://user-images.githubusercontent.com/26764547/36093021-69effeec-1011-11e8-9fc2-dd23647b07c1.png)


I have actually been able to do some pretty neat stuff using the parameters themselves. And, frankly, I think, once a person has actually mastered the use of keyframes and parameters, transform tool is for sissies. You'll understand that too, someday. No offense though. :D 

I hope that helps.
P. S: I'm super glad that you actually made a video. That is quality issue-reporting. Please do continue to submit such quality issues. You're one of the best reporters here. :)

P. P. S: Here are some links to master keyframes and parameters:
https://www.youtube.com/watch?v=nEyrC1v-M1s
https://www.youtube.com/watch?v=mgi4esWA84M
https://www.youtube.com/watch?v=P3zIprwr1rk (Made by Mr. Jonathan Thomas, himself!)
https://www.openshot.org/static/files/user-guide/animation.html#
https://www.openshot.org/static/files/user-guide/clips.html#properties
[you'll catch 'em all, once you understand these. Good luck!]

**Comment by peanutbutterandcrackers** [comment]
@DylanC - I suggest we keep this issue open, however, to further improve the transform tool. Perhaps an 'enhancement' label would be suited? Or, better yet, you could create a new issue yourself that references this one and have it marked 'enhancement'?

Sorry if I'm being a little nosey. :D

**Comment by peanutbutterandcrackers** [comment]
@DylanC - Hey! This thing: https://github.com/blog/2471-introducing-team-discussions I'm not sure if it'll work for public discussions, though. TL;DR, TBH. 😄

**Comment by rexdk** [comment]
I think this issue was reported as bug #769 and closed with no action. And it was then reported as bug #991 and closed with no action. While I agree it would be an enhancement to have the transform tool work correctly, surely the fact that the tool does not work correctly makes this technically a bug, not an enhancement request.
I've had the same issue June 2020  - 2.5.1 Win10.
https://www.reddit.com/r/OpenShot/comments/glc7nt/transform_tool_too_sensitive/
Feels like a bug to me - I found the tool useless in my situation.

**Comment by ctsdownloads** [comment]
Marking resolved as of #3366

**Comment by rexdk** [comment]
@ctsdownloads This is not resolved in the daily build of 28Jul20 on my Win10 system - can the issue be opened again please?
