### ISSUE TITLE
Transition timing doesn't match timeline

### ISSUE THREAD

**Issue by N3WWN** [OpenShot/openshot-qt#1041]
OpenShot 2.4.1

I noticed this on earlier versions and it's still present in 2.4.1, not to mention visible in the videos just published by @jonoomph ...

Transitions take 1/2 as long as they should;  The transition is complete exactly 1/2 way through the duration of the transition.

This is visible here:  https://youtu.be/VE6awGSr22Q?t=6m30s  

If you adjust the YouTube playback speed to 0.25, we enter the transition about 06:18 and the transition is visibly complete about 08:07, but the blue box which represents the transition extends to about 10:03.

To replicate:

- New project with profile of "HD 1080p 60 fps" (my default profile)
- Import a clip
 I used this 25.14s long video: https://videos.pexels.com/videos/aerial-shot-of-mountain-and-ocean-1469
- Drag the clip to the start of the timeline
- Zoom in (to the 2s value)
- Drag the clip to the start of the timeline again, overlapping the first clip by at least 2 sec
 I placed the 2nd clip at about 22s, giving about 3s of overlap.
- Click on the transition and note the duration in the properties
 Mine is 3.20s
- Move the playhead to 22s and step through, frame by frame, until you visibly see that the transition is complete
 For me, it was at 23:49
- Note that the blue box representing the transition continues until about 25:14, but no transition is visible during this 2nd half

I think this may be related to some of the other issues regarding frame markers moving if profiles change, but I'm not sure, so I'm creating a new issue to address it specifically.

Thanks!

**Comment by DylanC** [comment]
Dup of #519

**Comment by DylanC** [comment]
@N3WWN - Can you try v2.4.3 and let us know if this bug is still present?
