### ISSUE TITLE
4K export on OS X

### ISSUE THREAD

**Issue by osvtonosx** [OpenShot/openshot-qt#1042]
**System Details:**
* Operating System / Distro: ? OS X 10.5
* OpenShot Version: 2.4.1
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
Hi,
 sorry for the question: is there a special way to export 4K videos ?
because Youtube isn't able to convert a 4K uhd 2160p exported video

Thanks

**Comment by osvtonosx** [comment]
sorry, it could be I've found what's wrong here.
I try and give feedback.

**Comment by DylanC** [comment]
@osvtonosx - No problem, What is the feedback?

**Comment by osvtonosx** [comment]
sorry for the late response.
I could do an 4K export after changing the prefs to get the correct " dimensions" on O S V E launch..

Now, I'm looking for the crop function ...

Thanks
![howtocrop](https://user-images.githubusercontent.com/33726263/33184626-d317295a-d07d-11e7-8202-ed85bd38bfff.png)

**Comment by DylanC** [comment]
@osvtonosx - Great news! Thanks.
