### ISSUE TITLE
Right-click cuts when razor tool enabled

### ISSUE THREAD

**Issue by xenotropic** [OpenShot/openshot-qt#1044]
I would expect a right-lick to just open the context menu always. Left click would engage a selected action like razor tool. This is Win7, v. 2.4.1.

**Comment by DylanC** [comment]
@xenotropic - Usually I use left click with the razor tool. I didn't even know you could do a right click with it. :)

**Comment by xenotropic** [comment]
It helps to have testers who don't know what they are supposed to do :^) 

I used left click to make a cut, and then I wanted to get a context menu to delete the offcut, but instead I got another cut. It was also confusing as to what was happening, because it does both context menu and the cut. A context menu partially appeared; then it does the cut, which take a few seconds (which would be fine if that was what you were expecting, but if not you're like "why did this freeze") and then the second cut completes and the context menu appears. After doing it a few times I figured out what the problem was, but I could imagine a user who is not familiar with software being like "gah this this doesn't work". Hopefully it's an easy fix, to make the razor feature wait for a left click event instead of any click.

**Comment by DylanC** [comment]
@xenotropic - It would likely be an easy fix. I bet its just a matter of finding the time to get it in. First I think any major issues will be worked on first. (anything causing crashes)  Afterwards we can tackle issues like this one and add some extra polish.

**Comment by ferdnyc** [comment]
Despite @xenotropic 's cuntiness, this is now fixed. (Though, right-click won't open the menu, it will simply do nothing.)

Think of the very, very long delay as punishment.
