### ISSUE TITLE
launch.exe hangs 2.4.0 even after uninstall with registry clean

### ISSUE THREAD

**Issue by jabowery** [OpenShot/openshot-qt#1045]
**System Details:**
![capture](https://user-images.githubusercontent.com/57646/32913267-6d78aaf2-cad7-11e7-9e98-96181e61867d.PNG)

* Operating System / Distro: ?
* OpenShot Version: ?
2.4.0

* _Please attach log files if crash_
It just hangs forever "Not Responding".

**Issue Description and steps to reproduce:**

Install 2.4.0
Run it once.
Close.
Run it again.
It hangs with windows "Video Preview" "Transitions" and "Project Files"
Uninstall.
Reinstall.
Run it once.
Close.
Run it again.
It hangs the same way.
Uninstall.
regedit and delete everything referencing "openshot".
Reinstall.
Run it again.
It hangs again the same way.

**Comment by jabowery** [comment]
The problem went away after uninstalling 2.4.0 (no registry cleaning) I downloaded and installed 2.4.1.

I can do video editing again -- for now.

**Comment by DylanC** [comment]
@jabowery - Great news. Thanks.
