### ISSUE TITLE
BITCOIN DONATIONISSUE FIX IT

### ISSUE THREAD

**Issue by Pansare** [OpenShot/openshot-qt#1046]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

**Comment by Pansare** [comment]
Dear Team Member,
         i am Pratap from India i can can't donate you bitcoin donation donate time (500 
Our server has encountered an unexpected error. We have automatically been notified of this error, and will fix it as soon as possible. We apologize for any inconvenience this has caused.) Error pls fix it this problem.

**Comment by jonoomph** [comment]
Sorry about that. It's fixed now. =)
