### ISSUE TITLE
Video Export problem

### ISSUE THREAD

**Issue by Ben2112** [OpenShot/openshot-qt#1047]
Ich bin neu bei openshot und mir stellt sich folgendes Problem:
nachdem ich ein Projekt mit mehreren zusammengeschnittenen Videos exportiere, fehlt auf dem exportierten Video der Ton. Video ist ok.
Was mache ich falsch?

**Comment by DylanC** [comment]
EN:

I am new to openshot and I have the following problem:
After I export a project with several edited videos, the audio is missing on the exported video. Video is ok.
What am I doing wrong?

**Comment by croco3008** [comment]
To track down your problem developers will need to know:
1. Your OpenShot version
2. Your operating system
3. Does audio work in preview mode?
4. What export profile you tried? Does some other format will work ok?

**Comment by peanutbutterandcrackers** [comment]
@Ben2112 - Perhaps try setting the 'target' in the export dialogue to something else. I recommend 'OGG(vorbis/theora)'. It just might be that the default audio encoder is not working properly. It could very well also be that the media player that you are using can't decode the audio. Try [VLC](https://www.videolan.org/vlc/) instead. If you do not have the project till now but still have the exported video, you could try re-encoding it into another format using something like [Handbrake](https://handbrake.fr/). Please note that this might not work if the audio encoder didn't do the job while exporting and no audio has been exported at all.

Hope this helps.

Fig: Changing the 'target' during export.
![screenshot from 2018-02-12 07 20 43](https://user-images.githubusercontent.com/26764547/36090895-1ac00616-100a-11e8-8ac5-9e5136476ac1.png)

P. S: Please do make sure that you are also using the latest version of OpenShot (v 2.4.1) and not any older ones.

Good luck!

**Comment by DylanC** [comment]
@Ben2112 Can you try v2.4.2 and let us know if you have success? A change was put in for the audio issues.
