### ISSUE TITLE
No audio in final video

### ISSUE THREAD

**Issue by JFeinstein** [OpenShot/openshot-qt#1048]
**System Details:**
* Operating System / Distro: Windows 7 Enterprise, Service Pack 1
* OpenShot Version: ?  Version 2.4.1
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**  I have spliced a video that includes audio. When I export the final video it does not include audio. What am I missing?

**Comment by DylanC** [comment]
@JFeinstein - What video format did you use?

**Comment by peanutbutterandcrackers** [comment]
@JFeinstein - Perpahs try a different 'Target' while exporting and see if that works? I suggest 'OGG(theora/vorbis)'. (It might just be an encoder issue.) Like so:
![screenshot from 2018-02-12 07 20 43](https://user-images.githubusercontent.com/26764547/36081377-30bd3234-0fc6-11e8-9d26-c9f7483c98ca.png)
Hope that helps! Good luck!

**Comment by DylanC** [comment]
Closing question as answered. Thanks!
