### ISSUE TITLE
[new feature] two videos a line from left to right

### ISSUE THREAD

**Issue by fulgorit** [OpenShot/openshot-qt#1050]
[new feature] two videos one video above another one a line from left to right with at left one video and at right another video the finished result is at left of the line

**Comment by peanutbutterandcrackers** [comment]
@fulgorit - Although I am not the one to code new features, could you please explain this feature request further. I am unable to grasp this. Perhaps a diagram? Screenshot? I only ask because this interests me.

**Comment by DylanC** [comment]
@peanutbutterandcrackers - I think he is talking about a split screen type of feature. Where you could play one video track on the left side and one video track on the right.

**Comment by peanutbutterandcrackers** [comment]
@DylanC - Ah! I see! I so wish that feature too!

[Although, even right now, with the new colored bar effect implemented in the daily builds, along with the shift effect, I'm pretty sure I could mix the two effects with chroma keying to produce a split screen effect.]

But still. That feature would be super cool!

**Comment by peanutbutterandcrackers** [comment]
@DylanC - And, let's have that split-screen effect not be just a line from top to bottom; but let's have the possibility for an anime-style split effect too!!!

**Comment by DylanC** [comment]
@peanutbutterandcrackers - Sounds like a not so fun thing to develop but a cool feature though! :)

**Comment by peanutbutterandcrackers** [comment]
@DylanC - I know. But still. All we have to do is create an enthusiastic community of volunteers around OpenShot.

**Comment by N3WWN** [comment]
How about using the existing features in 2.4.x? 😉   

Horizontal (side-by-side):
Set `Layout` -> `1/4 Size - Center` on both clips, then adjust the "left" clip's `Location X` property to `-0.25` and adjust the "right" clip's `Location X` property to `0.25`.

Vertical (one on top of the other):
Set `Layout` -> `1/4 Size - Center` on both clips, then adjust the "top" clip's `Location Y` property to `-0.25` and adjust the "bottom" clip's `Location Y` property to `0.25`.

If a line is needed between the two clips, you could import a static image, scaled appropriately and placed on a higher layer in the timeline, much like I discussed in https://github.com/OpenShot/openshot-qt/issues/1077#issuecomment-347565890

**Comment by DylanC** [comment]
@N3WWN - Nice! Maybe either we need to wrap up this functionality in an easy to use way (more dev effort) or just have documentation on how to do this via the description above. (no dev effort)

**Comment by peanutbutterandcrackers** [comment]
@N3WWN and @DylanC the 'Guardians of the GitHub' for OpenShot.
Now if only I could see you two submitting patches, you'll probably join Captain @jonoomph the first avenger to become The Avengers. I hope that day is coming soon too.

[Yeah. I have no life. Please send help] 😆 🤣

**Comment by DylanC** [comment]
@peanutbutterandcrackers - I did submit one already. 🥇

**Comment by peanutbutterandcrackers** [comment]
@DylanC - That'll count as a cameo. 😃
