### ISSUE TITLE
Export video produces popping sound in preview & exported final file

### ISSUE THREAD

**Issue by rmwebber** [OpenShot/openshot-qt#1052]
**System Details:**
* Operating System / Distro: Windows 7 x64
* OpenShot Version: 2.4.1
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

Export either as DVD video or 720p 30fps mp4. FLAC audio track makes a popping sound during playback either in preview or in exported file. FLAC track is 32 bit, 44.1 khz, mono.

**Comment by croco3008** [comment]
It may be related with audio format. Could you try disabling audio and use some other audio source as (mp3) reference? If that works then developers will need your sample. For workaround I will recommend to open your videofile in audacity and export it to wav. Then back into openshot, disable audio in movie clip and import wav.

**Comment by rmwebber** [comment]
More data: The audio has been tested with both FLAC & MP3 at both 96khz and 44.1khz in both stereo and mono. This is an extremely long audio file (43 minutes of continuous music with videos, stills and titles over it, including transitions and effects. I will dump the FLAC file down to 44.1khz mono wav and attempt a 720p 30fps render. The last time I tried to render, I not only got the popping, but also very heavy video stuttering as well. CPU is Core i3-2310M w/8GB RAM and 256GB SSD.

**Comment by rmwebber** [comment]
WAV 44.1Khz mono. No change. When rendered with no video, no popping. When rendered with ANY video, ANY transition, it is like a slow bowl of rice crispies. This is at any resolution for the export.

The only thing that has me using OpenShot 2.4 is that I contributed to the kickstarter campaign, and its transition library which includes the ability to user-define grayscale images as transitions. That, and I have 30 hours into my project and I'm running out of time to deliver.
