### ISSUE TITLE
 How do I open the .osp file?

### ISSUE THREAD

**Issue by Viniciusantunesarruda** [OpenShot/openshot-qt#1054]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

Estou com dificuldade em abrir o arquivo em .osp

**Comment by DylanC** [comment]
EN:
I'm having trouble opening the .osp file

**Comment by DylanC** [comment]
@Viniciusantunesarruda 

If you have the file associated with OpenShot you can double click it or you can also open it from inside OpenShot.
