### ISSUE TITLE
Odd glitch (Possibly user error)

### ISSUE THREAD

**Issue by Lando1** [OpenShot/openshot-qt#1055]
Operating System / Distro: Windows 10
OpenShot Version: 2.4.0-dev3

I started using open shot and it was working well but know when i use open shot i get only the tracks as seen in the screen shot. I don t know is=f this a bug or just me being stupid.
Thanks for any help! 

Screen shot: (https://i.gyazo.com/25f1ab5fbc1fbef336dc4cceeddc0ee4.png)

**Comment by N3WWN** [comment]
Can you try resetting your screen layout with:

View -> Views -> Simple View

?

**Comment by DylanC** [comment]
@Lando1 - Follow the suggestion above.
