### ISSUE TITLE
No Sound in my exported video? Why?

### ISSUE THREAD

**Issue by JaneO52** [OpenShot/openshot-qt#1062]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

When I export the video there is no sound, but in the preview it plays perfectly. Help!!

**Comment by DylanC** [comment]
@JaneO52 - What audio format did you use?

**Comment by DylanC** [comment]
@JaneO52 - Also what version of OpenShot?

**Comment by JaneO52** [comment]
It was an imported video with audio already - I was just splicing.
The version is 2.4.1
Thanks!


Jane O'Malley| Coldwell Banker Residential Brokerage Winnetka | Broker

P 224-216-8140 | F 781-609-0063 | jane.omalley@cbexchange.com | www.janeomalley.cbintouch.com<http://www.janeomalley.cbintouch.com>




________________________________

**Comment by DylanC** [comment]
@JaneO52 - Thanks for the info.

**Comment by aluit** [comment]
I have the same issue, also with video that already has audio. I only solved the problem by choosing a different output format (mpeg4 instead of h.264).

**Comment by peanutbutterandcrackers** [comment]
@JaneO52 and @aluit - Could you both please try having a different 'Target' while exporting the project. I recommend 'OGG(vorbis/theora)'. Like so:
![screenshot from 2018-02-12 07 20 43](https://user-images.githubusercontent.com/26764547/36081431-ba8ef858-0fc6-11e8-82b7-fe32b5ffab4b.png)

The reason why audio is not there in the final video could be an issue with the encoder and thus, changing it should make a difference.

Or, it could also very well be that the media player that you used doesn't support or can not decode the audio encoder used. Could you both please try giving [VLC](https://www.videolan.org/vlc/) a shot instead, please?

Hope that helps. All the very best! 👍

**Comment by DylanC** [comment]
Closing question as answered. Thanks!
