### ISSUE TITLE
how to add blender path in open shot

### ISSUE THREAD

**Issue by yogsy7h** [OpenShot/openshot-qt#1063]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

**Comment by DylanC** [comment]
@yogsy7h - Find the executable on your system and copy/paste the full path in to OpenShot preferences.

**Comment by DylanC** [comment]
@yogsy7h - If you use Windows it might be this path:

C:\Program Files\Blender Foundation\Blender\blender.exe

**Comment by Witten-1** [comment]
Where are the Openshot- preferences ????
There is no menu-button for this.....
And in the file  "default_settings" is no possibility to add the path to blender...

Please tell m the correct way...

Thanks
