### ISSUE TITLE
OpenShot Unresponsive when importing mp4 video

### ISSUE THREAD

**Issue by victordmontero** [OpenShot/openshot-qt#1064]
Hi, whenever i try to import a mp4 video OpenShot freezes. It gets totally unresponsive.
- System Details:
    - OS: Windows 10 Pro
     - OpenShot Version: 2.4.1
![image](https://user-images.githubusercontent.com/17789558/33177564-6e5df79e-d039-11e7-809e-004e6082be52.png)

PD: I'm running OpenShot on VMware

**Comment by DylanC** [comment]
@victordmontero - I'm sure running on VMware is not a good idea. Importing files normally works fine.

**Comment by DylanC** [comment]
@victordmontero - I would suggest to try on a normal PC and not a VM.
