### ISSUE TITLE
tutorial window stuck under windows bar , can't reach the next button

### ISSUE THREAD

**Issue by DrMacConKey** [OpenShot/openshot-qt#1065]
**System Details: windows 10 machin lenovo z5070 i5 2GB invidia 64 bit system 
* Windows 10
* OpenShot Version: 2.4.1
* _Please attach log files if crash_
![bug openshot](https://user-images.githubusercontent.com/28638347/33191383-7fcbf638-d0c1-11e7-93a1-a44ce47840ad.JPG)

**Issue Description and steps to reproduce:**

tutorial window stuck under windows bar , can't reach the next buttom even when maxmize the main application

**Comment by DylanC** [comment]
Dup of #977

**Comment by peanutbutterandcrackers** [comment]
Hey there, a fix to this issue was just merged into the source tree and is ready for testing. Could you please try out the [latest daily builds](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914) and see if this has been resolved? Thanks!
