### ISSUE TITLE
OpenShot-v2.4.1-x86_64.AppImage fails to start

### ISSUE THREAD

**Issue by damarlin** [OpenShot/openshot-qt#1066]
**System Details:**
* Operating System / Distro: ?
   Red Hat Enterprise Linux Workstation release 7.4 (Maipo)

* OpenShot Version: ?
   OpenShot-v2.4.1-x86_64.AppImage

* _Please attach log files if crash_

[openshot-dump.txt](https://github.com/OpenShot/openshot-qt/files/1500381/openshot-dump.txt)

**Issue Description and steps to reproduce:**
  Downloaded Linux (64-bit AppImage) v2.4.1
  make image executable and copy to /opt/openshot/OpenShot-v2.4.1-x86_64.AppImage
  run executable from command line:
    $ /opt/openshot/OpenShot-v2.4.1-x86_64.AppImage

**Comment by DylanC** [comment]
@damarlin - Why did you copy it to that location? I think the idea with AppImage is to use from a normal directory.

**Comment by DylanC** [comment]
@damarlin - Try installing pango. This seems to be the solution here.

**Comment by damarlin** [comment]
I also tried running from my home directory, but got the same results.  Pango is already installed:

$ rpm -q pango
pango-1.40.4-1.el7.x86_64

$ ls -l /lib64/libpangoft*
lrwxrwxrwx. 1 root root    27 Oct 19 21:37 /lib64/libpangoft2-1.0.so.0 -> libpangoft2-1.0.so.0.4000.4
-rwxr-xr-x. 1 root root 92272 Mar  9  2017 /lib64/libpangoft2-1.0.so.0.4000.4

$ nm --dynamic /lib64/libpangoft2-1.0.so.0.4000.4 | grep hb_buffer_set_cluster
                 U hb_buffer_set_cluster_level

but I still get the error:

/tmp/.mount_5pmipC/usr/bin/launch: symbol lookup error: /lib64/libpangoft2-1.0.so.0: undefined symbol: hb_buffer_set_cluster_level

**Comment by DylanC** [comment]
@damarlin - Hmm.. not sure what else we could try. I don't have Red Hat to test this.
