### ISSUE TITLE
Invalid files on import - GoPro 6

### ISSUE THREAD

**Issue by gotchaapps** [OpenShot/openshot-qt#1067]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

I just downloaded openshot with the intent to edit some GoPro 6 video files. They are mp4 files shot at 4K, 60 fps. It says they are invalid files and won't import them. Any ideas why it won't import the files, they will play on windows movie viewer and VLC.

**Comment by DylanC** [comment]
@gotchaapps - What version of OpenShot are you using? What Operating System?

**Comment by gotchaapps** [comment]
I am using version 2.4.1 with Windows 10.

**Comment by DylanC** [comment]
@gotchaapps  - Thanks.

**Comment by mmistretta** [comment]
I am seeing a similar issue.  It won't import any MOV or mp4 video files.  We shot MOV video on an iphone and I tried converting them to mp4 and neither will import.  Both play fine on my machine which is Fedora.  I am also using 2.4.1.

**Comment by DylanC** [comment]
@gotchaapps - I think this was due to us not handling the higher framerates. Can you try a daily build? I think we have a fix in there for this issue.

**Comment by gotchaapps** [comment]
Thanks so much for the info. 
Guy
