### ISSUE TITLE
YouTube won't accept OSP file.

### ISSUE THREAD

**Issue by corboranth** [OpenShot/openshot-qt#1068]
I made a video, it's edited and everything but I can not get it on YouTube. I save it to my computer however YT does not accept OSP files. What should I do?

**Comment by gurjyot** [comment]
Is OSP the only format in which OpenShot export the final video?

**Comment by DylanC** [comment]
@corboranth -  OSP is just an OpenShot project file. You must use the Export feature to create a video for uploading.
