### ISSUE TITLE
I can't run it.

### ISSUE THREAD

**Issue by AbdullZ7** [OpenShot/openshot-qt#107]
I got this Message every time I tried to open "OpenShot"
![launch_2016-02-21_02-26-56](https://cloud.githubusercontent.com/assets/5797362/13199860/c36e3820-d842-11e5-8d2d-5e01cc1003f5.png)

**Comment by DerGenaue** [comment]
Possibly an encoding error (userdirectory)?

**Comment by tinman321** [comment]
Same problem with Windows 8.1 for Russian

**Comment by jonoomph** [comment]
I created a similar Russian named folder, and added it to the list of folders we are attempting to create on launch, to trigger the error you are getting (in the info.py file... which is where this error is coming from), and everything worked fine. Can you confirm this is still happening on 2.0.6?
