### ISSUE TITLE
MP4 and WEBM totally unusable Openshot 2.4.1

### ISSUE THREAD

**Issue by clockworkpc** [OpenShot/openshot-qt#1072]
Update:

Perhaps Openshot on my system has some problem with the Vorbis codec?  (See comment below)

I think related to #993 

**System Details:**
* Ubuntu 16.04
* OpenShot Version: 2.4.1
* _Please attach log files if crash_
No crash

There seem to be two openshot-qt packages installed, but I installed it only once from a newly added PPA.

![screenshot from 2017-11-26 14-38-10](https://user-images.githubusercontent.com/9858440/33236916-737600ca-d2b7-11e7-8564-a98ede87b61d.png)

**Issue Description and steps to reproduce:**
Neither WEBM nor MP4 plays at all in Openshot 2.4.1.
When I export a snippet of the video in either format it simply freezes in the first second.

I demonstrate this in my video:
https://youtu.be/QdIchJCUmsk

**Comment by clockworkpc** [comment]
UPDATE:
No problems with the following MKV file:
![screenshot from 2017-11-27 14-33-35](https://user-images.githubusercontent.com/9858440/33249684-082ebd2e-d380-11e7-850d-78d4c95a20fd.png)

However, total non-performance with the following WEBM:
![screenshot from 2017-11-27 14-34-50](https://user-images.githubusercontent.com/9858440/33249712-26275bce-d380-11e7-8e73-737f0bb4ea29.png)

**Comment by jonoomph** [comment]
Can you please try and reproduce this with the AppImage? I'm curious if the problem is with a dependency, or with libopenshot. Thanks!

**Comment by clockworkpc** [comment]
@jonoomph Tested it on AppImage and there is definitely a difference!
On Openshot from PPA:
- WEBM with VP8 **not working**
- MP4 with H264 works!

On Openshot from AppImage
- WEBM with VP8 works!
- MP4 with H264 works!

**Comment by jonoomph** [comment]
Hmmm, that's great news that the AppImage works, but I wonder what is breaking with the PPA version. Are you using the standard LibAV package? Or do you have other PPAs or a custom compiled LibAV version?

**Comment by clockworkpc** [comment]
![screenshot from 2017-11-28 17-55-22](https://user-images.githubusercontent.com/9858440/33306182-807ada84-d465-11e7-97ca-5eb795b992f1.png)

**Comment by clockworkpc** [comment]
@jonoomph Does any of this look out of order?

**Comment by jonoomph** [comment]
Can anyone else on Ubuntu 16.04 confirm this behavior with the PPA version of OpenShot?

**Comment by clockworkpc** [comment]
Is there any other information I can give you?

**Comment by jonoomph** [comment]
Not at this point. I just need to setup a Ubuntu 16.04 box and test it out myself to see what's happening. There might be an incompatible version of FFmpeg/LibAV installed, or perhaps I'm missing a dependency needed on that platform. Or... maybe it will work fine and your problem is due to some local configuration issue.

**Comment by DylanC** [comment]
@jonoomph - I can try this on a 16.04 install if you want.

**Comment by DylanC** [comment]
@clockworkpc - I tried to install the PPA on 16.04 yesterday but the PPA would not reload successfully. I will try again soon in case the issue was just intermittent.
