### ISSUE TITLE
Import media dialog should "remember" last used directory

### ISSUE THREAD

**Issue by petebachant** [OpenShot/openshot-qt#1073]
When importing new items, it would be helpful for the dialog to open up in the directory used last.

**Comment by embeh** [comment]
Yes, please. Just came here to post the same issue.

**Comment by Torniojaws** [comment]
Yep, it's a "standard" feature in modern programs. Should be there.

**Comment by DylanC** [comment]
@Torniojaws - Agreed. I put this feature into my own software and it makes a great difference to productivity/usability.
