### ISSUE TITLE
Extending title does not snap to existing clips

### ISSUE THREAD

**Issue by embeh** [OpenShot/openshot-qt#1074]
**System Details:**
* Operating System / Distro: Win 7
* OpenShot Version: 2.4.1

**Issue Description and steps to reproduce:**
1.) Place a few clips on different tracks, slightly staggered in time such that they end at different times
2.) Create a static title and drag it into the topmost track
3.) Click-drag the end handle of the title to extend it's duration
4.) While still keeping the mouse button down, drag the end handle close to the end of one of the existing clips
--> the title end handle is not snapping to any of the end markers of the existing clips, making it hard to ensure the title has the correct length.

PS: The same is true for the Razor tool

**Comment by N3WWN** [comment]
I see this with all recent versions on Linux, including 2.4.1.  Snapping for the end of titles (or other resizing functions) would be very helpful!

Being able to snap to frame markers would be good, too!  I like to end my titles where the fade out of the video starts.  

In a related experience, I have to remove things like fade out when changing the length of a title and reapply the fade out again.  It would be nice if the fade out (and other effects which are tied to the end of the video) would dynamically update if the length of the video is changed.

**Comment by DylanC** [comment]
@embeh @N3WWN - Confirmed this as an issue.

**Comment by N3WWN** [comment]
I think this is still a valid ask - probably more of a feature request than a bug, though

**Comment by N3WWN** [comment]
I think this is still a valid ask - probably more of a feature request than a bug, though
