### ISSUE TITLE
Key frame curve editor

### ISSUE THREAD

**Issue by embeh** [OpenShot/openshot-qt#1075]
A great addition would be a key frame editor that would show a curve representation of the keyed value, along with tools to manipulate, create, deleted the key frames and their tangents.

Similar to this: http://math.hws.edu/graphicsbook/a2/blender-graph-editor.png

**Comment by peanutbutterandcrackers** [comment]
@embeh - I think Mr. Thomas has plans for something similar. He has made a [blog post](https://www.openshot.org/blog/2018/01/01/happy-new-year-2018/) about it, revealing the plan.

All the more reasons to get excited for OpenShot! Yay!

**Comment by embeh** [comment]
Thanks! Some good stuff on the 2018 plan. Also like the new image sequence reader.

**Comment by peanutbutterandcrackers** [comment]
@embeh - Please do continue to support OpenShot in any way you can. We are the ones on whom the future of this awesome software depends. More or less. :)
