### ISSUE TITLE
Find Blender path easily and multithread

### ISSUE THREAD

**Issue by FRUDS** [OpenShot/openshot-qt#1078]
* Ubuntu 16.04 & Windows 10
* OpenShot Version: 2.4

In Openshot-QT lacks work in a multithreaded mode, it would be nice to add components for determining the number of cores of the CPU and sending them to the animation processing.
Also you need to remove the binding to the release of Blender.
For Windows you need to add the function of the first run of Openshot-qt Blender search in the Program Files directory

**Comment by DylanC** [comment]
Dup of #68

**Comment by DylanC** [comment]
I put in a change to have browse buttons in future. This will work better in newer releases:
https://github.com/OpenShot/openshot-qt/pull/2255
