### ISSUE TITLE
edit title (inkscape)

### ISSUE THREAD

**Issue by primer97** [OpenShot/openshot-qt#1082]
**System Details:**
* Operating System / Distro: w10
* OpenShot Version: 2.4.1

**Issue Description and steps to reproduce:**

inkscape 0.92 is installed.
I went to openshot preferences to fill path : c:\Programmes\Inkscape\inkscape.exe
but when I want to edit any title it says that I must install c:\Programmes\Inkscape\inkscape.exe

**Comment by PASTJL** [comment]
See my answer for the blender issue in a pevious post.i paste it below.

You must set the System Variable PATH to point towards the folder of exe of blender and inskape.
You must fill the openshot preference with only inskape and blender without any path.
It runs correctly on my windows 10 desktop

**Comment by DylanC** [comment]
@primer97 - If you set the path correctly it will work. Search closed issues with the keyword inkscape if you still have trouble.
