### ISSUE TITLE
drag and drop not working

### ISSUE THREAD

**Issue by primer97** [OpenShot/openshot-qt#1084]
**System Details:**
* Operating System / Distro: w10
* OpenShot Version: 2.4.1

**Issue Description and steps to reproduce:**
Please allow user to import a video file by drag and drop (on track or on file list)
When trying to do that, nothings happens.
Thank you.

**Comment by DylanC** [comment]
@primer97 - This is already a feature. It should be working.

**Comment by primer97** [comment]
I can drag file from the video list (from inside openshot) 
but when I try to drag from windows explorer it does nothing.

If it should be wrking, it could be a local problem maybe , I don't know. But drag and drop to other solftware is working...
Thank you.

**Comment by DylanC** [comment]
@primer97 - I will test this for you but I suspect it will be working.

**Comment by misscbeezy** [comment]
For me on Windows 7 this is the same for me ONLY when I use the right click "run as administrator" to start 
OpenShot  Launch icon from desktop.  But if I just double click on OpenShot  Launch icon (w/out  right click "run as administrator" ) to start program then I am able to drag and drop with no problem.

**Comment by DylanC** [comment]
@primer97 - Try the solution posted by @misscbeezy. Should work if you start without admin mode.
