### ISSUE TITLE
Openshot can't find Blender

### ISSUE THREAD

**Issue by JQuinnC** [OpenShot/openshot-qt#1086]
Windows 10
Openshot version 2.4.1.

I copied the path from Blender directly into Openshot. I included all the following:

F:\Program Files\Blender Foundation\Blender\Blender.exe
F:\Program Files\Blender Foundation\Blender\
F:\Program Files\Blender Foundation\Blender

It worked the first time I did it when I included the .exe. When I rebooted to resume my project, Openshot could no longer find Blender.

**Comment by milocanepa** [comment]
Me sucede lo mismo. No logro que localice Bender.
Gracias.

**Comment by Witten-1** [comment]
how did You copy the path into openshot???

Where is the config-  or sys-file

There is no menu-button to insert the path !!!

**Comment by milocanepa** [comment]
My english is very bad. 
I did it in the following way: I opened the Windows explorer, I looked for the executable "blender" (V. 2.78), I clicked right click, I went to "properties", I copied the executable address and I sinned it in the "preferences" of Openshot ( V 2.4.0)

**Comment by Witten-1** [comment]
Thank You for Your answer,

 

But the animated titles doesn’t work,  please look to the screenshot..

 

Where is the mistake and how can this mistake eliminated??

 

I like this wonderful program !!!!!

 

 



 

 



 

 



 

 

 

Mit musikalischem Gruß

 

    Helmut Pleschke

 



 

 

Von: JQuinnC [mailto:notifications@github.com] 
Gesendet: Mittwoch, 29. November 2017 21:05
An: OpenShot/openshot-qt <openshot-qt@noreply.github.com>
Cc: Heli <werbung@pleschke.de>; Comment <comment@noreply.github.com>
Betreff: Re: [OpenShot/openshot-qt] Openshot can't find Blender (#1086)

 

In Windows Explorer, you can click the location bar and it will convert to
an actual path. I copied that into OS.

**Comment by PASTJL** [comment]
I have posted a workaround to configure Inskape and blender for Windows.
You must set the System Variable PATH to point towards the folder of exe of blender and inskape.
You must fill the openshot preference with only inskape and blender without any path.
It runs correctly on my windows 10 desktop

**Comment by milocanepa** [comment]
Thanks!

**Comment by DylanC** [comment]
Closing since there is plenty of information on this in closed issues.
