### ISSUE TITLE
cx_Freeze: Python error in main script

### ISSUE THREAD

**Issue by coolhj** [OpenShot/openshot-qt#1088]
**System Details:**
* Operating System: Windows 7 
* OpenShot Version: 2.4.1
![screenshot_17](https://user-images.githubusercontent.com/34106592/33394334-44913080-d542-11e7-9bc2-1886b6025e18.png)
worked perfectly until today.I tried to redownload openshot and reinstall but nothing.

**Comment by DylanC** [comment]
@coolhj - Sometimes this could be files missing from your project. It tries to load them and cannot find them. (then crashes)

Otherwise it may be corrupted preference file. Try delete preferences folder and restart OpenShot.
