### ISSUE TITLE
Wish: Following features:

### ISSUE THREAD

**Issue by peanutbutterandcrackers** [OpenShot/openshot-qt#1093]
1. Color grading capabilities
2. Optional frame-by-frame view in the timeline for more precise cutting
     It would be nice if it went from 1 second in timeline, to frame-by-frame.
3. Move-able, drag-able, click-able, delete-able keyframes
4. Aspect Ratio Manipulation
5. Ability to check for marker's properties i.e. the exact time/position of where the marker is placed.
6. Ability to change colur of how the clip looks in the timeline. Not the color of the video (although it would be nice too) but the color of the clip marker in the timeline. That would help organize the work even more, IMHO.
7. Themes?
8. The ability to save custom presets

Thank you, Mr. Jonathan Thomas and other developers for this wonderful software. Your hard work is very much appreciated. May God Bless you.

With much appreciation,
From Nepal :)

**Comment by ferdnyc** [comment]
> 2. Optional frame-by-frame view in the timeline for more precise cutting
>   It would be nice if it went from 1 second in timeline, to frame-by-frame.

Is it... **not** frame-by-frame? I mean, The scrubbing controls (arrow keys) move frame-by-frame, no matter what, and at "1 second" zoom (on my system) each frame looks like it's about _three_ pixels wide (at 25fps), even without fullscreening OpenShot. So, each individual frame is already represented by a distinct, unique position on the timeline.

Or are you referring to the tickmarks on the ruler, which are still only placed at half-second intervals? At "1 second" zoom, the ruler probably _could_ contain tickmarks for individual frames. Or at least every second (odd) frame, with the spaces between representing the even-numbered ones.

**Comment by peanutbutterandcrackers** [comment]
It is frame-by-frame. But yeah, I am referring to the tickmark thingies. But still, having the time-line show everything frame-by-frame would allow one to have a lot more control. For one, a picture could be added on top-of a frame rather easily - to produce a lot of cool stuffs like the shooting star memes and stuff. Secondly, keyframes would be more identifiable. So, that should help a user out with the editing.

Kdenlive also has frame-by-frame timeline view. Pretty neat, actually. :)

**Comment by peanutbutterandcrackers** [comment]
Haha. I know.

Here are some screenshots:
![screenshot from 2018-03-15 12 09 21](https://user-images.githubusercontent.com/26764547/37447362-e8bc96d6-2849-11e8-88fc-8e48f60faf37.png)
![screenshot from 2018-03-15 12 08 48](https://user-images.githubusercontent.com/26764547/37447363-ea28bd9c-2849-11e8-9a85-72be5abf85fa.png)
![screenshot from 2018-03-15 12 08 32](https://user-images.githubusercontent.com/26764547/37447365-ea8528ca-2849-11e8-9d44-dd3aebdc88aa.png)
![screenshot from 2018-03-15 12 07 51](https://user-images.githubusercontent.com/26764547/37447366-eaf0056e-2849-11e8-9a69-900276ea7970.png)

**Comment by N3WWN** [comment]
Hmmm.... since the preview cache will have the images generated for each frame, this may not be _too_ incredibly difficult to add.

**Comment by ferdnyc** [comment]
Ahh, I see, an "exploded" view of the clip, with each frame fully _visible_ on the timeline. Yeah, neat.

@N3WWN is right, since the frame-by-frame preview has to be generated _anyway_... Only thing is, as of right now I believe only one preview image per *rendered* frame is created (taking into account all clips/effects/transitions on the timeline), and whenever any change is made that's invalidated and the cache flushed (for the affected frames). So, the preview cache would have to be able to hold a per-frame-_per-clip_ cache (plus the rendered composite version) to make this go. Still, it's exactly the same caching OpenShot is already performing, simply more of it.

And yes, I did notice the OpenShot video playing in Kdenlive. Which feels a little bit like using Bing to search Google's own websites...

**Comment by peanutbutterandcrackers** [comment]
So, does that mean we might be closer to frame-by-frame timeline view in OpenShot than I had previously thought? That would be awesome!!!

@ferdnyc - Because YOLO. :D
