### ISSUE TITLE
how many images can be uploaded

### ISSUE THREAD

**Issue by Hessadv** [OpenShot/openshot-qt#1096]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

**Comment by DylanC** [comment]
@Hessadv - What do you mean? Can you give more details?

**Comment by Hessadv** [comment]
I tried to upload over 24 images to the project file but then it appears as though it is full because I can’t upload anymore.  Just wondering if there is a limit to how many files can be used if I want to do a slide show/video presentation using pictures.

 

Beth

**Comment by DylanC** [comment]
@Hessadv - I can check this for you but as far as I know there should be no limit.

**Comment by DylanC** [comment]
@Hessadv - There is no limit. You should be able to attach all the images you need.
