### ISSUE TITLE
Windows10 openshot launch error (& reinstall repeats error)

### ISSUE THREAD

**Issue by eric888888** [OpenShot/openshot-qt#1097]
Windows 10 
64bit
![openshot error](https://user-images.githubusercontent.com/34218628/33529289-e042856c-d8d3-11e7-8947-c83365e3943d.jpg)

v2.4.1

Was loving it & using it a day or two, but then it would not open .. so I uninstalled and redownloaded .. but still it gets stuck with same error 1 second into startup.
vvv
I saw an earlier suggestion here (very similar error it seemed) where someone suggested to delete 'preferences folder'..i looked C:>Openshot>etc   ..did not find a folder, but two files in the subfolder 'windows' ..  but renaming (disabling?) those two files did not work (so I renamed them back again).
vvv
I also tried restoring the few things I have in Recycle Bin in case Openshot was looking to restart with earlier files.. but that still gives the error.

Would love to keep using the wonderful product! ..please inform! :) .. and thanks so much!

**Comment by eric888888** [comment]
when launching OpenShot from desktop, it shouldn't be looking to populate earlier files anyway right?

**Comment by DylanC** [comment]
@eric888888 - It does try to reopen the last opened project I think. Delete backup.osp if there is one.

**Comment by eric888888** [comment]
Thanks for the idea Dylan ..
but there isn't a file of that name .. are there any other filenames it might be? (Windows10/ 64bit) .. or even the likely folder location, if you think I may recognize a 'likely' candidate to remove?
Thanks for your suggestions... what I did use of openshot was awesome and id love to have it back :)

**Comment by eric888888** [comment]
also.. still leaves me confused wrt a uninstall and reinstall situation. It still hung immediately in that case .. could it be possible that its backup is held somewhere else?

**Comment by DylanC** [comment]
@eric888888 - I think its the preferences folder you need to remove. I will check the location on Windows for you and post it here.

**Comment by DylanC** [comment]
@eric888888 

The preferences folder is at the location:
C:\Users\USERNAME\.openshot_qt

**Comment by eric888888** [comment]
That worked thanks!! :) ..ill use it this week to check.. but it opens now properly in that nice 'factory fresh' way. When I 'save as' .. that function does the 'continue with project' function .. so feel free to allow it to start fresh when clicking on the original launce file(!) .. thx a lot Dylan .. I tried shotcut too, but I feel openshot does the final export a lot quicker (using H.264)^^ Thanks again!

**Comment by DylanC** [comment]
@eric888888 - No problem. Glad you got it sorted! :)
