### ISSUE TITLE
Black screen in output video FHD 1920x1080 60p

### ISSUE THREAD

**Issue by dsieradzki** [OpenShot/openshot-qt#1098]
**System Details:** i5-7500, 8 GB Ram, GTX 1050Ti
* Operating System / Distro: Kubuntu 17.10 64bit
* OpenShot Version: 2.4.1

**Issue Description and steps to reproduce:**
Black screen in part of output video.
1. Add two clips, on the seconds clip some part from both sides
2. Add Fade in(fast) effect on start slice and Fade out(slow) on the end on the second clip
3. Export as FHD 1920x1080, it's important to export in >60< frames with default codec

When I export in 24 frames is ok, problem is in 60 frames.
Similar problem occurs when I do timelaps(32x) on one slice.

**Comment by N3WWN** [comment]
Same issue as mentioned in at least https://github.com/OpenShot/openshot-qt/issues/1034 and https://github.com/OpenShot/openshot-qt/issues/519 ?

At this time, anything that uses keyframes will not render properly if exported at a different framerate.  If the project was originally set to the export framerate before the fade/animation/etc is applied to the clips, then all will go as expected.

**Comment by DylanC** [comment]
Dup of #519

**Comment by mikelacsa** [comment]
This issue was fixed as mentioned in [519](https://github.com/OpenShot/openshot-qt/issues/519)

**Comment by NetlistPCB** [comment]
I'm seeing the same issue on Windows 10
