### ISSUE TITLE
Just installed openshot, added a video .flv and .mp4 and no video preview so can't edit anything

### ISSUE THREAD

**Issue by metadune** [OpenShot/openshot-qt#1099]
**System Details:**
* Operating System / Distro: win10
* OpenShot Version: 2.4.1
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

Just installed openshot, added a video .flv and .mp4 and no video preview so can't edit anything. I hit play nothing happens

**Comment by Raketenwilli** [comment]
Did you dragged and dropped the files from the project files to the tracks? Anyway you can right-click the files and select preview.

**Comment by metadune** [comment]
Ah ok gotcha, I didn't realized you had to drag the  project files to the tracks. Thanks
