### ISSUE TITLE
found the reason exporting a project HANGS openshot!!

### ISSUE THREAD

**Issue by nanohtpc** [OpenShot/openshot-qt#1100]
**Issue Description and steps to reproduce:**

HI guyz...

Prevoiusly i used FREEMAKE for my project, but i need something BETTER, so i give a shot to Openshot..

then when i tried to export my project, using older videos it just hangs (not responding), those videos were from 2014 but converted from AVI TO MKV using FREEMAKE..

now im using HANDBRAKE for that... and guess what???? NOT HANGIING!!, seems to be that the codec used in FREEMAKE on that time, wasnt compatible with this version of OPENSHOT, so if anybody read this.....

- be sure to test with a DIFFERENT CODEC, it Openshot HANGS on exporting...
- if the openshot team could make magic and find some sort o fix it would be great.
- if you cant export anyways, convert your source file with handbrake, and then test again..

seems like openshot doesnt like older FREEMAKE codecs in my case... 8((((

**Comment by DylanC** [comment]
@nanohtpc - Thanks for your feedback.
