### ISSUE TITLE
How to export with Progressive Download?

### ISSUE THREAD

**Issue by Stan-Green** [OpenShot/openshot-qt#1101]
I just installed OpenShot and tried to export my first video. The way we use video is to put them on a private server and use progressive download for playback. (No need for a streaming server!) I don't see any option in the export to enable this. I also cannot find it in a Google search. Is there a way to do this in OpenShot? I know there are ways to enable this after the export, but I would rather not have to do that.

Thanks,
Stan

**Comment by DylanC** [comment]
@Stan-Green - I think this is something you would need to do afterwards. Perhaps putting it on a service like Youtube or else put in your own HTML5 web player.

Example here:
https://www.w3schools.com/html/html5_video.asp

**Comment by Stan-Green** [comment]
I am fully aware of how to publish videos using HTML5. I have created a video distribution system for my organization using HTML5. (I have very good reasons not to use YouTube.) Progressive download allows the video to start playing prior to the entire video being downloaded. (https://en.wikipedia.org/wiki/Progressive_download) This allows the simulation of streaming without the complexity of having a streaming server. So the question again is how to enable progressive download in OpenShot?

**Comment by DylanC** [comment]
@Stan-Green - OpenShot does not have such a feature but maybe we could add something like that in the future if possible.

**Comment by N3WWN** [comment]
@DylanC FYI, there is a request that I submitted about the "FastStart" feature already open in https://github.com/OpenShot/openshot-qt/issues/733#issuecomment-337984385 :

> BTW, speaking of relocating the moov atom, it would be very helpful to be able to set options like this (or other ffmpeg options) within OpenShot so that I don't have to remember to do this (and double the disk space requirement) performing this step after OpenShot has completed rendering.
