### ISSUE TITLE
animated title

### ISSUE THREAD

**Issue by franck007pro** [OpenShot/openshot-qt#1102]
**blender command put C: / program files (x86) / blender foundation / blender / blender.exe

advanced title editor I put C: \ Program Files \ Inkscape \ inkscape.exe "

it does not work OpenShot v 2.4.1

**Comment by franck007pro** [comment]
** Blender commande mettre C: / program files (x86) / blender foundation / blender / blender.exe

éditeur de titre avancé j'ai mis C: \ Program Files \ Inkscape \ inkscape.exe "

il ne fonctionne pas OpenShot v 2.4.1

**Comment by franck007pro** [comment]
** Blender commande mettre C: / program files (x86) / blender foundation / blender / blender.exe

éditeur de titre avancé j'ai mis C: \ Program Files \ Inkscape \ inkscape.exe "

il ne fonctionne pas OpenShot v 2.4.1

**Comment by PASTJL** [comment]
My answer workarround for Windows See #1082

**Comment by misscbeezy** [comment]
remove the "  quotation marks " from beginning & end of path, worked for me on Windows 7

**Comment by DylanC** [comment]
@franck007pro - Try suggestion from @misscbeezy
