### ISSUE TITLE
Animated Title Issue

### ISSUE THREAD

**Issue by fightdread** [OpenShot/openshot-qt#1103]
**System Details:**
* Operating System: OSX 10.9.5
* OpenShot Version: 2.4.1

**Issue Description and steps to reproduce:**
When I try to add an Animated Title I get the following error message.  I have verified that the .app file for blender is in the location that it is looking for.  I am using Blender 2.79.

Blender, the free open source 3D content creation suite is required for this action (http://www.blender.org).

Please check the preferences in OpenShot and be sure the Blender executable is correct.  This setting should be the path of the 'blender' executable on your computer.  Also, please be sure that it is pointing to Blender version 2.78 or greater.

Blender Path:
/Applications/blender.app

**Comment by DylanC** [comment]
@fightdread - I have an old Mac I can test on.

**Comment by peanutbutterandcrackers** [comment]
@DylanC - any luck with the testing? #1287 also seems to have the same problemos, senor!

**Comment by DylanC** [comment]
@peanutbutterandcrackers - Same issue that I had with #1287. Doesn't seem to be working for me.

**Comment by peanutbutterandcrackers** [comment]
Mac and Windows. *smh* I hope these issues are resolved soon...

**Comment by peanutbutterandcrackers** [comment]
It seems that the solution provided at #1400 works. It has apparently [worked for some users](https://github.com/RedSoxFan04). I think it's worth a shot.

**Comment by DylanC** [comment]
I put in a change to have browse buttons in future. This will work better in newer releases:
https://github.com/OpenShot/openshot-qt/pull/2255
