### ISSUE TITLE
Interface continues to freeze

### ISSUE THREAD

**Issue by maxroby** [OpenShot/openshot-qt#1104]
**System Details:**
* Operating System / Distro: Ubuntu Linux 17.10
* OpenShot Version: 2.4.1

**Issue Description and steps to reproduce:**
With any click, mouse move, menu action the interface freezes, a dialog shows "The script on this page appears to have a problem. Do you want to stop the script?" and it's very hard to work.

**Comment by DylanC** [comment]
@maxroby - Do you have a screenshot?

**Comment by maxroby** [comment]
Here it is.

Regards,
Roberto


Il 08/12/2017 18:12, DylanC ha scritto:

**Comment by DylanC** [comment]
@maxroby - Never seen this before. Thanks.

**Comment by DylanC** [comment]
@maxroby - What is the spec of your computer hardware?

**Comment by maxroby** [comment]
Ubuntu 17.10 64bit on Intel Core i7, 8 GB RAM, Lenovo Thinkpad E530 notebook.

**Comment by DylanC** [comment]
@maxroby - Great, thank you!

**Comment by DylanC** [comment]
@maxroby Can you try v2.4.2 and let us know if you have any success?
