### ISSUE TITLE
Imported File Path Set to Relative Project Path

### ISSUE THREAD

**Issue by watkec** [OpenShot/openshot-qt#1105]
* Operating System / Distro: Ubuntu 14.04
* OpenShot Version: 2.3.2
**Issue Description and steps to reproduce:**
We need to share openshot projects from one computer to another. However, if we zip the folder with the project file and all related files, the internal link within the project is still to the path of the original computer. Is there a way to set the path of all imported files to match the relative path of the project file so the folder can be freely shared between multiple people on multiple machines who work on a single project?

**Comment by aluizioneto** [comment]
I have the same issue here. This gets even worse when collaborators use different Operating Systems (which is exactly what I'm dealing with right now).

**Comment by DylanC** [comment]
@watkec - Marking as a bug since I think this needs to be resolved for many people.
