### ISSUE TITLE
I can't open the files

### ISSUE THREAD

**Issue by SaulCampello** [OpenShot/openshot-qt#1106]
When I save a new Project I can't open it later. In conclusion, I lose the Project. I hope you can fix it. Thanks.

**Comment by DylanC** [comment]
@SaulCampello - What happens when you try to open it?

**Comment by peanutbutterandcrackers** [comment]
@SaulCampello - That wording. Haha. It's the best. "I can't heat my coffee. In conclusion, I drink cold coffee" You seem to be a fun-to-hang-around person.

Anyways, could you give more details regarding the issue? That will help others help you. :)

**Comment by DylanC** [comment]
Closing due to lack of details to investigate. If you log another issue we do need detailed descriptions with system specs and logs if possible to investigate. Thanks.
