### ISSUE TITLE
Download forbidden...

### ISSUE THREAD

**Issue by K4T1E** [OpenShot/openshot-qt#1109]
I am operating on Windows 10 on a Surface Pro 4, every time I try to download OpenShot is says "download forbidden" am I doing something wrong?

**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

**Comment by DylanC** [comment]
@K4T1E - Do you have a screenshot?
