### ISSUE TITLE
Windows 10: Transport buttons unresponsive, then crashes

### ISSUE THREAD

**Issue by pnaw10** [OpenShot/openshot-qt#111]
Quick Foreword Note: Originally posted this on Launchpad since that's where the "report a bug" from within OpenShot takes you, but then I noticed the OpenShot website links here to GitHub instead. Wasn't sure if you're still actively checking Launchpad or if that's been abandoned so I am crossposting.
= = = =

Just installed OpenShot, rebooted the machine and imported about a dozen GoPro MP4 files.

I can drag a video from the bin down to the timeline. But as soon as I try to play any video, the problems begin. Once a video is playing, pressing pause does nothing for several seconds. Once it pauses, the Windows "spinning" icon appears. In two instances, OpenShot crashed a short time later. Only once, it just froze for a few minutes and then unfroze as if nothing happened. (On the plus side, when it crashed, I was happy to see my project file recovered even though I hadn't even saved anything yet.)

I am also surprised that once the timeline is playing, it continues to "runaway" past the very last clip. Other editors I've used automatically stop the cursor once it reaches the end of the very last clip on the timeline.

It might be this particular machine - I'm on my laptop, but my desktop PC is considerably better. Still, thought you should know in case this input helps you in creating "recommended system requirements" for OpenShot, as I didn't see any posted anywhere. Once I have a chance to try it on the desktop, I'll file another report with that machine's specs, if I encounter the same issues.

Architecture (64 bits or 32 bits) : 64 bit
Operating System & version: Windows 10, version 1511
Installation Method : MSI via link from the latest Kickstarter backer email
Version of Openshot installed : 2.0.6 (beta 3)

Processor: AMD A6-3400M APU 1.40 GHz
RAM: 6 GB
HDD: 580 GB, approx 500 GB free

BZR Revision used (if any) : ??
MLT/melt version: ??
FFmpeg (i.e.libavcodec) version : ??
FFmpeg installation : ??
= = = = =

Also, I was a kickstarter donor but I didn't see my name in the credits. I opted-out of having a certificate mailed to me, but I thought I'd still be in the credits?

**Comment by petebachant** [comment]
I am getting a similar error on Windows 10. A sequence will play for a couple seconds, then the transport controls become unresponsive.

**Comment by jonoomph** [comment]
This is similar to #116.

**Comment by jonoomph** [comment]
This is a problem mostly for slower machines, but still, the UI should not become unresponsive since it's in it's own thread. I think the UI thread must be getting tangled up with the playback threads (which race ahead trying to cache frames, and use a ton of CPU). I'll be tracking this ticket on #116 though, and am closing this ticket. Thx!
