### ISSUE TITLE
Little Translation Mistake

### ISSUE THREAD

**Issue by Raketenwilli** [OpenShot/openshot-qt#1110]
**System Details:**
* Operating System / Distro: Windows 10 Pro
* OpenShot Version: 2.4.1

The German translation (De) needs to be changed at the introduction (video preview) from "Ihre Videovorschau kann hier ansehen werden." to "Ihre Videovorschau kann hier angesehen werden.".

**Comment by stephan75** [comment]
Hi,
translations are handled via https://translations.launchpad.net/openshot

maybe you can log-in there and fix this on your own?

**Comment by Raketenwilli** [comment]
I don't want to create an account there, sorry. But it is located here -> https://translations.launchpad.net/openshot/2.0/+pots/openshot/de/86/+translate

**Comment by DylanC** [comment]
@Raketenwilli - I have a Launchpad account. I could try change this if you like.

**Comment by Raketenwilli** [comment]
@DylanC feel free to do so ;D

**Comment by DylanC** [comment]
@Raketenwilli - I have this updated now. :)
