### ISSUE TITLE
No sound on exported video.

### ISSUE THREAD

**Issue by Bryan5280** [OpenShot/openshot-qt#1111]
I'm new to OpenShot and trying to export my first video.  When I do, I lose the sound from it.  Please help!  

Window 7
OpenShot Version 2.4.1

The audio is directly from the recorded videos, and then I added a song on another track.

**Comment by paddydisplays** [comment]
Had the same problem this morning, found the answer in google

http://openshotusers.com/forum/viewtopic.php?f=11&t=1227 

I changed the audio ot aac  and exports fine now

**Comment by DylanC** [comment]
@Bryan5280 - Follow the suggestion by paddydisplays.

**Comment by guillermomartinez-accenture** [comment]
The link provided by @paddydisplays is broken.

**Comment by paddydisplays** [comment]
> The link provided by @paddydisplays is broken.

from memory, when exporting the video go to advanced tab, then audio settings  and in the Audio codec field to "acc".  That worked for me ( so weird, last week was the first time  i used this program in over a  year  and then today I got a email about this question)
