### ISSUE TITLE
what's the best way to seperate a long video into seperate shorter videos?

### ISSUE THREAD

**Issue by Snapper763** [OpenShot/openshot-qt#1113]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

**Comment by peanutbutterandcrackers** [comment]
Perhaps [this](https://www.youtube.com/watch?v=BQS2tmgD_Rk&t=180s)? :)

**Comment by DylanC** [comment]
Closing question as answered. Thanks!
