### ISSUE TITLE
Audio files won't play and clips cut out before speaking is done

### ISSUE THREAD

**Issue by LerPa** [OpenShot/openshot-qt#1114]
* Operating System: Windows 10
* OpenShot Version: 2.4.1 

**Issue Description and steps to reproduce:**

These aren't issues as much as they are newbie problems. Things were going well at first. I had a video in one track and its audio in the track below. But I had six tracks (for three audio and three video) and realized that they could all go on the timeline in two tracks. At least, I thought that was right, and so I moved them. The audio continued to play with the video for a while, but it's stopped, and I can't figure out why. 

Second problem: Some of the videos (and their audio files) fade out and stop before the talking is done. I tried grabbing the edge to drag it, but OpenShot won't let me do that. Again, can't figure why this is happening. (Should I have left them in six tracks?)

Help?

**Comment by DylanC** [comment]
@LerPa - What audio format are those files?

**Comment by peanutbutterandcrackers** [comment]
I wonder if this problem has to do with the fact that you are using windows 10, with which OpenShot 2.4.1 is known not to work that well...

Could you please grab latest daily build from: https://www.openshot.org/download/ by clicking on the 'daily builds' button and see if that works for you?

**Comment by DylanC** [comment]
@LerPa Can you try v2.4.2 and let us know if you have any success?
