### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by labregowski** [OpenShot/openshot-qt#1115]
**System Details:**
* Operating System / Distro: Windows 10
* OpenShot Version: 2.4.1

Is there a way to translate the Titles (except rewriting all of them and export as a new video)?
Is there a way to integrate such translations with Youtube so I can have one unique video tha will show different Titles, according to user's language?

**Comment by DylanC** [comment]
@labregowski - I think you would have to rewrite them imho.

**Comment by labregowski** [comment]
Thanks for your reply.
ALl the best

**Comment by DylanC** [comment]
@labregowski - No worries.
