### ISSUE TITLE
Audio Glitch with fade in?

### ISSUE THREAD

**Issue by Markmusicman** [OpenShot/openshot-qt#1117]
I am having an audio glitch when doing fade ins any help would be greatly appreciated!!
Thanks
Mark

**Comment by peanutbutterandcrackers** [comment]
Does that glitch only occur in preview? Did you render the project? Did the glitch manifest itself even in the exported video?

Sorry for the late reply. This is just a community that scratches each other's back.

**Comment by DylanC** [comment]
@Markmusicman Can you try v2.4.2 and let us know if you have any success?
