### ISSUE TITLE
Pressing the "x" on the unsaved changes dialog, quits Openshot.

### ISSUE THREAD

**Issue by firew4lker** [OpenShot/openshot-qt#112]
Pressing the "x" on the unsaved changes dialog, quits Openshot. Some times with a segmentation fault message.

Archlinux. Openshot rev589, libopenshot rev509

http://i.imgur.com/z3r7Gwj.png

**Comment by jonoomph** [comment]
I agree with you that hitting ESC shouldn't quit the program on this prompt. I've just committed a 'Cancel' button to go along with 'No' and 'Yes'. Also, now the ESC button triggers the cancel button, and does not close OpenShot. Thx!
