### ISSUE TITLE
Editing performance is very poor

### ISSUE THREAD

**Issue by mikan66** [OpenShot/openshot-qt#1120]
**System Details:**  Core I5, 3.4 GHz, 16 GB RAM
* Operating System / Distro: ? Windows 10 with SSD, 
* OpenShot Version: ?  2.4.1,  install on HDD.  Movie data files on SSD.
* _Please attach log files if crash_

I have 38 clips amounting to 1 hour of MPEG2  all video in one track.  I'm attempting to "edit" out select pieces of some segments.  This process is difficult, but also extremely slow to respond to commands.  I'm still trying to figure out the best way to removed portions and have the dead space "collapse" between the remaining segments.

I can be a beta tester, but I must abandon this tool for now and find something else that supports better editing of loaded segments withing a track or timeline.

**Comment by PontiacCZ** [comment]
I confirm this issue on Windows. When I started adding clips to timeline the editing operations (cuts, fade in/out or adding a jpeg to the timeline) took to 2 seconds. I could live with that.

Now  I have two minutes on the timeline and these actions take from 5 to 10 seconds. I am not able to continue under such conditions.

_OpenShot 2.4.1
Windows 7 SP1 x64
AMD A10-5800 (4 cores @ 3,8 GHz), 16 GB RAM (I reserved 8 GB for OpenShot cache)_

**Comment by anstg** [comment]
Same issue it takes me 10-30 seconds to place a clip

**Comment by DylanC** [comment]
Dup of #902

**Comment by peanutbutterandcrackers** [comment]
@DerGenaue - It's just that the devs would rather have us volunteers close the issues that are too vague like "editing is very bad" or something and would rather have a specific issue, with enough information - logs and system specs and reproduction-method and everything. However, because you are an esteemed contributor, I shall proceed to remove the 'duplicate' label and keep this one. :)

**Comment by peanutbutterandcrackers** [comment]
@igpf - OpenShot actually works even on a 32 bit machine. I have used it on a really old laptop as well (only for testing purposes). So, it's not that high. However, we do have issues with performance (esp. on windows and mac) that are going to be addressed slowly (as we are a volunteer-based project).
