### ISSUE TITLE
How to stick two shots together with a shortcut?

### ISSUE THREAD

**Issue by DrWaleedAYousef** [OpenShot/openshot-qt#1121]
How to stick two shots together on the same track with easy shortcut instead of clicking on one and keep dragging until hitting the other one? This is more difficult on a closer zoom since a shot is too wide and one has to keep dragging until hitting the other shot.

**Comment by N3WWN** [comment]
Possibly the easiest way to do this is to highlight the current clip on the timeline, hit the `>|` button above the timeline (not the one in the preview frame), then select your clip in your project files, either right-click and select `Add to Timeline` (or use the shortcut, `CTRL-W` by default), select the track you want the clip added to (and adjust any other options) and click `OK`.

FYI, you can select the clip in your project files at any time, not only after setting the playhead at the end of the select clip like I've done here.

**Comment by DrWaleedAYousef** [comment]
Thanks so much;

I think I need to rephrase for more clarifications. The two clips are
already added and on the same track (call them A then B). After cutting
and clipping, now there is an empty time period between A and B. Instead
clicking on B and keeping dragging to the left so that the start of B
hits the end of A, I need a shortcut for that.

Thanks so much.

**Comment by N3WWN** [comment]
Ah, gotcha!

Sorry, I don't think there's a shortcut to move a clip up against the previous clip at this time.

What I do is to zoom out far enough that both clips are visible on the timeline (it only has to be the end of the first and the start of the second that are visible), make sure I have snapping enabled and drag the second clip to the end of the first.  

For some types of clips (titles, for instance), you cannot snap to the end of the clip, but you can snap to the playhead.  If that's something that you're running into, locate the playhead at the end of the previous clip, as I described earlier, and drag to the playhead.  The dragged clip will snap to the playhead.

**Comment by DrWaleedAYousef** [comment]
Thanks so much; currently, I do exactly as you just described. However, I hope if you consider it as a feature request; it will be too much easier. Thanks for the great software. 
--Waleed
