### ISSUE TITLE
cx_freeze Python error in main script when starting Openshot

### ISSUE THREAD

**Issue by arcede** [OpenShot/openshot-qt#1122]
Hi, I've installed Openshot OpenShot-v2.4.1-x86_64 on my Win10 laptop, but when I try to open the program I'm getting this "cx_freeze: Python error in main script" popup en the program doesn't start at all.
Do you have any ideas what I need to do to resolve this?
I've already tried to uninstall and reinstall.
I've attached a screenshot of the error popping up.

Thanks for the support!

**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
![171214_openshot-error](https://user-images.githubusercontent.com/34542238/33992169-df532188-e0d1-11e7-9fd1-d1136f3f85c2.jpg)

**Comment by duetltd** [comment]
I just downloaded OpenShot 2.4.1 64bit installed it - opened it and got a similar error - Windows 7. If a file is missing from a project - it is before I have a chance to load anything.

![image](https://user-images.githubusercontent.com/3537713/35200410-f79e0758-fedb-11e7-807b-0b8f8c16c610.png)
