### ISSUE TITLE
No Sound of uploaded video

### ISSUE THREAD

**Issue by GSIB55** [OpenShot/openshot-qt#1124]
Windows 7 Pro
OpenShot video 2.4.1

I created my first project using pictures and a video.  I wanted pictures to fade into video. Everything worked good and was quite simple.  Preview is ok.  However when I export it to a mp4 the sound on the video is gone.  
![audio](https://user-images.githubusercontent.com/34549356/34004138-17ccbf36-e0c5-11e7-9063-6b7c92c81bc4.PNG)

**Comment by qwaterma** [comment]
I am having the exact same issue. editing, everything is fine. when I export, I get no sound.

**Comment by N3WWN** [comment]
Try changing the Audio Codec to `aac` and see if that helps.

**Comment by GSIB55** [comment]
Thanks N3WWN for the followup.  I just gave up and went with Kizoa.
