### ISSUE TITLE
Edits don't happen at the right time when exported

### ISSUE THREAD

**Issue by domspy1995** [OpenShot/openshot-qt#1125]
**System Details:**
* Operating System / Distro: Windows 10
* OpenShot Version: 2.4.1
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
When I edit a clip (Say changing the scale and location), the edit will happen at a different time after I export the project from when I set it in the .OSP file.

**Comment by N3WWN** [comment]
Are you exporting the video with a different frame rate than the profile that you're project is set to?

**Comment by domspy1995** [comment]
Ah... That fixed it... Thank-you!
