### ISSUE TITLE
Control Z

### ISSUE THREAD

**Issue by Jkood45** [OpenShot/openshot-qt#1126]
**Intel 2.5 dual core**
* Win8.1
* Version 2.4.1
* NO crash yet

**Should you use command Conrol Z to return the last operation, that LAST clip that you had on the track line, will automatically go SLOW speed by few notches. Meaning, the last clip that you skooted or moved from track to track, IF you did control Z on it to undo that **mistake**. Guess what, that whole clip becomes garbage, it locks in to slow slow speed on voice and on video. EVERY Time, enough to force to get here and write this paragraph!. **

**Comment by peanutbutterandcrackers** [comment]
@Jkood45  - The thing is, OpenShot  is a free software made by (mostly) a single person in the time he squirrels away from work, using a Linux machine for primary development, it has performance issues in Windows. Please do however keep on supporting OpenShot. It will only get better with time and more volunteers/supporters. Sorry for the inconvienience. Thanks!
