### ISSUE TITLE
motion blur?

### ISSUE THREAD

**Issue by Geesbugg** [OpenShot/openshot-qt#1127]
**System Details:**
* Windows 7 Premium
* 2.4.1

When I convert from 1920x1080 to 1280x720, it will be motion blur. Is there anything to remedy this?
You must convert with other software to avoid this.

**Comment by peanutbutterandcrackers** [comment]
If you only trying to 'convert' videos rather than edit them, HandBrake is probably a better option for you... Here: https://handbrake.fr/

Hope that helps.

**Comment by DylanC** [comment]
@Geesbugg - A separate video converter is the right solution here. OpenShot won't really be working on format conversion features.

**Comment by Geesbugg** [comment]
One more thing.
So, movies that originally are 1280x720 do not become motion blurred
only when the resolution is 1920x1080 rendered to 1280x720

My intention was that it was unnecessary to save in such a high resolution, it takes so much space. The purpose was that the edited movie did not need such a high resolution.

**Comment by peanutbutterandcrackers** [comment]
@Geesbugg - Ah. That makes sense though. Does it render out a motion blurred video too? If you haven't yet tried rendering it, perhaps it's just a 'preview' issue? Or, perhaps, you could figure out a custom profile that will work just right for this thing? [Here](https://www.openshot.org/static/files/user-guide/profiles.html#custom-profile) is how you create custom profiles.

All the very best!
