### ISSUE TITLE
title in transactions

### ISSUE THREAD

**Issue by marwes9** [OpenShot/openshot-qt#1128]
it might be very easy, but i cant find out how to put an title on the transactions, sort of like chapters. any help would be great

**Comment by N3WWN** [comment]
I think you're asking about displaying titles during transitions...

You can add a title by clicking on the `Title` menu and selecting `Title` or `Animated Title`.

Then, create your title, which will then appear in your `Project Files` frame.  

Drag and drop the title from `Project Files` to a track in the timeline that is above the transition that you want the title to appear over.

**Comment by DylanC** [comment]
@marwes9 - Follow suggestion by @N3WWN.
