### ISSUE TITLE
Trackers? In a video editing software?

### ISSUE THREAD

**Issue by diamondburned** [OpenShot/openshot-qt#1129]
**System Details:** i7-5500U + HD5500
* Operating System / Distro:  Arch Linux x86_64 4.14.3-1-ARCH
* OpenShot Version: 2.4.1-1

**Issue Description and steps to reproduce:** Openshot sending stuff to Google Analytics after closing `openshot-qt`

>    timeline:INFO Adjusting max size of preview image: PyQt5.QtCore.QRect(0, 53, 336, 188)
timeline_webview:INFO UpdateLayerIndex
>      logger:INFO 16777251
preview_thread:INFO exiting thread
preview_thread:INFO onModeChanged
>     metrics:INFO Track metric: [200] http://www.google-analytics.com/collect?cid=8797f0a4-b856-40eb-a4f5-4967c497416b&v=1&tid=UA-4381101-5&an=OpenShot+Video+Editor&aip=1&aid=org.openshot.openshot-qt&av=2.4.1&ul=en&ua=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&cd1=0.1.9&cd2=3.6.3&cd3=5.10.0&cd4=5.9.2&cd5=arch-Arch-Linux&t=screenview&sc=end&cd=close-app | GIF89a€ÿÿÿÿ,D;

**Comment by TheCNixon** [comment]
Bump for importance.

**Comment by N3WWN** [comment]
I'm not sure, but you may be able to turn them off by unchecking `Send Anonymous Metrics and Errors` in the Debug preferences.

**Comment by DylanC** [comment]
@diamondburned - This has been mentioned before. #877 #776 #123

As stated in #123, this is just for gathering some system info to help the project development and track bugs on particular system configurations.

**Comment by TheCNixon** [comment]
But why do it with google's ad service and not a more private method?
