### ISSUE TITLE
Openshot crashing when adding video to timeline

### ISSUE THREAD

**Issue by sydneyjd** [OpenShot/openshot-qt#113]
Hello,
I'm running the latest version of openshot from tarball, and every time i try to drag a video to the timeline it crashes, no matter the format. I have a debug log linked. 
https://cloud.openmailbox.org/index.php/s/SOpHgtiOtrWdBAo/download
Thanks!
-Sydney

**Comment by jonoomph** [comment]
Hmmm, not sure about this one. The debug log appears to crash while exporting a video, and not related to dragging and dropping one. Try deleting the log file (~/.openshot-qt/openshot-qt.log) and run the app again and crash it as quickly as possible (to keep the log small). Thx.

**Comment by Happy-S5** [comment]
Openshot also crashes when I add video to time line. When I drag or when I right click and add.

**Comment by jonoomph** [comment]
Here we go... some big debugging improvements (if it works):
http://releases.openshot.org/windows/OpenShot-v2.0.7-3-gb0f0381-47-528-x86_32.msi, or if you need Linux or Mac versions, you can find them on the download page: http://www.openshot.org/download/ (click "Other Downloads", and get the latest one).

Our library (libopenshot) now opens up a socket to communicate with our UI (openshot-qt), and sends all debug output directly to the openshot_qt.log file.

Steps:
1) Download and install the latest version (mentioned above)
2) Preferences - Enable "Debug (Verbose)", and verify the "Debug (Port)" preference appears (it's new)
3) Close OpenShot, and delete your log file (/Users/USER/.openshot_qt/openshot_qt.log)
4) Launch OpenShot, and make it crash as quickly as possible (to keep the log small)
5) Check the log file (and be sure it contains output like this... "logger_libopenshot:INFO"
6) Attach that .log file with instructions on what you did to cause the crash (if anything)

**Comment by jGRite** [comment]
I wanna say I'm having this issue as well on Ubuntu 14.04 LTS on Openshot 2.3.3. When I drag a file (doesn't matter what kind) to openshot from "files 3.10.1" it will close openshot instantly. If I import a files within openshot this is no problem. However opening files within openshot is less intuitive because the explorer windows to files I don't need to open. I can do a debug files after this video finishes rendering.

**Comment by DylanC** [comment]
@sydneyjd @jGRite - Does this issue still exist in the latest version of OpenShot?

**Comment by DylanC** [comment]
Closing until further activity.

**Comment by mzbean** [comment]
@jonoomph I just did that but it still does that :(

**Comment by ferdnyc** [comment]
> @jonoomph I just did that but it still does that :(

@mzbean This issue was reported over 3 years ago, and closed almost 2 years ago. If you're having the same issue, please open a new report using the Bug Report template, and provide the details requested.
