### ISSUE TITLE
Openshot crash trying to import a png image sequence

### ISSUE THREAD

**Issue by jEsuSdA** [OpenShot/openshot-qt#1130]
**System Details:**
* Operating System / Distro: Debian Testing
* OpenShot Version: 2.4.1
* _Please attach log files if crash_
[openshot-errorlog.txt](https://github.com/OpenShot/openshot-qt/files/1564706/openshot-errorlog.txt)

**Issue Description and steps to reproduce:**

1 - Open Openshot-qt
2 - Drag and drop the first PNG image of a image sequence into the Project Files.
3 - Confirm you want to create a video sequence from all the PNG files.
4 - Openshot crash.

Some files to test:
[entrada.zip](https://github.com/OpenShot/openshot-qt/files/1564708/entrada.zip)

Thanks! ;)

**Comment by davegorst** [comment]
I've had the application apparently freeze while importing image sequences, when in reality it's continuing to process. A progress bar and cancel button would be helpful.

**Comment by DylanC** [comment]
@jEsuSdA - Is this an issue on the daily builds?

**Comment by AragCF** [comment]
This bug is still reproducable (runtime error, windows 8.1 x64).

**Comment by AragCF** [comment]
Also it asks me every time when I add multiple pictures. This consumes a lot of my time clicking «No».
To place a button like «Yes for all» and «No for all» would be a great idea.

**Comment by AragCF** [comment]
I moved to Kdenlive.

**Comment by HugginsHomes** [comment]
I get this with JPG images on 2.5.1 (release) as well.  Has occurred on prior versions as well.  Agreed with @AragCF that a yes all/no all button is needed.  Clicking this each time for 40+ images can be quite annoying.
