### ISSUE TITLE
Exporting project hangs on clips with modified speed

### ISSUE THREAD

**Issue by Zeerooth** [OpenShot/openshot-qt#1131]
**System Details:**
* System specs: Intel Core i7 4270HQ, 12GB RAM, 128GB SSD
* Operating System / Distro: Antergos
* OpenShot Version: Lastest in Arch repos - 2.4.1-1

My problem: I made quite a big project in Openshot and when trying to export it, it always hangs on clips with modified speed and becomes unresponsive without actually crashing. I tested it with almost all file extensions without any success.

Edit: Forget this, actually after leaving computer for a few hours it seems that my project is rendering. Just really, really slow - 1% in an hour! While taking 100% of my resources. I think it still counts as an issue though

Edit2: Okay, finally figured it out - while setting time scale to 16x the values on single clip go to enormous size effectively blocking any rendering and decreasing performance dramatically. You should do it manually.

**Comment by DylanC** [comment]
@Zeerooth - Thanks for the info!
