### ISSUE TITLE
Audio will not export with video

### ISSUE THREAD

**Issue by rjptalk** [OpenShot/openshot-qt#1133]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

This include audio already on source video as well as separate added audio track.  I changed the Audio Codec to every other thing I could think of and nothing works.

**Comment by Snapper763** [comment]
I had the same issue, I changed the Audio Codec to aac which fix that issue for me

**Comment by rjptalk** [comment]
I tried the aac fix, but it did not work for me.  I tried a number of things and finally changing the audio codex to libmp3lame worked.  I do not know why that is and that was absolutely the last option I could come up with.
