### ISSUE TITLE
Blurry Video export

### ISSUE THREAD

**Issue by Snapper763** [OpenShot/openshot-qt#1134]
**System Details:**
* Operating System / Distro: window 7
* OpenShot Version: 2.4.1

I have a video that I'm splitting up into clips. The source video is clear but the exported clip is fuzzy. The video was shot in 1080P/24 FPS, I selected that as the target and I tried MPEG, MOV, MP4 and nothing helps.

Any suggestions?

**Comment by N3WWN** [comment]
Can you post screenshots of a frame of the source video and the same frame of the exported, blurry video?  A screenshot of your entire OpenShot window with the video selected may be helpful, too.

**Comment by DylanC** [comment]
@Snapper763 - What profile did you use?

**Comment by DylanC** [comment]
@Snapper763 Can you try v2.4.2 and let us know if you have any success?

**Comment by Snapper763** [comment]
Hi,
Thanks for the suggestion. I had a video of a show my band did and wanted to edit it down to a clip of each song. I haven’t edited videos before and don’t know when I’ll need to again so I brought the tape to a editing house and paid them to do it.

Thanks again for the help,
Mike

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by peanutbutterandcrackers** [comment]
@Snapper763 - [Here](https://gist.github.com/peanutbutterandcrackers/f0f666243133e0ed25abbc12a4ba23d7) is an awesome guide if you want to become an OpenShot editing ninja. As for the performance issues, it will only get better with time... :+1:

**Comment by Snapper763** [comment]
Excellent, thanks. I’ll check it out.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
