### ISSUE TITLE
Split Clip. Play function stops at 29m59.25s

### ISSUE THREAD

**Issue by alexckent** [OpenShot/openshot-qt#1136]
* Operating System / Distro: Windows 10
* OpenShot Version: 2.4.1

In project files, I right click on a video, choose 'Split clip...' and can set the start of the clip.

However, when trying to find the end of the clip, playback freezes at just short of 30 minutes.

I can select the end point in the video after 30 minutes, but can't preview it in the 'Split Clip' dialogue.

**Comment by DylanC** [comment]
Dup of #629

**Comment by mikelacsa** [comment]
The same issue was raised in [1501](https://github.com/OpenShot/openshot-qt/issues/1501)

**Comment by mikelacsa** [comment]
The same issue was raised in [1444](https://github.com/OpenShot/openshot-qt/issues/1444)

**Comment by mikelacsa** [comment]
This issue was fixed by [#2832](https://github.com/OpenShot/openshot-qt/pull/2832)
