### ISSUE TITLE
consistently crashes at same spot when rendering (88% complete mark)

### ISSUE THREAD

**Issue by tomscotto** [OpenShot/openshot-qt#1137]
**System Details:**
windows 10 home
toshiba satellite CL45-C
2GB RAM
1.89G SDD disk space available
OpenShot Version: 2.4.1
could not find log file!!  happy to reattach if it exists and location is provided.
as in title, a video i am attempting to export crashes consistently at 88%.
[error.pdf](https://github.com/OpenShot/openshot-qt/files/1570132/error.pdf)

@DylanC - OK i found it.  for windows 10, it is:
C:/Users/USERNAME/.openshot_qt/openshot-qt.log

since it's a big, honkin' 25MB file and will take forever to upload (maybe longer) i will wait to hear from someone that needs it to fix the issue, if someone gets assigned.  i will keep the file for a while.

i'm using something called shotcut now.  great results.  it does throw an error on occasion, but right away--not after several hours of rendering.  after error, saving/exporting as a different file named hasn't failed in 4 tests so far!

**Comment by DylanC** [comment]
@tomscotto - I can't remember exactly where it is on Windows. Its some place like:
C:/Users/USERNAME/AppData/Roaming/qt_openshot.

**Comment by arsenal3k** [comment]
im having the same problem, stops around 70% and havent been able to fix it, even tried uninstalling and reinstalling the program

**Comment by phlemoine** [comment]
Happened few weeks back, music track was 2 mins+ and was longer than video. fixed the issue by cutting music to same duration as video sequence. However, issue happened again today, at ~5% rendering. Unsuccessfully tried various video profiles.
Using windows 10, nov23,2017 daily build, 6 tracks, mix of png, jpg, webm, mp3 and wav. let me know what/where logs are needed to help debugging

**Comment by DylanC** [comment]
@tomscotto - Perhaps you can try to reduce the quality of the images used? It seemed to work for #1323. Also maybe try this in a daily build of Openshot.

**Comment by DylanC** [comment]
@tomscotto Can you try v2.4.2 and let us know if you have any success?

**Comment by xcbxcbx** [comment]
I also struggled with rendering getting stuck at the same spot with a particular project.  After a whole lot of trial and error, I found that the Openshot render worked after I re-encoded the original video file with Handbrake using Constant Framerate instead of Peak Framerate in the video settings.
