### ISSUE TITLE
Incorrect time reported

### ISSUE THREAD

**Issue by alexckent** [OpenShot/openshot-qt#1139]
**System Details:**
* Operating System / Distro: Windows 10
* OpenShot Version: 2.4.1
**Issue Description and steps to reproduce:**

The time ruler bar is sometimes inaccurate. 

As you can see from the image, the time is at 1h 26m but the time ruler is showing approx 6h 1m.

![image](https://user-images.githubusercontent.com/6452347/34170555-258dc0b2-e4e3-11e7-96d1-4b2faa60afb5.png)

**Comment by peanutbutterandcrackers** [comment]
I wonder if it is because you have an incorrect video profile selected?

For instance, if the profile is '24 fps' but your camera shoots at '30 fps' or something?

**Comment by alexckent** [comment]
I'm trying to remember about this issue from memory as no longer have the files, but I'm not sure about it being a video profile issue. The problem seemed to kick in after using the application for half an hour or so. 

It wasn't a big deal as I was restarting the application a lot anyway. I found that after a restart, media objects would sometimes have shifted around a little so I was used to restarting often and especially before export to avoid a crash.

Plus it didn't affect anything other than the ruler - I could see the time indicator was accurate.

**Comment by peanutbutterandcrackers** [comment]
Hmm... I see. Well I'm glad that it wasn't much of a problem.

Regarding the media objecs shifting around a little during restart, perhaps it has something to do with autosave too? o.O I had similar issue but I save only manually, and whenever it reports a change when I try to exit, I discard all the changes...

Openshot will get better though, in the future, with our help. So, yeah. I look forward to that. :)
