### ISSUE TITLE
WINDOWS 2.0.6: right button in clips video unfolds anything 

### ISSUE THREAD

**Issue by telelauro** [OpenShot/openshot-qt#114]
in this third version ( and others yes it is ok) when I add a video clip, and give the right mouse button  no unfolds anything,  I want delete the clip of the project, or preview it, or choose a piece of the video file to add it to the edit line, and anything it possible... why?

**Comment by jonoomph** [comment]
I think this is fixed in the latest version (which will be release very shortly). I'm going to go ahead and close this, but please open again if you still notice the problem.
