### ISSUE TITLE
QT_PLUGIN_PATH should not be exported as a system-wide environment variable

### ISSUE THREAD

**Issue by stuartpb** [OpenShot/openshot-qt#1140]
The Windows installer for OpenShot sets `QT_PLUGIN_PATH` to `%PROGRAMFILES%\OpenShot Video Editor\` as a system-wide environment variable. This causes issues for other Qt-based applications, such as Ultimaker/Cura#1722. As noted in https://github.com/Ultimaker/Cura/issues/1722#issuecomment-352893941, the official documentation at  http://doc.qt.io/qt-5/deployment-plugins.html states:

> Note: `QT_PLUGIN_PATH` should not be exported as a system-wide environment variable since it can interfere with other Qt installations.

Since Qt already checks the application's directory for plugins, removing this environment variable from the installer will not adversely affect OpenShot's execution in any way.

**Comment by stuartpb** [comment]
As noted in https://github.com/Ultimaker/Cura/issues/1722#issuecomment-353022457, this appears to be [fixed by current installers](https://github.com/OpenShot/openshot-qt/blob/master/installer/windows-installer.iss#L86) (though I'm not sure that blindly *unsetting* these system-wide environment variables is appropriate, either.)

**Comment by michalfapso** [comment]
Thanks, @stuartpb. We had an issue with our application when it didn't work correctly for one user and it took us few days to find out, that OpenShot set the system-wide QT_PLUGIN_PATH variable. Also thanks to @jonoomph who fixed this issue back in 2016.
