### ISSUE TITLE
Question: How to select an audio track?

### ISSUE THREAD

**Issue by wboote** [OpenShot/openshot-qt#1141]
Hi guys,

Great software!  Do you know if i'm able to select a single audio track other than the default one for an imported vid?

Thanks in advance,

Waz.
=)

**Comment by N3WWN** [comment]
Hi @wboote !

I'm not entirely sure what you're asking, but I think you may be asking how to replace the audio track for a clip.

You can do this by adjusting the volume for the track with the audio you want to replace, or you an separate out the audio and then delete the audio clip.

To add in the replacement audio, you can place the clip with the audio on the timeline.  If the clip with the replacement audio also has video, you can either place the new clip on a track below the video that you want to see, or you can split the audio and delete the video.

Hopefully this helps!

**Comment by DylanC** [comment]
@wboote - Follow suggestion provided by N3WWN.

**Comment by wboote** [comment]
@DylanC  -  to be clear; I have an existing video with two audio streams; Italian and English.

I want to create a crop of this video and render out only the English audio stream.


Cheers,

Waz.
=)

**Comment by N3WWN** [comment]
@wboote , if you add the clip to the timeline and then right click and use one of the two `Separate Audio` options, does that give you the two streams in separate tracks that you can operate on?

**Comment by OmarBond** [comment]
Separate Audio command only separates the primary audio channel (e.g. Italian instead of English) to a separate track. Question is, if one goes into the file's Properties, where does one select the correct Audio Track there?

**Comment by sylock** [comment]
I have the same need. From the properties of the clip, I cannot chose an audio track (there are 5 audio tracks to my MKV and I need to do mixing of these audio tracks).
Is there a way to handle this with openshot?

**Comment by wboote** [comment]
You can pre process the file and strip out other audio streams:

# Step 1
```
ffprobe -v error -select_streams a -show_entries stream=index,codec_name,channels,bit_rate:stream_tags=language -of default=noprint_wrappers=1:nokey=1 input.mp4
```
# Step 2
## Example: to keep only audio stream 0:2 (i.e. “stream 2” from your ffprobe):
```
ffmpeg -i input.mp4 -map 0:v -map 0:a:2 -c:v copy -c:a copy -dn output.mp4
```
This will produce output.mp4 with all the original video, and only the single specified audio track.


# detail:
Here’s a Windows-style ffmpeg command that keeps all video streams intact, but only one audio stream (replace N with the audio‐stream index you got from your ffprobe):
```
ffmpeg -i input.mp4 
  -map 0:v           <!-- keep every video stream -->
  -map 0:a:N       <!-- keep only audio stream N -->
  -c:v copy          <!-- copy video codecs as-is -->
  -c:a copy          <!-- copy audio codec as-is -->
  -dn                 <!-- drop any data streams -->
  output.mp4
```
