### ISSUE TITLE
Bad render, Video different from preview window

### ISSUE THREAD

**Issue by pls8xx** [OpenShot/openshot-qt#1142]
**System Details:** PC 
* Operating System / Distro: ?Windows 10
* OpenShot Version: ?2.4.1

* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

**Comment by aluit** [comment]
I also have this problem. I'd like to know what settings lead to a good render. I had jitter in my mp4 video (I couldn't use the default h.264, as no audio was produced.) Youtube fixed the jitter in that video.
My current one has worse problems, presumably from rendering crossfade transitions. Some formats cause the program to close.
PC, Windows 7, OpenShot 2.4.1
[astrodemo.zip](https://github.com/OpenShot/openshot-qt/files/1594227/astrodemo.zip)

**Comment by pls8xx** [comment]
It's possible that my initial problems were caused by not setting the profile at the start of my project or maybe selecting a render not compatible with the profile.

I use video editing for a karaoke site that supports video. The karaoke site applies a huge compression on the video with a flash recorder. What works best at the site is to feed the flash app with a 320x240 h.264 video. The 'Mobile' 320x240 has worked good for me.

I usually edit with Corel software, but I was looking for a free editor that other members at the karaoke site could use.

**Comment by peanutbutterandcrackers** [comment]
@pls8xx - so has this issue been resolved, good sir?

@aluit - could you please try what @pls8xx has done (using the 'mobile'  profile)? Thanks!

**Comment by aluit** [comment]
Sorry for the long delay in replying. My jitter problem seems to have gone away when I use a different audio format. I got no audio with h.264, audio but jittery render when using mpeg4, but when I took up your suggestion of using Ogg/Vorbis, I got good render plus audio. Hooray!

**Comment by peanutbutterandcrackers** [comment]
Awesome! Glad that it has worked out for you.

If you want, please do try out our daily builds from the [download](https://www.openshot.org/download/) page by clicking on the 'daily builds' button. :)
