### ISSUE TITLE
Timeline Cursor Issues

### ISSUE THREAD

**Issue by m3n7alpiracy** [OpenShot/openshot-qt#1143]
**System Details:**
* Ubuntu 16.04
* OpenShot Version: 2.4.1

I am rendering 60fps clips and when I switch the default profile to 60fps from the default (so I can export without having to change all the settings every time) the timeline cursor keeps going past the clip length. Like more than double. I have to change the profile to 24fps for the cursor to stop at the end of the clip.

Not sure if this is intentional, but it's extremely annoying! Please fix ASAP!

**Comment by peanutbutterandcrackers** [comment]
Could you please also give some screenshots so that it can help the devwlopers fix the issue ASAP? Thanks! :)

P.S: If the video is originally shot at x-fps and one uses y-fps profile instead, these issues will arise. Please make sure that it is not what is happening. Thanks!
