### ISSUE TITLE
Editing size of displayed video?

### ISSUE THREAD

**Issue by TheWeirdOtaku** [OpenShot/openshot-qt#1146]
* Operating System / Distro: Win 8.1
* OpenShot Version: 2.4.1

Sorry if the title isn't clear enough, I'm not sure how else I should put it.

I have a question, is it possible to cut fx. the sides off of the video, so I'm left with the middle part, or is that just not possible?
I'm not sure how to explain it, but imagine you have these 2 videos of the exact same thing, and you want them to play side by side, but it's split in the middle, so you can see half of each video.

**Comment by N3WWN** [comment]
Is it possible for you to post a link to an example of the original video (or one like it) and then an example of how you'd like it to look?

Thanks!

**Comment by TheWeirdOtaku** [comment]
I'm not completely sure what you mean with linking the original video, but I'd l like it to look like this video: https://youtu.be/Ucz-9VwShoI?t=3m19s

Thank you too!

**Comment by N3WWN** [comment]
Thanks for linking to an example of the output.

What does the original video look like?  

Is it a [vertical video](https://en.wikipedia.org/wiki/Vertical_video) displayed landscape (with black bars on the side)?  Is it a full screen vertical video (vertical video displayed portrait without black bars on the side)?  Or is it a full screen horizontal video that you'd like to crop a portion out of?

**Comment by TheWeirdOtaku** [comment]
It's a full screen horizontal video.

**Comment by N3WWN** [comment]
For the left and right videos, you can probably just adjust the `Location X` property of the two videos.

For the middle video, you will likely need to crop it outside of OpenShot.

But, if you're going to crop the middle one, you may as well use that as the only clip and position it 3 times.

I know that probably doesn't help a lot, but perhaps it'll get you going in the right direction.

**Comment by DylanC** [comment]
Closing as answered. Thanks @N3WWN
