### ISSUE TITLE
Crash when adding video to timeline or trying to play timeline

### ISSUE THREAD

**Issue by rmbradburn** [OpenShot/openshot-qt#1147]
**System Details:**
* Operating System / Distro: macOS 10.13.2
* OpenShot Version: 2.4.1
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
When dragging clips to the timeline, the program crashed, immediately closing. Eventually, I was able to add clips to the timeline using right-click, "Add to timeline". However, when I press "Play" to review the timeline, OpenShot immediately crashes and closes. It was working fine for several hours while I was learning to use it, but now crashes consistently.

**Comment by rmbradburn** [comment]
I'm not seeing an app-specific crash log in Console; however, I'm new to this, so if there's somewhere or somehow else I should be looking for a crash log, let me know.

**Comment by DylanC** [comment]
@rmbradburn Can you try v2.4.2 and let us know if you have any success?
