### ISSUE TITLE
Crash during launch - Cx_freeze

### ISSUE THREAD

**Issue by songsammy** [OpenShot/openshot-qt#1148]
**System Details:**
* Operating System / Distro: win7 64bit
* OpenShot Version: 2.4.1
* crashed
![openshot](https://user-images.githubusercontent.com/30046778/34300990-96a22688-e765-11e7-9d50-fff364ed6ea9.PNG)

**Issue Description and steps to reproduce:**
I tried to reinstall , but failed to . I will try later tomorrow.

**Comment by dietervanmarcke** [comment]
Same problem here.  I tried reinstalling the last version and the last-but-one; but both gave the same error

**Comment by peanutbutterandcrackers** [comment]
Hey there! 

It has been reported that this issue affects only certain users in the computer, and thus, it is a user-related issue. Some report that the admin could run OpenShot while the standard user could not, and vice-versa. 

A user recently reported that he [resolved](https://github.com/OpenShot/openshot-qt/issues/1244#issuecomment-365036861) this issue by copying openshot.settings file from the standard user (or whichever user can use OpenShot in your windows machine) to the admin user (or whichever user can NOT use OpenShot). He also recommends having a backup made of the openshot.settings file.

Please note that the solution is edited in at the very end of the comment.

Hope this helps. :)
All the very best!

**Comment by DylanC** [comment]
Closing this question as answered.

**Comment by peanutbutterandcrackers** [comment]
Please do look forward to v2.4.2. This issue has been put on the list of the 'critical bugs to be fixed' for the release. OpenShot should finally work quite well on Windows Machines with v2.4.2. Please, do however continue to support OpenShot. Perhaps test the latest [daily build](https://github.com/OpenShot/openshot-qt/releases/tag/daily) if you have the time and report the issues as you encounter them. Thanks!
