### ISSUE TITLE
Blocked update openshot

### ISSUE THREAD

**Issue by KMCG13** [OpenShot/openshot-qt#1149]
system : windows seven 34bits
version : openshot video editor 2.4.1

My question is  : what is the solution after deployement client openshot Video Editor on W7 workstation, for blocked the upgrade of application openshot for the users.
Where find in base regedit the line for blocked this upgrade

Thanks

**Comment by KMCG13** [comment]
My question is : what is the solution after deployement client openshot Video Editor on W7 workstation, for blocked the upgrade of application openshot for the users.
Where find in base regedit the line for blocked this upgrade

Thanks

**Comment by DylanC** [comment]
@KMCG13 - Sounds like your workstation is on a proxy and security rules block the url. This is not a problem with OpenShot.

**Comment by KMCG13** [comment]
Ok thank you for your response, but for my question, it's impossible for blocked it with application openshot directly

**Comment by DylanC** [comment]
@KMCG13 - Usually websites are blocked in groups. So only very well recognized sites as "Safe" will not be blocked such as Microsoft and Google websites for example.
