### ISSUE TITLE
WINDOWS 2.0.6: the clips goes so slow and faltering

### ISSUE THREAD

**Issue by telelauro** [OpenShot/openshot-qt#115]
when I add a video file to project and visualize the video stutters and does not go soft. I do not think it's a problem of my computer (ROG Assus core7, 16 RAM, SSD ...). Arhivos natives are, .mp4 (1440 x 1080 / bit ratio 11911kbits / total kbitsps 12037 bits / 25 fps)

**Comment by jonoomph** [comment]
This is pretty similar to https://github.com/OpenShot/openshot-qt/issues/116, so I'm marking this as a duplicate.
