### ISSUE TITLE
No support for avchd?

### ISSUE THREAD

**Issue by CraftyCarper1** [OpenShot/openshot-qt#1150]
**System Details:** 
* Operating System / Distro: ? Win 7 x64
* OpenShot Version: ? 2.4.1
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
I have tried a few times to edit a video but failed. The video is AVCHD (.m2ts) from my camcorder. Is there any support for this? All that happens is the program stalls and says Not Responding.

**Comment by N3WWN** [comment]
Some video formats may not be supported or are in a format that requires a lot of processing overhead.  The rendering overhead is made worse if the project profile does not match the source video.

I edit AVCHD (.mts) files by first converting them to mp4 file using a tool like [Handbrake](https://handbrake.fr) or [ffmpeg](https://ffmpeg.org).

**Comment by DylanC** [comment]
@CraftyCarper1 
Maybe not supported yet. Try the suggestion by @N3WWN
