### ISSUE TITLE
No picture at the end of the video (black screen)

### ISSUE THREAD

**Issue by eoglasi** [OpenShot/openshot-qt#1153]
**System Details:**
* Operating System / Distro: Win10 64bit
* OpenShot Version: 2.4.1

**Issue Description and steps to reproduce:**

Creating video, content:
0/ photo (fade in fast, fade out fast)
1/ video (fade in fast, fade out fast)
2/ photo (fade in fast, fade out fast)

The video is short, I review it in the program and everything is fine.

When I do export in the new video for the last 10 seconds the screen is black (no picture, tone is on). The image appears only in the last second.

Where am I wrong, what is the problem?

**Comment by N3WWN** [comment]
Can you provide a screenshot (or several) of your timeline so we can see how your project is set up?

An example of the output video would be helpful, too.

Thanks!
