### ISSUE TITLE
OpenShot ignores mute(dead) keys in input fields

### ISSUE THREAD

**Issue by thorsig** [OpenShot/openshot-qt#1156]
**System Details:**
* Operating System / Distro: Kubuntu Artful (17.10)
* OpenShot Version: 2.4.1 (AppImage)

Select to use an Icelandic keyboard (in terminal, "setxkbmap is" if you're not already using an Icelandic keyboard)

In a project, create a new text rendition with movement, e.g. the Star Wars scroller.

In any field, first try copy-paste this text: "áéýúíóÁÉÝÚÍÓ"  (it will work perfectly)

In any other field, try typing in the text. It's done by pressing the key  second to the right from "l" (ell) and then the appropriate letter key ( ' + a = á ) - this will not work. You will get "aeyuioAEYUIO".

Apparently OpenShot is interfering with the keyboard input methods. That is unacceptable. It should in all cases and without exception use the system IME.

Also this behavior makes it impossible for me to type directly into OpenShot fields in Chinese or Japanese (yes, I've tried, yes I know how to write in Chinese and Japanese...)

**Comment by peanutbutterandcrackers** [comment]
@DylanC - being a 'foreigner' myself, I hope this issue gets some attention.

**Comment by DylanC** [comment]
@peanutbutterandcrackers - Hopefully. It looks harder to reproduce than most issues here.

**Comment by peanutbutterandcrackers** [comment]
@DylanC - step 1: Add Nepali keyboard layout from your layouts option (does not require IME)
Step 2: Try to create an animated title using random Nepali letters
Step 3: "Oh! That!"

:D :D :D

**Comment by fengsanv** [comment]
i have  meet this  problem.  Can not input  local  language  .When i use sogou  input  Chinese,  it  can not  call IME..Very Very strange .This is  a BIG  bug .  why  do not  solve it  for  long time .  i  doubt.
