### ISSUE TITLE
The program close unexpectedly at the opening.

### ISSUE THREAD

**Issue by Molo2007** [OpenShot/openshot-qt#1157]
**System Details:**
* Operating System / Distro: Ubuntu (17.04)
* OpenShot Version: 2.4.1 (Applmage)

**Issue Description and steps to reproduce:**

I open the program and it show me the initial screen for one thousandth of a second and close the program.

**Comment by peanutbutterandcrackers** [comment]
Could you please try again with the latest app image or use the ppa openshot.org/ppa instead? Thanks!
