### ISSUE TITLE
 32-bit version ?

### ISSUE THREAD

**Issue by oren-evron** [OpenShot/openshot-qt#1158]
**System Details:**
* Operating System / Distro: Windows 7, SP1, 32-bit
* OpenShot Version: ?latest

**Issue Description and steps to reproduce:**
Hi,
I require the 32-bit version.
Currently, all others builds are on 64 bit - and installation is failing.
![image](https://user-images.githubusercontent.com/4487884/34342783-9dfdacd0-e9c3-11e7-93f0-97f6df5c343f.png)
Thanks in advance - Oren

**Comment by peanutbutterandcrackers** [comment]
Openshot is currently not available in 32 bit version. However, Jonathan Thomas, the lead developer, has mentioned in his [blog post](www.openshotvideo.com/2018/01/happy-new-year-2018.html) that he is going to work on a 32 bit version as well. I hope that solves your issue. Please do not forget to close the issue once it is solved/resolved. Thanks.

**Comment by DylanC** [comment]
@oren-evron 
This will be released in the future. The lead dev will be working on it.
