### ISSUE TITLE
ImportError: No module named '_openshot' on Windows 10

### ISSUE THREAD

**Issue by Scarfmonster** [OpenShot/openshot-qt#1159]
**System Details:**
* Operating System / Distro: Windows 10 64-bit
* OpenShot Version: 2.4.1

**Issue Description and steps to reproduce:**
Fresh installation of OpenShot, when trying to start I get the following error:

![screenshot_60](https://user-images.githubusercontent.com/6295315/34366329-7554d9a2-ea9a-11e7-8c57-7062c03dd04f.png)

I tried to look for a similar issue but can't find anything. I also tried reinstalling and restarting the computer but nothing seems to work.

**Comment by JAndersM** [comment]
Had the same bug today when trying to install OS under Win10

**Comment by DylanC** [comment]
@Scarfmonster Can you try v2.4.2 and let us know if you have any success?

**Comment by Scarfmonster** [comment]
I just realized that my previous reply didn't send for some reason. Anyway, 2.4.2 32-bit version works for me, although very slowly, 64-bit version doesn't and gives a similar error.
![screenshot_60](https://user-images.githubusercontent.com/6295315/42709114-b049e91c-86df-11e8-9a7f-770180a65ee0.png)

**Comment by peanutbutterandcrackers** [comment]
Could you please [attach the logs](https://gist.github.com/peanutbutterandcrackers/d84c257e74b72d8b06b4daffaebc5a14) so that the devs can investigate on this? Thank you!

**Comment by Scarfmonster** [comment]
I deleted the .openshot_qt folder, reinstalled the 64-bit version of openshot and started it. The only log file created is openshot-qt.log and it's completely empty. It's the only file inside .openshot_qt beyond some empty folders.

**Comment by peanutbutterandcrackers** [comment]
Did you run openshot again after doing all that? If you do, the log files will not be empty. Or, should not be, anyway.

**Comment by Scarfmonster** [comment]
Yes, I did run Openshot, it created the log file & folders, but the log file is empty. Openshot-qt.log is the only file and liopenshot.log isn't created at all. This is only the case with the 64-bit version of Openshot.

**Comment by peanutbutterandcrackers** [comment]
Closing as abandoned.
