### ISSUE TITLE
WINDOWS 2.0.6: the buttons play/stop doesn,t works very well.

### ISSUE THREAD

**Issue by telelauro** [OpenShot/openshot-qt#116]
when I preview video clip, and want to stop, or freeze instantly , unfortunately the video continues to play. and after a few second it stands alone ... its happend with any clips.

**Comment by nitehawk39** [comment]
I also experienced this laggy playback.

**Comment by jonoomph** [comment]
What are you system specs? I've noticed this also, but it only happens on a slower system. All of my newer systems are pretty instant and very responsive.

That being said, I'm still investigating why there is a UI lag on slower systems. The UI should be on it's own thread, and should respond quickly, even if the background processing is chugging along.

**Comment by telelauro** [comment]
Sorry jonathan...
I have windows 8.1 and my computer is asus rog core i7 and 16RAM SSD
samsung,
And i can,t stop very well the videos too

El jueves, 17 de marzo de 2016, Jonathan Thomas <notifications@github.com>
escribió:

> What are you system specs? I've noticed this also, but it only happens on
> a slower system. All of my newer systems are pretty instant and very
> responsive.
>
> That being said, I'm still investigating why there is a UI lag on slower
> systems. The UI should be on it's own thread, and should respond quickly,
> even if the background processing is chugging along.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenShot/openshot-qt/issues/116#issuecomment-197672847>
>


-- 
"Dabilen kamerari Kroma-keyrik ez"

**Comment by telelauro** [comment]
I bought this machine for editing my audiovisuals works! I have two
partitions UBUNTU and Windows.... And i think it is fast for openshot
too!!! ;)

[image: Imágenes integradas 1]

2016-03-17 14:09 GMT+01:00 tele lauro <telelauro@lauro20.org>:

> Sorry jonathan...
> I have windows 8.1 and my computer is asus rog core i7 and 16RAM SSD
> samsung,
> And i can,t stop very well the videos too
>
>
> El jueves, 17 de marzo de 2016, Jonathan Thomas <notifications@github.com>
> escribió:
>
>> What are you system specs? I've noticed this also, but it only happens on
>> a slower system. All of my newer systems are pretty instant and very
>> responsive.
>>
>> That being said, I'm still investigating why there is a UI lag on slower
>> systems. The UI should be on it's own thread, and should respond quickly,
>> even if the background processing is chugging along.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/OpenShot/openshot-qt/issues/116#issuecomment-197672847>
>>
>
>
> --
> "Dabilen kamerari Kroma-keyrik ez"
>
>


-- 
"Dabilen kamerari Kroma-keyrik ez"

**Comment by jreynojustin** [comment]
OpenShot is now in Version 2.2 if you are still noticing issues in the latest version please re-open this issue letting us know.
