### ISSUE TITLE
I would like to determine the duration time of fade in and fade out

### ISSUE THREAD

**Issue by Doideira** [OpenShot/openshot-qt#1160]
**System Details:**
* Operating System / Distro: Debian 9.3 amd64
* OpenShot Version: 2.3.4
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
Long time ago I used to choose the time fade in or fade out lasts in seconds (booth video and audio), but now there's only "fast" and "slow" options. I don't even know how long is "fast" or "slow". Isn't there a full properties box for clips anymore?

**Comment by N3WWN** [comment]
It has been a while since I used OpenShot 2.3.x, but with 2.4.x you can use keyframes for the the `Alpha` property to specify the fade points.  See also : https://github.com/OpenShot/openshot-qt/issues/784#issuecomment-354779030

**Comment by DylanC** [comment]
@Doideira - Follow both suggestions above. The answers are quite good. Thanks.

**Comment by WebGuyJeff** [comment]
> @doideira - The most preferable way to do what you want is to use keyframes, as @N3WWN has pointed out [Go [Here](https://www.youtube.com/watch?v=P3zIprwr1rk) for an introduction to animation (keyframes) from Mr. Jonathan Thomas -- the lead developer of OpenShot -- himself. [Here](https://www.youtube.com/watch?v=mgi4esWA84M) for another video introducing Keyframes in general. [Here](https://www.youtube.com/watch?v=nEyrC1v-M1s) for another neat thing you can do with keyframes. And finally, and most importantly [here](https://www.openshot.org/static/files/user-guide/clips.html#properties) for all the parameters you can keyframe in OpenShot].
> 
> However, if you can't be bothered with all that and want an even easier work-around, try this: On your video in which you want to apply the fade effect, drop two transitions (preferably just simple fade) at the two ends. You'll be able to manually adjust the transitions length using the mouse. For the last (exiting) transition (fade-out) however, you'll have to right click and click on 'reverse transition' for this to work. Here is a screenshot: ![fade-manual](https://user-images.githubusercontent.com/26764547/36060307-073cef38-0e6f-11e8-90c9-49b4460fce02.png)
> 
> Hope this helps!

Anybody have any tips on adjusting duration with the mouse?

I'm hovering all around the transition and it's edges and all I can do is move it. when I try to adjust the properties in the left sidebar, the duration is greyed out and locked to 10 seconds. That's a little epic for a 30 second clip!

**Comment by Colorjet3** [comment]
I am currently running the latest DEV Daily build of v3.0.0.  The Duration attribute in the properties is always greyed out.  I am able to select the transition and grab either the left edge or the right edge and and change the duration.  Another way to do this is change the values of the End attribute in the Properties of the Transition.  This will automatically change the Duration.

I am able to do this in both Windows 11 Pro and Ubuntu 22.04 LTS.
