### ISSUE TITLE
Export Video/Advanced/Audio Settings/Audio codec: setting not saved in project

### ISSUE THREAD

**Issue by phlemoine** [OpenShot/openshot-qt#1161]
**System Details:**
* Operating System / Distro: windows 10
* OpenShot Version: 2.4.1 daily build Nov23, 2017

**Issue Description and steps to reproduce:**
open export video dialog, click Advanced, then Audio Settings. Change Audio Codec (in my case ac3 to "aac"), and click export video. 
Re-open export video dialog, click Advanced/Audio Settings. Codec value is back to ac3

**Comment by N3WWN** [comment]
I would like to be able to save the Advanced export settings, also! 😁

**Comment by DylanC** [comment]
Dup of #1107
