### ISSUE TITLE
Cracking and Popping on my Exported Video

### ISSUE THREAD

**Issue by vincentupsdellred** [OpenShot/openshot-qt#1162]
**System Details:**
* OS: Microsoft Windows 10 Home Build 16299
* OpenShot Version: 2.4.1 (Installed on Flash Drive)
* Computer Model: HP 15 Notebook PC
* Headphones Brand: Zumreed
* Flash Drive: EMTEC 16 GB

**Issue Description:** I have experienced clicking and popping on a video I exported. The clicking and popping occur in parts of the video where multiple clips are overlaid. Also, the audio is completely ruined between 1:35 and 1:48. No such problems existed in the preview. I have no idea how to reproduce these problems.

**Comment by DylanC** [comment]
@vincentupsdellred - Any luck with a newer daily build? I saw a fix went in for this 8e96e1779273c7b619f2831d6734fc259dd5418a

**Comment by DylanC** [comment]
@vincentupsdellred Can you try v2.4.2 and let us know if you have any success?
