### ISSUE TITLE
Splitting clips with mono sound causes audio to be shifted

### ISSUE THREAD

**Issue by gtjoseph** [OpenShot/openshot-qt#1163]
Was: Trimming the front of a 1080p60 video offsets audio by the clip amount

**UPDATE**

This appears to be related to manipulating an input source file with mono audio.  If I pre-convert the clip to stereo with 
```
ffmpeg -i mono_clip.mp4 -ac 2 stereo_clip.mp4
```
Then the clip can be manipulated just fine.  
Making the default project audio mono does NOT help.

**System Details:**
* Fedora 27 X86_64
* OpenShot Version: (from github master) v2.4.1-2-g445a326d
* ffmpeg: (rpmfusion) 3.3.5
* libopenshot: (from github master) v0.1.9-1-g7490aaa
* libopenshot-audio: (from github master): v0.1.5

**Steps to Reproduce**
* Create a  1080p60fps video with a synchronizing sound like a clapper .  I used my Pixel XL ...
** Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc, smpte170m), 1920x1080, 32925 kb/s, SAR 1:1 DAR 16:9, 60.02 fps, 60 tbr, 90k tbn, 180k tbc (default)
** Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, mono, fltp, 96 kb/s (default)
* Open openshot with an empty project and import the video clip.
* Drag it into the timeline.
* Either use properties or grab the clip start handle and advance the start a few seconds.
* Drag the clip back to the start of the timeline if necessary.
* Play the result.  It should play correctly.
* Export the result as 1080p60fps.
* Save as a new project and exit openshot.
* Play the exported video.  If you get any audio, it'll be offset.
* Open openshot again and open the existing project.
* Preview the clip.  The audio will be offset if it still exists at all.

Originally I thought this issue was one of not exporting or saving audio at all but after a few days of experimenting, I realized that my tests were causing the audio to get shifted right off the video clip.  With a shorter test video and a shorter trim from the front, I realized the audio was being shifted. 

THIS DOES NOT HAPPEN ON 30FPS VIDEOS!!  Maybe the metadata being used to sync the audio and video is always assuming 30fps and calculating the shift on 30 instead of 60.

If I trim the front of the clip using ffmpeg from the command line, I can import it to openshot and continue to modify and export it as long as I don't change the start position.

If the issue rings any bells, let me know where to look.  I'd be glad to fix it create a pull request.

**Comment by peanutbutterandcrackers** [comment]
@DylanC - Aye, good sir, here's an issue that needs your scrutiny. The bounty seema plentiful. And the territory is not entirely uncharted, aye! *tips pirate hat*

**Comment by peanutbutterandcrackers** [comment]
@gtjoseph - Aye good sir, methinks this is a great bug report. Hope you continue your voyages to these seas and provide us with plenty of bounty. We shall try to squash them filthy bugs, together, in pirate brotherhood, following the footsteps of the great pirate Stallman. Hrr! Hrr!! Hrrr!!! *tips pirate hat*
