### ISSUE TITLE
arabic and animated titles

### ISSUE THREAD

**Issue by abogadeer** [OpenShot/openshot-qt#1165]
Windows 10 
Openshot 2.4.1
Blender 2.79

To be honest, I am not sure if the problem is from openshot or blender

When I type Arabic text in Animated titles, the text is not displayed after rendering.
All animated titles won't work with Arabic. I tried them all. At least the on which worked with me.

I tried mixing Arabic and English text with no success.

Can you please check this issue

thanks

**Comment by DylanC** [comment]
@abogadeer  - Looks like a Blender issue:
https://blender.stackexchange.com/questions/3522/how-can-i-add-text-in-a-non-english-language
