### ISSUE TITLE
video deleted while editing now i can't use open shot

### ISSUE THREAD

**Issue by androidjames** [OpenShot/openshot-qt#1166]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

**Comment by peanutbutterandcrackers** [comment]
Good sir, you need to provide more details so that we can help you... were you using the latest version of OpenShot (v 2.4.1)?

**Comment by DylanC** [comment]
Closed due to lack of details.
