### ISSUE TITLE
Static in my video.

### ISSUE THREAD

**Issue by Naixon** [OpenShot/openshot-qt#1167]
**System Details:**
* Operating System / Distro: Windows 10 Home
* OpenShot Version: 2.4.1.0

**Issue Description and steps to reproduce:**
I was editing a video with a song that I made and when I played it, all that I heard was static.
Reproduction steps:
1. Open Openshot
2. Import an image and wav file.
3. Put them in one video and play.

**Comment by DylanC** [comment]
Dup of #1162

**Comment by Naixon** [comment]
It works with v2.4.2, thanks!
