### ISSUE TITLE
Problem fade out

### ISSUE THREAD

**Issue by afranio1** [OpenShot/openshot-qt#1169]
**System Details:**
* Operating System / Distro: Windows 10 Home
* OpenShot Version: 2.4.1
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
When I insert a fade in, everything is fine; when I insert a fade out, in the preview it is perfect but when I export the file the fade becomes 30 seconds and more!
Is there a solution or is it a bug in the app?
Thank you.
Ciao

**Comment by dustyridge** [comment]
How did you resolve this issue

**Comment by peanutbutterandcrackers** [comment]
Could you try using 'alpha' keyframes instead, as a work around? You might want to look up 'OpenShot Keyframes' on youtube and read the docs at openshot.org 

Hope that helps
