### ISSUE TITLE
Crashes at transition

### ISSUE THREAD

**Issue by trista-la-vista** [OpenShot/openshot-qt#1171]
**System Details:**
* Operating System / Distro: Windows 10
* OpenShot Version: 2.4.1
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
I added a transition to my video, but every time I try to play the video, it'll crash when it hits the transition. How can I fix this?

**Comment by peanutbutterandcrackers** [comment]
Sorry about this issue. This doesn't happen on Linux machines. The development of OpenShot is currently beinf handled by a single man and therefore he is not able to fix all the issues by himself. Please do however continue to support OpenShot. It will get better with time... sorry for the inconvienience...

**Comment by cptX** [comment]
This does crash on Linux Mint 18.3 with version 2.4.1-dev1 daily build. Openshot crashes the moment it reaches a transition... Problem is critical as I cannot create any video now.

**Comment by lordpyre** [comment]
I observed the same on Windows 10, both with the daily `OpenShot-v2.4.1-136-g7ee5946-a67583a2-e7451201-x86_64.exe' and with the 4.1 release. If I have more transitions in one track, the preview and video generation crash when they reach a transition. Moving the transitions to separate tracks solved the problem as a workaround. I hope it helps others too because it definitely made my weekend ;-)

**Comment by peanutbutterandcrackers** [comment]
Strange, doesn't quite crash on my Linux Mint Computer. I am not quite using the absolutely latest version. I'll try to re-check again once I have upgraded everything...
![screenshot at 2018-05-30 12-10-57](https://user-images.githubusercontent.com/26764547/40702736-aa537e2e-6402-11e8-89bb-6d25fdf56644.png)

**Comment by lordpyre** [comment]
On Windows 10, it looks like this: 
![image](https://user-images.githubusercontent.com/10208306/40704276-ef0e962c-63e7-11e8-96cf-a19d5ab30227.png)
If I move one of the videos to another track, it doesn't crash. But of course, it's not the same fun ;-)
For me, just deleting the transition and setting up fade-out/in for the videos solved the problem as a workaround.
But if I can help in resolving the issue, let me know.

**Comment by peanutbutterandcrackers** [comment]
Strange, I am using the latest version from the ppa right now and don't encounter the crash on transition. Perhaps @cptX, good sir, you need to upgrade everything, and also [attach the logs]() in case the crash reoccurs. Hope that helps.

@lordpyre - Thank you for your offer to help. Openshot v2.4.2-rc1 is out. Perhaps you'd like to try that out and report all the bugs that you can find? Thanks!

**Comment by lordpyre** [comment]
hey, I just took a quick look at the rc1 version. I can see that compared to 2.4.1 the performance of handling sliced videos improved a lot. I like it :) but the crash with the transition is still there. :(

**Comment by peanutbutterandcrackers** [comment]
@cptX - Yes, it is available for linux too as an appimage. [Click here](https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.4.2-rc1-x86_64.AppImage) to start downloading it. Or, go to openshot.org/download and click on the 'daily builds' button and download OpenShot-v2.4.2-rc1-x86_64.AppImage from the list (the same thing with just a click, though :D ). Hope that helps!

**Comment by peanutbutterandcrackers** [comment]
@lordpyre - Could you please attach the logs from rc1 again in a separate comment? I will notify the devs regarding that. Perhaps by rc2, it will have been resolved. Thanks!
