### ISSUE TITLE
problems with split clip

### ISSUE THREAD

**Issue by oldcoot2** [OpenShot/openshot-qt#1172]
**System Details:**
* Operating System / Distro: Windows 10 home
* OpenShot Version: 2.4.1-dev-1
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
I used a Wolverine 8mm to digital converter to transfer a 8mm film to a MP4 file.
In OpenShot
Imported the raw footage
Set the clip to 16 fps
Did a right click and "split clip"
Did the start and end to get 4 or 5 clips I wanted to keep, giving them names like 1-crowd, 2-rocket, cotton-candy
Made a title and set it to 16 fps
I dragged the clips to the timeline and it looked okay but I made a booboo.  Deleted all the clips from the timeline and recreated what I wanted.
When I went to check, what I had created the clips had "expanded" to include stuff from the original final but not in the clip.  The last clip I used should of been maybe a minute long, but it suddenly had the rest of the original file and was 3+ minutes.

**Comment by peanutbutterandcrackers** [comment]
I wonder if the fact that your video profile itself most likely is not a 16fps one has got anything to do with this. I suggest you create a custom profile to fit your needs (8mm size thingy, 16fps and all). Here: http://www.openshot.org/static/files/user-guide/profiles.html

I hope this helps!
