### ISSUE TITLE
memory leak ftw

### ISSUE THREAD

**Issue by ISeveryUSERnameTAKEN** [OpenShot/openshot-qt#1173]
* Windows 7 64bit
* OpenShot Version 2.4.1

Not a specific Bug but i am pretty sure you have a memory leak somewhere. If i pick any project file, no matter how small the amount of memory the launch.exe process uses continues to grow and grow. I reached 14 gig before my PC started slowing down pretty hard. If you restart the computer the same project file that was just using 14 gig will now use much less.... in my case 2 gig. 

im not really a coder, just a User that noticed this repeatable issue.

**Comment by DylanC** [comment]
@ISeveryUSERnameTAKEN - No problem. Thanks for letting us know.

**Comment by DylanC** [comment]
@ISeveryUSERnameTAKEN - Does this happen in the daily builds?  I used a daily build last night on Windows 10 and exported successfully.
