### ISSUE TITLE
View a preview of the video?

### ISSUE THREAD

**Issue by bbik** [OpenShot/openshot-qt#1174]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
How can I see the preview of how the video is turning out, i deleted it without doing it on purpose and now i don't know how to get it back

**Comment by DylanC** [comment]
@bbik - Not sure what you mean. Just press play on the preview area once you have assembled your clips.

**Comment by peanutbutterandcrackers** [comment]
@bbik - Go to View > Views > Simple View. This will bring OpenShot back to it's default view. Hope that helps. :)

**Comment by DylanC** [comment]
@bbik - Yes, follow the advice above from @peanutbutterandcrackers. This will bring back the preview.
