### ISSUE TITLE
Add a circle or arrow to a clip?

### ISSUE THREAD

**Issue by geuston** [OpenShot/openshot-qt#1175]
How do you add a circle or an arrow to a clip, to highlight a specific soccer player on the field?  I've seen lots of advice online for much older versions of OpenShot, but not for the current one - 2.4.1.  In older versions, adding an arrow involved grabbing a frame with Ctrl+D, manipulating it in GIMP and then returning it as a still.  Today, all I can seem to do with CTRL+D is grab a low res thumbnail.  Any thoughts or suggestions would be appreciated.

**Comment by geuston** [comment]
How do you add a circle or an arrow to a clip, to highlight a specific soccer player on the field?  I've seen lots of advice online for much older versions of OpenShot, but not for the current one - 2.4.1.  In older versions, adding an arrow involved grabbing a frame with Ctrl+D, manipulating it in GIMP and then returning it as a still.  Today, all I can seem to do with CTRL+D is grab a low res thumbnail.  Any thoughts or suggestions would be appreciated.

**Comment by N3WWN** [comment]
If I were going to do this, I'd create the circle or arrow in GIMP (or download one with a transparent background from a free clipart site) and overlay it over the video, scaling and transforming the image to place it where I want it.

**Comment by geuston** [comment]
Thanks N3.  I can make the circle and add it to an upper layer, but how do I place it around the player?  I tried something similar, and it ended up just taking up space in the middle of the screen.

**Comment by N3WWN** [comment]
@geuston Take a look at the `Transform` feature.  

If transforming doesn't give you the necessary control over the image, you can manually manipulate the image using the `Location X`, `Location Y`, `Scale X`, `Scale Y` and `Rotation` properties.

**Comment by peanutbutterandcrackers** [comment]
Yeah. Transform feature is a lot of help. Just in case you do not see 'transform' when you right click the image on the timeline, you should probably upgrade to a newer version of OpenShot.

[Here](https://www.youtube.com/watch?v=P3zIprwr1rk), this video might also be of some help.

P.S: If your issue is resolved, please do not forget to close it. Thanks!

**Comment by DylanC** [comment]
Closing as answered. Thanks guys!
