### ISSUE TITLE
What is the canvas size of OpenShot video editor?

### ISSUE THREAD

**Issue by MissCrescent** [OpenShot/openshot-qt#1176]
I'm trying to make an animatic but I don't know the canvas size, so I don't know how big to make my backgrounds.

**Comment by peanutbutterandcrackers** [comment]
I think the width is whatever the current video profile makes it to be. So, perhaps click the 'choose profile' icon and note down the size of the current profile from there? Hope this helps!

**Comment by DylanC** [comment]
@MissCrescent - Yes, Check the profile sizing.
