### ISSUE TITLE
Missing File Issue

### ISSUE THREAD

**Issue by internetgirl** [OpenShot/openshot-qt#1177]
**System Details:**
* Operating System / Distro: Windows 7
* OpenShot Version: Version 2.4.1

Upon opening a project I've been working on for a few days, a dialog box pops up saying there is a 'missing file', but I am certain no file is missing. It completely blocks me from opening my current and in-progress version of my project.

![ugh](https://user-images.githubusercontent.com/35042680/34497583-051e9a9c-efb3-11e7-9864-12769e739824.PNG)

It takes me here, the place where I imported the files to the software. 

![ugh part 2](https://user-images.githubusercontent.com/35042680/34497871-31b2e558-efb4-11e7-9514-dc016b821c57.PNG)

When I select the right 'folder' it still shows that the file is missing. No matter how many times I try to hit the 'X' it doesn't go away. It continues a cycle of saying 'missing file' then takes me to my computer's files. 

I have no idea how to solve this issue and I have a deadline coming up for this project, so help of any kind is appreciated.

**Comment by bizzymonkey** [comment]
I had the same problem . . . brought it to our IT guy at work and he fixed it in like two minutes.  Basically, there's a file on your computer probably called ".openshot_qt" that you need to delete.  Once deleted, Open Shot will think it's the first time it has been opened.

**Comment by DylanC** [comment]
@bizzymonkey - Yes, that's the preferences folder.  @internetgirl - Try this suggestion.

Delete the preferences folder called .openshot_qt.

**Comment by DylanC** [comment]
Dup of #1118

**Comment by internetgirl** [comment]
Got it. Thanks for the help

**Comment by DylanC** [comment]
@internetgirl - Glad you got sorted. I will close this but leave #1118 open so this can be worked on in the future.

**Comment by Aseeah23** [comment]
The same thing happens to me now ... is there a way to recover the project ?

**Comment by peanutbutterandcrackers** [comment]
@Aseeah23 - Could you give the solution reported [above](https://github.com/OpenShot/openshot-qt/issues/1177#issuecomment-358036652) a shot and see if that works, please?
