### ISSUE TITLE
Preview does nothing on WAV file

### ISSUE THREAD

**Issue by m-brooks** [OpenShot/openshot-qt#1178]
Windows 7 SP1
OpenShot Version: 4.2.1

Imported 65MB WAV file into track 0 of a new empty project.
Click the play (arrow) button on the preview.
The arrow icon is replaced by a pause (||) icon, thus indicating that we are now in playing mode. However, nothing plays. There is no sound. 
The master track cursor behaves strangely. Initially it jumps forwards by 2 seconds from 00:00:00:01 to 00:00:00:03 and then seems to freeze, but after a while it suddenly jumps forwards by maybe 10 seconds or so then freezes again. This behaviour keeps repeating itself.
I am happy to supply the specific WAV file with which I have observed this issue (just happens to be the first audio file that I have tried using, so not a good start).

Regards.

**Comment by peanutbutterandcrackers** [comment]
Does this problem still persist? I could succesfully preview a .wav file on my OpenShot installation (a daily build). Perhaps it's just the way too huge size or something? I wonder...

[This](http://www.wavsource.com/snds_2018-01-14_3453803176249356/movies/2001/sorry_dave.wav) previewed just fine for me, though.

**Comment by DylanC** [comment]
@m-brooks Can you try v2.4.2 and let us know if you have any success?
