### ISSUE TITLE
Blink on transition

### ISSUE THREAD

**Issue by m-brooks** [OpenShot/openshot-qt#1179]
Windows 7 SP1
OpenShot Version: 2.4.1

MP4 files from GoPro. GoPro natively breaks a long video sequence into multiple smaller files.
When I import two such files and butt join them consecutively within the one track, on Preview there is a very obvious pause as the video cursor reaches the end of the first file and rolls onto the start of the next file. That's fair enough in Preview - it has extra work to do at this point in the playback. However, I decided to verify that it behaves itself when actually exporting the concatenation into an output movie. Sadly it doesn't behave itself - there is a visible flash as it makes the transition.
Good old Windows Movie Maker 6.0 handled all this a lot better, even in Preview.

**Comment by peanutbutterandcrackers** [comment]
As a work-around, you could probably try turning 'Snap' mode off by 'un-clicking' the magnet icon on top of the timeline. Or, perhaps even overlap the two clips and use a transition instead?

**Comment by DylanC** [comment]
@m-brooks Can you try v2.4.2 and let us know if you have any success?
