### ISSUE TITLE
/usr/local/lib/libopenshot.so.7: undefined symbol: _ZTIN

### ISSUE THREAD

**Issue by mcori** [OpenShot/openshot-qt#118]
Hello,

I installed all necessary packages, compiled and installed libopenshot.so and libopenshot-audio. At first time launch.py couldn't find lipopenshot.so. I moved libraries from /usr/local/lib to /usr/lib. After that I started to get this message:

logger:ERROR Traceback (most recent call last):
logger:ERROR File "./launch.py", line 53, in <module>
logger:ERROR from classes.app import OpenShotApp
logger:ERROR File "/ProjectsP/Video/openshot-qt-2.0.6/openshot_qt/classes/app.py", line 41, in <module>
logger:ERROR import openshot
logger:ERROR File "/usr/local/lib/python3.4/dist-packages/openshot.py", line 28, in <module>
logger:ERROR _openshot = swig_import_helper()
logger:ERROR File "/usr/local/lib/python3.4/dist-packages/openshot.py", line 24, in swig_import_helper
logger:ERROR _mod = imp.load_module('_openshot', fp, pathname, description)
logger:ERROR File "/usr/lib/python3.4/imp.py", line 243, in load_module
logger:ERROR return load_dynamic(name, filename, file)
logger:ERROR ImportError
logger:ERROR :
logger:ERROR /usr/local/lib/libopenshot.so.7: undefined symbol: _ZTIN4juce6ThreadE

How can I solve the problem?

Thank you

**Comment by mcori** [comment]
I solved the problem :)

**Comment by DavideCatto** [comment]
How have you solved?

**Comment by peanutbutterandcrackers** [comment]
@mcori - How did you solve it, good sir?

@DavideCatto - Since the issue has been closed, I think mentioning him is the only way to send him a notification (I might be wrong, though).
