### ISSUE TITLE
No binary archive for windows

### ISSUE THREAD

**Issue by ghost** [OpenShot/openshot-qt#1180]
**System Details:**
* Operating System / Distro: Windows
* OpenShot Version: 2.4.1
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

There isn't a binary archive, so you have to use the installer. If there was a .zip archive (there might be, but I haven't found it on the official website) that would be absolutely great.

**Comment by DylanC** [comment]
@kevlarballoons - Yes indeed. I think AppImage is the most reliable way to produce the builds cross platform at the moment but we could look into it.
