### ISSUE TITLE
Openshot does not remember changes to settings

### ISSUE THREAD

**Issue by bo1e** [OpenShot/openshot-qt#1181]
Windows 10 updated
OpenShot Version: 2.4.1, just downloaded and installed spanking clean

When Openshot first starts, I get the tutorial and question about error reporting and improvements. On next startup the same thing happens. Openshot always thinks it is starting for the first time.
I try to change the interface language, and am told to restart. I restart, but the language goes back to default (system language).
I try to change other settings, but they go back to default when openshot is restarted.

**Comment by DylanC** [comment]
@bo1e - Try running the application in admin mode.
