### ISSUE TITLE
Crop video to pixel dimensions

### ISSUE THREAD

**Issue by jim1001** [OpenShot/openshot-qt#1183]
**System Details:**
* Operating System / Distro: Win 7
* OpenShot Version: 2.4.1

My source videos are mp4a 1280 x 720 pixels and I’m converting them to webm 664 x 498 pixels (4:3).  Don’t worry about the format details, that’s not my concern here.

I've successfully converted them, exporting to a profile of 664 x 498 & they play fine on the target device. However because of the different aspect ratio I end up with black bands at top & bottom. I could export to the correct height then try cropping to the correct width but I can't see a way to do this. Ideally I’d like to position a mask of correct dimensions over the video so I can see what the result will be.

Any help / advice appreciated - thank you.

**Comment by N3WWN** [comment]
I'm not sure if this is what you're looking for, but check out my comment on how to add a 1280x720 border overlay here:  https://github.com/OpenShot/openshot-qt/issues/1077#issuecomment-347565890 .  You should be able to easily modify what I'm doing to add a mask of particular dimensions for your scenario.

**Comment by jim1001** [comment]
First of all thank you for taking the time to reply and help.

Then there is no in-built simple way to crop to a rectangular pixel area - I thought that would be a standard feature for any image / video software.

Good to know you think your technique will work though - will try & have a go soon. 

Leaving the issue open in case there are any other helpful suggestions...

**Comment by DylanC** [comment]
@jim1001 - A new crop effect has been added recently. Perhaps this is what you wanted.

**Comment by peanutbutterandcrackers** [comment]
[Daily Builds](https://github.com/OpenShot/openshot-qt/releases/tag/daily). :)

**Comment by jim1001** [comment]
DylanC & peanutbutterandcrackers,

Thanks for your time & the helpful updates. Since my original post I've invested some time into using command line ffmpeg & ffplay & have been using those for everything since. Don't know when I'll go back to OpenShot. Good to know it's improving though.

All the best, Jim

**Comment by DylanC** [comment]
@jim1001 - No problem. Come back anytime!  :)
