### ISSUE TITLE
Crash When Changing Clip Time

### ISSUE THREAD

**Issue by teej14** [OpenShot/openshot-qt#1185]
**System Details:**
* Operating System / Distro: Windows 10
* OpenShot Version: 2.4.1
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
![openshot time crash](https://user-images.githubusercontent.com/35157675/34635825-e750ce9a-f28c-11e7-977b-25908c061c3d.gif)

Please see attached gif of issue. When changing clip time the program presents a launch.exe error and closes.

**Comment by peanutbutterandcrackers** [comment]
Like I was just pointing out to someone else:

> Issues like these do not happen on my linux machines. It seems that there are a lot of windows-specific bugs in openshot. Because of lack of developers esp to look after windows versions, the project is falling behind. But I think that once he has the time, Mr. Jonathan Thomas - our one and only developer for now - will hopefully get around to solving these issues. Sorry for the inconvienience...
