### ISSUE TITLE
Every video effect i try to add to my project crashes openshot

### ISSUE THREAD

**Issue by entropicChaos** [OpenShot/openshot-qt#1187]
**System Details:**
* Operating System / Distro: Linux 64bit 12gb Ram/Debian 9.3 stretch
* OpenShot Version: 2.4.1 dev-1

**Issue Description and steps to reproduce:**
Well i tried to add some effects to my video like blur but  the program becomes unresponsive and freezes and i have to force exit .

That happens with every video effect i try to add.

I tried to fix this by increasing openShot default memory threshold from 250mb to 8gb but it didn't help.

thanks 

![schermata da 2018-01-06 17-39-33](https://user-images.githubusercontent.com/35173209/34641853-87b6a6e8-f30a-11e7-864d-4f6711ffb96c.png)

**Comment by peanutbutterandcrackers** [comment]
This might seem counterintuitive, but perhaps you should use the daily ppa from openshot.org/ppa

Ooenshot works really well on my elementary OS machine (far less powerful than yours) - even with effects. Previously, I had same issue. I do run into similar issue every now and then. But I have decided that I'd rather help the caterpillar grow into a butterfly than look down upon it. :)

**Comment by DylanC** [comment]
@entropicChaos - Maybe try the latest daily build of the AppImage.

**Comment by DylanC** [comment]
@entropicChaos Can you try v2.4.2 and let us know if you have any success?
