### ISSUE TITLE
Mint 17.3 Rosa Appimage doesn't work

### ISSUE THREAD

**Issue by Ericjar** [OpenShot/openshot-qt#1191]
Intel Core I5 
4GB memory
Linux Mint 17.3 Cinnamon

Went thru what appeared to make it executable but double-clicking it did nothing... Openshot 2.4.2 
Also attempted to open another download qt-2-4-1 tar.gz without success
Will this install/run on Mint 17.3?  if not how do I upgrade to Mint 18 without losing all my work/settings/data?

Any help appreciated

My bad, I was trying to install a 64 bit version and only have 32 bit mint on the computer, so now will try to upgrade from Mint 17.3 32 bit to mint 18.3 64 bit ... wish there were an easy way to do this though, looks like I have to back everything up and then try to install off DVD unless someone has a better suggestion.

**Comment by peanutbutterandcrackers** [comment]
If your computer is a 64 bit one, then it is better if you run 64 bit operating system on it.

Also, you could install OpenShot from the PPA. That way you'll get automatic updates too. [Here](https://www.openshot.org/ppa/)

This time around, while installing, you might want to partition your Hard Disk. But that is a tad bit more advanced. But there are tutorials on the Internet about that. You will also need to set the permissions for the partition manually (pretty easy too). Usually, I only allow only one user (me) to read and write to the partition. That way it becomes my own personal/secure backup partition.

Linux Mint 18.3 is pretty neat too. All the best.

**Comment by peanutbutterandcrackers** [comment]
P.S: If your issue is fixed (or resolved) please do close this issue. Thanks!

**Comment by Ericjar** [comment]
I downloaded the most recent version from their site.

Thanks for the info, yes it works now... THANKS!
