### ISSUE TITLE
Lag/Unresponsive

### ISSUE THREAD

**Issue by Pheeblebeeble** [OpenShot/openshot-qt#1194]
**System Details:** 
* Operating System / Distro: Windows 10 x64
* OpenShot Version: 2.2.1
* _Please attach log files if crash_
n/a
**Issue Description and steps to reproduce:**
This has been brought up a few times it would appear? But none of them really answer to what is going on or they never fully follow through with the questions etc. Yes I know this is not a forum etc. However - I have spent a good hour trying to figure out what is going on aside from doing a boot on a platform I don't have. Essentially at this point my lag has jumped drastically from when I first started using the program tonight (have been using it since this version launch so clearly it is better than before) however its gone from a few second lag to a full minute and a half lag when trying to "snip" bits out of my video I am editing. It doesn't just do it on snipping out, it does when I am turning down the volume to the clip etc. I went with what I normally do which is if I have the software open for longer than 2 hours I'll close out wait 10 minutes and get it back up and running. Doesn't always work but sometimes it does help with the lag problem. I don't have any dump errors or anything like that which I kind of wish I did have. I've gone through all of the other fixes this or that. Which appears all fine to those fixes, but still the lag. <I've now read this off to my husband a couple times to make sure it makes sense> 

I don't know if it is a bug or what it is. Like I said I have gone through the different bug reports etc to see if it is like any of the others, and the only one that it is close to would be a closed question/comment that had a dump file attached. However, I don't have any dump errors to offer. For which I apologize. I will still continue to use the software as it is amazing. Just minorly annoying when you are 3+ hours into a project and having to restart every couple of hours. 

-edit-
So after fighting with it all day - I got it to stop doing that by re-exporting it into a new file and opening that file and working on it that way. I figured out it was the fact that I was starting to add timelapse to it etc. But I fixed it dangit. Sorry for opening this up now! I feel bad.

**Comment by peanutbutterandcrackers** [comment]
Hey, if it is fixed, you can close this issue too.
