### ISSUE TITLE
Create custom profile?

### ISSUE THREAD

**Issue by Yesideez** [OpenShot/openshot-qt#1195]
**System Details:**
* Operating System / Distro: Mint 18.3 Cinnamon x64
* OpenShot Version: 2.4.1

Trying to join the forums but the anti spam question is a pig. Which tool is shown? Tried razor blade and play and Nothing else.

Trying to edit video files of non standard width, height and FPS. Can I create a custom profile going by an existing clip? Love the software but this one thing is something I need and I can't find it.

**Comment by lucientisserand** [comment]
Hi Yesideez,
Like you I used to create custom profiles in openshot. But in openshot-qt I can't find the GUI no more. However the config files still exist. I found the solution [here](https://www.openshot.org/static/files/user-guide/profiles.html#custom-profile).
You may have created profiles with the old openshot. You can just copy the files (they have the same syntax) from ~/.openshot/user_profiles to ~/.openshot_qt/profiles

**Comment by peanutbutterandcrackers** [comment]
Was here to point to [this page](https://www.openshot.org/static/files/user-guide/profiles.html#custom-profile) but it seems it has already been pointed out.

@DylanC - I think this issue can be closed now.

**Comment by DylanC** [comment]
@Yesideez - There is no GUI for this at the moment. Best suggestion is to copy and edit one of the profiles. After making your edits you would need to paste to the location of the Openshot profiles.
