### ISSUE TITLE
Openshot wont... work

### ISSUE THREAD

**Issue by Dizzie-doodles** [OpenShot/openshot-qt#1196]
So, I cant use anything in openshot, legit it freezes and crashes every time I try to do anything, and when it does let me add things to the timeline, I cant preview anything at all. Help.

**Comment by peanutbutterandcrackers** [comment]
You might want to mention which Operating System you are using, and on which machine (the specs - RAM and CPU and all). That would help the developers figure things out.

OpenShot works pretty well on my two Linux machines (and on a friend's linux machine too). Not perfectly, but I can live with that. Plus, the developer has revealed plans to focus really well on the stability of the software this year. [Here](www.openshotvideo.com/2018/01/happy-new-year-2018.html)

**Comment by DylanC** [comment]
@Dizzie-doodles - We need more details to help you.

**Comment by Dangerman1973** [comment]
Mine won't work as well. Here's my PC info

![about_pc](https://user-images.githubusercontent.com/35552821/35081976-0bb35e36-fbcc-11e7-951a-0ad8495a13d9.png)

**Comment by DylanC** [comment]
Closing due to lack of added details from original reporter.
