### ISSUE TITLE
launch-openshot cannot find python module 'openshot'

### ISSUE THREAD

**Issue by djfun** [OpenShot/openshot-qt#12]
I am running Ubuntu 15.10 and have installed openshot-qt from the libopenshot-daily ppa.
When I try to start openshot via the launch-openshot command or from the Unity launcher "OpenShot 2.0" it crashes with:
```
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
launch-openshot:INFO ------------------------------------------------
launch-openshot:INFO    OpenShot (version 2.0.2)
launch-openshot:INFO ------------------------------------------------
    language:INFO Qt Detected Languages: ['de-DE']
    language:INFO LANG Environment Variable: de_DE.UTF-8
    language:INFO LOCALE Environment Variable: de_DE
    language:INFO Attempting to load qt_de_DE.UTF-8 in '/usr/share/qt5/translations'
    language:INFO Successfully loaded qt_de_DE.UTF-8 in '/usr/share/qt5/translations'
    language:INFO Attempting to load de_DE.UTF-8/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Attempting to load de/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Successfully loaded de/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Exiting translation system (since we successfully loaded: de_DE.UTF-8)
      logger:ERROR Traceback (most recent call last):
      logger:ERROR   File "/usr/bin/launch-openshot", line 77, in <module>
      logger:ERROR main()
      logger:ERROR   File "/usr/bin/launch-openshot", line 70, in main
      logger:ERROR app = OpenShotApp(sys.argv)
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 66, in __init__
      logger:ERROR self.project = project_data.ProjectDataStore()
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot_qt/classes/project_data.py", line 53, in __init__
      logger:ERROR self.new()
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot_qt/classes/project_data.py", line 245, in new
      logger:ERROR import openshot
      logger:ERROR ImportError
      logger:ERROR :
      logger:ERROR No module named 'openshot'
```
*Workaround:*
The first line of launch-openshot is `#!/usr/bin/python3.5`, the python module however is installed in `/usr/lib/python3.4/dist-packages`.
When I change launch-openshot to use python3.4, the module is found and openshot launches.

*Installed versions:*
openshot-qt: 2.0.0+0+504+85+201601102218~ubuntu15.10.1
python-libopenshot4: 0.0.6+0+492+85+201601102202~ubuntu15.10.1

**Comment by jonoomph** [comment]
Hmmm... this seems like a simple solution. I wonder if I can generically use #!/usr/bin/python3, which would probably fix it also. Maybe give that a try, and see what happens. Thanks!

**Comment by jonoomph** [comment]
Okay, it looks like I am already using #!/usr/bin/env python3 at the top of launch-openshot. Also, the version should be 2.0.4, and not 2.0.2. I'm thinking you have an older version, and need to update and try again. Fingers crossed. =)

**Comment by djfun** [comment]
I updated (or rather removed and installed again) to version 2.0.4+0+510+86+201601120649~ubuntu15.10.1

The first line of /usr/bin/launch-openshot in this package still says ```#!/usr/bin/python3.5```, though.
I have looked in the .deb files at https://code.launchpad.net/~openshot.developers/+archive/ubuntu/libopenshot-daily/+packages and the one for vivid (15.04) has (the correct?) ```#!/usr/bin/python3```.

Unfortunately I don't have that much experience with Debian packaging, so I can't tell where this needs to be changed.

**Comment by djfun** [comment]
I looked at the buildlog on launchpad some more and it seems that under 15.10 wily pybuild calls setup.py with python3.4 and also python3.5 and setuptools then rewrites the shebang line to the calling python version.
