### ISSUE TITLE
Saved project cannot open: "NoneType object is not subscriptable"

### ISSUE THREAD

**Issue by ktheijs** [OpenShot/openshot-qt#1200]
I am running OpenShot 2.4.1 on Windows 10 64x. 

There is no crash, but any time I try to open a project that I have saved it shows a popup with the message: "NoneType"object is not subscriptable.

The project does not open. Is there a way to recover my project? I have put a lot of work into it...
It is not just this project that doesn't open. No project opens.

**Comment by peanutbutterandcrackers** [comment]
@DylanC - Duplicate of #1151

**Comment by ferdnyc** [comment]
Closing all remaining open issues regarding "NoneType" error messages, which I believe were all found to be attributable to various project-file data export bugs (like the history corruption), all of which have (AFAIK) since been corrected.

**Comment by hrimhari** [comment]
I have version 2.4.4 and I just got into a NoneType situation.

**Comment by ferdnyc** [comment]
@hrimhari Please file a [new issue](https://github.com/OpenShot/openshot-qt/issues/new/choose) using the Bug Report template, including the requested logfiles, and we'll hopefully be able to sort out why.
