### ISSUE TITLE
I deleted no longer used files in thumbnail folder and can't open .OSP project

### ISSUE THREAD

**Issue by acporto** [OpenShot/openshot-qt#1201]
**System Details:**
* Operating System / Distro: Ubuntu 16.04
* OpenShot Version: 2.4.1
* _Please attach log files if crash_
![selecao_859](https://user-images.githubusercontent.com/4195718/34902148-b0ba111e-f7fc-11e7-9c2f-a9a9cb8a7e9b.png)

**Issue Description and steps to reproduce:**
Close Openshot, delete some files in "thumbnail folder, open project1.osp

I just want put the (new) files back to where it once belonged.

**Comment by acporto** [comment]
A "workaround" is crating a copy of a image, copy the name of some .png files that are with I/O error, deleting then and renaming the nem files that i've copied to replace the wrong ones.

**Comment by DylanC** [comment]
@acporto - Yes, I was gonna suggest this workaround. Really people shouldn't touch the contents of the thumbnails folder. Just let Openshot handle it. 😃
