### ISSUE TITLE
Crash upon exporting project

### ISSUE THREAD

**Issue by JBoughter** [OpenShot/openshot-qt#1203]
**System Details:**
* Operating System / Distro: Windows 10 x64
* OpenShot Version: Latest daily ([this one](https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.4.1-3-g8e96e17-57-663-x86_64.exe) if this issue gets older)
* _Please attach log files if crash_
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/1628717/openshot-qt.log)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/1628718/libopenshot.log)

**Issue Description and steps to reproduce:**
1. Load or create any project.
2. Export using any settings.
3. Crash.

**Comment by DylanC** [comment]
@JBoughter - Thanks for the issue report.

**Comment by DylanC** [comment]
@JBoughter - Can you try reducing the size of the images used perhaps and try out a daily build to see if you get a success?
