### ISSUE TITLE
 OpenShot doesn't get the settings

### ISSUE THREAD

**Issue by Theo-FR** [OpenShot/openshot-qt#1204]
**System Details:** i7-7700K - 3.8-4.2 Ghz , 16 gb RAM - 3000 Mhz
* Operating System : Window 10
* OpenShot Version: 2.41.1-x86_64

Hi , i just installed OpenShot today and i experience a really booring bug , everytime when i launch OpenShot , the tutorial launch , i close it and want to change my settings so i do it , it tells me that i have to restart the program to save it , i do it and it reload the tutorial and didn't change my settings like it said it would do , i tried to change the settings like 20 times and it still bug :(

Please send help !! xd

**Comment by DylanC** [comment]
Dup of #1181
