### ISSUE TITLE
Not Installing

### ISSUE THREAD

**Issue by BlueSnow0** [OpenShot/openshot-qt#1205]
x64 system
Windows 10 64bit
OpenShot-v2.4.1-x86_64
File Size:  130,581KB
(Installing from downloads folder but have tried other places with the same result)
(yes I have tried redownloading it more than once)

The installer opens > English > accept EULA > add desktop shortcut >
![image](https://user-images.githubusercontent.com/35447506/34932559-09472cb2-fa1f-11e7-848d-4598b9ab2645.png)

> install >
"The Drive or UNC Share you selected does not exist or is not accessible. Please select another."
![image](https://user-images.githubusercontent.com/35447506/34932594-29acf234-fa1f-11e7-90a5-1fb268e95cd7.png)

**Comment by DylanC** [comment]
@BlueSnow0 - Are you trying to install to a network drive?

**Comment by BlueSnow0** [comment]
No, don't even have a network drive

**Comment by DylanC** [comment]
@BlueSnow0 - What location are you installing to?

**Comment by jgrasser** [comment]
@DylanC I was unable to reproduce this issue. I attempted to install to the following file system location: C:\Program Files\OpenShot Video Editor. No errors were reported, and application auto started.

System: Windows 10 Pro 64bit
Version: OpenShot-v2.4.1-x86_64

**Comment by peanutbutterandcrackers** [comment]
@BlueSnow0 - Also, and this just might be too trivial, it is not EULA but GPL, the license. And for some reason, if your installer does say EULA instead of GPL, I think you just might have downloaded the copy from some another place and the installer has probably been tampered with? o.O

**Comment by BlueSnow0** [comment]
Nope it's a GPL, downloaded from https://www.openshot.org/download/

**Comment by DylanC** [comment]
Unable to reproduce this issue.

**Comment by peanutbutterandcrackers** [comment]
@BlueSnow0 - You should probably try out the [daily builds](https://github.com/OpenShot/openshot-qt/releases/tag/daily) and see if they work out for you. Hope that helps!

Please do look forward to v2.4.2, BTW. A lot of things are going to be just great in v2.4.2. :)

**Comment by GeraldKane** [comment]
I'm getting the same problem. I recently downloaded the newest version and when I go to install from the .exe it skips over asking me where I wish to download the program.

**Comment by GeraldKane** [comment]
It jumps straight from this:

![Screenshot (2)](https://user-images.githubusercontent.com/51189086/204190772-9b4335db-4224-45d0-8a69-0a55e7f4a202.png)

To this:

![Screenshot (3)](https://user-images.githubusercontent.com/51189086/204190777-2cd096a1-87a9-46d5-b4ae-f6fda088a11a.png)

Without asking me where I would like to unpack the files.

![Screenshot (4)](https://user-images.githubusercontent.com/51189086/204190782-ff4e122e-8314-4e6b-aad4-c7e734562779.png)

Which is how this screen comes up.

**Comment by Colorjet3** [comment]
Please go to openshot.org/download/#daily and download the latest DEV Daily Build available.  Give it a try and let us know if this resolved your issue.

**Comment by GeraldKane** [comment]
The popup now asks where I would like to put the files. Thank you so much for your help and timely response.

**Comment by Colorjet3** [comment]
You are welcome @GeraldKane .  Feel free to close this ticket and good luck with your projects.
