### ISSUE TITLE
Slow down of clip with number of frames <= slow down factor results in smaller clip

### ISSUE THREAD

**Issue by koperj001** [OpenShot/openshot-qt#1206]
Windows 7 and Linux Mint 18.3
Openshot 2.4.1

Example situation:
-	Clip with 30 frames (from time-lapse video) in Openshot time-line/track

Reproduction:
Right-click clip
Test1: Select Time --> Slow --> 1/16
Delete clip and move original clip to time-line/track
Test 2: Select Time --> Slow --> 1/32

Expected:
Test 1: Clip is resized correctly to new length (16 times longer)
Test 2: Clip is resized correctly to new length (32 times longer)

Actual
Test 1: Clip is resized to new length (16 times longer)  Correct
Test2: Clip is resized incorrectly (reduced to 2 frames)  NOT correct

The incorrect behavior occurs when the number of frames in the clip is smaller or equal to the slow down factor

**Comment by peanutbutterandcrackers** [comment]
@DylanC I think this issue here needs some attention. The author has even given a mathematical rationale behind the bug. Could you please test it? I don't have my computer with me now.....

**Comment by DylanC** [comment]
@koperj001 - Great bug report btw!  @peanutbutterandcrackers - Yep, I will test it tonight!

**Comment by DylanC** [comment]
@koperj001 @peanutbutterandcrackers 
A clip of 10 secs is expanded to 297.71 when set to x32 time but 10 x 32 = 320. Seems to be acting a bit weird but I still have yet to produce this bug since OpenShot on Windows crashed. I will check on Linux later today.

**Comment by peanutbutterandcrackers** [comment]
@DylanC - Looking forward to hear about the result of your investigations, Mr. Holmes. :)

**Comment by DylanC** [comment]
@koperj001 - Can you provide a clip to test with? I can't produce this issue with any clip I try.

**Comment by koperj001** [comment]
Excuses for the late response, but I have been quite busy at work and also needed to get a new project.
The project file is here now. I hope you will be able to reproduce:
- Clip 2 is a small clip of 2 frames (that needed to be slowed down so you can see the Kudu passing in front of the car (I was not able to slow this one down)
- Clip 3 is a small clip of 8 frames (this may be slowed down a factor 2 or 4, but not higher)
- Clip 4 is also somewhat larger: somewhere around 24 frames
I'll mail the clip (and the OSP-file to you
