### ISSUE TITLE
How to export edited video with subtitles

### ISSUE THREAD

**Issue by spsike6479** [OpenShot/openshot-qt#1207]
**System Details:**
windows 10
* OpenShot Version: ? 2.4.1

Is there a way to include the subtitles that were in the original video file when exporting the edited one. I'm editing a file downloaded from a tivo. The original file had subtitles, but exported file didn't.

**Comment by Amarok19** [comment]
This is not a bug, a feature request, improvement suggestion etc. so it doesn't belong in GitHub, please post your question on the forum and remove the bug report if possible. You can also rephrase the bug report into a form of feature request as there is curently no way to render subtitles onto a video using OpenShot, but it is possible that many users would welcome such a feature.
