### ISSUE TITLE
Won't install.

### ISSUE THREAD

**Issue by sparky3489** [OpenShot/openshot-qt#1208]
Win 7, 2.2GHz, 32-bit, 4GRam
![image](https://user-images.githubusercontent.com/35472289/34965779-5857c59e-fa1c-11e7-9486-f1decffe89c0.png)
 
OpenShot-v2.4.1-3-g8e96e17-57-663-x86_64.exe

Says x86 right in the name.

**Comment by DylanC** [comment]
@sparky3489 - Openshot does not have 32bit support yet.

**Comment by sparky3489** [comment]
So then shouldn't the name be "amd64" not" x86_64"? It's kind of misleading.

**Comment by DylanC** [comment]
@sparky3489 - You are probably right. :)
