### ISSUE TITLE
Freezes during splitting

### ISSUE THREAD

**Issue by bevort** [OpenShot/openshot-qt#1209]
**System Details:**
Windows 10
OpenShot Version: 2.4.1
Source to split is in webm format
Would gladly add the  log file if I could find it

**Issue Description and steps to reproduce:**
When splitting a file into more parts openshot randomly freezes randomly after creating a clip.
what happens most of the time is that the program freezes after a clip and will not play the original file to find the next starting point.
This can happen after the first clip or after any other one. It happend ones that I even could not strat the movie att all.
When the program freezes windows displays "Not Responding" in the titlebar of the program and it will stay there forever. When closing the Splitting popup the complete program closes.
Re-opening the program want for a recovery and the created clips are available.
No log file could be found. It doesn't seem to create one in this case

**Comment by DylanC** [comment]
@bevort - Hi there, I think the log files are in this location:
C:/Users/USERNAME/.openshot_qt/openshot-qt.log

**Comment by DylanC** [comment]
@bevort Can you try v2.4.2 and let us know if you have any success?
