### ISSUE TITLE
Audio level settings applied incorrectly on video export

### ISSUE THREAD

**Issue by sknaumov** [OpenShot/openshot-qt#1210]
**System Details:**
* Operating System / Distro: Windows 10
* OpenShot Version: 2.4.1

**Issue Description and steps to reproduce:**
1. Add audio level (say, fade out fast and the end of clip).
2. Verify behavior in internal media player - OK.
3. Export video:
 - Expected: audio levels are the same and applied at the same moment as in internal media player.
 - Actual: either audio transition applied not at the same place (instead of the last 3-5 seconds - 10-15 away from clip end) or the whole part of the video (to which sound effect was applied) become soundless.

It looks like in some cases it could depend on frame rate of exported video. I've managed to fix it once by using 24 fps profile, while for 30 and 50 fps profiles some parts of the video were soundless. Original video was 48fps (from GoPro).

**Comment by sknaumov** [comment]
Also I would say that audio effects are not even close in their flexibility to video effects. Is there a way to apply custom fade out interval for sound?

**Comment by DylanC** [comment]
@sknaumov Can you try v2.4.2 and let us know if you have any success?
