### ISSUE TITLE
Transitions applied incorrectly on video export

### ISSUE THREAD

**Issue by sknaumov** [OpenShot/openshot-qt#1211]
**System Details:**
* Operating System / Distro: Windows 10
* OpenShot Version: 2.4.1

**Issue Description and steps to reproduce:**
1. Overlap clips to make a default fade transition.
2. Verify behavior in internal media player - OK.
3. Export video:
  - Expected: transition is applied at the same time and with the same duration as in internal media player.
  - Actual: transition duration is not the same (greatly reduced).

It looks like in some cases it could depend on frame rate of exported video. I haven't seen this problem on 24 fps export.

Non-affected video: https://youtu.be/rPDdbT3-law?t=180
Affected video: https://youtu.be/_fNtxVu8HLM?t=321

In internal media player both transitions were like on the first video.

**Comment by peanutbutterandcrackers** [comment]
Like I was just pointing out to someone else:

> Issues like these do not happen on my linux machines. It seems that there are a lot of windows-specific bugs in openshot. Because of lack of developers esp to look after windows versions, the project is falling behind. But I think that once he has the time, Mr. Jonathan Thomas - our one and only developer for now - will hopefully get around to solving these issues. Sorry for the inconvienience...

**Comment by peanutbutterandcrackers** [comment]
@DylanC - Possible dup of #640 ?

**Comment by DylanC** [comment]
@peanutbutterandcrackers - Yup, dup of #640

**Comment by DylanC** [comment]
@sknaumov - Does v2.4.3 have the same issue for you?

**Comment by sknaumov** [comment]
No, it is not dup of #640, but probably a dup of #519.
#640 is about incorrect transition time everywhere including internal editor (because of brightness level that is set for automatically created transition), while this bug is about problems with exported video when project profile and original video framerates don't match.

**Comment by DylanC** [comment]
@sknaumov - Updated my comment, thanks.

**Comment by ferdnyc** [comment]
Closing as dup of (fixed) #519
