### ISSUE TITLE
Internal media player sometimes get broken

### ISSUE THREAD

**Issue by sknaumov** [OpenShot/openshot-qt#1212]
**System Details:**
* Operating System / Distro: Windows 10
* OpenShot Version: 2.4.1

**Issue Description and steps to reproduce:**
Sometimes when I split a video or create transitions, internal media player starts to play video with some severe lags, but more importanly, not from the same moment at which playback pointer stays. It could be healed only by OpenShot restart.

**Comment by DylanC** [comment]
@sknaumov - Yes, we have seen reported issues about slow downs with Win10.
