### ISSUE TITLE
Step description on undo/redo buttons.

### ISSUE THREAD

**Issue by Amarok19** [OpenShot/openshot-qt#1214]
**System Details:**
* Operating System / Distro: Microsoft Windows Version 10.0.15063 Build 15063
* OpenShot Version: 2.4.1-dev1

After any action is taken, a possibility to 'Undo' it is available and after undoing it is also possible to 'Redo' this action. What would be a nice enhancement is if the buttons in the GUI (on the top bar) had a hover tooltip that would indicate at least what type of action will be reversed if Undo/Redo is performed and optimally more info could be added, for example if a clip was split, the label would say:
[baseline] Undo: Clip split
[enhanced] Undo: Clip split, Clip 1

**Comment by DylanC** [comment]
@Amarok19 - Cool idea!
