### ISSUE TITLE
OpenShot Crash or Not Responding after first use

### ISSUE THREAD

**Issue by Dangerman1973** [OpenShot/openshot-qt#1215]
I started Openshot for the first time and worked on my first project, but the program crashes/not responding when I work on it. Need help.

![about_pc](https://user-images.githubusercontent.com/35552821/35081420-eda0cbf2-fbc8-11e7-88a0-2db78fc150c4.png)

**Comment by Dangerman1973** [comment]
![not_respond](https://user-images.githubusercontent.com/35552821/35081942-d53ff314-fbcb-11e7-917e-401bcd587704.png)

**Comment by DylanC** [comment]
@Dangerman1973 - What happened when it crashed? Did you see any error message?
