### ISSUE TITLE
Feature Request: Improve workflow for simple cutting of videos

### ISSUE THREAD

**Issue by OctagonHex** [OpenShot/openshot-qt#1216]
**System Details:**
* Operating System / Distro: Windows 7
* OpenShot Version: OpenShot 2.4.1

**Feature Request:**
I think many users want to use OpenShot in the same way as me: to do some quick trimming of videos. For example, remove a few seconds on the beginning, and at the end. That's all.

Now I want to save the video again. I would like to simply "Save" the video, but I understand, that Openshot is project-based, not file-base. That's ok, so I choose "Export...". But now the user experience degrades. For obvious reasons, I want the settings to be as close as possible to the input video.
I use video-sources of varying pedigree: USB webcams, DSC cameras, Screen-Recordings, etc... all with different resolution, frame-rates, codes, encodings, audio codecs, bitrates, etc....

Now, to get an trimmed output video as close as possible to the input video format, I have to do:
- find out the exact resolution, codec, FPS, bitrate, for audio, video, ...
- create a new profile and enter the information, and do a test, if the chosen combination works.
- export the video.

Therefor, I would like to have a button:
"Create video profile from current video clip", or "Copy video properties to project settings" , or "Use encoding of first video", or anything along these lines.
That would help me enormously. Thank you!

**Comment by DylanC** [comment]
@OctagonHex - True, I think the workflow could improve a bit.

**Comment by peanutbutterandcrackers** [comment]
Is this similar to loss-less export? o.O
