### ISSUE TITLE
Unable to open OSP file

### ISSUE THREAD

**Issue by ajstars** [OpenShot/openshot-qt#1217]
Windows 10 Professional
Laptop battery gave up just after a save of a video project and the following morning when back on charge the file was still there.  I can no longer open the file without error: TitleFileName-1svg cannot be found.
There is a folder of all my thumnails and a folder of the blender titles I created.
When I cancel the error, I then receive a Runtime Error on OpenShot which then terminates the programme.  Just before doing so though the video files do appear to be imported into Openshot.  I have tried ignoring the run time error box and saving the file again, but it just wont open or play.

**Comment by DylanC** [comment]
@ajstars - Does the runtime error mention Cx_freeze at all?

**Comment by ajstars** [comment]
No I don’t believe so.

Thanks



Sent from myMail for iOS


Friday, 9 February 2018, 13:31 +0000 from notifications@github.com <notifications@github.com>:

@ajstars<https://github.com/ajstars> - Does the runtime error mention Cx_freeze at all?

**Comment by DylanC** [comment]
@ajstars - I would recommend to try a daily build. There are much new features in it or you can wait until v2.4.2 is released.  (Should be soon)

**Comment by DylanC** [comment]
@ajstars - You need to create this file TitleFileName-1svg and put it where your created it before.
