### ISSUE TITLE
OpenShot-v2.4.1-x86_64.AppImage closing while drag&drop new files (mp4) into openshot

### ISSUE THREAD

**Issue by jabi27** [OpenShot/openshot-qt#1218]
Description:	Ubuntu 17.10
Release:	17.10
OpenShot-v2.4.1-x86_64.AppImage

and tried today the daily build:
OpenShot-v2.4.1-3-g8e96e17-57-663-x86_64.AppImage

It is the same result.

While drag a file (mp4) from the file-manager to openshot it crash/close. Not every time but often. This has started sometime recently (this new year) so I suspect some change in the Ubuntu stream? 

** log clip **
..
..
files_treeview:INFO Adding file: /home/jbi/Videoklip/DCIM/155YBPHH/S1550026.MP4
project_data:INFO _set key: ['files'] values: {'path': '/home/jbi/Videoklip/DCIM/155YBPHH/S1550026.MP4', 'audio_bit_rate': 253375, 'video_bit_rate': 45316596, 'video_timebase': {'num': 1, 'den': 180000}, 'top_field_first': True, 'has_single_image': False, 'display_ratio': {'num': 16, 'den': 9}, 'type': 'FFmpegReader', 'audio_timebase': {'num': 1, 'den': 48000}, 'id': 'R551GQH6PJ', 'height': 1080, 'has_audio': True, 'pixel_ratio': {'num': 1, 'den': 1}, 'video_length': '864', 'sample_rate': 48000, 'channels': 2, 'audio_stream_index': 1, 'vcodec': 'h264', 'width': 1920, 'interlaced_frame': False, 'video_stream_index': 0, 'pixel_format': 0, 'channel_layout': 3, 'duration': 17.32266616821289, 'has_video': True, 'media_type': 'video', 'acodec': 'aac', 'file_size': '98125539', 'fps': {'num': 50, 'den': 1}} add: True partial: False remove: False
logger_libopenshot:INFO FFmpegReader::Close ()
timeline_webview:INFO SortItems
timeline_webview:INFO UpdateLayerIndex
 files_model:INFO updating files model.
Caught signal 11 (SIGSEGV)
---- Unhandled Exception: Stack Trace ----
  /tmp/.mount_8xk8W0/usr/bin/libQt5Gui.so.5 ( QDrag::actionChanged(Qt::DropAction)      + 0x2e  )  [0x7fd29329b9ce]
  /tmp/.mount_8xk8W0/usr/bin/platforms/libqxcb.so (                                           + 0x373fe)  [0x7fd2794af3fe]
  /tmp/.mount_8xk8W0/usr/bin/platforms/libqxcb.so (                                           + 0x3f369)  [0x7fd2794b7369]
  /tmp/.mount_8xk8W0/usr/bin/platforms/libqxcb.so (                                           + 0x2db3b)  [0x7fd2794a5b3b]
  /tmp/.mount_8xk8W0/usr/bin/platforms/libqxcb.so (                                           + 0x2eb6b)  [0x7fd2794a6b6b]
  /tmp/.mount_8xk8W0/usr/bin/libQt5Core.so.5 ( QObject::event(QEvent*)                   + 0x23e )  [0x7fd292b0322e]
  /tmp/.mount_8xk8W0/usr/bin/libQt5Widgets.so.5 ( QApplicationPrivate::notify_helper(QObject*, QEvent*)  + 0x8c  )  [0x7fd2936a0c8c]
  /tmp/.mount_8xk8W0/usr/bin/libQt5Widgets.so.5 ( QApplication::notify(QObject*, QEvent*)   + 0x3d6 )  [0x7fd2936a5e56]
  /tmp/.mount_8xk8W0/usr/bin/PyQt5.QtWidgets.so ( sipQApplication::notify(QObject*, QEvent*)  + 0x86  )  [0x7fd294076426]
  /tmp/.mount_8xk8W0/usr/bin/libQt5Core.so.5 ( QCoreApplication::notifyInternal(QObject*, QEvent*)  + 0x6d  )  [0x7fd292adac2d]
  /tmp/.mount_8xk8W0/usr/bin/libQt5Core.so.5 ( QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*)  + 0x1e7 )  [0x7fd292adce07]
  /tmp/.mount_8xk8W0/usr/bin/libQt5Core.so.5 (                                           + 0x2b4cd3)  [0x7fd292b27cd3]
  /lib/x86_64-linux-gnu/libglib-2.0.so.0 ( g_main_context_dispatch                   + 0x2e7 )  [0x7fd291db8fb7]
  /lib/x86_64-linux-gnu/libglib-2.0.so.0 (                                           + 0x4b1f0)  [0x7fd291db91f0]
  /lib/x86_64-linux-gnu/libglib-2.0.so.0 ( g_main_context_iteration                  + 0x2c  )  [0x7fd291db927c]
  /tmp/.mount_8xk8W0/usr/bin/libQt5Core.so.5 ( QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>)  + 0x5c  )  [0x7fd292b2798c]
  /tmp/.mount_8xk8W0/usr/bin/PyQt5.QtCore.so (                                           + 0xd52e4)  [0x7fd28c33d2e4]
  /tmp/.mount_8xk8W0/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalFrameEx                        + 0x6d79)  [0x7fd296f7f7a9]
  /tmp/.mount_8xk8W0/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalCodeEx                         + 0x886 )  [0x7fd296f82936]
  /tmp/.mount_8xk8W0/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalFrameEx                        + 0x6742)  [0x7fd296f7f172]
  /tmp/.mount_8xk8W0/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalFrameEx                        + 0x6c5c)  [0x7fd296f7f68c]
  /tmp/.mount_8xk8W0/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalFrameEx                        + 0x6c5c)  [0x7fd296f7f68c]
  /tmp/.mount_8xk8W0/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalFrameEx                        + 0x6c5c)  [0x7fd296f7f68c]
  /tmp/.mount_8xk8W0/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalFrameEx                        + 0x6c5c)  [0x7fd296f7f68c]
  /tmp/.mount_8xk8W0/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalCodeEx                         + 0x886 )  [0x7fd296f82936]
  /tmp/.mount_8xk8W0/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalFrameEx                        + 0x6742)  [0x7fd296f7f172]
  /tmp/.mount_8xk8W0/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalFrameEx                        + 0x6c5c)  [0x7fd296f7f68c]
  /tmp/.mount_8xk8W0/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalCodeEx                         + 0x886 )  [0x7fd296f82936]
  /tmp/.mount_8xk8W0/usr/bin/libpython3.4m.so.1.0 (                                           + 0x209f66)  [0x7fd296f82f66]
  /tmp/.mount_8xk8W0/usr/bin/libpython3.4m.so.1.0 ( PyObject_Call                             + 0x68  )  [0x7fd296ee4718]
  /tmp/.mount_8xk8W0/usr/bin/libpython3.4m.so.1.0 (                                           + 0x15155d)  [0x7fd296eca55d]
  /tmp/.mount_8xk8W0/usr/bin/libpython3.4m.so.1.0 ( PyObject_Call                             + 0x68  )  [0x7fd296ee4718]
  /tmp/.mount_8xk8W0/usr/bin/libpython3.4m.so.1.0 ( PyEval_CallObjectWithKeywords             + 0x47  )  [0x7fd296f5a977]
  /tmp/.mount_8xk8W0/usr/bin/sip.cpython-34m-x86_64-linux-gnu.so (                                           + 0x12ff4)  [0x7fd28c74aff4]
  /tmp/.mount_8xk8W0/usr/bin/PyQt5.QtWidgets.so ( sipVH_QtWidgets_10(PyGILState_STATE, void (*)(_sipSimpleWrapper*, PyGILState_STATE), _sipSimpleWrapper*, _object*, QDropEvent*)  + 0x4c  )  [0x7fd294146f3c]
  /tmp/.mount_8xk8W0/usr/bin/PyQt5.QtWidgets.so ( sipQTreeView::dropEvent(QDropEvent*)      + 0x53  )  [0x7fd2940342e3]
  /tmp/.mount_8xk8W0/usr/bin/libQt5Widgets.so.5 ( QWidget::event(QEvent*)                   + 0x7d5 )  [0x7fd2936dc275]
  /tmp/.mount_8xk8W0/usr/bin/libQt5Widgets.so.5 ( QFrame::event(QEvent*)                    + 0x1e  )  [0x7fd2937d7c7e]
  /tmp/.mount_8xk8W0/usr/bin/libQt5Widgets.so.5 ( QAbstractItemView::viewportEvent(QEvent*)  + 0x18b )  [0x7fd2938d8d5b]
  /tmp/.mount_8xk8W0/usr/bin/libQt5Widgets.so.5 ( QTreeView::viewportEvent(QEvent*)         + 0x30  )  [0x7fd293915820]
  /tmp/.mount_8xk8W0/usr/bin/PyQt5.QtWidgets.so ( sipQTreeView::viewportEvent(QEvent*)      + 0x7b  )  [0x7fd29402d78b]
  /tmp/.mount_8xk8W0/usr/bin/libQt5Core.so.5 ( QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*)  + 0xf3  )  [0x7fd292adae53]
  /tmp/.mount_8xk8W0/usr/bin/libQt5Widgets.so.5 ( QApplicationPrivate::notify_helper(QObject*, QEvent*)  + 0x6c  )  [0x7fd2936a0c6c]
  /tmp/.mount_8xk8W0/usr/bin/libQt5Widgets.so.5 ( QApplication::notify(QObject*, QEvent*)   + 0xa63 )  [0x7fd2936a64e3]
  /tmp/.mount_8xk8W0/usr/bin/PyQt5.QtWidgets.so ( sipQApplication::notify(QObject*, QEvent*)  + 0x86  )  [0x7fd294076426]
  /tmp/.mount_8xk8W0/usr/bin/libQt5Core.so.5 ( QCoreApplication::notifyInternal(QObject*, QEvent*)  + 0x6d  )  [0x7fd292adac2d]
  /tmp/.mount_8xk8W0/usr/bin/libQt5Widgets.so.5 (                                           + 0x1940f2)  [0x7fd2936fa0f2]
  /tmp/.mount_8xk8W0/usr/bin/libQt5Widgets.so.5 (                                           + 0x19492b)  [0x7fd2936fa92b]
  /tmp/.mount_8xk8W0/usr/bin/libQt5Widgets.so.5 ( QApplicationPrivate::notify_helper(QObject*, QEvent*)  + 0x8c  )  [0x7fd2936a0c8c]
  /tmp/.mount_8xk8W0/usr/bin/libQt5Widgets.so.5 ( QApplication::notify(QObject*, QEvent*)   + 0x3d6 )  [0x7fd2936a5e56]
  /tmp/.mount_8xk8W0/usr/bin/PyQt5.QtWidgets.so ( sipQApplication::notify(QObject*, QEvent*)  + 0x86  )  [0x7fd294076426]
  /tmp/.mount_8xk8W0/usr/bin/libQt5Core.so.5 ( QCoreApplication::notifyInternal(QObject*, QEvent*)  + 0x6d  )  [0x7fd292adac2d]
  /tmp/.mount_8xk8W0/usr/bin/libQt5Gui.so.5 ( QGuiApplicationPrivate::processDrop(QWindow*, QMimeData const*, QPoint const&, QFlags<Qt::DropAction>)  + 0x83  )  [0x7fd292ffb453]
  /tmp/.mount_8xk8W0/usr/bin/libQt5Gui.so.5 ( QWindowSystemInterface::handleDrop(QWindow*, QMimeData const*, QPoint const&, QFlags<Qt::DropAction>)  + 0x9   )  [0x7fd292fe48c9]
  /tmp/.mount_8xk8W0/usr/bin/platforms/libqxcb.so (                                           + 0x36621)  [0x7fd2794ae621]
  /tmp/.mount_8xk8W0/usr/bin/platforms/libqxcb.so (                                           + 0x3f269)  [0x7fd2794b7269]
  /tmp/.mount_8xk8W0/usr/bin/platforms/libqxcb.so (                                           + 0x2db3b)  [0x7fd2794a5b3b]
  /tmp/.mount_8xk8W0/usr/bin/platforms/libqxcb.so (                                           + 0x2eb6b)  [0x7fd2794a6b6b]
  /tmp/.mount_8xk8W0/usr/bin/libQt5Core.so.5 ( QObject::event(QEvent*)                   + 0x23e )  [0x7fd292b0322e]
  /tmp/.mount_8xk8W0/usr/bin/libQt5Widgets.so.5 ( QApplicationPrivate::notify_helper(QObject*, QEvent*)  + 0x8c  )  [0x7fd2936a0c8c]
---- End of Stack Trace ----
QLibraryPrivate::unload succeeded on "/tmp/.mount_8xk8W0/usr/bin/imageformats/libqgif.so"  
QLibraryPrivate::unload succeeded on "/tmp/.mount_8xk8W0/usr/bin/imageformats/libqico.so"  
QLibraryPrivate::unload succeeded on "/tmp/.mount_8xk8W0/usr/bin/imageformats/libqjpeg.so"  
QLibraryPrivate::unload succeeded on "/tmp/.mount_8xk8W0/usr/bin/imageformats/libqsvg.so"  
QLibraryPrivate::unload succeeded on "/tmp/.mount_8xk8W0/usr/bin/platforms/libqxcb.so"  
QLibraryPrivate::unload succeeded on "Xcursor" (faked) 

***********

Thanks for a very good product :-)

Best 
/Jan

**Comment by jabi27** [comment]
Cut & paste other files also crashes the appImage. Here a png file:
-
reeview:INFO Adding file: /home/jbi/Videoklip/STIL/STIL-logo.png
project_data:INFO _set key: ['files'] values: {'has_video': True, 'duration': 86400.0, 'pixel_format': -1, 'vcodec': '', 'display_ratio': {'num': 1, 'den': 1}, 'audio_stream_index': -1, 'width': 1200, 'fps': {'num': 30, 'den': 1}, 'pixel_ratio': {'num': 1, 'den': 1}, 'interlaced_frame': False, 'id': 'PI5VG4I0SA', 'height': 1200, 'has_single_image': True, 'video_bit_rate': 0, 'video_stream_index': -1, 'file_size': '5760000', 'video_timebase': {'num': 1, 'den': 30}, 'channels': 0, 'has_audio': False, 'path': '/home/jbi/Videoklip/STIL/STIL-logo.png', 'sample_rate': 0, 'channel_layout': 4, 'audio_timebase': {'num': 1, 'den': 1}, 'video_length': '2592000', 'audio_bit_rate': 0, 'top_field_first': True, 'media_type': 'image', 'type': 'QtImageReader', 'acodec': ''} add: True partial: False remove: False
timeline_webview:INFO SortItems
timeline_webview:INFO UpdateLayerIndex
 files_model:INFO updating files model.
Caught signal 11 (SIGSEGV)
------
Best
/Jan

**Comment by jabi27** [comment]
If importing file from openshot it self (ctrl-f) there is no issues.

**Comment by DylanC** [comment]
@jabi27 - I have seen this before on 17.10 too. Have you tried any of the daily builds? This has not happened to me in a long time.

**Comment by DylanC** [comment]
@jabi27 - A fix went in for drag and drop. Maybe this may solve your issue. Can you try a daily build please?
