### ISSUE TITLE
EDITING: I can´t recuperate the view clip 

### ISSUE THREAD

**Issue by telelauro** [OpenShot/openshot-qt#122]
when I try to change the way we see the clip imported into the project, I am not able to return to view them big. like this> HOW CAN I view 
![pantaila-argazkia 2016-03-07 17 06 25](https://cloud.githubusercontent.com/assets/16803007/13577316/beff920e-e489-11e5-947b-8da4ddf9b766.png)

And there goes the characteristics of the video clip. How to choose a piece of clip once this changed the way display the video clip does not return to be equal to or do not get put openshot igaul that when the program is newly installed.

**Comment by jonoomph** [comment]
Can you right click on the file, and choose "Details" or "Thumbnail"? That should switch the view.

**Comment by telelauro** [comment]
Sorry but it is impossible tu open right click ... This option is missing¡
and i try to another machine and it is the same.

El jueves, 17 de marzo de 2016, Jonathan Thomas <notifications@github.com>
escribió:

> Closed #122 <https://github.com/OpenShot/openshot-qt/issues/122>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenShot/openshot-qt/issues/122#event-592833021>
>


-- 
"Dabilen kamerari Kroma-keyrik ez"
