### ISSUE TITLE
support for appimaged 

### ISSUE THREAD

**Issue by Lvaskz** [OpenShot/openshot-qt#1221]
hi, i am using linuxmint 18.03, 
64 bits, cinnamon. 
Openshot 2.4.1
Actually i installed the appimage daemon called appimaged.
This is appimaged "appimaged is an optional daemon that watches locations like ~/bin and ~/Downloads for AppImages and if it detects some, registers them with the system, so that they show up in the menu, have their icons show up, MIME types associated, etc. It also unregisters AppImages again from the system if they are deleted. If firejail is installed, it runs the AppImages with it."https://github.com/AppImage/AppImageKit
Many appimages, using this can register the icon in the system menu without installing, only putting the appimages on the bin folder or download folder, etc but many icons appimages are not recognized by appimaged, like rambox, vlc, nextcloud, protonmail etc.
By that reason i request if this is posible, openshot can be supported by appimaged
the icon is missing from menu application and task bar 
![openshot](https://user-images.githubusercontent.com/29207169/35206370-cfc352f8-ff01-11e7-94eb-4df3c05fb98f.png)

type in the terminal : appimaged, after install appimaged

**Comment by Lvaskz** [comment]
![openshot appliactio menu missing](https://user-images.githubusercontent.com/29207169/35206476-8434a2d2-ff02-11e7-861d-ca4ba3215cde.png)

**Comment by Lvaskz** [comment]
By the way. Th

**Comment by DylanC** [comment]
@Lvaskz - Thanks, I'll go ask the guys for you.

**Comment by peanutbutterandcrackers** [comment]
This too is one of those really good reports. Thank you @Lvaskz for such a detailed report! :+1:
