### ISSUE TITLE
blender issue

### ISSUE THREAD

**Issue by pilotgeorge** [OpenShot/openshot-qt#1222]
**Intel i5 12 GIGS RAM**
* Operating System / Distro: WIN 10
* OpenShot Version: 2.4.1
* _Please attach log files if crash_  none

**I am trying to use an animated title. I get an error message regarding Blender stating the Blender must be locatable.  Under preferences, I set Blender location as "c:\program files (x86)\blender foundation\blender.exe" The Blender files are at this location, but apparently OpenShot can't find it.

How do I fix this?**

**Comment by PASTJL** [comment]
You have to give the whole path including blender.exe
If it doesn't work a Workaround has been given here.
Add to  the System Variable "Path" C:\program files (x86)\blender and set only blender.exe with no path in the openshot configuration.
The same can be done for inskape.

**Comment by DylanC** [comment]
@pilotgeorge - Copy and paste the file path from your file manager. It should work once it is the correct path.
