### ISSUE TITLE
Not Responding

### ISSUE THREAD

**Issue by adamjhursh** [OpenShot/openshot-qt#1223]
I am operating Windows 10 64 bit, using Open Shot 2.4.1.

Every time I go to edit my project it goes into not responding, and it extremely sluggish.  I am extremely disappointed in this software for this exact issue.  I tried to deal with it but cannot continue.

**Comment by LtFarns** [comment]
Please delete this, it is not specific enough for devs to resolve. I also have software installed and experience moments when response is ok. Start with a new project and slowly test all features. Make note of items that work fluidly and when lag begins after an added item. This will help devs better improve open shot for all of us.

**Comment by DylanC** [comment]
Not enough details.
