### ISSUE TITLE
Am I missing some effects?

### ISSUE THREAD

**Issue by Ericjar** [OpenShot/openshot-qt#1224]
Running Linux Mint 18.3 on 64 bit laptop 4 GB RAM Intel core I5

Openshot version 2.4.1
**Issue Description and steps to reproduce:**
Just wondering ... also running this on Windows and both just show 7 "effects" in the effects tab ares. I realize they are customizable just thought there were more to begin with. Pretty sure an older version I had had more.

**Comment by DylanC** [comment]
@Ericjar - Yes, the effects need to be recreated for the new version.

**Comment by Ericjar** [comment]
Ahhhh... OK thanks, just wasn't sure if somehow I got a bad package. Hoping to migrate away from some other editors gradually :)

I guess I will have to come here to check now and then.

**Comment by DylanC** [comment]
@Ericjar - No problem. :)  Once the project has better performance and reliability I think effects will be added then. Maybe check back every 4 months or so to see if they are added.
