### ISSUE TITLE
Inkscape doesn't edit the subtitles

### ISSUE THREAD

**Issue by rogerio77** [OpenShot/openshot-qt#1225]
**System Details:*Intel® Core™ i5-7300U CPU @ 2.60GHz × 4  Gallium 0.4 on llvmpipe (LLVM 3.9, 256 bits) Memory 7.3 Giga*
* Operating System / Distro:  Red Hat Enterprise Linux Workstation 7.4?
* OpenShot Version: 2.4.1-Dev1 (Jan 21)
* _Please attach log files if crash_

**Issue Description and steps to reproduce: When I go to modify a subtitle in Ilkscape it doesn't work. Look the video to see further details https://youtu.be/PDnWVYhGuPE

**Comment by rogerio77** [comment]
Any update or comment?This tool has been tested before in this OS? I mean in Red Hat Enterprise Linux Workstation 7.4?

**Comment by PASTJL** [comment]
Did you get a system error when you save from Inskape? Try to only change the text with Inskape and see if the text is modified in OpenShot ...
With my Kubuntu i have got an error of writing in /home/<user>/.openshot_qt (Inskape (snap package)).
The workaround for me is to rename the folder .openshot.qt by openshot_qt ( removing the dot at the beginning) and create a symbolic link as below  
**ln -s /home/&lt;user&gt;/openshot_qt /home/&lt;user&gt;/.openshot_qt** 
the symbolic link correct the error of writing ( Before i have tested **chmod -R 755 .openshot_qt** with no success).
I have tried what you do in your youtube video and runs correctly for me ( adding an emoticon). I download the last version ( 3 Feb 2018) of OpenShot.

**Comment by DylanC** [comment]
@rogerio77 - This is running fine for me. I think it must be something to do with RH Linux. I must test in this OS to see can I reproduce.

**Comment by DylanC** [comment]
Cannot reproduce this issue.
