### ISSUE TITLE
Razor vs. Slice

### ISSUE THREAD

**Issue by anarchopunkbarbie** [OpenShot/openshot-qt#1228]
**System Details:**
* Kubuntu / Distro: 16.04.3 LTS
  Quad-core i5, 4GB RAM
* OpenShot Version: 2.4.1-dev1

[ISSUE]
The Razor tool causes CPU and RAM usage > 97% each, which leads to choppy playback without audio in preview, extremely long export times, and no audio present in exported video.

[SOLUTION]
Placing the marker and using the Slice option from a context (right-click) menu on the marker head works flawlessly.

Not sure why the Razor tool affects system resources differently than the Slice option, but glad to have figured out a way to make it work.

**Comment by anarchopunkbarbie** [comment]
[UPDATE]
I take that back. Slice does in fact seem to resolve the CPU and memory issue(s), and the video plays in the preview, but upon export the audio is removed. I have verified that it is set to export audio and video.
![openshotbugreport1](https://user-images.githubusercontent.com/35823435/35422477-e49cab26-0216-11e8-92b5-927622081fb2.png)

**Comment by anarchopunkbarbie** [comment]
If it helps ...

Codec info of exported video from VLC:
![openshotbugreport2](https://user-images.githubusercontent.com/35823435/35422760-4fa94d24-0218-11e8-87d4-de573aa4331c.png)

Codec info of original video from VLC:
![openshotbugreport3](https://user-images.githubusercontent.com/35823435/35422811-86ae612e-0218-11e8-8e3e-e77b9434ba7f.png)

**Comment by DylanC** [comment]
@anarchopunkbarbie - Should this issue be closed?

**Comment by anarchopunkbarbie** [comment]
I switched to Kdenlive when I was unable to resolve this issue.

**Comment by peanutbutterandcrackers** [comment]
@anarchopunkbarbie - Could you please try out the latest [daily build](https://github.com/OpenShot/openshot-qt/releases/tag/daily) and see if that works? Perhaps use [daily PPA](http://openshot.org/ppa)? We'd really like to help you...
