### ISSUE TITLE
When file is dragged in, it rotates 90 degrees

### ISSUE THREAD

**Issue by DJase** [OpenShot/openshot-qt#1229]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

**Comment by DJase** [comment]
When file is dragged in, it rotates 90 degrees

**Comment by DylanC** [comment]
@DJase - I saw a fix went in for videos with rotate metadata. I would recommend to try a new daily build soon and see if the issue is still there.
