### ISSUE TITLE
is www.google-analytics.com called when running the program??

### ISSUE THREAD

**Issue by brobr** [OpenShot/openshot-qt#123]
Output when running from terminal:

`bash-4.3$ python3 src/launch.py 
Loaded modules from current directory: /home/sbo_64/OPENSHOT/OPENSHOT-QT/openshot-qt-master/src
      launch:INFO ------------------------------------------------
      launch:INFO    OpenShot (version 2.0.6)
      launch:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.0.6
         app:INFO libopenshot version: 0.1.0
         app:INFO platform: Linux-4.4.4-x86_64-Intel-R-_Core-TM-_i7-3632QM_CPU_@_2.20GHz-with-slackware-14.2
         app:INFO processor: Intel(R) Core(TM) i7-3632QM CPU @ 2.20GHz
         app:INFO machine: x86_64
         app:INFO python version: 3.5.1
         app:INFO qt5 version: 5.5.1
         app:INFO pyqt5 version: 5.5
    language:INFO Qt Detected Languages: ['en-US']
    language:INFO LANG Environment Variable: en_US
    language:INFO LOCALE Environment Variable: en_US
    language:INFO Skipping English language (no need for translation): en_US
    language:INFO Skipping English language (no need for translation): en_US
project_data:INFO Setting default profile to HDV 1080 25p 1920x1080
         app:INFO Setting font to /home/sbo_64/OPENSHOT/OPENSHOT-QT/openshot-qt-master/src/images/fonts/Ubuntu-R.ttf
         app:INFO Setting custom dark theme
link SVGID_18_-5 hasn't been detected!
link SVGID_18_-5 hasn't been detected!
link SVGID_22_-5 hasn't been detected!
link SVGID_24_-2 hasn't been detected!
link SVGID_24_-2 hasn't been detected!
     ui_util:INFO Initializing UI for MainWindow
     ui_util:INFO Binding event MainWindow:actionNew_trigger
     metrics:INFO Track metric: {'date': 'Sun, 28 Feb 2016 22:17:45 GMT', 'last-modified': 'Sun, 17 May 1998 03:00:00 GMT', 'access-control-allow-origin': '*', 'content-type': 'image/gif', 'server': 'Golfe2', 'cache-control': 'no-cache, no-store, must-revalidate', 'content-length': '35', 'pragma': 'no-cache', 'content-location': 'http://www.google-analytics.com/collect?cd=main-screen&cd4=5.5&aip=1&cid=7c6cd6c9-5c08-4bf3-87aa-2d3bc1fd92e3&tid=UA-4381101-5&an=OpenShot+Video+Editor&t=screenview&v=1&av=2.0.6&aid=org.openshot.openshot-qt&cd5=Slackware+-14.2-&cd3=5.5.1&ul=en&ua=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&cd2=3.5.1&cd1=0.1.0', 'expires': 'Mon, 01 Jan 1990 00:00:00 GMT', 'age': '698198', 'status': '200', 'x-content-type-options': 'nosniff'} (b'GIF89a\x01\x00\x01\x00\x80\xff\x00\xff\xff\xff\x00\x00\x00,\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x02D\x01\x00;')
     ui_util:INFO Binding event MainWindow:actionOpen_trigger
     metrics:INFO Track metric: {'date': 'Sun, 28 Feb 2016 21:10:36 GMT', 'last-modified': 'Sun, 17 May 1998 03:00:00 GMT', 'access-control-allow-origin': '*', 'content-type': 'image/gif', 'server': 'Golfe2', 'cache-control': 'no-cache, no-store, must-revalidate', 'content-length': '35', 'pragma': 'no-cache', 'content-location': 'http://www.google-analytics.com/collect?cd=launch-app&cd4=5.5&aip=1&cid=7c6cd6c9-5c08-4bf3-87aa-2d3bc1fd92e3&tid=UA-4381101-5&an=OpenShot+Video+Editor&t=screenview&v=1&av=2.0.6&aid=org.openshot.openshot-qt&sc=start&cd5=Slackware+-14.2-&cd3=5.5.1&ul=en&ua=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&cd2=3.5.1&cd1=0.1.0', 'expires': 'Mon, 01 Jan 1990 00:00:00 GMT', 'age': '702227', 'status': '200', 'x-content-type-options': 'nosniff'} (b'GIF89a\x01\x00\x01\x00\x80\xff\x00\xff\xff\xff\x00\x00\x00,\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x02D\x01\x00;')
     ui_util:INFO Binding event MainWindow:actionSave_trigger
     ui_util:INFO Binding event MainWindow:actionUndo_trigger
     ui_util:INFO Binding event MainWindow:actionSaveAs_trigger
     ui_util:INFO Binding event MainWindow:actionImportFiles_trigger
     ui_util:INFO Binding event MainWindow:actionImportImageSequence_trigger
     ui_util:INFO Binding event MainWindow:actionRedo_trigger
     ui_util:INFO Binding event MainWindow:actionRemoveClip_trigger
     ui_util:INFO Binding event MainWindow:actionRemoveTransition_trigger
     ui_util:INFO Binding event MainWindow:actionExportVideo_trigger
     ui_util:INFO Binding event MainWindow:actionUploadVideo_trigger
     ui_util:WARNING Icon theme gtk-quit not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAddTrack_trigger
     ui_util:INFO Binding event MainWindow:actionPreferences_trigger
     ui_util:INFO Binding event MainWindow:actionPlay_trigger
     ui_util:INFO Binding event MainWindow:actionJumpStart_trigger
     ui_util:INFO Binding event MainWindow:actionRewind_trigger
     ui_util:INFO Binding event MainWindow:actionFastForward_trigger
     ui_util:INFO Binding event MainWindow:actionJumpEnd_trigger
     ui_util:INFO Binding event MainWindow:actionArrowTool_trigger
     ui_util:INFO Binding event MainWindow:actionSnappingTool_trigger
     ui_util:INFO Binding event MainWindow:actionAddMarker_trigger
     ui_util:INFO Binding event MainWindow:actionPreviousMarker_trigger
     ui_util:INFO Binding event MainWindow:actionNextMarker_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowAll_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowVideo_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowAudio_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowImage_trigger
     ui_util:INFO Binding event MainWindow:actionTransitionsShowAll_trigger
     ui_util:INFO Binding event MainWindow:actionTransitionsShowCommon_trigger
     ui_util:INFO Binding event MainWindow:actionEffectsShowAll_trigger
     ui_util:INFO Binding event MainWindow:actionEffectsShowVideo_trigger
     ui_util:INFO Binding event MainWindow:actionEffectsShowAudio_trigger
     ui_util:INFO Binding event MainWindow:actionTimelineZoomIn_trigger
     ui_util:INFO Binding event MainWindow:actionTimelineZoomOut_trigger
     ui_util:INFO Binding event MainWindow:actionTitle_trigger
     ui_util:INFO Binding event MainWindow:actionAnimatedTitle_trigger
     ui_util:INFO Binding event MainWindow:actionFullscreen_trigger
     ui_util:INFO Binding event MainWindow:actionExit_Fullscreen_trigger
     ui_util:INFO Binding event MainWindow:actionAbout_trigger
     ui_util:WARNING Icon theme gtk-info not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionThumbnailView_trigger
     ui_util:WARNING Icon theme view-preview not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionDetailsView_trigger
     ui_util:WARNING Icon theme view-list-details not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionReportBug_trigger
     ui_util:INFO Binding event MainWindow:actionAskQuestion_trigger
     ui_util:WARNING Icon theme im-message-new not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionTranslate_trigger
     ui_util:WARNING Icon theme stock_person not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionDonate_trigger
     ui_util:INFO Binding event MainWindow:actionHelpContents_trigger
     ui_util:WARNING Icon theme help not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionSimple_View_trigger
     ui_util:INFO Binding event MainWindow:actionAdvanced_View_trigger
     ui_util:WARNING Icon theme get-hot-new-stuff not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionFreeze_View_trigger
     ui_util:WARNING Icon theme locked not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionUn_Freeze_View_trigger
     ui_util:WARNING Icon theme locked not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionShow_All_trigger
     ui_util:INFO Binding event MainWindow:actionProfile_trigger
     ui_util:INFO Binding event MainWindow:actionAdd_to_Timeline_trigger
     ui_util:INFO Binding event MainWindow:actionPreview_File_trigger
     ui_util:INFO Binding event MainWindow:actionRemove_from_Project_trigger
     ui_util:INFO Binding event MainWindow:actionRemoveTrack_trigger
     ui_util:INFO Binding event MainWindow:actionRemoveMarker_trigger
     ui_util:INFO Binding event MainWindow:actionAddTrackAbove_trigger
     ui_util:INFO Binding event MainWindow:actionAddTrackBelow_trigger
     ui_util:INFO Binding event MainWindow:actionRemoveEffect_trigger
     ui_util:INFO Binding event MainWindow:actionSplitClip_trigger
     ui_util:INFO Binding event MainWindow:actionProperties_trigger
     ui_util:INFO Binding event MainWindow:actionRenameTrack_trigger
     ui_util:WARNING Icon theme gtk-edit not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionUpdate_trigger
 files_model:INFO updating files model.
transition_model:INFO updating transitions model.
timeline_webview:INFO Qt Found!
timeline_webview:INFO $scope.Qt = true;
     version:INFO Found current version: {'date': 'Tue, 08 Mar 2016 00:40:59 GMT', 'content-length': '29', 'content-type': 'application/json', 'server': 'Apache/2.2.22 (Ubuntu)', 'content-location': 'http://www.openshot.org/version/json/', 'status': '200'} (b'{"openshot_version": "2.0.6"}')
 main_window:INFO foundCurrentVersion: Found the latest version: 2.0.6
effects_model:INFO updating effects model.
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
properties_model:INFO updating clip properties model.
preview_thread:INFO QThread Start Method Invoked
preview_thread:INFO initPlayer
 main_window:INFO Clear all thumbnails: /home/rob/.openshot_qt/thumbnail
 main_window:INFO Clear all animations: /home/rob/.openshot_qt/blender
 main_window:INFO Clear all backups: /home/rob/.openshot_qt/backup
project_data:INFO Setting default profile to HDV 1080 25p 1920x1080
preview_thread:INFO refreshFrame
preview_thread:INFO self.player.Position(): 1
 main_window:INFO updateStatusChanged
         app:INFO Process command-line arguments: ['src/launch.py']
 main_window:INFO updateStatusChanged
preview_thread:INFO onModeChanged
preview_thread:INFO exiting thread
     metrics:INFO Track metric: {'date': 'Sun, 28 Feb 2016 22:09:27 GMT', 'last-modified': 'Sun, 17 May 1998 03:00:00 GMT', 'access-control-allow-origin': '*', 'content-type': 'image/gif', 'server': 'Golfe2', 'cache-control': 'no-cache, no-store, must-revalidate', 'content-length': '35', 'pragma': 'no-cache', 'content-location': 'http://www.google-analytics.com/collect?cd=close-app&cd4=5.5&aip=1&cid=7c6cd6c9-5c08-4bf3-87aa-2d3bc1fd92e3&tid=UA-4381101-5&an=OpenShot+Video+Editor&t=screenview&v=1&av=2.0.6&aid=org.openshot.openshot-qt&sc=end&cd5=Slackware+-14.2-&cd3=5.5.1&ul=en&ua=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&cd2=3.5.1&cd1=0.1.0', 'expires': 'Mon, 01 Jan 1990 00:00:00 GMT', 'age': '698700', 'status': '200', 'x-content-type-options': 'nosniff'} (b'GIF89a\x01\x00\x01\x00\x80\xff\x00\xff\xff\xff\x00\x00\x00,\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x02D\x01\x00;')
bash-4.3$ 
`

**Comment by CiaranG** [comment]
Yes - by default, and without asking or telling you in any way that it's doing so, it's reporting your actions as you move between the various screens, etc. You can turn it off in preferences, if you happen to stumble across it in the 'Debug' tab.

I'm not one of them, but I understand there are actually people who think it's ok for software to do this.

**Comment by Bugsbane** [comment]
I have no issue with making this available as opt-in to help provide feedback to the developer, however there is no way this is OK by default and without telling the user. No user expects that their actions are going to be fed back to a central server while using a video editing app.

**Comment by DerGenaue** [comment]
While I agree with you opinions, I think this is ok for an early Beta Application as this is.
There really should be a popup informing you about it though.

**Comment by Bugsbane** [comment]
Yes, although I do think it needs to state that it's via Google Analytics. Personally, I had no problem with Johnathon having all of the details of what I work on, as the potential for abuse there is low. I do have an issue with my data going to Google though, as the potential for abuse is much higher as a Prism partner with enough data about all of us to make the claim that the data collection is anonymous, questionable. Google generally knows who most people are with no more than your IP address, even if you're not logged in. Years ago it came out they had 43 data points they use to identify a person (of which being logged in to a google account is only 1) and tie all of the new information back to them, and they only need one or two data points to correlate.

I would suggest that the debug entry at the very least adds "via Google Analytics" and that the user is warned on opening if it's going to be on by default. Personally I question how anonymous it is really, and so feel uncomfortable with that phrase being used.

**Comment by sydneyjd** [comment]
I feel the same as Bugsbane. This is just not right. At least let the user know with a window or something that this is happening. I'm not impressed by this...

**Comment by jonoomph** [comment]
Thanks for the feedback everyone! I plan on turning this into a prompt on first run... once the final version is ready. This data has been crucial for me to track down bugs, and it is literally just anonymous meta-data... and the IP is anonymized through the API I use. I get zero IP related data. 

I get version info, screen name, exception details, os name and version, language, and date. That's about it I think. 

But I do understand the concern, and will certainly flip this around and let the user decide once we are done with beta testing. Thx!

**Comment by ebfe** [comment]
Unfortunately this is still enabled by default in the 2.1 release.

**Comment by tbalthazar** [comment]
Thanks for the awesome work on OpenShot.
Google tracking is still enabled by default in v2.2. :(

**Comment by jonoomph** [comment]
I'll start working on a simple "prompt" to enable error reporting and metric tracking, and default this off in the next release. I'll update this ticket once it's ready for testing. Thanks everyone.

**Comment by Bugsbane** [comment]
Thanks Johnathon. This goes a long way. Personally my preference would be to still provide you with the usage data (presuming it's useful to you) but just not to google et al. Any chance that Google Analytics could be swapped out for Piwik or Open Web Analytics in a future version?
