### ISSUE TITLE
Won't show my video when Im editing

### ISSUE THREAD

**Issue by SebastianCrafts** [OpenShot/openshot-qt#1231]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

**Comment by DylanC** [comment]
@SebastianCrafts - Is the preview not playing or what do you mean here?

**Comment by DylanC** [comment]
Closing due to lack of details.

**Comment by peanutbutterandcrackers** [comment]
Perhaps the [daily builds](https://github.com/OpenShot/openshot-qt/releases/tag/daily) might work for you?
