### ISSUE TITLE
1:1 Ratio needed and how to re position a clip?

### ISSUE THREAD

**Issue by Jareth100** [OpenShot/openshot-qt#1232]
**System Details:**
* Operating System / Distro: WIN10
* OpenShot Version: 2.4.1

I have two questions that I need help with (I'm a newbie, so try to explain it in simple terms)
1. I need to create social videos, which means the best ration for me is 1:1 so there won't be any black bars. The profiles I went over don't have this ratio. How can I make one?

2. I have a premade animation of an intro, which I am trying to put on top of another clip. The into is 16:9 and the clip is 1:1, so the intro is playing mostly outside the clip. Do I have a way to move the into to the right, so it plays on top of the clip?

Thanks!

**Comment by peanutbutterandcrackers** [comment]
@Jareth100 - [Here](https://www.openshot.org/static/files/user-guide/profiles.html#custom-profile) is how you create a custom profile in OpenShot. It might help you with your first question. I'm not so very sure about the second one. Sorry.

I hope that helps. 👍

**Comment by DylanC** [comment]
@Jareth100 - Did you try the right click menu>>Layout?

**Comment by DylanC** [comment]
Closing this as the question has been answered.
