### ISSUE TITLE
Is live scrubbing available?

### ISSUE THREAD

**Issue by rstimers** [OpenShot/openshot-qt#1233]
MacBook Pro i7 2.3GHz 
16GB RAM
macOS High Sierra 10.13.2
NVIDIA GeForce GT 750M 2GB
OpenShot Version 2.4.1

I watched a bunch of reviews and OpenShot seemed to have everything I needed and looked great so I downloaded and installed but seconds into my first test I ran into a bit of a problem - no live scrubbing.  It seems the preview buffers 20 seconds or so that I can drag the playhead back and forth through but anything beyond that is blank.  In iMovie, I can scrub the entire video with no problem or delay.  I record my kids' sports from a stationary camera and then go in and edit out the parts where they are not on field.  To do this, I need to scrub through the video looking for when they enter or exit the field.  Is there a way to change the scrubbing in OpenShot? Or am I missing something?  Or is there another workflow that I can/should use to locate the spots I want to trim?

Thanks,

Rob.

**Comment by rstimers** [comment]
Update: so that was in a 1.5 hour video.  I just uploaded a 3.5 minute video and it appears I CAN live scrub it in it's entirety.  Is it just a file size issue?  As I said, I live scrubbed the 1.5 hour video in iMovie so it wouldn't appear to be a hardware limitation.

**Comment by N3WWN** [comment]
@rstimers The preview performance can be tweaked for your system by altering the values in the cache preferences.

Check out this comment for how I did this on my system: https://github.com/OpenShot/openshot-qt/issues/960#issuecomment-337678019

**Comment by rstimers** [comment]
@N3WWN  Thanks for your reply.  I adjusted the settings and all it did was make the video preview highly pixelated and choppy.  The scrubbing did not change - I can still only scrub what the playhead has played in real time.  I can't move the playhead forward ten minutes and scrub, the preview just goes black or loads a screen from the new area but freezes.
