### ISSUE TITLE
 Cannot open new project 

### ISSUE THREAD

**Issue by sciamano69** [OpenShot/openshot-qt#1234]
**System Details: *64-bit operating system, x64-based processor**
* Operating System / Distro: *Windows 10*
* OpenShot Version: 2.4.1

**When I start Openshot there is no crash and I can work but  I cannot open a new project. Is it normal?
With the same version in ubuntu I can open a new project, but in Windows 10 I cannnot.
Thank you**

**Comment by DylanC** [comment]
@sciamano69 - What happens when you try to start a new project?

**Comment by sciamano69** [comment]
Nothing. I can click but nothing happens. I can import files and use openshot normally but no way to open a project.

**Comment by jgrasser** [comment]
@DylanC the user is correct. On a fresh install, clicking the New Project option will not cause any affect on the application. Presumably this is something to do with the way that Openshot manages project data. Selecting the Save Project As will open a dialog and allow for saving a project. If you select New Project at this point, the project will change as is evident by the project name changing in the title bar. 

I think that project creation and management could be done in a more intuitive way. Perhaps, prevent the user from import assets until the new project option is selected, or a saved project restored.

**Comment by DylanC** [comment]
@jgrasser - Thanks! Confirmed this as a bug.
