### ISSUE TITLE
Preview of video will not play past 29:59

### ISSUE THREAD

**Issue by pete51x** [OpenShot/openshot-qt#1236]
I have imported a 1 hour 40m MP4 video into OpenShot but the preview won't play past 29:59
I have tried re-loading without success. It still sticks at 29:59
I have a windows 8 computer

My  OpenShot Version: is 2.4.1

Can anyone help??  It' really frustrating.

Thanks

**Comment by peanutbutterandcrackers** [comment]
There have been a lot of issues of late being reported that seem to be windows specific. This one just seems to be one  too. Although I haven't really tried to edit such a long video on my Linux machine...
