### ISSUE TITLE
Posibility for cuda and(or) openGl 

### ISSUE THREAD

**Issue by 07pepa** [OpenShot/openshot-qt#1237]
hello there... 

i found out that blender could use cuda even managed 
 to get it working... (https://docs.blender.org/manual/en/dev/render/cycles/gpu_rendering.html)

for someone with beefy graphic it would be nice for performance benefit... ialso read somewhere that it could be enforced by cli params (little to no work)

**Comment by peanutbutterandcrackers** [comment]
That would be just great. Now, if only nouveau and other open source graphics drivers would also work really well, we'd finally be able to live in a Stallman Eutopia. :)

**Comment by DylanC** [comment]
Dup of #527

**Comment by ferdnyc** [comment]
Closing as dup of #2812, which has a WIP implementation in #2825.
