### ISSUE TITLE
Can no longer import files into program

### ISSUE THREAD

**Issue by bellano** [OpenShot/openshot-qt#1238]
**System Details:**
* Operating System / Windows 8.1
* OpenShot Version: 2.4.1

In the not-so-distant past, I had no problem importing or dragging/dropping files into the software.
Now when I drag & drop, the file icon shows a red circle with a slash through it whenever it reaches the drop window.  
When I try to import, it shows nothing in the window afterward.

Can't figure out where things went wrong.  :(

bellano

**Comment by peanutbutterandcrackers** [comment]
Perhaps un-installing the program, [Optional: performing a registry and misc. files cleanup using one of them 'Cleaners' for windows or some other stuff], and installing the program again might solve it? Reboot before and after the re-installation would be highly preferable too.

It's strange, OpenShot works really well on my Linux Machine (Elementary OS 0.4.1 'Loki'). Must be something Windows-specific.

If the program does not work even after the reinstalltion, perhaps something has caused the regression. There are a lot of windows-specific issues here, these days. I wonder why...

**Comment by DylanC** [comment]
@bellano - Can you try a daily build please?
