### ISSUE TITLE
OpenShot grinds to a halt if there're four files (or more) on the timeline

### ISSUE THREAD

**Issue by FlyingScoots** [OpenShot/openshot-qt#1239]
**System Details:**
* Operating System / Distro: Windows 10 x64
* OpenShot Version: 2.4.1

Hello.
So, I'm doing a little project where I'm basically just overlaying images over a video. Should be simple enough, right?
The video in question is tiny. We're talking an 8 megabyte 720p 24fps mp4 file. And images in question are also small, roughly 500 KB each.
Problem is, OpenShot slows down dramatically if I add a second image. It makes resizing it and making it track over a point in the video that I want very slow and frustrating. And then by the time I add a third image, the program freezes for up to five minutes at a time at seemingly random intervals, making any work impossible.
It also starts to take progressively longer and longer to save project files. In the above case I've managed to save a project file that came out to be something like 12 megabytes, but reopening it took solid 10 minutes, and then the program froze never to respond again within the time that I cared for.

I kinda refuse to believe that OpenShot can't handle the load I'm throwing at it. My computer also should be more than capable of handling this stuff. Plus, OpenShot performed admirably when I used it to simply convert gigantic 15-20GB .avi files from Fraps, usually at 50 fps and 1080p, into much smaller mp4 files which I then used to make videos with the Movie Maker.
Is there something I can do? Any attempts to look up similar issues turned up posts that are a few years old with complaints not as detailed as mine and no fix coming up in them.

Thanks. If anyone helps me to work this one out, that is...

**Comment by peanutbutterandcrackers** [comment]
Like I was just pointing out to someone else:

> Issues like these do not happen on my linux machines. It seems that there are a lot of windows-specific bugs in openshot. Because of lack of developers esp to look after windows versions, the project is falling behind. But I think that once he has the time, Mr. Jonathan Thomas - our one and only developer for now - will hopefully get around to solving these issues. Sorry for the inconvienience...

**Comment by peanutbutterandcrackers** [comment]
Perhaps this video: https://youtu.be/aci-ViWAEqs might be of some assistance.
