### ISSUE TITLE
Tremendously slow processing persists.

### ISSUE THREAD

**Issue by OK64** [OpenShot/openshot-qt#1240]
System Details:
Operating System: Win 10
OpenShot Version: v2.4.1-x86_64

Each action performed successively places a higher load on the program at an exponent rate.
Closing and re-opening the software seems to reset this load back to a feasible working rate, however, only for several actions before it is unfeasible to work with yet again.

I have only installed this program today and was astounded by the great level of utility this program provided, however soon got very choked up by the serious lack of garbage management.

By reading the past year's logs I am under the impression that there is a lacking interest in the team for fixing this major problem, that is, making this program usable again.
I am rather disappointed to see that this bug has persisted for half a year now.

PS.
This program may be free, but the time the developers have invested into it was not. It would be a shame to see it go to waste by letting such an issue get in the way.

**Comment by DylanC** [comment]
@OK64 - I know. In the past I used the 1.x series of OpenShot always and it was great. This is why I want to help the project be more successful. I do think it has fantastic potential to be become as good as the 1.x series and even better in the future.

I'm not sure I would say the devs don't have interest in that area, it may be more a question of time and technical knowledge in that specific area.

**Comment by HemoglobinSlayer** [comment]
Good day all,
I am having the same problem. As soon as I start snipping clips and adding more than 3 to 4 videos the program becomes unusable. With unusable I mean any action you take on the program takes longer than a minute.
When using any action on the software it only uses 20% CPU and 1.6gb RAM. Thus I have no idea what could be the cause of the problem. I have turned the preview off but still the same problem persists.
Hope there is a fix. Really like the software.

Think my system specs should be more than efficient enough:
I7 - 7820 CPU @ 2.90 GHz
32gb 2400MHz SODIMM RAM
GTX1070 GPU
512gb SSD
Windows 10 x64

**Comment by Slivo-fr** [comment]
I'm experiencing the same issue there, anything I can provide to help to debug ?

**Comment by Tobselotzi** [comment]
Same problem here on:
Operating System: Windows 10 Home 64-bit (10.0, Build 16299) (16299.rs3_release.170928-1534)
BIOS: BIOS Date: 10/27/16 13:01:14 Ver: V1.00
Processor: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 CPUs), ~4.2GHz
Memory: 16384MB RAM
DirectX Version: DirectX 12
NVIDIA GeForce GTX 1060 6GB

**Comment by Elirocca** [comment]
I am having the same problem. I have notebook with all the requirements and 100% dedicated to editing videos, but the processing time is just terrible. Any other free software suggestion instead?

**Comment by petesimon** [comment]
Shotcut at www.shotcut.org is nice

**Comment by peanutbutterandcrackers** [comment]
Yeah. Shotcut is great too. And so is Kdenlive. But the thing is, there are quite a few volunteers and developers in those projects. They use a separate multimedia library, too, while OpenShot is the "labor of love" of (mostly) a single man, from the ground up - including the multimedia library - libopenshot. Just letting you know why there are so many issues with this project...

**Comment by DylanC** [comment]
@OK64 - Have you tried a daily build at all? People have reported better success on Windows systems.

**Comment by peanutbutterandcrackers** [comment]
@Tobselotzi - With version 2.4.2? Please be patient with OpenShot, good sir. You might see some more improvements in the 2.4.2.x bug-fix series. This is not a commercial product but a labour of love of people who believe that software should be free as in freedom. :)

**Comment by OK64** [comment]
Hello, I have installed and tested the latest version; it seems to be operating relatively smoothly now.
Great work!

**Comment by peanutbutterandcrackers** [comment]
@OK64 - Awesome! Please do keep on loving and supporting OpenShot! It'll get better with time! :smile:

**Comment by Slivo-fr** [comment]
I still experience this issue on my side
