### ISSUE TITLE
Please make it work for ubuntu 17.04 (newest version)

### ISSUE THREAD

**Issue by GoldCraft1000** [OpenShot/openshot-qt#1242]
please make it work for ubuntu 17.04 (newest version)
if it works please help me :D 
Err:8 http://ppa.launchpad.net/openshot.developers/ppa/ubuntu artful Release   
  404  Not Found
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/openshot.developers/ppa/ubuntu artful Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage 

tried doing apt-secure and sudo apt-secure and none works :D 

os info for techical guys :D 

4.13.0-32-generic (#35-Ubuntu SMP Thu Jan 25 09:13:46 UTC 2018)
GNOME 3.26.2 (Ubuntu)

**Comment by DylanC** [comment]
@GoldCraft1000 - Usually we would recommend to use the AppImage. Its more reliable to test OpenShot than the PPA.

**Comment by GoldCraft1000** [comment]
Problem solved.
i don't know how to install using an AppImage and the PPA didn't work.
so what i did was that i went to the ubuntu software center and downloaded openshot from there and voila it works :D
