### ISSUE TITLE
video image quality - 4k settings 

### ISSUE THREAD

**Issue by badninja23** [OpenShot/openshot-qt#1243]
16GB ram, intel i7, 4.2GHz, 64 bit, geforce 1070
windows 10 pro
open shot 2.4.1

Hello
So I am looking for an alternative to Premiere for my 4k drone footage. It seems like the quality isn´t that good upon exporting from openshot, the funny thing is it seems to be just as noisy when I export in HD as when I export in 4K. The footage is in H264 30FPS
Where am I losing quality?
Many thanks in advance

**Comment by peanutbutterandcrackers** [comment]
Even when you set the quality to 'high'?

**Comment by badninja23** [comment]
Thanks peanutbutterandcrackers  👍 👍
I checked in profiles and settings for an option to choose high quality but couldn't see it. Where would I choose high quality?
The profile I use is 4K UHD 30FPS
Any suggestiosn greatly appreciated! :-)

**Comment by peanutbutterandcrackers** [comment]
You're most welcome. :)

Not in the profiles, but when you click on 'Export', in the dialogue that opens up, you should see 'Target', 'Video Profile' and 'Quality'. Please do make sure that the 'Quality' is set to 'High'.

I'm not sure if that will work for real, but I think it's worth a shot.

Hope that helps!

**Comment by peanutbutterandcrackers** [comment]
Here: [This](https://www.openshot.org/static/files/user-guide/quick_tutorial.html#step-5-export-your-video) might be of some help too.

**Comment by badninja23** [comment]
Yes my good man, totally sorted. Big up yourself!!!! PB and C FTW!!!!

**Comment by peanutbutterandcrackers** [comment]
I'm glad that it worked out for you. 👍 😄 

Please do keep on supporting OpenShot and making bug reports and stuff. :)

**Comment by peanutbutterandcrackers** [comment]
P. S: Geekoutdoors FTW, too. :)
