### ISSUE TITLE
OpenShot 2.4.1 won't open - cx_Freeze Python error in main script

### ISSUE THREAD

**Issue by StollenTorch** [OpenShot/openshot-qt#1244]
**System Details:** 
Intel i5
8gb ram
Asus 6gb gtx 1060
* Operating System / Distro: ?
Windows 10
* OpenShot Version: ?
2.4.1
* _Please attach log files if crash_
![error](https://user-images.githubusercontent.com/36052886/35701509-e1156160-075b-11e8-854f-f61fdc9bde1f.PNG)

**Issue Description and steps to reproduce:**
I've tried uninstalling and reinstalling, running as an administrator, nothing helps

**Comment by LtFarns** [comment]
what are the exact steps taken that makes the error occur? are you able to drop a vid onto timeline? does it happen when you import a vid clip? does it occur on program launch. please Be as specific as possible

**Comment by StollenTorch** [comment]
It quite literally can't open the program

**Comment by DylanC** [comment]
@StollenTorch - Does it happen with a new project? Usually it means the program is looking for a file in the project that has been removed another way like the file manager.

Note you make need to delete the .osp backup file in case it still tries to load that on startup.

**Comment by osve001** [comment]
Intel i5-7600
16GB RAM
Win7Pro x64
OpenShot-v2.4.1-x86_64.exe

![openshoterror_cx_freeze](https://user-images.githubusercontent.com/28224249/35817382-83a30d30-0a9d-11e8-8256-561b28a8599c.png)

Yesterday morning It was working fine. In the afternoon, It does not open. Nothing changed on the PC (sw or hw). Everything else on the PC is working fine. Then, I uninstalled Openshot, redownloaded and reinstalled it (several times) and get same error message.
I´ve been reading about it over here, but no solutions so far.

Thanks for your help.

**Comment by silentdistrict** [comment]
Experience the exact same script. Was working almost perfectly yesterday then today it just started showing up with this message. Uninstalled, backup, nothing seems to be working.

**Comment by contaminatedesert** [comment]
System Details:
Intel i5
8gb RAM
Acer Aspire E 15

Operating System / Distro: 
Windows 10 x86

OpenShot Version: 
2.4.1

Exact same thing happened to me. It was working one day and the next received identical error.

**Comment by osve001** [comment]
FIXED!
Hi everyone.
I noticed the following: I had two accounts on win7pro: admin (Openshot didn't open anymore) and a standard user (Openshot WORKED fine).
So, I decided to update my pc.
After a clean installation of windows 10 pro everything works smoothly. I think my old win7pro was the problem.
I hope this helps.
Thank you all for your help

**Comment by peanutbutterandcrackers** [comment]
@osve001 - I'm not sure if this is going to fix ALL of the cx_Freeze issue but let's see. From now on, I'll try to point out to this place when further cx_Freeze issue is reported. If it solves the issue for them too, then I'll be certain of it.

Plus, a clean installation does not really seem like the best of fixes.

So, the point is, when run as the Standard user, Openshot works just fine? 😕 I'm a bit confused. But then again, it's been quite a few years since I've deserted windows and all that stuff.....

@DylanC - What do you think about this?

**Comment by peanutbutterandcrackers** [comment]
@osve001 - But I'm glad it's been fixed for you. 👍 Hope you do keep on making great videos with OpenShot. :)

**Comment by DylanC** [comment]
@peanutbutterandcrackers - Its hard to know the source of the problem. Some people report only Openshot works well run in admin mode on Windows and others say only in a normal account it works good. 

Something around the accounts is causing issues but I think the problem is with AppImage or the way the AppImage is produced. Clean installs seem to be the only thing reported that works for users.

**Comment by peanutbutterandcrackers** [comment]
@DylanC - I have actually opened an issue in cx_Freeze's github repo regarding this because this morning I found a lot of non-OpenShot related issues being reported on the Internet while looking up for a solution for a user who seemed to be really frustrated because of the issue... Perhaps it is a bug over there?

AppImage? You probably mean the .exe files. Us Linux users are almost forgetting everything about windoze and macintoy now. 😆

**Comment by osve001** [comment]
NOT WORKING again!
Intel i5-7600
16GB RAM
Win10Pro x64 <---- CLEAN INSTALLATION (a week ago)
OpenShot-v2.4.1-x86_64.exe

![cx_freeze_error_openshot241](https://user-images.githubusercontent.com/28224249/36115415-522c5b30-1033-11e8-8107-e1640a0654d5.png)

It does not work on the admin account. But, again, it works on a stardard account.
Definitely, there is an issue with accounts in windows.

I've got dual boot (win10pro/Ubuntu 16.04) and Openshot works fine on Ubuntu.

On windows, I'll try to uninstall and reinstall Openshot. But, this time, only for the admin (instead for all users). I think the way to do so is by changing the target folder... Am I wrong?

**Comment by peanutbutterandcrackers** [comment]
I'm glad it works for you and that you have figured it out. I'll point others to this direction too. :)

**Comment by peanutbutterandcrackers** [comment]
Please do look forward to v2.4.2. This issue has been put on the list of the 'critical bugs to be fixed' for the release. OpenShot should finally work quite well on Windows Machines with v2.4.2. Please, do however continue to support OpenShot. Perhaps test the latest [daily build](https://github.com/OpenShot/openshot-qt/releases/tag/daily) if you have the time and report the issues as you encounter them. Thanks!

**Comment by lowlight-ua** [comment]
I have this problem on 2.4.2, and the workarounds described here don't work. Can't start the program.

**Comment by Flowo1f** [comment]
OPENSHOT STILL ISNT WORKING CHECK MY ERROR LINK HERE
https://github.com/OpenShot/openshot-qt/issues/2182#issue-366507356

**Comment by zenz** [comment]
@Flowo1f same problem, not work.

**Comment by Wimads** [comment]
Had the same issue with v2.4.4 64bit.
Just wanted to confirm, as per suggestion of @lowlight-ua , 32 bit version does indeed solve the issue. Thanks!

**Comment by michaelh99** [comment]
fwiw, I had this error the very first time I ran the 64 bit version 2.5.0 and the second time it came up just fine.  It's the only version that's ever been installed on this machine

**Comment by ferdnyc** [comment]
@michaelh99 Do you know which error, exactly? There have been a few different ones posted here, over time.

**Comment by michaelh99** [comment]
> > @michaelh99 Do you know which error, exactly? There have been a few different ones posted here, over time.

This one, which only happens the first time the app is launched, after a new install.  Note that I haven't tried again after a reboot so there could be some other interaction I haven't tested for.
I've just installed the 2.5.1 and got the same error as I did right after I installed 2.5.0.  I had uninstalled 2.5.0 after my last post when I determined that it couldn't be a replacement for me for Vegas Pro.

![openshoterror](https://user-images.githubusercontent.com/2307675/76252335-f2301600-621e-11ea-87e9-6dcf61e928f4.jpg)

**Comment by ferdnyc** [comment]
@michaelh99 
Hmm... It's trying to write to `C:\WINDOWS\system32\config\systemprofile\.openshot_qt` — no surprise it _can't_, but odd that it would be trying.

Were you running OpenShot as Administrator, by any chance? (Or is it setting itself up to do that automatically? If so, that's definitely unintended, only the installer should run as Administrator.)

...A replacement for Vegas Pro? No, I wouldn't think so. But thanks for taking the time to test that out anyway.

**Comment by michaelh99** [comment]
@ferdnyc 
> Were you running OpenShot as Administrator, by any chance? (Or is it setting itself up to do that automatically? If so, that's definitely unintended, only the installer should run as Administrator.)

No, installed and running as a normal user.
 
> ...A replacement for Vegas Pro? No, I wouldn't think so. But thanks for taking the time to test that out anyway.

Well, not a full replacement but maybe something that would load and run faster for simple editing.  OS is just different enough that I probably won't use it that way.
I'd be happy to do additional testing for you on this issue if you can think of things you like me to try

**Comment by ferdnyc** [comment]
@michaelh99 Appreciated! One quick thing you could check: Is there a `HOME` environment variable set in your user session? (You can check with `echo %HOME%` in a command shell, or there's a list buried in one of the user-account configuration dialogs.) Unfortunately Python itself had a bug, not fixed until 3.8, where it would respect that environment variable if it's set on Windows, instead of deferring to `%USERPROFILE%` like it's supposed to.

**Comment by martinlabarthe** [comment]
Hello guys and girls, solved this issue.

here you have the steps to fix it:
https://youtu.be/xpmDJFX3px8

**Comment by JanithK93** [comment]
I had the same issue. I tried reinstalling and it didnt work. So I tried slightly different method.

1. Uninstall the software
2. Navigated to the file location where it was installed. If there's should be a folder named as openshot video editor. Deleted it
3. Again wen to C drive > Users > Make user to visible hidden folders (view >put a tick on hidden items checkbox) > folder names with as your pc name
4. There is a folder as  ".openshot_qt". Delete it
5. Check if there are temp folders in Public and Default folders. If so delete
6. If possible restart
7. Now install the software again. Should work fine

**Comment by cocozuniga** [comment]
Same that happens with MS office 2019/21. Error when try to start. Solution: C:\ProgramData\Microsoft\Windows\Start Menu\Programs
Right button on "OpenShot Video Editor
Properties
Advanced options
Mark: run as administrator
Apply - Accept.
Ready!!
Now the Direct access will work fine.

**Comment by mahmoudatef2022** [comment]
![WhatsApp Image 2022-05-30 at 10 07 44 PM](https://user-images.githubusercontent.com/106587222/171137631-5a34c6ce-01de-44a2-a772-059010691756.jpeg)

how to fix this ? win7

**Comment by mahmoudatef2022** [comment]
> ![WhatsApp Image 2022-05-30 at 10 07 44 PM](https://user-images.githubusercontent.com/106587222/171137631-5a34c6ce-01de-44a2-a772-059010691756.jpeg)
> 
> how to fix this ? win7

**Comment by Autinhorse** [comment]
Jun 15 2022, version 2.6.1 on windows 10, same problem
