### ISSUE TITLE
2.4.1 > Split Clip > mouse drag to point on displayed time line causes severe memory leak

### ISSUE THREAD

**Issue by LtFarns** [OpenShot/openshot-qt#1245]
Greetings all, really impressed by the potential open shot seems to have and the opportunities as a content provider it has offered me. 
I have had great success editing footage in previous builds so i am here to contribute and help as best i can. Please note I actually QA software for a living so am here to help identify and rule out defects as best I can.

It would seem the above captioned steps mentioned in subject line are causing severe memory leak on my local instance. Perhaps it is due to conflict with main timeline Vid Preview and that of Split clip vid preview?

![memleak](https://user-images.githubusercontent.com/36059394/35713378-a4cf1fda-078c-11e8-8612-62300a969261.jpg)

**Comment by LtFarns** [comment]
At first glance it appears that video preview is trying to re calibrate in real time with each left click release of mouse on time line. Perhaps a better solution would be to kill vid preview once timeline movement is initiated and force user to click re generate preview once user releases on new position of timeline. btw Working on a machine w. 16 gb ddr4 . atm. 
![timeline preview](https://user-images.githubusercontent.com/36059394/35714264-4a3a1e1c-0791-11e8-90c3-f3ea0c371fea.jpg)

**Comment by DylanC** [comment]
@LtFarns - Thanks for the report. We do need more people who can log detailed tickets here.
