### ISSUE TITLE
60fps causes audio fade out effect to happen early in exported video.

### ISSUE THREAD

**Issue by KingPopinLockin** [OpenShot/openshot-qt#1246]
**System Details:** Pentium(R) Dual-Core, 4 GB RAM, 64 bit.
* Operating System / Distro: Windows 7
* OpenShot Version: 2.4.1

**Issue Description and steps to reproduce:** When Previewing my video it will play exactly how I intend it to but when I export it in 60fps (doesn't matter the resolution) the audio does something a little weird.  I have the music volume set to "fade slowly" at the end of the video but and works fine during preview at 720p 30fps.  When exported into a video of any resolution but at 60fps the audio will fade entirely to early.  The video's total length is only about 8.5 seconds long. (intended to be the intro to youtube videos) the audio is set to start fading at about 6 seconds and fade over two seconds but after being exported the video will play the audio for about 3 or 4 seconds before it fades away.

I couldn't find anyone talking about this issue being specifically linked to the exported video being 60fps.  If anyone knows a fix to this I would be very grateful to know what it is.  I will be testing a few things to see if I can find a work around or solution until then.

EDIT: 59/50fps also has this issue and the effect to fade the image will also happen early.   I have also  noticed that the video file will not have a thumbnail and will instead have a black/blank thumbnail until the fps is at least as low as 50fps in which it will have a thumbnail but all other problems still occur.

**Comment by peanutbutterandcrackers** [comment]
I wonder if you start the project itself in 60fps, apply all the transitions and other editing that you are talking about, and render it, it'll render right...

It must have something to do with the profile that you are editing in. Editing in 30fps and exporting in 60... I'd expect everything to go twice as fast.

**Comment by KingPopinLockin** [comment]
You may be right about that, I have a very crappy laptop, takes all night
to render a 20 minute video at 60 fps but this problem was to consistent
and was the only problem.  Next time I'll try your idea and see if that
works.  I've been simply doing 30 fps videos since this started but would
really like that 60 haha.

On Feb 14, 2018 3:51 AM, "peanutbutterandcrackers" <notifications@github.com>
wrote:

I wonder if you start the project itself in 60fps, apply all the
transitions and other editing that you are talking about, and render it,
it'll render right...

It must have something to do with the profile that you are editing in.
Editing in 30fps and exporting in 60... I'd expect everything to go twice
as fast.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/OpenShot/openshot-qt/issues/1246#issuecomment-365551265>,
or mute the thread

**Comment by peanutbutterandcrackers** [comment]
I think you shoukd also note that if your camera shoots at 24/30fps, rendering in 60fps won't give a good result. Please try using footage from a camera that actually shoots at 60fps. Hope that helps! :)
