### ISSUE TITLE
100% CPU when Scrubbing

### ISSUE THREAD

**Issue by DeltaBravo** [OpenShot/openshot-qt#1247]
Arch Linux: up to date
OpenShot: 2.4.1

Clean profile (removed ~/.openshot; dismiss tutorial)
Import file (610MiB MP4 created with AMD Re Live)

Split Clip: Click "Start", drag slider near middle of clip, 3 core CPU all cores 100% for 46 seconds
OR
Drag clip onto track: Drag play head anywhere in clip; 3 core CPU all cores 100% for 34 seconds

Please do not hesitate to ask for more information. I am not a developer so I have no clue about what info is relevant so I am being brief to start.

**Edit:** [Issue 1245](https://github.com/OpenShot/openshot-qt/issues/1245) seems to be very similar however I am not seeing excessive memory use--only CPU.

**Edit:** when launching openshot-qt from the console I also see the following when I begin to drag the play head:

    preview_thread:INFO previewFrame: 39  
    preview_thread:INFO self.player.Position(): 39  
    [swscaler @ 0x7fb194462be0] Warning: data is not aligned! This can lead to a speed loss

**Comment by DeltaBravo** [comment]
The specific packages my OS shows as dependencies of OpenShot:

- confuse-3.2.1-1
- dvgrab-3.5-7
- enca-1.19-1
- jsoncpp-1.8.4-2
- libebur128-1.2.4-1
- libftdi-1.4-1
- libopenshot-0.1.9-5
- libquicktime-1.2.4-17
- libusb-compat-0.1.5-1
- libxxf86dga-1.1.4-1
- lirc-1:0.9.4.d-1
- mlt-6.6.0-3
- mlt-python-bindings-6.6.0-3
- mplayer-38017-1
- python-httplib2-0.10.3-1
- python-pyzmq-16.0.3-1
- python2-xdg-0.25-4
- recode-3.6-10
- sox-14.4.2-2
- xf86dgaproto-2.1-3
- openshot-2.4.1-1

**Comment by DylanC** [comment]
@DeltaBravo - Have you tried a daily build at all?

**Comment by agrapsas** [comment]
This is happening to me with whatever version is packaged with Ubuntu 18.04. Very annoying. Let me know if there's anything I can output to help debug/resolve.

**Comment by DeltaBravo** [comment]
@DylanC Sorry for not responding to this issue--I simply have not taken the time to grab the latest build and report back. I will eventually do so although I'm not sure what value it will be by such a time...

@agrapsas Please include what specific version of OpenShot you are using. This information may be under "Help > About..." in the menu inside OpenShot.

**Comment by peanutbutterandcrackers** [comment]
@agrapsas - [Here](http://openshot.org/ppa) is the daily PPA, if you want to switch to it, rather than just using AppImages. But then again, I'm not sure if it works with 18.04. OpenShot v2.4.2 should be out anytime now. Perhaps the Ubuntu Maintainers will tweak the latest version to make it work even better with the distro? Maybe?

**Comment by DeltaBravo** [comment]
Sorry for not responding earlier. At the time of your last comment my distro had not yet updated. Once it had there was no significant change in performance and I did not get around to reporting that here.

Perhaps it is the particulars of the video files I am trying to edit or perhaps it is my specific combination of hardware. Regardless, OpenShot is completely unusable for me which is frustrating of course.

**Comment by DylanC** [comment]
@DeltaBravo - No problem, everyone has a different experience with OpenShot performance. It relates to many factors such as your PC hardware, video/audio formats and the way OpenShot was packaged. 

From my own experience I reported this: #1919. Seems the AppImage doesn't work very well on my own system but the version I've built from source code OpenShot runs great.
