### ISSUE TITLE
Is there anything like proxies or so in openshot because openshot crashes everytime while i am editing 4k video (i'm not using the fastest and newest computer ;-)

### ISSUE THREAD

**Issue by coenboy** [OpenShot/openshot-qt#1248]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

**Comment by DylanC** [comment]
@coenboy - Nope, sounds like your machine may not be strong enough.

**Comment by peanutbutterandcrackers** [comment]
While there are no proxies in Openshot, this video might help you. It's a work around. Hope it works.

https://www.youtube.com/watch?v=aci-ViWAEqs

**Comment by ser** [comment]
@peanutbutterandcrackers - are there any negative sides of artificially lowering the project resolution?

**Comment by peanutbutterandcrackers** [comment]
@ser - I wouldn't think so, No. Not as far as I understand. OpenShot doesn't really modify the video files themselves, and when exporting, one would just choose the required profile so that should work as well. OpenShot is pretty non-destructive. Hope that helps.
