### ISSUE TITLE
Editing issue

### ISSUE THREAD

**Issue by zzcolby27** [OpenShot/openshot-qt#1249]
**System Details:**
* Operating System / Distro: Windows 10
* OpenShot Version: 2.4.1

**Issue Description and steps to reproduce:**
This is just a general issue with the software.
Could you please make it so that when you crop something, you only crop something on that one track?I'm wanting to make an intro with music in one track and clips in the other, and when I crop the clips, I crop the music too. I even tried locking the track, but that didn't work. I have Vegas, but that thing is so unstable, that when I import ANY mp4, it crashes. So i'm using openshot. Also, could you add a dedicated mute track button? That'd be nice. Otherwise, great software.

**Comment by N3WWN** [comment]
Are you talking about cutting the video in a clip without touching the audio?  If that's the case, perhaps you can try splitting the audio into its own track(s) by selecting the clip in the timeline, right clicking and selecting `Separate Audio` and either `Single Clip (all channels)` or `Multiple Clips (each channel)`.

Track volume/muting has been requested elsewhere and, I believe is marked to be implemented as a future feature, but I can't find it right now.  Can you confirm, @DylanC ?

**Comment by DylanC** [comment]
@N3WWN - We have a ticket here for it: #784

**Comment by zzcolby27** [comment]
Sorry guys. Nvm, I was being an idiot and didn't know that right clicking the specific clip would let you do that. I was clicking slice all. Oops.

**Comment by DylanC** [comment]
@zzcolby27 - No problem. Closing this as resolved now. Thanks for getting back to us.
