### ISSUE TITLE
Application asked to terminate in an unusual way

### ISSUE THREAD

**Issue by Mkalfus** [OpenShot/openshot-qt#1250]
**System Details:**Win 7 pro
* Operating System / Distro: ?
* OpenShot Version: ?latest
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
simply opening the program. I had edited a file and tried to save as the same file name. program will not load with out error mentioned above. Tried rebooting and reloading. No joy.

**Comment by peanutbutterandcrackers** [comment]
Perhaps also try uninstalling and reinstlling the program to see if that works?

**Comment by peanutbutterandcrackers** [comment]
Also:

> Like I was just pointing out to someone else:

> Issues like these do not happen on my linux machines. It seems that there are a lot of windows-specific bugs in openshot. Because of lack of developers esp to look after windows versions, the project is falling behind. But I think that once he has the time, Mr. Jonathan Thomas - our one and only developer for now - will hopefully get around to solving these issues. Sorry for the inconvienience...

**Comment by peanutbutterandcrackers** [comment]
Also:

> Like I was just pointing out to someone else:

> Issues like these do not happen on my linux machines. It seems that there are a lot of windows-specific bugs in openshot. Because of lack of developers esp to look after windows versions, the project is falling behind. But I think that once he has the time, Mr. Jonathan Thomas - our one and only developer for now - will hopefully get around to solving these issues. Sorry for the inconvienience...

**Comment by DylanC** [comment]
@Mkalfus - Perhaps try out a daily build. They seem to work better on Windows than v2.4.1.

**Comment by Mkalfus** [comment]
All is working correctly now…. Had an issue with a windows update.

 

Michael Kalfus

System Administrator

The Mayfield Group.

**Comment by peanutbutterandcrackers** [comment]
Great!

Closing this as resolved, then.
