### ISSUE TITLE
Giant screen with update 2.4.1

### ISSUE THREAD

**Issue by mnwstl** [OpenShot/openshot-qt#1253]
**System Details:**
* Operating System / Distro: ubuntu 18.04 - 64 bits
* OpenShot Version: 2.4.1

The system upgraded to version 2.4.1, but the image was too large. What can I do? Do I have a way back to the theme of the previous version? My resolution is 1360 x 768.
![2018-02-06_11-33-06](https://user-images.githubusercontent.com/22776404/35862221-0f739d90-0b32-11e8-920a-e0806871d0d1.png)

**Comment by DylanC** [comment]
@mnwstl - May be a problem with 18.04. I haven't seen this happen on Ubuntu 17.10. I can test this and get back to you.

**Comment by mnwstl** [comment]
Hi! I did some research that indicated problems between the Qt and the resolution of the Monitor. I was using the HDMI input and then switched to the D-SUB input to PC and went back to normal. Everything indicates that the Qt (do not understand programming) does not recognize the monitor correctly.

**Comment by DylanC** [comment]
@mnwstl - Ah very good. I was getting around to this soon but you have saved me the time. What resolution is the monitor? 1080p?

**Comment by mnwstl** [comment]
The manual says to be a monitor-TV 1360 x 768 @ 60hz - 720p. It's HD, but not full HD.

**Comment by DylanC** [comment]
@mnwstl - Thanks, I'll give my own laptop a test on this resolution.

**Comment by DylanC** [comment]
@mnwstl - I can't seem to produce this issue on my monitors. Does anyone have a similar monitor to test this?

**Comment by mnwstl** [comment]
I have another monitor, however it is distant, in another state and I have no way to test. What I have here is a Samsung 26  "LN26B450C4MXZD. I liked the theme with the fine time lines of the previous version, however in this new version no longer exists.

**Comment by mnwstl** [comment]
It is noticed that it improved a lot with the new version, however I liked more of the theme "blue flat slim" which allowed a better use of the screen.

I noticed that the translation to the Portuguese is not correct. It seems to confuse Portuguese from Portugal (pt) with Portuguese from Brazil (Pt_BR).

![2018-07-05_21-59](https://user-images.githubusercontent.com/22776404/42355358-0f31e828-80a3-11e8-8176-1fec85ea03ac.png)

**Comment by peanutbutterandcrackers** [comment]
@mnwstl - Is the language issue related to [this issue](https://github.com/OpenShot/openshot-qt/issues/1793), good sir? Also, please excuse my ignorance, but what is "blue flat slim" theme? Can I have a link please? How does OpenShot look with that theme?

**Comment by DylanC** [comment]
@mnwstl Please follow the progress of that bug here in #1793. I think this seems to be resolved, so I'm gonna close this one out.

**Comment by mnwstl** [comment]
@peanutbutterandcrackers This theme was part of the OpenShot 1.4.3. The tracks were thinner and by default started with two.
![2018-07-09_14-42-59](https://user-images.githubusercontent.com/22776404/42458269-ef573bd2-836f-11e8-9043-d0a074ffbce6.png)

**Comment by peanutbutterandcrackers** [comment]
Oooh! Cool! Perhaps we should get this too! Could you please open a separate issue requesting this theme too? Although, it won't really be in the priority, though. Tons of crashes going on for our windows users. :/
