### ISSUE TITLE
Bottom of the video is missing in the video preview pane after rotating 90° and setting a vertical video profile (export file is OK)

### ISSUE THREAD

**Issue by JohanG77** [OpenShot/openshot-qt#1259]
# Preliminary words
First of all, I would like to say Openshot Video Editor is a great software, despite it is very slow on Windows 10 x64 (issues already created by other users for that so not talking about that in this issue).

# System Details
Operating System / Distro: Windows 10
OpenShot Version: 2.4.1
# Steps to reproduce

1. Start a new project
2. Import a video file
3. Drag and drop the file into a track
4. Right-click on the video sequence in the track and choose Transform -> Rotate 90°
5. Change the video profile to a vertical profile (attached one to accelerate the investigation)
[Johan vertical 1080x1920.txt](https://github.com/OpenShot/openshot-qt/files/1708202/Johan.vertical.1080x1920.txt)
# Observed result
All along the video the bottom of the picture is not visible in the video preview pane, even if we resize the video preview pane (that's a pain especially since the useful information in my video is at the bottom of the picture).
However, in the exported file, the bottom is not missing. This is the reason why I don't rank this issue as a critical bug, still it is a rather big one.
# Expected result
All the picture is visible in the video preview pane.

**Comment by peanutbutterandcrackers** [comment]
@DylanC - I had similar issue with a video I was editing for a friend. So, this is probably a bug. At least, his rendered video was OK; mine wasn't. I had to use ffmpeg to change the video orientation before editing the footage.

Just confirming this. :)

**Comment by peanutbutterandcrackers** [comment]
@JohanG77 - This is a really good quality issue report. Thanks for being so clear.

**Comment by DylanC** [comment]
@peanutbutterandcrackers - Yes, I have come across this too. Thanks!  @JohanG77 - Great quality report. Excellent!

**Comment by sknaumov** [comment]
@JohanG77 @DylanC Does it still work for you in Openshot 2.4.4? When I'm trying standard 1920x1080 profile, my video ends up cropped vertically and looks square. When I'm trying to use this custom profile, video is not cropped, but has huge black shoulders not only from left and right, but also from above and below - so it looks correct, but heavily zoomed-out.

**Comment by ferdnyc** [comment]
This should now be fixed with the merge of #2975, with thanks to @SuslikV . The preview video parameters weren't being completely set up when initially loading a profile.
