### ISSUE TITLE
python errors - Cx_freeze at launch

### ISSUE THREAD

**Issue by JATS99** [OpenShot/openshot-qt#1261]
**System Details:**
* Operating System / Distro: Windows
* OpenShot Version: latest
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**  I get Python errors and the product won't open.  Can you please help?  I have uninstalled and reinstalled several times, and still get the same error messages.

<img width="570" alt="openshot troubleshoot" src="https://user-images.githubusercontent.com/36282254/36001529-2269533e-0cec-11e8-9fab-a9deb4492cd7.PNG">

**Comment by JATS99** [comment]
I have uninstalled and reinstalled but issue remains.  Can you please help?

**Comment by mikeink94** [comment]
I've posted the same issue as well and a quick response to this topic or mine would be highly appreciated. Inability to use this program is a serious issue and the frustration makes me unable to support this program and recommend it to anyone

**Comment by peanutbutterandcrackers** [comment]
Hey there! 

It has been reported that this issue affects only certain users in the computer, and thus, it is a user-related issue. Some report that the admin could run OpenShot while the standard user could not, and vice-versa. 

A user recently reported that he [resolved](https://github.com/OpenShot/openshot-qt/issues/1244#issuecomment-365036861) this issue by copying openshot.settings file from the standard user (or whichever user can use OpenShot in your windows machine) to the admin user (or whichever user can NOT use OpenShot). He also recommends having a backup made of the openshot.settings file.

Please note that the solution is edited in at the very end of the comment.

Hope this helps. :)
All the very best!

**Comment by DylanC** [comment]
Closing this question as answered.

**Comment by peanutbutterandcrackers** [comment]
Please do look forward to v2.4.2. This issue has been put on the list of the 'critical bugs to be fixed' for the release. OpenShot should finally work quite well on Windows Machines with v2.4.2. Please, do however continue to support OpenShot. Perhaps test the latest [daily build](https://github.com/OpenShot/openshot-qt/releases/tag/daily) if you have the time and report the issues as you encounter them. Thanks!
