### ISSUE TITLE
Documentation tables don't wrap

### ISSUE THREAD

**Issue by ferdnyc** [OpenShot/openshot-qt#1262]
The Sphinx formatting for the [online documentation](http://www.openshot.org/files/user-guide/) makes heavy use of ReStructuredText tables, which unfortunately do not use wrapping on internal text. This means that when the documentation is browsed in a narrower view, the tables have to be scrolled horizontally to view their contents.

After a fair bit of experimentation with the possibilities for RST formatting, I found that converting the images to figures with a caption and definition list was probably the best option for layout. (I tried both a custom-titled admonition and a sidebar, but neither really worked out the way I'd hope.)

I'm not thrilled with the result myself, to be perfectly honest, but ReStructuredText doesn't give a lot of formatting options. (I have to wonder if wholesale conversion to MarkDown might not work out better, but for now I worked within the flexibility of the existing RST format.) Ultimately I felt that it was "better than before", which is probably the best I can hope for.

Making that change, this:

![screenshot from 2018-02-08 17-33-25](https://user-images.githubusercontent.com/538020/36002508-6d7b8ebc-0cf8-11e8-90aa-c6228042687d.png)

becomes this:

![screenshot from 2018-02-08 17-33-37](https://user-images.githubusercontent.com/538020/36002518-74b6efd2-0cf8-11e8-86e6-789e4711cf6b.png)

I'm happy to update all of the documentation files, convert all of the image legends, and submit a PR. But I wouldn't want to go through all of that without getting buy-in that it's something desirable that would be accepted, so I thought I'd raise this here first. Further discussion of the exact formatting is eagerly encouraged.

(There's also the issue of the non-legend tables, but for now I'm leaving that aside. Perhaps the same solution would work for them.)

**Comment by DylanC** [comment]
@ferdnyc - Looks good to me. What do you think @jonoomph ?

**Comment by ferdnyc** [comment]
BTW, the caption ("_Figure: Animation.1_") seen in the second screenshot is both completely free-form and optional. I threw it in because I figured it might be useful to refer to the figures by name from the body text, at some point. I was also hoping to come up with a format for the legend that explicitly labeled it as corresponding to the named figure, but failed in that goal.

I chose the "Chaptername.#" format simply because the chapters aren't currently numbered, and I figured this was simpler than imposing a numbering that would have to be manually adjusted whenever chapters are added, removed, or reordered.

**Comment by peanutbutterandcrackers** [comment]
@ferdnyc Is it possible to wrap the tables? Table style looks a lot more friendlier than the numbering style, IMHO... Nevertheless, I really appreciate your efforts to make this project even better. 👍 

Thank you for your help to the project, though. I'm always glad to see people lend helping hands to my favourite Video Editor. :)

**Comment by ferdnyc** [comment]
Aha. It _appears_ this may actually be a (well-known) issue / design-choice in the "Read The Docs" Sphinx theme: rtfd/sphinx_rtd_theme#117

I gather that it should be possible to get the tables to wrap with proper CSS adjustments. I'm still digging through the info there (which sure does range a bit) to work out the right way to address this. But, in general I agree, getting the tables to wrap would be preferable.

I was originally working off the reStructuredText docs, which basically contain no discussion of wrapping _at all_, because all of that is handled by the formatter (Sphinx). Now that I've looked more into Sphinx, and found the info above, it sounds like wrapping the tables should be possible. (With the possible caveat — and the reason it's not the default, I gather — being that it can cause less-than-ideal formatting on mobile devices.)

Anyway I'll report back after some more reading/testing.

**Comment by ferdnyc** [comment]
I think I've got it. Some screenshots at various window widths, from locally-built docs. (I reverted my edits to `animation.rst`. This is the checked-in documentation source, with adjustments to the Sphinx build config to add some additional CSS directives.)

![screenshot from 2018-02-09 23-48-36](https://user-images.githubusercontent.com/538020/36058643-207fa39e-0df4-11e8-898b-2e1dd638ed29.png)

![screenshot from 2018-02-09 23-48-22](https://user-images.githubusercontent.com/538020/36058644-25685b94-0df4-11e8-89ed-9f2f0cedffa8.png)

![screenshot from 2018-02-09 23-48-06](https://user-images.githubusercontent.com/538020/36058646-299fa74e-0df4-11e8-9327-4b90bd48ef82.png)

![screenshot from 2018-02-09 23-48-57](https://user-images.githubusercontent.com/538020/36058647-2c64bc6c-0df4-11e8-81eb-5cb095a6cabd.png)

(Hmmm. I should've captured those all with the same image width, so it'd be clearer. Sorry!  You get the idea.)

I'll put together a PR for this fix... at some point over the weekend, but not tonight.

**Comment by peanutbutterandcrackers** [comment]
@ferdnyc - Awesome!!! Please do! I'm so glad that you've fixed this issue. You're awesome. 👍 

I hope you stick around and help this project even more. Thank you for your efforts, good sir. :)

**Comment by peanutbutterandcrackers** [comment]
@DylanC - Pretty sure @jonoomph would be really happy to see this progress. :)

**Comment by DylanC** [comment]
@ferdnyc - Thanks, this is looking awesome indeed!

**Comment by DylanC** [comment]
@ferdnyc - Are we good to close this now?

**Comment by ferdnyc** [comment]
I was debating that myself... the code in the _repo_ has changed, but the old version of the manual is still deployed at https://www.openshot.org/user-guide/ so effectively the changes aren't visible to anyone.

It'd be nice to get the online copy of the docs re-generated to incorporate this fix (and whatever other changes have been made in the interim), since right now the issue with non-wrapped tables is still the case unless you generate your own private copy of the manual.

**Comment by DylanC** [comment]
@ferdnyc - Ah. I see. I'll check with the guys to see can we deploy a new version. Thanks.

**Comment by peanutbutterandcrackers** [comment]
I think the new version has been deployed: https://www.openshot.org/static/files/user-guide/clips.html#properties Yay!!! :smile: :+1: 

Great job, @ferdnyc !!!

**Comment by ferdnyc** [comment]
Indeed, updated to the 2.4 series, with all applicable enhancements. That should also close at least #724, looks like.

**Comment by DylanC** [comment]
@ferdnyc - Perfect, thanks!

**Comment by sahitir** [comment]
Hi, I face this problem too. I have an rst file with all the tables with columns having the lengthiest widths as long as the largest text (as a straight line). Could you please tell me how the CSS directive can be used to wrap the text? Thanks in advance.

**Comment by ferdnyc** [comment]
@sahitir 

Sure, those fixes are in this file:
 https://github.com/OpenShot/openshot-qt/blob/develop/doc/css/tablefix.css

https://github.com/OpenShot/openshot-qt/blob/5143e0f2f15cb530936a48c5cdf695fa4762dbfe/doc/css/tablefix.css#L1-L14

**Comment by sahitir** [comment]
@ferdnyc Thank you! Let me see how I can make use of this.

**Comment by ferdnyc** [comment]
@sahitir It's been a couple of years, but as I recall other than adding those styles, the only other adjustment I made was to explicitly set some column widths on the tables (usually all but the final one).

**Comment by ferdnyc** [comment]
Yeah ­— see, for example, all the tables in https://github.com/OpenShot/openshot-qt/blob/develop/doc/files.rst . Except for one that didn't need any adjustment, I set explicit widths for the left columns to define the width I wanted them to have, and then let the last column fill the rest of the space. My commit message on 901f9835 reads:

> ### Manually specify some table column widths
> Turning on wrapping in the theme leaves decisions on column widths
> up to the Sphinx formatter. It does an OK job sometimes, other times
> the tables are imbalanced.
> 
> Column widths can be manually specified by using the explicit
> `.. table:` directive, using its `:widths:` option.
> 
> (Table code itself is the same, but has to be nested inside the
> `.. table:` directive, requiring the entire table block be
> indented five spaces. Not ideal, but it's what works.)
> 
> Width syntax is... complex. If specified for all columns out of
> 100, then they appear to effectively be percentages. Widths can
> be left out for some columns (on the right of the table), and
> they will be defaulted. But that computation involves some sort
> of Sphinx magic.
> 
> If we have a three-column table, `:widths: 5 25` (with the third
> column unspecified) will _not_ be laid out the same as
> `:widths: 5 25 70`.
> 
> I've allowed Sphinx to default column widths where possible, but
> when things got weird or unpredictable I specified explicit widths
> for all columns.
> 
>

**Comment by ferdnyc** [comment]
> indented five spaces.

That should be "indented _three_ spaces", though. A later commit fixed the indentation.

**Comment by ferdnyc** [comment]
See also the PR that included that original commit, #1272, where I go into quite a bit more detail about table-wrapping (with screenshots).
