### ISSUE TITLE
Crash after fade out effect

### ISSUE THREAD

**Issue by Bennerdoodle** [OpenShot/openshot-qt#1263]
**System Details:**
* Operating System / Distro: Windows 10
* OpenShot Version: 2.4.1
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

While making a credits scene for my video, I wanted the text of the names to fade in and out. Fade in works fine but whenever a frame gets to its "fade out" time the whole program freezes and then crashes. Even if its a completely separate project,

**Comment by peanutbutterandcrackers** [comment]
Like I was just pointing out to someone else:

> Issues like these do not happen on my linux machines. It seems that there are a lot of windows-specific bugs in openshot. Because of lack of developers esp to look after windows versions, the project is falling behind. But I think that once he has the time, Mr. Jonathan Thomas - our one and only developer for now - will hopefully get around to solving these issues. Sorry for the inconvienience...

Coud you perhaps try setting 'alpha' keyframes manually? (You might have to look up 'openshot keyframes' on YouTube...

**Comment by DylanC** [comment]
@Bennerdoodle Can you try v2.4.2 and let us know if you have any success?
