### ISSUE TITLE
tutorial window flickers at opening

### ISSUE THREAD

**Issue by DiggerD** [OpenShot/openshot-qt#1264]
I have filed very few bug reports, so I'll try to be as professional as possibe.
**System Details:**
what exactly do you want here? 

* Operating System / Distro: 
Linux Mint 18.3

* OpenShot Version:  
2.4.1-dev1

**Issue Description and steps to reproduce:**
When I start OpenShot the tutorial screen flickers constantly as does the text inside the top bar of the GUI and the tiny window that represents openshot inside the workspace switcher in the XFCE panel. 

I can add items to a project, open a project, save a project but inevitably the flickering comes back. It is sometimes suppressed by browsing through menu items but it then comes back again. Navigating the menu causes it to temporarily disappear. There are many other odd things with this bug..when I quit, the flickering tutorial window dissapears but the GUI is still there. When I quit again, it shuts down. 

I have just installed it before this problem happened. 
I rebooted the computer to see if that would clean it up. 

Thanks

**Comment by peanutbutterandcrackers** [comment]
Similar problem happens to me too, at times. The way I deal with it is that I simply close the tutorial window. Often, it does not close at once. Takes many clicks. And seems like it's frozen. But if I am patient with it, it does go away.

It seems we need someone with a good knowledge o PyQT framework to come and fix it for us. Mr. Thomas, who is our only active developer, has a lot of work that he has to do all by himself. And I'm not sure when he can get back to this issue (there are so many others).

If you could fix it, please do. The community would be very grateful.

**Comment by peanutbutterandcrackers** [comment]
Plus, once you've gone through all the tutorials in the tutorial window, it doesn't come up on every restart of the program. I'm also almost sure that there is a way to disable the tutorial window manually.

**Comment by imdanix007** [comment]
edit the configuration file at ~/.openshot_qt/openshot.settings. search for Tutorial_Enabled and change value="".

**Comment by Q-pah** [comment]
To be more specific,
editing ~/.openshot_qt/openshot.settings I actually had to change
{**_"value": true_**, "title": "", "type": "hidden", "category": "Tutorial", "se    tting": "tutorial_enabled"}
to this:
{**_"value": ""_**, "title": "", "type": "hidden", "category": "Tutorial", "se    tting": "tutorial_enabled"}

**Comment by peanutbutterandcrackers** [comment]
Hey there, a fix to this issue was just merged into the source tree and is ready for testing. Could you please try out the [latest daily builds](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914) and see if this has been resolved? Thanks!

**Comment by peanutbutterandcrackers** [comment]
Hey there! Could you all please try [this build](https://drive.google.com/open?id=1n5_joUIWr4FI7daLaCj7WwFUk-sXsVKN) that incorporates the changes from the PR by @ferdnyc? This issue has, hopefully, been resolved. And if you give confirm it as resolved, we can go ahead and merge the changes into the main source. Thanks!

**Comment by ferdnyc** [comment]
@peanutbutterandcrackers : please close as dup of... some other Tutorial-problems bug. We'll have to choose the one with the most data about the problem to consolidate on.

**Comment by peanutbutterandcrackers** [comment]
Closing as dup of #1708 (even though this was reported earlier, because of lack of interest here and the discussions there); fix in progress, should be resolved in the next release.
