### ISSUE TITLE
Samsung 7 Recorded Videos Won't Play

### ISSUE THREAD

**Issue by jkreski** [OpenShot/openshot-qt#1265]
**System Details:**
* Operating System / Distro: ?  Windows 10 Tower PC, was fine untill recently
* OpenShot Version: ?  2.4.1
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

The video is an MP4 video as recorded on my cell phone camera.  Wondering - is it the wrong type?
The program has become very slow to start.  I can import the video.  I can drag and drop it onto the track - Track 4 is on  top and so I just use that one.  I have played around with the Profiles and have selected the Mobile on assuming it would be the least resource intense and OK for debugging.  The opening frame shows-up on the Video Preview.  However, now, pressing PLAY  does not play the video - or if it does it takes quite some time for the video to play.  Quality seems otherwise fine.  I also noted in VLC  Media Player that I needed to select SLOWER for the videos to render correctly.

My application is personal videos to be distributed to family and to upload to social media like YouTube, Facebook, etc..  I had done several using old videos from a large VCR tape sized cam corder - the original ones - and were transferred to CD.  From there I was able to edit them here and distribute.  No music, etc..  No copyright issues, actually.

How can I start to de-bug this issue?

**Comment by rkg2137** [comment]
I'm having the same issue with video from my Parrot Bebop 2 drone as well 1080p at 30fps. 

I used a software called handshake (free) and converted one of my video clips from the above format to 720p and 30fps and it worked fine however; the video file size went from 88MB down to 7MB and has lost a great deal of its quality.

**Comment by DylanC** [comment]
@peanutbutterandcrackers - Yes, stuff like this happens lots on Windows. Running just fine for me on Ubuntu 17.10. I guess testing more with 1080p on Windows should produce some results to investigate.

**Comment by peanutbutterandcrackers** [comment]
@DylanC - I'm more concerned about producing more volunteer programmers for OpenShot, though. 😄

**Comment by DylanC** [comment]
@peanutbutterandcrackers - Yes, that would be much better! :D

**Comment by N3WWN** [comment]
@rkg2137 HandBrake has different profiles which dramatically affect the output quality.  I have used HandBrake in the past to convert video so that is able to be opened (or more easily edited) in various video editors without a loss in quality by selecting the appropriate profile.

**Comment by DylanC** [comment]
@jkreski - Do you have a sample video you can provide us?
