### ISSUE TITLE
Cx_freeze at launch

### ISSUE THREAD

**Issue by bartschoneveld** [OpenShot/openshot-qt#1266]
Windows 10
Intel Core I5-431U 2.00 GHz 2.60 GHz
Ram 8,00 GB
64-bit

Open Shot OpenShot-v2.4.1-x86_64
![snapshot open shot](https://user-images.githubusercontent.com/9466558/36028891-24a6b636-0da1-11e8-8b6b-6a5581a728cd.png)

Uninstalled with revo uninstaller and re-installed but I keep the problem, worked always fine

What can I do?

**Comment by peanutbutterandcrackers** [comment]
@bartschoneveld - Hey, could you give [this](https://github.com/OpenShot/openshot-qt/issues/1244#issuecomment-364742348) solution a try? More of a work-around though. But still...

**Comment by peanutbutterandcrackers** [comment]
Hey there! 

It has been reported that this issue affects only certain users in the computer, and thus, it is a user-related issue. Some report that the admin could run OpenShot while the standard user could not, and vice-versa. 

A user recently reported that he [resolved](https://github.com/OpenShot/openshot-qt/issues/1244#issuecomment-365036861) this issue by copying openshot.settings file from the standard user (or whichever user can use OpenShot in your windows machine) to the admin user (or whichever user can NOT use OpenShot). He also recommends having a backup made of the openshot.settings file.

Please note that the solution is edited in at the very end of the comment.

Hope this helps. :)
All the very best!

**Comment by DylanC** [comment]
Closing this question as answered.

**Comment by peanutbutterandcrackers** [comment]
Please do look forward to v2.4.2. This issue has been put on the list of the 'critical bugs to be fixed' for the release. OpenShot should finally work quite well on Windows Machines with v2.4.2. Please, do however continue to support OpenShot. Perhaps test the latest [daily build](https://github.com/OpenShot/openshot-qt/releases/tag/daily) if you have the time and report the issues as you encounter them. Thanks!
