### ISSUE TITLE
How do I shoot videos with my webcam. Everything I see in the manual is about editing.

### ISSUE THREAD

**Issue by jasper1969** [OpenShot/openshot-qt#1268]
**System Details:**
* Operating System / linux mint
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

**Comment by peanutbutterandcrackers** [comment]
I'm afraid the feature has not yet been added to OpenShot. Perhpas you might want to try another capture program (like cheese: $ sudo apt install cheese) and import the video into openshot?

**Comment by peanutbutterandcrackers** [comment]
Please do not forget to close the issue if it has been resolved, too. Thanks. :)

**Comment by jasper1969** [comment]
Thanks for the suggestion. Perhaps your description should not include 
that wording until it's functional.

**Comment by jasper1969** [comment]
cheese works, thanks again for the assistance.
