### ISSUE TITLE
Youtube Poop Features?

### ISSUE THREAD

**Issue by zzcolby27** [OpenShot/openshot-qt#1269]
**System Details:**
* Operating System / Distro: Windows 10
* OpenShot Version: 2.4.1
* _Please attach log files if crash_

Sorry about that last question, I was being a dumbass. Anywho, will you add more "youtube poop" friendly features? Your program is amazing is has worked much better then Vegas when it comes to editing (at least for me.) I was wondering if you'll add more features that could make it easier to make a ytp in your program? Things like a easier to use interface for complex features, more effects, a specific mute button on the tracks, etc? Thanks for reading.

**Comment by peanutbutterandcrackers** [comment]
@zzcolby27 - Yes, actually. Mr. Thomas (the founder/lead developer) has been committing new features in to OpenShot 2.x. We've got 'Hue', 'Shift', 'Bars', 'Pixelate' among others. And what's more - they're all keyframeable. You can also do chroma keying and stuff. So, yeah. One could actually make YTP with OpenShot. You might want to look up 'Openshot Keyframes' on YouTube for tutorials if you are not sure how to use Keyframes in OpenShot.

Everything is keyframe-able in OpenShot, which I think is what makes it one of the Best Video Editors out there (although it's still a diamond in the rough with regards to stability and all).

You might also want to read the [user guide](https://www.openshot.org/user-guide/) and look at the [official tutorials](https://www.youtube.com/watch?v=1k-ISfd-YBE&list=PLymupH2aoNQNezYzv2lhSwvoyZgLp1Q0T) (they're made by Mr. Thomas himself, BTW).

Also, in his [blog post](http://www.openshotvideo.com/2018/01/happy-new-year-2018.html?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+OpenshotVideoEditor+%28OpenShot+Video+Editor%29), Mr. Thomas has also revealed plans for "an easy plug-in framework to allow others to quickly create video and audio effects" (among other things). Once that is done, I'm pretty sure there will be a plethora of effects for OpenShot out there. So yeah, do keep on supporting OpenShot.

**Comment by peanutbutterandcrackers** [comment]
P. S: You'll probably have to wait for the next stable release before you get those new effects  ['Hue', 'Shift', 'Pixelate'...]. But they're already in the code.

**Comment by DylanC** [comment]
@zzcolby27 - Those features you have asked for are being added in future versions. 

More effects - #713 
Mute whole track #784   

The filters will be there soon, as they are currently adding more to the program.
