### ISSUE TITLE
cx_Freeze: Python error in main script

### ISSUE THREAD

**Issue by mikeink94** [OpenShot/openshot-qt#1270]
Windows 10
Intel Core i5-6200U
8GB Ram

I finished my project and decided to take a break so I closed the program and when I turned it back on to export it I could no longer launch it, I kept getting an error even after restart my computer and uninstalling and reinstalling the program like 30 times. It's extremely frustrating and I need a solution to this as soon as possible. I made this video for a college application and restarting would be more painful than making a brand new video with a new program. I also tried downloading the program on a different computer where it worked but the .osp file I emailed myself wouldn't open on it, it just kept saying failed to launch ______.osp. I need any solution at all and soon please...thank you.

**Comment by mikeink94** [comment]
![screenshot 1](https://user-images.githubusercontent.com/36344231/36067405-a1d51ef6-0e8a-11e8-8a28-be626bf6a759.png)

**Comment by mikeink94** [comment]
Forget it I'm just gonna use another program, using this program was very slow and it froze everytime I moved a track so nevermind even responding. I'll leave this issue open as a warning to anyone else who runs into this issue to save you days of unnecessary anger..just use a better program.

**Comment by peanutbutterandcrackers** [comment]
@mikeink94 - I understand your frustration. It seems that this cx_Freeze error is popping up on many windows computers. But on my Linux machine, OpenShot works just fine. So, I believe it is a windows-specific problem.

It might have to do with the fact that OpenShot is developed by (mostly) a single man, who uses Linux Machine for primary development, in the time that he squirrels away. The project currently lacks volunteer programmers to help with the issues...

I'm sorry for the time that was wasted. I hope someone will soon figure out a way to solve it.

If it is any consolation, the following issues also talk about the same problem:
#1266 #1261 #1244 #1148 #1035 

I'll try to see if I can get my hands on a windows-machine and try to understand the problem further. But I am not that good of a programmer. So, I don't think I'll be able to really solve this issue... Sorry about that, too.

**Comment by osve001** [comment]
FIXED!
Have a look at:
OpenShot 2.4.1 won't open - cx_Freeze Python error in main script #1244

**Comment by peanutbutterandcrackers** [comment]
@mikeink94 - Could you please give @osve001's solution a shot and give your feedback?

**Comment by peanutbutterandcrackers** [comment]
If you're still out there, @mikeink94 , please do give the final (newer) solution at #1244 a shot... It seems like a viable workaround.
