### ISSUE TITLE
os x webm export codec not found

### ISSUE THREAD

**Issue by hannolans** [OpenShot/openshot-qt#1274]
**System Details:**
* OS X 10.13.3
* OpenShot Version: 2,4.1

**Issue Description and steps to reproduce:**
Not able to export as webm due to not existing codec. After this message I installed ffmpeg with brew but no effect. Probably I have to let Openshot know I have ffmpeg installed? 
![schermafbeelding 2018-02-13 om 23 07 50](https://user-images.githubusercontent.com/899399/36176600-70bff6a2-1113-11e8-9369-0719f9dfd6ca.jpg)
![schermafbeelding 2018-02-13 om 23 09 34](https://user-images.githubusercontent.com/899399/36176605-749bfe38-1113-11e8-9d92-bc3072ecb31b.jpg)

**Comment by peanutbutterandcrackers** [comment]
Perhaps uninstall and reinstall Openshot again, now that you have ffmpeg too?

**Comment by hannolans** [comment]
Good suggestion. Uninstalled and reinstalled but no luck so far.

**Comment by peanutbutterandcrackers** [comment]
I wonder if it is really a bug or just an issue specific to your machine... 

I hope we can get some other mac users to test it ans see if it affects them too.

I haven't yet exported to webm yet, to be honest. Perhaps I too ahould test it.....

As a workaround, could you export to another format and ffmpeg it to webm for now? Sorry for the inconvinience.

**Comment by hannolans** [comment]
Yes, I'm wondering as well if it is related to my machine. I can try on another machine. I like to use and promote this for editing media on commons.wikimedia.org as that content is all webm.

**Comment by peanutbutterandcrackers** [comment]
Wow. Thanks for supporting free and open source software. Yes, OpenShot is quite powerful. But it seems it is most powerful on linux. We need more volunteers like you, willing to test it, with a lot of patience, on other platforms. (We also need quite a bit of volunteer programmers to do bug-fixes as well as Mr. Jonathan Thomas is the only programmer we have right now. And also financial supporters, gitHub issue managers, and just generally enthusiastic users who are willing to share the word about this awesome but still a diamond-in-the--rough (on non-Linux platforms) free software :)

Good luck with your project, good sir!

**Comment by peanutbutterandcrackers** [comment]
@DylanC - I checked this issue on my Linux Machine (to see if I was affected, seeing that I'd never exported to webm) - it is not an issue here. Maybe, mac-specific (worst case scenario)?

**Comment by peanutbutterandcrackers** [comment]
"It's a bird!? It's a plane!? It's a bug!!!!!" lol

**Comment by pauloord123** [comment]
Me too and worse: all exports result in a crash (without any message), also installed ffmpeg but no change. If I start Terminal in MacOS with ./launch I see a lot og messages, but the crash seems to come from libavcodec.55.dylib (in app) or 'nearby'.
