### ISSUE TITLE
Program Freezes when I do anything!

### ISSUE THREAD

**Issue by LazyTitan57** [OpenShot/openshot-qt#1275]
Not sure why but as soon as I click on anything the program freezes and sometimes wont come out of it.
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

**Comment by peanutbutterandcrackers** [comment]
You're probably using Windows, aren't you?

**Comment by peanutbutterandcrackers** [comment]
Could you attach the log files and add more details in, please? That will help the developers fix the problems.

**Comment by LucasReSilva** [comment]
I have de same problem here
Windows 10
Ryzen R7 1700

**Comment by DylanC** [comment]
@LazyTitan57 - We need more details here or this will be closed. Thanks.

**Comment by peanutbutterandcrackers** [comment]
I think switching to the daily builds will do the trick, as it has done for many other windows users.

Please head over to the [download](http://openshot.org/download) page, and click on the button that says 'daily builds' and grab the latest one and install it on your machine. This problem has probably been resolved in the daily builds. Hope that helps!
