### ISSUE TITLE
OpenShot crashes in any H.264 AVI compiling setting

### ISSUE THREAD

**Issue by kubota95** [OpenShot/openshot-qt#1278]
**System Details:** Latitude E5570, Core i5-6440HQ @ 2.6 GHz, 16GB RAM, SSD
* Operating System / Distro: Windows 10 Pro x64 / 1709
* OpenShot Version: 2.4.1

**Issue Description and steps to reproduce:**
Compiling video in H.265 AVI results in crash.  Happens in all quality settings and attempted frame rates.  Tried in: default HDV 720 24P, any 720P / 1080i / 1080P / 4K / etc. profiles.  Other profiles seem to work - (though mpeg4 AVI in any tested profile and quality leaves a great portion of the screen darkened on playback - like a shadow that starts at a specific line and position about a quarter way down from the top.)

The video is about 14 minutes long, made from a single jpeg AVI recording with start/finish cuts and one splice, and a fade in / out.  Original recording details on output:

{
    "acodec": "adpcm_ms",
    "audio_bit_rate": 386256,
    "audio_stream_index": 1,
    "audio_timebase": {
        "den": 24141,
        "num": 1024
    },
    "channel_layout": 3,
    "channels": 2,
    "display_ratio": {
        "den": 9,
        "num": 16
    },
    "duration": 1520.199951171875,
    "file_size": "22557589504",
    "fps": {
        "den": 1,
        "num": 25
    },
    "has_audio": true,
    "has_single_image": false,
    "has_video": true,
    "height": 1080,
    "id": "BL60A0DAJC",
    "interlaced_frame": false,
    "media_type": "video",
    "path": "C:\\Users\\XXX\\Desktop\\XXX_jpeg.avi",
    "pixel_format": 13,
    "pixel_ratio": {
        "den": 1,
        "num": 1
    },
    "sample_rate": 48000,
    "top_field_first": true,
    "type": "FFmpegReader",
    "vcodec": "mjpeg",
    "video_bit_rate": 118708535,
    "video_length": "38005",
    "video_stream_index": 0,
    "video_timebase": {
        "den": 25,
        "num": 1
    },
    "width": 1920
}
-----------------------------------------------------
Windows crash log entries:

Faulting application name: launch.exe, version: 0.0.0.0, time stamp: 0x57a98a3e
Faulting module name: ntdll.dll, version: 10.0.16299.248, time stamp: 0xeffc9126
Exception code: 0xc0000374
Fault offset: 0x00000000000f87bb
Faulting process id: 0x38b0
Faulting application start time: 0x01d3a5e25bee3fae
Faulting application path: C:\Program Files\OpenShot Video Editor\launch.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: 850640a2-266d-4c3b-a179-f72f69b47329
Faulting package full name: 
Faulting package-relative application ID: 
------------------------------------------------------

Fault bucket 1459440143923889921, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: launch.exe
P2: 0.0.0.0
P3: 57a98a3e
P4: StackHash_dccc
P5: 10.0.16299.248
P6: effc9126
P7: c0000374
P8: PCH_41_FROM_ntdll+0x00000000000A09D4
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2166.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER29F3.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2A01.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2A50.tmp.txt

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_launch.exe_949beed066c324d5015abc785b23bf86bb66223_8ac0f197_45582d3d

Analysis symbol: 
Rechecking for solution: 0
Report Id: 850640a2-266d-4c3b-a179-f72f69b47329
Report Status: 268435456
Hashed bucket: d03c6dfddd4a84101440f91415874701

OpenShot Log:
[openshot-qt.txt](https://github.com/OpenShot/openshot-qt/files/1725993/openshot-qt.txt)

**Comment by peanutbutterandcrackers** [comment]
@kubota95 - A very well written issue. Thanks. Hopefully, someone will get back to you on this, soon.

**Comment by peanutbutterandcrackers** [comment]
@kubota95 - A very well written issue. Thanks. Hopefully, someone will get back to you on this, soon.
