### ISSUE TITLE
clip windows

### ISSUE THREAD

**Issue by bulgaros71** [OpenShot/openshot-qt#128]
in the window of the clip, if I click the right button on an imported file (which in the old version gave no problems) it will not open no menu, so I can not work on the clip.
If I drag it into the timeline I see well

**Comment by telelauro** [comment]
I have the same problem... and I can´t work on the clip until I put it in the timeline...

**Comment by jonoomph** [comment]
Please attach your log file so I can check for any errors.

**Comment by jonoomph** [comment]
C:\Users\USER\.openshot_qt\openshot_qt.log

**Comment by telelauro** [comment]
here you have the archive in .rar


2016-03-17 5:00 GMT+01:00 Jonathan Thomas <notifications@github.com>:

> C:\Users\USER.openshot_qt\openshot_qt.log
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenShot/openshot-qt/issues/128#issuecomment-197683023>
>



-- 
"Dabilen kamerari Kroma-keyrik ez"

**Comment by DylanC** [comment]
@bulgaros71 - Please test in the latest version of OpenShot and re-open if this bug still exists.
