### ISSUE TITLE
Transparent titles overlay gone in v 2.4.1

### ISSUE THREAD

**Issue by ergunn** [OpenShot/openshot-qt#1280]
**System Details:**
* Operating System / Distro: Win 7 pro
* OpenShot Version: 2.4.1
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
The option to adjust title opacity is gone, not possible to create text overlays that are transparent?
I have tried all types of tutorials, and the new version seems to have lost this possability?
Thanks,
Erik

**Comment by peanutbutterandcrackers** [comment]
You can change the opacity of any clip by right clicking the clip > properties; and setting the alpha value of the clip manually. Please note that these properties are keyframable, like everythig else in OpenShot (which is precisely what is so very great about the software). You might want to look up 'OpenShot Keyframes' on youTube and also have a read through the online user guide at openshot.org

However, I think the best way to go about doing this would be to create a text overlay in GIMP with transparency and export it as a .png file and use that png file as tge overlay in your Videos. There are plenty of tutorials on YT regarding this too.

Hope that helps!

**Comment by peanutbutterandcrackers** [comment]
@ergunn - on second thought, you seem to imply that another version of OpenShot did indeed have this feature. Could you please tell us which? Thanks!

**Comment by ergunn** [comment]
Thanks for your suggestions and help!
I have been looking for video tutorials, and in those youtube-videos there are a different option of adding subtitles or other text-overlay that is transparent.
I do not know which version this is from, but have a look at this clip: https://www.youtube.com/watch?v=mB64rtc5X8c 

Thanks, Erik :)

**Comment by ergunn** [comment]
And now i realize all is my bad: If i put the overlay-text in track 2, and the video in track 1, it works. Learning by doing, thanks! :)

**Comment by DylanC** [comment]
@ergunn - No problem. Everyone makes mistakes. :)

**Comment by marcelkloes** [comment]
Hi,

I am trying and trying, but I can't get any text via titles over my video. I tried dragging it into Track 1 to 4, or the indiviual image or video in the track, but the only option given in titles is save or cancel. Please help. thanks.

**Comment by peanutbutterandcrackers** [comment]
@marcelkloes - First, you have to save the title you make from `Title` > `Titles` and then it'll appear in the Project Files tab and then you should drag it down to the timeline from there. I am using 2.4.2 and I can confirm that the transparent title overlays have not gone anywhere. :+1:
