### ISSUE TITLE
Feature request : image position

### ISSUE THREAD

**Issue by RAVke** [OpenShot/openshot-qt#1282]
**System Details:**
* Operating System / Distro: ? OSX Sierra
* OpenShot Version: ? 2.4.1
* _Please attach log files if crash_   Program works excellent on my computer :) :)

**Issue Description and steps to reproduce:**
Is it possible to add the following feature : if we are working with pictures : choose the position of the image in the frame, eg "top, middle, bottom" or "left, middle, right" Or that we can let an image slide through the window (for example from left to right).

Keep up the good work!

Nico

**Comment by peanutbutterandcrackers** [comment]
Are you perhaps referring to the following: (?)
1. Right click on the image > Layout > 1/4 size {center/top left/top right/...}
2. To make the image slide through the window: Right click the image > Animat > Entire Clip > Edge to Edge > Right to Left

Does that answer your question? o.O

**Comment by DylanC** [comment]
@RAVke - Yes, use the suggestion provided by @peanutbutterandcrackers. This will give you what you need.
