### ISSUE TITLE
Exported Video Flickers / shows permanently a keyframe

### ISSUE THREAD

**Issue by HaWoe** [OpenShot/openshot-qt#1283]
**System Details:**
* Operating System / Distro: Windows 10 / Version 1709 / Build 16299.248
* OpenShot Version: 2.4.1
* _(Program didn't crash)_

**Issue Description and steps to reproduce:**
I importet a mp4-Videofile (length 2h 50min, 3,71 GB (3.985.574.066 Bytes), video: 1280 x 720 Pix, data rate 2994 kBit/s, whole rate 3120 kBit/s, 25 frames/s, audio: 125 kBit/s, stereo, 48.000 kHz) to trim it and remove the advertising. Finally I had a project consisting of 5 clips, nothing more. After the export the film produces the correct sound but the video flickers and shows every few frames a keyframe (I think).
The export was made as mp4 (mpeg4), profile: HD 720p, 25fps (1280 x 720). The codec seems to be broken, but I don't know how to fix it. The same happens with the setting "HD 720p, 24fps (1280 x 720)" even if I render only a few minutes of the film -> [uploaded part of film on dropbox](https://www.dropbox.com/s/3hjyvgg4n067qc6/Tv%20%20%20test%20oliver%20twist%20%28part%29.mp4?dl=0)

**Comment by peanutbutterandcrackers** [comment]
@HaWoe - Are you sure you uploaded the correct film? I can't see any noticable flickering and/or keyframe in the clip that you've uploaded...

I did have a vaguely similar issue on a friend's windows 7 laptop a few days back but I am not sure if we are on the same page...

Perhaps it was a problem with the encoding and dropbox re-encoding the video fixed it? o.O

**Comment by HaWoe** [comment]
Hello @peanutbutterandcrackers , thank you for your answer.

The problem was the Microsoft "Filme & TV"-App. Playing the clip with the VLC-Player works without flickering. Can you tell me how to fix the app? Re-installing? Or is it necessary to overwrite some codecs?

By the way, I didn't know that Dropbox re-encodes uploaded films!

Greetings
HaWoe

**Comment by peanutbutterandcrackers** [comment]
@HaWoe - I am not sure how to fix that... sorry. And yes, I think dropbox re-encodes and/or compresses videos. I haven't really checked but I am pretty positive...

Please do let me know how 25 fps works out for you.

Yes, VLC media player is an awesome and powerful media player.

Well, I hope you keep on creating awesome videos with OoenShot. All the very best! :)

**Comment by HaWoe** [comment]
Hi @peanutbutterandcrackers 
yes the jitter disappears. The source was with 25 frames, so it was clear why the output with 24fps struggled every 25th frame.
But the preference with 'high' quality let the size of the output-file explode (from approximately 3 GB to over 12 GB) *argh* - now I'm testing the next film with 'low' quality settings.
Greetings
HaWoe

**Comment by peanutbutterandcrackers** [comment]
Yeah, the medium and low quality might help. Perhaps even try other encodings ('target')? Hope that helps. :)

I hope you continue to use and support OpenShot. :)

**Comment by DylanC** [comment]
@peanutbutterandcrackers - Should we close this one?

**Comment by peanutbutterandcrackers** [comment]
@DylanC - If you see it fit to be closed, then so, good sir. *tips tophat* :)

@HaWoe - Please do use mentions to tell me what happens when using 'low' quality. I'd like to know. All the very best!
