### ISSUE TITLE
Timelapse video: fewer frames than images in imported sequence

### ISSUE THREAD

**Issue by MadeBunnyCry** [OpenShot/openshot-qt#1285]
I'm using OpenShot to create timelapse videos from image sequences, but I've consistently had an issue with the resulting video being shorter than the number of images and framerate (24 fps) would predict.

For example, with my latest video, the imported sequence had 1284 images, but I'm only getting 987 frames in the resulting video. I've used a renaming tool to make sure my images are sequentially numbered. The end of my videos are consistent with the end of the image sequence, so the missing frames are not cut from the end, apparently.

Any insight into what might be causing this issue would be greatly appreciated.

**Comment by peanutbutterandcrackers** [comment]
Whoa. That is definitely strange. I think I should look into this to see if it happens on my machine too. Could you please also give us the specs of your machine?

@DylanC - I think we need to test this...

**Comment by DylanC** [comment]
@MadeBunnyCry - As far as I know the implementation of the image sequence import is not so mature yet. I think not many naming patterns are supported.  See #932 

What format do you have the file names?

**Comment by jaylubo** [comment]
I see this as well with Openshot 2.5.1. My image filename is img_XX
