### ISSUE TITLE
Blender/Inkscape path - OSX 10.13

### ISSUE THREAD

**Issue by EmptyVessel-NZ** [OpenShot/openshot-qt#1287]
**i7 Macbook Pro**
OSX 10.13
Openshot 2.4.1
![screen shot 2018-02-19 at 5 00 35 pm](https://user-images.githubusercontent.com/36614762/36362142-c5490f88-1596-11e8-8be3-529442cc4159.png)

Hi all, I'm not having much luck establishing the path to Blender in the current Openshot version, the path appears perfectly fine to me but I get the error message the app can't be found, have tried specifying only the folder and also using only 'blender' rather than blender.app
![screen shot 2018-02-19 at 5 03 53 pm](https://user-images.githubusercontent.com/36614762/36362154-e577c164-1596-11e8-83a6-c24e870f271c.png)

Any help would be very gratefully received.
Cheers.
Greg.

**Comment by DylanC** [comment]
@EmptyVessel-NZ - Hi Greg, I can test on my own mac later today if you wish.

**Comment by EmptyVessel-NZ** [comment]
If you could Dylan I'd appreciate it, thanks.

**Comment by EmptyVessel-NZ** [comment]
any progress on this or anyone from Openshot care to clarify what the setting should be?
Thanks.

**Comment by DylanC** [comment]
@EmptyVessel-NZ - I had a look just now. Not sure what is going on but when I try to get the path I have the same trouble. Now something I did notice is the version I downloaded has a capital B. So in your case maybe try **B**lender.app.

Still wouldn't be sure its going to work but maybe worth a shot.

**Comment by EmptyVessel-NZ** [comment]
thanks Dylan, I tried the capital B but still the same issue. :(

**Comment by peanutbutterandcrackers** [comment]
Could you take a look at [this]https://www.youtube.com/watch?v=ZH2fMcuZgeol) video? Please note that I haven't really watched it fully, nor do I use a mac. But I hope it helps.

**Comment by DylanC** [comment]
@EmptyVessel-NZ - That's unfortunate. Tried my best with the Mac I have and I had no luck too. Hopefully a more experienced Mac user can help you out.

**Comment by peanutbutterandcrackers** [comment]
@DylanC - Can you create new labels too? If so, how would it be if we had 'mac' and 'windows' label? Or 'mac-specific' or 'windows-specific' labels? I think that'll help others wanting to help....

**Comment by EmptyVessel-NZ** [comment]
thanks both, @peanutbutterandcrackers yeah I worked in IT a long time so I'm satisfied I've got the correct path and double-checked using the method in the video also and still receiving the error message.
Given Openshot support points me to this forum is there nobody actually from Openshot here to answer queries when they're raised?

**Comment by peanutbutterandcrackers** [comment]
@EmptyVessel-NZ So, the thing is, OpenShot is the labour of love of a single person --- Mr. Jonathan Thomas. He is the only active developer we currently have. And he does all the things. Therefore, we do not really have people from OpenShot helping us out. We are all volunteers who love this project and try to scratch each other's back. That is how this Free and Open Source Software works.

If you can, I would like to request you to please consider helping out this project with your knowledge. Perhaps you could do some digging around to see what exactly is causing the problem... Maybe even submit a Pull Request fixing this issue?

I'm sorry for the inconvenience. But OpenShot is a really wonderful program. It really is...

**Comment by EmptyVessel-NZ** [comment]
_"I'm sorry for the inconvenience. But OpenShot is a really wonderful program. It really is..."_
I'm very happy with it so far, I was using Premiere and it was way more full-featured than I needed and Openshot is about perfect in terms of feature set for what I need.

I'm always grateful for projects like these providing such software for free, confused even and I was a Linux user for many years so the free and open-source concept is not new to me.
I'm very happy to do what digging I can and have already done quite a bit of investigation and will continue to do what I can, I do use several free/donation products where the sole developer still does what they can do support that product - very generously IMO. There would be occasions I'm sure where the person who coded the product is the best one to comment on/resolve an issue/bug.

I've tried moving the Blender folder out of the system /Applications location and in to my own user ~/Applications in case of some permissions problem but again the same error.

I'll have a look and see if perhaps I can get to the application log and see if there is an error which makes it clearer why it can't find the executable despite the path being apparently correct.

One comment on your 'Pull Request' suggestion - I am new to Github so I'll have to do some reading to understand what the procedures here are.

**Comment by EmptyVessel-NZ** [comment]
Updating after some further investigation:
When attempting to run blender from Terminal the path is reported as incorrect:
-bash: /Users/gregcole/Applications/blender/blender.app: is a directory

So just because the application shows as that path from the OSX GUI perhaps I actually need to work out how to point Blender to the 'launch' python script inside the package which is actually what runs the application.
That being the case I can't believe very many OSX users would have managed to get this working if that's what's necessary.

**Comment by DylanC** [comment]
Dup of #1103

**Comment by EmptyVessel-NZ** [comment]
thanks Dylan.

**Comment by peanutbutterandcrackers** [comment]
@EmptyVessel-NZ - I hope you do stick around and try to help us out with the issue resolving and testing and stuff. I'm sorry I do not have a mac so I can't really provide any useful insights in this regards. Perhaps someone can soon provide some help regarding this? Sorry for the inconvenience...

**Comment by EmptyVessel-NZ** [comment]
@peanutbutterandcrackers - yeah of course, I'm happy to hang around and do what I can. I spent quite a bit of time yesterday trying to work out what was going on but so far not able to sort it out. Inkscape is similarly affected. I asked on the OpenShot Facebook page also but no response there.

**Comment by peanutbutterandcrackers** [comment]
@EmptyVessel-NZ - I think Mr. Jonathan Thomas is the one who handles even the FB page. He makes [tutorial videos on YouTube](https://www.youtube.com/watch?v=1k-ISfd-YBE&list=PLymupH2aoNQNezYzv2lhSwvoyZgLp1Q0T), too. And everything else OpenShot. Perhaps someday, you'll get enough confidence of the community and Mr. Thomas that you'll be able to become the maintainer of the FB page, at the very least. :)
Yes, we do need some more mac users. There seem to be quite few of them....

**Comment by skvaller** [comment]
C:\Program Files\Inkscapes\inkscapes.exe

C:/program files/blender foundation/blender/blender.exe

**Comment by peanutbutterandcrackers** [comment]
It seems that the solution provided at #1400 works. It has apparently [worked for some users](https://github.com/RedSoxFan04). I think it's worth a shot.

**Comment by EmptyVessel-NZ** [comment]
@peanutbutterandcrackers thank you so much, I can confirm that this has resolved the issue for me.

Very grateful for the help!

**Comment by peanutbutterandcrackers** [comment]
Awesome! I'm glad it worked for you. But it is that kind person that actually deserves the thanks, though. :)

**Comment by EmptyVessel-NZ** [comment]
@peanutbutterandcrackers - of course, you're right! I will add my thanks to the original post!

**Comment by peanutbutterandcrackers** [comment]
That is very nice of you. :)

I hope you make amazing videos with OpenShot!
