### ISSUE TITLE
Fade to white?

### ISSUE THREAD

**Issue by artm115834** [OpenShot/openshot-qt#1289]
2017 iMac, MacOS High Sierra 10.13.3. I'm a totally new user. I saw a fade filter, which appears to be fade to black. Is there a fade to white filter? Thanks.

**Comment by peanutbutterandcrackers** [comment]
You could import an all white image the same size as the video (for instance 1080 x 720 or sth), and on the timeline, overlap it at the end of the video you want to fade to white. That will result in a fade to white effect. Hope that helps.

P.S: You should probably check out "Jonathan Thomas OpenShot" on YouTube. He's our main developer and has made awesome tutorials. The DP shows him with a bird on his shoulder. :)

**Comment by N3WWN** [comment]
To add a tad to what @peanutbutterandcrackers said, the `Fade` fades to/from transparent, so whatever image or video is underneath (on a lower track) will become more or less visible as the transparency progresses.  

The reason it appears to fade to black is because there is no image underneath the current video, so OpenShot defaults to a blank (black) background.

**Comment by artm115834** [comment]
Thanks, peanutbutterandcrackers and N3WWN. I'll give these things a try.

N3WWN: Is that a ham operator call sign? I used to be WV2OCM--way, way back when...

**Comment by N3WWN** [comment]
You're welcome @artm115834 !

Yes, OM, I am a ham.  hi hi  But haven't been too active lately.  Used to do a lot of APRS and some LEO satellite work when I was active.  Now I pretty much just maintain our local DStar repeaters.  If only there was more time...

73 de Rich N3WWN

**Comment by peanutbutterandcrackers** [comment]
@artm115834 - has this issue been resolved for you, good sir?

**Comment by DylanC** [comment]
@peanutbutterandcrackers - Seemed to be resolved from what I can see. @artm115834 - Closing this issue now if you don't mind.
