### ISSUE TITLE
Enhancement: multicam support

### ISSUE THREAD

**Issue by N3WWN** [OpenShot/openshot-qt#1292]
I'd like to see multicam support added to OpenShot, and I think it may be able to be done with a minimum of development.

Most of my videos are composed of videos from 2 cameras which I manually sync, trim, transform, layer, etc.  Multicam support would be VERY helpful with this.

I think an interesting implementation would be to have a "video source" clip on an upper layer.  A new property/keyframe type would be required for this type of clip and that keyframe would track source.  That property should also include a "show no video" option;  perhaps Track -1.

The "video source" clip should have a length that can be changed via dragging the start and end.

Also, the "video source" clip should be exportable (and importable) as well as behaving like any other video clip so that fades, transforms, etc.  This would allow presets.  Perhaps this could be implemented with the SVG file format which is interpreted in this special way internally within OpenShot?

**Example # 1 (current):**

Track 0 - titles
Track 1 - Border around video in Track 2
Track 2 - Overlay video in lower right (filling 25% of the screen)
Track 3 - Background video (filling 100% of the screen)

I have to adjust the following on every video I place on Track 2:
- Scale
- Scale X & Y
- Location X & Y

I then have to copy the properties from Track 2 and apply them to Track 1.  I cannot easily swap the videos or change the active video in the overlay.  

This needs to be done for EVERY video pair, of which I have between 6 and 18 pairs of videos every weekend (12-36 videos + 1 border image for every pair) during the summer months.  I create one longer video by placing these overlayed segments side by side on the timeline.  This makes the timeline very cluttered and very difficult to adjust if I find that I need to resize or move one or more of the overlays elsewhere (upper left, for instance).

**Example # 2 (desired):**

Track 0 - titles
Track 1 - Border around video in Track 2
Track 2 - "Video source"  in lower right (filling 25% of the screen), showing Track 4
Track 3 - Background video (filling 100% of the screen)
Track 4 - Overlay video

Create a "video source" clip "preset" in Track 2 which contains the Scale, Scale X & Y and Location X & Y properties and will use the video on Track 4.

With this method, I can change the clip on Track 4 and that would filter up to what is being shown on Track 2.  I could also add a keyframe to view another track, say Track 5, for a bit and then switch back to Track 4.

**Example # 3 (desired):**

Track 0 - titles
Track 1 - "Video source"  with "hot areas", one as the "background" (showing Track 2) and one in the lower right (filling 25% of the screen and showing Track 3).  The border around the overlay video would also be included and be opaque (in this example).
Track 2 - Background video (filling 100% of the screen)
Track 3 - Overlay video in lower right (filling 25% of the screen)

This one would be like a SVG file where the elements could be assigned to different tracks on the timeline.  In the attached example image, the solid green area would be assigned to Track 2, the solid blue area would be assigned to Track 3 and the black area would be opaque, creating a border around the blue area.

![video source - 180220](https://user-images.githubusercontent.com/19431804/36446807-74dba4ce-1650-11e8-9941-f04adbe50056.png)

In reality, it may be specific colors or alpha values that are used which would not exclude the use of certain colors as non-video selection areas:  Any color (not black) that is totally transparent could be swapped out with the video track since a totally transparent, non-black color would not be visible anyway.  This could be RGBA where R, G and B are > 0 and A = 0.  For instance, # FF000000 is totally transparent red, # F4BF4200 is a shade of totally transparent orange and # FFFFFF00 is totally transparent white.  A SVG file with these three colors would be able to display video from 3 different tracks at once along with other artifacts, like totally opaque red text ( # FF0000FF ) or a semi-transparent orange logo ( # F4BF4280 ).  

Implementing the "video source" clip this way (totally transparent colors within SVG files) would allow users to use Inkscape (or any other SVG editor) to create the file.  The file could then be converted (by manually setting the alpha to zero or doing the same via a script) or the colors could be selected upon import into OpenShot.

In Examples # 2 and # 3, instead of needing to modify the properties of each clip over and over and over again, I can place the clip on the timeline and then copy and paste the "video source" clip, making the values consistent for every overlay (something I have problems with when I set 5 properties on 2 different clips for every video pair + border).

**Example # 4 (desired - multicam):**

Track 0 - titles
Track 1 - "Video source"
Track 2 - Camera from stage left
Track 3 - Camera from stage right
Track 4 - Camera from center stage

Here, Tracks 2 through 4 are manually sync'd/aligned and keyframes on Track 1 would be used to change which Track (2-4) is visible at multiple times along the timeline.  

This would be incredibly useful for presentations, weddings, rocket launches, sports events, etc.

Just thinking... and dreaming!  😁

**Comment by peanutbutterandcrackers** [comment]
@DylanC - While #684 does raise a similar issue. This is a lot more elaborate. Plus, it's from @N3WWN too. I like this one better.

@N3WWN - That would be simply very neat! I wonder why you haven't made any PRs as of yet... given the technical insights you have. And here I am, hoping to submit a PR by the end of 2018...

**Comment by N3WWN** [comment]
@peanutbutterandcrackers Actually, LightWorks was one of the tools I was using before I found OpenShot.  I don't think the multicam support in LightWorks is very intuitive at all.  This may be because I've never successfully used multicam in **any** editor.

Sorry that this is somewhat of a dupe of #684 ... I searched for "multicam" and "multiple cameras" and no results were returned.  I guess I should have searched for "multi-cam", too! 🤣 

I would love to submit some PRs to OpenShot!  It's actually very daunting to get started in development for OpenShot because of all of the technologies that I'm unfamiliar with, even though I am a developer with over 20 years of experience.  I've never really worked with Qt, graphics, sound, video, etc from a dev point of view, although I understand how a lot of it works from a high-level perspective.

My hope is that I will be able to start contributing some items when the new custom effect framework is released.

If I get some "free" time, I'll take a look at the OpenShot source some more and see if there's anything I can start digging into so I can get some PRs into the pipeline.

**Comment by peanutbutterandcrackers** [comment]
@N3WWN - I will be looking forward to that day! Hope it comes soon when your name is also listed in the 'developers' section in OpenShot's 'about' dialogue window. :)

**Comment by N3WWN** [comment]
I'd still love to see this enhancement.  Examples # 3 and # 4 would be very useful in my typical projects.

**Comment by N3WWN** [comment]
I'd still love to see this enhancement. Examples # 3 and # 4 would be very useful in my typical projects.
