### ISSUE TITLE
Inkscape problem

### ISSUE THREAD

**Issue by Jonsgs** [OpenShot/openshot-qt#1293]
**System Details:**
* Operating System / Distro: W7
* OpenShot Version: 2.4.1
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
So I downloaded Inkscape .92 for OpenShot but I when pressed advanced editing, it still tells me to install inkscape.

**Comment by grzegorz75jan** [comment]
https://github.com/OpenShot/openshot-qt/issues?utf8=%E2%9C%93&q=openshot+blender+inkscape
https://www.youtube.com/results?search_query=openshot+inkscape+blender+associate+path

https://streamable.com/hvu96

**Comment by peanutbutterandcrackers** [comment]
@Jonsgs - Perhaps [this video](https://www.youtube.com/watch?v=l_r12b99TIg&t=1155s) will be of some help? Even though it is talking about blender, I think it also applies for InkScape, since it is being done on a windows machine.

**Comment by jacksteamdev** [comment]
For those coming here using a Linux install:

https://github.com/OpenShot/openshot-qt/issues/3296#issuecomment-600781209
