### ISSUE TITLE
Says "Import Error, DLL Load Failed"

### ISSUE THREAD

**Issue by EBW1** [OpenShot/openshot-qt#1295]
**System Details:**
* Operating System / Distro: Windows 10
* OpenShot Version: 2.4.1
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

![prob](https://user-images.githubusercontent.com/36717030/36512966-ace5b408-1732-11e8-91b4-c17ad3a5efcd.png)

I downloaded OpenShot and it was working fine. Made 2 videos. When trying to make 3rd says Import Error, DLL Load Failed shown in image, I have tried to re download it, still doing the same thing

Help!!!

**Comment by EBW1** [comment]
never mind!!! found how

**Comment by peanutbutterandcrackers** [comment]
@EBW1 - Could you please tell us what solved this issue for you? Was it deleting the .openshot_qt folder? o.O [This could help the devs fix this thing]

**Comment by EBW1** [comment]
i ran as administrator and it worked!!!!

Thanks!!

**Comment by DylanC** [comment]
@EBW1  - Thanks!
