### ISSUE TITLE
Can export video, but it fades to black and stops half way through

### ISSUE THREAD

**Issue by ORainKnightO** [OpenShot/openshot-qt#1297]
**System Details:**
* Operating System / Distro: Windows 10
* OpenShot Version: 2.4.1
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
It exports just fine, but when I play back the exported file, it just fades to black and the audio completely stops halfway through the video.

On the left you can see that it is in process of fading out, while the original work, on the right, is perfectly fine.
All I did was create a normal video and hit export. I tried a bunch of different sizes and frame rates, including the standerd 720p and the same thing keeps happening.
![ice_screenshot_20180222-171706](https://user-images.githubusercontent.com/36748425/36569666-474940b6-17f4-11e8-994f-848484c8e9d2.png)

Edit: After a bit of experimentation, I have found out that I can't have it on 60fps or this happens. I have currently gotten 720p 24fps and 1080p 24fps to work correctly.

**Comment by peanutbutterandcrackers** [comment]
@ORainKnightO - So, it's working correctly when you have it set to 24fps?

So, the thing is: If your original video was shot in 24fps, you'll get errors like these if you choose an incorrect profile (like 60fps) while editing it.

Hope that helps!

P. S: Please do not forget to close this issue if this has been resolved. Thanks! :)

**Comment by peanutbutterandcrackers** [comment]
@ORainKnightO - I hope this issue was really resolved for you. Was it? o.O

**Comment by ORainKnightO** [comment]
Yes, as long as I set it to the correct frame rate it was fine. Thank you :D

**Comment by peanutbutterandcrackers** [comment]
@ORainKnightO - Glad it really was resolved. I hope you create awesome videos with OpenShot! :)

**Comment by ORainKnightO** [comment]
Thank you :D

**Comment by peanutbutterandcrackers** [comment]
@ORainKnightO - You're most welcome! :)
