### ISSUE TITLE
Rendering Failure

### ISSUE THREAD

**Issue by WolfieMar** [OpenShot/openshot-qt#1299]
When I Made a Video And I Wanted To Check It Out, It Kept On Lagging On Almost The End! Its Very Annoying Because I Want To Make This Cool Video!

**Comment by peanutbutterandcrackers** [comment]
@WolfieMar - I do understand your frustration. However, if you could also give more details, that will help others help you. If you're using windows, it seems that OpenShot is having a lot of problems on windows and this might be one of them. But you could probably try out rebooting the computer, and starting the render process without doing anything else. That should give the CPU only one (heavy) work to do. Hope that helps!

**Comment by WolfieMar** [comment]
im using windows 10

**Comment by peanutbutterandcrackers** [comment]
@WolfieMar - I see. Perhaps you should try uninstalling OpenShot, deleting all the OpenShot specific files (perhaps a cleaner like [BleachBit](https://www.bleachbit.org/), a free and Open Source software, might help you out with the registry clean up and stuff) and then reinstalling it might help? Some of the users say they can work fine with OpenShot on Windows. But I am not very sure...

Perhaps, if you're feeling too tired of windows, you might want to give Linux a try, too? I recommend [Linux Mint](https://www.linuxmint.com/).

But as for the windows specific problems in OpenShot, maybe it'll take a little bit more time to fix as we only have a single developer working on OpenShot, actively, right now.

Hope this helps. :)

**Comment by WolfieMar** [comment]
im a windows user and im not going to install linux because of all my windos data that only can run on windows and i dont like other OSes. also the bug is gone

**Comment by peanutbutterandcrackers** [comment]
The bug is gone? Did you do anything that proved to work around the bug?

Anyways, glad that it is working for you now. :)
