### ISSUE TITLE
Editing out certain parts and blending the rest together

### ISSUE THREAD

**Issue by pitbull830** [OpenShot/openshot-qt#1300]
How do you edit out a part of your video and blend the rest together

**Comment by peanutbutterandcrackers** [comment]
Please watch [this](https://www.youtube.com/watch?v=BQS2tmgD_Rk&t=180s) video.

Basically, you drag the video into the timeline. Cut off the vid at the start of the 'bad' part. Cut off again at the end of the 'bad' part. Delete the resulting 'bad' clip. Drag the two clips together. And export it from OpenShot.

Hope that helps!

**Comment by DylanC** [comment]
Closing this as the question has been answered.
