### ISSUE TITLE
Scrolling stops at end of timeline

### ISSUE THREAD

**Issue by artm115834** [OpenShot/openshot-qt#1301]
2017 iMac, MacOS High Sierra 10.13.3.

I often zoom the slider to 1 second for the kinds of projects I create. When I zoom in this way and play back my video, the screen doesn't move forward in the timeline when the play-head reaches the end of the line. I'm guessing I'm so new to OpenShot and the my iMac that I'm missing a simple setting, so please forgive this naive problem: How do I get the OpenShot timeline to advance with the zoom slider set at 1 second? Thanks.

**Comment by peanutbutterandcrackers** [comment]
@DylanC - I can confirm that this same issue manifests itself on my Elementary OS 0.4.1 'Loki' machine - using the daily PPA. Turns out, it doesn't scroll even for 2 seconds or 10 seconds. I think we actually lack an auto-scrolling feature.

**Comment by peanutbutterandcrackers** [comment]
@artm115834 - I think for the time being, you'll just have to make do with what OpenShot is right now. Sorry for the inconvenience. Hopefully, the developers will get around to fixing this soon.... (Actually, we only have a single developer right now. What we need is more people submitting bug fixes and enhancements to this awesome project)

**Comment by DylanC** [comment]
@peanutbutterandcrackers - Yep, this should be solved!

**Comment by artm115834** [comment]
Thank you, DylanC and peanutbutterandcrackers.

**Comment by DylanC** [comment]
@artm115834 - No problem. Happy to help! :)

**Comment by peanutbutterandcrackers** [comment]
@DylanC - Yeah!

@artm115834 - You're most welcome! :)
