### ISSUE TITLE
Chroma Variation

### ISSUE THREAD

**Issue by Danielma1** [OpenShot/openshot-qt#1303]
**System Details:**
* Operating System / Distro: WIN 10
* OpenShot Version: 2.4.1.

Hi. I would like to know how to adjust the color variation in chroma.

Thanks

**Comment by peanutbutterandcrackers** [comment]
@Danielma1 - Right click the 'C' icon on the clip on the timeline, click properties. The 'Fuzz' property is the color variation one in OpenShot. [Here](https://www.youtube.com/watch?v=2sushecqMs4&t=1s) is a video on Chorma Keying in OpenShot by Mr. Jonathan Thomas --- the creator and lead developer of OpenShot --- himself. Hope that helps!

**Comment by DylanC** [comment]
Closing this question as answered. Thanks @peanutbutterandcrackers
