### ISSUE TITLE
enhancement / feature: this project urgently requires subtitle support

### ISSUE THREAD

**Issue by Meteor0id** [OpenShot/openshot-qt#1304]
Subtitles are a must have for video editors. But I am sure we all agree on that, it's simply easier said than programmed.

Nevertheless, I noticed a few questions have been posted but no actual feature request/ enhancement ticket. So here we are.
Let's get started on subtitles soon.

**Comment by DylanC** [comment]
@Meteor0id - Yep, it would be a nice addition to the program.

**Comment by bes1002t** [comment]
Would be necessary to get a full video editor feature set. Hope someone could take care of this in the future.

**Comment by SuslikV** [comment]
The feature request is not clear. Do you need to embed subtitle file into final movie (multiplex, becomes closed captions, if selected media container supports it, "soft" subtitles) or rasterize it (render directly to final image, becomes part of the image, as any titles, "hard" subtitles) ?

If you just need a program for subtitle creation, try these:
- _Aegisub_ (old but handy);
- _SubtitleEdit_ (still under development, many formats, a bit dubious interface).

**Comment by bes1002t** [comment]
@SuslikV I think the issue creator was talking about subtitles in genera. In my humble opinion it's the development team who should decide which way would be the best way.

Probably not using hard subtitles would be better, because mostly you wanna provide different languages.
