### ISSUE TITLE
Preferences are not saved

### ISSUE THREAD

**Issue by chrisncy** [OpenShot/openshot-qt#1306]
**System Details:**
Windows10
 OpenShot Version: 2.4.1

Hello
Choices in preferences are not saved
I do not know how to do
Thank you

Sorry for google English

**Comment by peanutbutterandcrackers** [comment]
@DylanC - This could be because for some reason OpenShot's doesn't have permissions to save a openshot.settings file... Strange, the cx_freeze error also seemed to have something to do with permissions, if I'm not mistaken.

**Comment by peanutbutterandcrackers** [comment]
@chrisncy - Sorry for the inconvenience. I think the developers will get around to fixing this too, hopefully soon...

**Comment by DylanC** [comment]
@peanutbutterandcrackers - Yes, Windows issues are about the permissions many times.

**Comment by chrisncy** [comment]
Thank you for your answers.
Can you tell me in which folder I have to put the permissions?

**Comment by DylanC** [comment]
@chrisncy - I would recommend to try running OpenShot in administration mode.

**Comment by peanutbutterandcrackers** [comment]
Yeah. Running OpenShot in administrator mode seems to do the trick in most of the cases. :)

**Comment by chrisncy** [comment]
Hello
not on my computer :-(
I tried in administrator mode, and no effect...
Never mind and thanks to all

**Comment by peanutbutterandcrackers** [comment]
@chrisncy - Did you try deleting the .openshot_qt folder from your home directory? That could fix this, too.
