### ISSUE TITLE
Err:12 http://ppa.launchpad.net/openshot.developers/ppa/ubuntu artful Release 404  Not Found

### ISSUE THREAD

**Issue by 0s2o** [OpenShot/openshot-qt#1307]
**System Details:**
* Operating System / Distro: Ubuntu 17.10 - Kernel: x86_64 Linux 4.13.0-36-generic
* OpenShot Version: 2.4.1

Err:12 http://ppa.launchpad.net/openshot.developers/ppa/ubuntu artful Release
  404  Not Found

![screenshot from 2018-02-25 08-50-25](https://user-images.githubusercontent.com/392155/36642200-faa2657c-1a09-11e8-90fd-6e6298b1d799.png)

**Comment by peanutbutterandcrackers** [comment]
@chebit - First and foremost, thank you! I just learned about screenfetch command because of this screenshot. Pretty neat!
Secondly, Perhaps you might one to try to use the [app images](https://github.com/OpenShot/openshot-qt/releases) for now?

**Comment by DylanC** [comment]
@peanutbutterandcrackers 
I'm closing this as the primary method of distribution at the moment is the AppImage. Also we will (hopefully) have Openshot latest version in Ubuntu store from now onwards.
