### ISSUE TITLE
cant install blender with openshot on windows10

### ISSUE THREAD

**Issue by Taproot88** [OpenShot/openshot-qt#1308]
**System Details:**
* Operating System / Distro: w10
* OpenShot Version: 2.4.1

![blender](https://user-images.githubusercontent.com/36818400/36643136-fe65eef2-1a47-11e8-9977-e047d90fa5dd.png)

this what i have on my c\programme page, but when i iopen animated title it asks me to install blender but its already installed like you can see

can you hel please, thank you
sorry for my bad english

**Comment by peanutbutterandcrackers** [comment]
@Taproot88 - Under Edit > Preferences, you need to set 'Blender Path' to the exact path where blender has been installed on your computer. Hope this helps!

**Comment by peanutbutterandcrackers** [comment]
@Taproot88 - Perhaps [this](https://www.youtube.com/watch?v=l_r12b99TIg&t=1155s) video will be of some help to you. He goes into the details of blender path, it seems.

**Comment by Taproot88** [comment]
hello guys, i ve added blender path but its still doesent work

you can clearly see it recognize the path
![19437680_10208868120132621_1025242012469253912_n2323](https://user-images.githubusercontent.com/36818400/36812128-64a371f0-1cd0-11e8-8b18-b7134c00f183.jpg)

**Comment by DylanC** [comment]
@Taproot88 - Did you type in blende.exe in the path or blender.exe?

**Comment by Taproot88** [comment]
i have added blender.exe here
![19437680_10208868120132621_1025242012469253912_n2323](https://user-images.githubusercontent.com/36818400/36837286-37be8cc6-1d3c-11e8-828b-d8a724beb981.jpg)

If i try to add \blender.exe in the c:\PROGRAMME path it opens blender for me. The "\blender.exe" line you see in RED disappears and blender opens. Not blender in openshot it only opens blender by itself
![bblender](https://user-images.githubusercontent.com/36818400/36837601-1e862f06-1d3d-11e8-8428-69bf677fc9b9.jpg)

this is what i found in properties. I've added that path in blender after adding \blender.exe in to it. bUT AS YOU CAN see ma c:\programme path doesent finish with \blender.exe
![bblender](https://user-images.githubusercontent.com/36818400/36837855-c7cd7e98-1d3d-11e8-93e2-2765f7ed9c0a.jpg)

thank you

**Comment by Taproot88** [comment]
problem solve now it works fine, very slow but thats normal i guess, thank you all

**Comment by DylanC** [comment]
@Taproot88 - Great to hear, thanks!

**Comment by peanutbutterandcrackers** [comment]
@Taproot88 - Could you please tell us how you managed to fix this issue, please? Would help us help others too. :)

Glad it's working for you now! :+1:

**Comment by pcurik** [comment]
Hello,
I have the same problem.
I wrote the right path:
![bez-nazvu-2](https://user-images.githubusercontent.com/17381673/37459368-1d78ec8c-2848-11e8-99fd-85c0dd5450d5.jpg)

but if I try to use , the result is with 2.78 before path
![bez-nazvu-1](https://user-images.githubusercontent.com/17381673/37459448-61a9a612-2848-11e8-8c66-8a658f45ad7d.jpg)

**Comment by peanutbutterandcrackers** [comment]
@DylanC - This ^ is quite strange, isn't it? Any ideas? Perhaps, with a different locale, this issue manifests itself? o.O

**Comment by peanutbutterandcrackers** [comment]
@pcurik - Thank you for the good report!

**Comment by DylanC** [comment]
@peanutbutterandcrackers - The Blender path has been working for a very long time so yeah it must be something like that. I can play around with different locale to see if the issue happens.

**Comment by peanutbutterandcrackers** [comment]
@DylanC - Looking forward to the results of your tests, El Capitano! :)

**Comment by peejayw** [comment]
I have just installed Openshot on Windows 10 and have the above problem with Blender. When I try to use an animated title, Openshot opens two instances of the window regarding the path of Blender. I have made sure to copy/paste the path to Blender so Im pretty sure its correct.
Any suggestions on what else I can try?
