### ISSUE TITLE
First Video with OpenShot

### ISSUE THREAD

**Issue by artm115834** [OpenShot/openshot-qt#1309]
I’ve completed my first OpenShot Video Editor project: https://youtu.be/eFcYa4BEVts.

This work is a continuation of the kinds of videos I’ve been producing for my YouTube channel during the last few years, but this one is my first in OpenShot and my first on a Mac. All the other videos were created in Windows with Windows Movie Maker. I welcome constructive ideas on how to make these kinds of OpenShot videos better. Thanks!

This work is a continuation of the kinds of videos I’ve been producing for my YouTube channel during the last few years, but this one is my first in OpenShot and my first on a Mac. All the other videos were created in Windows with Windows Movie Maker. I welcome constructive ideas on how to make these kinds of OpenShot videos better. Thanks!

**Comment by peanutbutterandcrackers** [comment]
@artm115834 - Whoa! You're a composer!? Awesome!!! I'm so glad that OpenShot is working for you. Please do continue to make awesome videos with OpenShot! Hope it keeps being useful to you. And please do continue to support OpenShot, too. Perhaps consider making a [donation](https://www.openshot.org/donations/) to the developers, someday. Or telling your friends about it. Or putting a credit to OpenShot in the description. :)

Welcome to the family, good sir!

P. S: That is a really beautiful music.
