### ISSUE TITLE
How can I disable snapping in Openshot in Windows?

### ISSUE THREAD

**Issue by JonClyde1** [OpenShot/openshot-qt#1311]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

**Comment by peanutbutterandcrackers** [comment]
@JonClyde1 - You must have an icon that looks like a magnet right above the timeline. Clicking it (toggling) should turn snapping off. Hope that helps! :)

**Comment by peanutbutterandcrackers** [comment]
@JonClyde1 - Maybe [this](https://www.youtube.com/watch?v=l_r12b99TIg) video will also be of some help (for a beginner, generally. Not for this specific question, though)?

**Comment by DylanC** [comment]
@JonClyde1 - Yes, just click the magnet icon.

**Comment by JonClyde1** [comment]
Tried it several times (clicking the icon). No change: snapping always
remains on. Button broken?

Never mind, though. This may be useful for future users, if there are more
people than just me complaining. Moot point with me, as I have moved on to
DaVinci Resolve.

Good luck in all your endeavors!

Jonathan S. (JonClyde1)

**Comment by DylanC** [comment]
@JonClyde1 - Oh right. Really that is all that should be required. Thanks for getting back to us with this info!
