### ISSUE TITLE
'NoneType' object has no attribute 'set_cursor'

### ISSUE THREAD

**Issue by rodinux** [OpenShot/openshot-qt#1313]
**System Details:**

* Operating System / Distro: ?
Debian Strecht
* OpenShot Version: ?
OpenShot (version 1.4.3)
* _Please attach log files if crash_
```
------------------------- ERROR 1 ------------------------------
Failed to import 'from openshot import main'
Error Message: cannot import name main
----------------------------------------------------------------
--------------------------------
   OpenShot (version 1.4.3)
--------------------------------

Detecting formats, codecs, and filters...
---
video_codecs:
  - a64multi
  - a64multi5
  - alias_pix
  - amv
  - apng
  - asv1
  - asv2
  - avrp
  - avui
  - ayuv
  - bmp
  - cinepak
  - cljr
  - dnxhd
  - dpx
  - dvvideo
  - ffv1
  - ffvhuff
  - flashsv
  - flashsv2
  - flv
  - gif
  - h261
  - h263
  - h263p
  - hap
  - huffyuv
  - jpeg2000
  - jpegls
  - ljpeg
  - mjpeg
  - mpeg1video
  - mpeg2video
  - mpeg4
  - msmpeg4v2
  - msmpeg4
  - msvideo1
  - pam
  - pbm
  - pcx
  - pgm
  - pgmyuv
  - png
  - ppm
  - prores
  - prores_aw
  - prores_ks
  - qtrle
  - r10k
  - r210
  - rawvideo
  - roqvideo
  - rv10
  - rv20
  - sgi
  - snow
  - sunrast
  - svq1
  - targa
  - tiff
  - utvideo
  - v210
  - v308
  - v408
  - v410
  - vc2
  - wrapped_avframe
  - wmv1
  - wmv2
  - xbm
  - xface
  - xwd
  - y41p
  - yuv4
  - zlib
  - zmbv
  - libopenjpeg
  - libtheora
  - libvpx
  - libvpx-vp9
  - libwebp_anim
  - libwebp
  - libx264
  - libx264rgb
  - libx265
  - libxvid
  - h264_nvenc
  - h264_omx
  - h264_vaapi
  - nvenc
  - nvenc_h264
  - nvenc_hevc
  - hevc_nvenc
  - hevc_vaapi
  - mjpeg_vaapi
...
---
audio_codecs:
  - comfortnoise
  - s302m
  - aac
  - ac3
  - ac3_fixed
  - alac
  - dca
  - eac3
  - flac
  - g723_1
  - mlp
  - mp2
  - mp2fixed
  - nellymoser
  - real_144
  - sonic
  - sonicls
  - truehd
  - tta
  - vorbis
  - wavpack
  - wmav1
  - wmav2
  - pcm_alaw
  - pcm_f32be
  - pcm_f32le
  - pcm_f64be
  - pcm_f64le
  - pcm_mulaw
  - pcm_s8
  - pcm_s8_planar
  - pcm_s16be
  - pcm_s16be_planar
  - pcm_s16le
  - pcm_s16le_planar
  - pcm_s24be
  - pcm_s24daud
  - pcm_s24le
  - pcm_s24le_planar
  - pcm_s32be
  - pcm_s32le
  - pcm_s32le_planar
  - pcm_s64be
  - pcm_s64le
  - pcm_u8
  - pcm_u16be
  - pcm_u16le
  - pcm_u24be
  - pcm_u24le
  - pcm_u32be
  - pcm_u32le
  - roq_dpcm
  - adpcm_adx
  - g722
  - g726
  - adpcm_ima_qt
  - adpcm_ima_wav
  - adpcm_ms
  - adpcm_swf
  - adpcm_yamaha
  - libgsm
  - libgsm_ms
  - libmp3lame
  - libopencore_amrnb
  - libopus
  - libshine
  - libspeex
  - libtwolame
  - libvo_amrwbenc
  - libvorbis
  - libwavpack
...
---
formats:
  - a64
  - ac3
  - adts
  - adx
  - aiff
  - amr
  - apng
  - asf
  - ass
  - ast
  - asf_stream
  - au
  - avi
  - avm2
  - bit
  - caf
  - cavsvideo
  - crc
  - dash
  - data
  - daud
  - dirac
  - dnxhd
  - dts
  - dv
  - eac3
  - f4v
  - ffm
  - ffmetadata
  - fifo
  - filmstrip
  - flac
  - flv
  - framecrc
  - framehash
  - framemd5
  - g722
  - g723_1
  - gif
  - gsm
  - gxf
  - h261
  - h263
  - h264
  - hash
  - hds
  - hevc
  - hls
  - ico
  - ilbc
  - image2
  - image2pipe
  - ipod
  - ircam
  - ismv
  - ivf
  - jacosub
  - latm
  - lrc
  - m4v
  - md5
  - matroska
  - matroska
  - microdvd
  - mjpeg
  - mlp
  - mmf
  - mov
  - mp2
  - mp3
  - mp4
  - mpeg
  - vcd
  - mpeg1video
  - dvd
  - svcd
  - mpeg2video
  - vob
  - mpegts
  - mpjpeg
  - mxf
  - mxf_d10
  - mxf_opatom
  - null
  - nut
  - oga
  - ogg
  - ogv
  - oma
  - opus
  - alaw
  - mulaw
  - f64be
  - f64le
  - f32be
  - f32le
  - s32be
  - s32le
  - s24be
  - s24le
  - s16be
  - s16le
  - s8
  - u32be
  - u32le
  - u24be
  - u24le
  - u16be
  - u16le
  - u8
  - psp
  - rawvideo
  - rm
  - roq
  - rso
  - rtp
  - rtp_mpegts
  - rtsp
  - sap
  - segment
  - stream_segment,ssegment
  - singlejpeg
  - smjpeg
  - smoothstreaming
  - sox
  - spx
  - spdif
  - srt
  - swf
  - tee
  - 3g2
  - 3gp
  - mkvtimestamp_v2
  - truehd
  - tta
  - uncodedframecrc
  - vc1
  - vc1test
  - voc
  - w64
  - wav
  - webm
  - webm_dash_manifest
  - webm_chunk
  - webp
  - webvtt
  - wtv
  - wv
  - yuv4mpegpipe
  - chromaprint
  - alsa
  - caca
  - fbdev
  - opengl
  - oss
  - pulse
  - sdl,sdl2
  - sndio
  - v4l2
  - xv
...

------------------------- ERROR 2 ------------------------------
Failed to import 'from openshot.openshot import main'
Error Message: 'NoneType' object has no attribute 'set_cursor'
----------------------------------------------------------------

OpenShot has failed to import some of the Python files or libraries 
required for our application to run.  Here are some trouble shooting
tips:

Tip 1) Check if MLT can be successfully imported in Python.  Run the 
 following commands, and see if any errors are displayed.  If you get 
 an error, you need to investigate the correct way to install MLT.
 NOTE:  Do not type the $ or >> characters in the examples below.

       $ python
       >> import mlt
       >> mlt.Factory().init()

Tip 2) If MLT is working from the first example, then the next tip is 
 to look at the above error messages very closely, and google for more 
 help.  It's likely the problem is already reported, and maybe there is
 a simple work-around.  Also, you can search for bugs or report a new 
 bug at https://bugs.launchpad.net/openshot.  Good luck!
```
**Issue Description and steps to reproduce:**

I don't know what's happens ?? I had try this:
```
~$ python
Python 2.7.13 (default, Nov 24 2017, 17:33:09) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>  import mlt
  File "<stdin>", line 1
    import mlt
    ^
IndentationError: unexpected indent
>>> mlt.Factory().init()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'mlt' is not defined

```

**Comment by peanutbutterandcrackers** [comment]
Good sir, you are using OpenShot 1.x series. Please switch to OpenShot 2.x as that is what this github page is all about. You might want to try out with the [PPA](https://openshot.org/ppa). Hope that helps!

**Comment by rodinux** [comment]
Thanks, but I use Debian and I can not use ppa (Ubuntu required), but I can perhaps try to use the unstable repository for openshot.

**Comment by peanutbutterandcrackers** [comment]
Whoa. A Debian user! Please do provide us with some insights if you do find any bugs. And please also report it to both - the debian bug tracker and us so that both parties can see each other's progress in fixing the bug.

Yes, there is a repo for OpenShot for Debian too. The Debian Multimedia maintainers are taking care of that. I hope you like OpenShot!

**Comment by peanutbutterandcrackers** [comment]
Also, you might want to take a look at the [App Images](https://github.com/OpenShot/openshot-qt/releases/tag/daily)...

**Comment by rodinux** [comment]
I have try with the deb http://www.deb-multimedia.org stable main non-free repository to upgrade, but there was a conflict 
libavcodec-extra57 : Is in conflit with: libavcodec57 but 10:3.3.6-dmo1+deb9u1 will be installed

**Comment by rodinux** [comment]
It is strange, because before this issue, I was abble to use openshot, I think it could be a mistake I have done...

**Comment by peanutbutterandcrackers** [comment]
Whoa: https://tracker.debian.org/pkg/openshot-qt It says openshot-qt is marked for autoremoval on 12 March because of [this](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=890102) bug.

@DylanC, @N3WWN @ferdnyc @jonoomph - I think this deserves some GRAVE attention!!!

**Comment by DylanC** [comment]
@peanutbutterandcrackers - Oh dear. Thats not good. @jonoomph - Can anything be done to help this bug?

**Comment by ferdnyc** [comment]
Sorry, I'm a Fedora user, and I can't reproduce this in either Gnome Shell or LXDE (I don't have an XFCE installation) so it may be a debian build issue. (Though, testing this did lead me to unearth an issue with the rpmfusion packaging for openshot in Fedora, which I was able [to report](https://bugzilla.rpmfusion.org/show_bug.cgi?id=4809).)

Also, I'm not familiar with debian packaging policy, but wouldn't "autoremove" simply remove that _build_ of openshot, and theoretically revert to the previous 2.4.1-1 build? The expanded information there reads (emphasis mine):
> **Version of** openshot-qt is marked for autoremoval from testing on Mon 12 Mar 2018. It is affected by 890102. You should try to prevent the removal by fixing these RC bugs.

 If so, and if that build didn't exhibit the same problematic behavior that 2.4.1-2 did, then that sounds like the correct action until the issue can be addressed.  I mean, it is called "testing" for a reason.

**Comment by rodinux** [comment]
I found how to resolve my issue. It was really more stupid to do. 
`$ sudo apt-get remove openshot python-mlt --purge` 
`$ sudo apt-get install python-mlt`
`$ sudo apt-get install openshot`
`$ mv ~/.openshot/ ~/.openshot-old/`
to let's openshot create a new folder ~/.openshot
[Bug avec Openshot](https://debian-facile.org/viewtopic.php?pid=255462#p255462)
[OpenShot Won't Start - Python MLT Error](https://ubuntuforums.org/showthread.php?t=2081636)

**Comment by ferdnyc** [comment]
Glad you sorted that out! Yeah, if you were previously running OpenShot 1.x, the old configs probably confused it. The 2.x series made a lot of changes. (I know the project file format has changed; any old OpenShot-1.x `.osp` files you may have around unfortunately won't load in 2.x.)

My "can't reproduce" was referring to the external debian bug that @peanutbutterandcrackers pointed to,  
not this bug report, sorry for crossing the streams there. (I still think that "autoremove" status is no cause for alarm, though, as long as it's referring to that particular build instance and not the entire OpenShot package itself. It sounds like they're handing the issue, which sounds like a local build or dependency problem since nobody else has reported it here, on their end.)

**Comment by peanutbutterandcrackers** [comment]
@rodinux - I'm glad that you sorted it out. I hope you make great videos with OpenShot!

@ferdnyc - I hope you're right. But still, if we could figure out a solution, that'd be great. It'd be nice to have OpenShot in the debian repositories... Plus, the debian guys are really known for their rock-solid stability. I really hope they can help us out with the stability issues.

**Comment by peanutbutterandcrackers** [comment]
@rodinux - Good sir, if OpenShot works for you on your debian machine, could you also please help sort out [this](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=890102) bug?
