### ISSUE TITLE
trimming videos

### ISSUE THREAD

**Issue by markobagic** [OpenShot/openshot-qt#1314]
I can only trim a video from the right side and not from the left side.Dont get me wrong;I can OF COURSE TRIM VIDEOS WHICH I PUT ON MY TRACK FROM BOTH SIDES but if I trim it from the left side then there is no green small square in the left down corner of the video(i.e it is lost) which means that if I add another video to this one that the transition between them will not be smooth but actually quite jumpy which is something completely undesirable since I need continuity in my movie which will be marked by Cambridge.I filmed many videos for my short movie so I can somehow combine them to get what I want in my movie but honestly it really makes me stressed that if I trim a video from the left side and combine it with another video that the transition between these 2 will be so jumpy.I GENUINELY BEG YOU to help me and/or tell me how to solve this problem and how to combine 2 videos without losing continuity given that we trim it from the left side and what are your general tips.Thank you﻿

**Comment by peanutbutterandcrackers** [comment]
While I do not fully understand your problem (it would have been easier to if you had a screenshot posted), I am certain that [this](https://www.youtube.com/watch?v=BQS2tmgD_Rk) video will certainly help you figure out what you're trying to achieve.

Also, a side note, the arrowed keys help you move frame-by-frame. Just letting you know.

Hope this helps. Good luck with the video! :)

**Comment by N3WWN** [comment]
The small green markers on the clips are keyframes.  If you can trim your videos before making any other changes, then you shouldn't lose any keyframed properties.

For me, I follow this basic procedure when editing:  Set project profile to match my desired output (this ensures that keyframes are where they need to be when the video is rendered), put clips onto the appropriate tracks, trim them (left & right), align/arrange them, apply any other properties (alpha, fades, mute audio, etc.) and finally add titles.

**Comment by DylanC** [comment]
Closing this question as answered.
