### ISSUE TITLE
Audio cutting out at 2 minutes into video

### ISSUE THREAD

**Issue by bopha99** [OpenShot/openshot-qt#1315]
**System Details:**
* Operating System / Distro:  Windows 10, 64 bit HD
* OpenShot Version: 2.4.1
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

I've made a video with many different clippings from multiple sources.  I then add a song to another track.  By this time my computer is very slow so I go to export the video with the song.  After the video is exported, the song always seems to stop about 2 minutes into the exported video when a new clip starts.  How do I fix this problem so that the song continues to play throughout the whole video?  Thanks in advance.

**Comment by WolfieMar** [comment]
what about me? when i try to make a vid and it hits like 1:30 mark the music stops and video lags. and hen i explort the music just stops.

**Comment by DylanC** [comment]
@bopha99 Can you try v2.4.2 and let us know if you have any success?

**Comment by IzzySoft** [comment]
@DylanC I'm running 2.4.2 on Linux Mint 18.3 (just installed from your PPA today) – and yes, I have the very same problem: regardless of which MP3 file I take, the music stops at 1:49 (guess it depends on some other factors than time, like number of clips or the likes; in my case, it's about the boundary after the 7th clip when counting the opening title as clip). Applies to both, preview and exported video.

If I cut the MP3 about a second before it gets "silenced", audio starts to rattle at that point. Could not do closer tests as it seems my machine is too low-spec (Dual-Core AMD A4-3400 at 2.7GHz with 8G RAM), so even the preview stutters.

Side-Note: Even when previewing the MP3, sound output stops at the very same place. Just did a fresh start of OpenShot, only imported the audio – et voila, same thing again at exactly the same place; so my above guess must be wrong.

My current work-around is using `mp3splt` to split the sound file into pieces slightly shorter than the "critical number" – but of course I'd prefer not to be bound to that, as it a.o. leaves a bunch of additional files cluttering around.

With the bug still there, may I suggest to reopen this issue?

**Comment by DylanC** [comment]
@IzzySoft - Maybe try v2.4.3 first and let me know if you still have a problem.

**Comment by IzzySoft** [comment]
@DylanC I would, but it's not yet in the PPA. OpenShot shows me there's an update available, so I assume it has been released – but apt cannot yet find it.

**Comment by DylanC** [comment]
@IzzySoft - That sounds positive. The PPA will have a delay before getting an update as far as I know.

**Comment by ferdnyc** [comment]
Logs. Logs, logs, logs. See [CONTRIBUTING.md](https://github.com/OpenShot/openshot-qt/blob/develop/CONTRIBUTING.md) for instructions. That document says to download the daily build, but the collection procedure is the same for installed versions.

(Don't overlook the part in CONTRIBUTING step 3, about deleting the existing logs before you start.) 

Ideally you'd want to reproduce both sides of the issue as concisely as possible:
1. Launch OpenShot
2. Add the audio clip to the Timeline
3. Activate the preview, and stop once it encounters playback issues (after a few seconds)
4. Perform an export that results in a bad file
5. Exit OpenShot

The log files will be huge as it is in debug mode, so if you can reproduce the issue with as little unrelated activity as possible it'll be a big help.

**Comment by IzzySoft** [comment]
@ferdnyc I happily oblige as soon as 2.4.3 is available in the PPA (which currently still has 2.4.2 as most recent) and the issue still persists. As I wrote, the issue does not exist in the 2.4.3 AppImage – so either it's solved, or some library is the culprit. No need to bloat it it's solved :wink:
