### ISSUE TITLE
Capture video from DV cassette from camcorder using fire wire.

### ISSUE THREAD

**Issue by DaveR121** [OpenShot/openshot-qt#1316]
Can anyone please assist.

I just downloaded the latest version of OpenShot, but can't find a way to capture/import video straight from camcorder.

I'm using mac version 10.0.5.

My reason for downloading OpenShot is because I'm having trouble capturing from iMove (keeps quitting in middle of capture). And I don't really like the new version of iMovie.

Thanks
Dave

**Comment by peanutbutterandcrackers** [comment]
@DaveR121 - Sorry, good sir. But OpenShot does not yet have that functionality. Maybe in the future, we might have that. But not right now. Sorry.

But it seems that you can use [VLC Media Player](https://www.videolan.org/vlc/index.html) to do it. It is a free and open source media player and is really powerful. Here are some helpful links:
https://forum.videolan.org/viewtopic.php?t=84846
https://forum.videolan.org/viewtopic.php?f=2&t=86469
https://forum.videolan.org/viewtopic.php?t=116875 (If there are any problems with interlacing. Disclaimer: I didn't even check how the discussion goes, so sorry if this doesn't help)
https://forum.videohelp.com/threads/361335-Capturing-video-from-Camcorder

I hope that helps! Please do let us know how it goes.

**Comment by DaveR121** [comment]
Thank you very much for your reply.
Best regards
Dave

**Comment by peanutbutterandcrackers** [comment]
@DaveR121 - You're most welcome. I hope you can capture video from your DV Camcorders using VLC. Please do continue to love, support and use OpenShot! :)

**Comment by Rnicoletti1967** [comment]
Please, if I capture videos by VLC then I can edit videos with OpenShot ? and can I burn DVD using Openshot ? thanks.

**Comment by peanutbutterandcrackers** [comment]
@Abacab7711 - I don't think you actually need his permission to go ahead and fix it, good sir. It happens all the time here, and in other repos, where one user would open up an issue (say, 'Need frame-capture feature') and another one would come around and make a PR that says "fixis issue no #zyx that said "need frame-capture feature". That is the great thing about Free/Libre Software. :)

@Rnicoletti1967 - Yes, you can edit the videos using OpenShot. If you run into issues, you could always transcode your VLC-captured footage to something like `.mkv` using [HandBrake](https://handbrake.fr/). For DVD burning, you might want to use something like [DVD Styler](https://www.dvdstyler.org/en/) or [Open DVD Producer](http://opendvdproducer.jonata.org/). OpenShot is not able to burn DVDs yet. And I highly doubt it ever will, as DVDs are falling out of favour, and more importantly, there's this philosophy in the GNU/Linux World that you should have your program do one thing and one thing only and make your program do said thing really well. OpenShot still needs to focus on doing the one thing it does well, and we are still working on that... Hope that makes sense.
