### ISSUE TITLE
High CPU High Memory

### ISSUE THREAD

**Issue by trash70** [OpenShot/openshot-qt#1317]
i7-4770 @ 3.4GHz . 16gb ram
Win 7 all updated
* OpenShot Version: 2.4.1

No matter what i'm doing in OpenShot my CPU is in the high 70's and Memory is nearly 2 million .
Stutters , freezes ,i wait , make a move repeat .
 This is with next to nothing running , I tried setting CPU to affinity and real time  and it did nothing .
Any ideas what's going on ? thanks for your time .

**Comment by peanutbutterandcrackers** [comment]
OpenShot currently does seem to have problems with windows, while it works on Linux pretty well. However, many windows users have used the software and it seems to work well for them too. I don't really know...

I hope someone is able to help you soon. I'm sorry but I don't really use windows...

Even if this version doesn't work, please do look forward to updates. :)

**Comment by DylanC** [comment]
@trash70 Can you try v2.4.2 and let us know if you have any success?
