### ISSUE TITLE
animated titles don't work

### ISSUE THREAD

**Issue by bell18** [OpenShot/openshot-qt#1318]

**Comment by peanutbutterandcrackers** [comment]
You will have to provide a little more details for the community members to be able to help you. Perhaps you haven't installed blender. Or, maybe you need to set the correct blender path. The thing is, for the animated titles, OpenShot uses blender - the free and open source 3d modelling software.

**Comment by DylanC** [comment]
You need to set the correct Blender path in the preferences. Check the closed issues related to blender. This question has been answered many times. Closing this as the question has been answered.
