### ISSUE TITLE
MP4 video choppy

### ISSUE THREAD

**Issue by stuartd99** [OpenShot/openshot-qt#1321]
Mac 10.10

MP4 video playback inside OpenShot - and in rendered MP4 file - is choppy.

Original MP4 footage is 23.98 and I'm using a matching profile.

**Comment by peanutbutterandcrackers** [comment]
@EmptyVessel-NZ - Good sir, could you perhaps help @stuartd99 out, please? You use a mac, too, right?

@stuartd99 - OpenShot does work on a mac, though. [This](https://github.com/OpenShot/openshot-qt/issues/1309) was a recent post here on the issues section. Just letting you know. :)

**Comment by DylanC** [comment]
@stuartd99 Can you try v2.4.2 and let us know if you have any success?
