### ISSUE TITLE
Is There a Way On How To Export Faster?

### ISSUE THREAD

**Issue by WolfieMar** [OpenShot/openshot-qt#1324]
Is There a Way To Make Video's Export Faster? Because The Speed For Video's To Export Takes Too Long!

**Comment by DylanC** [comment]
@WolfieMar - A faster computer or lower the quality settings.

**Comment by peanutbutterandcrackers** [comment]
@DylanC - haha that's funny but true.

@WolfieMar - Perhaps have OpenShot as the only major running process? i.e. don't have web browser open while rendering. Have as much CPU for OpenShot to spare? Maybe that'll help?
