### ISSUE TITLE
Exporting video crashes Openshot at 59%

### ISSUE THREAD

**Issue by deuZige** [OpenShot/openshot-qt#1326]
**System Details:**
* Windows 10/64 ?
* OpenShot Version: 2.4.1

* _Please attach log files if crash_ 
Where are the stored?

After spending hours to create an acceptable video (for my talents and skills) i wanted to export the video for uploading to (for example) youtube. At first at default settings but later i found out it didn't matter. It simply crashes at 59% no matter what resolution, codec or any other setting parameter i use.

Those hours i spent making the video aren't lost i hope. I'd rather have them back if they are.

**Comment by peanutbutterandcrackers** [comment]
@deuZige - Good sir, sorry for the inconvenience. I hope someone will be able to help you. This is a community backed project and it's us helping each other out. Perhaps someone will get to you on this, soon. Hopefully.

@WolfieMar - Could you perhaps help out with this issue too, since you are also using Windows 10?

@DylanC - Similar to #1323? and #1203? #1137?

**Comment by feliperodriguesap** [comment]
Também estou com esse mesmo problema, passei horas editando e quando fui exportar deu erro, já tentei de todos os formatos mas não dá certo, sempre da erro.

**Comment by peanutbutterandcrackers** [comment]
@feliperodriguesap - Are you using windows? Could you perhaps also try out the [daily builds](https://github.com/OpenShot/openshot-qt/releases/tag/daily) and see if that works out for you?

**Comment by feliperodriguesap** [comment]
@peanutbutterandcrackers - I use windows 10

**Comment by peanutbutterandcrackers** [comment]
@feliperodriguesap - Then I recommend trying out one of the [daily builds](https://github.com/OpenShot/openshot-qt/releases/tag/daily) to see if that works. v2.4.1 does not seem to work that well with Windows. However, a user recently did report that the daily build worked quite well for him. Perhaps you will have luck with it, too? Or else, I'm afraid you'll have to wait for further daily builds or for v2.4.2 (which will come with a ton of fixes and enhancements). Hope that helps.

**Comment by HooterLooper** [comment]
I got the same issue and want to try daily builds as you said but I don't really understand how I have to install it ? Could you help me ?

**Comment by peanutbutterandcrackers** [comment]
@HooterLooper - To make it even simpler for you, go to the OpenShot site's [download section](https://www.openshot.org/download/), click on daily builds, and click on Windows. Download the one at the top of the list (or there-abouts) and you should be ready to go.

Daily build means an installable version of the software made daily (actually, whenever a change is made in the source code). And next to the item there on the download list, you can even see when it was 'built'. Hope that clears things up for you. :)

Good luck with OpenShot!

**Comment by rolandh** [comment]
I get 100% crashes at about 80% exporting any x264 format video. Other formats are ok

**Comment by rolandh** [comment]
Downgrading to version 2.1 and it now exports fine
