### ISSUE TITLE
Request for New Target: Chromebook

### ISSUE THREAD

**Issue by gary9872** [OpenShot/openshot-qt#1329]
I was helping out someone recently with some video work and they presentations were at school. Neither of the two projects worked (the audio). The culprit was the chromebooks, which was the standard I believe throughout that entire school system.

So to that end I am requesting to add Chromebook  under Device > Target >

using webm VP8 or VP9 for video, and Vorbis for audio as per google support page.

https://support.google.com/chromebook/answer/183093?hl=en

If you like I can submit a diff patch against 2.4.1 or git for it 

Thanks,

Gary

**Comment by peanutbutterandcrackers** [comment]
@DylanC - I think you should take a look at this. He has made an offer we can not refuse.

@gary9872 - Hey! Thanks! I'm so glad that you are helping OpenShot become a better Video Editor. Please do stick around and help us out with other bugs and stuffs too. We need more developers here. Currently, it's just Mr. Thomas alone. We really appreciate the help. :)

**Comment by DylanC** [comment]
@gary9872 - If you could submit a PR that would be great! Might take a while to get it reviewed but at least it will get in after a while.

**Comment by peanutbutterandcrackers** [comment]
Yeah! You go, @gary9872 !!! :smile:

**Comment by gary9872** [comment]
Add to openshot-qt/src/presets directory

chromebook.xml

https://pastebin.com/G6sHeCRh

**Comment by peanutbutterandcrackers** [comment]
@gary9872 - Actually, if you could make a PR, that would probably land you a credit (at least in the git logs) of doing so... Are you sure you do not want to make a PR?

Also, could you please, if you decide to make a PR, take care of #201 ?

Thanks!

**Comment by DylanC** [comment]
I'm adding the file here in case the pastebin disappears or anything like that. (Note its supposed to be just .xml but for uploading purposes I added the .txt to the end.
[chromebook.xml.txt](https://github.com/OpenShot/openshot-qt/files/1784099/chromebook.xml.txt)

@peanutbutterandcrackers - I can do a PR for this if you like.

**Comment by peanutbutterandcrackers** [comment]
@DylanC - Well, if @gary9872 does not want to, then please, by all means. :)
Would you like to take care of #201, too, please?

**Comment by DylanC** [comment]
@peanutbutterandcrackers , @gary9872 - PR added. I should be able to get around to #201 too.

**Comment by peanutbutterandcrackers** [comment]
@DylanC - Awesome!

@gary9872 - I hope you stick around and make some PRs too, good sir!
![25vxxj](https://user-images.githubusercontent.com/26764547/37073133-20397a06-21ed-11e8-97b0-fab1f531b838.jpg)

**Comment by DylanC** [comment]
Closing since this fix has been merged in.
