### ISSUE TITLE
Audio issues on exported video when two tracks are overlaid

### ISSUE THREAD

**Issue by mallardtheduck** [OpenShot/openshot-qt#133]
Steps to reproduce:
1. Create a new project.
2. Add two audio files, both starting at zero and overlapping (on separate OpenShot tracks).
3. Export the video.
4. On playback (of the exported video), lots of audio clipping and popping is apparent. This does not occur when previewing in OpenShot.

Example project attached.

[Audio Test.zip](https://github.com/OpenShot/openshot-qt/files/185914/Audio.Test.zip)

**Comment by kpuljek** [comment]
I have the exact same problem

**Comment by edwin-oetelaar** [comment]
confirmed : https://www.youtube.com/watch?v=uvZDinEtTmo
I think it was not happening a year ago.

**Comment by djbarker** [comment]
I too am suffering from this issue. It's a show stopper for me unfortunately, who wants a video with broken sound? Shame as otherwise Openshot seems nice (albeit a bit slow).

**Comment by theManintheMoon** [comment]
I'm having a 'Mee-Too' moment; trying to export Video-Only, No Sound and am getting a pop or (it's a bit hard to descibe...) "wuhmph!" when the project has a transition from one track to another. btw- it's July, 2017.

PS- I'm running Openshot 1.4.3, default install from within Ubuntu Studio 17.10 (artful).

**Comment by DylanC** [comment]
@mallardtheduck - I will be closing this issue for now. We will be taking on bugs related to the 2.0 series of OpenShot. The development of 1.0 series has stopped. 

If you find the same issue in the new version please log a new issue or reopen this stating the issue persists in the latest version.

Thank you.
