### ISSUE TITLE
cx_Freeze: Python error

### ISSUE THREAD

**Issue by raz5652** [OpenShot/openshot-qt#1330]
Windows 10 (64)
OpenShot-v2.4.1-x86_64
Keep getting a cx_freeze error on the first launch after installation. uninstalled cleared registry and reinstalled but same error.

**Comment by peanutbutterandcrackers** [comment]
Please try deleting the .openshot_qt folder in your home directory.
If that does not work, please try logging in with a different user to run OpenShot --- perhaps as the admin or sth.
Many users have reported that doing this has resolved the issue.
Hope this helps!

**Comment by raz5652** [comment]
what does home directory means? c:/ drive where the windows is installed. no openshot_qt folder there or any where else i cant see. Running as admin dosnt work aswel
![screenshot 2](https://user-images.githubusercontent.com/37027061/36942434-137ccb1e-1f69-11e8-8d5b-72cf9286760e.png)

**Comment by peanutbutterandcrackers** [comment]
Home directory is the folder where your 'My Documents', 'My Pictures' etc are located.
Hope that helps!
:smile:

**Comment by raz5652** [comment]
Yes, unders users folder.. thankyou that worked

**Comment by peanutbutterandcrackers** [comment]
You are most welcome!
Hope you create awesome videos with OpenShot! :)

**Comment by DylanC** [comment]
@raz5652 - Great news. Thanks!
