### ISSUE TITLE
How to trim/ remove the first part of my video

### ISSUE THREAD

**Issue by johnpdolden** [OpenShot/openshot-qt#1331]
**System Details:**Lenovo Z580 64
* Operating System / Distro: ? Windows 10
* OpenShot Version: ? 2.4.1
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
I have an MP4 file from which I am trying to trim off the first 12 minutes. I am struggling to see how to achieve this. Any help would be gratefully received
regards
John.

**Comment by DylanC** [comment]
Closing this as the question has been answered.
