### ISSUE TITLE
Version 2.4.1 so slow virtually unusable

### ISSUE THREAD

**Issue by tjsepka** [OpenShot/openshot-qt#1333]
64 bit Windows 10 Pro version 1709 (OS Build 16299.248)
Asus M5A99FX Pro R2.0 othererboard
AMD FX-8350, eight core processor, 4.33 GHz
16 Gbyte G.Skill DDDR-3 memory
XFX Radeon RX-460P4T video card, 4 Gbyte

Hard drives:
KINGSTON SV300S37A240G 240 Gbyte solid state (C: - operating system drive)
(2) Seagate ST1000DM010-2EP102 1 Tbyte drives

Project is as follows:
Track 0 contains two 3:30 minute mp3 audio files
Track 1 contains a ~80 jpg images ranging from 30 kbytes to 3.9 Mbytes, with a 4 second image length arranged sequentially end-to-end.

It takes MINUTES to add a image file to the time line.  It takes minutes after clicking a timeline object before you can do anything with it (hourglass).

Windows often says the program is not responding.  The launch.exe process often consumes 12.5% CPU time which is 1/8 of the 8 core processor.

Watching what happens with Sysinternals process monitor reveals significant processor time being spent in msvcrt.dll.  Screenshot here:

![image](https://user-images.githubusercontent.com/30416148/36948501-79371922-1fa1-11e8-838c-c5ae3eeda4a3.png)

**Comment by peanutbutterandcrackers** [comment]
@tjsepka - Good sir, the devs have been notified about this bug. Hopefully, this will be fixed in v2.4.2. Please do look forward to it! :)

**Comment by AlyssaDiPaolo** [comment]
When will v2.4.2 be released? I'm having the same issues with Openshot just being completely unusable. It freezes and is unresponsive with every edit I make. I cannot make anymore progress on my project until this is fixed. If the update isn't released soon, I might as well use a new video editor because I would be able to remake my project before then.

**Comment by peanutbutterandcrackers** [comment]
Could you please try out the [latest daily builds](https://github.com/OpenShot/openshot-qt/releases/tag/daily) and see if that works for you. It will be updated within 24 hours of changes made to the OpenShot source. That should help you out...

OpenShot v2.4.2 might be at least a month away. At least.

Sorry, but this is the labor of love of a single man, with help from the community that supports him... That is why OpenShot can't be as quick with it's releases as other commercial products...

I hope your problem will be fixed soon. This has already been reported as a high priority issue and hopefully will be fixed really soon...

**Comment by itschris2003** [comment]
It'd better be. I can't open my project because openshot just freezes so I'm stuck...

**Comment by peanutbutterandcrackers** [comment]
It will get better, good sir. But it will take time. Sorry for the inconvenience caused.

**Comment by DylanC** [comment]
@tjsepka - The daily builds use all cores, so I suggest you try a daily build for your system or wait until v2.4.2 is released. Thanks.
