### ISSUE TITLE
Projects not portable to another machine

### ISSUE THREAD

**Issue by tjsepka** [OpenShot/openshot-qt#1334]
OpenShot version 2.4.1
64 bit Windows

I copied the entire contents of a project file to another machine,  Loading the project says it is missing file clips for every clip.

See here:

![image](https://user-images.githubusercontent.com/30416148/36948635-5fb5737a-1fa3-11e8-9d1d-55bbae875e4e.png)

**Comment by peanutbutterandcrackers** [comment]
@tjsepka - Currently, OpenShot does not have the feature for portable projects. This will, hopefully, be implemented in the near future. Sorry for the inconvenience.

@DylanC - Dup of #988
