### ISSUE TITLE
Images rotated when adding to timeline

### ISSUE THREAD

**Issue by tjsepka** [OpenShot/openshot-qt#1335]
64 bit Windows 10 Pro version 1709 (OS Build 16299.248)
OpenShot version 2.4.1

I have images that were rotated and saved to their proper orientation prior to loading them into OpenShot.  They appear properly in Windows file explorer and other software (such as IrfanView, which I used to rotate the image) and any other software that I use to view images.

I don't know why OpenShot does this, nor is there any way to rotate them into their proper orientation when trying to add them to a timeline.

**Comment by peanutbutterandcrackers** [comment]
Could you please try adding the original picture into OpenShot.

It might be related to the meta-data of the image. I wonder if using another tool like GIMP to do the rotation would fix it. Maybe the software you used for rotation doesn't handle the rotation correctly, or maybe messes up setting the meta-data. And perhaps using GIMP will fix it.

Just a thought. Hope that helps!

P. S: I did try rotating a png screenshot I had and it worked pretty well. I used [GIMP](http://gimp.org/).

**Comment by peanutbutterandcrackers** [comment]
Also, you can rotate an image/clip on the timeline by right-clicking it > Rotate > Rotate *degrees*, too.
