### ISSUE TITLE
Exported movie has freezed frames

### ISSUE THREAD

**Issue by marecl** [OpenShot/openshot-qt#1338]
Win 10
OpenShot 2.4.1

Exported video (mp4 and avi all variants) is fine to about 50%. Playback is fine to mentioned 50%, then it's just one frame which lasts to the end of video. Audio was disabled, video cut and speeded up dusing edit.

**Comment by DylanC** [comment]
@marecl Can you try v2.4.2 and let us know if you have any success?

**Comment by marecl** [comment]
I'm not working with video files anymore and I'm on a trip now but will check as soon as I get back home.
