### ISSUE TITLE
Confusing Properties Labels

### ISSUE THREAD

**Issue by musikidd** [OpenShot/openshot-qt#1339]
**System Details:**
* Operating System / Distro: Win 10
* OpenShot Version: 2.4.1
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

First time user, and I'm trying to manually manipulate the timing of titles over a video using the Properties widget, and I'm messing with `Duration`, `End`, `Start`, `Time`, only to eventually discover that Position was the property I needed to adjust to change the start time!

What were the others for then? `Duration` is uneditable, but `End` is, and it has the same value, AND if you change `End`, `Duration` changes as well.  Huh????

Searching in the docs for `Properties` and `Duration` yields nothing, and pages that 'start', 'end', and 'time' appear on don't speak to the same list of properties.

I suggest tooltips for the label column in addition to updating the documentation..

**Comment by peanutbutterandcrackers** [comment]
@DylanC - Any thoughts regarding this? o.O I think this is a really good suggestion. Tooltips would be great!

**Comment by DylanC** [comment]
@peanutbutterandcrackers - I think its the documentation needs to be updated but yeah maybe tooltips would be cool.
