### ISSUE TITLE
Openshot running slow

### ISSUE THREAD

**Issue by odin24seven** [OpenShot/openshot-qt#1340]
**System Details:**
Intel I7 8700k
Asus z370-e motherboard
Corsair Dominator DDR4 16 2 x 8 gb 3000
GTX 1080 Ti 11 gb GDDR5X
Samsung 840 pro SSD
* Operating System / Distro: ?
Windows 10 newest updates
* OpenShot Version: ? 2.4.1
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
very slow to cut up video and rearrange video. changing from video to wave is slow. It wont let me drag media in to openshot anymore i have to do it from import file and it feels like it gets slower the more i use it. is there anything i can do to fix this

**Comment by peanutbutterandcrackers** [comment]
@odin24seven - Good sir, this has already been brought to the developers attention. Hopefully, all of these issues will be resolved by v2.4.2. Please do look forward to it.
This seems to be windows-specific. OpenShot works pretty well on Linux Machines... And the developers are working to sort it out.
Sorry for the inconvenience...

**Comment by creeeeek** [comment]
For info only:
Just thought I would add to this, this is the first I have tried openShot and the tutorials looked amazing, I have a Intel i5 @2.67 Ghz, 4gb RAM. Windows 10 64 bit. I was about to try my old program (VideoStudio x6) I always used on Windows 7 and I thought I would check out the forum, and great that it is a known problem, I will wait before uninstalling :)
Thanks

**Comment by ursusbruno** [comment]
Version: OpenShot-v2.4.1-8-g3accac8-57-666-x86_64 working way better!!!
Good job!

**Comment by DylanC** [comment]
@peanutbutterandcrackers - Can I close this one?

**Comment by peanutbutterandcrackers** [comment]
@DylanC - Perhaps we should wait to hear from @odin24seven, Cap'ain? But if there is no interest from the reporter, then perhaps, yes sir!

**Comment by DylanC** [comment]
@peanutbutterandcrackers  - No problem. I will wait a bit. :)

**Comment by odin24seven** [comment]
Sorry I haven't checked my email in awhile. I will try the ver. You
mentioned and give you some more feedback in a week. Thanks for getting
back with me.

**Comment by peanutbutterandcrackers** [comment]
@odin24seven - Awesome! Hope it works well for you!

**Comment by DylanC** [comment]
@odin24seven - Any news on this?
