### ISSUE TITLE
Jerky audio on preview

### ISSUE THREAD

**Issue by Peter111160** [OpenShot/openshot-qt#1342]
I have problems with audio on preview. It sounds jerky, but the video preview is ok. I found the recommendation to use ogg vobis instead of mp3 audio and tried that, but this doesn't help.

I'm working with a Lenovo Thinkpad T460, Ubuntu 17.10, Openshot 2.41 / Openshot 2.41-16 (both with the same effect). In Openshot 1.43 it worked fine (although I can't verify that now, because the osp-file can't be loaded into the old openshot version).

Any ideas, how I can fix this?

Best regards, Peter

**Comment by peanutbutterandcrackers** [comment]
I was able to edit with okay preview yesterday on my friend's machine. Maybe it has something to do with your specs? Just a thought. But I wonder if this can be reproduced...

But the good thing is - it's just preview. The rendering will be fine no matter what. So, if you can ignore that, for now - till it is fixed. It should export pretty well at the end. :)

My friend's machine specs:
![screenshot from 2018-03-07 10 18 27](https://user-images.githubusercontent.com/26764547/37073767-064f9aea-21f1-11e8-8d5e-937478501ef0.png)

**Comment by Peter111160** [comment]
Thanks for your answer - and you're right, the rendering works perfect. That is, what's count! 
By the way: how do you produce the specs output in your screenshot? Don't know a linux command, which produce such a nice and brief summary ...

**Comment by peanutbutterandcrackers** [comment]
@Peter111160 - It is `$ screenfetch`, good sir. `sudo apt install screenfetch`
I hope you continue to support OpenShot and provide us with other reports/issues/suggestions... maybe even patches to fix bugs. Thank you! You're awesome!

P. S: If this issue has been resolved, please do not forget to close it. Thank you! :)

**Comment by Peter111160** [comment]
@peanutbutterandcrackers - thanks so much for your assistance. I love OpenShot a lot - it's easy to produce really nice Video-Clips :-) !! I will, for sure, support OpenShot in the future, although I'm unfortunatelly not able to program patches ...

Attached you will find my specs: Do you see any reason for the problems I have?

![bildschirmfoto von 2018-03-08 10-14-58](https://user-images.githubusercontent.com/28689016/37143119-76d5af42-22ba-11e8-9a48-8a528dd0599e.png)

**Comment by peanutbutterandcrackers** [comment]
@Peter111160 - Whoa. That's a really nice computer you have got there. I think it has something to do with the fact that you're using Ubuntu 17.10 which uses wayland as it's display server protocol instead of X? Perhaps? Or maybe not?

OpenShot, too, is not yet quite mature enough - the code base. So, that might be another factor too.

Another factor might be the audio file format that your audio clip uses...

But please do look forward to the future versions, good sir. OpenShot will evolve for the better - if we all help the project out. :)

**Comment by Peter111160** [comment]
@peanutbutterandcrackers - Thanks for all your assistance!! I'll close the issue now ...

**Comment by peanutbutterandcrackers** [comment]
You're most welcome! I think more commits will be made to libopenshot-audio (OpenShot's audio framework) and hopefully, we'll soon reach a day of virtually flawless preview playback in OpenShot -- both audio and video.

Hope you make awesome videos with OpenShot! :)
