### ISSUE TITLE
stops on preview and most of the when it starts everying is black

### ISSUE THREAD

**Issue by Baker6** [OpenShot/openshot-qt#1345]
**System Details:**
* Operating System /windows 10  I7 with 1070 card: 
* OpenShot Version: ?  2.41
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**stops on preview and most of the when it starts everything is black, same thing when you right click on clip  to spilt the frames

**Comment by peanutbutterandcrackers** [comment]
Could you please try out the latest [daily build](https://github.com/OpenShot/openshot-qt/releases/tag/daily) and see if the issue persists even there? o.O

**Comment by DylanC** [comment]
@Baker6 Can you try v2.4.2 and let us know if you have any success?
