### ISSUE TITLE
Video background change

### ISSUE THREAD

**Issue by ksmolko1000** [OpenShot/openshot-qt#1352]
**System Details:**
* Operating System / Distro: Windows 7 Home Premium
* OpenShot Version: 2.4.1
* _Please attach log files if crash_

Ok so I have a question, Imagine we have video with 2 people and for example woods background. How can I change only the background? I want these 2 people to be somewhere else, but in woods.
Please help me

**Comment by gary9872** [comment]
https://www.youtube.com/watch?v=Hd9k3x0diOo

**Comment by peanutbutterandcrackers** [comment]
@gary9872 - Hey there! Good to see you helping out here. Thank you. :)

@ksmolko1000 - So, in this case, you should probably use alpha masks like Mr. Gary has pointed out. However, the next time around you want to change backgrounds, I suggest you use [chroma-keying (Green/Blue Screen)](https://www.youtube.com/watch?v=2sushecqMs4&t=24s) instead.

P. S: Those videos are made by the creator and lead developer of OpenShot, Mr. Jonathan Thomas, himself. :)

**Comment by ksmolko1000** [comment]
Thanks for your help guys ;-)

**Comment by peanutbutterandcrackers** [comment]
You're most welcome. Please do not forget to close the issue if it has been resolved. Thanks!

**Comment by DylanC** [comment]
@peanutbutterandcrackers - I'll mark as resolved for him/her.

**Comment by peanutbutterandcrackers** [comment]
@DylanC - Aye, aye, Cap'ain! :smile:
