### ISSUE TITLE
Preview Volume and Speed Issue

### ISSUE THREAD

**Issue by westernnativevoice** [OpenShot/openshot-qt#1353]
Hi there. I'm working on a project and the preview window makes the playback very fast and with no sound. Is there a fix?

**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

**Comment by peanutbutterandcrackers** [comment]
That is quite strange. Which platform are you on, good sir?
Also, can you try exporting the video from OpenShot? Perhaps the exported video will come out just fine. Previews are often like that.
Could you also provide us what type of video and audio you are using? A .MOV? a .m4a? That could help us help you. [This is just a community that scratches each other's backs.] :)

**Comment by DylanC** [comment]
@westernnativevoice Can you try v2.4.2 and let us know if you have any success?
