### ISSUE TITLE
Docs: Use semantic markup where appropriate

### ISSUE THREAD

**Issue by ferdnyc** [OpenShot/openshot-qt#1354]
A proposal for changes to the documentation, with examples as requested by @peanutbutterandcrackers.

ReStructuredText (the documentation source format) supports semantic markup ("roles" in RST parlance) for certain text, including: keyboard combinations (`:kbd:`), menu items (`:menuselection:`), GUI elements (`:guilabel:`), and file paths (`:file:`). These are converted to various HTML tags and classes, which can then be further customized by adding CSS styling to the generated output.

### Main Window
As an example, a section of the Main Window chapter (compare to the [online version](https://www.openshot.org/static/files/user-guide/main_window.html)):

![screenshot from 2018-03-09 17-58-57](https://user-images.githubusercontent.com/538020/37234859-436141c6-23c8-11e8-9297-b05ab0bcb2d5.png)

#### Keyboard Shortcuts
And the Keyboard Shortcuts list (bottom of same page) becomes:
![screenshot from 2018-03-09 17-58-28](https://user-images.githubusercontent.com/538020/37234871-54fe5d7e-23c8-11e8-9606-01dd2d59ba0e.png)

##### Source code changes
The source code for the shortcuts table gets converted to a `.. list-table::`, and becomes:
```rst
.. list-table::
   :header-rows: 1
   :widths: 15 20

   * - Shortcut
     - Action
   * - :kbd:`Ctrl` + :kbd:`H`
     - About OpenShot
   * - :kbd:`Ctrl` + :kbd:`M`
     - Add Marker
   * - :kbd:`Ctrl` + :kbd:`Shift` + :kbd:`T`
     - Add Track
   * - :kbd:`Ctrl` + :kbd:`W`
     - Add to Timeline
   * - :kbd:`Ctrl` + :kbd:`B`
     - Animated Title
   * - :kbd:`Ctrl` + :kbd:`P`
     - Choose Profile
   * - :kbd:`Ctrl` + :kbd:`C`
     - Copy
[..etc...]
```

This is due to the impracticality of embedding strings like `` :kbd:`Ctrl` + :kbd:`Shift` + :kbd:`T` `` into the original source formatting:
```rst
==================  ============
Shortcut            Action
==================  ============
Ctrl+H              About OpenShot
Ctrl+M              Add Marker
Ctrl+Shift+T        Add Track
Ctrl+W              Add to Timeline
Ctrl+B              Animated Title
Ctrl+P              Choose Profile
Ctrl+C              Copy
```

### Titles

As a longer sample, here's the entire Titles chapter (again, compare to the [online version](https://www.openshot.org/static/files/user-guide/titles.html)):

![screenshot from 2018-03-09 18-14-09](https://user-images.githubusercontent.com/538020/37235079-c344963a-23c9-11e8-8635-960540625542.png)
![screenshot from 2018-03-09 18-14-38](https://user-images.githubusercontent.com/538020/37235083-c5c4823a-23c9-11e8-9430-06224b016855.png)

### Styling

As far as styling goes, we have a **lot** of control over how things are formatted, because now they're marked up with HTML classes that can be styled via CSS. I already added the styling for the keyboard keys, by default Sphinx outputs them as a `PRE`-class span, which colors the text red (same as file paths). I thought that looked awful, so I renamed the `tablefix.css` file I'd already created to `openshot.css` and added the following:
```css
/* Add boxed "keycaps" styling for keyboard combos */
code.kbd {
  border-radius: 3px;
  padding: 3px 4px 1px;
  border: 1px solid #777;
}
code.kbd span.pre { color: black; }
```

I also added the accelerator underlining (the reason the S is underlined in the "Save" button), which by default the ReadTheDocs theme hides, even though Sphinx generates the appropriate markup.

I don't personally love the styling for menu selections, as I think they blend into the text a little **too** well. But, if we wanted to bold them (as the "hand-styled" versions are in the original text, compare "**Help→Tutorial**" in the online version to my screenshot), then doing so is as simple as adding a line to `openshot.css`:
```css
.menuselection { font-weight: bold; }
```

**Comment by peanutbutterandcrackers** [comment]
@ferdnyc - Awesome! I have to admit, I kinda' like this one better.
However, although I do see that the formatting makes clear that the thing being explained is a button, in the 'titles' and '3d animated titles' section, the 'render' and 'save' being in the box thingy while the others not, does look a tiny bit strange. Just a personal opinion. But I love that they can be clearly seen as being buttons. Perhaps changing the color for those a little bit (a little lighter/darker shade for the enclosing) would make it blend well? Just a thought.

You're like the Doctor of the Docs. You always find ways to make things even better. Awesome!

**Comment by ferdnyc** [comment]
No, I completely agree, the `:guilabel:` styling looks like... well, it looks awful. That's part of what annoys me about the `:menuselection:` styling — one is so understyled it almost completely blends in to the text, while another is styled so garishly as to pull you right out of what you're reading. (I actually think `:guilabel:` is even _worse_ when it's used in the prose, like the "**Next**" in the very first screenshot. Completely distracting.)

The blue coloring seems to be part of ReadTheDocs' "theme", such as it is... they're big on blue. But we're not stuck with any of it, thanks to CSS. I _could_ even style the GUI elements to look almost **exactly** like OpenShot's actual interface buttons, with white text on a dark gray background... but I suspect that'd be a mistake, in the documentation. I'll try to find some middle ground that at least loses that stupid blue.

**Comment by peanutbutterandcrackers** [comment]
I'm pretty sure you'll figure something out. You always do. :)
