### ISSUE TITLE
Audio Glitch

### ISSUE THREAD

**Issue by MrTertius** [OpenShot/openshot-qt#1356]
System Details: Intel i5 Processor, Integrated GPU, 4GB RAM
Operating System / Distro: Windows 10
OpenShot Version: 2.4.1

Please attach log files if crash
Program has not crash once

Issue Description and steps to reproduce:
Audio plays normally when Timeline Playhead has been moved back on timeline

**Comment by peanutbutterandcrackers** [comment]
I think you pressed enter a little too soon, good sir. I don't really understand the issue. Could you please explain it more? Thanks!

**Comment by DylanC** [comment]
Closing until we have more details or screenshots.
