### ISSUE TITLE
Video Jumps

### ISSUE THREAD

**Issue by MrTertius** [OpenShot/openshot-qt#1357]
**System Details: i5 Intel Processor, Integrated GPU, 4GB RAM
* Operating System / Distro: Windows 10
* OpenShot Version: 2.4.1
* _Please attach log files if crash_
No Crashes At All
**Issue Description and steps to reproduce:**
Video no longer jumps in the preview window

**Comment by peanutbutterandcrackers** [comment]
This, too, I am afraid, needs more description, good sir.

**Comment by DylanC** [comment]
Closing until we have more details or screenshots.
