### ISSUE TITLE
Videos gets shortent on timeline

### ISSUE THREAD

**Issue by MrTertius** [OpenShot/openshot-qt#1358]
**System Details: i5 Intel Processor, integrated GPU, 4GB RAM
* Operating System / Distro: Windows 10
* OpenShot Version: 2.4.1
* _Please attach log files if crash_
No Crashes
**Issue Description and steps to reproduce:**
Video no longer gets shortent on timeline

**Comment by peanutbutterandcrackers** [comment]
Do you mean you are unable to slice the video in the timeline?

It seems to me that you are having too many issues with v2.4.1. Could you please one of the latest [daily build](https://github.com/OpenShot/openshot-qt/releases/tag/daily) a shot, please?

**Comment by DylanC** [comment]
Closing until we have more details or screenshots.
