### ISSUE TITLE
Timeline Duration Incorrect

### ISSUE THREAD

**Issue by MrTertius** [OpenShot/openshot-qt#1360]
**System Details:**
i5 Intel Processor, Integrated GPU, 4GB RAM
* Operating System / Distro: ?
Windows 10
* OpenShot Version: ?
2.4.1
* _Please attach log files if crash_
No Crashes
**Issue Description and steps to reproduce:**
Duration On Timeline Is Corrected

**Comment by peanutbutterandcrackers** [comment]
If you mean the timestamp, the syntax is Hrs:Min:sec:Frames. It seems that it has been confusing a lot of people...

**Comment by DylanC** [comment]
Closing until we have more details or screenshots.
