### ISSUE TITLE
Program Freezes When Selecting Options

### ISSUE THREAD

**Issue by MrTertius** [OpenShot/openshot-qt#1361]
**System Details:**
i5 Intel Processor, Integrated GPU, 4GB RAM
* Operating System / Distro: ?
Windows 10
* OpenShot Version: ?
2.4.1
* _Please attach log files if crash_
No Crashes
**Issue Description and steps to reproduce:**
Program will not Freeze when an option is selected

**Comment by peanutbutterandcrackers** [comment]
Please grab one of the latest [daily build](https://github.com/OpenShot/openshot-qt/releases/tag/daily) and see if that works out for you...

**Comment by DylanC** [comment]
Closing until we have more details or screenshots.
