### ISSUE TITLE
Video Flashes Black At End

### ISSUE THREAD

**Issue by MrTertius** [OpenShot/openshot-qt#1362]
**System Details:**
Intel i5 Processor, Integrated GPU, 4GB RAM
* Operating System / Distro: ?
Windows 10
* OpenShot Version: ?
2.4.1
* _Please attach log files if crash_
No Crashes
**Issue Description and steps to reproduce:**
Video will not flash black at end

**Comment by peanutbutterandcrackers** [comment]
This issue has been reported and should hopefully be fixed in the future releases (v2.4.2, perhaps). Please try out the latest [daily build](https://github.com/OpenShot/openshot-qt/releases/tag/daily) in the meantime. Thanks!

**Comment by DylanC** [comment]
Closing until we have more details or screenshots.
