### ISSUE TITLE
Shortcut for jumping to the next/previous keyframe

### ISSUE THREAD

**Issue by philiplb** [OpenShot/openshot-qt#1363]
Hi,
coming from Blender VSE, I miss a small feature:
In Blender, I can let the marker jump to the previous or next keyframe of the selected clip. This way I can easily go through all keyframes of the clip.
It would be awesome if this could be added to OpenShot.
Maybe Shift+Right for the next keyframe and Shift+Left for the previous?

**Comment by ferdnyc** [comment]
I've been thinking about that too. I wonder if keyframes maybe shouldn't just _also_ be considered markers, for the purposes of the existing Next/Previous Marker controls.

**Comment by peanutbutterandcrackers** [comment]
Awesome! This feature needs to be implemented too, now that I think about it. Would be a lot more easier than just scrubbing through to find the next keyframe.
