### ISSUE TITLE
Moving to the previous/next frame broken on MacOS?

### ISSUE THREAD

**Issue by philiplb** [OpenShot/openshot-qt#1364]
**System Details:**
* Machine: MacBook Pro
* Operating System / Distro: MacOS 10.13.3
* OpenShot Version: 2.4.1

**Issue Description and steps to reproduce:**

The Left and Right keys just won't move the marker to the previous/next frame. For me, they just don't react.

**Comment by peanutbutterandcrackers** [comment]
Are you sure you have clicked on the timeline/play-head first and then trying stepping through the frames using the arrowed keys?

Also, you might want to try out the latest [daily build](https://github.com/OpenShot/openshot-qt/releases/tag/daily), too. Maybe that'll work?

**Comment by DylanC** [comment]
Dup of #811.

**Comment by philiplb** [comment]
@peanutbutterandcrackers 
Just tried that, I'm afraid without success.
Also no luck with the daily build.

@DylanC 
Of course, I'm closing this then. :)

**Comment by peanutbutterandcrackers** [comment]
@philiplb - Thank you for confirming. Hopefully, this will be fixed in OpenShot v2.4.2. Please wait for it, and continue to support OpenShot!
