### ISSUE TITLE
Marker positioning is off by a frame.

### ISSUE THREAD

**Issue by ferdnyc** [OpenShot/openshot-qt#1365]
**System Details:**
* Operating System / Distro: Fedora Linux 27
* OpenShot Version: 2.4.1

**Issue Description and steps to reproduce:**

It took me a while to convince myself of this, but now I'm sure. Markers are being placed one frame ahead of where they should be. Steps:

1. Zoom all the way in to 1-second granularity on the timeline.
1. Somewhere in the middle of a clip, create a keyframe by (say) adjusting the Volume to less than 1.00.
1. Immediately and without moving the head, click Add Marker. Note the timecode position (mine is 00:00:02:17).
1. Use Next Marker to skip ahead, and then Previous Marker to skip back to the marker you just set.
1. Notice that the Volume parameter is _not_ on a keyframe — it's blue. That's because you're now positioned at 00:00:02:18.
1. Use <kbd>←</kbd> to move one frame left. Timecode changes to 00:00:02:17, Volume turns green.

This occurs when approaching the marker from either direction, and it occurs whether you create the marker first or the keyframe first. The marker's always a frame AHEAD of the keyframe, even though they were both set from the same position in the video.

Actually, looking at the timeline, the marker and the keyframe indicator _appear_ to line up (though they don't). The play head lines up visually with the marker (which is positioned one frame ahead of where it's placed), and improperly with the keyframe indicator (which is positioned where it's placed, but **displayed** one frame ahead).

Here are a marker and keyframe created using the steps above.

![screenshot from 2018-03-11 20-42-58](https://user-images.githubusercontent.com/538020/37260754-2a44d51c-256d-11e8-89b2-0af8da7060d8.png)

Here's the position after I skip to the marker (keyframe indicator is _blue_ at this point, timecode is one frame higher than expected):

![screenshot from 2018-03-11 20-43-08](https://user-images.githubusercontent.com/538020/37260763-35b0c294-256d-11e8-931a-e2f4af97a4df.png)

And after I move one frame left to the keyframe position (head moves to expected timecode, keyframe turns _green_ in properties):

![screenshot from 2018-03-11 20-43-15](https://user-images.githubusercontent.com/538020/37260771-4647c53a-256d-11e8-9de8-5739163ad721.png)

**Comment by peanutbutterandcrackers** [comment]
I have a theory:

OpenShot uses 1-based indexing for frames.
Python (and C++ too, I presume) both use 0-based indexing.

So, what is probably happening is that somewhere in the source code, there are a bunch of missing '+1's.

#1369 is another symptom of the same possible underlying problem...

**Comment by ferdnyc** [comment]
The fact that parameter keyframes are positioned by frame# instead of time index would also explain #1034 - "Keyframes do not remain in the same place when exporting to a different fps that they were placed in."

**Comment by peanutbutterandcrackers** [comment]
Hmm... that makes sense... I wonder if this can be fixed in v2.4.2. Looks like libopensot has to change the way it handles stuffs (switching to time instead of frames) and all...

**Comment by N3WWN** [comment]
I wonder if it would make sense (without looking at the code) to perform the conversion backwards and forwards, or forwards and backwards, so we can measure how far from our original value we are after the 2nd conversion.  That _may_ let us make a determination of what to do with the original value before storing it;  use as is or shift for better alignment.

**Comment by ferdnyc** [comment]
I think that might make sense if the conversion were in a macro or function somewhere, and the misalignment was due to _imprecise_ conversion. But when each conversion is done in place, ad-hoc (as they are, see my WIP PR #1384) then having the math check itself is probably only a chance for more errors.

The code that would check the conversion is just as susceptible to using the wrong formula as the conversion itself is, and when that's where the errors are introduced the solution is, well, to actually use the _right_ formula. (And there are _so many_ times that math is duplicated. In C or C++ code, like I said, the conversions would be a pair of macros, called every time they're needed, with the actual math done in only one place in the code. But when it's a mix of Python, JavaScript, and math actually hardcoded into the parameters of HTML tags...)

**Comment by DylanC** [comment]
@ferdnyc - I've asked Mr.Thomas to review your PR since I think you said it should be good for a merge.

**Comment by ferdnyc** [comment]
The particular issue of marker-positioning (and keyframe-position-display) should be fixed with the merge of #1384.
