### ISSUE TITLE
What is new in 2.4.1-9

### ISSUE THREAD

**Issue by MrTertius** [OpenShot/openshot-qt#1367]
**System Details:** : i5 Intel Processor, Integrated GPU, 4GB RAM
* Operating System / Distro: Windows 01
* OpenShot Version: ? 2.4.1
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
Someone linked me a page of daily builds and i saw 2.4.1-9. May i ask whats new in that build ???

**Comment by peanutbutterandcrackers** [comment]
@MrTertius - The daily builds are, as the name implies - daily build of the program from the source code. Whenever any change happens in the project's source code, within 24 hours (actually a lot quicker than that), a computer program builds a 'use-able' version of the program that incorporates that change. Said changes can be bug fixes, new features and stuff.

As of today, the daily build has: 1. save indicator 2. Possible fix for language issues 3. Few extra effects (crop, color shift, shift, pixelate, bars etc. to name a few) among others.

However, the daily builds are not stable releases. That is why they aren't released to the general public.

However, often, a daily build might turn out even better than the latest stable release. That is why you have been suggested to use the daily build.

Hope that clears things up. :)

**Comment by DylanC** [comment]
Closing question as answered.
