### ISSUE TITLE
*.opus audio issue

### ISSUE THREAD

**Issue by peanutbutterandcrackers** [OpenShot/openshot-qt#1368]
OpenShot v2.4.1-dev1 (daily build: Mar 12, 2018)

If I import a .opus audio file, and add it to the timeline, all that can be seen is a narrow clip indicator thingy. And the playhead gets stuck at the audio clip once I try to play it.
![screenshot from 2018-03-12 17 15 31](https://user-images.githubusercontent.com/26764547/37281436-1cf2ee9c-2619-11e8-8bd8-8d03cb844830.jpeg)

However, if I convert them to .mp3 (using ffmpeg), they import and play just fine.
![screenshot from 2018-03-12 17 17 02](https://user-images.githubusercontent.com/26764547/37281467-3a621ac0-2619-11e8-99b5-41d47af39472.jpeg)

**Comment by DylanC** [comment]
@peanutbutterandcrackers - Does Openshot list Opus as supported or do we need to add this format support?

**Comment by gary9872** [comment]
If you click on the properties it seems to acknowledge what it is.

I imported one. It imported fine, but then when I tried to add it to a track, I could only manage to get it on the threshold between them. Then it became unresponsive. I check what it was doing via top. Using one core @ 100% and gobbling up memory like crazy 4 gigs in about 10 seconds.

**Comment by peanutbutterandcrackers** [comment]
Hmm... that is definitely strange... Thank you for the info! :)

**Comment by gary9872** [comment]
can you post where I can get the clip you have ( to see if i get the same results?)

**Comment by gary9872** [comment]
This one I made and works fine. Do it work right for you?

http://www.mediafire.com/file/do1kd2yf6cwreuk/test.opus

**Comment by DylanC** [comment]
@peanutbutterandcrackers @gary9872 - Sooo is this an issue or not an issue? Pretty confused here. 😆

**Comment by gary9872** [comment]
@peanutbutterandcrackers Check to see if yours has a video header in it. I had a file that was just audio but had a video header. The video had a time of zero seconds while the audio was like 3 mins. When I dragged it to the time line it parsed the video time, not the audio. 

@DylanC The first clip I gave was a raw opus stream, so I don't think we should expect that to work out of the box. So my concerns are closed.

**Comment by DylanC** [comment]
@gary9872 - No problem. @peanutbutterandcrackers - Are you okay to close this or do you feel we need to do something here?

**Comment by peanutbutterandcrackers** [comment]
@gary9872 - Hmm that makes sense. But that was on my pal's computer and he isn't around (and neither is his computer)... but I'll try to check it later on (much later, as we have vacations soon).....
Thank you for your insights. You're awesome!

@DylanC - I think yes, for now, this can be closed. If I need to re-open it later on after testing things out further, I shall do it.
