### ISSUE TITLE
Split Clip: Off by a frame

### ISSUE THREAD

**Issue by peanutbutterandcrackers** [OpenShot/openshot-qt#1369]
OpenShot v2.4.1-dev1 (daily build: Mar 12 2018)

In light of #1365, I think what I experienced yesterday is, indeed, a bug that needs fixing.

If one uses the 'split clip' dialogue to split the clip and set a 'start' and an 'end', and drag the clip on to the timeline, I can see that the frame before the one I set as 'start' is the first frame and the frame before the frame I set as the 'end' is the end frame.

What I think is happening is that OpenShot uses 1-based-indexing for frames. However, Python (and perhaps C++ too) use 0-based indexing. So, basically, I think merely adding '+1' somewhere (or in multiple places in the code) should fix it. Definitely.

**Comment by DylanC** [comment]
@peanutbutterandcrackers - You could be right here! Sounds like it makes sense.

**Comment by DylanC** [comment]
@peanutbutterandcrackers - Is this bug still here in v2.4.2?

**Comment by peanutbutterandcrackers** [comment]
@DylanC - Yes, sir! Still there. It's still starting one frame before the 'start' point and ending one frame before 'end'. At one point, the end seemed to work too but I must have been mistaken. This needs some more work.
