### ISSUE TITLE
No mute buttons in Windows vn

### ISSUE THREAD

**Issue by JimH44** [OpenShot/openshot-qt#137]
I like the look of OpenShot, and have started trying to use it.
I wanted to separate the audio and video, so I followed the on-line advice, to drag the clip into two separate tracks, and hide the video in one of them, by clicking the video hide button. But I can't see any hide buttons as described here.
![image](https://cloud.githubusercontent.com/assets/8330030/14068654/e2f47bc8-f4d5-11e5-96ac-77374392ae4a.png)
If there is another way of doing this nowadays, can you pls point us to it.
Thanks, Jim

**Comment by JimH44** [comment]
Perhaps these functions are now performed by right-clicking a clip?
Is this documented anywhere?
Thanks again, Jim

**Comment by komackaj** [comment]
[Related link](http://www.openshotvideo.com/2009/07/audio-editing-with-openshot.html) is for previous OpenShot version. This repository holds current version 2.0.6 (Beta3) and AFAIK there is no user manual for it. Which one are you using?

I was able to mute the clip by right-clicking the clip and Volume -> Entire clip -> Level 0%. But found no simple way to replicate the "Hide Video" feature from previous version.

**Comment by JimH44** [comment]
Thanks, Komackaj, for that tip.
I have found out that there is a way to see the audio waveform superimposed over the video image. (This is very helpful for videos that describe how to use software. It makes it much easier to chop out false starts or long silences.
1. Drag a clip to two adjacent tracks, both starting at the same point.
2. For the upper one, right-click and select Properties.
3. Scroll down and right-click Waveform and select Yes
4. Just above that, change Wave color if you want to
5. Select the lower track and scroll down in its properties and check that Waveform is set to "No"
6. Right-click the lower track and select Volume->Entire clip->Level 0%

Where can we put that information so that it becomes part of the documentation for version 2.x?
Jim

**Comment by JimH44** [comment]
Sorry, I didn't answer your question properly.
I am using 2.0.6 (now 2.0.7) from the OpenShot website, Windows version, on Windows 7 Professional, 64-bit.

**Comment by komackaj** [comment]
Thanks @JimH44 for a nice tip!
As for documnetation, according to [this repo wiki page](https://github.com/OpenShot/openshot-qt/wiki/Online-Documentation) it will updated for current version in some time, maybe @olielvewen may be of help, he  took care of all wiki pages so far. Perhaps try creating a new page in [wiki](https://github.com/OpenShot/openshot-qt/wiki) will be a way to do it, I don't know if it is open for editing.
