### ISSUE TITLE
Select all clips to the left/right of the ruler

### ISSUE THREAD

**Issue by philiplb** [OpenShot/openshot-qt#1370]
Hi,

sometimes, it is very handy to select all clips left or right of the ruler. For example, if you want to make some space and move everything to after the ruler 5s to the right.
I often use this in Blender when I want to insert a clip.
![screen shot 2018-03-12 at 14 10 24](https://user-images.githubusercontent.com/1672238/37285387-2d1473aa-25ff-11e8-9026-9b6de856afd9.png)

**Comment by peanutbutterandcrackers** [comment]
I agree. This would be quite a handy feature to have in OpenShot.
