### ISSUE TITLE
Rotated images shown in original orientation on timeline

### ISSUE THREAD

**Issue by tjsepka** [OpenShot/openshot-qt#1373]
OpenShot version 2.4.1-dev1

After I rotate images on the timeline, the original image orientation is still shown on the timeline, not the rotated one.  I believe the timeline should always match the preview image (and of course, the exported video) to avoid confusion.  This should happen automatically, and not require the user to reload anything as a potential work-around.

**Comment by tjsepka** [comment]
Clarification on the version I'm using.  I got the version number I mentioned above from Help>About.  The version I'm using came from here:

https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.4.1-8-g3accac8-57-666-x86_64.exe

**Comment by peanutbutterandcrackers** [comment]
Could you perhaps also include a screenshot, good sir. Would help us understand this clearly. At least I don't quite fully grasp this issue... although I have encountered something (that I think is) similar myself.

**Comment by DylanC** [comment]
@tjsepka Can you try v2.4.2 and let us know if you have any success?

**Comment by tjsepka** [comment]
No change.  Images are still rotated on the timeline, even though they display properly in Windows file explorer and IrfanView.  I checked the thumbnail directory created by OpenShot and the image is incorrect (shown rotated) there.

On a side note, in OpenShot there is a file property named "ID".  I thought that might be the thumbnail file name, but it's not.  What is the "ID" property listed in OpenShot?

**Comment by peanutbutterandcrackers** [comment]
Hmm... I'd really like to see a screenshot, though.

I wonder, if [GIMP](http://gimp.org/) can open the image correctly. If even GIMP can't, then I would think that the metadata lacks the orientation details. But that's just a thought...

We should probably test it out. Could you please also attach the image for us? If we can reproduce, we'll mark it as a bug and work on fixing it in 2.4.2.x bug-fix series.

**Comment by DylanC** [comment]
@tjsepka - Ah I understand what you mean now. Yes, this is the case currently. Marking as a bug unless another dev disagrees on it.
