### ISSUE TITLE
Is the dev working on the new version???

### ISSUE THREAD

**Issue by MrTertius** [OpenShot/openshot-qt#1374]
**System Details:** Intel i5, Integrated GPU, 4GB RAM
* Operating System / Distro: ? Windows 10
* OpenShot Version: ? 2.4.1
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
I was wondering if the dev are seeing the issues we are posting. 
is the dev currently working on the new version???

**Comment by DylanC** [comment]
Yes. Mr.Thomas is working on the high priority issues for the upcoming v2.4.2 release. He cannot tackle all of the issues here at once. He is one man and has limited time to work on the project. (much like the rest of us)

**Comment by MrTertius** [comment]
Ah thank you for the response, I cannot wait for the release, Mr.Thomas can take all the time in the world to fix high priority problems

**Comment by peanutbutterandcrackers** [comment]
Yeah. Esp. windows-specific critical bugs are on top of the list. Please do continue to love and support OpenShot. It will only get better with our help.

**Comment by MrTertius** [comment]
I see a bright future for openshot, once 2.4.2 has been released, i will promote it through my YouTube Channel

**Comment by peanutbutterandcrackers** [comment]
Thank you! That is how we all help the project --- by doing what little we can do in our small way.
I hope you create awesome videos with OpenShot, too once v2.4.2 is released.
:)

[P. S: Please do not forget to close the issue once it has been resolved. It will help the moderator. Thanks! :)]

**Comment by stephan75** [comment]
By the way:
Everyone can see the most recent development steps in chronological order

at https://github.com/OpenShot/openshot-qt/commits/master
