### ISSUE TITLE
Application window frozen on playback in preview

### ISSUE THREAD

**Issue by itschris2003** [OpenShot/openshot-qt#1375]
**System Details:**
* Operating System / Distro: Windows 10 (x86)
* OpenShot Version: 2.4.1
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
Okay, I finally have a screenshot to outline the windows performance issues. If you look, first of all you'll notice that it is frozen, but secondly I'm getting stuttering, despite it being ON THE LOWEST OUTPUT SETTING which for me improves the performance of playback. At one point, playback froze but the audio was still going. This is all I've got so far, I'll try to get some footage done of the process I take when opening up the editor
![image](https://user-images.githubusercontent.com/18634859/37368413-28bda6fa-26fe-11e8-8a44-558c3c016e0a.png)

**Comment by peanutbutterandcrackers** [comment]
Sorry about this. I will try to get the dev's attention towards the issues described here. Thank you for the offer for a screencast. It will help the devs understand things better. :+1:

**Comment by DylanC** [comment]
@itschris2003 Can you try v2.4.2 and let us know if you have any success?
