### ISSUE TITLE
Needs GPU support

### ISSUE THREAD

**Issue by JazzMaster** [OpenShot/openshot-qt#1376]
There isnt a crash but the application needs GPU support. CPU rendering as-it-is is slow as hell and locks up at 3% of the CPU instead of like say 75% of it. Dont be afraid to ask the user for more power. Now this is done silently on a laptop but on a desktop as well this happens both under Linux at least- possibly under Win10 FC as well. Will test further. KDEnLive doesnt suffer from this as much and is much more responsive due to GPU resource tasking instead of CPU. GPU are over 10x more efficient.

If the app seems to hang- its not hung. Its rendering at a very slow pace. UBU 18 edition and Sin10FC tested so far.

**Comment by peanutbutterandcrackers** [comment]
Good sir, thank you for the issue reporting.

Yes, the project does need to be able to support GPU.

However, we only have one active developer and 2 active contributors at the moment. What we need is more people (perhaps like you) willing to contribute code to the project. Maybe we shall have GPU support in the (hopefully not-so-distant) future.

**Comment by gary9872** [comment]
Are you talking about when your export (slow rendering) ?

**Comment by DylanC** [comment]
Dup of #527

**Comment by jyo64** [comment]
> Good sir, thank you for the issue reporting.
> 
> Yes, the project does need to be able to support GPU.
> 
> However, we only have one active developer and 2 active contributors at the moment. What we need is more people (perhaps like you) willing to contribute code to the project. Maybe we shall have GPU support in the (hopefully not-so-distant) future.

Hi , I am new to the world of programming and would like to contribute to opensource projects , will guide me to get started ? Thanks

**Comment by ferdnyc** [comment]
I'm actually not sure if this is about video encoding or animated title rendering (which use completely different technologies).

But either way...
* Hardware video encoding is now implemented in the development code, and I expect will be in the next release. (At least for Linux, not sure if Win/Mac are sorted out yet.)
* Blender GPU rendering has a WIP implementation in #2825, and mostly just needs testing. (But I think many people will actually be surprised by just how much it DOESN'T speed up their renders, unless they have a $1000 GPU.)

So, either way, closing this as "in development / upcoming", and as a dup of the open master issues on these requests. (That's #2812 for Blender GPU rendering, possibly #527 for hardware encode.)
