### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by Tivaak** [OpenShot/openshot-qt#1378]
After saving my work yesterday, I wanted to continue today but all the links with the images were broken. The video links are still working but the images are all gone. 
When I open the osp file it says "....png file can't be found". but when I try to find it again on my computer it looks for folders and not for png files. 
any idea how I can fix this without having to redo all the work? 
Thanks!

**Comment by ferdnyc** [comment]
> when I try to find it again on my computer it looks for folders and not for png files.

That's normal, OpenShot asks you to tell it _where_ it can find the missing file (and assumes the filename is still the same), so you just need to navigate to the folder that contains the image.

However, if your project contains a _lot_ of "missing" images, you'll have to to do that for **each** one of them. (That's bug #1325.) If that's the case, it may be easier to either (a) restore the images back to their original location, or (b, and as a last resort) change the paths in (a copy of) the `.osp` file, directly.

The project file is a text file, it can be opened with any editor like Notepad or Textedit. If you look at the contents, you'll be able to see what paths OpenShot _thinks_ your images can be found at. If they're not there anymore, but they can be put back, then doing that before opening the project in OpenShot should let you continue without having to update the location of every file. The file can be _huge_, but just search for the filename of one of your images.

If you can't restore the images to their expected location for some reason, then the project file (which, again, is just a text file in a special format) can also be modified with that same text editor you use to read it. I would only recommend trying this on a _copy_ of the file, but if all else fails you can edit the entries for your images to provide the correct path(s). Just look for the string `"path"` in the file. Some of them will be relative to the location of the project file, so something like `"../../../../Pictures/myimage.jpg"` and the like.

**Comment by DylanC** [comment]
Closing as answered.
