### ISSUE TITLE
Exporting only changed parts

### ISSUE THREAD

**Issue by philiplb** [OpenShot/openshot-qt#1379]
Hi,
this would be awesome:
The possibility to (re-) export only the changed parts of the video since the last export. Imagine for example you are editing a 2h movie and you need more than a day for the export. Murphy says that you spot a typo in some titles within minutes after the export. Easy fix but now, the whole export has to be done again. It would be more than great, if OpenShot could export only the changed parts now and stitch them into the previously exported file.
I can imagine this feature to be rather complicated to implement as it isn't easy to determine and track "changed" parts:
- Keyframes affect whole areas
- The footage files might be changed externally
- ...

So a not so demanding option might be to include some manual UI in the export dialog: There are already input fields for "Start Frame" and "End Frame". A simple checkbox might do it: "Stitch into existing file instead of overwriting"

**Comment by peanutbutterandcrackers** [comment]
Yeah. This would be quite neat.
