### ISSUE TITLE
Previous/Next Marker, and other "navigation" actions, move playhead offscreen

### ISSUE THREAD

**Issue by ferdnyc** [OpenShot/openshot-qt#1382]
**System Details:**
* Operating System / Distro: Fedora Linux x86_64
* OpenShot Version: 2.4.1

**Issue Description and steps to reproduce:**

When working at a high zoom level where the entire length of the clip does not fit on screen, using the Previous/Next Marker controls to reposition the playhead can cause it to move outside of the visible timeline view.

This is true of all playhead positioning, since using <kbd>←</kbd> or <kbd>→</kbd> to scrub through the clip can also move the playhead offscreen, as can  <kbd>Ctrl</kbd>+<kbd>Home</kbd> (Jump to Start), <kbd>Ctrl</kbd>+<kbd>End</kbd> (Jump to End), and the like.

For _some_ of those, like the scrubbing controls, there might be situations where it's useful to move the playhead without repositioning the timeline view. (I can't think of any, but maybe there are.) But for the "Jump"-style controls, I  would think we'd want the timeline to automatically scroll so that the playhead is visible after the jump, no?

(Barring that, a "Scroll to playhead"-type button / keyboard combo, or a toggle like the Snapping icon, that moved the playhead into view when clicked/pressed/enabled might be helpful, and would leave that choice up to the user.)

**Comment by N3WWN** [comment]
I've noticed this, too, and I think a "Follow playhead" toggle would be a good solution.

**Comment by peanutbutterandcrackers** [comment]
@N3WWN - That is a great idea! Should file an enhancement proposal for this. I think.

**Comment by N3WWN** [comment]
@peanutbutterandcrackers - Wanna add this to a new 2.4.3 checklist?

**Comment by peanutbutterandcrackers** [comment]
@N3WWN - Aye! Aye, good sir! Done! :heavy_check_mark:
