### ISSUE TITLE
Dragging a marker adds its icon to the timeline as a clip

### ISSUE THREAD

**Issue by ferdnyc** [OpenShot/openshot-qt#1383]
**System Details:**
* Operating System / Distro: Fedora Linux x86_64
* OpenShot Version: 2.4.1

**Issue Description and steps to reproduce:**

OK, this one's actually funny. :laughing: 
1. Add a clip to the timeline.
1. Click "Add Marker".
1. (Move the playhead out of the way of the marker.)
1. Attempt to reposition the marker by grabbing and dragging it.
1. The marker's icon, `blue.png`, is added to the timeline as an image clip.

Before:
![screenshot from 2018-03-14 22-47-12](https://user-images.githubusercontent.com/538020/37441980-54a912ea-27da-11e8-8969-cf950d4dcb1f.png)

After:
![screenshot from 2018-03-14 22-47-21](https://user-images.githubusercontent.com/538020/37441983-57e68e88-27da-11e8-94a4-a3bb2da32560.png)

Since markers _aren't_ repositionable, they probably shouldn't be draggable. (Or, dragging them should reposition them.)

**Comment by peanutbutterandcrackers** [comment]
This one's funny, indeed. I did try dragging other icons to see if those are also draggable. They weren't. Haha

**Comment by N3WWN** [comment]
"That's not a bug!  That's a feature!"  😁 

Now, if we can find some way to promote this easter egg as something useful, there'll be no need to fix it!

**Comment by DylanC** [comment]
@ferdnyc - I don't think we can convince anyone else its not a bug. 😆 Something to be fixed but I would say low priority.

**Comment by DylanC** [comment]
@ferdnyc - Man... I can tell you so far this bug is gonna be painful! :rofl: It doesn't even happen in the browser but only when deployed to Qt.

**Comment by DylanC** [comment]
@ferdnyc - Managed to fix this actually. It was easy enough in the end. :+1:

**Comment by ferdnyc** [comment]
> It doesn't even happen in the browser but only when deployed to Qt.

**RIGHT?** That was one of the first things I noticed. Though later I realized that the mouse pointer did turn into a hand when you _tried_ to drag, which felt like a clue.

> Managed to fix this actually.

`\o/` I knew it had to be something stupid. I'm on my phone now, but I look forward to seeing the changes.

(As a reminder, if you put `Fixes #1383` in a PR text, GitHub will auto close this issue on merge. I've found that quite handy. Not sure how it works with PRs that fix multiple issues, tho.)

**Comment by DylanC** [comment]
> RIGHT? That was one of the first things I noticed. Though later I realized that the mouse pointer did turn into a hand when you tried to drag, which felt like a clue.

I saw that too. I felt like a detective following any clues I could spot.

> \o/ I knew it had to be something stupid. I'm on my phone now, but I look forward to seeing the changes.

It was something very small. The img element didn't turn off "draggable" which means you could drag it. This turns into a problem with the timeline because the tracks deal with... yep you guessed it! - **draggable elements**. :rofl: 

Looks like a bit of an oversight really during early development. That's all.

**Comment by ferdnyc** [comment]
> I saw that too. I felt like a detective following any clues I could spot.

Few people appreciate how much debugging is like a criminal investigation. QA, too, for that matter.



> It was something very small. The img element didn't turn off "draggable" which means you could drag it.

That makes a disturbing amount of sense. I didn't realize draggability was controlled in the HTML, or could be.

I think at one point I even did a string search for "drag"... but since literally _every_ match was inside the JavaScript, and your change marks the first occurrence of that string in the HTML, I'd have actually had to **know** anything about Angular/jQuery to realize you could do that. And as we have established, I do not. :wink:
