### ISSUE TITLE
When is the next version released?

### ISSUE THREAD

**Issue by MrTertius** [OpenShot/openshot-qt#1385]
**System Details:** Intel i5 Processor, Integrated GPU, 4GB RAM
* Operating System / Distro: Windows 10
* OpenShot Version: 2.4.1
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
Hello, i have a question which is, when wil the next version of Openshot be released???

**Comment by peanutbutterandcrackers** [comment]
I hope that by the end of May, we will have v2.4.2 out. But I'm not quite sure. There are still a lot of things to be checked off the list of critical bugs and we need more volunteer programmers to help fix things...

**Comment by MrTertius** [comment]
Oh dear, well, i hope it gets fixed very fast

**Comment by peanutbutterandcrackers** [comment]
We've got more and more volunteers coming on board. So, yeah. Perhaps it will be faster than we think it will be. :)

[You might also want to close this question, good sir, as it has been generally answered. Would help Mr. Dylan sort the issues out. Thanks!]
