### ISSUE TITLE
Audio Out Of Sync With Video Preview

### ISSUE THREAD

**Issue by MrTertius** [OpenShot/openshot-qt#1386]
**System Details:** Intel i5 Processor, integrated GPU, 4GB RAM
* Operating System / Distro: Windows 10
* OpenShot Version: 2.4.1.9
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
The audio is out of sync with the video preview

**Comment by peanutbutterandcrackers** [comment]
This might be an issue with the video profile that you have chosen. For instance, if your original video is in 25fps but you're editing in 30fps, you might run into issues like this...

**Comment by MrTertius** [comment]
Hello, I usually record my videos in 30FPS but i am still finding out how to fix my FPS drops

**Comment by peanutbutterandcrackers** [comment]
So, you might want to change the video editing profile from the default (720p 24fps) to something that is 30fps to match your video. You can learn about changing profiles [here](https://www.openshot.org/static/files/user-guide/profiles.html). Hope that helps!

**Comment by peanutbutterandcrackers** [comment]
I hope this was resolved for you, @MrTertius!
