### ISSUE TITLE
Audio in OpenShot still plays over speaker after plugging in headphone

### ISSUE THREAD

**Issue by SirDaedalus** [OpenShot/openshot-qt#1390]
**System Details:**
* Windows 10 Professional / 64bit
* OpenShot 2.4.1
* Intel High Definition Onboard Audio (on Lenovo U300s Laptop)

Not sur if this one's related to a driver issue (and not to OpenShot), but when plugging in my headphone (resulting in everything on Windows is playing over the headphone), OpenShot audio (while cutting) still plays over the internal speakers.

**Comment by peanutbutterandcrackers** [comment]
I don't really think this is an issue with OpenShot. Could you please try using another speaker? Or, does the audio play through the headphone even if you play a movie from another program? Perhaps then you can know for sure whether this has to do with OpenShot or not?

Hope that helps!

**Comment by SirDaedalus** [comment]
Just tried to reproduce it, you can close the bug. It was caused by using an iPhone headphone on the Laptop jack, which probably caused the driver to not switch to jack-output completely.

**Comment by peanutbutterandcrackers** [comment]
I see.

Hope you create awesome videos with OpenShot!

You could actually 'comment and close' this issue.

Just in case you're late, @DylanC, Cap'ain, an issue to close here. :)

**Comment by DylanC** [comment]
@peanutbutterandcrackers Thanks!

**Comment by peanutbutterandcrackers** [comment]
@DylanC - My pleasure, Cap'ain!
