### ISSUE TITLE
AppImage build uses very out-of-date Qt w/o native file chooser

### ISSUE THREAD

**Issue by ferdnyc** [OpenShot/openshot-qt#1391]
**System Details:**
* Operating System / Distro: Linux (any, but for my testing specifically: Fedora 27 x86_64)
* OpenShot Version: OpenShot-v2.4.1-x86_64.AppImage

**Issue Description and steps to reproduce:**

One desirable feature in recent releases of Qt5 is the ability to display native file-chooser, color-picker, and font-selector dialogs for the platform an application is running on. These dialogs are generally more full-featured than Qt's own "built-in" dialogs, and they're certainly far better integrated into the local UI. (See #1302 for problems caused by OpenShot's use of the Qt built-in file-chooser, instead of a native dialog.)

Unfortunately, because these features are relatively recent developments, especially in Linux (where access to native GTK3 dialogs requires QT 5.7 or later), they may not be available or easily accessed on all of the distros where OpenShot users may run the software.

I was hoping that the AppImage build of OpenShot might provide those users with a workaround for their distro's Qt native-dialog problems. Unfortunately, the current AppImage build doesn't use native dialogs even on distros where they _are_ supported and accessible by default! (The distro I test on, Fedora 27, will provide native dialogs out of the box, whether the user installs OpenShot pre-packaged from the rpmfusion repository, or configures and builds it themselves directly from the GitHub repo. But `OpenShot-v2.4.1-x86_64.AppImage` in Fedora 27 falls back to Qt built-in dialogs.)

The reasons for this most likely begin with the _**ancient**_ Qt 5.2.1 release that's being bundled into the AppImage. As I said earlier, native GTK3 dialogs require Qt 5.7+, so even if Qt 5.2 could be configured for native-dialog support they'd be using the inferior, deprecated GTK2 API. Therefore, upgrading Qt to a recent 5.9 / 5.10 release version should be the first step in attempting to get native-dialog support working in the AppImage.

(The current AppImage's bundled Python 3.4.3 is similarly out of date, and should really be updated to a recent Python 3.6 release as well.)

**Comment by peanutbutterandcrackers** [comment]
The devs have been informed about this. Hope this will be resolved soon.

@N3WWN - could you perhaps help out with this, too?

**Comment by DylanC** [comment]
@ferdnyc - I would recommend Qt5.9 as its LTS (Long Term Support) and I use it in my own project without issues. Qt5.10 has some issues for me. Certain things have changed in a feature breaking manner.

**Comment by ferdnyc** [comment]
I guess this is a duplicate of #1408, now? Or vice versa?

I'm happy to track it in either issue, and since I'm only able to close this one, I'll say:
**Closing as duplicate, #1408.**
