### ISSUE TITLE
Unable to change waveform colour

### ISSUE THREAD

**Issue by MrTertius** [OpenShot/openshot-qt#1392]
**System Details:** Intel i5 Processor, Integrated GPU, 4GB RAM
* Operating System / Distro: Windows 10 
* OpenShot Version: 2.4.1-9
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
When i try to change the waveform colour in the properties window, it does not change

**Comment by peanutbutterandcrackers** [comment]
So, the waveform is kinda' confusing.

What it is changing is not the waveform displayed on the timeline, but the waveform displayed on the clip when you set 'waveform' parameter to 'yes' in the properties. The screenshot will probably be more clear:
![screenshot from 2018-03-18 08 48 36](https://user-images.githubusercontent.com/26764547/37562168-54edd720-2a89-11e8-8bd9-5ab8c41058aa.png)

Hope that helps!

**Comment by DylanC** [comment]
@MrTertius - Follow the suggestion by @peanutbutterandcrackers. Maybe its just a bit confusing but it does indeed work.

**Comment by peanutbutterandcrackers** [comment]
@MrTertius - If you want to have OpenShot be able to change the clip's waveform colour in the timeline, then please do file a separate enhancement request. Thanks!
