### ISSUE TITLE
Add "Shut down after processed"

### ISSUE THREAD

**Issue by songsammy** [OpenShot/openshot-qt#1393]
My computer is too slow that I have to wait for ages to get the video exported.
So  I often do the work first , and then export it later at night.
_(I mean , I leave it on **DURING the WHOLE night**. It's a waste of energy)_
Would you please give us a tickbox of "_Shut down after processed_"?

**Comment by peanutbutterandcrackers** [comment]
Yeah! This would be quite neat!

**Comment by songsammy** [comment]
Request new feature
