### ISSUE TITLE
Video freezes after making it 4x faster

### ISSUE THREAD

**Issue by CPTHBarkington** [OpenShot/openshot-qt#1394]
When I make a video x4 the normal speed, It plays alright in openshot but when it's exported it freezes for 2 to 4 seconds at the start of each clip, Can someone help?

**Comment by peanutbutterandcrackers** [comment]
That is strange. Did you make the video faster using 'properties' or did you just right click and set the speed from the presets? o.O Also, which system is this?

I wonder if it has to do with mismatch of frame rates in the original video and OpenShots video editing profile that has been chosen to edit the video... (for eg the original video is in 24fps and you're editing it at 30fps?)

**Comment by CPTHBarkington** [comment]
I right clicked and set the speed, Windows 10, And the only thing that works for me when I export a video is YoutubeHD 25frames.

**Comment by CPTHBarkington** [comment]
I tried it and now when I export the video it doesn't go 4x faster, even tho I added that.

**Comment by CPTHBarkington** [comment]
Didn't mean to press that

**Comment by peanutbutterandcrackers** [comment]
Hmm... that is strange...

Does it work in the preview?

I wonder if speeding is broken for Windows... o.O Would have to receive confirmation from other windows users too, though, to be sure of it.

You are using windows, right?

**Comment by CPTHBarkington** [comment]
Sorry I was out of town for a bit, I am using Windows, it does work in preview only just when I export the video

**Comment by peanutbutterandcrackers** [comment]
Could you please try exporting in other profiles?

@DylanC - Any thoughts?

**Comment by DylanC** [comment]
@peanutbutterandcrackers - For now I would just recommend trying some other profiles. Sometimes trying other profiles produces much better results.

**Comment by DylanC** [comment]
@CPTHBarkington Can you try v2.4.2 and let us know if you have any success?
