### ISSUE TITLE
[Feature Request] ETA and better percentage on export window

### ISSUE THREAD

**Issue by ArmeF97** [OpenShot/openshot-qt#1395]
**System Details:**
* Operating System / Distro: Windows 10 x64 bit
* OpenShot Version: 2.4.1

**Request Description:**
See this export window?
![image](https://user-images.githubusercontent.com/6240983/37565688-f5c39968-2aad-11e8-902f-8d2586c02897.png)
I just want the percentage to be more precise (like 4.25%, not 4%) and to have an ETA

**Comment by peanutbutterandcrackers** [comment]
Pretty neat!

**Comment by jonoomph** [comment]
Thanks so much for the PR, but unfortunately I just merged in a change which overlaps this one.. and adds more detailed %, along with time remaining, and FPS. But please keep the contributions coming!!! =)
