### ISSUE TITLE
trying to crop video

### ISSUE THREAD

**Issue by Chisi76** [OpenShot/openshot-qt#1396]
I am new to this, 71 yrs old and not too tech savy.
Can anyone tell me how to see the length of the video in MB rather than minutes and seconds?
The video I am trying to crop is always too big to post in messenger which is what I'm trying to do.
Many thanks

**Comment by peanutbutterandcrackers** [comment]
So, what you're trying to do is probably called splitting. I believe you want to cut out certain parts of the video that you deem aren't quite necessary, right? It is quite easy, you just have to use the razor tool. I suggest you go through these [tutorials](https://www.youtube.com/watch?v=1k-ISfd-YBE&list=PLymupH2aoNQNezYzv2lhSwvoyZgLp1Q0T) --- they will help you use OpenShot really well.

Also, the actual size of the video can be brought down while exporting by choosing a lower quality. You can set the 'quality' to 'Low' in the export window. Another thing worth trying would be to export in a smaller video profile. For instance, you could change the 'Video Profile' in the export window from the default 'HDV 720 24P' to something like 'Mobile 360p'. That should bring the size of the video down, considerably.

You might also want to check out the [user guide](https://www.openshot.org/static/files/user-guide/index.html). Hope that helps!

**Comment by DylanC** [comment]
@Chisi76 - I don't think its possible to see the MB before exporting in video editors in general. Its a bit of a unknown although maybe some editor does some approximation based on Math to display something to the user. 

I would recommend to export on the low setting and see your results. Trim your video and export again to see another MB result. See what kind of quality and length of video works for you.

**Comment by DylanC** [comment]
@Chisi76 - Closing this question as answered. Hopefully our answers have pointed you in the right direction at least.

**Comment by peanutbutterandcrackers** [comment]
@Chisi76 - Good sir, perhaps you'd like to go through [this guide](https://gist.github.com/peanutbutterandcrackers/f0f666243133e0ed25abbc12a4ba23d7) to become OpenShot Expert. Just thought I'd help you. :)
