### ISSUE TITLE
Making Videos for TelVue HyperCaster & Mediaroom?

### ISSUE THREAD

**Issue by JCannon2018** [OpenShot/openshot-qt#1397]
Does anyone use OpenShot to produce videos for a TelVue HyperCaster B1000 to be viewed in Mediaroom?   I am trying to find the right export profile to use, and after going through several that the HyperCaster does not like, figured I'd ask this group.

Thanks,
Jason....

**Comment by gary9872** [comment]
I don't see a preset per say. Did you try DVD? That would be the closest. 

https://telvue.com/wp-content/uploads/2015/03/TelVueB1000_HyperCaster1.pdf

You might get away the target MP4 (h.264). Depends on the model.It's an optional feature?

**Comment by JCannon2018** [comment]
MP4 (h.264) seems to be working.  Still running some tests but thanks.

**Comment by peanutbutterandcrackers** [comment]
Awesome! Please do not forget to close this issue once this has been resolved. Thanks! :)
