### ISSUE TITLE
Daily build Linux (build 52) , broken link...

### ISSUE THREAD

**Issue by PASTJL** [OpenShot/openshot-qt#1399]
Dailay build Linux (build 52) , broken link...

**Comment by peanutbutterandcrackers** [comment]
If you could also provide us with the actual broken link, good sir, perhaps we could get the attention of the devs to fix it... Would you please also include the broken link? Thanks!

**Comment by peanutbutterandcrackers** [comment]
This has already been brought to the devs attention and will, hopefully, be sorted out soon. Sorry for the inconvenience...

**Comment by DylanC** [comment]
@PASTJL - This should be fixed now. Thanks.
