### ISSUE TITLE
Can't launch openshot after changing regional settings

### ISSUE THREAD

**Issue by jarlarntzen** [OpenShot/openshot-qt#14]
Hi. 

I changed my regional settings from Norwegian (which has , (comma) as a decimal separator) to American English (which has . (period) as a decimal separator).

This resulted in the inability to launch OpenShot except by removing `~/.openshot_qt` as adviced.
Seems like there is something that depends on regional settings inside .openshot_qt
```
$ launch-openshot
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
launch-openshot:INFO ------------------------------------------------
launch-openshot:INFO    OpenShot (version 2.0.2)
launch-openshot:INFO ------------------------------------------------
   json_data:ERROR Couldn't load user settings file: Extra data: line 1 column 2970 - line 1 column 2972 (char 2969 - 2971)
         app:ERROR Couldn't load user settings. Exiting.
Couldn't load user settings file: Extra data: line 1 column 2970 - line 1 column 2972 (char 2969 - 2971)
```

**Comment by jonoomph** [comment]
I have committed a fix for this tonight, which forces all numbers to be 1234.56 format, and prevents breakages. If you are using Linux, and update will be available soon. Otherwise, I'll make some new Mac and Windows installers soon. Thanks

**Comment by jarlarntzen** [comment]
Sounds like a good move. I'm on Ubuntu 14.04 LTS and I'll probably get around to test this tonight.
