### ISSUE TITLE
Beta 4.0 now crashes worse than Beta 3.0. on my W10 (x64) desktop PC! 

### ISSUE THREAD

**Issue by dancetheskies** [OpenShot/openshot-qt#140]
I'm running W10, v10240 (fully updated).

I start OS 4.0, import an mp4 video clip to the time line, and press the play button,  Within a few seconds it crashes with the familiar "runtime Error" and "Launch.exe has stopped working" error messages.  In one case, I offset the video several seconds down the time line and started the play function, and it crashed even before the timeline position bar got to the start of the video!
![open shot crash](https://cloud.githubusercontent.com/assets/16670296/14129774/16d80f2e-f5fb-11e5-89fd-90635c0085c1.JPG)

**Comment by jonoomph** [comment]
Do you have a test MP4 I could try. Also, please turn on debug mode (in the preferences), delete your log file (located in /Users/NAME/.openshot_qt/openshot_qt.log), and try and reproduce the crash. Then attach your new log with your test MP4. 

I'd really like to know what's happening. =)

**Comment by nwgat** [comment]
this is related to #13 
btw beta 4 no longer have four timeline crashes, only one now, and it no longer crashes on export
but still crashes while previewing video or playing timeline

it crashes on h264 (mov, mp4) and even raw 4k y4m files
[openshot-qt.2.0.7.txt](https://github.com/OpenShot/openshot-qt/files/194896/openshot-qt.2.0.7.txt)

**Comment by telelauro** [comment]
I have the same problem with this new version, and unfortunately earlier too. I can not continue to edit any project by this ruling. And it is continuous. Files are estarndar ____.Mpg4 (h260). I´m working with a good computer, I use (Asus ROG 16RAM Windows 8.1 core7i ).

**Comment by hansw96** [comment]
Just installed the product. I'm having exactly the same issue. 

Windows 7 Pro, 64 bit.
.flv files created by OBS

Add a video (.flv) click play. Stop, Drag the timeline back. Click play -> crash.

I've seen all kinds of variations. Crashing before it reaches the video. Crashing when I let go of the timeline, etc. When I overlap an image and video, it seems to crash easier / more often.

I could not reproduce it with .mp4 files created by OBS.

**Comment by jonoomph** [comment]
@nwgat - Well, I just remembered (after looking at the attached log file), that Windows truncates the stdout & stderr, and the verbose debug data from libopenshot does not make it into the log file. I'm going to focus on this for a bit, and come up with a solution (hopefully). Without the verbose libopenshot logs, I'm not able to see what classes/methods are crashing.

I could create a debug version for Windows, that also shows the console window... but hopefully I can find a better way to route the output from libopenshot into the Python app (openshot-qt). I'll keep everyone posted.

**Comment by hansw96** [comment]
If necessary, I would be happy to run a debug version, or provide other information (sample video file).

**Comment by nwgat** [comment]
yeah build a debug version so we can get to the bottom of this

**Comment by telelauro** [comment]
Jonathan; 
with reference to such failures if is necessary for you, I can record (an editing session) with screenomatic application (https://screencast-o-matic.com/home) so you can check in-situ what this going on, at least Windows users.
and I can share with you that video  from drive. what do you think? I hope your news!!!! and I do withaout problems... ALL FOR OPENSHOT!!!!

**Comment by jonoomph** [comment]
Here we go... some big debugging improvements (if it works): 
http://releases.openshot.org/windows/OpenShot-v2.0.7-3-gb0f0381-47-528-x86_32.msi

Our library (libopenshot) now opens up a socket to communicate with our UI (openshot-qt), and sends all debug output directly to the openshot_qt.log file.

**Steps:**
1) Download and install the latest version (mentioned above)
2) Preferences - Enable "Debug (Verbose)", and verify the "Debug (Port)" preference appears (it's new)
3) Close OpenShot, and delete your log file (/Users/USER/.openshot_qt/openshot_qt.log)
4) Launch OpenShot, and make it crash as quickly as possible (to keep the log small)
5) Check the log file (and be sure it contains output like this... "logger_libopenshot:INFO"
6) Attach that .log file with instructions on what you did to cause the crash (if anything)
7) I'll fix the bug, and we'll all celebrate =)

**Comment by dancetheskies** [comment]
Ugh!  It's getting worse!  I did the new debug version download and installation (after uninstalling the old version), and now OpenShot will not even boot up without a host of errors.  I've attached the dialog that pops up when I try to run the program.  Exiting the error message exits the run attempt.
![openshotruncraash](https://cloud.githubusercontent.com/assets/16670296/14316259/10df7ad2-fbd0-11e5-96e6-dea25ed61572.JPG).  Am I doing something wrong?  I'll try a new download of the installer in case it got mashed during the prior D/L.

**Comment by nwgat** [comment]
i get the same error , its either a typeo of _openshot or the module is missing

**Comment by jonoomph** [comment]
Hmmm, sounds like the installer is broken due to some of my new debugging code. Let me test it on a few different systems, and see if I can reproduce this error.

**Comment by jonoomph** [comment]
Good news, I was able to reproduce the same error. It was strange, because it works fine when installed "over" the old version. But if I uninstall first, and then install fresh, I get the same error you do. 

Oh... I see the problem, I'm missing one of the most important files: libopenshot.dll.  Hahah, that might be a problem. Let me fix this real quick. =)

**Comment by jonoomph** [comment]
Okay, fixed the installer issue with the missing libopenshot.dll. Please give this version a try: http://releases.openshot.org/windows/OpenShot-v2.0.7-3-gb0f0381-47-528-x86_32.msi (same URL, but new installer). Thanks!

**Comment by telelauro** [comment]
I just installed this new version jonathan, without removing the latest version, perhaps it is better to remove and reinstall from scratch ?, you think?
Anyway, I just try to install this version you  left, but it seems that problems are not solved ... Besides the videos are in slow motion, it is not displayed at normal speed, and image stutters .
Cheer up! luck!

**Comment by dancetheskies** [comment]
With the latest version I no long get those crash messages.  But I also cannot get the video to play smoothly (or at all) in the preview window.  I've made splits with no error messages, but transitions do no take effect.  The window just stops responding to program mousse inputs it seems. ??????

**Comment by jonoomph** [comment]
@dancetheskies Please delete your /.openshot_qt/openshot_qt.log file, enable debug mode in preferences, re-launch OpenShot, and trigger the crash (or freeze). The freeze should also be visible in the log, if it's stuck in a loop (or something similar). Once you have crashed it (or froze it), please attach the openshot_qt.log file here.

Fingers crossed we can quickly see what is happening. =)

**Comment by dancetheskies** [comment]
OK, I have attached a crash file.  Note I changed the file type from .log to .txt to get it accepted as an attachment here.  This crash happened after I loaded a 1080p-30 fps .mp4 clip (AVC codec), made a couple of slices to remove a section of the clip, then slid the pieces together with a slight overlap on the time line for a faded transition.

FWIW, I was able to load the same file, trim off the tail end to shorten it, and export the file successfully... the first time I have actually gotten an export to go to completion.  We're getting close, though my clips play ragged in the program preview window with about 1 second of smooth play, then a fraction of a second pause, then repeats like that for the duration of the play back.  Maybe it's due to the debug code in the program or it could be my 2 year old Surface Pro 2 tablet PC resources?  The exported .mp4 AVC (high quality) file plays fine and looks great.
[openshot-qt.txt](https://github.com/OpenShot/openshot-qt/files/213214/openshot-qt.txt)

**Comment by telelauro** [comment]
Acabo de hacer la misma operación;
1) he insertado dos ficheros en openshot
2) los he añadido al proyecto de video.
3) automaticamente se ha creado sin problema la transicion
4) he reproducido el proyecto. La reproduccion ha sido muy lenta... y no
muy seguida
5) a los 20 segundos se ha colgado y ha dado un error que adjunto a
continuacion.




2016-04-11 16:58 GMT+02:00 dancetheskies <notifications@github.com>:

> OK, I have attached a crash file. Note I changed the file type from .log
> to .txt to get it accepted as an attachment here. This crash happened after
> I loaded a 1080p-30 fps .mp4 clip (AVC codec), made a couple of slices to
> remove a section of the clip, then slid the pieces together with a slight
> overlap on the time line for a faded transition.
>
> FWIW, I was able to load the same file, trim off the tail end to shorten
> it, and export the file successfully... the first time I have actually
> gotten an export to go to completion. We're getting close, though my clips
> play ragged in the program preview window with about 1 second of smooth
> play, then a fraction of a second pause, then repeats like that for the
> duration of the play back. Maybe it's due to the debug code in the program
> or it could be my 2 year old Surface Pro 2 tablet PC resources? The
> exported .mp4 AVC (high quality) file plays fine and looks great.
> openshot-qt.txt
> <https://github.com/OpenShot/openshot-qt/files/213214/openshot-qt.txt>
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenShot/openshot-qt/issues/140#issuecomment-208385696>
>



-- 
"Dabilen kamerari Kroma-keyrik ez"

**Comment by jonoomph** [comment]
@dancetheskies You can also compress your log file and attach it (i.e. *.zip / *.tar, etc...). Just a tip. I'll take a look at your log file once it finishes downloading. =)

**Comment by nwgat** [comment]
@jonoomph hey how about using [crashrpt ](http://crashrpt.sourceforge.net)on windows, while launchpad on linux?

**Comment by jonoomph** [comment]
@nwgat That does look interesting. I don't think it supports MinGW though. I might also just roll my own crash report dialog, when I detect a crash. That way I can have a consistent experience for all users, and for myself. 

I just made some really big changes to the way libopenshot logs debug output. I would appreciate it a bunch, if you (and everyone on this thread) can install the latest daily build of OpenShot (www.openshot.org/download - click **Other Installers**), and trigger a crash with this new version.

You should now have 2 log files (in your /.openshot_qt/ folder):
- **openshot_qt.log** - This is the interface-related debug output
- **libopenshot.log** - This is all libopenshot-related debug output (which is where most crashes are happening), and will hopefully reveal the class/method that is triggering the crash.

**Comment by dancetheskies** [comment]
OK, I loaded the latest version dated 4/12/2016 and find it much less stable than the prior version I was testing.  I simply imported an H.264 .mp4 file, dragged it to the time line, and tyried to do a simple slice saving both sides.  The program appeared to lock up going into a constant busy loop (program not responding and circle busy icon rotating)..  When clicked on the window icon to close the program I got the "usual" error messages.
Here's the debug logs: 
[Crash Logs.zip](https://github.com/OpenShot/openshot-qt/files/216365/Crash.Logs.zip)

**Comment by nwgat** [comment]
crash when exporting mp4 (x264)
[libopenshot.log.txt](https://github.com/OpenShot/openshot-qt/files/216988/libopenshot.log.txt)
[openshot-qt.log.txt](https://github.com/OpenShot/openshot-qt/files/216989/openshot-qt.log.txt)

**Comment by nwgat** [comment]
another crash for 4k files after dragging them to timeline
[libopenshot.txt](https://github.com/OpenShot/openshot-qt/files/217055/libopenshot.txt)
[openshot-qt.txt](https://github.com/OpenShot/openshot-qt/files/217056/openshot-qt.txt)

**Comment by jonoomph** [comment]
@nwgat Have you watched your memory utilization when these crashes happen? I'm just curious if the program is running out of memory (perhaps a memory leak).

**Comment by jonoomph** [comment]
@dancetheskies @nwgat Both of your libopenshot.log files end with this line:
`FFmpegReader::ProcessVideoPacket (After)`

I'm guessing this is the beginning of a pattern I'm about to see with libopenshot.log files being sent to me. =) So, I'm going to make the assumption that this log message is the last "successful" line of code, and it never makes it to the next log message. I'll see if I can come up with anything... and if not, I'll just add more debug messages until we find this. Thanks again for your help!

**Comment by dancetheskies** [comment]
Here's another set of log files following a "launch.exe stopped working" error message after loading a clip, slicing in two places, dragging the pieces over the slice points for transitions, and then running from the start.  The crash occurred before after about 15 seconds before getting to the first transition point as I recall.

**Comment by dancetheskies** [comment]
Now having an issue uploading my zipped log files.  Re-trying...

**Comment by nwgat** [comment]
openshot uses 1.3GB memory out of 32GB, so i dont think its a memory *leak*, meybe it runs out of memory because of 32-bit executable ? the files are *huge* at 4096x2160 and 25.4GB

btw @jonoomph uploading log files here on github is a mess, they dont allow .log so we need to rename them to .txt, adding .log to zip is not allowed either, so i would like to have a dialog in openshot that uploads to a https server, you can get https certificates from https://letsencrypt.org
it would been useful to zip or 7z them to save space to upload faster

**Comment by jonoomph** [comment]
I've fixed a pretty serious race condition yesterday, and would love for some help testing it out. 
Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot. Thanks!

If it still crashes, please attach logs. @nwgat I probably do need to create a "Report Bug Dialog", which automatically renames, compresses logs, and posts it to GitHub (something to ease the pain of reporting the results of a crash). I'll add it to my list... which seems to grow every day. =)

**Comment by dancetheskies** [comment]
I've tested the latest build.  Booted it, dragged an .MP4 clip to the program, then to the time line, pressed the preview play button, and watched.  The program crashed in about 5 seconds with the normal "launch.exe stopped working" error dialog.  Hmmm....  What other dire issues lay hidden within?  Is this only happening on a few Windows PCs?  Only on W10 PCs?
[Crash logs.zip](https://github.com/OpenShot/openshot-qt/files/232976/Crash.logs.zip)

**Comment by saluk** [comment]
I've been having similar issues, but after downloading the latest download (2.0.7.22) playback seems a lot smoother. I'm experience the export problem however (https://github.com/OpenShot/openshot-qt/issues/151)

**Comment by jonoomph** [comment]
Sorry for the long delay... had a few things I was working on. =) I've made some pretty big changes to how video frames are parsed (and/or skipped), and things seem much, much more stable now (for me at least). Please give the newest preview build a try and let me know if this new build works better. Thx!

Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot.

**Comment by telelauro** [comment]
Hi !
I just try the newest version, and it is better... now the preview is correct but when I made export in 16% was chrashe ... but now I can edit the project. IT´S seams greate !!! ANIMO JONATHAN!!! 
gracias por tu trabajo, parece que funciona mucho mejor, ahora podremos ir editando sin tantos fallos y limar mejor el programa, UN ABRAZO y te mandamos fuerzas desde mi colegio!!

**Comment by wydevices** [comment]
Gracias Telelauro!!!

-----Mensaje original-----
De: "telelauro" <notifications@github.com>
Enviado: ‎04/‎07/‎2016 23:10
Para: "OpenShot/openshot-qt" <openshot-qt@noreply.github.com>
Asunto: Re: [OpenShot/openshot-qt] Beta 4.0 now crashes worse than Beta 3.0.on my W10 (x64) desktop PC! (#140)

Hi !
I just try the newest version, and it is better... now the preview is correct but when I made export in 16% was chrashe ... but now I can edit the project. IT´S seams greate !!! ANIMO JONATHAN!!! 
gracias por tu trabajo, parece que funciona mucho mejor, ahora podremos ir editando sin tantos fallos y limar mejor el programa, UN ABRAZO y te mandamos fuerzas desde mi colegio!!

**Comment by hydra009** [comment]
[openshot-qt.log.txt](https://github.com/OpenShot/openshot-qt/files/448390/openshot-qt.log.txt)

I have downloaded the latest daily build and am still having the same problem as with previous versions, which is that Launch.exe crashes when moving from one point to another on the timeline. 

Attached is the log file. 

Thanks in advance for your help. :)

**Comment by nwgat** [comment]
how do you move on the timeline?, did you trys imply clicking where you want it? that seems to be more stable than dragging the red line

**Comment by jonoomph** [comment]
We have recently made a ton of improvements for video freezing and crashes, and I would like to verify this issue still occurs with our latest daily build. Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot. 

If the issue still occurs, please reopen this issue and attach log files (https://github.com/OpenShot/openshot-qt/blob/master/.github/CONTRIBUTING.md), and hopefully we'll be able to nail this down and fix it. Thanks!
