### ISSUE TITLE
Tutorial: Resolve path blender MacOS

### ISSUE THREAD

**Issue by timanagement** [OpenShot/openshot-qt#1400]
PT-Br 

Ajustar o caminho para o Blender no MacOS

1º - “Localize a pasta do blender em Aplicativos”
![1](https://user-images.githubusercontent.com/18239673/37683354-20ef7f26-2c6b-11e8-867d-b65a644f6be2.png)

2º - Clique com o botão direito e escolha mostrar conteúdo do pacote
![2](https://user-images.githubusercontent.com/18239673/37683355-2115d522-2c6b-11e8-8716-3a2bf4cec377.png)

3º - Depois de mostrar o conteúdo do pacote, abra a pasta Contents
![3](https://user-images.githubusercontent.com/18239673/37683356-2139770c-2c6b-11e8-884e-10f5d3221e1c.png)

4º - Depois de abrir a pasta Contents abra a pasta MacOS
![4](https://user-images.githubusercontent.com/18239673/37683357-215dc594-2c6b-11e8-9e02-5a8d208444cf.png)

5º - Coloque uma janela do terminal ao lado e arraste o binário do blender
	e solte-o no na janela do terminal.  Isto fará com que o caminho dele
seja mostrado, como se estivesse digitado.
![5](https://user-images.githubusercontent.com/18239673/37683358-217f90e8-2c6b-11e8-9050-3a926f100d6e.png)

6º - Ao realizar o 5º procedimento o resultado será:
	Eis o caminho para copiar e incluir nas configurações do OpenShot:
	/Applications/Blender/blender.app/Contents/MacOS/blender
	Copie-o e cole no local apropriado nas configurações do Openshot
![6](https://user-images.githubusercontent.com/18239673/37683359-21a0a1c0-2c6b-11e8-917d-44cb33b81067.png)

![7](https://user-images.githubusercontent.com/18239673/37683624-f9c01752-2c6b-11e8-964f-ec854efc5b09.png)

EN-US 

Adjusting the path to Blender on MacOS

1º - “Locate the blender folder in Applications”
![1](https://user-images.githubusercontent.com/18239673/37683354-20ef7f26-2c6b-11e8-867d-b65a644f6be2.png)

2º - Right-click and choose Show Package Contents
![2](https://user-images.githubusercontent.com/18239673/37683355-2115d522-2c6b-11e8-8716-3a2bf4cec377.png)

3º - After showing the contents of the package, open the Contents folder
![3](https://user-images.githubusercontent.com/18239673/37683356-2139770c-2c6b-11e8-884e-10f5d3221e1c.png)

4º - After opening the Contents folder open the MacOS folder
![4](https://user-images.githubusercontent.com/18239673/37683357-215dc594-2c6b-11e8-9e02-5a8d208444cf.png)

5º - Attach a terminal window to the side and dragão the blender binary
	and drop it on the terminal.

	This will make your path displayed as if typed.
![5](https://user-images.githubusercontent.com/18239673/37683358-217f90e8-2c6b-11e8-9050-3a926f100d6e.png)

6º - When performing the 5th procedure the result will be:

	Here's the way to copy and include in the OpenShot settings:

	/Applications/Blender/blender.app/Contents/MacOS/blender

	Copy and paste it into the appropriate location in the Openshot settings

![6](https://user-images.githubusercontent.com/18239673/37683359-21a0a1c0-2c6b-11e8-917d-44cb33b81067.png)

![7](https://user-images.githubusercontent.com/18239673/37683624-f9c01752-2c6b-11e8-964f-ec854efc5b09.png)

**System Details:**
* Operating System / Distro: macOS High Sierra
* OpenShot Version: 2.4.1

Contribuindo com pouco em agradecimento ao muito recebido...

Contributing with little in thanks to the much received...

**Comment by peanutbutterandcrackers** [comment]
@timanagement - Thank you for the explanation. I hope this helps others too. I'll try to point others to this explanation. Hope you continue to contribute to this project, good sir!

**Comment by DylanC** [comment]
@timanagement - This is great, it will help lots of Mac users.

**Comment by EmptyVessel-NZ** [comment]
@timanagement  Just adding my thanks, this worked for me also. :)

**Comment by adilsonsf** [comment]
Obrigado, isto funcionou perfeitamente para mim.

Thanks so much, that worked fine for me.

![image](https://user-images.githubusercontent.com/37127293/39475633-5de89c52-4d2f-11e8-99f9-788e344602ab.png)

**Comment by DylanC** [comment]
I put in a change to have browse buttons in future. This will work better in newer releases:
https://github.com/OpenShot/openshot-qt/pull/2255

**Comment by AndyOhhh** [comment]
This doesn't work for me. I'm Mojave 10.14 and experiencing a similar issue with teh path to Incscape. Any suggestions are welcome, thanks.

**Comment by flagsoft** [comment]
Does not work on with OpenShot 4.4.0 on macOS Mojave with Blender 2.80.

**Comment by flagsoft** [comment]
> > Problem: Does not work on with OpenShot 2.4.4 on macOS Mojave 10.14.5 with **Blender 2.80**.
> > Solution: **Blender version 2.79b works.**
> > Maybe a calling convention problem?
> 
> The new version of macOS Mojavi depreciated OpenGL in order to force the adoption of the Metal API;
> 
> Maybe this explains your case.

No, on the same system with Blender version 2.79b it works... so.... ?

**Comment by flagsoft** [comment]
> > > > Problem: Does not work on with OpenShot 2.4.4 on macOS Mojave 10.14.5 with **Blender 2.80**.
> > > > Solution: **Blender version 2.79b works.**
> > > > Maybe a calling convention problem?
> > > 
> > > 
> > > The new version of macOS Mojavi depreciated OpenGL in order to force the adoption of the Metal API;
> > > Maybe this explains your case.
> > 
> > 
> > No, on the same system with Blender version 2.79b it works... so.... ?
> 
> Maybe, but I can't confirm this.

Maybe or maybe not. So let us stop guessing (!) ;) We need a SOLUTION.

**Comment by paulgaborro** [comment]
Thank you!
Saved my day!
