### ISSUE TITLE
Crash reading project Mac OS

### ISSUE THREAD

**Issue by DavidBrams** [OpenShot/openshot-qt#1401]
Hello,

info : 

  Nom du modèle :	MacBook
  Identifiant du modèle :	MacBook8,1
  Nom du processeur :	Intel Core M
  Vitesse du processeur :	1,2 GHz
  Nombre de processeurs :	1
  Nombre total de cœurs :	2
  Cache de niveau 2 (par cœur) :	256 Ko
  Cache de niveau 3 :	4 Mo
  Mémoire :	8 Go

* OpenShot Version: 2.4.1
* _Please attach log files if crash_ : no file crash

I made a project today i saved on my desk, i can open it but it just crash when i want to read it.
I specify that i didnt moove the different files of the project on my desk, when i did it yesterday (to save them in a folder), i couldnt then open the project (log fils "file not found..." something like this).

Too bad, Openshot is really easy to use...

Thanks for your help,

David

**Comment by DylanC** [comment]
@DavidBrams - Are you sure you didnt' move any of the source files used to make the project?

**Comment by DavidBrams** [comment]
Absolutly certain.








David Brami | CEO

Siege social : 47 rue de Saint Genès
33000 Bordeaux – France

De :  DylanC
Répondre à :  OpenShot/openshot-qt
Date :  vendredi 23 mars 2018 10:20
À :  OpenShot/openshot-qt
Cc :  Brami David, Mention
Objet :  Re: [OpenShot/openshot-qt] Crash reading project Mac OS (#1401)


@DavidBrams - Are you sure you didnt' move any of the source files used to make the project?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

  
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/OpenShot/openshot-qt","title":"OpenShot/openshot-qt","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/OpenShot/openshot-qt"}},"updates":{"snippets":[{"icon":"PERSON","message":"@DylanC in #1401: @DavidBrams - Are you sure you didnt' move any of the source files used to make the project? "}],"action":{"name":"View Issue","url":"https://github.com/OpenShot/openshot-qt/issues/1401#issuecomment-375590738"}}}

**Comment by DavidBrams** [comment]
Absolutly certain. 

Envoyé de mon iPhone

**Comment by DylanC** [comment]
@peanutbutterandcrackers - Any ideas here?

**Comment by peanutbutterandcrackers** [comment]
I would like to see a screen-shot of the 'file not found' error. I think we can suggest a work-around.

**Comment by DavidBrams** [comment]
Sorry but skip it guys, i finaly used another soft and did not kept any screen shot. 
Thanks again and good luck 

Envoyé de mon iPhone
