### ISSUE TITLE
Tabs all gone!! Help please!

### ISSUE THREAD

**Issue by ZacWizard** [OpenShot/openshot-qt#1403]
Hey Guys, I was trying to make a video but i closed some of the tabs (All by accident) Is there anyway to fix it? Because i need to make my video :(

(I am using openshot video editor, basically the standard one) 

![capture432](https://user-images.githubusercontent.com/37691751/37821106-cefa2b3a-2ed6-11e8-9bea-3b7940a62382.JPG)
 
Please help me :(

**Comment by ZacWizard** [comment]
Thank you @DylanC  for the help!

**Comment by ZacWizard** [comment]
@DylanC how do i close this topic :(

**Comment by DylanC** [comment]
@ZacWizard - No problem. Happy to help. I can close this for you. 😃
