### ISSUE TITLE
How to cut a part out of a movie

### ISSUE THREAD

**Issue by danmop** [OpenShot/openshot-qt#1404]
How to cut out a clip in the middle of a movie.
I am watching a movie in the timeline and found a bad part I want out at e.g. 1min to 1.10min.
and then continue watching the movie and remove more bad clips? 

Can I mark to parts on the timeline and click remove?

**Comment by DylanC** [comment]
@danmop - Use the icon with the **scissors**.  You can click that icon, then click where you want to make the first "cut". Click again later in the clip to make another cut. On the middle clip you can right click and clip to remove the clip. 

I hope my description makes sense to you.

**Comment by danmop** [comment]
got it thanks
