### ISSUE TITLE
Unable to install Daily Build 52

### ISSUE THREAD

**Issue by MrTertius** [OpenShot/openshot-qt#1405]
**System Details:** Intel i5 Processor, Integrated GPU, 4GB RAM
* Operating System / Distro: Windows 10
* OpenShot Version: 2.4.1-52
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
I can't install Openshot 2.4.1-52

**Comment by peanutbutterandcrackers** [comment]
@MrTertius - It would be better if you could provide more details. What does it say? What error does it give? Screenshots, too perhaps. Thanks!

**Comment by MrTertius** [comment]
Ok, I have downloaded the Daily build, as well as removing the old files, i double click the installer, then i noticed it started to lag, and when it was half way done, it froze at the halfway point, i tried re-lauching the installer and it did the same thing, i will try again and then provide the screenshots

**Comment by peanutbutterandcrackers** [comment]
I see. Could you also try daily build 51 instead of 52 then? Or some other one? Just to see how they behave...

**Comment by MrTertius** [comment]
Yes, i will try that

**Comment by peanutbutterandcrackers** [comment]
Awesome! You can be our awesome windows beta-tester!

**Comment by MrTertius** [comment]
It will be an honour

**Comment by peanutbutterandcrackers** [comment]
It would be awesome to work with you too, good sir. This is, after all, a labour of love of a single man and we - as a community - need to help each other out, as much as possible. :)

**Comment by MrTertius** [comment]
I will try to report as much bugs as possible to make Openshot the best Video Editor ever :)
