### ISSUE TITLE
Issues with setting the bitrate of a video that is made with images (not other videos)

### ISSUE THREAD

**Issue by TheLEGObrick** [OpenShot/openshot-qt#1406]
**System Details:**
* Operating System / Distro: Windows 10
* OpenShot Version: 2.4.1
**Issue Description and steps to reproduce:**

I'm trying to set a good bitrate for a video I make of some pictures along with sound files (essentially a slideshow with sounds), but no matter what I set the video bitrate to, OpenSoft exports the video with ~6820 kbps bitrate. So, I have no idea if this is an intended feature or a bug, anyone care to explain?
![image](https://user-images.githubusercontent.com/29981196/37831597-c6139858-2eae-11e8-992a-01d0cf1d3a27.png)
^ What I set the bitrate to be as
![image](https://user-images.githubusercontent.com/29981196/37831534-89d44bda-2eae-11e8-8e1b-7b3eee21376f.png)
^ What the bitrate actually is after exporting

**Comment by TheLEGObrick** [comment]
Update: Something that's even more messed up is that if I use mpeg4 instead of h.264, the bitrate is actually reduced to some degree, however, even that isn't consistent; setting the bitrate to 1 Mb/s results in a total bitrate of 2057 kbps, while using 384 kb/s causes the total bitrate to become 1960 kbps, and both of the "versions" have 1863 kbps data bitrate

**Comment by MrTertius** [comment]
I have noticed the same thing, one of my videos were 1.03GB big

**Comment by N3WWN** [comment]
I just played with this a bit and it seems that the `Bit Rate / Quality` setting in the `Advanced` tab is informational, reporting the bitrate that will be used at the current `Quality` setting.  

You can adjust the bitrate using the `Quality` dropdown on the `Simple` tab, selecting `High`, `Med` or `Low`.

To test this, I just exported a 10 sec video with all three settings:

- High
  - 15359717 bytes (15.4 MB)
  - 12039 kb/s (video bitrate according to ffprobe)
- Med
  - 5661007 (5.4 MB)
  - 4376 kb/s (video bitrate according to ffprobe)
- Low
  - 1762132 (1.8 MB)
  - 1302 kb/s (video bitrate according to ffprobe)

So, it looks like the values in the `Advanced` tab should either not be writable or should update the preset.

**Comment by N3WWN** [comment]
A little more info... 

You *can* adjust the bitrate in the `Advanced` tab, apparently, but it looks like it's only a hint to the renderer;  If I set the bitrate to `25 Mb/s` or `115 Mb/s`, the rendered bitrate is not much higher than the default `High` quality of 15 Mb/s.

Likewise, if I set the bitrate to `0.1 Mb/s`, the rendered bitrate is no lower than the default `Low` quality of 384 kb/s.

**Comment by MrTertius** [comment]
So, allow me to explain it again:

If i go to the Simple Tab and change the Quality there and then go to Advance to change the bitrate, then the file size will be smaller if thats what you mean

**Comment by N3WWN** [comment]
@MrTertius It appears that you can change one or both with varying results on my system.   

I'm working with the github master source code version of OpenShot, built from scratch on Ubuntu Linux.  It seems the `Bit Rate / Quality` setting in the `Advanced` tab trumps everything, but is still only a hint to the renderer.

While I haven't tested this with any of the published 2.4.1 AppImages recently, I do know that I witnessed the Bit Rate in the `Advanced` tab having no bearing on the rendered file with the AppImages in the fall of 2017.  

I'll have to see if something has changed in the last few months with how these values are used.

Sorry for the confusion. 😕

**Comment by MrTertius** [comment]
I tried lowering the bitrate and ended up with over a Gigabyte of video size

**Comment by gary9872** [comment]
I would agree with @N3WWN regarding Advance Tab having no bearing in 2017. But it seems to work now correctly. 

To my knowledge Openshot only does one pass. It is impossible to obtain the bitrate you want with only 1 pass. Can someone confirm or deny this for me?

**Comment by jurajsomorovsky** [comment]
This was still an issue for me (OpenShot 2.4.3 running on KUbuntu 20.04).
The bit rate quality in the advanced tab setting had no influence on the resulting mp4 size, independently of the value I used (note that the audio bit rate config worked for me). I ended up converting the resulting video bitrate manually using the command line, e.g.:
```
ffmpeg -i input.mp4 -b:v 300k output.mp4
```
Note that the resulting video quality is not exactly the same in the output file but you can easily play with the values.

(I know this is a closed issue but all google searches led me here, so hopefully, it will help somebody)

**Comment by ferdnyc** [comment]
@jurajsomorovsky I can buy that, with 2.4.3, and I realize unfortunately that's still the official distro package version even in Ubuntu 20.04 / Debian 11.

I've been [trying to sell them](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=925754) on packaging a current release, but it seems like every time we point them at an update that will fix their _current_ build problems with the older versions, they leapfrog us to some **newer** bleeding-edge tools that we haven't released support for yet. The latest was GCC 9, which thwarted our long-standing attempts to get OpenShot 2.4.4 packaged. The released libopenshot-audio versions didn't build under GCC 9 until 0.1.9, which was released with OpenShot 2.5.0 earlier this year.

I think we're finally in good shape, though. OpenShot 2.5.1 should be compatible with even GCC 10 and whatever else they want to throw at it, so maybe we'll finally see an official package update some time soon. (Hope so, too, because the AppImage builds have been having some compatibility issues with 20.04 / 11 as well, and it really would be simpler for users to just run a native package.)

**Comment by jurajsomorovsky** [comment]
Ok, thank you for the info. I just installed 2.5.1 from the ppa and can confirm that everything works :)
