### ISSUE TITLE
Choose profil AUTOMATIC: I suggest for OPENSHOT 2.0 (BETA 5)

### ISSUE THREAD

**Issue by telelauro** [OpenShot/openshot-qt#141]
IMPORTANT: I suggest a significant improvement Jonathan.
This note is important. I've noticed that if a project before starting the profil choose well, the program is more stable. So I suggest,
1) make public and notify users of Openshot
2) Like a others video editors (pinnacle) : When you select a file in the new project, the first frame is key to automatically selecionar the profile choice. It is difficult to know exactly witch is each video camera has for each format.
If I had that option would automatically be pretty good, though, I have to say that would avoid many faults when working in Openshot. Well, I've noticed that if you choose a right profile, failures are less.

**Comment by jreynojustin** [comment]
OpenShot is now in Version 2.2 if you are still noticing issues in the latest version please re-open this issue letting us know.
