### ISSUE TITLE
Lost preview screen

### ISSUE THREAD

**Issue by ghost** [OpenShot/openshot-qt#1413]
I'm using Openshot on a PC and I pressed a button that I thought would take me to full screen. Instead, I've somehow ended up with nothing on my screen except the "track 4 track 3 track 2" screen. Can someone please help me get the actual video back?

**Comment by Blay3** [comment]
It happened to me too and sorry but I can't figure it neather. Someone please help

**Comment by peanutbutterandcrackers** [comment]
Go to View > Views > Simple View. Everything will go back to normal. Hope that helps! :)

**Comment by Blay3** [comment]
Yeah i did it myself without reading this with a bit of luck
thanks anyways
