### ISSUE TITLE
Jerky playback

### ISSUE THREAD

**Issue by theelectricsoul** [OpenShot/openshot-qt#1414]
**System Details:**
* Operating System / Distro: Win Server 2016
* OpenShot Version: 2.4.1

My machine handles x264 in 4k easily. Playback is jerky compared to Shotcut or any videoplayer with HWA disabled. You guys probably know that. 

Thanks for awesome software :)

**Comment by peanutbutterandcrackers** [comment]
Could you please try out the latest [daily build](https://github.com/OpenShot/openshot-qt/releases/tag/daily) and see if that works for you? Thanks!

**Comment by theelectricsoul** [comment]
[Video](https://streamable.com/vikdk)
Look for yourself. Openshot has also a higher CPU load.
Thanks a lot  :)

**Comment by peanutbutterandcrackers** [comment]
Thank you for the video. That is some good issue reporting.

However, it seems that you're using version 2.3.4-dev1 while the latest stable release is v2.4.1-dev1. Please upgrade it first. If even that doesn't work, head over to OpenShot's [download page](https://www.openshot.org/download/), and click on the 'daily build' button (those are the versions that are built every time something is done to the OpenShot source code), download and install the latest daily build.

Please do report if this problem persists even there. Preview works fine for me on the latest version of OpenShot on my Linux machine.

Hope that helps!

**Comment by theelectricsoul** [comment]
great.. I downgraded :)   Ok...   now I tested the lastest build for sure. 

Playback is good....   :)
