### ISSUE TITLE
Openshot Unable To Support Quicksync Encoded Videos

### ISSUE THREAD

**Issue by MrTertius** [OpenShot/openshot-qt#1417]
**System Details:** Intel i5 Processor, Integrated GPU, 4GB RAM
* Operating System / Distro: Windows 10
* OpenShot Version: 2.4.1-52
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
When a Quicksync Encoded Video is imported to Openshot and added to the timeline, the preview goes out of sync with the audio.

**Comment by peanutbutterandcrackers** [comment]
We'll try to get the devs attention to this issue too. Thanks for your help in making OpenShot better, good sir!
