### ISSUE TITLE
Animated title error

### ISSUE THREAD

**Issue by Michellebear** [OpenShot/openshot-qt#1419]
I use Mac OS 10.12
The latest vision of Openshot
The latest vision of  Blender

set the correct path of preference: /Applications/blender.app/Contents/MacOS/blander

Some animated title work well, but some can't like Exploding Text.
It showed "No frame was found in the output from Blender"

What should I do?

**Comment by philiplb** [comment]
Are you sure about "/Applications/blender.app/Contents/MacOS/blander"?
Because "blander" would be a typo of "blender".

**Comment by Michellebear** [comment]
/Applications/blender.app/Contents/MacOS/blender
sorry , i typed wrong in my question

**Comment by peanutbutterandcrackers** [comment]
You might want to follow [this tutorial](https://github.com/OpenShot/openshot-qt/issues/1400). It was posted recently and has helped a lot of Mac users. Hope it helps you too!

**Comment by DylanC** [comment]
@Michellebear - Yes, follow the advice in #1400
