### ISSUE TITLE
What i can do if this comes out

### ISSUE THREAD

**Issue by loock21** [OpenShot/openshot-qt#1421]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

**Comment by peanutbutterandcrackers** [comment]
Good sir, I think you've forgotten to attach a screenshot (and add more description).

**Comment by DylanC** [comment]
@loock21 - Please add more details to this. Closing until we have more details.
