### ISSUE TITLE
Which Settings Do I Use? 

### ISSUE THREAD

**Issue by MrTertius** [OpenShot/openshot-qt#1422]
**System Details:** Intel i5 Processor,  Integrated GPU
* Operating System / Distro: Windows 10
* OpenShot Version: 2.4.1-53
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
Hello,  i need help regarding the rendering settings, can anyone tell me what Bitrate i should use to render a 200MB 720p video?

**Comment by N3WWN** [comment]
There are a lot of variables which go into determining the final output size of a video.  The codec, how much motion needs to be encoded (this relates to the codec), the resolution, frame rate, constant vs variable bit rate, duration, etc.

Unfortunately, without knowing a lot about each of these variables, it's very difficult to determine the final file size in a single pass.  

Think of two scenarios:

*Scenario # 1* - a 2 hour video of a slide show taken directly from the presentation software (i.e. Power Point)

*Scenario # 2* - a 15 minute video of a white-water rafting trip taken with a GoPro attached to the head of one of the people on the raft

The first scenario has very little in the way of frame-to-frame differences to encode and a full resolution video may take only 100 MB (50 MB/hr or 111 kbps).

The second scenario has constant panning, tilting, rotation and LOTS of movement to encode between each frame.  This is a lot of work for the encoder to minimize the data and could easily result in a low resolution video requiring, say, 2 GB of storage (8 GB/hr or 17.8 Mbps).

**Comment by MrTertius** [comment]
But what bitrate do i use, 25Mbps?

**Comment by N3WWN** [comment]
If your video can be encoded at exactly 25 Mbps, then you can produce a 64 second long video:

Since there are 8 bits in a byte:

25 Mbps = 3.125 MBps

Now that we know that we're rendering 3.125 MB each second, we can find out how long before we fill 200 MB of storage with this video:

200 MB / 3.125 MBps = 64.0 s

**Comment by MrTertius** [comment]
I have tested out some options and it looks like in Advanced Mode, Openshot adds more MB to a 1 Minute Video, in Simple mode i have found out that the Medium Quality Setting has the right Size to a file increasing a 18.3MB Video File to 53.9MB
