### ISSUE TITLE
How do i see the videos frames? 

### ISSUE THREAD

**Issue by MrTertius** [OpenShot/openshot-qt#1423]
**System Details:** Intel i5 Processor, Integrated GPU, 4GB RAM
* Operating System / Distro: Windows 10
* OpenShot Version: 2.4.1-53
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
How do i see the video frames on the timeline?

**Comment by gary9872** [comment]
Look closely at the time. The last set of numbers is not tenths of a second but rather the current frame rate, in that second.

**Comment by MrTertius** [comment]
A screenshot may be helpful

**Comment by qubodup** [comment]
I'm afraid you can only see it in the counter but never on the timeline

![openshot timeline clip](https://user-images.githubusercontent.com/18312/38000894-2d0c32f8-322a-11e8-8739-d6e5336807e0.png)

**Comment by MrTertius** [comment]
Ah thank you, now i know where the frames are
