### ISSUE TITLE
Precise playhead control in timeline

### ISSUE THREAD

**Issue by qubodup** [OpenShot/openshot-qt#1424]
Usability issue.

As a video editor, often you want clips to have exact durations or start at exact time values, for this you need to be able to move the playhead precisely quickly.

The only way to precisely position the playhead is to click and then use left/right arrow keys to set the time code.

The time code should be editable.

Clicking it should not move the playhead to frame 0

**Comment by peanutbutterandcrackers** [comment]
I absolutely think this would be wonderful. I'll try to get the devs attention to this, ASAP. Thanks!

**Comment by sid1950** [comment]
When editing long form, or working with long rushes this is a must. I have a 90 minute recording with 3 pages of shot logs and no quick way to get to the shots!
