### ISSUE TITLE
Start timeline at 0

### ISSUE THREAD

**Issue by qubodup** [OpenShot/openshot-qt#1426]
![OpenShot timeline start position](https://user-images.githubusercontent.com/18312/38001022-eab0c77e-322a-11e8-8d56-55a199a34110.png)

It seems common practice that the first frame has the time code 0 seconds 0 frames. OpenShot starts at 0 seconds, 1 frame.

Both make sense but starting at 0 appears to be the established default.

Examples of software that do this by default: Premiere, Shotcut, Filmora, Windows Movie Maker.

OpenShot should have the option to start at 0 and make it default for consistency.

**Comment by peanutbutterandcrackers** [comment]
@DylanC @ferdnyc @N3WWN - What do you think about this, good sirs?

**Comment by ferdnyc** [comment]
Having an option is _insane_, it would mean making the math conditional at **far** too many places in the code. If OpenShot switches to 0-based, fine, but then it should simply switch and stick with it. I have no strong preference either way, but I am vehemently opposed to the complexity of making it configurable.

**Comment by N3WWN** [comment]
I agree with @ferdnyc ... an option would likely introduce more problems than anything else.

I think we should have time **and** frame number as separate displayed values, not a combined time+frame.

**Comment by qubodup** [comment]
Thank you for your quick responses!

Premiere for example allows switching between (display?) modes. The standard is hh:mm:ss:frame

![Premiere's options 25fps](https://user-images.githubusercontent.com/18312/38032511-242755b8-329e-11e8-8ea1-e75355ffd6fb.png)

![Premiere's options 29.97fps](https://user-images.githubusercontent.com/18312/38032990-3914077c-329f-11e8-9e78-6bb54a42b4fa.png)

I think FCPX, Shotcut and Kdenlive have the same defaults (Kdenlive might be configurable, not sure).

![Final Cut Pro X](https://user-images.githubusercontent.com/18312/38033098-7abe7bb2-329f-11e8-9ccb-c2d4a577d12b.png)

Configurability *might* be a necessity for a video editor to be able to handle non-integer frame rates, see Premiere screenshot for 25fps project and 29.97 project above. (Pure speculation)

I don't know anything about programming video editors. It could be that configuring might be easier if display of time information is abstracted from internal calculation/use of time (perhaps it already is).

**Comment by DylanC** [comment]
@ferdnyc - So should we set this to be 0 by default? I'm getting lost in this discussion. :)

**Comment by qubodup** [comment]
> But the question of whether that time index is considered Frame 31 (1-indexed) or Frame 30 (0-indexed), and therefore whether the third representation should instead be 00:00:01s00frames (if it's 0-indexed), is fundamental to the internal representation of the data.

I see. I assumed it might be possible to - whenever timeline time information is used for display purposes, rather than internal calculations - simply subtract one frame from a time code before converting it to a human-readable display format.
