### ISSUE TITLE
Video Property Scaled to NONE actually does scale in preview, but exports properly

### ISSUE THREAD

**Issue by gary9872** [OpenShot/openshot-qt#1427]
As noted earlier by PRORACING-SK

Imported image when scaled to NONE shows a scaled image in preview, but exports at right scale.

Example

A profile with resolution of 792x192 is selected where all images are scaled to NONE.

An imported image with dimensions 512x129 is scaled to 792x192
An imported image smaller than 512x129 is scaled smaller than 792x192 incrementally
An image bigger than 512x129 is cropped incrementally. ie An image 792x192 is cropped ALOT.

**Comment by peanutbutterandcrackers** [comment]
Some screenshots would help the devs understand this issue better, IMHO, good sir.

**Comment by PRORACING-SK** [comment]
Everything can be seen here. This way it works not only in my profile but in all I tried. The distortion is more or less visible in various profiles.

![screen-shot](https://user-images.githubusercontent.com/37664665/38060111-8ff5db2a-32e9-11e8-8797-1e8395878a09.jpg)

**Comment by peanutbutterandcrackers** [comment]
@DylanC - Any thoughts on this? Should this be brought to Mr. Thomas's attention, ASAP?

@ferdnyc - Maybe you have some input regarding this, too?

@N3WWN - Any ideas, good sir?

**Comment by DylanC** [comment]
@peanutbutterandcrackers - Not sure about ASAP but this should be fixed I think.

**Comment by peanutbutterandcrackers** [comment]
@DylanC - All right then, I will count on you to bring this to Mr. Thomas's attention when the time is right, Cap'ain! :)

**Comment by N3WWN** [comment]
@PRORACING-SK Would you mind attaching the 4-1 image to the ticket as well as your Test Ratio osp file?

**Comment by PRORACING-SK** [comment]
Hi @N3WWN; Here are test images.

![4-1 768x192](https://user-images.githubusercontent.com/37664665/38568228-72406240-3ce8-11e8-9f49-166dbf3653d1.gif)

![4-1 515x129](https://user-images.githubusercontent.com/37664665/38568229-725ed4d2-3ce8-11e8-9476-89a10f3c5453.gif)

and the test profile (if it is the osp...)

[proracing_4_1.zip](https://github.com/OpenShot/openshot-qt/files/1895357/proracing_4_1.zip)

**Comment by ferdnyc** [comment]
I can't quite reproduce.

It's weird that your profile window doesn't show any _details_ for the profile. How was it created? Also, what are the OpenShot system details (version, OS, etc.)?

What I'm seeing in OpenShot 2.4.1 release, after creating a profile `$HOME/.openshot_qt/profiles/proracing_4:1` with the following contents:

```
description=PRORACING 4:1
frame_rate_num=25
frame_rate_den=1
width=768
height=192
progressive=1
sample_aspect_num=1
sample_aspect_den=1
display_aspect_num=4
display_aspect_den=1
```

Is that the preview is still 16:9 (an issue we know about), so it will be _clipped_ when using the wider profile... but it isn't distorted.

![screenshot from 2018-04-10 12-21-10](https://user-images.githubusercontent.com/538020/38570461-ea8a3820-3cbb-11e8-8428-4fda38443c63.png)
![screenshot from 2018-04-10 12-35-50](https://user-images.githubusercontent.com/538020/38570470-f1cbbed8-3cbb-11e8-86e0-cef99fef5c8a.png)
![screenshot from 2018-04-10 12-35-53](https://user-images.githubusercontent.com/538020/38570475-f4f28cf4-3cbb-11e8-9c3e-30c9e53e066b.png)
![screenshot from 2018-04-10 12-36-27](https://user-images.githubusercontent.com/538020/38570479-f781ccd2-3cbb-11e8-82e5-5f9926bef39a.png)
![screenshot from 2018-04-10 12-36-36](https://user-images.githubusercontent.com/538020/38570490-fc1751ea-3cbb-11e8-812c-19e93c96a35d.png)

**Comment by ferdnyc** [comment]
Are you running with the patches from PR #1407, by any chance? Those patches will distort the preview, unfortunately. See my last comment there.

**Comment by peanutbutterandcrackers** [comment]
This has been fixed by https://github.com/OpenShot/libopenshot/commit/e0ec60396592780110e5ca1ab930a0eaa9a7ff2
