### ISSUE TITLE
WINDOWS 2.07: Does not work, right click remove effect.

### ISSUE THREAD

**Issue by telelauro** [OpenShot/openshot-qt#143]
Does not work, right botton click remove effect in video flies.
And when I play the file with effect the reproduction is slow and crahs.
![no funciona quitar efectos 2 07](https://cloud.githubusercontent.com/assets/16803007/14140098/57e3af42-f677-11e5-941c-761d21648c6c.png)

**Comment by jreynojustin** [comment]
OpenShot is now in Version 2.2 if you are still noticing issues in the latest version please re-open this issue letting us know.
