### ISSUE TITLE
App crash on Windows 10

### ISSUE THREAD

**Issue by I-like-PI** [OpenShot/openshot-qt#1430]
**System Details:**
* Operating System / Distro: Windows 10
* OpenShot Version: 2.4.1

[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/1854223/openshot-qt.log)
![2018-03-27 1](https://user-images.githubusercontent.com/33037694/38002679-4823b466-31f9-11e8-8fa0-e04fb173d263.png)
![2018-03-27](https://user-images.githubusercontent.com/33037694/38002680-483966e4-31f9-11e8-89ba-f897eecff072.png)

**Issue Description and steps to reproduce:**

The Application "Openshot" has crashed twice and is very laggy. It doesn't matter what I do. If I do anything, the app will lag.

**Comment by peanutbutterandcrackers** [comment]
OpenShot has been known to be quite unstable in Windows 10 for some reason. But, the latest daily build has been reported to work rather well. So, please do try out the daily build. Please head over to the [downloads](https://www.openshot.org/download/) page and click on 'daily build' to download the latest daily build for your OS. Thanks!

**Comment by I-like-PI** [comment]
+peanutbuttercrackers The thing is, I downloaded and set up Openshot two days ago.

**Comment by I-like-PI** [comment]
also, does anyone know what could've caused a runtime error besides RAM?

**Comment by peanutbutterandcrackers** [comment]
Are you sure you are not using v2.4.1 but the latest daily build? Daily builds are versions of OpenShot built within 24 hours of *any* changes to the source code. You can get them from the [downloads](https://www.openshot.org/download/) page by clicking on the 'daily build' button.

Sorry, I don't really know about that.... This is definitely strange....

**Comment by peanutbutterandcrackers** [comment]
A similar issue would be #1296

**Comment by jholovacs** [comment]
Daily build crashes too.  Any time I set Youtube to be the target video profile.

**Comment by peanutbutterandcrackers** [comment]
@jholovacs - Do other profiles work? o.O Perhaps we should wait for a new daily build and see if that fixes this? Currently, work is underway to support ffmpeg3.2 (almost complete - just needs testing and stuff).... maybe once it is stable enough, things will go smoothly? o.O

**Comment by jholovacs** [comment]
If I leave the default settings completely alone, it doesn't crash... but it's defaulting to a pretty large video file, not really appropriate for uploading.

**Comment by peanutbutterandcrackers** [comment]
Hmm.... I see. Perhaps you might want to try out some other profiles, for the moment? Or, maybe wait a few days for some more stability related fixes to be merged into the source tree, if you have the time?

Sorry for the inconvenience.

**Comment by DylanC** [comment]
@I-like-PI - Can you try v2.4.2 and let us know if you have any success?
