### ISSUE TITLE
Select and deselect clips

### ISSUE THREAD

**Issue by amuellerde** [OpenShot/openshot-qt#1432]
Hello,

"ctrl+a" select all clips, "ctrl+shift+a" deseelect all.
when select all clips,  how can I cancel the selection for some clips?

**Comment by qubodup** [comment]
Curious. CTRL+Left Mouse Button allows you to add to a selection but not to remove from it.

**Comment by peanutbutterandcrackers** [comment]
That is exactly what I was thinking.

@ferdnyc - Any thoughts on this too, good sir?

**Comment by amuellerde** [comment]
I also was thinking, use CTRL+Left MB again.

**Comment by peanutbutterandcrackers** [comment]
@DylanC - Maybe this needs to brought to the devs attention, too?

**Comment by DylanC** [comment]
@peanutbutterandcrackers - Maybe at some point. Right now I would prefer to see more bug fixes get in to the next release. Its a good idea for sure.

**Comment by peanutbutterandcrackers** [comment]
Alright then, Cap'ain!

**Comment by sahin52** [comment]
This issue still exists.
