### ISSUE TITLE
Option to add Text

### ISSUE THREAD

**Issue by MrTertius** [OpenShot/openshot-qt#1433]
**System Details:** Intel i5, Integrated GPU, 4GB RAM
* Operating System / Distro: Windows 10
* OpenShot Version: 2.4.1-53
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
There needs to be an option where you can add text on the timeline that show up in the preview

**Comment by N3WWN** [comment]
Titles can already be used to do this, but the text shows up in the preview **and** in the rendered video.

Is your request for text that is only visible in the preview and not rendered into the final rendered video?

**Comment by DylanC** [comment]
@MrTertius - You can do this already. Just add a Simple Title.
