### ISSUE TITLE
Clip Duplicates When An Action Is Undone

### ISSUE THREAD

**Issue by MrTertius** [OpenShot/openshot-qt#1434]
**System Details:** Intel i5, Integrated GPU, 4GB RAM
* Operating System / Distro: Windows 10
* OpenShot Version: 2.4.1-53
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
Whenever a undo an action on a clip, the clip duplicates

**Comment by peanutbutterandcrackers** [comment]
This hasn't really happened to me... Could you please provide screenshots and stuff, too?

**Comment by DylanC** [comment]
@peanutbutterandcrackers - I think I have seen something like this before. Not that the clip duplicates but the undo goes back 2 steps instead of 1. (So it looks like it duplicates)

**Comment by peanutbutterandcrackers** [comment]
Oh... I've seen that with track-renaming and deletion...

Perhaps this is also a critical bug that needs to be fixed? Maybe we should reopen it, @MrTertius ?
