### ISSUE TITLE
Openshot Crashes When A Transition Is Added

### ISSUE THREAD

**Issue by MrTertius** [OpenShot/openshot-qt#1435]
**System Details:** Intel i5 Processor, Integrated GPU, 4GB RAM
* Operating System / Distro: Windows 10
* OpenShot Version: 2.4.1-53
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
When i add a transition, Openshot crashes

**Comment by peanutbutterandcrackers** [comment]
Similar issue reported in #1296

**Comment by peanutbutterandcrackers** [comment]
@DylanC - Does this need to be brought to @jonoomph's attention ASAP? Or should be wait for some other changes to fix this? o.O

**Comment by DylanC** [comment]
@peanutbutterandcrackers - If I can reproduce then maybe.

**Comment by peanutbutterandcrackers** [comment]
All right then. Will be looking forward to your results.

**Comment by AndyX90** [comment]
Problem still exists in actual daily build.

**Comment by peanutbutterandcrackers** [comment]
I have notified a developer about this. Hope this will be resolved soon. Thanks for your patience!

**Comment by bouda19** [comment]
Hi,

I have installed the last version of openshot (OpenShot-v2.4.2-dev1) and the issue still persist.

Operating System / Distro: Windows 10
OpenShot Version: v2.4.2-dev1
Please attach log files

[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/2250530/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2250531/openshot-qt.log)

**Comment by peanutbutterandcrackers** [comment]
@bouda19 - Does this issue still persist with the current daily builds?

**Comment by bouda19** [comment]
@peanutbutterandcrackers I've just tested with the last version and the issue is fixed. Thanks
