### ISSUE TITLE
Title template / Inkscape Version (0.92.3)

### ISSUE THREAD

**Issue by PASTJL** [OpenShot/openshot-qt#1436]
Windows / Linux
Daily Build (53)
When launching Advanced Editor, on a Title, I get the message
![screenshot_20180329_084134](https://user-images.githubusercontent.com/2668291/38073892-398f2fae-332d-11e8-8c0c-75d2bc7dfe3d.png)

**Comment by PASTJL** [comment]
Certainly, the templates need to be updaed ...

**Comment by DylanC** [comment]
@PASTJL - Yes I think so. Leave it with me and I will see what can be done.

**Comment by DylanC** [comment]
@PASTJL - I have a fix put in for this. It should be solved in the daily builds soon.
