### ISSUE TITLE
In Ubuntu Gnome Classic (flashback) menu bar is not visible

### ISSUE THREAD

**Issue by alexgabi** [OpenShot/openshot-qt#144]
![openshot-qt_no_menu_bar](https://cloud.githubusercontent.com/assets/6351555/14156759/623eebea-f6c8-11e5-8db2-e73d873e50a8.png)

**Comment by jonoomph** [comment]
This is probably a bug with Ubuntu and the appmenu-qt5 package: https://bugs.launchpad.net/ubuntu/+source/appmenu-qt5/+bug/1307619. Ubuntu's appmenu-qt5 package automatically removes the top menu from all Qt5 apps, and moves it to the top of the screen (or wherever). So, if the menu is removed from OpenShot, this is the only reason I can think of.

Please take a look at that package, and maybe try removing it (do so at your own risk though... =)). Good luck!

**Comment by alexgabi** [comment]
sudo apt-get remove appmenu-qt5

and now openshot-qt menu bar looks OK.
Thank you
