### ISSUE TITLE
Audio Bug Is Really Getting Annoying!

### ISSUE THREAD

**Issue by WolfieMar** [OpenShot/openshot-qt#1440]
Remember When I Had A Problem With The Audio That It Stops At Almost The End? Its Very Annoying. Like Its In Some Of My Video's! And Its Very Annoying. Check Out My Video: https://www.youtube.com/watch?v=duFurMz02LU And Skip To 1:45. Its Annoying! Please Make An Update For Windows To Fix This!

**Comment by peanutbutterandcrackers** [comment]
Please try the latest dalily build. v2.4.1 has got quite a lot of bugs on Windows. But the latest daily build has been reported to work rather well. Please head over to the [downloads](https://www.openshot.org/download/) page and click on the 'daily builds' and grab the latest one. That should help you out. Thanks!

P. S: Nice video!

**Comment by DylanC** [comment]
@WolfieMar Can you try v2.4.2 and let us know if you have any success?
