### ISSUE TITLE
Cannot extend track after resetting time

### ISSUE THREAD

**Issue by theelectricsoul** [OpenShot/openshot-qt#1441]
**System Details:**
* Operating System / Distro: Win Server 2016
* OpenShot Version: 2.4.1.dev1

[Video](https://streamable.com/crgbt)

**Comment by peanutbutterandcrackers** [comment]
@DylanC - I can confirm this one. Same thing happens to me too.

I think the speeding functions need some more stability. I [couldn't keyframe speed](https://github.com/OpenShot/openshot-qt/issues/1198), too. 

Do you think this to be critical enough to be considered for the checklist? o.O

**Comment by peanutbutterandcrackers** [comment]
So, the video that the OP posted isn't available anymore. So, I am going to go ahead and close this so as to have the discussions be followed up over at #1819, for now.
