### ISSUE TITLE
How to mess up a splitted track after time transformation

### ISSUE THREAD

**Issue by theelectricsoul** [OpenShot/openshot-qt#1442]
**System Details:**
* Operating System / Distro: Win Server 2016
* OpenShot Version: 2.4.1 dev1

https://streamable.com/copjw

**Comment by peanutbutterandcrackers** [comment]
You might want to click on 'reset time' in the dropdown, on the second time. That will reset the time changes made to the clip. Hope that helps!

[What's happening is, the clip x4 is the clip running four times faster
and the clip running x4 x1 is clip running four times faster running at normal (x4) speed]

**Comment by theelectricsoul** [comment]
The point of the video is to show how to mess up a track, and not to figure out whats going on ;) Usability is key :)

**Comment by theelectricsoul** [comment]
problem persist with 2.4.1-53

**Comment by theelectricsoul** [comment]
I tested again. The bug is, that you cannot extend a track that has been sped up. This will create noise.

**Comment by peanutbutterandcrackers** [comment]
Okay. I think I'll have to notify the devs about this, then.

Thank you for your patience!

**Comment by DylanC** [comment]
@theelectricsoul Can you try v2.4.2 and let us know if you have any success?
