### ISSUE TITLE
Crashing OVS after playing a moved video fragment

### ISSUE THREAD

**Issue by theelectricsoul** [OpenShot/openshot-qt#1443]
**System Details:**
* Operating System / Distro: Win Server 2106 
* OpenShot Version: 2.4.1 dev1

https://streamable.com/5zwfm

Sry... the keyword "crash" did not return results in help. No idea where the crash log is.

**Comment by peanutbutterandcrackers** [comment]
Here is how you attach log files: [contributing guilelines](https://github.com/OpenShot/openshot-qt/blob/master/.github/CONTRIBUTING.md).

And I suggest you try out the latest daily build. Just head over to the [download](https://www.openshot.org/download/) page and click on the 'daily builds' and grab the latest one and see if that works.

Thanks!

**Comment by theelectricsoul** [comment]
tested 2.4.1-53 as seen in the video of the first post
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/1863717/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/1863718/openshot-qt.log)

**Comment by peanutbutterandcrackers** [comment]
I wonder if it is happening because you are overlapping the left clip over the right, while the normal way to do it is to overlap the right clip over the left? Just a thought. I tried doing the same kind of overlapping here on my machine, and OpenShot did crash after a while....

@DylanC @ferdnyc @N3WWN - I think we've stumbled upon an interesting problem here, gentlemen.

**Comment by theelectricsoul** [comment]
I pinpointed the bug.

https://streamable.com/awnb5

**Comment by peanutbutterandcrackers** [comment]
@theelectricsoul - I see that you put the video on the left over the right. Which is not what us normal users do, normally. Could you try to see if you tried to do the overlapping normally ---- i.e. by putting the video clip on the right side *over* the video on the left one --- and see if the bug can be reproduced then?

Sorry for the late reply. I've not been able to come around to github lately.

If you can replicate the bug even then, I will let the devs know about this right away.

Sorry for the inconvenience.

**Comment by theelectricsoul** [comment]
@peanutbutterandcrackers 

As mentioned in the [last](https://github.com/OpenShot/openshot-qt/issues/1443#event-1550659058) video, it doesn't matter if you overlap from left to right, or right to left. 

--------------
But you got me wondering. No offense really, but let me get your reply straight. Are you saying, that you are willing not to consider reporting a bug that will make the user lose changes to their project, because you are convinced that nobody else on this planet but me will overlap from left to right?


It doesn't matter at the moment, but the reason why I even discovered this bug, was because I had to move a track aside, to make space for just a moment. I wanted to move the track back, but the software obviously crashed before I could do that.

**Comment by peanutbutterandcrackers** [comment]
It isn't like that. There are only 2 active developers who are squirring time away to work on OpenShot. And I already have given them a truck load of list of issues to fix. That is why I am a bit reluctant about reporting this to the devs right away.
This is a community project, good sir. Each of us scratching each other's back. And things won't really go that fast. I understand that it is frustrating. But please be patient. I will get devs notified about this issue, ASAP.

You might want to [attach the logs](https://github.com/OpenShot/openshot-qt/blob/master/.github/CONTRIBUTING.md), too, good sir. That will help the devs fix this.

**Comment by theelectricsoul** [comment]
> What I mean by 'report this to the devs' is to let them know that this is an uber high priority bug that needs a fix really soon

Nice :) Then I'll keep reporting bugs :)

**Comment by peanutbutterandcrackers** [comment]
Thank you! :)

Please do note that we are all squireling our time away here. So, it might take a while before these bugs are actually fixed, good sir!

I hope you keep on loving/supporting/using OpenShot to make amazing videos!

**Comment by N3WWN** [comment]
I just tried this with daily build `2.4.1-53` and OpenShot behaved the way that it should and did not crash.  

The main difference is that I did this on Fedora Linux instead of Windows, so the bug may be limited to Windows users.

**Comment by ferdnyc** [comment]
Agreed, I've performed that exact operation literally dozens of times and OpenShot has never crashed on me. But I'm also on Fedora.

I notice you're using `.m2ts` format video (from a Blu-Ray source, perhaps?), I wonder if it could be a decoder problem? Does the same thing happen with other video formats (say, MP4)?
