### ISSUE TITLE
How to Transitions work? 

### ISSUE THREAD

**Issue by MrTertius** [OpenShot/openshot-qt#1446]
**System Details:** Intel i5 Processor, Integrated GPU, 4GB RAM
* Operating System / Distro: Windows 10
* OpenShot Version: 2.4.1-53
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
How do the transitions work?

**Comment by peanutbutterandcrackers** [comment]
Perhaps [this](https://github.com/OpenShot/openshot-qt/issues/1012#issuecomment-364615674) might help you out?

**Comment by peanutbutterandcrackers** [comment]
Maybe [this](https://www.youtube.com/watch?v=mgi4esWA84M&t=298s) and [this](https://www.youtube.com/watch?v=Hd9k3x0diOo&t=1s), too?
