### ISSUE TITLE
Every time a tutorial window pops up, it forces the application out of maximized

### ISSUE THREAD

**Issue by jholovacs** [OpenShot/openshot-qt#1447]
**System Details:**
* Operating System / Distro: Windows 10 Pro
* OpenShot Version: 2.4.1
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

**Comment by peanutbutterandcrackers** [comment]
@DylanC - Dup of #307 

@jholovacs - Thank you for the report; this has already been brought to the devs attention and we hope this will be resolved soon. Thanks for your patience!

**Comment by ferdnyc** [comment]
@peanutbutterandcrackers You can probably add this issue to the testing pool for #1726 .

**Comment by ferdnyc** [comment]
@peanutbutterandcrackers : please close as dup of... some other Tutorial-problems bug. And also as fixed in 2.4.2, actually.

**Comment by peanutbutterandcrackers** [comment]
Closing as fixed in 2.4.2 and as a dup of #736
