### ISSUE TITLE
Video splitting issue

### ISSUE THREAD

**Issue by sspmrsomebody1** [OpenShot/openshot-qt#1448]
Processor: Intel(R) Core(TM) i7-4500 CPU @ 1.80GHz 2.40 GHz
RAM: 8GB (7.89GB usable)
System type: 64-bit Operating System, x64 based processor
Windows 8.1, OpenShot 24.1

VIDEO OF ISSUE (3 mins): https://youtu.be/Mx7Fc4tsnXk
I have a track at 2x speed, I slice it then put the 2nd part back to normal speed.
When I reset the speed (or change it to 1X) the 2 track parts no longer match up; the video in the second part shows video present in the previous part.
Also please add a progress bar for those of us who experience freezing when editing in OpenShot.

**Comment by peanutbutterandcrackers** [comment]
Could you perhaps make a separate issue for the 'progress bar' (with some screenshots from other softwares, hopefully) so that we could add an 'enhancement' label to it?

I'm not so sure about the issue... Maybe someone else can help you out? 

@DylanC - any thoughts here?

**Comment by DylanC** [comment]
@peanutbutterandcrackers - Certain video clips are causing a lack of precision with libopenshot. This sounds like a similar case. Further info from Mr.Thomas is on slack.

**Comment by peanutbutterandcrackers** [comment]
Hope this will be fixed ASAP. :)

**Comment by sspmrsomebody1** [comment]
Also it would be nice if waveforms (like in kdenlive) & continuous thumbnails for videos (like in Movie Maker or iMovie) were added to clips.

Also I found a WORKAROUND to the bug:
Instead of speeding up the whole thing then slicing it up & putting some clip slices back to 1x speed, do the slicing first then put 2x speed on the bits you want to speed up.

**Comment by sspmrsomebody1** [comment]
eg

**Comment by peanutbutterandcrackers** [comment]
If you want continuous thumbnails, perhaps the best idea would be to open another issue so that we can label it as an 'enhancement' so as to keep things organized. Thanks!
