### ISSUE TITLE
Openshot will not do anything

### ISSUE THREAD

**Issue by Chipfo** [OpenShot/openshot-qt#1449]
**System Details:**
* Operating System / Distro: ? Windows 8.1
* OpenShot Version: ? Downloaded today
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

I am used to using windows movie maker but I am new to openshot. I cannot get it to respond to anything, I can drag and drop videos in the project files box but other than that it won't play them or do anything. Do I need to uninstall and reinstall?

**Comment by peanutbutterandcrackers** [comment]
I suggest you use the latest daily build. Daily builds are versions created by the build server as soon as there is any change in the source code. To get the latest daily build, head over to the [downloads](https://www.openshot.org/download/) page, and click on the 'daily builds' button and grab the latest one.
The daily builds have been reported to work rather well on windows too, which, for the moment seems to be the most problematic platform for OpenShot, which works rather well on Linux Distros.

I hope that helps!

**Comment by peanutbutterandcrackers** [comment]
P. S: You'll have to uninstall current version and install the latest daily build. Just in case that's confusing.
Thanks!

**Comment by Chipfo** [comment]
Thank you I will try the daily build.

**Comment by Chipfo** [comment]
No, still not responding to anything

**Comment by peanutbutterandcrackers** [comment]
Sorry for the inconvenience. Could you please read the [contributing guidelines](https://github.com/OpenShot/openshot-qt/blob/master/.github/CONTRIBUTING.md) and attach the logs? That could help the devs fix this issue. Thanks!

**Comment by DylanC** [comment]
@Chipfo - What PC hardware do you have?

**Comment by DylanC** [comment]
Closed due to lack of activity.
