### ISSUE TITLE
Surface more useful error messages on export failure

### ISSUE THREAD

**Issue by ferdnyc** [OpenShot/openshot-qt#1450]
Currently when the export process aborts, the user is shown the "Export Error" dialog. It contains a generic message about the type of error encountered:
> Sorry, there was an error exporting your video:
> Error while writing raw video frame

That "error type" is also logged in `openshot-qt.log`
> export:INFO Error type string: Error while writing raw video frame

(Only!) if OpenShot is in **debug** mode, `libopenshot.log` will include a `write_video_packet` message containing the _reason_ why the write failed, e.g.:
> FFmpegWriter::write_video_packet ERROR [No space left on device] (error_code=-28.0000)

There are two issues with that.
1. The application shouldn't have to be in debug mode for libopenshot to log an **error** message.
1. The exact **reason** for the error (in this case, "No space left on device") should be displayed to the user in the "Export Error" dialog, in addition to (always) being logged.

**Comment by DylanC** [comment]
@ferdnyc - This is very true, I agree.

**Comment by DylanC** [comment]
@jonoomph - Would this be a useful change to make soon? (ish)
