### ISSUE TITLE
Severe memory leak

### ISSUE THREAD

**Issue by andreyskrypnik** [OpenShot/openshot-qt#1452]
* System Details:
* Operating System / Distro: Linux Mint 18.3 Cinnamon
uname -a:
Linux promus-big 4.13.0-37-generic #42~16.04.1-Ubuntu SMP Wed Mar 7 16:03:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
CPU: Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
RAM: 8 Gb
SWAP: 14 GB

* OpenShot Version: OpenShot-v2.4.1-x86_64.AppImage or from a PPA
* _Please attach log files if crash_

When you start and work with a small project, memory consumption is constantly growing (about 100 megabytes in 15-20 seconds). The program fills all the RAM, and then the entire SWAP. This situation arises both with AppImages and with the program from the PPA.

I do not know where the AppImage applications store logs

**Comment by DylanC** [comment]
@andreyskrypnik - Thanks for the report. The logs exists inside HOME/.openshot_qt

**Comment by peanutbutterandcrackers** [comment]
[This guide](https://github.com/OpenShot/openshot-qt/blob/master/.github/CONTRIBUTING.md) might be of some help, too. :)

**Comment by andreyskrypnik** [comment]
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/1885757/openshot-qt.log)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/1885760/libopenshot.log)

**Comment by andreyskrypnik** [comment]
These are logs from Linux Mint. A similar problem arose on Arch Linux.

**Comment by peanutbutterandcrackers** [comment]
Perhaps attach those too, good sir? I'll try to notify the devs regarding this.

**Comment by andreyskrypnik** [comment]
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/1888675/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/1888676/openshot-qt.log)

This is LOG with Arch Linux. I try to do the same on it. The last work went well with a small file (just swap and RAM did not have time to fill up to the end). And before the last work the same situation as in Linux Mint.

**Comment by peanutbutterandcrackers** [comment]
Thank you! I have notified a developer regarding this. Hope he can sort this out, too. Soon. :)
