### ISSUE TITLE
Black frames before the transition

### ISSUE THREAD

**Issue by aseques** [OpenShot/openshot-qt#1456]
**System Details:**
* Operating System / Distro: ? Windows 10
* OpenShot Version: ? 2.4.1

**Issue Description and steps to reproduce:**
Insert a transtition at any point in the middle of a clip. At the begin of the transition until the mid, the screen is black, then the effect starts until the view is normal.

![imatge](https://user-images.githubusercontent.com/555542/38168108-e1c640be-3543-11e8-8b8d-d7a72f76be56.png)

This is the effect it produces.

![openshot_transition](https://user-images.githubusercontent.com/555542/38168087-52a3f214-3543-11e8-909e-bba6e434e844.gif)

**Comment by DylanC** [comment]
@aseques - Yes, I think you are not using transitions for how they were intended to be used. Try the advice from @peanutbutterandcrackers

**Comment by aseques** [comment]
This is just an example, the same effect happens when  I add the transition to the end of a fragment of a video to fade the video to black, so I can add the title just after. Do you want another example showing the effect?

**Comment by peanutbutterandcrackers** [comment]
@aseques - So this is how you apply a transition correctly:
![correct_transition_openshot](https://user-images.githubusercontent.com/26764547/38455200-a30078d0-3a94-11e8-9710-2b26923ace1a.png)
And these are some ways how you can apply a transition incorrectly:
![incorrect2](https://user-images.githubusercontent.com/26764547/38455204-b2574df4-3a94-11e8-9970-1c3b645e3139.png)
![incorrect1](https://user-images.githubusercontent.com/26764547/38455205-b2dca9b8-3a94-11e8-96f3-5780a8a2ba18.png)
I hope that helps! :)

**Comment by aseques** [comment]
@peanutbutterandcrackers  I understand what you mean, but it's not properly working (at least in windows), see this capture:
![imatge](https://user-images.githubusercontent.com/555542/38455533-def77624-3a79-11e8-80aa-c328002ec42d.png)

There's a static image until 00:17, just after this one there's another one. I add the transition from there until 00:27, the first two seconds (until 00:19) the video is totally black. The effect I want is the following:

- 00:17 until 00:22 going from normal to black
- 00:22 until 00:27 gorin from black to normal (with the second picture)
I can upload the project if you want

**Comment by peanutbutterandcrackers** [comment]
Good sir, you actually have to overlap the two clips by dragging the right clip over the left one. Doing so will also add an automatic transition which you can remove and replace with a transition of your choice (from the 'transitions' tab), in which case, you'll have to make sure you apply them correctly (as pointed out in the screenshots in my previous comment). Hope that helps!

**Comment by aseques** [comment]
@peanutbutterandcrackers then it's a bug isn't it? When clip A i followed immediately by clip B there's no black interval. When I add the transtition it appears the black interval. Your solution might be a workaround, but the bug is still present. (unless I haven't yet understood how transitions are suposed to work)

**Comment by peanutbutterandcrackers** [comment]
Good sir, OpenShot has been designed to have a transition only when two videos overlap each other. And when you add a transition, you have to add it so that the beginning of transition is at the *exact* beginning of the 2nd clip. Or else there would be a black interval. Please look at the screenshots I have provided in my previous comment for proper placement of transitions. This is not a bug. I hope that helps. :)

**Comment by aseques** [comment]
That's what I am doing I add the transition to start at 00:17, just the same time I add the second clip.

**Comment by aseques** [comment]
If I have two clips with audio (home recordings) and I want a transition from clipA to clipB but I need them not to overlap (because I would lose the ambient audio. How should I proceed? Isn't it accomplished by at transition?

**Comment by peanutbutterandcrackers** [comment]
You might want to use keyframes, then, good sir. But it might take a bit of learning. However, once you master keyframes, a whole new world of possibilities will open up to you and OpenShot, with it's *everything is keyframe-able* approach will become your favorite video editor of all time (except for the stability issues which will soon be fixed).
You might want to go through the items on [the list](https://github.com/OpenShot/openshot-qt/issues/1477#issuecomment-379473284) that I recently posted for another new user.

Hope that helps, good sir! :)

**Comment by aseques** [comment]
If it's the intended way of working then close this issue, I still don't understand the rationalle of this choice, but I can't comment more on this. Thanks anyway

**Comment by peanutbutterandcrackers** [comment]
@aseques - Good sir, if you have a suggestion, then please do explain. This is an open source project. The community has a say on how things will go forward. If you have a better idea, please explain (with illustrations, too, hopefully). Perhaps the devs will like and implement it? :)

**Comment by N3WWN** [comment]
I also like to fade in/out between multiple clips.  I put the clips on different tracks and do the following:

Top clip -> Right Click -> `Fade` -> `End of clip` -> `Fade Out (Fast)`
Bottom clip -> Right Click -> `Fade` -> `Start of clip` -> `Fade In (Fast)`

Then, I align the keyframes on the two clips by dragging the bottom clip to the left until the left edge of the bottom clip is aligned with the fade out keyframe (green mark) of the top clip.

Here's the end effect:

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/19431804/38504465-c54bde62-3be2-11e8-9ec0-315a2d900479.png">

How much or little your overlap the two clips can change how the fade in/out looks to match your needs or preference.

**Comment by aseques** [comment]
Thanks a lot @N3WWN , this is what I was looking for

**Comment by peanutbutterandcrackers** [comment]
I'm so glad you found what you were looking for @aseques!

Awesome!

Hope you create amazing videos using OpenShot!

@N3WWN - You're awesome!!!

**Comment by maysu1914** [comment]
Hi @peanutbutterandcrackers, this bug is appear in my setup too, and I made a project like you showed above. This is your project:

![38455200-a30078d0-3a94-11e8-9710-2b26923ace1a](https://user-images.githubusercontent.com/49559010/60244650-80e44900-98c3-11e9-8f68-d2a8ec172037.png)

and this is my project:
![2](https://user-images.githubusercontent.com/49559010/60244730-b0935100-98c3-11e9-9f04-499d10f29521.png)

but the result is this:
![ezgif-1-52d630090ea7](https://user-images.githubusercontent.com/49559010/60244555-4d092380-98c3-11e9-8325-0f9af11fc217.gif)

I really want to know where is my mistake. Thank you.

OS: Windows 10 Pro 64 bit 1809
Program Version: OpenShot 2.4.4 64 bit
