### ISSUE TITLE
Speeding up a clip cannot be changed easily (time→fast→forward)

### ISSUE THREAD

**Issue by MarcelWaldvogel** [OpenShot/openshot-qt#1457]
**System Details:**
* Operating System / Distro: Linux/Ubuntu 17.10
* OpenShot Version: 2.4.1 (and nightly)

**Issue Description and steps to reproduce:**

1. Right click on a clip and select Time→Fast→Forward→(any of 2X, 4X, 8X, 16X, 32X)  
This speeds up the clip accordingly
1. Change the speed to something else, because it was not the right speed  
That factor is *multiplied* with the previous speed
1. Try to get back to the original speed by right-clicking and selecting Time→Reset time  
Nothing happens
1. Try again, differently: Time→Normal→Forward→1X  
The clip grows by a few percent

So, the first operation does what is expected, but none of the later operations (I tried in several orders) seem to be able to change this the way I expect it to happen. And I would guess that others have similar expectations.

**Comment by PorcelainMouse** [comment]
I think I'm experiencing this.

**Comment by peanutbutterandcrackers** [comment]
@DylanC - Perhaps this should be marked as a bug and aimed at resolving in the next releases?

**Comment by JanisE** [comment]
I agree on the feature hard to use.

I want to speed up the video exactly 60 times. I have only options 2X, 4X, 8X, 16X. I would get 60X by applying 8X and 5X, only there is no 5X (although I've seen it in some older screenshots on Google; I'm using the 2.4.4 Linux version right now).

If I look at the Time value among the clip's properties, firstly, I don't understand what it means. When I'm applying the nX speeds on the context menu, sometimes the value changes, but I do not see relation easily.

Secondly, when I'm applying the nX speeds, often, the Time value does not change at all. It just gets painted green, but the value stays `1`, even if I click on 8X repeatedly and see the clip getting shorter on the timeline.

**Comment by cdalexndr** [comment]
It would be nice if the time speedup feature is moved to video properties, like a "Time Warp" entry that can be modified to any value.
