### ISSUE TITLE
When I undo a slice there's this wierd extra bit of clip

### ISSUE THREAD

**Issue by sspmrsomebody1** [OpenShot/openshot-qt#1458]
Processor: Intel(R) Core(TM) i7-4500 CPU @ 1.80GHz 2.40 GHz
RAM: 8GB (7.89GB usable)
System type: 64-bit Operating System, x64 based processor
Windows 8.1, OpenShot 24.1

I slice a video, undo the action and instead of just unslicing, it puts another duplicate piece of clip on top of the unsliced one, a little snippet which is identical to the bit of unsliced clip beneath it.

Video (1 min): https://youtu.be/stkbV4Z529E

**Comment by peanutbutterandcrackers** [comment]
Thank you for the good report.

@DylanC - I can confirm this, Cap'ain!

**Comment by DylanC** [comment]
@peanutbutterandcrackers - Yeah I have seen this one before. I think this one may be a duplicate of an older report. Maybe a dup of #934
