### ISSUE TITLE
openshot silently exits if used, imported files are renamed or deleted.

### ISSUE THREAD

**Issue by jstnlth** [OpenShot/openshot-qt#146]
When opening an .osp file, if any of the items imported into the project are missing, then playback (pressing play on the video preview) causes OpenShot to exit.  

I would expect OpenShot to do a sanity check upon loading the .osp to make sure that the imported files exist, and to notify the user if any were missing - especially ones that have actually been used in the tracks.  Currently the user has absolutely no clue why all their work just "crashes" OpenShot.

**Comment by jonoomph** [comment]
Sanity check has been added in our latest daily builds. It now prompts for where to find the missing file, and removes it from the project if the user can't find it (thus... no crash). Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot. Thanks!
