### ISSUE TITLE
Chrome Key Effect Now Causes Errors In Openshot

### ISSUE THREAD

**Issue by MisterTeeXD** [OpenShot/openshot-qt#1462]
**System Details:** Intel i5, Integrated GPU, 4GB RAM
* Operating System / Distro: Windows 10
* OpenShot Version: 2.4.1-55
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

The Chroma Key Effect has now caused some breaking errors, it crashes Openshot when i open a project and it crashes the Microsoft Runtime Component, all these errors have now made the Chroma Key Effect useless to use

**Comment by peanutbutterandcrackers** [comment]
@MrTertius - Please do not close this issue until it has been resolved, good sir. It will seem that this issue has already been resolved if you close it prematurely.

Could you please kindly [attach the logs](https://github.com/OpenShot/openshot-qt/blob/master/.github/CONTRIBUTING.md), please? Thanks!

**Comment by MrTertius** [comment]
Ok i had trouble finding the log files but i then clicked the link you added here, just for clarification:

I see 3 log files of openshot-qt.log.(number)
a single .log text file
a openshot.settings file
and a libopenshot.log file. 

Which of these files do i attach to an issue?

**Comment by DylanC** [comment]
@MrTertius - These are the files:

openshot-qt.log
libopenshot.log

**Comment by MrTertius** [comment]
Ahh ok, i will remember to attach these if i ran into any problems
