### ISSUE TITLE
OpenShot crashes when trying to open/play a recent project

### ISSUE THREAD

**Issue by santiki** [OpenShot/openshot-qt#1463]
**System Details:**MacBook Pro 2.5ghz i7
* Operating System / Distro: macOS 10.13.3
* OpenShot Version: 2.4.1
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

**Comment by DylanC** [comment]
@santiki - Did you see any error message appear?

**Comment by santiki** [comment]
No error message, the program just shuts down. Project shows across the bottom, but when I try and play it, it just closes.

**Comment by peanutbutterandcrackers** [comment]
Perhaps you might want to [attach the logs](https://github.com/OpenShot/openshot-qt/blob/master/.github/CONTRIBUTING.md), good sir!

**Comment by DylanC** [comment]
Closed due to lack of details.
