### ISSUE TITLE
My OpenShot Video Editor Doesn't Work Anymore...

### ISSUE THREAD

**Issue by itsLolo14YT** [OpenShot/openshot-qt#1464]
**System Details:**
* OpenShot Version: 2.4.1
* _Please attach log files if crash_
https://user-images.githubusercontent.com/38043220/38254873-a2347eca-375a-11e8-9d1a-6ede84eddade.png
**Issue Description and steps to reproduce:**
My OpenShot Video Editor is broken.... How do I fix this...?

**Comment by DylanC** [comment]
@itsLolo14YT - Hi there, I think you must delete the preferences folder. See here for a similar issue that has been resolved: #1330

**Comment by DylanC** [comment]
@itsLolo14YT - Basically find the folder called: .openshot_qt in the same folder that contains My Documents, My Pictures, My Videos etc. and delete it.
