### ISSUE TITLE
Gif Is a still image, Can't fix

### ISSUE THREAD

**Issue by adswan** [OpenShot/openshot-qt#1465]
I use a laittitude 6420 and the newest version of openload. I just downloaded today, and I cant seem to get gifs to run properly. A gif will just be the first frame as a picture. Is there something you have to do to get them to animate?

**Comment by N3WWN** [comment]
Animated GIFs are not currently supported by OpenShot as animations.

What I have done in the past is to convert the animated GIF to a video format with a tool like ffmpeg:
`ffmpeg -i ~/animated.gif ~/animated.mp4`

**Comment by DylanC** [comment]
Dup of #558

**Comment by adswan** [comment]
N3WWN, thank you. I did not know that gifs aren't supported. Much appreciation.

DylanC, Sorry, I tried looking if someone had asked but I guessed I missed it XD

**Comment by DylanC** [comment]
@adswan - Its okay. I had the same issue with Gifs in a recent project. Its possible we will fix this in the future for sure!
