### ISSUE TITLE
No audio when exporting file for web

### ISSUE THREAD

**Issue by dbstlouis** [OpenShot/openshot-qt#1466]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
I edited a existing video (interview with audio) and when we attempted to export for web posting there is no audio. What specs are required to ensure audio is preserved?

**Comment by DylanC** [comment]
@dbstlouis - I had this same issue recently. What export profile did you use?

**Comment by dbstlouis** [comment]
I was using HDV 1440i 29.97 fps

**Comment by DylanC** [comment]
@dbstlouis - What did you select as output format on the export dialog?

**Comment by peanutbutterandcrackers** [comment]
Perhaps the audio is there but your media player does not have the ability to decode the audio encoded using the encoder that OpenShot used? I suggest you try playing the video with [VLC Media Player](https://www.videolan.org/vlc/index.html), just to make sure it is not what I imagine it is. Similar issue has happened to me too, before. But it was the media player's fault. Hope that helps!

**Comment by DylanC** [comment]
@dbstlouis - Are you using v2.4.1 or a daily build?

**Comment by DylanC** [comment]
Marking as a bug since I did have this issue too.

**Comment by DylanC** [comment]
@dbstlouis Can you try v2.4.2 and let us know if you have success? A change was put in for the audio issues.
