### ISSUE TITLE
OpenShot crashes during export

### ISSUE THREAD

**Issue by KaylynnStrain** [OpenShot/openshot-qt#1469]
**System Details:**
* Operating System / Distro: ?  Windows 10
* OpenShot Version: ?  2.4.1
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
crashes every time I try to export a finished edited video, occasionally my computer itself will crash and restart

**Comment by DylanC** [comment]
@KaylynnStrain - Do you see any error message from Openshot?

**Comment by peanutbutterandcrackers** [comment]
You might also want to [attach the logs](https://github.com/OpenShot/openshot-qt/blob/master/.github/CONTRIBUTING.md). Thanks!

**Comment by DylanC** [comment]
Closing until we have more details.
