### ISSUE TITLE
[Improvement Needed] Enhance Chroma Key

### ISSUE THREAD

**Issue by MrTeeXD** [OpenShot/openshot-qt#1472]
**System Details:** Intel i5 processor, Integrated GPU, 4GB RAM
* Operating System / Distro: Windows 10
* OpenShot Version: 2.4.1-55
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
I think the Chroma Key needs to be enhanced more to get rid of extra bits of the colour that's being keyed out

**Comment by peanutbutterandcrackers** [comment]
Perhaps [this](https://www.youtube.com/watch?v=2sushecqMs4&t=24s) video will help you out with understanding chroma key effect in OpenShot? Please do watch till the end. You can, apparently, use more than one effect on a single clip.
