### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by AlexRE133** [OpenShot/openshot-qt#1473]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**Its not a big problem, how do i activate the video preview

**Comment by peanutbutterandcrackers** [comment]
I think the user lost the video preview tab.

Please go to 'View' > 'Views' > 'Simple View'. This will restore OpenShot to it's original/factory-default mode/view - with the video preview working, should all go well.

Hope that helps!

**Comment by DylanC** [comment]
@AlexRE133 - Yes, please follow the suggestion provided by @peanutbutterandcrackers
