### ISSUE TITLE
Is There a Way to Loop GIFs?

### ISSUE THREAD

**Issue by adswan** [OpenShot/openshot-qt#1474]
**System Details:**
* Operating System / Distro: 
* OpenShot Version: Newest Version
* 
**Issue Description and steps to reproduce:**
I was wondering if there was a way to loop gifs in the software, or a way to keep pasting gifs without the black space in between them. Any help is greatly appreciated!

**Comment by DylanC** [comment]
@adswan - Not at the moment. GIF support may come in the future.

**Comment by DylanC** [comment]
@adswan - Closing this as answered but you can track the progress in #558

**Comment by adswan** [comment]
okay thank you!
