### ISSUE TITLE
Crashes on nwgat openshot presets windows, i think opus and flac issues

### ISSUE THREAD

**Issue by cyberpunkbln** [OpenShot/openshot-qt#1475]
**System Details:**
* Operating System / Distro: Windows 10 64Bit
* OpenShot Version: 2.4.1 64Bit
* _Please attach log files if crash_

Hello,

when i want to use this presets from nwgat, the the launcher.exe on windows 10 crashed. Every Preset crashes.

But when i use another code as flac or opus (ac3,44100 or others from the standard presets) the openshot encode very well. I can use strange video combinations, but when i want to use (opus,48000 or flac) it's crashed.

Can it be the bitrate value? or some other issue?

Thx

**Comment by peanutbutterandcrackers** [comment]
I think @gary9872 - the ninja of OpenShot presets - can help you out with this.

**Comment by cyberpunkbln** [comment]
Hello,
this will be cool, when he can help me ;).
I think the failure is in the libs, every time when i use libopus or flac as codec, OpenShot launcher.exe crashes.

**Comment by cyberpunkbln** [comment]
Oh i see wrong Topic i have choosen;), i reopen an new topic with the correct.
