### ISSUE TITLE
Size

### ISSUE THREAD

**Issue by KazukiTLN** [OpenShot/openshot-qt#1479]
Hi !
I'm new on this software, so i don't really how to use it. But I'll learn of course. However, i've got a problem I can't resolve. 
I can't change the size of the text in the title. Is it a bug? Can I know how to solve it?
Thank you !

Cordially.
A new user

**Comment by peanutbutterandcrackers** [comment]
Hey there!

You'll have to click on 'Change Font' button and there you'll get the option to change the font type, size and style. Hope that helps!

I hope you create amazing videos with OpenShot!

Cordially.
A not-so-new user
(yes, this is a community that scratches each other's backs) :)
