### ISSUE TITLE
Ability to turn off audio or video on a clip indepenently as in version 1.4.3

### ISSUE THREAD

**Issue by stevenelson74708** [OpenShot/openshot-qt#148]
When I import a project created from version 1.4.3, which had some clips with audio turned off and some clips with video turned off, into version 2.0.7 the ability to turn off the audio or video of a particular clip independently seems to be missing, as all clips appear to have both audio and video enabled with no way to disable independently the audio or video of a clip. This is functionality that was available in version 1.4.3, and it is something that I make use of regularly, which means that I can't really upgrade to version 2.0.7. 

Is this functionality available in 2.0.7 and I just don't see how to do it (there were audio and video icons on the clips in version 1.4.3 which controlled the enable/disable of the clip's audio and video), or will that functionality be available in a forth coming version?

**Comment by komackaj** [comment]
Hi @stevenelson74708, importing projects in old format is just partial for now, thank you for reporting it. As for turning audio/video of a clip off see [my comment in this issue](https://github.com/OpenShot/openshot-qt/issues/137#issuecomment-202308549).

**Comment by stevenelson74708** [comment]
So, if I understand correctly, the audio of a clip can be effectively disabled by setting the volume of the clip to 0 percent, but currently there is no way to disable the video of a clip. Is my understanding of the currently functionality of version 2.0.7 correct?

**Comment by komackaj** [comment]
As far as I know, this is the state, maybe @jonoomph will correct me.

**Comment by stevenelson74708** [comment]
Will the ability to disable the video of a clip be provided in a future release of version 2.0.X?

**Comment by jreynojustin** [comment]
OpenShot is now in Version 2.2 if you are still noticing issues in the latest version please re-open this issue letting us know.
