### ISSUE TITLE
Crashes Windows 10 on Audiocodecs Flac, Opus and other maybe

### ISSUE THREAD

**Issue by cyberpunkbln** [OpenShot/openshot-qt#1480]
**System Details:**
* Operating System / Distro: Windows 10 64Bit
* OpenShot Version: 2.4.1 64Bit
* _Please attach log files if crash_
[openshot-qt.txt](https://github.com/OpenShot/openshot-qt/files/1886006/openshot-qt.txt)

Hello,

i reopen my issue why my tests have revealed that the audio-codec is the problem. The launch.exe crashes when i use libopus or flac as an audio-codec.

thx

**Comment by peanutbutterandcrackers** [comment]
Thank you for the good report. I hope this will be fixed soon.

However, you seem to refer to some other issue "i reopen my issue"; could you please point to that issue too? Perhaps that'll help the devs fix this? Thanks!

**Comment by peanutbutterandcrackers** [comment]
Oh! Ooopsie me! It's #1475 you were referring to! Silly me!

It would have been fine if you'd just added these info in the comments, though. But thanks anyways! :)

@gary9872 - Any thoughts, good sir?

**Comment by cyberpunkbln** [comment]
@peanutbutterandcrackers thx for refering;).

In the moment i decode in another audiocodec and the use shotcut to decode in vp9/opus or i use ffmpeg. I hope this is a little bug with the libs from ffmpeg or the own libopenshotcodec?

**Comment by peanutbutterandcrackers** [comment]
Hmm.... I don't really know about this. Sorry.

@DylanC - Any thoughts, Cap'ain?

**Comment by cyberpunkbln** [comment]
@peanutbutterandcrackers No problem, thx for your your involving.

@DylanC Hi, was it possible to make an windows build that referring to the newest dlls from opus and xiph (flac)?

**Comment by DylanC** [comment]
@cyberpunkbln - A recently reported issue reminded me about this. I don't think we got around to figuring if its a DLL issue or something else. I think @peanutbutterandcrackers knows a little more about the situation currently.
