### ISSUE TITLE
[ENHANCEMENT] Please add a setting for the default import directory instead of C:/Users/<username>

### ISSUE THREAD

**Issue by sspmrsomebody1** [OpenShot/openshot-qt#1482]
OS: Windows 8.1

It would be nice if OpenShot would remember the last place you imported a file from by default, unless you set a default directory for which folder the Import dialog will open from, instead of always opening in the User Profile folder.

lol there are 404 issues :p

**Comment by sspmrsomebody1** [comment]
When importing in a project it opens to the last place you imported into that particular project. :+1:

**Comment by DylanC** [comment]
@peanutbutterandcrackers - Closing now since its already been added.
