### ISSUE TITLE
Simple OpenShot project file is >4 million characters and 4 MB. Why?

### ISSUE THREAD

**Issue by sspmrsomebody1** [OpenShot/openshot-qt#1483]
Windows 8.1
OpenShot 2.4.1

OpenShot gets very slow when a project is complicated, and I just noticed how big such a simple project file is. Is undo history being recorded in the file? Perhaps, for example, there is a more efficient way of storing project data, starting with not recording default settings for clips perhaps? (eg instead of "clip": {"setting x":"default", "setting y": "not default", "setting z":"default"} having "clip":{"setting y":"not default"} as a way of reducing project size & lag?

**Comment by sspmrsomebody1** [comment]
I think it's the undo history. I just discovered that OpenShot saves undo history in project files and that there's a "clear history" button lol

Peo

**Comment by DylanC** [comment]
@sspmrsomebody1 - Yes, I've seen reports too of the daily builds producing smaller project file sizes. I would recommend to try out a daily build.

**Comment by sspmrsomebody1** [comment]
, "interpolation": 2}]}, "channel_mapping": {"Points": [{"co"
I was looking at the code of an OSP file and I thought perhaps new OSP files could be written like this? (without removing support for old files) you probably already thought of this :/
, "interp": 2}]}, "cMap": {"Points": [{"co"

**Comment by DylanC** [comment]
@sspmrsomebody1 - I think writing them like this may make them less easy to understand. Not sure if it would be a good idea overall. (no offense) :)
