### ISSUE TITLE
Alphachannel Videos for webm (vp8,vp9) or transparent png output?

### ISSUE THREAD

**Issue by cyberpunkbln** [OpenShot/openshot-qt#1485]
Hello,

i try to use the ability from webm(vp8,vp9) Videos to have an Alphachannel. I hope in the next Version? Change the Background to transparent?
A pity that Openshot this can not.

Or give it a trick?

When i output to PNGs i don't have an alpha channel , and i must 100 pngs rework in gimp;).

Know anybody another open source programm, as an example an prg with simple chroma key and an webm (vp8,vp9) alphachannel output? Or an ffmpeg trick?

thx

Ps: Is for the OBS-Stinger Feature.

**Comment by peanutbutterandcrackers** [comment]
I have notified a developer about this. I hope this will be implemented soon. (but this is surely a low priority work, at the moment)

**Comment by cyberpunkbln** [comment]
@peanutbutterandcrackers thx for that, no problem, when it comes it comes :)

**Comment by i-am-jabriel** [comment]
hi i want this feature to be in openshot can you hire me to make it!
