### ISSUE TITLE
appimage will not start

### ISSUE THREAD

**Issue by jjgalvez** [OpenShot/openshot-qt#1486]
**System Details:**
* Operating System / Distro: Arch
* OpenShot Version: Daily
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
the appimage will not start, it immediately crashes with:

QLibraryPrivate::loadPlugin failed on "/tmp/.mount_nUUapf/usr/bin/platforms/libqxcb.so" : "Cannot load library /tmp/.mount_nUUapf/usr/bin/platforms/libqxcb.so: (/usr/lib/libfontconfig.so.1: undefined symbol: FT_Done_MM_Var)" 
This application failed to start because it could not find or load the Qt platform plugin "xcb".

**Comment by jjgalvez** [comment]
I removed libfont from the package and now it works

**Comment by peanutbutterandcrackers** [comment]
@jigalvez - Just for the sake of posterity, how did you remove libfont from the package? Just in case someone else needs to take a look at this.

**Comment by jjgalvez** [comment]
This is how I got Openshot to work on Arch where we're having libfontconfig issues. The current workaround for the issue is to remove libfontconfig.so.1 from the openshot appimage. The basic steps are:
1) extract openshot appimage to a folder
2) delete libfontcongif from <openshot>/usr/bin
3) recreate appiamge with appimagetool

To do this you will need appimagetool which can be downloaded here (https://github.com/AppImage/AppImageKit/releases)

1) extract appimage:
Openshot is a type 1 appimage, meaning it can't be extract by adding --appimage-extract to the command line which only works for more recent type 2 builds.  So I had to mount the build using
sudo mount -o loop <Openshot>.AppImage /mnt.
I then created a folder with the same name as the Openshot images I downloaded minus appimage and added .AppDir so I ended up with something like <OpenShot>.AppDir.
Next copy everything from the mounted image to the new folder.
2) delete libfontcongif:
cd to <OpenShot>.AppDir/usr/bin and remove libfontconfig.so.1.
3) recreate appiamge:
Last rebuld the appimage with appimagetool-x86_64.AppImage <OpenShot>.AppDir

The new appimage should now work. 

Finally umount the loop

**Comment by peanutbutterandcrackers** [comment]
Awesome, good sir! I will point others to this direction. Thanks!

**Comment by DylanC** [comment]
@jjgalvez - Jonathan put in a fix for this. Now the AppImage starts for me.

**Comment by fabrixx** [comment]
In latest OpenShot dev version after unmount>rename>copy i not have libfontcongif in /usr/bin and i have same issue:
```
[fabrixx@archlinux bin]$ ls
blender
_bz2.cpython-34m-x86_64-linux-gnu.so
classes
_codecs_cn.cpython-34m-x86_64-linux-gnu.so
_codecs_hk.cpython-34m-x86_64-linux-gnu.so
_codecs_iso2022.cpython-34m-x86_64-linux-gnu.so
_codecs_jp.cpython-34m-x86_64-linux-gnu.so
_codecs_kr.cpython-34m-x86_64-linux-gnu.so
_codecs_tw.cpython-34m-x86_64-linux-gnu.so
_ctypes.cpython-34m-x86_64-linux-gnu.so
effects
_hashlib.cpython-34m-x86_64-linux-gnu.so
imageformats
images
_json.cpython-34m-x86_64-linux-gnu.so
launch
launch-openshot
launch.py
libavcodec.so.54
libavformat.so.54
libavresample.so.1
libavutil.so.52
libbz2.so.1.0
libcrypto.so.1.0.0
libffi.so.6
libfreetype.so.6
libgcrypt.so.11
libgio-2.0.so
libglib-2.0.so
libgmodule-2.0.so
libgmodule-2.0.so.0
libgnutls.so.26
libgomp.so.1
libgraphite2.so.3
libgsm.so.1
libgstapp-1.0.so.0
libgstaudio-1.0.so.0
libgstbase-1.0.so.0
libgstpbutils-1.0.so.0
libgstreamer-1.0.so.0
libgsttag-1.0.so.0
libgstvideo-1.0.so.0
libgthread-2.0.so
libharfbuzz.so.0
libicudata.so.52
libicui18n.so.52
libicuuc.so.52
libjpeg.so.8
libmp3lame.so.0
libnvidia-tls.so.340.102
libogg.so.0
libopencore-amrnb.so.0
libopencore-amrwb.so.0
libopenjpeg.so.2
libopenshot-audio.so
libopenshot-audio.so.0.1.4
libopenshot-audio.so.5
libopenshot.so
libopenshot.so.0.1.7
libopenshot.so.12
libopus.so.0
liborc-0.4.so.0
libpgm-5.1.so.0
libpng12.so.0
libpython3.4m.so.1.0
libQt5Core.so.5
libQt5DBus.so.5
libQt5Gui.so.5
libQt5Network.so.5
libQt5OpenGL.so.5
libQt5Positioning.so.5
libQt5PrintSupport.so.5
libQt5Qml.so.5
libQt5Quick.so.5
libQt5Sensors.so.5
libQt5Sql.so.5
libQt5Svg.so.5
libQt5WebKit.so.5
libQt5WebKitWidgets.so.5
libQt5Widgets.so.5
library.zip
librtmp.so.0
libschroedinger-1.0.so.0
libspeex.so.1
libsqlite3.so.0
libssl.so.1.0.0
libswscale.so.2
libtasn1.so.6
libtheoradec.so.1
libtheoraenc.so.1
libva.so.1
libvo-aacenc.so.0
libvo-amrwbenc.so.0
libvorbisenc.so.2
libvorbis.so.0
libvpx.so.1
libX11-xcb.so.1
libx264.so.142
libXau.so.6
libxcb-glx.so.0
libxcb-icccm.so.4
libxcb-image.so.0
libxcb-keysyms.so.1
libxcb-randr.so.0
libxcb-render.so.0
libxcb-render-util.so.0
libxcb-shape.so.0
libxcb-shm.so.0
libxcb-sync.so.1
libxcb-util.so.0
libxcb-xfixes.so.0
libxcb-xkb.so.1
libXcomposite.so.1
libXdmcp.so.6
libXext.so.6
libXi.so.6
libxkbcommon.so.0
libxkbcommon-x11.so.0
libxml2.so.2
libXrender.so.1
libxslt.so.1
libxvidcore.so.4
libzmq.so.3
locale
_lzma.cpython-34m-x86_64-linux-gnu.so
mmap.cpython-34m-x86_64-linux-gnu.so
_multibytecodec.cpython-34m-x86_64-linux-gnu.so
_multiprocessing.cpython-34m-x86_64-linux-gnu.so
_opcode.cpython-34m-x86_64-linux-gnu.so
openshot-qt
openshot-qt.svg
openshot-qt.wrapper
_openshot.so
platforms
presets
profiles
PyQt5._QOpenGLFunctions_2_0.so
PyQt5.QtCore.so
PyQt5.QtDBus.so
PyQt5.QtDesigner.so
PyQt5.QtGui.so
PyQt5.QtHelp.so
PyQt5.QtMultimedia.so
PyQt5.QtMultimediaWidgets.so
PyQt5.QtNetwork.so
PyQt5.QtOpenGL.so
PyQt5.QtPrintSupport.so
PyQt5.Qt.so
PyQt5.QtSvg.so
PyQt5.QtTest.so
PyQt5.QtWebKit.so
PyQt5.QtWebKitWidgets.so
PyQt5.QtWidgets.so
PyQt5.uic.widget-plugins
qt.conf
readline.cpython-34m-x86_64-linux-gnu.so
settings
sip.cpython-34m-x86_64-linux-gnu.so
_ssl.cpython-34m-x86_64-linux-gnu.so
termios.cpython-34m-x86_64-linux-gnu.so
tests
timeline
titles
transitions
windows
zmq.backend.cython.constants.so
zmq.backend.cython.context.so
zmq.backend.cython._device.so
zmq.backend.cython.error.so
zmq.backend.cython.message.so
zmq.backend.cython._poll.so
zmq.backend.cython.socket.so
zmq.backend.cython.utils.so
zmq.backend.cython._version.so
zmq.devices.monitoredqueue.so
zmq.utils.initthreads.so
zmq.utils.rebuffer.so
```
