### ISSUE TITLE
Easy rotation

### ISSUE THREAD

**Issue by yikuansun** [OpenShot/openshot-qt#1487]
On the OpenShot for Mac, version 2.4.1, is there a way to rotate clips without changing the values manually? I am trying out a lot of effects using keyframes, and some effects are ones that are used moving very fast, so I would want to rotate the effect really quickly and accurately, like the Transform property.

**Comment by peanutbutterandcrackers** [comment]
@DylanC - Perhaps an enhancement for the transform tool? o.O
