### ISSUE TITLE
Rotation X-Axis and Y-Axis

### ISSUE THREAD

**Issue by PASTJL** [OpenShot/openshot-qt#1488]
Just a question for new feature
Actually rotation is only possible on Z-Axis ( perhaps playing with Shear X / Shear Y we can simulate a X or Y rotation, but it is tricky)
Is-it possible to add the two rotation in clip properties ? ( keyFramed of course ;-)  )

**Comment by PASTJL** [comment]
Hum I answer to myself. A workaround =>  Rotation on X-AXIS can be done with scale X using negative scale as -1.
But difficult to do several loops !!! 
For Y similar thing can be done...

**Comment by peanutbutterandcrackers** [comment]
@DylanC - Does this issue deserve a cookie (label), Cap'ain?

**Comment by DylanC** [comment]
@peanutbutterandcrackers - Yes sir! :)
