### ISSUE TITLE
Clip Properties Functionality as in 1.4.3

### ISSUE THREAD

**Issue by stevenelson74708** [OpenShot/openshot-qt#149]
Is there clip properties functionality in version 2.0.7 similar to that which is present in version 1.4.3 that includes, among other things, the ability to adjust the layout of a clip from start to end with percentages for Height, Width, X, Y, and Alpha with preview, and the ability to set the clip audio and video fade in and out times in hundredths of seconds and to adjust the audio volume with a slider?

I find the clip properties functionality present in version 1.4.3 very useful, and it would be unfortunate if similar functionality were not available in version 2. Is a similar functionality planned for a future release of version 2?

**Comment by schuko24** [comment]
totally agree to stevenelson74708. Would be very nice and highly appreciated to have the workflow that I am used to in the last years in version 2.x too.

**Comment by RonCam** [comment]
I'm a new user starting with 2.0.7 and found the same problem -- thought I was doing something wrong. 
 
I see new builds are coming at a fast clip, but there hasn't been a reply to the OP in 25 days on this particular point.  Is restoring this feature on the 'to-do list', and so I should wait a bit, or is it advisable to drop back to v1.4?

I'm running on Linux so I would have that option, if restoring the feature isn't in the 'pipeline'.

**Comment by schuko24** [comment]
@ RonCam: I'm running 1.4.3 parallel, as it still gives the desired features to create a video with titles and so on. You can find my videos about model aircrafts on youtube, look for schuko24.
Every now and then I try the 2.0 series, just to check, what works. Jonathan seems to be very busy in core features. I think the UI will follow, give him the needed time.

**Comment by jreynojustin** [comment]
OpenShot is now in Version 2.2 if you are still noticing issues in the latest version please re-open this issue letting us know.
