### ISSUE TITLE
Language installed 

### ISSUE THREAD

**Issue by Caterat** [OpenShot/openshot-qt#1490]
* Operating System / Distro: Windows 10 Pro
* OpenShot Version: 2.4.1

During install, I selected English version but the Norwegian language is installed. Why is that and how do I fix it? This is very frustrating and makes the program unusable.
Selecting Edit/Setup and changing language doesn't change anything. 
Has this ever been tested???

**Comment by DylanC** [comment]
@Caterat - Hello, Please try out a daily build. This has already been fixed. The fix will be included with v2.4.2 release too.
