### ISSUE TITLE
Waveform Must Always Show On The Same Clip

### ISSUE THREAD

**Issue by MrTertius** [OpenShot/openshot-qt#1493]
**System Details:** Intel i5, Integrated GPU, 4GB RAM
* Operating System / Distro: Windows 10
* OpenShot Version: 2.4.1-55
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
If only the "Show Waveform" could always show the Clip's Waveform instead of having to constantly selecting the "Show Waveform" Option for everytime the clip has been splitted

**Comment by N3WWN** [comment]
It looks like the waveforms are retained by the left side of the clip, but not the right side, after splitting or using the razor tool.  

If I zoom in or out, the waveform is refreshed on the left clip, but is not present on the right clip and `Show Waveform` needs to be selected again on that section.

**Comment by MrTertius** [comment]
Its kind of frustrating for me because i use the Wavefrom to perfectly edit my clips
