### ISSUE TITLE
Openshot Crashed Several Times [Log files attached]

### ISSUE THREAD

**Issue by MisterTeeXD** [OpenShot/openshot-qt#1494]
**System Details:** Intel i5, Integrated GPU, 4GB RAM
* Operating System / Distro: Windows 10
* OpenShot Version: 2.4.1-55
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
Openshot had crashed too many times and i think that the log files needs to be reviewed. I have attached the log files so that the problem can be reviewed
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/1896234/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/1896246/openshot-qt.log)

**Comment by peanutbutterandcrackers** [comment]
Awesome, @MrTertius !

I'll try to get a developer's attention towards this. Thanks!

**Comment by MrTertius** [comment]
You are welcome

**Comment by DylanC** [comment]
@MisterTeeXD Can you try v2.4.2 and let us know if you have any success?
