### ISSUE TITLE
Title overlay not working

### ISSUE THREAD

**Issue by patrgoulet** [OpenShot/openshot-qt#1496]
I am creating a basketball mix tape for my son, and had a simple text title overlay working great, but at some point it no longer appears in the video previews.  I have tried to start over with a new project, as well as edit existing projects, and the overlay appears to be ignored in the track.  Using version 2.4.1 on Windows 10, using 'camera border' title template with white text and clear (white) background.  Must have done something settings wise but cannot figure it out.

**Comment by N3WWN** [comment]
Any chance you can post a screenshot or two so we can see how the clips on your timeline are arranged?  Shots which show the title visible in the preview window and then when not visible would be helpful, too.

**Comment by N3WWN** [comment]
Ah, I think I see what is happening.

If you look at the title on `Track 2`, you will see that it is shorter than the clip on `Track 3`.  

The title is about 10s in duration.  
The clip on `Track 3` is at least 24s in duration (the end of the clip is hidden behind the title editor window).

The playhead is positioned at the 2nd frame of the 35th second of the project, which is after the title is over.

If you'd like the title to last longer than the first 10 seconds of the project, you can either adjust the `End` property, which will adjust the duration, or you can click on the end of the title and drag it to change how long the title is shown.  

You can click on the middle of the title and drag it around to change where in the project the title is shown, too.

**Comment by patrgoulet** [comment]
Thank you.  To make sure I understand, right now the title is not popping up on the track at all...basically as if it is not there, or transparent or something.  When is was working yesterday, it would pop on and off per the duration just fine.

**Comment by N3WWN** [comment]
Good point... the video on Track 3 is likely not transparent, so it will cover everything underneath it.  To make the title visible, raise it to a higher number track.  Titles are transparent and will show the clips on the lower tracks through the transparency.

**Comment by patrgoulet** [comment]
That did the trick!  I could have sworn it was working before with the title on a lower track, but working great now.  Thank you for the quick replies...very appreciated.  Love the tool.  Seems to get a little sluggish as I add more clips but pleased with how it works.

**Comment by Mechazo11** [comment]
> Good point... the video on Track 3 is likely not transparent, so it will cover everything underneath it. To make the title visible, raise it to a higher number track. Titles are transparent and will show the clips on the lower tracks through the transparency.

Did not know that, it was getting really annoying putting multiple overlay titles on top of one another on the same track. Thank you for the suggestion
