### ISSUE TITLE
Continued crashing upon export

### ISSUE THREAD

**Issue by SydneyJewishMuseum** [OpenShot/openshot-qt#1497]
**System Details:**
* Operating System / Distro: Windows
* OpenShot Version: Version 2.4.1

Log Name:      Application
Source:        Application Error
Date:          12/04/2018 10:19:35 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      SJMSYD-WK42-15.sjm.local
Description:
Faulting application name: launch.exe, version: 0.0.0.0, time stamp: 0x57a98a3e
Faulting module name: ntdll.dll, version: 6.1.7601.24094, time stamp: 0x5abee643
Exception code: 0xc0000374
Fault offset: 0x00000000000bf6b2
Faulting process id: 0x1db4
Faulting application start time: 0x01d3d1f20ee189a0
Faulting application path: C:\Program Files\OpenShot Video Editor\launch.exe
Faulting module path: C:\windows\SYSTEM32\ntdll.dll
Report Id: 2d636720-3de7-11e8-b917-ecb1d73f17f9
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2018-04-12T00:19:35.000000000Z" />
    <EventRecordID>736206</EventRecordID>
    <Channel>Application</Channel>
    <Computer>SJMSYD-WK42-15.sjm.local</Computer>
    <Security />
  </System>
  <EventData>
    <Data>launch.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>57a98a3e</Data>
    <Data>ntdll.dll</Data>
    <Data>6.1.7601.24094</Data>
    <Data>5abee643</Data>
    <Data>c0000374</Data>
    <Data>00000000000bf6b2</Data>
    <Data>1db4</Data>
    <Data>01d3d1f20ee189a0</Data>
    <Data>C:\Program Files\OpenShot Video Editor\launch.exe</Data>
    <Data>C:\windows\SYSTEM32\ntdll.dll</Data>
    <Data>2d636720-3de7-11e8-b917-ecb1d73f17f9</Data>
  </EventData>
</Event>

**Issue Description and steps to reproduce:**

Attempted to export video for Web > YouTube > VGA NTSC (640x480) > Medium Quality (though all qualities gave the same response)

**Comment by peanutbutterandcrackers** [comment]
Could you please try using the latest daily build of the program? Please head over to the [download](http://openshot.org/download) page and click on 'daily builds' and grab the latest one and see if it works using that.

Other than that, you could definitely try exporting in normal profile (the default one) and use a transcoder like [handbrake](https://handbrake.fr/) to transcode into web format.

Hope that helps!

**Comment by DylanC** [comment]
@SydneyJewishMuseum - I exported from Openshot on Windows 10 just last night. Please try the daily builds. You should be able to export at some quality unless you have a different issue with you system.
