### ISSUE TITLE
Not Responding 

### ISSUE THREAD

**Issue by emxzy** [OpenShot/openshot-qt#1498]
**System Details:**
* Operating System / Distro: Windows 10 
* OpenShot Version: 2.4.1
* _Please attach log files if crash_

I'm loving open shot and recently starting using it no problems, it keeps not responding and takes forever to do anything, please fix it :(

**Comment by peanutbutterandcrackers** [comment]
Could you please try using the latest daily build of the program? Please head over to the [download](http://openshot.org/download) page and click on 'daily builds' and grab the latest one and see if it works using that.

**Comment by DylanC** [comment]
@emxzy - What kind of PC do you have? Openshot does need quite a bit of CPU and RAM.

**Comment by emxzy** [comment]
@DylanC It's a work pc so I'm not sure on the model but its a brand new HP with an i5 processor

**Comment by DylanC** [comment]
@emxzy - Did you try out a daily build like @peanutbutterandcrackers suggested?

**Comment by emxzy** [comment]
@DylanC I did, it worked and now it crashes after playing the preview for about 3 secs so I'll download another daily build, Thank you @peanutbutterandcrackers
