### ISSUE TITLE
Can't return from Fullscreen. F11 does not work.

### ISSUE THREAD

**Issue by jarlarntzen** [OpenShot/openshot-qt#15]
And there's no visible menu bar in Ubuntu 14.04 LTS. 
I was able to use the Alt command interface to type and select "Exit Fullscreen" to enter windowed view again.
These lines appear in the terminal window when performing the above actions.
```
 main_window:INFO keyPressEvent: player.Position(): 1
QMetaObject::invokeMethod: No such method QMenuBar::aboutToShow()
 main_window:INFO keyPressEvent: player.Position(): 1

```

**Comment by jonoomph** [comment]
Very strange issue. I ended up adding the 'fullscreen' and 'exit fullscreen' buttons to the top toolbar, which fixed the F11 / ESC shortcuts (which were being ignored by Qt5). I'm not going to think too hard about this one. =)
