### ISSUE TITLE
How to make video longer?

### ISSUE THREAD

**Issue by philosophytulsa** [OpenShot/openshot-qt#1500]
Making an "End of the Year" video for the school I work for, but there's only 5 minutes on the track and I need more time than that. I read a different forum that said the videos can be of any length, so I'm wondering how to change that?

Side note: I just downloaded this program today and I am not familiar with video editing software whatsoever.

**Comment by DylanC** [comment]
@philosophytulsa - Did you try dragging and dropping your video to the track?

**Comment by philosophytulsa** [comment]
@DylanC I'm using pictures and short video clips and right now I'm at 4:00 minutes but the track stops at 5:16 minutes and I don't know how to extend that

**Comment by N3WWN** [comment]
Have you dragged and dropped additional clips to the right of your current ones?  

The timeline will dynamically extend to accept clips which require more than the initial 5 minutes of displayed timeline.

**Comment by DylanC** [comment]
@philosophytulsa - It should expand as you drop more items to the track.
