### ISSUE TITLE
Issue with editing a clip

### ISSUE THREAD

**Issue by cheesecake7** [OpenShot/openshot-qt#1501]
**System Details: Windows 10 on Acer laptop
* Operating System / Distro: 
* OpenShot Version: 2.4.1
* _Please attach log files if crash_

Was looking to use Openshot for editing long video files (over 2h) and keep only 20min segments out of these files.

However, the tool to 'clip' these videos (Ctrl+X) can't go farther than 29min59s30 precisely. I wanted to signal the issue but I probably won't be waiting to see the fix : I need to edit these videos asap.

Have a nice day

**Comment by DylanC** [comment]
@cheesecake7 Can you try v2.4.2 and let us know if you have any success?

**Comment by DylanC** [comment]
Dup of #1136
