### ISSUE TITLE
Video and audio icons not showing on tracks. Running on windows, version 2.4.1 and the latest daily build for 64 bit. Tried changing themes to no avail.

### ISSUE THREAD

**Issue by Heggety** [OpenShot/openshot-qt#1503]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

**Comment by peanutbutterandcrackers** [comment]
I think what you're looking for isn't really implemented yet. You mean the audio icon to mute the track and the video icon to disable the video, right? It has been requested but hasn't yet been implemented. Maybe soon?

#38

**Comment by Heggety** [comment]
Oh, perhaps but it is in the user documentation so I assumed it meant that it was implemented....

**Comment by Heggety** [comment]
It was in the blog. I also found references to the eye icon in replie to questions about hiding tracks here on github.  https://www.openshot.org/blog/2009/07/15/audio-editing-with-openshot/

**Comment by peanutbutterandcrackers** [comment]
I see. I wonder if it is talking about the older 1.x series...

However, those icons will be implemented, again, good sir; as they're quite helpful. It might be a while before that, though. Thank you for your patience. :)
