### ISSUE TITLE
Bluetooth Headset

### ISSUE THREAD

**Issue by jhaisley** [OpenShot/openshot-qt#1505]
**System Details:**
* Operating System / Distro: macOS 10.13.4
* OpenShot Version: 2.4.1

**Issue Description and steps to reproduce:**
I'm using 3m Worktunes Connect bluetooth headphones, however I suspect this is generalizable to any bluetooth headphones but can not test that.

Using bluetooth headphones OpenShot does not output audio to the headphones.  All other apps work properly and output audio to the headphones.  Wired headphones and internal speakers work fine.

**Comment by peanutbutterandcrackers** [comment]
Perhaps this has something to do with #1390 ?

**Comment by DylanC** [comment]
@jhaisley - Do you have any other device plugged into your headphone Jack?

**Comment by DylanC** [comment]
Could be something to do with:
https://github.com/OpenShot/libopenshot/pull/90

@jhaisley - Can you try a daily build please and let us know?

**Comment by DylanC** [comment]
@jhaisley Can you try v2.4.2 and let us know if you have any success?
