### ISSUE TITLE
AppImage does not work on Pop OS

### ISSUE THREAD

**Issue by DylanC** [OpenShot/openshot-qt#1507]
**System Details:**
* Operating System / Distro: Pop OS 18.04
* OpenShot Version: daily build 

I hate to be adding to the pile of issues.. :laughing:  ..but I noticed the AppImages will not run on Pop OS 18.04 but maybe the AppImage wouldn't open on normal Ubuntu 18.04 either. Not sure.

**Comment by gary9872** [comment]
OpenShot-v2.4.1-62-gf738520-59-691-x86_64.AppImage fails here, cannot find xcb

**Comment by peanutbutterandcrackers** [comment]
Perhaps [this](https://github.com/OpenShot/openshot-qt/issues/1486#issuecomment-381417680) will be of some help? The user recently managed to make the AppImages work.

**Comment by gary9872** [comment]
@peanutbutterandcrackers Thanks for the work around, however I think we should ask for a pull request as the whole point of an AppImage is that it has everything it needs to run properly on the operating system it is targeted for.

**Comment by gary9872** [comment]
@DylanC What is the last Appimage that worked for you>

**Comment by DylanC** [comment]
@gary9872 - All the AppImages used to work on my Ubuntu 17.10 installation. However, I've moved to Pop OS 18.04 and now all the AppImages do not work anymore. 😆

**Comment by gary9872** [comment]
This is what I've narrowed it down to

The Appimage is using an external library (which , namely libfontconfig.so.1) Ideally the Appimage shouldn't use any external libraries. The external library is incompatible with the libraries in the AppImage.

The new version of Ubuntu will not fix the problem. Eventually all LInux releases will fail as they update the freetype library.

There are two solutions: 

1. PR to rebuild internal libraries with support for new freetype 2.9 API types and functions (specifically FT_Done_MM_Var)

https://www.freetype.org/freetype2/docs/reference/ft2-multiple_masters.html

2. PR to rebuild AppImage with internal freetype support. 

@DylanC Could you pass that along?

Cheers,

Gary

**Comment by DylanC** [comment]
@gary9872 - Will do. I'd like to run the AppImages without running a VM. 😆

**Comment by jonoomph** [comment]
Gonna give this a try! A new daily build should be available in the next hour, with it's own libfontconfig.so.1 library. We'll see if this blows up.

**Comment by DylanC** [comment]
@jonoomph - Thanks, I tried the OpenShot-v2.4.1-84-g4768049-59-696-x86_64.AppImage daily build and this now works on my system. :)
