### ISSUE TITLE
Sport camera's videos can't be imported in Openshot

### ISSUE THREAD

**Issue by PhaoTam** [OpenShot/openshot-qt#1509]
**System Details:**
* Operating System / Distro: Win10
* OpenShot Version: 2.4.1

**Issue Description and steps to reproduce:**
When i drag and drop a video taken with my phone, there is no problem.
But when i try to drag and drop a video from my sport camera, it fail. There is no error message, just nothing happen.

I try to select an other profile (4K UHD 2160p 30fps (3840x2160), just in case, but without success. 
The properties of these videos are:
Width: 3840
Height: 2160
Data flow: 24697 kbits/s
Total flow: 24713 kbits/s
FPS: 30.03 trames/s

Do you have an idea to resolve this issue?

Thanks in advance!

**Comment by peanutbutterandcrackers** [comment]
First, I would suggest you switch to the latest daily build. Please head over to the [download](https://www.openshot.org/download/) page, and click on the 'daily builds' button and grab the latest one.

Secondly, what kind of video is it? I mean the encoder and stuff used. Is it a .mp4? .mkv? That should help others (who are smarter than me) help you out.

Third, a work-around might be to use a video transcoder like [Hand Brake](https://handbrake.fr/) to transcode the original video into something more OpenShot friendly. That might make it import-able.

**Comment by PhaoTam** [comment]
Hi, Thanks for your advice!
1) I just start with OpenShot, so my version is the last one.
2) The not working videos are in .mp4
3) I will try this transcoder, thank you!

**Comment by gary9872** [comment]
If you can post the information for your video using gathered by this tool that will help immensely.

https://mediaarea.net/en/MediaInfo/Download
