### ISSUE TITLE
Program crashes for me whenever I try to export a video.

### ISSUE THREAD

**Issue by hillsoftware** [OpenShot/openshot-qt#151]
I am running Windows 10 64bit. Trying latest openshot as of this post 2.0.7

I have tried bringing in 1080p video captured from my phone, and from OBS.

I can edit the video, clip, etc.

But when I do a file/export video and then click export.

I get a "launch.exe" has stopped working.

And a couple pop ups saying Visual C++ Runtime Library "runtime error in launch.exe"

I don't know if it is the 1080p video (the phone is 30fps clips, OBS is doing 60fps clips).

Always crashes. 

Can edit the videos fine with Movie Studio 13, and Premier Elements.

**Comment by telelauro** [comment]
Hi!!! I have same problem. I work all my works at school in Ubuntu 1.4 without problems, and  in windows at home with Openshot is impossible. Unfortunately I can try a lot of because always crahs. And Im working in Windows 8.1 with a ASUS ROG core7 16 RAM and SSD ... And I work normalay with Pinnacle Avid Studio 17 HD, ... and I want to edit my WORKS in openshot. Pinnacle is very hard and very heavy too, and Openshot is better!!!

**Comment by jonoomph** [comment]
@hillsoftware Please download our latest daily installer:

1.  www.openshot.org/download - click '**Other Installers**' link and grab the newest one
2.  Then enable 'Debug Mode (Verbose)' in the Preferences
3.  Quit OpenShot and delete your log file (**/.openshot_qt/openshot_qt.log**)
4.  Re-launch OpenShot and trigger the crash as quickly as possible (to keep the log file small)
5.  Attach the **openshot_qt.log** file here

Hopefully we can determine from the .log file what is happening (and what is crashing). Thanks!

**Comment by hillsoftware** [comment]
Here it is. Renamed it to a txt file so github would process.

[openshot-qt.txt](https://github.com/OpenShot/openshot-qt/files/212268/openshot-qt.txt)

**Comment by kurkosdr** [comment]
I can confirm the problem persists as of 2.0.7 the windows export problem persists, as in the previous beta. Windows 10 64-bit.

**Comment by srvivn21** [comment]
OpenShot-v2.0.7-18-g68d44e1-47-533-x86_32 on Windows 7.  I get about 10% into exporting my video.  Below is the "View Problem Details" text, and attached is a zip file with both the libopenshot.log and openshot-qt.log

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	launch.exe
  Application Version:	0.0.0.0
  Application Timestamp:	549dea3c
  Fault Module Name:	Qt5Gui.dll
  Fault Module Version:	5.4.2.0
  Fault Module Timestamp:	094587e0
  Exception Code:	c0000005
  Exception Offset:	00056acf
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789
[openshot-crash.zip](https://github.com/OpenShot/openshot-qt/files/232611/openshot-crash.zip)

**Comment by hillsoftware** [comment]
I tried the latest build over the weekend, and it still crashes for me when I try to export.

**Comment by alexanderghenry** [comment]
Still crashing :(

[openshot-qt.log.txt](https://github.com/OpenShot/openshot-qt/files/355584/openshot-qt.log.txt)

**Comment by telelauro** [comment]
It is more stable, but yes,  still crashing,
Its look good, is still the beta version so animo Jonathan and all
Of us.

El sábado, 9 de julio de 2016, alexanderghenry <notifications@github.com>
escribió:

> Still crashing :(
>
> openshot-qt.log.txt
> <https://github.com/OpenShot/openshot-qt/files/355584/openshot-qt.log.txt>
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/OpenShot/openshot-qt/issues/151#issuecomment-231536569>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AQBkv4AQWHsGyfKggj_WwS8--VPm3tBXks5qT64YgaJpZM4IBcYv>
> .
>


-- 
"Dabilen kamerari Kroma-keyrik ez"

**Comment by superbole** [comment]
I am also experiencing this problem.

I'm wiling to run tests or experiments to assist with sorting this issue out.

Sheldon

**Comment by arcanon** [comment]
Also seeing this issue with 2.2.0, windows 10 (build 1607). any ideas for a work around?

**Comment by arcanon** [comment]
So it turns out it could just be the codec. If I use one clip (a 2kp30 from DJI mavic) the export then works

**Comment by demaniak** [comment]
Seeing same problem on Ubuntu 16.04, OpenShot 2.2 (installed from PPA). Trying to export with h.264.

**Comment by jonoomph** [comment]
We have recently made a ton of improvements for video freezing and crashes, and I would like to verify this issue still occurs with our latest daily build. Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot. 

If the issue still occurs, please reopen this issue and attach log files (https://github.com/OpenShot/openshot-qt/blob/master/.github/CONTRIBUTING.md), and hopefully we'll be able to nail this down and fix it. Thanks!

**Comment by DavidEdwards** [comment]
I have this issue.

Windows 10, latest installer (as of writing this). Version 2.2.0.

1. Open saved project.
2. Export button.
3. Export Video button.
4. 16% complete - crash.

[openshot-qt.txt](https://github.com/OpenShot/openshot-qt/files/850513/openshot-qt.txt)
[libopenshot.txt](https://github.com/OpenShot/openshot-qt/files/850514/libopenshot.txt)

**Comment by NuggetGamerMC** [comment]
I am also having this error! I need to fix it asap please help!!!!!

**Comment by DavidEdwards** [comment]
For what it is worth, i switched to Lightworks to get it done in the time i had left.

**Comment by BrotherGabriel** [comment]
Having the same problem 2.2.0 and the 2.2.0-70 build is the same - problem seems to occur irrespective of codec or size

**Comment by eddyizm** [comment]
First attempt and using OpenShot and cannot export a video.  v.2.3.4 on windows 10 (creators update). It was crashing randomly during editing and I powered through it to give it a shot but now after all this I can't export it. I came from trying lightworks and being utterly disappointed in that app but I was able to export without issue with that one.

**Comment by Galloog1** [comment]
I can confirm that this is happening.  It is frustrating for me to have spent days working on a project only to have it not be able to export.

**Comment by YamiYukiSenpai** [comment]
@jonoomph I can confirm that this is still happening.

**Comment by webD97** [comment]
I can confirm this as well. OpenShot 2.3.4 crashes somewhere between 90-100% when exporting to h.264. I'll try to attach a clean log asap.

Maybe it's interesting to know that the only source file in the project has ~120GiB and has a deinterlace filter applied.

**Comment by warbdan** [comment]
Same issue here. Too bad. I like the ease of use, but crashed randomly during editing(even changing volume on audio files), and crashes on export even if choosing something besides mp4 with h.264. I even tried mpeg-4 and crash...

**Comment by nhkay** [comment]
logger:INFO OpenShot version 2.3.4

on Manjaro. also crashes constantly when trying to export anything to the point the entire program is useless.

**Comment by chefarov** [comment]
Similar in debian, for openshot 2.3.4

When I press 'export', either no popup or crashes

**Comment by berteh** [comment]
Adding OpenShot to the list of programs whitelisted in my AntiVirus (AVast) fixed this problem for me.

Using Win8 and OpenShot 2.4.1, OpenShot used to crash with no warning on each click on the "render" button. Now that it's path is added to the exceptions of AVast (free edition) I can export with no problem.

**Comment by jnm2** [comment]
I've consistently had this issue with Windows 10, no third-party antivirus.
