### ISSUE TITLE
Sound won't play in editor

### ISSUE THREAD

**Issue by VexHex** [OpenShot/openshot-qt#1511]
Lenovo Y50-70
Windows 10 Home
OS Build 16299.371
Openshot 2.4.1

Can you help me out please? I was in Openshot working on a project for school when suddenly I couldn't hear the sound playing. I checked the volume settings and everything looked fine, but I still couldn't hear it. I don't know what happened, so help please!!!

**Comment by VexHex** [comment]
EDIT: I found that the other sounds from my computer won't play either
Might be PC problem. How to fix?

**Comment by DylanC** [comment]
@VexHex - I would try to look at the settings in Windows and the Audio drivers. Unfortunately this is only for Openshot support issues, so we can't really help all that much to solve your PC audio. 

A link for online help:
https://forums.lenovo.com/t5/Lenovo-P-Y-and-Z-series/Lenovo-Y5070-Windows10-64bits-no-sound-after-mute-unmute-master/td-p/2170202
