### ISSUE TITLE
'find directory" does not propose any file and enter into an infinite loop

### ISSUE THREAD

**Issue by Flyingdishes** [OpenShot/openshot-qt#1514]
**System Details:**
* Operating System / Distro: ? all
* OpenShot Version: ? all
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

When moving an already created OSP Folder/file to a different directory/volume ,  references to project resource files are lost.
The "'find directory" , proposing to search for the file on other directories does not propose any file and enter into an infinite loop.

**Comment by PASTJL** [comment]
Opening a .osp files with a textEditor, i think the path of the files clips are relative and not absolute  to the location of the osp file. So try to move all the project ( osp file and clips)  by keeping the same file tree.

**Comment by PASTJL** [comment]
@Flyingdishes  Humm sorry you did it in a precedent post with an infinite loop, i have just read it....

**Comment by Flyingdishes** [comment]
Thanks Pastjl,
I in fact moved the all root directory, including all files referenced into the osp ; this leads me to believe that path are absolute and not relative.

The second issue is that the "find file" feature does not propose any file even if they are for sure present into the directory selected.

**Comment by gary9872** [comment]
Can we get this marked as a feature request?

**Comment by DylanC** [comment]
@gary9872 - Yes sir! :)

**Comment by ferdnyc** [comment]
This was fixed in commit bdd2135 which will be included in the next release of OpenShot. Once you select the directory where your disconnected file can be found, all files in that directory will be recovered automatically.
