### ISSUE TITLE
How to delete audio from video file

### ISSUE THREAD

**Issue by MuCe60** [OpenShot/openshot-qt#1515]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

**Comment by gary9872** [comment]
After adding a file the timeline, right click on the file added and select seperate audio >  Single Clip
It will separate it into 2 tracks one will have audio one will have video. Delete the one you don't want

**Comment by MuCe60** [comment]
Thank you very much Gary…:)
Kind regards.

MuCe

**Comment by Geshelin** [comment]
This doesn't work for me, if I click on Remove Clip on the bottom one, they both go away; if I click on Remove Clip on the top one, the video goes away and leaves the sound.
![image](https://user-images.githubusercontent.com/44833543/48260433-1eb60100-e424-11e8-9615-5d86884acd82.png)

Dylan, I am afraid we are destined to become friends while I try to learn this program. At 72 it takes me a long time to catch on to these things--tho I was pretty good with DOS when I was young. ;-)

**Comment by peanutbutterandcrackers** [comment]
@Geshelin - Hey there, I think you should go through [this guide](https://gist.github.com/peanutbutterandcrackers/f0f666243133e0ed25abbc12a4ba23d7) to help you understand OpenShot fully.

Hope that helps!
