### ISSUE TITLE
"Failed - Forbidden"

### ISSUE THREAD

**Issue by kenzie3893** [OpenShot/openshot-qt#1516]
**System Details:**
* Operating System / Distro: Windows 10
* OpenShot Version: Newest full release
* _Please attach log files if crash_
![capture](https://user-images.githubusercontent.com/38514662/38967037-319c6fc4-4353-11e8-91d6-9b73260a7423.PNG)

**Issue Description and steps to reproduce:**
I have openshot on my laptop and it works just fine. But I tried to download it on my desktop and it completely "forbids" me to continue the download halfway through

Edit: Btw I attached a screenshot of my download history. I tried downloading the most recent build and the most recent full release

**Comment by gary9872** [comment]
My best guess it to try again.

I don't think it has anything to do with openshot, but rather github hosting through amazon servers.

You computer might be stopping from downloading it via firewall antivirus, or s3 amazonaw server 0 is out to lunch right now.

**Comment by DylanC** [comment]
@kenzie3893 - Amazon services probably went down for a while. Nothing really we can do about Amazon reliability. :)

**Comment by Sonia1111** [comment]
While downloading Openshot, I am also getting the same error "Failed - Forbidden". I tried 4 times and got the same error. It seems like , it is looking for  adequate permission which might I don't have
