### ISSUE TITLE
Advanced editing of a title

### ISSUE THREAD

**Issue by mellybean79** [OpenShot/openshot-qt#1517]
**System Details:**
* Operating System / Distro:  Windows 
* OpenShot Version: newest
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
Help, i'm trying to edit a title. I have inkscape installed, but for some reason i'm still getting the "please install inkscape to use this function"  Is there someway i have to link the programs?

Thanks!

**Comment by N3WWN** [comment]
Make sure that the path to Inkscape is correct in the OpenShot preferences:  `Edit` -> `Preferences` -> `Advanced Title Editor (path)`

**Comment by mellybean79** [comment]
Thank you so much!
