### ISSUE TITLE
Scale Y on a MTS Clip freeze OpenShot

### ISSUE THREAD

**Issue by PASTJL** [OpenShot/openshot-qt#1518]
Kubuntu 17.10
OpenShot AppImage Daily Build 2.4.1  ( 63 and 64)
When scaling Y to 1,0 at the beginning of the clip, and afterwards going to for example at the 1s frame, when clicking another time on scale Y seems to put Openshot in infinite loop ( CPU is stressed) and no action is possible on Openshot.

**Comment by PASTJL** [comment]
To add more information, it was running correctly with build 57  (April 4th) and always failing with build 84 of April 19th

**Comment by PASTJL** [comment]
tested with daily build 90  (April 30th) still fails ( freezes a long time more than 1 minut) when using keyframe on Y-Axis. I confirm that the build 57 has not this issue.

**Comment by N3WWN** [comment]
Hi @PASTJL !

Would you be able to post a few seconds of your MTS clip (in the exact same format as your original) or even your original MTS clip (if it is not very large) so that we can attempt to recreate this bug on our end?

Thanks!

**Comment by PASTJL** [comment]
Hi @N3WWN 
I migrate to Kubuntu 18.03 and last daily build (102). The issue disappears. So we can close this bug
