### ISSUE TITLE
Cannot render NVENC video

### ISSUE THREAD

**Issue by BinaryVigilante** [OpenShot/openshot-qt#1519]
Hi,

First off, thank you for a great video editor!

I have a feature request, which I would be very happy if it got implemented.

It would be really nice to have an estimated time for rendering completion appear when the rendering starts. I come from Kdenlive which has this feature, and I find it really handy :)

Thanks for your time and have a nice day/night!

Kind regards!

**Comment by peanutbutterandcrackers** [comment]
Could you please check what codec and stuff the video you're trying to edit with [this program](https://mediaarea.net/en/MediaInfo) and provide the info here? That will help others help you. Hope that helps!

**Comment by BinaryVigilante** [comment]
I'm trying to render a video recorded with NVENC using the matroska container and the audio is aac.

I'm then trying to render it to a libx264 video file, still with the matroska container and still with the audio at aac. I can do it in Kdenlive with no problem at all, and both Openshot and Kdenlive uses Melt to render.

**Comment by peanutbutterandcrackers** [comment]
@BinaryVigilante - Hmm... OpenShot 1.x series did use the MLT library but with the 2.x series, OpenShot uses it's own multimedia library called libopenshot. Therefore, I am assuming that it is probably a case of lack of support NVENC encoding?

If you could, then yes please. @gary9872 might be able to give some more insight using the output from mediainfo...

**Comment by DylanC** [comment]
@peanutbutterandcrackers - NVENC does not seem to be working. #583 #808

**Comment by BinaryVigilante** [comment]
Ok, I used mediainfo:

General
Unique ID                                : 322868740778034119691474323225712689292 (0xF2E641F1E236F7E17CB57A2EB29E808C)
Complete name                            : 2018-04-16_12-18-05.mkv
Format                                   : Matroska
Format version                           : Version 4 / Version 2
File size                                : 311 MiB
Duration                                 : 6mn 41s
Overall bit rate                         : 6 481 Kbps
Writing application                      : Lavf57.40.101
Writing library                          : Lavf57.40.101 / Lavf57.40.101

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.2
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 2 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 6mn 41s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 60.119 fps
Original frame rate                      : 60.000 fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Matrix coefficients                      : BT.601
DURATION                                 : 00:06:41.934000000

Audio #1
ID                                       : 2
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : A_AAC
Duration                                 : 6mn 41s
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 KHz
Frame rate                               : 46.875 fps (1024 spf)
Compression mode                         : Lossy
Title                                    : Track1
Default                                  : Yes
Forced                                   : No
DURATION                                 : 00:06:41.856000000

Audio #2
ID                                       : 3
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : A_AAC
Duration                                 : 6mn 41s
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 KHz
Frame rate                               : 46.875 fps (1024 spf)
Compression mode                         : Lossy
Title                                    : Track2
Default                                  : Yes
Forced                                   : No
DURATION                                 : 00:06:41.856000000


One thing to note tho, if I write "mkv" in the Video Format, it indeed gives the "Could not open codec" error. But I write "matroska", it says this: "Could not deduce output format from file extension". Just in case it gives more info.

**Comment by peanutbutterandcrackers** [comment]
[Here](https://handbrake.fr/) is handbrake, just in case. :)

@gary9872 - Any thoughts?

**Comment by DylanC** [comment]
Dup of #583 #808.

**Comment by BinaryVigilante** [comment]
I suppose it is a workaround to use ffmpeg to convert the mp4 file to mkv  :)

ffmpeg does indeed support the MKV container :) I use Melt for rendering, which is running on ffmpeg and there are no problems at all. But thanks anyways for the hint and the link ;) I will give it a look anyways!

And sorry about the duplication.. I did not see the other two posts. :(

Have a fantastic day!

**Comment by gary9872** [comment]
You can use nvenc_h264 with ac3, but I don't think the AppImage doesn't support it.

 If you say are in Linux and you use the build from your distro which uses external libraries you should have no problem using it. That being said there are no way to set any other parameters to it so it may not be much if any faster. It works for me, it offloads some work to the GPU, but don't expect a huge performance bost.

**Comment by Flashwalker** [comment]
I confirming this issue.  
Affects export via `h264_nvenc`.  
Despite the fact that i have installed `libnvidia-encode-390`.

**Comment by ferdnyc** [comment]
@Flashwalker Yeah, hardware acceleration does not currently support secondary GPUs (laptop Optimus / PRIME -- Hah! I just got that), unfortunately. Works fine if the Nvidia chip is your primary GPU.

It's not supported _at all_ in the AppImages, tho, since it seems to be impossible to include hardware driver support in a way that's compatible with all distros. (Which is the entire reason for the existence of AppImage builds in the first place.)

**Comment by ferdnyc** [comment]
If VAAPI works at all, (a) I'm kind of surprised, TBH, but (b) it's most likely either encoding unaccelerated (but through the VA interface), or it's using your Intel chip's integrated GPU as the hardware encoder. Which would probably explain the poor quality, when using VAAPI instead of QSV.

**Comment by hradec** [comment]
I've tried today (dec 27/2020) and neither nvenc or vaapi works to export a video using hardware encode. I just updated my manjaro to the latest version, which came with the latest openshot-qt available. 

not working at all! Why was this issue closed then?

**Comment by sachinkhatrilin** [comment]
I am facing the same issue on version 2.5.1. Its surprising to see the issue is so old yet open.

**Comment by JacksonRG** [comment]
@sachinkhatrilin were you using the AppImage, or your distro's packaged version?
