### ISSUE TITLE
Help ! xc_Freeze error!

### ISSUE THREAD

**Issue by Sunfay** [OpenShot/openshot-qt#1522]
Please I need help... 
![aaaa](https://user-images.githubusercontent.com/28486824/39074121-7bf5c95a-44f0-11e8-8e9a-4717977f1dc6.PNG)

**Comment by peanutbutterandcrackers** [comment]
Please try out the latest daily build. This issue seems to have been resolved in the latest daily build.

Please head over to the [download](http://openshot.org/download) page and click on the button that says 'daily build' and grab the latest one and install it. Hope that helps!

**Comment by DylanC** [comment]
Yes, this issue doesn't seem to happen in the daily builds. Also please use the search on Github to find users who have already solved this issue. Thanks.
