### ISSUE TITLE
Constant crashes of the program

### ISSUE THREAD

**Issue by swwe** [OpenShot/openshot-qt#1524]
**System Details:**
* Operating System / Distro: windows 10
* OpenShot Version: last one
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
the program crashes all the time when i put a file on the time line, its the most basic action to do when editing a video and it crashes when i do it, i tried 5 times now today to put something on the time line and it crashes

**Comment by willowcrone** [comment]
Same here.  It continuously freezes and crashes.  I am using it on Win 10, on a Lenovo Yoga 720

**Comment by peanutbutterandcrackers** [comment]
Perhaps switching to the latest daily build will fix the problems for you, too - as for many other users.

Please head over to the [download](https://www.openshot.org/download/) page, and click the button that says 'daily builds' and grab the latest one and install it, and see if this issue still persists then.

Hope this helps!

**Comment by DylanC** [comment]
@swwe Can you try v2.4.2 and let us know if you have any success?
