### ISSUE TITLE
blenders not working with my open shot i don't know why 

### ISSUE THREAD

**Issue by RAWdawg1** [OpenShot/openshot-qt#1529]
**System Details:**
* Operating System / windows 10 
* OpenShot Version: ? newest  
* _Please attach log files if crash_

**Issue Description and steps to reproduce: I have the correct file path but it just wont work I've try'd everything can someone help :)
![screenshot 11](https://user-images.githubusercontent.com/38607557/39093335-d84e0dea-4615-11e8-9a58-24b254e84f5c.png)

**Comment by sspmrsomebody1** [comment]
Do Ctrl+H to see the OpenShot version.
Make sure your blender is version 2.78 or higher; if not install a newer version.
Also you may need to change the Blender path if it is not located at `C:/Program Files/Blender Foundation/Blender.exe`. Find Blender in the Start Menu, then Right click > Open file location which will open a folder with a Blender shortcut in it. Right click on it and click "Open file location" again then copy the path in the address bar. Then go into OpenShot, click Edit > Prefrences and paste it into there, then put `\blender.exe` on the end.

**Comment by RAWdawg1** [comment]
version 2.4.1 for my openshot i only recently installed blender so that should be good but still wont work.

**Comment by RAWdawg1** [comment]
:) OK got it to work by screenshoting blender on its launch screen and typing the location from that XD thank you @sspmrsomebody1   the path i had to use was **c:\program files\blender foundation\blender\blender.exe**

**Comment by mouarfff** [comment]
same issue but replace \ with / doesn't take any effect.

**Comment by ferdnyc** [comment]
@mouarfff See pinned issue #2901 — depending which version of Blender you have installed, it may not be compatible with the OpenShot release you're running. The recent 2.80 release broke support for all earlier versions.

**Comment by mouarfff** [comment]
i have last stable openshot version (2.4.4) in windows 10, and i upgraded blender 3 days ago

**Comment by ferdnyc** [comment]
@mouarfff That's the problem, then. OpenShot 2.4.4-release isn't compatible with Blender 2.80. 

There hasn't been a new release of OpenShot since Blender broke compatibility with their previous API in the 2.80 release, so the only options right now are:
1. Downgrade Blender to 2.78-2.79 (with OpenShot 2.4.4-release)
2. Run OpenShot daily builds (with Blender 2.80)

**Comment by mouarfff** [comment]
Ok thx, i don't wanted to downgrade lol, but i'll do it.

Maybe u should make a BIG warning somewhere ? :)

**Comment by ferdnyc** [comment]
@mouarfff Issue #2901 is pinned at the top of https://github.com/OpenShot/openshot-qt/issues/ — not sure what more we could do, though I'm honestly open to suggestions. (I guess we could update the README, but I'm pretty sure existing users never look at that either. Heck, I don't even look at it. :laughing: )

**Comment by RAWdawg1** [comment]
XD why am i reeving open shots messages
u may have the wrong guy
________________________________

**Comment by ferdnyc** [comment]
@RAWdawg1 Because you opened issue #1529 — you can unsubscribe at https://github.com/OpenShot/openshot-qt/issues/1529 if you don't want to follow it anymore.

**Comment by mouarfff** [comment]
> 
> 
> @mouarfff Issue #2901 is pinned at the top of https://github.com/OpenShot/openshot-qt/issues/ — not sure what more we could do, though I'm honestly open to suggestions. (I guess we could update the README, but I'm pretty sure existing users never look at that either. Heck, I don't even look at it. 😆 )

Ho sorry , i'm sooo stupid, i don't speak the language of the gods (english)
