### ISSUE TITLE
Ubuntu 14.04: Only 1 core of multiple core cpu being used

### ISSUE THREAD

**Issue by mgmdpm** [OpenShot/openshot-qt#153]
In version 2.0.6 64 bit Ubuntu 14.04.4  I created a 3 min. 45 sec.  video with about 6 tracks, music, speech, stills, titles and videos.  No fancy transitions or animated titles.  I found that the preview screen took many seconds to respond to mouse clicks and the sound track became out of sync with the rest of the tracks.  On saving, everything was fine.  The sound was correct.   What I discovered is that although I have an 8 core AMD CPU, Openshot is only using 1 core, which gets pegged at 100%, causing, I suspect, all the other problems I had.  Is there any way to make Openshot multiple cores aware so it can use all of them as needed?

**Comment by jonoomph** [comment]
Please check if "Debug Mode (Verbose)" is turned off in the Preferences. Also, please try version 2.0.7 (you can grab the AppImage version on www.openshot.org/download - just make executable, and launch it, no installation needed).

While it is previewing (or exporting), please share a pic of your system monitor, showing the CPU graphs (I'm just curious what it looks like during export).

Thanks!

**Comment by mgmdpm** [comment]
Hello Mr. Thomas;

Debug mode is turned off in the preferences area of both the version
installed from PPA and from the appimage version.  Send anonymous metrics
and errors is checked in both versions.

switching between thumbnail view and detail view now works.  In 2.0.6 it
was stuck in detail view once switched from thumbnail view, you could not
go back.

In both the PPA version and the appimage version, all CPU cores now appear
to be engaged, but the behavior in the program is still very slow to
respond to mouse clicks in preview mode.

In 2.0.6, even after exiting the program, there was still one process from
openshot still running and consuming CPU cycles and RAM.  That behavior now
appears fixed in 2.0.7.

Notice the ram use.  In 2.0.7 from ppa, it slowly rose to 99% ram use,
followed by swap slowly rising to almost 90 % also.  It took 5 mins of
constant hard drive use to allow the program to finally stop and exit.

In 2.0.7 from appimage, the ram use is also slowly rising to about 80 %.
It never uses swap.  There is no hard drive use and you can exit the
program once the preview finally stops, which can take about 20 seconds
from when you click pause on the preview window.

The version from appimage still has the sound out of sync with the images
during preview mode, but the saved file is fine.  Also, when previewing, It
can take 10 seconds to respond to mouse clicks of the pause button (shown
as the graphic of the pause button changing back to a play button),
followed by another 10-15 seconds before the preview actually stops.

In some of the screen shots, you can see the complexity of the video I
created.

I have attached numerous screen shots of the CPU and RAM use labelled to
tell you what was going on at the time of screen capture.  The last image
just labelled screen capture is showing the preferences in debug mode.

CPU is AMD FX(tm)-8350 Eight-Core Processor × 8
Graphics  GeForce GTX 550 Ti/PCIe/SSE2
8 GB RAM installed, system reports 7.7 GB usable

Ubuntu 14.04.4 64 bit with stock Unity GUI.

Hope this is helpful.

Marty Miller

**Comment by DylanC** [comment]
@mgmdpm Does this issue happen in the latest version or newer versions of OpenShot?

**Comment by DylanC** [comment]
@mgmdpm - Closing ticket since it relates to a much older version of OpenShot. If you can produce on the latest version then please report a new ticket. Thanks.
