### ISSUE TITLE
Chroma Key of OBS

### ISSUE THREAD

**Issue by TavernSenses** [OpenShot/openshot-qt#1530]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

The Chroma Key function that is available in Open Shot is pretty dismal. Why can 't the excellent Chroma Key engine of OBS be used? Or is there an existing plug-in that performs as good, or at least better than what's available now?

ADDED: Actually, the Chorma Key in Open Shot is so bad I do my Chroma Key in OBS, and then export the video to be edited further in Open Shot. But since the video cannot be exported with an empty background (it's black) from OBS, I have to fill in the background while still in OBS, which drastically limits edit possibilities thereafter in Open Shot.

**Issue Description and steps to reproduce:**

**Comment by DylanC** [comment]
@peanutbutterandcrackers - I guess we could look at this for some inspiration:
https://github.com/obsproject/obs-studio/blob/master/plugins/obs-filters/chroma-key-filter.c

Maybe then we could make improvements to our own Chroma key code.

**Comment by peanutbutterandcrackers** [comment]
I see. I hope we can make those improvements soon!

**Comment by minecraftchest1** [comment]
Bump.

**Comment by ferdnyc** [comment]
There's a PR currently open at OpenShot/libopenshot#716 that would greatly expand OpenShot's ChromaKey abilities, using the Babl library for color matching and color space conversion. 

At the moment we're waiting on a response from the author regarding some testing issues, but I'm hopeful it will be merged soon.
