### ISSUE TITLE
OpenShoot tooooo slow

### ISSUE THREAD

**Issue by gamersalpha** [OpenShot/openshot-qt#1532]
**System Details:**
Cpu i5-3570K
16 Go Ram
GTX 1060 
* Operating System / Distro: ?
Windows 10 pro x64

* OpenShot Version: ?
2.4.1
* _Please attach log files if crash_
no crash, just tooooo slowly, can't using it in production

**Issue Description and steps to reproduce:**
I try this openShot, and i add two jpg image and two transition and is just tooo slow, when if i left click i copy past transition

thanks

**Comment by N3WWN** [comment]
Please try one of the daily builds.  A lot of development has gone into improving performance for the next release (2.4.2) and is currently available via the daily builds.

**Comment by gamersalpha** [comment]
Where cet it please ?

**Comment by DylanC** [comment]
@gamersalpha - You need to go to the downloads page: https://www.openshot.org/download/

Click daily builds. Download the correct installer for your system.

**Comment by gamersalpha** [comment]
i try the latest daily builds from 21/04/2018

and now crash evry time :/

**Comment by peanutbutterandcrackers** [comment]
@gamersalpha - Could you please try the daily build pointed by @piacentecristian? If even that does not work out for you (i.e. crashes evri tiem), please [attach the log files](https://github.com/OpenShot/openshot-qt/blob/master/.github/CONTRIBUTING.md). Hope that helps!

**Comment by carlosnewmusic** [comment]
in linux with kernel 4.15 kali linux, the same thing takes a long time to load the preview and blocks the application

**Comment by N3WWN** [comment]
@carlosnewmusic Please include the following information so we know more about the environment that you are running OpenShot within:

>**Describe the bug**
OpenShot takes a long time to load the preview and blocks the application

>**System Details (please complete the following information):**
> - Operating System / Distro: Kali Linux with kernel 4.15
> - OpenShot Version [e.g. 2.4.1]

>**To Reproduce**
> Steps to reproduce the behavior:
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error

>**Expected behavior**
A clear and concise description of what you expected to happen.

>**Screenshots**
If applicable, add screenshots to help explain your problem.

>**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

>**Additional context**
Add any other context about the problem here.

These are the fields which are provided when you open a new issue for us to get the minimum information necessary.  Without these details, it is difficult for us to provide you with steps to diagnose or resolve the issue.

I've filled in the OS/Distro and bug description with what you listed.

Thanks!

**Comment by jeppec** [comment]
I downloaded 2.4.1 as well as OpenShot-v2.4.1-117-g964d420-59-709-x86.
OpenShot is sadly so slow that it's unusable. Moving things around takes a very long time, showing wait cursor, preview play stutters. Takes 4-5 seconds between each progress in preview replay. The project involves 5 GoPro shots each ~3.3 GB (1080p 50 frames/sec). The shots have been sped up 4 times in OpenShot. Simple start and end title.

Hardware Core i9 7900X, 64 GB Ram, GTX 1080 Ti, NVMe disc, Windows Pro 10 (1803 build 17134.48)
How can I assist in figuring out what's slowing it down?

**Comment by peanutbutterandcrackers** [comment]
@jeppec - Thank you for your offer to help, good sir. Here are some ways you can help:
1. Please keep on trying out the [latest daily builds]() and see if any of them work out for you.
2. Please [attach the logs]() in cases of crash.
3. Please keep on following the progress happening in OpenShot.

For the moment, if it is urgent, you might want to try using [KdenLive](https://kdenlive.org/en/download/) to edit your videos.

This is after all, a community project - the labour of love of a single man. And one of the reason OpenShot does not work well on Windows is that there aren't many windows users constantly following the project, submitting well-written bug reports and providing patches and/or other intel as to what might be the reason behing OpenShot not working that great. Linux users on the other hand do all sorts of detective works and submit patches. That is why, OpenShot is fairly stable on Linux Platforms.

Hope you keep on supporting this free software gem.

Sorry for the inconvenience caused, good sir. I hope the developers would soon get to resolve these issues.

**Comment by peanutbutterandcrackers** [comment]
@jeppec - Thank you for your offer to help, good sir. Here are some ways you can help:
1. Please keep on trying out the [latest daily builds](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914) and see if any of them work out for you.
2. Please [attach the logs](https://github.com/OpenShot/openshot-qt/blob/master/CONTRIBUTING.md) in cases of crash.
3. Please keep on following the progress happening in OpenShot.

For the moment, if it is urgent, you might want to try using [KdenLive](https://kdenlive.org/en/download/) to edit your videos.

This is after all, a community project - the labour of love of a single man. And one of the reason OpenShot does not work well on Windows is that there aren't many windows users constantly following the project, submitting well-written bug reports and providing patches and/or other intel as to what might be the reason behing OpenShot not working that great. Linux users on the other hand do all sorts of detective works and submit patches. That is why, OpenShot is fairly stable on Linux Platforms.

Hope you keep on supporting this free software gem.

Sorry for the inconvenience caused, good sir. I hope the developers would soon get to resolve these issues.
