### ISSUE TITLE
Trend Micro Virus Detection, can't start openshot

### ISSUE THREAD

**Issue by Spartacus2018** [OpenShot/openshot-qt#1534]
**System Details:**

* Operating System / Distro: ?
Windows 10 pro x64
* OpenShot Version: ?
dayli update
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

i can't lunch openshoot my antiVirus bloque openshot : 

![image](https://user-images.githubusercontent.com/301074/39297348-92021d28-4943-11e8-8e6b-88685e1a458f.png)

and 
![image](https://user-images.githubusercontent.com/301074/39297385-abd51d9a-4943-11e8-812c-53ab2ad026c5.png)

**Comment by DylanC** [comment]
@Spartacus2018 - Maybe try to add an exception to the anti-virus:
https://esupport.trendmicro.com/en-us/home/pages/technical-support/premium-security/1059964.aspx
