### ISSUE TITLE
Python error on startup

### ISSUE THREAD

**Issue by jtullett** [OpenShot/openshot-qt#1536]
**System Details:**
* Operating System / Distro: Windows 10
* OpenShot Version: 2.4.1
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
Launching the program or opening a project file yields the error in the attached screengrab.

![screenshot 8](https://user-images.githubusercontent.com/13500976/39311174-7c8f52d4-496c-11e8-8db1-389ff8ca490c.png)

**Comment by gary9872** [comment]
Can you update to python 3.6?

**Comment by peanutbutterandcrackers** [comment]
Using the latest daily build solves this issue, as has solved for many users. You might want to head over to the [download](http://openshot.com/download) page and click on the 'daily build' and grab the latest one.

v2.4.2 will be released soon, too. That should have this fixed, too. Hope that helps.

**Comment by DylanC** [comment]
@jtullett - I would recommend to try a daily build like @peanutbutterandcrackers suggested or wait until v2.4.2 is released. (soon)
