### ISSUE TITLE
OpenShot v2.4.1 Unusual Runtime Termination Request Issue (Need Help Please!)

### ISSUE THREAD

**Issue by wrookie11** [OpenShot/openshot-qt#1540]
**System Details:**
* Operating System / Distro: Windows 7
* OpenShot Version: 2.4.1
* _Please attach log files if crash_

**Runtime termination everytime I run the software. Not entirely certain how I caused the issue as everything happened so quick. But it had something to do with dragging a file either into the software or dragging a file from the file area onto one of the tracks while it was already processing data. In other words, I dragged a file from somewhere to somewhere into OpenShot before it was ready and now i'm stuck with this permanent runtime termination issue. Another user on this site finchamp described a similar issue. But if anyone know how to troubleshoot the issue, please help explain how to do so. I'm dying to get this project finished. Thanks much.**

**Comment by wrookie11** [comment]
finchamp's thread link

https://github.com/OpenShot/openshot-qt/issues/553

**Comment by gary9872** [comment]
Have you tried any of the latest daily builds?
 
Can you attach a log?

**Comment by peanutbutterandcrackers** [comment]
Yes, you might want to try out the latest daily build by heading over to the [download](http://openshot.org/download) page and clicking on the 'daily builds' button and grabbing the latest one, like @gary9872 pointed out.

**Comment by DylanC** [comment]
@wrookie11 Can you try v2.4.2 and let us know if you have any success?
