### ISSUE TITLE
vidéo bug 

### ISSUE THREAD

**Issue by rogeraniobi** [OpenShot/openshot-qt#1541]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ? 
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

bug video
when I import my video on the software, it starts to bug.
is it because video is too important for my pc? Any ideas ? thank you :)

vidéo qui bug
lorsque j'importe ma vidéo sur le logiciel, elle se met a buguer.
est ce parce que la vidéo est trop importante pour mon pc ? quelqu'un a une idée ? merci :)

**Comment by N3WWN** [comment]
A detailed description of the bug or a screenshot showing the bug would be helpful, also.

**Comment by DylanC** [comment]
Closing until we have enough details to do anything here.
