### ISSUE TITLE
Dropping frames at end of imported mp4

### ISSUE THREAD

**Issue by mnoah66** [OpenShot/openshot-qt#1547]
**System Details:**
* Operating System / Distro: Windows 10 Home, 64 bit
* OpenShot Version: 2.4.1

**Issue Description and steps to reproduce:**

Preview and export is dropping frames at the end of an imported mp4.

I have 198 jpg's that I turned into an mp4 with the following command: ffmpeg -i Image-%3d.jpg -vf "tblend=average" original.mp4

This results in a 1920x1080, 25fps ~7 second video time lapse.

I import ths video into OpenShot, and in both the preview and export, it freezes the last few frames and/or drops them off entirely.  In my project profile, I have set it to "HD1080p 25FPS (1920x1080)" to match the source "original.mp4" video.

Here is the original: https://vimeo.com/267403906
Here is the OpenShot export: https://vimeo.com/267403937

**Comment by peanutbutterandcrackers** [comment]
You might want to try out the latest daily build. Please head over to the [download](https://www.openshot.org/download/) page and click on the 'daily build' button and grab the latest one. The daily versions are known to work better than v2.4.1. Or, perhaps wait for v2.4.2, which should be out within a couple of weeks. Hope that helps!

P. S: If there are still problems with the daily build, you might want to use [this tool](https://mediaarea.net/en/MediaInfo) to extract information about the media file and provide the info here. That should help others help you. Thanks!

**Comment by peanutbutterandcrackers** [comment]
Also, I usually make timelapses using ffmpeg [this](https://gist.github.com/peanutbutterandcrackers/b062ddcc7fb3802972b73025b531b493) way. Maybe that will be of some help to you, too?

Also, did you know that you can make timelapses from within OpenShot by importing pictures as an image sequence when prompted?

**Comment by DylanC** [comment]
@mnoah66 Can you try v2.4.2 and let us know if you have any success?
