### ISSUE TITLE
Custom Profile Openshot 2.0.7

### ISSUE THREAD

**Issue by m3hdad** [OpenShot/openshot-qt#155]
How do you create your own profile in 2.0.7 - Did you remove this feature?

**Comment by jonoomph** [comment]
Thanks for the bug report / suggestion. I have just added back the ability to use custom profiles. Somehow, I thought this was already working... haha. With commit a42479f9baf15c30edae990bd22170d2e9f32121, all you need to do is drop a custom profile file in your user folder: **/.openshot_qt/profiles/**. It will then show up in the interface, the same as all the other profiles. We'll probably add a UI to this at some point, but for now, just copy/paste the custom profile file into that folder, and re-launch OpenShot.

Daily builds of OpenShot can be found on www.openshot.org/download (then click 'Other Installers" link). This might take a few hours before the build shows up though.

**Comment by m3hdad** [comment]
Thanks for your comment. But it did not work. I just copied my custom profile from previous version and paste in /.openshot_qt/profiles/. It just did not work. I also tried /.openshot_qt/user_profiles/. but still didn't get anything.

**Comment by m3hdad** [comment]
BTW my OS is ubuntu 15.10

**Comment by jonoomph** [comment]
Please attach the custom profile file here, and I'll test it out. Also, please be sure you are running the newest daily build, with today's date/time next to it (on www.openshot.org/download - 'Other Installers link').

The profile will be sorted alphabetically with all the other ones, so be sure the "name" inside your profile is recognizable. =) Thx!
