### ISSUE TITLE
Video and Audio glitch/stutter every second or so.

### ISSUE THREAD

**Issue by athompsonG85** [OpenShot/openshot-qt#1550]
**System Details:** HP Elitebook Corei7 with 500GB SSD
* Operating System / Distro: ? Windows 7 Pro
* OpenShot Version: Recent 2.4.1
* _Please attach log files if crash_

Imported a Mpeg4 (H.264) and when simply played back it stutters video and audio every second or so. Also when importing a .png (converted powerpoint slide) it say it can't import (not valid... yes i exported as a .png I didn't simply rename the extension.)

**Comment by peanutbutterandcrackers** [comment]
You might want to try out the latest daily build. Please head over to the [download](https://www.openshot.org/download/) page and click on the 'daily build' button and grab the latest one. The daily versions are known to work better than v2.4.1. Or, perhaps wait for v2.4.2, which should be out within a couple of weeks. Hope that helps!

P. S: If there are still problems with the daily build, you might want to use [this tool](https://mediaarea.net/en/MediaInfo) to extract information about the media file and provide the info here. That should help others help you. Thanks!

**Comment by DylanC** [comment]
@athompsonG85 Can you try v2.4.2 and let us know if you have any success?
