### ISSUE TITLE
Exported videos are glitchy

### ISSUE THREAD

**Issue by belleblaasbel** [OpenShot/openshot-qt#1552]
**System Details:**
* Operating System / Distro: windows 10
* OpenShot Version: Downloaded Daily 1 mei
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
Exported videos are glitchy in all formats when played in windows standard media player. Videos are ok when played in openshot and also on VLC. But i need them in MediaLab and there they are glitchy too.

**Comment by gary9872** [comment]
All formats? So you have tried mpeg-2 video, with mp2 or pcm audio?

**Comment by DylanC** [comment]
@belleblaasbel Can you try v2.4.2 and let us know if you have any success?

**Comment by belleblaasbel** [comment]
Eventually it worked with different output settings. Thanks

Op ma 2 jul. 2018 11:48 schreef DylanC <notifications@github.com>:

**Comment by DylanC** [comment]
@belleblaasbel - Good to hear, thank you!
