### ISSUE TITLE
Gaussian Blur

### ISSUE THREAD

**Issue by TavernSenses** [OpenShot/openshot-qt#1554]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: 2.4.1
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

The blur filter appears to simulate only motion blur. Is there a simple Gaussian blur filter, so that you can simulate "out of focus" (works for both static as video images)?

EXAMPLE: how do I blur a car's license plate in a video?

**Comment by DylanC** [comment]
@TavernSenses - I don't think we have this feature yet. Maybe we could consider adding it.
