### ISSUE TITLE
Idea/request: Auto image detect and auto video creation

### ISSUE THREAD

**Issue by m-ex** [OpenShot/openshot-qt#1556]
That's an idea:
starting this option, there should be next options:
1. Select folder to monitor
So when new images are added to folder (for example program should wait for new 2-10-100 images) and when that amount of new images are added to folder program start to render a video file.
2. video file output folder
3. video output setting, WxH, bitrate etc.

That's all, if it can be realized, than it would be great

**Comment by peanutbutterandcrackers** [comment]
Pretty sure an ffmpeg script could be written for this.

But OpenShot kinda' does automatic video creation out of the images given to it though. [This](https://youtu.be/VE6awGSr22Q?t=252) video shows how OpenShot can largely automate video creation from images. So, yeah. Perhaps you'd like to do that for now, good sir?

Hope that helps!
