### ISSUE TITLE
OpenShot crashing while trying to use transitions

### ISSUE THREAD

**Issue by CamperJohn** [OpenShot/openshot-qt#1558]
**System Details:**
* Operating System / Distro: Windows 10 Version	10.0.16299 Build 16299
* OpenShot Version: 2.4.1-dev1
* _Please attach log files if crash_
** I do not know where the log file is located...will supply if directed to them.

**Issue Description and steps to reproduce:**

OpenShot crashes every time I try to add a transition.
Whether overlaying two images or adding an existing transition from the menu the program crashes when the timeline track (red vertical line) comes in-line with the transition.
I tried to add a screenshot of the problem.

![2018-05-04](https://user-images.githubusercontent.com/38983332/39632643-48fe8970-4f7b-11e8-9b06-89ae7be45c3c.png)

**Comment by CamperJohn** [comment]
I reviewed the Users Manual and found how to capture the log...attached.

[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/1974844/openshot-qt.log)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/1974845/libopenshot.log)

**Comment by peanutbutterandcrackers** [comment]
Could you please [try out the latest daily build](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914) and see if that works for you?

**Comment by CamperJohn** [comment]
After a little testing, the latest build seems to have resolved my issue...thanks.
