### ISSUE TITLE
The program plays the sound out of the speakers, even though there are headphones plugged in.

### ISSUE THREAD

**Issue by HenryMicheal** [OpenShot/openshot-qt#1559]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

**Comment by peanutbutterandcrackers** [comment]
I think this might be related to #1390 and, possibly, #1505

**Comment by DylanC** [comment]
@HenryMicheal Can you try v2.4.2 and let us know if you have any success?
