### ISSUE TITLE
Windows Vista install python problem

### ISSUE THREAD

**Issue by bdurr** [OpenShot/openshot-qt#156]
I installed OpenShot on a Vista laptop, which seemed to go ok.  When I try and start it I get a bunch of python errors.  The report frame is titled cx_Freeze: Python error in main script.  It won't let me copy and paste the contents easily.  The traceback references a bunch of python paths that don't exist.  I do have Python 3.5 installed but the real path is not what's shown in the long traceback list.  Is there something I failed to specify?

**Comment by jonoomph** [comment]
I haven't personally tested OpenShot on Vista, but in theory it should work. What version are you testing with? Please grab the latest daily build: www.openshot.org/download (and click the 'Other Installers' link). Also, please "uninstall" the previous version before installing the new one.

Once you do that, if it still errors, please take a screenshot and post the pic here. Thx!

**Comment by bdurr** [comment]
I uninstalled the 2.0.7 stable version and installed the latest, which was v2.0.7-12-ga42479f-47-531-x86_32.msi.  The same issue occurred.  Screenshot attached I hope.  None of the paths listed exist - python3.5 is installed but a totally different path.  Thanks for the help.

![capture](https://cloud.githubusercontent.com/assets/18452077/14539212/4d141390-0234-11e6-8b3d-1688c2ed0e7f.JPG)

**Comment by NValerij** [comment]
It seems I faced the very look like this problem - OpenShot starts with error with the same title.
In its error description OpenShot says that it can't write to some file in Users directory:
> cx_Freeze: Python error in main script
> ---------------------------
> Traceback (most recent call last):
>   _File "C:\Program Files (x86)\OpenShot Video Editor\classes\json_data.py", line 143, in write_to_file_
>     _with open(file_path.**encode('UTF-8')**, 'w') as f:_
> FileNotFoundError: [Errno 2] No such file or directory: b'C:\\Users\\**\xd0\x92\xd0\xb0\xd0\xbb\xd0\xb5\xd1\x80\xd0\xb8\xd0\xb9**\\.openshot_qt\\openshot.settings'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Program Files (x86)\OpenShot Video Editor\classes\app.py", line 76, in __init__
>     self.settings.load()
>   File "C:\Program Files (x86)\OpenShot Video Editor\classes\settings.py", line 100, in load
>     return self.write_to_file(file_path, self._data)
>   File "C:\Program Files (x86)\OpenShot Video Editor\classes\json_data.py", line 148, in write_to_file
>     raise Exception(msg)
> Exception: Couldn't save user settings file:
> C:\Users\Валерий\.openshot_qt\openshot.settings
> [Errno 2] No such file or directory: b'C:\\Users\\**\xd0\x92\xd0\xb0\xd0\xbb\xd0\xb5\xd1\x80\xd0\xb8\xd0\xb9**\\.openshot_qt\\openshot.settings'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
>   File "openshot_qt/launch.py", line 77, in <module>
>   File "openshot_qt/launch.py", line 70, in main
>   File "C:\Program Files (x86)\OpenShot Video Editor\classes\app.py", line 79, in __init__
>     exit()
> NameError: name 'exit' is not defined
> 
> ---------------------------
> ОК   
> ---------------------------

Something mixed with encodings (my account name is written in Cyrillic).
To fix this problem I just deleted bold text in italic-marked line.

Now I have the same issue as #29 =)

**Comment by jonoomph** [comment]
I have made some improvements to fix some encoding issues. Have you tried the latest daily build?

Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot. Thx!

**Comment by bdurr** [comment]
I uninstalled the previous version and installed the latest version - unfortunately with exactly the same result.  Thanks.

**Comment by NValerij** [comment]
As of me uninstall/install again helped. Now it starts Ok out of the box.
Note for @bdurr: it is easy to copy error message with Ctrl-C. Hope it can help locate error.

**Comment by bdurr** [comment]
Uninstalled the last version and installed the 4-24 3:46 pm version.  Exactly the same result.  I'm wondering why it looks in the wrong place for python support.

**Comment by jonoomph** [comment]
I think the python paths are misleading... and are reporting the path on my build server. The error indicates it can't load the openshot DLL / python modules... still not sure what's happening.

**Comment by DylanC** [comment]
Issue has been resolved in #374 and the linked tickets inside that one. Closing for now since all issues related have been solved.
