### ISSUE TITLE
Slicing Innacuracy

### ISSUE THREAD

**Issue by sspmrsomebody1** [OpenShot/openshot-qt#1561]
Windows 8.1
OpenShot-v2.4.1-104-ge93e5f7-59-697

So, I imported a video, and split it using Ctrl+K in several places and they didn't split where the playhead was. I changed the zoom to see if it would fix it but it was still not working.

[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/1976296/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/1976297/openshot-qt.log)

**Comment by peanutbutterandcrackers** [comment]
I think this might be related to #1369

**Comment by DylanC** [comment]
@sspmrsomebody1 Can you try v2.4.2 and let us know if you have any success?
