### ISSUE TITLE
Thank you for an awesome program

### ISSUE THREAD

**Issue by audioclown** [OpenShot/openshot-qt#1562]
Thanks for a awesome programe ,loving the greenscreen i'm also having sound issues with breaking audio but other than that top work ,your transistions are cool ,i really apreciate the hard work you have put in as i just tried camtasia lol it sucks compared to yours .

**Comment by DylanC** [comment]
@audioclown - Thanks for the awesome feedback! :)

**Comment by sspmrsomebody1** [comment]
I love the interface and you have made some great improvements to performance recently, but I think the buffer needs to go further ahead, as when I play video it keeps freezing. Thank you for making OpenShot! #1567

**Comment by jonoomph** [comment]
Indeed, thanks for the positive energy and nice words!! Thanks @audioclown!
