### ISSUE TITLE
Drag & Drop of files with Umlaut in name fails

### ISSUE THREAD

**Issue by huste** [OpenShot/openshot-qt#1564]
**System Details:**
* Operating System / Distro: Win10 64bit German
* OpenShot Version: 2.4.1

**Issue Description and steps to reproduce:**

Try to drag&drop a file (in my case an mp3) to the project files, when it has an Umlaut in it's name. I tried it with ä.mp3 because first I thought, the filename was too long, so I shortened "Die Ärzte - Nie Wieder Krieg, Nie Mehr Las Vegas.mp3" to simply "ä.mp3".
Adding the file via the main menu works, though.

**Comment by DylanC** [comment]
@huste - Hi there, recently a fix went in for this. Can you try a daily build please?

**Comment by huste** [comment]
@DylanC : It works in OpenShot-v2.4.1-104-ge93e5f7-59-697-x86_64.exe 
Thanks

**Comment by DylanC** [comment]
@huste - Great news, thanks! :)
