### ISSUE TITLE
ubuntu 17.10 animated title get "No frame was found in the output from Blender"

### ISSUE THREAD

**Issue by LuisBL** [OpenShot/openshot-qt#1565]
**System Details:**
* Operating System / Distro: ubuntu 17.10
* OpenShot Version:  OpenShot version 1.4.3

Blender and OpenShot are working well in my OS, but when I try to get animated title a popup say:

```
Path to Blender:
/usr/bin/blender

Erreur finale :
No frame was found in the output from Blender
```

**Issue Description and steps to reproduce:**

I've seen #493 and #470 

Will be happy to help with some guidance.

More info:
```
$ more /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.10
DISTRIB_CODENAME=artful
DISTRIB_DESCRIPTION="Ubuntu 17.10"
$ which blender
/usr/bin/blender
$
$ openshot --version
...
OpenShot version 1.4.3
$
```

**Comment by LuisBL** [comment]
I checked that `*.blend` files are::
```
$ ls /usr/share/openshot/openshot/blender/blend/explode.blend
/usr/share/openshot/openshot/blender/blend/explode.blend
```

So I guess that, for a debug purpose, I could run some kind of ::
```
$ blender -b /usr/share/openshot/openshot/blender/blend/explode.blend -P scriptXYZ.py
```
If you could provide me with a `scriptXYZ.py` script.

**Comment by DylanC** [comment]
Issue #493 and #470 are both in relation to the v2.x series of Openshot. We don't really support v1.4.3 anymore since development stopped on that version a long time ago. 

I can add a tag here for people to possibly help you but I don't know if someone will have the answers you need.

**Comment by LuisBL** [comment]
ok so if I get it correctly the best thing to do here is not to use the ubuntu openShoot 1.4.
I upgraded to ubuntu 18.04 and now openShoot version is `OpenShot version 2.4.1` !

**Comment by N3WWN** [comment]
If you can use 2.4.1, I'd say, "Yes, please do!" 😉
