### ISSUE TITLE
Video Zooming in

### ISSUE THREAD

**Issue by BadFoxDragon** [OpenShot/openshot-qt#1566]
**System Details:**
Ryzen 1200
16gb 2400mhz ram
256gb Samsung 950 Pro
GT 1030
* Operating System:
Windows 10
* OpenShot Version:
Latest at time of posting

I'm fairly certain it's because it's video that had to be downloaded from Mixer because it was a livestream done on an Xbox One (if that's the sole reason that's fine, I'll just have to invest in a capture card). The problem is, when I put the video file in the timeline to edit it, randomly in the video it will zoom in in the preview, it varies as to how much but it jumps around from no zoom to top left quarter to top left eighth and back again whenever it wants. 

When the raw file is played in Chrome or VLC player it plays just fine with none of the aforementioned zooming. I do not want to have to upload the video file for someone to analyze as it's 11gb and would take quite a long time on my current upload speed.

All I'm asking is for ways to maybe fix the problem, or confirmation that it is indeed simply because that it was an Xbox One stream that was then downloaded from Mixer.

![screenshot 1](https://user-images.githubusercontent.com/39031979/39675875-32270258-512f-11e8-9223-090c670badf9.png)
![screenshot 2](https://user-images.githubusercontent.com/39031979/39675876-3231276a-512f-11e8-9752-96f27affce2d.png)

**Comment by peanutbutterandcrackers** [comment]
Oh. I see. However, would you please use [media info](http://mediaarea.net/MediaInfo) and give us the details about the video so that we can fix it in the future releases? Thanks!

**Comment by N3WWN** [comment]
Sharing a very short video that exhibits this issue would be VERY useful.  Even just a few seconds of the one you imported into OpenShot would be perfect!  Thanks!

**Comment by BadFoxDragon** [comment]
Heres the media info
[this.zip](https://github.com/OpenShot/openshot-qt/files/1984384/this.zip)
and heres a segment of video
https://ufile.io/i89rh

**Comment by BadFoxDragon** [comment]
I do really like the program! And I'm fairly certain it's just the fact that it was an xbox stream that was then downloaded from Mixer. I will honestly probably be making the move back to it after a while. For now though I'm going to be using Sony Vegas Pro 14, and will be checking in on OpenShot every now and then for updates and features.

BTW, you guys could totally have the option when installing to add stock sound effects and images to the editors library, stuff like the hitmarker sound from COD, a plethera of troll face stuff, ways to add text in random places and times. Go watch some of M3rkMus1k's stuff on youtube as example. You could be the "go to" for easy youtube editing!

**Comment by N3WWN** [comment]
Thanks for uploading those @BadFoxDragon !  

Is the video clip an example of how it _should_ look or an example of how OpenShot is mishandling it?

**Comment by BadFoxDragon** [comment]
How it's mishandling it, it should be the full screen of the game. Again
vlc doesn't do that with the raw file.

**Comment by BadFoxDragon** [comment]
I don't really have a way of just cutting out a part of the raw file. If
you have a way let me know, I can do it when I get home in 4~ hours.

**Comment by N3WWN** [comment]
The `ffmpeg` command line utility should do the trick: https://www.ffmpeg.org/download.html

You can tell it to extract a small portion and copy the audio and video streams instead of transcoding them, giving us a [hopefully] perfect copy of what is in your raw file.  

Give this a try:

`ffmpeg -ss 00:00:30 -i source.mp4 -t 00:00:10 -codec copy Issue-1566.mp4`

This command will extract 10 seconds of the source.mp4 video, starting 30 seconds into the clip.

If it doesn't matter where in the video the segment is taken from, you can skip the `-ss` param.  Likewise, if you think we'll need 40 seconds to see the issue, adjust the `-t` param:

`ffmpeg -i source.mp4 -t 00:00:40 -codec copy Issue-1566.mp4`

Replace `source.mp4` with the raw filename if that is not the name.  I got the filename from your screenshots.

If the file extension is not `mp4`, please use the same file extension for the Issue-1566 file as the original file.

For instance, if the name is awesomeVid.MTS, you'd use:

`ffmpeg -i awesomeVid.MTS -t 00:00:10 -codec copy Issue-1566.MTS`

Let me know if you have any problems.  This is a very interesting issue, indeed!

**Comment by BadFoxDragon** [comment]
I'll definitely be testing all that later. Probably two parts, one that
openshot sees fine and one that's zoomed. Quite a few other editing
softwares do the same thing though, so it's not unique to openshot.

**Comment by BadFoxDragon** [comment]
okay, teach me. how do i actually USE ffmpeg

**Comment by N3WWN** [comment]
Where are you getting hung up at?

Did you download a Windows version of ffmpeg?  I found one here: https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-4.0-win64-static.zip

After downloading it, extract the files from the zip, which should leave two txt files and three directories (bin, presets and doc).

To make things easy, you can either copy the ffmpeg.exe from the bin directory to the directory that has your raw file, or copy your raw file to the bin directory.

Either way, get the ffmpeg.exe and raw file in the same place, open a command prompt window and use `cd` to change your current directory to where ffmpeg.exe and the raw file are located.

If you're unsure of how to do this, you may be able to open a command prompt window from the file explorer using the tips on this page:  http://www.thewindowsclub.com/how-to-open-command-prompt-from-right-click-menu

Once you have a command prompt window in the correct directory (you can make sure the two files are present by executing a `dir` command), you should be able to use the ffmpeg commands I provided above:

`ffmpeg.exe -i source.mp4 -t 00:00:40 -codec copy Issue-1566.mp4`

If you have spaces in your video files, you can enclose them in quotes:

`ffmpeg.exe -i "my source.mp4" -t 00:00:40 -codec copy Issue-1566.mp4`

If you're still stuck, please let me know exactly where you are having trouble and perhaps post a screenshot.
