### ISSUE TITLE
Not buffering properly

### ISSUE THREAD

**Issue by sspmrsomebody1** [OpenShot/openshot-qt#1567]
I play my project in OpenShot and it keeps on starting and stopping because of an insufficient buffer length. With music it's very annoying. Please can you increase the buffer length and/or make OpenShot detect when it needs more buffering?
OpenShot 2.4.1-dev1 / Installer: OpenShot-v2.4.1-104-ge93e5f7-59-697-x86_64
Windows 8.1

EDIT (OpenShot-v2.4.1-115-ge7a99e9-59-697): I set the cache limit to 2000MB and restarted OpenShot and it still lagged.

**Comment by N3WWN** [comment]
You can change the amount of RAM and/or disk space allocated to the preview cache in the `Edit-`>`Preferences`->`Cache`->`Cache Limit` setting.

**Comment by sspmrsomebody1** [comment]
Hmm, I tried that once and I think it still did it. Perhaps I didn't restart it and that was necesarry?
Anyway, I think the problem could be avoided by having a longer buffer.

**Comment by sspmrsomebody1** [comment]
The problem is that OpenShot doesn't buffer far enough ahead, and it also slows down when debuffering behind,

**Comment by peanutbutterandcrackers** [comment]
@DylanC - Cap'ain, perhaps the buffer thingy needs to be worked upon? o.O

**Comment by sspmrsomebody1** [comment]
Currently using OpenShot-v2.4.1-115-ge7a99e9-59-697-x86_64, it still has buffer problems when buffering chroma key filtered video and fade transitions.

**Comment by sspmrsomebody1** [comment]
OpenShot buffers too slowly especially when debuffering to conserve memory and rendering more demanding effects such as Chroma Key and fade transitions.

**Comment by peanutbutterandcrackers** [comment]
I have notified the devs regarding this issue. Hopefully, some steps will be made to resolve this issue (partially, even) by rc2. Thank you for helping out! :)

**Comment by DylanC** [comment]
@sspmrsomebody1 Can you try v2.4.2 and let us know if you have any success?

**Comment by ryamoo** [comment]
Hello - sorry for reviving an old thread, but I was searching for openshot forward caching and came across this.
I had the issue in 2.4.2 and just updated to 2.4.3 and it's still present.
I store my media on a USB drive so mostly use that, so put it down to that.
I tried my media on the internal SSD and it still had the issue. 

It just doesn't buffer far enough ahead. If I move the playhead back again it plays fine and the thin blue cache bar is there. As soon as I change something and it's not cached, it does the stutter thing again.

I increased the cache setting from 2048 to 3072. Before restarting, Openshot was using over 3gb ram anyway. After restarting it was using 1.5gb... 
I've just increased the setting to 4096 and tried playing a short bit of a project, and it still stutters, and Openshot was using less than 1gb of ram. 

Anything else I can try or any more information I can provide?

**Comment by mmcintyre123** [comment]
I am using the daily build from Feb. 18, 2022, 4:43 p.m.:
OpenShot-v2.6.1-dev-daily-9138-f2b89e32-2b8b05c7-x86_64.exe (64-bit)
And still observing this issue.  Please see my system specs and OpenShot preference settings below:

**System Specs**
System Type: x64-based PC
Processor: AMD Ryzen 5 3600XT 6-Core Processor, 3793 Mhz, 6 Core(s), 12 Logical Processor(s)
RAM: 32.0 GB
Storage: 1TB M.2 NVMe SSD

**Preference settings:**
Cache Mode: Memory
Cache Limit: 6000 MB
Preview: HD 720p 24fps
Default Audio Sample Rate 48000

**Observations:**
When I pause the preview playback, buffering continues to 10 seconds ahead and stops.  
When I resume playback, buffering remains stopped until the playback has reached the end of the current buffer, then it resumes.
Problem: buffering is not able to keep up with the speed of playback, and the result is jittery audio and video playback.

**Comment by JacksonRG** [comment]
@mmcintyre123 That is the cache working as intended. If the user pauses, we can cache several seconds out for the case that the video is too demanding to preview in real time. (effects like chroma key in particular slows down preview). But during playback caching was causing the playback and cache to fight for read/write access to the frame cache, so we cut it down to just a few frames so that playback was smooth.

If the frames can't rendered quick enough to preview, you might have to change the preview profile.
