### ISSUE TITLE
Multiple PNG overlays have a yellowish background

### ISSUE THREAD

**Issue by jonoomph** [OpenShot/openshot-qt#157]
This was reported on IRC by Yoan. When compositing & animating multiple PNG files together, it created yellowish background.

![fdmvrd4e5vg_bg](https://cloud.githubusercontent.com/assets/5551883/14516491/1f10e4d4-01c9-11e6-8a89-c84d05c545fd.jpeg)

**Comment by jonoomph** [comment]
Using the same PNG images, I am not able to reproduce the problem. The images are composited together correctly, and have no yellow tint.

[Logo test.zip](https://github.com/OpenShot/openshot-qt/files/218377/Logo.test.zip)

**Comment by jonoomph** [comment]
Here is a screenshot of the finished logo composite:
![screenshot-from-logo-animation](https://cloud.githubusercontent.com/assets/5551883/14516654/ea387dd8-01ca-11e6-94e9-35960acec1c7.png)

**Comment by telelauro** [comment]
I´mtrying this issue and I don´t have any problem. 
![inserto de logo en png](https://cloud.githubusercontent.com/assets/16803007/14582550/b79ffe6a-0408-11e6-9fb8-71dad5eb5eae.jpg)

**Comment by DylanC** [comment]
Unable to reproduce this issue at all.
