### ISSUE TITLE
Very Inconvenient Zooming

### ISSUE THREAD

**Issue by SilasLaspada** [OpenShot/openshot-qt#1570]
I don't know if this is a bug per se, but it is very annoying for me. The new zoom goes 1-7-14-24 and it is inconvenient for me to use, as I do a lot with smaller clips and I usually use the zoom levels between 1 and 7. Is there any way to change this in the settings? If not, I dislike this change.

**Comment by SilasLaspada** [comment]
I am using the current daily build (OpenShot-v2.4.1-115-ge7a99e9-59-697-x86_64)

**Comment by peanutbutterandcrackers** [comment]
Hmm... could you try to use a little older daily build? Previously, we had a little different zoom level. Perhaps you'll like that better? Or, in v2.4.1, the zoom level increases by 1 with each increments. Perhaps that?

We would like some feedback and to what the users prefer.

Perhaps you might want a custom-zoom level setting feature thingy? You'll probably have to file a separate enhancement request then. (You're more than welcome to do it, after all this is a community project. Please also give us ideas as to how you think it should be implemented. Thanks!)

**Comment by SilasLaspada** [comment]
I liked the way the zoom level worked in the older builds. The one in the latest stable is nice too, but it was a bit more clunky imo. I think that a custom zoom level option would be great and is probably the best long-term solution. For me at least, I think it would be best to implement a custom zoom setting before the next release, and I can use the older build in the mean time.

**Comment by peanutbutterandcrackers** [comment]
I see. Do you have any ideas as to how we might implement a custom zoom level? As in, would it be implemented in the 'preferences'? Or, something else, you might want, good sir?

**Comment by SilasLaspada** [comment]
You've got a good point, I didn't think that far ahead. I suppose a group of zoom level presets (like maybe the current one, the one from the previous builds, and the one that always increments by one) under preferences would be the best I could think of. And I'm sorry if I'm being too demanding about this, do you want me to close this in favor of an enhancement request?

**Comment by peanutbutterandcrackers** [comment]
Wow. zoom-level-presets. Pretty neato idea, indeed! What do you think, @DylanC, Cap'ain?

Maybe once you have formulated your idea, you can close this one and make an enhancement request? :)

**Comment by SilasLaspada** [comment]
Ok, that sounds great! I'll put an enchancement request up sometime tomorrow and I'll close this now.
