### ISSUE TITLE
Video stalls at certain frame

### ISSUE THREAD

**Issue by TavernSenses** [OpenShot/openshot-qt#1573]
Open Shot 2.4.1-dev1
Windows 10

When I play a my mp4 video file (codec: PNG) in OpenShot, the video is played only up till frame 11 (of 20 frames. The video is less than a second). The marker keeps running though, but the playback screen stops at frame 11.

When I play the same file in VLC Media Player, there is no problem at all. All 20 frames are played.

ADDED: it also happens in "Preview File", so it's not that I accidently entered a bogus keyframe.

**Comment by peanutbutterandcrackers** [comment]
Could you please [try out the latest daily build](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914) and see if this issue persists there too? Thanks!

**Comment by DylanC** [comment]
@TavernSenses Can you try v2.4.2 and let us know if you have any success?
