### ISSUE TITLE
Openshot creates flickering black screen clips

### ISSUE THREAD

**Issue by nolanv22** [OpenShot/openshot-qt#1574]
**Describe the bug**
The clips will not flicker from what they are supposed to show to a black screen very rapidly. It also distorts the audio but I'm not sure if this is related or another bug. I can tell you it's not my microphone's issue.

**System Details (please complete the following information):**
 - Operating System Windows 10
 - OpenShot Version [2.4.1]

**To Reproduce**
1. Use voice recorded audio file in track 1 at least 15 secs
2. record a video of gameplay using nividia geforce experience at least 10 minutes in length, and place it in track 0
3. process the video to an mp4 with 1280x720 with the quality on high

**Expected behavior**
A clean video no blinking or audio distortion
**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**
I think it has something to do with the processing of the project

**Comment by DylanC** [comment]
@nolanv22 Can you try v2.4.2 and let us know if you have any success?
