### ISSUE TITLE
Relative path for video project folders

### ISSUE THREAD

**Issue by LukeEu** [OpenShot/openshot-qt#1577]
Hello to everyone, 
I detected a bug which is at the same time a missing feature. sorry for the lenght but the problem must be explained.
the issue is related to the project folders.
As pro video producer (teacher in school context) i'm using video editing software from the beginning (1994) and all of us know how big and complex could be a video project: big in file numbers and in file sizes.
Openshot has a weak recovery system to allow the replacing of files, as described by Flyingdishes  in the issue "Cannot find files while openning an existing saved .osp " and in the consequent tread. It is clear that if we are just testing openshot, it could be aceptable to click xx times for 10 files, but if i have a project with more as 100 elements to relocate every time it is not acceptable. Think that this feature exist in premiere, avid etc.. from the beginning, because it is a foundamental feature. you must be able to open projects from external hd.
The pro scenario is usually a project folder, which contain in ordered subfolders, titles, images, videos, speech and music.
I propose for this exceptional programm, which is finally near to replace commercial products, to replace the recovery system and integrate it with an open project features that point directly to the projectfile folder or elsewhere in a selected folder, and which is able to scan for project files.

thank you
Luke

**Comment by N3WWN** [comment]
Referencing https://github.com/OpenShot/openshot-qt/issues/1325 here so it is noted in that issue
