### ISSUE TITLE
custom video canvas dimension/size

### ISSUE THREAD

**Issue by gary1976** [OpenShot/openshot-qt#1579]
I have a Daktronics GS6 (40x150) full colour animanted display for my business that is 40 pixels high and 150 pixels wide.  I want to create my own content for it.  Is it possible to custom size a video to this exact size?

I use a MacBook Air with 10.13.3 and Openshot 2.4.1

I looked at: https://github.com/gary9872/openshot-presets-testing/commit/055b68f0782c2efed618f0fa0c87febf2197fa0b?diff=unified
but I do not know where/how to create the custom profile.

**Comment by peanutbutterandcrackers** [comment]
[Here], this might help you to create custom profiles. I hope that helps. :)

**Comment by DylanC** [comment]
Closing as answered.
