### ISSUE TITLE
Audio missing on export

### ISSUE THREAD

**Issue by bdfdrmn** [OpenShot/openshot-qt#1582]
I just began using the software and am trying to edit a video that has audio on it. I can edit the video but the audio disappears. How do I keep the audio in tact?

thanks

**Comment by PASTJL** [comment]
If you put your clip in a track, under the timeline, right click on it and are you able to extract the audio ?
If you can't, as workaround, with VLC you can can convert your clip to a mp3 audio clip, and import the mp3 in your openshot project.

**Comment by bdfdrmn** [comment]
Thanks to pastjl, I did separate and put on its own track the audio.  I then went to GH and loaded the video on one track and the audio on another. I hit 'export' as mp4 and the final result again did not include the audio???  The directions are light so Im stumped as to why the audio didnt come out in the final?  What did I miss?

**Comment by PASTJL** [comment]
When you playback the clip in the timeline, does you hear the audio ? If not, do you hear the audio with VLC?
If so  try to extract it with VLC as I said above => convert clip to mp3 audio, try if you can hear in VLC and if ok import the mp3 in your openshot project.

**Comment by bdfdrmn** [comment]
Hi, and thanks again.    Yes, the mp3 audio track I made on vlc plays fine on GH.  I guess I dont know how to combine the video and audio tracks?  I set each up next to each other and hit 'export', but all i got was video.   Is there some step Im missing?

    On Tuesday, May 15, 2018, 11:28:06 PM PDT, PASTJL <notifications@github.com> wrote:  
 
 
When you playback the clip in the timeline, does you hear the audio ? If not, do you hear the audio with VLC?
If so try to extract it with VLC as I said above => convert clip to mp3 audio, try if you can hear in VLC and if ok import the mp3 in your openshot project.

**Comment by PASTJL** [comment]
Sorry my english is very poor, do you say that for example, you put the initial clip in track 1 beginning at frame/ time 0 and the mp3 audio in track 0 or 2 beginning at the same frame/time 0 ?

**Comment by peanutbutterandcrackers** [comment]
Also, you are not supposed to put audio and video "next to each other" on the same track but on two different tracks. The audio is supposed to go on a lower track while the video on the upper one.

[Here](https://www.youtube.com/watch?v=0a_B4LxTy3Y&t=14s) is a quick guide on using OpenShot.

And [Here](https://www.youtube.com/watch?v=1k-ISfd-YBE&list=PLymupH2aoNQNezYzv2lhSwvoyZgLp1Q0T) is an in-depth tutorial playlist made by the creator of OpenShot himself.

**Comment by bdfdrmn** [comment]
I appreciate your comments!  thank you.
the directions on GH are very light so for someone not really high tech like me, I dont know what to do and have to just try things.   I put the audio and video on separate tracks but will have to check which was on top. Also, originally I just ran the video which had audio already on it, and only the video came out. So thats when the problems started and didnt know what to do.  Someone else suggested using vlc to separate the audio from the video which I did. Then I put the separate video and audio tracks on GH only to find that the audio still wouldnt play.  I have Handbrake and use it on video alone but did not need it on this particular video. 
I will check out what you said, thanks again!
    On Wednesday, May 16, 2018, 8:32:38 PM PDT, peanutbutterandcrackers <notifications@github.com> wrote:  
 
 
Also, you are not supposed to put audio and video "next to each other" on the same track but on two different tracks. The audio is supposed to go on a lower track while the video on the upper one.

Here is a quick guide on using OpenShot.

And Here is an in-depth tutorial playlist made by the creator of OpenShot himself.

**Comment by bdfdrmn** [comment]
Thank you all! Im impressed with all the help Im getting!
I repositioned the audio and video tracks to put the video above.  Then in the 'export' box above, I looked at output forms, and it was on mp4. I changed it to Mov mp4 and viola! It worked!  I cant say I understand it all but am happy with the result.  It came out at 150 MB's so compressed it down to 24 and now can send it. 

Thanks again! I really appreciate it.

**Comment by peanutbutterandcrackers** [comment]
@bdfdrmn - We're always happy to be of help. Please do keep on loving and supporting OpenShot. It is a community backed project and we all can do our little bit to make it better.

[Here](https://gist.github.com/peanutbutterandcrackers/f0f666243133e0ed25abbc12a4ba23d7), I have just compiled a list of resources to help you (and others) become an OpenShot Ninja. Hope this is of some help. All the very best, kind sir! :+1:

**Comment by bdfdrmn** [comment]
Richard, I have a question for you, please.    When I slice to the left and right of a clip I want, after exporting, the left side is gone but still comes out as a dark screen for the period of time I thought I deleted.  When adding markers and slicing to edit a clip, how do I completely delete the part to the left of the marker so the clip begins at the slice?
thank youBill
    On Thursday, May 17, 2018, 11:55:36 AM PDT, Richard Alloway <notifications@github.com> wrote:  
 
 
@bdfdrmn - Can you give this a try: Export Video -> Advanced -> Audio Settings -> Audio codec and change ac3 to aac :



...now export your video and see if the audio is in tact.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
     

|  | Virus-free. www.avast.com  |

**Comment by DylanC** [comment]
@N3WWN -  ^ Another question for you if you have a chance to answer.

**Comment by peanutbutterandcrackers** [comment]
@bdfdrmn - It seems that @N3WWN is not quite active in the forums right away (he's a busy man). Therefore, I would like to help you out. Could you please attach a screenshot of the project and the part where you have kept the left and the right side? And a screenshot of the final video, too? A screen-recording would be even better, too.

Also, [here](https://gist.github.com/peanutbutterandcrackers/f0f666243133e0ed25abbc12a4ba23d7) is a guide to OpenShot mastery. I hope that'll help you out. :+1:

**Comment by bdfdrmn** [comment]
Thanks, Richard!   Ive since learned to 'split clip' in the top menu, and that is easy and works well.  Oddly, my finished shortened file is much larger in mb's than the original. Dont understand why
    On Wednesday, May 30, 2018, 7:44:19 AM PDT, Richard Alloway <notifications@github.com> wrote:  
 
 
Sorry, $dayjob is REALLY busy right now and Open Source contributions (part of my job) have a lower priority than helping paying customers... hopefully you understand. 😃
 
It sounds like you're putting a clip on the timeline, slicing/cutting off the start and/or end and then exporting. If this is correct, then the blank space at the start is to be expected. OpenShot exports from the start of the timeline though the end of the last clip.

In order to remove the blank section, move the trimmed clip all the way to the left on the timeline so it starts at 00:00:00:01 (frame 1 at time 00:00:00).

Give that a try and let us know...

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
   

|  | Virus-free. www.avast.com  |

**Comment by N3WWN** [comment]
Happy to help 😁   

We're discussing the size of the rendered image versus the size of the original in https://github.com/OpenShot/openshot-qt/issues/1628 , so you can probably close this issue (assuming your question is now answered).

Thanks!

**Comment by DylanC** [comment]
@N3WWN - Thanks Rich!
