### ISSUE TITLE
Video Audio Unable To Play On Mobile Devices

### ISSUE THREAD

**Issue by MisterTeeXD** [OpenShot/openshot-qt#1583]
**Describe the bug**
When a video is rendered in Openshot and then moved to a Android/iOS Device, then the audio is unrecognised by the device and cannot play

**System Details (please complete the following information):**
 - Operating System / Distro: Windows 10
 - OpenShot Version 2.4.1-90

**To Reproduce**
1. Go to File
2. Click on Export Video
3. Scroll Down to (No Scrolling Needed)
4. See error by moving the video file on a mobile device and play the ideo

**Expected behavior**
The device recognises the audio and plays the video with the audio

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**
A few builds back, this bug was still there

**Comment by peanutbutterandcrackers** [comment]
Can you please use the VLC app to play the video? I think it's just an encoding/decoding issue. Perhaps we need to have a separate 'mobile devices' profile?

**Comment by DylanC** [comment]
@MisterTeeXD Can you try v2.4.2 and let us know if you have any success?
