### ISSUE TITLE
Crashes on Windows 10

### ISSUE THREAD

**Issue by tkvarenes** [OpenShot/openshot-qt#1584]
Crashes both when I am previewing a project or exporting it.
It seems to be related to the amount of effects and transitions made to the project. 
I have a project with 2 tracks (Track 4 and Track 3), both rotated 90 degrees, and track 4 with fade-in and fade-out.
Works on the preview, but then, after slowing down track 4 by 1/2, it crashes when previewing. Always at the same spot, when the transition to track starts.

I have had other examples other, where it crashes when the transition to the track starts fading in.

**System Details (please complete the following information):**
Windows 10, Openshot version 2.4.1

**Comment by peanutbutterandcrackers** [comment]
I would suggest that you [try out the latest daily build](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914). A lot of the issues has been resolved in the daily builds. Hope this helps!

**Comment by rudolfolah** [comment]
I think I just had this problem with the zoom and fade transitions; loaded up 3 video clips and it was fine then added the transitions and it crashed (possibility though that I've run out of space on the drive, so I'm going to see if that's the issue).

**Comment by peanutbutterandcrackers** [comment]
For now, as reported by others, deleting the `.openshot_qt` folder does, indeed, seem to do the trick. The folder is located in `C:\Users\Your_Username\`  folder on windows, I believe. Or thereabouts.

On a side note, v2.4.2 is going to be released really soon. Any day now. That will come with a ton of fixes and improvements. So, that's something to look forward to!

**Comment by DylanC** [comment]
@tkvarenes Can you try v2.4.2 and let us know if you have any success?
