### ISSUE TITLE
Headphones not holding sound in video

### ISSUE THREAD

**Issue by MrSpaceChicken** [OpenShot/openshot-qt#1588]
**Describe the bug**
I am using the video editing software and i have bluetooth headphones connected ass my default device. I know they are working with everything else on my computer because I tested it but the music from my video plays on the laptop speakers, not the headphones. Solutions?

**System Details (please complete the following information):**
 - Operating System / Distro: Windows 10
 - OpenShot Version: Just downloaded it so most recent

**To Reproduce**
1. Set up headphones to your pc
2.  Test to see if sound works for those headphones on the pc
3. open up a file and play anything with sound
**Expected behavior**
I expected the music and sound of video to play through my headphones, and I think I woke up my brother because of it

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**

**Comment by peanutbutterandcrackers** [comment]
Probably related to #1559, #1390 and possibly #1505

**Comment by DylanC** [comment]
@MrSpaceChicken Can you try v2.4.2 and let us know if you have any success?

**Comment by ferdnyc** [comment]
This is fixed, anyway, by the new audio device selection features added to post-2.4.4. (We really need to get a release out, so we have a version number we can use when talking about the new code.)
