### ISSUE TITLE
Zoom-level alterations on an unsaved project triggering require_save in the project without any other substantial changes

### ISSUE THREAD

**Issue by peanutbutterandcrackers** [OpenShot/openshot-qt#1592]
**Description**
Currently, on an unsaved project, with no real changes and just zoom-alteration, the project requires saving and the save indicators are lit up. It would be nice if zoom-alterations triggered requires_save() (or whatever the function is) only after the project has actually been saved. Not really a bug. Just something I think would be more elegant.

**System Details:**
 - Operating System / Distro: Linux Mint 18.3, Elementary OS 0.4.1 'Loki'
 - OpenShot Version 2.4.1+ (latest daily build from the PPA)

**To Reproduce**
1. Run OpenShot
2. Change zoom level by adjusting the zoom slider
Project Save indicator is shown.

I am well aware that `.osp` file also saves the zoom level, and that it is a design choice. I just think it isn't necessary for change in zoom level to trigger save requirement of an untitled project with nothing in it to save.

**Comment by DylanC** [comment]
@peanutbutterandcrackers - Sounds like something we should fix.
