### ISSUE TITLE
Preview Stutters When Chrome Key Is Applied

### ISSUE THREAD

**Issue by MisterTeeXD** [OpenShot/openshot-qt#1593]
**Describe the bug**
When Chroma Key is applied to a green screen video, the preview will stutter.

**System Details (please complete the following information):**
 - Operating System / Distro: Windows 10
 - OpenShot Version: 2.4.1-90

**To Reproduce**
1. Go to Effects
2. Click and Drag on Chroma Key and apply it to the green screen video clip
3. Scroll down to (No scrolling needed)
4. See error by playing the video and looking at the preview window

**Expected behavior**
The Preview will play smooth when chroma key is applied to the video clip

**Screenshots**

**Logs**
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/2008551/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2008567/openshot-qt.log)

**Additional context**
No Further Additional Context

**Comment by peanutbutterandcrackers** [comment]
I think the chroma key code does need quite a bit of brushing up, and that the program itself needs to become a lot more robust. We do have a few regular contributors to the project now and they're doing their best to make OpenShot better. Thank you, too, for doing your bit in making OpenShot better, good sir! :)

**Comment by DylanC** [comment]
Dup of #1412
