### ISSUE TITLE
Sounds og video bug when video is exported

### ISSUE THREAD

**Issue by EsbenAndersen** [OpenShot/openshot-qt#1598]
The video I export is never the same as the project I'm working on. When I run my video/project in openshot it runs smoothly without any problems. When I export it, either there is some sounds issues or video bugs. I've tried many different video profiles.

It's on windows 10 and I guess it's the newest version since I just downloaded it.

**Comment by peanutbutterandcrackers** [comment]
You are probably using v2.4.1 which is indeed the latest stable version. But you might want to [try the latest daily build](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914) which contains all the changes made to the code since v2.4.1.

**Comment by DylanC** [comment]
@EsbenAndersen Can you try v2.4.2 and let us know if you have any success?
