### ISSUE TITLE
Size of Clip on TimeLine (Zoom Level) makes Effects difficult to modify

### ISSUE THREAD

**Issue by dudeguy-perc** [OpenShot/openshot-qt#160]
when you're dealing with a very short clip, like animation  / chroma keyed rotoscope; it can be difficult to modify the Effects of the clip, could Effects be appended to Properties? Or could the time line be zoomed in significantly more than it can now?

Xubuntu 14.04, OpenShot 2.0.7

**Comment by qubodup** [comment]
Yes, please allow to zoom closer. So many of us need to be able to do frame-exact editing. :)

Also see:
https://github.com/OpenShot/openshot-qt/issues/224
https://github.com/OpenShot/openshot-qt/issues/415
https://github.com/OpenShot/openshot-qt/issues/313

**Comment by DylanC** [comment]
This issue is still open. Closed duplicate issues so we can track it here.

**Comment by DylanC** [comment]
Closed some more duplicate issues

**Comment by DylanC** [comment]
You can now zoom in fully in v2.4.

**Comment by N3WWN** [comment]
The zoom level still appears to be limited to 1s in 2.4.0, making it difficult to align clips accurately.  

Many times, I have to try to shift a clip by a single pixel (sometimes clicking and releasing the left mouse button is enough) to get clips to align.  

Can the zoom level be increased to 0.1s (or perhaps unlimited)?

**Comment by DylanC** [comment]
@N3WWN - Oh I thought 1s was good enough. Well I'll check if more is required.

**Comment by N3WWN** [comment]
1s was a definite improvement, but we want more 😀 

Thanks for looking into it!

**Comment by DylanC** [comment]
@N3WWN - I have added an enhancement for this in #891. Thanks for your feedback.
