### ISSUE TITLE
Music disappears on exported file after 1:45 minutes

### ISSUE THREAD

**Issue by djbounty** [OpenShot/openshot-qt#1603]
After I completed the video with an MP3 file (total video 2:40 minutes), the music disappears after 1:45 minutes and is then gone for the remainder of the movie. 

Before the sound disappeared, there was a small 'radling' sound for like half a second, like a computer which could not handle the export. Mine would be a i5 with 8GB, so I would say there would not need to be any problem there. See file on my Youtube channel: https://youtu.be/Ln3N5YyTgBo

I had this before on a previous project in which I had to cut the MP3 in 2 pieces and them in twice.

Please advice, thx!

**Comment by peanutbutterandcrackers** [comment]
Hey there!

In case you're using v2.4.1, the first step would be to [switch to the daily builds](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914) as they are known to be a lot more stable than v2.4.1. You might want to render the project again from the latest daily build. It will probably work then. All the very best! :+1:

**Comment by DylanC** [comment]
@djbounty Can you try v2.4.2 and let us know if you have any success?
