### ISSUE TITLE
Computer language not used ?

### ISSUE THREAD

**Issue by nsgitfr** [OpenShot/openshot-qt#1608]
@DylanC 
@peanutbutterandcrackers
Regression or miss use ?

**Describe the bug**
Interface is not set to locale. Remains EN.

**System Details (please complete the following information):**
 - Operating System / Distro: Windows 10, 
 - OpenShot Version OpenShot-v2.4.1-117-g964d420-60-711-x86_64.exe

**Logs** 
Attached

As previous distro, setup, install, uninstall are set to locale properly. 
App is not and remains as EN.
Local Windows is FR

Best

[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2028929/openshot-qt.log)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/2028930/libopenshot.log)

**Comment by DylanC** [comment]
@nsgitfr - I don't think it currently has that feature. Might be something good to add though.

**Comment by nsgitfr** [comment]
@DylanC - What is language asked during setup used for then ?

**Comment by peanutbutterandcrackers** [comment]
Confirmed as present in v2.4.2 by #1784; the issue also confirms that this particular bug wasn't present in v2.4.1. So, a 2.4.2-issue

**Comment by peanutbutterandcrackers** [comment]
@dmapdm - Please follow the discussion here. Plus, @nsgitfr is your fellow French. :)
