### ISSUE TITLE
Video and sound are 1,2x faster during editing.

### ISSUE THREAD

**Issue by PetrxStepanek** [OpenShot/openshot-qt#1609]
The program started playing video and audio tracks approximately 1.2 times faster during editing, so the video is faster and the voice sound does not match the reality.
I reset the video and audio time, but it did not even work.
I've installed the Daily Builds (from May 22, 2018) today.

**Comment by peanutbutterandcrackers** [comment]
Sorry for the late reply, good sir.

Perhaps you are editing in a different profile? Maybe the original footage is 24fps but you are editing in 30fps? That could be a reason why it's behaving that way...

**Comment by PetrxStepanek** [comment]
Thanky you for your reply. I will check it and try chance profile. 
However, the exported video already has the sound at the right speed.

**Comment by peanutbutterandcrackers** [comment]
Hmm... that is quite strange...

**Comment by DylanC** [comment]
@PetrxStepanek Can you try v2.4.2 and let us know if you have any success?
