### ISSUE TITLE
Last 3 Seconds Of Exported Video Freezes

### ISSUE THREAD

**Issue by MisterTeeXD** [OpenShot/openshot-qt#1611]
**Describe the bug**
When a video is exported, the last 3 seconds near the end is frozen

**System Details (please complete the following information):**
 - Operating System / Distro: Windows 10
 - OpenShot Version 2.4.1-90

**To Reproduce**
1. Go to File
2. Click on Export Video
3. Scroll down to (No scrolling needed)
4. See error by replying the video file

**Expected behavior**
The last 3 seconds will not be frozen when exported

**Screenshots**
I have zipped a Example Video of the bug (See at the end)
[Figure That Out.zip](https://github.com/OpenShot/openshot-qt/files/2032522/Figure.That.Out.zip)

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**
This bug was in all builds of Openshot and still exists

**Comment by sspmrsomebody1** [comment]
I have had a similar problem but it was only the last 1 second. Also I noticed if I put it back into OpenShot the ending would jump around and glitch.

**Comment by DylanC** [comment]
@MisterTeeXD Can you try v2.4.2 and let us know if you have any success?
