### ISSUE TITLE
crackling and distortion in preview

### ISSUE THREAD

**Issue by maldu0** [OpenShot/openshot-qt#1613]
**Describe the bug**
video files that are loaded into openshot have heavily distorted audio and crackling while the original video sounds fine, with no distortions or crackling. this does not persist in exported videos, just in the preview. this is my first time using openshot, so I apologize if it's something really obvious. 

**System Details**
Windows 10 64 bit
Openshot 2.4.1

**Expected behavior**
video files loaded into openshot have normal audio that isn't altered from the source

**Comment by maldu0** [comment]
ok, i will try it and see if my issue is resolved, thanks!

**Comment by maldu0** [comment]
i'm afraid after a while of testing multiple file formats and attempting to screw around in the settings for a while, I've concluded that even the daily build has the same problem.

**Comment by peanutbutterandcrackers** [comment]
Hmm... could you please [attach the logs](https://github.com/OpenShot/openshot-qt/blob/develop/CONTRIBUTING.md)? But first, I would like to recommend that you grab the latest daily build again. It's v2.4.2-rc1.

**Comment by maldu0** [comment]
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2087116/openshot-qt.log)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/2087117/libopenshot.log)

**Comment by peanutbutterandcrackers** [comment]
Wow. Thank you for the logs. However, they do seem to be quite huge.

If you do not mind, could you please go to your `.openshot_qt` folder again, delete these logs, run OpenShot again (I really really really hope you are running version 2.4.2-rc1 - or more recent one - by now) and re-create the crash/crackling/distortion, close the program and then attach the logs here - all in one go? That would make the size of the logs far smaller and the devs will be able to go through them faster. These are way too big...

Sorry for the inconvenience, good sir...

P. S: There were a number of fixes pushed into the source tree regarding this issue, though... Maybe some more fixes need to be made?

**Comment by maldu0** [comment]
so, um, I did exactly that, opened openshot, placed the files in, listened to the broken audio and then closed the program, but the logs are still enormous. they're around the same size as the other ones. not sure what i did though. i followed the instructions for creating logs, and then attempted to recreate the bug as quickly as i could without touching anything that was unnecessary, and they're almost the exact same in size.

**Comment by peanutbutterandcrackers** [comment]
Did you try rc2? There were a few commits addressing this same issue just before the release of rc2. Maybe that'll help?

**Comment by DylanC** [comment]
@maldu0 Can you try v2.4.2 and let us know if you have any success?

**Comment by Jayden58** [comment]
I am having this same issue. I updated to a newer version and I am still having it. I downloaded a video from the internet to make sure it was not my recording software.

EDIT:
Win10 22H2
Openshot 3.2.1

**Comment by Jayden58** [comment]
[openshot-qt.log](https://github.com/user-attachments/files/16418206/openshot-qt.log)
Followed the instructions the other person did. Deleted the log, then reproduced the issue.
[libopenshot.log](https://github.com/user-attachments/files/16418241/libopenshot.log)
