### ISSUE TITLE
Adding track below - repeatable crash and other issue

### ISSUE THREAD

**Issue by glogman** [OpenShot/openshot-qt#1618]
On Windows 10, with a new project, when adding a track before track 0, the software crashes.

When adding a track before track 1:
1) any customised named track loses its name. 
2) any transitions on the selected track are moved to the new track even though the images/movies stay with the original track.
3) even if the project was saved in a good state before attempting to add a track, after the software crash, a reopened project shows that the project was automatically saved after the "good state", thereby leading to annoying rework.

 - Operating System Windows 10 Home
 - OpenShot Version 2.4.1

Not sure where the logs are located.

**Comment by DylanC** [comment]
@glogman Can you try v2.4.2 and let us know if you have any success?
