### ISSUE TITLE
great to shit

### ISSUE THREAD

**Issue by zergneptune3579** [OpenShot/openshot-qt#1619]
open shot has been great but my most recent video never played when i hit play which made it difficult to cut and edit also when i was done and went to review the video would pause in the same spot every single fucking time it is getting to the point to were i dont wanna use the application any more and when i go to export it would always stop at 32% every single time and it would later say not responding and that was the first time to ever happen in all of my editing and i would open other projects and everything is fine and i know for a fact it is not my video cause i review my videos before i even bother editing so i just dont understand that why now is openshot acting like a piece of shit and not working properly cause i never had this problem before until today

**Comment by DylanC** [comment]
@zergneptune3579 - Please report issues in a polite manner. We can't help you if you post stuff like this. We need you to tell us the problem and provide details of the system you are running Openshot on. 

Thanks.
