### ISSUE TITLE
Project file format

### ISSUE THREAD

**Issue by kajho** [OpenShot/openshot-qt#162]
I have several project files made by the old version of OpenShot, and it seems that the file format is changed, so the new version cannot read the files at all. How can I read/import the old files
so that I can keep on working with them?

**Comment by jonoomph** [comment]
Tracking this issue here: https://github.com/OpenShot/openshot-qt/issues/85. If you get the latest version from www.openshot.org/download (and choose 'Other Downloads'), it should allow you to open the old project files. =)
