### ISSUE TITLE
Error Exporting video

### ISSUE THREAD

**Issue by johnsixfox** [OpenShot/openshot-qt#1622]
![error](https://user-images.githubusercontent.com/28743314/40630955-c16bf2d2-631a-11e8-86ed-3c690f9fb177.PNG)

I have a problem exporting video, someone help asap, please.

**Comment by peanutbutterandcrackers** [comment]
Perhaps the destination where you are exporting to A. does not have enough space or B. isn't write-able by you (permissions). Those are the only 2 things that come to my mind right now. And this is the first one of this kind of issue I have seen.

Please make sure the drive has enough space and you have the permission to write to it. Hope this helps!

**Comment by DylanC** [comment]
@johnsixfox Can you try v2.4.2 and let us know if you have any success?
