### ISSUE TITLE
Will Not Open Properly

### ISSUE THREAD

**Issue by MarbleMaestro** [OpenShot/openshot-qt#1624]
I was trying to open OpenShot after my computer crashed, but all I got was this error message:
![error](https://user-images.githubusercontent.com/39741769/40674981-04fb2e52-633c-11e8-93b2-04e869a402fa.PNG)
I clicked [OK] and it just closed. I have no idea what this message means. I uninstalled and reinstalled OpenShot completely, but nothing changed. I've been working on a project for nearly three hours, and now I think all of that work was for nothing.
I am using version 2.4.1 (64-Bit) on Windows 8.

**Comment by peanutbutterandcrackers** [comment]
Sorry for the inconvenience, good sir. This has been already reported and worked around. You just need to delete the .openshot_qt folder in your home folder and that should do the trick.

Also, I would recommend [switching to the latest daily build](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914), as it has got tons of new features and is a lot more stable. Or, you could also wait for v2.4.2 which should be out any day now.

Hope that helps! :)

**Comment by DylanC** [comment]
@MarbleMaestro Can you try v2.4.2 and let us know if you have any success?
