### ISSUE TITLE
size of split clip

### ISSUE THREAD

**Issue by bdfdrmn** [OpenShot/openshot-qt#1628]
Hard to understand why I start with a clip 120MB, split it down to about 20% of the original, and end up with 600MBs???

what am I doing wrong? 

thank you

**Comment by N3WWN** [comment]
What is the profile (resolution and frame rate) of the original clip that you are importing into OpenShot and what is the profile of your exported video?

**Comment by bdfdrmn** [comment]
hah...you know, I was just thinking about that in my little non techie mind. Ill check that out.  Thank you
    On Wednesday, May 30, 2018, 7:54:32 AM PDT, Richard Alloway <notifications@github.com> wrote:  
 
 
What is the profile (resolution and frame rate) of the original clip that you are importing into OpenShot and what is the profile of your exported video?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
   

|  | Virus-free. www.avast.com  |

**Comment by N3WWN** [comment]
Let me know what you find out.  I'd like to confirm that your export profile is at a higher resolution and/or frame rate than your original, which is the cause of the larger rendered version of the trimmed clip.

**Comment by bdfdrmn** [comment]
I will.....thank you.  Im having trouble trying to close that thread. 
    On Wednesday, May 30, 2018, 11:01:23 AM PDT, Richard Alloway <notifications@github.com> wrote:  
 
 
Let me know what you find out. I'd like to confirm that your export profile is at a higher resolution and/or frame rate than your original, which is the cause of the larger rendered version of the trimmed clip.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
   

|  | Virus-free. www.avast.com  |

**Comment by bdfdrmn** [comment]
Richard, how do I find the resolution?  this is from 'properties', attached. I see frame rate but dont know what to do with it. 



    On Wednesday, May 30, 2018, 7:54:32 AM PDT, Richard Alloway <notifications@github.com> wrote:  
 
 
What is the profile (resolution and frame rate) of the original clip that you are importing into OpenShot and what is the profile of your exported video?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
   

|  | Virus-free. www.avast.com  |

**Comment by bdfdrmn** [comment]
Richard....yes......I was exporting at high quality. I tried using low which looks fine, and it's 1/10th the size but still 49mbs. Im running it through again and exporting at low to see what happens. 
thank you
    On Wednesday, May 30, 2018, 11:01:23 AM PDT, Richard Alloway <notifications@github.com> wrote:  
 
 
Let me know what you find out. I'd like to confirm that your export profile is at a higher resolution and/or frame rate than your original, which is the cause of the larger rendered version of the trimmed clip.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
   

|  | Virus-free. www.avast.com  |

**Comment by bdfdrmn** [comment]
Hi, Richard........is there anyway to adjust colors in a video in GH?  I dont think so.  Do you know of a program that does that?
thanks
    On Wednesday, May 30, 2018, 11:01:23 AM PDT, Richard Alloway <notifications@github.com> wrote:  
 
 
Let me know what you find out. I'd like to confirm that your export profile is at a higher resolution and/or frame rate than your original, which is the cause of the larger rendered version of the trimmed clip.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
   

|  | Virus-free. www.avast.com  |

**Comment by peanutbutterandcrackers** [comment]
You could use the `color saturation` effect to make the color B&W (grey-scale). Also you could try out `Brightness & Contrast` to change the color. Also there's the new `Hue` effect in [the latest daily builds](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914) if you want to try that out. (You'll have to wait for v2.4.2 if you don't want to use the daily build.)

**Comment by bdfdrmn** [comment]
thank you.  Ill experiment!!
appreciate your help
    On Monday, June 4, 2018, 9:31:14 PM PDT, peanutbutterandcrackers <notifications@github.com> wrote:  
 
 
You could use the color saturation effect to make the color B&W (grey-scale). Also you could try out Brightness & Contrast to change the color. Also there's the new Hue effect in the latest daily builds if you want to try that out. (You'll have to wait for v2.4.2 if you don't want to use the daily build.)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
   

|  | Virus-free. www.avast.com  |
