### ISSUE TITLE
Title Speed after Export

### ISSUE THREAD

**Issue by AzraelTWC** [OpenShot/openshot-qt#1631]
I have titles as a way to do commentary on a video and in the preview they are time perfectly. After exporting everything is sped up and it can't be read in time. Is this an issue with my exporting at a higher fps than the preview. if so, how do i remedy this?

**Comment by N3WWN** [comment]
Any item that is keyframed will change position if/when the export frame rate is different than the project profile frame rate when the keyframes were set on the timeline.

If the preview is correct, then selecting `Export Video` and retaining the default selected profile (which is the project profile) should result in a rendered video which matches the preview.

**Comment by AzraelTWC** [comment]
Ah well theres my issue then, I never got an option to set a profile rate. This makes much more sense now. Thank you.

**Comment by N3WWN** [comment]
There is a default profile for new projects.  The current project profile is shown in the title bar of the main window within brackets.  When I create a new project, I see the following: `Untitled Project [HD 1080p 60 fps] - OpenShot Video Editor`

You can change this default profile in `Edit` -> `Preferences` -> `Profiles` -> `Default Profile`.

You can also change the current project profile with the filmstrip `Change Profile` icon or `File` -> `Choose Profile`, but, a word of warning, if you already have keyframed items on the timeline, those items will change if you select a profile with a different frame rate (this is the problem you originally encountered).

If you need to change the resolution of an existing project and there isn't a profile in the list which has the same frame rate as the existing project, you can create a [custom profile](https://www.openshot.org/static/files/user-guide/profiles.html#custom-profile) which has the exact same frame rate and your desired resolution.
