### ISSUE TITLE
Provide 32 bit download

### ISSUE THREAD

**Issue by qubodup** [OpenShot/openshot-qt#1632]
https://www.openshot.org/download/ offers Windows (64-bit Installer) to me.

There are nightly 32bit builds as it seams.

Why not offer both 64 and 32 bit downloads.

Note: 64bitter-s might want to dl the 32bit version (as preparation to be used on other computer) or vice versa.

Sorry if this was planned anyway and the next version simply happens to be the first to support 32bit windows

**Comment by ferdnyc** [comment]
> Sorry if this was planned anyway and the next version simply happens to be the first to support 32bit windows

No apologies necessary, but that is indeed the exact situation. The forthcoming release (OpenShot 2.4.2) will be the first _in quite some time_ to offer 32-bit support, previous versions (including the current 2.4.1 release) were 64-bit only.

Still, this is a good reminder that, once 2.4.2 is released, the download page should offer both versions for downloading, even if (by default) a particular build is selected to match the user's architecture.

**Comment by DylanC** [comment]
Closing this but leaving #1671 open to track instead.
