### ISSUE TITLE
Video Not inserting

### ISSUE THREAD

**Issue by SAF56** [OpenShot/openshot-qt#1633]
**Describe the bug**
When I try insert a video it says is not a valid video 
**System Details (please complete the following information):**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**To Reproduce**

**Expected behavior**
I expected my videos to insert and i could start to work on them.

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**

**Comment by SAF56** [comment]
I dont know what to do

**Comment by N3WWN** [comment]
What type of video are you trying to add?  .mp4?  .mov?  .avi?

**Comment by sspmrsomebody1** [comment]
> System Details (please complete the following information):
>
>Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
OpenShot Version [e.g. 2.4.1]
To Reproduce
Steps to reproduce the behavior:
>
>Go to '...'
Click on '....'
Scroll down to '....'
See error

You didn't fill out all the steps and stuff. If you want the problem to be fixed you need to do that.

>What type of video are you trying to add? .mp4? .mov? .avi?

This is a good start.

**Comment by DylanC** [comment]
@SAF56  Can you try v2.4.2 and let us know if you have any success?
