### ISSUE TITLE
Launch.exe crash when Previewing and Exporting Video With Fade Transitions

### ISSUE THREAD

**Issue by Kolrolf** [OpenShot/openshot-qt#1635]
I'm having an issue where OpenShot will crash if I have overlapping fade transitions in separate tracks and attempt to export the video. If the transitions start at different times then everything is fine until the second fade starts and then OpenShot crashes (error message "launch.exe has stopped working").

Possibly related issue: if I insert a fade transition with a duration of 0.6 seconds I get the same crash when previewing and when exporting the video. Longer fade transitions do not cause the crash and I have not tested to see what length of fade does not cause the crash.  Somewhere between 0.6 second and 4 seconds though.

Both of these issues do NOT occur with OpenShot Version 2.4.1.
I have tried the trick of deleting the .openshot_qt folder, but this did not fix the issue.

System Details
 - Operating System: Windows 10
 - OpenShot Version 2.4.2-rc1 and daily builds since 2.4.1

Trying to Export to:
 Target - MP4 (h.264)
 Video Profile - HD 1080p 60fps
 Quality - High

**Comment by peanutbutterandcrackers** [comment]
I have informed the devs about this. Could you please tell us what kind of video you are editing? I will try to reproduce this issue on my buddy's windows 10 computer and see if I can shed some light into this situation.

**Comment by Kolrolf** [comment]
The video portion as saved as an .avi, captured using OBS 21.1.0 and the audio is a .wav

**Comment by peanutbutterandcrackers** [comment]
Can you also please [attach the logs](https://github.com/OpenShot/openshot-qt/blob/develop/CONTRIBUTING.md) so that the devs can fully understand the problem? Thank you!

**Comment by jonoomph** [comment]
Can you please upload a simple example OSP project file, and a the test files you are using... the smallest and simplest possible to reproduce the issue. That would definitely help us! Thx

**Comment by jonoomph** [comment]
I was able to reproduce this bug! Nice! Now I just gotta fix it, haha

**Comment by Kolrolf** [comment]
I noticed another daily build was up (v2.4.1-143) and checked it out.  Looks like you squashed the bug! Great job!

**Comment by peanutbutterandcrackers** [comment]
Awesome! I'm glad things worked out! Hope you create awesome videos with OpenShot, good sir!
