### ISSUE TITLE
Laggy & slow interface on AMD cpu and gpu

### ISSUE THREAD

**Issue by yvz5** [OpenShot/openshot-qt#1638]
**Laggy & slow interface on AMD cpu and gpu**
I have a ryzen 7 (8 cores & 16 threads) and 8gb gpu with 16 gb ram. This beast handles any recent game with full settings without any stutter but open shot lags so hard that its impossible to use it.

**System Details (please complete the following information):**
 - Windows 10
 - OpenShot Version 2.4.1

**To Reproduce**
1. Find a ryzen 7 pc
2. just do some editing
3. punch your monitor
4. profit

**Comment by peanutbutterandcrackers** [comment]
v2.4.1 is known to be not-so-well on windows platforms. I suggest that you [switch to the latest daily builds](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914) - they're known to be a lot more stable. v2.4.2 will be out soon and we have release candidate 1 out now. Perhaps you could test it and report us any bugs/issues that you can find, good sir? :)

Sorry for the inconvenience and thank you for your patience. Hope that helps!

**Comment by yvz5** [comment]
v2.4.2 is usable. thanks for the tip

**Comment by peanutbutterandcrackers** [comment]
@yvz5 - Yay! Glad it is working for you. It is still the release candidate so it might still have quite a bit of rooms for improvement though. But please do keep on loving and supporting OpenShot. It will only get better - with our help. :)
