### ISSUE TITLE
crash on file export

### ISSUE THREAD

**Issue by sentient** [OpenShot/openshot-qt#1639]
Ubuntu 18.04 (LTS)

Crash when trying to export the project

Full stack trace below. I hope somebody finds it useful

preview_thread:INFO self.player.Position(): 1
timeline_webview:INFO UpdateLayerIndex
 main_window:INFO updateStatusChanged
 main_window:INFO updateStatusChanged
 files_model:INFO updating files model.
timeline_webview:INFO UpdateLayerIndex
properties_model:INFO Update item: 
properties_model:INFO updating clip properties model.
 main_window:INFO Loaded project /home/marco/Documents/memorial-day-2018.osp
     ui_util:INFO Initializing UI for Dialog
      export:INFO (4, 'Mono (1 Channel)')
      export:INFO (3, 'Stereo (2 Channel)')
      export:INFO (7, 'Surround (3 Channel)')
      export:INFO (1551, 'Surround (5.1 Channel)')
      export:INFO (1599, 'Surround (7.1 Channel)')
      export:INFO /usr/lib/python3/dist-packages/openshot_qt/profiles/square_pal_wide
      export:INFO AVI (h.264)
      export:INFO updateChannels
      export:INFO /usr/lib/python3/dist-packages/openshot_qt/profiles/square_pal_wide
      export:INFO /usr/lib/python3/dist-packages/openshot_qt/profiles/atsc_1080i_60
      export:INFO /usr/lib/python3/dist-packages/openshot_qt/profiles/atsc_1080i_60
      export:INFO Low
      export:INFO None
      export:INFO MP4 (h.264)
      export:INFO None
      export:INFO /usr/lib/python3/dist-packages/openshot_qt/profiles/square_pal_wide
      export:INFO /usr/lib/python3/dist-packages/openshot_qt/profiles/square_pal_wide
      export:INFO /usr/lib/python3/dist-packages/openshot_qt/profiles/atsc_1080i_60
      export:INFO /usr/lib/python3/dist-packages/openshot_qt/profiles/atsc_1080i_60
      export:INFO Low
      export:INFO High
      export:INFO Valid framerate detected, sending to libopenshot: 30.0
      export:INFO /home/marco/Documents/Memorial day 2018-t1.mp4
[libx264 @ 0x33c8020] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 AVX512
[libx264 @ 0x33c8020] profile High, level 4.1
[libx264 @ 0x33c8020] 264 - core 152 r2854 e9a5903 - H.264/MPEG-4 AVC codec - Copyleft 2003-2017 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=16 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=2 keyint=12 keyint_min=1 scenecut=40 intra_refresh=0 rc_lookahead=12 rc=abr mbtree=1 bitrate=15000 ratetol=1.0 qcomp=0.60 qpmin=2 qpmax=30 qpstep=4 ip_ratio=1.40 aq=1:1.00
[mp4 @ 0x33c75c0] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[mp4 @ 0x33c75c0] Using AVStream.codec.time_base as a timebase hint to the muxer is deprecated. Set AVStream.time_base instead.
[mp4 @ 0x33c75c0] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
Caught signal 11 (SIGSEGV)
---- Unhandled Exception: Stack Trace ----
  /usr/lib/python3/dist-packages/_openshot.cpython-36m-x86_64-linux-gnu.so (                                           + 0xcfbee)  [0x7f4a48e09bee]
  /usr/lib/python3/dist-packages/_openshot.cpython-36m-x86_64-linux-gnu.so (                                           + 0xd0154)  [0x7f4a48e0a154]
  /usr/bin/python3               ( PyCFunction_Call                          + 0xbd  )  [0x4c517d]
  /usr/bin/python3               ( _PyEval_EvalFrameDefault                  + 0x6bc0)  [0x557c60]
  /usr/bin/python3               (                                                   )  [0x54fbe1]
  /usr/bin/python3               (                                                   )  [0x54fe6d]
  /usr/bin/python3               ( _PyEval_EvalFrameDefault                  + 0x362f)  [0x5546cf]
  /usr/bin/python3               (                                                   )  [0x54fbe1]
  /usr/bin/python3               ( _PyFunction_FastCallDict                  + 0x1c9 )  [0x558e19]
  /usr/bin/python3               ( _PyObject_Call_Prepend                    + 0x231 )  [0x45a461]
  /usr/bin/python3               ( PyObject_Call                             + 0x3e  )  [0x459eee]
  /usr/lib/python3/dist-packages/PyQt5/QtCore.cpython-36m-x86_64-linux-gnu.so (                                           + 0x1efc30)  [0x7f4a56b68c30]
  /usr/lib/python3/dist-packages/PyQt5/QtCore.cpython-36m-x86_64-linux-gnu.so (                                           + 0x1f0108)  [0x7f4a56b69108]
  /usr/lib/python3/dist-packages/PyQt5/QtCore.cpython-36m-x86_64-linux-gnu.so (                                           + 0x1f0390)  [0x7f4a56b69390]
  /usr/lib/python3/dist-packages/PyQt5/QtCore.cpython-36m-x86_64-linux-gnu.so (                                           + 0x1f0d07)  [0x7f4a56b69d07]
  /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 ( QMetaObject::activate(QObject*, int, int, void**)  + 0x929 )  [0x7f4a5c315679]
  /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 (                                           + 0x2e6660)  [0x7f4a5d1f6660]
  /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 ( QMetaObject::activate(QObject*, int, int, void**)  + 0x865 )  [0x7f4a5c3155b5]
  /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 ( QAbstractButton::clicked(bool)            + 0x42  )  [0x7f4a5d155b82]
  /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 (                                           + 0x245d9a)  [0x7f4a5d155d9a]
  /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 (                                           + 0x24717a)  [0x7f4a5d15717a]
  /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 ( QAbstractButton::mouseReleaseEvent(QMouseEvent*)  + 0xfd  )  [0x7f4a5d15736d]
  /usr/lib/python3/dist-packages/PyQt5/QtWidgets.cpython-36m-x86_64-linux-gnu.so (                                           + 0x3599a3)  [0x7f4a5dab09a3]
  /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 ( QWidget::event(QEvent*)                   + 0x1f8 )  [0x7f4a5d0a3038]
  /usr/lib/python3/dist-packages/PyQt5/QtWidgets.cpython-36m-x86_64-linux-gnu.so (                                           + 0x35af93)  [0x7f4a5dab1f93]
  /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 ( QApplicationPrivate::notify_helper(QObject*, QEvent*)  + 0x9c  )  [0x7f4a5d06482c]
  /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 ( QApplication::notify(QObject*, QEvent*)   + 0x7ff )  [0x7f4a5d06c64f]
  /usr/lib/python3/dist-packages/PyQt5/QtWidgets.cpython-36m-x86_64-linux-gnu.so (                                           + 0x3ab97e)  [0x7f4a5db0297e]
  /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 ( QCoreApplication::notifyInternal2(QObject*, QEvent*)  + 0x118 )  [0x7f4a5c2e69a8]
  /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 ( QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool)  + 0x1d2 )  [0x7f4a5d06b622]
  /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 (                                           + 0x1ae14b)  [0x7f4a5d0be14b]
  /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 (                                           + 0x1b07ba)  [0x7f4a5d0c07ba]
  /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 ( QApplicationPrivate::notify_helper(QObject*, QEvent*)  + 0x9c  )  [0x7f4a5d06482c]
  /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 ( QApplication::notify(QObject*, QEvent*)   + 0x2a4 )  [0x7f4a5d06c0f4]
  /usr/lib/python3/dist-packages/PyQt5/QtWidgets.cpython-36m-x86_64-linux-gnu.so (                                           + 0x3ab97e)  [0x7f4a5db0297e]
  /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 ( QCoreApplication::notifyInternal2(QObject*, QEvent*)  + 0x118 )  [0x7f4a5c2e69a8]
  /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5 ( QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*)  + 0x6f3 )  [0x7f4a5c8a8523]
  /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5 ( QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*)  + 0x135 )  [0x7f4a5c8a9ff5]
  /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5 ( QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>)  + 0xab  )  [0x7f4a5c8812eb]
  /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5 (                                           + 0x9d1c0)  [0x7f4a376e51c0]
  /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 ( g_main_context_dispatch                   + 0x2e7 )  [0x7f4a5a627287]
  /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (                                           + 0x4c4c0)  [0x7f4a5a6274c0]
  /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 ( g_main_context_iteration                  + 0x2c  )  [0x7f4a5a62754c]
  /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 ( QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>)  + 0x5f  )  [0x7f4a5c33f8ef]
  /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 ( QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>)  + 0x13a )  [0x7f4a5c2e49ea]
  /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 ( QDialog::exec()                           + 0x207 )  [0x7f4a5d24eec7]
  /usr/lib/python3/dist-packages/PyQt5/QtWidgets.cpython-36m-x86_64-linux-gnu.so (                                           + 0x38df77)  [0x7f4a5dae4f77]
  /usr/bin/python3               ( _PyCFunction_FastCallKeywords             + 0x19d )  [0x4c53cd]
  /usr/bin/python3               (                                                   )  [0x54ffe4]
  /usr/bin/python3               ( _PyEval_EvalFrameDefault                  + 0x362f)  [0x5546cf]
  /usr/bin/python3               (                                                   )  [0x54f0e8]
  /usr/bin/python3               ( _PyFunction_FastCallDict                  + 0x2a2 )  [0x558ef2]
  /usr/bin/python3               ( _PyObject_Call_Prepend                    + 0x231 )  [0x45a461]
  /usr/bin/python3               ( PyObject_Call                             + 0x3e  )  [0x459eee]
  /usr/lib/python3/dist-packages/PyQt5/QtCore.cpython-36m-x86_64-linux-gnu.so (                                           + 0x1efc30)  [0x7f4a56b68c30]
  /usr/lib/python3/dist-packages/PyQt5/QtCore.cpython-36m-x86_64-linux-gnu.so (                                           + 0x1f0108)  [0x7f4a56b69108]
  /usr/lib/python3/dist-packages/PyQt5/QtCore.cpython-36m-x86_64-linux-gnu.so (                                           + 0x1f0390)  [0x7f4a56b69390]
  /usr/lib/python3/dist-packages/PyQt5/QtCore.cpython-36m-x86_64-linux-gnu.so (                                           + 0x1f0d07)  [0x7f4a56b69d07]
  /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 ( QMetaObject::activate(QObject*, int, int, void**)  + 0x929 )  [0x7f4a5c315679]
  /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 ( QAction::triggered(bool)                  + 0x42  )  [0x7f4a5d05e122]
---- End of Stack Trace ----

**Comment by peanutbutterandcrackers** [comment]
Are you using the version of openshot available in the official repos? Which profile were you exporting to?

You could wait for some more time for v2.4.2 which will have a lot more improvements. Or, you could [switch to the latest daily PPA](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914) and see if that'll work for you. Hope that helps!

**Comment by DylanC** [comment]
@sentient Can you try v2.4.2 and let us know if you have any success?
