### ISSUE TITLE
Video rotation attribute is ignored during import

### ISSUE THREAD

**Issue by haspok** [OpenShot/openshot-qt#164]
When importing an .mp4 video clip with a rotation attribute of 90 degrees (recorded by a mobile phone in portrait mode), it is reset to 0 - the video is turned on its side. I can view the same video in VLC correctly.

If I manually set the rotation to 90, the top and bottom are cropped - I cannot easily "zoom out" to see the whole picture.

**Comment by DylanC** [comment]
@haspok - What version of OpenShot are you using?

**Comment by DylanC** [comment]
Closing since no version has been provided. Feel free to update this later.
