### ISSUE TITLE
Have software use graphics cards

### ISSUE THREAD

**Issue by BigChubs** [OpenShot/openshot-qt#1641]
I notice this software doesn't use the GPU in my desktop computer. I believe having the software use graphics card as part the load. Would help with the software freezing up and etc. Plus graphics card helps with rendering everything anyways.

**Comment by DylanC** [comment]
Dup of #527

**Comment by ferdnyc** [comment]
I'm actually not sure if this is about video encoding or animated title rendering (which use completely different technologies).

But either way...
* Hardware video encoding is now implemented in the development code, and I expect will be in the next release. (At least for Linux, not sure if Win/Mac are sorted out yet.)
* Blender GPU rendering has a WIP implementation in #2825, and mostly just needs testing. (But I think many people will actually be surprised by just how much it DOESN'T speed up their renders, unless they have a $1000 GPU.)

So, either way, closing this as "in development / upcoming", and as a dup of the open master issues on these requests. (That's #2812 for Blender GPU rendering, possibly #527 for hardware encode.)
