### ISSUE TITLE
can't get to add a new animated title

### ISSUE THREAD

**Issue by LuisBL** [OpenShot/openshot-qt#1642]
**Describe the bug**
I can't make openshot take into account a new nor a modified python script for animated title

**System Details (please complete the following information):**
 - Operating System / Distro: ubuntu 18.04
 - OpenShot Version 2.4.1

**To Reproduce**
Steps to reproduce the behaviour:
1. modify something in python script:
  e.g `/usr/lib/python3/dist-packages/openshot_qt/blender/scripts/spacemovie_intro.py`
2. restart openshot
3. Go to Animated title
4. Modification made in the python script e.g. "default text" does not appear.

**Expected behaviour**
to see a new choice in new_title windows or at least see modifications made on spacemovie_intro.py

**Comment by peanutbutterandcrackers** [comment]
Good sir, perhaps you should put the modified python script in `~/.openshot_qt/blender` under a directory `scripts` (that I think you'll have to create) and perhaps it will show up? Maybe it's just a permission issue or something? I hope that helps!

[ I will try to ask around to make sure that this will indeed fix things. If I get any new info, I will update you, too. :) ]

**Comment by peanutbutterandcrackers** [comment]
@DylanC - Any ideas, Cap'ain?

**Comment by gary9872** [comment]
Try modifying this.

/usr/lib/python3.6/site-packages/openshot_qt-2.4.1.dev1-py3.6.egg/openshot_qt/blender/scripts/spacemovie_intro.py

(or something similar in an egg info dir)

**Comment by LuisBL** [comment]
Hello @gary9872  on ubunut the `/usr/lib/python3.6/site-packages/` is `dist-packages` that why I modified:
 `/usr/lib/python3/dist-packages/openshot_qt/blender/scripts/spacemovie_intro.py`
but with no success
;(

**Comment by peanutbutterandcrackers** [comment]
On a side note, @gary9872, you probably would want to [take a look at this](https://github.com/OpenShot/libopenshot/pull/85), good sir!

**Comment by DylanC** [comment]
@LuisBL Can you try v2.4.2 and let us know if you have any success?
