### ISSUE TITLE
CANNOT IMPORT FILES FOR EDITING

### ISSUE THREAD

**Issue by Desert33** [OpenShot/openshot-qt#1644]
**Describe the bug**

**System Details (please complete the following information):**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**

**Comment by DylanC** [comment]
@Desert33 - So what happens when you try to import? What system are you using? OS etc?

**Comment by Desert33** [comment]
Only abut 18 seconds of 10 minute video is downloaded, not the entire video.
I'm using Windows 10.

**Comment by Desert33** [comment]
Some additional background.
I made the DVD from a VHS tape.
The DVD works OK on all the players.
The DVD is badly in need of editing.
DVD Directory
VIDEO_TS.BUP
VIDEO_TS.IFO
VIDEO_TS.VOB
VTS_O1_0.BUP
VTS_01_BUP
VTS_01_01.IFO
VTS.01_1.VOB
VTS_01_2.VOB
VTS_01_3.VOB
The only file that can be edited are the VOB files and
the are not completely loading.
Hope this helps.

**Comment by peanutbutterandcrackers** [comment]
Good sir, I suggest you [use the latest daily build](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914) instead of v2.4.1. v2.4.1 is known to have a lot of issues, esp. with windows. But the latest daily builds are a lot more stable. Or, you could wait for v2.4.2 which should be out within a week or two now. Hope that helps!

**Comment by gary9872** [comment]
If you are using Linux, install mplayer

and do the command 

mplayer dvd://1 -dumpstream 

It will create a stream.dump file which will pull all the vobs together that are part of title1. You should be able to import that into openshot.

You should be able to do that for each title on the DVD. Just rember to rename stream.dump to something else after each run or it will erase your previous title.

Cheers,

Gary

**Comment by gary9872** [comment]
You shouldn't be editing from a raw DVD structure. I can see nothing good coming from this. 

You should use a program such as Handbrake that will take all the files and put them into a single file for each title.

**Comment by peanutbutterandcrackers** [comment]
lol. I just realized I wrote that reply without reading the problem properly first. I have got to stop thinking about the daily builds every time I see an issue.

What Mr. @gary9872 has said is true. Please use [HandBrake](https://handbrake.fr/) to rip the DVD into a proper media format (maybe an `.mkv` or an `.mp4`, even). You should be able to edit those using OpenShot. [Please do switch to the daily builds, too - they're a lot more robust.] Hope that helps!

**Comment by DylanC** [comment]
Closing since I consider this issue to be answered.
