### ISSUE TITLE
No sound with video playback

### ISSUE THREAD

**Issue by RickVickers** [OpenShot/openshot-qt#1645]
First time using OpenShot.  exported product but there is no sound with video playback.  do I need to do something to combine the tracks (only 2- one audio and one video) before exporting or does that happen automatically?

**Comment by BarryBlake** [comment]
I'm having the exact same problem Rick.  Can someone please advise us what we need to do to get audio on our recorded playback.  I have audio in the video preview, so why does that not export like the image does?

**Comment by peanutbutterandcrackers** [comment]
No you do not need to do anything. I think the problem is the media player. I think the media player that you are using is unable to decode the audio stream from videos exported from OpenShot. I suggest you give [VLC](https://www.videolan.org/vlc/index.html) a try. It is probably the greatest media player out there.

**Comment by BarryBlake** [comment]
Okay I fixed the problem myself.  For anyone else with the problem, here's what solved it for me...
In the box you get after you hit the red button to Save your work, click the TARGET dropdown and choose MP4 (mpeg4).  If you then click the ADVANCED tab and click AUDIO SETTINGS, you’ll see the Audio Codec has changed to libmp3lame.
Fecked if I know what that is, but this is the setting that solved the no audio problem for me.

**Comment by peanutbutterandcrackers** [comment]
Yes, so the default audio encoding was not being decoded by the media player. Using VLC, too, will help - with any of the exported profiles.

I'm glad you were able to fix it, good sir! Hope you create amazing videos using OpenShot! :+1:

**Comment by BarryBlake** [comment]
Great - thanks for coming back with your advice.  BTW - I think OpenShot is totally amazing and so simple to use compared to the one that used to come with YouTube.  Very intuitive!

**Comment by peanutbutterandcrackers** [comment]
@BarryBlake - Thank you for your kind words, too, good sir! Please do remember that this is an Open Source project backed by the community. And there will be issues. But should you encounter a bug or any other issues, please do look around. We are all scratching each other's back and are more than willing to help each other out. I am glad that you like the program. So do I! It is my favourite video editor, ever! :)
