### ISSUE TITLE
OpenShot cannot open .kdenlive project

### ISSUE THREAD

**Issue by LissieTilbrook** [OpenShot/openshot-qt#1647]
**Describe the bug**
According to this blog post from **2010**, https://www.openshot.org/blog/2010/03/06/import-kdenlive-and-kino-projects/ Openshot can open .kdenlive projects.

My question is... ***HOW???*** I am unable to do so!

I tried opening it. Not showing in file chooser. Renamed the .kdenlive file to an .osp file. Error:

![screenshot at 2018-06-04 00-39-08](https://user-images.githubusercontent.com/32066229/40900123-b87d2474-678f-11e8-9fa4-aaacebf3523f.png)

So... is this deprecated? No matter what I do, or where I find info on the Internet, the bottom line is...

I cannot open Kdenlive project files whatsoever!!!!
===================

**System Details (please complete the following information):**
 - Operating System / Distro: AlexaTilbrook.org Linux 18.04 "DollHouse" (customized Ubuntu MATE 18.04)
 - OpenShot Version 2.4.1

**To Reproduce**
0. Rename a .kdenlive project file to .osp
1. Go to ''open project"
2. double-click on the renamed Kdenlive project file
3. Pray
4. See error (screenshot of error above)

**Expected behavior**
Kdenlive project imported.

**Screenshots**
*(above)*

**Additional context**
The blog post, from 2010, https://www.openshot.org/blog/2010/03/06/import-kdenlive-and-kino-projects/, seemed promising. Now it's 2018... and no possible help. The documentation has no results for "kdenlive" whatsoever.

Kdenlive was getting slow on me. I thought Openshot would help, and when I found out that OpenShot would import Kdenlive files... but to my chagrin, it does not.

**Comment by DylanC** [comment]
@LissieTilbrook - I can consult with the other devs but I would imagine we don't have support for this in the latest version. The blog post mentioned MLT in 2010 and I don't think we use MLT really anymore.

**Comment by peanutbutterandcrackers** [comment]
I don't think OpenShot supports **import** of `.kdenlive` files, yet. I did make [an enhancement request](https://github.com/OpenShot/openshot-qt/issues/1230) a few months back regarding the same thing.

However, regarding **opening** of `.kdenlive` files, I highly doubt it. kdenlive and OpenShot are two separate projects and opening kdenlive files to edit in OpenShot - I don't think that will be possible as they are currently based on two completely different media frameworks.

However, if you want to use your kdenlive-edited footages in OpenShot, I suggest you export (probably export lossless or something similar) the project from kdenlive and import the resulting video into OpenShot.

Hope that helps!
