### ISSUE TITLE
Adding to Timeline

### ISSUE THREAD

**Issue by Aleksejczyk** [OpenShot/openshot-qt#1649]
Adding Images to Timeline

System stops responding when I try to add images to the timeline.  Whether I'm adding 6 or 100 into a track it comes back with "System Not Responding".  Please advise on how to fix.

Thank you.

**Comment by peanutbutterandcrackers** [comment]
I suggest that you try [using the daily builds](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914) as it is known to be a lot more stable. Or, you could also wait for v2.4.2 which should be out in about a week or two. Hope that helps!

**Comment by DylanC** [comment]
@Aleksejczyk Can you try v2.4.2 and let us know if you have any success?
