### ISSUE TITLE
Video Preview playback not smooth

### ISSUE THREAD

**Issue by ovari** [OpenShot/openshot-qt#165]
This may relate to #116.

Unfortunately, OpenShot's Video Preview does not play videos smoothly with:
Windows 8.1 using [OpenShot-v2.0.7-15-g3b4ceff-47-531-x86_32.msi (April 19, 2016, 4:44 p.m.)](http://releases.openshot.org/windows/OpenShot-v2.0.7-15-g3b4ceff-47-531-x86_32.msi); and
Linux Mint 17.3 using [OpenShot-v2.0.7-15-g3b4ceff-47-531-x86_64.AppImage (April 19, 2016, 4:02 p.m.)](http://releases.openshot.org/linux/OpenShot-v2.0.7-15-g3b4ceff-47-531-x86_64.AppImage).

Interestingly, the videos play smoothly using [VLC media player](https://www.videolan.org/).

Thank you

**Comment by singpolyma** [comment]
I also have this issue.  Running version `2.0.7+0+615+100+201603300516~ubuntu14.04.1` installed from official PPA.  Old openshot (from official repos) and vlc play the videos just fine, but latest openshot preview lags unusably and uses more that 100% CPU while playing preview.

**Comment by singpolyma** [comment]
This might be related to #29 ? Hard to say.  Changing the size of my preview window does not seem to help much (my inputs are 720p)

**Comment by singpolyma** [comment]
Related to #95

**Comment by msourada** [comment]
Same issue here. Tried 2.0.7 on CentOS 7 (AppImage). Even on NTSC/DVD clips (project is set to same resolution/fps). The 1.4.3 version (from repos) works smooth without any issues... Any info I can provide to help debug the issue?

**Comment by jreynojustin** [comment]
OpenShot is now in Version 2.2 if you are still noticing issues in the latest version please re-open this issue letting us know.
