### ISSUE TITLE
incorrect video on export

### ISSUE THREAD

**Issue by nickg001** [OpenShot/openshot-qt#1650]
I did a short video with a fade in and out of sequence. I exported it in: MP4 (H.264). When I play the video half of the video is black but I have the sound. If I do not fade, the video is displayed correctly.

 - Operating System / 64bits Linux mageia6]
 - OpenShot Version [. 2.4.1]

1. select the video sequence
2. right click> fade> full clip> fade in and out (slow)
3. file>video export  option : mp4 h.264

**Comment by peanutbutterandcrackers** [comment]
First and foremost, it might be that you are using different FPS-es. The video should be edited using a profile that uses the same FPS as the original video. For eg: If the video is 24fps but you edit it at 30fps, problems like these might arise. You can use [MediaInfo](http://mediaarea.net/MediaInfo) to check the info about your original footage.

Secondly, I would recommend that you [switch to the latest daily builds](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914). That daily builds are known to be far more stable than v2.4.1.

Hope that helps!

**Comment by nickg001** [comment]
thanks
