### ISSUE TITLE
Same bugs and now the program closes alone when i strart exporting a video

### ISSUE THREAD

**Issue by swwe** [OpenShot/openshot-qt#1652]
Well the same bugs of always are still there, it does not matters how much dayly updates i install they are not fixed, but now i cant export my videos... when i click export and it begins to export the program just closes, not even shows me the "the program does not respond" window, it just close like it were normal, can somebody help me please? thanks

**Comment by peanutbutterandcrackers** [comment]
Sorry for the inconvenience. Could you please try out the latest daily build 'OpenShot-v2.4.2-rc1-x86_64.exe' and attach the logs in case of crash? That will really help us help you, and to also fix the issue. Also, you will have to provide us with your system details. What platform (Operating System) are you using, what are the specs (CPU, RAM etc.) of your computer.

**Comment by swwe** [comment]
Hi, i had install that daily build and the problem still there, i supose that with "logs" you mean images, on that case i think that there is no image to attach, because the program does not do anything in particular, it simply closes 5 seconds after y click "export", without showing me any crash window or something (if you mean something else with "logs" tell us, and if you like i can record a video showing this problem, but it really does not do anything on particular)

System details:
Windows 10 home 64 bits
Intel core I7 6700 3.40 hz
16 gb RAM

Thanks

**Comment by peanutbutterandcrackers** [comment]
By logs I mean the text file where the program dumps all the information about what it is doing. [Please follow these instructions](https://github.com/OpenShot/openshot-qt/blob/develop/CONTRIBUTING.md) to attach the logs. That will help us help you. Thanks!

**Comment by swwe** [comment]
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/2077446/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2077447/openshot-qt.log)

Here they are

**Comment by DylanC** [comment]
@swwe Can you try v2.4.2 and let us know if you have any success?
