### ISSUE TITLE
Old Movie Effect

### ISSUE THREAD

**Issue by Teva05000** [OpenShot/openshot-qt#1653]
Hi Guys,

I saw in some tutorials that there was an "Old Movie" effect in one of the past versions of OpenShot. I can't find it anymore in my 2.4.1 version. Is there a way to add it or to activate it?

Many thanks,

**Comment by peanutbutterandcrackers** [comment]
Hey there!

So, OpenShot 1.x series was based on another multimedia framework (MLT). And 2.x series is based on a completely new, written-from-scratch framework (libopenshot). And there are a lot of audio and video effects that need to be ported from 1.x series to 2.x one. It is on [the to-do list](https://www.openshot.org/blog/2018/01/01/happy-new-year-2018/). Also, v2.4.2 will be dropping soon. And it's going to have a ton of new video effects (but not the 'old movie' one, yet; sorry).

We'll put the "Old Movie" effect on priority, though.

Hope you keep on loving and supporting OpenShot! :)

**Comment by Teva05000** [comment]
Awesome, thanks peanutbutterandcrackers for your quick answer and thanks for all the work you put in OpenShot!!

**Comment by peanutbutterandcrackers** [comment]
Thank you for the kind words, good sir! Please do keep on loving an supporting OpenShot! :)
