### ISSUE TITLE
Won

### ISSUE THREAD

**Issue by ghost** [OpenShot/openshot-qt#1654]
**Describe the bug**

**System Details (please complete the following information):**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**

**Comment by peanutbutterandcrackers** [comment]
I see that you opened #1655, but you did forget to fill out all the necessary informations for us, good sir.
