### ISSUE TITLE
Won't show screen. pls help

### ISSUE THREAD

**Issue by ghost** [OpenShot/openshot-qt#1655]
The screen won't show what I'm making and is blank lol. Please fix this asap

**Comment by peanutbutterandcrackers** [comment]
Please provide us with some more information. Like which version you are using, details about your computer and operating system. What can you see. Perhaps some screenshots. That will help us understand and help you.

However, I would suggest uninstalling the current version of OpenShot and [installing a latest daily build](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914). That might solve whatever problem that you might be having - as it does for almost 80% of all the issues reported here.
