### ISSUE TITLE
Audio Volume Error

### ISSUE THREAD

**Issue by MisterTeeXD** [OpenShot/openshot-qt#1656]
**Describe the bug**
When a video clip is placed ontop of a audio clip and the volume is lower for a selected Video clip, both the Audio Track and Video Clip Volume will be lowered instead of one selected Part of the Clip/Track

**System Details (please complete the following information):**
 - Operating System / Distro: Windows 10
 - OpenShot Version 2.4.2-rc1

**To Reproduce**
1. Go to the video clip and cut a part out and drag the audio clip below the video clip
2. Click on the selected video clip with the audio track unselected
3. Scroll down in the properties window to Volume
4. See error by playing both the video clip and audio track

**Expected behavior**
Only the selected part of the video clip or audio track will have the volume lowered

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**
A strange out of order fix for this is move the audio track in between 2 video clips on the same track as the 2 video clips, then move the part of the splitted video clip on the track where the audio track was (meaning below the 2 video clips) and then only one part of the video clip will have the volume lowered and the audio track will have the volume set to normal (See screenshot for this fix)
![screenshot 41](https://user-images.githubusercontent.com/37266538/41030413-97e92bc2-697e-11e8-903d-fc8e24da26b1.png)

**Comment by MrTertius** [comment]
Also, may i point out that when a audio track is placed under the video track and then you change the volume of the music track, it will not be lowered but it will be lowered if the music track was placed above the video track as this problem was in the other daily builds as well

**Comment by peanutbutterandcrackers** [comment]
@DylanC - Cap'ain, any thoughts?

@MrTertius - I am sorry but I can not still understand the problem fully. Could you please make a recording describing this bug? Screen capture? I see that [VLC can be used to do so](https://www.youtube.com/watch?v=w7KW3PtUWJc). Sorry for causing you trouble. But then again, perhaps @DylanC can see this and test it out. :)

**Comment by MrTertius** [comment]
I am sorry for the confusing, apparently Openshot is different from other Video Editors i have used, apparently i have to put a audio file one track above the video clip, for example, my video clip is on track 4, then i put my audio file on track 5 and then the volume is lowered, did i explain it correctly?

**Comment by peanutbutterandcrackers** [comment]
No, sir. It is not that way. Audio files are supposed to go on the lower tracks. Strange... I have always put audio tracker *under* the video tracks...

P. S: If it is possible, I would really like to see a screen-capture of this problem.

**Comment by MrTertius** [comment]
Then that is a problem, When i put a audio file one track below the video file, then the volume will not be lowered if i lower it, this is a problem that needs fixing

**Comment by peanutbutterandcrackers** [comment]
@MrTertius - How are you lowering the volume, good sir? I just tried changing the volume using keyframes and was perfectly able to do so. And I was able to change it from the drop-down menu too.

Perhaps you'd want to read [this guide](https://gist.github.com/peanutbutterandcrackers/f0f666243133e0ed25abbc12a4ba23d7) to learn all about keyframes in OpenShot?

Hope that helps!

**Comment by DylanC** [comment]
@MisterTeeXD Can you try v2.4.2 and let us know if you have any success?
