### ISSUE TITLE
Too Much Memory Usage

### ISSUE THREAD

**Issue by ghost** [OpenShot/openshot-qt#1657]
**Describe the bug**
Openshot Uses Too Much Memory

**System Details (please complete the following information):**
 - Operating System / Distro: Windows 10
 - OpenShot Version 2.4.2-rc1

**To Reproduce**
1. Add a Greenscreen Video Clip
2. Click on Effects
3. Click and drag on the Chroma Key Effect
4. See error by looking at the Task Manager and playing the video

**Expected behavior**
Openshot will use less memory

**Screenshots**
![memory usage](https://user-images.githubusercontent.com/37266538/41038055-65aa7398-6995-11e8-8776-8388b302d50e.PNG)

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**
I have tested this and it looks like Openshot is using over 500MB of memory which is very bad (See Screenshot)

**Comment by N3WWN** [comment]
The default preview cache is set to use up to 250MB of RAM, which is 1/2 of what you're reporting is being used.  You could lower the amount of RAM that the preview cache uses, or switch to a disk cache... either change should reduce _some_ of the memory usage, but may reduce performance.

Video editing typically uses a lot of RAM, though... many commercial packages have requirements of 8 GB of available RAM for the editor alone, but I've seen some suggest 16 GB or more for "optimum performance".
