### ISSUE TITLE
Add Auto Animate Disable Option

### ISSUE THREAD

**Issue by MisterTeeXD** [OpenShot/openshot-qt#1658]
**Is your feature request related to a problem? Please describe.**
Its annoying when Openshot auto animates something

**Describe the solution you'd like**
A option to turn off auto animate so that keyframes are not placed automaticly

**Describe alternatives you've considered**
No alternatives

**Additional context**
I can see how new users will complain when something in their video gets moved randomly and i think its best to have a option to turn off the auto keyframes

**Comment by peanutbutterandcrackers** [comment]
Hey there!

I am not sure if OpenShot really auto-animates anything. Perhaps it's just that the users don't know about **everything is keyframe-able** motto of OpenShot.

Perhaps you might want to read [this guide](https://gist.github.com/peanutbutterandcrackers/f0f666243133e0ed25abbc12a4ba23d7) to master OpenShot? o.O

In case there is something I am missing, could you please make a screen-cast or perhaps attach some screenshots?

Thanks!

**Comment by peanutbutterandcrackers** [comment]
@MisterTeeXD - Please do go through [that guide](https://gist.github.com/peanutbutterandcrackers/f0f666243133e0ed25abbc12a4ba23d7), though. Please consider it my gift to you! :) :+1:
