### ISSUE TITLE
Chroma key: Where?

### ISSUE THREAD

**Issue by Le3ooo** [OpenShot/openshot-qt#1659]
Hello, I have a question, where do I find the chroma key (green screen) option here?

**Comment by peanutbutterandcrackers** [comment]
Please watch [this video](https://www.youtube.com/watch?v=2sushecqMs4&t=24s) to learn all about chroma keying in OpenShot.

P. S: It is made by Mr. Jonathan Thomas, our main developer, himself. So, it is quite authoritative. :)

Hope that helps!
