### ISSUE TITLE
Can't import JPEGs

### ISSUE THREAD

**Issue by alobar74** [OpenShot/openshot-qt#1661]
i cant import jpgs from my hard drive it keeps saying its not a valid format ...win10

**Comment by gary9872** [comment]
You have stated both WIndows 10, Linux mint 17.1 . Does it do it in both operatiing systems?

**Comment by peanutbutterandcrackers** [comment]
Perhaps you'd like to upgrade to the [latest daily build](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914)? That should resolve this issue. But this is definitely strange. Perhaps the jpeg files are themselves corrupted? Can you open them with other programs?

Switching to the latest daily build should definitely help.

Hope it does. :)

**Comment by DylanC** [comment]
@alobar74 Can you try v2.4.2 and let us know if you have any success?
