### ISSUE TITLE
No sound when exporting video

### ISSUE THREAD

**Issue by rayan1224** [OpenShot/openshot-qt#1663]
**Describe the bug**

**System Details (please complete the following information):**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**

**Comment by laughingvulcan** [comment]
Had the same problem, found a simple fix on a similar thread. 

After you hit the red button to save your work, under the "target" dropdown menu it is set at MP4 (h.264).  Change this to MP4 (mpeg4).

**Comment by peanutbutterandcrackers** [comment]
Yes, that is only an issue with the media player not being able to decode the audio stream. If you use VLC to play the first exported video with the audio issue, you will be able to play it because VLC can decode the stream. Hope that helps! :+1:

**Comment by peanutbutterandcrackers** [comment]
I thought I should add this too, just in case it wasn't clear: The sound *is* there. It's just that the media player is unable to decode the audio stream.

[Here is the download link for VLC Media Player, BTW.](https://www.videolan.org/vlc/index.html) :)

**Comment by rayan1224** [comment]
Thanks Guys, almost there... exporting the video by selecting "mpeg4" fixed the sound problem but for and unknown reason, now the video stream is flickering from normal to green screen at a fast pace! I'll try different video output format to see if I can resolve my problem.

**Comment by rayan1224** [comment]
Like peannut.. was stating, If I use VLC... problem is resolved. Now I have to see if the IT dept. can make sure all employees have a player that'll read the stuff properly.

Thanks again guys.

**Comment by DylanC** [comment]
@rayan1224 - No problem. Good job @peanutbutterandcrackers !

**Comment by peanutbutterandcrackers** [comment]
@rayan1224 - Awesome! Glad this was resolved. Yes, you should really use VLC. It is the best free and open source media player out there. VLC > Windows Media Player. :) You're most welcome!

@DylanC - Thanks, Cap'ain!

Closing this as this has been resolved. :)
