### ISSUE TITLE
ops-project file doesn't work after update

### ISSUE THREAD

**Issue by tourbiker** [OpenShot/openshot-qt#1668]
i just updated from Ubuntu 17.10 to 18.04 64bit which includes openshot 2.4.1

trying to open a previous project i found, that only the used raw-files are selected. Neither any cutting nor any effect was accessible in the project.
How can i get back these informations which are readable in the osp-file but just not used by the program itself?

Thanx in advance
oli

**Comment by peanutbutterandcrackers** [comment]
I dindn't know there was an update that messed up the backwards compatibility of the `.osp` files. I am not quite sure about this. Maybe the Ubuntu Packagers did something? I don't really know.

@DylanC - Any thoughts, Cap'ain?

**Comment by DylanC** [comment]
@peanutbutterandcrackers - Sounds like a strange issue. I don't think upgrading Openshot should mean a project cannot open. o_O

**Comment by peanutbutterandcrackers** [comment]
No, it shouldn't. Perhaps this needs some detective work?

@tourbiker - Could you please upload the `.osp` file here after zipping it? You can upload `.zip` files here.

**Comment by DylanC** [comment]
@tourbiker Can you try v2.4.2 and let us know if you have any success?
