### ISSUE TITLE
Strange Issue with audio (2.0.7 vs 1.4.3)

### ISSUE THREAD

**Issue by PaoloPelloni** [OpenShot/openshot-qt#167]
On my laptop, brand new Ubuntu 16.04 I have both openshot & openshot-qr respectively 1.4.3 from official repository and 2.0.7 from PPA.

If I export the same project video with the same exact settings mp4/h264/ac3 the former gives me a perfect output while the latter has a defective audio. The track is there but is corrupted in weird ways. No audio in the beginning, then it starts with lot of noise and so on......

I suppose the underlying layer is the same for both (melt?). How can I help and report it accurately?

**Comment by PaoloPelloni** [comment]
After some more research I figure out that one of the issues is that openshot2 ignores the mute on whole track (is not even there anymore) and on single clip on the timeline, you have to manually set each volume to 0. It's annoying but the audio is now better.
Still the crackling sounds weren't in the original audio so it has to be an issue with multiple tracks with audio playing concurrently.

**Comment by RonCam** [comment]
I'm having "distorted, crackling' audio problems too, and noticed it's be related to CPU usage going up to 100%.  Trying to fix it by running nothing else, but when I forget and start Chrome while OpenShot's running, the sound (actually, I'm noticing it first from what's running in the browser) starts 'going to pieces'. 

Just an idea.  What does the CPU monitor show?

I just started with 2.0.7 but may go to the earlier version if it persists.

**Comment by PaoloPelloni** [comment]
Good idea RonCam I'll give it a try to run it without any other task when I have time.
Normally my 2CPUs are pretty loaded but that is not an issue at all with 1.4.3, which is still my production tool since it has less bugs, more options and a better GUI. Basically there's not a single thing in which I found openshot2 better than its predecessor. But I am willing to help with the development.
The crackling sound with me happens when there are two audio tracks overlapping (a fade out music and a talk track).

**Comment by RonCam** [comment]
Happened to me again, and I found an easy way to fix it -- takes not time at all, no CPU monitor needed.
Open terminal, run top, and you'll see _if_ your %CPU use could be the problem, and if that's a 'yes', then you'll see what's causing it.
I saw the combined running of Chromium, OpenShot and pulseaudio forcing the system's CPU usage to 100%, did a <Ctrl-C> to stop top, then killed pulseaudio using its PID number.
To my surprise, playing a video with audio, the audio was now working normally, and perfectly clear.  Apparently pulseaudio restarts itself, when needed?  
After that, again running top showed the system's %CPU to be in the normal range.

**Comment by PaoloPelloni** [comment]
Apparently with me the issue was only importing old projects from 1.4. 
With brand new projects created in 2.0 I have no crackling sound in audio, so despite the regressions in 2.0 and some crashing, this was also in 1.4, I am willing to give it a try to cut in 2.0 from now on. If I discover more RonCam I'll keep you posted.

**Comment by jreynojustin** [comment]
OpenShot is now in Version 2.2 if you are still noticing issues in the latest version please re-open this issue letting us know.

**Comment by scryedzxp** [comment]
This issue is STILL happening in 2.4.0. All I did was created a new project, dragged an mp3 onto the timeline, played the track and about 2 minutes in I hear crackling and stuttering.

**Comment by joeostrander** [comment]
I have the same issue

**Comment by kpande** [comment]
this happens still when video and audio track are coinciding, same sample rates etc

**Comment by cptX** [comment]
I can verify that this is still happening in 2.4.1-dev1.
I had to go back in 1.4.3 to edit a video because of these cracking and unexplained sounds in 2.4.1. Source Video is fine when played outside Openshot.

**Comment by peanutbutterandcrackers** [comment]
Strange. I had no issues with the audio on my Elementary OS 0.4.1 'Loki' machine using 2.4.1-dev1. Currently I am using the daily PPA and haven't really worked on any project to know if it there. But I think it works fine...

**Comment by peanutbutterandcrackers** [comment]
@Lemmings19 - could you please try out the latest daily build. There was [a commit](https://github.com/OpenShot/libopenshot/commit/1ec9e4426a94181187ac1f039971d7700911abb2) recently that dealt with the popping issues. Please head over to the [download](http://openshot.org/download) page and click on 'daily builds' and grab the latest one. Hope that helps!
