### ISSUE TITLE
What Is Going On With The Daily Builds?

### ISSUE THREAD

**Issue by MrTertius** [OpenShot/openshot-qt#1670]
I have the daily builds bookmarked and i noticed that some builds are being moved and removed for some odd reason, please explain what is going on so i can be up to date.

**Comment by peanutbutterandcrackers** [comment]
I didn't realize that this was happening. I will try to contact the devs and get back to you on this one.

@DylanC - Anything about this, Cap?

**Comment by DylanC** [comment]
@peanutbutterandcrackers - I don't sadly, I didn't even know this was happening. :laughing:

**Comment by DylanC** [comment]
@peanutbutterandcrackers - From what I can see @jonoomph is changing some GitLab pipeline stuff. This may be the cause in the interruption of normal daily builds.

**Comment by MrTertius** [comment]
So should i use Gitlab?

**Comment by peanutbutterandcrackers** [comment]
No, No, No. Not at all. Gitlab is used just for the builds. GitHub is the main repo. But any change made here is mirrored onto GitLab.

I think it's just the transition. And that these things will go to normal, soon.

Hope that helps. :)

Should I close this issue now, good sir?

**Comment by MrTertius** [comment]
I will close this issue, thanks for answering :)
