### ISSUE TITLE
openshot.org download page still refers to "Windows (64-Bit Installer)"

### ISSUE THREAD

**Issue by ferdnyc** [OpenShot/openshot-qt#1671]
The page https://www.openshot.org/download/ still describes the Windows downloads as "(64-Bit Installer)" files, even though the daily builds now also include 32-bit builds, and the 2.4.2 release will as well. OpenShot is no longer 64-bit exclusive on Windows, the site should reflect that.

![screenshot 2018-06-08 21 17 58](https://user-images.githubusercontent.com/538020/41186452-c5e57da4-6b64-11e8-9d18-31f6b270ef8e.png)

**Comment by DylanC** [comment]
@ferdnyc - Agreed! :+1:

**Comment by DylanC** [comment]
@jonoomph - I don't have any power to change this. Could this be updated or do you disagree that a change needs to be made here?
