### ISSUE TITLE
2.4.2 When ????

### ISSUE THREAD

**Issue by kimeguma** [OpenShot/openshot-qt#1675]
2.4.2 When ????

**Comment by TheLEGObrick** [comment]
I saw some guy mention that it's coming within a couple weeks if it comes on schedule

**Comment by peanutbutterandcrackers** [comment]
OpenShot does not really have a fixed release schedule. New versions are released as and when they are ready. This is a volunteer-backed project, the labour of love of a single man. I am also just another volunteer here. Mr. Thomas, our main developer, and others squirrel time away from their day to work on this free software gem. Therefore, things do not move as fast as they could have.

However, v2.4.2-rc1 (Release Candidate 1) is already out. You can grab it from the download page by clicking on the `daily builds` button. Please do report any bugs that you can find. Once all the major bugs from the Release Candidates are fixed, v2.4.2 will be released.

Hope that answers your question. :)

**Comment by DylanC** [comment]
@kimeguma - v2.4.2 has been released now. 👍
