### ISSUE TITLE
Problem with Aspect Ratio after merging two video clip

### ISSUE THREAD

**Issue by UtpalKumarRay** [OpenShot/openshot-qt#1676]
**Describe the bug**
I have two video clips(MP4) shot in Sony Digital Camera (DSC-WX7). The resolution of the source video clips are 1440x1080. After I merge them(I tried two different output format, 1080p & 720p)  using OpenShot, it creates an output video file. But the output video file does not maintain the original Aspect Ratio. So, the video is not at all pleasing to watch.

Even a slightest help on this issue will be greatly appreciated.

**System Details (please complete the following information):**
 - Operating System / Distro: Ubuntu 16.04.03
 - OpenShot Version 2.4.1

**To Reproduce**
As told on the top.

**Expected behavior**
The aspect ratio of the merged video file should be same as input video files.

**Screenshots**

**Logs**

**Additional context**
I can send you the source file if you want.

**Comment by peanutbutterandcrackers** [comment]
Perhaps you should [create your own custom profile](https://www.openshot.org/static/files/user-guide/profiles.html#custom-profile) to fit your needs. Maybe that can fix it...

Hope that helps, good sir!

**Comment by DylanC** [comment]
@UtpalKumarRay Can you try v2.4.2 and let us know if you have any success?
