### ISSUE TITLE
"Issue" with "excessive" rounding (More closer to a suggestion/feature request)

### ISSUE THREAD

**Issue by TheLEGObrick** [OpenShot/openshot-qt#1677]
**Is your feature request related to a problem? Please describe.**
I use OpenShot for... certain tasks in which I would like if I could be able to set the image duration exact on (even) a thousandth of a second. However, OS automatically rounds any that sort of number to the closes hundredth, and because I almost kind of have OCD, I can't accept the nigh inexisting inaccuracy.

**Describe the solution you'd like**
I'd like if there was at least an option to changing how heavily OS rounds durations of things

**Describe alternatives you've considered**
 

**Additional context**
 

PS: I have virtually no idea on what the hell am I meant to do with this "feature request"... issue format?

**Comment by peanutbutterandcrackers** [comment]
Hmm... I see. I will try to get the devs attention to this one, too. If there are any advantages to having OpenShot support that much precision, it'd be pretty nice to have that feature. Thank you for the suggestion.

P. S: You don't exactly have to follow the issue format. It is just there to help. :)

**Comment by TheLEGObrick** [comment]
Alright uh, thanks for letting me know that

**Comment by peanutbutterandcrackers** [comment]
You're most welcome!
