### ISSUE TITLE
Open file dialog

### ISSUE THREAD

**Issue by PaoloPelloni** [OpenShot/openshot-qt#168]
I am using 2.0.7 under Ubuntu 16.04 and noticed that the file open dialog is not the standard one from the OS (as in v1.4.3). Is there a way to get it back as it was? The OS one has bookmarks, latest files and other useful things.

**Comment by jreynojustin** [comment]
OpenShot is now in Version 2.2 if you are still noticing issues in the latest version please re-open this issue letting us know.
