### ISSUE TITLE
Audio Glitches

### ISSUE THREAD

**Issue by MisterTeeXD** [OpenShot/openshot-qt#1683]
**Describe the bug**
When a video clip is added to the timeline and it starts playing another clip the the previous clip's audio will sound glitchy

**System Details (please complete the following information):**
 - Operating System / Distro: Windows 10
 - OpenShot Version: 2.4.2-rc2

**To Reproduce**
1. Go to imported clips
2. Drag 1 video clip on the timeline
3. Drag another video clip and put it next to the previous clip
4. See error by clicking play

**Expected behavior**
The audio will no longer sound glitchy

**Screenshots**
[2018-06-12 16-02-13.zip](https://github.com/OpenShot/openshot-qt/files/2094321/2018-06-12.16-02-13.zip)

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**
I have a zipped recorded video attached of this Glitchy Sound and also, this glitchy sound was in other Daily Builds as well, including the Release Candidate Builds.

**Comment by peanutbutterandcrackers** [comment]
I have notified the devs about this. Hopefully there will be some further fixes to this.

**Comment by DylanC** [comment]
@MisterTeeXD Can you try v2.4.2 and let us know if you have any success?
