### ISSUE TITLE
Openshot preview different than export!!

### ISSUE THREAD

**Issue by saidch1** [OpenShot/openshot-qt#1684]
Hello guys!

I worked for 2 days on a video in Openshot with images, videos, and subtitles; the preview is perfect; however when I export it either MP4 or AVI.... it s completely different the subtitles are in a different place, everything is wrong...
Can anyone help me?

Thank you!

**Comment by N3WWN** [comment]
What frame rate is your project in and what frame rate did you export the video at?  If they differ, any keyframed items will be in different locations.

**Comment by DylanC** [comment]
@saidch1 - Can you get back to us on this issue?

**Comment by DylanC** [comment]
@saidch1 Can you try v2.4.2 and let us know if you have any success?
