### ISSUE TITLE
Missing translations ?

### ISSUE THREAD

**Issue by nsgitfr** [OpenShot/openshot-qt#1685]
Not a bug, a request... 
Looking for translations FR-FR... some are missing for 2.4.2... What will happen ? Release will be with EN terms ?
No one to help ?
Best

**Comment by peanutbutterandcrackers** [comment]
@nsgitfr - Good sir, a [call for translations](https://www.openshot.org/blog/2018/04/18/call-translations-openshot-242/) was made a month or so back for v2.4.2. It is up to the users from several nations themselves to translate OpenShot in to their own languages. So, yes, the translation for french will probably have a lot of missing words for this release. However, if you want, and have the time to volunteer, you can go ahead and help out with the translations right away. That way, v2.4.3 might have the full french translations. Hope that answers your question.
