### ISSUE TITLE
Slow display of audio wave in Ubuntu

### ISSUE THREAD

**Issue by ruffieuxh** [OpenShot/openshot-qt#1688]
Hi,
I am a new user of OpenShot and I like the program very much. It totally fits my requirements.
I am currently cutting an educational video consisting of a video stream (me presenting a ppt presentation) and a screencast (the ppt presentation itself). The video stream consists of 3 videos, each some 30mins long.
Obviously I need to cut out some parts of the speach (i.e. make errors, etc). This works well in principle.
However, when I want to display the audio wave to find the place to cut out, it takes every time around 2-3 minutes to display the audio wave and after each cut the wave is gone and I need to set it up again, which again takes 2-3 minutes.
This obviously slows me down quite a bit and is frustrating.

**System Details (please complete the following information):**
 - Operating System / Distro:Ubuntu 16.04
 - OpenShot Version: 2.4.1-dev 1

I also tried it with 2.4.1.160 and 2.4.2-rc1 builds, but they do not seem to work stable yet. They crash many times. With rc1 the creation of the wave seems a bit faster, but the program crashes quite often.

**To Reproduce**
1. Put a 30min video onto the time line
2. Right click on it and ask for the wave 
3. It takes 1-2 minutes during which nothing else can be done in Openshot
4. Wave is displayed.

**Expected behavior**
I would not want to wait for more than 10sec

**Screenshots**
none

**Logs**
none

**Additional context**
none

**Comment by peanutbutterandcrackers** [comment]
Sorry for the inconvenience. This is a known issue and we hope that the devs will soon get around to resolving this. I will try to get them to put this in the priority. I'm afraid for the moment, you'll just have to wait for future releases.

Speaking of which, you mentioned there was a crash with rc builds. Could you please open another issue of the crash and [attach the logs](https://github.com/OpenShot/openshot-qt/blob/develop/CONTRIBUTING.md)? That will help us make the release more stable. However, please do delete the `opesnshot-qt.log` and `libopenshot.log` files from the `.openshot_qt` folder in your home directory first. That way, the logs will be smaller in size and will have precisely what is needed.

Hope that helps!

**Comment by ruffieuxh** [comment]
Will do so. Please note, that the wave time problem is substantially better (faster) in the rc1 version, althought not fast enough yet (55sec).

**Comment by peanutbutterandcrackers** [comment]
@ruffieuxh - Wow. Thank you for the encouraging report! I have just notifed the devs of this good news. Hopefully, some more work will soon be done in this front. Please do keep on loving and supporting OpenShot! :)

**Comment by ruffieuxh** [comment]
Tested rc3 today and I can report that the display of the audio wave for the same video now only takes some 20sec and therefore improved a lot. Some further optimization is still needed, but you are on a good way! :-)
What is embarassing is that the display of the way disappears everytime when you are cutting or slicing. You may want to have a look at this as well.
Please continue your good work!

**Comment by N3WWN** [comment]
@ruffieuxh I've noticed the waveform disappearing on the timeline, too.  You can make it reappear by zooming in/out one step (you can restore your view by zooming out/in one step again).  

If you slice and keep both sides, one side (the right, IIRC) won't retain the waveform and you'll have to have OpenShot generate them again for that partial clip.

**Comment by peanutbutterandcrackers** [comment]
@ruffieuxh - Awesome! Thanks for the good word! Hope you too keep on loving and supporting OpenShot! :)

**Comment by ruffieuxh** [comment]
@N3WWN Yes, Richard, saw that, thanks. But I still think it should not disappear. Plus it does not seem to work everytime.
