### ISSUE TITLE
Accented Characters in Path Name Makes Project Saving Impossible

### ISSUE THREAD

**Issue by AllainMcCain** [OpenShot/openshot-qt#169]
I am French, and thus, many of my folders have accented characters such as é or è. When I try to save a project, the software fails. Here's an example of an error message:

**Couldn't save project data file:
C:/Users/George/Documents/[2014-] Début de la vie adulte/Untitled Project.osp
[Errno 2] No such file or directory: b'C:/Users/George/Documents/[2014-] D\xc3\xa9but de la vie adulte/Untitled Project.osp'**

"Début" is transformed into "D\xc3\xa9but" by the software, which makes saving impossible. A workaround is to have a path name without any accented characters, but that's annoying for a French user like me.

Thanks.

**Comment by DylanC** [comment]
@AllainMcCain - What version of OpenShot are you using?

**Comment by DylanC** [comment]
@AllainMcCain - Closing since no response and ticket seems to pertain to an older version. Please open a new ticket if issue exists in OpenShot 2.3.4. Thanks.
