### ISSUE TITLE
New video file exporting without sound. How do I fix?

### ISSUE THREAD

**Issue by Joslin1** [OpenShot/openshot-qt#1690]
**Describe the bug**

**System Details (please complete the following information):**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**

**Comment by DylanC** [comment]
@Joslin1 - Can you try a daily build and see if the problem still exists?

**Comment by Joslin1** [comment]
What is a daily build?

Matthew Scotti
Project Manager | Joslin Innovation
Joslin Diabetes Center
1-617-309-5919

This message is intended for the use of the person(s) to whom it is addressed. It may contain information that is privileged, confidential, or otherwise protected from disclosure under applicable law.  If you are not the intended recipient, any dissemination, distribution, copying, or use of this information is prohibited, and you should destroy this communication without making copies or further transmitting.
[JDC_Harvard_Lockup CMYK_NEW]

**Comment by peanutbutterandcrackers** [comment]
Please use [VLC Media Player](https://www.videolan.org/vlc/index.html) instead. It is not exporting without sound. Rather, the media player that you are using currently is not able to decode the audio stream. VLC can play nearly everything you throw at it. If you want to have the the video to have audio for all media players, please try exporting using a different profile instead.
![screenshot at 2018-06-14 08-05-51](https://user-images.githubusercontent.com/26764547/41388063-e883bf1c-6fa9-11e8-9eeb-09aa16eb5d78.png)

Hope that helps!

[Closing this as answered, and hopefully resolved. :)]

**Comment by peanutbutterandcrackers** [comment]
Also, daily builds are versions of a program released as soon as any changes have been made to the main source code repository, so as to test and improve the program. So, version 2.4.1 (the latest stable release) was released. And then several  changes have been made to the code - several important new features, stability fixes, bug fixes, enhancements. And the daily builds have all of that.

Hope that helps! :)
