### ISSUE TITLE
Crash after some 2 hours of work

### ISSUE THREAD

**Issue by ruffieuxh** [OpenShot/openshot-qt#1692]
**Describe the bug**
Application got slower and slower and eventually crashed, when navigating while navigating within a stream in preview mode.

**System Details (please complete the following information):**
 - Operating System / Distro: Ubuntu 16.04
 - OpenShot Version: 2.4.2. rc1

**To Reproduce**
Just cut a long video (i.e. 3 slices of 30mins each) and 3 streams (video, screencast and several pictures).

**Expected behavior**
No crash even over a long time.

**Screenshots**
None available

**Logs**
uploaded

**Additional context**
none
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/2101706/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2101707/openshot-qt.log)

**Comment by gary9872** [comment]
My advice would be to save often. Regardless of how stable openshot or will become there will always be crashes. 

From what you've said, it seems like there was an issue with memory. Either you didnt' have enough or Openshot has a leak. : Do you have at least 8GBs, and you are editing with nothing else running?

**Comment by peanutbutterandcrackers** [comment]
@gary9872 - Hey there! Please do take a look again at your ImageMagick Patch for libopenshot. (This must be the 3rd time I am reminding you about it in the comments wherever I can see you. lol) There's something in the thread that you might want to see. Thanks!

@ruffieuxh - I agree with what @gary9872 has said. Please do follow his advice, good sir. But OpenShot will get better with time. :)

**Comment by ruffieuxh** [comment]
Thanks for your comments. Yes, I do have some other stuff running in parallel and I am aware that I am giving the application a hard condition. Fully understand that it might running slow, but it should not crash due to low memory. I am running it on a system with 8GB of memory.

Still like the application very much! Keep up your good work.

**Comment by peanutbutterandcrackers** [comment]
@ruffieuxh - Thank you for the good word. Hope you will keep on loving and supporting OpenShot!
