### ISSUE TITLE
Related problems? Crash in OpenShot-v2.4.2-rc2-x86_64.exe

### ISSUE THREAD

**Issue by Eta76** [OpenShot/openshot-qt#1693]
**Describe the bug**
Made my first project consisting of about 20 short (30seconds) movies.
Added description text as an overlay, for every movie.

Export to multiple filetypes crashed.
mp4/dvd/.. crashed at 1.2%
web crashed immediatly,
No stacktrace was logged in log file.

When deleting the last 90% of the movie timeline, the export succeeded.
This makes me think the problem is in a preprocess step, maybe the overlays, or maybe the audio streams? 

it could be the crash occurred with an jpeg overlay, which has a 'transform' action. 
A 500x1080 pixels images was moved to the right, different keyframes seem to be used, since the transformed image was slightly moving between start and end on the timeline.

Unfortunately the crash took away a large part of the project file. So I cant reproduce my problem yet.
But since it took me 6hours creating the 10minute movie... I am eager to get this fixed :-) 

**System Details (please complete the following information):**
 - Windows 10 
 - OpenShot Version OpenShot-v2.4.2-rc2-x86_64.exe

**To Reproduce**
I think the crucial project part was the transform. But projectfile was stripped from its history.. (bug) 

**Expected behavior**
Export of complete movie

**Logs**
------------------------------------------
libopenshot logging: Thu Jun 14 17:31:01 2018
------------------------------------------
---- Unhandled Exception: Stack Trace ----
------------------------------------------
libopenshot logging: Thu Jun 14 17:35:03 2018
------------------------------------------
------------------------------------------
libopenshot logging: Thu Jun 14 20:51:16 2018
------------------------------------------
------------------------------------------
libopenshot logging: Thu Jun 14 20:56:14 2018
------------------------------------------
---- Unhandled Exception: Stack Trace ----
------------------------------------------
libopenshot logging: Thu Jun 14 20:57:06 2018
------------------------------------------

from openshot-qt.log
..
main_window:INFO updateStatusChanged
project_data:ERROR Error while converting absolute paths to relative paths: path is on mount 'D:', start on mount 'C:'
 main_window:INFO Saved project C:/Users/edgar/Betoeterd_intro.osp
timeline_webview:INFO 4
..
timeline_webview:ERROR TimelineWebView::eval_js() called before document ready event. Script 
..
 main_window:ERROR Unhandled crash detected... will attempt to recover backup project: C:\Users\edgar\.openshot_qt\backup
....
properties_model:INFO updating clip properties model.
preview_thread:INFO refreshFrame
preview_thread:INFO self.player.Position(): 1
    timeline:INFO Adjusting max size of preview image: PyQt5.QtCore.QRect(213, 0, 1008, 567)
 main_window:INFO Clear all thumbnails: C:\Users\edgar\.openshot_qt\thumbnail
 main_window:INFO Clear all animations: C:\Users\edgar\.openshot_qt\blender
 main_window:INFO Failed to clear thumbnails: C:\Users\edgar\.openshot_qt\thumbnail
project_data:INFO Setting default profile to HD 1080p 25 fps
project_data:INFO 2.4.2-rc2
project_data:INFO 0.2.0
preview_thread:INFO refreshFrame
preview_thread:INFO self.player.Position(): 1
timeline_webview:INFO UpdateLayerIndex
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "C:\Program Files\OpenShot Video Editor\windows\views\timeline_webview.py", line 2455, in update_zoom
    newScale = zoomToSeconds(newValue)
  File "C:\Program Files\OpenShot Video Editor\classes\conversion.py", line 63, in zoomToSeconds
    return zoomSeconds[zoomValue] or 1
IndexError: list index out of range
 main_window:INFO updateStatusChanged
[openshot-qt.zip](https://github.com/OpenShot/openshot-qt/files/2103783/openshot-qt.zip)

I am a developer myself, currently only VS2017(C++) installed, but I could try to debug/reproduce this.

**Comment by Eta76** [comment]
trying to recreate the projectfile in 2.4.2 RC, but 2 jpeg, 2 movies and transistion and the editor crashes. when previewing (scrubbing the cursor through the timeline)

**Comment by peanutbutterandcrackers** [comment]
@Eta76 - Hey there! The issue where transition triggered a crash was solved. There was a commit that should have resolved it (and it was reported to have been resolved, too). Could you please test this out with the latest RC, RC3?

Um... since you are developer yourself, please do try to debug/reproduce this, good sir. OpenShot is the labour of love of a single man and a community effort. I, myself, am just another volunteer who loves this program. It'd be awesome to have a new contributor to the project!

**Comment by Eta76** [comment]
crash seems to be solved. it crashed real easy before, and now no crashes witnessed. 
Still jumping frames, I don't know if this is related to transitions. But I will make a new bug, if it is easiliy reproducable.

PS: I am a C++ developer, and OpenShot seems python based, so not my line of work :-)

**Comment by peanutbutterandcrackers** [comment]
@Eta76 - OpenShot uses a lot of C++! [libopenshot](https://github.com/OpenShot/libopenshot) is the multimedia framework that OpenShot uses. And it is entirely written in C++. So, openshot-qt is just a py-qt wrapper around the C++ libopenshot core, in essence. Perhaps you could help us out, sir!
