### ISSUE TITLE
Can't open new project

### ISSUE THREAD

**Issue by otaixap** [OpenShot/openshot-qt#1694]
It seems like the last time i made a video it didn't save properly and now every time i open it an annooying message appears asking for the missing files. I can't start a new project because the message just keeps popping up and it doesn't let me do anything.
![captura de pantalla de 2018-06-14 16-48-05](https://user-images.githubusercontent.com/40278668/41437547-be771dba-6ff2-11e8-89ba-1673332c544b.png)
I just want to make a video please help

**Comment by DylanC** [comment]
@otaixap - Yep, thats what he mean't.

**Comment by DylanC** [comment]
@otaixap - Yes, I would say your project file became corrupted. Maybe start again is best.
