### ISSUE TITLE
Crash when previewing and running through a transition

### ISSUE THREAD

**Issue by ruffieuxh** [OpenShot/openshot-qt#1695]
**Describe the bug**
Previewing a video with 3 streams. Application crashes sometimes when running through a transition.

**System Details (please complete the following information):**
 - Operating System / Distro: Ubuntu 16.04 LTS
 - OpenShot Version: 2.4.2-rc1

**To Reproduce**
1. Preview Video with transitions
2. When preview runs through a transition it sometimes crashes the application

**Expected behavior**
No crash during preview

**Screenshots**
None

**Logs**
Attached

**Additional context**
None
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/2105328/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2105329/openshot-qt.log)

**Comment by peanutbutterandcrackers** [comment]
This is a known issue and it has already been resolved, good sir. Please try v2.4.2-rc3 (which was released just a few hours earlier). Thanks! Hope that helps!

P. S: Please do confirm whether or not it works for you. :+1:

**Comment by ruffieuxh** [comment]
Thanks! Will do so.

**Comment by ruffieuxh** [comment]
Crashed again today running through a transition between two streams based on rc3 (see attached log files).
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/2111176/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2111177/openshot-qt.log)

**Comment by peanutbutterandcrackers** [comment]
I have just let the devs know about this issue. Hope this will be fixed soon!

**Comment by DylanC** [comment]
@ruffieuxh Can you try v2.4.2 and let us know if you have any success?

**Comment by ruffieuxh** [comment]
Ran the exact same video in preview mode over 50mins including several dozens of transitions and it did not crash once, despite I ran heavy number crunching in parallel (by intention). Well done!!

**Comment by peanutbutterandcrackers** [comment]
Yay! Closing this as resolved, then! Please do continue to love and support OpenShot. :)

**Comment by klaymoore07** [comment]
Trying to do a gender reveal video. Very simple, it is 5 video clips, 3 titles with transitions scattered throughout and I can view the video sometimes, but cannot export the video without it crashing. I'm completely green to this software and process. I am using v2.4.2. I was able to export the video without the transitions but it doesn't look as nice
