### ISSUE TITLE
Cannot edit a video

### ISSUE THREAD

**Issue by pliegok** [OpenShot/openshot-qt#1696]
**Describe the bug**
I imported an MP4 video into the system using the import button. I see the video is there but I cannot play, edit or do anything. 

**System Details (please complete the following information):** WINDOWS 8 latest version of systems
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**To Reproduce**
Clicked on Import file, selected the MP4 file from my PC and uploaded. The video shows on the left hand side but nothing else happens, you click play, effects, anything, nothing happens. You export it and there is nothing in the video that gets exported. 

**Expected behavior**
Want to add blur effects to some text inside a video I created. 

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**

**Comment by pliegok** [comment]
ok that worked! How do I select a specific text within the video to get blurred out?

**Comment by DylanC** [comment]
@pliegok - I don't think we have this feature yet. @gary9872 Any suggestions for an alternative he/she could do?

**Comment by peanutbutterandcrackers** [comment]
Umm... Yes we do. In the latest daily builds!

1. Please switch to the [latest daily build](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914), or wait for v2.4.2 to be out - which should be within June.
2. Seeing that you seem to be a relatively new user, please go through this [OpenShot Zero to Hero Guide](https://gist.github.com/peanutbutterandcrackers/f0f666243133e0ed25abbc12a4ba23d7). You will be able to understand the nuances of the following steps only if you go through all of that guide and understand the use of keyframes.
3. In the `Effects` tab, you should find an effect called `Pixelate`. That is what you are looking for.
4. ..........and there seems to be a bug. I will report it to the devs and hopefully it will be fixed soon. But please do read through the guide in the meantime.

**Comment by DylanC** [comment]
@peanutbutterandcrackers - Oh yeah I forgot about that feature. 😆  @pliegok - Try the suggestion by @peanutbutterandcrackers  👍

**Comment by peanutbutterandcrackers** [comment]
@DylanC - It seems that the effect is bugged in the latest daily build: https://github.com/OpenShot/libopenshot/issues/121. Could you please test it out for me, Cap'ain?

**Comment by DylanC** [comment]
@pliegok Can you try v2.4.2 and let us know if you have any success?
