### ISSUE TITLE
Cant watch exported videos

### ISSUE THREAD

**Issue by HypnotizeCSGO** [OpenShot/openshot-qt#1697]
**Describe the bug**
When i export a finished video. i get half a second of video then blackscreen (sound works). tired multiple target format/video profile/quality to no avail.

**System Details (please complete the following information):**
Win 10 latest version i think (downloaded for first time 8th june 2018)

**To Reproduce**
Any video i make.

**Screenshots**
https://gyazo.com/8cdcfbef29b58b7b0e919de06d472e11 (imagine with sound)

**Comment by peanutbutterandcrackers** [comment]
Good sir, please try out the [latest daily build](). They are known to be a lot more stable than v2.4.1 and also have quite a lot of new features and improvements. v2.4.2 will also be out soon (we already have v2.4.2-rc3 released). Once you have the latest daily build installed, you can re-render the `.osp` project all over again. That should fix your issue. Hope that helps!

P. S: If it doesn't, I would suspect your current media player for not being able to properly de-code the audio stream. In which case, switching to [VLC Media Player](https://www.videolan.org/vlc/index.html) should fix the issue. Long live VLC! :)
