### ISSUE TITLE
automated video editing with placeholder items

### ISSUE THREAD

**Issue by yvz5** [OpenShot/openshot-qt#1698]
**Is your feature request related to a problem? Please describe.**
I have a small youtube channel and I upload videos everyday. Its a pain in the butt to do the same things over and over again. 

**Describe the solution you'd like**
I would like to define placeholder items on the timeline and replace them with input i give to a CLI. For example: 
IntoVideo.mp4 + PlaceHolder1 (or a variable doesnt matter what you call them) + PlaceHolder2 (Main video) + OuttroVideo.mp4
IntroAudio.mp3 ---------------------------------------------------------------------- + PlaceHolder3 (Main Audio)

and I want to be able to use a cli like so: 
openshot.exe --project=c:\project.osp --action=render --placeholder1 = c:\video1.mp4 --placeholder2= c:\raw_video.mov --placeholder3=c:\music.mp3 

**Describe alternatives you've considered**
I ve tried using ffmpeg with bash script but its too complicated and hard to automatize.

**Additional context**
this feature would save me at least an hour every day.

**Comment by peanutbutterandcrackers** [comment]
Hmm... I think [OpenShot Cloud API](https://www.openshot.org/cloud-api/) does just that, but then again, it is a commercial product which is used to fund the development of OpenShot Video Editor - the free software. Perhaps you'd be interested in it, for now?

**Comment by yvz5** [comment]
well then I ll try to do this by myself. will let you know the progress

**Comment by peanutbutterandcrackers** [comment]
Okay!

**Comment by oblam** [comment]
This is a feature that I would love to have. I am editing about a hundred videos that have the same opening and closing but different content. Has anybody made some headway on this?

**Comment by yvz5** [comment]
hey @oblam i totally forgot this. are you a developer ? if you are interested we can work on this together
