### ISSUE TITLE
not really an issue - openshot file format and forum

### ISSUE THREAD

**Issue by charlie-57** [OpenShot/openshot-qt#170]
I'd like to 'port' a project from one system to another - I did the original work on a bodhi-linux laptop installation and now I've moved it to a desktop pc-bsd installation so I can work at higher resolution and make better use of the 'cropping' feature.
So I'd like to edit the projects' xml files directly in order to ...
1. make the pathnames fit the project files on the new installation
2. up the resolution used in the project files to as high as the original clips will allow

I'd also like to replace the audio on the video clip files as I double recorded nearly everything - is there a program which can do this ?  Otherwise I'd have to do it for each clip using openshot -> another 'generation' of decompressing the clip .mpg files wouldn't help the quality ...

I should ask these questions at the openshot user forum http://openshotusers.com/forum/index.php but it doesn't offer new user registrations right now ...

Thanks for reading and all and any responses appreciated ...

**Comment by Philhellene** [comment]
I have had the same issue with the forum: can't register as a new user.

**Comment by jreynojustin** [comment]
@charlie-57 I believe registration issues are now open so please post in there and feel free to ask.

Thanks for using OpenShot!
