### ISSUE TITLE
I messed up my Open Shot Layout... :/

### ISSUE THREAD

**Issue by Shiva297** [OpenShot/openshot-qt#1703]
So 

![capture](https://user-images.githubusercontent.com/40357878/41534480-b340e9da-72cc-11e8-8fad-d29996393785.JPG)

As You Can See I Sorta Messed The Entire Layout.. I don't know how to fix it I tried to Uninstall and then install it again..

**Comment by DylanC** [comment]
@Shiva297 - View>>Layout>>Simple View

**Comment by Shiva297** [comment]
@DylanC Thanks For The Help!

**Comment by peanutbutterandcrackers** [comment]
Closing this as resolved. Hope you create awesome videos with OpenShot!
