### ISSUE TITLE
Error message when altering a video stream

### ISSUE THREAD

**Issue by ruffieuxh** [OpenShot/openshot-qt#1704]
**Describe the bug**
Many times when I alter a video stream (cutting, slicing, freezing, etc) I get the attached error message (Java script error).

**System Details (please complete the following information):**
 - Operating System / Distro: Ubuntu 16.04
 - OpenShot Version: 2.4.2.rc3

**To Reproduce**
1. Perform slicing activity
2. Many times the attached error message appears.

**Expected behavior**
No error message

**Screenshots**
attached

**Logs**
attached
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2111120/openshot-qt.log)
![bildschirmfoto vom 2018-06-18 13-46-10](https://user-images.githubusercontent.com/12776226/41534636-865b1840-72ff-11e8-89cc-e5ea7c5d6efb.png)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/2111121/libopenshot.log)

**Additional context**

**Comment by peanutbutterandcrackers** [comment]
I have informed the devs regarding this issue. Hope this will be resolved soon. Thanks for the report!

**Comment by DylanC** [comment]
@ruffieuxh Can you try v2.4.2 and let us know if you have any success?

**Comment by ruffieuxh** [comment]
Seems to be fixed in 2.4.2! Thanks.

**Comment by peanutbutterandcrackers** [comment]
Awesome!

Closing this as resolved!

**Comment by DylanC** [comment]
@ruffieuxh - Thanks for getting back to us with all your issues! :)
