### ISSUE TITLE
Propertie marker not deletable/movable

### ISSUE THREAD

**Issue by gitmiluser27** [OpenShot/openshot-qt#1705]
How can I manually move or at least delete manually set properties (e.g., alpha belending from 0 to 0.50).

They are displayed as small green markers, but there is no way to mark or delete them.

**Comment by peanutbutterandcrackers** [comment]
You can not move or delete them, good sir. What you can do, however, is set them manually from the properties panel. Please right click on the clip in the timeline and click `properties`. The property tab should open up. There, you can manually keyframe properties to your liking. Please note that the properties are set where the playhead currently is on the clip. You might want to go through [this guide](https://gist.github.com/peanutbutterandcrackers/f0f666243133e0ed25abbc12a4ba23d7) to learn more. Hope that helps!

P. S: Keyframe markers are not yet dragable or deletable. They are just indicators, at the moment. But perhaps in the future releases?

Hope you create awesome videos using OpenShot!

**Comment by singalen** [comment]
Hope they will be clickable some day. At the very least, clicking one should make it visually selected, and bring up a properties window for this very frame.

A little rant. Sorry for it and thanks again for your product!
Currently these little green ticky keyframes are the worst part in the OS interface for me.
I AGAIN spent about half an hour finding out what is it and how to edit/remove one - even though last time I tried to do something advanced in OS, I have already found out how they work and even helped others on it.

**Comment by peanutbutterandcrackers** [comment]
@singalen - Perhaps in the future releases? We are lacking on the contributors side, though. Perhaps you'd like to [join us](https://www.openshot.org/static/files/user-guide/developers.html) (and together we shall rule the NLE Video Editing Galaxy?
![openshot meme 1 2](https://user-images.githubusercontent.com/26764547/42606323-b32ca988-859c-11e8-9a1e-fb0c4748260c.png)

**Comment by Trombonedaddio** [comment]
In OpenShot, remove green property markers by first selecting the sample so that it has a red border, and moving the time pointer near the marker (when the time pointer is exactly over the marker the relevant property will turn green in the property box).  Then right click the square box to the right of the property (which allows you to adjust the transition of the property) and select "Remove Keyframe".  Generally it removes the next marker, although if there's only one it will remove it if the pointer is anywhere.
