### ISSUE TITLE
Video output not correct

### ISSUE THREAD

**Issue by gitmiluser27** [OpenShot/openshot-qt#1706]
When I combine images and movies with 25FPS and 30FPS and set transitions/fade effects: 

 pauses and non-existent transitions are shown at once

(3 seconds white, 3 seconds black, audio gone) although nothing is set in the project.

This happens, if i try to export a 1080p 30FPS MP4 Video.

Tested in V2.4.1 and V2.4.2_rc2

**Comment by peanutbutterandcrackers** [comment]
Good sir, you have to export in the same FPS profile as the original footage, or else problems like these may arise. Could you please export it in the same FPS that the original footage is in?

On a side note: Future release of OpenShot will have the ability to deal with varying FPS-es and will set the effects accordingly.

**Comment by DylanC** [comment]
@gitmiluser27 Can you try v2.4.2 and let us know if you have any success?
