### ISSUE TITLE
Adding Text

### ISSUE THREAD

**Issue by FrozenPuppet** [OpenShot/openshot-qt#1707]
Hi, my name's Darcy, and I just recently got OpenShot. I want use it to edit videos in a way that Movie Maker just can't (I'm very broke). Something I've noticed though is that there doesn't seem to be any way to add text.

I'm not entirely sure if there isn't a way, but I sure can't find it. I think this would be a helpful feature and would like to see it added to OpenShot. If it is already in, where can it be found?

Thank you.

**Comment by DylanC** [comment]
@FrozenPuppet - Did you try Title>>Simple Title? or is this not what you are looking for?

**Comment by peanutbutterandcrackers** [comment]
@FrozenPuppet - Hey there, Darcy! Like @DylanC said, `Title` > `Title` is the best way to go. You can use the titles as overlays. If you want further control you can use tools like [GIMP](https://gimp.org) and [InkScape](https://inkscape.org) to create your custom texts (with transparency) and put them on top of the video tracks. Both of the tools are free (like OpenShot) and you can use them to create awesome text overlays to your own liking. Also, if you have [Blender](https://blender.org) installed, you can even create animated titles using OpenShot. Hope that helps!

P. S: [Here](https://gist.github.com/peanutbutterandcrackers/f0f666243133e0ed25abbc12a4ba23d7) is a guide to go from zero to hero in OpenShot! Happy Editing!

**Comment by FrozenPuppet** [comment]
That's exactly what I was looking for. Thanks!

**Comment by marcelkloes** [comment]
Hi,

I am trying to add titles (text below my images and video,) but so far it doesn't work. I try to drag a title into  my track or image, but nothing happens. Any idea? I am using Windows 10 pro.

**Comment by peanutbutterandcrackers** [comment]
@marcelkloes - You can't drag a title directly in to a track, sir. First you have to save it. It'll then appear in the 'Project Files' tab and then you can drag the project file into the timeline. Hope that helps.
