### ISSUE TITLE
Image sequence export not working

### ISSUE THREAD

**Issue by Algomorph** [OpenShot/openshot-qt#171]
When I try to export as image sequence, I get an .mp4 video file instead. It seems to be using the video/audio settings I've specified. I'm at commit f35bad057e366a8a4f035ece2b5cb7289fbd9684.

**Comment by tonirevert** [comment]
I have the same problem here

**Comment by cjust1** [comment]
I'm also having this issue.

**Comment by ypnos** [comment]
I have this problem with OpenShot 2.2.0

**Comment by fogartycarl** [comment]
Same here V2.2.0  seems to work on my other 32bit Ubuntu 16.04 laptop but my 64bit Ubuntu 16.04 laptop does not have the image sequence option when you right click a clip and when I use the export dialog i get another mp4 file

**Comment by simbalion** [comment]
Same. It appears this is a bug.

**Comment by Dave3of5** [comment]
Any update on this I'm also getting this error. does anyone know what version this regression happened in ?

**Comment by mikeperalta1** [comment]
Same :(

**Comment by johnLIC** [comment]
Me too.  I can not export image sequences from OpenShot-v2.2.0-x86_64.bin in Centos 7.

**Comment by DylanC** [comment]
@Algomorph - Does this issue exist in OpenShot 2.3.4 ?

**Comment by DylanC** [comment]
@Algomorph - I can't find this option. Did this option exist in 2.0 before?

**Comment by ypnos** [comment]
As I had already written here, this feature is present and broken in OpenShot 2.2.

**Comment by DylanC** [comment]
@ypnos - Thanks!

**Comment by khjay1** [comment]
Can confirm.....Arch Linux  has been broken in all 2.X series, functional in 1.X series...... much missed feature

**Comment by khjay1** [comment]
My apologies..... re visited nightly.... working in up to date Archlinux since -                                                                      OpenShot-v2.3.4-3-gfe0f5f8-55-637-x86_64.AppImage 	July 26, 2017, 10:19 p.m.

**Comment by DylanC** [comment]
@Algomorph - Can you or others here try the v2.4 version please?

**Comment by DylanC** [comment]
Closed since it was confirmed working in the daily and it is working for me in v2.4.

**Comment by johnLIC** [comment]
Just for fun I tested OpenShot 2.4.0 in Centos 7.  Image sequence export worked for me.  Yeah!

**Comment by rodmcfall** [comment]
This does NOTwork in windows 10 v2.5.1

**Comment by ThePreviousOne** [comment]
Not working in v3.0.0 either.

**Comment by Colorjet3** [comment]
I just did a test with v3.0.0 daily build #10873 it worked.
Here are the steps during my test:
1.  Start OpenShot.
2.  I created Text title and imported a .jpg file.
3.  I dragged both the title and the .jpg onto track5 snapped together.
4. clicked on Export | Advanced Tab.  Changed "Export to:" to "Image Sequence".
5. clicked on Export Video and it worked.

If you guys are doing something different then please let me know so I can replicate your steps/issue.
