### ISSUE TITLE
Please provide the process to increase video resolution

### ISSUE THREAD

**Issue by testdefteam** [OpenShot/openshot-qt#1710]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by N3WWN** [comment]
You could start a new project, set the profile of the project to one with a higher resolution than the clips that you will be adding, import the clips and then add them to the timeline.  The exported video will conform to the project profile (resolution and frame rate).

If all you want to do is to change the resolution of the clips, this does not really take advantage of the OpenShot feature set.  There are other tools, such as HandBrake and ffmpeg, which are tailored more directly for performing this type of modification, if that's all you're looking to do.
