### ISSUE TITLE
Hello   I wonder if it is possible to save a single frame as a photo in Open shot video editor?   How would I do that?     

### ISSUE THREAD

**Issue by Irefre** [OpenShot/openshot-qt#1711]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by N3WWN** [comment]
Hi @Irefre !

This feature is not part of OpenShot 2.4.1, but PR #1542 PR exists to add this function and will likely be part of 2.4.3.  

It was submitted too late for inclusion in 2.4.2, but perhaps it will be merged for a daily build of 2.4.2 after its official version is published.

**Comment by Irefre** [comment]
Thank you very much for your answer :-)
