### ISSUE TITLE
Crash when trasitioning in preview mode

### ISSUE THREAD

**Issue by ruffieuxh** [OpenShot/openshot-qt#1714]
**Describe the bug**
I today reviewed my entire video and went through many transitions between track 0 and 1. When the first transition between track 0 and 2 came up, it stopped and then crashed.

**System Details (please complete the following information):**
 - Operating System / Distro: Ubuntu 16.04
 - OpenShot Version: 2.4.2-rc4

**To Reproduce**
1. Preview a video with 3 tracks
2. Run through a transition from track 0 to track 2

**Expected behavior**
No crash during any transition

**Screenshots**
None

**Logs**
Attached
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/2118533/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2118534/openshot-qt.log)

**Comment by ruffieuxh** [comment]
Another example for the crash
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/2118676/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2118677/openshot-qt.log)

**Comment by ruffieuxh** [comment]
Hi,

I am clearly doing both within the track and between tracks. And yes, it mostly crashes between tracks. 

How would I then do a nice transition between tracks? I think I got the idea from you introduction videos. :-)

Please find attached a screenshot requested.
![bildschirmfoto vom 2018-06-24 17-48-55](https://user-images.githubusercontent.com/12776226/41820778-24323e28-77d7-11e8-942b-88ca8afc0b57.png)

**Comment by peanutbutterandcrackers** [comment]
Hmm... I see. It seems you have put videos that you want to show in lower tracks. Which is not how OpenShot works. We should put videos in the upper tracks... It's like stacking a bunch of see-through pages on top of each other.

Please go through [this guide](https://gist.github.com/peanutbutterandcrackers/f0f666243133e0ed25abbc12a4ba23d7) to go from zero to hero in OpenShot. Maybe then you'll see what you can do to fix it. Hope that helps! :+1:

**Comment by DylanC** [comment]
@ruffieuxh Can you try v2.4.2 and let us know if you have any success?

**Comment by ruffieuxh** [comment]
Ran the exact same video in preview mode over 50mins including several dozens of transitions and it did not crash once, despite I ran heavy number crunching in parallel (by intention). Well done!!

**Comment by peanutbutterandcrackers** [comment]
Awesome! Closing this as resolved!
