### ISSUE TITLE
Openshot only using one core

### ISSUE THREAD

**Issue by Sjorsa** [OpenShot/openshot-qt#1715]
When I try to drag a clip (or even an image) around, it takes about ten seconds before I can do anything. this makes editing very tedious. I noticed in task manager only one core is being used 100%, the other ones only +-10%. I've looked around, but can't find more info about this. Thanks in advance!

Ryzen 5 1600 6C/12T
GTX 1060 6GB
Windows 10 64bit

**Comment by DylanC** [comment]
@Sjorsa - I would recommend to try a daily build. We have RC builds for v2.4.2 which are much better and use all cores.
