### ISSUE TITLE
Installation fails via PPA

### ISSUE THREAD

**Issue by sk8nfool** [OpenShot/openshot-qt#1719]
Installation fails when I follow instructions on https://www.openshot.org/ppa/ when I try to execute
    sudo apt-get update
with the message
    E: The repository 'http://ppa.launchpad.net/openshot.developers/ppa/ubuntu bionic Release' does not have a Release file.

**Comment by DylanC** [comment]
@sk8nfool - I think the PPA is kinda broken at the moment due to updates on our build pipeline. Sit tight and hopefully it will be fixed. 😄

**Comment by DylanC** [comment]
@sk8nfool - Try the PPA again. Should be back up and running.
