### ISSUE TITLE
Can't open project from 1.4.3

### ISSUE THREAD

**Issue by abject** [OpenShot/openshot-qt#172]
I recently upgrade OpenShot from 1.4.3 to 2.0.7 and I can't open my projects file.

I get the following error message:

`Failed to load project file /path/to/my/projects.osp: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)`

It seems to have a problem with the file decoding.

There is already a bug open in Launchpad about this error: https://bugs.launchpad.net/openshot/+bug/1568511

**Comment by mosteo** [comment]
I'm hitting this problem too, but in addition I cannot see any character in the project file that couldn't be encoded with plain ascii?

**Comment by PostPollux** [comment]
It's exactly the same here! 
`
Failed to load project file /run/media/johannesw/SAMSUNG/trailer01.osp: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)`

I really don't see any character in the path, that couldn't be encoded in ascii. Any Ideas? I'm using OpenShot V 2.1.0

**Comment by xintrea** [comment]
Same problem. Cant open project from 1.4.3 in OpenShot 2.1.0.

Error:

`Failed to load project file /media/wd_2000_part_1/filecollection/Video/MyTetraVideo/2016-10-15/montage/MyTetra v.1.42 Обзор 54 2x.osp: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)`

I try convert *.osp file from x-esc-entities to real UTF-8 in S (string?) tag. Result difference for this files:

```
$ diff before.osp after.osp 
51c51
< S'\xd0\x9f\xd0\xbe\xd1\x81\xd0\xbb\xd0\xb5\xd0\xb4\xd0\xbe\xd0\xb2\xd0\xb0\xd1\x82\xd0\xb5\xd0\xbb\xd1\x8c\xd0\xbd\xd0\xbe\xd1\x81\xd1\x82\xd1\x8c \xd0\xbf\xd0\xbe-\xd1\x83\xd0\xbc\xd0\xbe\xd0\xbb\xd1\x87\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x8e 1'
---
> S'Последовательность по-умолчанию 1'
301c301
< S'\xd0\x97\xd0\xb2\xd1\x83\xd0\xba\xd0\xbe\xd0\xb2\xd1\x8b\xd0\xb5 \xd1\x8d\xd1\x84\xd1\x84\xd0\xb5\xd0\xba\xd1\x82\xd1\x8b'
---
> S'Звуковые эффекты'
... etc ...
```

But error already show.

**Comment by xintrea** [comment]
Nota bene:

Watch look on console output: In json_data we have position 597. In project_data we have position 0.

**Comment by yohanboniface** [comment]
Same issue here. Any known workaround?

**Comment by tom4tom** [comment]
Same here, with my project (on Ubuntu 16.04 an WIN10):
osp: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)

**Comment by jreynojustin** [comment]
The OSP file format changed significantly from V1 to V2. The old format is not supported unfortunately. We may add an import integration depending on feature demand.

**Comment by yohanboniface** [comment]
I'm interested in such import, or at least any information that can help me migrate my project (even by scripting on my side or such). Thanks!

**Comment by jreynojustin** [comment]
@jonoomph Thoughts on this?

**Comment by yohanboniface** [comment]
Any chance to hints on how to do that by scripting myself?
