### ISSUE TITLE
Bug at the start of the video

### ISSUE THREAD

**Issue by Francysun** [OpenShot/openshot-qt#1723]
Problems with the first slide.
In the first slide the image and audio jump and jerk. After the first, it resumes normally and the video is fluid. Besides, it's also very slow and I have to wait a long time to make a single change.

**System Details (please complete the following information):**
 - Operating System / Distro: Windows 10
 - OpenShot Version 2.4.1

**To Reproduce**
1. I try to modify the first slide
2. Click right mouse
3. Scroll down to 'remove transition or remove picture/audio'
4. At the first, the software is blocked, than delete the elements and when I watch if it's solved, the problem persist.

**Expected behavior**
I expect that solve the jump and jerk at the start of clip

**Screenshots**
![screenshot_openshot](https://user-images.githubusercontent.com/40488837/41769455-9a6da434-760f-11e8-901b-3e5b79572bb1.jpg)

**Comment by peanutbutterandcrackers** [comment]
Version `2.4.2` will be out soon, with a lot of improvements. Perhaps this issue has been resolved in the RC-builds, already. You could try out the Release Candidates over at daily builds section of the download page over at http://openshot.org/download

**Comment by DylanC** [comment]
@Francysun Can you try v2.4.2 and let us know if you have any success?
