### ISSUE TITLE
MacOS Blender for Animated Titles Not Working

### ISSUE THREAD

**Issue by SquidyProductions** [OpenShot/openshot-qt#1724]
For some reason I can't use the Animated Title feature. I have put in the path correctly but it doesn't work. I don't know if this is a bug or if this is just what I'm doing. I downloaded Blender for MacOS and copied the path to the application I downloaded and it didn't work. 

I am using **macOS** High Sierra Version 10.13.5

**Comment by peanutbutterandcrackers** [comment]
[Here](https://github.com/OpenShot/openshot-qt/issues/1400) is a good tutorial showing how to fix this issue (posted by another kind user). Hope that helps!

**Comment by DylanC** [comment]
@SquidyProductions Can you try v2.4.2 and let us know if you have any success?
