### ISSUE TITLE
erro ao iniciar o open shot 

### ISSUE THREAD

**Issue by Coxinha25** [OpenShot/openshot-qt#1725]
Ao abrir o open shot, aparece o erro ''Arquivo KEYI(QD2L89)Ausente
                                                            2018-05-29 15-39-50.mp4 nao pode ser encontrado''

**System Details (please complete the following information):**
- windows 10
-processador icore i5

como posso solucionar este problema?

![image](https://user-images.githubusercontent.com/40527012/41813129-50ceec0a-7706-11e8-8743-429033f53c83.png)

**Comment by peanutbutterandcrackers** [comment]
Perhaps the file has been moved to some place else from where it was before, good sir. Please make sure the file is in the same place where it was when the `.osp` file (the OpenShot project) was saved.
