### ISSUE TITLE
Cannot import HEVC file on 2.4.1/2.4.2rc6 on WIndows 10

### ISSUE THREAD

**Issue by tomck** [OpenShot/openshot-qt#1728]
**Describe the bug**
I can open this file from my NVR in VLC but not OpenShot
[HEVC-fail-file.zip](https://github.com/OpenShot/openshot-qt/files/2130541/HEVC-fail-file.zip)

**System Details (please complete the following information):**
 - Operating System / Distro: Windows 10 x64
 - OpenShot Version: 2.4.1

**To Reproduce**
1. Click Green + icon to add file
2. Select the AVI attached to this post
3. ???
4. See error "not a valid ... file"

**Expected behavior**
File to be added to media library for editing

**Screenshots**
Unnecessary

**Logs**
Where would I find these for a file not being valid?

**Additional context**
From an easternCCTV NVR, can get model if it matters but I think the cameras themselves provide raw H.265

**Comment by peanutbutterandcrackers** [comment]
I can confirm that this is an issue. OpenShot does not support HEVC encoded files. And, after taking a look at [Wikipedia](https://en.wikipedia.org/wiki/High_Efficiency_Video_Coding), I doubt it will ever happen.

> Like its predecessor AVC, software which implements HEVC must pay a price per distributed copy.† While this licensing model is unproblematic for paid software, it is an obstacle to most free and open-source software, which is crucially meant to be freely distributable. In the opinion of MulticoreWare, developers of x265, enabling royalty-free software encoders and decoders is in the interest of accelerating HEVC adoption.[168][172][173] HEVC Advance made an exception that specifically waives the royalties on software-only implementations (both decoders and encoders) when not bundled with hardware.[174] However, the exempted software is not free from license obligations until also exempted by MPEG LA and Technicolor.
>While the obstacle to free software is no concern in for example TV broadcast networks, this problem, combined with the prospect of future collective lock-in to the format, makes several ideal organizations like Wikipedia,[175] Mozilla (see OpenH264), and the Free Software Foundation Europe[176] wary of royalty bearing formats for internet use. Competing formats intended for internet use (VP9 and the upcoming AV1) steer clear of these concerns by being royalty-free.
>^† : Regardless of how the software is licensed from the software authors (see software licensing), if what it does is patented, it is (additionally) bound by the patent holders' licenses.

**Comment by peanutbutterandcrackers** [comment]
I was unable to transcode the video using [HandBrake](https://handbrake.fr/) or [ffmpeg](https://ffmpeg.org/). However, [VLC](https://www.videolan.org/vlc/download-windows.html) was able to transcode it perfectly into `.mkv` file which I was then able to import into OpenShot!
![screenshot from 2018-06-24 14 34 32](https://user-images.githubusercontent.com/26764547/41817498-c81e301c-77bb-11e8-9923-97bc845d14e2.png)

**Comment by peanutbutterandcrackers** [comment]
If you're a geek, you could [try transcoding like this](https://wiki.videolan.org/Transcode), using VLC.

An easier way would be [this](https://www.youtube.com/watch?v=1jMuRnMSQoU).

Once the conversion is done, use the exported file to import into OpenShot and edit.

Hope that helps!

All the very best! :+1:

**Comment by peanutbutterandcrackers** [comment]
@rugubara - Sorry for the tardy reply. Hmm... that is strange... I should probably look something up, then. However, for the time being, I suggest you transcode the original footage to `.mkv` using [HandBrake](https://handbrake.fr) to make it editable. Sorry for the inconvenience...

**Comment by peanutbutterandcrackers** [comment]
@DylanC - Cap'ain, do you have any ideas why it is so? o.O

**Comment by DylanC** [comment]
@tomck - Following discussion on issue #1408, can you try to import the same video in Openshot v2.4.3?
