### ISSUE TITLE
Video preview does not work

### ISSUE THREAD

**Issue by vk4tnt** [OpenShot/openshot-qt#1729]
**Describe the bug**
The video preview does not work. When I import a wmv video file I created when Windows still had a Movie Maker, the project shows the first frame of my video but when I click play, it still only shows the first frame. The audio progresses nicely just the video does nothing. My only intention is to cut a few sceness out of the video. Please advise
**System Details (please complete the following information):**
 - Operating System / Distro: Windows 10
 - OpenShot Version: 2.4.1

**To Reproduce**
as above
**Expected behavior**
Video plays and lets me place the slider to where I want to cut the video

**Screenshots**
N/A
**Logs**
N/A
**Additional context**
N/A

**Comment by peanutbutterandcrackers** [comment]
It might be because of the `.wmv` container. Please try to use [HandBrake](https://handbrake.fr/) to convert the video into some other container like `.mkv`. That should make it work. Hope that helps! :+1:

**Comment by vk4tnt** [comment]
Thanks for that. It worked, with the exception that HandBrake didn't convert my whole file. Never mind, I will investigate into the matter.
Thanks again ;-)

**Comment by peanutbutterandcrackers** [comment]
You could also use [VLC](https://www.videolan.org/vlc/download-windows.html), it's a really good swiss-army knife for all things video related. [Here](https://www.guidingtech.com/8848/use-vlc-player-to-convert-videos-from-one-format-to-another/) is how you convert videos using VLC.

Hope that helps!

**Comment by DylanC** [comment]
@vk4tnt Can you try v2.4.2 and let us know if you have any success?
