### ISSUE TITLE
What app should be used for opening an osp file? My first videos were mp4, but  now they're osp.

### ISSUE THREAD

**Issue by treetopper1** [OpenShot/openshot-qt#1730]

**Comment by DylanC** [comment]
@treetopper1 - Openshot should be used to open the .osp files. (Openshot project files - .osp)

**Comment by peanutbutterandcrackers** [comment]
Also, when you are done editing and you finally export it, you can have the `.mp4` (or `.mkv`, etc) file. :)

`.osp` : OpenShot Project :+1: 

Hope that helps!

**Comment by peanutbutterandcrackers** [comment]
Also, when you are done editing and you finally export it, you can have the `.mp4` (or `.mkv`, etc) file. :)

`.osp` : OpenShot Project :+1: 

Hope that helps!

P. S: You might also want to go through [this guide](https://gist.github.com/peanutbutterandcrackers/f0f666243133e0ed25abbc12a4ba23d7) to go from zero to hero in OpenShot. :+1:
