### ISSUE TITLE
openshot under wine installation probs

### ISSUE THREAD

**Issue by bobcrikey** [OpenShot/openshot-qt#1732]
Hello everyone , look what happened when i tried to run openshot -rc6 win 64 version
under wine for linux. 

i'd like to know is where did those chinese writings come from when im installing an english exe.
too weird, it also didnt run.maybe i should had tried the 32bit version but

its very interesting isnt :)
![where did this come from](https://user-images.githubusercontent.com/40479177/41882974-4dde9ba0-792f-11e8-86cc-ac3c8ec1caeb.jpg)

**Comment by peanutbutterandcrackers** [comment]
Hmm... It would be nice if we could work into resolving this. But since OpenShot is directly available on Linux Distros (and works best on them), I think this won't be quite the priority. Perhaps this would be an issue for the Wine devs, instead? But thank you for pointing this out.

**Comment by DylanC** [comment]
@peanutbutterandcrackers - Yes, I think this really would be the lowest of priority. 😆
