### ISSUE TITLE
RunTime error Microsoft Visual C++ on launch

### ISSUE THREAD

**Issue by dubblel** [OpenShot/openshot-qt#1733]
Was in the middle of editing a video and during a video preview, the program crashed giving me the RunTime Error. This has happened before but I was always allowed to re-open the program and continue on. This time however, every time I launch the program, it immediately crashes and gives me the runtime error message. I cannot get back into the program.

**System Details (please complete the following information):**
 - Operating System is Windows 7 Pro
 -This happened with the latest daily build of OpenShot from June 21st.  Because this kept happening I tried a couple of the ones immediately preceding the current build, but to no avail.

**To Reproduce**
1. Go to openshot
2. Right Click on openshot
3. Scroll down to open

**Expected behavior**
immediate runtime error and forces me to close the program

**Screenshots**

**Logs**
not sure how to do this.....

**Comment by peanutbutterandcrackers** [comment]
[This](https://github.com/OpenShot/openshot-qt/blob/develop/CONTRIBUTING.md) is how you attach the logs. Please delete the `.openshot_qt` folder first and then restart OpenShot (and recreate the crash). Doing so would give us a very succinct log that will have exactly the clues as to how the crash is occurring and will help the devs fix it. Hope that helps. Looking forward to seeing the logs. All the very best. :+1:

**Comment by dubblel** [comment]
Thanks for the info on how to create logs!

I managed to get past the issue. Seems the video clip I was working on was the issue as it crashed during editing and was unsaved. 

When I reopened the program it opened the back up file to get me back where I was, but where I was was causing the crash. 

So I deleted the clip I was using and it got me back and running. 

I had been using the clip in another project and when I got back to that project the program recognized that I was missing the file and would crash at that point during an export. 

I noticed when I opened the project initially, there was a stretch in a 3 min portion where it thought there was a 5 min clip within it (which was the missing buggy clip I had deleted to get back into the program). 

Once I stretched the timeline, everything settled back into place and was working as expected.

**Comment by peanutbutterandcrackers** [comment]
I see. Awesome! I'm glad that it's working for you. Hope you create awesome videos with OpenShot! Please do look forward to future versions of OpenShot - they will come with tons of performance and stability fixes!

**Comment by peanutbutterandcrackers** [comment]
May I close this issue now?

**Comment by dubblel** [comment]
Yes. Thanks again for your info.
