### ISSUE TITLE
jerky timeline resolution

### ISSUE THREAD

**Issue by Sameroney** [OpenShot/openshot-qt#1734]
Hello,
i downloaded openshot to edit and render videos in 2.7k and 4k.
But the video in the timeline is very slow and jerky … I think my PC just is not good enough … is it possible to reduce the quality of the video (in the timeline), so i can work fluent?
If I render the video, it should be in good quality afterwards…

Besides, can you suggest any good basic tutorial? Videos from Youtube?
Greetings from Germany,
Johannes

**Comment by DylanC** [comment]
@Sameroney Can you try v2.4.2 and let us know if you have any success?
