### ISSUE TITLE
Freeze when move in timeline

### ISSUE THREAD

**Issue by Petr-Ledvina** [OpenShot/openshot-qt#1736]
Openshot 2.4.1: I add video to time line, move in time to e.g. 50% of length of video. Click play video: OK. Than move in timeline to e.g. 40%. Click to play video: video have frozen. In old Openshot 1.4.3 no problem with the same video.
**System**
Ubuntu 16.04, Intel Core i7, 8G RAM
**To Reproduce**
- Open new project, import one video file (1 file, 10 GB, 80 minutes, codec: H264,1920x1080,50fps + sound mpeg aac)
- add video to timeline
- run video from preview: no problem with screen and with sound
- move in time line e.g. to 50. minutes. Play in preview window: no problem
- move in time line e.g. to 40. mintues. Click "play" in preview window: Video have frozen.

**Expected behavior**
Video is playing and I can continue e.g. with cutting scenes.

**Comment by peanutbutterandcrackers** [comment]
I would suggest that you [switch to the latest daily builds](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914). There have been a ton of improvements in OpenShot since version 2.4.1. Also, if you're into stable releases only, you could wait for version 2.4.2 - which should be out really soon!

**Comment by jabowery** [comment]
Is there a more recent Windows build?

**Comment by DylanC** [comment]
@Petr-Ledvina Can you try v2.4.2 and let us know if you have any success?

**Comment by Petr-Ledvina** [comment]
I have just tried new version  2.4.2, but unfortunately video have frozen again.

**Comment by peanutbutterandcrackers** [comment]
@Petr-Ledvina - Good sir, could you please [attach the logs](https://gist.github.com/peanutbutterandcrackers/d84c257e74b72d8b06b4daffaebc5a14) and also attach details about the media file by using [MediaInfo](http://mediaarea.net/MediaInfo)? Thanks!

**Comment by Petr-Ledvina** [comment]
So, here is a log
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2160681/openshot-qt.log)
and here is a media log: 
[media_info_frozen_in_OS_2_4_2.txt](https://github.com/OpenShot/openshot-qt/files/2160701/media_info_frozen_in_OS_2_4_2.txt)

**Comment by peanutbutterandcrackers** [comment]
Thank you! We'll try to fix this issue as soon as possible. Also, you seem to have forgotten the libopenshot.log. Could you please attach that too (or try again with both openshot-qt.log and libopenshot.log)? Sorry for the inconvenience.

**Comment by Petr-Ledvina** [comment]
So the missing log: [libopenshot.log](https://github.com/OpenShot/openshot-qt/files/2163854/libopenshot.log) (but it`s look almost empty).

**Comment by peanutbutterandcrackers** [comment]
Thank you! Hope we can get this resolved in the upcoming releases! :+1:
