### ISSUE TITLE
Program freezes when loaded or playing video from Campark Action Cam ACT740

### ISSUE THREAD

**Issue by BobcatArts** [OpenShot/openshot-qt#1737]
**Describe the bug**
Loading video from a Campark Action Cam ACT 740 causes the program to freeze when I try to play. Video will work if opened in ShotCut and then just saved again. 

**System Details (please complete the following information):**
Windows 10.  Openshot version 2.4.1-x86-64

**To Reproduce**
1- load video file from Campark to project.
2- Drag to Track
3- Play

**Expected behavior**
File should play, instead Freezes (Not Responding).

**Comment by peanutbutterandcrackers** [comment]
I would like to suggest that you try out the [latest daily build](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914). There have been tons of improvements in the daily builds. Hope that helps!

**Comment by BobcatArts** [comment]
I tried that first thing and no dice!

**Comment by peanutbutterandcrackers** [comment]
@BobcatArts - Could you please then try [attaching the logs](https://github.com/OpenShot/openshot-qt/blob/develop/CONTRIBUTING.md) so that we can try to figure out what exactly is causing the freeze? "No dice" means "No luck", right? Or has this issue been resolved? o.O

**Comment by BobcatArts** [comment]
Issue has not been resolved. Logs are attached, I think? I'm very new at this stuff. 
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2146339/openshot-qt.log)

**Comment by DylanC** [comment]
@BobcatArts - What video format are you working with? Looks like the freeze happens on track drop rather than the Play action. By the time you try to Play I think its already frozen or in a frozen state.

**Comment by peanutbutterandcrackers** [comment]
You might also want to try v2.4.2 which was out this morning, @BobcatArts. So, has this issue been resolved, good sir?

**Comment by BobcatArts** [comment]
Nope. I just installed v2.4.2 to try it with MP4 video from my Campark and it froze immediately like before. It will not work with MP4 from this device for whatever reason.

**Comment by peanutbutterandcrackers** [comment]
@BobcatArts - Good sir, could you please do the following things?
1. Please use [MediaInfo](http://mediaarea.net/MediaInfo) to get all the info that you can, about the video file and paste it in the comments here.
2. Please [attach the logs](https://gist.github.com/peanutbutterandcrackers/d84c257e74b72d8b06b4daffaebc5a14) in case of crash.

That should really help us help you.
