### ISSUE TITLE
openshot not starting on mac os X

### ISSUE THREAD

**Issue by softmasters** [OpenShot/openshot-qt#174]
Hello,
I've just downloaded and installed openshot 2.0.7 beta on my mac 10.6.8 (with intel core 2 duo @2.4GHz cpu).
When I click the openshot icon in applications, the icon in the application bar starts bouncing and then disappears after a few seconds.
The program never starts.
Thank you.

**Comment by nanoSpawn** [comment]
Same here with latest beta as of juny the 14th. MacOS X 10.6.8 on a Imac Intel i3

Unfortunately, upgrading to El Capitán is not possible for the moment being.

**Comment by jreynojustin** [comment]
OpenShot is now in Version 2.2 if you are still noticing issues in the latest version please re-open this issue letting us know.
