### ISSUE TITLE
How do I generate the logs?

### ISSUE THREAD

**Issue by cinlouval** [OpenShot/openshot-qt#1742]
Dont understand how to do this for submission with crash report

**Comment by DylanC** [comment]
@cinlouval - Follow suggestion by @peanutbutterandcrackers. Closing question as answered but do let us know if this worked.

**Comment by cinlouval** [comment]
Good day

I did as instructed - deleted the files and re-ran the process.  I saw the
file generating up to roughly 65% before it crashed and software closed on
its own.

There is a file (blue highlight in first image) but when I tried to open,
it seemed as though it would but then the following message (image) came up.

Log files attached.

Looking out for your reply.

Thanks
CV


















Yours sincerely

Cindy-Lou Valentine

Mobile: 18687359018
Website: http://www.cindylouvalentine.com
Email: cindylouvalentinephotos@gmail.com

*Live the moment...Be the Moment!*

Photos submitted via email or other media :  ©Cindy-Lou Valentine, All
rights reserved.

**Comment by cinlouval** [comment]
Hello Dylan...How do I change the subject to more appropriate wording? I re-opened the issue but it now relates to Openshot crashing during export of recording.

Rgds
Cindy

**Comment by cinlouval** [comment]
I deleted the qt files again and tried output to a different format which I
opened under a new issue.

Should I close this one?



Yours sincerely

Cindy-Lou Valentine

Mobile: 18687359018
Website: http://www.cindylouvalentine.com
Email: cindylouvalentinephotos@gmail.com

*Live the moment...Be the Moment!*

Photos submitted via email or other media :  ©Cindy-Lou Valentine, All
rights reserved.

**Comment by DylanC** [comment]
@cinlouval - I will close this one for you. Since your original question about the logs has been answered. :) In the future if you want to just change the title you should see an "Edit" button on the right side of your issue title.

**Comment by cinlouval** [comment]
Cool...thanks



Yours sincerely

Cindy-Lou Valentine

Mobile: 18687359018
Website: http://www.cindylouvalentine.com
Email: cindylouvalentinephotos@gmail.com

*Live the moment...Be the Moment!*

Photos submitted via email or other media :  ©Cindy-Lou Valentine, All
rights reserved.
