### ISSUE TITLE
Issue with openShot and FLAC export (Windows 7)

### ISSUE THREAD

**Issue by nicolardot** [OpenShot/openshot-qt#1743]
Hello,

Congratulation for this nice work : openShot !

I wanted to export a video with a nice quality of sound, so with lossless audio. Is FLAC the only way to do this ?

I have just begun with openShot yesterday, with the objective of keeping a video archive for high quality musical recording, and also if possible a HD video.

So I have a HD video on a track, and a PCM audio track of good quality. I tryed to export the result in a lossless format, OGG(theora, FLAC). The vorbis format doesn't produce a crash of openShot, but  OGG(theora, fla) does (Windows 7 pro). Is the FLAC codec responsible of this ? The other parameters were 1080i 25fps, 48000 Hz and stereo. Mp4 h.264 works well.

I thank you very much if you can help me !

marc.nicolardot@yahoo.fr

**Describe the bug**

**System Details (please complete the following information):**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**

**Comment by nicolardot** [comment]
I would like to have some help for export crash with ogg(theora/flac), windows 7

**Comment by nicolardot** [comment]
I would like to have some help after a crash with ogg(theora/flac) export with openShot (windows 7 pro)

**Comment by peanutbutterandcrackers** [comment]
@nicolardot - Hey there! Sorry for the tardy reply. Could you please try out the latest stable version of OpenShot (v2.4.2) which was out just this morning? http://openshot.org/download Perhaps that will solve it? Even if it doesn't, we can look into it together and try to figure out what is going wrong. Hope that helps!

**Comment by DylanC** [comment]
@nicolardot Can you try v2.4.2 and let us know if you have any success?

**Comment by nicolardot** [comment]
Sorry for this bad news, openShot has crashed after 0.1 % export with FLAC codec. Do you have an idea for how I could test if the problem is related to the codec ? What should be the audio bit rate (asked by openShot) for an lossless with FLAC codec ?
Thank you very much for your help !
Marc Nicolardot

    Le dimanche 1 juillet 2018 à 05:20:09 UTC+2, peanutbutterandcrackers <notifications@github.com> a écrit :  
 
 
@nicolardot - Hey there! Sorry for the tardy reply. Could you please try out the latest stable version of OpenShot (v2.4.2) which was out just this morning? http://openshot.org/download Perhaps that will solve it? Even if it doesn't, we can look into it together and try to figure out what is going wrong. Hope that helps!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
   

    Le lundi 2 juillet 2018 à 12:15:39 UTC+2, DylanC <notifications@github.com> a écrit :  
 
 
@nicolardot Can you try v2.4.2 and let us know if you have any success?

**Comment by nicolardot** [comment]
Sorry for this bad news, openShot has crashed after 0.1 % export with FLAC codec. Do you have an idea for how I could test if the problem is related to the codec ? What should be the audio bit rate (asked by openShot) for an lossless with FLAC codec ?
Thank you very much for your help !
Marc Nicolardot

    Le dimanche 1 juillet 2018 à 05:20:09 UTC+2, peanutbutterandcrackers <notifications@github.com> a écrit :  
 
 
@nicolardot - Hey there! Sorry for the tardy reply. Could you please try out the latest stable version of OpenShot (v2.4.2) which was out just this morning? http://openshot.org/download Perhaps that will solve it? Even if it doesn't, we can look into it together and try to figure out what is going wrong. Hope that helps!

**Comment by peanutbutterandcrackers** [comment]
Hmm.... @gary9872 or @N3WWN might be able to give some insight here.

@nicolardot - Sorry for the inconvenience, good sir. We'll try to get this fixed, ASAP.

@DylanC - Perhaps this also needs some testing to see if this is reproducible?

**Comment by DylanC** [comment]
@peanutbutterandcrackers - Tried this on Windows 10 since I don't have Windows 7. FLAC export is working for me.

**Comment by nicolardot** [comment]
Thank you for your help. I tried with your version of openShot on an other windows 7 computer FLAC export HDV 1080 25i 1920x1080 with both OGG(theora/flac) and OGG(theora/vorbis) options. Both exports failed. With my other computer, OGG(theora/vorbis) succeded after codex loading. So I think it could be a codex problem. Could you give me indication in order to load a good OGG(theora/flac) codex ?
Best regards,
Marc Nicolardot

    Le samedi 28 juillet 2018 à 13:39:41 UTC+2, DylanC <notifications@github.com> a écrit :  
 
 
@peanutbutterandcrackers - Tried this on Windows 10 since I don't have Windows 7. FLAC export is working for me.

**Comment by DylanC** [comment]
Dup of #1480
