### ISSUE TITLE
Error when opening project

### ISSUE THREAD

**Issue by BerndVME** [OpenShot/openshot-qt#1748]
I get the error 'NoneType' object has no attribute 'get' and sometimes I also get the issue that he tells me he cannot create thumbnail because it already exists (I rename the folder and its ok again). -> [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\Bernd PC\\.openshot_qt\\thumbnail' Please help thx

**Comment by peanutbutterandcrackers** [comment]
Ummm..... For one user, he opened the `.osp` file in a text editor and deleted two `none`s that were out of place. I wonder if you could try that as well...

But perhaps give OpenShot version 2.4.2 (the latest one released this morning) a try first. Perhaps that'll help?

**Comment by DylanC** [comment]
@BerndVME Can you try v2.4.2 and let us know if you have any success?
