### ISSUE TITLE
Chroma Key Effect not active on last Frame

### ISSUE THREAD

**Issue by overdetermined** [OpenShot/openshot-qt#175]
Hi there,

I'm just trying out openshot, and it seems to me that (at least for the Chroma Key effect) it is not active on the lst frame. I am importing a *.flv file from which I am extracting a pink color, on a background track I have a black image. This works perfectly except for the last frame.

Am I doing something wrong? 
Im using version 1.4.3 on arch-linux.

Thanks
val

**Comment by DylanC** [comment]
@overdetermined - Do you still experience this problem?

**Comment by DylanC** [comment]
@overdetermined - Closing this ticket since it relates to 1.4.3.  Development is focused on the v2 series now.

**Comment by Betka-H** [comment]
getting the same problem
most of the video has the transparent bg, but the last 4 frames have a black color where it would be transparent

**Comment by Colorjet3** [comment]
Hello @Betka-H 
What version of OpenShot are you running and in what operating system/version environment?
