### ISSUE TITLE
Not responding

### ISSUE THREAD

**Issue by Stil57** [OpenShot/openshot-qt#1750]
I got to many Not responding while im using it it seems a great editting software but cant really try it out like that

**Comment by DylanC** [comment]
@Stil57 - If you are using Windows and OpenShot v2.4.1 I would recommend you try a daily build for a better experience. Also you could wait until v2.4.2 is released and try that version.

**Comment by peanutbutterandcrackers** [comment]
Version 2.4.2 is already out! Please try it out: https://www.openshot.org/download/

**Comment by DylanC** [comment]
@Stil57 Can you try v2.4.2 and let us know if you have any success?

**Comment by Stil57** [comment]
Sure i'm on it
________________________________
Από: DylanC <notifications@github.com>
Στάλθηκε: Δευτέρα, 2 Ιουλίου 2018 1:16 μμ
Προς: OpenShot/openshot-qt
Κοιν.: Stil57; Mention
Θέμα: Re: [OpenShot/openshot-qt] Not responding (#1750)


@Stil57<https://github.com/Stil57> Can you try v2.4.2 and let us know if you have any success?

**Comment by Stil57** [comment]
i've been trying it out for like 4 days and it's ok i mean much better not trying to respond and stuff but i got some issues with the audio everytime i export my  project the last 2 seconds are like completely destroyed (audio)
________________________________
Από: Antonis Papaemmanouhl <stil_57@hotmail.gr>
Στάλθηκε: Δευτέρα, 2 Ιουλίου 2018 1:22 μμ
Προς: OpenShot/openshot-qt; OpenShot/openshot-qt
Κοιν.: Mention
Θέμα: Απ: [OpenShot/openshot-qt] Not responding (#1750)

Sure i'm on it
________________________________
Από: DylanC <notifications@github.com>
Στάλθηκε: Δευτέρα, 2 Ιουλίου 2018 1:16 μμ
Προς: OpenShot/openshot-qt
Κοιν.: Stil57; Mention
Θέμα: Re: [OpenShot/openshot-qt] Not responding (#1750)


@Stil57<https://github.com/Stil57> Can you try v2.4.2 and let us know if you have any success?

**Comment by peanutbutterandcrackers** [comment]
I see. Could you please also [attach the logs](https://gist.github.com/peanutbutterandcrackers/d84c257e74b72d8b06b4daffaebc5a14)? That should help the devs figure out what is going on behind the scenes.

**Comment by DylanC** [comment]
@Stil57 - Can you try v2.4.3? Its much more stable.
