### ISSUE TITLE
Problem with exporting a video. Error: Sorry, there was an issue exporting your vide. Could not open or write a file.

### ISSUE THREAD

**Issue by malaoudi** [OpenShot/openshot-qt#1754]
When I click on export, as MP4 or other forms, it brings this error. 
Error: Sorry, there was an issue exporting your vide. Could not open or write a file.

**Comment by peanutbutterandcrackers** [comment]
That is strange. Are you perhaps using windows? Maybe this has something to do with permissions. Could you please attach a screenshot? That should help us understand the situation better. I, myself, have never really ran into this issue.

Also, version 2.4.2 is out: https://www.openshot.org/download/ Perhaps using that will solve it.

Hope that helps! :+1:

**Comment by DylanC** [comment]
@malaoudi Can you try v2.4.2 and let us know if you have any success?
