### ISSUE TITLE
It worked, now it doesn't

### ISSUE THREAD

**Issue by JoshLeGrow** [OpenShot/openshot-qt#1756]
If I load a video clip in, it plays the first half a second, then it crahses. I've been using the editor for months, and this just started happening tonight.

OS: Windows 10
OpenShot Version: 2.4.2

**Comment by peanutbutterandcrackers** [comment]
If you are indeed using version 2.4.2, then please [follow this guide](https://gist.github.com/peanutbutterandcrackers/d84c257e74b72d8b06b4daffaebc5a14) to attach the logs. That should help the devs sort this thing out as fast as possible. Hope that helps! :+1:
