### ISSUE TITLE
How to maintain original layout of recorded video in exports off OpenShot

### ISSUE THREAD

**Issue by coolnani** [OpenShot/openshot-qt#1761]
Thanks a million first for the wonderful editor, **hats off to your efforts**, and for keeping it free!

So, I recorded an HD video on my Android mobile device. It plays full screen on the device in portrait mode. I imported this video to OpenShot, added an audio track and a title PNG and exported it as MP4 (h.264) / HD 1080p 25 fps. This new video just does not play full screen anymore on the device. It shrinks to the center to almost a thumbnail size. 

I have tried:

- distorted layout among other layouts
- different export profiles and resolutions
- even zooming and scaling

Nothing seems to play the exported video full screen on my device, except the title PNG. What am I missing? 

Attached are the self-explanatory, original and the exported video screenshots while they played:

![image](https://user-images.githubusercontent.com/12514805/42138212-4178f088-7d97-11e8-9caf-2e55c5568f26.png)

![image](https://user-images.githubusercontent.com/12514805/42138242-f88e725c-7d97-11e8-8752-906e66883dff.png)

Kindly help, many thanks in advance!

**Comment by coolnani** [comment]
Figured it out! Created a custom video profile like this:

`description=Android video
frame_rate_num=30000
frame_rate_den=1001
width=1080
height=1920
progressive=1
sample_aspect_num=1
sample_aspect_den=1
display_aspect_num=16
display_aspect_den=9`

And with help from [**this video**](https://www.youtube.com/watch?v=k0QzGAaLdqc).

Thanks!

**Comment by DylanC** [comment]
@coolnani - Great news, thanks!
