### ISSUE TITLE
Frozen Frames In 2.4.2

### ISSUE THREAD

**Issue by MisterTeeXD** [OpenShot/openshot-qt#1762]
**Describe the bug**
When a video is exported with no Effects and Transitions are added, frames at the end of the video are frozen.

**System Details (please complete the following information):**
 - Operating System / Distro: Windows 10
 - OpenShot Version: 2.4.2

**To Reproduce**
1. Go to File
1.a: Make sure no effects and transitions are added
2. Click on Export Video
3. Go to file location of the exported video file
4. See error by playing the video file

**Expected behavior**
The last frames will not be frozen

**Screenshots**
[My own intro.zip](https://github.com/OpenShot/openshot-qt/files/2153216/My.own.intro.zip)

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**
I have tested this with multiple formats with no effects and transitions and those frozen frames are still there.

**Comment by peanutbutterandcrackers** [comment]
@DylanC - Cap'ain, I think this needs to be tested and marked as a bug if necessary... (sorry, haven't had the time to do a lot of testing myself these days...)

**Comment by DylanC** [comment]
@peanutbutterandcrackers - As soon as I fix my laptop OS I can test this and all the others. 👍

**Comment by MisterTeeXD** [comment]
When will this issue be fixed?

**Comment by peanutbutterandcrackers** [comment]
This is probably related to https://github.com/OpenShot/libopenshot/issues/122; A patch has already been created by a dev to fix it, it only needs to be applied upstream. So, hopefully, as soon as our BDFL returns. :)

**Comment by MisterTeeXD** [comment]
BDFL ???

**Comment by peanutbutterandcrackers** [comment]
Yes, Mr. Jonathan Thomas. Our [BDFL](https://en.wikipedia.org/wiki/Benevolent_dictator_for_life) :)

**Comment by MisterTeeXD** [comment]
Ok and how do i know what has been changed in the new daily builds?

**Comment by peanutbutterandcrackers** [comment]
There isn't a way to know that, really, except to look at the [commit logs](https://github.com/OpenShot/openshot-qt/commits/develop) and make a few good guesses. The daily build system doesn't publish release notes like the stable builds - even those release notes are polished by humans. Hope that helps!

**Comment by MisterTeeXD** [comment]
Hello, just to clarify, will this issue be closed by a Dev when its fixed, i am waiting patiencely for an update

**Comment by MisterTeeXD** [comment]
I officially declare this Issue FIXED and CLOSED
