### ISSUE TITLE
OpenShot do not open in Windows 10

### ISSUE THREAD

**Issue by JoSBlanes** [OpenShot/openshot-qt#1763]
**Describe the bug**

**System Details (please complete the following information):**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**

**Comment by DylanC** [comment]
@JoSBlanes Can you try v2.4.2 and let us know if you have any success?
