### ISSUE TITLE
Make zoom more gentle when zoomed in (1s -> 2s, instead of 1s -> 7s)

### ISSUE THREAD

**Issue by timlau** [OpenShot/openshot-qt#1765]
**Is your feature request related to a problem? Please describe.**
Zoom step from 1s to 7s it is 7x in one step, that is to much when working with short clips.

**Describe the solution you'd like**
something like 1s, 2s, 4s, 8s, 16s (2x in each step) will be more useful

**Additional context**
![screenshot from 2018-07-02 11-36-38](https://user-images.githubusercontent.com/283985/42157032-eddb6d88-7dec-11e8-897a-a1f94a896690.png)
![screenshot from 2018-07-02 11-37-02](https://user-images.githubusercontent.com/283985/42157034-efbb68b0-7dec-11e8-80ed-96ceef80615e.png)

**Comment by peanutbutterandcrackers** [comment]
Hmm... There is [another thread](https://github.com/OpenShot/openshot-qt/issues/1571) where this issue is also being discussed upon. Perhaps we should put this (or, rather, that) issue as a priority for the 2.4.2.x bug-fix series. Thank you for the report, good sir!

**Comment by peanutbutterandcrackers** [comment]
Kinda' a dup of #1571

**Comment by DylanC** [comment]
@timlau -  #1944 has a fix in for this. The scale is more gentle but not 2x in each step.

**Comment by peanutbutterandcrackers** [comment]
Closing this for now. If there are further developments regarding this issue, please feel free to re-open this. Perhaps we can have something akin to zoom-level-presets #1571 (or maybe just a config file to edit that defines the zoom levels) in the future...
