### ISSUE TITLE
Make properties easier to work with (Grouping etc)

### ISSUE THREAD

**Issue by timlau** [OpenShot/openshot-qt#1766]
**Is your feature request related to a problem? Please describe.**
Working with properties don't give a good user experience, some properties is not useful, like video properties on audio only files. 

**Describe the solution you'd like**

- Related  properties like start, end, duration should be grouped together, same with transformation properties.
- Audio clip should not show video properties.
- Video clips without audio should not show audio properties
- ID properties should not be show, it has value for the end user.
- mouse over text on each properties to tell what it does (what does channel filter and channel mapping  do, etc do ? )

**Comment by timlau** [comment]
For some inspiration check out how it is done in Davinci Resolve 
https://www.youtube.com/watch?v=NiNQ-hRqJd

**Comment by peanutbutterandcrackers** [comment]
@timlau - Hey there! Thank you for your feature request. However, OpenShot just does not have enough volunteers/contributors contributing right now - only a few. And we could use some more. We still have to deal with a lot of stability issues first and deal with the bugs too. So, perhaps, you might want to join us too! It'll be fun. Here: https://www.openshot.org/static/files/user-guide/developers.html We have pretty decent documentation too. And you are most welcome to join us, good sir!
![openshot meme 1 2](https://user-images.githubusercontent.com/26764547/42161818-2755773c-7e1c-11e8-994a-2846ecaf0935.png)

**Comment by timlau** [comment]
It is always an issue in most FLOSS project, to few contributors ;-)
My primary mission is to promote open source video editors, I have started a Youtube series by promoting free video editors by showing the same video made by the mayor free video editors.

https://www.youtube.com/playlist?list=PLYjnIt23wwfAjUeqLk1T1wd3fUqC_vhMR

currently i have made videos of shotcurt, openshot & kdenlive

**Comment by peanutbutterandcrackers** [comment]
Cool; I hope you'll be able to contribute to this project in code, too. :+1:
