### ISSUE TITLE
.mod is not a valid video, audio or image files (?????)

### ISSUE THREAD

**Issue by lutzig** [OpenShot/openshot-qt#1769]
**Describe the bug**
Try to add a video made with my camescope (format .mod) without any success...

**System Details (please complete the following information):**
 - Operating System : X-UBUNTU 18.04 LTS
 - OpenShot Version : 2.4.1

**Expected behavior**
A clear and concise description of what you expected to happen. That video file .mod is running...

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.
      launch:INFO ------------------------------------------------
      launch:INFO    OpenShot (version 2.4.1)
      launch:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.4.1
         app:INFO libopenshot version: 0.1.9
         app:INFO platform: Linux-4.15.0-23-generic-i686-athlon-with-Ubuntu-18.04-bionic
         app:INFO processor: athlon
         app:INFO machine: i686
         app:INFO python version: 3.6.5
         app:INFO qt5 version: 5.9.5
         app:INFO pyqt5 version: 5.10.1
    language:INFO Attempting to load qt_fr_FR.UTF-8 in '/usr/share/qt5/translations'
    language:INFO Successfully loaded qt_fr_FR.UTF-8 in '/usr/share/qt5/translations'
    language:INFO Attempting to load fr_FR.UTF-8/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Attempting to load fr/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Successfully loaded fr/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Qt Detected Languages: ['fr-FR']
    language:INFO LANG Environment Variable: fr_FR.UTF-8
    language:INFO LOCALE Environment Variable: fr_FR
    language:INFO Attempting to load qt_fr_FR.UTF-8 in '/usr/share/qt5/translations'
    language:INFO Successfully loaded qt_fr_FR.UTF-8 in '/usr/share/qt5/translations'
    language:INFO Attempting to load qtbase_fr_FR.UTF-8 in '/usr/share/qt5/translations'
    language:INFO Successfully loaded qtbase_fr_FR.UTF-8 in '/usr/share/qt5/translations'
    language:INFO Attempting to load qt_fr_FR.UTF-8 in '/usr/lib/python3/dist-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load qt_fr in '/usr/lib/python3/dist-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load qtbase_fr_FR.UTF-8 in '/usr/lib/python3/dist-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load qtbase_fr in '/usr/lib/python3/dist-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load fr_FR.UTF-8/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Attempting to load fr/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Successfully loaded fr/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Exiting translation system (since we successfully loaded: fr_FR.UTF-8)
project_data:INFO Setting default profile to HDV 720 24p
         app:INFO Setting font to /usr/lib/python3/dist-packages/openshot_qt/images/fonts/Ubuntu-R.ttf
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
         app:INFO Setting custom dark theme
     ui_util:INFO Initializing UI for MainWindow
     ui_util:INFO Binding event MainWindow:actionNew_trigger
     ui_util:INFO Binding event MainWindow:actionOpen_trigger
     ui_util:INFO Binding event MainWindow:actionSave_trigger
     ui_util:INFO Binding event MainWindow:actionUndo_trigger
     ui_util:INFO Binding event MainWindow:actionSaveAs_trigger
     ui_util:INFO Binding event MainWindow:actionImportFiles_trigger
     ui_util:INFO Binding event MainWindow:actionImportImageSequence_trigger
     ui_util:INFO Binding event MainWindow:actionRedo_trigger
     ui_util:INFO Binding event MainWindow:actionRemoveClip_trigger
     ui_util:INFO Binding event MainWindow:actionRemoveTransition_trigger
     ui_util:INFO Binding event MainWindow:actionExportVideo_trigger
     ui_util:INFO Binding event MainWindow:actionUploadVideo_trigger
     ui_util:INFO Binding event MainWindow:actionAddTrack_trigger
     ui_util:INFO Binding event MainWindow:actionPreferences_trigger
     ui_util:INFO Binding event MainWindow:actionPlay_trigger
     ui_util:INFO Binding event MainWindow:actionJumpStart_trigger
     ui_util:INFO Binding event MainWindow:actionRewind_trigger
     ui_util:INFO Binding event MainWindow:actionFastForward_trigger
     ui_util:INFO Binding event MainWindow:actionJumpEnd_trigger
     ui_util:INFO Binding event MainWindow:actionArrowTool_trigger
     ui_util:INFO Binding event MainWindow:actionRazorTool_trigger
     ui_util:INFO Binding event MainWindow:actionSnappingTool_trigger
     ui_util:INFO Binding event MainWindow:actionAddMarker_trigger
     ui_util:INFO Binding event MainWindow:actionPreviousMarker_trigger
     ui_util:INFO Binding event MainWindow:actionNextMarker_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowAll_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowVideo_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowAudio_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowImage_trigger
     ui_util:INFO Binding event MainWindow:actionTransitionsShowAll_trigger
     ui_util:INFO Binding event MainWindow:actionTransitionsShowCommon_trigger
     ui_util:INFO Binding event MainWindow:actionEffectsShowAll_trigger
     ui_util:INFO Binding event MainWindow:actionEffectsShowVideo_trigger
     ui_util:INFO Binding event MainWindow:actionEffectsShowAudio_trigger
     ui_util:INFO Binding event MainWindow:actionTimelineZoomIn_trigger
     ui_util:INFO Binding event MainWindow:actionTimelineZoomOut_trigger
     ui_util:INFO Binding event MainWindow:actionTitle_trigger
     ui_util:INFO Binding event MainWindow:actionAnimatedTitle_trigger
     ui_util:INFO Binding event MainWindow:actionFullscreen_trigger
     ui_util:INFO Binding event MainWindow:actionAbout_trigger
     ui_util:INFO Binding event MainWindow:actionThumbnailView_trigger
     ui_util:WARNING Icon theme view-list-icons not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionDetailsView_trigger
     ui_util:WARNING Icon theme view-list-details not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionReportBug_trigger
     ui_util:INFO Binding event MainWindow:actionAskQuestion_trigger
     ui_util:INFO Binding event MainWindow:actionTranslate_trigger
     ui_util:INFO Binding event MainWindow:actionDonate_trigger
     ui_util:INFO Binding event MainWindow:actionHelpContents_trigger
     ui_util:INFO Binding event MainWindow:actionSimple_View_trigger
     ui_util:INFO Binding event MainWindow:actionAdvanced_View_trigger
     ui_util:WARNING Icon theme get-hot-new-stuff not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionFreeze_View_trigger
     ui_util:INFO Binding event MainWindow:actionUn_Freeze_View_trigger
     ui_util:INFO Binding event MainWindow:actionShow_All_trigger
     ui_util:INFO Binding event MainWindow:actionProfile_trigger
     ui_util:INFO Binding event MainWindow:actionAdd_to_Timeline_trigger
     ui_util:INFO Binding event MainWindow:actionPreview_File_trigger
     ui_util:INFO Binding event MainWindow:actionRemove_from_Project_trigger
     ui_util:INFO Binding event MainWindow:actionFile_Properties_trigger
     ui_util:INFO Binding event MainWindow:actionRemoveTrack_trigger
     ui_util:INFO Binding event MainWindow:actionRemoveMarker_trigger
     ui_util:INFO Binding event MainWindow:actionAddTrackAbove_trigger
     ui_util:INFO Binding event MainWindow:actionAddTrackBelow_trigger
     ui_util:INFO Binding event MainWindow:actionRemoveEffect_trigger
     ui_util:INFO Binding event MainWindow:actionSplitClip_trigger
     ui_util:INFO Binding event MainWindow:actionProperties_trigger
     ui_util:INFO Binding event MainWindow:actionRenameTrack_trigger
     ui_util:INFO Binding event MainWindow:actionUpdate_trigger
     ui_util:INFO Binding event MainWindow:actionTutorial_trigger
     ui_util:INFO Binding event MainWindow:actionAnimation_trigger
     ui_util:INFO Binding event MainWindow:actionLockTrack_trigger
     ui_util:INFO Binding event MainWindow:actionUnlockTrack_trigger
     ui_util:WARNING Icon theme transform-move not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionEditTitle_trigger
     ui_util:INFO Binding event MainWindow:actionDuplicateTitle_trigger
     ui_util:INFO Binding event MainWindow:actionClearHistory_trigger
files_listview:INFO currentChanged
files_listview:INFO updateSelection
 files_model:INFO updating files model.
transition_model:INFO updating transitions model.
     version:INFO Found current version: {"openshot_version": "2.4.2"}
effects_model:INFO updating effects model.
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
 main_window:INFO foundCurrentVersion: Found the latest version: 2.4.2
properties_model:INFO updating clip properties model.
 main_window:INFO InitCacheSettings
 main_window:INFO cache-mode: CacheMemory
 main_window:INFO cache-limit-mb: 250
 main_window:INFO Creating CacheMemory object with 262144000 byte limit
 main_window:INFO Clear all thumbnails: /home/.openshot_qt/thumbnail
 main_window:INFO Clear all animations: /home/.openshot_qt/blender
 main_window:INFO Clear all assets: /home/.openshot_qt/assets
 main_window:INFO Clear all backups: /home/.openshot_qt/backup
preview_thread:INFO QThread Start Method Invoked
preview_thread:INFO initPlayer
    tutorial:INFO process tutorial dialogs
 main_window:INFO updateStatusChanged
         app:INFO Process command-line arguments: ['/usr/bin/openshot-qt']
 main_window:INFO recover_backup
project_data:INFO Setting default profile to HDV 720 24p
preview_thread:INFO refreshFrame
preview_thread:INFO self.player.Position(): 1
timeline_webview:ERROR TimelineWebView::eval_js() called before document ready event. Script queued: $('body').scope().SetTrackLabel('Piste %s');
timeline_webview:ERROR TimelineWebView::eval_js() called before document ready event. Script queued: $('body').scope().LoadJson({"type": "load", "key": "", "value": {"id": "T0", "fps": {"num": 24, "den": 1}, "width": 1280, "height": 720, "sample_rate": 44100, "channels": 2, "channel_layout": 3, "settings": {}, "clips": [], "effects": [], "export_path": "", "files": [], "duration": 300, "scale": 16, "tick_pixels": 100, "playhead_position": 0, "profile": "HDV 720 24p", "layers": [{"id": "L0", "label": "", "number": 0, "y": 0, "lock": false}, {"id": "L1", "label": "", "number": 1, "y": 0, "lock": false}, {"id": "L2", "label": "", "number": 2, "y": 0, "lock": false}, {"id": "L3", "label": "", "number": 3, "y": 0, "lock": false}, {"id": "L4", "label": "", "number": 4, "y": 0, "lock": false}], "markers": [], "progress": [], "history": {"undo": [], "redo": []}, "version": {"openshot-qt": "0.0.0", "libopenshot": "0.0.0"}}, "partial": false, "old_values": null});
 main_window:INFO updateStatusChanged
timeline_webview:ERROR TimelineWebView::eval_js() called before document ready event. Script queued: $('body').scope().SetSnappingMode(1);
timeline_webview:ERROR TimelineWebView::eval_js() called before document ready event. Script queued: $('body').scope().MovePlayheadToFrame(1);
preview_thread:INFO onModeChanged
properties_model:INFO Update item: 
properties_model:INFO updating clip properties model.
    timeline:INFO Adjusting max size of preview image: PyQt5.QtCore.QRect(57, 0, 700, 394)
timeline_webview:ERROR TimelineWebView::eval_js() called before document ready event. Script queued: $('body').scope().SetTrackLabel('Piste %s');
timeline_webview:ERROR TimelineWebView::eval_js() called before document ready event. Script queued: $('body').scope().LoadJson({"type": "load", "key": "", "value": {"id": "T0", "fps": {"num": 24, "den": 1}, "width": 1280, "height": 720, "sample_rate": 44100, "channels": 2, "channel_layout": 3, "settings": {}, "clips": [], "effects": [], "export_path": "", "files": [], "duration": 300, "scale": 16, "tick_pixels": 100, "playhead_position": 0, "profile": "HDV 720 24p", "layers": [{"id": "L0", "label": "", "number": 0, "y": 0, "lock": false}, {"id": "L1", "label": "", "number": 1, "y": 0, "lock": false}, {"id": "L2", "label": "", "number": 2, "y": 0, "lock": false}, {"id": "L3", "label": "", "number": 3, "y": 0, "lock": false}, {"id": "L4", "label": "", "number": 4, "y": 0, "lock": false}], "markers": [], "progress": [], "history": {"undo": [], "redo": []}, "version": {"openshot-qt": "0.0.0", "libopenshot": "0.0.0"}}, "partial": false, "old_values": null});
preview_thread:INFO refreshFrame
preview_thread:INFO self.player.Position(): 1
timeline_webview:ERROR TimelineWebView::eval_js() called before document ready event. Script queued: $('body').scope().SetSnappingMode(1);
timeline_webview:ERROR TimelineWebView::eval_js() called before document ready event. Script queued: $('body').scope().MovePlayheadToFrame(1);
timeline_webview:ERROR TimelineWebView::eval_js() called before document ready event. Script queued: $('body').scope().SetTrackLabel('Piste %s');
timeline_webview:ERROR TimelineWebView::eval_js() called before document ready event. Script queued: $('body').scope().LoadJson({"type": "load", "key": "", "value": {"id": "T0", "fps": {"num": 24, "den": 1}, "width": 1280, "height": 720, "sample_rate": 44100, "channels": 2, "channel_layout": 3, "settings": {}, "clips": [], "effects": [], "export_path": "", "files": [], "duration": 300, "scale": 16, "tick_pixels": 100, "playhead_position": 0, "profile": "HDV 720 24p", "layers": [{"id": "L0", "label": "", "number": 0, "y": 0, "lock": false}, {"id": "L1", "label": "", "number": 1, "y": 0, "lock": false}, {"id": "L2", "label": "", "number": 2, "y": 0, "lock": false}, {"id": "L3", "label": "", "number": 3, "y": 0, "lock": false}, {"id": "L4", "label": "", "number": 4, "y": 0, "lock": false}], "markers": [], "progress": [], "history": {"undo": [], "redo": []}, "version": {"openshot-qt": "0.0.0", "libopenshot": "0.0.0"}}, "partial": false, "old_values": null});
timeline_webview:ERROR TimelineWebView::eval_js() called before document ready event. Script queued: $('body').scope().SetSnappingMode(1);
timeline_webview:ERROR TimelineWebView::eval_js() called before document ready event. Script queued: $('body').scope().MovePlayheadToFrame(1);
timeline_webview:INFO Qt Found!
timeline_webview:INFO $scope.Qt = true;
timeline_webview:INFO UpdateLayerIndex
timeline_webview:INFO UpdateLayerIndex
    tutorial:INFO hide_tips
    timeline:INFO Adjusting max size of preview image: PyQt5.QtCore.QRect(117, 0, 700, 394)
 files_model:INFO updating files model.
 main_window:INFO Imported media file /home/Vidéos/MOV003.MOD
     ui_util:INFO Initializing UI for Dialog
 main_window:INFO About Openshot add cancelled
 main_window:INFO auto_save_project
 main_window:INFO auto_save_project
 main_window:INFO auto_save_project
 main_window:INFO auto_save_project
 main_window:INFO auto_save_project
 main_window:INFO auto_save_project
 files_model:INFO updating files model.
 main_window:INFO Imported media file /home/Vidéos/MOV003.MOD
     ui_util:INFO Initializing UI for Dialog
 main_window:INFO About Openshot add cancelled
    tutorial:INFO minimize tutorial
    tutorial:INFO process tutorial dialogs
    tutorial:INFO process tutorial dialogs
    tutorial:INFO process tutorial dialogs
    tutorial:INFO process tutorial dialogs
 main_window:INFO auto_save_project
    tutorial:INFO process tutorial dialogs
    tutorial:INFO process tutorial dialogs
    tutorial:INFO process tutorial dialogs
    tutorial:INFO process tutorial dialogs
preview_thread:INFO onModeChanged
preview_thread:INFO exiting thread

Thank you in advance for your help.
Regards,

**Comment by peanutbutterandcrackers** [comment]
Good sir, please try transcoding the video into, say, `.mp4` or `.mkv` using [HandBrake](https://handbrake.fr/) and then try importing the video into OpenShot. That should work out.

On a side note, I have never really heard of `.mod` files. Could you please use [MediaInfo](http://mediaarea.net/MediaInfo) to get details about the file and then post it here. I'd really like to know what kind of container it is. Thanks!

**Comment by lutzig** [comment]
~/Vidéos$ mediainfo MOV003.MOD
General
Complete name                            : MOV003.MOD
Format                                   : MPEG-PS
File size                                : 2.68 GiB
Duration                                 : 41 min 41 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 9 208 kb/s
FileExtension_Invalid                    : mpeg mpg m2p vob pss evo

Video
ID                                       : 224 (0xE0)
Format                                   : MPEG Video
Format version                           : Version 2
Format profile                           : Main@Main
Format settings                          : BVOP
Format settings, BVOP                    : Yes
Format settings, Matrix                  : Default
Format settings, GOP                     : M=3, N=12
Format settings, picture structure       : Frame
Duration                                 : 41 min 41 s
Bit rate mode                            : Variable
Bit rate                                 : 8 641 kb/s
Maximum bit rate                         : 9 200 kb/s
Width                                    : 720 pixels
Height                                   : 576 pixels
Display aspect ratio                     : 4:3
Frame rate                               : 25.000 FPS
Standard                                 : PAL
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Interlaced
Scan order                               : Top Field First
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 0.833
Time code of first frame                 : 00:00:00:00
Time code source                         : Group of pictures header
GOP, Open/Closed                         : Closed
Stream size                              : 2.52 GiB (94%)
Color primaries                          : BT.601 PAL
Transfer characteristics                 : BT.470 System B, BT.470 System G
Matrix coefficients                      : BT.470 System B, BT.470 System G

Audio
ID                                       : 189 (0xBD)-128 (0x80)
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Muxing mode                              : DVD-Video
Duration                                 : 41 min 41 s
Bit rate mode                            : Constant
Bit rate                                 : 384 kb/s
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Bit depth                                : 16 bits
Compression mode                         : Lossy
Stream size                              : 115 MiB (4%)
Service kind                             : Complete Main
Menu
PC:~/Vidéos$

**Comment by peanutbutterandcrackers** [comment]
Hmm... interesting. Did transcoding using HandBrake fix it, sir?

**Comment by lutzig** [comment]
Handbrake recognised .mod files...

**Comment by peanutbutterandcrackers** [comment]
So, were you able to convert from HandBrake and then import the converted files into OpenShot for editing? Has this issue been worked around? Should I close this issue then, good sir?

**Comment by N3WWN** [comment]
I'm wondering if the file extension is the issue here... handbrake may have analyzed the contents of the file in order to process it.

mediainfo tells us `FileExtension_Invalid : mpeg mpg m2p vob pss evo` 

Perhaps changing the extension of the file from `.mod` to `.mpg` (or one of the others that mediainfo says are valid for the contained streams) would allow OpenShot to process the video without transcoding?

Check out WikiPedia's page on the [MOD](https://en.wikipedia.org/wiki/MOD_and_TOD) video file format for more info.  

I'm especially interested in this nugget from that page which backs up my initial thought of just changing the file extension:

> Standard definition video is stored in MPEG program stream container files with MOD extension; in most other systems these files have extension MPG or MPEG.

**Comment by lutzig** [comment]
1. Handbrake has generated a .m4v file what isn't recognised by OpenShot...
2. By changing the extension name .mod by .mpg is recognised by OpenShot but the video and audio had lost lot of their quality in OpenShot but not a lot when I watch it.

**Comment by peanutbutterandcrackers** [comment]
So, I think transcoding using HandBrake is the way to go, then.

Should I close this issue, then?

**Comment by lutzig** [comment]
Yes, it can be closed ;)...
Thank you for your help

**Comment by ferdnyc** [comment]
Odd that HandBrake would've used the `.m4v` extension, I didn't think that was one of its defaults. But, we should really recognize that extension anyway, it _is_ a valid, if infrequently-used, extension for video-only MP4 files. But, looking at the code, that's a libopenshot issue. I'll clone that part of this over there.
