### ISSUE TITLE
[Feature] Record Narration Speech

### ISSUE THREAD

**Issue by MrTeeXD** [OpenShot/openshot-qt#1770]
**Is your feature request related to a problem? Please describe.**
With this feature, you can record an narrative speech and apply it to your video clips

**Describe the solution you'd like**
A button with a mic and record icon that will allow you to record your voice overs

**Describe alternatives you've considered**
Technically you could record your speeches in Audacity but a built in Narrative Speech recorder can be usefull

**Additional context**

**Comment by peanutbutterandcrackers** [comment]
Perhaps this will be there in OpenShot `2.7'? Haha :D

Thank you for your help to make OpenShot better, Mr. Tee. You're the best!
