### ISSUE TITLE
How to add audio?

### ISSUE THREAD

**Issue by MaRiO32760** [OpenShot/openshot-qt#1771]
How do I add audio to my project?

It is an M4A audio file. how do I add it into my project? I tried using the audio tab but nothing happened.

**Comment by peanutbutterandcrackers** [comment]
[Here](https://gist.github.com/peanutbutterandcrackers/f0f666243133e0ed25abbc12a4ba23d7), is a guide to take you from zero to hero in OpenShot, good sir! :+1: 

If you just want the answer to the question though: [this](https://www.youtube.com/watch?v=0a_B4LxTy3Y&t=14s) video shows a quick workflow in OpenShot. Hope that helps!

Closing this as answered. If you still have any queries, please do feel free to comment/re-open. :)
