### ISSUE TITLE
Pixel Ratio not taken into consideration 

### ISSUE THREAD

**Issue by robin-a-meade** [OpenShot/openshot-qt#1774]
**Describe the bug**
When importing video, the pixel ratio of the imported video is not take into consideration when previewing the video or when exporting.

**System Details (please complete the following information):**
 - Operating System / Distro: Windows 10 and Fedora 28
 - OpenShot Version [e.g. 2.4.2]

**To Reproduce**

1. Download sample 15s video segment extracted from a Widescreen DVD using default Handbrake settings:  https://drive.google.com/open?id=1NGU9BKFMnAl3HjGVTVwAmKN35TCK9yJz

2. Open a new OpenShot project

3. Choose Profile matching the file:
![image](https://user-images.githubusercontent.com/1343270/42194814-75cdfeb2-7e11-11e8-9dec-97a16c2a3c4a.png)

4. Import the downloaded video file and place it on the timeline

![image](https://user-images.githubusercontent.com/1343270/42194960-3fb4a51e-7e12-11e8-9396-43d01c04bf65.png)

Notice that the File Properties indicates that the Pixel Ratio was properly detected, but the preview shows the video with a 3:2 aspect ratio (with pillar bars) instead of the expected 16:9 ratio.

**Expected Behavior**

The Pixel Ratio of the imported video files should be taken into consideration when displaying the video in the preview pane and when exporting the final result.

**Comment by peanutbutterandcrackers** [comment]
@N3WWN - I think you're most suited to look into this issue... please? *puppy face*

**Comment by N3WWN** [comment]
My head starts spinning around when I look at the preview window aspect ratio stuff.  I thought I had it figured out a while ago and submitted a PR to fix how custom aspect and pixel ratios work, but it only worked in that edge case and broke the preview window rendering properly for other AR/PR combinations. 

At this point, my guess is that the issues is in `libopenshot`'s `FFmpegReader::UpdateVideoInfo()` function... in that function the pixel_ratio for a clip appears to only obtained from the aspect ratio or set to 1:1.  A clip that has a pixel ratio defined in the properties is never queried for it.

I guess a question I have for @robin-a-meade is:  Does the video render properly?  Is this just a preview window issue or is it preview window *and* rendered/exported video that displays with the bars?

**Comment by robin-a-meade** [comment]
The original 15s sample video renders correctly with a 16:9 aspect ratio in VLC.

If I start a OpenShot project with profile of *DVD/DV Widescreen NTSC (720x480)* and add this file to the project, the file properties properly lists a Pixel Ratio of 32:27 and an Aspect Ratio of 16:9. However, when placing the file on the timeline, the preview window ignores the pixel ratio, displaying the video with a 3:2 aspect ratio, adding pillar-bars to fill out the 16:9 ratio of the selected profile.

If I then perform a trivial edit (adding fade in and fade out) and export using the project's profile (as selected earlier), the result is a 720x480 video. Curiously, no pillar bars where added to force the 16:9 ratio of the export profile. It plays with a 3:2 aspect ratio, making people people look tall and skinny.

Here's the relevant ffprobe output:

Original file:

```
Duration: 00:00:15.04, start: 0.000000, bitrate: 1144 kb/s
  Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), 
     yuv420p(tv, smpte170m/smpte170m/bt709), 720x480 [SAR 32:27 DAR 16:9], 
     978 kb/s, 30.04 fps, 29.97 tbr, 90k tbn, 180k tbc (default)

```

Exported file:

```
Duration: 00:00:15.08, start: 0.033000, bitrate: 18213 kb/s
  Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), 
    yuv420p, 720x480, 
    18026 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 59.94 tbc (default)
```

**Comment by nathankidd** [comment]
Data point that videos with different SAR/DAR and thus this issue are perhaps more common: I have the same issue with video produced by a Sony Handycam HDR-CX100
```
Input #0, mpegts, from '00000.MTS':
  Duration: 00:25:08.99, start: 1.033367, bitrate: 11263 kb/s
  Program 1 
    Stream #0:0[0x1011]: Video: h264 (High) (HDMV / 0x564D4448), yuv420p(top first), 1440x1080 [SAR 4:3 DAR 16:9], 29.97 fps, 59.94 tbr, 90k tbn, 59.94 tbc
```
VLC, etc. show correct aspect ratio, but OpenShot's preview shows black bars and people are squished tall and skinny.

**Comment by SuslikV** [comment]
@nathankidd What is set in _Scale_ property of the imported clip in OpenShot?
