### ISSUE TITLE
AppImage build is bundled with outdated libfontconfig

### ISSUE THREAD

**Issue by ferdnyc** [OpenShot/openshot-qt#1775]
**System Details:**
 - Operating System / Distro: Fedora 28, any recent Linux distro
 - OpenShot Version 2.4.2 from `OpenShot-v2.4.2-x86_64.AppImage`

Adding to the list of libraries that desperately need to be updated in the official builds, running OpenShot from the AppImage results in fontconfig log spew when it picks up the `Ubuntu-R.ttf` font:
```console
         app:INFO Setting font to /tmp/.mount_iw4BV5/usr/bin/images/fonts/Ubuntu-R.ttf
Fontconfig warning: line 5: unknown element "its:rules"
Fontconfig warning: line 6: unknown element "its:translateRule"
Fontconfig error: line 6: invalid attribute 'translate'
Fontconfig error: line 6: invalid attribute 'selector'
Fontconfig error: line 7: invalid attribute 'xmlns:its'
Fontconfig error: line 7: invalid attribute 'version'
Fontconfig warning: line 9: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/10-hinting-slight.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/10-hinting-slight.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/10-hinting-slight.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/10-hinting-slight.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 6: invalid attribute 'xmlns:its'
```
...and so on.

This is an [extremely](https://bugzilla.redhat.com/show_bug.cgi?id=1566762) well [known](https://bbs.archlinux.org/viewtopic.php?id=235643) fontconfig [issue](https://bugs.chromium.org/p/chromium/issues/detail?id=829890) with apps that bundle their own version, when running on systems that use a _newer_ version of fontconfig. The `/etc/fonts/` files from the latest fontconfig contain XML properties for new features, which are not supported by older versions of the library.

I can't seem to determine what version of fontconfig is bundled with the AppImage (it doesn't appear to have _its own_ version string embedded anywhere within the file!), but based on the output we know it's older than the current 2.13.0 release, which is when the config file format was extended.

Please update the AppImage builds to bundle fontconfig-2.13.0. Systems using older versions will not be impacted, as `libfontconfig.so.1` from fontconfig-2.13.0 can read `/etc/fonts/` files from older versions with no problems.

**Comment by deejay2** [comment]
Same issue here with Pop!_OS (Ubuntu 18.10 based).

**Comment by zufanka** [comment]
is there a workaround?

**Comment by ferdnyc** [comment]
@zufanka 

There's no need for a workaround, per se, as in real-world terms this issue is harmless.

The only effect of the outdated `libfontconfig.so` is a bunch of messages output on the console; no functionality is impacted.

That being said, if #3012 gets merged it will solve this, as there will no longer be any version of `libfontconfig.so` included in the AppImage builds.
