### ISSUE TITLE
I am unable to open OPENSHOT. Please Help Me...

### ISSUE THREAD

**Issue by V-Soni** [OpenShot/openshot-qt#1779]
![bandicam 2018-07-03 14-05-31-884](https://user-images.githubusercontent.com/40788535/42208602-34760108-7eca-11e8-9f81-7ca2f6f1c12d.jpg)

**Comment by peanutbutterandcrackers** [comment]
Which version is it that you are trying to open, good sir? Could you please give the latest version (version `2.4.2`) a try, please?

**Comment by peanutbutterandcrackers** [comment]
Why does it say C:\GitLab-Runner\ and stuff...? That is strange.... :/

**Comment by ViralSo** [comment]
hmm....

**Comment by ViralSo** [comment]
I had downloaded openshot that day itself....Therefore it is the latest
version sir....Sir what is the exact issue with the software??

**Comment by peanutbutterandcrackers** [comment]
We'll try to figure it out. Sorry for the inconvenience, good sir. Could you please [attach the logs](https://gist.github.com/peanutbutterandcrackers/d84c257e74b72d8b06b4daffaebc5a14) for us here? Thank you!

**Comment by peanutbutterandcrackers** [comment]
@DylanC - This might be of some interest to you, too, Cap'ain!

**Comment by peanutbutterandcrackers** [comment]
Also, @ViralSo, could you please try out the [daily builds](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914) to see if they work? Thank you!
