### ISSUE TITLE
Changing speed on multiple clips doesn't scale Timeline positions (creates gaps between clips in the timeline)

### ISSUE THREAD

**Issue by saabi89** [OpenShot/openshot-qt#1781]
Hi,

I am trying to make a timelapse using multiple videos from my camera.

I have about 65 videos each 5 minute long. The problem I am facing is that when I increase the speed of the videos for 32x, the videos in the timeline do not join automatically.

I will try and explain with screenshots. So first, I bring in the videos. I am only bringing in 3 to illustrate the issue.

![1](https://user-images.githubusercontent.com/40805708/42239579-4050bb8a-7efc-11e8-9985-b9407ba5391d.png)

Next I select all the videos in track 4 using Ctrl+A and then change the time, go fast and set 32X. When I do that, it reduces the video blocks, which is what I want. But the blocks are miles apart for some reason.

![2](https://user-images.githubusercontent.com/40805708/42239820-0732b97e-7efd-11e8-936d-3a7311a11a60.png)

I understand I can bring them close manually, which is fine if it is just 3 videos. Now imagine if I have around 65 videos or more. It will be such a pain.

Does anyone know how I can select all the videos and increases the speed to whatever (8x, 16x, 32x) in such a way that the blocks are next to each other without a gap?

Thanks,
Saabi

**Comment by saabi89** [comment]
For some reason I messed up the second image. Uploading the correct one here.

![untitled](https://user-images.githubusercontent.com/40805708/42239870-31573a04-7efd-11e8-87d4-0eb5170329d5.png)

**Comment by peanutbutterandcrackers** [comment]
I had run into this a similar issue with the daily builds during the RC series but couldn't get around to reporting it. So, I think this is a bug, indeed. Possibly related to #1610 too? Maybe I should check on that machine again and add some further info in the comments below...

@DylanC - Could you please also test this one out, Cap'ain?

@ferdnyc - Perhaps this might be of some interest to you, sir?

**Comment by saabi89** [comment]
Thanks. Hope this gets solved in the next update.
