### ISSUE TITLE
2.4.2 AppImage won't run "undefined symbol: drmGetDevice2"

### ISSUE THREAD

**Issue by geckolinux** [OpenShot/openshot-qt#1783]
Hi there, 

I was using the AppImage of OpenShot 2.4.0 on openSUSE Tumbleweed, which worked fine. However, the lastest 2.4.2 version won't run. This is the last error when run from a terminal:
`/tmp/.mount_YHAhte/usr/bin/launch: symbol lookup error: /usr/lib64/libGLX_mesa.so.0: undefined symbol: drmGetDevice2`
I'll attach the full log here.

Thanks a lot!
[output.txt](https://github.com/OpenShot/openshot-qt/files/2161740/output.txt)

**Comment by peanutbutterandcrackers** [comment]
Good sir, this issue has [already been worked around](https://github.com/OpenShot/openshot-qt/issues/1757#issuecomment-402237492). Please try the work-around for now. Please follow the discussion at #1757. A proper fix will be applied upstream for the bug-fix releases soon. Hope that helps!

Closing this for now. Please follow the other thread. Thanks!

**Comment by peanutbutterandcrackers** [comment]
@geckolinux - Good sir, please do confirm that the work-around worked for you too. Thank you!

**Comment by geckolinux** [comment]
Oops, sorry for the duplication. I did search first for the error it threw, but didn't find any open issues. Thanks for the fast response!

**Comment by peanutbutterandcrackers** [comment]
@geckolinux - It's all right, sir. Did the work-around resolve the issue for you?
