### ISSUE TITLE
openshot crashes when requested to export video

### ISSUE THREAD

**Issue by domink** [OpenShot/openshot-qt#1787]
**Describe the bug**
App crashes just after clicking on "Export Video" button at "Export Video Dialog".

**System Details (please complete the following information):**
 - Mac OS 10.13.5
- Hardware: Mac mini model Macmini4,1
         Intel Core 2 Duo (2,4 GHz)
         Caché level 2: 3 MB
         RAM: 8 GB
 - OpenShot Version 242

**To Reproduce**
Create a project
1. Go to 'File/Export Video'
2. Click on 'Export Video'
3. App crashes (almost immediately)

**Expected behavior**
Get the project exported or a popup notifying the error and actions to remediate it.

**Screenshots**
Not applicable

**Logs**
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/2162583/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2162584/openshot-qt.log)

**Additional context**
Not applicable

**Comment by peanutbutterandcrackers** [comment]
Possibly related to #1662

**Comment by domink** [comment]
Is any daily build available for mac for testing?

(Thanks for the prompt response :-) )

**Comment by peanutbutterandcrackers** [comment]
You can find the daily builds by following [this guide](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914). However, I am not sure if any of the latest ones will be any better as nothing substantial has changed since the release of version 2.4.2. Still, I would suggest that you stay in the loop and keep on loving and supporting this [free software](https://en.wikipedia.org/wiki/Free_software) gem.

**Comment by domink** [comment]
Thanks!

I'll wait for news then.
I love your app, it looks really easy to use and I'm desiring to see my first video rendered there.

I'm sw engineer with experience on Android and Windows apps, mostly on Java but... developed also on C, C++, C#. No experience on Mac dev but happy to help you if needed.
Not sure my skills are valid for your project, and my time is limited because daily work (not now... I'm on holidays :-) ). But... if you need help, I'll try my best

**Comment by dannafe** [comment]
I am having the same problem on both of my Macs.
MacBook Pro's with plenty of RAM and SSD discs.
Exports work a few times after first install, then immediate crash on export.
Reinstalling does **NOT** fix this.
This problem first came up with v2.4.2.
Reverting back to v2.4.1 does not fix this.

**Comment by bobcrikey** [comment]
Iv just tried openshot 2.4.2 on my macmini  4 gigs of ram and exported a video perfectly.
Not one problem.
and heres a video iv just done on my macmini if you want to see domink.
 cheers bob
[vader osx 242.mp4.tar.gz](https://github.com/OpenShot/openshot-qt/files/2163159/vader.osx.242.mp4.tar.gz)

**Comment by kimiassy** [comment]
i have the same issue on my imac

**Comment by dannafe** [comment]
using the profile YouTube + Quality: Low is working for me, too
OX-X MacBook Pro, Lots of RAM

**Comment by peanutbutterandcrackers** [comment]
@kimiassy - Could you please, for the time being, export to `YouTube + Quality: Low` and other profiles that @dannafe has pointed out to work, please? Also, could you please [attach the logs](https://gist.github.com/peanutbutterandcrackers/d84c257e74b72d8b06b4daffaebc5a14)? That will help us get some insight into this issue. Thanks!

@dannafe - Great detective work, sir! I wonder if something needs to be altered in the profiles (in the upstream)...

**Comment by abrewin** [comment]
I have tried both Mac and Windows 10 latest versions and its crashing on Export for me too.  Windows: exporting to MP4 High quality, it runs till about 95% then shuts down.  File is there but corrupted.   
Mac:  Crashes as soon as I click Export Video both High quality and Low.    

How to I find the Log files in Mac?

**Comment by StBrane** [comment]
I was having the same crash upon export issue.  

Advanced settings has the frame rate at 30000 to 1001.
I changed this to 28 and 28. 
Target is mp4(h2.64)
quality low. 


which then proceeded to dump 15,000 images into a folder.

**Comment by peanutbutterandcrackers** [comment]
@abrewin @StBrane - Thank you for the confirmation, good sirs.

Please read [this guide](https://gist.github.com/peanutbutterandcrackers/d84c257e74b72d8b06b4daffaebc5a14) to attach the logs, properly. [This guide](https://github.com/OpenShot/openshot-qt/blob/develop/CONTRIBUTING.md) tells you where to find the logs in different platforms. Please do attach the logs for us. That should help us do some further investigations into this. Thanks!

**Comment by kforney** [comment]
Experiencing this issue on Fedora 28 as well.

Here are my logs: 
[openshot-qt.log](https://pastebin.com/8seqwmwk)
[libopenshot.log](https://pastebin.com/6EnZvx5R)
[Output from terminal](https://pastebin.com/tP03TUnt)

**Comment by kforney** [comment]
Also, here's a backtrace from gdb: [Backtrace](https://pastebin.com/4cRzXMsn)

**Comment by peanutbutterandcrackers** [comment]
@ferdnyc - Another fellow fedora user encountering a problem here, sir! Perhaps you'd be interested. :)

**Comment by ferdnyc** [comment]
Apologies for the delay, there are a lot of issues open right now, and few people to look at them unfortunately.

@kforney — please open a new Issue, your crash doesn't appear related to @domink 's, and it's best to keep everyone's issues separate. Also, we're probably going to need [debug logs](https://github.com/OpenShot/openshot-qt/blob/develop/CONTRIBUTING.md) from you, if you can reproduce the issue.

@domink — Looking at your logs, it looks like you're outputting to MP4... but the audio bitrate is set to 44.1kHz. _Most likely_ your input video uses 48kHz. (You can check in OpenShot by right-clicking on an item in Project Files, choosing File Properties, and looking at "Sample Rate" under Audio Format. Or externally with a tool like [MediaInfo](https://mediaarea.net/en/MediaInfo/Download/Mac_OS).)

If your input video is 48kHz (Sample Rate = 48000), then I highly recommend setting the export sample rate to 48000 as well. (You can do that under Advanced > Audio Settings in the export window.) The resampler is really flaky, and frequently the source of export crashes. As of the next release, the default sample rate will be 48000 for all of the HD profiles, unfortunately that didn't make it into v2.4.2.

I'd also recommend going into OpenShot's preferences and setting the Default Audio Sample Rate to 48000. Again, that's going to become the initial setting as of the next release, but you're better off getting ahead of it and making that change yourself.

(If your input audio is 44.1kHz, or you really do need to output to 44.1kHz for some reason, then we'll have to keep looking for other issues. But 44.1kHz is a somewhat unusual samplerate for MP4, and not well supported so usually 48kHz is the better choice.)

**Comment by ferdnyc** [comment]
> When I select low quality youtube, it went through successfully. It seems 8G ram is not enough for HD video.

You don't give any details on your project so it's impossible to say, but I doubt that's the issue. I wish it were that simple, but I've done HD encodes with 6GB of RAM. The crash you were seeing would've happened if you had 100G of RAM. Switching from the YouTube-HD preset to the YouTube preset uses a completely different set of encoders, and most likely it's one of the encoders YouTube-HD uses that was crashing on you.

**Comment by dannafe** [comment]
I am still only able to export videos under the YouTube Low Resolution settings.  Every other setting I have tried halts Openshot

**Comment by ferdnyc** [comment]
Well, there are a couple of things about the YouTube (non-HD) preset that make it different from most other presets.
1. It uses MPEG-2 video (most use x264 or xvid in MP4 containers)
1. It uses MPEG-1 layer II audio (most use MP3 or AAC)

Either way, I would guess that if the YouTube target works for you, then you'd almost certainly be able to use the targets "MPEG (mpeg2)" and "AVI (mpeg2)" (both under "Profile: All Formats") as well, even with HD Video Profiles.

**Comment by DylanC** [comment]
@domink - Try v2.4.3 and let us know if you still have a problem.

**Comment by nlsn** [comment]
I'm new to OpenShot, so quite possibly I'm doing something wrong. However, when I try to export mp4 h.264 it hangs or dies. I'm trying export to mpeg2 (dvd presets) and it's going.

This is v2.4.3-x86_64 on Windows 10.

i7-8700 CPU @ 3.20GHz
16.0 GB RAM

It doesn't seem to matter what resolution or quality I choose, as long as it's mp4 it hangs or dies.

Thanks.
