### ISSUE TITLE
question: the sound of my video falters

### ISSUE THREAD

**Issue by Louisedeman** [OpenShot/openshot-qt#1788]
Hi, i am just starting to explore this video program. the videos (Mp4) i want to use are not working properly, because the sound falters.

i am using windows

is there a solution?

kind regards,
louise de man

**Comment by peanutbutterandcrackers** [comment]
Which version are you using? Please make sure you are using version 2.4.2 - the latest release. And which OS? Windows 8? 10?

What happens if you transcode the video into, say, an `.mkv` using [HandBrake](http://handbrake.fr/) and then import it into OpenShot.

**Comment by Louisedeman** [comment]
thanx,

i am using the latest version on windows 10.
I really dont want to have toe transcode every video i made before i can
use the program. that takes to much time
thanks for the tip though!

2018-07-04 12:10 GMT+02:00 peanutbutterandcrackers <notifications@github.com

**Comment by peanutbutterandcrackers** [comment]
@Louisedeman - Could you please, then, [attach the logs](https://gist.github.com/peanutbutterandcrackers/d84c257e74b72d8b06b4daffaebc5a14) so that the devs can look into this? Thanks! Hopefully we can get this fixed in the upcoming releases. Also, please give us full system specs and the output of running [MediaInfo](http://mediaarea.net/MediaInfo) on the clip? Thanks!

**Comment by peanutbutterandcrackers** [comment]
It just hit me that you could be using a profile with FPS different than your original footage. That might be causing issues with sound, then. Could you please make sure you are using the exact same FPS as your original footage while editing? If not, please switch to one. If there isn't a profile that matches your FPS/dimensions, etc. you can always [create your own custom profile](https://www.openshot.org/static/files/user-guide/profiles.html#custom-profile). Hope that helps!
