### ISSUE TITLE
Some dialogs does not looks proper rendered

### ISSUE THREAD

**Issue by domink** [OpenShot/openshot-qt#1790]
**Describe the bug**
Some dialogs does not looks proper rendered, white zones on the right which are partially draw when moving the mouse over those. I include a screen sample from Preferences diaolg.

**System Details (please complete the following information):**
- Mac OS 10.13.5
- Hardware: Mac mini model Macmini4,1
         Intel Core 2 Duo (2,4 GHz)
         Caché level 2: 3 MB
         RAM: 8 GB
 - OpenShot Version 2.4.2

**To Reproduce**
Open Preferences dialog

**Expected behavior**
Full dialog is rendered

**Screenshots**
![image](https://user-images.githubusercontent.com/1288430/42270814-0dd5793a-7f82-11e8-8124-41fa76f60bbb.png)

**Logs**
Not applicable

**Additional context**
Not applicable

**Comment by peanutbutterandcrackers** [comment]
@DylanC - Cap'ain, this one too (for testing)!

**Comment by DylanC** [comment]
@peanutbutterandcrackers - I can confirm this also happens on my Mac.

**Comment by ferdnyc** [comment]
Anyone (@domink , @DylanC) able to check whether this is still an issue with the development code and/or the 2.5.0 RC? I'm without access to a Mac to test on, myself.
