### ISSUE TITLE
crashes on windows 10

### ISSUE THREAD

**Issue by plamizia** [OpenShot/openshot-qt#1792]
hi guys
everytime i use the program it crashes: ie when i play sequences, when i insert an animation, etc
what log can i give you?
i use windows 10, i7 with 8gb ram, hd ssd
let me know please
thanks

**Comment by thatguycrazy** [comment]
hi, plamizia I have a dell E6430 i5 8gb ram with ssd and it is crashing when i insert transitions. so i'm having the same issue. what does yours say when it crashes? launch.exe?

**Comment by peanutbutterandcrackers** [comment]
Hey there,

Are the both of you using version 2.4.2? If not, then please switch to using version 2.4.2. Also, please do [attach the logs](https://gist.github.com/peanutbutterandcrackers/d84c257e74b72d8b06b4daffaebc5a14). That should help us help you. Thanks!

**Comment by madge1009** [comment]
I am also having crash problems only since updating to 2.4.2.  I have attached my log for what it's worth.  Also Windows 10.  It crashes when I export to video.  It does seem to have something to do with transitions, when I remove them it does not crash.
[openshot-qt.zip](https://github.com/OpenShot/openshot-qt/files/2171706/openshot-qt.zip)

**Comment by peanutbutterandcrackers** [comment]
@madge1009 - Strange, the crashes triggered by transitions were handled in the source code and should no longer be happening... Thank you for the logs, BTW. We'll try to get on fixing this in the upcoming releases. Sorry for the inconvenience.

**Comment by thatguycrazy** [comment]
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/2172612/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2172613/openshot-qt.log)

Crashes when playing transitions.

**Comment by peanutbutterandcrackers** [comment]
Thank you for the logs, sir. We'll look into this. :+1:

**Comment by DylanC** [comment]
@plamizia - This transitions bug has been fixed. See #2125.

**Comment by nesoor** [comment]
Not to be rude but I just installed this program and this is my first time using it but it is broken as hell.
It can't do anything without crashing.
