### ISSUE TITLE
Audio out of sync from video in preview mode and after export

### ISSUE THREAD

**Issue by AngryFIlly888** [OpenShot/openshot-qt#1797]
**Describe the bug**
Audio from videos is out of sync and audio skips.  Video some times skips but I think I fix that.

**System Details (please complete the following information):**
 - Operating System / Windows 10
 - OpenShot Version 2.4.2, also tried in different versions and had the same problem.

**To Reproduce**
1. Import video (With audio and a way to pinpoint where it is usually)
2. Add to track
3. Play video in preview/after export

**Expected behavior**
Audio skip and out of sync by about 3 seconds.

**Clip of issue**
https://www.youtube.com/watch?v=apmrJsACLSU
(Watch subtitles/Closed captions)

**Additional context**
I think it has something to do with the audio sample rate and frame rate that the videos I import are at. I tried changing the profiling in OpenShot and OBS, it fix the video skip but not the audio.

**UPDATE**
Did more testing
1. The video in OpenShot says it is 33 seconds ( actually 33.05) and the original is 33 seconds long, but the beginning is cut by about 4 seconds maybe less and the end by less than a second.
2. At around the 30 second mark the video in the preview stops ( the time line bar keeps moving) and the audio made a buzzing noise that lasted 3 seconds, then half a second of the audio from the original video played clearly.
P.S. I found an FPS value in OBS that fixes the audio sync issues, 24 NTSC. Audio good, video glitchy.

**Comment by peanutbutterandcrackers** [comment]
Hey there!

Are you sure your profile (in OpenShot) has the same FPS your input video? For instance, if the original footage is 30fps but you edit in 24fps you'll end up having issues like these. Could you please make sure you are using the same profile? If not, we can get this marked as a bug.

Thanks!

**Comment by peanutbutterandcrackers** [comment]
Oh, I see. Then this is probably related to https://github.com/OpenShot/libopenshot/issues/115

Marking this as a bug for now, then. Thank you for the report. Please do look forward to upcoming releases. :)

**Comment by AngryFIlly888** [comment]
BINGO! found an FPS value that works, 24 NTSC. the audio is in sync but the video is glitchy. https://www.youtube.com/watch?v=2RjLPxdyIjw
Using the same video from last time. With captions.
P.S. the Glitchyness of the video is not OpenShot. It was like that before I put it in to the editor.

**Comment by peanutbutterandcrackers** [comment]
In the meantime, you might also want to experiment with [creating custom profiles](https://www.openshot.org/static/files/user-guide/profiles.html#custom-profile), perhaps?

**Comment by AngryFIlly888** [comment]
I FIXED IT!!!
Right now I am kicking my self in the butt, all I needed to do was change the encoder in OBS.
So mad, but so happy at the same time.
Sorry if this caused any problems.

**Comment by AngryFIlly888** [comment]
P.S. if this was any other open source video editor I would of totally forgot about trying to fix it, but I had faith in this one. Thx.

**Comment by DylanC** [comment]
@AngryFIlly888 - Glad you got this sorted! :)

**Comment by ego-lay-atman-bay** [comment]
I am having the same issue, and I would like to know how to make it sync correctly.

**Comment by jon-bondy** [comment]
I  resolved this problem by going to Edit, Preferences, Preview, Playback Audio Device and changing it from the actual device to "Default".
