### ISSUE TITLE
Timeline can't play past an hour of duration

### ISSUE THREAD

**Issue by MrThatKid** [OpenShot/openshot-qt#180]
The timeline video preview stops playing at ~55 minutes and 36 seconds into the timeline. Attempts to go past that point yield nothing. Position of files and timeline zoom don't matter either as it stops in the same time location. The files used are in the .MPG format using the DV/DVD Widescreen NTSC format on Kubuntu 16.04, 64-bit.
The package I'm using is openshot-qt 2.0.7 from ppa:openshot.developers/ppa

For the record, this doesn't happen in Openshot 1.4.3 on the same system.

**Comment by TheOpenDevProject** [comment]
#135 Probably related

**Comment by DylanC** [comment]
@MrThatKid  - Closed ticket referenced. Should be resolved now in the latest version.
