### ISSUE TITLE
merge and append project into time line from another openshot project

### ISSUE THREAD

**Issue by bobcrikey** [OpenShot/openshot-qt#1800]
hello everyone, "A Merge and an append option"
I'd like see a merge option to be included into future version of openshot .
As it would be handy at either the beginging of a time line or at the end of the time line to merge
another project files into current timeline and project files. or append it.

I know you can just add in the new files, but to be able to copy a whole project with all the files from say
project A and paste them into project B so you have a combined  2 projects into 1. :)

thanks
  bob

**Comment by peanutbutterandcrackers** [comment]
Is [this](https://github.com/OpenShot/openshot-qt/issues/1230) what you mean, good sir?
