### ISSUE TITLE
Extending Open Shot effects 

### ISSUE THREAD

**Issue by wallyvianna** [OpenShot/openshot-qt#1803]
I want to know if plugins or extensions with more effects can be added to Open Shot, and how to do it.

**Comment by peanutbutterandcrackers** [comment]
Sorry sir, not yet. Plans are there for an effects plugin so that the users can write their own cool new effects and stuff. But it might take a while before that becomes a reality... Please stay on the loop and keep on loving/supporting OpenShot till then!

Closing this as answered. :)
