### ISSUE TITLE
Cheers! How to fade an audio file?

### ISSUE THREAD

**Issue by marioratko** [OpenShot/openshot-qt#1804]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by peanutbutterandcrackers** [comment]
There's the simple way:
![screenshot from 2018-07-07 07 56 34](https://user-images.githubusercontent.com/26764547/42405758-4cc5a1ca-81bb-11e8-8034-1055873690dd.png)

and there's the 'hard' way - using volume keyframes.

I prefer using keyframes. It allows one to control every aspect of any property of a clip. Check [this](https://gist.github.com/peanutbutterandcrackers/f0f666243133e0ed25abbc12a4ba23d7) guide out to learn about Keyframes. :+1:

**Comment by DylanC** [comment]
@marioratko - Follow the answer provided above. Thanks
