### ISSUE TITLE
Python error in main script :( 2.0.7 on W10 hp Pavillon BeatsAudio

### ISSUE THREAD

**Issue by JRelland** [OpenShot/openshot-qt#181]
Hello and thank you for this application.

I have already run it on this computer :)

I put the last version et got this.

![image](https://cloud.githubusercontent.com/assets/10448655/15094957/4a5fa9a6-14b4-11e6-930f-850331c34804.png)

Thank you for your feedback

BR, José jose.relland@gmail.com

**Comment by jreynojustin** [comment]
OpenShot is now in Version 2.2 if you are still noticing issues in the latest version please re-open this issue letting us know.
