### ISSUE TITLE
fail to export 

### ISSUE THREAD

**Issue by lilly91** [OpenShot/openshot-qt#1812]
**Describe the bug**
When exporting the video it always stops at 34.4% and crashes. Launch.exe not responding is the error displayed. Tried to export in different formats but same issue.

**System Details (please complete the following information):**
 - Operating System / Distro: [Windows 10]
 - OpenShot Version [2.4.2]

**Comment by peanutbutterandcrackers** [comment]
Um... good sir, could you please [attach the logs](https://gist.github.com/peanutbutterandcrackers/d84c257e74b72d8b06b4daffaebc5a14) here, please? That should really help us help you. Thanks!

**Comment by peanutbutterandcrackers** [comment]
@lily91 - Would you not like for this to be solved, sir/ma'am? We could really use the logs to investigate this issue...

**Comment by lilly91** [comment]
Thank you but the issue has been solved. I had to export the file in a different format.

**Comment by peanutbutterandcrackers** [comment]
Oh, I see. Thank you for the confirmation. We'll be working, in the meantime, to make OpenShot stable with all sorts of export profiles. Please do keep on loving and supporting OpenShot. :+1: :)
