### ISSUE TITLE
project files list Alphabetical order needed

### ISSUE THREAD

**Issue by bobcrikey** [OpenShot/openshot-qt#1813]
hello , all project files need to be in alphabetical order.
At present if you import files into the project one at a time they are usually not in order alphabetically.
have a look at this picture to demostrate., notice the apple and the book are at the bottom and should
be at the top of the project files listing. the same in the image tab, they are out of order.

This needs to be corrected, its frustrating having to go through dozens of files scrolling up and down
trying to file the you want , 

if the project files and the image files were in alphabetical order, you can get to your file quicker.
this needs to be addressed.

thanks bob
![not in order](https://user-images.githubusercontent.com/40479177/42416914-3a1e75b6-82be-11e8-92c8-b49217c91881.jpg)

**Comment by peanutbutterandcrackers** [comment]
Precisely! I was thinking the same thing some time earlier; but was unable to submit an issue myself (too busy juggling around the other reported issues). Perhaps we should have a 'sort by' option in that tab...

**Comment by N3WWN** [comment]
And here again we have differing preferred ways of doing things.  For me, I import files in groups, so I like it that OpenShot sorts by the order added instead of alphabetical.  So, now we're looking at adding a configurable option, just as you said, @peanutbutterandcrackers .  Folks will want to be able to sort by time/date, alpha, import order, etc as well as asc/dec to invert the order.

**Comment by peanutbutterandcrackers** [comment]
Hmm... yeah... Perhaps we should keep the `sort by: import order` too? :)

**Comment by sangaman** [comment]
This is a critical piece of missing functionality for me.

**Comment by N3WWN** [comment]
stalebot, you've been busy today! hehe

I can confirm that the ability to sort the project files is not present in daily build OpenShot-v2.5.1-dev2-1597049004-bf0159bb-7cec1822-x86_64.AppImage.

**Comment by mikep345678** [comment]
Just wanna upvote this request: to be able sort alphanumerically (by clicking "name" header would be intuitive") and/or to be able to drag to sort media would be **huge**.

Thank you!
