### ISSUE TITLE
One time use Razor Tool feature

### ISSUE THREAD

**Issue by Hunteil** [OpenShot/openshot-qt#1816]
**Is your feature request related to a problem? Please describe.**
When I use the razor tool and it takes awhile... I'll let it process, but sometimes I'll forget the tool is still active and click on a strip and get stuck screwing everything up.

**Describe the solution you'd like**
Could you please add a feature to enable single use of that tool? i.e. when you use it, it turns off the tool. Just add the feature to the preferences.

**Comment by DylanC** [comment]
@peanutbutterandcrackers - This is a duplicate or related to this one #1418

**Comment by peanutbutterandcrackers** [comment]
Um, I wonder if it is not quite even related, Cap'ain. It seems the user wants the razor tool to stop being activated once the splitting is done. While over there, discussions are about for changing the razor tool to actually look like a razor instead of scissors (or some such other UI/documentation enhancement)...

**Comment by Hunteil** [comment]
correct @peanutbutterandcrackers . I just want it to revert to not being selected after being used once. I don't care about the picture.

Though I understand what @DylanC is saying. Which that video did help me with other ways to do cutting which I didn't know.

But my goal feature request is only to deactivate the tool after 1st use. How you do it needs discussed.

**Comment by Hunteil** [comment]
options:
A. Hold shift to allow continuous razor tool usage. Let go of shift and allow it to cut the film once and deactivate.
B. Have it a option in preferences to turn on/off the rule to deactivate it after 1st use.

**Comment by peanutbutterandcrackers** [comment]
I like that idea. Hold shift for continuous razor tool usage. :+1:
