### ISSUE TITLE
Snap back end of strips in timeline

### ISSUE THREAD

**Issue by Hunteil** [OpenShot/openshot-qt#1817]
**Is your feature request related to a problem? Please describe.**
Sometimes I realize my title screens need updating or a clip in my timeline needs to be replaced. So I create a new clip and line it up to previous clip with the snap feature. Then then I find that I can't stretch the back side of the new clip to front of the next clip with snaps. So I have to use Razor Tool and guess when it ends. Then I have to move all my clips up behind my new clip to keep things continuous without gaps. Which messes up my markers and placements of everything down the line.

**Describe the solution you'd like**
A button to allow snapping the backside of a clip when stretching to the front of another clip.

**Describe alternatives you've considered**
I've used Razor Tool to guess. I've also moved the new clip under the next clip (with Tracks) for layered cover up, but that's sloppy.

**Additional context**
If there's better ways to do this. please let me know.

**Comment by DylanC** [comment]
@peanutbutterandcrackers - Can you have a read of this issue and see does it make sense to you?

**Comment by peanutbutterandcrackers** [comment]
Hmm... I don't think I am grasping *exactly* what he is saying.

@Hunteil - Good sir, could you please provide us with some screenshots? Or some graphics as to what you are trying to convey here, please? Thank you!

**Comment by Hunteil** [comment]
Do you guys have a reliable .gif capture program you can recommend? I can try to explain with that. Also, I'm sorry I'm not using the correct terminology in my OP. I'm not well versed as I thought I was. (I'm completely novice & from a different industry)

I'll ask a question of the nouns I used so I can fix my wording and explain better lol.

-When you place any video on to any track... that object is called a clip right?
-Stretch.... Very wrong term I just realized... see this thread; that I clarified on: #1818 
-Snapping/snap/snapped... I'm referring to the Magnet image tool that I have enabled.

**Comment by peanutbutterandcrackers** [comment]
[The user guide](https://www.openshot.org/user-guide/) should help you figure out the terminology, good sir. :+1: 

But you seem to have gotten that mostly right.

I haven't really made any gifs but if you're on GNU/Linux, you could probably use [Simple Screen Recorder](http://www.maartenbaert.be/simplescreenrecorder/) for screen recording (and OpenShot itself if you need to edit and process - for instance zoom in on certain part of the video) and finally use [GIFup](https://github.com/bharatkalluri/gifup) to turn the video into a gif. Hope that helps! :)

**Comment by benrob0329** [comment]
I belive the request is for the end of one clip to snap when dragging to the closest end of another clip. Similar to how it is now when dragging the position of clips.

**Comment by peanutbutterandcrackers** [comment]
If that is the case, snapping - as it is called - seems to be working with OpenShot even when the end of one clip is dragged into another one, for me, at 
![screenshot from 2018-07-16 16-52-22](https://user-images.githubusercontent.com/26764547/42755631-bc8b02c0-8918-11e8-86a5-48c0649913fe.png)
least.

**Comment by benrob0329** [comment]
When moving clips, yes. Not when dragging the ends of it however (trimming or expanding them).

**Comment by peanutbutterandcrackers** [comment]
Oh, this?
![screenshot from 2018-07-17 07-21-01](https://user-images.githubusercontent.com/26764547/42791765-fd7c69da-8991-11e8-87da-a55dfb88802a.png)

I see it now... Thanks for the report. :+1:

**Comment by ferdnyc** [comment]
Yeah, agreed. I was surprised to discover that snapline alignment didn't trigger when resizing clips, the same way it does for moving them.
