### ISSUE TITLE
Make stretching more accurate

### ISSUE THREAD

**Issue by Hunteil** [OpenShot/openshot-qt#1818]
**Is your feature request related to a problem? Please describe.**
When I go to stretch a clip and try to line it up with something else. I notice that it doesn't stretch to exactly where I told it to go.

**Describe the solution you'd like**
Make the stretch method more accurate. If not due to limitation, then after the user attempts to stretch a clip more than 3 times, maybe make a reminder for a better way to do it. (that is if there's a better way to do it.)

**Describe alternatives you've considered**
Stretch it bigger, then use Razor tool.

**Additional context**
If there's some better way of doing it like a button I'm supposed to hold. Feel free to correct me.

**Comment by peanutbutterandcrackers** [comment]
I am sorry but I don't think I understand what you are trying to say. Could you please attach a few screenshots here, please? Thank you.

BTW, Images are stretch-able on the time-line. Videos aren't exactly stretch-able... but maybe we are talking about two different things here? o.O

**Comment by peanutbutterandcrackers** [comment]
Hmm... I see. Then, I think, this is closely related to making the timeline zoom levels even more bigger (down to frame-by-frame, hopefully) and getting the snapping right. Right?

**Comment by ferdnyc** [comment]
This actually was/is the clip-resizing bug that @DylanC addresses with #1914, I believe.

**Comment by Hunteil** [comment]
I don't believe that issue reference what I'm talking about... (Granted that is strange)
Mine is about grabbing the end and dragging it to the spot I want it to stop playing at. It don't matter how close I zoom in/out. It jumps a couple of frames off of where I want it. (And yes I'm no where near the end of the video clip.
