### ISSUE TITLE
Time RESET doesn't work correctly

### ISSUE THREAD

**Issue by Hunteil** [OpenShot/openshot-qt#1819]
**Describe the bug**
When resetting the time on a clip you sped up, you'll find it ruins the clip.

**System Details (please complete the following information):**
 - Windows 10
 - OpenShot Version 2.4.2

**To Reproduce**
-Take a clip, place it in a track timeline. right click>Time>Fast>Forward>8x
It should work and shrink the clip correctly.
-Right click the clip>Time>Reset Time
It should play a normal speed. But it never made the clip the full length. (1st part of issue)
-select clip and stretch to original size.
It will not stretch and even show the clip smaller while holding the mouse button. If you let go it kinda adjusts it, but nothing I can find fixes it.

**Expected behavior**
See above

**Screenshots**
I figured this was easy enough to reproduce.

**Logs**
No crash

**Comment by Hunteil** [comment]
Sorry, just realized Stretch isn't the correct term. See #1818 for how I'm describing it.
Either-way the issue still stands.

**Comment by peanutbutterandcrackers** [comment]
As I had already [confirmed over at issue 1411](https://github.com/OpenShot/openshot-qt/issues/1441#issuecomment-377439180), I think this is a bug.

**Comment by DylanC** [comment]
@Hunteil - Try v2.4.3 and let us know if you still have a problem.

**Comment by ferdnyc** [comment]
I re-tested this just now and it's definitely fixed in 2.4.4-dev2 (I think it was fixed by 2.4.4 release, honestly), so I'm going to close it.
