### ISSUE TITLE
OpenShot doesnt start anymore on Fedora 23

### ISSUE THREAD

**Issue by 772** [OpenShot/openshot-qt#182]
I was only working with my project. Then I rapidly closed it. A few minutes later, I tried to open it again and it didnt work. The hell? I reinstalled OpenShot three times now and deleted the .openshot_qt folder in my home user folder. Nothing helped so far. I also updated Python.

**openshot-qt.log**
      logger:ERROR Traceback (most recent call last):
      logger:ERROR   File "/usr/bin/openshot-qt", line 9, in <module>
      logger:ERROR load_entry_point('openshot-qt==2.0.7', 'gui_scripts', 'openshot-qt')()
      logger:ERROR   File "/usr/lib/python3.4/site-packages/pkg_resources/**init**.py", line 558, in load_entry_point
      logger:ERROR return get_distribution(dist).load_entry_point(group, name)
      logger:ERROR   File "/usr/lib/python3.4/site-packages/pkg_resources/**init**.py", line 2682, in load_entry_point
      logger:ERROR return ep.load()
      logger:ERROR   File "/usr/lib/python3.4/site-packages/pkg_resources/**init**.py", line 2355, in load
      logger:ERROR return self.resolve()
      logger:ERROR   File "/usr/lib/python3.4/site-packages/pkg_resources/**init**.py", line 2361, in resolve
      logger:ERROR module = **import**(self.module_name, fromlist=['**name**'], level=0)
      logger:ERROR   File "/usr/lib/python3.4/site-packages/openshot_qt/launch.py", line 52, in <module>
      logger:ERROR from classes.app import OpenShotApp
      logger:ERROR   File "/usr/lib/python3.4/site-packages/openshot_qt/classes/app.py", line 41, in <module>
      logger:ERROR import openshot
      logger:ERROR ImportError
      logger:ERROR :
      logger:ERROR No module named 'openshot'

**Comment by russellballestrini** [comment]
bump, I have the same error.  Anyone know a work around?

**Comment by jonoomph** [comment]
Sounds like a broken PPA issue, but that should be resolved now. Please reopen this if you still encounter the issue. Thanks!
