### ISSUE TITLE
Mixer sound between clips of mts video files.

### ISSUE THREAD

**Issue by nirhp** [OpenShot/openshot-qt#1822]
**Describe the bug**
When creating a video from more than one .mts video file, a "mixer" sound is played between clips.

**System Details (please complete the following information):**
 - Operating System: Windows 10
 - OpenShot Version: 2.4.2

**To Reproduce**
[00039.zip](https://github.com/OpenShot/openshot-qt/files/2178077/00039.zip)

1. Unzip the attached 00039.zip file
2. Import the unzipped 00039.mts video file to a new openshot project
3. Add this video twice (one time after another) to one of the tracks (So you'll 2 clips which play one after another)
4. If you'll try to play the project directly from openshot or export it to a video files, a mixer sound will play between the mts video clips.

**Expected behavior**
No mixer sound between clips (The original sound of the video files doesn't have it)

**Screenshots**
![image](https://user-images.githubusercontent.com/14215603/42477445-bd4855e4-83d9-11e8-9695-054c4947a351.png)

**Comment by peanutbutterandcrackers** [comment]
For the sake of more info, could you please also attach the output of [MediaInfo](http://mediaarea.net/MediaInfo) on the `.MTS` files, please? Thank you!

**Comment by nirhp** [comment]
Here it is:
[meta.txt](https://github.com/OpenShot/openshot-qt/files/2178951/meta.txt)

**Comment by peanutbutterandcrackers** [comment]
@nirhp - Thank you, sir! We'll try to get this fixed in the future releases! :+1:

**Comment by DylanC** [comment]
@nirhp - Can you try in v2.4.3 and let us know if you still have an issue.

**Comment by nirhp** [comment]
Sorry, but I won’t be able to test it before 1.2.19 :(

**Comment by nirhp** [comment]
The issue persist on 2.4.3
