### ISSUE TITLE
Crash when exporting to YouTube in Low quality.

### ISSUE THREAD

**Issue by nirhp** [OpenShot/openshot-qt#1823]
**Describe the bug**
When exporting to YouTube in Low quality OpenShot crashes. (but the file does export)

**System Details (please complete the following information):**
 - Operating System: Windows 10
 - OpenShot Version 2.4.2

**To Reproduce**
[00039.zip](https://github.com/OpenShot/openshot-qt/files/2178118/00039.zip)

1. Unzip the attached 00039.zip file
2. Import the unzipped 00039.mts video file to a new openshot project
3. Add this video to one of the tracks
4. Export to a new video with the following settings:
Profile = web
Target = youtube
Quality = low
5. Open shot will crash

**Expected behavior**
Openshot not crashing

**Screenshots**
Export settings
![image](https://user-images.githubusercontent.com/14215603/42478084-097cc5ba-83dc-11e8-8024-60f6a553af5c.png)

**Logs**
[openshot-qt.zip](https://github.com/OpenShot/openshot-qt/files/2178129/openshot-qt.zip)

**Comment by peanutbutterandcrackers** [comment]
Thank you for the report sir. Please look forward to the upcoming releases!

**Comment by nirhp** [comment]
I’m in a long holliday, it will take me some months until I’ll be able to test it...

**Comment by nirhp** [comment]
Issue persist

[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2706692/openshot-qt.log)
