### ISSUE TITLE
Crashing When attempting to export video (Windows 10)

### ISSUE THREAD

**Issue by RiptideRupture** [OpenShot/openshot-qt#1824]
Everytime I try to export the video it crashes. I usually have it on Web for Youtube. 

**System Details (please complete the following information):**
 - Operating System: Windows 10
 - OpenShot Version:  v2.4.2

(my latest video Ive been trying to create was around 10 minutes long, three separate clips, with three songs.)
1. Go to Export video
2. Click on Profile, select Web.
3. Click Target, select Youtube. 
4. I usually keep my quality on High. 
5. Export video
6. see Error

**Expected behavior**
Usually my cursor shows loading then Openshot launch stops working.

**Comment by peanutbutterandcrackers** [comment]
Good sir, could you please [attach the logs](https://gist.github.com/peanutbutterandcrackers/d84c257e74b72d8b06b4daffaebc5a14) please? Thanks!

**Comment by joshpies** [comment]
I'm having the same issue.  I'll gladly provide the logs but I'm not clear on how to find them.

**Comment by peanutbutterandcrackers** [comment]
@joshpies - Please take a look at [this](https://github.com/OpenShot/openshot-qt/blob/develop/CONTRIBUTING.md) document for the location of the logs. Thanks!

**Comment by kalindkaria** [comment]
I am having the same issue, it started crashing when I included second transition of wipe out from left to right between 2 clips... i dont know whats the issue.. ezpecting a reply asap.

I am attaching the log files also. Please help me!

Thank you.

[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2187485/openshot-qt.log)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/2187479/libopenshot.log)

**Comment by peanutbutterandcrackers** [comment]
@kalindkaria - Perhaps you'll have to wait for new releases for this to be resolved. However, I would like to request that you [attach the logs, again](https://gist.github.com/peanutbutterandcrackers/d84c257e74b72d8b06b4daffaebc5a14). Please delete the logs and re-create the crash and attach the new (smaller) logs. That should be quite helpful to the devs to fix this... Thank you!

**Comment by DylanC** [comment]
@RiptideRupture - This transitions bug has been fixed. See #2125.
