### ISSUE TITLE
i "x"'d out a window and i dont know how to get it back

### ISSUE THREAD

**Issue by dragonfruitdoggo** [OpenShot/openshot-qt#1825]
**Describe the bug**
its not a bug, its just me being stupid and not knowing how to do stuff. So i was on open shot and i pressed the x on the window of filters/effects. Anyone know how to get it back?

**System Details**
 - Operating System / Distro = macOS High Sierra version 10.13.5
 - OpenShot Version = 2.4.2

**Expected behavior**
i dont know, i wanted to rearrange my work space but now i cant find out how to get it back

**Comment by dragonfruitdoggo** [comment]
ok i got it back but how do u delete a thingy

**Comment by dragonfruitdoggo** [comment]
ohh ok

**Comment by peanutbutterandcrackers** [comment]
Glad it worked out for you. View > Views > Simple View is really simple, isn't it?
