### ISSUE TITLE
Same problem, different systems

### ISSUE THREAD

**Issue by bkarlan** [OpenShot/openshot-qt#183]
When trying to render certain animated intro's I get the same message either on the Mac running El Capitan or on Ubuntu Studio.  It tells me that I don't have blender installed, yet I do and it's the most up to date version.  And in the preferences it says "blender" under the blender executable section.  I've also tried "/usr/bin/blender" on Ubuntu.  I can see blender start with a flash of the flash screen but then the message is back.

**Comment by ankitpati** [comment]
No repro with OpenShot 2.2 AppImage on Ubuntu 16.04. Rendering works fine with blender installed.

Closing this as fixed. Please reopen if necessary.

**Comment by bkarlan** [comment]
1 year?  1 year to tell me you can't reproduce the problem?  1 year?

**Comment by ankitpati** [comment]
We regret the delay, but OpenShot has just one full-time developer working on it.

**Comment by bkarlan** [comment]
I've long ago gave up on this program.
