### ISSUE TITLE
I cant download

### ISSUE THREAD

**Issue by haiaah** [OpenShot/openshot-qt#1833]
I can't download the program for windows.

**Comment by peanutbutterandcrackers** [comment]
I was just able to download from the website (for windows). Please go to https://www.openshot.org/download/ and click on windows downloads and then click on 'download'. Alternatively, you could also use torrent. Hope that helps.

If that doesn't; please provide more details. Perhaps a screenshot of the webpage.

Also, it is possible that your internet connection isn't the best and that is why the download is failing... just a theory.

**Comment by peanutbutterandcrackers** [comment]
https://github.com/OpenShot/openshot-qt/releases/download/v2.4.2/OpenShot-v2.4.2-x86_64.exe

Clicking on the above URL should start 64 bit OpenShot's download for you.

**Comment by Bigbot1984** [comment]
I can't download openshot today. I always get this Error 403 after having dowloaded it for 15 minutes.
What's wrong with the server??

**Comment by peanutbutterandcrackers** [comment]
Perhaps something is wrong with the server. Could you please try downloading via torrent instead, please? I recommend [transmission bit torrent client](https://transmissionbt.com/). [Here](https://github.com/OpenShot/openshot-qt/releases/download/v2.4.2/OpenShot-v2.4.2-x86_64.exe.torrent) is the torrent. Either ways, this error should be resolved soon enough. Maybe it's just the service provider that is currently hosting the website? 

Hope that was helpful! :+1:

**Comment by Bigbot1984** [comment]
I did clicked on the "Torrent" link and it didn't let me download a torrent file. It instead makes me save the .exe file.

**Comment by shivajain03** [comment]
I am facing the same issue, after 10 minutes it says file is forbidden and it stops downloading.
I have tried multiple times but the same thing occurs.

**Comment by ferdnyc** [comment]
@shivajain03 

I just downloaded the same file, the transfer started immediately and took approximately 5 seconds. So, I don't know what to tell you. Try again, or perhaps try a different browser. The issue must be something local to your computer.

![image](https://user-images.githubusercontent.com/538020/65182777-0e04ed00-da30-11e9-828e-039f3e77ad2a.png)

**Comment by ferdnyc** [comment]
@shivajain03 If that doesn't work, you could also try finding the same file towards the very _**bottom**_ of the list at https://github.com/OpenShot/openshot-qt/releases/tag/daily and downloading from there.

It's ultimately the same servers providing the downloads either way, but perhaps it'll make some difference.
