### ISSUE TITLE
how can I write to the image

### ISSUE THREAD

**Issue by HaydutV5** [OpenShot/openshot-qt#1835]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by HaydutV5** [comment]
how can I write to the image

**Comment by peanutbutterandcrackers** [comment]
Sorry sir, we do not quite understand your problem.

If you want to write to an image, you could probably use [GIMP](https://gimp.org) or use [InkScape](https://inkscape.org) but maybe that is not what you're looking for...
