### ISSUE TITLE
Click on the timeline doesn't move playing position sometimes

### ISSUE THREAD

**Issue by singalen** [OpenShot/openshot-qt#1839]
Seems to mostly work when I click **and drag** the mouse a little.

**System Details:**
 - Operating System / Distro: MacOS 10.13
 - OpenShot Version: 2.4.2
![openshot-timeline](https://user-images.githubusercontent.com/151199/42602629-29985d20-851f-11e8-83f9-e89333b4ef7f.gif)

**Comment by peanutbutterandcrackers** [comment]
Can't reproduce on my [Elementary OS](https://elementary.io) machine. Perhaps it is a mac related issue? o.O

**Comment by DylanC** [comment]
@peanutbutterandcrackers - No problem. There is a bunch of Mac issues I will need to test in a testing session. :)

**Comment by N3WWN** [comment]
It seems to me that the "trick" is clicking on the timeline above the minor graduations (the top of the short lines).  Clicking below the top of the minor graduations results is no playhead movement for me, too.  Even if I click and drag, if the cursor is below the top of the minor graduations, it won't work.

**Comment by peanutbutterandcrackers** [comment]
@singalen - Does @N3WWN's suggestion work for you, sir?

@N3WWN - Is the action a little less responsive on a mac, and thus in need of some work? o.O

**Comment by N3WWN** [comment]
@peanutbutterandcrackers - I don't think it's any different on a Mac.  

I noticed in @singalen 's animated GIF that it was the vertical location of the cursor that determined if the click caused movement or not.  I replicated in Linux, FYI.

If there's no reason to NOT extend the clickable location to move the playhead, I can look at increasing it to include more of the lower portion.

**Comment by peanutbutterandcrackers** [comment]
@N3WWN - I see. I wonder if there is any reason NOT to increase it. But perhaps @DylanC or @ferdnyc  might have some insight into this? I don't really see why not...

**Comment by ferdnyc** [comment]
The strange thing about this is that it's _supposed_ to be clickable all the way down to the bottom of the ruler marks. And it is, in the timeline JS debugger. So, something's being set in Qt that's shrinking the clickable area of the ruler.

**Comment by DylanC** [comment]
@ferdnyc - I don't think something is shrinking the clickable area. I feel the click events are not registering sometimes. It happens at random intervals from my testing. A click on the ruler would just do nothing, clicking the same area again later works.

**Comment by ferdnyc** [comment]
I also just noticed that if you _drag_ a selection box from the Timeline area up into the ruler area, it moves the Playhead (which it probably shouldn't do), but **only** after you cross above the top of the Markers. While you're down in the Marker region, the Playhead ignores you. But the moment the selection rectangle crosses the point at the top of a Marker, the Playhead jumps to the mouse position, and keeps following as long as you're above that point.

**Comment by DylanC** [comment]
@ferdnyc 

> Hm, really? ...Do you mean in the debugger, or in OpenShot?

It was happening to me inside OpenShot. I will need to check the debugger to see what is happening there but I feel like it wasn't happening inside the debugger. You may be right about the marker area not being clickable. I will need to go over this again as your statements are making me question my own. 😆

**Comment by ferdnyc** [comment]
Yeah, in the Timeline debugger I never had any problems clicking anywhere on the ruler, it always moved the playhead. That was the thing that _surprised_ me, that the ruler behaved so differently between the debugger and OpenShot.

**Comment by DylanC** [comment]
@ferdnyc - I've had another look and unfortunately its as I first thought. So the ruler does have a "dead-zone" where the markers go. Clicking there produces no result. (obviously)

However, clicking the ruler in the "active" zones works perfect in the debugger/Chrome 100% of the time.  The bug only happens inside OpenShot. Some of the clicks do not trigger in the "active" zone at all. You can reproduce this behavior by clicking random spots (click only, no dragging).

**Comment by ferdnyc** [comment]
> So the ruler does have a "dead-zone" where the markers go. Clicking there produces no result. (obviously)

Regardless whether it's in the debugger or Qt, you mean? Yeah, I _think_ I see that now. It's weird how the markers **seem** to extend up so much higher in the Qt interface than the debugger, even though in reality I know they don't.

> However, clicking the ruler in the "active" zones works perfect in the debugger/Chrome 100% of the time. The bug only happens inside OpenShot. Some of the clicks do not trigger in the "active" zone at all. You can reproduce this behavior by clicking random spots until a click doesn't register any action as a result(click only, no dragging).

Honestly, I can't get it to do that, even after clicking around _quite_ rapidly for quite a while. It always seems to register my clicks. 

It _could_ possibly be a thread preemption / resource contention issue, since any move of the Playhead both (a) potentially triggers a cache frame being generated, and (b) always involves the preview thread. Are you using memory or disk cache, and how many cores does your machine have? On my 4-core i5 box with cache in memory (8G of RAM), so far I haven't been able to reproduce the issue.

Also, if you launch OpenShot from a terminal window so that you can see the console output, does it output either/both of the 
```
preview_thread:INFO previewFrame: 170
preview_thread:INFO self.player.Position(): 170
```
lines, for the missed clicks?

Next thing might be to add a `timeline.qt_log(playhead_seconds);` at `src/timeline/directives/ruler.js` line 116, to see whether the clicks are getting dropped in the JavaScript or the Qt end. When I do that, I get this output for each click (unless I accidentally drag instead):
```
timeline_webview:INFO 66.88
preview_thread:INFO previewFrame: 1606
preview_thread:INFO self.player.Position(): 1606
```

**Comment by ferdnyc** [comment]
(Unrelated:) I don't understand why those messages would _only_ be output for ruler clicks. <kbd>←</kbd> and <kbd>→</kbd> presses to move the Playhead also update the preview frame, and should involve the preview _thread_, but they only trigger this output:
```
      logger:INFO 16777236
 main_window:INFO keyPressEvent: Right
```
...Which means there's a _different_ code path for generating preview frames on mouse click, vs. generating preview frames from keyboard _moves_. That just seems bizarre.

**Comment by ferdnyc** [comment]
Oh, wow, it gets better. _These_ lines:
```
preview_thread:INFO previewFrame: 170
preview_thread:INFO self.player.Position(): 170
```
Are output only when  you _either_:
1. have no clip selected,
2. are clicking somewhere **inside** the area the selected clip occupies on the timeline

If you have a clip selected, and you click somewhere before or after the clip (on the ruler), no log output is generated. :scream:

**Comment by DylanC** [comment]
@ferdnyc - I'll have to get back looking at this again. Seems the problem may run deeper than we first thought.

**Comment by DylanC** [comment]
> Also, if you launch OpenShot from a terminal window so that you can see the console output, does it output either/both of the

> preview_thread:INFO previewFrame: 170
> preview_thread:INFO self.player.Position(): 170
> lines, for the missed clicks?

Nope, I don't get those lines for the missed clicks. I do get them for any successful clicks. 

> Next thing might be to add a timeline.qt_log(playhead_seconds); at src/timeline/directives/ruler.js line 116, to see whether the clicks are getting dropped in the JavaScript or the Qt end. When I do that, I get this output for each click (unless I accidentally drag instead):

> timeline_webview:INFO 66.88
> preview_thread:INFO previewFrame: 1606
> preview_thread:INFO self.player.Position(): 1606

For the missed clicks I do not get output for this to the console. I guess its on the Qt side then. Would make sense considering its perfect inside Chrome. Its definitely doing something on each click and just hanging every now and then on that function or thing its doing.

**Comment by stevesan** [comment]
i'm noticing this a lot right now. Windows 11, 64-bit.
Version: 3.3.0 | 0.4.0
OpenShot-v3.3.0-release-13186-621eb57a-6c4ada06 | Official
Release Date: 2024-12-22

**Comment by Colorjet3** [comment]
Hello @stevesan 

I am running Windows 11 Pro 24H2 and I am unable to replicate this issue.  I've tested this in these scenarios:
1.  Start OpenSHot (empty project).
2.  Open a large project
3.  Zoom in/out.

Questions for you:
1.  Is this repeatable?
2.  Does it happen when you first start OpenShot without opening a project?
3.  Does it happen in one specific project or multiple projects.
4.  If repeatable, does it happen at any specific time on the timeline or is it random?
5.  Anything else you can share?

Things to do:
1.  Ensure your WIndows has the latest Microsoft updates.
2.  Ensure your computer has the latest hardware updates.
3.  Restart your computer after all updates.
4.  Test OpenShot.  If problem persists, continu....
5.  Close OpenShot.
6.  Make a backup of c:\users\username\.openshot_qt folder.
7.  Delete c:\users\username\.openshot_qt folder.
8.  Start OpenShot and test.  If problem persists, continue...
9.  Close OpenShot.
10. Uninstall using Add or Remove Programs.
11.  go to openshot.org/download/#daily and download the latest dev daily build.
12.  Install OpenShot.
13.  Test
