### ISSUE TITLE
openshot and archlinux

### ISSUE THREAD

**Issue by DrWaleedAYousef** [OpenShot/openshot-qt#184]
I downloaded the AppImage, changed it to executable. However, running it on ArchLinux gives me:

fuse: device not found, try 'modprobe fuse' first
Could not mount AppImage
Please see https://github.com/probonopd/AppImageKit/wiki/FUSE

Then I tried mounting directly without FUSE:
sudo mount -o loop OpenShot-2.0.7.AppImage /MyMount

It gives me this:
mount failed: Unknown error -1

Any help?

**Comment by probonopd** [comment]
Please check the md5 sum of your download. Maybe it wasn't downloaded entirely?

**Comment by DrWaleedAYousef** [comment]
it check successfully

**Comment by probonopd** [comment]
That is strange. At least the loop-mounting should work anywhere. Can you loop-mount other ISO files and/or AppImages?

**Comment by DrWaleedAYousef** [comment]
Sorry for the very long delay! I can mount devices NOT iso images !!! So, I think I may have a problem but I do not know what it is. I am using Archlinux.

**Comment by jreynojustin** [comment]
@DrWaleedAYousef 

This is not an issue related to the project and therefore I am closing the issue.

However, the Openshot package is available in the AUR. I recommend you install it through there. See: https://www.archlinux.org/packages/community/any/openshot/
