### ISSUE TITLE
Thumbnail Generator

### ISSUE THREAD

**Issue by emeterioy** [OpenShot/openshot-qt#1842]
Hi, I just downloaded this software and I have a question, I tried to look for an answer but couldn't find one. How do I generate my own thumbnail when I save the video that I edited, it looks like the software automatically generate one from the first image that's on the video. issue is that I have an intro in my video so that means that the same image will show up in thumbnail. can I choose my own?

**Comment by peanutbutterandcrackers** [comment]
Hmm... I don't really know about a way to generate custom thumbnails...

@DylanC - Perhaps you might have some ideas regarding this, Cap'ain?
@N3WWN - Perhaps you, sir?

**Comment by N3WWN** [comment]
@emeterioy - Are you looking to change the frame from the video which is used as the thumbnail in the `Project Files` and on the timeline?

**Comment by emeterioy** [comment]
When I export the video into my computer, I want to change the mp4 thumbnail of the video that I exported. To a different thumbnail within that video.

**Comment by peanutbutterandcrackers** [comment]
I wonder if that can be controlled by a program like OpenShot. To me it seems like the issue of the File Manger... but then again, I don't really know much about this...

**Comment by DylanC** [comment]
@emeterioy  @peanutbutterandcrackers - This is not in our control. The thumbnail shown would be a result of whatever the OS is doing.
