### ISSUE TITLE
Feature Request: Toggle Checker-board Transparency

### ISSUE THREAD

**Issue by peanutbutterandcrackers** [OpenShot/openshot-qt#1844]
I would like to request a feature where the transparency can be toggled to be displayed as checker-board, like in GIMP among other softwares. And then in the end, it would render as black or any color the user chooses. Currently the UI renders transparency as black. It would also be nice if the background color (the color to which transparency is changed to) to be user-set-able. That would be pretty neat too.

**Comment by N3WWN** [comment]
@peanutbutterandcrackers - Got another workaround for you... 😜 

How about putting an image like the following on the bottom track and removing it before you render:

![image](https://user-images.githubusercontent.com/19431804/42705515-8c4e5888-86a1-11e8-8b1f-eb82b829dcc4.png)
https://cdn3.vectorstock.com/i/1000x1000/31/62/checkerboard-pattern-seamless-checkered-vector-14763162.jpg

You could replace that image with any image that you'd like.  😉 

Although I could see the displaying of transparency as useful in the preview window, so perhaps we could have a toggle button to turn on a non-rendering checkerboard layer.

**Comment by peanutbutterandcrackers** [comment]
@N3WWN - Work-around man to the rescue! Haha! This is actually neat.

I wish we could have two radio buttons. One would be transparency button (checker-board transparency) and another would be color button in which the color could also be set. That way the user could choose which color they want to render transparency into. Instead of just plain old black.

**Comment by N3WWN** [comment]
I think this feature would still be desirable.

**Comment by N3WWN** [comment]
I continue to think this feature would still be desirable.
