### ISSUE TITLE
Transform Tool Enhancements

### ISSUE THREAD

**Issue by peanutbutterandcrackers** [OpenShot/openshot-qt#1845]
1. So, evidently, transform tool in OpenShot behaves like the one in InkScape in that in order to preserve the aspect ratio, CTRL has to be pressed while dragging the corner sides. This probably needs to be documented. Also, since we're going the InkScape route, I think it'd be nice to use the status bar in OpenShot to display help about the transform tool (and others too, perhaps), like InkScape does. [Note the InkScape Status bar: "**Ctrl** to scale uniformly"]
![screenshot from 2018-07-13 15-17-41](https://user-images.githubusercontent.com/26764547/42684474-e8ec3ca0-86af-11e8-9c11-5462b17801a7.png)

2. As requested in #1487, let's enhance the transform tool again to have rotation feature in it - but like InkScape. Let's have clicks toggle the transform tool's handles between scale and rotation. There will be a need for visual cue (apart from the text on the status bar) in the transform tool itself to let users know of the change in it's property. Rotation handles need to be different. Transform handles are fine as they are right now.

3. When scaling the clip using the transform tool, currently, the preview tab limits how far the user can drag (and thus how much the user can scale the clip). I propose that we use *recursive transformation handles* that would line up at the same points where the original nodes would have been, once the original ones extend beyond the preview tab. That way, the user can scale their clips to however much they want. Here is a sample idea of how it would look:
![transform_tool_recursion](https://user-images.githubusercontent.com/26764547/42684783-db704ebc-86b0-11e8-8082-8327173f0829.png)
The red inner transform handles would show up once the blue ones go beyond the video preview, and work work exactly the same. The user would be able to scale down or up using the new or original handles.

**Comment by Hunteil** [comment]
I think the Status bar feature can be moved to a separate suggestion. It's definitely something I want to comment on without over throwing the other topics of this thread. Please give link when created and I'll throw in examples for that. :-)

**Comment by peanutbutterandcrackers** [comment]
@Hunteil - #1858 :)
