### ISSUE TITLE
Adding text

### ISSUE THREAD

**Issue by xfatimia** [OpenShot/openshot-qt#1847]
**My Question:**
Can you add text to your video?

**System Details**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**Screenshots**

**Comment by N3WWN** [comment]
I think you may be looking for the `Title` menu. 😁

**Comment by DylanC** [comment]
@xfatimia - Follow suggestion by @N3WWN. Thanks.
