### ISSUE TITLE
Contribute on development

### ISSUE THREAD

**Issue by francescoBLT** [OpenShot/openshot-qt#1848]
HI
my company is interested in developing a plugin or an interface in order to make our custom  video file format compatible with OpenShot. We operate on Windows. I've yet developed plugin interface for VLC (crosscompiling from Debian Linux) and ffmpeg (compiled under Windows with minGW). I have some questions:
 Did you have a starting tutorial in order to develop plugins ? 
 Did you suggest to develop under windows or crosscompiling from linux ?  
 Did you have some writing rules used in development ?
Regards 
Francesco

**Comment by peanutbutterandcrackers** [comment]
Um... @DylanC - Do you know anything about this, Cap'ain? @N3WWN ?

@francescoBLT - While I don't know much about the things under-the-hood in OpenShot, perhaps if the company wants to make some contributions, [this](https://www.openshot.org/static/files/user-guide/developers.html) would be a good starting guide. Hopefully someone else will soon be able to answer the rest of your questions.

**Comment by DylanC** [comment]
@peanutbutterandcrackers - I don't think we support plugins as far as I know. Maybe they could just contribute the features they need. However, the features would have to be acceptable in terms of what this project plans to be feature wise.

**Comment by DylanC** [comment]
@francescoBLT - Hi there, do you have details on what this custom format is?

**Comment by N3WWN** [comment]
@peanutbutterandcrackers - If they use a package of OpenShot that uses the system ffmpeg, import support may "just work" because it looks like libopenshot will try to open any file supported by ffmpeg, but output support would probably need to be added into openshot-qt (a preset?) to have a persistent output format.  Manually setting the output format via the `Export Video`->`Advanced`->`Video Settings` may work, too.

**Comment by peanutbutterandcrackers** [comment]
[This guide](https://www.openshot.org/static/files/user-guide/profiles.html#custom-profile) should probably be a bit helpful, then... Hopefully...

**Comment by francescoBLT** [comment]
I apologize for the delay, I wasn't at office.  Thanks to all for the answeres, I will study the documentation now. Asap I receive the autorization I will make available a documentation of our format (or,  if you have a directory where upload a file it will be better)
Regards
Francesco

**Comment by DylanC** [comment]
@francescoBLT - You can provide the details here or attach the file here. Drag and drop to attach the file.

**Comment by francescoBLT** [comment]
BLT ESSENCE PAYLOAD SEGMENT

The BLT Essence Payload Segment is made by sequential Frames in a minimum number as per DURATION
Tag in the BLT HEADER; any Frame can be randomly accessed using the byte offset value indicated in the
BLT TABLE SEGMENT; a Frame is composed by two Field (named 0 / 1 or Top / Bottom).
The Lenght of each Field is specified in the BLT TABLE SEGMENT (please note each field can be different
size). Even in case of PROGRESSIVE materials (ie. 720p) the FRAME is composed by two Field, each one
representing a FULL frame picture; in other words, when progressive the frames are grouped two by two for
seamless transition between Interlacved and progressive materials.
Each single FIELD (containing a complete TV Field) of the BLT PAYLOAD ESSENCE segment, is composed
as follow: 
__________________________________________________________________________________________
| HEAD  |  TCD  |         AUDIO ESSENCE         |         VIDEO ESSENCE  | ZERO STUFFING |
__________________________________________________________________________________________

The FIELD HEAD is fixed lenght of 16 Bytes and it can be used for identifyng start of FIELD (in case of
streaming). It is mandatory the first part of FIELD and indicates the start.The FIELD HEAD is 4DW with
these fixed values: 0xFFFFFFF8 0x00000000 0x00000000 0x00000000
The FIELD TCD is fixed lenght of 20 Bytes and it carries the Time Code information as per SMPTE12m -
LTC. The FIELD TCD is 5DW with this use:
DW1 is fixed value 0xFFFFFFF4
DW2 + DW3 is SMPTE LTC as below detailed table (8 Bytes)
DW5 + DW5 is used for extended TCD info
TCD bit assignement as per SMPTE12m – LTC
TCD Byte
1 bit [3:0] = FRAME lsb (9..0) bit[7:4] UBIT 3:0
2 bit [1:0] = FRAME Msb (2..0) bit[2] = DF bit[7:4] UBIT
3 bit [3:0] = SEC lsb (9..0) bit[7:4] UBIT
4 bit [2:0] = SEC Msb (5..0) bit[7:4] UBIT
5 bit [3:0] = MIN lsb (9..0) bit[7:4] UBIT
6 bit [2:0] = MIN Msb (5..0) bit[7:4] UBIT
7 bit [3:0] = HOUR lsb (9..0) bit[7:4] UBIT
8 bit [1:0] = HOUR Msb (2..0)
The FIELD AUDIO ESSENCE carries the Audio datas with multitrack capabilities (4/8/16 mono tracks) and it
is composed by a Marker/Header and followed by the Audio payload. The lenght of Audio Payload is variable
in function of the number of Audio tracks and TV Standard (ie. 50Hz or 59.94Hz). The structure is:
------------------------------------------------------------------------------------------------------
| AUDIO MARKER | AUDIO HEADER   | AUDIO PAYLOAD                                                            |
| 0xFFFFFFF5         |  LL ID (2x2 Bytes) |                                                                                        |
------------------------------------------------------------------------------------------------------
The DW of Audio Header indicates the lenght and type of Audio Payload.
Bit[31:16] is the Total Bytes Lenght of FIELD AUDIO ESSENCE (including MARKER+HEADER+PAYLOAD).
Bit[15:0] is Audio ID, with following legal values (at present specs):
0x0083 4 Audio Tracks
0x0087 8 Audio Tracks
0x008F 16 Audio Tracks
Number of Audio Samples per FIELD is 960 with TV Standard 50Hz otherwise it is 802/800 with TV Standard
59.94Hz (the M format). So, the Total Bytes Lenght and ID will have following values:
Lenght                    Value ID                      Byte Lenght                 TV Std                          DESCRIPTION
0x1E04                    0x0083                            7684                          50Hz                        4 Audio Tracks
0x1904/0x1914       0x0083                        6404/6420                    59.94Hz                    4 Audio Tracks
0x3C04                    0x0087                          15364                         50Hz                         8 Audio Tracks
0x3204/0x3224       0x0087                       12804/12836                 59.94Hz                    8 Audio Tracks
0x7804                    0x008F                          30724                         50Hz                        16 Audio Tracks
0x6404/0x6444       0x008F                       25604/25668                 59.94Hz                   16 Audio Tracks

When TV Standard is 59.94Hz (the M format) the typical lenghts sequence is 5 FIELD long and it is:
800/802/800/802/800. Reader should tolerate different sequences also.
The Audio Payload is composed by sequential values, Little indian ordered (LSB byte first), with ordered
Audio tracks in sequence Sample by Sample, that is:
4 Audio tracks: 1/2/3/4/1/2/3/4 ...
8 Audio tracks: 1/2/3/4/5/6/7/8/1/2/3/4/5/6/7/8 ...
16 Audio tracks: 1/2/3/4/5/6/7/8/9/10/11/12/13/14/15/16/1/2/3/4/5/6/7/8/9/10/11/12/13/14/15/16 ...

**Comment by francescoBLT** [comment]
The FIELD VIDEO ESSENCE carries the compressed Video datas; the current specs of this document
specify JPEG2000 (ISO/IEC 15444-1) as image compression standard wavelet based. Refer to ISO/IEC
15444-1 for deep details about Codec and wavelet details.
The Video essence can be in two flavours: merged (luma and chroma interleaved) or split (luma and
chroma separated). The possible structures are:

MERGED:
---------------------------------------------------------------------------
|  VIDEO MARKER  | VIDEO HEADER  | VIDEO / JP2K PAYLOAD (Y+C) |
|  0xFFFFFFF0/1      |   (12 Bytes)         |                                                 |
---------------------------------------------------------------------------
SPLIT:
------------------------------------------------------------------------------------------------------------------
|  VIDEO MARKER  | VIDEO HEADER  | VIDEO / JP2K  | VIDEO MARKER  | VIDEO HEADER  | VIDEO / JP2K |
|  0xFFFFFFF0/1      |  Y  (12 Bytes)      |  Y PAYLOAD    | 0xFFFFFFF2/3      | U,V  (12 Bytes)   | U,V PAYLOAD |
-------------------------------------------------------------------------------------------------------------------


VIDEO MARKER VALUES:
MARKER           Byte LEN        DESCRIPTION
0xFFFFFFF0          4                  Field 0 (TOP) merged or split mode, at begin of FIELD VIDEO ESSENCE
0xFFFFFFF1          4                  Field 1 (BOTTOM) merged or split mode, at begin of FIELD VIDEO ESSENCE
0xFFFFFFF2          4                  Field 0 (TOP) split mode only, at begin of CHROMA Payload
0xFFFFFFF3          4                  Field 1 (BOTTOM) split mode only, at begin of CHROMA Payload

hint: how to understand if VIDEO PAYLOAD is merged or split.
First method: Reader can check if Chroma Marker is following the Video Payload, that is once got first
MARKER (0xFFFFFFF0/1) in the FIELD VIDEO ESSENCE, use the PAYLOAD LEN + 16 as byte offset to
check at the end of Payload if next value is a Chroma Marker (0xFFFFFFF2/3).
Second method: Reader can check the value of byte at offset 22 (from begin of FIELD VIDEO
ESSENCE), if value is 0x2F then Payload is merged mode, any other value is split mode.

**Comment by francescoBLT** [comment]
At the end of these long posts a question:
I've compiled openshot under Linux Ubuntu 18.04 following the instructions at:

https://openshot.org/static/files/user-guide/developers.html

all works fine. The question is: How I can cross compile for windows ?
Regards

**Comment by DylanC** [comment]
@francescoBLT - Apologies for the late reply. As far as I know we do not cross compile. @ferdnyc Do we?

**Comment by ferdnyc** [comment]
Not to my knowledge. OpenShot itself isn't compiled anyway, but libopenshot and -audio are and AIUI the packaged builds are compiled for Windows on Windows. The tricky part isn't so much doing the build, it's getting all of the dependencies sorted out. The only guide I know of with any information on how to do so is [this one](http://openshot.org/files/libopenshot/InstallationGuide.pdf) which was written in 2008, last updated in 2015, and is out of date enough that it has not proved particularly helpful in my experience. 

(The only definitive statement I can make about compiling libopenshot on Windows is that at one point I tried to figure out how to do it. I never succeeded.)
