### ISSUE TITLE
/libopenshot.so.8: undefined symbol: _ZN6Magick12DrawableFontC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

### ISSUE THREAD

**Issue by shakaran** [OpenShot/openshot-qt#185]
Ubuntu 16.04
Openshot 2.0.7 with PPA

```
$ openshot-qt 
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
      logger:ERROR Traceback (most recent call last):
      logger:ERROR   File "/usr/bin/openshot-qt", line 9, in <module>
      logger:ERROR load_entry_point('openshot-qt==2.0.7', 'gui_scripts', 'openshot-qt')()
      logger:ERROR   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
      logger:ERROR return get_distribution(dist).load_entry_point(group, name)
      logger:ERROR   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
      logger:ERROR return ep.load()
      logger:ERROR   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
      logger:ERROR return self.resolve()
      logger:ERROR   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
      logger:ERROR module = __import__(self.module_name, fromlist=['__name__'], level=0)
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 53, in <module>
      logger:ERROR from classes.app import OpenShotApp
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 41, in <module>
      logger:ERROR import openshot
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot.py", line 28, in <module>
      logger:ERROR _openshot = swig_import_helper()
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot.py", line 24, in swig_import_helper
      logger:ERROR _mod = imp.load_module('_openshot', fp, pathname, description)
      logger:ERROR   File "/usr/lib/python3.5/imp.py", line 242, in load_module
      logger:ERROR return load_dynamic(name, filename, file)
      logger:ERROR   File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
      logger:ERROR return _load(spec)
      logger:ERROR ImportError
      logger:ERROR :
      logger:ERROR /usr/lib/x86_64-linux-gnu/libopenshot.so.8: undefined symbol: _ZN6Magick12DrawableFontC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

**Comment by clockworkpc** [comment]
Operating System: Ubuntu 16.04

Openshot Version:
Package: openshot-qt
Version: 2.1.0+0+668+103+201608300650~ubuntu16.04.1
Priority: optional
Section: video
Maintainer: Ghislain Antony Vaillant <ghisvail@gmail.com>
Installed-Size: 158 MB
Depends: python3-httplib2, python3-openshot, python3-pyqt5, python3-pyqt5.qtmultimedia, python3-pyqt5.qtopengl, python3-pyqt5.qtsvg, python3-pyqt5.qtwebkit, python3-xdg, python3-zmq, qttranslations5-l10n, python3:any (>= 3.3.2-2~)
Suggests: openshot-qt-doc
Download-Size: 84.0 MB
APT-Manual-Installed: yes
APT-Sources: http://ppa.launchpad.net/openshot.developers/ppa/ubuntu xenial/main amd64 Packages
Description: OpenShot video editor
 OpenShot Video Editor is a free, open-source, non-linear video editor. It can
 create and edit videos and movies using many popular video, audio, and image
 formats. Create videos for YouTube, Flickr, Vimeo, Metacafe, Xbox, and many
 more common formats!

Terminal Output:
logger:ERROR Traceback (most recent call last):
      logger:ERROR   File "/usr/bin/openshot-qt", line 9, in <module>
      logger:ERROR load_entry_point('openshot-qt==2.1.0', 'gui_scripts', 'openshot-qt')()
      logger:ERROR   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
      logger:ERROR return get_distribution(dist).load_entry_point(group, name)
      logger:ERROR   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
      logger:ERROR return ep.load()
      logger:ERROR   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
      logger:ERROR return self.resolve()
      logger:ERROR   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
      logger:ERROR module = __import__(self.module_name, fromlist=['__name__'], level=0)
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 53, in <module>
      logger:ERROR from classes.app import OpenShotApp
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 40, in <module>
      logger:ERROR from classes import info, settings, project_data, updates, language, ui_util, logger_libopenshot
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot_qt/classes/logger_libopenshot.py", line 31, in <module>
      logger:ERROR import openshot
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot.py", line 28, in <module>
      logger:ERROR _openshot = swig_import_helper()
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot.py", line 24, in swig_import_helper
      logger:ERROR _mod = imp.load_module('_openshot', fp, pathname, description)
      logger:ERROR   File "/usr/lib/python3.5/imp.py", line 242, in load_module
      logger:ERROR return load_dynamic(name, filename, file)
      logger:ERROR   File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
      logger:ERROR return _load(spec)
      logger:ERROR ImportError
      logger:ERROR :
      logger:ERROR /usr/lib/python3/dist-packages/_openshot.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN8openshot12FFmpegWriter15SetAudioOptionsEbNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiiNS_13ChannelLayoutEi

**Comment by jonoomph** [comment]
This has been fixed. Thanks.
