### ISSUE TITLE
how can i make an transition but for the end?

### ISSUE THREAD

**Issue by f399kl** [OpenShot/openshot-qt#1850]
**My Question:**

i think ist simple to explain (kinda). so is there a way to make something like an Transition but for the end of a Video?so the Video just doesnt look like i just cutted it of? thanks

**System Details**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**Screenshots**

**Comment by DylanC** [comment]
@f399kl - Normally via the right click menu I do a fade out. Is this what you are looking for?

**Comment by benrob0329** [comment]
If you have a transition over just one clip it will transition to black from my knowledge.
