### ISSUE TITLE
Error when Exporting

### ISSUE THREAD

**Issue by MadelineLee6146** [OpenShot/openshot-qt#1851]
Hey. I've been trying to export this video for three days and it keeps coming up with 1: a runtime error
And 2: there was an error exporting raw frames or something similar...
...please help...

**Comment by DylanC** [comment]
@MadelineLee6146 - Hi there, do you have a screenshot at all?

**Comment by Thomas2811** [comment]
I worked long time on video...and now i cant export...its really disappointing. 

Its 10 minutes duration. Try export as mp4 2,5 K, 1080p and others. 

Openpoint closes without notification while exporting.

**Comment by jakalope** [comment]
Same here. I'm using 1080p input video and trying to export in YouTube-HD format. It gets 0.1% through and closes the window unexpectedly.

**Comment by jakalope** [comment]
Just tried it with [this](https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.4.2-dev1-1531493711-628eb373-554d9f2f-x86_64.exe) version and got the same result.

**Comment by jakalope** [comment]
Okay, figured out _my_ issue. I have a 2-socket Xeon and if I set the CPU Affinity to use only one of the two sockets, it does not crash.

**Comment by keaim** [comment]
Pareil pour moi sous windows 10, impossible d'exporter une vidéo. Quelle est la solution? merci

**Comment by MadelineLee6146** [comment]
Sadly i have no screenshot. Its on a seperate device to what im using now but i think i figured out one issue

**Comment by peanutbutterandcrackers** [comment]
I would advise you to [attach the logs](https://gist.github.com/peanutbutterandcrackers/d84c257e74b72d8b06b4daffaebc5a14). That should help out the devs investigate more into this issue...

**Comment by Torniojaws** [comment]
I also could not export a video composed of 4 separate videos edited into one 5 minute video with about 40 cuts and one wav audio file. The export would crash regardless of settings (Web / YoutubeHD, H264, etc). I downgraded to version 2.4.1 and exporting the same project was succesful.

I would attach the log file, but it is **500 MB** in size(!!). Here's one from the log rotation files that was created around the crash:


[openshot-qt.log.2.zip](https://github.com/OpenShot/openshot-qt/files/2238412/openshot-qt.log.2.zip)

**Comment by mikevir** [comment]
Ditto here, export failed at about a quarter of the way through.  It would only work if all transitions were removed - the project had six of them.  Reverted back to 2.4.1 which has no export problems.
