### ISSUE TITLE
Issue with FLAC

### ISSUE THREAD

**Issue by Gitlab1111** [OpenShot/openshot-qt#1852]
Whenever I'm trying to make a video with FLAC music files I get a buggy sound in the first 2 seconds of it when I play it or export it.  Putting it on different tracks don't work either. the sound is heard about a fraction of a second but is still noticeable and annoying.

Using Openshot Version 2.4.2 on a Linux Mint 19 Tara Cinnamon PC. Using it from the installed PPA and not the app image version.

**Comment by peanutbutterandcrackers** [comment]
Hmm... strange. On my machine, with [this `.flac` file](https://ia800307.us.archive.org/34/items/MusopenCollectionAsFlac/Bach_GoldbergVariations/JohannSebastianBach-01-GoldbergVariationsBwv.988-Aria.flac) imported into the timeline, the interface freezes up.
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2197381/openshot-qt.log)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/2197382/libopenshot.log)

OS: Elementary OS 0.4.1 'Loki'
OpenShot Version: 2.4.2-dev1 (daily PPA)

**Comment by DylanC** [comment]
@Gitlab1111 - I can hear it too. Confirmed.

**Comment by DylanC** [comment]
Dup of #1480

**Comment by SmashManiac** [comment]
Reproduced on Windows 7. Audio stutters at the end too. The issue occurs in Preview File as well.

**Comment by Gitlab1111** [comment]
Even when using the app image version OpenShot-v2.4.3-x86_64.AppImage I still get the strange sound error. Is this being looked into?
![openshot flac error](https://user-images.githubusercontent.com/41243135/50426966-03764800-0850-11e9-8966-4a068dde3fa9.png)

Still the sound can be heard right from the start of the video.
