### ISSUE TITLE
[MAJOR ISSUE] Openshot Fails To Find Missing Clips

### ISSUE THREAD

**Issue by MisterTeeXD** [OpenShot/openshot-qt#1853]
**Describe the bug**
When a file is moved but remains in the same drive, Openshot fails to find the missing files

**System Details (please complete the following information):**
 - Operating System / Distro: Windows 10
 - OpenShot Version: 2.4.2

**To Reproduce**
1. Go to File
2. Click on Open Project
3. Select Any Project
4. See error when Openshot asks for the missing files

**Expected behavior**
Openshot would find the files automaticly without painstakingly having the user finding it 

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**
I went through a pain telling Openshot where the files are and then when I tell Openshot where the final video clip is, it repeatedly gives an error where the file cannot be found

**Comment by peanutbutterandcrackers** [comment]
Closing as dup of #1118 and #1320 

Work is currently in progress to fix this and should be fixed in the future releases. Thank you for pointing this out, BTW. :+1:
