### ISSUE TITLE
How to handle the incompatibility of openshot and libopenshot in the repository?

### ISSUE THREAD

**Issue by gorgonz** [OpenShot/openshot-qt#1855]
**My Question:** Starting openshot (after install) I receive an error, that libopenshot must be V2.x, but I don't have it. On the other hand I read in the internet, that there is no reason to require the V2.x version in this version. How should I go on?

**System Details**
 - OpenSUSE tumbleweed
 - where there is offered openshot in version 2.4.2-1.1 and libopenshot in version 0.1.9-2.1. 

**Screenshots**

**Comment by peanutbutterandcrackers** [comment]
@gorgonz - How did you install OpenShot on tumbleweed, sir? This is a known issue with the PPAs, though. Happened on my Ubuntu 16.04 based machines too. However, if you try and forcibly install `python3-openshot` and `libopenshot`, apparently it'll be fixed. But I'm not that sure here...

Maybe something's up with the packaging? For the moment, you could probably try out Flatpaks or AppImages...

**Comment by gorgonz** [comment]
i used the official OSS repository, the link is:
http://download.opensuse.org/tumbleweed/repo/oss/x86_64/

**Comment by peanutbutterandcrackers** [comment]
I wonder if you should try contacting the package maintainers regarding this...

**Comment by peanutbutterandcrackers** [comment]
Or, if you want to, you can always build it from the source...

**Comment by DylanC** [comment]
@gorgonz - Follow what @peanutbutterandcrackers was saying. I think its the package maintainer you would need to contact.

**Comment by gorgonz** [comment]
close is accepted. Thx for staying polite, it was my fault indeed, to address it here ;-). I will follow both advices.
