### ISSUE TITLE
Make use of Status Bar

### ISSUE THREAD

**Issue by peanutbutterandcrackers** [OpenShot/openshot-qt#1858]
OpenShot does have a status bar but it isn't used. It would be nice if we could make extensive use of the status bar. Here are some ideas:
1. Display keys to change tool options when a tool is selected (like InkScape)
2. Display what values can be put in for property parameters
3. Display Rendering status - i.e. the preview generation (generation preview 11.5%); that would help the users not get too impatient with the program

**Comment by Hunteil** [comment]
I 500% back this!

Plenty of programs utilize the status bar constantly. Why not Openshot?
More importantly when the program is auto-saving, or when it's loading something like a preview. Or let's say you're using a tool, it can list out various short cut keys or tips.
