### ISSUE TITLE
Playback with Preview Window is slow and doesn't load sometimes

### ISSUE THREAD

**Issue by idonthavekids** [OpenShot/openshot-qt#186]
I've just started using OpenShot, and I've run into a pretty big problem.

When I import a video, it seems to play at 1/2 of the speed that it should and sometimes, if the clip is anywhere close to 30 seconds long or more, the Video Preview just freezes.

Could this be due to a slow computer or is it a problem with the software?

Thanks.

**Comment by quebecblogue** [comment]
Yes, I have the same issue... I import a 12 seconds clip and as soon as I am trying to preview it, it freezes OpenShot at first but if I don't act it's even freezing my Ubuntu 16.04 system.

I doubt my computer sucks that much and I have 16GB of ram.

I really want to make this works.

**Comment by singpolyma** [comment]
Probably related to #165

**Comment by DylanC** [comment]
@idonthavekids - Possibly older version tested here. Although the version is not mentioned. Please log a new ticket if the issue exists in 2.3.4. Thanks.
