### ISSUE TITLE
slow down of audio/video  past 2 min mark on the time line with 11 tracks at once

### ISSUE THREAD

**Issue by bobcrikey** [OpenShot/openshot-qt#1860]
hello, iv notice a huge slow down of the audio and the video past the 2 min mark 
with 11 tracks being used at once.

now i dont know whether its a memory leak or what would cause openshot 2.4.2 to do this
most of my tracks are mixtures of png's , some jpegs, some chromakey png's plus the wav files
for my animations. there are no transitions either.
its happening on my linux mint and on my (win 10 version  although not so bad but still there.)

it seems fine if you have 4 video tracks and one audio , but once past that the slow down kicks in .

i thought i'd share whats happening with my animation work on 2,4,2 and hoping one of the dev's
might have a few ideas on how to improve this situation to help openshot develop better and
to get rid of the audio/video bugs slowing the system down 

oh my system is an Amd ryzen 1600 6 cores 12 threads with 16 gigs of dual channel ram:)

cheers 
  bob

**Comment by peanutbutterandcrackers** [comment]
Hmm... thank you for the report. Could you please also [attach the logs](https://www.openshot.org/static/files/user-guide/profiles.html#custom-profile)? Thank you.

In the meantime, @DylanC - Cap'ain, I think this one also needs some more testing...

**Comment by bobcrikey** [comment]
hello everyone, heres the log from my linux mint version of openshot 2.4.2 in order to save it properly
i had opened in libre office and it wanted to save out only in libre office format .

i forgot to say apon export the video is perfect with the sound, its just the slow down on the timeline
for play back, past the 2 mins mark,
so im hoping it can be solved .
[openshot-qt.log.odt.tar.gz](https://github.com/OpenShot/openshot-qt/files/2200299/openshot-qt.log.odt.tar.gz)


cheers 
  bob

**Comment by DylanC** [comment]
@bobcrikey - Try v2.4.3 and let us know if you still have a problem.

**Comment by bobcrikey** [comment]
Hello again, im just starting to use 2.4.3 now for my 2nd episode of
starwars, will get back to you
when i start doing up to 10 tracks at once,

cheers
 bob

**Comment by DylanC** [comment]
@bobcrikey - Thanks bob.
