### ISSUE TITLE
Export video Crashes on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by shivdhwaj** [OpenShot/openshot-qt#187]
Every thing goes fine but when tried to export the CPU utilization raises above 90% suddenly after export and then boom openshot crashes.

**Comment by fweng322** [comment]
I wonder if it used too much memory.

My test result:

1. Openshot 2.0.7 Windows x64, put a video clip in track 4 and two audio clips in track 3.  The preview was not smooth at all, and crashed while previewing.

2. Openshot 1.4 Linux, put the same video clip in track 2 and same audio clips in track 1.  The preview was very smooth and export with profile 720p30 H.264 was successful.  The exported mp4 size is 10MB.

3. Openshot-qt 2.0.7 Linux (installed from ppa) test with the same condition.  The preview was not smooth at all but it completed the preview.  Then when exporting to about 60% it crashed.  The second try of exporting succeeded, and the exported mp4 size is 43MB.

**Comment by DylanC** [comment]
@shivdhwaj - Closing since this relates to a much older version of OpenShot. Please verify if the problem exists in newer versions and report a new issue.
