### ISSUE TITLE
Can I use Open Shot to open dmsm files?

### ISSUE THREAD

**Issue by Emac477** [OpenShot/openshot-qt#1870]
I have created many video files using Roxio. Since this time my computer crashed and I lost the original download file to re-install. Can I use this software to open them?
Edited to note Operating System....
I am using a HP Envy laptop running Windows 10

**Comment by DylanC** [comment]
@Emac477 - No, sadly these files are specific to Roxio. Its a project file format for that editor. Openshot has its own project file format called .osp.
