### ISSUE TITLE
Transitions crash every time

### ISSUE THREAD

**Issue by Cmax74** [OpenShot/openshot-qt#1871]
**Describe the bug**
Transitions crash every time. It does not matter if I play the preview or convert the video. Always ! It is frustrating !**System Details (please complete the following information):**
 - Operating System / Distro: Windows 10
 - OpenShot Version newest

**Comment by DylanC** [comment]
@Cmax74 - Transitions work fine on my Linux box. I have tried on a Windows 10 VM but Openshot generally wasn't running too well. A more fair test to reproduce would be on a real Windows machine if someone else could test this for you.

**Comment by rcook** [comment]
Reliably crashes for me too. Windows 10. The timeline is a simple text title transitioning into an .flv video clip.
