### ISSUE TITLE
Opening a previously saved .osp file shows only a blank project [macOS]

### ISSUE THREAD

**Issue by GitGianluc** [OpenShot/openshot-qt#1872]
Steps to reproduce:
1. Open a new project
2. Import a clip or any other file
3. Select “File > Save project”, assign a project name (without weird characters or blank spaces) and save in whichever folder you wish
4. Close OpenShot
5. Double click on the saved file: a blank project is displayed. The only way I found to reopen it is to select the desired project from “File > Recent projects”.

Software version (for both creating and trying to open the saved file): 2.4.2
Platform: Mac OS X 10.11 El Capitan

**Comment by DylanC** [comment]
@GitGianluc - Can you open the .osp file in a text editor and check if it actually has content? We came across this before but basically the file didn't save due to a sudden system shutdown. Different case to yours of course but maybe the file is also blank for you.

**Comment by GitGianluc** [comment]
@DylanC – That's a good point, thank you! Anyway: I opened the file in Sublime Text and is not empty... :-(

**Comment by DylanC** [comment]
@GitGianluc - I will give this a try on my Mac for you.

**Comment by DylanC** [comment]
@GitGianluc - I think this is directly related to #2162. He can open project files from inside the editor but not via the file manager.

**Comment by DylanC** [comment]
@ferdnyc - Did Openshot open project files if passed via an argument to the main binary? I would find it strange if it never did this.

**Comment by ferdnyc** [comment]
That's an excellent question. It _must've_, since the `.desktop` file includes the line:
```
Exec=openshot-qt %F
```

Which means this is something I broke when I added the command-line arguments. I'll look over those changes and get it fixed up ASAP.
