### ISSUE TITLE
Problems with the translation into the Portuguese language.

### ISSUE THREAD

**Issue by mnwstl** [OpenShot/openshot-qt#1873]
System Details:
 - Linux / ubuntu 18.04
 - OpenShot Version 2.4.2 (ppa).

It seems to confuse Portuguese of Portugal (PT), European, with Portuguese of Brazil (Pt_BR), Latin America. The descriptive is: "Português do Brasil (pt)" and "Português do Brasil (pt_BR)", when it should be "Português (pt)" and "Português do Brasil (pt_BR)". Respectively: Portuguese from Portugal (European) and Portuguese from Brazil (Latin America). See:

![20180709_152909a](https://user-images.githubusercontent.com/22776404/42913697-ae2bcc86-8acc-11e8-98be-c21ea1634d4d.jpg)

As for the result of the translation, I did some tests changing the language of the system for English, Spanish (es), Portuguese of Portugal (pt) and Portuguese of Brazil (pt_BR).

Results in OpenShot:
1) When I select the default language, it results in English in all cases.

2) When I select the Portuguese of Portugal language (pt), this is the result in all cases.

3) When I select the Spanish language (es), this is the result in all cases.

4) When I select the Portuguese of Brazil language (pt_BR):
    With the system in English, it results in Portuguese from Brazil (Pt_BR).
    With the system in Portuguese of Portugal, it results in Portuguese from Brazil (Pt_BR).
    With the system in Spanish, it results in Portuguese from Brazil (Pt_BR).
    With the Portuguese system in Brazil (Pt_BR), it results in English. That's the problem.

To differentiate pt from pt_BR:
File, in the menu bar in pt is "Ficheiro" and in Pt_BR is "Arquivo".

**Comment by ferdnyc** [comment]
> I did one more test:
> 1 - I completely uninstalled the Openshot and removed the configuration files.
> 2 - I passed the language of the system to English and rebooted the computer.
> 3 - I reinstalled the OpenShot and the initial language was the default (English). I changed it to pt_BR and it worked fine.
> 4 - I returned the system language to pt_BR and the OpenShot was in English even though I have not changed the language options.

That's #1521, and was fixed by my new translation code which is now included in the Daily Builds. Completely separate from the pt-vs-pt_BR confusion bug, which is still not fixed.

Admins, please close this as dup of #1793, it's confusing trying to track the same bug in two places. I'll post further updates there.

**Comment by mnwstl** [comment]
I have the daily PPA installed, however I have not noticed any changes.
Should I split this post and transfer the issue of translation to #1793?
