### ISSUE TITLE
Who Knows HTML?

### ISSUE THREAD

**Issue by MisterTeeXD** [OpenShot/openshot-qt#1878]
**My Question:**
Hello, i know this has nothing to do with Openshot but i need help with HTML, i have coded a whole website with HTML and now i ran into trouble with text alignment, i need to align 3 texts (one left, one center and one right) on the same line, i have tried everything but nothing works. I need help desperately.

**Comment by DylanC** [comment]
@MisterTeeXD - Umm.. you know this is for issues with Openshot? xD

Anyway, Have you tried text-align?
https://www.w3schools.com/cssref/tryit.asp?filename=trycss_text-align

If you don't know CSS yet you could do it inline for now:
<div style="text-align: center;">Some text</div>

However, I would recommend spending some time learning CSS.
