### ISSUE TITLE
New Project not functioning

### ISSUE THREAD

**Issue by Chickloski** [OpenShot/openshot-qt#1879]
When I'm in OpenShot the New Project buttons and choices do nothing.  No error message, just nothing and so I'm unable to start my project.

**Describe the bug**

**System Details (please complete the following information):**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**

**Comment by CrystalGrace** [comment]
There are technically 2 buttons for New Project: one under "File" at the top left and the one right below it. Make sure to check both to see if they work.
This might be one of those bugs were you'll have to fix the program by uninstalling and reinstalling the program. If that doesn't work, or you're not comfortable with trying that, then you'll have to wait for Openshot to release a new update that rids the bug you're dealing with.
In the meantime, have you tried the keyboard shortcuts for them? You can create a new project by using Ctrl N on your keyboard. You can also just close the program and open it again and it usually always opens as a new project **(just remember to save the project you're closing from!!)**

**Comment by Chickloski** [comment]
Hi Crystal,

 

I’ve already tried all the options except the uninstall – reinstall option.  I will try that and if that doesn’t work I will have to go to another program.

Thank you for the response.

 

Cheers,

Corinne NIKKEL

Office Administration

Skyview Inspection 360 Ltd.

250-490-1118 (South Okanagan)

778-484-1160 (North Okanagan)

1-877-490-1118 - Toll Free

Fax: 1-250-492-0544

clientcare@skyviewinspectionservices.com

Now you have a BUILDING EXPERT on your side !
