### ISSUE TITLE
 Lost ő and ű using animated text with Windows and Linux Mint

### ISSUE THREAD

**Issue by KAMI911** [OpenShot/openshot-qt#188]
Using OpenShot 2.0.7 on Windows 7 (64 bit) I found that the animated text in star wars effect lost ő and ű characters. Please see the attached picture.

Főszereplők becomes Fszereplk
![lost_o_u](https://cloud.githubusercontent.com/assets/5292264/15266393/e5bc9e60-19a3-11e6-8f21-603b2a20e2f5.png)

I have same problem on Linux mint 17.3 (Ubuntu 14.04) 64 bit, same version.

**Comment by DylanC** [comment]
@KAMI911 - Do you have this issue on newer versions of OpenShot?

**Comment by DylanC** [comment]
@KAMI911 - I'm closing this for now but if the issue exists in the latest version of OpenShot then please do report a new issue. Thanks.
