### ISSUE TITLE
Freeze or crash ramdomly

### ISSUE THREAD

**Issue by cxgaranderie** [OpenShot/openshot-qt#1880]
**Describe the bug**
OpenShot 2.4.2 freezes or crashes every 2s. Almost unusable.

**System Details (please complete the following information):**
 - Operating System / Distro: Ubuntu 18.04
 - OpenShot Version 2.4.2 installed from PPA

**To Reproduce**
Crashes or freezes at any time, generally after 10s of use, when playing project

**Expected behaviour**
No crash, no freeze

**Screenshots**
Not applicable

**Logs**
Where are the logs?

**Additional context**

**Comment by DylanC** [comment]
@cxgaranderie - What kind of PC are you running it on?
