### ISSUE TITLE
OpenShot weird screen at start

### ISSUE THREAD

**Issue by peternerd** [OpenShot/openshot-qt#1881]
**Describe the bug**
Hello,
I receantly installed OpenShot just wanted to report which seems to a bug when it starts, I saw a screen like those in the old TV boxes when they didn't have any signal.
![image](https://user-images.githubusercontent.com/1245765/42983394-16aa84b6-8bac-11e8-8420-eee706cf37b4.png)

I'm not sure if this is ok, after I close the screen (two times) OpenShot interface shows.
Should I look for a newer version? I'm new with this application and just installed from my default repos.

**System Details (please complete the following information):**
 -Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-693.11.1.el7.x86_64
      Architecture: x86-64
 - OpenShot Version 1.4.3

**To Reproduce**
1 Just open OpenShot

**Expected behavior**
I expect to see OpenShot interface.

**Logs**
➜  ~ openshot 

------------------------- ERROR 1 ------------------------------
Failed to import 'from openshot import main'
Error Message: cannot import name main
----------------------------------------------------------------
--------------------------------
   OpenShot (version 1.4.3)
--------------------------------
Process no longer exists: 30296.  Creating new pid lock file.
No LADSPA plugins were found!

Check your LADSPA_PATH environment variable.

Detecting formats, codecs, and filters...
Warning: Could not get list of video codecs using the MLT API.  Falling back to 'melt' executable.

**Additional context**

**Comment by DylanC** [comment]
@peternerd - You should try the v2 series of OpenShot. v1.4.x is no longer supported.
