### ISSUE TITLE
What size does a photo have to be to fill the entire screen?

### ISSUE THREAD

**Issue by johnmaknak** [OpenShot/openshot-qt#1882]
On Windows Movie Maker, each frame has to be 1280 X 720 to fill the screen. I've noticed that the dimensions needed for Openshot are different. Does anyone know what they are? That seems to be the same with YouTube.

So that would mean that OpenShot isn't compatitble with YouTube really, right?

Thanks.

**System Details**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**Screenshots**

**Comment by CrystalGrace** [comment]
Seems to be somewhere around 842x472. It's a little difficult to measure a software without a software that could measure it for you. Hope that helped! :)

**Comment by DylanC** [comment]
@johnmaknak - Follow the above advice. (Thanks @CrystalGrace)

**Comment by peanutbutterandcrackers** [comment]
If one clicks on the 'choose profile' button, one would see this:
![screenshot at 2018-12-11 08-59-17](https://user-images.githubusercontent.com/26764547/49776186-1acb1680-fd23-11e8-94b6-067af4e85923.png)
which has the size listed. Perhaps that is the size required to cover the entire screen.

Hope that helps.

**Comment by N3WWN** [comment]
You can also load an image and play with the `Scale`, `Scale X`, and `Scale Y` properties to alter the image sizing within the project.
