### ISSUE TITLE
Want to create a mp3 Audio with a static image not larger than both together

### ISSUE THREAD

**Issue by propagare** [OpenShot/openshot-qt#1884]
**My question:**

How can I do that? 
At the moment the imported image is only 7 seconds viewable (max. 300 sec available via prefs) and the mp3 is 592 seconds long. I cant figure out how to export it like that without becoming much bigger than the mp3+the image.

**System Details**
 - Operating System / Distro: Ubuntu 16.04.4 LTS
 - OpenShot Version 1.4.3 (ppa installed)

**Comment by DylanC** [comment]
@propagare - Can you drag the length of the image to match the mp3 length?

**Comment by propagare** [comment]
No, max 300 sec.

**Comment by DylanC** [comment]
@propagare - I guess that is a limitation on the v1.4.3 version. Maybe give the v2 version a try.
