### ISSUE TITLE
Figure out how icon themes work with AppImages

### ISSUE THREAD

**Issue by ferdnyc** [OpenShot/openshot-qt#1886]
So, I made an extremely surprising discovery today.

Needing to look at some source icons, I installed the Humanity icon theme for Fedora (it's available as an optional system package, `humanity-icon-theme-0.6.13-2.fc28.x86_64`, but normally not installed).

The next time I launched `Openshot-v2.4.2-x86_64.AppImage`, OpenShot loaded **_using my system theme icons_**. _Not_ the Humanity icons (which the AppImage would **normally** use, and what I expected to see), but my system's selected Adwaita icon theme. The same theme that's used when I run `/usr/bin/openshot-qt` installed from a Fedora package, or `src/launch.py` from my repo path, but normally ignored by the AppImage in favor of its internal fallback icons.

I tested a couple more times, and it's **definitely** the theme install. `sudo dnf remove -y humanity-icon-theme`, the AppImage goes back to built-in Humanity icons. `sudo dnf install -y humanity-icon-theme`, AppImage uses Adwaita theme icons.

Somehow, merely having the Humanity theme _available_ on my system allowed the AppImage to pick up the **OTHER** icons from my default system theme.

We need to figure out what's going on here, and get a better handle on how access to system resources works inside the AppImage. It clearly has implications for theming, and potentially for access to other resources like system dialogs as well. (I checked, and installing Humanity as a system theme did not magically make the AppImage use system dialogs. That would've been completely bonkers.)

**Comment by DylanC** [comment]
@ferdnyc - +1. I just noticed that the icons in Openshot are completely different in my built from source version. It actually uses my system icons but the AppImage icons are different and seem to be set to a particular icon theme.
