### ISSUE TITLE
Sound Issue

### ISSUE THREAD

**Issue by blipblops** [OpenShot/openshot-qt#1888]
**Describe the bug**

**System Details (please complete the following information):**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**

**Comment by blipblops** [comment]
the noise on the video clips i import have strange pauses about every second after being played. the video clip goes on but the audio either pauses or cuts off every second

**Comment by blipblops** [comment]
it happens whenever i play the videos i import or edit, and i expected the noise to continue on as if i were watching a normal video

**Comment by Lunardog15** [comment]
This is because of It rendering it as you view it and possibly the computer struggling to keep up

**Comment by DylanC** [comment]
@blipblops - Does it happen with v2.4.2?
