### ISSUE TITLE
How Do Transitions Work?

### ISSUE THREAD

**Issue by MisterTeeXD** [OpenShot/openshot-qt#1889]
**My Question:**
Hello, i need help with Openshot's Transitions, i have tried to apply them to my video clips so it does not looked like a splitted them, a recorded video or some sort would be helpful and a easier one too on how the transitions work

**System Details**
 - Operating System / Distro: Windows 10
 - OpenShot Version: 2.4.2

**Screenshots**
![screenshot 56](https://user-images.githubusercontent.com/37266538/43022844-ecc71e80-8c68-11e8-9767-dd8c2500fbf7.png)

**Comment by benrob0329** [comment]
You need to overlap the clips slightly for the transition to fade one to the other.

**Comment by MisterTeeXD** [comment]
A video would be helpful

**Comment by mnwstl** [comment]
Have you searched the user's guide?
https://www.openshot.org/
https://www.openshot.org/static/files/user-guide/index.html
https://www.openshot.org/blog/2018/03/02/masks-transitions-video-tutorial/

**Comment by DylanC** [comment]
@MisterTeeXD - Overlap both clips to have them transition between each other.
