### ISSUE TITLE
Can't speed up the video.

### ISSUE THREAD

**Issue by GaidenFocus** [OpenShot/openshot-qt#1892]
I tried everything I found online about it but for the most part, cant find the window half are talking about (I think they are using an older version) because there is no clip prop window, just a side box on the left.

Another one said you can right click and speed it up.  I selected x8 and it made the box shorter, but really it just clipped off everything past that mark.  So it was playing at the same speed but just an 8th.  

Anyone know how to make a 3 hour video into a 3 minute video?

**Comment by benrob0329** [comment]
Right click on the clip and select "properties"

**Comment by DylanC** [comment]
@GaidenFocus - Follow the above advice. Thanks.

**Comment by GaidenFocus** [comment]
Nope.  Already tried that.

The prop window on the left shows up.  I see no option for speed up / slow down.

![image](https://user-images.githubusercontent.com/34256261/43095368-3817e27a-8e7b-11e8-8d98-654c296a57fc.png)

**Comment by CrystalGrace** [comment]
[Using what the creator of Openshot himself said in a thread](https://github.com/OpenShot/openshot-qt/issues/327), I believe they're trying to tell you about the Time property. In the "Properties" section in the bottom left of your screen, if you scroll down you'll see "Time". If you know how keyframes work and how to use them, you can set the speed from there using keyframes.
However, I can't even get it to work either! My clip either glitches out or doesn't change. So for now, unless it works for you, until it gets fixed, you'll have to make use of the right clicking the clip, go to Time, Fast, then choose a speed they have, but you seem to be having a problem with that as well.
And yes, in older versions of Open Shot there was an advanced speed dialog box that would pop up to where you could set the speed to whatever you want easily and without problems or gitches, which is probably what you're referring to and what you keep seeing in tutorials. But it seems to be gone now.

**Comment by peanutbutterandcrackers** [comment]
Linking #327 and https://github.com/OpenShot/libopenshot/issues/176#issuecomment-442466083 here so that it might be of some help to someone. Even though I myself haven't yet been able to properly use the 'Time' property.

**Comment by Noino** [comment]
Wrote a step by step guide for changing speed of clips
https://github.com/OpenShot/openshot-qt/issues/327#issuecomment-463998686

**Comment by N3WWN** [comment]
See also my detailed description of changing playback speed (and speed+direction) of clips at 
https://github.com/OpenShot/libopenshot/issues/176#issuecomment-442466083

**Comment by dopeboy** [comment]
In case this trips up people, the answer is: right click on a clip. Go to time->fast->forward

Thanks @N3WWN for the answer.
