### ISSUE TITLE
How do I make a video black and white? 

### ISSUE THREAD

**Issue by mucholapka** [OpenShot/openshot-qt#1894]
**My Question:**
How do I make a video black and white? As simple as that.

**System Details**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**Screenshots**

**Comment by CrystalGrace** [comment]
In "Effects", put "Color Saturation" on the clip you want black and white.
Then, by either clicking the "S" icon on the clip, or finding the "Color Saturation" section in the Selection drop down in "Properties", set the "Saturation" to 0.

**Comment by DylanC** [comment]
@mucholapka - Follow the above advice.
