### ISSUE TITLE
Windows: Preferences for Advanced Title Editor (Path) expects forward slashes instead of backslashes

### ISSUE THREAD

**Issue by dlcarraw** [OpenShot/openshot-qt#1896]
**Describe the bug**
Under Windows, when you configure the Advanced Title Editor (Path) setting in Preferences using the Windows path to the Inkscape executable, you will receive an error that says "Please install c:\program files\inkscape\inkscape.exe to use this function." 

**System Details (please complete the following information):**
 - Operating System / Distro: Windows 10
 - OpenShot Version 2.4.2

**To Reproduce**
1. Install Inkscape for Windows. It normally installs in C:\Program Files\Inkscape as inkscape.exe

2. In OpenShot, go to Preferences and enter the Windows path for Inkscape, in this example it would be C:\Program Files\Inkscape\inkscape.exe

3. Go to Title -> Title and click on a template that allows you to edit a title (for example, the Bar 1 template)

4. Click the "Use Advanced Editor" button.

5. You will get an error that says "Please install c:\program files\inkscape\inkscape.exe to use this function."

6. If you manually change the path to use forward slashes instead, when you click the "Use Advanced Editor" button, Inkscape will launch. In this example, that means changing the path to C:/Program Files/Inkscape/inkscape.exe

7. NOTE:  If you set the path using the forward slashes and successfully launch the Inkscape with the "Use Advanced Editor" button once, the Inkscape integration will continue to work even if you set the preference back to using backslashes in the path. This is important to know during testing.

**Expected behavior**
Windows operating systems use backslashes in a file path, rather than forward slashes (which Linux uses). However, OpenShot expects forward slashes for the Advanced Title Editor (Path) setting regardless of operating system. Consequently, when a Windows user wants to specify the path to Inkscape, they fail because Windows displays paths using backslashes.

**Comment by DylanC** [comment]
@dlcarraw - Yes, we should fix this regarding your expected behavior.

**Comment by ferdnyc** [comment]
Hmm. See, now I'm confused.

On Windows 7, this is how my preferences are set:
![screenshot 2018-07-29 06 44 49](https://user-images.githubusercontent.com/538020/43365510-f26b9dcc-92fb-11e8-9a02-35e098fa827a.png)

OpenShot has no trouble launching Inkscape. I tried changing to all-lowercase, too, just in case it was being case-sensitive, but still no problems. Inkscape came right up.

While it's True Qt uses forward slashes by default (even on Windows), it's supposed to auto-convert native paths. Are you sure there wasn't some other issue with the path name, like a component that was spelled wrong?

**Comment by ferdnyc** [comment]
> NOTE: If you set the path using the forward slashes and successfully launch the Inkscape with the "Use Advanced Editor" button once, the Inkscape integration will continue to work even if you set the preference back to using backslashes in the path. This is important to know during testing.

I never had the path set with forward slashes, so I'm not sure that's the issue. It really is _supposed_ to work with backslashes.

**Comment by ferdnyc** [comment]
Tried it again:
1. _Completely_ deleted `%USERPROFILE%\.openshot_qt` directory and all contents
1. Launched OpenShot 2.4.2 release
1. Went into Preferences, typed `C:\Program Files\Inkscape\inkscape.exe` in title editor field
1. Opened Title > Title
1. Selected a title and hit Use Advanced Editor

Inkscape took forever to launch (also doing a Windows Update), but it did eventually come up.

I can't get it to **not** accept the path with backslashes. @dlcarraw , please try again with steps above, confirm that you're still having a problem with the path when using backslashes. Perhaps there's something different under Windows 10 compared to Windows 7.

**Comment by ferdnyc** [comment]
Ping @dlcarraw about this issue, see my previous comment.

If there's no response, @DylanC , @peanutbutterandcrackers , I think this can probably be closed. As I said, I couldn't reproduce (tho I'm running Win7, not Win10), even after I tried pretty hard.

**Comment by dlcarraw** [comment]
I'm visiting family in a rural area with very little internet. Will respond when I get back to the 21st century.
On Sep 22, 2018 3:12 PM, Frank Dana <notifications@github.com> wrote:

Ping @dlcarraw<https://github.com/dlcarraw> about this issue, see my previous comment.

If there's no response, @DylanC<https://github.com/DylanC> , @peanutbutterandcrackers<https://github.com/peanutbutterandcrackers> , I think this can probably be closed. As I said, I couldn't reproduce (tho I'm running Win7, not Win10), even after I tried pretty hard.

**Comment by ferdnyc** [comment]
(Note: One enhancement to address this, regardless, would be to add a "Choose..." button and launch a filepicker for the user to locate the `inkscape.exe` executable with, rather than having them type in the path. Then there wouldn't be any possibility of problems due to typos, misparsed path strings, Qt quirks in path formatting, or what have you.)

**Comment by DylanC** [comment]
@ferdnyc - I've started something like this actually. First for Blender but afterwards I could do Inkscape too. :+1:

**Comment by DylanC** [comment]
I put in a change to have browse buttons in future. This will work better in newer releases:
https://github.com/OpenShot/openshot-qt/pull/2255
