### ISSUE TITLE
Video preview = constant freezing

### ISSUE THREAD

**Issue by wyrsek** [OpenShot/openshot-qt#1897]
Just installed OpenShot. Put in a track with audio. Put in a track with video. If I try to play the preview, it turns my CPU usage up to 100%. I get a fraction of a second of sound and video, and then it freezes for a while. Then a fraction of sound and video...freeze...rinse and repeat.
Looked at changing the cache options to Disk, 250MB, .3 Ratio, 30 Quality. Still no dice.

Didn't know if anyone had any ideas. Video was recorded using a Logitech webcam and Cheese to record: 1280x960, Codec: On2 VP8

**System Details**
 - Operating System / Distro: Linux Mint 18.3 Sylvia
 - OpenShot Version 2.4.2

**Comment by vicmortelmans** [comment]
I seem to have the same problem. I re-encoded my audio tracks using aac encoder and that improved a lot. One of the mp3 tracks had a video (jpeg) stream, and I also had to remove that for a better performance.

Here's how I did it using ffmpeg:

`find . -name "*.mp3" -print0 | xargs -0 -L 1 sh -c 'ffmpeg -i "$1" -acodec aac -strict experimental "${1%.mp3}.m4a"' --`

For one mp3 input file I had to add the option `-map 0:0` to extract the audio track only (it also had a jpeg video stream).

Note that `ffmpeg -i myfile.mp3` will show the enclosed streams.

**Comment by wyrsek** [comment]
My problem seems to be with the video rather than the audio. If I take out the video, it plays perfectly, but once video is involved it's Freeze City...

**Comment by peanutbutterandcrackers** [comment]
@vicmortelmans - Thank you for sharing your insights with the community.

@wyrsek - Sorry for the inconvenience sir. OpenShot's preview does seem to be too high-quality to play well. This is a well documented issue. Perhaps we'll have to work on getting proxies, etc. Since those enhancement requests have already been made, I will close this issue so as to control the amount of open issues. I hope you understand. Thank you.

**Comment by mouarfff** [comment]
i have the same issue

**Comment by ferdnyc** [comment]
> Here's how I did it using ffmpeg:
> 
> `find . -name "*.mp3" -print0 | xargs -0 -L 1 sh -c 'ffmpeg -i "$1" -acodec aac -strict experimental "${1%.mp3}.m4a"' --`
> 
> For one mp3 input file I had to add the option `-map 0:0` to extract the audio track only (it also had a jpeg video stream).

Just to add a convenience to this helpful advice from @vicmortelmans, if you include `-vn` in the `ffmpeg` command line, it will disable output of any video streams present. If there are none it simply has no effect, so it's safe to just always include `-vn` and not worry about whether any of the audio files include video/image content. So, e.g.
```sh
find . -name "*.mp3" -print0 | xargs -0 -L 1 \
sh -c 'ffmpeg -i "$1" -acodec aac -vn -strict experimental "${1%.mp3}.m4a"' --
```
Will always convert MP3 files to AAC-encoded MP4 audio-only, regardless whether the original file included any embedded image data or not.
