### ISSUE TITLE
Exporting I get "Faulting application"  event 1000 - Got it to work, by deleting transitions

### ISSUE THREAD

**Issue by tsoward** [OpenShot/openshot-qt#1898]
**Describe the bug**
Downloaded current product today, installed first on Win 7 desktop, when that failed, reinstalled on another Windows 10 desktop and moved project files over.
Combined a bunch of jpg images and 2 .MOV videos, then some more .jpgs; track 3 added some music under the .jpgs (the videos had their own sound); about 23 minutes in length  (I.e. very basic), 

after completing tried to export but ~30% in get Application error Event 1000 Exception code: 0xc0000005

It seems to move when removed the transition (I had slightly overlapped them and it inserts the blue blob beteen) from pictures to video 1;  but still failed.  I then removed the transition from video 1 to video 2 and then it exported ok!!

**System Details (please complete the following information):**
 - Operating System Tried both Windows 7 Pro and Windows 10 Pro both 64bit; both machines older (3rd gen I think) Intel Core I5 w/8Gb, and SSDs.
 - OpenShot Version 2.4.2
**To Reproduce**
1. Open Project
2. Click on export button, took all defaults
3. Wait ~ 5 minutes (about 30% through)  around the transition from a series of photos to the 1st video

**Expected behavior**
Complete the export

**Screenshots**
![image](https://user-images.githubusercontent.com/41549304/43049999-83c99ada-8dcf-11e8-999f-dce6a792d2f1.png)

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.
Faulting application name: launch.exe, version: 0.0.0.0, time stamp: 0x00000000
Faulting module name: libopenshot.dll, version: 0.0.0.0, time stamp: 0x5b3706d6
Exception code: 0xc0000005
Fault offset: 0x000000000004e0dc
Faulting process id: 0x71b4
Faulting application start time: 0x01d421f7e7124a83
Faulting application path: C:\Program Files\OpenShot Video Editor\launch.exe
Faulting module path: C:\Program Files\OpenShot Video Editor\libopenshot.dll
Report Id: 65dd049e-147d-4c9b-b445-63e9df8bcb23
Faulting package full name: 
Faulting package-relative application ID: 

**Additional context**
I'm new to the product - first day.

**Comment by DylanC** [comment]
@tsoward - This transitions bug has been fixed. See #2125.
