### ISSUE TITLE
Openshot Crashing during editing and exporting

### ISSUE THREAD

**Issue by UMNVideo** [OpenShot/openshot-qt#1899]
OpenShot keeps crashing every time I attempt to export a video.  The export never gets past 30% complete. 
The video editor also keeps crashing after attempting to do pretty much anything.  This includes adding a transition, previewing the edited video, adding a video track, moving a video clip, etc. 

 - Operating System Windows 10
 - OpenShot Version 2.4.2
- Computer: Lenovo, steady state, 8GB memory

Expected behavior
No crashing. 

Here is an attachment of my logs. 
[openshot-qt.zip](https://github.com/OpenShot/openshot-qt/files/2217626/openshot-qt.zip)

**Comment by creeeeek** [comment]
I have experienced the exact same thing. when exported everything simply disappears, part of the exported video is created. about 10 percent.
I tried restarting. I then re-installed V2.41 and it is back too normal and works fine
What i was doing is going back to some old projects and adding a music track to it.

**Comment by UMNVideo** [comment]
@dumischbaenger 
I was able to fix the problem by uninstalling the program from the computer, restarting the computer, and installing the 2.4.1 version.  This older version works much better and I have not had a problem since.

**Comment by DylanC** [comment]
@UMNVideo - This transitions bug has been fixed. See #2125.
