### ISSUE TITLE
razer cutting tool separate s clips and it disapears further down the timeline

### ISSUE THREAD

**Issue by bobcrikey** [OpenShot/openshot-qt#1900]
Hello, iv noticed a bug only happens now and again .
when you use the razer cutting tool to separate clips on the odd occasion the split cliip (on the right),

disapears and moves on its own quite a distance down the timeline and you have to go find it, 
rather than stay put after razer cut .

as i said it only happens now and again on 2.4.2

cheers
 bob

**Comment by DylanC** [comment]
@bobcrikey - Thanks, I'll have a look at this later.

**Comment by gvbowles** [comment]
This happens when you slice and keep both sides. For me it happens every time I do a slice and keep both sides. I haven't tried it on the 7/29/2018 build. Will get back to you on that.

**Comment by sirex** [comment]
Same here.

**Comment by DavidDaish** [comment]
While I can add very little to the conversation, I thought it would be worthwhile to mention that I also have this issue. I have a suspicion that the distance the clip is moved down is increased with each cut. As in, it starts at the correct distance, and increases with each cut. I am running OpenShot 2.4.2 on Ubuntu Xenial.

**Comment by DylanC** [comment]
@bobcrikey - Confirmed as a bug since so many users have reported it and I can see this issue sometimes.

**Comment by alex-moon** [comment]
Using v2.4.2 I get this behaviour consistently using ctrl+k to split a long clip into a series of shorter clips. Guess all I can do is +1 this - attached is output on the CLI when this happens (not sure if this is useful):
[openshot-1900.txt](https://github.com/OpenShot/openshot-qt/files/2288490/openshot-1900.txt)

**Comment by jmouse888** [comment]
Same exact issue here.  Running 2.4.2 on Ubuntu 16.04 LTS
