### ISSUE TITLE
Crash while exporting in a different video format than the original cut

### ISSUE THREAD

**Issue by Alomphega** [OpenShot/openshot-qt#1901]
**Describe the bug**
All works fine, still exporting, and that is fine too (thanks to developers !) 
BUT if we change the video format (ie : instead of a big HD 1920x1080 I try to export a smaller HD 1280x720) then the software shuts down (no alert, just an unpolite quit)

**System Details :**
 - Operating System : Windows 10
 - OpenShot Version : 2.4.2

**To Reproduce**
1. Go to 'Export'
2. Chose video profile from HD 1080 to HD 720 (or other smaller vid format)
3. Clic to 'Export' button
4. See the quit after few second (and 0%)

note : the same while just trying to play the project with a smaller vid format chosen by "Choose Profile"

**Expected behavior**
Well, obviously we wait a film exported, smaller than the original...

**Screenshots**
If applicable, add screenshots to help explain your problem. (NO SCREENSHOTS)

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem. (?)

**Additional context**
Add any other context about the problem here. (All I can say is above I think.)

Hoping this will help...
Guy Capra

**Comment by DylanC** [comment]
@Alomphega - Try v2.4.3 and let us know if you still have a problem.

**Comment by Alomphega** [comment]
@DylanC : just time left to make one quick try ; seems to be OK now, so thanks and bravo ! :-)

**Comment by DylanC** [comment]
@Alomphega - Great news! Thanks!
