### ISSUE TITLE
Auto-Recovering a project whose videos are deleted create a major issue

### ISSUE THREAD

**Issue by TorSKY** [OpenShot/openshot-qt#1902]
Hello,

I made a project long time ago and closed it without saving as I wasn't needing it anymore. It was based on several small videos that I've now deleted.

It's now impossible for me to run OpenShot as the software always try to automatically recover this unwanted project and is unable to find the videos because they had been deleted since.

I succeded to pass the "video1.mp4 cannot be found" messages by renaming several other videos. But after I got the message: "Your most recent unsaved project has been recovered", the software crashes.

I can't abort the recovering process, it lunches automatically when the program starts. I also uninstalled OpenShot and reinstalled it but I didn't deleted everything so it still tries to recover.

I'll try to go deeper in uninstalling. But maybe a messageboard asking "do you want to recover ?" before the soft tries to do it with an unrecoverable project making it fully unoperable would be better that needing a complete uninstallation.

Regards

**Comment by TorSKY** [comment]
Succeded to pass throught this bug by renaming small videos with the name of the ones the soft were looking to, then quickly made Ctrl+N, refusing to save the opened project, it makes the soft crashes again, but now it doesn't try to recover it anymore.

So solved for me, but something more convenient to abort the auto-recovering would be appreciated.

**Comment by Patrik356b** [comment]
IMO: It should always ask

**Comment by DylanC** [comment]
@Patrik356b - Agreed.

**Comment by peanutbutterandcrackers** [comment]
A fix has gone in for this issue. Could you please check out the [daily builds](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914) and see if you are happy enough with it? Perhaps you might have some further suggestions (which you can give here in the comments).

**Comment by peanutbutterandcrackers** [comment]
Closing this for now. Please do feel free to re-open if so required (after checking the latest changes). Thank you!
