### ISSUE TITLE
App not responding when exporting video

### ISSUE THREAD

**Issue by taufiqqsalimm** [OpenShot/openshot-qt#1903]
**Describe the bug**
App not responding crash when exporting video progress at 8.5%

**System Details (please complete the following information):**
 - Operating System : Windows 7 Pro x64
 - OpenShot Version : e.g. 2.4.2

**Expected behavior**
App not responding happen at the same progress percentage each time im exporting videos. Already checked RAM and CPU usage, no issue.

![app crash log](https://user-images.githubusercontent.com/41577387/43075965-196cc112-8eb5-11e8-95bd-f52d7af1b1b2.png)

Thank you in advance :)

**Comment by DylanC** [comment]
@taufiqqsalimm - What profile are you using for export? Video formats on the tracks?
