### ISSUE TITLE
No way to register for forum

### ISSUE THREAD

**Issue by MrYossu** [OpenShot/openshot-qt#1906]
OK, so I know this isn't an issue with OS itself, but I can't see any other way to ask it.

I've just started using OS and am very impressed. However, given the complexity of the software, I have questions. I see a forum, but no way to register. There was an email address openshot_forum@openshotusers.com given in case you had trouble logging in, but that doesn't seem to work.

How do I register? While I'm really impressed with the software, I can't see me getting very far without some support.

Thanks

**Comment by DylanC** [comment]
@MrYossu - You can get support here. Do you have a specific question to ask? We have a question label for people looking for information on certain features.

**Comment by ferdnyc** [comment]
(Basically, there isn't currently a user forum available. That email address is defunct.)

**Comment by MrYossu** [comment]
OK, thanks to both of you. I'll post my question in a new thread.
