### ISSUE TITLE
Exported video jerking

### ISSUE THREAD

**Issue by MrYossu** [OpenShot/openshot-qt#1907]
I am new to OS, so please forgive me if this is a dumb question.

As an experiment, I tried importing a video clip, pausing it at the end, then reversing at high speed.

When I export it, the resulting video plays fine for a few seconds, then jerks a lot before it is supposed to freeze. I did a short version of the clip here...

[test.zip](https://github.com/OpenShot/openshot-qt/files/2220183/test.zip)

This was done at low quality to keep the file size down, but the same happens at high quality.

Don't know if it's relevant, but here is the .osp file...

[SW.zip](https://github.com/OpenShot/openshot-qt/files/2220184/SW.zip)

**System Details**
 - Operating System Windows 7 pro, fully updated
 - 40Gb RAM, wads of disk space
 - OpenShot Version 2.4.2

Thanks for any help you can give.

**Comment by DylanC** [comment]
@MrYossu - Is it 4Gb of RAM or 40Gb? 😆

**Comment by DylanC** [comment]
@MrYossu - I think maybe this is due to your sample rate being 44100. Seems to cause much trouble with videos. Maybe try 48000.

**Comment by MrYossu** [comment]
Hello,
Thanks for the reply. 
I can see that the Advanced tab of the export window allows me to set the audio sample rate, which is currently 44100. I tried setting that to 48000, and it was a little better, but still not great.
Any other suggestions? Thanks again.
P.S. It really is 40Gb. I figure that between me and the PC, one of us should have a decent memory!
