### ISSUE TITLE
Openshot crash and can't open a projecty

### ISSUE THREAD

**Issue by perepater** [OpenShot/openshot-qt#191]
I have a project with clips from mp4 and mov files. I have a project, 15 minutes aprox. of duration and now when I open try to open the project, Openshot crashes. I have the version 1.4.3 of Openshot and Ubuntu 12.04

**Comment by jreynojustin** [comment]
OpenShot is now in Version 2.2 if you are still noticing issues in the latest version please re-open this issue letting us know.
