### ISSUE TITLE
Alpha channels not corresponding to correct time indexes.

### ISSUE THREAD

**Issue by adamlaughlin** [OpenShot/openshot-qt#1912]
When I insert keyframes and begin to modify the alpha channels to produce a fade effect, all goes well in the video preview window.
However, when encoding is done the fades are dramatically lengthened and encompass a significant portion of content which was previewed at 1.00 alpha.
I've tried re-doing the project without modifying the timeline width and after a couple more attempts I can't provide a use case where it fades as intended in the output.

Any thoughts?

**Comment by DylanC** [comment]
@N3WWN - You are more qualified in this area to answer.

**Comment by DylanC** [comment]
@peanutbutterandcrackers - Any thoughts on this?
