### ISSUE TITLE
Are you happy with the current Clip (Right click) menu?

### ISSUE THREAD

**Issue by DylanC** [OpenShot/openshot-qt#1913]
We could use some user feedback here. Our wonderful contributor @ferdnyc is working on an alternative menu layout for clips. He could use some feedback on the following PR #1643 

Please answer the following:
1. Are you happy with the menu layout in the current Clip menu? (via right click)
2. What do you think of the new layout in the PR #1643?

**Comment by bobcrikey** [comment]
hello everyone, i just made a comment to PR# 1643 :)
cheers bob

**Comment by N3WWN** [comment]
Also commented within PR #1643 .
