### ISSUE TITLE
How to add text in the video - Lyrical video

### ISSUE THREAD

**Issue by vasanth2online** [OpenShot/openshot-qt#1917]
How to add text to the videos as we do it in lyrical video.

**Comment by peanutbutterandcrackers** [comment]
You might want to use some external Free tools like [GIMP](http://gimp.org/) or [InkScape](http://inkscape.org/) or use the internal [title editor](https://www.openshot.org/static/files/user-guide/titles.html#titles). You might also want to take a look at [this guide](https://gist.github.com/peanutbutterandcrackers/f0f666243133e0ed25abbc12a4ba23d7) so as to learn how to use keyframes to make the video even better.

Hope that helps.

Closing for now. However, if you still need some further clarification, please do feel free to re-open. Thanks.
