### ISSUE TITLE
Error report after crash on Win7 - running beta 4

### ISSUE THREAD

**Issue by flutedude** [OpenShot/openshot-qt#192]
Problem signature:
  Problem Event Name:   APPCRASH
  Application Name: launch.exe
  Application Version:  0.0.0.0
  Application Timestamp:    549dea3c
  Fault Module Name:    libopenshot.dll
  Fault Module Version: 0.0.0.0
  Fault Module Timestamp:   000037fe
  Exception Code:   c0000005
  Exception Offset: 0005438c
  OS Version:   6.1.7601.2.1.0.256.48
  Locale ID:    1033
  Additional Information 1: 0a9e
  Additional Information 2: 0a9e372d3b4ad19135b953a78882e789
  Additional Information 3: 0a9e
#   Additional Information 4: 0a9e372d3b4ad19135b953a78882e789
# This is a home built machine that has been strong for several years.

OS Name Microsoft Windows 7 Professional
Version 6.1.7601 Service Pack 1 Build 7601
Other OS Description    Not Available
OS Manufacturer Microsoft Corporation
System Name ALANK-VIDEO
System Manufacturer System manufacturer
System Model    System Product Name
System Type x64-based PC
Processor   Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz, 3201 Mhz, 6 Core(s), 12 Logical Processor(s)
BIOS Version/Date   American Megatrends Inc. 4210, 8/12/2013
SMBIOS Version  2.7
Windows Directory   C:\Windows
System Directory    C:\Windows\system32
Boot Device \Device\HarddiskVolume2
Locale  United States
Hardware Abstraction Layer  Version = "6.1.7601.17514"
User Name   AlanK-Video\AlanK
Time Zone   Pacific Daylight Time
Installed Physical Memory (RAM) 32.0 GB
Total Physical Memory   31.9 GB
Available Physical Memory   27.1 GB
Total Virtual Memory    32.1 GB
Available Virtual Memory    26.8 GB
Page File Space 200 MB
Page File   C:\pagefile.sys

**Comment by DylanC** [comment]
@flutedude - Do you have this issue present in newer versions of OpenShot?

**Comment by DylanC** [comment]
@flutedude - Please test in a newer version of OpenShot to verify this issue. Closing for now. Thanks.

**Comment by flutedude** [comment]
No idea. I stopped using it since it was so unstable.

**Comment by DylanC** [comment]
@flutedude - No problem. Thanks for the response.
