### ISSUE TITLE
How Were So Many Issues Closed?

### ISSUE THREAD

**Issue by MisterTeeXD** [OpenShot/openshot-qt#1920]
So, i noticed that so many issues has been closed, at first it was at 503 issues and now its dropped down to 371, were those bugs fixed, i want to be updated.

**Comment by DylanC** [comment]
@MisterTeeXD - Some were fixed and some are just issues gone stale (reported on older versions but no more further feedback)

Issues need a cleanup every now and then. Otherwise its impossible to understand what needs to be fixed.
