### ISSUE TITLE
Closing program during exporting video

### ISSUE THREAD

**Issue by mrb79** [OpenShot/openshot-qt#1925]
**Describe the bug**
When i try to export a video in MP4(h.264) HD 1080i 30fps i see that at about 65% the program closes.
The file geenrated (about 4GB)  is unreadable. I try many times with the same result.

**System Details (please complete the following information):**
 - Operating System / Distro: Windows 10
 - OpenShot Version 2.4.2

**To Reproduce**
1. Open project
2. Export video
3. At 65% program closes

**Expected behavior**
The operation must be completed.

**Screenshots**

**Logs**
I attach log file.
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2238592/openshot-qt.log)

**Additional context**

**Comment by DylanC** [comment]
@mrb79 - Do you also have a log file for libopenshot?

**Comment by mrb79** [comment]
Yes i have but is a big file (5GB).

**Comment by DylanC** [comment]
@mrb79 - Maybe delete the file and reproduce the issue. Afterwards upload the smaller file.

**Comment by mrb79** [comment]
Ok. I try.

**Comment by mrb79** [comment]
I retry clearing the file before. The file generated has size 1.8GB.

**Comment by DylanC** [comment]
@mrb79 - Try v2.4.3. Its much more stable for exports.
