### ISSUE TITLE
I cant close Welcome screen = cant use Openshot

### ISSUE THREAD

**Issue by jazbina** [OpenShot/openshot-qt#1927]
I cant close Welcome screen. It doesn't respond. Because of that I cant use Openshot.

**Comment by ferdnyc** [comment]
Glad to hear you were able to get past it. This is an issue some users experience with the welcome tutorial, unfortunately. The Tutorial code was replaced following the release of OpenShot 2.4.2, so an alternative fix would be to [download](https://www.openshot.org/download/) the latest Daily Build for your system, which should clear up that issue.

However, if you feel that your issue has been solved, please feel free to close this report using the button below.
