### ISSUE TITLE
Openshot unusable - i5 4690k is not good for Openshot

### ISSUE THREAD

**Issue by jazbina** [OpenShot/openshot-qt#1928]
**Describe the bug**
Openshot unusable. I load small video clips from phone and it freez. CPU is 100%.
 i5 4690k is not good for Openshot. I am using CPU video card.

**System Details (please complete the following information):**
 - Operating System / Distro: Debian Testing
 - OpenShot Version 2.4.1

**To Reproduce**
1. Import video file (mp4)
2. Add it to timeline
3. CPU is 100%

**Comment by jazbina** [comment]
In Kdenlive I have no problems.

**Comment by DylanC** [comment]
@jazbina - v2.4.1 is not the latest version. Maybe try v2.4.2.
