### ISSUE TITLE
Issue opening OpenShot after install

### ISSUE THREAD

**Issue by wgramlich** [OpenShot/openshot-qt#193]
On Windows 7 Enterprise 32bit
Issue opening OpenShot after install.
Error Message title is "cx_Freeze: Python error in main script"
![openshoterror](https://cloud.githubusercontent.com/assets/19391687/15294211/4d1bf3e2-1b59-11e6-998e-a5eb7502e392.png)

I have tried repairing.  Reinstalling.  No solution.

**Comment by wgramlich** [comment]
Also tried on Windows 10 x64 and had the same issue.

**Comment by Progi1984** [comment]
Same one :)

**Comment by TheInaneRambler** [comment]
Any updates on this?

still gives me this error even when i use the oldest version for windows they're still listing for download

**Comment by DylanC** [comment]
@wgramlich - What version of OpenShot did you try in this issue?

**Comment by DylanC** [comment]
Closing until we get more details. Windows launch issues should be resolved by now.

**Comment by Progi1984** [comment]
@DylanC It was the latest version which was on the front of the homepage of OpenShot at this moment.
