### ISSUE TITLE
Export crashing

### ISSUE THREAD

**Issue by Quatsous** [OpenShot/openshot-qt#1930]
bonjour
Je n'arrive pas à exporter ma vidéo; quand j'essaie, je suis immédiatement sortie d'openShot.
Il y a quelques mois avec sans doute la version -1, cela marchait.

**Comment by DylanC** [comment]
**Google Translate**

Hello
I can not export my video when I try, I immediately exit openShot.
A few months ago with probably the -1 version, it worked.

**Comment by DylanC** [comment]
@Quatsous - What version are you using currently?
