### ISSUE TITLE
No audio on project, just loud static?

### ISSUE THREAD

**Issue by tpbis** [OpenShot/openshot-qt#1931]
Hi, I'm having an issue wherein any audio I add to my project only plays static instead of the audio, though it doesn't seem to affect the project when it has been exported.  It happens with .flv , .mp3 and .mp4 files, all the files I have currently tried.

I am running on Win 10, i7700k, 1070 and 16gb DDR4.

**Comment by DerGenaue** [comment]
Witnessed something similar with an .mp3 file.
On another computer, it worked.
Mitigated the issue by converting the audio to .ogg

**Comment by speedytechdev** [comment]
Hi, @tpbis Are you still having this issue and have you tried the [daily build](https://www.openshot.org/download/).
