### ISSUE TITLE
Very Slow and often unresponsive when playing back videos inside of the editor

### ISSUE THREAD

**Issue by Bonjarva** [OpenShot/openshot-qt#1933]
When  I import a video to edit into the software once imported and dropped into edit pane I would click onto any part of the video and play it to see where I am editing but it plays back insanely slow and often becomes unresponsive

**System Details **
Windows 10 intel i7, 4GB NVIDIA® GeForce® GTX 1050 Ti, 16GB RAM
OpenShot Version 2.4.1

**Comment by DylanC** [comment]
@Bonjarva - Try Openshot v2.4.2. People have reported much better playback performance.

**Comment by Bonjarva** [comment]
Yeah i tried updating to 2.4.2 and still has the same issue as well as exporting videos just breaks the software

**Comment by DylanC** [comment]
@Bonjarva - No problem. Thanks for getting back to me.

**Comment by DylanC** [comment]
@Bonjarva - Hate to ask again but can you try in v2.4.3. We have reports of this version being much more stable for exports.

**Comment by DylanC** [comment]
@Bonjarva - Very good. Please report a separate issue if you have a different kind of problem. Thanks.
