### ISSUE TITLE
Autosave corrupted project file

### ISSUE THREAD

**Issue by sirex** [OpenShot/openshot-qt#1936]
**Describe the bug**
I had a project file created with OpenShot 1.4. Then I installed OpenShot 2.4 and opened that project file. Then OpenShot 2.4 autosaved project file and I was no longer been able to open it with 1.4 version.

For some reason OpenShot 2.4 razor tool always cuts right side, even if press Ctrl+K. That was the deal breaker for me and I wanted to return to the older version.

**System Details (please complete the following information):**
 - Operating System / Distro: Ubuntu 16.04
 - OpenShot Version 2.4.1

**Comment by DylanC** [comment]
@sirex - Yes, the newer project format would not be backwards compatible. Hopefully you backed up your project file before opening.
