### ISSUE TITLE
Speeding up & down clips

### ISSUE THREAD

**Issue by SirDshimshi** [OpenShot/openshot-qt#1938]
In a video I'm making I need to to speed up a clip to a certain length, I think it would be very useful to have an option for the users to choose the desired length they want to stretch or compress the clip. Or that or you can add to the properties menu a scale to speed or slow a clip, where 1 is the default speed.
I know there is a way to fast forward clips by right clicking on them but there it is only possible to change the speed by powers of two which is quite uncomfortable.

**Comment by trdwll** [comment]
Click the little carrot (arrow/V) on the clip and to Time. Took me a little while to figure it out also.

**Comment by KLZSailing** [comment]
I don't get it. Clicking on the arrow/V also shows time by powers of two, can't modify time to other values

**Comment by belda** [comment]
I also would say this suggestion would be more useful, you are usually dealing with speed of the video, not time and the values that get assigned to the time in the properties are really not making any sense.
for example you usually want to have 24fps project and slow 30fps video to 80% to make it look smooth
