### ISSUE TITLE
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'

### ISSUE THREAD

**Issue by david-kohen** [OpenShot/openshot-qt#1939]
**Describe the bug**
Openshot fails with the message:
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'

**System Details
Ubuntu 18.04
OpenShot Version 
openshot-qt 2.4.2.dev1 (also tried AppImage - same problem)

**To Reproduce**
run openshot-qt fromthe command line

**Expected behavior**
I expected openshot to open :)

**Logs**
libopenshot.log:
BEGINS
------------------------------------------
libopenshot logging: Wed Aug  1 18:04:56 2018
-----------------------------------------
ENDS
openshot-qt.log
BEGINS
      launch:INFO ------------------------------------------------
      launch:INFO    OpenShot (version 2.4.2-dev1)
      launch:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.4.2-dev1
         app:INFO libopenshot version: 0.2.0
         app:INFO platform: Linux-4.15.0-29-generic-x86_64-with-Ubuntu-18.04-bionic
         app:INFO processor: x86_64
         app:INFO machine: x86_64
         app:INFO python version: 3.6.5
         app:INFO qt5 version: 5.10.1
         app:INFO pyqt5 version: 5.10.1
    language:INFO Attempting to load qt_en_IL in '/home/dkohen/.local/lib/python3.6/site-packages/PyQt5/Qt/translations'
    language:INFO Attempting to load qt_en in '/home/dkohen/.local/lib/python3.6/site-packages/PyQt5/Qt/translations'
    language:INFO Attempting to load en_IL/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Attempting to load en/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Attempting to load qt_en_IL in '/home/dkohen/.local/lib/python3.6/site-packages/PyQt5/Qt/translations'
    language:INFO Attempting to load qt_en in '/home/dkohen/.local/lib/python3.6/site-packages/PyQt5/Qt/translations'
    language:INFO Attempting to load en_IL/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Attempting to load en/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Qt Detected Languages: ['en-IL']
    language:INFO LANG Environment Variable: en_IL
    language:INFO LOCALE Environment Variable: en_IL
    language:INFO Skipping English language (no need for translation): en_IL
    language:INFO Skipping English language (no need for translation): en_IL
project_data:INFO Setting default profile to HDV 720 24p
         app:INFO Setting font to /usr/lib/python3/dist-packages/openshot_qt/images/fonts/Ubuntu-R.ttf
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
         app:INFO Setting custom dark theme
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "/usr/bin/openshot-qt", line 11, in <module>
    load_entry_point('openshot-qt==2.4.2.dev1', 'gui_scripts', 'openshot-qt')()
  File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 94, in main
    app = OpenShotApp(sys.argv)
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 159, in __init__
    from windows.main_window import MainWindow
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/main_window.py", line 43, in <module>
    from windows.views.timeline_webview import TimelineWebView
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/views/timeline_webview.py", line 40, in <module>
    from PyQt5.QtWebKitWidgets import QWebView
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'
     metrics:INFO Track exception: [200] http://www.openshot.org/exception/json/ | *duplicate-exception-ignored*
      logger:ERROR Exception ignored in:
      logger:ERROR <module 'threading' from '/usr/lib/python3.6/threading.py'>
      logger:ERROR Traceback (most recent call last):
      logger:ERROR   File "/usr/lib/python3.6/threading.py", line 1294, in _shutdown
      logger:ERROR t.join()
      logger:ERROR   File "/usr/lib/python3.6/threading.py", line 1056, in join
      logger:ERROR self._wait_for_tstate_lock()
      logger:ERROR   File "/usr/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
      logger:ERROR elif lock.acquire(block, timeout):
      logger:ERROR KeyboardInterrupt
ENDS

I uninstalled PyQt5 and let it reinstall via apt install openshot-qt - same result 
also tried removing both openshot-qt and PyQt5 and then running from the App image.

Also I noticed that openshot-qt is remaining in memory - at one stage I had fours copies that I had to kill manually.

Latest log: from AppImage:
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2250086/openshot-qt.log)

**Comment by DylanC** [comment]
@david-kohen - Maybe try manually installing python3-pyqt5.qtwebkit.

**Comment by klapperys** [comment]
exact same error i manually installed the webkit running void on my linux setup

**Comment by behnambm** [comment]
This worked for me : 
` $pip3 uninstall pyqt5`

**Comment by ferdnyc** [comment]
@behnambm You're using an AppImage build of OpenShot, I take it? (Not the PPA or other source?)

That's something we should be able to fix, when running that way OpenShot is **supposed** to be importing all of its Python modules from the copies included in the AppImage itself. If it was using the copy of PyQt5 installed on your system (or in your user `$HOME/.local`) instead of the internal copies, then that means there's something its startup scripts aren't doing to properly manage the Python module path.

So, that's extremely helpful information, thanks!

**Comment by behnambm** [comment]
@ferdnyc I installed OpenShot from Mint Software Manager.
Then i executed it , but it didn't work so i removed PyQt5 and i executed it after removing PyQt5 and it worked. 

Sorry for poor English  :)

**Comment by ferdnyc** [comment]
@behnambm I see, thanks.

Yeah, unfortunately with system installs, we're at the mercy of the user's environment — distro packages can try to pull in the right dependencies, but if there are broken (incomplete) modules installed in the user's module path, OpenShot will end up loading those instead.

Don't think there's anything we can really do about that, except maybe put a note about it on the Wiki somewhere. It really comes down to a local configuration error. We don't have control 
over the availability of dependencies, except in the AppImage builds.
