### ISSUE TITLE
Frame indexing needs to be 0-based?

### ISSUE THREAD

**Issue by Algomorph** [OpenShot/openshot-qt#194]
Firstly, I respect the developer(s) for all the work that's being done on the GUI. I realize how someone might have thought it was more intuitive, but I strongly feel like going to 1-based indexing for frames was not a good idea. You get time signatures like 00:13:60 (60fps profile), which make no sense to me (i.e. "what the heck, isn't that second 14?!"). I think the video should start at frame 00, the way it's done in the vast majority of other programs.

**Comment by DylanC** [comment]
@Algomorph - We will take your opinion on board. I'll get some feedback on this and see how we will proceed. Thanks.
