### ISSUE TITLE
Output error for blender 

### ISSUE THREAD

**Issue by tori3425** [OpenShot/openshot-qt#1940]
When I click the x button, a message comes  up in openshot saying Error output: no frame was found in the output from blender. 
I have the blender path set as C:/Program Files/Blender Foundation/Blender/blender.exe which makes the images work and come up but then that other problem comes up.

**Comment by DylanC** [comment]
I put in a change to have browse buttons in future. This will work better in newer releases:
https://github.com/OpenShot/openshot-qt/pull/2255
