### ISSUE TITLE
Video Length

### ISSUE THREAD

**Issue by TheLabeast** [OpenShot/openshot-qt#1941]
I am trying to edit a 15 min video Everything runs perfectly fine until I end up exporting it, It always cuts the video to 8 minutes I need help someone please help me thank u all

**Comment by peanutbutterandcrackers** [comment]
Hey there,

Is the video cutting at 8 mins or is it speeding up and finishing at 8 mins?

Please make sure your footage and the video profile that you are editing in has the same FPS. And please try out a few different export profiles - webm, ogv, mp4, flv, etc. Perhaps one of them will work well?

Hope that helps.

Closing this for now. Please do re-open if you want to.
