### ISSUE TITLE
Failing to open Openshot 2.4.2 on Ubuntu KDE

### ISSUE THREAD

**Issue by Squidyman56** [OpenShot/openshot-qt#1947]
**My Question:**
So I used to use (I cannot remember the name at the moment. Ill edit this if I do remember) as my desktop environment, but I just recently changed to KDE. I wanted to try opening Openshot now that I use KDE, and it opened fine. It had an "Update available" in the top corner, so I clicked it. It brought me to the website where I downloaded the 2.4.2 update. I first tried to run it after checking the "Is Executable" box, and it didn't load. I then downloaded it again, but this time to my desktop, and I checked the "Is Executable" box. It didn't load. I shouldn't need a program to run it, correct? Because it wants to be opened with one of the image viewers or document viewers on my machine. 

**System Details**
 - Operating System / Distro: [Ubuntu 17.10 KDE Plasma Version 5.10.5]
 - OpenShot Version [2.4.2]

**Screenshots**

**Comment by peanutbutterandcrackers** [comment]
Could you please try switching to the PPA and see if that works for you: https://www.openshot.org/ppa/ ?

Also closing this for now as it is very likely that you have figured something out and/or lost interest. However, if you are still around and the issue has not been resolved (or isn't resolved even after switching to the PPA) please do feel free to re-open this. Thanks!
