### ISSUE TITLE
"File Not Found"

### ISSUE THREAD

**Issue by xKings** [OpenShot/openshot-qt#1948]
**Describe the bug**
Hello!, I have been having this problem where whenever i open OpenShot, it will say file not found. If i press okay it will ask to locate the file. I dont know where the file is. It dosent let me use OpenShot. If i press the close button it will ask the same thing. 

**System Details (please complete the following information):**
 - Operating System / Distro: Windows 10
 - OpenShot Version 2.4.2

**Screenshots**
![image](https://user-images.githubusercontent.com/42078899/43669088-81a112e6-974e-11e8-829b-66e297ecf312.png)

![image](https://user-images.githubusercontent.com/42078899/43669105-932e86d8-974e-11e8-8335-cbd73e0f8016.png)

**Comment by peanutbutterandcrackers** [comment]
Sorry for the massively late reply. A fix has gone in for this issue. It should be included with the release of 2.4.4. Please do look forward to it.

Closing this for now.
