### ISSUE TITLE
Cant dismiss tutorial popup window

### ISSUE THREAD

**Issue by mikedilger** [OpenShot/openshot-qt#1949]
**Describe the bug**
I just installed and ran openshot-qt for the first time on ArchLinux.  The main window has a tutorial modal window within.  Clicking on the buttons and/or checkmark on this window has no effect, and it cannot be dismissed.  Kinda makes the whole application unusable.  So I have uninstalled it.

**System Details (please complete the following information):**
 - Operating System / Distro:    Arch Linux
 - OpenShot Version:    2.4.2-1

**To Reproduce**
1. Install OpenShot
2. Run openshot-qt
3. Try to dismiss the modal tutorial window

**Expected behavior**
That buttons on the window would work.

**Comment by PostPollux** [comment]
I have the same problem with Linux Manjaro which is based on Arch. Clicking like crazy on the buttons helps though. With some luck the button works with your 10th or 20th click...
But of course this should be fixed...

**Comment by mozai** [comment]
Using 2.4.1 in Ubuntu linux (v18.04.1) and I'm also running into this, interrupting my work.  Clicking on the "next" button many times will dismiss it temporarily.

**Comment by DylanC** [comment]
@ferdnyc - Back when the tutorial code was the main agenda, did we (you) work on this aspect?

**Comment by ferdnyc** [comment]
Yes, in fact @mozai 's issue is a well-known bug with 2.4.1. The "clicking like crazy" thing is a hallmark of the old tutorial code, so I'm guessing @PostPollux is also running 2.4.1. This issue was one of the primary motivators for the rewrite, and for leveraging QDockWidgets instead of creating our own tutorial windows. (See #1708, #1623, #1555, etc. ad nauseam all the way back to at least #714)

So that _should_ be fixed in 2.4.2, or at least I thought it was. The report from @mikedilger is AFAIK the first we've heard of the non-responsive tutorial popups in the **new** code. I can't deny it's possible, but I don't have an Arch system to test on.

My first suggestion would be to try [the 2.4.2 AppImage](https://github.com/OpenShot/openshot-qt/releases/download/v2.4.2/OpenShot-v2.4.2-x86_64.AppImage).

**Comment by ferdnyc** [comment]
The other strange thing is, a tutorial popup in 2.4.2 _shouldn't_ be a modal dialog, in fact with the new code it's not a dialog at all. So, it shouldn't interfere with using OpenShot. 

On my Fedora 28 system, running 2.4.2 from the rpmfusion package, I can still interact with the OpenShot window even if the tutorial is open. It'll just keep popping back up again until I dismiss it. I can also use Gnome Shell's move-window shortcut (<kbd>Super</kbd>*+drag) to move it out of the way and keep using OpenShot while it's visible, though certain operations (like moving the main OpenShot window) will cause it to return to its default location.

So, if both the tutorial **and** the rest of OpenShot are unresponsive, it may be that OpenShot is frozen.

\* – (Super is AKA the "Windows key")

**Comment by mikedilger** [comment]
Just FYI I don't use openshot (I only had a one-time use case for it, and "clicking like crazy" worked for me).  But I won't close the issue, as it's a general one and some of you are probably still interested in tracking it.

**Comment by ferdnyc** [comment]
Oh, OK. The reason this isn't fixed in 2.4.2 is, 2.4.2 doesn't _have_ the new tutorial code.

It's already fixed for 2.4.3.

**Comment by DylanC** [comment]
@ferdnyc - Makes sense. xD

**Comment by peanutbutterandcrackers** [comment]
Yeah. `2.4.2` didn't have that PR merged. The daily builds work great, though. `2.4.3` is going to be the first one to ship with a proper functional tutorial window, for the first time, thanks to @ferdnyc.

Now, might I, with some fear and hesitation, again remind @ferdnyc of some polishing up that you wanted to do with the code? Drag-able-ization and stuff? If you're feeling up to it, good sir? :)

I realize that probably nobody loves the tutorial pop ups as much as I do. :laughing:

**Comment by ferdnyc** [comment]
I believe my response to @DylanC on the possibility of revisiting the tutorials in a future PR was, and I quote:

> The hell I will

That predated my departure and has nothing to do with the fact that I'm no longer interested in the stress of contributing code to this development black hole (something I was just deftly reminded of), so I don't see how I could be any clearer on that point.

**Comment by ferdnyc** [comment]
Actually, [my exact words](https://github.com/OpenShot/openshot-qt/pull/1726#issuecomment-406297326) in that exchange were:
>>It can always be revisited at a later stage.
>
> The HELL I will.

So, I _was_ even clearer!

**Comment by DylanC** [comment]
@ferdnyc @peanutbutterandcrackers - Tbh, I think the Tutorial area has gotten enough love. We could do with spending time on other more problematic areas. If we could reduce the amount of reports of crashes and failed exports even by 50% that would be a huge improvement.

**Comment by DylanC** [comment]
@mikedilger - Try v2.4.3 and let us know if you still have a problem.

**Comment by peanutbutterandcrackers** [comment]
Closing this issue as the fix has been merged in 2.4.3. Please do re-open if the issue seems to persist (highly unlikely).
