### ISSUE TITLE
Crashes every time I try to export with new version 2.4.2

### ISSUE THREAD

**Issue by ricanmonkey** [OpenShot/openshot-qt#1950]
I installed the newest update today and every time I try to export my project it crashes. It will get between 12-32 % and crash regardless of which format I choose. Any help would be most appreciated. I attached the log immediately after it crashed.
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2259190/openshot-qt.log)

**Comment by clifftopvideo** [comment]
Having similar problems. Have tried all sorts of things such as changing save location, starting project afresh and trying to save the simplest edits. Crash! 
can't manage to attach any files ...

**Comment by rolandh** [comment]
I can't export anything with x264 always crashes.

**Comment by DylanC** [comment]
@ricanmonkey - Try v2.4.3 and let us know if you still have a problem.
