### ISSUE TITLE
I deleted the area where you view your video

### ISSUE THREAD

**Issue by KCGarcia999** [OpenShot/openshot-qt#1951]
I deleted the area where you view your video

**My Question:**
Can you help me? I deleted the area where you view the video you're editing and I can't put it back. How do you put it back?

**System Details**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**Screenshots**

**Comment by KCGarcia999** [comment]
DARN IT REPLY

**Comment by DylanC** [comment]
@KCGarcia999 - Normally I would lock and close any issue with someone shouting in it. However, I'm feeling generous today. You need to restore the layout. I think its Layouts>>Simple View in the menus. 

Look around the options in the menu for "Simple View" and that should restore the default layout.

**Comment by DylanC** [comment]
@KCGarcia999 - Its View>>Views>>Simple View actually.
