### ISSUE TITLE
how to save movie to play video and sound in reverse backward?

### ISSUE THREAD

**Issue by dgd3** [OpenShot/openshot-qt#1952]
**My Question:**

how to save movie to play video and sound in reverse backward?

**System Details**
 - Operating System / Distro: [OSX110.13.3 (17D102)]
OSX110.13.3 (17D102)

 - OpenShot Version [2.4.2]
v2.4.2

**Screenshots**
N/A

**Comment by DylanC** [comment]
@peanutbutterandcrackers - Any ideas on this one? I don't really know.

**Comment by peanutbutterandcrackers** [comment]
I think this is as simple as Right clicking the clip on the timeline and setting the time parameter to go backward by 1x.
![screenshot at 2018-11-27 11-26-22](https://user-images.githubusercontent.com/26764547/49060854-505a0500-f237-11e8-8ebd-e46f1db3a6d7.png)

Hope this helps.
