### ISSUE TITLE
No Audio on Export

### ISSUE THREAD

**Issue by NintendoZaedus** [OpenShot/openshot-qt#1953]
**Describe the bug**
For some reason when I export my video it doesn't have any audio. I am using the following settings for my export:
<img width="455" alt="screen shot 2018-08-04 at 1 30 18 pm" src="https://user-images.githubusercontent.com/42098470/43679428-b386ab4e-97ea-11e8-9f7e-e3bbb0bd7f11.png">
and here is my audio settings
<img width="443" alt="screen shot 2018-08-04 at 1 32 08 pm" src="https://user-images.githubusercontent.com/42098470/43679444-e702e8d4-97ea-11e8-9932-0f90721f5b8e.png">
If you have some better export settings please let me know! Thanks in advance 😸 

**System Details (please complete the following information):**
- I am using the latest version (2.4.1) of Openshot
- I am on MacOS High Sierra 10.13.6

**To Reproduce**
Set your export settings to what the screenshots have
**Expected behavior**
The audio to work

**Comment by DylanC** [comment]
@NintendoZaedus - Can you try v2.4.2? v2.4.1 is no longer the latest version.

**Comment by Baldrickk** [comment]
I'm getting the same issue with 2.4.1 and 2.4.2

**Comment by peanutbutterandcrackers** [comment]
It is very likely that it is just a matter of your audio player not being able to decode the audio stream. Please try VLC Media Player instead. I am sure you will find out that the audio is indeed there. If you can't seem to find a better export setting (webm, or oga export could also fix this issue), you could transcode the final video using [HandBrake](https://handbrake.fr/). Hope that helps.

Closing as answered. Please feel free to re-open if the issue still persists.

**Comment by speedytechdev** [comment]
Hi, @NintendoZaedus  Are you still having this issue and if so have you tried the [daily build](https://www.openshot.org/download/).
