### ISSUE TITLE
I have been unable to download openshot, always say download error

### ISSUE THREAD

**Issue by luluwang12345** [OpenShot/openshot-qt#1958]
**My Question:**
我一直無法下載openshot，總是說失敗-網路錯誤，但網路沒斷過啊~

**System Details**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**Screenshots**

**Comment by DylanC** [comment]
**Google Translate**

I have been unable to download openshot, always say failure - network error, but the network has not broken ah ~

**Comment by peanutbutterandcrackers** [comment]
This might help: https://www.openshot.org/ppa/
