### ISSUE TITLE
Image in video as endscreen

### ISSUE THREAD

**Issue by Skyknight47** [OpenShot/openshot-qt#1960]
**My Question:**
Hello, i have a problem with openshot. 
The whole time i'm editing a YouTube video, and i come to the last step, (I already putted the intro and the clip selfs in) The endscreen! I have made an endscreen so it is a background what says like: "Yo! Thanks for watching, Subscribe Here ->". So if i put it in openshot, it just works, and if i export it it doesn't work. I normally export videos in avi (mpeg4). So i thougt maybe it doesn't work because its avi. so i tried to export it in mp4. but that doenst work either! Then i changed the type of image.(from .png to .jpeg/jpg) IT KEEPS BEING A DIC..
so please help its very important for me and my channel
Thanks!

**System Details**
 - Operating System / Distro: [e.g. Windows 10]
 - OpenShot Version [e.g. 2.4.2]

**Screenshots**

**Comment by DylanC** [comment]
@Skyknight47 - Could be in relation to an issue we had with dropped frames at the end. Can you try a daily build? It should have the fix in it.
