### ISSUE TITLE
"Ran out of input"

### ISSUE THREAD

**Issue by joelpotter** [OpenShot/openshot-qt#1962]
Started a new project, worked on it twice but when I tried to open the project it just says "Failed to load C://MyName/User/Movies/project.osp: Ran out of input

 - Operating System - Windows 10
 - OpenShot Version - 2.4.2

Tried to move the project into a different folder, tried to uninstall and re-install the program. Tried to run it with earlier versions, nothing worked. Anyone else experiencing this problem and know if it can be fixed? Would be nice not having to start all over again.

Thanks!

**Comment by DylanC** [comment]
@joelpotter - If you open the .osp in a text editor does it have content/code/text?
