### ISSUE TITLE
Unable to import videos

### ISSUE THREAD

**Issue by goudjeswimmy** [OpenShot/openshot-qt#1963]
**My Question:**

When I try to import any video, the program freezes for a second, then closes itself. It doesn't display any message and when I start it up again, it doesn't show anything different either. I think there is something wrong with the videos I'm using (they're from my phone) but I can play them on my laptop just fine. How do I fix this?

Edit: It crashes when I play the video in OpenShot, not when it is imported

**System Details**
 - Operating System / Distro: [Windows 10]
 - OpenShot Version [2.4.2]

**Screenshots**

**Comment by DylanC** [comment]
@goudjeswimmy - Hi, what kind of spec machine are you running this on?
