### ISSUE TITLE
Openshot locks up when stepping frame-by-frame

### ISSUE THREAD

**Issue by mlackey99** [OpenShot/openshot-qt#1965]
I am new to Openshot, just downloaded a copy (v2.4.2) a few days ago.  I am seeing an issue.

New project, import video, the control buttons in the video preview window work as advertised, can play, pause, skip to start/end, etc. Works well. Next, press either left-arrow or right-arrow keys. Video stops playing, and for a while am able to step the video frame-by-frame. As long as I don't hit the keys too fast, it seems to work. But when I speed up the rate at which I tap the keys, or I press and hold either
of the arrow keys, it's bad news. The video preview window freezes, the timelines freeze, and nothing works. I see the infamous "please wait" spinney circle. If I click on the main window controls (minimize, maximize, close) I see "not responding" on the window header.  Not doing anything with effects, transitions, etc. just learning the basics and trying to navigate frame-by-frame through the video. I have uninstalled and re-installed several times, behavior is easily repeatable, and not hard at all to replicate. For me, just trying to nav frame-by-frame is enough to cause the problem.

Running on an HP laptop with 16Gb, Core i7 and Windows 8.1 64-bit. Will be glad to supply more info if needed.

**Comment by DylanC** [comment]
@mlackey99 - Can you try v2.4.3 and let us know if you still have a problem.
