### ISSUE TITLE
2.4.2 is even less usable - 3 new bugs

### ISSUE THREAD

**Issue by sknaumov** [OpenShot/openshot-qt#1966]
To be honest, I want to ask, is it tested at all before release?

Just by trying to create a simple video I already encountered 3 new bugs in 2.4.2 not present in earlier releases:
1. When I slice a video, first it is sliced as usual, but then when I move a remaining fragment closer to the beginning (to fill up the gap after the "keep only right" slicing), the right part after "keep both sides" is appeared at the position where it would be without a moving, instead of being just next to the left part.
2. When I want to create a fade transition, default length is 10 seconds. But when I pull its edges to shorten it, transition "blue rectangular" changes, but properties of transition doesn't (it still has 10 seconds length). When I manually put 1,5 seconds length, I then need to manually adjust brightness level at the edges of transition.
3. Sometimes slice of a movie can't be moved - it refuses to do so if cursor (blue raindrop) indicator is in between old place and new place. I first need to move cursor out of place over which I want to drag a video fragment.

**System Details (please complete the following information):**
 - Ubuntu 18.04.1
 - OpenShot 2.4.2

**Comment by DylanC** [comment]
@sknaumov - Can you confirm you still have the bugs in v2.4.3?

**Comment by sknaumov** [comment]
I tested 2.4.3 on Windows so far and see issue (2), but not (1) and (3). Need to check Linux version.

**Comment by DylanC** [comment]
@sknaumov - Actually I think your issue 2 sounds exactly like this one - #640. Do you agree?

**Comment by sknaumov** [comment]
No, issue #640 is very old one and its is about transition that is created automatically when you overlap 2 parts of video. Transition there is fully performed at half of transition blue rectangle.

This issue is new (AFAIR I haven't seen it in 2.4.1): I just tried to add fade transition at the end of my video. Default transition duration is 10 seconds (and so quite long rectangle). When I make transition rectangle shorter to perform transition, say, in 1 second, internal player still performs 10 second transition. And when I start to move this shorter rectangle, it suddenly becomes long again.

**Comment by DylanC** [comment]
@sknaumov - Ahh I see. I've promoted your comment to a new issue with a better title. #2231  I will close this since 2/3 are solved and we can focus on that individual item. :+1:
