### ISSUE TITLE
Software crashing within a couple minutes of launching.  Seemingly random.

### ISSUE THREAD

**Issue by Murball** [OpenShot/openshot-qt#1969]
**Describe the bug**

**System Details (please complete the following information):**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**

**Comment by Murball** [comment]
Sorry, new to this.  I downloaded the Daily Build to try to resolve a problem with the editor randomly crashing after updating a few days ago.  No resolution to issue with Daily build.

**Comment by DylanC** [comment]
@Murball - Try v2.4.3 and let us know if you still have a problem.
