### ISSUE TITLE
Unable to start OpenShot

### ISSUE THREAD

**Issue by Simplyjustaguy** [OpenShot/openshot-qt#1970]
*When ever I try to open Openshot it crashes giving me an error that says: "cx_Freeze Python error in main script" with many different file names under this. What do I do?

**System Details**
 - Operating System / Distro: [Windows 10]
 - OpenShot Version [e.g. 2.4.2]

**Comment by DylanC** [comment]
@Simplyjustaguy - Try v2.4.3 and let us know if you still have a problem.
