### ISSUE TITLE
loading bug

### ISSUE THREAD

**Issue by KMuJu** [OpenShot/openshot-qt#1971]
After 00:03:20 the video takes unusually long time to load and isn't viewable, but when it's loaded it is okey until it needs to load more after 00:03:20. It happens even if i restart the program

 Windows 10
 - OpenShot Version 2.4.2

for me it happened after the editor crashed, so i have no clue how to do it again

**Comment by DylanC** [comment]
@KMuJu - Try v2.4.3 and let us know if you still have a problem.
