### ISSUE TITLE
High Frame rate video is not displaying. Is it supported?

### ISSUE THREAD

**Issue by Therm0phile** [OpenShot/openshot-qt#1972]
High Frame rate video is not displaying. Is it supported?
**My Question:**
I imported a 240 fps video from my iphone, and Openshot will not play it in the video preview window.  the first frame loads, then the window just displays black. The progress bar advances as if there was not a problem. It doesn't matter if I give it plenty of time to load, it does not play. I have 10GB of RAM allocated to the Openshot cache.

This video will play just fine from my system (Media Player), but Openshot seems to not be able to read the file. It exports without error, but the resulting video has the same issue. The first frame is fine, holds for a few seconds, then the rest of the video is black. 
video details:.
Container: Quicktime
Frame-rate: 240
Codec: H.264 (High Profile)
 

Edit: I'm wondering if it is a problem with the video, Openshot, or something else. I would also like to know of any fixes/workarounds.
Edit: 240 FPS should be supported as of 2017. https://github.com/OpenShot/libopenshot/pull/91

**System Details**
 -Distro: Linux Mint 19 Tara
 - OpenShot Version: 2.4.1

**Screenshots**
![screenshot from 2018-08-10 10-36-15](https://user-images.githubusercontent.com/42278524/43972441-3fccf9a8-9c89-11e8-9ba9-20441bcb54a9.png)
![screenshot from 2018-08-10 10-37-14](https://user-images.githubusercontent.com/42278524/43972481-5ed0fa5c-9c89-11e8-8817-e750a5ab7036.png)

**Comment by DylanC** [comment]
> Edit: 240 FPS should be supported as of 2017. OpenShot/libopenshot#91

@Therm0phile  - Hi there, That fix actually went in May 2018. So it would be present only in the daily builds and should be in v2.4.2.

**Comment by Therm0phile** [comment]
I have tried to download the newest version from the Openshot site, but the Appimage wont open. Other AppImages (like the sample one here https://appimage.org/ ) have not had this problem. I set the permissions to allow it to run, then open it. It asks if I want to install a folder, then it doesn't open. I have tried several different versions, nut they all have this issue.
