### ISSUE TITLE
The software doesn't start after installation

### ISSUE THREAD

**Issue by saurabhgayali** [OpenShot/openshot-qt#1977]
**Describe the bug**
I installed and launched for first time. It doesn't start while showing the error.
screenshot:
https://pasteboard.co/HyIfHWh.png

**System Details (please complete the following information):**
 - Operating System /  Windows 10, 64bit
 - OpenShot Version [e.g. 2.4.1]

**To Reproduce**
1. Install
2. Run

**Expected behavior**
It should run
**Screenshots**
https://pasteboard.co/HyIfHWh.png

![hyifhwh](https://user-images.githubusercontent.com/13806535/43994882-07d854a4-9dc2-11e8-9529-0f9aee673d51.png)

**Comment by DylanC** [comment]
@saurabhgayali - Can you try v2.4.2?

**Comment by sck0006** [comment]
I have the same issue verbatim (with a different drive path of course).
I get the same issue with both the 64bit and 32bit versions. 
Both versions 2.4.2.

System Details: Intel i7, Radeon HD 7000 series, 4GB RAM

Operating System / Distro: Windows 10
OpenShot Version: 2.4.2

I've tried setting PYTHONPATH in system variable, matching the program directory for the version I was testing.
I've tried deleting user/.openshot_qt folder.

Reinstalled several times w/ no luck.

I'd attach logs but can't find them.  I'll be happy to help troubleshooting.

**Comment by sck0006** [comment]
Adding a few comments.
I've only got one user account, a Microsoft account.
I created a local account & tried that as well, no luck.

I delete the .openshot_qt folder, but it's always blank, it never appears to have any profile stuff.

**Comment by sck0006** [comment]
I did some more troubleshooting with users but still no luck
I did the following:
Deleted OpenShot
Deleted .openshot_qt folder
restarted
Created New Local User w/ a brand new name so no existing folders, made user Administrator.
restarted
Logged in to new account
Installed Openshot 2.4.2 x64
same error pops up.

I also tried 2.4.1 out of curiosity, still no luck.

I'm not sure if it's supposed to populate anything in the .openshot_qt folders. 
It does create a list of folders each time the program starts
assets; backup; blender; cache; preview-cache; profiles; tests; thumbnails; title; transitions
However, all folders are blank. I'm specifically wondering about the profiles folder, I thought I saw in another post that someone copied a profile over to this folder & it fixed the issue.
Any chance anyone can post their profile info, or an example folder, so I can try it out? I'm not sure how much computer-specific content is in there or if it would do anything, but it may start pointing in the right direction...


![image](https://user-images.githubusercontent.com/42101742/44145777-92a59118-a052-11e8-871d-682e99ac9f7c.png)

**Comment by nlwin2000** [comment]
I uninstalled the new version and reinstall the old version and works. Thank goodness. Apparently the new version is bugged.

**Comment by sck0006** [comment]
Which version did you roll back to? I tried 2.4.1 without any luck.

**Comment by nlwin2000** [comment]
2.4.1 was the working version I had until upgrade which messed me up. I
uninstalled the new and install my old version. It worked for me.

**Comment by saurabhgayali** [comment]
creating new user for a software is too much. That cannot be a bug resolution.

**Comment by DylanC** [comment]
@saurabhgayali - Try v2.4.3 and let us know if you still have a problem.
