### ISSUE TITLE
Creating navigation in a video (.e.g. hotspots, jump to frame)

### ISSUE THREAD

**Issue by masters-george** [OpenShot/openshot-qt#1978]
I did not see any details in the User Guide as to how I might do the following: I create interactive courseware videos. These have hotspots the user can click as part of the learning process. Some of the clickable areas include a previous button and a next button, a clickable menu of topics they can navigate to and short quizzes. These are fairly easy to do in Camtasia and would like to move to an open source cross-platform solution that makes these easy to do. How do I accomplish these in Openshot?

**System Details**
 - Operating System / Distrom-  I have two -- WIndows 10 -- Ubuntu 18.04
 - OpenShot Version [e.g. 2.4.1] - 2.4.2

**Screenshots**

**Comment by DylanC** [comment]
@masters-george - I don't think we support these just yet. Do you know what Camtasia does to support this feature?
