### ISSUE TITLE
I Quit !

### ISSUE THREAD

**Issue by MisterTeeXD** [OpenShot/openshot-qt#1979]
I'm sorry to say this but i officially quit using this Program, i got tired of the bugs getting in my way of editing and all the "Not Responding" Messages i get, i am so tired of being patient to wait for a fix, i am so tired and frustrated, I, MisterTee, quit using this program and i shall move on to a new video editing software starting tomorrow.

Im sorry

MisterTee

**Comment by DylanC** [comment]
@MisterTeeXD - No problem. That's perfectly understandable. Hopefully in the future it will be much more awesome and you will come back. ;)

**Comment by MisterTeeXD** [comment]
I have decided to return, Lets get Openshot fixed for Windows

**Comment by DylanC** [comment]
@MisterTeeXD - Woohoo! :+1:
