### ISSUE TITLE
Where do I fucking start?

### ISSUE THREAD

**Issue by fuckedoff** [OpenShot/openshot-qt#1982]
**Describe the bug**
Christ there are so many fucking bugs you cunt.

**System Details (please complete the following information):**
 - Operating System / Distro: WINDOWS 10
 - OpenShot Version [e.g. 2.4.2]

**To Reproduce**
1. Working between 1second and 7second steps sucks balls.
2. Take a clip, freeze it for 2 seconds, then "time" "fast forward" it to 2x speed, then try and fast fade both ends, it ends up as a shower of fucking shit.
3. Make multiple copies of THE SAME FUCKING CLIP to make something workable.
4. Make titles, LOTS OF THEM, then watch as your shit piece of shit software takes one filename and superimposes it on another, making the last x titles you made take the place of the first x.
5. Jesus what a cunting piece of fucking shit, and this is release? You cunt.
6. I've wasted 20 hours of work, lost, because of your freeware bollocks. I'll be paying for something that works. Cunt.

**Expected behavior**

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**

**Comment by DylanC** [comment]
@fuckedoff - Hello Sir, firstly you might want to read up on these:

Open Source:
https://en.wikipedia.org/wiki/Open-source_software

Freeware:
https://en.wikipedia.org/wiki/Freeware

If you choose not to, well basically freeware is usually tied to a company selling an already successful professional product. Open Source software is merely something worked on by people in their spare time.

If it doesn't work for you then you are perfectly free to spend your money on whatever you wish. Just maybe try to be respectful and learn some manners.

Thank you and have a nice day! =)
