### ISSUE TITLE
Support For NVIDIA GPU h.264 Encode and Decode

### ISSUE THREAD

**Issue by sbeaman** [OpenShot/openshot-qt#1983]
WAIT!!! I know this was asked in #795, #964, and #1190.

However version 12 of LIBAV and version 3.3 of LIBffmpeg both support native encode/decode for H.264 on NVIDIA hardware. (I believe OpenShot currently uses these versions or later)

See: https://developer.nvidia.com/ffmpeg

**Example**: **_To encode a single YUV file into an H.264/HEVC bitstream, use the following command:_**
FFMPEG: ffmpeg -vsync 0 -c:v h264_cuvid -i <input.mp4> -f rawvideo <output.yuv>
LIBAV: avconv -vsync 0 -c:v h264_cuvid -i <input.mp4> -f rawvideo <output.yuv>

It appears all that is required is specifying the h264_cuvid encoder. If possible could a profile exist that uses this encoder? If not could we create our own profile with custom ffmped/libav parameters?

I can't speak to the stability of the ffmpeg/libav implementations, but would not mind a, "Use at your own risk" option in OpenShot for encoding.

Love the software and thank you for taking the time to develop and distribute it for free.

**Comment by sbeaman** [comment]
@DylanC Thank you for taking the time to respond.

Excellent news on the adding support using ffmpeg 4. That version of ffmpeg also adds support for H.264 encoding on AMD hardware.
I would appreciate his feedback if NVIDIA support can be easily enabled on the current version of OpenShot. I do NOT want to do anything to divert effort away from supporting ffmpeg 4.

**Comment by DylanC** [comment]
@sbeaman - Yep, its a great feature to have. Peter has started with AMD hardware and I believe decoding and maybe encoding is already working in a rough manner. I will get back to you on the Nvidia question, as I have much of his messages to catch up on first.

GPU support is taking time because we have been waiting until we can start implementing in a way that will work across all platforms. Windows 10 seems to still be causing much issues with development but maybe not impossible issues to get past.

**Comment by gausie** [comment]
@DylanC why was this closed?

**Comment by DylanC** [comment]
@gausie - This question has been answered.

**Comment by gausie** [comment]
No problem - I am just used to issues being closed when the problem they describe is solved, rather than when they are acknowledged/work begins. But however you run the repo is good with me!

**Comment by RafaelLinux** [comment]
> @sbeaman - We now have a separate branch for this:
> https://github.com/OpenShot/openshot-qt/tree/hardware-support
> 
> It has basic support for Linux so far and of course we hope to get it working on all platforms first before we think about merging it in.

The link is not working  :(

**Comment by danieljsummers** [comment]
@RafaelLinux looks like it was merged and released - https://github.com/OpenShot/openshot-qt/releases/tag/v2.5.0
