### ISSUE TITLE
"Sorry, There was an Error exporting your video: Error while Writing raw video frame"

### ISSUE THREAD

**Issue by PetrosMarion** [OpenShot/openshot-qt#1984]
**My Question:**
WHHHAAAAAT? How does that happen, why does it happen at different percentages, and how do I fix it?

**System Details**
 - Operating System / Intel(R) Core(TM) i7-4700HQ @ 2.40GHz 64-bit
 - OpenShot Version [e.g. 2.4.2]

**Screenshots**

![image](https://user-images.githubusercontent.com/42330771/44011458-58522588-9e7e-11e8-96e9-f2ae86bda165.png)

**Comment by peanutbutterandcrackers** [comment]
Does this issue still persist with the latest release? This is certainly a new issue unlike anything I've seen before. If this still persists, please do attach the logs so that the devs might be able to investigate this. Thank you!

**Comment by hdvprojection** [comment]
I'm getting the same error while trying to export an image sequence, and it doesn't matter if I try TIFFs or PNGs.

I'm running v. 2.4.4, on Xubuntu 19.04. I believe that the attached is the pertinent logfile.
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/3149995/openshot-qt.log)

**Comment by AndyOhhh** [comment]
I'm getting this too when exporting image sequence. Did you find a fix?

**Comment by SuslikV** [comment]
I'm unable to reproduce this with the OpenShot v2.5.1 (Windows build). Can you confirm that the issue is still present?

**Comment by naraink** [comment]
I am getting this right now. With the latest version of openshot, I just downloaded yesterday :(

**Comment by naraink** [comment]
Ignore, I had some space issue (no space left ;)) in my hard disk, fixing it fixed this.
