### ISSUE TITLE
Export crashes program on OS X El Capitan

### ISSUE THREAD

**Issue by bennetttm** [OpenShot/openshot-qt#1987]
**Describe the bug**
after completing and saving a project I choose Export.   I can rename the file or not.  Clicking on Export Video button the dialog window and program window immediately close and there is no export file.  Even does this with no project saved.

**System Details (please complete the following information):**
 - Operating System / Distro: OS X El Capitan version 10.11.5
 - OpenShot Version 2.4.2

**To Reproduce**
1. After opening or creating a project Go to File->Export Video
2. Click on Export Video
3. Application crashes

**Expected behavior**
After clicking on Export Video, expect the dialogue box to close, the program window to remain open, and a new mp4 file created in the designated  location. 

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.  Not sure where log might be for this application.

**Additional context**
don't know if it matters but don't believe Blender or Inkscape is installed on this machine.

**Comment by DylanC** [comment]
@bennetttm - Try v2.4.3 and let us know if you still have a problem.
