### ISSUE TITLE
Program Crash when previewing a saved project.

### ISSUE THREAD

**Issue by hayestc** [OpenShot/openshot-qt#1988]
**Describe the bug**
After saving a project and exiting the program, I am unable to preview the video I was working on.
When I reopen the project, I attempt to preview what I had done, which was put in a picture and then a simple cross-fade transition into the actual video, and upon reaching the cross-fade the entire program crashes.  This happened on two different PCs.

**System Details (please complete the following information):**
 - Both Systems have Windows 10 with latest patches, and 8GB of ram with Quadcore Intel CPU's. I7 -3770k, and I7-3920mx.
 - OpenShot Version 2.4.2

**To Reproduce**
1. Create a project with a picture that transitions into a video.
2. Save Project and Close Openshot
3. Reopen Openshot and load project.
4. Preview video and see crash when preview hits cross-fade.

**Expected behavior**
A full crash of program.

**Screenshots**
I don't have any screenshots.

**Logs**
How do you get logs?

**Additional context**
NA

**Comment by DylanC** [comment]
@hayestc - How did you apply this cross fade you mentioned?

**Comment by hayestc** [comment]
I first put the picture in, made it only 7 seconds, then dragged video in and overlapped it by 2 seconds.  Used the automatically generated crossfade.

**Comment by hayestc** [comment]
Also video is AVCHD video from sony camcorder.

**Comment by michalfita** [comment]
I face same crash on Windows 7. With OpenShot 2.4.3.

**Comment by DylanC** [comment]
@hayestc - This transitions bug has been fixed. See #2125.
