### ISSUE TITLE
Audio glitch.

### ISSUE THREAD

**Issue by lyric643** [OpenShot/openshot-qt#1989]
**Describe the bug**
When I put a video (with the volume on 0%) on a track, with an audio file on a separate track, and then try to play the video, the audio file glitches. 

**System Details (please complete the following information):**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**To Reproduce**
1. Create a project with an audio file, and a video file that has sound.
2. Put them onto separate tracks.
3. Set the volume on the video file to 0%.
4. Preview/play the project.
5. See error.

**Expected behavior**
I expected the audio file to play smoothly with no glitches in the sound.

**Screenshots**
N/A

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**
N/A

**Comment by DylanC** [comment]
@lyric643 - Does this also happen on v2.4.2?

**Comment by lyric643** [comment]
Yes, it does.

**Comment by DylanC** [comment]
@lyric643 - Try v2.4.3 and let us know if you still have a problem.

**Comment by speedytechdev** [comment]
**Closing Warning Reason:** inactive
