### ISSUE TITLE
Possible to slow clip down?

### ISSUE THREAD

**Issue by wgusapukc** [OpenShot/openshot-qt#1990]
**My Question:**

    Hello,
    THank you for all your great work.
    I have a specific question about a project.
    I have a video I wish to play over a song, music video, and I want to make a 1 min clip last for say 1.5 min. Is there a way to make the video play slower to last the duration of the song without reducing quality of the video being manulated?
    Thanks again, I am new to OpenShot and believe the format aswell as the tools are perfect for what I need them for.
    My question is am I wrong?

    Thank you,
    wgusapukc

**Comment by DylanC** [comment]
@wgusapukc - Yes, if you Right Click on the clip you will see the menu options. There is an option in that Time menu to slow the clip down.
