### ISSUE TITLE
[Needs Improvement] Openshot Adds More File Size To Rendered Videos

### ISSUE THREAD

**Issue by MisterTeeXD** [OpenShot/openshot-qt#1994]
**Describe the bug**
When a video is rendered through Openshot, Openshot Will Add More File Size

**System Details (please complete the following information):**
 - Operating System / Distro: [Windows 10]
 - OpenShot Version [2.4.2]

**To Reproduce**
1. Go to File
2. Click on Export Video
3. Look at the file size of the rendered video

**Expected behavior**
Openshot should add less file size while still maintain Quality

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**
I have actually went ahead and tested this with another video editing software. The Video Editing Software I tested this on has less file size added and still maintain Quality when its set to render a 720p video with a Bitrate setting of "Smaller Size" while Openshot adds extra file size when set to render in a Medium Setting and no option to set bitrate from "Better Quality, Standard and Smaller Size".

I think that a option in the Simple Tab in the rendering box should be added so that users can set to "Better Quality, Standard and Smaller Size" bitrate while still maintaining Clear Quality in the video.

**Comment by peanutbutterandcrackers** [comment]
Since #1680 has a lot more detail and discussion, I will proceed to close this issue so as to keep the number of open issues in check.
