### ISSUE TITLE
Really awful performance

### ISSUE THREAD

**Issue by videodude** [OpenShot/openshot-qt#1998]
Hi,

i am having a hard time with openshot since it's painfully slow on my machine...ok itś not the fastest gamer PC in the world but its an i5 3,1 Ghz running linux/kubuntu.
Whenever i import mts files (AVC Codec 15 Mbit) playing comes to a stall, any ideas on what might be causing the issue? 
TIA

**Comment by DylanC** [comment]
@videodude - How does that same video play in the "Videos" application?

**Comment by videodude** [comment]
@DylanC video plays just fine/fluent in VLC and shotcut :O

**Comment by DylanC** [comment]
@videodude - Maybe try convert the video first via the command line:

Assuming you have ffmpeg installed, try this:
`ffmpeg movie007.mts -c:a copy -c:v copy movie007.mp4`

Obviously for the first parameter use the actual name of your video file. :)
