### ISSUE TITLE
live sound and live video recording support to OpenShot

### ISSUE THREAD

**Issue by Reaper10** [OpenShot/openshot-qt#2]
Could there be live sound and live video support to OpenShot one day?

OpenShot  live sound 
I don't know if this is being worked on or not but live sound support would be good to have in Openshot, ie a audio mixer window. The mixer should all so have jack audio support.The Openshot audio tracks could all so use a record button on them.
At the bottom of the Mixer could have a sound input menu on every audio track this way a user can hook up a hardware mixer to a Openshot audio track and record the sound form their hardware mixer without a DAW software. The Openshot mixer's faders and pan knob should be able to read & write volume and pan automation on the track. A the top of the mixer there should be a output menu on every audio track this way a user can hook up a audio output from the Openshot mixer out to a jack audio input. The Jack Audio support is so a user can send the sound from the users DAW software into Openshot an audio tracks or  send the sound from Openshot an audio tracks  to the users DAW .

live video support 
Openshot video tracks need a record button on them.and a Camera recording window where a user can find Camera recording options, like Camera record, Multi Camera record and Multi Camera sync and Multi Camera record monitoring.

**Comment by jonoomph** [comment]
Yes, it could be possible to support live video. I've thought about this quite a bit. We would need to create a libopenshot StreamReader (or something like that), which has no duration, and would allow you to use it like any other reader... I just haven't had time yet. =)

Regarding audio mixers, it will happen at some point. It's just lower on the priorities at the moment. =)
