### ISSUE TITLE
Internationalization improvements

### ISSUE THREAD

**Issue by gupascal** [OpenShot/openshot-qt#20]
Hello,

May it be possible to avoid series of strings like "Cross 1", "Cross 2", ... which are very laborious to translate, and replace them by a single string like "Cross %d" or "Cross {}". This would greatly assist translators in their work.

See https://translations.launchpad.net/openshot/2.0/+pots/openshot/fr/+translate?direction=backwards&memo=960&start=950 for an example.

Thanks

**Comment by jonoomph** [comment]
I did consider this, but just ran out of time. Let me look again, and see what I can do. It's really just the file names in a folder (with _ replaced with " "), which is why there are so many repeats, partial duplicates, etc... It's not your typical translation in other words. =)

**Comment by jonoomph** [comment]
Okay, this has been committed and the changes should show up soon in the translation system on Launchpad.net. Thanks for the suggestion and reminder to do this. I now detect if a transition ends with a number, and change the translatable name to "Transition Name %s", and substitute the number back into the final translation at runtime.
