### ISSUE TITLE
Crash While Exporting Any Video

### ISSUE THREAD

**Issue by SuperFire92** [OpenShot/openshot-qt#2000]
**Describe the bug**
The Title Tells Everything.

**System Details (please complete the following information):**
 Windows 10
 2.4.2

**To Reproduce**
Just Export a Video I guess? This might just be me.

**Expected behavior**
When I export a video, it exports for a few and then crashes with no warning.

**Comment by DylanC** [comment]
@SuperFire92 - Try v2.4.3 and let us know if you still have a problem.
