### ISSUE TITLE
Multiple Projects in same folder overwrite each others assets

### ISSUE THREAD

**Issue by DerGenaue** [OpenShot/openshot-qt#2004]
**Describe the bug**
When having multiple projects in the same folder, Openshot will "share" the assets and thumbnails-folders
When a title is saved in the application, it is not checked properly, whether this filename already exists and titles from other projects are simply overwritten. Very annoying...

**System Details (please complete the following information):**
 - Windows 10 / 7
 - OpenShot 2.4.2

**Expected behavior**
Separate folders should be used for different projects.
Eg. the project-name should be appended to the folder name
(careful when renaming projects)
Also, titles should not overwrite other files without prompting the user.

**Additional Notes**
Something similar can apparently also happen within one single project:
After restarting OpenShot and opening a old project, try to duplicate a title.
The title-name-counter will be reset (to 1) and an already existing title with this name will be overwritten.

**Comment by ferdnyc** [comment]
#2976 will _partly_ solve this, in that each project's assets will be separated and titles from other projects will no longer be overwritten. **_However_**, I hadn't tested the #2041 case where the Title Editor will trample its _own_ filenames after a project is saved and reloaded, and currently that remains an issue with the #2976 code. (Now that I'm aware of it, though, I'm hopeful I can fix that as well.)
