### ISSUE TITLE
Audiobuffer is apparently not cleared on play/pause

### ISSUE THREAD

**Issue by DerGenaue** [OpenShot/openshot-qt#2005]
**Describe the bug**
When pausing the playback in the editor, the sound is paused immediately.
Scrolling to a different position in time and resuming the playback at this point leads to a short piece of audio from the old position being played before the new audio starts.

**System Details (please complete the following information):**
 - Windows 10 / 7
 - OpenShot 2.4.2

**To Reproduce**
1. Empty project
2. Import Music of your choice into the timeline
3. Skip to somewhere within the piece of music
4. Play for a short time; pause again
5. Move the cursor back to the beginning
6. Play again

**Expected behavior**
Audio buffer should be cleared on pause so no audio is left to play when restarting

**Comment by peanutbutterandcrackers** [comment]
I wonder if libopenshot-audio repository is the better place to report this issue. But hey! Good to see a contributor around! I hope you stick to OpenShot and help make it even better!
