### ISSUE TITLE
Adding a new layer crashes the application / takes forever

### ISSUE THREAD

**Issue by DerGenaue** [OpenShot/openshot-qt#2006]
**Describe the bug**
Adding a new layer into a "big" project that is already filled with clips takes so long that windows considers the application crashed.

**System Details (please complete the following information):**
 - Windows 10 / 7
 - OpenShot 2.4.2

**To Reproduce**
1. Have multiple layers in the timeline filled with clips
2. Click on 'Add layer below' on one of the lower layers
3. Layer creation takes longer than 30s

**Expected behavior**
Layer creation should be immediate, as it is when doing on a fresh project or when creating a layer above all other.

**Additional context**
I think this might be due to many changes being applied incrementally by a process (moving all the clips up a layer) and some blocking loop.

**Comment by DylanC** [comment]
@DerGenaue - Try v2.4.3 and let us know if you still have a problem.

**Comment by DerGenaue** [comment]
Nope, still the same
