### ISSUE TITLE
Reduce animations for improved usability / Make animation speed adjustable

### ISSUE THREAD

**Issue by DerGenaue** [OpenShot/openshot-qt#2007]
**Is your feature request related to a problem? Please describe.**
Animations can be useful and beautiful, but there are places where immediate feedback is more important.
This is especially the case for events that happen very often or in quick succession.
The most notable cases for this are the vertical lines in the sequence editor:
* The player position (when clicking)
* The snapping indicator

Especially the latter one triggers many times when moving a clip and every time a movement-animation is started.
This even causes a small lag in the drag additionally to the confusion of the snapping indicator line moving all around the place.
A typical usecase where this is problematic is when choosing between two snapping points that are close together and one is trying to select a specific one

**Describe the solution you'd like**
* No animation on these indicators at all
* UI animation speed option in the settings

**Comment by DerGenaue** [comment]
Did this get implemented or was it just closed to clean up old issues?
Should I test the latest version?

**Comment by ferdnyc** [comment]
@DerGenaue The latter, mostly. There hasn't been any significant change in the Timeline animations. If you're interested in testing out the latest version, sure and I think you'll find it runs more smoothly overall, but if the animations are a dealbreaker then I doubt you'll have a significantly different experience, sorry.
