### ISSUE TITLE
New installation on Ubuntu 18.04.1 LTS fails

### ISSUE THREAD

**Issue by sails1000** [OpenShot/openshot-qt#2009]
I downloaded the Linux installer:

OpenShot-v2.4.2-x86_64.AppImage

I changed its properties to add the executable flag
I executed it with:

./OpenShot-v2.4.2-x86_64.AppImage

After sending a considerable amount of output to the terminal window, it fails with the following message:

preview_thread:INFO QThread Start Method Invoked
preview_thread:INFO initPlayer
 main_window:ERROR Unhandled crash detected... will attempt to recover backup project: /home/tony/.openshot_qt/backup
/tmp/.mount_Mq6VKa/usr/bin/launch: symbol lookup error: /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0: undefined symbol: drmGetDevice2

Any ideas what might be happening?

Thanks,
Tony

**Comment by sails1000** [comment]
Here's the full log...

      launch:INFO ------------------------------------------------
      launch:INFO    OpenShot (version 2.4.2)
      launch:INFO ------------------------------------------------
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_RsIG8W/usr/bin/platforms" ... 
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_RsIG8W/usr/bin/platforms/libqeglfs.so" 
Found metadata in lib /tmp/.mount_RsIG8W/usr/bin/platforms/libqeglfs.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.2",
    "MetaData": {
        "Keys": [
            "eglfs"
        ]
    },
    "className": "QEglFSIntegrationPlugin",
    "debug": false,
    "version": 328193
}


Got keys from plugin meta data ("eglfs") 
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_RsIG8W/usr/bin/platforms/libqkms.so" 
Found metadata in lib /tmp/.mount_RsIG8W/usr/bin/platforms/libqkms.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.2",
    "MetaData": {
        "Keys": [
            "kms"
        ]
    },
    "className": "QKmsIntegrationPlugin",
    "debug": false,
    "version": 328193
}


Got keys from plugin meta data ("kms") 
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_RsIG8W/usr/bin/platforms/libqlinuxfb.so" 
Found metadata in lib /tmp/.mount_RsIG8W/usr/bin/platforms/libqlinuxfb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.2",
    "MetaData": {
        "Keys": [
            "linuxfb"
        ]
    },
    "className": "QLinuxFbIntegrationPlugin",
    "debug": false,
    "version": 328193
}


Got keys from plugin meta data ("linuxfb") 
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_RsIG8W/usr/bin/platforms/libqminimal.so" 
Found metadata in lib /tmp/.mount_RsIG8W/usr/bin/platforms/libqminimal.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.2",
    "MetaData": {
        "Keys": [
            "minimal"
        ]
    },
    "className": "QMinimalIntegrationPlugin",
    "debug": false,
    "version": 328193
}


Got keys from plugin meta data ("minimal") 
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_RsIG8W/usr/bin/platforms/libqminimalegl.so" 
Found metadata in lib /tmp/.mount_RsIG8W/usr/bin/platforms/libqminimalegl.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.2",
    "MetaData": {
        "Keys": [
            "minimalegl"
        ]
    },
    "className": "QMinimalEglIntegrationPlugin",
    "debug": false,
    "version": 328193
}


Got keys from plugin meta data ("minimalegl") 
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_RsIG8W/usr/bin/platforms/libqoffscreen.so" 
Found metadata in lib /tmp/.mount_RsIG8W/usr/bin/platforms/libqoffscreen.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.2",
    "MetaData": {
        "Keys": [
            "offscreen"
        ]
    },
    "className": "QOffscreenIntegrationPlugin",
    "debug": false,
    "version": 328193
}


Got keys from plugin meta data ("offscreen") 
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_RsIG8W/usr/bin/platforms/libqxcb.so" 
Found metadata in lib /tmp/.mount_RsIG8W/usr/bin/platforms/libqxcb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.2",
    "MetaData": {
        "Keys": [
            "xcb"
        ]
    },
    "className": "QXcbIntegrationPlugin",
    "debug": false,
    "version": 328193
}


Got keys from plugin meta data ("xcb") 
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_RsIG8W/usr/platforms" ... 
loaded library "/tmp/.mount_RsIG8W/usr/bin/platforms/libqxcb.so" 
loaded library "Xcursor" 
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_RsIG8W/usr/bin/platformthemes" ... 
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_RsIG8W/usr/platformthemes" ... 
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_RsIG8W/usr/bin/platforminputcontexts" ... 
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_RsIG8W/usr/platforminputcontexts" ... 
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_RsIG8W/usr/bin/generic" ... 
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_RsIG8W/usr/generic" ... 
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_RsIG8W/usr/bin/styles" ... 
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_RsIG8W/usr/styles" ... 
         app:INFO openshot-qt version: 2.4.2
         app:INFO libopenshot version: 0.2.0
         app:INFO platform: Linux-4.15.0-041500-generic-x86_64-with-Ubuntu-18.04-bionic
         app:INFO processor: x86_64
         app:INFO machine: x86_64
         app:INFO python version: 3.4.3
         app:INFO qt5 version: 5.2.1
         app:INFO pyqt5 version: 5.2.1
    language:INFO Attempting to load qt_en_GB.UTF-8 in '/tmp/.mount_RsIG8W/usr/bin/translations'
    language:INFO Attempting to load qt_en in '/tmp/.mount_RsIG8W/usr/bin/translations'
    language:INFO Attempting to load en_GB.UTF-8/LC_MESSAGES/OpenShot in '/tmp/.mount_RsIG8W/usr/bin/locale'
    language:INFO Attempting to load en/LC_MESSAGES/OpenShot in '/tmp/.mount_RsIG8W/usr/bin/locale'
    language:INFO Attempting to load qt_en_GB in '/tmp/.mount_RsIG8W/usr/bin/translations'
    language:INFO Attempting to load qt_en in '/tmp/.mount_RsIG8W/usr/bin/translations'
    language:INFO Attempting to load en_GB/LC_MESSAGES/OpenShot in '/tmp/.mount_RsIG8W/usr/bin/locale'
    language:INFO Successfully loaded en_GB/LC_MESSAGES/OpenShot in '/tmp/.mount_RsIG8W/usr/bin/locale'
    language:INFO Qt Detected Languages: ['en-GB', 'en']
    language:INFO LANG Environment Variable: en_GB.UTF-8
    language:INFO LOCALE Environment Variable: en_GB
    language:INFO Skipping English language (no need for translation): en_GB.UTF-8
    language:INFO Skipping English language (no need for translation): en_GB
project_data:INFO Setting default profile to HDV 720 24p
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_RsIG8W/usr/bin/iconengines" ... 
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_RsIG8W/usr/iconengines" ... 
         app:INFO Setting font to /tmp/.mount_RsIG8W/usr/bin/images/fonts/Ubuntu-R.ttf
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
         app:INFO Setting custom dark theme
connectionpool:INFO Starting new HTTP connection (1): www.google-analytics.com
connectionpool:INFO Starting new HTTP connection (1): www.google-analytics.com
connectionpool:INFO Starting new HTTP connection (1): www.google-analytics.com
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_RsIG8W/usr/bin/imageformats" ... 
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_RsIG8W/usr/bin/imageformats/libqgif.so" 
Found metadata in lib /tmp/.mount_RsIG8W/usr/bin/imageformats/libqgif.so, metadata=
{
    "IID": "org.qt-project.Qt.QImageIOHandlerFactoryInterface",
    "MetaData": {
        "Keys": [
            "gif"
        ],
        "MimeTypes": [
            "image/gif"
        ]
    },
    "className": "QGifPlugin",
    "debug": false,
    "version": 328193
}


Got keys from plugin meta data ("gif") 
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_RsIG8W/usr/bin/imageformats/libqico.so" 
Found metadata in lib /tmp/.mount_RsIG8W/usr/bin/imageformats/libqico.so, metadata=
{
    "IID": "org.qt-project.Qt.QImageIOHandlerFactoryInterface",
    "MetaData": {
        "Keys": [
            "ico"
        ],
        "MimeTypes": [
            "image/vnd.microsoft.icon"
        ]
    },
    "className": "QICOPlugin",
    "debug": false,
    "version": 328193
}


Got keys from plugin meta data ("ico") 
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_RsIG8W/usr/bin/imageformats/libqjpeg.so" 
Found metadata in lib /tmp/.mount_RsIG8W/usr/bin/imageformats/libqjpeg.so, metadata=
{
    "IID": "org.qt-project.Qt.QImageIOHandlerFactoryInterface",
    "MetaData": {
        "Keys": [
            "jpg",
            "jpeg"
        ],
        "MimeTypes": [
            "image/jpeg",
            "image/jpeg"
        ]
    },
    "className": "QJpegPlugin",
    "debug": false,
    "version": 328193
}


Got keys from plugin meta data ("jpg", "jpeg") 
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_RsIG8W/usr/bin/imageformats/libqsvg.so" 
Found metadata in lib /tmp/.mount_RsIG8W/usr/bin/imageformats/libqsvg.so, metadata=
{
    "IID": "org.qt-project.Qt.QImageIOHandlerFactoryInterface",
    "MetaData": {
        "Keys": [
            "svg",
            "svgz"
        ]
    },
    "className": "QSvgPlugin",
    "debug": false,
    "version": 328193
}


Got keys from plugin meta data ("svg", "svgz") 
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_RsIG8W/usr/imageformats" ... 
loaded library "/tmp/.mount_RsIG8W/usr/bin/imageformats/libqsvg.so" 
link SVGID_18_-5 hasn't been detected!
link SVGID_18_-5 hasn't been detected!
link SVGID_22_-5 hasn't been detected!
link SVGID_24_-2 hasn't been detected!
link SVGID_24_-2 hasn't been detected!
loaded library "/tmp/.mount_RsIG8W/usr/bin/imageformats/libqgif.so" 
loaded library "/tmp/.mount_RsIG8W/usr/bin/imageformats/libqico.so" 
loaded library "/tmp/.mount_RsIG8W/usr/bin/imageformats/libqjpeg.so" 
     metrics:INFO Track metric: [200] http://www.google-analytics.com/collect?cd1=0.2.0&av=2.4.2&cd5=Ubuntu-18.04-bionic&cd4=5.2.1&an=OpenShot+Video+Editor&t=screenview&tid=UA-4381101-5&cd=main-screen&ul=en-gb&aid=org.openshot.openshot-qt&v=1&cid=1a5c2a48-4098-4d39-81a0-cdd7d3dd95b8&cd2=3.4.3&ua=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&aip=1&cd3=5.2.1 | (35 bytes)
     metrics:INFO Track metric: [200] http://www.google-analytics.com/collect?cd1=0.2.0&av=2.4.2&cd5=Ubuntu-18.04-bionic&cd4=5.2.1&an=OpenShot+Video+Editor&t=screenview&tid=UA-4381101-5&cd=launch-app&ul=en-gb&aid=org.openshot.openshot-qt&v=1&cid=&sc=start&cd2=3.4.3&ua=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&aip=1&cd3=5.2.1 | (35 bytes)
     metrics:INFO Track metric: [200] http://www.google-analytics.com/collect?cd1=0.2.0&av=2.4.2&cd5=Ubuntu-18.04-bionic&cd4=5.2.1&an=OpenShot+Video+Editor&t=screenview&tid=UA-4381101-5&cd=initial-launch-screen&ul=en-gb&aid=org.openshot.openshot-qt&v=1&cid=1a5c2a48-4098-4d39-81a0-cdd7d3dd95b8&cd2=3.4.3&ua=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&aip=1&cd3=5.2.1 | (35 bytes)
     ui_util:INFO Initializing UI for MainWindow
     ui_util:INFO Binding event MainWindow:actionNew_trigger
     ui_util:WARNING Icon theme document-new not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionOpen_trigger
     ui_util:WARNING Icon theme document-open not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionSave_trigger
     ui_util:WARNING Icon theme document-save not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionUndo_trigger
     ui_util:WARNING Icon theme edit-undo not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionSaveAs_trigger
     ui_util:WARNING Icon theme document-save-as not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionImportFiles_trigger
     ui_util:WARNING Icon theme list-add not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionImportImageSequence_trigger
     ui_util:WARNING Icon theme list-add not found. Will use backup icon.
     ui_util:WARNING Icon theme list-add not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionRedo_trigger
     ui_util:WARNING Icon theme edit-redo not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionRemoveClip_trigger
     ui_util:WARNING Icon theme list-remove not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionRemoveTransition_trigger
     ui_util:WARNING Icon theme list-remove not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionExportVideo_trigger
     ui_util:WARNING Icon theme media-record not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionUploadVideo_trigger
     ui_util:WARNING Icon theme folder-remote not found. Will use backup icon.
     ui_util:WARNING Icon theme system-shutdown not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAddTrack_trigger
     ui_util:WARNING Icon theme list-add not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionPreferences_trigger
     ui_util:WARNING Icon theme document-properties not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionPlay_trigger
     ui_util:WARNING Icon theme media-playback-start not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionJumpStart_trigger
     ui_util:WARNING Icon theme media-skip-backward not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionRewind_trigger
     ui_util:WARNING Icon theme media-seek-backward not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionFastForward_trigger
     ui_util:WARNING Icon theme media-seek-forward not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionJumpEnd_trigger
     ui_util:WARNING Icon theme media-skip-forward not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionArrowTool_trigger
     ui_util:INFO Binding event MainWindow:actionRazorTool_trigger
     ui_util:INFO Binding event MainWindow:actionSnappingTool_trigger
     ui_util:INFO Binding event MainWindow:actionAddMarker_trigger
     ui_util:INFO Binding event MainWindow:actionPreviousMarker_trigger
     ui_util:WARNING Icon theme go-first not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionNextMarker_trigger
     ui_util:WARNING Icon theme go-last not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionFilesShowAll_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowVideo_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowAudio_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowImage_trigger
     ui_util:WARNING Icon theme edit-clear not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionTransitionsShowAll_trigger
     ui_util:INFO Binding event MainWindow:actionTransitionsShowCommon_trigger
     ui_util:WARNING Icon theme edit-clear not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionEffectsShowAll_trigger
     ui_util:INFO Binding event MainWindow:actionEffectsShowVideo_trigger
     ui_util:INFO Binding event MainWindow:actionEffectsShowAudio_trigger
     ui_util:WARNING Icon theme edit-clear not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionTimelineZoomIn_trigger
     ui_util:WARNING Icon theme zoom-in not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionTimelineZoomOut_trigger
     ui_util:WARNING Icon theme zoom-out not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionTitle_trigger
     ui_util:WARNING Icon theme font not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAnimatedTitle_trigger
     ui_util:WARNING Icon theme video-x-generic not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionFullscreen_trigger
     ui_util:WARNING Icon theme view-fullscreen not found. Will use backup icon.
     ui_util:WARNING Icon theme zoom-in not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAbout_trigger
     ui_util:WARNING Icon theme gtk-info not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionThumbnailView_trigger
     ui_util:WARNING Icon theme view-list-icons not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionDetailsView_trigger
     ui_util:WARNING Icon theme view-list-details not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionReportBug_trigger
     ui_util:WARNING Icon theme dialog-error not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAskQuestion_trigger
     ui_util:WARNING Icon theme im-message-new not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionTranslate_trigger
     ui_util:WARNING Icon theme stock_person not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionDonate_trigger
     ui_util:WARNING Icon theme bookmark-new not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionHelpContents_trigger
     ui_util:WARNING Icon theme help not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionSimple_View_trigger
     ui_util:WARNING Icon theme go-home not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAdvanced_View_trigger
     ui_util:WARNING Icon theme get-hot-new-stuff not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionFreeze_View_trigger
     ui_util:WARNING Icon theme locked not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionUn_Freeze_View_trigger
     ui_util:WARNING Icon theme locked not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionShow_All_trigger
     ui_util:WARNING Icon theme zoom-in not found. Will use backup icon.
     ui_util:WARNING Icon theme document-open-recent not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionProfile_trigger
     ui_util:WARNING Icon theme video-x-generic not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAdd_to_Timeline_trigger
     ui_util:WARNING Icon theme list-add not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionPreview_File_trigger
     ui_util:WARNING Icon theme media-playback-start not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionRemove_from_Project_trigger
     ui_util:WARNING Icon theme list-remove not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionFile_Properties_trigger
     ui_util:WARNING Icon theme video-x-generic not found. Will use backup icon.
     ui_util:WARNING Icon theme edit-clear not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionRemoveTrack_trigger
     ui_util:WARNING Icon theme list-remove not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionRemoveMarker_trigger
     ui_util:WARNING Icon theme list-remove not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAddTrackAbove_trigger
     ui_util:WARNING Icon theme list-add not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAddTrackBelow_trigger
     ui_util:WARNING Icon theme list-add not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionRemoveEffect_trigger
     ui_util:WARNING Icon theme list-remove not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionSplitClip_trigger
     ui_util:WARNING Icon theme edit-cut not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionProperties_trigger
     ui_util:WARNING Icon theme document-properties not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionRenameTrack_trigger
     ui_util:WARNING Icon theme gtk-edit not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionUpdate_trigger
     ui_util:WARNING Icon theme package-upgrade not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionTutorial_trigger
     ui_util:WARNING Icon theme im-message-new not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAnimation_trigger
     ui_util:WARNING Icon theme video-x-generic not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionLockTrack_trigger
     ui_util:INFO Binding event MainWindow:actionUnlockTrack_trigger
     ui_util:WARNING Icon theme transform-move not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionEditTitle_trigger
     ui_util:WARNING Icon theme gtk-edit not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionDuplicateTitle_trigger
     ui_util:WARNING Icon theme edit-copy not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionClearHistory_trigger
     ui_util:WARNING Icon theme edit-clear not found. Will use backup icon.
connectionpool:INFO Starting new HTTP connection (1): www.openshot.org
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_RsIG8W/usr/bin/sensors" ... 
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_RsIG8W/usr/sensors" ... 
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_RsIG8W/usr/bin/bearer" ... 
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_RsIG8W/usr/bearer" ... 
 files_model:INFO updating files model.
transition_model:INFO updating transitions model.
effects_model:INFO updating effects model.
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
properties_model:INFO updating clip properties model.
 main_window:INFO InitCacheSettings
 main_window:INFO cache-mode: CacheMemory
 main_window:INFO cache-limit-mb: 250
 main_window:INFO Creating CacheMemory object with 262144000 byte limit
preview_thread:INFO QThread Start Method Invoked
preview_thread:INFO initPlayer
 main_window:ERROR Unhandled crash detected... will attempt to recover backup project: /home/tony/.openshot_qt/backup
/tmp/.mount_RsIG8W/usr/bin/launch: symbol lookup error: /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0: undefined symbol: drmGetDevice2

**Comment by peanutbutterandcrackers** [comment]
This issue has already been resolved in the [daily builds](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914), or, you could also switch to the [PPA](https://www.openshot.org/ppa/). There was some issue with a package and that was resolved by a new commit and this issue will not happen with 2.4.3, at the very least.

If you do not want to be bothered with all that, you can try [this work-around](https://github.com/OpenShot/openshot-qt/issues/1757#issuecomment-402237492).

Closing this as answered. Please feel free to re-open if the answer is not of help.
