### ISSUE TITLE
Feature instagram profile

### ISSUE THREAD

**Issue by purencool** [OpenShot/openshot-qt#201]
Currently I have created a small video for instagram however it does not mater what format I export it as it won't work. I am wondering could you create a profile that would automatically export it into an instagram or twitter video?

**Comment by JtLively** [comment]
Have you tried looking up the standard format for Instagram videos?

**Comment by peanutbutterandcrackers** [comment]
@JtLively whoa! We had moderators other than @DylanC too? Please do make a return to help OpenShot again!

**Comment by gary9872** [comment]
I took a stab at  a profile for instagram. 

You can try it here: 

https://github.com/gary9872/openshot-presets-testing

**Comment by peanutbutterandcrackers** [comment]
@gary9872 - Awesome! Thank you!

@DylanC - You might want to take a look at this, cap'ain! I don't have neither twitter, nor instagram... :D

**Comment by DylanC** [comment]
@peanutbutterandcrackers - I don't have Instagram either but I will put in a PR sometime soon enough. I will just leave this link here for myself, as I need to know the video spec.

http://support.schedugr.am/support/solutions/articles/1000201572-instagram-video-specifications

**Comment by peanutbutterandcrackers** [comment]
@DylanC - Awesome!

**Comment by wes-novack** [comment]
Has anyone successfully utilized the instagram video profile/settings contained here?  https://github.com/gary9872/openshot-presets-testing

**Comment by DylanC** [comment]
@wes-novack - I haven't yet but if I want to get the instagram profile added to the source code I will need to test it first.

**Comment by DylanC** [comment]
@wes-novack - Yes, we shouldn't ever really use ac3. We made a change to this a while back:
https://github.com/OpenShot/openshot-qt/pull/1747

Good to hear it worked! :+1:

**Comment by DylanC** [comment]
@purencool @wes-novack  - Instagram and Twitter presets have now been added. Thanks @gary9872 , I based them on your link above.

**Comment by plieningerweb** [comment]
just to note, tried this as well. But preview video was still horizontal

see me notes at https://gist.github.com/plieningerweb/05ebc827d0bf72b05c0bac70a1b391ac

**Comment by DylanC** [comment]
@ferdnyc - Instagram profile may need to be updated based on the comment above ^.

**Comment by ferdnyc** [comment]
The instagram preset itself is fine, the issue seems to be that it list six profile options:

https://github.com/OpenShot/openshot-qt/blob/ff78c8943155b903171219352c727428c0871ac5/src/presets/instagram.xml#L21-L26

The problem is, those last two don't.. um... _exist_.

They can be created, and that may solve this, but another part of the issue is, if the user's input video is created in the usual cellphone manner (recorded as a horizontal video at `1920×1080` or similar HD format, but encoded with metadata that rotates it 90°), it would probably be _better_ to create the export video the same way, rather than actually rotating it, then exporting a `1080×1920` video with no rotation. And libopenshot isn't well set up to do that. (See OpenShot/libopenshot#322.)

Still, creating the vertical profiles should help some, I'll do that now.

**Comment by ferdnyc** [comment]
I've created #3054 to add the vertical profiles. @plieningerweb if you'd like to test them now, the attached zip file contains both new profile files, which will be picked up by OpenShot if they're added to the `.openshot_qt/profiles/` directory in your user homedir. (You may have to create the `profiles` directory if it doesn't already exist.)

**Comment by ferdnyc** [comment]
Hmf. Those are really hard to find, our profile list is getting too long. I wonder if it would be better to rename them "Vertical HD 720p 30 fps" and "Vertical HD 1080p 30 fps" so they don't get lost in all the rest of the "HD" options?

**Comment by ferdnyc** [comment]
(The "attached zip file" from two comments ago:) 
[vertical-profiles.zip](https://github.com/OpenShot/openshot-qt/files/3785223/vertical-profiles.zip)

**Comment by ferdnyc** [comment]
#3054 is merged, so for testing purposes the next set of Daily Builds will also include the vertical profiles.

**Comment by ferdnyc** [comment]
Whoops. Well, the presets required a quick fix, but #3055 is also merged, so **now** the vertical profiles should be usable in the Daily Builds.

**Comment by ferdnyc** [comment]
@plieningerweb 

I took a look at the Gist you posted — excellent idea, BTW, I wish more users would supply us with that kind of information, it helps us help them.

Too many of our bug reports go something more like, "I worked on my project for 6 hours, then exported a video and it came out wrong!!!!!!!!!!1!!!!!one!!!". As sympathy-inducing as that statement obviously is, there's still nothing we can actually **fix** there, so unsurprisingly whatever issue the user encountered will still be an issue 6 months later when some _other_ user encounters it and replies, "ME2!!!! Y U NO FIX YET???" :roll_eyes:

Aaaanyway... I did have a couple of comments/questions.

1. I can't explain why the preview video would've formatted horizontally for you, if you were using the custom `720×1420` profile you mentioned. When I activate one of the built-in "HD Vertical" profiles in the development version of OpenShot (now that they're there), the preview definitely reformats.
    
    With my default "HD 720p 30 fps" profile:
    ![image](https://user-images.githubusercontent.com/538020/67848321-ce273000-fada-11e9-86d9-b59d714720f8.png)

    After switching to "HD Vertical 720p 30 fps":
    ![Screenshot from 2019-10-30 06-02-57](https://user-images.githubusercontent.com/538020/67848468-20685100-fadb-11e9-8b6a-c9e41750ac9c.png)

    The only thing I can think of that might matter: What version of OpenShot are you running? Preview aspect ratio changes were somewhat broken in versions prior to... either 2.4.4 or 2.4.3, I can't recall. But if you're running 2.4.4, or _certainly_ if you're working off one of the Daily Builds, the aspect ratio **should** change to match your project's current profile.

1. Speaking of project profiles: There's no reason to change the Default Profile in the Settings and restart OpenShot, just to work in a different profile. Each project has its own profile setting. ("Default Profile" is exactly that — it's the one that's initially selected, but you can change it at any time.) And even changing the Default Profile _won't_ affect the profile used on existing saved projects.

    To set the profile for an individual project (either when first creating it, or one that's already in progress), you can either select **File > Choose Profile...** from the menu, or use the toolbar icon two in from the right side (between "Import Files" and "Fullscreen". It'll bring up a profile selection dialog window (as seen in my second screenshot).

1. Post-processing your exports with `ffmpeg -vcodec libx264 -crf 24` to reduce the export size is a clever workaround! But if your only reason for postprocessing is to reencode at `CRF 24` quality, it's actually possible to eliminate that step and just export directly from OpenShot with the same parameters. All it requires is that you be willing to delve into the Advanced configuration for the Export window.
    
    In Export's Advanced view, the High/Medium/Low Quality selector is replaced by direct fields for all of the output parameters, including (in the "Video Settings" pane) the "Bit Rate / Quality" field. If you have "Instagram" selected in the Simple tab as the "Target" preset, and "High" selected for Quality, "Bit Rate / Quality" will initially be filled in with "5.50 Mb/s", most likely.  But OpenShot will export with exactly the same parameters, if you edit that field to contain "crf 24". (Lowercase 'crf', a space, and then the number 24 — I'm not sure how picky it is, so best not to deviate.) That _**should**_ result in Export creating a file roughly the same size and quality as the result of your `ffmpeg` post-processing command. I'd be interested to hear the results if you try it out.

    Like I said, that feature's currently undocumented, and that's kind of shameful. But the `x265` presets do make use of it internally for their High/Medium/Low Quality levels, and though the rest of the codecs are all fixed-bitrate configurations, at least `x264` supports it — I believe in 2.4.4 release, and definitely in the devel code (Daily Builds). We still really need to both make variable bitrate encoding more available to users (so they can use it even from Export's Simple tab), and better-explained in the existing interface (such that it is).

**Comment by plieningerweb** [comment]
@ferdnyc 

Thank you for that extensive and awesome answer! I think that will help a lot of other users as well.

Regarding your point 2, preview for me did not change after applying my custom vertical instagram option. I use the appimage version 2.4.4

![Screenshot from 2019-10-30 15-46-11](https://user-images.githubusercontent.com/481107/67868671-90eb8e00-fb2c-11e9-85fe-506ae863207c.png)
![Screenshot from 2019-10-30 15-45-01](https://user-images.githubusercontent.com/481107/67868673-91842480-fb2c-11e9-962e-9b7a5946b496.png)

I could not find the preset "HD Vertical 720p 30 fps" you have chosen, maybe it is only in the dev version.

regarding 2 and 3: thanks for the tipps! Totally makes sense!
