### ISSUE TITLE
Program crashes when trying to open saved project

### ISSUE THREAD

**Issue by MarkHighPeak** [OpenShot/openshot-qt#2012]
**Describe the bug**
First time I have used this program.  Spent a hour creating and saving the file .osp as I went along.  When I closed the program, then sub-sequentially reopened it, when I tried to open the .osp file, it would open, then after about 5 seconds, the whole program just crashed and closed down, even if I don't touch the computer. 

**System Details (please complete the following information):**
 - Operating System Windows 10
 - OpenShot Version 2.4.2

**To Reproduce**

**Expected behavior**
I thought the program would open the saved file so I could continue to work on it,

**Screenshots**
N/A

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.  Please advise how ?

**Additional context**

**Comment by ilseg** [comment]
I have the same problem. I try to open the .osp file, and the program says: "20180811_154734.jpg cannot be found" (20180811_154734 is not the name of my file by the way. the name of my file is a written name, not a number"

**Comment by DylanC** [comment]
@MarkHighPeak - Try v2.4.3 and let us know if you still have a problem.

**Comment by peanutbutterandcrackers** [comment]
@blaze84 - sorry for the delayed response. I think it is because of a history bug (a fix for which is on it's way to being merged into the main source tree). Could you please attach a zipped version of the .osp file here? Perhaps I could remove the history stack from the project file and attach it again for you...
