### ISSUE TITLE
how do i cancel a project as a whole, i started off wrong in the first place.

### ISSUE THREAD

**Issue by fth28** [OpenShot/openshot-qt#2016]
**My Question:**

**System Details**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**Screenshots**

**Comment by DerGenaue** [comment]
`File` -> `New Project`

**Comment by peanutbutterandcrackers** [comment]
Yes. You might want to delete the project entirely and do what @DerGenaue has pointed out.

Closing this as answered. Hope that helps. Please feel free to reopen if this doesn't resolve your issue. Thank you.

**Comment by Geshelin** [comment]
I have the same issue, and this so-called answer is worthless. If, PB&C, I knew how to delete the project entirely I wouldn't be looking for answers to how to delete the project entirely.
