### ISSUE TITLE
After install (32-bit, on latest W10), won't start OS2

### ISSUE THREAD

**Issue by MichCapich** [OpenShot/openshot-qt#2017]
**Describe the bug**
After clean install, OS2 won't start.

**System Details (please complete the following information):**
 - Operating System / Distro: Windows10 32-bit 1803 (Dutch)
 - OpenShot Version 2.4.2, used 32-bit installer

**To Reproduce**
I just start the application... Few seconds... and got the error, as shown in attachment. From then, nothing.

**Expected behavior**
Just starting OS2

**Screenshots**
Added

**Logs**
-- none --

**Additional context**
-- none --

![knipsel](https://user-images.githubusercontent.com/42606460/44457691-368b9f00-a604-11e8-886a-b200b92c9984.PNG)

**Comment by peanutbutterandcrackers** [comment]
Since windows 10 is most probably 64 bit, please do use the 64 bit one for now. However, I do think this issue is quite interesting. Therefore, despite closing it for now, I will be keeping it on my list of interesting issues to look at. Please do feel free to re-open and/or make further comments.
