### ISSUE TITLE
Preview too slow to be usable (<1 FPS)

### ISSUE THREAD

**Issue by mortoray** [OpenShot/openshot-qt#2018]
I dragged a single 1920x1080 video into OpenShot and tried to playback. The preview gave a slow sequence of post cards, less than one update per second.

**System Details (please complete the following information):**
(K)Ubuntu 18.04
OpenShot 2.4.1
Intel(R) Core(TM) i7-7820X CPU @ 3.60GHz (8core)
32G RAM
GeForce GTX 1060 6GB (2560x1440)

I tried reducing the preview pane size and it has no effect.

I've set the Cache settings to use 2048MB of RAM.

**Comment by peanutbutterandcrackers** [comment]
This is a known issue and work is being done to fix this. It might not be until few more releases before this is completely resolved, however. But please do look forward to the future.

Closing for now.

However, seeing that you are an experienced programmer, I would like to request you to perhaps help out, volunteer with OpenShot. We do not have enough programmers helping us out and we are most certainly in need for someone like you! :)
