### ISSUE TITLE
Are H5P interactive HTML5 elements available in the editor?

### ISSUE THREAD

**Issue by LeopardLady** [OpenShot/openshot-qt#2019]
Hi Guys,
Just discovered your OpenShot editor - very groovy! Looking forward to working with it.

Question please: are H5P interactive HTML5 elements available in the editor in any way? Or is it possible for us to import them into the editor in some way? -- https://h5p.org/

Thank you,
LL

**Comment by peanutbutterandcrackers** [comment]
I don't think there is support for that in OpenShot, yet. Sorry. Perhaps in the future? Some day?

Oh, and this might be of some help to you if you're new to OpenShot: https://gist.github.com/peanutbutterandcrackers/f0f666243133e0ed25abbc12a4ba23d7

Hope you enjoy using OpenShot!

[Closing as answered]
