### ISSUE TITLE
Openshot does not accept any videos and has weird start up 

### ISSUE THREAD

**Issue by fjordson** [OpenShot/openshot-qt#202]
I am running Debian stretch according to lsb_release -a
And Debian stretch/sid according to cat /etc/*-release

---

Upon launching the program I see this box:
[http://i.imgur.com/3h18tnm.jpg](url)

Sometimes it will freeze and I'll have to kill from terminal.  Others time I can just close it out.  Then it comes back two more times.  After closing the box out two more times I get to the actual GUI of the program.  Then I try to drag videos and I get the message that each file is unsupported no matter the type.

Here is the output when I run the program from the terminal:

`Added /usr/share/openshot to system path

------------------------- ERROR 1 ------------------------------
Failed to import 'from openshot import main'
Error Message: cannot import name main
----------------------------------------------------------------
--------------------------------
   OpenShot (version 1.4.3)
--------------------------------
Process no longer exists: 8067.  Creating new pid lock file.
No LADSPA plugins were found!

Check your LADSPA_PATH environment variable.
mlt_repository_init: failed to dlopen /usr/lib/i386-linux-gnu/mlt/libmltavformat.so
  (/usr/lib/i386-linux-gnu/libass.so.5: undefined symbol: FT_Outline_EmboldenXY)
/usr/share/openshot/openshot/windows/SimpleGtkBuilderApp.py:32: GtkWarning: Unable to locate theme engine in module_path: "adwaita",
  self.builder.add_from_file(path)

Detecting formats, codecs, and filters...
Warning: Could not get list of video codecs using the MLT API.  Falling back to 'melt' executable.
Warning: Could not get list of audio codecs using the MLT API.  Falling back to 'melt' executable.
Warning: Could not get list of formats using the MLT API.  Falling back to 'melt' executable.
state saved
`

Not sure what to do.  Guess I'm missing downloading something.

**Comment by jonoomph** [comment]
Not sure what's happening. However, it's worth pointing out this error is with the 1.x branch of OpenShot, and all development is now focusing on the 2.x branch (openshot-qt). You might try that! =)

**Comment by johnLIC** [comment]
Thanks for the tip!  I was struggling to get version 1.4.3 (?) working on CentOS 7 until I found this thread.  OpenShot is such a great piece of software!  The new version looks snaazier than the previous version I had.  Thanks!
