### ISSUE TITLE
Small clip from feature lenght Video trimmed incorrectly

### ISSUE THREAD

**Issue by jedikalimero** [OpenShot/openshot-qt#2020]
**Describe the bug**
I was trying to cut a less than 4 seconds clip with audio from "Star Wars A New Hope"
 but the result is buggy.

**System Details (please complete the following information):**
 - Windows 10
 - 2.4.2

**To Reproduce**
I created a new project.
Added a MKV video of the movie "Star Wars A New Hope". The properties of the video are in the Aditional context section (extracted with MediaInfo).

As you can see, It has 3 audio tracks and subtitles but OpenShot seem to load only the first audio track (Spanish AC-3) or maybe it is the second (Spanish DTS) (but I wanted the Spanish audio, anyway)

I put the video in an editor track and locate the piece I want to save. I use the razor tool a few times around the piece and delete the unwanted parts until I have exactly the piece that I want.

In properties, I change volume to 5 because it was sounding very low. (it doesn't sound so low in MPC or VLC when playing).

I play the clip and check everything is just as I wanted.
I click the export button and save with defaults (MP4 h.264, HDV 720 24p (1280x720) Quality high, ACC audio). The total lenght is 95 frames (less than 4 seconds, just the phrase from Tarkin to Leia: "Charming to the end")

I play the exported video in MPC. At the beginning, there is a little jump in a frame and when he starts to say "...to the end", the image freezes until the end of the clip. In other players not only the image freezes but also the audio, so you can only hear "Charming toooooooooo".

I have tried to attach a ZIP file containing the resulting MP4:
[Untitled Project.zip](https://github.com/OpenShot/openshot-qt/files/2312034/Untitled.Project.zip)

**Expected behavior**
A correct export result.

**Additional context**

General
Unique ID                   : 246194238325967879557042009203884532719 (0xB937491B4BDC317B9DC05819C5C9A3EF)
Complete name               : S:\PELICULAS\Ciencia Ficcion\Star Wars\Star Wars IV - Una.nueva.esperanza.BDrip.1080.(Spanish.Ac3.DTS.English.Ac3).by.Nestai.mkv
Format                      : Matroska
Format version              : Version 2
File size                   : 13.3 GiB
Duration                    : 2 h 4 min
Overall bit rate            : 15.3 Mb/s
Movie name                  : Star Wars IV Una nueva esperanza BDrip 1080 by Nestai
Encoded date                : UTC 2011-09-23 14:01:42
Writing application         : mkvmerge v4.9.1 ('Ich will') creado el Jul 11 2011 23:53:15
Writing library             : libebml v1.2.1 + libmatroska v1.1.1

Video
ID                          : 1
Format                      : AVC
Format/Info                 : Advanced Video Codec
Format profile              : High@L4.1
Format settings             : CABAC / 4 Ref Frames
Format settings, CABAC      : Yes
Format settings, ReFrames   : 4 frames
Codec ID                    : V_MPEG4/ISO/AVC
Duration                    : 2 h 4 min
Bit rate                    : 13.1 Mb/s
Width                       : 1 920 pixels
Height                      : 816 pixels
Display aspect ratio        : 2.35:1
Frame rate mode             : Constant
Frame rate                  : 23.976 (24000/1001) FPS
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 8 bits
Scan type                   : Progressive
Bits/(Pixel*Frame)          : 0.350
Stream size                 : 11.3 GiB (85%)
Title                       : Star Wars IV Una nueva esperanza BDrip 1080 by Nestai
Writing library             : x264 core 116 r2074 2641b9e
Encoding settings           : cabac=1 / ref=4 / deblock=1:-2:-1 / analyse=0x3:0x113 / me=esa / subme=10 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=12 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=2pass / mbtree=1 / bitrate=13143 / ratetol=1.0 / qcomp=0.60 / qpmin=10 / qpmax=51 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / vbv_maxrate=30000 / vbv_bufsize=20000 / nal_hrd=none / ip_ratio=1.40 / aq=1:1.00
Language                    : Spanish
Default                     : Yes
Forced                      : No

Audio #1
ID                          : 2
Format                      : AC-3
Format/Info                 : Audio Coding 3
Codec ID                    : A_AC3
Duration                    : 2 h 4 min
Bit rate mode               : Constant
Bit rate                    : 640 kb/s
Channel(s)                  : 6 channels
Channel positions           : Front: L C R, Side: L R, LFE
Sampling rate               : 48.0 kHz
Frame rate                  : 31.250 FPS (1536 SPF)
Bit depth                   : 16 bits
Compression mode            : Lossy
Stream size                 : 571 MiB (4%)
Title                       : Ac3 5.1@640 kbps (DTS Blu Ray)
Language                    : Spanish
Service kind                : Complete Main
Default                     : Yes
Forced                      : Yes

Audio #2
ID                          : 3
Format                      : DTS
Format/Info                 : Digital Theater Systems
Codec ID                    : A_DTS
Duration                    : 2 h 4 min
Bit rate mode               : Constant
Bit rate                    : 768 kb/s
Channel(s)                  : 6 channels
Channel positions           : Front: L C R, Side: L R, LFE
Sampling rate               : 48.0 kHz
Frame rate                  : 93.750 FPS (512 SPF)
Bit depth                   : 24 bits
Compression mode            : Lossy
Stream size                 : 685 MiB (5%)
Title                       : DTS 5.1@768 kbps (Blu Ray)
Language                    : Spanish
Default                     : No
Forced                      : No

Audio #3
ID                          : 4
Format                      : AC-3
Format/Info                 : Audio Coding 3
Codec ID                    : A_AC3
Duration                    : 2 h 4 min
Bit rate mode               : Constant
Bit rate                    : 640 kb/s
Channel(s)                  : 6 channels
Channel positions           : Front: L C R, Side: L R, LFE
Sampling rate               : 48.0 kHz
Frame rate                  : 31.250 FPS (1536 SPF)
Bit depth                   : 16 bits
Compression mode            : Lossy
Stream size                 : 571 MiB (4%)
Title                       : Ac3 5.1@640 kbps (DTS-HD Blu Ray)
Language                    : English
Service kind                : Complete Main
Default                     : No
Forced                      : No

Text #1
ID                          : 5
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Title                       : Forzados
Language                    : Spanish
Default                     : Yes
Forced                      : Yes

Text #2
ID                          : 6
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Title                       : Completos
Language                    : Spanish
Default                     : No
Forced                      : No

Text #3
ID                          : 7
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Title                       : Forzados
Language                    : English
Default                     : No
Forced                      : No

Text #4
ID                          : 8
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Title                       : Completos
Language                    : English
Default                     : No
Forced                      : No

Text #5
ID                          : 9
Format                      : PGS
Muxing mode                 : zlib
Codec ID                    : S_HDMV/PGS
Codec ID/Info               : Picture based subtitle format used on BDs/HD-DVDs
Title                       : Forzados&Completos (.sup)
Language                    : Spanish
Default                     : No
Forced                      : No

Text #6
ID                          : 10
Format                      : PGS
Muxing mode                 : zlib
Codec ID                    : S_HDMV/PGS
Codec ID/Info               : Picture based subtitle format used on BDs/HD-DVDs
Title                       : Forzados (.sup)
Language                    : English
Default                     : No
Forced                      : No

Text #7
ID                          : 11
Format                      : PGS
Muxing mode                 : zlib
Codec ID                    : S_HDMV/PGS
Codec ID/Info               : Picture based subtitle format used on BDs/HD-DVDs
Title                       : Completos (.sup)
Language                    : English
Default                     : No
Forced                      : No

**Comment by ctsdownloads** [comment]
Unreproducible, old version of OpenShot
