### ISSUE TITLE
Crash on rendering start

### ISSUE THREAD

**Issue by dnewcomb** [OpenShot/openshot-qt#2021]
Program crashes as soon as I start rendering .

System Info
Ubuntu 18.04.1 64 bit
Intel Xeon 6 core x2
44GB RAM

OpenShot version
OpenShot-v2.4.2-dev1-1534503451-1989b09c-554d9f2f-x86_64.AppImage

**To Reproduce**
1.Load MP4 Video
2. Click on Red rendering button
3. Set directory for project and project name
4. See error at end of command string below
[terminal output.txt](https://github.com/OpenShot/openshot-qt/files/2312628/terminal.output.txt)

**Expected behavior**
Expected to render video.  Instead, program crashes and disappears. Very short rendered file.

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**

**Comment by dnewcomb** [comment]
Added the daily ppa and crashed in the same place. File attached.  Will remove adn try the stable ppa.
[daily_ppa_08232018.txt](https://github.com/OpenShot/openshot-qt/files/2316377/daily_ppa_08232018.txt)

Running again using the stable ppa, crash in same place.
[stable_ppa_08232018.txt](https://github.com/OpenShot/openshot-qt/files/2316406/stable_ppa_08232018.txt)

Creating a fresh .openshot_qt in my home directory still crashed in the same place

**Comment by DylanC** [comment]
@dnewcomb - Try v2.4.3 and let us know if you still have a problem.

**Comment by dnewcomb** [comment]
Sorry to check in so late, but it's working well for me. Your fixes enabled
me to complete at video editing job for my church.  Thanks!

Doug

**Comment by DylanC** [comment]
@dnewcomb - Great to hear. Thanks! :+1:
