### ISSUE TITLE
put a text in the video

### ISSUE THREAD

**Issue by smack2005** [OpenShot/openshot-qt#2025]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by smack2005** [comment]
can I add a text and a drawing in the video that appears at a given second and disappears a while later?
the title function overlaps and obscures the video, I do not want this effect
thank you

**Comment by DylanC** [comment]
@smack2005 - Add an image with a fade in and fade out. The image you create should have your text placed on it in the desired location of course.
