### ISSUE TITLE
audio fade out not matching timeline

### ISSUE THREAD

**Issue by sartyx** [OpenShot/openshot-qt#2026]
For some reason an additional audio track is not fading way too early when exporting to 3840*1920.
Seems to work in lower resolutions, at least closer to what it should be.

Anyway the program is still great work, considering that Davinci Resolve can´t handle the 4K and 5K videos on my system but OpenShot does without any complains.

**Comment by JimbobTheSailor** [comment]
This is and bug #2037  are both specific instances of a general bug. See my comments in #2037 . I too am reporting this bug
