### ISSUE TITLE
Win10 won't let save or export my finished video. I allowed launch.exe to change files, but it still won't save my export.

### ISSUE THREAD

**Issue by rnale** [OpenShot/openshot-qt#2027]
**Describe the bug**

**System Details (please complete the following information):**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**

**Comment by rnale** [comment]
![capture](https://user-images.githubusercontent.com/42679721/44601834-9c0d9600-a792-11e8-9dc0-ebc90da85560.PNG)

**Comment by DylanC** [comment]
@rnale - This is an issue with Windows 10 and not Openshot. Please contact someone with Windows 10 knowledge. Thanks.
