### ISSUE TITLE
still can't animate a title (Windows 10)

### ISSUE THREAD

**Issue by anderm8** [OpenShot/openshot-qt#2028]
windows 10
blender 2.79
OpenShot 2.42

I checked the scripts and the have the text_object.activate_x already
I ran a few of the scripts from the command line and they failed as expected because they did not get any parameters.

From OpenShot, of the title animations that I tried from the command line, a command window pops open once or twice then disappears - which means that Blender is getting launched. I then get the "You must have Blender.... installed, check your path message. But the path is correct. If I change a character in the path, I get NO command window pop-ups with that same message.

**Comment by anderm8** [comment]
clarification: I was following: https://github.com/OpenShot/openshot-qt/wiki/How-to-troubleshoot-errors-with-animated-titles 

I think there is a typo as to the log file name/location. But for me, I could not find any log files to examine as the folder does not exist.

**Comment by DylanC** [comment]
I put in a change to have browse buttons in future. This will work better in newer releases:
https://github.com/OpenShot/openshot-qt/pull/2255
