### ISSUE TITLE
OpenShot X Window System error

### ISSUE THREAD

**Issue by Xplosive** [OpenShot/openshot-qt#203]
The program (OpenShot 1.4.3) was crashed (closed unexpectedly) today with these errors on my Computer:

![screenshot from 2016-05-23 15-25-07](https://cloud.githubusercontent.com/assets/19533756/15473637/4ca0505e-2101-11e6-9e9a-625217b3896d.png)
![screenshot from 2016-05-23 16-10-32](https://cloud.githubusercontent.com/assets/19533756/15473638/4ca6a9cc-2101-11e6-85c9-afef41f02a6f.png)

"The program 'openshot' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 38830234 error_code 2 request_code 139 minor_code 4)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Segmentation fault (core dumped)
xplosive@hp-compaq-dc5850-small-form-factor:~$"

PC Specs:
HP Compaq dc5850 SFF:
CPU: AMD Athlon(tm) Dual Core Processor 5000B × 2
RAM: 4 GB
VGA: AMD Radeon HD 6450 (Gallium 0.4 on AMD CAICOS (DRM 2.43.0, LLVM 3.8.0)
HDD: Hitachi HDS721016CLA382 (JPEOA3EA) (160 GB)
OS: I am using Ubuntu Linux 16.04 LTS 64-bit at the moment. (Original OS: Windows Vista Business, but currently not installed.)

**Comment by ankitpati** [comment]
Can you please verify that the issue still persists in the latest stable [AppImage](http://github.com/OpenShot/openshot-qt/releases/download/v2.2.0/OpenShot-v2.2.0-x86_64.AppImage "OpenShot 2.2")?

If not, we can close this issue as fixed.

As an aside, I regularly use OpenShot 1.4.3 on Ubuntu 16.04, and I am yet to experience this issue. Chances are that a conflicting software installed on your machine may have caused this. Either way, the OpenShot Project has no control over what distros package in their repositories, and as such cannot fix the bug in the Ubuntu package of OpenShot even if we identify it.

**Comment by DylanC** [comment]
Closing since this issue relates to the 1.4.x series. Focus is on v2.x series.
