### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by Linus50** [OpenShot/openshot-qt#2032]
**My Question:**How can I fix the problem shown in the file attached?

System : Windows 8.1, 
 - OpenShot Version : 2.4.2
**Screenshots**
![openshot launch exe](https://user-images.githubusercontent.com/26854168/44627438-656c8280-a92e-11e8-83d2-715cfd02ad65.jpg)

**Comment by ShakeDash** [comment]
even I am facing the same problem
hope they give a fix soon 
![capture](https://user-images.githubusercontent.com/42928771/44974021-118c1a00-af7c-11e8-8b92-e82a1d187a04.PNG)

**Comment by ferdnyc** [comment]
I'm going to close this in favor of the more detailed #2748, for OpenShot 2.4.4.
