### ISSUE TITLE
How to fix launch.exe has stopped working 

### ISSUE THREAD

**Issue by Jean45** [OpenShot/openshot-qt#2033]
I need help fixing this before my project due in 2 days. When I preview my video, launch.exe has stopped working keep popping up. I had reinstall openshot and restart my pc. But still it won't work

**System Details**
 - Window 8.1
 - OpenShot Version [e.g. 2.4.2]

![screenshot 1](https://user-images.githubusercontent.com/42715003/44628418-46e99580-a8f4-11e8-8aa1-700412e17262.png)

**Comment by DylanC** [comment]
@Jean45  Try v2.4.3 and let us know if you still have a problem.

**Comment by mikelacsa** [comment]
@Jean45 are you still experiencing this issue using the new version?

**Comment by ferdnyc** [comment]
No response in... forever, closing.
