### ISSUE TITLE
Extend timeline past 6 minutes?

### ISSUE THREAD

**Issue by kingttx** [OpenShot/openshot-qt#2034]
**My Question:**
Before I upgraded Ubuntu, my older Openshot version worked great. With 2.4.2, I cannot get the timeline to auto-extend past 6 minutes. Dragging a video onto the track past 6 minutes makes Openshot freeze up. CPU usage spikes to almost 800% for openstack-qt when viewed in 'top'. 

Is there a trick to get Openshot's timeline to extend further than 6 minutes?

**System Details**
 - Operating System / Distro: Ubuntu 18.04.1
 - OpenShot Version 2.4.2

**Screenshots**
![screenshot from 2018-08-26 11-23-46](https://user-images.githubusercontent.com/37450238/44630956-8e871600-a922-11e8-97f9-f968aa4679b0.png)

**Comment by DylanC** [comment]
@kingttx  Try v2.4.3 and let us know if you still have a problem.

**Comment by kingttx** [comment]
Only 2.4.1 is in the Bionic PPA. Should I grab it from here?
http://ppa.launchpad.net/openshot.developers/ppa/ubuntu/pool/main/o/openshot-qt/

Tom

**Comment by DylanC** [comment]
@kingttx - I can see from your link it has v2.4.3. Maybe fully uninstall and then install v2.4.3 from PPA.
