### ISSUE TITLE
How to change the direction of clips/reverse them?

### ISSUE THREAD

**Issue by blop43** [OpenShot/openshot-qt#2036]
**My Question:**
I saw some old tutorials telling me to right click and select 'Properties' and there should be something I can change there to do this, however they seem to be outdated. How can I change the direction of videos using OpenShot?

**System Details**
 - Operating System / Distro: [Linux Ubuntu 18.04]
 - OpenShot Version [2.4.1]

**Comment by blop43** [comment]
Sorry! Ten minutes after I wrote this I found a solution! D:

**Comment by DylanC** [comment]
@blop43 - No problem. :)

**Comment by ssnowman62** [comment]
How did you do it?

**Comment by peanutbutterandcrackers** [comment]
@ssnowman62 - Right click on the clip in the timeline. Time > Normal > Backward > 1X. Hope that helps. Closing this as answered.
