### ISSUE TITLE
Export in HD720p 50fps with fade generates blank video/breaks fade

### ISSUE THREAD

**Issue by rob0d** [OpenShot/openshot-qt#2037]
I've got a simple project. I have two MP4 (1280x720/H264/AC3/50fps) files that I want to join into one file with a fast fade in/out. It all looks as I want in the preview. I want to just export it with minimal conversion.

When I select MP4(h.264) HD 720p 50fps format it generates a file without problems, however the video disappears approximately after 20 seconds. 
When I select any other fps or other format it generates file with video correctly but the fade at the end of first file starts a lot sooner and before and after every fade the video flashes. 
When I remove the fade in/out it the video is fine (but there are still flashes in it).

To me it seems like a bug. I'm not sure if these are two separate bugs or the same.
I'm using the latest Openshot installed via PPA on fully up-to-date Ubuntu 16.04.

**Comment by JimbobTheSailor** [comment]
I am have the same issue. This is a symptom of a broader issue. A number of effects are not synchronising to the timeline, but alter their duration according to the frame rate. For example. If I use the animation effect scroll from bottom to top on a png file whose timeline is 20seconds. In the preview using the scrubber the image scrolls nicely across the full twenty seconds. However, if I export the video at 60fps, then the entire effect completes in 7 seconds, leaving 13 seconds of blank video. If I do nothing except now export at 30fps, then the entire effect completes in 14 seconds, leaving 6 seconds of blank video. If I export at 25fps, then the entire effect completes in 17 seconds.  This is exactly the same problem with fade as noted by the author above. If I set a fade for say 10 seconds, it all works in the scrubber but its actual time that it executes for varies with the exported frame rate. The faster the framerate, the faster the effect happens. Note that the underlying video clip does not alter when the framerate is changed. It still plays correctly. It is only the duration of the effects that alter by frame rate. It seems that the code is incorrectly calculating the time to apply an effect as a function of framerate. This is a BIG PROBLEM everything is rendered differently when the frame rate is changed
