### ISSUE TITLE
Very Big Component on lower res screen

### ISSUE THREAD

**Issue by adyoi** [OpenShot/openshot-qt#2038]
![osv](https://user-images.githubusercontent.com/6408640/44704113-620aff80-aac4-11e8-8d4b-ef6d8adc8b45.png)

my laptop resolution is 1366 x 768 looks like tightness 😄

**Comment by peanutbutterandcrackers** [comment]
Note to self: https://github.com/ferdnyc/openshot-qt/tree/dockable-timeline might be on to something.

@adyoi - Do you have any ideas as to how this could have looked better, good sir?
