### ISSUE TITLE
http://www.openshot.org/ website suggestions

### ISSUE THREAD

**Issue by ovari** [OpenShot/openshot-qt#204]
1. Add cross-platform
   [Home](http://www.openshot.org/) tab, “Simple. Powerful.” section, description reads:
   “OpenShot Video Editor is a free, open-source video editor for Linux licensed under the GPL version 3.0.”
   suggested to update to:
   “OpenShot Video Editor is a free, [open-source](https://en.wikipedia.org/wiki/Open-source_software), **cross-platform (supports Linux, OS X and Windows)** video editor licensed under the [GPL version 3.0](https://en.wikipedia.org/wiki/GNU_General_Public_License).”
2. Typo “platoform”
   [Features](http://www.openshot.org/features/) tab, a dot point reads:
   “Cross-**platoform** (**S**upports Linux, OS X**,** and Windows)”
   suggested to update to:
   “Cross-platform (supports Linux, OS X and Windows)”
3. Run spelling and grammar checker
   There are other small errors on your website that can be found using a spelling and grammar checker.

Suggestions in boldface.

Thank you for your wonderful program.

**Comment by jreynojustin** [comment]
Thank you for the feedback but this only pertains to issues for the applications integrity itself.
