### ISSUE TITLE
File conflicts aren't checked properly after opening saved project (ASSETS_PATH is constant)

### ISSUE THREAD

**Issue by DerGenaue** [OpenShot/openshot-qt#2041]
**Describe the bug**

Openshot has an internal constant `info.ASSETS_PATH`, which always points to the users home-directory to a temp location for assets.
This temp location is used for saving eg. titles when they are created.
This temp-location also is used to check for conflicts when saving or creating titles.  
**However**  
After saving, all the asset-files are moved to a local assets-folder directly next to the project save.
This makes all the conflict-checks break after saving, since they only check the static location, but not the local one

**Steps to reproduce**
 1. New Project
 2. Create Title `<name>-1`
 3. Create Title `<name>-2`
 4. Duplicate Title `<name>-1`
   ->The file name is correctly increased to `<name>-3` since `<name>-2` already exists
   ->Trying to save as `<name>-2` will correctly trigger a prompt whether to overwrite the other file
 7. Save and re-open project
 8. Retry 4. : it will not work as intended

**Expected behavior**
As soon as a save has been performed, the `ASSETS_PATH` should point to the local folder so that conflicts are checked correctly and no project files are overridden accidentally.
All newly created files should be created directly in this local folder.

**Attention**
More discussion might be needed; since this does not fix that assets of an already existing project might be overwritten when saving another project in the same location for the first time.

This is one of the underlying issues of #2004

**Comment by ctsdownloads** [comment]
Merged, see above.
