### ISSUE TITLE
OpenShot  won't open - cx_Freeze Python error in main script

### ISSUE THREAD

**Issue by ToyBonnieGirl** [OpenShot/openshot-qt#2043]
**Describe the bug**

**System Details (please complete the following information):
Windows 7
unknown i cannot open it to check
![image](https://user-images.githubusercontent.com/28080143/44761638-d8821e80-ab11-11e8-97ae-0c967fe2aa4b.png)

**Comment by ToyBonnieGirl** [comment]
i actually need this fixed soon unfortunately, this is the only editing program i've ever used and i need to edit some footage i have ready for some videos

**Comment by realfasix** [comment]
i have uninstalled v2.4.1, deleted .openshot_qt folder and c:\program files\OpenShot Video Editor folder
installed v2.4.2 and nothing changed... so...
uninstalled v2.4.1, deleted the above 2 folders, updated python to 3.7.0 (just in case)
installed yesterday daily build and nothing change.

**Comment by maxdevfud** [comment]
Windows 32 bit error on opening OpenShot:

![image](https://user-images.githubusercontent.com/3717458/44899807-17c39180-ad03-11e8-81d3-88b9b9856de4.png)

**Comment by OgreMHDW** [comment]
Same for me. Running v2.4.2 with Windows 10 64-bit. 

![image](https://user-images.githubusercontent.com/4369476/44950184-58500780-adf6-11e8-9c30-ca61e7db0119.png)

**Comment by Smartheads** [comment]
I'm getting the same issue. I tried doing what @peanutbutterandcrackers said, but that didn't help. 2.4.1 worked fine. Shouldn't have upgraded...
Windows 10 Home Edition 64bit
