### ISSUE TITLE
Crash on export 

### ISSUE THREAD

**Issue by NicoThum** [OpenShot/openshot-qt#2044]
Hello,
Openshot crash on export wathever the profile selected, no error message, just shutdown of the soft ,;(

I run the latest version of the soft, i use windows 10.
I need your help please :)

**Comment by noobnoob316** [comment]
I have the exact same problem and it takes up to 10 - 15 tries to export a video..

**Comment by MarsCandidate** [comment]
I feel you. Apparently my laptop decides to crash countless times, especially when trying to export a video. In the end it does not happen, and all my time has gone down the drain. Which is fine; no, I am not upset at the developers; yet I am trying to seek counsel.

**Comment by cdefy** [comment]
Hi,

Same here, crash after 6.2% of exporting, no matter what. It was working just fine before the last update.
I tried to install an old version without success.
I reinstalled OpenShot... Bad idea, the export button doesn't react any more! :-(

Hope it will be fixed soon, I needed a video for the end of the week :-s

Thanks for the work anyway, it's an awesome free open source software!

**Comment by cdefy** [comment]
@MarsCandidate : I found it [here](https://www.videohelp.com/software/OpenShot-Video-Editor/old-versions). I tried the 2.3.4 but it didn't launch. I can't remember which version I had before doing the update a few days ago. :-(

**Comment by peanutbutterandcrackers** [comment]
Hey everyone,

Sorry for the inconvenience.

OpenShot, while an amazing Video Editing Software with awesome keyframe-prowess and all, is still a diamond in the rough and needs quite a lot of stabilizations...

Please [attach the logs](https://gist.github.com/peanutbutterandcrackers/b188841d1ed3a91a88b457b88caf9566); that will help the devs figure out the root of this issue.

Please do be patient with this [Free Software](https://en.wikipedia.org/wiki/Free_software) gem. It'll only get better with time.

**Comment by cdefy** [comment]
@peanutbutterandcrackers : no worries at all! Just trying to figure a way around for me because I need to export a video before the end of the week, that's why I wanted to downgrade in the mean time.
I'll try with the link you gave [here](https://github.com/OpenShot/openshot-qt/issues/2013#issuecomment-417184137).

Keep on the good work! ;-)

**Comment by MarsCandidate** [comment]
Well I've accidentally figured out a fix to this @cdefy @peanutbutterandcrackers @NicoThum @noobnoob316 @Gelma this happened when I was trying to figure out how to attach my logs. It worked for me, but I do not know weather it would work for the rest of you, but I would just try it out; open File Explorer, click on "This PC", click on your search box and then type ".openshot_qt" (without adding the quotations) and click on the folder. Look at the very bottom, and delete every .log file that you see, once again, located at the very bottom. Afterwards, open OpenShot right away, and try exporting again. It worked for me, but for the rest of you I am not so sure.

**Comment by cdefy** [comment]
So I redo my project, try to export it half way, it works. Finish it (1:30mn only), try to export... and crashes again.

So I clear the logs, reopen it, got that new error message 'NoneType' object has no attribute 'get'.
Try to export, crash. @peanutbutterandcrackers I attached the logs this time.

[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/2338376/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2338377/openshot-qt.log)

PS.: can I ask you why and what exactly you're sending to Google Analytics?

**Comment by MarsCandidate** [comment]
Congratulations! :)

**Comment by alan06200** [comment]
Same problem : crash when I export whith the last version 2.4.2 on windows 10

**Comment by cdefy** [comment]
@alan06200 Did you try with the last daily build? On the Download page of the official website, under "Looking for a different download?", click on Daily Builds to display them.

**Comment by alan06200** [comment]
No I haven't ... Today I export 2 clips one with transition between us and 1 without . I do this 3or 4 exports whith the same exportation. Always these whith transition crash ....The other no ......!

I try to download the Daily Builds. Thanks cdefy

**Comment by alan06200** [comment]
I have instal the last Daily Buids and ...... same crash, but it seem that I understand where is the problem 👍 When my video has 1 or 2 transitions , openshot crash...when i remove the transition ( 2clip video) ,openshot export whith no problem....

**Comment by DylanC** [comment]
@NicoThum @noobnoob316 @MarsCandidate @cdefy - This transitions bug has been fixed. See #2125.

**Comment by peanutbutterandcrackers** [comment]
@cdefy - Hey there. Sorry I wasn't around much. Thank you for your willingness to help. I'll put this issue on my list for future reference for all the other ones you've linked and the investigations that you have done. I'm glad that this seems to have been resolved for now, as well. Hope you create awesome videos using OpenShot.
