### ISSUE TITLE
launch.exe crashes after loading clip from older equipment

### ISSUE THREAD

**Issue by OlliEliotD** [OpenShot/openshot-qt#2045]
I'm using windows7 and am new to this software. When I load in video from an older camera (vivitar dvr 498) the program crashes. Error says "launch.exe" has crashed.

Video from my Nikon and iPhone loads fine, it's just the video and sound from the older camera. As well, before it crashes, green bars occur on the bottom of the video images.

**Comment by DylanC** [comment]
@OlliEliotD - Try v2.4.3 and let us know if you still have a problem.

**Comment by OlliEliotD** [comment]
Hi,

I actually switched to a different program because I couldn’t get it to work. I’m sorry. 

Oliver Daniels
