### ISSUE TITLE
Text/PNG Pictures desyncing

### ISSUE THREAD

**Issue by lung9** [OpenShot/openshot-qt#2048]
**Describe the bug**
For no apparent reason Text/PNG Pictures in the rendered Video arent aligning with what is seen in the Video Preview

**System Details:**
OS: Windows 10 Home Edition
 - OpenShot Version 2.4.2

**To Reproduce**
I am actually not sure how to reproduce but i think you have to change the position of the image frequently without any real breaks.

**Expected behavior**
Rendered video aligning with the video preview

**Video**
Comparison of Render and Video preview:
https://youtu.be/ySsje9aqC8A

**Comment by peanutbutterandcrackers** [comment]
Hmm, this is interesting. I thought the audio was the only thing that kept desyncing.

@N3WWN - Any ideas on this one, good sir?
