### ISSUE TITLE
How do I add layers

### ISSUE THREAD

**Issue by Jackrussellrocky** [OpenShot/openshot-qt#205]
Hi All,

I am new to openshot.

How do I add layers please.

Thank you , for your support..

**Comment by Kissaki** [comment]
You mean a track?
![image](https://cloud.githubusercontent.com/assets/93181/15646112/4d793896-265c-11e6-9af9-0825cd5405cb.png)
A track works as a "layer".

**Comment by Jackrussellrocky** [comment]
Thank you,

My main problems are crashing and jerky playback.

I am using windows 10 PLEASE HELP URGENTLY..

**Comment by Kagetsuki** [comment]
@Jackrussellrocky bug reports and detailed system specs could help. Also, please close this issue as your initial question was resolved. If you have any other problems please open up an issue with as many details as you can.

**Comment by Jackrussellrocky** [comment]
Hi,

It was not resolved?

**Comment by Kagetsuki** [comment]
@Jackrussellrocky The only people who can close the issue are you and @jonoomph . Since @jonoomph is obviously quite busy working on code and other issues it would be a nice courtesy if you could close the issue.

**Comment by Jackrussellrocky** [comment]
Why would i close an unresolved issue?

**Comment by Kagetsuki** [comment]
@Jackrussellrocky your issue was about adding tracks, which @Kissaki informed you of how to do. If you are having an issue with a bug or performance those belong in different issue tickets and details should be provided.
