### ISSUE TITLE
When I try to save edited video, displayed bug on right side

### ISSUE THREAD

**Issue by em454** [OpenShot/openshot-qt#2050]
**Describe the bug**

**System Details (please complete the following information):**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**To Reproduce**

**Expected behavior**

**Screenshots**
![image 1](https://user-images.githubusercontent.com/42860888/44899338-69d4d900-ad3c-11e8-8793-13ed09c28441.png)

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**

**Comment by peanutbutterandcrackers** [comment]
Closing in favour of #2053 as that issue provides more detail. Please follow the discussion over there. Thanks.
