### ISSUE TITLE
openshot tries to load a project with old file from a previous  project

### ISSUE THREAD

**Issue by bobcrikey** [OpenShot/openshot-qt#2052]
hello everyone, tonight i tried to load an older project i done last week, however 
i got so many error messages for files that was not in the actual project i had done

have a look at this 

![non existant file](https://user-images.githubusercontent.com/40479177/44944337-47b08900-ae18-11e8-9986-f2ca50ea6f41.png)

I believe it to be a bug.
I had used those particular files in a temp project and had made a video from a image sequence and just exported
the video without saving the project.

dylynC do you have any ideas about this one.? as this is not the first time iv seen this bug.
cheers
 bob

**Comment by ctsdownloads** [comment]
Unreproducible, old version of OpenShot
