### ISSUE TITLE
Flickering on the right side of the video

### ISSUE THREAD

**Issue by KidsDontPlay** [OpenShot/openshot-qt#2053]
**Describe the bug**
A flickering appears on the right edge of the screen in the video preview and the rendered video.

**System Details (please complete the following information):**
 - OpenShot 2.4.2
 - Linux Mint (4.13.0-25-generic # 29~16.04.2-Ubuntu SMP Tue Jan 9 12:16:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux)

**To Reproduce**
 - open a new project with profile HDV 720 24p
 - add a video to the track (video details in screenshots)

**Expected behavior**
No flickering

**Screenshots**
 - https://i.imgur.com/cul27M3.mp4
 - ![settings](https://user-images.githubusercontent.com/13290261/44949983-0088bf00-ae3d-11e8-92d5-4862330bb37c.png)

**Additional context**
 - this is a duplicate to #2050. I decided to create a new one because the other one doesn't provide enough information
 - said video [file](https://cdn.discordapp.com/attachments/397045596239953932/485560412771713035/mine.mp4)
 - EDIT: [here](https://drive.google.com/open?id=1hzgOO50j--Jb76zG22zRADJqs3fCGVJn) is the same video without any flickering problems

**Comment by DylanC** [comment]
@MrRiegel  Try v2.4.3 and let us know if you still have a problem.

**Comment by peanutbutterandcrackers** [comment]
I'm going to close #2050 in favour of this. And I'm going add my own example file here. I ran into the same issue this morning while trying to reverse the attached webm (that I got from 9gag) for testing. I was using the default profile.


[Issue #2053.zip](https://github.com/OpenShot/openshot-qt/files/2682488/Issue.2053.zip)

**Comment by julienaubert** [comment]
Thanks to everyone for this app. It is great!

I have this issue too. Tested in 2.4.3.

I tried just adding an image - then it works fine (no flicker on export). However, adding a video, with default settings, I get flicker or black on right side too. 

Example video: 
[Untitled 5.mov.zip](https://github.com/OpenShot/openshot-qt/files/2705528/Untitled.5.mov.zip)

Export options are the default, except I have set w/h to same resolution as the above movie:
<img width="448" alt="screenshot 2018-12-22 at 21 56 03" src="https://user-images.githubusercontent.com/1526239/50378520-7c995380-0634-11e9-97c5-19d8f7d55ec1.png">

And the resulting export shows a black vertical line on the right. It is as if it is not writing the last pixels on each row from the source?
[Untitled Project.mp4.zip](https://github.com/OpenShot/openshot-qt/files/2705534/Untitled.Project.mp4.zip)

**Comment by schauveau** [comment]
I see it too and I think that this is a bug in the FFmpeg reader (or in libswscale) when the width of the video is not a multiple of 8. Here is a small program I made to test the behavior. 
[test1.cc.gz](https://github.com/OpenShot/openshot-qt/files/2963604/test1.cc.gz)
You can change the values of NX (the image size) and STRIDE_OUT (a stride added to each output line) and see how the sws_scale function is behaving during a conversion from YUV420P to RGBA
What I am observing is that the pixels are always converted in batches of 8 pixels (probably because of vectorised code). Try for instance NX=21 and STRIDE_OUT=0. Only 16 pixels are converted per row. 
In libopenshot, the output image RGBA has no stride which means that the last `mod(width,8)` pixels are not converted and since data allocated by av_alloc is not cleared we get random value (usually pixels from previous frames).
Note: I think that FFMpegReader could allocate its image with av_image_alloc and align=8.

**Comment by schauveau** [comment]
The small test program in my previous comment should be compiled with something like
``` g++ test1.cc $(pkg-config --cflags --libs libswscale libavutil) ```

**Comment by StarDust19** [comment]
Please somebody comment how to actually solve it! The comments so far are either confusing or just simply like "yeah, it's a problem with me 2 lol".

**Comment by schauveau** [comment]
I do not know if my previous comment was confusing (yeah ... probably. That was more a comment for that devs than for users) but if I was right then a workaround could be to always use videos with a width that is a multiple of 8. For example, in the 2 screenshots posted previously, the videos have a width of 750 (=8*93+6) and 854 (=8*106+6) thus causing the last 6 pixels to become random.
If you have ffmpeg installed then you could try one of the following commands to 'fix' the width of the problematic videos:
```
# use the pad filter to add borders on both sides to keep the video centered
ffmpeg -i  input.mp4 -vf "pad=w='8*ceil(iw/8)':x='(ow-iw)/2':color=black" output.mp4
# use the pad filter to add a single border on the right side  
ffmpeg -i  input.mp4 -vf "pad=w='8*ceil(iw/8)':x='0':color=black" output.mp4
# use the crop filter to remove a few pixels on both sides.  
ffmpeg -i input.mp4  -vf "crop=w='8*floor(iw/8)':x='(iw-ow)/2'" output.mp4
```
In the previous commands, `iw` and `ow` are respectively the input width and the output width of the video and you can of course replace `black` by your preferred border color (e.g. `gray`, `#FF0000`, ...)    
PS: the documentation for the ffmpeg filters can be found in https://ffmpeg.org/ffmpeg-filters.html
PPS: you may also want to pass other options to ffmpeg for example to control the re-encoding quality.

**Comment by olissongs** [comment]
Tested it in OpenShot 2.4.4 Ubuntu 18.04

same Problem.


Tested the fmpeg commands, they have no effect.

any other Solutions?

Testing it in KDEenlive, it runs out of the box. thats my workaround. Not happy not using my prefered app openshot

**Comment by tomjridge** [comment]
Just to say that I also have this problem

**Comment by didnthodl** [comment]
Tested on version 2.5.0-dev1 and ffmpeg to version 3.4.6-0 on Ubuntu0.18.04.1.
I get this exporting a video with 1280x720, which is divisible by 8.
Still same problem with the flickering
Kdenlive works fine, though

**Comment by ferdnyc** [comment]
> I get this exporting a video with 1280x720, which is divisible by 8.

That isn't really the involved factor, though, it's a question of your **input** video's properties (dimensions and aspect ratio, primarily), along with any scaling or transformations on the Timeline.

The video noise is "attached to" (for lack of a better term) the imported video clip. And it can usually be worked around in OpenShot by scaling the video clip slightly larger than the output profile, so that the corrupted pixels are pushed offscreen.

**Comment by didnthodl** [comment]
> > I get this exporting a video with 1280x720, which is divisible by 8.
> 
> That isn't really the involved factor, though, it's a question of your **input** video's properties (dimensions and aspect ratio, primarily), along with any scaling or transformations on the Timeline.

Wow, that was a quick solution. Thanks for the clarification! It works if the width of my input video is divisible by 8. That's actually a fairly easy thing for me to do. I was already reading tutorials on how to use Kdenlive...

Thanks so much!

**Comment by rarsa69** [comment]
Thank's for the explanation. I had found out that displacing the X location between 0.001 and 0.005 resolved the problem. I thought it was just a hacky way to solve it but with the explanation, it is clear that it's a good way to remove the noise.

**Comment by bfallc** [comment]
Coming across this issue today, you can also set x-crop to something like 0.98, to slice off the corrupted edge.

**Comment by Talkashie** [comment]
I am also having this issue on 2.5.1, Windows 10. Is this issue being looked into?

**Comment by JacksonRG** [comment]
@Talkashie Could you include any videos or logs to show how this issue shows up for you?

**Comment by jytou** [comment]
I am also experiencing this. And the version 2.6.1 has so many problems that I need to revert to 2.5.1. But this cropping problem makes it unusable for some videos.

**Comment by SamiSieranoja** [comment]
I'm still experiencing this, in OpenShot-v3.4.0.

**Comment by Colorjet3** [comment]
Hello @SamiSieranoja 

Please provide the following:
1.  What operating system/version you are running (Windows 10? Ubuntu 25.10? etc?)
2.  What type of a file are you working with (.mov? .mp4? etc?).
3.  What Profile is your imported file?
4.  What is the Default Profile of your project?
5.  Are you willing to share your file so we can test with it?
6.  Does this happen with this file only or other files also?
7.  Have you tried converting your file using something like VLC, ShutterEncoder, or Handbrake and create a new Newfilename.mp4 file, then import this into OpenShot and see what happens?

Also, have you tried the latest dev daily build?  Try step 7 first before you try the dev daily build.  Then, go to openshot.org/download/#daily and get the latest dev daily build available and import your source file (not the one you ran through a converter) to test first.

**Comment by DarkTyger** [comment]
> What operating system/version you are running (Windows 10? Ubuntu 25.10? etc?)

Arch Linux, Kernel 7.1.8-arch1-3.

> What type of a file are you working with (.mov? .mp4? etc?).

Exporting to mkv or mp4. Input source is mkv, captured using:

``` bash
#!/usr/bin/env bash
EXIT_CODE=1

if [[ "${1:-}" == "--output" && -n "${2:-}" ]]; then
  mkdir -p "$(dirname "$2")"
  echo "Waiting ..."
  sleep 3

  eval "$(xdotool getwindowgeometry --shell "$(xdotool getactivewindow)")"

  if [[ -n "${WIDTH:-}" && "$WIDTH" -gt 10 ]]; then
    # libx264 + yuv420p requires even dimensions; drop the odd pixel.
    WIDTH=$(( WIDTH - WIDTH % 2 ))
    HEIGHT=$(( HEIGHT - HEIGHT % 2 ))

    # One raw BGR0 frame is WIDTH*HEIGHT*4 bytes, which exceeds the 5 MB
    # default probesize, so ffmpeg only sees a single frame and can't
    # estimate the rate. Give it room for a few frames.
    PROBESIZE=$(( WIDTH * HEIGHT * 4 * 4 ))

    echo "Recording ..."

    # nice + 2 encoder threads keeps ffmpeg from starving Firefox's JS.
    nice -n 15 ffmpeg -y -hide_banner -loglevel warning \
      -f x11grab -framerate 30 -probesize "$PROBESIZE" \
      -video_size "${WIDTH}x${HEIGHT}" -i "${DISPLAY:-:0.0}+${X},${Y}" \
      -c:v libx264 -preset ultrafast -tune zerolatency -crf 15 \
      -threads 2 -pix_fmt yuv420p "$2"

    EXIT_CODE=$?
  fi
fi

exit $EXIT_CODE
```

> What Profile is your imported file?

2.5K WQHD 1440p 30 fps (it didn't really matter, various profiles did the same thing).

> Have you tried converting your file using something like VLC, ShutterEncoder, or Handbrake and create a new Newfilename.mp4 file, then import this into OpenShot and see what happens?

No. Probably not relevant. Likely the input video size.

> Also, have you tried the latest dev daily build? 

**OpenShot Version Info**
Version: 4.0.0 | libopenshot: 1.0.0
Build: OpenShot-v4.0.0-release-candidate-16756-732f1829-56930c67 | Released: 2026-08-27
OS: Arch Linux
CPU: AMD Ryzen 5 7600 6-Core Processor (12 threads) | RAM: 94 GB
Cache: Memory, 512 MB, 600 frames, ahead 70%, pre-roll 24/48
Performance: Threads: OMP 12 | FFmpeg 8, Cards: Decode: None (0) | Encode: 0

**Comment by DarkTyger** [comment]
A working solution that I have verified, from Claude:

> The project now expects the recording as a standard 1920×1080 file. Close OpenShot, then run this in the video/ folder:

``` bash
mv keenlore.mkv keenlore-1290x1024.mkv
ffmpeg -i keenlore-1290x1024.mkv \
  -vf "scale=-2:1080:flags=lanczos,pad=1920:1080:(ow-iw)/2:0:black" \
  -fps_mode passthrough -c:v libx264 -crf 10 keenlore.mkv
```

> What it does: it scales the 1290×1024 recording to 1360×1080 and pads it with black to 1920×1080, 280 px from the left. That's where OpenShot already puts it, so your framing and any zooms stay the same.
>
> Why that removes the line: the export is 1920×1080, so OpenShot no longer has to resize anything. Right now it stretches each frame to a fractional 1360.55 px, and the 1290-px right edge is where that goes wrong. Your cuts still line up: passthrough keeps every frame's original timestamp. Quality: -crf 10 is visually lossless. The original is kept as keenlore-1290x1024.mkv.
>
> What I changed in keenlore.osp: the stored size of keenlore.mkv now reads 1920×1080, 16:9, in its file entry, every clip that uses it, and the undo history. Nothing else changed. The file name is the same, so no clip needs relinking.
>
> Keep the export settings from my earlier change (1920×1080 at 30 fps). They're what makes the new file land pixel for pixel.
