### ISSUE TITLE
On openshot Audio fine after Export very choppy

### ISSUE THREAD

**Issue by Colinsky1** [OpenShot/openshot-qt#2054]
OGG format issues

**System Details (please complete the following information):**
 - Operating System win 10
 2.4.2

**To Reproduce**

**Screenshots**
If applicable, add screenshots to help explain your problem

![op](https://user-images.githubusercontent.com/42942475/44995804-c4577a80-af72-11e8-94e7-63e0deb34edb.JPG)

![op2](https://user-images.githubusercontent.com/42942475/44995819-d0dbd300-af72-11e8-9ad5-2d8effedd7d7.JPG)

![opadjpg](https://user-images.githubusercontent.com/42942475/44995827-d76a4a80-af72-11e8-846b-1fe9159c2717.JPG)
.

**Comment by DylanC** [comment]
@Colinsky1  Try v2.4.3 and let us know if you still have a problem.
