### ISSUE TITLE
export video fail

### ISSUE THREAD

**Issue by divetime** [OpenShot/openshot-qt#2058]
**Describe the bug**
created a video, attempting to export and openshot shuts down  after  about 7% has processed.  

**System Details (please complete the following information):**
 - Operating System / windows
 - OpenShot Version 720 24p

m havens
buzybx3@gmail.com

**Comment by DylanC** [comment]
@divetime - Try v2.4.3 and let us know if you still have a problem.

**Comment by DylanC** [comment]
@divetime - This editor is free to export. It sounds like maybe you reported the issue in the wrong place. I would recommend to not delete the program and all your work next time. :smiley:

**Comment by divetime** [comment]
Thank you for your *sincere advice *for my days of frustration trying
to get this program to export and not responding until a month after my
attempt to reach out to someone for assistance.

Had I been able to contact someone sooner (instead of being told I didn't
send request to correct link), I would have still had it loaded. I don't
keep programs on my computer that are of no use to me.
