### ISSUE TITLE
Blender is not visible, despite being correctly addressed in preferences 

### ISSUE THREAD

**Issue by Geoffphuket** [OpenShot/openshot-qt#2061]
**Describe the bug**

**System Details (please complete the following information):**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**To Reproduce**

I want to add an animated title and have downloaded Blender, installed, and added the executable location under preferences:  C:\Program Files\Blender Foundation\Blender

The program still asks me to add blender and doesn't  work, despite all settings being correct.

![1](https://user-images.githubusercontent.com/42936987/45015152-00f6a500-b04b-11e8-9b62-571890859677.JPG)

**Comment by MrRiegel** [comment]
your path is wrong.
use `C:\Program Files\Blender Foundation\Blender\blender.exe`

**Comment by Geoffphuket** [comment]
I've tried everything now! Blender will run independently, so I know there's nothing wrong there.
Even copying the exact location and pasting it directly to Openshot doesn't work. Can nobody help?
![1](https://user-images.githubusercontent.com/42936987/45141191-61b6e680-b1df-11e8-9070-e44bb74e83e4.JPG)

**Comment by MrRiegel** [comment]
why does your path contain `file://`? that's wrong.
show your preference window.
it should look like this.
https://screenshotscdn.firefoxusercontent.com/images/e3576445-aaab-4bd9-8b7e-eeb48ed15251.png

**Comment by Geoffphuket** [comment]
Yes, that was exactly how I entered it on my first attempt and it didn't work. I'm stumped!

**Comment by MrRiegel** [comment]
in your first screen shot the `blender.exe` was missing.
and in your second one you used `/` instead of `\` and added `file://`.
what are you doing?
just follow this [instructions](https://youtu.be/x74mztViPgo?start=38)

**Comment by Geoffphuket** [comment]
I'd tried various combinations of the address, including the one shown on the YouTube video - none of them worked. In the end I got it to work by reinstalling OpenShot and trying again.
Now I'm not sure it was worth all the trouble! It takes forever to render a short title, even on a fast Core i7 machine with buckets of memory.... and after all that, the result isn't impressive, to say the least.

**Comment by DylanC** [comment]
@Geoffphuket - For speed you would more need a graphics card in your machine. Really helped render titles for me. I don't think processor or RAM matters that much for it.

**Comment by DylanC** [comment]
I put in a change to have browse buttons in future. This will work better in newer releases:
https://github.com/OpenShot/openshot-qt/pull/2255

**Comment by Iwan2019** [comment]
> why does your path contain `file://`? that's wrong.
> show your preference window.
> it should look like this.
> https://screenshotscdn.firefoxusercontent.com/images/e3576445-aaab-4bd9-8b7e-eeb48ed15251.png

I use Browse button and I used the path C:\Program Files\Blender Foundation\Blender\blender.exe    but still does not work... can you help me?

**Comment by ferdnyc** [comment]
@Iwan2019 You're not using Blender 2.80 (the new release), are you? OpenShot isn't compatible with that version yet (#2901), though a fix is currently being worked on (#2915).

**Comment by ferdnyc** [comment]
For the moment, the only solution is to install Blender 2.79 instead.

**Comment by Iwan2019** [comment]
Yes it Done... Thanks verymuch

Dikirim dari Yahoo Mail di Android 
 
  Pada Sab, 10 Agt 2019 pada 7:37, Frank Dana<notifications@github.com> menulis:   
For the moment, the only solution is to install Blender 2.79 instead.

**Comment by ferdnyc** [comment]
I've pinned #2901 to increase its visibility until we're able to get a fix released.

**Comment by Iwan2019** [comment]
Oh...I install 2.79.  Animated  tittle work but when I pres render the same message come... Again and again... Any script i need change?

Dikirim dari Yahoo Mail di Android 
 
  Pada Sab, 10 Agt 2019 pada 7:37, Frank Dana<notifications@github.com> menulis:   
For the moment, the only solution is to install Blender 2.79 instead.
