### ISSUE TITLE
launch.exe entrypoint not found   Kernel32.DLL   Win XP/SP3

### ISSUE THREAD

**Issue by asdefew** [OpenShot/openshot-qt#2063]
**Describe the bug**
launch.exe entrypoint not found   Kernel32.DLL   Win XP/SP3  -  openshot does not start

**System Details (please complete the following information):**
 - Win XP/SP3  Kernel32.DLL found in WINDOS\system32\
 - OpenShot Version 2.4.2-x86.exe installed
**To Reproduce**
after installation: program does not start
Original kernel32.dll is added as zip
**Expected behavior**
normal start
**Screenshots**
<img width="528" alt="openshot2018-09-04 20_56_37-videosoftware" src="https://user-images.githubusercontent.com/42979690/45052662-23061c80-b077-11e8-8ba0-d2286b1390bf.png">

lp explain your problem.

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**
[kernel32.zip](https://github.com/OpenShot/openshot-qt/files/2349901/kernel32.zip)

**Comment by MrRiegel** [comment]
[system requirements](https://www.openshot.org/static/files/user-guide/introduction.html#system-requirements) says Win 7/8/10
