### ISSUE TITLE
Transformation is unaffected by time change

### ISSUE THREAD

**Issue by KidsDontPlay** [OpenShot/openshot-qt#2064]
**Describe the bug**
if you change the speed of a video the speed of the animation between two keyframes is unchanged

**System Details (please complete the following information):**
 - Linux mint 16
 - OpenShot Version 2.4.2

**To Reproduce**
 - set the play-head to the first frame of a clip
 - right-click the clip and click transform
 - scale the clip to half of its origin size and move it to the left of the video
 - set the play-head to the last frame
 - move the clip to the right side
 - right-click the clip and press time>fast>forward>2x

**Expected behavior**
transformation speed is changing as well

**Comment by ctsdownloads** [comment]
Unreproducible, old version of OpenShot
