### ISSUE TITLE
Crashes on export

### ISSUE THREAD

**Issue by DRONEFUN1333** [OpenShot/openshot-qt#2065]
During the export process the program just shuts down. When I open it back up it recovers project at an earlier stage of work. I have to then open my saved project. It goes from 30 to 50 % done when it shuts down. I tried about 6 times before giving up and going to another program to complete my project.
       Prior to export the program works very well and I enjoy it. It did shut down one time while working on project (I learned to save while working).  I am puzzled on how to add a title and credits etc but will figure this out if the export gets fixed.
       Since my desktop was 4 years old I thought this might be the issue. I have now upgraded to a Windows 10, I-7 eight generation, with 16GB of memory,SSD & a hard drive. So it should not be a memory or processor issue.  I have no idea how to attach logs. 
       There is nothing to screen shot for it just stops and shuts down the program (not the computer). When the program is opened back up sometimes it recovers old version of the project, other times it just opens like it is ready to work new.
       If this issue would get fixed (has happened a few times in the past 2 months) I would consider upgrading for the additional features, but not until the export works.
     Open Shot - 2.4.2
Thank you.

**Comment by N3WWN** [comment]
What are the file types of the clips within the transition?  

I am using 2.4.1, so not the latest version, but find that sometimes a transition which consists of a `.jpg` file and a `.mp4` file will crash, but if I convert the `.jpg` into a `.png`, the transition works perfectly.

**Comment by DRONEFUNE1333** [comment]
Original video was shot in MP4 format using a DJI drone. When project was
complete and export attempted I was using MOV format. No JPG's used in any
of my 4 failed projects.

**Comment by alan06200** [comment]
I am using the las 2.4.2 and now download the Daily Builds of the 64 bits version. The problem is the same with the Daily Buids version. In twice version when I use a transition of 2 clips xxx.avi and I export the project in mp4 file...Openshot crash.
When I remove the transition the export is normal....
this problem exist from the new verison2.4.2

**Comment by DylanC** [comment]
@DRONEFUN1333 @alan06200 - This transitions bug has been fixed. See #2125.
