### ISSUE TITLE
Annoing noise on merging point when concatenating movies

### ISSUE THREAD

**Issue by mcatalin22** [OpenShot/openshot-qt#2066]
I'm using OpenShot 2.4.2 and I have some issues with the sound on merging files. When merging two or more video files at the merging point some noise is added to the final video. Anyone knows how to get rid of this noise? It doesn't appear in all merging points, just some of them.

**System Details**
 - Operating System / Distro: [Windows 10]
 - OpenShot Version [2.4.2]

**Comment by ctsdownloads** [comment]
Unreproducible, old version of OpenShot
