### ISSUE TITLE
00539.MTS manquant

### ISSUE THREAD

**Issue by fredodugard** [OpenShot/openshot-qt#2068]
Message d'erreur au lancement du programme :+1:  
Fichier manquant :+1: 
00539.MTS ne peut être trouvé
![erreur open shot](https://user-images.githubusercontent.com/43000926/45090441-a1ae9880-b10f-11e8-9357-0bf5310b1784.JPG)

**Comment by peanutbutterandcrackers** [comment]
While I do not understand the issue well, I suggest you try transcoding the video using [HandBrake](https://handbrake.fr/) into something like `.mkv`, `.mp4`, etc.

Closing this for now. Please do feel free to comment/re-open if you feel like it.
