### ISSUE TITLE
Crash on export [windows]

### ISSUE THREAD

**Issue by Kissaki** [OpenShot/openshot-qt#207]
cropped and positioned some clips in one track in OpenShot 2.0.7

Exporting the video seems to work at first, with the progress bar showing progress, but eventually launch.exe crashes

>   libopenshot.dll!06cf59fc()  Unknown
>     [Frames below may be incorrect and/or missing, no symbols loaded for libopenshot.dll]  
>     libopenshot.dll!06ce1747()  Unknown
>     [External Code] 
>     libgomp-1.dll!63606352()    Unknown
>     libgomp-1.dll!6360935e()    Unknown
>     libgomp-1.dll!63609527()    Unknown
>     libgomp-1.dll!63601641()    Unknown
>     libopenshot.dll!06ce5462()  Unknown
>     libgomp-1.dll!636090b4()    Unknown
>     libgomp-1.dll!63609224()    Unknown
>     libgomp-1.dll!63609287()    Unknown
>     libgomp-1.dll!636077d6()    Unknown
>     libwinpthread-1.dll!64944f11()  Unknown
>     [External Code]

**Comment by apraetor** [comment]
I have this issue as well. OpenShot crashes any time I preview a video or export (Win10, 2.0.7). It happens at 4% export every time regardless of the duration of the video being exported.

**Comment by olivm-fr** [comment]
I have freezes on Win7 64b, 2.0.7, when exporting. Have to kill the app :( 
But depending on the format being selected, it goes up to 40%, 80%, and even, sometimes (rarely), it completes (on videos lasting 1min) !
It goes further with OGG formats than MP4.
Webm gives a direct crash.

Honestly, it makes OpenShot a nightmare...

**Comment by jonoomph** [comment]
I've made some pretty big improvements to how videos are read (especially videos with missing frames or missing audio data). Please give our latest preview version a try: 

Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot.

**Comment by olivm-fr** [comment]
Thanks for caring about this issue.
I've updated yesterday and tested ... but the result is the same : the process freezes (@ around 24%).

As I needed the job done, I've copied the project file and its source videos/SVGs on a Fedora computer. => it has frozen once, and then it has succeeded several times in a row. I could complete my rendering, thanks to Linux ;)

**Comment by DylanC** [comment]
@Kissaki - Closing since this is reported on a much older version of OpenShot.  Please test the latest version to confirm if problem still exists. Thanks.

**Comment by apraetor** [comment]
Just tested with 2.3.4, issue still occurs on every export attempt. Do you want to reopen this, or should I create a new incident?
