### ISSUE TITLE
The color of exported video is different from origin image

### ISSUE THREAD

**Issue by ShizumaruRiya** [OpenShot/openshot-qt#2070]
**Describe the bug**
The color of exported video is different from original image.

**System Details (please complete the following information):**
Windows 10 Pro 1803
Ver. 2.4.2

**To Reproduce**
1. Import any image.
(Download a free image from https://pixabay.com/)
2. Drag and drop the image into timeline.
3. Set play time for 5 sec.
4. No effect, no filter.
5. Export as 4K 2160p 60fps, High.

**Expected behavior**
Play the video and the origin image with VLC.
The color should be the same.

**Screenshots**
https://i.imgur.com/eWd85r6.png

**Logs**
none.

**Additional context**
none.

**Comment by peanutbutterandcrackers** [comment]
I wonder if this has something to do with color-pace conversions and stuff. Something @N3WWN would probably be more qualified to speak about than I myself. Perhaps this is not a *real* issue per se?
