### ISSUE TITLE
crash on export, macOS 10.11.6

### ISSUE THREAD

**Issue by pauloord123** [OpenShot/openshot-qt#2072]
**Describe the bug**
Program crashes (reproducible) on export of a simple movie, no transitions or effects, only combination of audio and (strechted) video.

**System Details (please complete the following information):**
 - Operating System  MacOS El Capitan, 10.11.6
 - OpenShot Version  2.4.2

**To Reproduce**
1. Add video and audio
2. Put in seperate tracks
3. Export
4. Program ends (crashes) without messages 

**Expected behavior**
Generate movie with sound combined

**Screenshots**
impossible

**Logs**
when launching in terminal (./launch) on the crash I got:

`[libx264 @ 0x11309c400] using cpu capabilities: MMX2 SSE2Fast SSSE3 Cache64 SlowShuffle
[libx264 @ 0x11309c400] profile High, level 4.1
[libx264 @ 0x11309c400] 264 - core 142 r2438 af8e768 - H.264/MPEG-4 AVC codec - Copyleft 2003-2014 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=2 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=2 keyint=12 keyint_min=1 scenecut=40 intra_refresh=0 rc_lookahead=12 rc=abr mbtree=1 bitrate=15000 ratetol=1.0 qcomp=0.60 qpmin=2 qpmax=30 qpstep=4 ip_ratio=1.40 aq=1:1.00
Caught signal 4 (SIGILL)
---- Unhandled Exception: Stack Trace ----
  4   libavcodec.55.dylib                 0x0000000109cfae36 ff_lag_rac_init + 5820
---- End of Stack Trace ----`

And a bit later:
`[...] $ Caught signal 4 (SIGILL)
-bash: syntax error near unexpected token `('
`
connected with libavcodec.55.dylib 

**Additional context**
original video is 640 x 480, what to choose as output?

**Comment by pauloord123** [comment]
I tried the same on a 'clean' macbook and Openshot Video Editor works fine. 
So what is wrong with the other machine?

**Comment by poborn** [comment]
Same problem happening to me on my macbook. OS 10.11.6
Quits instantly, every time i hit the 'export video' button.

**Comment by rajshroff** [comment]
I am having the same problem. Every time I hit the export video button Open Shot Video closes instantly. I also run Macbook OS 10.11.16

**Comment by pauloord123** [comment]
I switched to using ffmpeg. For me this is enough to merge video and audio of different duration in one file. 
It is quite easy, with ffmeg and an Applescript, to get the duration of both files and then adjust the video to fit the audio duration. Second step is to merge the new vidoe with the audio.
Have good luck with Openshot...!
