### ISSUE TITLE
OpenShot Video Editor is frozen completely

### ISSUE THREAD

**Issue by wksteele** [OpenShot/openshot-qt#2075]
**Describe the bug**

I was using it earlier today to edit some videos.  I had just exported a video successfully and when I went to edit the next one it froze.  It went to "Not responding" on the title bar and from that point on it will not do anything.  I have uninstalled the software and reinstalled it and brought it up and it froze almost immediately.  I have rebooted my computer and uninstalled and reinstalled it with the same results.  It is basically useless to me now for anything.

**System Details (please complete the following information):**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

Windows 7 (updated to current this week), OpenShot-v2.4.2-x86_64.exe.

**To Reproduce**

I cannot reproduce it because it simply will not do anything.  I can't edit video or play video.  It just freezes and I have to end it with the task manager.

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/35817097/45249366-221df680-b2d4-11e8-82b9-6256c5ef67a5.png)

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/2362964/libopenshot.log)

[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2362965/openshot-qt.log)

[openshot-qt.2.log](https://github.com/OpenShot/openshot-qt/files/2362966/openshot-qt.2.log)
[openshot-qt.3.log](https://github.com/OpenShot/openshot-qt/files/2362967/openshot-qt.3.log)
[openshot-qt.1.log](https://github.com/OpenShot/openshot-qt/files/2362968/openshot-qt.1.log)

**Additional context**

This is my first time posting, so I don't really know what to do or to say.  I'm going to have to look for something else.  The problem is that I love working with it, but now I don't feel I can depend on it.

**Comment by DylanC** [comment]
@wksteele - I noticed you are on an older version. Can you try v2.4.2 please?
