### ISSUE TITLE
Unable to load DLL library

### ISSUE THREAD

**Issue by OgreMHDW** [OpenShot/openshot-qt#2076]
**Describe the bug**
When attempting to open the program after install, an error is received that it cannot load the DLL. 

**System Details (please complete the following information):**
 - Operating System / Distro: Windows 10 Pro, v1809 build 17751.1
 - OpenShot Version: 2.4.2

**To Reproduce**
1. Install OpenShot.
2. Run the program. 

**Expected behavior**
Program should open.

**Screenshots**
![image](https://user-images.githubusercontent.com/4369476/45257617-0b23e680-b35e-11e8-8c8a-75293445bc75.png)

**Logs**
No logs were generated.

**Comment by Doobyfrucan** [comment]
Same as original poster. 

System: Windows 10 Pro (Version 1709 build 16299.547).
OpenShot version: Tried both OpenShot 2.4.2 and OpenShot 2.4.3-release-candidate-1537166623-x86_64

**Comment by peanutbutterandcrackers** [comment]
Could you please try out [the latest daily builds](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914) and see if those work for any of you? And/Or, you could also try deleting `.openshot_qt` folder from your home folder.

**Comment by Doobyfrucan** [comment]
Tried latest build which still gives the same error message As for the folder,  insofar as I can tell there was no `.openshot_qt` folder anywhere on windows.

**Comment by peanutbutterandcrackers** [comment]
Should be in your home folder. In the same folder that contains 'My Documents' and other folders.

**Comment by Doobyfrucan** [comment]
From what I can tell nothing there, am doing a system-wide search for it though. Something just hit me about the error message, the line you're referring to uses a forward slash `openshop_qt/launch.py` while all other directories use the backslash - I know some systems / languages are picky about which they use - would this be a factor in this case?

**Comment by Doobyfrucan** [comment]
Found the directory

**Comment by Doobyfrucan** [comment]
Deleting the directory has no impact.

**Comment by Doobyfrucan** [comment]
I can also confirm that the `openshot_qt` directory and all of its subfolders are in fact empty.

**Comment by Phi618** [comment]
I also tried both. Neither made the software working.

**Comment by ferdnyc** [comment]
I'm going to close this in favor of the more detailed #2748, for OpenShot 2.4.4.
