### ISSUE TITLE
Cropping a video in OpenShot

### ISSUE THREAD

**Issue by ppkakkar** [OpenShot/openshot-qt#2078]
I want to crop a video Horizontally or Vertically to remove some watermarks.
How to crop a video horizontally or vertically in OpenShot?

**System Details**
 - Operating System - Windows 10
 - OpenShot Version 2.4.1

**Comment by Lurchiloo** [comment]
you will find an effect called crop

**Comment by N3WWN** [comment]
You can also use the `Scale X` and `Scale Y` properties along with `Location X` and `Location X` to zoom in and recenter.

**Comment by DylanC** [comment]
@ppkakkar Follow above feedback if you haven't seen this yet.

**Comment by chrismd2** [comment]
Hey, I know this is an old/long time closed question, but I landed here when I realized most videos and guides on the topic are on an outdated version.  This was certainly the best answer I found:

> you will find an effect called crop

Being a complete noob, it took me a moment to realize how to edit the effect to crop the video.
- Click and drag that effect to the video track you wish to crop
- Right click the effect logo on the track and choose properties
- Edit the properties in the appropriate pane

**Comment by endofmyday** [comment]
> Hey, I know this is an old/long time closed question, but I landed here when I realized most videos and guides on the topic are on an outdated version. This was certainly the best answer I found:
> 
> > you will find an effect called crop
> 
> Being a complete noob, it took me a moment to realize how to edit the effect to crop the video.
> 
> * Click and drag that effect to the video track you wish to crop
> * Right click the effect logo on the track and choose properties
> * Edit the properties in the appropriate pane

i know this is still a pretty old thread but i want people to know, the effect in openshot called "crop" isnt a true crop feature, it only creates black bars on the sides. say you use a custom profile on openshot for a 9:16 aspect ratio for an android screen, say 480x720. if you use the crop effect on a video that was originally widescreen 16:9 say 1280x720 and are trying to convert it to an android screen properly, it wont work, even with the crop, the original video will stay widescreen, so when you set your custom profile (for specific resolution) after the crop, the picture size will  just be a smaller version of the widescreen video in the 9:16 aspect ratio. if you wanna crop a video, i would suggest doing it outside of openshot, and then use openshot for whatever youre doing, making the file size smaller etc

**Comment by joro88** [comment]
> the effect in openshot called "crop" isnt a true crop feature, it only creates black bars on the sides. 

I totally agree. OpenShot offers only that fake crop.

Crop seems pretty advanced functionality for OpenShot
