### ISSUE TITLE
Openshot crashes on transitions

### ISSUE THREAD

**Issue by Lorkkk** [OpenShot/openshot-qt#2079]
Hi all, this bug was already reported a lot of times but it is always closed. 
If i add some transitions, during the prewiev it crashes on the first of them.

**System Details :**
 - Operating System / Distro: [ Windows 10]
 - OpenShot Version [v2.4.2-x86_64]

**To Reproduce**
1. Add one video
2. Add a second video, that at beginning it's overlying with the first.
3. Click play in the prewiev

Now on Windows 10, just updated right now, with the latest version of Openshot OpenShot-v2.4.2-x86_64 i've the same problem like others had encountered in the past.

It's 10 days that i have this kind of problem and it's very frustrating! 
If you need some other infos please tell me where i can find them (i'm not an expert) and i will send you.

Thanx

**Comment by DylanC** [comment]
@Lorkkk - This bug has been fixed in v2.4.3. 🎉
