### ISSUE TITLE
OpenShot crash when restoring clip using "Undo"

### ISSUE THREAD

**Issue by linqcan** [OpenShot/openshot-qt#208]
How to reproduce:
- Add a clip
- Remove the clip
- Click on "Undo"
- Try to right-click (ShowClipMenu) on the restored clip

Expected clip menu to appear, instead I've got no clip menu and error in the console:

```
timeline_webview:INFO ShowClipMenu: Q39TB2T7HB
      logger:ERROR Traceback (most recent call last):
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot_qt/windows/views/timeline_webview.py", line 695, in ShowClipMenu
      logger:ERROR start_of_clip = float(clip.data["start"])
      logger:ERROR AttributeError
      logger:ERROR :
      logger:ERROR 'NoneType' object has no attribute 'data'
```

Bonus: If you move the clip to another layer and try to right-click on it OpenShot crashes with the following signature:

```
terminate called after throwing an instance of 'openshot::ReaderClosed'
  what():  No Reader has been initialized for this Clip.  Call Reader(*reader) before calling this method.
Aborted (core dumped)
```

**Comment by jonoomph** [comment]
This has been fixed in our latest daily builds. Please verify, and reopen this issue if you still see a problem. Fingers crossed it will work great now. Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot. Thanks!
