### ISSUE TITLE
openshot crashes while generating mpeg2 in avi container

### ISSUE THREAD

**Issue by Lurchiloo** [OpenShot/openshot-qt#2080]
Hello together,

i´am trying to cut my video archives. The files are in SD, DV in an avi container. 
While trying to export in several output formats to compare the best quality i noticed the everytime i tried to use mpeg2 or mpeg4 that openshot crashes at 1% during the process. All the other formats are working but the quality was not very convincing.. also yes the original material looks a bit creepy nowadays.

**System Details**
 - Windows 10

[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2364625/openshot-qt.log)

 - OpenShot Version  2.4.2

I hope you can help me with this issue!

Thanx, Lars

**Comment by DylanC** [comment]
@Lurchiloo - Try v2.4.3 and let us know if you still have a problem.

**Comment by Lurchiloo** [comment]
still crashes at 1%

**Comment by Lurchiloo** [comment]
do you think i can solve the problem with installing a codec package? 
Can you recommend one for windows 10 64bit?
