### ISSUE TITLE
Generated Title 3D return no blender with Dissolving and Exploding

### ISSUE THREAD

**Issue by Sefran007** [OpenShot/openshot-qt#2086]
**Describe the bug**
Openshot broken looking for path with some generated title 3D like Dissolving and Exploding text

**System Details (please complete the following information):**
Architecture : x86_64
model name : Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz
Operating System & version: Linux 4.17.17-1-MANJARO #1 SMP PREEMPT Sat Aug 18 14:38:10 UTC 2018 GNU/Linux
Installation Method : pacman/yaourt
Version of Openshot installed : 2.4.2
MLT/melt version : 6.10.0
FFmpeg (i.e.libavcodec) version : n4.0.2
built with gcc 8.2.0 (GCC)
configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avresample --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-nvenc --enable-omx --enable-shared --enable-version3
libavutil 56. 14.100 / 56. 14.100
libavcodec 58. 18.100 / 58. 18.100
libavformat 58. 12.100 / 58. 12.100
libavdevice 58. 3.100 / 58. 3.100
libavfilter 7. 16.100 / 7. 16.100
libavresample 4. 0. 0 / 4. 0. 0
libswscale 5. 1.100 / 5. 1.100
libswresample 3. 1.100 / 3. 1.100
libpostproc 55. 1.100 / 55. 1.100
Blender version : 2.79 (sub 0)

**To Reproduce**
I revolve problem with changing setting from blender interface.
For me the translation (french) of blender is the problem.
File>User Preferences…
Chose system configuration.
From International Fonts unselect New Data
After this, my openshot working well :-)

**Expected behavior**

**Screenshots**
http://sefran007.free.fr/wp-content/uploads/BugErreurScriptBlender.png

**Logs**
I add graphic blender debugger to understand problem
http://sefran007.free.fr/wp-content/uploads/DebugErrorWithBlender.png

**Additional context**
Missing from python script command bpy.context.user_preferences.system.use_translate_new_dataname = False With testing bpy.context.user_preferences.system.use_international_fonts is true.

Of course the state of bpy.context.user_preferences.system.use_translate_new_dataname is saved before, and restoring at the end of running plugin ;-)

**Comment by Sefran007** [comment]
[patch.zip](https://github.com/OpenShot/openshot-qt/files/2372220/patch.zip)

**Comment by peanutbutterandcrackers** [comment]
This is neat, too! Please do submit a PR soon! :)
