### ISSUE TITLE
Title 3D zoom clapboard does not fit the text well

### ISSUE THREAD

**Issue by Sefran007** [OpenShot/openshot-qt#2087]
**Describe the bug**
Title 3D zoom clapboard does not fit the text well with multi lines (character \n)

**System Details (please complete the following information):**
1) Manjaro Linux 4.17.17-1-MANJARO #1 SMP PREEMPT x86_64 GNU/Linux
2) Installation method Pacman/Yaourt
3) Openshot 2.4.2
4) melt 6.10.0
5) Blender 2.79 (sub 0)

**To Reproduce**
Generate title 3D clapboard with title text "My title\nAuthor"

**Expected behavior**
http://sefran007.free.fr/wp-content/uploads/TitleFileName0060.png

**Screenshots**
None

**Logs**
None

**Additional context**
I add this with zoom_clapboard.py for correct placement text for rendering.
[zoom clapboard.zip](https://github.com/OpenShot/openshot-qt/files/2372265/zoom.clapboard.zip)

 ```
# Panel background of clapboard
 bpy.context.scene.objects.active = bpy.data.objects["Cube"]
 bpy.data.objects["Cube"].select = True
 # Center axes of object
 bpy.ops.object.origin_set(type='ORIGIN_GEOMETRY')
 
 # Text of clapboard
 bpy.context.scene.objects.active = bpy.data.objects["Text"]
 bpy.data.objects["Text"].select = True
 # Center axes of object
 bpy.ops.object.origin_set(type='ORIGIN_GEOMETRY')
 # Same position of x for center
 bpy.data.objects["Text"].location[0] = bpy.data.objects["Cube"].location[0]
 # Same position of z for center
 bpy.data.objects["Text"].location[2] = bpy.data.objects["Cube"].location[2]
 # Fit width of text to adapt board clapboard
 bpy.data.objects["Text"].dimensions[0] = 0.95 * bpy.data.objects["Cube"].dimensions[0]

```

**Comment by peanutbutterandcrackers** [comment]
@DylanC - Evidently, we've lost somehow failed to notice these gems of improvements regarding blender from this fine gentleman here, Cap'n!
