### ISSUE TITLE
Title 3D defocus does not fit the text well

### ISSUE THREAD

**Issue by Sefran007** [OpenShot/openshot-qt#2088]
**Describe the bug**
Title 3D defocus does not fit the text well

**System Details (please complete the following information):**
1) Manjaro Linux 4.17.17-1-MANJARO #1 SMP PREEMPT x86_64 GNU/Linux
2) Installation method Pacman/Yaourt
3) Openshot 2.4.2
4) melt 6.10.0
5) Blender 2.79 (sub 0)

**To Reproduce**
Gnenerate title 3D defocus with title: 
"Title of week
Subtitle
Author"

**Expected behavior**
http://sefran007.free.fr/wp-content/uploads/TitleFileName0105.png

**Screenshots**
None

**Logs**
None

**Additional context**
I add this with defocus.py for correct placement text for rendering.
[defocus.zip](https://github.com/OpenShot/openshot-qt/files/2372289/defocus.zip)

```
# Text of defocus
bpy.context.scene.objects.active = bpy.data.objects["Text"]
bpy.data.objects["Text"].select = True
# Mode object
bpy.ops.object.mode_set(mode='OBJECT')
# Center axes of text
bpy.ops.object.origin_set(type='ORIGIN_GEOMETRY')
# Set position of axe x and z to 0
bpy.data.objects["Text"].location[0] = 0.0
bpy.data.objects["Text"].location[2] = 0.0

#Possibility to set camera view to object text size
#bpy.ops.view3d.camera_to_view_selected()
```

**Comment by peanutbutterandcrackers** [comment]
Another comment so that you will receive email notification to come back around and submit these patches as Pull Requests so that we have have further discussions and code reviews with the community. You are awesome!
