### ISSUE TITLE
Title 3D blur does not fit the text well 

### ISSUE THREAD

**Issue by Sefran007** [OpenShot/openshot-qt#2089]
**Describe the bug**
Title 3D blur does not fit the text well with multiline

**System Details (please complete the following information):**
1) Manjaro Linux 4.17.17-1-MANJARO #1 SMP PREEMPT x86_64 GNU/Linux
2) Installation method Pacman/Yaourt
3) Openshot 2.4.2
4) melt 6.10.0
5) Blender 2.79 (sub 0)

**To Reproduce**
Generate 3D title blur with text title:
"My title of week
Subtitle
Author"

**Expected behavior**
http://sefran007.free.fr/wp-content/uploads/TitleFileName0107.png

**Screenshots**
None

**Logs**
None

**Additional context**
I add this with blur.py for correct placement text for rendering.
[blur.zip](https://github.com/OpenShot/openshot-qt/files/2372304/blur.zip)

```
# Text of blur
bpy.context.scene.objects.active = bpy.data.objects["Text"]
bpy.data.objects["Text"].select = True
# Mode object
bpy.ops.object.mode_set(mode='OBJECT')
# Center axes of text
bpy.ops.object.origin_set(type='ORIGIN_GEOMETRY')
# Set position of axe x and z to 0
bpy.data.objects["Text"].location[0] = 0.0
bpy.data.objects["Text"].location[2] = 0.0

#Possibility to set camera view to object text size
#bpy.ops.view3d.camera_to_view_selected()
```

**Comment by peanutbutterandcrackers** [comment]
Cool improvements, good sir! Now, if only you would be so kind as to create a Pull Request so that we can have proper code reviews. :)
