### ISSUE TITLE
audio very slow

### ISSUE THREAD

**Issue by angelistudio** [OpenShot/openshot-qt#209]
Hi there,
and thanks Jonathan for this beautiful software.

I'm completely new to Openshot, just trying to add some images and an audio file (mp3). In preview mode and also when I export the movie, the audio is REALLY slow. 
The mp3 sample rate is 44.100, and so is the audio in Preferences > Profiles.

I'm using OS X Yosemithe.

Any suggestions?

**Comment by Kagetsuki** [comment]
Audio processing is generally a pretty heavy operation - how much memory do you have available when you're previewing? Is swap usage at 0%?

**Comment by jeffersoneagley** [comment]
I'm on an MSI GT-70 with an i7, 32GB ram, and a GTX870M, and I'm having the "audio plays super slow in preview mode" bug. I don't think this is a hardware usage issue.

**Comment by DylanC** [comment]
@angelistudio - What version of OpenShot is this? Did you test on the latest version? (2.3.4)

**Comment by DylanC** [comment]
Closing for now until we get further details.
