### ISSUE TITLE
Title 3D rotate 360 does not fit the text well

### ISSUE THREAD

**Issue by Sefran007** [OpenShot/openshot-qt#2090]
**Describe the bug**
Title 3D rotate 360 does not fit the text well with multiline text

**System Details (please complete the following information):**
1) Manjaro Linux 4.17.17-1-MANJARO #1 SMP PREEMPT x86_64 GNU/Linux
2) Installation method Pacman/Yaourt
3) Openshot 2.4.2
4) melt 6.10.0
5) Blender 2.79 (sub 0)

**To Reproduce**
Generate title 3D rotate 360 with text title:
"My title of day
Subtitle
Author"

**Expected behavior**
http://sefran007.free.fr/wp-content/uploads/TitleFileName0136.png

**Screenshots**
None

**Logs**
None

**Additional context**
I add this with rotate_360.py for correct placement text for rendering.
[rotate 360.zip](https://github.com/OpenShot/openshot-qt/files/2372329/rotate.360.zip)

```
# Text of rotate 360
bpy.context.scene.objects.active = bpy.data.objects["Font"]
bpy.data.objects["Font"].select = True
# Mode object
bpy.ops.object.mode_set(mode='OBJECT')
# Center axes of text
bpy.ops.object.origin_set(type='ORIGIN_GEOMETRY')
# Set position of axe x and z to 0
bpy.data.objects["Font"].location[0] = 0.0
bpy.data.objects["Font"].location[2] = 0.0

#Possibility to set camera view to object text size
#bpy.ops.view3d.camera_to_view_selected()
```

**Comment by peanutbutterandcrackers** [comment]
I must admit, I am a fan of you already, good sir @Sefran007! These improvements would be a lot of help!
