### ISSUE TITLE
Title 3D neon curve does not fit the text well 

### ISSUE THREAD

**Issue by Sefran007** [OpenShot/openshot-qt#2092]
**Describe the bug**
Title 3D neon curve does not fit the text well with multiline text.

**System Details (please complete the following information):**
1) Manjaro Linux 4.17.17-1-MANJARO #1 SMP PREEMPT x86_64 GNU/Linux
2) Installation method Pacman/Yaourt
3) Openshot 2.4.2
4) melt 6.10.0
5) Blender 2.79 (sub 0)

**To Reproduce**
Generate title 3D neon curve with text:
"My title of year
Subtitle
Author"

**Expected behavior**
http://sefran007.free.fr/wp-content/uploads/TitleFileName0250.png

**Screenshots**
None

**Logs**
None

**Additional context**
I add this with neon_curve.py for correct placement text for rendering.
[neon curves.zip](https://github.com/OpenShot/openshot-qt/files/2372378/neon.curves.zip)

```
# set scene Logo
bpy.context.screen.scene = bpy.data.scenes[1]
# Set text to view
bpy.context.scene.objects.active = bpy.data.objects["Font"]
bpy.data.objects["Font"].select = True
# Mode object
bpy.ops.object.mode_set(mode='OBJECT')
# Center axes of text
bpy.ops.object.origin_set(type='ORIGIN_GEOMETRY')
# Set position of axe x and z to 0
bpy.data.objects["Font"].location[0] = 0.0
bpy.data.objects["Font"].location[2] = 0.0
#bpy.ops.view3d.camera_to_view_selected()
# set scene Background line
bpy.context.screen.scene = bpy.data.scenes[0]

```

**Comment by peanutbutterandcrackers** [comment]
Another comment just so you will not miss the notification emails! :)
