### ISSUE TITLE
Title 3D colors out does not fit the text well

### ISSUE THREAD

**Issue by Sefran007** [OpenShot/openshot-qt#2093]
**Describe the bug**
Title 3D colors out does not fit the text well with mutiline text.

**System Details (please complete the following information):**
 1) Manjaro Linux 4.17.17-1-MANJARO #1 SMP PREEMPT x86_64 GNU/Linux
2) Installation method Pacman/Yaourt
3) Openshot 2.4.2
4) melt 6.10.0
5) Blender 2.79 (sub 0)

**To Reproduce**
Generate title 3d colors out with text title 1:
"My first title
Subtitle
Autor"
title2:
"My second title
Subtitle
Autor"
title3:
"My fird title
Subtitle
Autor"

**Expected behavior**
http://sefran007.free.fr/wp-content/uploads/TitleFileName0109.png

**Screenshots**
None

**Logs**
None

**Additional context**
I add this with colors.py for correct placement text for rendering.
[colors.zip](https://github.com/OpenShot/openshot-qt/files/2372407/colors.zip)

```
# Set Title 1 to view
bpy.context.scene.objects.active = bpy.data.objects["Title1"]
bpy.data.objects["Title1"].select = True
# Mode object
bpy.ops.object.mode_set(mode='OBJECT')
# Center axes of text
bpy.ops.object.origin_set(type='ORIGIN_GEOMETRY')
# Set position of axe x, y and z
bpy.data.objects["Title1"].location[0] = 0.0
bpy.data.objects["Title1"].location[1] = 0.23
bpy.data.objects["Title1"].location[2] = 0.0

# Set Title 2 to view
bpy.context.scene.objects.active = bpy.data.objects["Title2"]
bpy.data.objects["Title2"].select = True
# Mode object
bpy.ops.object.mode_set(mode='OBJECT')
# Center axes of text
bpy.ops.object.origin_set(type='ORIGIN_GEOMETRY')
# Set position of axe x, y and z
bpy.data.objects["Title2"].location[0] = -4.2
bpy.data.objects["Title2"].location[1] = 4.5
bpy.data.objects["Title2"].location[2] = 0.0

# Set Title 3 to view
bpy.context.scene.objects.active = bpy.data.objects["Title3"]
bpy.data.objects["Title3"].select = True
# Mode object
bpy.ops.object.mode_set(mode='OBJECT')
# Center axes of text
bpy.ops.object.origin_set(type='ORIGIN_GEOMETRY')
# Set position of axe x, y and z
bpy.data.objects["Title3"].location[0] = 4.7
bpy.data.objects["Title3"].location[1] = 6.7
bpy.data.objects["Title3"].location[2] = 0.0

```

**Comment by peanutbutterandcrackers** [comment]
Commenting so that you won't miss the notifications. Extremely sorry for the delayed reply. These neat patches somehow got lost in the constant influx of new issues that we get here in the OpenShot repository. Could you please submit these patches as a Pull Request so that the community could come together and test the patches out and provide some further suggestions as needed? It would be awesome to have these cool improvements in before our next release!
