### ISSUE TITLE
Title 3D glare does not fit the text well

### ISSUE THREAD

**Issue by Sefran007** [OpenShot/openshot-qt#2094]
**Describe the bug**
Title 3D glare does not fit the text well with multiline text.

**System Details (please complete the following information):**
1) Manjaro Linux 4.17.17-1-MANJARO #1 SMP PREEMPT x86_64 GNU/Linux
2) Installation method Pacman/Yaourt
3) Openshot 2.4.2
4) melt 6.10.0
5) Blender 2.79 (sub 0)

**To Reproduce**
Generate title 3D glare with text title:
"My super title
Subtitle
Author"

**Expected behavior**
http://sefran007.free.fr/wp-content/uploads/TitleFileName0125.png

**Screenshots**
None

**Logs**
None

**Additional context**
I add this with glare.py for correct placement text for rendering.
[glare.zip](https://github.com/OpenShot/openshot-qt/files/2372439/glare.zip)

**Comment by peanutbutterandcrackers** [comment]
I am going to put this comment in all of your Open Issues so that you get emails so that you can come back ASAP and submit a PR. :)
