### ISSUE TITLE
When python blender script title 3d crash display no found blender

### ISSUE THREAD

**Issue by Sefran007** [OpenShot/openshot-qt#2095]
**Is your feature request related to a problem? Please describe.**
When python blender script title 3d crash display no found blender

**Describe the solution you'd like**
I propose a debug patch that generates an image with the error, the line of code concerned and the system information useful for debugging.

We should create folder openshot into scripts openshot application.
Example path with manjaro :
`/usr/lib/python3.7/site-packages/openshot_qt/blender/scripts/openshot/`

put file debug.py into directory /usr/lib/python3.7/site-packages/openshot_qt/blender/scripts/openshot/
[openshot.zip](https://github.com/OpenShot/openshot-qt/files/2372466/openshot.zip)

create file __init__.py :
`sudo touch /usr/lib/python3.7/site-packages/openshot_qt/blender/scripts/openshot/__init__.py`

Import can be do like this into 3DTitleScript.py:

```
import bpy, os, sys
directory = os.path.dirname(bpy.data.filepath)[:-5] + 'scripts/openshot'
if not directory in sys.path:
    sys.path.append(directory)
from debug import print_error
```

And for use into  3DTitleScript.py:

```
#INJECT_PARAMS_HERE

# The remainder of this script will modify the current Blender .blend project
# file, and adjust the settings. The .blend file is specified in the XML file
# that defines this template in OpenShot.
#----------------------------------------------------------------------------

# Modify Text / Curve settings
try:
    …
    my blender code
    pirnt("bug") #error code
    …
except Exception as E:
    print_error(sys.exc_info(), str(E))

# Render the current animation to the params["output_path"] folder
bpy.ops.render.render(animation=params["animation"])
```

Now when we preview the image the blender errors of python commands are viewable by the user.

**Comment by ferdnyc** [comment]
Closing as unactionable, as @peanutbutterandcrackers indicated a PR would be considered for merge.
