### ISSUE TITLE
Title 3D no sound file support for blender plugins

### ISSUE THREAD

**Issue by Sefran007** [OpenShot/openshot-qt#2097]
**Is your feature request related to a problem? Please describe.**
Title 3D no sound file support for create blender plugins

**Describe the solution you'd like**
For blender plugins no possible sound file load. Need a xml tag sound for load sound file for blender.

**Describe alternatives you've considered**
I create sound load features with blender_listview.py
[blender_listview_sound.zip](https://github.com/OpenShot/openshot-qt/files/2384345/blender_listview_sound.zip)

With this patch we can test sound before select, clear selected file, etc…

I test with xml sample

```
    <param name="sound_files1" type="sound" title="Sound 1 Path" description="">
        <values>
            <value name="" num=""/>
        </values>
        <default>/goodpath/goodfile.mp3</default>
    </param>

    <param name="sound_files2" type="sound" title="Sound 2 Path" description="">
        <values>
            <value name="" num=""/>
        </values>
        <default>/goodpath/badfile.mp3</default>
    </param>

    <param name="sound_files3" type="sound" title="Sound 3 Path" description="">
        <values>
            <value name="/goodpath/badfile.mp3" num="0"/>
            <value name="goodfile.mp3" num="1"/>
            <value name="relativepath/goodfile.mp3" num="2"/>
            <value name="/goodpath/goodfile.mp3" num="3"/>
            <value name="/goodfile.mp3" num="4"/>
        </values>
        <default></default>
    </param>

    <param name="sound_files4" type="sound" title="Sound 4 Path" description="">
        <values>
            <value name="/goodpath/badfile.mp3" num="0"/>
            <value name="goodfile.mp3" num="1"/>
            <value name="/badrelativepath/goodfile.mp3" num="2"/>
            <value name="/badfile.mp3" num="3"/>
            <value name="/goodfile.mp3" num="4"/>
        </values>
        <default></default>
    </param>

    <param name="sound_files5" type="sound" title="Sound 5 Path" description="">
        <values>
            <value name="/goodpath/badfile.mp3" num="0"/>
            <value name="goodfile.mp3" num="1"/>
            <value name="relativepath/goodfile.mp3" num="2"/>
            <value name="/badfile.mp3" num="3"/>
            <value name="/goodfile.mp3" num="4"/>
        </values>
        <default>/goodpath/goodfile.mp3</default>
    </param>

    <param name="sound_files6" type="sound" title="Sound 6 Path" description="">
        <values>
            <value name="/goodpath/badfile.mp3" num="0"/>
            <value name="goodfile.mp3" num="1"/>
            <value name="relativepath/goodfile.mp3" num="2"/>
            <value name="/bidon.mp3" num="3"/>
            <value name="/goodfile.mp3" num="4"/>
        </values>
        <default>/goodpath/badfile.mp3</default>
    </param>

    <param name="sound_files7" type="sound" title="Sound 7 Path" description="">
        <values>
            <value name="/goodpath/badfile.mp3" num="0"/>
            <value name="goodfile.mp3" num="1"/>
            <value name="/badrelativepath/goodfile.mp3" num="2"/>
            <value name="/badfile.mp3" num="3"/>
            <value name="/goodfile.mp3" num="4"/>
        </values>
        <default>/goodpath/badfile.mp3</default>
    </param>

    <param name="sound_files8" type="sound" title="Sound 8 Path" description="">
        <values>
            <value name="" num=""/>
        </values>
        <default></default>
    </param>
```

**Comment by Sefran007** [comment]
Very better patch
[blender_listview_sound.zip](https://github.com/OpenShot/openshot-qt/files/2383553/blender_listview_sound.zip)

**Comment by peanutbutterandcrackers** [comment]
Again, my reply from https://github.com/OpenShot/openshot-qt/issues/2112#issuecomment-447329408:
> Wow! Neat! Sorry for the late reply but it's so cool that you have actually made a patch. However, a suggestion: Please make an Pull Request instead of submitting a patch like this. The reason being other contributors will be able to take a look at the diff, incrementally test your changes with each further change you make, provide you with constructive criticisms, suggestions, etc so that you could polish this code even further. It seems that this has somehow been lost in the pile of issues flooding the repo. Hope you can come around and make a PR soon! Thank you for doing your part to make OpenShot better!

**Comment by ferdnyc** [comment]
Closing as unactionable, as @peanutbutterandcrackers indicated a PR would be considered for merge. (Though, maybe not so much for this one. This particular patch makes no sense. Blender output is imported into OpenShot as a series of frame images (an Image Sequence), it _**can't have**_ an audio track. But an audio track can certainly be added on the OpenShot Timeline. What problem is this patch even trying to solve?)
