### ISSUE TITLE
Widgets missing on screen

### ISSUE THREAD

**Issue by LadyReader** [OpenShot/openshot-qt#2099]
<Deleting everything except the tracks on an untitled project>

I accidently deleted everything except the tracks where you can put videos... I can't preview the video, add transitions, or any of the cool stuff I could do at the beginning... I don't know how to fix my mistake!!! There is no clear "click this if all you got is tracks" button. I'm so lost and can't figure out what I need to do to get it fixed...

[At the top of my video editor screen it says: *Untitled Project {HDV 720 24p} - OpenShot Video Editor

**System Details**

![screen shot](https://user-images.githubusercontent.com/43193160/45398678-52ca9c80-b602-11e8-9b46-c2bf4787ab67.png)

**Comment by DylanC** [comment]
@LadyReader  - Use menu "View>>Views>>Simple View" to restore it.

**Comment by LadyReader** [comment]
Hey, do you know how I can fix the problem at all? If you do, that would be amazing thanks!!!!

**Comment by LadyReader** [comment]
I found the answer to my problem... All I had to do was click "Views" then click "Advanced Views".
