### ISSUE TITLE
Can't install in linux

### ISSUE THREAD

**Issue by thriftykapila** [OpenShot/openshot-qt#210]
Linux says that there is not any software to run executable files

**Comment by stephan75** [comment]
Sorry, but your error report is one of the worst one that a developer should deal with!

What Linux version you have exactly?

What file(s) you have downloaded exactly? an *.exe installer file??

Did you use any Linux package installer tool like synaptic or apt-get or similar?

**Comment by Kagetsuki** [comment]
@jonoomph I think this issue is stale and should be closed.

**Comment by JtLively** [comment]
If you have issues with a new installation, open a new issue along with OS/distro, version of Openshot, and details on errors - [OpenShot.org](http://openshot.org/download/)
