### ISSUE TITLE
Youtube

### ISSUE THREAD

**Issue by Sircaldinhas** [OpenShot/openshot-qt#2100]
**My Question: Hello I was wondering if this program (Openshot) can edit videos for Youtube if I was very grateful because nowadays it is very difficult to find such programs for Youtube.

**System Details**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**Comment by DylanC** [comment]
@Sircaldinhas - Yes, you can. All my YT videos online have been created with Openshot.
