### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by Sircaldinhas** [OpenShot/openshot-qt#2101]
**My Question: How do I speed up my video in only one part?

**System Details**
 - Operating System / Distro: [e.g. Windows 10, 
 - OpenShot Version [e.g. 2.4.1]

**Comment by ymollard** [comment]
With the **Scissors** tool, cut the start and end sides of the part you want to speed up. You end up with 3 parts.
Speed up the middle part to the desired speed. And then stick the right part to the middle one.
