### ISSUE TITLE
Audio waves on clips

### ISSUE THREAD

**Issue by BinaryVigilante** [OpenShot/openshot-qt#2102]
Hello!

I currently use Kdenlive for editing my videos, and one of the only reasons are that Kdenlive has audio waves on the clips. i.e. you can see the audio wave on the actual clip on the timeline.

Would this be a feature that could be implemented in openshot? 'cause I would love to use openshot for my video editing, but this feature is one of the things keeping me from using it :(

Have a great day/night! :D

**Comment by DylanC** [comment]
@BinaryVigilante - We do have this feature already but it is quite slow with large files. Right click audio track - Display >> Show waveform.

Are you saying the audio waveform shows on the video clip? If so,  we don't have that feature yet.

**Comment by BinaryVigilante** [comment]
Hello! Thanks for the reply! I don't know if you just added this, but it's now there! :D
![image](https://user-images.githubusercontent.com/24778415/45519319-dd52fd80-b7b4-11e8-821d-d096da7a30c1.png)

If it's new, thank you very for this! I'm now able to use this as my new editor! :D
