### ISSUE TITLE
Clicks are heard, when mixing several audio tracks

### ISSUE THREAD

**Issue by MrMadguy64** [OpenShot/openshot-qt#2105]
**Example of bug**
https://dropmefiles.com/03PTf

**Describe the bug**
It's common task to make slide show + some videos and use mix of voice and music as background. Your program is very good for this task, but unfortunately I have to use external sound editor program in order to prepare whole sound track first and only then import it to OpenShot, due to really noticeable clicks, heard when I mix sound in OpenShot itself. Not only while editing video in OpenShot (Weak computer? Understandable. But both my computers aren't weak. 16GB RAM and I allowed OpenShot to use most of it in options), but, that is much more worse, when watching exported video in player (Shouldn't happen due to weak hardware). And of course this situation causes all kinds of timing problems.

It really sounds like bit capacity overflow, when shape of sound wave becomes clipped, when summary amplitude becomes way too high. It shouldn't happen, as it doesn't happen in any sound editor. So, while your program is great video editor (Except keyframe manual effects. Why it's so hard and not intuitive to do something simple like 1.5X faster video?), but extremely bad sound editor. 

**System Details (please complete the following information):**
 - Operating System / Distro: Windows 7 Pro/Home 64bit on Intel Core i7 + 16GB RAM
 - OpenShot Version: 2.4.2 (and all previous versions, I have been using).

**To Reproduce**
1. Import some voice, music and pictures
2. Make slide show, while mixing music and voice
3. Export video (I tried several formats, but standard Youtube HD 30FPS + MP3 - is mostly used).
4. Hear noticeable clicks, when amplitude of both voice and music becomes too high.

**Expected behavior**
Do the same in Audacity (except slide show of course) - you won't hear any clicks. Neither while editing sound in program itself, nor when sound is exported to, let's say, MP3.

**Screenshots**
None.

**Logs**
None.

**Additional context**
None.

**Comment by DylanC** [comment]
@MrMadguy64 - Try v2.4.3 and let us know if you still have a problem.

**Comment by MrMadguy64** [comment]
@DylanC - Unfortunately I still have this problem. I've tried different video formats - MP4, AVI. And therefore different audio formats (AAC, MP3), bitrates and sampling rates - I hear exactly the same clicks in absolutely all cases. The only improvement since older versions of OpenShot - I no longer hear them, while editing video in program. Only when I export. And again: I don't hear any problems, when I use voice without music or music without voice - I hear clicks, only when they're mixed.
