### ISSUE TITLE
Audio does not go through earphones only through laptop speakers

### ISSUE THREAD

**Issue by elemprendedoramazonico** [OpenShot/openshot-qt#2107]
**Describe the bug**
I can only hear the audio of my Project through the laptop speakers regardless of having earphones plugged in.

**System Details (please complete the following information):**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]: Windows 10
 - OpenShot Version [e.g. 2.4.1]: 2.4.2

**To Reproduce**
1. Add an audio file to the Project.
2. Plug your earphones.
3. Click play.
4. You won't hear the audio on your earphones but on your laptop's speakers.

**Expected behavior**
I expected the audio to go through the earphones.

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**

**Comment by peanutbutterandcrackers** [comment]
Probably related to #1559, #1390 and possibly #1505 and #1588 
Closing as duplicate for now as this issue does not bring any new information. Please follow the discussions over at the linked issues. Hope that'll help.
