### ISSUE TITLE
Using splitscreen with zoom and pan separately 

### ISSUE THREAD

**Issue by NGbuckliNG** [OpenShot/openshot-qt#2111]
Hi. I'm using OpenShot 2.4.2.

I'm trying to put two videos side-by-side using a splitscreen. So far I've used Properties > Layout > Show All (Distort). I've tried messing about with the Scale X, Scale Y, Location X and Location Y properties as well.

What I want to do is to use the Scale and Location properties separately for each clip, such that each clip stays on its half of the screen i.e. I'm zooming and panning for two separate clips and playing them side by side.

How can this be done?

Thanks.

**Comment by peanutbutterandcrackers** [comment]
Step 1: If you aren't comfortable with using OpenShot's keyframe-prowess, please go through [this guide](https://gist.github.com/peanutbutterandcrackers/f0f666243133e0ed25abbc12a4ba23d7).
Step 2: Put 2 clips that you plan on splitting on top of each other on separate tracks.
Step 3: Apply Crop effect on the uppermost clip. Split the video vertically in half.
Step 4: In step 3, you'll realize that the subject might be cropped, at this point, remove the crop effect (after noting the parameters), insert shift effect, shift the effect in x axis, and then apply the crop effect.
Step 5: Shift the bottom footage as needed.

Done!

To add panning, keyframe the  Location parameters of both the clips.

Hope that helps!

Closing as answered. If you need further help, please do comment/re-open/etc.
