### ISSUE TITLE
Title 3D font load file broken for blender plugins

### ISSUE THREAD

**Issue by Sefran007** [OpenShot/openshot-qt#2112]
Is your feature request related to a problem? Please describe.
Title 3D as no font file load support and font load file broken for blender plugins.
Only BFONT select is possible.

Describe the solution you'd like
For blender plugins no possible font file load. Need a xml tag font for load font file for blender plugin.

Describe alternatives you've considered
I create font load features with blender_listview.py
[blender_listview_font.zip](https://github.com/OpenShot/openshot-qt/files/2383460/blender_listview_font.zip)

With this patch we can test font before select, clear selected file, etc…

I test with xml sample :
    <param name="font_files1" type="font" title="Font 1 Path" description="">
        <values>
            <value name="" num=""/>
        </values>
        <default>/goodpathl/font.ttf</default>
    </param>

    <param name="font_files2" type="font" title="Font 2 Path" description="">
        <values>
            <value name="" num=""/>
        </values>
        <default>/goodpath/badfont.ttf</default>
    </param>

    <param name="font_files3" type="font" title="Font 3 Path" description="">
        <values>
            <value name="/goodpath/badfont.ttf" num="0"/>
            <value name="goodfile.ttf" num="1"/>
            <value name="~/goodrelativepath/goodfont.ttf" num="2"/>
            <value name="/goodpath/goodfont.ttf" num="3"/>
            <value name="/goodfont.ttf" num="4"/>
        </values>
        <default></default>
    </param>

    <param name="font_files4" type="font" title="Font 4 Path" description="">
        <values>
            <value name="/goodpath/badfont.ttf" num="0"/>
            <value name="goodfont.ttf" num="1"/>
            <value name="/badrelative/goodfont.ttf" num="2"/>
            <value name="/badfont.ttf" num="3"/>
            <value name="/goodfont.ttf" num="4"/>
        </values>
        <default></default>
    </param>

    <param name="font_files5" type="font" title="Font 5 Path" description="">
        <values>
            <value name="/goodpath/badfile.avi3" num="0"/>
            <value name="goodfile.ttf" num="1"/>
            <value name="~/goodrelative/goodfont.ttf" num="2"/>
            <value name="/badfont.ttf" num="3"/>
            <value name="/goodpath/goodfont.ttf" num="4"/>
        </values>
        <default>/goodpath/goodfont.ttf</default>
    </param>

    <param name="fonte_files6" type="font" title="Font 6 Path" description="">
        <values>
            <value name="/goodpath/badfont.ttf" num="0"/>
            <value name="goodfont.ttf" num="1"/>
            <value name="goodrelative/goodfont.ttf" num="2"/>
            <value name="/badfont.ttf" num="3"/>
            <value name="/goodfont.ttf" num="4"/>
        </values>
        <default>/goodpath/badfont.ttf</default>
    </param>

    <param name="font_files7" type="font" title="Font 7 Path" description="">
        <values>
            <value name="/goodpath/badfont.ttf" num="0"/>
            <value name="goodfont.ttf" num="1"/>
            <value name="/badrelative/goodfont.ttf" num="2"/>
            <value name="/badfont.ttf" num="3"/>
            <value name="/goodfont.ttf" num="4"/>
        </values>
        <default>/goodpath/badfont.ttf</default>
    </param>

    <param name="font_files8" type="font" title="Font 8 Path" description="">
        <values>
            <value name="" num=""/>
        </values>
        <default></default>
    </param>

**Comment by peanutbutterandcrackers** [comment]
Wow! Neat! Sorry for the late reply but it's so cool that you have actually made a patch. However, a suggestion: Please make an Pull Request instead of submitting a patch like this. The reason being other contributors will be able to take a look at the diff, incrementally test your changes with each further change you make, provide you with constructive criticisms, suggestions, etc so that you could polish this code even further. It seems that this has somehow been lost in the pile of issues flooding the repo. Hope you can come around and make a PR soon! Thank you for doing your part to make OpenShot better!

**Comment by ferdnyc** [comment]
Closing as unactionable, as @peanutbutterandcrackers indicated a PR would be considered for merge.
