### ISSUE TITLE
Title 3D no file load support for blender plugins

### ISSUE THREAD

**Issue by Sefran007** [OpenShot/openshot-qt#2113]
Is your feature request related to a problem? Please describe.
Title 3D as no file load support for create blender plugins

Describe the solution you'd like
For blender plugins no possible file load from openshot or other. Need a xml tag file for load file for blender plugin.

Describe alternatives you've considered
I create load file features with blender_listview.py
[blender_listview_file.zip](https://github.com/OpenShot/openshot-qt/files/2383483/blender_listview_file.zip)

With this patch we can load relative file from openshot_path/blender with ':' caracter.

I test with xml sample :
    <param name="file_files1" type="file" title="File 1 Path" description="">
        <values>
            <value name="" num=""/>
        </values>
        <default>~/goodrelativepath/goodfile.ext</default>
    </param>

    <param name="file_files2" type="file" title="File 2 Path" description="">
        <values>
            <value name="" num=""/>
        </values>
        <default>~/goodrelativepath/badfile.ttf</default>
    </param>

    <param name="file_files3" type="file" title="File 3 Path" description="">
        <values>
            <value name="~/goodrelativepath/badfile.ttf" num="0"/>
            <value name=":icons/colors.png" num="1"/>
            <value name="~/goodrelativepath/goodfile.ext" num="2"/>
            <value name="/goodpath/goodfile.ext" num="3"/>
            <value name=":earth/clouds.jpg" num="4"/>
        </values>
        <default></default>
    </param>

    <param name="file_files4" type="file" title="File 4 Path" description="">
        <values>
            <value name="/goodpath/badfile.ttf" num="0"/>
            <value name="icons/colors.png" num="1"/>
            <value name="/badpath/goodfile.ext" num="2"/>
            <value name="/badfile.txt" num="3"/>
            <value name="/goodfile.ext" num="4"/>
        </values>
        <default></default>
    </param>

    <param name="file_files5" type="file" title="File 5 Path" description="">
        <values>
            <value name="~/goodrelative/badfile.ttf" num="0"/>
            <value name=":icons/colors.png" num="1"/>
            <value name="~/goodreladive/goodfile.ext" num="2"/>
            <value name="/goodpath/goodfile.ext" num="3"/>
            <value name=":earth/clouds.jpg" num="4"/>
        </values>
        <default>/goodpath/goodfile.ttf</default>
    </param>

    <param name="filee_files6" type="file" title="File 6 Path" description="">
        <values>
            <value name="~/goodrelative/badfile.ttf" num="0"/>
            <value name=":icons/colors.png" num="1"/>
            <value name="~/goodrelative/goodfile.ext" num="2"/>
            <value name="/goodpath/goodfile.ext" num="3"/>
            <value name=":earth/clouds.jpg" num="4"/>
        </values>
        <default>/goodpath/badfile.ttf</default>
    </param>

    <param name="file_files7" type="file" title="File 7 Path" description="">
        <values>
            <value name="/goodpath/badfile.ttf" num="0"/>
            <value name="icons/colors.png" num="1"/>
            <value name="/badpath/goodfile.ext" num="2"/>
            <value name="/badfile.txt" num="3"/>
            <value name="/goodfile.ext" num="4"/>
        </values>
        <default>/goodpath/badfile.ttf</default>
    </param>

    <param name="file_files8" type="file" title="File 8 Path" description="">
        <values>
            <value name="" num=""/>
        </values>
        <default></default>
    </param>

**Comment by peanutbutterandcrackers** [comment]
Again, my reply from https://github.com/OpenShot/openshot-qt/issues/2112#issuecomment-447329408:
> Wow! Neat! Sorry for the late reply but it's so cool that you have actually made a patch. However, a suggestion: Please make an Pull Request instead of submitting a patch like this. The reason being other contributors will be able to take a look at the diff, incrementally test your changes with each further change you make, provide you with constructive criticisms, suggestions, etc so that you could polish this code even further. It seems that this has somehow been lost in the pile of issues flooding the repo. Hope you can come around and make a PR soon! Thank you for doing your part to make OpenShot better!

**Comment by ferdnyc** [comment]
Closing as unactionable, as @peanutbutterandcrackers indicated a PR would be considered for merge.
