### ISSUE TITLE
Cannot Import MP4s? (RESOLVED)

### ISSUE THREAD

**Issue by DecalsIAm** [OpenShot/openshot-qt#2114]
Doesn't matter the quality of the video, if it is an mp4 video, it will not import. Did I miss something in the program description that it doesn't work for mp4s?

Windows 10
OpenShot Version 2.4.2

**Comment by DylanC** [comment]
@DecalsIAm - Try v2.4.3 and let us know if you still have an issue.

**Comment by DylanC** [comment]
@jonoomph @peanutbutterandcrackers @ferdnyc - This seems to be the first instance of import issues regarding mp3/mp4. I have linked all of the dups to this original one and updated the priority list I have here:
https://gist.github.com/DylanC/73ecfa2f6f99fd7828604e4f8b65bb3f

**Comment by DecalsIAm** [comment]
I don’t use the portable app.

**Comment by Pedals2Paddles** [comment]
First time using Open Shot.  Imported some mov files from an action camera, which worked fine.  Then imported two MP4 files from my phone, which has rendered the application totally unusable. it literally broke the app and cannot be recovered. The application crashed upon trying to play the files back.  And you can't even reopen the app because it gets stuck in some backup state.  Presumably, I have to delete application and start over.  So this is a non-starter for me and will have to use a different application.

**Comment by corelgott** [comment]
I'm also seeings openshot crash when trying to import a mp4 on OSX (High Sierra)

**Comment by oisinmulvihill** [comment]
First time user on OSX High Sierra (10.13.6) attemting to use OpenShot v2.4.4. Any attempt to import (drag-n-drop or import from menu) gopro generated mp4 files results in immediate crash. I can import images no problem. I tried converting the file with Quicktime to MOV format however this resulted in a crash as well :(

Its a shame as OpenShot looks like it has everything I need to move away from iMovie and much more.

**Comment by SuslikV** [comment]
@oisinmulvihill can you add your openshot log-file? Can you import images from the same location, with the same filename? What if you try to import some .mp3 files?

**Comment by oisinmulvihill** [comment]
I've tried openshot v2.4.4 on a new macbook air running OSX Mojave (10.14.3). It works out of the box with the same gopro created mp4s.

On my OSX 10.13 machine, I can import images from the same directory. I haven't tried importing if they have the same filename. I try this evening along with some mp3s and see what happens.

I had a look at the osx logging console to see if I could catch errors/logs but nothing came up. Where do I find the openshot log?

**Comment by oisinmulvihill** [comment]
Ah, I see where to get logs https://github.com/OpenShot/openshot-qt/blob/develop/CONTRIBUTING.md

**Comment by SuslikV** [comment]
@oisinmulvihill there is typo in the mentioned file, the log's name now is `openshot-qt.log` ("-" instead of underline, but folder's name is still uses underline)

**Comment by oisinmulvihill** [comment]
Attached are the logs:

[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/3144429/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/3144430/openshot-qt.log)

**Comment by SuslikV** [comment]
@oisinmulvihill Please, try to open the files via main menu _File > Import Files... (CTRL+F)_. Then try to drag-n-drop from path (and filename) with no spaces in it (from the root directory, maybe right from the "Desktop" folder). Any changes?

Can you post the log from OSX Mojave (10.14.3) as well? It may help developers to compare the results, because logs is not very useful. Maybe bug somewhere with Qt.

**Comment by JerseyMutt** [comment]
Not my first time using OpenShot. First used it a few months ago in Linux Mint 19.1 and it worked great. Came back to it again this week and find that it works fine when I import video (mp4s included), but the minute I try and upload an mp3, it crashes. I've tried importing from both the menu and dragging/dropping. I'm also using the latest appimage  (downloaded today) and am still having the same issue. FWIW, the same problem is also present when trying to use OpenShot on my Windows 10 VM. My logs from my Linux box are attached (deleted the older ones about 20 minutes ago before making another attempt).

[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/3168058/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/3168059/openshot-qt.log)

**Comment by SuslikV** [comment]
@JerseyMutt Can you check what kind of .mp3 is crashes for you? Maybe the ones that has embedded images? Like in this thread - https://github.com/OpenShot/openshot-qt/issues/2756#issuecomment-487876270 Or any?

**Comment by jackhagley** [comment]
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/3591258/openshot-qt.log)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/3591259/libopenshot.log)
Same issue on 10.13.6
Crashes on import

**Comment by mikelacsa** [comment]
From PVH-GiantGuy on issue [2307](https://github.com/OpenShot/openshot-qt/issues/2307) Describe the bug
Openshot immediately closes when I import video or audio files (I know this is not a new issue, but wanted to add one more account of it)

System Details (please complete the following information):

Operating System: macOS 10.13.6
OpenShot Version: 2.4.3
To Reproduce
Steps to reproduce the behavior:

Built a project folder and included video files (mp4 and wmv), photos (png) and audio files (mp3)
Launched OpenShot video editor and saved the .osp OpenShot Project to the project folder
Imported 2 photo files
Tried to import a video file.
OpenShot application quits
No error message or error log
Tried this 3 times; same result each time
