### ISSUE TITLE
.osp issues.

### ISSUE THREAD

**Issue by UpriseNova** [OpenShot/openshot-qt#2117]
**Describe the bug**
I decided to go and save my project that I made by going to the top left and clicking on "File" then going to "Save As" to save my project. It made a bunch of folders with all the components that I used to make my project. One of the files was a .osp file. When I went onto OpenShot I wanted to access the project I worked on for 6 hours straight. It said that I had to open my project with a .osp file. I did so and the program started popping up a bunch of messages saying that the components that I used for my project are not on my computer. It would then ask me to go to the folder that those components are located in. I went into the folder where the components are located in and they were not there. It was like as if they disappeared. I went back onto my desktop to make sure that they are on my computer, and they were sitting there in the folder. I closed off OpenShot and re opened it with my other folder with my components open. I decided to try to open my .osp file again. It asked me for the missing file and when it did so I grabbed the missing file and dropped it in where it said that there was nothing. A couple seconds later after I drop the file into the empty folder, it gets deleted. I tried searching on my computer for that file and it was gone. It got deleted. I have everything else besides that one file (it was a song file). I also tried putting all of the components in the folders that are attached to the program... but those all got deleted, so now they're empty.

**System Details (please complete the following information):**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1] Windows 10
 - OpenShot Version [e.g. 2.4.1] I'm using the latest version of OpenShot. Whatever version was being used during 9/15/18 is the one im using.

**To Reproduce**
1. Open up OpenShot
2. Click on the tab listed as "File" on the top left.
3. Click on the option listed as "Open Project..."
4. Find the .osp file and open it. 
5. Get message saying that a file is missing.
**Expected behavior**
I expected to be reunited to my hard dedication also known as my project.

**Screenshots**
https://www.dropbox.com/s/qrow3jphust8udk/OpenShot%20not%20working%20V2.PNG?dl=0
https://www.dropbox.com/s/qze3lvd5b4xa2qx/OpenShot%20not%20working%20V1.PNG?dl=0 

**Logs**
I'm not experiencing any crashes.

**Additional context**
Nothing else really.

**Comment by DylanC** [comment]
@UpriseNova - Try v2.4.3 and let us know if you still have a problem.

**Comment by peanutbutterandcrackers** [comment]
As far as the missing files are concerned, first, switch to a latest daily build. A fix has gone in recently which will make it possible for one to easily point OpenShot to missing files. Once you have the daily build running, try opening the `.osp` file and when it complains it can't find certain files, point towards the folder that contains those files and it should work. Hope that helps.
