### ISSUE TITLE
preview quality is better than export quality

### ISSUE THREAD

**Issue by JeniMojo** [OpenShot/openshot-qt#2118]
**My Question:**

Hi! so whenever I'm editing a video the preview quality is amazing but when I go to export it is a bit blurry. is there a way I can fix this? or am I doing something wrong?

**System Details**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**Screenshots**

**Comment by DylanC** [comment]
@JeniMojo - What resolution is the source video and/or pictures? You might be exporting to HD when the source put in is not high enough quality.
