### ISSUE TITLE
Where is the (File Edit Title View Help) Menu

### ISSUE THREAD

**Issue by dmullinax** [OpenShot/openshot-qt#212]
I am running the latest version of Ubuntu 14.04 LTS in the gnome compiz environment.  I followed the directions on the PPA to download the latest version here: http://www.openshot.org/ppa/

I did not uninstall the old version 1.4.3.  Should I have?

I am missing the (File Edit Title View Help) menu.  So how do I get to the title menu to create an SVG?

I can import an SVG like I could the previous version, but the formatting is not carried over.  Also when I right-click on an SVG file, I am missing the context menu options 
Edit Title (Simple) 
Edit Tile (Inkscape).

Also when I play the video in preview mode, it drags unlike the other version.  I was hoping that this version will solve the sync issue I was having when editing avi files downloaded from my Cannon Powershot.  Well first things first.  Where is my menu?

**Comment by edwin-oetelaar** [comment]
export QT_QPA_PLATFORMTHEME=

/usr/bin/openshot-qt

helps for me.

**Comment by dmz006** [comment]
Any more "permanent" solution?

**Comment by maetamong** [comment]
Actually, I have the same problem.
I am running Openshot 2.0.7 on Mint 17.3.
I 'd like to import my copied SVG file and then edit it.
But I can't find the menu for editing.

And I  tried to run openshot with a script like the above. 
But it doesn't work.

**Comment by dmz006** [comment]
I just upgraded to ubuntu 16 and something must have cleared out or reinstalled because now the menus are all showing fine.

**Comment by jonoomph** [comment]
Yeah, this is a bug in Ubuntu. I don't remember the package name, but it's the one that finds the main menu in a Qt Application, and moves it to the top of the screen. Nothing to fix in OpenShot unfortunately. Thanks!

**Comment by ankitpati** [comment]
`appmenu-qt` is the culprit.

**Comment by BarbzYHOOL** [comment]
I guess I have the same problem and I don't want to use the appimage because I guess it's slower and also because I can't use my custom fonts for animated titles with that appimage file
