### ISSUE TITLE
Error when opening .OSP file

### ISSUE THREAD

**Issue by ikcuts** [OpenShot/openshot-qt#2120]
I try to open a saved file that I previously have been able to open, but I get an error message of "invalid load key '\x00'"

I uninstalled OpenShot and I am now downloading it again.

**Comment by DylanC** [comment]
@ikcuts - What version of OpenShot?

**Comment by peanutbutterandcrackers** [comment]
Well, I suspect the `.osp` file has become corrupted, for some reason; but I am not sure. Perhaps you might want to try [the latest daily build](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914) and see if they can do the trick. Also, deleting `.openshot_qt` folder from your home directory might be worth a shot, too.

**Comment by DylanC** [comment]
@ikcuts - Try v2.4.3 and let us know if you still have a problem. I would recommend to start a new project as it sounds your file has been corrupted.
