### ISSUE TITLE
Qt5.11 Compatibility

### ISSUE THREAD

**Issue by antonino-tocco** [OpenShot/openshot-qt#2121]
**My Question:**
Qt5.11 Compatibility

Hi, it is possible to run openshot-qt with Qt5.11 ? If there is incompatibility with code, which modules/files can I fix and how?

**System Details**
 - Operating System / Distro: Ubuntu / MacOS
 - OpenShot Version: Latest Develop

**Comment by peanutbutterandcrackers** [comment]
I don't remember anybody trying that out, yet. Perhaps you could test it out, good sir.

**Comment by DylanC** [comment]
@antonino-tocco - I can try to build it with Qt5.11. I would imagine it should work.

**Comment by eszlari** [comment]
The flatpak version is built against Qt 5.11:
https://flathub.org/apps/details/org.openshot.OpenShot

**Comment by DylanC** [comment]
@antonino-tocco - Your question has been answered. I would assume no real fixes are required.
