### ISSUE TITLE
Title 3D inutile verbose output when render pictures

### ISSUE THREAD

**Issue by Sefran007** [OpenShot/openshot-qt#2123]
**Describe the bug**
Output console message on preview title 3D render
```
blender_listview:INFO init_slider_values
blender_listview:INFO sliderPreview_valueChanged: 1
blender_listview:INFO sliderPreview_valueChanged: 125
blender_listview:INFO btnRefresh_clicked
blender_listview:INFO QThread Render Method Invoked
blender_listview:INFO Blender command: /usr/bin/blender -b '/usr/lib/python3.7/site-packages/openshot_qt/blender/blend/fly_by_two_titles.blend' -P '/home/franc/.openshot_qt/blender/ec1dafac-ba54-11e8-b7e5-a64af601b8d6/fly_by_two_titles.py'
blender_listview:INFO preview_timer_onTimeout
blender_listview:INFO ***** End preview_timer_onTimeout *****
blender_listview:INFO Image detected from blender regex: []
---
blender_listview:INFO Image detected from blender regex: []
blender_listview:INFO Image detected from blender regex: [('/home/franc/.openshot_qt/blender/ec1dafac-ba54-11e8-b7e5-a64af601b8d6/TitleFileName0125.png', '')]
blender_listview:INFO Image detected from blender regex: []
---
blender_listview:INFO Image detected from blender regex: []
blender_listview:INFO Blender render thread finished
```

**System Details (please complete the following information):**
Manjaro Linux 4.17.17-1-MANJARO #1 SMP PREEMPT x86_64 GNU/Linux
Installation method Pacman/Yaourt
Openshot 2.4.2
melt 6.10.0
Blender 2.79 (sub 0)

**To Reproduce**
1: Open bash termimal and launch openshot-qt
2: Open a preview Title 3D

**Expected behavior**
The result log like this :

```
blender_listview:INFO init_slider_values
blender_listview:INFO sliderPreview_valueChanged: 1
blender_listview:INFO sliderPreview_valueChanged: 125
blender_listview:INFO preview_timer_onTimeout
blender_listview:INFO QThread Render Method Invoked
blender_listview:INFO Blender command: /usr/bin/blender -b '/usr/lib/python3.7/site-packages/openshot_qt/blender/blend/fly_by_two_titles.blend' -P '/home/franc/.openshot_qt/blender/af91a7d4-ba6b-11e8-95de-a64af601b8d6/fly_by_two_titles.py'
blender_listview:INFO Image detected from blender regex: [('/home/franc/.openshot_qt/blender/af91a7d4-ba6b-11e8-95de-a64af601b8d6/TitleFileName0125.png', '')]
blender_listview:INFO Blender render thread finished
```

**Screenshots**
None

**Logs**
```
blender_listview:INFO init_slider_values
blender_listview:INFO sliderPreview_valueChanged: 1
blender_listview:INFO sliderPreview_valueChanged: 125
blender_listview:INFO btnRefresh_clicked
blender_listview:INFO QThread Render Method Invoked
blender_listview:INFO Blender command: /usr/bin/blender -b '/usr/lib/python3.7/site-packages/openshot_qt/blender/blend/fly_by_two_titles.blend' -P '/home/franc/.openshot_qt/blender/ec1dafac-ba54-11e8-b7e5-a64af601b8d6/fly_by_two_titles.py'
blender_listview:INFO preview_timer_onTimeout
blender_listview:INFO ***** End preview_timer_onTimeout *****
blender_listview:INFO Image detected from blender regex: []
---
blender_listview:INFO Image detected from blender regex: []
blender_listview:INFO Image detected from blender regex: [('/home/franc/.openshot_qt/blender/ec1dafac-ba54-11e8-b7e5-a64af601b8d6/TitleFileName0125.png', '')]
blender_listview:INFO Image detected from blender regex: []
---
blender_listview:INFO Image detected from blender regex: []
blender_listview:INFO Blender render thread finished
```

**Additional context**
A patch for correct this.
[blender_listview_verbose.zip](https://github.com/OpenShot/openshot-qt/files/2388418/blender_listview_verbose.zip)

**Comment by peanutbutterandcrackers** [comment]
Again, my reply from https://github.com/OpenShot/openshot-qt/issues/2112#issuecomment-447329408:
> Wow! Neat! Sorry for the late reply but it's so cool that you have actually made a patch. However, a suggestion: Please make an Pull Request instead of submitting a patch like this. The reason being other contributors will be able to take a look at the diff, incrementally test your changes with each further change you make, provide you with constructive criticisms, suggestions, etc so that you could polish this code even further. It seems that this has somehow been lost in the pile of issues flooding the repo. Hope you can come around and make a PR soon! Thank you for doing your part to make OpenShot better!

**Comment by mikelacsa** [comment]
The same was issue raised in [2148](https://github.com/OpenShot/openshot-qt/issues/2148)

**Comment by ferdnyc** [comment]
> The same issue was raised in [2148](https://github.com/OpenShot/openshot-qt/issues/2148)

By the same user, though that was actually a _slightly_ different issue. @Sefran007 dropped a bunch of patches into issues here at one point, which isn't how we handle code changes.

I'm going to close all of them as unactionable. As @peanutbutterandcrackers indicated, a PR would certainly be considered for merge.
