### ISSUE TITLE
Title 3d Openshot generates the same image twice

### ISSUE THREAD

**Issue by Sefran007** [OpenShot/openshot-qt#2124]
**Describe the bug**
When render freview image from title 3d, twice picture are generated.

I correct this with this patch:
[blender_listview_goodrenderpreview.zip](https://github.com/OpenShot/openshot-qt/files/2388514/blender_listview_goodrenderpreview.zip)

**System Details (please complete the following information):**
Manjaro Linux 4.17.17-1-MANJARO #1 SMP PREEMPT x86_64 GNU/Linux
Installation method Pacman/Yaourt
Openshot 2.4.2
melt 6.10.0
Blender 2.79 (sub 0)

**To Reproduce**
1. Open with bash terminal openshot
2. Générate preview of title 3d

**Expected behavior**
blender_listview:INFO init_slider_values
blender_listview:INFO sliderPreview_valueChanged: 1
blender_listview:INFO sliderPreview_valueChanged: 125
blender_listview:INFO preview_timer_onTimeout
blender_listview:INFO QThread Render Method Invoked
blender_listview:INFO Blender command: /usr/bin/blender -b '/usr/lib/python3.7/site-packages/openshot_qt/blender/blend/fly_by_two_titles.blend' -P '/home/franc/.openshot_qt/blender/51600940-ba74-11e8-b0f0-a64af601b8d6/fly_by_two_titles.py'
blender_listview:
blender_listview:INFO Image detected from blender regex: []
…
blender_listview:INFO Image detected from blender regex: []
INFO Image detected from blender regex: [('/home/franc/.openshot_qt/blender/51600940-ba74-11e8-b0f0-a64af601b8d6/TitleFileName0125.png', '')]
blender_listview:INFO Image detected from blender regex: []
…
blender_listview:INFO Image detected from blender regex: []
blender_listview:INFO Blender render thread finished
blender_listview:INFO onRenableInterface

**Screenshots**

**Logs**

```
blender_listview:INFO init_slider_values
blender_listview:INFO sliderPreview_valueChanged: 1
blender_listview:INFO sliderPreview_valueChanged: 125
blender_listview:INFO btnRefresh_clicked
blender_listview:INFO ***** end init_slider_values *****
blender_listview:INFO QThread Render Method Invoked
blender_listview:INFO preview_timer_onTimeout
blender_listview:INFO Blender command: /usr/bin/blender -b '/usr/lib/python3.7/site-packages/openshot_qt/blender/blend/fly_by_two_titles.blend' -P '/home/franc/.openshot_qt/blender/713f4840-ba54-11e8-8d00-a64af601b8d6/fly_by_two_titles.py'
blender_listview:INFO Image detected from blender regex: []
…
blender_listview:INFO Image detected from blender regex: []
blender_listview:INFO Image detected from blender regex: [('/home/franc/.openshot_qt/blender/713f4840-ba54-11e8-8d00-a64af601b8d6/TitleFileName0125.png', '')]
blender_listview:INFO Image detected from blender regex: []
---
blender_listview:INFO Image detected from blender regex: []
blender_listview:INFO Blender render thread finished
blender_listview:INFO onRenableInterface
blender_listview:INFO QThread Render Method Invoked
blender_listview:INFO Blender command: /usr/bin/blender -b '/usr/lib/python3.7/site-packages/openshot_qt/blender/blend/fly_by_two_titles.blend' -P '/home/franc/.openshot_qt/blender/713f4840-ba54-11e8-8d00-a64af601b8d6/fly_by_two_titles.py'
blender_listview:INFO Image detected from blender regex: []
---
blender_listview:INFO Image detected from blender regex: []
blender_listview:INFO Image detected from blender regex: [('/home/franc/.openshot_qt/blender/713f4840-ba54-11e8-8d00-a64af601b8d6/TitleFileName0125.png', '')]
blender_listview:INFO Image detected from blender regex: []
---
blender_listview:INFO Image detected from blender regex: []
blender_listview:INFO Blender render thread finished
blender_listview:INFO onRenableInterface
 main_window:INFO animated title add cancelled
preview_thread:INFO exiting thread
```

**Comment by peanutbutterandcrackers** [comment]
Hey there!

Sorry for the delay in replying.

Thank you for taking the time to report and actually fix, too.

Could you please submit a PR and not just a patch? That way, it'll be open for peer-review and discussions, too.

**Comment by Sefran007** [comment]
[blender_listview_goodrenderpreview.zip](https://github.com/OpenShot/openshot-qt/files/2394871/blender_listview_goodrenderpreview.zip)
 It's OK ?

**Comment by Sefran007** [comment]
> Hey there!
> 
> Sorry for the delay in replying.
> 
> Thank you for taking the time to report and actually fix, too.
> 
> Could you please submit a PR and not just a patch? That way, it'll be open for peer-review and discussions, too.

[blender_listview_goodrenderpreview.zip](https://github.com/OpenShot/openshot-qt/files/2394872/blender_listview_goodrenderpreview.zip)

It's OK ?

**Comment by peanutbutterandcrackers** [comment]
@Sefran007 - It might be. It might not be. I am not quite sure as I am not an expert. However, if you do make a Pull Request, other developers/contributors can come in and review your solution and give some constructive criticisms, suggestions, deductions, etc. which will help in making the patch even more polished. It'll help them to test it out as well. The current machine that I am using doesn't quite have the testing environment set up so I am unable to test it out for myself. However, @DylanC, Cap'n, could you perhaps take a look at this? Thanks!
