### ISSUE TITLE
when using transitions, when previewing. Openshot is auto close.

### ISSUE THREAD

**Issue by surahman99** [OpenShot/openshot-qt#2125]
**Describe the bug**
when using transitions, when previewing. Openshot is auto close.
whene xport transitional videos with all formats, openshot is auto close

**System Details (please complete the following information):**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1] WINDOWS 7 ULTIMATE
 - OpenShot Version [e.g. 2.4.1] OpenShot-v2.4.3-release-candidate-1537166623-x86_64 (newest Daily Build Installer) 

**Logs**
here
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2389416/openshot-qt.log)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/2389425/libopenshot.log)

**Additional context**

**Comment by Merino2017** [comment]
Hello, I have the same problem.  Just noticed yesterday...

**Comment by stamatisbreezer** [comment]
same problem with export a movie that has transitions, the program is auto-closing.
 when I remove transitions I can render my movie.

**Comment by DylanC** [comment]
@surahman99 - What format of files are you using? WMV?

**Comment by surahman99** [comment]
@DylanC 

I using YouTube HD, its crash
i Change to MP4 (h.264), crash too. I change to MP4 (mpeg4) also crash. I try to MPEG (mpeg2) and crash.

Buat when i remove transition, i can export project.

Thanks

**Comment by DylanC** [comment]
@surahman99 @Merino2017 @stamatisbreezer - Hey all. This bug should be fixed now in v2.4.3 official. Please give it a shot and report back here. Thanks.

**Comment by surahman99** [comment]
I did a quick test, and so far no problems. The transition run well, and the OpenShot did not auto close. I exported it and run wel tool. Thank you!

**Comment by DylanC** [comment]
@surahman99 - Woohoo! Great news! I made sure to notify the team about this bug before we release. Seems the fix is working nicely. 👍

**Comment by DylanC** [comment]
Dup of #2079
