### ISSUE TITLE
Opacity and Green screens

### ISSUE THREAD

**Issue by h00pak** [OpenShot/openshot-qt#2126]
**My Question:**

Can I overlay multiple video layers and adjust the opacity on each to merge them? Is there a feature that will allow me to use a green screen?
Thanks

**System Details**
 - Operating System / Distro: [MacOS High Sierra]
 - OpenShot Version [e.g. 2.4.2]

**Screenshots**

**Comment by peanutbutterandcrackers** [comment]
You are probably looking for [this](https://www.youtube.com/watch?v=2sushecqMs4&t=85s) and [this](https://www.openshot.org/user-guide/) and also [this, as a bonus](https://gist.github.com/peanutbutterandcrackers/f0f666243133e0ed25abbc12a4ba23d7).

**Comment by DylanC** [comment]
@h00pak - Follow advice given by @peanutbutterandcrackers
