### ISSUE TITLE
[Meta-Issue:] Promoting comments to new issues

### ISSUE THREAD

**Issue by ferdnyc** [OpenShot/openshot-qt#2127]
I happened to spot this in the options menu for one of my own comments, and discovered that it's available to _all_ users and on _all_ comments. Which is great, and finally provides something I'd suggested a few months back, which (at the time) wasn't possible. As [the GitHub Blog explains](https://blog.github.com/changelog/2018-09-13-open-a-new-issue-from-a-comment/), since last week, you can...

> ### Open a new issue from a comment
> Sometimes a conversation in an issue or a pull request can move off in a tangental [sic] direction. Now you can click Open new issue within the comment’s options menu to open a new issue which will include a reference to the original comment – helping you get the conversation back on track.

(That's the entire explanation, so no real reason to follow that link unless you want to. The only other thing there is a link to GitHub Help, which naturally hasn't yet been updated to even mention this feature.)
![image](https://user-images.githubusercontent.com/538020/45721723-3f29b380-bb77-11e8-8810-2d7fb1f96256.png)
So, that's something commenters on existing issues should be encouraged to use when appropriate, or it can be used directly by someone who wants to "adopt" an issue raised in a comment. Doesn't appear to be accessible on mobile, unless I'm missing something, but at least it's an option for some users.

**Comment by ferdnyc** [comment]
if I'd been really clever, I would've found that old suggestion comment, and used the new feature to create this issue. But that sounds like an awful lot of work, and... **#LAAAAAZY**

**Comment by DylanC** [comment]
@ferdnyc - This is really cool! 😎 Another reason to love GitHub.

**Comment by ferdnyc** [comment]
This was never actually an _issue_, so... closing.
