### ISSUE TITLE
Can you please add a function of making slide shows like imagination or ffdiaporama? So we can make videos from photos more conveniently.

### ISSUE THREAD

**Issue by linuxalex1** [OpenShot/openshot-qt#2128]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by peanutbutterandcrackers** [comment]
Hey there,

First and foremost, this kinda' does already exist. [This Video](https://youtu.be/VE6awGSr22Q?t=251) should help you out with that. If that is exactly what you need, then please do close this issue.

I hope that helps!
