### ISSUE TITLE
What's the best Openshot version for me?

### ISSUE THREAD

**Issue by Michaelbenky** [OpenShot/openshot-qt#2129]
**I downloaded the latest version of OpenShot but a when I open it, I receive a message that tells me that my OpenGL is not compatible. I downloaded an older version but once I open it, it crashes. I'd like to know what's the best version for me to download.**

**System Details**
 - Operating System: Windows 10 64-bit
 - OpenShot Version: Latest version on website.
 - CPU: Core 2 due (2.33 GHz)
 - RAM: 3 GB
 - Graphics card: 384 MB Intel.
 - Open GL version: 1.3

**Comment by Michaelbenky** [comment]
I know the answer now. It's version 2.2.0. I tried it and it works.

**Comment by DylanC** [comment]
@Michaelbenky - I wasn't sure of the answer. Thanks for the research. 👍
