### ISSUE TITLE
Program crashes repeatedly within a few minutes of starting the software at random points

### ISSUE THREAD

**Issue by etgohomeok** [OpenShot/openshot-qt#213]
The program is crashing within the first couple of minutes of using it, and it is never happening at a consistent point (it crashes at a different place in the same sequence of events every time). The text of the error message is:

> This application has requested the Runtime to terminate it in an unusual way.
> Please contact the application's support team for more information.

I am attempting to create a "Picture in Picture (PiP)" effect with two video clips. Unfortunately I cannot attach the exact video clips since they are for work, but they are from two different sources (one from OBS Studio and the other from my Android phone) and I have imported both of them into Handbrake and re-encoded them to have the same encoding (MP4, H.264 at 1080p with all default settings).

My sequence of events is:
1. Import both files into OpenShot.
2. Drag them onto two separate tracks.
3. Set Layout > 1/4 bottom right on the top track.
4. Perform a splice operation on both files with "Keep Right Side" enabled and drag both tracks to be aligned so that the two videos are synchronized.

And that is the farthest I've gotten before crashing. I've attached my log file. If it is necessary, I can take some more videos that do not have confidential information in them and upload them, however I cannot share the ones that are currently producing this crash.

I am using Windows 7 64-bit and I've tried the main 2.0.7 download as well as the 2.0.7-22 (April 25) build and they both are crashing.

![error](https://cloud.githubusercontent.com/assets/19737434/15792345/b11fdc8c-29aa-11e6-90fc-63d3ae588517.png)

[openshot-qt.zip](https://github.com/OpenShot/openshot-qt/files/298376/openshot-qt.zip)

**Comment by cyphunk** [comment]
I had the same issue on linux with version 1.4. And it's only gotten worse on 2.0. Not sure how to resolve this. I simply save the file after any tiny edit and then force quit the app when it locks up and reopen the file. A pain, but still, easier to use then lots of other stuff

**Comment by jonoomph** [comment]
We have recently made a ton of improvements for video freezing and crashes, and I would like to verify this issue still occurs with our latest daily build. Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot. 

If the issue still occurs, please reopen this issue and attach log files (https://github.com/OpenShot/openshot-qt/blob/master/.github/CONTRIBUTING.md), and hopefully we'll be able to nail this down and fix it. Thanks!
