### ISSUE TITLE
audio clip stops when reaches an image

### ISSUE THREAD

**Issue by demsav** [OpenShot/openshot-qt#2131]
**My Question:**
Hi audio clip sound stops when reaches every image in a sequence of images in a different track from the one the audio clip is located and then it restarts . How do i solve this?
thanks. 

**System Details**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**Screenshots**

**Comment by DylanC** [comment]
@demsav - If the audio clip has an image/album art I would recommend to remove it.
