### ISSUE TITLE
removing black boarders from a video

### ISSUE THREAD

**Issue by YMA1983** [OpenShot/openshot-qt#2132]
**My Question:**
Hi,

how can I remove the black borders from a video I am trying to create?
![capture](https://user-images.githubusercontent.com/33132761/45832198-3cda6d00-bccf-11e8-89ef-56deec6dadac.PNG)

**System Details**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**Screenshots**

**Comment by N3WWN** [comment]
Try adjusting the `Scale` property for the clip.  IIRC, `Stretch` scaling will fill the screen with your clip, although the aspect ratio will likely be off.
