### ISSUE TITLE
Effects Preview differs a lot compared to the exported video

### ISSUE THREAD

**Issue by jongleur1983** [OpenShot/openshot-qt#2133]
**Describe the bug**
Added a clip to a project, added Animate/Zoom to start and middle of that clip.
Using the preview in OpenShot the clip is animated - zooms out and in again.
The exported file ~~(indepentend of format/resolution)~~ only contains the first part of that animation, zooming out.

It seems to be relevant to change the output format or resolution, probably after applying the effects.

**System Details (please complete the following information):**
 - Operating System / Distro: Windows 10
 - OpenShot Version ~~2.4.2~~ 2.4.3

**To Reproduce**
1. Create a project
2. Add a clip to it
3. Apply effects (in my case it was a zoom effect)
4. View the preview in OpenShot
5. Export in a format that's not pre-selected (in my case the original clip was 1920p60, output format 4K UHD60 MP4)
6. Compare exported file to preview: effects missing partially or completely.

**Expected behavior**
Preview and exported video should match.

**Screenshots**
00:05:19 - preview screen
![grafik](https://user-images.githubusercontent.com/2063360/45901212-7a7bea80-bde2-11e8-83fa-14a184e5e778.png)

00:07:07 - preview screen
![grafik](https://user-images.githubusercontent.com/2063360/45901252-95e6f580-bde2-11e8-9d94-94b0759e6318.png)

00:08:21 - preview screen:
![grafik](https://user-images.githubusercontent.com/2063360/45901267-a8f9c580-bde2-11e8-9ea9-e5d64311e7ec.png)

00:05 - playback of exported file in VLC:
![grafik](https://user-images.githubusercontent.com/2063360/45901352-ee1df780-bde2-11e8-86c3-cd993079a8d9.png)

00:07 - playback of exported file in VLC:
![grafik](https://user-images.githubusercontent.com/2063360/45901390-07bf3f00-bde3-11e8-8167-c71ba4174890.png)

00:08 - playback of exported file in VLC:
![grafik](https://user-images.githubusercontent.com/2063360/45901423-202f5980-bde3-11e8-880f-12d32298ba1f.png)

The osp files content can be seen at https://gist.github.com/jongleur1983/6c16c5e3a6251153a73ab1b26df17358

**Additional context**
If the complete project is required to reproduce I could provide it as well but it's 200MB of video files, so probably not the best idea if it's not needed.

**Comment by DylanC** [comment]
@jongleur1983 - Can you try v2.4.3 and let us know if you still have an issue?

**Comment by jongleur1983** [comment]
@DylanC error still persists, but reproduction is a little bit harder (and probably that was the case before as well):
Exporting the project in FullHD (mp4, HD, 25fps) works correctly, changing the export format to 4K UHD 60fps the problem persists - in this case no effects are applied to the exported video at all.

**Comment by DylanC** [comment]
@jongleur1983 - Well it sucks you still have a problem but at least its a bit better. :laughing:

**Comment by DylanC** [comment]
@jongleur1983 - I think you need to be editing in the profile you plan to export in. (Only mentioned this in case you are changing that profile during editing)

**Comment by jongleur1983** [comment]
@DylanC thanks, going to try it out in the next days, just to be sure, BUT: if that's the case, I still consider it a bug that it's possible to change the profile on export when that may produce unpredictable and different results.
On top of that this would exclude the quite common use case to export the same project to different target formats while minimizing quality loss compared to the original sources.

**Comment by DylanC** [comment]
@jongleur1983 - I think we tried to address this before #1557 but we never decided if that kind of fix was really a good idea. I have a new idea for the fix and maybe I'll chat with @N3WWN about it.

**Comment by jongleur1983** [comment]
@DylanC that seems to work - but it's far from ideal:
1) it's not even the same profile selection on export as on project creation.
2) it's possible without any hint to select a different profile. If changing the format here I IMHO should at least get a warning about the risk to get wrong results. In fact I should get this information when creating a project already at best.
