### ISSUE TITLE
Ubuntu 16.04LTS AppImage problem

### ISSUE THREAD

**Issue by Ausrpned** [OpenShot/openshot-qt#2139]
Following instruction on the Getting started guide, the Linux (64-bit AppImage) just yields more  AppImage files.

???

Cheers

**Comment by DylanC** [comment]
@Ausrpned - Can you explain what you did and what version of OpenShot?

**Comment by DylanC** [comment]
@Ausrpned - You need to right click and make the AppImage executable to use in the file properties. Hopefully this answers your (vague) question. 👍
