### ISSUE TITLE
Titles mixed up and/or missing

### ISSUE THREAD

**Issue by ThailandSteve** [OpenShot/openshot-qt#2140]
**Describe the bug**
I am inserting titles as my video progresses, every time I save and close, then open again the titles are all mixed up and missing, its driving me crazy.....whats happening?

**System Details (please complete the following information):**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**

**Comment by DylanC** [comment]
@ThailandSteve - Try v2.4.3 and let us know if you still have a problem.

**Comment by ThailandSteve** [comment]
Yes, problem solved! Also the programme was freezing and closing a lot, I
thought it was my pc but it is working great now, not one crash in 4 hours.

Cheers

Steve

**Comment by DylanC** [comment]
@ThailandSteve - Excellent, glad to hear it! 👍
