### ISSUE TITLE
Videos export as low quality video and audio pieces of poop.

### ISSUE THREAD

**Issue by lxlMlgGamerlxl** [OpenShot/openshot-qt#2141]
Not sure if I'm doing something wrong or something, but it's like it's an old 2009 youtube tutorial. Audio is super compressed and peaking too.

**Comment by ferdnyc** [comment]
You're doing something wrong.

(What, I can't say, because you provided no information whatsoever about your project setup, the input files you're using, what export preset you chose, and basically anything else that could possibly help us help you. So, you at _least_ did that wrong.)

**Comment by ferdnyc** [comment]
Also, dup of #2118 (right down to the exact same lack of useful information).

**Comment by lxlMlgGamerlxl** [comment]
> 
> 
> You're doing something wrong.
> 
> (What, I can't say, because you provided no information whatsoever about your project setup, the input files you're using, what export preset you chose, and basically anything else that could possibly help us help you. So, you at _least_ did that wrong.)

I've tried exporting as mp4 (both selections) and 1080p first 60 fps, then 30, then 29.something. I choose high quality every time.
