### ISSUE TITLE
Additional positioning accuracy required for high fps video (i.e. 240fps) 

### ISSUE THREAD

**Issue by N3WWN** [OpenShot/openshot-qt#2145]
**Describe the bug**
Right now, the positioning information is 2 digits to the right of the decimal so precision is 1/100th of a second.  With higher frame rates (ones in excess of 100fps), more precision is required.  For instance, there are 2.4 240fps frames that occur every 0.01s.

**System Details (please complete the following information):**
N/A

**To Reproduce**
N/A

**Expected behavior**
Position information needs to be stored with enough digits to position high-fps events accurately.  Probably 3 would be "okay" for 240 fps video (whose frames are 0.00416666.. in duration), but more wouldn't be a bad thing ;)

**Screenshots**
N/A

**Logs**
N/A

**Additional context**
At 100 fps or slower, this is not a problem and the existing 1/100s granularity is just fine.

**Comment by DylanC** [comment]
@N3WWN - Would you consider this a bug or enhancement?

**Comment by N3WWN** [comment]
@DylanC - Ummm... YES!  😜 

Probably an enhancement cuz nothing is actually broken, this would just allow improved positioning.

**Comment by N3WWN** [comment]
In addition to increasing the granularity of properties like position for high frame rate video (>100fps), we need to be able to see what frame we're presently viewing on the timeline.

At present, with 100 fps video, increasing frame-by-frame results in:
`00:00:00:98`
`00:00:00:99`
`00:00:00:00`
`00:00:01:01`

It should be (for 100fps video):

`00:00:00:98`
`00:00:00:99`
`00:00:00:100`
`00:00:01:01`

**Comment by N3WWN** [comment]
Confirmed that this is still needed in the most recent nightly build (April 26, 2021, 6:02 a.m.): https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.5.1-dev2-daily-7320-a00bbb76-503515e6-x86_64.dmg

**Comment by N3WWN** [comment]
Confirmed that this is still an issue with OpenShot-v2.6.1-dev-daily-8409-111026d8-73c519f0-x86_64.AppImage

**Comment by N3WWN** [comment]
Confirmed in OpenShot-v2.6.1-dev-daily-9348-04db6ce8-46255e46-x86_64.AppImage

Frame rates over 99 fps result in frame number display issues:

<img width="253" alt="image" src="https://user-images.githubusercontent.com/19431804/165593069-59ed4a54-aac5-412d-abf4-79df52e5d1b1.png">

**Comment by N3WWN** [comment]
I can confirm that this issue remains a problem in the latest daily builds

**Comment by Colorjet3** [comment]
Submitted this as an enhancement request:  https://trello.com/c/gNZo6VmP/126-additional-positioning-accuracy-required-for-high-fps-video-ie-240fps
