### ISSUE TITLE
Title 3d Openshot generate preview bug with blender locales

### ISSUE THREAD

**Issue by Sefran007** [OpenShot/openshot-qt#2148]
**Describe the bug**
When changing blender langage to french, from title 3d all render preview bug.

**System Details (please complete the following information):**
Manjaro Linux 4.17.17-1-MANJARO #1 SMP PREEMPT x86_64 GNU/Linux
Installation method Pacman/Yaourt
Openshot 2.4.2
melt 6.10.0
Blender 2.79 (sub 0)

**To Reproduce**
1. Select a different langage from blender and render
2. Render preview and generate from title 3d

**Expected behavior**
After preview picture from title 3d blender, when generate animation preview slide with render pictures.

**Screenshots**
none.

**Logs**
None (nothing).

**Additional context**
I do a patch to correct this bug.
[blender_listview_progress.zip](https://github.com/OpenShot/openshot-qt/files/2414762/blender_listview_progress.zip)

I add a progress render picture bar, and i correct sommes UTF-8 strings.

**Comment by speedytechdev** [comment]
Hi @Sefran007 thank you for letting us know about the issue. If your patch works we might be able to push it to our code.

**Comment by speedytechdev** [comment]
@DylanC ^^^

**Comment by jonoomph** [comment]
@Sefran007 Can you please email me: jonathan@openshot.org. I would love to work with you to incorporate these changes and invite you to our developer group chat. =)  Thanks!
