### ISSUE TITLE
Minor enhancement requests

### ISSUE THREAD

**Issue by IzzySoft** [OpenShot/openshot-qt#2149]
### Is your feature request related to a problem? Please describe.
These are just minor improvements I want to suggest – which hopefully are easy to implement and not requiring too much effort, but (at least in my opinion) would make working with OpenShot much easier.

### Describe the solution you'd like
**Asset View** (where the clips are imported to) in "details" view:

* next to each clip, it would be nice to see the length of it (video/audio)
* also nice, but less important: a column to place comments in
* if a clip is also present in the timeline, show that fact in the asset view (e.g. by overlaying a check-mark on the thumbnail). That way, when done, one can easily remove unused clips – or, after a "break", see where one has stopped (could also be done in thumbnail view)
* I'd also welcome being able to re-arrange the order of clips here (drag-and-drop, order by name, order by length)

**Timeline:**

* <s>true, there is a time scale ("ruler"). But it'd be nice to have the exact time of the "playhead" position – maybe next to the zoom slider, or next to the buttons of the video preview (as there's more space left)?</s> strike that, I was blind :fearful: It's already there (see comment below).
* could transitions indicate their direction (e.g. using an arrow pointing up/down)?
* this item probably leaves the "easy" category: could things like volume and brightness be indicated as overlay on the clip (e.g. by a line), and adjustments made possible by "dragging" that line? Example with volume: on a 10s clip, if I drag the volume line at 5s down to 50%, that would add a keyframe with the 50% volume – effectively making the volume start at 100%, going down to 50% at 5s (linear, not a "straight drop") and then up to 100% at 10s. Would especially helpful with brightness on clips where it "fluctuates".

**Misc**

* when adjusting e.g. size of an image or volume, I sometimes notice it implicitly sets a keyframe even if I want to apply the value to the entire clip. Could be my fault by "doing something wrong" (aka "user error"). To avoid that (making it easier to distinguish both cases), could there be a "properties pop-up" as it was in v1.x, where all changes then apply to the entire clip?

### Describe alternatives you've considered
I see none.

### Additional context
If I missed context, please let me know and I add it.

**Comment by ferdnyc** [comment]
> * true, there is a time scale ("ruler"). But it'd be nice to have the exact time of the "playhead" position – maybe next to the zoom slider, or next to the buttons of the video preview (as there's more space left)?

... ... ...You mean that giant time clock at the top left of the Timeline? :laughing: 

![openshot-playheadtimeindex](https://user-images.githubusercontent.com/538020/46255732-ff17da00-c46e-11e8-9540-36414afdfa80.png)

...Other than that, a bunch of good suggestions, thanks! Some of them are already on our radar, though of course it never hurts to know that more people would like to see the same things.

**Comment by IzzySoft** [comment]
@ferdnyc You mean I was blind all the time? :scream: How could that have happened? Yikes, OK, thanks and strike that from my list :ok_hand:
