### ISSUE TITLE
Can I use MP3 Audio files. When I tried this it was glitchy

### ISSUE THREAD

**Issue by lynnys** [OpenShot/openshot-qt#2154]
**My Question:**

**System Details**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**Screenshots**

**Comment by DylanC** [comment]
@lynnys - Try v2.4.3 and let us know if you still have a problem.

**Comment by Isolator70** [comment]
Hi, not sure if this the same issue if have also:
When I add a MP3 file with included **coverart** to openshot and play it (preview), my CPU is highly loaded/ maxed out. The playback is stuttering. Preview is not usable for me.
Workaround: When I remove the coverart from the MP3 file, everything is fine.

Maybe you could try it also and give feedback, thanks.

**Comment by lynnys** [comment]
I believe it is my graphics processor. I have a dedicated  video computer
on the way.
Thanks for the advice.
