### ISSUE TITLE
OpenShot failing to start under a standard account even if reinstalled

### ISSUE THREAD

**Issue by DanPinGF** [OpenShot/openshot-qt#2158]
**Describe the bug**
I have experienced this symptom before. It used to work under a standard account, but now after multiple crashes involving MSVCRT.DLL when attempting to apply "Time" to any video (see [#1197](https://github.com/OpenShot/openshot-qt/issues/1197) for more info), it is now refusing to launch due to a problem with the Python library.

**System Details (please complete the following information):**
 - Operating System / Distro: Windows 10
 - OpenShot Version 2.4.1+

**To Reproduce**
1. Within the Desktop, right-click on the OpenShot icon, if it's there already.
2. Click on 'Troubleshoot compatibility'.
3. Once you get into the Program Compatibility Troubleshooter, under the "Select troubleshooting option", click 'Troubleshoot program'.
4. Under the "What problems do you notice?" screen, select "The program require additional permissions". Once the checkbox has been filled, click 'Next'.
5. Click the button inside the troubleshooter to test the program.
6. A UAC box will appear asking you to enter the admin password. Fill that out, and hiter enter.

The program should work fine.

**Expected behavior**
Final attempts to restart OpenShot multiple times after hundreds of crashes fail as it will corrupt the Python library; the actual UI is replaced with an error message about "name 'exit' is not defined", which would completely brick OpenShot's normal operation and therefore cause it to turn incompatible with the PC. Simply reinstalling the program is not sufficient. You now need to run the program as an administrator in order to access OpenShot.

**Screenshots**
none

**Logs**
none

**Additional context**
none

**Comment by speedytechdev** [comment]
@DylanC This might make sense to you.

**Comment by DylanC** [comment]
@speedytechdev - It does but I don't know why anyone else doesn't seem to have this issue.

**Comment by DanPinGF** [comment]
@speedytechdev - Complete aspectitation. On the other hand, the bricking was due to a problem in the registry, which may be fixed if the Python interpreter was installed. It can be found [here](https://www.python.org).
