### ISSUE TITLE
CTRL+Z doesn't work for me on Ubuntu

### ISSUE THREAD

**Issue by codyatschool** [OpenShot/openshot-qt#216]
CTRL+Y does.

**Comment by znbn** [comment]
me too, on Mint 17.3

**Comment by schuko24** [comment]
seems to depend on your keyboard layout (querty vs. quertz)

**Comment by komackaj** [comment]
@codyatschool @znbn Can you please confirm it is an keyboard layout problem in order to close this? Thanks

**Comment by jreynojustin** [comment]
No response to @komackaj's inquiry. If you have more information to provide let us know.
