### ISSUE TITLE
Image is not the same as file

### ISSUE THREAD

**Issue by stefaniakgary** [OpenShot/openshot-qt#2161]
When adding files to the project they come through jittery and incorrect.  On the computer they look fine, but in the program they are not correct. 

**System Details:**
Windows 10
 - OpenShot Version 2.4.3

**To Reproduce**
1. Drag files into project files
2. Add file to track o
3. press play under video preview

**Expected behavior**
I would expect for it to play the video in the same quality and cadence as the video does on my computer. 

**Additional context**
this is the first and only project i have tried.  I have tried to move the original files off the external hard drive and onto to the desktop to see if the issue is related to lag from the device and it does not make a difference.  The videos as is are fine, but once in the program the are not right.  If i publish the files (having made no changes) they play from the computer in the same choppy way.

**Comment by LeosWelt** [comment]
You should propably look: What resolution do the original files have? What resolution do you choose in Open Shot? Are there differences with the image frequency (30 vs 25 frames/sec b.e)?
Can you upload a demo file so others can test it?

**Comment by speedytechdev** [comment]
@stefaniakgary ^^^
