### ISSUE TITLE
[Important] Transparent Videos?

### ISSUE THREAD

**Issue by MisterTeeXD** [OpenShot/openshot-qt#2163]
**My Question:**
Hello, is there anyway of exporting transparent videos in Openshot, there's a animation that i have worked on that i really want to have transparency in.

**System Details**
 - Operating System / Distro: [Windows 10]
 - OpenShot Version [2.4.3 Latest Build]

**Screenshots**

**Comment by LeosWelt** [comment]
I don't know any video format that transports transparency, so i allways work with png-image-sequences when i want to work with transparency.

**Comment by MisterTeeXD** [comment]
I have tried that but unfortunately, doing so, does not give me a transparent video to work with

**Comment by peanutbutterandcrackers** [comment]
It is probably because the video, when exported from OpenShot, will have the transparency rendered to black - even in the image sequences (I haven't really tried it myself, though; just a - highly plausible - theory). I would suggest, if it is that important, to use [GIMP Scripting](https://docs.gimp.org/en/gimp-scripting.html) to remove the background and turn the image sequences into `.png`s with *actual* transparency. Hope that helps.

**Comment by N3WWN** [comment]
I'm not aware of _any_ video formats which support transparency.  AFAIK, the best you could do, as others have said, is to export your video as a sequence of images and then use `convert` or some other utility to replace the background with transparency and then combine the transparent images into an animated GIF.  

You will lose the audio with this method, but you can export just the audio and could perhaps attempt to sync the playing of the audio with the start of the GIF.

What is your target for a transparent video?  There aren't any video players that support transparent video, also AFAIK, so even if you could generate a transparent video, you'd see the default background color of the player window.

**Comment by MisterTeeXD** [comment]
I want to make a Scene Transition with those images, i already Keyframed them

**Comment by N3WWN** [comment]
If this is all within OpenShot, you could take those clips and add them to a track on top of the track(s) that you want to transition between.  If the images already have transparency, those areas should be show the underlying track(s).

**Comment by MisterTeeXD** [comment]
I want to use that Transition in OBS Studio for Scene Transition

**Comment by N3WWN** [comment]
I can't help with OBS Studio... but does it have the ability to import image sequences?

**Comment by skylarmt** [comment]
This is a way to make a video appear transparent on the web, using a canvas: http://www.sciencelifeny.com/transparency/transparency.html
