### ISSUE TITLE
Audio dropout/pitch issue, possibly introduced with 2.4.3

### ISSUE THREAD

**Issue by N3WWN** [OpenShot/openshot-qt#2167]
**Describe the bug**
A little history:

I've been using OpenShot 2.4.1 (technically 2.4.1-dev with my clip nudging code and resvg external SVG rendering) to process individual clips (direct from a GoPro Session 4 and GoPro Session 2018) into Picture-In-Picture videos which I then run through an external tool (ShotCoach app on my wife's iPad) which adds timestamps to events in the videos.  I then take the resulting videos from ShotCoach and use OpenShot 2.4.1 again to create a nice final video with fades and such.  I've done this hundreds of times and never ran into the issue I'm about to describe.

A few days ago, I used 2.4.3 (since this version includes clip nudging) to process my individual clips (the ones from the GoPros) into Picture-In-Picture videos.  I still used 2.4.1 to render the final video due to my SVG rendering requirements.

Using 2.4.3 for the PIP portion, instead of using my dev version of 2.4.1 for everything, I now hear audio issues in my videos.  

Here are 3 clips which are the 3 steps in the video processing trail (I trimmed them from their originals for length only, maintaining the encoding and such).

Output from OpenShot 2.4.3 (where the GoPro videos are combined as a PIP video) - 3rd person video is muted via right click on the clip ->`Volume`->`Entire Clip`->`0%`, otherwise, only scaling, position and trimming is performed on the clips:

[Stage4-2.4.3-PIP.mp4](https://www.dropbox.com/s/7nl5m0erdvc81dj/Stage4-2.4.3-PIP.mp4?dl=0)

`$ ffprobe Stage4-2.4.3-PIP.mp4 2>&1 | grep Stream`
`Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x1080, 34261 kb/s, 60 fps, 60 tbr, 15360 tbn, 120 tbc (default)`
`Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 191 kb/s (default)`

No audio issues are apparent here.

This is the result of taking the above clip and running it through Shot Coach:

[Stage4-ShotCoach.mp4](https://www.dropbox.com/s/2ktf6w6i7ta6py8/Stage4-ShotCoach.mp4?dl=0)

`$ ffprobe Stage4-ShotCoach.mp4 2>&1 | grep Stream`
`Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 191 kb/s (default)`
`Stream #0:1(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, smpte170m/unknown/unknown), 1920x1080, 15773 kb/s, 29.90 fps, 30 tbr, 600 tbn, 1200 tbc (default)`

No audio issues are apparent here.

This is the final video:

[Stage4-2.4.1-final-output.mp4](https://www.dropbox.com/s/99g2v7pk7vpn6h3/Stage4-2.4.1-final-output.mp4?dl=0)

`$ ffprobe Stage4-2.4.1-final-output.mp4 2>&1 | grep Stream`
`Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x1080, 18965 kb/s, 60 fps, 60 tbr, 15360 tbn, 120 tbc (default)`
`Stream #0:1(und): Audio: ac3 (ac-3 / 0x332D6361), 44100 Hz, stereo, fltp, 128 kb/s (default)`

The pitch of the audio is definitely lower (the chirping of the inserts and the Range Officer saying "Stand By" are obviously deeper) and you can hear some of the shots that are fired have little/no audio when compared to the previous two clips.

I find it odd that the issue is apparently caused in the first step, but isn't detectable until the last step.

For completeness, if I use my OpenShot 2.4.1-dev1 to create the PIP, this is the ffprobe output:
`ffprobe Stage4-2.4.3-PIP_2.4.1.mp4 2>&1 | grep Stream`
`Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x1080, 33262 kb/s, 60 fps, 60 tbr, 15360 tbn, 120 tbc (default)`
`Stream #0:1(und): Audio: ac3 (ac-3 / 0x332D6361), 44100 Hz, stereo, fltp, 192 kb/s (default)`

I wonder if it's the `AC3@44.1kHz` vs `AAC@48kHz` changes that went into 2.4.3 or if OpenShot has an issue transcoding between the two?

**System Details (please complete the following information):**
 - Operating System / Distro: Fedora 25
 - OpenShot Version: 2.4.3 is where I think the cause is, but it could be that 2.4.1 (and maybe 2.4.3) are unable to handle  `AC3@44.1kHz` transcoding to/from `AAC@48kHz` correctly

**To Reproduce**
Steps to reproduce the behavior:  Steps noted above

**Expected behavior**
Pitch should not change and audio should not drop out.

**Screenshots**
Links to clips attached above - screenshots not necessary, me thinks.

**Logs**
No crash :)

**Additional context**
N/A

**Comment by ferdnyc** [comment]
See also #2207, these two **must** be related.
