### ISSUE TITLE
Not able to view the tutorial beyond the 3rd screen... help!

### ISSUE THREAD

**Issue by kombucha321** [OpenShot/openshot-qt#2170]
The 3rd tutorial screen that says "Timeline: arrange your clips on the timeline here..." is so low on the page I'm not able to move the window enough to click "next"! This is frustrating I'm new and I want to learn how to use this. But I can't click "next" on the tutorial. When I expand the window fully it just exits out of the Tutorial.  

**System Details (please complete the following information):**
 - Windows 10
 - OpenShot Version [e.g. 2.4.3]

**To Reproduce**
1. Click "help"
2. Click "tutorial"
3. Click "next" twice. 
4. Can't click "next" on the following tutorial box.

**Expected behavior**
I expect to be able to expand the window fully to view the "next" button without the tutorial canceling out. OR able to click and drag the tutorial box so that I can view and click the "next" button. 

**Additional context**
I'm new and want to learn this tutorial :)

**Comment by peanutbutterandcrackers** [comment]
@ferdnyc - *ahem* *ahem* Cap'ain? :smile:

**Comment by ferdnyc** [comment]
Yup, we know about this one, on very small screens. Dup of... bah, I can't find it. The one where we discussed what would happen with the timeline being sized so small that it hugs the bottom of very small displays.

The simplest workaround, @kombucha321, is to make the Timeline section of the user interface _taller_ before starting the tutorial. The third tutorial popup automatically positions itself based on the position of the Timeline. 

At some point in the development cycle for the most recent release, one of the developers resized the default interface for OpenShot to make the video Preview section larger and the Timeline section smaller. This had the side-effect of making the Timeline too short to fit the its tutorial popup, on screens shorter than about 900px.

So, if OpenShot comes up looking something like this:

![image](https://user-images.githubusercontent.com/538020/46254902-c2df7c00-c464-11e8-8612-346bcd90098d.png)

and you adjust it to something like **this**:

![image](https://user-images.githubusercontent.com/538020/46254908-d25ec500-c464-11e8-956d-4d69485116df.png)

Then when the tutorial reaches the third popup, the Next button won't be sticking off the bottom of your screen.

**Comment by ferdnyc** [comment]
(To change the size of the Timeline/Preview sections of the interface, grab on to that dotted line right in the middle of the window and drag it upwards. This part here:)

![image](https://user-images.githubusercontent.com/538020/46254929-279ad680-c465-11e8-81e9-47f41b99e21b.png)

**Comment by ferdnyc** [comment]
This information now has an (inaugural!) entry on the OpenShot [Workarounds for Known Bugs](https://github.com/OpenShot/openshot-qt/wiki/Workarounds-for-Known-Bugs#timeline-tutorial-popup-extends-off-bottom-edge-of-screen) wiki page.

**Comment by kombucha321** [comment]
Thank you so much!!!

**Comment by DylanC** [comment]
@ferdnyc - Fantastic workaround Ferd! :tada:
