### ISSUE TITLE
starwars movie made with openshot 2.4.2 now on youtube

### ISSUE THREAD

**Issue by bobcrikey** [OpenShot/openshot-qt#2172]
Hello everyone,
 heres a link to my new star wars episode 1  movie all made with openshot 2.4.2.
all animations and effects made within openshot.

https://youtu.be/VZowxyI_nF8

enjoy,
 cheers bob.

p.s episode 2 has already started with openshot 2.4.3

**Comment by DylanC** [comment]
@bobcrikey - This is really great! I love the use of lego for some of the characters. :)

**Comment by DylanC** [comment]
@bobcrikey - Also these videos will be a really great test for each release. :laughing:

**Comment by bobcrikey** [comment]
@DylanC - Glad you liked my starwars episode 1 mate,  it took awhile,
  The lego characters, was a last minute idea, as i couldnt get some action figures even 2nd hand.
 i hope you watched it right through to the end credits, as i usually put a screen picture using openshopt and blender3d and gimp.

Sometimes i have up to 10 tracks at once being used for animations.
Im hoping that strange churping sound bug with 2.4.3 gets fixed . As iv already started worked
on episode 2 , i hope you watch that one when its released im hoping for november release, but sometimes it might be december.

I dont know if you watched any of my earlier videos dr who, star trek movies, all done with openshot.
thanks for watching  mate.

cheers bob

**Comment by DylanC** [comment]
@bobcrikey - Yep, I saw you were using all Open Source software to make it. Funnily enough myself and Peter were just talking about the chirping issue last night. He has a few ideas of what might be the cause but of course will need some more time to investigate.

I hope for us to focus just on audio issues and bugs for this next release. We need our latest release to be even more stable I think.
