### ISSUE TITLE
4K export has sped up bits freezing / blank

### ISSUE THREAD

**Issue by ashic** [OpenShot/openshot-qt#2173]
**Describe the bug**
With 4K output, 2x/4x speeded up clips appear blank / frozen. 

**System Details (please complete the following information):**
 - Antergos (ArchLinux)
 - OpenShot Version 2.4.3

**To Reproduce**
Take 4K input. Clip together some videos, cut, slice, etc.
Have a segment that's sped up 4x. Export to 4K (30/60fps). 

The clips shows fine inside openshot preview, but the exported video has the sped up bits frozen, or completely blank. Things resume from next clip.

**Expected behavior**
Exported video should have the same things shown in the preview window.

**Additional context**
Exporting to 1080p gave the same issue (to a lesser extent... some things worked). Exporting to 720p made it work smoothly.

**Comment by LeosWelt** [comment]
I have checked this with my installation, arch linux (based on Zen-Installer), version 2.4.3. I have tried some videos in 4K made with a Sony Handycam FDR-AX53. I have created some speed ups and slowdowns, forward and backward, and everything worked wll, exporting to MP4 4K 2160P 25fps 3840x2160 pixels

**Comment by speedytechdev** [comment]
Hi @ashic If you are still having problems can you send us the file and the crash logs if not we would like to close this issue.

**Comment by ashic** [comment]
@LeosWelt Were you able to add fade transitions, and fade out? It seems a combination of a speed up and faded transitions seem to cause it. I've been able to get around some of it by putting two clips on separate tracks, instead of overlapping with a transition. 
Another things I'm seeing is with audio... if I have a fast fade out on video, and a slow fade out on audio - with there being two audio clips one after the other - then halfway through the second track, audio just stopped. If I remove the audio on the fadeout, then things are fine. 

I can't really send the files, and they're several gigs. And there aren't crash logs, as the app doesn't crash. Launching on the command line though, I can seem some errors in the logs. I'll run another render and capture the logs and provide them here.

**Comment by speedytechdev** [comment]
That would be great.

**Comment by LeosWelt** [comment]
I now have also seen some problems. When speeding up a video, i get black images at some positions inside a video, the black parts are mostly 8 images in length.

I have added the render-video into open shot and uploaded a screenvid as a Youtube unlisted video

https://youtu.be/KRLWNiy2giI

The input videos are 4K 3840*2160, 25 frames/sec. The framerate for the project is the same, also 4K.

**Comment by speedytechdev** [comment]
@LeosWelt @ashic  Could you post your pc specs in chat, please. I am wondering if your computers are similar because if so then we know it is an issue that Openshot does not like those parts. If they are not similar then we would have to look at how 4k is processed with Openshot.

**Comment by ashic** [comment]
[log2.txt](https://github.com/OpenShot/openshot-qt/files/2460528/log2.txt)
That's a log from an export. 

In my case, the preview window shows everything fine (well, stuttering at 4K, but the fades, transitions, audio, etc. work for the full clip). It's only the exported video that has blacked out portions, audio dying, etc. 

In terms of specs, I'm on a Dell Precision 5510 laptop with:

* Intel(R) Xeon(R) CPU E3-1505M v5 @ 2.80GHz (quad core, hyperthreaded to 8).
* 32 GB DDR4.
* GPU: Intel Corporation HD Graphics P530 (rev 06). (Integrated graphics). 
* Also tried the discreet GPU:  Quadro M1000M. Same result. 
* 1 TB Samsung NVME hard drive. 

Running Antergos (Arch) 64 bit. All things up to date with pacman.

**Comment by speedytechdev** [comment]
@ashic I had something similar but mine was in 1080 and when I exported the video it was black at portions. So it looks like it is an issue with fades glitching out when exporting.

**Comment by speedytechdev** [comment]
@DylanC ^^^

**Comment by LeosWelt** [comment]
My hardware:
AMD Ryzen 5-2600, 6-core, 12 hyperthreads
32GB DDR3
Mainboard Gigabyte Aorus X470 Gaming Pro
GPU Nvidia 1050TI

Running Arch Linux 64 Bit (installed with ZEN-Installer)

I will try to create a log in terminal, too. The only comparable parts are RAM and OS. Puuh, i thought it was an AMD ryzen problem ...

**Comment by LeosWelt** [comment]
Unfortunately i was not able to create the bug a second time until now. I will try to get it again with black images, i have not sored the project when the error was visible :(

**Comment by ashic** [comment]
Another repro. I took a 4K 60 fps edited mp4 export, started a new project, added it as the only file. It's 3 minutes 33 seconds, and 1.9GB. I added the file to a track (Track 4), and applied:

1. Fade -> End of Clip -> Fade Out (Slow)
2. Volume -> End of Clip -> Fade Out (Slow)

I then exported it to 4K 60 fps. The exported clip blacked out at 1 minute 25 seconds. Music also stopped at that time.
