### ISSUE TITLE
openshot crash upon playing first frame of video

### ISSUE THREAD

**Issue by mdda** [OpenShot/openshot-qt#2176]
**Describe the bug**
After adding a video clip to the timeline, and then pressing 'Play', openshot crashes when the cursor gets to the start of the video

**System Details (please complete the following information):**
 - Operating System / Distro: Linux square.herald 4.16.13-300.fc28.x86_64
 - OpenShot Version : 
openshot-2.4.3-1.fc28.noarch
openshot-lang-2.4.3-1.fc28.noarch
libopenshot-0.2.2-1.fc28.x86_64
libopenshot-audio-0.1.5-2.fc28.x86_64
python3-libopenshot-0.2.2-1.fc28.x86_64

**To Reproduce**
1. Go to timeline, insert a video
2. Click on Play button
3. Play cursor arrives at beginning of video
4. See crash

**Expected behavior**
Something should play in the preview window (the initial video frame is displayed)

**Screenshots**
Not really applicable

**Logs**
[openshot-crash.log](https://github.com/OpenShot/openshot-qt/files/2435057/openshot-crash.log)
[ffmpeg-i.log](https://github.com/OpenShot/openshot-qt/files/2435060/ffmpeg-i.log)

**Additional context**
First time user.

**Comment by speedytechdev** [comment]
Hi @mdda is it specific files that crash it or all files.
