### ISSUE TITLE
Openshot not starting

### ISSUE THREAD

**Issue by Eskander88** [OpenShot/openshot-qt#2177]
установщик OpenShot-v2.4.3-x86_64.exe
ОС х64 битная, Windows 10

После запуска по иконке на рабочем столе файрвол сообщает о попытке launcher.exe подключится к 127.0.0.1

Разрешаю.

Далее ничего не происхоит

**Comment by DylanC** [comment]
Google Translate...

Installer OpenShot-v2.4.3-x86_64.exe
OS x64 bit, Windows 10

After launching via the icon on the desktop, the firewall reports the attempted launcher.exe to connect to 127.0.0.1

I allow.

Then nothing happens

**Comment by arielpajares** [comment]
temgo problema tampoco iniciapero en mi ceibalita
