### ISSUE TITLE
SEGV when importing a video

### ISSUE THREAD

**Issue by valgit** [OpenShot/openshot-qt#2178]
**Describe the bug**

the app crash when importing a video

**System Details (please complete the following information):**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
Fedora 27 64 bits

 - OpenShot Version [e.g. 2.4.1]
2.4.3 AppImage

**To Reproduce**
run the program, import a video

**Expected behavior**
running

ur problem.

**Logs**
  metrics:ERROR Failed to Track metric: HTTPConnectionPool(host='www.google-analytics.com', port=80): Max retries exceeded with url: /collect?ua=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&an=OpenShot+Video+Editor&cd5=Fedora-27-Twenty+Seven&cd2=3.4.3&cd3=5.2.1&cd1=0.2.2&cd=metrics-opt-out&v=1&tid=UA-4381101-5&av=2.4.3&cid=edee437a-523c-46ee-a0ec-a7cec5088f6f&aip=1&t=screenview&ul=en-us&cd4=5.2.1&aid=org.openshot.openshot-qt (Caused by <class 'OSError'>: [Errno 101] Network is unreachable)
 main_window:INFO File Properties Cancelled
Caught signal 11 (SIGSEGV)

Caught signal 11 (SIGSEGV)
---- Unhandled Exception: Stack Trace ----
  /tmp/.mount_dAk7d6/usr/bin/libQt5Gui.so.5 ( QDrag::actionChanged(Qt::DropAction)      + 0x2e  )  [0x7f0ebc41b9ce]
  /tmp/.mount_dAk7d6/usr/bin/platforms/libqxcb.so (                                           + 0x373fe)  [0x7f0e9bf513fe]
  /tmp/.mount_dAk7d6/usr/bin/platforms/libqxcb.so (                                           + 0x3f369)  [0x7f0e9bf59369]
  /tmp/.mount_dAk7d6/usr/bin/platforms/libqxcb.so (                                           + 0x2db3b)  [0x7f0e9bf47b3b]
  /tmp/.mount_dAk7d6/usr/bin/platforms/libqxcb.so (                                           + 0x2eb6b)  [0x7f0e9bf48b6b]
  /tmp/.mount_dAk7d6/usr/bin/libQt5Core.so.5 ( QObject::event(QEvent*)                   + 0x23e )  [0x7f0ec19e222e]
  /tmp/.mount_dAk7d6/usr/bin/libQt5Widgets.so.5 ( QApplicationPrivate::notify_helper(QObject*, QEvent*)  + 0x8c  )  [0x7f0ebc820c8c]
  /tmp/.mount_dAk7d6/usr/bin/libQt5Widgets.so.5 ( QApplication::notify(QObject*, QEvent*)   + 0x3d6 )  [0x7f0ebc825e56]
  /tmp/.mount_dAk7d6/usr/bin/PyQt5.QtWidgets.so ( sipQApplication::notify(QObject*, QEvent*)  + 0x86  )  [0x7f0ebd1f6426]
  /tmp/.mount_dAk7d6/usr/bin/libQt5Core.so.5 ( QCoreApplication::notifyInternal(QObject*, QEvent*)  + 0x6d  )  [0x7f0ec19b9c2d]
  /tmp/.mount_dAk7d6/usr/bin/libQt5Core.so.5 ( QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*)  + 0x1e7 )  [0x7f0ec19bbe07]
  /tmp/.mount_dAk7d6/usr/bin/libQt5Core.so.5 (                                           + 0x2b4cd3)  [0x7f0ec1a06cd3]
  /lib64/libglib-2.0.so.0        ( g_main_context_dispatch                   + 0x157 )  [0x7f0ec0740b77]
  /lib64/libglib-2.0.so.0        (                                           + 0x4af20)  [0x7f0ec0740f20]
  /lib64/libglib-2.0.so.0        ( g_main_context_iteration                  + 0x2c  )  [0x7f0ec0740fac]
  /tmp/.mount_dAk7d6/usr/bin/libQt5Core.so.5 ( QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>)  + 0x5c  )  [0x7f0ec1a0698c]
  /tmp/.mount_dAk7d6/usr/bin/libQt5Core.so.5 ( QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>)  + 0x11b )  [0x7f0ec19b896b]
  /tmp/.mount_dAk7d6/usr/bin/libQt5Core.so.5 ( QCoreApplication::exec()                  + 0x81  )  [0x7f0ec19bf0e1]
  /tmp/.mount_dAk7d6/usr/bin/PyQt5.QtWidgets.so (                                           + 0x2c3020)  [0x7f0ebd1d2020]
  /tmp/.mount_dAk7d6/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalFrameEx                        + 0x6d79)  [0x7f0eca30d7e9]
  /tmp/.mount_dAk7d6/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalFrameEx                        + 0x6c5c)  [0x7f0eca30d6cc]
  /tmp/.mount_dAk7d6/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalFrameEx                        + 0x6c5c)  [0x7f0eca30d6cc]
  /tmp/.mount_dAk7d6/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalCodeEx                         + 0x886 )  [0x7f0eca310976]
  /tmp/.mount_dAk7d6/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalCode                           + 0x3b  )  [0x7f0eca31110b]
  /tmp/.mount_dAk7d6/usr/bin/libpython3.4m.so.1.0 (                                           + 0x24d6ed)  [0x7f0eca3546ed]
  /tmp/.mount_dAk7d6/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalFrameEx                        + 0x6d79)  [0x7f0eca30d7e9]
  /tmp/.mount_dAk7d6/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalCodeEx                         + 0x886 )  [0x7f0eca310976]
  /tmp/.mount_dAk7d6/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalCode                           + 0x3b  )  [0x7f0eca31110b]
  /tmp/.mount_dAk7d6/usr/bin/launch ( main                                      + 0x777 )  [0x404117]
  /lib64/libc.so.6               ( __libc_start_main                         + 0xea  )  [0x7f0ec9b53f2a]
  /tmp/.mount_dAk7d6/usr/bin/launch (                                                   )  [0x404425]
---- End of Stack Trace ----
Caught signal 11 (SIGSEGV)
---- Unhandled Exception: Stack Trace ----

**Comment by speedytechdev** [comment]
@DylanC Has same issue as https://github.com/OpenShot/openshot-qt/issues/2181

**Comment by raphaelhuefner** [comment]
Same here, OpenShot crashes when importing a video. Can't get a meaningful log even with debug mode enabled:

```
rh:~/.openshot_qt$ jq . openshot.settings | grep -C6 debug-mode
  },
  {
    "value": true,
    "title": "Debug Mode (Verbose)",
    "type": "bool",
    "category": "Debug",
    "setting": "debug-mode",
    "restart": false
  },
  {
    "min": 0,
    "max": 9999,
    "value": 5556,
rh:~/.openshot_qt$
```

And here is the empty stack trace at the end of the log:

```
rh:~/.openshot_qt$ cat libopenshot.log
------------------------------------------
libopenshot logging: Sat Oct  6 02:50:11 2018
------------------------------------------
Timeline::SortClips (clips.size()=0.0000)
Timeline::GetFrame (requested_frame=1.0000, minimum_frames=2.0000, OPEN_MP_NUM_PROCESSORS=2.0000)
Timeline::GetFrame (processing frame) (frame_number=2.0000, omp_get_thread_num()=1.0000)
Timeline::GetFrame (Adding solid color) (frame_number=2.0000, info.width=1280.0000, info.height=720.0000)
Timeline::GetFrame (Loop through clips) (frame_number=2.0000, clips.size()=0.0000, nearby_clips.size()=0.0000)
Timeline::GetFrame (Add frame to cache) (frame_number=2.0000, info.width=1280.0000, info.height=720.0000)
Timeline::GetFrame (processing frame) (frame_number=1.0000, omp_get_thread_num()=0.0000)
Timeline::GetFrame (Adding solid color) (frame_number=1.0000, info.width=1280.0000, info.height=720.0000)
Timeline::GetFrame (Loop through clips) (frame_number=1.0000, clips.size()=0.0000, nearby_clips.size()=0.0000)
Timeline::GetFrame (Add frame to cache) (frame_number=1.0000, info.width=1280.0000, info.height=720.0000)
Timeline::GetFrame (end parallel region) (requested_frame=1.0000, omp_get_thread_num()=0.0000)
Timeline::Close ()
Timeline::SortClips (clips.size()=0.0000)
Timeline::GetFrame (requested_frame=1.0000, minimum_frames=2.0000, OPEN_MP_NUM_PROCESSORS=2.0000)
Timeline::GetFrame (processing frame) (frame_number=2.0000, omp_get_thread_num()=1.0000)
Timeline::GetFrame (Adding solid color) (frame_number=2.0000, info.width=1280.0000, info.height=720.0000)
Timeline::GetFrame (Loop through clips) (frame_number=2.0000, clips.size()=0.0000, nearby_clips.size()=0.0000)
Timeline::GetFrame (Add frame to cache) (frame_number=2.0000, info.width=1280.0000, info.height=720.0000)
Timeline::GetFrame (processing frame) (frame_number=1.0000, omp_get_thread_num()=0.0000)
Timeline::GetFrame (Adding solid color) (frame_number=1.0000, info.width=1280.0000, info.height=720.0000)
Timeline::GetFrame (Loop through clips) (frame_number=1.0000, clips.size()=0.0000, nearby_clips.size()=0.0000)
Timeline::GetFrame (Add frame to cache) (frame_number=1.0000, info.width=1280.0000, info.height=720.0000)
Timeline::GetFrame (end parallel region) (requested_frame=1.0000, omp_get_thread_num()=0.0000)
VideoPlaybackThread::run (before render) (frame->number=1.0000, need_render=1.0000)
PlayerPrivate::run (determine sleep) (video_frame_diff=0.0000, video_position=1.0000, audio_position=1.0000, speed=0.0000, render_time=12.0000, sleep_time=29.0000)
Timeline::SortClips (clips.size()=0.0000)
Timeline::GetFrame (requested_frame=1.0000, minimum_frames=2.0000, OPEN_MP_NUM_PROCESSORS=2.0000)
Timeline::GetFrame (processing frame) (frame_number=2.0000, omp_get_thread_num()=1.0000)
Timeline::GetFrame (Adding solid color) (frame_number=2.0000, info.width=1280.0000, info.height=720.0000)
Timeline::GetFrame (Loop through clips) (frame_number=2.0000, clips.size()=0.0000, nearby_clips.size()=0.0000)
Timeline::GetFrame (Add frame to cache) (frame_number=2.0000, info.width=1280.0000, info.height=720.0000)
Timeline::GetFrame (processing frame) (frame_number=1.0000, omp_get_thread_num()=0.0000)
Timeline::GetFrame (Adding solid color) (frame_number=1.0000, info.width=1280.0000, info.height=720.0000)
Timeline::GetFrame (Loop through clips) (frame_number=1.0000, clips.size()=0.0000, nearby_clips.size()=0.0000)
Timeline::GetFrame (Add frame to cache) (frame_number=1.0000, info.width=1280.0000, info.height=720.0000)
Timeline::GetFrame (end parallel region) (requested_frame=1.0000, omp_get_thread_num()=0.0000)
VideoPlaybackThread::run (before render) (frame->number=1.0000, need_render=1.0000)
PlayerPrivate::run (determine sleep) (video_frame_diff=0.0000, video_position=1.0000, audio_position=1.0000, speed=0.0000, render_time=6.0000, sleep_time=35.0000)
---- Unhandled Exception: Stack Trace ----
---- End of Stack Trace ----
rh:~/.openshot_qt$
```

- OpenShot Version: 2.4.3
- Model Identifier: MacBookPro7,1
- System Version: macOS 10.13.6 (17G65)
- Kernel Version: Darwin 17.7.0

LMK if any other data is relevant.

**Comment by raphaelhuefner** [comment]
I downgraded to 2.4.2 and that's working for me. Download from here: https://github.com/OpenShot/openshot-qt/releases/ (It's a bit hard to get to the older versions via the home page.)

**Comment by DylanC** [comment]
Dup of #2114
