### ISSUE TITLE
GUI scales up unexpectedly when displayed on external monitor

### ISSUE THREAD

**Issue by brierjon** [OpenShot/openshot-qt#2179]
**Describe the bug**
The rendering of OpenShot on an extended desktop external monitor results in scaling up of all GUI elements making OpenShot not usable if more than 50% of the window is displayed on the external display. External monitor is connected via HDMI. These are LoDPI displays at 1920x1080.

**System Details (please complete the following information):**
 - Operating System / Distro: Pop!_OS 18.04 64-bit
 - OpenShot Version 2.4.3-dev1
 Installed from the Openshot stable PPA.
 Nvidia driver - 396.24 (system76 release)
 Resolution 1920x1080 (16:9)

**To Reproduce**
1. Launch Openshot
2. Grab window from main monitor
3. Drag window from main monitor to external monitor (nvidia driver 396.24 - X 11.19.6)
4. See window render of

**Expected behavior**
Expected display to scale minimally and display similar to the built-in monitor.

**Screenshots**
Screenshot one of what the app appears like when on the main monitor:

Screenshot of app on external monitor
Screenshot of rendering when on the external monitor (extended desktop from laptop built in display)
https://photos.app.goo.gl/hTsC9nkUkbdfLUBu8

Screenshot of rendering when on the laptop display.
https://photos.app.goo.gl/AGXEo2ecXmF693Km6

**Logs**
Ask if needed.

**Additional context**

**Comment by DylanC** [comment]
@speedytechdev - Maybe being lowDPI is the issue. Not 100% sure on this.

**Comment by brierjon** [comment]
@speedytechdev Is your primary display the external? My primary display is the laptop and the external is the extended. My external monitor is a Samsung SyncMaster XL2370 connected via HDMI. I'm only differentiating between HiDPI and LoDPI as that is how System76 refers to this on their help documentation for Pop!_OS on a Serval WS. 

Could the display oddity be related to how Nvidia proprietary drivers are scaling and scaling is detected by QT? - [https://support.system76.com/articles/hidpi-multi-monitor/](https://support.system76.com/articles/hidpi-multi-monitor/)

**Comment by speedytechdev** [comment]
@brierjon  My laptop is my primary display and I also have a Samsung display but I can't remember the model. You might be right about the "Nvidia proprietary drivers are scaling and scaling is detected by QT"
If you could confirm that it would be greatly appreciated and hopefully we could make a patch for it.
