### ISSUE TITLE
No layout from old project files

### ISSUE THREAD

**Issue by XXLRay** [OpenShot/openshot-qt#218]
When I try to open an old project from Openshot 1.x then openshot-qt 2.0.7 from the ppa doesn't interpret the clips' layout settings. All clips are show at 100 percent size and position 0,0.
Even when I adjust the size in openshot-qt the video doesn't display properly in the preview window. I have attached an example project.
[Layoutfade.zip](https://github.com/OpenShot/openshot-qt/files/308915/Layoutfade.zip)

**Comment by JtLively** [comment]
Please try a the newest version and create a new issue if this persists.
And next time, please provide screenshots and a hash sum (at least md5) with attached files.
