### ISSUE TITLE
MP4 File Timeline

### ISSUE THREAD

**Issue by Skalar01** [OpenShot/openshot-qt#2180]
I would like to transfer MP4 files to the timeline in my new OpenShot project.
Unfortunately, this does not work for me.
What could be the cause. Preview videos can be seen.
Thanks for a short feedback.
Best regards Rudolf

**Comment by speedytechdev** [comment]
What happens when you put it into the timeline and is it all mp4 files or just that one.

**Comment by Skalar01** [comment]
Hello

The program works in the meantime as expected.

Thanks for your help.

**Comment by DylanC** [comment]
@Skalar01 - Great news, thanks! :+1:
