### ISSUE TITLE
shut down when film is imported

### ISSUE THREAD

**Issue by cuttyyy** [OpenShot/openshot-qt#2181]
**Describe the bug**
Ny trying to import a film in a new project the program breaks down.

**System Details (please complete the following information):**
 -Apple 10.11.6
NVIDIA GeForce 9600M GT 256 MB

**To Reproduce**
1. Go to '...' "Dateien importieren"
2. Click on '....' eine Datei im Importfenster
3. Das Programm schliesst.
4. kein Error angegeben

**Expected behavior**
Ich sollte einen Film im Fensgter Projektdateien sehen

**Screenshots**
nicht möglich

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**

**Comment by speedytechdev** [comment]
Sind es bestimmte Dateien, die den Fehler verursachen?

**Comment by speedytechdev** [comment]
^^^ English Version: they are mp4 from the phone, but they are stored on the computer.
How many characters are allowed to have the names?

**Comment by DylanC** [comment]
Dup of #2114
