### ISSUE TITLE
Python Launch Error

### ISSUE THREAD

**Issue by Flowo1f** [OpenShot/openshot-qt#2182]
![python error](https://user-images.githubusercontent.com/40410075/46436386-4c6da300-c71e-11e8-9f45-62f1e00a1774.JPG)

**Comment by Flowo1f** [comment]
I got the same Problem. I have been sitting up here Trying to figure it out for days now. I just downloaded the 32bit Version and it is still not working.

**Comment by phtran72** [comment]
Having same problem, same error dialog box, clean install, version 2.4.3, both 64- and 32-bit builds, on Windows 10 64-bit, standard user account.
