### ISSUE TITLE
Crash on manually entering negative value for left margin property of pixelation effect

### ISSUE THREAD

**Issue by cnramey** [OpenShot/openshot-qt#2183]
I experimentally tried manually setting the margins on a pixelation effect to negative numbers. Nothing happened at all with the first two (right and bottom margin) except changing the values in the UI, but  upon changing the left margin property value to -.20, it crashed OpenShot.

I was able to reproduce this crash by re-opening and only setting the left margin to the -.2 value. 

(I'm assuming we're not meant to set the value on pixelation margins below zero at all, given that the slider's minimum stops there, so I'm not worried about the effect, just the crash!)

I reproed with Debug (Verbose) active and have attached the log.  I deleted the old log files first and tried to repro as quickly as possible. 

Do you think it might be a function duped multiple times that has still has an old/incorrect property name or something? 

I'm new to filing issues on GitHub so let me know if I'm missing anything - thanks!
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2443924/openshot-qt.log)

**Comment by speedytechdev** [comment]
I just tested that and I set the bottom and right to -2 and it crashed. So it does not like going into the negatives. 
![image](https://user-images.githubusercontent.com/40452959/46482948-10882a00-c853-11e8-8aed-6ec3b41b5af5.png)

**Comment by DylanC** [comment]
@speedytechdev - Thanks. Now confirming as a bug.
