### ISSUE TITLE
Part of film goes black

### ISSUE THREAD

**Issue by speedytechdev** [OpenShot/openshot-qt#2184]
**Describe the bug**
I exported my film in 1080 at 60fps and some of the film is missing it is just a black screen. It looks like it is a part of my film which might be causing it. It was fine the first time I exported it but when I exported it the second time it goes black in that spot. I have closed the software and reopened it. I also readded the video to the timeline and that did not fix it. I found out what the issue was. Since there a fade at the end of the clip it made the whole clip black.

**System Details (please complete the following information):**
 - Operating System / Distro: Windows 10
 - OpenShot Version: 2.4.3

**To Reproduce**
Not sure how I just to reproduce it. This image shows which clip is causing the problem. It worked before. https://imgur.com/a/dWLnCce

**Expected behaviour**
If you work out how to reproduce it you should have a black screen for 20 to 30 secs

**Screenshots**
https://imgur.com/a/dWLnCce

**Logs**
Not sure where to find them

**Additional context**
The fade caused the issue

**Comment by EternalHobo** [comment]
I have the same issue in Windows 10. The black screen always appears near a fade effect, can last from 20 sec to 2 min, and doesn't show up in the video preview (only after exporting to mp4 format). This has been a regular occurrence on all updates I've had for the past few months, at least.
