### ISSUE TITLE
Export project and open it in other computer

### ISSUE THREAD

**Issue by FMV72** [OpenShot/openshot-qt#2185]
**My Question:**
I need to export my projects and open it in others computers.
I work in two or three different places where I have Windows, Mac and Linux.
I installed OpenShot in every computer and I save my files and projects on my cloud space in Google Drive, syncronized with the local file system in every machine (same files everywhere).
When I open my project from a different machine from the one where I created it, OpenShot crash and close.
How can I do?

**System Details**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**Screenshots**

**Comment by DylanC** [comment]
Dup of #988.
