### ISSUE TITLE
Animated Masks please

### ISSUE THREAD

**Issue by whidzee** [OpenShot/openshot-qt#2188]
I'd love the ability to have animated masks for effects. This would be great for bluring a person's face.

I can see it working in a couple of ways.

You could have a circle image, which you can manipulate using the new transform tool to track your person's face you want to blur.

Or it could be more fancy of a tool to be a circle spline that you can manupulate the 4 besier control points and animate their position across the frame through time. this way you do away with needing an image as the shape to move, and the shape can change as you warp and deform your spline circle. You could add the ability to have a fade off on this too so that you dont get a harsh edge on the bluring effect.

**Comment by speedytechdev** [comment]
@DylanC Enhancement
