### ISSUE TITLE
Python Error

### ISSUE THREAD

**Issue by OfficialAnError** [OpenShot/openshot-qt#2190]
When opening the client, an error will pop up, following that, the program will open up about 7-15 seconds later (depending on the quality of the computer). 

Using the client is very tedious when this happens because you can't move to fast while editing because it'll crash, it's just small stuff like that.

 - Operating System: Windows 10
 - OpenShot Version 2.4.3

1. Click on the client icon.
2. See error
3. Client opens

When opening the client, it'll show an error saying there was a python error in the script.

https://www.dropbox.com/s/jg5zz5b3xv52tj0/Python%20Error%20Becasue%20Delayed%20YT%20Vids%20Are%20Utter%20shit.PNG?dl=0

**Comment by OfficialAnError** [comment]
Sorry if this was already reviewed somewhere else here, but I need to get some videos out.

**Comment by speedytechdev** [comment]
@DylanC @OfficialAnError I know it must be stressful so I will try and get a python expert to help you.

**Comment by OfficialAnError** [comment]
@speedytechdev Thank ya very much, my homeslice, breadslice, daug!

**Comment by speedytechdev** [comment]
@OfficialAnError No problem

**Comment by OfficialAnError** [comment]
@DylanC  

'Processor - Intel (R) Core (TM) i5-7200U CPU @ 2.50GHz 2.70GHz
Ram - 8.00 GB
System Type - 64-bit operating system, x64-based processor
Laptop - HP Laptop 15-bs0xx
Edition - Windows 10 Home
Version - 1803
OS Build - 17134.285'

I don't know if you need my product id or device id, but yeah, that's the sum

**Comment by DylanC** [comment]
@OfficialAnError - Alright, I'll see can I produce this soon. 

> I don't know if you need my product id or device id, but yeah, that's the sum

Nah, that would be too much info. :laughing:

**Comment by fcgll520** [comment]
i have the same issue. i can't open it.
