### ISSUE TITLE
Hardware acceleration 2.4.3 Openshot

### ISSUE THREAD

**Issue by CarlBicknell** [OpenShot/openshot-qt#2191]
**My Question: What hardware acceleration does Openshot 2.4.3 use on Windows 10? I see that there is now some mention of threading, how many threads are supported and what for? Is there any kind of GPU acceleration? Thanks.**

**System Details**
 - Operating System / Distro: [ Windows 10 64 bit]
 - OpenShot Version [2.4.3]

**Screenshots**

**Comment by speedytechdev** [comment]
@DylanC (**Question**)

**Comment by DylanC** [comment]
@CarlBicknell - We do have some Nvidia GPU support. See #1983 for more information. Threading is there for the export. I think we use 16 threads but I could be wrong. Hopefully this somewhat answers your question but I can get more information on this area if you like.

**Comment by peanutbutterandcrackers** [comment]
The good news is, a dev is working on hw_accel. So, hopefully in the future versions we'll have it.
