### ISSUE TITLE
impossible to export the video, openshot shutdowns all the time

### ISSUE THREAD

**Issue by sylvinho73** [OpenShot/openshot-qt#2192]
**Describe the bug**

**System Details (please complete the following information):**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**

**Comment by sylvinho73** [comment]
Dear, I am using openshot 4.2.4 and when I want to export the video, it shutdown, and I cannot export. Can you please help? it is urgent

**Comment by DylanC** [comment]
@sylvinho73 - We do not have a version 4.2.4. Which version are you using?

**Comment by DylanC** [comment]
@sylvinho73 - Oh I saw you have been sorted on a different thread.
