### ISSUE TITLE
impossible to export the video, openshot shutdowns all the time

### ISSUE THREAD

**Issue by sylvinho73** [OpenShot/openshot-qt#2193]
Dear, I am using openshot 4.2.4 on OSX and it shutdowns all the time when I want to export the video, please help it is urgent.

Thanks

**Comment by speedytechdev** [comment]
@sylvinho73 Sorry to get to you so late but we don't have a version 4.2.4 Can you please double check what version you are on. If you push ctrl-H it should show you what version you are on.
![image](https://user-images.githubusercontent.com/40452959/46577820-185eee80-ca4c-11e8-8788-490aacd0d905.png)

**Comment by sylvinho73** [comment]
Sorry the version is 2.4.2. How can you please help me? my project is ready and I need to export it !

**Comment by speedytechdev** [comment]
@sylvinho73 All good, I would recommend that you save the project file and get 2.4.3. It fixed a lot of bugs so it might allow you to export. Hopefully, that helps.

**Comment by sylvinho73** [comment]
That is what I did yesterday, but with the 2.4.3, when I try to open the project, it shutdowns again, I cant open the project.

**Comment by speedytechdev** [comment]
I got an idea. If you send me the osp file I can export it and send it to you.

**Comment by speedytechdev** [comment]
@sylvinho73 ^^^

**Comment by sylvinho73** [comment]
hey, great idea, how can I send the file to you?

**Comment by speedytechdev** [comment]
https://jumpshare.com/

**Comment by sylvinho73** [comment]
https://jmp.sh/NOQJMSw

**Comment by sylvinho73** [comment]
The link is above, please tell me if it works

**Comment by speedytechdev** [comment]
It works, what do you want it exported as.?

**Comment by sylvinho73** [comment]
I need a avi file, if possible good quality, but medium is also OK

**Comment by speedytechdev** [comment]
Can you also send the other files for it.
![image](https://user-images.githubusercontent.com/40452959/46580316-e4e98780-ca7e-11e8-833a-354ce86de41b.png)

**Comment by sylvinho73** [comment]
this is a photo which is in the project

**Comment by sylvinho73** [comment]
https://jmp.sh/dXKol2U

**Comment by sylvinho73** [comment]
I added this picture in the folder, you want me to send to you all the rootfile of the project? because there are more than 300 pitures and videos...

**Comment by sylvinho73** [comment]
is it working?

**Comment by speedytechdev** [comment]
No sorry, I can't get it to work. Maybe reinstall Openshot or try an older version. I am trying my best but I am the only staff member online so it is hard to know what to do.

**Comment by sylvinho73** [comment]
where can I find the 2.4.1 version to try?

**Comment by speedytechdev** [comment]
What device?

**Comment by speedytechdev** [comment]
https://github.com/OpenShot/openshot-qt/releases

**Comment by speedytechdev** [comment]
@sylvinho73 Please let me know if you still need help.

**Comment by sylvinho73** [comment]
Hey, I installed the 2.4.1 and it works !!! I can export ! thanks for your help

**Comment by DylanC** [comment]
@sylvinho73 - Great news thanks. :+1:
