### ISSUE TITLE
Vertical video editing 

### ISSUE THREAD

**Issue by Carloceruti** [OpenShot/openshot-qt#2197]
Hello everyone. 
I need to make a lot of video editing in 9:16 proportions because I need videos for IGTV. Right now I have to edit the videos  in 16:9 and then rotate them in VLC. These operation is always really complicated, time consuming and sometimes video players on tablet and smartphone have problems. 
It will be possible to introduce vertical formats? Right now I didn't find any alternative solution

Right now I'm editing in windows. I'm considering to switch to lubuntu. 

Thank you, best regards.

**Comment by speedytechdev** [comment]
Hi, @Carloceruti is this a feature request or a question?

**Comment by Carloceruti** [comment]
Hi, is a feature request. I didn't find already a feature that can make 9:16 videos.

**Comment by speedytechdev** [comment]
@Carloceruti ok, can you fill out the info below, please. 

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.

**Comment by speedytechdev** [comment]
@DylanC ^^^ enhancement

**Comment by peanutbutterandcrackers** [comment]
I wonder if what you are trying to have can be achieved by using a [custom profile](https://www.openshot.org/static/files/user-guide/profiles.html#custom-profile).

**Comment by DylanC** [comment]
@peanutbutterandcrackers - Yes, I think so. It would be worth a shot @Carloceruti

**Comment by Carloceruti** [comment]
Hi everybody,

sorry for my late reply but I've been out these week.

the custom profile I think could solve my problem. Is it possible also to
do it in openshot for win? I've reached the profiles folder but I can't
create a file / modify the existing ones

thank you

best regards

Carlo Ceruti

**Comment by DylanC** [comment]
@Carloceruti - Hi there, Usually I would take a copy of a profile and put it in the openshot preferences folder. The openshot preferences folder also has a profile folder inside it. I can't remember where this is in Windows but maybe @peanutbutterandcrackers could point you in the right direction.

**Comment by peanutbutterandcrackers** [comment]
Hmm... I wouldn't exactly know where. But it would be in the `.openshot_qt` folder in the same folder that contains `My Documents` and `My Pictures` and other folders in Windows. So, very likely in `C:\Users\username\.openshot_qt\profiles` folder. You should be able to copy paste your profile template into it.

**Comment by plieningerweb** [comment]
just to note, tried this as well. Worked, even though preview video was still landsacpe.
see me notes at https://gist.github.com/plieningerweb/05ebc827d0bf72b05c0bac70a1b391ac
