### ISSUE TITLE
serious crackling noise apon export 2.43 win 10 and linux

### ISSUE THREAD

**Issue by bobcrikey** [OpenShot/openshot-qt#2199]
Hello everyone @DylanC , i have found a serious bug apon exporting and lots more louder than
 just the chirping sounds i experience with @N3WWN ,

heres some video to share with you dylan
[snow falling linux 243.mp4.tar.gz](https://github.com/OpenShot/openshot-qt/files/2453930/snow.falling.linux.243.mp4.tar.gz)

and this one as well 
[snowing on the mountain win 10.mp4.tar.gz](https://github.com/OpenShot/openshot-qt/files/2453933/snowing.on.the.mountain.win.10.mp4.tar.gz)

@DylanC if you care to send me an email i can send you some other vids with 243 errors iv encountered the last couple days.
thanks mate,
 cheers bob

**Comment by DylanC** [comment]
@bobcrikey - I can confirm this but also I could hear the same noise when I played the video clip in a video player. Did you run the clips in a video player to test?

**Comment by bobcrikey** [comment]
@DylanC , no dylan, they were straight png's out of blender and imported into openshot 243 and made into video then exported by openshot , and then openshot is closed and reopened and the exported video snow flakes imported and then i needed 2 chromakeys to work with mountain background and the audio added and then all exported by openshot 243.

just as a footnote , having 2 chromakeys at once on the snowflakes slowed encoding right down to around 13fps.

thanks Dylan,i can send you the original files if you want mate.

cheers bob

**Comment by speedytechdev** [comment]
@bobcrikey Dylan will get back to you but can you make a report about the issue having "2 chromakeys at once on the snowflakes slowed encoding right down to around 13fps". Thanks

**Comment by DylanC** [comment]
@bobcrikey - Maybe send the source files. I would like to reproduce this for myself too.

**Comment by bobcrikey** [comment]
@DylanC heres my files for you to test your system mate,
[snowflakes test.tar.gz](https://github.com/OpenShot/openshot-qt/files/2460706/snowflakes.test.tar.gz)

cheers bob

**Comment by DylanC** [comment]
@bobcrikey 

I did a simple test of adding the snowflakes clip and a chroma key effect. On the track underneath I added the wind sound. I noticed the slow frame rate on the video and as soon as it hit the audio I noticed the crackling noise.

![chroma_test](https://user-images.githubusercontent.com/4488048/46829098-c47a3f80-cd94-11e8-9e1c-ef73130877cd.png)

I think your issue may be the same as this one - #1412.

**Comment by bobcrikey** [comment]
@DylanC ,Thanks for testing on your system mate, it now proves
there is a bug in openshot in regards to chromakey and 
audio export at the same time.

I should be able to have chromakey plus animation plus audio
export all together at the same time with no audio problems
and maintain at least 60fps or more for encoding.

but alas openshot is not doing this,

I did read that other thread you pointed me to about 
chromakey problems others have been experiencing.

I hope you can find a solution dylan, and that your able 
to let jonathan know about it.

cheers mate.
  bob

**Comment by DylanC** [comment]
Dup of #1412.

**Comment by DylanC** [comment]
@bobcrikey - I think I will get this shortlisted to be fixed for the next release. Mostly I want to focus on audio bugs and well this does seem related to audio, so it should be on the list too. 👍

**Comment by bobcrikey** [comment]
@DylanC cheers bob
