### ISSUE TITLE
Menu: File --> Recent Projects contains a list of your (Jonathan) recent projects

### ISSUE THREAD

**Issue by jarlarntzen** [OpenShot/openshot-qt#22]
It does not bother me the least but I'd just like for you to know about this.
![menu_027](https://cloud.githubusercontent.com/assets/2108412/12275499/a9e11ca6-b970-11e5-88cd-b6f77f98c24c.png)

And BTW, there's no error message when I try to load any of the non-existing project files.

**Comment by jonoomph** [comment]
Haha, that's a good find! I wish I could say this was a feature... but...

**Comment by jonoomph** [comment]
This is fixed now. Thanks.

**Comment by jarlarntzen** [comment]
Funny error, yeah :) 
I'd just like to add that even though my projects appear in the menu whenever I save a new one at run-time, it still reverts back to your list on restart if OpenShot crashed instead of being shut down gracefully.

```
 files_model:INFO updating files model.
 main_window:INFO Loaded project /home/jarl/Videos/FlightGear.osp
uint DBusMenuExporterDBus::GetLayout(int, int, const QStringList&, DBusMenuLayoutItem&): Condition failed: menu 
preview_thread:INFO exiting thread

```

I'm all for having example projects linked in some kind of menu like this, though. The example projects would possibly be prohibitively large, though unless they consist of simple example imagery.

**Comment by jonoomph** [comment]
Yeah, that's a good idea. A couple simple projects, which are mostly just small images, transitions, etc... very small file sizes. I'll think about this some. =)
