### ISSUE TITLE
AppImage won't run on Xubuntu 16.04

### ISSUE THREAD

**Issue by boysssss** [OpenShot/openshot-qt#220]
The first time I run the AppImage it asks me if I want a desktop Launcher, if I click no nothing happens, if I click yes it creates application menu launcher and nothing.
This is my terminal output:
neo@neo-xubuntu:~/Downloads$ ./OpenShot-2.0.7.AppImage
/tmp/.mount_KjTZjY/usr/bin/openshot-qt.wrapper
Loaded modules from current directory: /tmp/.mount_KjTZjY/usr/bin
      launch:INFO ------------------------------------------------
      launch:INFO    OpenShot (version 2.0.7)
      launch:INFO ------------------------------------------------
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_KjTZjY/usr/bin/platforms" ... 
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_KjTZjY/usr/bin/platforms/libqeglfs.so" 
Found metadata in lib /tmp/.mount_KjTZjY/usr/bin/platforms/libqeglfs.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.2",
    "MetaData": {
        "Keys": [
            "eglfs"
        ]
    },
    "className": "QEglFSIntegrationPlugin",
    "debug": false,
    "version": 328193
}

Got keys from plugin meta data ("eglfs") 
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_KjTZjY/usr/bin/platforms/libqkms.so" 
Found metadata in lib /tmp/.mount_KjTZjY/usr/bin/platforms/libqkms.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.2",
    "MetaData": {
        "Keys": [
            "kms"
        ]
    },
    "className": "QKmsIntegrationPlugin",
    "debug": false,
    "version": 328193
}

Got keys from plugin meta data ("kms") 
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_KjTZjY/usr/bin/platforms/libqlinuxfb.so" 
Found metadata in lib /tmp/.mount_KjTZjY/usr/bin/platforms/libqlinuxfb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.2",
    "MetaData": {
        "Keys": [
            "linuxfb"
        ]
    },
    "className": "QLinuxFbIntegrationPlugin",
    "debug": false,
    "version": 328193
}

Got keys from plugin meta data ("linuxfb") 
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_KjTZjY/usr/bin/platforms/libqminimal.so" 
Found metadata in lib /tmp/.mount_KjTZjY/usr/bin/platforms/libqminimal.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.2",
    "MetaData": {
        "Keys": [
            "minimal"
        ]
    },
    "className": "QMinimalIntegrationPlugin",
    "debug": false,
    "version": 328193
}

Got keys from plugin meta data ("minimal") 
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_KjTZjY/usr/bin/platforms/libqminimalegl.so" 
Found metadata in lib /tmp/.mount_KjTZjY/usr/bin/platforms/libqminimalegl.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.2",
    "MetaData": {
        "Keys": [
            "minimalegl"
        ]
    },
    "className": "QMinimalEglIntegrationPlugin",
    "debug": false,
    "version": 328193
}

Got keys from plugin meta data ("minimalegl") 
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_KjTZjY/usr/bin/platforms/libqoffscreen.so" 
Found metadata in lib /tmp/.mount_KjTZjY/usr/bin/platforms/libqoffscreen.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.2",
    "MetaData": {
        "Keys": [
            "offscreen"
        ]
    },
    "className": "QOffscreenIntegrationPlugin",
    "debug": false,
    "version": 328193
}

Got keys from plugin meta data ("offscreen") 
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_KjTZjY/usr/bin/platforms/libqxcb.so" 
Found metadata in lib /tmp/.mount_KjTZjY/usr/bin/platforms/libqxcb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.2",
    "MetaData": {
        "Keys": [
            "xcb"
        ]
    },
    "className": "QXcbIntegrationPlugin",
    "debug": false,
    "version": 328193
}

Got keys from plugin meta data ("xcb") 
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_KjTZjY/usr/platforms" ... 
loaded library "/tmp/.mount_KjTZjY/usr/bin/platforms/libqxcb.so" 
loaded library "Xcursor" 
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_KjTZjY/usr/bin/platformthemes" ... 
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_KjTZjY/usr/platformthemes" ... 
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_KjTZjY/usr/bin/platforminputcontexts" ... 
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_KjTZjY/usr/platforminputcontexts" ... 
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_KjTZjY/usr/bin/generic" ... 
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_KjTZjY/usr/generic" ... 
loaded library "gtk-x11-2.0" 
loaded library "gnomeui-2" 
loaded library "gnomevfs-2" 
/tmp/.mount_KjTZjY/usr/bin/launch: symbol lookup error: /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined symbol: g_type_check_instance_is_fundamentally_a
neo@neo-xubuntu:~/Downloads$

**Comment by rolandixor** [comment]
How would you fix this? I think someone needs to fork Openshot 2.0. I'd do it if I had a clue what I was doing with Python and Qt (could learn both but don't have the time). At least if we have someone to overview patches and pull requests, we could get something going. Clearly the project has been abandoned and it's time for someone to take over.

**Comment by nalipaz** [comment]
Let me preface this by saying I am not associated with openshot and only started using it today. However, I am encountering this same error on Debian Jessie. Although this is the issue queue for openshot-qt, I found this googling for a solution even though my errors reference libgtk-x11 rather than Qt. Seems like a similar issue happening on gtk as well.

On a side note, I don't really see any reason @rolandixor is claiming this project is abandoned, the most recent release is from Today even... Perhaps you know something we don't know, because from what I can tell this is being pretty actively developed.

**Comment by nalipaz** [comment]
Interestingly enough, running as sudo allows me to run the application. Found a similar Kubuntu bug for cairo where the maintainer says he needs to update glib. https://bugs.launchpad.net/calibre/+bug/1449027

**Comment by probonopd** [comment]
Possibly one of the environment variables needs to be unset?

**Comment by michalzubkowicz** [comment]
Same on Ubuntu 16.04 from PPA. Running as sudo helps. It's not an AppImage related problem i think so.

**Comment by probonopd** [comment]
Running as sudo helps?
That could be either due to the root rights, or due to some environment variables that are set differently for your user vs. root.

**Comment by probonopd** [comment]
See https://github.com/OpenShot/openshot-qt/issues/298

**Comment by jonoomph** [comment]
The AppImage should work now, with our latest daily builds.  Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot's AppImage. If you still encounter errors with Ubuntu 16.04, please reopen this ticket and attach the output from the AppImage. Thanks!

**Comment by mikymisho** [comment]
/tmp/.mount_W5kqGB/usr/bin/launch: symbol lookup error: /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0: undefined symbol: drmGetDevice2
Donloaded latest version ot OpenShot (OpenShot-v2.4.2-x86_64.AppImage) with XUbuntu

**Comment by probonopd** [comment]
Please try https://github.com/knapsu/plex-media-player-appimage/issues/11#issuecomment-379187464
