### ISSUE TITLE
Last frames of the video freeze

### ISSUE THREAD

**Issue by mikavonyaet** [OpenShot/openshot-qt#2201]
**OS:** Windows 10 1803
**OpenShot version:** 2.4.2
**Steps to reproduce:**
1. Add a video on any track
2. Crop it from the left and right
3. Export the video
I'm new to Openshot and did not use another formats except MP4 720p 24p with high quality
I had that bug with 2 videos: https://youtu.be/ZY-vC20GKxo and https://youtu.be/lBdrdUBX_hs
Sorry for bad English, i'm not a native speaker

**Comment by DylanC** [comment]
@mikavonyaet - Can you try v2.4.3 and let us know if you still have a problem. Thanks.

**Comment by peanutbutterandcrackers** [comment]
I think this has been resolved in `2.4.3`. There was a patch to libopenshot shortly after the release of `2.4.2` that resolved this issue.
