### ISSUE TITLE
clips are very hard to work with

### ISSUE THREAD

**Issue by arnoldbird** [OpenShot/openshot-qt#2206]
**Describe the bug**

It is difficult to work with clips.  Once I start making a few cuts in the video and trying to move the clips, the UI starts misbehaving.  In some cases the clips are impossible to move, or when I do move them, they don't align with the top or bottom of that part of the UI, and it is hard to place two clips next to one another in many cases.  Sometimes they join right together like they should, and other times there is a small gap between the two selections that can't easily be eliminated.

Sometimes clicking on one section causes another selection to move up or down slightly.

**System Details (please complete the following information):**
 - Ubuntu 16.04 LTS
 - OpenShot Version 2.4.3-dev1.  Installed today.
- My computer is not especially powerful so that could be part of the problem.  It has 16 GB of RAM. Intel Core i5-5250U CPU @ 1.60GHz × 4.

**Comment by speedytechdev** [comment]
Hi @arnoldbird do you have some screenshots of the issue.

**Comment by LeosWelt** [comment]
I have noticed some "behaviour" when moving clips.
It is hard to select a clip that is very small, the mouse just tries to get to the left or right border of the clip, it is almost impossible to select the clip, or move it.
When trying to allign clips, when you take a clip with the mouse, it does not snap to other clips. You have to select it, and the move it, and then it snaps.

**Comment by speedytechdev** [comment]
@LeosWelt Can you make that a feature request ina different issue please.
