### ISSUE TITLE
Preview playback rate/pitch in 2.4.3 is dependent on Default Audio Sample Rate preference

### ISSUE THREAD

**Issue by ferdnyc** [OpenShot/openshot-qt#2207]
**Describe the bug**

I just discovered (<strike>and this _has_ to be related to @N3WWN 's issue #2167</strike> it's not tho) that in 2.4.3 the Preview audio playback rate/pitch is dependent on the Default Audio Sample Rate.

**Context/Details**

I wasn't sure at first, but I noticed that things sounded "off" when I was previewing one of my usual test projects. I had cleared my preferences to test some dock-placement code, so the preference was reset from my usual 48kHz to the default 44.1kHz. Suddenly, the Preview of my test clip (a 48kHz MP4 file) sounded "draggy" — even after I upped the cache from the tiny default to a sensible value, and let the Preview play through once to build a complete cache of the Timeline.

**Steps to Reproduce**

1. Change the Default Audio Sample Rate preference from 44.1kHz to 48kHz
1. Restart OpenShot
1. Load my saved project (with clip on Timeline)
1. Preview the project once to build the cache, with the volume muted (to avoid biasing myself)
1. Turn the audio volume back up and Preview again

Sure enough, it sounded more normal, if not a little too fast — but that's a trick of perception, after having just heard it slowed down. Definitely different, though. (A 44.1kHz clip _would_ play back pitched higher, at this point, after sounding normal when the preference was set to 44.1kHz.)

Just to be sure, I ran a completely unambiguous test:
1. Change the Default Audio Sample Rate preference to 96kHz
1. Restart OpenShot, load project.
1. Hit Preview, and... chipmunks.

**System Details (please complete the following information):**
 - Operating System / Distro: Fedora Linux 28
 - OpenShot Version 2.4.3-dev

**Additional Context**

<strike>I haven't tested exporting, but #2167 seems to indicate that the same issue will be present in the exported video file.</strike> Exporting is fine, though.

**Comment by bobcrikey** [comment]
hello @ferdnyc , i just tried your suggestion, about converting to 48khz, in the preferences, i did that
and went back to the original mp3 and converted that to 48kzh as iv been using that and wav together
on 2 different audio tracks along with the videos, alas mate, im still getting crackling sounds 
even apon export., 

cheers bob

**Comment by ferdnyc** [comment]
> I haven't tested exporting, but #2167 seems to indicate that the same issue will be present in the exported video file.

Huh... nope,actually. With the Default Audio Sample Rate still set to 96khZ, I exported that same test project (one 48kHz video clip on the Timeline) at both 96kHz and 48kHz, and in both instances the resulting audio played back accurately and at the correct pitch. The audio setup in the files (as determined by MediaInfo) is pretty much normal — 1024 samples per frame in both cases, with an audio frame rate of 46.875 FPS in the 48kHz file, and 93.750 FPS in the 96kHz file.

So, it appears this is exclusively a Preview issue.

**Comment by ferdnyc** [comment]
> im still getting crackling sounds
> even apon export.,

@bobcrikey — Neither this issue nor #2167 is about crackling. You should really open a separate issue for the problem you're having, since (as I just proved with my own) issues that involve the same parts of the software aren't necessarily _related_. It's not helpful to muddy up issue reports with unrelated problems, keeping each one separate is far more likely to produce a solution for any given problem.

**Comment by bobcrikey** [comment]
@ferdnyc  actually i did open an issue #2199 , although your issue about 48khz may have been related to my issue about the crackling sound in preview playback and export, i thought i'd try your suggestion.

bob

**Comment by datacate** [comment]
I can confirm this issue with OpenShot 3.0 on Windows 10. I have some video encoded with an audio sample rate of 32kHz, and with the default sample rate in OpenShot preferences set to 48kHz, not only is the audio pitch off and the audio lagging behind the video playback, but when using waveform view for video clips on the timeline, there's clearly a delay between the audio position in the clips (peaks and valleys) and when you hear them. If I change the default sample rate in Preferences, the audio speeds up or slows down accordingly - but I could not get 1:1 by adjusting that setting.

My fix was to use OpenShot to re-encode the video with 48kHz audio sampling before using it to edit. Oddly, I would have thought that a default sample rate of 48kHz would have given me perfect audio playback with the newly encoded video, but in fact, I had to set the default to 44.1kHz to get everything to work perfectly.

It seems there is some lingering issue around these settings and audio playback in the editor, at least in the Windows version.
