### ISSUE TITLE
error popup "family.jpg is not a valid video, audio, or image file."

### ISSUE THREAD

**Issue by MarcLoveCr8** [OpenShot/openshot-qt#2209]
When adding video or image an error popup "family.jpg is not a valid video, audio, or image file."  keeps popping up numerous times. 

I am using Windows 10 and OpenShot 2.4.3

![openshot error popup](https://user-images.githubusercontent.com/43997785/46679351-7841ca80-cbef-11e8-9ce7-5d8f35141fed.JPG)

**Comment by MarcLoveCr8** [comment]
Uninstalled OpenShot program and re-installed again.

The same problem still remains...

Any solution?

**Comment by azzaNZ** [comment]
![day11_01_105338](https://user-images.githubusercontent.com/31429614/72779836-1725f500-3c82-11ea-9bbf-59d2a519c925.jpg)
Here's one of mine it won't accept.  Interestingly, I've run this through a batch renamer.  If I rename it something like day11_01.jpg it accepts it, but won't with this name, even if I subsequently manually rename it back to day11_01.jpg.  No other image editor / viewer struggles with the file.  Perhaps something in the exif data?

**Comment by SuslikV** [comment]
@azzaNZ it looks similar to https://github.com/OpenShot/openshot-qt/issues/3137 that was solved in https://github.com/OpenShot/openshot-qt/commit/b91780cd7bfe52412be1d8c36409e1e7d61782f8 thus you need to try latest _Daily Build_: https://www.openshot.org/download/
