### ISSUE TITLE
Can't open file - runTime terminate

### ISSUE THREAD

**Issue by 33885514** [OpenShot/openshot-qt#2211]
**Describe the bug**
Can't open my file and do it making my video.
The system had some information see the below word:
This application has requested the Runtime to terminate it in an unusual way. Please contact  the application's support team for more informaion.

**System Details (please complete the following information):**
 - Operating System / Distro: [Windows 7 x86 64]
 - OpenShot Version [v2.4.3-x86_64]

**To Reproduce**
1. Go to 'Open the OpenShot'
2. Click on 'open project'
3. See error

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/44012036/46710230-96eca380-cc79-11e8-97d1-ab4d0069cedb.png)

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**

**Comment by ctsdownloads** [comment]
Unreproducible, old version of OpenShot
