### ISSUE TITLE
Error on build DMG 

### ISSUE THREAD

**Issue by antonino-tocco** [OpenShot/openshot-qt#2213]
**Describe the bug**
Hi, when I build DMG for mac, the folder structure is very different from the folder structure from the Openshot DMG in the official site. I have try to build it with cx_Freeze 5.1.1 and 6.0b1. With the cx_Freeze 5.1.1 I have an error if I use PIL, which is in my dependencies and if I don't use PIL it build DMG but when I run it from a PC different from which I have build I receive illegal istruction 4 after dylib loaded: /usr/lib/system/libxpc.dylib.
If I build with cx_Freeze 6.0b1 it build DMG but when I run it from a PC different from which I have build I receive illegal istruction 4. 
**System Details (please complete the following information):**
 - Operating System / Distro: MacOS 10.14 Mojave
 - OpenShot Version [e.g. 2.4.1] 2.4.2

**To Reproduce**
1. Download openshot-qt repository
2. Run python3 freeze.py bdist_mac --include-frameworks "..." --qt-menu-nib ...
3. Run ./installer/build-mac-dmg.sh
2. Install App with this DMG on a "new" Mac
3. Run app

**Expected behavior**

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.
This when I run app from icon

Process:               launch [4942]
Path:                  /Users/USER/Desktop/VideoEditor.app/Contents/MacOS/launch
Identifier:            launch
Version:               VERSION
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           launch [4942]
User ID:               501

Date/Time:             2018-10-10 16:07:55.786 +0200
OS Version:            Mac OS X 10.14 (18A391)
Report Version:        12
Anonymous UUID:        AE1C4D2C-676F-F1B9-5705-BA6767D9860A

Sleep/Wake UUID:       6EE29295-E4DA-4B5C-B203-16A7CC594AE9

Time Awake Since Boot: 30000 seconds
Time Since Wake:       13000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [4942]

Application Specific Information:
dyld2 mode

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   Python                        	0x000000010c7677f8 countformat + 111
1   Python                        	0x000000010c76728a va_build_value + 46
2   Python                        	0x000000010c76723e Py_BuildValue + 138
3   Python                        	0x000000010c6fc942 mro_implementation + 221
4   Python                        	0x000000010c6f827c mro_internal + 136
5   Python                        	0x000000010c6f50f3 PyType_Ready + 1051
6   Python                        	0x000000010c6e94f1 _Py_ReadyTypes + 16
7   Python                        	0x000000010c76a77e _Py_InitializeEx_Private + 156
8   launch                        	0x000000010c69b768 main + 440
9   libdyld.dylib                 	0x00007fff5b8e0085 start + 1

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x3acaccf4d45a006a  rdx: 0x000000000000005b
  rdi: 0x000000010c7cd017  rsi: 0x0000000000000000  rbp: 0x00007ffee3565030  rsp: 0x00007ffee3564fd8
   r8: 0x0000000000000000   r9: 0x0400104900000200  r10: 0x0000000000000000  r11: 0x00007fc0f2800068
  r12: 0x000000010c832660  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x00007ffee35650f0
  rip: 0x000000010c7677f8  rfl: 0x0000000000010297  cr2: 0x000000010c7671b4
  
Logical CPU:     7
Error Code:      0x00000000
Trap Number:     6

Binary Images:
       0x10c69a000 -        0x10c69bfff +launch (VERSION) <4F5E8725-13E9-39E8-865D-72B17461C935> /Users/USER/Desktop/VideoEditor.app/Contents/MacOS/launch
       0x10c6a2000 -        0x10c812fef +Python (0) <B7655BE9-052F-38CA-A628-80074572F813> /Users/USER/Desktop/VideoEditor.app/Contents/MacOS/Python
       0x115624000 -        0x1156a26a7  dyld (625.13) <D6387150-2FB8-3066-868D-72E1B1C43982> /usr/lib/dyld
    0x7fff2e810000 -     0x7fff2ec5ffff  com.apple.CoreFoundation (6.9 - 1555.10) <4A4C87BC-4C8E-392A-ABEE-824D4074C485> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff589a3000 -     0x7fff589a4ff7  libDiagnosticMessagesClient.dylib (107) <C542CB3C-AA44-3D7F-B88C-79CC31B481AB> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff58d55000 -     0x7fff58d56ffb  libSystem.B.dylib (1252.200.5) <D5133811-9D66-3DEB-9521-0A67347C9A54> /usr/lib/libSystem.B.dylib
    0x7fff58fb0000 -     0x7fff59007ff7  libc++.1.dylib (400.9.4) <D4AB366F-48A9-3C7D-91BD-41198F69DD57> /usr/lib/libc++.1.dylib
    0x7fff59008000 -     0x7fff5901dfff  libc++abi.dylib (400.17) <BA948A32-9024-3E55-98D4-18E31F6AED25> /usr/lib/libc++abi.dylib
    0x7fff59c6b000 -     0x7fff59eceffb  libicucore.A.dylib (62107.0.1) <EAE6FC43-3AD2-3A53-9F7A-4E5E5F66D006> /usr/lib/libicucore.A.dylib
    0x7fff5a7fc000 -     0x7fff5af82fe7  libobjc.A.dylib (750) <2E868147-8818-359E-8CD7-A8B80665928F> /usr/lib/libobjc.A.dylib
    0x7fff5b6df000 -     0x7fff5b6f1ffb  libz.1.dylib (70.200.4) <99A3D725-8388-38B4-B66C-5E9006E6F072> /usr/lib/libz.1.dylib
    0x7fff5b762000 -     0x7fff5b766ff3  libcache.dylib (81) <FE21A7E9-DBEB-33AC-836B-785AD036ACF4> /usr/lib/system/libcache.dylib
    0x7fff5b767000 -     0x7fff5b771ff3  libcommonCrypto.dylib (60118.200.6) <78093D4F-91DB-35C8-981A-13375778B2E7> /usr/lib/system/libcommonCrypto.dylib
    0x7fff5b772000 -     0x7fff5b779fff  libcompiler_rt.dylib (63.4) <A4D9CF37-D076-3CE9-95F1-DA89DA1601B6> /usr/lib/system/libcompiler_rt.dylib
    0x7fff5b77a000 -     0x7fff5b783ff3  libcopyfile.dylib (146.200.3) <4BCDADBF-79F5-3829-B47D-64DA0D44BCBF> /usr/lib/system/libcopyfile.dylib
    0x7fff5b784000 -     0x7fff5b808fff  libcorecrypto.dylib (602.200.50) <7AEC5B72-0B92-37E8-808B-6732DB714139> /usr/lib/system/libcorecrypto.dylib
    0x7fff5b88e000 -     0x7fff5b8c8ff7  libdispatch.dylib (1008.200.78) <B8962879-AD55-3CF0-9B0A-5F1D57D1E14B> /usr/lib/system/libdispatch.dylib
    0x7fff5b8c9000 -     0x7fff5b8f8fff  libdyld.dylib (625.13) <4B16C209-83D4-3817-9B62-C2F7FFB23755> /usr/lib/system/libdyld.dylib
    0x7fff5b8f9000 -     0x7fff5b8f9ffb  libkeymgr.dylib (30) <A73AA788-C35C-3284-BFCA-95B1BBDF0CF3> /usr/lib/system/libkeymgr.dylib
    0x7fff5b907000 -     0x7fff5b907ff7  liblaunch.dylib (1336.201.2) <43E6698E-155E-3EAE-BAFF-CA5FCB35325C> /usr/lib/system/liblaunch.dylib
    0x7fff5b908000 -     0x7fff5b90dfff  libmacho.dylib (917) <17BF7038-9C70-3EE1-9E96-3AE10D49669E> /usr/lib/system/libmacho.dylib
    0x7fff5b90e000 -     0x7fff5b910ff3  libquarantine.dylib (86.200.11) <C70DA995-0D6E-302C-A15E-F7F03A3857B4> /usr/lib/system/libquarantine.dylib
    0x7fff5b911000 -     0x7fff5b912ff3  libremovefile.dylib (45.200.2) <D74A307B-3DC7-3992-B16C-DACB8207BE13> /usr/lib/system/libremovefile.dylib
    0x7fff5b913000 -     0x7fff5b92aff3  libsystem_asl.dylib (356.200.4) <EC9D8AD4-E5CB-3765-804A-9E1E9DC045D2> /usr/lib/system/libsystem_asl.dylib
    0x7fff5b92b000 -     0x7fff5b92bfff  libsystem_blocks.dylib (73) <26419398-C30C-30F1-B656-A92AFA9560F6> /usr/lib/system/libsystem_blocks.dylib
    0x7fff5b92c000 -     0x7fff5b9b4fff  libsystem_c.dylib (1272.200.26) <3DEEE96E-6DF6-35AD-8654-D69AC26B907B> /usr/lib/system/libsystem_c.dylib
    0x7fff5b9b5000 -     0x7fff5b9b8ff7  libsystem_configuration.dylib (963.200.27) <02CC3996-B34E-333C-8806-AE2699D34424> /usr/lib/system/libsystem_configuration.dylib
    0x7fff5b9b9000 -     0x7fff5b9bcff7  libsystem_coreservices.dylib (66) <254B6849-2C8F-302C-8616-B8324A11AB30> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff5b9bd000 -     0x7fff5b9c3ffb  libsystem_darwin.dylib (1272.200.26) <974E9EF7-DE72-34B7-B056-0A81C10DF8EB> /usr/lib/system/libsystem_darwin.dylib
    0x7fff5b9c4000 -     0x7fff5b9caff7  libsystem_dnssd.dylib (878.200.35) <FFC665AA-B257-35AD-BD8B-32FD42C2EEC1> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff5b9cb000 -     0x7fff5ba17ff3  libsystem_info.dylib (517.200.9) <0707C387-D7DE-372E-8FF1-3DE5C91932D6> /usr/lib/system/libsystem_info.dylib
    0x7fff5ba18000 -     0x7fff5ba3fff7  libsystem_kernel.dylib (4903.201.2) <45FAA4C0-D553-34FD-ADF8-884886AE0D2A> /usr/lib/system/libsystem_kernel.dylib
    0x7fff5ba40000 -     0x7fff5ba8bff7  libsystem_m.dylib (3158.200.7) <43D1796B-954F-37D6-B1AC-9D80DF0655A2> /usr/lib/system/libsystem_m.dylib
    0x7fff5ba8c000 -     0x7fff5bab0ff7  libsystem_malloc.dylib (166.200.60) <846F6898-117C-3427-A8FB-3772FFC2410B> /usr/lib/system/libsystem_malloc.dylib
    0x7fff5bab1000 -     0x7fff5babcffb  libsystem_networkextension.dylib (767.200.40) <F84D5474-4DC1-3E1A-AE00-8CE9593278B4> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff5babd000 -     0x7fff5bac4fff  libsystem_notify.dylib (172.200.21) <BCCB222F-DC64-3954-A836-DCCE6659CA5A> /usr/lib/system/libsystem_notify.dylib
    0x7fff5bac5000 -     0x7fff5bacefef  libsystem_platform.dylib (177.200.16) <B75B04AD-69FE-3ADE-84D2-C17972FC8F49> /usr/lib/system/libsystem_platform.dylib
    0x7fff5bacf000 -     0x7fff5bad9fff  libsystem_pthread.dylib (330.201.1) <87A6B136-E423-3B6D-A58A-137F392D7D9D> /usr/lib/system/libsystem_pthread.dylib
    0x7fff5bada000 -     0x7fff5baddff7  libsystem_sandbox.dylib (851.201.1) <FBA7E09B-F10F-3424-90EA-B4999B7FB461> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff5bade000 -     0x7fff5bae0ff7  libsystem_secinit.dylib (30.200.13) <CBEAB62B-F0A0-342F-9878-CADC14A3CB0D> /usr/lib/system/libsystem_secinit.dylib
    0x7fff5bae1000 -     0x7fff5bae8ff7  libsystem_symptoms.dylib (820.207.88) <B6E22FA8-0F7B-36FD-9D99-284056D3CB47> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff5bae9000 -     0x7fff5bafeff7  libsystem_trace.dylib (906.200.86) <7983ED77-18B5-39A5-BE19-AE4F2832ADEA> /usr/lib/system/libsystem_trace.dylib
    0x7fff5bb00000 -     0x7fff5bb05ffb  libunwind.dylib (35.4) <41222EF6-2233-3CF4-947A-15D48CB8C030> /usr/lib/system/libunwind.dylib
    0x7fff5bb06000 -     0x7fff5bb36fff  libxpc.dylib (1336.201.2) <0A8747D1-33AA-37E1-B97A-BA9B95FE4E8C> /usr/lib/system/libxpc.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 20468
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=236.5M resident=0K(0%) swapped_out_or_unallocated=236.5M(100%)
Writable regions: Total=547.7M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=547.7M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Kernel Alloc Once                    8K        2 
MALLOC                           155.1M       11 
MALLOC guard page                   16K        4 
MALLOC_NANO (reserved)           384.0M        2         reserved VM address space (unallocated)
STACK GUARD                       56.0M        2 
Stack                             8192K        2 
VM_ALLOCATE                        256K        2 
__DATA                            4244K       47 
__LINKEDIT                       216.6M        5 
__TEXT                            20.0M       45 
__UNICODE                          560K        2 
shared memory                        8K        3 
===========                     =======  ======= 
TOTAL                            844.6M      115 
TOTAL, minus reserved VM space   460.6M      115 

This when I manually run Contents/MacOs/launch-mac-sh

dyld: loaded: /Users/antoninotocco/Desktop/VideoEditor.app/Contents/MacOS/launch
dyld: loaded: /Users/antoninotocco/Desktop/VideoEditor.app/Contents/MacOS/Python
dyld: loaded: /usr/lib/libSystem.B.dylib
dyld: loaded: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
dyld: loaded: /usr/lib/libobjc.A.dylib
dyld: loaded: /usr/lib/libDiagnosticMessagesClient.dylib
dyld: loaded: /usr/lib/libicucore.A.dylib
dyld: loaded: /usr/lib/libz.1.dylib
dyld: loaded: /usr/lib/libc++abi.dylib
dyld: loaded: /usr/lib/libc++.1.dylib
dyld: loaded: /usr/lib/system/libcache.dylib
dyld: loaded: /usr/lib/system/libcommonCrypto.dylib
dyld: loaded: /usr/lib/system/libcompiler_rt.dylib
dyld: loaded: /usr/lib/system/libcopyfile.dylib
dyld: loaded: /usr/lib/system/libcorecrypto.dylib
dyld: loaded: /usr/lib/system/libdispatch.dylib
dyld: loaded: /usr/lib/system/libdyld.dylib
dyld: loaded: /usr/lib/system/libkeymgr.dylib
dyld: loaded: /usr/lib/system/liblaunch.dylib
dyld: loaded: /usr/lib/system/libmacho.dylib
dyld: loaded: /usr/lib/system/libquarantine.dylib
dyld: loaded: /usr/lib/system/libremovefile.dylib
dyld: loaded: /usr/lib/system/libsystem_asl.dylib
dyld: loaded: /usr/lib/system/libsystem_blocks.dylib
dyld: loaded: /usr/lib/system/libsystem_c.dylib
dyld: loaded: /usr/lib/system/libsystem_configuration.dylib
dyld: loaded: /usr/lib/system/libsystem_coreservices.dylib
dyld: loaded: /usr/lib/system/libsystem_darwin.dylib
dyld: loaded: /usr/lib/system/libsystem_dnssd.dylib
dyld: loaded: /usr/lib/system/libsystem_info.dylib
dyld: loaded: /usr/lib/system/libsystem_m.dylib
dyld: loaded: /usr/lib/system/libsystem_malloc.dylib
dyld: loaded: /usr/lib/system/libsystem_networkextension.dylib
dyld: loaded: /usr/lib/system/libsystem_notify.dylib
dyld: loaded: /usr/lib/system/libsystem_sandbox.dylib
dyld: loaded: /usr/lib/system/libsystem_secinit.dylib
dyld: loaded: /usr/lib/system/libsystem_kernel.dylib
dyld: loaded: /usr/lib/system/libsystem_platform.dylib
dyld: loaded: /usr/lib/system/libsystem_pthread.dylib
dyld: loaded: /usr/lib/system/libsystem_symptoms.dylib
dyld: loaded: /usr/lib/system/libsystem_trace.dylib
dyld: loaded: /usr/lib/system/libunwind.dylib
dyld: loaded: /usr/lib/system/libxpc.dylib
Illegal instruction: 4

**Additional context**

**Comment by DylanC** [comment]
@antonino-tocco - Hope you don't mind me asking but why are you building a DMG file?

**Comment by antonino-tocco** [comment]
Because I'd like to install it on my different devices after edit it

**Comment by DylanC** [comment]
@antonino-tocco - Cool. Well I don't know much about building DMG files but according to this link here:

https://stackoverflow.com/questions/14268887/what-is-the-illegal-instruction-4-error-and-why-does-mmacosx-version-min-10

It does seem like you are building the code with some optimizations that do not work on older versions of the OS. Hopefully this helps you figure it out.
