### ISSUE TITLE
Better way to select clips

### ISSUE THREAD

**Issue by LeosWelt** [OpenShot/openshot-qt#2217]
**Is your feature request related to a problem? Please describe.**
When trying to select clips, it is sometimes hard to do so when the clips are of small sizes. The mouse flips from wight border to left border and a click there leads to scaling.

**Describe the solution you'd like**
When working with small clips, a way to select the clip without affecting left or right borders would be fine. Perhaps with pressing a key while or before the select-click.

**Describe alternatives you've considered**
...

**Additional context**
...

**Comment by DylanC** [comment]
Related to #2206

**Comment by N3WWN** [comment]
Try drawing a box around the clip(s) by clicking and dragging from an empty spot (perhaps the gap between tracks).

**Comment by LeosWelt** [comment]
Perhaps the maximal zoom can be increased to give clips with length of only some images easier editing. For some effects i use images of length one image to let it look like flashing. Hard to edit with the maximum zoom of this version.
