### ISSUE TITLE
Openshot 2.4.3 on osx 10.9.5 doesn't run

### ISSUE THREAD

**Issue by arfo62** [OpenShot/openshot-qt#2218]
**My Question:** Hi everybody,
I've just downloaded openshot 2.4.3. but when I launch it doesn't start... Thank you for helping...
arfo62

**System Details**
 - Operating System / Distro: [macmini late 2012, osx 10.9.5., 16GB ram, ssd, I7quadcore ]
 - OpenShot Version [e.g. 2.4.3]

**Screenshots**

**Comment by arfo62** [comment]
Thank you Dylan!
I hope someone will answer...
arfo62

**Comment by kalvhed** [comment]
met o  same problem is not old versions? will follow here

**Comment by kalvhed** [comment]
21.5-inch, Mid 2010
 OS X 10.9.5 (13F1911)

**Comment by DylanC** [comment]
@kalvhed - Thanks for confirming.

**Comment by bernielubell** [comment]
I have the same problem with OS10.10.5
