### ISSUE TITLE
Openshot 2.4.3, Windows 7. Clips judder on playback when effects are added

### ISSUE THREAD

**Issue by JohnR58** [OpenShot/openshot-qt#2219]
**My Question: Video clips judder on playback when effects are added. Why is this?

**System Details**
Windows 7, i5 processor, 4GB RAM, OpenShot Version [2.4.3]

**Comment by DylanC** [comment]
@JohnR58 - Effects have performance issues. I would suggest to follow the progress on #2289 or the original linked issue inside it.
