### ISSUE TITLE
Removing animation from a clip resets its scaling values

### ISSUE THREAD

**Issue by andrewcharnley** [OpenShot/openshot-qt#222]
As per title, pretty straight forward I should think.

**Comment by DylanC** [comment]
@andrewcharnley - Does this still occur on latest versions of OpenShot?

**Comment by andrewcharnley** [comment]
Unable to check sorry, it's been a while! :)

**Comment by DylanC** [comment]
@andrewcharnley - No problem. I will check this on a later build shortly.  If I need more info I will come back and ask you if you don't mind.

**Comment by DylanC** [comment]
@andrewcharnley - Can you give instruction on how to reproduce this?

**Comment by DylanC** [comment]
@andrewcharnley - Tested in the daily build tonight and I can confirm this still exists.

**Comment by mikelacsa** [comment]
I tested this with the latest version and it worked OK. Closing the issue now.
