### ISSUE TITLE
Can AVHCD videos be imported?

### ISSUE THREAD

**Issue by SKYEUNG** [OpenShot/openshot-qt#2224]
**My Question:**
Will this accept AVHCD format videos?

**System Details**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**Screenshots**

**Comment by DylanC** [comment]
@SKYEUNG - I think your best bet would be to just try it. @ferdnyc Do you know this off the top of your head?

**Comment by DylanC** [comment]
@SKYEUNG - We have a branch on here that is dedicated to hardware encoding. I've been told this will do it. However, it could be some time before that branch gets merged into the main project codebase.
