### ISSUE TITLE
Opeshot 2.4.3 video and mp3. The sound makes small cuts.

### ISSUE THREAD

**Issue by emilict** [OpenShot/openshot-qt#2226]
**Describe the bug**
When you incorporate an mp3 to a  video it slows down and the sound makes small cuts.

**System Details (please complete the following information):**
 - Operating System / Distro: Windows 10 64 bits
 - OpenShot Version 2.4.3.

**To Reproduce**
1. Import vídeo, place in the timeline.
2. Import audio mp3, place in the timeline.
Play vídeo.

**Comment by ctsdownloads** [comment]
Unreproducible, old version of OpenShot
