### ISSUE TITLE
[2.4.3] launch.exe crashes when opening a .mp4 file.

### ISSUE THREAD

**Issue by zenieldanaku** [OpenShot/openshot-qt#2229]
**Describe the bug**
The program freezes when trying to import a .mp4 file. I've tryed with the lastest version and the previews one, but I've got the same problem. I haven't tryed with other file tipes, though.

**System Details (please complete the following information):**
 - Operating System / Distro: Windows 7 Ultimate 32-bit
 - OpenShot Version: 2.4.3
 - Microprocessor: Sempron 140 (2.7 GHz)
 - RAM: 4 GB DDR 2

**To Reproduce**
1. Go to File menu
2. Click on Import File (or just click the icon in the toolbar, or press Ctrl+F)
3. Browse the file. Select and click on "Open".
4. See error: a complete freeze. 

**Expected behavior**
As far as I understand, it should place my mp4 file in the "Project Files" section.

**Screenshots**
No screenshots since it's a freeze, but I leave the crash report generated by windows 7 below.

**Logs**
Descripción:
  Este programa dejó de interactuar con Windows por un problema.

Firma con problemas:
  Nombre del evento de problema:	AppHangB1
  Nombre de aplicación:	launch.exe
  Versión de la aplicación:	0.0.0.0
  Marca de tiempo de la aplicación:	00000000
  Firma de bloqueo:	88b8
  Tipo de bloqueo:	0
  Versión del sistema operativo:	6.1.7601.2.1.0.256.1
  Id. de configuración regional:	11274
  Firma adicional de bloqueo 1:	88b858039bf67d3ccff6117a9a79fcc0
  Firma adicional de bloqueo 2:	ebb5
  Firma adicional de bloqueo 3:	ebb5779c88cc4ec5c61c6157b114f56e
  Firma adicional de bloqueo 4:	88b8
  Firma adicional de bloqueo 5:	88b858039bf67d3ccff6117a9a79fcc0
  Firma adicional de bloqueo 6:	ebb5
  Firma adicional de bloqueo 7:	ebb5779c88cc4ec5c61c6157b114f56e

**Additional context**
None.

**Comment by zenieldanaku** [comment]
Oh, I understand now. This program can't work with video directly, only stills. What a shame...

**Comment by DylanC** [comment]
@zenieldanaku - Yes, that's why its called "Openshot Image Editor"...
