### ISSUE TITLE
Scaling values do not always apply.

### ISSUE THREAD

**Issue by andrewcharnley** [OpenShot/openshot-qt#223]
I couldn't work this out, sometimes the end of a clip will have the values correctly set but the start of the clip as the same values yet is still using a value of 1. There appears to be no way to select the keyframe?

If there is, it's not intuitive. I can see the green markers but clicking/right clicking doesn't have any action.

**Comment by DylanC** [comment]
@andrewcharnley - Do you have a screenshot to show this?

**Comment by DylanC** [comment]
Closing since no more activity here.
