### ISSUE TITLE
Transition duration fails to change when I manipulate edges

### ISSUE THREAD

**Issue by DylanC** [OpenShot/openshot-qt#2231]
This issue is new (AFAIR I haven't seen it in 2.4.1): I just tried to add fade transition at the end of my video. Default transition duration is 10 seconds (and so quite long rectangle). When I make transition rectangle shorter to perform transition, say, in 1 second, internal player still performs 10 second transition. And when I start to move this shorter rectangle, it suddenly becomes long again.

So #640 is about incorrect brightness level at the edge of automatically created transition, while this bug is about transition duration that fails to change when you manipulate with edges of transition blue rectangle.

_Originally posted by @sknaumov in https://github.com/OpenShot/openshot-qt/issues/1966#issuecomment-429561767_

**Comment by MisterTeeXD** [comment]
This is my issue as well, dragging the sides to make it shorter and yet its still a 10 Second Transition

**Comment by MisterTeeXD** [comment]
This has to be added in the next version of Openshot

**Comment by amuellerde** [comment]
I have the same issue.
Change by mouse dosnt work.
i have moved this transition to a emty track, changed by preferences and move it back to.

**Comment by MisterTeeXD** [comment]
This has to be fixed

**Comment by lucianog1980** [comment]
Issue still happening on 2.4.3. Please we need to have this issue fixed, otherwise I will change to another software.

**Comment by MisterTeeXD** [comment]
Plz fix

**Comment by sknaumov** [comment]
@DylanC This bug was introduced by 81f274254f255742fc663c62ad9c9fa2a683d323 commit.
