### ISSUE TITLE
Adding fades makes the video & audio stutter

### ISSUE THREAD

**Issue by mjz2325** [OpenShot/openshot-qt#2232]
**Bug**

I have literally just downloaded OpenShot, and was experimenting with some video footage I have. At work, I use Camtasia, which was why I liked your user interface, as there are similarities. However, as soon as I dropped a fade-in onto my clip, and pressed play, everything stuttered until the fade-in was finished, then it was fine again. I have plenty of memory, plenty of disk space, and a fast machine, so this should not be happening. I have also tried multiple changes to the OpenShot preferences, including even increasing the allowed memory cache to 10GB, but all to no avail. Can anyone explain why this is happening please, and if there is a solution? 

**System**

MackBook Pro, Intel i7 Quad Core 2.2GHz, 16GB RAM, 750GB SATA HDD, OSX El Capitan 10.11.6, Intel HD Graphics 3000 512 MB (17" display). OpenShot version 2.4.3. 

**To Reproduce**

Drag & drop a fade transition onto a video clip, then play from before the fade. 

**Expected Behaviour**

What should happen, is everything just plays nice & smoothly, but what does happen, is that playback stutters badly, for the duration of the fade, then becomes smooth again immediately after the transition finishes. 

**Additional Context**

I have not tried other transitions, but I'm going to guess that it won't just be the fade it applies to. 
N.B. I notice that someone has posted the same issue with a Windows version (#2219), so it would appear to be an issue across platforms.

**Comment by DylanC** [comment]
Dup of #2220
