### ISSUE TITLE
Effects Tab Missing?

### ISSUE THREAD

**Issue by dansullyvans** [OpenShot/openshot-qt#2233]
I've been working on a video for a while now and i recently got the idea to add a VHS effect to it. So i went on YouTube looking for tutorials and all of them require the chroma key effect. However, my openshot doesn't seem to have the Effects tab. I've been using this program for about a month now so im fairly new, but i just can't seem to find it.

Im on 2.4.3  so i should have this feature, right?

![capture](https://user-images.githubusercontent.com/44141693/46919562-f1a23a00-cfae-11e8-9686-11b0ca6dd18b.PNG)

This is what i see whenever i open the program, as you can see im missing some stuff

I've reinstalled it and im still missing it

**Comment by peanutbutterandcrackers** [comment]
It seems you have reconfigured the layout to not have the 'effects' tab. But restoring everything is as easy as going to `Views` > `View` > `Simple View`, and you'll find the effects tab next to the project files tab (along with transitions). Hope that helps!

[Closing as answered]
