### ISSUE TITLE
Files not exporting fully

### ISSUE THREAD

**Issue by Alimentary** [OpenShot/openshot-qt#2234]
**My Question:**
When i export a mp4 only reaches a certain percent than the whole software shuts off.

**System Details**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1] windows 10
 - OpenShot Version [e.g. 2.4.1] recent

**Screenshots**

**Comment by DylanC** [comment]
@Alimentary - Can you give v2.4.3 a try? Its much better for exports.

**Comment by GreenBeeBlacksmithing** [comment]
I'm using v2.4.3, and mine freezes at 45%, then crashes. Also, when trying to play back what I've done it stops the playback about halfway through the video. I spent 4 hours trying to edit a 34-minute video down to under 5 minutes (a lot of me just standing around waiting for steel to get hot).

**Comment by GreenBeeBlacksmithing** [comment]
Good news is, I managed to make a 10-second intro and an exit card of 30 seconds.
