### ISSUE TITLE
fade-in and fade-out of clips leads to dull videos without or only partly fading

### ISSUE THREAD

**Issue by Walker10474** [OpenShot/openshot-qt#2235]
**Describe the bug**
When adding fading to a video clip or a title clip, it works in the preview like a charm. After exporting the project, the video clips with fading are dark and dull and without fading at begin/end. Title clips have normal colors and do fade in, but do not fade out.

**System Details (please complete the following information):**
 - Operating System: Ubuntu 16.04.5
 - OpenShot Version 2.4.3-dev1 from the OpenShot PPA repository

**To Reproduce**
1. Load project with video and title clips (example files are provided) or create a new and import a video clip
2. Left-click the clip to select
3. Right-click the clip, select "Fade" from the menu, "Entire Clip", "Fade In and Out (Fast)" or "Volume", "End of Clip", "Fade Out (Fast)"
4. Click "Export video", select profile "Web", target "YouTube", video profile "VGA NTSC (640x480)"

**Expected behavior**
The video and title clips should fade in at the beginning and fade out at their and, as shown in the preview. The audio clip should reduce the volume to zero at the end, as in the preview.

**Screenshots**
I've got videos for you.
First the video without any fading: https://www.youtube.com/watch?v=bt1ned2mSmc
Then the same video with added fade-in/fade-out at the video/title clips and volume-to-zero at the audio clip: https://www.youtube.com/watch?v=97hhItfnMvI

Here is the OpenShot project (zipped directory) with all project and media files used in the two videos: https://harhar.net/oc/index.php/s/OxvJCj5V0bP5xfV

**Comment by DylanC** [comment]
Dup of #2220

**Comment by Walker10474** [comment]
Hm, I would say #2220 describes a totally different effect: Half of the audio is missing instead of lowering the volume.

In my case, the volume is not changed at all, so there is unwanted the full audio instead of the last seconds being unhearable -- but the main problem is that the video fading in/out does only work in preview, but does not work at all in the exported video.

**Comment by DylanC** [comment]
@Walker10474 - Fair enough. I guess this is separate then.
