### ISSUE TITLE
What is this green bar that shows up when I export my project

### ISSUE THREAD

**Issue by marijn26** [OpenShot/openshot-qt#2238]
**My Question:**
Whenever I play my video in Openshot, it looks perfectly fine. But when I export it, the video flickers and has this huge green bar popping up. What should I do to fix this?

**System Details**
 - Operating System / Distro: Windows 10
 - OpenShot Version 2.4.3

**Screenshots**
![untitled](https://user-images.githubusercontent.com/44159532/46941018-6b4b2e00-d06a-11e8-837f-40a66cdc751e.png)

**Comment by DylanC** [comment]
@marijn26 - I'm not sure to be honest. @peanutbutterandcrackers - Did we ever see this happen anyone? o_O
