### ISSUE TITLE
OpenShot is below zero

### ISSUE THREAD

**Issue by Shatsan** [OpenShot/openshot-qt#2239]
This program should be really improved because the user interface and the features are excellent. However, it constantly has lags, sometimes even crashes, and the video exporting is always incorrect like losing the audio, or stopping the picture. Because of the fact that my pc is designed for animating and rendering, a simple video editing should be nothing impossible to process. Openshot is below the description of an unusasble pile of trash.

**Comment by DylanC** [comment]
@Shatsan - Yes, it should be improved. That is what the project is working on. v2.4.3 has been a great release and we have much great feedback on exports now working for people which failed in previous versions. Thanks for the feedback. 👍
