### ISSUE TITLE
Zoom needs greater zoom!

### ISSUE THREAD

**Issue by andrewcharnley** [OpenShot/openshot-qt#224]
It's not enough for fine tweaking when working with milliseconds. I had three clips and ended up aligning them by value input when moving and testing would have been much easier. The lack of zoom does not allow it.

**Comment by Kagetsuki** [comment]
THIS! The highest granularity I can get is 8s per tick and I've got a lot of places that are under 1s. It's like trying to play with Lego with mittens on.

**Comment by daneel6672** [comment]
Agree - in version 1.4.3 the maximum zoom is 1 second which is really useful for aligning clips. Why did you increase this to 8 seconds? Please change it back!

**Comment by stolk** [comment]
OpenShot 1.4 could zoom further in than OpenShot 2.1.0 can.
Please increase max zoom level.

**Comment by DylanC** [comment]
@andrewcharnley - Does this issue still exist on v2.3.4 of OpenShot?

**Comment by DylanC** [comment]
@andrewcharnley - This will be tracked in #160
