### ISSUE TITLE
Crashes when importing videos from my phone with mp4 

### ISSUE THREAD

**Issue by mitchlee31** [OpenShot/openshot-qt#2240]
**Describe the bug**

**System Details (please complete the following information):**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**

**Comment by DylanC** [comment]
Google Translate..

I have the latest version of openshot 2.4.3 and crashes when importing videos from my phone with mp4 file

**Comment by zenieldanaku** [comment]
I had a similar problem, but then i closed the issue because i understood that i was asking more than the program is capable of.

**Comment by DylanC** [comment]
@zenieldanaku - Openshot uses ffmpeg. It supports all ffmpeg formats:
http://www.ffmpeg.org/general.html#Video-Codecs

@mitchlee31 - Do you have more file details on your mp4 file? Details like resolution and frames per second?

**Comment by zenieldanaku** [comment]
@DylanC Apparently not my Samsung Galaxy J1 Ace MP4 videos, for some reason.

**Comment by DylanC** [comment]
@zenieldanaku - I've added this to a priority list. Its been reported a few times so there must be an issue with the type of mp4 phones are producing. Hopefully this will be fixed for the next release.

**Comment by DylanC** [comment]
Dup of #2114
