### ISSUE TITLE
Program keeps Freezing Please Help

### ISSUE THREAD

**Issue by ToddWe** [OpenShot/openshot-qt#2242]
**Describe the bug**
I import some video files i took from my Google Pixel phone, get about a minute into edited video, about 5 imported files, and the replay starts running REAL slow.  Then if i add more files it just freezes up during playback.  I tried shutting down, and exporting the existing work, and it got to 99 percent and froze up.... 
I really want to love this program.

**System Details (please complete the following information):**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1] WIndows 10
 - OpenShot Version [e.g. 2.4.1   version ]2.4.3

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**

**Comment by ctsdownloads** [comment]
Unreproducible, old version of OpenShot
