### ISSUE TITLE
Cannot click Next on timeline tutorial

### ISSUE THREAD

**Issue by kruzer-bruzer** [OpenShot/openshot-qt#2244]
**Describe the bug**
The timeline tutorial description bar will not go away due to the "next" button being off of my screen and then when i tried to restore down on it, I still could not see the "next" button

**System Details (please complete the following information):**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**

**Comment by t3nchi** [comment]
yep that happened to me aswell, so I uninstalled the program, and reinstalled it, and when I run the program, I just checked the "Hide tutorial" box. Hope this help.

**Comment by DylanC** [comment]
@kruzer-bruzer - This issue is similar #2170. Checkout the link posted on it:

https://github.com/OpenShot/openshot-qt/wiki/Workarounds-for-Known-Bugs#timeline-tutorial-popup-extends-off-bottom-edge-of-screen

**Comment by peanutbutterandcrackers** [comment]
Closing this as answered.
