### ISSUE TITLE
error with wmv format

### ISSUE THREAD

**Issue by nuranga** [OpenShot/openshot-qt#2245]
**My Question:**

I have a Portable version of Openshot, and I am using Windows. When I import wmv files to the programe it does not work. When I put the file in the track or timeline, the video shows a still image and is not running well.

Why could this be?

**System Details**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**Screenshots**

**Comment by DylanC** [comment]
@nuranga What version of Openshot do you have?

**Comment by nuranga** [comment]
Is a Portable version 2.2.1.0 and I am using it in Windows 10

**Comment by DylanC** [comment]
@nuranga - Can you try v2.4.3 to compare results?

**Comment by nuranga** [comment]
Sorry, I have been really busy and I could´t  answerd te message before . Really sorry. 
I have tried with the version that you told me ( v2.4.3) and it works. So the problem is with my portable version (Portable version 2.2.1.0)  isn´t it? Is it possible to solve the problem there (in the portable version)?

Thank you so much for everything

**Comment by DylanC** [comment]
@nuranga - Yes the problem is with that portable version. Can I ask where did you get this "Portable" version from?

**Comment by nuranga** [comment]
It was given to me from a friend, he took it from https://portableapps.com/

**Comment by DylanC** [comment]
@nuranga - I see. Well if you want to use that portable version you will need to wait until they update it to v2.4.3. The portable version is very old.
