### ISSUE TITLE
Missing Function Visiblility Video/Picture and Audio in Tracks

### ISSUE THREAD

**Issue by olissongs** [OpenShot/openshot-qt#2246]
This features are gone

![bildschirmfoto vom 2018-10-16 15-42-12](https://user-images.githubusercontent.com/1310153/47020748-564dc800-d15a-11e8-9309-e2ce5dadb44d.png)

this features are great helpers for creative work testing some versions

why dropped?

**Comment by olissongs** [comment]
Ok i understand, hard job. So sometime this feature will be back again, great!

**Comment by CardboardComputers** [comment]
Pretty sure there's no quick way to mute or hide an entire track, but to mute or hide a clip without changing the volume or alpha, you can set "Enable Audio" or "Enable Video" to 0.

**Comment by ferdnyc** [comment]
Closing as duplicate of #784. (We'll keep that one open to track this.)
