### ISSUE TITLE
v2.4.3: opening old version project, title show incorrect layout...

### ISSUE THREAD

**Issue by valterfukuoka** [OpenShot/openshot-qt#2248]
**Describe the bug**
When I open a project created with old version 1.4.3 (Debian 9 Stretch repository), the titles shows incorrect layout...
The first line of the title seems to align to the right, when it should be in the center...

**System Details (please complete the following information):**
 - Operating System / Distro: Debian 9 Stretch
 - OpenShot Version [e.g. 2.4.3 app image linux]

**To Reproduce**
1. Opening a old v1.4.3 project with the new v2.4.3 Openshot, the title shows incorrect layout...

**Expected behavior**
The first line of the title seems to align to the right, when it should be in the center...
If I open the .svg file with InkScape, or Gimp, or Firefox, the correct layout is displayed, so the .svg file is probably correct...

**Screenshots**
First image is using the the old v1.4.3
![v1 4 3](https://user-images.githubusercontent.com/5293980/47061336-fd3e6c80-d20b-11e8-8335-881b53fb31cf.png)

Following image is using new v.2.4.3
![v2 4 3](https://user-images.githubusercontent.com/5293980/47061378-1f37ef00-d20c-11e8-8e2c-b079ec6adeb0.png)

Thanks,
Valter Fukuoka

**Comment by peanutbutterandcrackers** [comment]
Sorry but OpenShot 2.x series isn't backwards compatible with 1.x series. In fact, it has been rewritten using completely different multimedia framework. You'll have to edit 1.x osp files 1.x program and 2.x ones with 2.x.

Hope that clears things up.

Closing this as answered.
