### ISSUE TITLE
Clip X,Y ignored on animation. 

### ISSUE THREAD

**Issue by andrewcharnley** [OpenShot/openshot-qt#225]
Since animation overrides these there is no way to set X,Y (doesn't do anything). How about a padding attribute (left,right,top,bottom)?

I've worked around it by adding space to the png's used in the vid but it's quite annoying!

**Comment by jonoomph** [comment]
Please retest with the latest daily build of OpenShot 2.x. Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot. It sounds like you might be using an old version of OpenShot by your comment. Hopefully the latest version will work great for you.
