### ISSUE TITLE
Photo rotated

### ISSUE THREAD

**Issue by kccomdoc** [OpenShot/openshot-qt#2250]
When Importing pictures some of the photos show up sideways.  These were originally sideways and I rotated them with a photo editor.  When impororting they are rotated back.  How do I get them rotated correctly in the open shot video editor?

**System Details**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**Screenshots**

**Comment by DylanC** [comment]
@kccomdoc - What version of Openshot are you using?

**Comment by peanutbutterandcrackers** [comment]
Could you please provide us some sample of the photo files affected by this issue? Thank you!

**Comment by seffyroff** [comment]
I'm seeing the same thing here.  Some Portrait/Landscape and some that are 180 rotated.  For the record I think there's some silent lossless rotation going on at the OS level (Win10).

**Comment by ferdnyc** [comment]
I'm going to close this as a duplicate of #2794 / #2969, which contain the most detail on this issue.
