### ISSUE TITLE
Tells you if audio is peaking

### ISSUE THREAD

**Issue by speedytechdev** [OpenShot/openshot-qt#2258]
**Is your feature request related to a problem? Please describe.**
I was working on sound for my video and the audio sounded fine in the editor but when I exported it the sound was peaking.

**Describe the solution you'd like**
A way to tell if my audio is peaking like a line mixer or even an alert.

**Additional context**
Something like this https://imgur.com/a/VwM68XX and it would go red if you are peaking.

**Comment by bobcrikey** [comment]
This would be very useful :)
