### ISSUE TITLE
openshot dev version 18th oct working great

### ISSUE THREAD

**Issue by bobcrikey** [OpenShot/openshot-qt#2260]
Hello  @DylanC , thanks for your audio work in the latest dev and the other dev's.
 11 tracks 2 chromakeys, 3 animations, 3 audio tracks. No crackling Sounds not a one.
and export is perfect sound.
thankyou thankyou thankyou mate.

working great on linux mint 18.3/19 and windows 10.
cheers bob.

**Comment by DylanC** [comment]
@bobcrikey - I'm delighted to hear the news but we have not done much yet on the audio front. :laughing: I'm not sure why its working better for you but I'm happy to hear it. :+1:

**Comment by bobcrikey** [comment]
hello @DylanC , I spoke too soon mate, today the crackling came back on  linux. 
It is strange though, maybe something in the latest dev version fixed something but not others
but do keep working on that crackling sound problem.

I really thought you had fixed the audio problems quick like, so i got excited when i had my 11 tracks
working in sync harmony.
As you know i only use openshot for my animation short movies. im well under way working hard for
episode 2 at the moment, iv just finished in blender 3d At-At walker actually walking , but that will be brought into openshot for final compositing :)

cheers bob

**Comment by DylanC** [comment]
@bobcrikey - Don't worry we will work on that area. I only wish I knew why things were working so great for you in that moment. 😆
