### ISSUE TITLE
The program doesn't open

### ISSUE THREAD

**Issue by merililla** [OpenShot/openshot-qt#2263]
**My Question:**
I installed OpenShot 2.4.3 on D disk of my pc (the C one is almost full). 
When I try to open it an error window appears (see screenshot). 
I tried to install it as administrator. The same error.
I tried to install it as administrator in C. The same error. 
What can I do???

Thankyou

**System Details**
 - Operating System / Distro: [ Windows 7]
 - OpenShot Version [2.4.3]

**Screenshots**

![errore openshot](https://user-images.githubusercontent.com/44317002/47255030-94086480-d46a-11e8-9460-cf820c578fee.jpg)

**Comment by DylanC** [comment]
@merililla - Not sure, I think it would be best to install on C: drive anyway.

**Comment by peanutbutterandcrackers** [comment]
You could perhaps try deleting the `.openshot_qt` folder in your home folder.

Or, if you like portable apps: https://portableapps.com/node/59167
