### ISSUE TITLE
Openshot 2.4.3 on OSX crashes when try to import a video

### ISSUE THREAD

**Issue by soledelsud** [OpenShot/openshot-qt#2268]
Openshot 2.4.3 on OSX crashes when try to import a video.
I have tried it with different video Format.

**System Details (please complete the following information):**
Operating System: OSX 10.12.6
OpenShot Version 2.4.3 dev1 - 1539029164-31e9e7b6-750d7a3f-x86_64

Also with 2.4.1 in 2.4.2 crashes

**To Reproduce**
1. Go to -> File
2. Import file
3. select Video and click to import
4. OpenShot ... crashes

**Logs**
I can not find any Log/Crash-Information about OpenShot in the Console of my OSX.

**Comment by DylanC** [comment]
Dup of #2114
