### ISSUE TITLE
cx_Freeze: Python error in main script

### ISSUE THREAD

**Issue by opencobalt** [OpenShot/openshot-qt#2269]
**Describe the bug**
Did clean install (first time). Tried to start after install. and failed raising this error.

**System Details (please complete the following information):**
 - Win 8.1 64 Bit
 - OpenShot 2.4.3 64 Bit

**To Reproduce**
1. Clean install
2. Start program

**Expected behavior**
Programm starts up without error.

**Screenshots**
![os-error](https://user-images.githubusercontent.com/14311876/47269739-6dc5f000-d562-11e8-9ae7-63ce1a1e91b1.png)

**Logs**
No logs found in main dir. of program.

**Add. infos**
I just noticed, I have no msys64 folder in C:\. Well, maybe this is important.

**Comment by peanutbutterandcrackers** [comment]
Please delete the `.openshot_qt` folder in your home folder; deleting it has been known to solve quite a lot of similar issues.

Hope that helps.

Please don't forget to close this if this has been resolved. Thank you!
