### ISSUE TITLE
Quality settings on the exported file do not work.

### ISSUE THREAD

**Issue by michelemaria** [OpenShot/openshot-qt#2270]
Non funzionano le impostazioni di qualità sul file esportato.
Qualunque sia il livello scelto tra basso, medio e alto, i bitrate in uscita non cambiano.
Funzionava tutto bene fino a 15 gg fa, adesso non piu.
Versione 2 4 3 windows 10
Per favore qualcuno risponda grazie.
Ho già reinstallato ma non cambia nulla.

**Comment by LeosWelt** [comment]
Translation via Google:

Quality settings on the exported file do not work.
Whatever level you choose between low, medium and high, the output bitrates do not change.
Everything worked fine up to 15 days ago, now not anymore.
Version 2 4 3 windows 10
Please someone answer thank you.
I have already reinstalled but it does not change anything.

You should tell what output format (MP4, AVI...) you have choosen, what Profile, look inside "Advanced" what bitrates are choosen.

**Comment by michelemaria** [comment]
Output:

MP4 h264

Full hd P 30 Frame

File outpot do no respect bitrate insert into advanced option

**Comment by DylanC** [comment]
Answered in #2300
