### ISSUE TITLE
Issue installing daily build (October 18

### ISSUE THREAD

**Issue by wisemanlove** [OpenShot/openshot-qt#2271]
Delete file failed: code 5

**System Details (please complete the following information):**
 - Operating System / Distro: Windows10
 - OpenShot Version: 2.4.1

Try and download the daily build to fix audio and file location issues but unable to install it. 

![screenshot 13](https://user-images.githubusercontent.com/43181695/47305126-6fee8400-d620-11e8-835a-853502f4b78e.png)

**Comment by DylanC** [comment]
@wisemanlove - This daily build does not correct the audio. False report im afraid.
