### ISSUE TITLE
Add a DBUS interface for executing commands (InkScape) outside Flatpak's sandbox

### ISSUE THREAD

**Issue by ghost** [OpenShot/openshot-qt#2273]
"Use Advanced Editor" in the titles editor fails with "Please install inkscape to use this function". Inkscape is installed at /usr/bin/inkscape, and /usr/bin is in environment variable PATH. In OpenShot Preferences, "Advanced Title Editor" is set to "inkscape".

**System Details**
 - Operating System / Distro: [Linux Mint 19]
 - OpenShot Version [2.4.3]
 - Inkscape Version [0.92]

**Comment by eszlari** [comment]
This is because you are running the flatpak version (https://flatpak.org).

There is a DBUS interface for executing commands outside flatpak's sandsbox (https://github.com/flatpak/flatpak/blob/master/data/org.freedesktop.Flatpak.xml). The OpenShot developers would have to add support for it.

**Comment by peanutbutterandcrackers** [comment]
@eszlari - Could you make a PR to address this issue, good sir?

**Comment by eszlari** [comment]
@peanutbutterandcrackers Unfortunately, I lack the skills to do that.

**Comment by peanutbutterandcrackers** [comment]
I'll mark this as an 'enhancement' just so that we can see that we need to integrate the DBUS interface for our flatpak users.
