### ISSUE TITLE
Video will not upload to YouTube

### ISSUE THREAD

**Issue by DrRickJ** [OpenShot/openshot-qt#2274]
**My Question:**

This saves as an osp file. YouTube says this is not a supported file type. How do I either save it as an mp4 or other supported file or change the file from osp to a supported file type?﻿

**System Details**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**Screenshots**

**Comment by DylanC** [comment]
@DrRickJ - You will need to Export the video. Use the Youtube profile for the export.

**Comment by DylanC** [comment]
@DrRickJ - File >> Export Video.

**Comment by DrRickJ** [comment]
When I tried Web, then YouTube, it only exported 15 seconds of video. So I
tried Web, then YouTube-HD, and it has been uploading a video for 12 hours
and is at 50%.

**Comment by peanutbutterandcrackers** [comment]
@DrRickJ - Perhaps you could try exporting it to default targets?
