### ISSUE TITLE
Is there a way to add new effects?

### ISSUE THREAD

**Issue by LeosWelt** [OpenShot/openshot-qt#2277]
**My Question:**
There are many effecs available in mlt and/or frei0r, is there a way to add more effects like described for the old openshot?

**System Details**
 - Operating System / Distro: [Arch Linux 64Bit LTS]
 - OpenShot Version [2.4.3]

**Screenshots**

**Comment by DylanC** [comment]
@LeosWelt - No, I don't think so. I think the effects in this version are custom developed. It will take some time to add more effects.
