### ISSUE TITLE
ASF file previews in slow motion

### ISSUE THREAD

**Issue by ajbogh** [OpenShot/openshot-qt#2279]
**Describe the bug**
An ASF file may preview in slow motion, causing disk churn (noisy hard drive). Converting the ASF to MP4 solves the issue, but this solution seems unnecessary. I'm not sure if a timeline with ASF files that cause this problem exports correctly or if there's corruption in the rendered output.

**System Details (please complete the following information):**
 - Ubuntu 18.04
 - OpenShot 2.4.1

**To Reproduce**
1. Add an ASF file to the timeline
2. Preview the ASF file by pressing the Play button in the preview screen
3. Notice the ASF file plays slow and that the hard drive seeks excessively (only noticed on HDD, did not try on SSD)
4. Add MP4 files to see them play at normal speed
5. Convert ASF file to MP4 using VLC or another program, add that video to the timeline, notice it plays at normal speed.

**Expected behavior**
ASF files should play at normal speed and not use up the hard drive.

**Additional context**
Original video files were from various game cams (Bushnell)

**Comment by ctsdownloads** [comment]
Unreproducible, old version of OpenShot
