### ISSUE TITLE
PPA Problem - no files found

### ISSUE THREAD

**Issue by axpa** [OpenShot/openshot-qt#228]
Hello, I followed your suggestion about "how to insert a PPA repository" exactly on Vers. 2.07 of openshot on your website. The Key has been installed by my computer without any problems. But when I tried "sudo apt-get update" it reclaims that the routine couldn't find any files:
 W: Fehlschlag beim Holen von http://ppa.launchpad.net/openshot.developers/ppa/ubuntu/dists/sid/main/binary-amd64/Packages  404  Not Found
and
W: Fehlschlag beim Holen von http://ppa.launchpad.net/openshot.developers/ppa/ubuntu/dists/sid/main/binary-i386/Packages  404  Not Found

So how can I fix this ?
I am using Linux elementary-OS 3.2 wich is build upon debian with kernel 14.04, 64-bit
Thank's in advance

**Comment by Kagetsuki** [comment]
The PPA is resolving to sid, which is probably a problem with what your elementary-OS build is tied to. Sid is pretty old, so either you should update your OS (I don't know about elementary) or try manually changing 'sid' to something newer in your apt source list entry (I'm guessing for you it will be `/etc/apt/sources.list.d/openshot_developers-ubuntu-ppa-sid.list`).

**Comment by Kagetsuki** [comment]
@jonoomph This issue appears to be stale - it should be closed and @axpa should re-open it if he returns and still can not resolve it.

**Comment by axpa** [comment]
Sorry for waiting that long. I had to work a couple of weeks outside the reach of any internet connection.

@Kagetsuki     the sources.list are exactly were you guessed them. 
                        My OS is updated already to the latest of Debian 14.04 Lt.
                        If you suggest to update to let`s say to Debian 16.04 or 16.1 that's a problem. Because elementary OS is not ready for it yet.
So how can I make the PPA resolving to something newer/else by hand ? 
I haven't a clue what it could be.
Btw: I'm unfearful to use the console...

Thank's

**Comment by Kagetsuki** [comment]
You can try to force it by manually changing to something newer than "sid" in the apt line in sources.list, doing apt-get update, and then trying apt-get install. The thing is PPA builds are tied to the system they are versioned for, so if you have an older system it's very possible the newer PPA build will not be able to install due to older or missing dependencies.

If changing "sid" in the apt entries to something newer doesn't work, it may be a better idea to just build by hand.

**Comment by axpa** [comment]
Well, as I mentioned bevor, I haven't a clue with what I could change "sid".
Is there a way to get the source ? Then I could build it by hand.
Thank you.

**Comment by axpa** [comment]
Sorry, of course I found the source. I will try it out tomorrow. I must leave by now. And yes, I give you a report what happened.
Thank you very much.

**Comment by ankitpati** [comment]
The PPA works fine now.

Closing this issue as fixed. Please reopen if necessary.
