### ISSUE TITLE
Cannot change Title font

### ISSUE THREAD

**Issue by Chris2228** [OpenShot/openshot-qt#2280]
Bonjour,
Openshot 2.4.3 linux mint 19 Tara
Impossible de changer les polices d'écriture

**Comment by speedytechdev** [comment]
Google translate:

Heading: font
Hello
Openshot 2.4.3 linux (mint 19 Tara)not sure what this means
Can not change the fonts

**Comment by speedytechdev** [comment]
@Chris2228 
Pouvez-vous entrer dans plus de détails s'il vous plaît. Par exemple, seule la police Arial fonctionne.
(Hopefully that makes sense)

**Comment by Chris2228** [comment]
Seul la police par défault fonctionne, a savoir : Bfont, toutes les autres ne fonctionnent pas du tout

**Comment by speedytechdev** [comment]
google translate: 
Only the default font works, namely: Bfont, all the others do not work at all

**Comment by sersha** [comment]
The same problem persists with OpenShot-v2.4.3-x86_64.AppImage on Linux Mint 19.1 fully patched. Cannot change any title font, in size or in font itself. Makes unfortunately very good program in practice unusable...
