### ISSUE TITLE
Crash on cutting a Video [v2.4.3] [Win10 64 bits]

### ISSUE THREAD

**Issue by Areidz** [OpenShot/openshot-qt#2282]
Hello, I wanted to try OpenShot in Windows 10  64 bits (lastest update), and it's crashing when I try to cut a video. The video is just one minute of a 1080p 30fps footage, x264 codec.

Also, if I want to play the video, after one minute, the video stops playing (sometimes also the sound), and the program becomes unstable.

I've tried to wipe the installation and reinstall it, but the problem is still there.

**System Details:**
 - Operating System / Distro: Windows 10 Home, 64 bits, comp 17134
 - OpenShot Version: 2.4.3 (stable)
 - RAM: 8GB

**Logs**
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2514665/openshot-qt.log)

**Comment by ctsdownloads** [comment]
Unreproducible, old version of OpenShot
