### ISSUE TITLE
Can't read sound files with APE, WV and FLAC format

### ISSUE THREAD

**Issue by Nelson-Lemercier** [OpenShot/openshot-qt#2284]
**Describe the bug**
In the FFmpeg documentation (https://www.ffmpeg.org/general.html) in the section Supported File Formats, Codecs or Features -> Audio codecs, the APE (Monkey's Audio), WV (WavPack) and FLAC (Free Lossless Audio Codec) seems supported but when I try to play a sound of one of this format, the player freeze at the beginning of the sound and Openshot become bery slow and have difficulties to respond.

**System Details (please complete the following information):**
  - openshot-qt version: 2.4.3
  - libopenshot version: 0.2.2
  - platform: Windows-10-10.0.17134
  - processor: Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
  - machine: AMD64
  - python version: 3.6.4
  - qt5 version: 5.9.1
  - pyqt5 version: 5.9

**To Reproduce**
1. Download an APE, WV or FLAC sound file
2. Import it on a new Openshot project
3. Add it on one of the channels
4. Try to play it
5. It should stop at the beginning of the sound file and freeze.

**Expected behavior**
The sound should be played like any other sound files with supported format.

**Screenshots**

The player freeze at the beginning of the sound

![freeze](https://user-images.githubusercontent.com/42967865/47513853-c3164000-d887-11e8-84b3-8fe8c5658267.png)

**Logs**

I'm not sure there is someting interesting in the log

[freeze log.log](https://github.com/OpenShot/openshot-qt/files/2515821/freeze.log.log)

**Comment by DylanC** [comment]
Dup of #1480
