### ISSUE TITLE
Waveform dissapear.

### ISSUE THREAD

**Issue by stephi1993** [OpenShot/openshot-qt#2285]
when working with sound, and cutting according to sound, the waveform dissapear. When trying to re-create it, it just makes a flat line 

Win 10 Pro
OpenShot Version 2.4.3

![image](https://user-images.githubusercontent.com/44484004/47536293-8d8d4900-d8bf-11e8-9929-395786bdb72f.png)

**Comment by DylanC** [comment]
@stephi1993 - Confirmed. If you split a clip in two it seems to happen on the second clip.

**Comment by w2aew** [comment]
This also happens if you trim the clip by moving the left edge.

**Comment by Samv2005** [comment]
Uninstalling and reinstalling worked for me
