### ISSUE TITLE
Project stops being played and closes itself in the middle of a transition between two videos

### ISSUE THREAD

**Issue by Goodman29** [OpenShot/openshot-qt#2286]
**Describe the bug**

**System Details (please complete the following information):**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**

**Comment by DylanC** [comment]
@Goodman29 - What version are you using?

**Comment by DylanC** [comment]
@Goodman29 - This has been fixed in v2.4.3 anyway. I suspect you are using an older version like v2.4.2.
