### ISSUE TITLE
Empty .blend Files

### ISSUE THREAD

**Issue by MrTeeXD** [OpenShot/openshot-qt#2287]
**Describe the bug**
When opening a blender file, it will bring a empty file instead of actual objects

**System Details (please complete the following information):**
 - Operating System / Distro: [Windows 10]
 - OpenShot Version [2.4.3 Latest Daily Build]

**To Reproduce**
1. Go to the folder location to where the Blend files are
2. Double Click on one of the Files
3. See error by looking at the empty blend files

**Expected behavior**
The files should have contained something

**Screenshots**
![screenshot 78](https://user-images.githubusercontent.com/37266538/47585933-0f807f00-d95f-11e8-9ae9-4c54e1dabdf7.png)

Here is a screenshot from one of them

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**
I think this is also in other daily builds

**Comment by peanutbutterandcrackers** [comment]
I don't quite understand this issue. I think the .blend files are just scripts that, when run, will output images, but just by themselves aren't anything more than just scripts.

If you can explain it further (if I am misunderstanding) please do.

Else, I think you (or I) could close this one.
