### ISSUE TITLE
[Critical] Effects Drops Performance

### ISSUE THREAD

**Issue by MisterTeeXD** [OpenShot/openshot-qt#2289]
**Describe the bug**
When applying effects for your clips on the timeline, it slows down the preview so much and affects the rendering process

**System Details (please complete the following information):**
 - Operating System / Distro: [Windows 10]
 - OpenShot Version [2.4.3 Latest Daily Build]

**To Reproduce**
1. Go to Effects
2. Click and drag any effect into your video clip
3. See error by playing back the video clip containing the effect

**Expected behavior**
The preview should run smooth and does not affect the rendering process

**Screenshots**
None

**Logs**
None

**Additional context**
This was in all the Openshot Versions

**Comment by DylanC** [comment]
Dup of #2153

**Comment by peanutbutterandcrackers** [comment]
Closing this duplicate. Discussions to be followed at #2219
