### ISSUE TITLE
Would like to register on forum

### ISSUE THREAD

**Issue by lacogada** [OpenShot/openshot-qt#2292]
**My Question:**
Would like to register on forum but see know way to do that.
Only see Login button.

Referring to this location
http://openshotusers.com/forum/

**System Details**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**Screenshots**

**Comment by DylanC** [comment]
@lacogada - I'm not 100% sure but I think the forum needs lots of work. @peanutbutterandcrackers - Would I be correct on this matter?

**Comment by lacogada** [comment]
Yes ... you are correct.
--------------------------------------------
On Wed, 10/31/18, DylanC <notifications@github.com> wrote:

 Subject: Re: [OpenShot/openshot-qt] Would like to register on forum (#2292)
 To: "OpenShot/openshot-qt" <openshot-qt@noreply.github.com>
 Cc: "lacogada" <lacogada@yahoo.com>, "Mention" <mention@noreply.github.com>
 Date: Wednesday, October 31, 2018, 3:45 AM
 
 @lacogada - I'm
 not 100% sure but I think the forum needs lots of work. @peanutbutterandcrackers
 - Would I be correct on this matter?
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by trt1** [comment]
Hi,
I'm also interested in joining the OpenShot forum, but no way.

**Comment by DylanC** [comment]
@lacogada @trt1 @peanutbutterandcrackers  - Marking this as a bug so we can hopefully solve it in the future.

**Comment by peanutbutterandcrackers** [comment]
@DylanC - I did have someone from twitter volunteering to fix the entire thing. I guess we'll just have to wait for some more time before we can take him in...

**Comment by lacogada** [comment]
oo
My time is 0:00.88opp from Yahoo Mail on Android

**Comment by ferdnyc** [comment]
"Thanks, talking clock!"

I'mma lock this discussion as it seems like @lacogada may have suffered some sort of account compromise, and anyway the discussion here has no real likelihood of progressing any further. The old forum is dead, long live the Subreddit. 

(More details in the project Wiki, if anyone somehow can't find their way to `/r/openshot` on their own.)
