### ISSUE TITLE
Open shot do not run correctly quality file export

### ISSUE THREAD

**Issue by michelemaria** [OpenShot/openshot-qt#2293]
Good morning, I have this pc:
intel core i5 4200 2.5 ghz
ram 4 gb
windows 10 version 1803
Since I upgraded open shot to version 2.4.3 the quality setting on the exported file no longer works.
any value imposed on the quality bit rate (low-medium-high) on the export file the value does not change and is always 20mb / sec
Any value imposed even in the advanced settings window does not do what is set.
Please, it's days that I write this on the forum but nobody answers.
Do I have to go back to a previous version to solve the problem?
how can I download it?
I have already re-opened open shot but nothing has been solved.
Please someone answer me what to do, it is absurd what does not work !!!!!!
Thanks, michele.

**Comment by DylanC** [comment]
Answered in #2300
