### ISSUE TITLE
Fast forward renders as freeze frame

### ISSUE THREAD

**Issue by SwadCam** [OpenShot/openshot-qt#2297]
Windows 10 Home
HP envy
Intel i7 8GB RAM
OpenShot V2.4.3

Sections of video with fast forward (X2) or slow (X1/4) play in preview correctly but render as freeze frame.
Tried Different resolutions QHD & 1080P MP4 and MOV but does the same.

Please help?
Mark

**Comment by SwadCam** [comment]
Found out that fast and slow forward work fine unless the video has been sliced.
I can use it OK if I slice the original to length then render that and import the clip back into the project.
Most reliable if I render just the clip slowed down or speeded up before using it in the main project.
Cheers,

**Comment by upsuper** [comment]
I have the same problem with OpenShot 2.5.1 on Ubuntu 19.10.

**Comment by SwadCam** [comment]
Sorry but this issue and constant crashes made me buy Power Director 17. Not Cheap but worksvery well.
Sorry OpenShot, wish you well with developments !

**Comment by SuslikV** [comment]
Usually this happens when input frame rate different from output.
