### ISSUE TITLE
Zoom animation not in exported video

### ISSUE THREAD

**Issue by tbrick52** [OpenShot/openshot-qt#2298]
**My Question:**
I am attempting to add zoom animation to my video clips by right clicking on the clip and clicking on Animation > Zoom > Start of Clip > Zoom in (100% - 150%). Then I right click on the same clip and click on Animation > Zoom > End of Clip > Zoom out (150% - 100%). It looks fine in the preview but the exported videos the effect is either shorter than the preview or not there at all.

What could I be doing wrong? 

**************
Update: I discovered the answer to my own question but I will keep this post open in case others are looking for the answer as well. 

I was exporting the video with these settings: 
Profile: Web
Target: YouTube-HD
Video Profile: HD 1080p 24fps (1920x1080)

I simply changed the Video Profile to  HD 1080p **30** fps (1920x1080) and it worked perfectly.
*******************

**System Details**
 - Operating System  Windows 10
 - OpenShot Version  2.4.3

**Comment by ctsdownloads** [comment]
Resolved by issue author.
