### ISSUE TITLE
Export quality setting not working

### ISSUE THREAD

**Issue by michelemaria** [OpenShot/openshot-qt#2300]
Good morning, it's days that I mark a problem and no one answers.
is absurd !!!!!
Is the solution to abandon your program and take another one?
Just say it, but at least answer.

Good morning, I have this pc:
Intel Core i5 4200 2.5 ghz
ram 4 GB
Windows 10 version 1803
Since I updated the release open to version 2.4.3, the quality setting on the exported file no longer works.
any value imposed on the quality bit rate (low-medium-high) on the export file the value does not change and is always 20mb / sec.
Any value imposed even in the advanced settings window does not do what is set.
Please, these are days that I write this on the forum but no one answers.
Do I have to go back to a previous version to solve the problem?
how can I download it?
I have already reopened the shot open but nothing has been resolved.
Please someone answer me what to do, it's absurd what does not work !!!!!!
Thanks, Michele.

**Comment by DylanC** [comment]
> Good morning, it's days that I mark a problem and no one answers.
is absurd !!!!!
Is the solution to abandon your program and take another one?
Just say it, but at least answer.

Its not really all that absurd. We have a life too and work full time jobs just like anyone else. 

> Since I updated the release open to version 2.4.3, the quality setting on the exported file no longer works.
any value imposed on the quality bit rate (low-medium-high) on the export file the value does not change and is always 20mb / sec.

I can test this but I can't find anyone else reporting this issue. Hopefully I can reproduce the problem. If there is a problem it will take time to solve. So perhaps you will need to use a different program for now.

**Comment by michelemaria** [comment]
Hello, I'm sorry if I insisted, I thought it was your job full time, I did not think it was a secondary activity, for this reason I'm sorry.
Actually I congratulate you on your program because it's really great.
Only since I moved from 2.4.2 to 2.4.3 I have this problem and I can not solve it.
I have to deliver videos within this week but I can not export them in the qualitative format that they ask me.
I try to solve with another program, do not worry, and I'm sorry again.

Greetings, michele.

**Comment by michelemaria** [comment]
Hello, I'm sorry but I'm crazy.
I did what you said but it still does not work.
MP4 input file 1920x1080 30 fps 17000 kbps
File output mp4 1920x1080 30 fps rises to 23000 kbps even if imposed low, medium, high.
I do not understand, until a month ago it was perfect, it respected whatever value you imposed.
Can it be because I have windows 1803 and not 1809?
The 1809 version does not let me see it in the udpate updates.
I'm sorry to bother you, but I've tried them all and it does not work anymore.
If you think of something, just let me know on the email stefaniap74@virgilio.it
Thanks, bye, michele.

**Comment by michelemaria** [comment]
Hello, I'm sorry but I'm crazy.
I did what you said but it still does not work.
MP4 input file 1920x1080 30 fps 17000 kbps
File output mp4 1920x1080 30 fps rises to 23000 kbps even if imposed low, medium, high.
I do not understand, until a month ago it was perfect, it respected whatever value you imposed.
Can it be because I have windows 1803 and not 1809?
The 1809 version does not let me see it in the udpate updates.
I'm sorry to bother you, but I've tried them all and it does not work anymore.
If you think of something, just let me know on the email stefaniap74@virgilio.it
Thanks, bye, michele.

**Comment by DylanC** [comment]
@peanutbutterandcrackers - Do the export quality settings work for you? o_O

**Comment by TheForslunds** [comment]
I have the same problem, Windows Home 10, 1809, 66-bit swedish, i allways get 18Mbit/s bitrate on 1080p 60fps, doesn´t matter if i chose low, med or high. I have tryed to change it in advanced to 8 Mb/s but it still exports in 18Mbit/s.
I have to use handbrake to reduce the bitrate to a "normal" value, 12min 1080p 60fps clip ends up to be way over 2GB and after i run it trough Handbrake (8Mbit) it shrinks to 750MB.
Does the quality setting work in Linux? (Considering dualboot)

**Comment by TheForslunds** [comment]
@DylanC - Have you noticed that i have the same problem as @michelemaria and i have found more people having the same issue when im google the problem.
At the moment i managing this problem with handbrake but it is an additional step.
//Tommy

**Comment by michelemaria** [comment]
OKK !!!!!!!!!!

Thank you very much !!!!

**Comment by peanutbutterandcrackers** [comment]
@DylanC - Sorry Cap'an, I didn't see this one. I will test this out when I have the time and get back to this. Hopefully, soon.

**Comment by peanutbutterandcrackers** [comment]
Hmm... I haven't gotten around to testing this, yet. But it seems something needs to be done about the bitrate settings in general... I might have to do a little more digging.

@michelemaria - It seems you are in need of a Video Editor. While OpenShot is not working for you, you could probably use [Kdenlive](https://kdenlive.org) or [Shotcut](https://shotcut.org) for the time being. As for this issue, let's hope that in the next release this one will be resolved. Also, if you want to learn about Free Software Projects like OpenShot and kdenlive and shotcut, this wikipedia article might be of some help: https://en.wikipedia.org/wiki/Free_software

**Comment by michelemaria** [comment]
hello, thank you, I hope that some of you solve the problem before the new version, the other programs you suggested are not as simple as yours.
and anyway the thing that I do not understand is that up until a few months ago those settings worked very well!
hi, look confident.
