### ISSUE TITLE
Cannot Open MP4

### ISSUE THREAD

**Issue by docpomus** [OpenShot/openshot-qt#2301]
**My Question:**
I just installed OpenShot 2.4.3 on Windows 10 and tried to open an MP4 file.
A message displayed "format unsupported"
Also, in the Profile menu there is no option for "AV Formats" (please see image)
![screenhunter 345](https://user-images.githubusercontent.com/33205669/47678491-32897980-db7f-11e8-96d0-eacaeec12979.jpg)

**System Details**
 - Operating System Windows 10
 - OpenShot Version 2.4.3

**Comment by Freimann1** [comment]
I posted what looks like a similar issue last night with 2.4.3. I managed to import the video file in .TS format (after fiddling with VCL and changing from .MP4). 

Tried to export after trimming.... again similar in another post .. although that post said "Export freezes at zero". I get a file with the extension I chose except the file is empty. MP4 is supposed to be their default export file format according to their tutorial.

Bit strange 2.4.3 can neither import or export the most common file format? I see someone said 2.4.1. may work?

Thanks

**Comment by peanutbutterandcrackers** [comment]
This is also strange indeed.

As a quick (possible) work-around, you could perhaps switch to using the [daily builds](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914)?

If that doesn't help, I'd advise you to attach the logs so that the devs can debug this.

**Comment by DylanC** [comment]
Dup of #2114
