### ISSUE TITLE
Zooming in and out of an image

### ISSUE THREAD

**Issue by Bethany0316** [OpenShot/openshot-qt#2302]
**My Question:**

I CANNOT for the life of me figure out how to zoom in and out of images slowly.

**System Details**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**Screenshots**

**Comment by peanutbutterandcrackers** [comment]
1. Please go through [this guide](https://gist.github.com/peanutbutterandcrackers/f0f666243133e0ed25abbc12a4ba23d7) first. Esp. the part about keyframes.
2. [Follow this video tutorial](https://www.youtube.com/watch?v=nEyrC1v-M1s).
3. Done!

Hope that helps. :+1: 

Closing as answered. Please feel free to re-open if you have any further queries.
