### ISSUE TITLE
A little sluggish but results were good.

### ISSUE THREAD

**Issue by helidude35** [OpenShot/openshot-qt#2306]
Hello.
This is my first experience with OpenShot. I Just found and downloaded 2.4.3
I had small problems but nothing like I have read here so I am happy and thankful.

My issues are simple, so I have read,  but here they are.
1. Slow to respond to mouse commands. Felt sluggish and kind of got in the way bit not impossible to deal with and accept.

2. Video preview play back is VERY choppy and does not give a good resemblance of the preview so I was making a lot of guess work and viewing shorter sections of video where the transitikns were.

3. Audio fade in and fade out did not work at all. No fade in and no fade out.

4. Trimming video clips was a little difficult as described in the first issue. Again not impossible to deal with.

After exporting the video the final result was just fantastic minus the audio fade but overall I am very satisfied.

I will be recommending OpenShot to my friends and let them know to make a donation for the work thats has been put into this great video editor.

**Comment by DylanC** [comment]
@helidude35 - Glad to hear you had a good experience. I have also had good experiences for my needs and I do think it will improve over time. We just need to focus on building up more of a team and better planning for releases.
