### ISSUE TITLE
Program closes when importing video or audio files - macOS 10.13.6

### ISSUE THREAD

**Issue by PVH-GiantGuy** [OpenShot/openshot-qt#2307]
**Describe the bug**
Openshot immediately closes when I import video or audio files (I know this is not a new issue, but wanted to add one more account of it)

**System Details (please complete the following information):**
 - Operating System: macOS 10.13.6
 - OpenShot Version: 2.4.3

**To Reproduce**
1. Built a project folder and included video files (mp4 and wmv), photos (png) and audio files (mp3)
2. Launched OpenShot video editor and saved the .osp OpenShot Project to the project folder
3. Imported 2 photo files
4. Tried to import a video file.
5. OpenShot application quits
6. No error message or error log
7. Tried this 3 times; same result each time

**Comment by OneCosmicGuy** [comment]
Just downloaded and tried this program... same problem. Glad I'm not the only one. I'm on OS 10.11.6

**Comment by DylanC** [comment]
Dup of #2114
