### ISSUE TITLE
Ping? Outstanding PRs in library repos...

### ISSUE THREAD

**Issue by ferdnyc** [OpenShot/openshot-qt#2308]
I hate to drop this _here_, but they haven't been getting any attention in the `libopenshot` or `libopenshot-audio` repos, and one or two of these are pretty critical (and relatively simple changes, too)... the other two are admittedly more trivial. But they're all really small patches, just a few lines each.

OpenShot/libopenshot-audio#19 fixes a bug that prevents `libopenshot` from _**compiling**_ under linux, at least with some compilers / library versions, and it's been sitting there four almost four full months now. (Not to mention, it's a FOUR-line change in a single header file.)

![image](https://user-images.githubusercontent.com/538020/47849599-aeb2d580-dda8-11e8-8d9f-2117001ae5c6.png)

I'm not alone, either. @alaviss has some CMake changes submitted to both repos since before most of my open PRs, and those are still waiting as well. The PRs need to be resync'd with the devel branch, but the changes look like they'd be nice to have, assuming Travis passes them...

**Comment by ferdnyc** [comment]
Links to all four PRs, for conveience:
* OpenShot/libopenshot-audio#29 : **Fix spelling of ASIO in CMakeLists.txt**
* OpenShot/libopenshot-audio#28 : **Remove Xinerama dependency**
* OpenShot/libopenshot#163 : **tests/CMakeLists: Use same dependencies as src/**
* OpenShot/libopenshot-audio#19 : **fix Juce header file's isfinite() semantics**

**Comment by DylanC** [comment]
@ferdnyc - Good luck with this! 😆

**Comment by ferdnyc** [comment]
:snowflake: chance in :fire:, I know... heck, just the idea that luck would be _involved_ or _necessary_... :angry:

**Comment by DylanC** [comment]
@ferdnyc @jonoomph - Correct me if I'm wrong but I think we have a new contributor coming on board to look at the lib PR's.

**Comment by ferdnyc** [comment]
All closed except the ASIO spelling one, which I think will haunt me to my grave. (My current plan is to just sneak the fix into a completely unrelated PR. 😇)
