### ISSUE TITLE
changing the file from osp to an mp4 file

### ISSUE THREAD

**Issue by offroadlegion** [OpenShot/openshot-qt#2319]
i cannot upload the video i edited on youtube because it is an osp file and i need it to be an mp4 file but i cant change it.

**Comment by peanutbutterandcrackers** [comment]
You need to export it, once you're done with the editing. To export, go to `File` > `Export Video`.

Hope that helps.

P. S: Here's an [OpenShot guide](https://gist.github.com/peanutbutterandcrackers/f0f666243133e0ed25abbc12a4ba23d7) for you.

Closing as answered. If you need any further help, please feel free to re-open this.
