### ISSUE TITLE
Openshot Crashes When Opening a Project or Starting a New Project

### ISSUE THREAD

**Issue by PrimordialHelios** [OpenShot/openshot-qt#232]
Making any changes to the project currently open, and then trying to open a project, or start a new project results in Openshot completely freezing on Windows 10 Home x64.

**Comment by jreynojustin** [comment]
Hi @PrimordialHelios,
Please make sure you have the latest version by downloading our latest daily installer:

1.  www.openshot.org/download - click '**Other Downloads**' link and grab the newest one
2.  Then enable 'Debug Mode (Verbose)' in the Preferences
3.  Quit OpenShot and delete both log files:
  - **/.openshot_qt/openshot_qt.log**
  - **/.openshot_qt/libopenshot.log**
4.  Re-launch OpenShot and trigger the crash as quickly as possible (to keep the log files small)
5.  Attach **both** log files here

Hopefully we can determine from the .log files what is happening (and crashing). Please also identify the operating system and version in which you are running the application and any specific steps to help reproduce this bug.

Once you obtain the necessary logs and other information please reply to the issue and we will try to recreate and address the issue.

Thanks for contributing feedback! We will close this issue until you respond back and reopen it.
