### ISSUE TITLE
OpenShot crashes on Fade Out

### ISSUE THREAD

**Issue by Xionbarzhad** [OpenShot/openshot-qt#2322]
**Bug Description**
Upon trying to add a fade out transition onto the end of my clip, I am getting an issue where OpenShot Video Editor locks up and no longer responds. Fade In works fine. 

**System Details:**
 - Operating System: Windows 10
 - OpenShot Video Editor Version 2.4.3

**To Reproduce**
1. Open/Create a single video clip placed onto "Track 0"
2. Place a Fade In transition (Fast/Slow) to the start of the clip.
3. Apply Fade Out transition (Fast/Slow) to the end of the clip.
4. OpenShot VE locks up, forcing user to hard close the program.

**Expected behavior**
Fade Out transition effect should be applied as easily as Fade In without hard locking OpenShot.

**Additional Information**
1. Because Fade Out is causing OpenShot VE to lock up, applying Fade to the Entire Clip will also result in OpenShot VE locking up.
2. Video Clip being used is about 1hr 37mins in length.

**Log Files**
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/2546062/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2546063/openshot-qt.log)

**Screenshots**

![pre fade](https://user-images.githubusercontent.com/44751644/47967291-618d6880-e021-11e8-878c-7c5f26a99992.jpg)
![fade in](https://user-images.githubusercontent.com/44751644/47967292-618d6880-e021-11e8-888a-7682a21c818d.jpg)
![pre fade out](https://user-images.githubusercontent.com/44751644/47967290-618d6880-e021-11e8-9ccd-92479cf124f7.jpg)
![fade out lock](https://user-images.githubusercontent.com/44751644/47967289-618d6880-e021-11e8-9cc2-a6c0913e6dcf.jpg)

**Comment by Xionbarzhad** [comment]
Thought I was giving it a while when doing this but perhaps I wasn't giving it enough time.
Next video I work on of similar length I'll see if it applies it after a while.

However I will state that it seemed to handle Fade In correctly and in a reasonable amount of time.
But I also had it crashing on me on another video when doing a Fade In. So perhaps it has something to do with when a video gets spliced.

Essentially I was using the same 3hr clip and was turning it into two parts. I would find the split point (roughly 1hr 30min into it) and splice it to only keep one side. 
Part 1 would allow a Fade In just fine, but would crash when applying the Fade Out.
Part 2 weirdly was crashing trying to apply either a Fade In or a Fade Out.

**Comment by DylanC** [comment]
@Xionbarzhad - I tried to reproduce this using your steps but it did not happen for me.
