### ISSUE TITLE
Properties box does not ope

### ISSUE THREAD

**Issue by charlieo23** [OpenShot/openshot-qt#2323]
I put an audio clip on a track, right clicked and chose Properties, and no box opened.  The same happened with a still image.

Without the properties box this program is less than useless.

How do I get the Properties box open when right clicking and choosing Properties does not work?

**Comment by charlieo23** [comment]
Never mind - I was used to the Linux version, and the Windows version has apparently removed the properties popup. It appears the current menu choices are more limited.

**Comment by peanutbutterandcrackers** [comment]
@charlieo23 - This is strange. Could you please give us some screenshots? And some more details? Which OpenShot version are you using? Nothing has been removed from any of the versions. Perhaps you might want to try the basic `View` > `Views` > `Advanced View` as a way to get the properties bar back.

Hope that helps.

**Comment by charlieo23** [comment]
Thank you for your response.

>> as a way to get the properties bar back.

Not the properties bar; the properties popup window. On my Linux machine
you right click on an element (video, pic, sound clip) and choose
properties and up comes a box to set them. In this version choosing
Properties now opens a side panel - that does not have all of the
properties in the old popup box. So the behavior of the windows version,
which I downloaded about a week ago, does not match what is in your online
documentation.

The properties box let you set audio/video fade in/out in exact seconds.
The popup menu now gives fade as just slow or fast.

I already tried toggling back and forth between the views. The right menu
effect is the same.

I am now wrestling with a different issue, which is that output file sizes
are bloated compared to the Linux version when I choose the same specs.

**Comment by peanutbutterandcrackers** [comment]
@charlieo23 - Yes, I meant properties pop-up. Sorry, my mistake. "bar", huh.
It is also true that OpenShot works better on GNU/Linux Machines than on Windows ones. So that might be causing these issues.

I wonder if you should try deleting the `.openshot_qt` folder in your home folder and then try toggling the 'Simple' and 'Advanced' views to see how they work.

If even that doesn't work, you might want to [switch to the latest daily builds](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914).

**Comment by pix9** [comment]
I had seen similar behavior after recent update (GNU Linux Manjaro ), but thankfully it worked after  trying 
View > Views > Advanced View

As suggested in one of the above posts by  @peanutbutterandcrackers 
thanks.
