### ISSUE TITLE
Unable to change Title font and size

### ISSUE THREAD

**Issue by trt1** [OpenShot/openshot-qt#2324]
**Describe the bug**
Titles : unable to change font and size

**System Details (please complete the following information):**
 - Operating System / Distro: Windows 7
 - OpenShot Version2.4.3

**To Reproduce**
1. Go to Menu Bar
2. Click on 'Title'
3. Scroll down to 'Title'
4. Choose 'Camera Border' ou 'Standard 2' title style
5. Click on 'Change Font' (in right panel)
6. Try to change font : unable to change the standard 'Ubuntu' font and size 11.

**Expected behavior**
The desired font and most important its size to be taken in account and saved.

**Screenshots**
none

**Logs**
none

**Additional context**
none

**Comment by trt1** [comment]
Hi,
thanks for your reply and suggestion. No, I hadn't tried it, as these properties are basic and supposed not to require Inkscape. Moreover, as I'm already a beginner on OpenShot, I fear to learn one more software.

Best regards

**Comment by PASTJL** [comment]
Hi,
Have you installed Inskape? It is mandatory to use the basics functions of Title. You must configure Openshot with the path of Inkscape ( and the same with Blender / animated titles)

**Comment by green-anger** [comment]
> Have you installed Inskape? It is mandatory to use the basics functions of Title. You must configure Openshot with the path of Inkscape ( and the same with Blender / animated titles)

I believe this is not entirely true. For titles there are SVG files to use in OpenShot. To modify them you do need some vector editor but not necessarily Inkscape. You need Inkscape only if you want to edit the title from OpenShot ("Use Advanced Editor" button in Edit Title window which is currently broken #2273). And I agree with @trt1, modifying titles is more of an advanced technique for new users, they don't have to learn it to happily use OpenShot.

Also this issue seems to be a duplicate (#2280, #2069).

**Comment by PASTJL** [comment]
Yes, my bad. I have the same issue as @trt1  as pointed by @green-anger with the basic feature of Openshot of Title. I use last Appimage of Openshot => November 3th. So the workaround is the installation of Inkscape and configure the path in preferences/general.

**Comment by peanutbutterandcrackers** [comment]
@DylanC - Any ideas, Cap'ain?

**Comment by PASTJL** [comment]
I confirm that Openshot does not handle correctly the svg files. The workaround is to export the svg file to a png file with Inkscape (Advanced Editor) in a visible directory for Openshot.

**Comment by jdknox** [comment]
Even editing the file in Inkscape doesn't help in my case.  Inkscape shows the correct font, but when I load the title in OpenShot the font reverts to a standard serif font.  It almost seems like builtin OS fonts work, but any I have installed don't.

Another workaround is to convert the font to paths in Inkscape, but that makes it a pain to edit...

**Comment by ferdnyc** [comment]
@jdknox I imagine that's exactly the case, when running OpenShot from the AppImage. As I just noted in #2647, I don't expect this will have a solution for the AppImage builds, other than using a distro package. On the plus side, you'll also get the far superior native font dialog, instead of Qt's gimpy one.

**Comment by NoBodyButMe** [comment]
Any solution for the font problem?

**Comment by YoussefAMansour** [comment]
> **Describe the bug**
> Titles : unable to change font and size
> 
> **System Details (please complete the following information):**
> 
> * Operating System / Distro: Windows 7
> * OpenShot Version2.4.3
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to Menu Bar
> 2. Click on 'Title'
> 3. Scroll down to 'Title'
> 4. Choose 'Camera Border' ou 'Standard 2' title style
> 5. Click on 'Change Font' (in right panel)
> 6. Try to change font : unable to change the standard 'Ubuntu' font and size 11.
> 
> **Expected behavior**
> The desired font and most important its size to be taken in account and saved.
> 
> **Screenshots**
> none
> 
> **Logs**
> none
> 
> **Additional context**
> none

i still have the same problem with the font size in titles

**Comment by masm32-source** [comment]
I discovered that if I install a new font for single user, the titel font will not change. If I install the font for all users, than it is possible to change the titel font. But size doesn't work. Using inkscape doesn't work, because it uses the standard font after importing to OpenShot.

**Comment by alex-c3** [comment]
Same here, version 2.6.1
Most fonts I have are not recognized (size works!)
It looks like only the basic ones are, plus a few others (Algerian and Vivaldi work, e.g., but Gotham, Game of Thrones or Yu Gothic dont).

**Comment by itaybia** [comment]
i'm on 2.6.1, i don't have inkscape installed as i'm not trying to use advanced features.
changing anything doesn't seem to work. even worse, changing anything makes the font very small, with no way to go back (undo doesn't help).
workaround i'm using so far for sizing is to change the scale of the title block. gotta say, this is far from an advanced feature, and should be quite basic without an installation of anything external to the program.
