### ISSUE TITLE
No 'sharpen' feature in existence - would be extremely helpful.

### ISSUE THREAD

**Issue by nk8020** [OpenShot/openshot-qt#2325]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nk8020** [comment]
I shoot wildlife clips, and often enough want to make a little sharper for the pleasure of the viewer. As there is no way to do so now, I resort to playing with the Brightness/contrast and color saturation to try and compensate, and they do to some degree, but not a whole lot. Such a feature would be more than nice to have, especially considering the quality of screens on the market.

**Comment by hq9000** [comment]
so still no plans to add a sharpen filter? Would be incredibly useful.
