### ISSUE TITLE
Export freezes at 0.0%

### ISSUE THREAD

**Issue by mpeeters2** [OpenShot/openshot-qt#2327]
I have a 21 second video that I would like to export, but whatever I try it freezes at 0.0%...

**System Details (please complete the following information):**
 - Operating System : Windows 10
 - OpenShot Version  2.4.3

**Comment by mpeeters2** [comment]
I replaced the 2.4.3 version by the older 2.4.1 version and now it works!
Am I missing out on important things when I keep working with the 2.4.1. version?

**Comment by DylanC** [comment]
@mpeeters2 - Not really. v2.4.1 was a good release.
