### ISSUE TITLE
openshot 2.4.1 effect removal

### ISSUE THREAD

**Issue by carnussien** [OpenShot/openshot-qt#2328]
hello,
I can' t find how to remove an effect i have applied to a clip.
Can anybody help
Thanks

**System Details**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**Screenshots**

**Comment by N3WWN** [comment]
You can right-click on the effect icon that appears in the upper-left of the clip and select `Remove effect`.

**Comment by carnussien** [comment]
OK Merci!!!
