### ISSUE TITLE
Preview Issues - No audio and faster than real-time when playing

### ISSUE THREAD

**Issue by anditbeginswith** [OpenShot/openshot-qt#2331]
There is no audio when playing the the preview mode. When I export the project I can hear the audio on the created file, just not in the preview.
Also while it plays it plays faster than just normal/real time speed. I can't find a way to adjust the speed.

Windows 10
OpenShot 2.4.3

I expect to hear the audio when I play the project in preview mode.

There have been others posting about the same problem but nobody has helped them. 
I hope that you can find a solution to help everyone.

**Comment by speedytechdev** [comment]
Hi @anditbeginswith I will help were I can and hopefully fix the issue. I need a few things from you please.

- When did this start?
- Is it specific files
-Does this happen with any other projects
-Did you check the volume on the audio clips
- Do you have crash logs and screenshots of your timeline.

**Comment by anditbeginswith** [comment]
Thanks for taking the time, I did an OS wipe and reinstall after I had this
issue, reinstalled open shot and it was fine.
Thanks again

**Comment by speedytechdev** [comment]
@anditbeginswith Great to hear.

**Comment by speedytechdev** [comment]
@DylanC ^^^
