### ISSUE TITLE
How do I delete a project entirely?

### ISSUE THREAD

**Issue by Geshelin** [OpenShot/openshot-qt#2332]
**My Question:**

**System Details**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**Screenshots**

**Comment by DylanC** [comment]
@Geshelin - Close Openshot, find the project file (.osp is the file extension) and delete it just like any other file on your computer.

**Comment by DylanC** [comment]
Closing this as answered. Reopen if you still are not sure how to do this. Thanks.
