### ISSUE TITLE
How do I close the Effects etc. functions and return to the initial screen?

### ISSUE THREAD

**Issue by Geshelin** [OpenShot/openshot-qt#2333]
**My Question:**

**System Details**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**Screenshots**

**Comment by Geshelin** [comment]
I spent a good half-hour on the long tutorial, watching several sections several times. Nowhere did I hear how to delete a project that I didn't want or now to return to the initial screen where I could drag-and-drop my files.  I deliberately did not save the "project" that was actually experimentation to learn the program, but now it is there as a file.

**Comment by DylanC** [comment]
@Geshelin - Do you have a screenshot to help us understand the question?

**Comment by Geshelin** [comment]
I can't send a screen shot because I eventually uninstalled the program.
However, you were so prompt in replying to my questions that I will
reinstall the program when I get home from work. If the same problem recurs
I will send you that screenshot. Thank you.

Hanna Geshelin
Sigaliot 56/4
Box 2511
Ma'alot-Tarshiha, Israel
2150153
055-951-2994
USA Tel: 208-240-6807
e-mail: hbgesh@gmail.com
