### ISSUE TITLE
Openshot crashes on opening

### ISSUE THREAD

**Issue by rsarrais** [OpenShot/openshot-qt#2335]
**Describe the bug**
I always had that problem with OpenShot. My first install was the 2.4.1 version, and I could only open it on "compatibility mode" for Windows 7. But since I installed the new 2.4.3 version, which never worked, even on "combatibility mode", even on 32 bits, and returned to the 2.41. version, I CANNOT OPEN IT anymore, even on "compatibilty mode". It simply crahses on start.

The only way I can still use it is reinstalling the 2.4.1 version .exe and launching it right after install. Sometimes I still need to install it twice before it works on launch. Very annoying.

**System Details (please complete the following information):**
 - Operating System / Distro: Windows 7
 - OpenShot Version 2.4.1 and then 2.4.3, going back to 2.4.1 

**To Reproduce**
1. Install 2.4.1 or 2.4.3 versions.
2. Click on the shortcut after install.
3. Crashes on start every time.

**Comment by rsarrais** [comment]
Well I found a portable version of the 2.4.3, it works perfectly now, MUCH faster. I would recommend it to anyone having the same kind of troubles with crashes:

https://portableapps.com/node/59167

Thank you for this wonderful opensource free software!

**Comment by peanutbutterandcrackers** [comment]
I didn't know about the portable version. Thank you for the information.

I'll be closing this since it seems the issue has been resolved for you.

**Comment by rsarrais** [comment]
It's been a whole new experience using OpenShot without lags and crashes, wonderful software indeed. Thank you.
