### ISSUE TITLE
Shift+Remove Clips Not Working

### ISSUE THREAD

**Issue by Freedom2021** [OpenShot/openshot-qt#2336]
**My Question:**
Shift+Remove Clip feature seems not be working for me.  I've tried different combinations as follows:
1. Hold down "Shift", right click on clip, select "Remove Clip".  Results in clip being removed but gap left behind by clip removal rather than gap being removed (aka all following clips are shifted to fill in gap).
2. Hold down "Shift", right click on clip, release "Shift", select "Remove Clip".  Same results as in 1.
3. Right click on clip, Hold down "Shift", and  select "Remove Clip".  Same results as in 1.

I currently only have clips on one track.  As an example, I have 3 clips, and want to delete the middle clip, then have the last clip shifted flushed to the first clip.

Not sure if I am missing something or is there a way around this other than manually arranging the clips one by one.

Also, I wonder if a keyboard shortcut like Shift+Delete and/or Shift+Delete can be or has been implemented for this features.

Thank you.

**System Details**
 - Operating System / Distro: Win 7 Pro
 - OpenShot Version 2.4.3

**Comment by speedytechdev** [comment]
Hi @Freedom2021 I have not heard of this feature was it in a previous version and could you make a feature request in a different post, please.
