### ISSUE TITLE
Export on hardware support branch not working

### ISSUE THREAD

**Issue by DylanC** [OpenShot/openshot-qt#2338]
Mentioned here as a PR for some reason:
#2337

Original message:
le logiciel me marque quil ne repond pas quand je fait exporter la video

EN:
the software tells me that it does not respond when I export the video

**Comment by peanutbutterandcrackers** [comment]
I wonder if it is that ready already. Work is currently being done. Perhaps we should close this for now? Cap'ain? @DylanC
