### ISSUE TITLE
Are OSP files one-time only use?

### ISSUE THREAD

**Issue by TOSoulard** [OpenShot/openshot-qt#2339]
I'm just learning how to use this and it seems that you can't save the file, open it back up and continue working. Is that correct or am I doing something wrong?

Thanks

**System Details**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**Screenshots**

**Comment by DylanC** [comment]
@TOSoulard - They are not a one time use, you can open your project file later when you need to continue the project.

**Comment by peanutbutterandcrackers** [comment]
And you might want to take a look at [this guide](https://gist.github.com/peanutbutterandcrackers/f0f666243133e0ed25abbc12a4ba23d7) as well. :+1:
