### ISSUE TITLE
Openshot 2.0.7 fails to open on Ubuntu 16.04

### ISSUE THREAD

**Issue by james3mc** [OpenShot/openshot-qt#234]
I'm running Ubuntu 16.04. I used:
```
sudo add-apt-repository ppa:openshot.developers/ppa
sudo apt-get update
sudo apt-get install openshot-qt
```
to install Openshot 2.0.7.

However when I try to open it, the icon appears in the unity menu for a few seconds, blinking, and then disappears again with no Openshot starting.

**Comment by Kagetsuki** [comment]
Can you copy and paste the output of running "openshot-qt" in a terminal? It should dump a lot of run-time information when it's starting up.

**Comment by dshimer** [comment]
I experienced the exact same thing when running the AppImage and captured the terminal information.  I'll attach that but please tell me if it is not appropriate to place that information here and I will start another post?

[OpenShot-2.0.7.AppImage_crash_terminal.txt](https://github.com/OpenShot/openshot-qt/files/364215/OpenShot-2.0.7.AppImage_crash_terminal.txt)

**Comment by Kagetsuki** [comment]
@dshimer How did you install Qt? When was the last time you updated it?

**Comment by dshimer** [comment]
@Kagetsuki  No idea.  This is Ubuntu 16.04 which has been updated every 6 months since 12.04. I have been running OpenShot 1.x forever. Tried the 2.x ppa and couldn't get it to work properly (froze importing a video) so thought I'd try the AppImage.  I must have misunderstood and thought that the AppImage was self contained and would have everything it needed. I'm willing to try or report anything necessary but don't have a specific memory of installing Qt.

**Comment by Kagetsuki** [comment]
@dshimer No idea about the AppImage but it's using system libs. Get rid of the app image and see if you can give the output of the normal package. I'm on 16.04 as well btw.

**Comment by dshimer** [comment]
@Kagetsuki For me the version from the PPA opens (though freezes when importing video).  I was hoping that the AppImage output may help because the symptoms were the same as those listed by james3mc but I probably just clouded the issue.

**Comment by Kagetsuki** [comment]
@dshimer what's the format of the video? would you be able to upload this video somewhere for someone else to try?

**Comment by jonoomph** [comment]
The AppImage should work now, with our latest daily builds.  Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot's AppImage. If you still encounter errors with Ubuntu 16.04, please reopen this ticket. Thanks!
