### ISSUE TITLE
Gets stuck at opening screen on late 2013 Macbook pro with OSX Mojave 10.14.1 

### ISSUE THREAD

**Issue by Gibouille** [OpenShot/openshot-qt#2340]
**Describe the bug**
When I start the software it displays the box asking if I want participate in bug reporting but the software then doesn't answer, I need to force it to quit

**System Details (please complete the following information):**
MAc OSX Mojave, late 2013 MBP retina 16 Go ram i7 processor
**To Reproduce**
Install software, launch it

**Expected behavior**
Being able to click yes or no in the box that asks me wether or not I want to participate in monitoring (send errors and metrics)

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**

**Comment by speedytechdev** [comment]
Hi @Gibouille sorry for the late response. Could you send me some screenshots of the issue and the error logs, please.

**Comment by Gibouille** [comment]
Here is a screenshot.
[http://www.new-era-way.com/pics/openshot.png(url)

I'll send a log when I figure out where they are.

**Comment by speedytechdev** [comment]
Cool I will take a look tomorrow after I sleep. Here is how to get the logs https://github.com/OpenShot/openshot-qt/blob/develop/CONTRIBUTING.md

**Comment by Gibouille** [comment]
I can't enable "debug mode" because I can't acces sopenshot menu. Whe openshot launches it gets stuck immediately and I have fo fore it to quit from the system.

**Comment by speedytechdev** [comment]
@Gibouille I can't find it sorry they might have moved it. I would love to help you but I need to sleep. @DylanC Could you help.
