### ISSUE TITLE
can't import image sequence starting with 0326.png

### ISSUE THREAD

**Issue by stjema** [OpenShot/openshot-qt#2341]
win10, made in blender. recent version, no idea which one.  try it with the file 0326 (top image)

![0328](https://user-images.githubusercontent.com/13036947/48258426-5c5f5d80-e415-11e8-8297-7f52897e48b9.png)
![0329](https://user-images.githubusercontent.com/13036947/48258429-5c5f5d80-e415-11e8-8383-60f89cf14907.png)
![0330](https://user-images.githubusercontent.com/13036947/48258431-5c5f5d80-e415-11e8-83e0-bf695b610152.png)
![0331](https://user-images.githubusercontent.com/13036947/48258433-5cf7f400-e415-11e8-9609-8248a20cc7f4.png)
![0332](https://user-images.githubusercontent.com/13036947/48258435-5cf7f400-e415-11e8-9b72-93593c78e213.png)
![0333](https://user-images.githubusercontent.com/13036947/48258436-5cf7f400-e415-11e8-8e31-a95067c8705a.png)
![0334](https://user-images.githubusercontent.com/13036947/48258438-5cf7f400-e415-11e8-88e2-40d650aeb732.png)
![0335](https://user-images.githubusercontent.com/13036947/48258439-5cf7f400-e415-11e8-997a-db4f8ff73268.png)
![0336](https://user-images.githubusercontent.com/13036947/48258441-5d908a80-e415-11e8-8a2b-117ee20fba4b.png)
![0337](https://user-images.githubusercontent.com/13036947/48258443-5d908a80-e415-11e8-82f8-f1c5add47ffd.png)
![0338](https://user-images.githubusercontent.com/13036947/48258444-5d908a80-e415-11e8-8cb9-9d9f0eb752c1.png)
![0339](https://user-images.githubusercontent.com/13036947/48258446-5d908a80-e415-11e8-9f44-e03b349459aa.png)
![0340](https://user-images.githubusercontent.com/13036947/48258448-5d908a80-e415-11e8-8384-485cf459c41f.png)
![0341](https://user-images.githubusercontent.com/13036947/48258449-5e292100-e415-11e8-8f05-afe32ed0c54a.png)
![0342](https://user-images.githubusercontent.com/13036947/48258451-5e292100-e415-11e8-833f-7b393cb5d803.png)
![0343](https://user-images.githubusercontent.com/13036947/48258453-5e292100-e415-11e8-8aa2-5e01ede1a4e9.png)
![0326](https://user-images.githubusercontent.com/13036947/48258456-5ec1b780-e415-11e8-8d5b-803b7fdae301.png)
![0327](https://user-images.githubusercontent.com/13036947/48258458-5ec1b780-e415-11e8-8a29-8554cc1edbb7.png)

**Comment by peanutbutterandcrackers** [comment]
Perhaps you could rename the file to be 0001.png 0002.png or something and maybe that'll help?
