### ISSUE TITLE
How can I resize the parent video to the crop size?

### ISSUE THREAD

**Issue by mpax4059** [OpenShot/openshot-qt#2348]
Hello! I was wondering if there is a way to resize the parent video size. I imported a video, but I only wanted a certain area of the video so I cropped the video to the area that I am wanting. My only problem now is that the video has all of the blacked out arean when I export it, but I only want the area that I cropped to be showing. Is there a way to resize the parent video to the size of the area that I cropped?

**Comment by PASTJL** [comment]
You can scale X and scale Y according to the proportion of the image to zoom as better you can. You have to modify it in the properties of the clip in the timeline
