### ISSUE TITLE
Openshot 2.4.3 under Ubuntu 18.04 crashes during export too

### ISSUE THREAD

**Issue by MadEdward** [OpenShot/openshot-qt#2349]
**Describe the bug**

**System Details (please complete the following information):**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**

**Comment by MadEdward** [comment]
Problem seems to be the way Openshot uses the RAM. I read a comment on this issue today, and created a 6 GigaByte swap file next to my 3.8 GigaByte RAM. I tried with both swappiness =40 and swapiness=80. And with Quality set at High, Middle and Low. With High my system crashed and got stuck. I needed to do a hard manual reboot to get the system up again. With Low Openshot-qt closed or crashed, but the system kept running. I received the message that ¨Openshot-qt closed unexpectedly, but due to memory shortage no analysis could be made and no error report was sent¨.
It looks like the current Openshot version still keeps exhausting memory and does not release any memory during the process.

**Comment by DrSensor** [comment]
Same problem here. My machine is intel core i5 with gtx 940mx and 7.7 GB RAM.
Whatever I do some editing or exporting, it keeps my max memory. Seems like everytime openshot play some frame, it will cache it but not free the memory at a specific interval 🤔

**Comment by peanutbutterandcrackers** [comment]
Strangely enough, this does not happen to me on my Linux Mint 19 machine with 2 GB RAM and Intel Celeron N3050 @ 2x 2.16GHz

Perhaps you might want to attach the logs, and add some more information regarding the file itself?

However, I think I remember one other problem with Ubuntu 18.04 series somewhere in the issues. I wonder if these issues are related.

**Comment by stanwmusic** [comment]
It is maxing out my 7.7 GB of RAM then the  swap file fills and  then last time I didn't stop it in time and it locked down  I had to hold the power button until it shut off.It made it to 27.3 % exported with 50 images and    a 3.4 minute MP3.  I tried  changing to medium quality  and then low, all  to no avail and it is useless and hopeless.  and I have been trying to get this one video for over 7 hours now  for a   friend in Nashville I'm running  OpenShot 2.4.4 on Ubuntu 18.04.3  and all 4 cores  run at 100% even if I change priority to very low. On this same  computer with Ubuntu 14.04 I had no problems with the older version of Openshot.

**Comment by ferdnyc** [comment]
@stanwmusic 

Hmm, if you're running OpenShot 2.4.4 release, that version had some memory-management issues that were only discovered and cleared up shortly _after_ the release, so one thing you might try is downloading a newer Daily Build AppImage from https://openshot.org/download/ and running that — you should see less memory growth, and on complex projects with a large number of Clips (even still images) on the timeline, the difference can be huge.

Definitely don't lower OpenShot's priority, the only effect that has is to let the rest of the OS interrupt it more, which means its operations will take even longer. It'll also make it more likely that the kernel will swap OpenShot out of memory, which will only make the disk thrashing even worse.

Aside from the upgrade from 2.4.4 to a development build, the only other thing I can think to suggest is to check the OpenShot Preferences for a few things:
1. Make sure Debug Mode isn't enabled in the Debug tab, as that causes _huge_ storms of log messages to be generated and written to the log files
1. Crank _down_ the History Limit in the Autosave tab, to reduce OpenShot's memory use in general. (And in fact, separate from / in addition to that change, it's not a bad idea to do an Edit > Clear History right before starting an Export process.)
1. Also, check the Cache tab, make sure you're using the Disk cache mode, and that you have a reasonable amount of disk space allocated for the cache

**Comment by stanwmusic** [comment]
> @stanwmusic
> 
> Hmm, if you're running OpenShot 2.4.4 release, that version had some memory-management issues that were only discovered and cleared up shortly _after_ the release, so one thing you might try is downloading a newer Daily Build AppImage from https://openshot.org/download/ and running that — you should see less memory growth, and on complex projects with a large number of Clips (even still images) on the timeline, the difference can be huge.
> 
> Definitely don't lower OpenShot's priority, the only effect that has is to let the rest of the OS interrupt it more, which means its operations will take even longer. It'll also make it more likely that the kernel will swap OpenShot out of memory, which will only make the disk thrashing even worse.
> 
> Aside from the upgrade from 2.4.4 to a development build, the only other thing I can think to suggest is to check the OpenShot Preferences for a few things:
> 
> 1. Make sure Debug Mode isn't enabled in the Debug tab, as that causes _huge_ storms of log messages to be generated and written to the log files
> 2. Crank _down_ the History Limit in the Autosave tab, to reduce OpenShot's memory use in general. (And in fact, separate from / in addition to that change, it's not a bad idea to do an Edit > Clear History right before starting an Export process.)
> 3. Also, check the Cache tab, make sure you're using the Disk cache mode, and that you have a reasonable amount of disk space allocated for the cache

Thanks for the tips I will try them all.
 I only lowered it's priority once to see it it  would  use less  resources , I raised it's priority  first , I was just  desperate and  very very irritated lol . I am still working on the  video  10+ hours now. I should have never  promised to get it done for them the old version Openshot on 14.04  was great.   I will  try to get a daily  build. There is for sure a  memory leak
