### ISSUE TITLE
incomplete edit toolbar

### ISSUE THREAD

**Issue by YKastell** [OpenShot/openshot-qt#235]
Trying to use Openshot 2.0.7 but there is no  scissors in the edit Toolbar other tools does not work

![screenshot at 2016-07-03 20 29 12](https://cloud.githubusercontent.com/assets/20269474/16546992/e55e1044-415c-11e6-9584-5167ee63511b.png)

Ubuntu 16.04 OpenShot 2.0.7

**Comment by Sahbum** [comment]
I just installed OpenShot 2.0.7 from the PPA and am experiencing the same thing - I cannot find nor use any of the editing tools.

**Comment by CallumGozzers** [comment]
Same for me 👍

**Comment by DylanC** [comment]
@YKastell - Does this issue still occur for you?

**Comment by DylanC** [comment]
Closing since this has no more activity and the version tested is very old.
