### ISSUE TITLE
Rendering failure

### ISSUE THREAD

**Issue by AndreaHewitt** [OpenShot/openshot-qt#2350]
**My Question:**

Every time I try to render a video it gets to 70-85% and then this error message appears: "Sorry, there was an error exporting your video: Error while writing raw video frame." 

How can I resolve this?

**System Details**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**Screenshots**

**Comment by speedytechdev** [comment]
Hi @AndreaHewitt I would recommend that you use 2.4.3. This has fixed a lot of bugs.
