### ISSUE TITLE
Every time I import videos it crashes

### ISSUE THREAD

**Issue by Joetheperson** [OpenShot/openshot-qt#2351]
I am on a mac and every time i try to import a video OpenShot crashes

**Comment by speedytechdev** [comment]
Hi@Joetheperson I have some questions I need you to answer so I can help you.

1. What version of Openshot are you on?
2. Does this happen with specific files?
3. Has this happened before?

**Comment by woodytopsail** [comment]
This exact thing is happening to me, also.
1) v2.4.3
2 It happens with cell phone video, .mp4 or after I convert the same file to .mov
3) So far, it ALWAYS happens.
4) I can bring in still photos, but that defeats the purpose of the video editor.
I hope you have some ideas. Thanks.

**Comment by speedytechdev** [comment]
That is odd that it does not like mp4 since I have used mp4 files with my projects. The thing is they are not from my phone. Could you send me more information about this, please. So the logs and pictures and etc.

**Comment by DylanC** [comment]
Dup of #2114

**Comment by moribo21** [comment]
I'm on macOS High Sierra 10.13.6 and I'm using version 2.4.3 OpenShot. Could not import the .mov or .mp4 files. The software crash.

**Comment by moribo21** [comment]
New test, new crash : attached the log file. 
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2888369/openshot-qt.log)

**Comment by moribo21** [comment]
Other observation : The files in .openshot-qt (assets, backspace, blender, preview-cache, profile, tests, thumbnail, title, transitions) are empty.
