### ISSUE TITLE
Soft audio

### ISSUE THREAD

**Issue by bmfazio** [OpenShot/openshot-qt#2354]
**Describe the bug**
Using fast fade in and fade out fades the entire clip.

**System Details:**
 - Operating System: Windows 10
 - OpenShot Version (latest)

**To Reproduce**
1. Add audio clip
2. Apply fast fade in/fade out
3. Watch preview and listen sound coming out at proper level, with a fast fade in and fade out
4. Export
5. Play video, sound is at 1% of the volume it should be through the entire clip

**Expected behavior**
Step 3

**Comment by speedytechdev** [comment]
Hi @bmfazio I can not find the issue could you please give some evidence.
