### ISSUE TITLE
How do I move video on the timeline?

### ISSUE THREAD

**Issue by ImperialJohn** [OpenShot/openshot-qt#2356]
**Is there a move tool?:**

Can anyone tell me if there is a little hand tool that will allow me to move and reposition video clips on the timeline? I cannot seem to find one only a magnet and a pair of scissors which is not what I want?

**System Details**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**Screenshots**

**Comment by speedytechdev** [comment]
Hi @ImperialJohn if you hover over a clip in the timeline you should get four arrows that point to N,E,S and W. That is the move tool. Just hold down the left mouse button and drag the clip to were you would like it in the timeline.

**Comment by speedytechdev** [comment]
@ImperialJohn Could you let me know if that fixed the issue so we can close this post. Thanks

**Comment by aliciapaz** [comment]
Hello, I have the same problem in Mac. Or is that I'm doing something wrong? 

MacBook Pro (13-inch, M1, 2020)
Operating System: Monterey 12.4
OpenShot version: 2.6.1

https://user-images.githubusercontent.com/67963195/178385873-cd078d24-cea3-4ee0-ae22-cb817009244d.mov
