### ISSUE TITLE
How to overlay image?

### ISSUE THREAD

**Issue by ImperialJohn** [OpenShot/openshot-qt#2357]
**How do I overlay an image on part of the video clip?**

Hi. Does anyone know how I can overlay an image file over a small portion of the video clip in the middle and a bit to the right? Is there a way to do it in this program and position and resize the image so that it blocks out the video from the part of the screen it is positioned in? Or do I need to buy more advanced paid for video editor for this?

**System Details**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**Screenshots**

**Comment by speedytechdev** [comment]
Hi @ImperialJohn do you mean something like this. 
![image](https://user-images.githubusercontent.com/40452959/48522555-fcb5f600-e8dd-11e8-87c6-3bae4ed74242.png)

**Comment by speedytechdev** [comment]
@ImperialJohn Could you let me know if that fixed the issue so we can close this post. Thanks
