### ISSUE TITLE
Key shortcuts for the time slider

### ISSUE THREAD

**Issue by martinlabarthe** [OpenShot/openshot-qt#2358]
I have very low vision so it takes me a while to find with the mouse some sliders or buttons, so  I use a lot the keyboard and shortcuts and use mouse only when I can not use keys, as Java developer o game player found out that can work much faster that way even when I had good vision that using the mouse only .

In particular I would love five shortcuts:
1. move time slider to left/right
2. zoom slider in/out
3. center the time slider with the preview player cursor. Sometimes it goes out of sight and i do not know if it is on the left side or right side.

Thanks a lot for the great job you have done.

Martin

**Comment by speedytechdev** [comment]
Hi @martinlabarthe Some of these shortcuts are already in Openshot. If you press ctrl shift p and go to the keyboard option you can see all the bindings in there. Number 3 I don't believe is added but we can. Are there any other shortcuts you would like us to add?

**Comment by martinlabarthe** [comment]
Hi,

Thanks for the incredible fast response!

The tip solved the problem for me and found there other critical keys.

So now i could only think of just a key for centering the slider on the cursor.


Thanks a lot,
Martin



About what other shortcuts, let me explain:



Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

________________________________
De: speedytechdev <notifications@github.com>
Enviado: Thursday, November 15, 2018 10:09:17 PM
Para: OpenShot/openshot-qt
Cc: martinlabarthe; Mention
Asunto: Re: [OpenShot/openshot-qt] Key shortcuts for the time slider (#2358)


Hi @martinlabarthe<https://github.com/martinlabarthe> Some of these shortcuts are already in Openshot. If you press ctrl shift p and go to the keyboard option you can see all the bindings in there. Number 3 I don't believe is added but we can. Are there any other shortcuts you would like us to add?

**Comment by speedytechdev** [comment]
Hi @martinlabarthe that is great to hear I will get your feature request put in.

**Comment by speedytechdev** [comment]
@DylanC enhancement

**Comment by martinlabarthe** [comment]
Hi,

I was thinking over night.


  1.  The center cursor key would be nice I think if centered a bit to the left, so you have some visibility to the left side but more space to the right side so you can play the video for a bit longer time.


  1.  Another desirable key would be a key like the actual “dellete”, that removes the selected clip BUT would be nice if also at the same time it moves the right side of the clip to the left so it fils “the gap”,actually to do that I “Paint” with mouse the right side and drag it to the left. Maybe you have something already  I dont know.



When cutting hundreds of small section that one would be helpful too.


Thanks a lot,
Regards,
Martin







Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

________________________________
De: speedytechdev <notifications@github.com>
Enviado: Friday, November 16, 2018 5:49:32 AM
Para: OpenShot/openshot-qt
Cc: martinlabarthe; Mention
Asunto: Re: [OpenShot/openshot-qt] Key shortcuts for the time slider (#2358)


Hi @martinlabarthe<https://github.com/martinlabarthe> that is great to hear I will get your feature request put in.

**Comment by schauveau** [comment]
I am probably missing something but do not see any shortcut to move the time slider to the left/right.  
This is quite annoying when editing a long video. At maximal zoom, the horizontal slider becomes minuscule and very imprecise. 

I am thinking that a 'goto time' shortcut or menu would be nice. That could bring a dialog where the requested time could be entered using different formats: a single number in seconds, as minute:second, as hours:minutes:seconds  ... 
That feature could also be used to jump to markers if they were given a name.
