### ISSUE TITLE
a big problem

### ISSUE THREAD

**Issue by David465646** [OpenShot/openshot-qt#2359]
its asking me for a deleted file
so, i opend up openshot, and first thing you know, asking for a MP4, it was used in another video, but now is asking agin for it, i cannot get rid of it, i tried even reinstalling openshot, an nothing worked

 - windows 8.1 pro
 - OpenShot Version 2.4.3

i dont even know how to reprotuce the error, it just happend

Expected behavior
i expected to happend nothing, just open up the software

Screenshots
how to screenshot?

**Comment by speedytechdev** [comment]
HI @David465646 did you try and make a new project and import all your files to the new project.

**Comment by speedytechdev** [comment]
@DylanC I am positive that this is a bug and is similar to another issue I just can't remember which one.

**Comment by peanutbutterandcrackers** [comment]
This issue has been resolved in the daily builds. If it is really urgent for you, please [try out the daily builds](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914). Hope that helps!

**Comment by DylanC** [comment]
@speedytechdev - We have this solved already in the latest code. Thanks for the quick replies on issues.

**Comment by speedytechdev** [comment]
@DylanC Sorry about that and no problem
