### ISSUE TITLE
Can't add brightness or saturation

### ISSUE THREAD

**Issue by alexanderghenry** [OpenShot/openshot-qt#236]
I have Win10, OS 2.0.7. New install, new project.

I successfully spliced three movies together with 2-second fades in between. The first one I rotated 90-left.

I want to adjust the brightness and saturation, I have dark colors blending together that I want to become visible again. I have all views open, I drag the effect onto the clip, and nothing happens. The icon does change from circle-not to arrow, but no new attributes appear in properties.

**Comment by DylanC** [comment]
@alexanderghenry - Do you have this issue on later versions than 2.0.7?

**Comment by DylanC** [comment]
Closing since this is a much older version of OpenShot and no more activity here.
