### ISSUE TITLE
video are lagging

### ISSUE THREAD

**Issue by IIlol** [OpenShot/openshot-qt#2360]
**Describe the bug**

**System Details (please complete the following information):**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**

**Comment by speedytechdev** [comment]
Hi @IIlol you need to fill out that information or we don't know how to help you.
