### ISSUE TITLE
Redesign Timeline

### ISSUE THREAD

**Issue by MisterTeeXD** [OpenShot/openshot-qt#2363]
**Is your feature request related to a problem? Please describe.**
I think the timeline needs a redesign

**Describe the solution you'd like**
None

**Describe alternatives you've considered**
None

**Additional context**
A nice redesign of the Openshot Timeline would be a amazing change to the timeline and the feel of it, i feel like the timeline needs a complete overhaul. Who agrees?

**Comment by MisterTeeXD** [comment]
I also made a little Mockup of what i though it might look like (Sorry for the horrible Mockup) : 
[Timeline beta.zip](https://github.com/OpenShot/openshot-qt/files/2590320/Timeline.beta.zip)

**Comment by speedytechdev** [comment]
@MisterTeeXD I was thinking of updating it but was not sure what to change. If you have any ideas that would be great.

**Comment by MisterTeeXD** [comment]
I made a mockup image of what i think it might look like

**Comment by speedytechdev** [comment]
Yay I saw that I need more detail (not to be rude). I need a design that looks modern but also easy to use.

**Comment by MisterTeeXD** [comment]
Thats all i could design

**Comment by speedytechdev** [comment]
All good I need to think of some ideas myself but thanks for the idea.

**Comment by MisterTeeXD** [comment]
You are welcome

**Comment by MisterTeeXD** [comment]
Oh so i was close to the actual design?

**Comment by DylanC** [comment]
@MisterTeeXD - A little bit. Its similar because it had flat colours and not the gradient style we have currently.

**Comment by MisterTeeXD** [comment]
Mmmm interesting

**Comment by ferdnyc** [comment]
There is no "actual design", as that was a work-in-progress that was abandoned.

(Also, images can be added directly to Issues, there's no reason to make people jump through hoops downloading ZIP files. Here's @MisterTeeXD 's mockup, as the entire contents of that ZIP is a single PNG:)

![image](https://user-images.githubusercontent.com/538020/48665311-14c27c80-ea7a-11e8-95e7-cca2cce9e266.png)

**Comment by MisterTeeXD** [comment]
So this issue is useless i suppose and i do understand that some features have to be declined due to other issues as well
