### ISSUE TITLE
wav form not displaying when razer scissor used lastest dev version

### ISSUE THREAD

**Issue by bobcrikey** [OpenShot/openshot-qt#2365]
Hello everyone, I just downloaded the latest dev version of openshot and discovered
if you tell openshot to display the wav form and then cut it in half , the left side of the wav form displays
and the right cut clip wont display anything ,
heres a clip to show what im talking about.
![openshot no wav picture](https://user-images.githubusercontent.com/40479177/48657731-953ca980-ea89-11e8-93d8-d6c51b200965.png)

Its quite possible i brought this up at least 6 months ago or more but it wasnt fixed or another
bug as surfaced after it got fixed.

cheers
    bob

**Comment by bobcrikey** [comment]
@DylanC , Thanks for letting me know mate, i didnt know someone else already picked up on that bug
 and reported it , 
cheers 
 bob

**Comment by peanutbutterandcrackers** [comment]
Closing this duplicate, then. Hopefully we'll be able to see this fixed, soon.
