### ISSUE TITLE
Where did my media files go

### ISSUE THREAD

**Issue by Redwolf2016** [OpenShot/openshot-qt#2366]
After accidentally clicking the x I can not bring the file selector back.

**My Question:**
While trying to move the media previewer ( I don't know what its called because I can't find it) I closed it out and there is no way, that I can tell, to open it back up. The program is unusable without having my files present and I would like to get a project finished today.

**System Details**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**Screenshots**
![capture](https://user-images.githubusercontent.com/45124954/48662285-a9f74e00-ea45-11e8-9b73-6b79abfb81fb.JPG)

**Comment by speedytechdev** [comment]
Hi @Redwolf2016 if you click the view tab and go into views and select simple view it should rest everything. 
![image](https://user-images.githubusercontent.com/40452959/48693711-3b7de000-ec3f-11e8-885d-134b5c852d74.png)

**Comment by peanutbutterandcrackers** [comment]
Closing this as answered.
