### ISSUE TITLE
Zooming in/out (Animation)

### ISSUE THREAD

**Issue by NatureIsGood** [OpenShot/openshot-qt#2369]
Objekts can be zoomed in/out within percentages of 50% 75% 100% and 150%
It wout be great to have also 0% so one can implode an object completely.

**Comment by NatureIsGood** [comment]
By the way: Beeing able to explode from 0% to 100% would be great as well

**Comment by peanutbutterandcrackers** [comment]
It is, indeed [possible](https://www.youtube.com/watch?v=nEyrC1v-M1s). However, you might need [this guide](https://gist.github.com/peanutbutterandcrackers/f0f666243133e0ed25abbc12a4ba23d7) to understand everything that is happening.

Closing this as answered. Please feel free to comment/re-open if you have further queries. Thank you.
