### ISSUE TITLE
Timeline and Animated Titles crash

### ISSUE THREAD

**Issue by Elrondo46** [OpenShot/openshot-qt#237]
When I want to navigate the timeline or open Animated Title window, there is a core dump in 2.0.7. Same in 2.0.6.

I'm on manjaro and used a modified PKGBUILD with last version (just change 2.0.6 to 2.0.7).

Same bugs same crashs

**Comment by andrewcharnley** [comment]
This problem exists on Fedora 24 as well (but worked on Fedora 23). I believe it's the version of Python3 but could be wrong.

**Comment by jonoomph** [comment]
Please test again with the latest daily build of OpenShot. I've merged in changes to the text alignment, and updated the minimum version compatibility to 2.78. I've tested all animation on Linux, Mac, and Windows with Blender 2.78 and everything works great.

Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot. _It might take a couple hours for the latest version to appear._

If you have other issues, please file additional bugs for each one. Thanks!
