### ISSUE TITLE
Program freezes and then closes when it's trying to export video with target AVI (mpeg2)

### ISSUE THREAD

**Issue by DennisMont** [OpenShot/openshot-qt#2370]
**Describe the bug**
When it's trying to export a video with target AVI(mpeg2), program begins to export and then it freezes, then it closes. It was tried to export with AVI(mpeg4) and there is no problem. It was also tried to change the video profile but the problem persists. See second screenshot.

**System Details (please complete the following information):**
 - Windows 10 Home.
 - OpenShot Version 2.4.3

**To Reproduce**
1. Go to File > Import files and select a file (In order to reproduced the bug, it was selected a file with the characteristics shown in first figure of Screenshots).
2. Drag the imported file to Track 0.
3. Go to File > Export Video. 
4. In Export Video window, set the next configurations:
          Profile: All formats
          Target: AVI (mpeg2)
          Video Profile: QVGA 15 FPS(320x240)
          Quality: med

**Expected behavior**
The export must be done succesfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/42948466/48674635-bd2d1b00-eb24-11e8-9529-4db336a26e8e.png)
![image](https://user-images.githubusercontent.com/42948466/48674835-10a06880-eb27-11e8-9d0c-1afd1b443d30.png)

**Logs**
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2592944/openshot-qt.log)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/2592945/libopenshot.log)

**Additional context**
It was tried to export video with other Video Profiles:
      CIF PAL (352x288)
      HD 1080i 25 fps(1920x1080)
The problem persists.

**Comment by speedytechdev** [comment]
@DylanC Confirmed Bug 
![image](https://user-images.githubusercontent.com/40452959/48693944-d5458d00-ec3f-11e8-9b58-85a46a6daf92.png)

**Comment by speedytechdev** [comment]
@DylanC Confirmed Bug. It got up till here then crashed.
![crop](https://user-images.githubusercontent.com/40452959/48694069-2f465280-ec40-11e8-9d61-3448798725f8.png)

**Comment by speedytechdev** [comment]
@DylanC Confirmed Bug. It got up till here then crashed.
![crop](https://user-images.githubusercontent.com/40452959/48694117-53099880-ec40-11e8-9f4c-b8477b4b324a.png)

**Comment by speedytechdev** [comment]
Hi @DennisMont thanks for letting us know about the issue. This is a confirmed bug and we will hopefully have it fixed soon.

**Comment by DennisMont** [comment]
You're welcome. Thank you for the software.

**Comment by peanutbutterandcrackers** [comment]
If this is a bug, I'll label it as such, based on @speedytechdev's inquiries. (I myself haven't followed this thread through)
