### ISSUE TITLE
How do I make an Openshot installation file executable?

### ISSUE THREAD

**Issue by LeonArundell** [OpenShot/openshot-qt#2376]
**My Question:**
How do I make an Openshot installation file executable?
The Linux upgrade instructions say, "AppImage requires no installation. Just download, make executable, and run."

**System Details**
 - Operating System / Distro: [Linux Kubuntu 18.04]
 - OpenShot Version [2.4.1]

**Comment by bostontrader** [comment]
Find the file in your file system.  From the terminal:

chmod 700 /path/to/filename.

700 is not carved in stone.  It's read/write/execute for your present user.  This is just one of several possible sets of permissions.

**Comment by peanutbutterandcrackers** [comment]
In some distros you might also have something akin to this, in the right-click menu:
(all you need to do is mark it as execuatable)
![screenshot at 2018-11-26 15-29-45](https://user-images.githubusercontent.com/26764547/49006018-3b766680-f190-11e8-9889-63d9ea798ef7.png)

Closing this as answered. Please do feel free to re-open if you require any further assistance.
