### ISSUE TITLE
Openshot 2.4.1 crashing while exporting video in any format - Windows 7

### ISSUE THREAD

**Issue by bryisfly** [OpenShot/openshot-qt#2377]
**Describe the bug**
Silent crash on openshot upon reaching 76%. Can someone help me with this?

**System Details (please complete the following information):**
 - Operating System / Distro: Windows 7
 - OpenShot Version 2.4.1

**Comment by speedytechdev** [comment]
Hi, @bryisfly I would recommend using 2.4.3. This version has fixed a lot of bugs so it might fix your issue.

**Comment by MadEdward** [comment]
Hi Speedytechdev, as you know I have posted the same problem twice with Openshop 2.4.3, so that version definetely does NOT solve the problem, which seems storage/memory related. When might we expect a solution to the problem, without having to buy a new computer with 32 GiB RAM???
Kind regards, Max (MadEdward as a nickname).

**Comment by speedytechdev** [comment]
@MadEdward I know it is a pain but we are trying to fix the bugs. There are a lot of bugs and not enough staff.

**Comment by peanutbutterandcrackers** [comment]
It seems we have quite a lot of problems when it comes to Windows machines. I was able to successfully create the following video on my Linux Mint 19 machine that has only 2GB RAM, 2x2.16GHz Intel Celeron N3050 processor and Mesa DRI Intel(R) HD Graphics 400 (Braswell):
![meet tux](https://user-images.githubusercontent.com/26764547/48016787-a1a13800-e154-11e8-9f1d-bfe2a64a6ad4.gif)

However, we can always hope for the best in the future releases.

Just in case you have a project you have worked hard on, I suggest you do not delete the project but keep it. Perhaps a future version of OpenShot will be able to export it. Or, you could try exporting in different targets - webp, ogg, mp4, flv, etc. and see if any of that works out for you. Or, you could use the daily builds.

Hope that helps.

**Comment by pazush** [comment]
Hi there, i was crashing too
i solved it by creating a virtual memory allocation for my computer - also called (google for:) Page file
i have 16gb ram and never needed more... but seems like openshot eats loads of ram
so by creating a virtual memory ive managed to stop those crashes.
