### ISSUE TITLE
Openshot 2.4.3 on Windows 10 cannot save trimmed video

### ISSUE THREAD

**Issue by Freimann1** [OpenShot/openshot-qt#2378]
**My Question:**
I am new to this. I cannot import .mp4 1080p files to Openshot. After playing around with the red recording button in VLC, I managed to change by .mp4 to a .TS file, which was accepted by Openshot.

After Split Clip, I tried to export the trimmed video but it won't work for any of the formats. Whatever the format, it just results in that file extension with zero byte in it (the export progress never changed from 0% i.e. no info was exported. I played with Advanced tab. Changing the "End Frame" to a large number from the default of 1 leads to a few thousand bytes in the exported file but it cannot be placed by VLC.

Any pointers would be most welcome.

Thanks

**System Details**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**Screenshots**

**Comment by peanutbutterandcrackers** [comment]
Possible duplicate of #2114
