### ISSUE TITLE
Missing File

### ISSUE THREAD

**Issue by gmseed** [OpenShot/openshot-qt#2379]
Steps to Reproduce:

1) Create a new project and in the project folder add a single image called, say, image.png.
2) Drag and drop image.png into the Project Files section.
3) Drag and drop image.png from Project Files onto Tracks 4, 3, 2, 1 and 0. That is, image.png has been added to 5 separate tracks.
4) Save the project and quit OVE.
5) Relaunch the editor and from the Recent files select the newly create project.
6) A Missing File dialog appears stating that image.png is missing. Click OK and then click Cancel on the file selector dialog.
7) You'll see that this OK-Cancel process will continue 5 times, ie the number of times image.png was dragged onto the number of tracks.

Thus, really there is only 1 file missing but we receive the OK-Cancel for the number of times the file is used. This could be a lot!! When really there is just 1 missing file and the OK dialog should only appear once. 

OS: Win7

**Comment by speedytechdev** [comment]
Hi @gmseed this has been fixed in a daily build. Please let me know if the issue has been solved.

**Comment by peanutbutterandcrackers** [comment]
Closing this as answered. Like @speedytechdev has said, please try the daily build. This issue has been fixed and I myself have personally been able to verify the fact. Here is how you can get a hold of the daily builds: https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914

Hope that helps!

Please do keep on loving and supporting OpenShot. It'll only get better with time.
