### ISSUE TITLE
v2.4.3 repeatedly Not Responding - Improper Installation?

### ISSUE THREAD

**Issue by kcaauwe** [OpenShot/openshot-qt#2380]
OS: Windows 10
Device: Dell Inspiron 15-7579, 64-bit Intel i7 processor, 12GB RAM
Openshot Versions tried: v2.4.3 (64-bit), v2.4.3 (32-bit), daily build OpenShot-v2.4.3-dev1-1542715254-31e9e7b6-3861a2c5-x86_64.exe (64-bit)

Each version of OpenShot that I've tried becomes unresponsive.  Before I tried different versions I uninstalled the previous version and deleted any associated files from my machine left after the uninstall finished.  

I'm able import a file, but as soon as I attempt to edit the video file in any way, the application becomes unresponsive (Not Responding).  I've tried closing the app using the exit and the control panel.  When I re-open the application it them immediately becomes unresponsive. 

I've read through the form and looked at other questions/bugs but i'm not finding where I'm going wrong. Any tips would be appreciated.

Attached are my logs. 

Thanks!
KC
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/2600343/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2600344/openshot-qt.log)

**Comment by peanutbutterandcrackers** [comment]
OpenShot does have quite a lot of performance related issues. Perhaps, for the time being, you should use some other Libre video editors like [KdenLive](https://www.kdenlive.org/) and [Shotcut](https://shotcut.org/), and keep on testing OpenShot using the [daily builds](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914).

However, OpenShot does seem to work well on GNU/Linux Machines. The following is a video I was able to make on my Linut Mint 19 MATE laptop with only 2GB RAM:
![meet tux](https://user-images.githubusercontent.com/26764547/48016787-a1a13800-e154-11e8-9f1d-bfe2a64a6ad4.gif)

**Comment by DylanC** [comment]
@kcaauwe - Can you try the just released version? (v2.4.4)
