### ISSUE TITLE
Timeline Time Signatures Incorrect

### ISSUE THREAD

**Issue by MrTeeXD** [OpenShot/openshot-qt#2381]
**Describe the bug**
Openshot's timeline Time signatures are wrong

**System Details (please complete the following information):**
 - Operating System / Distro: [Windows 10]
 - OpenShot Version [2.4.3 Latest Daily Build]

**To Reproduce**
1. Go to Project Files 
2. Drag a video clip on the timeline
3. Look at the time signatures

**Expected behavior**
The time signatures are corrected

**Screenshots**
![screenshot 86](https://user-images.githubusercontent.com/37266538/48795186-c8d73800-ed04-11e8-9644-ea0b54c04624.png)

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**
This is a rather strange Calculation that OpenShot is doing on the timeline

**Comment by peanutbutterandcrackers** [comment]
I wonder if this is happening because you are probably using a X-FPS footage in a Y-FPS profile? Could you please use something like [MediaInfo](https://mediaarea.net/en/MediaInfo) to figure out the exact FPS of your footage? Thanks!

**Comment by speedytechdev** [comment]
@MisterTeeXD Can you let us know if this fixed the issue, please. So we know whether or not to close this issue.
