### ISSUE TITLE
Error de exportación

### ISSUE THREAD

**Issue by JoaquinEMZ** [OpenShot/openshot-qt#2383]
Realice mi edición de video y al exportarlo en el formato:
Objetivo: MP4(h.264)
Perfil de video: 1024x576 16:9 PAL (1024x576)
Calidad: Media
El software OpenShot se cierra automaticamente si la posibilidad de exportarlo. Esto sucede con cualquier tipo de objetivo o calidad. No puedo generar el video por que se auto cierra y no señala errores en pantalla.

 - Window 10 x64
 - OpenShot Version 2.4.3.

1. Ir a Exportar Video
2. Seleccionar Exportar video.

Espero que empiece el proceso de exportar el vídeo a su formato especificado.
![sin titulo](https://user-images.githubusercontent.com/39202503/48805709-d4bbfd80-ecf6-11e8-9750-572e2c6e5472.png)

Comentarios:
Pocas opciones para la disposición del vídeo, no se puede dividir la pantalla en dos imágenes, no se puede especificar el video sin animación.

**Comment by DylanC** [comment]
Please report issues in English if possible. We do not speak languages other than English.
