### ISSUE TITLE
Openshot Freezes on Ubuntu When Timeline is Resized with a clip

### ISSUE THREAD

**Issue by abegosum** [OpenShot/openshot-qt#2384]
**Describe the bug**
After dropping a video onto a track in the timeline, resizing the timeline section of the window causes the application to freeze.

**System Details (please complete the following information):**
 - Operating System / Distro: Ubuntu 18.04, using Gnome 3
 - OpenShot Version [e.g. 2.4.1]: 2.4.3

**To Reproduce**
1. Open Openshot
2. Import a video asset into the project files section (in my case, an mp4 with an AVC encoded video track and an AAC encoded audio track)
3. Drag the imported video asset into the timeline
4. Right-click the video in the timeline and select Properties to display the video properties pane
5. Grab the handle in the middle of the OpenShot window above the timeline and drag up to increase the size of the timeline
6. After releasing the handle, the window freezes with the cursor changed to the drag icon; even closing doesn't work
7. If you try to close using the close window button, eventually Gnome prompts you to close the frozen window

**Expected behavior**
Upon completion of the resize of the timeline, I expect the cursor to return to the default and to be able to continue working.

**Additional context**
I have also replicated this issue in Ubuntu 18.04 using KDE Plasma desktop; so, it is not unique to Gnome

**Comment by peanutbutterandcrackers** [comment]
Hmm... strange. Can't replicate on my machine running Linux Mint 19 using a 44 second long webm video. Perhaps I need to use mp4? Or, maybe it's the time duration? How long was your clip, sir?

**Comment by SteveIDusa** [comment]
Going to offer my 2 cents. I have been able to document the freeze that I experience when editing Video in Linux Mint 19. I have created a short video to demonstrate.....https://youtu.be/nNZzEqqj_KM

The clip that is being edited was created in Simple Screen Recorder, its settings are displayed at the beginning of the video as screen shots.

I have been using Openshot for about 6 months, its simplicity is very appealing, the fact it is opensource is even more appealing. For my first 10 Videos I had no problem with using it, but I am not sure what version it was that was installed as it was provided via the in Linux Mint Software Manager in Mint 18.3. After completing a fresh install of Mint 19 I started having problems with the repo version so I went to the Openshot website and setup the PPA to get the current stable release. However this did not seem to solve the problem and I have been trying to work around it and periodically do some additional research to see if it has been resolved. That was the reason for the attempt today using the WebM and VP8 settings. But coming back to it today I find that it is still an issue even with these other settings. 

So if there is anything else that I can provide please feel free to ask. I can confirm that with this little 2 min video using mp4 and h256 I did not experience any freeze problems. I can also confirm that I have seen mp4 and h256 experience freezes on longer clips like the one today.
