### ISSUE TITLE
Add More Effects Or Allow People To Add Effects

### ISSUE THREAD

**Issue by speedytechdev** [OpenShot/openshot-qt#2385]
It would be nice to be able to have more effects than just 8. A lot of people have requested it and nothing has happened. If we cant add more effects then make it easy for people to add more.

**Comment by peanutbutterandcrackers** [comment]
I shall be closing this as [this is already a plan](https://www.openshot.org/blog/2018/01/01/happy-new-year-2018/), and also because you are one of the team now.
