### ISSUE TITLE
Openshot does not start

### ISSUE THREAD

**Issue by chorez** [OpenShot/openshot-qt#2386]
**Describe the bug**
I installed Openshot for the first time and tried to open it and literally nothing happens. I checked task manager: The process "launch.exe" does appear, but disappears after a while. The program never launched so far. I tried running it as administrator, but did not work either.

I also tried installed older versions of Openshot without success.
2.4.1 and 2.2.0

**System Details (please complete the following information):**
 - Operating System / Distro: Win 10
 - OpenShot Version [2.4.3 and older versions

LOGS:
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2604834/openshot-qt.log)

**Comment by peanutbutterandcrackers** [comment]
This is interesting. Thank you for the thoughtfulness. However, it seems the openshot-qt.log doesn't contain anything quite substantial. Could you please also attach `libopenshot.log`? However, before doing that, I would advise you to delete the `.openshot_qt` director/folder entirely and only then run Openshot, and once `launch.exe` vanishes from the task-manager processes, attach both libopenshot and openshot log here. That way, we'll have smaller logs and will also have more relevant information. Thank you!

**Comment by Flower2012** [comment]
Hi, 
I have the same problem here. I could install the software however could not open it. Every time I try to open it I get a message (please, see attachment). So, until now I could not run it. 
I am using 32 bit Windows 2007. 
Please, help me. 
Thanks in advance for your help. 
Warm Regards,

![untitled](https://user-images.githubusercontent.com/45470420/49254242-ef0e7d80-f452-11e8-8f23-36fda73a30ff.jpg)

**Comment by Flower2012** [comment]
When I click OK. Every thing ends in a void.

**Comment by JAndersM** [comment]
I get the same type of error when trying to start OpenShot under Win10.
![2018-12-18](https://user-images.githubusercontent.com/16062873/50171438-be539280-02f2-11e9-8c60-21bd79a07c5f.png)

I have had this error for a long time and been hoping that new versions should fix it. Bun sadly no change.

**Comment by ferdnyc** [comment]
I'm going to close this in favor of the more detailed #2748, for OpenShot 2.4.4.

**Comment by gb9130** [comment]
Same problem 4 years later. I installed Linux Lite 6.0 and Openshot via Lite's Software manager. All attempts to launch Openshot resulted in nothing; no error msgs. Any thoughts?

**Comment by JacksonRG** [comment]
@gb9130 I'm not sure what version Lite's Software Manager has access to. We maintain a PPA, but otherwise, leave it to the package managers.

We have an appiamge available [here](https://www.openshot.org/download/). I'd love to hear if that has any problems launching.

**Comment by gb9130** [comment]
Good question. Since Openshot won't launch, how can I tell which version is
installed?
Gil

**Comment by gb9130** [comment]
Was able to generate an error message by running the terminal command
openshot-qt.
Getting MSG: Error determining OS version in metrics.py, but I can't find
the file metrics.py.
See below.
Note that Linux Lite 6.0 changed etc/os-release from "Ubuntu' to "Linux
Lite 6". So I suspect Openshot needs to be updated. Your thoughts?
Gil
----------------------------------------------------
Welcome to Linux Lite 6.0 user

Wednesday 10 August 2022, 13:32:41
Memory Usage: 590/3876MB (15.22%)
Disk Usage: 21/109GB (20%)
Support - https://www.linuxliteos.com/forums/ (Right click, Open Link)
user  ~  openshot
openshot: command not found
user  ~  127  openshot-qt
Loaded modules from installed directory:
/usr/lib/python3/dist-packages/openshot_qt
app:INFO ------------------------------------------------
app:INFO Wed Aug 10 13:33:03 2022
app:INFO Starting new session
app:INFO ------------------------------------------------
app:INFO OpenShot (version 2.5.1)
app:INFO ------------------------------------------------
app:INFO openshot-qt version: 2.5.1
app:INFO libopenshot version: 0.2.5
app:INFO platform: Linux-5.15.0-46-generic-x86_64-with-glibc2.35
app:INFO processor: x86_64
app:INFO machine: x86_64
app:INFO python version: 3.10.4
app:INFO qt5 version: 5.15.3
app:INFO pyqt5 version: 5.15.6
metrics:ERROR Error determining OS version in metrics.py
language:INFO Qt Detected Languages: ['en-US']
language:INFO LANG Environment Variable: en_US.UTF-8
language:INFO LOCALE Environment Variable:
language:INFO OpenShot Preference Language: Default
project_data:INFO Setting default profile to HD 720p 30 fps
app:INFO Setting font to Cantarell
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
app:INFO Setting custom dark theme
QMainWindow::addDockWidget: invalid 'area' argument
ui_util:INFO Initializing UI for MainWindow
exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
File "/usr/bin/openshot-qt", line 33, in <module>
sys.exit(load_entry_point('openshot-qt==2.5.1', 'gui_scripts',
'openshot-qt')())
File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 97, in
main
app = OpenShotApp(argv)
File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 219,
in __init__
self.window = MainWindow(mode)
File "/usr/lib/python3/dist-packages/openshot_qt/windows/main_window.py",
line 2521, in __init__
self.timeline = TimelineWebView(self)
File
"/usr/lib/python3/dist-packages/openshot_qt/windows/views/timeline_webview.py",
line 3000, in __init__
self.cache_renderer.setInterval(0.5 * 1000)
TypeError: setInterval(self, int): argument 1 has unexpected type 'float'
version:INFO Found current version: {"trans_rate_unstable": 0.001,
"error_rate_stable": 0.16, "openshot_version": "2.6.1",
"trans_rate_stable": 0.01, "error_rate_unstable": 0.05}

**Comment by gb9130** [comment]
No progress. Anyone have a suggestion? GB

**Comment by JacksonRG** [comment]
@gb9130 To find the version number, you can click `Help` > `About OpenShot` at the top of the window. But from that terminal output you posted, it looks like you're on version 2.5.1 our current release version is 2.6.1 though. Have you tried 2.6.1 or the daily build?

**Comment by listlfa** [comment]
tried with below (2.6.1)
edit : shoot, i only looked at the last few lines which said 2.6.1.  i had 2.5.1 which is the latest xubuntu had :/  sorry

fixed with
https://howtotrainyourrobot.com/openshot-on-ubuntu-22-04/

--@----:~$ openshot-qt 
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
         app:INFO ------------------------------------------------
         app:INFO             Mon Nov  7 17:13:11 2022            
         app:INFO               Starting new session              
         app:INFO ------------------------------------------------
         app:INFO             OpenShot (version 2.5.1)            
         app:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.5.1
         app:INFO libopenshot version: 0.2.5
         app:INFO platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.35
         app:INFO processor: x86_64
         app:INFO machine: x86_64
         app:INFO python version: 3.10.6
         app:INFO qt5 version: 5.15.3
         app:INFO pyqt5 version: 5.15.6
     metrics:ERROR Error determining OS version in metrics.py
    language:INFO Qt Detected Languages: ['en-AU', 'en']
    language:INFO LANG Environment Variable: en_AU.UTF-8
    language:INFO LOCALE Environment Variable: 
    language:INFO OpenShot Preference Language: Default
project_data:INFO Setting default profile to HD 720p 30 fps
ZmqLogger::Connection - Error binding to tcp://*:5556. Switching to an available port.
ZmqLogger::Connection - Error binding to tcp://*:5556. Switching to an available port.
         app:INFO Setting font to Cantarell
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
         app:INFO Setting custom dark theme
QMainWindow::addDockWidget: invalid 'area' argument
     ui_util:INFO Initializing UI for MainWindow
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "/usr/bin/openshot-qt", line 33, in <module>
    sys.exit(load_entry_point('openshot-qt==2.5.1', 'gui_scripts', 'openshot-qt')())
  File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 97, in main
    app = OpenShotApp(argv)
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 219, in __init__
    self.window = MainWindow(mode)
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/main_window.py", line 2521, in __init__
    self.timeline = TimelineWebView(self)
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/views/timeline_webview.py", line 3000, in __init__
    self.cache_renderer.setInterval(0.5 * 1000)
TypeError: setInterval(self, int): argument 1 has unexpected type 'float'
     version:INFO Found current version: {"error_rate_unstable": 0.05, "trans_rate_unstable": 0.001, "trans_rate_stable": 0.01, "error_rate_stable": 0.16, "openshot_version": "2.6.1"}
^C      logger:ERROR Exception ignored in:
      logger:ERROR <module 'threading' from '/usr/lib/python3.10/threading.py'>
      logger:ERROR Traceback (most recent call last):
      logger:ERROR   File "/usr/lib/python3.10/threading.py", line 1567, in _shutdown
      logger:ERROR lock.acquire()
      logger:ERROR KeyboardInterrupt
      logger:ERROR :
         app:INFO             OpenShot's session ended            
         app:INFO             Mon Nov  7 17:14:05 2022            
         app:INFO ================================================
