### ISSUE TITLE
Missed effects

### ISSUE THREAD

**Issue by mbnoimi** [OpenShot/openshot-qt#2387]
In my distro there are 14 effects only while the others are missing!

How can I fix this issue?

**System Details:**
 - Operating System / Distro: Linux Mint 19 x64 - xfce
 - OpenShot Version: 2.4.3-dev1
 - PPA: ppa:openshot.developers/ppa

**Screenshots**
![image](https://user-images.githubusercontent.com/284547/48856613-e6210a80-edc7-11e8-9c7a-c996d876a1f7.png)

**Comment by peanutbutterandcrackers** [comment]
No, sir. None of the effects are missing. The images that you must have seen are from OpenShot 1.x series, which had a few more effects. However, OpenShot 2.x is a complete re-write of the program using different technologies and the effects are still being ported (and might take quite a lot of time to be fully ported). So, you'll just have to wait for newer releases to get new effects.

Hope that clears things for you.

Closing as answered.
