### ISSUE TITLE
python error in main script

### ISSUE THREAD

**Issue by bartschoneveld** [OpenShot/openshot-qt#2388]
![image](https://user-images.githubusercontent.com/9466558/48871734-3e670500-ede6-11e8-9437-e3db4af2a49d.png)

Windows 10 64

**Comment by bartschoneveld** [comment]
Thnxs peanutbutterandcrackers,

Unfortunately this didn't  work...

kind regards,
Bart

**Comment by peanutbutterandcrackers** [comment]
@ferdnyc - Sorry to bother you again, but this issue seems to be related to the other one where you did some `.dll` checking and figured the solution out. Perhaps this will be of interest to you, too?

**Comment by ferdnyc** [comment]
It does appear very similar to #2367, so I'll suggest the same troubleshooting steps (minus some flailing around) that worked there.

@bartschoneveld , if you could please try the following:
1. Download [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) from the Microsoft SysInternals library. (It doesn't need to be installed, you just extract and run it.)
1. Launch OpenShot, and leave that error box open when it appears
1. Open (or launch) Process Explorer
1. Hit <kbd>Ctrl</kbd>+<kbd>d</kbd> to open Process Explorer's bottom pane
1. Select `launch.exe` (the still-running OpenShot launcher) in the top half of the window
1. Click on anything in the bottom half of the window, then hit <kbd>Ctrl</kbd>+<kbd>a</kbd>
1. A file-save dialog will open, asking to save a text file. Save it anywhere you like. That file will contain a list of all the DLLs that have been loaded by OpenShot.
1. Go to the folder where you saved the file, then drag-and-drop it (the text file) into the comment editor for this issue. That'll upload the file to GitHub and insert it into your comment.
1. Post the Comment containing the text file, and we'll take a look at it to see if we can find the source of the problem.

**Comment by khaledouf** [comment]
[launch.exe.txt](https://github.com/OpenShot/openshot-qt/files/2621406/launch.exe.txt)

**Comment by speedytechdev** [comment]
@bartschoneveld Can you let us know if this fixed the issue, please? So we know whether or not to close this issue.

**Comment by bartschoneveld** [comment]
Unfortunately all of the above suggested solutions failed.....

**Comment by speedytechdev** [comment]
Sorry to hear that. Until the issue is fixed this will stay open and sorry for the inconvenience this has caused you.

**Comment by ferdnyc** [comment]
How can my suggestion have "failed"? My suggestion was that you collect data and provide it to us, so that we can try to help you. We can't do that without information.

So, again:
> @bartschoneveld , if you could please try the following:
> 
> 1. Download [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) from the Microsoft SysInternals library. (It doesn't need to be installed, you just extract and run it.)
> 2. Launch OpenShot, and leave that error box open when it appears
> 3. Open (or launch) Process Explorer
> 4. Hit Ctrl+d to open Process Explorer's bottom pane
> 5. Select `launch.exe` (the still-running OpenShot launcher) in the top half of the window
> 6. Click on anything in the bottom half of the window, then hit Ctrl+a
> 7. A file-save dialog will open, asking to save a text file. Save it anywhere you like. That file will contain a list of all the DLLs that have been loaded by OpenShot.
> 8. Go to the folder where you saved the file, then drag-and-drop it (the text file) into the comment editor for this issue. That'll upload the file to GitHub and insert it into your comment.
> 9. Post the Comment containing the text file, and we'll take a look at it to see if we can find the source of the problem.

**Comment by bartschoneveld** [comment]
Dear ferdnyc,

Thanks for your effort to solve this problem.
Process	CPU	Private Bytes	Working Set	PID	Description	Company Name
Registry		740 K	8.212 K	96		
System Idle Process	85.80	52 K	8 K	0		
System	0.29	212 K	10.928 K	4		
 Interrupts	1.00	0 K	0 K	n/a	Hardware Interrupts and DPCs	
 smss.exe		492 K	1.144 K	404		
csrss.exe	< 0.01	1.912 K	5.332 K	568		
wininit.exe		1.380 K	6.564 K	664		
 services.exe		5.748 K	10.344 K	736		
  svchost.exe		976 K	3.892 K	864	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		12.676 K	28.428 K	920	Hostproces voor Windows-services	Microsoft Corporation
   ShellExperienceHost.exe	Suspended	63.748 K	119.752 K	7736	Windows Shell Experience Host	Microsoft Corporation
   SearchUI.exe	Suspended	94.804 K	163.456 K	7948	Search and Cortana application	Microsoft Corporation
   RuntimeBroker.exe		8.356 K	22.980 K	5000	Runtime Broker	Microsoft Corporation
   RuntimeBroker.exe		9.728 K	33.172 K	1144	Runtime Broker	Microsoft Corporation
   SkypeBackgroundHost.exe	Suspended	2.012 K	3.168 K	9112	Microsoft Skype	Microsoft Corporation
   RuntimeBroker.exe		11.208 K	32.276 K	9888	Runtime Broker	Microsoft Corporation
   EasyMailReLaunch.exe	Suspended	27.256 K	41.380 K	940	EasyMailReLaunch	
   SkypeApp.exe	Suspended	200.060 K	172.804 K	7832	SkypeApp	Microsoft Corporation
   SettingSyncHost.exe	0.02	2.764 K	11.248 K	820	Host Process for Setting Synchronization	Microsoft Corporation
   RuntimeBroker.exe		6.996 K	24.352 K	5756	Runtime Broker	Microsoft Corporation
   RuntimeBroker.exe		8.480 K	29.124 K	11068	Runtime Broker	Microsoft Corporation
   LockApp.exe	Suspended	15.080 K	43.572 K	2276	LockApp.exe	Microsoft Corporation
   RuntimeBroker.exe		6.736 K	29.076 K	8736	Runtime Broker	Microsoft Corporation
   Microsoft.Photos.exe	Suspended	145.460 K	112.596 K	10476		
   RuntimeBroker.exe	< 0.01	14.052 K	34.356 K	5896	Runtime Broker	Microsoft Corporation
   dllhost.exe		2.264 K	10.708 K	10212	COM Surrogate	Microsoft Corporation
   smartscreen.exe		13.792 K	27.244 K	8856	Windows Defender SmartScreen	Microsoft Corporation
  svchost.exe	0.01	10.404 K	17.548 K	976	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		3.016 K	8.336 K	72	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		2.328 K	9.648 K	1184	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		2.128 K	10.048 K	1208	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		2.504 K	10.880 K	1216	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		1.612 K	6.836 K	1224	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		7.100 K	15.572 K	1316	Hostproces voor Windows-services	Microsoft Corporation
   taskhostw.exe		11.892 K	22.228 K	3480	Hostproces voor Windows-taken	Microsoft Corporation
   DropboxUpdate.exe		2.112 K	3.416 K	3488		
  svchost.exe		2.656 K	10.556 K	1348	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		1.592 K	5.920 K	1468	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		16.156 K	19.588 K	1488	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		2.148 K	11.448 K	1532	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		2.744 K	9.324 K	1616	Hostproces voor Windows-services	Microsoft Corporation
   sihost.exe		7.028 K	26.128 K	2452	Shell Infrastructure Host	Microsoft Corporation
  svchost.exe		1.692 K	6.884 K	1644	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		5.684 K	9.592 K	1720	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		12.984 K	22.484 K	1756	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		1.840 K	7.900 K	1768	Hostproces voor Windows-services	Microsoft Corporation
   ctfmon.exe		8.148 K	20.236 K	9192		
  svchost.exe		2.160 K	8.072 K	1796	Hostproces voor Windows-services	Microsoft Corporation
   dasHost.exe		6.864 K	18.156 K	1996		
  svchost.exe		1.748 K	7.212 K	1804	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		2.528 K	7.724 K	1876	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		2.012 K	7.760 K	1512	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		1.348 K	5.732 K	1900	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		5.756 K	13.028 K	1948	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		2.080 K	8.336 K	2100	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		1.972 K	7.760 K	2140	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		1.916 K	9.820 K	2148	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe	< 0.01	3.788 K	9.960 K	2156	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		2.596 K	7.820 K	2340	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		3.276 K	12.524 K	2376	Hostproces voor Windows-services	Microsoft Corporation
   audiodg.exe		11.116 K	18.300 K	13340		
  svchost.exe		7.976 K	16.432 K	2436	Hostproces voor Windows-services	Microsoft Corporation
  WTabletServicePro.exe		1.604 K	7.316 K	2524	Tablet Service	Wacom Technology, Corp.
   Wacom_TabletUser.exe		1.872 K	8.368 K	2928	Tablet user module for professional driver	Wacom Technology, Corp.
   WacomHost.exe		1.700 K	11.616 K	2984		
    Wacom_Tablet.exe	< 0.01	10.288 K	27.460 K	4532		
   Wacom_TouchUser.exe	0.01	5.676 K	15.000 K	3860		
  RtkAudioService64.exe		1.744 K	7.448 K	2532	Realtek Audio Service	Realtek Semiconductor
   RAVBg64.exe		4.148 K	11.540 K	2632		
  svchost.exe	0.04	3.748 K	8.868 K	2660	Hostproces voor Windows-services	Microsoft Corporation
  QHActiveDefense.exe	0.04	374.240 K	307.944 K	2672	360 Total Security	Qihoo 360 Technology Co. Ltd.
   QHWatchdog.exe	< 0.01	1.016 K	4.860 K	7108		
   QHSafeTray.exe	0.03	28.828 K	55.396 K	8568		
    QHSafeMain.exe	0.84	50.992 K	89.808 K	10992		
  svchost.exe		1.952 K	6.584 K	2680	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		3.912 K	12.868 K	2692	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe	< 0.01	2.408 K	7.436 K	2896	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		5.996 K	19.324 K	2216	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		9.188 K	27.828 K	2936	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		2.920 K	13.540 K	3140	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		11.048 K	38.976 K	3248	Hostproces voor Windows-services	Microsoft Corporation
  spoolsv.exe	< 0.01	10.392 K	25.192 K	3256	App voor Spooler-subsysteem	Microsoft Corporation
  svchost.exe		2.072 K	7.956 K	3308	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		1.368 K	5.888 K	3872	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		2.408 K	8.880 K	4240	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		3.920 K	13.384 K	4280	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		1.740 K	7.152 K	4544	Hostproces voor Windows-services	Microsoft Corporation
  3DPrintService.exe		1.052 K	4.664 K	4560		
  AGSService.exe		1.996 K	11.100 K	4568	Adobe Genuine Software Integrity Service	Adobe Systems, Incorporated
  AGMService.exe	0.02	2.536 K	11.204 K	4584	Adobe Genuine Software Service	Adobe Systems, Incorporated
  mDNSResponder.exe	0.02	2.112 K	6.864 K	4592	Bonjour Service	Apple Inc.
  BayerHCService.exe	< 0.01	14.048 K	18.376 K	4600	Bayer Healthcare Service	Bayer Healthcare LLC
  HidMonitorSvc.exe		1.196 K	5.348 K	4608	HidMonitorSvc Application	Alps Electric Co., Ltd.
   Apoint.exe	0.03	4.048 K	19.116 K	6088	Alps Pointing-device Driver	Alps Electric Co., Ltd.
    ApMsgFwd.exe	1.09	1.840 K	6.956 K	6812		
    hidfind.exe		1.188 K	5.140 K	7124	Alps Pointing-device Driver	Alps Electric Co., Ltd.
  AppleMobileDeviceService.exe	0.01	3.540 K	12.468 K	4616	MobileDeviceService	Apple Inc.
  svchost.exe		7.028 K	16.476 K	4624	Hostproces voor Windows-services	Microsoft Corporation
  cnwisam.exe		2.752 K	10.412 K	4644	imagePROGRAF Status Monitor for x64 Edition	CANON INC
  svchost.exe		8.108 K	23.044 K	4656	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		13.728 K	22.948 K	4664	Hostproces voor Windows-services	Microsoft Corporation
  devolonetsvc.exe	1.15	6.748 K	12.984 K	4684	devolo Network Service	devolo AG
  loggerservice.exe	< 0.01	1.580 K	6.512 K	4692	Dragon NaturallySpeaking Logging Service	Nuance Communications, Inc.
  dgnsvc.exe		1.632 K	7.440 K	4700	Dragon NaturallySpeaking Service	Nuance Communications, Inc.
  hasplms.exe	0.07	21.304 K	20.760 K	4712	Sentinel LDK License Manager Service	SafeNet Inc.
  ibtsiva.exe		1.060 K	4.240 K	4736	Intel(R) Wireless Bluetooth(R) iBtSiva Service	Intel Corporation
  cnwiols6.exe		1.256 K	5.060 K	4744	Canon IOS Core Module	CANON INC.
  sqlservr.exe	0.16	278.380 K	133.188 K	4840	SQL Server Windows NT - 64 Bit	Microsoft Corporation
  NitroPDFReaderDriverService5x64.exe		1.284 K	5.272 K	4944	Nitro PDF Spool Service	Nitro Software, Inc.
  sqlbrowser.exe		1.452 K	4.540 K	5004	SQL Browser Service EXE	Microsoft Corporation
  sqlwriter.exe		1.776 K	7.608 K	5016	SQL Server VSS Writer - 64 Bit	Microsoft Corporation
  svchost.exe		1.636 K	6.432 K	5024	Hostproces voor Windows-services	Microsoft Corporation
  SecurityHealthService.exe		3.980 K	14.716 K	5032	Windows Security Health Service	Microsoft Corporation
  svchost.exe	< 0.01	3.864 K	12.572 K	5084	Hostproces voor Windows-services	Microsoft Corporation
  ThreeshipsHelperService.exe		11.280 K	15.816 K	5100	Three Ships Helper Service	Three Ships
  svchost.exe		1.368 K	5.600 K	5108	Hostproces voor Windows-services	Microsoft Corporation
  Lavasoft.WCAssistant.WinService.exe	< 0.01	36.028 K	53.024 K	3416	SPWindowsService	
  svchost.exe		5.068 K	20.908 K	4224	Hostproces voor Windows-services	Microsoft Corporation
  atwtusb.exe		1.612 K	6.620 K	4272	User Mode Tablet Driver	
   atwtusb.exe		2.060 K	8.688 K	13500		
  LDSvc.exe	0.09	21.684 K	56.684 K	5208	PACE License Service	PACE Anti-Piracy, Inc.
  svchost.exe		3.980 K	12.200 K	5324	Hostproces voor Windows-services	Microsoft Corporation
  CodeMeter.exe	0.09	4.068 K	15.396 K	5340	CodeMeter Runtime Server	WIBU-SYSTEMS AG
  svchost.exe		1.348 K	5.368 K	5384	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		2.116 K	8.608 K	5548	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		3.488 K	11.888 K	5844	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		1.804 K	7.012 K	6164	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		11.504 K	24.672 K	6916	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe	< 0.01	5.776 K	19.924 K	6948	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		3.548 K	14.384 K	7100	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		2.892 K	12.304 K	7396	Hostproces voor Windows-services	Microsoft Corporation
  SearchIndexer.exe	0.01	48.744 K	66.888 K	8676	Indexeerfunctie van Microsoft Windows Search	Microsoft Corporation
   SearchProtocolHost.exe		1.824 K	7.792 K	14888		
   SearchFilterHost.exe		1.408 K	6.152 K	700		
  svchost.exe		4.520 K	20.724 K	8900	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		12.672 K	24.216 K	9684	Hostproces voor Windows-services	Microsoft Corporation
  iPodService.exe	0.02	2.336 K	8.332 K	8556	iPodService Module (64-bit)	Apple Inc.
  svchost.exe		4.028 K	9.348 K	10560	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		2.424 K	8.420 K	10892	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		2.588 K	10.348 K	7996	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		1.704 K	6.924 K	7884	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		7.620 K	27.152 K	9488	Hostproces voor Windows-services	Microsoft Corporation
  SgrmBroker.exe		2.860 K	4.924 K	11244	System Guard Runtime Monitor Broker-service	Microsoft Corporation
  svchost.exe		2.616 K	9.896 K	7460	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		1.792 K	8.104 K	1112	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		3.064 K	11.152 K	8796	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		6.308 K	10.072 K	6020	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		1.824 K	6.684 K	11856	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		2.236 K	8.912 K	13208	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		2.284 K	6.932 K	8812	Hostproces voor Windows-services	Microsoft Corporation
  svchost.exe		2.088 K	7.548 K	12120	Hostproces voor Windows-services	Microsoft Corporation
 lsass.exe	< 0.01	8.668 K	19.880 K	744	Local Security Authority Process	Microsoft Corporation
 fontdrvhost.exe		3.516 K	7.028 K	872		
csrss.exe	0.61	2.552 K	5.980 K	680		
winlogon.exe		2.340 K	10.508 K	444		
 fontdrvhost.exe		5.188 K	13.664 K	968		
 dwm.exe	1.86	77.640 K	104.524 K	1068		
explorer.exe	0.16	57.748 K	135.656 K	3996	Windows Verkenner	Microsoft Corporation
 MSASCuiL.exe		1.996 K	9.152 K	10124	Windows Defender notification icon	Microsoft Corporation
 iTunesHelper.exe	< 0.01	4.324 K	15.348 K	9236	iTunesHelper	Apple Inc.
 cnwida.exe	< 0.01	3.252 K	9.884 K	6492	imagePROGRAF Status Monitor for x64 Edition	CANON INC.
 E_IATILRE.EXE		2.868 K	9.700 K	5484	EPSON Status Monitor 3	SEIKO EPSON CORPORATION
 CodeMeterCC.exe	0.05	7.104 K	19.588 K	8624	CodeMeter Control Center	WIBU-SYSTEMS AG
 MEGAsync.exe		69.060 K	59.544 K	9472	MEGAsync	Mega Limited
 EXCEL.EXE		48.908 K	90.688 K	8300	Microsoft Excel	Microsoft Corporation
 OUTLOOK.EXE	0.04	83.532 K	174.960 K	9756	Microsoft Outlook	Microsoft Corporation
 hotshots.exe		22.744 K	54.556 K	11764		
 procexp64.exe	3.50	21.416 K	38.444 K	7364	Sysinternals Process Explorer	Sysinternals - www.sysinternals.com
 launch.exe		6.972 K	14.456 K	9920		
ApntEx.exe		1.852 K	7.032 K	7156	Alps Pointing-device Driver for Windows	Alps Electric Co., Ltd.
 conhost.exe		5.612 K	10.704 K	6676	Consolevensterhost	Microsoft Corporation
CCleaner64.exe	0.03	9.072 K	13.680 K	9052		
Dropbox.exe	0.15	135.792 K	169.444 K	8608	Dropbox	Dropbox, Inc.
 Dropbox.exe		1.908 K	8.272 K	8508	Dropbox	Dropbox, Inc.
 Dropbox.exe		1.396 K	7.300 K	7756	Dropbox	Dropbox, Inc.
 QtWebEngineProcess.exe		31.448 K	45.036 K	2944	C++ application development framework.	The Qt Company Ltd
Lightshot.exe		13.756 K	13.508 K	10316	Lightshot	Skillbrains
PromoUtil.exe		8.328 K	22.500 K	9772		
 cefutil.exe	0.02	11.264 K	45.612 K	3952		
  cefutil.exe	0.17	28.088 K	39.192 K	12156		
  cefutil.exe	0.18	27.984 K	40.980 K	7608		
opera.exe	0.03	119.004 K	176.216 K	3764	Opera Internet Browser	Opera Software
 opera_crashreporter.exe		6.056 K	10.140 K	8788	Opera crash-reporter	Opera Software
 opera.exe		105.292 K	121.912 K	5868	Opera Internet Browser	Opera Software
 opera.exe		37.980 K	52.972 K	3720	Opera Internet Browser	Opera Software
 opera.exe	0.03	50.472 K	72.884 K	4800	Opera Internet Browser	Opera Software
 opera.exe		31.796 K	45.124 K	4932	Opera Internet Browser	Opera Software
 opera.exe		34.516 K	50.108 K	1820	Opera Internet Browser	Opera Software
 opera.exe		34.644 K	48.264 K	3216	Opera Internet Browser	Opera Software
 opera.exe		91.312 K	119.624 K	6232	Opera Internet Browser	Opera Software
 opera.exe	0.07	81.404 K	108.356 K	4252	Opera Internet Browser	Opera Software
 opera.exe	0.02	162.056 K	188.364 K	9040	Opera Internet Browser	Opera Software
 opera.exe	0.04	68.676 K	97.804 K	2712	Opera Internet Browser	Opera Software
 opera.exe	2.15	94.708 K	121.476 K	5916	Opera Internet Browser	Opera Software
 opera.exe		12.608 K	17.748 K	15336	Opera Internet Browser	Opera Software
 opera.exe		12.572 K	17.744 K	15328	Opera Internet Browser	Opera Software

Process: launch.exe Pid: 9920

Name	Description	Company Name	Path
_heapq-cpython-36m.dll			C:\Program Files\OpenShot Video Editor\lib\python3.6\_heapq-cpython-36m.dll
_struct-cpython-36m.dll			C:\Program Files\OpenShot Video Editor\lib\python3.6\_struct-cpython-36m.dll
advapi32.dll	Geavanceerde Windows 32 basis-API	Microsoft Corporation	C:\Windows\System32\advapi32.dll
bcrypt.dll	Windows-bibliotheek van cryptografische primitieven	Microsoft Corporation	C:\Windows\System32\bcrypt.dll
bcryptprimitives.dll	Windows Cryptographic Primitives Library	Microsoft Corporation	C:\Windows\System32\bcryptprimitives.dll
combase.dll	Microsoft COM voor Windows	Microsoft Corporation	C:\Windows\System32\combase.dll
comctl32.dll	Bibliotheek met elementen voor gebruikerservaring	Microsoft Corporation	C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.17134.407_none_fb449d63306391e9\comctl32.dll
CoreMessaging.dll	Microsoft CoreMessaging Dll	Microsoft Corporation	C:\Windows\System32\CoreMessaging.dll
CoreUIComponents.dll	Microsoft Core UI Components Dll	Microsoft Corporation	C:\Windows\System32\CoreUIComponents.dll
cryptbase.dll	Base cryptographic API DLL	Microsoft Corporation	C:\Windows\System32\cryptbase.dll
cryptsp.dll	Cryptographic Service Provider API	Microsoft Corporation	C:\Windows\System32\cryptsp.dll
dwmapi.dll	API voor Beheer van bureaubladvensters van Microsoft	Microsoft Corporation	C:\Windows\System32\dwmapi.dll
gdi32.dll	GDI Client DLL	Microsoft Corporation	C:\Windows\System32\gdi32.dll
gdi32full.dll	GDI Client DLL	Microsoft Corporation	C:\Windows\System32\gdi32full.dll
imageres.dll	Windows Image Resource	Microsoft Corporation	C:\Windows\System32\imageres.dll
imageres.dll.mui	Windows Image Resource	Microsoft Corporation	C:\Windows\System32\en-US\imageres.dll.mui
imm32.dll	Multi-User Windows IMM32 API Client DLL	Microsoft Corporation	C:\Windows\System32\imm32.dll
kernel.appcore.dll	AppModel API Host	Microsoft Corporation	C:\Windows\System32\kernel.appcore.dll
kernel32.dll	DLL-bestand voor Windows NT BASE API-client	Microsoft Corporation	C:\Windows\System32\kernel32.dll
kernel32.dll.mui	DLL-bestand voor Windows NT BASE API-client	Microsoft Corporation	C:\Windows\SysWOW64\nl-NL\kernel32.dll.mui
KernelBase.dll	DLL-bestand voor Windows NT BASE API-client	Microsoft Corporation	C:\Windows\System32\KernelBase.dll
KernelBase.dll.mui	DLL-bestand voor Windows NT BASE API-client	Microsoft Corporation	C:\Program Files\WindowsApps\Microsoft.LanguageExperiencePacknl-nl_17134.13.16.0_neutral__8wekyb3d8bbwe\Windows\System32\nl-NL\KernelBase.dll.mui
launch.exe			C:\Program Files\OpenShot Video Editor\launch.exe
libpython3.6m.dll			C:\Program Files\OpenShot Video Editor\libpython3.6m.dll
libwinpthread-1.dll	POSIX WinThreads for Windows	MingW-W64 Project. All rights reserved.	C:\Program Files\OpenShot Video Editor\libwinpthread-1.dll
locale.nls			C:\Windows\System32\locale.nls
msctf.dll	DLL-bestand voor MSCTF-server	Microsoft Corporation	C:\Windows\System32\msctf.dll
msvcp_win.dll	Microsoft® C Runtime Library	Microsoft Corporation	C:\Windows\System32\msvcp_win.dll
msvcrt.dll	Windows NT CRT DLL	Microsoft Corporation	C:\Windows\System32\msvcrt.dll
ntdll.dll	DLL-bestand voor NT-laag	Microsoft Corporation	C:\Windows\System32\ntdll.dll
ntmarta.dll	Windows NT MARTA-provider	Microsoft Corporation	C:\Windows\System32\ntmarta.dll
oleaut32.dll	OLEAUT32.DLL	Microsoft Corporation	C:\Windows\System32\oleaut32.dll
rpcrt4.dll	Runtime voor RPC (Remote Procedure Call)	Microsoft Corporation	C:\Windows\System32\rpcrt4.dll
rsaenh.dll	Microsoft Enhanced Cryptographic Provider	Microsoft Corporation	C:\Windows\System32\rsaenh.dll
sechost.dll	Host for SCM/SDDL/LSA Lookup APIs	Microsoft Corporation	C:\Windows\System32\sechost.dll
SHCore.dll	SHCORE	Microsoft Corporation	C:\Windows\System32\SHCore.dll
shlwapi.dll	Shell lichtgewicht hulpprogrammabibliotheek	Microsoft Corporation	C:\Windows\System32\shlwapi.dll
SortDefault.nls			C:\Windows\Globalization\Sorting\SortDefault.nls
StaticCache.dat			C:\Windows\Fonts\StaticCache.dat
TextInputFramework.dll	"TextInputFramework.DYNLINK"	Microsoft Corporation	C:\Windows\System32\TextInputFramework.dll
ucrtbase.dll	Microsoft® C Runtime Library	Microsoft Corporation	C:\Windows\System32\ucrtbase.dll
user32.dll	DLL-bestand voor Windows USER API-client (meerdere gebruikers)	Microsoft Corporation	C:\Windows\System32\user32.dll
uxtheme.dll	DLL-bestand Microsoft UxTheme	Microsoft Corporation	C:\Windows\System32\uxtheme.dll
version.dll	Version Checking and File Installation Libraries	Microsoft Corporation	C:\Windows\System32\version.dll
win32u.dll	Win32u	Microsoft Corporation	C:\Windows\System32\win32u.dll
WinTypes.dll	DLL Windows-basistypen	Microsoft Corporation	C:\Windows\System32\WinTypes.dll
ws2_32.dll	Windows Socket 2.0 32-bits DLL-bestand	Microsoft Corporation	C:\Windows\System32\ws2_32.dll
zlib1.dll			C:\Program Files\OpenShot Video Editor\zlib1.dll
zlib-cpython-36m.dll			C:\Program Files\OpenShot Video Editor\lib\python3.6\zlib-cpython-36m.dll

**Comment by bartschoneveld** [comment]
Tnkx for looping in to it. I’m now using Open Shot in Virtual Box, so iT works for now. I wait for the next update....
Thans Alain for the time you’ve put in to it.

Kind Renards,
Bart
