### ISSUE TITLE
segmentation fault 2.4.3

### ISSUE THREAD

**Issue by ar-g** [OpenShot/openshot-qt#2389]
**Describe the bug**
Running from terminal gives:
```
openshot-qt 
Compiled translation resources missing!
Loading translations from: /usr/lib/python3/dist-packages/openshot_qt/language
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
[1]    11884 segmentation fault (core dumped)  openshot-qt
erminal gives
```
**System Details (please complete the following information):**
Ubuntu 18.04

**Comment by peanutbutterandcrackers** [comment]
This most certainly is strange. I am using OpenShot from PPA using Linux Mint 19 which is based on Ubuntu 18.04...

@ferdnyc - Perhaps this too, sir, might be of interest to you?

**Comment by ferdnyc** [comment]
That _sounds_ like it might be a `libopenshot` version mismatch. @ar-g can you try the [2.4.3 AppImage](https://github.com/OpenShot/openshot-qt/releases/download/v2.4.3/OpenShot-v2.4.3-x86_64.AppImage) and see if that works for you?

If so, it sounds like a packaging/installation problem.

**Comment by speedytechdev** [comment]
@ar-g Can you let us know if this fixed the issue, please. So we know whether or not to close this issue.

**Comment by ar-g** [comment]
Yes, AppImage works, but it crashes way to often in the middle of export. It also crashes when I change from laptop screen to the external screen.

**Comment by speedytechdev** [comment]
Ok, sorry that you are still having issues. Hopefully, @ferdnyc can help you.
