### ISSUE TITLE
you put QT_PLUGIN_PATH while using binary download in which problematic for people dev

### ISSUE THREAD

**Issue by ghost** [OpenShot/openshot-qt#239]
Thanks for binary download release. But please don't put QT_PLUGIN_PATH in installer because this would make people Qt c++ run into problems. qtbase source build in c++ is very sensitve towards any prefix QT_\*  in path environment, and I did relized that because I was the one. My Qt Creator and other qt c++ apps strangely stop working because of this, after I build qtbase source with QT_PLUGIN_PATH which you had set.

**Comment by DylanC** [comment]
@ghost - Thanks for the feedback. We will keep this in mind.
