### ISSUE TITLE
Problems with exporting video in different profile than originally set up.

### ISSUE THREAD

**Issue by AuneK** [OpenShot/openshot-qt#2390]
**Describe the bug**
Imported video in default profile.
Cut out segments of the video, and increased the playback speed of those segments to 4x speed
In the exported video, the part of the vide that was to be sped up was shown as a still picture from somewhere else in the video.

**System Details (please complete the following information):**
 - Operating System / Distro: Win 10 Pro 1803
 - OpenShot Version 2.4.3

**To Reproduce**
1. I recorded a one minute video of a digital clock counting from 20:40:00 to 20:41:00.
2. Start a new project in OpenShot with default profile (720p, 30fps), import video form step 1.
3. Cut the video at 20:40:15 and 20:40:45. Increase the playback speed for the middle videosegment to 4x speed
4. Export the video in different profiles to see the behavior.

For me the following profiles was ok:
720p_30fps
1080p_30fps
2160p_30fps

In these cases, the clock played at normal speed up to 20:40:15, then continued at increased speed to 20:40:45, and then again played at normal speed until the end of the video

I had problems with the following profiles:
720p_60fps
1080p_60fps
2160p_60fps

In these cases, the clock played at normal speed up to 20:40:15, then showed a still picture of 20:40:22, until it switched to 20:40:45 and played at normal speed until the end of the video.

I also restarted OpenShot, set the profile to 720p, 60fps, and imported the original video, and exported video to 720p_30fps and 720p_60 fps. In this case the 60fps video was as expected, but the 30fps video played the first part as expected, then showed a still picture of 20:40:30, and then played the last segment from 20:40:45 to the end as expected.

**Expected behavior**
I would all exported videos to play the video segment from 20:40:15 to 20:40:45 at 4x speed. Not shot a still picture of 20:40:22 or 20:40:30.

**Screenshots**
I have some ~80mb of videos showing this. Please contact me if these are of interest.

**Logs**
N/A

**Additional context**

**Comment by peanutbutterandcrackers** [comment]
That is a limitation of OpenShot. You can change the dimensions but the fps has to be the same. Always. There might be ways to work-around them but they aren't currently being discussed now as there are a pile of other things that need to be dealt with. So, I'm afraid this won't be the priority right now. [And to fix this issue, OpenShot would require a huge overhaul, if I am not mistaken. On a bright side, rudimentary work had already started in this regards but has been stalled for almost a year now.]

If 60fps is what you absolutely want, you could always use [ffmpeg](http://ffmpeg.org/) to convert the output from OpenShot. Off the top of my head, it would be something along the lines of:
`ffmpeg -i input_30_fps_video.mp4 -r 60 output_60_fps_video.mp4`
But one might want to set various other parameters as well.

Hope that helps.

Closing this one for now. Please do feel free to make further comments/open this issue if you see it necessary.
