### ISSUE TITLE
Is openshot optimized for OpenCL on amd graphic cards

### ISSUE THREAD

**Issue by bobcrikey** [OpenShot/openshot-qt#2392]
hello everyone, 
 @DylanC 
 
          How much memory is used for each track used and if chromakey is used?
 and is OpenCL used at all for any calculations/rendering and if so, is openshot
 optimized for amd Rxs560 and AMD Vega graphics cards 

As i do notice it can take up to one minute before openshot actually starts. and i use
a ryzen computer with 16 gigs of ram and fast 860 samsung M.2 drivr 

thanks 
bob

**Comment by DylanC** [comment]
@bobcrikey - I think not yet until the hardware acceleration development is complete.

**Comment by DylanC** [comment]
@bobcrikey - I have a list of stuff I'd like us to focus on and Chroma key is on it:
https://gist.github.com/DylanC/73ecfa2f6f99fd7828604e4f8b65bb3f

You will need to wait a while for hardware accel to arrive. Same with Chroma key but I hope we get around to it soon.
