### ISSUE TITLE
Exact coincide of duration

### ISSUE THREAD

**Issue by musicfreund** [OpenShot/openshot-qt#2393]
I have made 2 tracks: one of music examples and one of pictures. How can I adjust, that the pictures exactly coincide in time with the examples of music on the second?

**Comment by peanutbutterandcrackers** [comment]
Perhaps this guide can be of some help: https://gist.github.com/peanutbutterandcrackers/f0f666243133e0ed25abbc12a4ba23d7?

Also, there's a nudge feature (using shift + arrowed keys) that move clips by half-a-frame. Perhaps that could be of some massive help.

Hope that helps!
