### ISSUE TITLE
How do you change the pitch of the audio?

### ISSUE THREAD

**Issue by DandyDude** [OpenShot/openshot-qt#2395]
Whenever I change the speed of a clip, the pitch of the audio changes with it. How do I change the pitch of the audio?

**Comment by peanutbutterandcrackers** [comment]
I'm afraid we do not have that feature yet. As far as I understand it, even VLC and mplayer and all the other media players do the same thing. I think I have heard of a fork of mplayer that keeps the pitch the same, but I can't remember for sure.

Perhaps you could try using [Audacity](https://www.audacityteam.org/) to do what you are trying to accomplish?

**Comment by MunaAlaneme** [comment]
USE NUMPY RIGHT NOW!!!!!!!!!!!!!

**Comment by fazzaan** [comment]
why is this issue closed

**Comment by DylanC** [comment]
@fazzaan I haven't looked at this in some time but it looks like a question ticket was posted and answered by the dev team.

If you feel this is a capability you would like you can always open a feature request ticket.
