### ISSUE TITLE
Cannot import any video files on OS-X 10.11.6 using Openshot 2.4.3

### ISSUE THREAD

**Issue by iangilmour** [OpenShot/openshot-qt#2398]
Openshot crashes on any video file import attempt.

See attached log for further details.

[openshot-run.txt](https://github.com/OpenShot/openshot-qt/files/2613165/openshot-run.txt)

**Comment by peanutbutterandcrackers** [comment]
Could you please try [the latest daily build](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914) and see if that works any better for you, good sir? Thank you.

**Comment by iangilmour** [comment]
same problem with OpenShot-v2.4.3-dev1-1543262951-31e9e7b6-750d7a3f-x86_64.dmg.

**Comment by OneCosmicGuy** [comment]
For what it's worth, I'm having the same problem with the same application version being used on the same OS version.
