### ISSUE TITLE
OpenShot AppImage File Has Never Successfully Executed in OpenSUSE Tumbleweed Yet

### ISSUE THREAD

**Issue by ejmarkow** [OpenShot/openshot-qt#240]
I'm always getting the following error and this is becoming very annoying. When will it finally run properly? Waiting for a long time now.

ejm@galicia:~/temp1> ./OpenShot-v2.0.7-27-g126c750-47-535-x86_64.AppImage
/tmp/.mount_NvPt2R/usr/bin/openshot-qt.wrapper
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Loaded modules from current directory: /tmp/.mount_NvPt2R/usr/bin
Segmentation fault (core dumped)

**Comment by anewuser** [comment]
I can't use it either on KDE Neon (which runs the Krita 3.0 AppImage normally):

    /tmp/.mount_n96Ufu/usr/bin/openshot-qt.wrapper
    desktop-file-validate is missing. Skipping ./bin//openshot-qt.wrapper.
    Loaded modules from current directory: /tmp/.mount_n96Ufu/usr/bin

**Comment by jonoomph** [comment]
Lots of improvements have been made to the AppImage, and many bugs fixed. Please try again with our latest daily build, and reopen this ticket if the problem persists. Fingers crossed the newest version works great for you. 

Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot.
