### ISSUE TITLE
Cut video remaining

### ISSUE THREAD

**Issue by mick47** [OpenShot/openshot-qt#2403]
Gday
i slice the video or razor the video .Delete the unwanted area and then pull the RH video up to rejoin the LH video .Every time the unwanted video is back!! What am i doing wrong .I can delete the video but as soon as i bring the clips together the unwanted footage is back.
Pls help
mick

**Comment by peanutbutterandcrackers** [comment]
It would have helped us if you'd provided us more details. For starters, I suggest that you make sure that you are using the latest version of OpenShot (2.4.3, as of this day). Second, if you are not sure you did it right, please watch [this video to learn how to cut and split in OpenShot (using different techniques)](https://www.youtube.com/watch?v=BQS2tmgD_Rk&index=6&list=PLymupH2aoNQNezYzv2lhSwvoyZgLp1Q0T&t=0s). If even that doesn't work out, please do provide us more details like what kind of video it is (.mp4? .mkv? .flv?), and other details about your system.

Hope that helps!

**Comment by mick47** [comment]
Thanks will use the first cutting process on the video.
These are old DVD Recorder files.
Peanutbutter is there an area on openshot to minimise distortion.?
Have the latest version.
Ta Mick

**Comment by peanutbutterandcrackers** [comment]
Sorry, OpenShot does not have that feature. However, I suggest you use something like [HandBrake](https://github.com/peanutbutterandcrackers/meet-tux) to rip the DVDs. HandBrake is designed for that, and should do the ripping really well, thus giving you less distortions, hopefully.

Please do not forget to close this issue if this has been resolved. Thank you!

**Comment by mick47** [comment]
thanks
