### ISSUE TITLE
How do I magnify a part of the clip

### ISSUE THREAD

**Issue by ttigvbringj** [OpenShot/openshot-qt#2405]
**My Question:**

**System Details**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**Screenshots**

**Comment by speedytechdev** [comment]
@ttigvbringj Are you trying to zoom into the timeline. If so you can click on the plus or minimize button.
![image](https://user-images.githubusercontent.com/40452959/49184394-1c601a80-f3c4-11e8-9cab-689669ab31e8.png)

**Comment by speedytechdev** [comment]
Please let us know if this helped or are we not getting your question?

**Comment by peanutbutterandcrackers** [comment]
Or, if you want to zoom in to part of a clip, you should probably first read [this guide](https://gist.github.com/peanutbutterandcrackers/f0f666243133e0ed25abbc12a4ba23d7) and then proceed to keyframe the `scale x` and `scale y` properties of your clip. Hope that helps!

Closing as answered.
