### ISSUE TITLE
Frequent crashes on Windows.

### ISSUE THREAD

**Issue by NeonJackal** [OpenShot/openshot-qt#241]
Tried using on a Windows 10 and Windows 8 PC, crashes during playback or editing quite frequently.

**Comment by goober889** [comment]
Experiencing same issue on Ubuntu 16.04 Xenial

**Comment by WiseWoodrow** [comment]
It's very disappointing.  This seems like a good video editor, but it crashes -so- much that I can't even identify a source.  Random actions, often to do with playing the video, crash the editor.  I have no idea why there aren't any open source video editors.  There are so many open source programs for everything except video editing - all of the ones for video editing suck.

**Comment by goober889** [comment]
Well, there's Kdenlive, but that's only available for Linux and Mac.

**Comment by jreynojustin** [comment]
There's some other issues more informative with crash logs. Please provide logs and check out our latest builds. We've made a lot of tweaks since July!
