### ISSUE TITLE
Drop area & visual area disappeared after pressing a button?

### ISSUE THREAD

**Issue by ValoxGaming** [OpenShot/openshot-qt#2411]
**My Question:**
I pressed a button next to where it showed what it looks like, and the whole area disappeared. I have no idea how to get it back and now I can't drop any files in, or see the images going along w/ music.

**System Details**
 - Operating System / Distro: Windows 10

**Screenshots**
![image](https://user-images.githubusercontent.com/33590780/49257064-14719c00-f3ff-11e8-90c5-56dc1b1fb4b6.png)
(It used to be at top, but under the tool bar)

**Comment by torpedoboy49** [comment]
view > views > show all

**Comment by speedytechdev** [comment]
@ValoxGaming Did this fix your issue. Please let us know so we know whether or not to close the issue.

**Comment by speedytechdev** [comment]
No problem glad to help.
