### ISSUE TITLE
Help video export craches

### ISSUE THREAD

**Issue by ashjojo90** [OpenShot/openshot-qt#2412]
**My Question:**

< I need help and I am new to this so please bare with me, I am having a hard time exporting my video so that I can access it as a file on my computer and upload it. Every time I export it gets to about 95% and shuts off. As I have been trying to find a solution I have changed the target, profile, and quality as people suggest after looking for answer online. Nothing is working, I am disappointed as I have spent a few hours putting together this video and am looking for some guidance before I rule this as a complete waste of time. Thanks in advance for helping.>

**System Details**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**Screenshots**

**Comment by speedytechdev** [comment]
Hi @ashjojo90 Hopefully we can help you. It would be a pain if you wasted all that time. I need to know a few things from you please. 

- What version of Openshot are you using

- What is the format of the file you are editing/used in your film

- What is the format you are exporting at 

Please let me know if you get stuck or need help.

**Comment by ashjojo90** [comment]
The files I am using are coming from our go pro and the audio is from purchased song off iTunes, I’ve tried exporting in many different formats high med and low quality... also in the mp4 h.264 and mp4 mpeg4... target in all formats I am not sure what version we downloaded openshot at the beginning of the year I am looking to see if maybe I need to update it now

**Comment by ashjojo90** [comment]
I tried downloading it but it wouldn’t let me 😩

**Comment by speedytechdev** [comment]
Does it say why?

**Comment by ashjojo90** [comment]
Yes one sec let me do again

**Comment by ashjojo90** [comment]
Ok it worked with chrome not explorer trying to export video now

**Comment by speedytechdev** [comment]
ok

**Comment by ashjojo90** [comment]
It worked I exported it thank you!

**Comment by speedytechdev** [comment]
No problem I am going to close this issue ok

**Comment by speedytechdev** [comment]
@DylanC or @peanutbutterandcrackers could you close this please

**Comment by speedytechdev** [comment]
close
