### ISSUE TITLE
scroll bar shrinking

### ISSUE THREAD

**Issue by podunkly** [OpenShot/openshot-qt#2413]
**Describe the bug**

**System Details (please complete the following information):**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**

**Comment by speedytechdev** [comment]
Hi @podunkly could you please fill out the information you have posted or we have no idea how to help you thanks.

**Comment by speedytechdev** [comment]
@podunkly If you don't answer soon I have to close this issue sorry.

**Comment by podunkly** [comment]
you can close this, I ended up getting kind of what I needed.  The main
issue that I was going to open the ticket for was for the scroll bar on the
edit timeline. it just kept shrinking and there didn't seem to be a way to
set the over all amount of time on the timeline to something that made the
scroll bar useable.  I'd have to zoom way in, then the scrolling would go
crazy.

**Comment by speedytechdev** [comment]
@podunkly I think put an idea request in for "set the overall amount of time on the timeline". I will close this anyway.
