### ISSUE TITLE
Cannot import any video files on Windows 10 using Openshot 2.4.3 

### ISSUE THREAD

**Issue by jmrsuarez** [OpenShot/openshot-qt#2416]
**Describe the bug**
When i try to import a mp4 video file, the application do not responds. 

**System Details (please complete the following information):**
Windows 10 - OpenShot Version 2.4.3

**To Reproduce**
1. Open the application
2. Try to import a mp4 video file

**Expected behavior**
that the video clips opens 

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

It is a new windows 10 machine without any other software. i also have tryed the daily builds, and the 32 bit version.

**Comment by speedytechdev** [comment]
Hi @jmrsuarez that is odd since I use a windows 10 pc and on 2.4.3. Could you send crash logs please and your pc specs. Thanks

**Comment by jmrsuarez** [comment]
Hardware Sempron, 2.80 Ghz, 64 bits, AMD, 10 GB, Open shoot dont crash, it only get stalled on a gray window and his title change to a non responding state. 

![openshot](https://user-images.githubusercontent.com/13615559/49329467-de3e3480-f544-11e8-9fb6-30314deeb8fa.jpg)

**Comment by speedytechdev** [comment]
Ok so if the issue did not change with the different versions of Openshot then we know that either Openshot does not support/like your system or your system does not like Openshot. @ferdnyc Could you help with this, please. Thanks

**Comment by ferdnyc** [comment]
Even if it doesn't crash, logs would be helpful. See the [CONTRIBUTING.md](https://github.com/OpenShot/openshot-qt/blob/develop/CONTRIBUTING.md) file for instructions on how to collect logs. Then just drag-and-drop the `openshot-qt.log` and `libopenshot.log` files into the Issue comment editor to upload and post them.

**Comment by 22catcher** [comment]
Hello, I have the same issue. I click the plus sign, choose a 9MB mp4 video, but nothing happens. Or better to say, it does something, because it thinks for a few seconds and than I can undo it, but nothing appears in the program. Tried it with 5MB video, same. Exported 3 seconds into mp4, exported without error, but it's a 0 second black video without sound. I have the 64 bits version for my 64 bits 1909 Windows 10 PC.
