### ISSUE TITLE
Can't import a 1.4.3 project to Beta 2.0.7

### ISSUE THREAD

**Issue by J-e-f-f-A** [OpenShot/openshot-qt#242]
Upon attempting to open a 1.4.3 project, I receive the error: 
my_project_name.osp: No module named 'classes.project'

Ubuntu Linux
![no_module_named](https://cloud.githubusercontent.com/assets/308891/16711185/b8f5434c-461b-11e6-8a0b-89df45ac6e3b.png)

[openshot-qt.stderr.txt](https://github.com/OpenShot/openshot-qt/files/355806/openshot-qt.stderr.txt)
[openshot-qt.stdout.txt](https://github.com/OpenShot/openshot-qt/files/355807/openshot-qt.stdout.txt)

**Comment by pols12** [comment]
I encounter the same issue. I worked with current Debian testing repos version (1.4.3), and I am just trying opening my project with Fedora RPMfusion version (2.0.7):

> Failed to load project file /home/user/project.osp: No module named 'classes.project'

Seems to be similar to #85 (where this bug has been reporting several times since the issue has been closed).

**Comment by jreynojustin** [comment]
The OSP file structure has changed drastically in Version 2.0. This is not something we are actively doing as per @jonoomph comment in issue #85.

**Comment by pols12** [comment]
@jreynojustin So this issue will never be fixed? Or we should reopen #85?

**Comment by jreynojustin** [comment]
There was another duplicate in which I can't recall the number that was also closed. We're discussing internally whether or not to address it. I think there is one collaborator who may also contribute a pull request implementing a conversion solution.

I'll let you know what happens!
