### ISSUE TITLE
Imported video stalls 

### ISSUE THREAD

**Issue by JVang24** [OpenShot/openshot-qt#2422]
**My Question:**
Imported videos stall each time I play it in the "video preview" section. It play for a few sec then freezes for a few. The same thing happened when I installed Shotcut. Wasn't sure so I uninstalled Shotcut thinking it was the program. But I'm getting the same issue with Openshot. I'm totally new to this. Please help! Just wanna edit some vlogs and upload on YouTube. TIA! 

**System Details**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**Screenshots**

**Comment by speedytechdev** [comment]
Hi, @JVang24 Hopefully we can help. I need to know a few things to help you and get you on your way.

-  What version of Openshot are you using
-  What is your pc specs
-  Is it all the files you use all specific ones like mp4

**Comment by PASTJL** [comment]
Can you play the imported clip with VLC ? to verify if it is corrupted....

**Comment by JVang24** [comment]
Yes, plays perfectly fine on VLC

**Comment by JVang24** [comment]
Hey guys, hopefully someone can give me an answer. I'm sorry if I didn't provide the correct information. I suck at computers.

**Comment by DylanC** [comment]
@JVang24 - Since it performs poor in other video editors I would have a concern about your PC spec or maybe your graphics drivers are just not setup right. Can you update your graphics drivers on it at all?

**Comment by JVang24** [comment]
Found my specs!

**Comment by JVang24** [comment]
Please let me know what I need to do next. I have a feeling that my laptop
although brand new is not the issue. Its probably because my laptop is just
very basic & is not compatible with the program.
