### ISSUE TITLE
Split clip does not affect the preview window

### ISSUE THREAD

**Issue by sarwil** [OpenShot/openshot-qt#2423]
I drag mp4 files into the `Project files' window. Following a tutorial, I right click on a file and select "split clip". An extra window appears as expected, where I select the `start' and `end' of the shortened clip I want and then hit `create' (all as in the tutorial). But whatever I try, the `end' selection never works! In other words, when I preview the newly created clip, it does start at the point I selected, but then runs till the end of the original movie. The same is true when I first export the new clip and then view it. 
I know that there are other ways of splitting, eg by using the razor tool in a time line, but that is not handy at all if you want to cut short fragments out of a long video file.

**System Details (please complete the following information):**
 - Operating System: Windows 10
 - OpenShot Version  2.4.13

**Comment by speedytechdev** [comment]
Hi, @sarwil I just tested this. So yes it does not stop were it is meant to in the preview window but it works fine in the timeline and when exported. So I will mark this a bug since it does not work on the preview window.
