### ISSUE TITLE
Openshot Hangs when importing mp4 video in windows 10

### ISSUE THREAD

**Issue by FrankLoB** [OpenShot/openshot-qt#2427]
openshot works great on .mov files, but now i have a new camera and it only generates mp4, when i import the mp4 openshot stops responding for eternity. I tried this with multiple computers and 3 other running windows 10 and 1 windows 7, no luck and i tried with a different mp4 file, still no success, so if anyone can help me with this issue it would be much appreciated thanks.

**Comment by peanutbutterandcrackers** [comment]
Is it 4k 60fps footage, by any chance?

**Comment by FrankLoB** [comment]
No 1080p 30fps


Frank Lo Bianco
Administrateur Réseau - Technicien Informatique
FLoBianco@uniger<mailto:flobianco@unigertec.com>pro.com<http://pro.com>
3980 Boulevard Leman, Laval (Québec) H7E 1A1<x-apple-data-detectors://7/2>
Tel: 450-902-3142 ext : 420<tel:450-902-3142;420>
Fax: 450-682-2082<tel:450-682-2082>
Cell: 514-213-0303<tel:514-213-0303>
http://www.unigertec.com<http://www.unigertec.com/>
Ce courriel et ses pièces jointes peuvent contenir de l'information privilégiée et confidentielle. Si vous n'êtes pas le destinataire, veuillez en aviser immédiatement l'expéditeur, effacer ce courriel et en détruire toute copie. Toute diffusion ou utilisation de cette information par une personne autre que le destinataire est interdite et pourrait être illégale.
This email and any attachments may contain privileged and confidential information. If you are not the intended recipient, please notify the sender immediately, delete this email and destroy any copies. Any dissemination or use of this information by a person other than the intended recipient is unauthorized and may be illegal.
[enviro]


On Dec 4, 2018, at 10:53 PM, peanutbutterandcrackers <notifications@github.com<mailto:notifications@github.com>> wrote:


Is it 4k 60fps footage, by any chance?

**Comment by peanutbutterandcrackers** [comment]
Oh, I see.
For the time being, you could probably transcode the video using [HandBrake](https://handbrake.fr/) and then import it into OpenShot. We will try to get this sorted in the future releases.
Please do keep on loving and supporting OpenShot. Thank you.

**Comment by FrankLoB** [comment]
Do i transcode it to .mov format?


Frank Lo Bianco
Administrateur Réseau - Technicien Informatique
FLoBianco@uniger<mailto:flobianco@unigertec.com>pro.com<http://pro.com>
3980 Boulevard Leman, Laval (Québec) H7E 1A1<x-apple-data-detectors://7/2>
Tel: 450-902-3142 ext : 420<tel:450-902-3142;420>
Fax: 450-682-2082<tel:450-682-2082>
Cell: 514-213-0303<tel:514-213-0303>
http://www.unigertec.com<http://www.unigertec.com/>
Ce courriel et ses pièces jointes peuvent contenir de l'information privilégiée et confidentielle. Si vous n'êtes pas le destinataire, veuillez en aviser immédiatement l'expéditeur, effacer ce courriel et en détruire toute copie. Toute diffusion ou utilisation de cette information par une personne autre que le destinataire est interdite et pourrait être illégale.
This email and any attachments may contain privileged and confidential information. If you are not the intended recipient, please notify the sender immediately, delete this email and destroy any copies. Any dissemination or use of this information by a person other than the intended recipient is unauthorized and may be illegal.
[enviro]


On Dec 4, 2018, at 11:03 PM, peanutbutterandcrackers <notifications@github.com<mailto:notifications@github.com>> wrote:


Oh, I see.
For the time being, you could probably transcode the video using HandBrake<https://handbrake.fr/> and then import it into OpenShot. We will try to get this sorted in the future releases.
Please do keep on loving and supporting OpenShot. Thank you.

**Comment by peanutbutterandcrackers** [comment]
Yes, sir. That is what I think might work for you. Or, perhaps try a few different ones. `.mkv` is one that I like (it's Open).

**Comment by FrankLoB** [comment]
Thankyou so much for your help


Frank Lo Bianco
Administrateur Réseau - Technicien Informatique
FLoBianco@uniger<mailto:flobianco@unigertec.com>pro.com<http://pro.com>
3980 Boulevard Leman, Laval (Québec) H7E 1A1<x-apple-data-detectors://7/2>
Tel: 450-902-3142 ext : 420<tel:450-902-3142;420>
Fax: 450-682-2082<tel:450-682-2082>
Cell: 514-213-0303<tel:514-213-0303>
http://www.unigertec.com<http://www.unigertec.com/>
Ce courriel et ses pièces jointes peuvent contenir de l'information privilégiée et confidentielle. Si vous n'êtes pas le destinataire, veuillez en aviser immédiatement l'expéditeur, effacer ce courriel et en détruire toute copie. Toute diffusion ou utilisation de cette information par une personne autre que le destinataire est interdite et pourrait être illégale.
This email and any attachments may contain privileged and confidential information. If you are not the intended recipient, please notify the sender immediately, delete this email and destroy any copies. Any dissemination or use of this information by a person other than the intended recipient is unauthorized and may be illegal.
[enviro]


On Dec 4, 2018, at 11:06 PM, peanutbutterandcrackers <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, sir. That is what I think might work for you. Or, perhaps try a few different ones. .mkv is one that I like (it's Open).

**Comment by peanutbutterandcrackers** [comment]
You are most welcome.
