### ISSUE TITLE
Adjust volume on an audio file?

### ISSUE THREAD

**Issue by ugoboom** [OpenShot/openshot-qt#2428]
**Please fill out this template** 

**My Question:**
How do I adjust the volume of an audio file?

**System Details**
 - Operating System / Distro: [Windows 10]
 - OpenShot Version [2.4.3]

**Screenshots**

**Comment by peanutbutterandcrackers** [comment]
Or, you could also keyframe the volume property. Consult [this guide](https://gist.github.com/peanutbutterandcrackers/f0f666243133e0ed25abbc12a4ba23d7) to learn more about keyframes.

Closing as answered.
