### ISSUE TITLE
Cannot Export Video

### ISSUE THREAD

**Issue by JohnnyG2** [OpenShot/openshot-qt#2432]
A clear and concise description of what the bug is:

Choose "Export Video" and Get Error Message "could not open or write file"

**System Details (please complete the following information):**
 - Operating System Windows 10
 - OpenShot Version 2.4.3

**To Reproduce**
1. Go to 'FILE.'
2. Click on 'EXPORT VIDEO'
3. Scroll down to 'EXPORT VIDEO BUTTON ON POPUP'
4. See error "EXPORT ERROR"  Sorry, There was and error exporting your video: Could not open or write file.

**Expected behavior**
Expected to export video. Chose...all formats....MP4.... HDV 720 24p.....Quality High

**Screenshots**

**Logs**
ui_util:WARNING Icon theme media-playback-pause not found. Will use backup icon.
**Additional context**
Is there some other way to convert saved video file that is in .osp format to mp4?

**Comment by ctsdownloads** [comment]
Unreproducible, old version of OpenShot
