### ISSUE TITLE
openshot-2.4.3在预览视频时卡顿

### ISSUE THREAD

**Issue by Kmeyel** [OpenShot/openshot-qt#2433]
openshot-2.4.3在预览视频时卡顿

重新导入了工程文件预览视频 慢放，很慢的播放。类似减速播放

**Comment by nijiawen** [comment]
openshot-2.4.3 freezes when previewing video.

After reloading the project file, the preview is slow. It plays very slowly, as if in slow motion.

**Comment by SuslikV** [comment]
Sometimes after remuxing (to the same container) the files works better. You may give it a try. FFmpeg or other tools based on it (OBS Studio for example) can do multiplex of the media streams into new file format without quality loss.
