### ISSUE TITLE
Can I Use This Program To Produce Commercial Videos?

### ISSUE THREAD

**Issue by muhlisgursoy** [OpenShot/openshot-qt#2437]
Hello,

Short question; can I use this program to produce commercial videos? I'm working on photo and video stocks.

Thanks.

**Comment by speedytechdev** [comment]
@muhlisgursoy Of course, If you could can you give us credit since this is all free and open source. If your work is public please let us know and we would be happy to post it on the forums and maybe our social media. Hopefully, this helped. If you need anything else let me know.

**Comment by peanutbutterandcrackers** [comment]
Yes, while a credit/shoutout would be nice, it isn't required, in any way whatsoever. If you wanted, the license even allows you to create entirely new version of OpenShot called muhlishot or something, too. The only thing you have to make sure is that your code is released under the GPL. As for the program itself, you can use it to whatever you want to do. Here are the four freedoms that you have: ![Freedoms](https://www.openclipart.org/download/256647/1469656861.svg)

Just in case you run into some issues with OpenShot, you might want to look at [ShotCut](https://shotcut.org/) or [KdenLive](https://kdenlive.org/en/).

Hope that helps. 

Closing as answered.
