### ISSUE TITLE
Problem with attenuation of audio when exporting

### ISSUE THREAD

**Issue by XimoSancho** [OpenShot/openshot-qt#2438]
I'm running openshot under Windows10 (64 bits), v.2.4.3. Windows 10 is installed in Spanish, so that the software shows in Spanish
Everything works fine with the attenuation of the audio volume when previsualizing from inside the software. But when exporting the video (no matter the format), attenuation does not work.
Any help with that?

**Comment by InvaderKyn** [comment]
A greeting.
I also suffer the same problem and it is very exasperating. Will someone deign to answer us ...?

**Comment by InvaderKyn** [comment]
@speedytechdev @ferdnyc @peanutbutterandcrackers @...

**Comment by InvaderKyn** [comment]
Sorry for the insistence.

**Comment by speedytechdev** [comment]
@XimoSancho @InvaderKyn Sorry we just took some time off with family. I believe this has been fixed but I am not positive. @jonoomph

**Comment by peanutbutterandcrackers** [comment]
Does this mean that the volume fades out (or decreases) in the export?

I have run into a sound-related issue myself (with crackling sound); hopefully this one will be fixed in the future. As of now, I have kept my project files safe so that I can re-render them again when this is fixed.

I'm sorry, but I guess we'll just have to wait for now...

**Comment by InvaderKyn** [comment]
> @peanutbutterandcrackers / @speedytechdev 
It is as if "the attenuation" will not be exported in any way, although the program believes that it does.

I regret that my writing is not completely intelligible. I am only a Spanish speaker using the google translator service.

**Comment by Grimeton** [comment]
Greetings,

in my case, the fade out of the volume is much to early. It then sometimes comes back and fades out again till the video is over.

I tried all kinds of stuff, deleting the track, adding it again, adding the fade out manually and so on. Nothing is working.

Cu

**Comment by joanlofe** [comment]
@XimoSancho I also had this issue and it was solved by installing the latest daily build. To find it, click the button "Daily build" in the [downloads page](https://www.openshot.org/download/) of Openshot.

**Comment by speedytechdev** [comment]
Thanks for letting us know @joanlofe. @XimoSancho If you can confirm this we can close the issue.
