### ISSUE TITLE
Openshot 1.4.3 on linux mint 9   , project  not opening 

### ISSUE THREAD

**Issue by ashishraikwar** [OpenShot/openshot-qt#244]
i am using open shot to build a video project. everything was fine, but due to power cut , and some error it got hiberanete when i am exporting video in mpeg2 . now when i opening my project it can`t open. when i try to exporting video before this it is nearly created of 5GB. my free space is about 1 GB .   i am working from 6 month on this project and it not opening at all. ..plz help

**Comment by Kagetsuki** [comment]
First off, always keep backups of any WIP project.

Can you clarify what you mean when you are talking about "free space"? Memory perhaps?

Would it be possible for you to zip or tarball your project and upload it for someone else to check? Do you have access to another machine to try opening it on?

**Comment by jreynojustin** [comment]
OpenShot is now in Version 2.2 if you are still noticing issues in the latest version please re-open this issue letting us know.
