### ISSUE TITLE
Openshot_qt does not match the FreeDesktop directory specs

### ISSUE THREAD

**Issue by ThePreviousOne** [OpenShot/openshot-qt#2440]
it seems that Openshot places its files in$HOME/.openshot_qt
directory which doesn't match FreeDesktop directories specs :

The default for $XDG_CONFIG_HOME is $HOME/.config, the default for
$XDG_DATA_HOME is $HOME/.local/share. So all applications should look for
those environment variables and use those default values if the variables
are not set.

This causes a lot of clutter when applications do this a makes backups harder
when files are not in the right place

See [here](https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html)

**Comment by TuxVinyards** [comment]
Appimage 2.5.0

This link creator is a great feature >> kudos.

$HOME/.local/share is fine but this categories line is needed or the desktop link ends up classified as 'Other' and it doesn't get placed in 'sound and video' section:

Categories=AudioVideo;AudioVideoEditing;  

Also, a request:  I downloaded the image, not the .deb, deliberately so I didn't install.  Try: "Would you like to add a desktop menu link for this appimage y/n/later " on the popup.    Not   "Do you want to install bla bla bla "  I found myself auto-clicking 'no' the first time round ....

**Comment by ferdnyc** [comment]
@TuxVinyards I've migrated your comment to a new issue #3222, because it has nothing to do with the issue @ThePreviousOne opened here. Unless something is directly related to an existing issue, it should be filed as its own separate issue. That way, we can keep track of different things as we discuss/investigate/fix them.

**Comment by ThePreviousOne** [comment]
I was filing this issue against another Application and realized that link was wrong. Fixed it

**Comment by anestv** [comment]
The issue still exists in the latest versions. In the file `src/classes/info.py` , the specific lines are:

> HOME_PATH = os.path.join(os.path.expanduser("~"))
> USER_PATH = os.path.join(HOME_PATH, ".openshot_qt")

We can change them, to check if a directory "~/.openshot_qt" already exists, then to use that one as USER_PATH for backwards compatibility; and otherwise to create and use "$XDG_DATA_HOME/openshot_qt" according to the FreeDesktop directories specs (if $XDG_DATA_HOME is not set it should be $HOME/.local/share ).

By the way, the CACHE_PATH should also be placed inside $XDG_CACHE_HOME (default $HOME/.cache)

I can make a PR to demonstrate the needed changes

**Comment by ferdnyc** [comment]
@anestv Thanks, yeah it's definitely still an unsolved problem. It's not quite so simple to solve, either, as OpenShot is a cross-platform application. `$XDG_USER_DIRS` does not exist on Windows, and probably not on MacOS either.

We really _should_ be using `QStandardLibrary` paths to locate our dependent directories, but there are a _lot_ of changes throughout the source that would need to be done for that to work. It's a rather.. involved case, and exactly 0% fun.

(There are even some parts of the code where the defined path variables aren't even used, instead files are located at some fixed location beneath `info.PATH` or `info.USER_PATH`.)

But the more fundamental issue is the fact that `info.CACHE_PATH` isn't actually the cache, and it gets used for almost nothing. The **actual** working cache is located in (at least) `info.PREVIEW_CACHE_PATH`, `info.TITLE_PATH`, `info.BLENDER_PATH`, and `info.THUMBNAIL_PATH` — but those variables (except for `PREVIEW_CACHE_PATH`) can't be treated as cache universally. While they do describe the cache location for _new_ project data, when a saved project file is loaded some of them get updated to point to the project's assets directory, which is **_not_** a cache.  (Hey, I did say it's "involved". :wink: )

**Comment by ferdnyc** [comment]
> We really _should_ be using `QStandardLibrary` paths 

Sorry, that should've read "We really _should_ be using [`QStandardPaths`](https://doc.qt.io/qt-5/qstandardpaths.html) locations..."

**Comment by anestv** [comment]
Oops, I was only thinking of unix.

Indeed, it seems like using QStandardPaths is really the way to go! QStandardPaths are based on the XDG paths in unix, so, when we use them I think the current issue will be resolved!

**Comment by ThePreviousOne** [comment]
I dont know if this makes things any easier but I found this https://github.com/sago007/PlatformFolders

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
