### ISSUE TITLE
How to stop popping noise in exported video

### ISSUE THREAD

**Issue by wstinnett** [OpenShot/openshot-qt#2441]
I am creating a slide show with fades and then the music.  There are popping noises in the exported video.  I haven't seen any answers on how to fix this.  So my question is: has their been a solution to this issue.  I just installed the latest 12/3 daily build and still get the issue.
**System Details**
Windows 10
 - OpenShot Version 2.43 

Thanks.

**Comment by peanutbutterandcrackers** [comment]
This is a known issue. And for some reason, it isn't going anywhere, yet. But I'd suggest you tinker around with various export profiles and the 'advanced' tab in the export window.

If all else fails, you could perhaps even try setting up a virtual machine on your computer, running a GNU/Linux distro (https://www.linuxmint.com/download.php); and using the latest daily build to render the .osp file in there.

Another thing you could do would be to export the audio and video separately and maybe join using an external tool.

Hopefully version 2.4.4 will have all these issues fixed. There will be some changes for the better in it.

As of right now, however, I'm afraid we don't have much lead regarding the issue.

**Comment by wstinnett** [comment]
Thank you for the tips. I will try them out.

Regards,
Walter  



On Mon, Dec 10, 2018, at 2:21 AM, peanutbutterandcrackers wrote:
> This is a known issue. And for some reason, it isn't going anywhere,
> yet. But I'd suggest you tinker around with various export profiles
> and the 'advanced' tab in the export window.> If all else fails, you could perhaps even try setting up a virtual
> machine on your computer, running a GNU/Linux distro
> (https://www.linuxmint.com/download.php); and using the latest daily
> build to render the .osp file in there.> Another thing you could do would be to export the audio and video
> separately and maybe join using an external tool.> Hopefully version 2.4.4 will have all these issues fixed. There will
> be some changes for the better in it.> As of right now, however, I'm afraid we don't have much lead regarding
> the issue.> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].
Links:

  1. https://github.com/OpenShot/openshot-qt/issues/2441#issuecomment-445711541

**Comment by speedytechdev** [comment]
@wstinnett I am going to close this issue. Since this is a common bug and it has been reported. If you have any questions please leave a comment.
