### ISSUE TITLE
7.1 Audio not exporting

### ISSUE THREAD

**Issue by mthroesch** [OpenShot/openshot-qt#2442]
I record my game play With OBS with 7.1 Audio VLC shows all channels. (MKV format)
When I put the file into OpenShot 2.4.3 and export it or clip it and export it to MP4 format which is what I want. The file comes out with 2.0 Audio.  Is there any settings I need to change?

Settings in OpenShot :
Profile: HD 1080p 30FPS,  
Audio Sample Rate: 44100,  
Audio Channels: Surround (7.1Channel)

PC Specs if needed:
Intel I7 8700k ,
Gskill 32GB RAM 3600 ,
x2 Samsung 970Evos 500GB  M.2 SSD
EVGA 1080TI 

**System Details**
 - Operating System / Distro: [e.g. Windows 10]
 - OpenShot Version [e.g. 2.4.3]

**Comment by peanutbutterandcrackers** [comment]
I suggest you try playing the video with VLC. The audio stream most likely is there but your media player probably isn't able to decode it. If you wanted, you could try exporting as a webm or something. Or, you could also try transcoding using HandBrake.
