### ISSUE TITLE
GUI is zoomed in and too big

### ISSUE THREAD

**Issue by jekay001** [OpenShot/openshot-qt#2443]
As some already mentioned, I have the same issue the GUI is too big and zoomed in.
Operating System: Windows 10, x64
Screenshot: https://imgur.com/a/gMxVUoC

**Comment by speedytechdev** [comment]
Hi @jekay001 what version of Openshgot are you on and have you tried the latest [daily build](https://www.openshot.org/download/).

**Comment by gpsblues** [comment]
1. Edit file **C:\Program Files\OpenShot Video Editor\launch-win.bat** (administrator required)
2. Add line **SET QT_AUTO_SCREEN_SCALE_FACTOR=0** before launch.exe
3. Save File
4. Run Openshot always via **launch-win.bat** (not launch.exe)
5. Have a good time!

This solution works good in Win10 64bit.

**Comment by ferdnyc** [comment]
Correct, this is linuxmint/cinnamon#8206, which appears to affect every GNOME-based desktop, but only under certain (still not well understood) conditions.

It's due to a misdetection of physical screen dimensions that has Qt sizing the interface for what it thinks is a 7" screen.

**Comment by ferdnyc** [comment]
Oh. Actually... wait. If that's happening under WINDOWS, then that's a new wrinkle!

**Comment by TriHydera** [comment]
can you fix the issue

**Comment by Colorjet3** [comment]
Please download the latest DEV Daily Build from openshot.org/download/#daily and give it a try.  Let us know if you are still having the same issue and we can continue to troubleshoot.

**Comment by TriHydera** [comment]
> Please download the latest DEV Daily Build from openshot.org/download/#daily and give it a try. Let us know if you are still having the same issue and we can continue to troubleshoot.

When updating portable apps version?

**Comment by Colorjet3** [comment]
Please check this out:  https://github.com/OpenShot/openshot-qt/wiki/OpenShot-UI-too-large.
