### ISSUE TITLE
[1.4.3] Ubuntu 16.04 wrong track length

### ISSUE THREAD

**Issue by shadowvzs** [OpenShot/openshot-qt#2444]
Wrong tracking
At tracking bar it is clearly the video is over, but still continually got audio/video event nothing in trackbar.
This happen when i cutted out 10 second and this piece visually deleted from video trackbar but acctually still there.
I tryed save the project and restart but still there that invisble x second when was cutted out

**System Details:**
 - Operating System / Distro:  ChaletOs - based on Ubtuntu 16.04
 - OpenShot Version 1.4.3

**To Reproduce**
1. Edit a long video (above 1 hour
2. Do many cut downs (atleast at me appeared after i gues the 10th cut [used razor tool])
3. Randomly happen if you cutted and video visually shorter in trackbar but still there that piece
4. You can do anything the following cuts will be wrong after this cut (you pause down and do use razor tool and when you list back then have x second difference compared where you paused and cutted)

**Expected behavior**
Expecting remove seconds from video.

**Screenshots**
![openshot](https://user-images.githubusercontent.com/17709504/49836827-d3896800-fdac-11e8-8dab-d3e62b3fba2d.png)

**Logs**
i dont know if exist any log about it.

**Comment by speedytechdev** [comment]
Hi, @shadowvzs I would recommend using 2.4.3 since this fixed a lot of bugs. If you are still having issues after that let me know.

**Comment by shadowvzs** [comment]
sry but the new version for me alot worse than old one.... 
i tryed long ago and allways got problems with version 2+, i downloaded now too and it example tryed undo my cut and freezed the whole window for longer time until i closed, the video preview with sound not really ok (weird but seems the HD video too powerfull for my machine? in old version i got different resolution in preview and it was smoothly)

**Comment by peanutbutterandcrackers** [comment]
@shadowvzs - Hey there! Version 1.x has been discontinued. 2.x series is written from scratch from the ground up using a different multimedia framework. The naming is therefore unfortunate, as it might give the idea that 2.x series is somehow supposed to be a lot more better. In fact, I personally think of OpenShot 2.x still being in the 0.x versions of the 2.x series. There are tons of bugs. And not enough volunteers helping out. So, it might be a while before these issues are dealt with. However, they will be. With help from the community.

I will be closing this issue for now, so as to help control the number of issues. If you have any questions, etc. please feel free to comment/re-open.

**Comment by shadowvzs** [comment]
could i ask why so fast the old version compared with new? 
sad to hear about the situation with volunteers, sadly i also cannot help because i am php/js dev (and started in this year so still i am noob even with those) :/

**Comment by shadowvzs** [comment]
that would be interesting, you could use js with python or which role are js? nodejs (backend)? :)

**Comment by DylanC** [comment]
@shadowvzs - I used to be a noob like you but I took JS in the knee. 🤣 On a more series note. I would recommend to get familiar with AngularJS before looking at the timeline code. Some of it is more normal JS but it isn't very basic stuff, so maybe give yourself more time and JS projects. Maybe in the future you can help us out! :)

**Comment by shadowvzs** [comment]
i dont see anypoint in angularJS (i tryed angular 6, that was cool but i think 1 was too slow), i learning atm reactJS, well to get a better image maybe check my last repos (since i am not copy-paste hero, the most of thing was wrote by me and not forked)

**Comment by DylanC** [comment]
@shadowvzs - Oh I see. Well its Angular 1. The code is a bit old now. Angular 1 is still very popular though. I was thinking about writing the timeline in a new framework language but it would be lots of work.

**Comment by shadowvzs** [comment]
react not that young and what about plainJS (maybe longer a bit but you dont need to know framework what will be at end slower than vanilla js)? maybe longer but if optimized then the fastest :)
