### ISSUE TITLE
Crash on background

### ISSUE THREAD

**Issue by DaveJarvis** [OpenShot/openshot-qt#2445]
**Describe the bug**
OpenShot crashes when the tty is closed.

**System Details (please complete the following information):**
 - Operating System / Distro: Ubuntu Linux 16.04.5 LTS
 - OpenShot Version 2.4.3-dev1

**To Reproduce**
1. Open a terminal window
1. Type: `sudo apt remove openshot`
1. Type: `sudo add-apt-repository ppa:openshot.developers/ppa`
1. Type: `sudo apt-get install openshot-qt`
1. Type: `openshot-qt`
1. Press `Ctrl+F`
1. Select a PNG image
1. Click **Open**
1. Press `Ctrl+z` to suspend OpenShot 
1. Type: `bg` to run OpenShot in the background
1. Press `Ctrl+d` to close the terminal
1. Interact with OpenShot (e.g., drag the illustration into the timeline)

**Expected behavior**
OpenShot doesn't crash.

**Actual behavior**
OpenShot crashes.

**Additional context**
The following works:

1. Type: `openshot-qt > os.logs 2>&1`

No crash. For some reason writing directly to the tty and then closing the tty results in a segfault.

**Comment by ctsdownloads** [comment]
Unreproducible, old version of OpenShot
