### ISSUE TITLE
Mac Openshot 2.4.3 video preview aspect ratio

### ISSUE THREAD

**Issue by sinjun68** [OpenShot/openshot-qt#2447]
So I've read a bunch on this topic and created a 1:1 aspect ratio custom profile.
No matter what I choose as a profile, the video preview never updates to reflect the new profile.
The preview always remains the same!
Am I missing something?

**System Details**
 - Operating System / Mac OSX 10.14
 - OpenShot Version [e.g. 2.4.3]

**Comment by peanutbutterandcrackers** [comment]
This is a known issue and will be, hopefully, resolved in the future releases. Please follow the discussions over at #835. Closing as a duplicate.
