### ISSUE TITLE
Preview monitor in OpenShot 2.0.7 is very slow

### ISSUE THREAD

**Issue by Quartz2013** [OpenShot/openshot-qt#245]
When i play the video i have in my timeline the preview in the monitor is very slow.
As far as i know this can't be a memory problem. The problem occurs on a new (OpenSuSE Leap) computer with 32 GB memory.

**Comment by jreynojustin** [comment]
OpenShot is now in Version 2.2 if you are still noticing issues in the latest version please re-open this issue letting us know.
