### ISSUE TITLE
Lastest movie animation made with openshot 2.4.3 dev version

### ISSUE THREAD

**Issue by bobcrikey** [OpenShot/openshot-qt#2451]
Hello everyone heres my latest star wars animation movie  episode 2 
made with openshot 2.4.3 dev version.

enjoy 
   bob

https://youtu.be/nO_WNuChwFU

**Comment by speedytechdev** [comment]
@bobcrikey Nice https://media.giphy.com/media/srg19CG0cKMuI/giphy.gif
