### ISSUE TITLE
Compose a film of smaller sequences, edited as distinct projects

### ISSUE THREAD

**Issue by hesco** [OpenShot/openshot-qt#2452]
**Please fill out this template** 

**Is your feature request related to a problem? Please describe.**

I had asked on the IRC channel:  

I assembled my printed takes on a couple of channels from a previous day's shooting and am now ready to begin integrating the coverage from the next day's photography.  How do I insert blank timeline into the middle of a channel or collection of channels, into which I can add new material, without having to drag over every clip already in the channel?

As an editor working on a project with a longer running time (25 minutes for current project, looking like an hour or so for next project), I would like to compose a project of sequences, which are unique projects which can be edited distinctly, and then composed into a larger project in its current or latest form, in a way which creates a dependency relationship such that changes to a sequence/project, would trigger if not a new immediate rendering of the master project, then at least a visual clue that updating the latest render was yet pending.  

**Describe the solution you'd like**

I would want to define a master project as a collection of sequences, each a shorter project covering a discrete portion of the script, which can be assembled into a larger project.  And I would like to see some sort of intuitive Make-like behavior so that the appropriate versions were getting rendered and incorporated into the master project in a sane way.  I would love to see a means for versioning a cut of the sequence with log messages, to allow for an easy way to do A/B tests looking at alternative interpretations or to roll back to a previous cut after an experiment, by manipulating the metadata on an included sequence.  

As an .osp file appears to be json, it could easily be pretty-printed and stored under version control in human readable format which would produce useful diff's for tracking changes.  By making git or mg or svn or cvs an optional dependency, it ought to be easy enough to implement, I'd think, not knowing anything about your code base.  

**Describe alternatives you've considered**

The ability to lock and move sequences across multiple tracks, an easy way to choose a point on the timeline and insert five minutes of emptiness to accommodate new material, cut that new material, then snap back every thing to the right of the new material to watch it again.  

**Additional context**

**Comment by peanutbutterandcrackers** [comment]
I'm not sure I quite understand this issue but is this related to #1230?
