### ISSUE TITLE
Common Issues feedback

### ISSUE THREAD

**Issue by ferdnyc** [OpenShot/openshot-qt#2454]
Hm. One issue with #2449 being locked is, I have to create a new issue to comment on #2449. (Sorry! At least you can close this once it's read and handled, or not handled as deemed appropriate.)

Anyway, [the intro](https://github.com/OpenShot/openshot-qt/issues/2449#issue-391048153) to "Common Issues" currently reads:
> **These are issues that a lot of users have reported. If your issue is one of these below please only make a post about it if we are missing information. For example, the issue only happens if you press ctrl left arrow.**
> 
> [Render problems with h.264](#2371) 

...which led to me puzzling for like 30 seconds over why hitting <kbd>Ctrl</kbd>+<kbd>←</kbd> would cause rendering issues with a certain codec.

I know, believe me — and I _agree_, people should be able to figure out what it means, all they have to do is think a little.

But, at the same time, I still read it wrong. **#JustSayin**

**Comment by speedytechdev** [comment]
@ferdnyc I just locked it so people don't write on it but if staff cant write on it I will unlock it. Please feel do any changes you feel are necessary.

**Comment by ferdnyc** [comment]
@speedytechdev I assume you guys can. (The lock info says you can.) I'm not staff.

**Comment by speedytechdev** [comment]
Oh

**Comment by ferdnyc** [comment]
I dunno, just something to set it off more. Maybe...

<hr/>

**These are issues that a lot of users have reported. If your issue is one of these below please only make a post about it if we are missing information.** (**For example:** "The issue only happens if you press ctrl left arrow.")

Performance Issues
--
[Render problems with h.264](#2371)

User Interface Issues
--
(...List...)

Library or Startup Issues
--
(...List...)

**Comment by speedytechdev** [comment]
Nice, I will update it now and thanks for the feedback/help.
