### ISSUE TITLE
App stucks in "Missin File in Clip" prompt

### ISSUE THREAD

**Issue by achede22** [OpenShot/openshot-qt#2455]
How to reproduce the error

1. open Openshot
2. Upload a Video "test.mpg"
3. close OpenShot without saving
4. Remove video file "test.mpg"
5. Open OpenShot and it will ask you for the missing file "test.mpg"

as you deleted it, OpenShot will never work again.

![screenshot from 2018-12-16 19-35-08](https://user-images.githubusercontent.com/29759848/50059760-c59b6480-0169-11e9-8ca7-f0e71df9338f.png)

OpenShot just try to "continue the unsaved job" , but it don't let you start from scratch

**Comment by peanutbutterandcrackers** [comment]
Hey there!

This issue has already been fixed and version 2.4.4 will be released with the fix. If you want it right now, you could try out the daily builds. Hope that helps.

Closing this as resolved.
