### ISSUE TITLE
What You See Is NOT What You Get, Apparently

### ISSUE THREAD

**Issue by peanutbutterandcrackers** [OpenShot/openshot-qt#2456]
It seems that every now and then, OpenShot is exporting something very different from the preview. In this post, I aim to keep track of all the WYSINWYG issues.

#2453 (now closed as somehow fixed) - Effects applied do not seem to be rendered.
#667 (re-opened because of a recent [video demonstration](https://www.youtube.com/watch?v=rlXq-Dm1AaQ)) - Video Reversed in the project (and seen as such in the preview) does not render reversed.
#2048 ([contains video demonstration](https://youtu.be/ySsje9aqC8A)) - Things syncing well in the preview are not syncing in the exported video
#2298 (resolved, but might be useful in figuring out the issue. Hint: It seems to be FPS related)
https://github.com/OpenShot/libopenshot/issues/115 ([preview](https://youtu.be/qEFqt61q61s) vs. [render](https://youtu.be/81rf-HOg7T0)) - The render is a "tad bit out of sync"
https://github.com/OpenShot/openshot-qt/issues/2396#issuecomment-441832514 - This comment also notes that OpenShot "seems not to be a WYSIWYG video editor". Just adding that here for the comment.

**Comment by ferdnyc** [comment]
FTR, I didn't get the impression that #2396 was complaining about mismatches between the _preview_ and the export.

**Comment by peanutbutterandcrackers** [comment]
I was just adding the comment from the issue here because the "Gloabally, seems not to be a WYSIWYG video editor, which is... slightly annoying for such tool" line in the comment made me realize that all these other issues could be put under one umbrella issue. Didn't feel like leaving out the issue (comment) that articulated it that well. If you think it is rather unnecessary, I can always remove it.

**Comment by ferdnyc** [comment]
Cool.

**Comment by SkippyleGrandGourou** [comment]
Looks like a good place to comment :  it seems openshot does not respect keyframes in the output video when using Youtube HD presets.

More precisely, I had a track with audio fading out while another had audio and alpha fading in.  The preview displayed (and sounded) correctly, but when exporting the whole video the audio fade out occurred too early (before the character had finished her sentence…).

I did not investigate further once I discovered this issue did not occurred with the "advanced" default settings.  If it has not been already referenced, I may try to produce a minimal working example and file an actual issue when I find some time… maybe.

**Comment by step21** [comment]
Adding this: I have a project with two clips, and I slowed both of them by half. The first one is cut at the beginning and it now (after slowing down) starts earlier than before.

**Comment by ccollischon** [comment]
> The render is a "tad bit out of sync"

I think the effect is rather in the UI and not in the render. When pausing / resuming and clicking / resuming the preview the audio buffer behaves weirdly. That would explain the described problems as well. The user simply edits the videos out of sync and the renderer is perfectly fine.

That would explain why @SuslikV could never reproduce it with his hand-crafted examples.

**Comment by elgybe** [comment]
I am experiencing this issue for a few months on every project. Here is what I can observe:
When previewing, everything is ok. 
When rendering the video, there is an extra "video only" track (about 1/4 of a second long) just at the beginning of the video output, but the sound begins correctly the rendering, so there is an offset of 1/4 of a second between the sound and the picture.

Hope this helps, I can share a sample project just tell me the way you prefer for sharing (the video file is quite big...).
