### ISSUE TITLE
Album cover image appears in timeline

### ISSUE THREAD

**Issue by sansori2** [OpenShot/openshot-qt#2458]
When you add a song (MP3) in the timeline, the cover image of the album appears as an image in the timeline. 

**System Details
Windows 10
Open Shot video 2.4.3.

**Comment by peanutbutterandcrackers** [comment]
The easiest solution might be to use [HandBrake](https://handbrake.fr/) to transcode the audio from an mp3 to something like oga.

Please do let me know if it does or does not work.
