### ISSUE TITLE
Openshot title in Hebrew

### ISSUE THREAD

**Issue by shaieyal** [OpenShot/openshot-qt#2459]
Hi all,
I'm new user of OpenShot and so far I love it. only problem I found is creating Title in Hebrew language - the Hebrew characters simply do not show. English works perfect but Hebrew does not show.
Any ideas how to resolve?

thanks in advance, Shai

**Comment by peanutbutterandcrackers** [comment]
Do you mean the Animated Titles, or the normal Titles?

**Comment by guye1296** [comment]
Any updates? Hebrew characters are not shown on an animated title on the latest version

**Comment by ferdnyc** [comment]
@guye1296 

In the Animated Titles, we're pretty limited by Blender's font support. Which, in a word, abysmal.

On the bright side, that's slated to finally be at least _somewhat_ addressed in Blender 2.90, so there may be more features possible for making use of fonts once that release is available.

The SVG titles (the non-animated ones), font support is still a bit up and down, some things work and others just don't, which is understandably frustrating.

There is always a workaround available with those titles, though. If you can't create the titles you want using the built-in title editor, it's always an option to load the title file into Inkscape and edit it there, which gives you the full power of its text layout tools. Then you can export the file as a transparent PNG image. If you import it into OpenShot that way, with the fonts already rendered, you know it'll look exactly how you want it to.
