### ISSUE TITLE
Openshot

### ISSUE THREAD

**Issue by Ratul-Ghosh** [OpenShot/openshot-qt#246]
Dear Openshot, 

while working with an entire music album, when I try to drag n drop more than 3 files in panel 'track 1', I am restricted to drag more files in that panel, as it seems due to lack of panel's length.

please help me to overcome the situation, 

from, 
ratul

**Comment by Kagetsuki** [comment]
@Ratul-Ghosh Each time you drag a track it should expand the time bar (the scroll bar will be on the bottom). Can you give a screenshot or something of this?

**Comment by jreynojustin** [comment]
Non-response. Closing issue.
