### ISSUE TITLE
Each subsequent slice takes longer and longer (Windows 10)

### ISSUE THREAD

**Issue by dragonixor** [OpenShot/openshot-qt#2461]
**Please fill out this template** 

**Describe the bug**
When trying to get clips out of a recording of a few hours, I slice around the bits I want to keep and then erase the remnants of what I don't need. At first, it works fine, but each cut takes longer, with the program going unresponsive during the process, to the point of taking several minutes per slice

**System Details (please complete the following information):**
 - Operating System / Distro: Windows 10
 - OpenShot Version 2.4.3
Intel Core i7-8700K 3.70Ghz
32GB RAM

**To Reproduce**
1. Open a new project
2. Insert a video, preferably a certain length
3. Advance in the video, right click the marker and slect slice all > keep both sides
4. Repeat steps 2 and 3 a few times, deleting 1 section out of 2 (to make separated clips)
5. After ~10-20 repetitions, the slow down becomes evident

If anything more information is needed, I can try to get it for you, but right now I feel like I might have to use another editor at least for longer videos, which is a bummer because I really likes being able to make titles on inkscape easily, which I used for subtitles.

**Comment by 45Green** [comment]
Same problem here, but after ~3-5 repetitions on the laptop.

**Comment by peanutbutterandcrackers** [comment]
I wonder if a recent change made in the source tree fixed this issue. Could you please try out the [daily builds](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914) and see if this behaviour repeats itself yet? If it does, we'll try to get it fixed ASAP.

**Comment by dragonixor** [comment]
Installing now, will update you when it's done

**Comment by dragonixor** [comment]
Trying to open a project I already created gives me this error:
https://i.imgur.com/aRhbnQ2.png

With a new project, it seems like the issue is still there, sadly
