### ISSUE TITLE
Openshot crashes with Inkscape

### ISSUE THREAD

**Issue by Yinnova** [OpenShot/openshot-qt#2462]
My Question is about Inskcape and openshot
I have a problem with Inkscape. When I choose an advanced title editor, the openshot crahses (always). Could you help me?

With the other programme "Blender" I haven't any problem.
Thank you!

System Details:
 - Operating System / Distro: Windows 7 proffesional
 - OpenShot Version 2.4.3

**Comment by speedytechdev** [comment]
Hi @Yinnova could you provided me with some other details, please

-  What version of Inkscape are you using
-  Do you have any screenshots (if possible)
-  Do you have the crash logs from the issue

Hopefully, we can help you with your problem.

**Comment by mphilippe** [comment]
I have the same issue, it makes OpenShot become unresponsive as soon as I click to start edition on Inkscape.

I'm on Windows 10, Inkscape's version is 0.92.3 (2405546, 2018-03-11).

Where should I look for crash logs?

**Comment by SuslikV** [comment]
@mphilippe The software will be released as soon as you close InkScape editor.

**Comment by ferdnyc** [comment]
Yeah, this is unfortunately a known (and long-standing) bug in how OpenShot communicates with Inkscape. There's a fuller (too full) explanation in [my comment](https://github.com/OpenShot/openshot-qt/issues/1789#issuecomment-403194654) on #1789.
