### ISSUE TITLE
Upgrade seems to lead to system crash

### ISSUE THREAD

**Issue by hesco** [OpenShot/openshot-qt#2463]
**Please fill out this template** 

**Describe the bug**

I was prompted to upgrade from within the application.  I accepted the upgrade.  It never seemed to complete.  After killing the process and restarting the application, intent on ignoring the upgrade offer, it shortly locked up and became unusuable, took over the lightdm gui and froze the machine, requiring a reboot.    

**System Details (please complete the following information):**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
GRUB_TITLE=Linux Mint 18.3 Cinnamon 64-bit

 - OpenShot Version [e.g. 2.4.3]
upgrading from 2.4.1 to 2.4.3 

**To Reproduce**
1.  Open Openshot 
2.  Accept offer to upgrade when prompted 

**Expected behavior**

I expect to watch it spend a moment or so downloading and upgrading components of the OpenShot installation, probably terminating and reopening the new version of OpenShot.  

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**

Not sure what logs might be of interest, but , 
judging from uptime, these log excerpts seem most relevant:

/var/log/auth.log  -- 

Dec 19 11:30:49 marcus010 systemd-logind[959]: New session c2 of user hesco.
Dec 19 11:30:49 marcus010 lightdm: pam_ck_connector(lightdm:session): nox11 mode, ignoring PAM_TTY :0
Dec 19 11:30:59 marcus010 polkitd(authority=local): Registered Authentication Agent for unix-session:c2 (system bus name :1.61 [/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1], object path /org/gnome/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Dec 19 11:32:35 marcus010 systemd-logind[959]: Removed session c1.
Dec 19 11:32:35 marcus010 systemd: pam_unix(systemd-user:session): session closed for user lightdm

**Comment by ctsdownloads** [comment]
Unreproducible, old version of OpenShot
