### ISSUE TITLE
Crash on initial install and run appears to be python related.

### ISSUE THREAD

**Issue by camcorderdoctor** [OpenShot/openshot-qt#2464]
**Please fill out this template** 

**Describe the bug**

**System Details (please complete the following information):**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.3]

So I just downloaded the latest OpenShot 2.4.3 and I am getting a python error, happened right from the start. I use Windows 8.1 Home if that means anything. I have included a screenshot of the error message for review. Maybe I'm missing some libraries to run it or something? Anyway would love to use this program any advise would be greatly appreciated. Thanks
![screenshot 1](https://user-images.githubusercontent.com/42306645/50253272-a8f46c00-03b7-11e9-9d36-cbea84eee3fe.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**

**Comment by ctsdownloads** [comment]
Old version of OpenShot
