### ISSUE TITLE
, I try to make a video of duration 1 minute and 30 seconds, the program has a default of 5 minutes, I do not know how to remove that remaining time

### ISSUE THREAD

**Issue by kobrat1** [OpenShot/openshot-qt#2465]
Hello, I try to make a video of duration 1 minute and 30 seconds, the program has a default of 5 minutes, I do not know how to remove that remaining time, which I have left over. regards

**Comment by speedytechdev** [comment]
Hi, @kobrat1 If you export your clip it should get rid of the rest of the timeline. Which means it should be 1 min and 30 seconds unless something is in the timeline further down. Please let me know if this helped.

**Comment by peanutbutterandcrackers** [comment]
You might also want to consult [this guide](https://gist.github.com/peanutbutterandcrackers/f0f666243133e0ed25abbc12a4ba23d7). Closing this as answered.
