### ISSUE TITLE
ImportError: DLL load failed: The specified procedure could not be found.

### ISSUE THREAD

**Issue by DcR-NL** [OpenShot/openshot-qt#2466]
**Describe the bug**
After first time install and launching, i get this error and nothing more:

```
---------------------------
cx_Freeze: Python error in main script
---------------------------
Traceback (most recent call last):
  File "C:\msys64\mingw64\lib\python3.6\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
  File "C:\msys64\mingw64\lib\python3.6\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
  File "openshot_qt/launch.py", line 54, in <module>
  File "D:\Windows\Software\OpenShot Video Editor\classes\app.py", line 34, in <module>
    from PyQt5.QtWidgets import QApplication, QStyleFactory, QMessageBox
ImportError: DLL load failed: The specified procedure could not be found.

---------------------------
OK   
---------------------------
```

**System Details (please complete the following information):**
 - Operating System / Distro: Windows 10 (x64)
 - OpenShot Version: 2.4.3

**To Reproduce**
1. Install application
1. Launch application

**Expected behavior**
No error window.

**Screenshots**
![image](https://user-images.githubusercontent.com/1094952/50308847-c3ecdc00-049c-11e9-816b-336565de3b10.png)

**Logs**
None? .openshot_qt is empty

**Additional context**
Tried uninstalling, removing the installation folder and installing again. Still the same error.

**Comment by KerryRitter** [comment]
Same issue. Windows 10 x64.

**Comment by phtran72** [comment]
Same issue installing clean on my daughter's computer.  No issue installing same build on my Windows 10 laptop.  Tried 32-bit build, same problem.

**Comment by DCSIProductions** [comment]
Exactly same issue on Windows 7 64 bit laptop

**Comment by ferdnyc** [comment]
I'm going to close this in favor of the more detailed #2748, for OpenShot 2.4.4.
