### ISSUE TITLE
using video 3gp format 

### ISSUE THREAD

**Issue by pietjes** [OpenShot/openshot-qt#2467]
**Please fill out this template** 

**My Question:**
I should to make use of the Video program but before installing it I should like to know if video-format
3gp is supported by this program ? Maybe the program can convert 3gp to MP4 or another compatible format ?

Thanks in advance !
 

**System Details**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.3]

**Screenshots**

**Comment by speedytechdev** [comment]
@ferdnyc or @peanutbutterandcrackers Would one of you know?

**Comment by peanutbutterandcrackers** [comment]
@pietjes - I am not really sure as I haven't really come across any 3gp files recently. However, I think you should be able to use [HandBrake](https://handbrake.fr/) to transcode the 3gp file into something like mkv and then use it in OpenShot. Hope that helps.

**Comment by ferdnyc** [comment]
The only `.3gp` file I have handy is an (AAC) audio-only one from my phone, which OpenShot has no problems importing and working with. FFMpeg supports the format well, so there shouldn't be any problems.
