### ISSUE TITLE
Is It Possible to Export Transparent PNGs?

### ISSUE THREAD

**Issue by shatterblast** [OpenShot/openshot-qt#2469]
After importing an image sequence of .PNG files for testing, I try exporting the same images.  The transparency seems replaced by a black background.  Is it possible to export PNGs with transparency preserved?

My system is Linux Mint 18.3 with OpenShot version "2.4.3-dev1".

Thank you for your time.

**Comment by shatterblast** [comment]
I switched to HitFilm Express for this need.

**Comment by shatterblast** [comment]
I switched to HitFilm Express for this need.

**Comment by peanutbutterandcrackers** [comment]
@N3WWN - Just out of curiosity, is this possible? It isn't currently, it seems, but could we have this feature. Seems like a nice little feature to have.
