### ISSUE TITLE
Apply multi preset effect on clip

### ISSUE THREAD

**Issue by mihani** [OpenShot/openshot-qt#2470]
**My Question:**

Hi,
I used Openshot and I would like to apply a fade transition (with preset menu) on a selection of clip It's possible to do this ?

Thanks

**System Details**
 - Ubuntu 18.04
 - OpenShot Version 2.4.3-dev1

**Comment by speedytechdev** [comment]
Hi, @mihani try [this](https://www.openshot.org/static/files/user-guide/transitions.html). If did not help you please let me know and I could go into further detail.

**Comment by mihani** [comment]
I can't see this... I apply on each clip a preset fade... I know this for the next time.

Thank you for your help @speedytechdev
