### ISSUE TITLE
Picture Frames Animation_no output from Blender

### ISSUE THREAD

**Issue by RxnCatalyst** [OpenShot/openshot-qt#2472]
Selecting Picture Frames animated title produces  two text boxes displaying "No frame was found in the output from Blender" messages.  All the other animated titles work without error.  Only get error when I select picture frames animation 

I can acknowledge the error in the two messages and select my four picture paths (used elsewhere in the same project) but, as expected, get same error displayed in two message boxes when I attempt to render.  Picture paths can be .png .jpg .mp4 does not matter.

 - Operating System  Windows 10 (8GB RAM, 2.2GHz Processor)
 - OpenShot Version 2.4.3
 - Blender Version 2.79b

**Comment by Danddman** [comment]
I am having the same issue with Blender 2.80 and Openshot 2.4.3 in Window2 10 with 8GB RAM and 3.0GH processor. Only I get this error on all animated titles.

**Comment by pacohojaverde** [comment]
Same. OpenShot 2.4.4 and Blender 2.8.

**Comment by ferdnyc** [comment]
@midoriha-senpai Belated, but: That's because Blender 2.80 isn't compatible with OpenShot 2.4.4. See pinned issue #2901.

**Comment by ferdnyc** [comment]
(Obviously, it also isn't compatible with 2.4.3, to address the previous comment.)
