### ISSUE TITLE
INSERTING A VIDEOCLIP INBETWEEN TWO OTHER CLIPS

### ISSUE THREAD

**Issue by renevc** [OpenShot/openshot-qt#2473]
Is there still no way to insert videoclips inbetween two other clips? Found an issue from 2017 but it seems as if this is not possible. Would be a great enhancement for me.

Kind regards, René

**Comment by peanutbutterandcrackers** [comment]
No, sir. Not yet. However, please do follow the discussion in that thread. Once the devs are done dealing with the stability and performance related issues, there will be a lot more features added. And this really is a much needed one. A lot more interest in a certain feature might help prioritize the issue over others (but there are no guarantees).

Please do keep on loving and supporting this Free Software gem that is OpenShot.

Closing this as answered and duplicate.
