### ISSUE TITLE
Openshot Video Editor ugly and barely usable@Linux Mint 19.1 Cinnamon

### ISSUE THREAD

**Issue by peterdp** [OpenShot/openshot-qt#2478]
Details see https://github.com/linuxmint/Cinnamon/issues/8206

Some annotations of how the issue is observed in Openshot. Red arrows indicating some of the blurred icon/text zones, red box indicating the much too large visualization of the 'Track edit area':

![ugly_openshot_2](https://user-images.githubusercontent.com/46158705/50453156-e79d9f80-093e-11e9-8abf-f25c4a357ded.png)

I like the Openshot Video Editor very much. Because of the above described problem however I can't use Openshot on Linux Mint 19.1 Cinnamon. I want to help resolving the issue.

Is there someone who uses Openshot on Linux Mint 19.1 Cinnamon without the described problem?

Is there someone else who has the same problem on Linux 19.1 Cinnamon?

Even if it is possibly a more general QT problem, can someone with Openshot development knowledge help the Linux Mint team with the location of the problem? What can cause the blurry icon display? 

I propose https://github.com/linuxmint/Cinnamon/issues/8206 further is used to exchange updates.

The goal of this bug report is:

1) informing the OpenShot community of the issue
2) learning if other Openshot users experience the same issue
3) asking the Openshot community if someone can help with the location of the issue
4) learning if the Openshot program can be improved to avoid the dependency on the root cause of this issue

**Comment by peanutbutterandcrackers** [comment]
I don't know about 19.1, but OpenShot was looking (and working) pretty decently in my friend's Linux Mint 19 Cinnamon. I wonder if it is a 19.1 issue.

**Comment by ferdnyc** [comment]
I don't, please don't tag me on issues in the future.

**Comment by peanutbutterandcrackers** [comment]
I'm sorry. Okay.

**Comment by peterdp** [comment]
It's not an openshot issue. Details see linuxmint/Cinnamon#8206
