### ISSUE TITLE
SVG/PNG Text Size Not Respected

### ISSUE THREAD

**Issue by peanutbutterandcrackers** [OpenShot/openshot-qt#2480]
OpenShot Version: 2.4.2-dev1+ (daily PPA)
Operating System: Linux Mint 19 MATE

This just might be a false alarm. Still...

I'd noticed this before with `svg` files but last night I encountered the same issue with `png` files. With `svg`, I'd thought that it was just a behaviour of the svg render-er but it seems there is another reason underlying this.

No matter what the size of the text used in pngs, OpenShot seems to render it by scaling to fit the entire screen.

However, the `png`s in question have nothing but text in them. Like so (white text on transparent background):
![image-00072](https://user-images.githubusercontent.com/26764547/50460536-28c59c00-099f-11e9-8b77-d87f1d25cce2.png)

Steps to reproduce:
1. Grab a frame from the current project.
2. Open it in GIMP.
3. Create a text layer, considering how the final image will look on the project itself. Note the text size, `x`.
4. Remove the background frame and crop the image to the text layer.
5. Export it as `png`.
6. Import it into the project.
7. Result:
![bug](https://user-images.githubusercontent.com/26764547/50460685-5b23c900-09a0-11e9-8a82-aa402a5c131c.png)

Expectation:
It'll only be as big as it's original dimensions.

Further Information:
Changing the `scale` property doesn't bring it to the original dimensions, either. The only way to do it seems to be by manually changing `scale x` and `scale y` properties.

I've noticed similar issue with `svg` files. A 720 sized 'A' doesn't exactly cover the entire screen.

**Comment by jonoomph** [comment]
Also, here is an updated test image (which works nicely):
![1080-box](https://user-images.githubusercontent.com/5551883/50881699-16d4f780-13a8-11e9-9422-e496b281d8ad.png)

**Comment by peanutbutterandcrackers** [comment]
Confirmed as fixed. Thank you, Mr. Thomas. :100: :+1:
