### ISSUE TITLE
Program freezing up when export & AVI preview freezing

### ISSUE THREAD

**Issue by 45Green** [OpenShot/openshot-qt#2481]
**Describe the bug**
The program freezes when you try to do anything (ex. export), without memory leaks or high CPU/GPU consumption and indication what it was an error.

**System Details (please complete the following information):**
 - Operating System: Windows-10-10.0.17134
 - OpenShot Version: 2.4.3

**To Reproduce**
Unreproducible cause the nature of this problem (see logs).

**Expected behavior**
The program should not freeze or at least leave a clear message about the error.

**Logs**
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/2711484/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2711478/openshot-qt.log)

**Additional context**
This problem was reported by my friend, first, he was thinking what it was because AVI but when deadline is very near, the project editing become unpossible cause it's freezing.

AVI problem (quoting from PM):
```md
### Describe the bug
When you try to playback AVI clip on existing project, the program freezes and then closes itself. But there is no problem when AVI files has been entirely removed from project.

### System Details
Windows 10 Home
OpenShot Version 2.4.3

### To Reproduce
Go to File > Import files and select an .mp4 and .avi large files (> 1GB).
Place them on the timeline.
When you try to skip-thought .avi track using timeline, the OSV will freeze and then close without leaving a log (even in Verbose mode).

### Expected behavior
No side effects using playback ruler and video preview.
```

**Comment by ctsdownloads** [comment]
Unreproducible, old version of OpenShot
