### ISSUE TITLE
MTS file exported in wrong aspect ratio

### ISSUE THREAD

**Issue by IlaFrance** [OpenShot/openshot-qt#2486]
<bMTS Video Exports in Different Aspect Ration/b>

**Dear OpenShot Developer, 

I have tried every possible way of exporting my MTS file and cannot find the way to do it so that the aspect ratio of 16/9 is preserved in the exported file, which is always unacceptably narrowed. (Though the attached screen shot shows one in MP4, I have tried mov, MPEG2, and all the others available to try to get a way of preserving the size.) 

Is there a way of changing or setting up the screen aspect ratio in advance? Or some way of exporting it that I have not been able to figure out? I cannot find which version I have, but it seems, from the software manager on my computer to be Openshot qt. 

I have attached three screen shots showing the Openshot project, the original MTS screen size and the exported screeen size.

Thank you so much in advance for your help. 

With good wishes,
Ila*

**System Details**
 - Operating System / Distro: [Linux Mint]

![openshot project](https://user-images.githubusercontent.com/46200626/50513059-b2579580-0a95-11e9-9851-4a9bffb8d3db.png)
![exported file](https://user-images.githubusercontent.com/46200626/50513064-b84d7680-0a95-11e9-8397-514f38ab8060.png)
![original mts file](https://user-images.githubusercontent.com/46200626/50513065-b84d7680-0a95-11e9-9635-134e6aef9519.png)

**Comment by ctsdownloads** [comment]
Closed issue, 2018 - old version
