### ISSUE TITLE
Deleting track not entirely undo-able

### ISSUE THREAD

**Issue by Harvzor** [OpenShot/openshot-qt#2488]
**Describe the bug**
I (accidentally misclicked) and deleted the the track which had all of my work (a 45 minute video cut into 15 minutes) on it rather than the empty track which wasn't needed.

I thought clicking the undo button would fix everything - it did bring back my track but it was empty. Continued clicking of the back button brought up some of the segments of my cut up video but not all of them (ran out of undo history).

**System Details (please complete the following information):**
 - Windows 10
 - OpenShot 2.4.3

**To Reproduce**
1. New project
2. Import a long video
3. Cut video up into at least 20 different parts, (moving them around, removing some sections of video)
4. Delete track with work on it
5. Clicking undo brings back the track but not the parts of the cut up video
6. Successive clicking of undo brings back some of the bits of video

**Expected behavior**
I expected the undo button to bring back the track with all of my work.

**Additional**
Thanks for the hard work on this application, I'm looking forward to the future of it.

Sadly I've now lost 3 or more hours of my work so I'm pretty upset... **Is there anyway to get it back?**

**Comment by Harvzor** [comment]
Also, I've now disabled the autosave feature as once I realised that my change could not be undone, I thought perhaps I could at least use my last save, but I guess the autosave had just happened and saved the broken state of my work.

I've also changed the undo limit to 999 rather than 20.

**Comment by peanutbutterandcrackers** [comment]
Hey there,

Sorry for the inconvenience. Yes, it was the auto-save. I myself have had issues with that and have just recently disabled it. While in session, OpenShot does have unlimited undo-redo features.

Yes, I think deleting a track should be a single step and not too many individual steps. Hopefully we can get this fixed soon.
