### ISSUE TITLE
Add presets for social media sites in the export dialog

### ISSUE THREAD

**Issue by aldonogueira** [OpenShot/openshot-qt#2489]
I want to publish a song to Twitter and Mastodon, but both don't accept audio files. Apparently the user needs to convert it to video before upload. Then I created two tracks in OpenShot, one with the song and the other one with a picture, and exported the project to one of the formats they say they accept. The problem is that there are many choices of video and audio codecs. Mastodon accepted an webm file, but I couldn't post anything to Twitter  

I guess it would be really helpful if there were presets for popular social media sites, such as Twitter, Facebook and Mastodon, among the web profiles in the export dialog  

This is the song I published to Mastodon using OpenShot :)  
https://masto.donte.com.br/@aldonogueira/101319924051080900

**Comment by peanutbutterandcrackers** [comment]
For the time being, could you please try out some from [OpenShot Presets Testing](https://github.com/gary9872/openshot-presets-testing) repository? But yes, this needs to happen. We'll try to get this in in the future releases (we had a not-so-small issue block this small enhancement before so we can't promise anything for the upcoming release, however). Thank you for the suggestion!

**Comment by speedytechdev** [comment]
Hi @aldonogueira could you make a sperate post for your song so we can give it the showcase label. We would love to show the community your work.
