### ISSUE TITLE
Opening 1.4.3 project (ascii codec byte 0xd0 error)

### ISSUE THREAD

**Issue by smishlayev** [OpenShot/openshot-qt#249]
Greetings!
I hve tried Openshot BETA 2.0.7 (both PPA and AppImage) and I cannot open my legacy format project. The error message is as follows
Failed to load project file /home/diana/Desktop/Jugger Victory Park.osp: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)

Have someone experienced something similar and may be can help? Greatly appreciated

Cheers,
Lyosha

**Comment by jonoomph** [comment]
Can you attach your *.osp file here, and I'll take a look. (assuming it doesn't have any sensitive info in it). Thanks! My guess is that you have a file path which contains a non ascii character... which of course, "should" be fine, but it is clearing breaking somewhere. =) Thanks.

**Comment by jonoomph** [comment]
Good news, I was able to reproduce it by adding a unicode file path to a 1.4.3 project file, and attempting to import it into OpenShot 2.1. Keep in mind, support for legacy 1.4.3 projects files is a bit limited, but it should import the basic structure, and many of the basic properties. 

Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot. _It might take a couple hours for the latest version to appear._
