### ISSUE TITLE
Mobile (360P) preset, makes the 720P video 4 times larger..

### ISSUE THREAD

**Issue by Ehishere** [OpenShot/openshot-qt#2492]
Hi
I used the mobile quality 360P video profile , to resize a 720P video..
Using the simple tab, I got a 4 times larger file in size(30 Mb became120 Mb)
When doing through Advanced tab, I see preset frame rate is 30000 for mobile profile! Maybe that's the reason. There are other profiles with unusual preset frame rates too,

System Details
 - Windows 10 - OpenShot Version  2.4.3

**Comment by ctsdownloads** [comment]
Double check the codec/container. Also make sure the frame rate is the same as the source video. The source video was probably in a container like mp4 and had some video compression. Make sure you match this and the frame rate.
