### ISSUE TITLE
I am a mess

### ISSUE THREAD

**Issue by Maxwell1214** [OpenShot/openshot-qt#2494]
**Please fill out this template** 

<I accidentally closed the video preview of my openshot. What will I do to get it back? -->

**My Question:**

I accidentally closed the video preview and I dont know how to get it back. I cannot use it without the preview. What will I do?
![image](https://user-images.githubusercontent.com/46241443/50536942-02695180-0b95-11e9-9c82-75383ea3484c.png)

**System Details**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.3]

**Screenshots**

**Comment by peanutbutterandcrackers** [comment]
View > Views > Simple View

Hope that helps.

Closing as answered.
