### ISSUE TITLE
Video freezes when you resize a clip that has time property set

### ISSUE THREAD

**Issue by ManoStuart** [OpenShot/openshot-qt#2495]
**Describe the bug**
Video freezes when you resize a clip that has time property set.
Tried with avi and mp4

**System Details:**
- Windows 10  64 bit
- Openshot Version 2.4.3

**To Reproduce**
* Add a clip
* Slice the clip and keep the left side
* Set the time of the clip to fast forward 2X
* Resize clip (increase the duration)
* In the preview the clip will play normally until the point where the resize occurred, then it freezes.

**Expected behavior**
The clip should fast forward including the resized portion

**Comment by larstr** [comment]
Same issue exist also on Linux platform in OpenShot version 2.4.1, 2.4.2 and 2.4.3. Export of video will also contain frozen images.
