### ISSUE TITLE
Audio track no audio after I used the zoom in/out feature

### ISSUE THREAD

**Issue by geminiflux** [OpenShot/openshot-qt#2498]
I started a project and everything was fine. It was my first time using Open Shot so I used the zoom in and out feature to look at the whole track. As soon as I did that all my audio disappeared. The track is stil there, just no sound. 

I looked for a mute button but don't see one. 
I deleted everything and imported the sound track again. Still no sound.
I closed the program. Still no sound.
I deleted the entire project and started over from scratch. Still no sound.

I've also noticed when I hit play to preview (trying to get the sound back) it flies through 10 minutes of audio in 30 seconds, so if I had sound it wouldn't be understandable. 

**System Details**
 - Operating System Windows 10
 - OpenShot Version  2.4.3

**Comment by speedytechdev** [comment]
Hi @geminiflux, that is really odd. Could I please get some things from you so we can work out what happened. 

- Have you tried the daily build?
- Do you have any screenshots?
- Could you please provide the crash logs
- Send a copy of the project with all the files used.

Could you also post the second issue in a different post please just to make it easier for us thanks.

**Comment by HajoVonKracht** [comment]
Similar effect here. I used openShot fine, all working like a charm. Today when I try to do the next project: no sound at all. 
Reading the above issue: the last project used was the first in which I used the "transform" feature.
Now no way to get the sound back.

**Comment by SuslikV** [comment]
@HajoVonKracht what do you mean by "Now no way to get the sound back" - You import video file with the sound and  export video has muted track, or no audio tracks at all?

**Comment by HajoVonKracht** [comment]
I import videos with sound. In the OpenShot Video Editor I hear no sound at all. When I export the project, the generated .mp4 file has audio included, but the OpenShot Video Editor stays completely mute. I have de-installed and re-installed the tool, but without effect.

**Comment by ferdnyc** [comment]
@HajoVonKracht The Transform tool use I can't believe is anything other than coincidence, if you're anything like me then most sessions are the first time for using _some_ feature.

It sounds like OpenShot simply isn't able to access your audio device. You didn't say what OS you're using — is it Windows, by any chance?

If you could try downloading the latest Daily Build for your OS from https://OpenShot.org/download/ , since the last release we've added a new audio device selector in the preferences, using that to configure your sound output **should** fix things, or at least trigger an error message that'll point to the cause of the trouble.

**Comment by DamonGang** [comment]
Same problem. I have no sound in the editing area. I followed the steps and still had the problem. I made a video demonstrating the "no sound" https://youtu.be/HitG6Y8mfzU

**Comment by ferdnyc** [comment]
@DamonGang 

Sorry to hear that. A few questions:

Have you checked the second tab of the Preferences? What are your settings for sample rate and output device?

Do you have more than one audio device on your system?

If you launch OpenShot from a terminal window, are there any error messages or warnings about audio playback in the output?
