### ISSUE TITLE
No Video Preview (help)

### ISSUE THREAD

**Issue by ssvi** [OpenShot/openshot-qt#2499]
![screenshot 3](https://user-images.githubusercontent.com/46272248/50553575-5f3d3880-0c77-11e9-98d3-ca5279124ae2.png)
Just downloaded OpenShot and theres no video preview so I can't see / edit anything. Does anyone know how to get it?

Thank you

**Comment by peanutbutterandcrackers** [comment]
View > Views > Simple View

All the best.
