### ISSUE TITLE
Open Project and Import Files dialog click to open only?

### ISSUE THREAD

**Issue by firew4lker** [OpenShot/openshot-qt#25]
The Open Project and Import Files dialog seems to only support click to open/select folder/files? Can I enable click to select folder/file and double click to open?

Arch Linux with KDE.

**Comment by jonoomph** [comment]
For me, the file dialogs are single click to select, and double click to open or go a folder deeper. This might be a global Qt setting on KDE (just a wild guess). Digging around a bit, I'm finding lots of bug reports related to KDE and Qt and single click. I don't think this is an OpenShot bug, so I'm going to close this issue. But feel free to keep digging and update this issue if you find anything else. =)

**Comment by firew4lker** [comment]
Thanks you. I solved it.

It seems that in a mixed KDE-4, KDE-5, QT-5 system, Qt-5 apps will search config from 

~/.config/kdeglobals

Just add 

SingleClick=false

to the [KDE] section of ~/.config/kdeglobals
