### ISSUE TITLE
Strange audio on ubuntu mate

### ISSUE THREAD

**Issue by LeonardoCT** [OpenShot/openshot-qt#250]
when i try to play the preview i just get audio distortion

**Comment by Hubrrr** [comment]
I have same issue. but I'm using Windows 10. Very crackly, skipping audio when previewing -- but audio is fine after export.

**Comment by FrankSanabria** [comment]
What is your processor?

**Comment by Hubrrr** [comment]
Mine is: AMD Athlon II X4 620 Processor, 2600 Mhz, 4 Cores, 4 Logical Processors. If relevant, it doesn't have this issue when I edit using Adobe Premier Elements 14.

**Comment by DylanC** [comment]
@LeonardoCT - Do you still have this issue on v2.3.4 of OpenShot?

**Comment by DylanC** [comment]
Could not reproduce this behavior on v2.3.4.
