### ISSUE TITLE
animated title : O.S. 2.4.3  won't accept Blender path .

### ISSUE THREAD

**Issue by vmars316** [OpenShot/openshot-qt#2501]
Hello & Thanks ,
Windows 10 x64
I would like to use the 'animated title' but 
O.S. 2.4.3  won't accept Blender path "C:\Program Files\Blender Foundation\Blender" .
What can I do ?
Thanks

**Comment by peanutbutterandcrackers** [comment]
Please try out the daily builds and browse to the blender executable. That should do the trick, hopefully.

**Comment by vmars316** [comment]
Thanks peanutbutterandcrackers ,

I am a github member ,
but I don't know how to navigate it .
I see this note: 


* Please **attach log files** if you are reporting a crash. Otherwise, we will not be able to determine the cause of the crash.

  _Please download our latest daily installer:_

  1. www.openshot.org/download - click the '**Daily Builds**' button, then grab the latest build from the list.
     (Use the buttons below to download installers for a different Operating System.) 

from here:
https://github.com/OpenShot/openshot-qt/search?q=daily&unscoped_q=daily 


But how to get to "latest daily installer" ?

And as for "www.openshot.org/download - click the '**Daily Builds**' button" 

There is no "Daily Builds" button at www.openshot.org/download .
 
Sorry for the trouble ,
Thanks for your help !

**Comment by douglaslitw** [comment]
Windows 10 x64
you need Blender path
C:\PrFiles\Blender Foundation\Blender\blender.exe
Inkscape path the same
C:\PrFiles\Inkscape\inkscape.exe

**Comment by peanutbutterandcrackers** [comment]
@vmars316 - Here:
![screenshot at 2019-01-01 10-58-49](https://user-images.githubusercontent.com/26764547/50570458-48503080-0db4-11e9-99d0-ace55a01e1df.png)
That is the download page and right next to the windows download, you can see the daily build button. Click on it, and download the top-most one from the list that shows up. Hope that helps.

**Comment by ctsdownloads** [comment]
Solution - [needs Blender 2.80](https://download.blender.org/release/Blender2.80/blender-2.80-windows64.msi). Apparently newer versions come up as undetected when I run OpenShot from the command line during tests.

1) Try the **_latest_** version of OpenShot.
2) Use the [Blender package for 2.80](https://download.blender.org/release/Blender2.80/blender-2.80-windows64.msi)
