### ISSUE TITLE
I cannot re-install Openshot after I uninstalled it

### ISSUE THREAD

**Issue by ubuntu2388** [OpenShot/openshot-qt#2503]
Hello there! How are you?!

 I am using the latest version of Openshot in my Ubuntu latest version. Unfortunately, when it kept hanging I got so frustrated and decided to uninstall it. I hoped that when I would download it again, it would be fixed. Haha I know it is kind of dumb to expect it to be fixed because you know when it comes to issues you cannot correct a wrong with another wrong.

And so when I downloaded Openshot in the Ubuntu Software Window, it would say this:
"Unable to Install 'Openshot Video Editor':
Error while installing package: installed postfix package post-installation script subprocess returned error exit status 75

How can I resolve this my friend?
Thank you in advance :)

**System Details**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.3]

**Screenshots**

**Comment by ctsdownloads** [comment]
You need to run `sudo apt -f install` in a terminal, then try again.
