### ISSUE TITLE
Openshot crashes when you speed up past x16

### ISSUE THREAD

**Issue by speedytechdev** [OpenShot/openshot-qt#2507]
**Please fill out this template** 

**Describe the bug**
I tried to speed up a video I made to make it a time-lapse. This works with other editors I used but when I used open shot it did not work. Everything before x16 works but past that it crashes/goes slow.

**System Details (please complete the following information):**
 - Operating System / Distro:  Windows 10, 
 - OpenShot Version  2.4.3

**To Reproduce**
Steps to reproduce the behaviour:
1. Right click on the video in the timeline
2. select the time option and choose the forward option
3. Once you have chosen the forward option choose x16 or x32
4. Wait 1min or so and see it crash.

**Expected behavior**
The video to speed up.

**Screenshots**
![capture 1](https://user-images.githubusercontent.com/40452959/50625044-20b2c100-0f8a-11e9-84d9-8d06871d5b94.PNG)
![capture 2](https://user-images.githubusercontent.com/40452959/50625046-20b2c100-0f8a-11e9-8727-f7562cac2571.PNG)

**Logs**
[logs](https://jmp.sh/wjgsYIu)

**Comment by speedytechdev** [comment]
Closing this issue since it seems to be fixed by the daily build.

**Comment by ctsdownloads** [comment]
Old version of OpenShot. Closing as it's outdated.
