### ISSUE TITLE
Rendering Bux Program Crash

### ISSUE THREAD

**Issue by vince127** [OpenShot/openshot-qt#2508]
**Please fill out this template** 

**Describe the bug**
A clear and concise description of what the bug is
When I finish editing my video and I start to render it takes very long. At the start of the rendering proces the fps is about 11 (1080 60fps) but then it starts to get lower, to 6 fps. And the biggest trouble causing bug is that everytime I try to render my file, it crashes at exactly 34,0%. The full program crashes and it has happened 4 times with rendering it at 1080 60fps and two times while rendering at 720 60fps. My file isn't even that big, it's 28 minutes and I used two tracks almost fully and 1 tracks only at the beginning and end.
**System Details (please complete the following information):**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot 2.4.3

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Video Profile**
If the problems you are experiencing are known to be, or may possibly be, related
to a specific format video file being used in OpenShot, please consider generating
a [MediaInfo](https://mediaarea.net/en/MediaInfo) profile and including it with your
report. Select View > Text from the menu to bring up a plaintext report, and attach
or paste it into this report. (If copy/pasting, consider adding the profile as an
additional comment after you post this initial report.)

**Additional context**

**Comment by ctsdownloads** [comment]
Sorry to hear about your project crashing. 1080 60fps is some pretty serious rendering requiring a PC that can handle it. If you're seeing it crash during the export/rendering, it's likely it may be too much for your computer. 

Is this a desktop or a laptop. If it's a desktop, what are your specifications? CPU, RAM and video card?

**Comment by vince127** [comment]
Thanks for the response! It's a Dell laptop and it's already 5 years old
and I've used it everyday for school.

Op di 19 mei 2020 22:23 schreef Matt Hartley <notifications@github.com>:
