### ISSUE TITLE
Fade in/out timing changes when exporting to Video Profile HD 1080p 30fps

### ISSUE THREAD

**Issue by KenWade** [OpenShot/openshot-qt#251]
Fade in/out timing changes when exporting to Video Profile HD 1080p 30fps.

When exporting, just after selecting the new Video Profile, the fade times change.  This can be seen in timeline and the video is rendered as per the messed up fade timing.

**Comment by JtLively** [comment]
Please try the newest version.
If the issue persists, open a new issue with current version, OS, and applicable screenshots. 

We apologize for the late response and are doing our best to make up for time.
