### ISSUE TITLE
Name of the exported video without double extension

### ISSUE THREAD

**Issue by ArmeF97** [OpenShot/openshot-qt#2510]
**Is your feature request related to a problem? Please describe.**
![immagine](https://user-images.githubusercontent.com/6240983/50725555-6e046f00-10ff-11e9-92d2-097f9810d3fe.png)

As you can see I named my exported video t1.mp4, but the it's name, in the folder, is "t1.mp4.mp4", can we do something to detect redundant things like this? 

**Describe the solution you'd like**
If the name ends with .mp4, it should be trimmered

**Comment by speedytechdev** [comment]
hi, @ArmeF97 I like the idea and I don't think we have anything like that yet.

**Comment by ferdnyc** [comment]
Sorry, I honestly thought I'd already fixed this forever ago. #3088 will fix it for real, finally.
