### ISSUE TITLE
Can't speed up the video with arbitrary precision

### ISSUE THREAD

**Issue by giteshnandre** [OpenShot/openshot-qt#2511]
I am opening this issue because the https://github.com/OpenShot/openshot-qt/issues/1892 is closed even though there is no solution. Note that 'Time' property did not work for me. It creates a glitch in the clip.

**Comment by N3WWN** [comment]
Did you follow the details that I wrote in https://github.com/OpenShot/libopenshot/issues/176#issuecomment-442466083 ?   

If there's a problem with any of what I wrote, I'd like to correct it.

Or, if my steps are correct, but there's another artifact created by Openshot which is unexpected, please provide the details so we can replicate and resolve it.

Thanks!

**Comment by poszy6** [comment]
For me this isnt working at all. When I seleck the time -> fast -> forward -> 2X (or any of the values) the clip shrinks, but when I try to play it, it froze and lag.  I think when you use 2X(or other) OpenShot calculate the new time value for you ( its just a hunch ).
