### ISSUE TITLE
App crashes while preview playback of an image sequence without prompting an error message.

### ISSUE THREAD

**Issue by RoadRacer82** [OpenShot/openshot-qt#2513]
**Please fill out this template** 

**Describe the bug**
App crashes while preview playback of an image sequence without prompting an error message.

**System Details (please complete the following information):**
 - Operating System / Distro: Windows 10 Pro 64 bit, Build 17134
 - OpenShot Version 2.4.3
 - Mainboard: Gigabyte H370M D3H GSM
 - CPU: Intel Core i5-8500, 6x 3 GHz
 - RAM: 2x 8 GB DDR4 2666 MHz CL16
 - Disk 0: 240 GB Corsair Force MP500 (M.2 PCIe 3.0 4x, NVMe 1.2)
 - Disk 1: 2 TB SATA HDD
 - GPU: NVIDIA GeForce GTX 1050 Ti 4 GB
 - Monitor 1: 4K UHD 16:9 (3840x2160 60 Hz)
 - Monitor 2: FHD+ 16:10 (1920x1200 60 Hz)

**To Reproduce**
1. Chose Profile '4K UHD 2160p 30 fps (3840x2160)' (I also tried 50 fps and 60 fps)
2. Add image sequence (821 *.png files 3840x2160) via drag&drop to the 'Project Files' area
3. Add the sequence to the very beginning of 'Track 0'
4. Start preview playback
5. After about 9 seconds the app crashes without prompting an error message
6. The same happens when 'Export Viedo' without starting the preview (4.) before

**Expected behavior**
I would expect that it works, because with a small sequence with only 300 images it does work.
With a 720 *.jpg image sequence it also works (slowly, but it works).
According to the MS-Windows Resourcemonitor the hardware usage is below its capacity, thus the hardware seems not to be the problem.

**Screenshots**
n.a.

**Logs**
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/2730484/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2730485/openshot-qt.log)

**Video Profile**
If the problems you are experiencing are known to be, or may possibly be, related
to a specific format video file being used in OpenShot, please consider generating
a [MediaInfo](https://mediaarea.net/en/MediaInfo) profile and including it with your
report. Select View > Text from the menu to bring up a plaintext report, and attach
or paste it into this report. (If copy/pasting, consider adding the profile as an
additional comment after you post this initial report.)

**Additional context**

**Comment by ctsdownloads** [comment]
Old version of OpenShot. Closing as it's outdated.
