### ISSUE TITLE
Imported Videos have first few seconds missing

### ISSUE THREAD

**Issue by pikaras** [OpenShot/openshot-qt#2515]
Whenever I import a MP4 file, the first 3-15 seconds are missing and the last 3-15 seconds are very glitchy.  This happens indiscriminately to all MP4 files, regardless of whether they are dragged into the file section, imported with right click, or imported otherwise.

Version is Windows 10, V 2.4.3.  Uninstalled and reinstalled program and issue persists.  

To reproduce, simply add any MP4 to the timeline.  Converting the file to FLV and adding it that way seems to work.

Screenshot of a video with the first 11 seconds missing (and the last 11 seconds buggy AF)
![image](https://user-images.githubusercontent.com/46461568/50794566-8d220e80-126f-11e9-8d32-16c024dfedd4.png)

**Comment by ctsdownloads** [comment]
Old version of OpenShot. Closing as it's outdated.
