### ISSUE TITLE
Openshot

### ISSUE THREAD

**Issue by jazanyc** [OpenShot/openshot-qt#2518]
**Please fill out this template** 

**Describe the bug**
Openshot crashes when I try to import photos.

**System Details (please complete the following information):**
 - Operating System / Distro: Windows 10
 - OpenShot Version 2.4.3

**To Reproduce**

**Expected behavior**
The program would run as 

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Video Profile**
If the problems you are experiencing are known to be, or may possibly be, related
to a specific format video file being used in OpenShot, please consider generating
a [MediaInfo](https://mediaarea.net/en/MediaInfo) profile and including it with your
report. Select View > Text from the menu to bring up a plaintext report, and attach
or paste it into this report. (If copy/pasting, consider adding the profile as an
additional comment after you post this initial report.)

**Additional context**

**Comment by peanutbutterandcrackers** [comment]
Hey there,

You haven't filled up the form correctly (nor provided any other relevant information). So, I will count this as a mistakenly opened issue and close it.

If you have any problems, please do comment. Thanks!
