### ISSUE TITLE
Not loading after installing Win 7 32bit

### ISSUE THREAD

**Issue by Darren7617** [OpenShot/openshot-qt#2521]
**Describe the bug**
Error window appears reporting problems with python ?. I have included a screenshot of the error.
Is there a way to fix this I really like this software.

**System Details (please complete the following information):**
 - Operating System Windows 7 32 bit
 - OpenShot Version  2.4.3]

**Expected behavior**
I expected it to open

**Screenshots**
[Any ideas what is causing this.docx](https://github.com/OpenShot/openshot-qt/files/2743393/Any.ideas.what.is.causing.this.docx)

**Comment by peanutbutterandcrackers** [comment]
The next time around, please only attach `.png` files or `.jpg` or `.gif` files rather than a `.docx` file. It'll be a lot easier for us.

This is the same old cx_freeze error. I will be closing this as a duplicate for now. Please do follow the discussions in other threads. Thank you.
`
