### ISSUE TITLE
Is it possible to make a picture move in a specific direction?

### ISSUE THREAD

**Issue by Raysunman** [OpenShot/openshot-qt#2523]
Lets say for example that I wanted to have an animation of a human walking across a sidewalk and I wanted them to move to the left then down. Is such an action like this possible with open shot editor? I got it recently so I am not quite sure if this is possible.

**Comment by speedytechdev** [comment]
Hi @Raysunman, Hopefully my aswner can help you. 

So you can use the properties panel if you want a lot of process control. You can use this to control rotation, scale, location and etc. This can be accessed by going to the **view** tab on the top left. Going to views and choosing the advanced view.
![image](https://user-images.githubusercontent.com/40452959/51017195-14f17b00-15d8-11e9-8d54-25b1149c50bb.png)

You could also use the animation presets which can be found by right clicking on the picture and going to **animate**. You can choose to do the animation at the start,end or entire clip.
![image](https://user-images.githubusercontent.com/40452959/51017211-2c306880-15d8-11e9-916b-1bb86263a1fb.png)

Please let me know if you are stuck still or this did not aswner your question. Thanks and have a great day.
![have a good day](https://user-images.githubusercontent.com/40452959/51019627-761d4c80-15e0-11e9-9493-d68bb762f8ef.gif)

**Comment by speedytechdev** [comment]
**Closing warning reason:** Question answered

**Comment by peanutbutterandcrackers** [comment]
[This Guide](https://gist.github.com/peanutbutterandcrackers/f0f666243133e0ed25abbc12a4ba23d7) will give you further instructions on how to create something like this:
![meet tux](https://user-images.githubusercontent.com/26764547/48016787-a1a13800-e154-11e8-9f1d-bfe2a64a6ad4.gif)

Closing as answered.
