### ISSUE TITLE
Open Shot gets hanged on 25% while exporting,strange.

### ISSUE THREAD

**Issue by gulrez2019** [OpenShot/openshot-qt#2524]
**Please fill out this template** 

**Getting hang, launch.exe failed to start. Everything works fine until I export the video, everytime when export reaches 25% it got hanged and don not respond. Windows gives message launch.exe failed to start**

**System Details (please complete the following information):**
 - Operating System : Window 7]
 - OpenShot Version : 2.4.3

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
Description:
  A problem caused this program to stop interacting with Windows.

Problem signature:
  Problem Event Name:	AppHangB1
  Application Name:	launch.exe
  Application Version:	0.0.0.0
  Application Timestamp:	00000000
  Hang Signature:	3d79
  Hang Type:	0
  OS Version:	6.1.7600.2.0.0.256.1
  Locale ID:	1033
  Additional Hang Signature 1:	3d79b9d90986516dde940a4757b40f19
  Additional Hang Signature 2:	9411
  Additional Hang Signature 3:	94118edeb17c58ac1fe99157b73375b2
  Additional Hang Signature 4:	3d79
  Additional Hang Signature 5:	3d79b9d90986516dde940a4757b40f19
  Additional Hang Signature 6:	9411
  Additional Hang Signature 7:	94118edeb17c58ac1fe99157b73375b2

**Video Profile**
If the problems you are experiencing are known to be, or may possibly be, related
to a specific format video file being used in OpenShot, please consider generating
a [MediaInfo](https://mediaarea.net/en/MediaInfo) profile and including it with your
report. Select View > Text from the menu to bring up a plaintext report, and attach
or paste it into this report. (If copy/pasting, consider adding the profile as an
additional comment after you post this initial report.)

**Additional context**

**Comment by speedytechdev** [comment]
Hi @gulrez2019, To make it easier for us to keep all the information about this issue in one spot. Could you post your information as a comment in this [post](https://github.com/OpenShot/openshot-qt/issues/2519), please since this is a common issue. Once you have copied and pasted the information in please remove this issue. 

Thanks and have a great day.

**Comment by speedytechdev** [comment]
> Information being moved

**Comment by mikelacsa** [comment]
details moved
