### ISSUE TITLE
How to forward/backstep video 1 Frame at a time ?

### ISSUE THREAD

**Issue by vmars316** [OpenShot/openshot-qt#2526]
Hello & Thanks ;
OS 2.4.3 , win 10 x64
How to advance/backstep video 1 Frame at a time ?
I would like to take a snapshot of certain Frames .
Thanks

**Comment by peanutbutterandcrackers** [comment]
Using the arrowed keys (cursor keys). Hope that helps. Closing as answered.

**Comment by vmars316** [comment]
Ahh Thank You !
