### ISSUE TITLE
No preview in preview screen

### ISSUE THREAD

**Issue by jahipster** [OpenShot/openshot-qt#2527]
I am in simple view (issue same in advanced view). No preview of video in video preview box. I can right click and see full preview in pop out box, but preview will not play in preview location on regular view.

I believe this is also why I cannot export video - saying only frame 1 to frame 1. When I type in actually frames, I get only black screen (even though export took about 3 minutes).

[Windows 10, 64-bit]

![screenshot](https://user-images.githubusercontent.com/46636528/51079584-82181580-1697-11e9-8d60-076761003b49.png)

**Comment by peanutbutterandcrackers** [comment]
This is strange. Could you please [attach the logs](https://gist.github.com/peanutbutterandcrackers/d84c257e74b72d8b06b4daffaebc5a14) so that the devs can dig further into this issue? Thanks!

**Comment by N3WWN** [comment]
A screenshot including the timeline would be helpful, also, so we can see the current playhead position, video clip effects, keyframes, etc.
