### ISSUE TITLE
OpenShot crashes when dragging a mp3 into the timeline

### ISSUE THREAD

**Issue by Gravarty** [OpenShot/openshot-qt#2528]
OpenShot closes without showing any errors when dragging a mp3 into the timeline

 - macOS Mojave 10.14.2
 - OpenShot Version 2.4.3 (doesn't work with the latest dev build as well)

1. Open OpenShot
2. drag (or import) a mp3 file into OpenShot

(Logs via Terminal)

`timeline:INFO Adjusting max size of preview image: PyQt5.QtCore.QRect(23, 0, 675, 380)
timeline_webview:INFO Dropping item on timeline - item_id: None, item_type: os_drop
files_listview:INFO Processing drop event for PyQt5.QtCore.QUrl('file:///Users/user/Downloads/title.mp3')
files_listview:INFO Adding file: /Users/user/Downloads/title.mp3
Caught signal 4 (SIGILL)
---- Unhandled Exception: Stack Trace ----
---- End of Stack Trace ----`

**Comment by peanutbutterandcrackers** [comment]
For the time being, you could probably use [HandBrake](https://handbrake.fr/) to convert the mp3 file o something else (oga or opus should be fine) and try that.

However, could you please also recreate the crash again and attach the logs as suggested by [this guide](https://gist.github.com/peanutbutterandcrackers/d84c257e74b72d8b06b4daffaebc5a14) please? That'll help the devs further to fix this.
