### ISSUE TITLE
Messed up display

### ISSUE THREAD

**Issue by InkSack** [OpenShot/openshot-qt#2529]
I opened openshot and this is what I saw.
![image](https://user-images.githubusercontent.com/46652821/51088115-d7196180-1753-11e9-884d-5cd4619088da.png)
Apparently, this is not right, how do I fix/reset this.

**Comment by Theis-Borup** [comment]
I've got the same problem...

**Comment by JUNE06512156** [comment]
我也是
請問有人會處理嗎?

**Comment by JUNE06512156** [comment]
> 我有同樣的問題......

我知道怎麼用了
去檢視下方的檢視那邊可以調呦~~~

**Comment by InkSack** [comment]
Sorry but that makes no sense

**Comment by peanutbutterandcrackers** [comment]
View > Views > Simple View

That'll fix it.

Closing as answered.

**Comment by InkSack** [comment]
Thank you
