### ISSUE TITLE
Openshot 2 not finding my external hard drive

### ISSUE THREAD

**Issue by Leblonk1** [OpenShot/openshot-qt#253]
When I go to import files Openshot will only show me my computer hard drive, not the external hard drives I have plugged in. If I select a file that is on an external hard drive and choose to open it with Openshot it opens, and works, but I can't load files directly from the program. Is this a bug, or did I do something wrong when I installed Openshot 2?

**Comment by Kagetsuki** [comment]
@Leblonk1 sounds like a problem with the system file chooser or linkage between the QT file chooser and the system. What OS are you using?

**Comment by Leblonk1** [comment]
@Kagetsuki Ubuntu 14.04

**Comment by jonoomph** [comment]
Have you tried our latest AppImage on our website? If not, give that a try. Also, try dragging and dropping files into OpenShot from your file manager. That should also work. Good luck!
