### ISSUE TITLE
Crashing/lagging/glitching

### ISSUE THREAD

**Issue by lisamsp** [OpenShot/openshot-qt#2530]
Im working on a video and im almost done, but everything is lagging en i can't do anything.
Please help me bc i spend alot of time on this video!

Thank you

**Comment by peanutbutterandcrackers** [comment]
If that is the case, I would recommend that you try out the [latest daily builds](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914). I have quite certain it'll work better for you. But please do make sure to make a backup of your project file (the `.osp` file somewhere else before you try to open it up. If something goes wrong, you can just bring the original `.osp` file back into the same place, switch back to the stable version, and open it up). Hope that helps.

Closing as answered. Please do feel free to comment, etc.
