### ISSUE TITLE
Just froze, stopped working and crashed

### ISSUE THREAD

**Issue by teo1978** [OpenShot/openshot-qt#2531]
**Please fill out this template** 

**Describe the bug**
I tried OpenShot for the first time and for about 5 minutes, and while I was cutting and moving some clips, it partially stopped responding. It wouldn't responding to clicks on the timeline (I couldn't cut, move, do anything with the clips; when I resized the window, it failed to redraw stuff) but the application interface apparently continued responding. I could click on the File menu and click Save Project, but it didn't actually save shit (even though it didn't show any error message).

After a while, it crashed.

Fucking pathetic.

**System Details (please complete the following information):**
 - Operating System / Distro: Ubuntu 16.04
 - OpenShot Version 1.4.3

**To Reproduce**
1. Use OpenShot normally for more than a few minutes

**Expected behavior**
Should work.

** Observed Behavior (you forgot this one in the template BTW)
Stops responding, stops working and eventually fucking crashes.

**Logs**
> If you are experiencing a crash, please collect and attach logs of the problem.

I would be glad to do that if you told me where to find them.

**Comment by peanutbutterandcrackers** [comment]
It seems you are using OpenShot 1.x. It is obsolete. Pleas use the 2.x series. [This PPA](https://www.openshot.org/ppa/) has it. Hope that helps. Closing for now.
