### ISSUE TITLE
A weekly update of bugs fixed needed

### ISSUE THREAD

**Issue by bobcrikey** [OpenShot/openshot-qt#2532]
Hello everyone, A weekly update of bugs fixed would be great.
it will show the progress of openshot.

Quite often when a new dev version comes out theres nothing to say what bugs have been fixed,
having a thread updated when a new dev version with the bug fixes would help.

as not bugs have been fixed yet. and it can be frustrating downloading so many dev versions
only to find the bugs still exist.

cheers
 bob

**Comment by peanutbutterandcrackers** [comment]
The [commit history](https://github.com/OpenShot/openshot-qt/commits/develop) will give you all the details. While it could be great, we don't think we have enough volunteers to send out a post every week saying what has been changed (however, a bot could be made to do that job; but alas I don't know how to make one).

The dev versions are made after every single commit that is made too the develop branch. So, if you wanted to test the change of the most recent commit, you'd wait for the dev version that comes with a newer timestamp (or number). Hope that helps.

Closing this for now as answered. Feel free to comment, etc.
