### ISSUE TITLE
OpenShot Crashes When Adding MP4 and MTS Video Files to Project

### ISSUE THREAD

**Issue by jeremyschwartz98011** [OpenShot/openshot-qt#2534]
**Describe the bug**
OpenShot immediately crashes upon adding either .MP4 or .MTS file format videos to a new project.  

**System Details (please complete the following information):**
 - Windows 10 64-bit
 - OpenShot Version 2.4.3-dev3

**To Reproduce**
1. Go to "Import Files"
2. Selected either MP4 or MTS video file
3. Brief loading cursor, then OpenShot crashes

**Expected behavior**
Video files successfully uploaded into the OpenShot project workspace. 

**Logs**
See attached logs for MP4-related crash. 
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2756587/openshot-qt.log)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/2756588/libopenshot.log)

**Additional context**
I had been encountering "Not Responding" issues with a previous build of OpenShot and was recommended to download the newest "Daily Build" from the OpenShot website. The video upload/crash issue started after downloading the Daily Build: OpenShot-v2.4.3-dev3-1547274944-cf4f12cf-3861a2c5-x86_64

**Comment by weerdenburg** [comment]
I'm also having issues with *.MTS files (Panasonic DMC-FT5).
OpenShot is able to load them, but placed on the timeline the program hangs / or has almost no response anymore.

**Comment by djon3s** [comment]
I am also having issues with importing *.mp4 when drag & dropping in OpenShot on MacOSX

First time using, 2nd tutorial screen, pick an *.mp4 to drag onto and OpenShot spontaneously quits without an error message or complaint. 

Version of OpenShot is 2.4.4
macOS Version is High Sierra 10.13.6

**Comment by SuslikV** [comment]
@djon3s Look for OS updates (if possible). There was info that the OSX Mojave 10.14.3 works a bit better with the OpenShot - https://github.com/OpenShot/openshot-qt/issues/2114#issuecomment-487875996

**Comment by andikay** [comment]
I just downloaded the latest OpenShot 2.6.0 and this issue with MTS files hanging the app when dragged into the timeline still exists...how can this be sich a "great video editor" when auch a glaring issue exists in the application and it has been unanswered for over two years now! Sorry, but this is ridiculous.
