### ISSUE TITLE
Imported MOV file gives every minute a hickup 

### ISSUE THREAD

**Issue by Luckyluke1945** [OpenShot/openshot-qt#2536]
**Please fill out this template** 

**My Question:**
Playing the file in a windows quicktime player there is no problem.
Playing this file in OpenShot Video Editor gives each minute a hickup in the audio and maybe also in the video
Could a be that OpenShot is missing particularly codec.
Original video codec info:
   Stream 0: 
     Codec: H264-MPEG-4 AVC (part 10)(avc1) 
     Language: English
     Type: Video
     Video resolution: 1280x720
     Buffer size: 1280x720
     Frame speed:  30
     Decode format: Planar 4:2:0 YUV
     Orientation: Upper left
     Chrome-location: Left
  Stream 1:
     Codec: sowt
     Language: English
     Type: Audio
     Channels: Mono
     Sample rate: 32000 Hz
     Bits per sample: 16

**System Details**
 - Operating System / Distro: [e.g. Windows 7 32bit home premium]
 - OpenShot Version [2.4.3]

**Screenshots**

**Comment by ctsdownloads** [comment]
Old version of OpenShot. Closing as it's outdated.
