### ISSUE TITLE
WHEN I EXPORT IT ALWAYS DELAYS THE AUDIO FROM FILM :-(((((((((((((((

### ISSUE THREAD

**Issue by rosagudmunds** [OpenShot/openshot-qt#2537]
**Please fill out this template** 

When I export my video it always gives me audio delays!!! No matter how many times I double check if I've synched the audio precisely it always takes it out of sync !!

I'm using iOS MOJAVE 10.14.1 (18B75
My open shot is version 2.4.3.dev-3

I simply export video on the default mp4 profile, as I don't know of an alternative to rather use.

The video I am exporting is a combination of .MOV and .VOB files and is approx. 45 min in length

PLEASE HELP!

**Comment by Another-MrZ** [comment]
Not sure is the same bug, but I too have synching problems on export when I try to superimpose an audio track over a previous video with its own audio. The two audio tracks are mixed together, but the audio I want to overlap always starts way earlier than the one set in the project, which is perfectly synched.
Using Version 2.4.4 on Windows 7 and exporting AVI/MPEG4

**Comment by SuslikV** [comment]
@Another-MrZ if you preview the clip in OpenShot - are the audio tracks stay in sync?

**Comment by Another-MrZ** [comment]
**@SuslikV**  When I preview the clip it is synched, but when I export, the audio track to be superimposed starts several seconds earlier than it should.

I have noticed that when I preview, the waveform of the videoclip is out of synch with the audio I hear.  It is like I hear the audio, and after few seconds the line passes over the corrispondent wave.
This even when I load a single video track without trying to superimpose anything.
I only tried with AVI/MPEG4 format.
Not sure I have explained it clearly enough to help.

**Comment by SuslikV** [comment]
Can you export this test file - https://github.com/OpenShot/openshot-qt/issues/1290#issuecomment-489569399 - again into mp4 format? Any changes?

Waveform display is other issue, it was mentioned earlier - just change the zoom level of _Timeline_ (15 sec is nice value to display the audio).
