### ISSUE TITLE
Need help getting Openshot to work with out a missing .mov file

### ISSUE THREAD

**Issue by JohnWT2000** [OpenShot/openshot-qt#2538]
**Please fill out this template** 

**My Question:**
Every time I try to open Openshot to edit a piece of footage I run into an error telling me that I am missing a .mov file that was on my old external drive that had crashed. It keeps trying to access the missing file by having me dig through the files on my computer. I have no way to get the file back and I would like to know how I can reset the program so then it won't try to pick up a lost project.

**System Details**
 - Operating System / Distro: Windows 10
 - OpenShot Version v2.4.3

**Screenshots**

![screenshot 37](https://user-images.githubusercontent.com/46791079/51335837-12b47400-1a51-11e9-9851-0cecac6b59a5.png)

**Comment by speedytechdev** [comment]
Hi @JohnWT2000, This issue was fixed in the [daily builds](https://www.openshot.org/download/). If you give that a go it should fix the issue please let me know if it does not.

**Comment by JohnWT2000** [comment]
It did not work it gave me an error code 740. Upon trying to install the daily build.

**Comment by speedytechdev** [comment]
@ferdnyc would you know why
