### ISSUE TITLE
blender.exe issue

### ISSUE THREAD

**Issue by wxy555123** [OpenShot/openshot-qt#2539]
I have set its path correctly, and when I click animated titles, it works.
But at the same time it always popups a black dos window.
Why is this? Does it need any more settings? Thanks!

![qq 20190118173838](https://user-images.githubusercontent.com/21214207/51378484-53db7f80-1b48-11e9-886a-5e243bf59d24.png)

**Comment by speedytechdev** [comment]
Hi, @wxy555123 so you don't get anything in the preview window.
My file path for blender is C:/Program Files/Blender Foundation/Blender/blender.exe

**Comment by wxy555123** [comment]
@speedytechdev 
But it's not like what you say... Actually, I can see the corresponding 3D image in the preview window.
so I'm sure I set the right path.
![55555555](https://user-images.githubusercontent.com/21214207/51456889-3a297a80-1d8a-11e9-8801-5e2d393bb122.png)

**Comment by speedytechdev** [comment]
Yeah, then it should be working fine. That black box is Blender running in the background and it means it is working. Just click the minimize to taskbar button.

**Comment by ctsdownloads** [comment]
Assuming Windows 7 32bit here. Solution - [needs Blender 2.80](https://download.blender.org/release/Blender2.80/blender-2.80-windows32.msi). Apparently newer versions come up as undetected when I run OpenShot from the command line during tests.

1) Try the latest version of OpenShot.
2) Use the [Blender package for 2.80](https://download.blender.org/release/Blender2.80/blender-2.80-windows32.msi)
