### ISSUE TITLE
Can It export to 4K

### ISSUE THREAD

**Issue by LewisGazzard** [OpenShot/openshot-qt#254]
Hi,
I have just purchased a 4k camera and am looking for some software to edit on the go on my small i5 laptop. This software seems great as it is not as demanding on resources as programs such as Premiere Pro.

BUT, the main thing for me is can it export in 4k?

This is really important as my clients want 4K video!

Thanks for the help!
Lewis.

**Comment by ankitpati** [comment]
[Yes](http://www.openshotvideo.com/2016/12/openshot-22-released-4k-video-editing.html "OpenShot 2.2"), it can.

Closing this as fixed.
