### ISSUE TITLE
No option for COLOURIZING VIDEO/SEPARATING COLOUR CHANNELS

### ISSUE THREAD

**Issue by DedTed** [OpenShot/openshot-qt#2541]
**Hey!**

I wanna colourize a little video snippet in my project to red. Unfortunately, there seems to be no option for this, even to separate the individual colour channels. Please help, I don't wanna export the snippet to another application.

**Comment by N3WWN** [comment]
I'm actually surprised that this is not available. 😮   @peanutbutterandcrackers or @DylanC can we get this added to the list of feature requests?  Seems it should be fairly straight-forward and may be able to be based on one of the other, existing effects.
