### ISSUE TITLE
How to make Blender and OpenShot work on Animated 3D Titles? How to properly edit/change settings? I can see in Preferences Blender command (path) showing blender. 

### ISSUE THREAD

**Issue by vickor01** [OpenShot/openshot-qt#2542]
**Please fill out this template** 

**My Question:**

**System Details**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.3]

**Screenshots**

**Comment by vickor01** [comment]
Windows 10, OpenShot v. 2.4.3.

**Comment by vickor01** [comment]
I can't use Animated 3D Titles. I receive a notification that Blender is required. In Preferences Blender command (path) shows Blender. And what? Anything else should be set or what?

**Comment by speedytechdev** [comment]
Can you take a screenshot of what it shows please.

**Comment by MrDrieze** [comment]
![geanimeerde titel](https://user-images.githubusercontent.com/46943475/51570169-a9908e80-1e9e-11e9-9d05-15c1294c04de.PNG)
![voorkeuren](https://user-images.githubusercontent.com/46943475/51570175-ae554280-1e9e-11e9-83e2-8a322e6c519a.PNG)
These are the notifications i get when i want to use the animated titles. 
What should i do?

**Comment by speedytechdev** [comment]
@vickor01 Sorry for getting back to you so late. Could you try and add blender.exe after the slash.

**Comment by vickor01** [comment]
Well, it worked - at least an effect can be seen, but it takes several minutes and a black windows pops up for several times. After the effect is seen and I click render nothing happens...

**Comment by speedytechdev** [comment]
@ferdnyc ^^

**Comment by speedytechdev** [comment]
@vickor01 Sorry forgot to tell you. So the black windows should show up which means the program is running. It is odd that it is not working so I have asked for some help to solve this issue.

**Comment by DylanC** [comment]
@vickor01 

Try v2.4.4, it has a browse button to easily select the blender.exe file and the full path will be correct. Make sure to point to the actual blender.exe file rather than just the blender folder like you were doing above.

![Screenshot from 2019-03-22 08-29-47](https://user-images.githubusercontent.com/4488048/54810004-cd910600-4c7c-11e9-8b27-ea4e0aec2061.png)
