### ISSUE TITLE
TSV Import audio sync

### ISSUE THREAD

**Issue by phunkz** [OpenShot/openshot-qt#2546]
imported TSV (recorded File in 1280x720 50p
audio and video not in sync after dragging the file to timeline

**System Details (please complete the following information):**
 windows 7 12GB RAM OpenShot Version [e.g. 2.4.3] + 2.4.3dev of today

**To Reproduce**
drag tsv to timline
play

**Expected behavior**
audio in sync

**Screenshots**
No

**Logs**
No

**Video Profile**
TSV 720p50

**Comment by ctsdownloads** [comment]
Old version of OpenShot. Closing as it's outdated.
