### ISSUE TITLE
Video not aligned to begin of timeline=> calculates start or end of renderarea wrong

### ISSUE THREAD

**Issue by phunkz** [OpenShot/openshot-qt#2547]
if i cut off the first five minutes of a 15 minutes video (without moving the video to begin of the timeline after cutting, the renderresult ist a 10! minute video with first 5 Minutes muted!

**System Details (please complete the following information):**
win7 12GB Ram - OpenShot Version 2.4.3 dev (today)

**To Reproduce**
cut off the first five minutesof a 15 minutes video (without moving the video to begin of the timeline only one track involved)
export video 720p50  

**Expected behavior**
Renderresult: A 15 Minutes video with beginning 5 minutes muted
or
a 10 minutes video without any muting

**Video Profile**
TSV 720p50

**Additional context**
I think it calculates the length of the renderarray based on the begin and end of the first/last clip but
starts rendering at beginn of the timeline. So it renders the empty 5 minutes at the start and loses the rest of 5 minutes  after the 10 minutes are rendered

Ive seen the lag on export also(reported by others) (profile 720 50p) even for very short videos of 30 seconds.

**Comment by ctsdownloads** [comment]
Old version of OpenShot. Closing as it's outdated.
