### ISSUE TITLE
OpenShot can not import /Open anything!

### ISSUE THREAD

**Issue by beshoo** [OpenShot/openshot-qt#2548]
**My Question:**
Simply I cannot import any mp4/avi/mp3 anything.... just freeze and not responding 

**System Details**
Windows 7 ultimate 32bit
4gb of RAM

 - OpenShot Version [e.g. 2.4.3]
OpenShot-v2.4.3-dev3-1547945882-7b6eb9c2-3861a2c5-x86.exe
**Screenshots**
https://vgy.me/auB1Po.png

**Comment by peanutbutterandcrackers** [comment]
Please [attach the logs](https://gist.github.com/peanutbutterandcrackers/d84c257e74b72d8b06b4daffaebc5a14). Thank you.
