### ISSUE TITLE
Linear Interpolation

### ISSUE THREAD

**Issue by AmyCourtney** [OpenShot/openshot-qt#2549]
Setting XY position to linear interpolation by default

Hello,

I was wondering if there is any way to set the default interpolation for XY position to linear? By default it is set to Bézier.

All my animations are linear and setting each one individually is very time consuming so I would appreciate your advice on a way to work around this. Alternatively, is there a way to select all key frames simultaneously and then choose linear interpolation?

Many thanks for your help!

**System Details**
 - Operating System: Windows 7
 - OpenShot Version: 2.4.3

**Comment by peanutbutterandcrackers** [comment]
Adding 'enhancement' label here.

It would be even better if there could be an `.openshotrc` file or something where one could define the default values for interpolation. Not only that, but being able to define default value for each type of interpolation (scale x and scale y would be linear, volume would be constant, etc. - just as some examples) in said file.

**Comment by creikey** [comment]
I could try to do something like this, would it be like a `constants.py` file that tries to find a config file in JSON called like `open-shot-config.json` in whatever platform dependant directory?

**Comment by peanutbutterandcrackers** [comment]
I was slightly wrong. There already is something akin to `.openshotrc` - `.openshot-qt/openshot.settings`; that would be the file to use.

@creikey - openshot.settings is pretty much a json file. I don't exactly know about the technical aspect of this, sorry. Perhaps there already is something file that reads the settings file?
