### ISSUE TITLE
Unable to Install Openshot

### ISSUE THREAD

**Issue by Nithin-Reddy** [OpenShot/openshot-qt#255]
I use KaOs, I have Executed this command`sudo chmod a+x OpenShot-2.0.7.AppImage`

and then, `./OpenShot-2.0.7.AppImage`, Unfortunately my Output is this:

`/tmp/.mount_Cjj0Q6/usr/bin/openshot-qt.wrapper
Loaded modules from current directory: /tmp/.mount_Cjj0Q6/usr/bin
Segmentation fault (core dumped)`

Have I tried the latest version?
Yes, 2.0.7

My system details are posted in this link.
https://gist.github.com/anonymous/12c09c90a2f1583948cdb26ecca627a5

**Comment by jonoomph** [comment]
The AppImage should work now, with our latest daily builds.  Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot's AppImage. If you still encounter errors, please reopen this ticket and attach the output from the AppImage. Thanks!
