### ISSUE TITLE
OpenShot 2.4.3-dev1 cannot start Blender 2.76b

### ISSUE THREAD

**Issue by AlexRealKzn** [OpenShot/openshot-qt#2550]
Hey. I am a junior at Linux. I used OpenShot and made titles by Openshot+Blender. 
Everything worked fine but today I got the trouble - OpenShot cannot launch Blender. It demands the correct path and the Openshot's version 2.78 or higher. I had changed nothing. What should I do? Thanks in advance.

 - Operating System Linux Mint 18.3
 - OpenShot Version 2.4.3
![_2019-01-21_16-42-32](https://user-images.githubusercontent.com/46894711/51478243-f8093480-1d9b-11e9-8539-bd6c5bd2d81c.png)

**Comment by AlexRealKzn** [comment]
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/2781379/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2781380/openshot-qt.log)
https://mega.nz/#F!dWwQUQyL
Thanks a lot in advance!

**Comment by dr0i** [comment]
On `ubuntu 20` and `OpenShot version 2.4.3` and  `blender 2.78` I discovered that an absolute path doesn't work - openshot always seems to *append* the path to blender to your home directory. So, only relative paths (starting from your home directory) are working.

**Comment by ctsdownloads** [comment]
No reply from author recently, assuming resolved and closing.
