### ISSUE TITLE
Orange and teal look

### ISSUE THREAD

**Issue by abastyr** [OpenShot/openshot-qt#2551]
**How to achieve the Orange&Teal look?**

Hello, first of all, sorry for bothering.

I am trying to achieve the cinematic look known as the Orange&Teal, which is commonly used in movies to create contrast. Normally this can be done by modifying the curves of the RGB channels, very similar to the second screenshot I have sent, but I cannot seem to find such an option in the OpenShot.

Is there any way how this effect could be achieved?

**System Details**
 - Operating System / Windows 10
 - OpenShot Version [e.g. 2.4.3]

**Screenshots**

![Orange and Teal showcase](https://lightroomtv.co.uk/wp-content/uploads/2018/04/Teal-Orange-Finished-Image-1024x683.jpg)

![RGB curves](https://www.gimp.org/tutorials/Basic_Color_Curves/curves-dialog-orangeteal-red-high.png)

**Comment by ctsdownloads** [comment]
Old version of OpenShot. Closing as it's outdated.
