### ISSUE TITLE
Changing keyframe type is also affecting previous keyframes

### ISSUE THREAD

**Issue by schauveau** [OpenShot/openshot-qt#2552]
**Please fill out this template** 

**Describe the bug**
When changing the type of the numerical keyframe (e.g. linear, bezier or constant) I noticed that the type of the previous keyframe is also changed. 

**System Details (please complete the following information):**
 - Operating System / Distro: Debian/buster
 - OpenShot Version 2.4.3

**To Reproduce**
1. In a video element, create 5 keyframes for the 'Scale X' property with the default type (Linear)
2. Move the cursor to the 3rd keyframe. The 'Scale X' name should turn green. 
3. Right click on the value and change its type to 'Constant'
4. Move the cursor to the 2nd keyframe (or anywere between the 1st and the 2nd keyframes) 
5. The type of 'Scale X' for the 2nd keyframe was also set to 'Constant' which is unexpected.

**Expected behavior**
Changing a keyframe type should NOT affect the previous keyframe.

**Workaround**
With that bug, changing the type of single keyframe X can be done as follow:
1. Insert a dummy keyframe before keyframe X. 
2. Edit the type of  keyframe X (Remark: the bug will affect the type of the dummy keyframe)
3. Remove the dummy keyframe

**Comment by peanutbutterandcrackers** [comment]
I can confirm. This is present.

However, this wasn't present before. So this must have slid in somehow. Certainly very strange.

It seems that only the keyframe immediately preceding the keyframe being modified is being affected, not the other ones.

**Comment by schauveau** [comment]
I had a quick look at the code. There is a function value_updated in file properties_model.py
There is a 'for point' loop within which the value of point["interpolation"] is updated at 2 different locations for previous_point_x and closest_point_x.
https://github.com/OpenShot/openshot-qt/blob/develop/src/windows/models/properties_model.py#L443

I commented out the first instance (so for previous_point_x) and that seems to fix the bug at least for switching between 'linear' and 'constant' interpolation. The new interpolation is now applied to the current or to the next keyframe point.

Remark: There is one exception. When the interpolation is changed after the last keyframe point, the modification is applied to that last keyframe point so BEFORE the requested location. That probably makes sense but this is a bit confusing. In fact, there no transition is taking place after the last keyframe so should not provide the Bezier, Linear and Constant entries. This is already the case when there are no keyframes and so no transitions in the whole segment. 

I am not sure if the assignments to point["handle_right"] should also be commented out. They are obviously related to the Bezier interpolation but I could not figure out if those values are really used (dead code?).

**Comment by peanutbutterandcrackers** [comment]
Hmm.... I will try to get the devs' attention to this then. Thank you for digging things out. You're awesome! :+1:
