### ISSUE TITLE
Provide a way to shrink timeline

### ISSUE THREAD

**Issue by schauveau** [OpenShot/openshot-qt#2553]
**Please fill out this template** 

**Is your feature request related to a problem? Please describe.**

It seems that the length of the timeline can only grow (when adding elements) but cannot shrink when removing elements. This is annoying because temporarily adding a large video (to only keep a chunk) causes the timeline to expand and so the timeline horizontal scrollbar to shrink to a minuscule size.  

Saving and reloading the project does not help. 

My only workaround is to manually change a 'Duration' value in the project file. 
 
**Describe the solution you'd like**
Ideally, the length of the timeline should be adjusted down when the 'last' element is removed (or clipped).  
 
**Describe alternatives you've considered**

The timeline resizing could also occur when loading the project file. That is not perfect but that would be good enough.
 
If a fully automated approach is not feasible then a 'Shrink Timeline' entry could be added in the menus.

**Comment by ctsdownloads** [comment]
Time line size is moot as the export process only renders the time line area that contains content. 

Old version of OpenShot. Closing as it's outdated.

**Comment by ferdnyc** [comment]
> Time line size is moot 

it's kind of not, though. As @schauveau notes, it:

> causes the timeline to expand and so the timeline horizontal scrollbar to shrink to a minuscule size.

Currently the timeline does, indeed, only ever grow ­— and every time it does, a `"duration"` property is updated in the project data that ensures the max length will be preserved for the life of the project.

But the point that export only renders the occupied length of the timeline is a good one: If we have the logic to compute that already, for _export_, why couldn't we also apply it when saving the project, and/or loading it, to readjust the stored duration?

**Comment by dukeman74** [comment]
I can't find a newer mention of this problem, but it very much still seems to be a problem.
blank video is not exported, but it becomes difficult to work with short clips that are pulled out of very long ones.
Trying to pull the interesting 40 seconds out of a 24 hour long security footage quickly makes 
<img width="1421" height="61" alt="Image" src="https://github.com/user-attachments/assets/5d040f97-0a09-48ad-8b60-49b7385ba3f9" />
a situation like this, where this ui element is useless.

it's also unclear which is the correct "duration" to edit in the project file.

**Comment by Colorjet3** [comment]
If you are running OpenShot v3.4.0, you can:
1.  Zoom out of the timeline until you see the end of the timeline.
2.  Hover your mouse at the end of the timeline and when the mouse turns to left/righ arrow, click and hold and drag the end of the track to the left to shrink it.   Or, to the right if you want to expand it.

Another option is to double click the zoom slider that is right above the timeline.
