### ISSUE TITLE
Can't change resolution

### ISSUE THREAD

**Issue by crypto-ali** [OpenShot/openshot-qt#2554]
**Please fill out this template** 

**My Question:**

I am trying to lower the resolution on a couple of videos. But whenever I change the profile to the desired lower resolution, add the video file, and export. It exports a video of the same resolution and file size. I've even tried it at an even lower resolution. Same result: same resolution and same file size.

I have followed this piece of info from the User Guide:

Project Profile
The project profile is used when previewing your project and editing. The default project profile is “HD 720p 24fps”. It is best practice to always switch to your target profile before you begin editing. For example, if you are targeting 1080p 30fps, switch to that profile before you begin editing your project.

It is not working for me. What am I missing?

**System Details**
 - Operating System / Distro: [Ubuntu 18.04 - Lubuntu Desktop]
 - OpenShot Version [2.4.3-dev1]

**Screenshots**

**Comment by ctsdownloads** [comment]
User needs to make sure they're also exporting in the same resolution as their profile. And, set their profile not just in Preferences, but also using the icon to Choose Profile next to add media icon at the top. Then render in the same resolution/fps.

Old version of OpenShot. Closing as it's outdated.
