### ISSUE TITLE
Repetition of video start and slow frame rate

### ISSUE THREAD

**Issue by jonnygwhizz** [OpenShot/openshot-qt#2556]
**Please fill out this template** 

**My Question:**

Regardless if I use a title sequence or just go straight to a video clip, the frame rate takes ages to catch up in preview. The first clip starts playing very VERY slowly, then after the initial slow couple of seconds, the video playback plays the first couple of seconds of the first clip again at normal speed.
The rest of the video plays without a hitch afterwards. 
Help!

**System Details**
 - Operating System / Distro: [Windows 10]
 - OpenShot Version [ 2.4.3]

**Screenshots**

**Comment by ctsdownloads** [comment]
User needs to use [this approach](https://vimeo.com/420117641) to make editing more smooth. 

Old version of OpenShot. Closing as it's outdated.
