### ISSUE TITLE
Alpha Mask won't show the last file in Project Files as a Source option.

### ISSUE THREAD

**Issue by LawrenceSmall** [OpenShot/openshot-qt#2559]
**Describe the bug**
When trying to set the source file of an Alpha Mask, the last file of the Project Files list is not shown in the Source context menu.  Adding or removing files will adjust the context menu list, so the last file is always missing.

**System Details (please complete the following information):**
 - Operating System / Distro: Windows 10 Home, 64-bit, version 1809
 - OpenShot Version 2.4.3

**To Reproduce**
Add some images to your project files.
Put one on the timeline as a clip.
Add an Alpha Mask to the clip.
Go to mask properties, right-click on Source, and view the Files list.
The bottom Project File won't be listed.

**Expected behavior**
All files to be listed.

**Screenshots**
"Using MIPAR Blank.PNG" should be at the bottom of the Source Files list.
![capture](https://user-images.githubusercontent.com/40901537/51711628-94307700-1ffa-11e9-8668-3baedf71aea6.PNG)

**Comment by ctsdownloads** [comment]
Old version of OpenShot. Closing as it's outdated.
