### ISSUE TITLE
OpenShot 2.0.7 fails to start on Ubuntu 14.04.1

### ISSUE THREAD

**Issue by harro-mirbach** [OpenShot/openshot-qt#256]
Hello,

I've just installed OpenShot-QT 2.0.7 from the PPA. 
apt-get reported the insrtallation as OK

When i try to start with `openshot-qt &` on the shell I'll get the error:

```
harro@xxxxxxxx:~$ Traceback (most recent call last):
  File "/usr/bin/openshot-qt", line 5, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named 'pkg_resources'
```

My distribution: 

```
harro@xxxxxxxxx:~$ uname -a
Linux ubuntu-srv.home 3.19.0-33-generic #38~14.04.1-Ubuntu SMP Fri Nov 6 18:17:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

My DISPLAY is redirected to a remote X-Server, while my server has no desktop environmant installed.
`export DISPLAY=xxx.xxx.xxx.xxx:0
`

The OpenShot 1.4 from the ubuntu trusty repository was working.

How can I fix this error?

Thanks and Best Regards

Harro

**Comment by jreynojustin** [comment]
OpenShot is now in Version 2.2 if you are still noticing issues in the latest version please re-open this issue letting us know.
