### ISSUE TITLE
The program does not run, please help.

### ISSUE THREAD

**Issue by cdanca** [OpenShot/openshot-qt#2560]
**Describe the bug**
When I try to open the Application, it seems that it´s going to start but nothing happens...

**System Details
- MacBook Pro (15-inch, Early 2011)
  OS X Yosemite Version 10.10.5 
  processor 2.2 GHz Intel Core i7
  Memory 8 GB 1600 MHz DDR3
  Graphics AMD Radeon HD 6750M 1024 MB

**To Reproduce**
1. Try to run the Application

**Expected behavior**
I expect the program to run

**Screenshots**
I´ve added a zipped video file "NothingHappens.mov.zip"

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Video Profile**
 N/A

**Additional context**
 N/A.

Thank you very much.

[NothingHappens.mov.zip](https://github.com/OpenShot/openshot-qt/files/2795799/NothingHappens.mov.zip)

**Comment by jmperrier** [comment]
Got the same problem here... Any solution??
