### ISSUE TITLE
Imported video has wrong starting point and can't change the starting point.

### ISSUE THREAD

**Issue by jmeyer1980** [OpenShot/openshot-qt#2561]
**Please fill out this template** 

**Describe the bug**
Importing an unedited clip that I tried to edit before a crash, now imports incorrectly. 

**System Details (please complete the following information):**
 - Windows 10
 - OpenShot Version 2.4.3

**To Reproduce**
1. Open OpenShot
2. Drag source video onto timeline
3. Scrub to seek a specific time where you want to slice
4. Hit play to check because scrub playback is glitchy...
5. Application hangs
6. Force-close application
7. Re-open application
8. Drag media back onto timeline
9. See that media has a new starting point and freak out
10. playback original media in VLC or another video playback application to confirm that it is unedited.

**Expected behavior**
I expected to be able to scrub to a certain point in the timeline smoothly, be able to slice the media, and continue editing without issue...

Instead, I had trouble scrubbing and now cannot use OpenShot because it refuses to import my file with the correct starting time. I have verified that the starting time showing in the media is 0:00, but the actual frame showing in the preview would actually be located in the middle of the media.

**Comment by ctsdownloads** [comment]
Old version of OpenShot. Closing as it's outdated.
