### ISSUE TITLE
How to slide a title from right to left?

### ISSUE THREAD

**Issue by gmolledaj** [OpenShot/openshot-qt#2563]
**Please fill out this template** 

**My Question:**
How to slide a title from right to left? If the title is long and it does not fit completely on the screen, it is necessary to start reading from the left and therefore it must be moved from right to left.
¿Cómo deslizar un título de derecha a izquierda? Si el título es largo y no cabe completo en la pantalla, es necesario empezar a leer desde la izquierda y por ello debe desplazarse en sentido derecha a  izquierda.
Kiel oni povas tragliti titolon de dekstra al maldekstra? Se la titolo estas longa kaj ĝi ne taŭgas tute sur la ekrano, necesas komenci leganta de la maldekstra kaj sekve ĝi devas esti movita de dekstre al maldekstre.

**System Details**
 - Operating System / Distro: [Windows 8.1]
 - OpenShot Version [2.4.3]

**Screenshots**

**Comment by peanutbutterandcrackers** [comment]
By using `location x` property. You might want to read this first: https://gist.github.com/peanutbutterandcrackers/f0f666243133e0ed25abbc12a4ba23d7/

Hope that helps!

**Comment by gmolledaj** [comment]
Thanks. 
Pasos: crea el título animado con el texto moviéndose de izquierda a derecha. Lo añades al proyecto en la pista que quieras.  Le pulsas encima con el botón derecho del ratón y eliges TIME - Normal - Backward - 1X. Ya está, eso es todo.
