### ISSUE TITLE
Crashes when importing

### ISSUE THREAD

**Issue by johnnymix** [OpenShot/openshot-qt#2564]
**Please fill out this template** 

**Describe the bug**
The application crashes every time I attempt loading a file.

**System Details (please complete the following information):**
Mac OS Hig Sierra
 - OpenShot Version 2.4.3-dev3

**To Reproduce**
1. Go to import file
2. Click on selected file

**Expected behavior**
Program closes completely
**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Video Profile**
If the problems you are experiencing are known to be, or may possibly be, related
to a specific format video file being used in OpenShot, please consider generating
a [MediaInfo](https://mediaarea.net/en/MediaInfo) profile and including it with your
report. Select View > Text from the menu to bring up a plaintext report, and attach
or paste it into this report. (If copy/pasting, consider adding the profile as an
additional comment after you post this initial report.)

**Additional context**

**Comment by cambrogers** [comment]
I'm having the same issue.  I'm trying to add my mp4 video to the project files and Openshot shuts down.  there is no error or warning or anything.  I can however import a picture.  What do I have to convert an mp4 file to inorder to add it to my project files list?

**Comment by Erudition** [comment]
Same issue here.
