### ISSUE TITLE
Headphones don't work IN program

### ISSUE THREAD

**Issue by Raziel0315** [OpenShot/openshot-qt#2565]
**Describe the bug**
The audio only comes out of the system speakers even though headphones are plugged in.

**System Details (please complete the following information):**
 - Operating System  Windows 10
 - OpenShot Version  2.4.3

**To Reproduce**
Pretty easy to reproduce: plug in headphones. Start a video.  Sounds comes out through system speakers.

**Expected behavior**
Sound should come through headphones.

**Comment by Raziel0315** [comment]
I should add that the headphones work for every other sound-related program on the system.  The headphones also work on other devices besides the computer.  The headphones are logitech, mic/headphones combo.

**Comment by speedytechdev** [comment]
@DylanC Did you not fix an issue similar to this.

**Comment by Raziel0315** [comment]
If someone else DID solve it, I wasn't able to find it.
However, I just figured out how to fix it.
The program seems to work like the Audactiy voice recording program.
All you have to do is plug the headphones in BEFORE starting the program.
At least, that's what worked for me.
The program is a hell of a lot easier to use when you can hear it.

**Comment by DylanC** [comment]
@speedytechdev - Nope, I didn't. As @Raziel0315 found out this just has some unusual behavior. There may be a reason why it works like this but I'm not 100% sure.

**Comment by Raziel0315** [comment]
Tested again: audio still comes through headphones so long as you plug them in BEFORE starting Openshot.

**Comment by Tamanders** [comment]
I am also having this issue.  I tried plugging in the headphones (Logitech G35 Gaming Headset) before starting Openshot.  No joy.  I tried restarting my computer with the headphones plugged in and then starting Openshot.  No joy.  The headphones have worked in the past with Openshot, not really sure what the problem is.

**Comment by speedytechdev** [comment]
I tested this and it seems to be a common issue.

**Comment by joeybisme** [comment]
Good day.  I had a similar issue.  I used my Beats Wireless headphones to edit my videos on OpenShot.  A couple days ago, the audio to my headphones would not work through OpenShot but every other application worked fine.  I attempted to do as above and open the app after powering on/syncing the headphones.  No dice.  I unplugged my video microphone and, viola, OpenShot sends audio to headphones now.

**Comment by xPapay** [comment]
> Tested again: audio still comes through headphones so long as you plug them in BEFORE starting Openshot.

Thanks! This helped. 👍

**Comment by joeybisme** [comment]
I fixed the issue.  I have to to start the app withOUT headphones then
start the app and NOT vice versa.

Thanks,
Joey

**Comment by DanPinGF** [comment]
You may be aware of the common effects of removing an in-use audio output device as stated in #4303.
