### ISSUE TITLE
hyperlink in videos

### ISSUE THREAD

**Issue by dale2k9** [OpenShot/openshot-qt#2569]
I was going to post this on the forum but it appears to be broken with MySQL errors. 
On youtube, I see a lot of videos with links that display inside the video to the video owner's either updated  or related content.  Is it possible to put in hyperlinked text using open-shot?  If a video is part of a group of related content, I'd like to put a list that content as hyperlinks at the beginning and end of the video.  This will help me to keep my videos short, linking to related videos instead of combining related videos.

**Comment by DylanC** [comment]
@dale2k9 - I'm pretty sure you need to use the Youtube online editor to do this. Openshot would not be able to do something like that as far as I know.
