### ISSUE TITLE
How to apply Fade In/Out to multiple clips or set as default? 

### ISSUE THREAD

**Issue by steven-1227** [OpenShot/openshot-qt#2570]
**Please fill out this template** 

**My Question:**
I just started using OpenShot - made me abandon Adobe Premiere Elements - *love* it for my simple needs - 90% stitching related video clips together.
For my simple needs, I'm not really interested in using the fancy transitions etc. (yet).
I just want to quickly take 5-10 clips, paste them in, and apply the Fade In/Out (Fast) on each clip.

a) is there a way to apply the Fade to multiple clips at the same time? 

b) alternatively, is there a way to template or default the clips importation to have that fade applied as soon as it's dragged onto the timeline? 

Thanks
-steve

**System Details**
 - Operating System / Distro: Windows 10 Home Edition Build 17134.rs4 
 - OpenShot Version 2.4.3

**Comment by nanohtpc** [comment]
Same request here..

**Comment by DylanC** [comment]
@steven-1227 @nanohtpc 

a) Drag your mouse over multiple clips to select them. Right click and click the fade option you want.
b) Nope. I think you can default the clip length though.

**Comment by blackdc2** [comment]
> @steven-1227 @nanohtpc
> 
> a) Drag your mouse over multiple clips to select them. Right click and click the fade option you want.

Hi, I am new to Openshot, I have tried the method described above (all the clips turn red when i select them), however the fade setting is only applied to the clip which I right click on. The effect is not applied to any of the others which are also selected.
