### ISSUE TITLE
Are Openshot forums no longer?

### ISSUE THREAD

**Issue by dale2k9** [OpenShot/openshot-qt#2575]
Yesterday I was going to post on the Openshot forums but I was getting MySQL errors returned from the forum app.  Today I thought I'd try again and when I went to the Visit Forums link from the Support menu, which points to http://openshotusers.com/forum/, I get an http 404 (not found) error.

Are they having technical issues or is this the place I should ask questions that might have otherwise gone to the forums?

**Comment by DylanC** [comment]
@dale2k9 - I'm pretty sure its closed due to technical issues.
