### ISSUE TITLE
the videos down load from MP4 to openshot do not appear complete

### ISSUE THREAD

**Issue by Alirioe** [OpenShot/openshot-qt#2576]
**Please fill out this template** 

**My Question:**
the openshot are cutting the top part of the video.

**System Details**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.3]

**Screenshots**

**Comment by ctsdownloads** [comment]
Old version of OpenShot. Closing as it's outdated.
