### ISSUE TITLE
Will no longer Export

### ISSUE THREAD

**Issue by FairyTailFanTaji** [OpenShot/openshot-qt#2578]
**Describe the bug**
The application will no longer export my video.

**System Details:**
 - Operating System / Distro: Windows 10
 - OpenShot Version 2.4.3

**Steps to reproduce the behavior:**
1. Exported first video.
2. Fixed a mistake in the video.
3. Clicked "Export Video".
4. Nothing happens.

**Expected behavior**
I expected to be able to re-export my video to fix the mistake I made.

Can anyone help me fix this? I just got the application today.

**Comment by ctsdownloads** [comment]
Old version of OpenShot. Closing as it's outdated.
