### ISSUE TITLE
how do i remove part of a clip

### ISSUE THREAD

**Issue by BigDumDum** [OpenShot/openshot-qt#2579]
**Please fill out this template** 

**My Question:**

**System Details**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.3]

**Screenshots**

**Comment by ralatgit** [comment]
I have marked the beginning and end of the first segment I want to keep of  a project file. How do I delete everything up to the first marker?

**Comment by DylanC** [comment]
@BigDumDum @ralatgit - Use the slice tool (scissors icon) to break the clip into smaller parts. Then select the parts you want to delete with the mouse and press the delete button.

This guide might help:
https://www.openshot.org/static/files/user-guide/clips.html#cutting-slicing
