### ISSUE TITLE
Crash on Ubuntu 14.04 whenever the time options are manipulated

### ISSUE THREAD

**Issue by haudren** [OpenShot/openshot-qt#258]
I installed openshot 2.0.7 on Ubuntu 14.04 from the ppa. I opened a new project, added a single ".mov" [video file](https://www.videezy.com/random-objects/2769-dollar-bills-money-being-counted-by-hand).

The software crashes whenever I try to:
- Change the speed by using the context menu
- Change the "time" property from the properties panel.

Note that the bug only appears if I try to change this property first. I tried to first change the scale of the video, then accelerate it, and it worked, but the software crashed soon after while I was seeking in the clip.

This may be related to #199 and/or #196 .

I attach a log: https://gist.github.com/haudren/d9875226f730d93a8f7259138be37c48

**Comment by jreynojustin** [comment]
OpenShot is now in Version 2.2 if you are still noticing issues in the latest version please re-open this issue letting us know.

**Comment by haudren** [comment]
It looks like this has been fixed in 2.2, I don't get the same crash as before :)

**Comment by jreynojustin** [comment]
Great!
