### ISSUE TITLE
Adding MP4 to project crashes gnome session

### ISSUE THREAD

**Issue by sporkfighter** [OpenShot/openshot-qt#2583]
Adding mp4 files to project causes immediate crash of gnome, requiring me to log in again.

 - Operating System / Distro: Fedora 29/gnome
 - OpenShot Version 2.4.3

**To Reproduce**
1. Open Openshot
2. Click on '+' to select mp4 files.
3. Select mp3 files.
4. Watch the black screen, then log into gnome again.

**Expected behavior**
Add files to project and continue.

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Video Profile**
If the problems you are experiencing are known to be, or may possibly be, related
to a specific format video file being used in OpenShot, please consider generating
a [MediaInfo](https://mediaarea.net/en/MediaInfo) profile and including it with your
report. Select View > Text from the menu to bring up a plaintext report, and attach
or paste it into this report. (If copy/pasting, consider adding the profile as an
additional comment after you post this initial report.)

**Additional context**

**Comment by ctsdownloads** [comment]
Old version of OpenShot. Closing as it's outdated.
