### ISSUE TITLE
Unable to add title

### ISSUE THREAD

**Issue by onaccident** [OpenShot/openshot-qt#2585]
**Describe the bug**
Unable to add title bar 

**System Details (please complete the following information):**
 - Operating System Windows 10
 - OpenShot Version 2.4.3

**To Reproduce**
1. Open "openshot"
2. Click on 'title
3. Scroll down to title (ctl T"
4. click save upon selecting title bar

**Expected behavior**
a title to appear in the tracks per the preview image

**Comment by ctsdownloads** [comment]
Make sure Inkscape is installed, path is set in preferences. 
Old version of OpenShot. Closing as it's outdated.
