### ISSUE TITLE
Cropped imported video

### ISSUE THREAD

**Issue by adavidi** [OpenShot/openshot-qt#2586]
**Describe the bug**
When I import a video it is cropped (top and bottom)

**System Details (please complete the following information):**
Windows 10
OpenShot Version 2.4.3

**To Reproduce**
I've taken a portrait video with my IPhone (6s), then downloaded it to my computer and imported it to OpenShot.
The video was cropped (top and bottom)
When I play the video in VLC it looks fine (not cropped)

**Expected behavior**
I would like the video to be the same as the original

**Screenshots**
The screenshot is of the importing dialog window, you can see the original video in full, but when imported it is cropped
![image](https://user-images.githubusercontent.com/47348070/52261113-f6f60c80-2930-11e9-81ab-2649d1dd5dd3.png)

**Comment by jwyseu** [comment]
See https://github.com/OpenShot/openshot-qt/issues/2649
Preview will still not be ok but at least the output works
