### ISSUE TITLE
Render regions

### ISSUE THREAD

**Issue by Hit-Bug-zz** [OpenShot/openshot-qt#259]
I've been wondering, is this software able to render regions on a timeline? That would be a very nice feature since I do not want to clutter my projects. I've been wanting to completely move to the open scene however there are software that lack features that I cannot move away from.

**Comment by jarlarntzen** [comment]
Could you clarify a little bit regarding "rendering regions on a timeline"?

**Comment by MrHuds0n** [comment]
"Region rendering" usually refers to the ability of rendering multiple sections of the same project to separate files. I suppose that's what the question here is.
