### ISSUE TITLE
[Win10] Cannot open track properties

### ISSUE THREAD

**Issue by lobneroO** [OpenShot/openshot-qt#2590]
**Describe the bug**
When selecting a track, opening the context menu via right-click and choosing "Properties", nothing happens (same goes for using Ctrl+I as a shortcut). It should open the properties window for the track (or rather the selected part of the track).

**System Details (please complete the following information):**
 - Win10 Pro Version 1803 Build 17134.523
 - OpenShot Version 2.4.3

**To Reproduce**
1. Create a new project
2. Add a video to one of the tracks
3. Right click on the video file on the track to open the context menu and choose "Properties"
4. Nothing happens

**Expected behavior**
A window with the properties of the track/part of the track should open

**Logs**
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2833663/openshot-qt.log)

**Comment by Rofloki** [comment]
I am having the same issue.
