### ISSUE TITLE
sorry there was an error exporting your video: could not open or write file

### ISSUE THREAD

**Issue by Guitanguran** [OpenShot/openshot-qt#2591]
**Please fill out this template** 

**Describe the bug**
I get error message when trying to export video

**System Details (please complete the following information):**
 - Operating System / Windows 10
 - OpenShot Version 2.4.3

**To Reproduce**
1. Go to '...'export video
2. Click on '....' export video 
3. See error

**Expected behavior**
I expected a dialogue box on saving file as Mp4

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Video Profile**
If the problems you are experiencing are known to be, or may possibly be, related
to a specific format video file being used in OpenShot, please consider generating
a [MediaInfo](https://mediaarea.net/en/MediaInfo) profile and including it with your
report. Select View > Text from the menu to bring up a plaintext report, and attach
or paste it into this report. (If copy/pasting, consider adding the profile as an
additional comment after you post this initial report.)

**Additional context**

**Comment by ctsdownloads** [comment]
Old version of OpenShot. Closing as it's outdated.
