### ISSUE TITLE
Error when openning a saved file

### ISSUE THREAD

**Issue by Ishimurandrs** [OpenShot/openshot-qt#2593]
When I try to open a saved project, this message appears:

>  Failed to load project file C:/Users/Videos/project.osp: invalid load key, '{'.    <

These are my system settings 
 - Windows 10 with x64 bits 
 - Openshot 2.4.3 (I also tried with 2.4.2)

Please, I really need your help, this is an important project to me, thanks in advance

**Comment by NonnaF** [comment]
I can´t open the saved file, I get messade "xxfile is not found" and then the whole program shuts down.
