### ISSUE TITLE
timeline fullscreen

### ISSUE THREAD

**Issue by JeremackYT** [OpenShot/openshot-qt#2598]
**Please fill out this template** 

**Describe the bug**
I clicked fullscreen on the timeline and I can't un-fullscreen the timeline.  I WANT TO SEE THE OTHER THINGS.

**System Details (please complete the following information):**
 - Windows 10 64 bit
 - OpenShot Version i dont know
![2019-02-08 1](https://user-images.githubusercontent.com/47464517/52510633-ff14ad00-2bb9-11e9-9625-4ef1edb312b7.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Video Profile**
If the problems you are experiencing are known to be, or may possibly be, related
to a specific format video file being used in OpenShot, please consider generating
a [MediaInfo](https://mediaarea.net/en/MediaInfo) profile and including it with your
report. Select View > Text from the menu to bring up a plaintext report, and attach
or paste it into this report. (If copy/pasting, consider adding the profile as an
additional comment after you post this initial report.)

**Additional context**

**Comment by peanutbutterandcrackers** [comment]
`View` > `Views` > `Simple View`
