### ISSUE TITLE
Missing key for removing clip from timeline

### ISSUE THREAD

**Issue by jarlarntzen** [OpenShot/openshot-qt#26]
I'm constantly missing using **backspace** or **delete** key for deleting clips from the timeline. Right-click --> Remove clip is reasonable of course but it's still too cumbersome and I do really expect for something like the delete-key to work.

Thanks!

**Comment by nwgat** [comment]
more keyboard shortcuts! :+1:

**Comment by jonoomph** [comment]
Delete key now removes any selected transitions and clips. Nice suggestion. =)

**Comment by jarlarntzen** [comment]
:+1:

**Comment by jarlarntzen** [comment]
Thanks, Jonathan! This now works wonderfully on my Ubuntu 14.04 LTS, which has a full keyboard including a delete key and numpad. Now, it does not work as well on my MacBook Pro which doesn't have a Delete key.

I would recommend adding the Backspace key in addition to the Delete key for all kinds of deletions: clips, imported files, transitions etc. Very fast, natural and easy to use.

Thanks.
