### ISSUE TITLE
Openshot Crashes in Linux 16.04 and Windows 10

### ISSUE THREAD

**Issue by walkingcedar** [OpenShot/openshot-qt#260]
I managed to get 80% of the way through a video project I was working on, and--rather suddenly--Openshot 2.0.7 stopped working properly. It would fade in and out. Ultimately, it crashes when I hit the play button. It stopped displaying the video imagery in the window display. It cannot render the video (export) as it comes up with this: "Sorry, there was an error exporting video: exception class 'openshot.Reader.Closed'" This is the EXACT issue I ran into in Windows 10, as well. In Linux, there seems to be some sort of Library issue. Here is what it says in Windows 10 when I try to play my .OSP file: 
"Runtime Error!"
This application has requested the Runtime to terminate in an unusual way. Launch.exe has stopped working. A problem caused the program to stop working correctly. 

No matter what I do, I cannot get Openshot to work properly and finish my project--not in Ubuntu (be it 14.04, 16.04) or Windows. I have to start all over. I am incredibly disappointed in the 2.0.7 release, as you all stated the crash issue had been fixed. This problem just won't go away. I am going to have to switch to Kdenlive and start my project all over. This is upsetting and disappointing, to say the least. I am not likely to return to Openshot as a result. I am, 90% of the time, a Linux Ubuntu user. This whole fiasco with Openshot just kills me. I know you all are trying, but it crashed at the wrong time for me, and I cannot restore it.

**Comment by wgmitchener** [comment]
I see a lot of crashes in Fedora 24 as well.

- I tried the .AppImage files, and they segfault on startup.

- The executable packaged as RPMs from rpmfusion sort of works, but if I click anywhere on the time bar or try to drag the time cursor, it crashes.

**Comment by lostcontrol** [comment]
Also had many crashes yesterday with Openshot 2.1 while trying to render my video edit. Seems openshot or libopenshot is leaking a lot memory. Takes about 4GB of RAM (for 1 clip of 4 minutes with just a title and a mp3) before crashing.

**Comment by apraetor** [comment]
I am running Windows 10 64bit with 16 GB of RAM. After running for ~30 minutes and getting to 34% Windows terminates Launch.exe with event name RADAR_PRE_LEAK_64. From what I can find online this means Windows believes the program has crashed and is consuming excessive memory resources. When this occurs the system is at 50% memory utilization.

**Comment by PanderMusubi** [comment]
See also https://github.com/OpenShot/openshot-qt/issues/277

**Comment by jonoomph** [comment]
We have recently made a ton of improvements for video freezing and crashes, and I would like to verify this issue still occurs with our latest daily build. Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot. 

If the issue still occurs, please reopen this issue and attach log files (https://github.com/OpenShot/openshot-qt/blob/master/.github/CONTRIBUTING.md), and hopefully we'll be able to nail this down and fix it. Thanks!

**Comment by elmissnid** [comment]
I'm a Linux user from 9 years this app not usable till now it just crash never completed a 2 minutes clip just crash in 34%, and Wasted a 2 hour of hard work, it utilize all the RAM still stuck and crash I have an I7 with 8GB of ram 

what is the developer thinking just not usable, I just loose the hope of this project waiting for a long time?

I recommend the developer stop the openshit and work in selling hot corn

**Comment by mgrigajtis** [comment]
Just installed it in Windows 10, crashes like crazy.

**Comment by peanutbutterandcrackers** [comment]
Just an update: OpenShot is getting better - slowly by slowly. Here's something I worked really hard on to create. Yes, it wasn't a walk in the park. But we are, collectively, doing our bit to make OpenShot better. :)

![meet tux](https://user-images.githubusercontent.com/26764547/48016787-a1a13800-e154-11e8-9f1d-bfe2a64a6ad4.gif)
