### ISSUE TITLE
no file details in project file pane view in details view

### ISSUE THREAD

**Issue by psturgis** [OpenShot/openshot-qt#2600]
**Please fill out this template** 

**My Question:**
How can I get the details of the files I have added to the project files pane. There are not visiable in the detailed view.
Only the name is showed.

**System Details**
 - Operating System /Windows 10
 - OpenShot Version [ 2.4.3]

**Screenshots**
![knipsel](https://user-images.githubusercontent.com/8074558/52524290-a3baeb80-2c9b-11e9-96b6-576624f35486.PNG)

**Comment by ctsdownloads** [comment]
View, views, Simple View. The right click on the clip, properties.
Old version of OpenShot. Closing as it's outdated.
