### ISSUE TITLE
No sound in preview

### ISSUE THREAD

**Issue by Veikka11** [OpenShot/openshot-qt#2606]
**Please fill out this template** 

**My Question:**
Why can´t i hear the video sound on preview?

**System Details**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.3]

**Screenshots**

**Comment by ctsdownloads** [comment]
Check sound card, headphones or similar. Is the correct audio device in your operating system selected for playback.

Old version of OpenShot. Closing as it's outdated.
