### ISSUE TITLE
[bug] doesn't work

### ISSUE THREAD

**Issue by azerty06530** [OpenShot/openshot-qt#2607]
**Please fill out this template** 

**Describe the bug**
The application simply doesn't work at all... I tried thousands of time tu import a video I want to split/cut. But nothing appear on the screen the same screen with the effects. 

**System Details (please complete the following information):**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.3]

**To Reproduce**

**Expected behavior**
a BETTER application and BETTER explanation on how to use it. The tutorial is super useless and doesn't help at all ... So it has to be improved ... Why it has to be difficult to use it? seriously think about it when you do an application.

**Screenshots**
![image](https://user-images.githubusercontent.com/47568726/52655589-c4ca4900-2ef4-11e9-9eaf-964a2a6b8483.png)

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Video Profile**
If the problems you are experiencing are known to be, or may possibly be, related
to a specific format video file being used in OpenShot, please consider generating
a [MediaInfo](https://mediaarea.net/en/MediaInfo) profile and including it with your
report. Select View > Text from the menu to bring up a plaintext report, and attach
or paste it into this report. (If copy/pasting, consider adding the profile as an
additional comment after you post this initial report.)

**Additional context**

**Comment by mokahless** [comment]
Please actually fill in the template for your bug report so the devs can clearly see the issue you are experiencing.
