### ISSUE TITLE
Export video keep crashing

### ISSUE THREAD

**Issue by jonehodne** [OpenShot/openshot-qt#2610]
Hi, 

Have a problem with export keeps crashing around 64%. libipenshot are too big to submit so at the moment only attached the openshot file. Is it possible to read anything from this that might help the problem? Im running on a windows 10 64bit computerr. Heard that it have been problems with this. Is there any workarounds?

Tried latest build:
OpenShot-v2.4.3-dev3-1549992080-62fa7176-2f74da2f-x86_64.exe (64-bit)

[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2857924/openshot-qt.log)

Any help is greatly appreciated,

Regards,

Jone Hodne

**Comment by ctsdownloads** [comment]
Old version of OpenShot. Closing as it's outdated.
