### ISSUE TITLE
Openshot 2.4.3 speed

### ISSUE THREAD

**Issue by lewjoubert** [OpenShot/openshot-qt#2617]
Is there a way to adjust speed other than from the fixed selection?
The problem I have is that I am converting super 8mm film, and I need to reduce the playback speed in OpenShot by 0.6 to obtain the correct rate.
Any ideas?

**Comment by N3WWN** [comment]
@lewjoubert Take a look at my comment that I posted at 
https://github.com/OpenShot/libopenshot/issues/176#issuecomment-442466083 .  That should give you all you need to know to arbitrarily adjust the playback speed.

**Comment by poszy6** [comment]
For me this isnt working at all. When I seleck the time -> fast -> forward -> 2X (or any of the values) the clip shrinks, but when I try to play it, it froze and lag.  I think when you use 2X(or other) OpenShot calculate the new time value for you ( its just a hunch ).

**Comment by SuslikV** [comment]
@poszy6 Are you bot?

**Comment by poszy6** [comment]
Sure.. no. I am pissed and used copi paste like an angry guy

**Comment by poszy6** [comment]
Are you a bot?

**Comment by SuslikV** [comment]
Just export the file and playback it. The 2X speed works OK in the latest build of OpenShot. The algorithm is not perfect (you see it as slow processing) but it works.

**Comment by lewjoubert** [comment]
I no longer use Openshot due to the hassle setting speed. I now use Kdenlive, what a pleasure, does everything and more, plus no more crashes and freezing.
