### ISSUE TITLE
Overlapping 2 video with OpenShot Video Editor

### ISSUE THREAD

**Issue by FabienGitHub** [OpenShot/openshot-qt#2618]
How can i overlap totaly 2 video .mp4 of same length ?
I think to set transparency at 50% for each of them but did not succeed.

Thanks

Fabien

**Comment by N3WWN** [comment]
@FabienGitHub Place each clip on a different track and set the alpha property for the clip in the upper track to 0.50.

**Comment by FabienGitHub** [comment]
Awesome! Exactly what i need.

Thanks a lot
