### ISSUE TITLE
Give your bug report a descriptive title

### ISSUE THREAD

**Issue by Carloceruti** [OpenShot/openshot-qt#2619]
:**Describe the bug:**
I set a custom profile in 9:16. When I load it I still see the preview in 16:9. When I render the video the preview stretch the video. Basically is impossible to work on the vertical format

**Steps to reproduce the behavior:**
1. Set a custom profile
    example

 description=CARLO916
frame_rate_num=30000
frame_rate_den=1001
width=576
height=1024
progressive=1
sample_aspect_num=1
sample_aspect_den=1
display_aspect_num=16
display_aspect_den=9

2. load some media files
3. put them in the timeline
4. see wrong preview
5. export video
6. on preview notice stretched video

**Expected behavior:**
I would expect to see vertical preview

**System Details:**
- OpenShot Version [e.g. 2.4.3]
- Operating System / Distro: Lubuntu 18.01

**Comment by ctsdownloads** [comment]
Old version of OpenShot. Closing as it's outdated.
