### ISSUE TITLE
OpenShot Newbie

### ISSUE THREAD

**Issue by scojopa** [OpenShot/openshot-qt#262]
Just installed OpenShot 2.07 on linux mint 18 x64

I can load and save a video to mp4 - audio and video quality are perfect. But when I load the video to sites like twitter and/or youtube - there is not audio. Twitter shows the audio meter moving like it would normally but no audio. Tried it on youtube and same thing. I there a different codec I should use?

When I export the video (again playback locally on desktop is fine after export)

Profile: web
Target: Youtube + HD
Video Profile: HD 1080P 25fps
Quality: Med

Audio Codec: libmp3lame
Sample Rate 44100
no. of Channels: Stereo (2 Channels)
BitRate/Quaility: 320 kb/s

**Comment by scojopa** [comment]
Openshot User Forum  - you cannot register to ask a question?

**Comment by scojopa** [comment]
In case anyone is seeing these  - tried to email the administrator on the forum and the email address is no good

Technical details of permanent failure:
Google tried to deliver your message, but it was rejected by the server for the recipient domain openshotusers.com by mx1.servage.net. [77.232.76.19].

The error that the other server returned was:
554 5.7.1 <openshot_forum@openshotusers.com>: Recipient address rejected: "USER UNKNOWN"

**Comment by jonoomph** [comment]
The forum is not run by myself, so I'm sorry I can't help with that. Please try again and hopefully it was a temporary issue. =)
