### ISSUE TITLE
Time Line stops counting after XX:XX Windows 10

### ISSUE THREAD

**Issue by Scraft161** [OpenShot/openshot-qt#2621]
I found this when editing a video (Screenshot Should explain it)
![openerror01](https://user-images.githubusercontent.com/19813118/52777081-4c25d280-3043-11e9-841d-bb960bdb4154.PNG)

I don't know how this happened but this is not normal behavior

**Comment by N3WWN** [comment]
Dupe of https://github.com/OpenShot/openshot-qt/issues/652
