### ISSUE TITLE
open shot bug in the window with reference to options available (windows)

### ISSUE THREAD

**Issue by akch41** [OpenShot/openshot-qt#2623]
With this bug you can no longer see the project space, project window and only the timeline appears. 

1. Go to top right hand side there is small box. Click it multiple times
4. Voila all options disappeared you are stuck with timeline and nothing can be done

Screenshots:

![bugs](https://user-images.githubusercontent.com/12879383/52847483-570b6080-3132-11e9-8183-abbbc22e068d.png)

**Comment by akch41** [comment]
And restarting the application doesn't reset it up

**Comment by N3WWN** [comment]
You can restore the default layout via `View` > `Views` > `Simple View`
