### ISSUE TITLE
2.4.3 will not open on a mac

### ISSUE THREAD

**Issue by dogbiird** [OpenShot/openshot-qt#2626]
When I try to start openshot, it will go through the normal procedure of whenever you first get it. Once I click "open" on it, the app will just bounce for a few seconds before disappearing from the task bar. My mac version is 10.10.5

**Comment by thoth444** [comment]
I am using MacOS Yosemite 10.10.5 and the same issue is happening to me. My wife is running the app on her MacOS Mojave 10.14 and it is working fine for her.

**Comment by cryptosquirrels** [comment]
I have this issue as well

**Comment by JacksonRG** [comment]
@Larcini20 what version of openshot and macOS are you using? Also could you attach your log files for us to take a look at? Instructions for finding them can be found [here](https://github.com/OpenShot/openshot-qt/wiki/Issue-Logging)

**Comment by cryptosquirrels** [comment]
I have monterey 12.4


I tried to download it again today and it wont open.


just FYI

**Comment by JacksonRG** [comment]
That's very interesting. Are any log files being generated? That may show us where the failure is happening.

**Comment by cryptosquirrels** [comment]
Sorry I went with shotcut since I couldnt get this to work - I just updated
my MAC today to idk what version I was on yesterday :/
