### ISSUE TITLE
Rotated video rotates applied transitions

### ISSUE THREAD

**Issue by fazjaxton** [OpenShot/openshot-qt#2629]
I am editing a phone video that was imported with a rotation of 90 degrees.  (Perhaps openshot received this from the video metadata?  I did not set it).  When I apply any transition effect, the transition is rotated with the photo.  Maybe this is fine/appropriate for wipes, etc, but I am trying to achieve an [effect like this](https://www.youtube.com/watch?v=Hd9k3x0diOo), which is borderline impossible with the video rotated.  It would be nice to be able to alter the order in which these effects are applied (rotate then transition, transition then rotate), so that either effect could be achieved easily.

I expected the transition to be applied with reference to the final video frame, not the rotated frame of the clip.

OpenShot 2.4.3, Windows 10

**Comment by ctsdownloads** [comment]
Old version of OpenShot. Closing as it's outdated.
