### ISSUE TITLE
Windows User Name In Unicode

### ISSUE THREAD

**Issue by tprodromos** [OpenShot/openshot-qt#263]
It looks like it can not handle Windows User Names in Unicode. In my case Greek.
When i click to run the application, i get like the attached files.

Log File: 
[openshot-qt.zip](https://github.com/OpenShot/openshot-qt/files/403104/openshot-qt.zip)

Screen Shot:
![openshot1](https://cloud.githubusercontent.com/assets/20851608/17425456/2a52f70e-5ad6-11e6-870b-43bdc3862ce9.jpg)

**Comment by DylanC** [comment]
@tprodromos - Is this still an issue for you in newer versions of OpenShot?

**Comment by tprodromos** [comment]
Hello,
Is working now!

Thanks!

**Comment by tprodromos** [comment]
Hello,

Is working now!

 

Thanks.
