### ISSUE TITLE
Playback Lags in editor

### ISSUE THREAD

**Issue by ohineedascreenname** [OpenShot/openshot-qt#2631]
When playing back a video in the editor, it's extremely slow and laggy. I have tried it on several computers of different specs and it acts the same on each one

**Comment by yvansubestimado** [comment]
a mi me pasa lo mismo.. Alguna solucion?

**Comment by ohineedascreenname** [comment]
> 
> 
> a mi me pasa lo mismo.. Alguna solucion?

No he recibido ninguna respuesta. Lo siento.

**Comment by Josee9988** [comment]
Same here! Extremely laggy built-in editor video preview

**Comment by ctsdownloads** [comment]
Best practice when working with video in OpenShot is to reduce the frame rate (you can select a profile with lighter resolution and frame rate) for editing. This alone, makes a huge difference. Once editing is complete, return your resolution/FPS profile to the same as the source video, then render at the same resolution/FPS as your source video.

You don't need a higher frame rate for editing, so reducing it while editing then returning it normal after editing before rendering will provide you with a much better experience.
