### ISSUE TITLE
Video editing-only able to see first 15 seconds

### ISSUE THREAD

**Issue by ilovescience716** [OpenShot/openshot-qt#2632]
I have added a video to my timeline and I am only able to see/work with the first 15 seconds of it.  I have no idea why.  The video is 52 minutes long.....

Any ideas for how to be able to access the rest of the video?  All that I see is black and when I go beyond the first 15 seconds and Openshot doesn't let me play anything.

**Comment by Paulcooked** [comment]
same here. perhaps not enough storage? would love actual help from someone who knows.
