### ISSUE TITLE
adding transitions to selected images via the 'add to timeline' function bugs the video's lenght

### ISSUE THREAD

**Issue by dav9597** [OpenShot/openshot-qt#2633]
**Describe the bug**
adding transitions to selected images via the 'add to timeline' function bugs the video's lenght

**Steps to reproduce the behavior:**
1. Add images to project's file section
2. Select all of them
3. Right click, and click on 'Add to timeline'
4. Check video's lenght before adding a transition, to see if it's correct
4. When adding every type of transition to the timeline, the final video's lenght bugs, and the final result is not what it should be.

**Expected behavior**
The lenght should have adapted to the added transitions instead of bugging, and the final timeline should be corrected as a result.

Strange thing is that the first day of installation this method worked successfully, just from the following days it started failing.

**System Details**
- OpenShot Version: 2.4.3-dev3
- libopenshot Version:  0.2.2
- Platform: Windows-10-10.0.17134
- Processor: Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
- Machine: AMD64
- Python version: 3.6.4
- Qt5 version: 5.9.1
- PyQt5 version: 5.9
- Qt Detected Languages: ['it-IT', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.4.3-dev3-1550174979-62fa7176-2f74da2f-x86_64.exe

**Log Files**
- http://logs.openshot.org/oi9nzonhgk6mw26lz6luaqzyk242admj/openshot-qt.zip
- http://logs.openshot.org/oi9nzonhgk6mw26lz6luaqzyk242admj/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Comment by ctsdownloads** [comment]
Old version of OpenShot. Closing as it's outdated.
