### ISSUE TITLE
Video preview screen ratio doesn't match that which of the profile

### ISSUE THREAD

**Issue by mickael-h** [OpenShot/openshot-qt#2637]
When you create a custom profile with an aspect ratio like 1:2 (for mobiles), the aspect ratio in the video preview stays at 16:9.
This makes editing extremely tedious as you have to guess and manually enter X and Y values for your clips, export the video, and then check the result to see if positioning was correct.

**Steps:**
1. Create a custom profile with a 1:2 aspect ratio (or any unusual ratio)
2. Select that profile in OpenShots
3. Import your mobile video clips
4. See the video preview is still in 16:9

**Expected behavior:**
The video preview's aspect ratio should be the same as the profile's

**System Details:**
- OpenShot Version 2.4.3
- Operating System: Windows 10

**Comment by ctsdownloads** [comment]
Is this still an issue with the current version of OpenShot? The version we have on the website currently? https://www.openshot.org/download/
