### ISSUE TITLE
Panel

### ISSUE THREAD

**Issue by Forbahl10** [OpenShot/openshot-qt#2638]
How do I get back to the start panel? My panel is this way.
![image](https://user-images.githubusercontent.com/34489039/53271149-4deb3800-36cc-11e9-97ee-de83af8f016e.png)

And I want him to come back like this

![image](https://user-images.githubusercontent.com/34489039/53271214-825ef400-36cc-11e9-819f-2cece102fbe0.png)

**Comment by DylanC** [comment]
@Forbahl10 - Menu View >> Views >> Simple View.
