### ISSUE TITLE
Popping sounds - can I download a previous version?

### ISSUE THREAD

**Issue by rceleste125** [OpenShot/openshot-qt#2640]
Hi,  the latest version 2.4.3 (even daily build) produces popping and crackling sounds instead of the video sound.  This didn't happen in the previous version.  Can I re-install the previous version until this is fixed?

**Comment by speedytechdev** [comment]
Hi @rceleste125 Have you looked at [#2441](https://github.com/OpenShot/openshot-qt/issues/2441) and yes you can go back to the previous version.  Just go to our [downloads page](https://www.openshot.org/download/).

**Comment by rceleste125** [comment]
Thanks for replying!  I'm experiencing the popping/crackling sound while in OpenShot.  So, I can't hear any audio while editing.  Which renders the product useless.  I'll try and download the previous version and see if that does it.

**Comment by rceleste125** [comment]
Ugg! Previous version doesn't work now.... No offense, but this doesn't seem to be a viable product.

**Comment by speedytechdev** [comment]
I am sorry to hear that. If I can take some information about the issue I can get one of the devs to look at it. If not I am sorry you did not have a pleasant experience with our product.

Thank you and have a great day
