### ISSUE TITLE
Crashing on zoom

### ISSUE THREAD

**Issue by logruszed** [OpenShot/openshot-qt#2641]
Pretty straightforward. Any time I try and perform the zoom animation for my video project the program stops responding forcing a hard shut down.

Windows 10, 16GB RAM, Ge Force GTX 960.

Project size is around 12GB, 2 hours of 1080 video at 24 frames.

Program crashes a lot, but I've worked around most of them but this zoom issue is a motherfucker.

**Comment by ctsdownloads** [comment]
Is this still an issue with the current version of OpenShot? The version we have on the website currently? https://www.openshot.org/download/
