### ISSUE TITLE
Crash trying to export

### ISSUE THREAD

**Issue by Barmatyr** [OpenShot/openshot-qt#2642]
Program crash trying to export 

I want to make a document which consist on one picture and 2 hours audio track. So maybe the parameter i put are incorrect, i'd be glad to have tip on this point. I just want have a doc those size are relative to 1 picture and 2 hour high quality audio. For example i reduce fps to 25 to 1 as the video is not important, is this wrong

-Configure  exportation parameter
-Click export
- Program crash nearly instantly

Expected computation progress reach 100%, and having a new document with edited audio and video.

**System Details:**
-Win 7 
- OpenShot Version 2.4.3

**Log Files:**
No log file in program folder

**Exception / Stacktrace:**
Signature du problème :
  Nom d’événement de problème:	APPCRASH
  Nom de l’application:	launch.exe
  Version de l’application:	0.0.0.0
  Horodatage de l’application:	00000000
  Nom du module par défaut:	swresample-2.dll
  Version du module par défaut:	2.9.100.0
  Horodateur du module par défaut:	00000000
  Code de l’exception:	c0000005
  Décalage de l’exception:	000000000000d1b3
  Version du système:	6.1.7601.2.1.0.768.3
  Identificateur de paramètres régionaux:	1036
  Information supplémentaire n° 1:	21e4
  Information supplémentaire n° 2:	21e486e94a88fc31713e7fc96fd0182a
  Information supplémentaire n° 3:	5298
  Information supplémentaire n° 4:	52988712f68cb6f93df42f80de5bb961

**Comment by Barmatyr** [comment]
> **Describe the bug:**
> A clear and concise description of what the bug is.

ogram crash

**Comment by ctsdownloads** [comment]
Is this still an issue with the current version of OpenShot? The version we have on the website currently? https://www.openshot.org/download/
