### ISSUE TITLE
Slo-mo (time:1/4X) is still on exported 60fps video

### ISSUE THREAD

**Issue by avengerx** [OpenShot/openshot-qt#2644]
**Describe the bug:**
Slow-motion clip is exported as still image on HD/720p, 60fps video.

**Steps to reproduce the behavior:**
1. Add a new file to the project, MP4/h264, 1280x720, 60fps, 15Mbps
2. Clip a small scene of the file you want slow-motion (about 2 seconds may be okay)
3. Add the normal-speed file, and following add also the "cut scene" clipped fragment
4. Set the "cut scene" part time as "1/4X" (right-click, time, forward, 1/4X)
5. Export the video as HD 720p 60fps (1280x720)

**Expected behavior:** The slo-mo part of the movie plays in slo-mo.

**Actual behavior:** The slo-mo part of the movie is still in the first slo-mo frame. If audio enabled, it will loop the first audio packet

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 2.4.3
- Operating System / Distro: Windows 10

**Workaround:** export as 24fps

**More info:** Exporting as either HD 720p or HDV 720p profiles, as long as 24fps, works fine. If FPS is set to 60 (to match source video), then the slow-mo part breaks.

**Comment by Alayan-stk-2** [comment]
I encountered the same still-image issue when exporting at 30FPS.

On a second try, instead of a still image, it was the wrong part of the clip which was shown in slow motion (likely because the keyframes weren't corrected for the different framerate).

**Comment by SuslikV** [comment]
@Alayan-stk-2 are you using latest build of OpenShot, what OS?

**Comment by Alayan-stk-2** [comment]
It happened with the latest stable release, 2.4.4 (no dev build), on linux.

As a workaround, I had my video recorder record openshot playing the slow-motion clip correctly in the preview, then put the resulting slow-mo video as a normal-speed one in the project.

**Comment by SuslikV** [comment]
@Alayan-stk-2 Native install or AppImage?

**Comment by Alayan-stk-2** [comment]
AppImage

**Comment by SuslikV** [comment]
Try at least to compile your own. What OS exactly (just wondering)?
