### ISSUE TITLE
Tick Marks in Timeline

### ISSUE THREAD

**Issue by MIKE1106** [OpenShot/openshot-qt#2648]
While using OpenShot 2.4.3 the timeline window shows small blue tick marks that appear at the bottom of the timeline as I move the playhead.  All else seems to work well.

![image](https://user-images.githubusercontent.com/16543603/53498315-15ed4780-3a74-11e9-8230-2c1694d69ce2.png)

**Comment by N3WWN** [comment]
That is not a bug... that is showing how much of the preview has been rendered and cached.

**Comment by ferdnyc** [comment]
As @N3WWN says, that's the preview cache status display. (Which I _believe_ is documented in the manual, though I'll double-check before closing this.)

**Comment by ferdnyc** [comment]
Huh, I guess it isn't! OK, a documentation bug, then. I'll add it to the list.
