### ISSUE TITLE
Specify the BugTracker website

### ISSUE THREAD

**Issue by buhtz** [OpenShot/openshot-qt#265]
Please specifiy the bugtracker website.

There is one here on GitHub and one on Launchpad.
When using "Report a Bug" in the help menu of OpenShot (Debian unstable) it redirects to the Launchpad site.

**Comment by JtLively** [comment]
There seems to be only one maintainer here at the moment. There's always the OpenShot IRC channel.

**Comment by jonoomph** [comment]
Thanks for the comment. Website and current version of OpenShot (2.2.0) all point to Github now.
