### ISSUE TITLE
Input box to manually enter hh:mm:ss timecodes in Split Clip tool

### ISSUE THREAD

**Issue by avtneyney** [OpenShot/openshot-qt#2650]
Hello. It would be nice if you add an inputbox or simply replace the current timecode label with inputbox to be able input precise start/stop point timecodes instead of relying strictly onto rough mouse drag and keyboard arrow controls. It would not only help to make finely timed cuts but also make the Split Clip tool usable on certain files (large many hours long .mp4 files for example) where it simply stops playing video at selected timestamp but still lets you to select start/stop timecodes.

**Comment by ctsdownloads** [comment]
Appreciate the feature request, thank you.
