### ISSUE TITLE
Audio cuts out at the end of videos.  

### ISSUE THREAD

**Issue by jamiewenzel2019** [OpenShot/openshot-qt#2651]
When editing a video, for some reason the audio cuts out the last 6 seconds of the video and is replaced with a buzzing sound.  The video itself does not have this issue, and when I edit the video in other video editors, I don't have the issue.  It doesn't matter what video I use or what computer tries it, everyone is experiencing the same problem.  I have noticed several people online of complaining about this since 2016.  This has to be a fixable issue or people wouldn't be able to use your software.  Is there some sort of audio incompatibility with mp4's or something? Maybe a setting somewhere to fix this?

**Comment by speedytechdev** [comment]
Hi @jamiewenzel2019 could you attach your crash logs and what version of Openshot do you use?

**Comment by jamiewenzel2019** [comment]
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/2930995/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2930996/openshot-qt.log)

I am using version 2.4.3.

**Comment by IowaBoy1** [comment]
I am having the same problem. It does it when I fade the audio. In the preview, the fade is great. But when I export it, it just drops all the audio for the final seconds. If I reset the audio and export it again, I get audio all the way to the end
