### ISSUE TITLE
cx_Freeze: Python error in main script

### ISSUE THREAD

**Issue by MusoCity** [OpenShot/openshot-qt#2652]
### 
![openshot-error](https://user-images.githubusercontent.com/37819494/53611907-e8db9900-3c1b-11e9-8f78-21b540d5f904.png)

This is a first time install on Win7 64
it won't run, just keeps giving the attached error.
There are no log files as it has not run.

**Describe the bug:**

**Steps to reproduce the behavior:**

**Expected behavior:**

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.
Log files can be found in your HOME/.openshot_qt/ folder. Please compress or zip
the log files (as they can become quite large).

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please
attach a small snippet of the exception here, but please keep it as small as
possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them here, dragging-and-dropping into this form, or clicking below and loading
images saved to your computer. All images are public, so please don't post screenshots
containing personal information.

**Comment by jonathanzhang53** [comment]
@MusoCity I had this issue. I raged and uninstalled the first time it happened but I tried again and looked at some similar issues I found elsewhere.

What I did on Win64 windows 10 was just opened openshot and used "Open Project" and then selected the project. But when I try to open the project like you did, I get the same error. Hope it helps someone.

**Comment by deepakrathod033** [comment]
Same error, I install OpenShot Video Editor & run the first time then software cannot run and shows an error "cx_Freeze: Python error in main script" I can't understand how to fix it.
