### ISSUE TITLE
Averaging out the parameters over time

### ISSUE THREAD

**Issue by pythoniste** [OpenShot/openshot-qt#2653]
When I vary parameter of a vide over time, I can see the right result in the Video Preview window.
When I export the video, the parameters seen to be avegared out over time.

This is an example :

1. Create a new project.
2. Import a video (5 seconds will suffice)
3. Put the time slider to 0 second and put X and Y scale to 0.01
4. Put the time slider to 2 seconds and put X and Y scale to 1
5. Export the video

When you preview the video, you will see the image grow from almost nothing to the right size ant then keep the right size.
When you view the rendered video, you will see the image at a scale of 80 percent (more or less) from the start to the end of the video.

If you replace step 3 and 4 by these :
3. Put the time slider to 0 second and put alpha 0.01
4. Put the time slider to 2 seconds and put alpha to 1

Then, when you preview the video, you will see a black screen and the image appear gradually until it is the clear image (at 2 secs) and keep this way.
When you view the rendered video, you will see the image beeing darkened and staying in the same contrast all along from the start to the end of the video.

I can give you an example project if needed.
I tried on 2.4.1 on Ubuntu 16.4 LTS / A friend of mine tried on 2.4.3 on Windows with the same results.

**Comment by ctsdownloads** [comment]
Is this still an issue with the current version of OpenShot? The version we have on the website currently? https://www.openshot.org/download/

**Comment by ferdnyc** [comment]
I suspect this was a result of the user exporting their project at a different frame rate than they originally configured it for, which was known to be broken until the later 2.4.x releases. The symptoms they're describing shouldn't be a problem anymore.
