### ISSUE TITLE
Windows installer's cert has already expired

### ISSUE THREAD

**Issue by lflee** [OpenShot/openshot-qt#2655]
**Describe the bug:**
Windows installer's cert has already expired.

**Steps to reproduce the behavior:**
1. View the installer's cert before installing the software

**Expected behavior:**
Cert hasn't expired.

**System Details:**
- OpenShot Version 2.4.3 (source - (https://github.com/OpenShot/openshot-qt/releases/download/v2.4.3/OpenShot-v2.4.3-x86_64.exe) )
- Operating System Windows 10

**Log Files:**
(It's a "pre-install" issue.)

**Exception / Stacktrace:**
(It's a "pre-install" issue.)

**Screenshots:** 
![img_20190304_172434](https://user-images.githubusercontent.com/3342858/53724125-2d796580-3ea4-11e9-96a4-9c56daa450c5.jpg)

**Comment by ctsdownloads** [comment]
Old version of OpenShot.
