### ISSUE TITLE
Problème d'exportation

### ISSUE THREAD

**Issue by LouisRobard** [OpenShot/openshot-qt#2657]
Bonsoir,
Venant de terminer un projet avec l'outil openshot vidéo éditor, je viens d'exporter celui)ci dans mes document afin de pouvoir le lire. Cependant, lors de la lecture, certains cuts apparaissent très sombres tandis que d'autres apparaissent en bonne luminosité.
Je ne comprend pas pourquoi certaines vidéos sont très sombres voire noires. 
Merci de votre réponse,
Louis

**Comment by ctsdownloads** [comment]
Try opening the OpenShot project file again, zoom in and see if there a space between your cut video clips.
