### ISSUE TITLE
Audio files are importing as Video

### ISSUE THREAD

**Issue by pwd-github** [OpenShot/openshot-qt#2659]
**Describe the bug:**
Despite changing format from mp3 to ogg, oga or flac, the audio appears as a video file.

**Steps to reproduce the behavior:**
1. Open Openshot
2. Right click the files square
3. Select file to import
4. See audio files listed as video.

**Expected behavior:**
I expected audio files to be listed as audio

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 2.4.3
- Operating System / Distro: Fedora 29

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.
Log files can be found in your HOME/.openshot_qt/ folder. Please compress or zip
the log files (as they can become quite large).

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please
attach a small snippet of the exception here, but please keep it as small as
possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them here, dragging-and-dropping into this form, or clicking below and loading
images saved to your computer. All images are public, so please don't post screenshots
containing personal information.

**Comment by ctsdownloads** [comment]
Using a current version of OpenShot, I can drag in wavs without any issue. Same with MP3s. Drag the files you're having issues with into Audacity, render them to wav and try again. I suspect the issue will be resolved.
