### ISSUE TITLE
export a single track

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [OpenShot/openshot-qt#266]
In a project with mutliple tracks I want to export only one of the tracks.

Much better would be to export each of the track as on video in a batch job - 6 tracks, 6 videos.

**Comment by CharlesKumar** [comment]
is this still pending to implement?

I'm using openshot 2.3.4 

Exporting single track would be a nice feature and makes the multiple clipping a large video, an easier task..

**Comment by DylanC** [comment]
@CharlesKumar - I think it is as far as I know.

**Comment by CharlesKumar** [comment]
let's wait for batch jobs but through manually

is single track export possible? 

I am new to this openshot and want to know if it is already implemented

**Comment by Slowrider1969** [comment]
Was there ever an update to this question.  I would also like to have this option for breaking up recorded training videos.  Searched the forum and didn't see anything similar.

**Comment by SuslikV** [comment]
@Slowrider1969 in the https://github.com/OpenShot/openshot-qt/issues/784#issuecomment-643806061 mentioned feature (not official) to disable/enable OpenShot Tracks, so it can be used as workaround.

**Comment by CharlesKumar** [comment]
Hi Friends,

I saw the github notification for this thread now and i want to tell you that I use format factory for exporting multiple clips of a single video file. 

In format factory, select crop option in the Video section.
select start time and end time for video clip   
click + icon which adds the clip to the list
repeat clipping and adding to list 
click ok and click settings to change the encoding options to your choice
click ok->start


Note: set selction operation (on the right while clipping) from crop to off

[Shotcut](https://www.shotcut.org/) claims to have ([batch-exporting-multiple-edited-videos-from-one-project](https://forum.shotcut.org/t/batch-exporting-multiple-edited-videos-from-one-project/7851)
[
Da Vinci Resolve](https://www.blackmagicdesign.com/in/products/davinciresolve/) claims to have render queue, mute clip, mute audio, mute part of audio, etc., watch this youtube [video](https://www.youtube.com/watch?v=H0hUk7YBwww)
