### ISSUE TITLE
Adding multiple effects causes video preview to stutter

### ISSUE THREAD

**Issue by blackoutworm** [OpenShot/openshot-qt#2662]
Hi there. Adding 1 effect doesn't cause any sort of stuttering, but adding 2 or better yet 3 makes the preview unbelievably slow.
I thought lowering the preview quality would help, so I tinkered around with the cache settings. This didn't help at all.
It's also not a computer spec issue as my computer has 32 gigs of ram and 2 Nvidia GTX 980ti GPUs.
And I'm on Linux Mint 18.3, so it can't be a forking or dependency issue either.
My Openshot-qt version is 2.4.3. I've seen other people are having this problem too with the latest Openshot. Not sure if they're related though, cuz they named specific effects.
Is there any sort of workaround for this?

**Comment by ctsdownloads** [comment]
Try lowering the resolution/fps in your OpenShot timeline profile, make your edits then restore the profile to match your imported video.
