### ISSUE TITLE
WinError 183 try to create existing thumbnails folder

### ISSUE THREAD

**Issue by DeKaZedd** [OpenShot/openshot-qt#2663]
**Describe the bug**
When I try to open a existing project, from the soft by file -> open or by doubleclicking in the Windows explorer, I get the error : 
[WinError 183] Impossible de créer un fichier déjà existant: 'C:\\Users\\cp26r\\.openshot_qt\\thumbnail'

that should translate to this in english:
[WinError 183] Unable to create an existing file:'C:\\Users\cp26r\.openshot_qt\thumbnail'

**Steps to reproduce the behavior:**
1. Create project
(1.1 synch all the files with google drive, just uploading them online)
2. Close computer
3. Try to open the project within the soft or with Windows explorer
3.1 Get the error

**Expected behavior**
I expect the project to be loaded correctly without any error of thumnail file already existing

**System Details**
- OpenShot Version: 2.4.3-dev3
- libopenshot Version:  0.2.2
- Platform: Windows-10-10.0.17134
- Processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
- Machine: AMD64
- Python version: 3.6.4
- Qt5 version: 5.9.1
- PyQt5 version: 5.9
- Qt Detected Languages: ['fr-FR', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.4.3-dev3-1551911804-8f385c11-2f74da2f-x86_64.exe

**Log Files**
- http://logs.openshot.org/x02apuwfofvjt9jwvfgpwygnd0jmz2ac/openshot-qt.zip
- http://logs.openshot.org/x02apuwfofvjt9jwvfgpwygnd0jmz2ac/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by Michiel72** [comment]
![image](https://user-images.githubusercontent.com/44952852/67640223-72518100-f8f9-11e9-8dcf-99434b68ce99.png)

**Comment by ferdnyc** [comment]
@Michiel72 

The original report from @DeKaZedd included log files showing where OpenShot logged the failure that leads to this message:
<pre><code>
    timeline:INFO Adjusting max size of preview image: PyQt5.QtCore.QRect(170, 0, 1265, 712)
preview_thread:INFO refreshFrame
preview_thread:INFO self.player.Position(): 1
     version:INFO Found current version: {"openshot_version": "2.4.3"}
 main_window:INFO foundCurrentVersion: Found the latest version: 2.4.3
 main_window:INFO Clear all thumbnails: C:\Users\NAME\.openshot_qt\thumbnail
<b> main_window:INFO Failed to clear thumbnails: C:\Users\NAME\.openshot_qt\thumbnail</b>
project_data:INFO Setting default profile to HD 720p 30 fps
project_data:INFO Loading project file: PATH.osp
project_data:INFO checking project files...
</code></pre>

Can you please post your logs, so we can determine whether it's the same issue? (Here are [instructions for collecting logs](https://github.com/OpenShot/openshot-qt/blob/develop/CONTRIBUTING.md#did-you-find-a-bug) if you need, but please **DO NOT** follow the instruction to enable 'Debug Mode'. It does not add any useful data for this report.)
