### ISSUE TITLE
question and improvement for speed

### ISSUE THREAD

**Issue by devynatorules-original** [OpenShot/openshot-qt#2665]
do you guys think you could give us gpu acceleration and use as much cpu as possible? I find that gpu acceleration can quite dramatically render much faster for videos, also when I set 480p on the render page, only half the cpu is used, please improve that to use full please. all resolution settings should use all the cpu to render much quickly, especially people with server computers with many cores, must use full frequency of all cores

**Comment by ctsdownloads** [comment]
Marked this as a feature request, thanks for your feedback.
