### ISSUE TITLE
Create New Files per Track

### ISSUE THREAD

**Issue by rah00027** [OpenShot/openshot-qt#2667]
Hi,
      I created multiple tracks by slicing one long track.  How can I save each track to a different file, so I can choose any file/ track I want in a folder?  Please go through each step.  Thank you.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Comment by DylanC** [comment]
@rah00027 - This feature doesn't exist currently. You would need to save one track at a time and repeat the process to completed all of your tracks.
