### ISSUE TITLE
works with blender 2.80?

### ISSUE THREAD

**Issue by didierherisson** [OpenShot/openshot-qt#2668]
I'm discovering openshot and blender at the same time...
As blender 2.80 features many changes to follow standard UI, it may be easier for me to start learning it from this release. The few bugs if any will be fixed when I will start serious work.
Blender can be launched by:
`$/home/didier/blender/blender-2.80-a0f2923fd821-linux-glibc224-x86_64/blender

Read prefs: /home/didier/.config/blender/2.80/config/userpref.blend
found bundled python: /home/didier/blender/blender-2.80-a0f2923fd821-linux-glibc224-x86_64/2.80/python`

and this works pretty well.
So I set this path for blender in the preferences, and I have the return message:
`Chemin vers l'exécutable de Blender :
/home/didier/blender/blender-2.80-a0f2923fd821-linux-glibc224-x86_64/blender

Erreur de sortie :
Aucune image n'a été trouvée en sortie de Blender`

(This is the french translation, should be something like: Path to blender: [...] No image found as blender's output).

Any suggestion?

PS: it may be another question but not an issue: I would like to use the animated titles as starting points for editing and playing in blender, how would you suggest me to do? where can I find the files to edit in blender?

**Comment by j2l** [comment]
It works ... not yet
If you open the blend anim file (C:\Program Files\OpenShot Video Editor\blender\blend) with Blender 2.8 you can render it (after some render tweaks), so it should work in theory.
But the openshot script is not adapted for B28, you need B279 to make it work within openshot

Result of animation is located at  C:\Users\username\.openshot_qt\blender\...\...png

J'espère que ça t'aide :)

**Comment by j2l** [comment]
What'd be great is to have more info about C:\Program Files\OpenShot Video Editor\blender scripts and xml into openshot to be able to share/add users' blend like https://www.youtube.com/watch?v=kJNPV4rwxnI into openshot
That could turn into a Adobe Spark killer

**Comment by peanutbutterandcrackers** [comment]
@j2l - Hey there, thank you for helping out here. Perhaps you might also be interested in [contributing to OpenShot](https://www.openshot.org/static/files/user-guide/developers.html)?

@didierherisson - I hope @j2l's reply answers your question. Blender 2.8 does introduce a lot of changes and thus makes the animation scripts obsolete (for now). But once the stable release is done, perhaps we might work on updating our scripts, as well.

@j2l - I will ask the devs regarding this. That would be awesome!

**Comment by j2l** [comment]
@peanutbutterandcrackers thanks, I'm more an artist than a dev and documentation is lacking info about script+xml for animated titles.
Or do you have a link about that elsewhere?

**Comment by didierherisson** [comment]
Le vendredi 15 mars 2019 à 13:42 +0000, PM a écrit :
> It works ... not yet
> If you open the blend anim file (C:\Program Files\OpenShot Video
> Editor\blender\blend) with Blender 2.8 you can render it (after some
> render tweaks), so it should work in theory.
> But the openshot script is not adapted for B28, you need B279 to make
> it work within openshot
> Result of animation is located at
> C:\Users\username.openshot_qt\blender......png
> J'espère que ça t'aide :)
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

Ok, thanks for the answers.
As I just installed blender few days ago to get animated titles, I'm
not sure  I will be able to developp anything before years... My
contributions will just be bug reporting for a while, just because i
don't have the knowledge. 
I will remain with 2 install for blender, 2,79 for run inside Openshot
and 2,8 to (hopefully) start learning blender, openshot will be updated
to run blender 2.80 before I can produce anything anyway!

Thank you for all the devs implied!
-- 
Didier Hérisson

**Comment by DylanC** [comment]
Closing as answered.
