### ISSUE TITLE
OpenShot 2.0.7 can't fade in by adding a Fade transition and reversing it.

### ISSUE THREAD

**Issue by monohydroxy** [OpenShot/openshot-qt#267]
OpenShot 2.0.7 can't fade in by adding a Fade transition and reversing it.  I could be wrong, but this seems like the correct way to do a Fade In.  Fade Out works by just adding a Fade transition.  The Project file before and after reversing the transition is different: handles change Y from 1 to -1, but I'm not sure what it means.

**Comment by jreynojustin** [comment]
OpenShot is now in Version 2.2 if you are still noticing issues in the latest version please re-open this issue letting us know.
