### ISSUE TITLE
video not playing

### ISSUE THREAD

**Issue by emrldman** [OpenShot/openshot-qt#2671]
**Describe the bug:**

**Expected behavior:**
I am trying to make a video and its only showing a black screen or its going through 1 frame.

**System Details:**
- OpenShot [HDV 720 24p: 
-Operating System: Windows 10

**Comment by ctsdownloads** [comment]
Is this still an issue with the current version of OpenShot? The version we have on the website currently? https://www.openshot.org/download/

In the software, is this happening in the preview window when you have play-head indicator over the video?
