### ISSUE TITLE
Openshot for Windows stops responding when importing video file

### ISSUE THREAD

**Issue by gstedje** [OpenShot/openshot-qt#2672]
OpenShot Version: 2.4.3 x86 Windows. Fresh install.
Windows Version: Windows 7 x86
Video File details: Doesn't seem to matter. MP4, 720p @30fps 1996kbps data rate. Audio 128Kbps stereo @44KHz. Video file created with OpenShot. Small WMV and MOV files cause the same hang.
Hardware. Older Dell Laptop with Core2Duo T9600 / GM45

**Comment by ctsdownloads** [comment]
Try the current version of OpenShot https://www.openshot.org/download/ and let me know if it's still not working for you.
