### ISSUE TITLE
How do I make Openshot zoom in and move it around? 

### ISSUE THREAD

**Issue by PowerMan2206** [OpenShot/openshot-qt#2673]
Title gore, I know. Let me explain. How do I, for example, zoom in on my palm (while holding it in the air) and move the zoom around to follow my palm?

Another question, how do I even zoom in?

**Comment by DylanC** [comment]
@PowerMan2206 - Right click on clip. Animate >> Entire Clip >> Zoom >> (Pick your zoom level here).

The camera panning to follow an object might be not possible but @N3WWN might know something about this.

**Comment by N3WWN** [comment]
You can also use the `Scale X` and `Scale Y` properties available when you have a clip selected.  The scale properties can use keyframes, so if you want to change the zoom in different parts of the clip, you can.

To follow your palm around, use the `Transform` tool.  Place the playhead where you want to start tracking and move the image as you want (perhaps centering the palm of your hand in the preview window).  Then, move the playhead to where you hand changes direction and use `Transform` again to recenter your palm.  If your palm changes direction again, move the playhead to the end of that motion and recenter again.  Repeat until you've got the tracking completed.  

By changing the function used to describe the behavior between keyframes from `Linear` to a Bezier function, you can smooth out the changes in direction/recentering.  I like `Ease In/Out`, personally.

You can go to https://easings.net to get an idea of how each function behaves.

I use `Transform` (or `Location X` and `Location Y`) keyframes with `Ease In/Out` and `Scale` to take a wide angle video (taken on a tripod) to zoom in and track me playing a sport.

**Comment by DylanC** [comment]
Thanks @N3WWN!
