### ISSUE TITLE
Can't drag one clip along the timeline until restarting OpenShot

### ISSUE THREAD

**Issue by Thynix** [OpenShot/openshot-qt#2674]
**Question that turned into maybe a bug:**
I split a clip, and for reasons I can't understand, I can't drag one of them. When I try, it starts dragging a selection box instead, and the borders of the clip turn yellow instead of red like the others, which I can still drag.

I created the project during this session, and so it didn't load from a file, so I don't think this is project corruption. When I restarted the program and loaded the project, the problem went away. I don't have debug logging enabled, so `libopenshot.log` doesn't contain anything but startup times. `openshot-qt.log` does contain things, and I can post it if it seems likely to be helpful. I don't know what the steps to reproduce this would be. I was splitting clips, deleting parts of them, and dragging the parts I wanted to the start of the timeline.

**System Details:**
- OpenShot Version: 2.4.3
- Operating System / Distro: Windows 10 64-bit version 1809

**Screenshots:**
https://gfycat.com/anguishedacidicfrilledlizard

**Comment by halfgaar** [comment]
Same issue here, Linux Mint 17 (Ubuntu 14.04), Openshot 2.4.3.

**Comment by DylanC** [comment]
@Thynix @halfgaar - Try v2.4.4. Let us know if you run into more trouble. Thanks.

**Comment by khawabonga** [comment]
Same issue here: OpenShot v2.5.1, Windows 7 64 bits. 
Restarting OpenShot and reloading the project solves it.

**Comment by aiorazabala** [comment]
Same issue here: OpenShot v2.5.1. Ubuntu 18.04
Restarting OpenShot and reloading the project solves it. losing the project and reopening it does not solve it. Restarting OpenShot takes quite some time, so this glitch is pretty inconvenient.

**Comment by RayTang-hub** [comment]
Same issue here: OpenShot v2.5.1. MacOS v10.15.7
Restarting solves the problem. But this bug is very frequently.

**Comment by Thynix** [comment]
@DylanC It looks like this hasn't been fixed. It doesn't look like anyone else has been able to figure out steps to reproduce either. :/

**Comment by DylanC** [comment]
@Thynix - I'm not really involved with OpenShot at the moment but I'll reopen in case more people have this issue still. 👍

**Comment by Taildragger22** [comment]
Had same problem, I did right-click on the clip I couldn't move, copied it to a different place on the time line, and deleted the original. I could then move the affected clip.   Hope this helps.

**Comment by JacksonRG** [comment]
@Taildragger22 Does this issue happen every time you split a clip?

**Comment by tweektane** [comment]
Fix:
When i encounter this, i copy the clip that has issue and paste it in other track, then delete the original clip with issue and replace it with the new copy.
You will notice, its not turning to yellow anymore and you can drag it already.
