### ISSUE TITLE
Errno 9 bad file descriptor while exporting & saving file

### ISSUE THREAD

**Issue by Em1107** [OpenShot/openshot-qt#2675]
I'm trying tot export my openshot file and everytime I try to do so, a sign pops up saying: Errno 9 Bad file descriptor. I know nothing about programming and I really need tot export this file as soon as possible because it's a school project.  Can someone help me with this problem? I would be very greatful!

**Comment by ctsdownloads** [comment]
Is this still an issue with the current version of OpenShot? The version we have on the website currently? https://www.openshot.org/download/
