### ISSUE TITLE
Openshot black rectangle always present

### ISSUE THREAD

**Issue by jessjamesjones** [OpenShot/openshot-qt#268]
Using Open shot on Ubuntu 16.04 LTS. When openshot is open there is a black rectangle present on the desktop or if I have some other program open. The black rectangle is the preview screen in Openshot. However if i take a screen shot, it is not present. Any ideas what is wrong?

**Comment by jreynojustin** [comment]
Could you take a picture with your phone and upload it? Re-open the issue and post that if you do.
