### ISSUE TITLE
Keyframes do not take place in the video

### ISSUE THREAD

**Issue by ertufa** [OpenShot/openshot-qt#2683]
I am new at using OpenShot. I was editing a video and trying to figure out how do keyframes work. I have used lots of keyframes in that video and when I exported the video I noticed that keyframes that I have used can not be seen. 

![hahafgaga](https://user-images.githubusercontent.com/48606659/54466739-49c5ae00-4792-11e9-9d18-acb18606ff18.PNG)

What can I do for this problem?

**Comment by cmoralesmx** [comment]
I think I may be experiencing a related issue.  
I can set key frames but when the export is done, the resulting video does not match the preview.  
Lets say I want to change Location X from 0.00 at 00:00:55 to +0.25 at 00:01:00. So, set the corresponding key frames and the preview shows the expected result.  
However, the exported video does Location X from 0.00 at 00:00:53 to +0.20 at 0:01:00
Then, I try to change the X & Y scales from 0.5 at 00:01:15:23 to 1.0 at 00:01:20:00 but the scale does not change in the exported video.

**Comment by kubko32459** [comment]
If I cut clip, then preview render same video without any changes.

Ubuntu 18.04.2 LTS
GNOME: 3.28.2
Memory: 15.6 GiB
Processor: Intel® Core™ i7-5500U CPU @ 2.40GHz × 4 
Graphics: Intel® HD Graphics 5500 (Broadwell GT2)
OS: 64-bit
Disk: 249.9 GB

**Comment by DylanC** [comment]
@ertufa @cmoralesmx @kubko32459 - Can ye guys try v2.4.4? I believe it has fixes for keyframes in it.
https://github.com/OpenShot/openshot-qt/releases/tag/v2.4.4

**Comment by kubko32459** [comment]
@DylanC 
I have the latest v2.4.4.

**Comment by DylanC** [comment]
@kubko32459 - Do the keyframes work at least?
