### ISSUE TITLE
Why new projrct not opening?

### ISSUE THREAD

**Issue by gauravojha1** [OpenShot/openshot-qt#2685]
**Question:**
A clear and concise question, with enough context and explanation for people to answer it.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your question. You can include screenshots by
copy/pasting them here, dragging-and-dropping into this form, or clicking below and loading
images saved to your computer. All images are public, so please don't post screenshots
containing personal information.

**Comment by DylanC** [comment]
@gauravojha1 - Can you try v2.4.4 and let us know how you get on?
