### ISSUE TITLE
Setting a keyframe freezes program

### ISSUE THREAD

**Issue by kzar79** [OpenShot/openshot-qt#2688]
On clips quite long (> 10 minutes, which is absolutely normal in any standard job), when a keyframe is added or changed, the program freezes for a couple of minutes. It seems the program does a lot of computations when a keyframe is added/edited, proportional to the length of the clip.

**Steps to reproduce the behavior:**
1. Create a new long (> 10 minutes) clip (also a static image)
2. Go to any frame and change a property OR
2b. Right click and create a fade-in or fade-out, or any other action that inserts a keyframe
3. The program freezes for a time proportional to the duration of the clip

**Expected behavior:**
The keyframe is immediately added/edited and the program continues working.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 2.4.3
- Operating System / Distro: Linux Ubuntu 16.04

**Comment by ctsdownloads** [comment]
Could be an issue with the specs of the PC, have you tried the same at a lower resolution/fps in your profile for testing purposes?
