### ISSUE TITLE
capturing a still picture from video

### ISSUE THREAD

**Issue by DJBaune** [OpenShot/openshot-qt#2689]
I would like to know how to capture a still picture from a video I recently created in OpenShot. 
Thank You,

**Comment by N3WWN** [comment]
If you're using a recent version of OpenShot (2.4.2 or newer, IIRC), there should be a camera icon underneath the preview window and to the right.  Clicking on that will capture a full resolution, fully rendered snapshot of the current frame in the preview window.

<img width="624" alt="image" src="https://user-images.githubusercontent.com/19431804/54614206-6849d480-4a32-11e9-9ebe-30244656669c.png">

**Comment by DJBaune** [comment]
Wow, I will try that.

Thanks.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by DJBaune** [comment]
Hey, I tried it and it works great!!! Thanks.

Question: is there a scroll wheel function for advancing or backing up
frame by frame?

**Comment by N3WWN** [comment]
I'm glad that worked out for you, @DJBaune !  

To the best of my knowledge, there's no way to use the wheel to move frame-by-frame, but you can use the <kbd>LEFT</kbd> and <kbd>RIGHT</kbd> arrow keys to do it.

**Comment by DJBaune** [comment]
Great, thanks for all your help. 😁

**Comment by DylanC** [comment]
Closing as answered. Thanks @N3WWN!
