### ISSUE TITLE
OpenShot 2.0.7 Crashes When Exporting Video (Windows 7 x64)

### ISSUE THREAD

**Issue by GT500org** [OpenShot/openshot-qt#269]
I am trying to create my first video in OpenShot 2.x (about 6 minutes long). I exported a video clip (with audio), an extra audio clip so that I could add some commentary to the first few minutes of the video, and a picture of something I mentioned in the video so that I could have it appear in the upper-right corner for a few seconds. Here's a screenshot of what OpenShot looks like with the imported content:
![openshot_video](https://cloud.githubusercontent.com/assets/18017139/17503710/045c5382-5dc0-11e6-87b4-b869a273cb22.png)

When I go to export the video, regardless of the settings I have tried, OpenShot crashes when I click on "Export Video". I have tried with the following combination of settings:

MP4/h.264 Video
1080p @60 FPS
High Quality
Audio Sample Rate 48000

MP4/h.264 Video
1080p @30 FPS
High Quality
Default Audio Sample Rate (44100)

WEBM/vpx Video
1080p @60 FPS
High Quality
Audio Sample Rate 48000

MP4/h.264 Video
1080p @60 FPS
High Quality
Default Audio Sample Rate (44100)

I even tried deleting the picture from the timeline early on, and retrying, and it didn't help. I have yet to complete a single encode. Will try in Linux, since I suspect it will probably work OK.

**Comment by PanderMusubi** [comment]
See also https://github.com/OpenShot/openshot-qt/issues/277

**Comment by GT500org** [comment]
The machine in question has 16GB of RAM and a 16GB pagefile. More info [here](https://www.gt500.org/specs/).

**Comment by jreynojustin** [comment]
OpenShot is now in Version 2.2 if you are still noticing issues in the latest version please re-open this issue letting us know.
