### ISSUE TITLE
gif files

### ISSUE THREAD

**Issue by BluCasey** [OpenShot/openshot-qt#2690]
hello im new to the program 

im trying to make a video to my song , 
and I was tryin to import a gif file but it wont play inside of program 
is there anyone that can help me with importing and exporting my song with the gif files ?

**Comment by bernardpaulus** [comment]
Hello,

I am just another user, but I would suggest you to first use another tool to do the conversion from .gif to .avi, and then import the .avi . You could use https://cloudconvert.com/gif-to-avi to do the conversion for instance.

Regards

**Comment by DylanC** [comment]
Closing as answered.
