### ISSUE TITLE
Exporting in WMV format?

### ISSUE THREAD

**Issue by cirruss** [OpenShot/openshot-qt#2694]
**Question:**
A clear and concise question, with enough context and explanation for people to answer it.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [Windows 10]

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your question. You can include screenshots by
copy/pasting them here, dragging-and-dropping into this form, or clicking below and loading
images saved to your computer. All images are public, so please don't post screenshots
containing personal information.

**Comment by cirruss** [comment]
Please can someone explain how to export a video in WMV format as it doesn't appear to be an option available upon export, even when checking advanced settings?

Any help or URLs to help would be much appreciated.

**Comment by RoestVrijStaal** [comment]
My apologies for breaking in this issue as a visitor, but @cirruss do you mean the [codec](https://en.wikipedia.org/wiki/Windows_Media_Video) or the [container](https://en.wikipedia.org/wiki/Advanced_Systems_Format)? 

Why do you want to export a WMV? Nowadays there are better video codecs who compress better while preserving a bigger quality  and video containers which have more features and are more supported by other devices.

**Comment by DylanC** [comment]
@cirruss - I would recommend to export to a different format. @RoestVrijStaal - Visitors are more than welcome to respond to issues. We always have too many issues to handle. :+1:

**Comment by cirruss** [comment]
Hi!  It is for the students who are sitting an AS ICT exam, they are asked
to export as .WMV file format.

**Comment by DylanC** [comment]
@cirruss - I see. Do you have a reason to export to that format? I don't see why ye don't just export to .mp4 format. I guess you could always use a video converter to convert to wmv.

**Comment by eisneinechse** [comment]
In the export window chose Advanced Settings and change the video and audio settings:
Video Settings: Video Format "wmv" ; Video Codec "msmpeg4"
Audio Settings: Audio Codec "wmav2"

Starting from version 2.4.4 you could also make your own custom presets. Like this one. Call it something like format_wmv_msmpeg4.xml and store it in .openshot_qt/presets, then (re)start openshot-qt and you should have a preset for WMV:

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE openshot-export-option>
<export-option>
	<type translatable="True">All Formats</type>
	<title translatable="True">WMV</title>
	<videoformat>wmv</videoformat>
	<videocodec>msmpeg4</videocodec>
	<audiocodec>wmav2</audiocodec>
	<audiochannels>2</audiochannels>
	<audiochannellayout>3</audiochannellayout>
	<videobitrate
	 low="50 crf"
	 med="23 crf"
	 high="0 crf"></videobitrate>
	<audiobitrate
	 low="96 kb/s"
	 med="128 kb/s"
	 high="192 kb/s"></audiobitrate>
	<samplerate>48000</samplerate>
</export-option>

**Comment by DylanC** [comment]
@eisneinechse - Much better suggestion. Thanks. :+1:

**Comment by goldenkimucc** [comment]
I've noticed that WMV uploads to youtube faster and more reliably
