### ISSUE TITLE
Problem with Croma Key adding a video

### ISSUE THREAD

**Issue by agensmedia** [OpenShot/openshot-qt#2695]
When I add a video to create a chroma key effect, the video appears as if it had an applied zoom, bigger than normal, sometimes the head of the person is cut off.
I have tryed unintalling the programa etc.
Could you please help me?

**Comment by DylanC** [comment]
@agensmedia - What version of Openshot is this? Can you try it in v2.4.4 if your version is older?

**Comment by agensmedia** [comment]
Hi first at all thanks you very much!!

My Openshot is v2.4.3 I will try with 2.4.4 and I´ll tell you.
Thanks you very much again,

**Comment by mikelacsa** [comment]
@agensmedia 

I just want to check if you're still experiencing this issue?

**Comment by agensmedia** [comment]
yes

- 

El 2019-11-16 22:43, mikelacsa escribió:

> @agensmedia [1] 
> 
> I just want to check if you're still experiencing this issue? 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].
 

Links:
------
[1] https://github.com/agensmedia
[2]
https://github.com/OpenShot/openshot-qt/issues/2695?email_source=notifications&amp;email_token=ALUHZULE2AV5XEKPNRJ6VTDQUBSONA5CNFSM4HAENBJKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEH3G5Y#issuecomment-554677111
[3]
