### ISSUE TITLE
Video with no Audio? - On Purpose!

### ISSUE THREAD

**Issue by StevieB31** [OpenShot/openshot-qt#2696]
Hi Everybody, I'm pretty new to OpenShot and happy with the software so far from a video editing perspective.  I want to create a video with NO audio (on purpose), but I have background noise etc from the video files.  Do i have to create a "blank Audio file" and overlay it as a separate track or is there the ability to mute/remove the audio within the software?

Thanks, 

Steve

**Comment by DylanC** [comment]
@StevieB31 - RIght click on the video clip(s). Volume >> Entire Clip >> Level 0%.

**Comment by StevieB31** [comment]
Thanks Dylan.  Gotta admit, I feel I should have dig a little deeper before I posted the question now the answer is pretty obvious.  Thanks for the comment and getting me going in the right direction.
Thanks!!

**Comment by DylanC** [comment]
@StevieB31 - No probs. I'm only coming back to the project just now. So I'm catching up on some old questions here.
