### ISSUE TITLE
OpenShot in Mavericks OSx

### ISSUE THREAD

**Issue by hide2424** [OpenShot/openshot-qt#2699]
Hello,
I try to install the Openshot to mavericks,but it doesn't work. I wanted to give a donation as well. 
My OSX is Mavericks in a macbook pro 2014 .
Thank you very much
Chris

**Comment by ctsdownloads** [comment]
Do you mean it won't start the software? If this is the case, remove the program and the original installer, then re-download again to see if this helps.
