### ISSUE TITLE
Holding Shift, Ctrl or Command for selecting/deselecting clips?

### ISSUE THREAD

**Issue by jarlarntzen** [OpenShot/openshot-qt#27]
Dragging a marquee / select rectangle to select clips works just fine in many cases but for finer control amongst lots of clips it's quite fiddly.

**Example**: There are 5 clips inside the select rectangle but I only want to move 4 of them. Solution: I have to select and move the clips in at least 2-3 iterations to avoid moving my unwanted clip with them.

**Comment by nwgat** [comment]
i agree

**Comment by jonoomph** [comment]
CTRL + click has been added to transitions and clips on the timeline. Currently, it only works for adding items to your selection... and doesn't remove the item if CTRL + clicked a 2nd time. But it feels pretty good to have this option now, when trying to select a few very specific items before deleting or moving them.

**Comment by jarlarntzen** [comment]
Great stuff! Looking forward to test this. Any plans to add deselect as well? (Just before anyone reports that too as a bug, I mean :) )
