### ISSUE TITLE
Video preview not working - clip 16x speed forward

### ISSUE THREAD

**Issue by KvaGram** [OpenShot/openshot-qt#270]
I decided to try the newest version of openshot. My previous experience was with version 1.4.3
I went ahead and started editing a timelapse-recording. It was a simple edit.

Just set it to x16 speed forward, and add a watermark showing the speed.
However when trying to use the video preview, it seems to load for a minute, than play maybe a second before stopping to load again. It seems the preview fails to handle the speedup video correctly.
version 1.4.3 did this just fine.

**Comment by jreynojustin** [comment]
@KvaGram We've made some improvements to this feature in our latest builds. Take a look and let us know if you're still running into issues by re-opening the issue!

**Comment by KvaGram** [comment]
Thank you. Although I have long since moved to using lightworks for video
editing.
Wish you luck with OpenShot.
