### ISSUE TITLE
OpenShot 2.4.4 requires nonexistent libopenshot 0.2.3?

### ISSUE THREAD

**Issue by ferdnyc** [OpenShot/openshot-qt#2702]
**Describe the bug:**
After test-building an updated `openshot-qt` for Fedora from the 2.4.4 release tarball, I launched it and got the following dialog:

![image](https://user-images.githubusercontent.com/538020/54855199-ce9d5400-4ccb-11e9-8c52-5b61781247c5.png)

But, there doesn't appear to be a `libopenshot-0.2.3` release listed at https://github.com/OpenShot/libopenshot/releases

**Comment by jonoomph** [comment]
Oops, that doesn't sound right

**Comment by jonoomph** [comment]
I think I got so distracted with trying to update the Debian packaging and our PPA, I forgot to actually tag the libopenshot-audio and libopenshot releases. Working on that now!

**Comment by jonoomph** [comment]
@ferdnyc Okay, here we go. Sorry about that.

- https://github.com/OpenShot/libopenshot/releases (v0.2.3)
- https://github.com/OpenShot/libopenshot-audio/releases (v0.1.8)
