### ISSUE TITLE
Is it possible to use OpenShot Cloud for only rendering?

### ISSUE THREAD

**Issue by ThomasBerends** [OpenShot/openshot-qt#2705]
**Question:**
Is it possible to upload the .osp file + project files to the OpenShot Cloud and let it render there?

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 2.4.4
- Operating System / Distro: Windows 10

**Comment by DylanC** [comment]
@ThomasBerends - I think so but I wouldn't know enough about cloud stuff to give a definitive answer. @jonoomph  ?

**Comment by ferdnyc** [comment]
@ThomasBerends I believe the answer to the question is "yes". If I'm understanding correctly what you're asking (or were asking, four months ago), that's basically the entire purpose of the Cloud API.

Regardless, the easiest way for anyone to determine the answer would be to visit the demo instance at http://cloud.openshot.org/ (login: `demo-cloud`, password: `demo-password`, any data created/submitted is deleted after 12 hours) There you can experiment with the API directly.

The other easiest way would be to peruse the API docs at http://cloud.openshot.org/doc/

Closing the question as hopefully answered, and very old regardless.
