### ISSUE TITLE
How do you change the aspect ratio?

### ISSUE THREAD

**Issue by thespiceguy** [OpenShot/openshot-qt#2706]
**Question:**
How do i change the aspect ratio/format? as in like 1:1 3:4 and so on. it seems to eb stuck in this default mode

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: Windows 10

**Comment by DylanC** [comment]
@thespiceguy - Change the export profile in Profile settings.
