### ISSUE TITLE
Setting Preferences for showing with an aspect ratio of 16:9 (Widescreen) and a resolution of 1280 × 720 pixels?

### ISSUE THREAD

**Issue by cirruss** [OpenShot/openshot-qt#2708]
**Question:**
A clear and concise question, with enough context and explanation for people to answer it.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your question. You can include screenshots by
copy/pasting them here, dragging-and-dropping into this form, or clicking below and loading
images saved to your computer. All images are public, so please don't post screenshots
containing personal information.

**Comment by cirruss** [comment]
Studnets using this for their AS ICT exam and they are asked to set this aspect ratio, it isn't listed as an option, any ideas for manually setting this?

**Comment by N3WWN** [comment]
The aspect ratio and resolution for the project as set by the project profile.  You can set that with the small icon that looks like two pieces of film or `File`->`Choose Profile`.

**Comment by DylanC** [comment]
Answered.
