### ISSUE TITLE
 output format

### ISSUE THREAD

**Issue by gini253** [OpenShot/openshot-qt#2709]
Hi 
I am using the open shot for my private movie clips. When I insert them in a new project and then export it, I can't figure out, how to get the same output format as the input format. the clips are not in good quality since they are quite old. When I insert two clips with 222 mb each and export them as one (with no other options), I only get 900 mb or 145 mb. This is nothing like the 450 mb it should be, not even close. Is it possible to use an option like "use input format"?

**Comment by ctsdownloads** [comment]
> I am using the open shot for my private movie clips. When I insert them in a new project and then export it, I can't figure out, how to get the same output format as the input format.

You would want to make sure the properties for your imported video match that of your preview profile and your export settings, under export/advanced. As for format, I assume you mean resolution, frame rate and aspect ratio?

>When I insert two clips with 222 mb each and export them as one (with no other options), I only get 900 mb or 145 mb. This is nothing like the 450 mb it should be, not even close.

File size for your export depends on factors such as bitrate, resolution, frame rate and other factors.

**Comment by learnedtocode** [comment]
I had the same feature request at #3562.

> As for format, I assume you mean resolution, frame rate and aspect ratio?

yes, and codecs and codec parameters also.
