### ISSUE TITLE
OpenShot 2.0.7 - Video preview freezes after a second with clips shot on GoPro

### ISSUE THREAD

**Issue by darren12345** [OpenShot/openshot-qt#271]
I have a bunch of 720p 25fps video clips shot on a GoPro. When I try to preview them the video preview freezes after a second or so and openshot-qt starts using 100% CPU. This also happens if I add one to the timeline and preview the project. Doesn't happen with any other videos and they play OK in Ubuntu Totem video player and in KDenLive. They are all different sizes, ranging from a few MB to a couple of GB in size but it happens on all of them.

Here's a Dropbox link to the smallest file should anyone want to try reproduce it: https://www.dropbox.com/s/1ulcob22yo2cizr/GOPR0811.MP4?dl=0

Thanks.

**Comment by jreynojustin** [comment]
OpenShot is now in Version 2.2 if you are still noticing issues in the latest version please re-open this issue letting us know.
