### ISSUE TITLE
Transitions

### ISSUE THREAD

**Issue by stevenrbtw** [OpenShot/openshot-qt#2710]
Is there a way to move favorite transitions into the Common Transitions menu?  I have only a few that I use regularly but have to scroll through the entire list of the Show All menu to select the one I want.  Somewhat inconvenient and a time waster. I can't figure out a way to drag and drop, or Copy-Paste.

Thanks,

Steven R Btw
srbtw@hotmail.com

**Comment by N3WWN** [comment]
If you have actually installed OpenShot (not running from an AppImage, etc), you can copy the files for the transitions that you want to make common from the `transitions/extra` directory to the `transitions/common` directory.  The `transitions` directory will be under the application install location, which may vary depending on your OS.

**Comment by stevenrbtw** [comment]
Thank you so much.
