### ISSUE TITLE
Capability to increase volume more than 100%

### ISSUE THREAD

**Issue by seanjmcm** [OpenShot/openshot-qt#2712]
**Describe the new feature:**
I would like the ability to increase the sound a video clip by over 100%

**Describe the solution you'd like:**
When right clicking and selecting volume, I would like to see an option for 150% and 200%

**Describe alternatives you have considered:**
Keyframing seems to be an option but it is not simple: https://gist.github.com/peanutbutterandcrackers/f0f666243133e0ed25abbc12a4ba23d7

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your request.

**Comment by N3WWN** [comment]
You don't need to get complicated with the keyframes;  select the clip that you want to increase the volume of, use the `|<` icon (located at the top left of the timeline) to make sure you're on the first frame of the clip and then double-click on the `Volume` property's current value and enter a new value.  

As long as the background of the `Volume` property doesn't turn green, you've adjusted the value for the entire track.  

If it did turn green, that means a keyframe was created.  You can remove the keyframe via a `right click` on the value and select `Remove Keyframe`.

**Comment by seanjmcm** [comment]
Hi Richard,

Thanks for your feedback, however, if I write 2.0, it simply resets to 1.0,
i.e. it is not possible to increase the volume more than 100%.

I am on windows 10.  I'd like to be able to increase it above 100%.

Rgds,
Seán

**Comment by N3WWN** [comment]
What version of OpenShot are you using?

I'm using OpenShot 2.4.4 and am able to set it to pretty much any value.   I tested 0, 0.5, 1.0, 1.5, 2.0, 5.0, 100.0, 1000.0 and 1000000.0.  Obviously the really high values totally ruined the sound, but they were accepted and used.

**Comment by SuslikV** [comment]
The mentioned reset happens if you at least once set via right-click menu the _Volume->Entire Clip->Level 100%_
So, it is rather bug report than feature request...

**Workaround:**
Right-click over the _Volume_ property and choose _Remove Keyframe_. Now it is possible to set new value for the property (1.5 , 2.0 , 3.0 etc.)

**Comment by SuslikV** [comment]
I think, that the property itself may has green border, about 2px width, to indicate that the property is animated (has at least one keyframe that was set by user). Because by looking through the properties list is hard to say which one is animated and which is not.

**Comment by tinproject** [comment]
@seanjmcm I've notice that the value is locale dependant. I'm use the spanish locale and if I input `2.0` it will reset to the original value, but if I use `2,0` is properly set to double volume.

**Comment by romgere** [comment]
It depends also on the video format I guess, I'm able to set volume to value bigger than `1` on some video, but not on `.webm` videos :thinking:

**Comment by RedDragonWebDesign** [comment]
I stumbled across this while google searching how to get the volume above 100%. After seeing it suggested in this thread, I used the `properties -> volume -> enter custom volume` trick mentioned above, which worked fine for me.

To make custom volume easier to find, may I suggest adding it to the right click menu? You could add an option in this menu called "Custom Level" or something, and clicking on it just opens the properties tab and scrolls down to volume.

![image](https://user-images.githubusercontent.com/43397938/95573110-cad13f80-09df-11eb-982b-ee8b565058bf.png)

**Comment by PrasadNR** [comment]
I do not see "Custom Level" option either.

**Comment by blackhatfx** [comment]
Hi, the "custom level" option does not display for me either.

Regards,

**Comment by Colorjet3** [comment]
Hello @blackhatfx I am not sure I've ever seen a Custom option for volume.  However, you can still set your own custom volume by:
1.  Right click on your clip on a track and select Properties.
2.  Ensure that the Playhead is aligned with the left edge of your clip.
3.  In the Properties window find the "Volume" attribute.
4.  Double click the 1.00 value and manually type 2.00 or whatever custom volume you like.

Let me know if this did the trick for you.
