### ISSUE TITLE
I don't manage to open my video

### ISSUE THREAD

**Issue by Emma3993** [OpenShot/openshot-qt#2714]
Hello, i made a video with open shot and when i save my "project" i can't open it because my computer doesn't know how to read it. What app can i use to play my video? i have the windows one but it doesn't work and "mpc hc" neither.
I'm french so maybe i don't have the same apps.
Thank you and have a good day :)

**Comment by Emma3993** [comment]
ok i'm just stupid i needed to make the file an mp4 one and not an osp one :)

**Comment by ThomasBerends** [comment]
@Emma3993 Can you close this issue because it has been solved?

**Comment by DylanC** [comment]
Answered.
