### ISSUE TITLE
Transition does not cover clips of same aspect ratio

### ISSUE THREAD

**Issue by GreyArea765** [OpenShot/openshot-qt#2715]
This seems similar to other bugs like https://github.com/OpenShot/openshot-qt/issues/1837 however I get this when transitioning between two clips of the same aspect ratio.

**Describe the bug:**
See the attached image which is a screenshot of a transition between two clips of the same aspect ratio.  The transition does not coer the edges properly.

**Steps to reproduce the behavior:**
Drag two clips into timeline, overlap each other and add any common wipe (left, right, down, up)  transition.

**Expected behavior:**
Transition should cover entire clip

**System Details:**
- OpenShot 2.4.4
- Operating System / Distro: Windows 10

**Screenshots:** (Optional)
![Capture](https://user-images.githubusercontent.com/24699077/55359522-f362aa00-54c9-11e9-9e81-9f4772544ebc.PNG)

**Comment by SuslikV** [comment]
This is only for round looking transitions (they didn't stretch), so try other transition from the list.

**Comment by GreyArea765** [comment]
You are indeed correct, any of the wipe diagonals and some of the others I've tried at random work as expected - but the fact that all of the common wipes (left, right, up, down) are unusable for footage of equal ratios seemed like a bug enough for me to report it.

**Comment by daehruoydeef** [comment]
I got same bug, it occurs for all round looking transition. Other I found which behave the same are the wipe top to wipe right to wipe left.
Fade for example is working just fine. Is there any fix yet, maybe with creating our own .svg ?
