### ISSUE TITLE
Potential drag and drop issues with Qt 5.12

### ISSUE THREAD

**Issue by ferdnyc** [OpenShot/openshot-qt#2716]
This isn't a report of any known existing problems, merely a BOLO for issues that might come up in the near future, with the hope of making them easier to solve.

[This bug report](https://gitlab.com/mbunkus/mkvtoolnix/issues/2472) against mkvtoolnix-gui alerted me to the fact that significant changes were made to drag & drop support in Qt 5.12, compared to earlier versions. (And possibly some bugs were also introduced in Qt 5.12.0, which the subsequent Qt 5.12.1 addressed.)

As a result, and as seen in [this Qt forum discussion](https://forum.qt.io/topic/97649/bug-in-qt-5-12-drag-n-drop/57), code implementing drag & drop operations which worked fine in Qt ≤ 5.11 may no longer work properly in 5.12.x. (See also [this Qt bug tracker issue](https://bugreports.qt.io/browse/QTBUG-72844).)

Qt 5.12 doesn't appear to be in widespread use yet, but it'll be arriving on Linux distros soon (if it hasn't already). I believe next month's Fedora 30 release is slated to include Qt 5.12. So, if any reports come in about drag & drop not working, it's worth at least checking the Qt version reported by OpenShot. (It can be seen in the logfile, or in the console output at launch, e.g.:)
```
$ openshot-qt
Loaded modules from installed directory: /usr/lib/python3.7/site-packages/openshot_qt
      launch:INFO ------------------------------------------------
      launch:INFO    OpenShot (version 2.4.4)
      launch:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.4.4
         app:INFO libopenshot version: 0.2.3
         app:INFO platform: Linux-5.0.4-200.fc29.x86_64-x86_64-with-fedora-29-Twenty_Nine
         app:INFO processor: x86_64
         app:INFO machine: x86_64
         app:INFO python version: 3.7.2
         app:INFO qt5 version: 5.11.3
         app:INFO pyqt5 version: 5.11.3
```

The official Windows, MacOS, and AppImage builds use whatever Qt version they're compiled with, which I believe is still 5.6 for Windows and Mac, 5.2 for the Linux AppImage. So it won't be an issue there.

**Comment by SuslikV** [comment]
OBS Studio for example, uses Qt 5.10.1 because of number of bugs in newer versions.

**Comment by ferdnyc** [comment]
@SuslikV Huh. Interesting! I'd be curious to know what those are, because the Fedora RPMFusion distro package is built against Qt 5.11.3 (in current Fedora 29) — so now I'm curious what bugs I'm subjecting myself to!
```console
$ IFS="^J"; (for dep in `rpm -q --requires obs-studio|grep -v rpmlib`; do rpm -q --whatprovides `echo "$dep"|cut -d' ' -f1`; done)|sort|uniq
ffmpeg-4.0.3-4.fc29.x86_64
ffmpeg-libs-4.0.3-4.fc29.x86_64
glibc-2.28-26.fc29.i686
glibc-2.28-26.fc29.x86_64
libcurl-7.61.1-10.fc29.x86_64
libgcc-8.3.1-2.fc29.x86_64
libstdc++-8.3.1-2.fc29.x86_64
obs-studio-libs-23.0.2-1.fc29.x86_64
qt5-qtbase-5.11.3-1.fc29.x86_64
qt5-qtbase-gui-5.11.3-1.fc29.x86_64
qt5-qtx11extras-5.11.3-1.fc29.x86_64
x264-0.155-2.20180806git0a84d98.fc29.x86_64
```

As I said, I _would_ be curious, but since their [GitHub project](https://github.com/obsproject/obs-studio) doesn't have an Issues section, there's no mention of Qt versions in the Wiki, and their [support forum](https://obsproject.com/forum/) software rejects search terms like "Qt" and "5.10" / "5.11" / "5.12" as too short (a search for "version" was unenlightening), I don't really know how to ask that question anywhere. 

(Granted, I haven't even tried just Googling for it yet, which makes me seem lazy.)

**Comment by SuslikV** [comment]
Not much.
I know about this: https://github.com/obsproject/obs-studio/pull/1610#issuecomment-470024952
OBS Studio uses own bug tracker: https://obsproject.com/mantis/view_all_bug_page.php
There was messages that high DPI handling may be not perfect. And some strange rendering behavior for Mac.

**Comment by ferdnyc** [comment]
@SuslikV Aha, thanks! Yeah we've seen some DPI scaling issues come up but those go back to any Qt 5 release, which can get weird ideas under Gnome in certain circumstances. Those styling issues don't sound like they were much fun. OpenShot doesn't use style sheets at all for the UI, tho, so I guess we're safe there. (All widget decoration is done through properties set directly on UI objects, either in the UI files or directly from the implementation code.)

The drag & drop issues in 5.12 aren't too surprising, I guess, if you read between the lines of [the 5.12 release notes](https://doc.qt.io/qt-5/whatsnew512.html). They must've gutted every part of their codebase that's involved with mouse input tracking or processing:
> * Replaced the handling of tablet/touchscreen/touchpad/mouse input with a unified implementation based on the Windows Pointer Input Messages on Windows 8 and newer. Hardware such as the screen digitizer in the MS Surface line is now supported without special drivers.
> * Pointer Handlers are renamed to Input Handlers (we include the pre-existing Keys attached property in this category) and are now fully supported as a first-class QML feature in Qt Quick. (C++ API for them is still not public yet.)
> * HoverHandler is a new type of handler for detecting mouse hover. It can detect hover even in cases of deep nesting: unlike MouseArea, you can hover multiple nested Items with HoverHandlers in them at the same time. (For example, a sidebar and an individual button on the sidebar).
> * DragHandler is now a multi-point handler: if you set minimumPointCount to 2, it will react only to a 2-finger drag, for example. This can give you another degree of freedom: single-finger drag can perform the typical item movement, and 2-finger drag can do something else (change the tilt angle, for example).
> * Dial: Added inputMode property, that adds two new ways of interacting with the Dial: horizontally and vertically. These new input modes use a relative input system that adds changes to the dial's position to its value. This results in a dial that is less "jumpy", making it safe for operations that could be harmful if done incorrectly, like adjusting audio levels.
> * Slider and RangeSlider: Added touchDragThreshold property for configuring the threshold to initiate the touch 'drag' of the handle of the slider. The mouse 'drag' is not affected by the property.

**Comment by ferdnyc** [comment]
I'm going to close this, since nothing seems to have come of it so far. Multiple Linux users are running OpenShot under Qt 5.12.x with no reports of anything changing or not working properly. And, while that doesn't cover the very large majority of Windows users who are still using the installer's bundled Qt 5.9.x, there's no real timeframe for when or if the Windows and Mac builds will be upgraded to FFmpeg 5.12... an when that happens, if there are any problems then a closed bug report can be searched for just as easily as an open one.
