### ISSUE TITLE
Program crashes when MP3 audio is previewed

### ISSUE THREAD

**Issue by JBN13** [OpenShot/openshot-qt#2717]
**Describe the bug**
crash at preview

**Steps to reproduce the behavior:**
1. Go to import media.
2. Select an audio MP3 file.
3. Add the MP3 file to a track in the video.
4. Press play in the preview video field.
5. The program crashes.

The system also crashes under these circumstances:
1. Go to import media.
2. Select an audio MP3 file.
3. Right click on the audio file in the imported media window. 
4. Select preview.
5. The program crashes.

**Expected behavior**
I expected to see my video preview or hear my audio file preview.
                
**System Details**
- OpenShot Version: 2.4.4
- libopenshot Version:  0.2.3
- Platform: Windows-10-10.0.17134
- Processor: Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
- Machine: AMD64
- Python version: 3.6.4
- Qt5 version: 5.9.1
- PyQt5 version: 5.9
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.4.4-1553153504-d04a71ee-fbfac789-x86_64.exe

**Log Files**
- http://logs.openshot.org/zzjkurnv1o5rw4h60gsm3r72gefjj4km/openshot-qt.zip
- http://logs.openshot.org/zzjkurnv1o5rw4h60gsm3r72gefjj4km/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.
                
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/3031873/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/3031874/openshot-qt.log)

**Comment by SuslikV** [comment]
What do you mean by crash? How it looks like?

**Comment by JBN13** [comment]
The program completely shuts down. I have to re-open it to try to edit my video again. 
FYI, I tried adding a different type of audio file, and the video previewed and exported without shutting down the program. 


- Jersha

On Tuesday, April 2, 2019, 1:06 AM, SuslikV <notifications@github.com> wrote:


What do you mean by crash? How it looks like?
