### ISSUE TITLE
 Split Clip Player Loads Only First Half of Video Twice

### ISSUE THREAD

**Issue by craigjaneway** [OpenShot/openshot-qt#2718]
**Describe the bug**

Split Clip player stops midway and will not play the remainder of the video.   Using another player to find clips of the second half revealed first half had replaced the second half of the file in the Split Clip player.  I was not able to use it to pull clips from the second half of the video.

**Steps to reproduce the behavior:**
1. Load video file.
2. Right-click and select Split Clip.
3. In the player, move the slider to just before midway.
4. Press play.
5. The player stops and will not play past midpoint.
6. Selecting a section of the non-playing second half is a clip from the first half of video.

**Expected behavior**

**System Details**
- OpenShot Version: 2.4.4
- libopenshot Version:  0.2.3
- Platform: Windows-10-10.0.17763
- Processor: Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
- Machine: AMD64
- Python version: 3.6.4
- Qt5 version: 5.9.1
- PyQt5 version: 5.9
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.4.4-1553153504-d04a71ee-fbfac789-x86_64.exe

**Log Files**
- http://logs.openshot.org/bbyr3s06lv0t58zs2bghpj1zczc78kz3/openshot-qt.zip
- http://logs.openshot.org/bbyr3s06lv0t58zs2bghpj1zczc78kz3/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by SuslikV** [comment]
Your steps to reproduce is not clear.

For example:
What do you mean by "load video file"?
What do you mean by "select Split Clip"?

There is option _Slice -> Keep Both Sides_ - it slices the source clip at current position into two separate clips (still aligned in timeline).
