### ISSUE TITLE
Openshot Video and Audio are out of line

### ISSUE THREAD

**Issue by JulioMoiloino** [OpenShot/openshot-qt#272]
Video and Audio are separated and the audio does not match the video. I was told to fix this by duplicating the movie and separating the audio and video. How is this done on OpenShot 2.0.

-AnnoyedWithOpenShot

**Comment by JtLively** [comment]
To answer your question -
1. Add the same video to track 1 and 2
2. Mute the video on track 1 via timeline settings
3. Hide the video on track 2 via timeline settings
4. Slide one of the track blocks as needed

Please open a new issue if you have any other issues with the newest version.
