### ISSUE TITLE
Interrupting the audio track during editing (Give your bug report a descriptive title)

### ISSUE THREAD

**Issue by hcroze** [OpenShot/openshot-qt#2724]
**Describe the bug**
Interrupting the audio track during editing

**Steps to reproduce the behavior:**
In edit and test mode
1) Single audio track working properly alone
2) I add a series of images on another track
3) Now the audio track is jerky
Fortunately the video produced works properly
The bug did not occur with the previous version

**Expected behavior**
Normal progress of the audio track during editing

**System Details**
- OpenShot Version: 2.4.4-dev1
- libopenshot Version:  0.2.3
- Platform: Windows-10-10.0.15063
- Processor: Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
- Machine: AMD64
- Python version: 3.6.4
- Qt5 version: 5.9.1
- PyQt5 version: 5.9
- Qt Detected Languages: ['fr-FR', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.4.4-dev1-1554501663-4c5851df-7001b687-x86_64.exe

**Log Files**
- http://logs.openshot.org/4y41gkrgz7kjkmpj2w1b3c2mo3l2i8xf/openshot-qt.zip
- http://logs.openshot.org/4y41gkrgz7kjkmpj2w1b3c2mo3l2i8xf/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Comment by RyotaFujikawa** [comment]
I am also having the same problem with adding images and making the audio track jerky :(
