### ISSUE TITLE
Custom SVG title with adaptive text

### ISSUE THREAD

**Issue by ThomasBerends** [OpenShot/openshot-qt#2726]
**Question:**
I've created a custom .svg file with text inside of it. I can load this in OpenShot without any problems by following the documentation here:
https://www.openshot.org/static/files/user-guide/titles.html

However, this guide doesn't explain how to make the text editable. I can edit the text, and it shows up in the preview. However, the 'Save' button doesn't work anymore after I edited the text.

I'm trying to create custom overlays for my video's, but the text inside of them needs to be changeble. What do I need to do in my SVG file to make the text changeble?

Of course, when I get an answer to this, and it works, I'll update the docs to include this information.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: Newest
- Operating System / Distro: Windows 10

**Comment by SuslikV** [comment]
Try this one: [drawing002.zip](https://github.com/OpenShot/openshot-qt/files/3062157/drawing002.zip) is it works for you?

Please provide your file sample.

**Comment by ThomasBerends** [comment]
@SuslikV Thanks for taking the time to answer.

Your file works yes, my SVG file just contains this (simplified version with still the problem present):

`<svg aria-hidden="true" focusable="false" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1280 720">
   <text x="50" y="702" fill="#ffe200" font-size="24"><tspan>OVERLAY_TEXT</tspan></text>
</svg>`

This results in the following:
![openshot-2726](https://user-images.githubusercontent.com/1807910/55900948-9d2bf000-5bc8-11e9-9b0e-993aea14893e.png)

And clicking the 'Save' button does nothing.

**Comment by SuslikV** [comment]
Add at least empty parameter `style=""` to your file:

`<svg aria-hidden="true" focusable="false" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1280 720"> <text x="50" y="702" fill="#ffe200" font-size="24" style=""><tspan>OVERLAY_TEXT</tspan></text> </svg>`

or in right way

`<svg aria-hidden="true" focusable="false" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1280 720"> <text x="50" y="702" style="font-size:24px;fill:#ffe200;"><tspan>OVERLAY_TEXT</tspan></text> </svg>`

By the way, what editor are you using for making SVG files? I recommend Inkscape (at least v0.92).

**Comment by ThomasBerends** [comment]
That's working, thank you!

I'm not using any editor besides a text editor. I've done XML in my job for most of my life so for a few simple overlays I thought I just write it myself.
