### ISSUE TITLE
How do I move a project to another computer?

### ISSUE THREAD

**Issue by BrokenHouseAirline** [OpenShot/openshot-qt#2727]
Created a video with OpenShot, but I needed to move it to another computer. When I try to open the project, it tells me it can't see the files associated with the project (requires an End Task just to get out of the endless loop of errors too). I've copied all the original files to the computer, but it still doesn't see the files.

**Comment by SuslikV** [comment]
Do you copied whole folder of the project? You may hold _Esc_ button until all errors gone...

**Comment by ferdnyc** [comment]
This was fixed in commit bdd2135 which will be included in the next release of OpenShot. Once you select the directory where your disconnected file can be found, all files in that directory will be recovered automatically.
