### ISSUE TITLE
Link for 'Ask a Question' on webpage is wrong

### ISSUE THREAD

**Issue by RasmusWL** [OpenShot/openshot-qt#2728]
**Steps to reproduce the behavior:**
1. Go to https://www.openshot.org/
2. Click on `Support > Ask a Question` 
    ![image](https://user-images.githubusercontent.com/1054041/55875111-7d7ad480-5b94-11e9-9341-1167758ed6a9.png)

3. This takes you to https://github.com/OpenShot/openshot-qt/issues/new?template=i-have-a-question.md

**Expected behavior:**
it should take you to https://github.com/OpenShot/openshot-qt/issues/new?template=question.md

**Comment by ferdnyc** [comment]
This has been fixed, that selection now links to the [OpenShot subreddit](https://www.reddit.com/r/OpenShot/).
