### ISSUE TITLE
Zoom on picture-in-picture clip, without changing shown size

### ISSUE THREAD

**Issue by RasmusWL** [OpenShot/openshot-qt#2729]
**Question:**

How can I apply a zoom effect to a clip, without changing the dimension shown? As an example, I try to display Lenna on top of the OpenShot logo, and I want to zoom in on Lenna without covering up more of the OpenShot logo. Example of what I'm looking for can be seen [here](https://www.youtube.com/watch?v=9C_hE-xqDlc&t=3)

![example](https://user-images.githubusercontent.com/1054041/55875609-c2533b00-5b95-11e9-8cb4-549b0909f5d4.png)

**Attempts at solving the problem**

I tried 3 approaches:

* _naive_: apply linear transition of scale x/y of `1.0 -> 2.0`, and linear crop of all sides `0.0 -> 0.25`. This didn't work at all, since at half the transition more of the video will be shown _(crop for all sides will be at `0.125`, scale at `1.5`, shown area in one dimension is `1.5 - (1.5 * 0.125 * 2) = 1.125`)_ [result video](https://youtu.be/nv13Wc2QTZI)
* _manual crop values_: since the naive approach didn't work, I created a script to calculate the proper scaling values for each frame, and inserted these into the project json `.osp` file. _(for example, halfway needs a scale of `(1.0 - (1.0 / 1.5)) / 2 = 0.16666666666666669` for each side)_. This almost does what I want, except for the fact that the dimensions is not completely constant. If you look at the left edge of the Lenna picture in the [result video](https://youtu.be/s7Izfx4RiEQ), you can see that it jumps back and forth a bit.
* _mask_: I applied a mask to the Lenna clip, by following the [mask guide](https://www.youtube.com/watch?v=Hd9k3x0diOo). However, the mask is scaled together with the clip. I can understand this is probably what you want most of the time if you're displaying only part of the video. [result video](https://youtu.be/PShm6WR43m8)

Is it is possible to achieve this effect with OpenShot? :blush:

I can see one work-around; by doing the animation in an other project with the wanted dimensions, exporting this to a video, and importing into the original project. However, since I'm trying to automate the whole process with the openshot-api, I would rather not have to go through this :neutral_face: 

**System Details:**
- OpenShot Version: 2.4.4
- Operating System / Distro: Ubuntu 18.04

**Other Details**:

I found an example for how to do this with [After Effects](https://forums.adobe.com/thread/1240096).

**Comment by SuslikV** [comment]
Usually, the order of layers need to be changed and background clip with the "hole" in the middle is the best solution.

**Comment by RasmusWL** [comment]
Thanks for the input @SuslikV. I can see that this can work for my MWE, and it should be applicable to my actual problem as well.

However, I don't think it's more of a hack than an actual solution to the core of this problem. It will not work if you want to add a transition to the location/rotation of Lenna, or transition to location/rotation of the OpenShot logo.

I think a solution to the core of this problem, could be to allow changing scale/location/rotation of the mask (by default, it could mirror the clip. solving my problem would just be making scale constant = 1.0)

**Comment by jonoomph** [comment]
We could add an additional property to effects, to render them before we scale the clip image. That combined with the crop effect, would allow the image to scale, but the crop to remain fixed (in theory). Not sure how well this would work in reality, but it's a possibility. :smile:

**Comment by RasmusWL** [comment]
I think I understand your point. We could figure out the viewport that should be displayed by the crop effect _before_ scaling the image. So by setting `{left,right,top,bottom}_crop=0.0`, we will only show the same part that was shown on the first frame of the crop effect.

I don't know the internals of OpenShot, so I don't know if this is a good solution :smile: 

For now, the "solution" that SuslikV came up with works for my specific case.
