### ISSUE TITLE
Both openshot and openshot-qt losting audio when I undo all modification on audio track.

### ISSUE THREAD

**Issue by antoflav** [OpenShot/openshot-qt#273]
I verified this behavior in openshot v. 1.4.3-1.2 and openshot-qt v. 2.0.7+0+615+100+201603300517. When I do some modification on audio track (eg. cut clip, remove clip, etc.), than, if I undo all modification, the audio is no longer heard. I have to clear the entire audio track and reload it back on timeline.

Best regards.

Flavio

**Comment by jonoomph** [comment]
This should be fixed now. Please retest with our latest daily build, and re-open this issue if it still occurs, along with the Operating System version. Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot. Thanks!
