### ISSUE TITLE
Convert Audio from Mono to Stereo

### ISSUE THREAD

**Issue by asjones987** [OpenShot/openshot-qt#2730]
I have a video recording that was recorded off a mixer that came in mono (right speaker only). I would like the audio to come out of both speakers (I know not true "stereo"). How can I convert the audio in the video to play on both left/right?

What are my options? In general I would prefer to do it all in OpenShot. I did some digging around the audio option,s but did not see anything yet.

Thanks for your help and ideas

**Comment by ThomasBerends** [comment]
As far as I know, you can't do this in OpenShot. You can however do this in Audacity, there's a tutorial here:
https://chacadwa.com/foh/mono-to-stereo-in-audacity

**Comment by SuslikV** [comment]
It is quite possible. You need to remap the channels end Enable Audio (of them, while muting/disable Audio from the main clip).  This is not simple, but it's possible.

You need right-click menu over the selected clip -> _Separate Audio_ -> _Multiple Clips (each channel)_ - two new clips appear (channel 1 and channel 2) if source is stereo.

1. Copy/Paste the track with actual sound.
2. Delete the silent track.

Properties of the original clip:

3. _Enable Audio_ -> 0 (whole clip) - to mute it.

Properties of the two audio clips (single channel and its copy):

4. _Enable Audio_ -> 1 (whole clip) - to hear it.
5. _Channel Mapping_ for one clip -> 0; for another clip -> 1 - this is for stereo output (left and right audio channels)

It is easier to duplicate the audio channel during capture (depending on recording software). What program are you using to capture?

**Comment by asjones987** [comment]
Wow interesting... camera has a mono cable going into it... we are looking at getting a stereo to mono cable to fix the problem, but older stuff is just mono.
