### ISSUE TITLE
Will not accept selected profile

### ISSUE THREAD

**Issue by VictorMature** [OpenShot/openshot-qt#2731]
*From website bug report--the relay to Github did't work*
**Describe the bug**
Openshot will not change the default profile. I'm editing NTSC 640x480 (Preview window is anamorphic at 720x480); when I set the profile to VGA NTSC in Edit > Preferences and restarted the software, the preview screen came in at 854x480, a 16:9 aspect ratio. When I  chose the VGA NTSC (640x480) profile in File > Choose Profile, no change. The only time the preview window can be sized with no bars is at the 16:9 aspect ratio. Exporting at 640x480 I get bars at the top and bottom.
Once I got a weird result, an edit preview of 968x480, with no change in profiles.
I've had the software for 3 weeks or so, and I successfully edited two videos before it started acting up. Openshot was editing normally, with a 720x480 preview window and a successful export at 640x480, on 4/8/2019 (gesture_w_sumi_vlc_screeencap.jpg). Yesterday (4/9/2009) the aspect ratio in preview was screwy. I opened one of the previous, successful files, and it looked right once, but not after closing and opening it (preview_window_vid_6.jpg).
Today I uninstalled and reinstalled Openshot, with no change.

**Steps to reproduce the behavior:**
1. Start new project, or open an existing one 
2. The preview window will display at 16:9
3. Click on 'Edit preferences', select 'Profiles' tab
4. Scroll down to 'VGA NTSC' and restart software.
5. Preview window will still be at 16:9.
6. Nothing on God's green Earth will change this.

**Expected behavior**
I expected the preview window to display at 720x480, with the DV NTSC 640x480 video filling the screen.

![preview_window_vid_6](https://user-images.githubusercontent.com/44735211/55919230-b9289500-5bba-11e9-88d2-f652a82407e9.jpg)
![gesture_w_sumi_vlc_screeencap](https://user-images.githubusercontent.com/44735211/55919238-c0e83980-5bba-11e9-9d67-5dd3cf4dbbc5.jpg)

**System Details**
- OpenShot Version: 2.4.4-dev1
- libopenshot Version:  0.2.3
- Platform: Windows-10-10.0.17134
- Processor: AMD64 Family 21 Model 56 Stepping 1, AuthenticAMD
- Machine: AMD64
- Python version: 3.6.4
- Qt5 version: 5.9.1
- PyQt5 version: 5.9
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.4.4-dev1-1554582998-101f25a7-7001b687-x86_64.exe

**Log Files**
- http://logs.openshot.org/o6zg7vptmchmlzatdblu3pcev1a9pn00/openshot-qt.zip
- http://logs.openshot.org/o6zg7vptmchmlzatdblu3pcev1a9pn00/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

            

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them here, dragging-and-dropping into this form, or clicking below and loading
images saved to your computer. All images are public, so please don't post screenshots
containing personal information.

**Comment by ctsdownloads** [comment]
Is this still an issue in the current version of OpenShot?

**Comment by VictorMature** [comment]
I had to go with another package. Openshot has a good interface and it will be great when it gets figured out.
