### ISSUE TITLE
Unable to open saved file, project file invalid load key, '\x00'.

### ISSUE THREAD

**Issue by RoyMonroe** [OpenShot/openshot-qt#2733]
I was working on a project and just when I finished the application stopped responding then closed. My desktop itself was unresponsive so I restarted it. When it came back, the project wouldn't open, but other ones would.

1. Open openshot
2. Try to open .osp file
3. See error project file invalid load key, '\x00'.
There is nothing in the recent projects bar

**System Details:**
- OpenShot Version v2.4.4
Windows 10

[BradyCast..zip](https://github.com/OpenShot/openshot-qt/files/3066447/BradyCast.zip)

**Comment by SuslikV** [comment]
Your project file is just empty data file. No useful info in it. Just delete it and start new project. Usually, this kind of errors caused by RAM of your PC (either there is no free space left for the application or general PC failure). Save backups of your projects during work.

**Comment by puneetav** [comment]
[Online Celebration.zip](https://github.com/OpenShot/openshot-qt/files/5428780/Online.Celebration.zip)
Received the same error.. the project was saved multiple times and suddenly the editor crashed and now just unable to open. any help appreciated.
