### ISSUE TITLE
Top/bottom of clip not displayed in preview

### ISSUE THREAD

**Issue by lotekfinc** [OpenShot/openshot-qt#2734]
**Question:**
A clear and concise question, with enough context and explanation for people to answer it.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your question. You can include screenshots by
copy/pasting them here, dragging-and-dropping into this form, or clicking below and loading
images saved to your computer. All images are public, so please don't post screenshots
containing personal information.

**Comment by lotekfinc** [comment]
I made a video using my smartphone with the long-side being vertical.  When I load the video into OpenShot it loads with the correct orientation but it clips the top and the bottom of the video.

**Comment by lotekfinc** [comment]
![image](https://user-images.githubusercontent.com/49522777/55957627-ca15ec80-5c34-11e9-8c44-4f03fb8133bb.png)

**Comment by SuslikV** [comment]
What is your main menu _Edit>Preferences>Profiles tab>Default Profile_ setting?
What you have set at clip's _Properties>Scale_ ?

**Comment by DylanC** [comment]
@lotekfinc ^
