### ISSUE TITLE
Non-ReSVG rendering of SVG files worsened in 2.4.4?

### ISSUE THREAD

**Issue by ferdnyc** [OpenShot/openshot-qt#2739]
So, maybe this is known/expected, but it seemed a bit odd to me.

SVG rendering in OpenShot 2.4.4 builds _without_ ReSVG seems to be **worse** than 2.4.3? 

Obviously, with ReSVG enabled it's far improved, which is great.

But here are some screenshots I posted to OpenShot/libopenshot#143, when we were comparing QtSVG to ReSVG:

![image](https://user-images.githubusercontent.com/538020/56098178-d4054d00-5ecb-11e9-8bd9-823161d9e3cf.png)

![image](https://user-images.githubusercontent.com/538020/56098181-d8316a80-5ecb-11e9-9a52-33df10e9d864.png)

And now here's that same Title in the Fedora 29 RPM Fusion build of OpenShot 2.4.4 (which unfortunately can't yet be linked with ReSVG due to the distro's rust support still lagging behind...):

![image](https://user-images.githubusercontent.com/538020/56098233-686faf80-5ecc-11e9-9448-376172993539.png)

![image](https://user-images.githubusercontent.com/538020/56098243-7c1b1600-5ecc-11e9-8d92-b52c5ef191d2.png)

If I modify the text color, the reflection _sort of_ appears, but the white outline around the text never does:

![image](https://user-images.githubusercontent.com/538020/56098371-e1bbd200-5ecd-11e9-9b64-43e8377311f0.png)

This is how the original, un-modified title image looks in Inkscape with checkerboard transparency:

![image](https://user-images.githubusercontent.com/538020/56098351-a4574480-5ecd-11e9-91be-7328be9832f4.png)

**Expected behavior:**
The same crappy rendering we've come to expect, I guess? If QtSVG isn't rendering the SVG files in non-ReSVG OpenShot 2.4.4, then what _is_?

**System Details:**
- OpenShot Version : 2.4.4
- Operating System / Distro: Fedora 29 x86_64, installed from RPM Fusion package

**Comment by ctsdownloads** [comment]
Still a bug in current version? Just sorting these old issues.
