### ISSUE TITLE
openshot 2.0.7 not showing transitions

### ISSUE THREAD

**Issue by jack-craig-aptos** [OpenShot/openshot-qt#274]
hi all,

i just installed 2.0.7 on my fedora 23.

i am finding transition not showing

also transition properties not found

what am i doing wrong?

tia, jackc...

**Comment by jreynojustin** [comment]
OpenShot is now in Version 2.2 if you are still noticing issues in the latest version please re-open this issue letting us know.

**Comment by jack-craig-aptos** [comment]
i just upgraded from f23 -> f25, i'll retest, thx!!
