### ISSUE TITLE
PNG Sequence Will Not Fully Import

### ISSUE THREAD

**Issue by jetpack-toast** [OpenShot/openshot-qt#2740]
**Describe the bug**
I have a folder which contains a series of PNG images (001.png through 020.png) which make up a small animation of a cheese wedge jumping from the middle of the screen to the lower right corner. When I import this PNG sequence into OpenShot, it is placed in the project files pane. When I try to preview the file or add it to the timeline and play the video, the animation only contains unique frames from 001 up to 010. The frames 011 through 020 are just duplicates of frame 010. Because of this, the cheese wedge stops before ever making it to the lower right corner of the screen as the full animation is not imported. The PNG images were generated by Blender, but I have tried generating them through Inkscape as well and got the same result.

The attached screenshots show every fifth frame of the animation from the preview window. Notice how frames 10, 15, and 20 are all the same. The actual 15th and 20th frames are attached as well as the original PNG files.

Any help would be greatly appreciated! Thank you guys for such an awesome application!

![cheese_animation_frame_1](https://user-images.githubusercontent.com/43581768/56182690-8aeaf100-5fd0-11e9-9cfd-8dad9538b7a5.jpg)
![cheese_animation_frame_5](https://user-images.githubusercontent.com/43581768/56182691-8aeaf100-5fd0-11e9-8aff-3effa71c0888.jpg)
![cheese_animation_frame_10](https://user-images.githubusercontent.com/43581768/56182692-8aeaf100-5fd0-11e9-9cfe-eeab8233a6e2.jpg)
![cheese_animation_frame_15](https://user-images.githubusercontent.com/43581768/56182693-8aeaf100-5fd0-11e9-8522-6a753c04ad7e.jpg)
![cheese_animation_frame_20](https://user-images.githubusercontent.com/43581768/56182694-8b838780-5fd0-11e9-8db6-f376a4fba669.jpg)
![0015](https://user-images.githubusercontent.com/43581768/56182717-a8b85600-5fd0-11e9-9600-7c4a48dc7a64.png)
![0020](https://user-images.githubusercontent.com/43581768/56182718-a8b85600-5fd0-11e9-8c87-48821a36f67b.png)
**Steps to reproduce the behavior:**
1. Open a new project.
2. Click the green plus button on the upper left to import files.
3. Navigate to a folder which contains a sequence of PNG image files named 001.png through 020.png.
4. Select 001.png then click the Open button.
5. A dialog pops up asking "Would you like to import 001.png as an image sequence?". Click Yes.
6. Right click on the imported PNG sequence then click on Preview File.
7. Click the green play button on the preview window. Frames 001.png through 010.png will animate perfectly fine, but frames 011.png through 020.png appear to just be copies of 010.png so the animation does not load fully. This same thing happens if you drag the imported sequence to the timeline and play it from there.

**Expected behavior**
The PNG sequence should be fully loaded from frame 001.png to 020.png and the animation should play (either in preview or from the timeline) without duplicated frames near the end.

**System Details**
- OpenShot Version: 2.4.4-dev1
- libopenshot Version:  0.2.3
- Platform: Linux-4.18.0-17-generic-x86_64-with-Ubuntu-18.04-bionic
- Processor: x86_64
- Machine: x86_64
- Python version: 3.4.3
- Qt5 version: 5.2.1
- PyQt5 version: 5.2.1
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: en_US.UTF-8
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.4.4-dev1-1554580857-101f25a7-7001b687-x86_64.AppImage

**Log Files**
- http://logs.openshot.org/abf89mtqhh4ruyca5bepf1z4rb5c234f/openshot-qt.zip
- http://logs.openshot.org/abf89mtqhh4ruyca5bepf1z4rb5c234f/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by SuslikV** [comment]
Probably PNG with alpha channel required here. In _Timeline_ use keyboard arrows (left/right) to playback frame by frame - few frames is missing in my setup (25 fps profile).

Sequence of png images with alpha 000.png to 064.png (total 65) to reproduce the bug (you may remove the 000.png on your wish). Each image is 128x128x32 with number of grey color (~141KB to download, CRC of the zip, MD5:76077193C3DA0FA0B78ED220559C1813):

[000_064_with_alpha.zip](https://github.com/OpenShot/openshot-qt/files/3083809/000_064_with_alpha.zip)

The behavior depends on default profile.
For example,
for `HD 1080p 29.97 fps` the missing frames are: 16, 49, 64;
for `HD 1080p 25 fps` (Europe, PAL etc.) missing are: 5, 11, 17, 23, 29, 35, 41, 47, 53, 59, 64;
for `HD 1080p 30 fps` all is present, nothing is missing.

In the Project Files right-click over the imported sequence click _File Properties -> Output_ section in OpenShot I see:
```
...
    "type": "QtImageReader",
    "vcodec": "",
    "video_bit_rate": 0,
    "video_length": 65,
    "video_stream_index": -1,
    "video_timebase": {
        "den": 30,
        "num": 1
    },
...
```
so, 30 fps is default for image sequence,

while the _File Properties -> Video Details_ section I see:
```
...
Frame Rate    30    1
...
```
This is numerator (frirst) and denominator(second) of imported video **it should be adjusted** according to default profile of OpenShot, save changes and then the video (that is sequence of images) re-add back to the track.

Anyway, there is other bugs with the mentioned build of OpenShot:
- I cant import sequence of images second time until application restarted.
- The last frame (064.png from the test above) is missing in tracks playback.

**Comment by jetpack-toast** [comment]
Thank you for your reply SuslikV! I gave this a shot, but even when I'm using a profile of `HD 1080p 30fps`, the last several frames will be duplicated. For example, I tried out the PNG files you attached and stepped through them on the timeline. Everything counted up correctly until the number 53. The twelve frames following 53 also just showed the frame for 53 rather than 54 and up. Here are the exact steps I performed:

1. I removed OpenShot from my Ubuntu 18.04 system and deleted the ~/.openshot_qt folder.
2. I installed the latest daily build from today, April 16th, 2019.
3. I opened OpenShot, went to `Edit -> Preferences -> Profiles` and changed the default profile to `HD 1080p 30fps`.
4. I closed OpenShot and re-opened it in order to get the default profile change to take effect.
5. I imported the PNG number series you attached to your last post as an image sequence.
6. I right clicked on the PNG sequence and went to `File Properties -> Output`. It showed the following which appeared to be correct according to the profile:
```
    "type": "QtImageReader",
    "vcodec": "",
    "video_bit_rate": 0,
    "video_length": 65,
    "video_stream_index": -1,
    "video_timebase": {
        "den": 30,
        "num": 1
    },
```
7. I then checked the `Video Details` section and the `Frame Rate` was set to `30   1` which also appeared to be correct according to the profile.
8. I dragged the image sequence to `Track 1` in the timeline and stepped through it frame by frame using the right arrow key.
9. The video counted up correctly from 1 to 53. I hit the right arrow key 12 more times after seeing 53 and the timeline and time display advanced appropriately, but those last 12 frames still showed 53.

I also tried changing the profile to 25fps and 60fps while updating the `Frame Rate` on the image sequence to match the fps, but the exact same problem persisted in that the frame showing the number 53 was duplicated across the final 12 frames.

Could you please let me know if I'm doing something wrong in order to work around this issue?

**Comment by SuslikV** [comment]
What latest version of Python and Qt libs available for you?

**Comment by jetpack-toast** [comment]
Yes, I'm running Ubuntu 18.04. I've tried installing OpenShot from the Ubuntu repos which gives me version 2.4.1-2build2 as well as both the stable build from the OpenShot website (AppImage) and the most recent daily build from a couple days ago (also AppImage). I don't currently have the Qt libs installed, but I am running Python 2.7.15rc1 if that helps any. Is it possible this issue is specific to Ubuntu 18.04? I wonder if anybody else is having the same problem. Perhaps I'll try building the application from source on my computer to see if the outcome is any different unless you happen to have any other ideas. Thank you again for following through with me on this!

**Comment by SuslikV** [comment]
Linux native installation is compilation from the source (if someone already did it - you'll find it in repositories, if not - you should do it yourself).

**Comment by ZapUser77** [comment]
Exact same problem.  It simply won't import the last 11 frames.

**Comment by ferdnyc** [comment]
@ZapUser77 Please provide details of your OpenShot installation (see the [bug report template](https://github.com/OpenShot/openshot-qt/issues/new?assignees=&labels=%3Abeetle%3A+bug&template=bug-report.md&title=Give+your+bug+report+a+descriptive+title) for guidance on what info is needed), and also a directory listing of all the files in the image sequence that you want to import.

**Comment by ZapUser77** [comment]
Already deleted it.
I was using the latest version. Had numbered frames produced by blender in a folder by themselves.  It loaded 1-49, and didn't 50-60.  It just used frame 49 12 times.  (The last frame being used 12 times, is the exact number the other person reported.)
That was using the default settings.  I tried several other setting, all had the exact same result.

**Comment by DDHeuts** [comment]
Well I just downloaded and installed OpenShot and i experience the same problem. It is well described in more than one place. So I hope someone solves it. Version2.5.1 libopenshot 0.2.5
