### ISSUE TITLE
openshot::InvalidFile - Project won't load again anymore

### ISSUE THREAD

**Issue by Mcpixel53** [OpenShot/openshot-qt#2743]
**Describe the bug:**
Openshot stopped loading the project I was working on. I probably moved/renamed a couple of files, but after having them back to their original place/name it just crashes while loading the project.
Selecting the new destination of those files won't alter the outcome.

**Steps to reproduce the behavior:**
1. Open Openshot.
2. Load project.
3. Ask for few image paths | Nothing really.
4. Crash with InvalidFile exception. 

**System Details:**
- OpenShot-qt version: 2.4.4
- libopenshot version: 0.2.3
- Linux-4.9.0-8-amd64-x86_64-with-debian-9.8
- python version: 3.4.3
- qt5 version: 5.2.1
- pyqt5 version: 5.2.1

**Exception / Stacktrace:**
`project_data:INFO Setting default profile to HD 720p 30 fps
project_data:INFO Loading project file: /home/mrpotackl66/Proxecto sen título.osp
   json_data:ERROR Error while converting relative paths to absolute paths: Unterminated string starting at: line 1 column 1 (char 0)
project_data:INFO checking project files...
[ALL FILES CHECK]
project_data:INFO 2.4.4
project_data:INFO 0.2.3
terminate called after throwing an instance of 'openshot::InvalidFile'
what():  File could not be opened.

Caught signal 6 (SIGABRT)
---- Unhandled Exception: Stack Trace ----
  /lib/x86_64-linux-gnu/libc.so.6 ( abort                                     + 0x16a )  [0x7f439096c42a]
  /usr/lib/x86_64-linux-gnu/libstdc++.so.6 ( __gnu_cxx::__verbose_terminate_handler()  + 0x15d )  [0x7f438ec9b0ad]
  /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (                                           + 0x8f066)  [0x7f438ec99066]
  /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (                                           + 0x8e089)  [0x7f438ec98089]
  /usr/lib/x86_64-linux-gnu/libstdc++.so.6 ( __gxx_personality_v0                      + 0x2cd )  [0x7f438ec989dd]
  /lib/x86_64-linux-gnu/libgcc_s.so.1 (                                           + 0xff33)  [0x7f438ea02f33]
  /lib/x86_64-linux-gnu/libgcc_s.so.1 ( _Unwind_Resume                            + 0x57  )  [0x7f438ea03437]
  /tmp/.mount_pEYpBc/usr/bin/libopenshot.so.17 ( openshot::QtImageReader::QtImageReader(std::string)  + 0x8b  )  [0x7f4379c9dd8b]
  /tmp/.mount_pEYpBc/usr/bin/libopenshot.so.17 ( openshot::Mask::SetJsonValue(Json::Value)  + 0x373 )  [0x7f4379c54473]
  /tmp/.mount_pEYpBc/usr/bin/libopenshot.so.17 ( openshot::Timeline::SetJsonValue(Json::Value)  + 0x269 )  [0x7f4379cadd69]
  /tmp/.mount_pEYpBc/usr/bin/libopenshot.so.17 ( openshot::Timeline::SetJson(std::string)  + 0x99  )  [0x7f4379c9fa99]
  /tmp/.mount_pEYpBc/usr/bin/_openshot.so (                                           + 0x88cd9)  [0x7f4379f78cd9]
  /tmp/.mount_pEYpBc/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalFrameEx                        + 0x654b)  [0x7f43910fa00b]
  /tmp/.mount_pEYpBc/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalCodeEx                         + 0x886 )  [0x7f43910fd9c6]
  /tmp/.mount_pEYpBc/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalFrameEx                        + 0x6742)  [0x7f43910fa202]
  /tmp/.mount_pEYpBc/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalFrameEx                        + 0x6c5c)  [0x7f43910fa71c]
  /tmp/.mount_pEYpBc/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalFrameEx                        + 0x6c5c)  [0x7f43910fa71c]
  /tmp/.mount_pEYpBc/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalFrameEx                        + 0x6c5c)  [0x7f43910fa71c]
  /tmp/.mount_pEYpBc/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalFrameEx                        + 0x6c5c)  [0x7f43910fa71c]
  /tmp/.mount_pEYpBc/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalCodeEx                         + 0x886 )  [0x7f43910fd9c6]
  /tmp/.mount_pEYpBc/usr/bin/libpython3.4m.so.1.0 (                                           + 0x209ff6)  [0x7f43910fdff6]
  /tmp/.mount_pEYpBc/usr/bin/libpython3.4m.so.1.0 ( PyObject_Call                             + 0x68  )  [0x7f439105f7a8]
  /tmp/.mount_pEYpBc/usr/bin/libpython3.4m.so.1.0 (                                           + 0x1515ed)  [0x7f43910455ed]
  /tmp/.mount_pEYpBc/usr/bin/libpython3.4m.so.1.0 ( PyObject_Call                             + 0x68  )  [0x7f439105f7a8]
  /tmp/.mount_pEYpBc/usr/bin/libpython3.4m.so.1.0 ( PyEval_CallObjectWithKeywords             + 0x47  )  [0x7f43910d5a07]
  /tmp/.mount_pEYpBc/usr/bin/PyQt5.QtCore.so ( PyQtSlot::invoke(_object*, _object*) const  + 0x50  )  [0x7f438f839840]
  /tmp/.mount_pEYpBc/usr/bin/PyQt5.QtCore.so ( PyQtSlot::invoke(void**, _object*, void*) const  + 0xcf  )  [0x7f438f839caf]
  /tmp/.mount_pEYpBc/usr/bin/PyQt5.QtCore.so ( PyQtSlotProxy::unislot(void**)            + 0x62  )  [0x7f438f844762]
  /tmp/.mount_pEYpBc/usr/bin/PyQt5.QtCore.so ( PyQtSlotProxy::qt_metacall(QMetaObject::Call, int, void**)  + 0x57  )  [0x7f438f8450d7]
  /tmp/.mount_pEYpBc/usr/bin/libQt5Core.so.5 ( QMetaObject::activate(QObject*, int, int, void**)  + 0x8ad )  [0x7f438f24236d]
  /tmp/.mount_pEYpBc/usr/bin/PyQt5.QtCore.so (                                           + 0x1ed9c9)  [0x7f438f8469c9]
  /tmp/.mount_pEYpBc/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalFrameEx                        + 0x6d79)  [0x7f43910fa839]
  /tmp/.mount_pEYpBc/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalCodeEx                         + 0x886 )  [0x7f43910fd9c6]
  /tmp/.mount_pEYpBc/usr/bin/libpython3.4m.so.1.0 (                                           + 0x209ff6)  [0x7f43910fdff6]
  /tmp/.mount_pEYpBc/usr/bin/libpython3.4m.so.1.0 ( PyObject_Call                             + 0x68  )  [0x7f439105f7a8]
  /tmp/.mount_pEYpBc/usr/bin/libpython3.4m.so.1.0 (                                           + 0x1515ed)  [0x7f43910455ed]
  /tmp/.mount_pEYpBc/usr/bin/libpython3.4m.so.1.0 ( PyObject_Call                             + 0x68  )  [0x7f439105f7a8]
  /tmp/.mount_pEYpBc/usr/bin/libpython3.4m.so.1.0 (                                           + 0xf9131)  [0x7f4390fed131]
  /tmp/.mount_pEYpBc/usr/bin/libpython3.4m.so.1.0 ( PyObject_Call                             + 0x68  )  [0x7f439105f7a8]
  /tmp/.mount_pEYpBc/usr/bin/libpython3.4m.so.1.0 ( PyEval_CallObjectWithKeywords             + 0x47  )  [0x7f43910d5a07]
  /tmp/.mount_pEYpBc/usr/bin/PyQt5.QtCore.so ( PyQtSlot::invoke(_object*, _object*) const  + 0x50  )  [0x7f438f839840]
  /tmp/.mount_pEYpBc/usr/bin/PyQt5.QtCore.so ( PyQtSlot::invoke(void**, _object*, void*) const  + 0xcf  )  [0x7f438f839caf]
  /tmp/.mount_pEYpBc/usr/bin/PyQt5.QtCore.so ( PyQtSlotProxy::unislot(void**)            + 0x62  )  [0x7f438f844762]
  /tmp/.mount_pEYpBc/usr/bin/PyQt5.QtCore.so ( PyQtSlotProxy::qt_metacall(QMetaObject::Call, int, void**)  + 0x57  )  [0x7f438f8450d7]
  /tmp/.mount_pEYpBc/usr/bin/libQt5Core.so.5 ( QMetaObject::activate(QObject*, int, int, void**)  + 0x8ad )  [0x7f438f24236d]
  /tmp/.mount_pEYpBc/usr/bin/libQt5Widgets.so.5 ( QAction::triggered(bool)                  + 0x32  )  [0x7f438a080a52]
  /tmp/.mount_pEYpBc/usr/bin/libQt5Widgets.so.5 ( QAction::activate(QAction::ActionEvent)   + 0xe8  )  [0x7f438a082f38]
  /tmp/.mount_pEYpBc/usr/bin/libQt5Widgets.so.5 (                                           + 0x2a6a7a)  [0x7f438a1f3a7a]
  /tmp/.mount_pEYpBc/usr/bin/libQt5Widgets.so.5 (                                           + 0x2abb54)  [0x7f438a1f8b54]
  /tmp/.mount_pEYpBc/usr/bin/libQt5Widgets.so.5 ( QMenu::mouseReleaseEvent(QMouseEvent*)    + 0x23a )  [0x7f438a1fceaa]
  /tmp/.mount_pEYpBc/usr/bin/libQt5Widgets.so.5 ( QWidget::event(QEvent*)                   + 0x405 )  [0x7f438a0c2ea5]
  /tmp/.mount_pEYpBc/usr/bin/libQt5Widgets.so.5 ( QMenu::event(QEvent*)                     + 0x11b )  [0x7f438a1fd64b]
  /tmp/.mount_pEYpBc/usr/bin/libQt5Widgets.so.5 ( QApplicationPrivate::notify_helper(QObject*, QEvent*)  + 0x8c  )  [0x7f438a087c8c]
  /tmp/.mount_pEYpBc/usr/bin/libQt5Widgets.so.5 ( QApplication::notify(QObject*, QEvent*)   + 0x10e1)  [0x7f438a08db61]
  /tmp/.mount_pEYpBc/usr/bin/PyQt5.QtWidgets.so ( sipQApplication::notify(QObject*, QEvent*)  + 0x86  )  [0x7f438aa5d426]
  /tmp/.mount_pEYpBc/usr/bin/libQt5Core.so.5 ( QCoreApplication::notifyInternal(QObject*, QEvent*)  + 0x6d  )  [0x7f438f21ac2d]
  /tmp/.mount_pEYpBc/usr/bin/libQt5Widgets.so.5 ( QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool)  + 0x391 )  [0x7f438a08b9e1]
  /tmp/.mount_pEYpBc/usr/bin/libQt5Widgets.so.5 (                                           + 0x19296a)  [0x7f438a0df96a]
  /tmp/.mount_pEYpBc/usr/bin/libQt5Widgets.so.5 (                                           + 0x1949bb)  [0x7f438a0e19bb]
  /tmp/.mount_pEYpBc/usr/bin/libQt5Widgets.so.5 ( QApplicationPrivate::notify_helper(QObject*, QEvent*)  + 0x8c  )  [0x7f438a087c8c]
---- End of Stack Trace ----`

**Comment by Mcpixel53** [comment]
Here is the project file that is giving me troubles.

**Comment by SuslikV** [comment]
The crash probably caused by new mount point of the required transition file:
`/tmp/.mount_yZ0nJG/usr/bin/transitions/common/fade.svg`

to resolve the issue, find in your project file `Proxecto sen título.osp` the mentioned string (see above) and replace all occurrences by actual path to the OpenShot's _fade.svg_ file, save changes (I cannot predict where it mounted now on your PC, so use file find options of your favorite file manager).

Or you may try to open this repaired _.osp_ file of your project, 28KB to download, CRC of the zip archive MD5:DD837055E8A00FBBBC39AF42B88FA203, (all fade transitions were cut off, so you need to re-add it manually):

[Proxecto sen título_repaired02.zip](https://github.com/OpenShot/openshot-qt/files/3095412/Proxecto.sen.titulo_repaired02.zip)

 but I'm not sure will it work for you or not...

----------

Generally, this bug is related to: https://github.com/OpenShot/openshot-qt/issues/2735

**Comment by linuxgaming** [comment]
I had the same error and in my case what helped was replacing all occurrences of `@transitions/` with the full path in the project file.

**Comment by Mcpixel53** [comment]
The repaired file totally worked SuslikV, thanks!

The funny thing is that I haven't used any transition in my project.. I guess that only the automatically created ones, so can't explain myself why this happened.

**Comment by mdreier** [comment]
I experience the same issue, and it is really annoying as I have to update the file manually every time that I restart Openshot. This error is specific to the AppImage, as its mountmoint changes every time the image is started (at least on my system - Ubuntu 18.04.3). It would be nice if the paths to files inside the app image would be saved and loaded relative to the app image root (see e.g. comments on AppImage/AppImageKit#83).
