### ISSUE TITLE
OpenShot appears not to launch on Mac Yosemite.

### ISSUE THREAD

**Issue by anotherHobbyist** [OpenShot/openshot-qt#2745]
I have downloaded and opened dmg and put openShot app icon into Applications folder
on Mac Yosemite system. When I click on the icon in the Applications dir, it appears to 
launch then I wait and wait and nothing has happened to tell me it is running or why
it isn't. Is there anyone who can advise me about this issue.

Could it be that iMove and iPhoto are being given exclusive priority by the system?

I have come here  via support -> "ask a question" link in OpenShot download web page.

Thank you  for attention

**Comment by ThomasBerends** [comment]
Could you open the terminal and start OpenShot from there?

You can find the terminal in Applications -> Utilities -> Terminal.

If you type one of these two (I'm not at a Mac at this moment so I can't test which one works), it should show you what's going wrong. If you then copy/paste that to us, we can try to find the problem and fix it.

`open -a "OpenShot"`
or
`open -a "OpenShot Video Editor"`

**Comment by anotherHobbyist** [comment]
These are the terminal app commands I used:

jekillenMBPII:~ Jeff$ open "OpenShot"
The file /Users/Jeff/OpenShot does not exist.
jekillenMBPII:~ Jeff$ open "OpenShot"
The file /Users/Jeff/OpenShot does not exist.
jekillenMBPII:~ Jeff$ open "OpenShot Video Editor"
The file /Users/Jeff/OpenShot Video Editor does not exist.
jekillenMBPII:~ Jeff$ 

It is looking for OpenShot in my user account, not in /Applications apparently.

I am logged in as user with admin status.

Thank you for attention
Jeff K

**Comment by ThomasBerends** [comment]
Please use the -a flag I've added in the example. This should try to open it in the application folder. Within the " ", you should type the name as OpenShot appears in your application folder.

**Comment by anotherHobbyist** [comment]
Sorry, I did neglect the -a option


Last login: Sun Apr 21 11:03:12 on ttys000
jekillenMBPII:~ Jeff$ open -a "OpenShot video Editor"
LSOpenURLsWithRole() failed for the application /Applications/OpenShot Video Editor.app with error -10810.
jekillenMBPII:~ Jeff$
