### ISSUE TITLE
How to export only a part of a project?

### ISSUE THREAD

**Issue by geaplanet** [OpenShot/openshot-qt#2746]
**Question:**
I want to export to video only 10 minutes of a 40 minutes project. How to do that? 
I know in advanced export there is first frame and last frame, but how to know the exact frame? I only could find minutes and seconds information, not frames.

**System Details:**
- OpenShot Version 2.4.4
- Operating System / Distro: Kde Neon

**Comment by N3WWN** [comment]
You could take your project frame rate and multiply it by the number of seconds for the start and stop and use those numbers in the first and last frames fields that you found in the advanced export settings.  This is what I've done when I only wanted a portion of the project exported.

For example, if you wanted to export from 19m27s to 29m27s of your 40 min project, and I'll assume your project is 24 FPS, the start frame would be:
`(19*60+27)*24 = 28008`
and the end frame is:
`(29*60+27)*24 = 42408`

**Comment by geaplanet** [comment]
Thanks @N3WWN
