### ISSUE TITLE
Image sequence imported with glitches

### ISSUE THREAD

**Issue by GabiAPF** [OpenShot/openshot-qt#2747]
I am trying to import a sequence of 30 PNG images into a project. Each image is 1280×720, and the project is set at that same resolution and 30 FPS. 

The names of the images are P04b-01.png to P04b-30.png, and I have checked that none of them is missing.

I can open each image individually on any image editor and they all open without a problem. However, when I import the sequence into OpenShot, the images appear greyish, deformed and heavily interleaved, as seen on the screenshot. 

I have imported other sequences without a problem. I do not understand what the problem may be.

**Steps to reproduce the behavior:**
1. Start new project
2. Click on + to import a file
3. Select P04b-01.png (you can find the sequence attached to this post)
4. Click on Yes to import it as a sequence

**Expected behavior:**
The sequence should be imported normally.

**System Details:**
- OpenShot Version: 2.4.4
- Operating System / Distro: Debian Jessie

![Broken](https://user-images.githubusercontent.com/49786665/56425762-0c21dc80-628c-11e9-9a56-71560469e5b2.png)
[sequence.zip](https://github.com/OpenShot/openshot-qt/files/3098232/sequence.zip)

**Comment by GabiAPF** [comment]
I have edited my post because I originally thought the sequence was being shortened to a small fraction of a second when I restarted OpenShot, but that's an entirely different bug: the time scale is off when I open a project I've already been working on. However, that is a minor bug, as it fixes itself when I change the time scale. So please focus on the main issue for now.

I have managed to export the sequence to AVI using GIMP and then import it into OpenShot, but that is a convoluted and time-consuming workaround and I would rather not have to do it again if another sequence ends up having this same problem.

**Comment by SuslikV** [comment]
Your first file (P04b-01.png) has different color depth (no alpha channel). So it can't be the part of the sequence. Either remove it or add alpha to it, same as all other images has. Then try to import it into OpenShot again.

**Comment by GabiAPF** [comment]
Oh, thank you! Deleting the first image and recreating it from the next one solved the problem. I can't imagine how that happened, nor how you figured it out, but I'll make sure to check the color depth if it ever happens again.
