### ISSUE TITLE
Shudder sound and jpg-qualities?

### ISSUE THREAD

**Issue by magielsr** [OpenShot/openshot-qt#2749]
Reading that many experienced shudder sound with Openshot, I did the following: downloaded and installed the latest daily build. Found that with some jpg-files it worked then flawless and with other jpg's I found no improvement.
Are there any meta-dates of the jpg involved or any other jpg-qualities could play a role in this?

**Comment by SuslikV** [comment]
You mean Preview issues? Usually, big files is harder to playback (requires a lot of internal bandwidth of the PC).

**Comment by DylanC** [comment]
Answered.
