### ISSUE TITLE
Hangs when opening video

### ISSUE THREAD

**Issue by garilla22** [OpenShot/openshot-qt#275]
I had the unpleasant situation. When I click to import the files and import the video or what, everything hangs in the console displays a message here:
`[swscaler @ 0x28dcbe0] No accelerated colorspace conversion found from yuv422p to rgba.
project_data:INFO _set key: ['files'] values: {'audio_bit_rate': 352800, 'video_bit_rate': 3159808, 'display_ratio': {'den': 3, 'num': 4}, 'has_video': True, 'has_audio': True, 'audio_stream_index': 1, 'duration': 6.866598129272461, 'acodec': 'pcm_s16le', 'interlaced_frame': False, 'video_stream_index': 0, 'fps': {'den': 1, 'num': 30}, 'pixel_ratio': {'den': 1, 'num': 1}, 'channels': 1, 'type': 'FFmpegReader', 'audio_timebase': {'den': 22050, 'num': 1}, 'channel_layout': 4, 'top_field_first': True, 'video_length': '206', 'video_timebase': {'den': 1000000, 'num': 33333}, 'has_single_image': False, 'path': '/home/admin/VIDEO/DSCN1553.AVI', 'sample_rate': 22050, 'media_type': 'video', 'file_size': '2712142', 'vcodec': 'mjpeg', 'width': 320, 'pixel_format': 13, 'height': 240, 'id': 'LTJ2HK4P3F'} add: True partial: False remove: False
 files_model:INFO updating files model.
[swscaler @ 0x28dcbe0] No accelerated colorspace conversion found from yuv422p to rgba.
[swscaler @ 0x28dcbe0] No accelerated colorspace conversion found from yuv422p to rgba.`
![2016-08-27 00 48 53](https://cloud.githubusercontent.com/assets/19745988/18022054/6ada8542-6bf4-11e6-85f4-edee421a0240.png)
What should I do?Loading only the second attempt via the kill -9 command!
My system Linux linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux

**Comment by johnLIC** [comment]
I am having similar issues.  Any solution?

**Comment by johnLIC** [comment]
...sorry, here are some more details...
Centos 7
uname -r:  3.10.0-327.36.1.el7.x86_64
graphics card = gtx 970 with nvidia driver 367.44
openShot version = OpenShot-v2.1.0.AppImage

**Comment by jonoomph** [comment]
Have you tried using our latest daily build **AppImage**? Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily **AppImage** of OpenShot. Mark it as executable, and launch it (no installation needed).

If that doesn't solve the issue, please attach the smallest video file (which actually reproduces the crash/freeze), and I'll take a look... that is... if you don't mind sharing it publicly here. Thanks!

**Comment by johnLIC** [comment]
Hi,


I tried this build:


OpenShot-v2.1.0-29-gc0c2180-49-587-x86_64.bin


but it is too unstable.  Here's the most recent crash, below.


2, 'memo': '', 'value': 0.0, 'readonly': False, 'max': 5184000.0, 'keyframe': True, 'name': 'Time', 'choices': [], 'points': 1}), ('layer', {'min': 0.0, 'closest_point_x': -1, 'type': 'int', 'interpolation': 2, 'memo': '', 'value': 0.0, 'readonly': False, 'max': 20.0, 'keyframe': False, 'name': 'Track', 'choices': [], 'points': 0}), ('volume', {'min': 0.0, 'closest_point_x': 1, 'type': 'float', 'interpolation': 2, 'memo': '', 'value': 1.0, 'readonly': False, 'max': 1.0, 'keyframe': True, 'name': 'Volume', 'choices': [], 'points': 1}), ('wave_color', {'type': 'color', 'min': 0.0, 'green': {'min': 0.0, 'closest_point_x': 1, 'type': 'float', 'interpolation': 0, 'memo': '', 'value': 123.0, 'readonly': False, 'max': 255.0, 'keyframe': True, 'name': 'Green', 'choices': [], 'points': 1}, 'closest_point_x': 1, 'interpolation': 0, 'red': {'min': 0.0, 'closest_point_x': 1, 'type': 'float', 'interpolation': 0, 'memo': '', 'value': 0.0, 'readonly': False, 'max': 255.0, 'keyframe': True, 'name': 'Red', 'choices': [], 'points': 1}, 'memo': '', 'value': 0.0, 'readonly': False, 'max': 255.0, 'keyframe': True, 'blue': {'min': 0.0, 'closest_point_x': 1, 'type': 'float', 'interpolation': 0, 'memo': '', 'value': 255.0, 'readonly': False, 'max': 255.0, 'keyframe': True, 'name': 'Blue', 'choices': [], 'points': 1}, 'name': 'Wave Color', 'choices': [], 'points': 1}), ('waveform', {'min': 0.0, 'closest_point_x': -1, 'type': 'int', 'interpolation': 2, 'memo': '', 'value': 0.0, 'readonly': False, 'max': 1.0, 'keyframe': False, 'name': 'Waveform', 'choices': [{'value': 1, 'name': 'Yes', 'selected': False}, {'value': 0, 'name': 'No', 'selected': True}], 'points': 0})])
timeline_webview:INFO $scope.ShowClipMenu
timeline_webview:INFO ShowClipMenu: 7N4FCK0PX0
 main_window:INFO actionRemoveClip_trigger
project_data:INFO _set key: ['clips', {'id': '7N4FCK0PX0'}] values: None add: False partial: False remove: True
timeline_webview:INFO SortItems
timeline_webview:INFO UpdateLayerIndex
 main_window:INFO updateStatusChanged
properties_model:INFO Update item:
properties_model:INFO updating clip properties model.
Segmentation fault (core dumped)


________________________________

**Comment by jreynojustin** [comment]
OpenShot is now in Version 2.2 if you are still noticing issues in the latest version please re-open this issue letting us know.
