### ISSUE TITLE
Closes on export

### ISSUE THREAD

**Issue by PatrickEllington** [OpenShot/openshot-qt#2750]
My video compilation causes the program to close at 64% completion. What do i do to fix this.
thanks

**Comment by ThomasBerends** [comment]
Without knowing anything about the project, your system or anything else, we cannot answer your question.

One thing you could do is check how long your project is, and check what happens at 64% in your project. Is there a certain file there that's different than the rest?

**Comment by DylanC** [comment]
> What do i do to fix this.

@PatrickEllington - Provide more details.

**Comment by ferdnyc** [comment]
I'm going to close this, since there's still no response. If you're still having difficulties @PatrickEllington , feel free to open a [new issue](https://github.com/OpenShot/openshot-qt/issues/new/choose) using the Bug Report template, and fill in as much detail as possible using the form provided.
