### ISSUE TITLE
OpenShot crashes when exporting to flv on windows 10

### ISSUE THREAD

**Issue by kmpm** [OpenShot/openshot-qt#2751]
**Describe the bug**
OpenShot crashes when exporting to flv on windows 10

This happens after about 0.3% complete.
The project contains a 2 sec simple title and a flv source video that is about 4 minutes long.
The source is according to VLC, H264 - MPEG-4 AVC in 1280x1024 at 60fps with audio in MPEG AAC - Stereo 44kHz.
Export to mp4 works but not flv. It will just create an empty 0 byte flv file.

**Steps to reproduce the behavior:**
1. Go to 'File -> Export Video'
2. Select profile 'All Formats'
3. Change target to 'FLV (h.264)
4. Video Profile and Quality is set to HD 720p 30 fps, High quality
5. Click 'Export Video'

**Expected behavior**
I would expect the export process to start and generate my desired output.

**System Details**
- OpenShot Version: 2.4.4-dev1
- libopenshot Version:  0.2.3
- Platform: Windows-10-10.0.17763
- Processor: Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
- Machine: AMD64
- Python version: 3.6.4
- Qt5 version: 5.9.1
- PyQt5 version: 5.9
- Qt Detected Languages: ['sv-SE', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.4.4-dev1-1555530828-aa85c1bb-9a1a6093-x86_64.exe

**Log Files**
- http://logs.openshot.org/7auslkh9swb6er5g5teldq0k1hiytj7h/openshot-qt.zip
- http://logs.openshot.org/7auslkh9swb6er5g5teldq0k1hiytj7h/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Comment by SuslikV** [comment]
I can confirm this bug, you even don't need to add any files to the project. It is bug with audio of FLV format in OpenShot.
