### ISSUE TITLE
Make log less verbose

### ISSUE THREAD

**Issue by SuslikV** [OpenShot/openshot-qt#2752]
**New feature:**
I want to see new feature as commandline key or option in settings to allow user to log only critical errors not INFO level. Really, about 25MB logs... For what purpose this? Just to catch the application's bugs? It is not the way how application should work. Also, the log is on the SSD drive, which lifetime is short, and application just writes a lot of unneeded info to this log.

**The solution I'd like to see:**
Add either new commandline key "verbose_level=0..3" or add similar option in the settings of the application.

**Alternatives:**
Log only ERRORS by default, and add special option to enable logging of INFO, DEBUG etc. level of the application messages, but only if asked for.
OR
Allow, to fail silently on write to log operations, thus I can restrict access of the application to the log file and it isn't harm anything for me.

**Comment by FinixFighter** [comment]
I agree with you!
