### ISSUE TITLE
Really Very slow and its terminates automatically

### ISSUE THREAD

**Issue by valasudurai** [OpenShot/openshot-qt#2753]
The program not good as mentioned in the website
It was really slow and its terminates automatically and saying the app request to terminate in unusual way
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/3123630/openshot-qt.log)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/3123631/libopenshot.log)

**Comment by SuslikV** [comment]
Similar to https://github.com/OpenShot/openshot-qt/issues/2751
Just choose another output format (MP4 should work well)
