### ISSUE TITLE
Cannot preview audio when I have an image on the other track

### ISSUE THREAD

**Issue by Randall-Coding** [OpenShot/openshot-qt#2761]
**Describe the bug:**
If I just have audio I can preview the clip.  Or even a video clip with audio.  But if I put an image on one track and audio on another track I cannot play it in preview mode. 

This means if I want to edit my audio, I have to remove the image, edit the audio, then add it back in before exporting.  

**Steps to reproduce the behavior:**
1) Add an audio track to track 2.  In my case I am using a ogg vorbis audio file
2) Add an image to track 1 to display while the audio is playing.  Tried with png and jpeg
3) Try to preview the entire movie.  It won't play the audio back correctly (possibly a few second slices of audio in and out but that is it).

**Expected behavior:**
Being able to preview both audio and video at the same time

**System Details:**
- OpenShot Version [2.4.4]: 
- Operating System  Linux/Ubuntu 18.04

**Comment by SuslikV** [comment]
If you export the video and playback it, is all OK? Please, attach your `openshot-qt.log` file.

**Comment by Randall-Coding** [comment]
Export still works normally.  Just the preview playback for editing.

When playing in preview mode the log doesn't output any errors.  
`properties_model:INFO Update item: 
properties_model:INFO updating clip properties model.
timeline_webview:INFO redraw_audio_onTimeout
    timeline:INFO Adjusting max size of preview image: PyQt5.QtCore.QRect(228, 0, 188, 106)
preview_thread:INFO refreshFrame
preview_thread:INFO self.player.Position(): 1
preview_thread:INFO onModeChanged
preview_thread:INFO onModeChanged
`

But there is an error on loading up the software 
`timeline_webview:ERROR TimelineWebView::eval_js() called before document ready event. Script queued: $('body').scope().SetTrackLabel('Track %s');
timeline_webview:ERROR TimelineWebView::eval_js() called before document ready event. Script queued: $('body').scope().LoadJson({"key": "", "old_values": {}, "value": {"id": "T0", "export_path": "", "effects": [], "import_path": "", "sample_rate": 44100, "channels": 2, "width": 1280, "layers": [{"y": 0, "id": "L1", "number": 1000000, "lock": false, "label": ""}, {"y": 0, "id": "L2", "number": 2000000, "lock": false, "label": ""}, {"y": 0, "id": "L3", "number": 3000000, "lock": false, "label": ""}, {"y": 0, "id": "L4", "number": 4000000, "lock": false, "label": ""}, {"y": 0, "id": "L5", "number": 5000000, "lock": false, "label": ""}], "clips": [], "fps": {"num": 24, "den": 1}, "progress": [], "duration": 300, "files": [], "markers": [], "scale": 15, "settings": {}, "playhead_position": 0, "tick_pixels": 100, "profile": "HDV 720 24p", "channel_layout": 3, "version": {"openshot-qt": "0.0.0", "libopenshot": "0.0.0"}, "height": 720}, "partial": false, "type": "load"});
preview_thread:INFO refreshFrame
preview_thread:INFO self.player.Position(): 1
timeline_webview:ERROR TimelineWebView::eval_js() called before document ready event. Script queued: $('body').scope().SetSnappingMode(1);
    timeline:INFO Adjusting max size of preview image: PyQt5.QtCore.QRect(266, 0, 334, 188)
preview_thread:INFO refreshFrame
preview_thread:INFO self.player.Position(): 1
`

**Comment by SuslikV** [comment]
This info is useless for troubleshooting.
Weak PC maybe? If you using AppImage version, try to make and install your own native linux install of the OpenShot.

**Comment by Randall-Coding** [comment]
Weak PC?  Yeah I'll make sure to have my PC start lifting some weights.  Thanks for the useless troubleshooting

**Comment by SuslikV** [comment]
Not at all.
