### ISSUE TITLE
Windows EXE doesn't include any metadata

### ISSUE THREAD

**Issue by ferdnyc** [OpenShot/openshot-qt#2762]
The `launch.exe` file that represents "the OpenShot application" on Windows doesn't include any identifying metadata:

![image](https://user-images.githubusercontent.com/538020/57039233-1ba90a00-6c2a-11e9-995a-fcc108df0588.png)

There's probably some way to change that, and it would probably be a good idea to do so. At least the "Product name" and "Product version" fields would be nice to have set, since "launch.exe" isn't a very descriptive filename all by itself. (I'm sure @jonoomph wouldn't mind having his copyright info in there, either.)

**Comment by SuslikV** [comment]
GPL is bit different of _copyright_ but, for example, the Inkscape filled it with the organization's name.

**Comment by ferdnyc** [comment]
@SuslikV 

You're right that it's different, even a GPL'd application has a copyright holder. In fact, [the GPL](https://www.gnu.org/licenses/gpl-3.0.en.html) even states that an assertion of copyright is one of its features/aspects, in the Preamble:

> Developers that use the GNU GPL protect your rights with two steps: (1) assert copyright on the software, and (2) offer you this License giving you legal permission to copy, distribute and/or modify it.

OpenShot's copyright assertion is made in its About dialog:

![image](https://user-images.githubusercontent.com/538020/57049539-74869b80-6c46-11e9-9d0a-fcc6fdbe267a.png)

That same statement just needs to get embedded into the Launch exe, along with other relevant metadata. Which it looks like the Windows version of cx_Freeze would be "in charge" of handling. I'm just not yet 100% clear on how, exactly, that's done.

**Comment by SuslikV** [comment]
Developer**S** (sic!)
