### ISSUE TITLE
Video preview is blank (Give your bug report a descriptive title)

### ISSUE THREAD

**Issue by AnonymCodeGit15** [OpenShot/openshot-qt#2765]
**Describe the bug**
Video preview is blank
Whenever i click + to add a video the video preview is blank

**Expected behavior**
The video does not appear in the video preview tab

**System Details**
- OpenShot Version: 2.4.4
- libopenshot Version:  0.2.3
- Platform: Windows-7-6.1.7600-SP0
- Processor: x86 Family 6 Model 42 Stepping 7, GenuineIntel
- Machine: x86
- Python version: 3.6.4
- Qt5 version: 5.9.1
- PyQt5 version: 5.9
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.4.4-dev1-1556833544-8fb72aae-9a1a6093-x86.exe

**Log Files**
- http://logs.openshot.org/etabw0yidvb9kl1hftpvcwcj8e79kgjm/openshot-qt.zip
- http://logs.openshot.org/etabw0yidvb9kl1hftpvcwcj8e79kgjm/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.
Screen shot
 https://imgur.com/HujznWn

**Comment by N3WWN** [comment]
You don't appear to have added a clip to the timeline.  The preview window only shows what is rendered from the timeline.

If you're new to OpenShot, this [tutorial](https://cdn.openshot.org/static/files/user-guide/quick_tutorial.html) may help.
