### ISSUE TITLE
Allow selecting one or two out of a bunch of multiple audio tracks

### ISSUE THREAD

**Issue by udippel** [OpenShot/openshot-qt#2768]
This is the type of input tracks I use to get here:

  Stream #0:1[0x22a](deu): Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, s16p, 256 kb/s
    Stream #0:2[0x22b](mis): Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, s16p, 192 kb/s
    Stream #0:3[0x22c](deu): Audio: ac3 ([6][0][0][0] / 0x0006), 48000 Hz, stereo, fltp, 448 kb/s
    Stream #0:4[0x22d](mul): Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, s16p, 192 kb/s
    Stream #0:5[0x22e](deu): Subtitle: dvb_teletext ([6][0][0][0] / 0x0006)
    Stream #0:6[0x655]: Unknown: none ([5][0][0][0] / 0x0005)
    Stream #0:7[0x669](deu): Subtitle: dvb_subtitle ([6][0][0][0] / 0x0006) (hearing impaired)

So far - I did ask - it seems Openshot cannot handle these properly. Importing gets me some left and right (I guess), and I also guess from stream #0:1.

So my request for enhancement is two-fold: 

1.a. Selecting the audio tracks that I want to use at import (respectively in the Tracks area.

1.b. Able to select the track(s) for Preview whose audio I want to preview

2. Re-assemble  selected tracks at export. VLC (e.g.) allows to select a specific audio track.

**Comment by ctsdownloads** [comment]
Is this still an issue in the current version of OpenShot?
