### ISSUE TITLE
Openshot Export Video Issues

### ISSUE THREAD

**Issue by Addictedd** [OpenShot/openshot-qt#277]
For some reason whenever I try exporting my edited video, it freezes at 1% and I can't do anything about it. Any suggestions?

**Comment by PanderMusubi** [comment]
I had the similar problems on a machine with 4 GB RAM and 4 GB swap. Switched to a machine with 12 GB RAM and 12 GB swap and was no longer a problem. Does that help you too?

**Comment by apraetor** [comment]
Mine crashes at any random % during the encode (16 GB RAM, 64 GB swap on SSD) if I switch between OpenShot and other apps too much. If I leave the computer entirely alone during the encode it seems to succeed every time.. but for multi-hour encodes this is a bit silly.

**Comment by meoso** [comment]
Tried countless time to export 1080p and 720p video of approx 8 minutes.
repeatedly get the crash error on commandline: 
```
*** Error in `/tmp/.mount_smG5oI/usr/bin/launch': malloc(): smallbin double linked list corrupted: 0x00007f9ae3abd260 ***
Aborted
```

```
 $ uname -a
Linux skynet 4.6.0-0.bpo.1-amd64 #1 SMP Debian 4.6.4-1~bpo8+1 (2016-08-11) x86_64 GNU/Linux
```

Tried last 5 to 7 AppImage versions, currently : `./OpenShot-v2.1.0-22-g42e4f3a-49-587-x86_64.AppImage`

**Comment by luukp** [comment]
This is very similar behaviour to what I am seeing.  While rendering openshot gradually consumes more and more memory until there is none left, and at that point it crashes (16GB RAM), inconveniently about 94% through the video we are trying to render.

**Comment by DylanC** [comment]
@Addictedd - Referenced issues here have already been closed. If the issue still exists log a new ticket with the issue verified on OpenShot version 2.3.4. Thanks.

**Comment by apraetor** [comment]
@DylanC I reopened this as issue #849, as it does still exist on Windows 10 under OpenShot 2.3.4

**Comment by DylanC** [comment]
@apraetor - No problem. Thanks.

**Comment by umonkey** [comment]
Ubuntu 16.10, export does not work.  UI freezes, console reads this:

    terminate called after throwing an instance of 'std::bad_alloc'
      what():  std::bad_alloc
    Caught signal 6 (SIGABRT)
    ---- Unhandled Exception: Stack Trace ----
      /lib/i386-linux-gnu/libc.so.6  ( gsignal                                   + 0xb0  )  [0xb7525050]
      /lib/i386-linux-gnu/libc.so.6  ( abort                                     + 0x157 )  [0xb7526577]
      /usr/lib/i386-linux-gnu/libstdc++.so.6 ( __gnu_cxx::__verbose_terminate_handler()  + 0x17f )  [0xb52c674f]
      /usr/lib/i386-linux-gnu/libstdc++.so.6 (                                           + 0x720d4)  [0xb52c40d4]
      /usr/lib/i386-linux-gnu/libstdc++.so.6 (                                           + 0x70e09)  [0xb52c2e09]
      /usr/lib/i386-linux-gnu/libstdc++.so.6 ( __gxx_personality_v0                      + 0xe1  )  [0xb52c3661]
      /lib/i386-linux-gnu/libgcc_s.so.1 (                                           + 0x153ff)  [0xb4f743ff]
      /lib/i386-linux-gnu/libgcc_s.so.1 ( _Unwind_Resume                            + 0x57  )  [0xb4f74877]
      /usr/lib/i386-linux-gnu/libopenshot.so.12 ( openshot::Frame::AddImage(int, int, int, QImage::Format, unsigned char const*)  + 0x30e )  [0xad6ab5fe]
      /usr/lib/i386-linux-gnu/libopenshot.so.12 (                                           + 0x79204)  [0xad68f204]
      /usr/lib/i386-linux-gnu/libgomp.so.1 (                                           + 0x10f00)  [0xad45bf00]
      /usr/lib/i386-linux-gnu/libgomp.so.1 (                                           + 0x1a03c)  [0xad46503c]
      /usr/lib/i386-linux-gnu/libgomp.so.1 (                                           + 0x1a112)  [0xad465112]
      /usr/lib/i386-linux-gnu/libgomp.so.1 ( GOMP_barrier                              + 0x26  )  [0xad453696]
      /usr/lib/i386-linux-gnu/libopenshot.so.12 (                                           + 0x7ea65)  [0xad694a65]
      /usr/lib/i386-linux-gnu/libgomp.so.1 (                                           + 0x17173)  [0xad462173]
      /lib/i386-linux-gnu/libpthread.so.0 (                                           + 0x62d5)  [0xb76b92d5]
      /lib/i386-linux-gnu/libc.so.6  ( clone                                     + 0x6e  )  [0xb75e264e]
    ---- End of Stack Trace ----

Lots of wasted time making up the project, have to revert to 1.4.3 and redo.  Project file format changed, which also sucks.
