### ISSUE TITLE
Extracting the audio after you split it from the video.

### ISSUE THREAD

**Issue by GrandpaBill3006** [OpenShot/openshot-qt#2770]
After I split the audio from the video, I want to extract it so I can do some custom editing in Audacity, BUT I tried copying and that doesn't work.
So, Whats the trick to extracting the sound track to a folder on my computer/desktop/anywhere?

**Comment by SuslikV** [comment]
Use FFmpeg with proper commands (example https://obsproject.com/mantis/view.php?id=1115#c3768) to demulltiplex some streams or use some other tools.

In OpenShot, right now, you can only export audio. In other words re-encode it to lossless _flac_ format (resampled to the projects audio sample frequency) by next steps:

1. in _Export Video_ dialog the profile is set to _Profile: All Formats_
2. select _Target: OGG (theora/flac)_ in the export dialog's _Simple_ tab
3. at _Advanced_ tab you need to specify _Export To: Audio Only_
4. Click _Export Video_ (sic!) button

and when task complete - you may drag-n-drop final .ogg file into Audacity. Edit, save as WAV and drop new audio file back to OpenShot, don't forget to check if _Enable Audio_ property of the video clip is already set to 0 from start to the end.

**Comment by GrandpaBill3006** [comment]
Thanks, I'll give it a try.

**Comment by DylanC** [comment]
Answered.
