### ISSUE TITLE
After the crush the video runs very slowly. I've updated the program but it crushes again when I start the clip.

### ISSUE THREAD

**Issue by MacciL** [OpenShot/openshot-qt#2771]
When I've put the audio in the video, the program began to have problems: the audio was glitchy and then the program arrested and crashed. I've opened it again and each clip runs very slowly and it's not better even if I relish speed with the options of the program. I've also updated the program with the newest version, following the instructions. At the moment, with the start of the clip, the program closes.

**System Details**
- OpenShot Version: 2.4.4-dev1
- Platform:  Windows 10 home
- Processor: Intel Core i5 2.20Gh, 4GB RAM
- Machine: Acer 
The log file: 
https://drive.google.com/open?id=1imfxk23zfx5VqVryhZMBzi38FWQwnRh7
https://drive.google.com/open?id=17Gsl53pl39xLWxMnxFRlO8NjP_3_E1Y5

**Comment by SuslikV** [comment]
Please, provide your OpenShot log-files right after the issue occurs.

**Comment by MacciL** [comment]
I followed the procedure on the site, I already attached the log there and I mistakenly thought it was enough. I added a link to the log, sorry If I did something wrong, I'm not really good with this stuff!
Thanx for helping!

**Comment by SuslikV** [comment]
Try to make new project. If it fails in the new project too (add 1 video file), then your installation is just broken. Reinstall is needed.
