### ISSUE TITLE
Win10: Hangs while editing large files (>400 MB)

### ISSUE THREAD

**Issue by sandeepshampur** [OpenShot/openshot-qt#2773]
Using on Windows 10 1803 build 17134.706. I installed the editor to merge two video files. One was 289 MB and the other 224 MB. Importing the files took a long time and during this time the system froze. Added the two file to time line and the system froze again. After a while, the software exited without any message. I notice that log file is about 15 MB after two attempts in editing the video files. I tried to upload them but nothing happened after choosing the two log files. There was no message that it was being uploaded. Hence I am logging the issue here. Not sure how to upload the log files.

**Comment by SuslikV** [comment]
zip logs first and use sharing services (Google Drive etc.)

Editor able to process even bigger files. Size not the case. Can you provide MediaInfo in .txt format of both files?

**Comment by sandeepshampur** [comment]
I used VideoPad to merge them and it worked like a charm. I no longer have these split files. My question is why is it freezing the system? I noticed that it was using 100% CPU and 100% disk usage during this time. Even the task manager took a long time to come up. Unfortunately when I wanted to try on a different video file, the software said that it had recovered my earlier work I was doing and froze my system again. I had to kill it from task manager as I had enough. I uninstalled it promptly and cleaned up the logs files. What surprises me is that I use a good system and I was surprised it froze my system (i5-4440 4 core 3.1 GHz, 8GB 1600 MHz, 500 GB HDD). Just before the application quit without any information, I happened to notice in task manager that its memory usage had gone up to 3GB.

**Comment by SuslikV** [comment]
Can be closed. High memory consumption was already reported. Without log's details and reproduction of the bug in the test environment - it is hard to say why you have had such issue. I have much weaker PC and used bigger files and it works.

**Comment by sandeepshampur** [comment]
Closing this as I do not intend to install it again.
