### ISSUE TITLE
Audio stutter when overlaping in timelime

### ISSUE THREAD

**Issue by 09williamsad** [OpenShot/openshot-qt#2776]
Description
Audio stutters when its end overlaps with an image or video clip.

**Steps to reproduce the behavior:**
1. Position an audio clip and a video clip or image so that the audio clip ends during the video/image, see below image
![image](https://user-images.githubusercontent.com/23011550/57466661-fe52ec00-7278-11e9-8a61-b9053adcb5fc.png)
2. Play in the timeline or export to video and play, the audio clip should end with a stutter.

**Expected behavior:**
An audio clip should end without any stutter as it plays normally when its end does not overlap.

**System 1 Details:**
- OpenShot Version 2.4.4
- Windows 7 Home Premium 64 bit 

**System 2 Details:**
- OpenShot Version 2.4.3
- OpenShot Version 2.4.0
- Windows 10 Home 64 bit 

**Troubleshooting tried:**
reinstalling openshot
restarting computer
creating new project
windows 7 and 10 computers
changing the audio file type from avi to mp3

**Comment by ctsdownloads** [comment]
Is this still an issue in the current version of OpenShot?
