### ISSUE TITLE
not opening OSP files via file manager

### ISSUE THREAD

**Issue by pleabargain** [OpenShot/openshot-qt#2777]
**Describe the bug**
not opening OSP files

**Steps to reproduce the behavior:**
1. Go to osp file
2. Click on osp
nothing happens/ OSP does NOT start
**Expected behavior**
I expect OSP to open the osp file

**System Details**
- OpenShot Version: 2.4.4-dev1
- libopenshot Version:  0.2.3
- Platform: Linux-5.0.0-13-generic-x86_64-with-Ubuntu-19.04-disco
- Processor: x86_64
- Machine: x86_64
- Python version: 3.4.3
- Qt5 version: 5.2.1
- PyQt5 version: 5.2.1
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: en_US.UTF-8
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.4.4-dev1-1557343973-17a22589-9a1a6093-x86_64.AppImage

**Log Files**
- http://logs.openshot.org/h2ujy8jpq72m0fhaerl78pq0sbcror9f/openshot-qt.zip
- http://logs.openshot.org/h2ujy8jpq72m0fhaerl78pq0sbcror9f/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

video of .osp file NOT opening
https://youtu.be/VTVhUqfotFY

**Comment by ferdnyc** [comment]
PR #2872 adds a Task to the Windows installer which will create file associations for .OSP files on install (unless the user unchecks that option).
