### ISSUE TITLE
Blender Path

### ISSUE THREAD

**Issue by newwdruid** [OpenShot/openshot-qt#278]
I am new to OpenShot, And I want to edit a title but a box comes up for the path to blender. I have a Macbook Pro and am still figuring this Mac out. How do I get the path information for the open shot preferences?

**Comment by FrankSanabria** [comment]
You need install blender

**Comment by DylanC** [comment]
@newwdruid - Install blender and point the path in OpenShot to:
/Applications/blender.app/Contents/MacOS/blender

**Comment by DylanC** [comment]
@newwdruid This question has been answered. I will be closing this issue for now. Thanks.
