### ISSUE TITLE
Tab key order on advanced export options is quirky

### ISSUE THREAD

**Issue by jpnance** [OpenShot/openshot-qt#2780]
**Describe the bug:**
When I'm picking particular frames to export in the advanced export options, I want to be able to press tab to advance from "Start Frame" to "End Frame" but it goes in the reverse order that I would expect.

**Steps to reproduce the behavior:**
1. Go to File > Export Video > Advanced
2. Click on the "Start Frame" field, where it says 1
3. Press the tab key

**Expected behavior:**
I would have expected the "End Frame" field to now be selected but, instead, input field focus has gone away altogether. Pressing shift+tab instead for Step 3 takes the focus to the correct place.

**System Details:**
- OpenShot Version: 2.4.4
- Operating System: Windows 10

Maybe this should be rolled in with https://github.com/OpenShot/openshot-qt/issues/730?

**Comment by ferdnyc** [comment]
I'm going to close this, since tab order in the Daily Builds has already been sorted out, and the fix will be in the next release. The issue was addressed by @SuslikV in #2782 — the PR just wasn't tagged to auto-close.
