### ISSUE TITLE
Even downloading the 2.4.4-dev1 Audio doesn't working

### ISSUE THREAD

**Issue by CristiAllan** [OpenShot/openshot-qt#2781]
Hello guys!

I don't know what is happening, but after installing a new OS(I installed the newest version for Elementary OS, which is based on Ubuntu 18.04 LTS), I downloaded the newest version of OpenShot but the sound doesn't work. I downloaded the 2.4.4-dev1 version and still getting problem, even old .osp projects simply doesn't have any sound.

The 'Enable Video' option works well for a track, but no matter if it's setted as -1, 0 or 1 to 'Enable Audio' option. I don't get any sound of my tracks, I already tested .mp4 and .mkv files.

Do I need some extra config?

**Comment by SuslikV** [comment]
When exported, is there any sound in files? Where is your log-files?

**Comment by CristiAllan** [comment]
After sending the issue, I removed the 2.4.4-dev1 and installed 2.4.4 again and it worked well.
Unfortunatelly I don't have any clue of what happened, but it's working now, thanks
