### ISSUE TITLE
Find directory that contains declan2.mp3 not finding the file that exists in the directory

### ISSUE THREAD

**Issue by seanjmcm** [OpenShot/openshot-qt#2783]
**Describe the bug:**
I moved the project to a new folder.  When I open it is says,

`Find directory that contains declan2.mp3`

I browse to the correct directory `audio` using openshot  but the file that is there in windows explorer and is called declan2.mp3 is not present.  

Why can I not load the mp3 file?

**Steps to reproduce the behavior:**
Move the project to a folder on another drive.

**Expected behavior:**
To be able to select the file

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.
Log files can be found in your HOME/.openshot_qt/ folder. Please compress or zip
the log files (as they can become quite large).

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please
attach a small snippet of the exception here, but please keep it as small as
possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them here, dragging-and-dropping into this form, or clicking below and loading
images saved to your computer. All images are public, so please don't post screenshots
containing personal information.
![image](https://user-images.githubusercontent.com/9802201/57637620-cc58c700-75a3-11e9-9182-3fbd5d298f1e.png)

**Comment by SuslikV** [comment]
Please, post your openshot log-file (you may .zip it before attaching).
