### ISSUE TITLE
Rotate to left do not work

### ISSUE THREAD

**Issue by enzopolo** [OpenShot/openshot-qt#2784]
**Describe the bug:**
The Rotate to left do not work fine.

Verso 2.4.3 and 2.4.4 has been tested

**Comment by SuslikV** [comment]
Clarify issue, please. It rotates the source clip, not profile or output width/height, so what is wrong?

**Comment by ferdnyc** [comment]
I'm going to close this as a duplicate of #2794 / #2969, which contain the most detail on this issue.
