### ISSUE TITLE
How to fix starting point for zoom effect scale x and y with bezier ease in/out

### ISSUE THREAD

**Issue by justinechacko** [OpenShot/openshot-qt#2790]
Is there any zoom effect like blur and pixelate available? or how I fix starting point for zoom effect scale x and y with bezier ease in/out. Some time zoom is not smooth even if I set ease in/out.

**Comment by SuslikV** [comment]
Blur filter is present.
It is not clear what effect you want to achieve with the zoom. The place where zoom starts is marked by small green dot (animation key). Try linear part first and in few frames set smooth curve.

**Comment by justinechacko** [comment]
I can see smooth zoom if I try from start of the clip to say a 5 seconds. But if I cut clip from a time say 30 s

**Comment by SuslikV** [comment]
You can only remove existing animation key (right-click over the parameter in _Properties_ list) when the _Timeline_ cursor is under the key (the parameter in _Properties_ list turns green). The whole animation can be removed by right-click menu over the selected clip in the _Timeline_ the option _Animate > No Animation_ .

**Comment by justinechacko** [comment]
Okey, is there any way to pause after zoom in for a 2 seconds, and ** then I need to zoom out**. I tried time>freeze for 2 seconds. But it zoom out not respecting freeze.

**Comment by justinechacko** [comment]
I got it, I need to add same scale to next seconds.

**Comment by peanutbutterandcrackers** [comment]
@SuslikV - You're here too, thank you!

@justinechacko - Please go through this guide: https://github.com/OpenShot/openshot-qt/wiki/OpenShot:-Zero-To-Hero-Guide and you'll become a keyframe-ninja in OpenShot. Hopefully you'll be able to create something like the following soon:

![meet tux](https://user-images.githubusercontent.com/26764547/48016787-a1a13800-e154-11e8-9f1d-bfe2a64a6ad4.gif)

**Comment by SuslikV** [comment]
@peanutbutterandcrackers No way, am I know you? It was big mistake to dig into this soft. Application imprecise, unhandy, resource demanding and it was ported on Windows...

**Comment by DylanC** [comment]
Answered.
