### ISSUE TITLE
Can't rotate videos to original position when "Rotation" present in metadata.

### ISSUE THREAD

**Issue by tofran** [OpenShot/openshot-qt#2794]
**Description:**
When a video has a non zero `Rotation` in its metadata its impossible to rotate it to its original position.

EXIF causing the issue:
```
Rotation                        : 90
```

**Steps to reproduce:**
1. On your phone start recording a video vertically and then flip it to horizontal
2. Add that video to the timeline
3. Right click it > rotate
4. Both "No Rotation" and "Rotate 90 (Right)" will keep the video vertical (all other options will not flip it to the desired orientation)

**Expected behavior:**
The video should be flipped to horizontal.

**System Details:**
- OpenShot Version [v2.4.4]: OpenShot-v2.4.4-x86_64
    also tried with build `dev1-1558038193-42af4ca8-9a1a6093`
- Video camera: Oneplus 6

**Demo:**
[![image](https://user-images.githubusercontent.com/5692603/57960620-a31c9b80-7901-11e9-93b6-57cc93694bbb.png)](https://drive.google.com/file/d/1X3-yOoi1urKoPK3ppRBjTMck1F-LnJKJ/view?usp=sharing)

**Video Sample**
[unrotatabe-video.mp4](https://drive.google.com/file/d/1AZJtqKtmFnilNVAbXOZt8xC4oVOWmdcD/view?usp=sharing)

**Related issues:**
I'll link here some issues that may be related, but lack information:
#2784
#2785
#2700
#2629

**Comment by peanutbutterandcrackers** [comment]
@tofran - Thank you for the well-written report. I will try to get the devs to look into this. :+1:

**Comment by SuslikV** [comment]
Possible workaround.
In the _Properties_ of the selected clip set _Rotation_ to very small value, for example: `0,00000000000000000001` thus clip will rotate at desirable position the simple `0` won't work - just a bug.

**Comment by rredford** [comment]
I used 0.001 which was small enough to round to zero. Annoying though.

**Comment by SuslikV** [comment]
@rredford this is kind of "optimization" to escape unneeded transform during rendering (which itself is only limited to bilinear with blurry result) and improve speed of the application. Thus, this is not only UI bug.

Related check, that doing transform, is seems to be here (libopenshot library): https://github.com/OpenShot/libopenshot/blob/a8d545ea92a8a061b0117a2ff6e7a1a78d818c1f/src/Timeline.cpp#L521
Default value of 90 degree is set during read of the file (for such clip as on example above), so rotating more - can do 0 degree total (no rotation). But then, why my `0,00000000000000000001` works here is a big question for me...

**Comment by rredford** [comment]
I did not state what source of bug was, not saying if it was UI bug nor complex bug or anything. Not sure what you are trying to correct.

**Comment by tofran** [comment]
I don't think this issue should be closed for lack of activity.
This is a breaking bug that prevents non-technical people from using openshot.
