### ISSUE TITLE
Blinking Titles

### ISSUE THREAD

**Issue by Pine9** [OpenShot/openshot-qt#2795]
**Describe the bug**
When title text is added, it blinks repeatedly, in both the preview and the final version of the video.
I saw a similar issue on GitHub from 2017, but it was closed. I tried downloading the daily build, but it didn't seem to make a difference.

**Steps to reproduce the behavior:**
1. Start a new project and import a video file to add to your timeline or open a current project with this already in place.
2. Go to 'Title -> Title'
3. Select a font. It doesn't matter if you modify it or not. In my case, I chose Standard 1, removed the subtitle, changed the title text, changed the text color to white, and changed the font.
4. Add it to your timeline.
5. See that in the video preview, the text blinks. Even if you export the video, the issue remains.

**Expected behavior**
I was expecting the title to remain static.

**System Details**
- OpenShot Version: 2.4.4-dev1
- libopenshot Version:  0.2.3
- Platform: Windows-10-10.0.17134
- Processor: Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
- Machine: AMD64
- Python version: 3.6.4
- Qt5 version: 5.9.1
- PyQt5 version: 5.9
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.4.4-dev1-1558038498-42af4ca8-9a1a6093-x86_64.exe

**Log Files**
- http://logs.openshot.org/zplmbskrabsfpiekdnm2wg59o1slq4op/openshot-qt.zip
- http://logs.openshot.org/zplmbskrabsfpiekdnm2wg59o1slq4op/libopenshot.zip

**Comment by SuslikV** [comment]
What name of the title template you trying?

**Comment by Pine9** [comment]
@SuslikV Standard 1, but I see the behavior for other titles as well.

**Comment by SuslikV** [comment]
Strange, I don't see it. And if you add simple .png or .jpg image - is it blinks too?

**Comment by Pine9** [comment]
@SuslikV Yes, images blink too. I just realized that this blinking behavior only happens when I import a preexisting video file, then try to add a title or image on top of that. If I just add the title and there's nothing else in the project, it doesn't blink.
