### ISSUE TITLE
Reversed video has blank spots during playback example https://streamable.com/blsek  in older versions of openshot this function was smooth but more recent versions have more funky than functional

### ISSUE THREAD

**Issue by nic7773** [OpenShot/openshot-qt#2798]
**Describe the bug:**

**Steps to reproduce the behavior:**

**Expected behavior:**

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.
Log files can be found in your HOME/.openshot_qt/ folder. Please compress or zip
the log files (as they can become quite large).

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please
attach a small snippet of the exception here, but please keep it as small as
possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them here, dragging-and-dropping into this form, or clicking below and loading
images saved to your computer. All images are public, so please don't post screenshots
containing personal information.

**Comment by SuslikV** [comment]
It worth adding a log-file. Because it is not clear is the problem persist in the current build on your OS or it already was resolved.

**Comment by nic7773** [comment]
OpenShot Version 2..4.4
Operating System Windows 10 Pro version 1809
The clip was done the night I posted the complaint. There was no error log file as the clip rendered and played...but the finished clip had blank spots in it.

**Comment by SuslikV** [comment]
Try https://www.openshot.org/download/ (click "daily builds" button)

**Comment by nic7773** [comment]
I downloaded the 32bit version and it worked smoother....thanx!
