### ISSUE TITLE
How to export a video as GIF

### ISSUE THREAD

**Issue by florianjacob** [OpenShot/openshot-qt#280]
Hi there, I'm using openshot-qt 2.0.7. I want to cut out a short scene from an mp4 video and export it as animated, looping GIF, but I could not find out how to do that. :disappointed:

The blog post at http://www.openshotvideo.com/2015/02/february-update-gifs-video-playback.html is the only thing I found concerning GIF support and openshot, and it suggests it should be possible somehow(?) with 2.0.

Thanks!

**Comment by jarlarntzen** [comment]
:+1:

**Comment by JtLively** [comment]
I'd recommend using one of the following sites to create a GIF from a video:
[EZ Gif](http://ezgif.com/)
[Make a Gif](http://makeagif.com/)

**Comment by florianjacob** [comment]
Thanks, I used similar sites before, but I was looking for an integrated solution to export gifs directly from a video editor to make the process easier and faster. The blogpost seemed like openshot would support this somehhow.

For the record, I ended up using [shotcut](https://shotcut.org), which achieves this via its ffmpeg export. :wink:

**Comment by adiakritos** [comment]
the gifs generated from those sites are very low-resolution. I need something that allows me to get a gif as high-res as the video I made it from or at least close to it.

**Comment by Wtower** [comment]
Although this does not answer your question, take a look:

https://askubuntu.com/questions/648603/create-animated-gif-from-mp4-video-via-command-line

**Comment by florianjacob** [comment]
@Wtower nice solution for Linux users, and that's what I'd use if I had to do this. But in my case, this was actually for a friend on Windows, and using ffmpeg on the command line on Windows just to get a video converted is nothing they'd be willing to do. 😉

**Comment by Raybo128** [comment]
In Openshot, with your video in the timeline, select Export, then click the Advanced tab, under Advanced Options, set an export path, export to "Image Sequence" from the dropdown.  Image Sequence Settings default to.png.  Click Export Video and the result will be a series of still images in your folder.

Now open Gimp and go to File -> Open As Layers, browse to the export folder, select all the files and click open.  Go to Filters menu -> Animation, then click optimize for GIF.  Go back to File -> Export As, then select GIF from dropdown, enter filename.  Then in dialog box, click "As animation", then click "Export".  It should result in an animated GIF file.

These are simplified instructions but you get the idea.  Experiment with settings.

**Comment by peanutbutterandcrackers** [comment]
@Raybo128 - Awesome work-around, good sir! I hope you keep on helping out here in the forums! :+1:

**Comment by gabrielchung** [comment]
You can also use ffmpeg to convert a mp4 video to animated GIF.

Example command:
ffmpeg.exe -i demo.mp4 -f gif demo.gif

**Comment by AnnaO1984** [comment]
> In Openshot, with your video in the timeline, select Export, then click the Advanced tab, under Advanced Options, set an export path, export to "Image Sequence" from the dropdown. Image Sequence Settings default to.png. Click Export Video and the result will be a series of still images in your folder.
> 
> Now open Gimp and go to File -> Open As Layers, browse to the export folder, select all the files and click open. Go to Filters menu -> Animation, then click optimize for GIF. Go back to File -> Export As, then select GIF from dropdown, enter filename. Then in dialog box, click "As animation", then click "Export". It should result in an animated GIF file.
> 
> These are simplified instructions but you get the idea. Experiment with settings.

Ok, very strange, because I don't have 'save as layers' , no Filters menu and certainly no 'Export as Gif' ? Is there a extension I should install or something?

**Comment by ferdnyc** [comment]
@AnnaO1984 I believe the GIMP animation tools are part of the GAP, the GIMP Animation... Package? Plugin? Something like that. That's what you'd want to look for, if you need to work with multi-frame files.

"OPEN As Layers" (not Save) I believe is a standard feature, but the rest all sounds like GAP enhancements.

**Comment by ferdnyc** [comment]
(If you ever do find yourself needing a "Save Layers" feature (meaning, you want to write every layer of a GIMP image out as a separate PNG file), I only recently [solved that one, myself](https://askubuntu.com/a/1263136/166554).)

**Comment by dscotese** [comment]
I added this topic to the Reddit forum and figured further discussion is warranted and should happen there, so here's a link: https://www.reddit.com/r/OpenShot/comments/ixe4y4/annao1984_how_to_make_an_animated_gif_issue_280/

**Comment by M0gyy** [comment]
You just need to name your export SOMETHING.gif and hit export. The menu to choose animation details then comes up.

**Comment by yofr** [comment]
In export video menu, , select export to "image sequence" in advanced options, and change "image format" in image sequence settings (see below) to .gif instead of png:
![image](https://user-images.githubusercontent.com/6814849/110937422-a1bc2e80-8332-11eb-9de6-e8f498dfc688.png)

**Comment by florianjacob** [comment]
Seems like this indeed works now, thank you!
