### ISSUE TITLE
How do you completely remove audio?

### ISSUE THREAD

**Issue by openshotnewguy** [OpenShot/openshot-qt#2800]
How do you completely remove the audio stream from your video?

I have been trying to edit videos in webm(vpx) so that I can post them on 4chan, 4chan has a strict under 2mb with no audio stream requirement.

The problem I am running into is that I have hit the size requirement, I have tried setting the value in properties to my clips to 0 and -1 for the enable audio tab. I have also set the volume to 0. I have also tried splitting my audio and deleting it.

Unfortunately 4chan still detects and audio stream when trying to post the webm even though it has no sound in the clip, I believe the audio stream of nothing still exists and 4chan is detecting that the channel is still open.

I was wondering if anyone has found a fix for this?

**System Details:**
OpenShot Version 2.4.4
Windows 7 Ultimate

**Comment by SuslikV** [comment]
Main menu _File > Export Video > Advanced tab > Advanced Options > Export To: **Video Only**_

**Comment by DylanC** [comment]
Answered.
