### ISSUE TITLE
How to create a list of Clip from list of Photo

### ISSUE THREAD

**Issue by trithucbkpro** [OpenShot/openshot-qt#2801]
Today, I build openshot library on my Mac, after that, I read some example in project and try to create a program myself in Python
      I have an audio file and 2 photos to create a video, when I create a clip for each photo , everything is ok, but when I put 2 photos in a list, some exeption thrown. I searched on both Google and Issues in project, seem nobody face with problem. (I want to create video with unknow size of list photo, it can be 5, 10 or 20... photos)
There are 2 case I used

Case 1: Everything is ok

   audioReader = openshot.FFmpegReader("data/record_12345.m4a")
    audioClip = openshot.Clip(audioReader)
    audioClip.Layer(0)
    audioClip.End(20)  # audioClip.Duration()
    audioClip.has_video = openshot.Keyframe(0)
    t.AddClip(audioClip)

    imgReader1 = openshot.QtImageReader(listPhoto[0])
    clip1 = openshot.Clip(imgReader1)
    clip1.Layer(1)
    clip1.Position(0.0)
    clip1.End(5.0)
    t.AddClip(clip1)

    imgReader2 = openshot.QtImageReader(listPhoto[1])
    clip2 = openshot.Clip(imgReader2)
    clip2.Layer(1)
    clip2.Position(5.0)
    clip2.End(5.0)
    t.AddClip(clip2)

Case 2:

    index = 0
    for photo in listPhoto:
        imgReader = openshot.QtImageReader(photo)
        clip1 = openshot.Clip(imgReader)
        clip1.Layer(1)
        start = index * 5
        clip1.Position(start)
        clip1.End(5.0)
        t.AddClip(clip1)
        index += 1
throw Exception : 

   Caught signal 11 (SIGSEGV)
---- Unhandled Exception: Stack Trace ----
4   libopenshot.17.dylib                0x0000000101d77cf2 _ZN8openshot4Clip4OpenEv + 68
  5   libopenshot.17.dylib                0x0000000101e0f19f _ZN8openshot8Timeline17update_open_clipsEPNS_4ClipEb + 1035
  6   libopenshot.17.dylib                0x0000000101e11a47 _ZN8openshot8Timeline23find_intersecting_clipsExib + 1235
  7   libopenshot.17.dylib                0x0000000101e107ea _ZN8openshot8Timeline8GetFrameEx + 2174
  8   _openshot.so                        0x00000001019d8821 _wrap_Timeline_GetFrame + 337
  9   Python                              0x00000001009a0020 _PyMethodDef_RawFastCallKeywords + 243
  10  Python                              0x000000010099f6a8 _PyCFunction_FastCallKeywords + 44
  11  Python                              0x0000000100a33956 call_function + 624
  12  Python                              0x0000000100a2beeb _PyEval_EvalFrameDefault + 5156
  13  Python                              0x000000010099fa87 function_code_fastcall + 116
  14  Python                              0x0000000100a339c6 call_function + 736
  15  Python                              0x0000000100a2bed2 _PyEval_EvalFrameDefault + 5131
  16  Python                              0x000000010099fa87 function_code_fastcall + 116
  17  Python                              0x0000000100a339c6 call_function + 736
  18  Python                              0x0000000100a2beeb _PyEval_EvalFrameDefault + 5156
  19  Python                              0x000000010099fa87 function_code_fastcall + 116
  20  Python                              0x0000000100a339c6 call_function + 736
  21  Python                              0x0000000100a2bf91 _PyEval_EvalFrameDefault + 5322
  22  Python                              0x000000010099fa87 function_code_fastcall + 116
  23  Python                              0x0000000100a339c6 call_function + 736
  24  Python                              0x0000000100a2bf91 _PyEval_EvalFrameDefault + 5322
  25  Python                              0x0000000100a341aa _PyEval_EvalCodeWithName + 1683
  26  Python                              0x0000000100a2aa3f PyEval_EvalCode + 42
  27  Python                              0x0000000100a59477 run_mod + 54
  28  Python                              0x0000000100a584a7 PyRun_FileExFlags + 160
  29  Python                              0x0000000100a57b70 PyRun_SimpleFileExFlags + 277
  30  Python                              0x0000000100a6fcf6 pymain_main + 4914
  31  Python                              0x0000000100a705c3 _Py_UnixMain + 75
  32  libdyld.dylib                       0x00007fffd9d7e235 start + 1
---- End of Stack Trace ----

I have no Idea "Why"

**Comment by ctsdownloads** [comment]
Is this still an issue on current version of OpenShot?
