### ISSUE TITLE
Openshot crashes when I try to open .mp4 on Mac

### ISSUE THREAD

**Issue by egrabczewski** [OpenShot/openshot-qt#2802]
**Describe the bug**
Openshot crashes when I try to open an 32MB .mp4 file

**Steps to reproduce the behavior:**
1. Click "New Project" icon. Nothing happens.
2. Click on "+" icon. A dialogue opens and I select the .mp4 file
3. OpenShot immediately crashes.

**Expected behavior**
Obviously I expect it to either add the file to the project files or to tell me that this file format is not supported.

**System Details**
- OpenShot Version: 2.4.4-dev1
- libopenshot Version:  0.2.3
- Platform: Darwin-17.7.0-x86_64-i386-64bit
- Processor: i386
- Machine: x86_64
- Python version: 3.6.4
- Qt5 version: 5.5.1
- PyQt5 version: 5.5.1
- Qt Detected Languages: ['en-GB']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.4.4-dev1-1558038332-42af4ca8-9a1a6093-x86_64.dmg

**Log Files**
- http://logs.openshot.org/r67b62ks26x2xuig8ul7cryjq9hoeth6/openshot-qt.zip
- http://logs.openshot.org/r67b62ks26x2xuig8ul7cryjq9hoeth6/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by egrabczewski** [comment]
I'm not sure about the "System Detials" part of this log. Here is what I am running on:
 Model Name:	iMac
  Model Identifier:	iMac11,1
  Processor Name:	Intel Core i5
  Processor Speed:	2.66 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Memory:	16 GB
  Boot ROM Version:	62.0.0.0.0
  SMC Version (system):	1.54f36
  Serial Number (system):	VM0099NU5PJ
  Hardware UUID:	53AF59A1-04DA-520C-8539-D34BE8E3DAEE

**Comment by SuslikV** [comment]
Here, @oisinmulvihill says that OpenShot may work better with OSX Mojave (10.14.3) : https://github.com/OpenShot/openshot-qt/issues/2114#issuecomment-487875996

**Comment by DylanC** [comment]
@egrabczewski ^
