### ISSUE TITLE
Aspect Ratio Issue / Scaling Issue with "4K" Dash Cams

### ISSUE THREAD

**Issue by devlin85** [OpenShot/openshot-qt#2803]
When opening videos that have a forced aspect other than the resolution it ends up scaling incorrectly. For example. All modern "4K" dash cams have a resolution of 2880x2160 but an aspect ratio of 16:9 to make it widescreen. "Best Fit" assumes it is 4:3 based on the resolution and makes the video look as such, with black bars on the side. You can manually correct the issue by changing the scale method to "stretch". This does work, but it's a pain to have to do it to every single video.

**Comment by ctsdownloads** [comment]
If this remains an issue on the current version of OpenShot, make sure your preview profile and rendering profile for export match aspect ratio.
