### ISSUE TITLE
NoneType' object is not subscriptable error 

### ISSUE THREAD

**Issue by paolomessina511** [OpenShot/openshot-qt#2805]
**Describe the bug**
When I launch the file I get 'NoneType' object is not subscriptable error and file doesn't open. 

**System Details**
- OpenShot Version: 2.4.4-dev1
- libopenshot Version:  0.2.3
- Platform: Windows-10-10.0.17134
- Processor: x86 Family 6 Model 42 Stepping 7, GenuineIntel
- Machine: x86
- Python version: 3.6.4
- Qt5 version: 5.9.1
- PyQt5 version: 5.9
- Qt Detected Languages: ['it-IT', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.4.4-dev1-1558039835-42af4ca8-9a1a6093-x86.exe

**Log Files**
- http://logs.openshot.org/1rk3gw3pvfq0b8lnpfmfef7vjhjx2uaa/openshot-qt.zip
- http://logs.openshot.org/1rk3gw3pvfq0b8lnpfmfef7vjhjx2uaa/libopenshot.zip

**Comment by SuslikV** [comment]
Can you pack to .zip and post your .osp (project file) you have problems with?

**Comment by ferdnyc** [comment]
Ahhh, crap. OK, maybe not closing _all_ of these, since this report came in three weeks after we thought we'd finally fixed all of these. So I'll leave it open a bit longer to see if @paolomessina511 responds, before closing as abandoned.

**Comment by mikelacsa** [comment]
Issue not responded to after 7 days of being labeled "needs info". Closing this issue.
