### ISSUE TITLE
Inconsistent behaviour of 'New Project ...'

### ISSUE THREAD

**Issue by udippel** [OpenShot/openshot-qt#2806]
This might explain #1234 and #1879.
At first, I also thought Openshot wouldn't work at all. But then I found that 'New Project...' actually works, even removes previous clips and stuff. Though it is inconsistent w.r.t. a basic UI paradigm: a command followed by 3 dots requires some user input. In this case it doesn't. I think that a file selection box (like the one that pops up when you click '+') would sort things out pretty well: offering the user a potential location, an existing or new folder and a project file name. Then the .osp as well as resulting, rendered, file would be stored there. And eventually to be added files ('+') would by default searched in there.

**Comment by ferdnyc** [comment]
@udippel 

You're absolutely correct about the "New Project" ellipses. There are, of course, [a lot of gray areas](https://stackoverflow.com/questions/637683/when-to-use-ellipsis-after-menu-items) in the rules governing their use, and a lot of inconsistencies even among software written _by_ the OS vendors responsible for those rules. (For instance, should our "Choose Profile" menu entry have ellipses? How about "Export"? You could make a case for "Title" and "Animated Title" as well, while you were at it.

But, all _that_ aside, some things are clear and unambiguous. The fact that our "New Project" menu option has no business displaying ellipses at the end is one of those. Submitted #2879 to address. Thanks!
