### ISSUE TITLE
Export Movie Fails 

### ISSUE THREAD

**Issue by SeaMac** [OpenShot/openshot-qt#2807]
**Describe the bug**
Export Movie Fails

**Steps to reproduce the behavior:**
1. Make a Movie
2. Export it
3. OpenShot QUITS
4. May 27 05:26:02 Triple-Time com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x10000049.launch-mac.sh[33687]): Service exited with abnormal code: 4

**Expected behavior**
A movie file, somewhere.

**System Details**
- OpenShot Version: 2.4.4-dev1
- libopenshot Version:  0.2.3
- Platform: Darwin-16.7.0-x86_64-i386-64bit
- Processor: i386
- Machine: x86_64
- Python version: 3.6.4
- Qt5 version: 5.5.1
- PyQt5 version: 5.5.1
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.4.4-dev1-1558038332-42af4ca8-9a1a6093-x86_64.dmg

**Log Files**
- http://logs.openshot.org/6nyoemw2jst3gh7glcuv4s73m4f50ig2/openshot-qt.zip
- http://logs.openshot.org/6nyoemw2jst3gh7glcuv4s73m4f50ig2/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by SeaMac** [comment]
It won't Export ANY Movie!!!! It INSTANTLY QUITS!!!!!

**Comment by SuslikV** [comment]
Try to export to webm format for example.
Any changes?

**Comment by SeaMac** [comment]
> Try to export to webm format for example.
> Any changes?

I tried to change my project's Profile to webm format ...
![image](https://user-images.githubusercontent.com/5051781/58430146-10949e80-805d-11e9-8f0d-52fec32aad98.png)

Where is it on this list? 
![image](https://user-images.githubusercontent.com/5051781/58430179-2bffa980-805d-11e9-9d94-3843f5ab52e7.png)

Does the profile matter when exporting?

**Comment by SeaMac** [comment]
> Try to export to webm format for example.
> Any changes?

Which webm? vp9 or vpx ? (Leaving the profile alone for now.)

**Comment by SeaMac** [comment]
VPX format: FAILS! 
These are the most recent errors from my Console:
May 27 08:57:32 Triple-Time com.apple.xpc.launchd[1] (com.apple.quicklook[37905]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.quicklook
May 27 08:59:51 Triple-Time syslogd[39]: ASL Sender Statistics
May 27 09:01:43 Triple-Time com.apple.xpc.launchd[1] (com.apple.quicklook[37946]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.quicklook
May 27 09:04:42 Triple-Time com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x1000004c.launch-mac.sh[37802]): Service exited with abnormal code: 4

**Comment by SeaMac** [comment]
Reopened OpenShot. Reloaded my Project. Tried using webm VP9 export.
Same Thing.

These 2 got added to my Console's system.log 👍 May 27 09:05:54 Triple-Time com.apple.xpc.launchd[1] (com.apple.quicklook[37987]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.quicklook
May 27 09:09:03 Triple-Time com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x1000004d.launch-mac.sh[38003]): Service exited with abnormal code: 4

And I'm SURE now that these errors ARE related to the sudden and total crash on export.
And now I'll try different profiles ... (I have lots of "Combos" of Profile and Format ... are they all compatible?)

**Comment by SeaMac** [comment]
> Try to export to webm format for example.
> Any changes?

Nope. I have tried a variety of Profiles and Formats for Exporting Movie ... any of the attempts I made caused OpenShot to immediately quit. 

Further suggestions? / Updated Log Files you would Need?

**Comment by SuslikV** [comment]
Newer OS. I have no other ideas.
