### ISSUE TITLE
OpenShot closes when I import or drag SVG files on project

### ISSUE THREAD

**Issue by RafaelLinux** [OpenShot/openshot-qt#2809]
**Describa el problema**
OpenShot close when I drag SVG files on project

**Pasos para reproducir el comportamiento:**
1. Select an SVG file an drag it to "Project Files"

**Comportamiento esperado**
Continue working as with previous version

**Detalles del sistema**
- OpenShot Version: 2.4.4
- libopenshot Version:  0.2.3
- Platform: Linux-4.12.14-lp150.12.61-default-x86_64-with-glibc2.4
- Processor: x86_64
- Machine: x86_64
- Python version: 3.4.3
- Qt5 version: 5.2.1
- PyQt5 version: 5.2.1
- Qt Detected Languages: ['es']
- LANG Environment Variable: es_ES.UTF-8
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.4.4-dev1-1558038193-42af4ca8-9a1a6093-x86_64.AppImage

**Archivos de registro**
- http://logs.openshot.org/ggc3m5o5vqfg63z4u1nm75cpfehujj7j/openshot-qt.zip
- http://logs.openshot.org/ggc3m5o5vqfg63z4u1nm75cpfehujj7j/libopenshot.zip

**Excepción / Rastreo de pila**
```/tmp/.mount_1FbZcN/usr/bin/libopenshot.so.17 openshot::QtImageReader::Open()          0x75a  [0x7fe13f22147a]
/tmp/.mount_1FbZcN/usr/bin/libopenshot.so.17 openshot::QtImageReader::QtImageReader(std::string) 0x69  [0x7fe13f221d69]
/tmp/.mount_1FbZcN/usr/bin/libopenshot.so.17 openshot::Clip::Clip(std::string)        0x5dc  [0x7fe13f1ab43c]
/tmp/.mount_1FbZcN/usr/bin/_openshot.so                                          0x74cfd  [0x7fe13f4e8cfd]
/tmp/.mount_1FbZcN/usr/bin/libpython3.4m.so.1.0 PyEval_EvalFrameEx                       0x654b  [0x7fe15441b00b]
/tmp/.mount_1FbZcN/usr/bin/libpython3.4m.so.1.0 PyEval_EvalCodeEx                        0x886  [0x7fe15441e9c6]
/tmp/.mount_1FbZcN/usr/bin/libpython3.4m.so.1.0                                          0x209ff6  [0x7fe15441eff6]
/tmp/.mount_1FbZcN/usr/bin/libpython3.4m.so.1.0 PyObject_Call                            0x68  [0x7fe1543807a8]
/tmp/.mount_1FbZcN/usr/bin/libpython3.4m.so.1.0                                          0x1515ed  [0x7fe1543665ed]
/tmp/.mount_1FbZcN/usr/bin/libpython3.4m.so.1.0 PyObject_Call                            0x68  [0x7fe1543807a8]
/tmp/.mount_1FbZcN/usr/bin/libpython3.4m.so.1.0                                          0xcac29  [0x7fe1542dfc29]
/tmp/.mount_1FbZcN/usr/bin/libpython3.4m.so.1.0                                          0x174686  [0x7fe154389686]
/tmp/.mount_1FbZcN/usr/bin/libpython3.4m.so.1.0 PyObject_Call                            0x68  [0x7fe1543807a8]
/tmp/.mount_1FbZcN/usr/bin/libpython3.4m.so.1.0 PyEval_EvalFrameEx                       0x44cd  [0x7fe154418f8d]
/tmp/.mount_1FbZcN/usr/bin/libpython3.4m.so.1.0 PyEval_EvalFrameEx                       0x6c5c  [0x7fe15441b71c]
/tmp/.mount_1FbZcN/usr/bin/libpython3.4m.so.1.0 PyEval_EvalCodeEx                        0x886  [0x7fe15441e9c6]
/tmp/.mount_1FbZcN/usr/bin/libpython3.4m.so.1.0                                          0x209ff6  [0x7fe15441eff6]
/tmp/.mount_1FbZcN/usr/bin/libpython3.4m.so.1.0 PyObject_Call                            0x68  [0x7fe15438...

**Comment by SuslikV** [comment]
And if you just add it via main menu _File > Import Files_?

**Comment by RafaelLinux** [comment]
I tried, but same result. OpenShot closes.

**Comment by SuslikV** [comment]
Can you provide sample SVG file that you can't import to OpenShot?

**Comment by RafaelLinux** [comment]
Of course. I have more, but this is an example (saved from Inkscape with default config).
[corona.tar.gz](https://github.com/OpenShot/openshot-qt/files/3244212/corona.tar.gz)

**Comment by SuslikV** [comment]
It seems to be an issue inside the _resvg_ lib, because it din't crashes if _libopenshot_ uses only _QtSvg_ module. I need to look at files closer. Later I will update info on this. Meanwhile, try to modify an existing svg file (make copy of it), save it and try to add to OpenShot again.

Your copy re-saved in Inkscape v0.92.1 (should work well), about 2 KB to download, CRC of the zip archive MD5:00423C3ED801E0A447996208980A43E7
[corona_resaved.zip](https://github.com/OpenShot/openshot-qt/files/3244689/corona_resaved.zip)

**Comment by SuslikV** [comment]
You trying to import extremely huge image (viewBox parameter). It isn't supported in current version of OpenShot.

**Comment by RafaelLinux** [comment]
I loaded corona_resaved.svg without problems. Previously, I tried to load corona.svg saved as "Plain SVG" but did not seem to change nothing, crashed equally.

About the size, I tried at 1920px width, and crashed equally. Most of NLE don't do a constant render of SVG/vector sources, so when a SVG is resized 2x or 3x it's original size, they are blurry. That's why I insert SVG at that size, cause usually I show it at 200px width and progressively transform it to 3x or 4x times his size.

**Comment by SuslikV** [comment]
What is default size of the canvas you are working at in Inkscape? Try A4. Check in main menu of Inskscape _File > Document Properties_ you need to look at _Display units_ (mm), _Scale_ (1.00000) and _Viewbox_ (210.00; 297.00). Each time you saving files to use later in OpenShot I recommend to click _Resize page to drawing or selection_ button (it will resize canvas to your drawing before saving).

**Comment by RafaelLinux** [comment]
I usually work with the image with a width of twice FHD resolution, and adjust canvas just to the exact size all the objects grouped. I must say that I have not problems with the same SVG with other NLEs, so maybe the issue is related to some library, as you wrote.

**Comment by RafaelLinux** [comment]
2.5.1 AppImage - still same error  :(

**Comment by RafaelLinux** [comment]
It seems it's working yet!!!
Thank you
