### ISSUE TITLE
No waveform generation from MP4-Clip (?) but from MP3 

### ISSUE THREAD

**Issue by udippel** [OpenShot/openshot-qt#2814]
(Does this have to make with #2285?)
I have an MP4-file with sound. When I 'separate audio' it takes ages, and yet doesn't show any waveform, though it plays okay. I tried another waveform generation, watching the spinning wheel, and still no waveform shown. 
What am I doing wrong? I dunno, because when I dump an MP3-file into a track, and make Openshot show the waveform, it take s a similar time, but produces that waveform.

**Comment by SuslikV** [comment]
What length of the used MP4?

**Comment by udippel** [comment]
With pleasure: some 40 to 50 minutes, with the mp3 of a similar size.

**Comment by SuslikV** [comment]
Is your zoom level of the _Timeline_ was set less than 5 seconds?

**Comment by udippel** [comment]
Thanks for your interest, again!
#2816 shows the situation as screenshot(s).

**Comment by SuslikV** [comment]
In the mentioned screenshots I see that zoom is less than 5 seconds (the digits right to "-" button of _Timeline_ scaling slider), try to increase it let's say to 15 seconds.

With the same clip at different scales I see different behavior of the _Timeline_ rendering. The waveform and time ruler may disappear:

For long clips **it may** render the audio waveform (scale 15 seconds)
![OpenShot_waveform_generation01good](https://user-images.githubusercontent.com/19683044/58745052-f0e1e980-8453-11e9-897b-6e6d9d357079.png)

Or **may not**  (scale 3 seconds), starting from 00:16:23 of the 25fps project the _Timeline_'s ruler rendering ends, and I see blank area; when scaling set to 1 second the blank area starts from about 00:05:27
![OpenShot_waveform_generation02bad](https://user-images.githubusercontent.com/19683044/58745055-f808f780-8453-11e9-8023-d86550aa79f3.png)

**Comment by udippel** [comment]
You are right. With 15 seconds when splitting audio, the waveform is immediately generated. 
(I mentioned somewhere else that this is no improvement for me, since with 2.4.1 it would split audio almost immediately, without creating the waveform. I think it's better done on demand if necessary.)
