### ISSUE TITLE
RFE: Indicate the track as 'active' at all times, not only at beginning and the end.

### ISSUE THREAD

**Issue by udippel** [OpenShot/openshot-qt#2816]
![Screenshot_20190530_131503](https://user-images.githubusercontent.com/50265752/58632877-39c85f80-82e7-11e9-923e-1b08a64d941f.png)
![Screenshot_20190530_131408](https://user-images.githubusercontent.com/50265752/58632879-39c85f80-82e7-11e9-9df0-6fe74a3d4f95.png)

With a fine timeline, it seems impossible to see which track is set active. Once I scroll to beginning or end, red colour indicates the active track. 
One screenshot show the active track at the start, the other shows no indication when in the center of that same track.

**Comment by ferdnyc** [comment]
Mmmm. This shouldn't be too hard, since it's a change I had already included in the (never-completed) #1883, so the code is already there for the stealing.

**Comment by ferdnyc** [comment]
Fixed in #2827, thanks to @SuslikV
