### ISSUE TITLE
Bad frames at beginning of video when selecting lower framerate during export from current profile

### ISSUE THREAD

**Issue by SmashManiac** [OpenShot/openshot-qt#2817]
**Describe the bug:**
When exporting a video, switching to a different profile with a lower framerate than the project's may cause the first frame(s) of the exported video to contain dummy data, such as cut content from imported clips.

**Steps to reproduce the behavior:**
1. Create a new project
2. Choose profile HD 720p 60 fps
3. Drag&drop a video file on a track
4. Change the Start property of the segment to a few seconds in
5. Align the beginning of the cropped segment with the beginning of the timeline
6. Select Export Video
7. In the General tab, select profile HD 720p 30 fps
8. Start the export
9. Open the exported video
10. Notice that the first frame of the video matches the first frame of the original clip instead of immediately after the cropped content

**Expected behavior:**
Selecting a profile in the Export Video dialog and selecting a profile in the Choose Profile dialog should result in the same export output.

**System Details:**
- OpenShot Version 2.4.4
- Operating System / Distro: Windows 7 SP1

**Log Files:**
N/A

**Exception / Stacktrace:**
N/A

**Comment by ctsdownloads** [comment]
Is this an issue with the current version available from the website?
