### ISSUE TITLE
Crash when deleting video clip

### ISSUE THREAD

**Issue by alexgleason** [OpenShot/openshot-qt#282]
Terminal output:

```
 main_window:INFO keyPressEvent: player.Position(): 4128
 main_window:INFO keyPressEvent: player.Position(): 4128
 main_window:INFO auto_save_project
 main_window:INFO keyPressEvent: player.Position(): 4128
 main_window:INFO actionRemoveClip_trigger
 main_window:INFO actionRemoveTransition_trigger
terminate called after throwing an instance of 'openshot::ReaderClosed'
  what():  No Reader has been initialized for this Clip.  Call Reader(*reader) before calling this method.
Aborted (core dumped)
```

I'm not sure exactly what happened. It seemed really random.

**Comment by jonoomph** [comment]
This should be fixed now. Please test with our latest daily build, and reopen this issue if it still breaks. Please include step by step instructions to reproduce, and attach log files of the crash (https://github.com/OpenShot/openshot-qt/blob/master/.github/CONTRIBUTING.md). Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot. Thanks!
