### ISSUE TITLE
Crash on importing mp4 (Windows 10 and Ubuntu 18.04) 

### ISSUE THREAD

**Issue by ReidDead** [OpenShot/openshot-qt#2821]
**Describe the bug**
Crash on importing mp4 (Windows 10 and Ubutu 18.04) 

**Steps to reproduce the behavior:**
1. Go to 'File Menu'
2. Click on 'Import File'
3. Scroll down to 'Select the mp4 file'
4. Openshot crash

**Expected behavior**
Import the mp4 to project files.

**System Details**
- OpenShot Version: 2.4.4-dev2
- libopenshot Version:  0.2.3
- Platform: Windows-10-10.0.17763
- Processor: AMD64 Family 16 Model 6 Stepping 2, AuthenticAMD
- Machine: AMD64
- Python version: 3.6.4
- Qt5 version: 5.9.1
- PyQt5 version: 5.9
- Qt Detected Languages: ['pt-BR', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.4.4-dev2-1559259840-85d6ac6a-9a1a6093-x86_64.exe

**Log Files**
- http://logs.openshot.org/lnohq4plfiuhswt0tjif87s8nsgidbz7/openshot-qt.zip
- http://logs.openshot.org/lnohq4plfiuhswt0tjif87s8nsgidbz7/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

The same behaviour using Win10 or Ubuntu 18.04
Tested on Win10 with version 2.4.4 and 2.4.4 Dev-2
Tested on Ubuntu18.04 with flatpak version and appimage

**Comment by SuslikV** [comment]
Can you import the file from this post: https://github.com/OpenShot/openshot-qt/issues/1290#issuecomment-489569399 ?

If possible, please share the file that causes problem for you (I want to test it).

**Comment by ReidDead** [comment]
Occur the same behaviour with your file, tested on Windows 10 2.4.4 dev-2.

Here is the file I wanted to import
https://drive.google.com/file/d/1GgplTzdSTtQljOVzZAjiNYROpy_ErJYp/view?usp=sharing

Thanks!

**Comment by SuslikV** [comment]
File not a case. You should able to import the mentioned by me the test file.

What path to file?
Can you place the test .mp4 file in the folder like "C:\OShot" and import from it?
Can you import image files (.png, for example)?

**Comment by ReidDead** [comment]
![print openshot](https://user-images.githubusercontent.com/22009970/59106099-ecae4400-890b-11e9-9050-24aec38f7889.png)

the images are importing correctly, the problemns with mp4 files persist

[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/3266018/openshot-qt.log)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/3266019/libopenshot.log)

**Comment by SuslikV** [comment]
It not a crash. Just a "not responding" state of the application (endless loop). Try at least "C:\OShot" path as suggested.

**Comment by ReidDead** [comment]
![print openshot](https://user-images.githubusercontent.com/22009970/59128963-d9b66680-8941-11e9-99c0-2f9df665fe8d.png)

The path is not the problem, I do not put the files in a path with special characters or space.
I'll try with a fresh install of windows 7 on a VM. It's strange, cause this occur on Ubuntu as well, but my windows may be the problem.

I left the endless loop for about nearly 50 minutes, after that, windows prompted me to force close the application.

**Comment by SuslikV** [comment]
And what happens if you try to import .mp3 file (audio only file)?

**Comment by speedytechdev** [comment]
@ReidDead Has your issue been solved?

**Comment by mikelacsa** [comment]
@ReidDead are you still having this issue?

**Comment by mikelacsa** [comment]
No response 7 days after labeled "needs info". Closing the issue.
