### ISSUE TITLE
Stuttering/cracking/popping in the end of the clip

### ISSUE THREAD

**Issue by vedurk** [OpenShot/openshot-qt#2824]
**Describe the bug**
Stuttering/cracking/popping in the end of the clip. The problem can be heard both in the video preview and the exported file.

**Steps to reproduce the behavior:**
1. Import MP4 video
2. Put it into timeline
3. Export

**Expected behavior**
Clear sound expected

**System Details**
- OpenShot Version: 2.4.4-dev2
- libopenshot Version:  0.2.3
- Platform: Windows-7-6.1.7601-SP1
- Processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
- Machine: AMD64
- Python version: 3.6.4
- Qt5 version: 5.9.1
- PyQt5 version: 5.9
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.4.4-dev2-1559259840-85d6ac6a-9a1a6093-x86_64.exe

**Log Files**
- http://logs.openshot.org/idyhzphmv4gjmqsnuztre53tdwplapzu/openshot-qt.zip
- http://logs.openshot.org/idyhzphmv4gjmqsnuztre53tdwplapzu/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Comment by vedurk** [comment]
Though, it does not seem to occur with every clip.

**Comment by SuslikV** [comment]
Try file with constant FPS. Or try to edit the audio file by external program (common practice) and add it as uncompressed track later. Video editors suitable for making audio drafts for sync purposes mainly.

**Comment by vedurk** [comment]
I tried to export the 720p 30 FPS option - still the same problem. By the way, the problem only occurs in the end of the recordings from my phone. Of course if I crop them just a bit, there is no stuttering.
Actually I'm already using Audacity to do the main audio editing - but for some clips I use OpenShot itself. If I use the combination of external audio editing or cropping the very last bit of the audio, then I am able to get satisfactory results.

**Comment by woofboy** [comment]
I have a similar problem, but it can be at the start of imported videos, too, or when I cut a video up and paste parts of it together - the parts where the video clips join together stutter/crack/pop (if the clips are short, the entire section is ruined because the stutter/crack/pop is all that you can hear). This is both in preview, but also (more importantly) after export. I'm working with MP4s, if that makes a difference. It's at the point where I'm trying to find an alternative editor because it's spoiling the videos I'm trying to produce.

**Comment by mikelacsa** [comment]
@vedurk are you still experiencing this issue with the latest version/deaily build?

**Comment by mikelacsa** [comment]
No response 7 days after being labeled "needs info". Closing the issue.

**Comment by vedurk** [comment]
Hi! Sorry, I forgot to check it again. I did download the latest build (OpenShot-v2.5.1-dev2-1591560328-c29174f1-7cec1822-x86_64.exe). The problem is still there. If needed, I could also upload the source MP4 file(s).
