### ISSUE TITLE
How change audio codec on output ?

### ISSUE THREAD

**Issue by Oxygenum** [OpenShot/openshot-qt#283]
In advanced settings im see only ac3 audio codec ?
How change it to mp3 or aac ?

**Comment by synapticjuice** [comment]
yes I have same problem. I'm using Openshot 2.1 on Ubuntu 16.04. There is no drop down menu under "export video - advanced - audio settings - audio codec". Openshot 1.4.3 has a drop down that lets you select AAC from the list. I have tried typing in AAC into Openshot 2.1 but this brings the error Sorry, there was an error exporting your video: exception class 'openshot.InvalidCodec' After searching and playing with the software I have not found the answer. Frustrating.

**Comment by Oxygenum** [comment]
Hi !
My solution for mp3 on output...
Type : libmp3lame instead ac3
Work in Linux with installed lame mp3 encoding library...

BR MK/Oxygenum

**Comment by synapticjuice** [comment]
anyone know how to solve for AAC?

**Comment by ricardojlrufino** [comment]
ac3 is not allowed in whatsapp web, libmp3lame works !!

**Comment by jmunin** [comment]
Hi, libmp3lame works in Windows 10 too, no need to install anything!!

**Comment by ibro99** [comment]
For AAC output, use libvo_aacenc for the output codec.

**Comment by zhitaoh** [comment]
I installed libfdk_aac on my Ubuntu and confirmed that the AAC encoder works with **avconv**. But my OpenShot 2.3.4 still complains about "openshot.InvalidCodec" when exporting to AAC audio using libfdk_acc. On the other hand, MP3 export using libmp3lame works. Any ideas?

**Comment by arbidroid** [comment]
I have the same problem. I can encode audo with AAC using ffmpeg but OpenShot complains with "openshot.InvalidCodec". Could someone that got this working please explain how he or she did it?

**Comment by Geesbugg** [comment]
I solved it, I select the AVI with mp4 codec so it was mp3.

**Comment by DylanC** [comment]
Original question has been solved here.

**Comment by LaraChicharo** [comment]
To use ACC:
Install the package libavcodec-extra.
Type libvo_aacenc instead of ac3.

**Comment by ezonakiusagi** [comment]
To use AAC in Openshot 2.4.3, just type "aac" in: "Advanced"->"Audio Settings"->"Audio Codec".

It would be so much better if there was  drop down menu of available codecs.

**Comment by hubyhuby** [comment]
+1 Would be nice to have a drop down with available audio exports. Like with video export formats

**Comment by Tomoms** [comment]
A drop down menu would be nice indeed, but I'd like to point out that using `libvo_aacenc` is not suggested by the [libav wiki](https://wiki.libav.org/Encoding/aac). `libfdk_aac` is the best codec, although it's not free. To use it in OpenShot, just install it and type `libfdk_aac` (although I believe in most distros the package is named `libfdk-aac`) in the audio codec textbox.

**Comment by Colorjet3** [comment]
I am going to submit an enhancement request to the development team to add the "Drop Down" option to the "Audio Codec" so we are not 2nd guessing what Openshot supports vs. having to know how to change it manually and then break something.  Additionally, I am going to request a drop down option for the "Bit Rate / Quality" as well.

@hubyhuby and @Tomoms.  If you guys have some suggestions as well please feel free to add it here and I will compile all in one request.

**Update:**  As you are thinking about this please check the User Guide for all relevant information that is available that may not have been available back in 2021 or earlier:
1.  Go to https://www.openshot.org/user-guide/
2.  Search for Export and read from there.

**Comment by Tomoms** [comment]
@Colorjet3 I haven't got any other suggestion. It seems a good idea to submit an enhancement request for this feature, thanks!
