### ISSUE TITLE
Cannot delete clip with the delete key

### ISSUE THREAD

**Issue by AndersBillLinden** [OpenShot/openshot-qt#2831]
**Describe the bug:**
I cannot use the delete key to delete a clip

**Steps to reproduce the behavior:**
1. Drag clip into timeline
2. Select clip with left mouse button, border is getting red
3. Press Delete

**Expected behavior:**
The clip should dissapear as in previous versions

**Actual behavior:**
The clip remains.

**System Details:**
- OpenShot https://github.com/OpenShot/openshot-qt/commit/591ac414f054b0f2f0a217449d1a4b871fbf3d5e
- Windows 10

**Comment by ferdnyc** [comment]
@AndersBillLinden 

It still works for me, in OpenShot 2.4.4 on Linux.

If you go into the Preferences, in the Keyboard tab, what do you see listed for "Delete Item" and "Delete Item (Alternate 1)"?

**Comment by SuslikV** [comment]
The save file of the project may be broken in some weird way. Is it happens when you create new project and drop new video file into _Timeline_?

**Comment by AndersBillLinden** [comment]
Cannot reproduce any longer. Closing.
