### ISSUE TITLE
Segfault (SIGSEGV) while using arrow keys to run through frames

### ISSUE THREAD

**Issue by pumaking** [OpenShot/openshot-qt#2834]
**Describe the bug:**
I am running Openshot 2.4.4 and it segfaulted (SIGSEGV) while using the arrow keys to move the time head around the timeline.

**Expected behavior:**

No segfault!

**System Details:**
- OpenShot 2.4.4
- Linux 5.1.7 (Arch)

**Exception / Stacktrace:**

<pre>
Caught signal 11 (SIGSEGV)                                                                                                                                               
---- Unhandled Exception: Stack Trace ----                                                                                                                               
  /usr/lib/python3.7/site-packages/_openshot.so (                                           + 0xdce98)  [0x7f2df94                                                       18e98]                                                                                                                                      
  /usr/lib/python3.7/site-packages/_openshot.so (                                           + 0xdda3f)  [0x7f2df94                                                       19a3f]                                                                                                                                      
  /usr/lib/libpython3.7m.so.1.0  ( PyCFunction_Call                          + 0x103 )  [0x7f2e07bccf93]                                                                 
  /usr/lib/libpython3.7m.so.1.0  ( _PyEval_EvalFrameDefault                  + 0x5ed6)  [0x7f2e07c65a36]                                                                 
  /usr/lib/libpython3.7m.so.1.0  ( _PyEval_EvalCodeWithName                  + 0x2f9 )  [0x7f2e07bacd09]                                                                 
  /usr/lib/libpython3.7m.so.1.0  ( _PyFunction_FastCallKeywords              + 0x2b2 )  [0x7f2e07bf3882]                                                                 
  /usr/lib/libpython3.7m.so.1.0  ( _PyEval_EvalFrameDefault                  + 0x4b8a)  [0x7f2e07c646ea]                                                                 
  /usr/lib/libpython3.7m.so.1.0  ( _PyEval_EvalCodeWithName                  + 0x2f9 )  [0x7f2e07bacd09]                                                                 
  /usr/lib/libpython3.7m.so.1.0  ( _PyFunction_FastCallKeywords              + 0x2b2 )  [0x7f2e07bf3882]                                                                 
  /usr/lib/libpython3.7m.so.1.0  ( _PyEval_EvalFrameDefault                  + 0x143c)  [0x7f2e07c60f9c]                                                                 
  /usr/lib/libpython3.7m.so.1.0  ( _PyFunction_FastCallDict                  + 0x11b )  [0x7f2e07baddbb]                                                                 
  /usr/lib/libpython3.7m.so.1.0  ( _PyObject_Call_Prepend                    + 0x68  )  [0x7f2e07bbd818]                                                                 
  /usr/lib/libpython3.7m.so.1.0  ( PyObject_Call                             + 0x6b  )  [0x7f2e07bae49b]                                                                 
  /usr/lib/python3.7/site-packages/PyQt5/sip.so (                                           + 0xadae)  [0x7f2e0629                                                       cdae]                                                                                                                                   
  /usr/lib/python3.7/site-packages/PyQt5/sip.so (                                           + 0xae8f)  [0x7f2e0629                                                       ce8f]
  /usr/lib/python3.7/site-packages/PyQt5/QtWidgets.so (                                           + 0x3aae2d)  [0x7f2e036b6e2d]
  /usr/lib/python3.7/site-packages/PyQt5/QtWidgets.so (                                           + 0x2870cc)  [0x7f2e035930cc]
  /usr/lib/libQt5Widgets.so.5    ( QWidget::event(QEvent*)                   + 0x828 )  [0x7f2e02dd4148]
  /usr/lib/libQt5Widgets.so.5    ( QMainWindow::event(QEvent*)               + 0x65  )  [0x7f2e02ee1405]
  /usr/lib/python3.7/site-packages/PyQt5/QtWidgets.so (                                           + 0x286744)  [0x7f2e03592744]
  /usr/lib/libQt5Widgets.so.5    ( QApplicationPrivate::notify_helper(QObject*, QEvent*)  + 0x84  )  [0x7f2e02d92da4]
  /usr/lib/libQt5Widgets.so.5    ( QApplication::notify(QObject*, QEvent*)   + 0x118c)  [0x7f2e02d9b33c]
  /usr/lib/python3.7/site-packages/PyQt5/QtWidgets.so (                                           + 0x151b3f)  [0x7f2e0345db3f]
  /usr/lib/libQt5Core.so.5       ( QCoreApplication::notifyInternal2(QObject*, QEvent*)  + 0x179 )  [0x7f2e05f98849]
  /usr/lib/libQt5Widgets.so.5    (                                           + 0x1b7cc2)  [0x7f2e02df1cc2]
  /usr/lib/libQt5Widgets.so.5    ( QApplicationPrivate::notify_helper(QObject*, QEvent*)  + 0x84  )  [0x7f2e02d92da4]
  /usr/lib/libQt5Widgets.so.5    ( QApplication::notify(QObject*, QEvent*)   + 0x211 )  [0x7f2e02d9a3c1]
  /usr/lib/python3.7/site-packages/PyQt5/QtWidgets.so (                                           + 0x151b3f)  [0x7f2e0345db3f]
  /usr/lib/libQt5Core.so.5       ( QCoreApplication::notifyInternal2(QObject*, QEvent*)  + 0x179 )  [0x7f2e05f98849]
  /usr/lib/libQt5Gui.so.5        ( QGuiApplicationPrivate::processKeyEvent(QWindowSystemInterfacePrivate::KeyEvent*)  + 0x16d )  [0x7f2e0279a76d]
  /usr/lib/libQt5Gui.so.5        ( QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*)  + 0x116 )  [0x7f2e0279f936]
  /usr/lib/libQt5Gui.so.5        ( QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>)  + 0xbc  )  [0x7f2e02778d9c]
  /usr/lib/libQt5XcbQpa.so.5     (                                           + 0x6db8c)  [0x7f2df3228b8c]
  /usr/lib/libglib-2.0.so.0      ( g_main_context_dispatch                   + 0x2bf )  [0x7f2e054e390f]
  /usr/lib/libglib-2.0.so.0      (                                           + 0x6d869)  [0x7f2e054e5869]
  /usr/lib/libglib-2.0.so.0      ( g_main_context_iteration                  + 0x2e  )  [0x7f2e054e58ae]
  /usr/lib/libQt5Core.so.5       ( QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>)  + 0x69  )  [0x7f2e05fed969]
  /usr/lib/libQt5Core.so.5       ( QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>)  + 0x13c )  [0x7f2e05f974dc]
  /usr/lib/libQt5Core.so.5       ( QCoreApplication::exec()                  + 0x96  )  [0x7f2e05f9f596]
  /usr/lib/python3.7/site-packages/PyQt5/QtWidgets.so (                                           + 0x1505cd)  [0x7f2e0345c5cd]
  /usr/lib/libpython3.7m.so.1.0  ( _PyMethodDef_RawFastCallKeywords          + 0x148 )  [0x7f2e07bf3e68]
  /usr/lib/libpython3.7m.so.1.0  ( _PyCFunction_FastCallKeywords             + 0x21  )  [0x7f2e07bf4101]
  /usr/lib/libpython3.7m.so.1.0  ( _PyEval_EvalFrameDefault                  + 0x51b9)  [0x7f2e07c64d19]
  /usr/lib/libpython3.7m.so.1.0  ( _PyFunction_FastCallKeywords              + 0x10b )  [0x7f2e07bf36db]
  /usr/lib/libpython3.7m.so.1.0  ( _PyEval_EvalFrameDefault                  + 0x4b8a)  [0x7f2e07c646ea]
  /usr/lib/libpython3.7m.so.1.0  ( _PyFunction_FastCallKeywords              + 0x10b )  [0x7f2e07bf36db]
  /usr/lib/libpython3.7m.so.1.0  ( _PyEval_EvalFrameDefault                  + 0x6cd )  [0x7f2e07c6022d]
  /usr/lib/libpython3.7m.so.1.0  ( _PyEval_EvalCodeWithName                  + 0x2f9 )  [0x7f2e07bacd09]
  /usr/lib/libpython3.7m.so.1.0  ( PyEval_EvalCodeEx                         + 0x44  )  [0x7f2e07badc64]
  /usr/lib/libpython3.7m.so.1.0  ( PyEval_EvalCode                           + 0x1c  )  [0x7f2e07badc8c]
  /usr/lib/libpython3.7m.so.1.0  (                                           + 0x237694)  [0x7f2e07cd6694]
  /usr/lib/libpython3.7m.so.1.0  ( PyRun_FileExFlags                         + 0x9e  )  [0x7f2e07cd7b6e]
  /usr/lib/libpython3.7m.so.1.0  ( PyRun_SimpleFileExFlags                   + 0x1b5 )  [0x7f2e07cdb035]
  /usr/lib/libpython3.7m.so.1.0  (                                           + 0x23e2a7)  [0x7f2e07cdd2a7]
  /usr/lib/libpython3.7m.so.1.0  ( _Py_UnixMain                              + 0x3c  )  [0x7f2e07cdd4ec]
  /usr/lib/libc.so.6             ( __libc_start_main                         + 0xf3  )  [0x7f2e07e3ace3]
  /usr/bin/python                ( _start                                    + 0x2e  )  [0x55eecf5e505e]
---- End of Stack Trace ----
</pre>

**Comment by SuslikV** [comment]
Can you test with the file from this post - https://github.com/OpenShot/openshot-qt/issues/2828#issuecomment-500698612 - as well? Just drag the _Timeline_ cursor left and right over the clip. Is it crashes for you?

Also, please add your openshot log files.

**Comment by pumaking** [comment]
I repeated the same steps with the video file you linked but could not reproduce the segfault. The segfault I saw only happened once and I was able to use the arrow keys after restarting.

I've attached my log files.
[openshot-logs.zip](https://github.com/OpenShot/openshot-qt/files/3282493/openshot-logs.zip)

**Comment by SuslikV** [comment]
When I add the mentioned file to _Timeline_ (or just Preview it) and trying to drag _Timeline_ cursor left and right (over not yet cached frames between 0...15 seconds) my build of OpenShot almost constantly crashes in libopenshot.dll (Windows platform), so I was asking about it.

**Comment by mikelacsa** [comment]
@pumaking is this still a problem?

**Comment by pumaking** [comment]
I have no more info, sorry. Have not used OpenShot since this.

**Comment by mikelacsa** [comment]
Understood @pumaking. Thanks for responding.
