### ISSUE TITLE
Text position 

### ISSUE THREAD

**Issue by Ivangabor** [OpenShot/openshot-qt#2835]
Is it possible to put the text on a certain place, with an arrow? 
I should like to  attract attention to an object on the video.

System Details
- OpenShot Version 2.4.1
- Operating System:Linux Ubuntu 18.10

**Comment by SuslikV** [comment]
Just edit the text's svg file that appears at the "assets" folder of the project's folder right after the project save (restart application to be sure that you see modified file). Or just make new file with simple arrow (draw it) in Inkscape for example (svg files has better scaling capabilities) and drag-n-drop saved file into OpenShot.

**Comment by Ivangabor** [comment]
Thank You, Suslik V.

**Comment by DylanC** [comment]
Answered.
