### ISSUE TITLE
Saving to .osp Project files also saves unneeded history to the file

### ISSUE THREAD

**Issue by SuslikV** [OpenShot/openshot-qt#2839]
Saving to _.osp_ project files also saves history, that itself just blows the save file for no reason and doing a lot of unneeded writing operations to disk (harmful for SSD and performance).

**Steps to reproduce the behavior:**
1. Start new project
2. Make few modifications
3. Save your project to _.osp_ file
4. Restart the OpenShot
5. Open your saved in p.3 project file
6. Notice that you can Undo the actions taken under the previous session

**Describe the solution you'd like:**
Do not store history inside the project's file to reduce disk usage, decrease the save file size and thus improve performance of the application.

**Describe alternatives you have considered:**
No workarounds known, because wiping history before file save - makes impossible to make intermediate backups when working with large projects while preserving working history.

---------
And really, did you ever went back in history right after you opened the project file next day?! To some step that you even don't remember...

**Comment by ferdnyc** [comment]
This has been extensively covered in #1923 and the pull requests that grew out of it. (Which sorted out what was, at the time, a rather nasty bug in the project-file history storage that was growing project files to be literal megabytes in size.) 

With that bug fixed, the official edict is that history storage across sessions via the project file is considered a feature, so it is desired functionality. (The size of the undo/redo stack can always be reduced via the Preferences, of course.) `¯\_(ツ)_/¯`

**Comment by SuslikV** [comment]
Wow! Feature... Now I will modify original request for removing this feature completely. Hope, someone will find soon how to make PC crash with special project file. Especially, when users decide to share some templates.

**Comment by ferdnyc** [comment]
> Hope, someone will find soon how to make PC crash with special project file.

Well, any bug that can take the OS down is an OS bug, as far as I'm concerned. User applications shouldn't have the ability to do that no matter what they do.

But the cross-session history stack _was_ crashing OpenShot at one point, when run from AppImage. If any of the history entries happened to reference file paths inside the AppImage mount, attempting to restore them would take it down hard. (That mount changes every run, so paths from previous sessions are invalid.) Not sure if that was ever fixed. I think it was.

My _personal_ opinion is that history rarely has any usefulness beyond the current session, and preserving it between sessions is more trouble than it's worth. But I lost that argument. And I can't really argue that storing it has any negative repercussions. 

With the history storage bug fixed, it's really not a significant impact on the project file size, or on memory consumption (beyond what would be consumed during the session anyway). And the user isn't forced to **use** the history from old sessions. Even that AppImage bug had to be triggered by an attempt to restore a history entry from an old session, so the workaround was simply "don't do that".
