### ISSUE TITLE
Openshot Cloud: What is the path of a file?

### ISSUE THREAD

**Issue by bmfb46680** [OpenShot/openshot-qt#2844]
Hi,

I'm interested in using the Openshot video editor in the cloud. I've read the documentation and watched the video and had a few questions left.

- If I have a .osp (project) file that references the filepaths of the .svg and - if I would be using images in the video - .png or .jpg, how  would that work on the cloud? What would the correct filepath be of a .svg or .jpg file that is uploaded to the cloud?

Many thanks,

Isaac

**Comment by ferdnyc** [comment]
Hey @bmfb46680 , sorry for the delay getting back to you on this.

Exact file paths are set by the API, they're included in the JSON object data that's returned whenever you issue an API command that either uploads a file, or causes the creation of one. You can read [the docs for the `/files/` APIs](http://cloud.openshot.org/doc/api_endpoints.html#files) for specifics.

> API endpoint that manages file objects. These can be images, videos, or audio files. File objects belong to both a project and a clip object. All assets used in your video must be added as file objects before they can be added as clips. Also, multiple clips can refer to a single file object.
> 
> File objects are rich with metadata, and include all kinds of interesting attributes about the file (and its content). Also, you will notice many technical attributes and embedded metadata (camera info, artist/album info, device rotation, etc…).

One example they give is a file-upload request (that allows you to add media files to a Cloud project):

> #### Request Data - Uploading binary file
> 
> ```
> {
>     "media": null,
>     "project": "http://127.0.0.1:8001/projects/36/",
>     "json": { "url": "video/files/36/LOCAL-FILE.MP4", "name": "Custom-Filename.mp4"  }
> }
> 
> ```

The response data includes information on the uploaded media file's format, codecs, and location. (Expand for full response.)

<details>
<summary>Response Data for a video file</summary>

```
{
  "url": "http://cloud.openshot.org/files/721/",
  "id": 721,
  "media": "http://cloud.openshot.org/media/video/files/292/sintel_trailer-720p.mp4",
  "project": "http://cloud.openshot.org/projects/292/",
  "actions": [
      "http://cloud.openshot.org/files/721/thumbnail/"
  ],
  "json": {
      "channel_layout": 3,
      "has_video": true,
      "pixel_ratio": {
          "num": 1,
          "den": 1
      },
      "height": 720,
      "audio_stream_index": 1,
      "vcodec": "h264",
      "top_field_first": true,
      "video_stream_index": 0,
      "file_size": "7610368",
      "media_type": "video",
      "interlaced_frame": false,
      "has_audio": true,
      "path": "/home/ubuntu/api/video/files/292/sintel_trailer-720p.mp4",
      "fps": {
          "num": 24,
          "den": 1
      },
      "duration": 51.9466667175293,
      "audio_bit_rate": 126694,
      "acodec": "aac",
      "type": "FFmpegReader",
      "video_timebase": {
          "num": 1,
          "den": 24
      },
      "sample_rate": 48000,
      "width": 1280,
      "audio_timebase": {
          "num": 1,
          "den": 48000
      },
      "video_bit_rate": 1166138,
      "has_single_image": false,
      "display_ratio": {
          "num": 16,
          "den": 9
      },
      "metadata": {
          "major_brand": "isom",
          "artist": "Durian Open Movie Team",
          "encoder": "Lavf52.62.0",
          "copyright": "(c) copyright Blender Foundation | durian.blender.org",
          "creation_time": "1970-01-01 00:00:00",
          "minor_version": "512",
          "language": "und",
          "handler_name": "SoundHandler",
          "compatible_brands": "isomiso2avc1mp41",
          "title": "Sintel Trailer",
          "description": "Trailer for the Sintel open movie project"
      },
      "video_length": "1253",
      "pixel_format": 0,
      "channels": 2
  },
  "date_created": "2018-02-25T22:03:22.323107Z",
  "date_updated": "2018-02-25T22:03:22.589635Z"
}
```
</details>

**Comment by ferdnyc** [comment]
I'll leave this issue open in case you have further questions. Please feel free to close it, though, if you've got everything you need for the moment.

**Comment by jonoomph** [comment]
@bmfb46680 You can also send questions to cloud-support@openshot.org for help with our Cloud API. In general though, if you use the /projects/<ID>/load/ endpoint, you can upload a .zip file that contains all your project's content in a single directory (including the *.osp project file, svg titles, and any media files used). Just zip up those things, and send it to the /load/ endpoint, and everything all paths should work great.

**Comment by ferdnyc** [comment]
Oh, I forgot to mention that you can go to http://cloud.openshot.org/ and login as `demo-cloud` with the password `demo-password`, to experiment with the API yourself. Any data created/submitted is deleted after 12 hours, but it'll let you get a feel for the API.

**Comment by bmfb46680** [comment]
Many thanks for all the help! I've been enjoying your videos Jonathan, very helpful!

I'll be checking out the demo, pretty neat that I can test it all out that way.
