### ISSUE TITLE
Video Corrupted with flickering green

### ISSUE THREAD

**Issue by ghostslayer989** [OpenShot/openshot-qt#2845]
**Describe the bug:**
Corrupted exported video with a green bar at the bottom half. Audio is fine.
Closed post from different user [https://github.com/OpenShot/openshot-qt/issues/2238](https://github.com/OpenShot/openshot-qt/issues/2238)

**Steps to reproduce the behavior:**
1. Have a 18 min long video (I do atleast)
2. Export in 1920x1080 60fps - High Quality
3. Watch video process have a green box.

**Expected behavior:**
I expected my video to be perfectly normal with no green-box and could be viewed without seeing corrupted frames.

**System Details:**
- OpenShot Version 2.4.4
- Operating System / Distro: Windows 10 x64 Pro.

**Screenshots:** (Optional)
![image](https://user-images.githubusercontent.com/45863583/60398463-665dda00-9b26-11e9-8f5d-62e5538270fa.png)
Video Profile.

![image](https://user-images.githubusercontent.com/45863583/60398450-36163b80-9b26-11e9-9a99-36d1051b26b9.png) My corrupted video.

**Comment by SuslikV** [comment]
Try, at least, MP4 (h.264) output format. Any changes? Can you try VLC Player as well to playback your recently exported video?

**Comment by ghostslayer989** [comment]
Thanks @SuslikV
