### ISSUE TITLE
Can't open project/stuck in loop, when item is missing

### ISSUE THREAD

**Issue by chickendick** [OpenShot/openshot-qt#2847]
I am trying to open a project, and one of the video clips used in the project has been intentionally deleted from my computer. However I still want to open the project even though that item is unavailable.
On startup, I get a message asking me to find this item. If I click cancel, it won't let me progress, and I get stuck in a loop of being asked to find the item.
I have to close the whole program from task manager.

**Comment by SuslikV** [comment]
You stopped too early. Just hold _Esc_ button for a while...

**Comment by speedytechdev** [comment]
@chickendick Did @SuslikV Answer help or is it still an issue?

**Comment by ferdnyc** [comment]
This was fixed in commit bdd21358 which will be included in the next release of OpenShot. Once you select the directory where your disconnected file can be found, all files in that directory will be recovered automatically.
