### ISSUE TITLE
Effect don't do anything

### ISSUE THREAD

**Issue by trialism** [OpenShot/openshot-qt#2848]
I added a video to a lane, started the preview and then clicked on every effect but nothing happened. Tried to drag - still nothing. I'm on the latest manjaro.

**Comment by ferdnyc** [comment]
@trialism Here's a link to the [OpenShot User Guide section on Effects](https://cdn.openshot.org/static/files/user-guide/clips.html#effects). Admittedly, it's more of a "paragraph" than a "section", and could really stand to be fleshed out better, but the basic information on how to use effects is there:

> In addition to the many clip properties which can be animated and adjusted, you can also drop an effect directly onto a clip. Each effect is represented by a small letter icon. Clicking the effect icon will populate the properties of that effect, and allow you to edit (and animate) them.
>
> ![](https://cdn.openshot.org/static/files/user-guide/_images/clip-effects.jpg)

(In the example screenshot, the "clouds.jpg" clip has two effects applied: <b>(N)</b>egative, represented by a letter N in an orange circle, and <b>(B)</b>rightness & Contrast, represented by a letter B in a purple circle.)

**Comment by ferdnyc** [comment]
Closing as hopefully answered, let us know if you have any further issues.
