### ISSUE TITLE
When a crash happens there is never enough RAM to send a report

### ISSUE THREAD

**Issue by not83** [OpenShot/openshot-qt#285]
When a crash happens there is never enough RAM to send a report however I had over 4 gigs worth of RAM available. What gives?

Ubuntu 14.04 
660Ti nvidia
8 gigs of ram
version: OpenShot version 2.0.7
i5-4570

**Comment by jreynojustin** [comment]
OpenShot is now in Version 2.2 if you are still noticing issues in the latest version please re-open this issue letting us know.
