### ISSUE TITLE
Pressing Export Does Nothing (Workaround Included)

### ISSUE THREAD

**Issue by dadkins1** [OpenShot/openshot-qt#2850]
**Describe the bug:**
When I press Export on the toolbar (or use the menu or keyboard shortcut), Openshot doesn't open the Export dialog. The program behaves normally afterward, as though I had canceled the dialog (i.e.: it doesn't crash or hang).

**Steps to reproduce the behavior:**
1. Open Openshot
2. Click on 'Export'
3. Nothing happens...it's as though the button isn't connected to anything

**Expected behavior:**
I expected to see the Export dialog appear.

**System Details:**
- OpenShot Version [2.4.4]
- Operating System / Distro: Windows 10

**Log Files:**
I went through the log and found this exceptional message :)
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "C:\Program Files\OpenShot Video Editor\windows\main_window.py", line 690, in actionExportVideo_trigger
    win = Export()
  File "C:\Program Files\OpenShot Video Editor\windows\export.py", line 143, in __init__
    if os.path.exists(export_path):
  File "C:\msys64\mingw64\lib\python3.6\genericpath.py", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Exception / Stacktrace:**
See above -- my "export_path" project setting was somehow set to null. I was able to work around the problem by replacing null with a valid path, e.g.: "C:\\path\\to\\videos". I would expect the __init__ routine to be able to handle the case where export_path is None.

**Comment by ferdnyc** [comment]
> I would expect the **init** routine to be able to handle the case where export_path is None.

I would've expected `os.path.exists()` to be able to handle it, but clearly not as you demonstrated. I've submitted a pull request to fix this, thanks for the detailed report!

**Comment by dadkins1** [comment]
Yes, I was quite surprised seeing that Python didn’t like it. Thanks for the fix!
