### ISSUE TITLE
Better caching

### ISSUE THREAD

**Issue by ghost** [OpenShot/openshot-qt#2852]
**Describe the new feature:**
I see there's a caching featuring with the program, but I've noticed some flaws with it. Editing a 1.72GB file with 16GB of memory allocated to openshot for caching doesn't cache the whole file, or even a third. It uses (somehow) 19.5GB of memory on ~3 minutes of footage. I would also like to see a persistent cache option, where it only drops the entire cache when the project is closed. I've had a few instances where it just drops the cache for no reason.

**Screenshots:**
In the example below I show how a small portion of a 1.72GB file is using 19.5GB of memory. That doesn't make much sense to me, a better caching system would be really nice. 
![cachething](https://user-images.githubusercontent.com/11285986/60731339-5292e900-9f15-11e9-8ce2-2200166083e8.png)

**Comment by SuslikV** [comment]
Items in the cache stored uncompressed, so single RGBA frame at 1920x1080 8 bit per channel (+ alpha) requires 1920x1080x4x8=66355200 bit or about 8 MB. At 30 fps it about 237 MB per 1 second of footage. In 16 GB of RAM you can store about 69 sec of it. For 1280x720 footage, size - 16 GB can store about 155 sec video clip (with alpha, or 207 sec without). And this is without audio...

In other words - there is nothing to improve.

**Comment by diamondpumpkin** [comment]
> Items in the cache stored uncompressed, so single RGBA frame at 1920x1080 8 bit per channel (+ alpha) requires 1920x1080x4x8=66355200 bit or about 8 MB. At 30 fps it is about 237 MB per 1 second of the footage. In 16 GB of RAM you can store about 69 sec of it. For 1280x720 footage, size - 16 GB can store about 155 sec of video with alpha (or 207 sec without). And this is without audio...
> 
> In other words - there is nothing to improve.

That makes a bit more sense, what about the cache randomly dropping? It's a bit annoying when it drops out of no where and it has to recache what I was working on. Also, I've noticed when zooming in and out on the timeline, the blue line indicating the cached parts disappears.

**Comment by SuslikV** [comment]
Zooming - is another bug (the ruler should blank too) - try other scale (15 seconds or more of _Timeline_, https://github.com/OpenShot/openshot-qt/issues/2814), and I don't think that the cache flushes in this case. Other cases is not documented well. Can you provide exact steps to reproduce the cache drop?

**Comment by diamondpumpkin** [comment]
> Zooming - is another bug (the ruler should blank too) - try other scale (15 seconds or more of _Timeline_, #2814), and I don't think that the cache flushes in this case. Other cases is not documented well. Can you provide exact steps to reproduce the cache drop?

It appears slicing any cached parts will drop a good portion if not all of the cache. This happens even if you keep both sides.

**Comment by SuslikV** [comment]
It will be hard to solve - the cache keeps only composed data, not sources.

**Comment by diamondpumpkin** [comment]
> It will be hard to solve - the cache keeps only composed data, not sources.

Yeah I figured as much.

**Comment by Jonas-July** [comment]
With regards to this, the cache only seems to contain the frames for the preview, so a smaller preview (like 848x477 vs 1920x1080) will lead to more frames in the cache.

This might mean that areas of the timeline that haven't recently changed, but are often accessed (as they might be finished for example) could be cached as compressed frames (with minimal visual loss) while the active area caches them raw.
After all, if I export to MP4, then my preview might as well be MP4.
Of course, this should still be an option. Maybe an on/off button below the preview

But to be honest, I don't think that I understood how the caching here works. I've looked at the source for CacheMemory and related classes, and tried learning by doing, but the blue bar above the tracks (which I think signifies the presence of a cached frame) doesn't exactly match the cache.
If there is some non-code documentation on the cache that I missed, I'd be glad if I get a pointer to it.

The cache can still be improved, even with above limitations.
