### ISSUE TITLE
OpenShot crashing on project load

### ISSUE THREAD

**Issue by CluckCluckChicken** [OpenShot/openshot-qt#2854]
I open my project, and OpenShot instantly crashes.
The log is in the files below.
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/3368987/openshot-qt.log)

**Comment by SuslikV** [comment]
Can you share the project's file too?

**Comment by CluckCluckChicken** [comment]
[Trailer.zip](https://github.com/OpenShot/openshot-qt/files/3373861/Trailer.zip)

**Comment by SuslikV** [comment]
The effects of OpenShot doesn't know about `"reader"` effect that starts at line `20726` of your project file.

Try this repaired file instead:
about 18 KB to download, CRC of the zip archive MD5:47242A7C09F54CECDCFC01081DAAEB10
[Trailer-repaired3.zip](https://github.com/OpenShot/openshot-qt/files/3374061/Trailer-repaired3.zip)

**Comment by CluckCluckChicken** [comment]
thanks
