### ISSUE TITLE
Duplicating and editing a title

### ISSUE THREAD

**Issue by bmfb46680** [OpenShot/openshot-qt#2857]
Tried it 10 times, now it's working for some reason. Never mind, I'm sorry for opening this too early.

**Comment by ferdnyc** [comment]
@bmfb46680 Not to worry, glad you got it sorted out. If the problem comes up again please do open up a new issue with any details you can provide about how/why. If there's a bug that comes up sometimes with title editing, we'd definitely like to track it down.

**Comment by bmfb46680** [comment]
Ok Ferdnyc, I will do that.

I have a question and I don't want to open a new thread for it. How secure and private is OpenShot when I would use it in the cloud. Can Jonathan see whatever I'm editing, activity, source files or other info when I pay for it (I thought it was something like $0,15 per hour or so).

Let me know what is and what is not tracked. By the way, I'm not talking about the demo, but about the real cloud API.

Many thanks!

**Comment by ferdnyc** [comment]
Honestly, I don't know the answer to that, and I _would_ open a new issue since it's a perfectly valid, but unrelated, question.

It's worth using the question template (again), tagging @jonoomph in the new issue, and even emailing him at jonathan@openshot.org if you don't get a timely response.

**Comment by bmfb46680** [comment]
Alright, I'll do that. Thanks for the message!

**Comment by ferdnyc** [comment]
@bmfb46680 Out of curiosity, does either #1867 or #2069 sound anything like the issue you were having with title editing?
