### ISSUE TITLE
How secure and private is the OpenShot Cloud API?

### ISSUE THREAD

**Issue by bmfb46680** [OpenShot/openshot-qt#2859]
How secure and private is OpenShot when I would use it in the cloud. Can Jonathan see whatever I'm editing, activity, source files, exports or other info when I pay for it? (I thought it was something like $0,15 per hour or so).

Let me know what is and what is not tracked. By the way, I'm not talking about the demo, but about the real cloud API. But I would like to know it about the demo as well. @jonoomph

**Comment by jonoomph** [comment]
@bmfb46680 The OpenShot Cloud API runs on your own AWS instances, and is thus, secured with your own private keys. The only information I receive is billing-based, and that is anonymized through Amazon AWS. So, in all truth, I can only see that "someone" has used X hours of OpenShot Cloud API at a cost of $0.15 USD / hour. The rest is between you and Amazon AWS. Hope that answers the question.

**Comment by bmfb46680** [comment]
Hi Jonathan,

Thanks for the info! That clears it all up.

**Comment by ferdnyc** [comment]
I'm going to add a "Cloud" tag for these questions / issues / etc. — anything related, basically — so that they're easier to track down and reference in the future.
