### ISSUE TITLE
OpenShot Cloud API (Demo): 1 succesful export, 1 failed

### ISSUE THREAD

**Issue by bmfb46680** [OpenShot/openshot-qt#2861]
Today I finally tested the OpenShot Cloud API.
I uploaded as Jonathan said all my project files (.ose, svg, ..) in a zip to the id/load/ section.
In that zip file, I had 2 projects (.ose files) with all related files such as images and text.

I went to export and successfully created my first cloud-rendered video!

However, I didn't see the 2nd video that I also added in the zip file. There was only 1 project that I could export, so perhaps it sees the 2 videos as 1 project, I don't know. It DID provided me with 2 links to my videos, 1 was live, the other one was an empty player.

Here's the response in the Cloud API:
 "url": "http://cloud.openshot.org/exports/1076/",
            "id": 1076,
            "output": "http://cloud.openshot.org/media/video/output/nameeditedoutforgithub1.mp4",
            "export_type": "video",
            "video_format": "mp4",
            "video_codec": "libx264",
            "video_bitrate": 8000000,
            "audio_codec": "libfdk_aac",
            "audio_bitrate": 1920000,
            "start_frame": 1,
            "end_frame": 1500,
            "actions": [
                "http://cloud.openshot.org/exports/1076/retry/"
            ],
            "project": "http://cloud.openshot.org/projects/1547/",
            "webhook": "",
            **"json": {
                "error": "Pending export never picked up by worker (cron terminated)"
            },
            "progress": 100.0,
            "status": "failed",**
            "date_created": "2019-07-10T09:48:45.692758Z",
            "date_updated": "2019-07-10T10:45:01.434708Z"
        },
        {
            "url": "http://cloud.openshot.org/exports/1077/",
            "id": 1077,
            "output": "http://cloud.openshot.org/media/video/output/nameeditedoutforgithub2.mp4",
            "export_type": "video",
            "video_format": "mp4",
            "video_codec": "libx264",
            "video_bitrate": 8000000,
            "audio_codec": "libfdk_aac",
            "audio_bitrate": 1920000,
            "start_frame": 1,
            "end_frame": 121,
            "actions": [
                "http://cloud.openshot.org/exports/1077/retry/"
            ],
            "project": "http://cloud.openshot.org/projects/1547/",
            "webhook": "",
            "json": {
                "hostname": "ip-172-30-0-111"
            },
            "progress": 100.0,
            "status": "completed",
            "date_created": "2019-07-10T20:56:07.530761Z",
            "date_updated": "2019-07-10T20:56:11.824158Z"
        }

Am I using the API wrong? Do I need to create 1 zip per video? How can I solve this?

Many thanks!

**Comment by jonoomph** [comment]
@bmfb46680 Please send an email to cloud-support@openshot.org for help with our Cloud API. GitHub is not currently used to track issues with our Cloud API. This GitHub repo is only used for OpenShot Video Editor, our desktop video editor. The /projects/ID/load/ endpoint is only designed to load a single project. You can, however, easily create a /projects/ID/ for each project, and then load a different zip for each one. Or, if they share most of the same files, you can use a /projects/ID/copy/ endpoint to duplicate a project on the Cloud API. Hope that helps. And feel free to send future issues to cloud-support@openshot.org. Thanks!

**Comment by bmfb46680** [comment]
Ok I'll send a message via e-mail!
