### ISSUE TITLE
How to add a button into the menu?

### ISSUE THREAD

**Issue by cminghao** [OpenShot/openshot-qt#2876]
Hi, kind of new to all these, took me awhile to get openshot up and running and now I would like to be able to make changes to it, but I'm already stuck on the first step, I can't remove buttons from the menu, such as the Quit button but when I try to add a new button the program will not even start up or if I try to add a second Quit button it does not show up.

ah, found the solution, just had insert a few things into the codes!

**Comment by ferdnyc** [comment]
Glad to hear you sorted it out, I was just starting to write a response. In the future, if you have questions about issues you're having it would be helpful if you can provide more information about exactly what you did, and what the results of those actions were.

(By which I mean, it's the details that truly matter. There are probably dozens of different ways to modify the OpenShot interface. As you've seen, some work, some don't. So _exactly_ how you attempted to do what you were trying to do is critical information. Did you use QT Creator? Edit th .ui files directly? Edit the Python code? Etc...)

And when OpenShot "will not even start up", there's _usually_ some message output that explains why, whether it's a Windows crash message, or an error in the `%USERPROFILEDIR%/.openshot_qt/openshot-qt.log` file... _something_. Having information on **how** it failed to function helps us figure out the why.

Just saying, it's one of those "Help us help you!" things. :grin:
