### ISSUE TITLE
OpenShot 2.1, Windows & Multi-Threading

### ISSUE THREAD

**Issue by nwgat** [OpenShot/openshot-qt#288]
OpenShot 2.1 on my 8-core FX-8350 system uses only 25-30% , which is a far cry from 99%

the virtual c++ error is still there but only when you drag the seek marker not when you click to the spot you want to cut

the 3-4 visual c++ errors from timeline seem to be gone

so there is a bottleneck somewhere in the treading application

**Comment by jreynojustin** [comment]
OpenShot is now in Version 2.2 if you are still noticing issues in the latest version please re-open this issue letting us know.
