### ISSUE TITLE
Disabled video isn't really disabled unless Scale is set to "None"

### ISSUE THREAD

**Issue by ferdnyc** [OpenShot/openshot-qt#2882]
While working through some of the older open issues, I came across a feature request for a way to disable video for clips on the timeline and though, "Well... we already have that, don't we?"

It turns out we **_do_**, but there's a bit of a bug in that when I disabled the video on the top clip of two that I had on different tracks of the Timeline, I ended up with this:

![image](https://user-images.githubusercontent.com/538020/61589583-1ea4fe00-ab7a-11e9-879a-e1d3f960ebab.png)

...The workaround there was to **also** set the scaling to "None", at which point the black rectangle disappeared and I was able to see the bottom clip without any interference from the video-disabled upper one.

Now, obviously _disabling_ a clip's video entirely should override all other processing of the clip's video content, so the fact that scaling is even being performed in any mode appears to be a sign that an enable check is missing from some of the video processing code. This may well prove to be a libopenshot bug, but I'm filing it here for now as it can always be transferred later.

_Created (with significant editing) from a comment originally posted by @ferdnyc in https://github.com/OpenShot/openshot-qt/issues/1260#issuecomment-513539243_

**Comment by NecroWizard666** [comment]
@ferdnyc your workaround doesn't fix my issue. I'm using an image overlay on a video track. Switching the scale to "None" on the image clip doesn't make the black center go away ("Enable Video" is set to "-1", setting it to "0" makes the image entirely black).

This issue only started happening after I tried to export my project to another drive, manually reconnecting the project files.
![Screenshot from 2019-09-16 16-17-13](https://user-images.githubusercontent.com/55415486/64999669-812a2a00-d89d-11e9-8a70-c66cefd46536.png)

**Comment by ferdnyc** [comment]
@NecroWizard666 Apologies that it took so long to respond to this.

> @ferdnyc your workaround doesn't fix my issue. I'm using an image overlay on a video track. Switching the scale to "None" on the image clip doesn't make the black center go away ("Enable Video" is set to "-1", setting it to "0" makes the image entirely black).

From what you describe there, the black square _isn't_ that image clip — it's another clip _covering_ the image clip. That's why, when you enable video for the image clip, you can see it covered by the black square, and when you disable its video (the image clip's), the frame is entirely black — the black square is still there, but covering nothing because it's the _only_ thing still there.

Any clip that displays correct video (including image clips) doesn't need to be set `Scale=None` (unless that's how you want it to be sized/displayed), and if you're seeing any _part_ of a clip's content, then _that_ clip is displaying properly.

Black squares covering part of an image are always the result of a _different_ clip (which should be invisible) covering the image — they're never an issue with the clip that you **can** see.

> Some clips stay solid black, others (like the one in the screenshot) flicker with the black center.
> 
> This issue only started happening after I tried to export my project to another drive, manually reconnecting the project files.

Looking at your screenshot, I'm afraid that reconnection process clearly wasn't successful, because the first thing that jumps out at me is that your project has **NO** Project Files. That's not a workable situation for OpenShot to run in, and the first step to fixing the issues with that project would be to reimport all of the media files the project is supposed to be using, then reassembling them onto the timeline. Or, preferably, restoring the project file to an earlier sate from a backup or older copy and re-attempting the recovery process.

But the project in its current state is not workable and I wouldn't recommend continuing to put more time into it without first repairing the missing-media issue.

**Comment by NecroWizard666** [comment]
@ferdnyc I will attempt to try again on the media, it's funny that the last update made it seem like they had solved the portability issue with projects, because so far it's been a bear to move the project to another drive. Your workaround did fix my issue, I didn't realize that after a whole bunch of messing around, that I was adjusting the scale on the top layer of a stack of clips on the track. After deleting the duplicates, setting the scale to "none" on the clip fixed the black center.

**Comment by ferdnyc** [comment]
@NecroWizard666 Yeah, I would describe the situation in 2.4.4 as "improved" rather than "solved". 

Things are definitely better, in that there's now a tool to rediscover media files — though it breaks on Image Sequences, turns out — and when that's used it will prevent the same file being detected as missing for each individual clip that uses it, which is what led to user reports of getting stuck in an "infinite loop" of missing-file dialogs.

(It wasn't infinite, ever, under any circumstances. But it _was_ repeated for each clip that made use of a missing file, which meant getting the same dialog box over and over again, potentially **dozens** of times for a project like yours.)

The new reconnection logic will find all missing files in the same directory, after you locate the first one manually. Which is definitely an improvement.

My PR #2976 hopes to improve the situation more. However, it's not quite ready to merge yet, since @jonoomph pointed out that it breaks undo/redo for saved project files.

(An unconscious bias. I've made no secret of the fact that I think saving undo history across sessions is a _bad_ feature, causing way too many problems for far too little benefit. But regardless what I think of it, history-persistence **is** an existing feature, just one I often fail to account for in my code and testing.)

So I still need to address that problem, to complete the work on #2976.
