### ISSUE TITLE
Crash when slicing a track with Show Waveform enabled.

### ISSUE THREAD

**Issue by firew4lker** [OpenShot/openshot-qt#289]
If the Show Waveform is enabled for a track and you try to slice it, Opeshot will crash with:

timeline_webview:INFO Generate left splice waveform for clip id: 3WXNT9E102
Unhandled Python exception
Aborted (core dumped)

It happens every time.

Latest bzr version Openshot on Archlinux 32-bit.

**Comment by firew4lker** [comment]
PID: 19976 (python3)
UID: 1000 (koko)
GID: 100 (users)
**Signal: 6 (ABRT)**
Timestamp: Tue 2016-08-30 18:03:51 EEST (1min 33s ago)
Command Line: python3 ./launch.py
Executable: /usr/bin/python3.5
Control Group: /user.slice/user-1000.slice/session-c2.scope
Unit: session-c2.scope
Slice: user-1000.slice
Session: c2
Owner UID: 1000 (koko)
Boot ID: 
Machine ID: 
Hostname: lala
Coredump: /var/lib/systemd/coredump/core.python3..lz4
Message: Process 19976 (python3) of user 1000 dumped core.
                
Stack trace of thread 19976:
 #0  0x00000000b777bd41 __kernel_vsyscall (linux-gate.so.1)
                #1  0x00000000b7287e70 raise (libc.so.6)
                #2  0x00000000b7289397 abort (libc.so.6)
                #3  0x00000000b548fdb3 _ZNK14QMessageLogger5fatalEPKcz (libQt5Core.so.5)
                #4  0x00000000b2c6e913 n/a (QtCore.so)
                #5  0x00000000b2c6507d n/a (QtCore.so)
                #6  0x00000000b2c65bbe n/a (QtCore.so)
                #7  0x00000000b56a8cf0 _ZN11QMetaObject8activateEP7QObjectiiPPv (libQt5Core.so.5)
                #8  0x00000000b56a93fd _ZN11QMetaObject8activateEP7QObjectPKS_iPPv (libQt5Core.so.5)
                #9  0x00000000b5f43f49 _ZN7QAction9triggeredEb (libQt5Widgets.so.5)
                #10 0x00000000b5f46c21 _ZN7QAction8activateENS_11ActionEventE (libQt5Widgets.so.5)
                #11 0x00000000b60d1020 n/a (libQt5Widgets.so.5)
                #12 0x00000000b60d785a n/a (libQt5Widgets.so.5)
                #13 0x00000000b60dbfc8 _ZN5QMenu17mouseReleaseEventEP11QMouseEvent (libQt5Widgets.so.5)
                #14 0x00000000b689bb42 n/a (QtWidgets.so)
                #15 0x00000000b5f9841a _ZN7QWidget5eventEP6QEvent (libQt5Widgets.so.5)
                #16 0x00000000b60dcb3a _ZN5QMenu5eventEP6QEvent (libQt5Widgets.so.5)
                #17 0x00000000b689a5da n/a (QtWidgets.so)
                #18 0x00000000b5f4b20a _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
                #19 0x00000000b5f53f5a _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
                #20 0x00000000b66f07a3 n/a (QtWidgets.so)
                #21 0x00000000b567b17d _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
                #22 0x00000000b5f5257d _ZN19QApplicationPrivate14sendMouseEventEP7QWidgetP11QMouseEventS1_S1_PS1_R8QPointerIS0
                #23 0x00000000b5fb5b0f n/a (libQt5Widgets.so.5)
                #24 0x00000000b5fb832a n/a (libQt5Widgets.so.5)
                #25 0x00000000b5f4b20a _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
                #26 0x00000000b5f5309c _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
                #27 0x00000000b66f07a3 n/a (QtWidgets.so)
                #28 0x00000000b567b17d _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
                #29 0x00000000b59c1658 _ZN22QGuiApplicationPrivate17processMouseEventEPN29QWindowSystemInterfacePrivate10Mouse
                #30 0x00000000b59c3409 _ZN22QGuiApplicationPrivate24processWindowSystemEventEPN29QWindowSystemInterfacePrivate
                #31 0x00000000b599df8c _ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEvent
                #32 0x00000000a2f3aa4e n/a (libQt5XcbQpa.so.5)
                #33 0x00000000b4ba8b69 g_main_context_dispatch (libglib-2.0.so.0)
                #34 0x00000000b4ba8e09 n/a (libglib-2.0.so.0)
                #35 0x00000000b4ba8ed4 g_main_context_iteration (libglib-2.0.so.0)
                #36 0x00000000b56d47f3 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (li
                #37 0x00000000a2f3ac21 n/a (libQt5XcbQpa.so.5)
                #38 0x00000000b567923d _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                #39 0x00000000b568218f _ZN16QCoreApplication4execEv (libQt5Core.so.5)
                #40 0x00000000b59b84c1 _ZN15QGuiApplication4execEv (libQt5Gui.so.5)
                #41 0x00000000b5f4b164 _ZN12QApplication4execEv (libQt5Widgets.so.5)
                #42 0x00000000b66eeff9 n/a (QtWidgets.so)
                #43 0x00000000b74b857a PyCFunction_Call (libpython3.5m.so.1.0)
                #44 0x00000000b753239c PyEval_EvalFrameEx (libpython3.5m.so.1.0)
                #45 0x00000000b753147b PyEval_EvalFrameEx (libpython3.5m.so.1.0)
                #46 0x00000000b753147b PyEval_EvalFrameEx (libpython3.5m.so.1.0)
                #47 0x00000000b7533347 n/a (libpython3.5m.so.1.0)
                #48 0x00000000b75334b0 PyEval_EvalCode (libpython3.5m.so.1.0)
                #49 0x00000000b755329b n/a (libpython3.5m.so.1.0)
                #50 0x00000000b75559d3 PyRun_FileExFlags (libpython3.5m.so.1.0)
                #51 0x00000000b7555b63 PyRun_SimpleFileExFlags (libpython3.5m.so.1.0)
                #52 0x00000000b7555fb7 PyRun_AnyFileExFlags (libpython3.5m.so.1.0)
                #53 0x00000000b756da8e Py_Main (libpython3.5m.so.1.0)
                #54 0x0000000008048896 main (python3.5)
                #55 0x00000000b7274196 __libc_start_main (libc.so.6)
                #56 0x0000000008048938 _start (python3.5)

**Comment by jreynojustin** [comment]
@firew4lker I see that you've been spamming references to your issues in other non-related issues. Please in future issues do not go referencing your issue in others that are not related to the one you have reported. It is spam and I am closing this issue because of it.

We will get to issues as we deem their priority.

**Comment by firew4lker** [comment]
@jreynojustin Your are being stupid. You ought to  read messages and bugs carefully. The hastag (#) followed by a number is the way a stack trace is produced by the debugger.

**Comment by jreynojustin** [comment]
@firew4lker,

You should have formatted your post correctly as a code snippet or gist knowing the hashtag symbol referenced other issues.

Anyway, your issue was dated and had to have been from an older version of OpenShot which is also grounds to closing an issue.

Are you still having the issue in the latest build of V2.2?

**Comment by ankitpati** [comment]
@jreynojustin Collaborators can reformat comments. We should try that before contacting the issue reporters. I just reformatted the comment to remove the `#` tags.

@firew4lker Can you please verify if the issue persists in the latest stable [release](http://github.com/OpenShot/openshot-qt/releases/download/v2.2.0/OpenShot-v2.2.0-x86_64.AppImage "OpenShot 2.2")?

**Comment by firew4lker** [comment]
No the problem is NOT present now.  But there is another (related?) bug. #518
