### ISSUE TITLE
Blender 2.80 doesn't work with OpenShot 2.4.4

### ISSUE THREAD

**Issue by nanohtpc** [OpenShot/openshot-qt#2901]
win10 x64 :

test with last stable / last daily

blender 2.80 released today...

**Comment by ferdnyc** [comment]
Thanks. Logs would be helpful (as they'll contain the output from Blender telling us _why_ it isn't working), but otherwise I'll test this out myself and see what the problem is. Will have to wait until the weekend, though, I have another project I'm working on this week.

**Comment by nanohtpc** [comment]
downgrading then...

**Comment by ferdnyc** [comment]
Unpinning as finally put behind us.
