### ISSUE TITLE
Grayed-out dropbox selectors don't look quite grayed-out enough

### ISSUE THREAD

**Issue by ferdnyc** [OpenShot/openshot-qt#2907]
**Describe the bug:**
I feel like the two "...Graphics Card" selectors (which are both disabled) should _look_ WAY more disabled than they actually do. I think we're doing something wrong with how we style and/or deactivate those. They totally _look_ like I should be able to click on them.

![Screenshot from 2019-07-31 01-41-55](https://user-images.githubusercontent.com/538020/62187463-6fb1b080-b337-11e9-87ac-71f0107b68f7.png)

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 2.4.4-dev2
- Operating System / Distro: Windows 7

**Comment by ferdnyc** [comment]
Come to think of it, same thing is true on Linux. This is a screenshot I took of the completed Export window, for a different purpose... but, all of these controls are _disabled_. Not that you could tell.

![Screenshot from 2019-07-21 00-46-13](https://user-images.githubusercontent.com/538020/62188507-a937eb00-b33a-11e9-8f4f-0fc0102c9570.png)

**Comment by SuslikV** [comment]
List can be changed - items removed.

**Comment by ferdnyc** [comment]
Sure, that's a reasonable solution to a minor styling issue.

**Comment by SuslikV** [comment]
It is used in OBS Studio (user didn't see the encoders in the encoder selection that is not available to him, and falls back to "software" when PC config changes and encoder that was in use is no longer available).

**Comment by ferdnyc** [comment]
This issue is about the visual appearance of disabled interface elements. It has **nothing** to do with encoder configuration. Those selectors were merely one _example_ of the issue.

(For a much more extensive demonstration of the issue, see the _entire_ Export dialog in the second screenshot. We certainly can't remove all of the widgets while it's exporting, nor would we want to. We simply want to disable them.)

**Comment by SuslikV** [comment]
Hm, it is not about object delete. I only said about removing from UI ("invisible").

**Comment by ferdnyc** [comment]
The issue is fixed in #2916.
