### ISSUE TITLE
impossible to load a project

### ISSUE THREAD

**Issue by webersauer** [OpenShot/openshot-qt#2912]
I saved a project and when I tried to load again to work in the project it didn´t open. It gives the error message:" invalid load key '\x0d'" Is there something that can be done to open this projext again?

**Comment by ferdnyc** [comment]
@webersauer Almost certainly, yes. Best thing would be if you post your OpenShot version / where you installed it from, the OS you're running it on, and a copy of the project file that won't load. (From GitHub's web interface, you can upload it as a comment attachment right on this issue. Just place the `.osp` inside a `.zip` file, that's one of the supported attachment file formats.)

**Comment by SuslikV** [comment]
99% chance that your project was overwritten by internal error of the application and it's no longer recoverable. Please, make backups of the projects you are working on.

**Comment by ferdnyc** [comment]
Yes, very helpful thank you. #troll

**Comment by SuslikV** [comment]
@ferdnyc you didn't provided a solution. User was left with the broken project and it is unknown when the issue will rise again (no matter what causes it - PC malfunction, software error or user action). Many users just ignore the questions to provide additional info or data on the problem (my own experience).

**Comment by ferdnyc** [comment]
> you didn't provided a solution.

"Post your file, we'll take a look at it and can almost definitely fix it" is a perfectly valid solution. #troll

> Many users just ignore the questions to provide additional info or data on the problem (my own experience).

Then those users don't get helped! But for users who _want_ to get help, and do respond to our attempts to assist them, recovering a project file in this state should be a trivial matter. I've done it multiple times. In fact, I've yet to ever see a project file I _couldn't_ make loadable again.

How exactly does "your project was overwritten by internal error of the application and it's no longer recoverable" provide a solution? It's both _**false**_ AND unhelpful.

**Comment by SuslikV** [comment]
The number of mails the user will receive is key point here. And I edit my original post again (bold letters now).

**Comment by mikelacsa** [comment]
_The user did not respond after 7 days of the issue getting labeled "needs info". Closing this issue now._
