### ISSUE TITLE
constant launch.exe crashes when simply working with an audio file.

### ISSUE THREAD

**Issue by madLyfe** [OpenShot/openshot-qt#292]
no idea why this keeps happening. im not doing anything advanced, just slicing and moving the audio clip around on the timeline.
![vswza4e](https://cloud.githubusercontent.com/assets/16073360/18105112/d9ecc1c6-6ec3-11e6-96a9-283f34b8c516.png)

**Comment by Cybertoad** [comment]
Same issue, trying to copy a log but not sure where it is located. Did you ever get a response to your problem here ?

**Comment by madLyfe** [comment]
> Same issue, trying to copy a log but not sure where it is located. Did you ever get a response to your problem here ?
no not yet.

**Comment by DylanC** [comment]
@madLyfe - What version of OpenShot did you test? Does this issue still occur in version 2.3.4?

**Comment by DylanC** [comment]
Closing due to lack of detail on this ticket. Please comment if this issue still persists in the latest version.
