### ISSUE TITLE
File Properties : scan type wrong

### ISSUE THREAD

**Issue by lucaetere** [OpenShot/openshot-qt#2923]
Compared with mediainfo, there must be something wrong here
ver2.4.4
![prop](https://user-images.githubusercontent.com/53849689/62604176-10046800-b92a-11e9-9688-19e83fafa9ac.png)

**Comment by lucaetere** [comment]
why Interlaced: NO ???

**Comment by ferdnyc** [comment]
Also confirmed, however I'm going to roll this into your #2922 as it's easier to track the overall issue of interlaced video support if it's all in the same place.
