### ISSUE TITLE
App crashes at rendering.

### ISSUE THREAD

**Issue by 134981654** [OpenShot/openshot-qt#2928]
App crashes.

At rendering

Everything worked and now not. Daily build does not work for me.

**System Details**
- OpenShot Version: 2.4.4-dev2
- libopenshot Version:  0.2.3
- Platform: Windows-10-10.0.18362
- Processor: Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.4.4-dev2-1565251638-e95d1847-f17a7ed4-x86_64.exe

**Log Files**
- http://logs.openshot.org/fimru5hs28trg8rm2xaooqc9kha2imey/openshot-qt.zip
- http://logs.openshot.org/fimru5hs28trg8rm2xaooqc9kha2imey/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by SuslikV** [comment]
I don't see any export running in the log. At which point application crashes? How your crash looks like? Any messages on the screen?

**Comment by 134981654** [comment]
Yes, that is correct. There was no messages on the screen whatsoever. App crashes was from 0%-10% in process of rendering, and based on the task activity, there was task activated called "windows problem reporting service" just a few moments before the crash.
I did previously about 10 or 15 renderings on the same computer and with the same  preferences; in the meantime I have updated hardware drivers on my PC, so I have suspected that this was the problem. After carefully looking into it, and trying different software versions, I have decided to try rendering with different video, and it was successful.  The video was the problem, it was mp4 video, and speed of it was 8x, so I suspect that there was some kind of conflict there... Anyhow, I think that this problem is solved, thank you for your interest.

**Comment by SuslikV** [comment]
OK. I'd like to link this one: https://github.com/OpenShot/openshot-qt/issues/1197 here, to track the issue that looks similar (at least from the available description).

**Comment by mikelacsa** [comment]
@134981654 are you still experiencing the crashes?

**Comment by mikelacsa** [comment]
I see. Thanks @134981654. I'm closing this issue now.
