### ISSUE TITLE
Open recently silently fails if path/file don't exist

### ISSUE THREAD

**Issue by msbentley** [OpenShot/openshot-qt#293]
Using OpenShot 2.1 on ubuntu 16.04 x64, I renamed a directory containing a recent project. When I try to open the project from the "File / Recent Projects" menu, the program doesn't report a file not found message, but just silently ignores the request.

**Comment by DylanC** [comment]
@msbentley - Agreed. We should be outputting a visual error message here.

**Comment by peanutbutterandcrackers** [comment]
@DylanC - Still not fixed in v.2.4.1 Tested today. So, yeah...

**Comment by peanutbutterandcrackers** [comment]
@DylanC - Wonder if we should do prioritizations and milestones too. Like "This enhancement will be solved in v2.4.2" or something...

**Comment by DylanC** [comment]
@peanutbutterandcrackers - True. Something like that would be nice!

**Comment by peanutbutterandcrackers** [comment]
@DylanC - Perhaps you should write to Mr. Thomas regarding that (and also informing him about the pull request that awaits his approval). I would also like to suggest making very small version number bumps. Let's have OpenShot v2.4.2 after v 2.4.1. Let's even have 'unstable' and 'stable' versions, aside of the daily builds. Let's have v2.4.x where x is an even number, be stable - bug fix release and 2.4.x where x is an odd number be an enhancement release --- like GIMP does. And let's have the Major.Minor.x go up to Major.Minor.42 before finally going up to Major.Minor+1.0, or something similar. I'd like to see OpenShot be around even after 25 more years.
