### ISSUE TITLE
Issue with importing pictures

### ISSUE THREAD

**Issue by FREAKSHOWow** [OpenShot/openshot-qt#2935]
So, I was editing a video adding PNGs and JPGs onto the video and it worked completely fine for the first 30 minute video. Next day, I come back to edit the second and it works fine, I add the original 4 from the first video back and then add another 2. Then - while importing the third new one, it said that the image was not a valid image, audio or video file, so i checked and it was a PNG, like others that I has already done, so I tried several different things and it didn't work. Then I tried to do the next one and the same thing happened, only that I got the error message multiple times about both the images i had tried to import and then they appeared in my imported slot, but every time i add another image, I get more error messages about all of them.
Then i deleted the file and started again and this time i couldn't import any photos, even trying different ones after just reproduced the error message and didn't make them appear.

The weird thing is that it just worked for a long period of time and just stopped.

(Im running OpenShot version 2.4.4 on Windows 10)

EDIT: I'm finding that with the JPGs, even continuously trying to import them doesn't work but with the PNGs, they do appear after the error messages but the error messages keep appearing even after they are imported when a new file is imported

**Comment by SuslikV** [comment]
Probably project's files damaged. Try to create new one in a new folder. Any changes?

**Comment by mikelacsa** [comment]
@FREAKSHOWow how is it going? Are you still experiencing this issue? If so, would you send us a fresh copy of your log files, please? Here are the steps to do it:

1. Locate the following files and delete them:

C:/Users/USER/.openshot_qt/openshot-qt.log
C:/Users/USER/.openshot_qt/libopenshot.log

2. Reproduce the issue you experienced.
3. New log files will be created.
4. Send them here.

Thanks!

**Comment by mikelacsa** [comment]
No response 7 days after being labeled "needs info". Closing the issue.
