### ISSUE TITLE
No get turns to nonetype object is not subscriptable on one project alreay exported, how to re open it

### ISSUE THREAD

**Issue by davidemonetto** [OpenShot/openshot-qt#2942]
**Question:**
We were working on a openshot project some days ago  that collapsed after an export. Somehow,  I found an autosave that worked pretty well, except some errose in exportation and the phrase " has no attribuite get", accompained the fact that the imported video didnt show up, resolved by simply importing one of the files - every other one popped up immediately. Strangely, exportation of a single part of the video gave me issues. Today I was working with the volume of the audio, the token of the video that had problems disappeared, it became suddently impossibile to import in the timeline toner ones. I trial to re open it: nonetype object one subscriptable. I am desperate. How can I recover it? I am a newby in this sort of things. 

**System Details:**
- OpenShot Version: 2.4.4
- Operating System / Distro: Windows 10

**Comment by SuslikV** [comment]
Please, make backup copies during your work on large projects. Save project files (.osp) in newly created folder only (one per project).

The project seems to be damaged. Probably, it can be fixed only by manual edit of the file. But you can try to make copy of the project file into new folder and delete the problem clip from the sources list, then save the project and try to import clip again.

**Comment by mikelacsa** [comment]
@davidemonetto how is it going? Have you tried @SuslikV 's suggestion?

**Comment by mikelacsa** [comment]
No response 7 days after being labeled "needs info". Closing the issue.
