### ISSUE TITLE
Option for limiting number of Threads to use while encoding

### ISSUE THREAD

**Issue by Lalarian** [OpenShot/openshot-qt#2943]
**Describe the new feature:**
I think it's easily explained: I could really use an Option for settings how many cores/threads. Of course it's great that multicore and SMT are being used by OpenShot, but I cannot use my system (Xubuntu 18.04 on Intel i7-3720QM) well, while OpenShot is exporting a video, because OS uses 100% CPU.

I can temporarily fix this problem, by using taskset like this:
"taskset -apc 0,1,2,3,4,5 758", so OS would only use 6 of 8 threads, but of course it's too bothersome, having to do this everytime I export a video.

OpenShot should use at maximum while exporting a video.

**Describe the solution you'd like:**
In Configuration menu/Performance there could be an numerical input filed for settings the maximum number of threads to use.

**Describe alternatives you have considered:**
Maybe a niceness preset?

**Screenshots:** (Optional)
not required

**Comment by ferdnyc** [comment]
@Lalarian 

Download the latest Daily Build for your OS from https://openshot.org/download/ :wink: 

![image](https://user-images.githubusercontent.com/538020/63624197-ab076e00-c5c9-11e9-9d39-4928d873a6df.png)

**Comment by Lalarian** [comment]
Thank you!
