### ISSUE TITLE
not able to select objects in a project or drag and drop new objects

### ISSUE THREAD

**Issue by JustaKing4** [OpenShot/openshot-qt#2944]
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/3537295/libopenshot.log)

[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/3537296/openshot-qt.log)

Running windows 10, 64 version of Openshot. I don't know how the error happened, but it happened during editing the same project. Suddenly I could no longer reposition any of the files in the project and I could not drag any new items into the project. I can still copy/paste and right click items to edit their properties but cannot freely move anything. Also I cannot export the project at all without ending up with a corrupted file. This last bug happened sometime ago, and I was trying to find a solution here at that time, but I somehow worked around it to obtain a finished video, but this time the video is not finished, so Im pretty much stuck....After updating to the newest build, i get this error message now everytime I try to load the project. 

'NoneType' Object is not subscriptable     

this is so frustrating.....

Update: I have completely uninstalled and reinstalled and am still encountering the same issues...is there another folder I need delete while wiping the program?

**Comment by SuslikV** [comment]
Project file is damaged. There is null data somewhere in the saved file that in't handled by OpenShot correctly. You can start completely new project or, if it's nothing special about, - upload the zip of the broken project file here  - I will try to fix it for you.

**Comment by JustaKing4** [comment]
Thank you for the offer, but i figured out if i changed the audio to a certain frequency it was able to export it. I get a static noise at certain parts in the video, which is annoying, but at least the video is safe and done. I think i will be switching to a different editing sowftware, because as great as the community is, i just keep running into major problems with openshot. Thanks for all of your help though and God bless. 
            JustaKing

⁣Get BlueMail for Android ​

**Comment by mikelacsa** [comment]
_The user is not interested in pursuing to fix the issue anymore, Closing the issue_
