### ISSUE TITLE
 OpenShot 2.1.0 on Windows: cx_Freeze: Python error in main script

### ISSUE THREAD

**Issue by basst85** [OpenShot/openshot-qt#295]
## cx_Freeze: Python error in main script

Traceback (most recent call last):
  File "C:\msys64\mingw64\lib\python3.5\site-packages\cx_freeze-5.0-py3.5-mingw.egg\cx_Freeze\initscripts\Console.py", line 21, in <module>
  File "openshot_qt/launch.py", line 77, in <module>
  File "openshot_qt/launch.py", line 70, in main
  File "C:\Program Files\OpenShot Video Editor\classes\app.py", line 115, in **init**
    import classes.metrics
  File "C:\Program Files\OpenShot Video Editor\classes\metrics.py", line 28, in <module>
    import httplib2
  File "C:\msys64\mingw64\lib\python3.5\site-packages\httplib2__init__.py", line 51, in <module>
  File "C:\msys64\mingw64\lib\python3.5\ssl.py", line 98, in <module>
ImportError: DLL load failed: The specified module could not be found

---

I'm using OpenShot v 2.1.0

**Comment by CyberWolf2k16** [comment]
I have same issue, but I noticed it first when trying to install v2.1.0. I also tried the 64 bit version of 2.0.7 as well and SAME issue. Attached screen cap of error.
![oserror](https://cloud.githubusercontent.com/assets/21952292/18202650/84b86f5c-70df-11e6-982f-b839459d769e.jpg)

**Comment by jonoomph** [comment]
Very strange. I'm testing on a Windows 10 (64 bit) system, and don't get this error at all. Of course, version 2.1 will only run on a 64 bit system at the moment. I'll dig around the ssl error though. Perhaps, I'm missing a file needed by Windows 7.

**Comment by jonoomph** [comment]
@CyberWolf2k16, this is a different error than your screenshot shows. So, I'm going to focus on the original reported issue to keep this issue organized. Can someone else with Windows 7 64 bit reproduce this error?

**Comment by jonoomph** [comment]
@basst85, can you attach the specs of your system? I want to verify it's a 64 bit CPU and 64 bit version of Windows 7. Thx!

**Comment by jonoomph** [comment]
I'm going to go ahead and disable ssl validation (since we don't use ssl in OpenShot), and that might fix this issue.  Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot. _It might take a couple hours for the latest version to appear._

Feel free to reopen this ticket if the problem persists. Thanks!

**Comment by VadymVolos** [comment]
Win10x64 and OpenShot-v2.1.0.exe

![990](https://cloud.githubusercontent.com/assets/12669290/19766661/c0ee68e8-9c57-11e6-92dd-8d797bcc4f00.png)

**Comment by chris-33-92** [comment]
I have the same issue when i try to launch the editor.

But there is something strange : when the editor is automatically launching just after installation, it properly works !? It does not work when you try to launch using the icon.

**Comment by dokuhebi** [comment]
I'm also getting the same error in on Windows 7.  I installed what I believe is the latest build (OpenShot-v2.2.0-2-g5a2acb8-49-597-x86_64.exe). 

![screenshot 19](https://cloud.githubusercontent.com/assets/655053/21633311/04a76ce8-d21c-11e6-8970-713676e2049d.png)

**Comment by ircole** [comment]
Is there a resolution for this.  I just installed OpenShot-V2.2.0-x86_64 and get the same error.

**Comment by hellpanderrr** [comment]
I get the same error using OpenShot-V2.2.0-x86_64 on Win7x64. 
I tried commenting out usage of http2lib here https://github.com/OpenShot/openshot-qt/blob/master/src/classes/metrics.py#L152 and here https://github.com/OpenShot/openshot-qt/blob/master/src/classes/metrics.py#L172 — then there is no exception, but OpenShot app doesn't show and the process stays in the memory doing nothing.

**Comment by vac** [comment]
I get same (ssl) error  on v2.3.1 on Windows 10 x64

**Comment by jonoomph** [comment]
Hi everyone, and sorry about this ticket still happening. These errors all come down to the Python httplib2 library, which I only use for a few basic things, and something on your system not linking correctly with the required SSL DLLs I ship with httplib2. Long story short, I've removed httplib2 from OpenShot and replaced it with another (simpler) HTTP library, and I've verified this fix with another user, so I feel pretty confident the following installer will work for everyone:

https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.3.3-5-g4349753-55-628-x86_64.exe

**Comment by ircole** [comment]
The new update works for me.  Thanks.

**Comment by gadic** [comment]
The link provided works for me as well, thanks!
I guess the fix is NOT added to the current release, as the official version v2.3.4 does not work.
My install: Win 7 Entreprise, Service Pack 1, Intel Core i7, 64-bit.

**Comment by hpinto** [comment]
With the new versrion (2.4.4) i have the same problem on a Win10 x64 (Intel I7).

**Comment by EBW1** [comment]
Link is not working for me and i get the same error

**Comment by okumedia** [comment]
Seems this error on OpenShot-v2.4.3-x86.exe I just download today. Any fix yet?

**Comment by bephial** [comment]
Same here. I have Anaconda installed.

![06-02-_2019_09-09-53](https://user-images.githubusercontent.com/34677403/52328212-0d629d80-29ef-11e9-93f3-ad73ddc45541.png)

**Comment by webbruder** [comment]
Same error for me.
https://user-images.githubusercontent.com/34677403/52328212-0d629d80-29ef-11e9-93f3-ad73ddc45541.png
