### ISSUE TITLE
Lanch.exe Fails on 2.10 , 

### ISSUE THREAD

**Issue by Cybertoad** [OpenShot/openshot-qt#296]
Lanch.exe Fails on 2.10.
Running win7 64 , quadcore 2.66 with 8g ram. 
Opening program and it will run open for hours if I do nothing was on all last night never crashed.
I opened a new project, added a new file tried to slice the file it froze at once and went into error Launch.exe fail.
I setup debug but where does it send the log to? Cant find the log file ?
Great program but wont work on this PC or a laptop I have with Win7 either.

**Comment by vinkas** [comment]
I got the same error when I try to scroll around the timeline :/

**Comment by openmn** [comment]
I am on Win7 64-bit running 2.1.0. It has been pretty stable (not crashing) when I am editing the video, but when I go to export, it will get through about half (varies between 30-70%), and then will give me a launch.exe error and I have to close the program. Have tried MP4 (Both H264 and MP4) and WebM. Usually lasts longer during WebM. This is only happening on my projects with more than one clip. I have successfully used ver. 2.1 to take some 4k drone footage and bring it down to 720p, but I have to do it one clip at a time. I have not been able to render my full 7 minute video for a few days. It has about 2 dozen clips, photos, and music tracks.

**Comment by vinkas** [comment]
I am also a Win7 64-bit user

**Comment by openmn** [comment]
Updated information from my previous comment. My issue was that some of my clips were set to 2x, which should work, but causes this issue in 2.1. Once I rendered them in 2x in WinMovMak and moved the 2x clips into OpenShot, I no longer had launch.exe issues. A bug, but I was able to make it work for my project this time.

**Comment by jreynojustin** [comment]
Hi @Cybertoad,

Please install the newest version of OpenShot (V2.2) and re-open the issue if you are still noticing a problem.
