### ISSUE TITLE
MP4 compression like/with ffmpeg

### ISSUE THREAD

**Issue by shadowvzs** [OpenShot/openshot-qt#2962]
![compare](https://user-images.githubusercontent.com/17709504/64074549-580e7480-ccb5-11e9-8764-582ab22ffb67.png)

Hi, i recorded a video and edited with OpenShot (cut/fade etc) and i **exported (_mp4, 720p, h.264_)** it then i used ffmpeg for compress and the size difference is very huge:

- exported output size: **16.2Gb**
- after ffmpeg: **1.2Gb**

ffmpeg command: `ffmpeg -i vagatlan.mp4 -vcodec h264 -acodec aac output.mp4`
quality loss: _i didn't noticed any quality difference in video, look like the quality is **SAME**_ :)

possible integret a ffmpeg conversion option after the export or compress video like ffmpeg?
since size difference is really huge at 2h+ videos :)

**Comment by SuslikV** [comment]
Look at the _Advanced_ tab of the exported video quality settings. Type `18 crf` or `23 crf` instead of the bitrate.

**Comment by georg-d** [comment]
> Look at the _Advanced_ tab of the exported video quality settings. Type `18 crf` or `23 crf` instead of the bitrate.

I did try with two very different values (e.t. 10 and 35) many spellings (e.g. "crf 35" and "35crf" and "10 crf" and just "35" etc) but file size and visual quality is always the same. At least on my machine, crf setting is not working for all h.264 encoders, see https://github.com/OpenShot/openshot-qt/issues/4002
