### ISSUE TITLE
Cannot open filemanager with latest Mac built (Give your bug report a descriptive title)

### ISSUE THREAD

**Issue by anavmehta** [OpenShot/openshot-qt#2965]
**Describe the bug**
Cannot open filemanager with latest Mac built

**Steps to reproduce the behavior:**

**Expected behavior**
When I select "+" to select files, the filebrowswer doesnt open

**System Details**
- OpenShot Version: 2.4.4
- libopenshot Version:  0.2.3
- Platform: Darwin-19.0.0-x86_64-i386-64bit
- Processor: i386
- Machine: x86_64
- Python version: 3.6.4
- Qt5 version: 5.5.1
- PyQt5 version: 5.5.1
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.4.4-dev2-1566992604-f8c180c1-f17a7ed4-x86_64.dmg

**Log Files**
- http://logs.openshot.org/8xlyz2fgxpxwd89cab75q0c2zm5esb2k/openshot-qt.zip
- http://logs.openshot.org/8xlyz2fgxpxwd89cab75q0c2zm5esb2k/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by ferdnyc** [comment]
@anavmehta 

Hmm, that's very strange. A few questions:

1. Were you able to open the file browser with previous builds, or is this the only one you've tried?
1. If you try to add a file by drag-and-drop, does that work?
1. If you _are_ able to add a file by drag-and-drop, and insert it into the timeline, then does the Save browser come up when you choose "Save Project"?
1. Your report says you've installed a recent Daily Build? Is that the version you collected these logs with? I only ask because, the logs don't seem to indicate that they were produced by a daily build install — I would expect them to report the OpenShot version as `2.4.4-dev2`, same as the daily build filename. But all of your logs show:
```
      launch:INFO ------------------------------------------------
      launch:INFO    OpenShot (version 2.4.4)
      launch:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.4.4
         app:INFO libopenshot version: 0.2.3
         app:INFO platform: Darwin-19.0.0-x86_64-i386-64bit
```

**Comment by anavmehta** [comment]
On Tue, Sep 3, 2019 at 3:18 PM Frank Dana <notifications@github.com> wrote:

> @anavmehta <https://github.com/anavmehta>
>
> Hmm, that's very strange. A few questions:
>
>    1. Were you able to open the file browser with previous builds, or is
>    this the only one you've tried?
>
> This is the only one I have tried

>
>    1. If you try to add a file by drag-and-drop, does that work?
>
> No

>
>    1. If you *are* able to add a file by drag-and-drop, and insert it
>    into the timeline, then does the Save browser come up when you choose "Save
>    Project"?
>    2. Your report says you've installed a recent Daily Build? Is that the
>    version you collected these logs with? I only ask because, the logs don't
>    seem to indicate that they were produced by a daily build install — I would
>    expect them to report the OpenShot version as 2.4.4-dev2, same as the
>    daily build filename. But all of your logs show:
>
> Daily build doesnt work. It cannot be installed because "Software cannot
be verified"

**Comment by anavmehta** [comment]
Drag and drop doesnt work either. None of the file selection is functional.

**Comment by mikelacsa** [comment]
Hi @anavmehta 

Have you tried the latest daily build?

**Comment by ferdnyc** [comment]
@mikelacsa 

@anavmehta responded to that: 
>  Daily build doesnt work. It cannot be installed because "Software cannot
> be verified"

I guess maybe we're not signing the daily builds on MacOS? (I don't know why we wouldn't be, the same process generates them as generates the releases. Unless @jonoomph is doing some additional step by hand, for the release builds.)

**Comment by mikelacsa** [comment]
@ferdnyc copy that. Is more information needed so this issue can be worked on?

**Comment by ferdnyc** [comment]
@mikelacsa That's a good question. Honestly without access to a Mac, I'm kind of at a loss.

@anavmehta The Daily Build service was offline for a couple of weeks, @jonoomph just got it restored a couple of hours ago and we have new Daily Builds — would you be able to try the newest MacOS build, let us know if you get the same verification failure? If so then that's a concrete issue we can try to solve with the build servers.

If we get that fixed, then we can see if the latest builds still have the same issues with access to the host filesystem.

**Comment by mikelacsa** [comment]
@anavmehta Have you tried the newest MacOS build?

**Comment by mikelacsa** [comment]
No response from @anavmehta. Closing this issue.
