### ISSUE TITLE
can not use video as mask

### ISSUE THREAD

**Issue by anegroo** [OpenShot/openshot-qt#2968]
**Describe the bug**
I would like to use a vide file as a mask for another video from timeline ( Since version 2.43 we could theoretically use a video file as mask (this can be read in description of 2.43). ). I copied the mask file to the ".openshot_qt\transitions" folder (i tried in many formats and codecs, even uncompressed) and it appears in OpenShot in the transitions list, but I can not drag and drop over the video from the Timeline. After that I can not drag and drop even the native mask files! In another case, If I tried first the native transitions or a simple custom mask, and it works. But when I try vith the video mask, OpenShot suddenly  refuse to accept any mask from that point. 

**Steps to reproduce the behavior:**
1. Create a video for mask
2. Copy it to the transitions folder
3. It appears in the transitions list in the OpeShot interface
4. Drag over the another video from timeline, 
4. See error: red mark - can not drag over

**Expected behavior**
 I use Openshot from a year ago, I introduce my students in video editing with the help of your great program, as a free alternative to Premiere.  One important exercise is using masks and I was very happy, when appeared the possibility (in 2.43) to use video files as masks. I tried only in version 2.44 but is not working

**System Details**
- OpenShot Version: 2.4.4-dev2
- libopenshot Version:  0.2.3
- Platform: Windows-8.1-6.3.9600 and I tried With the latest Kubuntu also
- Processor:  ACPI\GENUINEINTEL_-_INTEL64_FAMILY_6_MODEL_58_-_______INTEL(R)_XEON(R)_CPU_E3-1225_V2_@_3.20GHZ\_1
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.4.4-dev2-1566992561-f8c180c1-f17a7ed4-x86_64.exe

**Log Files**
- http://logs.openshot.org/z44hrpdx0zd2pcn5in2pr6g7it8hkkai/openshot-qt.zip
- http://logs.openshot.org/z44hrpdx0zd2pcn5in2pr6g7it8hkkai/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)

                
![Screenshot](https://user-images.githubusercontent.com/54820985/64134328-986d1000-cde5-11e9-8574-c69ab9931727.png)

**Comment by ferdnyc** [comment]
@anegroo 

Sorry for the delay in responding to this. The announcement mention of the new Mask/Transition video support was probably a little unclear about how exactly it works.

The change that was made in OpenShot 2.4.3 was to the `Source` property of both the Mask effect, and to Transitions on the timeline. Previously the only available `Source` values were the static `.svg` files in the `transitions` folder, but now if you right-click the `Source` property field, in addition to the supplied transition files, you can also select any of the items in Project Files to use as your `Source`. A grayscale copy of the image or video will be used as the alpha mask for the effect/transition.

Here's a quick example:
![image](https://user-images.githubusercontent.com/538020/64569683-2ee08a80-d32c-11e9-8335-2b82047d859b.png)

I have two files imported here.
1. A video to demonstrate on.
2. "BouncyFun.mp4", a quick video I created in OpenShot from a still image. It's just the word "Fun" in black text, moving around on a white background.

You can see that I have my video on the timeline, with a Mask effect applied, and I've set "Bouncyfun.mp4" as the Source of the mask.

Farther down the timeline I have the same video again, without the mask, but after a couple of seconds I start a transition using BouncyFun.mp4 as the Source, and use that to crossfade into another video (actually the BouncyFun animation itself).

And here's what the result would be, converted to an animated GIF to ensure minimum possible quality and hopefully hide most of my shortcomings as an animator and video producer. :wink: 

![FunTest](https://user-images.githubusercontent.com/538020/64570156-abc03400-d32d-11e9-89a9-d6b5793d11e0.gif)

**Comment by anegroo** [comment]
Hi Frank, excuse me for the late answer. I followed you explanation, and it works well.  Thank you very much!

**Comment by SuslikV** [comment]
@ferdnyc 

![2019-09-13 19-31-20](https://user-images.githubusercontent.com/19683044/64878878-3621d400-d65d-11e9-9d5b-2b908bafdd82.gif)

**Comment by ferdnyc** [comment]
@SuslikV 
Heh, that's pretty screwy alright.

I'd suggest filing a new issue for that, so we can track it. It's unlikely that Source is the _only_ place where that **could** happen, though right now it may be the only menu long/complex enough for it to actually happen.

@anegroo  Glad I could help! Closing this as answered, though feel free to reopen if anything else comes up.

**Comment by VisionaryMind** [comment]
As of 2022, this feature is still not working on Linux platforms. It was apparently never fixed.
