### ISSUE TITLE
Open Shot 2.1.0 crashes with launch failure error if a clip is dragged over a time line

### ISSUE THREAD

**Issue by dancetheskies** [OpenShot/openshot-qt#297]
I know the clip should be dragged to the Project Files window pane to import it, but it's a natural movement to drag it directly to the time line with other editors accepting this import method.  The clip does not even have to be release, just dragging it still held by the mouse over a timeline track will instantly crash the program.

Just preventing it from being dropped there would be the best solution.

**Comment by jreynojustin** [comment]
OpenShot is now in Version 2.2 if you are still noticing issues in the latest version please re-open this issue letting us know.
