### ISSUE TITLE
New Effects like Chrominance and Color Tint  Filter

### ISSUE THREAD

**Issue by darshitvvora** [OpenShot/openshot-qt#2970]
**Describe the new feature:**
New effects like chrominance control and rgb color tinting for video

**Describe the solution you'd like:**
Add new effect for same. I think it will be in libopenshot

**Describe alternatives you have considered:**
Possibly someone could suggest workaround for same with any other effect

**Screenshots:** (Optional)
https://www.lunapic.com/editor/premade/tint.gif - example of blue color tint effect

**Comment by ctsdownloads** [comment]
Thanks for the feature request.
