### ISSUE TITLE
Openshot crashes as soon as it is opened (current build) [seems to be audio/video files causing the problem]

### ISSUE THREAD

**Issue by DirtySouthCats** [OpenShot/openshot-qt#2977]
**Describe the bug:**
I opened the program and was working on a project just fine until at one point it quit responding and then crashed and closed. Upon trying to reopen the program it would just repeatedly crash and I could not open it. After trying to reinstall and making sure I had the newest update with current daily build and troubleshooting via the Openshot.org website (deleting the log files) I was again able to open the program, however the same problem repeated itself after several minutes. I can add image files with no issues but when trying to add an audio or video file is when the issue seems to arise. Now when reopening the program it says "recovering from backup" but crashes and reinstalling does not allow the program to open at all.

**Steps to reproduce the behavior:**
1. Go to 'OpenShot Video Editor'
2. Click on 'Open'
3. Scroll down to 'N/A'

**Expected behavior:**
Not to crash when adding files to a project.

**System Details:**
- OpenShot Version: OpenShot-v2.4.4-dev2-1566992561-f8c180c1-f17a7ed4-x86_64
- Operating System / Distro: Windows 10 Pro 64 bit

**Log Files:**
Since the last crash (after reinstalling the latest daily build there are no log files for me to upload. The only file I have is the openshot-qt.txt file. 
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/3585744/openshot-qt.log)

**Comment by ferdnyc** [comment]
@DirtySouthCats OpenShot does appear to be crashing when attempting to load the backup file, which seems to contain an image sequence that doesn't load correctly for whatever reason.

Moving or removing the file `C:\Users\rebec\.openshot_qt\backup.osp` should fix the backup-recovery crashes and at least allow OpenShot to start up for you again, though I'm not sure what caused the bad recovery data in the first place, or whether it might happen again.

If it _does_, then a copy of the bad `backup.osp` file might help us track down the cause.

**Comment by ferdnyc** [comment]
Hmm, here's one possibility: The backup file loads a bunch of images from `C:\Users\rebec\Pictures\DirtySouthCats\`, files like `Rebexxa11.png`, `Rebexxa27.jpg`, etc.

It's _also_ trying to load the set of files in that directory as an image sequence, matching the pattern `Rebexxa%d.png`. (Which just means any png file named "Rebexxa" followed by a number.)

Looking at the data for the files it _did_ load, though, those PNG files appear to be all different sizes, aspect ratios, etc. Files in an image sequence are imported as individual frames that get combined into a video, so they're expected to all be the same size and format. 

It looks like the code to import the images might be crashing because it's trying to assemble an image sequence from a set of mismatched images.

**Comment by DirtySouthCats** [comment]
Yes, I've fixed the issue between the png and jpg photos. I also deleted all the thumbnails out of the folder. The application still crashes upon opening.

**Comment by ferdnyc** [comment]
@DirtySouthCats At this point I'd recommend deleting the entirety of `C:\Users\rebec\.openshot_qt` (or rename it to something else, if you think there might be useful data in there), then try launching OpenShot without loading a project file. See if it runs like that. 

If it _does_, then you can try loading a project file, if you have one that you want to work on... but if it crashes again, then I'd consider that project file damaged and not attempt to use it anymore. (If you'd be willing to post the file so we can examine it, in that case, it would be a big help. We certainly like to prevent this happening in the future.)

**Comment by mikelacsa** [comment]
@DirtySouthCats how did it go? Did you try @ferdnyc's recommendation?

**Comment by ferdnyc** [comment]
Unfortunately, still no response after more than two weeks. Closing.
