### ISSUE TITLE
2.1.0 AppImage fails to run with "undefined symbol: g_type_check_instance_is_fundamentally_a"

### ISSUE THREAD

**Issue by geckolinux** [OpenShot/openshot-qt#298]
Hi, this happened on openSUSE Tumbleweed. The AppImage does not run at all. I am attaching the log.

Thanks!

[log.txt](https://github.com/OpenShot/openshot-qt/files/448877/log.txt)

**Comment by probonopd** [comment]
In another recipe, I noted that function g_type_check_instance_is_fundamentally_a was introduced in glib2-2.41.1.

> Bundling __libglib-2.0.so.0__ in order to do away with the following error (FIXME, find a better solution):
antergos-2014.08.07-x86_64.iso
linuxmint-17.3-cinnamon-64bit.iso
ubuntu-14.04.1-desktop-amd64.iso
undefined symbol: g_type_check_instance_is_fundamentally_a

So maybe this would help here too?

**Comment by jonoomph** [comment]
I'm already bundling the following files with the OpenShot AppImage. I can now reproduce the error mentioned above using Mint 18, so I'm going to do some experimenting, and see what fixes it. =)
-  libglib-2.0.so
- libgio-2.0.so
- libgmodule-2.0.so
- libgobject-2.0.so
- libgthread-2.0.so

**Comment by jonoomph** [comment]
Here is the version of glib I'm using on my build server (which creates the AppImage):
- libglib2.0-0 2.40.2-0ubuntu1

**Comment by jonoomph** [comment]
@probonopd, what would be the ideal distro to use for building an AppImage, so it's not too recent, and not too old? Just curious what you would recommend.

Currently, I'm using Ubuntu 14.04 LTS (from April 2014)

**Comment by jonoomph** [comment]
Looks like "g_type_check_instance_is_fundamentally_a" was introduced in glib 2.4.0.

**Comment by probonopd** [comment]
Thanks @jonoomph for looking into this. Generally I recommend CentOS 6 or debian oldstable (wheezy).

**Comment by jonoomph** [comment]
Thanks @probonopd, I've incorporated the fixes you mentioned on https://github.com/OpenShot/openshot-qt/issues/294, and new builds should be available soon on openshot.org for people to test. It now works for me on Mint 18. =)
