### ISSUE TITLE
importing .wmv file to openshot 2.2.0 on windows 7

### ISSUE THREAD

**Issue by ffctfb** [OpenShot/openshot-qt#2980]
Similar to issues #606 I am having the same issues from different operating system

System Details:
- Operating System: Windows 7
- OpenShot Version: 2.2.0

I am having issues importing my .wmv file to Openshot to edit them and export them. The files show up in Openshot, but will not play back. When I put them in the timeline, they play as a still image for a few seconds before going to black. I originally created the video file in OpenShot but it was running slow and I needed to upload my Video to my Youtube Channel Slap.Shtikk for my feature video, so i just transfered the file to Windows Movie Maker and finished the video and saved it. To my suprise even though i exported the video at 1920x1080 HD format it saved at a weird 854x480 :S and when uploaded into Youtube, the view setting only goes up to 480p and i need it in 1080pHD. I read the answers posted to issue#606 and it says to download .appimage which i did only to find out it only works for linux and windows does not recognize the file:

Windows cannot open this file:

Openshot-v2.3.1-x86_64.AppImage

To open this file, Windows needs to know what program you want to use to open it...

I expected this extension file would work to solve it for my windows 7, please help? with a solution for this, the continuous conversion, splitting and exporting of the file via other programs is making it less and less in quality and I just need this done from Openshot and finish the project in HD.

Thank you

**Comment by ferdnyc** [comment]
@slapshtikk 

Correct, AppImage files are only for Linux. However, Windows installers are available at https://openshot.org/download/ . The current release is OpenShot 2.4.4. (2.2.0 is from December 2016!) There's also a Daily Build section with even newer previews of what will (eventually) be the next release. But I'd stick with 2.4.4 for starters.

For WMV importing, OpenShot 2.4.4 should _hopefully_ have better luck — it uses a much more up to date version of FFmpeg than 2.2.0 did.

**Comment by slapshtikk** [comment]
> @slapshtikk
> 
> Correct, AppImage files are only for Linux. However, Windows installers are available at https://openshot.org/download/ . The current release is OpenShot 2.4.4. (2.2.0 is from December 2016!) There's also a Daily Build section with even newer previews of what will (eventually) be the next release. But I'd stick with 2.4.4 for starters.
> 
> For WMV importing, OpenShot 2.4.4 should _hopefully_ have better luck — it uses a much more up to date version of FFmpeg than 2.2.0 did.

Ferdnyc :( no :'( it's not working on 2.4.4 as well, was there an update attachment/extension?? Thank you for replying :)

**Comment by ferdnyc** [comment]
@slapshtikk Hmm, no, the 2.4.4 installer is pretty much self-contained, everything would be updated with that.

WMV support is not one of FFmpeg's strong points, unfortunately. 

You said you originally created the file in OpenShot, though? Is it possible to use that same project, but export the file to something _other_ than WMV? MP4 is going to be _much_ better supported on YouTube, as well as in OpenShot.

If you really need to use the WMV, checking the format with [MediaInfo](https://mediaarea.net/en/MediaInfo) might give us some clues about why OpenShot's having trouble with it. If you load your video file into that, then switch to View → Text in the menu, you should be able to copy/paste the window contents. If you post that data here, it might help us see why it's giving OpenShot trouble.
