### ISSUE TITLE
Performance Questions

### ISSUE THREAD

**Issue by virtualbitzz** [OpenShot/openshot-qt#2983]
I know that video editing software will often gladly soak up all available system resources, whether it be CPU, RAM, Disk I/O, or NIC utuilization.

I'm editing in 1440p@60fps and am noticing that Openshot is typically only using about 6GB of RAM, no more than 50% CPU and no more than 50% GPU. Unfortunately timeline playback is not smooth. I drop frames constantly and the audio often stutters. Also when exporting at this same resolution and framerate (MP4 h264) It only uses about 50% of the CPU. I'm not sure if this is a performance issue or not, but was wondering if Openshot somehow artificially limits the amount of system resources that it consumes. 

I have a fairly beefy system. Ryzen 1800x 8x core @ 3.6ghz, 32GB RAM, and a GTX 1080, Windows 10.

Openshot 2.4.4

**Comment by ferdnyc** [comment]
@virtualbitzz

You might want to check out the recent Daily Build downloads at https://OpenShot.org/download/ -- a bunch of performance improvements have been made since 2.4.4 release, and there's a lot more control over those parameters in the Preferences, too. I'd hope you'd at least be able to see some nice boosts to the export speed.

Previewing probably won't see as much improvement (if any), unfortunately. That's an area that hasn't been very conducive to optimization, so far.

**Comment by SuslikV** [comment]
OpenShot uses software rendering mechanism in all steps, so nothing will improve in nearby future. It uses RAM transfer a lot. Fortunately, major leakage in the composition during rendering was solved this year (that caused inadequately large amount of RAM consumption).

**Comment by cdalexndr** [comment]
On a i5-3570(4 core), playback stutters with only 33% CPU usage.
Even with current software rendering, if all CPU were utilized it would help reduce or even eliminate stuttering during playback.
I noticed more stuttering in areas with transitions than in middle of large movie segments.

**Comment by mouarfff** [comment]
I have a lot of performance issue too with a i7 7700HQ, 24gb of memory and gofrce 1060 3go.
Rendering animation process take a lot a lot of time, and i can't make any preview playing, because a lot of  frames drop and the audio often stutters.

**Comment by halbcust** [comment]
I was having the choppiness issue as well and thought it may be a cache issue. I am not that technical but after emptying cache it didn't make much difference but when I rebooted my video ran well again. So I quickly ran an export while it worked well and the mp4 ran well too. But it is only a temporary fix.

**Comment by mouarfff** [comment]
ok thx, i need time to make more test, i would do this but i loose a lot of time with making video with a lot of isssues :( ...
