### ISSUE TITLE
Openshot closes itself when I hit the video tab, stay on show all tab or try to import a video file.

### ISSUE THREAD

**Issue by tyazgan** [OpenShot/openshot-qt#2984]
**Describe the bug:**
When I open OpenShot Video Editor, I can import my project file which I was working on all day today and it did not crash or gave any error. Recently, when I import my project, the app closes itself without displaying any error or crash, it just closes down. I found out that the app closes itself if I stay on show all tab or on the video tab. If I quickly switch on images or audio tab when I first open the app it doesn't close and I can continue working on my project with the exception of opening the video or showall tab. Since I can not continue working on my project like this I came here for help. I also deleted the log files and reinstalled the newest version of OpenShot Video Editor and it still does the same thing. 

**Steps to reproduce the behavior:**
1. Open OpenShot Video Editor
2. Import my current project
3. If I stay on show all or video tab the app closes itself
4. No crashes but the app closes down

**Expected behavior:**
Not to close down while viewing my files on show all and video tab or when I try to import a video file. 

**System Details:**
- OpenShot Version : 2.4.4-dev2
- Operating System / Distro: Windows 10 pro 64bit

**Log Files:**
Since the app does not crash I do not know whether log files would help. I am also new to this and do not know what to do to be honest but I attached the log files I found under .openshot_qt files. 

[.openshot_qt.zip](https://github.com/OpenShot/openshot-qt/files/3588097/default.openshot_qt.zip)

**Comment by ferdnyc** [comment]
@tyazgan OK, it sounds like OpenShot is having an issue loading the information for one of your project files. (A video file, specifically.)

Unfortunately, your log files are _huge_, far too huge to locate any information that might be related to the crash.

If you could, please collect a new crash log using the procedure found in https://github.com/OpenShot/openshot-qt/blob/develop/CONTRIBUTING.md (i.e.: _Delete_ the existing log files first, launch OpenShot, do whatever action causes it to crash as quickly as possible, and then immediately collect the _new_ log file. That way it should contain only the necessary information leading up to the crash.)

If possible, please also provide a copy of the project file. (Just the `.osp`, not the media.)

**Comment by mikelacsa** [comment]
@tyazgan 

Just checking if you're still experiencing this issue?

**Comment by ferdnyc** [comment]
No response to repeated requests for updates, closing.
