### ISSUE TITLE
Multiple Timeline loading separate project in same openshot instance

### ISSUE THREAD

**Issue by darshitvvora** [OpenShot/openshot-qt#2985]
**Describe the new feature:**
Add multiple timeline in one openshot instance

**Describe the solution you'd like:**
This would be very helpful where we can load separate project in different timeline and copy paste project from one timeline to another. Example: In one project I add all effects as save that project as template, while creating new video, I can load raw video in one timeline. Effect in other timeline and the just copy paste effect from one timeline to another and video is ready for export

**Describe alternatives you have considered:**
opening multiple instance of openshot but this uses lot of memory in computer

**Comment by ferdnyc** [comment]
> **Describe alternatives you have considered:**
> opening multiple instance of openshot but this uses lot of memory in computer

Even if you were to do that, it wouldn't work. As I tried to explain in #2971, OpenShot does not have **any** ability to transfer timeline elements from one timeline to another — only within the same timeline. The actions labeled as "Copy" and "Paste" in the interface don't actually place anything on the the clipboard, really. They simply trigger code that selectively applies information from part of the current project data to another part.

I guess I'll leave this open as a request, but I suspect it's very unlikely to happen.

**Comment by darshitvvora** [comment]
@ferdnyc  - Thank you for reply. But it would be really great to have this feature. Hope to figure out some workaround for this
