### ISSUE TITLE
Ubuntu users: Are Unity Launchers still a thing?

### ISSUE THREAD

**Issue by ferdnyc** [OpenShot/openshot-qt#2992]
I happened to notice that there's still code in OpenShot to interface with the Unity Launcher system on Ubuntu, for reporting export progress:

https://github.com/OpenShot/openshot-qt/blob/483b719694da7d5d9413f7dab40535f1c505abd5/src/windows/main_window.py#L2393-L2406

As a Fedora user, I'm not really up on the state of Canonical's distro-specific featureset, so I'm just curious: is that still a thing?

I know that Ubuntu moved away from their Unity desktop and made the switch to GNOME a few releases back, so does that mean the code here is outdated / useless, or is there still relevant functionality in the GNOME-based Ubuntu desktop?

**Comment by DylanC** [comment]
@ferdnyc 

1) The implementation is likely specific to just Unity.
2) Ubuntu has moved away from Unity but as far as I know you can still install it and Unity still has fans. Might be worth keeping the code for a bit longer. imo.
