### ISSUE TITLE
there is any nighty build repo to test HW acceleration?

### ISSUE THREAD

**Issue by Askmewho** [OpenShot/openshot-qt#2993]
thats all guy, I wont to compile it (again hahah)

..if its possible..

**Comment by ferdnyc** [comment]
@Askmewho 

Sure! The development builds downloadable at https://openshot.org/download/ (click the Daily Builds button below the download link) have all of the current hardware acceleration features enabled. There are additions to the Performance tab in the Preferences window for device selection and to tune the export process for your system, and the Video Profile selections in the Export window will indicate which profiles are available to take advantage of hardware-accelerated encoding, and which are software-only encoders that run on the CPU.

**Comment by ferdnyc** [comment]
Oops, sorry, you said you wanted to build it yourself — the `develop` branch of each project repo is the most-current code, and contains all of the features included in the Daily Builds.

**Comment by Askmewho** [comment]
Ok! Just it doesnt appear on my linix desktop that option. Maybe ivendont have hw accel in my rx460 with my actual mesa driver

**Comment by Askmewho** [comment]
Ive note than the linux build runs far faster on linux. Even with my modest but desent specs, so I will not move on windows just for hw accel. Thanks!

**Comment by Askmewho** [comment]
Ive see performance label, but just multithread option.

**Comment by ferdnyc** [comment]
> Ok! Just it doesnt appear on my linix desktop that option. Maybe ivendont have hw accel in my rx460 with my actual mesa driver

It may also be that our detection isn't working properly for your hardware, that's actually something it would be really great to try and fix. Could you open an issue over at [OpenShot/libopenshot](https://github.com/OpenShot/libopenshot/issues/) (where the hardware detection lives), please? about the failure to detect your device? The output of the `vainfo` and `lspci` commands would also be helpful, for starters.
