### ISSUE TITLE
open shop splash screen or website banner

### ISSUE THREAD

**Issue by Reaper10** [OpenShot/openshot-qt#3]
Here is a new splash screen or website banner what ever you want to use for. 

<img width="950" alt="opne shot" src="https://cloud.githubusercontent.com/assets/8137561/8706003/e13b1920-2af2-11e5-819c-ca200e755e77.png">
or
<img width="950" alt="opne shot 2" src="https://cloud.githubusercontent.com/assets/8137561/8737694/bbc2f91c-2bea-11e5-8c40-4c34d0c887b1.png">

**Comment by jonoomph** [comment]
Thanks, I appreciate the artistic effort! I think I've settled on a good type-face to go along with the icon though, so for the moment, I think we are good. But I really do appreciate your effort! Thanks!
