### ISSUE TITLE
Keyframes tab does not show anything

### ISSUE THREAD

**Issue by jarlarntzen** [OpenShot/openshot-qt#30]
There's just a dark, empty pane no matter what kind of clip is selected. Adding any kind of animation (zoom in/out etc) or fade does not change anything.

Maybe keyframes isn't ready for use and if so, I'd suggest removing it until a later version to avoid confusion.

The animations themselves **do** work very nicely, though :)

**Comment by jonoomph** [comment]
This is a placeholder for a new Keyframe UI dock, which will list each point and value for a specific Keyframe. It's not quite ready, so I've removed it for now.

**Comment by jarlarntzen** [comment]
Makes sense. I look forward to try this too.
