### ISSUE TITLE
choppy playback of Canon T2i video (H.264 1920x1080 30p (29.97 fps) on Windows 7 in OpenShot 2.1.0

### ISSUE THREAD

**Issue by cphuntington97** [OpenShot/openshot-qt#300]
Playback in Windows Media Player is perfectly smooth. Any advice?

**Comment by cphuntington97** [comment]
Same behavior on Ubuntu 16.04 LTS. Choppy playback in Openshot; perfectly smooth playback in every other video player.

**Comment by jreynojustin** [comment]
OpenShot is now in Version 2.2 if you are still noticing issues in the latest version please re-open this issue letting us know.
