### ISSUE TITLE
Html behavior in animation titles edition

### ISSUE THREAD

**Issue by mouarfff** [OpenShot/openshot-qt#3000]
Hello !

I try to use the animation title but in lot of case, i can't write what i want because it's translate some symbols has html " ' " i can't use ' symbol, and i can't back to the line, i can't make align center, i need to type for example "\n" or "\t".

In some case, if i type "\n#, it doesn't have any effect .

**Comment by ferdnyc** [comment]
@mouarfff The animated titles editor fields doesn't support HTML content, only simple text. If you enter HTML code, you're going to get your HTML source rendered into a title. Blender's text rendering isn't an HTML parser, it just takes simple strings. Rendering complex HTML isn't possible, and if you wanted to have more control over the layout of the text elements the only thing I can suggest is loading one of the title files directly into Blender and editing them there. The `.blend` files are located in the `blender/blend/` directory of your OpenShot installation.

As for issues typing `'` characters, you'd have to be specific about where you're having issues with that. I just tested the Space Movie template, with the current development code (which uses the newer Blender 2.80 release), and as you can see from this screenshot there are no problems with any quoting characters or other symbols. (OK, the Emoji didn't work, but that was pushing it.)

![image](https://user-images.githubusercontent.com/538020/65081472-b3a55700-d971-11e9-8352-a617602bc7f7.png)

**Comment by mouarfff** [comment]
thx

i see another issue but i think depend of notepad++ (where i write my text before), it confuse with ' and the other { symbol

For this moment, i upgraded blender in 2.8 but now openshot don't see it ... (i will post another bug)
