### ISSUE TITLE
animated title duration

### ISSUE THREAD

**Issue by mouarfff** [OpenShot/openshot-qt#3002]
I try to create a title, but the duration can't be ajusted fine.
(here "star wars" like pre-formated title).

if my text is bigger or smaller than the default duration, i can crop it.

**Comment by mikelacsa** [comment]
This is has been considered an enhancement for future versions. Thanks @mouarfff

**Comment by ferdnyc** [comment]
Reopening, as we'll lose track of it otherwise.
