### ISSUE TITLE
launch.exe issue appears all the time :(

### ISSUE THREAD

**Issue by lauririwa** [OpenShot/openshot-qt#3003]
launch.exe stopped working appears all the time, when Im cutting the clips, when I add photos, and most important, when I try to export .
- I have the lastest OpenShot Version  and windows 7.

![Sin título](https://user-images.githubusercontent.com/55413669/64997932-8ea0dd80-d8b8-11e9-87f7-e958801617b4.png)

**Comment by SuslikV** [comment]
It looks like general PC error not connected to the OpenShot itself. Anyway, can you reinstall the application and try it again? Latest daily builds available here: https://www.openshot.org/download/

**Comment by mikelacsa** [comment]
> launch.exe stopped working appears all the time, when Im cutting the clips, when I add photos, and most important, when I try to export .
> 
> * I have the lastest OpenShot Version  and windows 7.
> 
> ![Sin título](https://user-images.githubusercontent.com/55413669/64997932-8ea0dd80-d8b8-11e9-87f7-e958801617b4.png)

@lauririwa are you still experiencing the problem after installing the latest daily build?

**Comment by mikelacsa** [comment]
_No response from the user 7 days after "need info" label. Closing this issue now._
