### ISSUE TITLE
Some problems report

### ISSUE THREAD

**Issue by Elrondo46** [OpenShot/openshot-qt#301]
- Animated title blank Screen
- Crash when separate video/audio

Solved
- Timeline crash
- Improve stability

Manjaro last version

Please solve the issues

**Comment by jonoomph** [comment]
Please test again with the latest daily build of OpenShot. I've merged in changes to the text alignment, and updated the minimum version compatibility to 2.78. I've tested all animation on Linux, Mac, and Windows with Blender 2.78 and everything works great.

Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot. _It might take a couple hours for the latest version to appear._

If you have other issues, please file additional bugs for each one. Thanks!
