### ISSUE TITLE
Segfault in _IceWrite

### ISSUE THREAD

**Issue by wilx** [OpenShot/openshot-qt#3010]
**Describe the bug**
Segfault on Linux, stack trace ending with `_IceWrite`.

**Steps to reproduce the behavior:**

Try to start AppImage.

**System Details**
- OpenShot Version: 2.4.4-dev2
- libopenshot Version:  0.2.3
- Platform: Linux-5.0.0-29-generic-x86_64-with-Ubuntu-19.04-disco
- Processor: x86_64
- Machine: x86_64
- Python version: 3.4.3
- Qt5 version: 5.2.1
- PyQt5 version: 5.2.1
- Qt Detected Languages: ['en-US', 'en']
- LANG Environment Variable: en_US.UTF-8
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.4.4-dev2-1568687222-f8c180c1-f17a7ed4-x86_64.AppImage

**Log Files**
- http://logs.openshot.org/7vbvcz6wi2fdva9m36u2cnf9ah3py3dn/openshot-qt.zip
- http://logs.openshot.org/7vbvcz6wi2fdva9m36u2cnf9ah3py3dn/libopenshot.zip

**Exception / Stacktrace**
```/usr/lib/x86_64-linux-gnu/libICE.so.6                                          0x7cd8  [0x7f00a60d4cd8]
/usr/lib/x86_64-linux-gnu/libICE.so.6 _IceWrite                                0x48  [0x7f00a60d9558]
/usr/lib/x86_64-linux-gnu/libICE.so.6 IceFlush                                 0x14  [0x7f00a60d9644]
/tmp/.mount_rhaUsz/usr/bin/platforms/libqxcb.so                                          0x4b054  [0x7f00a6998054]
/tmp/.mount_rhaUsz/usr/bin/platforms/libqxcb.so                                          0x4b1ff  [0x7f00a69981ff]
/tmp/.mount_rhaUsz/usr/bin/platforms/libqxcb.so                                          0x4bf21  [0x7f00a6998f21]
/tmp/.mount_rhaUsz/usr/bin/platforms/libqxcb.so                                          0x4cbb5  [0x7f00a6999bb5]
/usr/lib/x86_64-linux-gnu/libSM.so.6 _SmcProcessMessage                       0x8dc  [0x7f00ada5141c]
/usr/lib/x86_64-linux-gnu/libICE.so.6 IceProcessMessages                       0x368  [0x7f00a60dd978]
/tmp/.mount_rhaUsz/usr/bin/libQt5Core.so.5 QMetaObject::activate(QObject*, int, int, void**) 0x7e6  [0x7f00ad0482a6]
/tmp/.mount_rhaUsz/usr/bin/libQt5Core.so.5 QSocketNotifier::activated(int, QSocketNotifier::QPrivateSignal) 0x2e  [0x7f00ad0b457e]
/tmp/.mount_rhaUsz/usr/bin/libQt5Core.so.5 QSocketNotifier::event(QEvent*)          0x59  [0x7f00ad0542a9]
/tmp/.mount_rhaUsz/usr/bin/libQt5Widgets.so.5 QApplicationPrivate::notify_helper(QObject*, QEvent*) 0x8c  [0x7f00a89f6c8c]
/tmp/.mount_rhaUsz/usr/bin/libQt5Widgets.so.5 QApplication::notify(QObject*, QEvent*)  0x3d6  [0x7f00a89fbe56]
/tmp/.mount_rhaUsz/usr/bin/PyQt5.QtWidgets.so sipQApplication::notify(QObject*, QEvent*) 0x86  [0x7f00a93cc426]
/tmp/.mount_rhaUsz/usr/bin/libQt5Core.so.5 QCoreApplication::notifyInternal(QObject*, QEvent*) 0x6d  [0x7f00ad020c2d]
/tmp/.mount_rhaUsz/usr/bin/libQt5Core.so.5                                          0x2b542f  [0x7f00ad06e42f]
/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 g_main_context_dispatch                  0x2ae  [0x7f00ac31b9ee]
/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0                                          0x4ec88  [0x7f00ac31bc88]
/usr/lib/x86_64-linux-gnu/l...

**Comment by ferdnyc** [comment]
@wilx Sounds like there's a library incompatibility... does this happen right at startup, or while using OpenShot?

If at startup, or if the error can be reproduced, could you please capture and post the output of the following, leading up to a segfault?
```sh
cd /path/to/downloaded/AppImage/
LD_DEBUG=libs ./OpenShot-v2.4.4-dev2-1568687222-f8c180c1-f17a7ed4-x86_64.AppImage
```

**Comment by ferdnyc** [comment]
> does this happen right at startup, or while using OpenShot?

(Never mind, it's clear from the log file that it happens right at launch. So, yeah, if you could please capture the output with `LD_DEBUG=libs`, that'd be a huge help.)

**Comment by wilx** [comment]
I am attaching the log with `LD_DEBUG=libs`:  [ld_debug_libs_log.zip](https://github.com/OpenShot/openshot-qt/files/3639579/ld_debug_libs_log.zip)

**Comment by ferdnyc** [comment]
@wilx Many thanks!

Darn... I was really hoping there would be some useful information in there (like a missing symbol error or something), but alas there's nothing at all.

I have a build running on the build servers right now that excludes a few more common system libs from the AppImage. Assuming that works for _me_, even, I'll post a download link here, and we can see if it perhaps solves the issue. If not I'll have to come up with some better debug options for the dynamic loader.

**Comment by ferdnyc** [comment]
@wilx 

Yeah, here's a build off of a development branch, where I've excluded several more system libs from being bundled with the AppImage. It works _for me_, but then again so did the original AppImage without these changes. Still, give it a try if you could, and let me know if it changes anything.

https://drive.google.com/open?id=1bqSudb-MITqqNJoJrKZub1WHuN-eoicN

**Comment by wilx** [comment]
> @wilx
> 
> Yeah, here's a build off of a development branch, where I've excluded several more system libs from being bundled with the AppImage. It works _for me_, but then again so did the original AppImage without these changes. Still, give it a try if you could, and let me know if it changes anything.
> 
> https://drive.google.com/open?id=1bqSudb-MITqqNJoJrKZub1WHuN-eoicN

This actually started immediately without issue.

**Comment by ferdnyc** [comment]
\o/ That's great news, thanks! Hopefully the libraries I excluded will be present on every distro by default, and we can just go forward with leaving them out of the main builds. I'll submit that test branch as a PR now.

You should be able to switch back to the regular Daily Builds once that merges. (This issue will get auto-closed when that happens, so you'll be notified.)

**Comment by wilx** [comment]
Cool. Thanks.
