### ISSUE TITLE
Helo. I lost some recurses and the program does not  start from scratch

### ISSUE THREAD

**Issue by sistemas99** [OpenShot/openshot-qt#3013]
Helo. I lost some recurses and the program does not  start from scratch

**Comment by SuslikV** [comment]
Try to reinstall the application: https://www.openshot.org/download/

**Comment by mikelacsa** [comment]
> Helo. I lost some recurses and the program does not start from scratch

Hi! Are you still having this problem?

**Comment by mikelacsa** [comment]
No response more than 7 days after being labeled "needs info". Closing this issue now.
