### ISSUE TITLE
the preview video plays faster than 1x

### ISSUE THREAD

**Issue by aBetterFun** [OpenShot/openshot-qt#3018]
In the first several seconds, it's normal, but after playing for a while, the preview video starts to play faster than the actual speed. Also it costs more cpu usage than usual. This problem happens almost every time after I restarted the script. Could someone please solve this problem?

**Comment by mikelacsa** [comment]
Hi!

Thanks for your input. We'd like to know more about the problem you're experiencing so we can address it more efficiently. Can you tell me the following please:

1. Steps to reproduce the behavior
2. What are your system's specs
3. Have you tried testing it with the latest daily build? https://www.openshot.org/download/

Lastly, can you send us a fresh copy of your log files?

Thanks in advance.

**Comment by mikelacsa** [comment]
No response more than 7 days after being labeled "needs info". Closing this issue now.
