### ISSUE TITLE
Still picture in clip is set at 300 seconds

### ISSUE THREAD

**Issue by KyleRickards** [OpenShot/openshot-qt#302]
Hi

The picture length in a timeline is set to 300 seconds maximum, is it possible to get this extended to a longer period/or have a much higher stop limit?

**Comment by JtLively** [comment]
For now, best bet is to duplicate the image.

**Comment by peanutbutterandcrackers** [comment]
I have tested it and can confirm that this limitation does not exist in v 2.4.1. I actually created a 2 hour 16 minutes and 49 seconds long video (that totalled at 5+ GB) with just a single image on a friend's windows machine using v 2.4.1. So, yeah. I think this issue has been resolved by now.

**Comment by DylanC** [comment]
@peanutbutterandcrackers - Yep, I can't produce this either.
