### ISSUE TITLE
Unable to run latest release source zip

### ISSUE THREAD

**Issue by beppe9000** [OpenShot/openshot-qt#3023]
**Describe the bug:**
I tried to run OpenShot using the command provided in the readme.md file without success.
I thought it was nice to run from source since I have python installed but I think I will use the installer for now...

**Steps to reproduce the behavior:**
1. I downloaded latest source release
2. Unzipped it with 7zip in my downloads folder
3. Open a terminal window in the resulting folder
4. used the command in the readme (removing the '3' and made sure it's python3)

**Expected behavior:**
No exceptions thrown. Program starts.

**System Details:**
- OpenShot Version:. 2.4.4
- Operating System / Distro: Windows Server 2016

**Exception / Stacktrace:**
![image](https://user-images.githubusercontent.com/6625123/65834598-d540ff80-e2dc-11e9-93ec-ac749e5ba288.png)

**Comment by ferdnyc** [comment]
@beppe9000 OpenShot is not a pure-Python program, it requires the `openshot` extension module (which is compiled from the [libopenshot](https://github.com/OpenShot/libopenshot/) Python bindings). The installer installs those files as well. Without libopenshot and the Python bindings installed, OpenShot cannot function.

**Comment by ferdnyc** [comment]
@beppe9000 That's called the installer. They're even pre-downloaded! :laughing:
