### ISSUE TITLE
Adjusting audio level of a single audio track

### ISSUE THREAD

**Issue by FinixFighter** [OpenShot/openshot-qt#3035]
Description: It would be very useful to have the possibility of adjusting the audio level of a sound track in multiple points of the track. In some video editors this is called "audio ducking".

Possible solution: It would be nice to have an horizontal line on an audio track that can be distorted (dragging it up or down) so that the volume of that particular point of the track will be higher or lower.

![audio ducking](https://user-images.githubusercontent.com/19877271/66346676-f3e56d00-e952-11e9-8b50-0a6d9835304c.png)
For instance, when you add a track to the timeline you will see something like what is in the top track (in the image). Then you can click on the line for creating a point that you can drag up or down. In the bottom track you can see that mutiple points have been created. By doing so you will be able to modify the volume of a track as you want! In a very simple way!

**Comment by ferdnyc** [comment]
You can do that today. Volume is a property of the track data, and it can be keyframed just like any other property. There's no graph of the level adjustments, but the current level at each frame is displayed in the Properties view, regardless whether it comes from a keyframe (green) or an interpolation (blue).

Simply move the playhead to each point on the clip where you want to set a keyframe, and either:
* Right-click on the Volume row and choose "Add Keyframe" (to set a keyframe at the current volume level, useful at points before and after you want to make adjustments)
* Modify the Volume level at that point, which will create a keyframe to set the volume to that level. The level will be interpolated between keyframe points, a curve icon at the right end of the volume level display lets you adjust the curve function on both sides of the point.

**Comment by ferdnyc** [comment]
(And I'm guessing by the rewrite of this report from its original form, that you discovered the "Add to timeline" dialog in the context menu of the Project Files window, for adding multiple images to the timeline.)

**Comment by ferdnyc** [comment]
Closing as answered, feel free to reopen if you need additional info.
