### ISSUE TITLE
Crash CPU hits 300%

### ISSUE THREAD

**Issue by timlefkowitz** [OpenShot/openshot-qt#304]
This looks like the best video editor for linux. My video came out great but its hard for me to preview and export. the program crashes so much. I just want to export my video :( hits 80% and boom my work is gone :(

**Comment by PanderMusubi** [comment]
When it crashes and you restart it, is it in the first restart also without tracks. but after directly closing and restarting again, the tracks are also there again?

**Comment by DylanC** [comment]
@timlefkowitz - Do you have this issue on the latest version v2.3.4?

**Comment by DylanC** [comment]
Try OpenShot v2.4. The preview is much better and no lag detected in my testing.
