### ISSUE TITLE
Openshot crashes on launch

### ISSUE THREAD

**Issue by gbbbbb** [OpenShot/openshot-qt#3049]
So recently, whenever I tried to open Openshot, the screen would be white for a few seconds then crash, even after reinstalling 2 times i still have this problem, please help.

**Comment by ferdnyc** [comment]
@gbbbbb Most likely there's a backup file causing trouble in your user directory, reinstalling won't clear that out.

My recommendation would be to rename or delete the entire `.openshot_qt` directory in your home dir, which is usually found at:
* <code>/home/<var>username</var>/.openshot_qt</code> under Linux
* <code>/Users/<var>username</var>/.openshot_qt</code> on MacOS
* <code>C:\Users\\<var>username</var>\\.openshot_qt</code> on Windows 

You may have to enable "Show hidden files" to see it.

**Comment by ferdnyc** [comment]
Oh, P.S: If you're seeing issues with OpenShot's GUI displaying, it wouldn't hurt to restart the computer, as well.

**Comment by gbbbbb** [comment]
It worked! Thank you so much!
