### ISSUE TITLE
Add feature support to Wikipedia

### ISSUE THREAD

**Issue by PanderMusubi** [OpenShot/openshot-qt#305]
Please, add detailed feature support to Wikipedia, preferably with references to where that particualr feature is documented. See https://en.wikipedia.org/wiki/Comparison_of_video_editing_software

**Comment by jreynojustin** [comment]
@PanderMusubi this is for code issues only. Please refer to our website to provide such Feedback or also feel free to change it since Wikipedia is editable by anyone.
