### ISSUE TITLE
Animated title not working with 2.80 blender in mac Mojave os.

### ISSUE THREAD

**Issue by 2mailram** [OpenShot/openshot-qt#3053]
**Describe the bug**

**Steps to reproduce the behavior:**
1. Go to 'title->animated tile'
2. Click on 'select tiltle'

**Expected behavior**

**System Details**
- OpenShot Version: 2.4.4
- libopenshot Version:  0.2.3
- Platform: Darwin-18.7.0-x86_64-i386-64bit
- Processor: i386
- Machine: x86_64
- Python version: 3.6.4
- Qt5 version: 5.5.1
- PyQt5 version: 5.5.1
- Qt Detected Languages: ['en-IN']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.4.4-dev2-1572293466-00fe96f6-0eb5fb46-x86_64.dmg

**Log Files**
- http://logs.openshot.org/ylw5afnleefl8nzefrjv925wrqlvxe48/openshot-qt.zip
- http://logs.openshot.org/ylw5afnleefl8nzefrjv925wrqlvxe48/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by 2mailram** [comment]
Animated title not working state

**Comment by ferdnyc** [comment]
Duplicate  of #2901. Blender 2.80 was released after OpenShot 2.4.4 and is not compatible. Using 2.80 currently requires running one of the Daily Builds available at https://openshot.org/download/
