### ISSUE TITLE
Crash When Exporting Some Videos.

### ISSUE THREAD

**Issue by ianbarton** [OpenShot/openshot-qt#3056]
I am experiencing crashes when exporting, some video projects.  This happens whatever format or profile I select. Crash normally happens around 50-60% complete. Logs attached.

I am using Openshot V2.2.4 on Arch Linux.

[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/3793385/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/3793386/openshot-qt.log)

**Describe the bug:**

**Steps to reproduce the behavior:**

**Expected behavior:**

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.
Log files can be found in your HOME/.openshot_qt/ folder. Please compress or zip
the log files (as they can become quite large).

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please
attach a small snippet of the exception here, but please keep it as small as
possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them here, dragging-and-dropping into this form, or clicking below and loading
images saved to your computer. All images are public, so please don't post screenshots
containing personal information.

**Comment by ctsdownloads** [comment]
@ianbarton is this still an active issue for you? Thanks

**Comment by ianbarton** [comment]
No longer am issue as I have stopped using OpenShot.
