### ISSUE TITLE
Custom Export Dialog Presets - Folder Path, Bit Rate etc. from the GUI

### ISSUE THREAD

**Issue by Twenkid** [OpenShot/openshot-qt#3058]
**Describe the new feature and the solution:**
1. Store and reuse the last used configuration of the Export Dialog, the content of the edit boxes etc. May have a button for returning to default (folder, file name)
2. Save Custom Presets of these configurations and allow for easy reuse - possibly add to the "Simple" tab. E.g. "High 20M" etc.
3. Folder Path and File Name to be combo boxes, in order to allow for easy access to different folders.

**Describe the solution you'd like:**
Buttons, combo boxes...

* I found that issue "Creating a new Preset": https://github.com/OpenShot/openshot-qt/issues/2924
However it's regarding the MXF format and ffmpeg, while my request is just for saving the content of the dialog.

**Comment by mikelacsa** [comment]
Thanks for this enhancement idea. This is noted.

**Comment by Twenkid** [comment]
BTW, I found that the ideas were requested earlier as:
* Video Export - favorite formats + remember last selection https://github.com/OpenShot/openshot-qt/issues/1586
