### ISSUE TITLE
Distinct saturation per color

### ISSUE THREAD

**Issue by mkarg** [OpenShot/openshot-qt#3060]
**Describe the new feature:**
OpenShot has a saturation effect. There is *a single* slider for saturation.

Other picture and video editing software is able to change saturation *by color*, i. e. it has *distinct* sliders for R/G/B, and animate them separately. This allows to improve the visual quality of poor shots, even dynamically (like having a shot start in Day/Summer setting and gradually turn into Night/Winter setting).

**Describe the solution you'd like:**
Saturation effect should have distinct sliders for R/G/B. Each slider should be animated.

**Describe alternatives you have considered:**
* Custom effect for the Day/Night setting.
* *Scriptable* effect (e. g. JavaScript given by users instead of hard-coded algorithm).

**Comment by mikelacsa** [comment]
Thanks for this enhancement idea. This is noted.

**Comment by mkarg** [comment]
In fact I already coded it and it works well. As soon as I manage to test it on Windows (besides Ubuntu) I will open a PR. :-)
