### ISSUE TITLE
It won't take my file as if it is invalid but it is a valid file.

### ISSUE THREAD

**Issue by M8TRIXgames** [OpenShot/openshot-qt#3064]
*Describe the bug:**
I am trying to upload a .mp4 file from my SLOBS recording software but it is saying the file is invalid.

**Steps to reproduce the behavior:**
Unknown

**Expected behavior:**
My .mp4 file should be a valid loadable file.

**System Details:**
- OpenShot Version 2.4.4
- Operating System Windows 10

![Screenshot for github](https://user-images.githubusercontent.com/57340105/68100765-c7603a80-fe97-11e9-9c8d-5516d703c4ff.png)

**Comment by SuslikV** [comment]
Please add to your report the _MediaInfo_ (https://mediaarea.net/MediaInfo) of the file in .txt format.

**Comment by M8TRIXgames** [comment]
Ok. But, I am a complete noob to this and I don't know what this does or how to use it.

**Comment by SuslikV** [comment]
Please, type the `MediaInfo` into YouTube search and look how to use it (to view media properties of the media file).

**Comment by mikelacsa** [comment]
@M8TRIXgames 

I would like to follow up if you can share the MediaInfo here?
