### ISSUE TITLE
openshot: openshot-qt.ee - exeption failfast

### ISSUE THREAD

**Issue by mouarfff** [OpenShot/openshot-qt#3066]
I have very often this error and it's happend when i make a save (or when there is an autosave in 30-80% frenquency).

Windows 10 64b pro 
OpenShot-v2.4.4-dev2-1571901451-3f5370a8-0eb5fb46-x86_64

**Comment by ferdnyc** [comment]
..._What_ error? Please include screenshots, logs, or whatever other information you can provide about the error you're experiencing. We can't see your screen.

**Comment by mouarfff** [comment]
The error message is in the title of my bug repport.

It's appear in a windows classic message box when a save is made

**Comment by mikelacsa** [comment]
@mouarfff are you still experiencing this?

If so, can you provide a screenshot?

**Comment by mouarfff** [comment]
`http://pix.toile-libre.org/?img=1574003903.png`

**Comment by mouarfff** [comment]
also in this version :
OpenShot-v2.4.4-dev2-1573705363-c2713520-12a15298-x86_64.exe

**Comment by mikelacsa** [comment]
Thanks, @mouarfff

**Comment by mikelacsa** [comment]
![image](https://user-images.githubusercontent.com/37053994/71140574-94f27d00-224c-11ea-802b-c2dba7b8b357.png)
@ferdnyc for your reference.
