### ISSUE TITLE
Tutorial Window become resized

### ISSUE THREAD

**Issue by joshen48** [OpenShot/openshot-qt#307]
The tutorial just open the window so diminished

**Comment by JtLively** [comment]
Please elaborate.

**Comment by chrismark** [comment]
I think they mean the tutorial resizes the window or puts it in minimized state maybe.
Same thing in my case (win10, openshot2.2.0). 
Clicking close hides the tutorial. But once I click on the main window, the main window gets resized.
Only goes away if you finish the tutorial. There was one time the tutorial popped up again somehow. And I only got it to go away by finishing it.

**Comment by JtLively** [comment]
Got it. I just realized yesterday that I'm using an old version - 1.4.3. But its stable, unlike the 2.2.0 I tried and had a similar issue.

**Comment by DylanC** [comment]
How do I make the tutorial show in v2.4?

**Comment by JtLively** [comment]
@DylanC In the menu bar select "Help" > "Tutorial

**Comment by peanutbutterandcrackers** [comment]
@ferdnyc - I just had this thought that maybe - just maybe - if I got you to take a look at this bug, in about a week or so, you'll submit a PR that actually resolves this issue.

**Comment by ferdnyc** [comment]
Huh. I have to admit, after testing, that I'm surprised this happens in Linux as well (since it was first reported on Windows). Yet, it does.

However, I have to also admit that I don't really care. So the tutorial doesn't run fullscreened. That's a problem why?

**Comment by DylanC** [comment]
@ferdnyc - I think why it has a particular set size/dimensions is to select accurate coordinates for the popup bubbles to appear. It may become more difficult to place them if the app is full screen. (depends on users monitor resolution etc)

**Comment by peanutbutterandcrackers** [comment]
Because some YouTuber has got a review of OpenShot where the reviewer points out that OpenShot hasn't even fixed this small problem yet. Plus, it'd be really neat if the tutorial window didn't resize anything. I personally think that this issue is worth resolving. Because I don't want to see my favourite video editor receiving negative reviews on YouTube. *liek if you cri evritym* :D
