### ISSUE TITLE
combining  Split clips with speed 2x or 4x broke all edition

### ISSUE THREAD

**Issue by Erikcht** [OpenShot/openshot-qt#3071]
Combining  Split clips with speed 2x or 4x broke all edition.
I first cut a part at the beginning and cut a part at the end.
Then I set the speed to advance by 2x.
What happened was that he took a completely different part of the edit and still put it at normal speed overriding the entire edit.

Unfortunately for me to do my editing I had to resort to proprietary software.
But I come here to report this problem

- OpenShot Version 2.4.4
- Operating System / Distro: Windows 10

**Comment by SuslikV** [comment]
How you cut the clip parts?
I did a lot of splits of single clip and speed up different parts for different values. I didn't have any reset. Do you mean that you attempted to apply speed up of one value and then other one to the same fragment (double xN, where N= 2 and N= 4 )?

**Comment by mikelacsa** [comment]
No response after 7 days. Closing issue.

**Comment by Erikcht** [comment]
Hi, sorry by the delay, i was too much busy to aswer this week creating for my youtube channel.
I was creating an edit for a video.
Separating in 10 or 20 cuts my video.
I took these snippets that I wanted to be displayed, mutated this part, accelerated not by double xN, where N = 2, but N = 4 and N = 16.
