### ISSUE TITLE
I hear a noise as I cut frames on the track.

### ISSUE THREAD

**Issue by francisrod01** [OpenShot/openshot-qt#3072]
**Describe the bug:**
When I cut one part of the video down, *it loses the audio of the whole project*. It's possible to export as a video and I can hear the audio clearly.

> The current version installed doesn't work, so I got the Daily build and now I can do video editing so good!

**Steps to reproduce the behavior:**
1. Go to 'Open Project '
2. Click on 'Razor tool'
3. Select the time you want to cut down *(there's no range to choose, just one shot)*
4. Export the video
5. Try to reproduce the video again
6. Hear a noise when the cut part begins.

**Expected behavior:**
I expect to cut some parts and I could continue hearing the audio.

**System Details:**
- qt5-default (5.7.1+dfsg-3+deb9u1)
- OpenShot version 1.4.3 / *it doesn't have any log files*
- Linux Debian Stretch / # 1 SMP Debian 4.9.189-3+deb9u1 (2019-09-20)
- Daily Build OpenShot-v2.4.4-dev2-1573278881-c2713520-0eb5fb46-x86_64.AppImage

**Log Files:**

Daily Build logs [openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/3828519/openshot-qt.log)

Logs after install qt5-default and changing the original project:
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/3828570/openshot-qt.log)

**Screenshots:** (Optional)

![image](https://user-images.githubusercontent.com/4691768/68545204-8f7e5900-03a9-11ea-9c45-98f1523fadfa.png)

**Comment by mikelacsa** [comment]
Hi!

I just want to confirm if your problem was fixed when you used the daily build?

**Comment by francisrod01** [comment]
Hi @mikelacsa, I downloaded the last daily build right now to test it.
- Daily Build **OpenShot-v2.4.4-x86_64.AppImage** and the problem persists.
- I got a new log file: [openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/3836438/openshot-qt.log)

**Comment by mikelacsa** [comment]
Thanks for the update @francisrod01
