### ISSUE TITLE
Extend a Clip to Fill the Gap with a Command instead of dragging or Merge Subclips

### ISSUE THREAD

**Issue by Twenkid** [OpenShot/openshot-qt#3075]
**Describe the new feature:**

The use case is - slicing a clip in consecutive touching parts for muting or masking the audio, adding effects, A-B roll overlaying etc. Then you discover that something is not right and have to remove the sliced parts and do it again, when that editing is not recent for simple undoing.

It'd be convenient either to remove the wrong clips, select the left-most one and call:
1) **"Extend the clip to fill the gap"** or: 
To select all consecutive slices from the same original clip and call: 
2) **"Merge"** [with adjacent clips, cut from the same original video with preserved order]

The Merge would be possible also by selecting just one sub-clip of them, because that operation is reasonable only for such consecutive segments which are cut from the same video. That may imply that the system keeps track of such "sister clips" if the slicing parameters are not enough.

The command may require a choice of up to the next clip on the same track or on another/any track, or up to a marker.

**Describe the solution you'd like:**

A menu command or a button in a palette of commands.

**Describe alternatives you have considered:**

My current solution is to remove the wrong slices and to extend the left clip manually which is laborious - you may cover a bit the following clips and thus first move them right, or/and to zoom-in a lot to be precise in preserving the timing. 

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your request.

**Comment by ctsdownloads** [comment]
Appreciate the feature request, thanks for the great input.
