### ISSUE TITLE
Copy & Paste / Drag & Drop of Effects

### ISSUE THREAD

**Issue by mkarg** [OpenShot/openshot-qt#3078]
**Describe the new feature:**
Copy & Paste / Drag & Drop a customized effect from one clip to another.

**Describe the solution you'd like:**
CTRL-C copies the selected customized effect (i. e. the effect type with all its current custom settings including all key frames, hence the JSON) from a source clip into the clipboard. CTRL-V on a target clip applies the same effect type with the settings found in the clipboard (including the key frames). CTRL-X does the same as CTRL-C but additionally _removes_ the effect from the source clip.

Mouse can move a customized effect from source clip to target clip using drag & drop. Holding CTRL when releasing the mouse button will _copy_ instead of _move_.

**Describe alternatives you have considered:**
Manually copying setting-by-setting from source effect to target effect.

**Comment by SuslikV** [comment]
Unfortunately, even available code is not working (Copy/Paste over the Clip makes not editable Effect that keeps reference to parent Clip).
