### ISSUE TITLE
Export Selection - Select a Region from the Timeline to Export

### ISSUE THREAD

**Issue by Twenkid** [OpenShot/openshot-qt#3086]
**Describe the new feature:**

Possibility to select a timeline range or a set of ranges (eventually for many exports at once) and call "Export Selection". Alternatively, adding a review dialog like the one for cutting videos from the project files.

The goal is to avoid manual calculation of the frames when using Advanced Export settings.

**Describe the solution you'd like:**

Either use some selection markers as begin-end, a dialog similar to the preview and cutting dialog from the project files or another simple dialog.

**Describe alternatives you have considered:**

Currently when I want to export a selection, I calculate the frames. If there is a view/some indication of/around the timeline which displays plain frame numbers, given current profile, instead of time or time:frame, it would do similar job, but still the user would have to enter the numbers manually.

**Comment by MBB232** [comment]
Related to: https://github.com/OpenShot/openshot-qt/issues/3244

Would not the easiest way be to select time in stead of framenumbers in the advanced export dialog? As video noob I do not know why, but there may be a technical reason why you can only select a frame number. 

Searching on how to find the framenumber, found his awesome tutorial by AndrewBullen explained that you can add a dummy track and have the framenumber show up in the video screen. 
https://www.reddit.com/r/OpenShot/comments/g32m05/exporting_sections_and_frame_numbers/
It proves that the framenumber is calculated in realtime by Openshot, so theoretically you should be able to show it directly to the user, right?

A bit of un-used real estate left under the video player (Left and right of the buttons), where you could show the frame number. Or add a toggle between Show PT/CT/AFN/RFN 
(Project time, Clip Time, Absolute Frame Number/Relative Frame Number)

Alternative: If you can not do that, perhaps the Markers could be tagged and used for selecting start and end time of the export? (On the top menu bar, a dropdown menu could let you jump to chapter titles?)

And if Markers are taggable, maybe even export Markers to  chapter numbers if you want to. 
https://medium.com/@dathanbennett/adding-chapters-to-an-mp4-file-using-ffmpeg-5e43df269687		

![OpenshotMarker](https://user-images.githubusercontent.com/62191951/80667932-be47d300-8aa0-11ea-9467-5732fedf24e0.PNG)
