### ISSUE TITLE
Ordering tracks

### ISSUE THREAD

**Issue by PanderMusubi** [OpenShot/openshot-qt#309]
After a lot of editing, it could be practical to reorder tracks. Please ad a way to order tracks. Probably by grabbing them somewhere on the left under the name and pull-down menu.

**Comment by JtLively** [comment]
On the left side of the timeline, you can right-click the track and choose to move them up or down.

**Comment by Static2600** [comment]
I don't see a way to move the tracks up or down when right clicking on the left side of the timeline. There is a plus and a minus, but these are for inserting new tracks either above or below the current track. Am I missing something?

**Comment by JtLively** [comment]
Sorry. The steps above are for the older ~1.4.3 stable versions. The newer versions do not seem to have this feature.

**Comment by manotails** [comment]
Has this feature been resolved yet? I have version 2.4.3 installed and don't seem to be able to move any tracks up or down. PLEASE please can someone give me some good news?

**Comment by peanutbutterandcrackers** [comment]
@manotails - Sorry. This feature has not yet been implemented. We do not have enough contributors currently. However, I am going to re-open this issue and hopefully we can get this done in the future releases (perhaps a couple more before this one's implemented, though).

**Comment by worc** [comment]
still not seeing this feature in 2.5.1

**Comment by pbb72** [comment]
Please re-open this issue.  Re-ordering (and disabling) tracks would be a very welcome feature for composing videos.
