### ISSUE TITLE
huge performance issue

### ISSUE THREAD

**Issue by ThomasWaldmann** [OpenShot/openshot-qt#3090]
Something is very very wrong, see this full screen screenshot of a 3840x2160 display:

https://paste.thinkmo.de/je6vHUjR/+inline (click on the image to get a 1:1 scaling)

At the top right, you see the preview window.

At the bottom right, you see the ubuntu system monitor, showing a huge CPU load when displaying this simple slideshow of some pictures with simple transition effects, the display is not fluent, it is still jerky, sound is also jerky.

As you see, the overall load on the 32 logical cores is about 50-70%.

Machine specs:
- 2x Xeon E5-2667v2 (3.3 .. 4.0GHz, 16Cores / 32 Threads total)
- 128GB memory (mostly unused here)
- Nvidia GTX 1070, 8GB, Nvidia drivers
- PCIe x4 SSD 3GB/s transfer rate

**Steps to reproduce the behavior:**

Make a slideshow and have a big preview window.

**Expected behavior:**

Not burn that much CPU for a simple slideshow and still not being able to display fluent graphics and sound.

It should not take a monster machine like above for that. We also tried on a different machine with freshly installed ubuntu, only 4 or 8 cores and the load was even higher, the problem happening with a smaller preview window already.

With a very small preview window, the problem gets smaller and goes away below some very small (unusable) size.

**System Details:**
- OpenShot Version 2.4.1
- Operating System / Distro: Ubuntu 18.04 64 bit, all updates

```
         app:INFO openshot-qt version: 2.4.1
         app:INFO libopenshot version: 0.1.9
         app:INFO platform: Linux-4.19.69-x86_64-with-Ubuntu-18.04-bionic
         app:INFO processor: x86_64
         app:INFO machine: x86_64
         app:INFO python version: 3.6.8
         app:INFO qt5 version: 5.9.5
         app:INFO pyqt5 version: 5.10.1
```
**Screenshots:**

https://paste.thinkmo.de/je6vHUjR/+inline (click on the image to get a 1:1 scaling)

**Comment by ThomasWaldmann** [comment]
Note: I am not personally a openshot user, just gave friend Klaus the opportunity to try this on my machine as he was experiencing more severy performance issues on his less big machine.

**Comment by ThomasWaldmann** [comment]
BTW, are there more recent packages for ubuntu somewhere? I installed the stuff available from the stable ubuntu package source.

TODO:
- try to reproduce on current 2.4.4 appimage version, or
- try the ppa: https://www.openshot.org/ppa/

Release notes: https://www.openshot.org/blog/2019/03/20/openshot-244-released-keyframe-scaling-docking-and-more/

**Comment by dw-kw** [comment]
Hi Thomas,
here is your friend Klaus. Thanks for your issues.
Already I had installed on my desktop-PC openshot V2.4.4 and your described probs are the same and is not fixed unfortunatley.
Klaus

**Comment by ThomasWaldmann** [comment]
@dw-kw ah, ok. :-(

I had read the 2.4.4 changelog and it sounded somehow promising.

**Comment by ThomasWaldmann** [comment]
If it is not fixed and nobody even looked at the issue, there is no reason to mark it stale or close it.

**Comment by ThomasWaldmann** [comment]
See above.

**Comment by ThomasWaldmann** [comment]
see above.

**Comment by ThomasWaldmann** [comment]
well, obviously nobody gives a sh*t.
