### ISSUE TITLE
Common Scale parameter for both X and Y, not just two ScaleX and ScaleY

### ISSUE THREAD

**Issue by Twenkid** [OpenShot/openshot-qt#3092]
**Describe the new feature:**

A property "ScaleXY" which adjusts both X and Y, since this is the usual case, both are set to the same value.

**Describe the solution you'd like:**

A new parameter (property) "ScaleXY", linked to ScaleX and ScaleY which when enabled and adjusted sets both ScaleX and ScaleY.

**Describe alternatives you have considered:**

Manually adjusting first ScaleX, then ScaleY.

**Comment by N3WWN** [comment]
I like this, but what if there was an option for ScaleY to "Follow ScaleX" (or "=ScaleX", etc) or vice versa?  Instead of a new property field, this would pull the value of one from the other.

**Comment by Twenkid** [comment]
Right. That is like to lock/set the aspect ratio of the
selection/scaling/crop operations, so the selection is defined with one
side - two clicks.

На пт, 22.11.2019 г., 17:28 Richard Alloway <notifications@github.com>
написа:

**Comment by N3WWN** [comment]
Thanks for the bump, stalebot!

I don't recall the last time that I needed to adjust ScaleX and ScaleY independently... I *do* scale them both the same in almost every video.  Being able to scale the clip with a single property would reduce a great many mouse clicks and keystrokes per clip!

**Comment by Twenkid** [comment]
Yes, that independent scaling is rather a perverse design decision. Scaling
one param is "Shear" transform, which is rarely needed, unlike Scaling.
Titles usually/often need Scaling, because fonts seem not to change on
screen after changing their size in the dialog; the way to make them bigger
is with Scale + moving left-up accordingly.

I'm not using the latest version, if it was fixed, but the above were other
issues/bugs IMO, including the only way to position by entering numbers
manually, while there are no guiding number grid on the video - so it's
partially a guess work.

There could be a dialog or a mode with keys for more convenient adjustment
of the position and size with online refresh, because these are common
operations.

**Comment by N3WWN** [comment]
Confirmed that this is still needed in the most recent nightly build (April 26, 2021, 6:02 a.m.): https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.5.1-dev2-daily-7320-a00bbb76-503515e6-x86_64.dmg

**Comment by merinsky** [comment]
This would be very appreciated. Independent scaling is pain in the a**.

**Comment by N3WWN** [comment]
Still definitely needed...

**Comment by jonoomph** [comment]
Thanks for the suggestion. Currently, OpenShot comes with a `Transform` feature, which allows the user to scale both the `scale_x` and `scale_y` properties at the same time. It also allows for maintaining the aspect ratio (holding **CTRL** during scale), or allows the user to squish and stretch the clip (by not enforcing aspect ratio). As demonstrated in this video, it is quite simple, and quite powerful.

But for this to work, the actual property editor needs to allow for independent editing of these 2 properties. I'm open to suggestions of course.

https://user-images.githubusercontent.com/5551883/167318007-fc7183f9-75ee-47f7-8b8d-3b22033c8657.mp4

**Comment by N3WWN** [comment]
@jonoomph Is there a way to use `Transform` with specific values instead of trying to drag to get the exact numbers desired?

**Comment by JacksonRG** [comment]
@N3WWN If you double click on the value in the properties menu, you can input a number rather than drag.

Let me know if that helps, or if that wasn't the question you were asking.

**Comment by JamesRichards22** [comment]
I vote for this. I mean, there are lots of features I'd like to see and this is one of them. A lock between Scale X and Y would be best I think. Dragging from the corner might get me close, but it's always fiddly. I usually do that, and then adjust as needed.

Also, bump so robot doesn't close.
