### ISSUE TITLE
Cannot create info.THUMBNAIL_PATH. File already exists

### ISSUE THREAD

**Issue by techfreek** [OpenShot/openshot-qt#31]
As shown in the screenshot below, this happened the second time I tried to launch openshot. 

Windows 10 Home 64 bit. 8 gigs ram. Intel i7. Let me know if I can provide any more info.

![openshot](https://cloud.githubusercontent.com/assets/3945675/12298105/408ee3fa-b9c5-11e5-82ba-c267040076c6.PNG)

**Comment by jonoomph** [comment]
Hmmm. On launch, OpenShot "attempts to" delete the /.openshot_qt/thumbnail/ folder, and then recreate it. I'm guessing that some file was locked... and the folder could not be deleted... and then it tries to recreate the folder. I've added some exception handling around this code, to prevent future errors.

A work-around is to manually delete that folder (and see if you get any windows errors), and then launch OpenShot again. If it won't let you delete the folder, just reboot, and try that again. Next Windows release will contain this fix.  Thank!

**Comment by YoranSys** [comment]
On linux with this update i get same error. I need to delete folder before open my project.

**Comment by jonoomph** [comment]
I was just able to reproduce this bug. It happens when I try and open any project that contains thumbnails (which is just about all of them). Bug fixed! Thanks again.
