### ISSUE TITLE
Offer Flattr button for donations

### ISSUE THREAD

**Issue by PanderMusubi** [OpenShot/openshot-qt#310]
Please offer a Flattr button for donations via that platform for micropayments.

**Comment by JtLively** [comment]
As of now, your options are donation by Paypal and Patreon.
@jonoomph would have more info regarding the possibility of this on the website in the future. 

However, this will be closed as it doesn't pertain to the app, though we thank you for the suggestion and wanting to actively support the OpenShot project.
