### ISSUE TITLE
Rendered and File-Buffered Previews of short regions for Smooth Preview Playback with External Players

### ISSUE THREAD

**Issue by Twenkid** [OpenShot/openshot-qt#3101]
**Describe the new feature:**

Generation of short rendered clips for short previews of selected regions with an external player (ffplay etc.), without the need for laborious Export dialogs, file paths etc. Just select a region - eventually a library of preselected regions (between markers, between time marks), which are rendered in the background on demand, when the editor is not under heavy load etc.

Most of the time, the previews in the editor are needed in order to see and feel how the transitions look and are there blank frames or some bugs, how does the flow go, how the different segments change, is the editing pace and camera motion and dynamics right between the sequences, how the sound or music sync at particular points for music videos; how the sound changes between the adjacent clips, which are discontinuously recorded - so do you need to fix the sound and how etc.  

In most of the cases that affects only short regions at the time, sometimes just a few seconds, sometimes 15 or 30 seconds, where the highest quality is not needed at all, thus a complete render and preview are not needed for the most of the time. (I know there's buffering, but I don't think it works good enough currently, also sometimes there are bugs, the clips get parasite frames from another location and need to be replaced)

I suggest that this need for reviews only of short segments allows to generate automatically or semi-automatically, behind the scenes, just these short previews which the user can play smoothly with an external player, if the internal can't be improved enough.

The reason for that feature is the poor preview performance of OpenShot so far and lack(?) of an easy proxy-video editing mode. 

Another helpful feature would be again auto- or semi-auto generation of proxy videos which could go with another feature - the project may have not one, but two or three profiles: one for editing with the proxies, one for test exporting and one for the final production. In general, the full quality and resolution is rarely needed (worth the load for slow machines), except for complex precise effects.

The proxy videos could be generated by a command, which encodes the original quality videos once they are imported to the project - because the entire videos may be not needed, it would be handy if there is a dialog for a rough cut of the imported clips - related to the feature when cutting of the videos in the library, right-click (not the slicing in the timeline).

 ...

A partial work-around of the preview performance is shown in a link in the related issues - setting export settings in the Export dialog to mobile, which sets the preview quality during editing, but I don't know does it still work and is it enough, I will test later. (I've noticed that sometimes the preview quality goes down/video gets pixelated, without knowing why it did). 

On the other hand, these automatic prerendered preview videos could be either at low resolution or at high.

**Describe the solution you'd like:**
Options for generation of proxy, preview quality, preview-short-exports.

**Describe alternatives you have considered:**

Proxies could be done manually, by re-encoding all the source videos (with an ffmpeg script) and when done, replacing the files at the project location with the same-name files with the original resolutions etc.

This issue is related to: 

Smoother preview playback with proxies
https://github.com/OpenShot/openshot-qt/issues/1380

Is there anything like proxies or so in openshot because openshot crashes everytime while i am editing 4k video (i'm not using the fastest and newest computer ;-) 
https://github.com/OpenShot/openshot-qt/issues/1248

It is related also to:  "Render regions"
https://github.com/OpenShot/openshot-qt/issues/259

**Comment by ctsdownloads** [comment]
Appreciate the feedback and the feature request.
