### ISSUE TITLE
Time Freeze function not working for a video file but works for another

### ISSUE THREAD

**Issue by vilmes21** [OpenShot/openshot-qt#3104]
**Question:**
I'm editing a mp4 file. Right-clicked on the clip, "Time" - "Freeze" - "x seconds", but it is not freezing. I thought my editor has gone wrong, but when I imported another source video (also mp4 format), the freezing works fine. Why?

**System Details:**
- OpenShot Version: 2.4.4
- Operating System / Distro: MacOS Catalina

**Comment by mikelacsa** [comment]
Hi! can you share your log files here, please?
