### ISSUE TITLE
Draft Timelines for testing ideas without messing up the main timeline

### ISSUE THREAD

**Issue by Twenkid** [OpenShot/openshot-qt#3107]
**Describe the new feature and the solution:**
Draft Timelines for testing ideas and cuts without messing up the main timeline. 

**Describe alternatives you have considered:**
Everything is tested in the main timeline. When the project is complex, that involves a lot of scrolling, may require adding new top tracks.

**Comment by ctsdownloads** [comment]
Marked enhancement.
