### ISSUE TITLE
User manual content

### ISSUE THREAD

**Issue by ferdnyc** [OpenShot/openshot-qt#3108]
While glancing over the [Developers section of the User Guide](https://www.openshot.org/static/files/user-guide/developers.html#the-big-picture), I happened to notice this passage, in particular the first sentence of the second paragraph:

![UserGuide-Developer-ManyBugsQuote_1](https://user-images.githubusercontent.com/538020/69904835-c678d680-1379-11ea-8770-f6587b7af51d.png)

_\*cough\*_ **_Ahem..._**

![UserGuide-Developer-ManyBugsQuote_2](https://user-images.githubusercontent.com/538020/69904840-d690b600-1379-11ea-864b-1fd0f5a0290f.png)

While in some ways I appreciate the brutal honesty there, we should probably fix that.

More practically, I noticed there were places where the Guide directs the user to some directory location under `/.openshot_qt/...`, which is just _wrong_. (`$HOME/.openshot_qt/...` or `~/.openshot_qt/...`, sure, that's acceptable, and even correct outside of Windows. But `/.openshot_qt/` is a very different thing.)

All of which is to say, #2989 is still open, and would clearly benefit from some attention.

**Comment by N3WWN** [comment]
![](https://i.imgflip.com/1kxup2.jpg)

(Sorry, couldn't resist!)

**Comment by DylanC** [comment]
@ferdnyc - I'm still lurking in the shadows following this project btw. 😄 I remember at one point I was thinking @N3WWN would be a great person for Docs. I could see from his responses to issues that he has fantastic knowledge of OpenShot from a users perspective and has technical knowledge too. 👍

**Comment by ferdnyc** [comment]
Absolutely! Hell, if ego-stroking is fair game, it is obvious to anyone who interacts with @N3WWN that they are dealing with a hoopy frood who always knows where his towel is.
