### ISSUE TITLE
Animated Title - No transparency

### ISSUE THREAD

**Issue by jesseakc** [OpenShot/openshot-qt#311]
The still image title transparency works just fine.  However, the animated titles have a solid grey background and no transparency.  

Using Openshot Version 2.1.0 on  Linux Mint 18 'Sarah' Cinnamon 64-bit fresh install and Blender 2.76b

**Comment by jesseakc** [comment]
ui_util:INFO Initializing UI for Dialog
blender_model:INFO updating effects model.
     metrics:INFO Track metric: {'content-length': '35', 'status': '200', 'pragma': 'no-cache', 'expires': 'Mon, 01 Jan 1990 00:00:00 GMT', 'content-type': 'image/gif', 'cache-control': 'no-cache, no-store, must-revalidate', 'last-modified': 'Sun, 17 May 1998 03:00:00 GMT', 'age': '273828', 'access-control-allow-origin': '*', 'x-content-type-options': 'nosniff', 'content-location': 'http://www.google-analytics.com/collect?cid=6a8fefbd-ff2a-44e5-8e31-6aba122d8e44&av=2.1.0&tid=UA-4381101-5&ua=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&cd5=LinuxMint-18-sarah&aid=org.openshot.openshot-qt&cd4=5.5.1&cd=animated-title-screen&cd3=5.5.1&cd1=0.1.2&t=screenview&aip=1&ul=en&an=OpenShot+Video+Editor&cd2=3.5.1%2B&v=1', 'date': 'Mon, 05 Sep 2016 20:57:28 GMT', 'server': 'Golfe2'} (b'GIF89a\x01\x00\x01\x00\x80\xff\x00\xff\xff\xff\x00\x00\x00,\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x02D\x01\x00;')
blender_treeview:INFO File Name
blender_treeview:INFO Title
blender_treeview:INFO Extrude
blender_treeview:INFO Bevel Depth
blender_treeview:INFO Font Name
blender_treeview:INFO Bfont
blender_treeview:INFO Text Alignment
blender_treeview:INFO CENTER
blender_treeview:INFO Text Size
blender_treeview:INFO Text Width
blender_treeview:INFO Diffuse Color
blender_treeview:INFO Specular Color
blender_treeview:INFO Specular Intensity
blender_treeview:INFO Start Frame
blender_treeview:INFO End Frame
blender_treeview:INFO Animation Length
blender_treeview:INFO 2
blender_treeview:INFO 1
blender_treeview:INFO init_slider_values
blender_treeview:INFO sliderPreview_valueChanged: 1
blender_treeview:INFO sliderPreview_valueChanged: 125
blender_treeview:INFO btnRefresh_clicked
blender_treeview:INFO QThread Render Method Invoked
blender_treeview:INFO Blender command: blender -b '/usr/lib/python3/dist-packages/openshot_qt/blender/blend/slide_left_to_right.blend' -P '/home/jesseakc/.openshot_qt/blender/e8ef0065-7628-11e6-8f4e-000d096208dc/slide_left_to_right.py'
blender_treeview:INFO preview_timer_onTimeout
blender_treeview:INFO Blender render thread finished
blender_treeview:INFO onRenableInterface
blender_treeview:INFO QThread Render Method Invoked
blender_treeview:INFO Blender command: blender -b '/usr/lib/python3/dist-packages/openshot_qt/blender/blend/slide_left_to_right.blend' -P '/home/jesseakc/.openshot_qt/blender/e8ef0065-7628-11e6-8f4e-000d096208dc/slide_left_to_right.py'
blender_treeview:INFO Blender render thread finished
blender_treeview:INFO onRenableInterface
blender_treeview:INFO QThread Render Method Invoked
blender_treeview:INFO Blender command: blender -b '/usr/lib/python3/dist-packages/openshot_qt/blender/blend/slide_left_to_right.blend' -P '/home/jesseakc/.openshot_qt/blender/e8ef0065-7628-11e6-8f4e-000d096208dc/slide_left_to_right.py'
blender_treeview:INFO sliderPreview_valueChanged: 1
blender_treeview:INFO sliderPreview_valueChanged: 2
blender_treeview:INFO sliderPreview_valueChanged: 3
blender_treeview:INFO sliderPreview_valueChanged: 4
blender_treeview:INFO sliderPreview_valueChanged: 5
blender_treeview:INFO sliderPreview_valueChanged: 6
blender_treeview:INFO sliderPreview_valueChanged: 7
blender_treeview:INFO sliderPreview_valueChanged: 8
blender_treeview:INFO sliderPreview_valueChanged: 9
blender_treeview:INFO sliderPreview_valueChanged: 10

and so on...

**Comment by jonoomph** [comment]
Please test again with the latest daily build of OpenShot. I've merged in changes to the text alignment and the background transparency, and updated the minimum version compatibility to 2.78. I've tested all animation on Linux, Mac, and Windows with Blender 2.78 and everything works great.

Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot. _It might take a couple hours for the latest version to appear._

If you have other issues, please file additional bugs for each one. Thanks!
