### ISSUE TITLE
export crashes with profile HD 1080p 25fps (1920x1080) or profile HD 1080i 25pfs (1920x1080) (Give your bug report a descriptive title)

### ISSUE THREAD

**Issue by cometchaserde** [OpenShot/openshot-qt#3115]
**Beschreiben Sie den Fehler**
export crashes with profile HD 1080p 25fps (1920x1080) or profile HD 1080i 25pfs (1920x1080)

**Erwartetes Verhalten**
i expect a new video in 1920x1080

**Systemdetails**
- OpenShot Version: 2.4.4
- libopenshot Version:  0.2.3
- Platform: Linux-4.9.0-9-amd64-x86_64-with-debian-10.2
- Processor: 
- Machine: x86_64
- Python version: 3.4.3
- Qt5 version: 5.2.1
- PyQt5 version: 5.2.1
- Qt Detected Languages: ['de-DE']
- LANG Environment Variable: de_DE.UTF-8
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.4.4-dev2-1575675205-06e6de5c-12a15298-x86_64.AppImage

**Logdateien**
- http://logs.openshot.org/ipyyvhexqvwemqeb76mruva5jbrpsdpm/openshot-qt.zip
- http://logs.openshot.org/ipyyvhexqvwemqeb76mruva5jbrpsdpm/libopenshot.zip

**Ausnahme / Stapelverfolgung**
```No stacktrace found in log files```

**Comment by SuslikV** [comment]
This log looks like you run out of free RAM space during export. (you may try to clear the undo history, save the project, restart application, then open it again and start the export).
