### ISSUE TITLE
Stuttering preview playback when adding Effects

### ISSUE THREAD

**Issue by stuartbrand** [OpenShot/openshot-qt#3121]
Openshot 2.4.1 on Linux mint 19  
Intel i9 8 core 16 thread 5Ghz  
32GB Ram and 1TB Nvme

Import 1080p dashcam footage, plays back no problem in the preview.

Added the brightness and contrast effect to the clip. Previews pauses for half a second every second durring preview playback. Exporting the clip plays back normal.

Removing the effect resolves the preview playback issue.

**Comment by SuslikV** [comment]
It pauses for the non-cached parts of the video (blue line at the top of the Timeline) only?

**Comment by stuartbrand** [comment]
Yes, you are correct. When I begin the preview playback, there is a blue line that starts to appear above the played section. When I replay the parts with the blue line, the stuttering stops.

**Comment by SuslikV** [comment]
Probably, application is just slow. You may try to reduce number of threads to 1 by main menu _Edit>Preferences>Performance_ to see if it changes anything for you. And try latest daily build from the site https://www.openshot.org/download/  or even compile your own.

**Comment by mikelacsa** [comment]
@stuartbrand have you tried @SuslikV 's solution?
