### ISSUE TITLE
Cannot Open .osp file "invalid load key, '{'."

### ISSUE THREAD

**Issue by briannamu** [OpenShot/openshot-qt#3123]
I had an open shot file project and the next day I was unable to open it! I tried reinstalling the program, but it still will not open. I have even tried the daily build and deleting the log files, as Open Shot's website instructed when troubleshooting.

The message given when trying to open the file is:
![image](https://user-images.githubusercontent.com/58742718/70549250-7f3cd380-1b39-11ea-915c-f0dda1636b9b.png)

I will do anything to fix this issue. I can even attach the file into a zip if needed. Please, someone help me because I have spent hours onto this project.

**Comment by ferdnyc** [comment]
> But please do attach the project file to the transferred issue, it should be easy enough to fix up.

Also, having an example of a damaged project file will help us solve this problem, if we haven't already fixed it. (If the damaged file was originally created under OpenShot 2.4.4 release, it's likely the bug has already been fixed. But it can't hurt to make sure.)

**Comment by briannamu** [comment]
[100 reasons to go vegan.zip](https://github.com/OpenShot/openshot-qt/files/3946966/100.reasons.to.go.vegan.zip)
I am using Windows 10 and version 2.4.4

Hope this helps!

**Comment by ferdnyc** [comment]
Devs: This is a strange one. The `.osp` file is ~13MB, making it _look_ like an exploded history file, but on examination the file turns out to be truncated in the history block (causing the load error), and approximately 60-70% filled with zeroes! Everything past this point is `00` bytes:

![image](https://user-images.githubusercontent.com/538020/70567386-e0799c80-1b63-11ea-852b-0d2ff9be0024.png)

After trimming off the entire (truncated) `"history"` block (along with all of the empty space after) and adding on a `"version"` block, the file size is reduced from 13MB to 3.6MB, and it passes JSON validation:
```sh
$ ls -l 100\ reasons\ to\ go\ vegan\ \(part\ 2\)*
-rw-r--r--. 1 ferd ferd  13M Dec  9 19:29 100 reasons to go vegan (part 2) - Copy.osp
-rw-r--r--. 1 ferd ferd 3.6M Dec 10 15:47 100 reasons to go vegan (part 2)_REPAIRED.osp
$ tail -n10 100\ reasons\ to\ go\ vegan\ \(part\ 2\)_REPAIRED.osp 
    "progress": [],
    "history": {
	"undo": [],
	"redo": []
    },
 "version": {
  "openshot-qt": "2.4.4",
  "libopenshot": "0.2.3"
 }
}
$ json_verify -su < 100\ reasons\ to\ go\ vegan\ \(part\ 2\)_REPAIRED.osp
JSON is valid
```
@briannamu Here's the repaired file, it _should_ load in OpenShot for you, and hopefully everything is present and working, though without the media files I obviously can't test it. It's obviously much smaller than your original file [appears to be], but the only missing items hopefully are the stored undo history, not the project data.

[issue_3123_repaired.zip](https://github.com/OpenShot/openshot-qt/files/3947104/issue_3123_repaired.zip)

The way the original file was cut off and the blank space at the end is very strange, to be honest, and not something we've seen before. Two thoughts:

1. I notice that the filename ends in `- Copy`, is it possible there was an error copying the original file? (Probably **not**, as the error I got trying to load it into OpenShot was the same error you got. But I just want to rule that out.)
2. Is it possible the disk you were saving to ran out of space while OpenShot was saving the _original_ file, or while it was being transferred from one disk to another at some point? That's one scenario I can think of where the file might end up in the state it was in, with a long area of completely blank space at the end.

**Comment by SuslikV** [comment]
Always make intermediate backup copies of the project when working on something huge or complex. Do not use auto-saving features...

The file damaged due to history undo writing fault (special feature of OpenShot where each undo action is written into the project no matter of).

**Comment by ferdnyc** [comment]
> The file damaged due to history undo writing fault

I don't know that that's strictly true, or at least up until now we haven't seen any kind of bug that causes _blank_ space to be written to a file like that. It's _possible_, certainly, but it really seems to me like an out-of-space issue or something must've been involved.

Sure, you could say that if OpenShot _hadn't_ been saving history to the project, then the file would've been smaller and it wouldn't have gotten cut off, but that's kind of reductive. No matter how small the data, it can always run out of space on a disk.

**Comment by briannamu** [comment]
OH MY GOD THANK YOU! IT WORKS I LIERARLY CANNOT THANK YOU ENOUGH. 
Seriously thank you, I had a major panic attack from thinking I lost all my progress... If I was rich I'd give you $1,000 right now, swear to god. <3

**Comment by ferdnyc** [comment]
So, I put together some experiments. I converted the repaired project file into one I could load, by creating dummy files for all of the paths referenced in it. Then I created a small filesystem, one I knew would be too small to save everything, in a tempfile and mounted it:
```sh
$ df -h /mnt/testdisk 
Filesystem      Size  Used Avail Use% Mounted on
/dev/loop0      7.9M  160K  7.1M   3% /mnt/testdisk
```
Then I loaded the file into the latest OpenShot, and tried to resave it to the full disk.

Whether it ran out of space copying asset files, or saving the project file itself, OpenShot 2.4.4-dev2 noticed the full disk and displayed an error dialog:

![image](https://user-images.githubusercontent.com/538020/70581198-5ee63680-1b84-11ea-924f-3b6905163ae1.png)

Then I tried the same thing with OpenShot 2.4.4 release from the AppImage. Same result:

![image](https://user-images.githubusercontent.com/538020/70581337-e03dc900-1b84-11ea-9bc8-cc8ae58c0e9f.png)
(Wow, that icon is horrible.)


So, it could be that I'm wrong about the disk-full issue, as it seems that we'd at _least_ catch that when it happens. But this does mean that whatever happened to the project file is still a mystery, unfortunately. I suppose it could be an out-of-_memory_ error, storing the undo list in the first place. The project is **VERY** complex, my (underpowered) system has trouble even loading it.

**Comment by ferdnyc** [comment]
@briannamu Glad I could help! Good luck with the project. Given the complexity of what you've got there so far, I can't stress the advice @SuslikV gave enough: Backups, backups, backups.

I'm a little worried that you might run into trouble exporting under OpenShot 2.4.4, it has some memory issues that mean it will require a pretty beefy system to create a video from that project. If that's the case, you may need to install the latest daily build version and use it for export instead.

One caution, though: Right now projects saved from the Daily Builds aren't fully compatible with OpenShot 2.4.4 (the release version). So you'll want to keep a copy of the version saved from 2.4.4 as well, if you do go that route.

**Comment by briannamu** [comment]
Will do! Again, Thank you so much!

**Comment by ferdnyc** [comment]
(Oh, and if you've been doing a lot of editing to the project, **Edit > Clear history** is always a good idea right before a save, or an export. It'll free up a lot of memory, make the save file smaller, and make the export go faster.)

**Comment by Jorji-Costava** [comment]
Can you help me with mine as well? please, this is immensely important to me and I've put in lots of time to it
[MSS_Trailer.zip](https://github.com/OpenShot/openshot-qt/files/3969102/MSS_Trailer.zip)

**Comment by deanl3** [comment]
I have this same exact issue with the same invalid load key "{" Below is the .osp file if that helps. If anyone could help that would be great.
[TheGameAwardsSummedUp.zip](https://github.com/OpenShot/openshot-qt/files/3971156/TheGameAwardsSummedUp.zip)

**Comment by SuslikV** [comment]
@deanl3 try this one (change profile if needed, re-save it), maybe it will work for you: 
[TheGameAwardsSummedUp (2)_repaired.zip](https://github.com/OpenShot/openshot-qt/files/3973012/TheGameAwardsSummedUp.2._repaired.zip)

The project file is heavily damaged. Make backup copies during your work.

**Comment by ferdnyc** [comment]
@SuslikV @deanl3 

Hrm. Now this one is especially troubling:
1. Once again, no `"history"` at all, the JSON serialization aborts in the project data proper.
1. This time, the data successfully written was only 32,000 lines / 1.1 MB, much smaller than the previous two.
1. This time, the project media (based on the available JSON data, at least) consists solely of audio/video files, not still images.

We're actually getting **farther away** from a pattern. :confounded:  (Other than, I note, that all three damaged files so far have come from Windows users. That could possibly be significant, if the issue is somehow confined to the frozen Python implementation bundled with OpenShot.)

**Comment by deanl3** [comment]
Thank you so much @SuslikV I've been saving my projects quite frequently but never thought to make backups of the .osp files. I appreciate you getting back to me so quickly! @ferdnyc all I know is that when OpenShot stopped responding I simply closed the application and restarted my laptop. Every single time I just open back up my project and everything Is fine but this time it had that error. Once again thank you for such a quick response. I appreciate all the hard work!

**Comment by SuslikV** [comment]
@deanl3 the "stopped responding" was during: 1) preview playback, 2) timeline navigation, 3) keyframe edit 4) file add or 5) video export?

Is your auto-saving feature of OpenShot was enabled (main menu _Edit>Preferences>Autosave tab>Enable Autosave_) the last time?

**Comment by deanl3** [comment]
@SuslikV it was during a preview playback. It froze up but the audio kept going on the video. Also yes the auto save feature was enabled the last time.

**Comment by ferdnyc** [comment]
@deanl3 Mmm, if OpenShot froze up _during_ an autosave attempt, that's a definite possibility for how the file might've been corrupted.

The good news on that front is that the _current_ `develop` / Daily Build code includes new autosave logic, which first copies the **previous** save file to a recovery directory before overwriting it with the autosave. So, autosave should be a safer operation in the next release of OpenShot.

But with 2.4.4, given that it saves directly over the existing save file, I'd recommend turning it off. OpenShot will still write crash-recovery backups even with autosave turned off (and attempt to restore the recovery data on relaunch, if it finds a crash-recovery backup), and since those backups don't overwrite your existing project file they're actually the safer option for protecting against project data loss.

**Comment by deanl3** [comment]
@ferdnyc That might have been a possibility. I know whenever Openshot triggers an autosave the video playback freezes up/ buffers for a few seconds. I'll keep autosave off and make sure to create backup copies. I managed to finish the video which I'm thrilled about if you guys want to check it out. [https://www.youtube.com/watch?v=8k3bjNVGyis&t=2s](url)

**Comment by mikelacsa** [comment]
@deanl3 funny video! uhm...

**Comment by mikelacsa** [comment]
@ferdnyc can this ticket be considered solved and closed?

**Comment by ryanzguitarz** [comment]
I am having the same problem with the invalid load key on a project of mine. Can anybody help me? 
[Tour.zip](https://github.com/OpenShot/openshot-qt/files/4398417/Tour.zip)

**Comment by SuslikV** [comment]
@ryanzguitarz unfortunately, no useful datais left  in your project - it is completely damaged. If you are user of the v2.5.1 then you may try to find some copies on your PC (if any were made of course) - look for files with the `.osp` extension on the system drive.

Make backup copies time to time if you working on something huge.

**Comment by nodoambiental** [comment]
We have Ubuntu 18.04, a laptop Lenovo ideapad320, and OpenShot 2.4.1 and we have the same problem with "invalid load key '{'...". Unfortunately, we have not found a solution.

**Comment by Troprism** [comment]
I also have this issue 
![image](https://user-images.githubusercontent.com/66119093/83252164-57bbef00-a1dd-11ea-9519-26ada1db50d3.png)
I read this and also couldn't find a solution...
And I saved the file in .osp and I couldn't drag drop the file here so please help...

**Comment by SuslikV** [comment]
@Troprism Use 7-zip program and compress the file into `.zip` format first (to upload it here) or use google drive and post shared link to the file.

**Comment by Troprism** [comment]
https://drive.google.com/file/d/1kVxKcIauW2wZde4_cFanlHdAzRejW_kI/view?usp=sharing
Here you go hope this helps... Thanks

**Comment by SuslikV** [comment]
@Troprism Can you make the link available to everyone?

**Comment by Troprism** [comment]
Whoops sorry
https://drive.google.com/file/d/1kVxKcIauW2wZde4_cFanlHdAzRejW_kI/view?usp=sharing

**Comment by SuslikV** [comment]
@Troprism Repaired file:

[Quarantine Playz #2_repaired.zip](https://github.com/OpenShot/openshot-qt/files/4703045/Quarantine.Playz.2_repaired.zip)

about 43 KB to download, CRC of the `.zip` archive MD5:5B1F80023CF36A68421BDF56A0A82735717AD0AE

The project is huge. Should work well, but the project file is heavily damaged. Please, make backup copies during your work.

**Comment by Troprism** [comment]
Yeah i spent 2 weeks making that 
For sure Im gonna make backups for these from now on...
Thanksss so muchhh!!! 
Not all heroes wear capes 
Hope you have a good weekend!

**Comment by PO28** [comment]
Hello, I've had the same issue as the original post. 
[FOOTBALL CLIPS - Copy.zip](https://github.com/OpenShot/openshot-qt/files/4705049/FOOTBALL.CLIPS.-.Copy.zip)

**Comment by PO28** [comment]
> Hello, I've had the same issue as the original post.
> [FOOTBALL CLIPS - Copy.zip](https://github.com/OpenShot/openshot-qt/files/4705049/FOOTBALL.CLIPS.-.Copy.zip)

For context the application froze up on an attempt to save, I had to restart my pc afterwards, has too much memory built up in it?

**Comment by SuslikV** [comment]
@PO28 unfortunately, no useful data is left in your project - it is completely damaged. If you are user of the v2.5.1 then you may try to find some auto-backup copies on your PC (if any were made of course) - look for files with the `.osp` extension on the system drive.

Make backup copies time to time if you working on something important for you.

**Comment by PO28** [comment]
Will do, thank you regardless.

**Comment by Troprism** [comment]
> @Troprism Repaired file:
> 
> [Quarantine Playz #2_repaired.zip](https://github.com/OpenShot/openshot-qt/files/4703045/Quarantine.Playz.2_repaired.zip)
> 
> about 43 KB to download, CRC of the `.zip` archive MD5:5B1F80023CF36A68421BDF56A0A82735717AD0AE
> 
> The project is huge. Should work well, but the project file is heavily damaged. Please, make backup copies during your work.

Sorry to bother you again but now it keep saying that all my .svg (Titles) are gone but when I open the assets folder outside of openshot I can see all of my videos, effects and titles that I used... Is there anyway to tix this please?
1st picture stating the error message
![image](https://user-images.githubusercontent.com/66119093/83326893-252bf800-a2aa-11ea-92ee-b0e95e6f7a93.png)

2nd and 3rd picture stating that My titles etc etc are gone (in openshot)
![image](https://user-images.githubusercontent.com/66119093/83326915-47be1100-a2aa-11ea-89ed-0c2bc68f038e.png)
![image](https://user-images.githubusercontent.com/66119093/83326922-5c020e00-a2aa-11ea-86d6-7a6b44f0ef11.png)

4th picture stating that I actually still have the Titles etc etc (but outside of openshot)
![image](https://user-images.githubusercontent.com/66119093/83326933-7dfb9080-a2aa-11ea-9337-69b9ee28c9b3.png)

Sorry to bother again...

**Comment by SuslikV** [comment]
@Tropism the "thumbnails" is the folder that contains icons in `.png` format. This is not actual `.svg` source files. Look for the folder that contains actual files (with `.svg` extention).

The project file keeps only description (of layers compositions) and path to actual sources that are in use. So, you files are still in the folder of the broken project, like `Quarantine Playz #2_assets\title\` for `.svg` titles files or similar.

**Comment by mrtripledot** [comment]
> Devs: This is a strange one. The `.osp` file is ~13MB, making it _look_ like an exploded history file, but on examination the file turns out to be truncated in the history block (causing the load error), and approximately 60-70% filled with zeroes! Everything past this point is `00` bytes:
> 
> ![image](https://user-images.githubusercontent.com/538020/70567386-e0799c80-1b63-11ea-852b-0d2ff9be0024.png)
> 
> After trimming off the entire (truncated) `"history"` block (along with all of the empty space after) and adding on a `"version"` block, the file size is reduced from 13MB to 3.6MB, and it passes JSON validation:
> 
> ```shell
> $ ls -l 100\ reasons\ to\ go\ vegan\ \(part\ 2\)*
> -rw-r--r--. 1 ferd ferd  13M Dec  9 19:29 100 reasons to go vegan (part 2) - Copy.osp
> -rw-r--r--. 1 ferd ferd 3.6M Dec 10 15:47 100 reasons to go vegan (part 2)_REPAIRED.osp
> $ tail -n10 100\ reasons\ to\ go\ vegan\ \(part\ 2\)_REPAIRED.osp 
>     "progress": [],
>     "history": {
> 	"undo": [],
> 	"redo": []
>     },
>  "version": {
>   "openshot-qt": "2.4.4",
>   "libopenshot": "0.2.3"
>  }
> }
> $ json_verify -su < 100\ reasons\ to\ go\ vegan\ \(part\ 2\)_REPAIRED.osp
> JSON is valid
> ```
> 
> @briannamu Here's the repaired file, it _should_ load in OpenShot for you, and hopefully everything is present and working, though without the media files I obviously can't test it. It's much smaller than your original file [appears to be], but the only missing items hopefully are the stored undo history, not the project data.
> 
> [issue_3123_repaired.zip](https://github.com/OpenShot/openshot-qt/files/3947104/issue_3123_repaired.zip)
> 
> The way the original file was cut off and the blank space at the end is very strange, to be honest, and not something we've seen before. Two thoughts:
> 
> 1. I notice that the filename ends in `- Copy`, is it possible there was an error copying the original file? (Probably **not**, as the error I got trying to load it into OpenShot was the same error you got. But I just want to rule that out.)
> 2. Is it possible the disk you were saving to ran out of space while OpenShot was saving the _original_ file, or while it was being transferred from one disk to another at some point? That's one scenario I can think of where the file might end up in the state it was in, with a long area of completely blank space at the end.

Can I get some help with this issue plz. I'm in the middle of an important video edit and woke up with this problem on the project. Plz plz S.O.S help

**Comment by SuslikV** [comment]
@mrtripledot share your project file please.

**Comment by mrtripledot** [comment]
hey guy here it is

**Comment by SuslikV** [comment]
@mrtripledot the mails is only for notification - not for reply. The mail itself has recommendation (at the bottom) to reply directly from the github.com site. So, use the site if you want to say or share something.

**Comment by mrtripledot** [comment]
> @mrtripledot the mails is only for notification - not for reply. The mail itself has recommendation (at the bottom) to reply directly from the github.com site. So, use the site if you want to say or share something.


[New Yoppa.zip](https://github.com/OpenShot/openshot-qt/files/4738739/New.Yoppa.zip)
here it is

**Comment by mrtripledot** [comment]
> > @mrtripledot the mails is only for notification - not for reply. The mail itself has recommendation (at the bottom) to reply directly from the github.com site. So, use the site if you want to say or share something.
> 
> [New Yoppa.zip](https://github.com/OpenShot/openshot-qt/files/4738739/New.Yoppa.zip)
> here it is

dont ask me what happen to the old yoppa @_@

**Comment by mrtripledot** [comment]
> @mrtripledot the mails is only for notification - not for reply. The mail itself has recommendation (at the bottom) to reply directly from the github.com site. So, use the site if you want to say or share something.

<_<
>_>
<_<

**Comment by SuslikV** [comment]
@mrtripledot unfortunately, no useful data is left in your project - it is completely damaged. If you are user of the v2.5.1 then you may try to find some auto-backup copies on your PC (if any were made of course) - look for files with the `.osp` extension on the system drive.

Make backup copies manually time to time if you working on something important for you.

**Comment by allensutton** [comment]
Hi @SuslikV - I have the same issue and was trying to use GHex like you did to look at the binary, but I don't see the pattern of repeating zeros like you did.  I dual boot with Windows and Linux. The Linux version for 2.5.1 kept crashing and things of that nature (different issue entirely), so I downloaded it for Windows and was able to edit it.  However, exports stalled at about 53%, so I just decided to try and open the project in Linux and see if maybe it would export there, and now I get this error.  What am I looking for, exactly? The error seems to indicate malformed JSON, but I don't know how I would determine where the JSON became malformed.  Do you have any ideas? Here's my project file if you want to take a look:
[gradvideo.zip](https://github.com/OpenShot/openshot-qt/files/4740169/gradvideo.zip)

**Comment by SuslikV** [comment]
@allensutton Unfortunately, the OpenShot's project files not cross-platform interchangeable. The reason it crashes in Linux from saving in Windows - is different path to effects ("missing" Transition files, see: https://github.com/OpenShot/openshot-qt/issues/2735 ) that now are saved as absolute path in your project:

To resolve the OpenShot crash issue (`libstdc++-6.dll` or `libstdc++-6.so` lib crash on "load" action), just change all paths `C:\\Program Files\\OpenShot Video Editor\\transitions\\common\\` to `@transitions/common/`.

Example.
From:
```
"path": "C:\\Program Files\\OpenShot Video Editor\\transitions\\common\\fade.svg"
```
to:
```
"path": "@transitions/common/fade.svg"
```

The repaired file with transitions paths changed (no history):

[CA-2020-Grad-Video-2_repaired02.zip](https://github.com/OpenShot/openshot-qt/files/4741488/CA-2020-Grad-Video-2_repaired02.zip)

about 92 KB to download, CRC of the .zip archive MD5:BA76E36460D8EC731A325C7BD1130BF1

As for the "stuck at the some percentage" during the export - give to it more time, maybe the performed task is too demanding. Wait for 20-30 minutes (or so), if progress is still not moving - look at the same percentage on the Timeline - maybe scene can be simplified.

**Comment by allensutton** [comment]
Thanks @SuslikV - that at least appears to have fixed that particular issue.  But being that the issue is really just a problem I encountered while trying to work around my main issue, which is the stalling of the export, I kept trying to find a solution to that one in the meantime.  My project would always stall around 53% or so.  I noticed in one of your other posts on a different issue that you indicated that the percentage directly coincides with the spot on the timeline where the problem likely is.  With that in mind, through trial and error by pulling segments of the project into their own projects and attempting to export, I think I've identified the exact spot where the problem is.  After some research, I believe it's related to the issue described in the comments of #3126 where OpenShot seems to have issues with projects that contain a lot of still images. Would it be helpful to comment on that issue and add my project file, or do you recommend opening a new issue entirely?

**Comment by SuslikV** [comment]
@allensutton disable auto-saving feature of OpenShot (in _Preferences_) and monitor amount of RAM that is in use during the _Export_. And report the bug separately.

**Comment by sarynahlawy** [comment]
Hi @ferdnyc were you able to solve this issue at all? The same just happened in my project and I copied the file tried looking into the it's hex code but it was all 00 :S . Do you mind having a look I might be missing something here https://drive.google.com/file/d/13Lpg8Mp0TavcifEWdTfi71_f2oPw1Fdk/view?usp=sharing 

TIA

**Comment by SuslikV** [comment]
@sarynahlawy your project file is completely damaged.

Make backup copies manually time to time if you working on something important for you.

**Comment by Claustica** [comment]
Hello, here's something a bit new for this, I'm a mac user who just had this issue. Honestly I have no ideal how to change the .osp into a .zip on Mac so an explanation to that would be great as well and due to me using Mac would I have to restart the project altogether?

**Comment by Claustica** [comment]
I did a bit more testing and it seems that the only file that's causing this is this audio file, I went through a series of the files in the video and only this one alone gave the error message, the file name is

Link's Memories - "Despair".mp3

I'm not sure why this file kills the edit and causes an error but hopefully that helps

**Comment by xn3ep** [comment]
I've been working on this for many hours, and I saved it quite a few times. However, I over-wrote my previous file every time I saved it. When I was finally completed with it, I saved it one last time and started exporting it. While it was getting imported, a person shut down my computer, and when I tried to open the save file, I got the same error. I've attached the file.

[Openshot Work.zip](https://github.com/OpenShot/openshot-qt/files/4967638/Openshot.Work.zip)

**Comment by Claustica** [comment]
I already redid and remade my project that got corrupted, but I hope my data still helps, have a good day and thank you for helping people here to recover what they've lost!

**Comment by xn3ep** [comment]
> I already redid and remade my project that got corrupted, but I hope my data still helps, have a good day and thank you for helping people here to recover what they've lost!

I'm glad that you've provided the data, but I'm still not quite sure what to do. Could you help me recover my project?

**Comment by xn3ep** [comment]
Can you please help me get my file back? I worked hard on it and really need it back.

[Openshot Work.zip](https://github.com/OpenShot/openshot-qt/files/4975420/Openshot.Work.zip)

**Comment by xn3ep** [comment]
Please?

**Comment by xn3ep** [comment]
I'm waiting for someone to help me with my file. If someone can help me, I'd appreciate it, but if not, then please inform me so I can get over it and do the work again.

**Comment by Claustica** [comment]
Alright man, listen. I don't know how to fix it, if I did I wouldn't have remade my video. The people who (by looking at the thread) fixed other peoples projects haven't done one in awhile. I'd recommend you go through your project and look for a problem file that corrupted it and turn that in so if they do return they might try to decipher this and help other people, but for now I'd recommend you get ready to buckle down and do the video again

**Comment by BakiHanma18** [comment]
I also find myself having this issue. I've already gone into a Binary Code Editor and deleted all of the zeros at the end, but I'm not sure as to what to do beyond this. Does anyone know what to do? This is the file by the way
[Kan vs Kak.zip](https://github.com/OpenShot/openshot-qt/files/5100239/Kan.vs.Kak.zip)

**Comment by oolong** [comment]
I'm having the same problem. Interestingly I got this on one project file, started again with the same video, saved it and got the same problem (strongly regretting that I didn't export it in between). I've attached the file with the extension changed to .txt to suit GitHub's sensibilities.

I see that running it through DuckDuckGo's JSON validator suggests

> Error: Parse error on line 31:
> ... "path": "./Daisy /"Giggling Babelfish\"
> -----------------------^
> Expecting 'EOF', '}', ':', ',', ']', got 'undefined'

It looks like maybe it's upset by the use of " marks in a file/directory name? This is in Linux Mint, btw.
[Giggling Babelfish edit.txt](https://github.com/OpenShot/openshot-qt/files/5743521/Giggling.Babelfish.edit.txt)

**Comment by zedzee** [comment]
Guys - I am experiencing the same error message ("**invalid load key. '\x00'** ") but mine happened after my machine seemed to freeze and I was forced to turn it off and on again, to recover it, as all else seemed to fail.

So now when I try to open my project, I get above message.

I've attached the .OSP file in the home that someone might be able to help me fix it please?

Note, I'm fairly new to OpenShot and not a JSON expert, so hope someone can guide me through any fixes that I may need to apply.

[C4S_CloudMeetup_01.zip](https://github.com/OpenShot/openshot-qt/files/6160328/C4S_CloudMeetup_01.zip)

**Comment by anabocafe** [comment]
Hello, I'm having the same issue, but only with one project that I was about to finish. The error that I have is this: Failed to load project file : invalid load key, '{'.

Can somebody help me please to recover it? It's super short but I spend a lot of time in made this project, it's about 8min.

I'll attach it here. Thanks a lot!
[Open shot project anabocafe.zip](https://github.com/OpenShot/openshot-qt/files/6266885/Open.shot.project.anabocafe.zip)

**Comment by jenmtl** [comment]
Hello! I'm having the same issue, "invalid load key, '{'" with a short video (<1 min), after manually saving and closing OpenShot for the night.  I have been saving this project manually all along and have turned off autosave after reading this thread. 

The project is here: 
[BooleanA4.zip](https://github.com/OpenShot/openshot-qt/files/6863459/BooleanA4.zip)

Does anyone have any suggestions on how I might be able to recover it? Thanks so much!

**Comment by JacksonRG** [comment]
@jenmtl Do you mean you had turned off autosave before your project became corrupted?

**Comment by JacksonRG** [comment]
@jenmtl I did some work in fixing this project file. It seems there were some strings had `"` marks in the middle of them.

I think this is because one of your title files have `"`, `*`, and `?` in them. I will probably make sure the program doesn't allow users to make these.

I think this still has errors, but I'm working on it.
[BooleanA4.zip](https://github.com/OpenShot/openshot-qt/files/6881838/BooleanA4.zip)

**Comment by ChrisPixi** [comment]
Hello,

I encounter a weird issue with an .osp file that seems valid from a JSON point of view but not for OpenShot.
The project loads correctly, no error, timeline is okay, editing looks fine too.
But nothing is displayed in the preview pane and hitting the "play" button causes OpenShot to crash.

This started to happen after the application hanged for quite some time and I had to kill it.
I have looked for potential automatic backups but could not find any :(.
I believe the autosave feature, combined with me killing it lead to the corruption of the file.

I have been working a fair amount of time on this project and was quite close to completion.
I also spent a few hours troubleshooting this but not much luck so far.
Any help or hint will be greatly appreciated.

Please find below the corrupted project file along with debug logs.
[OSP crash.zip](https://github.com/OpenShot/openshot-qt/files/7071611/OSP.crash.zip)

**Comment by lavib** [comment]
Hello, I have a related issue: 
![image](https://user-images.githubusercontent.com/3630521/135163264-07fa4ee8-b95a-4588-b542-6431e3c10eb9.png)

The Json seems to be valid:
[Début diapo.zip](https://github.com/OpenShot/openshot-qt/files/7247196/Debut.diapo.zip)

But I don't find any way to open it with OpenShot :(

Any help appreciated !

**Comment by JacksonRG** [comment]
@lavib Is that occurring on Openshot 2.6.0, or 2.6.1? I know of one particular cause for that bug, which I recently wrote a fix for.

**Comment by gbrea** [comment]
The same thing happens to me since version 2.6.1, in ubuntu 22.04.
The `título.osp` file is not opened by double clicking, but it is opened from the program interface.
If I rename the file and the associated folder to `titulo.osp`, without any special character (accents, ç, etc.), it does open normally.

These characters change them to `??` when trying to open from console

`INFO main_window: File not found at Documentos/t??tulo.osp`

**Comment by JacksonRG** [comment]
@gbrea That does sound like a somewhat different issue. But it's a very interesting one. I just tried it, opening a file with a special character from my file explorer.

Next I'm going to see if any files open in their default applications properly if named this way. Then I can find if the issue is in the file explorer, or in how openshot gets the file name. I'll keep you posted.
