### ISSUE TITLE
Openshot crashes instant when opening a project on another PC

### ISSUE THREAD

**Issue by bybyle** [OpenShot/openshot-qt#3129]
**Describe the bug:**

**Steps to reproduce the behavior:**
1. Go to 'OPEN'
2. Click on 'the file'

**Expected behavior:**
I did a montage on my big PC yesterday, and I tried to move it to my laptop to see if my teacher would be able to open it. The answer was no. When I try to open the project, Openshot just open and close without saying anything.
I have the exact same file, that I send me on Facebook, that works. So why on works and the other no? 

Attached you will find the logs from both projects.

Thanks in advance !

**System Details:**
- OpenShot Version 2.4.4
- Operating System / Distro: Windows 10

**Log Files:**
Log files from the project I can't open : 
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/3977338/openshot-qt.log)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/3977339/libopenshot.log)

Log file from the project I can open : 
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/3977341/openshot-qt.log)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/3977342/libopenshot.log)

**Comment by SuslikV** [comment]
The project files of OpenShot weren't designed for exchange or long-time backup. It's working files to work with it right now until video export is done, that's all. You may experiment with the main menu _File_ import/export instead (daily builds of OpenShot has limited support for some external formats, https://www.openshot.org/download/).
