### ISSUE TITLE
Extend zoom level to one step extra

### ISSUE THREAD

**Issue by PanderMusubi** [OpenShot/openshot-qt#313]
At the moment the maximum zoom level is 8 seconds. Please extend that to 4 seconds. Optionally, let the used add in Preferences the minumum and maximum zoom level. Optionally, store zoom level per project to override what is set in Preferences.

**Comment by PanderMusubi** [comment]
At the moment, I really need zoom level to go to 4 seconds. If there is a workaround, please let me know.

**Comment by gebeleixis** [comment]
if u are on windows the last git builld has max zoom 1 sec http://releases.openshot.org/windows/OpenShot-v2.1.0-17-ge64e4b4-49-587-x86_64.exe

**Comment by DylanC** [comment]
@PanderMusubi - This will be tracked in #160
