### ISSUE TITLE
Anonymize contents in openshot_qt file

### ISSUE THREAD

**Issue by jjsjjs** [OpenShot/openshot-qt#3133]
**Describe the new feature:**
The openshot_qt file contains to much personal information.
So one has to anomize it before submitting it, a lot of work

**Describe the solution you'd like:**
Openshot should anomize all filenames and (sub)foldernames in the qt log file, because they can contain personal info. I believe this is a GDPR issue.

**Comment by ferdnyc** [comment]
@jjsjjs Certainly not a GDPR issue for local storage, nothing personally identifiable is uploaded anywhere except at the user's request. And in fairness the log file will pretty much always contain data that someone could argue is personal information. Even if file paths were anonymized (which would already take a fair amount of work) there are track labels, file tags, custom profile Iabels, etc...

But it's a reasonable suggestion, so I'll leave this open. Maybe someone will feel motivated.
