### ISSUE TITLE
audio stutters

### ISSUE THREAD

**Issue by jjsjjs** [OpenShot/openshot-qt#3134]
audio stutters when on another track is a simple image.
You can't choose audio drivers like ASIO or change buffers which could help a lot.
Has noting to do with a weak pc or something, mine is fast enough and doing a lot of audio stuff

**Comment by ferdnyc** [comment]
@jjsjjs Are you referring to issues in the preview, or exported video? What OpenShot version? What OS? (I can assume Windows from your mention of ASIO, but being explicit is far more helpful in a bug report.)

ASIO actually is supported if you compile libopenshot-audio yourself, unfortunately I don't think we're allowed to distribute builds with ASIO compiled in.

The main problem is buffering, ultimately. I'm hopeful OpenShot/libopenshot#416 will help.

**Comment by jjsjjs** [comment]
Thanks for replying to this issue.
Yes it's on WIn10-64bits, Openshot 2.4.4. The issue is in the software itself when editing.
I will test again and see if i can use what you've mentioned.

**Comment by jjsjjs** [comment]
i now tested Openshot 250 Release candidate, and it seems greatly improved. Thank you very much!
