### ISSUE TITLE
Can't open Inkscape for Titles if Inkscape is installed via the Microsoft Store

### ISSUE THREAD

**Issue by ZingBlue** [OpenShot/openshot-qt#3136]
**Describe the bug:**
OpenShot can not find Inkscape if it is installed through the Microsoft Store.

**Steps to reproduce the behavior:**
If you have Inkscape installed via the Microsoft Store (https://www.microsoft.com/store/productId/9PD9BHGLFC7H), in OpenShot, if you press CTRL + T to open the title templates, then select a title and click "Use Advanced Editor", it will say "Please install Inkscape to use this function."

**Expected behavior:**
It should open Inkscape, and allow the user to edit the title template.

**System Details:**
- OpenShot Version: 2.4.4
- Operating System: Windows 10, 64 Bit

**Comment by SuslikV** [comment]
Is there anything set in main menu _Edit>Preferences>General tab>Advanced Title Editor (path)_ of the OpenShot? If not - try to specify the path to Inkscape's `.exe` file manually.

**Comment by mikelacsa** [comment]
![image](https://user-images.githubusercontent.com/37053994/71327988-e94a7500-254a-11ea-8998-398f3b8af252.png)

**Comment by ZingBlue** [comment]
Hello, sorry for the late response, I was rather busy yesterday. Once I put the file location in
``C:/Program Files/WindowsApps/25415Inkscape.Inkscape_0.92.4.0_x64__9waqn51p1ttv2/VFS/ProgramFilesX64/Inkscape/inkscape.exe``
it says this:
``Please install C:/program files/windowsapps/25415inkscape.inkscape_0.92.4.0_x64__9waqn51p1ttv2/vfs/programfilesx64/inkscape/inkscape.exe to use this function``

**Comment by SuslikV** [comment]
This is virtual environment path. It wouldn't be supported any time soon, I think. If someone has access to modern Windows system can confirm or deny this. It's just my own assumption based on some experience. I hope you have installed the OpenShot in some regular folder...

Anyway, please, look for other solutions.

**Comment by mikelacsa** [comment]
@ZingBlue 

Can you tell us what happens when you go to the windows run dialog (Windows key + R) and paste the path for your inkscape and run it?

Please send us screenshots of the result.

**Comment by ZingBlue** [comment]
![image](https://user-images.githubusercontent.com/23709367/71537706-b569a980-28d4-11ea-85f1-8473d4eb3fc7.png)
@mikelacsa Maybe it is an issue with Windows perms too.

**Comment by ferdnyc** [comment]
Yeah, I can't say I'm surprised this doesn't work. I'm not sure how MS Store apps are distributed, but just based on the path contents I agree with @SuslikV — the location points to a virtual environment that probably isn't even accessible until Inkscape is launched and it gets mounted from whatever archive/container format the application is distributed in.

But, Windows still must be _able_ to open Inkscape even when the container's not mounted (by mounting it first, of course), for instance when the user double-clicks an SVG file with Inkscape set as their default SVG editor. In theory, if we could tap into that same functionality, we could launch the containerized Inkscape the same way.

Unfortunately, [this answer](https://superuser.com/a/1071343/12106) to a similar SuperUser question regarding store-app file associations makes me believe that the methods Windows employs for doing so are largely black magic.

I mean, `ActiproSoftwareLLC.562882FEEB491_2.5.17.17_neutral__24pqs290vpjk0` (or `25415Inkscape.Inkscape_0.92.4.0_x64__9waqn51p1ttv2` for that matter) is bad enough, but then the file association is `".conf"="AppXea46y3k4tynme684q1dgefbnb0b9r8ec"`, and it's stored at `[HKEY_CURRENT_USER\SOFTWARE\Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppModel\Repository\Packages\ActiproSoftwareLLC.562882FEEB491_2.5.17.17_neutral__24pqs290vpjk0\App\Capabilities\FileAssociations]
`!??! This is clearly not data intended for human consumption. :confused:

**Comment by eda1-fiunam** [comment]
> Hello, sorry for the late response, I was rather busy yesterday. Once I put the file location in
> `C:/Program Files/WindowsApps/25415Inkscape.Inkscape_0.92.4.0_x64__9waqn51p1ttv2/VFS/ProgramFilesX64/Inkscape/inkscape.exe`
> it says this:
> `Please install C:/program files/windowsapps/25415inkscape.inkscape_0.92.4.0_x64__9waqn51p1ttv2/vfs/programfilesx64/inkscape/inkscape.exe to use this function`

I can confirm this same issue with flatpak OpenShot on Linux Mint. The program doesn't recognize the /bin/inkscape path, and it says I need to install it.

And when I look for inkscape using the search file window, even when I've chosen /bin/inkscape I get this path:

/run/user/1000/doc/78dad9d7/inkscape.

A different issue, but strong related, it happens the same with codecs.
