### ISSUE TITLE
Update PPA to add support for Ubuntu 19.10 and 20.04

### ISSUE THREAD

**Issue by MycroftHolmes1989** [OpenShot/openshot-qt#3143]
Currently, Openshot Stable PPA has support for upto Ubuntu 19.04. I would request you to add support for Ubuntu 19.10 and 20.04 LTS beta.

**Comment by ferdnyc** [comment]
I won't even pretend to understand how Ubuntu packaging works, I know that the _official_ Ubuntu repos (through 20.04) still [seem to be packaging 2.4.3](https://launchpad.net/ubuntu/+source/openshot-qt) which is still occasionally the source of confusing bug reports. But for anything else (the stable/daily PPAs) AFAIK @jonoomph is the only one with access to make any changes there.

cc: @jonoomph
