### ISSUE TITLE
unable to open openshot : old file missing

### ISSUE THREAD

**Issue by andreabisello** [OpenShot/openshot-qt#3146]
long time ago i created a video with openshot.
now this video don't exists anymore.
openshot will search for this file,
i'm not able to say openshot "stop asking for this video"
beucase i cannot quit this workflow
![image](https://user-images.githubusercontent.com/2149815/71483015-ef1faf00-2805-11ea-8680-ba4ca2548e3e.png)
i updated to openshot 2.4.4 64bit on a updated windows 10,
but still stalled.
i'll remove and reinstall.

**Comment by andreabisello** [comment]
uninstalling and reinstalling openshot doesn't solve the problem : the only way is to create a fake video with the same name openshot is searching for and open this folder.

**Comment by SuslikV** [comment]
If this error rises right after the application startup, then please, find `.openshot_qt` folder on your PC and look for the filename inside each file (skip logs and images, of course).

Also, if you share the OpenShot's log-file it may help to look into what was happened.

**Comment by blacchat** [comment]
share logs and the .osp?

**Comment by andreabisello** [comment]
log attached.
you can search for "20191210_092736.mp4" inside the log.
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/4007894/openshot-qt.log)

**Comment by SuslikV** [comment]
log shows that your OpenShot constantly crashing and thus attempts to find the mentioned file that is still stored in `backup.osp`. You may try to move it to other folder to see if it helps.

**Comment by andreabisello** [comment]
the problem for me is not to restore the video, video was deleted, and to solve the problem i created a fake video with the same name. the problem is the UI : i was not able to exit this loop

**Comment by SuslikV** [comment]
Did you tried to move the `backup.osp` file to the other location?

**Comment by andreabisello** [comment]
Im not able ti reproduce the problem now , i exit the loop creating a fake
file with the correct name

Il Dom 29 Dic 2019, 17:32 SuslikV <notifications@github.com> ha scritto:

**Comment by Jayotis** [comment]
This has happened to me and I have lost work.  I have 2 video files I cut up and rearranged.  While attempting to playback the finished product the interface would lock in play mode with none of the control functions working(pause, change play position, move the slider, ect)  Also save was greyed out like I had already saved.  I restarted the program and tried to load the project but it kept asking for "u2013 Process Steps.mkv"  I do not have that file.  I was not able to close the program.  I made a fake file to get around the condition but I have to recut one of the videos. 
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/4200537/openshot-qt.log)

**Comment by SuslikV** [comment]
@Jayotis Make backups of your project files during the work.
Find the `.osp` files on your PC that has the `u2013 Process Steps.mkv` string in it, and just remove this `.osp` files.

**Comment by Jayotis** [comment]
> @Jayotis Make backups of your project files during the work.
> Find the `.osp` files on your PC that has the `u2013 Process Steps.mkv` string in it, and just remove this `.osp` files.

Thank you for the reply.  I'm not sure what files I should backup.  I dropped 2 videos in for edit, made some cuts, made some moves then hit play.  As I said, it locked up the controls, it runaway in play mode, couldn't save. Happened again today, but I waited it out and regained control after the whole video played out and was able to save and export.  The finished product is not great but finished in time.

**Comment by SuslikV** [comment]
@Jayotis I did rewrite my previous post. If you editing something huge - it is wise to save the project files (`.osp`) manually time to time and disable auto-saving in preferences of OpenShot.

The second part of the issue (missing file) can be solved by removing any auto-backups that OpenShot did before. In your 5 opened sessions of OpenShot - 2 were shutdown ungracefully (40% times!). And program just tries to recover the backups (were old media file is still mentioned).

**Comment by Jayotis** [comment]
> @Jayotis I did rewrite my previous post. If you editing something huge - it is wise to save the project files (`.osp`) manually time to time and disable auto-saving in preferences of OpenShot.
> 
> The second part of the issue (missing file) can be solved by removing any auto-backups that OpenShot did before. In your 5 opened sessions of OpenShot - 2 were shutdown ungracefully (40% times!). And program just tries to recover the backups (were old media file is still mentioned).
> 
> **Edit:** I just noticed, @Jayotis your issue is similar to #3227 because the `u2013` is single symbol (not from English alphabet) of the actual filename. I thought that you just give to the file this strange name, like year or so.

Thank you for the explanation.  Yes I inferred the symbol to be a tag of some sort and part of the clip tracking methods.  I also wondered if it pointed to a deleted clip that never got processed out of the list.

**Comment by gitmich** [comment]
The latest version has a problem if there are non-ascii character in the file path location or file name.
Thanks developers provide this good software. Could developer help to check the process of parsing material path in the .osp project file when there contain non-ascii character?
thanks very much.

**Comment by SuslikV** [comment]
> I tried daily build OpenShot-v2.5.0-dev1-1582091950-fe8ea216-836e49fa-x86_64.AppImage. The problem is still existed.

@gitmich developers are aware of the problem: https://github.com/OpenShot/openshot-qt/pull/3229

**Comment by SuslikV** [comment]
@gitmich can you try new daily build of OpenShot?
https://www.openshot.org/download/#daily to check if the the issue was solved for you. Any changes?

**Comment by ferdnyc** [comment]
The OpenShot 2.5.1 release (now available at https://openshot.org/download/) contains a fix for the project-file encoding bug present in OpenShot 2.5.0. The new release will also recognize and auto-repair damaged encoding, when opening OpenShot 2.5.0 project files.

All OpenShot 2.5.0 users are strongly urged to upgrade to OpenShot 2.5.1 ASAP. After upgrading, it's further recommended that you open any projects previously saved from OpenShot 2.5.0 and re-save them, which will correct any encoding issues that may be present.

**Comment by gitmich** [comment]
> @gitmich can you try new daily build of OpenShot?
> https://www.openshot.org/download/#daily to check if the the issue was solved for you. Any changes?

@SuslikV  Dear Sir,
I tried OpenShot-v2.5.1-dev2-1583451229-f1e5c9c8-0d8d639e-x86_64.AppImage . it's working well on the Unicode character path and file name. But it still has a problem when open the older version project. I notice the material path format of the older project is "assets/\u6a19\u984c\u6a94\u6848\u540d\u7a31-1.svg" , it's different with newer version project.
This is working fine when reading the project file which made by the new version app.
Thank you very much.

**Comment by ferdnyc** [comment]
@gitmich 

If you open the project file containing `"assets/\u6a19\u984c\u6a94\u6848\u540d\u7a31-1.svg"` in OpenShot 2.5.1, does it not correctly load the title files? The JSON data loader in 2.5.1 should be able to convert `\uXXXX` entities into Unicode (and it will automatically fix `/uXXXX` entities that may have been saved by 2.5.0).

Would you be able to provide an example of a project file that doesn't load correctly in 2.5.1? We'd like to correct the issue if at all possible.
