### ISSUE TITLE
My project file is dammaged, so project isn't loaded

### ISSUE THREAD

**Issue by MIKADO38** [OpenShot/openshot-qt#3147]
hello,
After a crash, My project file is dammaged, so project isn't loaded
an error:  NoneType object is not subscriptable ?
videos, music and photos are read but the timeline is empty 

Is it possible to recover my project ?
Best regards
[Ecosse 3new.zip](https://github.com/OpenShot/openshot-qt/files/4003249/Ecosse.3new.zip)
[openshot_qt.zip](https://github.com/OpenShot/openshot-qt/files/4003254/openshot_qt.zip)

**Comment by SuslikV** [comment]
Take this (about 42KB to download):
[Ecosse 3new_repaired.zip](https://github.com/OpenShot/openshot-qt/files/4005032/Ecosse.3new_repaired.zip)

CRC of the .zip archive MD5: 5F34B4EEE71F6766701CC822A6BC7332

The fault is in the `"clips"`section of the file, `null` object at the end (line 55115).

**Comment by MIKADO38** [comment]
Hello,
the project works properly
thank you so much
it's very nice of you
regards,

**Comment by SuslikV** [comment]
Please, time to time make backup copies when working on something important for you.
