### ISSUE TITLE
 (Give your bug report a descriptive title)

### ISSUE THREAD

**Issue by Fredietone** [OpenShot/openshot-qt#3148]
![pantallazo](https://user-images.githubusercontent.com/59277731/71507707-b1fb0180-2885-11ea-8715-140f998b47aa.png)
**Describa el problema**

**Pasos para reproducir el comportamiento:**
1. Ir a «...»
2. Pulsar en «....»
3. Desplazarse hasta «....»
4. Ver el error

**Comportamiento esperado**
Una descripción clara y concisa de lo que esperaba que sucediera.

**Detalles del sistema**
- OpenShot Version: 2.4.4
- libopenshot Version:  0.2.3
- Platform: Windows-10-10.0.18362
- Processor: Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
- Machine: AMD64
- Python version: 3.6.4
- Qt5 version: 5.9.1
- PyQt5 version: 5.9
- Qt Detected Languages: ['es-ES', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.4.4-dev2-1577331825-a1158ee2-12a15298-x86_64.exe

**Archivos de registro**
- http://logs.openshot.org/n0glalc42eknzfw5pvnibo0p7nim33if/openshot-qt.zip
- http://logs.openshot.org/n0glalc42eknzfw5pvnibo0p7nim33if/libopenshot.zip

**Excepción / Rastreo de pila**
```No stacktrace found in log files```

**Capturas de pantalla** (Opcional)
Si se aplica, añada capturas de pantalla para ayudar a explicar el problema. Puede incluir capturas
copiando y pegando en GitHub o arrastrando y soltando en la página de GitHub. Todas las imágenes
son públicas y por tanto no debería publicar capturas que contengan información personal.

**Comment by SuslikV** [comment]
Click `OK` and in the next dialog window that appear on the screen locate the missing file manually.

**Comment by Fredietone** [comment]
> Click `OK` and in the next dialog window that appear on the screen locate the missing file manually.

Thankyou, after that comeback to ask the same, always looking for files. That is not normal

**Comment by SuslikV** [comment]
If location to the source files changes than there is nothing to do but locate each file manually.

Did you swap the drive for new one or have changed something else in your PC? (the last media file in the posted log-file has different drive letter)

**Comment by Fredietone** [comment]
Hi, It happened when i worked with my laptop and the file was created in PC. now I also have the problem on the pc. i did´nt anything

**Comment by SuslikV** [comment]
Does it matter? Navigate each missing file manually and save project again to other file.

For the transfer between PCs and different OSes people usually use export/import of file projects. Unfortunately, only daily builds of OpenShot has some support for the feature (limited support) and own project files (`.osp`) is not yet good for the transfer itself.

**Comment by Fredietone** [comment]
Ok, I did it. i was finding every file and open the project file .osp
Thank you very much for all :). Next time I will use the import / import function

**Comment by speedytechdev** [comment]
Hi @Fredietone it seems your issue has been fixed. I am going to close this issue but if you are still having problems please reopen the issue.
