### ISSUE TITLE
All of my tracks cannot be moved anymore and my transitions just disappeared

### ISSUE THREAD

**Issue by JomariAlexMP** [OpenShot/openshot-qt#3150]
**Describe the bug:**
So I'm making a video for a song mashup that I'm gonna post in my channel. In my project, I previously had no problem with organizing my clips and tracks. and only experience the typical lag and crash issues. But now, for some reason, I can't seem to move any of my tracks placed in the timeline anymore. Instead of the typical red outline that appears when clicking a track, it turns to a yellow outline instead. The Properties don't seem to appear anymore when I double-click a track, and would only appear if I click the arrow button on the track. Moreover, I have a lot of transitions on my current project, but the "blue-color" design of my transitions just disappeared (eventhough playing the videos still show that the transitions are still there).  For my last issue, I do still can add new videos from my Project Files to my timeline, but they automatically go to the front of Track 1, and even if you place a track in, let's just say Track 10, the track would still go to Track 1.

**Steps to reproduce the behavior:**
Issue 1.) When trying to select a track in the timeline, it cannot be moved/dragged anywhere. (Red outline indicating a track being selected is instead a yellow outline.)
Issue 2.) Double-clicking a track doesn't make the Properties appear, and can only be accessed through a track's arrow button.
Issue 3.) Adding any new track, from the Project Files, to the timeline automatically places it at Track 1 of the timeline.

**Expected behavior:**
1. I should be able to move tracks in the timeline.
2. Double-clicking tracks should make the Properties appear.
3. Adding new tracks should be placed on the specific track it is put on.

**System Details:**
- OpenShot Version [e.g. 2.4.4]: 
- Operating System / Distro: Windows 10, 64-bit, Version 1903

**Log Files:**
I don't think this is a crash problem since it did not crash for me(?)

I already checked out some posts with (I think?) a similar problem with mine, but nothing worked for me. I'm going to attach a google drive link of the zip file containing the .osp file and videos/audios I used. I apologize if it's a large file but I hope my project can still be fixed since I really don't want 2 weeks of work wasted.

Here's the link:
https://drive.google.com/file/d/14ghdWVgeYibs5l_Yjxjmarqk-zQl8_q1/view?usp=sharing

**Comment by SuslikV** [comment]
The project file is damaged. Look for the `null` objects inside or share the one that someone will be able to fix it for you.

**Comment by JomariAlexMP** [comment]
@SuslikV What do I do with the null objects inside? I saw in another thread that the guy removed all of the lines that contained "null". I did that in a copied file and it just produced an error prompt saying that the project now had an invalid key and can't be opened.

**Comment by SuslikV** [comment]
Some values are legit to be null. When you removing `null` itself (not the whole string) you should look if it is part of the dictionary object or just a value - for example, if you see:
```
"effects": [
        {
                some_data_here
        },
        null,
        {
                some_data_here
        }
]
```
this is 3 objects inside the `effects` separated by commas. The middle one is just a `null`. You should remove the null word and comma next to it to get the 2 valid objects separated by commas:
```
"effects": [
        {
                some_data_here
        },
        {
                some_data_here
        }
]
```
if you see only
```
                "partial": false,
                "type": "update",
                "old_values": null,
```
then it is OK. The value here may be null.
