### ISSUE TITLE
View source tracks to adjust transition point

### ISSUE THREAD

**Issue by bryren** [OpenShot/openshot-qt#3151]
**Question:**
Working on compositing 2 video streams. Working to add transitions.
I want to see what each channel is offering and the preview pane.
Preview shows the potential output. I can fade the top channel, or add a transition.
I will not get the transitions in the correct position and want to see what the other channel has to offer.

**System Details:**
- OpenShot Version 2.4.1
- Operating System : Linux Mint 19.3

**Comment by SuslikV** [comment]
Where you want them to show preview? Each in separate window?

If there will be feature to _skip/hide the track_ - temporary disable (remove from the rendering) all clips from the selected track. Will it be enough for you? I assuming that both of your clips lies on different tracks.

**Comment by bryren** [comment]
Yes, two tracks, aligned in time, each input in a separate window. I dropped the audio from one track.
If I have 2 video tracks that are aligned for time and I want to switch back and forth between, I do not see how to play director. How to position the transition or cut.

After entering this question, I noticed that my tracks did not stay in alignment. I had good alignment early in the stream, but very shortly, they drifted apart. I did not see a timing (clock) adjustment.

**Comment by SuslikV** [comment]
> ... I noticed that my tracks did not stay in alignment. I had good alignment early in the stream, but very shortly, they drifted apart...

I think it is part of the other issue: https://github.com/OpenShot/openshot-qt/issues/2808 

Try to zoom-in to 1 second and align all objects manually again (do not move the clips at any other level of zoom!). No other workaround is known.


>... I did not see a timing (clock) adjustment.

Feature simply not exist (yet). OpenShot is not very complex application, if you demanding more - you may need to look at other solutions as well.
