### ISSUE TITLE
Garbage pixel column

### ISSUE THREAD

**Issue by stefan-reich** [OpenShot/openshot-qt#3152]
Hi, I get this mysterious slim garbage pixel column (it changes, too) on the right side of my video.

[Screenshot.](http://botcompany.de/1004590/raw/1102823)

Nothing fancy in the input, straight transcoding of a full-screen video actually.

This is OpenShot 2.4.1 on Linux with, I believe, the mpeg4 encoder.

What's going on?

**Comment by SuslikV** [comment]
This one is similar to https://github.com/OpenShot/openshot-qt/issues/2053

The input's width is not multiply of 32 (I recommend 32 instead of 8 or whatever).

**Comment by stefan-reich** [comment]
I see. Could this not be made into a warning in the software?
