### ISSUE TITLE
Crash on drag and drop from explorer

### ISSUE THREAD

**Issue by kurkosdr** [OpenShot/openshot-qt#316]
When I attempt to drag and drop any file from Windows Explorer to OpenShot, a crash happens.

Video of what I did to crash OpenShot can be found here:
https://youtu.be/9jat5x1hz2o

The file starring in the video: 
[https://drive.google.com/open?id=0B1xkSWvhG63eRDNjU0xpQ0syV1k](https://drive.google.com/open?id=0B1xkSWvhG63eRDNjU0xpQ0syV1k)

OS is Windows 10 Home 64-bit.

I also attach some logs and the settings file below. If there is any way to provide a better crash dump, let me know.

[libopenshot.log.txt](https://github.com/OpenShot/openshot-qt/files/457509/libopenshot.log.txt)
[openshot.settings.txt](https://github.com/OpenShot/openshot-qt/files/457510/openshot.settings.txt)
[openshot-qt.log.txt](https://github.com/OpenShot/openshot-qt/files/457511/openshot-qt.log.txt)

**Comment by lasercar** [comment]
This causes a crash in Mac 10.10.5 as well.

**Comment by psyca** [comment]
Can confirm for Linux (Mageia 6 - Cauldron)

[psyca@localhost ~]$ openshot-qt 
Loaded modules from installed directory: /usr/lib/python3.5/site-packages/openshot_qt
      launch:INFO ------------------------------------------------
      launch:INFO    OpenShot (version 2.1.0)
      launch:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.1.0
         app:INFO libopenshot version: 0.1.2
         app:INFO platform: Linux-4.8.1-desktop-1.mga6-x86_64-with-mageia-6-Cauldron
         app:INFO processor: x86_64
         app:INFO machine: x86_64
         app:INFO python version: 3.5.2
         app:INFO qt5 version: 5.6.1
         app:INFO pyqt5 version: 5.6
    language:INFO Qt Detected Languages: ['de-DE', 'de']
    language:INFO LANG Environment Variable: de_DE.UTF-8
    language:INFO LOCALE Environment Variable: de_DE
    language:INFO Attempting to load qt_de_DE.UTF-8 in '/usr/share/qt5/translations'
    language:INFO Attempting to load qt_de in '/usr/share/qt5/translations'
    language:INFO Attempting to load qtbase_de_DE.UTF-8 in '/usr/share/qt5/translations'
    language:INFO Attempting to load qtbase_de in '/usr/share/qt5/translations'
    language:INFO Attempting to load qt_de_DE.UTF-8 in '/usr/lib/python3.5/site-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load qt_de in '/usr/lib/python3.5/site-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load qtbase_de_DE.UTF-8 in '/usr/lib/python3.5/site-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load qtbase_de in '/usr/lib/python3.5/site-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load de_DE.UTF-8/LC_MESSAGES/OpenShot in '/usr/lib/python3.5/site-packages/openshot_qt/locale'
    language:INFO Attempting to load de/LC_MESSAGES/OpenShot in '/usr/lib/python3.5/site-packages/openshot_qt/locale'
    language:INFO Successfully loaded de/LC_MESSAGES/OpenShot in '/usr/lib/python3.5/site-packages/openshot_qt/locale'
    language:INFO Exiting translation system (since we successfully loaded: de_DE.UTF-8)
project_data:INFO Setting default profile to HDV 1080 25p 1920x1080
         app:INFO Setting font to /usr/lib/python3.5/site-packages/openshot_qt/images/fonts/Ubuntu-R.ttf
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
         app:INFO Setting custom dark theme
    language:INFO Attempting to load qt_de_DE.UTF-8 in '/usr/share/qt5/translations'
    language:INFO Attempting to load qt_de in '/usr/share/qt5/translations'
    language:INFO Attempting to load de_DE.UTF-8/LC_MESSAGES/OpenShot in '/usr/lib/python3.5/site-packages/openshot_qt/locale'
    language:INFO Attempting to load de/LC_MESSAGES/OpenShot in '/usr/lib/python3.5/site-packages/openshot_qt/locale'
    language:INFO Successfully loaded de/LC_MESSAGES/OpenShot in '/usr/lib/python3.5/site-packages/openshot_qt/locale'
link SVGID_18_-5 hasn't been detected!
link SVGID_18_-5 hasn't been detected!
link SVGID_22_-5 hasn't been detected!
link SVGID_24_-2 hasn't been detected!
link SVGID_24_-2 hasn't been detected!
     ui_util:INFO Initializing UI for MainWindow
     ui_util:INFO Binding event MainWindow:actionNew_trigger
     ui_util:INFO Binding event MainWindow:actionOpen_trigger
     ui_util:INFO Binding event MainWindow:actionSave_trigger
     ui_util:INFO Binding event MainWindow:actionUndo_trigger
     ui_util:INFO Binding event MainWindow:actionSaveAs_trigger
     ui_util:INFO Binding event MainWindow:actionImportFiles_trigger
     ui_util:INFO Binding event MainWindow:actionImportImageSequence_trigger
     ui_util:INFO Binding event MainWindow:actionRedo_trigger
     ui_util:INFO Binding event MainWindow:actionRemoveClip_trigger
     ui_util:INFO Binding event MainWindow:actionRemoveTransition_trigger
     ui_util:INFO Binding event MainWindow:actionExportVideo_trigger
     ui_util:INFO Binding event MainWindow:actionUploadVideo_trigger
     ui_util:WARNING Icon theme gtk-quit not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAddTrack_trigger
     ui_util:INFO Binding event MainWindow:actionPreferences_trigger
     ui_util:INFO Binding event MainWindow:actionPlay_trigger
     ui_util:INFO Binding event MainWindow:actionJumpStart_trigger
     ui_util:INFO Binding event MainWindow:actionRewind_trigger
     ui_util:INFO Binding event MainWindow:actionFastForward_trigger
     ui_util:INFO Binding event MainWindow:actionJumpEnd_trigger
     ui_util:INFO Binding event MainWindow:actionArrowTool_trigger
     ui_util:INFO Binding event MainWindow:actionSnappingTool_trigger
     ui_util:INFO Binding event MainWindow:actionAddMarker_trigger
     ui_util:INFO Binding event MainWindow:actionPreviousMarker_trigger
     ui_util:INFO Binding event MainWindow:actionNextMarker_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowAll_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowVideo_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowAudio_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowImage_trigger
     ui_util:INFO Binding event MainWindow:actionTransitionsShowAll_trigger
     ui_util:INFO Binding event MainWindow:actionTransitionsShowCommon_trigger
     ui_util:INFO Binding event MainWindow:actionEffectsShowAll_trigger
     ui_util:INFO Binding event MainWindow:actionEffectsShowVideo_trigger
     ui_util:INFO Binding event MainWindow:actionEffectsShowAudio_trigger
     ui_util:INFO Binding event MainWindow:actionTimelineZoomIn_trigger
     ui_util:INFO Binding event MainWindow:actionTimelineZoomOut_trigger
     ui_util:INFO Binding event MainWindow:actionTitle_trigger
     metrics:INFO Track metric: {'cache-control': 'no-cache, no-store, must-revalidate', 'pragma': 'no-cache', 'status': '200', 'expires': 'Mon, 01 Jan 1990 00:00:00 GMT', 'age': '1039673', 'access-control-allow-origin': '*', 'content-length': '35', 'x-content-type-options': 'nosniff', 'date': 'Wed, 28 Sep 2016 23:22:27 GMT', 'server': 'Golfe2', 'content-type': 'image/gif', 'last-modified': 'Sun, 17 May 1998 03:00:00 GMT', 'content-location': 'http://www.google-analytics.com/collect?cd2=3.5.2&ua=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&tid=UA-4381101-5&cd5=Mageia-6-Cauldron&cd1=0.1.2&an=OpenShot+Video+Editor&cd=main-screen&cd3=5.6.1&av=2.1.0&t=screenview&aid=org.openshot.openshot-qt&cid=2507440c-0e69-4507-a378-acabf0882329&ul=de-de&cd4=5.6&aip=1&v=1'} (b'GIF89a\x01\x00\x01\x00\x80\xff\x00\xff\xff\xff\x00\x00\x00,\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x02D\x01\x00;')
     ui_util:INFO Binding event MainWindow:actionAnimatedTitle_trigger
     ui_util:INFO Binding event MainWindow:actionFullscreen_trigger
     ui_util:INFO Binding event MainWindow:actionAbout_trigger
     ui_util:WARNING Icon theme gtk-info not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionThumbnailView_trigger
     ui_util:WARNING Icon theme view-preview not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionDetailsView_trigger
     ui_util:WARNING Icon theme view-list-details not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionReportBug_trigger
     ui_util:INFO Binding event MainWindow:actionAskQuestion_trigger
     ui_util:WARNING Icon theme im-message-new not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionTranslate_trigger
     ui_util:WARNING Icon theme stock_person not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionDonate_trigger
     ui_util:INFO Binding event MainWindow:actionHelpContents_trigger
     ui_util:INFO Binding event MainWindow:actionSimple_View_trigger
     ui_util:INFO Binding event MainWindow:actionAdvanced_View_trigger
     ui_util:WARNING Icon theme get-hot-new-stuff not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionFreeze_View_trigger
     ui_util:WARNING Icon theme locked not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionUn_Freeze_View_trigger
     ui_util:WARNING Icon theme locked not found. Will use backup icon.
     metrics:INFO Track metric: {'cache-control': 'no-cache, no-store, must-revalidate', 'pragma': 'no-cache', 'status': '200', 'expires': 'Mon, 01 Jan 1990 00:00:00 GMT', 'age': '1039673', 'access-control-allow-origin': '*', 'content-length': '35', 'x-content-type-options': 'nosniff', 'date': 'Wed, 28 Sep 2016 23:22:27 GMT', 'server': 'Golfe2', 'content-type': 'image/gif', 'last-modified': 'Sun, 17 May 1998 03:00:00 GMT', 'content-location': 'http://www.google-analytics.com/collect?cd2=3.5.2&ua=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&sc=start&tid=UA-4381101-5&cd5=Mageia-6-Cauldron&cd1=0.1.2&an=OpenShot+Video+Editor&cd=launch-app&cd3=5.6.1&av=2.1.0&t=screenview&aid=org.openshot.openshot-qt&cid=2507440c-0e69-4507-a378-acabf0882329&ul=de-de&cd4=5.6&aip=1&v=1'} (b'GIF89a\x01\x00\x01\x00\x80\xff\x00\xff\xff\xff\x00\x00\x00,\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x02D\x01\x00;')
     ui_util:INFO Binding event MainWindow:actionShow_All_trigger
     ui_util:INFO Binding event MainWindow:actionProfile_trigger
     ui_util:INFO Binding event MainWindow:actionAdd_to_Timeline_trigger
     ui_util:INFO Binding event MainWindow:actionPreview_File_trigger
     ui_util:INFO Binding event MainWindow:actionRemove_from_Project_trigger
     ui_util:INFO Binding event MainWindow:actionFile_Properties_trigger
     ui_util:INFO Binding event MainWindow:actionRemoveTrack_trigger
     ui_util:INFO Binding event MainWindow:actionRemoveMarker_trigger
     ui_util:INFO Binding event MainWindow:actionAddTrackAbove_trigger
     ui_util:INFO Binding event MainWindow:actionAddTrackBelow_trigger
     ui_util:INFO Binding event MainWindow:actionRemoveEffect_trigger
     ui_util:INFO Binding event MainWindow:actionSplitClip_trigger
     ui_util:INFO Binding event MainWindow:actionProperties_trigger
     ui_util:INFO Binding event MainWindow:actionRenameTrack_trigger
     ui_util:WARNING Icon theme gtk-edit not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionUpdate_trigger
     ui_util:INFO Binding event MainWindow:actionTutorial_trigger
     ui_util:WARNING Icon theme im-message-new not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAnimation_trigger
     ui_util:INFO Binding event MainWindow:actionLockTrack_trigger
     ui_util:INFO Binding event MainWindow:actionUnlockTrack_trigger
files_listview:INFO currentChanged
files_listview:INFO updateSelection
 files_model:INFO updating files model.
transition_model:INFO updating transitions model.
timeline_webview:INFO Qt Found!
timeline_webview:INFO $scope.Qt = true;
timeline_webview:INFO UpdateLayerIndex
     version:INFO Found current version: {'content-length': '29', 'date': 'Tue, 11 Oct 2016 00:20:01 GMT', 'status': '200', 'content-type': 'application/json', 'server': 'Apache/2.2.22 (Ubuntu)', 'content-location': 'http://www.openshot.org/version/json/'} (b'{"openshot_version": "2.1.0"}')
 main_window:INFO foundCurrentVersion: Found the latest version: 2.1.0
effects_model:INFO updating effects model.
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
properties_model:INFO updating clip properties model.
preview_thread:INFO QThread Start Method Invoked
preview_thread:INFO initPlayer
 main_window:ERROR Unhandled crash detected... will attempt to recover backup project: /home/psyca/.openshot_qt/backup
    tutorial:INFO process tutorial dialogs
         app:INFO Process command-line arguments: ['/bin/openshot-qt']
 main_window:INFO updateStatusChanged
 main_window:INFO recover_backup
project_data:INFO Setting default profile to HDV 1080 25p 1920x1080
preview_thread:INFO refreshFrame
preview_thread:INFO self.player.Position(): 1
timeline_webview:INFO UpdateLayerIndex
 main_window:INFO updateStatusChanged
preview_thread:INFO onModeChanged
properties_model:INFO Update item: 
properties_model:INFO updating clip properties model.
timeline_webview:INFO redraw_audio_onTimeout
     metrics:INFO Track metric: {'cache-control': 'no-cache, no-store, must-revalidate', 'pragma': 'no-cache', 'status': '200', 'expires': 'Mon, 01 Jan 1990 00:00:00 GMT', 'age': '1039646', 'access-control-allow-origin': '*', 'content-length': '35', 'x-content-type-options': 'nosniff', 'date': 'Wed, 28 Sep 2016 23:22:57 GMT', 'server': 'Golfe2', 'content-type': 'image/gif', 'last-modified': 'Sun, 17 May 1998 03:00:00 GMT', 'content-location': 'http://www.google-analytics.com/collect?cd2=3.5.2&exf=1&ua=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&tid=UA-4381101-5&cd5=Mageia-6-Cauldron&cd1=0.1.2&an=OpenShot+Video+Editor&cd3=5.6.1&av=2.1.0&t=exception&aid=org.openshot.openshot-qt&cid=2507440c-0e69-4507-a378-acabf0882329&ul=de-de&cd4=5.6&aip=1&v=1&exd=unhandled-crash'} (b'GIF89a\x01\x00\x01\x00\x80\xff\x00\xff\xff\xff\x00\x00\x00,\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x02D\x01\x00;')
Unhandled Python exception
Abgebrochen (Speicherabzug geschrieben)

**Comment by jonoomph** [comment]
There was indeed an issue with this which results in a crash, but I've fixed it on more recent builds (fingers crossed). Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot and test this again. Hopefully it will no longer crash on you. =)

Closing the ticket for now, but please reopen if the problem persists. Thanks!
