### ISSUE TITLE
Import/Export fcpxml to exchange data with other NLE

### ISSUE THREAD

**Issue by tacman** [OpenShot/openshot-qt#3163]
**Describe the new feature:**

I would like to exchange projects between OpenShot and Final Cut Pro, Adobe Premiere and Davinci Resolve.

**Describe the solution you'd like:**

Although it's not great, Final Cut's XML is probably the most complete exchange format.

**Describe alternatives you have considered:**

No other formats contain as much information.

The FCP format is fairly complex, but I think the 80/20 rule would apply here.  Implementing an exchange format for 20% of the functionality (files, timelines, clips, basic transformations) would go a long way.

**Comment by tacman** [comment]
Not sure if this can be done without video "clips" -- a single video file create multiple clips that can be moved around on a timeline, with different in-points and out-points.

**Comment by ferdnyc** [comment]
@tacman 

Final Cut Pro XML (as well as EDL) import and export was actually added as a feature around 7-8 months ago, which makes it too recent for the 2.4.4 release version, but both the current Daily Build versions of OpenShot and the imminent 2.4.5 release version already support the import and export of data in FCP XML format.

Hope you'll give it a try and let us know how it works out for you!

(I'm going to close this as answered, but feel free to reopen or add additional comments if there's anything else we can help with.)
