### ISSUE TITLE
Video clip timeframe and fps not imported or exported correctly

### ISSUE THREAD

**Issue by john-davies** [OpenShot/openshot-qt#3164]
_This is possibly related to #3138 but I also have some additional problems not shown in that issue._

**Describe the bug:**
Video clip timeframe and fps not imported or exported correctly

**Steps to reproduce the behavior:**
1. I created a short time lapse movie containing 150 frames at 25 fps using ffmpeg:

`ffmpeg -framerate 25 -start_number 0000 -i %04d.jpg -c:v libx264 -profile:v high -crf 20 -pix_fmt yuv420p e.mp4`

2. If I open the file with VLC or HandBrake then it reports the expected 25 fps and duration of 6s

3. I then import this file into a blank OpenShot project with a profile of 720p 25fps 

![issue1](https://user-images.githubusercontent.com/16657559/71919299-3d28a100-317c-11ea-9c50-1a035923438e.jpg)

4. Opening the "Preview" window gives the correct frame count but the overall time is reported as 5.25s rather than 6s.

![issue2](https://user-images.githubusercontent.com/16657559/71919352-61847d80-317c-11ea-9da4-fd8d74f1d36c.jpg)

5. If I add this clip to a blank track and export it then ffmpeg reports a frame rate of 25.17 fps and a duration of 5.98s for the resulting output file.

6. Additionally there are jumps in the timeline when I'm previewing the clip in OpenShot. For example starting at frame 125:

![issue3](https://user-images.githubusercontent.com/16657559/71919378-76f9a780-317c-11ea-9a55-cfe55ba18dc4.jpg)

then 1 click of the right arrow key gets me correctly to frame 126 but the timeline jumps from 4.25s to 5.01s:

![issue4](https://user-images.githubusercontent.com/16657559/71919398-824cd300-317c-11ea-8f06-5e0df852554a.jpg)

**Expected behavior:**
I would expect the clip and fps setting to remain constant throughout these operations.

**System Details:**
- app:INFO openshot-qt version: 2.4.4 _( Latest AppImage version downloaded from the website )_
- app:INFO libopenshot version: 0.2.3
- app:INFO platform: Linux-4.4.0-170-generic-x86_64-with-Ubuntu-16.04-xenial

**Log Files:**

Initial input file: https://drive.google.com/open?id=1EXuKU6o4mmXW2bV-UQ1NcNZiJ0KfsBYY

Output video file: https://drive.google.com/open?id=11TaZc6qmQv9_W-MSVOkMmny2lIdsNbQb

**Comment by N3WWN** [comment]
It's not obvious, but the last number is not fractions of a second, but rather the frame number.  So, 00:00:00:01 is the first frame of the video and 00:00:05:25 is frame 25 of last second of the video, which is the same as 00:00:06:00, but since there is no zero frame, 00:00:06:00 doesn't make sense.

**Comment by john-davies** [comment]
Ah OK, thanks, that makes sense now. I did check in the manual as to the format of that field but I couldn't find anything so I assumed that it was fractions of a second. Maybe a format like "hh:mm:ss/ff" would give a stronger hint as to what's going on ( unless nobody else has had a problem and it's just me, in which case forget it! )

I'm still slightly confused by the fractional fps in the output file though, but maybe it doesn't really matter,

I've been doing some more testing in the meantime and I've found another possible issue. When I import the clip then the last 5 frames appear to be identical in the preview. This isn't the case in the input file but the problem does seem to be carried over to the output file.

It happens with all the timelapse files that I created but it doesn't happen with https://www.sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4 for example.

**Comment by N3WWN** [comment]
No, you're not the first to be confused by this! ;)  #1426 and #1355 are two other issues mentioning this time formatting.

I don't have any explanation for the fractional fps in the output.  I know there used to be an issue where the first frame was always blank in the output, regardless of the input, but I don't recall if that changed the duration or the frame rate.

Can you try creating the timelapse videos with some different ffmpeg options or output video formats?  IIRC, mp4 uses predicted frames by default, which openshot may not be able to properly use.  Just a guess, though...

**Comment by john-davies** [comment]
You could spend days on the time formatting options and still not satisfy everybody! I think that using a different separator for the frames and mentioning it in the on-line manual "Main Window" overview section could be a quick improvement.

The only other comment that I would make is that in the "Split Clip" window it would be useful to show the duration of the clip that you've selected and/or have some markers to show where the current start and end points are. At the moment it's quite tricky to edit the selection once it's been made.

As regards the missing frames then I think your suggestion is correct. If I encode with the following command:

`ffmpeg -framerate 25 -start_number 0000 -i %04d.jpg -vcodec yuv4  output.avi`

then all frames are shown correctly in the preview mode. I'll need to have a further play around with the codecs because the yuv4 generates very large files. ( Or I just don't use the final few frames of the clip. )

From my point of view I think that this issue can now be closed.

_For information the ffmpeg description for this codec is:_

```
Codecs:
 D..... = Decoding supported
 .E.... = Encoding supported
 ..V... = Video codec
 ..A... = Audio codec
 ..S... = Subtitle codec
 ...I.. = Intra frame-only codec
 ....L. = Lossy compression
 .....S = Lossless compression
 -------

DEVI.. yuv4                 Uncompressed packed 4:2:0

```

**Comment by SuslikV** [comment]
> I've been doing some more testing in the meantime and I've found another possible issue. When I import the clip then the last 5 frames appear to be identical in the preview. This isn't the case in the input file but the problem does seem to be carried over to the output file...

This part of the issue was reported here too: https://github.com/OpenShot/openshot-qt/issues/2435
