### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by technotrance911** [OpenShot/openshot-qt#3171]
**Describe the bug:**
Hello!
I can not open the saved project. Error: 'NoneType' object is not subscriptable

**Steps to reproduce the behavior:**
I did my project, and at this time the program began to behave strangely. Objects stopped selecting. Objects did not respond to a mouse click. I close program. Then start program again and I began to get an error when opening a project. 'NoneType' object is not subscriptable

**System Details:**
- OpenShot Version 2.4.4-2.fc28
- Operating System Fedora 28 x86_64
- Qt 5.11.3
- Python 3.6.8

**Log Files:**
[openshot_qt.zip](https://github.com/OpenShot/openshot-qt/files/4045525/openshot_qt.zip)

**Comment by technotrance911** [comment]
Is there any way to restore the project? Even without the latest changes. I did it for several days.

**Comment by SuslikV** [comment]
It's depending on how much data were damaged. Where is you project file? Can you share it?

**Comment by a3nm** [comment]
I had the same problem with Openshot 2.4.3 from Debian. I'm not sure what caused the problem, as I could re-do the same steps in a new file without triggering the problem.

I attach the project file which was obtained by saving and raises the error when opening. [video.osp.zip](https://github.com/OpenShot/openshot-qt/files/4393635/video.osp.zip)

Thanks!

**Comment by SuslikV** [comment]
@a3nm your repaired project file:

About 3KB to down load, CRC of the zip archive MD5:CE373548057B39A67BDA9A1D754C7EC7
[video - repaired.zip](https://github.com/OpenShot/openshot-qt/files/4394912/video.-.repaired.zip)

v2.5.1 compatible:
About 3KB to down load, CRC of the zip archive MD5:FF5123CD992CC21D99E6625BDDA92D9D
[video - repaired-251compatible.zip](https://github.com/OpenShot/openshot-qt/files/4394922/video.-.repaired-251compatible.zip)

When you complete your project, consider to upgrade to the latest version available (v2.5.1)

**Info for the developers:**
project file has`null` object after 16750 position in the file (end of the `"clips"` section)
Also, may suffer form the https://github.com/OpenShot/openshot-qt/issues/3227 that was solved in v2.5.1

**Comment by a3nm** [comment]
Hi @SuslikV, woaw that's super kind of you, thanks! I'm very sorry I hadn't clarified in my bug report that this was only the result of around 2 minutes of playing around. I have recreated the file already, and it really wasn't worth the effort. My point in providing the file was simply to help debugging efforts. Sorry again that I haven't been clear about my expectations here.

I'm using 2.4.3 because it's the latest version shipped by Debian, just filed a bug with them to ask if they could update. I'll do so on my end. Many thanks again for your work in investigating this.

**Comment by Andrea9501** [comment]
Hi, I have the same problem of @technotrance911: I was working on a project in OpenShot, I closed it and when I tried to open it again the error message "Nonetype" object is not subscriptable appeared. The further problem in my case is that I don't have many programming skills as you. Can you @SuslikV  give me a hand please?

**Comment by SuslikV** [comment]
@Andrea9501 can you share your project file compressed into `.zip` format?

**Comment by Andrea9501** [comment]
Thank you @SuslikV for the answer but I'm editing the video again from the beginning; luckily (very luckily) I exported it few minutes before the project crushed and now I'm using that video as model. Thank you anyway, very kind of you!
If the new project crush again I'll ask you, thank you!

**Comment by SuslikV** [comment]
@Andrea9501 Better is to disable auto-saving feature in _Preferences_ of the application and make backup copies manually, time to time.

**Comment by Andrea9501** [comment]
Yeah, I've noticed it... Anyway I just exported the newly made video, forgive me if I bothered you :-)

**Comment by che12pm** [comment]
@SuslikV I have the same problem. Can you please help me. I would be very grateful.

**Comment by SuslikV** [comment]
@che12pm were is your project file?

**Comment by che12pm** [comment]
@SuslikV I made the video from start again. Sorry for bothering you.

**Comment by SuslikV** [comment]
@che12pm Please, make backup copies of your project file time to time if you working on something huge or important for you.

**Comment by whentington** [comment]
I recently started using openshot and this exact situation has happened to me, "'NoneType' object is not subscriptable" error, the program began to behave strangely, so i closed it and tried to open it and it gave me this error, it looks like you were able to fix it for this person so i was wondering if you could fix it for me too?

here is the zip file for my project:
[vid.zip](https://github.com/OpenShot/openshot-qt/files/9940223/vid.zip)
thanks

**Comment by FredFiveOne** [comment]
In the event this happens to anyone else in the future

Follow these steps:
1. Backup your osp file in case a change doesn't solve the problem
2. Open your .osp file in a text editor (eg. sublime, notepad, etc.)
3. Search for "null"
4. In my case, there was a section that looked like the following with line breaks "}, null, null}"
5. Delete ", null, null" (there may be line breaks in between)
6. Try and open your file.
7. If successful, you are done! Otherwise start over at 2, replacing your osp file with a copy of your backup and try again until you (hopefully) delete the right section and solve the issue.

I just saved hours of work with this, and created an account just to comment in case it happens to someone else in the future, and they end up here looking for answers.

**Comment by Colorjet3** [comment]
Thank you @FredFiveOne for this.  Really appreciate you taking the time to share your fix with the community.  I would like to ask you for a favor.  It would be great if you can share a screen shot of the page from your .osp file so we can see a few of the lines above and the lines below the "}, null, null}".

Thank you in advance!

**Comment by FredFiveOne** [comment]
No problem @Colorjet3. Please see below for the snippet containing the "}, null, null}". Note that there are line breaks, so it actually looks like:
```
},
null,
null
```

The snippet:
```
                            "handle_left": {
                                "X": 0.5,
                                "Y": 1.0
                            },
                            "handle_right": {
                                "X": 0.5,
                                "Y": 0.0
                            },
                            "handle_type": 0,
                            "interpolation": 0
                        }
                    ]
                }
            },
            "waveform": false,
            "file_id": "KJ11WX0ZQ6",
            "title": "Outro.mp4",
            "image": "thumbnail/KJ11WX0ZQ6.png"
        },
        null,
        null
    ],
    "effects": [
        {
            "id": "99NCMEYWKZ",
            "layer": 3000000,
            "title": "Transition",
            "type": "Mask",
            "position": 88.53333333333333,
            "start": 0,
            "end": 0.7999999999999261,
            "brightness": {
                "Points": [
                    {
                        "co": {
                            "X": 1,
                            "Y": 1
                        },
                        "handle_left": {
                            "X": 0.5,
                            "Y": 1
                        },
                        "handle_right": {
                            "X": 0.5,
                            "Y": 0
```

**Comment by Colorjet3** [comment]
Thank you so much for this @FredFiveOne.  This will give me a better understanding of the formatting.  I am going to play around with a test project (the .osp) and see if I can break the syntax to generate the "NoneType" message so it is better documented and more importantly how to resolve it.
