### ISSUE TITLE
transitions not playing between scenes or seperately

### ISSUE THREAD

**Issue by wynnbeattie** [OpenShot/openshot-qt#3177]
Tried latest version and 2.50. Scenes load and play. Transitions are ignored between scenes. If I load only a transition as a new project, it wont play. 

**System Details**
- OpenShot Version: 2.5.0  , also 2.4.3
![openshot transition problem](https://user-images.githubusercontent.com/13833153/72444399-95136900-3775-11ea-8591-c0f7e2e3a12e.png)

Windows 10, I5 processor.

**Comment by SuslikV** [comment]
There is no Preview Transition feature yet.

I prefer to place all objects on different tracks (transition, clip, clip), thus forming "stairs" that going up and down, up and down...

**Comment by ferdnyc** [comment]
> There is no Preview Transition feature yet.

There actually sort of is... I'll demonstrate:

@wynnbeattie This is largely by design. Transitions operate between two video sources, their "in" and "out" (represented by Brightness `+1` and `-1`), so there always need to be two clips running wherever a transition is placed. I'll demonstrate with some (slightly sped-up) animated GIFs:

One way you can do it is, as @SuslikV says, to stack your clips upwards on separate tracks/layers, and place your Transitions on the start of the upper clip (but only over the area where both clips are playing simultaneously):

![OpenShot-Trans1](https://user-images.githubusercontent.com/538020/72457067-cd29a480-3793-11ea-97a8-ac576ce7ffa2.gif)

If you set the transition's "Replace Image" property to "Yes", you can see the actual transition in its grayscale form — when operating on clips, "Black" will be one of the two sources, and "White" will be the other source. (Gray areas represent fades between the two in corresponding proportions. (This is the "sorta" preview I mentioned):

![OpenShot-Trans2](https://user-images.githubusercontent.com/538020/72457199-10841300-3794-11ea-81fd-72203b350611.gif)

The other way transitions can be used is by overlapping two clips on the same track, which will automatically create a simple fade between the two tracks:

![OpenShot-Trans3](https://user-images.githubusercontent.com/538020/72457242-298cc400-3794-11ea-904d-662309887532.gif)

You can also turn that fade into any other transition by changing its "Source" property, but one annoyance with that is, you also have to Reverse the transition (using its context menu).

**Comment by ferdnyc** [comment]
(Sorry about the glitching, that's just OBS not doing a great job capturing my desktop.)

**Comment by SuslikV** [comment]
> (Sorry about the glitching, that's just OBS not doing a great job capturing my desktop.)

@ferdnyc what is your config is: `grep DRI /var/log/Xorg.0.log` ?

**Comment by ferdnyc** [comment]
@SuslikV 
> 
> @ferdnyc what is your config is: `grep DRI /var/log/Xorg.0.log` ?

(For my actual desktop session...)
```console
$ grep DRI /var/log/Xorg.1.log
[   975.085] (II) NVIDIA(0): [DRI2] Setup complete
[   975.085] (II) NVIDIA(0): [DRI2]   VDPAU driver: nvidia
```

And in anticipation of follow-up questions:
```console
$ vdpauinfo
display: :1   screen: 0
API version: 1
Information string: NVIDIA VDPAU Driver Shared Library  440.44  Sun Dec  8 03:27:26 UTC 2019

Video surface:

name   width height types
-------------------------------------------
420     4096  4096  NV12 YV12 
422     4096  4096  UYVY YUYV 
444     4096  4096  NV24 YV24 
```
<details>
<summary>More...</summary>

<pre><code>
Decoder capabilities:

name                        level macbs width height
----------------------------------------------------
MPEG1                           0 65536  4032  4048
MPEG2_SIMPLE                    3 65536  4032  4048
MPEG2_MAIN                      3 65536  4032  4048
H264_BASELINE                  51 65536  4032  4080
H264_MAIN                      51 65536  4032  4080
H264_HIGH                      51 65536  4032  4080
VC1_SIMPLE                      1  8190  2048  2048
VC1_MAIN                        2  8190  2048  2048
VC1_ADVANCED                    4  8190  2048  2048
MPEG4_PART2_SP                  3  8192  2048  2048
MPEG4_PART2_ASP                 5  8192  2048  2048
DIVX4_QMOBILE                   0  8192  2048  2048
DIVX4_MOBILE                    0  8192  2048  2048
DIVX4_HOME_THEATER              0  8192  2048  2048
DIVX4_HD_1080P                  0  8192  2048  2048
DIVX5_QMOBILE                   0  8192  2048  2048
DIVX5_MOBILE                    0  8192  2048  2048
DIVX5_HOME_THEATER              0  8192  2048  2048
DIVX5_HD_1080P                  0  8192  2048  2048
H264_CONSTRAINED_BASELINE      51 65536  4032  4080
H264_EXTENDED                  51 65536  4032  4080
H264_PROGRESSIVE_HIGH          51 65536  4032  4080
H264_CONSTRAINED_HIGH          51 65536  4032  4080
H264_HIGH_444_PREDICTIVE       51 65536  4032  4080
VP9_PROFILE_0                  --- not supported ---
VP9_PROFILE_1                  --- not supported ---
VP9_PROFILE_2                  --- not supported ---
VP9_PROFILE_3                  --- not supported ---
HEVC_MAIN                      --- not supported ---
HEVC_MAIN_10                   --- not supported ---
HEVC_MAIN_STILL                --- not supported ---
HEVC_MAIN_12                   --- not supported ---
HEVC_MAIN_444                  --- not supported ---

Output surface:

name              width height nat types
----------------------------------------------------
B8G8R8A8         16384 16384    y  Y8U8V8A8 V8U8Y8A8 A4I4 I4A4 A8I8 I8A8 
R10G10B10A2      16384 16384    y  Y8U8V8A8 V8U8Y8A8 A4I4 I4A4 A8I8 I8A8 

Bitmap surface:

name              width height
------------------------------
B8G8R8A8         16384 16384
R8G8B8A8         16384 16384
R10G10B10A2      16384 16384
B10G10R10A2      16384 16384
A8               16384 16384

Video mixer:

feature name                    sup
------------------------------------
DEINTERLACE_TEMPORAL             y
DEINTERLACE_TEMPORAL_SPATIAL     y
INVERSE_TELECINE                 y
NOISE_REDUCTION                  y
SHARPNESS                        y
LUMA_KEY                         y
HIGH QUALITY SCALING - L1        y
HIGH QUALITY SCALING - L2        -
HIGH QUALITY SCALING - L3        -
HIGH QUALITY SCALING - L4        -
HIGH QUALITY SCALING - L5        -
HIGH QUALITY SCALING - L6        -
HIGH QUALITY SCALING - L7        -
HIGH QUALITY SCALING - L8        -
HIGH QUALITY SCALING - L9        -

parameter name                  sup      min      max
-----------------------------------------------------
VIDEO_SURFACE_WIDTH              y         1     4096
VIDEO_SURFACE_HEIGHT             y         1     4096
CHROMA_TYPE                      y  
LAYERS                           y         0        4

attribute name                  sup      min      max
-----------------------------------------------------
BACKGROUND_COLOR                 y  
CSC_MATRIX                       y  
NOISE_REDUCTION_LEVEL            y      0.00     1.00
SHARPNESS_LEVEL                  y     -1.00     1.00
LUMA_KEY_MIN_LUMA                y  
LUMA_KEY_MAX_LUMA                y  
</code></pre></details>

```console
$ sudo lspci -s 01:00 -v
01:00.0 VGA compatible controller: 
NVIDIA Corporation GK208B [GeForce GT 710] (rev a1) (prog-if 00 [VGA controller])
	Subsystem: Micro-Star International Co., Ltd. [MSI] Device 8c93
	Flags: bus master, fast devsel, latency 0, IRQ 34
	Memory at f9000000 (32-bit, non-prefetchable) [size=16M]
	Memory at d0000000 (64-bit, prefetchable) [size=128M]
	Memory at d8000000 (64-bit, prefetchable) [size=32M]
	I/O ports at e000 [size=128]
	[virtual] Expansion ROM at 000c0000 [disabled] [size=128K]
	Capabilities: [60] Power Management version 3
	Capabilities: [68] MSI: Enable+ Count=1/1 Maskable- 64bit+
	Capabilities: [78] Express Legacy Endpoint, MSI 00
	Capabilities: [100] Virtual Channel
	Capabilities: [128] Power Budgeting <?>
	Capabilities: [600] Vendor Specific Information: ID=0001 Rev=1 Len=024 <?>
	Kernel driver in use: nvidia
	Kernel modules: nouveau, nvidia_drm, nvidia

01:00.1 Audio device: NVIDIA Corporation GK208 HDMI/DP Audio Controller (rev a1)
	Subsystem: Micro-Star International Co., Ltd. [MSI] Device 8c93
	Flags: bus master, fast devsel, latency 0, IRQ 17
	Memory at fa080000 (32-bit, non-prefetchable) [size=16K]
	Capabilities: [60] Power Management version 3
	Capabilities: [68] MSI: Enable- Count=1/1 Maskable- 64bit+
	Capabilities: [78] Express Endpoint, MSI 00
	Kernel driver in use: snd_hda_intel
	Kernel modules: snd_hda_intel
```

```console
$ nvidia-smi
Thu Jan 16 20:30:28 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.44       Driver Version: 440.44       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GT 710      Off  | 00000000:01:00.0 N/A |                  N/A |
| 50%   43C    P0    N/A /  N/A |    830MiB /   980MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0                    Not Supported                                       |
+-----------------------------------------------------------------------------+

$ nvidia-smi -q|grep -v 'N/A'|grep -B1 ':'

Timestamp                           : Thu Jan 16 20:29:58 2020
Driver Version                      : 440.44
CUDA Version                        : 10.2

Attached GPUs                       : 1
GPU 00000000:01:00.0
    Product Name                    : GeForce GT 710
    Product Brand                   : GeForce
    Persistence Mode                : Disabled
    Driver Model
    GPU UUID                        : GPU-17c62d61-31f7-c3f7-b0e1-8f97137a9800
    Minor Number                    : 0
    VBIOS Version                   : 80.28.A6.00.34
--
    PCI
        Bus                         : 0x01
        Device                      : 0x00
        Domain                      : 0x0000
        Device Id                   : 0x128B10DE
        Bus Id                      : 00000000:01:00.0
        Sub System Id               : 0x8C931462
--
        Bridge Chip
        Replays Since Reset         : 0
        Replay Number Rollovers     : 0
    Fan Speed                       : 50 %
    Performance State               : P0
    FB Memory Usage
        Total                       : 980 MiB
        Used                        : 830 MiB
        Free                        : 150 MiB
    BAR1 Memory Usage
    Compute Mode                    : Default
--
    Temperature
        GPU Current Temp            : 43 C
--
    Applications Clocks
        Graphics                    : 954 MHz
        Memory                      : 900 MHz
    Default Applications Clocks
        Graphics                    : 954 MHz
        Memory                      : 900 MHz
```

**Comment by ferdnyc** [comment]
I thought it might be because I'm using software encoding. (If I configure it for NVENC, every time I try to capture at full 1920x1200 resolution it reports "out of memory".) But I set it to downscale to 1280x800 and hardware-encode, and if anything that made it worse.

_\*shrug\*_ It's a $50 video card, I suspect perfect results are impossible.

**Comment by SuslikV** [comment]
@ferdnyc DRI2 only? Is no good for such GPU. If you think this is performance issue, you may try custom ffmpeg output of obs and mpeg2 encoder within mpeg-ts container - it has very low impact on CPU and may help a lot. But I think this is driver bug or so. And if you resize the obs window, is it glitches too, in preview?
