### ISSUE TITLE
AppImage install failure on Linux Mint 18 Cinnamon 64-bit - wrong qt  lib

### ISSUE THREAD

**Issue by Windsurfer01** [OpenShot/openshot-qt#318]
This error repeatedly occurs in the log file:
In /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqeglfs.so:
  Plugin uses incompatible Qt library (5.5.1) [release]
"The plugin '/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqeglfs.so' uses incompatible Qt library. (5.5.1) [release]" 

I have qt 5.5.1 installed.

**Comment by Windsurfer01** [comment]
I forgot to mention that it is OpenShot 2.1.

**Comment by probonopd** [comment]
This is because the OpenShot AppImage does not correctly bundle its own `qt5/plugins/. Qt then tries to load the plugins from the host system, which doesn't work due to version mismatch. The OpenShot AppImage needs to be fixed.

**Comment by jonoomph** [comment]
Looking into this now. Our AppImage does include the plugins correctly, at least based on my initial investigation. However, I think I need to include a qt.conf file, which tells Qt where to look for it's plugins... and basically ignore the system PATH. I'll keep you posted.

**Comment by jonoomph** [comment]
Committed a fix which adds a qt.conf file, which will hopefully help set the prefix correctly, and only search the current folder, rather than the system Qt path. I'll give it a test on Mint 18/Cinnamon/64-bit, and see what happens. =)

**Comment by Windsurfer01** [comment]
Thanks for the rapid response. I tried the new commit. Qt appears to load correctly, but there is an error report in the last line. See attached log file.
[Openshot_log_1.txt](https://github.com/OpenShot/openshot-qt/files/463589/Openshot_log_1.txt)

I also noticed with the earlier version that it created a menu entry in 'Other' rather than 'Sound and Video'. Should I make another error report for this?

**Comment by Windsurfer01** [comment]
The error is issue #298.

**Comment by Windsurfer01** [comment]
Sorry, I closed it in error.

**Comment by probonopd** [comment]
So the error you are getting now is

> g_type_check_instance_is_fundamentally_a

Which means you now have a duplicate to https://github.com/OpenShot/openshot-qt/issues/298

**Comment by Windsurfer01** [comment]
If the latest libraries are now included, and is contained in the AppImage, then it appears that they may need renaming within the AppImage, or that the file names are being read, rather than the internal version number. My Linux Mint 18 Synaptic shows the correct files are present as per attached screenshot.
![screenshot from 2016-09-09 14-41-08](https://cloud.githubusercontent.com/assets/3854941/18389125/4ab8e530-769c-11e6-9cfe-96eba8fdc724.png)

I will try copying them with a new name, or making some symlinks and report back.

**Comment by Windsurfer01** [comment]
I followed the instructions at #298 exactly, and copied the files into /home/mike/usr/lib/. I moved the AppImage to /home/mike, deleted .openshot_qt, removed the menu entry in Other and ran AppImage again.

A dialog appeared warning about a gtk issue. 'Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.' I closed it and continued. The application would not start. I ran the AppImage again and the gtk warning did not appear. Still nothing appears to work.

I cannot reproduce the gtk dialog warning, but it at the start of the log.

Are there any folders other than .openshot_qt that I need to remove?

**Comment by probonopd** [comment]
You understand that the steps I posted in #298 must be done at __AppImage creation time__, not when using the AppImage?

**Comment by Windsurfer01** [comment]
Yes. I deleted everything except AppImage. Followed your steps, and then
ran AppImage.

**Comment by probonopd** [comment]
Sorry, but " I deleted everything except AppImage" doesn't sound like you have understood it. Let @jonoomph fix the AppImage and then retry.

**Comment by Windsurfer01** [comment]
@probonopd thanks for trying to help me. 

I first tried the basic download, but have since been using OpenShot-v2.1.0-6-gdb65e4f-49-580-x86_64.AppImage (Sept. 9, 2016, 12:02 a.m.) which @jonoomph loaded after I first posted. I assumed it had a fix in it. I could not see the point of deleting it, as there was nothing later, and I assumed that it is not self modifying.

The first screen shot attachment (example file) indicates that I have the required files in /usr/lib as a symlink pointing to the real files in /usr/lib/x86_64-linux-gnu which is the Linux Mint 18 default. In /usr/lib/x86_64-linux-gnu are the all the files typically shown in the second screen shot. All the symlinks appear to point to the highlighted files as shown in the second screen shot. These are all installed by Linux Mint in a fresh install, or by AppImage. I cannot tell which.

I also have all of the libg*.so files in /home/mike/usr/lib/ which is the place that I assumed you require them.

So it is very possible that I don't understand what is required. I hope this helps you to understand what is in my system.

![screenshot from 2016-09-10 16-34-31](https://cloud.githubusercontent.com/assets/3854941/18411830/164bf652-7778-11e6-9559-1932a409a52f.png)
![screenshot from 2016-09-10 17-04-39](https://cloud.githubusercontent.com/assets/3854941/18411860/df8e0d3e-7778-11e6-9639-32c803264fec.png)

**Comment by probonopd** [comment]
@Windsurfer01 yes I think I understand and all I can tell you is *NOT* to change things in your base system but wait for @jonoomph to fix the AppImage. Otherwise you might __damage__ your base system.

**Comment by Windsurfer01** [comment]
Thanks. We certainly agree on not changing the base system. AppImage 
seems to have all the dependency hell of debs.

**Comment by jonoomph** [comment]
The AppImage should be fixed now. I can successfully run it on Mint 18. Please give this a try again, and re-open this ticket if it still breaks. Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot's AppImage. Thanks!
