### ISSUE TITLE
Name Sorting Project Files (Quality of Life Enhancement)

### ISSUE THREAD

**Issue by TharenaMelishka** [OpenShot/openshot-qt#3182]
When I select multiple files to import (Sequentially numbered), they don't import sequentially, so if I import say 12 files, I have to hunt them for the correct order.  

Can we get it so when we click on "name" at the top of project files it will sort alphabetically, and invert sort if we click it again?  

Also support the idea in #2436 where project files get folders, so if I have a multi segment video I could sort the files (audio / video / image) into the folders for ease of editing.  

Thanks!

**Comment by SuslikV** [comment]
This is feature request. Sorting option not implemented yet
