### ISSUE TITLE
OpenShot crashes when importing "incorrect" SVG file

### ISSUE THREAD

**Issue by Olfried2** [OpenShot/openshot-qt#3184]
**Describe the bug:**
OpenShot crashes when importing "incorrect" SVG file

_And BTW. I like the Idea to lead the people through a website to create a bug report ! But github threw an error. So I have to do this manually. (Not a big deal, just an information)_

**Steps to reproduce the behavior:**
1. Open a video project
2. import the ~/Videos/assets/TitleFileName-2.svg
3. OpenShot crashes

The _incorrect_ file -> [TitleFileName-2.svg.zip](https://github.com/OpenShot/openshot-qt/files/4080937/TitleFileName-2.svg.zip)

**Expected behavior:**
An error-message that this file doesn't meet the requirements to be imported or something like this.
Not just crash - the recovering of the project file was not the latest (as OpenShot crashed)

**System Details:**
OpenShot-v2.5.0-release-candidate-1578960720-x86_64 (more in logfiles)
Operating System / Distro: Linux-4.15.0-74-generic-x86_64-with-Ubuntu-18.04-bionic

**Log Files:**
[libopenshot.log.txt](https://github.com/OpenShot/openshot-qt/files/4080944/libopenshot.log.txt)
[openshot-qt.log.txt](https://github.com/OpenShot/openshot-qt/files/4080978/openshot-qt.log.txt)

**Exception / Stacktrace:**

**Comment by SuslikV** [comment]
Can be system specific. On Windows (some of the dev. 2.5.0 builds of OpenShot) the dropped file shows error message, like this:

![Error message on svg import (invalid file)](https://user-images.githubusercontent.com/19683044/72667980-738ed780-3a2a-11ea-847b-cc30a7371496.png)

And leaves the entry in the log:

>files_listview:WARNING Failed to import file: No Reader has been initialized for this Clip.  Call Reader(*reader) before calling this method.

No crash so far.

**Comment by ferdnyc** [comment]
Definitely crashes under Linux, with or without Resvg. Interestingly, it happens after the file is first sent through _FFmpegReader_. (I guess maybe as a fallback after `QtImageReader` fails to decode it. I haven't looked into it in more detail yet.)
