### ISSUE TITLE
Slice issue with media files opened from command line

### ISSUE THREAD

**Issue by Raph-2018** [OpenShot/openshot-qt#3185]
I have just tried the release candidate v2.5.0-1578960720 on linux xubuntu 14.04, and I noticed the following problem:

If I open a media file with Openshot from the file manager or via command line, and then I press Ctrl+K to slice it on the timeline, the video file is sliced a few seconds before the position of the red marker (see image attached). Of course, this is very annoying and prevents the user from being able to cut the video at an accurate time (moreover, the lapse of time seems to vary depending on the position of the red marker on the video).

Strangely enough, there is no such behavior when the media file is opened from inside Openshot.

I guess the issue could be related to the bug #2162 or #2355. I remember noticing a similar behavior with version 2.4.4 (the bug was so annoying I had to downgrade to the previous version).

![Screenshot](https://user-images.githubusercontent.com/42306896/72668188-6e2e8e80-3a24-11ea-8c8f-a062d0209e7d.jpg)

**Comment by SuslikV** [comment]
The screenshot says that cursor at `00:02:30` and frame `15`. What log-file says?

**Comment by Raph-2018** [comment]
@SuslikV: Here is what the log says when I press Ctrl+K:

[Log.txt](https://github.com/OpenShot/openshot-qt/files/4081520/Log.txt)

**Comment by Raph-2018** [comment]
I just noticed another strange thing: if I click on the menu "slice all - keep both" instead of pressing Ctrl+K, the video is properly sliced!

**Comment by SuslikV** [comment]
I think it is not affected by the keypress at all. But for sure, there is difference in how the profile applied. 
The default one called from the recover_backup() function...

`get_app().project.load("")`

What a mess. This string is also needed in `app.py` right before the file import:
```
                # Auto import media file
                self.window.filesTreeView.add_file(path)
```
