### ISSUE TITLE
fichier récent inconnu (Give your bug report a descriptive title) Ne retrouve pas les photos formant les derniers montages

### ISSUE THREAD

**Issue by Cornetdenis** [OpenShot/openshot-qt#3188]
**Describe the bug**
fichier récent inconnu

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 2.5.0
- libopenshot Version:  0.2.4
- Platform: Windows-10-10.0.18362
- Processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['fr-FR', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.0-release-candidate-1578960861-x86_64.exe

**Log Files**
- http://logs.openshot.org/9yly0asmar4mho0i93oigi8rmw0xk2bc/openshot-qt.zip
- http://logs.openshot.org/9yly0asmar4mho0i93oigi8rmw0xk2bc/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Captures d’écran** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by SuslikV** [comment]
Can you navigate to each file manually when OpenShot asking you for this?
