### ISSUE TITLE
Request - import help with Sony Ex1/3 files

### ISSUE THREAD

**Issue by jdjddjdj** [OpenShot/openshot-qt#3189]
Hello!
When I import Sony EX1/EX3 files into Openshot - video plays fine but no audio.

Importing these files have "traditionally" presented difficulties for various editing software, usually in the form of missing or muted audio files or duplicate entries in the footage bin.

The ideal workflow - Drag/drop BPAV folder = Openshot imports all the various clips from the various subfolders.

Can provide sample clips for testing.

Thank you - I have just discovered the wonderful resource that is Openshot
Awesome project. Go team!

cheers
jd

Sample file results from a file from my EX1 - "Project Files > File Properties"

{
    "acodec": "pcm_s16be",
    "audio_bit_rate": 1536000,
    "audio_stream_index": 1,
    "audio_timebase": {
        "den": 48000,
        "num": 1
    },
    "channel_layout": 3,
    "channels": 2,
    "display_ratio": {
        "den": 9,
        "num": 16
    },
    "duration": 475.9087829589844,
    "end": 475.8754,
    "file_size": "2147269245",
    "fps": {
        "den": 1001,
        "num": 30000
    },
    "has_audio": true,
    "has_single_image": false,
    "has_video": true,
    "height": 1080,
    "id": "HGCLWE7S7Z",
    "interlaced_frame": false,
    "media_type": "video",
    "metadata": {
        "compatible_brands": "mp42",
        "creation_time": "2020-01-19T16:38:23.000000Z",
        "handler_name": "Sound Media Handler",
        "language": "eng",
        "major_brand": "mp42",
        "minor_version": "0"
    },
    "name": "COIN0125_08.MP4",
    "path": "/name/changed/chip vbackup/BPAV/CLPR/COIN0125_08/COIN0125_08.MP4",
    "pixel_format": 0,
    "pixel_ratio": {
        "den": 1,
        "num": 1
    },
    "sample_rate": 48000,
    "start": 0.0,
    "tags": "",
    "top_field_first": true,
    "type": "FFmpegReader",
    "vcodec": "mpeg2video",
    "video_bit_rate": 4511934,
    "video_length": "14263",
    "video_stream_index": 0,
    "video_timebase": {
        "den": 30000,
        "num": 1
    },
    "width": 1920
}

**Comment by SuslikV** [comment]
If format not supported by FFmpeg there is not so much you can do. Extract the raw streams and try to add it to OpenShort one by one or so.

If possible, share short file sample with some sound inside, about 1..2 sec long. I can check if it playbacks on my end.

**Comment by ferdnyc** [comment]
@jdjddjdj As @SuslikV says, sample files would be needed, as the file _appears_ to be identified successfully for both video and audio. I would expect it to play with sound, unless the audio data **isn't** actually 48kHz stereo PCM signed 16-bit big endian @ 1.5Mbps.

In terms of verifying the file encoding (or, debugging the decoding process), a sample clip of the camera's standard test pattern (color bars + reference tone) would actually be the _most_ helpful.
