### ISSUE TITLE
Openshot after r671 wont start.

### ISSUE THREAD

**Issue by firew4lker** [OpenShot/openshot-qt#319]
After the commit (r672) fir the new Memory and Disk caching frameworks, Openshot fails to star on Archlinux 32 bit. libopenshot r549. Reverting to Openshot r671, will start.

Unhandled Python exception
Aborted (core dumped)

PID: 9145 (python3)
           UID: 1000 (koko)
           GID: 100 (users)
        Signal: 6 (ABRT)
     Timestamp: Thu 2016-09-08 11:40:26 EEST (52s ago)
  Command Line: python3 ./launch.py
    Executable: /usr/bin/python3.5
 Control Group: /user.slice/user-1000.slice/session-c1.scope
          Unit: session-c1.scope
         Slice: user-1000.slice
       Session: c1
     Owner UID: 1000 (koko)
       Boot ID: 46ba0b49987c4a568ce7aebb01fb3aac
    Machine ID: f920fb68b4c4974cd0aae6e80000022a
      Hostname: laptop
      Coredump: /var/lib/systemd/coredump/core.python3.1000.46ba0b49987c4a568ce7aebb01fb3aac.9145.1473324026000000000000.lz4
       Message: Process 9145 (python3) of user 1000 dumped core.
                
                Stack trace of thread 9145:
                #0  0x00000000b76f6d41 __kernel_vsyscall (linux-gate.so.1)
                #1  0x00000000b7202e70 raise (libc.so.6)
                #2  0x00000000b7204397 abort (libc.so.6)
                #3  0x00000000b540adb3 _ZNK14QMessageLogger5fatalEPKcz (libQt5Core.so.5)
                #4  0x00000000b2be9913 n/a (QtCore.so)
                #5  0x00000000b2be007d n/a (QtCore.so)
                #6  0x00000000b2be0bbe n/a (QtCore.so)
                #7  0x00000000b5623cf0 _ZN11QMetaObject8activateEP7QObjectiiPPv (libQt5Core.so.5)
                #8  0x00000000b56243fd _ZN11QMetaObject8activateEP7QObjectPKS_iPPv (libQt5Core.so.5)
                #9  0x00000000b56a4aa2 _ZN6QTimer7timeoutENS_14QPrivateSignalE (libQt5Core.so.5)
                #10 0x00000000b5631801 _ZN6QTimer10timerEventEP11QTimerEvent (libQt5Core.so.5)
                #11 0x00000000b2a95032 n/a (QtCore.so)
                #12 0x00000000b5624956 _ZN7QObject5eventEP6QEvent (libQt5Core.so.5)
                #13 0x00000000b2a94f92 n/a (QtCore.so)
                #14 0x00000000b5ec620a _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
                #15 0x00000000b5ece09c _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
                #16 0x00000000b666b7a3 n/a (QtWidgets.so)
                #17 0x00000000b55f617d _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
                #18 0x00000000b564e5ed _ZN14QTimerInfoList14activateTimersEv (libQt5Core.so.5)
                #19 0x00000000b564ec39 n/a (libQt5Core.so.5)
                #20 0x00000000b4b23d09 g_main_context_dispatch (libglib-2.0.so.0)
                #21 0x00000000b4b23fa9 n/a (libglib-2.0.so.0)
                #22 0x00000000b4b24074 g_main_context_iteration (libglib-2.0.so.0)
                #23 0x00000000b564f7f3 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (li
                #24 0x00000000a2e5bc21 n/a (libQt5XcbQpa.so.5)
                #25 0x00000000b55f6240 _ZN16QCoreApplication13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5
                #26 0x00000000b2b7139d n/a (QtCore.so)
                #27 0x00000000b74335a3 PyCFunction_Call (libpython3.5m.so.1.0)
                #28 0x00000000b74ad39c PyEval_EvalFrameEx (libpython3.5m.so.1.0)
                #29 0x00000000b74ae347 n/a (libpython3.5m.so.1.0)
                #30 0x00000000b74aad6e PyEval_EvalFrameEx (libpython3.5m.so.1.0)
                #31 0x00000000b74ac47b PyEval_EvalFrameEx (libpython3.5m.so.1.0)
                #32 0x00000000b74ae347 n/a (libpython3.5m.so.1.0)
                #33 0x00000000b74157f8 n/a (libpython3.5m.so.1.0)
                #34 0x00000000b73e7601 PyObject_Call (libpython3.5m.so.1.0)
                #35 0x00000000b73ff8fc n/a (libpython3.5m.so.1.0)
                #36 0x00000000b73e7601 PyObject_Call (libpython3.5m.so.1.0)
                #37 0x00000000b744a3f7 n/a (libpython3.5m.so.1.0)
                #38 0x00000000b7448543 n/a (libpython3.5m.so.1.0)
                #39 0x00000000b73e7601 PyObject_Call (libpython3.5m.so.1.0)
                #40 0x00000000b74a8acc PyEval_EvalFrameEx (libpython3.5m.so.1.0)
                #41 0x00000000b74ae347 n/a (libpython3.5m.so.1.0)
                #42 0x00000000b74157f8 n/a (libpython3.5m.so.1.0)
                #43 0x00000000b73e7601 PyObject_Call (libpython3.5m.so.1.0)
                #44 0x00000000b73ff8fc n/a (libpython3.5m.so.1.0)
                #45 0x00000000b73e7601 PyObject_Call (libpython3.5m.so.1.0)
                #46 0x00000000b744a3f7 n/a (libpython3.5m.so.1.0)
                #47 0x00000000b7448543 n/a (libpython3.5m.so.1.0)
                #48 0x00000000b73e7601 PyObject_Call (libpython3.5m.so.1.0)
                #49 0x00000000b74a8acc PyEval_EvalFrameEx (libpython3.5m.so.1.0)
                #50 0x00000000b74ae347 n/a (libpython3.5m.so.1.0)
                #51 0x00000000b74157f8 n/a (libpython3.5m.so.1.0)
                #52 0x00000000b73e7601 PyObject_Call (libpython3.5m.so.1.0)
                #53 0x00000000b73ff8fc n/a (libpython3.5m.so.1.0)
                #54 0x00000000b73e7601 PyObject_Call (libpython3.5m.so.1.0)
                #55 0x00000000b744a3f7 n/a (libpython3.5m.so.1.0)
                #56 0x00000000b7448543 n/a (libpython3.5m.so.1.0)
                #57 0x00000000b73e7601 PyObject_Call (libpython3.5m.so.1.0)
                #58 0x00000000b74a8acc PyEval_EvalFrameEx (libpython3.5m.so.1.0)
                #59 0x00000000b74ac47b PyEval_EvalFrameEx (libpython3.5m.so.1.0)
                #60 0x00000000b74ae347 n/a (libpython3.5m.so.1.0)
                #61 0x00000000b74ae4b0 PyEval_EvalCode (libpython3.5m.so.1.0)
                #62 0x00000000b74ce29b n/a (libpython3.5m.so.1.0)
                #63 0x00000000b74d09d3 PyRun_FileExFlags (libpython3.5m.so.1.0)
                
                Stack trace of thread 9150:
                #0  0x00000000b76f6d41 __kernel_vsyscall (linux-gate.so.1)
                #1  0x00000000b72b615f poll (libc.so.6)
                #2  0x00000000a66bd679 zmq_poll (libzmq.so.5)
                #3  0x00000000a68c1509 n/a (_poll.cpython-35m-i386-linux-gnu.so)
                #4  0x00000000a68c2caf n/a (_poll.cpython-35m-i386-linux-gnu.so)
                #5  0x00000000b74335a3 PyCFunction_Call (libpython3.5m.so.1.0)
                #6  0x00000000b74ac015 PyEval_EvalFrameEx (libpython3.5m.so.1.0)
                #7  0x00000000b74ae347 n/a (libpython3.5m.so.1.0)
                #8  0x00000000b74aad6e PyEval_EvalFrameEx (libpython3.5m.so.1.0)
                #9  0x00000000b74ac47b PyEval_EvalFrameEx (libpython3.5m.so.1.0)
                #10 0x00000000b74ac47b PyEval_EvalFrameEx (libpython3.5m.so.1.0)
                #11 0x00000000b74ae347 n/a (libpython3.5m.so.1.0)
                #12 0x00000000b74157f8 n/a (libpython3.5m.so.1.0)
                #13 0x00000000b73e7601 PyObject_Call (libpython3.5m.so.1.0)
                #14 0x00000000b73ff8fc n/a (libpython3.5m.so.1.0)
                #15 0x00000000b73e7601 PyObject_Call (libpython3.5m.so.1.0)
                #16 0x00000000b74a46fc PyEval_CallObjectWithKeywords (libpython3.5m.so.1.0)
                #17 0x00000000b74eacf5 n/a (libpython3.5m.so.1.0)
                #18 0x00000000b7396301 start_thread (libpthread.so.0)
                #19 0x00000000b72c00ae __clone (libc.so.6)
                
                Stack trace of thread 9158:
                #0  0x00000000b76f6d41 __kernel_vsyscall (linux-gate.so.1)
                #1  0x00000000b72b615f poll (libc.so.6)
                #2  0x00000000b4b32430 g_poll (libglib-2.0.so.0)
                #3  0x00000000b4b23f3c n/a (libglib-2.0.so.0)
                #4  0x00000000b4b24074 g_main_context_iteration (libglib-2.0.so.0)
                #5  0x00000000b564f7f3 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (li
                #6  0x00000000b55f423d _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                #7  0x00000000b5420215 _ZN7QThread4execEv (libQt5Core.so.5)
                #8  0x00000000b24fa09c n/a (libQt5DBus.so.5)
                #9  0x00000000b54256ba n/a (libQt5Core.so.5)
                #10 0x00000000b7396301 start_thread (libpthread.so.0)
                #11 0x00000000b72c00ae __clone (libc.so.6)
                
                Stack trace of thread 9147:
                #0  0x00000000b76f6d41 __kernel_vsyscall (linux-gate.so.1)
                #1  0x00000000b72b615f poll (libc.so.6)
                #2  0x00000000b476294d n/a (libxcb.so.1)
                #3  0x00000000b4764cc3 xcb_wait_for_event (libxcb.so.1)
                #4  0x00000000a2e221d3 n/a (libQt5XcbQpa.so.5)
                #5  0x00000000b54256ba n/a (libQt5Core.so.5)
                #6  0x00000000b7396301 start_thread (libpthread.so.0)
                #7  0x00000000b72c00ae __clone (libc.so.6)
                
                Stack trace of thread 9152:
                #0  0x00000000b76f6d41 __kernel_vsyscall (linux-gate.so.1)
                #1  0x00000000b72c087a epoll_wait (libc.so.6)
                #2  0x00000000a66803e0 n/a (libzmq.so.5)
                #3  0x00000000a66b71d8 n/a (libzmq.so.5)
                #4  0x00000000b7396301 start_thread (libpthread.so.0)
                #5  0x00000000b72c00ae __clone (libc.so.6)
                
                Stack trace of thread 9165:
                #0  0x00000000b76f6d41 __kernel_vsyscall (linux-gate.so.1)
                #1  0x00000000b72b615f poll (libc.so.6)
                #2  0x00000000b4b32430 g_poll (libglib-2.0.so.0)
                #3  0x00000000b4b23f3c n/a (libglib-2.0.so.0)
                #4  0x00000000b4b24074 g_main_context_iteration (libglib-2.0.so.0)
                #5  0x00000000b564f7f3 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (li
                #6  0x00000000b55f423d _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                #7  0x00000000b5420215 _ZN7QThread4execEv (libQt5Core.so.5)
                #8  0x00000000b54202f8 _ZN7QThread3runEv (libQt5Core.so.5)
                #9  0x00000000b54256ba n/a (libQt5Core.so.5)
                #10 0x00000000b7396301 start_thread (libpthread.so.0)
                #11 0x00000000b72c00ae __clone (libc.so.6)
                
                Stack trace of thread 9154:
                #0  0x00000000b76f6d41 __kernel_vsyscall (linux-gate.so.1)
                #1  0x00000000b72c087a epoll_wait (libc.so.6)
                #2  0x00000000a66803e0 n/a (libzmq.so.5)
                #3  0x00000000a66b71d8 n/a (libzmq.so.5)
                #4  0x00000000b7396301 start_thread (libpthread.so.0)
                #5  0x00000000b72c00ae __clone (libc.so.6)
                
                Stack trace of thread 9160:
                #0  0x00000000b76f6d41 __kernel_vsyscall (linux-gate.so.1)
                #1  0x00000000b739bc8b pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                #2  0x00000000b0abc296 n/a (libQt5WebKit.so.5)
                #3  0x00000000b0abc2ec n/a (libQt5WebKit.so.5)
                #4  0x00000000b7396301 start_thread (libpthread.so.0)
                #5  0x00000000b72c00ae __clone (libc.so.6)
                
                Stack trace of thread 9164:
                #0  0x00000000b76f6d41 __kernel_vsyscall (linux-gate.so.1)
                #1  0x00000000b739bc8b pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                #2  0x00000000b0aeab8c _ZN3WTF15ThreadCondition4waitERNS_5MutexE (libQt5WebKit.so.5)
                #3  0x00000000b07b19b5 n/a (libQt5WebKit.so.5)
                #4  0x00000000b0aea591 n/a (libQt5WebKit.so.5)
                #5  0x00000000b7396301 start_thread (libpthread.so.0)
                #6  0x00000000b72c00ae __clone (libc.so.6)
                
                Stack trace of thread 9161:
                #0  0x00000000b76f6d41 __kernel_vsyscall (linux-gate.so.1)
                #1  0x00000000b739c055 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                #2  0x00000000b0aeac37 _ZN3WTF15ThreadCondition9timedWaitERNS_5MutexEd (libQt5WebKit.so.5)
                #3  0x00000000b07b0680 n/a (libQt5WebKit.so.5)
                #4  0x00000000b0aea591 n/a (libQt5WebKit.so.5)
                #5  0x00000000b7396301 start_thread (libpthread.so.0)
                #6  0x00000000b72c00ae __clone (libc.so.6)
                
                Stack trace of thread 9151:
                #0  0x00000000b76f6d41 __kernel_vsyscall (linux-gate.so.1)
                #1  0x00000000b72c087a epoll_wait (libc.so.6)
                #2  0x00000000a66803e0 n/a (libzmq.so.5)
                #3  0x00000000a66b71d8 n/a (libzmq.so.5)
                #4  0x00000000b7396301 start_thread (libpthread.so.0)
                #5  0x00000000b72c00ae __clone (libc.so.6)
                
                Stack trace of thread 9155:
                #0  0x00000000b76f6d41 __kernel_vsyscall (linux-gate.so.1)
                #1  0x00000000b72c087a epoll_wait (libc.so.6)
                #2  0x00000000a66803e0 n/a (libzmq.so.5)
                #3  0x00000000a66b71d8 n/a (libzmq.so.5)
                #4  0x00000000b7396301 start_thread (libpthread.so.0)
                #5  0x00000000b72c00ae __clone (libc.so.6)
                
                Stack trace of thread 9162:
                #0  0x00000000b76f6d41 __kernel_vsyscall (linux-gate.so.1)
                #1  0x00000000b739bc8b pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                #2  0x00000000b0aeab8c _ZN3WTF15ThreadCondition4waitERNS_5MutexE (libQt5WebKit.so.5)
                #3  0x00000000b07b19b5 n/a (libQt5WebKit.so.5)
                #4  0x00000000b0aea591 n/a (libQt5WebKit.so.5)
                #5  0x00000000b7396301 start_thread (libpthread.so.0)
                #6  0x00000000b72c00ae __clone (libc.so.6)
                
                Stack trace of thread 9163:
                #0  0x00000000b76f6d41 __kernel_vsyscall (linux-gate.so.1)
                #1  0x00000000b739bc8b pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                #2  0x00000000b0aeab8c _ZN3WTF15ThreadCondition4waitERNS_5MutexE (libQt5WebKit.so.5)
                #3  0x00000000b07b19b5 n/a (libQt5WebKit.so.5)
                #4  0x00000000b0aea591 n/a (libQt5WebKit.so.5)
                #5  0x00000000b7396301 start_thread (libpthread.so.0)
                #6  0x00000000b72c00ae __clone (libc.so.6)

**Comment by jonoomph** [comment]
Just committed some fixes to the CacheDisk and CacheMemory objects related to this bug. Fingers crossed the new version will work for you. If not, please reopen this bug. Thx!
