### ISSUE TITLE
Project auto save exception

### ISSUE THREAD

**Issue by millpaub** [OpenShot/openshot-qt#3190]
**Describe the bug**
On export, the process shuts down about 40% through the process. No errors are displayed.
Loaded the lasts daily build with no noticeable changes.

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 2.5.0
- libopenshot Version:  0.2.4
- Platform: Windows-10-10.0.18362
- Processor: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.0-release-candidate-1579485252-x86_64.exe

**Log Files**
- http://logs.openshot.org/u1865iylv5rpuxeaeugln87qurlf78u9/openshot-qt.zip
- http://logs.openshot.org/u1865iylv5rpuxeaeugln87qurlf78u9/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by ferdnyc** [comment]
```
Traceback (most recent call last):
  File "C:\Program Files\OpenShot Video Editor\windows\main_window.py", line 643, in auto_save_project
    recover_path_with_timestamp = os.path.join(info.RECOVERY_PATH, "%d-%s.osp" % (int(time()), file_name))
TypeError: 'module' object is not callable
     metrics:INFO Track exception: [200] http://www.openshot.org/exception/json/ | *failed-recording-exception*: Control/space characters not allowed (key=b":1:Windows-2.5.0-TypeError: 'module' object is no")
 main_window:INFO auto_save_project
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "C:\Program Files\OpenShot Video Editor\windows\main_window.py", line 643, in auto_save_project
    recover_path_with_timestamp = os.path.join(info.RECOVERY_PATH, "%d-%s.osp" % (int(time()), file_name))
```

Thanks for the report. This should be easy to fix, it looks like a recent bug introduced into the autosave routine.

**Comment by ferdnyc** [comment]
@millpaub 

Hopefully #3191 will fix this, if and when it merges we'll have a new Daily Build for testing. But in the meantime, it looks like you're getting bit by a slightly weird autosave bug, so the workaround would be to simply turn off autosave (in the Preferences).

**Comment by millpaub** [comment]
Thanks for the reply.
 I think I found the problem.
The computer had been replaced and not all of the settings had been updated on the new computer. I moved the files to another machine and completed the export on it. During that time, I was reviewing what had happened during export on the other computer. I noticed on the export panel that the “cancel” button is highlighted when the export is processing. 
What happened was the screen delay was set to 15 minutes, once it went blank, I would hit the return key, which canceled the export. Is there a way to alter the program in such a way that it doesn’t automatically highlight the “cancel” button?
I suspect other users may have experienced the same problem and thought it was the export routine was the problem.
I set the screen blanking delay to 2 hours, my longest videos are shorter than that.

Thank you for your help.
Paul

**Comment by SuslikV** [comment]
>... I noticed on the export panel that the “cancel” button is highlighted when the export is processing.

Because there is no other button available when process of video export already started, only new confirmation dialog can be added, like "OpenShot's export. Are you sure wish to cancel the video export? Yes/No." where "No" can be default button. Is this OK solution? I usually don't like a lot of confirmations but rendering can be time consuming task and restarting it will be boring.

**Comment by ferdnyc** [comment]
> The computer had been replaced and not all of the settings had been updated on the new computer. I moved the files to another machine and completed the export on it. During that time, I was reviewing what had happened during export on the other computer. I noticed on the export panel that the “cancel” button is highlighted when the export is processing. What happened was the screen delay was set to 15 minutes, once it went blank, I would hit the return key, which canceled the export. Is there a way to alter the program in such a way that it doesn’t automatically highlight the “cancel” button?

It's worth looking into, sure.

Though, at the same time — not to try and redirect the issue, and like I said I do agree the input-focused Cancel is worth trying to correct — I'd recommend getting in the habit of unblanking your screen with a "known-safe" keypress. I use <kbd>Shift</kbd>, personally. Nothing will _ever_ happen as a side-effect of pressing <kbd>Shift</kbd>. :laughing:

**Comment by ferdnyc** [comment]
@SuslikV 

Yeah, thinking about it more, a confirmation dialog probably makes more sense than worrying about input focus.

...Just as long as "Yes" isn't the default response on the confirmation dialog, or we're right back where we started. :wink:

**Comment by SuslikV** [comment]
@ferdnyc many people right-handed, it is easy to miss the <kbd>Shift</kbd> button and press <kbd>Enter</kbd> instead...

I made PR (https://github.com/OpenShot/openshot-qt/pull/3193) to add confirmation dialog. Maybe it worth to look at.

**Comment by ferdnyc** [comment]
> @ferdnyc many people right-handed, it is easy to miss the Shift button and press Enter instead...

Of course. Nothing's foolproof. But it sounds very much like @millpaub was _aiming_ for <kbd>Enter</kbd>, nothing accidental about it.

Heck, if someone's really worried about missing <kbd>Shift</kbd>, they can always aim for <kbd>Ctrl</kbd>, and then if they miss they'll hit <kbd>Shift</kbd> or <kbd>Menu</kbd>. Point is, modifier keys are especially good choices for "no-consequence" input events, since they rarely have any significant effect unless combined with another key.
