### ISSUE TITLE
try to connect openshot software with node and ejs is it possible?

### ISSUE THREAD

**Issue by jatingajera31** [OpenShot/openshot-qt#3195]
try to connect openshot software with node and ejs is it possible?

**Comment by ferdnyc** [comment]
@jatingajera31

OpenShot _itself_ isn't really instrumented for any sort of external message-passing or communication with other software. There are more possibilities in using its underlying library **[libopenshot](https://github.com/OpenShot/libopenshot/)**. In _theory_ JavaScript bindings could be generated with SWIG, and libopenshot could be used from JS code the same way OpenShot uses it from Python code. However, currently no JS bindings exist for libopenshot.
