### ISSUE TITLE
Is there a way to transform images/videos mid-video w/o smooth transitions?

### ISSUE THREAD

**Issue by chanonlim** [OpenShot/openshot-qt#3196]
**Question:**
I want to make a video and I want to have the images scaled mid-video but I don't want the smooth transitions while I'm scaling it. Is there a way to do this?

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 2.4.1
- Operating System / Distro: Ubuntu 18.04

**Comment by SuslikV** [comment]
Yes, but is hard to achieve with cursor or menus in current version of OpenShot. You need _Properties_ panel of the clip and change the interpolation type of the animated segment to _Constant_ (there is number of opened bugs that makes its even harder ^_^).

Do you want to scale up 200% and back it to 100% (100%-200%-100%, like)?

**Comment by chanonlim** [comment]
Basically these values would probably have to change all over the place because I may, say only one to use 1 screenshot and zoom in certain positions.

On Sat, Jan 25, 2020, 00:43 SuslikV <notifications@github.com<mailto:notifications@github.com>> wrote:

Yes, but is hard to achieve with cursor or menus in current version of OpenShot. You need Properties panel of the clip and change the interpolation type of the animated segment to Constant (there is number of opened bugs that makes its even harder ^_^).

Do you want to scale up 200% and back it to 100% (100%-200%-100%, like)?

**Comment by SuslikV** [comment]
It is far easier to prepare number of already pre-zoomed images and import them into OpenShot. Then just place them in the right position on _Timeline_.

**Comment by chanonlim** [comment]
Ah, OK. Thanks!
