### ISSUE TITLE
Switching between transition and image - property editor keeps old properties

### ISSUE THREAD

**Issue by TharenaMelishka** [OpenShot/openshot-qt#3198]
Could not find reported

**Describe the bug:**
Clicking to change editing from a transition to an image, the properties changes the selection to the image but the properties remain the transition's and not the image properties.  

**Steps to reproduce the behavior:**
I have a file with multiple clips (30+) split between images and short video, with transitions for each clip.  While this could be an artifact of heavy load on OS, here is reproduction.

1.  Drag png image (screen shot from OS imported back into OS) to track.
2.  Drag transition to start of image and edit length to 2 sec (any transition)
3.  Click directly on image attached to transition.  -- this should show issue in properties (see screenshot)

Note:  this doesn't seem to happen every time, and I'm not sure how reproduce-able it is.

Workaround - Click from the transition to empty track space to clear properties, then click on the image.

**Expected behavior:**
I expected to see the properties of my image, not the transition.

**System Details:**
- OpenShot Version 2.5.0 Dev 1
- Operating System Windows 10

**Log Files:**
No log

**Exception / Stacktrace:**
N/A

**Screenshots:** (Optional)
See attached where image is selected, but properties show transition properties instead of image properties.

![2020-01-24 (2)](https://user-images.githubusercontent.com/9803487/73098335-280b7c00-3eb7-11ea-9180-a871ed8e1acd.png)

**Comment by SuslikV** [comment]
As soon as it happens, please post the log-file from the OpenShot session. Maybe it will help to resolve the issue.

**Comment by TharenaMelishka** [comment]
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/4146120/openshot-qt.log)
[openshot-qt.log.1.log](https://github.com/OpenShot/openshot-qt/files/4146127/openshot-qt.log.1.log)
[openshot-qt.log.2.log](https://github.com/OpenShot/openshot-qt/files/4146128/openshot-qt.log.2.log)
[openshot-qt.log.3.log](https://github.com/OpenShot/openshot-qt/files/4146131/openshot-qt.log.3.log)

..... Libopenshot.log is currently 130,680,295kb... even Word told me to go to hell.  :) So... I'm assuming you want one of the openshot-qt logs.  Cause I'm not giving Git the option of giving me the bird on that one. :)  I saw the .1 .2 and .3 and wasn't sure if you needed those, so I renamed extension to log to upload, then reverted them so I could keep editing without blowing up my session.  

Screenshot clearly shows a selection in the properties of the clip on track 5, while I have the clip on track 4 selected.  Side-by-side of a video clip + replay mod clip time sync'ed.  Just trying to put a set of closing keyframes on to return to the main video on Track 5, then clipping the other tracks to mate with track 4.  

![2020-02-02](https://user-images.githubusercontent.com/9803487/73623667-c44a2700-460b-11ea-8383-0827745994fd.png)

I've taken no actions since the error occurred except for going into the upper menus to see if there was a capture active log option in them.  Hope it helps!

**Comment by SuslikV** [comment]
It seems that the
`self.update_timer.stop()` in `properties_model.py`
was called from the
`update_model(self, filter="")` in `properties_model.py`

right **before** the
`update_item_timeout(self)` was called by the timer's end. That function carries next series of calls to update the _Property_ list and it performs call for the `update_model(self, filter="")` in the end.

I think, that when the `self.update_timer.start()` was triggered the call for `update_model(self, filter="")` **from everything else** should be suspended until the `update_item_timeout(self)` will call for it and ends its own staff.

The signal was delivered up to `update_item(self, item_id, item_type)` of the `properties_model.py` and on the screenshot above the label of the _Properties_ menu button was updated to the new file, while properties was left from the previous selection.

@TharenaMelishka the info above is for developers if there any...
