### ISSUE TITLE
Sound and picture are out of sync

### ISSUE THREAD

**Issue by cws999** [OpenShot/openshot-qt#3199]
Play the original video， Sound and picture are out of sync。
Play the  the edited video，Sound and picture are out of sync，too。
openshot=2.4.3
OS=debian buster
RAM=4G
cpu=Intel(R) Core(TM) i5-3427U CPU @ 1.80GHz

**Comment by SuslikV** [comment]
Try latest daily build or compile from the source.

Because not much info on the issue was given, I assuming that it is similar to:
https://github.com/OpenShot/openshot-qt/issues/2828#issuecomment-524439710
