### ISSUE TITLE
Minor issue with clip  thumbnail generation.

### ISSUE THREAD

**Issue by firew4lker** [OpenShot/openshot-qt#32]
When spliting a clip the thumbnail for the new clip is wrong. It keeps the first frame of the clip, before the split.

http://i.imgur.com/Zn2MRCP.png
http://i.imgur.com/XCVHRp7.png

**Comment by jonoomph** [comment]
Nice catch. I've fixed the thumbnails for the right-side clips, and also fixed an issue that would sometimes break audio on the newly created clip. Thanks! =)
