### ISSUE TITLE
Fix: deprecated pixel format used, make sure you did set range correctly

### ISSUE THREAD

**Issue by PanderMusubi** [OpenShot/openshot-qt#320]
What is causing these errors/warnings on the command line and how can these be fxied? `[swscaler @ 0x7423b60] deprecated pixel format used, make sure you did set range correctly`

**Comment by joshuacox** [comment]
just chiming in, I have the same problem here with latest openshot in arch linux, anyone ever find a fix?

**Comment by emilhem** [comment]
I have the same issue. The video that caused the message for me was recorded on a OnePlus 3.

**Comment by DylanC** [comment]
@PanderMusubi - I will investigate and come back to you.

**Comment by DylanC** [comment]
I don't think this message will affect anything but I'm putting this here for the devs in case we need to change something:

https://stackoverflow.com/questions/23067722/swscaler-warning-deprecated-pixel-format-used

**Comment by DylanC** [comment]
@jonoomph - Do you have any ideas about this one?
