### ISSUE TITLE
Export to '/tmp' on Linux always claims that the output file "already exists"

### ISSUE THREAD

**Issue by ferdnyc** [OpenShot/openshot-qt#3200]
**Update**: See https://github.com/OpenShot/openshot-qt/issues/3200#issuecomment-581657130, the issue isn't as serious or widespread as I initially believed.

It's kind of a minor thing, really, but it should also be easy enough to fix that I think we should correct it before merging #3161 for the final 2.5.0 release.

It seems that some confusion in the output path handling code for the export dialog is causing it to _always_ claim that the destination file already exists, even when it doesn't. It's not a huge problem, but it is a significant annoyance.

**Steps to reproduce the behavior:**
1. Create a project
2. Open the Export window
3. Set File Name to "mystupidname.mp4" and Folder Path to "/tmp"
4. Click "Export Video"
5. A "mystupidname.mp4 already exists" dialog pops up.

**Expected behavior:**
No "file already exists" dialog.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 2.5.0-rc / `develop` branch
- Operating System / Distro: Fedora 31 (but presumed to affect all platforms)

cc: @jonoomph

**Comment by SuslikV** [comment]
>... 3\. Set File Name to "mystupidname.mp4" and Folder Path to "/tmp" or something similar

Please, clarify in which way the p.3 should be complete. By typing new path?

**Comment by ferdnyc** [comment]
@SuslikV My mistake, it appears this issue _only_ occurs when exporting into `/tmp` (on Linux), because this code:
https://github.com/OpenShot/openshot-qt/blob/eb7ecbb424d23bfab5507ce282ff277dd4496223/src/windows/export.py#L724-L731

...creates a "temporary" file using the export filename in `/tmp` (again, on Linux), and then never deletes it.

So, a file _does_ already exist at the target path, when the export process goes to write there — because it was created in literally the same function, just like 20 lines previous.

**Comment by ferdnyc** [comment]
I kind of hate that code, anyway. There are way better ways to check a filename's validity... the most obvious being, just trying to create the _actual_ output file. Why go through all this extra hassle? It's just silliness that seems like it's needlessly complicating the process.

Especially since it doesn't clean up after itself. What if the file it's opening for writing already exists as a _real_ file? It doesn't check first, so that `open(..., 'w')` just truncated what _used_ to be valid user data. That's awful.

**Comment by SuslikV** [comment]
Would you like to make a fix for this? Also, using "default filename" by silently substituting the original name is not the best option, anyway the user will not find the exported file.

And yes, deleting the just created file is good option!

I did some checks:
* checked `os.path.exists` with invalid file name on Windows returns _False_ and no exception.
* The open() for writing (or reading) with the invalid filename rises exception, like:
`Error type string: [Errno 22] Invalid argument:...`
* The open() for reading with not existing valid filename rises exception, like:
`Error type string: [Errno 2] No such file or directory:...`

Short info on filename checks across OSes:
https://stackoverflow.com/questions/3038351/check-whether-a-string-is-a-valid-filename-with-qt

**Comment by ferdnyc** [comment]
> Would you like to make a fix for this? Also, using "default filename" by silently substituting the original name is not the best option, anyway the user will not find the exported file.
> 
> And yes, deleting the just created file is good option!
> 
> I did some checks:
> 
> * The _os.path.exists()_ with invalid filename on Windows returns _False_ and no exception.
> * The _open()_ for writing (or reading) with the invalid filename rises exception, like:
>   `Error type string: [Errno 22] Invalid argument:...`
> * The _open()_ for reading with not existing valid filename rises exception, like:
>   `Error type string: [Errno 2] No such file or directory:...`
> 
> **Edit:** some slash and back_slash combinations considered as part of the path.
> 
> Short info on filename checks across OSes:
> https://stackoverflow.com/questions/3038351/check-whether-a-string-is-a-valid-filename-with-qt

Yeah... though really, the conclusion there is, "There's no easy way to validate filenames, except by creating files", so that part's fair. (Truth is, on modern Linux filesystems, the _only_ UTF-8 glyph that's not permitted in a filename is `/`. HFS+ is much the same, with the possible addition of `:` for legacy MacOS compatibility. So really, we're talking about Windows, and this other (linked-related) answer goes into more detail on those headaches: https://stackoverflow.com/questions/62771/how-do-i-check-if-a-given-string-is-a-legal-valid-file-name-under-windows)

But I'm convinced the only reason this is there is because OpenShot **doesn't** properly deal with situations where libopenshot fails to create the requested file — IOW, it's trying to work around bad program behavior by adding _more_ bad program behavior, which is like falling in a hole and trying to dig your way out.

> Also, using "default filename" by silently substituting the original name is not the best option, anyway the user will not find the exported file.

You're right, I didn't even spot that (like I said, there aren't really such thing as invalid filenames in Linux) — that's awful, too. I mean, if we're gonna just _change_ the user's filename (and, we shouldn't just **change** the user's filename for them), then we should _at least_ TELL them we changed it. Yeah, this is another area where our [balance](https://github.com/OpenShot/openshot-qt/pull/3158#issuecomment-573385312) is way off.

From my POV, at least, the right fix for this is for OpenShot to do LESS. It should just hand libopenshot whatever filename the user provided (or left as the default), just like any other parameter in the export dialog. No worrying about validating it or whatever, beforehand, just pass it along. Libopenshot will try to create the file, because that's ITS job, and if it can't then it should pass the error information back to OpenShot so it can be displayed to the user. The user can then correct the problem, because that's _their_ job.

And as an added bonus, fixing this for real would _also_ allow us to fix suddenly-related issue #2881. File creation issues are NOT the only reason the encoding process can fail before it even starts, though they are one example. ALL of those situations, regardless of cause or nature, need to be handled the same way: we display a helpful error message, and re-enable the export dialog so the user can adjust their settings and try again.  (Bonus points if we even manage to do that for "failed" exports that don't fail due to encoding issues — the ones that abort because they run out of space on the disk, or whatever. Those, too, should prompt a **return** to the export dialog, rather than a "Done" button that closes it and throws away the user's selections.)

> Would you like to make a fix for this?

Mmm, yeah now that I seem to have talked myself into making it a bigger thing than it needs to be (as usual), I think I'm going to focus on the libopenshot side of it — like I said, if we can get libopenshot to the point where it's communicating useful information to OpenShot about the errors it encounters, then OpenShot can simply react to those errors appropriately, instead of trying to do overcomplicated nonsense just to try and avoid the errors in the first place.

**Comment by SuslikV** [comment]
If temporal solution will look like this dialog?
```
Filename invalid.
The entered File Name and Folder Path invalid. Probably, you have entered combination of symbols that are not supported by the system. Type new File Name and use Browse button for Folder Path.
```
`Default Filename and Path` `Change Manually`

**Comment by Giszmo** [comment]
This behaviour was never fixed.

I sometimes want to create a video to send it and not store it, so I want to be able to create it in /tmp. Please fix this!
