### ISSUE TITLE
imported video 1080p in black box

### ISSUE THREAD

**Issue by MPPlantOfficial** [OpenShot/openshot-qt#3205]
I've had no issues with previous clips being imported into Openshot. All of them were 1080p before importing but the last few ones looked tilted in the import box and surrounded by an ugly black box in the preview. I have to manually change the properties and zoom 2x scale just to get it right.

[Screenshot Import Box 
](https://ibb.co/z515Krp) (the last imported clip)
[Screenshot Preview Clip](https://ibb.co/N7Mkrdz) as you can see it's inside a black box.

**Comment by MPPlantOfficial** [comment]
any solutions yet? anyone know the reason the reason this is happening?

**Comment by SuslikV** [comment]
Screenshots is not enough to make the conclusion. If issue can be easily reproducible, just add this media file to the Timeline and attach OpenShot's log-file from this session.
