### ISSUE TITLE
Wrong cursor style on Tutorial popup

### ISSUE THREAD

**Issue by VADemon** [OpenShot/openshot-qt#3212]
**Describe the bug:**
The cursor style is set to "not allowed" when hovering over Tutorial windows.

**Steps to reproduce the behavior:**
1. Start OpenShot for the first time or bring up tutorials
2. Hover over Tutorial window
3. ???

**Expected behavior:**
Reg cursor style

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ 2.5.0 }} fa699d77
- Operating System / Distro: Win7

**Screenshots:** (Optional)
![openshot-qt](https://user-images.githubusercontent.com/1168140/74224387-0a148880-4cb9-11ea-9670-2c1c95a6ef8f.png)

**Comment by ferdnyc** [comment]
Hmmm. There is something weird going on with the mouse cursor when the tutorial is open... I saw the same thing just now, clicked Hide Tutorial, launched it _again_, and the second time around I got THIS cursor:

![Screenshot from 2020-02-11 10-50-57](https://user-images.githubusercontent.com/538020/74253162-ba37c080-4cbc-11ea-87dc-1b6ebb418200.png)

I've also gotten this one:

![Screenshot from 2020-02-11 10-52-18](https://user-images.githubusercontent.com/538020/74253170-bd32b100-4cbc-11ea-896e-89d88d46603e.png)

...It feels very nearly random, which cursor image actually comes up when the tutorial launches. And sometimes it's even the standard arrow cursor.

Aha... but the Forbidden cursor, specifically, is explainable: It somehow snuck into the UI definition for the tutorial dock:

https://github.com/OpenShot/openshot-qt/blob/3fed6be78f1361d37869fcaafd5a2b5a0c9b9bfa/src/windows/ui/main-window.ui#L403-L405

I'll fix that, and hopefully it'll put a stop to the _rest_ of the random cursor shapes, as well. Thanks for the report!
