### ISSUE TITLE
title images not saving anywhere

### ISSUE THREAD

**Issue by sarawas** [OpenShot/openshot-qt#3213]
**Describe the bug:**
I am a new user (well 3 weeks) installed latest update, now title files just disappear, not in openshot/inkscape,  project or anywhere. I can't find any log files on the system, and I am not techy, so really stuck on what to do..made 4 title images now just gone .help an old lady lol
**Steps to reproduce the behavior:**

**Expected behavior:**

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.
Log files can be found in your HOME/.openshot_qt/ folder. Please compress or zip
the log files (as they can become quite large).

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please
attach a small snippet of the exception here, but please keep it as small as
possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them here, dragging-and-dropping into this form, or clicking below and loading
images saved to your computer. All images are public, so please don't post screenshots
containing personal information.

**Comment by SuslikV** [comment]
What exactly disappeared? You cannot find the titles templates from the main menu _Title_ or what?

**Comment by sarawas** [comment]
Hi thanks for replying, I used advanced editor to alter title files in Inkscape, saved in titles folder. But on going back yesterday there was nothing in titles folder, they have vanished from the video, and they can't be recovered in inkscape. I just get the example message in openshot 'temp4.png cannot be found'. The files are now not on the PC? very weird

**Comment by SuslikV** [comment]
When OpenShot updates its files it simply wipes all folder contents and writes new files into it. Thus, please don't store the files in the program's folder. It is better to store them in project's folder that itself will be on other drive (or in some other folder, but again make sure that this is your own folder that you have created yourself, this is common practice). OpenShot is cannot auto-load some titles templates from the user folder (yet), so just copy them each time. I don't know better solution.

**Comment by sarawas** [comment]
Many, many thanks for helping me out :) That all makes perfect sense, and  grateful to you for taking the time. cheers x

**Comment by SuslikV** [comment]
Not at all. I don't think that the mechanism of the OpenShot's update was described before. There is a lot of stuff to do.
