### ISSUE TITLE
Use font-config for finding fonts, do not ship fonts

### ISSUE THREAD

**Issue by PanderMusubi** [OpenShot/openshot-qt#322]
This log message `app:INFO Setting font to /usr/lib/python3/dist-packages/openshot_qt/images/fonts/Ubuntu-R.ttf` reveals that openshot-qt is shipping font files. This should not be the case. Remove these font files from the repository. Also do not add dependencies to font file packages in the .deb file. Only recommended or suggested package references to font files should be used.

Use font-config for finding paths to font files. Add also one or two backup fonts to find via font-config when Ubuntu-R.ttf is not font. Python libraries exist for doing this. Please use the font names and not the filenames of the fonts for finding what is needed.

**Comment by DylanC** [comment]
@PanderMusubi - I'll check is there a good reason for this. Thanks.

**Comment by DylanC** [comment]
@jonoomph - Is there a reason for shipping fonts? (if we still do this)
