### ISSUE TITLE
2.5.0 not running on ubuntu 18.04

### ISSUE THREAD

**Issue by paolobenve** [OpenShot/openshot-qt#3220]
I installed openshot from daily ppa, but I got:

```
$ openshot-qt 
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
         app:INFO ------------------------------------------------
         app:INFO             Thu Feb 13 09:49:58 2020            
         app:INFO               Starting new session              
         app:INFO ------------------------------------------------
         app:INFO          OpenShot (version 2.5.0-dev1)          
         app:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.5.0-dev1
      logger:ERROR Traceback (most recent call last):
      logger:ERROR   File "/usr/bin/openshot-qt", line 11, in <module>
      logger:ERROR load_entry_point('openshot-qt==2.5.0.dev1', 'gui_scripts', 'openshot-qt')()
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 97, in main
      logger:ERROR app = OpenShotApp(argv)
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 115, in __init__
      logger:ERROR from classes import exceptions
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot_qt/classes/exceptions.py", line 30, in <module>
      logger:ERROR from classes.metrics import track_exception_stacktrace
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot_qt/classes/metrics.py", line 83, in <module>
      logger:ERROR "cd1": openshot.OPENSHOT_VERSION_FULL,  # Dimension 1: libopenshot version
      logger:ERROR AttributeError
      logger:ERROR :
      logger:ERROR module 'openshot' has no attribute 'OPENSHOT_VERSION_FULL'
         app:INFO             OpenShot's session ended            
         app:INFO             Thu Feb 13 09:49:59 2020            
         app:INFO ================================================

```

**Comment by SuslikV** [comment]
You have opened other issue: https://github.com/OpenShot/openshot-qt/issues/3219

At startup OpenShot cannot check that the required library (_libopenshot_) is out of date and thus fails to start.

I hope you know how to get most recent _libopenshot_ for your system.

**Comment by paolobenve** [comment]
ok, but I installed with apt from a ppa... shouldn't it have the correct dependencies?

**Comment by muziker** [comment]
I have the same problem with OPENSHOT_VERSION_FULL. How is openshot checking the updated version. Does it need to be online for it to check? Can it function in an offline mode?

**Comment by muziker** [comment]
In site-packages/_openshot.so, there is the string OPENSHOT_VERSION_FULL, but when doing this 

>import openshot
>print(openshot.OPENSHOT_VERSION_FULL )

gives an error because openshot.OPENSHOT_VERSION_FULL isn't there

**Comment by SuslikV** [comment]
I'm not common with the PPA packaging and how it checks for required version of _libopenshot_.

On Windows there is "frozen" version of Python with OpenShot scripts and all required libs (including libopenshot). You just downloading installation file and performing install (or unpack).

**Comment by muziker** [comment]
Instead of me adding a new issue, i'll chime in on this thread instead.

I'm trying to run openshot, by using the `python3 src/launch.py `. The pythonpath is pointing to the [path to libopenshot folder]. The reason the start fails is it looks for the OPENSHOT_VERSION_FULL string definition that is set by libopenshot when swigging the files to a python module. The sofile _openshot.so contains symbols that point to OPENSHOT_VERSION_FULL, but the python module does not return anything when calling _openshot.OPENSHOT_VERSION_FULL.

I checked by loading the openshot python module and querying for this string

**Comment by SuslikV** [comment]
@muziker if you are using _master_ branch, here is the definition:

https://github.com/OpenShot/libopenshot/blob/fe8ea216f4d006f1f0c57fc36203ebbfc65d276f/include/OpenShotVersion.h.in#L35

**Comment by muziker** [comment]
Right, the definition is there, but for the openshot python module to be able to reference it, the interface is swigged to allow _openshot.py to access this definition. For some reason, _openshot.py does not have that, so _openshot.OPENSHOT_VERSION_FULL returns nothing, hence, at least in my case, running the launcher fails

**Comment by SuslikV** [comment]
_libopenshot_ installation is not just a library file. You make look at the corresponding cmake script.

**Comment by versantus** [comment]
On Ubuntu 18.04 if using the PPA, you can install python3-openshot to resolve this:

`sudo apt-get install python3-openshot`

**Comment by fwolfst** [comment]
> On Ubuntu 18.04 if using the PPA, you can install python3-openshot to resolve this:

Solved it for me. Can anybody here improve the text on https://www.openshot.org/ppa/ or ping somebody who can? Sorry that I don't; I am horribly short of time atm.

**Comment by fwolfst** [comment]
> Probably file a bug on https://launchpad.net/~openshot.developers/+archive/ubuntu/ppa ?

I didnt manage to file a bug on launchpad, but wrote a mail to the mailinglist (which I am not subscribed to, no idea if it gets through)

**Comment by jerrac** [comment]
Just ran into this myself.  https://github.com/OpenShot/openshot-qt/issues/3220#issuecomment-607603781 fixed it. Spent the last 5 or 10 minutes looking for a place to submit a bug on launchpad, and couldn't find one. 

I'd suggest renaming the issue to "Stable PPA package for Ubuntu 18.04 is missing `python3-openshot` dependency." Hopefully one of the package maintainers will see it.

**Comment by ctala** [comment]
> On Ubuntu 18.04 if using the PPA, you can install python3-openshot to resolve this:
> 
> `sudo apt-get install python3-openshot`

Also fixed it for me. Thanks by the way.

**Comment by angelo-fuchs** [comment]
The suggested solution (`sudo apt-get install python3-openshot`) did not work for me.

I solved it by:

    dpkg -l | grep openshot
    ii  libopenshot-audio6:amd64              0.1.8+dfsg2+67+201903210434~ubuntu14.04.1   amd64        library for high-quality audio editing
    ri  libopenshot16:amd64                   0.2.2+dfsg1-1+b1                            amd64        library for high-quality video editing
    ii  openshot-qt                           2.5.1+dfsg2+1218+202003032149~ubuntu19.04.1 all          OpenShot video editor
    ii  python3-openshot                      0.2.2+dfsg1-1+b1                            amd64        OpenShot video library bindings for Python 3
    sudo apt-get remove libopenshot-audio6 openshot-qt python3-openshot
    sudo apt-get install openshot-qt

So: Listing all openshot packages, removing them, reinstalling openshot-qt.

**Comment by ctsdownloads** [comment]
Looks like this has been solved, closing this.

**Comment by angelo-fuchs** [comment]
@ctsdownloads Could you edit the two solutions (manual install of python3-openshot and longer one with deinstall then reinstall) into the initial post? This thread is quite prominent on my searchengine and experience says people don't read till the end :)

**Comment by mofleury** [comment]
had the same issue. It would be nice to add the installation python3-openshot in the instructions here : https://www.openshot.org/ppa/
hope that helps ;)

**Comment by revmarkp** [comment]
sudo apt-get install python3-openshot

sorts it for me also. I have Xubuntu 18.04

**Comment by MGradenko** [comment]
> On Ubuntu 18.04 if using the PPA, you can install python3-openshot to resolve this:
> 
> `sudo apt-get install python3-openshot`

Works for Ubuntu 20.04LTS as well. Thank you @ctala

**Comment by jamiejackherer** [comment]
This does not touch on what us Archlinux users can do about this issue. I am getting to a point where openshot will not be an option for me.

**Comment by imakin** [comment]
this is solved but i just fetched from the latest deb on stable ppa for ubuntu 20.04, the deb still not depends on `python3-openshot` so i have to manually searching for what is missing and then install it `python3-openshot`.
the deb from ppa works instantly on my ubuntu 20.10

**Comment by akomakom** [comment]
If, like me, you had the older package from official repos installed before adding the PPA and upgrading:
```
sudo apt autoremove # get rid of unnecessary extra deps
sudo apt dist-upgrade # upgrades python3-openshot to a matching version
```
