### ISSUE TITLE
Crash when opening preferences (Windows 10)

### ISSUE THREAD

**Issue by tonekneeo** [OpenShot/openshot-qt#3221]
**Describe the bug**
Crash when opening preferences

**Steps to reproduce the behavior:**
1. Go to 'Edit'
2. Click on 'preferences'
3. See error

**Expected behavior**
For the preferences menu to open.

**System Details**
- OpenShot Version: 2.5.0-dev1
- libopenshot Version:  0.2.4-dev1
- Platform: Windows-10-10.0.18362
- Processor: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.0-dev1-1581584036-99fda013-836e49fa-x86_64.exe

**Log Files**
- http://logs.openshot.org/mcumnpwrrqz7rio2u7u4nja2dl0n0031/openshot-qt.zip
- http://logs.openshot.org/mcumnpwrrqz7rio2u7u4nja2dl0n0031/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by SuslikV** [comment]
What it looks like, your crash? Any messages on the screen?

**Comment by tonekneeo** [comment]
> What it looks like, your crash? Any messages on the screen?

No error. Just crashes, and force quits.

**Comment by SuslikV** [comment]
Are you sure that it silently quits?

From the log-file it fails to initialize (or use) the Intel QSV encoder/decoder. Thus it is wise to install latest drivers for your Intel's built-in GPU (or even roll-back to some older, more stale version, if current one fails with the program).

**Comment by tonekneeo** [comment]
When I run the program with my default Nvidia Card I get the crash. When I open it with the Intel Card it does not crash. Thank you I didn't notice the Intel fail.

**Comment by SuslikV** [comment]
Can you post the log-file from the same successful attempt? Maybe it may help to developers.

**Comment by tonekneeo** [comment]
Logs from successful run.
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/4199509/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/4199510/openshot-qt.log)

**Comment by SuslikV** [comment]
Thank you for the info. It seems that HW decoding anyway is not in use.
