### ISSUE TITLE
Openshot Crashes when entry into Preferences. Trying to update path to Blender and Inkscape via Edit/Preferences, Openshot crashes. (Give your bug report a descriptive title)

### ISSUE THREAD

**Issue by bilsoncs** [OpenShot/openshot-qt#3224]
**Describe the bug**
Trying to update path to Blender and Inkscape via Edit/Preferences, Openscape crashes.

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 2.5.0-dev1
- libopenshot Version:  0.2.4-dev1
- Platform: Windows-10-10.0.18362
- Processor: Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.0-dev1-1581584036-99fda013-836e49fa-x86_64.exe

**Log Files**
- http://logs.openshot.org/isfu94cg2v4g9j6gs1w68yf0tx231tb5/openshot-qt.zip
- http://logs.openshot.org/isfu94cg2v4g9j6gs1w68yf0tx231tb5/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by bilsoncs** [comment]
In Describing the Bug I said Openscape when I ment Openshot.

**Comment by SuslikV** [comment]
It looks very similar to the https://github.com/OpenShot/openshot-qt/issues/3221

I think, developers aware of the problem: https://github.com/OpenShot/openshot-qt/issues/3210

Meanwhile, can you say to which graphics card is assigned OpenShot on your system?
Do you have installed latest video driver form the Intel for your CPU/GPU?

**Comment by bilsoncs** [comment]
NVIDIA Geforce 940MX
Driver is uptodate,

**Comment by bilsoncs** [comment]
Issue is Open

**Comment by bilsoncs** [comment]
After reading #3221 I changed my display settings to Integrated Graphics and I was able to access Preferences.

**Comment by SuslikV** [comment]
Is this driver from the Intel's site or Microsoft approved one?
Can you change the card assigned to the `openshot-qt.exe` to run it by Intel's GPU instead of NVIDIA?

**Comment by bilsoncs** [comment]
Sorry, I'm really not sure. I use AVG for driver updates and I don't know the answer.

**Comment by SuslikV** [comment]
It is NVIDIA driver, but I asked for the Intel's (CPU build-in graphics core) driver. Some earlier versions of Intel drivers had bugs in Quick Sync implementation.

**Comment by bilsoncs** [comment]
Intel HD Graphics 520,  Intel Driver, Dated 10/17/17, version 22.20.16.4836

**Comment by SuslikV** [comment]
Just to leave here a bit more info. **Your Intel's driver is out of date**. And you are using much newer FFmpeg (included the new OpenShot). I consider to you to try to get driver that is much newer than 25.20.100.6444, for example the https://downloadcenter.intel.com/download/29335/Intel-Graphics-Windows-10-DCH-Drivers?product=80939 (the `igfx_win10_100.7755.exe`, the downgrade will be almost impossible after this action, only if you are using some kind recovery snapshots of the whole system, also you may contact manufacturer of the PC to see if newer driver available for download from theirs page too). I hope you'll be able to start OpenShot's Preferences with this new driver installed, without switching settings to use the the Intel's GPU. Any changes?

**Comment by bilsoncs** [comment]
I tried to install igfx_win10_100.7755.exe as suggested, posted below are the reports I received.
![Driver Error Report](https://user-images.githubusercontent.com/61019973/74756936-545eb200-5243-11ea-9a1d-9b4dcd44d378.jpg)  and  
![Driver Rpt from HP](https://user-images.githubusercontent.com/61019973/74757013-6fc9bd00-5243-11ea-8049-32eb91d7ff32.jpg)

**Comment by SuslikV** [comment]
Yeah, that means that you are owner of the HP PC. Ask for their support by writing an e-mail. And look for the other brand next time. In general, such update may leave you at non-controllable blacklight level or similar "customization" that manufacturer may do to the video drivers.

**Comment by bilsoncs** [comment]
Yes I know it's an HP and from the HP driver update site it stated my driver is up to date.  Thanks for your help. I've had no problem with any other of the many programs that I use. I'm not going any farther. I know that if I need to change Preferences, I can change my display or just enter it manually. Thanks for your assistance.

**Comment by SuslikV** [comment]
Other workaround is to try to exclude the crashed test from the list, (by modifying `preferences.py` file) like in: https://github.com/OpenShot/openshot-qt/issues/3276#issuecomment-595052453
