### ISSUE TITLE
More control over slider with arrow keys

### ISSUE THREAD

**Issue by PanderMusubi** [OpenShot/openshot-qt#323]
Please add more control over the slider with arrow keys such as:
- Shift+Left and Shift+Right
- Ctrl+Left and Ctrl+Right

Now arrow keys move slider one frame at a time. The above combinations could move the slider at e.g. one second at a time, until the next beginning or ending of a frame

Perhaps Ctrl+Shift+Left and Ctrl+Shift+Right can be used for even more advanced naviation of the slider.

**Comment by ctsdownloads** [comment]
Thanks for the input, it's been added to the enhancement wishlist.
