### ISSUE TITLE
OpenShot Crashes when trying to slow down Clip.

### ISSUE THREAD

**Issue by ace200402** [OpenShot/openshot-qt#3230]
This bug was reported and closed as fixed in Aug 2017 with  Bug #588, This issue does not work with lasted Daily Build OpenShot-v2.5.0-dev1-1581720774-fe8ea216-836e49fa-x86_64.exe (64-bit)
```Computer Specs```
Using Windows 10
AMD Ryzen 5 3600X
32GB Corsair Ram 3000 Mhz
(incase it matters) XFX RX 5700 XT Ultra Thic III 8 GB Graphics Card

**Describe the bug:**
Small Video clip, cut into one section then copied and replicated 2 times, aligned one behind the other, then tried to slow the last clip down to 1/2 speed, it will play for about 4 seconds of video then crashes, Tried to run as admin no luck.

**Steps to reproduce the behavior:**
1. Open small video project with 30 seconds or less video content.
2. Right click onto video you want and select time, slow, forward, 1/2 speed
3. attempt to play video
4. 

**Expected behavior:**
I expect it to slow down the video and audio. even if just the video slows down i would be happy.

**Log Files:**
I did delete old logs and recreated issue within seconds of opening OpenShot

[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/4208842/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/4208843/openshot-qt.log)

**Comment by SuslikV** [comment]
This is navigational/playback issue - it has nothing to do with the time manipulations.

Sometimes OpenShot crashes during seeking of the files (closer to start - more often crash will happen). Maybe because of the close/reopen routine inside libopenshot for media files. But this is only my own thoughts.

For example, I was able reproduce the crash almost constantly with the seeking at first few seconds of the some scene before but almost unable to trigger it now.

**Comment by ace200402** [comment]
ok i somewhat understand, the only problem with that nav/playback is i can create and edit videos all day long, but the second i add any time effect it crashes with seconds of trying to preview the video, with your comment is there anyway around the problem?

**Comment by SuslikV** [comment]
I cannot reproduce the issue. Maybe the file somewhat special. Can you make short one and share it (where x1/2 time surely crashes the program, and point to time from where to start it)?

**Comment by ace200402** [comment]
sorry took so long to respond, how do i share the video file with you, the clip portion that i want to slow is literally about .60 seconds long

**Comment by SuslikV** [comment]
The MediaInfo of the file I got is this:
```
General
Complete name                            : O:\Temp\y2mate.com - guy_caught_in_neighbors_garage_gets_pistol_whipped_gUQaG3i9qyo_1080p.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41)
File size                                : 6.91 MiB
Duration                                 : 1 min 0 s
Overall bit rate                         : 957 kb/s
Writing application                      : Lavf58.26.101

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L3.1
Format settings                          : CABAC / 3 Ref Frames
Format settings, CABAC                   : Yes
Format settings, RefFrames               : 3 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 1 min 0 s
Bit rate                                 : 823 kb/s
Width                                    : 608 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 0.563
Frame rate mode                          : Constant
Frame rate                               : 30.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.042
Stream size                              : 5.93 MiB (86%)
Title                                    : ISO Media file produced by Google Inc. Created on: 01/20/2019.
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709

Audio
ID                                       : 2
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : mp4a-40-2
Duration                                 : 1 min 0 s
Bit rate mode                            : Constant
Bit rate                                 : 128 kb/s
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 44.1 kHz
Frame rate                               : 43.066 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 946 KiB (13%)
Title                                    : ISO Media file produced by Google Inc. Created on: 01/20/2019.
Default                                  : Yes
Alternate group                          : 1
```

MD5:0EDF460D4B2DA33DC481F3818FE20D6D
SHA256:54B9FCFB8369FC3B6C9FDBB3EC7CEAAE64C7453A18CA263622E59B4A04A49FBD

You may try to upload it to the https://www.virustotal.com/ to check if the CRC (_details_ tab) is the same to the file I got.

By using this file I cannot reproduce the bug on my system.

But I noticed another bug with the UI...
