### ISSUE TITLE
Not launching

### ISSUE THREAD

**Issue by jamesoverdale** [OpenShot/openshot-qt#3233]
![openshotbug](https://user-images.githubusercontent.com/61125144/74613280-d7182d80-50da-11ea-8a53-ed4e497bcae7.png)

**Comment by SuslikV** [comment]
You don't have enough permissions to access the files form the destination path. Either mad security software or something wrong with the users rights on your PC.

You can unpack OpenShot (daily build from https://www.openshot.org/download/ ) to any folder you have made yourself. For example with the `innounp.exe -x -d"C:\OpenShot" "C:\OpenShot-v2.5.0-dev1-1581877043-fe8ea216-836e49fa-x86_64.exe"` command line if you have the `innounp` util (at least v0.49) and downloaded most recent installation file of OpenShot (last in the command line example, that lies directly in the root of the drive `C:`). The`C:\OpenShot` - is the folder that you have made yourself on your drive `C:` where all files will be unpacked. Then just find the `openshot-qt.exe` from unpacked files and run it. Is the message gone for you now?
