### ISSUE TITLE
Can't start on ubuntu 19 when default python is python3.7 

### ISSUE THREAD

**Issue by songsammy** [OpenShot/openshot-qt#3235]
**Describe the bug:**
I double clicked the app icon , nothing (seemed) to happen.
I opened a terminal, entered "openshot-qt" , then I got an error.

**Steps to reproduce the behavior:**
1. install the latest openshot via PPA (because snap and amazon is somehow too slow in our country)
2. double click on the icon. I got nothing 
3. Open a terminal,enter "openshot-qt"
4. I got an error. The console output is included below

**Expected behavior:**
I expected it to run.

**System Details:**
openshot-qt -V
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
OpenShot version 2.5.0-dev1
**The "openshot-qt -V" worked properly,but is is python3, that's what i believe the problem is**
- Operating System / Distro: lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco

**Log Files:**
<pre><font color="#4E9A06"><b>sam@sam-ThinkPad-Edge-E430</b></font>:<font color="#3465A4"><b>~</b></font>$ openshot-qt
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
         app:INFO ------------------------------------------------
         app:INFO             Mon Feb 17 22:44:03 2020            
         app:INFO               Starting new session              
         app:INFO ------------------------------------------------
         app:INFO          OpenShot (version 2.5.0-dev1)          
         app:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.5.0-dev1
      logger:ERROR Traceback (most recent call last):
      logger:ERROR   File &quot;/usr/bin/openshot-qt&quot;, line 11, in &lt;module&gt;
      logger:ERROR load_entry_point(&apos;openshot-qt==2.5.0.dev1&apos;, &apos;gui_scripts&apos;, &apos;openshot-qt&apos;)()
      logger:ERROR   File &quot;/usr/lib/python3/dist-packages/openshot_qt/launch.py&quot;, line 97, in main
      logger:ERROR app = OpenShotApp(argv)
      logger:ERROR   File &quot;/usr/lib/python3/dist-packages/openshot_qt/classes/app.py&quot;, line 115, in __init__
      logger:ERROR from classes import exceptions
      logger:ERROR   File &quot;/usr/lib/python3/dist-packages/openshot_qt/classes/exceptions.py&quot;, line 30, in &lt;module&gt;
      logger:ERROR from classes.metrics import track_exception_stacktrace
      logger:ERROR   File &quot;/usr/lib/python3/dist-packages/openshot_qt/classes/metrics.py&quot;, line 83, in &lt;module&gt;
      logger:ERROR &quot;cd1&quot;: openshot.OPENSHOT_VERSION_FULL,  # Dimension 1: libopenshot version
      logger:ERROR AttributeError
      logger:ERROR :
      logger:ERROR module &apos;openshot&apos; has no attribute &apos;OPENSHOT_VERSION_FULL&apos;
         app:INFO             OpenShot&apos;s session ended            
         app:INFO             Mon Feb 17 22:44:04 2020            
         app:INFO ================================================
</pre>

**Exception / Stacktrace:**
[openshot-qt.zip](https://github.com/OpenShot/openshot-qt/files/4214385/openshot-qt.zip)

**Screenshots:** (Optional)
<pre><font color="#4E9A06"><b>sam@sam-ThinkPad-Edge-E430</b></font>:<font color="#3465A4"><b>~</b></font>$ openshot-qt
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
         app:INFO ------------------------------------------------
         app:INFO             Mon Feb 17 22:44:03 2020            
         app:INFO               Starting new session              
         app:INFO ------------------------------------------------
         app:INFO          OpenShot (version 2.5.0-dev1)          
         app:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.5.0-dev1
      logger:ERROR Traceback (most recent call last):
      logger:ERROR   File &quot;/usr/bin/openshot-qt&quot;, line 11, in &lt;module&gt;
      logger:ERROR load_entry_point(&apos;openshot-qt==2.5.0.dev1&apos;, &apos;gui_scripts&apos;, &apos;openshot-qt&apos;)()
      logger:ERROR   File &quot;/usr/lib/python3/dist-packages/openshot_qt/launch.py&quot;, line 97, in main
      logger:ERROR app = OpenShotApp(argv)
      logger:ERROR   File &quot;/usr/lib/python3/dist-packages/openshot_qt/classes/app.py&quot;, line 115, in __init__
      logger:ERROR from classes import exceptions
      logger:ERROR   File &quot;/usr/lib/python3/dist-packages/openshot_qt/classes/exceptions.py&quot;, line 30, in &lt;module&gt;
      logger:ERROR from classes.metrics import track_exception_stacktrace
      logger:ERROR   File &quot;/usr/lib/python3/dist-packages/openshot_qt/classes/metrics.py&quot;, line 83, in &lt;module&gt;
      logger:ERROR &quot;cd1&quot;: openshot.OPENSHOT_VERSION_FULL,  # Dimension 1: libopenshot version
      logger:ERROR AttributeError
      logger:ERROR :
      logger:ERROR module &apos;openshot&apos; has no attribute &apos;OPENSHOT_VERSION_FULL&apos;
         app:INFO             OpenShot&apos;s session ended            
         app:INFO             Mon Feb 17 22:44:04 2020            
         app:INFO ================================================
<font color="#4E9A06"><b>sam@sam-ThinkPad-Edge-E430</b></font>:<font color="#3465A4"><b>~</b></font>$ openshot-qt -v
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
usage: openshot-qt [-h] [-l LANG] [--list-languages] [-V]
openshot-qt: error: unrecognized arguments: -v
<font color="#4E9A06"><b>sam@sam-ThinkPad-Edge-E430</b></font>:<font color="#3465A4"><b>~</b></font>$ openshot-qt -V
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
OpenShot version 2.5.0-dev1
<font color="#4E9A06"><b>sam@sam-ThinkPad-Edge-E430</b></font>:<font color="#3465A4"><b>~</b></font>$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco
<font color="#4E9A06"><b>sam@sam-ThinkPad-Edge-E430</b></font>:<font color="#3465A4"><b>~</b></font>$ 

</pre>

**Comment by songsammy** [comment]
Or maybe python 2.7 isn't installed on my laptop.
<pre><font color="#4E9A06"><b>sam@sam-ThinkPad-Edge-E430</b></font>:<font color="#3465A4"><b>~</b></font>$ update-alternatives --list python
/usr/bin/python3.7
</pre>

**Comment by songsammy** [comment]
But python2 is installed,but
<pre><font color="#4E9A06"><b>sam@sam-ThinkPad-Edge-E430</b></font>:<font color="#3465A4"><b>~</b></font>$ python2
Python 2.7.16 (default, Oct  7 2019, 17:36:04) 
[GCC 8.3.0] on linux2
Type &quot;help&quot;, &quot;copyright&quot;, &quot;credits&quot; or &quot;license&quot; for more information.
&gt;&gt;&gt; 
</pre>
I have to start it via _**python2**_
when I use python:
<pre><font color="#4E9A06"><b>sam@sam-ThinkPad-Edge-E430</b></font>:<font color="#3465A4"><b>~</b></font>$ python
Python 3.7.3 (default, Oct  7 2019, 12:56:13) 
[GCC 8.3.0] on linux
Type &quot;help&quot;, &quot;copyright&quot;, &quot;credits&quot; or &quot;license&quot; for more information.
&gt;&gt;&gt; 

</pre>

**Comment by SuslikV** [comment]
This issue is similar to: https://github.com/OpenShot/openshot-qt/issues/3220

**Comment by songsammy** [comment]
I did this
[Linux Build Instructions](https://github.com/OpenShot/libopenshot/wiki/Linux-Build-Instructions#install-dependencies)
and did this
<pre><font color="#4E9A06"><b>sam@sam-ThinkPad-Edge-E430</b></font>:<font color="#3465A4"><b>~</b></font>$ sudo bash
<font color="#4E9A06"><b>root@sam-ThinkPad-Edge-E430</b></font>:<font color="#3465A4"><b>~</b></font># apt update &amp;&amp; apt upgrade
</pre>
and everithing is fine.

**Comment by ferdnyc** [comment]
The core problem was that you still had an older version of `libopenshot` installed that wasn't compatible with the latest `openshot-qt` code — unfortunately, upgrading the `openshot-qt` package via PPA doesn't necessarily update all of its dependencies (a bug in the current apt packaging). When you ran the `apt upgrade`, the previously-installed `libopenshot16` or `libopenshot17` would've been replaced with the current `libopenshot18` release that corresponds to OpenShot 2.5.0.

**Comment by pjotrek-b** [comment]
I also ran into this issue with using the PPA after having installed OpenShot from Xubuntu 18.04 default repositories.

Removing all libopenshot *and keep only libopenshot19** fixed it for v2.5.1-dev2.

Thanks! :smile:
