### ISSUE TITLE
MOV file (video) is put on timeline with wrong length

### ISSUE THREAD

**Issue by huubvanniekerk** [OpenShot/openshot-qt#3238]
**Describe the bug:**
Using Fedora 30, rpm-installed 2.5.0. After adding a MOV video of e.g. 2:08 minutes (recorded with a camera) to the timeline, the video gets a 38 seconds length. I can manually extend it to 2:08 minutes, but this is cumbersome. 

**Steps to reproduce the behavior:**

**Expected behavior:**
In 2.4.4 (AppImage), there's no problem: 2:08 gets put on the timeline with 2:08. So I expect this to happen in 2.5.0 as well.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 2.5.0 rpm-installed
- Operating System / Distro: Fedora Linux 30
![Screenshot-OpenShot-2 5 0-wrong-length-video-2020-02-19 20-21-50](https://user-images.githubusercontent.com/13077765/74964424-b3732100-5413-11ea-904d-12f504fee3ce.png)

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.
Log files can be found in your HOME/.openshot_qt/ folder. Please compress or zip
the log files (as they can become quite large).

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please
attach a small snippet of the exception here, but please keep it as small as
possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them here, dragging-and-dropping into this form, or clicking below and loading
images saved to your computer. All images are public, so please don't post screenshots
containing personal information.

**Comment by SuslikV** [comment]
Every file affected?

**Comment by huubvanniekerk** [comment]
No. I checked again 2 times: the first MOV video added to the timelink is shortened from 2:08 to 00:39:08, each next addition to the timeline, being .ogg or MOV, has the correct length.

**Comment by SuslikV** [comment]
Can you share the short file sample that "shortens" even more when added to the timeline?
How you are: "adding it to the Timeline"? (I want to reproduce the issue on my end)

**Comment by huubvanniekerk** [comment]
The short file sample is a video of 347MB, so how to share it is the question.
Adding it to the timeline: put timelime cursor at correct place, import the file, select file, right-click (menu appears), left-click Add to timeline, select Track, finish with OK. In 2.4.4, the video is added with its correct videolength (in this case 2:08).
What I notice now: when I take another .MOV video and put that in as first part, it does get the correct length on the timeline. I checked with 2.4.4, which shows the same. However, when I put the first video behind that one, it again gets the wrong shortened length.

**Comment by SuslikV** [comment]
And if you simply drag-n-drop it to the Timeline?

**Comment by huubvanniekerk** [comment]
Drag-n-drop gives the same result.

**Comment by SuslikV** [comment]
Can you post your OpenShot's log-file where you only add this .mov clip and seeing it shorter than it is?

**Comment by huubvanniekerk** [comment]
Sure, here it is.
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/4239347/openshot-qt.log)

**Comment by SuslikV** [comment]
Yeah, it has no useful info in it... And if you adjust your OpenShot's preview profile to 29.97 fps as source itself?

**Comment by huubvanniekerk** [comment]
It's currently HDV 720 24p, so that would mean change it to HD 720p 29.97 fps?

**Comment by SuslikV** [comment]
Too bad. I'm out of ideas what can cause such strange behavior of OpenShot. The duration calculation incorrect in libopenshot for both versions but it shouldn't cause this major difference for clip import as you has. I can only imagine that actual data references different file (you may try rename the one that imported).

Also, can you step by step describe this action (with the files names and position on Timeline):

> ...when I take another .MOV video and put that in as first part, it does get the correct length on the timeline. ... However, when I put the first video behind that one, it again gets the wrong shortened length.

You want to say that the "DSC_3289.MOV" someway unique?

If you have the FFmpeg _probe_ util installed, please, try to make .txt file of the all pts/dts/duration of the .MOV file, like (Windows syntax in the example, valid for v4.x of FFmpeg probe):
`ffprobe -v 0 -show_entries packet=pts,dts,duration,size,flags -of compact=p=0:nk=1 -select_streams v "DSC_3289.MOV" >"log_pts.txt"`

**Comment by huubvanniekerk** [comment]
This DSC_3289.MOV is not any more or less unique than the other videos I record with camera.  I made the txt file.
[log_pts.txt](https://github.com/OpenShot/openshot-qt/files/4239872/log_pts.txt)

**Comment by SuslikV** [comment]
Wow! It's perfect file in terms of timestamps. The device you are using costs more than 300$. Maybe you need better editor too...

Anyway, this leads to the conclusion that clip itself is OK for the _libopenshot_. On Windows I didn't see such behavior before. The log just says that clip already imported with the duration of `39.27862548828125` sec.

In your place, I would try to remove all traces of the `.openshot_qt` folder in the PC (there OpenShot stores its settings), and attempted to start from the scratch.

**Comment by huubvanniekerk** [comment]
Yes, the camera wasn't cheap. Considering I'm using Linux and not being a pro, I'll stay with OpenShot. I've tried to use e.g. Cinelerra, but that's too much for my (simple) use. Before using this (rpm)version 2.5.0 of OpenShot I didn't see this behaviour either and was quite satisfied using the 2.4.4 AppImage version.
I will remove all traces of the .openshot_qt folder and see what happens.
