### ISSUE TITLE
trying to add image to timeline crashes openshot

### ISSUE THREAD

**Issue by AceHW** [OpenShot/openshot-qt#3239]
**Describe the bug**
image crashes OpenShot

**Steps to reproduce the behavior:**
1. Download image https://pbs.twimg.com/media/DpKf_2oV4AAAYiP?format=jpg
2. Open OpenShot
3. Import image
4. Try to add image to timeline
5. OpenShot crashes 

**Expected behavior**
I expect it to be added in the timeline as howevermany seconds of still video because that's what OpenShot does with images added to the timeline

**System Details**
- OpenShot Version: 2.5.0-dev1
- libopenshot Version:  0.2.4-dev1
- Platform: Linux-4.19.0-6-amd64-x86_64-with-MX-19.1-patito_feo
- Processor: 
- Machine: x86_64
- Python version: 3.4.3
- Qt5 version: 5.2.1
- PyQt5 version: 5.2.1
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: en_US.UTF-8
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.0-dev1-1582091950-fe8ea216-836e49fa-x86_64.AppImage

**Log Files**
- http://logs.openshot.org/oox8qi5ec8ryxlxuuk1er7m29cs4boua/openshot-qt.zip
- http://logs.openshot.org/oox8qi5ec8ryxlxuuk1er7m29cs4boua/libopenshot.zip

**Comment by AceHW** [comment]
wait, maybe it's something to do with my computer or software or settings or something 

I tried with a couple other pics and it also crashed

**Comment by SuslikV** [comment]
Try to build your own OpenShot (native install). It doesn't happen on Windows, for example.

**Comment by AlejandroFNadal** [comment]
I am having the same problem using Openshot with the AppImage, Debian 10. I'll give it a try to installing it
