### ISSUE TITLE
 (Give your bug report a descriptive title)

### ISSUE THREAD

**Issue by insanesicsix6** [OpenShot/openshot-qt#3243]
**Describa el saund delay problem at export proyect
sound delay problem at export proyect
**Pasos para reproducir el comportamiento:**
1. Ir a «...»
2. Pulsar en «....»
3. Desplazarse hasta «....»
4. Ver el error

**Comportamiento esperado**
Una descripción clara y concisa de lo que esperaba que sucediera.

**Detalles del sistema**
- OpenShot Version: 2.5.0-dev1
- libopenshot Version:  0.2.4-dev1
- Platform: Windows-10-10.0.18362
- Processor: Intel64 6700k
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['es-ES', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.0-dev1-1582092062-fe8ea216-836e49fa-x86_64.exe

**Archivos de registro**
- http://logs.openshot.org/pxivby6v1s6ea9skm96niv06dqiksejc/openshot-qt.zip
- http://logs.openshot.org/pxivby6v1s6ea9skm96niv06dqiksejc/libopenshot.zip

**Excepción / Rastreo de pila**
```No stacktrace found in log files```

**Capturas de pantalla** (Opcional)
Si se aplica, añada capturas de pantalla para ayudar a explicar el problema. Puede incluir capturas
copiando y pegando en GitHub o arrastrando y soltando en la página de GitHub. Todas las imágenes
son públicas y por tanto no debería publicar capturas que contengan información personal.

**Comment by SuslikV** [comment]
line 577 of the log-file:

>   json_data:ERROR Error while converting absolute paths to relative paths: path is on mount 'X:', start on mount 'C:'

The second post in the https://github.com/OpenShot/openshot-qt/issues/3027 has info about the source files that are on different drives (relative paths not possible - limitation of current OpenShot for Windows).
