### ISSUE TITLE
display frame position on the timeline along with time

### ISSUE THREAD

**Issue by PontiacCZ** [OpenShot/openshot-qt#3244]
I like the "Advanced" tab of the "Export" window and especially possibility to encode a specific range from the timeline. But that has to be entered in frames (start frame - end frame).

How about displayig actual frame position on the timeline as well so we don't have to calculate it? It could look like this:

![image](https://user-images.githubusercontent.com/9153595/75171354-c6dffe00-572b-11ea-84b1-a716bb616a38.png)

**Comment by SuslikV** [comment]
related PR is here: https://github.com/OpenShot/openshot-qt/pull/3346
