### ISSUE TITLE
Fragmented Audio Clips

### ISSUE THREAD

**Issue by insurancesnoopers** [OpenShot/openshot-qt#3248]
This bug has not been reported.

Currently, whenever I import audio clips from my hard drive, the clip becomes fragmented. It contains a black box that blocks the audio from playing.
 
![IMG_0390 1](https://user-images.githubusercontent.com/5870078/75254304-068f0000-5795-11ea-8270-c22d581d65f4.JPG)

**Comment by SuslikV** [comment]
> ...the clip becomes fragmented. It contains a black box that blocks the audio from playing.

This part requires more info about what exactly happening. Can you attach the OpenShot's log-file as well?

From the screenshot I see that your video clip (Track 5) is shorter than audio only clip (Track 4) and thus, the video stops earlier than audio (you see black in Preview). The audio only clip has black thumbnail because of small bug in OpenShot. But this shouldn't stop playback of the audio itself. The playback of the video file maybe demanding (especially if this is HD file) and OpenShot just may struggle to playback it.

**Comment by insurancesnoopers** [comment]
Dear Suslik,
Thank you for your prompt response. First, my screenshot was only intended to display the issue that pertains to the 'black thumbnail' segment of the audio clip. My apologies for the any misunderstandings suffered with the addition of Track 5. 
Nonetheless, you are right that the black thumbnail doesn't stop the playback of the clip, but the thumbnail does interfere with the timeline placement and/or the audio clip's exact placement on the track. We now realize that this is a 'small bug' in Openshot, but remain hopeful that it can be or will be corrected soon. Moreover, this issue was never experienced by me in your preceding 2.4.4 version.
All the best,
Lonzie Johnson
-----Original Message-----

**Comment by SuslikV** [comment]
Probably I know what are you talking about. Is you CPU load rapidly jumps up during this strange behavior of the OpenShot?

This is not connected to the thumbnail existence. But it is hard to predict when it happens. Surely, it depends on Timeline and clip manipulations (start/end/position) during playback. Still under the investigation.

**Comment by insurancesnoopers** [comment]
Suslik,
I hadn't looked into the CPU load behavior, but in doing so, I didn't find any rapid increases in activity on  my computer.

**Comment by SuslikV** [comment]
Then I just discovered another bug of OpenShot (see edits above).

**Comment by insurancesnoopers** [comment]
Wow! I'm truly impressed with the analytical suggestions and approach that you have directed your developers to undertake in order to resolve this bug issue. 

Regrettably, I'm a novice when it comes to knowing just what to do whenever bugs need fixing. For instance, on our California car insurance services app, the Insurance Snoopers App, at www.insurancesnoopersapp.com, we are experiencing a video glitch with the OpenShot clips. Currently, the finalized OpenShot clips are uploaded onto our YouTube account, which transmit the videos to our app. Currently, the videos appear in the app, but do not play within the app. 

I've searching for a reputable back-end programmer/developer (since our Brazilian developer died last year) who can resolve this bug issue for us in our Unity designed app. With that in mind, would you be kind enough to steer me in the right direction to help us out?   

Regards,

Lonzie Johnson

**Comment by SuslikV** [comment]
@insurancesnoopers I don't trust you.

**Comment by insurancesnoopers** [comment]
Dear Susik, 
Is the below email from you? I don't understand. 

Lonzie L. Johnson, MBACo-Founder/CEOInsurance Snoopers, Inc.2400 N. Lincoln AvenueAltadena, CA 91001cell: 626-826-1112email:  ljohnsonca@aol.comemail: insurancesnoopers@aol.comweb: https://insurancesnoopersapp.comapp: Now in the Google Play and Apple's App Stores! 



-----Original Message-----

**Comment by SuslikV** [comment]
@insurancesnoopers I don't understand many things in this world too. Try to find domestic firm to solve your business issues. Or contact someone else. Nothing special about you - I has right to trust to people or not.

I appreciate your OpenShot bug report.
