### ISSUE TITLE
Can't install on windows 32 bits

### ISSUE THREAD

**Issue by Minicron** [OpenShot/openshot-qt#325]
Hello.

I'm trying to install OpenShot Video Editor v2.1 downloaded from the official website on my working computer at the office. Unfortunatly I keep getting this error message when trying :

![image](https://cloud.githubusercontent.com/assets/9683783/18351154/5018bac8-75d9-11e6-9af3-b1762498c0be.png)

I'm confused since I heard OpenShot was supported for 32bits windows system... And I can't find any other download link...

Any help ?

PS: I'm quite new to github, sorry if I broke any rule by posting this here.

**Comment by dnlbaines** [comment]
There is currently no 32 bit support for Windows in the newest release of OpenShot.

**Comment by jonoomph** [comment]
Please see https://github.com/OpenShot/openshot-qt/issues/334

**Comment by Siddharth48** [comment]
I am also encountering the same error. Please make this software available for 32 bit users also and remove 'x86' from the download filenames so that no one thinks of downloading it in 32 bit OS.

**Comment by dearpramod** [comment]
for 32 bit visit [](http://www.promod.com.np/``)

**Comment by DylanC** [comment]
Deleted and reported spam post. :)
