### ISSUE TITLE
No idea how to render a video

### ISSUE THREAD

**Issue by redpaintbucket** [OpenShot/openshot-qt#3250]
I am trying to create a short video but whenever I play an exported video file from my recording software (OBS), the video is extremely laggy and I have no idea how to render the video so it can play smoothly. I even tried exporting the video to "HD 1080p 60fps (1920x1080)" but it's still extremely laggy.

System Details:
- OpenShot Version 2.4.3
- Operating System / Windows 10

**Comment by SuslikV** [comment]
This highly depends on export settings. Does your source file (recording from the OBS Studio) playbacks smooth in any player you have?
