### ISSUE TITLE
Hardware encoding only enabled for the first detected video adapter

### ISSUE THREAD

**Issue by elforesto** [OpenShot/openshot-qt#3251]
When exporting a video, the only hardware encoding options available are for the first detected video adapter. For systems with multiple video adapters (e.g. a laptop with on-die GPU and discrete graphics), you may not be able to able to use the desired hardware encoder.

Required Environment:
Windows 10
OpenShot 2.5.0
A system with more than one available GPU such as a laptop with on-die GPU (Intel QSV) and discrete graphics

Steps to Reproduce:
1) Open or create any video project.
2) Go to File, Export Project, Export Video.
3) Go to Target and click the pick list.

Expected Result:
Any available hardware GPU encoding option should be shown.

Actual Result:
The on-die GPU is the only hardware GPU encoding option displayed. The discrete graphics is not listed.

Workaround:
Disable the on-die GPU in your system BIOS/UEFI firmware. This will result in a battery penalty on laptops during normal operation.

**Comment by SuslikV** [comment]
Application may run on different GPUs depending on driver settings. Use the right one. Old Intel QSV drivers has bugs in initialization that can crash application that uses newer techniques. Anyway, the transfer of data to RAM/GPU/RAM is slow.

**Comment by ferdnyc** [comment]
@elforesto The _intention_ (or, maybe I should say, "the goal") is to have all GPUs available for selection via the Performance tab in the preferences. There are selectors there for both Hardware Decoder Graphics Card, and Hardware Encoder Graphics Card, the idea being that you could target either or both processes to any available/detected GPU.

I would not be **at all** surprised to learn that's not actually _working_ as of yet, especially on Windows where hardware support is still in its infancy for us. But, that's at least the idea for how it's meant to work.
