### ISSUE TITLE
Subtitle using Chinese file name can't be reloaded

### ISSUE THREAD

**Issue by wwycheuk** [OpenShot/openshot-qt#3252]
**Describe the bug**
Subtitle using Chinese file name can't be loaded

**Steps to reproduce the behavior:**
1. Create a new project, add a video clip
2. Add a title, use the default Chinese file name ("TitleFileName-%d" was translated in launchpad.net)
3. Save the project (let's say "test.osp") and close it, then open it again
4. A dialog saying "u7a31-1.svg not found" (in Chinese) displayed, and the title can't be loaded
5. (Under "test_assets\title", there are two .svg files: "標題檔案名稱-1.svg" (The default translated Chinese filename) and "temp.svg". Open it with Inkscape, found that they are both the subtitle created in step 2.) 

P.S.: The translation was reverted for now, so that it won't cause problem before the bug was fixed. https://translations.launchpad.net/openshot/2.0/+pots/openshot/zh_TW/+translate?batch=10&show=all&search=TitleFileName 
P.S.2: Would you please provide a .1 version update to include the reverted translation? Thank you!

**Expected behavior**
The title should reloaded correctly.

**System Details**
- OpenShot Version: 2.5.0-dev1
- libopenshot Version:  0.2.4-dev1
- Platform: Darwin-18.7.0-x86_64-i386-64bit
- Processor: i386
- Machine: x86_64
- Python version: 3.6.4
- Qt5 version: 5.5.1
- PyQt5 version: 5.5.1
- Qt Detected Languages: ['zh-Hant-HK']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.0-dev1-1582715860-09e77609-836e49fa-x86_64.dmg

**Log Files**
- http://logs.openshot.org/xuq9m3rjicsr0qh2kbivjkf1g3offpth/openshot-qt.zip
- http://logs.openshot.org/xuq9m3rjicsr0qh2kbivjkf1g3offpth/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by SuslikV** [comment]
This issue is similar to https://github.com/OpenShot/openshot-qt/issues/3227 just has slightly deeper integration in to the program logic.

Can you try new daily build of OpenShot (https://www.openshot.org/download/) to see if recent changes solves the issue?

**Comment by wwycheuk** [comment]
Yes, it fixed the problem. Thanks!

**Comment by ferdnyc** [comment]
The OpenShot 2.5.1 release (now available at https://openshot.org/download/) contains a fix for the project-file encoding bug present in OpenShot 2.5.0. The new release will also recognize and auto-repair damaged encoding, when opening OpenShot 2.5.0 project files.

All OpenShot 2.5.0 users are strongly urged to upgrade to OpenShot 2.5.1 ASAP. After upgrading, it's further recommended that you open any projects previously saved from OpenShot 2.5.0 and re-save them, which will correct any encoding issues that may be present.
