### ISSUE TITLE
Playback exponentially slows after returning from sleep mode

### ISSUE THREAD

**Issue by xummux** [OpenShot/openshot-qt#3255]
**Describe the bug**

The bug is that OpenShot will not play at a normal speed after the computer returns from sleep mode and seems to exponentially slow down in playback speed.

**Steps to reproduce the behavior:**

Return from sleepmode with a current project.

**Expected behavior**

I expected that playback would be normal speed returning from sleepmode.

**System Details**
- OpenShot Version: 2.5.0
- libopenshot Version:  0.2.4
- Platform: Windows-10-10.0.18362
- Processor: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.0-dev1-1582715856-09e77609-836e49fa-x86_64.exe

**Log Files**
- http://logs.openshot.org/zhw3cm12icerbn0o0akc3qu1scbp1kif/openshot-qt.zip
- http://logs.openshot.org/zhw3cm12icerbn0o0akc3qu1scbp1kif/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by SuslikV** [comment]
Is UI response slows too?
CPU usage increases?

**Comment by xummux** [comment]
UI response seems to be just fine, no lag when adding a clip to the timeline.

CPU usage actually decreases.
![before_sleep_while_playing](https://user-images.githubusercontent.com/25647660/75459053-6e377d80-5944-11ea-8e88-46f6f1bb4c3e.jpg)
![after_sleep_while_playing](https://user-images.githubusercontent.com/25647660/75459071-74c5f500-5944-11ea-842f-bb703eb98cd2.jpg)

**Comment by xummux** [comment]
UI response seems to be just fine, no lag when adding a clip to the timeline.

CPU usage actually decreases.
![before_sleep_while_playing](https://user-images.githubusercontent.com/25647660/75459053-6e377d80-5944-11ea-8e88-46f6f1bb4c3e.jpg)
![after_sleep_while_playing](https://user-images.githubusercontent.com/25647660/75459071-74c5f500-5944-11ea-842f-bb703eb98cd2.jpg)

**Comment by SuslikV** [comment]
And if you save the project and restart the application without rebooting PC?

**Comment by xummux** [comment]
Restarting the application will allow normal playback speed. This issue seems to only happen when coming back from sleep mode while the application is running. If I exit the application and reload the project it works fine. So, that is my work around at the moment.

**Comment by Chealer** [comment]
@xummux does this persist in current versions? This looks a lot like #4376 .
