### ISSUE TITLE
Video freezes when I play it back

### ISSUE THREAD

**Issue by KEEGUNATOR** [OpenShot/openshot-qt#3265]
So, here I am. Just updated Openshot to the newest version, my audio bug is fixed, its all good. I decide to work on a project. I drop my file in there (about a minute long, HD) and play it to see where I need to cut out the parts. Boom, the video freezes. Now, my computers pretty beefy with a EVEA Geforce RTX 2060 GPU that I just got and a Intel i5-6400 CPU (yes, eek, i'm getting it replaced soon) and it seems weird to me. This has never happened to me before, and my computer usually doesn't have a problem with this. Since I have a triple monitor setup where 1 monitor has task manager open at all times, I look at it and see that my CPU utilization is at 100%. The whole time the video is frozen. The rest of the application is fine. Just whenever the video plays, it freezes and it maxes out my CPU. Not sure if its hardware or software problem, but isn't good for editing.
EDIT: Almost forgot, I'm on Windows 10.

**Comment by SuslikV** [comment]
It may depend on file itself. Can you _Remux_ the file with the OBS Studio for example? Keep copy of the original file before proceeding. Is the remuxed file playbacks better?

**Comment by KEEGUNATOR** [comment]
No, the file works everywhere else. Full audio and all. It'll just play for like 1 second then freezes.

**Comment by SuslikV** [comment]
"Everywhere else" is not OpenShot. Can you share the file sample that playbacks is not smooth for you?

**Comment by KEEGUNATOR** [comment]
Nevermind. Just a performance issue. If I leave it for a minute, It'll play again.
