### ISSUE TITLE
Only Bfont Can Be Used In Animated Titles

### ISSUE THREAD

**Issue by bbacle** [OpenShot/openshot-qt#3269]
**Describe the bug**
Animated Titles rendering

**Steps to reproduce the behavior:**
1. Go to "Title - Animated Title"
2. Click on "Dissolving Text"
3. Input "Gilligan" for the "File Name"
4. Input "Gilligan's Island" in "Title"
5. Input "1.50" for the "Text Size"
6. Try changing  Fonts in the "Font Name" (Nothing works there except the Bfont) - Why is this?
7. Slide the slider back to frame 1
8. Click on Render
9. The rendering only goes to frame 13 and stops (I left it on all night and it was still on frame 13 the next day)
10. I have gone back to version 2.4 and it rendered the animated title.

**Expected behavior**
I expected it to render the title for me so that I could put it into the timeline and export it to use in another video editing program that I use all the time.
It did not render in version 2.5 and in version 2.5.1 - it only worked in version 2.4.
Also I could not change to any other font (which, by the way, is very limited) - Can you not make it where it will accept any font that I have installed on my computer?
So there is the font issue as well as the rendering issue.
BTW...the font issue is on all versions 2.4 and forward.

**System Details**
- OpenShot Version: 2.5.1
- libopenshot Version:  0.2.5
- Platform: Windows-7-6.1.7601-SP1
- Processor: Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-release-candidate-1583026317-x86_64.exe

**Log Files**
- http://logs.openshot.org/730u3oip38wca5kvefjbez8pt74d319t/openshot-qt.zip
- http://logs.openshot.org/730u3oip38wca5kvefjbez8pt74d319t/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by ferdnyc** [comment]
Yeah, that's a UI bug — those other choices shouldn't be there, as they're not functional. (I don't know if they _ever_ worked, TBH.) Pretending that the user is able to change the animated title font is simply misleading.

**Comment by bobonov** [comment]
> 9. The rendering only goes to frame 13 and stops (I left it on all night and it was still on frame 13 the next day)

Is the freeze at frame 13 due to the invalid filed in the gui?
I'm experiencing the same freeze at frame 13 with "Dissolving Text" effect.
I'm using:
Windows 10
Openshot 2.5.1, libopenshot 0.2.5
Blender 2.82
I see other users experiencing this problem:  https://www.reddit.com/r/OpenShot/comments/f5u61w/animated_titles_not_working/

**Comment by SuslikV** [comment]
@bobonov 

> Is the freeze at frame 13...?

this part is similar to: https://github.com/OpenShot/openshot-qt/issues/3268
that itself should be already solved in daily builds ( https://www.openshot.org/download/#daily ).

**Comment by ferdnyc** [comment]
Yeah, the Blender thread hanging after rendering a few frames was fixed by #3273, merged post-2.5.1 release on March 5.

**Comment by bobonov** [comment]
> 9. The rendering only goes to frame 13 and stops (I left it on all night and it was still on frame 13 the next day)

Tried the latest build and I can confirm now it works, it does not freeze.
But I get a wrong result, opened a new issue #3350

**Comment by MBB232** [comment]
> Yeah, that's a UI bug — those other choices shouldn't be there, as they're not functional. (I don't know if they _ever_ worked, TBH.) Pretending that the user is able to change the animated title font is simply misleading.

@ferdnyc 

As a consequence of this, it seems no animated titles can be rendered for Asian languages. Because of a limitation in Blender/Bfont, they can not do that with Bfont
https://github.com/OpenShot/openshot-qt/issues/3494

https://developer.blender.org/T72829

> Jan 1 2020, Harley Acheson (harley) 
Unfortunately doing so does not automatically change the font used when inserting "Text" objects. Therefore, while your new text object is selected you must go to Properties / Object Data / Font and select a font that contains characters needed for your language. The default font (Bfont) does not contain any Korean characters. You can select the international font that comes with Blender (droidsans.ttf.gz) or any others on your computer. Sorry for the inconvenience. We are hoping to improve this in the future.

**Comment by helfgott** [comment]
By reading [this comment](https://github.com/OpenShot/openshot-qt/issues/3268#issuecomment-669172806) I was able to add custom fonts in Windows.

This change was made to use a different font than Bfont in animated titles, specifically the glare one but the same solution might be applied to other animated titles.

### What files I changed

- C:\Program Files\OpenShot Video Editor\blender\glare.xml (from now referred as glare.xml)
- C:\Program Files\OpenShot Video Editor\blender\scripts\glare.py.in  (from now referred as glare.py.in)

### Changes in glare.xml 
https://github.com/OpenShot/openshot-qt/blob/develop/src/blender/glare.xml#L30

This part is tricky. When chaning this XML we will change what is shown in the UI for the glare effect. We need to add the real names of the fonts. Not the file name, not the font name fron the description of the file but the real font name as read by blender.

For example, the font `arial.ttf` from `C:\Windows\Fonts` has the name **Arial** in the file, but blender recognizes it as **Arial Regular**

I've obtained the font names by doing this steps:

- Open blender
- Shift + F4 to open the python console
- Import the current fonts in a variable: `nowfonts = bpy.data.fonts.keys()`
- Print the current fonts to the screen: `print(nowfonts)`:
```
>>> nowfonts = bpy.data.fonts.keys()
>>> print(nowfonts)
[]
```
- Load one font of your preference, in this case I incorrectly put **Arial** instead **arial.ttf**:
>>> bpy.ops.font.open(filepath="C:\\Windows\\Fonts\\Arial")
{'CANCELLED'}
```

The legend {'CANCELLED'} means blender couldn't open the font, be sure you are writingcorrectly the path of the file:

```
>>> bpy.ops.font.open(filepath="C:\\Windows\\Fonts\\arial.ttf")
{'FINISHED'}
```
The legend ` {'FINISHED'}` means the font is loaded in blender, you can check all the operators here: https://docs.blender.org/api/current/bpy.ops.html

- Refresh the variable with the fonts list and print its content:
```
>>> nowfonts = bpy.data.fonts.keys()
>>> print(nowfonts)
['Arial Regular']

>>> 

As you can see, the font is now loaded as Arial Regular. This might be to the fact that this font is an Opentype (which has compressed several types of the same font and blender picks the default one)

I did that for each font I wanted to be present in the UI list for the glare animated title effect.

```
	<param name="fontname" type="dropdown" title="Font Name" description="">
		<values>
			<value name="Bfont" num="Bfont"/>
			<value name="Goudy Stout Regular" num="Goudy Stout Regular"/>
			<value name="Trajan Bold" num="Trajan Bold"/>
			<value name="Retro Cool Regular" num="Retro Cool Regular"/>
		</values>
		<default>Goudy Stout Regular</default>
	</param>
```


### Changes in glare.py.in 

```
# Add a new import
import os
```

- This method performs a loop loading all the fonts in a custom directory:

```
# Add a new method
def load_custom_fonts(custom_font_path):
	for file in os.listdir(custom_font_path): 
		filename = os.fsdecode(file) 
                # The replace fixes the windows path
		fontPath = str(os.path.join(custom_font_path, filename)).replace('\\','\\\\')
		bpy.ops.font.open(filepath=fontPath)
```

- Load the new method before the if:
https://github.com/OpenShot/openshot-qt/blob/develop/src/blender/scripts/glare.py.in#L104

```
# I created a new dir to store the ttf fonts
my_custom_dir_with_fonts =  "C:\\Users\\vvv\\openshot\\ttfs"
load_custom_fonts()
```
- change the if of the font to this :

```
if params["fontname"] != "Bfont":
              # font = bpy.data.fonts[params["fontname"]]
              font = bpy.data.fonts[params["fontname"]]
```

**Comment by GOPiGal** [comment]
@helfgott It seems to be not working in Openshot 3.1.1 from 2023-04-20
I suppose you wanted to use the following:

```
# I created a new dir to store the ttf fonts
my_custom_dir_with_fonts =  "C:\\Users\\vvv\\openshot\\ttfs"
load_custom_fonts(my_custom_dir_with_fonts)
```
Anyway, I have just pointed it to C:\Windows\Fonts `load_custom_fonts("C:\\Windows\\Fonts")` and OpenShot does not show the new font and still shows few fonts that are not even listed in the xml. I guess a step (or two) is missing here?
