### ISSUE TITLE
Crashed when try to open the Preferences Menu.

### ISSUE THREAD

**Issue by ghost** [OpenShot/openshot-qt#3271]
**Describe the bug**
My PC have 2 gpus: a Intel HD4600 and an NVIDIA GTX1070,running windows8.1 pro x64,when I try to open the Preferences in the Edit Menu ,the sofeware crash unless I disable the HD4600.

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 2.5.1
- libopenshot Version:  0.2.5
- Platform: Windows-8.1-6.3.9600
- Processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['zh-CN', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev1-1583113732-b724f2ef-005be5a4-x86_64.exe

**Log Files**
- http://logs.openshot.org/3wpof8hiv6325p5fxz28d3rhzqry66rr/openshot-qt.zip
- http://logs.openshot.org/3wpof8hiv6325p5fxz28d3rhzqry66rr/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**截图** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by SuslikV** [comment]
Look for info in the https://github.com/OpenShot/openshot-qt/issues/3221

Can you say what version of Intel's driver (GPU) is installed on your PC?

**Comment by tigerzhang7** [comment]
> Look for info in the #3221
> 
> Can you say what version of Intel's driver (GPU) is installed on your PC?

driver version 10.18.14.5117 date:2019.11.25

**Comment by SuslikV** [comment]
Then I should give this link: https://github.com/OpenShot/openshot-qt/issues/3224#issuecomment-587298837

Can you try driver update as mentioned there? The DHC drivers are differ from the one you are using now. Maybe you can use even newer driver.

**Comment by SuslikV** [comment]
Forget about it. I didn't noticed that you are using Win 8.
