### ISSUE TITLE
How do I get Hardware Acceration Enabled?

### ISSUE THREAD

**Issue by korishan** [OpenShot/openshot-qt#3277]
I have an AMD Radeon RX 580 8GB video card with latest drivers. Also running latest of Windows 10.

When I go to the preferences of OpenShot, I can't select any Hardware Encoder. The only thing that is shows is:
![Untitled](https://user-images.githubusercontent.com/25021176/75840183-a7cf1500-5d98-11ea-8360-0abed1445c97.png)

I can enable it in my web browsers, so I know the card is capable of it.

Thanks
Kori

**Comment by SuslikV** [comment]
The only available acceleration is:

https://github.com/OpenShot/libopenshot/blob/f1e5c9c8a2acfd738406c869d1d4bc512ca41e04/include/Settings.h#L80-L91

everything else is not implemented (if you'd like to see AMD AMF, for example).

You can try to run the application by another GPU (if any), video driver settings of the OS.

**Comment by nanohtpc** [comment]
no AMD then? 8(((

**Comment by SuslikV** [comment]
The acceleration may unavailable if OpenShot own checks fails too.

**Comment by denni95112** [comment]
I have the same issu, but I'm using Nvidia Quadro P5000. So the NVDEC should be aviable.

**Comment by SuslikV** [comment]
@denni95112 you should share your log-file - it has info about internal checks after the _Preferences_ opened. Thus, it is possible to tell is it fails for you or not.

**Comment by denni95112** [comment]
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/4319145/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/4319146/openshot-qt.log)

**Comment by erlNite** [comment]
I also experience this, OpenShot can't detect my AMD GPU in Preference --> Performance Settings. It's all empty. I'm on a Windows 10 latest official build system, all drivers up to date like GPU and Chipset. My GPU is AMD Radeon RX 5700 XT. I will try and look for optional updates for my GPU, but I was really hoping that OpenShot would support Hardware Acceleration for us AMD users :)

[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/4320750/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/4320751/openshot-qt.log)

**Comment by SuslikV** [comment]
@denni95112 @erlNite Unfortunately, OpenShot own checks shows that decoding failed (both logs NVIDIA and AMD cards).

The hardware acceleration support is very limited in OpenShot. And this wouldn't be changed soon. OpenShot can only use acceleration that standard build of FFmpeg supports and nothing more. The way the OpenShot renders its output sets number of limits on acceleration efficiency (a lot of RAM operations). Maybe you need to look for other program solutions.

**Comment by alichtman** [comment]
@SuslikV Can you recommend any?

> Maybe you need to look for other program solutions.

**Comment by goofyseeker311** [comment]
what's wrong with both RTX 3060 and 5600G both failing to accelerate with GPU on win11
