### ISSUE TITLE
Performance on Intel HD Graphics 620

### ISSUE THREAD

**Issue by ghost** [OpenShot/openshot-qt#3278]
**Question:**
I'm trying to figure out why I'm able to run, for example, Civ 5 fairly well and a few other graphics intensive applications, but OpenShot seems to stutter.

- is OpenShot slow to render because it doesn't have enough memory available? I see it sitting at 2.7 GB and my laptop has 8 GB available
  - **is there a way to increase the amount of memory OpenShot can use to pre-render more frames in the video preview?**
- is there some other performance issue within OpenShot-qt? perhaps some data structures need to change?
- or is my system just terrible? I've tried to rule this out by using kdenlive which stutters less but I know it's written in C++.

Also I wanted to say thank you for creating and working on OpenShot, it's been the only tool I can use on GNU/Linux for video editing and it works well!

**System Details:**
- OpenShot Version: 2.5.1-dev2
- Operating System / Distro: ubuntu 16.04 LTS

**Screenshots:**

![computer-info](https://user-images.githubusercontent.com/2110497/75993417-6d17ca80-5ec7-11ea-85ca-37a68e1611bb.png)

**Comment by rudolfolah** [comment]
I may have answered my own question, though maybe this requires additional documentation in the settings or in the README or wiki somewhere, or some extra logging to confirm Linux VAAPI is being used?

I think I didn't have libva installed though I did have the Intel HD graphics driver installed (I also double-checked which hardware encoder/decoder setting was being used):

    sudo apt-get i965-va-driver install libva-glx1

**Comment by SuslikV** [comment]
>... is there a way to increase the amount of memory OpenShot can use to pre-render more frames in the video preview?

Main menu _Edit>Preferences>Cache>Cache Limit (MB)_

This will not increase realtime performance of the yet not rendered (composed) frames. Just blue line in timeline will increase (showing what already was cached). The number of threads sometimes can increase performance. But most of its own stuff OpenShot doing on CPU (Qt preview etc.).
