### ISSUE TITLE
Appimage asks for desktop entry integrity every time when launch,openshot icon is not shown in menu entry of my os

### ISSUE THREAD

**Issue by Peacepill** [OpenShot/openshot-qt#3279]
**Describe the bug**

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 2.5.1
- libopenshot Version:  0.2.5
- Platform: Linux-4.15.0-20-generic-x86_64-with-Ubuntu-18.04-bionic
- Processor: x86_64
- Machine: x86_64
- Python version: 3.4.3
- Qt5 version: 5.2.1
- PyQt5 version: 5.2.1
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: en_US.UTF-8
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1583451229-f1e5c9c8-0d8d639e-x86_64.AppImage

**Log Files**
- http://logs.openshot.org/aqr82jtj5e6t6zyai5og84j2qstijbvc/openshot-qt.zip
- http://logs.openshot.org/aqr82jtj5e6t6zyai5og84j2qstijbvc/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.
Am using Bodhi 5.1 Linux

**Comment by ferdnyc** [comment]
@Peacepill 

Hmm, let me see if I understand correctly:

1. Launching `OpenShot-v2.5.1-x86_64.AppImage` (or any of the Daily Build variants) prompts you to install a desktop file every time you run it?
    1. If you say _Yes_ to the question, that should no longer happen. When the file `$HOME/.local/share/applications/appimagekit-org.openshot.OpenShot.desktop` is created, the AppImage should detect the presence of the launcher and no longer offer to install it. Can you confirm whether that file exists on your system?
    1. If you answer _No_ to the question, unfortunately it's normal that the prompt will come up each time you launch the AppImage — it's a limitation of the launcher-install logic in the version of AppImageKit we're currently using.
    1. Regardless, if all else fails the dialog can be forcibly disabled — for OpenShot and all other AppImages that use the same launcher tools — by creating a special file that signals to AppImageKit that it shouldn't prompt for installation. Just run the following in a shell:
         ```sh
         touch ~/.local/share/appimagekit/no_desktopintegration
         ```
        You shouldn't ever see the installation-prompt dialog again.

1. Your OS launcher menu entry for OpenShot doesn't show the application icon?
    When the AppImage installs `$HOME/.local/share/applications/appimagekit-org.openshot.OpenShot.desktop`, it uses the path of the AppImage's thumbnail image as the icon. For instance, on my system that file contains:
       ```ini
       Icon=/home/ferd/.cache/thumbnails/normal/d31803764d67c6a9392db4a51abf059e.png
       ```
    That's not a perfect solution, but it does help to avoid the issue of installing and uninstalling an icon file, in addition to the `.desktop` file itself. But it does mean that you may need to browse to the location of the AppImage in your file browser, so that it will generate the thumbnail file.

The way icons in particular are handled for the AppImage and installed .desktop file is a bit strange, now that I'm looking into it I see areas where things can be improved. I'll see about submitting some changes to that side of things that might work a bit better for more users.

**Comment by Peacepill** [comment]
> @Peacepill
> 
> Hmm, let me see if I understand correctly:
> 
> 1. Launching `OpenShot-v2.5.1-x86_64.AppImage` (or any of the Daily Build variants) prompts you to install a desktop file every time you run it?
>    
>    1. If you say _Yes_ to the question, that should no longer happen. When the file `$HOME/.local/share/applications/appimagekit-org.openshot.OpenShot.desktop` is created, the AppImage should detect the presence of the launcher and no longer offer to install it. Can you confirm whether that file exists on your system?
>    2. If you answer _No_ to the question, unfortunately it's normal that the prompt will come up each time you launch the AppImage — it's a limitation of the launcher-install logic in the version of AppImageKit we're currently using.
>    3. Regardless, if all else fails the dialog can be forcibly disabled — for OpenShot and all other AppImages that use the same launcher tools — by creating a special file that signals to AppImageKit that it shouldn't prompt for installation. Just run the following in a shell:
>       ```shell
>       touch ~/.local/share/appimagekit/no_desktopintegration
>       ```
>       
>       
>       You shouldn't ever see the installation-prompt dialog again.
> 2. Your OS launcher menu entry for OpenShot doesn't show the application icon?
>    When the AppImage installs `$HOME/.local/share/applications/appimagekit-org.openshot.OpenShot.desktop`, it uses the path of the AppImage's thumbnail image as the icon. For instance, on my system that file contains:
>    `ini Icon=/home/ferd/.cache/thumbnails/normal/d31803764d67c6a9392db4a51abf059e.png `
>    That's not a perfect solution, but it does help to avoid the issue of installing and uninstalling an icon file, in addition to the `.desktop` file itself. But it does mean that you may need to browse to the location of the AppImage in your file browser, so that it will generate the thumbnail file.
> 
> The way icons in particular are handled for the AppImage and installed .desktop file is a bit strange, now that I'm looking into it I see areas where things can be improved. I'll see about submitting some changes to that side of things that might work a bit better for more users.

thanks it helped too,u are life,time saver : )
