### ISSUE TITLE
Debian Stretch install fails to run with No module named 'openshot'

### ISSUE THREAD

**Issue by scottlinux** [OpenShot/openshot-qt#328]
Installed 2.1.0 release via:
`sudo python3 setup.py install`

It installs to /usr/local/lib/python3.5/dist-packages/

Install completes ok. Then it complains of being unable to import openshot when running openshot-qt:

<pre>$ openshot-qt 
Loaded modules from installed directory: /usr/local/lib/python3.5/dist-packages/openshot_qt-2.1.0-py3.5.egg/openshot_qt
      logger:ERROR Traceback (most recent call last):
      logger:ERROR   File "/usr/local/bin/openshot-qt", line 11, in <module>
      logger:ERROR load_entry_point('openshot-qt==2.1.0', 'gui_scripts', 'openshot-qt')()
      logger:ERROR   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 565, in load_entry_point
      logger:ERROR return get_distribution(dist).load_entry_point(group, name)
      logger:ERROR   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2589, in load_entry_point
      logger:ERROR return ep.load()
      logger:ERROR   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2249, in load
      logger:ERROR return self.resolve()
      logger:ERROR   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2255, in resolve
      logger:ERROR module = __import__(self.module_name, fromlist=['__name__'], level=0)
      logger:ERROR   File "/usr/local/lib/python3.5/dist-packages/openshot_qt-2.1.0-py3.5.egg/openshot_qt/launch.py", line 53, in <module>
      logger:ERROR from classes.app import OpenShotApp
      logger:ERROR   File "/usr/local/lib/python3.5/dist-packages/openshot_qt-2.1.0-py3.5.egg/openshot_qt/classes/app.py", line 40, in <module>
      logger:ERROR from classes import info, settings, project_data, updates, language, ui_util, logger_libopenshot
      logger:ERROR   File "/usr/local/lib/python3.5/dist-packages/openshot_qt-2.1.0-py3.5.egg/openshot_qt/classes/logger_libopenshot.py", line 31, in <module>
      logger:ERROR import openshot
      logger:ERROR ImportError
      logger:ERROR :
      logger:ERROR No module named 'openshot'
</pre>

If I try to run from the extracted tarball, I get:

<pre>
$ python3 src/launch.py
Loaded modules from current directory: /home/stmiller/Downloads/openshot/src
      logger:ERROR Traceback (most recent call last):
      logger:ERROR   File "src/launch.py", line 53, in <module>
      logger:ERROR from classes.app import OpenShotApp
      logger:ERROR   File "/home/stmiller/Downloads/openshot/src/classes/app.py", line 40, in <module>
      logger:ERROR from classes import info, settings, project_data, updates, language, ui_util, logger_libopenshot
      logger:ERROR   File "/home/stmiller/Downloads/openshot/src/classes/logger_libopenshot.py", line 31, in <module>
      logger:ERROR import openshot
      logger:ERROR ImportError
      logger:ERROR :
      logger:ERROR No module named 'openshot'
</pre>

<pre>
$ python3 --version
Python 3.5.2+
</pre>

Hopefully I'm just doing something very wrong. It offhand looks like Debian may require some symlinks to work. Thanks,

**Comment by jccall80** [comment]
same problem. Openshot doesn't work in debian stretch

**Comment by scottlinux** [comment]
Ok I got it to work by first compiling and installling libopenshot-audio and libopenshot first.

Install some dependecies:

`sudo apt install libavdevice-dev libavcodec-dev libavutil-dev libavformat-dev libavfilter-dev build-essential ffmpeg python-pyqt5 pyqt5-dev python3-zmq python3-pyqt5.qtwebkit python3-httplib2 cmake swig checkinstall`

Also needed, libunittest++-dev from sid as stretch does not have this package. Download the deb, install with sudo dpkg -i filename.deb

https://packages.debian.org/sid/amd64/libunittest++-dev/download

----

* Build libopenshot-audio first:

`git clone https://github.com/OpenShot/libopenshot-audio.git`

```
cd libopenshot-audio
mkdir build
cd build
cmake ../
make -j4
sudo checkinstall
```

Name package libopenshot-audio, provides: libopenshot-audio

----

* Then build libopenshot:

`git clone https://github.com/OpenShot/libopenshot.git
`
```
cd libopenshot
mkdir build
cd build
cmake ../
make -j4
sudo checkinstall
```


Name package libopenshot, provides: libopenshot

----

* Register new libraries that were just installed

`sudo ldconfig`

----

* Now we are ready for openshot-qt

`git clone https://github.com/OpenShot/openshot-qt.git`

`cd openshot-qt`

Run from that directory via:

`python3 src/launch.py`

Or install with:

`sudo python3 setup.py install`

Launch openshot-qt to run the app.

**Comment by jonoomph** [comment]
We have a PPA also, and you can grab the debian packages (or source) from that and rebuild using Debian's tools. Thanks!
