### ISSUE TITLE
Openshot stopped running unexpectedly

### ISSUE THREAD

**Issue by Zloyparen** [OpenShot/openshot-qt#3280]
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/4298125/openshot-qt.log)
![shot-2020-03-06_15-35-54](https://user-images.githubusercontent.com/61851365/76080868-50f85400-5fc1-11ea-8b89-60593ca4c92d.jpg)

**Comment by SuslikV** [comment]
`OPENSHOT_VERSION_FULL` AttributeError

Look for the solution (libopenshot lib update) here: https://github.com/OpenShot/openshot-qt/issues/3235#issuecomment-590540210

**Comment by ferdnyc** [comment]
Ugh. Ok, that's it, we're definitely fixing the PPA. `openshot-qt` has a VERSIONED dependency on `python3-openshot` (which in turn depends on a specific libopenshot version), and if that's not codified in the package metadata then things break.

@jonoomph, are you able to give me commit access to the daily PPA repo, or should I shoot patches your way?

In terms of your install, @Peacepill, just run
```sh
sudo apt upgrade python3-openshot
```

That should solve it.

**Comment by Peacepill** [comment]
> Ugh. Ok, that's it, we're definitely fixing the PPA. `openshot-qt` has a VERSIONED dependency on `python3-openshot` (which in turn depends on a specific libopenshot version), and if that's not codified in the package metadata then things break.
> 
> @jonoomph, are you able to give me commit access to the daily PPA repo, or should I shoot patches your way?
> 
> In terms of your install, @Peacepill, just run
> 
> ```shell
> sudo apt upgrade python3-openshot
> ```
> 
> That should solve it.

thanks it solved my problem

**Comment by pleabargain** [comment]
installing from PPA 6JULY.
for
OpenShot version 2.5.1-dev2

errors:

<pre>openshot-qt 
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
         app:INFO ------------------------------------------------
         app:INFO             Mon Jul  6 21:49:25 2020            
         app:INFO               Starting new session              
         app:INFO ------------------------------------------------
         app:INFO          OpenShot (version 2.5.1-dev2)          
         app:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.5.1-dev2
     metrics:ERROR Error determining OS version in metrics.py
      logger:ERROR Traceback (most recent call last):
      logger:ERROR   File &quot;/usr/bin/openshot-qt&quot;, line 11, in &lt;module&gt;
      logger:ERROR load_entry_point(&apos;openshot-qt==2.5.1.dev2&apos;, &apos;gui_scripts&apos;, &apos;openshot-qt&apos;)()
      logger:ERROR   File &quot;/usr/lib/python3/dist-packages/openshot_qt/launch.py&quot;, line 97, in main
      logger:ERROR app = OpenShotApp(argv)
      logger:ERROR   File &quot;/usr/lib/python3/dist-packages/openshot_qt/classes/app.py&quot;, line 115, in __init__
      logger:ERROR from classes import exceptions
      logger:ERROR   File &quot;/usr/lib/python3/dist-packages/openshot_qt/classes/exceptions.py&quot;, line 30, in &lt;module&gt;
      logger:ERROR from classes.metrics import track_exception_stacktrace
      logger:ERROR   File &quot;/usr/lib/python3/dist-packages/openshot_qt/classes/metrics.py&quot;, line 83, in &lt;module&gt;
      logger:ERROR &quot;cd1&quot;: openshot.OPENSHOT_VERSION_FULL,  # Dimension 1: libopenshot version
      logger:ERROR AttributeError
      logger:ERROR :
      logger:ERROR module &apos;openshot&apos; has no attribute &apos;OPENSHOT_VERSION_FULL&apos;
         app:INFO             OpenShot&apos;s session ended            
         app:INFO             Mon Jul  6 21:49:26 2020            
         app:INFO ================================================


fix = 
sudo apt upgrade python3-openshot
then
openshot-qt

**Comment by Colorjet3** [comment]
The latest release of v3.0.0 should work.  If you are going to give this a try, please be sure to download the latest DEV Daily build.  There are some additional fixes since the release of v3.0.0-Release-Candidate.
