### ISSUE TITLE
Feature Request/Addition: DPI-awareness and responsiveness

### ISSUE THREAD

**Issue by jebeld17** [OpenShot/openshot-qt#3284]
**Describe the bug**
OpenShot is not auto-adjusting the app DPI based on my screen resolution.

**Expected behavior**
Upon opening the app in a high-DPI environment, Openshot should open in a high-DPI mode. Upon opening Openshot in any DPI setting and changing thr resolution while the app is open, Openshot should additionally change the app's DPI automatically.

**System Details**
- OpenShot Version: 2.5.1
- libopenshot Version:  0.2.5
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1583451336-f1e5c9c8-0d8d639e-x86_64.exe

**Log Files**
- http://logs.openshot.org/ek9gnd8g5nzkhydv3giyb9p36ievfyeq/openshot-qt.zip
- http://logs.openshot.org/ek9gnd8g5nzkhydv3giyb9p36ievfyeq/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Comment by SuslikV** [comment]
Make sure that _Compatibility_ tab of the `.exe` file properties has no additional settings.
