### ISSUE TITLE
Filter box issue (Give your bug report a descriptive title)

### ISSUE THREAD

**Issue by Mmax2-Github** [OpenShot/openshot-qt#3287]
![Img1](https://user-images.githubusercontent.com/62033637/76359582-cc3c6b80-631b-11ea-9063-01a4e895d129.png)
![Img2](https://user-images.githubusercontent.com/62033637/76359604-d78f9700-631b-11ea-9b29-9c0606b023f0.png)
![Img3](https://user-images.githubusercontent.com/62033637/76359612-da8a8780-631b-11ea-9c11-55d788a32c18.png)
![Img4](https://user-images.githubusercontent.com/62033637/76359616-dd857800-631b-11ea-8b21-e3e2cc03c055.png)

**Describe the bug**
Filter box issue

**Steps to reproduce the behavior:**
I have the italian localized version.
1. Load a video in the timeline and select it: the property panel on the left populates with the properties.
2. In the filter box, type "al" (because I want to see the "alfa" property. All is correct and I see the "alfa" property together with other three properties.
3. If you go on and type "alf", all the properties disappear. Same problem with other property names.

Another example:
1. Type "scal", I see three properties: "Scala", "Scala X" and "Scala Y".
2. Go on and type "scala": all properties disappear.

**Expected behavior**
I have to get the correct properties when I type into the filter box.

**System Details**
- OpenShot Version: 2.5.1
- libopenshot Version:  0.2.5
- Platform: Windows-10-10.0.17763
- Processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['it-IT', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1583451336-f1e5c9c8-0d8d639e-x86_64.exe

**Log Files**
- http://logs.openshot.org/wgekmchjey84ytguqk2nzzk7whqjs3dn/openshot-qt.zip
- http://logs.openshot.org/wgekmchjey84ytguqk2nzzk7whqjs3dn/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Schermate** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by ferdnyc** [comment]
Hmm, odd. Based on the results, I bet the filter search is being done on the English strings, instead of the localized versions. That shouldn't be too hard to fix, hopefully. 

Thanks for reporting!

**Comment by ferdnyc** [comment]
I took a quick look, and I was right. Should be fixed in the development tree soon.

**Comment by SuslikV** [comment]
Yeah, really it can be filtered by the `alpha` instead of `alfa` ^_^

Any localization in OpenShot is affected by this issue.

**Comment by ferdnyc** [comment]
@Mmax2-Github The fix for this issue is now in the development code, and it will be present in the next set of Daily Builds which should be available momentarily at https://OpenShot.org/download/ (They're probably already there, in fact.)
