### ISSUE TITLE
Editing advanced titles on macOS 10.15.3 (Catalina)

### ISSUE THREAD

**Issue by richb-hanover** [OpenShot/openshot-qt#3294]
**Describe the bug:**
When attempting to use the Advanced Title editor (inkscape), the OpenShot window obscures the inkscape editing window. See the screenshot below

**Steps to reproduce the behavior:**
1. Title -> Title
2. See the Title window and select a particular style title
3. Click "Use Advanced Editor"
4. Inkscape opens,but the OpenShot GUI window obscures the Inkscape window.

**Expected behavior:**
I had expected to be able to see the entire Inkscape window.

However, when I make changes in Inkscape, then choose File -> Save, then Quit from Inkscape - the edits seem to transfer back to OpenShot.

**System Details:**
- OpenShot Version [e.g. 2.5.1]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: macOS 10.15.3 (Catalina)
- Inkscape 1.0beta2

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.
Log files can be found in your HOME/.openshot_qt/ folder. Please compress or zip
the log files (as they can become quite large).

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please
attach a small snippet of the exception here, but please keep it as small as
possible (for readability).

**Screenshots:** (Optional)

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1094930/76673139-c5f6fb00-6578-11ea-9b37-3e95a322884d.png">

**Comment by SuslikV** [comment]
Any system affected.
This is by design (modal window in use). Can be changed of course. But developers are busy a bit.

As workaround, you may modify the title directly in the project's folder. After the project saved there should appear new `.svg` file inside the `title` folder. This file will be used as the actual title later (during new drag-n-drop to the _Timeline_ and export).

**Comment by richb-hanover** [comment]
Yes, editing the `.svg` in the `title` folder is an adequate workaround. 

If I were to ask for any attention from the developers, it would be to work on #3295, which would make it easier to create and edit (simple) title slides. Thanks again!
