### ISSUE TITLE
image import very slow

### ISSUE THREAD

**Issue by brcisna** [OpenShot/openshot-qt#3298]
Openshot-2.5.x
Debian 11 ( Bullseye)

After downloading OpenShot-2.5.x AppImage, importing images is extrermely slow. 
Do mostly history videos, so importing 55-75 small resolution images 1280x720 takes almost 5 minutes to import. 
This did not happen in 2.4.x AppImage. Is there possibly a hardware acceleration setting that can be tweaked to try maybe?
Am probably missing something.
This is still by far the best video editing software have found so Thank You to all how put their efforts into this project!

Thank You

**Comment by SuslikV** [comment]
It looks similar to: https://github.com/OpenShot/openshot-qt/issues/444

Info for the developers.

I think, thumbnails creation can be run as separate process and update the model each 10 miniatures are ready or so, while using dummy images for the list creation.
