### ISSUE TITLE
 just cut video and export it WITHOUT any other modifications / encoding?

### ISSUE THREAD

**Issue by bETTY673** [OpenShot/openshot-qt#3300]
I cutted my video without any problem, but cant find setting about making no changes then export video (I mean resolution, filters, audio) just the same videofile, but cutted.

I cant find option do not modify encoding settings and use it from source file

**Comment by ferdnyc** [comment]
There is no such setting. OpenShot is a video-editing suite, not a transcoder.

You may be looking for software like [VidCutter](ozmartian/vidcutter), [Handbrake](https://handbrake.fr), or [Avidemux](http://avidemux.sourceforge.net/).

**Comment by bETTY673** [comment]
I dont want transcode, just cut video **WITHOUT** any encode, just the same setting as original video have

**Comment by bETTY673** [comment]
you dont understand what I mean, I use OpenShot  as editor, so why it dont have option do not change any video encode setting? it always want affect my original video quality, I dont want change any video settings (resolution, codec, audio) **JUST CUT VIDEO.**
