### ISSUE TITLE
After updated V2.5.1  the saved file couldnt open 

### ISSUE THREAD

**Issue by Mediveh** [OpenShot/openshot-qt#3301]
**Question:**
It means that the SVG cannot be found.  Is there any solutions can hlep me get my file back?
{engilsh is not my mother language] 

**System Details:**
- OpenShot Version [ 2.5.1]: {{ log_context.openshot_qt_version }}
- Operating System /Windows 7

**Screenshots:** (Optional)
![未命名2](https://user-images.githubusercontent.com/62345953/76977560-6fbafb00-6970-11ea-8f65-c6da98877e65.png)

**Comment by ferdnyc** [comment]
@Mediveh 

Hmm, it looks like our file path recovery may not have covered all of the bases on fixing up filenames from 2.5.0 projects.

Can you share your project file (`.osp`)? You can add it to a ZIP file and upload it to this issue as a comment attachment. We can definitely recover your project, we just have to figure out what wasn't corrected in the stored filenames and fix it manually.

(And hopefully fix the code to account for those situations in the future.)

**Comment by ferdnyc** [comment]
Sorry, that wasn't too clear.

Please create a ZIP archive of your <code><var>Project</var>.osp</code> file, and attach the ZIP to this issue. We can repair the encoding.
