### ISSUE TITLE
wmv import woes W7 version 2.5.1

### ISSUE THREAD

**Issue by powerstream1** [OpenShot/openshot-qt#3302]
**Describe the bug**
wmv import
Same problem as bug report 2980
I am having issues importing my .wmv file to Openshot to edit them and export them. The files show up in Openshot, but will not play back. When I put them in the timeline, they play as a still image for a few seconds before going to black.  Can't export.
The files were created with Windows Live Movie Maker.

None of the suggestions given under 2980 help.
thanks
mark

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Windows-7-6.1.7601-SP1
- Processor: Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1584480625-816118b6-232f3f79-x86_64.exe

**Log Files**
- http://logs.openshot.org/v4zhl62br3axz9c1je3i4yqwwywncfgn/openshot-qt.zip
- http://logs.openshot.org/v4zhl62br3axz9c1je3i4yqwwywncfgn/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by SuslikV** [comment]
Please, share the file sample (make short one, few seconds is far enough), so developers be able to test it.

**Comment by powerstream1** [comment]
Thanks, here it is:
https://www.dropbox.com/s/0g436xxfs64haha/short.wmv?dl=0

**Comment by SuslikV** [comment]
The file has additional stream (0:0) that carriers cover image (thumbnail). Unfortunately OpenShot tries to read it as mjpeg encoded video and thus skips actual video stream (0:2).

Only workaround I know is to use FFmpeg util to remux file with the different number of streams or in different order (so actual video now goes first):
```
ffmpeg.exe -i "С:\Temp\short.wmv" -map 0:2 -map 0:1 -c copy "С:\Temp\short_no_cover_image.wmv"
```
and only then import it into OpenShot.

**Info for the developers.**
By the way, the FFmpeg based players playbacks this file well, so stream selection is not perfect in the OpenShot. This should be taken into account when the https://github.com/OpenShot/libopenshot/pull/390 will be implemented.

**Comment by powerstream1** [comment]
Thanks for your help!

**Comment by andrewregan** [comment]
This is still a problem for me in the latest daily build, exactly as reported above.
