### ISSUE TITLE
https://github.com/OpenShot/openshot-qt/issues/3300

### ISSUE THREAD

**Issue by bETTY673** [OpenShot/openshot-qt#3303]
Sorry for reopen, want you see this, check my replies here https://github.com/OpenShot/openshot-qt/issues/3300

> I dont want transcode, just cut video WITHOUT any encode, just the same setting as original video have

> you dont understand what I mean, I use OpenShot as editor, so why it dont have option do not change any video encode setting? it always want affect my original video quality, I dont want change any video settings (resolution, codec, audio) JUST CUT VIDEO.

**Comment by SuslikV** [comment]
Unfortunately, the modern non-linear video edit software, like OpenShot, is unable to cut the video in any point and save it without the modification of any other data. The high compression of sources makes this impossible (data next to the cut point depends on both previous and following content). Only few special tools can do such edits and only for some points in the video (not at each frame). This is very specific software, while OpenShot is casual editor.

For simplification OpenShot uses profiles (720p 30 fps for example) just to be sure that everything will be exported at same quality or size. The "guess output settings" tool is not available in OpenShot (yet).

**Comment by bETTY673** [comment]
> The "guess output settings" tool is not available in OpenShot (yet).

Pls add, I have very specific video resolution and video bitrate, but if I type this manually, program cut overalll video quality :-(

**Comment by SuslikV** [comment]
Try `18 crf` setting in the Bitrate field (type it manually instead of bitrate - screenshot of the corresponding field is here: https://github.com/OpenShot/openshot-qt/pull/2967#issue-313345975)
