### ISSUE TITLE
openshot 0% cpu usage not responding

### ISSUE THREAD

**Issue by RED-124** [OpenShot/openshot-qt#3308]
**Describe the bug**
openshot 0% cpu usage not responding

**Steps to reproduce the behavior:**
1. Go to 'openshot'
2. Click on 'open'
3. Scroll down to 'anything during 30 seconds'

**Expected behavior**
Openshot will sudenly stop to respond and task manager indicate a 0% cpu usage.

**System Details**
- OpenShot Version: 2.5.1
- libopenshot Version:  0.2.5
- Platform: Windows-10-10.0.18362
- Processor: Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['fr-FR', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1584748987-2c6d25ee-232f3f79-x86_64.exe

**Log Files**
- http://logs.openshot.org/q48z047zaewl62cwu7iyksotfw0m4ju8/openshot-qt.zip
- http://logs.openshot.org/q48z047zaewl62cwu7iyksotfw0m4ju8/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by ferdnyc** [comment]
@RED-124 

Hmm, sorry to hear OpenShot's giving you trouble. I'm looking at the uploaded log, but one question up front: Step 4 you have listed "See error" —  I know that's part of the initial bug report form, but did you actually get an error, or is that just left over from the template? From the rest of your report it doesn't sound like there was any actual error message.

From the log it looks like OpenShot froze right after you added a file to the project using drag-and-drop, can you confirm that? It's possible the issue is in the drop handling for imports. Or it could be some problem it had importing that video file (though locking up definitely isn't the correct response to import issues, regardless).

**Comment by SuslikV** [comment]
I think your `C:\Users\user\.openshot_qt\backup.osp` (backup file of the most recent project that OpenShot attempts to load on startup) is just damaged - remove it and start new one.

**Comment by RED-124** [comment]
well this time, i imported a video, but it also freeze if i open a menu or make anything in the app... and no, it does not give any message, it just stop responding.
SuslikV, i already reinstaled completely the app, so it shouldn't be a probleme

**Comment by RED-124** [comment]
Ok, before reinstalling, i deleted all the files, backup included and it still wasn't working, but i just deleted it an other time and for now, it seems working...

**Comment by RED-124** [comment]
aaaaand it's not working again and this time i do not have the backup file...

**Comment by RED-124** [comment]
oh, and i have a new information, if i start a video before the freeze, it still play the sound in the background as if the video was still playing while the app it frozen

**Comment by SuslikV** [comment]
Each new behavior of the program requires additional info to see what was happened. Please, add new log-file (start application, see error or strange behavior, find the `openshot-qt.log` file on your PC - copy it and share this copy).

**Comment by RED-124** [comment]
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/4366420/openshot-qt.log)

**Comment by SuslikV** [comment]
Can you share the project file backup (`C:\Users\user\.openshot_qt\backup.osp`) which may has the issue? Then, please, follow these steps:

1) disable auto-saving feature of OpenShot (main menu Edit>Preferences>Autosave tab>Enable Autosave)
2) find and remove backup.osp file (if it is damaged it can't be loaded normally and halts everything on startup of the application)
3) time-to-time make project backups manually.

If task is too demanding, you may try to reduce the number of threads in main menu: _Edit>Preferences>Performance_ by setting _OMP Threads_ and _FFmpeg Threads_ to 0

**Comment by RED-124** [comment]
well, i don't know why, but after erasing the backup file, it never reappeard again, so i can't really share it with you...

**Comment by RED-124** [comment]
And i tried to make what you said, it worked for a bit of time but it's starting to crash again...

**Comment by SuslikV** [comment]
What do you mean by "crash again"? What it looks like, your "crash"?

**Comment by RED-124** [comment]
well, just like before, it stay on what was open and do not respond

**Comment by SuslikV** [comment]
Time to repeat the steps written above. Where is your new log-file of OpenShot?
