### ISSUE TITLE
NoneType object is not subscriptable

### ISSUE THREAD

**Issue by redpaintbucket** [OpenShot/openshot-qt#3311]
When I go to open up the video I was making, the error of "NoneType object is not subscriptable" appears and then the video says it's open but nothing appears. This is one of my favorite videos I've made and it's my second video I ever made also, so I really hope somebody has an answer.

How it happened:
1. A certain video file that worked two seconds ago, all of a sudden it stopped working on me. I couldn't move it to other tracks or move it in general and I couldn't delete it.
2. I saved the video, closed out OpenShot, and then restarted my computer (it became very laggy).
3. Opened OpenShot, opened the file, got the error message of OpenShot not finding a different video clip, selected the folder that had the video clip, and then it gave me the NoneType error.

Expected behavior:
For it to open up the video file and have everything working fine.

System Details:
- OpenShot Version 2.5.0
- Operating System: Windows 10

**Comment by SuslikV** [comment]
Big chance that the project file is damaged. It is better to:
1) update your OpenShot version (to v2.5.1, at least)
2) disable auto-saving feature of OpenShot (main menu _Edit>Preferences>Autosave tab>Enable Autosave_)
3) find and remove `backup.osp` file (if it is damaged it can't be loaded normally and halts everything on startup of the application)
4) time-to-time make project backups manually.

Can you share the project file (`.osp`) which has the issue?

**Comment by redpaintbucket** [comment]
I will update OpenShot to version 2.5.1, I have autosave disabled because it was really annoying. However how do I find the "backup.osp" file and how do I do manual backups? I also can't seem to share the file (I'm new to GitHub and a little bit with OpenShot), so can you also tell me how to share it?

**Comment by SuslikV** [comment]
This error means that the application either running or some issue happened with your PC. You may try to install v2.5.1 application to different folder (uninstall the v2.5.0 first and restart PC - usually this helps).

<kbd>Windows</kbd> + <kbd>E</kbd> there will be Search field or just google how to find file on PC.

Make backups manually - by saving project file time to time with the different name (my_pro_01.osp, my_pro_02.osp, my_pro_03.osp, etc.). Each new project should lie in its own new folder (the folder keeps your custom titles and thumbnails). Copy these `.osp` files (together with the whole project's folder) to different drive for safety (USB drive, for example). Thus, you'll have backup copy of your project. If drive fails - you have a copy on different drive.

**Comment by redpaintbucket** [comment]
I have updated OpenShot to version 2.5.1 (I think I originally had OpenShot open). However I still don't know how to share the project file you need.

With manually backing up projects I do not fully understand your instructions. How would I change the name to my_pro_02.osp, my_pro_03.osp, etc. Also, before I change the name, do I make a new folder with this backup, I copy and paste the folder anywhere else or do I need to put it on a flash drive? (I have one by the way). Does this also make a whole copy of the video but under a different name?

**Comment by SuslikV** [comment]
Each data application keeps in files (file - specially organized data on disk, disk - special device of your PC to store the digital data).

For better handling of saved data - files are stored in folders (folder - specially organized data on disk, mostly like file, but it can store only other files and nothing more).

Files all are different. They has "name" and "extension" (optionally). Extension is letters and numbers after the last point `.` (dot). Example: `my_pro_02.osp` - `my_pro_02` (name) and `.osp` (is extension). Windows usually hides extension from user (it's normal, just to not confuse people).

OpenShots saves it's data as files with the extension `.osp` (they are kind of "project files" for OpenShot). When you are want to save the project, you are clicking main menu _File>Save Project As..._ - here you can type new "name" of the file and click _Save_. Thus, previous file will be untouched and the file with the new name will be created and you will start to work with this new file automatically. If something wrong happens ("NoneType object" message, power loss etc.) - you can click main menu _File>Open Project..._ and open previous file (or more older one that was work normally).

**Comment by redpaintbucket** [comment]
Thank you, I forgot about the option "save as". Anyway, can you tell me how to share my OpenShot video that gives the NoneType error message when I open it? Because when I drag it here, it says it's not a supportable type of file (which makes sense).

**Comment by SuslikV** [comment]
> ...how to share my OpenShot video...?

Video? You shouldn't share the video itself. You only need to make new project file (main menu _File>New Project_) and work with it - the problem ("NoneType object" message) should gone.

If you wan't to share the `.osp` file here, on the github site, then you need to pack it into `.zip` format first (there is different programs to do this, `7-Zip` for example - it supports `zip` as _Archive format_ setting during add).

**Comment by redpaintbucket** [comment]
Well you asked me to share the "video" file that has the NoneType error, and before I screw up anything, 7-Zip doesn't allow me to Archive it or whatever. Should I click extract instead?

**Comment by SuslikV** [comment]
The 

> ...Can you share the project file (.osp) which has the issue?

was only my request to you just to confirm that the issue is already known to developers. By looking into this project file I can make conclusion why it shows to you the error. I'm pretty sure that you already forgot that the file of interest is named `backup.osp`. If you no longer seeing the error just forget about it and close this issue.

To learn how to use 7-zip, please, look for YouTube video tutorials.

**Comment by redpaintbucket** [comment]
Well I assumed that you needed the project files to see what was wrong with the files. However, how would I make a backup on a file with the NoneType error with no previous backups? Also, if I were to click save as on this file (which has the NoneType error and when I open it it says it's open but there's no content opened), would this be the "backup.osp" and would it fix the problem?
[destroying kids in the better counter blox.zip](https://github.com/OpenShot/openshot-qt/files/4397721/destroying.kids.in.the.better.counter.blox.zip)

**Comment by SuslikV** [comment]
This project is insanely huge! 193 MB! Delete it and make new one. Or you may try this one, repaired:

[des - repaired.zip](https://github.com/OpenShot/openshot-qt/files/4397814/des.-.repaired.zip)

about 67 KB to download, CRC of the zip archive MD5:AC3D9D4287F2C9738A7AAABD86AC342F

I doubt, that you'll be able to export such huge project with the OpenShot (the project consist of too many objects). The program will consume whole available RAM of your PC and then will crash, never the reaching the export's end.

Make smaller projects with the OpenShot!

**Info for the developers:**
from line 10727299 there are some null objects (root keys):

```
 "0": null,
 "9": null,
 "72": null,
 "85": null,
 "86": null,
 "166": null,
 "320": null
```

and one block is at line 141778 ("clips" section):

```
  null,
  null,
  null,
  null,
```
similar to: https://github.com/OpenShot/openshot-qt/issues/3314

major space occupied with the history data (about 99% of the file itself).

**Comment by redpaintbucket** [comment]
So you're telling me I can't make normal sized YouTube videos with OpenShot? I made a 12 minute one with no problems. Anyway, thank you so much for fixing the problem! Idk what I would've done if this wasn't fixed, I'll make a backup of this repaired one (just in-case) and backups of any future videos.
