### ISSUE TITLE
adding image to timeline crashes appimage 2.5 and 2.5.1

### ISSUE THREAD

**Issue by angusinalbertaii** [OpenShot/openshot-qt#3313]
**Describe the bug:**
adding image to timeline crashes appimage 2.5 and 2.5.1

**Steps to reproduce the behavior:**
1. attempt to add any file to timeline
2. openshot vanishes

**Expected behavior:**
The file should appear on the timeline

**System Details:**
- OpenShot Version [2.51]           
   openshot-qt version: 2.5.1
    libopenshot version: 0.2.5
    platform: Linux-4.19.0-6-amd64-x86_64-with-MX-19.1-patito_feo

**Log Files:**
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/4366912/openshot-qt.log)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/4366914/libopenshot.log)

**Comment by SuslikV** [comment]
You may try to follow this comment and linked PRs or reports: https://github.com/OpenShot/openshot-qt/issues/3322#issuecomment-607455593

also it looks very similar to: https://github.com/OpenShot/openshot-qt/issues/3239
