### ISSUE TITLE
project_data class sometimes injects numeric keys into project dictionary

### ISSUE THREAD

**Issue by ferdnyc** [OpenShot/openshot-qt#3314]
@ferdnyc I think this mysterious numbers as keys of dictionary can be set only in:

https://github.com/OpenShot/openshot-qt/blob/90e7bc4c9275f0b84340c6b4beda6e49540fee59/src/classes/project_data.py#L192

_Originally posted by @SuslikV in https://github.com/OpenShot/openshot-qt/issues/3290#issuecomment-597801992_

This was in response to my noting that a user's project file contained the following JSON, at the very end of the file:
```json
"version": {
  "openshot-qt": "2.5.1",
  "libopenshot": "0.2.5"
 },
 "4": null,
 "6": null,
 "5": null
}
```

Looking at that part of the code, I concur — it almost _certainly_ must be the source of those spurious numeric keys.

**Comment by SuslikV** [comment]
Additional info. This numbers usually appear only on ungraceful shutdown of the application (crash or whats ever). So, `_set` routine aborts somewhere in the middle.

**Comment by ferdnyc** [comment]
@SuslikV Yeah... it's hard to say what's happening because although `_set` is introducing bad values (at _some_ point), `json` is still able to complete the file and write it's contents to disk, so clearly the save process itself, at least, isn't **that** abortive.

It's possible this is a result of libopenshot crashing or even just being terminated earlier than the frontend code, which then goes on to try and access memory that's already been freed -- which could even be the cause of those crashes. (We still think autosave is a factor in this, right?)

I think there are two fixes that could at least help protect users' data better, and possibly lessen the severity of these problems overall:

#### Overwrites
For starters, autosave shouldn't overwrite the original project file. In fact, **no** saves should overwrite the original file. We should save to a new temporary file, then copy it to the original location after it's successfully written to disk. There's still some chance of corruption if there's a crash during that _copy_, but least incomplete saves aren't guaranteed to corrupt the original file.

What [autosave does right now](https://github.com/OpenShot/openshot-qt/blob/f4615cf1f0ccfc59be433944d436800edb50ff88/src/windows/main_window.py#L622) is,
1. If there's an original file (the user has manually saved and given the project a name/path), it's copied to the recovery directory
1. It lists the contents of the recovery directory, and if there are more than the max number of recovery files there, it deletes the oldest ones (Yes, things happen in this order, which introduces a weird and totally avoidable delay into an operation that should be as close to atomic as possible)
1. After all the furniture is rearranged, the project data is saved over the original file
1. Finally, if there's a backup file lying around from a previous autosave, it's deleted

1. Whereas, if it's autosaving an unsaved project, the backup file is just written/overwritten directly

Here’s how I think that can be improved:
1. First and foremost, no screwing around with deleting backup files in the middle of the autosave! Housekeeping can be done later.
1. Second, instead of copying the project, then overwriting the original, we write the new file to the recovery directory, then **copy the _recovery file_** over the previous save. (We already have a backup of that version, because it would've been written to the recovery directory during the _previous_ save.)
1. Third, we do the same thing for **all** saves, auto- or not. Only difference between the two is, if we’re autosaving an unsaved project, we copy it to the backup file instead.

#### Bad timing
The second thing that I think will make a huge difference is — and I can’t _believe_ I didn’t notice this until now — we need to be **stopping** the autosave timer whenever other critical things are going on. During export, primarily... but also when Blender is running, if Inkscape has been launched, etc.

Maybe we _force_ an autosave first, so that everything is committed to disk in case of a crash. But that timer should **not** be running and triggering autosaves during dicey operations. Heck, we should probably even stop it during preview playback! Right now, the only code I can find that ever stops it is in the Preferences dialog, when the user _disables_ autosave.


...Thoughts?

**Comment by SuslikV** [comment]
I was thinking only about to secure the `_set` itself, like was_started, was_ended, all OK then write changes. The description/comment says for itself that this shouldn't happen (strange keys):

>""" Store setting, but adding isn't allowed. All possible settings must be in default settings file. """


As for auto-saving. Auto-saving is annoying thing. It didn't cycles 3-5 files as it usually done in other applications (user-file is untouched!!!). And OpenShot's backup file, if damaged, causes even more troubles for the users, because it always auto-loads and... and nothing works. Maybe simpler to ask users if they wish to restore auto-backuped file (of course, one of the last 3-5 copies)? Again, restoring backup doesn't mean overwriting user-file!

There is two primary ways to build everything:
1) make stable soft (resolve the known bugs).
2) make small durable part of the soft that will monitor strange behavior (make backups or else) and be lazy on resolving bugs and rather add many new features every day.

Securing auto-save feature wouldn't solve the mistake in the code that surely exist somewhere. But in this case, **the simplest solution is to turn off default setting of auto-saving** in preferences.
