### ISSUE TITLE
impossible d&#39;utiliser l’accélération gpu (Give your bug report a descriptive title)

### ISSUE THREAD

**Issue by JimWatL** [OpenShot/openshot-qt#3315]
**Describe the bug**
impossible d'utiliser l’accélération gpu

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Windows-10-10.0.18362
- Processor: Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['fr-FR', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1584799825-2c6d25ee-232f3f79-x86_64.exe

**Log Files**
- http://logs.openshot.org/yh3svc3dvcg15zbob3dbt2at2llnwr0x/openshot-qt.zip
- http://logs.openshot.org/yh3svc3dvcg15zbob3dbt2at2llnwr0x/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Captures d’écran** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by SuslikV** [comment]
Similar to the: https://github.com/OpenShot/openshot-qt/issues/3277

**Comment by bozzmob** [comment]
I have an Windows 10, Nvidia 1080, Core i7 system.

I went over several issues here that GPU doesn't show up in the preferences>performance. I am facing the same issue. My GPU is not getting detected. Please can you help me with this?

![openshot-error](https://user-images.githubusercontent.com/1252941/83014392-3ec80800-a03c-11ea-8a38-5c105046a81b.PNG)
