### ISSUE TITLE
Audio static on cuts

### ISSUE THREAD

**Issue by danielrcollins1** [OpenShot/openshot-qt#3316]
**Describe the bug**
Audio static on cuts

**Steps to reproduce the behavior:**
1. Make a video from a single source file 
2. Make some cuts in the video, with silence on both sides
3. Test the video in OpenShot: all cuts are smooth in video & audio
4. Export the video
5. View the video externally
6. Video will have a blast of audio static (~1/2 sec) around about half of the cuts

(Have tested this with a variety of different import formats: FLV, MKV, MP4, MOV; behavior is the same for all).

**Expected behavior**
Videos should not have audio static around cuts.

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Windows-7-6.1.7601-SP1
- Processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1584799825-2c6d25ee-232f3f79-x86_64.exe

**Log Files**
- http://logs.openshot.org/b9pkt6olo8mb8e147ohhgkl29lf0leki/openshot-qt.zip
- http://logs.openshot.org/b9pkt6olo8mb8e147ohhgkl29lf0leki/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Comment by SuslikV** [comment]
From the issue description I can make assumption that you are running into:
1) https://github.com/OpenShot/openshot-qt/issues/3316 (or https://github.com/OpenShot/openshot-qt/issues/3256)
2) https://github.com/OpenShot/openshot-qt/issues/2808

Clip just overlaps a bit (zoom-in to 1 sec to check this) and audio is damaged by mistakes in mixing algorithm.

**Comment by danielrcollins1** [comment]
> 
> 
> From the issue description I can make assumption that you are running into:
> 
>     1. #3316 (or #3256)
> 
>     2. #2808
> 
> 
> Clip just overlaps a bit (zoom-in to 1 sec to check this) and audio is damaged by mistakes in mixing algorithm.

No, I just double-checked, that is not the case.

Example: One clip ends at 15.86 and the next starts at 15.87 and there is the half-second burst of audio static around this point. Other half-dozen examples in front of me right now are all similar.

**Comment by SuslikV** [comment]
Cuts in OpenShot is raw data cut (no fade-out or fade-in) - maybe you just hearing the distortion caused by this?

Sample required.

**Comment by danielrcollins1** [comment]
> 
> 
> Cuts in OpenShot is raw data cut (no fade-out or fade-in) - maybe you just hearing the distortion caused by this?
> 
> Sample required.

Thanks for asking about this. Here I've zipped up a test project package (raw video, OSP file, exported video): http://www.superdan.net/_temp/FLVCutTest-Package.zip

The test is: In the raw video I have short statements 1-7 with silence in between. I cut out the even-numbered statements, so 3 cuts: from 1-3, 3-5, and 5-7. In the preview, all of the cuts have smooth (silent) audio. In the exported version, 1-3 and 3-5 are fine, but there's the burst of static on the 5-7 cut. (As I say, it's about half the time; another test like this and I got static in 2 of 3 cuts.)

Any ideas for avoiding this would be appreciated.

**Comment by SuslikV** [comment]
You may try to avoid re-sampling of the audio (if source is 44100Hz keep in export 44100 too). Because it happens only time to time for you - it will be harder to resolve this. But I think, issue is in the re-sampling handling inside the application.

Sure, this is different issue, than the mentioned audio mix mistakes. I can reproduce it with the sample you have provided.

**Comment by danielrcollins1** [comment]
> 
> 
> You may try to avoid re-sampling of the audio (if source is 44100Hz keep in export 44100 too). Because it happens only time to time for you - it will be harder to resolve this. But I think, issue is in the re-sampling handling inside the application.
> 
> Sure, this is different issue, than the mentioned audio mix mistakes. I can reproduce it with the sample you have provided.

It looks like this was likely the root issue. I synched my input & output audio sample rates (to 48K), made a test with a series of 10 cuts, and all of those were fine... certainly the first time I've managed that. Thanks tremendously for the help!

**Comment by SuslikV** [comment]
I lost the thread while looked into the re-sampling code. There is one big mistake. For example, in-sampling rate is almost always = out-sampling rate, some `if` statements are doing nothing, and so on.

What I found so far:

- Same input file without the video (audio only file) has no such issues.
- File container doesn't matter.
- Preview has no issue (JUCE works instead of _libopenshot_'s algorithms).
- Sampling rate value doesn't affects the "cracking" pitch or whatever.
- _Audio Only_ export has issues too.

**Comment by SuslikV** [comment]
@jonoomph can you take a look at what is causing this issue (probably _libopenshot_ bug)?
