### ISSUE TITLE
video export crash (Give your bug report a descriptive title)

### ISSUE THREAD

**Issue by jwbruce** [OpenShot/openshot-qt#3319]
**Describe the bug**
video export crash

OpenShot crashes whenever I try to export my project to video.  No set of options appears to make a difference. 

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Linux-4.15.0-91-lowlatency-x86_64-with-Ubuntu-18.04-bionic
- Processor: x86_64
- Machine: x86_64
- Python version: 3.4.3
- Qt5 version: 5.2.1
- PyQt5 version: 5.2.1
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: en_US.UTF-8
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1585226908-94e9ad3e-232f3f79-x86_64.AppImage

**Log Files**
- http://logs.openshot.org/0wpjun1eubxux87g820j4zk1j4plb1vc/openshot-qt.zip
- http://logs.openshot.org/0wpjun1eubxux87g820j4zk1j4plb1vc/libopenshot.zip

**Exception / Stacktrace**
```/tmp/.mount_ZeWWma/usr/bin/libopenshot.so.19                                          0x963af  [0x7fb613bb23af]
/tmp/.mount_ZeWWma/usr/bin/libgomp.so.1                                          0x7dd4  [0x7fb610522dd4]
/tmp/.mount_ZeWWma/usr/bin/libgomp.so.1                                          0x9d76  [0x7fb610524d76]
/tmp/.mount_ZeWWma/usr/bin/libopenshot.so.19                                          0x982f6  [0x7fb613bb42f6]
/tmp/.mount_ZeWWma/usr/bin/libgomp.so.1                                          0x834a  [0x7fb61052334a]
/lib/x86_64-linux-gnu/libpthread.so.0                                          0x76db  [0x7fb62aac46db]
/lib/x86_64-linux-gnu/libc.so.6 clone                                    0x3f  [0x7fb62a7ed88f]
```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by SuslikV** [comment]
Why AppImage?

**Comment by jwbruce** [comment]
Uh.... because that is the link at the top of the page

https://www.openshot.org/download/
OpenShot Video Editor | Download<https://www.openshot.org/download/>
OpenShot Video Editor is available for download on Linux, OS X, and Windows. We provide both direct download links and torrents. We also have daily builds available using the Daily Builds button below. Release Notes
www.openshot.org

Furthermore, the OS-specific buttons at the bottom of the page do not work.



_________________________________________________

J.W. BRUCE, Ph.D.

Electrical & Computer Engineering

Box 5004

115 W. 10th Street

Cookeville, TN 38505

P (931) 372-3453

F (931) 372-3436

E jwbruce@tntech.edu<mailto:jwbruce@tntech.edu>

www.tntech.edu/ece<http://www.tntech.edu/ece>

________________________________

**Comment by SuslikV** [comment]
Usually, encapsulation used for rare systems where almost nothing works, but Ubuntu... I don't really understand why you are using the site to get the application for your system. Do you installing other applications from the sites too? Ubuntu usually has own repositories. And historically, if this is something special, then all the soft is compiled by the user before the use. I didn't seen that the owner of the project make any `.dep` files by the way.
