### ISSUE TITLE
missig effects under win10

### ISSUE THREAD

**Issue by gebeleixis** [OpenShot/openshot-qt#332]
I am missing effects under win 10 inseder preview 14915 with openshot 2.1.0
This is all the effects that I have
![all filters](https://cloud.githubusercontent.com/assets/22116468/18410647/20328fe2-7768-11e6-960a-bd41b7a7962c.JPG)

**Comment by vsevgit** [comment]
Got the same issue on mint 17.3

**Comment by cRaZyT69** [comment]
Got the same issue on Windows 7 64

**Comment by hayden-t** [comment]
win7x64 same

**Comment by juckendesAuge** [comment]
got same here on Linux Fedora 25 (64Bit) with the newest OpenShot-v2.2.0-2-g5a2acb8-49-603-x86_64.AppImage

https://youtu.be/v3kMnNxKS6k

**Comment by DylanC** [comment]
@gebeleixis - More effects will need to be coded for the v2.x series. Closing this ticket for now. Thanks.
