### ISSUE TITLE
Is there a performance problem in AMD Ryzen CPUs?

### ISSUE THREAD

**Issue by mcleary** [OpenShot/openshot-qt#3323]
**Question:**
I'm new to OpenShot so I don't know if this is the best place to ask this kind of question. I was trying to do some simple edit in a 1080p 60fps video but performance of the timeline far from usable. My CPU supports up to 16 threads, and I could see that OpenShot was using a number of threads but they were all using little CPU, so I couldn't even scrub in my timeline.

I did some tests in Intel Laptop CPU that has 4 threads, and I could see all CPUs being utilised while playing the timeline.

Is there some known issue related to that?

**System Details:**
- OpenShot Version [e.g. 2.5.1]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: Windows 10
- CPU: Ryzen 7 3700X

**Comment by SuslikV** [comment]
Did you try to use less threads in the Preferences of OpenShot?

**Comment by mcleary** [comment]
No but I can try that. Why do you think using less threads should help?

**Comment by SuslikV** [comment]
RAM bandwidth is was my guess.

**Comment by mcleary** [comment]
I can confirm that reducing the number of threads to 6 improves a lot the timeline performance but there are still issues on my machine at least. I will keep playing with the number of threads to see. Thanks

**Comment by ferdnyc** [comment]
Yeah, for _playback_ in particular (which is a weak-performing area for OpenShot at the best of times), additional threads can really work against you. The reader will pull in multiple frames per read in batches equal to the number of threads, so if you've got 16 threads working on decoding, then every time the player needs another frame it has to wait while the cache processes 16 of them — **while** still trying to keep up with playback as well.

(Come to think of it, playback itself will be on yet another thread, so you definitely want to keep the processing thread count at least _slightly_ below your total # cores.)

**Comment by mcleary** [comment]
I was having problems while exporting as well. While I could see several threads working, they were not able to fully utilise a core, so the performance while exporting was not good. The interface froze and it was doing less than a frame a second.

I will try to reduce the number of threads to see if exporting will improve as well.

**Comment by SuslikV** [comment]
No. Forget about hardware support for openshot. The way the acceleration made (per frame parallelism) is not effective. In mjpeg it can work but in mp4, where data may depend on both previous and next info, this will only blow up RAM consumption required for encoding. Maybe block encoding task inside one frame can work in parallel more effectively.

**Comment by toby20130333** [comment]
I meet the same problem
My client use my qt application in AMD Ryzen, running a long time result: The interface froze!!!
any help?
