### ISSUE TITLE
crashes when importing jpg image

### ISSUE THREAD

**Issue by PapaGriz** [OpenShot/openshot-qt#3324]
**Describe the bug**
crashes when importing image

**Steps to reproduce the behavior:**
1. Go to file
2. Click on File
3. Scroll down to import file
4. click on import file
5. import video file
6. success
7. go to file
8. scroll down to import file
9. click on import file
10. import image jpg file/files
11. error pops up stopped working close program

**Expected behavior**
expect jpg file to be imported

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Windows-10-10.0.18362
- Processor: AMD64 Family 16 Model 10 Stepping 0, AuthenticAMD
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/

**Log Files**
- http://logs.openshot.org/2j6xk58i7v7el7albvfh8nibxa71e787/openshot-qt.zip
- http://logs.openshot.org/2j6xk58i7v7el7albvfh8nibxa71e787/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by SuslikV** [comment]
Please share your OpenShot's backup project file: `C:\Users\T.A\.openshot_qt\backup.osp`

Then delete it and try to add image file again.
