### ISSUE TITLE
missing file error when loading up

### ISSUE THREAD

**Issue by Lewis-Durance140** [OpenShot/openshot-qt#3326]
error:
missing file Call of Duty_Modern Warfare 2020-03-28 15-53-19.mp4 cannot be found

1.open OpenShot
2. Click on file 
3. click on open project
4. find and open the project 
5. error

Expected behaviori was going to open OpenShot then click on file then open project, find and open the project, then it would open with the edits i have done and i would be able to continue editing 
System Details
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Windows-10 Pro-10.0.18362
- Processor: Intel Core i5-9600k 3.70ghz

**Exception / Stacktrace**
```No stacktrace found in log files```

                
![asdafgasdwadw](https://user-images.githubusercontent.com/62813497/77832864-f6ba6100-7130-11ea-9371-4ecf521077d6.PNG)

please help if you can i spent hours on the edit which i lost.

**Comment by SuslikV** [comment]
Do you still have this file on your PC? If yes - just point the OPenShot to the folder where the file can be found when it asks for.

**Comment by Lewis-Durance140** [comment]
yes i tried that but the clips aren't in the folder that they are usually in and its not just that clip its all of the ones i used in the edit.

**Comment by SuslikV** [comment]
So what? Just point OpenShot to each source.

**Comment by Lewis-Durance140** [comment]
that worked i thought i tried that before and it didnt work but thanks for your help
