### ISSUE TITLE
Can not fix Blender command Path 

### ISSUE THREAD

**Issue by newwdruid** [OpenShot/openshot-qt#333]
I want to animate text in Open shot but when I hit the animate text:
<img width="1440" alt="screen shot 2016-09-11 at 12 26 51 am" src="https://cloud.githubusercontent.com/assets/21300290/18415403/b046053e-77b6-11e6-8c44-4d177fec59f2.png">

then click the text I want :
<img width="1440" alt="screen shot 2016-09-11 at 12 27 07 am" src="https://cloud.githubusercontent.com/assets/21300290/18415409/d7ef2d4a-77b6-11e6-802a-6c0c4928b53d.png">

Then this comes up:
<img width="1440" alt="screen shot 2016-09-11 at 12 27 21 am" src="https://cloud.githubusercontent.com/assets/21300290/18415416/10d6d4dc-77b7-11e6-842f-ea03c6d9a694.png">

how do I get the path correct so blender works with text creation?

**Comment by mixedbredie** [comment]
In the preferences box you need to fill in the full bath to Blender and Inkscape.  Replace the words Blender and Inkscape with the paths below.
For example, Inkscape may be installed at /Applications/Inkscape.app/Contents/Resources/bin/inkscape-bin
Blender may be installed at /Applications/Blender.app/Contents/MacOS/blender
If you've not got Blender or Inkscape installed then get the apps at https://www.blender.org/download/ and https://inkscape.org/en/download/mac-os/

**Comment by DylanC** [comment]
@newwdruid - See above comment for an answer to your question. You just need to set the path correctly.
