### ISSUE TITLE
The Alpha channel value not restored

### ISSUE THREAD

**Issue by rhelms** [OpenShot/openshot-qt#3330]
**Describe the bug**
The Alpha channel value not restored

**Steps to reproduce the behavior:**
1. Select Ctrl-T to add a Title.
2. Select a template
2. Click on 'Background Color'
3. Change the Alpha channel value to 125 for partial transparency
4. Select OK then Save.
5. Add the title to a track. At this point, the Alpha channel value has been ignored.
6. Edit the Title.
7. Click on 'Background Color'
8. Change the Alpha channel value to 125 for partial transparency
9. Select OK then Save. At this point, the Alpha channel value can be seen in action.
10. Edit the Title
11. Click on 'Background Color'
12. The Alpha channel value presents as 255.

**Expected behavior**
If the Alpha channel value is set, then when the Color picker is selected to edit the colour, the Alpha transparency value should display as the previously saved value.

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Linux-4.15.0-91-generic-x86_64-with-Ubuntu-18.04-bionic
- Processor: x86_64
- Machine: x86_64
- Python version: 3.4.3
- Qt5 version: 5.2.1
- PyQt5 version: 5.2.1
- Qt Detected Languages: ['en-AU', 'en']
- LANG Environment Variable: en_AU.UTF-8
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1585351338-166f6938-232f3f79-x86_64.AppImage

**Log Files**
- http://logs.openshot.org/gzbl85d0f131t11o2um4v2gjo7l26btb/openshot-qt.zip
- http://logs.openshot.org/gzbl85d0f131t11o2um4v2gjo7l26btb/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by ferdnyc** [comment]
> If the Alpha channel value is set, then when the Color picker is selected to edit the colour, the Alpha transparency value should display as the previously saved value.

Mmm, yeah, I see the issue.

The problem is that the alpha value effectively gets separated from the color value in the process of storing it in the SVG source.

When the color dialog returns, it outputs a `QColor` value including alpha, which we store and reuse. That's why subsequent reopenings display the same color values.

When the QColor value is used to update the SVG data for the title, it's split into an RGB value that's used for the `fill` property, and a _separate_ `opacity` property that's assigned the color's alpha level.

It should be possible to recombine them into a QColor with alpha when retrieving the color for re-edits, though.

**Comment by ferdnyc** [comment]
#3331 should fix this, and as a consequence the color dialog will also display the correct alpha value on the _first_ use, as well. (Instead of showing 255 for backgrounds that are really completely transparent.)

**Comment by ferdnyc** [comment]
@rhelms This is now fixed with the merge of #3331, which will be included in the next set of Daily Builds generated at https://openshot.org/download/ if you'd like to test it out!

(They should be there shortly, I'd say give it 10-15 minutes from this comment.)
