### ISSUE TITLE
Failed to load project file /Users/robertramaker/bsur alle video v2.osp: invalid load key, '{'.

### ISSUE THREAD

**Issue by robertramaker** [OpenShot/openshot-qt#3332]
When opening file I get this message:

Failed to load project file /Users/robertramaker/bsur alle video v2.osp: invalid load key, '{'.

project with 32 tracks and 32 small movies.

**Comment by SuslikV** [comment]
Project file is damaged. Please, share it (compress in `.zip` format first), there is chance that it may be recovered.

**Comment by robertramaker** [comment]
what do you need? Just the osp file?

or also all the video’s?

**Comment by SuslikV** [comment]
Only `.osp` file (if you need it repaired and if it does'n damaged a lot, of course). If the project is simple just start new one.

Please, make backups copies of the project files time to time if you are working on something huge.

**Comment by robertramaker** [comment]
Thanks for your reply. I liked working with  openshot a lot, until this happened. It’s a big project with 32 small movies added together. 
If the program can’t do a proper safe, it is to risky using it. Even when I make a lot of backups, I never know when the program will still open the saved files. This is a major issue. I think you really need to fix it. 
meanwhile, i’ll be using another editor.

Robert

**Comment by SuslikV** [comment]
As you wish. Please, share you thoughts when you'll find software that best suits for your needs.

**Comment by robertramaker** [comment]
Hi There,


Here is my osp file. You don’t need to fix it. I remade the project in Shotcut. But I send it to you, so you can find your bug. Let me know if you’ve fixed it!

Regards,
Robert

**Comment by SuslikV** [comment]
I'm assuming it is empty? Then there is nothing to fix. Make backups time to time.

**Comment by robertramaker** [comment]
Well there has to be a problem. I saved a project. Stopped the program the normal way. And the next day my project wasn’t opening and I got the message invalid load key. In my view Openshot has a problem somewhere. But you don’t have to fix my file. I made the project in another editor.

Regards,
Robert

**Comment by SuslikV** [comment]
I still don't see it (your `.osp` file packed into `.zip` archive). Thus, I don't know is this already known issue or new one. But maybe it doesn't matter. Manual backups and disable auto-saving (in OpenShot's Preferences) is what I can recommend to anyone who meets same problems and finds this report.

**Comment by robertramaker** [comment]
Oké, Let’s close the issue.
Thanks for your time
Robert
