### ISSUE TITLE
Save project fails with "Couldn't save project data file: [Errno 24]: Too many open files"

### ISSUE THREAD

**Issue by arroos** [OpenShot/openshot-qt#3334]
When adding multiple subtitles to a video, on selecting "File/Save Project", a dialog is displayed stating ""Couldn't save project data file: [Errno 24]: Too many open files". I was also unable to edit, duplicate or create, edit or duplicate titles, or select Help/About. These actions failed silently with no error displayed. At the time the project included one video clip and 17 subtitles, although a few more titles had been discarded. About 22 subtitles were created overall. 

**Steps to reproduce the behavior:**
Create a new project with two tracks: track 1 (titles) and track 2 (video).
Import a video and drop it on the video track.
Create 22 or more titles. Drop them onto the titles track.
Select "File/Save Project".

**Expected behavior:**
The project is saved. 

**System Details:**
- OpenShot Version 2.5.1 (libopenshot 0.2.5)
- Operating System / Distro: Windows 10, 8 GB RAM

**Log Files:**
[OpenShot Logs.zip](https://github.com/OpenShot/openshot-qt/files/4403683/OpenShot.Logs.zip)

**Exception / Stacktrace:**
N/A

**Screenshots:** (Optional)
![image](https://user-images.githubusercontent.com/25801990/77927863-0314fa00-72a8-11ea-9f8b-dfb0e89dd99e.png)

**Comment by SuslikV** [comment]
It seems that the error was triggered during auto-save of the project. I can only recommend to disable this feature of OpenShot (in main menu _Edit>Preferences>Autosave tab>Enable Autosave_ - make it unchecked). This feature right now makes more troubles than good.

Please, make backup copies of project files time to time.

**Info for the developers**
It has connection to: https://github.com/OpenShot/openshot-qt/issues/3314 in part of "auto-save was not in time...".

**Comment by USATechDude** [comment]
From the Support Help Desk:

>Temmelig Hemmelig reported via email
>11 hours ago (Mon, 7 Dec 2020 at 8:47 AM)

>To: support@openshot.org

> On version 2.5.1 on Windows 10 I encountered the error message "Couldn't save project data file: [Errno 24]: Too many open files".
> 
> Googling this gave me the link https://github.com/OpenShot/openshot-qt/issues/3334
> 
> However, I keep getting the error even after turning off auto save. I suspect this error might be related to having too many objects in memory between saves. I was using Titles to add subtitles, and generated a lot of them (close to 700 .svg files in finished project).
> 
> I found that if I didn't save often enough my computer would eventually become sluggish, and then the error would trigger and I'd have to close OpenShot without saving.
> 
> I also found that if I did remember to save often enough, the error wouldn't trigger.
