### ISSUE TITLE
7.1 headphones buzzing noise and no audio

### ISSUE THREAD

**Issue by D-LUSiON** [OpenShot/openshot-qt#3336]
**Describe the bug**
A week back I bought Asus Centurion 7.1 headphones. I installed them and they work normal while I listen to music, watch video or play games. But when I start OpenShot they start buzzing and playing noise. I imported video and start editing it but there is no sound from the video at all. When I exit the program they stop buzzing and continue to work well (no noise from other audio sources - software players of web audio). I tried starting and exiting OpenShot several times, even restarted the PC but error was present every time. I even tried disabling the 7.1 mode but it's the same. I don't know if this is a problem with this particular model, in general with 7.1 headphones or any 7.1 USB audio system. Drivers for the headphones that are installed are the latest from the official site and firmware is updated to the latest.

Forgot to mention that I tried solution in  #2664 - in "Edit -> Preferences -> Preview" I changed the Default Audio Channels to "Surround (7.1 Channel)" but it didn't work. I also changed the "Playback Audio Device" setting from "Default" to "Windows Audio: Speakers (ASUS ROG 7.1)" but I found that the setting is changed to "DirectSound: Speakers (ASUS ROG 7.1)".

**Steps to reproduce the behavior:**
1. Plug in 7.1 headphones
2. Install drivers and ensure they work as expected
3. Start OpenShot
4. Hear the buzzing noise
5. Exit OpenShot - the noise stops.

**Expected behavior**
Audio output should work normal when using 7.1 headphones.

**System Details**
- PC: Asus ROG G750JZ laptop
- OpenShot Version: 2.5.1
- libopenshot Version:  0.2.5
- Platform: Windows-10-10.0.18362
- Processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1585351843-166f6938-232f3f79-x86_64.exe

**Log Files**
- http://logs.openshot.org/jx3tenlmj8l1xtvodduja3wsw0y91qy1/openshot-qt.zip
- http://logs.openshot.org/jx3tenlmj8l1xtvodduja3wsw0y91qy1/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by SuslikV** [comment]
No one of the developers has multi-channel devices, so support is limited. Just keep pair of casual stereo-phones for OpenShot, they should work OK.
