### ISSUE TITLE
Open Shot Not Responding (Give your bug report a descriptive title)

### ISSUE THREAD

**Issue by akshatdixit85** [OpenShot/openshot-qt#3337]
**Describe the bug**
Open Shot Not Responding

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Windows-10-10.0.18362
- Processor: Intel64 Family 6 Model 69 Stepping 1, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1585351843-166f6938-232f3f79-x86_64.exe

**Log Files**
- http://logs.openshot.org/jzejb7cyanm2ir2a54pivsihfqb2s66o/openshot-qt.zip
- http://logs.openshot.org/jzejb7cyanm2ir2a54pivsihfqb2s66o/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by SuslikV** [comment]
Maybe restart will help? Steps to reproduce behavior is not clear.
