### ISSUE TITLE
Speeded up clips are rendered even faster than should with freezed last frame until desired time

### ISSUE THREAD

**Issue by adawro1000** [OpenShot/openshot-qt#3339]
**Describe the bug**
When speeding up videoclips in timeline - time by 2x or x4 (maybe other settings too) after exporting/rendering whole video(with many clips inside), these clips are generated shorter in the whole video, and when they are on the last frame (earlier than it should be) they are freezed on that frame until next clip starts

**Steps to reproduce the behavior:**
1. Go to 'Timeline'
2. Right Click on desired 'Clip in timeline'
3. Select Time-Fast-Forward 2x (or other)
3. Run Export Video for Youtube HD
4. Play video in external player - clips are faster than proposed 2x (maybe 2,2x or 2.3 times ) so  ends too early with ending frame  freezed untill reaching proper time.

**Expected behavior**

**System Details**
- OpenShot Version: 2.5.1
- libopenshot Version:  0.2.5
- Platform: Windows-10-10.0.18362
- Processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['pl-PL', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1585351843-166f6938-232f3f79-x86_64.exe

**Log Files**
- http://logs.openshot.org/sabgszd1y1byes3u3978al4jwuy2t621/openshot-qt.zip
- http://logs.openshot.org/sabgszd1y1byes3u3978al4jwuy2t621/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by adawro1000** [comment]
One more - if speeded clip was cut at end to remove outtakes, after rendering/exporting that clip is not cut at tha desired point but are played to the natural end and then freezes on last frame until reaching proper end time

**Comment by SuslikV** [comment]
Your log file has no info about the export itself. I assuming that you messed up with the preview and export profiles.

For the cut point of the time manipulated items there were one or two reports ( https://github.com/OpenShot/openshot-qt/issues/3260 )

**Comment by adawro1000** [comment]
Log file is too large, so only some of it i was able to attach to ticket.
I have tried multiple times always exactly setting framerates etc.

**Comment by SuslikV** [comment]
Just save the project, close application, delete the log file, then reopen application load project and click export, wait for the task to complete. When done - close application and compress OpenShot's log-file into `.zip` format.
