### ISSUE TITLE
Downloads

### ISSUE THREAD

**Issue by inukaze** [OpenShot/openshot-qt#334]
Hi there i wanna know, where i can download the "Stable" release , for Windows X86 (32 Bits)
Thank you

**Comment by mrmr77** [comment]
I tried to upgrade win8.1 32bit to 64bit but in vain
how i can run openshot on 32 bit o.s. plz

**Comment by dnlbaines** [comment]
There is currently no 32 bit support for Windows in the newest release of OpenShot.

**Comment by inukaze** [comment]
Which is the lastest version supported on 32 Bits for Windows???  For i
search on the Internet and download it

**Comment by dnlbaines** [comment]
2.0 I believe.

**Comment by inukaze** [comment]
Thank you

**Comment by jonoomph** [comment]
Currently we are only supporting 64-bit builds of OpenShot for Windows. If there is a really great reason why OpenShot needs to be on 32-bit Windows, please let me know. =)  In general, OpenShot needs a pretty modern and powerful computer, lots of memory, fast CPU, etc..., etc...  However, I do understand that some people prefer to use older versions of Windows (companies for example), and perhaps that prevents them from using OpenShot.

I currently have a 64-bit build server that creates all the Windows builds... and I could also create a 32-bit build server, but I just haven't had the time or desire yet. I'm hoping someone will present a good argument for doing so. =)

**Comment by KryptoknightDB** [comment]
I have a 64 bit processor hp laptop but it has win 10 32 bit and i dont want to leave my oemto upgrade to 64 bit os  so please!please!please!please!please!please!please!please!please!please!please!please!please!please!please!please!please!please!please!please!please!please!please!please!please!please!please!please!please!please!please!
give a 32 bit version

**Comment by KryptoknightDB** [comment]
The setup file even says OpenShot-v2.2.0-x86_64.exe so why cant i use it

**Comment by NIPSEN** [comment]
I need a 32 bits version for ma parents computer, this is a good argument !

**Comment by wachin** [comment]
Hi, the PC of my parent are 32 bits. Ok I know that is difficult build a 32 bits version, but some of you can give a tutorial to run the source on Windows 7 32 bits. I download the source and found a list of software, I install python and I try to run in the place of the Launcher but I can't. I think that it is possible. Help

**Comment by tdalsgaard** [comment]
I would also kindly ask for a 32bit Windows version because I have an old PC with 32bit windows
 - this PC  works like a charm 
 - I would also like to be able to use the wonderfull OpenShot video editor on this old Windows PC 
 -  I already uses OpenShot video editor on a 32 bit Linux PC with pleasure.

**Comment by AdBeumer** [comment]
I'd love to have a 32bit Windows version.
I work at a school where I manage about 500 computers. Some are brand new, some quite old. I desperately try to maintain a single image for all computers. This means this golden image has to be able to run on our oldest computers, and that basically means that for now I'm stuck with 32bit Windows. Obviously we won't be running OpenShot on the old pc's. It'll go to the brand new, really butch ones, be it with only 4GB RAM. But as our students mostly will be workig on short clips, I expect we can live with that limitation.

So yes, please, 32bit Windows.

**Comment by miroi** [comment]
Well, I have the same issue - my desktop PC is 32bit Windows7, so I would need 32-bit software version.

**Comment by aGrimRepoMan** [comment]
I too would really appreciate a recent 32-bit Windows version of OpenShot.

**Comment by ArminWeigl** [comment]
Please
