### ISSUE TITLE
Openshot crashes when attempting to open Preferences menu

### ISSUE THREAD

**Issue by Crys85** [OpenShot/openshot-qt#3341]
**Describe the bug**
Openshot crashes when attempting to open Preferences menu

**Steps to reproduce the behavior:**
1. Click on Edit
2. Click on Preferences

**Expected behavior**
Expected to open preferences menu. Instead, Openshot crashes to desktop.

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Windows-10-10.0.18362
- Processor: Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1585351843-166f6938-232f3f79-x86_64.exe

**Log Files**
- http://logs.openshot.org/m9n0qn1o0gjn7u6y0sfqiin1a6fvnkj1/openshot-qt.zip
- http://logs.openshot.org/m9n0qn1o0gjn7u6y0sfqiin1a6fvnkj1/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Comment by SuslikV** [comment]
Application crashes in Quick Sync encoder test.
Try to exclude the crashed test from the list, (by modifying the `preferences.py` file) like in: https://github.com/OpenShot/openshot-qt/issues/3276#issuecomment-595052453

**Comment by Crys85** [comment]
Thanks! Modifying the preferences.py file as suggested allows me to open and use the preferences menu without any crashes.

Might be worth mentioning the system affected has both an onboard Intel HD Graphics 630 and an NVIDIA Geforce GTX1070 - if that in any way can assist developers with troubleshooting for future builds.

**Comment by SuslikV** [comment]
Can you say what Intel's GPU driver version you are using?

**Comment by Crys85** [comment]
The current driver version for the Intel(R) HD Graphics 630 is 26.20.100.7263

**Comment by Crys85** [comment]
For an experiment I manually installed [Intel's latest official driver](https://downloadcenter.intel.com/download/29465/Intel-Graphics-Windows-10-DCH-Drivers?product=98909) (26.20.100.7985) for the HD 630 then uninstalled Openshot and performed a clean install of the latest build. 

Unfortunately using the latest driver did not resolve the preferences menu crashing. It appears modifying the preferences.py file is the only workaround at the moment.

**Comment by SuslikV** [comment]
This is very strange. This is new DCH Driver, so expected to work well. Is there some special tools from the Dell is installed on your PC too (like "Dell Backup and Recovery tool")? I can only guess on this, it caused crashes in OBS Studio earlier because of old Qt libs, but here, in Intel's encoder checks...

**Comment by Crys85** [comment]
No, the Dell Update tool is the only Dell tool installed on this PC and it was only installed a few days ago for the purpose of updating drivers to try resolve the OpenShot issue. Can't say I've ever experienced a crash in OBS Studio before (I use it occasionally for screen recording). According to OBS's default settings it uses NVENC and Direct3D11 for encoding and rendering on this PC.

In task manager the integrated Intel GPU (GPU 0) doesn't ever appear to be utilized in day-to-day operation regardless of application. Only the dedicated nVidia GTX 1070 (GPU 1) seems to see any activity. I suspect the Intel GPU may only be activated/utilised if I connect a monitor into a graphics port on the motherboard and set it up to be a display source - not sure if it can be outsourced for rendering/encoding/hardware acceleration if the primary card in use is the nvidia. The monitor is currently connected straight into the nvidia graphics card.

**Comment by SuslikV** [comment]
The crash looks exactly as Intel's textures tries to load on NVIDIA hw (as I understand it).
