### ISSUE TITLE
Open shot freezes and crashes sometimes

### ISSUE THREAD

**Issue by mick432** [OpenShot/openshot-qt#3343]
**Describe the bug**

Openshot keeps freezing when I try to play different parts of a video and sometimes crashes. 
I create short videos, usually up to 5 mins, no extra effects, just fading. 
When I speed up any part of the video (4x or faster), it will not even replay it.

HW:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  2
Core(s) per socket:  2
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               58
Model name:          Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
Stepping:            9
CPU MHz:             2153.364
CPU max MHz:         3200,0000
CPU min MHz:         1200,0000
BogoMIPS:            5188.20
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            3072K
NUMA node0 CPU(s):   0-3

I have 8GB RAM and 500 SSD Hard drive.

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 2.4.1
- libopenshot Version:  0.1.9
- Platform: Linux-4.15.0-91-generic-x86_64-with-LinuxMint-19.1-tessa
- Processor: x86_64
- Machine: x86_64
- Python version: 3.6.9
- Qt5 version: 5.9.5
- PyQt5 version: 5.10.1
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: en_US.UTF-8
- LOCALE Environment Variable: en_US
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1585351338-166f6938-232f3f79-x86_64.AppImage

**Log Files**
- http://logs.openshot.org/xwwlbvlw78w5341xdnphpsm53n7kx04w/openshot-qt.zip
- http://logs.openshot.org/xwwlbvlw78w5341xdnphpsm53n7kx04w/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by SuslikV** [comment]
Playback of speed forwarded video is simply slow in OpenShot.

To get a bit better performance, try to reduce number of threads in _Preferences_ of the application.

And, you know, there much newer versions available (where number of errors were fixed).
