### ISSUE TITLE
Keyframe & Chroma key

### ISSUE THREAD

**Issue by mandhaniya** [OpenShot/openshot-qt#3345]
1) Sir, Please Enable _**add and Remove option for new key-frame**_, auto key-framing with property is quite disturbing. 
2) Present chroma key is some time not working well. please add **_advanced option for chroma key_**.
3) last one is please provide Screen guide or **_grid display with snapping_** option. so we can easily Transform the clips.

**Comment by mandhaniya** [comment]
..

**Comment by ferdnyc** [comment]
Reopening, in preference to #3347.
