### ISSUE TITLE
Audio Lost (in app and after export)

### ISSUE THREAD

**Issue by byMagix** [OpenShot/openshot-qt#3349]
Hi, I hope you can help me out. I am a complete beginner. I already spent 2 days on trying to keep 1s of audio tape. *facepalm*
I haven't seen any solution on the Internet yet.

What you see in the logs:
1. one clip (Track 1: Trimmed ; Track 2: Original)
2. Put them aligned
3. compared audiocurve (no difference spotted)
4. played trimmed clip (AUDIO LOST)

General Situation:

I want to: 
Trim a short clip down to just a sole word out of a sentence.

I did: 
1. Shot the clip via Nvidia Shadowplay
2. Opening it in Openshot 2.5.1 (daily release)

My problem: 
1.Put clip on track - Audio/in App player just fine
2. Trim Clip down to 0,8-1,5s - Audio gets lost completely / very laggy, no video, sometimes complete crash                      

Tried solutions:

1.Cutting it by Symbol eraser tool/dragging it on the track/right click and "Trim"/properties "Start" "End"-input multiple times with multiple clips 
(somehow certain 2/10 Clips work, regardless of volume, nothing they specifically have in common that the other clips dont have)
2. Adjust Export Profiles/Audio sample rate/Audio codec 
3.Using Openshot 2.4
4. Keeping video tape, only adjusting Volume to 100% the time i want to hear it, otherwise turn it to 0 (WORKED but not functional, i need the video cut)

**Comment by SuslikV** [comment]
Before importing Nvidia Shadowplay recordings into OpenShot can you try to remux them with the _OBS Studio_ application - main menu _File>Remux Recordings_ to new `.mp4` (drag-n-drop files and don' t forget to give to files new names when remuxing).
