### ISSUE TITLE
Open Shot rolling Space title

### ISSUE THREAD

**Issue by douglaspollard** [OpenShot/openshot-qt#335]
I wrote a title that takes about 2900 frames. I tried refresh  so that it would count the frames needed but it did not change from the 2232 frames needed for the example used by Open shot. When I make my title it cuts off the end of the title because there are not enough frames available. Anybody have any ideas?   Thanks, Douglas Pollard

**Comment by DylanC** [comment]
@douglaspollard - Do you have an example for us to try?
