### ISSUE TITLE
Video render hanging at 25% openshot unresponsive

### ISSUE THREAD

**Issue by kuroshima12** [OpenShot/openshot-qt#3351]
**Describe the bug**
Trying to render a video and it always freezes at 25%. In addition openshot is toggling between not responding and normal in task manager. I tried uninstalling and reinstalling a daily build but the issue still persisted. One thing I noticed is that the progress bar up to 25% would hang while openshot appears as not responding and then update when normal.

**Steps to reproduce the behavior:**
Render a 1080p60f video 

**Expected behavior**
I expect the render to complete successfully and not hang at 25% indefinitely.

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Windows-10-10.0.18362
- Processor: AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1585970041-166f6938-232f3f79-x86_64.exe

**Log Files**
- http://logs.openshot.org/wrfqjesb6llerkdq7p196gr03wzvm5zj/openshot-qt.zip
- http://logs.openshot.org/wrfqjesb6llerkdq7p196gr03wzvm5zj/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by SuslikV** [comment]
It is normal for OpenShot (current build). OpenShot running UI and export in one thread, thus updates interface only time to time. In case of demanding task this happens rarely. So, in between, the system informs you that UI is not responsive to the action you may want to take.

**Comment by kuroshima12** [comment]
Understood, regardless I am still experiencing an issue with the rendering process hanging indefinitely.

**Comment by SuslikV** [comment]
Just build simple scene: 50% of timeline is clip without effect + same clip (rest of time) with blur effect. The export should slow down at 50% as blur processing comes in.

**Comment by kuroshima12** [comment]
I did not add any visual effects so I am unsure of why the export would slow down to a halt? The only editing I did was combine video files of the same resolution together?

**Comment by SuslikV** [comment]
You may need to provide you project file to get the answer. It is hard to tell what lies at 25% of your timeline. Maybe you need to start new project if this one is corrupted somehow?

**Comment by kuroshima12** [comment]
Perhaps it is the video files that are the issue? I tried recreating the project multiple times with different configurations and still had the freezing issue.

**Comment by SuslikV** [comment]
This depends on complexity of the scene. Maybe you running too much threads (look at _Preferences_ of OpenShot and reduce the count) for your PC.

Some files, with relatively huge interleaving of video audio packets, are slow to read by OpenShot (only workaround here is remux back into .mp4 by different program - OBS Studio, FFmpeg etc.).

Some files are hard to decode itself (4K videos + HEVC).

All this may slow down the application. But process of export wouldn't stop (it may look like this but it actually working). If progress of the Export after a hour is still not moving, maybe you need other program/hw solutions or you need to simplify the task for OpenShot.

**Comment by 100busy** [comment]
i'm actually have this same problem currently. not really sure why but it's like it can't render video. did you discover what the problem was?
