### ISSUE TITLE
Mouse scroll the properties windows of a picture in the track OpenShot 2.5.1 was crashed.

### ISSUE THREAD

**Issue by blue-dog** [OpenShot/openshot-qt#3352]
**Describe the bug:**
Mouse scroll the properties windows of a picture in the track OpenShot was crashed.

**Steps to reproduce the behavior:**
1.  Drag a picture to track.
2.  Click the picture on the track, Mouse right key,  Click on properties.
3.  Mouse click on the properties and scroll down.
4.  Then OpenShot was crashed.

**Expected behavior:**
 Should not crash in any situation.

**System Details:**
- OpenShot Version  2.5.1 
- Operating System / Distro:  Windows 10

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.
Log files can be found in your HOME/.openshot_qt/ folder. Please compress or zip
the log files (as they can become quite large).

**Exception / Stacktrace:**
 
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/4435815/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/4435816/openshot-qt.log)

**Screenshots:** (Optional)
![11](https://user-images.githubusercontent.com/8454995/78522500-36074280-7800-11ea-8dd1-12e9f396cf72.png)
![22](https://user-images.githubusercontent.com/8454995/78522508-3b648d00-7800-11ea-903f-29f31aeb5e55.png)

**Comment by SuslikV** [comment]
Just coincidence. Qt libs crashed that used in OpenShot to render UI.
I was unable to reproduce it.

**Comment by RDCnlRcos** [comment]
Got the same issue

**Describe the bug:**
After a few minutes of using OpenShot, opening the properties of a clip, then scroll down.
Sudden Crash, no error message.

After a few attempts I noticed that on libopenshot.log after some Py exceptions:
BaseThreadInitThunk                                   
RtlUserThreadStart

[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/4443579/libopenshot.log)

**Comment by SuslikV** [comment]
Hmm. I cannot reproduce this.
