### ISSUE TITLE
My video looks very laggy and choppy after it is exported.

### ISSUE THREAD

**Issue by DrStephan** [OpenShot/openshot-qt#3355]
**Question:**
Alright, so I finished editing my video. preview looks great, the 60fps smoothness that I've wanted. So, I export. An hour later my video is successfully exported. I play back the video using the windows 10 default media player and my video is super laggy and choppy! The audio is perfectly fine. The player also doesn't make videos look choppy when playing back videos that I recorded with OBS and didn't edit at all. So, whats the problem? How can I fix this? 

Here is what I think is the log:
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/4438385/openshot-qt.log)

**System Details:**
- OpenShot Version 2.5.1 (installed today)
- Operating System / Distro: Windows 10, updated.

**Comment by SuslikV** [comment]
1) Select the Preview profile in OpenShot you need. It should match in FPS to your input file (OBS recording).
2) Try to use `18 crf` or `23 crf` like setting in OpenShot for _Export_ bitrate. Screenshot of the corresponding field: https://github.com/OpenShot/openshot-qt/pull/2967#issue-313345975
