### ISSUE TITLE
Openshot 2.1.0 Ubuntu Chrashes on 'play' command

### ISSUE THREAD

**Issue by hbkb001** [OpenShot/openshot-qt#336]
It doesn’t matter whether I hit the space bar or click the play icon it is the same result .... Open-shot 2.1.0 crashes...

System Details are:
Ubuntu 64bit - 15.10
8GB Ram
CPU - Intel i5

upgraded from Openshot 2.0.7 to Openshot 2.1.0

Had the same problem with 2.0.7 as I now have with 2.0.1.

doesn’t help I NEED it to work so I can churn out some videos.

Please Help (And fix) this.

**Comment by devaholic** [comment]
I have the same problem.
System Details
OS: Ubuntu 16.04 LTS
Processor: Intel® Core™ i7-3610QM CPU @ 2.30GHz × 8 
Memory 12G
Graphics: Gallium 0.4 on AMD TURKS (DRM 2.43.0, LLVM 3.8.0)

**Comment by esasarkama** [comment]
chrashes on play:

>>>
main_window:INFO Loaded project /home/esa/Videos/xxx/xxx.osp
uint DBusMenuExporterDBus::GetLayout(int, int, const QStringList&, DBusMenuLayoutItem&): Condition failed: menu
preview_thread:INFO onModeChanged
terminate called after throwing an instance of 'openshot::ReaderClosed'
  what():  The Timeline is closed.  Call Open() before calling this method.
Aborted (core dumped)
<<<
OS: Ubuntu 16.04

**Comment by hbkb001** [comment]
Have since switched systems with the same results...

here is what I'm running now:

ubuntu 15.10
memory 8GB
processor Intel Pentium D CPU 2.80Ghz x2
Graphics Gallium 0.4 on AMD CEDAR (DRM 2.43.0, LLVM 3.6.2)
OS Type 64 Bit
HDD 500GB

**Comment by hbkb001** [comment]
I have had my machine swapped over to be close enough to @devaholic 's machine he's described only difference is that I'm runnung a Duo Core 2.80Ghz  intell processor instead of the i7 & Ubuntu 15.10.

I will atempt to get a Log next time I can and post it.

#willsomeonefixthis PLEASE !!! 

anyhow - UPDATES PLEASE @devaholic @esasarkama @jonoomph @dscso How is it going with your openshot?? still got the same problem or is there a work around that you can share?

**Comment by jonoomph** [comment]
How did you install OpenShot 2.1.0? Have you tried our latest daily AppImage? 
Please download our latest daily installer:

1.  www.openshot.org/download - click '**Other Downloads**' link and grab the newest one
2.  Then enable 'Debug Mode (Verbose)' in the Preferences
3.  Quit OpenShot and delete both log files:
  - **/.openshot_qt/openshot_qt.log**
  - **/.openshot_qt/libopenshot.log**
4.  Re-launch OpenShot and trigger the crash as quickly as possible (to keep the log files small)
5.  Attach **both** log files here

Optionally, and maybe even more useful, if you can launch OpenShot from the gdb debugger, have it crash, and then attach the back trace... which will give us even more info about where it's crashing.

Hopefully we can determine from the .log files what is happening (and crashing). Thanks!

**Comment by esasarkama** [comment]
Hi Jonathan,
OpenShot-v2.1.0-27-g13f14ac-49-587-x86_64
does NOT crash, when I start to play the video.
I'll test further.
Thanks.

br esa

**Comment by jonoomph** [comment]
Sounds promising. I'm going to go ahead and close this ticket if it's no longer crashing on "Play". If you find other issues, feel free to create new issues. Thanks again!
