### ISSUE TITLE
Crash opening saved project

### ISSUE THREAD

**Issue by ferdnyc** [OpenShot/openshot-qt#3360]
Hello, I'm experiencing the same error: as the recovery backup ends loading, the software crashes.
 
1) I removed all the content of the .openshot_qt folder and it starts (as freshly installed).
2) I tried to open the backup.osp projects from the folder I copied before deleting the .openshot_qt and it starts but does not find the images.
3) I re-copied the old folders to the  .openshot_qt renaming the backup.osp file to _backup.osp and it starts. I tried to open _backup.osp file and it loads all the project, creating _backup folder and subfolders, but when it's finished the error comes back.
4) I tried to open the project in the notepad application, but I'm not able to find what's wrong.

I attach the backup.osp file.

I would be very grateful if you can help me.
Thanks in advance and regards!
PG

[backup.zip](https://github.com/OpenShot/openshot-qt/files/4441081/backup.zip)

_Originally posted by @PGB75 in https://github.com/OpenShot/openshot-qt/issues/513#issuecomment-610066788_

**Comment by ferdnyc** [comment]
@PGB75

Looking at your backup file, I _believe_ the issue is that the path `../Desktop/video zombie quarantena/IMG-20200406-WA%04d.jpg` was imported... three times, it looks like, as an image sequence — but looking at the images that were imported individually from that range, the files are _not_ part of an image sequence.

When an image file is imported from a directory that contains lots of sequentially-numbered files, OpenShot will detect that and offer to import them all as an image sequence. Answering "Yes" to that question will import the images as individual frames of a video or animation — which means all of the images in the sequence need to be exactly the same size, have the same color depth, and have other common properties that you'd expect individual video frames to share.

Fortunately, none of those three imports is in use on any of the project clips, so removing them should have no effect whatsoever on the project.

Here's a copy of the file with those three image sequence imports removed, give that a try and see if it works for you.

[backup_restored.zip](https://github.com/OpenShot/openshot-qt/files/4450359/backup_restored.zip)

**Comment by PGB75** [comment]
Hello, it works!
Thankyou very much, have a nice day!
PG
