### ISSUE TITLE
Exporting a video with audio set to mono triggers an OpenShot crash

### ISSUE THREAD

**Issue by HarryT140E** [OpenShot/openshot-qt#3361]
**Describe the bug**
Exporting a video with audio set to mono triggers an OpenShot crash

**Steps to reproduce the behavior:**
1 - open existing project
2 - project consists of 3 pictures followed by a MP4 video (SfB recorded session) that has mono audio
3 - click on 'export video'
4 - Simple tab:
4.1 - All formats
4.2 - Target: (CPU) MP4 (h.264)
4.3 - Video Profile: HD 1080p 25 fps (1920x1080)
4.4 - Quality: Low
5 - Advanced tab:
5.1 - Profile: HD 1080p 25 fps (1920x1080)
5.2 - change Frame Rate from 25 to 15
5.3 - Audio Settings: change Channel Layout from 'Stereo (2 Channel) to 'Mono (1 Channel)
6 - Click 'Export Video'
7 - a new window opens reporting
              'OpenShot Video Editor has stopped working
               A problem caused the program to stop working correctly
               Windows will close the program and notify you if a solution is available
               <Close program> button'

**Expected behavior**
Generating new video files works fine, always! Except when you decide to change stereo to mono output.

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Windows-10-10.0.16299
- Processor: Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-GB', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1586173838-166f6938-232f3f79-x86_64.exe

**Log Files**
- http://logs.openshot.org/pao4tajs47vnmnbtxf2jv10qq72e1jg9/openshot-qt.zip
- http://logs.openshot.org/pao4tajs47vnmnbtxf2jv10qq72e1jg9/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by Justin-CB** [comment]
I second this. This bug is not in 2.4.4 but is in 2.5.0 and 2.5.1. Also, I've found that trying to use the hardware-accelerated video export crashes OpenShot, but that may be because I'm using it on a mac mini, which has the integrated Intel graphics chip.

**Comment by rexdk** [comment]
I have found this too; 2.5.1 Win 10

**Comment by rexdk** [comment]
exporting with mono audio still causes a crash on a daily build downloaded 29Dec20. Issue not resolved.  Win10

**Comment by hughandcry** [comment]
I also have this issue.  The video file I am using is mono, but if I try to export as monom, down it goes.

**Comment by geomouchet** [comment]
This bug is still there.  I can export to stereo, no crash.  Export to mono and it crashes.  My system event viewer shows:

Faulting application name: openshot-qt.exe, version: 2.5.1.0, time stamp: 0x00000000
Faulting module name: msvcrt.dll, version: 7.0.19041.546, time stamp: 0x564f9f39
Exception code: 0xc0000005
Fault offset: 0x0000000000074452
Faulting process id: 0x3850
Faulting application start time: 0x01d78fed3d2385f6
Faulting application path: C:\Program Files\OpenShot Video Editor\openshot-qt.exe
Faulting module path: C:\WINDOWS\System32\msvcrt.dll
Report Id: 9fef1d62-1b6e-4d74-9fc9-f3e043821b01
Faulting package full name: 
Faulting package-relative application ID:

**Comment by geomouchet** [comment]
Update: OpenShot suggested I install the daily build.  That fixed the issue for me.  They said they had re-written the audio processing system earlier this year.

**Comment by DanPinGF** [comment]
Yup... this seems to be another MSVCRT.DLL thing. But it's not just about exporting a project with mono audio. Speeding up a track (#1197) or changing OpenShot settings that are also applicable to pre-existing projects (#4407) both also trigger a crash in MSVCRT.
