### ISSUE TITLE
Snap upon resize

### ISSUE THREAD

**Issue by switzel** [OpenShot/openshot-qt#3365]
**Describe the new feature:**
When resizing a clip while "snap" is active, it would be nice if it "snapped".

**Describe the solution you'd like:**
When I have two clips on different tracks and I try to scale one to the length of the other I would like it to snap at that length (provided "snap" is active).

**Describe alternatives you have considered:**
I tried for an hour and the alternative I found was to do it by hand using ffmpeg.

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your request.

**Comment by SuslikV** [comment]
Not clear. You wish to slice the clips at one point?

**Comment by switzel** [comment]
No, I want to scale a clip up our down, as I can by just dragging the end to the right or left. The only thing I'm missing is for it to snap at a marker or end. Concretely I have a video clip of 11 seconds, say, and an audio track of 11.9 seconds. Now I want a video of 11 seconds during which the audio track is played entirely. [Technically there is an issue whether the audio track should just be scaled or frequencies preserved using Fourier transform but in practice time scanner are such that it doesn't matter; and in any case it's not really related to my request.]

**Comment by SuslikV** [comment]
As workaround - use right-click menu over the clip or ruler - there is option to slice the clips at current point. Because current snapping is scale dependent (and it is unknown when it will become normal one) - the new feature will be useless right now.

**Comment by maksun** [comment]
Hello,

First thank you to Openshot team for this great piece of Free Software.

+1 for this issue apart for this "Now I want a video of 11 seconds during which the audio track is played entirely", ok for the snap between elements on track but you need to adjust your video to fit sound track length I think ;)

I will open another RFE for "snap to playhead", it can be an alternative also.
