### ISSUE TITLE
title editor fails to open .SVG if text property=Flowroot, 

### ISSUE THREAD

**Issue by MBB232** [OpenShot/openshot-qt#3367]
**Describe the bug:**

**Describe the bug:**

**Steps to reproduce the behavior:**

1. Go to 'Title>New Title'
2. Select a default title, Click on 'Edit in advanced editor'
3. click in insert text, single click, type text [image 1]
4 with mouse selector, select text; Object>Properties = [text123]
5 save&close Inkscape
6 See new line in build-in title editor
7 save&close. retry; "Edit title" gives no reaction [Image 2]

8. Select previous edit, Click on 'Edit in advanced editor'
9. click in insert text, draw textbox type text
10  with mouse selector, select text; Object>Properties = 'flowroot'
11. save&close 
12 no new line for your new text. Previous created line is gone too [image 3]

OR
2.  Select previous edit, Click on 'Edit in advanced editor'
3. click on last created line
4 with mouse selector, select text; Object>Properties = 'flowroot'
5 select text (not text box) with text selector
6 TEXT>Convert to text
7  with mouse selector, select text; Object>Properties = 'text'
8 save&close 
8 Both lines are gone, colors are gone
	 "advanced title editor"button is greyed out.  [image 4]

**Expected behavior:**
At least, not break the link to Title editor and Advanced Title Editors if the SVG is broken. 
Better: convert the 'flowroot' text to 'text
Best: have the text recognized as flowroot. (not really sure what this is)

Alternative: Have this documented somewhere

**System Details:**
- OpenShot Version 2.5.1
- Operating System Windows 10
- Inkscape 0.92 + 1.0 Beta (SVG 1.1 ?)

**Screenshots:** (Optional)

**How I ran into this**  
Came across this when I wanted to create a Title file from the Inkscape movie template, and would not see text lines

Actually, originally wanted to import an SVG that came from LibreOffice Draw, which *really* breaks things. Lots of different ID labels for text boxes which probably does not help. Not been able to diagnose properly enough to file a proper bug report. 
https://www.reddit.com/r/OpenShot/comments/fyhpar/documentation_how_to_create_title_templates_from/

**More info that I found**  

> https://graphicdesign.stackexchange.com/questions/21662/how-does-inkscape-decide-whether-to-use-flowroot-or-text
> 
> How does Inkscape decide whether to use flowRoot or text?
> According to the inkscape forum:
> 
> Flowed text is created
> 
> when dragging a frame with the text tool before entering the text.
> when flowing text into a frame (menu 'Text > Flow into Frame')
> To convert flowed text into regular text, save a copy of the file and use the menu command 'Text > Convert to text' in the copy (to be able to edit the flowed text later on in the original if needed
> 
> I have confirmed the convert to text works - just make sure you select the text and not a frame for example.
> 
> Note that some software, such as Apache's Batik SVG Toolkit, cannot render SVG with flowRoot elements. Consequently, any software that uses the Batik library (such as JasperReports) will also be unable to display the SVG file. The error message from Batik will include a short description about flowRoot being the cause of its inability to render the SVG file. Converting the text to text, as described above, should alleviate this issue.
> 

<img width="960" alt="1 InkscapeFlowroot" src="https://user-images.githubusercontent.com/62191951/79031624-5a687380-7ba0-11ea-8b2f-3a151511046c.PNG">
<img width="391" alt="2 OpenShot_OneNewLine" src="https://user-images.githubusercontent.com/62191951/79031625-5b99a080-7ba0-11ea-9b01-dd4b7967ff48.PNG">
<img width="391" alt="3 OpenShot_NoNewLine" src="https://user-images.githubusercontent.com/62191951/79031626-5b99a080-7ba0-11ea-8567-29e19be4e864.PNG">
<img width="391" alt="4 OpenShot_NOExternalEditor" src="https://user-images.githubusercontent.com/62191951/79031627-5c323700-7ba0-11ea-9787-71e9e9bd59c6.PNG">

**Comment by ferdnyc** [comment]
OpenShot's Title Editor is _very_ simplistic, and there's plenty it can't handle — that's sort of the nature of the beast, as it's *not* a full-fledged SVG parser and editor. The templates included with OpenShot are crafted to be editable with it, but SVG files using other text-layout features won't be.

That's precisely why the "Advanced Editor" mode is there ­— because, anything you can't do with the title editor, you can do in Inkscape and just import.

But if you're going to edit your titles in Inkscape, you should _edit_ your titles _in Inkscape_, placing all of the text and other features there and ignoring the Title Editor interface completely.

If you're looking to create title **templates** for OpenShot, then you can't deviate from the very simple format required for its templates: A simple SVG graphic layout with no filters or complex fills/shapes, and multiple, single-line `<text>` elements, each containing a single `<tspan>` child element where content can be placed by the Title Editor.

**Comment by ferdnyc** [comment]
My inclination is to close this as "not a bug" (though it looks like we don't actually have a label for that)... regardless, I'll keep it open as a feature request for the moment, in case anyone else has anything to offer.

But, I can say for sure that the "simple" Title Editor being able to import any arbitrary SVG design and use it as a template, that's just not something that's going to happen. Nor is it a bug that it can't do that. The template interface is not a full implementation of the SVG format.

**Comment by MBB232** [comment]
> My inclination is to close this as "not a bug" ..
> But, I can say for sure that the "simple" Title Editor being able to import any arbitrary SVG design and use it as a template, that's just not something that's going to happen. Nor is it a bug that it can't do that. The template interface is not a full implementation of the SVG format.

I find it a bit disappointing that you don't want to support external SVG import, I find it a really cool feature that I can quickly modify text to an advanced image. But after trying to troubleshoot this I have gotten new appreciation for the complexity of SVG and that you included it at all. 

However that was not the bug I reported; that was when adding a *single* line of text to a *default template* of Openshot by it's own advised external editor in it's *default* condition may break both the template *and* connection to both editors. 

I have to admit, after spending three days of trying to replicate, understand and document the problem, seeing it not classified as a bug hurts. May I at least ask that you  add it somewhere to the documentation?
