### ISSUE TITLE
je ne peut charger des fichier jpg ou png dans le projet (Give your bug report a descriptive title)

### ISSUE THREAD

**Issue by enthalpie91** [OpenShot/openshot-qt#3369]
**Describe the bug**
can't import a local jpeg file
**Steps to reproduce the behavior:**
1. Go to 'fichier...'
2. Click on '.import file...'
4. See error no error the file does'nt appear

**Expected behavior**

**System Details**
- OpenShot Version: 2.5.1
- libopenshot Version:  0.2.5
- Platform: Windows-7-6.1.7601-SP1
- Processor: x86 Family 6 Model 23 Stepping 10, GenuineIntel
- Machine: x86
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['fr-FR']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1586173838-166f6938-232f3f79-x86.exe

**Log Files**
- http://logs.openshot.org/cjz1fc5roqeaigsv0fp7ktrr5fk2v49z/openshot-qt.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Captures d’écran** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by SuslikV** [comment]
Any security software installed? Can you add OpenShot application to the white list? Firewall maybe?

**Comment by enthalpie91** [comment]
Hi

I dont undestand your question. I is a local file

regards

Le 11/04/2020 à 19:17, SuslikV a écrit :

**Comment by SuslikV** [comment]
OpenShot runs local HTTP server to generate thumbnails for the files (_Project Files_ view, _Timeline_ clip etc.). If something is blocks the access to this server, then OpenShot fails to import the whole file.

**Comment by enthalpie91** [comment]
HI Woaoww that's a new I did 'nt start any IIS on the machine , I will check that
regards

**Comment by enthalpie91** [comment]
HI Woaoww that's a new I did 'nt start any IIS on the machine , I will check that
regards

**Comment by enthalpie91** [comment]
Hi I have installed IIS and i still have the same problem. i can import audio file but no jpeg or other image file
regards

**Comment by enthalpie91** [comment]
this problem was reported but no solution given
https://github.com/OpenShot/openshot-qt/issues/1661

**Comment by SuslikV** [comment]
You issue is in blocked HTTP server that program runs and waits for pictures to arrive. When nothing will block the program - it will start to work normally.

Can you try v2.5.1 (release)? Maybe it will work better for you?

**Comment by SuslikV** [comment]
If nothing helps - look for other program solutions. This part of the software wouldn't be changed soon.

**Comment by enthalpie91** [comment]
I don't know why stay on this way. 
I don't understand why openshot does'nt verify at the installation what is right or not
I did'nt have any http server running util i installes IIS and this was not solving the problem
the file is local, don't load from network and so not affect by firewall
M4A file is loaded , not mpeg ou other images file, if a "proces" was blocking it should block every file not specilay mpeg . I use openshot under Linux without trouble

**Comment by enthalpie91** [comment]
I give one other information. 
when i go to the "windows show all" no file appear !! and of corse i have an audio file which appear on the windows audio. looks realy like a bug , on my linux machine nothing is like that

**Comment by SuslikV** [comment]
OpenShot runs its own HTTP server. Because OpenShot's _Timeline_ is actually browser page and it doesn't know other ways to get images for thumbnails. It download them from the local server that OpenShot runs in another thread. So, it like OpenShot has _server_ and _browser_ and both are running on the same machine simultaneously.
