### ISSUE TITLE
C++ Runtime error Details View on Transitions

### ISSUE THREAD

**Issue by lonely188** [OpenShot/openshot-qt#337]
If I right click the Project Files area and choose 'Details View' Ctrl+D and then click on the Transitions tab, the program crashes with a C++ Runtime error. It also crashes if I am on the Transitions tab first, and then switch to the 'Details View' mode. Both 'Project Files' and 'Effects' tabs work fine with the 'Details View' setting.

**Comment by jonoomph** [comment]
This is now fixed. =)
