### ISSUE TITLE
imported video duration is not the actual video duration

### ISSUE THREAD

**Issue by islam2hamy** [OpenShot/openshot-qt#3370]
**Describe the bug**
imported video duration is not the actual video duration

**Steps to reproduce the behavior:**
1. import the video
2. add it to the track
3. the  video duration is 2 minutes , and that is wrong because the  video duration is 8 minutes .

**Expected behavior**
the  video duration in the track is the same as the actual video duration

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Windows-10-10.0.18362
- Processor: Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1586173838-166f6938-232f3f79-x86_64.exe

**Log Files**
- http://logs.openshot.org/f3swmih9txhhq8fpp049ilixx7gkqeyi/openshot-qt.zip
- http://logs.openshot.org/f3swmih9txhhq8fpp049ilixx7gkqeyi/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Comment by SuslikV** [comment]
Why do you think that video has 8 minutes duration instead of 2?

**Comment by islam2hamy** [comment]
i have the video and if i play it with any media player the duration is 8 minutes .

**Comment by islam2hamy** [comment]
it is look like the imported video is cut !

**Comment by SuslikV** [comment]
Sample required. Can you, at least, provide the _MediaInfo_ of the file (in `.txt` format)?

**Comment by islam2hamy** [comment]
here you are
https://gofile.io/?c=OnuzyI

**Comment by SuslikV** [comment]
What happens if you playback this file in any other player? Audio and Video? Is both tracks has same length and how long the movie lasts (use independent clocks for measurement)? Is there static frames? No audio frames?

**Comment by islam2hamy** [comment]
the video is work very well in a different players , and the video and audio is both same length from the first second in the video to the last second in it.

**Comment by islam2hamy** [comment]
more detail information 

https://filebin.net/ydxsdzygyu3x9ftf

**Comment by SuslikV** [comment]
All logs shows that movie has about 134 sec duration. If movie encoded with heavy use of "edit list" or has damaged header then OpenShot is not the program you need.

**Comment by islam2hamy** [comment]
how to check that ?

**Comment by SuslikV** [comment]
It seems that you already did it.

**Comment by islam2hamy** [comment]
ok 
thank you for help
