### ISSUE TITLE
animated title fail

### ISSUE THREAD

**Issue by brcisna** [OpenShot/openshot-qt#3373]
OpenShot-2.5.1 dev2
Debian Bullseye (11)

EDIT : After rebooting server the animated titles appears to be working as expected.
Will mark this as closed. Sorry for inconvience. 

Built openshot from source
When creating an animated title the tile appears to complete. The title is nowhere to be had when completed. The blender path is correct of Blender-2.8.2a
No titles at ~/home/.opernshot-qt/titles

Thank You

**Comment by ferdnyc** [comment]
@brcisna Yeah, `titles` is (now) where SVG files from the [still-image] Title Editor end up, but _animated_ titles specifically would be generated into `$HOME/.openshot_qt/blender/` for an unsaved project, with each render placed in a separate directory named with a randomly-generated unique ID.

Once you save the project, they get transferred into a `$PROJECTNAME_assets/blender` directory next to the project file.
