### ISSUE TITLE
User title templates not preserved in 2.5.0/2.5.1

### ISSUE THREAD

**Issue by ferdnyc** [OpenShot/openshot-qt#3375]
Question: Why is it,if I save a custom footer/title template it is still in
the ~/honm/,openshot-qt/title folder even after program is closed,,,when I
open Openshot,all the saved templates are cleared out? I know I done this
in the past but i am thinking there may be like a 'custom' folder you have
to make within the openshot-qt folder.

_Originally posted by @brcisna in https://github.com/OpenShot/libopenshot/issues/474#issuecomment-611813193_

**Comment by ferdnyc** [comment]
Turns out, this is something we messed up during the move to `_assets` directories.

Previously, `info.TITLE_PATH` (`$HOME/.openshot_qt/title`) was the location for user title templates, and the actual _generated_ titles were stored in the `info.ASSETS_PATH` (which just pointed to `$HOME/.openshot_qt/`).

That was certainly confusing and weird, so with the `_assets` directory change, generated titles moved to live in a `titles` subdirectory of the assets folder (or of the user settings dir, prior to project save), and the `info.TITLE_PATH` follows that location.

All well and good, but it means we accidentally lost the user template location. Looks like we need an `info.USER_TITLES_PATH`.

**Comment by ferdnyc** [comment]
@brcisna This fix is now merged, and the latest `develop` branch should include any SVG files placed in `$HOME/.openshot_qt/title_templates/` in the Title Editor interface. (I had to change the location due to the repurposing of the `.../title` directory, but this new name is more indicative of its purpose anyway.)

**Comment by brcisna** [comment]
Hi Frank,

I have been battling with trying to figure out what i am missing with
animated titles i have created in blender. I am sure there are other things
i need to do for openshot to recognize these .blend files. I have simply
placed them in the default openshot directory that the other stock .blend
files reside at.Of course my custom .blend files are never seen in the
Openshot>Animated titles preview box?

This is Openshot-2.5.1 ,,that i built from source just for completeness.

Thank You.

**Comment by ferdnyc** [comment]
@brcisna Sorry, buried under a mountain of old messages.

To use custom `.blend` files in OpenShot, you'd need to install them directly into the package source, and you'd also need to write:
1. A corresponding `.py` script that sets all of the parameters required by the `.blend`
1. An XML definition for the user interface, which would define how those parameter values are presented to the user.

The structure of the Animated Title templates is quite complex, and not really intended to be user-extensible.

If you _were_ to create all three of those elements, it definitely **is** user-extensible, but like I said it's not for the faint of heart. A `.blend` file alone does not an OpenShot animated title template make.

**Comment by brcisna** [comment]
Hi Frank

Thank You for responding back. I did see in the openshot_qt/blend,
directory there was some companion python scripts and figured somehow this
had to happen for each added .blend file a person creates. I just like
trying to get an understanding of how this all ties together.I appreciate
you explaining this setup,too. I think i'm going to drop trying to do blend
files,,as i had an aneurysm,,about 2 years ago now, and things come very
slow and difficult for me,,,even typing and such. Thought maybe if i tried
hard enough my coordination may come back,but think it slowly gets
worse,,unfortunately.

Thank Again
Barry
