### ISSUE TITLE
Separating audio and video streams, even in a small slice, of a video makes the program very slow and then hang

### ISSUE THREAD

**Issue by vincenzocosta74** [OpenShot/openshot-qt#3378]
While editing a .mkv file, 30-60 minutes long, after cutting a small slice, trying to separate audio from video in the slice, makes the program very slow. The hourglass of the mouse pointer never stops. it is still possible to save the file, but the program is terribly slow. If I quit or kill the program, a process called "openshot-qt" is still running in background and is visible with "top".
This process eats up 100-200% of cpu time (I have an intel core i7-3632QM 4cores/8threads processor).

**Steps to reproduce the behavior:**
1. Create an example.mkv file with obs-studio and screen capture, a quite long one (30-60 minutes)
2. Run Openshot and import the the "example.mkv" file
3. Put the video in a timeline track
4. Cut and remove some slices of the video in the track (it better "works" with many of them)
5. Left click on a slice and "separate audio from video"
6. Then you should have the problem ....you wait and wait and wait ... forever! 

PS: This problem is present in the PPA 2.5.1 version, and it is NOT present in the 2.4 branch.

**System Details:**
- OpenShot (version 2.5.1-dev2) (from Appimage)
- Operating System: Kubuntu linux 18.04.4 - 64 bit - with 5.3.0-46-generic Linux kernel

**Attachments**
Here is a link to download my video project:
https://drive.google.com/file/d/1Xc_p6J6zrVntwxc-HgMttKXOxq-T8bPk/view?usp=sharing

here is a video showing the bug:
https://drive.google.com/file/d/12YSBCHOj8UtuBsma5cG8SFtlZTk6Q3Tu/view?usp=sharing
For some reason, OBS-studio was not able to record the hourglass in the mouse pointer in the previous video.

**Log Files:**
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/4475143/openshot-qt.log)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/4475144/libopenshot.log)

**Comment by SuslikV** [comment]
Slicing in OpenShot (current build, v2.5.1) is just a reference to whole original file (only time restrictions are set, like "from..to"). So, slowing is possible. It needs time to investigate - if there bug (and simple fix is possible) or just design issue.

**Comment by vincenzocosta74** [comment]
Ok, but something happened from version 2.4 -> 2.5, as with 2.4 it was not that bad. Currently, each time I need a separation between audio and video I end up killing the program a restarting. It makes the entire experience quite frustrating.

**Comment by SuslikV** [comment]
The v2.5.x uses much more threads by default (look at _Preferences_ of OpenShot).

**Comment by vincenzocosta74** [comment]
I made a small experiment. I tried to modify the number of threads used by openshot. In Preferences, I tried setting the "Thread OMP" and "ffmpeg thread" parameters to various values, trying with 0 (default), 2, 4, 8. Nothing changed in the behavior of the program, with my video project. The main problem is not "slicing", which is quite fast, but separating video and audio in a slice. Once I give this command the program becomes unusable and I need to kill it.

At least I've found a strange way to partially unblock the program after it becomes terribly slow: if, after the "separate audio and video" command I go the Preferences menu to modify the number of threads, the mouse pointer hourglass stops, and the program seems to behave normally again. But if I issue the "separate" command again it slows down again.
Then, if I try to stop the program in a "clean" way with the "File->Exit" menu command, the program stops, but a process called "openshot-qt" is still running in the background, and I need to kill it manually.

**Comment by SuslikV** [comment]
There is no developers who be able to solve this soon. If you you working on something important for you, please, consider to try other software solutions.

**Comment by Justin-CB** [comment]
I've noticed this issue with 2.4.4. The only solution was to save, kill openshot, then reopen the file.

**Comment by ctsdownloads** [comment]
I can duplicate this on PCLinuxOS as well. To replicate, I right click on a video clip that contains audio, choose separate audio, single clip all channels. If the video is more that 20 minutes, it will take a very long time to process kicking the CPU into high gear. It does completely, however.

I don't recall how long it takes exactly, but if left alone until it finally completes, it does work. One workaround for avoiding this is to mute the audio (right click the clip, volume 0), then drag the raw video clip into audacity (yes, Audacity can read mp4 video containers as audio). Export it from Audacity to a wav file. The use that wav file in OpenShot on a separate time line. Not ideal, but it's what I do if I need to see my wave form audio for editing.
