### ISSUE TITLE
German translation problem (Ausblenden should be Blenden)

### ISSUE THREAD

**Issue by TheRaven500** [OpenShot/openshot-qt#3379]
**Describe the bug:**
Not really a bug, more a translation problem and easy to fix:
In german language if you like to fade an item it is called "Ausblenden" which means "Fade out" and this is wrong. It should be "Blenden" which means "fade".
In short: Change "Ausblenden" to "Blenden" in german language/translation.

**Steps to reproduce the behavior:**
1. Switch to german language
2. Import an item
3. Klick on the arrow on the item
![fade](https://user-images.githubusercontent.com/63654062/79235102-76ec0080-7e6b-11ea-9a1f-4d4aa358474a.png)

**Comment by ferdnyc** [comment]
@TheRaven500 

Thanks for pointing that out! Our translations are a community project over at the Ubuntu Launchpad site, the German translation interface is https://translations.launchpad.net/openshot/2.0/+pots/openshot/de/+translate — I'm sure they'd welcome your participation, if you have the time!

There are some introductory guide links at the top of the page to get you oriented. (I mean, I assume they will. I really can't comment on the quality or usefulness of the guides, as they're in German! :laughing: That's also why I'm reluctant to just make this change myself — your explanation makes total sense to me, and I _assume_ it's correct, but I don't really feel qualified to "own" that change myself.)

**Comment by TheRaven500** [comment]
Thank you very much. I think (hope) i have fixed it. I changed german translation 139. to "Blenden".
Maybe i found other translation problems or can add some translations.
