### ISSUE TITLE
Open Project and Import Files Dialogs

### ISSUE THREAD

**Issue by Windsurfer01** [OpenShot/openshot-qt#338]
In Linux Mint 18, the Open Project and Import Files dialogs only show the /home/me path. Other mounted drives are not listed.

There appears to be no way to open a project on another drive.

To import Files, the work around is to use the system file manager to drag and drop the files onto the Project Files window.

**Comment by JtLively** [comment]
Try the newest version and create a new issue, including OS and Openshot version, if you have the same issue.

Also, check /mnt and /media
