### ISSUE TITLE
Set custom Bitrate/Quality as default

### ISSUE THREAD

**Issue by nicmichael** [OpenShot/openshot-qt#3381]
**Question:**

Is there any way to specify a default bitrate or quality for encoding? The current profiles don't seem to give that option.

I'm frequently exporting videos, always with the same settings:

- mp4/h.264 with 
   - video libx264 codec at 1.5 MB/s target bitrate
   - aac audio 48 khz 96 kb/s bitrate

These settings are somewhere in between the default quality options "medium" (which gives me too large of a file size) and "low" (which gives poor quality). Every time I export, I have to select "medium", then go to the "Advanced" tab and manually edit the bit rates for video and audio. Quite tedious. I wish users could configure a custom profile for not just resolution and frame rates, but also codecs and encoding settings. Or is this already possible somehow?

**System Details:**
- OpenShot Version 2.5.1
- Ubuntu 18.04

**Comment by injiniero** [comment]
Hi, @nicmichael 
Yes, you can create a custom preset and save it at your /home/user/.openshot_qt/presets directory.
As an example, I've created this one for x264 crf encoding:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE openshot-export-option>
<export-option>
	<type translatable="True">All Formats</type>
	<title translatable="True">MP4 (h.264 crf)</title>
	<videoformat>mp4</videoformat>
	<videocodec>libx264</videocodec>
	<audiocodec>aac</audiocodec>
	<audiochannels>2</audiochannels>
	<audiochannellayout>3</audiochannellayout>
	<videobitrate
	 low="50 crf"
	 med="25 crf"
	 high="0 crf"></videobitrate>
	<audiobitrate
	 low="96 kb/s"
	 med="192 kb/s"
	 high="224 kb/s"></audiobitrate>
	<samplerate>44100</samplerate>
</export-option>```
This is just a modified copy of the original /usr/lib/python3/dist-packages/openshot_qt/presets/format_mp4_x265_crf.xml file.

**Comment by nicmichael** [comment]
Sweet! Thanks a lot @injiniero. I just got to try it out, and it works great. Saves me a lot of extra clicks. Thanks for the quick help.

**Comment by SuslikV** [comment]
@injiniero please edit your post to fix the formatting issues (code example extends to the end of the post, probably extra empty line is missing for separation).

**Comment by injiniero** [comment]
![imagen](https://user-images.githubusercontent.com/63733300/79695697-a25e5900-8278-11ea-874d-aaf5d6daf63d.png)
@SuslikV I see the whole post, only the last line overflows at right margin.

**Comment by SuslikV** [comment]
@injiniero here what I mean:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE openshot-export-option>
<export-option>
	<type translatable="True">All Formats</type>
	<title translatable="True">MP4 (h.264 crf)</title>
	<videoformat>mp4</videoformat>
	<videocodec>libx264</videocodec>
	<audiocodec>aac</audiocodec>
	<audiochannels>2</audiochannels>
	<audiochannellayout>3</audiochannellayout>
	<videobitrate
	 low="50 crf"
	 med="25 crf"
	 high="0 crf"></videobitrate>
	<audiobitrate
	 low="96 kb/s"
	 med="192 kb/s"
	 high="224 kb/s"></audiobitrate>
	<samplerate>44100</samplerate>
</export-option>
```
This is just a modified copy of the original /usr/lib/python3/dist-packages/openshot_qt/presets/format_mp4_x265_crf.xml file.

**Comment by ctsdownloads** [comment]
This has been referenced in this Reddit thread as well. 
https://www.reddit.com/r/OpenShot/comments/gnxenl/open_letter_to_jonathan_reddit_sticky_easy_fixes/
