### ISSUE TITLE
Bucle in open a project

### ISSUE THREAD

**Issue by bydariogamer** [OpenShot/openshot-qt#3382]
**Describe the bug:**
When opening a project, I'm not able neither to open it, nor to cancel the action.
I only receive a message box with "unable to find blablabla.mp4" and the program reopens a "select file" window _ab aeternum_

**Steps to reproduce the behavior:**
Just try to open the .osp file

**Expected behavior:**
Open the project. That's not the actual problem anyway, I espected I could cancel it and try to reopen the program, but it wasn't possible. 

**System Details:**
- OpenShot Version : last one at 15/04/2020 for my OS
- Operating System / Distro: Windows 10

**THE PROBLEM:**
The actual problem is I moved some files since the last time I open the project, so the program was uncapable of finding them. I realize it so I cancel the action,but then it opens a new "select file" window, so I try to cancel it another time and it gave me the same error, and reopen the same window. I close the program in the task menu of Windows, but I didn't espect these kind of bucles just because a file moved since last time.

------
Sorry for my english, not actually good.
I would like to understand the problem, so please, send me an email to the direction attached to this profile.

**Comment by SuslikV** [comment]
Hit <kbd>Esc</kbd> button and hold it until you skip every missing files prompt.

But for sure , there should be more convenience method to cancel the open if for example needed drive (with sources) is missing/not connected right now.

**Comment by Justin-CB** [comment]
bucle is loop in english, by the way

**Comment by bydariogamer** [comment]
Hahaha. Thanks, I'm not English so I make this type of mistakes all the
time. And thank you for the solution for the problem. I've created a button
to kill the process directly when this happens, cause other menus fall in
loops sometimes.
