### ISSUE TITLE
Fonts do not* show correctly

### ISSUE THREAD

**Issue by joejoemars1** [OpenShot/openshot-qt#3384]
(This is the first time I've submitted a report, sorry if there are missing/vague details)

Some fonts (or most, I did not check many) do not show up correctly, setting the text style or attempting to increase the font size does not work either.

**Steps to reproduce the behavior:**
1. Go to 'Title' at the top of the window
2. Click on 'Title'
3. Select a title of any sort
4. Change the font to Arial, Arial Black, or stay on Ubuntu OR change the font style
5. The fonts should not display correctly

**Expected behavior**
The text should be in the correct font, change the style, and change size.

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Windows-10-10.0.18362
- Processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1586925760-166f6938-232f3f79-x86_64.exe

**Log Files**
- http://logs.openshot.org/i8faw761vpw3nyjr18j6zsgdvinz6oy1/openshot-qt.zip
- http://logs.openshot.org/i8faw761vpw3nyjr18j6zsgdvinz6oy1/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by ferdnyc** [comment]
@joejoemars1357 

Hmm. I'll try to take a look. I was going to point you to #2069 and #2324, but I see you're on Windows so those don't really apply. It _should_ be possible to change fonts in titles, though.

It's probably worth pointing out (as is discussed in #2069) that:
1. Font _size_ changes aren't possible. (Even though the font selector lets you choose a size; we don't have any control over that).
1. The font list will unfortunately include any bitmap fonts installed on the system. Even when selected those won't work, as they're not compatible with the SVG format.

**Comment by Algorithman** [comment]
I can confirm this issue. Even with the extended edit in inkscape (where the correct font is shown) openshot reverts to it's standard font all the time.

**Comment by masm32-source** [comment]
Hello,
I wanted to change the font of a title, with a font I installed to the WIndows fonts. I doesn't work, font always was Ubuntu font. Then I discovered taht if I install the font for all users, it was suddenly possible to change the font to my installed one. But sizing doesn't work. Maybe that helps someone.

**Comment by joejoemars1357** [comment]
Yup, if you install the font for all users, it'll show up correctly but won't size correctly like with other fonts.

**Comment by mortisthanos** [comment]
I've also noticed that OTF fonts won't show up correctly if selected within the Program, but if I open Inkscape outside of the program and manually create/change a saved title that all installed windows fonts are available and working and sizing of the fonts work too.

**Comment by luftwafflezz** [comment]
I can also confirm this issue. It's a problem for me because I don't like the default font in my video.
