### ISSUE TITLE
Give your bug report a descriptive title

### ISSUE THREAD

**Issue by aoipersd15** [OpenShot/openshot-qt#3385]
**Describe the bug:**

**Steps to reproduce the behavior:**
1. Go to 'Edit'
2. Click on 'Preference'
3.  Jump out the Program 

**Expected behavior:**

**System Details:**
- OpenShot Version 2.5.1
- Operating System / Distro:  Windows 10

**Comment by SuslikV** [comment]
Highly likely that application crashes in Quick Sync encoder test.
Try to exclude the crashed test from the list, (by modifying the `preferences.py` file) like in: https://github.com/OpenShot/openshot-qt/issues/3276#issuecomment-595052453

What version of the Intel's GPU driver are you using?

**Comment by aoipersd15** [comment]
inter i5-7500 CPI 3.40GHz 3.41GHz

SuslikV <notifications@github.com> 於 2020年4月18日 週六 上午3:24寫道：

**Comment by aoipersd15** [comment]
it done, thanks

Orl qaq <qaqorl@gmail.com> 於 2020年4月18日 週六 下午1:05寫道：
