### ISSUE TITLE
Add Icons and new template features

### ISSUE THREAD

**Issue by Paul-Mirowsky** [OpenShot/openshot-qt#3386]
There is a need for templates. Each piece of hardware involved has it's own corrective needs. It would be nice to have templates to do quick corrections per hardware type.
Adding 3 Icons with a universal meaning. Rather than right clicking for a menu, it is suggested that their be universal icons at global, track and select levels.

![Universal Icons for menu - 1](https://user-images.githubusercontent.com/63878491/79611266-3a691080-80c8-11ea-8258-8e3f9191d2af.png)
![Universal Icons for menu - 2](https://user-images.githubusercontent.com/63878491/79611280-42c14b80-80c8-11ea-98e1-1c207c67ba75.png)
![Universal Icons for menu - 3](https://user-images.githubusercontent.com/63878491/79611292-46ed6900-80c8-11ea-9274-2502cea372f2.png)
![Universal Icons for menu - 4](https://user-images.githubusercontent.com/63878491/79611299-49e85980-80c8-11ea-9018-d6beb349b60f.png)
![Universal Icons for menu - 5](https://user-images.githubusercontent.com/63878491/79611306-4c4ab380-80c8-11ea-8324-fc38e192ca3b.png)
![Universal Icons for menu - 6](https://user-images.githubusercontent.com/63878491/79611309-4ead0d80-80c8-11ea-8d30-06a43a62b63a.png)
![Universal Icons for menu - 7](https://user-images.githubusercontent.com/63878491/79611315-510f6780-80c8-11ea-96d6-ce2b2b71b1a0.png)
![Universal Icons for menu - 8](https://user-images.githubusercontent.com/63878491/79611318-540a5800-80c8-11ea-8955-d8e36c0a818a.png)
![Universal Icons for menu - 9](https://user-images.githubusercontent.com/63878491/79611322-566cb200-80c8-11ea-9c7b-e4df44bec10a.png)

**Comment by Paul-Mirowsky** [comment]
The last image titled "Video Icon selected for last item selected" had icon on tracks at left. My bad. They should not be there.  Only the last selected item (center right) should be available.

**Comment by SuslikV** [comment]
I cannot understand logic behind this suggestion. Hardly believable that casual user will do.

**Comment by Paul-Mirowsky** [comment]
1.

    It is possible that many might find that right clicking is second
    nature to finding out what is to be done next. However, an Icon
    immediately initiates interaction. At a Global level, it is equal to
    <Ctrl-A>.  At Track level, the entire Track would be selected in
    Red. The individual item Select function remains the same.

 2.

    Templates... Suppose you would like to initially apply audio set to
    0% and video to use fade in/out fast to a particular piece of
    hardware's file. By using Global, Track and Select levels this can
    be done easily. It could also supplement filters such as white
    balance of color correction in the future. This would not require
    doing the same menu multiple times to apply multiple functions.

 3.

    The icons are level aware.  A Global function is overridden by a
    Track function and a Track function is overridden by a Select
    function. This is standard top/down logic.

I would also suggest that holding the <Ctrl> key while selecting Track 
would allow selecting multiple Tracks. The last track Selected Icons 
would apply to those Tracks.

If you look closely at each PNG, they accurately displayed with 
highlighting in Red and show position of the Icons.

Reminder: the last "Video Icon selected for last item selected" PNG is 
incorrect as Icons are shown on Tracks, this should be on Mouse Over only.

Note: The Asterisk (*) icon is used incorrectly in the example as it is 
a universal "Settings" icon. There needs to be some other design for this.

Hope this helps.

Paul

**Comment by SuslikV** [comment]
As user, I rarely using right-click menu. Positioning, slicing and align is more common tasks in the _Timeline_. I don't see this suggestion as improvement. UI should be clear of side elements.

**Comment by Paul-Mirowsky** [comment]
I hadn't used any of this type of software for 5 years and many things 
have improved. I tried PiTiVi first, but it did not give me what was 
needed. I then tried OpenShot. After making 3 videos, as a user, this is 
what I saw as missing. Given the right icons, they can be very 
intuitive. It's why the tools you suggest have them, not the reason why 
they are not there.

Hope this helps.

Paul

**Comment by Paul-Mirowsky** [comment]
Now that I think about it, both the "Snapping" tool and the "Razor" tool 
are only context sensitive at the Select mode only. Why have them so far 
away from where they are needed.
