### ISSUE TITLE
Crashes every time when playback a saved work with 4 vertical smartphoneclips side by side

### ISSUE THREAD

**Issue by littlefico** [OpenShot/openshot-qt#3387]
checked the buffer preferences stated at issue #960 
EDIT: it may be, that some of the videos overlap with each other. so please take that into consideration.

**Describe the bug:**
Programme crashes every time when pressing the play button on my work. 
It is possible to export though.

**Steps to reproduce the behavior:**
Load your work and playback.

**Expected behavior:**
You see a Videoplayback.

**System Details:**
- OpenShot Version 2.5.1
- Operating System Win 10 32GB RAM (Intel Hades Canyon)

**Log Files:**
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/4495885/openshot-qt.log)

**Comment by SuslikV** [comment]
Is it crashes only at the beginning of the each clip not the end?

**Comment by littlefico** [comment]
to be clear, i dont speak about an exported clip but the preview in the programm openshot.
when i want to playback a video within the programm, openshot crashes instanly.

**Comment by SuslikV** [comment]
Where the _Timeline_'s cursor is positioned on the _Timeline_ when you trying to playback the video preview (at start of the clips, at middle or near the end)?

**Comment by littlefico** [comment]
Anywhere, does not matter.

Am Sonntag, 19. April 2020 schrieb SuslikV <notifications@github.com>:
> Where the Timeline's cursor is positioned on the Timeline when you trying
to playback the video preview (at start of the clips, at middle or near the
end)?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci3.googleusercontent.com/proxy/T3enzAxbG5sGBOgQszPbeIcSTGhHKUJ0CAJa52_FwPFe3MUgLpjTJ0ywmMmK3vx3zZNi83O4qJBaPOdoT4k6TW_sSogjttgJbF3eD3o2PM9l5BlNDetW6NxbrdZajcCnJhAHUTS7LqsEMAHLNL7FIh3hQtU-1AAKzMkhzCxz7SPo-h6ipwlKdBh9Fh5MnM4UqTMJPSzhEoFMb7sWIYuVVW2oCzibJSF_9lc4fdl8Rw=s0-d-e1-ft#https://github.com/notifications/beacon/ALDCKR4XUA2F54VCV3KMYM3RNMYPTA5CNFSM4MLFH6FKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOES5FEVI.gif>

**Comment by SuslikV** [comment]
Please, enable the "Debug" option inside the _Preferences_ of OpenShot and make new log-file with this debug option enabled. This will make more detailed log, maybe there will be additional info why OpenShot crashed.

**Comment by littlefico** [comment]
sorry for the late reply
ok, this is creepy. i switched users at my PC and with the new user it worked.
edit pending
