### ISSUE TITLE
Le son des fichiers importés grésille 

### ISSUE THREAD

**Issue by Quaigone** [OpenShot/openshot-qt#3388]
**Describe the bug**
son grésille

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Windows-10-10.0.18362
- Processor: AMD64 Family 21 Model 2 Stepping 0, AuthenticAMD
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['fr-FR', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1587099719-9e7e7415-26b7db94-x86_64.exe

**Log Files**
- http://logs.openshot.org/lfteppszesgyobpszk03hzeqf79zd9ga/openshot-qt.zip
- http://logs.openshot.org/lfteppszesgyobpszk03hzeqf79zd9ga/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Captures d’écran** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.
                
Bonjour,

Le problème est que lors de l'importation de fichiers, le son est remplacé par du grésillement. J'ai essayé plusieurs vidéos mais le problème est le même.

**Comment by SuslikV** [comment]
Is the recording is OK in other players?
If yes, try to change the Openshot's sampling rate to match the movie rate and PC settings: https://github.com/OpenShot/openshot-qt/issues/3116#issuecomment-563141265 (probably you need 48000Hz setting everywhere). But maybe you will end with nothing as in linked report...

**Comment by Quaigone** [comment]
Mes fichiers sont bons dans d'autres lecteurs. J'ai essayé de modifier plusieurs paramètres mais rien ne change. Pour le moment, je laisse tomber. Mais merci ;)

My files are good in other players. I tried to modify several parameters but nothing changes. For the moment, I give up. But thanks;)

**Comment by SuslikV** [comment]
So, the https://github.com/OpenShot/openshot-qt/issues/3116#issuecomment-616124576 didn't make any difference for you too?
