### ISSUE TITLE
Progress bar doesn't update while rendering animated title with no english blender version

### ISSUE THREAD

**Issue by injiniero** [OpenShot/openshot-qt#3389]
**Describe the bug:**
Rendering an animated title the progress bar doesn't update if blender is not the english version.

**Steps to reproduce the behavior:**
Render any animated title with a no english blender version

**Expected behavior:**
The progress bar should show the progress of the rendering process.

**System Details:**
- OpenShot Version: 2.5.1
- Operating System: Ubuntu 18.04

**Workaround**
Edit /usr/lib/python3/dist-packages/openshot_qt/windows/views/blender_listview.py file and change line 700:
```python
self.blender_frame_expression = re.compile(r"Fra:([0-9,]*).*Mem:(.*?) .*Sce:")
```
for this one:
```python
self.blender_frame_expression = re.compile(r"F??:([0-9,]*).*Mem:(.*?)")
```

**Comment by ferdnyc** [comment]
Wow, Blender internationalized their console logs!? Crazy.

I don't think that workaround will work in the general case. `F??` (which I'm guessing should be either `F..` or `F.*`, meaning an `F` followed by 2 characters, or an `F` followed by an indeterminate number of characters?) may be correct for _more_ languages, but if the output is in, say, Traditional Chinese, the localized text used to represent "Frame" in that script isn't likely to match `F..` either, and `Mem:` may become equally ineffective.

I wonder if there's a way we can just tell it to always output English strings on the console? If there is I'm not immediately seeing it.

**Comment by injiniero** [comment]
The solution could be not trying to catch the frame number but count output log lines. Frame number is the only one used actually, Memory is not used but caught.
And, you're right. My workaround works for blender in spanish: Frame = Fotograma (Fra -> Fot)
