### ISSUE TITLE
Openshot appears in 'Other' rather than 'Sound and Video' menu

### ISSUE THREAD

**Issue by Windsurfer01** [OpenShot/openshot-qt#339]
In Linux Mint 18 Cinnamon, Openshot appears in 'Other' rather than 'Sound and Video' menu.

**Comment by jonoomph** [comment]
Was this installed using the AppImage? PPA? Official repo?

**Comment by jonoomph** [comment]
Okay, I see where our AppImage does not specify a category with it's .desktop file. I've made a change to this, and you should be able to test using our next daily build to verify it fixes the problem.  

Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot. _It might take a couple hours for the latest version to appear._

**Comment by Windsurfer01** [comment]
Sorry - was away for a few days. It was using AppImage.

**Comment by Windsurfer01** [comment]
Work correctly now. Tested on Sept 17th AppImage.
