### ISSUE TITLE
Crackling/ missing audio near end of each audio clip

### ISSUE THREAD

**Issue by speedbooster** [OpenShot/openshot-qt#3391]
BISMILLAHIRRAHMANIRRAHEEM

Hi,
I think the bug has already been reported. I just downloaded OpenShot and the first attempt caused issue.

Audio in editor and exported is crackled near the end. (Files attached).
System screenshots attached in zip file, integrated audio.

[Files](https://www.MuhammadBilalKhan.com/Untitled_Project.zip)

**Comment by Justin-CB** [comment]
I've noticed that the ends of clips can have distorted audio as well.

**Comment by ctsdownloads** [comment]
Make sure under preferences, your audio settings are 2 channel stereo, and make note of the sample rate. In the project file bin, right click your video file, audio, then make sure the sample rate matches that of your source video's audio. If it's different, go back into your preferences, preview and change the sample rate to match your source video's audio sample rate.

You can also go into advanced view from Views, single left click the video/audio clip in the timeline. Scroll down to volume, double click on the 1.00 to the right of volume, change it to .85.
