### ISSUE TITLE
Opening preferences result crash

### ISSUE THREAD

**Issue by ghul01** [OpenShot/openshot-qt#3395]
**Describe the bug**
Opening preferences result crash. Deleting .openshot_qt folder and reinstalling won't fix it.

**Steps to reproduce the behavior:**
1. Start OpenShot and wait till it loads.
2. Click on 'Edit'
3. Click on Preferences
4. Main window closes

**Expected behavior**
A Setting window pop up.

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Windows-10-10.0.18362
- Processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1587538082-15c3efb7-26b7db94-x86_64.exe

**Log Files**
- http://logs.openshot.org/albqumzkrvcc21komgtwjuh0h11czxic/openshot-qt.zip
- http://logs.openshot.org/albqumzkrvcc21komgtwjuh0h11czxic/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by ghul01** [comment]
Also It often freezes while trying to navigate to a diferent section of the video.
Specs:
OS Name	Microsoft Windows 10 Education
Version	10.0.18362 Build 18362
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	DESKTOP-55TUBRD
System Manufacturer	Gigabyte Technology Co., Ltd.
System Model	B85M-DS3H-A
System Type	x64-based PC
System SKU	To be filled by O.E.M.
Processor	Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz, 3501 Mhz, 4 Core(s), 4 Logical Processor(s)
BIOS Version/Date	American Megatrends Inc. F1, 2015-01-19
SMBIOS Version	2.7
Embedded Controller Version	255.255
BIOS Mode	Legacy
BaseBoard Manufacturer	Gigabyte Technology Co., Ltd.
BaseBoard Product	B85M-DS3H-A
BaseBoard Version	x.x
Platform Role	Desktop
Secure Boot State	Unsupported
PCR7 Configuration	Binding Not Possible
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume3
Locale	Egyesült Államok
Hardware Abstraction Layer	Version = "10.0.18362.752"
User Name	DESKTOP-55TUBRD\Attila
Time Zone	Central Europe Daylight Time
Installed Physical Memory (RAM)	16.0 GB
Total Physical Memory	15.9 GB
Available Physical Memory	9.54 GB
Total Virtual Memory	23.2 GB
Available Virtual Memory	12.4 GB
Page File Space	7.25 GB
Page File	D:\pagefile.sys
Kernel DMA Protection	Off
Virtualization-based security	Running
Virtualization-based security Required Security Properties	
Virtualization-based security Available Security Properties	Base Virtualization Support, DMA Protection
Virtualization-based security Services Configured	
Virtualization-based security Services Running	
Device Encryption Support	Reasons for failed automatic device encryption: TPM is not usable, PCR7 binding is not supported, Hardware Security Test Interface failed and device is not Modern Standby, Un-allowed DMA capable bus/device(s) detected, TPM is not usable
A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by SuslikV** [comment]
What version of the Intel's GPU driver you are using?

Application crashes is in Quick Sync encoder test.
Try to exclude the crashed test from the list, (by modifying the `preferences.py` file) like in: https://github.com/OpenShot/openshot-qt/issues/3276#issuecomment-595052453

**Comment by ghul01** [comment]
GPU 0

	Intel(R) HD Graphics 4600

	Driver version:	20.19.15.4835
	Driver date:	2017-10-16
	DirectX version:	12 (FL 11.1)
	Physical location:	PCI bus 0, device 2, function 0

	Utilization	0%
	Dedicated GPU memory	0.0/128 MB
	Shared GPU memory	0.0/2.0 GB
	GPU Memory	0.0/2.1 GB
After update:
GPU 0

	Intel(R) HD Graphics 4600

	Driver version:	20.19.15.5126
	Driver date:	2020-01-21
	DirectX version:	12 (FL 11.1)
	Physical location:	PCI bus 0, device 2, function 0

	Utilization	0%
	Dedicated GPU memory	0.0/128 MB
	Shared GPU memory	0.0/2.0 GB
	GPU Memory	0.0/2.1 GB

Updating the driver wont solve the problem.
Also I checked in the BIOS that the GPU is enabled. OpenShot used to work on my machine so I tought this might be an update error. 
Editing the peferences worked well, thanks!

**Comment by SuslikV** [comment]
It's pre-DCH driver of Intel GPU, so, I think - no. Maybe you can disable Intel's video, and thus test should fail safely, but this doesn't change the things.
