### ISSUE TITLE
Application hangs/unresponsive when exporting MKV

### ISSUE THREAD

**Issue by mix3d** [OpenShot/openshot-qt#3397]
**Describe the bug**
Application hangs when trying to export MKV file. Source material is MKV

**Steps to reproduce the behavior:**
1. Create a new project. 
2. Add mkv source files
3. Export video using MKV as target, default settings. 
4. Application hangs, windows reports non responsive. A file is created, but no more than a split second of frame, even after waiting 20 minutes.

**Expected behavior**
Expect video to export normally. MP4 export worked as normal.

**System Details**
- OpenShot Version: 2.5.1
- libopenshot Version:  0.2.5
- Platform: Windows-10-10.0.17763
- Processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1587538082-15c3efb7-26b7db94-x86_64.exe

**Log Files**
- http://logs.openshot.org/606fqohlriko07iv3pu365xf0mgummvn/openshot-qt.zip
- http://logs.openshot.org/606fqohlriko07iv3pu365xf0mgummvn/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
![image](https://user-images.githubusercontent.com/1474137/80020316-a911e980-848d-11ea-87fc-84c1c21dfe52.png)

**Comment by SuslikV** [comment]
Export is working. You underestimate complexity of the AVC encoder ("av1"). If you need `mkv` output -just change preset back to `MP4 (h.264)` and at _Advanced tab_ of the _Export Video_ dialog type as _Video Settings>Video Format_ the `mkv` (instead of `mp4`). And better to use `23 crf` like settings instead of the bitrate.

**Comment by mix3d** [comment]
I'm not sure I follow your statement. It have a clear, reproducible bug with easy to follow steps. I'm glad there's a workaround, but that doesn't mean it's working.

**Comment by SuslikV** [comment]
You didn't wait for enough time to make the export complete its job. Is it much clearer now?

OpenShot's "Not responding" state in details is here - https://github.com/OpenShot/openshot-qt/issues/3351#issuecomment-609591736

**Comment by mix3d** [comment]
I exported as mp4 perfectly fine, no freezes, progress bar updated as expected. The MOMENT I click the export button with mkv setting, it hangs. Mp4 export time was roughly 20 minutes. I waited that long for mkv, nothing happened. Checked activity monitor, no disk activity, no process activity.

It's not "doing things in the background".

**Comment by mix3d** [comment]
This is my first video, all I did was take two 720p mkv input files, clip the beginnings and ends, put then end to end and export. No fancy features, no custom output settings.

**Comment by SuslikV** [comment]
You just need to wait... 24 hours or more to get first few seconds to be encoded (10 sec of static image takes for me about 15-20 minutes to encode by using this encoder). The encoder you've used is too demanding. The developer of the feature wasn't aware that the users will ignore small `av1` info near the BIG LETTERS of `MKV` , so you simply unaware that encoder (named as `av1` here) is way too demanding.

Better choose the target `MP4 (h.264)` profile and export to `.mp4` file.

**Comment by mix3d** [comment]
Then why enable a feature or option in the application if it's _effectively broken_?
________________________________

**Comment by SuslikV** [comment]
There is hope that feature will be useful for NASA PCs or maybe some other rocket science.

**Comment by eplebel** [comment]
i'm experiencing the same exact problem as reported by @mix3d, and agree that this is unambiguously a bug that needs to be fixed, thank you.

**Comment by mix3d** [comment]
Still an issue....

**Comment by RUDRAKSH13** [comment]
Yes I am also facing the same issue.
