### ISSUE TITLE
SVG title text lost at render, never recovers

### ISSUE THREAD

**Issue by c64whiz** [OpenShot/openshot-qt#3399]
I created a 15min video with several parts and a title SVG created by 
Openshot itself.  During development everything was fine.  However during rendering and after, the SVG file no longer shows text anywhere in the timeline or preview...even if a new project is created and the SVG is re-imported.  However, GIMP shows the SVG just fine as the text is fully visible.

I honestly don't know if you'll be able to reproduce it.  I did and have a video.  The SVG is also provided.

**Expected behavior:**
I expected the text of the title to show.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: OpenShot-v2.5.1-dev2-1587537989-15c3efb7-26b7db94-x86_64.AppImage (I understand this is daily build, but the problem seems rather basic.  I'm using the daily build because v2.5.1 crashed every time I attempted to bring an imported .mkv file to the timeline.  The daily build did not have this problem.)
- Operating System / Distro: Debian 10 fully updated

**Log Files:**
n/a

**Exception / Stacktrace:**
n/a

**Screenshots:** (Optional)
See attached files.

![pic1](https://user-images.githubusercontent.com/410595/80064007-fc1a8980-84eb-11ea-9bbe-9609f9fa45f7.png)
![pic2](https://user-images.githubusercontent.com/410595/80064018-00df3d80-84ec-11ea-8930-d601af32b7dd.png)

**Comment by SuslikV** [comment]
The best decision here is to forget about the AppImage and get native installation of the OpenShot. Developer may what to ask you to share the log-file from the session of OpenShot where the issue is surely present.
