### ISSUE TITLE
Openshot 2.1.0-10 Windows, problem with Cx_Freeze Python env export.

### ISSUE THREAD

**Issue by digination** [OpenShot/openshot-qt#340]
Hi, there is obviously a problem with the packaging of the windows versions of the application: Each time it is launched, cx_freeze pops an error window with a Nasty Stack Trace in it (see attached screenshot)

![sc](https://cloud.githubusercontent.com/assets/236661/18560191/d34de8fe-7b7a-11e6-89cb-a7ae27eccf82.jpg)

Regards,
Clément.

**Comment by jreynojustin** [comment]
OpenShot is now in Version 2.2 if you are still noticing issues in the latest version please re-open this issue letting us know.
