### ISSUE TITLE
How can I enable Waveform Display?

### ISSUE THREAD

**Issue by Giszmo** [OpenShot/openshot-qt#3403]
**Question:**

How do I enable waveform display? I see screenshots of the tracks showing the audio waveform but can't find how to switch it on.

**System Details:**
- OpenShot Version 2.5.1
- Operating System / Distro: Ubuntu

**Comment by SuslikV** [comment]
_Properties_ of the Audio only clip has property _Waveform_ that should be set to `Yes`

**Comment by Giszmo** [comment]
Thank you. I found the option. Only does it not show a waveform when set to "Yes". Trying with a .ogg track.

**Comment by SuslikV** [comment]
I can only assume that the file has no audio track or OpenShot not able to find it (like in https://github.com/OpenShot/openshot-qt/issues/3302 )

More info need about the media file itself (the _MediaInfo_ in _.txt_ format, if possible).

**Comment by Giszmo** [comment]
I see now the feature you were referring to works:
![feature](https://user-images.githubusercontent.com/96378/80419151-9725b180-88a6-11ea-8670-c6c9f5d2c804.png)

I thought there was also a way to see the waveform in the timeline:
![featureRequest](https://user-images.githubusercontent.com/96378/80419175-a0168300-88a6-11ea-8faa-69f3ff9511c7.png)

When editing a podcast with several speakers, they usually have pauses in between, so the wave form gives away quickly where to find the transitions. This is something audacity is better for but I need to also cut the video along with the audio.

**Comment by SuslikV** [comment]
In the _Timeline_ it is named as `Show Waveform` ( right-click menu over the clip that has audio _Display>Show Waveform_):

![OpenShot display sound wave in timeline](https://user-images.githubusercontent.com/19683044/80484049-c2b8a280-895f-11ea-8430-da56a6d06be1.png)

It looks like "spectrogram" of very low quality rather than "oscilloscope". Audacity is far better here too...

**Comment by Giszmo** [comment]
ok, cool, thanks. That's what I was looking for!
