### ISSUE TITLE
OpenShot-v2.5.1-x86_64.AppImage The program closes after importing the video file.

### ISSUE THREAD

**Issue by Piskuliki0723** [OpenShot/openshot-qt#3407]
The program itself closes after adding a video file to the scale
OS Deb
LOG

> '/home/user/Desktop/PO/OpenShot-v2.5.1-x86_64.AppImage' 
> Loaded modules from current directory: /tmp/.mount_a8unMu/usr/bin
>          app:INFO ------------------------------------------------
>          app:INFO             Sat Apr 25 10:20:17 2020            
>          app:INFO               Starting new session              
>          app:INFO ------------------------------------------------
>          app:INFO             OpenShot (version 2.5.1)            
>          app:INFO ------------------------------------------------
>          app:INFO openshot-qt version: 2.5.1
>          app:INFO libopenshot version: 0.2.5
>          app:INFO platform: Linux-5.4.0-4parrot1-amd64-x86_64-with-Parrot-4.8-rolling
>          app:INFO processor: 
>          app:INFO machine: x86_64
>          app:INFO python version: 3.4.3
>          app:INFO qt5 version: 5.2.1
>          app:INFO pyqt5 version: 5.2.1
>     language:INFO Qt Detected Languages: ['ru-RU']
>     language:INFO LANG Environment Variable: ru_RU.UTF-8
>     language:INFO LOCALE Environment Variable: 
>     language:INFO OpenShot Preference Language: Default
> project_data:INFO Setting default profile to HDV 720 24p
>          app:INFO Setting font to /tmp/.mount_a8unMu/usr/bin/images/fonts/Ubuntu-R.ttf
> logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
> QMainWindow::addDockWidget: invalid 'area' argument
>      ui_util:INFO Initializing UI for MainWindow
>  files_model:INFO updating files model.
> transition_model:INFO updating transitions model.
> effects_model:INFO updating effects model.
>      version:INFO Found current version: {"openshot_version": "2.5.1"}
>  main_window:INFO foundCurrentVersion: Found the latest version: 2.5.1
> properties_model:INFO updating clip properties model.
> transition_model:INFO updating transitions model.
>  files_model:INFO updating files model.
>  main_window:INFO InitCacheSettings
>  main_window:INFO cache-mode: CacheMemory
>  main_window:INFO cache-limit-mb: 3800
>  main_window:INFO Creating CacheMemory object with 3984588800 byte limit
> preview_thread:INFO QThread Start Method Invoked
>  main_window:ERROR Unhandled crash detected... will attempt to recover backup project: /home/user/.openshot_qt/backup.osp
> preview_thread:INFO initPlayer
>  main_window:INFO updateStatusChanged
>  main_window:INFO updateStatusChanged
>          app:INFO Process command-line arguments: ['/tmp/.mount_a8unMu/usr/bin/openshot-qt']
>  main_window:INFO recover_backup
> project_data:INFO Setting default profile to HDV 720 24p
> preview_thread:INFO refreshFrame
> preview_thread:INFO self.player.Position(): 1
> video_widget:INFO Load: Set video widget display aspect ratio to: 1.7777777910232544
> video_widget:INFO Set video widget pixel aspect ratio to: 1.0
>  main_window:INFO updateStatusChanged
> preview_thread:INFO onModeChanged
> properties_model:INFO Update item: 
> properties_model:INFO updating clip properties model.
>     timeline:INFO Adjusting max size of preview image: PyQt5.QtCore.QSize(724, 407)
> preview_thread:INFO refreshFrame
> preview_thread:INFO self.player.Position(): 1
> preview_thread:INFO refreshFrame
> preview_thread:INFO self.player.Position(): 1
> timeline_webview:WARNING TimelineWebView::eval_js() called before document ready event. Script queued: $('body').scope().SetTrackLabel('Дорожка %s');
> timeline_webview:WARNING TimelineWebView::eval_js() called before document ready event. Script queued: $('body').scope().LoadJson({"key": "", "partial": false, "type": "load", "old_values": {}, "value": {"import_path": "", "version": {"openshot-qt": "0.0.0", "libopenshot": "0.0.0"}, "markers": [], "width": 1280, "scale": 15, "fps": {"den": 1, "num": 24}, "profile": "HDV 720 24p", "settings": {}, "playhead_position": 0, "progress": [], "effects": [], "sample_rate": 44100, "layers": [{"y": 0, "number": 1000000, "id": "L1", "lock": false, "label": ""}, {"y": 0, "number": 2000000, "id": "L2", "lock": false, "label": ""}, {"y": 0, "number": 3000000, "id": "L3", "lock": false, "label": ""}, {"y": 0, "number": 4000000, "id": "L4", "lock": false, "label": ""}, {"y": 0, "number": 5000000, "id": "L5", "lock": false, "label": ""}], "id": "11S5GZG874", "clips": [], "tick_pixels": 100, "display_ratio": {"den": 9, "num": 16}, "files": [], "pixel_ratio": {"den": 1, "num": 1}, "channels": 2, "channel_layout": 3, "duration": 300, "height": 720, "export_path": ""}});
> timeline_webview:WARNING TimelineWebView::eval_js() called before document ready event. Script queued: $('body').scope().setScale(15, 0);
> timeline_webview:WARNING TimelineWebView::eval_js() called before document ready event. Script queued: $('body').scope().SetSnappingMode(1);
> timeline_webview:INFO Qt Found!
> timeline_webview:INFO $scope.Qt = true;
> timeline_webview:INFO SetThumbAddress: http://127.0.0.1:59999/thumbnails/
> timeline_webview:INFO SortItems
> timeline_webview:INFO UpdateLayerIndex
> timeline_webview:INFO UpdateLayerIndex
>  main_window:INFO Clear all thumbnails: /home/user/.openshot_qt/thumbnail
>  main_window:INFO Clear all animations: /home/user/.openshot_qt/blender
>  main_window:INFO Clear all titles: /home/user/.openshot_qt/title
> project_data:INFO Setting default profile to HDV 720 24p
> preview_thread:INFO refreshFrame
> preview_thread:INFO self.player.Position(): 1
> timeline_webview:INFO SortItems
> timeline_webview:INFO UpdateLayerIndex
> video_widget:INFO Load: Set video widget display aspect ratio to: 1.7777777910232544
> video_widget:INFO Set video widget pixel aspect ratio to: 1.0
>  main_window:INFO updateStatusChanged
>  main_window:INFO updateStatusChanged
>  main_window:INFO updateStatusChanged
>  files_model:INFO updating files model.
>  main_window:INFO New Project created.
> properties_model:INFO Update item: 
> properties_model:INFO updating clip properties model.
> project_data:INFO _set key: ['files'] values: {'has_audio': False, 'vcodec': 'h264', 'video_timebase': {'den': 15360, 'num': 1}, 'acodec': '', 'metadata': {'major_brand': 'isom', 'encoder': 'Lavf58.29.100', 'minor_version': '512', 'language': 'und', 'handler_name': 'VideoHandler', 'compatible_brands': 'isomiso2avc1mp41'}, 'has_video': True, 'width': 1280, 'interlaced_frame': False, 'fps': {'den': 47, 'num': 1440}, 'audio_bit_rate': 0, 'display_ratio': {'den': 9, 'num': 16}, 'audio_stream_index': -1, 'path': '/home/user/Видео/0.mp4', 'file_size': '954807', 'has_single_image': False, 'sample_rate': 0, 'id': 'V9QV91T3WJ', 'video_bit_rate': 609321, 'audio_timebase': {'den': 1, 'num': 1}, 'video_stream_index': 0, 'type': 'FFmpegReader', 'pixel_format': 0, 'media_type': 'video', 'duration': 1.600000023841858, 'pixel_ratio': {'den': 1, 'num': 1}, 'channels': 0, 'channel_layout': 4, 'video_length': '49', 'top_field_first': True, 'height': 720} add: True partial: False remove: False
> timeline_webview:INFO SortItems
> timeline_webview:INFO UpdateLayerIndex
>  files_model:INFO updating files model.
>  files_model:INFO updating files model.
>  main_window:INFO updateStatusChanged
>  files_model:INFO updating files model.
> project_data:INFO _set key: ['import_path'] values: /home/user/Видео add: False partial: False remove: False
>  main_window:INFO updateStatusChanged
>  main_window:INFO Imported media file /home/user/Видео/0.mp4
> files_treeview:INFO currentChanged
>      ui_util:INFO Initializing UI for Dialog
> add_to_timeline_model:INFO updating timeline model.
> add_to_timeline_model:INFO []
> add_to_timeline_model:INFO updating timeline model.
> add_to_timeline_model:INFO set files to [<classes.query.File object at 0x7fb4a4495320>]
> add_to_timeline_model:INFO [<classes.query.File object at 0x7fb4a4495320>]
> add_to_timeline_model:INFO updating timeline model.
> add_to_timeline_model:INFO [<classes.query.File object at 0x7fb4a4495320>]
> add_to_timeline:INFO accept
> project_data:INFO _set key: ['clips'] values: {'crop_width': {'Points': [{'co': {'X': 1.0, 'Y': 1.0}, 'interpolation': 2}]}, 'file_id': 'V9QV91T3WJ', 'has_audio': {'Points': [{'co': {'X': 1.0, 'Y': -1.0}, 'interpolation': 2}]}, 'reader': {'has_audio': False, 'vcodec': 'h264', 'video_timebase': {'den': 15360, 'num': 1}, 'acodec': '', 'metadata': {'major_brand': 'isom', 'encoder': 'Lavf58.29.100', 'minor_version': '512', 'language': 'und', 'handler_name': 'VideoHandler', 'compatible_brands': 'isomiso2avc1mp41'}, 'has_video': True, 'width': 1280, 'interlaced_frame': False, 'fps': {'den': 47, 'num': 1440}, 'audio_bit_rate': 0, 'display_ratio': {'den': 9, 'num': 16}, 'audio_stream_index': -1, 'path': '/home/user/Видео/0.mp4', 'file_size': '954807', 'has_single_image': False, 'sample_rate': 0, 'video_bit_rate': 609321, 'audio_timebase': {'den': 1, 'num': 1}, 'video_stream_index': 0, 'type': 'FFmpegReader', 'pixel_format': 0, 'duration': 1.600000023841858, 'pixel_ratio': {'den': 1, 'num': 1}, 'channels': 0, 'channel_layout': 4, 'video_length': '49', 'top_field_first': True, 'height': 720}, 'wave_color': {'red': {'Points': [{'handle_left': {'X': 0.5, 'Y': 1.0}, 'handle_type': 0, 'co': {'X': 1.0, 'Y': 0.0}, 'handle_right': {'X': 0.5, 'Y': 0.0}, 'interpolation': 0}]}, 'blue': {'Points': [{'handle_left': {'X': 0.5, 'Y': 1.0}, 'handle_type': 0, 'co': {'X': 1.0, 'Y': 255.0}, 'handle_right': {'X': 0.5, 'Y': 0.0}, 'interpolation': 0}]}, 'alpha': {'Points': [{'handle_left': {'X': 0.5, 'Y': 1.0}, 'handle_type': 0, 'co': {'X': 1.0, 'Y': 255.0}, 'handle_right': {'X': 0.5, 'Y': 0.0}, 'interpolation': 0}]}, 'green': {'Points': [{'handle_left': {'X': 0.5, 'Y': 1.0}, 'handle_type': 0, 'co': {'X': 1.0, 'Y': 123.0}, 'handle_right': {'X': 0.5, 'Y': 0.0}, 'interpolation': 0}]}}, 'perspective_c3_x': {'Points': [{'co': {'X': 1.0, 'Y': -1.0}, 'interpolation': 2}]}, 'crop_height': {'Points': [{'co': {'X': 1.0, 'Y': 1.0}, 'interpolation': 2}]}, 'mixing': 0, 'has_video': {'Points': [{'co': {'X': 1.0, 'Y': -1.0}, 'interpolation': 2}]}, 'perspective_c2_y': {'Points': [{'co': {'X': 1.0, 'Y': -1.0}, 'interpolation': 2}]}, 'channel_mapping': {'Points': [{'co': {'X': 1.0, 'Y': -1.0}, 'interpolation': 2}]}, 'end': 1.600000023841858, 'scale': 1, 'perspective_c2_x': {'Points': [{'co': {'X': 1.0, 'Y': -1.0}, 'interpolation': 2}]}, 'scale_x': {'Points': [{'co': {'X': 1.0, 'Y': 1.0}, 'interpolation': 2}]}, 'effects': [], 'crop_y': {'Points': [{'co': {'X': 1.0, 'Y': 0.0}, 'interpolation': 2}]}, 'waveform': False, 'shear_x': {'Points': [{'co': {'X': 1.0, 'Y': 0.0}, 'interpolation': 2}]}, 'shear_y': {'Points': [{'co': {'X': 1.0, 'Y': 0.0}, 'interpolation': 2}]}, 'perspective_c1_x': {'Points': [{'co': {'X': 1.0, 'Y': -1.0}, 'interpolation': 2}]}, 'time': {'Points': [{'co': {'X': 1.0, 'Y': 1.0}, 'interpolation': 2}]}, 'layer': 5000000, 'perspective_c3_y': {'Points': [{'co': {'X': 1.0, 'Y': -1.0}, 'interpolation': 2}]}, 'id': 'X4PK0RCMG5', 'location_y': {'Points': [{'co': {'X': 1.0, 'Y': 0.0}, 'interpolation': 2}]}, 'alpha': {'Points': [{'co': {'X': 1.0, 'Y': 1.0}, 'interpolation': 2}]}, 'display': 0, 'perspective_c1_y': {'Points': [{'co': {'X': 1.0, 'Y': -1.0}, 'interpolation': 2}]}, 'gravity': 4, 'anchor': 0, 'perspective_c4_y': {'Points': [{'co': {'X': 1.0, 'Y': -1.0}, 'interpolation': 2}]}, 'scale_y': {'Points': [{'co': {'X': 1.0, 'Y': 1.0}, 'interpolation': 2}]}, 'rotation': {'Points': [{'co': {'X': 1.0, 'Y': 0.0}, 'interpolation': 2}]}, 'duration': 1.600000023841858, 'channel_filter': {'Points': [{'co': {'X': 1.0, 'Y': -1.0}, 'interpolation': 2}]}, 'start': 0.0, 'title': '0.mp4', 'crop_x': {'Points': [{'co': {'X': 1.0, 'Y': 0.0}, 'interpolation': 2}]}, 'position': 0.0, 'volume': {'Points': [{'co': {'X': 1.0, 'Y': 1.0}, 'interpolation': 2}]}, 'perspective_c4_x': {'Points': [{'co': {'X': 1.0, 'Y': -1.0}, 'interpolation': 2}]}, 'location_x': {'Points': [{'co': {'X': 1.0, 'Y': 0.0}, 'interpolation': 2}]}} add: True partial: False remove: False
> timeline_webview:INFO SortItems
> timeline_webview:INFO UpdateLayerIndex
> Auto configuration failed
> 140414955543424:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libssl_conf.so): libssl_conf.so: cannot open shared object file: No such file or directory
> 140414955543424:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
> 140414955543424:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=ssl_conf, path=ssl_conf
> 140414955543424:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=ssl_conf
> QMutex: destroying locked mutex
>

**Comment by Piskuliki0723** [comment]
https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.5.1-dev2-1587624156-15c3efb7-26b7db94-x86_64.AppImage

There is no error in this version

**Comment by SuslikV** [comment]
Then it was fixed by:
https://github.com/OpenShot/openshot-qt/pull/3283
https://github.com/OpenShot/openshot-qt/pull/3304
