### ISSUE TITLE
Property Value Slide still active when moving Timeline slide

### ISSUE THREAD

**Issue by lobneroO** [OpenShot/openshot-qt#3410]
**Describe the bug:**
Editing a property (such as a track's volume) and then moving the slider in the Timeline will affect the property value (e.g. progressing in the timeline will increase the volume)

**Steps to reproduce the behavior:**
1. Select a track. 
2. Change the volume in the Properties section t

o 0.
3. Press enter to accept the change.
4. Move the slider in the Timeline section to the right
5. Check the volume property in the Properties section, it is >0

**Expected behavior:**
The volume property should have stayed the same

**System Details:**
- OpenShot Version 2.5.1 
- Windows 10

**Screenshots:** (Optional)
![OpenShotSliderBug](https://user-images.githubusercontent.com/17877050/80299473-ea0f4400-8794-11ea-8701-82be0b583741.gif)

**Comment by SuslikV** [comment]
Not a bug - it is feature of displaying values (animated) in the _Properties_ table in real-time.
Actually, there is even request to do so during playback of the _Video Preview_ (see https://github.com/OpenShot/openshot-qt/issues/3404 )

By modifying property value you actually made new keyframe (at current _Timeline_'s cursor position inside clip boundaries) with the default _Linear_ interpolation. OpenShot is not so simple to edit default properties - it always creates animations. There are few related requests:
https://github.com/OpenShot/openshot-qt/issues/2420
https://github.com/OpenShot/openshot-qt/issues/3383
