### ISSUE TITLE
NVidia GPU card not used with nvenc encoding

### ISSUE THREAD

**Issue by vadi2** [OpenShot/openshot-qt#3414]
**Describe the bug:**
It's my understanding that using an exporter with the `nvenc` tag would make use of my NVidia GPU, but it does not.

**Steps to reproduce the behavior:**
1. Export video
2. Select 'nvenc' target

**Expected behavior:**
GPU 100% and not CPU 100%.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 2.5.1
- Operating System / Distro: Ubuntu 19.10
- NVidia driver: 440.59

**Screenshots:** (Optional)

![Selection_567](https://user-images.githubusercontent.com/110988/80393973-829ae680-88b1-11ea-9ffe-9d4c37df7d4b.png)

**Comment by SuslikV** [comment]
With this card on board you may find better editor. Anyway OpenShot's log-file can has important info to your question, can you share the one?

**Comment by vadi2** [comment]
[openshot-qt.zip](https://github.com/OpenShot/openshot-qt/files/4541725/openshot-qt.zip)

**Comment by SuslikV** [comment]
Application can't get access to the "openshot.settings" file.

**Comment by Twenkid** [comment]
Hi all, a related case, on Win 7, OS 2.5.1, GF 750 Ti - the NVENC doesn't appear at all as a disabled option. I have CUDA 10.1 lib installed if that could be e problem.

![image](https://user-images.githubusercontent.com/23367640/80804289-5e931a00-8bbd-11ea-9d85-e96a8f9c2752.png)

**Comment by ferdnyc** [comment]
@vadi2 Wow, that is a serious piece of kit.

First thing you should check is the Preferences, make sure the max width and height for HW acceleration are high enough to permit 4K output. If the output profile frame size is larger than the configured max, HW encoding will be bypassed even if it's selected.

**Comment by ferdnyc** [comment]
@Twenkid Your issue is something completely different, I'm not immediately sure what's going on there. 

It'd be better to open a separate bug to track that issue, though. Your problem and @vadi2 's most likely aren't related.

**Comment by vadi2** [comment]
Yes it is those defaults, also the first three comboboxes have no other options within them:

![Selection_576](https://user-images.githubusercontent.com/110988/80855853-f720ad00-8c44-11ea-87d4-ee0961458f64.png)

**Comment by Twenkid** [comment]
The relation is in the inability to use the GPU. The preferences can't be adjusted in my case:

![image](https://user-images.githubusercontent.com/23367640/80860662-cdca4600-8c71-11ea-89e5-9d771b7d3b77.png)

**Comment by SuslikV** [comment]
@Twenkid During the _Preferences_ window loading, a new info appears in the log of OpenShot, there results of HW decoders tests are logged (if any), So, if you see something like:
```
 preferences:WARNING CheckPixel failed testing hardware decoding in preferences (i.e. wrong color found): 3-0
 preferences:WARNING CheckPixel failed testing hardware decoding in preferences (i.e. wrong color found): 3-1
 preferences:WARNING Exception trying to test hardware decoding in preferences (this is expected): 4-0
 preferences:WARNING Exception trying to test hardware decoding in preferences (this is expected): 4-1
 preferences:WARNING Exception trying to test hardware decoding in preferences (this is expected): 7-0
 preferences:WARNING Exception trying to test hardware decoding in preferences (this is expected): 7-1
```
then no test were success on your system, so you can't choose anything but CPU decoding.

The list of acceleration test/devices numbers in OpenShot's log:
https://github.com/OpenShot/libopenshot/blob/f1e5c9c8a2acfd738406c869d1d4bc512ca41e04/include/Settings.h#L80-L91

Currently NVIDIA decoder is not listed as supported on Windows for OpenShot:
https://github.com/OpenShot/openshot-qt/blob/e0d3776de53dc8b7d105b757e349f0e703f27155/src/windows/preferences.py#L294

As for the Device selection options:
https://github.com/OpenShot/openshot-qt/blob/e0d3776de53dc8b7d105b757e349f0e703f27155/src/windows/preferences.py#L321-L323

-----------------

This were decoders. As for encoders - I don't know where code is.

**Comment by ferdnyc** [comment]
@vadi2 Yeah, sorry, the max width/height thing was a red herring anyway. I had it in my head that they affected hardware _encoding_ too, but from looking at the code that doesn't seem to be the case. As the names of those settings imply, they're only be meaningful for hardware **de-**coding. So, that's not the issue.

One thing you might try is using the relatively-new `openshot-qt-cli.exe` tool (included in the OpenShot application folder since 2.5.0) to run OpenShot from a Windows `command.com` session.

The advantage to that is, you should be able to see any output produced during the encoding process, including console messages that may be printed by the FFmpeg libraries. Those aren't otherwise visible or available in any of the captured logs. Sometimes when there's a processing issue, including hardware encoder failures, it'll dump an error message to the console before falling back to software encoding.

To run OpenShot that way, just open a Command Prompt window, change to the directory where OpenShot is installed (probably `C:\Program Files\OpenShot Video Editor\`), and run `openshot-qt-cli.exe` to launch OpenShot with the console output visible. So:
```cmd
cd "C:\Program Files\OpenShot Video Editor"
openshot-qt-cli.exe
```

(You might have to increase the buffer length in the Command Prompt window first. IIRC the default is only ~ 300 lines? Not enough for noisy OpenShot output. Something like 2000 or 5000 lines is more realistic.)

**Comment by vadi2** [comment]
I'm on Ubuntu. Here's the [encoding log](https://ada-young.com/pastebin/zdpemdMg).

**Comment by MBB232** [comment]
> Currently NVIDIA decoder is not listed as supported on Windows for OpenShot:

Wait, so there *is* some hardware decoding supported on Windows? I thought I read on Reddit that it was not supported at all. (Why I did not bother to report it)

Like @Twenkid I saw the Intel QSV listed, but I thought *that* was a bug. It is showing up on my old laptop too,  which only has an Intel CPU, not an Intel GPU. Should it be seeing an old AMD/ATI GPU? (~10y old, OpenCL 1.3 or something). I thought ATI was not supported either? (Not really sure how to read your link)

On my new machine with both Intel and NVidia GPU are not seen either, except for that single QSV. 
I can not even get it to on the 'high-end GPU' from the Nvidia settings. 

@ferdnyc 
openshot-qt-cli.exe 
Would it matter to add that one to Nvidia, or is it running other processes in the background? (IRRC, Blender is seen by Nvidia when called from Openshot.

Also, is it documented somewhere yet? What does it do, can you use it to add files on a time/track with a script or something?
A google search gave me this:
https://blueprints.launchpad.net/openshot/+spec/command-line-interface-for-project-rendering

**Comment by vadi2** [comment]
Sorry to interrupt, but the issue isn't about Windows at all - please file a new report and discuss it there, thanks!

**Comment by ferdnyc** [comment]
> I'm on Ubuntu. 

My mistake, sorry. I'll take a look at that log.

**Comment by ferdnyc** [comment]
Ohhh, you're using the AppImage. Hardware accel is not supported at all in the AppImage builds, the drivers aren't accessible from the package mount. I'd recommend installing a distro package.

Ideally the AppImage builds wouldn't even have the hardware-accelerated elements included in the interface, but it only recently became clear there isn't going to be any way to make it work. Sorry about that.

**Comment by vadi2** [comment]
Alright, thanks.

**Comment by Twenkid** [comment]
> @Twenkid During the _Preferences_ window loading, a new info appears in the log of OpenShot, there results of HW decoders tests are logged (if any), So, if you see something like:
> 
> ```
>  preferences:WARNING CheckPixel failed testing hardware decoding in preferences (i.e. wrong color found): 3-0
>  preferences:WARNING CheckPixel failed testing hardware decoding in preferences (i.e. wrong color found): 3-1
>  preferences:WARNING Exception trying to test hardware decoding in preferences (this is expected): 4-0
>  preferences:WARNING Exception trying to test hardware decoding in preferences (this is expected): 4-1
>  preferences:WARNING Exception trying to test hardware decoding in preferences (this is expected): 7-0
>  preferences:WARNING Exception trying to test hardware decoding in preferences (this is expected): 7-1
> ```
> 
> then no test were success on your system, so you can't choose anything but CPU decoding.
> 

Thanks, yes, it reports errors like that.

```
preview_thread:INFO refreshFrame
preview_thread:INFO self.player.Position(): 1
preview_thread:INFO onModeChanged
preview_thread:INFO onModeChanged
preview_thread:INFO previewFrame: 23
preview_thread:INFO self.player.Position(): 23
preview_thread:INFO previewFrame: 32
preview_thread:INFO self.player.Position(): 32
preview_thread:INFO previewFrame: 37
preview_thread:INFO self.player.Position(): 37
preview_thread:INFO previewFrame: 32
preview_thread:INFO self.player.Position(): 32
     ui_util:INFO Initializing UI for dlgPreferences
Hardware decoding device number: 0
Hardware decoding device number: 0
 preferences:WARNING CheckPixel failed testing hardware decoding in preferences
(i.e. wrong color found): 3-0
Hardware decoding device number: 1
Hardware decoding device number: 1
 preferences:WARNING CheckPixel failed testing hardware decoding in preferences
(i.e. wrong color found): 3-1
Hardware decoding device number: 0
Hardware decoding device number: 0
[h264 @ 0000000004d42180] Invalid setup for format dxva2_vld: does not match the
 type of the provided device context.
 preferences:WARNING CheckPixel failed testing hardware decoding in preferences
(i.e. wrong color found): 4-0
Hardware decoding device number: 1
Hardware decoding device number: 1
[h264 @ 0000000004d43880] Invalid setup for format dxva2_vld: does not match the
 type of the provided device context.
 preferences:WARNING CheckPixel failed testing hardware decoding in preferences
(i.e. wrong color found): 4-1
Hardware decoding device number: 0
[AVHWDeviceContext @ 0000000017c8f3c0] Error initializing an MFX session: -3.
Hardware decoding device number: 0
[AVHWDeviceContext @ 0000000017c901c0] Error initializing an MFX session: -3.
 preferences:WARNING Exception trying to test hardware decoding in preferences (
this is expected): 7-0
Hardware decoding device number: 1
[AVHWDeviceContext @ 0000000017c90340] Error initializing an MFX session: -3.
Hardware decoding device number: 1
[AVHWDeviceContext @ 0000000017c90540] Error initializing an MFX session: -3.
 preferences:WARNING Exception trying to test hardware decoding in preferences (
this is expected): 7-1
  OpenType support missing for "Ubuntu", script 11
(...)
DirectWrite: CreateFontFaceFromHDC() failed (Unknown error 0x88985000.) for QFon
tDef(Family="Fixedsys", pointsize=10.5, pixelsize=15, styleHint=5, weight=50, st
retch=100, hintingPreference=0) LOGFONT("Fixedsys", lfWidth=0, lfHeight=-15) dpi
=96

```

**Comment by ferdnyc** [comment]
I've transferred @Twenkid's initial inquiry to new issue #3448, and will work on migrating the rest of the off-topic conversation there as well. Please continue that discussion in the _other_ issue, not here.

**Comment by ferdnyc** [comment]
Done. Closing this thread (as I think we've addressed the issue @vadi2 encountered, though unfortunately not very helpfully), and locking it to force the issue (so to speak).

**\#REDIRECT** #3448
