### ISSUE TITLE
Unable to open Title Editor

### ISSUE THREAD

**Issue by sunnyhy** [OpenShot/openshot-qt#3418]
**Describe the bug:**
Started using Openshot yesterday and it had no issues. Was using for a total of about 6 hours prior to this happening - specifically, editing subtitles to a video, background music etc. Basic stuff.

About an hour ago I tried to open the Title Editor window to change the content of some of my subtitles, but it was suddenly unable to open. When I right click the existing Title files and select Edit Title, nothing happens at all. But it's not lagging because other functions still work - even the Animated Title Editor works!! I've tried closing and reopening the project, relaunching the programme, and restarting the computer and the issue is still present. Keyboard shortcuts to open the Title editor also do not work.

**Steps to reproduce the behavior:**
1. Go to Project Files
2. Right click on any existing Title file
3. Select Edit Title
4. Error: nothing happens.

OR

1. Go to Title
2. Select Title or use keyboard shortcut Ctrl + T
3. Nothing happens.

**Expected behavior:**
Title editor opens in a new subwindow, allowing me to actually edit! the! title!

**System Details:**
- OpenShot Version [e.g. 2.5.1]: {{ log_context.openshot_qt_version }}
- Operating System: Windows 10

Would like to attach a recorded video of the screen but I can't.

**Comment by MBB232** [comment]
Did you use the advanced title editor (Inskcape) to create them, or only the build in  one?
Can you not create new titles, or does it only fail when trying to edit your own titles?

#3367  https://github.com/OpenShot/openshot-qt/issues/3367

**Comment by dracid** [comment]
Why is this closed? I also see this, I can neither duplicate nor edit the titles.
WIndows 10, Openshot 2.5.1, just casually adding a title to a video.
Tried deleting %user%/.openshot-qt folder, no change. 
Tried running as Administrator, also no change.

**Comment by JacksonRG** [comment]
@dracid Could you clear your log file in the openshot-qt folder, then try opening the title editor? If you then drop the log file into a github comment, I can take a look at it.
