### ISSUE TITLE
Disable track

### ISSUE THREAD

**Issue by PanderMusubi** [OpenShot/openshot-qt#342]
Please, offer an option to disable a complete track (not show the video and not play the audio). Use the same menu item in the menu to enable the track again. This would be similar to an open and closed eye on a layer in GIMP or Inkscape.

**Comment by JtLively** [comment]
On the left side, under the track name, there are options to mute sound and hide video. Or are you simply talking about a single button for both ?

**Comment by JtLively** [comment]
Whether you see those icons may depend on your color theme and version for OpenShot. 
If you have any other issues, please let us know.

**Comment by foobarbecue** [comment]
I can't see these buttons... where are they??? Openshot 2.4.1, Windows 10
![image](https://user-images.githubusercontent.com/854789/42074434-1d7d81d0-7b21-11e8-8c35-e2c690ec8129.png)

**Comment by foobarbecue** [comment]
hm, ok. So JtLively above is mistaken then, I presume.

**Comment by peanutbutterandcrackers** [comment]
@foobarbecue - Perhaps he was talking about the 1.x series. :)

We'll make this a priority (for `2.4.3` release, then, good sir!)

**Comment by sixtyfive** [comment]
I, too, saw these buttons in a couple of screenshots on the forums. How do these people already have the buttons available to them?

**Comment by peanutbutterandcrackers** [comment]
@sixtyfive - Those probably are screenshots of the 1.x series. Currently we are on the 2.x series which is a complete re-write of the application from the ground up and still needs ports of the features/effects from the 1.x series. Therefore it might be a while before we'll see the disable track buttons in OpenShot.

Those screenshots in the forums were of the 1.x series.

Hope that helps. :+1:

**Comment by RATATATO** [comment]
No. https://github.com/OpenShot/openshot-qt/issues/342#issuecomment-401250119 is 2.4.1 for ***Windows***.

Here is a screenshot of the current Windows version (2.4.3). The disable button is not found.

![tmp](https://user-images.githubusercontent.com/789330/47275591-95ad6600-d5eb-11e8-9940-9b0f41b0feeb.png)

I found a disable button from some screenshot on Google search.
- https://www.youtube.com/watch?v=5D6XEYjeYAA
- http://xeno999.blogspot.com/2012/11/openshot.html

So, It seems that Linux (and OS X ?) versions have new UI and a disable button, but Windows versions have had old UI yet.

**Comment by icolwell** [comment]
I'm running 2.4.4 on Ubuntu 16.04 and I don't see these buttons, were they added to 2.4.3 as @sixtyfive suggested?

**Comment by ferdnyc** [comment]
@icolwell As @peanutbutterandcrackers ' more recent comment indicated, direct track-wide control of that sort isn't currently available in OpenShot 2.x. Disable/enable track is still an open feature request (#784, specifically.)

Even though this report is older, marking as dup of #784 since that issue is still open.
