### ISSUE TITLE
Cannot start clip with KeyFrame

### ISSUE THREAD

**Issue by lobneroO** [OpenShot/openshot-qt#3425]
**Describe the bug:**
Setting a Key Frame as early as possible for a clip will not let the clip start with the Key Frame properties set

**Steps to reproduce the behavior:**
Add a clip. 
Move the slide before the clip and select the clip. 
Change a property to create a Key Frame and set the Curve to Constant.
Observe the Preview: The clip starts without any properties adjusted for one frame, then in the second frame the properties are taken into account.

**Expected behavior:**
The Clip starts with all settings of the Key Frame

**System Details:**
- OpenShot Version 2.5.1
- Windows 10

**Screenshots:** (Optional)
![OpenShotKeyFrameBug](https://user-images.githubusercontent.com/17877050/80720214-e5cc8900-8afc-11ea-9071-aa8762153e3b.gif)

**Comment by SuslikV** [comment]
Try to popup the _Video Preview_ window and resize it. Cached frames should update.

**Comment by ferdnyc** [comment]
@SuslikV 's suggestion should work. The issue most likely is that, because the playhead is positioned BEFORE the first frame of the clip, the preview for the first frame isn't refreshed even when the properties for the frame are modified.

If you position the playhead ON the first frame of the clip (which you can do by selecting it an using the Prev/Next Marker controls to jump to the left edge), and then adjust the properties, the preview should refresh automatically.

**Comment by lobneroO** [comment]
I have restarted the program, so there should not be any caching error. The problem persists. 

If I select the track and jump to the beginning via the markers, the property is already set to what I want, so that is not working either.

**Comment by lobneroO** [comment]
Just to ensure my property set up is not incorrect for what I want, here is a screenshot:
![grafik](https://user-images.githubusercontent.com/17877050/81074942-fceaec80-8ee9-11ea-8cf5-27f0357d1339.png)

**Comment by SuslikV** [comment]
> I have restarted the program...

Hmm, you know. I was talking about OpenShot own caching algorithms. It is not like some side issue. Simply, the math the OpenShot uses right now is not perfect. Project lacks specialists who can resolve this. So, I made assumption that you seeing the old frames (images cached by OpenShot itself). I have seen this many times in OpenShot. To verify is my assumption was right - is simple as single action - resize the video preview window (internal cache should update) and force its redrawing. The last is possible through the _Video Preview_ window "undocking" (making it float).

**Comment by SuslikV** [comment]
When (or if) the https://github.com/OpenShot/openshot-qt/pull/3084 will be integrated into OpenShot, it may help you to resolve the keyframe animation mistakes, if there any.

**Comment by ferdnyc** [comment]
> Just to ensure my property set up is not incorrect for what I want, here is a screenshot:

It's hard to say, not really knowing what you want. :laughing: The GIF you included originally doesn't really help illustrate the problem I'm afraid. For those of us who don't know what the video _should_ look like at any of those points, there's nothing obviously wrong with what's shown there.

But the keyframe settings look to be set up correctly to show a zoomed in portion of the video, offset to focus on one section — the lower-right part of the frame, looks like?

First question: Do you have additional keyframe points set for those properties at any later positions on that clip? Interactions with subsequent keyframes can be tricky at times, but if you've only set the values at the first frame of the clip then that shouldn't be an issue.

The only other thing I notice is that the clip in question doesn't start from the beginning of the video. So it's possible there's some kind of decoding issue or frame ordering problem behind this. Especially if the video was shot live and encoded on-the-fly, starting from any one particular frame of an encoded stream can sometimes have unexpected results.

One thing you could test is whether you still see the same issue even after shifting the start point (for the video within the clip, not where the clip is placed on the track) forwards or backwards a frame or two.

**Comment by ferdnyc** [comment]
Oh, last but not least, another thing to check: The frame rate for the source video, vs. the frame rate of the project profile selected for that timeline. Are they the same, or different?

**Comment by lobneroO** [comment]
> To verify is my assumption was right - is simple as single action - resize the video preview window (internal cache should update) and force its redrawing. The last is possible through the Video Preview window "undocking" (making it float).

Neither works, I get the same result.

> The GIF you included originally doesn't really help illustrate the problem I'm afraid. For those of us who don't know what the video should look like at any of those points, there's nothing obviously wrong with what's shown there.

Well, the first clip is camera 1 (only the drummer), then it changes to camera 2 with view of the whole stage and then it zooms into the right side of the stage. That part where you can see the whole stage shouldn't be there, that is the original footage, but I want to have it zoomed into the lower right corner immedeately.

> First question: Do you have additional keyframe points set for those properties at any later positions on that clip? Interactions with subsequent keyframes can be tricky at times, but if you've only set the values at the first frame of the clip then that shouldn't be an issue.

Yes, I change the position to the lower left later on. I have removed the later keyframe, but the issue persists.

> One thing you could test is whether you still see the same issue even after shifting the start point (for the video within the clip, not where the clip is placed on the track) forwards or backwards a frame or two.

I'm not sure how I can do that. There is a Start and End property, but I assume these are for where the clip is placed in the video. I have dragged the left side of the clip to the left (but I'm not sure if this adds the original footage or stretches the clip) and added a new keyframe to the front (the slide was slightly in front of the clip), and that seems to work
