### ISSUE TITLE
Set properties using natural units

### ISSUE THREAD

**Issue by ronisaacson** [OpenShot/openshot-qt#3426]
In the properties panel, most of the properties are decimal numbers. It would be helpful to view/edit these using more natural units that make sense for each property.

For example:

- Time-based properties (Position, Start, End, Duration): timecodes (hh:mm:ss:frame) would make much more sense than decimal seconds, and would make it easier to relate these values to the timeline view.
- Size and position properties (Location, Position, Scale, Crop, etc.): these could use pixels instead of just percentages.

**Comment by ferdnyc** [comment]
The time value issue is a fair point, I agree that could be better.

See https://github.com/OpenShot/openshot-qt/issues/1840#issuecomment-422181302 for an explanation of why frame positioning/dimension values AREN'T equivalent to pixel measurements, though, and why expressing them in concrete units like pixels would be misleading to the user.

Location and scale values are generally measured in units of one frame's length in the involved dimension. In other words, if you move something `-0.5` in the X dimension, you're moving it to the left a distance of half the width of the output frame. (Which isn't a fixed value until the video is exported.)

**Comment by ferdnyc** [comment]
One reason we don't convert those measurements to pixel units is, there's no guarantee that the exported project will have everything placed to the exact pixel. 

Sure, we _could_ convert `0.36` for a certain border width into `275px`. But the actual border might end up being `274px`, `276px`, or even `280px` — which isn't a bug. (To say nothing of it actually being `550px` when the user exports with a different profile.)

But if we **show** `275px` and the border's not EXACTLY 275 pixels, then we'll get bug reports that our non-pixel-accurate size values aren't being exported at exactly the number of pixels shown in the Properties list.

**Comment by ronisaacson** [comment]
That's totally understandable, but I think it could be done in a DWIMy way. One approach would be to enter/display the values using pixel dimensions (based on either the project profile or source video dimensions), but store them as percentages to use when doing the final rendering.

I had a bunch of different clips that I put in different tracks and wanted to arrange them in a grid to play at the same time. Using the numeric properties, I had a hard time getting them all cropped to the same size and positioned in a perfect grid. I just couldn't get precise enough. Eventually I gave up and pre-cropped the clips in a different tool so they were all the same size, and then using center gravity it was much easier to arrange the grid.

You could probably do this in OpenShot with a calculator, by figuring out how much of the source video to trim and converting that to a percentage based on the profile dimensions. But much like the timecodes, it's just too much work.

**Comment by ronisaacson** [comment]
Incidentally, I thought of another improvement for time entry, and that's making the Duration property editable (automatically recompute the end time). I hate grouping unrelated tasks together, but these all fall under the category of "stop making me alt-tab to the calculator when editing videos." :-)

Would you prefer I close this issue and open separate enhancements?
