### ISSUE TITLE
HDV Video Pixel Ratio 4:3 is ignored and requires manually setting Scale: Stretch

### ISSUE THREAD

**Issue by Twenkid** [OpenShot/openshot-qt#3429]
The pixel ratio of HDV videos 4:3 (1440x1080, displayed as 1920x1080) is ignored and the video is letterboxed. For proper aspect ratio in the editor and the output it requires to set manually SCALE to: Stretch (instead of the default "Best Fit") for all clips, one by one.  
OS 2.5.1, Win7.

Could the ratio be read automatically or add a Feature:

* Set an option for "Scale" which is applied as "Default", thus all following clips to stretch automatically. 

* Apply options on selection (to all selected clips).

**Comment by ferdnyc** [comment]
Duplicate of #1774, #3117
