### ISSUE TITLE
Horizontal export resolution limited to 3000px by GUI design only.

### ISSUE THREAD

**Issue by Ghostbird** [OpenShot/openshot-qt#343]
## To reproduce
1. Go to Edit » Preferences
2. Go to tab Profiles
3. Click Manage Profiles
4. Click the plus sign to create a new profile.
5. Click the first textbox after Size:
6. Enter a value in excess of 3000
7. Remove focus on the textbox by clicking elsewhere.
   Observe: The value is reduced to 3000
### Further observations

I manually edited the configuration file to get a profile that exports 3840×2160p @ 30fps. When I open OpenShot and export video, this profile works perfectly well. There seems to be no reason to limit the horizontal size to 3000px.

Once I have a profile with this size, I can create a copy in the Profile Manager, and as long as I never trigger the validation of the >3000px value in the Size textbox, I can change framerate, etc. without issue. It really seems that the only cause for this bug is a too restrictive validation routine that's only called when the Size textbox loses focus.
### Not tested

The same issue may occur when you try to enter a vertical size greater than 3000px. However I haven't tested this.
### Why this should be fixed

UHD (computer 4K) is a becoming a more and more common size for media. More and more people will be put off when they find out that OpenShot doesn't support UHD exports.
It's even stupider because it clearly does, it's just a GUI error that prevents it from working for the average user.
## Further recommendation

Go the extra mile, and provide UHD (and cinema 4K) profiles by default in OpenShot.

**Comment by DylanC** [comment]
@Ghostbird - Good idea. I'll check if the latest version supports this.

**Comment by Ghostbird** [comment]
Ah, terribly sorry for this, but I now realise that I was still running the old Openshot version 1.4.3 from the Debian repositories. I installed version 2.4.0 from http://openshot.org and there the "Manage Profiles" option is not available, but UHD and 4K profiles are included by default.

My apologies for wasting your time.
