### ISSUE TITLE
launch-win.bat doesn't work if you call it from a cmd/powershell prompt that's not in the OpenShot install directory.

### ISSUE THREAD

**Issue by corbob** [OpenShot/openshot-qt#3431]
**Describe the bug:**
When launching the `launch-win.bat` file from a terminal, it should launch OpenShot as expected.

**Steps to reproduce the behavior:**
1. open `cmd` or `powershell` terminal
2. launch `C:\Program Files\OpenShot Video Editor\launch-win.bat`
3. Receive error at the end: `'openshot-qt.exe' is not recognized as an internal or external command, operable program or batch file.`
4. There is also the side effect that the terminal window does not close if you launch it by double-clicking the file...

**Expected behavior:**
OpenShot should open regardless of where you launch it from.
Terminal window should close when OpenShot launches.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 2.5.1
- Operating System / Distro: Windows 10

**Comment by ferdnyc** [comment]
@corbob 
Hmm. Is `launch-win.bat` actually _used_ for anything, or is it just a complicated way to start OpenShot in a badly-configured environment?

Unless it's actually a necessary part of the implementation for some OpenShot function (the Start menu launcher, maybe?), perhaps the simplest fix is to just dump `launch-win.bat`?

What's the advantage (or expected advantage) of using that script, rather that running `openshot-qt.exe` directly? (I'm honestly asking — I'm not a regular user of Windows, so mostly I'm working off half-remembered details from months ago. And a few educated guesses.)

**Comment by corbob** [comment]
@ferdnyc yeah, I'm thinking you're right. This came up for me after installing it through Chocolatey and my Start menu/search being broken (one of the perils of being on fast ring insider builds of Windows 🤷 ), I found the launch-win file and thought that was the designated way of launching it. It looks though like this is more of a way to launch it when you need to troubleshoot something, and as such not a common way to launch it.

I also looked closer at the launch script and saw come references to `%cd%` that when I replace with `%~dp0` it breaks in weird way **only** when launched from cmd/powershell.

As opposed to try and fix something that appears to just be my not launching it properly I'll just close this issue and the corresponding PR.

**Comment by ferdnyc** [comment]
@corbob \*nod\* I have a feeling `launch-win.bat` is a leftover from the OpenShot-on-Windows development days, and is how you'd launch OpenShot from a local clone of the git repo. Might even still be useful for _that_. But in the interim our Windows packaging has grown in complexity, so `launch-win.bat` isn't merely unnecessary, it's no longer usable with the _packaged_ OpenShot we distribute via the installers.

Which means we should probably stop causing needless confusion by including it in the installer packages. I'll see if I can get it out of there safely.
