### ISSUE TITLE
Program closes unexpectedly when attempting to scroll down video clip properties

### ISSUE THREAD

**Issue by Nodrog106** [OpenShot/openshot-qt#3433]
**Describe the bug**
Program closes unexpectedly

**Steps to reproduce the behavior:**
Load video clip
Open Properties for it
try to scroll or click downwards past lowest visible property

**Expected behavior**
I expected it to sroll down
Instead it closed the program
Every time I tried

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Windows-10-10.0.18362
- Processor: AMD64 Family 21 Model 2 Stepping 0, AuthenticAMD
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-GB', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1588204308-15c3efb7-26b7db94-x86_64.exe

**Log Files**
- http://logs.openshot.org/movzwpb2wpnljlty4a4orgn8s547vlgp/openshot-qt.zip
- http://logs.openshot.org/movzwpb2wpnljlty4a4orgn8s547vlgp/libopenshot.zip

**Exception / Stacktrace**
```_C_specific_handler            7ffc04577fb0
_chkstk                        7ffc064a10b0
RtlRaiseException              7ffc06469e70
KiUserExceptionDispatcher      7ffc0649fe10
ZNQWidget::mapTo::QPoint 6b6e100
ZNQApplication::qt_metacall::QMetaObject::Call 6b53a20
ZNQWidgetPrivate::repaint_sys::QRegion 6b55aa0
ZNQWidgetPrivate::repaint_sys::QRegion 6b55aa0
ZNQWidgetPrivate::repaint_sys::QRegion 6b55aa0
ZNQWidgetPrivate::syncBackingStore 6b6d720
ZNQWidget::event::QEvent      6b84f90
ZNQDockWidget::event::QEvent 6c4ff30
???
ZNQApplicationPrivate::notify_helper::QObject::QEvent 6b475d0
ZNQApplication::notify::QObject::QEvent 6b4fc40
???
ZNQCoreApplication::notifyInternal::EP::QObject::QEvent 668efff0
ZNQCoreApplicationPrivate::sendPostedEvents::QObject::QThreadData 668f5fd0
qt_plugin_instance             6dd36c10
ZNQEventDispatcherWin::Private::sendTimerEvent 669453f0
CallWindowProcW                7ffc05dc5850
DispatchMessageW               7ffc05dc5410
ZNQEventDispatcherWin::processEventsE::QFlags::QEventLoop::ProcessEventsFlag 66944980
qt_plugin_instance             6dd36c10
ZNQEventLoop::exec::QFlags::ProcessEventsFlag 668eed70
ZNQCoreApplication::exec    668f6e00
???
PyMethodDef_RawFastCallKeywords 624a7950
PyEval_SliceIndex              623dc1e0
PyEval_EvalFrameDefault        623ddb50
PyFunction_FastCallKeywords    624a80e0
PyEval_SliceIndex              623dc1e0
PyEval_EvalFrameDefault        623ddb50
PyFunction_FastCallKeywords    624a80e0
PyEval_SliceIndex              623dc1e0
PyEval_EvalFrameDefault        623ddb50
PyEval_EvalCodeWithName        623dc520
PyEval_EvalCode                623287f0
PyBuiltin_Init                 62328aa0
PyMethodDef_RawFastCallKeywords 624a7950
PyEval_SliceIndex              623dc1e0
PyEval_EvalFrameDefault        623ddb50
PyFunction_FastCallKeywords    624a80e0
PyEval_SliceIndex              623dc1e0
PyEval_EvalFrameDefault        623ddb50
PyFunction_FastCallDict        624a8a50
???
???
???
BaseThreadInitThunk            7ffc...

**Comment by SuslikV** [comment]
Similar to: https://github.com/OpenShot/openshot-qt/issues/3352

1. Are you sure that you can reproduce this in any time and with any project file?
2. What happens if you switch _Default Theme_ to the "No Theme" in preferences of OpenShot?

**Comment by Nodrog106** [comment]
Thank you!​

 

Switching from Humanity Dark Theme to No Theme fixed it.

 


Best wishes
Gordon


 
 

Sent: Saturday, May 02, 2020 at 8:17 AM
