### ISSUE TITLE
applying blur effect causes crash

### ISSUE THREAD

**Issue by pdvigne** [OpenShot/openshot-qt#3434]
**Describe the bug:**
my clip has a normal, perfect audio, but if I apply a blur effect over the clip,  the result is a crash. If I remove the effect,  it turns normal again. The same with wave effect

**Steps to reproduce the behavior:**
1. Go to 'effects'
2. Click on 'blur'
3. Scroll down to 'clip on timeline'

**Expected behavior:**
expect that the video, and audio, flows normally, not crackle

**System Details:**
- OpenShot Version [e.g. 2.5.1]: {{ log_context.openshot_qt_version }}
- Operating System / Windows 10

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.
Log files can be found in your HOME/.openshot_qt/ folder. Please compress or zip
the log files (as they can become quite large).

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please
attach a small snippet of the exception here, but please keep it as small as
possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them here, dragging-and-dropping into this form, or clicking below and loading
images saved to your computer. All images are public, so please don't post screenshots
containing personal information. Please refer to this video https://youtu.be/xO7XzoKHhcc

**Comment by ferdnyc** [comment]
@pdvigne There isn't a lot to go on in your report currently, it'd be really helpful if you could attach log files from immediately after OpenShot crashes. 

That will let us see any error output the crash may have produced, and it'll also give us details about the format of your clips, in case the issue only occurrs with certain file types.

**Comment by pdvigne** [comment]
There's no longer necessary to solve this issue.
Thanks
