### ISSUE TITLE
Exported video freeze many seconds before the end

### ISSUE THREAD

**Issue by Merher83** [OpenShot/openshot-qt#3437]
** Describe the bug **
The exported video freezes 10 seconds before the end (but in the OpenShot editor everything seems OK)

** Steps to reproduce the behavior: **
1) Open OpenShot and create a new project

2) Add a short M2TS video (in my case: a 2-minute video encoded in h264 1920x1080 @ 50 frames / second)

3) Put this video on a track

4) In order to speed up its reading speed, right click on the sequence, select "Time", "Fast", "Forward" and "2x".
(As expected, the length of the video is halved. At this point, you can play the project to check it but you won't notice any problems).

5) Then click on "Export video" and select the following parameters for export:
- Profile: all formats
- Destination: CPU MP4 (h264)
- Video profile: 1024x576 16: 9 PAL (1024x576)
- Medium quality
Finally, click on the "Export video" button to generate the MP4 file.

** Expected behaviour **

Once the video export is complete, play the MP4 file generated with the player of your choice: you will notice that the exported video freezes 10 seconds before the end.
THIS IS THE PROBLEM !!!

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Windows-10-10.0.18362
- Processor: Intel64 Family 6 Model 26 Stepping 5, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['fr-FR', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1588204308-15c3efb7-26b7db94-x86_64.exe

**Log Files**
- http://logs.openshot.org/l6f86m5rslm81g0l5iogvhflptnrxvrs/openshot-qt.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Captures d’écran** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by SuslikV** [comment]
It seems to be similar to: https://github.com/OpenShot/openshot-qt/issues/2435

**Comment by Merher83** [comment]
Perhaps, but I would like to point out that if I export this same video at its normal speed, that is to say without increasing it by 2, the MP4 file obtained is correct.
So in my case, this export problem is related to having increased the video playback speed.
