### ISSUE TITLE
Jerky preview on a fast desktop machine.

### ISSUE THREAD

**Issue by stolk** [OpenShot/openshot-qt#344]
When I try to preview a 1280x720 video, it is very jerky, and keeps stuttering.
This did not happen with the old OpenShot v1.4.3 but does happen with the 2.1.0 version.

I encode my video files from PNG with:

```
/usr/bin/ffmpeg  -start_number 1 -i ./%04d.png   -vframes 400  -vcodec libx264 -vf fps=30 -crf 18  skull.mp4
```

My OpenShot project setting is 1280x720/30, and the video is 1280x720/30 as well.

I thought maybe it was related to the type of video file, so I tried .ogv instead, but that one gives even worse results, as the 30fps file is read as 24fps by OpenShot, and truncated as well. After that, I tried a motion-jpeg instead, to rule out encoding issues. The mjpeg stutters as well, when previewing in OpenShot.

Are there any ffmpeg options I can use to make the video easier to digest by OpenShot?

System specs:

```
Ubuntu 16.04.1 LTS
Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
nVidia GTX 750Ti
Running from SSD drives, no spinning disks present in my computer.
```

Is there a player I can use to see if the jerkiness originates from libmlt2 ?

**Comment by kpouget** [comment]
same for me, on archlinux, the video preview, and hence openshot itself, are unusable. It was working well with 1.4

**Comment by stolk** [comment]
Oh, and to rule out a libmlt2 issue, I tried 'shortcut' which is supposedly also based on libmlt2, and that one plays my video files fluently. So it seems to be a OpenShot specific issue, not MLT?

**Comment by NicoPy** [comment]
I get the same problem. Video playback is unusable. However, CPU and disk activity is very low. Globaly, user interface is responsive but everything related to video is very slow. Even video export is awfully slow.
What can I do to help fix this behaviour ?

**Comment by PanderMusubi** [comment]
For the rendered quality, see https://github.com/OpenShot/libopenshot/issues/37

**Comment by Windsurfer01** [comment]
Kdenlive produces output correctly, so it is probably not an ffmpeg issue. I am using Linux Mint 18, with the default ffmpeg. I do not know what the Appimage uses.

**Comment by DylanC** [comment]
@stolk - Closing due to issue verified against a much older version. Please log a new issue if problem still exists in 2.3.4. Thanks.
