### ISSUE TITLE
Speed up feature timeline is different after export

### ISSUE THREAD

**Issue by Inateno** [OpenShot/openshot-qt#3440]
Hello,
I'm new to this soft, I searched in the issues and found some bugs related to speedup but not that one so I thought it's good to report it.

**Description:**
I'm doing timelaps video as I was used to do with a "big known not-free/open software", so far so good from what the timeline says.

I "just" apply a first 16x to start with, because I need to add annotations/voice-over and/or speeding up some other sequences, so I just thought starting with a 16x to try this new software.

Exporting this take hours, sounds normal.

Timeline video is 15.34 seconds.
Exported video 15.34 seconds.

Nice.

But then I check the video with VLC, and at some points (some are more obvious than others), there are seconds that completely disappear.
I thought it was my fault so I go back in the soft, checking on the timeline.

So here is a screenshot that easily show what's going wrong there.
![image](https://user-images.githubusercontent.com/1068709/80908909-13474b80-8d24-11ea-87d9-94afc4436695.png)

If I try to find the sequence I actually see in VLC at 9.10 in OpenShot and I can find it at 8.45.

Weird.

It could be "fine", if the exported video wasn't removing minutes of sequences that ends with a "big gap" and also something I can't annotate.

On my screenshot, it's impossible for me to find (in the exported video) what you see in OpenShot at 9.10, this completely vanished and ~40sec of the sequence "2016_1120_163825_010.MOV" that can't be found in the export (and it's actually maybe most of the important stuff lol).

I saw an other issue about timelapse and you guys says to use other software to do pre-stuff, like cutting, speeding up etc.
I'm gonna give a try to Avidemux, but it's to bad to offer this feature and it doesn't works properly.

**System Details:**
- OpenShot Version 2.5.1 (libopenshot 0.2.5)
- Win10 Pro N

Keep up!
I would enjoy so much the ability to get rid of this big closed software, and I prefer not to use many soft to do "one simple thing", but I know how tricky it can be sometimes.

**Comment by SuslikV** [comment]
If input movie has fps that is different from the current fps of OpenShot's Preview Profile then this clip will be adjusted first (60fps video will became 30fps) and only then any other processing will start.

**Comment by Inateno** [comment]
Oh I see, I exported as 1080p 60 fps, let me try with a 30fps (not sure but I think the camera is filming in 30).

**Comment by Inateno** [comment]
Ok so using 30fps in export solved my issue, looks like I don't lost any sequences.
Would be nice to add a warning if the export framerate is different from the input source (or the lowest one as some can be 60 and some other 30).

I'm receiving a GoPro this week I'll try with a 60 (and more) FPS input to see how it goes.
