### ISSUE TITLE
Is this a problem?

### ISSUE THREAD

**Issue by teijkihtjwkethew** [OpenShot/openshot-qt#3449]
I was working on a video and saved the project for completion later, but when I opened (the project) it didn't work

**Comment by ferdnyc** [comment]
Well, it doesn't sound _ideal_, but if you'd like any advice on how to proceed you're going to have to give us more to go on so we can understand the issue I'm afraid.

The best place to start would be by filling out the [bug report template](https://github.com/OpenShot/openshot-qt/issues/new?assignees=&labels=%3Abeetle%3A+bug&template=bug-report.md&title=Give+your+bug+report+a+descriptive+title) and providing as much information as possible about what you did, what did or didn't happen, what you _expected_ would happen instead, and the exact text of any errors or popup messages OpenShot displayed.
