### ISSUE TITLE
Video export does not work

### ISSUE THREAD

**Issue by NicoPy** [OpenShot/openshot-qt#345]
When I try to export a video, OpenShot ends in a non responsive state. I have to kill it.
The export looks good at the beginning. CPU is about 100% busy (I7 Quad core hyper-threading). After a while, CPU utilisation falls down to about 45% and user interface is non responsive. 

Windows10x64
OpenShot 2.1.0 x64

**Comment by NicoPy** [comment]
I realised that if I don't kill OpenShot, the export process continues but very slowly.

**Comment by firew4lker** [comment]
I had the same issue on ArchLinux. It seems to be ok now.

**Comment by hollowdoor** [comment]
I don't know if my situation is the same, but I get 100% cpu during export.  I have a duel core, and my computer is old so my whole computer crashes. Both cores rise to a 100%, and stay there until my computer crashes.

I'm using Ubuntu, and OpenShot 1.2.0.

**Comment by hollowdoor** [comment]
This is still happening. But now with a quad core with 10.8GB memory with openshot 2.2. I'm still using Ubuntu.

**Comment by DylanC** [comment]
@NicoPy - Closing due to OpenShot version being much older. If problem still exists please log a new issue.

**Comment by hollowdoor** [comment]
Just fyi I can export small videos for now. The export sill runs all four cores to 100%. It appears to have improved though. I'm using the latest stable openshot. I've been told that rendering video at high cpu usage can't be helped. Is that true? Blender also renders at high cpu usage so maybe that's true.

**Comment by laulavasydan** [comment]
Why do i get this text in exporting video????

"This application is requested  the runtime to terminate it in an  unusalway."  ???

my video is about 3min 40 sec....   i tryed my 2 computers another just shut porgram down cracks? etc. this one gives that text after renderin 61.2%

<img width="450" alt="KUVAKAAPPAUS" src="https://user-images.githubusercontent.com/48855739/54864891-28525c80-4d66-11e9-876a-2cf0b6c69e14.PNG">
