### ISSUE TITLE
Pizza Hut address

### ISSUE THREAD

**Issue by TheDude53** [OpenShot/openshot-qt#3450]
Has anybody else noticed that the address at the bottom of the [OpenShot website ](https://www.openshot.org/)is a Pizza Hut? I haven't seen any other mention of it in a issue or on Google.

**Comment by ferdnyc** [comment]
According to Google Maps, it also houses, and I think this is far more to the point;

![image](https://user-images.githubusercontent.com/538020/81025812-f014bd00-8e45-11ea-8a28-4758518d5031.png)

(IOW, it's just a mailbox address where the company can receive documents, which is a requirement when incorporating a business in many states.)

**Comment by ferdnyc** [comment]
Though if you wanted to drop by for a visit, I'm sure @jonoomph could arrange a tour. Of the PostNet. :wink:

**Comment by ferdnyc** [comment]
That sandwich place next door is called "Which Wich", which (AAGH!) is a name that made me roll my eyes so hard, some overly-glammed-up lady went on TV and started reading numbers off them.

**Comment by ferdnyc** [comment]
Closing as... answered, I guess?  `¯\_(ツ)_/¯`
