### ISSUE TITLE
Backward Time is replacing a clip and seen only in export, but not in preview

### ISSUE THREAD

**Issue by Norumu** [OpenShot/openshot-qt#3451]
**Describe the bug:**
I am fairly junior to video editing, so my apologies if any nomenclature is confusing.

I'm on Windows 10, using the main release, and later tested with the daily build. I'm trying to make some very short, looping background clips for the very silly reason of Zoom meeting backgrounds. To make this happen, I'm taking a ~15secong video clip from a larger source file, removing the audio, then copying it onto the timeline to repeat, but use the Time > Backward > 1x option on the copied clip, so it reverses back to the starting point for a good enough smooth looping experience.

I successfully made one video file with this method. When attempting to make the next one using the same methodology, the copy of the first clip will be replaced by my first video file's version of that clip after I apply the Time > Backward > 1x option, but this is only seen in the exported video file, not within the project or preview. In the project, the copied clip looks exactly as it should on both the timeline and the preview. The clip replacement is ONLY seen in the video export.

I tried some troubleshooting.
1) I checked to see if it's an issue with the copy-paste clipboard since it seems like OpenShot maintains its own clipboard. So, instead of copying and pasting, I instead clipped the section of the video I'm using in the project files first, before adding it to the timeline. Then added that clip twice instead of copying and pasting. This did not resolve the issue.

2) I checked to see if changing the volume settings was causing this issue. Nope. Regardless of audio changes, this issue would still occur, though the audio would be bugged out in the wrong half of the video.

3) I checked the Time > Backward > 1x option specifically. When I did not use this on the 2nd half/copied clip, the resulting video export was fine and did not include the incorrect, original video file's clip. Then, after using the Time > Backward > 1x option, the resulting export showed this error.

To me, it seems like there's some very strange problem where the Time > Backward > 1x feature option is caching clip data, and I can't seem to purge it. 

Following this testing, I tried submitting a bug report through the OpenShot site's bug report walkthrough, which included testing on the Daily Build. Even after installing the daily build, this exact issue persisted. Albeit, I did not do a full uninstall prior to updating the daily build, but I think it's wildly impractical to have to do a full uninstall/reinstall cycle to deal with a fairly small error.

**Steps to reproduce the behavior:**
1. From a larger source video, cut a 15-second video clip
2. Add Step 1 15-second clip to the project timeline
3. Copy Step 2 clip to play immediately following the Step 2 clip
4. Reverse the Step 3 clip by right-clicking the Step 3 clip, selecting Time > Backward > 1x
5. Export video
6. Start a new project
7. From the same larger source video described in Step 1, cut a different 15-second video clip
8. Add Step 7 15-second clip to the project timeline
9. Copy Step 8 clip to play immediately following the Step 8 clip
10. Reverse the Step 9 clip by right-clicking the Step 3 clip, selecting Time > Backward > 1x
11. Export video
12. After 15-second mark, Step 11 video should show the clip from Step 4 instead of the intended clip from Step 10

**Expected behavior:**
The second video export should contain its own clips, as seen in its project timeline and preview.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 2.5.1-dev2
- Operating System / Distro: Windows 10

**Log Files:**
No crashes, but here are the log files.
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/4578333/openshot-qt.log)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/4578334/libopenshot.log)

**Comment by SuslikV** [comment]
With the _Process Video Frames in Parallel (Experimental)_ **unchecked** in _Preferences_ I even can't get not flickering video during this _Time>Normal>Backward>1x_ operation (result full of black frames inserted). How to test it??? Openshot is such openshot...

@ferdnyc please, check on linux, that it even possible to get _Time>Normal>Backward>1x_ over the clip (I tested small 5 sec file) to work OK in Preview and Export (without black frames flickering) when _Process Video Frames in Parallel (Experimental)_ is unchecked.

**Comment by matthewtmoran** [comment]
Also happening to me. Sped up a clip and it's replaced by another section of the video on export.
