### ISSUE TITLE
When Clicking. Edit. then preferences. it causes openshot to crash and shutdown 

### ISSUE THREAD

**Issue by ssnjimb** [OpenShot/openshot-qt#3455]
**Describe the bug**
When Clicking. Edit. then preferences. it causes openshot to crash and shutdown

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 2.5.1
- libopenshot Version:  0.2.5
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 69 Stepping 1, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1588204308-15c3efb7-26b7db94-x86_64.exe

**Log Files**
- http://logs.openshot.org/dtkkpp8acd48ykod5rtncl5u4bynacde/openshot-qt.zip
- http://logs.openshot.org/dtkkpp8acd48ykod5rtncl5u4bynacde/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by SuslikV** [comment]
What Intel's GPU driver version are you using?

Application crashed during Quick Sync decoder test.
Try to exclude the crashed test from the list, (by modifying the `preferences.py` file) like in: https://github.com/OpenShot/openshot-qt/issues/3276#issuecomment-595052453

**Comment by rlatoska** [comment]
The same Problem on Ubunut 20.04 (Lenovo ThinkPad T460)

1. renamed $HOME/.openshot_qt
2. started in terminal openshot_qt
3. crash on entering preferences

ui_util:INFO Initializing UI for dlgPreferences
Hardware decoding device number: 0
Hardware decoding device number: 0
[h264 @ 0x59271c0] Invalid setup for format vdpau: does not match the type of the provided device context.
[h264 @ 0x59271c0] Invalid setup for format cuda: does not match the type of the provided device context.
[AVHWFramesContext @ 0x56f63c0] Failed to read image from surface 0x17: -1 (unknown libva error).
[swscaler @ 0x7f10ac2ba4c0] Warning: data is not aligned! This can lead to a speed loss
Caught signal 11 (SIGSEGV)
