### ISSUE TITLE
.osp file doesn’t remember waveforms

### ISSUE THREAD

**Issue by XanderLeaDaren** [OpenShot/openshot-qt#3456]
**Describe the bug:**
Any clip with separated audio gets displayed twice as video when saving to project then opening the .osp file later

**Steps to reproduce the behavior:**
1. Place any video clip on the timeline
2. Separate audio [screenshot 1]
3. Save Project & quit OpenShot
4. Launch OpenShot & open the .osp Project file
5. The separated audio is now displayed with thumbnail and not as waveform [screenshot 2]

**Expected behavior:**
Any separated audio should be displayed as such when opening an .osp file

**System Details:**
– OpenShot Version 2.5.1
– libopenshot 0.2.5
– Operating System macOS Catalina 10.15.2

**Screenshots:** (Optional)
1. Separated audio displayed as waveform
![ekrano-kopio 2020-05-05 à 16 58 08](https://user-images.githubusercontent.com/28948599/81082260-5572b780-8ef3-11ea-88a4-26b4f68cf956.jpg)

2. Thumbnail display after closing and opening the file again
![ekrano-kopio 2020-05-05 à 16 59 13](https://user-images.githubusercontent.com/28948599/81082270-59063e80-8ef3-11ea-8fac-ec65b5f734e2.jpg)

3. Only workaround I found is to right-click > Display > Show waveform on _every_ separated audio clip – which can be very annoying for large projects :-/
![ekrano-kopio 2020-05-05 à 16 59 26](https://user-images.githubusercontent.com/28948599/81082282-5b689880-8ef3-11ea-9b26-d175ff47a76d.jpg)

**Comment by SuslikV** [comment]
All platforms affected.

**Comment by XanderLeaDaren** [comment]
Update: not sure if it’s related, but if you slice a clip shown as a waveform (either by Razor tool, menu or ctrl+k/j/l) and undo this slicing, the waveform disappears as well.

**Comment by XanderLeaDaren** [comment]
Related to #2285 ?

**Comment by XanderLeaDaren** [comment]
Could also be related to #2035
