### ISSUE TITLE
Keyboard shortcut to “bump” a clip to the next/previous one in the timeline

### ISSUE THREAD

**Issue by XanderLeaDaren** [OpenShot/openshot-qt#3457]
**Describe the new feature:**
When trimming parts of a video, you get “gaps” between clips. I would like a keyboard shortcut to move any selected clip right or left to the closest clip, filling the gap between them.

**Describe the solution you'd like:**
Select any desired clip, and hit a dedicated key combo, let’s say ctrl+shift+left/right to move the selected clip to the closest clip before/after.

**Describe alternatives you have considered:**
With snapping enabled, click on the clip and drag it to get it bumped to the desired previous/next clip.

**Screenshots (desired behaviour):**
1. Select a clip that has “gaps” around
![ekrano-kopio 2020-05-05 à 17 23 25](https://user-images.githubusercontent.com/28948599/81083819-5573b700-8ef5-11ea-84d7-56f99df14a66.jpg)

2. Result if left-bumping it to previous clip
![ekrano-kopio 2020-05-05 à 17 23 32](https://user-images.githubusercontent.com/28948599/81083824-57d61100-8ef5-11ea-9d9b-0c19e25f01eb.jpg)

3. Result if right-bumping it to next clip
![ekrano-kopio 2020-05-05 à 17 23 41](https://user-images.githubusercontent.com/28948599/81083833-5a386b00-8ef5-11ea-8a7f-eebd6c2c3916.jpg)

**Comment by SuslikV** [comment]
It looks very similar to: https://github.com/OpenShot/openshot-qt/issues/753 and some linked requests.

**Comment by XanderLeaDaren** [comment]
The “Nudge” command referenced in https://github.com/OpenShot/openshot-qt/issues/753#issuecomment-583915291 helps in moving clips, but still, it doesn’t help automatically moving a clip to “stick” to the next/previous one.
