### ISSUE TITLE
video preview is freezing

### ISSUE THREAD

**Issue by ruffieuxh** [OpenShot/openshot-qt#3459]
**Beschreiben Sie den Fehler**
video preview is freezing, when running based on a saved project

**Schritte zum Reproduzieren des Verhaltens**
1. Import a long video (i.e. 1.5hrs)
2. Add video to stream
3. save as a new project
4. preview video and jump a bit around n video. It will freeze and consume 150% cpu

**Erwartetes Verhalten**
I expect the preview NOT to freeze.

**Systemdetails**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Linux-4.15.0-99-generic-x86_64-with-Ubuntu-18.04-bionic
- Processor: x86_64
- Machine: x86_64
- Python version: 3.6.9
- Qt5 version: 5.9.5
- PyQt5 version: 5.10.1
- Qt Detected Languages: ['de-DE', 'en-GB', 'en']
- LANG Environment Variable: de_DE.UTF-8
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1588687640-15c3efb7-26b7db94-x86_64.AppImage

**Logdateien**
- http://logs.openshot.org/3l554nvo4scwx2v8pxssnqkoi4mj2jgi/openshot-qt.zip
- http://logs.openshot.org/3l554nvo4scwx2v8pxssnqkoi4mj2jgi/libopenshot.zip

**Ausnahme / Stapelverfolgung**
```No stacktrace found in log files```

**Bildschirmfotos** (Optional)
Wenn möglich, fügen Sie Screenshots zur unterstützenden Erklärung Ihres Problems hinzu. Sie können Screenshots einfügen,
indem Sie diese kopieren und auf Github einfügen oder durch Drag and Drop zur GitHub-Seite hinzufügen. Alle Bilder sind öffentlich zugänglich, posten Sie deshalb keine Screenshots die persönliche Informationen enthalten.

**Comment by SuslikV** [comment]
Some files better to remux (OBS Studio, FFmpeg etc.) before importing into OpenShot. Sometimes in _Preferences_ of OpenShot are too many threads are set by default, consider to reduce this numbers to number of available CPU cores at least. This affects performance of OpenShot.

AppImage builds are not recommended for production. Try native installation or build yourself.
