### ISSUE TITLE
A/V  out of sync on export using 720p 30fps Video Profile

### ISSUE THREAD

**Issue by chadleyb** [OpenShot/openshot-qt#3460]
**Describe the bug**
When the HD 720p 30fps Video Profile is selected, the audio and video are out of sync in the exported video. 

**Steps to reproduce the behavior:**
1. Prepare a video production (I have had this happen with two different videos the input is usually mkv from obs studio or MP4 from YouTube) 
2. Click on Red Dot to Export Video
3. Choose HD 720p 30 fps (1280 x 720) Video Profile
4. Export the video 
5. Audio and Video will be out of sync on produced video

**Expected behavior**
The Audio and Video should be in sync
Note: Exact same project file and sources when exported with the 720p 60fps Video Profile is properly in sync

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Windows-10-10.0.18362
- Processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1588687976-15c3efb7-26b7db94-x86_64.exe

**Log Files**
- http://logs.openshot.org/74nrix18zsi9aiecqq2ffceikfoiudp3/openshot-qt.zip
- http://logs.openshot.org/74nrix18zsi9aiecqq2ffceikfoiudp3/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by SuslikV** [comment]
Sounds similar to: https://github.com/OpenShot/openshot-qt/issues/1290

Side note. I can only recommend to you to disable auto-saving in _Preferences_ to not get project overwritten silently (and in most busy time).

**Comment by chadleyb** [comment]
My workaround is to produce it in 60fps and then use handbrake to shrink it.

**Comment by SuslikV** [comment]
Can you share smallest video sample that after encoding in OpenShot causing sync issues for you? So I can test it on my end?

**Comment by chadleyb** [comment]
I will get on that tomorrow.

**Comment by ctsdownloads** [comment]
Has this issue been resolved?

**Comment by chadleyb** [comment]
No I need to send a file. I'll get on it.

Thanks,
..Chad

**Comment by chadleyb** [comment]
bug.zip
<https://drive.google.com/file/d/1BrU09Rf5HqlgRbYDjIP-xRlsM8aWxyjl/view?usp=drive_web>

**Comment by SuslikV** [comment]
@chadleyb usually, users shoot video sample directly for the test purposes and share it with everyone. Your share is not for everyone.

**Comment by chadleyb** [comment]
https://drive.google.com/file/d/1BrU09Rf5HqlgRbYDjIP-xRlsM8aWxyjl/view?usp=sharing

Now everyone with the link should have access.

Thanks,
..Chad

**Comment by SuslikV** [comment]
Try VLC Player or mpv Player. The result may change. Issue needs more time to make any conclusions.

**Comment by chadleyb** [comment]
I've just been using the 60fps option, and it works fine. I was just trying
to let you know.

**Comment by chadleyb** [comment]
It continued to repeat on several of the videos that I was producing ... so
I just switched to 60fps and then I compressed with Handbrake. Nowe we've
moved to 1080p, so will be using that configuration.

Thanks,
..Chad
