### ISSUE TITLE
invalid load key '{'

### ISSUE THREAD

**Issue by snoopy8612** [OpenShot/openshot-qt#3461]
**Describe the bug:**
When I try to open my project I have this error

![image](https://user-images.githubusercontent.com/64739124/81304082-df01c100-907c-11ea-94ca-40dc67d27cf7.png)

**Can you help me? please !!!**

[le confinement avec Noodle et Jadecorrigetest.txt](https://github.com/OpenShot/openshot-qt/files/4593414/le.confinement.avec.Noodle.et.Jadecorrigetest.txt)

**System Details:**
- OpenShot Version 2.4.4: {{ log_context.openshot_qt_version }}
- Operating System Windows 7

**Comment by SuslikV** [comment]
Duplicate of: https://github.com/OpenShot/openshot-qt/issues/3444
