### ISSUE TITLE
Cannot import a video

### ISSUE THREAD

**Issue by Orzechonator** [OpenShot/openshot-qt#3465]
**Describe the bug**

**Hello,

When I'm trying to import a video to OpenShot project, nothing is happening. The OpenShot is not interactive for a while, something like it's loading and then... nothing. Reinstall did not help, portable version is doing the same. Don't know if I can tell You anything more, but it's really important for my job to use this app and I will be very glad if anyone could help me with that bug.

Cheers and thanks for help,
Kuba**

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Windows-10-10.0.18362
- Processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['pl-PL', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1588892279-6e7ad231-a62505ca-x86_64.exe

**Log Files**
- http://logs.openshot.org/xhxf1o66gh42jnpvlyejqyubdnp55yb4/openshot-qt.zip
- http://logs.openshot.org/xhxf1o66gh42jnpvlyejqyubdnp55yb4/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Comment by SuslikV** [comment]
Despite different OS version, this very similar to https://github.com/OpenShot/openshot-qt/issues/3369

I have only few thoughts about this behavior. Windows Defender (antivirus), Firewall or insufficient rights to run/access the application's own thumbnails generator server.

**Comment by Orzechonator** [comment]
Tried all of that, nothing worked.

**Comment by ctsdownloads** [comment]
Two questions: What is the size and type of file being imported? Are you dragging it in or are you using the import icon instead?

**Comment by tomtem67** [comment]
Same problem as Orzechonator, with win 10. Lates versinon OpenShot Video 2.5.1, -dev2, libopenshot: 0.2.5-dev2

When I'm trying to import a video to OpenShot project, nothing is happening. I tried draggin or import. Same with pictures or audio files. 

Sistem:

Ime operacijskega sistema	Microsoft Windows 10 Home
Različica	10.0.18363 Delovna različica 18363
Opis drugih operacijskih sistemov 	Ni na voljo
Izdelovalec operacijskega sistema	Microsoft Corporation
Ime sistema	TOMAŽ
Izdelovalec sistema	LENOVO
Model sistema	81SY
Vrsta sistema	x64-based PC
Inventarna številka sistema	LENOVO_MT_81SY_BU_idea_FM_Legion Y540-15IRH-PG0
Procesor	Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz, 2592 MHz, št. jeder: 6, št. logičnih procesorjev: 12
Različica/datum BIOS-a	LENOVO BHCN35WW, 23. 11. 2019
Različica SMBIOS-a	3.0
Različica vdelanega mikrovmesnika	1.35
Način BIOS	Vmesnik UEFI
Izdelovalec matične plošče	LENOVO
Izdelek matične plošče	LNVNB161216
Različica matične plošče	SDK0R32862 WIN


[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/5332773/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/5332774/openshot-qt.log)
