### ISSUE TITLE
Can't create or load anything with a random transition on it...

### ISSUE THREAD

**Issue by nanohtpc** [OpenShot/openshot-qt#3466]
Can't create or load anything with a random transition on it...

winx64

latest daily...

8((((

**Comment by SuslikV** [comment]
Duplicate of: https://github.com/OpenShot/openshot-qt/issues/3401

**Comment by nanohtpc** [comment]
probkem REMAINS, even editing the hidden files....

**Comment by jonoomph** [comment]
This is fixed in the latest daily build: https://www.openshot.org/download#daily
