### ISSUE TITLE
Can't Execute the openshot on my laptop

### ISSUE THREAD

**Issue by kantha1990** [OpenShot/openshot-qt#3467]
Hey everyone, just downloaded Openshot video editor for simple task. After the installation when i tried to execute the program it won't. I tried maybe 5-6 times even with administrative rights but it still won't open. Also checked my task manager and it didn't show any thing in regard with openshot. What may be the problem ? Is this my kind of bug ?

I am running:
windows 10
SSD
i7-7500U
8gbs Ram

I have also attached my openshot log. 

Any help would be appreciated. Thank you!!!

[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/4603878/openshot-qt.log)

**Comment by SuslikV** [comment]
Next string in the log should be, something like this:
```
app:INFO Setting font to *** images\fonts\Ubuntu-R.ttf
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
```
and maybe Firewall warning on the screen.

You may try to unpack the application to different folder (_innounp_ v0.49 should work well) and run `openshot-qt.exe` from the file explorer, maybe it will run then.

If not - try to modify default theme (`openshot.settings` file, I'm using _notepad++_ minimalist version for this):
find:
```
 {
  "value": "Humanity: Dark",
  "title": "Default Theme",
```
change to:
```
 {
  "value": "No Theme",
  "title": "Default Theme",
```
If nothing helps - don't waist you time on it, try other software.

**Comment by MBB232** [comment]
@kantha1990 Did you install the default version or the daily? 
I noticed a similar thing with the newest daily (but not older). After running windows defender on it, it ran. (4th of 5th try though)

**Comment by kantha1990** [comment]
@MBB232 I installed 2.4.2 version which I think is the latest one offered on the website. I tried even the next day but it didn't worked out in the end and had to uninstall it.

**Comment by kantha1990** [comment]
@SuslikV Couldn't find the file you asked for but yeah I uninstalled it in the end.

**Comment by SuslikV** [comment]
It usually lies in `.openshot_qt` folder on system drive, if it matter now.
