### ISSUE TITLE
Can't export the video

### ISSUE THREAD

**Issue by MayKoon** [OpenShot/openshot-qt#3471]
**Describe the bug:**

**Steps to reproduce the behavior:**

**Expected behavior:**

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.
Log files can be found in your HOME/.openshot_qt/ folder. Please compress or zip
the log files (as they can become quite large).

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please
attach a small snippet of the exception here, but please keep it as small as
possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them here, dragging-and-dropping into this form, or clicking below and loading
images saved to your computer. All images are public, so please don't post screenshots
containing personal information.

**Comment by SuslikV** [comment]
Not enough info to make any conclusion what caused your issue. Can you provide actual "Steps to reproduce the behavior" rather than leaving not filled template report? OpenShot's log-file after the export failure?

**Comment by sosofie** [comment]
Just downloaded the latest version as I was having troubles with the sound. This was ok when playing in openshots, but when exported into video the talking became inaudible and was replaced by crackling sounds. In an attempt to solve this, I downloaded the newer version, but now I can't even make a video anymore. If you click on the red dot, nothing happens. If you go to file > export project > export video    nothing happens. If you press Ctrl + E nothing happens. 
There are no warnings, no text box emerging, ... nothing happens.

**Comment by sosofie** [comment]
> Just downloaded the latest version as I was having troubles with the sound. This was ok when playing in openshots, but when exported into video the talking became inaudible and was replaced by crackling sounds. In an attempt to solve this, I downloaded the newer version, but now I can't even make a video anymore. If you click on the red dot, nothing happens. If you go to file > export project > export video nothing happens. If you press Ctrl + E nothing happens.
> There are no warnings, no text box emerging, ... nothing happens.

System Details: Windows 10

**Comment by SuslikV** [comment]
@sosofie try to look for the solution in: https://github.com/OpenShot/openshot-qt/issues/2676 and attach your OpenShot log file from this attempt (where issue surely present). Maybe project file is damaged - you can try to make new one.

**Comment by MBB232** [comment]
Noticed the same this afternoon when taking a quick look at the new dailys to see if the new frame-number was in it yet.  (It was not)
OpenShot-v2.5.1-dev2-1589067618-6e7ad231-a62505ca-x86_64.exe
Did not report it yet because I had not taken time to confirm. 
Is there another daily you want me to try? I noticed there were a lot of them today. (The daylies from 5 May were fine)

Not sure what the 'solution' was from what you linked, something by adding 'null fields' somewhere? 
I tried different profiles, and copy in a profile from your Encoder-version from the other day (still had it since it installed in separate dir). Made no difference. 

here are the logs. 

[CLI_log.txt](https://github.com/OpenShot/openshot-qt/files/4606856/CLI_log.txt)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/4606857/openshot-qt.log)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/4606858/libopenshot.log)

**Comment by SuslikV** [comment]
@MBB232 
the:
```
files_listview:INFO currentChanged
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "C:\Program Files\OpenShot Video Editor\windows\views\files_listview.py", line 309, in currentChanged
    self.updateSelection()
  File "C:\Program Files\OpenShot Video Editor\windows\views\files_listview.py", line 56, in updateSelection
    self.win.selected_files = [x.text() for x in self.selected_items if x.column() == 5]
AttributeError: 'FilesListView' object has no attribute 'selected_items'
```
needs investigation. The changes introduced in: https://github.com/OpenShot/openshot-qt/pull/3312 (merged by https://github.com/OpenShot/openshot-qt/commit/9edd6936099c5e0389a1bd63ef91204bbdb33c32) maybe some dependent branch wasn't merged or just mistake somewhere in the code.


the:
```
timeline_webview:INFO UpdateLayerIndex
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "C:\Program Files\OpenShot Video Editor\windows\main_window.py", line 743, in actionExportVideo_trigger
    from windows.export import Export
  File "C:\Program Files\OpenShot Video Editor\windows\export.py", line 45, in <module>
    from PyQt5.QtGui import QSize, QIcon
ImportError: cannot import name 'QSize' from 'PyQt5.QtGui' (C:\Program Files\OpenShot Video Editor\lib\PyQt5\QtGui.pyd)
```
The changes introduced in:  https://github.com/OpenShot/openshot-qt/pull/3419 (merged by https://github.com/OpenShot/openshot-qt/commit/564db2b2f9543094f7c3c762e171213bbe63cf97) just mistake. It would be fixed "soon" ^_^

**Comment by ferdnyc** [comment]
Ah, crap. That sure is my fault. Sorry about that, will get a fix in ASAP.

**Comment by ferdnyc** [comment]
(The bad `QSize` import. I suspect the other one is a case of badly-resolved PR conflicts, which I'll look at after I fix the export dialog imports.)

**Comment by SuslikV** [comment]
Small remark, @ferdnyc says only about issues pointed by @MBB232 
(Topic starter didn't provided any useful info to get the details and make any conclusions.)

**Comment by ferdnyc** [comment]
> I suspect the other one is a case of badly-resolved PR conflicts, which I'll look at after I fix the export dialog imports.

Nope, just more stupid on my part. Will be fixed by #3481.

**Comment by MBB232** [comment]
> > I suspect the other one is a case of badly-resolved PR conflicts, which I'll look at after I fix the export dialog imports.
> 
> Nope, just more stupid on my part. Will be fixed by #3481.

@ferdnyc 
Let me know if I need to test. Will they be in the dailies of the 16th? (I believe they are created every week?)

**Comment by ferdnyc** [comment]
@MBB232 New "daily" builds are actually generated within 5-10 minutes of each change to the branch, normally. So, it'll be testable shortly after the PRs are merged.

**Comment by ferdnyc** [comment]
(They're generated ONLY when the branch changes, which is why "daily" is something of a misnomer really, and why sometimes a week can pass with no new (unnecessary) builds if nothing changes.)

**Comment by ferdnyc** [comment]
I'll get #3481 in shortly. I took the opportunity to clean up the two files so that the duplicate code sections contain fewer differences, and the sections that are different are grouped more logically.

**Comment by MBB232** [comment]
Seems to be fixed in latest daily 16 may
