### ISSUE TITLE
Core Utilization AMD 3700X

### ISSUE THREAD

**Issue by SomeInfosecGuy** [OpenShot/openshot-qt#3473]
**Question:**
I have an AMD Ryzen 7 3700X and I noticed that only ~6 cores of compute cycles are used when exporting. Is there a way to use the 8 physical cores, or even better, all 16 threads?

I was looking through the issues and didn't see this addressed, and searched Google and found questions related to mine from over 10 years ago. Please forgive me if I missed an answer.

**System Details:**
- OpenShot Version 2.5.1
- Operating System / Distro: Windows 10 1909
- Samsung 860 evo
- 16GB 3200MHz system memory
- 4GB memory cache

**Comment by ctsdownloads** [comment]
Not really, no. However, if you have a compatible NVIDIA card, you could use [NVENC](https://github.com/OpenShot/libopenshot/blob/develop/doc/HW-ACCEL.md) powered rendering to speed things along.

**Comment by necros2k7** [comment]
> 
> 
> Not really, no. However, if you have a compatible NVIDIA card, you could use [NVENC](https://github.com/OpenShot/libopenshot/blob/develop/doc/HW-ACCEL.md) powered rendering to speed things along.

not supported on latest build
