### ISSUE TITLE
[website] "© 2008-2017" in the website's footer

### ISSUE THREAD

**Issue by yfdyh000** [OpenShot/openshot-qt#3474]
https://www.openshot.org/
As an active project, it should be updated.

In addition, the website is great. But I didn't see it being open sourced and provide a issues management, so I submit it here.

**Comment by ferdnyc** [comment]
It's not open-sourced and the project has no control over the website content. Only thing I can suggest is to email @jonoomph (jonathan@openshot.org), who is the sole maintainer of the site.
