### ISSUE TITLE
no popup when clicking export video 

### ISSUE THREAD

**Issue by ti-vo** [OpenShot/openshot-qt#3476]
**error description:**
when clicking on "export video", there is no popup (nothing happens)

**Reproduce:**
1. open a project
2. click on the red button 

**expected behaviour:**
Pop-up window so specify where to save exported video

**system details:**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Linux-4.19.0-8-amd64-x86_64-with-debian-10.3
- Processor: 
- Machine: x86_64
- Python version: 3.4.3
- Qt5 version: 5.2.1
- PyQt5 version: 5.2.1
- Qt Detected Languages: ['de-DE']
- LANG Environment Variable: de_DE.UTF-8
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1589067618-6e7ad231-a62505ca-x86.exe

**log files**
- http://logs.openshot.org/xyylbb7q8yeyn1smto0pu2ih84dur9hb/openshot-qt.zip
- http://logs.openshot.org/xyylbb7q8yeyn1smto0pu2ih84dur9hb/libopenshot.zip

**Ausnahme / Stapelverfolgung**
```No stacktrace found in log files```

**Comment by SuslikV** [comment]
This is only daily build issue. More info is here: https://github.com/OpenShot/openshot-qt/issues/3471#issuecomment-626494147

**Comment by ferdnyc** [comment]
If using the latest builds, agreed. Fixed in #3480.
