### ISSUE TITLE
Rejecting valid image files - data takes too much space

### ISSUE THREAD

**Issue by casparcash** [OpenShot/openshot-qt#3477]
I have a problem with the following error code: "Rejecting valid image files for image sequence import"
I know why it happens but don't know how to solve it. Whenever my temp-folder is full (meaning that my c-drive is full) I get this error-message. Is there a way to store the temporary data at an other location e.g. a temporary drive? Because this is difficult as movies take up so much space.

**Comment by SuslikV** [comment]
As workaround:

I assuming you are using Windows.

1. There is `%TMP%` variable (and %TEMP% may be) in Windows (System Properties, Advanced, the Environment Variables settings button or so).
2. Also, link is possible (google for NTFS symbolic links for folders, `mklink`)
