### ISSUE TITLE
Blender does not start 

### ISSUE THREAD

**Issue by maurizio-belingheri** [OpenShot/openshot-qt#3482]
![Capture](https://user-images.githubusercontent.com/65193201/81607293-bd823b80-93d4-11ea-895f-93358eb76766.JPG)
**Describe the bug**
Blender does not start when clicking on an icon of the animated titles despite having placed in Preferences the path to the Blender executable (ver. 2.82)

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 2.5.1
- libopenshot Version:  0.2.5
- Platform: Windows-10-10.0.18362
- Processor: Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1589216865-6e7ad231-a62505ca-x86_64.exe

**Log Files**
- http://logs.openshot.org/94152cl447blo2t6jpxkgm8o4kfea6pk/openshot-qt.zip
- http://logs.openshot.org/94152cl447blo2t6jpxkgm8o4kfea6pk/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.
                
![Capture](https://user-images.githubusercontent.com/65193201/81607343-d25ecf00-93d4-11ea-8e32-c16a28225bdd.JPG)

**Comment by speedytechdev** [comment]
Hi @maurizio-belingheri could you please provide the steps you took to get this issue. This will allow us to reproduce the bug and hopefully fix it.

**Comment by maurizio-belingheri** [comment]
The steps I took are the following:

-          Downloaded Blender version 2.82 (required version by OpenShot is >2.8)

-          Inserted the path to the Blender .exe file (the one with the blender icon) in OpenShot settings

-          Selected an animated title

-          After few seconds I got the message as per screenshot in my previous e-mail.

 

Kind regards,

 

M. Belingheri

**Comment by speedytechdev** [comment]
@maurizio-belingheri Perfect, When you get a chance can you edit the original issue and add those step's in. Hopefully, a dev will be able to help you soon. Enjoy the rest of your day 😄

**Comment by maurizio-belingheri** [comment]
Here are the edited steps with the issue:

-          Downloaded Blender version 2.82 (required version by OpenShot is >2.8)

-          Inserted the path to the Blender .exe file (the one with the blender icon) in OpenShot Preferences:





 

-          Selected an animated title (e.g. “World map”):



 

-          After few seconds I got this message:



 

Please help, thanks.

Kind regards,

 

M. Belingheri

**Comment by dr0i** [comment]
For Linux I discovered that an absolute path doesn't  work - openshot always seems to append the path to blender to your home directory. So, only relative paths (starting from your home directory) are working. Maybe that's also the case for windows.

**Comment by maurizio-belingheri** [comment]
Thank you, but I tried a relative path and the error remains the same.

 

Best regards,

 

M. Belingheri

**Comment by Shekelme** [comment]
Almost the same issue is on my PC:
OS: Windows 7 x64
OpenShot: OpenShot-v2.5.1-dev2-1592475299-517f2896-7cec1822-x86_64.exe
Blender: v2.83.0
I have pointed OpenShot to Blender's executable with "Browse..." button but it still doesn't work.

![image](https://user-images.githubusercontent.com/26449500/85250167-058a8880-b480-11ea-9527-a1b86342bdab.png)

And I still can't start making animated titles:

![image](https://user-images.githubusercontent.com/26449500/85250324-7336b480-b480-11ea-88f5-537b010e88e0.png)

Also there is a Windows cursor indicating that "system is busy" which is not indicated on last screenshot.

**Comment by ctsdownloads** [comment]
Found the solution - [needs 2.80](https://download.blender.org/release/Blender2.80/blender-2.80-windows64.msi). Apparently newer versions come up as undetected when I run OpenShot from the command line during tests. I can confirm this works for Linux users. Tested on PCLinuxOS.

1) Try the latest version of OpenShot.
2) Use the [Blender package for 2.80](https://download.blender.org/release/Blender2.80/blender-2.80-windows64.msi)
