### ISSUE TITLE
In the first seconds of the compiled video, the audio is heard accelerated

### ISSUE THREAD

**Issue by JavGuerra** [OpenShot/openshot-qt#3484]
**Describe the bug:**
In the first few seconds of the compiled video, the audio is heard at a higher speed, and then it returns to normal. I have tried this on Linux and Windows, with the same result. Examples:
Linux: https://youtu.be/0hm0ftg2Csc
Windows: https://youtu.be/jK2Qq0SN7Zg (With a file .osp created in Linux initially.)

**Steps to reproduce the behavior:**
1. I open a project
2. I choose a video
3. I drag the video to track one, at the beginning, and let it magnetically locate to the starting position of the track.
4. I choose the options to compile the video and start the process.
5. The result is displayed on my different computers as seen in the previous examples.

**Expected behavior:**
The audio should not increase its speed at the start of the compiled video, as no program option has been chosen to do this.

**System Details:**
- OpenShot Version 2.5.0 Linux. Versión 2.5.1 Windows.
- Operating System / Distro: the last Linux Mint / Windows 10.

**Comment by SuslikV** [comment]
Application exports only constant FPS videos. If source was variable - some strange things may happen.

**Comment by JavGuerra** [comment]
> Application exports only constant FPS videos. If source was variable - some strange things may happen.

As you can see in the examples, what is shown at the beginning is a cover that is a static image (png) and an audio (mp3).

The problem is when, in those examples, I drag the audio (or a video) at the beginning on the track, but if I put the audio or the video on the track, in any position, and then change the properties so that it is located at the zero position off the track, then the problem goes away.

**Comment by SuslikV** [comment]
@JavGuerra please say, if you can reproduce the issue with the build mentioned here: https://github.com/OpenShot/openshot-qt/issues/3439#issuecomment-624816230 . Because I cannot.

**Comment by JavGuerra** [comment]
@SuslikV I have tried to compile the video in the version that you indicate, and the problem does not reproduce. I have deleted the OpenShot configuration folder, I have updated OpenShot to version 5.1 in Linux Mint and compiling the video does not reproduce the problem either. I have not tested yet on Windows.

**Comment by SuslikV** [comment]
I even don't know at which second of your video I should look to see the speed up. Where it is?

**Comment by JavGuerra** [comment]
I said this when describing the problem. At the beginning, in the first seconds of the video.

**Comment by SuslikV** [comment]
0-10 seconds?

**Comment by JavGuerra** [comment]
In the first video (Linux), from 0 to 3 seconds.
In the second video (Windows) from 0 to 7 seconds.
