### ISSUE TITLE
Fullscreen does not remember if OpenShot window was maximized

### ISSUE THREAD

**Issue by MBB232** [OpenShot/openshot-qt#3485]
**Describe the bug:**
When using the  button, to go and return from fullscreen, the window size drops down to medium (AKA  RestoreDown) size regardless if it was maximized before. 

**Priority**
Low. Just discovered the  fullscreen modus, and found it odd. (May suitable as a 'beginner issue?' )

**Steps to reproduce the behavior:**
0.  Start with Openshot as loose window (drag it somewhere)
1. Go to 'maximize window' (right top corner) [See window fill screen but contain title bar]
2. Click on 'Fullscreen' (Openshot bar) [Openshot fills screen without title bars
3. Click on 'Fullscreen' (Openshot bar)' [Openshot moves back to window with title bars]
4. See loose window 

**Expected behavior:**
See window maximized again, as it started out before it went fullscreen. 
So it should remember if it was maximized or not when going fullscreen

**System Details:**
- OpenShot Version   2.5.1
- Windows 10,

**Log Files:** 
I can add them if they would help? 

**Screenshots:** 

<img width="840" alt="1-Window" src="https://user-images.githubusercontent.com/62191951/81753792-dbbf6880-94b4-11ea-94b6-ac4a23132632.png">
<img width="840" alt="2 Maximize" src="https://user-images.githubusercontent.com/62191951/81753796-dcf09580-94b4-11ea-82ae-14165364284a.png">
<img width="840" alt="3 Fullscreen" src="https://user-images.githubusercontent.com/62191951/81753797-dcf09580-94b4-11ea-92e0-dd60b2fb441a.png">
<img width="840" alt="4-ExitFullscreen_RestoreDown" src="https://user-images.githubusercontent.com/62191951/81753798-dcf09580-94b4-11ea-9d70-dafabb2334e9.png">

**Comment by ferdnyc** [comment]
> **Log Files:**
> I can add them if they would help?

No need.

> (May suitable as a 'beginner issue?' )

Agreed.

(For anyone considering working on this): Qt windows have separate properties for `maximized` and `fullscreen` (among other states). And `maximized` will stay **_`true`_** even after calling `showFullscreen()`, if the window was previously maximized. So, that's a restore-logic path. Buuut, those properties are read-only, so it's not a restore _interface_ per se.

And the annoying thing is, yes there's a `showFullscreen()`, along with `showMaximized()`, `showNormal()`, etc. — the functions we currently use — however none of those are state _toggles_, they just force a particular state. And they do it without considering any other existing state properties.

So, combining `windowState()` (which returns a bitmask) with [`setWindowState()`](https://doc.qt.io/qt-5/qwidget.html#setWindowState) (which takes one) may actually be the best approach to handling window state changes of all kinds. (And appears to be Qt's suggested approach, as you can just query, update, and set the state mask.)
