### ISSUE TITLE
Add "Insert keyframe with all properties" to property editor

### ISSUE THREAD

**Issue by imberest** [OpenShot/openshot-qt#3486]
**Describe the new feature:**
An option to add a keyframe with existing properties. This way editing video with keyframes would speed up the process X*3 times (where X is how many properties have been edited on a previous keyframe).
For example:
I am editing a video and want to zoom and pan, stay for some time, then zoom and pan to a different location
**0:00-0:05** zoom and pan to top right (new keyframe at 0:05)
**0:05-0:10** stay (at 0:10 duplicate keyframe of 0:05) <-- this is where I would benefit of "Duplicate keyframe" option
**0:10-0:16** pan and zoom to left top
So at 0:10 I have to insert every keyframe manually, which is 3 clicks per property (2 right clicks + left click on "Insert keyframe"), otherwise it will start the animation from 0:05 to 0:16.
And if to continue editing I would duplicate keyframe at 0:20, new at 0:25, duplicate at 0:30 etc...

I've started a [reddit ](https://www.reddit.com/r/OpenShot/comments/gi2ghn/editing_with_keyframes/)chat.

**Describe the solution you'd like:**
A button on property window or when object property window is opened to have an option "Insert duplicate keyframe", you can come up with a better name 😸 

**Screenshots:** 
Made a quick [video](https://streamable.com/v19hoo). 

Hope it makes sense 🤞

**Comment by ctsdownloads** [comment]
There are a number of keyframing improvements coming in a future release of OpenShot, I suspect they should help with this.

**Comment by frederikheld** [comment]
Aha. When did they come? It's 2023 now and I can't see any :-|
