### ISSUE TITLE
Layout Aspect Ratio

### ISSUE THREAD

**Issue by dnfort** [OpenShot/openshot-qt#3487]
When combining 8 videos and choosing "Show All (Maintain Ratio)" does not maintain the aspect ratio of the videos - they are elongated, up and down, in the Video Preview window and in any exported file.  Choosing "Show All (Distort)" produces the same result.  It is OK for 4 videos.  The videos are in landscape.

**Comment by ctsdownloads** [comment]
Hi, let me see if I can help here. Selecting 4 videos yields the correct aspect ratio, yet selecting 8 doesn't and does what your described with the preview and exported file.

On the surface, it "seems like" some of the source videos from the 8 might be different aspect ratios?

**Comment by rexdk** [comment]
I've had this issue too, trying to show about 21 videos. They all had the same aspect ratio, and were the same format/size. The Show All (Maintain Ratio) algorithm did not maintain the aspect ratio.

I'll try to take a screen shot next time it happens.

**Comment by rexdk** [comment]
I can re-create this on my Openshot 2.5.1, Win10.
*New project, default profile

*import a 384x576 png

*add it to the timeline on the first 5 tracks

*set each clip properties to Scale: None

![layout3](https://user-images.githubusercontent.com/44414261/83852428-a8ff3d80-a70b-11ea-8928-f208f8f41e3d.png)

*Layout -show all (maintain ratio)
![layout](https://user-images.githubusercontent.com/44414261/83852486-c6340c00-a70b-11ea-9532-133a99c47962.png)

The clips are set back to Scale: Best Fit, and the Scale X and Scale Y settings are *different* - ie the aspect ratio has not been preserved.

If you set all the clips back to Scale: None, you get:
![layout2](https://user-images.githubusercontent.com/44414261/83852567-e663cb00-a70b-11ea-97b8-c537041c7120.png)

which still has the wrong aspect ratio.

Layout - show all (distort) appears to work as expected
![layout4](https://user-images.githubusercontent.com/44414261/83852711-2034d180-a70c-11ea-876a-e78be1ed0cfd.png)
