### ISSUE TITLE
Cant convert to mp4

### ISSUE THREAD

**Issue by ArbitraryOrc096** [OpenShot/openshot-qt#3489]
I spent 3 hours filming and editing a youtube video. After which when I tried to Export the file so it could be an mp4 it did not work. It always gets stuck on 2.6%. This is weird because I also Posted a different youtube video the previous day and it had no trouble converting. I would really appriciate if you could resolve the matter. (I am on the latest version of Openshot.) I love the editing software, its easy to use and has cool features, but the fact remains that it is useless unless it can convert the video file. I would very much appreciate if the Matter could be resoled as soon as possible
![Open shot failure](https://user-images.githubusercontent.com/65381211/82007474-aa5dbd00-96ad-11ea-94fe-3ddf391aa290.JPG)

**Comment by SuslikV** [comment]
You can try to find what clip/transition/effect may cause this, it lies near the 2.6% of the timeline. Is there any special that can be removed?

**Comment by a1012112796** [comment]
Maye I face same issue...
![image](https://user-images.githubusercontent.com/25342410/85215923-70b95980-b3b1-11ea-8235-95b272a9b7ac.png)
