### ISSUE TITLE
ISSUE: built-in function delete_ReaderClosed

### ISSUE THREAD

**Issue by kkohr** [OpenShot/openshot-qt#349]
Trying to export my video and I get this error message. Trying to export as an mov file or YouTube file, still getting this either way.

**Comment by fredthefrenchy** [comment]
Hi,
I have the same issue exporting a 720p video (W10)

**Comment by jonoomph** [comment]
This should be fixed now. Please retest with our latest daily build, and reopen this issue if the problem still happens. Also, please include OS version, and attach logs (https://github.com/OpenShot/openshot-qt/blob/master/.github/CONTRIBUTING.md). Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot. Thanks!
