### ISSUE TITLE
Openshot wont launch on Mac OS X 10.10.5

### ISSUE THREAD

**Issue by vflorentina** [OpenShot/openshot-qt#3490]
I just downloaded Openshot on my Mac, and it keeps coming up with this error when trying to launch.. can anyone help? 

<img width="417" alt="Screen Shot 2020-05-15 at 7 08 16 pm" src="https://user-images.githubusercontent.com/65394160/82032450-8e264400-96de-11ea-9c79-2943b0708bbf.png">

**Comment by SuslikV** [comment]
As workaround, you may try: https://github.com/OpenShot/openshot-qt/issues/3201#issuecomment-603315241
