### ISSUE TITLE
raspberry pi 4 package / compiling instructions

### ISSUE THREAD

**Issue by rnrmi** [OpenShot/openshot-qt#3491]
Hi!

I'm using RPI4 as my main PC and there is no suitable video editor that works ok. I was wondering if Openshot 2.5 (with HW decoding) could be the 1st real alternative for video editing with better performance for RPI.
I'm under raspbian stable and I am not sure what would be the best way to get Openshot 2.5 running. Are there any .deb package with ARM in mind? Compiling would be the way but for most users under raspbian it is not that straithforward :/

Thanks!

**Comment by ctsdownloads** [comment]
Unless it's in the Raspbian repositories or you able to compile it, probably not. The usual AppImage approach to running OpenShot is only for Intel architecture processors last I checked.

Additionally, video editing on low specification hardware like a Pi is difficult as it would be hitting your processor tremendously hard. Intel/AMD CPU based systems with dedicated graphics are preferred for video editing.

All of this said, you can edit videos from a command line using FFMPEG, It's not simple, but it is fun and can be done from a Pi. https://www.rigacci.org/wiki/doku.php/doc/appunti/linux/video/ffmpeg

Good luck!
