### ISSUE TITLE
Animated Title doesn't support Chinese

### ISSUE THREAD

**Issue by 66Leo66** [OpenShot/openshot-qt#3494]
Animated Title doesn't support Chinese. Output is blank when input Chinese as title text.

**Steps to reproduce the behavior:**
1. Go to 'Animated Title'
2. Click on any template that accepts a title text
3. Type Chinese in title text box. For exemple '中文'
4. No text in outpt area

**Expected behavior:**
Chinese should be rendered correctly.

**System Details:**
- OpenShot Version :2.5.1
- Operating System / Distro: Windows 10

**Comment by MBB232** [comment]
Seems to be (at least) an issue in Blender. (If it worked with earlier versions of Blender, maybe try that one again?)
The Blender workaround is to convert SVG to path (in Inkscape) before rendering them as mesh, I suspect that OpenShot is not doing that. 

https://www.blender.org/forum/viewtopic.php?t=19477
https://www.youtube.com/watch?v=HkB2cgpPSkI

**Comment by 66Leo66** [comment]
I've tried blender 2.80 portable version, but OpenShot told me no frame was found in blender output hen I tried to input Chinese(English works fine). Do I have to install old blender using installer?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"MBB232"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月17日(星期天) 中午11:49
收件人:&nbsp;"OpenShot/openshot-qt"<openshot-qt@noreply.github.com&gt;;
抄送:&nbsp;"66Leo66"<1463359949@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [OpenShot/openshot-qt] Animated Title doesn't support Chinese (#3494)





 
Seems to be (at least) an issue in Blender. (If it worked with earlier versions of Blender, maybe try that one again?)
 The Blender workaround is to convert SVG to path (in Inkscape) before rendering them as mesh, I suspect that OpenShot is not doing that.
 
https://www.blender.org/forum/viewtopic.php?t=19477
 https://www.youtube.com/watch?v=HkB2cgpPSkI

**Comment by MBB232** [comment]
Keep in mind, I am not a programmer, just hanging around here.

Again, have you verified that asian text function works in _Blender_? Did it used to work for you before? 

A second search came up with this: 

> Unfortunately doing so does not automatically change the font used when inserting "Text" objects. Therefore, while your new text object is selected you must go to Properties / Object Data / Font and select a font that contains characters needed for your language. The default font (Bfont) does not contain any Korean characters. You can select the international font that comes with Blender (droidsans.ttf.gz) or any others on your computer. Sorry for the inconvenience. We are hoping to improve this in the future.

So it is unlikely to work at all, because due to a limitation/bug in Openshot, Only Bfont Can Be Used In Animated Titles
https://github.com/OpenShot/openshot-qt/issues/3269

**Comment by ferdnyc** [comment]
Yeah, unfortunately. Limitation, though, not a bug. Blender's font support is, quite frankly, abysmal. 

* It can't use any fonts installed on the system. 
* Fonts have to be loaded from individual file for each typeface to be used. (Meaning, you want bold letters? That's another file. Italics? Separate file...)
* It can't do any of the fallback that we're used to fonts doing, meaning if the font file you load doesn't include a character, you don't get that character unless you load another one that **does** and select _that_ font...

It's just a mess, TBH, and we have no good solutions. Patches welcome!
