### ISSUE TITLE
wrong cut scenes exporting video

### ISSUE THREAD

**Issue by doriclaudino** [OpenShot/openshot-qt#3496]
**Describe the bug:**
Exporting video generate different cuts scenes.

- **opt1** - 720p 30fps 1280x720 using (mp4 h.264) -> good
- **opt2** - 1080p 60fps 1280x720 using (mp4 h.264) -> bad

I have a slow cut in my video timeframe, when exporting using option **"opt2"** my exported video is not the same as my project.

**Steps to reproduce the behavior:**
1. Go to export
2. Click on default export (opt1)
3. Go to export
4. Click on default export (opt2)
4. See different cut scene

**Expected behavior:**
both exported options should generate the same ouput (only diff quality)

**System Details:**
- OpenShot Version 2.5.1
- Windows 10

**Log Files:**
No crash

**Exception / Stacktrace:**
No Exception 

**Screenshots:** (Optional)

opt1 scene (the image guys came bottom-top) so I use it as reference:
Can see the different background
![image](https://user-images.githubusercontent.com/3863501/82150712-f122f280-9826-11ea-8854-7247351c4ac0.png)

opt2 scene (the image guys came bottom-top) so I use it as reference:
Can see the different background
![image](https://user-images.githubusercontent.com/3863501/82150807-216a9100-9827-11ea-9d6c-79bf85555405.png)

Soo for now I'm sharing my final video using default export, I want to understand why this happens, two different outputs only changing the quality/fps.

**Comment by SuslikV** [comment]
More details of the OpenShot's current behavior is here: https://github.com/OpenShot/openshot-qt/issues/3470#issuecomment-626324627 (different FPS is the case)

**Comment by ctsdownloads** [comment]
Make sure the resolution and frame rate in your OpenShot profile match your source video resolution and frame rate. The issue happens when there is a mismatch with your frame rates.
