### ISSUE TITLE
Undoing: after moving several clips at once on timeline, Undo moves them back one by one

### ISSUE THREAD

**Issue by guiljo** [OpenShot/openshot-qt#3498]
**Describe the bug:**
Undoing a move on the timeline only moves clips one by one, even when multiple clips were selected for the original move.

**Steps to reproduce the behavior:**
1. Select multiple clips on timeline
2. Move them somewhere else on the timeline
3. Undo

**Expected behavior:**
All clips should move back to their former location together.
Instead, only one clip moves at a time, and you have to undo as many times as the number of clips you had selected.

**System Details:**
- OpenShot Version: 2.5.1
- Operating System / Distro: Windows 10

**Comment by ctsdownloads** [comment]
Was able to replicate this on PCLinuxOS using the AppImage for OpenShot Version: 2.5.1 - this appears to affect multiple platforms.
