### ISSUE TITLE
Startup locks in Ubuntu 18.40

### ISSUE THREAD

**Issue by davidsinfield** [OpenShot/openshot-qt#3499]
I can't start OpenShot from Ubuntu 18.04. It was working fine yesterday.

The startup messages are below. It's been in this state for 30 minutes.

Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
      launch:INFO ------------------------------------------------
      launch:INFO    OpenShot (version 2.4.1)
      launch:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.4.1
         app:INFO libopenshot version: 0.1.9
         app:INFO platform: Linux-4.15.0-99-generic-x86_64-with-Ubuntu-18.04-bionic
         app:INFO processor: x86_64
         app:INFO machine: x86_64
         app:INFO python version: 3.6.9
         app:INFO qt5 version: 5.14.2
         app:INFO pyqt5 version: 5.14.2
    language:INFO Attempting to load qt_en_GB.UTF-8 in '/home/david/.local/lib/python3.6/site-packages/PyQt5/Qt/translations'
    language:INFO Successfully loaded qt_en_GB.UTF-8 in '/home/david/.local/lib/python3.6/site-packages/PyQt5/Qt/translations'
    language:INFO Attempting to load en_GB.UTF-8/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Attempting to load en/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Qt Detected Languages: ['en-GB', 'en']
    language:INFO LANG Environment Variable: en_GB.UTF-8
    language:INFO LOCALE Environment Variable: en_GB
    language:INFO Attempting to load qt_en_GB.UTF-8 in '/home/david/.local/lib/python3.6/site-packages/PyQt5/Qt/translations'
    language:INFO Successfully loaded qt_en_GB.UTF-8 in '/home/david/.local/lib/python3.6/site-packages/PyQt5/Qt/translations'
    language:INFO Attempting to load qtbase_en_GB.UTF-8 in '/home/david/.local/lib/python3.6/site-packages/PyQt5/Qt/translations'
    language:INFO Successfully loaded qtbase_en_GB.UTF-8 in '/home/david/.local/lib/python3.6/site-packages/PyQt5/Qt/translations'
    language:INFO Attempting to load qt_en_GB.UTF-8 in '/usr/lib/python3/dist-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load qt_en in '/usr/lib/python3/dist-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load qtbase_en_GB.UTF-8 in '/usr/lib/python3/dist-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load qtbase_en in '/usr/lib/python3/dist-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load en_GB.UTF-8/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Attempting to load en/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Exiting translation system (since we successfully loaded: en_GB.UTF-8)
project_data:INFO Setting default profile to HDV 720 24p
ZmqLogger::Connection - Error binding to tcp://*:5556. Switching to an available port.
ZmqLogger::Connection - Error binding to tcp://*:5556. Switching to an available port.
         app:INFO Setting font to /usr/lib/python3/dist-packages/openshot_qt/images/fonts/Ubuntu-R.ttf
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
         app:INFO Setting custom dark theme
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "/usr/bin/openshot-qt", line 11, in <module>
    load_entry_point('openshot-qt==2.4.1', 'gui_scripts', 'openshot-qt')()
  File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 70, in main
    app = OpenShotApp(sys.argv)
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 163, in __init__
    from windows.main_window import MainWindow
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/main_window.py", line 43, in <module>
    from windows.views.timeline_webview import TimelineWebView
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/views/timeline_webview.py", line 40, in <module>
    from PyQt5.QtWebKitWidgets import QWebView
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'
     metrics:INFO Track exception: [200] http://www.openshot.org/exception/json/ | *old-exception-ignored*
^C      logger:ERROR Exception ignored in:
      logger:ERROR <module 'threading' from '/usr/lib/python3.6/threading.py'>
      logger:ERROR Traceback (most recent call last):
      logger:ERROR   File "/usr/lib/python3.6/threading.py", line 1294, in _shutdown
      logger:ERROR t.join()
      logger:ERROR   File "/usr/lib/python3.6/threading.py", line 1056, in join
      logger:ERROR self._wait_for_tstate_lock()
      logger:ERROR   File "/usr/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
      logger:ERROR elif lock.acquire(block, timeout):
      logger:ERROR KeyboardInterrupt
david@bigserver:~$ openshot-qt
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
      launch:INFO ------------------------------------------------
      launch:INFO    OpenShot (version 2.4.1)
      launch:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.4.1
         app:INFO libopenshot version: 0.1.9
         app:INFO platform: Linux-4.15.0-99-generic-x86_64-with-Ubuntu-18.04-bionic
         app:INFO processor: x86_64
         app:INFO machine: x86_64
         app:INFO python version: 3.6.9
         app:INFO qt5 version: 5.14.2
         app:INFO pyqt5 version: 5.14.2
    language:INFO Attempting to load qt_en_GB.UTF-8 in '/home/david/.local/lib/python3.6/site-packages/PyQt5/Qt/translations'
    language:INFO Successfully loaded qt_en_GB.UTF-8 in '/home/david/.local/lib/python3.6/site-packages/PyQt5/Qt/translations'
    language:INFO Attempting to load en_GB.UTF-8/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Attempting to load en/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Qt Detected Languages: ['en-GB', 'en']
    language:INFO LANG Environment Variable: en_GB.UTF-8
    language:INFO LOCALE Environment Variable: en_GB
    language:INFO Attempting to load qt_en_GB.UTF-8 in '/home/david/.local/lib/python3.6/site-packages/PyQt5/Qt/translations'
    language:INFO Successfully loaded qt_en_GB.UTF-8 in '/home/david/.local/lib/python3.6/site-packages/PyQt5/Qt/translations'
    language:INFO Attempting to load qtbase_en_GB.UTF-8 in '/home/david/.local/lib/python3.6/site-packages/PyQt5/Qt/translations'
    language:INFO Successfully loaded qtbase_en_GB.UTF-8 in '/home/david/.local/lib/python3.6/site-packages/PyQt5/Qt/translations'
    language:INFO Attempting to load qt_en_GB.UTF-8 in '/usr/lib/python3/dist-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load qt_en in '/usr/lib/python3/dist-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load qtbase_en_GB.UTF-8 in '/usr/lib/python3/dist-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load qtbase_en in '/usr/lib/python3/dist-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load en_GB.UTF-8/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Attempting to load en/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Exiting translation system (since we successfully loaded: en_GB.UTF-8)
project_data:INFO Setting default profile to HDV 720 24p
         app:INFO Setting font to /usr/lib/python3/dist-packages/openshot_qt/images/fonts/Ubuntu-R.ttf
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
         app:INFO Setting custom dark theme
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "/usr/bin/openshot-qt", line 11, in <module>
    load_entry_point('openshot-qt==2.4.1', 'gui_scripts', 'openshot-qt')()
  File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 70, in main
    app = OpenShotApp(sys.argv)
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 163, in __init__
    from windows.main_window import MainWindow
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/main_window.py", line 43, in <module>
    from windows.views.timeline_webview import TimelineWebView
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/views/timeline_webview.py", line 40, in <module>
    from PyQt5.QtWebKitWidgets import QWebView
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'
     metrics:INFO Track exception: [200] http://www.openshot.org/exception/json/ | *old-exception-ignored*

**Comment by ctsdownloads** [comment]
Did you install this from a PPA or AppImage? Also, from Help>About OpenShot, what version are you running?

**Comment by davidsinfield** [comment]
The PPA from ppa:openshot.developers/ppa. I've purged and reinstalled. Still the same.

Versions as per the quoted comments above:

launch:INFO ------------------------------------------------
launch:INFO OpenShot (version 2.4.1)
launch:INFO ------------------------------------------------
app:INFO openshot-qt version: 2.4.1
app:INFO libopenshot version: 0.1.9
app:INFO platform: Linux-4.15.0-99-generic-x86_64-with-Ubuntu-18.04-bionic

**Comment by ctsdownloads** [comment]
Interesting. Go ahead and do a purge install, then try the AppImage. Run the AppImage in the terminal, see if the behavior is the same.

**Comment by davidsinfield** [comment]
A bit more info:

I let the load go on overnight and nothing happened when I Ctrl-C out of it I get:

    logger:ERROR Exception ignored in:
      logger:ERROR <module 'threading' from '/usr/lib/python3.6/threading.py'>
      logger:ERROR Traceback (most recent call last):
      logger:ERROR   File "/usr/lib/python3.6/threading.py", line 1294, in _shutdown
      logger:ERROR t.join()
      logger:ERROR   File "/usr/lib/python3.6/threading.py", line 1056, in join
      logger:ERROR self._wait_for_tstate_lock()
      logger:ERROR   File "/usr/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
      logger:ERROR elif lock.acquire(block, timeout):
      logger:ERROR KeyboardInterrupt

**Comment by ferdnyc** [comment]
@davidsinfield 

That message is normal for  PyQt application, the Qt event loop can't be broken out of with Ctrl+C. So it would seem to imply that OpenShot was in its normal running state. The process could be forcibly terminated, most likely.

The original issue you're seeing is because the PyQt5.QtWebKit module is missing on your system. That's installed in a separate package from the rest of PyQt5. I'm not sure of the exact name on Ubuntu, but if you do some `apt` searches for some combination of Python, Qt, and WebKit all in the same package, that's what you'd want to install to get OpenShot working.

**Comment by davidsinfield** [comment]
@ctsdownloads The appimage works!
@ferdnyc I tried installing the webkit widgets library wit sudo apt-get install libqt5webkit5-dev no luck. Exactly the same result. Happy to run from the appimage.

Thanks for your help chaps.

**Comment by ferdnyc** [comment]
> @ferdnyc I tried installing the webkit widgets library wit sudo apt-get install libqt5webkit5-dev no luck. Exactly the same result. 

From a quick Ubuntu package websearch, the package you'd want is python3-pyqt5.qtwebkit.

**Comment by ferdnyc** [comment]
(There are advantages to using an installed package. Primarily support for hardware accelerated encoding, which is completely non-functional in the AppImage.)
