### ISSUE TITLE
Titles can not be edited directly from OpenShot

### ISSUE THREAD

**Issue by jarlarntzen** [OpenShot/openshot-qt#35]
I do not know if this is how it's supposed to be but I can not open the title for editing - neither in Inkscape, nor in the OpenShot title editor.

Quite boo-hoo when you accidentally leave a typo in or just want to make som small adjustment. I do assume it would be possible to simply locate the title.svg on disk and edit it in Inkscape - it would just be so much smoother to **Right-click --> Edit in Inkscape** or similar directly on the title on the OpenShot timeline or _Project Files_ pane.

**Comment by jreynojustin** [comment]
OpenShot is now in Version 2.2 if you are still noticing issues in the latest version please re-open this issue letting us know.
