### ISSUE TITLE
How to get the tabs back

### ISSUE THREAD

**Issue by Charms2002** [OpenShot/openshot-qt#3503]
**Question:**
I have somehow managed to get rid of the image, video and audio tab, as well as the transition tabs and cant figure out how to get them back?

**System Details:**
- Operating System / Distro: Windows 10

![All in one mums  HD 720p 30 fps  - OpenShot Video Editor 20_05_2020 00_15_02](https://user-images.githubusercontent.com/65632299/82387513-27cb5980-9a2f-11ea-96e6-5b750a6a18fa.png)

**Comment by ferdnyc** [comment]
@Charms2002 

You can choose either "Simple View" or "Advanced View" from the View > Views menu to restore the interface to a standard layout.

**Comment by SuslikV** [comment]
Also, you may right-click over the tool-bar (right to the Big Red Button of export) or over the main menu and choose the dock pane you wish to show/hide from the list.

**Comment by ferdnyc** [comment]
Good point. I forgot about that, and it's less destructive if all you've done is accidentally closed a dock.

(If, OTOH, the dock is somehow "lost" in a way that prevents you from seeing or interacting with it even when it's enabled, the View options will always force everything back to a good state — but you'll lose _all_ of your layout customizations.)
