### ISSUE TITLE
Use Shotcut instead OpenShit because here are aggressive insolent not grateful hate you and close your threats to show you who is the boss here

### ISSUE THREAD

**Issue by easy-and-simple** [OpenShot/openshot-qt#3505]
Use Shotcut instead OpenShit, because here are aggressive, insolent, not grateful for your help, hate you and close your threats just to show you who is the boss here
Escape negative feeling that you will need to fill reporting Openshit bugs.
You not only will not get any gratitude for your help but will become object of bad attitude and aggression
Better go help positive and creative people who are happy and grateful for your help instead to poison your life with toxic attitude you get here

**Comment by jonoomph** [comment]
https://github.com/OpenShot/openshot-qt/wiki/Code-of-Conduct
