### ISSUE TITLE
When selecting a title to view, Openshot then crashes

### ISSUE THREAD

**Issue by RootUserSam** [OpenShot/openshot-qt#3506]
**Describe the bug**
A clear and concise description of the issue
After I have opened up Titles, I click on one of the title to look at it, and openshot crashes.
**Steps to reproduce the behavior:**
1. Go to Title Menu
2. Click on Title
3. Select a Title
4. Openshot crashes

**Expected behavior**
I should be able to click on a title and look at it.
**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Windows-10-10.0.18362
- Processor: AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1590022547-25ca2d0d-7cec1822-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/l14edy8zac0qf89ltj0h8j4lisx4ggmc/openshot-qt.zip) (23 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/l14edy8zac0qf89ltj0h8j4lisx4ggmc/libopenshot.zip) (2 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by ferdnyc** [comment]
@RootUserSam 

According to your logs you're using a fairly old version of OpenShot (2.4.4) -- I'd suggest downloading the latest 2.5.1 version from https://OpenShot.org/download/ and trying with that version.

It also looks like the autosave function is having trouble on your system, it might be a good idea to switch it off in the Preferences.

**Comment by RootUserSam** [comment]
That one that I reinstalled was the nightly version and I thought it was the 2.5.1 at least. I will turn off the autosave but I was getting that error on the 2.5.1 and I had followed the instructions to update (downgrade) to the nightly. As I said, I will reinstall, If I get the same error, I won't reinstall the nightly but I will attach the new log files. Thanks.

**Comment by RootUserSam** [comment]
the openshot file that I downloaded was: OpenShot-v2.5.1-dev2-1590022547-25ca2d0d-7cec1822-x86_64.exe

**Comment by RootUserSam** [comment]
I reinstalled this: OpenShot-v2.5.1-x86_64. I turned off autosave and when I tried to select a regular title, it crashed.
Here is the log file: 
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/4670779/openshot-qt.log)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/4670781/libopenshot.log)

**Comment by ferdnyc** [comment]
@RootUserSam 

Thanks for the logs. Unfortunately, as is often the case with crashes like this, there's nothing in the log to indicate why the crash might be occurring, or even that there is a crash. The log shows you entering the title editor, and then just stops. So, it's very difficult to determine why.

Here's something you could try. In the OpenShot install folder (probably `C:\Program Files\OpenShot Video Editor\` there should be another launcher `openshot-qt-cli.exe`. If you open a Command Prompt window and run OpenShot that way, you'll be able to see the messages printed while it runs, possibly including any crash messages.

So, you'd just want to run these two commands:

```command
CD "C:\Program Files\OpenShot Video Editor\"
openshot-qt-cli.exe
```

(I THINK that's the name, it might be `openshot-cli.exe`)

**Comment by RootUserSam** [comment]
Here is the output from openshot-qt-cli.exe: 
         app:INFO ------------------------------------------------
         app:INFO             Mon May 25 10:19:34 2020
         app:INFO               Starting new session
         app:INFO ------------------------------------------------
         app:INFO             OpenShot (version 2.5.1)
         app:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.5.1
         app:INFO libopenshot version: 0.2.5
         app:INFO platform: Windows-10-10.0.18362
         app:INFO processor: AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
         app:INFO machine: AMD64
         app:INFO python version: 3.7.4
         app:INFO qt5 version: 5.12.4
         app:INFO pyqt5 version: 5.12.3
    language:INFO Qt Detected Languages: ['en-US']
    language:INFO LANG Environment Variable:
    language:INFO LOCALE Environment Variable:
    language:INFO OpenShot Preference Language: Default
project_data:INFO Setting default profile to HD 720p 30 fps
         app:INFO Setting font to C:\Program Files\OpenShot Video Editor\images\fonts\Ubuntu-R.ttf
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
QMainWindow::addDockWidget: invalid 'area' argument
     metrics:INFO Track metric: [200] http://www.google-analytics.com/collect?cid=1f59537c-4072-462d-9c45-fb288bebca47&v=1&tid=UA-4381101-5&an=OpenShot+Video+Editor&aip=1&aid=org.openshot.openshot-qt&av=2.5.1&ul=en-us&ua=Mozilla%2F5.0+%28Windows+NT+10%3B+10.0.18362%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&cd1=0.2.5&cd2=3.7.4&cd3=5.12.4&cd4=5.12.3&cd5=Windows+10-10.0.18362--&t=screenview&sc=start&cd=launch-app | (35 bytes)
     metrics:INFO Track metric: [200] http://www.google-analytics.com/collect?cid=1f59537c-4072-462d-9c45-fb288bebca47&v=1&tid=UA-4381101-5&an=OpenShot+Video+Editor&aip=1&aid=org.openshot.openshot-qt&av=2.5.1&ul=en-us&ua=Mozilla%2F5.0+%28Windows+NT+10%3B+10.0.18362%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&cd1=0.2.5&cd2=3.7.4&cd3=5.12.4&cd4=5.12.3&cd5=Windows+10-10.0.18362--&t=screenview&sc=start&cd=launch-app | (35 bytes)
     ui_util:INFO Initializing UI for MainWindow
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
     metrics:INFO Track metric: [200] http://www.google-analytics.com/collect?cid=1f59537c-4072-462d-9c45-fb288bebca47&v=1&tid=UA-4381101-5&an=OpenShot+Video+Editor&aip=1&aid=org.openshot.openshot-qt&av=2.5.1&ul=en-us&ua=Mozilla%2F5.0+%28Windows+NT+10%3B+10.0.18362%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&cd1=0.2.5&cd2=3.7.4&cd3=5.12.4&cd4=5.12.3&cd5=Windows+10-10.0.18362--&t=screenview&cd=main-screen | (35 bytes)
files_listview:INFO currentChanged
files_listview:INFO updateSelection
 files_model:INFO updating files model.
transition_model:INFO updating transitions model.
     metrics:INFO Track metric: [200] http://www.google-analytics.com/collect?cid=1f59537c-4072-462d-9c45-fb288bebca47&v=1&tid=UA-4381101-5&an=OpenShot+Video+Editor&aip=1&aid=org.openshot.openshot-qt&av=2.5.1&ul=en-us&ua=Mozilla%2F5.0+%28Windows+NT+10%3B+10.0.18362%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&cd1=0.2.5&cd2=3.7.4&cd3=5.12.4&cd4=5.12.3&cd5=Windows+10-10.0.18362--&t=screenview&cd=main-screen | (35 bytes)
     version:INFO Found current version: {"openshot_version": "2.5.1"}
effects_model:INFO updating effects model.
 main_window:INFO foundCurrentVersion: Found the latest version: 2.5.1
properties_model:INFO updating clip properties model.
transition_model:INFO updating transitions model.
 files_model:INFO updating files model.
 main_window:INFO InitCacheSettings
 main_window:INFO cache-mode: CacheMemory
 main_window:INFO cache-limit-mb: 250
 main_window:INFO Creating CacheMemory object with 262144000 byte limit
preview_thread:INFO QThread Start Method Invoked
 main_window:ERROR Unhandled crash detected... will attempt to recover backup project: C:\Users\samue\.openshot_qt\backup.osp
preview_thread:INFO initPlayer
logger_libopenshot:INFO Timeline::SortClips (clips.size()=0.0000)
logger_libopenshot:INFO Timeline::GetFrame (requested_frame=1.0000, minimum_frames=2.0000, OPEN_MP_NUM_PROCESSORS=2.0000)
logger_libopenshot:INFO Timeline::GetFrame (processing frame) (frame_number=2.0000, omp_get_thread_num()=1.0000)
logger_libopenshot:INFO Timeline::GetFrame (Adding solid color) (frame_number=2.0000, info.width=1280.0000, info.height=720.0000)
logger_libopenshot:INFO Timeline::GetFrame (Loop through clips) (frame_number=2.0000, clips.size()=0.0000, nearby_clips.size()=0.0000)
logger_libopenshot:INFO Timeline::GetFrame (Add frame to cache) (frame_number=2.0000, info.width=1280.0000, info.height=720.0000)
logger_libopenshot:INFO Timeline::GetFrame (processing frame) (frame_number=1.0000, omp_get_thread_num()=0.0000)
logger_libopenshot:INFO Timeline::GetFrame (Adding solid color) (frame_number=1.0000, info.width=1280.0000, info.height=720.0000)
logger_libopenshot:INFO Timeline::GetFrame (Loop through clips) (frame_number=1.0000, clips.size()=0.0000, nearby_clips.size()=0.0000)
 main_window:INFO updateStatusChanged
 main_window:INFO updateStatusChanged
logger_libopenshot:INFO Timeline::GetFrame (Add frame to cache) (frame_number=1.0000, info.width=1280.0000, info.height=720.0000)
         app:INFO Process command-line arguments: ['openshot-qt-cli']
logger_libopenshot:INFO Timeline::GetFrame (end parallel region) (requested_frame=1.0000, omp_get_thread_num()=0.0000)
 main_window:INFO recover_backup
project_data:INFO Setting default profile to HD 720p 30 fps
logger_libopenshot:INFO Timeline::Close ()
preview_thread:INFO refreshFrame
     metrics:INFO Track metric: [200] http://www.google-analytics.com/collect?cid=1f59537c-4072-462d-9c45-fb288bebca47&v=1&tid=UA-4381101-5&an=OpenShot+Video+Editor&aip=1&aid=org.openshot.openshot-qt&av=2.5.1&ul=en-us&ua=Mozilla%2F5.0+%28Windows+NT+10%3B+10.0.18362%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&cd1=0.2.5&cd2=3.7.4&cd3=5.12.4&cd4=5.12.3&cd5=Windows+10-10.0.18362--&t=exception&exd=unhandled-crash-windows-PlayerPrivate%3A%3Arun+%28determine+sleep%29+&exf=1 | (35 bytes)
preview_thread:INFO self.player.Position(): 1
video_widget:INFO Load: Set video widget display aspect ratio to: 1.7777777910232544
video_widget:INFO Set video widget pixel aspect ratio to: 1.0
 main_window:INFO updateStatusChanged
logger_libopenshot:INFO Timeline::SortClips (clips.size()=0.0000)
logger_libopenshot:INFO Timeline::GetFrame (requested_frame=1.0000, minimum_frames=2.0000, OPEN_MP_NUM_PROCESSORS=2.0000)
logger_libopenshot:INFO Timeline::GetFrame (processing frame) (frame_number=2.0000, omp_get_thread_num()=1.0000)
logger_libopenshot:INFO Timeline::GetFrame (Adding solid color) (frame_number=2.0000, info.width=1280.0000, info.height=720.0000)
logger_libopenshot:INFO Timeline::GetFrame (Loop through clips) (frame_number=2.0000, clips.size()=0.0000, nearby_clips.size()=0.0000)
logger_libopenshot:INFO Timeline::GetFrame (Add frame to cache) (frame_number=2.0000, info.width=1280.0000, info.height=720.0000)
preview_thread:INFO onModeChanged
logger_libopenshot:INFO Timeline::GetFrame (processing frame) (frame_number=1.0000, omp_get_thread_num()=0.0000)
logger_libopenshot:INFO Timeline::GetFrame (Adding solid color) (frame_number=1.0000, info.width=1280.0000, info.height=720.0000)
logger_libopenshot:INFO Timeline::GetFrame (Loop through clips) (frame_number=1.0000, clips.size()=0.0000, nearby_clips.size()=0.0000)
logger_libopenshot:INFO Timeline::GetFrame (Add frame to cache) (frame_number=1.0000, info.width=1280.0000, info.height=720.0000)
preview_thread:INFO refreshFrame
preview_thread:INFO self.player.Position(): 1
properties_model:INFO Update item:
properties_model:INFO updating clip properties model.
logger_libopenshot:INFO Timeline::GetFrame (end parallel region) (requested_frame=1.0000, omp_get_thread_num()=0.0000)
logger_libopenshot:INFO VideoPlaybackThread::run (before render) (frame->number=1.0000, need_render=1.0000)
logger_libopenshot:INFO PlayerPrivate::run (determine sleep) (video_frame_diff=0.0000, video_position=1.0000, audio_position=1.0000, speed=0.0000, render_time=339.0000, sleep_time=-305.0000)
    timeline:INFO Adjusting max size of preview image: PyQt5.QtCore.QSize(908, 511)
preview_thread:INFO refreshFrame
preview_thread:INFO self.player.Position(): 1
logger_libopenshot:INFO Timeline::SortClips (clips.size()=0.0000)
logger_libopenshot:INFO Timeline::GetFrame (requested_frame=1.0000, minimum_frames=2.0000, OPEN_MP_NUM_PROCESSORS=2.0000)
logger_libopenshot:INFO Timeline::GetFrame (processing frame) (frame_number=2.0000, omp_get_thread_num()=1.0000)
logger_libopenshot:INFO Timeline::GetFrame (Adding solid color) (frame_number=2.0000, info.width=1280.0000, info.height=720.0000)
logger_libopenshot:INFO Timeline::GetFrame (Loop through clips) (frame_number=2.0000, clips.size()=0.0000, nearby_clips.size()=0.0000)
logger_libopenshot:INFO Timeline::GetFrame (Add frame to cache) (frame_number=2.0000, info.width=1280.0000, info.height=720.0000)
logger_libopenshot:INFO Timeline::GetFrame (processing frame) (frame_number=1.0000, omp_get_thread_num()=0.0000)
logger_libopenshot:INFO Timeline::GetFrame (Adding solid color) (frame_number=1.0000, info.width=1280.0000, info.height=720.0000)
logger_libopenshot:INFO Timeline::GetFrame (Loop through clips) (frame_number=1.0000, clips.size()=0.0000, nearby_clips.size()=0.0000)
logger_libopenshot:INFO Timeline::GetFrame (Add frame to cache) (frame_number=1.0000, info.width=1280.0000, info.height=720.0000)
timeline_webview:WARNING TimelineWebView::eval_js() called before document ready event. Script queued: $('body').scope().SetTrackLabel('Track %s');
logger_libopenshot:INFO Timeline::GetFrame (end parallel region) (requested_frame=1.0000, omp_get_thread_num()=0.0000)
timeline_webview:WARNING TimelineWebView::eval_js() called before document ready event. Script queued: $('body').scope().LoadJson({"type": "load", "key": "", "value": {"id": "96NR4EWC6V", "fps": {"num": 30, "den": 1}, "display_ratio": {"num": 16, "den": 9}, "pixel_ratio": {"num": 1, "den": 1}, "width": 1280, "height": 720, "sample_rate": 44100, "channels": 2, "channel_layout": 3, "settings": {}, "clips": [], "effects": [], "export_path": "", "import_path": "", "files": [], "duration": 300, "scale": 15, "tick_pixels": 100, "playhead_position": 0, "profile": "HD 720p 30 fps", "layers": [{"id": "L1", "label": "", "number": 1000000, "y": 0, "lock": false}, {"id": "L2", "label": "", "number": 2000000, "y": 0, "lock": false}, {"id": "L3", "label": "", "number": 3000000, "y": 0, "lock": false}, {"id": "L4", "label": "", "number": 4000000, "y": 0, "lock": false}, {"id": "L5", "label": "", "number": 5000000, "y": 0, "lock": false}], "markers": [], "progress": [], "version": {"openshot-qt": "0.0.0", "libopenshot": "0.0.0"}}, "partial": false, "old_values": {}});
logger_libopenshot:INFO VideoPlaybackThread::run (before render) (frame->number=1.0000, need_render=1.0000)
timeline_webview:WARNING TimelineWebView::eval_js() called before document ready event. Script queued: $('body').scope().setScale(15, 0);
logger_libopenshot:INFO PlayerPrivate::run (determine sleep) (video_frame_diff=0.0000, video_position=1.0000, audio_position=1.0000, speed=0.0000, render_time=42.0000, sleep_time=-8.0000)
timeline_webview:WARNING TimelineWebView::eval_js() called before document ready event. Script queued: $('body').scope().SetSnappingMode(1);
timeline_webview:WARNING TimelineWebView::eval_js() called before document ready event. Script queued: $('body').scope().SetFollow(1);
timeline_webview:WARNING TimelineWebView::eval_js() called before document ready event. Script queued: $('body').scope().MovePlayheadToFrame(1);
timeline_webview:INFO Qt Found!
timeline_webview:INFO $scope.Qt = true;
timeline_webview:INFO SetThumbAddress: http://127.0.0.1:51617/thumbnails/
timeline_webview:INFO SortItems
timeline_webview:INFO UpdateLayerIndex
timeline_webview:INFO UpdateLayerIndex
     ui_util:INFO Initializing UI for Dialog
titles_model:INFO updating title model.
     metrics:INFO Track metric: [200] http://www.google-analytics.com/collect?cid=1f59537c-4072-462d-9c45-fb288bebca47&v=1&tid=UA-4381101-5&an=OpenShot+Video+Editor&aip=1&aid=org.openshot.openshot-qt&av=2.5.1&ul=en-us&ua=Mozilla%2F5.0+%28Windows+NT+10%3B+10.0.18362%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&cd1=0.2.5&cd2=3.7.4&cd3=5.12.4&cd4=5.12.3&cd5=Windows+10-10.0.18362--&t=screenview&cd=title-screen | (35 bytes)
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src\libcore\option.rs:347:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Thanks.

**Comment by SuslikV** [comment]
Only _resvg_ (crash cause) requires _Rust_ library in OpenShot. Consider to use build that based only on Qt SVG renderer, like the one that is mentioned in: https://github.com/OpenShot/openshot-qt/issues/3439#issuecomment-624816230
