### ISSUE TITLE
Failed to load project file, invalid load key, '{'

### ISSUE THREAD

**Issue by nexos493** [OpenShot/openshot-qt#3508]
**Beschreiben Sie den Fehler**
Ein kürzlich abgespeichertes Projekt lässt sich in OpenShot nicht mehr öffnen, bei der Auswahl der gespeicherten Datei erscheint nur die Fehlermeldung: "Failed to load project file C:/Users/Benutzer/Urlaub Griechenland2.osp: invalid load key, '{'."

**Schritte zum Reproduzieren des Verhaltens**
1. Klicken Sie auf  'Datei'.
2. Klicken Sie auf 'Projekt öffnen...'
3. Klicken Sie auf doe Projektdatei 'Urlaub Griechenland2.osp' (3,65 MB)
4. Sehen Sie den Fehler
[Urlaub Griechenland2.zip](https://github.com/OpenShot/openshot-qt/files/4671935/Urlaub.Griechenland2.zip)

**Erwartetes Verhalten**
Öffnen des kürzlich abgespeicherten Projektes.

**Systemdetails**
- OpenShot Version: 2.5.1
- libopenshot Version:  0.2.5
- Platform: Windows-8.1-6.3.9600
- Processor: Intel64 Family 6 Model 61 Stepping 4, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['de-DE', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verifiziertes Problem exsitiert immer noch im Daily Build:  http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1590135874-2e3181fe-7cec1822-x86_64.exe

**Logdateien**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/1xltgjwk4rg1teieif28nrrn6psfkuq0/openshot-qt.zip) (5 KB)
- libopenshot.log: Datei zu klein oder leer (nicht hochgeladen)

**Ausnahme / Stapelverfolgung**
```No stacktrace found in log files```

**Bildschirmfotos** (Optional)
Wenn möglich, fügen Sie Screenshots zur unterstützenden Erklärung Ihres Problems hinzu. Sie können Screenshots einfügen,
indem Sie diese kopieren und auf Github einfügen oder durch Drag and Drop zur GitHub-Seite hinzufügen. Alle Bilder sind öffentlich zugänglich, posten Sie deshalb keine Screenshots die persönliche Informationen enthalten.

**Comment by SuslikV** [comment]
Project file is damaged. Repaired one:

about 59KB to download, CRC of the .zip archive MD5:AA403CB16A2529A730E0C795EAA24C93
[Urlaub Griechenland2_repaired.zip](https://github.com/OpenShot/openshot-qt/files/4672349/Urlaub.Griechenland2_repaired.zip)

Project damaged in _History_ section, bottom of the file filled with zeros.
File damage looks similar to the one reported in: https://github.com/OpenShot/openshot-qt/issues/3123

**Comment by SuslikV** [comment]
Please, consider that next may become useful for you:
1. Make backup copies during your work.
2. Try to disable auto-saving feature of OpenShot (main menu _Edit>Preferences>Autosave tab>Enable Autosave_) - it can overwrite files silently and if something happens... you may get damaged file.

**Comment by USATechDude** [comment]
Look in the Recovery folder for an earlier version of the project that was saved using Autosave.  In Windows, the path is 

C:\Users\_<USERNAME>_\.openshot_qt\recovery
