### ISSUE TITLE
Filenames are cuttet.. even if the column is long enough

### ISSUE THREAD

**Issue by xstable** [OpenShot/openshot-qt#351]
![screenshot_001_20160923](https://cloud.githubusercontent.com/assets/1778068/18782616/93fdfa1e-8187-11e6-85bc-f9a80a6864a3.jpg)

**Comment by xstable** [comment]
Version 2.1.0

**Comment by DylanC** [comment]
@xstable - Does this issue exist in the daily build or have you tried v2.3.4?

**Comment by DylanC** [comment]
@xstable - This issue is solved in the latest daily builds.
