### ISSUE TITLE
Do I have to install the .dll files needed ?

### ISSUE THREAD

**Issue by littlebugyang** [OpenShot/openshot-qt#3513]
**Question:**
I am building the openshot-qt on windows using PyCharm. Problems occurred when I was going to run the launch.py. It threw the ImportError: DLL load failed: 找不到指定的模块。

**System Details:**
- OpenShot Version [e.g. 2.4.3]: The latest version on develop branch
- Operating System / Distro: [Windows 10, 2004]

**Screenshots:** (Optional)
![image](https://user-images.githubusercontent.com/27143932/82891188-e7fcf880-9f7f-11ea-87d5-e4ac6438d126.png)
The picture above is the error message. The Chinese characters could be translated into "unable to find the specific module"

![image](https://user-images.githubusercontent.com/27143932/82891364-2db9c100-9f80-11ea-92d1-4379dfe7f8dc.png)
The picture above is the error given by PyCharm. I printed the sys.path before the code `main()`.

I try to analyse the dependency of _openshot.pyd, and the picture below is part of the result:
![image](https://user-images.githubusercontent.com/27143932/82891503-6ce81200-9f80-11ea-890d-5aeffaf4495b.png)

I try to find the QT5GUI.DLL, LIBPYTHON3.7M.DLL ... in `/c/msys64/mingw64/lib`, however I discovered that no `libpython3.7m.dll` but a `libpython3.7.dll.a`. How am I going to deal with this problems ? And there are some DLL I cannot find, should I just download them from the Internet and put them together ?

Thanks for your replies.

**Comment by SuslikV** [comment]
You need to build you own _libopenshot_ that uses same python and Qt dependencies to be able to "freeze" your own openshot-qt.

Something like this: https://github.com/OpenShot/libopenshot/wiki/Windows-Build-Instructions

**Comment by littlebugyang** [comment]
@SuslikV 
> You need to build you own _libopenshot_ that uses same python and Qt dependencies to be able to "freeze" your own openshot-qt.
> 
> Something like this: https://github.com/OpenShot/libopenshot/wiki/Windows-Build-Instructions

Thanks for your reply.

I did try to build my own libopenshot, following the instructions in the page you mentioned. But I didn't found anything in `C:\msys64\mingw64\lib\python3.7\site-packages\`, which really confused me. 

And I try to load openshot on **MSYS2**'s **MINGW64**:
```
$ python3
Python 3.7.5 (default, Oct 17 2019, 08:08:02)  [GCC 9.2.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import openshot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:/msys64/mingw64/python\openshot.py", line 15, in <module>
    import _openshot
ImportError: DLL load failed: 找不到指定的程序。
>>>
```
I am just .... quite confused.

**Comment by littlebugyang** [comment]
@SuslikV 

I've found the `.dll` files that's missing. They are all in the directory `/mingw64/bin`. I just realized that I only add `/mingw64/lib` to my searching paths.

Thanks for your help sincerely.

**Comment by SuslikV** [comment]
The destination path for the install was modified not long time ago (https://github.com/OpenShot/libopenshot/pull/469). Now it is configurable for both: libs and python bindings. With the _cmake_ path variables:
`-DCMAKE_INSTALL_PREFIX` and `-DPYTHON_MODULE_PATH`

**Comment by littlebugyang** [comment]
@SuslikV 
Thanks a lot. 
I just noticed that without `-DCMAKE_INSTALL_PREFIX` and `-DPYTHON_MODULE_PATH` some weird error messages just came out and stop the process. I managed to figure it out, but I didn't know the reason. Anyway, thanks for your help again.
