### ISSUE TITLE
titles leave lot of tmp* files in /tmp

### ISSUE THREAD

**Issue by aoloe** [OpenShot/openshot-qt#3518]
in /tmp i've been left with lot of files with a name that starts with "tmp".

their content shows that they are "previews" for the titles in my openshot project.

for each title there is a `tmp88b89d4_` and a `tmp88b89d4_.png` file.

could you please add a unique prefix (`/tmp/openshot-88b89d4_`) that would allow me to delete all those files in one go? (or put them in a subdirectory of `/tmp`?

(i had 858 files left there by openshot...)

**Comment by ferdnyc** [comment]
> (i had 858 files left there by openshot...)

Wow, that is... a _lot_. #3520 should eliminate that file pollution entirely.

**Comment by aoloe** [comment]
nice, thanks!
it's of course much better to avoid that tmp files lay around, rather than simply  rename them!

still, having had a look at the PR, i would have wished that you also set `prefix='openshot'`

```py
new_file, tmp_filename = tempfile.mkstemp(prefix='openshot', suffix=".png")
```

my `/tmp` still has a `tmpaddon` and a few `tmp-*.xpi` files that i don't know from where they originate and i don't dare deleting... (and they are the reason why i could not delete all `tmp*` at once...)
