### ISSUE TITLE
Changing time settings of sliced clips changes start point

### ISSUE THREAD

**Issue by bfragged** [OpenShot/openshot-qt#3521]
**Describe the bug**
When a clip that has been sliced multiple times, if you change the time settings on some of the created clips, it changes their start point.

**Steps to reproduce the behavior:**
1. Add a source clip to track one (using Mavic Mini 1080p 59.94fps footage)
2. Split the clip in 2 places, creating 3 clips
3. Change the time setting on the 1st and 3rd clip to 16x 
4. Move the clips so they are all directly after each other
5. Previewed video shows it starting at 16x, then slowing to 1x, then back to 16x at the end
6. Export video as 720p 59.94 fps
7. Created video runs at 16x for the 1st clip, 1x for the 2nd clip, but then will jump to a different point in the source clip for the 3rd clip

**Expected behavior**
The exported video should have the speed changes, but the footage should all be in order

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Windows-10-10.0.18362
- Processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1590565733-10ed4baa-7cec1822-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/w5x5itlgzuy5hnc5qgueeyg7x8cpbciw/openshot-qt.zip) (117 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by ctsdownloads** [comment]
Marked as a bug

**Comment by Saitodepaula** [comment]
I also have this problem, and there are many open issues describing this problem, if you search by "time" in the issues.
