### ISSUE TITLE
Can I export an audio clip

### ISSUE THREAD

**Issue by erynhopekb** [OpenShot/openshot-qt#3523]
**Question:**
In a video I'm working on I got a really great candid comment that I want to reuse in another project. Is it possible to export that piece of audio so I can reuse it elsewhere?

**System Details:**
- OpenShot Version 2.5.1
- Operating System Windows 10

**Comment by USATechDude** [comment]
In OpenShot, trim the video clip to the section that you want then click the **Export Video** button.  On the **Advanced** tab, in the **Advanced Options** section, set the **Export To**: field to **Audio Only**.  When you export the clip it will be an audio clip in a MP4 container (if you use the default export profile.  You can import the MP4 into Audacity then export the audio as a WAV, MP3 or OGG.

**Comment by erynhopekb** [comment]
Thank you!
