### ISSUE TITLE
transitions gets added twice, once with black starting frame, then the actual transition

### ISSUE THREAD

**Issue by Ryder17z** [OpenShot/openshot-qt#3525]
**Describe the bug:**
![image](https://user-images.githubusercontent.com/2000703/83104549-4a0d4900-a0b9-11ea-8bc3-3c181f1bb736.png)

The frame should not be black

**Steps to reproduce the behavior:**
Put a transition between two images, in this case Wipe left to right

**Expected behavior:**
Apply transition once, correctly.

**System Details:**
Windows 10 x64
OpenShot 2.5.1

Example of exported video with the issue:
https://www.dropbox.com/s/y4x6mn9qrxfpfsb/Untitled%20Project-1.mp4?dl=0

**Comment by SuslikV** [comment]
Clip should overlap for whole length of the Transition mask. The bottom of the Preview is black by default. You may place white image at the bottom Track (for full export length) to see how transitions works.

**Comment by Ryder17z** [comment]
still a bug because the effect is rendered twice

**Comment by SuslikV** [comment]
What you see is just:
1. Transition from black into the Clip until end of the Clip (wrong direction of the Transition - choose _Reverse Transition_ in the right-click menu over the placed transition).
2. Transition from black to the second Clip (and here transition is already in the middle, so left part of the second Clip is already shown).

To fix:
1. Overlap two clips for the length of the transition itself (you may place clips on different Tracks).
2. Place Transition over the intersection interval of the both Clips (on the top track if clips lies on different tracks).
3. Right-click over the placed Transition and click _Reverse Transition_ if you need to change direction (from/to).
