### ISSUE TITLE
Audio speed up when export video with surround 5.1

### ISSUE THREAD

**Issue by igorditerni** [OpenShot/openshot-qt#3527]
**Describe the bug:**
I have an audio WMV (the same happen with the audio in ac3 and ogg formats) in surround 5.1 and I want to put it in a video.
When I export the video setting the audio output to Surround 5.1, the result is a video with an audio speeded up faster 3x.

**Steps to reproduce the behavior:**
1. Insert a video and an audio surround 5.1.
2. Click on 'export video' and then on 'advanced'.
3. Go to the Audio tab and in audio channels change 'Stereo (2 channels)' to 'Surround (5.1 channels)'.
4. Export video.

**Expected behavior:**
I expect a video with an audio at the right speed and not seeded up 3x faster.

**System Details:**
- OpenShot Version 2.5.1-dev2: {{ log_context.openshot_qt_version }}
- Operating System / Distro: Windows 10

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.
Log files can be found in your HOME/.openshot_qt/ folder. Please compress or zip
the log files (as they can become quite large).

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please
attach a small snippet of the exception here, but please keep it as small as
possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them here, dragging-and-dropping into this form, or clicking below and loading
images saved to your computer. All images are public, so please don't post screenshots
containing personal information.

**Comment by SuslikV** [comment]
I think, the issue is known: https://github.com/OpenShot/libopenshot/issues/492

**Comment by igorditerni** [comment]
I searched for it but without results. :(

**Comment by SuslikV** [comment]
It is because the fault is in different section of openshot - in OpenShot's video/audio processing library. So, that's normal that you didn't found it.
