### ISSUE TITLE
Problem exporting project

### ISSUE THREAD

**Issue by diegomartinez0729** [OpenShot/openshot-qt#3528]
**Describe the bug:**
I have tried to export my project many times, with failure each time. I even got the latest daily build and tried with no success. I have even tried multiple settings for the resolution and type of video, as well as quality, to no avail. This is a 33 minute project with many edited video files, some mp3 snippets, and several pictures; and it would freeze at 4.4% each time.

**Steps to reproduce the behavior:**
1. Go to File
2. Click on Export
3. Choose setting
4. Click Export Video

**Expected behavior:**
After 2 hours or so, my video would finish exporting and I’d be able to find it at the designated location.

**Actual Behavior**
It would freeze the export at 4.4% each time, and after a while if I click somewhere, I will receive an alert from Windows saying that the program has stopped responding.

**System Details:**
- OpenShot Version 2.5.1
- Windows 10

This video took me weeks to edit, so I’d rather not have to delete anything too substantial.

**Comment by SuslikV** [comment]
The performed task may be demanding, try to wait for a 20 minutes or so. Is the progress moving forward? If it is stuck at some point - just look at same percentage on the Timeline (from whole export length) - maybe something can be simplified?

**Comment by diegomartinez0729** [comment]
I tried that and it ended up working! Thank you!

**Comment by HHalftone** [comment]
Same issue.
-OpenShot Version 2.5.1
-Windows 7
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/5564132/openshot-qt.log)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/5564133/libopenshot.log)

OpenShot has been working really well and I've put out 5 videos with it so far. A few of these have been really large files and performance with the app and my computer was just fine.

All of a sudden, today I'm trying to export a comparatively simple gameplay video and no matter what file type I try to export it as, it freezes at 50.8%

I have tried the following: 

-Exporting using a different file type
-Exporting using a different quality type
-Uninstalling the program and reinstalling it
-Uninstalling, removing all program files and logs and reinstalling

Finally, I uninstalled my current version of the app and installed the daily build and then got a popup error, stating “Sorry, there was an error exporting your video: Could not open or write file.”

So now I can't even get to 50.8% - I don't know what to do this is driving me insane :( 

I do have the openshot-qt file as well as the libopenshot file (attached)

If anyone can advise me on what to try next, it would be very much appreciated. I'm at such a loss and need to be putting out my next video this Sunday.

**Comment by damianperon** [comment]
@HHalftone leave it running... mine finished an hour later... not good UX though

**Comment by HHalftone** [comment]
@damianperon Left it all night, remained unresponsive unfortunately. I now seem to be able to export at 1080p about 50% of the time but it exports a total mess with audio off so I'm in the process of re-encoding all source files and re-editing the whole bloody thing.
