### ISSUE TITLE
Openshot is crashing when I try to open .ops project or when  I am trying to edit preferences

### ISSUE THREAD

**Issue by maritatowers** [OpenShot/openshot-qt#3531]
**Describa el problema**
A clear and concise description of the issue

**Pasos para reproducir el comportamiento:**
1. Ir a «..Abrir proyecto, escoger un archivo .ops guardado anteriormente  e inmediatamente aparece una ventana donde dice que open shot ha dejado de funcionar.»
2. Ir a editar/ preferencias e inmediatamente deja de funcionar

**Comportamiento esperado**
Esperaba que abriera normalmente el archivo que es extensión openshot. Estaba teniendo unos problemas con la previsualización, desinstalé y volví a instalar el open shot pero ya no puedo trabajar más con el

**Detalles del sistema**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Windows-10-10.0.18362
- Processor: Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['es-MX', 'es-ES', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1590749307-10ed4baa-7cec1822-x86_64.exe

**Archivos de registro**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/kf3unbo4nfsnmn8xsd6fd2pjllyikhru/openshot-qt.zip) (219 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/kf3unbo4nfsnmn8xsd6fd2pjllyikhru/libopenshot.zip) (2 KB)

**Excepción / Rastreo de pila**
```No stacktrace found in log files```

**Capturas de pantalla** (Opcional)
Si se aplica, añada capturas de pantalla para ayudar a explicar el problema. Puede incluir capturas
copiando y pegando en GitHub o arrastrando y soltando en la página de GitHub. Todas las imágenes
son públicas y por tanto no debería publicar capturas que contengan información personal.

**Comment by rauldipeas** [comment]
I had the same problem, solved deleting all the settings and getting a fresh start.

Running very well now.

**Comment by USATechDude** [comment]
As rauldipeas stated, try uninstalling OpenShot then deleting the settings folder from your system.  The folder is usually located in the following path: C:\Users\USERNAME\.openshot_qt.

Download a fresh copy of OpenShot from the website then reinstall the application.
