### ISSUE TITLE
when i add video on my timeline so it crash

### ISSUE THREAD

**Issue by blush-er** [OpenShot/openshot-qt#3532]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 2.5.1
- libopenshot Version:  0.2.5
- Platform: Linux-5.6.0-kali2-amd64-x86_64-with-Kali-kali-rolling-kali-rolling
- Processor: 
- Machine: x86_64
- Python version: 3.4.3
- Qt5 version: 5.2.1
- PyQt5 version: 5.2.1
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: en_US.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1590749213-10ed4baa-7cec1822-x86_64.AppImage

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/qo1wvyobt6kqqscxkxcz9d4k8zac5sir/openshot-qt.zip) (254 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/qo1wvyobt6kqqscxkxcz9d4k8zac5sir/libopenshot.zip) (396 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by ctsdownloads** [comment]
Thanks for the details thus far, however:

> Expected behavior
> A clear and concise description of what you expected to happen.

We need to know what you're actually trying to do when the error happens.
1) Go to what? Click on what, specifically? We have to be able to replicate this to help or at least have an idea of what is taking place.
2) Your system details information is outstanding, thank you.
3) An example of what we need: "Created project, imported video, moved video, click preview the video clip, error happened." That level of detail helps us to help you.

**Comment by blush-er** [comment]
Actually when i  drag video on timeline section from imported section, that
time error occurs(software crash).
2: this error occur when i create project.
3 : below is a screen recording what error actually happens. You should
also see this 👇
