### ISSUE TITLE
Rendering of title with Tamil font appears squeezed and unreadable

### ISSUE THREAD

**Issue by AshokR** [OpenShot/openshot-qt#3534]
**Describe the bug:**
When I create a title with Tamil font, OpenShot creates the SVG file correctly, but it doesn't render it correctly

**Steps to reproduce the behavior:**
1. Go to 'Title'. 'Titles' dialog opens.
2. Click on 'Change Font' button.
3. In Writing System select 'Tamil'.
4. Select any font, say, 'Latha'.
5. In 'Line 1:' enter 'பொறியியல்'.
6. The title rendered appears squeezed and unreadable. However, when I open the created .svg file in Inkscape it looks good. 

**Expected behavior:**
I expected the Tamil font to be rendered correctly.

**System Details:**
- OpenShot Version 2.5.1
- Operating System / Distro: Windows 10

I looked at the following font related issues, but they are not of much help:
[Fonts do not* show correctly #3384](https://github.com/OpenShot/openshot-qt/issues/3384)
[Unable to change Title font and size #2324](https://github.com/OpenShot/openshot-qt/issues/2324)
[Can't edit title font #2069](https://github.com/OpenShot/openshot-qt/issues/2069)

**Screenshots:** (Optional)
1. Screenshot of incorrectly rendered Tamil text.
2. I am unable to upload the correct .svg file created by OpenShot because that file type is not supported by GitHub.
![Poriyiyal](https://user-images.githubusercontent.com/760007/83355998-ac4b9f80-a380-11ea-841d-da50ada767f5.png)

**Comment by SuslikV** [comment]
Try other builds that uses Qt only renderer for `.svg` files (instead of `resvg` lib): https://ci.appveyor.com/api/buildjobs/m6l96dy7rxea7i62/artifacts/OpenShot-v2.1.0-1663-g13a49ae4-win-x64-N498.7z This may work better. The link will not be valid for long.

**Comment by ctsdownloads** [comment]
Reached out to the op for this issue to see if they're willing to help with out [translation for Tamil](https://translations.launchpad.net/openshot/2.0/+lang/ta). This is a confirmed issue.

**Comment by AshokR** [comment]
> Try other builds that uses Qt only renderer for `.svg` files (instead of `resvg` lib)

This build works like a charm! Thanks a lot for the super fast response. நன்றி!

**Comment by msravi16** [comment]
I faced the same issue in Kannada language on my Mac and Ubuntu 14 operating systems. 
However, when I install old version of openshot 1.4.3-1.1 from Ubuntu Software Center it worksfine.  
@SuslikV could you please share me the build for Mac or Ubuntu. If you share me the steps to build to (Qt only renderer for .svg) I willtry to build myself.

**Comment by SuslikV** [comment]
@msravi16 unfortunately, I set up only Windows build on AppVeyor. The building is not that simple. General steps are here: https://github.com/OpenShot/libopenshot/wiki/Linux-Build-Instructions then you need to run the `openshot-qt` with this lib used as dependency. Maybe @ferdnyc knows more about. Right now, I see no way to select the `SVG` format renderer library for OpenShot on the fly.

During compilation, next key in CMAKE file controls if _libopenshot_ will use _resvg_ lib for the rendering. 1 = _resvg_ enabled (if found), 0 = _Qt_ enabled (or variable not defined, if _resvg_ was not found):
https://github.com/OpenShot/libopenshot/blob/782d764c68f5c805a79583d5140484c16ffdc9eb/src/CMakeLists.txt#L361

**Comment by SuslikV** [comment]
@msravi16 as workaround you may try to convert all `.svg` files to `.png` by Inkscape before importing them into OpenShot. Converting to paths also should work OK. Text will be non-editable in both cases.

**Comment by msravi16** [comment]
@SuslikV Thank you very much for quick reply.

1. I installed your above windows build, all the regional fonts started working fine. For next couple of weeks I will use the windows version. Once this re-svg is fixed in openshot general release, I will start new version again.
2. Exporting to .png from inkscape and then re-importing will be time consuming, so it will better to use your above windows version.
3. As you pointed out building openshot-qt is very difficult, I will give a try and update you if it goes well
