### ISSUE TITLE
No Audio At All

### ISSUE THREAD

**Issue by mdisante** [OpenShot/openshot-qt#3535]
I had version 2.4.4 installed and it was working fine. Top right-hand corner of screen showed that an update was available so I downloaded and installed version 2.5.1. As soon as it was installed and I launched openshot, I had no audio whatsoever - not a peep. This has been verified with the latest 64-bit Windows daily build.

**Steps to reproduce the behavior:**
1. Clear install and install version 2.4.4 - everything works as expected.
2. Upgrade to version 2.5.1 (including daily build) and reopen the same project. Now there is no audio.

**Expected behavior**
I expected things to work as they had in version 2.4.4.

**System Details**
- OpenShot Version: 2.5.1
- libopenshot Version:  0.2.5-dev2
- Platform: Windows 10 Home (x64) Version 1909 (build 18363.836)
- Processor: 2.70 gigahertz Intel Core i7-6820HK
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: 2.5.1-dev2-1590749307-10ed4baa-7cec1822-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/iiwzht2dn82qyszcygxmezt5zix0vbd8/openshot-qt.zip) (221 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
N/A - there is no indication of any issue on the screen. It all appears to be working but there is no sound.

**Comment by SuslikV** [comment]
Main menu: _Edit>Preferences>Preview tab>Playback Audio Device_ - check if all was set correctly. 

Exported file has sound?

**Comment by mdisante** [comment]
Yes sir, I checked all of the settings in preferences and they were the same as in version 2.4.4 where the audio works fine:

 

Default Profile                                  HD 720p 30 fps

Playback Audio Device                   Default

Default Audio Sample Rate           44100

Default Audio Channels                  Stereo (2 Channel)

 

I have not tried exporting the file in 2.5.1. I did so in 2.4.4 and the output file has audio.

 

Really, I have no idea why it should suddenly stop working.

 

I have 4TB of local storage, all SSD.

I have 48GB of RAM.

I have a Core i7 CPU of recent vintage.

 

The only thing I could think of is it might be the chip set on my mother board (MSI laptop).

 

I have reinstalled 2.5.1 and am retrying the export to see if there is audio in VLC…

 

No, using 2.5.1 there is no audio in the exported file either.

 

Please advise if any additional info is needed.

**Comment by mdisante** [comment]
I have attached a Belarc Advisor dump of my laptop hardware and software to assist with the examination.

**Comment by SuslikV** [comment]
Is the Volume level changes in Windows when application is running?

**Comment by mdisante** [comment]
The system sounds work normally and I double checked the mixer. All are at 100%.

**Comment by SuslikV** [comment]
I cannot reproduce this issue on my end.

1) And really, you should try to export video and play it back, to make sure that the sound actually works and exported just fine. If not - there was similar issue reported before... without actual solution. I will link it here then, just for tracking.

2) As workaround, you may try to unpack this custom Windows (x64) build of the OpenShot v2.5.1-dev2:
https://ci.appveyor.com/api/buildjobs/wlfn4elxc47agn94/artifacts/OpenShot-WYH-v2.1.0-1739-g5f694ff9-win-x64-N542.7z
to any new folder on your PC. This ensures that all files are updated. Then run `openshot-qt.exe` from the unpacked folder.
The link will not be valid for long. CRC of the 7z archive above is MD5:E1C197E3F4DE183EF10C2EFF9D3F00A8 (about 111 MB to download).

    The build includes all my own PRs, so it a bit ahead of the base project. Thus, OpenShot's project files created in this version may loose some features if they will be used in the regular OpenShot.

3) If this doesn't help, try to run `openshot-qt-cli.exe` from the official build and copy whole output to new `.txt` file. This may help to developers to find the bug (if there any).

**Comment by mdisante** [comment]
I downloaded and unpacked the 2.5.1-dev2.7z version and exported the video where the preview had no sound. The exported file also had no sound. Both of these functions worked fine with version 2.4.4.

 

I have attached the logging output from the cli version in the file temp.log.

 

Please advise if you need me to try anything else.

 

Thanks,

Mike DiSante

**Comment by mdisante** [comment]
I am not sure if this is related. My PC has a Nvidia GTX970 video card but I am unable to see it when I go to the performance tab of Preferences.

 

Silly question… Are you running windows or linux on your end? If you are running Windows, what does your hardware look like? Then I check for any key differences.

 

Thanks,

Mike

**Comment by SuslikV** [comment]
You send your log-file to nowhere. Time to open `github.com` and forget to respond to mail notifications directly.

**Comment by mdisante** [comment]
Okay, here is the log file:
[temp.log](https://github.com/OpenShot/openshot-qt/files/4718372/temp.log)

**Comment by mdisante** [comment]
Hopefully I did not close the

**Comment by mdisante** [comment]
Okay, I replied on Github and attached the log file. Please advise if I can do anything else.

**Comment by SuslikV** [comment]
I think, the problem described in this log strings:
```
[SWR @ 000002517225b1c0] Input channel count and layout are unset
[SWR @ 000002517225b1c0] Context has not been initialized
```
this is untypical for the OpenShot. This is sound initialization for the imported file.

What is special with your input file? How many tracks (streams) it has and in which order?
Right now OpenShot looks for the video stream in track 0 and audio in the track 1. Everything else may fail. If the input file can be remuxed to this simple configuration, please give it a try.

I think, the problem is in the file specific - OpenShot should able to read number of regular media files, but the ones that has some "special" format.

**Comment by mdisante** [comment]
Okay, I misunderstood then. I have constructed my edited video in track 5. Tracks 1 thru 4 are unused. I will try moving the video from track 5 to track 1 (or zero if available).

**Comment by mdisante** [comment]
The input file is a standard mkv file that plays properly in vlc and could be handled with no issue in the previous (2.4.4) version of OpenShot. So, I am confused; is it an issue with the 2.5.1 version of OpenShot or is there an issue with the file that the 2.4.4 version was able to tolerate???

Also, which track is supposed to be used for what? By default the first track presented is track 5 with the bottom-most being track 1. I have always constructed my finished video in track 5 as it was the most convenent. Am I doing this wrong?

Please advise. Thanks.

**Comment by SuslikV** [comment]
Right now developers started cleanup of the code, so no changes will be made that can solve your issue in a near by future. Either use old version or use workarounds or try other software. Not much you can do with.

By "track" I mean the file streams (not OpenShot's Tracks). Each file may has a number of streams: video, audio, subtitles, gps info etc. The position (mapping) of this streams in the file has value. The OpenShot's internal library, not so long time ago, started to use some HW accelerations for linux systems, thus code that handles file reading was changed. Maybe this causes some difficulties to your setup. Regression is quite possible. To be able to reproduce the issue on developer's end - small file sample is needed. But don't expect any fast response as I said earlier.

Example of the lossless streams management by FFmpeg is here: https://github.com/OpenShot/openshot-qt/issues/3302#issuecomment-601387671

**Comment by mdisante** [comment]
Ok, I understand completely. For now, I will use version 2.4.4. Would it be possible to send me a message when you think there is a newer version for me to try. If not, I understand.

 

Thank you for all of your time and assistance, I really understand that it is a royal pain in the butt.

 

Sincerely,

Mike DiSante
