### ISSUE TITLE
animated titles build Tutorial

### ISSUE THREAD

**Issue by brcisna** [OpenShot/openshot-qt#3540]
Hello All,

Debian Bullseye 11 , Openshot-2.5.1_dev2 from source 

Would it be possible for someone to do a very basic animated title build tutorial with blender? Reason asking is I have built a few Blender scenes for animated text & when i place these into the same directory as the other .blend files they are never recognized by Openshot. 
One obvious thing i see mine are missing compared to the supplied animated titles is a 'title' for each scene. Just a wild hunch that this cannot show a title to preview in Openshot gui,> animated titles preview box.?
The ones have built run fine in Blender of course but simply are not recognized by OpenShot for some reason.

Thank You

**Comment by ctsdownloads** [comment]
Are you talking about using the Animated Title feature in OpenShot or actually opening Blender, saving a Blender project (not using OpenShot yet), then importing a Blender project file into OpenShot?

**Comment by brcisna** [comment]
Hi Matt,

Yes, My problem is,,I get the animated text built in blender ,,tried saving
these .blend files in the premade .blend folder directory of OpenShot but
when opening Openshot the newly added animated tiles are never able to be
seen in Openshot preview in the animated titles preview box to use?
I am not sure what i am missing for these animated tiles (.blend files)  to
be recognized by Openshot.

Thank You
