### ISSUE TITLE
Installed 2.5.1 and it is says it is 2.4.3

### ISSUE THREAD

**Issue by irthomasthomas** [OpenShot/openshot-qt#3541]
Hello, I am a new openshot user. I just downloaded and installed OpenShot-v2.5.1-x86_64.appimage but it says there is a new version available and when I checked Help> About it says it is version 2.4.3 and informs me there is an update available.

Any ideas?

Regards, Thomas

**Comment by brcisna** [comment]
irthomasthomas 

Thomas ,

If you are on Linux,, you are actually launching the 'native' Openshot that ships with your distro.
The Appimage (that you downloaded) when it launched should have asked if you wanted to create a desktop shortcut. If you look thought your start menu items,,you should see two Openshot shortcuts( providing your chose to create a shortcut icon) for the newly downloaded Appimage when you lanched it.
