### ISSUE TITLE
Bug during export : clip effects displaying at the end of video is not correct

### ISSUE THREAD

**Issue by jerome25000** [OpenShot/openshot-qt#3543]
I have a project lasting about 7 minutes with many photos inside.
I copied / pasted for all the photos the same effects : zoom and fading (with the copy / paste feature).
For the last photos in the movie, these effects (zoom, fading) is buggy : photo are black, not displayed.
If I remove the effects for the last photos, ok all is displayed.

It seems copy/paste has the problem for the latest photos when generating the movie ??

**Comment by ctsdownloads** [comment]
Need additional information. 

- Operating system/version.

- Which version of OpenShot (assuming the latest)

- What is the resolution of the OpenShot profile you're using? 

- Have you tried duplicating this by rendering at a lower resolution?

**Comment by jerome25000** [comment]
Operating system/version : Windows 10
Which version of OpenShot (assuming the latest) : Latest version (2.5.1)
Exporting to mp4 full hd average quality
No not tried at a lower resolution

But seems the copy / paste (keys) has a problem.
