### ISSUE TITLE
Audio blip at start of preview

### ISSUE THREAD

**Issue by rexdk** [OpenShot/openshot-qt#3544]
*Open new Openshot project.
*Add an mp3 to the timeline
*Preview - there is no audio blip
*Stop the preview once the mp3 audio has started
*Preview from start - this time there is a blip of sound, from where the mp3 audio left off

Openshot 2.5.1
Win10

Presumably an audio buffer needs to be flushed.

Not a disaster, but disconcerting if you're making a music video.

**Comment by spaetz** [comment]
Yep, I have been noticing this one too on 2.5.1. It is not in the export 'just' in the preview....

**Comment by rexdk** [comment]
Agreed - it's  just in the preview,; no problem in the exported video

**Comment by lah5577** [comment]
I have had it happen not only in the preview, but also when exported.  The source file coming into Openshot was a mp4 that I recorded with OBS.  The audio blip does not show in the waveform.  I agree, it seems to be a buffering issue, because the blip is audio from wherever I left off on the previous playback.  The beginning of this file has a blip that is actually the audio from around the 10 second mark. https://www.youtube.com/watch?v=-OcqFprCGbw&t=20s.

For the experts here, should I try and roll back a version and then export?  One of the previous comments leads me to believe the problem started with 2.5.1.

Openshot 2.5.1
Windows 8.1

**Comment by rexdk** [comment]
I'm not an expert, but I wonder what happens of you load the project from scratch, and export it *before* you try any preview.

Also, when you do preview, is the audio blip always the same snip. or is it a snip from wherever you left off the preview (the latter is the thing I've seen)

**Comment by lah5577** [comment]
rexdk,

Those were good suggestions, so I've played with that a bit today.  I have exported the video twice, once as you suggested, doing an export immediately after opening the project file, the other after previewing it and stopping playback approx. half-way through the video.  In both instances, the audio blip at the beginning is that same blip that is from around the 10 second mark of the video.

This behavior does seem to be different than the issue during preview.  In preview I experience the same behavior as you mention, the blip is related to where I previously stopped playback.

**Comment by rexdk** [comment]
@lah5577 Ok, so the export issue looks different I think - possibly even unique to your set up. All I can do is suggest a few tests to try to pin it down some more:
(assuming I've understood correctly that your audio file, recorded in OBS, is in mp4 format)
have you tried importing the mp4 audio into eg Audacity and exporting as an mp3, then using that mp3 (it might be that particular file)
have you tried 'separating' the audio mp4 (right click menu on the clip) - then discarding the video (which is presumably blank).
does it happen with an entirely different audio clip in maybe mp3 format
does it happen if you remove the video and just export the audio
does it happen with a different profile

I'd guess there aren't too many Win 8.1 systems now (I do have one myself somewhere) so maybe it is just on that platform. Doesn't seem likely though.

Just trying to find a fix for you....

**Comment by gwestwood** [comment]
I've had this happen on Windows 10 with OpenShot 2.5.1 too, in both preview and export as described.  To make sure it doesn't happen on Export I now close and then reopen OpenShot before I export.
