### ISSUE TITLE
Adding Transitions or Effects in Windows Version

### ISSUE THREAD

**Issue by USATechDude** [OpenShot/openshot-qt#3546]
**Describe the bug:**
When I try the first time to add a transition to the timeline, I can only apply common transitions.  All other transitions are denied.  I can keep adding common transitions to the timeline until I select an extra transition.  After selecting an extra transition I cannot add any transition or effect to the timeline.

**Steps to reproduce the behavior:**

1. Create a new project 
2. Import three clips to the Project Files list
3. Add a clip to the timeline 
4. Move the playhead to the end of the clip 
5. Add another clip to the timeline
6. Move the playhead back one second on the first clip
7. Drag the second clip to the playhead overlaying the end of first clip
8. Select the default Fade transition and remove it from the timeline
9. Click on the Transitions tab of the Project Files window
10. Click one of the common transitions and drag it to the timeline
11. Edit the Properties of the transition
12. Click on the Effects tab of the Project Files window
13. Click and drag one of the Effects to the clip on the timeline
14. Edit the Properties of the Effect
15. Move the playhead to the end of the second clip
16. Add the last clip to the timeline
17. Move the playhead back one second on the first clip
18. Drag the second clip to the playhead to create the default Fade transition
19. Select the Fade transition and remove it from the timeline
20. Click on the Transitions tab of the Project Files window
21. Click on a transition other than the common transitions and drag it to the timeline
22. ***ERROR*** OpenShot will no longer add any transition or any effect to the timeline

**Expected behavior:**
I should be able to select any of the transitions and add them to my timeline, not just the common transitions.  After selecting an extra transition, I should be able to add any transition or effect to the clips on the timeline.
These issues do not occur in the Linux AppImage on Ubuntu 20.04 LTS
These issues do not occur in the stable version for Windows 

**System Details:**
- OpenShot Version: OpenShot-v2.5.1-dev2-1591067614-782d764c-7cec1822-x86_64.exe
- Operating System / Distribution: Windows 10 Version 2004

**Comment by nanohtpc** [comment]
similar to bug 3401, and it has almost 2 months old!!!!

**Comment by USATechDude** [comment]
I can convert an extra transition (i.e.: dissolve.jpg) to an SVG file then copy it to the 
`/OpenShot Video Editor/transitions/common `
folder and use it in OpenShot and not affect other transitions, effects or emojis.

**Comment by USATechDude** [comment]
After reading Issue #3401 I edited the file:

`C:\Program Files\OpenShot Video Editor\classes\app.py`

Using Notepad++, I commented out line 110 and restarted OpenShot then ran through the procedures I listed in my Issue.

I am now able to use any transition, effect or emoji.  However, this will only last until I install a new version.  Then I have to modify the file again.

**Comment by jonoomph** [comment]
So, this is a super weird bug:

Here is the error when dropping a transition on the timeline when `self.setWindowIcon(QIcon(":/openshot.svg"))` is present in `app.py`:
```
timeline_webview:INFO addTransition...
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "C:\Program Files (x86)\OpenShot Video Editor\windows\views\timeline_webview.py", line 2802, in dragEnterEvent
    self.addTransition(data, pos)
  File "C:\Program Files (x86)\OpenShot Video Editor\windows\views\timeline_webview.py", line 2907, in addTransition
    transition_reader = openshot.QtImageReader(file_ids[0])
  File "C:\Users\Administrator\builds\7546b651\1\OpenShot\openshot-qt\openshot.py", line 2503, in __init__
RuntimeError: File could not be opened.
     metrics:INFO Track exception: [200] http://www.openshot.org/exception/json/ | *failed-recording-exception*: Control/space characters not allowed (key=b':1:Windows-2.5.1-dev2-RuntimeError: File could not be ')
```
And when `self.setWindowIcon(QIcon(":/openshot.svg"))` is removed from `app.py`, everything works fine, and the transition is added.

@ferdnyc, I'm not sure why we need the `self.setWindowIcon(QIcon(":/openshot.svg"))` command, and considering it breaks on Windows, I'm going to remove that unless you want to do some debugging yourself.

**Comment by jonoomph** [comment]
This is fixed in the latest daily build: https://www.openshot.org/download#daily.
