### ISSUE TITLE
errores al exportar, al pre visualizar y auditivos

### ISSUE THREAD

**Issue by MaicolFA** [OpenShot/openshot-qt#3548]
**Describa el problema**
errores al exportar, al pre visualizar y auditivos

**Pasos para reproducir el comportamiento:**
1 exportar
2 exportando
3 exportado
4 veo el vídeo y en alguna partes aparecen números, en otras no aparece nada (errores al exportar, visualizar y en audio)

**Comportamiento esperado**
Una descripción clara y concisa de lo que esperaba que sucediera.
tiene que aparecer todo correcto como cuando uno lo previsualiza

**Detalles del sistema**
- OpenShot Version: 2.5.1
- libopenshot Version:  0.2.5
- Platform: Windows-10-10.0.19041
- Processor: x86 Family 6 Model 42 Stepping 7, GenuineIntel
- Machine: x86
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['es-ES', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Skipped this step

**Archivos de registro**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/tcu84cw398ryq5i0twb09erl2lfugg9z/openshot-qt.zip) (144 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/tcu84cw398ryq5i0twb09erl2lfugg9z/libopenshot.zip) (0 KB)

**Excepción / Rastreo de pila**
```No stacktrace found in log files```

**Capturas de pantalla** (Opcional)
Si se aplica, añada capturas de pantalla para ayudar a explicar el problema. Puede incluir capturas
copiando y pegando en GitHub o arrastrando y soltando en la página de GitHub. Todas las imágenes
son públicas y por tanto no debería publicar capturas que contengan información personal.

**Comment by USATechDude** [comment]
Check the properties of the clip to see if the Frame Number property has a value of Clip or Timeline.  If so, reset the value to None.

**Comment by MaicolFA** [comment]
pasa varias veces con los archivos png o algunas imagenes, cuando ya queda
exportado uno mira el video y aparece en negro, y otra cosa, nesecita mucha
mas optimizacion y que los objetos en las ventanas se pueden ajustar al
tamaño que uno quiera o se vean mas pequeños

**Comment by ctsdownloads** [comment]
Understanding how it happens. Did you try the suggestion above?
