### ISSUE TITLE
GPU support for intel shared GPU

### ISSUE THREAD

**Issue by darkRaspberry** [OpenShot/openshot-qt#3549]
**Describe the new feature:**
GPU is not supported for intel UHD XXX shared one. Please provide support. As render takes very much large time to process the video only through the CPU.

**Describe the solution you'd like:**
Provide support for windows GPU. Including shared GPU in windows (Intel UHD XXX)

**Describe alternatives you have considered:**
NOPE

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your request.

**Comment by ctsdownloads** [comment]
Thanks for the report. GPU enhancements in OpenShot are highly experimental. Added as an enhancement request.
