### ISSUE TITLE
Distored audio in 2.0.7

### ISSUE THREAD

**Issue by jbrid** [OpenShot/openshot-qt#355]
I am experiencing distorted audio in version 2.0.7. 
If I use the same audio and video files in a project in 1.4.3, I do not experience this issue.

Sample:
https://www.youtube.com/watch?v=pYJ1SBrt_yg

Ubuntu 16.04.1 LTS
4.7.0-040700-generic
OpenShot 2.0.7

**Comment by JtLively** [comment]
Have you compared the audio export info settings? Something doesn't seem right as the highest quality setting for the YouTube video is 480.

**Comment by jbrid** [comment]
It is not a problem with export. The audio problems also exist during preview.

**Comment by edwin-oetelaar** [comment]
I can confirm this : also it is not a problem of youtube, the mp4 file sounds bad in vlc too.
I have tried resampling all audio to the same rate (48000) and using it, but it makes no difference.
View here : https://www.youtube.com/watch?v=uvZDinEtTmo
I am using Ubuntu.
This problem did not exist some time ago, I made a movie the same way, with good audio.


Linux oet-desktop 3.13.0-100-generic #147-Ubuntu SMP Tue Oct 18 16:48:51 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
sudo add-apt-repository ppa:openshot.developers/ppa

My cpu spec :  cat /proc/cpuinfo 
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 26
model name	: Intel(R) Core(TM) i7 CPU         950  @ 3.07GHz
stepping	: 5
microcode	: 0x16
cpu MHz		: 1596.000
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 11
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 popcnt lahf_lm ida dtherm tpr_shadow vnmi flexpriority ept vpid
bogomips	: 6216.14
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual

**Comment by JtLively** [comment]
@edwin-oetelaar The only issue I heard was that the music level was much higher than your voice, all which can be modified in the audio tab of each video and audio section. If the audio is losing quality, I'd suggest ensuring A/V files match the project file settings.

**Comment by edwin-oetelaar** [comment]
Thanks for your reply. I have worked around the issue by changing the encoding-settings, sample frequencies, frame-rates and the project-profile. I have not changed any settings with regard to sound levels or clips. The result can be found here. 
I changed so many things before it worked I am not sure what made the difference in the end.

This is the file with problem : https://www.youtube.com/watch?v=uvZDinEtTmo (rattle in the sound)

This is without the problem : https://www.youtube.com/watch?v=c89DAxIPR0E (clear sound)

Conclusion, workaround is possible.

**Comment by JtLively** [comment]
@edwin-oetelaar Now I understand. I thought it was just a gritty bass synth. I think it may have been the project profile. I'm glad you found a solution. Sorry I couldn't do much to help. If you don't mind me asking, what profile are you using?

**Comment by jreynojustin** [comment]
OpenShot is now in Version 2.2 if you are still noticing issues in the latest version please re-open this issue letting us know.

**Comment by oyakteen** [comment]
I had the same issue in both the preview and the exported video and i tried to change the sample rate of the audio from 44100 to 48000 and it worked, now the export has no glitching sounds.

**Comment by jbrid** [comment]
@oyakteen Thanks for your solution. I am guessing that was my original issue as well. I am not able to run any tests at the moment to say for sure. 
Still seems like a software issue though.

**Comment by oyakteen** [comment]
@jbrid yeah sure man, happy editing lol👍
