### ISSUE TITLE
No Blender version detected in output  main window

### ISSUE THREAD

**Issue by guppie567** [OpenShot/openshot-qt#3551]
The Blender path is correct. When I want to create an animated text I get a message that blender path is not correct, and the same time blender executes.

**Steps to reproduce the behavior:**
1. Go to 'Title/Animated Title'
2. Click on 'any template'

**Expected behavior**

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Linux-4.15.0-101-generic-x86_64-with-Ubuntu-18.04-bionic
- Processor: x86_64
- Machine: x86_64
- Python version: 3.4.3
- Qt5 version: 5.2.1
- PyQt5 version: 5.2.1
- Qt Detected Languages: ['en-US', 'en']
- LANG Environment Variable: en_US.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1591560230-c29174f1-7cec1822-x86_64.AppImage

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/lh6hjq6rermbc380rs8at7eqtgggtbfq/openshot-qt.zip) (79 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/lh6hjq6rermbc380rs8at7eqtgggtbfq/libopenshot.zip) (1 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by ctsdownloads** [comment]
Thanks for the report. Question, can you paste the path you're using here? I have a feeling it's the installed Blender and not the stand-alone version.

**Comment by ctsdownloads** [comment]
Regarding your statement that the The Blender path is correct, can you post which path you're using so we can duplicate this?

**Comment by guppie567** [comment]
/snap/bin/blender

 

I've pasted a screenshot of Preferences.

 
 

Sent: Thursday, June 11, 2020 at 9:59 PM

**Comment by guppie567** [comment]
Yes, the Blender path is correct but when I try create an animated title the OpenShot freezes (watch icon).

 
 

Sent: Thursday, June 11, 2020 at 9:59 PM

**Comment by ctsdownloads** [comment]
Found the solution - [needs 2.80](https://download.blender.org/release/Blender2.80/blender-2.80-linux-glibc217-x86_64.tar.bz2). Apparently newer versions come up as undetected when I run OpenShot from the command line during tests. I can confirm this works for Linux users. Tested on PCLinuxOS.

1) Try the AppImage of OpenShot.
2) Use the standalone [Blender package for 2.80](https://download.blender.org/release/Blender2.80/blender-2.80-linux-glibc217-x86_64.tar.bz2)
