### ISSUE TITLE
Error Opening Project Failed to load project file /home/meie/Desktop/sudimisproov/Timmu 8.06.2020näd...

### ISSUE THREAD

**Issue by izzostar** [OpenShot/openshot-qt#3552]
**Describe the bug**
Error Opening old versions projects and now also current one.

**Steps to reproduce the behavior:**
File -> Open Project
Failed to load project file /home/meie/Desktop/sudimisproov/Timmu 8.06.2020nädalavideoprojekt parandada.osp: invalid load key, '{'.

**Expected behavior**
Project opens for edit.

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Linux-5.3.0-55-generic-x86_64-with-Ubuntu-19.10-eoan
- Processor: x86_64
- Machine: x86_64
- Python version: 3.4.3
- Qt5 version: 5.2.1
- PyQt5 version: 5.2.1
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: en_US.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1591560230-c29174f1-7cec1822-x86_64.AppImage

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/wtlznrnmxrl7x81oafdjkk2ayez464k2/openshot-qt.zip) (28 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/wtlznrnmxrl7x81oafdjkk2ayez464k2/libopenshot.zip) (12 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by SuslikV** [comment]
More likely the project file is damaged.
It looks similar to: https://github.com/OpenShot/openshot-qt/issues/3123

As for the use of `ä` in paths - work with OpenShot v2.5.1 or newer.

**Comment by izzostar** [comment]
Last two recovery files don't load either, third one does, (and asks for every file location). So, everything is not lost.

**Comment by izzostar** [comment]
ä has worked as long as i can remember. Not opening projects came with update to newest version. What version did i have before, i cant remember, probably 2.44. Mixture of repo and appimage usage on Lubuntu.

**Comment by SuslikV** [comment]
> ä has worked as long as i can remember...

It is not: https://github.com/OpenShot/openshot-qt/issues/3227 , but was fixed in v2.5.1

**Comment by izzostar** [comment]
yes so my last version was probably 2.44. Heard about the gpu rendering option and wanted to test it on old project files, but those did not open with new version 2.51.

**Comment by SuslikV** [comment]
So, I assuming you found the way to workaround the issue (by using backups)?

**Comment by ctsdownloads** [comment]
Assuming resolved in v2.5.1, closing
