### ISSUE TITLE
WIKI: Issue Management

### ISSUE THREAD

**Issue by MBB232** [OpenShot/openshot-qt#3553]
@ferdnyc Issue Management
https://github.com/OpenShot/openshot-qt/wiki/Issue-Management
Kept it out of documentation as it is getting quite long and cluttered, and this may be solved in one question. Or can rename this topic for general Wiki issues. 

I noticed the new tags still need to be listed. 
May I propose some new grouping; listing DOC, FAQ, Website, Work-around and Question together, as they are in the documentation workflow and do not necessarily need programmers. (actually, work-around should probably be in both, but I assume such issues keep their bug-tag as well. 

Another new <striketrough>tag</striketrough>grouping could be QA; making it easier for newcomers to see how they can help with testing. Tags that could go here could be Daily build, Closer, Needs Testing, Needs Info, and maybe Pending and Performance, if you want a bigger sample size. 
(If you have tags to document your WorkFlow/Action pulls, maybe list them here too?)

Also would it be helpful to have the listed items link directly to their filter in the tracker, or do you expect interested programmers to be active enough to do regular filter searches themselves?

**Comment by ctsdownloads** [comment]
Great feedback, thank you
