### ISSUE TITLE
Multiple files (drag and drop OR via import dialog) stops when import hits a duplicate file

### ISSUE THREAD

**Issue by leehockhin** [OpenShot/openshot-qt#3554]
**Describe the bug**
When importing multiple files, and there is a duplicate already in the Project Files, the import will stop when it hits the duplicate file.  Same behavior whether using Drag and Drop OR using Import Dialog.

**Steps to reproduce the behavior:**
1. Add a few files to Project Files
2. Select multiple files, with a duplicate file not at the end of the list
3. Drag and Drop files into Project Files area
4. There are No error messages but not all the files are copied into the Project Files
5. Same results if use the Import dialog

**Expected behavior**
An error message warning of the duplicate, with option to Skip or Replace File; then continue with the adding process for the rest of the files.

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Windows-10-10.0.18362
- Processor: Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
- Machine: Asus Gaming PC with NVidia GPU
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1591560328-c29174f1-7cec1822-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/topfa6wzaw66nhqkto828ftnigf1af15/openshot-qt.zip) (15 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/topfa6wzaw66nhqkto828ftnigf1af15/libopenshot.zip) (2 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
Not necessary as no error message was shown.

**Comment by ctsdownloads** [comment]
Thanks for this and thank you for your email as well. I've set labeled this as a bug from one of our testers.

**Comment by ferdnyc** [comment]
Will be fixed by #3630. (But I can also split it out to get it in faster, if need be. It's a 2-line fix.)
