### ISSUE TITLE
QA: Set of Test files + scripts

### ISSUE THREAD

**Issue by MBB232** [OpenShot/openshot-qt#3555]
I've seen a lot of questions and bug reports lately, and quite a few stall on the question on if it is an error with the configuration, the software or the media files. 
I think it could be useful if OpenShot offered a set of files that are known to be correct that users can try, and that way exclude some uncertainty? Perhaps a few files linked to known issues, to help diagnose edge cases. 

I've seen projects like LibreOffice work with tools like Coverty Scans and Bisected Bugs, whatever they may be. I can imagine that maintaining such systems may be too much overhead for Openshot. 
But I was wondering if along with those test files, Openshot could have some simple automated test scripts, or even self-tests?
It can unfortunately not be called from the command line, but perhaps they can be build in QT and compiled into the dailys? 

For instance there are a lot of audio issues, especially under windows. (For me it lists 14 audio devices, even though I am only aware of build-in 1 speaker. )
Having to test them all takes a lot of time, especially since you need to restart the program every time because it is a preference setting. 
Then creating a new project and loading in files every time takes even more time, and creates the risk of mistakes. _Having developers help in bug triage, only to finding out that the issue was with your _audio file_ is a waste of time all around. 
Aa simple 'test audio' button with known-to-work audio files in the program may simplify this. 

A similar issue exists with the title fonts that seems to multiply its bugs exponentially. But exporting a known text at a known time should always export the same image independent of the machine, right?
So by doing a hash-check or pixel comparison to pre-rendered images should prove if it is another case of missing fonts, or something new is broken. 

I'm sure actual expects in the program can come up with more complex cases. (finding out which Hardware codecs fail on what hardware/software may be a big issue?)

I would not be opposed to run such a check on a beta before releases, or if feedback is wanted after large changes. 
But making sure all settings are correct takes a lot of time and large risk of mistakes, making the result unreliable and thus unhelpful. 
So automated projects would be helpful.

**Comment by ctsdownloads** [comment]
Marked enhancement
