### ISSUE TITLE
OpenShot does not see a location of blender executable and freezes

### ISSUE THREAD

**Issue by guppie567** [OpenShot/openshot-qt#3557]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Linux-4.15.0-106-generic-x86_64-with-Ubuntu-18.04-bionic
- Processor: x86_64
- Machine: x86_64
- Python version: 3.4.3
- Qt5 version: 5.2.1
- PyQt5 version: 5.2.1
- Qt Detected Languages: ['en-US', 'en']
- LANG Environment Variable: en_US.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1591560230-c29174f1-7cec1822-x86_64.AppImage

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/lh6hjq6rermbc380rs8at7eqtgggtbfq/openshot-qt.zip) (147 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/lh6hjq6rermbc380rs8at7eqtgggtbfq/libopenshot.zip) (2 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.
![image](https://user-images.githubusercontent.com/66640560/84415986-6b495b80-abc8-11ea-99e5-a0f21e47375f.png)

**Comment by ctsdownloads** [comment]
Thanks very much for the detailed report, very helpful. Try this as snaps aren't that great with this sort of thing. Try the standalone version of Blender: https://www.blender.org/download/Blender2.83/blender-2.83.0-linux64.tar.xz/

Extract it, then browse to and copy the path to this standalone version. This should help.

**Comment by guppie567** [comment]
As you recommended I installed the standalone version, assigned location the executable, but it still freezes (watch icon). 

 

 
 

Sent: Thursday, June 18, 2020 at 10:35 PM

**Comment by nanohtpc** [comment]
same problem here

**Comment by ctsdownloads** [comment]
Found the solution - [needs 2.80](https://download.blender.org/release/Blender2.80/blender-2.80-linux-glibc217-x86_64.tar.bz2). Apparently newer versions come up as undetected when I run OpenShot from the command line during tests. I can confirm this works for Linux users. Tested on PCLinuxOS.

1) Try the AppImage of OpenShot.
2) Use the standalone [Blender package for 2.80](https://download.blender.org/release/Blender2.80/blender-2.80-linux-glibc217-x86_64.tar.bz2)
