### ISSUE TITLE
7.1 Surround Sound has the same bug as 5.1 Surround Sound

### ISSUE THREAD

**Issue by ramAustralia** [OpenShot/openshot-qt#3559]
7.1 Surround Sound has the same bug as 5.1 Surround Sound

I think you are on the right track about fixing it.

My system is Linux Mint.

A functional work around for both 5.1 and 7.1 is to create the 5.1 or 7.1 sound file separately and then use ffmpeg to merge it with the video created using OpenShot,
e.g.

ffmpeg -i video.mp4 -i audio.flac -c:V copy -map 0:0 -map 1:0 result.mp4

**Comment by ctsdownloads** [comment]
Do you have a link to the 5.1 bug in question? We can then mark this as the same issue.

**Comment by ramAustralia** [comment]
> Do you have a link to the 5.1 bug in question? We can then mark this as
> the same issue.
>

https://github.com/OpenShot/openshot-qt/issues/3527

and

https://github.com/OpenShot/libopenshot/issues/492
