### ISSUE TITLE
Closes when exporting

### ISSUE THREAD

**Issue by Nananaw** [OpenShot/openshot-qt#3561]
HP EliteBook 840 G3
Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz, 2496 Mhz, 2 Core(s), 4 Logical Processor(s)

Whenever I try exporting this specific video, Openshot closes when it reaches around 76%.

I go to the video and I click export(I have tried many different settings and still get the same problem) and when it reaches 76% openshot closes and I am left with a corrupted video file.

https://www.reddit.com/r/OpenShot/comments/h7a42a/exporting_video/
(reddit link with video of the project in openshot)

I have tried exporting at low quality and many other settings, and have tried uninstalling and reinstalling Openshot.

**Comment by SuslikV** [comment]
How many RAM is in use during the export (especially when export reaches your 76%)?

**Comment by Nananaw** [comment]
> How many RAM is in use during the export (especially when export reaches your 76%)?

Dont know how much RAM was in use but I deleted the files and the problem hasn't occurred again. I think one of my video files might have been corrupted.
