### ISSUE TITLE
Preserve input file settings in exported output?

### ISSUE THREAD

**Issue by learnedtocode** [OpenShot/openshot-qt#3562]
**Question:**

Most of my use of OpenShot is to open a video file then trim and/or downsize it for posting elsewhere.
It works well enough for this, but **how can I quickly and easily export a file using the same resolution, algorithm, quality settings etc that it had when I imported it?**
I must be missing something, currently I'm trying to find this through File Properties of the imported file, and then copying the resolution to the export profile, but that doesn't seem to be working either.

**System Details:**
- OpenShot Version: `OpenShot-v2.5.1-x86_64.AppImage`
- Operating System / Distro: Linux

**Comment by SuslikV** [comment]
Rather "feature request".

Anyway, similar was asked in: https://github.com/OpenShot/openshot-qt/issues/2709

Partially discussed in: https://github.com/OpenShot/openshot-qt/issues/2866#issuecomment-511175949 , https://github.com/OpenShot/openshot-qt/issues/3289#issuecomment-597610174 , https://github.com/OpenShot/openshot-qt/issues/3381#issuecomment-614104657

**Comment by learnedtocode** [comment]
Thanks for the links @SuslikV. Looks like it is not very easy to do this now.

>Maybe later, when export options will be extended to actual level of the encoder capabilities, -- https://github.com/OpenShot/openshot-qt/issues/2866#issuecomment-513475636

Hopefully an overhaul of the export options and profiles would come along with this, I did not find that section of the app very easy to use at the moment.

>you can create a custom preset and save it at your `/home/user/.openshot_qt/presets` directory. -- https://github.com/OpenShot/openshot-qt/issues/3381#issuecomment-614104657

This could work, in fact creating a few good presets this way might even be easier than using the export dialog. What do you think it would take to make a separate script that looks at a video file and creates an XML preset with the same settings programmatically?

**Comment by SuslikV** [comment]
> What do you think it would take to make a separate script that looks at a video file and creates an XML preset with the same settings programmatically?

I think that the `23 crf` as default for `.mp4` export is the key to all problems. Everything else is written in the way, that makes it hard to change or adjust.
