### ISSUE TITLE
OpenShot crashes with daily build and 2.5.1 as well when going to the end of the edited video

### ISSUE THREAD

**Issue by Pavel-aaa** [OpenShot/openshot-qt#3563]
**Describe the bug**
OS crashes when I 'm moving on timeline to the end of the edited video. If I start to play if plays till the end in hi-res mode or in low-res mode (QVGA) but then crashes anyway. No complex transitions just fades between the photos (jpegs) and few videos. Important is that parts in my film are cut from three "raw" clips 543, 270 and 473 Mb in full HD but 10 fps (video recording of zoom) which were placed on timelines (and each was cut), what was left from these big videos I'd deleted from timeline as I do not need them up to now. Initial output inititially 1280*720, 30 fps. Going to QVGA and making the "screen" for video very small didn't help. Daily build installed but became even worse - crashed at first launch and is crashing every time in the end of the video so I can't move on with editing. I sure know that my machine is weak (notebook with Intel I5 and 4GB, Win 7 64-bit)...

**Steps to reproduce the behavior:**
1. Open porject
2. Go to end or play to end
3. crash

**Expected behavior**
I expect to be able to continue with editing, 60% left!

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Windows-7-6.1.7600-SP0
- Processor: Intel I5-3317U @1,7GHz
- Machine: Win 7, 64-bit
- Python version: ?
- Qt5 version: ?
- PyQt5 version: ?
- Qt Detected Languages: ['ru-RU', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: applied

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/s86b9eiu7uids0zwh5upv0qdib1oiipo/openshot-qt.zip) (33 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
Problem signature:
  Имя события проблемы:	APPCRASH
  Имя приложения:	openshot-qt.exe
  Версия приложения:	2.5.1.0
  app time:	00000000
  Modul name (where mistake is):	StackHash_44b4
  Version of modul with mistake:	6.1.7600.16915
 Timeline of the modul with mistake:	4ec4b137
  Exclusion code:	c0000374
  Смещение исключения:	00000000000c6ae2
  Версия ОС:	6.1.7600.2.0.0.768.3
 Langiage code:	1049
  Additional data 1:	44b4
  Additional data 2:	44b4551b51f4c7db6b1ad48be52225dc
  Additional data3:	288b
 Additional data 4:	288b44fc0ee51179b0bf1c29c9099912

**Comment by ctsdownloads** [comment]
What type of video file was it? mp4, avi?

**Comment by frkn-857** [comment]
I have same proplem also

**Comment by frkn-857** [comment]
my video mp4

**Comment by frkn-857** [comment]
please help please
