### ISSUE TITLE
When switching to Razor Tool, I am unable to switch back to the Snapping Tool.

### ISSUE THREAD

**Issue by itsCara** [OpenShot/openshot-qt#3565]
The program works fine except for when I switch to the Razor tool to trim clips, when I click on the Snapping tool to switch back, it doesn't register. It also seems to not register when I click on the track to pull down the options. I would love to use this editing software but this is not allowing me to.
*Edit: It seems this is now happening when trying to switch from the Snapping tool to the Razor tool as well.*

**Steps to reproduce the behavior:**
1. Click on the Razor tool.
2. Try to click on the Snapping tool again.
3. If it doesn't work, try clicking on other things to see they still work.
4. Click on the arrow next to the track number to try and pull down the menu, and see it doesn't work.

**Expected behavior**
I expected to easily be able to switch back to the Snapping tool, but it is not registering my input and I'm forced to restart the software just to have the same issue again.

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Windows-10-10.0.18362
- Processor: AMD64 Family 23 Model 24 Stepping 1, AuthenticAMD
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1592168032-c29174f1-7cec1822-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/0igo2vx60l5zzomhh7wimvu85e47rc73/openshot-qt.zip) (393 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/0igo2vx60l5zzomhh7wimvu85e47rc73/libopenshot.zip) (1 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by SuslikV** [comment]
Click the _Razor Tool_ again to exit the "cutting mode" of the editor (make it "unchecked" - barely visible state change in the dark theme). _Snapping_ is independent feature.

And it is better to use _Slice_ from right-click menu over the clip.

**Comment by itsCara** [comment]
Thank you for your response :) I'm new to using OpenShot and watched the
official tutorials to find out all the ways to edit. I apologize for any
inconvenience.
