### ISSUE TITLE
Openshot could not open audio device

### ISSUE THREAD

**Issue by Rofikkernel** [OpenShot/openshot-qt#3566]
**Describe the bug:**
i selected all audio device in prefences and restart openshot after each change and still give this error , before using version 2.5 i am using version 2.4.4 and give me same error no audio in preview

this error only on openshot while other app like player not get error ,thanks

**Steps to reproduce the behavior:**
1.open openshot '...'
2. this error pop up show in first open  '....'

**Expected behavior:**
audio fixed

**System Details:**
- OpenShot Version 2.5.1
- Operating System / Distro: windows 10 1909

**Log Files:**
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/4778820/openshot-qt.log)

![bug](https://user-images.githubusercontent.com/26862653/84632086-9dd0bc80-af18-11ea-990f-e366726dfd61.png)
![bug2](https://user-images.githubusercontent.com/26862653/84632184-bccf4e80-af18-11ea-88cb-0b37d9b18c8c.png)

**Comment by SuslikV** [comment]
General audio settings in Windows was under the speaker's icon right-click menu _Playback Devices > (Device Name) > Properties > Advanced tab > Default Format_ section. (same path for _recording_ devices).

Set it to match the _Default Audio Sample Rate_ setting of OpenShot (currently it is not visible on the screenshot and log-file useless, but it probably 48000Hz or 44100Hz at 16bit/24bit).

Some screenshots:
![Playback devices](https://user-images.githubusercontent.com/19683044/70423320-ed1fc700-1a75-11ea-858a-f1949ca984fa.png)

And take a look at the _Communications_ tab as well:
![Communications tab](https://user-images.githubusercontent.com/19683044/70423867-05dcac80-1a77-11ea-9654-63274eb2c718.png)


If _Default Format_ for shared mode in Windows is set OK, then maybe application is blocked by security software.
