### ISSUE TITLE
Missing File Error Every Time I try to Open My Saved .osp File

### ISSUE THREAD

**Issue by BriC1155** [OpenShot/openshot-qt#3567]
I am having an issue when I try to open my saved project (the .osp file), I keep getting an error saying "Missing File" and I get stuck in a loop. 

This file DOES exist and in the folder it's looking at, so I'm not sure why Open Shot is not seeing it. 

I have already tried deleting the .openshot_qt file folder and then re-opened Open Shot Editor, but that does not work either.  Please help!  Over 8 hours have been spent on this project and it would be devastating if all that work and time was lost.  Thank you!

**Comment by BriC1155** [comment]
For reference, I have OpenShot Version 2.5.1.  Thanks!

**Comment by SuslikV** [comment]
Screenshot of the error message?
