### ISSUE TITLE
Waveform display unusably slow

### ISSUE THREAD

**Issue by srwalter** [OpenShot/openshot-qt#3568]
Clicking Display -> Waveform on a track causes the program to use 100% CPU indefinitely.  This occurs with either a video (MP4) or WAV track.  The track is 2 hours long and timeline scale is at 900 seconds.

**Expected behavior:**
Waveform should render in less than one minute.  In kdenlive it is effectively instantaneous

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 2.5.1
- Operating System / Distro: Arch

**Comment by rbutterworth** [comment]
I get the same on a 1 hour clip in the 2.5.1 daily build from today.

**Comment by Eate** [comment]
Duplicate of #1959
