### ISSUE TITLE
Timeline skips and stops and CPU is pegged

### ISSUE THREAD

**Issue by kenwdelong** [OpenShot/openshot-qt#3574]
**Describe the bug:**
I am using Open Shot 2.5.1 on a Window 10 8-core machine with 16GB RAM. As I'm editing a video, and moving the cursor forward and back, sometimes the playback starts skipping, halting, and jerking, and the CPU (all 8 cores) are pegged at 100%.

I notice that there's a little moving light-blue "slider" that travels along with the cursor; I have come to understand that this is likely the portion of the clip that is rendered and currently loaded into memory. When I move the cursor to a new spot and start playback, normally this slider immediately reforms for a few seconds in advance of the cursor. However, when it gets into the skipping-and-halting mode, the slider never properly reforms and usually it has gaps and is fragmented.

**Steps to reproduce the behavior:**
I can't find a way to reliably reproduce it; sometimes making the playback preview panel smaller fixes it.

**Expected behavior:**
It shouldn't skip and the slider should be "healthy"

**System Details:**
- 2.5.1
- Windows 10, Intel i7-8650U CPU

**Log Files:**
N/A

**Exception / Stacktrace:**
N/A

**Screenshots:** (Optional)
This is the "slider" when it's unhealthy
![image](https://user-images.githubusercontent.com/6744405/85246256-fdd6cf80-b3fe-11ea-85fa-5f369b66ef88.png)

**Comment by SuslikV** [comment]
OpenShot uses software render. Nothing will be changed soon. You may experiment with the number of threads OpenShot uses (in _Preferences_) both **decreasing and increasing** number of threads may improve performance. More threads = more data goes through the RAM.

About blue line itself: https://github.com/OpenShot/openshot-qt/issues/2169#issuecomment-629836478
