### ISSUE TITLE
Audio not going through the Headphones

### ISSUE THREAD

**Issue by BlazeRedraw** [OpenShot/openshot-qt#3576]
Sorry I'm new so I had to edit this in XP

Well I was going to edit a video and plugging in the headphones didn't really work, the sound kept coming from the computer and that's about it, it could be that I am using earphones and not headphones or something but other than that I can't find how to put text but I'm pretty sure a video on YouTube will help

**Comment by Eate** [comment]
What platform (operating system) are you on, such as Windows 10 or Ubuntu 20.04? Have you checked your audio settings? (As far as I know, OpenShot just sends audio through the default device.)

**Comment by xuiqzy** [comment]
The same problem occurs on macOS Catalina with Bluetooth Headphones, openshot installed via `brew`.

**Comment by BlazeRedraw** [comment]
> What platform (operating system) are you on, such as Windows 10 or Ubuntu 20.04? Have you checked your audio settings? ~(As far as I know, OpenShot just sends audio through the default device.)~ Edit: This does not seem to be the case, you can open Preferences and change the audio output device. (Edit/Preferences/Preview)

OK thanks I'll try it next time I edit a vid
