### ISSUE TITLE
Unresponsive for minutes at a time when editing high quality variable frame rate video

### ISSUE THREAD

**Issue by Kor1134** [OpenShot/openshot-qt#3577]
**Describe the bug:**
Working on a 300 second, high quality MP4, I need to trim the first 121 seconds of the video.  After I remove the cut section, OpenShot runs extremely slow, playback in the preview pane is out of sync and only plays a few frames at a time, and when I export the video or exit the application, it becomes unresponsive for several minutes at a time.  The verbose output generated over 200MiB of data in about 10-15 minutes of usage, doing nothing but cutting a section of video and previewing the change.

**Steps to reproduce the behavior:**
1. Import 1080p60 video with variable frame rate into a new project and add it to an empty track.  (The video I'm working with has an h264 bitrate of ~21Mbit/s.)
2. Cut a section from the beginning of the video, delete it, and move the remaining footage to the beginning of the track.
3. When you click play to sample the edited video, it will play several frames intermittently and may stop altogether after a few seconds.
4. Exit OpenShot.  You may have to wait a few minutes until the thread that is still processing the video finishes.

**Expected behavior:**
Application should be responsive and provide smooth playback and export while keeping video and audio synchronized.  I used Freemake and Filmora9 to accomplish the desired result in just a few minutes, but those applications embed a watermark unless I pay, and the fee is not worth the rare occasion I might need to modify a video and the limited audience I intend to make it for.

**System Details:**
- OpenShot v2.5.1-dev2
- Windows 7 Ultimate SP1 x64

**Log Files:**
[openshot-qt.log.zip](https://github.com/OpenShot/openshot-qt/files/4833979/openshot-qt.log.zip)
[libopenshot.zip](https://github.com/OpenShot/openshot-qt/files/4833983/libopenshot.zip)

**Comment by SuslikV** [comment]
OpenShot seeking algorithm is causing your problem. In some cases by remuxing ( https://github.com/OpenShot/openshot-qt/issues/2896#issuecomment-519383053 ) video before importing it into OpenShot may help.

**Comment by Kor1134** [comment]
> OpenShot seeking algorithm is causing your problem. In some cases by remuxing ( [#2896 (comment)](https://github.com/OpenShot/openshot-qt/issues/2896#issuecomment-519383053) ) video before importing it into OpenShot may help.

Then why don't you write a different algorithm optimized for video streams like this, detect constant or variable frame rate and fork the code to the appropriate algorithm. Or include a remux feature in OpenShot to work around this bug.  As I mentioned, Freemake worked perfectly but embedded a watermark unless I buy it.

**Comment by SuslikV** [comment]
Did you tried to remux? Is it works for you?

As for the code writing - I already did what I can. Just use it if you wish. Also, mpv player using FFmpeg and has nice seeking. Why to reinvent the wheel? I see the difference between these two.

**Comment by Kor1134** [comment]
I remuxed with ffmpeg and now it is smooth, but about 1 minute into the preview, playback stopped. Clicked play/pause a few times, nothing changed, so went to the beginning of the video and clicked play, and OpenShot stopped responding, had to close with task manager.

**Comment by SuslikV** [comment]
Try other software then. Unfortunately, this behavior of OpenShot wouldn't be changed any time soon. Similar issues were reported many times.
