### ISSUE TITLE
Size of file after export

### ISSUE THREAD

**Issue by sj-on** [OpenShot/openshot-qt#3578]
Suppose that I am combining 4 video files of size 20mb, 30mb, 89mb and 10mb, then after exporting(just combining and exporting on the same quality) the size must be, at maximum, 149mb. However, instead the file size goes even beyond that. Why is this the case?

**Comment by SuslikV** [comment]
Similar to https://github.com/OpenShot/openshot-qt/issues/3562

Try to use `18 crf` or `23 crf` like setting in OpenShot for the _Export_ bitrate. Screenshot of the corresponding field: https://github.com/OpenShot/openshot-qt/pull/2967#issue-313345975
