### ISSUE TITLE
Emoji translations for most languages attached

### ISSUE THREAD

**Issue by gunchleoc** [OpenShot/openshot-qt#3579]
I have extracted the official Emoji translations from the Unicode Consortium's CLDR.

[emojis.zip](https://github.com/OpenShot/openshot-qt/files/4838992/emojis.zip)

Can we merge these into the Launchpad translations somehow and thus save the translators many days of work?

**Comment by gunchleoc** [comment]
Please keep

**Comment by JacksonRG** [comment]
This is a good idea! We'll get this added to the translation.
