### ISSUE TITLE
Export to DVD so will play in DVD player

### ISSUE THREAD

**Issue by Amy385** [OpenShot/openshot-qt#3588]
I have a video project I'd like to be able to burn to a DVD to play in a DVD player. 
-What is the best format to use to export for this purpose?

I have exported the video in a number of formats and burned them to a DVD. However, each time I try to play the DVD in the DVD player, regardless of the format, I get the error message "Disc Error. Playback feature not available."
-What might be causing this? How do I get around this?

**System Details:**
- OpenShot Version: 2.5.0 libopenshot: 0.2.4
- Operating System: Windows 10

**Comment by ctsdownloads** [comment]
Hi Amy,

I'd simply export the video to an MP4 file, then [follow this guide](https://www.leawo.org/tutorial/mp4-to-dvd.html#part2) and software to create a DVD.
