### ISSUE TITLE
Openshot fails to start

### ISSUE THREAD

**Issue by DrWaleedAYousef** [OpenShot/openshot-qt#359]
when running the AppImage from the shell it gives me this:

wyousef@localhost ~/Downloads> ./OpenShot-v2.1.0.AppImage 
/tmp/.mount_HFJ49o/usr/bin/openshot-qt.wrapper
Loaded modules from current directory: /tmp/.mount_HFJ49o/usr/bin
fish: “./OpenShot-v2.1.0.AppImage” terminated by signal SIGSEGV (Address boundary error)

Thanks

**Comment by mikelplastika** [comment]
Kaixo, hi,
well openshot 2.1 installed on 64-bit Ubuntu 16.04, but it does not work, will not start.
It appears when installing on the console that is not "media all / all"

**Comment by DrWaleedAYousef** [comment]
What do you mean? Also, please observe that this is just the image file not the installation.

**Comment by mikelplastika** [comment]
Forgives. I habre confused with the topic of discussion. I just wanted to move the team openshot, which in ubuntu 16.04 64bit installs but does not start the program.

**Comment by jonoomph** [comment]
Ubuntu 16.04 64-bit has a broken dependency for OpenShot (if you are attempting to use our PPA). I've already filed a bug and posted a few messages about it on IRC, but no fixes upstream yet or from Canonical. Strangely, 32-bit Ubuntu 16.04 is fine. Feel free to find someone at Canonical who will actually reply to you, and inform them that libunittest++ is broken in that environment.

In the meantime, please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily AppImage of OpenShot.

**Comment by mikelplastika** [comment]
Thank you very much for your help. My field is the design and animation in
Education. I'm not a developer and I can not bring in the arrangements.

2016-10-06 8:28 GMT+02:00 Jonathan Thomas <notifications@github.com>:
