### ISSUE TITLE
Windows 64-bits very slow or not playing at all when I move play head

### ISSUE THREAD

**Issue by David263** [OpenShot/openshot-qt#3591]
Sorry, no time to verify this bug as I have a video due tomorrow.

**Describe the bug:**
I'm having extreme slowness in OpenShot catching up to moving the play head (scrubbing) of just 4 or 5 minutes at 25 frames per second. It is a lot slower than just filling the cache with all the frames in between. App gets unresponsive to input events. I set the cache size to 2000 on a 4GB memory. My . Is that a "much older version"? Is there a 32-bit version of OpenShot? Should I submit a bug report? I have to finish a 1-hour video by tomorrow. OpenShot was never this slow on a previous computer.

**Steps to reproduce the behavior:**
1. Open an mp3 file, move to timeline
2. Start playing. Stop. Move play head to right. Start. After a couple of times, OpenShot becomes unresponsive, either temporarily or permanently. There is no error message.

**Expected behavior:**
I expected OpenShot to work as well as on another computer, scrubbing without crashing.
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/4855116/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/4855118/openshot-qt.log)

**System Details:**
version is 2.5.1
Windows 10 Home

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.
Log files can be found in your HOME/.openshot_qt/ folder. Please compress or zip
the log files (as they can become quite large).

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please
attach a small snippet of the exception here, but please keep it as small as
possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them here, dragging-and-dropping into this form, or clicking below and loading
images saved to your computer. All images are public, so please don't post screenshots
containing personal information.

**Comment by David263** [comment]
I'm downloading the 32-bit version and will report my experience with it here.

**Comment by David263** [comment]
With the 32-bit version and the exact same project file, previewing was perfect, with NO delays or hangs. Besides the test listed above, I was also able to leave the player playing and scrub anywhere within the 2.6 minute video/audio combination. Obviously, the bug is in the 64-bit version only, so it should be reproducible and easy to fix. Happy bug hunting.

**Comment by SuslikV** [comment]
Make sure that you are not running into the https://github.com/OpenShot/openshot-qt/issues/3043 issue (or some part of it).
Thus, try to remove any images from your .mp3 files: https://github.com/OpenShot/openshot-qt/issues/2756#issuecomment-487876270

**Comment by David263** [comment]
Yes, the MP3 file contains a thumbnail (cover art). However, OpenShot x86 (32-bit) DOES work correctly with this file.

I suggest that this bug in the 64 bit version be fixed, not closed and ignored, since it has been well documented in the combination of my reporting and the reporting in #3043.

David Spector
Springtime Software

**Comment by SuslikV** [comment]
Years may pass to resolve this...

**Comment by oliveriod** [comment]
I have the same issue with mp4 files.
