### ISSUE TITLE
Starting a new project with 2 simple 140MB files has the app going from 0memory usage to 8GB after a single slice

### ISSUE THREAD

**Issue by jakebesworth** [OpenShot/openshot-qt#3592]
I've attempted to look at other bug reports, noticed that some memory issues were fixed within the last 6months, but that doesn't seem to change as I have the latest build.

openshot-qt is already the newest version (2.5.1+dfsg2+1218+202003032149~ubuntu18.04.1)

**Describe the bug:**

On ubuntu 18.04, I've created a brand new project. I imported 2 simple 720p video files that are 140MB, and 2minutes~ long.

As soon as I drag 1 of the videos into the Track 1 > try to slice > then preview the 2 slices, the preview starts to instantly freeze (preview is on 720p, 30fps), and my computer memory goes from barely any being used all the way to 8GB.

**Steps to reproduce the behavior:**

1. Start new project
2. Add a video file or two of > 100MB, 720p
3. Add first video to Track 1
4. Slice video
5. Try to preview slice 1 and slice 2, and once it hits the second slice, the memory grows exponentially

**Expected behavior:**

A small project shouldn't freeze and need such huge amounts of memory. I've worked on much larger projects in the past with no issues.

**System Details:**

         app:INFO openshot-qt version: 2.5.1-dev2
         app:INFO libopenshot version: 0.2.5-dev2
         app:INFO platform: Linux-4.15.0-96-generic-x86_64-with-Ubuntu-18.04-bionic
         app:INFO processor: x86_64
         app:INFO machine: x86_64
         app:INFO python version: 3.6.9
         app:INFO qt5 version: 5.9.5
         app:INFO pyqt5 version: 5.10.1

**Log Files:**

I tail'd the log file from when the program was in a good state to when the app starts melting:

https://gist.github.com/jakebesworth/2d24ff99e4e47a83642ba11c3c022e62

There aren't any notable errors or warnings before this point (some warnings about JS eval)

**Exception / Stacktrace:**

None I close program when my computer freezes due to no memory.

**Screenshots:** (Optional)

None required.

Let me know if this is enough information to go off of, or if this is a known issue. Thanks!

**Comment by ctsdownloads** [comment]
Thank you for the report. This is the workaround I recommend in the meantime. 
https://vimeo.com/420117641

**Comment by SuslikV** [comment]
@ctsdownloads in the video tutorial you provided you have selected preview profile with different FPS - in OpenShot this may cause problems during edit/export (different parts of the video will be exported). See details: https://github.com/OpenShot/openshot-qt/issues/3470#issuecomment-626324627 , also this was mentioned in https://github.com/OpenShot/openshot-qt/issues/2169#issuecomment-631669193

**Comment by jakebesworth** [comment]
Setting the profile to 720p 60fps  (same as the files being imported) seems to help a small amount, but then the program still looks to freeze up and memory usage seems sporadic after slicing a clip.

Note: Last year using openshot and many more files, I did not run into this issue after slicing a single video file.
