### ISSUE TITLE
pour le logiciel aucun fichier n'est valide

### ISSUE THREAD

**Issue by Quetzalame** [OpenShot/openshot-qt#3593]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Windows-10-10.0.18362
- Processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['fr-FR', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1593578219-517f2896-7cec1822-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/awptchts1puzvvj6ownjgancatne3iuh/openshot-qt.zip) (26 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/awptchts1puzvvj6ownjgancatne3iuh/libopenshot.zip) (6 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by ctsdownloads** [comment]
No information as to the issue provided. Closing, please reopen if you can provide details as to the issue. Thanks
