### ISSUE TITLE
Reverse Motion doesn't work as intented

### ISSUE THREAD

**Issue by ThomasJanuary88** [OpenShot/openshot-qt#3594]
**Describe the bug:**
When I want to play a video backward for 5s, for example from 0:20 to 0:25, the wrong part of the video is reversed in the exported video.

**Steps to reproduce the behavior:**
1. Drag and a video in a pist
2. Click on cut the video from t1 to t2
3. Right click on Time->Normal->Backward->1X
4. Look at preview (should be ok)
5. Export
6. Look at export (wrong part is reversed)

**Expected behavior:**
The reversed motion clip should be played from t1 to t2.

**System Details:**
- OpenShot Version 2.5.1
- Windows 10

**Comment by SuslikV** [comment]
Better keep your input fps = export fps. _Time_ property in OpenShot is set in frames not in seconds.

Similar issues: 
https://github.com/OpenShot/openshot-qt/issues/3451
https://github.com/OpenShot/openshot-qt/issues/3260
https://github.com/OpenShot/openshot-qt/issues/3274

**Comment by ThomasJanuary88** [comment]
Thanks for you reply.

None of this similar issues work for me.
I finally got my clip by exporting other and other the video and try to get the good part by comparing the preview with the exported video.

**Comment by SuslikV** [comment]
1) What fps of the input clip?
2) At what fps is your OpenShot Preview profile?
