### ISSUE TITLE
OpenShot Export with NVENC crashes

### ISSUE THREAD

**Issue by Eate** [OpenShot/openshot-qt#3595]
**Describe the bug:**
OpenShot export with hardware acceleration fails or crashes, despite having relevant drivers as well as FFmpeg compiled with NVENC. When on stable build and Nvidia drivers version 440, the latest stable drivers, I got the following error message in the logs when trying to export:
`Driver does not support the required nvenc API version. Required: 10.0 Found: 9.1`. It threw a pop-up dialogue notifying me of the error. When on the daily build, it crashed, with logs found in `OpenShot-Issue-02Jul2020-nv440or450-2.5.1-dev2-1593578124.txt`. So, I went to Nvidia's website, where I found that the latest API version would require driver version of at least 445. So, I installed the beta driver version 450, and opened OpenShot. The daily build had the word-for-word exact same crash log as on driver 440 (`OpenShot-Issue-02Jul2020-nv440or450-2.5.1-dev2-1593578124.txt`), and the stable build no longer threw a pop-up error but instead crashed, with logs found in `OpenShot-Issue-02Jul2020-nv450-2.5.1.txt`. I couldn't find what the issue was from just the logs, so I hope that someone here can help me out. Thanks!

**Steps to reproduce the behavior:**
1. Open a project
2. Export with NVENC, MP4, AVC

**Expected behavior:**
It properly encodes and outputs my video.

**System Details:**
- OpenShot Version:
  - 2.5.1-dev2-1593578124 via daily AppImage
  - 2.5.1 via stable PPA
- Operating System / Distro: Ubuntu 20.04

**Logs**
Via terminal, as log file does not catch the stack trace or show any warnings.
[OpenShot-Issue-02Jul2020.zip](https://github.com/OpenShot/openshot-qt/files/4866420/OpenShot-Issue-02Jul2020.zip)

**Comment by ctsdownloads** [comment]
Hardware acceleration is highly experimental. So activating it in preferences hasn't worked for me, however, for rendering in export I've had the following work for me using my CUDA capable NVIDIA card. I am not in front of the proper PC at the moment, but I have it set to one of the VA-API options as seen below. This provides me with MUCH faster export/rendering.
 
![HardwareAccel](https://user-images.githubusercontent.com/18758065/86994379-14995800-c15b-11ea-95e0-eaad6d2d5e6b.png)

**Comment by Eate** [comment]
I have tried VA-API, but it throws an error.
![image](https://user-images.githubusercontent.com/17911331/86999403-5cbe7780-c167-11ea-8eeb-32336d64f09d.png)
