### ISSUE TITLE
Crashes when trying to access preferences

### ISSUE THREAD

**Issue by Hallusk** [OpenShot/openshot-qt#3596]
**Describe the bug**
When I try and open the preferences, the program crashes immediately.

**Steps to reproduce the behavior:**
1. Go to edit
2. Click on preferences
4. See error - crashes

**Expected behavior**
The program not to crash

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Windows-10-10.0.18362
- Processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1593578219-517f2896-7cec1822-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/kproa870l34ceqxz7ocm6hj03btes9dy/openshot-qt.zip) (5 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by SuslikV** [comment]
Application crashes in Quick Sync encoder/decoder test.
Try to exclude the crashed test from the list, (by modifying the preferences.py file) like in: https://github.com/OpenShot/openshot-qt/issues/3276#issuecomment-595052453
