### ISSUE TITLE
Not possible to paste anywhere on the bare timeline

### ISSUE THREAD

**Issue by jarlarntzen** [OpenShot/openshot-qt#36]
Copying a clip or title is fully possible but it's only possible to paste whilst right-clicking on _another_ clip or title since the context menu does not appear when only the bare timeline is right-clicked directly.

It would be very nice to simply right-click exactly where one wants the copied clip to be pasted.

**Comment by jarlarntzen** [comment]
And BTW: `Ctrl+C`, `Ctrl+X` and `Ctrl+V` would be highly appreciated by myself :cake:

**Comment by jarlarntzen** [comment]
This also applies to OSX El Capitan

**Comment by komackaj** [comment]
Shorcuts not working related bug #138

**Comment by ankitpati** [comment]
No repro with OpenShot 2.2 AppImage on Ubuntu 16.04. Right-clicking on a bare timeline does show the paste option, and Ctrl + C, Ctrl + V also work.

Closing this as fixed. Please reopen if necessary.
