### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by OGLordBlight** [OpenShot/openshot-qt#360]
Issue `#1`
1. Loaded 8 videos files (.MTS - HD video)
2. Preview is very choppy (standalone issue)
3. Open Preview in new window
4. Edit video, mostly removing sections of video
5. Fullscreen main window
6. Revert from fullscreen main window
7. Preview window disappears 
8. minutes later program crashes

Issue `#2`
1. Post crash
2. Load second project file to track 3
3. every ~3-5 seconds preview locks up for over 60 seconds

Issue `#3`
1. Try to Advanced Edit title
2. Already have inkscape installed
3. Receive message to install inkscape

System:
Win 7 - 64 bit
Intel i7
16 GB Ram
256GB SSD
Nvidia GTX 660

**Comment by ankitpati** [comment]
Can you please verify if the issue still persists in the latest stable [release](https://github.com/OpenShot/openshot-qt/releases/download/v2.2.0/OpenShot-v2.2.0-x86_64.exe "OpenShot 2.2")?
