### ISSUE TITLE
Click on Preference option closing application.

### ISSUE THREAD

**Issue by prabhatyadav** [OpenShot/openshot-qt#3608]
**Describe the bug:**
OpenShop application get shutdown as i click on the preference option.

**Steps to reproduce the behavior:**
1. Go to Openshot video Editor  desktop icon double click on it.
2. Application get open. 
3. Click on 'Edit >preferences'
3. Openshot Video Editor get shut down.

**Expected behavior:**

**System Details:**
- OpenShot Version :  2.5.1
- Operating System / Distro:  Windows 10 Home Single language

**Comment by chrisrlong** [comment]
When this happens to me I get this in the windows application log:

Faulting application name: openshot-qt.exe, version: 2.5.1.0, time stamp: 0x00000000
Faulting module name: ntdll.dll, version: 10.0.18362.815, time stamp: 0xb29ecf52
Exception code: 0xc0000374
Fault offset: 0x00000000000f9229
Faulting process ID: 0x30ac
Faulting application start time: 0x01d6619253620dad
Faulting application path: C:\Program Files\OpenShot Video Editor\openshot-qt.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report ID: 23da1391-4364-4bb4-9149-2255990e8bc1
Faulting package full name: 
Faulting package-relative application ID:
