### ISSUE TITLE
Exporting eats up memory, Openshot 2.2.0, Windows 10 64-bit

### ISSUE THREAD

**Issue by theelectricsoul** [OpenShot/openshot-qt#361]
As soon as I export to a video file, you see the memory usage climb fast until memory ist eaten up. I have 16 GB of RAM. My Video ist 60 GB big.

**Comment by JtLively** [comment]
Have you had this same issue with newer versions?
Are you still having this issue?
What export settings are you using?

**Comment by jreynojustin** [comment]
OpenShot is now in Version 2.2 if you are still noticing issues in the latest version please re-open this issue letting us know.

**Comment by theelectricsoul** [comment]
Same issue. 
https://youtu.be/UJpETFrFOHQ

[Screenshot OS version used](http://i.imgur.com/1bIvXO9.png)

Cutting and playing the file with OS 2.2.0 is also jerky. Should I open a issue for that?

**Comment by theelectricsoul** [comment]
[Export Settings](http://i.imgur.com/mTbZ33G.png)

**Comment by jreynojustin** [comment]
Nope I'll just re-open this one and change the version number. Thanks for providing that additional information!

**Comment by Wintch** [comment]
Same here on:
windows 7 64bit Ultimate SP1
16gb RAM, Openshot Cache 4gb on disk

I can export in FullHD, 4k eats all the RAM and crashes. Ogg and h264
This largely depends on the lenght of the output video. Something about 3min will reproduce the glitch

**Comment by DylanC** [comment]
@theelectricsoul - Is this still an issue on v2.4?

**Comment by theelectricsoul** [comment]
Looking good. :) Great....   thanks a lot

**Comment by theelectricsoul** [comment]
Playing the file inside OS is still jerky but in sync.  The playback is fluent with the audio, but the picture is jumpy . Jumps around every 500ms.

**Comment by DylanC** [comment]
@theelectricsoul - I'm closing this based on the feedback the memory issue is resolved. For the other issue you can comment on an existing similar ticket or log a new ticket. Thanks.
