### ISSUE TITLE
Copyright in files are out of date in source files

### ISSUE THREAD

**Issue by nmat** [OpenShot/openshot-qt#3610]
**Describe the bug:**
Some files have a old copyright in them for example in freeze.py the copy right is from 2008-2016.

And other files are marked as 2008-2018 for example in the docs.

Might be good to standardize the copyright in the files and reflect on all the files in OpenShot source code.

**Comment by ferdnyc** [comment]
See the discussion in OpenShot/libopenshot#481 regarding copyright updating, and especially the linked blog post in the comments.

The long and short is: 
1. Copyright dates in source files shouldn't be updated just to keep to the current year, they should only be updated when changes (possibly, "significant changes") are made. Updating them without other changes pollutes the file's commit history.
1. Copyright dates possibly shouldn't be present in source files at all, as they're nothing but redundant, often conflicting data. The git commit history is the canonical source of information on file change timelines.
1. No copyright statement AT ALL is necessary for copyright protection, under copyright law in the US and elsewhere copyright is assigned the moment something is published.

I'd personally be more inclined to remove the dates entirely, and stop having to worry about updating them. @jonoomph any thoughts on that?

**Comment by ferdnyc** [comment]
> And other files are marked as 2008-2018 for example in the docs.

Those files, in particular, mostly WERE last updated in 2018, so the dates are correct.

**Comment by nmat** [comment]
Removing them sounds actually better and I agree with the information provided thank you.
