### ISSUE TITLE
The bug reporter is not usable

### ISSUE THREAD

**Issue by JanisE** [OpenShot/openshot-qt#3614]
I'm trying to report a bug using https://www.openshot.org/issues/new/
It requires me to attach two log files. They are both around 3.5 MB even after I delete and do the absolute minimum actions in Openshot to reproduce the bug. The reporter does not accept log files bigger than 500 KB.
If I zip those log files, the reported says that it cannot find OpenShot's version information and will not accept those archived log files.
Please, fix this so I can report a bug according to your guidelines.

**Comment by ferdnyc** [comment]
Hm. That's odd, I know that people have posted _much_ larger logs than that in the past. Maybe it's a recent change.

Anyway, the website reporting tool is really just a guided interface to creating a GitHub issue. As you no doubt saw when you posted _this_ issue, there's a Bug Report template that loads and requests the same info the web reporting flow collects.

It's fine to open an issue directly (but please do include the requested details), then you can  just post the logs via GitHub's attachment feature.

**Comment by rexdk** [comment]
For what it's worth, I agree that the page  https://www.openshot.org/issues/new/ is silly - you might not need to post the log files, depending on your issue. Most issues siubmitted here do not submit log files, and they would not help. The page could be replaced with a simple link to Github.

**Comment by ferdnyc** [comment]
I'm not particularly a fan either, but it's not my call. I at least was able to lobby for some improvements to the page a few months back, so it didn't post WRONG information with every bug report... though now I'm worried that the changes made then also led to the problems @JanisE experienced.

Regardless, agreed — most reports don't benefit much from using that page, over just filling out the GitHub bug report template.
