### ISSUE TITLE
Add "No to All" to "Import Image Sequence" dialog.

### ISSUE THREAD

**Issue by radiationcowboy** [OpenShot/openshot-qt#3623]
When attempting to import a large number of .jpg files with sequential filenames. (img0023.jpg, img0024.jpg...)
I am asked for each file "Would you like to import <filename> as an image sequence?"

A "No to All. button would save considerable time.

**Comment by rexdk** [comment]
"The image sequence importer was completely reworked a couple of months ago" (from #3585). This is not in the current release, but it is in the 'daily build'. I have yet to try the daily build, but I suspect that the issue has already been sorted out

**Comment by rexdk** [comment]
Oh dear - I've just tried the latest daily build and this behaviour has not been improved - sorry. I'll comment further in the earlier issue.

**Comment by jandermoreira** [comment]
Any news on this issue?
The "not to all" is a most wanted button.

And a "cancel" button will be a nice feature also!

**Comment by rexdk** [comment]
@jandermoreira  I agree it's annoying. Apparently there are some people who find it helpful (probably those using Blender.) I've just tried the latest daily build and you do still get asked - and if you try to import a second image you get asked again. The best workaround is to select all your images and drag them all in together - then you are asked about the first image, but if you say no the remaining images all import straight away. I think that is a recent change in behaviour - and it's a big improvement. I have a feeling there is resistance to any 'sensible' solution to this, and we might have to live with this. I'll try to get it into the documentation.
