### ISSUE TITLE
OpenShot 2.5.1 won't open - cx_Freeze Python error in main script

### ISSUE THREAD

**Issue by aryansharma141849** [OpenShot/openshot-qt#3626]
System Details:
Intel i5
8gb ram

Operating System / Distro: ?
Windows 10
OpenShot Version: ?
2.5.1
Please attach log files if crash
![Error in openshot](https://user-images.githubusercontent.com/35529590/88498066-c2bc5300-cfdf-11ea-8bbe-8af82d068684.PNG)

I have tried installing openshot many times but always getting the same error.

**Comment by ferdnyc** [comment]
@aryansharma141849 

Hmm, that's very strange. I installed 2.5.1 on a new Windows 10 install just the other day, and it functioned just fine. I'm not sure why you'd be getting that error, which appears to be deep inside the Python `requests` module.

How are you installing OpenShot, with the installer package downloaded from https://openshot.org/download/ ? Is it the 2.5.1 release build (https://github.com/OpenShot/openshot-qt/releases/download/v2.5.1/OpenShot-v2.5.1-x86_64.exe), or one of the Daily Build versions?

(Fair warning: whatever your answer is, I'm probably going to suggest you try the _other_ one and see if that makes a difference.) :wink:
