### ISSUE TITLE
Garbage audio for few milli seconds

### ISSUE THREAD

**Issue by tutyvijesh** [OpenShot/openshot-qt#3628]
**Describe the bug**
Garbage audio/disturbance at the beginning of the video for few milli seconds even if audio track is silent

Pls view this video as it has that disturbance at the beginning 
https://www.youtube.com/watch?v=JsvM98Sgc-s

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 2.5.1
- libopenshot Version:  0.2.5
- Platform: Windows-10-10.0.18362
- Processor: Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Skipped this step

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/ktj24tkotn8au4pmv3dd910y04y1fo2m/openshot-qt.zip) (5 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by rexdk** [comment]
There is a visual judder at the start of that video - I wonder if your source file might be corrupted or faulty. Have you tried to set the 'Start' property to say 0.5 seconds and exporting again? Or it may even be that the main clip is not at the very beginning of the track, and that another clip underneath is playing for those first few moments - you need to get the timeline resolution to its highest level to check.

**Comment by tutyvijesh** [comment]
Thanks for getting back. I have reviewed source file and audio is clean on that.
That being said, I played on the exported video format and so far it seems to be working okay when I export in 4K-29.97 fps setting....bit strange though.
    On Tuesday, July 28, 2020, 12:54:25 PM GMT+5:30, rexdk <notifications@github.com> wrote:  
 
 


There is a visual judder at the start of that video - I wonder if your source file might be corrupted or faulty. Have you tried to set the 'Start' property to say 0.5 seconds and exporting again? Or it may even be that the main clip is not at the very beginning of the track, and that another clip underneath is playing for those first few moments - you need to get the timeline resolution to its highest level to check.

**Comment by rexdk** [comment]
I suppose it might be something to do with converting the format of your .mov files. I'm out of my depth now though... If you need to go further, I guess to try exporting with different profiles, and maybe reducing the number of clips to try to narrow it down - reducing the problem to something more specific. But maybe you feel you're OK now?

**Comment by RiedleroD** [comment]
same happens to me - I opened an issue in libopenshot for that, which might've been the wrong place 👀 

Anyway, so I tried around a bit and it happens when exporting to vp8 or vp9 in a resolution that's at least 1080p - My project file includes a soundless x264 video, a fadeout from that video & a vp9 video with opus audio below that.
