### ISSUE TITLE
It just stopped working.

### ISSUE THREAD

**Issue by DanielDarkSeanJulian** [OpenShot/openshot-qt#363]
When i was editing a test clip just to test the program out it suddently crashed on me. It mught have been 'cus i was also running another program. But are you honestly gonna tell me to only have OpenShot up and nothing else? I'll see if it happens again.

**Comment by JtLively** [comment]
The only time I've had crash issues with OpenShot is if I have over a dozen tabs open in a web browser, but that's rare. Did you read the crash details? What OS?

**Comment by DanielDarkSeanJulian** [comment]
There were no details, it just stopped working. And it happened again. I was again trying to seperate the audio from the video and it crashed. Really? I can't seperate the damn audio now? Um i think it was the  2.1.0 one. And thanks for the reply.

**Comment by JtLively** [comment]
I'm assuming this was on Windows -10, 7 ? Many are having similar issues. For now, I'd suggest importing the mp4 file to Audacity for editing and uploading separately, or doing your video editing in openshot, then maybe doing the aforementioned steps and recombining them. Best I got. I'm a Linux guy without a Windows box right now. Knowing what OS you're using is important for troubleshooting, especially when a product supports Win/OSX/Linux.

**Comment by DanielDarkSeanJulian** [comment]
Okay, good thing i have 2 other backup editing programs like audacity and Ezvid. thanks anyway. And i think it's windows 10 i have. They did release a update on OpenShot where you can seperate the audio without issue. But it's for mac or linux. So i can't get it right now. Thanks anyway for your help, hope i didn't come of as too pissed. Was just disapointet with the crashing parts.

**Comment by jonoomph** [comment]
@DanielDarkSeanJulian, separating the audio is supported in OpenShot 2.1.0 and on all OSes. I just gave it another try in Windows 10, and it works fine. Please download our latest daily installer:

1.  www.openshot.org/download - click '**Other Downloads**' link and grab the newest one
2.  Then enable 'Debug Mode (Verbose)' in the Preferences
3.  Quit OpenShot and delete both log files:
  - **/.openshot_qt/openshot_qt.log**
  - **/.openshot_qt/libopenshot.log**
4.  Re-launch OpenShot and trigger the crash as quickly as possible (to keep the log files small)
5.  Attach **both** log files here

Hopefully we can determine from the .log files what is happening (and crashing). Thanks!

**Comment by jonoomph** [comment]
It's possible that the crash is related to a specific video file. Please try with a few different video files, and see if there is any relationship between video file and crash. Thanks!

**Comment by DanielDarkSeanJulian** [comment]
Oh shit, never mind, i just realized i clicked wromg, i was supposed to click on mutliple channels. Uh, sorry...i got it now. Lol. Sorry for wasting your time XD Oh my god...Uh, thanks anyway. :) (Feeling stupid as fuck"

**Comment by jonoomph** [comment]
Glad it's working =)

**Comment by DanielDarkSeanJulian** [comment]
Thanks anyway.
