### ISSUE TITLE
Last frames of clip missing when viewed in project

### ISSUE THREAD

**Issue by matwolf** [OpenShot/openshot-qt#3635]
I use clips from a service as intros and transitions. When I view them in the project, the last frames are missing. Adjusting "end", "time" and so forth has no effect.

**Steps to reproduce the behavior:**
1. Download [this mp4](https://www.dropbox.com/s/tett81pldyx9xhz/DBS-Transition.mp4?dl=1)
2. Put that clip into an empty Openshot project in any track.
3. Click play and wait til it ran to its end. (It should display an ›empty‹ background, but there still are elements to be seen. It simply does not run to its end. Jumping to the end with Ctrl+→ yields the same result.)
4. Compare that last frame with what is seen in any player outside Openshot. Some 12 or 15 frames are not displayed. (See screenshots.)

**Expected behavior**
To have the clip be processed from its first to the last frame.

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Linux-5.7.9-1-MANJARO-x86_64-with-ManjaroLinux-20.0.3-Lysia
- Processor: 
- Machine: x86_64
- Python version: 3.4.3
- Qt5 version: 5.2.1
- PyQt5 version: 5.2.1
- Qt Detected Languages: ['en-GB']
- LANG Environment Variable: en_GB.utf8
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1595950874-bf0159bb-7cec1822-x86_64.AppImage

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/cnsytt5evilg1sn5vo6yuzi5gr3cc4k1/openshot-qt.zip) (15 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
Last frames:
- in Openshot: ![Screenshot_2020-07-30_09-58-01](https://user-images.githubusercontent.com/5408224/88897821-31054d80-d24c-11ea-8b4c-edc04926c466.png)
- In a player outside Openshot: ![Screenshot_2020-07-30_09-58-52](https://user-images.githubusercontent.com/5408224/88897832-35316b00-d24c-11ea-93b3-58361ed95ba7.png)

**Comment by matwolf** [comment]
Just found out, by accident: Is it possible that the clip "ends", when its audio-track ends? (I just ran into such an effect.)

**Comment by pmichaud** [comment]
The bug report I just opened ( #3649 )   may be related to this one  (I didn't see this issue prior to filing mine).  In Github issue #3649 I made/linked to a YouTube video showing how the final frames of a clip weren't being rendered properly, and have steps to fully reproduce the problem using a publicly available source clip.

Pm

**Comment by matwolf** [comment]
> …using a publicly available source clip.

Patrick, to the best of my knowledge the clip linked in my report above also is publically available. Did you try to download it and had trouble doing so?

However, it seems, there is a wider issue and not somehow related to a certain ›broken‹ clip or something.

Mat

**Comment by pmichaud** [comment]
Matthias:  My comment (and creating a new issue) wasn't meant to imply anything improper with your report -- I completed submission of #3649 before I noticed that your report described behavior that could be similar and figured I'd link the two issues.  I didn't even try to reproduce the behavior you reported (because I didn't come across it until after filing my issue).

Just now I went ahead and download the clip you posted in this issue, though, and on my system OpenShot does show the blank frame at the end of the clip (i.e., no bug is evident):
![image](https://user-images.githubusercontent.com/41962/89427955-72d93c80-d701-11ea-96a4-c7886871771b.png)

Single stepping through the frames of your test clip on my system, it looks as though the final 8 or 9 frames of the clip are all the blank frame (i.e., they're identical in the original).  So if OpenShot is only having difficulty with the final 8 or 9 frames -- the problem I'm having on my system -- then this clip wouldn't necessarily expose a bug.  From your screenshot, it looks as though your system used the same image for frames 00:00:05:17 through the end of the clip (which would be about the last 15 frames of the clip).

At any rate, the clip you've posted seems to work fine on my system.  I'm happy to try more tests with it (or other clips) though.  Perhaps you could try single-stepping frames on your system like I did and find out if a frame is being repeated at the end of the clip, and if so, which one?

Pm

**Comment by Popolon** [comment]
I have the same issue with Openshot 2.5.1 and libopenshot 0.2.5, ArchLinux, on the [following animation](https://popolon.org/animation/bonhomme_crepe.mp4) I made with Pencil2D. As you can view in a browser or player, on the few last frames, the character disappear, that's not the case in Openshot. After the log, it detects correctly the number of frames (39). mplayer, based on ffmpeg too, play it perfectly. 

project_data:INFO _set key: ['files'] values: {'acodec': '', 'audio_bit_rate': 0, 'audio_stream_index': -1, 'audio_timebase': {'den': 1, 'num': 1}, 'channel_layout': 4, 'channels': 0, 'display_ratio': {'den': 3, 'num': 4}, 'duration': 3.25, 'file_size': '226492', 'fps': {'den': 1, 'num': 12}, 'has_audio': False, 'has_single_image': False, 'has_video': True, 'height': 600, 'interlaced_frame': False, 'metadata': {'compatible_brands': 'isomiso2avc1mp41', 'encoder': 'Lavf58.45.100', 'handler_name': 'VideoHandler', 'language': 'und', 'major_brand': 'isom', 'minor_version': '512'}, 'path': '/data/animation/pencil2d/bonhomme_crepe.mp4', 'pixel_format': 0, 'pixel_ratio': {'den': 1, 'num': 1}, 'sample_rate': 0, 'top_field_first': True, 'type': 'FFmpegReader', 'vcodec': 'h264', 'video_bit_rate': 69689, 'video_length': '39', 'video_stream_index': 0, 'video_timebase': {'den': 12288, 'num': 1}, 'width': 800, 'media_type': 'video', 'id': 'PT743E93AA'} add: True partial: False remove: False

**Comment by WhymustIhaveaname** [comment]
I met the same issue today and I commented under [Issue #1752](https://github.com/OpenShot/openshot-qt/issues/1752#issuecomment-890314165).

**Comment by Richie314** [comment]
I have the same issue and would like to get help to fix this: this bug ruins all my video edits

**Comment by WhymustIhaveaname** [comment]
> I have the same issue and would like to get help to fix this: this bug ruins all my video edits

Use Shotcut. It is the same easy-to-learn as Openshot while having much fewer bugs. Shotcut is also the software recommended by Ubuntu 20.

**Comment by matwolf** [comment]
This 1½ yo. issue was closed with _no one even assigned_ – although it concerns others as well.

OpenShot-v2.6.1-dev-daily-9138-f2b89e32-2b8b05c7-x86_64.AppImage from Feb 18, 2022 still show this behaviour.

Considering to reopen it, assign a developer and solve the problem would be very much appreciated!

**Comment by matwolf** [comment]
> Use Shotcut

After 1 day with Shotcut I can happily approve this hint. Thanks, very much appreciated!

**Comment by jonoomph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Jumbled frames and audio lag (PTS Offset issue)](https://trello.com/c/OZbY1sQA/45-jumbled-frames-and-audio-lag-pts-offset-issue)

**Comment by Troughy** [comment]
4 year old issue. I was looking forward to using Openshot as my video editor, but it's hard to edit a video if the end of it is missing.

**Comment by Colorjet3** [comment]
> 4 year old issue. I was looking forward to using Openshot as my video editor, but it's hard to edit a video if the end of it is missing.

Hello @Troughy Are you just commenting or have you tried the latest 3.2.1 version and reporting that it is still an issue?

If you haven't yet tried, please go to openshot.org/download/#daily and download the latest dev daily build and give it a try.  If you are running Linux, then be sure to download the dev daily build AppImage and give it a try.

**Comment by Troughy** [comment]
> > 4 year old issue. I was looking forward to using Openshot as my video editor, but it's hard to edit a video if the end of it is missing.
> 
> Hello @Troughy Are you just commenting or have you tried the latest 3.2.1 version and reporting that it is still an issue?
> 
> If you haven't yet tried, please go to openshot.org/download/#daily and download the latest dev daily build and give it a try.  If you are running Linux, then be sure to download the dev daily build AppImage and give it a try.

Hello, I'm pretty sure I tried the latest version, since I just downloaded it a few days ago. It is still an issue.

**Comment by Colorjet3** [comment]
1.  What operating system/version are you running @Troughy?
2.  If you are running a Linux Distro, did you test using the AppImage?
