### ISSUE TITLE
App crashes on trying to access Preferences within the app!!

### ISSUE THREAD

**Issue by rg2209** [OpenShot/openshot-qt#3636]
**Describe the bug**
Openshot windows app crashes as soon as I try to open the preferences menu within the app. Tried with latest daily build, still no go. 

**Steps to reproduce the behavior:**
1. Go to "Edit" button
2. Click on 'Preferences'
3. And app crashes.

**Expected behavior**

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1595950975-bf0159bb-7cec1822-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/t0mitxx42dl09si6rdu3tvj0yeklxg48/openshot-qt.zip) (34 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/t0mitxx42dl09si6rdu3tvj0yeklxg48/libopenshot.zip) (0 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by nmat** [comment]
Duplicate of https://github.com/OpenShot/openshot-qt/issues/3608 ?

**Comment by rg2209** [comment]
Yes, that is correct.
