### ISSUE TITLE
Huge memory usage when watching a spliced clip

### ISSUE THREAD

**Issue by MarceloTerra0** [OpenShot/openshot-qt#3638]
Huge memory usage when watching a spliced clip

Watching the first half of the spliced clip doesn't yield anything abnormal, however when watching the intersection of the two splices (and while watching the 2nd half of the spliced video) there's a huge memory usage

![image](https://user-images.githubusercontent.com/62788203/89110645-c9e9c380-d41a-11ea-9ae1-bc343d17730e.png)
(OpenShot was the only program running on my computer. The clip size is 500MB)

**Comment by jakebesworth** [comment]
Same issue here: https://github.com/OpenShot/openshot-qt/issues/3592
