### ISSUE TITLE
Issues with program

### ISSUE THREAD

**Issue by drdave17** [OpenShot/openshot-qt#364]
When I play back imported mp3 audio used with my video teh audio keep breaking up. Not sure if this is true of all audio files.
Also once i export mp4 video the audio does not align with the video.
Sometimes the program will crash when I export a video

**Comment by JtLively** [comment]
What OS?
Which export settings are you using?
What are you doing outside of OpenShot when it crashes ?

**Comment by jreynojustin** [comment]
@drdave17 Closing because of failure to respond to more information.
