### ISSUE TITLE
Audio will only play through speakers, not headphones or any other device

### ISSUE THREAD

**Issue by ZachariBarnes** [OpenShot/openshot-qt#3640]
**Describe the bug:**
Audio will only play through system speakers, never through any other device

**Steps to reproduce the behavior:**
1. Go to Edit
2. Click on Prefrences
3. Select the Preview Tab
4. Select any audio device besides "DirectSound: Spreaders (Realtek(R) Audio)
5. Reboot Openshot (Or don't), No Audio.

**Expected behavior:**
Audio should play through speakers

**System Details:**
- OpenShot Version 2.5.1: 
- Operating System: Windows 10,

**Screenshots:** (Optional)
![image](https://user-images.githubusercontent.com/10678967/89135204-83b36380-d4f1-11ea-9468-c0b499b3f489.png)

**Comment by Fr33Radical** [comment]
My audio does not work with Logitech G633. I tried to look to modify _default.settings, but can't figure it out.
To save the preferences, it does not do it automatically. I have to make Project 'Save As...' to save them to notice a change but it only inserted an error cause the application will crash when I put Surround sound 7.1.

I've seen so many threads with issues with audio and it looks that it is still not fix.
How can we help with this?
