### ISSUE TITLE
Do not close and lose export settings when there is a validation failure.

### ISSUE THREAD

**Issue by dailytabs** [OpenShot/openshot-qt#3642]
**Describe the new feature:**
When there is a failure after clicking Export Video button in the Export Video dialog, such as invalid audio codec, please do not close this dialog and lose all my custom settings!

**Describe the solution you'd like:**
Keep the dialog open so I can fix it without repeating EVERY customization I made.

**Describe alternatives you have considered:**
You'd have to save as a new profile, every time.

**Comment by ferdnyc** [comment]
Yup! Closing as duplicate of #2881
