### ISSUE TITLE
exported video contains wrong part of original video when slowmotion effect is applied (time | slow | forward )

### ISSUE THREAD

**Issue by alreadyinuse** [OpenShot/openshot-qt#3647]
**Describe the bug**
exported video contains wrong part of original video when slowmotion effect is applied (time | slow | forward )

**Steps to reproduce the behavior:**
I took a video, deleted the beginning and end, to show just the explosion.
I right clicked on the result, choosing time | slow | forward | 1/16x, to slow down the explosion 
I export the video
The exported video is the correct length, but doesn't show the explosion, instead shows a different part of the video

also, the web site interface that brought me here, uploading the log files, seems to have glitched or just been programmed without a reasonable user interface.  no idea if it worked or not.  

**Expected behavior**
the exported video should show the same video that plays when the video is played in the openshot editor.

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  I'll be happy to paste the rest of this info if you'll add a copy function to your about box.
- Platform: 
- Processor: 
- Machine: 
- Python version: 
- Qt5 version: 
- PyQt5 version: 
- Qt Detected Languages: 
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1595950975-bf0159bb-7cec1822-x86_64.exe

**Log Files**
- openshot-qt.log: File too small or empty (not uploaded)
- libopenshot.log: File too small or empty (not uploaded) (yeah, I just uploaded them.)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.
                
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/5024296/openshot-qt.log)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/5024297/libopenshot.log)

**Comment by benoit747** [comment]
hello
i confirm this problem when i change the speed (up or down) of a cut sequence.
The preview video is ok but the final export is wrong.
the accelerated sequence in the exported video is not the same as that in the preview video

**Comment by gwestwood** [comment]
I similarly confirmed this issue when using the 2.5.1 release version on Windows 10.

**Comment by mitchweaver** [comment]
This is still an issue, 2.5.1 on Linux.

**Comment by JacksonRG** [comment]
It appears that this issue has been solved, in subsequent daily builds. If you encounter this issue, I would suggest trying a more recent build, until the next stable release.

**Comment by Username2481632** [comment]
I am having a similar problem but with the pixelated effect. The preview is just fine but final export doesn't include the effect.
