### ISSUE TITLE
Openshot daily build doesn't properly render final 8 or so frames of .mp4 files

### ISSUE THREAD

**Issue by pmichaud** [OpenShot/openshot-qt#3649]
**Describe the bug:**
I'm loading looping video clips -- when appended back-to-back they should make a seamless video.  The final eight frames of each clip are repeating the (n-9)th frame, causing a "skip/stutter" in the output.

**Steps to reproduce the behavior:**
1. I downloaded a (free) clip from https://pixabay.com/videos/loop-looping-motion-29566/ .  It's a 20-second clip that can be "looped".   I'm using the 1280x720 version, but it also occurs in the 1920x1080 version as well.
2. I then load the clip into a new project in OpenShot ( OpenShot-v2.5.1-dev2-1595950874-bf0159bb-7cec1822-x86_64.appimage ).  
3. I verified that the project settings match the clip settings (720p, 29.97 fps).
4. Drag the clip to one of the tracks in the timeline, starting at timecode 0.
5. Move the time marker to 00:00:19:20 (about 12 frames before the end of the clip)
6. Single-step the time marker forward, observe that each frame is different from the previous one....
7. .... until frame 00:00:19:24 is reached, (bug)at which point all of the frames contain the same image as 00:00:19:23(/bug).  (As rendered in other video editing programs, such as Kdenlive, the frames after 00:00:19:23 are not the same as 00:00:19:23.)
8. Drag a new copy of the same clip to be immediately following the existing clip (snaps into place).
9. Play a preview over the boundary where the two clips meet.  There's a noticeable "stutter" in the video where the final frames of the first clip are not being properly rendered.
10.  The problem remains if rendering the full video to a final output -- the final output also contains the incorrectly rendered frames and resulting stutter.

Again, I'm pretty sure the problem is in OpenShot and not in the video files themselves, as other video editors seem to be able to seamlessly append the clips together without jumps or stutters.

I did a similar test using the clip at https://pixabay.com/videos/octagon-abstract-lights-particle-5192/  and observe exactly the same behavior.

**Expected behavior:**
The final frames of a source clip should be completely rendered and not skipped.

**System Details:**
- OpenShot Version :    OpenShot-v2.5.1-dev2-1595950874-bf0159bb-7cec1822-x86_64.appimage
- Operating System / Distro:  Kubuntu 20.04

**Log Files:**
No crash, log files are too large to upload.

**Exception / Stacktrace:**
No crash/exception/stacktrace

**Screenshots:** (Optional)
I created a YouTube video illustrating the problem:   https://www.youtube.com/watch?v=-Z8teb5siSA

**Comment by DDHeuts** [comment]
I have the same problem. Nice to know I'm not alone .. but i don't find any solution

**Comment by pmichaud** [comment]
Just as a final note -- lack of action and developer response for this bug meant that I moved on to a different video editing environment.  Given the apparent lack of interest it hasn't been worth my time to try to reproduce in current versions.

Pm

**Comment by jonoomph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Jumbled frames and audio lag (PTS Offset issue)](https://trello.com/c/OZbY1sQA/45-jumbled-frames-and-audio-lag-pts-offset-issue)
