### ISSUE TITLE
Audio/Video issue in first 1-2 seconds of rendered video

### ISSUE THREAD

**Issue by nocxsville** [OpenShot/openshot-qt#3650]
**Describe the bug:**
The first 1-2 seconds is repeated twice with different speeds at the beginning of the rendered video. The first time with a faster speed, then again with the normal speed. This effects audio and video. I tried several export options like:

- MP4 (h.264) and HD 1080p 60 fps (1920x1080)
- Web and youtube HD

all with the same result. I also tried several video players and OpenShot versions (2.5.0 and 2.5.1).
I can link a video uploaded to youtube to demonstrate the issue.

Source video file is MP4
Source audio file is MP3

**Steps to reproduce the behavior:**
1. Add a video to the project and drop it in a track
2. Add a mp3 to the project and drop it in another track
3. render it

**System Details:**
- OpenShot Version 2.5.0 and 2.5.1
- Operating System / Distro: Windows 10

**Comment by sirius1242** [comment]
I met similar problem, and I even not use another sound track, just splicing some video clips, that problem happend. I didn't update openshot recently, just updated libopenshot from 0.2.5-2 to 0.2.5-3 serveral days ago.

System Details:
- OpenShot Version 2.5.1-1
- libopenshot Version 0.2.5-3
- Operating System / Distro: Arch Linux with kernel version 5.7.12

**Comment by sirius1242** [comment]
Emmm, downgrade libopenshot to 0.2.5-2 not solve the problem.
