### ISSUE TITLE
Vorbis audio encoding error

### ISSUE THREAD

**Issue by l0cKy93** [OpenShot/openshot-qt#3654]
Hello,

Openshots return an "A valid audio codec could not be found for this file." when I try to encode a video as webm with vp9 / vpx and vorbis as an audio codec. Using libopus does not return an error. 

System specs:
Ubuntu 20.04
Openshot 2.5.1 (libopenshot 0.2.5)
Installed via the image from flathub

**Comment by ferdnyc** [comment]
@l0cKy93 I just tried the same thing with the 2.5.1 AppImage, and had no problems. Can you test with one of the AppImage downloads from https://openshot.org/download/ ?

If the problem doesn't occur with the AppImage, it must be a Flatpak build issue. We don't create the Flatpak versions of OpenShot, you'd have to report any issues to its maintainer.

(If you have the same problem with the AppImage, then we can look into it further and figure out what's causing problems for you.)

**Comment by l0cKy93** [comment]
Hello,
I just checked the appimage and there the conversion works flawless.

**Comment by ferdnyc** [comment]
I believe @eszlari is still the Flatpak maintainer for OpenShot, perhaps they can take a look.

**Comment by eszlari** [comment]
Why would anybody use vorbis instead of opus?
