### ISSUE TITLE
screen of video is black

### ISSUE THREAD

**Issue by MickyBee7** [OpenShot/openshot-qt#3660]
**Question:**
I can see the picture of the Video, but in the display-window ist stays  black while playing

**System Details:**
- OpenShot Version 2.5.1
- Operating System / Distro: [e.g. Windows 10

**Screenshots:** (Optional)
![grafik](https://user-images.githubusercontent.com/69437785/89742775-2c873300-da9d-11ea-8bb6-c360e5c7a813.png)

**Comment by nmat** [comment]
Hello,

The screen will be empty until you place the video in the timeline. The window you see there is a summary of the items used in openshot to create the video. Try to drag the video to the timeline and you will start to see a preview of the video in the frame.

Also see: https://cdn.openshot.org/static/files/user-guide/quick_tutorial.html#step-2-arrange-photos-on-timeline
