### ISSUE TITLE
OpenShot limits FFmpeg export to 16 threads

### ISSUE THREAD

**Issue by bdrung** [OpenShot/openshot-qt#3674]
OpenShot 2.5.1 limits the number of FFmpeg threads to 16 and the OMP threads to 24. Setting the number of threads to the maximum does not fully utilize the newly bought AMD Ryzen 9 3900X which has 12 cores and 24 threads. A video export takes roughly the same amount of time compared to an AMD Ryzen 7 3800X with 8 cores and 16 threads.

Please support increasing the number of threads to fully utilize the AMD Ryzen 9 3900X processor (and even Ryzen Threadripper).

**Comment by ferdnyc** [comment]
@bdrung 

There is very much a law of diminishing returns when it comes to increasing thread count during encoding -- I hope you're drowning in RAM, if you want to go higher.

What platform are you on? I can arrange to have a test build generated with increased thread limits, so we can evaluate the impact of doing this. AFAIK none of the developers have access to hardware like that so you'll be in uncharted waters. But if you're willing to test and there's a chance it might matter... sure, I'm game.

**Comment by bdrung** [comment]
This is a newly built system with a Gigabyte B550M Aorus Pro mainboard, a AMD Ryzen 9 3900X processor, and 32 GiB DDR4-3200 RAM running Ubuntu 20.04.

I am willing to test. Let me know which test cases I should run on this machine.

**Comment by ferdnyc** [comment]
@bdrung 

Ah... hm. Are you running OpenShot from the AppImage, or installed via `apt`? The latter may make things _slightly_ trickier, though not impossible. I can probably have our Travis scripts package some test `.deb`s, the CI jobs are running on Focal (some of them).

**Comment by bdrung** [comment]
I am currently using the AppImage version, because I failed to build the updated `.deb` package.

**Comment by bdrung** [comment]
Hi,

the test was not successful. Only the OMP Threads could be raised, but not the FFmpeg Threads. See `~/.openshot_qt/openshot.settings`:

```
 {
  "min": 0,
  "max": 128,
  "value": 24,
  "title": "OMP Threads (0 = Default)",
  "type": "spinner-int",
  "restart": true,
  "category": "Performance",
  "setting": "omp_threads_number"
 },
 {
  "min": 0,
  "max": 16,
  "value": 16,
  "title": "FFmpeg Threads (0 = Default)",
  "type": "spinner-int",
  "restart": true,
  "category": "Performance",
  "setting": "ff_threads_number"
 },
```

When trying to export with this value, it failed:

```
         app:INFO openshot-qt version: 2.5.1-dev2
         app:INFO libopenshot version: 0.2.5-dev2
         app:INFO platform: Linux-5.4.0-42-generic-x86_64-with-Ubuntu-20.04-focal
         app:INFO processor: x86_64
         app:INFO machine: x86_64
         app:INFO python version: 3.6.9
         app:INFO qt5 version: 5.9.5
         app:INFO pyqt5 version: 5.10.1
[...]
      export:INFO Error type string: Wrong number or type of arguments for overloaded function 'FFmpegWriter_SetVideoOptions'.
  Possible C/C++ prototypes are:
    openshot::FFmpegWriter::SetVideoOptions(bool,std::string,openshot::Fraction,int,int,openshot::Fraction,bool,bool,int)
    openshot::FFmpegWriter::SetVideoOptions(std::string,int,int,openshot::Fraction,int)

  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "/tmp/.mount_ktGakw/usr/bin/windows/export.py", line 1016, in accept
    'hours': seconds_run / 3600,
UnboundLocalError: local variable 'seconds_run' referenced before assignment
 main_window:INFO Export Video add cancelled
```

BTW, I have access to diskless, bare-metal server hardware running headless Debian live systems. I can easily run test cases there, if OpenShot could be operated headless on the command line. In case you are interested how good OpenShot will perform on systems with 56 or maybe even 128 threads.
