### ISSUE TITLE
Invaild Load Key, '{' (URGENT)

### ISSUE THREAD

**Issue by shaaronkingu** [OpenShot/openshot-qt#3682]
Here's the file that won't open and gives a pop up message "invalid load key, '{' . please someone help, this video is immensely important to me, I need to be able to finish it
i have openshot version 2.5.1,Operating System windows 10 and i'm incredibly nervous about this. if I have to restart then that's several weeks of work gone. So please someone HELP ME!

[nostradamus.zip](https://github.com/OpenShot/openshot-qt/files/5126043/nostradamus.zip)

**Comment by jandermoreira** [comment]
Since yesterday I have the same problem!
