### ISSUE TITLE
Blender no inicia

### ISSUE THREAD

**Issue by Tomasitoram** [OpenShot/openshot-qt#3686]
**Describa el problema**
Quiero direccionar openshot al ejecutable de Blender desde las preferencias y al seleccionar la carpeta donde se encuentra el ejecutable de blender (C:\Program Files\Blender Foundation\Blender 2.83) no me muestra el contenido de la carpeta

**Pasos para reproducir el comportamiento:**
1. Ir a «Editar»
2. Pulsar en «Preferencias»
3. Desplazarse hasta «Comando de Blender (Ruta)> Examinar>C:\Program Files\Blender Foundation\Blender 2.83»
4. Ver el error (No se muestra el contenido de la carpeta incluso cuando está seleccionado "Todos los archivos")

**Comportamiento esperado**
Que se muestre el ejecutable de blender junto a los demas archivos .dll, .txt y HTML que existen en esa carpeta

**Detalles del sistema**
- OpenShot Version: 2.4.4-dev2
- libopenshot Version:  0.2.4-dev1
- Platform: Windows-10-10.0.18362
- Processor: Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['es-MX', 'es-ES', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1598277873-f71051e8-7b76f1de-x86_64.exe

**Archivos de registro**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/xv9a5f1mpgerwsisk04yc4kn09esslqc/openshot-qt.zip) (19 KB)

**Excepción / Rastreo de pila**
```No stacktrace found in log files```

**Capturas de pantalla** (Opcional)
Si se aplica, añada capturas de pantalla para ayudar a explicar el problema. Puede incluir capturas
copiando y pegando en GitHub o arrastrando y soltando en la página de GitHub. Todas las imágenes
son públicas y por tanto no debería publicar capturas que contengan información personal.
                
![Captura de pantalla (3)](https://user-images.githubusercontent.com/70337009/91468858-f7cef600-e868-11ea-8e18-bf0eb521b32c.png)

**Comment by rexdk** [comment]
Problem in English :
I want to direct openshot to the Blender executable from the preferences and when selecting the folder where the blender executable is located (C: \ Program Files \ Blender Foundation \ Blender 2.83) it does not show me the contents of the folder

Possible solution: update OpenShot - it works for me with the latest version
Posible solución: actualice OpenShot; me funciona con la última versión

**Comment by ferdnyc** [comment]
Closing as a duplicate of #3740, this should be fixed by PR #3749.
