### ISSUE TITLE
Sorry, There was an Error exporting your video: Could not create hwdevice

### ISSUE THREAD

**Issue by ManiacRS** [OpenShot/openshot-qt#3689]
Hello everyone, newbie here!
I am trying to use the hardware acceleration in Openshot 2.5.1 in Ubuntu 18.04. I am using a fairly old laptop with an i3 M430 and an NVidia GT335M. I am using the NVidia binary driver and I update frequently.

Am I missing some setting? Is there something else I should do? Do I need to give you guys more info for you to help me?

P.S. I am using an appImage version of Openshot and NVidia driver version 340.108

**Comment by stratus-ss** [comment]
I am getting the same error on Arch Linux, latest openshot and a GTX970 with drivers 450.66 when trying to create MP4 (HEVC va)

**Comment by cmmh** [comment]
I have found that if you're using the appimage file, it doesn't have permission to open the /dev/dri files properly.   Once I installed (on Ubuntu) the .deb version it worked properly.

**Comment by doppel-T** [comment]
Hi, 
I have the same problem, I hope I get help here.
Which information shall I still deliver ?

Thanks in advance

Ubuntu 20.04 LTS
GeForce GTX 980 (nvidia-driver-450)
OpenShot 2.5.1 installed not the AppImage

**Comment by cmmh** [comment]
Make sure your user has permission to access the video drive /dev/ devices.

**Comment by ManiacRS** [comment]
> Make sure your user has permission to access the video drive /dev/ devices.

Well, I can go into that folder and view the files. Is that what you mean? If not how will I check whether I have the correct permissions..?

**Comment by james-h-dt** [comment]
Seeing the same problem when trying to use graphics hardware. 

Tried to use target: VA-API. Same error message raised, then app failed. 

Workaround: Use a CPU target instead. Worked okay this time. 

My platform: Arch Linux, latest build, Intel 620 integrated graphics. Tried adding user to group "video", on the off-chance. Saw no improvement.

**Comment by dhjw** [comment]
On my Ubuntu 20.04 system with Ryzen CPU I ran `sudo apt install mesa-va-drivers` and now it works. I installed openshot via the official PPA. I'm using the kisak-mesa repo for GPU drivers.

**Comment by Exordio** [comment]
Same problem
