### ISSUE TITLE
Windows 10 / Openshot 2.1.0; crashing when setting a clip to a higher speed

### ISSUE THREAD

**Issue by Jaccoky** [OpenShot/openshot-qt#369]
If you select a clip in the timeline and choose "Time... Fast... Forward... 2x", the application crashes as soon as you put the time-slider into this clip.
Also, if you try to export the project to a video, the export (application) crashes as soon as the 'fast' clip is reached.

On Windows 10, Openshot 2.1.0

**Comment by otrapa** [comment]
I have the same problem. But another crashes are very common even if I just do the basic work, try to export video and ... crash. It's pure randomly, which is the worst because I can't fix it in any way. I hope some new, more stable version, will be out soon.
Win 10 64bit, OpenShot version 2.1.0

**Comment by jonoomph** [comment]
Please download our latest daily installer:

1.  www.openshot.org/download - click '**Other Downloads**' link and grab the newest one
2.  Then enable 'Debug Mode (Verbose)' in the Preferences
3.  Quit OpenShot and delete both log files:
  - **/.openshot_qt/openshot_qt.log**
  - **/.openshot_qt/libopenshot.log**
4.  Re-launch OpenShot and trigger the crash as quickly as possible (to keep the log files small)
5.  Attach **both** log files here

Hopefully we can determine from the .log files what is happening (and crashing). Thanks!

**Comment by otrapa** [comment]
OK, so I did exactly what you wrote. Then I imported only one file (short h.264 mpeg-4 avc 720p video), chose Time-Fast-Forward-2X option, chose Export video, clicked Export video ... then crash. Logs attached in ZIP (because it wrote "We don't support that file type". I'm gonna try another simple work with the program to see what will happen.
OpenShot-v2.1.0-28
[OpenShotLogs.zip](https://github.com/OpenShot/openshot-qt/files/518274/OpenShotLogs.zip)

**Comment by Jaccoky** [comment]
Hi Jonathan,

 

Thanks for your reply. For installing the update, I had to reboot (because some DLL files were still in use and could not be overwritten). After rebooting, I switched on the Debug-mode and restarted OpenShot, but I could not find where the log-files were written. (They are not written in de Program-files folder and I could also not find them in the ‘My documents’ folder).

 

I then ran OpenShot and tried to analyze the disk-activity, but I did not see that the ‘launch.exe’ process was writing anything to any log file. (Also I did not notice any speed delay when switching on the debugging…)

 

I then tried to reproduce the 2 crashes I noticed earlier, however, I was not able to reproduce them. So drag-dropping files from the file-system straight into the timeline now worked fine and also speeding up a clip did not cause a crash anymore.

 

My conclusion is that the bug have either been solved already in your development process, or they may have been caused by locked DLL’s (however, my guess is that it is the first option).

 

If you have any further questions, please don’t hesitate to contact me, I am happy to help you with this very nice software!

 

With kind regards,

 

Jacco Kooij

**Comment by otrapa** [comment]
Another crash:
I imported two files (short h.264 mpeg-4 avc 720p video and .mp3 song), sliced video, kept both sides, at first part chose Volume-Entire Clip-Level 0%. Then I started work with the song - chose Volume-End of Clip-Fade Out (fast). That's it, all my work. I clicked on the red dot (Export Video) ... crash. And I had many others - a few/or a bit more different steps, then crash.
As a video-editing novice I really like this program for it's simplicity and "it has all I need" but this is annoying and almost impossible to use for some larger work (to create a big vid after vacation etc.).
[logs.zip](https://github.com/OpenShot/openshot-qt/files/522171/logs.zip)

**Comment by jonoomph** [comment]
Is it possible your system is running out of memory? Also, if don't mind sharing a small test project (including media, all zipped up), I can debug this in more depth, and hopefully reproduce the crash. 

There are lots of possible causes for a crash like this:
1) weirdness in a video or audio file
2) memory leaks / running out of memory
3) memory corruption
etc...

The trick is, we need to be able to reproduce the crash pretty consistently, so I can get a debugger on it, and see where it's blowing up. =) Thanks!

**Comment by otrapa** [comment]
The truth is ... my computer is pretty stable. I have no problems with another programs like this. I have legal Win 10, no warez in my pc, don't play games, using just a few programs overall. On desktop I have a small widget to see system information so I can tell, there is no running out of memory while using OpenShot. And I think there is no weirdness in a video and audio file I used (attached files from my last report). That's why it's so weird OpenShot doesn't work on my pc:-/
[files.ZIP](https://github.com/OpenShot/openshot-qt/files/526415/files.ZIP)

**Comment by lupus78** [comment]
I'm having a similar issue, but on Ubuntu 14.04 with OpenShot 2.10 (installed from PPA)

I have a GoPro 3+ footage in 1080 60fps. What I'd like to do is, to slow down the middle part of the video, so it start normal speed, at 11sec goes to 1/2 speed, and at 19sec back to normal speed. The whole video is 26sec. When I'm exporting it at around 30% (where the slow part is reached) OpenShot crashes.

If I just import the video and without any cutting just set the whole clip to slower/faster, the export crashes the same way.

The last error on the console is this: 
*** Error in `/usr/bin/python3': free(): invalid next size (normal): 0x0000000002d8ccb0 ***
Error logs attached.
[openshot_logs.zip](https://github.com/OpenShot/openshot-qt/files/531818/openshot_logs.zip)

I can send you the project and the video file if necessary.

**Comment by otrapa** [comment]
So, the last version (OpenShot-v2.1.0-41-g30897ac-49-589-x86_64) is much more stable, but still, if I select a video in the timeline, choose Time-Fast-Forward-2X, push green play button, program crashes.

**Comment by jreynojustin** [comment]
OpenShot is now in Version 2.2 if you are still noticing issues in the latest version please re-open this issue.

**Comment by Gomisan** [comment]
Using the latest (at this time) version of OpenShot and this bug is still present. v2.3.1 on Win10 64bit. Changing the speed of a clip, lancher crashes the minute you try and preview the sped up section.

From what I'm reading on various google searches this issue has existed for years!

**Comment by derrabauke** [comment]
Also on _Ubuntu 16.04_ with _Openshot 2.3.2_ this Bug still present.
Got a small .mkv file (~50Mb) --> 1/2x-times-slower on a clip --> program renders uncontrollable and process crashes.

Would be really cool, if you can fix that. Besides that I like Openshot a lot! Simple and really fast.
greets & keep up good work

**Comment by johnparra** [comment]
Also on Archlinux not work when run Time and Forward->2x
Version OpenShot 2.3.4

**Comment by Martinique** [comment]
Adjusting Time property of a clip makes OpenShot crash immediately or when starting playback, so I'm guessing I hit this bug. Windows 7 x64, OpenShot 2.3.4 (in case this is format-specific like #748 I'm trying to adjust a FF-HuffYUV clip)

**Comment by varmox** [comment]
Also on Arch Linux 4.12.4 with OpenShot 2.3.4.2. OpenShot Crashes when I speed up (2x) a small part of a 5min. Footage from GoPro Hero 4 Silver 1080p.

**Comment by eanbowman** [comment]
OpenShot Video 2.3.4 and Fast Forward x32 in Windows 10 does not actually seem to make the video faster. It merely crops the clip. The video exports VERY fast. The preview seems to take forever to scrub, maxing out only some of my CPU's capability while doing so.

Also the audio seems to clip massively if I add an audio track to my GoPro footage.

AMD Phenom II 1055T, 16GB RAM

![image](https://user-images.githubusercontent.com/1637212/29438683-5486686a-8386-11e7-8d30-b63918141643.png)

**Comment by brianthornock** [comment]
I just ran in to this problem on 2.5.1. I tried to increase time to 16x and it crashes during export.
