### ISSUE TITLE
Openshot resize edge clip not working under Linux

### ISSUE THREAD

**Issue by EasyNetDev** [OpenShot/openshot-qt#3695]
Hi,

I'm trying to edit a video and I'm facing a strange behavior under Linux. I've searched this issue on internet, but I couldn't find a fix.
Same version of OpenShot under Windows is working well, the cursor is changing to double end arrow and I can resize the clip without issue. But under Linux is impossible. Only once I was able to do it.
I've tested on my laptop with Debian Bullseye, OpenShot 2.5.1 on KDE and also same OS under a VM on ESXi 6.7. Both they have same behavior.

Here is the video:
https://youtu.be/h-q19CUrn8s
![Screenshot_20200829_143544](https://user-images.githubusercontent.com/1823016/91637082-ed962e80-ea05-11ea-9c81-d45c8d33b28d.png)

Is extremely annoying this bug. I have to go to slice the video which can be very imprecise.

**Comment by RiedleroD** [comment]
works for me on arch both on xorg+qtile and wayland+sway. Maybe change the title to "on Ubuntu"

**Comment by mbootsman** [comment]
Same problem here.
Ubuntu 20.10
OpenShot version 2.5.1

**Comment by OceanWolf** [comment]
Same on Debian Buster (using Backports) with 2.5.1 with LXDE as my window manger.

**Comment by OceanWolf** [comment]
Some more info.  I have just tested on Ubuntu live dvds of 20.04 and 21.10, which means I get a clean install on a clean OS.  No issue on 20.04 which carries 2.4.3 in its repo; but the issue does occur on 21.10 which carries 2.5.1 so the issue seems to occur somewhere between these two versions.

**Comment by benvantende** [comment]
I am on 2.6.1 and also experience this on the latest Kubuntu 22.10. I also noticed that scrolling values up and down in the properties sidebar does not work either. It is hard to pinpoint, as it did work in the version before 22.10.

**Comment by Colorjet3** [comment]
It is best to go to openshot.org/download/#daily build and download the latest available DEV Daily Build and give it a try.  Run the AppImage and see if that works better for you.  Many fixes.  A new production release is coming soon.

Please keep us updated.

**Comment by benvantende** [comment]
Hey! Thanks for the suggestion. The resize edge works now, but the value scrolling does not. I am now thinking I just imagined that was possible earlier. I do not use Openshot that often. You should be able to use the mouse wheel in these fields, right? Should I submit a bug report? I also do not do  that a lot ;)

**Comment by benvantende** [comment]
Also, really appreciate the work the team is putting into Openshot. Awesome!

**Comment by Colorjet3** [comment]
Hello @benvantende.  Thank you for the kind words.  The development team is very hard at work to continue improving the product and getting ready for a production release with all of the fixes and enhancements.

When you say "..value scrolling.." I think you are talking bout the Properties page value fields.  If that is the case, the scrolling never was or has been a feature.  The only two ways you can change the values is by holding the mouse down and scrolling right or left, or double click the value and manually type you need.

However, this would be a great feature to add to OpenShot.  I am going to document this and submit it to the development team.

Thank you again for your feedback and good luck with your project(s).
