### ISSUE TITLE
"Add Track" Timeline menu icon has no effect

### ISSUE THREAD

**Issue by rexdk** [OpenShot/openshot-qt#3696]
2.5.1-dev2 Win10
Above the Timeline are some icons; the left one is a plus, which says "Add Track" when hovered over. It's next to "Snapping Enable."

It does not add a track, or do anything else.

I've spent 45 mins searching for an existing issue on this - sorry if I've missed it. These icons are undocumented, so I guess it's possible this works in an unexpected way, but I can't imagine what it is, if so.

**Comment by ferdnyc** [comment]
So it doesn't! Seems I broke that way back in _January_. I think you're the first to notice.

Easy fix, fortunately. Looks as though I was just trying to be too clever for my own good in Python.

**Comment by rexdk** [comment]
Brill - thank you
