### ISSUE TITLE
System sound disabled or distorted in Windows 10 when running OpenShot video preview

### ISSUE THREAD

**Issue by LukeFarrer** [OpenShot/openshot-qt#3699]
Hi Support

I am running Windows 10 on a Dell Alienware laptop.
I am using the system speakers (Realtek - R - Audio)
Before running OpenShot the sound works fine.
However when previewing a video containing sound I cannot hear anything. It's like pressing Preview/Play disables the system sound. I once got a weird burst of noise, then nothing. Sometimes, but not always, the entire system sound is also disabled. (can't hear anything on YouTube, for example...)
What's more, the video preview playback is very slow and choppy.

I get this issue with .mp3 files, .wav files, and videos with sound in them.

This definitely looks like a bug. It is reproducible on today's build.

I tried to upload the log files but it said they were too large. So here they are:

[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/5150798/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/5150800/openshot-qt.log)

When can we get a fix for this?

Luke Farrer

**Comment by rexdk** [comment]
Hi Luke
I'm a humble user rather than a guru, but I wonder whether OpenShot is simply proving too great a load for your laptop (too little RAM or too slow cpu). Video editors need a lot of processing power. Sorry if you know more than me about this! But I run the latest OpenShot with no problem on a Win10 machine.

**Comment by LukeFarrer** [comment]
Thanks for your reply!
I'm using 32GB ram and the latest alienware laptop. I don't think that
power is an issue. It works well on my older laptop but not on this one,
strange.
Luke

**Comment by rexdk** [comment]
@LukeFarrer  Strange, as you say. I'm afraid I'm out of my depth now...

**Comment by brockmanah** [comment]
I am also having this problem.  Openshot appears to be incompatible with Realtek's drivers.  I have a brand new build - 32 gigs ram gaming PC, and I mostly do music production sort of stuff.  I don't have audio problems anywhere else, only on Openshot.
