### ISSUE TITLE
Windows 10 / Openshot 2.1.0; Crash when dragging a file from the file-system to the Timeline-pane

### ISSUE THREAD

**Issue by Jaccoky** [OpenShot/openshot-qt#370]
On Windows 10, with Openshot 2.1.0, the application crashes as soon as you drag a file from the file-system on (over) the Timeline-pane.

**Comment by jreynojustin** [comment]
OpenShot is now in Version 2.2 if you are still noticing issues in the latest version please re-open this issue letting us know.
