### ISSUE TITLE
Final render doesn't match preview..

### ISSUE THREAD

**Issue by ozzyOuzo** [OpenShot/openshot-qt#3703]
**Describe the bug:**

Final rendering contains video elements that are supposed to have been cut out in the timeline.

**Steps to reproduce the behavior:**
using mkv/h264 input project videos

**Expected behavior:**
final rendering have to match rendering from the preview...

**System Details:**
- OpenShot Version [2.5.1]:
- Operating System Windows 10

**Comment by ozzyOuzo** [comment]
Tried out the same process using input videos using mpeg4 codec . same error occurs.

i'm cutting out videos multiple times in the timeline (e.g removing parts)
i'm also changing some parts to fast forward 4x
few transitions and effects are used (fade and pixelated)

so again final rendering is showing non visible parts of videos (were supposed cutted ouf)
and preview seems ok.

**Comment by gwestwood** [comment]
I believe that this is the same issue as #3647

**Comment by ozzyyzzo4096** [comment]
it seems quite similar.
