### ISSUE TITLE
Windows 10 / Openshot 2.1.0; language 'en_US' can be chosen in 'Settings' but is not supplied

### ISSUE THREAD

**Issue by Jaccoky** [OpenShot/openshot-qt#371]
When selecting 'American English' as GUI-language, you will still get the default language, because the en_US folder is not available.
Solution: Either provide the en_US locale folder or remove the option from the list...

**Comment by jreynojustin** [comment]
OpenShot is now in Version 2.2 if you are still noticing issues in the latest version please re-open this issue letting us know.
