### ISSUE TITLE
Video Audio is Off when Exporting

### ISSUE THREAD

**Issue by thatoneXman** [OpenShot/openshot-qt#3720]
I'm slightly new to Video Editing, so the answer is probably Glaringly Obvious. When I export My video, the Audio is EVER SO SLIGHTLY off. How can I fix this?

- OpenShot Version: 2.5.1
- Operating System: Windows 10

**Comment by thatoneXman** [comment]
Keep in mind, I need an answer that DOESN'T require getting a More Powerful Hard Drive.

**Comment by ferdnyc** [comment]
@thatoneXman As far as I know all hard drives run on the same 12V + 5V power, so I don't think that'll be an issue. 😉

To help with your problem, we'll really need a lot more information about what you're trying to do, and what's happening that you don't expect.

1. Where are the audio and video for your project coming from? Separate files? The same file?
1. What file type (AVI, MP4, MP3 etc) are the file (s).
1. What is the encoding for each file?
1. What edits are you making after placing the files on the Timeline? Are you using only part of some clips, are any of them starting from a point after the beginning of the file?
1. If the audio and video are in separate files, how are you lining them up?
1. What format are you using to export? Does the same problem occur if you try a different format?

If you can provide a small sample input file that exports incorrectly, that's especially helpful.
