### ISSUE TITLE
The tutorial stays open and the buttons don't work... 

### ISSUE THREAD

**Issue by josephliv** [OpenShot/openshot-qt#3723]
Hi, when I open this on LinuxMint xfc the Welcome box pops up and the "hide tutorial' and the "next" button are not clickable. The checkbox that says "Yes, I would like to improve OpenShot!" doesn't check either. 
So I have to just work around it, everything else works fine and I just created and exported a video without any issues. This is just a very minor bug and sure will be fixed soon.

**Comment by ferdnyc** [comment]
@josephliv What version of OpenShot are you running? (You can check in Help > About.)

That sounds like a bug from an older version. The current version of OpenShot is 2.5.1, and that bug should be fixed.
