### ISSUE TITLE
Can we add captions to the video for certain duration in the video?

### ISSUE THREAD

**Issue by SriChIN** [OpenShot/openshot-qt#3725]
**Question:**
A clear and concise question, with enough context and explanation for people to answer it.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your question. You can include screenshots by
copy/pasting them here, dragging-and-dropping into this form, or clicking below and loading
images saved to your computer. All images are public, so please don't post screenshots
containing personal information.

**Comment by ferdnyc** [comment]
If I understand the minimally-completed question form correctly, _sorta_ yes.

OpenShot doesn't support subtitle tracks, but you can use the Title Editor to create text overlay captions. As with any other clip, you can display title images for any time duration you wish.

So, in terms of "burned-in" caption/subtitle graphics, yes it's possible.
