### ISSUE TITLE
Appimage version crash on moving video to timeline

### ISSUE THREAD

**Issue by damascene** [OpenShot/openshot-qt#3729]
**Describe the bug**
Crash when moving imported file to the timeline

**Steps to reproduce the behavior:**
1. import a video
2. Move it to time line
3. Crash

**Expected behavior**
Shouldn't Crash

**System Details**
- OpenShot Version: 2.5.1
- libopenshot Version:  0.2.5
- Platform: Linux-4.19.0-10-amd64-x86_64-with-debian-10.4
- Processor: 
- Machine: x86_64
- Python version: 3.4.3
- Qt5 version: 5.2.1
- PyQt5 version: 5.2.1
- Qt Detected Languages: ['en-US', 'en']
- LANG Environment Variable: en_US.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Not able to verify issue still exists in daily build

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/nz22w0c0s5ktq0hce3s7672swlmyqsm2/openshot-qt.zip) (23 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/nz22w0c0s5ktq0hce3s7672swlmyqsm2/libopenshot.zip) (11 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Comment by aswen** [comment]
I experienced exactly the same on Debian Buster:
```
10:58:26 alex@nvc3691 /data/software $ uname -a
Linux nvc3691 5.9.0-0.bpo.2-amd64 #1 SMP Debian 5.9.6-1~bpo10+1 (2020-11-19) x86_64 GNU/Linux
10:59:04 alex@nvc3691 /data/software $ cat /etc/debian_version 
10.7
```
Below the result of `strace ./OpenShot-v2.5.1-x86_64.AppImage >> /tmp/OpenShot.log 2>&1`:
[OpenShot.log](https://github.com/OpenShot/openshot-qt/files/5729137/OpenShot.log)

**Comment by rodlopesoficial** [comment]
I also have the same issue on chromebook. No matter what I try to add to timeline, it crashes.
