### ISSUE TITLE
What is my terminal telling me when I try to install OS?

### ISSUE THREAD

**Issue by Hanedinges** [OpenShot/openshot-qt#373]
Hi! I really nead a good video editor and hopefully this version won't crash all the time. 
But how to install it? I downloaded it, but when I click on the download, nothing happens or opens...
Then I I followed the instructions: 
sudo add-apt-repository ppa:openshot.developers/ppa
sudo apt-get update
sudo apt-get install openshot-qt

But the last command is not working...this is what my terminal shows, could any body help me?

This PPA contains the current stable version of OpenShot Video Editor.

If you would rather the bleeding-edge version, check out the following URL:
https://launchpad.net/~jonoomph/+archive/openshot-edge

 Meer info: https://launchpad.net/~openshot.developers/+archive/ubuntu/ppa
Druk op [ENTER] om door te gaan of op ctrl-c om het toevoegen ervan te annuleren

gpg: sleutelring `/tmp/tmp6ha0c4sl/secring.gpg' is aangemaakt
gpg: sleutelring `/tmp/tmp6ha0c4sl/pubring.gpg' is aangemaakt
gpg: opvragen sleutel B9BA26FA van hkp server keyserver.ubuntu.com
gpg: /tmp/tmp6ha0c4sl/trustdb.gpg: betrouwbaarheidsdatabank (trustdb) aangemaakt
gpg: sleutel B9BA26FA: publieke sleutel "Launchpad OpenShot Development PPA" geïmporteerd
gpg: Totaal aantal verwerkt: 1
gpg:               geïmporteerd: 1  (RSA: 1)
OK
simone@simone-Latitude-D620:~$ apt-get update
E: Kon het vergrendelingsbestand '/var/lib/apt/lists/lock' niet openen - open (13: Toegang geweigerd)
E: Kan de map /var/lib/apt/lists/ niet vergrendelen
E: Kon het vergrendelingsbestand '/var/lib/dpkg/lock' niet openen - open (13: Toegang geweigerd)
E: Kan de beheersmap (/var/lib/dpkg/) niet vergrendelen. Heeft u beheerdersrechten?
simone@simone-Latitude-D620:~$ sudo apt-get install openshot-qt
Pakketlijsten worden ingelezen... Klaar
Boom van vereisten wordt opgebouwd       
De status informatie wordt gelezen... Klaar
E: Kan pakket openshot-qt niet vinden
simone@simone-Latitude-D620:~$ add-apt-repository ppa:openshot.developers/ppa
Fout: moet als root uitgevoerd worden
simone@simone-Latitude-D620:~$ apt-get update
E: Kon het vergrendelingsbestand '/var/lib/apt/lists/lock' niet openen - open (13: Toegang geweigerd)
E: Kan de map /var/lib/apt/lists/ niet vergrendelen
E: Kon het vergrendelingsbestand '/var/lib/dpkg/lock' niet openen - open (13: Toegang geweigerd)
E: Kan de beheersmap (/var/lib/dpkg/) niet vergrendelen. Heeft u beheerdersrechten?
simone@simone-Latitude-D620:~$ ja
ja: opdracht niet gevonden
simone@simone-Latitude-D620:~$ nee
Opdracht ‘nee’ niet gevonden

**Comment by jonoomph** [comment]
Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily **AppImage** of OpenShot. Make the file executable, and double click it. No installation needed, and it should work on most Linux distros. Thanks!
