### ISSUE TITLE
Import Gimp project file

### ISSUE THREAD

**Issue by CHJ85** [OpenShot/openshot-qt#3733]
Hi there. So I'm able to import Krita project files into Openshot. But for some reason, it doesn't work with Gimp.
Could this be fixed somehow?
Would be a nice feature because Adobe users are used to all these apps intertwining with eachother.
I'm getting the same result in Kdenlive. Krita projects work but Gimp doesn't. So I don't know if this might have something to do with the way Gimp project files are being saved.

**Comment by ferdnyc** [comment]
@CHJ85 
See, now in my testing so far, I've found exactly the opposite. On my Linux system 
running OpenShot 2.5.1 / libopenshot 0.2.5 built against system packages (Qt 5.14.2, ffmpeg 4.2.4, ImageMagick 6.9.11.27), GIMP `.xcf` files import with no problems, even my most recent ones which use the newest features (layer groups). They're imported by the standard QtImageReader, so apparently Qt supports the format.

Krita `.kra` files, on the other hand, OpenShot has no idea what to do with. Ditto Krita `.ora` files. Krita OpenEXR (`.exr`) files seemingly import successfully, but the image isn't always correctly rendered.

So, to figure out why there are differences, we'll need a lot more information from you:
1. What version of OpenShot are you running?
1. What versions of GIMP and Krita?
1. What OS is all this taking place on?
1. How did you install OpenShot? (From what source.)
1. When you say "Gimp project files", you're referring to the native GIMP `.xcf` file format? (The one that's saved when you use **File > Save**, as opposed to **File > Export**.)
1. When you say that you _can_ load Krita files into OpenShot, what format are _those_ files saved in? Krita has at least 3 or 4 different file formats that it considers "standard" for different purposes.
1. How are you importing the files into OpenShot? (Drag-and-drop? "Import Files..." toolbar button / menu option?)

My best guess, for the moment, is that you're probably running OpenShot built with an older version of the Qt library, from before they fully completed their support for the XCF format. But that's just a wild guess, at the moment.

**Comment by ferdnyc** [comment]
(BTW, you mentioned PhotoShop: Recent versions of Krita and GIMP both have no problems at all reading/writing `.PSD` files, which OpenShot is also able to import. So, that's another option — you could just save your images as PhotoShop documents, which should support pretty much all of the features of GIMP and Krita's native project files.)

**Comment by CHJ85** [comment]
That is a option. Didn't think about that.
Btw, I'm on version 2.5.1-dev2 from the Focal repo.
Gimp version 2.10.18
Krita version 4.2.9
All from the default Ubuntu 20.04 repo.
All installed through APT.
Sorry, I should have mentioned this.
I'm sure most people use what's in the repo for convenience and stability purposes.

**Comment by ferdnyc** [comment]
@CHJ85 

Hmm. Near as I can tell, focal's official repo [still has the outdated 2.4.3 release](https://packages.ubuntu.com/focal/openshot-qt) that Debian has been packaging for like 2+ years now. It looks like _groovy_ does [finally have 2.5.1!](https://packages.ubuntu.com/groovy/openshot-qt) — and there was much rejoicing. But even that's the 2.5.1 _release_ version, AFAICT. If you're running 2.5.1-dev2, that's probably installed from the [libopenshot daily PPA](https://launchpad.net/~openshot.developers/+archive/ubuntu/libopenshot-daily)?

Regardless, so you're saying the version of OpenShot you have installed _cannot_ import the `.xcf` file inside this zip?:  [test-image.zip](https://github.com/OpenShot/openshot-qt/files/5286811/test-image.zip)

It opens right up with no problems, in my 2.5.1 installed on Fedora 32. Or the code in my development tree.

**Comment by ferdnyc** [comment]
AAAGH! I just realized what's going on here. I'll bet _anything_ that this is Ubuntu/Debian's Qt packaging striking again.

Qt uses image format plugins, to be able to read formats — Fedora installs all of the available plugins automatically when you install the base Qt libraries. But Ubuntu has shown a long history of _not_ doing that. I bet we just have to figure out how you'd install the Qt image format plugin that supports XCF.

**Comment by ferdnyc** [comment]
Perhaps try an `apt install [qt5-image-formats-plugins](https://packages.ubuntu.com/focal/qt5-image-formats-plugins)`, see whether that does anything. If it's not _already_ installed, I bet you'll find it magically repairs OpenShot's ability to import XCF (and many other formats).

**Comment by CHJ85** [comment]
Thank you. But qt5-image-formats-plugins was already installed.
If you can figure out what package it is, it could be a good idea to include it as a dependency in the future.
Also, you're right. I did get that version of openshot from the PPA. Sorry. My mistake.

**Comment by ferdnyc** [comment]
Ah, here we go. `QT_DEBUG_PLUGINS` tells me that XCF is supported by...
```sh
$ QT_DEBUG_PLUGINS=1 PYTHONPATH=.../libopenshot/build/src/bindings/python src/launch.py
# stuff stuff stuff, stuff stuff stuff... 
Found metadata in lib /usr/lib64/qt5/plugins/imageformats/kimg_xcf.so, metadata=
{
    "IID": "org.qt-project.Qt.QImageIOHandlerFactoryInterface",
    "MetaData": {
        "Keys": [
            "xcf"
        ],
        "MimeTypes": [
            "image/x-xcf"
        ]
    },
    "archreq": 0,
    "className": "XCFPlugin",
    "debug": false,
    "version": 331008
}
^C
$ rpm -qf /usr/lib64/qt5/plugins/imageformats/kimg_xcf.so
kf5-kimageformats-5.70.0-1.fc32.x86_64
```
So, whatever package in Ubuntu would correspond to the "KDE Frameworks 5 Tier 1 addon with additional image plugins for QtGui" is the one you'd want.

> If you can figure out what package it is, it could be a good idea to include it as a dependency in the future.

Unfortunately, the PPA configs aren't part of the OpenShot repo, that's sole @jonoomph territory.
