### ISSUE TITLE
cx_Freeze on initial launch with X64 bit Vista

### ISSUE THREAD

**Issue by Peachisme** [OpenShot/openshot-qt#374]
**Hello,** 

I asked a friend if he knew any good video editing programs and he recommended OpenShot. It looks like a fantastic program and I am really wanting to get back into video editing again. Only, one problem. I'm getting Python issues when I go to launch. I've found similar issues here and only one that was on a Vista, which did not seem to get resolved.  I have tried unintalling, deleting all OpenShot files and registry errors, then re-booting and installing the daily file. Still getting the same issue. Any assistance would be greatly appreciated. :)
## cx_Freeze: Python error in main script

Traceback (most recent call last):
  File "C:\msys64\mingw64\lib\python3.5\site-packages\openshot.py", line 18, in swig_import_helper
  File "C:\msys64\mingw64\lib\python3.5\imp.py", line 296, in find_module
ImportError: No module named '_openshot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\msys64\mingw64\lib\python3.5\site-packages\cx_freeze-5.0-py3.5-mingw.egg\cx_Freeze\initscripts\Console.py", line 21, in <module>
  File "openshot_qt/launch.py", line 53, in <module>
  File "C:\Program Files\OpenShot Video Editor\classes\app.py", line 40, in <module>
    from classes import info, settings, project_data, updates, language, ui_util, logger_libopenshot
  File "C:\Program Files\OpenShot Video Editor\classes\logger_libopenshot.py", line 31, in <module>
    import openshot
  File "C:\msys64\mingw64\lib\python3.5\site-packages\openshot.py", line 28, in <module>
  File "C:\msys64\mingw64\lib\python3.5\site-packages\openshot.py", line 20, in swig_import_helper

**Comment by Peachisme** [comment]
Also, my System Information:

OS Name	Microsoft® Windows Vista™ Home Premium
Version	6.0.6002 Service Pack 2 Build 6002
System Type	x64-based PC
Processor  	Intel(R) Core(TM)2 Quad CPU Q6600  @2.40GHz, 2400 Mhz, 4 Core(s)
Installed Physical Memory (RAM)	4.00 GB
Graphics	NVIDIA GeForce GT 630
Adapter RAM	(2,147,483,648) bytes

**Comment by Peachisme** [comment]
Yes, a newer version of windows is probably the best solution. =P I'm really kicking myself for not upgrading to 10 for free. Oh well, I guess I have to work with what I've got for right now. I have used dependency walker to look at the files that you listed, here's what I found:

![ieshims](https://cloud.githubusercontent.com/assets/22806364/19407164/8e963938-924e-11e6-9a64-82f9bfe0d8ce.jpeg)
![gpsvc](https://cloud.githubusercontent.com/assets/22806364/19407166/a30755f0-924e-11e6-8c0c-a6a9727b0ef0.jpeg)

These two .DLL files are unbound. The same two came up when I ran: libopenshot.dll and libopenshot-audio.dll 

This is what happened when I ran openshot.pyd :
![_openshot pyd](https://cloud.githubusercontent.com/assets/22806364/19407198/1b6a81a2-924f-11e6-99ac-b00c78693f43.jpg)

I am thankful for your speedy reply the other night after I initially inquired. If there is anything else that I can do to help you fix the vista issue, please let me know. I may have looked at the dependencies for the wrong file on that last one as I could only find this :
 C:\Program Files\OpenShot Video Editor\lib\python3.5\_openshot.pyd 

I tried finding a "python3.5_openshot.pyd"  file in the lib folder and had no luck, so I assumed that the "_openshot.pyd" file in the "python3.5" folder was the one you requested?

Again, your help is appreciated, I really would like to try Open Shot! :)

**Comment by DylanC** [comment]
@Peachisme - Duplicates have been resolved. Closing this issue too.
