### ISSUE TITLE
Animated Titles aren't working

### ISSUE THREAD

**Issue by captkj** [OpenShot/openshot-qt#3740]
**Describe the bug**
Animated Titles aren't working...I can open the animated titles window, but it stalls when I try to select a title.  

**Steps to reproduce the behavior:**
1. Go to Menu
2. Click on Title
3. Scroll down to Animated Title
4. Animated Title window opens successfully, but stalls when I select a title

**Expected behavior**
Edit and Render an animated title

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Windows-10-10.0.18362
- Processor: Intel64 Family 6 Model 158 Stepping 13, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1600895649-4e98fb72-12ddb3df-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/3d3h1ipiy9gvsq8s0skarv48dc205h6e/openshot-qt.zip) (52 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by rexdk** [comment]
@captkj Do you have Blender installed?

I've logged on this morning to report a bug (2.5.1-dev2 Win10) that if Blender is not installed OpenShot gives no warning and simply turns the cursor to a 'rotating wait' - until OpenShot is restarted. It might appear to be stalled, but as far as I can tell everything still works (except the animated titles that require Blender of course), but the cursor is changed.

If that is your situation it confirms the bug - presumably if Blender is installed it'll work OK.

But OpenShot does need to give a warning, especially as Blender is not commonly installed on Win10 systems.

========
Aha! - just read your logfile:
blender_listview:ERROR Worker exception: No Blender version detected in output

which I assume means you do not have Blender

In which case this needs to be labelled as a bug

Can you do that? I don't think I am able to change the label

**Comment by rexdk** [comment]
I've looked into this a bit more. I think you may have the latest  Blender installed. I have now installed the latest Blender 2.9.1 and I still get the blue wait cursor - and no further.

The manual mentions blender 2.75, so I installed that - now OpenShot gives a message that it needs 2.80 or more.

So I installed 2.80 - and it works - slowly, but it does work

So OpenShot can't cope with the latest Blender. I think you can probably install 2.80 alongside later versions by choosing a diffirent install directory

**Comment by TotallyClueless** [comment]
The Python modules, for example, dissolve.blend that OpenShot calls need rewriting for Blender 2.90. If you try and run them from inside Blender they kick out a load of errors. Sadly, my Python skills aren't up to fixing it so I will have to miss out on animated titles or learn how to use Blender!

**Comment by rexdk** [comment]
@TotallyClueless 
Yep - I saw your note in #3730. You could perhaps try to install Blender 2.80 alongside the later Blender, and put the path to 2.8 in OpenShot.

Whatever, one of thse issues need flagging as a bug, so that the development team pick it up

**Comment by captkj** [comment]
I'm not able to work on it this weekend, but yes...I have the latest Blender.  I saw the same notes on using Blender version 2.80.  I'll give that a try on Monday.  

How do I flag it as a bug?

**Comment by rexdk** [comment]
I don't know how to flag it as a bug I'm afraid! Was hoping you might find something to click as the author. If all else fails I'll start a new issue.

**Comment by captkj** [comment]
In Openshot (on the help menu), I clicked "Report a Bug."  That's how I initially reported the problem.  Hopefully, that's all I needed to do.

**Comment by captkj** [comment]
I uninstalled Blender 2.90.1...then installed Blender 2.80.  When I try to select the animated title I get this warning:

Blender, the free open source 3D content creation suite, is required for this action. (http://www.blender.org)
Please check the preferences in OpenShot and be sure the Blender executable is correct.
This setting should be the path of the 'blender' executable on your computer.
Also, please be sure that it is pointing to Blender version 2.80 or greater.
Blender Path: C:/Program Files/Blender/blender-2.80-windows64/blender.exe
Error Output:
No frame was found in the output from Blender

I've opened Blender 2.80 directly...just to make sure I was opening the application.

**Comment by rexdk** [comment]
Oh dear. I suppose that is the correct path?
C:/Program Files/Blender/blender-2.80-windows64/blender.exe

I installed mine to the default folder - which I _think_ is different.

Other than that I'm afraid I'm out of ideas....

**Comment by TotallyClueless** [comment]
So a week ago I wanted to edit a clip and OpenShot was my first ever attempt at video editing and I had never even heard of Blender. Then I came across the animated titles bug and posted it here as per the instructions from OpenShot website. However after poking around in Blender while waiting for a response and trying to see why the dissolve.blend didn't work I came across the video editor in Blender and there are loads of YouTube tutorials on how to use it and create animated Titles, etc. 

My solution/idea is just use Blender as it is far more capable. My advice to OpenShot is to actually respond to bug reports that you request. Even a simple acknowledgement that there is a problem would have been nice (I really don't believe that I can be one of the first people to come across this). 

On the upside while waiting for a response I've stumbled across Blender, learned how to use the video editor, learned how to make animated titles in it and made my first posts on Github so thanks for that.

**Comment by captkj** [comment]
Thanks for everyone's input...I didn't think of using Blender directly.  I'll give that a try as a temp solution.  I should say, I'm grateful for Openshot as well...it's very easy to use for a novice like me and they continue to improve on the software.  I'm sure their will be a fix down the road.

**Comment by rexdk** [comment]
I've raised a new issue 3744, which actually does have a bug label, so the development guys will see it

**Comment by ferdnyc** [comment]
That should be fixed once my PR #3749 merges — Blender changed the format of their `-v` message _again_ in 2.83, and we were no longer able to detect the version number.

@rexdk 

> I've raised a new issue 3744, which actually does have a bug label, so the development guys will see it

Just FYI, that... doesn't actually make a difference. I mean, it's good to have the bugs labeled as bugs, but they're not particularly more or less likely to get seen based on that label.

Personally, I get email copies of all the issues. And... that's the problem, really. It's hard to keep up with _all_ the issues, and if I did I'd never get around to writing any code. So I respond to what I can, when I can.

**Comment by ferdnyc** [comment]
From the logs @TotallyClueless posted in #3730 (which was, AFAICT, the first report of these issues, beliefs to the contrary notwithstanding), it's possible that my changes so far won't completely fix 2.90 support, as it looks like Blender _may_ have changed some of their internals again. Hard to say; ultimately 2.90 isn't released yet so some brokenness is to be expected. But Exploding Text and Dissolve both worked fine for me using 2.83.5, with those changes.

**Comment by ferdnyc** [comment]
(Ok, so 2.90 _has_ been released. I can't keep up with them! )

It's also possible 2.90 works fine, especially if @TotallyClueless was running with a Blender install that was set to use non-English object names. Previously that would throw off our scripting, but **is** also fixed in my PR, as OpenShot will now tell Blender to ignore user preferences when running the scripts.

**Comment by rexdk** [comment]
I've had the latest Blender release 2.90.1 installed and also had the problem. English version of course.

**Comment by ferdnyc** [comment]
Well, there are potentially at least two different problems.

1. The version detection issue, which any version above 2.83 will have. My PR fixes that, but isn't merged yet.
1. The crash in `dissolve.py` that @TotallyClueless posted over in #3730. That I traced down to a Blender API change since 2.80. I can backport a fix to our current code, though, as the newer code _should_ be compatible with all 2.80+ versions. (We were still using an especially-outdated API that's no longer available in 2.90.)
    This issue should _only_ affect `dissolve.py`, AFAICT, since it's the only script that used that feature. But I'll be adding that fix to #3749 before it's merged, hopefully.

**Comment by ferdnyc** [comment]
The next set of updated Daily Builds (which will be available at https://openshot.org/download/ within minutes, if they aren't already) should _hopefully_ be fully compatible with both Blender 2.83 and Blender 2.90+. Please open a new issue if you experience any problems with the updates.
