### ISSUE TITLE
Extra Space Added To End OF Clip When Slicing

### ISSUE THREAD

**Issue by Raziel0315** [OpenShot/openshot-qt#3747]
Didn't find previous mention of this.

**Describe the bug:**

This might not be considered a bug, but maybe a coding oversight.
As it says in the title, an extra space is added to the end of the clip when it is sliced.
Normally, this wouldn't be a problem, unless there is already a clip butted right up against the clip you are slicing.
To go back and move every single clip you've already been through to take up this extra space is beyond tedious.
To make matters worse, simply butting the newly cut clip up against the next one, (to fix the extra space), makes an unintended overlap, and makes the image/sound appear to lag for a split second.
The only way to fix this is to zoom in to the track maximum and move the intended tracks a mere fraction to get it perfect.
Now, multiply that by 10 minutes of previous cuts in the tracks: a true nightmare.

**Steps to reproduce the behavior:**

See above: easily duplicated.
I have been dealing with it for months.  It still persists in the daily builds.

**Expected behavior:**

No extra space added to end of clip; no overlapping of clips when pushed together.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

Daily Build Sept 27, 2020
Windows 10

**Comment by rexdk** [comment]
I'm pretty sure this is known about and is a consequence of adjusting framerates, or something similar. I think I've discussed it with ferdnyc, and there's little that can be done - it's inherent - correct this and something else goes wrong I think. Can't quite remember the details, and I can't find where it was discussed  - sorry, inadequate search skills

**Comment by rexdk** [comment]
aha - found it at last - see #3656
My conversation was at the bottom of 3585

**Comment by Raziel0315** [comment]
The added space wasn't always there.  Neither was the overlap.  They used to line up perfectly
