### ISSUE TITLE
Openshot 2.1.0: Original files disappear after a crash related to drag'n'drop

### ISSUE THREAD

**Issue by matthiasch** [OpenShot/openshot-qt#375]
Original files disappear after a crash related to drag'n'drop (when I drag files from the file system). 
That is pretty severe, just lost a recorded clip.

Openshot 2.1.0; Ubuntu 14.04 (installed from PPA)

**Comment by JtLively** [comment]
I'd suggest you set auto-save for OpenShot.

How often does this happen? What type of file? I can't reproduce the issue.

**Comment by jreynojustin** [comment]
OpenShot is now in Version 2.2 if you are still noticing issues in the latest version please re-open this issue letting us know.
