### ISSUE TITLE
Need ability to bulk-copy and apply Properties to incoming clips/photos/etc

### ISSUE THREAD

**Issue by shawntown** [OpenShot/openshot-qt#3752]
I have these little card images I need to pull in to overlay on my video clips pretty frequently. I see where you can set a default photo length (I set mine to 3 seconds), but what about other properties? Every single time I pull in a card image, I have to go to Fade>Entire Clip>Fade In & Out Fast, then go Animation>Zoom>Beginning of Clip>Zoom 100% to 75%, etc, etc...you get the point. Super tedious. I do this literally hundreds of times per day, and it accounts for probably 50% of all my time working in OpenShot.

If there were only a section in Preferences, just below “default photo length” perhaps, to create Saved Preset Properties for imported photos/clips/ even audio tracks perhaps, it would save a TON of time for those of us who have long, detailed projects that require a lot of editing. Thanks!!

**Comment by ferdnyc** [comment]
@shawntown If you want to set the _same_ properties on every image, you can already Copy keyframes from one clip to another, which sounds like it should do what you want?

Once you've set up one image the way you need, you can select it, open the clip's menu, and choose **Copy > Keyframes > All**. Then, go to another clip and **Paste** to duplicate that same configuration there. Does that help at all?
