### ISSUE TITLE
Animated Titles not working in latest Daily Build

### ISSUE THREAD

**Issue by USATechDude** [OpenShot/openshot-qt#3759]
Operating System:  macOS Catalina 10.15.7
OpenShot Version:  OpenShot-v2.5.1-dev2-1602472203-414a2cda-12ddb3df-x86_64.dmg
System Specifications:  MacBook Pro 16 (2019) / Intel i9-9880H @ 2.4 GHz / 16GB / 512GB / Radeon Pro 5500M 8GB

When creating a new animated title in OpenShot 2.5.1-dev2 (October 11, 2020) using Blender 2.90.1, I selected the Neon Curves title then set the options.  I set the File Name, then the Title, which includes two text lines, and set the rest of the options.  When I refresh the preview window, it shows the title with one text line with a \n character between the two lines that I created (see image).  I was expecting to see two text lines in the preview window for the title that I selected.  When I rendered the title, the result was a single text line with a \n between the two texts that I created.  I uninstalled Blender 2.90.1, installed Blender 2.80, then created a new project and a new animated title but had the same issue.  

I then tried this on my Windows 10 (2004 10.0.19041.508) and Linux (Ubuntu 20.04 LTS) systems, which have OpenShot 2.5.1-dev2 (October 11, 2020), but had the same result.  I launched my Linux (Ubuntu 20.04 LTS) VM and my Windows 10 (2004 10.0.19041.508) VM, which have OpenShot 2.5.1 and Blender 2.80, and recreated the title with two lines of text without the \n character.

<img width="912" alt="Screen Shot 2020-10-13 at 4 04 57 PM" src="https://user-images.githubusercontent.com/65924242/95920603-50087b80-0d75-11eb-9e64-ee9364b75376.png">

**Comment by ferdnyc** [comment]
Oh! Seems we're not protecting multi-line strings properly in the generated script. Thanks for the detailed report, should hopefully be an easy fix.

**Comment by ferdnyc** [comment]
It _was_ easy to fix, but I took the opportunity to beef up the entire way we pass parameters to the script, so that hopefully there won't be any more issues like this cropping up in the future.

**Comment by ferdnyc** [comment]
Whenever a set of Daily Builds pops out with PR #3761 incorporated (which may take half an hour or more to settle out, as I just merged a bunch of PRs in quick succession), this should be fixed for all animated title templates.

**Comment by USATechDude** [comment]
Thanks, @ferdnyc 
This works like a charm on my MacBook Pro.

However, when I tried the same title on my Windows 10 system with the latest Daily Build, the preview screen shows the OpenShot logo instead of my title, even after pressing Refresh.
![Screenshot01](https://user-images.githubusercontent.com/65924242/96035857-3de81500-0e29-11eb-89ef-8d33c5cc8fb3.png)

When I click the Render button, OpenShot passes the information to Blender and Blender generates and renders all 250 PNG images.  When the rendering is finished I receive an error message stating: Title%04d.png is not a valid video, audio, or image file.
![Screenshot02](https://user-images.githubusercontent.com/65924242/96036035-80115680-0e29-11eb-86cc-53c39a2924e1.png)

**Comment by ferdnyc** [comment]
@USATechDude Yup, turns out the Windows paths weren't being properly embedded in the script. Should be fixed by #3763, which I'll merge as soon as Travis is done with it.

Thanks again for the detailed testing. **#TIL** that my Windows laptop is too old and pathetic to run current versions of Blender (sigh), and I don't have access to a Mac _at all_, so all I can really determine for this stuff is "Hey, works on Linux" which isn't exactly end-to-end testing.

**Comment by ferdnyc** [comment]
These Daily Builds have the updated code:
* https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.5.1-dev2-1602755821-414a2cda-12ddb3df-x86_64.dmg
* https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.5.1-dev2-1602755448-414a2cda-12ddb3df-x86_64.exe
* https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.5.1-dev2-1602755446-414a2cda-12ddb3df-x86.exe
* https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.5.1-dev2-1602755345-414a2cda-12ddb3df-x86_64.AppImage
