### ISSUE TITLE
Title animated. After rendering it crashes and does't save

### ISSUE THREAD

**Issue by mario25rossi** [OpenShot/openshot-qt#3762]
**Describe the bug:**

**Steps to reproduce the behavior:**

**Expected behavior:**

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.
Log files can be found in your HOME/.openshot_qt/ folder. Please compress or zip
the log files (as they can become quite large).

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please
attach a small snippet of the exception here, but please keep it as small as
possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them here, dragging-and-dropping into this form, or clicking below and loading
images saved to your computer. All images are public, so please don't post screenshots
containing personal information.

**Comment by ferdnyc** [comment]
This should be fixed in these builds:
* https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.5.1-dev2-1602755821-414a2cda-12ddb3df-x86_64.dmg
* https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.5.1-dev2-1602755448-414a2cda-12ddb3df-x86_64.exe
* https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.5.1-dev2-1602755446-414a2cda-12ddb3df-x86.exe
* https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.5.1-dev2-1602755345-414a2cda-12ddb3df-x86_64.AppImage

**Comment by mario25rossi** [comment]
uninstalled and installed again: it didn't work. Render ok but crashes
before saving. All my job wasted! Please help me. Thank you

Il giorno gio 15 ott 2020 alle ore 13:09 Frank Dana <
notifications@github.com> ha scritto:

**Comment by ferdnyc** [comment]
@mario25rossi 

It would be helpful if you could post your log, as it may hold some information on the nature of the crash. You didn't say what OS you're running, but the logs are generally found at:

* Windows: <code>C:\Users\\<var>username</var>\\.openshot_qt\openshot-qt.log</code>
* Mac/Linux: <code>$HOME/.openshot_qt/openshot-qt.log</code>

You can either place the log inside a ZIP file, or change the filename to `openshot-qt.log.txt`, and then attach it to a comment.

**Comment by mario25rossi** [comment]
thank you

Il giorno ven 16 ott 2020 alle ore 07:49 Frank Dana <
notifications@github.com> ha scritto:

**Comment by ferdnyc** [comment]
@mario25rossi 

Sorry, I just realized you've been replying by email. If you tried to include logs as an email attachment, we didn't get them. Github removes all attachments from email comments.

You can post logs using the web interface, by dragging the file into a new comment here:

[`https://github.com/OpenShot/openshot-qt/issues/3762`](https://github.com/OpenShot/openshot-qt/issues/3762)

**Comment by mario25rossi** [comment]
Solved. Thank you
Uninstalled and installed openshot 2.5.1dev2 and blender 2.81, Finally works

**Comment by ferdnyc** [comment]
Great to hear, thanks! Re-closing as fixed.
