### ISSUE TITLE
Nothing showing on the screen

### ISSUE THREAD

**Issue by Kyrocryptix** [OpenShot/openshot-qt#3765]
**
![ Untitled Project  HD 720p 30 fps  - OpenShot Video Editor 10_16_2020 2_32_47 PM](https://user-images.githubusercontent.com/72963749/96221098-8257ea00-0fbc-11eb-8d71-46300e43a6ed.png)
**
I need help what to do? no I dont need to load, I pressed X on the top right of the screen in the app now nothing shows I tried deleting and downloading still nothing

**Comment by USATechDude** [comment]
@Kyrocryptix To reset your View so that you can see those windows again, click on the View pull-down menu, point to Views, then click Simple View. If you wish to see more windows, click the Advanced View option.
