### ISSUE TITLE
Bars Effect: impossible to delete Bar Colour keyframe

### ISSUE THREAD

**Issue by rexdk** [OpenShot/openshot-qt#3768]
Setting a bar colour property inserts a keyframe as you might expect.

The only way I know of to remove a keyframe is to jump to it, and right click on the property settings box, selecting Remove Keyframe.

However, right clicking on the Bar Colour property simply brings up the colour selector.
Result: the keyframe little green tick remains, and the property is still set at that time point.

This may well happen with other effect colour select properties too - I've not checked.

**Comment by rexdk** [comment]
>This may well happen with other effect colour select properties too - I've not checked.

I can't find any other effect which uses the colour selector, except chroma - which does not create a keyframe (no animation). So it just applies to Bars.

The apparent result of Bar Colour keyframes is that the RGB components individually change smoothly betwen the old and new colours, as far as I can see.

**Comment by ferdnyc** [comment]
Reopening as I just saw this, and have a fix in the works.
