### ISSUE TITLE
Crash when dragging clip from desktop

### ISSUE THREAD

**Issue by runintothenight** [OpenShot/openshot-qt#377]
Hello,

I have Windows 8.1.  Whenever I attempt to drag a video file from the desktop, OpenShot 2.1 crashes with the following dialog:
![openshotcrash](https://cloud.githubusercontent.com/assets/22861641/19413825/dfa84fb4-9307-11e6-9913-57c0a1eb8ef9.PNG)

**Comment by JtLively** [comment]
Try again or simply use **Import** with the newest version.
Check out #openshot IRC and/or open a new issue if the issue persists.
