### ISSUE TITLE
Time Glitches

### ISSUE THREAD

**Issue by zanheart** [OpenShot/openshot-qt#3771]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**
1. add a clip and chop a piece of it
2. speed it up or slow it down
3. export it
4. See error'

What is happening:
https://www.youtube.com/watch?v=oL2mckRVgFE&list=UU1ExryyoSCXLvEcxOc3S29A&index=1

**Expected behavior**

**System Details**
- OpenShot Version: 2.5.1
- libopenshot Version:  0.2.5
- Platform: Windows-10-10.0.18362
- Processor: Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1602903754-49b7e623-e663d7b7-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/i7fwhzzzyly1fgjni0j0qvltj5vchyur/openshot-qt.zip) (48 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/i7fwhzzzyly1fgjni0j0qvltj5vchyur/libopenshot.zip) (0 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by USATechDude** [comment]
The Time function in OpenShot takes into account the entire clip that is being edited, not just the portion that you want to use.  To work around this issue, you can export the part of the clip that you want the speed adjusted to a separate video file.  Create a new project and import only the clip to be adjusted.  Change the speed of that clip then export it as another video file.  Import the recently adjusted clip to your original project and add it to the timeline.

**Comment by zanheart** [comment]
I have tried that and it still doesn't work
