### ISSUE TITLE
openshot.org website has too many download buttons

### ISSUE THREAD

**Issue by hackerb9** [OpenShot/openshot-qt#3779]
Hi! I was helping a friend find a good video editor and suggested he try openshot.org. Unfortunately, there are a bunch of buttons there that say **DOWNLOAD**, **OPEN**, **START**, and the largest, most prominent ones aren't for OpenShot. They are advertisements. 

Could you please disallow advertisements that make fake user interface objects? It makes OpenShot look bad to have all these low quality ads that have to trick people into clicking on them.

Thank you.

**Comment by ferdnyc** [comment]
The website isn't under the control of the project, so there's nothing that can be done about this here. The issue has been brought up in the past, but ultimately it's up to @jonoomph . Tagging so maybe he'll see this.

**Comment by hackerb9** [comment]
Thank you. If it is not run by the project, why does the website say, "We rely on advertising to help fund OpenShot"?
