### ISSUE TITLE
Import .srt files to support subtitles

### ISSUE THREAD

**Issue by kholyphoenix1** [OpenShot/openshot-qt#378]
Hello, 

It would be possible to add subtitle?
If yes, what are the supported formats?

Thanks!

**Comment by DylanC** [comment]
@kholyphoenix1 - I will check this out and get back to you.

**Comment by kholyphoenix1** [comment]
Thanks!

**Comment by DylanC** [comment]
@kholyphoenix1 - It is not currently possible at the moment with subtitle formats unless you just want to use .svg files with text for now. However, I have confirmed that the subtitle formats may become available to use in a future version.

**Comment by dcabrejas** [comment]
@DylanC Thanks for the software, I am looking to add subtitles as well, is this possible already or not yet ?

**Comment by DylanC** [comment]
@dcabrejas - Not yet unfortunately. Unless you want to do it with SVG files (with text at the bottom of each one). I presume you want something a little better. :)

**Comment by poikilos** [comment]
Importing srt files, preferably as a single clip such as an effect, would really speed things up--that way if a subtitle editor affects the file later, the media would reload automatically and they can stay in sync.

**Comment by LinuxSuRen** [comment]
I also hope that openshot could imports srt files. In my [community](https://github.com/jenkins-zh/jenkins-open-tutorial), we start to record a lot of tutorial for [Jenkins](https://github.com/jenkinsci/jenkins).

If there's anything I can help with this feature, please let me know.

**Comment by poikilos** [comment]
> @kholyphoenix1 - It is not currently possible at the moment with subtitle formats unless you just want to use .svg files with text for now. However, I have confirmed that the subtitle formats may become available to use in a future version.

@DylanC  If so, I suggest re-labeling this as a feature request instead of closing the question, since there is still activity here.

**Comment by DylanC** [comment]
@poikilos - Not as involved with this project any more but sure. Makes sense!
