### ISSUE TITLE
OpenShot

### ISSUE THREAD

**Issue by elazizy** [OpenShot/openshot-qt#3797]
The program was not installed in any way. Correct, there is something wrong
![aed](https://user-images.githubusercontent.com/73445140/97373097-cf419780-18bd-11eb-8891-16e4560b7acc.jpg)

**صِف المشكلة**
A clear and concise description of the issue

**خطوات إعادة إحداث المشكلة:**
1. اذهب إلى '...'
2. انقر على '....'
3. مرّر لأسفل إلى '....'
4. انظر الخطأ

**السلوك المتوقع**
وصف واضح وموجز عن ما تتوقع حدوثه.

**تفاصيل النظام**
- OpenShot Version: 
- libopenshot Version:  
- Platform: 
- Processor: 
- Machine: 
- Python version: 
- Qt5 version: 
- PyQt5 version: 
- Qt Detected Languages: 
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Skipped this step

**ملفات السجل**
N/A

**Exception / Stacktrace**
```No stacktrace found in log files```

**لقطات الشاشة** (اختياري)
إذا كان ممكنا ، أضِف لقطات شاشة للمساعدة في توضيح المشكلة. يمكنك تضيمن لقطات الشاشة
عن طريق نسخها ولصقها في GitHub أو عن طريق السحب والإفلات في صفحة GitHub.
جميع الصور عامة، لذلك برجاء عدم نشر أي لقطات شاشة تحتوي على معلومات شخصية.

**Comment by elazizy** [comment]
![aa](https://user-images.githubusercontent.com/73445140/97377027-a9b98b80-18c7-11eb-9f78-962c7e5a5e47.jpg)
Another download did not install with the arrival of the message shake, and I did not know where it was wrong

**Comment by RiedleroD** [comment]
I can't read any of what you wrote because you used weird symbols my system font can't display. I can tell you that a .crdownload file is a temporary file that chrome creates when downloading a file. Please make sure you completely download [the official executable](https://www.openshot.org/download/).
