### ISSUE TITLE
Color picker picks the wrong value if dialog has dark background

### ISSUE THREAD

**Issue by strattonbrazil** [OpenShot/openshot-qt#3798]
**Describe the bug:**
When using the chroma tool I noticed it was working very poorly. After playing with the colors I noticed the ones grabbed by the picker were much darker, which was the problem. I realized the color picker is actually pulling values off the screen--not the render view--so the dark overlay the dialog puts over the window (at least on my dialog rendering implementation) will alter the picked color. See screenshot below. 

**Steps to reproduce the behavior:**
1. Loading OpenShot
2. Load color picker from effect property (ex. Chrome Key color)
3. Select color from render view
4. If dialog has darked the 

**Expected behavior:**

**System Details:**
- OpenShot Version: 2.5.1
- Operating System / Distro: Ubuntu 18.04

**Screenshots:**
![color_picker_background](https://user-images.githubusercontent.com/786471/97398087-d067ca00-18a7-11eb-8157-40fc6da45e77.png)

**Comment by ferdnyc** [comment]
I don't know how I didn't see this one along with #3799, but PR #3815 will fix this as well.
