### ISSUE TITLE
The chrome key does not work.

### ISSUE THREAD

**Issue by ANAELIAZOR** [OpenShot/openshot-qt#3800]
I made sure the problem was not reported!

**I select a color to delete but the color is not deleted from the video.**

**Steps to reproduce the behavior:**
1. I drag a video to the timeline. [Strip number 5]
2. Adds an image to the timeline [track number 4]
3. Moves to the tab: "Effects"
4. Drag the chrome key effect to the video.
5. I added an icon of the letter C on the part of the video in the timeline, I right-click on the icon and select: "Properties".
6. I get parameters to choose from, I click on the key color twice and a color selection window opens.
7. I click on the "Choose color from screen" button.
8. I make sure the screen is at maximum brightness, because if not then it chooses a color that is too dark, and then I click on the color to delete that appears in the video.
9. Click OK, and then the key color changes to the color I selected.
10. I click on the number and drag to the top [maximum is 25] and still the color is not deleted from the video.
I insert a larger value [100] by the keyboard, and then colors that are too far from the original color are deleted but the original color is not deleted.

**Expected behavior:**
I expected the solid color of the background to erase and be replaced by a black background or the image I placed below the video in the timeline.

**System Details:**
- OpenShot Version [dev2-2.5.1]
-libopenshot:0.2.5-dev2
- Operating System / Distro: [Linux Ubuntu 18.04.4 LTS ]

**Log Files:**
I DONT GET A crash.

**Screenshots:** (Optional)
![2020-10-28 21-08-42](https://user-images.githubusercontent.com/73610497/97484830-f356b480-1961-11eb-878a-6668610af5b5.png)

**Comment by ferdnyc** [comment]
This should be fixed as of OpenShot/libopenshot#643 (merged 2021-03-12), which corrected the ChromaKey effect to account for premultiplied color values.
