### ISSUE TITLE
No audio during editing (preview) on Dell G7

### ISSUE THREAD

**Issue by lcbudnick** [OpenShot/openshot-qt#3810]
**Describe the bug**
Om a Dell G7 laptop, the only audio device that works is the HDMI monitor. Selecting Default, there is no audio, selecting a specific device (from the preferences->preview tab) says "No such device: Primary Sound Driver"

**Steps to reproduce the behavior:**
1. Set the audio preview device to various options
2. Restart OpenSHot
3. If default device selected, there is no sound. Selecting a specific device other than HDMI results in error message

**Expected behavior**
Sound should work.

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Windows-10-10.0.18362
- Processor: Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1604080375-896b3073-2cb4eeff-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/c0onbbomrp8rcaqn23mxyvk9fxuzkwk6/openshot-qt.zip) (192 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/c0onbbomrp8rcaqn23mxyvk9fxuzkwk6/libopenshot.zip) (142 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by lcbudnick** [comment]
Should add that running under a Hyper-V VM (same version of Windows) on the same device, all sound options work fine.

**Comment by MBB232** [comment]
You've tried this? 
https://github.com/OpenShot/openshot-qt/wiki/FAQ#Audio_issues
Interesting about the Hyper-V working. Is it using different audio drivers?
