### ISSUE TITLE
Could not create hwdevice

### ISSUE THREAD

**Issue by doppel-T** [OpenShot/openshot-qt#3812]
**Beschreiben Sie den Fehler**
ich kann nicht mit der Grafikarte rendern

**Schritte zum Reproduzieren des Verhaltens**
ich möchte ein Video exportieren über VA-API MP4(h.264va)

**Erwartetes Verhalten**
das Video wird gerendert so wie wenn ich die CPU nutze

**Systemdetails**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Linux-5.4.0-52-generic-x86_64-with-glibc2.29
- Processor: x86_64
- Machine: x86_64
- Python version: 3.8.5
- Qt5 version: 5.12.8
- PyQt5 version: 5.14.1
- Qt Detected Languages: ['de-DE']
- LANG Environment Variable: de_DE.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Verifiziertes Problem exsitiert immer noch im Daily Build:  http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1604080262-896b3073-2cb4eeff-x86_64.AppImage

**Logdateien**
- [openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/5470552/openshot-qt.log)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/15tqgyteec6coa8p0an3qzz7yhs3hgqw/libopenshot.zip) (19 KB)

**Ausnahme / Stapelverfolgung**
```No stacktrace found in log files```

**Bildschirmfotos** (Optional)

![Bildschirmfoto vom 2020-11-01 11-16-49](https://user-images.githubusercontent.com/73776294/97800238-fa1c4a80-1c33-11eb-9bfd-05389f06ffec.png)

**Comment by JochenMehlich** [comment]
Bei mir tritt das Problem leider auch auf: Grafikkarte: AMD Radeon 5700xt

**Comment by JochenMehlich** [comment]
> **Beschreiben Sie den Fehler**
> ich kann nicht mit der Grafikarte rendern
Welche Grafikkarte verwendest du denn, denn bei mir steht im Log

`Encodiing Device Nr: 1
Cannot load libcuda.so.1
[AVHWDeviceContext @ 0x2e27900] Could not dynamically load CUDA
      export:INFO Error type string: Could not create hwdevice
 main_window:INFO Export Video add cancelled
     ui_util:INFO Initializing UI for dlgPreferences
Hardware decoding device number: 0
[AVHWDeviceContext @ 0x3322c00] Cannot open the X11 display /dev/dri/renderD128.
Hardware decoding device number: 0
[AVHWDeviceContext @ 0x2e9a980] Cannot open the X11 display /dev/dri/renderD128.
 preferences:WARNING Exception trying to test hardware decoding in preferences (this is expected): 6-0
Hardware decoding device number: 1
Hardware decoding device number: 1
 preferences:INFO 1
 preferences:INFO 1
 main_window:INFO Preferences add cancelled
preview_thread:INFO onModeChanged
Hardware decoding device number:`

**Comment by Volodya** [comment]
The same issue with today's daily build.
