### ISSUE TITLE
Constant freeze/break when previewing

### ISSUE THREAD

**Issue by matschi-klickme** [OpenShot/openshot-qt#383]
When I try to preview video or audio, the preview tends to freeze after ~ 1 Min of play. 
I end up with full Cpu usage, frozen preview and an unresponsive Interface with the logs filling up. 

Reproduction: 
Every time, approximately after similar playtimes. No matter whether a single or multiple elements are in the tracklist.  

Video Codecs:
Codec: H264 - MPEG-4 AVC (part 10) (avc1)
Resolution: 1280x720, Frame rate: 25
Codec: MPEG AAC Audio (mp4a)
Channels: Stereo
Sample rate: 48000 Hz

Plays fine with vlc. 

My Systems: 
Latest ARCH #1  x86_64 GNU/Linux

Openshot-Version: 
2.1.0-3 Arch,

Ffmpeg-version:
1:3.1.4-2 Arch,

Logs:

[openshot_logs.zip](https://github.com/OpenShot/openshot-qt/files/542308/openshot_logs.zip)

Thanks for your time and effort.

**Comment by firestar115** [comment]
I have this problem too.

Ubuntu 16.04

**Comment by sdfgeoff** [comment]
Same here. Seems to be a threading issue. Screenshot of top:
![Too many threads](https://s16.postimg.org/q3fx88jad/openshot.png)

The same thing happens with exporting - except that it also tries to consume copious amounts of ram:
![Too much ram](https://s22.postimg.org/shwuuoxm9/openshot2.png)

Looks like I'll be finding another video editor until this is resolved.

**Comment by mjeffe** [comment]
I have the same problem (also on Ubuntu 16.04). Playback with only a single track begins freezing after about 15 seconds, the CPU usage spikes for about a minute, then playback will proceed for 10 or 15 seconds, freeze again and the sequence repeats. Plays fine in VLC and Totem.

Video (according to VLC):
Codec: H264 - MPEG-4 AVC (part 10) (avc1)
Resolution: 720x482
Frame rate: 29.937430
Decoded format: Planar 4:2:0 YUV

Audio (according to VLC):
Codec: MPEG Audio layer 1/2 (mp4a)
Sample rate: 44100 Hz
Bitrate: 128 kb/s

My system:
Dell Latitude E5550 with 16GB RAM
Ubunut 16.04.1

Output from `openshot-qt --version`:
```
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
      logger:INFO OpenShot version 2.1.0
```
I installed Openshot using:
```
sudo add-apt-repository ppa:openshot.developers/ppa
sudo apt-get update
sudo apt-get install openshot-qt
```
Relevant info from `uname -a` output:
```
Linux ****** 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
Relevant info from `lshw` output:
```
    description: Laptop
    product: Latitude E5550 (Latitude E5550)
    vendor: Dell Inc.
    width: 64 bits
...
  *-core
       description: Motherboard
       product: 0TR3VC
       vendor: Dell Inc.
...
     *-cpu
          description: CPU
          product: Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
          vendor: Intel Corp.
          ...
          size: 1676MHz
          capacity: 3200MHz
          width: 64 bits
          clock: 100MHz
...
  *-display               
       description: VGA compatible controller
       product: Broadwell-U Integrated Graphics
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 09
       width: 64 bits
       clock: 33MHz
       capabilities: msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:48 memory:f6000000-f6ffffff memory:e0000000-efffffff ioport:f000(size=64)
```

I tried to keep logs small by: starting openshot, opening my project, clicking playback then running `killall openshot-qt` after a few seconds of the freeze/CPU spike.

Let me know if any additional information or tests would be helpful.

[openshot-qt_logs.zip](https://github.com/OpenShot/openshot-qt/files/559981/openshot-qt_logs.zip)

**Comment by oyvindstegard** [comment]
Same here.. OpenShot 2.1.0 (build from PPA) on Ubuntu 16.04 [Core i5 CPU@3.5GHz, Nvidia GTX 960 with 367-blob-driver, 16GB RAM]: preview stops after a few seconds, even when pre-converting 1080p raw input material to basic huffyuv codec in AVI container. It can be started again by moving timeline+stop/start, but always stops after a few seconds of playback (with openshot-qt using huge amounts of CPU). Also, dragging the timeline marker is very laggy, and often it fails to follow the mouse pointer all the way while holding the button. Maybe there are some graphics interaction problems with the preview video output.

**Comment by DylanC** [comment]
@matschi-klickme - Can you verify this issue exists in a newer version of OpenShot?

**Comment by sdfgeoff** [comment]
2.3.4 no longer has this issue on my PC.

**Comment by DylanC** [comment]
@sdfgeoff - Thanks. Closing for now.

**Comment by mjeffe** [comment]
It appears to be working for me as well on version 2.3.4

**Comment by DylanC** [comment]
@mjeffe - Thanks for the feedback.
