### ISSUE TITLE
Display total duration time of a project (i.e. all tracks) in seconds/minutes and frames on request

### ISSUE THREAD

**Issue by jnsantos** [OpenShot/openshot-qt#3835]
**Describe the new feature:**

New feature: Project info - information regarding total duration time of a project (i.e. all tracks) displayed in seconds/minutes and frames.

**Describe the solution you'd like:**

Ideally, I would be able to press a button (a question mark?) near the timeline tools (add track; magnet; scissor...) and get detailed info regarding the project - as stated above project duration. Of course, extra info can be displayed like the default project settings, estimated render time and so on.

**Describe alternatives you have considered:**

Maybe a pop-up when you select all clips in the tracks that shows this information.

PS - Thank you for this software and all your hardwork!
Cheers!

**Comment by ferdnyc** [comment]
Thanks @jnsantos 

The request is certainly not out of the question, in fact I agree a project summary display would be a nice feature.

But I did just want to point out that you _can_ find the length of your project today by simply seeking the playhead to the end of the last clip on the timeline. (Most easily, by clicking "Jump to End", the right-most button in the cluster of transport controls directly beneath the video preview.)

Whatever the time signature is at the end of the last clip, that's your project length.

Nevertheless, a view of that information — and perhaps other stats as well — would be quite handy.

**Comment by jnsantos** [comment]
Hi Frank,

Thank you for taking the time to answer.

I ended up finding the length by doing just that - playhead to the end and there's my time!

But a summary - and as you say of that info as well as other stats, in an unobtrusive way - would be a plus to the project.

Best regards,
Joaquim
________________________________
De: Frank Dana <notifications@github.com>
Enviado: 25 de novembro de 2020 16:34
Para: OpenShot/openshot-qt <openshot-qt@noreply.github.com>
Cc: Joaquim Santos <jnsantos@ua.pt>; Mention <mention@noreply.github.com>
Assunto: Re: [OpenShot/openshot-qt] Display total duration time of a project (i.e. all tracks) in seconds/minutes and frames on request (#3835)


Thanks @jnsantos<https://github.com/jnsantos>

The request is certainly not out of the question, in fact I agree a project summary display would be a nice feature.

But I did just want to point out that you can find the length of your project today by simply seeking the playhead to the end of the last clip on the timeline. (Most easily, by clicking "Jump to End", the right-most button in the cluster of transport controls directly beneath the video preview.)

Whatever the time signature is at the end of the last clip, that's your project length.

Nevertheless, a view of that information — and perhaps other stats as well — would be quite handy.

**Comment by sanchayanghosh** [comment]
I would like to take a shot at implementing this feature. I will shortly submit a plan and a patch, that hopefully opens a dialog box showing the same.
