### ISSUE TITLE
Cant open Preferences in OpenShot 2.2.0

### ISSUE THREAD

**Issue by xintrea** [OpenShot/openshot-qt#384]
Cant open Preferences in OpenShot 2.1.0

Error in console:

```
     ui_util:INFO Initializing UI for dlgPreferences
      logger:ERROR Traceback (most recent call last):
      logger:ERROR   File "/media/wd_640_part_2/home/xi/work/compilpro/compilpro_debian_5_0_4/OpenShot_2_1_0/src/windows/main_window.py", line 508, in actionPreferences_trigger
      logger:ERROR win = Preferences()
      logger:ERROR   File "/media/wd_640_part_2/home/xi/work/compilpro/compilpro_debian_5_0_4/OpenShot_2_1_0/src/windows/preferences.py", line 203, in __init__
      logger:ERROR for locale, language, country in get_all_languages():
      logger:ERROR   File "/media/wd_640_part_2/home/xi/work/compilpro/compilpro_debian_5_0_4/OpenShot_2_1_0/src/classes/language.py", line 179, in get_all_languages
      logger:ERROR native_lang_name = QLocale(locale_name).nativeLanguageName().title()
      logger:ERROR SystemError
      logger:ERROR :
      logger:ERROR Negative size passed to PyUnicode_New
     metrics:INFO Track metric: {'content-location': 'http://www.google-analytics.com/collect?aid=org.openshot.openshot-qt&cd1=0.1.2&cd=preferences-screen&cid=a5330714-7687-447d-be4c-e87a38b203f0&cd3=5.3.2&ua=Mozilla%2F5.0+%28X11%3B+Linux+i686%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&an=OpenShot+Video+Editor&cd4=5.3.2&aip=1&ul=ru-ru&cd2=3.4.2&t=screenview&tid=UA-4381101-5&v=1&cd5=debian-8.6-&av=2.1.0', 'content-length': '35', 'content-type': 'image/gif', 'x-content-type-options': 'nosniff', 'server': 'Golfe2', 'expires': 'Mon, 01 Jan 1990 00:00:00 GMT', 'cache-control': 'no-cache, no-store, must-revalidate', 'age': '691622', 'status': '200', 'access-control-allow-origin': '*', 'last-modified': 'Sun, 17 May 1998 03:00:00 GMT', 'pragma': 'no-cache', 'date': 'Wed, 12 Oct 2016 18:58:27 GMT'} (b'GIF89a\x01\x00\x01\x00\x80\xff\x00\xff\xff\xff\x00\x00\x00,\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x02D\x01\x00;')
```

System locale: LANG=ru_RU.UTF-8

UPD:
In english locale already cant open Preferences:

```
export LANG="en_US.UTF-8"
export LC_ALL=""
cd ./src
python3 launch.py
```

**Comment by leventelist** [comment]
I have similar issue with 2.2.0:

ui_util:WARNING Icon theme media-playback-start not found. Will use backup icon.
     ui_util:INFO Initializing UI for dlgPreferences
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/openshot_qt-2.2.0-py3.4.egg/openshot_qt/windows/main_window.py", line 552, in actionPreferences_trigger
    win = Preferences()
  File "/usr/local/lib/python3.4/dist-packages/openshot_qt-2.2.0-py3.4.egg/openshot_qt/windows/preferences.py", line 203, in __init__
    for locale, language, country in get_all_languages():
  File "/usr/local/lib/python3.4/dist-packages/openshot_qt-2.2.0-py3.4.egg/openshot_qt/classes/language.py", line 179, in get_all_languages
    native_lang_name = QLocale(locale_name).nativeLanguageName().title()
SystemError: Negative size passed to PyUnicode_New

**Comment by JtLively** [comment]
Where did you download Openshot and on what OS/distro ?

**Comment by leventelist** [comment]
On Sat, 25 Feb 2017 12:21:48 -0800
Jt <notifications@github.com> wrote:

> Where did you download Openshot and on what OS/distro ?

https://launchpad.net/openshot/+download

Gnu Linux Debian/Stable

Compiled from source.

I have this on stdout:

ui_util:WARNING Icon theme media-playback-start not found. Will use backup icon.
     ui_util:INFO Initializing UI for dlgPreferences
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/openshot_qt-2.2.0-py3.4.egg/openshot_qt/windows/main_window.py", line 552, in actionPreferences_trigger
    win = Preferences()
  File "/usr/local/lib/python3.4/dist-packages/openshot_qt-2.2.0-py3.4.egg/openshot_qt/windows/preferences.py", line 203, in __init__
    for locale, language, country in get_all_languages():
  File "/usr/local/lib/python3.4/dist-packages/openshot_qt-2.2.0-py3.4.egg/openshot_qt/classes/language.py", line 179, in get_all_languages
    native_lang_name = QLocale(locale_name).nativeLanguageName().title()
SystemError: Negative size passed to PyUnicode_New
     metrics:INFO Track metric: {'content-location': 'http://www.google-analytics.com/collect?v=1&cd5=debian-8.7-&tid=UA-4381101-5&aip=1&cd2=3.4.2&av=2.2.0&cid=d40c3ead-36ef-473e-8ffb-92a476d33bd7&ul=en&aid=org.openshot.openshot-qt&cd4=5.3.2&cd1=0.1.3&t=screenview&cd=preferences-screen&an=OpenShot+Video+Editor&cd3=5.3.2&ua=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36', 'access-control-allow-origin': '*', 'content-length': '35', 'x-content-type-options': 'nosniff', 'status': '200', 'content-type': 'image/gif', 'server': 'Golfe2', 'cache-control': 'no-cache, no-store, must-revalidate', 'pragma': 'no-cache', 'last-modified': 'Sun, 17 May 1998 03:00:00 GMT', 'expires': 'Mon, 01 Jan 1990 00:00:00 GMT', 'date': 'Thu, 16 Feb 2017 20:11:40 GMT', 'age': '792883'} (b'GIF89a\x01\x00\x01\x00\x80\xff\x00\xff\xff\xff\x00\x00\x00,\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x02D\x01\x00;')
     metrics:INFO Track exception: {'server': 'Apache/2.2.22 (Ubuntu)', 'vary': 'Accept-Encoding', 'content-length': '29', 'status': '200', 'content-type': 'text/html; charset=utf-8', '-content-encoding': 'gzip', 'date': 'Sun, 26 Feb 2017 00:27:10 GMT'} (b'*duplicate-exception-ignored*')


BTW... why do you connect to an URL when pressing on a menu item?


Thanks,
Levente

-- 
73 de HA5 OpenGL
Op.: Levente

**Comment by leventelist** [comment]
2.2 also has this bug.

**Comment by DylanC** [comment]
@xintrea - Does this happen for you in OpenShot v2.3.4?

**Comment by DylanC** [comment]
Works for me in v2.4. Please try the latest version.
