### ISSUE TITLE
Openshot crashes on opening previously-good project

### ISSUE THREAD

**Issue by agdyer** [OpenShot/openshot-qt#3843]
**Describe the bug**
On 4th November, I completed a project. Today I was using OpenShot to open videos from a camera I haven't used before, on importing each video, openshot reported "<file> is not a valid video, audio or image file." The same files could be opened and played in vlc.
After unsuccessfully trying to convert the new files to a usable format, I went back to the previous project. I found that files I had used previously in OpenShot were now not valid, and opening the project file that used them immediately crashed openshot.

Additional information: system was recently upgraded from Ubuntu 18.04 LTS to 20.04 LTS.
I'm guessing a required library has been lost, but that isn't an excuse for crashing when attempting to open a previously-valid project, or any help in identifying how to correct the root cause.

**Steps to reproduce the behavior:**
1. File > Open project
2. browse to a .osp file, click Open button
openshot crashes

**Expected behavior**
Either:
openshot opens the project file
Or:
openshot produces an error message saying why the project file could not be opened.

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Linux-5.4.0-54-generic-x86_64-with-glibc2.29
- Processor: x86_64
- Machine: x86_64
- Python version: 3.8.5
- Qt5 version: 5.12.8
- PyQt5 version: 5.14.1
- Qt Detected Languages: ['en-GB', 'en']
- LANG Environment Variable: en_GB.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Skipped this step

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/vyrzo9tto0qqi0aqclqpuxil7jmizp65/openshot-qt.zip) (8 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/vyrzo9tto0qqi0aqclqpuxil7jmizp65/libopenshot.zip) (4 KB)

**Exception / Stacktrace**
```/lib/x86_64-linux-gnu/libc.so.6 abort                                    0x12b  [0x7f1f86e24859]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6                                          0x9e951  [0x7f1f851d4951]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6                                          0xaa47c  [0x7f1f851e047c]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6                                          0xa9459  [0x7f1f851df459]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6 __gxx_personality_v0                     0x2a1  [0x7f1f851dfe11]
/lib/x86_64-linux-gnu/libgcc_s.so.1                                          0x10bdf  [0x7f1f86036bdf]
/lib/x86_64-linux-gnu/libgcc_s.so.1 _Unwind_RaiseException                   0x331  [0x7f1f86037271]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6 __cxa_throw                              0x3c  [0x7f1f851e078c]
/usr/lib/x86_64-linux-gnu/libopenshot.so.19                                          0x3be53  [0x7f1f7c309e53]
/usr/lib/x86_64-linux-gnu/libopenshot.so.19 openshot::FrameMapper::Open()            0x252  [0x7f1f7c374bb2]
/usr/lib/x86_64-linux-gnu/libopenshot.so.19 openshot::Clip::Open()                   0x37  [0x7f1f7c333a87]
/usr/lib/x86_64-linux-gnu/libopenshot.so.19 openshot...

**Comment by USATechDude** [comment]
Did you try opening one of the recovery files in the `~/.openshot_qt/recovery` folder to see if perhaps your project save file somehow corrupted?

**Comment by agdyer** [comment]
I found a work-around: rename the ~/.openshot_qt directory. The directory was created again when OpenShot was started, and it was then possible to open the same old project, and import videos without getting " is not a valid video, audio or image file." errors. This shows that the project save file was still uncorrupted.
@USATechDude - I tried browsing to the moved recovery folder and opening one of the .osp files there. OpenShot started and reported "Missing file" for each image and clip in the project. OpenShot did not crash. So, do the .osp files use relative filenames that are messed up when the file is moved?
Anyway, it appears that something "bad" in the ~/.openshot_qt directory caused the problem. Is it possible for OpenShot to handle problems in this directory more gracefully, and give an informative error, not just claim valid videos are "not valid" and crash?

**Comment by USATechDude** [comment]
> I tried browsing to the moved recovery folder and opening one of the .osp files there. OpenShot started and reported "Missing file" for each image and clip in the project. OpenShot did not crash. So, do the .osp files use relative filenames that are messed up when the file is moved?
Anyway, it appears that something "bad" in the ~/.openshot_qt directory caused the problem. Is it possible for OpenShot to handle problems in this directory more gracefully, and give an informative error, not just claim valid videos are "not valid" and crash?

@agdyer In OpenShot v2.5.1 I believe that the file paths are absolute, wherein the [latest Daily Builds](https://www.openshot.org/download/#daily) use relative file paths.  The developers have also been working on improving the error messages.  I suggest that you download and install the [latest Daily Build](https://www.openshot.org/download/#daily).
