### ISSUE TITLE
Transparent Background of Photos not working.

### ISSUE THREAD

**Issue by PIZZALOVINWOLF1** [OpenShot/openshot-qt#3845]
**Describe the bug:**
So I pull up a random picture on the internet with a transparent background into Openshot and place it over a video and it treats the grey squares as part of the image and covers the rest of the video with the squares. Anyway I can fix that? I am on version 2.5.1. and I think Windows 8?

**Steps to reproduce the behavior:**

**Expected behavior:**

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by USATechDude** [comment]
Did you check the transparency in Inkscape or GIMP?  If the gray squares are showing, then it's possible that the image from the Internet doesn't really have a transparent background.  Check to see if the file is a GIF, PNG, BMP, or TIFF file since those have transparency.  If your file is a JPG, then it may not have a transparent background after all.
