### ISSUE TITLE
Program crashes when Title dialog is opened

### ISSUE THREAD

**Issue by KarateBob73** [OpenShot/openshot-qt#3846]
**Describe the bug**
Open the Title dialog box to create a non animated title, and program closes entirely
**Steps to reproduce the behavior:**
1. Go to 'Title'
2. Click on Title'
3. Scroll down to any of the options, say grey box, click to use
4. program closes
![Crash from title](https://user-images.githubusercontent.com/74683544/99588130-1f40e500-29b8-11eb-92b8-b5218f56ed9e.gif)

**Expected behavior**
I expect to be able to enter text, etc, and create a title to overlay

**System Details**  IDK what this all is, not SUPER savvy
- OpenShot Version: 2.5.1
- libopenshot Version:  0.2.5
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-6028-39b4aa97-2cb4eeff-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/23l38wp2j96hbl7cklha3l0b55dmi6mr/openshot-qt.zip) (22 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/23l38wp2j96hbl7cklha3l0b55dmi6mr/libopenshot.zip) (11 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by ferdnyc** [comment]
@KarateBob73 

Hmm, that's strange. I tried build 6028 (http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-6028-39b4aa97-2cb4eeff-x86_64.exe) in Windows 10, and as you can see I cannot reproduce:

![image](https://user-images.githubusercontent.com/538020/99654381-37504d00-2a28-11eb-8f57-8dcab90d52cd.png)

There was no info in your logs, either, they just abruptly end at the launch of the Title Editor. (Which, I agree, does seem like an indicator of a crash.)

One possibility, you could try opening a Command Prompt window and running these commands:
```cmd
cd "C:\Program Files\OpenShot Video Editor\"
openshot-qt-cli.exe --debug
```
That'll run OpenShot with full debug output in the Command Prompt window, which might show some error message during the crash that the logs don't capture.
