### ISSUE TITLE
unable to save/open (and it crashes a lot)

### ISSUE THREAD

**Issue by vedlejedle** [OpenShot/openshot-qt#385]
Hi,
I was very happy and I was expecting a lot from Openshot when I was downloading it. I tried few thinks and I realy liked it.... And then it crashed. I started it again and after few minutes it crashed again. Nevermind - I said to myself, I will just save my project a lot, and everything is going to be ok. So I started to do video and I was saving a lot... and it crashed (after quite long time). I was happy, thinking that my progress is saved. I was not happy when I found out, that I can't open the saved file (it just opens a new blank project). I tried to download and install the program again, I tried to download different version... nothing helped. Not sure if the problem is saving or loading , but something is definetly broken (or I am completly stupid and forgot to do something obvious - that is also posible I am new to openshot).

I hope you can give me a good advice, or that you will fix the issue soon, because I hoped to do a lot of work with openshot and I realy like how it appears and works. But without the ability to save I will have to download some other program :-(

I have windows 7

Thanks

**Comment by dkman123** [comment]
I have this same issue with the videos I'm trying to work with.  To give more info:
I'm on Windows 10 64 bit
using OpenShot 2.1.0 (just updated to 33 to see if that fixed it, it didn't)
I'm pulling 3 minute MOVs from my dash cam
trying to export MP4, 720, sped up at 2x
I'd say it's less than 20% chance that it will do it.  Generally I don't make it off 0%
I think it said nt.dll was reporting the exception.  I didn't dig further.

If I flip over to Linux Mint 17.3 and pull OpenShot from the repository (I forget the version right now, but it certainly has a different look and feel) it works just fine.

**Comment by DylanC** [comment]
@vedlejedle - Does this issue happen on OpenShot v2.3.4?

**Comment by DylanC** [comment]
@vedlejedle - Please confirm this issue in the daily build or in v2.3.4. Closing for now until we have confirmed on a newer build.

**Comment by vedlejedle** [comment]
Hi,
I will try to check but I need to instal openshot again... I pulled that
request ages ago, haven' used the program since then.
M.

2017-08-25 14:28 GMT+02:00 DylanC <notifications@github.com>:
