### ISSUE TITLE
Preview video and audio are choppy and get progressively worse over time.

### ISSUE THREAD

**Issue by randomidiot143** [OpenShot/openshot-qt#3853]
When I launch OpenShot, the previews work fine, but the more I edit the clips, or the longer I keep the application running, the choppier the playback becomes. Restarting the program used to work long enough, but now I can't perform more than a single action before it becomes completely unusable. How can I fix this?

**System Details:**
- OpenShot Version 2.5.1
- OS: Windows 10
- System Specs: Intel i7 2.8GHz Quad-core; 500GB SSD; 16GB RAM; 4GB VRAM

**Comment by USATechDude** [comment]
Even though you may have a very powerful computer to edit videos, video editing still takes a lot of resources.  Sometimes, you have to reduce the overhead in OpenShot to speed up the editing process.  Follow the step outlined in [this video](https://vimeo.com/420117641) to see if they help you with your editing.

**Comment by kerryhatcher** [comment]
I'll second @USATechDude on that. That [video](https://vimeo.com/420117641) is great advice. I have a quad core ntel® Xeon(R) CPU E3-1505M v5 @ 2.80GHz, 64GB RAM, and a Quadro M4000M w/ 4GB VRAM.  I also  have bogged down previews as well. Same issue in Adobe Premier with a similar fix.
