### ISSUE TITLE
Data Validation for Profile

### ISSUE THREAD

**Issue by allelopath** [OpenShot/openshot-qt#3856]
Referring to this:
https://github.com/OpenShot/openshot-qt/issues/3848

Data validation of profile 

If invalid data is contained within a profile, a dialog box should popup with an error messages.

**Comment by ferdnyc** [comment]
Just to avoid people having to chase links, a summary of the relevant bits of #3848:

**Describe the bug:**
When exporting the application hangs at 0% progress.

**Square1080.txt**

description=Square_1080x1080_30_fps
frame_rate_num=30
frame_rate_den=1001
width=1080
height=1080
progressive=1
sample_aspect_num=1
sample_aspect_den=1
display_aspect_num=16
display_aspect_den=9
colorspace=709

@USATechDude 
> If you want a frame rate of 29.97 then you need to change the `frame_rate_num` to `30000`. Otherwise, OpenShot is trying to figure out how to calculate a frame rate of 0.02997 using your profile.

@allelopath 
> Ok, my mistake, but there is no data validation of profiles? A min and max frame rate should be decided (where 0.02997 would not be valid) and then checked. If the value is outside of this range, then an error should be flagged.

**Comment by ferdnyc** [comment]
(And I suppose, just for completeness' sake, my own response:)

Even if there were validation, that profile is valid data. It's terrible data, but it's valid. Though I suppose we could add a sanity-check and an "are you sure?" type prompt, if the values are really far outside what would seem to make sense.
