### ISSUE TITLE
Sound scrambled

### ISSUE THREAD

**Issue by vlachoudis** [OpenShot/openshot-qt#3863]
Version 2.5.1 from Ubuntu 20.10

while editing and moving in the timeline up/down while playing the sound
gets scrambled sometimes playing short audio intervals twice.
The scrambled sound gets propagated as well to the exported video.
I need to close and restart the program,
exporting the video from a freshly opened project, then I get correct the sound.

**Comment by Innitinnuit** [comment]
Openshot has a lot of little quirks. A simple restart to fix an occasional issue isn't a massive deal compared to other bugs. Whenever it happens just save and restart.

**Comment by vlachoudis** [comment]
@Innitinnuit this is exactly what I am doing, it not a problem that can stop me from working, I simply wanted to report the bug :smile:

**Comment by Innitinnuit** [comment]
Fair play. Sorry if I seemed combatant! I was just jealous of your bug compared to mine hahah

**Comment by vlachoudis** [comment]
any news on that?

**Comment by JacksonRG** [comment]
@vlachoudis I'm putting together a todo for reworking the audio pipeline. This is now on the list, updates to come.

**Comment by DanPinGF** [comment]
Maybe try updating to the latest OpenShot?
