### ISSUE TITLE
Crop video, freeze video, simple edits of video

### ISSUE THREAD

**Issue by OpenShooter** [OpenShot/openshot-qt#3865]
In making an instructional video for a computer program, I created a screen capture video of the program being used. Now I would like to enhance that video in several ways:

1) Crop a part of the screen for almost the entire video (to get rid of another window behind the one of interest.
2) At certain points in the video, freeze the image for several seconds (to allow narration).
3) Ability to do simple editing on the video. Useful edits would include
    a) Blurring all but a rectangular area of the image.
    b) Adding arrows, lines, callouts, etc to the image.

I know (2) and (3) could be accomplished by splitting the video, obtaining a screen shot of the final frame of the earlier split, editing that image in an external editor, then importing it back into Open Shot, but this is cumbersome. And there seems to be no way in Open Shot to capture a single frame of video as an image. Maybe I just missed something in the documentation.

So, the minimal capabilities that OpenShot needs to accomplish (1)-(3) are
- Ability to click a button and have a single frame of a video appear as a separate image, or stored as an image file (e g, PNG).
- Ability to modify an image using a second "mask" image, presumably running on a separate track. The mask image would be transparent in parts, to let the original video show, and opaque in other parts, to effect a cropping of the original image by replacing the unwanted parts with the pixels from the mask.

**Comment by Innitinnuit** [comment]
You can do all those things.
1) There is a crop tool within effects. Google it.
2) There is a freeze tool. Google it.
3) There is a blur tool. Just blur the whole track and add a track above with the rectangle.

**Comment by OpenShooter** [comment]
I'm pleased to hear that OpenShot can do some of these things already. However, Googling and wading through all the ads and videos is very time-consuming. Why not put the information into the manual, which will save time for all users?

Innitinnuit, your response would be more helpful if you recommended specific sites, as I have no idea what the best (recommended) way is to do each of these things.

**Comment by Innitinnuit** [comment]
![image](https://user-images.githubusercontent.com/75163258/100539105-e01e5980-322b-11eb-823e-070b90315090.png)

I literally google 'Openshot Crop How' and a tutorial video came up. 

I just read the bottom part of your comment. Again, you can do those things. I'd be happy to give more detail normally, but your issues can be fixed with an extremely simple googling and I refuse to hold your hand through that.

**Comment by Innitinnuit** [comment]
![image](https://user-images.githubusercontent.com/75163258/100539658-deef2b80-322f-11eb-8440-c14f65735ee4.png)

Here is another example. Again, 3 or 4 words a couple of seconds.
