### ISSUE TITLE
Reposition keyframe

### ISSUE THREAD

**Issue by vlachoudis** [OpenShot/openshot-qt#3867]
Hi all,

is there a way to reposition a keyframe inside a clip, e.g. drag it left/right with the mouse or keyboard?

What I am doing right now is to create a new keyframe copy the parameters and delete the previous one, but it is rather cumbersome.

Thanks
Vasilis

**Comment by ferdnyc** [comment]
@vlachoudis 

Currently that's the only way, I'm afraid. There's been quite a lot of discussion recently about keyframe editing and interaction (mostly in #3840 and #3823), but as of now that work is still incomplete (or hasn't even started).

**Comment by ferdnyc** [comment]
Any thoughts or suggestions you have would be more than welcome in those discussions. Fair warning though, there's quite a lot of history there already. Just digging through it all and getting up to speed is a bit of a commitment.

**Comment by vlachoudis** [comment]
Thank you @ferdnyc I've just started using openshot and found it very interesting, however as a novice I am not sure if what I am doing is the correct way or not.
