### ISSUE TITLE
Cannot Show Waveform of a clip in the latest Daily Build

### ISSUE THREAD

**Issue by USATechDude** [OpenShot/openshot-qt#3869]
A customer first reported this issue to the Help Desk via E-mail on 24 November 2020.

**Describe the bug:**
In OpenShot-v2.5.1-dev2-6045, I cannot display the clip's waveform using the Right-click menu to Display >> Show Waveform.

**Steps to reproduce the behavior:**
1. Launch OpenShot
2. import an audio clip (Kai_Engel_-_04_-_Moonlight_Reprise.wav)
3. Select the audio clip on the timeline
4. Right-click the audio clip
5. Point to Display
6. Click Show Waveform
7. Error - Nothing happens

**Expected behavior:**
Using the Display >> Show Waveform function should show an audio waveform on an audio clip in the timeline.

**System Details:**
10:26:00 INFO app: openshot-qt version: 2.5.1-dev2
10:26:00 INFO app: libopenshot version: 0.2.5-dev2
10:26:00 INFO app: platform: Linux-5.8.0-3-amd64-x86_64-with-MX-19.3-patito_feo
10:26:00 INFO app: processor: Intel Core i7-7700K Quad Core @4.2GHz
10:26:00 INFO app: machine: x86_64
10:26:00 INFO app: python version: 3.6.9
10:26:00 INFO app: qt5 version: 5.9.5
10:26:00 INFO app: pyqt5 version: 5.10.1

I also tested this feature in Windows (OpenShot-v.2.5.1-dev2-6042) and macOS (OpenShot-v2.5.1-dev2-6028).  I was not able to generate the waveform in any of the operating systems.

**Log Files:**
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/5598749/libopenshot.log)
[openshot-qt_console.log](https://github.com/OpenShot/openshot-qt/files/5598750/openshot-qt_console.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/5598751/openshot-qt.log)

**Exception / Stacktrace:**
ERROR exceptions: Unhandled Exception
Traceback (most recent call last):
  File "/tmp/.mount_VdqPBN/usr/bin/windows/views/webview.py", line 978, in Show_Waveform_Triggered
    if c and c.Reader() and not c.Reader().info.has_single_image:
  File "/home/gitlab-runner/builds/d0022447/0/OpenShot/openshot-qt/openshot.py", line 1145, in <lambda>
  File "/home/gitlab-runner/builds/d0022447/0/OpenShot/openshot-qt/openshot.py", line 80, in _swig_getattr
AttributeError: 'ClipBase' object has no attribute 'Reader'
INFO metrics: Track exception: [200] http://www.openshot.org/exception/json/ | *failed-recording-exception*: Control/space characters not allowed (key=b":1:Linux-2.5.1-dev2-AttributeError: 'ClipBase' objec")
INFO main_window: ---------------- Shutting down -----------------

**Screenshots:**

![2020-11-26 14-03-17](https://user-images.githubusercontent.com/65924242/100290483-1795b900-2f41-11eb-86cf-850d25ba02a8.gif)

**Comment by rexdk** [comment]
Same issue for me on
OpenShot-v2.5.1-dev2-1603696751-07a447c9-46debb51-x86_64
Win10

**Comment by USATechDude** [comment]
I just tried OpenShot-v2.5.1-dev2-6230-bdb3eea9-beec0d15-x86_64.exe, and I was able to display the waveform on my clip successfully.  The macOS build is still 6028, so it is not displaying the waveform. However, the developers are aware of the Mac Builds issues.
I opened my Ubuntu 20.04.1 VM and launched the Daily Build of OpenShot from the PPA.  I was able to use Display >> Show Waveform successfully.

**Comment by rexdk** [comment]
Ah yes, works for me on the latest build from 23Dec. Reminds me why I don't like installing daily builds though, as the longest it's stayed open without crashing so far is 15 minutes... :)  That's part of daily builds of course, not a problem
