### ISSUE TITLE
openshot's PPA isn't available for Ubuntu 16.10

### ISSUE THREAD

**Issue by nolsen42** [OpenShot/openshot-qt#387]
When will support for Ubuntu 16.10 be available? The openshot available in ubuntu's repo is heavily outdated.

**Comment by mray** [comment]
Also, the AppImage version of OpenShot does not seem to work (at least on my Ubuntu 16.10)

**Comment by probonopd** [comment]
> Also, the AppImage version of OpenShot does not seem to work (at least on my Ubuntu 16.10)

Please be more specific. Is it still trying to mix Qt from the AppImage and the system?

**Comment by herrdeh** [comment]
I couldn't either make the AppImage run.
So I tried to install it from the sources. First got the error:
"Package pyqt5 cannot be found". So I installed the "python3-pyqt5" ubuntu package.

Trying to start openshot-qt from the terminal leads to:

Loaded modules from installed directory: /usr/local/lib/python3.5/dist-packages/openshot_qt-2.1.0.dev1-py3.5.egg/openshot_qt
      logger:ERROR Traceback (most recent call last):
      logger:ERROR   File "/usr/local/bin/openshot-qt", line 11, in <module>
      logger:ERROR load_entry_point('openshot-qt==2.1.0.dev1', 'gui_scripts', 'openshot-qt')()
      logger:ERROR   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 565, in load_entry_point
      logger:ERROR return get_distribution(dist).load_entry_point(group, name)
      logger:ERROR   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2589, in load_entry_point
      logger:ERROR return ep.load()
      logger:ERROR   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2249, in load
      logger:ERROR return self.resolve()
      logger:ERROR   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2255, in resolve
      logger:ERROR module = __import__(self.module_name, fromlist=['__name__'], level=0)
      logger:ERROR   File "/usr/local/lib/python3.5/dist-packages/openshot_qt-2.1.0.dev1-py3.5.egg/openshot_qt/launch.py", line 53, in <module>
      logger:ERROR from classes.app import OpenShotApp
      logger:ERROR   File "/usr/local/lib/python3.5/dist-packages/openshot_qt-2.1.0.dev1-py3.5.egg/openshot_qt/classes/app.py", line 41, in <module>
      logger:ERROR from classes import info, settings, project_data, updates, language, ui_util, logger_libopenshot
      logger:ERROR   File "/usr/local/lib/python3.5/dist-packages/openshot_qt-2.1.0.dev1-py3.5.egg/openshot_qt/classes/logger_libopenshot.py", line 31, in <module>
      logger:ERROR import openshot
      logger:ERROR ImportError
      logger:ERROR :
      logger:ERROR No module named 'openshot'

I'd really love to get a more recent openshot than 1.43.

Cheers,
Wolf

**Comment by herrdeh** [comment]
Trying to start the AppImage gives these entries in the syslog:

Nov 14 12:08:17 Simux nemo-autostart.desktop[1976]: /tmp/.mount_BvlBFa/usr/bin/openshot-qt.wrapper
Nov 14 12:08:19 Simux kernel: [10942.006652] launch[11807]: segfault at 1b20 ip 0000000000001b20 sp 00007fff35f81bd8 error 14 in launch[400000+6000]

Let me know what I shall do for further debugging.

**Comment by probonopd** [comment]
It must not load stuff from `/usr/local/lib/python3.5/`. Never mix Python stuff from inside the AppImage with Python stuff from the outside.

**Comment by herrdeh** [comment]
Sorry - I don't understand what you are trying to tell me. Could you please be more dummy-compatible... (-;

**Comment by herrdeh** [comment]
Still no release candidate for ubuntu 16.10.
Could somebody be so kind and tell us something like "we're working on it" or so? - I'm really waiting... (-;

**Comment by mfraser** [comment]
Still nothing. Can't even get the Openshot version in the standard repositories to work.

**Comment by herrdeh** [comment]
Is now resolved - I could install OpenShot 2.2

**Comment by nolsen42** [comment]
The openshot PPA is now available for Ubuntu 16.10, I guess this issue no longer needs to be opened now.
