### ISSUE TITLE
 Caught signal 11 (SIGSEGV) ---- Unhandled Exception

### ISSUE THREAD

**Issue by Jar-357** [OpenShot/openshot-qt#3872]
**Describe the bug:**
crashing when attempting export 

**System Details:**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Linux-5.7.0-2parrot2-amd64-x86_64-with-Parrot-4.10-rolling
- Processor: amd fx 6300 6 core
- Machine: x86_64
- Python version: 3.6.9
- Qt5 version: 5.9.5
- PyQt5 version: 5.10.1
- Qt Detected Languages: ['en-GB', 'en']
- LANG Environment Variable: en_GB.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-6045-39b4aa97-2cb4eeff-x86_64.AppImage

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/vf1zsal7r0g9lte4wph3hx8lm7fkrnkd/openshot-qt.zip) (70 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/vf1zsal7r0g9lte4wph3hx8lm7fkrnkd/libopenshot.zip) (70 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Log Files:**
[openshot-qt (copy).log.zip](https://github.com/OpenShot/openshot-qt/files/5602527/openshot-qt.copy.log.zip)
[libopenshot (copy).log.zip](https://github.com/OpenShot/openshot-qt/files/5602572/libopenshot.copy.log.zip)
![Screenshot at 2020-11-26 11-30-56](https://user-images.githubusercontent.com/51335665/100346244-6ee86780-2fdb-11eb-8985-231a44fa667a.png)
![Screenshot at 2020-11-26 11-32-15](https://user-images.githubusercontent.com/51335665/100346320-8c1d3600-2fdb-11eb-8ac4-c25be871f38f.png)

**Exception / Stacktrace:**
Hardware decoding device number: 1
Caught signal 11 (SIGSEGV)
---- Unhandled Exception: Stack Trace ----

Caught signal 11 (SIGSEGV)
---- Unhandled Exception: Stack Trace ----
  /tmp/.mount_aEryYe/usr/bin/libQt5Core.so.5 ( QAbstractEventDispatcher::registerTimer(int, Qt::TimerType, QObject*)  + 0x19  )  [0x7f3776227309]
  /tmp/.mount_aEryYe/usr/bin/libQt5Core.so.5 ( QBasicTimer::start(int, QObject*)         + 0x7f  )  [0x7f3776227acf]
  /tmp/.mount_aEryYe/usr/bin/libQt5Widgets.so.5 ( QAbstractItemView::setRootIndex(QModelIndex const&)  + 0x7a  )  [0x7f37706765ca]
                              + 0x253cb1)  [0x7f37761f3cb1]

![Screenshot at 2020-11-26 11-30-56](https://user-images.githubusercontent.com/51335665/100346370-a6571400-2fdb-11eb-9b6c-6a368219bfc9.png)
![Screenshot at 2020-11-26 11-32-39](https://user-images.githubusercontent.com/51335665/100346374-a820d780-2fdb-11eb-9c98-ef61292c4a96.png)

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by WhymustIhaveaname** [comment]
I have exactly the same problem! I spent 3 hours editing the video, and it crashes at the final step! F**k!

**Comment by WhymustIhaveaname** [comment]
Desperately, I run OpenShot with sudo, and it works! At least it works. Now the progress is 45%. Sorry for the f word @openshot developer.

**Comment by Jar-357** [comment]
I ended up reinstalling my  OS, NOT because of this I had other reasons.  I likely caused this myself messing about with nvidia drivers and org conf etc I use the OS recommended  nouveau
software
nouveau.freedesktop.org now and everything's been fine

**Comment by WhymustIhaveaname** [comment]
Not good, the final video's audio is not synchronized! Also, the file name is "Untitled Project.mp4" but I gave it a name before! 

I decide to uninstall openshot and try other open-source video editors like flowblade.
