### ISSUE TITLE
Private metrics are sent unsecured via http

### ISSUE THREAD

**Issue by kmq** [OpenShot/openshot-qt#3875]
Openshot sends analytics to google UNENCRYPTED.

in https://github.com/OpenShot/openshot-qt/blob/837cc1542997f1fa197ed72a98bc7b5053f2f42f/src/classes/metrics.py#L169

which fits the non-chalant attitude displayed in the other bug-reports on user privacy that I have researched in making this report.

Please, at the very *least* send  user data via HTTPS.

Anonymity is not an all or nothing things, it is something gradual.

**Comment by Innitinnuit** [comment]
Good idea
