### ISSUE TITLE
Spilit clip can't spilit audio

### ISSUE THREAD

**Issue by nkson** [OpenShot/openshot-qt#388]
I'm just checking spilit audio mp3 file but fail. Can't play audio in this module. When i move the mouse on the timeline, the module can read the time but no move. I think this is a bug of app. Please some one do this.
Thanks you,
Kim Son

**Comment by JtLively** [comment]
You seem to be reporting multiple issues. To focus on the "Split clip [...] audio", ensure you have audio enabled for both splices and the entire track. If you need audio from a video file, you can import it in Audacity and you'll be able to easily create a mp3 file.

**Comment by JtLively** [comment]
If you have more issues, please ask in #openshot IRC channel and/or open a new issue (one issue per report) along with version and OS/distro.
