### ISSUE TITLE
Snapping Bug

### ISSUE THREAD

**Issue by Innitinnuit** [OpenShot/openshot-qt#3880]
Whenever I have two images I want to align the snapping tool - as well as turning off snap and dragging- will not align properly. One or the other is always one frame out. This happens at all zoom levels. 

The only solutions so far have been:
1) Zoom in fully and drag back and forth over the red cursor. After 5 or 6 times it works. Never less than that.

2) In properties to manually adjust the end point. However there is no rhyme or reason to this. Every issue is one frame out, so the same, but the number that I need to change in End has no logic to it. If it's always one frame out why can't I just always add on 0.1 for example and that fix the issue? I have to randomly guess numbers until the solution is fixed.

**Comment by rexdk** [comment]
Looks to me as though 2 abutting images snap to align with a one frame overlap. That may possibly be deliberate - I know there are difficulties at the joins and I think some sort of fudge to get it to work. Think I may have seen it in the code.

If it matters to you, and you want to adjust the End property of the first clip, remember that it is set in seconds, so the adjustment needs to be scaled. But even so I just found you need to adjust by slightly less than one frame (rounding errors possibly) - and then you get a visible gap between the clips - which is technically OK, though looks wrong. 

You can also align the images to have that gap without snap if your eye is good.
