### ISSUE TITLE
Endless loop occurs when a file referenced by a project (.osp) file cannot be found.

### ISSUE THREAD

**Issue by SANPartnership** [OpenShot/openshot-qt#3885]
**Describe the bug**
Upon opening a project file that references a missing .avi file, the error triggers a file selection dialog which cannot be closed. Unless the missing file is located and selected, the only way to recover control is to kill OpenShot in Task Manager and relaunch the program.

**Steps to reproduce the behavior:**
1. Create a project file that references an .avi or other video file.
2. Delete the referenced file.
3. Open the project file.
4. Notice the error message regarding the missing file, and the presence of a selection window with which to locate the file.
5. Attempt to close the selection window without locating and selecting the missing file (by clicking on the "x").
6. The selection window will not close unless the missing file is located and selected.

**Expected behavior**
The selection window should close, providing continuing access to the program.

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-6090-39b4aa97-2cb4eeff-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/736kcfci1dh6vxt4bh076s832q77t5ts/openshot-qt.zip) (11 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by Innitinnuit** [comment]
I usually have to click cancel two or three times for each missing file before it will open the project.

**Comment by Innitinnuit** [comment]
I found out when talking to one of the tech guys that if you press the ESC key it will stop looking for it. Before that I was pressing cancel 5-20 times to stop it asking for a missing file.
