### ISSUE TITLE
filenotfound

### ISSUE THREAD

**Issue by stellankinberg** [OpenShot/openshot-qt#3886]

**Comment by stellankinberg** [comment]
I saw that filenotfound was closed. The solution in that issue did not solve my problem. 
I have the same problem but tried another solution. I took a copy of another svg and renamed it with the name of the "missing file but no solution. It continued to stop alerting me of the missing file that i now [created.] 
I tink that openshot should give a list of missing files instead and continue. Having that list I can then add these in assets. and reopen the project.
![filenot found](https://user-images.githubusercontent.com/742374/100592833-eda11580-32f7-11eb-921c-ac46cac4423a.png)

**Comment by Innitinnuit** [comment]
The file has to be in the same folder as the original, was it?
