### ISSUE TITLE
Reinstalled itself randomly. Now crashes when try to open project files

### ISSUE THREAD

**Issue by Innitinnuit** [OpenShot/openshot-qt#3887]
Openshot reinstalled itself. I don't know why. Now projects I was working on today crash when I try to open them.

------------------------------------------
libopenshot logging: Wed Dec  2 15:09:28 2020
------------------------------------------
---- Unhandled Exception: Stack Trace ----
  /lib/x86_64-linux-gnu/libopenshot.so.19 openshot::FFmpegReader::Close()          0x62c  [0x7f757377c91c]
  /lib/x86_64-linux-gnu/libopenshot.so.19 openshot::FrameMapper::Close()           0x269  [0x7f75737a2989]
  /lib/x86_64-linux-gnu/libopenshot.so.19 openshot::Clip::Close()                  0x26e  [0x7f757375b23e]
  /lib/x86_64-linux-gnu/libopenshot.so.19 openshot::Timeline::update_open_clips(openshot::Clip*, bool) 0x6b5  [0x7f75737b8cc5]
  /lib/x86_64-linux-gnu/libopenshot.so.19 openshot::Timeline::find_intersecting_clips(long, int, bool) 0x36a  [0x7f75737b979a]
  /lib/x86_64-linux-gnu/libopenshot.so.19 openshot::Timeline::GetFrame(long)       0x7b1  [0x7f75737ba151]
  /lib/x86_64-linux-gnu/libopenshot.so.19 openshot::VideoCacheThread::run()        0x9a  [0x7f75737e2e9a]
  /lib/x86_64-linux-gnu/libopenshot-audio.so.7 juce::Thread::threadEntryPoint()         0xd9  [0x7f757364bb09]
  /lib/x86_64-linux-gnu/libopenshot-audio.so.7                                          0x136c3d  [0x7f757364bc3d]
  /lib/x86_64-linux-gnu/libpthread.so.0                                          0x9609  [0x7f75b5c96609]
  /lib/x86_64-linux-gnu/libc.so.6 clone                                    0x43  [0x7f75b5dd2293]
---- End of Stack Trace ----
---- Unhandled Exception: Stack Trace ----
  /lib/x86_64-linux-gnu/libQt5Gui.so.5                                          0x484030  [0x7f75b1723030]
  /lib/x86_64-linux-gnu/libQt5Gui.so.5 QOpenGLFunctions::initializeOpenGLFunctions() 0xf  [0x7f75b172322f]
  /lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5                                          0x788225  [0x7f75a98ed225]
  /lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5                                          0x78ab3d  [0x7f75a98efb3d]
  /lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5                                          0x78ae56  [0x7f75a98efe56]
  /lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5                                          0x78b89d  [0x7f75a98f089d]
  /lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5                                          0x790deb  [0x7f75a98f5deb]
  /lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5                                          0x77abc7  [0x7f75a98dfbc7]
  /lib/x86_64-linux-gnu/libQt5Quick.so.5 QQuickWindowPrivate::updateDirtyNode(QQuickItem*) 0x850  [0x7f75a8eb7320]
  /lib/x86_64-linux-gnu/libQt5Quick.so.5 QQuickWindowPrivate::updateDirtyNodes()  0x8b  [0x7f75a8eb7bdb]
  /lib/x86_64-linux-gnu/libQt5Quick.so.5 QQuickWindowPrivate::syncSceneGraph()    0x86  [0x7f75a8eb9106]
  /lib/x86_64-linux-gnu/libQt5Quick.so.5 QQuickRenderControl::sync()              0x1d  [0x7f75a8f84f6d]
  /lib/x86_64-linux-gnu/libQt5QuickWidgets.so.5                                          0xbe85  [0x7f75a8c07e85]
  /lib/x86_64-linux-gnu/libQt5QuickWidgets.so.5                                          0xc05c  [0x7f75a8c0805c]
  /lib/x86_64-linux-gnu/libQt5Core.so.5 QObject::event(QEvent*)                  0x1d5  [0x7f75b40f9cf5]
  /lib/x86_64-linux-gnu/libQt5Widgets.so.5 QWidget::event(QEvent*)                  0x22d  [0x7f75b029b25d]
  /lib/x86_64-linux-gnu/libQt5QuickWidgets.so.5 QQuickWidget::event(QEvent*)             0xd3  [0x7f75a8c0bce3]
  /lib/x86_64-linux-gnu/libQt5WebEngineWidgets.so.5                                          0x34686  [0x7f75b000a686]
  /lib/x86_64-linux-gnu/libQt5Widgets.so.5 QApplicationPrivate::notify_helper(QObject*, QEvent*) 0x86  [0x7f75b0258a66]
  /lib/x86_64-linux-gnu/libQt5Widgets.so.5 QApplication::notify(QObject*, QEvent*)  0x330  [0x7f75b02620f0]
  /usr/lib/python3/dist-packages/PyQt5/QtWidgets.cpython-38-x86_64-linux-gnu.so                                          0x3d6bf6  [0x7f75b0b5fbf6]
  /lib/x86_64-linux-gnu/libQt5Core.so.5 QCoreApplication::notifyInternal2(QObject*, QEvent*) 0x18a  [0x7f75b40cd93a]
  /lib/x86_64-linux-gnu/libQt5Core.so.5 QTimerInfoList::activateTimers()         0x3d0  [0x7f75b41248b0]
  /lib/x86_64-linux-gnu/libQt5Core.so.5                                          0x2de19c  [0x7f75b412519c]
  /lib/x86_64-linux-gnu/libglib-2.0.so.0 g_main_context_dispatch                  0x27d  [0x7f75b489bfbd]
  /lib/x86_64-linux-gnu/libglib-2.0.so.0                                          0x52240  [0x7f75b489c240]
  /lib/x86_64-linux-gnu/libglib-2.0.so.0 g_main_context_iteration                 0x33  [0x7f75b489c2e3]
  /lib/x86_64-linux-gnu/libQt5Core.so.5 QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) 0x65  [0x7f75b4125565]
  /lib/x86_64-linux-gnu/libQt5Core.so.5 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) 0x12b  [0x7f75b40cc4db]
  /lib/x86_64-linux-gnu/libQt5Core.so.5 QCoreApplication::exec()                 0x96  [0x7f75b40d4246]
  /usr/lib/python3/dist-packages/PyQt5/QtWidgets.cpython-38-x86_64-linux-gnu.so                                          0x3979c1  [0x7f75b0b209c1]
  /usr/bin/python3               PyCFunction_Call                         0xfa  [0x5f42ea]
  /usr/bin/python3               _PyObject_MakeTpCall                     0x296  [0x5f46d6]
  /usr/bin/python3               _PyEval_EvalFrameDefault                 0x5de6  [0x570936]
  /usr/bin/python3                                                         [0x50a14e]
  /usr/bin/python3               _PyEval_EvalFrameDefault                 0x5736  [0x570286]
  /usr/bin/python3               _PyFunction_Vectorcall                   0x1b6  [0x5f7146]
  /usr/bin/python3               _PyEval_EvalFrameDefault                 0x71e  [0x56b26e]
  /usr/bin/python3               _PyEval_EvalCodeWithName                 0x26a  [0x56955a]
  /usr/bin/python3               PyEval_EvalCode                          0x27  [0x68c4a7]
  /usr/bin/python3                                                         [0x67bc91]
  /usr/bin/python3                                                         [0x67bd0f]
  /usr/bin/python3               PyRun_FileExFlags                        0x9b  [0x67bdcb]
  /usr/bin/python3               PyRun_SimpleFileExFlags                  0x17e  [0x67de4e]
  /usr/bin/python3               Py_RunMain                               0x212  [0x6b6032]
  /usr/bin/python3               Py_BytesMain                             0x2d  [0x6b63bd]
  /lib/x86_64-linux-gnu/libc.so.6 __libc_start_main                        0xf3  [0x7f75b5cd70b3]
  /usr/bin/python3               _start                                   0x2e  [0x5fa4de]
---- End of Stack Trace ----

15:09:27 INFO app: ------------------------------------------------
15:09:27 INFO app:             Wed Dec  2 15:09:27 2020            
15:09:27 INFO app:               Starting new session              
15:09:27 INFO app: ------------------------------------------------
15:09:27 INFO app:          OpenShot (version 2.5.1-dev2)          
15:09:27 INFO app: ------------------------------------------------
15:09:27 INFO app: openshot-qt version: 2.5.1-dev2
15:09:27 INFO app: libopenshot version: 0.2.5-dev2
15:09:28 INFO app: platform: Linux-5.4.0-56-generic-x86_64-with-glibc2.29
15:09:28 INFO app: processor: x86_64
15:09:28 INFO app: machine: x86_64
15:09:28 INFO app: python version: 3.8.5
15:09:28 INFO app: qt5 version: 5.12.8
15:09:28 INFO app: pyqt5 version: 5.14.1
15:09:28 INFO language: Qt Detected Languages: ['en-GB', 'en']
15:09:28 INFO language: LANG Environment Variable: en_GB.UTF-8
15:09:28 INFO language: LOCALE Environment Variable: 
15:09:28 INFO language: OpenShot Preference Language: Default
15:09:28 INFO project_data: Setting default profile to HD 720p 30 fps
15:09:28 INFO app: Setting font to /usr/lib/python3/dist-packages/openshot_qt/images/fonts/Ubuntu-R.ttf
15:09:28 INFO logger_libopenshot: Connecting to libopenshot with debug port: 5556
15:09:28 INFO app: Setting custom dark theme
15:09:28 INFO ui_util: Initializing UI for MainWindow
15:09:29 INFO webengine: WebEngine backend initializing
15:09:29 INFO thumbnail: Starting thumbnail server listening on port 41071
15:09:29 INFO transition_model: updating transitions model.
15:09:29 INFO version: Found current version: {"openshot_version": "2.5.1"}
15:09:29 INFO effects_model: updating effects model.
15:09:29 INFO effects_model: Generating thumbnail for /home/navin/.openshot_qt/cache/caption.png (/usr/lib/python3/dist-packages/openshot_qt/effects/icons/caption.png)
15:09:29 INFO emoji_model: updating emoji model.
15:09:30 INFO main_window: InitCacheSettings
15:09:30 INFO main_window: cache-mode: CacheMemory
15:09:30 INFO main_window: cache-limit-mb: 250
15:09:30 INFO main_window: Creating CacheMemory object with 262144000 byte limit
15:09:30 INFO preview_thread: QThread Start Method Invoked
15:09:30 INFO main_window: Clear all thumbnails: /home/navin/.openshot_qt/thumbnail
15:09:30 INFO main_window: Clear all animations: /home/navin/.openshot_qt/blender
15:09:30 INFO main_window: Clear all titles: /home/navin/.openshot_qt/title
15:09:30 INFO main_window: updateStatusChanged
15:09:30 INFO main_window: updateStatusChanged
15:09:30 INFO app: Process command-line arguments: ['/usr/bin/openshot-qt']
15:09:30 INFO main_window: recover_backup
15:09:30 INFO project_data: Setting default profile to HD 720p 30 fps
15:09:30 INFO preview_thread: player Position(): 1
15:09:30 INFO video_widget: Load: Set video widget display aspect ratio to: 1.7777777910232544
15:09:30 INFO video_widget: Set video widget pixel aspect ratio to: 1.0
15:09:30 INFO main_window: updateStatusChanged
15:09:30 INFO main_window: foundCurrentVersion: Found the latest version: 2.5.1
15:09:30 INFO webengine: Registering WebChannel connection with WebEngine
15:09:30 INFO preview_thread: player Position(): 1
15:09:31 INFO timeline: Adjusting max size of preview image: PyQt5.QtCore.QSize(718, 404)
15:09:31 INFO preview_thread: player Position(): 1
15:09:31 ERROR webengine: angular-animate.min.js@L14: Uncaught TypeError: m.module(...).info is not a function
15:09:31 INFO webview: Qt Ready
15:09:31 INFO webview: Angular Ready
15:09:40 INFO ui_util: Initializing UI for Dialog
15:09:40 WARNING about: No changelog files found, disabling button
15:10:19 INFO main_window: Clear all thumbnails: /home/navin/.openshot_qt/thumbnail
15:10:19 INFO main_window: Clear all animations: /home/navin/.openshot_qt/blender
15:10:19 INFO main_window: Clear all titles: /home/navin/.openshot_qt/title
15:10:19 INFO project_data: Setting default profile to HD 720p 30 fps
15:10:19 INFO project_data: Loading project file: /home/navin/Documents/ARG/OpenSHot Files/Untitled Project1.osp
15:10:19 INFO assets: Using existing asset folder /home/navin/Documents/ARG/OpenSHot Files/Untitled Project1_assets
15:10:19 INFO assets: Using existing asset folder /home/navin/Documents/ARG/OpenSHot Files/Untitled Project1_assets
15:10:19 INFO assets: Using existing asset folder /home/navin/Documents/ARG/OpenSHot Files/Untitled Project1_assets
15:10:19 INFO project_data: checking project files...
15:10:19 INFO project_data: checking file /home/navin/Desktop/rvgtrailer5.mp4
15:10:19 INFO project_data: checking file /home/navin/Desktop/untitled1.mp3
15:10:19 INFO project_data: checking file /home/navin/Documents/ARG/EPISODES/13/Untitled Project1.mp3
15:10:19 INFO project_data: checking file /home/navin/Desktop/untitled.mp3
15:10:19 INFO project_data: checking file /home/navin/Downloads/boy-2328038_640.png
15:10:19 INFO project_data: checking file /home/navin/Downloads/On-air-Thinkstocck.jpg
15:10:19 INFO project_data: checking file /home/navin/Downloads/american-christmas-traditions-gettyimages-487756624.jpg
15:10:19 INFO project_data: checking file /home/navin/Downloads/oekaki-2009817_640.jpg
15:10:19 INFO project_data: checking file /home/navin/Documents/ARG/EPISODES/13/title.png
15:10:19 INFO project_data: checking file /home/navin/Documents/ARG/EPISODES/13/DISWELL.png
15:10:19 INFO project_data: checking file /home/navin/Downloads/index999999999999.jpeg
15:10:19 INFO project_data: checking file /home/navin/Downloads/Waipod Phetsuphan , Ding Ding Dong.mp4.mp3
15:10:19 INFO project_data: checking file /home/navin/Downloads/zen-garden.mp3
15:10:19 INFO project_data: checking file /home/navin/Downloads/underglow.mp3
15:10:19 INFO project_data: checking file /home/navin/Documents/Projects/YouTube/RVG/Every Episode/deleted scenes.mp4
15:10:19 INFO project_data: checking file /home/navin/Documents/Projects/YouTube/RVG/Every Episode/y2mate.com - vietnam_traditional_folk_music_yvoJdhkxYIs_160kbps.webm
15:10:19 INFO project_data: checking file /home/navin/Documents/Projects/YouTube/RVG/Misc/endtitle.png
15:10:19 INFO project_data: checking file /home/navin/Desktop/90sweb.png
15:10:19 INFO project_data: checking file /home/navin/Downloads/metaphor-1209691_1920.jpg
15:10:19 INFO project_data: checking file /home/navin/Downloads/33722ca883044584c5ce7e1a8ee96550.webp
15:10:19 INFO project_data: checking file /home/navin/Downloads/error-2129569_1280.jpg
15:10:19 INFO project_data: checking file /home/navin/Desktop/trailerwallpaper.jpg
15:10:19 INFO project_data: checking file /home/navin/Desktop/bloopers.png
15:10:19 INFO project_data: checking file /home/navin/Downloads/179223__efecto-fundador__digital-error.wav
15:10:19 INFO project_data: checking file /home/navin/Desktop/kradenoe_solntse_1943_512kb.mp4
15:10:19 INFO project_data: checking file /home/navin/Desktop/pagan-cross.mp3
15:10:19 INFO project_data: checking file /home/navin/Downloads/al-andalus.mp3
15:10:19 INFO project_data: checking file /home/navin/Desktop/personalanswer.png
15:10:19 INFO project_data: checking file /home/navin/Desktop/COMMENT-NAME10-RVG.png
15:10:19 INFO project_data: checking file /home/navin/Downloads/pagan-cross.mp3
15:10:19 INFO project_data: checking file /home/navin/Desktop/COMMENT-NAME9-RVG.png
15:10:19 INFO project_data: checking file /home/navin/Desktop/COMMENT-NAME8-RVG.png
15:10:19 INFO project_data: checking file /home/navin/Desktop/COMMENT-NAME7-RVG.png
15:10:19 INFO project_data: checking file /home/navin/Downloads/dire-space-emergency.mp3
15:10:19 INFO project_data: checking file /home/navin/Desktop/COMMENT-NAME6-RVG.png
15:10:19 INFO project_data: checking file /home/navin/Downloads/love-3556651_640.png
15:10:19 INFO project_data: checking file /home/navin/Desktop/COMMENT-NAME5-RVG.png
15:10:19 INFO project_data: checking file /home/navin/Desktop/COMMENT-NAME4-RVG.png
15:10:19 INFO project_data: checking file /home/navin/Downloads/signs-to-nowhere.mp3
15:10:19 INFO project_data: checking file /home/navin/Desktop/COMMENT-NAME3-RVG.png
15:10:19 INFO project_data: checking file /home/navin/Downloads/index99.jpeg
15:10:19 INFO project_data: checking file /home/navin/Desktop/COMMENT-NAME2-RVG.png
15:10:19 INFO project_data: checking file /home/navin/Desktop/fix.png
15:10:19 INFO project_data: checking file /home/navin/Desktop/COMMENT-NAME-RVG.png
15:10:19 INFO project_data: checking file /home/navin/Downloads/subtitle video.mp4
15:10:19 INFO project_data: checking file /home/navin/Desktop/wall-1217083_1280(1).jpg
15:10:19 INFO project_data: checking file /home/navin/Downloads/index.jpeg
15:10:19 INFO project_data: checking file /home/navin/Downloads/insfdfsdfdex.jpeg
15:10:19 INFO project_data: checking file /home/navin/Downloads/Lilac-Bowls-335ml-Plastic-LAVE2BOWL_th2.jpg
15:10:19 INFO project_data: checking file /home/navin/Downloads/cheesy-ranch-burger.jpg
15:10:19 INFO project_data: checking file /home/navin/Downloads/images.jpeg
15:10:19 INFO project_data: checking file /home/navin/Downloads/indekkkx.jpeg
15:10:19 INFO project_data: checking file /home/navin/Downloads/index890.jpeg
15:10:19 INFO project_data: checking file /home/navin/Downloads/index98.jpeg
15:10:19 INFO project_data: checking file /home/navin/Downloads/index9.jpeg
15:10:19 INFO project_data: checking file /home/navin/Downloads/710tVLiJOsL.jpg
15:10:19 INFO project_data: checking file /home/navin/Downloads/HLB1c9ehP9rqK1RjSZK9q6xyypXaD.jpg
15:10:19 INFO project_data: checking file /home/navin/Downloads/food-2202399_640.jpg
15:10:19 INFO project_data: checking file /home/navin/Downloads/boy-179376_640.jpg
15:10:19 INFO project_data: checking file /home/navin/Downloads/worm-1439069_640.jpg
15:10:19 INFO project_data: checking file /home/navin/Downloads/ca63640d6a175b2b259ad0396b094c19.jpg
15:10:19 INFO project_data: checking file /home/navin/Downloads/napkins-5073819_640.jpg
15:10:19 INFO project_data: checking file /home/navin/Downloads/il_340x270.774243765_5c7h.jpg
15:10:19 INFO project_data: checking file /home/navin/Downloads/fancy-a-spit-roast-card.jpg
15:10:19 INFO project_data: checking file /home/navin/Downloads/Filthy-Animal-Greeting-Card.webp
15:10:19 INFO project_data: checking file /home/navin/Desktop/Rvg-backgroundmusic-trailer.wav
15:10:19 INFO project_data: checking file /home/navin/Desktop/rvgtrailer4.mp4
15:10:19 INFO project_data: checking file /home/navin/Downloads/rvg 13.mp4
15:10:19 INFO project_data: Project data: openshot 2.5.1-dev2, libopenshot 0.2.5-dev2
15:10:19 INFO preview_thread: player Position(): 1
15:10:21 INFO video_widget: Load: Set video widget display aspect ratio to: 1.7777777910232544
15:10:21 INFO video_widget: Set video widget pixel aspect ratio to: 1.0
15:10:21 INFO main_window: updateStatusChanged
15:10:21 INFO main_window: updateStatusChanged
15:10:21 INFO main_window: updateStatusChanged
15:10:21 INFO main_window: updateStatusChanged
15:10:21 INFO preview_thread: player Position(): 1
15:10:21 INFO main_window: Loaded project /home/navin/Documents/ARG/OpenSHot Files/Untitled Project1.osp
15:10:38 INFO preview_thread: previewFrame: 1239, player Position(): 1239
15:10:40 INFO preview_thread: previewFrame: 1700, player Position(): 1700

**Comment by ferdnyc** [comment]
@Innitinnuit 

I know you closed this (though I don't know why), but did you install OpenShot from the daily PPA? That'll update to every new build whenever you `apt update`, and some of them may definitely be buggy. We generally don't recommend tracking the daily builds unless you're testing/developing OpenShot.
