### ISSUE TITLE
Inconsistent export behavior when video has no audio

### ISSUE THREAD

**Issue by wwahammy** [OpenShot/openshot-qt#3889]
**Describe the bug:**
When attempting to export a video with no audio, the behavior of exporting via some encoders varies. In some encoders, such as the CPU MP4 (h.264) encoder, the export succeeds. In others, such as the CPU webm (vpx) encoder, the user receives an Export Error stating: 
"Sorry, there was an error exporting your video: 
A valid audio codec could not be found for this file."

I provide example encoders below; I only tested those 4 encoders so I don't know which other encoders succeed or fail.

**Steps to reproduce the behavior:**
1. Record your desktop using Peek. Save as .webm file.
2. Open "OpenShot", import the given shareshare video and place onto the track
3. Go to Export Video (press Ctrl+E or go to File->Export Project->Export Video in menus)
4. Select one of the following targets:
* CPU MP4 (h.264)
* VA-API MP4 (h.264 va)
5. Give your export file name the extension of .mp4. 
6. Press Export Video. Export will succeed.
7. Restart the Export Video screen and select one of the following targets:
* CPU MP4 (mpeg4)
* CPU WEBM (vpx)
8. Give your export file name the extension of .mp4 or .webm respectively.
9. Press Export Video. Export Error alert pops up with the error:
"Sorry, there was an error exporting your video: 
A valid audio codec could not be found for this file."

**Expected behavior:**
I believe the behavior should be consistent, either they all succeed or they all fail. Ideally, I think they should all succeed.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 2.5.1 via flatpak
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]: Pop!_OS 20.10

**Comment by Innitinnuit** [comment]
> Ideally, I think they should all succeed.

Made me chuckle.
