### ISSUE TITLE
mlt?

### ISSUE THREAD

**Issue by cvaldesmol** [OpenShot/openshot-qt#389]
This is not really an issue but a question. I am starting my video editor project and I have to decide between mlt and libopenshot. I see some time ago openshot used mlt, I just wonder why you decided to move away from mlt to create your own library, Thanks in advance for your help

**Comment by jonoomph** [comment]
This is not really an issue, huh? This is documented on the OpenShot website and blog. Short version: we wanted a more powerful framework, and the ability and control to change and fix it. Thx.
