### ISSUE TITLE
COMMON BUGS I ENCOUNTER FREQUENTLY

### ISSUE THREAD

**Issue by SirSandman-git** [OpenShot/openshot-qt#3894]
**Describe the bug:**
1. project not playing sound until headphones are unplugged and plugged back in. Once plugged back in, the video lags heavily.

2. not happening anymore on my computor, but video simply not uploading to the video file due to "raw frame".

3. Not sure if this was intended or not, but titles get cut off if they are too long. Not just letters, the entire image just gets cut off once it passes the screen.

4. Sometimes, it forces me to do the "select multiple" function, which prevents me from cutting and dragging clips.

5. clips with effects applied lag a lot.

____________
the only ones that are able to be reproduced are the title and effect ones. For the title, just type a bunch of letters into a title. For the effect one, put more than one effect on a clip and it should lag

**Expected behavior:**
All of these I was expecting to not happen

**System Details:**
- OpenShot Version 2.4.3 (or whatever the most recent version is)
- windows 10, ASUS.

**Log Files:**
no crashes recently

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by Innitinnuit** [comment]
In Openshot 2.5.1 that came out earlier this year, there is a new feature for Hardware acceleration. That might help you with number 5.

I've personally never experienced any of the bugs you mention and don't think they are endemic to the openshot community at large, which means there would need to be logs for the openshot team to be able to offer help.
