### ISSUE TITLE
[Previewer No Audio] .mp4

### ISSUE THREAD

**Issue by Blazaddo** [OpenShot/openshot-qt#3896]
**Describe the bug:**
I important a .mp4 file to the editor, and place it on the track, the video works but the audio does not. If I try to split the audio it shows no audio, I can confirm this video has audio in listening to it through Windows Media player. I have tried going to the properties of the clip and turning the audio on, and there is still nothing. I believe the problem is in a complete loss of audio from importing as the split audio slip shows no action what so ever.

**Steps to reproduce the behavior:**
1. Import a .mp4 file
2. It doesn't have audio.

**Expected behavior:**
I expected the clip to have both video and audio.

**System Details:**
- OpenShot Version 2.5.1
- Operating System / Distro: Windows 10

**Comment by JacksonRG** [comment]
I'm sorry that this wasn't responded to.

If you're still experiencing this bug in the daily build, I'd be happy to help fix it.
