### ISSUE TITLE
Animated title does not like newline character

### ISSUE THREAD

**Issue by jarlarntzen** [OpenShot/openshot-qt#39]
Seems like filling in a newline character isn't well received by the python script.
I tried entering 

"Title with
new line"
..and got the following.

```
blender_treeview:INFO QThread Render Method Invoked
blender_treeview:INFO Blender command: blender -b '/usr/lib/python3/dist-packages/openshot_qt/blender/blend/glare.blend' -P '/home/jarl/.openshot_qt/blender/f5775184-bb10-11e5-80e8-02421e0a6e5a/glare.py'
  File "/home/jarl/.openshot_qt/blender/f5775184-bb10-11e5-80e8-02421e0a6e5a/glare.py", line 91
    params['title'] = r'Title with
                                 ^
SyntaxError: EOL while scanning string literal
blender_treeview:INFO Blender render thread finished
blender_treeview:INFO onRenableInterface
blender_treeview:INFO onBlenderErrorMessage

```
Seems like this applies to every animated effect with a multiline text editor.

**Comment by asilnevs** [comment]
This was possible with the old version of Openshot .
I checked it with version 2.0 but the trick does not work anymore .
http://openshotusers.com/forum/viewtopic.php?f=11&t=1382&p=6373&hilit=more+lines+in+title#p6373

**Comment by jarlarntzen** [comment]
On OSX, it works the same way. At least OpenShot allowed me to go on here.

**Comment by jonoomph** [comment]
Yeah, I battled with this a bit before moving on. The newline char was never making it to Blender. I'll take another look.

**Comment by jonoomph** [comment]
Okay, figured it out. =) Animated titles have multi-line support now. Just hit enter. Also, I fixed some unicode issues also, so it also supports unicode... although not all Blender fonts support all unicode characters. I might eventually try and add the Ubuntu-medium font to all Blender animations, which I believe supports all characters.

**Comment by SvaSanRA** [comment]
Hi, Jonatan.
  How I can add new unucode (cyrilic) fonts from system in Animated title?  If possibly, are you planing to realize function loading system fonts or add manually it in new version of OpenShot? 
Thank you.
