### ISSUE TITLE
OpenShot fails to start on Windows 10 and no exception is shown

### ISSUE THREAD

**Issue by vincentbitter** [OpenShot/openshot-qt#3900]
**Describe the bug:**
When I try to start OpenShot Video 2.5.1 on Windows 10 Pro (10.0.19042 Build 19042), OpenShot Video doesn't appear. This did work one week ago on the same system. Probably I changed something in the meanwhile on my system like Windows updates, but I have no clue what is causing this issue.

**Steps to reproduce the behavior:**
I tried several things:
* Double click the openshot-qt.exe file
* Double click on .ops file
* Run openshot-qt as Administrator
* Remove C:\Users\myUser\.openshot_qt folder and run openshot-qt.exe
* Run openshot-qt.exe from command line
* Switch GPU via 'Graphical settings' and double click openshot-qt.exe

**Expected behavior:**
The OpenShot Video interface is shown or an error message to explain what went wrong.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 2.5.1
- Operating System / Distro: Windows 10.0.19042 Build 19042
- NVIDIA GeForce GTX 960M or Intel HD Graphics 530

**Log Files:**
```
         app:INFO ------------------------------------------------
         app:INFO             Sun Dec  6 14:18:31 2020            
         app:INFO               Starting new session              
         app:INFO ------------------------------------------------
         app:INFO             OpenShot (version 2.5.1)            
         app:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.5.1
         app:INFO libopenshot version: 0.2.5
         app:INFO platform: Windows-10-10.0.19041
         app:INFO processor: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
         app:INFO machine: AMD64
         app:INFO python version: 3.7.4
         app:INFO qt5 version: 5.12.4
         app:INFO pyqt5 version: 5.12.3
    language:INFO Qt Detected Languages: ['en-US']
    language:INFO LANG Environment Variable: 
    language:INFO LOCALE Environment Variable: 
    language:INFO OpenShot Preference Language: Default
project_data:INFO Setting default profile to HD 1080p 24 fps
```

```
------------------------------------------
libopenshot logging: Mon Nov 30 16:24:40 2020
------------------------------------------
```

**Exception / Stacktrace:**
No exception is shown, not even in the log file.

**Additional info:**
Tried this also with the nightly build and by changing the 'Debug Mode (Verbose)' setting to 'true' in the settings file, but this resulted in the same behavior and output.

**Comment by vincentbitter** [comment]
After a restart of my computer, the application did run again. Still strange no error was logged or shown, so worth looking into.

**Comment by USATechDude** [comment]
If the issue happens again, try running the command-line interface with the debug option.

`C:\Program Files\OpenShot Video Editor>openshot-qt-cli.exe --debug`

This displays debug information in the command console and might tell you where the program is halting.
