### ISSUE TITLE
No audio when previewing video clip

### ISSUE THREAD

**Issue by mkov608** [OpenShot/openshot-qt#3902]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Windows-10-10.0.17763
- Processor: Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-6124-7ba7d920-2cb4eeff-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/9038qx6p8zb958jah23pj5zs1vbpt69u/openshot-qt.zip) (17 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/9038qx6p8zb958jah23pj5zs1vbpt69u/libopenshot.zip) (3 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by Innitinnuit** [comment]
You would need to fill in the required information before someone could help you with this.

**Comment by mkov608** [comment]
I did.  What required information are you referring to?
 
Vr
Mark
 
-----Original Message-----

**Comment by mkov608** [comment]
Steps to reproduce the behavior:

Import a clip.
Drag it to the track pane
Click on play:  Video plays, but there is no audio

**Comment by USATechDude** [comment]
What happens when you plug in headphones?  Does any sound play while OpenShot is running?

**Comment by mkov608** [comment]
No sound from headphones; yes, laptop system sounds work fine while OpenShot is running.

**Comment by mkov608** [comment]
Preview sound was working previously; suddenly stopped working.

**Comment by USATechDude** [comment]
Your Windows operating system is behind a few versions.  The current version is 10.0.19042 and your log shows that you are running 10.0.17763.  I recommend that you update to Windows 10 20H2 (October 2020) and install the November 2020 Cumulative Update and Cumulative Update Preview.  

I also suggest downloading a free driver update tool to check all of your system device drivers. I thought that I had all of my device drivers up to date and I was totally surprised when the driver update tool found 27 updates for my system!

Are the properties for your audio clip correct in OpenShot?  I wonder if OpenShot doesn't properly recognize the clip and sets the properties to the wrong format.  Just in case it is too soft for OpenShot's Preview player, have you tried adjusting the volume level to 200% or even higher?

**Comment by mkov608** [comment]
All Window's updates have been installed & laptop rebooted.  all device drivers are up to date and they are working properly.  

OpenShot used to recognize the clips from my GoPro8 camera with no issues.  adjusting the volume didn't help.

**Comment by USATechDude** [comment]
> OpenShot used to recognize the clips from my GoPro8 camera with no issues.

Does this mean that, after updating the OS and device drivers, OpenShot no longer recognizes your GoPro 8 clips, or am I misunderstanding your statement? I'd hate to think that you lost ground by updating your other software.
What happens if you [export a section](https://www.reddit.com/r/OpenShot/comments/g32m05/exporting_sections_and_frame_numbers/) of your project then play it outside of OpenShot Video Player?

**Comment by mkov608** [comment]
Correction:  OpenShot used to recognize the audio portion of my GoPro 8 clips; then suddenly, after working on a new project, the was no audio; it's almost as if there was a mute button depressed. The audio is fine when I play the clip with VLC media player.  If I export the clip from OpenShot there is no audio.

**Comment by USATechDude** [comment]
I don't understand why OpenShot is not importing your audio.  I think we need more debug information.  Would you launch OpenShot from the Command Prompt using the debug parameter, please? 

I suggest that you first remove the `openshot-qt.log` and `libopenshot.log` files from `C:\Users\(USERNAME)\.openshot_qt`.  Open a Command Prompt and type the following command, then press Enter.  

`C:\Program Files\OpenShot Video Editor>` **`openshot-qt-cli.exe --debug`**

A lot of information will scroll up the screen as OpenShot loads, and as you use the program.  At this point, recreate the issue.  Import your clip, add it to the timeline, then press Play under the Preview window.  Once the playback stops, close OpenShot, then review the information in your command prompt.

You can use your mouse to highlight everything in the Command Prompt, then copy the selected text to the clipboard.  Now you can open a text editor and paste the screen dump into a document.  I want to review those documents.  I would appreciate your help if you would upload the screen dump, the freshly created `openshot-qt.log` and `libopenshot.log` files, and the `openshot.settings` file to this thread.

**Comment by mkov608** [comment]
The files you requested are attached.
[OpenShot Debug.txt](https://github.com/OpenShot/openshot-qt/files/5681648/OpenShot.Debug.txt)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/5681650/openshot-qt.log)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/5681651/libopenshot.log)

I noticed in the debug file text a comment:  "Using non standard frame rate 59/1, but the settings I'm using are identical to that on my Windows 7 laptop where everything is working properly.

**Comment by USATechDude** [comment]
@mkov608 
>I noticed in the debug file text a comment: "Using non standard frame rate 59/1, but the settings I'm using are identical to that on my Windows 7 laptop where everything is working properly.

The lines in the text file are:
**[mov,mp4,m4a,3gp,3g2,mj2 @ 0000000017f88140] Using non-standard frame rate 59/1**
This is an FFmpeg message that basically states that your video was recorded using a Variable Bit Rate (VBR).  OpenShot (in fact, most NLE's) prefer working with Constant Bit Rate (CBR) clips.

According to your `openshot-qt.log`, the files you are importing (GH010122.MP4 and GH010123.MP4) are 1080p 59.94 fps VBR 48kHz videos.  The log also shows that your default profile is 720p 30 fps, but it does not show your chosen audio sample rate.  If you are using the default settings, the default audio sample rate is 44100.  Open the **Preferences** window and click the **Preview** tab.  Make sure the **Default Audio Sample Rate** is 48000.  I also suggest that you click on the Cache tab and change the Cache Limit (MB) value from 250 to 2048 for a little smoother editing process.

I can see where you dropped GH010122.MP4 on the timeline, played the clip from frame 1 through frame 81 (2.7 seconds), then closed OpenShot. However, there aren't any error or warning messages in the logs regarding sound or playback issues.  Would you mind repeating your process to test the audio, this time with Verbose Mode logging enabled?  You can enable Verbose Mode logging by opening the **Preferences** window, selecting the **Debug** tab, then checking the box next to **Debug Mode (Verbose)**.  When you playback your clip to test the audio, please keep the playback very short because verbose mode will fill the logs with information for every processed frame.  The logs will easily grow to several megabytes if you playback more than a couple of seconds of your clip.  After you complete the process, remember to turn off the Verbose Mode debugging.

I'm sorry to keep asking for more information, but my goal is to try to find out why your audio playback is not working.  I appreciate your help with all of this.

**Comment by mkov608** [comment]
Thank you too.  I've made the changes you suggested to the audio sample rate and the cache limit ... no change.  New debug file is attached.

[OpenShot Debug 2.txt](https://github.com/OpenShot/openshot-qt/files/5682420/OpenShot.Debug.2.txt)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/5682421/libopenshot.log)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/5682423/libopenshot.log)
[Uploading openshot-qt.log…]()

**Comment by USATechDude** [comment]
@mkov608 
Hi!  Thanks for uploading your logs.  Would you upload `openshot-qt.log` again, please?  In your last post, the link is a loop back to this page instead of the log file.

**Comment by mkov608** [comment]
Try this.

[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/5682483/openshot-qt.log)

**Comment by USATechDude** [comment]
@mkov608 
OK, over 86,000 lines of debug messages is a lot of tiny, tiny print.  OpenShot is reading your clips and processing both the audio and video in the MP4's.  This means that there is some disconnect between OpenShot and the Windows audio device.  Check the Playback Audio Device on the Preview tab of the Preferences window in OpenShot.  Make sure it is set to either Default or Windows Audio.  Why is it that OpenShot often has a hard time playing well with Windows 10 laptops?

I did see in the logs that you updated Windows 10, but the version shows as 10.0.18362. Sometimes Windows Update doesn't register the 20H2 update.  You can force the update by downloading the Update Assistant at the following link:
https://www.microsoft.com/en-us/software-download/windows10
That should take you up to version 10.0.19041, then the November 2020 Cumulative Update and the November 2020 Cumulative Update Preview can be installed through Windows Update.

OpenShot captures the default audio device determined by Windows.  You can narrow down the devices that Windows uses in the Sound Control Panel.  Launch the Control Panel (not Settings), then click the Hardware and Sound link.  Click the Sound link, then review the devices listed on the Playback tab in the window that appears.  If multiple devices are active, disable them until only the device connected to the speakers remains active.  After you disable any excess or duplicate devices, relaunch OpenShot and check the audio once again.  With all of the issues concerning OpenShot and sound that we see recently, I'm pretty sure that something changed in Windows, and we're having a tough time tracking it down.

**Comment by mkov608** [comment]
OpenShot no sound during preview solved, well almost.

I used the link you sent:  https://www.microsoft.com/en-us/software-download/windows10
to update Windows;  that took a while.

After the update I tried previewing a clip, with the same result ... no audio.  So, I clicked on Edit, Preferences, and then the preview tab.  Under Playback Audio Device, I selected Windows Audio; it was in Default.  Then I restarted OpenShot.  When I opened the audio the Playback Audio Device switched from Window Audio to Direct Sound.  I still didn't have any audio.  

Next I rebooted the computer again, and tried one more time ... Audio was back, so I stated to create a new debug file with the audio working.  Suddenly, the audio quit working again.  See debug file 3 attachment.  I'm not sure why the audio would play once and then quit after restarting OpenShot.  Weird!!!
[OpenShot Debug 3.txt](https://github.com/OpenShot/openshot-qt/files/5683726/OpenShot.Debug.3.txt)

**Comment by USATechDude** [comment]
@mkov608 That sounds like a power saving option.  Windows may be determining that the audio is no longer needed after the first playback so the driver is powered down.  After performing some research, I found a couple of suggestions that may help:

- Uninstall and reinstall the device driver in Device Manager.  Here's a link to solution provided by Microsoft: https://answers.microsoft.com/en-us/windows/forum/all/sound-not-working-until-reboot/3fb57f42-5b17-491b-8bdd-7eaa95ff2475
- Turn off Fast Startup in the Power Options Control Panel. Here's a link to a tutorial provided by Ten Forums: https://www.tenforums.com/tutorials/4189-turn-off-fast-startup-windows-10-a.html

Try the suggestions above then reboot your laptop.  Delete your `libopenshot.log` and `openshot-qt.log` files then open a Command Prompt and launch OpenShot with the --debug option:

`C:\Program Files\OpenShot Video Editor\openshot-qt-cli.exe --debug`

If your audio does not work, would you provide all three files again, please?

**Comment by mkov608** [comment]
I've uninstalled and reinstalled the audio device driver, turned off fast startup, and then rebooted the computer; I still don't have audio during preview.

[OpenShot Debug 4.txt](https://github.com/OpenShot/openshot-qt/files/5685015/OpenShot.Debug.4.txt)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/5685018/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/5685019/openshot-qt.log)


.  libopenshot.log and openshot-qtl.log files were deleted.  A new dubug file and log files are attached.

**Comment by mkov608** [comment]
Brother Tim suggested trying to run OpenShot in Windows 7 mode since OpenShot runs fine on my Windows 7 laptop.  So I tried running OpenShot in Windows 7 and Windows 8 compatibility mode ... no luck ... still no audio during preview.

**Comment by USATechDude** [comment]
@mkov608 Thank you for uploading your debug files.  The logs and the screen dump show that OpenShot is processing both audio and video, which is no change from your previous logs.  Expanding on Brother Tim's suggestion, I have two suggestions to see if something might work.

1. Launch OpenShot with the **Run as administrator** option.
2. Create a new account on your system.  Log in to Windows with the new account and launch OpenShot.

The above tests should determine whether the issue is profile specific or system-specific.

**Comment by mkov608** [comment]
I tried options 1 & 2.  Same result ... no audio during preview.

**Comment by mkov608** [comment]
Brother Tim wants to know what language the program is written in and if it's using Linux libraries.

**Comment by mkov608** [comment]
I also tried removing version 2.5.1 and installing version 2.4.4.  No luck ... still no audio.

**Comment by USATechDude** [comment]
From our web page:
>OpenShot is written in a few different programming languages. The interface is built with Python and PyQt5. Our video processing backend (libopenshot) is built in C++, and utilizes FFmpeg. Out interactive drag-n-drop timeline is built with HTML5, JavaScript, and AngularJS. 

The audio library is based on JUCE and is written in C++.  OpenShot was originally developed for Linux but the libraries are cross-platform.

**Comment by USATechDude** [comment]
Would you try the following, please?  Open the Sound Control Panel and select the Playback tab.  Launch OpenShot, import a clip, add it to the timeline, then press Play on the Preview window.  Switch back to the Sound Control Panel and look for the bouncing green bars to the devices' right.  If there are no bouncing bars, then OpenShot is not connecting with the audio playback device.

**Comment by mkov608** [comment]
There is no audio level indication.

**Comment by USATechDude** [comment]
> I've uninstalled and reinstalled the audio device driver, turned off fast startup, and then rebooted the computer; I still don't have audio during preview.

This is probably a needless question, but did you run the device driver updater tool after re-installing the audio device driver?  I realize that it sounds like I am grasping at straws here, but I'm just trying to satisfy the questions in my frazzled, tired mind.  :grin:

**Comment by mkov608** [comment]
Yes.

**Comment by USATechDude** [comment]
@mkov608 Would you be willing to join me on a Google Meet call so that we can try to work out a solution?  If so, please contact me by sending an E-mail message to support@openshot.org.  Just reference this issue number in the subject line of your message.

**Comment by mkov608** [comment]
Solved!  You have to select "sound", "speakers/headphones", "properties", "advanced tab", uncheck the "Enable audio enhancements" in the "Signal Enhancements" box.
![Sound Settings](https://user-images.githubusercontent.com/75637717/103030208-8a7e5980-4518-11eb-86ca-9a1133496bb7.jpg)
