### ISSUE TITLE
Permission Error

### ISSUE THREAD

**Issue by jhoppenrath** [OpenShot/openshot-qt#3907]
**Describe the bug**
I get a butt load of permission errors when I try to open Openshot from either the desktop icon or the .exe file in the program folder

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Windows-10 Pro
- Processor: Intel Core i7-6650U 2.20GHz
- Machine: i7
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-6134-141e1dad-2cb4eeff-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/vi98is233uflt4ax9n84pgtte76lvzs4/openshot-qt.zip) (4 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
![Open Shot Error](https://user-images.githubusercontent.com/75742440/101648525-237c8300-39f7-11eb-9bf0-2102fd300a76.jpg)

If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by USATechDude** [comment]
What happens if you run `openshot-qt.exe` as an Administrator?  The error occurs when you try to access a file from Python without having the necessary permissions.
If running OpenShot as an Administrator works, then you may have to reset the permissions on your **`C:\Users\jhopp\`** folder within Windows.
