### ISSUE TITLE
cannot find project contents after change and save if UNC path is used

### ISSUE THREAD

**Issue by solarmarkt** [OpenShot/openshot-qt#3912]
**Describe the bug**
- A new project is saved with content like images, music and so on.
- The project is reopened by clicking the .osp file.
- The project opens but is missing the links to the content files

**Steps to reproduce the behavior:**
1. see description of the bug
2. it is reproducable if the content files and the project file lies at a windows share location and the logged on user has access to this location via a full unc path e.g.: \\openshot.local\shares\data\marketing\tutorials\.....
3. if the user accesses this location NOT through the unc path BUT through a connected network share e.g.: F:\marketing\tutorials\.... than there is no problem
4. I guess the problem lies within the path name structure. If a unc path is used the string starts with a double backslash. If a network connected folder is used the string starts with a letter. I guess Open Shot has a problem saving the linkpath while using unc path names.

**Expected behavior**
It should be possible to access the project, change anything, save it and even while accessing the whole datastructure through full unc path, the project should be saved including all working links.

**System Details**
- OpenShot Version: 2.5.1
- libopenshot Version:  0.2.5
- Platform: Windows-10-10.0.17763
- Processor: Intel64 Family 6 Model 85 Stepping 7, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['de-DE', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-6134-141e1dad-2cb4eeff-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/wi4nup6doy2q154d4cyqsopuaw3wjbeu/openshot-qt.zip) (360 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/wi4nup6doy2q154d4cyqsopuaw3wjbeu/libopenshot.zip) (4 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by JacksonRG** [comment]
Thanks for the detail in this bug report! We did some work on the asset path code recently, and I'd love to know if you're still encountering this issue.

**Comment by DanPinGF** [comment]
Did you update to the latest OpenShot? If not, try and see if it'll make a difference.
