### ISSUE TITLE
Voiceover ability

### ISSUE THREAD

**Issue by andewyn** [OpenShot/openshot-qt#3918]
**Describe the new feature:**
I would love the ability to be able to do voiceovers within the application. I am able to this by using audacity and Openshot, but it would be nice to be able to use just the one application.

**Describe the solution you'd like:**
I'm not a developer, but just a simple button that give me the ability to do voiceovers in my video.

**Describe alternatives you have considered:**
I current use audacity and do a delicate dance to provide voiceovers.

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your request.

**Comment by moreaki** [comment]
Would this help? [https://www.youtube.com/watch?v=OoDmjrJgwq4](https://www.youtube.com/watch?v=OoDmjrJgwq4)

**Comment by andewyn** [comment]
> Would this help? https://www.youtube.com/watch?v=OoDmjrJgwq4

This says it is for Shotcut, not OpenShot. I'm not opposed to using a different application for editing. But this is what I was learning editing with.
