### ISSUE TITLE
Strange file appeared and disappeared in profile folder. Is it normal?

### ISSUE THREAD

**Issue by Innitinnuit** [OpenShot/openshot-qt#3923]
**Question:**
Strange file appeared and disappeared in profile folder

Hopefully what happened is normal and it's just my general ignorance regarding these things.

-----------------------------

I was in openshot_qt/profiles/ folder as I wanted to create a custom profile. This folder was blank, which is to be expected. I created a new text file and added the profile settings - I now know that I was supposed to paste an existing profile file from another folder and then edit that. I checked in openshot for the new profile which wasn't there, obviously. When I returned to the folder as well as the text file I created there was now another file.

This file couldn't be opened in a text editor even though it said it was a text file and I was unable to delete it. A few moments later the file had disappeared without my instruction.

I was just about to google the name of the file when it disappeared and so I don't know it and can only remember a few words. I saw the word 'Streaming' and at the end it said either 'Gotv' or 'Gootv' something similar to thaI'm a bit worried. Anyone know if this is supposed to happen in openshot?

**System Details:**
- OpenShot Version 2.5.1-dev-2
- Operating System ubuntu 20.04.01.lts

**Comment by Innitinnuit** [comment]
Thanks for letting me know whether this is a normal part of openshot or something sinister.

**Comment by ferdnyc** [comment]
@Innitinnuit All support here is provided on a volunteer basis by very few, very overwhelmed people. There is no promised timeframe for responding to issues.

Beyond that, and our report wasn't exactly specific. ("I was just about to google the name of the file when it disappeared and so I don't know it and can only remember a few words. I saw the word 'Streaming' and at the end it said either 'Gotv' or 'Gootv' something similar to thaI'm a bit worried.")

 I understand that was as specific as you're able to make it, but that doesn't really change the fact that I, at least, have no idea what file you're talking about.

If the file wasn't deletable, it was most likely in use at the time, and if it was automatically deleted after then it must have been a temporary file of some sort. I don't know of any OpenShot code that would create a temporary file in your user profiles dir (we are talking about <code>/home/<var>username</var>/.openshot_qt/profile/</code>, correct?), but OpenShot does create temporary files in other locations. Also, if you were editing a profile file in that directory with a text editor, most editors create temporary files in the same directory as any file they're editing. Perhaps that's what it was.

I certainly don't see any reason to think it's something sinister, what exactly are you worried about it having been?
