### ISSUE TITLE
Deselect Individual Files

### ISSUE THREAD

**Issue by Innitinnuit** [OpenShot/openshot-qt#3924]
**Describe the new feature:**
Often I can't use the mouse to 'Select All' because there are too many tracks. Even when I zoom out fully and even when I have closed the preview window to maximise the time line. After selecting all with CTRL + A we should be able to deselect individual files by holding CTRL and selecting the files I want to deselect.

**Describe alternatives you have considered:**
The workaround to this issue is so time consuming, we are talking in the region of 15 minutes for such a simple function.

**Comment by JacksonRG** [comment]
Happy to say that this has been fixed!
