### ISSUE TITLE
Delete Space!

### ISSUE THREAD

**Issue by Innitinnuit** [OpenShot/openshot-qt#3925]
**Describe the new feature:**
Let's say I have had to trim part of a clip in the middle of a project. Now I'm left with a gap between the end of that files and tghe start of the proceeding clips. It'd be amazing to be able to click anywhere there is a space and delete that space so that all the proceeding files snap to the end of the preceding clip.

**Describe alternatives you have considered:**
Selecting all the files and moving them to the left, except I can't because there's too many tracks. Even when I zoom out fully, remove the preview window so that the timeline takes up the whole window,

**Comment by moreaki** [comment]
I've just done this now clicking on the free space (make sure nothing else is selected (red border) and hitting "x" on the keyboard. Did I miss something?
