### ISSUE TITLE
Suggested improvements to OpenShot 2.5.1: non-linear time line, insert gap, keyboard control of transitions

### ISSUE THREAD

**Issue by OpenShooter** [OpenShot/openshot-qt#3926]
Suggestions for improvements to OpenShot 2.5.1 (Windows):

With the present version, synchronizing audio and video is quite laborious. Bugs in playback exacerbate this, but that's another issue. Here are some ideas:

1) Non-linear time line. At present, the time line is linear: t = ap +b, where t=time, p=position on timeline, b is set by the main slider, and a is controlled by the zoom slider/buttons. I propose that the center of the timeline remain linear, but left and right of the center by logarithmic, compressing the time for parts not being worked on.

2) Keyboard shortcut to select everything to the right of the time cursor and move it right (increasing time) a fixed amount (user-settable in preferences). The idea is to make it easy to insert video or image in the middle of the timeline. For example, if your timeline is now V1V2V3V4V5V6I1I2V7V8V9, V=video clip and I=image, and the time cursor is at the end of V3, the proposed shortcut would change the timeline to V1V2V3   V4V5V6I1I2V7V8V9, inserting a gap between V3 and V4.

3) Enable keyboard entry of transitions. For short clips, it's very difficult or impossible to create them, partly due to the bugs with freeze and fade.

**Comment by JacksonRG** [comment]
1: This would be a really interesting issue! I've never seen anything like that. But I imagine it looking like moving a magnifying glass over the timeline. I'll add it to future improvements.

2 and 3: Also adding these. They'd definitely speed up common tasks
