### ISSUE TITLE
Export freezes

### ISSUE THREAD

**Issue by djeezuss** [OpenShot/openshot-qt#393]
The export freezes when it exports over about 4 minutes of content.

![openshot export config](https://cloud.githubusercontent.com/assets/22917102/19913224/e9232cae-a076-11e6-8600-62aba8b2aa1b.png)

**Comment by DylanC** [comment]
@djeezuss - Does this issue exist in OpenShot v2.3.4? Please confirm.

**Comment by DylanC** [comment]
Closing due to lack of details or activity. Plenty of other export tickets to look at anyway. Thanks.
