### ISSUE TITLE
Audio and video mismatched after exporting the video, also 2 seconds repetition added in the starting of the video

### ISSUE THREAD

**Issue by pratapshiv1992** [OpenShot/openshot-qt#3939]

**Comment by USATechDude** [comment]
There isn't much to go on here, but I'm going to take a stab in the dark.  Did you use the Time feature to adjust the clip's playback speed or part of a clip on your timeline?  The Time function in OpenShot considers the entire clip that is being edited, not just the portion you want to use.  To work around this issue, you can export the part of the clip that you want the speed adjusted to a separate video file.  Create a new project and import only the clip to be adjusted.  Change the speed of that clip, then export it as another video file.  Import the recently adjusted clip to your original project and add it to the timeline.
