### ISSUE TITLE
Can't Open from OS X Dock

### ISSUE THREAD

**Issue by hdweiner** [OpenShot/openshot-qt#394]
Running 10.12.1, 32GB of RAM on Late 2013 iMac 27 in. Clicking on the dock icon starts the animation sequence, but the bounce continues without any appearance of the OpenShot UI. Can't enable verbose debugging.

libopenshot.log features nothing beyond the header:  "libopenshot logging: Thu Nov  3 15:22:00 2016"

Had to Force Quit the application.

[openshot-qt 2.log.zip](https://github.com/OpenShot/openshot-qt/files/570162/openshot-qt.2.log.zip)

**Comment by cristianosequeira** [comment]
Same problem here, but opening from Launchpad.

**Comment by jreynojustin** [comment]
Hi @hdweiner and @cristianosequeira,

I was able to re-create this issue as well. I'll talk with @jonoomph about it to see what we can do.

My error log is attached.

[openshot-qt.txt](https://github.com/OpenShot/openshot-qt/files/800724/openshot-qt.txt)

**Comment by jreynojustin** [comment]
We believe we have resolved the issue. I am no longer experiencing the problem. Please check the newest release in our daily build.
