### ISSUE TITLE
libssl missing during installation on CloudReady / Chromium OS

### ISSUE THREAD

**Issue by ludomx** [OpenShot/openshot-qt#3942]
I try to install on Linux from CloudRead / Chromium OS 85.4.0 (Home Build) stable-channel 64-bit, but I get an error;

> wget: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

**Comment by USATechDude** [comment]
Did you try using apt-get to install libssl?

`sudo apt-get install libssl1.1`

After libssl is installed, rerun the install command for OpenShot.

`bash <(wget -O - http://openshot.org/files/chromeos/install-stable.sh)`

The install script should start the install from the beginning but continue past the wget error that you received.

**Comment by ludomx** [comment]
I think I found the issue. I was in another session, and using Crostini rather than the Linux Terminal. All should be good. Thanks !
