### ISSUE TITLE
“OpenShot Video Editor” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by seyoon20087** [OpenShot/openshot-qt#3945]
I get this error when I try to open OpenShot video editor even in the latest version:
![image](https://user-images.githubusercontent.com/24852454/103456191-2426e180-4d37-11eb-808b-114654d971e6.png)
WHY DO I GET THIS? CAN YOU PLEASE FIX THIS? PLEASE ???

Operating system : macOS Big Sur 11.1 (20C69)
Model : iMac (21.5-inch, 2017)
Processor : 2.3 GHz Dual-Core Intel Core i5
Memory : 8 GB 2133 MHz DDR4
Graphics : Intel Iris Plus Graphics 640 1536 MB

**Comment by USATechDude** [comment]
From our [Common Issue Solutions](https://www.reddit.com/r/OpenShot/wiki/commonproblems#wiki_-why_cannot_apple_macos_open_openshot.3F) page on Reddit.

> In macOS, if you receive an error message that states:
> 
> "OpenShot Video Editor can’t be opened because Apple cannot check it for malicious software."
> "This software needs to be updated. Contact the developer for more information." ​
> 
> You can correct this issue. Apple macOS needs permission to run the file that you downloaded from the Internet. There are a couple of methods that may work. Please try the procedures below (in order) to see if one of them works for you.
> 
> 1. Go to System Preferences > Security & Privacy > General > Click the lock in the bottom left corner > Enter your password > Click Unlock > Click Open anyway near the bottom > Open.
> 2. Go to System Preferences > Security & Privacy > General. You might see one or more alerts near the bottom that say something like, "OpenShot is an application downloaded from the Internet. Do you still want to open it?" Click "OK" or "Yes" or whatever is the affirmative option on all of them. Also, ensure that you select the "App Store and identified developers" radio button on the same tab.

If the above suggestions do not work for you for some reason, you can download and install the [latest Daily Build](https://www.openshot.org/download/#daily) of OpenShot.  The latest Daily Builds are notarized per Apple's requirements for software running on macOS 10.15+.

**Comment by seyoon20087** [comment]
Thank you for your feedback, @USATechDude. I hope this issue will be corrected in a future release.
