### ISSUE TITLE
Player controls invisible on my monitor

### ISSUE THREAD

**Issue by mogplus88** [OpenShot/openshot-qt#3949]
On my monitor the play controls are a dark grey on a background that is slightly darker grey. I searched in vain for them when I first started using Openshot, and only discovered them by carefully reading the user guide, which referred to them often. I think it would be better if the controls were a bit more visible. I'm using the latest version of Linux Mint 20.

**Comment by ferdnyc** [comment]
@mogplus88 Hmm, it sounds like your system theme is providing "light" versions of standard icons. (Meant to stand out against the light backgrounds and controls provided by the theme.)

OpenShot uses the system theme icons if they're available, we don't have any control over how the icons look in those situations. The default icons we supply, which are used when there's no system theme available, are many things... but subtle is none of them:

![Screenshot from 2021-01-06 18-41-12](https://user-images.githubusercontent.com/538020/103833469-1501a580-504f-11eb-941e-77d5201a8e62.png)

As a workaround, you could go into the OpenShot preferences and change the theme from the default "Humanity: Dark" to either "Humanity" or "No theme", either of which will use a light window style that should be more compatible with your icon set. I personally don't think it looks very good, an it's not really a well-supported option, but it's there for those who need it.

**Comment by mogplus88** [comment]
Hi Frank,
    Well that worked, I can see the buttons now. 
    
    Before it looked like this.
    
    Now the buttons are much more visible. Thanks for the tip.
    
    
    On 7/1/21 10:45 am, Frank Dana wrote:
    
    
      
      @mogplus88
        Hmm, it sounds like your system theme is providing "light"
        versions of standard icons. (Meant to stand out against the
        light backgrounds and controls provided by the theme.)
      OpenShot uses the system theme icons if they're available, we
        don't have any control over how the icons look in those
        situations. The default icons we supply, which are used when
        there's no system theme available, are many things... but subtle
        is none of them:
      
      As a workaround, you could go into the OpenShot preferences and
        change the theme from the default "Humanity: Dark" to either
        "Humanity" or "No theme", either of which will use a light
        window style that should be more compatible with your icon set.
        I personally don't think it looks very good, an it's not really
        a well-supported option, but it's there for those who need it.
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/OpenShot/openshot-qt/issues/3949#issuecomment-755782468",
"url": "https://github.com/OpenShot/openshot-qt/issues/3949#issuecomment-755782468",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by JacksonRG** [comment]
Glad this was solved! Closing
