### ISSUE TITLE
RAM problem i know!!!, when playing the imagine it freezes, but it is better dans another version

### ISSUE THREAD

**Issue by telelauro** [OpenShot/openshot-qt#395]
![Uploading RAM cacthe problem.jpg…]()
![Uploading RAM cacthe problem.png…]()
when playing the imagine it freezes, I changed the cache properties and see that improvement. I have found that in the timeline, a blue line that resembles other porgramas appears and it seems that once the blue line extends and improves reproduction is perfect, but that line does not advance if there is a problem sola.Creo RAM. but my computer has 16MB of RAM, so it's not my computer may be the cause. I think the program does not manage well the RAM.

**Comment by explaner** [comment]
I am seeing the same with openshot-qt 2.1. It only plays for a few seconds then stops. If I pause it and wait a long time I can resume play for a few more seconds. I also have 16gb of RAM.

**Comment by DylanC** [comment]
Closing due to old version of OpenShot mentioned. Please log a new ticket if the issue exists in v2.3.4. Thanks.
