### ISSUE TITLE
Video glitches at a regular interval after exportation 

### ISSUE THREAD

**Issue by HarrisonBanjo** [OpenShot/openshot-qt#3950]
**Question:**
Here is a test video I created and exported:
`<iframe width="560" height="315" src="https://www.youtube.com/embed/eHeM1NTcVvE" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`
https://youtu.be/eHeM1NTcVvE
Notice about every time a train car passes, there is a small glitch. How can I fix this? 
Source video is 29.97 fps, and export is the same. 

**System Details:**

- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [Windows 10]

**Comment by RiedleroD** [comment]
do you mean the red light, or…?
because that doesn't look like a glitch to me.

**Comment by HarrisonBanjo** [comment]
Look closely at the moving train. Only objects that are moving fairly
quickly will have this problem. I used the same video in a different editor
and it had no glitching.

**Comment by RiedleroD** [comment]
oh you mean it's stuttering slightly, yes?

**Comment by HarrisonBanjo** [comment]
Yes, that’s the issue I’m having. Do you know what the problem is and how I
can fix it? I have already tried multiple different frame rates.

**Comment by RiedleroD** [comment]
uh no, sorry. Make sure your camera isn't the problem, but aside from that, I can't help you, sorry.
