### ISSUE TITLE
Failed to load project file : invalid load key, '\x00

### ISSUE THREAD

**Issue by niCO19120** [OpenShot/openshot-qt#3957]
**Describe the bug:**
Hello, 
I have a problem with my Open Shot project. After saving my project it's impossible to open it and the following message is appearing : 
_"Failed to load project file C:/Users/.../... Projet Film test.osp: invalid load key, '\x00"._

Can you help me to recover my project please ? I am joining the project in a compressed file

**System Details:**
- OpenShot Version 2.5.1
Windows 10

[TROMSO Projet Film test.zip](https://github.com/OpenShot/openshot-qt/files/5793182/TROMSO.Projet.Film.test.zip)

**Comment by USATechDude** [comment]
Try using one of the recovery files for your project.  they are located in the `C:\Users\(USERNAME)\.openshot_qt\recovery` folder.  Use the latest version of your project to see if you can recover your work.

**Comment by niCO19120** [comment]
Thank you for your response. Unfortunately I don't have the recovery folder. I have a backup folder but it is empty. What is the method to obtain the recovery folder and the metho to obtain regularly backup files during my sessions ?
,
I don't understand why my file is not opening. Is it possible to repear it in orner to fix the problem ?
