### ISSUE TITLE
crash at start with mono audio preview

### ISSUE THREAD

**Issue by llonacho** [OpenShot/openshot-qt#3958]
**Describe the bug**
no audio while playing preview. so i change the preview audio to mono, restart the program, play, and then it crashes, it closes without any popup

**Steps to reproduce the behavior:**
preferences, preview, audio channel, mono
close openshot, open openshot, put play preview
crashes

**Expected behavior**
to play the preview with audio of course

**System Details**
- OpenShot Version: 2.5.1
- libopenshot Version:  0.2.5
- Platform: Windows-10-10.0.19041
- Processor: AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Skipped this step

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/48pdof4qppths6kwznavlulwszp7jsjp/openshot-qt.zip) (6 KB)
- libopenshot.log: File too small or empty (not uploaded)

**debug mode**
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/5793666/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/5793667/openshot-qt.log)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)

**Comment by JacksonRG** [comment]
Hi, We just added some tweaks to the audio encoding, and I'd love to hear if you still experience this bug when using the latest [daily build](https://www.openshot.org/download/).

**Comment by llonacho** [comment]
hi, I downloaded the latest build and tried it again, now it is not crashing but I can only hear noise, not the sound. Also the preview is not fluid. Hope this help you, let me know if you something more.

**Comment by JacksonRG** [comment]
That's very interesting

**Comment by JacksonRG** [comment]
@llonacho As for the preview, I recommend upping the preview cache to around 2000 in the preferences. I'm looking into why the previews slowed down in the first place. But that has helped many people

**Comment by JacksonRG** [comment]
> but I can only hear noise

Can you only hear noise in the exported video?

**Comment by llonacho** [comment]
I increased the  cache and that worked fine, I did it before but when I installed the latest version the configuration was deleted...

yes, the noise is only in the preview when I use my logitech headphones (they have their own audio device), if I switch to the speakers the sound is ok.
The exported video is always ok.

**Comment by JacksonRG** [comment]
Do you plug in the headphones after starting openshot? I know there's a current issue being worked on related to picking up changes in audio device.

**Comment by llonacho** [comment]
the usb plug is always in, I never remove it.

**Comment by JacksonRG** [comment]
Thanks. Good to know
