### ISSUE TITLE
Keyframes on the first frame jitter before actually going to the correct values

### ISSUE THREAD

**Issue by Smiley-Riley** [OpenShot/openshot-qt#3965]
**Describe the bug**
When I try to add a keyframe to the first frame (e.g video comes in at 4:29) (I'll find this using ctrl back arrow) to set the values to something like scale x = 0.5  it'll say the keyframe is on the first frame, but when i play the video it has a little jitter as scale x goes from 0.51 at 4:29 to 0.5 at 4:30, At no point did have I set the keyframe to be 0.51 but it does for the first frame and I have no idea why

**System Details (please complete the following information):**
Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
Linux Ubuntu 19.04 OpenShot Version [e.g. 2.4.1]
2.5.1

**To Reproduce**
**Steps to reproduce the behavior:**
Add a video clip to timeline.
Slice off the beginning.
Change property of scale x on the first frame of the video

**Expected behavior**
There will be a little jitter as the scale changes from a different value that it should be to it's proper value from one hundredth of a second to the next

**Comment by JacksonRG** [comment]
Have you tested for this bug in the appimage of our most recent daily build?
