### ISSUE TITLE
win10 64 bits cx_Freeze: Python error in main script dev1 version

### ISSUE THREAD

**Issue by carlosnewmusic** [OpenShot/openshot-qt#397]
![sin titulo](https://cloud.githubusercontent.com/assets/19379457/20162546/17e7bea8-a6f6-11e6-9483-963383e4a087.jpg)

openshot v2.1.0-43-g3a6491c-49-589
classes zip http://www61.zippyshare.com/v/v8wHmmOP/file.html

**Comment by mixedbredie** [comment]
I get a similar issue running Openshot 2.1.0 on Windows 7 64bit.  Error appears on startup.  Starting Openshot again works.

![openshot_error](https://cloud.githubusercontent.com/assets/3995787/20195419/63e58734-a78e-11e6-94f5-7b6ed7a4137b.jpg)

**Comment by HSzilard** [comment]
Unfortunatelly, I got a similar error popup under Windows 10 Home 64bit, selected Language in the installer: Hungarian.

![Image of error](https://s11.postimg.org/t05z1suwz/error.png)

After closing it, the launcher.exe still running, but I can close it only in the Task Manager.
