### ISSUE TITLE
Nvidia hardware acs

### ISSUE THREAD

**Issue by Yrij-Zhavoronkov** [OpenShot/openshot-qt#3979]
Win 8.1. Geforce GTX 1050Ti. Openshot 2.5x. FFmpeg + nvenc work correctly.
Openshot don't show nvenc codec, but after replace dlls from FFmpeg it appear:
![image](https://user-images.githubusercontent.com/12384490/105641996-019c6a00-5e98-11eb-96d6-430f7624d858.png)
but it take error:
![Снимок](https://user-images.githubusercontent.com/12384490/105642014-10831c80-5e98-11eb-8868-939bab193734.PNG)

WTF?

**Comment by USATechDude** [comment]
Hardware acceleration is still experimental and only available in Linux.
https://github.com/OpenShot/openshot-qt/issues/3448#issuecomment-623524015

**Comment by tadeaustria** [comment]
I would also love to use Nvidia **encoding** on Windows. As far as I have read through all of the related threads, it seems quite unclear to me, why that is not working on Windows. The underlying FFmpeg works quite well with hardware accelerated encoding.
