### ISSUE TITLE
Cannot load AppImage file

### ISSUE THREAD

**Issue by ov10fac** [OpenShot/openshot-qt#3984]
Trying to load openshot-qt appimage.  Starts then crashes as follows:
Copying icon thumbnails to cache
ICONFILE = /home/jwright/.cache/thumbnails/normal/c47ff4cb6c9104c975ef16af289416ce.png
Loaded modules from: /tmp/.mount_ABRQ5F/usr/bin
INFO app: ------------------------------------------------
INFO app:             Tue Jan 26 09:35:52 2021            
INFO app:               Starting new session              
Aborted (core dumped)

Running Ubuntu 20.10 with all updates
Here's the log file

09:35:52 INFO app: ------------------------------------------------
09:35:52 INFO app:             Tue Jan 26 09:35:52 2021            
09:35:52 INFO app:               Starting new session

**Comment by MakiWolf** [comment]
Duplicate of [https://github.com/OpenShot/openshot-qt/issues/3859](https://github.com/OpenShot/openshot-qt/issues/3859)
