### ISSUE TITLE
Building Openshot for RPi 4B

### ISSUE THREAD

**Issue by Pythonic456** [OpenShot/openshot-qt#3991]
**Question:**
How do I compile OpenShot for RPi 4B on the 32-bit Raspbian OS?

**System Details:**
- Operating System / Distro: Raspberry Pi OS 32-bit

I have been trying to build the latest stable version of Openshot for RPi 4B. And have been struggling.
Thank you :+1:

**Comment by Pythonic456** [comment]
This is still relevant.

**Comment by JacksonRG** [comment]
Hi, sorry this was missed when you posted. 

Where in these [instructions](https://github.com/OpenShot/libopenshot/wiki/Linux-Build-Instructions) do you have an issue?

**Comment by Pythonic456** [comment]
Hi. It seems to be the Openshot Audio Library. I cannot remember exactly, and I am unable to access my Raspberry Pi right now. I will follow the instructions tomorrow and tell you where it fails to build. If you have a Raspberry Pi 4 handy, could you try yourself too? And a small update to my first comment: It doesn't have to be 32-bit anymore, I can run 32-bit and 64-bit ARM now.

Thanks!
