### ISSUE TITLE
dissolving text will not render past frame 13

### ISSUE THREAD

**Issue by AndrewB4** [OpenShot/openshot-qt#3997]
dissolving text will not render past frame 13. Which version of blender should I use with openshot 2.5.1 for this feature to function properly? I have tried the latest version of blender 2.91.2 and the feature does not work at all, just get error message to use blender version higher than 2.80 (which i am). Have tried using some older versions of blender 2.8, 2.82, 2.83 but although the error message no longer comes up i cannot get the text to render past frame 13 on any of the versions i have tried.

Feature: animated titles - dissolving text
**System Details:**
- OpenShot Version 2.5.1
- Operating System Windows 10

**Comment by AndrewB4** [comment]
got it to work by downloading today's daily build, thanks Tech Dude!

**Comment by USATechDude** [comment]
Resolved in #3998.
