### ISSUE TITLE
dissolving text will not render past frame 13.

### ISSUE THREAD

**Issue by AndrewB4** [OpenShot/openshot-qt#3998]
dissolving text will not render past frame 13.  I have tried the latest version of blender 2.91.2 and the feature does not work at all, just get error message to use blender version higher than 2.80 (which i am). Have tried using some older versions of blender 2.8, 2.82, 2.83 but although the error message no longer comes up i cannot get the text to render past frame 13 on any of the versions i have tried.

Feature: animated titles - dissolving text
System Details:

OpenShot Version 2.5.1
Operating System Windows 10

**Comment by AndrewB4** [comment]
This is the error message when using blender version 2.91:

Blender, the free open source 3D content creation suite is required for this action (http://www.blender.org).

Please check the preferences in OpenShot and be sure the Blender executable is correct.  This setting should be the path of the 'blender' executable on your computer.  Also, please be sure that it is pointing to Blender version 2.80 or greater.

Blender Path:
C:/Program Files/Blender Foundation/Blender 2.91/blender.exe

Error Output:
No frame was found in the output from Blender

**Comment by USATechDude** [comment]
I meant to answer your question earlier than today.  The stable version of OpenShot does not work with versions of Blender later than 2.83.9.  The [Daily Builds](https://www.openshot.org/download/#daily) support Blender 2.9 and higher.

Whether you choose to update OpenShot or downgrade Blender, delete the `C:\Users\(USERNAME)\.openshot_qt` folder to reset OpenShot to default settings.  This folder contains many settings that may become corrupt.  OpenShot will recreate the folder when you relaunch the application.

**Comment by AndrewB4** [comment]
Ok thank you for the info. I assume that if I want to install the daily builds version of openshot I have to delete the other version first? If so just want to be sure I won't lose my saved projects. Thank you.Sent from my Galaxy
-------- Original message --------From: "[USA]TechDude" <notifications@github.com> Date: 2021-02-03  9:47 p.m.  (GMT-08:00) To: OpenShot/openshot-qt <openshot-qt@noreply.github.com> Cc: AndrewB4 <info@carpetcleaningnanaimo.ca>, Author <author@noreply.github.com> Subject: Re: [OpenShot/openshot-qt] dissolving text will not render past frame
  13. (#3998) 
I meant to answer your question earlier than today.  The stable version of OpenShot does not work with versions of Blender later than 2.83.9.  The Daily Builds support Blender 2.9 and higher.
Whether you choose to update OpenShot or downgrade Blender, delete the C:\Users\(USERNAME)\.openshot_qt folder to reset OpenShot to default settings.  This folder contains many settings that may become corrupt.  OpenShot will recreate the folder when you relaunch the application.

**Comment by AndrewB4** [comment]
I tried exactly what you suggested and used 2.83.9 but it still won't render past frame 13. Will have to try the daily build I think.Sent from my Galaxy
-------- Original message --------From: "[USA]TechDude" <notifications@github.com> Date: 2021-02-03  9:47 p.m.  (GMT-08:00) To: OpenShot/openshot-qt <openshot-qt@noreply.github.com> Cc: AndrewB4 <info@carpetcleaningnanaimo.ca>, Author <author@noreply.github.com> Subject: Re: [OpenShot/openshot-qt] dissolving text will not render past frame
  13. (#3998) 
I meant to answer your question earlier than today.  The stable version of OpenShot does not work with versions of Blender later than 2.83.9.  The Daily Builds support Blender 2.9 and higher.
Whether you choose to update OpenShot or downgrade Blender, delete the C:\Users\(USERNAME)\.openshot_qt folder to reset OpenShot to default settings.  This folder contains many settings that may become corrupt.  OpenShot will recreate the folder when you relaunch the application.

**Comment by AndrewB4** [comment]
Thank you for your assistance it is working in today's daily buildSent from my Galaxy
-------- Original message --------From: "[USA]TechDude" <notifications@github.com> Date: 2021-02-03  9:47 p.m.  (GMT-08:00) To: OpenShot/openshot-qt <openshot-qt@noreply.github.com> Cc: AndrewB4 <info@carpetcleaningnanaimo.ca>, Author <author@noreply.github.com> Subject: Re: [OpenShot/openshot-qt] dissolving text will not render past frame
  13. (#3998) 
I meant to answer your question earlier than today.  The stable version of OpenShot does not work with versions of Blender later than 2.83.9.  The Daily Builds support Blender 2.9 and higher.
Whether you choose to update OpenShot or downgrade Blender, delete the C:\Users\(USERNAME)\.openshot_qt folder to reset OpenShot to default settings.  This folder contains many settings that may become corrupt.  OpenShot will recreate the folder when you relaunch the application.

**Comment by USATechDude** [comment]
@AndrewB4 That's great news!  Is this issue closed now?

**Comment by AndrewB4** [comment]
It is for me now thank you but it only works in the daily builds. there is still a bug in the stable version as no matter which version of blender i tried I could not get it to work. Thanks again.Sent from my Galaxy
-------- Original message --------From: "[USA]TechDude" <notifications@github.com> Date: 2021-02-04  6:48 a.m.  (GMT-08:00) To: OpenShot/openshot-qt <openshot-qt@noreply.github.com> Cc: AndrewB4 <info@carpetcleaningnanaimo.ca>, Mention <mention@noreply.github.com> Subject: Re: [OpenShot/openshot-qt] dissolving text will not render past frame
  13. (#3998) 
@AndrewB4 That's great news!  Is this issue closed now?

**Comment by Slaymeister** [comment]
> I meant to answer your question earlier than today. The stable version of OpenShot does not work with versions of Blender later than 2.83.9. The [Daily Builds](https://www.openshot.org/download/#daily) support Blender 2.9 and higher.

I had the same problem and, like @AndrewB4 , changing to Blender build 2.83.9 (LTS) did not fix the problem.  Is there a recommended version of Blender and an Openshot stable build that work together?
