### ISSUE TITLE
where is the .openshot_qt folder?

### ISSUE THREAD

**Issue by aquazzz1** [OpenShot/openshot-qt#3999]
**Question:**
Where is the .openshot_qt folder? my Openshot won't open, it just doesn't do anything, and I have seen people saying to delete the .openshot_qt folder. I can't find it.

**System Details:**
- OpenShot Version 2.5.1
- Operating System Windows 10 20H2

**Comment by USATechDude** [comment]
In Windows, the folder is located in your User folder.  By default, that folder is `C:\Users\(USERNAME)\.openshot_qt`.

**Comment by aquazzz1** [comment]
ok thank, you.
