### ISSUE TITLE
Wish: Animated title should allow shorter duration

### ISSUE THREAD

**Issue by jarlarntzen** [OpenShot/openshot-qt#40]
250 frames may be far too long.
I suggest having 0.1, 0.25x, 0.5x, 0.75x as multipliers in addition to the 1x, 2x, 3x etc multipliers or alternatively allow inputting seconds and simply adjust the multiplier accordingly behind the scenes.

**Comment by ctsdownloads** [comment]
Thanks for the input, it's been added to the enhancement wishlist.
