### ISSUE TITLE
Can't adjust the start and end positions of a clip

### ISSUE THREAD

**Issue by JaapJoris** [OpenShot/openshot-qt#4000]
**Describe the bug:**

I cannot adjust the start and end positions of a clip by grabbing the edge of the clip and dragging.

**Steps to reproduce the behavior:**

1. Drag a clip onto the timeline
2. Use the scissor tool to cut it up
3. Try to change the start/end time by grabbing the edge of a clip and dragging it

**Expected behavior:**

The expected behavior is described in the [manual](https://cdn.openshot.org/static/files/user-guide/clips.html#cutting-slicing):

> OpenShot has many easy ways to adjust the start and end positions of a
> clip (otherwise known as cutting). The most common method is simply
> grabbing the left (or right) edge of the clip and dragging.

**System Details:**

- OpenShot Version: 2.5.1
- Operating System / Distro: Debian 11

**Screenshots:** (Optional)

Here is a screenshot of a clip in my timeline. As you can see, the handles at the left and right edges of the clip that were previously there have disappeared. Dragging the clip will drag the whole clip to a new location, but it is no longer possible to adjust the start and end time of the clip. This feature used to work in previous versions of OpenShot, although I don't know when it broke for me.

![gJ4A2](https://user-images.githubusercontent.com/9511578/106761078-c1c24900-6634-11eb-8ec3-09b34274cc9e.png)

**Comment by USATechDude** [comment]
I verified that this issue does exist in Debian 11.0 Alpha 3.  I downloaded the [latest Daily Build](https://www.openshot.org/download/#daily) AppImage and successfully adjusted the clip's duration by dragging the right edge on the timeline.

**Comment by jEsuSdA** [comment]
Duplicate of #4062
