### ISSUE TITLE
Tutorial for working with clips

### ISSUE THREAD

**Issue by David263** [OpenShot/openshot-qt#4001]
More efficient use of OpenShot can be achieved by exporting and importing clips. These are called XML Projects, not clips. You can create and export clips in one project, and import them wherever you wish in other projects.

Here is a detailed tutorial:

1. Import a large video file.

2. Select the start of a segment (clip) of the file that you would like to create. Right-click the blue oval slider handle and choose Slice All > Keep right side.

3. Select the end of the segment, right click handle and choose Slice All > Keep left side.

4. Left-align the segment clip by dragging to the left to the beginning of the timeline. The Position property (if you have properties displayed) should show 0 (meaning frame 1).

5. Save your project (always save your projects often in case OpenShot crashes silently, especially if you have placed many clips on the timeline).

6. Now we have a small clip created from the larger video. Wouldn't it be nice to save it as a named clip so it can be used in other projects? You will do this in the next step.

7. Click (in the Menu) File > Export project > Export XML (Final Cut Pro). This saves PROJECT.xml, a file that contains about 250 lines of text that describe the clip you just made.

8. You can now reuse your open project to create other clips in a similar way. Don't forget to export your clips with a different name each time!

9. Now, in a fresh OpenShot timeline, you can import each of your exported clips, like this:

10. First, make sure you import all the large video files that your clips come from. If you forget to do this, you will get an error message later. Each such error message will then allow you to import the corresponding large video file.

11. Click File > Import Project > Import XML (Final Cut Pro). Choose the XML clip you want to import. It will be imported to its own timeline, so you can then right-click the clip, select Copy > Clip, then right-click where you want your clip to go, selecting Paste.

David Spector
Springtime Software

**Comment by David263** [comment]
Thank you for asking my opinion. I think that this is important information, so it should be corrected (if needed) and added to whatever documentation is read by users.

Until clips can be copied to the clipboard and pasted into other projects, this information is basic to using OpenShot.

**Comment by David263** [comment]
I see no good reason why this issue should be closed. If the developer chooses to ignore it, that is fine. But don't close it just because you wish to ignore it. That isn't being open to feedback from your users. There are many times that I would like to be able to manipulate clips in various ways: copy them to other projects, change their starting or ending points. OpenShot needs to be made more flexible. And I see no documentation for the new and complex-looking feature that replaced the scaling of the timeline.

**Comment by JacksonRG** [comment]
Apologies. Our Github page is generally used for reporting bugs and suggesting features. We may not have responded because this appeared to be an informational post (which would be welcome on our [subreddit](https://www.reddit.com/r/OpenShot/) as this is certainly valuable information!

If I'm understanding correctly, the issue you're reporting is that the ability to share clips between projects isn't documented. And the feature you're requesting is a more direct way to do perform this task. Is that correct?

**Comment by David263** [comment]
I'm sorry that I posted in the wrong place. I'm not aware of any method to cut and paste OpenShot timeline clips from one project to another, documented or not. I used this Issue posting to describe a roundabout method I invented to almost achieve this goal.
