### ISSUE TITLE
Move playhead forward/backward 1 second

### ISSUE THREAD

**Issue by mikep345678** [OpenShot/openshot-qt#4005]
**Describe the new feature:**
I find myself frequently needing to move the playhead a second or two forward or backward. For example, I like to have a 2-second crossfade between clips. I move the playhead to where I want the crossfade to "end" on the latter clip, then have to rather manually look at the playhead time, subtract two seconds, then move the playhead back those two seconds, which is never exactly two seconds on first drop, so I have to futz with the playhead a few frames forward or back to get to the timestamp where I want to slice.

**Describe the solution you'd like:**
Possibility to assign a hotkey ("alt-left/rightarrow") to move playhead one second forward or backward.

**Describe alternatives you have considered:**
Only alternative is manually moving playhead.

**Comment by USATechDude** [comment]
In OpenShot v2.5.1, you can move the playhead one frame at a time by using the Left or Right arrow keys on your keyboard.  If you want to move a selected clip one frame at a time, you can use Shift+Arrow Keys to nudge the clip.

If you are in macOS, there is a bug that we are working to resolve. The arrow keys do not work to move the playhead one frame at a time.  You can remap the Next Frame and Previous Frame keyboard shortcuts in the Keyboard tab of the Preferences window.  On my 2019 MBP, I remapped the keys to "," and "." to move my playhead one frame at a time.

**Comment by mikep345678** [comment]
Yes, of course it is possible to move the playhead a frame at time with arrow keys-- I do this all the time. But, that means that moving forward or backward one second means hitting the arrow key 30 times (at 30 fps), or dragging the playhead then fine-tuning with the arrows.

A simple arrow-key modifier option (assignable shortcut) would be a huge efficiency improvement for a regular video edit I do weekly.

Please consider reopening this and engaging in further conversation before dismissing the idea out of hand.


Thank you,
Mike

**Comment by USATechDude** [comment]
I'm sorry, I wasn't trying to dismiss your request, or even close it for that fact.  I am reopening this because I clicked the wrong button.

**Comment by mikep345678** [comment]
OK, cool! No harm no foul! : )

Thank you!

**Comment by JacksonRG** [comment]
@mikep345678 I know I'm late to this issue. But the newest daily build does feature new zoom capabilities, so that you can zoom with your scroll wheel, or +/- keys. Along with this comes a change to show times at very high zoom. This will allow more carefully placing the playhead, and arranging clips down to the frame.

This is being actively worked on to fix a few bugs. But hopefully at stable release it will address your issue
