### ISSUE TITLE
Ability to select all content after playhead

### ISSUE THREAD

**Issue by mikep345678** [OpenShot/openshot-qt#4006]
**Describe the new feature:**
Add "select all following" (via hotkey or context menu) to select all clips and other content after the playhead.

**Describe the solution you'd like:**
Occasionally after completing the edit of a bunch of clips, I'm presented a new clip to insert or replace in the middle of the edit, which risks mis-aligning some of the later clips if they are accidentally not selected. Currently, there is no easy way to select and move "everything" after the current playhead position. Being able to select (via hotkey or context menu) all content after the playhead would make it much easier to insert or adjust a clip in the middle of the edit.

**Describe alternatives you have considered:**
Actually, there could/should be two options added: [select all following (not including current)] and [select all following (including current)]. This would allow the flexibility whether or not to include clips that are currently under the playhead in the selection.

**Comment by USATechDude** [comment]
You can use your mouse to click-and-drag a selection box around your clips on the timeline.  As you drag a box around the clips, they turn yellow.  Once you release the mouse button, the clips turn red to show that they are selected.  Once the clips are selected, you can click-and-drag them on the timeline.

**Comment by mikep345678** [comment]
Yes, understood; that's how I do it now. But for a longer edit with a large number of clips, or worse with a large number of tracks, it is difficult to ensure that all tracks are selected and stay selected. My feature request was born from more than once having accidentally ruined timing between "later" clips when moving them.

A corollary suggestion is to be able to "group" a bunch of clips, which would lock them together and allow them to be moved (or nudged!) "as one". Also tied to this would be the ability to zoom vertically (to show more or less tracks and make tracks larger and smaller)-- but I guess those are two additional feature requests, eh. : )

FWIW: I love OpenShot. I use it literally every week for a recurring edit (as a volunteer, for church), and deploy and support the package among school staff (professionally, in my day job as a school tech guy.). My FRs are not criticisms but rather are motivated by desire to make this awesome project even better!

Thank you,
Mike

**Comment by gbisaga** [comment]
I know this is old, but I agree this would be a very useful feature. I have many clips in a complex dance between timelines. I'm never confident that I have really selected them all. Also, having to zoom out and then back in again seems like an additional trouble spot. 

My very common (constant!) use case for this is when I'm doing a screencast and chopping out pieces - either because there's some stuff that is not worth spending the time on, or because I want to do jump cuts to eliminate filler words.
