### ISSUE TITLE
Browse button stays active while rendering video.

### ISSUE THREAD

**Issue by Bottersnike** [OpenShot/openshot-qt#401]
When rendering a video in windows 10 the "Browse" button next to the folder path on the render dialog stays enabled and clickable.

**Comment by DylanC** [comment]
@Bottersnike - Good idea thanks!

**Comment by ferdnyc** [comment]
This was fixed... well, at some point, not sure exactly when. The entire Export dialog should now be properly disabled except for the Cancel button.
