### ISSUE TITLE
Animated Titles issue

### ISSUE THREAD

**Issue by singularsyzygy** [OpenShot/openshot-qt#402]
Hi there,

I am having an issue where I get the "No frame was found in the output from Blender".  I have the correct path in.

What I have noticed, is that fonts, or animated titles with fonts do not work.  some work.  World map (and realistic), lens flare, magic wand, picture frames, snow and space movie intro (funny enough) works.

All the others give me the "No frame..." error.

Any help on this one would be appreciated.

**Comment by 07pepa** [comment]
maybe this will help https://github.com/OpenShot/openshot-qt/issues/379

**Comment by singularsyzygy** [comment]
Nope, that did not work.

**Comment by mixedbredie** [comment]
@singularsyzygy can you post the error messages you get? Can you run the animated title .blend and .py from the command line and post the output?  Any animated title that displays some text will fail with an error about ```AttributeError: 'TextCurve' object has no attribute 'align'```

```/path/to/blender -b /path/to/blend/file.blend -P /path/to/python/script.py```

**Comment by jonoomph** [comment]
Please test again with the latest daily build of OpenShot. I've merged in changes to the text alignment, and updated the minimum version compatibility to 2.78. I've tested all animation on Linux, Mac, and Windows with Blender 2.78 and everything works great.

Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot. _It might take a couple hours for the latest version to appear._

If you have other issues, please file additional bugs for each one. Thanks!
