### ISSUE TITLE
Imported videos are missing frames at the end

### ISSUE THREAD

**Issue by neekt** [OpenShot/openshot-qt#4023]
When importing a video into OpenShot, the last ~0.4 seconds worth of frames are *always* missing.

I have attached a short mp4 example of this to make it clear. It shows the video being played in SMPlayer, and then imported into OpenShot and played there. You can clearly see the last several frames (~0.4 seconds) have been cut off (it looks like it has been "frozen" at a prior frame). I show a side-by-side comparison of the video in SMPlayer and OpenShot at the end of the video to show that the end of the video is definitely missing.

The issue persists when the video is exported (which sounds a bit like [this old issue](https://github.com/OpenShot/openshot-qt/issues/1528)). The audio doesn't seem to be affected.

I don't use OpenShot often, but I have noticed this issue for about a year or more now.

https://user-images.githubusercontent.com/5132610/108950444-56f7b100-76ba-11eb-8a9e-ebb09a8df52d.mp4

**System Details:**
- OpenShot Version: tested in 2.5.1 (libopenshot 0.2.5) AppImage for Linux and the same version OpenShot-qt in the Linux Mint software repository.
- Operating System / Distro: Linux Mint 19.3

**Comment by JacksonRG** [comment]
Hi, Sorry I missed your issue at first. We've worked out some timing bugs recently. Have you downloaded the most recent daily build from https://www.openshot.org/download/ ?

**Comment by neekt** [comment]
I just tried this with the latest daily build and can confirm the bug still exists.

The number of frames dropped ranged from 10 to 12 across the three clips I tested it on.

Version: OpenShot-v2.6.1-dev-daily-9169-f2b89e32-2b8b05c7-x86_64.AppImage | Feb. 24, 2022, 2:32 p.m.
OS: Linux Mint 20.3 Cinnamon

**Comment by JacksonRG** [comment]
As I suggested in #4663, does changing the `end` property have any effect? Specifically adding 12/current_fps seconds?

**Comment by neekt** [comment]
I just tested this out on the latest daily build - OpenShot-v2.6.1-dev-daily-10349-5aa9487e-46255e46-x86_64.AppImage | Nov. 18, 2022, 5:52 p.m. - and was pleased to see that this issue seems to be fixed in this build.

The problem persists in the current stable release v2.6.1. Running Linux Mint 20.3 Cinnamon.

Ping #4663 #3635 #3649

Cheers
