### ISSUE TITLE
Openshot-qt is asking for version 2.6.0 of libopenshot, whereas I am using the source build of libopenshot(latest release is 2.5.2)

### ISSUE THREAD

**Issue by sanchayanghosh** [OpenShot/openshot-qt#4030]
I could not find this bug in searching through the issue tracker.
**Describe the bug:**
The issue is with the info object, where the info.minimum_openshot_version is set at 2.6.0. So, openshot-qt refuses to launch with python3 src/launch.py. 

**Steps to reproduce the behavior:**
1. Open terminal
2. cd to openshot-qt
3. Run python3 src/launch.py
4. You get a dialog box asking for version 2.6.0

**Expected behavior:**
Openshot starts

**Workaround**
In app.py, set the version returned by openshot manually to some low version string - eg. 1.5.0

**System Details:**
- OpenShot Version 2.5.2 (cloned from git)
- Operating System / Distro: Linux Mint Cinnamon

**Comment by sanchayanghosh** [comment]
Before proceeding with a possible remedy, I wanted to clarify if there may be a version problem with libopenshot itself, or is it the case where a release of libopenshot 2.6.0 is imminent.

However, feel free to correct me if I have made a mistake.

**Comment by Primorior** [comment]
Having the same issue on the newest 2.5.2 daily build

**Comment by sanchayanghosh** [comment]
Cloned the repository again with pyCharm (the openshot-qt). Set the PYTHONPATH to libopenshot.
It no more asks for version. 
@Primorior Please do the above. It should solve it for you.
