### ISSUE TITLE
I can not open the saved project

### ISSUE THREAD

**Issue by shigerusz** [OpenShot/openshot-qt#4031]
Hi,

I can not open the saved project. 
At opening the saved project. It always does not happen anything and it seems to die itself.

While it works just for new one,  arranging clips of pictures, videos, music, then rendering them.
But after saving the project and quit then I  open saved project again, it happens nothing,
**
My system Raspian OS, ARM cpu, Openshot 2.4.3

For reproduction the trouble, I removed  the .openshot_qt directory. It automatically re-created .openshot_qt directory again 
I used Openshot just a few steps for the purpose of just saving the project.

I attache these fresh log files.
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/6055878/openshot-qt.log)

Kind Regards,

**Comment by sanchayanghosh** [comment]
Is the project you worked on containing confidential information or media? I tried it with the latest version built from source, and my projects open fine. It would be great if you could upload a sample project that you are unable to open on your app.
