### ISSUE TITLE
Bug detected on Openshot

### ISSUE THREAD

**Issue by manoelaugustom** [OpenShot/openshot-qt#4034]
this bug has not already been reported: https://github.com/OpenShot/openshot-qt/issues -->

**Describe the bug:**
I installed Openshot in a G3 Dell computer with windows 10. When I import a video, the audio of the video and the computer´s audio turn off automatically. It´s impossible to hear what the people are speaking in the video. Is there any incompatibility between windows 10 and OpenShot?? Can person of support contact me to solve the problem? I live in Rio de janeiro, Brazil. Thanks, Antonieta

**Steps to reproduce the behavior:**
1. Open the software Openshot
2. Import a video file
2. Pull the video to start building the project
2. Click on '->" under the video´s window to test (see and hear)
3. the audio turn off imediatelly and we can´t hear any sound.
4. there is a bug that turn off the audio after importing the video.

**Expected behavior:**
It´s impossible to use Openshot without sound. I need a solution to the problem.

**System Details:**
- OpenShot Version [e.g. 2.5.1]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: Windows 10
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/6057874/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/6057875/openshot-qt.log)

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by USATechDude** [comment]
Have you tried the suggestions from the repository's wiki page?
https://github.com/OpenShot/openshot-qt/wiki/Windows-Audio-Issues
