### ISSUE TITLE
Openshot crashes with segfault 11 with normal, reproducible use

### ISSUE THREAD

**Issue by ghost** [OpenShot/openshot-qt#4039]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**
Add audio asset (can be video with embedded audio to any track). Change "preset" setting in preferences. Restart Openshot. Set the red cursor in timeline to the added assed. Click play in the timeline.
Works with Macos 10.14 (unable to check the daily build as it requires macos 10.15), Ubuntu 20.04 LTS (with 1.4.2 version from official repository, and "stable" release from openshot's ppa).

Moreover the log files very rapidly become larger than the limit of 500kB.
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/6064670/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/6064671/openshot-qt.log)

**Expected behavior**
The program should not crask

**System Details**
- OpenShot Version: 2.5.1
- libopenshot Version:  0.2.5
- Platform: Darwin-18.7.0-x86_64-i386-64bit
- Processor: i386
- Machine: x86_64
- Python version: 3.6.4
- Qt5 version: 5.5.1
- PyQt5 version: 5.5.1
- Qt Detected Languages: ['en-PL']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Not able to verify issue still exists in daily build
                
**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/3ftycww2i3urdhkesn3909s9a6ve7k89/openshot-qt.zip) (19 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/3ftycww2i3urdhkesn3909s9a6ve7k89/libopenshot.zip) (11 KB)

**Comment by mateusz-lacki** [comment]
To be more precise:  The change that crashes both versions ("Change "preset" setting in preferences") is changing audio from "stereo" to "mono" or vice versa.

**Comment by Das-Sams** [comment]
Same on linux
I have to export stereo with just one side working now - will fix it later in command line with ffmpeg.

blech./home/alex: uname -a
Linux blech 5.10.2-gentoo #11 SMP Wed Feb 10 22:47:12 CET 2021 x86_64 AMD Ryzen 7 PRO 4750G with Radeon Graphics AuthenticAMD GNU/Linux

Python 3.8.7
Qt 5.15.2
OpenShot Version: 2.5.1
libopenshot Version: 0.2.5
