### ISSUE TITLE
Languages mixed-up

### ISSUE THREAD

**Issue by JoannesPeeters** [OpenShot/openshot-qt#404]
Languages are mixed-up.

![image](https://cloud.githubusercontent.com/assets/23584956/20458072/8b31a0d0-ae9a-11e6-8d0c-b3f3e61b718c.png)

**Comment by flythefly** [comment]
exactly same problem here. not possible to set only english on non purely english windows

**Comment by qbart** [comment]
hello, similar for me, changed language to English but it shows language based on my region (Poland)

**Comment by DylanC** [comment]
Already mentioned in #331

**Comment by DylanC** [comment]
As confirmed in #331.

> Changing interface language to American English works fine in OpenShot-v2.4.1-34-g6a9257e-59-685.

Can someone confirm this here too?

**Comment by DylanC** [comment]
Confirmed as fixed in #331.
