### ISSUE TITLE
NVidia Quadro M1200 not detected for GPU Acceleration

### ISSUE THREAD

**Issue by corneil** [OpenShot/openshot-qt#4040]
I have a Lenovo P51 and tried with Hybrid and Discrete bios settings. But the export only listed the Intel QSV encoder.

**System Details**
- OpenShot Version: 2.5.1
- libopenshot Version:  0.2.5
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-GB', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Skipped this step

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/5tk3rknrbtpkvmyspjeyhjr7pwpcfkjs/openshot-qt.zip) (6 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by codecrunchers** [comment]
I believe GPU Acceleration is only available on Linux

**Comment by USATechDude** [comment]
Yes, hardware acceleration is still experimental and only available in Linux.
