### ISSUE TITLE
OpenShot cannot render animated titles

### ISSUE THREAD

**Issue by Pythonic456** [OpenShot/openshot-qt#4047]
OpenShot does not seem to be able to render any animated title frames.

**Steps to reproduce the behavior:**
1. Go to 'Title > Animated Title'.
2. Click on a title template.
3. See error.

**Expected behavior:**
I expected to be able to render some animated titles with OpenShot.

**System Details:**
- OpenShot Version 2.5.1, libopenshot 0.2.5
- Operating System / Distro: Windows 10 Pro
- Blender Version: 2.92.100.0

A windows opens and says this:
```Blender, the free open source 3D content creation suite is required for this action (http://www.blender.org).

Please check the preferences in OpenShot and be sure the Blender executable is correct.  This setting should be the path of the 'blender' executable on your computer.  Also, please be sure that it is pointing to Blender version 2.80 or greater.

Blender Path:
blender

Error Output:
No frame was found in the output from Blender
```

Help would be appreciated!

**Comment by Mikrotherion** [comment]
Can half confirm. Most animated titles work for me (so blender is there and does work), but for some (Dissolving Text and Exploding Text) I get the same error message.
For those that do work I'm not sure they work correctly. The World Map, for example, is very dark and oceans are black

System Details:

    OpenShot Version 2.5.1, libopenshot 0.2.5-r1
    Operating System / Distro: Gentoo 64bit
    Blender Version: 2.91.2

**Comment by ferdnyc** [comment]
@Pythonic456 

On Windows, you'll need to set the path to `blender.exe` in the Preferences. Go to Edit > Preferences, and on the first tab there's a setting "Blender command (path)". Click the Browse button at the end of that field and select the location of the Blender executable (probably `C:\Program Files\Blender Foundation\Blender 2.92\blender.exe`).

If you're using Blender installed from the Windows Store, those packages use a container format that's not compatible with OpenShot (it can't directly access the `blender.exe` file), so you'll have to download and install a full version from [blender.org](https://blender.org/).

That _should_ solve it, assuming there are no other issues using Blender 2.92 with OpenShot 2.5.1. I don't believe there are, but I haven't tested it personally. My only access to a Windows install is as a virtual machine under Linux, and Blender won't run like that because it requires GPU acceleration that isn't available in the VM.

**Comment by ferdnyc** [comment]
@Mikrotherion 

ISTR doing a fix for either just Dissolving Text, or all animated titles using the particle physics engine (which would also include Exploding Text, Magic Wand, and Snow) some time following the 2.5.1 release. I'll look around for details on that.

In the meantime, I looked at World Map — it _is_ working as intended, but I personally agree with you that it seems too dark. I've opened PR #4053 to add a "Sunlight intensity" adjustment that lets the user raise (or lower) the energy of the light source that provides the artificial sunlight for the render.

Here's a comparison between the default (`1.0`) and raising it to `3.0`:

![Screenshot from 2021-03-24 11-51-16](https://user-images.githubusercontent.com/538020/112341374-be902480-8c97-11eb-98a2-68bde7920d0a.png)

![Screenshot from 2021-03-24 11-51-35](https://user-images.githubusercontent.com/538020/112341393-c2bc4200-8c97-11eb-8591-27dface53ea4.png)

The range goes all the way down to `0` though I can't imagine why anyone would want that, and it tops out at `20.0` because any brighter than this and it'll look like crap:

![Screenshot from 2021-03-24 11-52-06](https://user-images.githubusercontent.com/538020/112341652-fc8d4880-8c97-11eb-88a3-4fbf072600bb.png)

Hopefully we can also pick a new, sensible default that's higher than `1.0`.

**Comment by Pythonic456** [comment]
@ferdnyc I uninstalled blender and downloaded the Windows ZIP from [Blender.ORG](https://blender.org/). But clicking Prefrences in OpenShot crashes with this error:
```> .\openshot-qt-cli.exe
Loaded modules from current directory: D:\*****\OpenShot Video Editor
         app:INFO ------------------------------------------------
         app:INFO             Wed Mar 31 12:35:09 2021
         app:INFO               Starting new session
         app:INFO ------------------------------------------------
         app:INFO             OpenShot (version 2.5.1)
         app:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.5.1
         app:INFO libopenshot version: 0.2.5
         app:INFO platform: Windows-10-10.0.19041
         app:INFO processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
         app:INFO machine: AMD64
         app:INFO python version: 3.7.4
         app:INFO qt5 version: 5.12.4
         app:INFO pyqt5 version: 5.12.3
    language:INFO Qt Detected Languages: ['en-US']
    language:INFO LANG Environment Variable:
    language:INFO LOCALE Environment Variable:
    language:INFO OpenShot Preference Language: Default
project_data:INFO Setting default profile to HD 720p 30 fps
         app:INFO Setting font to D:\*****\OpenShot Video Editor\images\fonts\Ubuntu-R.ttf
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
         app:INFO Setting custom dark theme
QMainWindow::addDockWidget: invalid 'area' argument
     ui_util:INFO Initializing UI for MainWindow
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
files_listview:INFO currentChanged
files_listview:INFO updateSelection
 files_model:INFO updating files model.
transition_model:INFO updating transitions model.
     version:INFO Found current version: {"openshot_version": "2.5.1"}
effects_model:INFO updating effects model.
 main_window:INFO foundCurrentVersion: Found the latest version: 2.5.1
properties_model:INFO updating clip properties model.
transition_model:INFO updating transitions model.
 files_model:INFO updating files model.
 main_window:INFO InitCacheSettings
 main_window:INFO cache-mode: CacheMemory
 main_window:INFO cache-limit-mb: 250
 main_window:INFO Creating CacheMemory object with 262144000 byte limit
preview_thread:INFO QThread Start Method Invoked
preview_thread:INFO initPlayer
 main_window:ERROR Unhandled crash detected... will attempt to recover backup project: C:\Users\******\.openshot_qt\backup.osp
 main_window:INFO updateStatusChanged
 main_window:INFO updateStatusChanged
         app:INFO Process command-line arguments: ['D:\\*****\\OpenShot Video Editor\\openshot-qt-cli.exe']
 main_window:INFO recover_backup
project_data:INFO Setting default profile to HD 720p 30 fps
preview_thread:INFO refreshFrame
preview_thread:INFO self.player.Position(): 1
video_widget:INFO Load: Set video widget display aspect ratio to: 1.7777777910232544
video_widget:INFO Set video widget pixel aspect ratio to: 1.0
 main_window:INFO updateStatusChanged
preview_thread:INFO onModeChanged
properties_model:INFO Update item:
properties_model:INFO updating clip properties model.
preview_thread:INFO refreshFrame
preview_thread:INFO self.player.Position(): 1
timeline_webview:INFO Qt Found!
timeline_webview:INFO $scope.Qt = true;
timeline_webview:INFO SetThumbAddress: http://127.0.0.1:49210/thumbnails/
    timeline:INFO Adjusting max size of preview image: PyQt5.QtCore.QSize(1290, 726)
preview_thread:INFO refreshFrame
preview_thread:INFO self.player.Position(): 1
timeline_webview:INFO UpdateLayerIndex
timeline_webview:INFO SortItems
timeline_webview:INFO UpdateLayerIndex
     ui_util:INFO Initializing UI for dlgPreferences
Hardware decoding device number: 0
Hardware decoding device number: 0
 preferences:WARNING CheckPixel failed testing hardware decoding in preferences (i.e. wrong color found): 3-0
Hardware decoding device number: 1
Hardware decoding device number: 1
 preferences:WARNING CheckPixel failed testing hardware decoding in preferences (i.e. wrong color found): 3-1
Hardware decoding device number: 0
Hardware decoding device number: 0
[h264 @ 00000000091ad640] Invalid setup for format dxva2_vld: does not match the type of the provided device context.
 preferences:WARNING CheckPixel failed testing hardware decoding in preferences (i.e. wrong color found): 4-0
Hardware decoding device number: 1
Hardware decoding device number: 1
[h264 @ 00000000091ac880] Invalid setup for format dxva2_vld: does not match the type of the provided device context.
 preferences:WARNING CheckPixel failed testing hardware decoding in preferences (i.e. wrong color found): 4-1
Hardware decoding device number: 0
[AVHWDeviceContext @ 00000000128ce980] Error setting child device handle: -16
>
```

Anyone know how to fix this?

**Comment by FireCulex** [comment]
Can confirm dissolving text causes the error. Blur works. At first blender will take 100% cpu and after a few minutes it stops, openshot takes a 100% cpu. There's no indication of whats happening.  Its just a rotating circle. At first I thought it was freezing but it takes ~5 minutes.

**Comment by MrHyplex9511** [comment]
wow

**Comment by wsuhoey** [comment]
I still get this error with Dissolving Text in 2024. OpenShot v3.1.1 and Blender v4.0.2.

**Comment by Colorjet3** [comment]
Hello @wsuhoey 
1.  What operating system/version are you running?
2.  What is the path to Blender in OpenShot (Edit | Preferences | General tab) set to?
3.  Does this happen with other animated templates as well?  If yes, which ones?

**Comment by Colorjet3** [comment]
**Update**

I confirmed this to be an issue in Windows 11 Pro and Blender 4.02.  Additional test results:
1.  Blender 4.0    = Same error message.
2.  Blender 3.6.5 = No issues.  Animated title gets created successfully
3.  Blender 3.6.2 = No issues.  Animated title gets created successfully.

In Windows environment you can install different versions of in parallel.  I now have both blender 3.65 and 4.02 installed.  My path in OpenShot is pointing to 3.6.5.  This will be the workaround for now until the lead developer has time to look at this issue and fix it.

**Comment by wsuhoey** [comment]
> Hello @wsuhoey
> 
> 1. What operating system/version are you running?
> 2. What is the path to Blender in OpenShot (Edit | Preferences | General tab) set to?
> 3. Does this happen with other animated templates as well?  If yes, which ones?

Hi @Colorjet3 

Windows 10 22H2
C:/Program Files/Blender Foundation/Blender 4.0/blender.exe
I haven't tested all of them yet, but the first 10 I think worked except Dissolving Text specifically.

**Comment by Colorjet3** [comment]
Thank you @wsuhoey for the information.  I went ahead and test all the animated titles and the "Dissolve Text" was the only one that generated that error message.  I did note that a few of them were taking a long time to render.  In a couple of them the CPU would spike but in others my CPU / GPU was barely taking a hit.

Were you able to at least install Blender 3.6.5, point OpenShot to it and get the "Dissolve Text" animated title working?  I just want to confirm this workaround as it can help others as well.

**Comment by wsuhoey** [comment]
> Thank you @wsuhoey for the information. I went ahead and test all the animated titles and the "Dissolve Text" was the only one that generated that error message. I did note that a few of them were taking a long time to render. In a couple of them the CPU would spike but in others my CPU / GPU was barely taking a hit.
> 
> Were you able to at least install Blender 3.6.5, point OpenShot to it and get the "Dissolve Text" animated title working? I just want to confirm this workaround as it can help others as well.

I can confirm that I do not get errors with Blender 3.6.9 on the "Dissolving Text" template. It is rendering now, currently on frame 140/256.
