### ISSUE TITLE
add support for armhf and arm64 (for raspberry pi and other arm SBCs)

### ISSUE THREAD

**Issue by Itai-Nelken** [OpenShot/openshot-qt#4048]
the version of openshot in the apt repos is very old and not a very good experience, could arm appimages be added please?
I am happy to help with testing and some coding as far as my very very bad skills allow.

thanks so much for making this great video editor, its one of my favorites!

**Comment by Pythonic456** [comment]
Yes. I think that this could possibly increase the OpenShot user base, with the advent of the RPi 4B, and the Pi 400, what with them being the most powerful Pis yet. I use a 4B as my main PC and it works amazingly.

**Comment by Pythonic456** [comment]
What would the technical challenges be? Probably old versions of libs needed, but could I help with this?
