### ISSUE TITLE
Hardware acceleration not working on Intel-AMD Switchable Graphics

### ISSUE THREAD

**Issue by oliverkardos** [OpenShot/openshot-qt#4050]
Hardware acceleration is not working on a Windows 10 system: Lenovo Ideapad 330s-15ikb 81F500GYHV series with Intel Core i5-8250u, Intel UHD 620 Graphics And AMD Radeon 540 Series Graphics. This is a switchable graphics system (powersaving and high performance options) , these are two seperate chips

Openshot is not detecting ANY of these despite both GPUs support hardware accel. Comptetitor Shotcut can use either of them just fine. Openshot cannot. Openshot can only use cpu render
![image](https://user-images.githubusercontent.com/79978011/111052517-b6481600-845b-11eb-9d62-24bba8f83869.png)

**Comment by oliverkardos** [comment]
details: the option is available at the export menu , but not in settings. Even if applied in export, it doesn't seem to work.

**Comment by USATechDude** [comment]
Hardware acceleration is still experimental in OpenShot and only available in Linux.  This issue is discussed in Issue #3414.
