### ISSUE TITLE
Unable to change clip lenght

### ISSUE THREAD

**Issue by jEsuSdA** [OpenShot/openshot-qt#4062]
I was not able to change clip lenght while drag the mouse coursor in clip borders.

**Detalles del sistema**
- OpenShot Version: 2.5.1
- libopenshot Version:  0.2.5
- Platform: Linux-5.4.0-17.1-liquorix-amd64-x86_64-with-debian-bullseye
- Processor: 
- Machine: x86_64
- Python version: 3.7.5
- Qt5 version: 5.11.3
- PyQt5 version: 5.11.3
- Qt Detected Languages: ['es-ES']
- LANG Environment Variable: es_ES.utf8
- LOCALE Environment Variable: 
- Daily Build: Not able to verify issue still exists in daily build

**Archivos de registro**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/zvbc3etav5n3pr3y20pgjwpv7mgtw502/openshot-qt.zip) (21 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Comment by JaapJoris** [comment]
Duplicate of #4000
