### ISSUE TITLE
when i try to export the video it stops at 63% then says not responding and openshot shuts down

### ISSUE THREAD

**Issue by audreane20** [OpenShot/openshot-qt#4067]
**Describe the bug**
A clear and concise description of the issue
when I try to export the video it stops at 63% then says not responding and openshot shuts down (closes the app)

**Steps to reproduce the behavior:**
1. get a video ready
2. try to export it
3. at 63% it will say not responding
4. The app will then shut down

**Expected behavior**
at 63% of the exportation of the video the app will shut down

**System Details**
- OpenShot Version: 2.5.1
- libopenshot Version:  0.2.5
- Platform: Windows-10-10.0.18362
- Processor: Intel64 Family 6 Model 69 Stepping 1, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-daily-7016-9efa3592-bd033247-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/30j0wxu2exkadsa06scow69fn34f6a4f/openshot-qt.zip) (90 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by WhymustIhaveaname** [comment]
I experienced this problem once. If 63% is exactly when you start using a new material, there may be some authority problem. Not only the authority should be correct; the owner also has to be the user using openshot.

**Comment by DanPinGF** [comment]
Did you try exporting the project in mono audio? The MSVCRT.DLL is so faulty you probably shouldn't export it that way.
