### ISSUE TITLE
OpenShot disables all audio on PC

### ISSUE THREAD

**Issue by tom-longhsaw** [OpenShot/openshot-qt#4069]
OpenShot was working fine until today.  Now whenever I play a clip inside OpenShot not only does the audio not play on the clip, it also disables the audio for all other applications on the PC!

1. Start a new project in OpenShot
2. Add a new video file to the project (I have tried this with MTS, MP4 etc.)
3. Drag the video file into a track
4. Press play (there is no audio playback and all audio on the rest of the PC is now disable.  The audio for other applications can be re-enable by muting and then re-enabling the speakers, but this does not fix the problem with OpenShot which will disable all audio again as soon as you press play)

This is a relatively new PC and OpenShot was working fine on it last week.  The only guess I have (and this might be a red herring) is that since my last use where OpenShot worked and now I have had to use Zoom for the first time on this PC.  I have previously experienced issues on another PC where Zoom made changes to the audio settings that prevented other devices from getting access to the speakers.

Other things I have tried:
 * I installed the latest daily build (no impact)
 * I tried manually choosing the audio device instead of using the "Default" (no impact)
 * I tried a complete reboot of the PC (no impact)

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev3
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Skipped this step

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/wkfi666ms9f2ofovoxnf9anufr9m52ee/openshot-qt.zip) (20 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/wkfi666ms9f2ofovoxnf9anufr9m52ee/libopenshot.zip) (1 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by tom-longhsaw** [comment]
With regard to the "stale" label.  I have tested this issue with build 2021-09-04 23:49 and the issue is still present.  When the OpenShot editor is started it disables the sound on my pc and the only way to restore sound in any application is to disable the speakers and then re-enable them.  This does not restore sound to "OpenShot" itself, if that application is used again it will disable sound again for all other applications including itself.

FYI The speakers are the built in "Realtek Audio", the driver is version 6.0.9147.1, which is identified as the latest available driver.

**Comment by tom-longhsaw** [comment]
I have downloaded the latest build and there is some improvement.  The audio is still not playing on clips added to a project, but the good news is the issue is now _isolated_ so the audio in other applications now continues to function correctly after OpenShot has exited.

**Comment by JacksonRG** [comment]
Good to hear, we've made some improvements to our sound device handling. Do you have any other audio devices to test this bug with? Like headphones or external speakers?

**Comment by tom-longhsaw** [comment]
Will give it a shot with some head phone, and also have a couple of 
speakers I can unplug.  Will let you know.

------ Original Message ------
From: "JacksonRG" ***@***.***>
To: "OpenShot/openshot-qt" ***@***.***>
Cc: "tom-longhsaw" ***@***.***>; "Author" 
***@***.***>
Sent: 01/04/2022 16:39:11
Subject: Re: [OpenShot/openshot-qt] OpenShot disables all audio on PC 
(#4069)


Good to hear, we've made some improvements to our sound device handling. 
Do you have any other audio devices to test this bug with? Like 
headphones or external speakers?

—
Reply to this email directly, view it on GitHub 
<https://url.emailprotection.link/?buEq4eyNl9NRYRhKUfm4VcEhLW9nyxLjG-p3Wi9CpaXxGUZoR4OlOnot1KnUa0XK2lQG6KmFPW97qLSf9Srm31abmeoiqD62-hGfjN0I6R27ccUZDvuE0CWrMwhXG2SkyEBa5Ns0259Xc9fWS-G_E0x9Eh3FKgcCMO6iF-y3T0zg~>, 
or unsubscribe 
<https://url.emailprotection.link/?b0uh7LQwcQV8AT1mgPOVDuEBBGEK5lZqVhiF16Ft4aWngMAWaoAg5NS2FIPmbupRPxtPHw0DtKUeQxoEq97rKaJbZiK50-2FuZ4sJ2dq7HpI_haBbR6TlWVMugQKFQc7i2YZB82YngOtvoUiTe2iiEOfDvanBVnIQzlXRJsR-40I~>.
You are receiving this because you authored the thread.Message ID: 
***@***.***>

**Comment by tom-longhsaw** [comment]
Interesting...

This time I created a new project and brought in an MP4 that has sound 
and just added it as a track and played it.  I got no sound on the 
playback.  However, when I then switched to YouTube the sound had also 
gone there and for every other playback (i.e. the same problem as I was 
seeing 12 months ago).  However, when I plug in headphones, then I can 
hear the sound from YouTube (and if I play the MP4 outside of OpenShot), 
but I cannot hear it in OpenShot.

Next experiment will be to start OpenShot with the headphones plugged in 
before I begin to see if it is the driver for the speakers that is 
taking the sound out...

------ Original Message ------
From: "JacksonRG" ***@***.***>
To: "OpenShot/openshot-qt" ***@***.***>
Cc: "tom-longhsaw" ***@***.***>; "Author" 
***@***.***>
Sent: 01/04/2022 16:39:11
Subject: Re: [OpenShot/openshot-qt] OpenShot disables all audio on PC 
(#4069)


Good to hear, we've made some improvements to our sound device handling. 
Do you have any other audio devices to test this bug with? Like 
headphones or external speakers?

—
Reply to this email directly, view it on GitHub 
<https://url.emailprotection.link/?buEq4eyNl9NRYRhKUfm4VcEhLW9nyxLjG-p3Wi9CpaXxGUZoR4OlOnot1KnUa0XK2lQG6KmFPW97qLSf9Srm31abmeoiqD62-hGfjN0I6R27ccUZDvuE0CWrMwhXG2SkyEBa5Ns0259Xc9fWS-G_E0x9Eh3FKgcCMO6iF-y3T0zg~>, 
or unsubscribe 
<https://url.emailprotection.link/?b0uh7LQwcQV8AT1mgPOVDuEBBGEK5lZqVhiF16Ft4aWngMAWaoAg5NS2FIPmbupRPxtPHw0DtKUeQxoEq97rKaJbZiK50-2FuZ4sJ2dq7HpI_haBbR6TlWVMugQKFQc7i2YZB82YngOtvoUiTe2iiEOfDvanBVnIQzlXRJsR-40I~>.
You are receiving this because you authored the thread.Message ID: 
***@***.***>

**Comment by tom-longhsaw** [comment]
More results...
starting OpenShot with the headphones plugged in did not make a 
difference.  I still did not get any sound in OpenShot.  However, with 
the headphones, the sound is not affected in other applications
when I unplugged the headphones it reset the sound so the speakers 
started working again with other applications (apart from OpenShot)

------ Original Message ------
From: "JacksonRG" ***@***.***>
To: "OpenShot/openshot-qt" ***@***.***>
Cc: "tom-longhsaw" ***@***.***>; "Author" 
***@***.***>
Sent: 01/04/2022 16:39:11
Subject: Re: [OpenShot/openshot-qt] OpenShot disables all audio on PC 
(#4069)


Good to hear, we've made some improvements to our sound device handling. 
Do you have any other audio devices to test this bug with? Like 
headphones or external speakers?

—
Reply to this email directly, view it on GitHub 
<https://url.emailprotection.link/?buEq4eyNl9NRYRhKUfm4VcEhLW9nyxLjG-p3Wi9CpaXxGUZoR4OlOnot1KnUa0XK2lQG6KmFPW97qLSf9Srm31abmeoiqD62-hGfjN0I6R27ccUZDvuE0CWrMwhXG2SkyEBa5Ns0259Xc9fWS-G_E0x9Eh3FKgcCMO6iF-y3T0zg~>, 
or unsubscribe 
<https://url.emailprotection.link/?b0uh7LQwcQV8AT1mgPOVDuEBBGEK5lZqVhiF16Ft4aWngMAWaoAg5NS2FIPmbupRPxtPHw0DtKUeQxoEq97rKaJbZiK50-2FuZ4sJ2dq7HpI_haBbR6TlWVMugQKFQc7i2YZB82YngOtvoUiTe2iiEOfDvanBVnIQzlXRJsR-40I~>.
You are receiving this because you authored the thread.Message ID: 
***@***.***>
