### ISSUE TITLE
Python plugin API for OpenShot a good method for persistent data?

### ISSUE THREAD

**Issue by expertmm** [OpenShot/openshot-qt#407]
(I had posted on the user forum and was directed here due to the nature of the question)

This may seem redundant at first since one can program plugins in Blender and can access openshotlib via Python, but I have pointed out some fine details and use cases of having this type of API that would open up whole new categories of plugins...

I would like to help OpenShot to be able to write plugins (and I would like to write plugins) such as frame-painting plugins; another category of plugins that generate or use motion estimation data (such as anti-shake or motion matching plugins--they could even both get the data from the same motion estimation plugin else show error on screen if motion estimation info is not available for the frame of the footage file); and possibly other categories of plugins which would also use persistent data in some way. Both categories of plugins would be highly dependent on footage staying the same, so py (or however programmed) plugins may need to be required to have a get_context_list function that could return ["footage","clip","track","master"] (but that would return only ["media"] in this case). There definitely would need to be a warning but not necessarily block the person if they want to risk frame painting on a clip such as after a color adjustment effect. There would also need to be a get_content_list function that would return something like ["video"] or ["audio"] or ["image"] or ["video","image"]. The py file should be able to get and set info somehow such as:
```
openshot.plugin_context.media.content_string #returning ["video"] or ["audio"] or ["image"]
openshot.plugin_context.media.path #returning full path of clip, such as to store motion estimation data to the same folder
#also store persistent data in memory (of arbitrary name and type) between frames:
if openshot.plugin_context.my_variable_1 is not None:
    openshot.plugin_context.my_variable_1 = QImage() #pretend I wrote something legit after the equal sign
#where plugin_context is the instance of the plugin as applied to a specific media object
#it may also need to get the frame number and rate or timecode (at least global time, but possibly also time relative to clip), such as for beat matching, or so it can have an option to reset a cumulative effect such as motion blur
```
Regarding uses of such an API not highly dependent on unchanging sources, but that might also require a python API or other API, named outputs and inputs (that can be piped together) would be great--such as a plugin that detects and outputs "bass" from audio track, then that (0 to 1) value can be used as an input for a brightness (or other) video plugin selectable from drop-down (possibly node interface if anyone wants to program that).

I recommend against writing a plugin API that requires binary plugins, since that is a big pain for developers (such as, if I go on another computer, I have to make sure my IDE is setup properly there and possibly deal with version issues related to Qt or other libraries). Also, I know that libopenshot is accessible from Python and that I would be able to write my own video editing program, but that is not really interesting to me. I'd rather stick with OpenShot since it already has a great interface). I don't currently know the coding of OpenShot in depth, nor future plans--so that's why I ask, is writing a Python API for OpenShot a good idea to accomplish these goals?

**Comment by expertmm** [comment]
My exact question: is this type of plugin possible with current code, or would someone have to write a python plugin API?

**Comment by DylanC** [comment]
@expertmm - I will check this with the team.

**Comment by peanutbutterandcrackers** [comment]
I don't know about all this but in his 'Happy New Year 2018' post (can be found at the bottom of the home page at openshot.org), Mr. Thomas talks about plans for writing an easy effects plugin framework. So, perhaps yes?

I think the best way to know for sure would be to write Mr. Thomas an email. The website has his email too. And when he's not too busy, he does indeed reply.

**Comment by peanutbutterandcrackers** [comment]
@expertmm - Also, since you too seem to be a well-wisher of OpenShot and also an expert coder (name reference pun!), could you perhaps consider helping out with the bug fixing or enhancing or anything that requires typing code into the terminal? Mr. Thomas is our only programmer at the moment and this is causing the project to not grow to it's full potential. I myself plan to be able to help soon, but it seems it's not going to be any sooner than a year or so. So, please do help the project, good sir.

Here's to hoping to see your pull request soon...

**Comment by peanutbutterandcrackers** [comment]
@expertmm - Thank you! That will be tremendous help! Please do squash the bugs! I hope to see your pull requests soon!!!

**Comment by peanutbutterandcrackers** [comment]
@DylanC - Look, The Avengers are assembling!  :)

**Comment by DylanC** [comment]
@peanutbutterandcrackers - Hopefully we can get together an all star team! :)

**Comment by peanutbutterandcrackers** [comment]
Yeah!!!

**Comment by peanutbutterandcrackers** [comment]
@expertmm - If this issue has been resolved, perhaps you would consider closing it? We have a LOT of issues now. And every single issue closed makes me feel like OpenShot is one step closer to being what it could be. :smile:

**Comment by DylanC** [comment]
@peanutbutterandcrackers - I think I will close this. We should have a Python API of some sort coming in 2018. @expertmm - Hope you don't mind but I believe this is in the pipeline anyway.

**Comment by expertmm** [comment]
Sure, I'll keep an eye on that.

**Comment by peanutbutterandcrackers** [comment]
In the meantime, there's also [this](https://openshot.org/files/libopenshot/) thing that you might be interested in. :)
