### ISSUE TITLE
Video output gets bloated file size

### ISSUE THREAD

**Issue by Rstation4** [OpenShot/openshot-qt#4077]
Linux Mint 20.1 Cinnamon
Cinnamon Version 4.8.6
Linux Kernel 5.4.0-70-generic
AMD Ryzen 3 3200G
RAM: 5.8 GiB

Openshot version:  2.5.1

I've had some projects with this version crash as well during the export process. I ended up changing the Hardware Decoder Mode since I kept getting crashes when the project was exporting around 70% and up. In one instance it froze the PC. Why are the videos getting heavily bloated as with one case it was 25.7 Mbs and ended up being  174 Mbs which is a huge difference.

My videos are recorded with OBS with the following settings in the picture. When i make videos I only use 2 tracks, the 1st track has the video and the second one has a music format added to it which are small and not flac or wav.
In that one case all I did was add a song (4.1 Mbs)and split the short video into 2 with the first part muted. 
When I export it I use medium quality to reduce the size.

![OpenShot](https://user-images.githubusercontent.com/73009731/113490467-f01aa400-947e-11eb-8379-cf5929a6daa1.png)

![OBS setting](https://user-images.githubusercontent.com/73009731/113490469-f446c180-947e-11eb-8335-6b801152232a.png)

Logs:
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/6253330/openshot-qt.log)

**Comment by DanPinGF** [comment]
I actually have been noticing this, too. Sometimes exporting a project with a small resolution can have a duration long enough to produce hundreds or thousands of megabytes in size. @speedytechdev, please reopen this issue and add a '🔥 hot' label to this. Kindly?

**Comment by DanPinGF** [comment]
And it also takes forever to export a lengthy project in addition to this (#1838). What must I do?

**Comment by DanPinGF** [comment]
@JacksonRG - This is a known issue that needs to be sorted. Kindly reopen this?
