### ISSUE TITLE
Cannot register into the forum

### ISSUE THREAD

**Issue by herrdeh** [OpenShot/openshot-qt#408]
I tried to register, guessed the captcha (took me some time) and got the message "a confirmation message was sent to you". After a day the message did not arrive, so I triggered "resend" - still nothing happened.
And - yes, I checked the SPAM folder.

**Comment by jonoomph** [comment]
Sorry about that. Please try again, and reopen if needed. I'm not the one that maintains the forum, but hopefully it was a temp problem.
