### ISSUE TITLE
tiny UI on 3840x2160 screen resolution and cannot adjust

### ISSUE THREAD

**Issue by fkam18** [OpenShot/openshot-qt#4083]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 2.5.1
- libopenshot Version:  0.2.5
- Platform: Linux-5.8.0-48-generic-x86_64-with-Ubuntu-20.04-focal
- Processor: x86_64
- Machine: x86_64
- Python version: 3.4.3
- Qt5 version: 5.2.1
- PyQt5 version: 5.2.1
- Qt Detected Languages: ['en-GB', 'en']
- LANG Environment Variable: en_GB.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-daily-7080-b232919f-ad144575-x86_64.AppImage

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/gucogbtb9qlyj7jrlhqufa9zris2qsrh/openshot-qt.zip) (185 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/gucogbtb9qlyj7jrlhqufa9zris2qsrh/libopenshot.zip) (1 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by fkam18** [comment]
![openshot-tiny-ui](https://user-images.githubusercontent.com/19807662/113702723-ce652b00-96d1-11eb-97a8-8399daa56446.png)

**Comment by fkam18** [comment]
One tip: when I set 100% with 3840x2160 in Ubuntu Display Settings, then it works better. If I do fractional scaling say 125%, then it falls into the small fonts effect esp in the track bars.

**Comment by sc0nway** [comment]
On some computers, especially laptops with small screens with high resolutions, OpenShot's user interface needs to be smaller to fit the screen. There are only two tracks at the bottom, the preview window takes up half the right side, and the Project Files list uses up the remaining available window space.

Our developers addressed the UI scaling issue in our [latest Daily Builds](https://www.openshot.org/download/#daily), although you might still notice that Docks appear oversized for your screen. I have attached a file you can unzip and transfer to your `C:\Program Files\OpenShot Video Editor` folder. You can replace the existing file with the one from the ZIP archive. To initiate OpenShot, execute the launch-win.bat file by double-clicking the file or creating a shortcut on your desktop or in the Startup menu.

The launch-win.bat file contains the following code:

    :: Get the current directory
    SET IMAGE_MAGICK_PATH=%~dp0

    :: Set some environment variables for ImageMagick
    SET DYLD_LIBRARY_PATH=%IMAGE_MAGICK_PATH%
    SET MAGICK_CONFIGURE_PATH=%IMAGE_MAGICK_PATH%ImageMagick\etc\configuration
    SET MAGICK_CODER_MODULE_PATH=%IMAGE_MAGICK_PATH%ImageMagick\modules-Q16\coders

    :: Set some debug variables
    SET PATH=%cd%;%PATH%
    SET QT_PLUGIN_PATH=%cd%
    SET QT_DEBUG_PLUGINS=1
    SET QT_ENABLE_HIGHDPI_SCALING=1
    SET QT_SCALE_FACTOR=0.75

    :: Launch application
    openshot-qt-cli.exe


The lines that concern changing the scale of the interface (the size of the font) are these:

    SET QT_ENABLE_HIGHDPI_SCALING=1
    SET QT_SCALE_FACTOR=0.75


If OpenShot appears too big or too small when you start the program using the launch-win.bat file, you can adjust the value of `SET QT_SCALE_FACTOR`. To meet your specific requirements, you can raise the value above 0.75 or lower it below 0.75.

[launch-win.zip](https://github.com/OpenShot/openshot-qt/files/12178955/launch-win.zip)
