### ISSUE TITLE
OpenShot : Export issue with all the video where the time property as been changed

### ISSUE THREAD

**Issue by Flouflette38** [OpenShot/openshot-qt#4091]
Hi, 
I spent some time to do a video with mp4 videos. 
I've accelerated some of them and slow down others changing the time property or using the preset time changes. 
All good with the preview. But when I export the video, all these videos are, or black or with a time 1, some normal speed, so some pieces are missing or there is extra pieces. 
I'm using the last version of openshot 2.5.1 with windows 10. 
Anyone with the same issue ? 

Thanks
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/6306904/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/6306905/openshot-qt.log)

**Comment by DanPinGF** [comment]
Duplicate of #1197, because if you're on Windows it appears you're trying to use the 'Time' feature on tracks, something that currently doesn't work in all versions starting with 2.4.1.
