### ISSUE TITLE
OpenShot is not consuming NVIDIA GeForce Graphics Card --(Making export very slow)

### ISSUE THREAD

**Issue by GemAbhishek** [OpenShot/openshot-qt#4092]
**Question:**
A clear and concise question. Your question should provide enough context and explanation for people to answer it. Avoid excessive background or irrelevant details, as they can obscure your actual question.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your question. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by MuhammedCanKucukaslan** [comment]
You can manually configure it to use from NVIDIA control panel.
[How to I customize Optimus profiles and settings?](https://nvidia.custhelp.com/app/answers/detail/a_id/2615/~/how-do-i-customize-optimus-profiles-and-settings%3F) ( [archived](https://web.archive.org/web/20210125181221/https://nvidia.custhelp.com/app/answers/detail/a_id/2615/~/how-do-i-customize-optimus-profiles-and-settings) )

**Comment by GemAbhishek** [comment]
> You can manually configure it to use from NVIDIA control panel.
> [How to I customize Optimus profiles and settings?](https://nvidia.custhelp.com/app/answers/detail/a_id/2615/~/how-do-i-customize-optimus-profiles-and-settings%3F) ( [archived](https://web.archive.org/web/20210125181221/https://nvidia.custhelp.com/app/answers/detail/a_id/2615/~/how-do-i-customize-optimus-profiles-and-settings) )

still not using NVIDIA GeForce Graphics Card---- I read task manager GPU graph -- it is 0 for GPU-NVIDIA GeForce Graphics Card---- which is making export very slow

**Comment by DanPinGF** [comment]
Which OS are you using? And which OpenShot version is it? Your initial post doesn't have enough details.

**Comment by DanPinGF** [comment]
Hmm, if I'm correct, you seem to be indicating that OpenShot is not using the dedicated GPU--but rather the processor's integrated GPU--to export the project. I've also seen that not only does it take forever to export, but the resulting output file is humongous, between several hundred megabytes to over a gigabyte (see issue #4077).
