### ISSUE TITLE
How to fix install erroron Windows 10? "cx_Freeze: Python error in main script" Missing or nonexistent folders "c:\msys64\mingw64..."?

### ISSUE THREAD

**Issue by MiguelNunes71** [OpenShot/openshot-qt#410]
The cx_Freeze problem on Windows 10  still persists, is there any fix to install openshot?
It is necessary to install some plugin or associated dependent program?

![capturar](https://cloud.githubusercontent.com/assets/9210919/20462609/3639b8b2-af1a-11e6-9a2e-0db949335815.PNG)

**Comment by janagyjr** [comment]
I've gotten that error several times on my Win7 Pro machine.

**Comment by carlosnewmusic** [comment]
![sin titulo](https://cloud.githubusercontent.com/assets/19379457/20676012/9e9ed8d6-b58e-11e6-9eee-08ad7b5399b3.jpg)
On windows 10 64 bit from the latest dev version

**Comment by DylanC** [comment]
@MiguelNunes71 - Does this issue occur in OpenShot v2.3.4?

**Comment by DylanC** [comment]
This is working in the latest version.
