### ISSUE TITLE
Android 10-11 screen recording audio repeat

### ISSUE THREAD

**Issue by CodeNinja789-coding** [OpenShot/openshot-qt#4100]
**Describe the bug**
When you play the video( the screen recording of android 10/11 samsung A5x, it starts looping the audio like looping 1 sec, "ing -ing -ing" instead of usual( "bluring effect is quite common for zoom users" like this text)

**Steps to reproduce the behavior:**
1. Go to Screen recording( samsung galaxy a5x)
2. Click on record
3. Scroll down to upload to openshot editor
4. See error (repeating audio)

**Expected behavior**
Repeat repeat repeat

**System Details**
- OpenShot Version: 2.5.1
- libopenshot Version:  0.2.5
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['zh-TW', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Skipped this step

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/ooq49t7ks7qozhv8v4dkzdnsuq3a4m20/openshot-qt.zip) (17 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by DanPinGF** [comment]
@CodeNinja789-coding - It may be caused by your video file's codec. That codec might not be fully supported by OpenShot. You probably need to convert the file in a different format for it to function correctly.

**Comment by DanPinGF** [comment]
@speedytechdev - We need help over here...
