### ISSUE TITLE
Sound pitch issue after exporting

### ISSUE THREAD

**Issue by rickyfant** [OpenShot/openshot-qt#4101]
**Describe the bug**
I've set up a video project with a short piece of music at the beginning. After exporting the video, the pitch of the music sounds higher than it actually is, for just a couple of seconds, than back to actual pitch. In OpenShot preview, everything works well.

**Steps to reproduce the behavior:**
1. Create video that starts with music
2. Export the video
3. Open video with external app (Win 10 media manager)
4. Hear music sound incorrect

**Expected behavior**
The music should sound correctly from the beginning 

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev3
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['it-IT', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-daily-7110-982558ec-ad144575-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/24yo38cfiv1v9te40aohcor66y0cg7n5/openshot-qt.zip) (4 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/24yo38cfiv1v9te40aohcor66y0cg7n5/libopenshot.zip) (7 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Schermate** (Optional)
N/A

**Comment by JacksonRG** [comment]
Hi, this sounds like a race condition we recently found in the export process. Having fixed it, I'd love to hear if the pitch issue still happens
