### ISSUE TITLE
The keyframes (smal green lines in the tracks bar)

### ISSUE THREAD

**Issue by LucHamers** [OpenShot/openshot-qt#4102]
**Describe the bug**
The keyframes are not shown in the tracks, not at the start of the selected object and not at to position, where a property was changed. 

**Steps to reproduce the behavior:**
1. Add video to a track
2. Move cursor somewhere
3. Change any property, e.g Alpha

**Expected behavior**
At position 0 and at the position where we changed the property, a keyframe (small green horizontal line) is shown. The keyframes are there, the property behaviour is correct, we can even jump to them via next/previous key point (cool improvement!), but it is not shown. 

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev3
- Platform: Linux-5.11.12-1-default-x86_64-with-glibc2.4
- Processor: x86_64
- Machine: x86_64
- Python version: 3.6.9
- Qt5 version: 5.9.5
- PyQt5 version: 5.10.1
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: en_US.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-daily-7283-0e1b8d66-7064ab55-x86_64.AppImage

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/7330g4as3ake96xbk5l5y4xtbl2s9r9r/openshot-qt.zip) (15 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
![image](https://user-images.githubusercontent.com/8796818/115766107-dac2d680-a3a7-11eb-9cd0-194b2b8af10c.png)

**Comment by JacksonRG** [comment]
Thanks for pointing this out! I noticed this as well when test. I'll be fixing this shortly

**Comment by LucHamers** [comment]
This bug is still present in the 2.6.1 release version (build date 2021-09-04 23:49, using the linux app image OpenShot-v2.6.1-x86_64.AppImage)
