### ISSUE TITLE
Overkill memory usage 99% and pc freeze

### ISSUE THREAD

**Issue by shadowvzs** [OpenShot/openshot-qt#4103]
hi, i have v2.5.1 and i combine 2 mp4 file what was recorded with samsun phone (4+2gb), i do few cut and save in 1080p 30fps h264 mp4 format and often this freeze on linux mint.

system info, ryzen 1600 cpu, 16gb ddr4, ssd, on linux mint 20.04 

if i have only openshot running and i export the video this make me 99% ram useage (yeas, open shot use from 15/16gb memory) and swap file when reach the 100% usage the pc freeze....

i checked the task manager, nothing running with more than 50mbyte memory usage and just system stuffs running.

after i deleted the swap (swapoff and remove the swap line from fstab) then memory usage a lot better, export start at 2.8gb, after export reach 33.5% the ram usage reach 5.5gb (44-45%) without swap file (with swap file the pc was frozen 2x before when export had 12-15%), so a lot better without swap but still memory usage will be multiplied...

**Comment by shadowvzs** [comment]
nobody check it?
right now it is very useless..... 

memory usage just go up and up then kill the pc when it is reached the 100% - 4+2gb video takes more than 15gb memory??????

![openshot](https://user-images.githubusercontent.com/17709504/117570699-08ac5880-b0d4-11eb-8f7f-d8248ae0c2c0.png)

**Comment by Salim9304** [comment]
This memory leak has always been in openshot on Linux. 
The PC often freezes because of this and for me.

**Comment by shadowvzs** [comment]
> This memory leak has always been in openshot on Linux.
> The PC often freezes because of this and for me.

i experienced only recently with 2.5.1, in last few month, before that i used linux lite and chaletOs, and in past i used linux mint with openshot 1.4.3

**Comment by JacksonRG** [comment]
Does this occur with a specific file type? That may help us narrow down where in the video editing code the leak may be.

Also, have you tried this with the daily build?

**Comment by shadowvzs** [comment]
> Does this occur with a specific file type? That may help us narrow down where in the video editing code the leak may be.
> 
> Also, have you tried this with the daily build?

what do you mean under daily build? i tried with appImage and with that version what i installed via apt.

this is the settings what i use
![image](https://user-images.githubusercontent.com/17709504/120693794-23df6d80-c4b2-11eb-9d55-a242c43eb6e0.png)

and this is a video info
```
shadowvzs@shadowvzs-MS-7B86:~/Downloads$ ffmpeg -i ./20210530_110134.mp4 -f null -
ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  WARNING: library configuration mismatch
  avcodec     configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared --enable-version3 --disable-doc --disable-programs --enable-libaribb24 --enable-liblensfun --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libtesseract --enable-libvo_amrwbenc
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from './20210530_110134.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2021-05-30T09:06:04.000000Z
    com.android.version: 10
    com.android.capture.fps: 30.000000
  Duration: 00:04:30.38, start: 0.000000, bitrate: 17259 kb/s
    Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, unknown/bt470bg/unknown), 1920x1080, 17001 kb/s, SAR 1:1 DAR 16:9, 30 fps, 30 tbr, 90k tbn, 180k tbc (default)
    Metadata:
      creation_time   : 2021-05-30T09:06:04.000000Z
      handler_name    : VideoHandle
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 255 kb/s (default)
    Metadata:
      creation_time   : 2021-05-30T09:06:04.000000Z
      handler_name    : SoundHandle
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> wrapped_avframe (native))
  Stream #0:1 -> #0:1 (aac (native) -> pcm_s16le (native))
```

was recorded i guess with samsung a5, useally, not sure if it is related with it
I combine 2 video from this kind and just cut a bit from start and a bit from the end of the 2nd video and add fade, output useally around 30-40 min still enough to burn down all ram, around every 10 sec eat +100mb ram, after minutes eat all memory and everything die, only cold shut down help from pc button

i have a sample video temporary here
https://drive.google.com/file/d/1kO_7KjY2pVYk5HDI5LNk0IHOImQaudJD/view?usp=sharing

**Comment by DanPinGF** [comment]
I've seen this problem on Windows, too, except there isn't usually a memory leak.

**Comment by DanPinGF** [comment]
Oops... looks like a duplicate of #4088.
