### ISSUE TITLE
Why is my Video Preview section so laggy? 

### ISSUE THREAD

**Issue by DerpyCoder123** [OpenShot/openshot-qt#411]
https://www.youtube.com/watch?v=khHuhILTBF0&feature=youtu.be

**Comment by singularsyzygy** [comment]
I am having the same issue.  It is very laggy on Windows and Mac

**Comment by janagyjr** [comment]
I'm having the same issues, as well as another one.

**Comment by MartinHerrman** [comment]
I'm new to openshot after buying my first camcorder. It is recording full HD (AVCHD/MP4). My laptop is a Dell XPS13 (i5-5300U, 8GB, SSD). I'm running Linux Fedora 24 with the AppImage dated Nov 15th (the stable image doesn't start properly). Playing my project result is very slow/stuttering, cpu usage increases to 300+ %.

**Comment by DylanC** [comment]
@DerpyCoder123  - Does this issue occur in OpenShot v2.3.4?

**Comment by DylanC** [comment]
Try OpenShot v2.4. The preview is much better and no lag detected in my testing.
