### ISSUE TITLE
La rotation de 90° ne fonctionne pas

### ISSUE THREAD

**Issue by Philipeau** [OpenShot/openshot-qt#4111]
**Décrire le bogue**
La rotation de 90° à droite ou à gauche ne fonctionne pas en utilisant le clic droit sur la vidéo. Il n'y a que la rotation de 180° qui tourne de 90°...

**Comportement attendu**
La vidéo devrait tourner de 90°, mais au lieu de cela elle semble se mettre en miroir ?

**Détails du système**
- OpenShot Version: 2.5.1
- libopenshot Version:  0.2.5
- Platform: Windows-10-20H2 19042.928
- Processor: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz   2.59 GHz

- Version Daily : le problème vérifié existe toujours dans la version quotidienne : http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-daily-7374-3d804c40-8c4baa5f-x86_64.exe

**Captures d’écran** (Facultatif)

**Comment by USATechDude** [comment]
> Describe the bug
Rotating 90 ° right or left does not work when using right click on the video. Only the 180 ° rotation turns 90 ° ...
>
>Expected behaviour
The video should rotate 90 °, but instead it appears to mirror?

Try resetting OpenShot to its default settings.  Open File Explorer and delete the C:\Users\(USERNAME)\.openshot_qt folder.  Removing this folder removes settings and many things that can, in theory, become corrupt.  OpenShot automatically recreates the folder with the default settings when you relaunch the program.  This folder is not deleted when the program is uninstalled, so your previous settings are saved, often causing projects to fail.

**Comment by Philipeau** [comment]
Merci pour votre réponse.
J'ai supprimé le dossier .openshot_qt, mais le problème est le même : quand je clique sur la vidéo et demande une rotation de 90° vers la gauche, j'obtiens une rotation de 180°. Si je demande une rotation de 180° j'obtiens une rotation de 90° vers la droite (ou 270° vers la gauche).
La seule solution que j'ai trouvée est une solution de contournement en passant par "Propriétés" > "Rotation" > et il me faut demander (très curieusement) 360° pour obtenir la rotation de 270° vers la droite que je souhaite donner à la vidéo (90° vers la gauche).
Philippe
---
582 / 5000
Résultats de traduction
Thank you for your reply.
I deleted the .openshot_qt folder, but the problem is the same: when I click on the video and ask for 90 ° left rotation, I get 180 ° rotation. If I ask for a rotation of 180 ° I get a rotation of 90 ° to the right (or 270 ° to the left).
The only solution I have found is a workaround going through "Properties"> "Rotation"> and I have to ask (very oddly) 360 ° to get the 270 ° rotation to the right that I want to give to the video (90 ° to the left).
Philippe
<img width="959" alt="2021-05-01_16h18_32" src="https://user-images.githubusercontent.com/83423678/116785297-2573db00-aa99-11eb-8ef0-dd1d31d2273d.png">
