### ISSUE TITLE
Immovable Clip

### ISSUE THREAD

**Issue by JacksonRG** [OpenShot/openshot-qt#4112]
## Description
I found that while using openshot I would occasionally find that I couldn't move clips on the timeline. Through experimentation I found this way to reliably reproduce this bug. 
## Reproducing the bug
1. Put a file in the timeline
1. Shift+right click anywhere
    - Releasing right click before dismissing the context (right click) menu
1. Try to move it
1. Find that you can only move it up and down

From this I conclude that the shift "keyup" event is not being received if a context window was being shown.

## Expected behavior
- When shift is held, a clip can only be moved vertically. Keeping it's place in time the same.
- As shift isn't being held, the clips should be able to move.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [Linux / Pop!_OS 20.04]

Video Example:
https://ipfs.io/ipfs/QmSr8BEwrW8rCPUvQcP9EWYmz5R4mzXZE8wunyw952edLN

**Comment by jonoomph** [comment]
**Pro Tip:** If you mention "Closes #4119" in the Issue description, it will auto close the bug when the PR is merged. https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
