### ISSUE TITLE
How can contribute Korean translation of openshot website?

### ISSUE THREAD

**Issue by sebuls** [OpenShot/openshot-qt#4116]
**Question:**
How can make Korean translation of OpenShot website?

**Detail**
I found several languages at top right icon at https://www.openshot.org/ but there is no Korean.

There is no Korean at
https://translations.launchpad.net/openshot/website/+translations

How can start Korean translation of OpenShot website ?

**Comment by ferdnyc** [comment]
@sebuls 

If I click `View all languages` at Launchpad, I do see a listing for Korean, with 0/604 strings untranslated. But you should be able to download the (empty) translation master and start adding translations. 

There's documentation linked at the top of that page, presumably it's a good idea to read that:

https://translations.launchpad.net/openshot/website/+pots/django/ko/+translate?show=untranslated

**Comment by ferdnyc** [comment]
(It probably SHOULDN'T go without saying that we'd be very glad to have OpenShot available in Korean, and we'd be grateful for any help you can offer!)

**Comment by sebuls** [comment]
@ferdnyc Thank you very much.
I started Korean translation of OpenShot website

**Comment by USATechDude** [comment]
You can use Google Translate to translate our webpage to Korean.
https://translate.google.com/translate?hl=&sl=en&tl=ko&u=https%3A%2F%2Fwww.openshot.org%2F&sandbox=1

**Comment by sebuls** [comment]
@USATechDude Hello.
Your link shows
This translation service isn't available in your region

**Comment by ferdnyc** [comment]
Heh. Well, a native translation is far better anyway.
