### ISSUE TITLE
Once it starts, the next moment it silently quits.

### ISSUE THREAD

**Issue by itagagaki** [OpenShot/openshot-qt#4117]
**Describe the bug**
Once it starts, the next moment it silently quits.

**Steps to reproduce the behavior:**
1. Launch OpenShot VIdeo Editor from Windows Start Menu
2. It starts up and once the window appears, the next moment it silently quits.

**System Details**
- OpenShot Version: 2.5.1
- libopenshot Version:  0.2.5
- Platform: Windows-10-10.0.19041 (Windows 10 Pro 20H2)
- Processor: Intel64 Family 6 Model 165 Stepping 5, GenuineIntel (Intel Core i7-10700K)
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['ja-JP', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Skipped this step

**ログファイル**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/7bbzh1n9dgkdpyczruproj6k9c40evy4/openshot-qt.zip) (3 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Comment by USATechDude** [comment]
Try resetting OpenShot to its default settings.  Open File Explorer and delete the C:\Users\(USERNAME)\.openshot_qt folder.  Removing this folder removes settings and many things that can, in theory, become corrupt.  OpenShot automatically recreates the folder with the default settings when you relaunch the program.  This folder is not deleted when the program is uninstalled, so your previous settings are saved, often causing projects to fail.

**Comment by itagagaki** [comment]
Thanks for the response. I tried to launch OpenShot after deleting the .openshot_qt folder, but it still quit quietly. However, it worked fine the second time. This is the same as before; it works the second time, so I live with it. Hope to find out the cause.

**Comment by brimwats** [comment]
I seem to be having a related issue, same Window sbuild and version—program immediately freezes and had to be forcequit. I deleted the folder, and it worked for a few seconds before showing a tutorial and freezing again 
![image](https://user-images.githubusercontent.com/49103046/116802787-adbea400-aaca-11eb-9a0d-c86c03e31e05.png)

**Comment by DanPinGF** [comment]
I have a similar problem. It only crashes once or twice in a while when I start it up.
