### ISSUE TITLE
Invalid load key

### ISSUE THREAD

**Issue by JammyYeeter** [OpenShot/openshot-qt#4120]
![Screenshot (242)](https://user-images.githubusercontent.com/83669020/117055072-a7bb0400-ad12-11eb-8538-22a49ae66fee.png)

Can anyone help me, it is a project I have been working on for a bit now, and I really don't want to lose it.

**Comment by JammyYeeter** [comment]
I can add a file if that can help

**Comment by JacksonRG** [comment]
Does this happen with all files, or only this specific one?

**Comment by JammyYeeter** [comment]
> Does this happen with all files, or only this specific one?

Only this one specific file

**Comment by JammyYeeter** [comment]
Thank you! I found this recovery and I got most of the project back

**Comment by JacksonRG** [comment]
That's great to hear. Happy edditing
