### ISSUE TITLE
Adjusting audio causes crackling and voice alienation overlay the underlying speech

### ISSUE THREAD

**Issue by HeikoBoettger** [OpenShot/openshot-qt#4125]
When ever I adjust audio changing volume from 1,00 to 0,00 in a key frame or adding a delay to freeze the picture on the begin and end of a video, it results in noises in the audio stream.

Either it sounds like I had appliced voice alienation in addition to the normal voices or there are some crackling inside the audio stream including caps. When freezing the picture I sometimes even get black frames for a millisecond.

When looking in to the issue tracker seeing reports about crashes, I wonder whether these issues are caused by some kind of memory corruption or buffer management issue. I also tried to follow the hints not overlaying multiple streams to avoid issues caused by audio mixing but I only adjusting the volume of a single non-overlaping video in direction 0. 

For me this is a reason not recommend openshot for anybody for quickly composing some videos, it just takes to much time to recheck whether audio still works.

I tried the daily build to see whether there is a fix in the master but it seems unusable at the moment due to the redesign our the position slider and video layer view, Any good hint what else might be the cause?

**Comment by DanPinGF** [comment]
I'm not too sure if this has been resolved. I've seen this problem, too, on Windows
