### ISSUE TITLE
Unpredictable preview cache

### ISSUE THREAD

**Issue by fivenote** [OpenShot/openshot-qt#4127]
I compiled Openshot on a raspberry pi 4 4gb. My build is up to date with GitHub repository. I know the pi won’t be a video edit powerhouse, but openshot is very usable except for the cache behavior.

Preview playback always stutters and lags even if I reduce the preview profile to a lower res. That’s expected because the pi cpu is maxed out trying to render and play. However, preview playback is smooth when I see the little blue cache line filled in on the timeline where it is playing.

The problem is that once it preview caches a section, the cache line will disappear for no reason, or stop caching altogether. I increased the memory cache to 1000Mb and also tried 2000Mb. No matter the value, openshot seems to cache ok for a while, then quit, or move cached parts around unexpectedly. FWIW... the pi never runs out of memory. 

For very short videos there’s enough ram to cache the entire timeline. I’ve seen openshot do this sometimes, but not consistently. How do I get openshot to persist the preview cache as much as possible?

Is there a setting, code mod, or bug fix to make this work?

Thanks for helping a pi user with openshot.

**Comment by myier** [comment]
Hi, with the same computer, increasing the cache did it for me. But it's a rendered frame cache, not an input file cache, so if you move the blocks or change effects and so on, the cache is purged for the corresponding frames, so it will be slow for a while again.
To speed up the playback, I found that making the preview smaller by dragging the handle would make it render in real-time.
(tested with debian's version 1.5.1)
