### ISSUE TITLE
Render-video rotated by 180 degrees

### ISSUE THREAD

**Issue by LeosWelt** [OpenShot/openshot-qt#4128]
**Describe the bug**
I had problems in the "normal" version with missing audio in rendered videos.
I tried the daily build, and the audio is there again, but the video output is rotated by 180 degrees, so you will need to stand on your head to watch it correct.

**Steps to reproduce the behavior:**
I have tried it first with a existing project, using video output of OBS as MKV. Rendering was MP4 with Full-HD.
Tried this with rendering 2,5K and videos from a Sony 4K-cam, same result, rotated video output.

**Expected behavior**
The videos should be rendered without the rotation of 180 drgrees.

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev3
- Platform: Linux-5.12.1-arch1-1-x86_64-with-arch
- Processor:  AMD Ryzen 5-2600, 32GB RAM
- Machine: x86_64
- Python version: 3.6.9
- Qt5 version: 5.9.5
- PyQt5 version: 5.10.1
- Qt Detected Languages: ['de-DE']
- LANG Environment Variable: de_DE.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Already using

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/r0a5rsqfr25bvat46msr4c001nytfopr/openshot-qt.zip) (29 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/r0a5rsqfr25bvat46msr4c001nytfopr/libopenshot.zip) (5 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)

**Comment by LeosWelt** [comment]
I have found out:
Its a thing that happens when using VLC to watch the video. VLC shows old videos in correct rotation.
It does not happen when using "mplayer" or "videos" for watching. So there is possibly something inside the video that tells VLC to rotate the output.

**Comment by JacksonRG** [comment]
@LeosWelt Sorry I missed this, but in order to correct this with any video file (for instance different phones treat rotation differently) we have the rotation property on each clip. You can put your playhead at the beginning of a clip, and search `rotation` in the properties window. Then just set it to 180 to flip it over.
