### ISSUE TITLE
Openshot stops working when exporting video (MacOS Sierra)

### ISSUE THREAD

**Issue by singularsyzygy** [OpenShot/openshot-qt#413]
I am experiencing issues exporting a video on Mac.  It stops working and force quits after a while (~10-15 min into processing a 10min video) and does this extremely slowly.  As before mentioned time, it stops at around 6-8%

What would you need of me to help with this issue?

**Comment by JtLively** [comment]
Ensure you have the latest version of Openshot
Check your processor levels
Don't do anything resource-intensive while exporting
Try another export format.

**Comment by DylanC** [comment]
@singularsyzygy - Does this issue occur in OpenShot v2.3.4?

**Comment by DylanC** [comment]
Closing due to a lack of logs or real detail to tackle this.
