### ISSUE TITLE
Timeline Scale Issues, Slider Not Matching Up With Playhead

### ISSUE THREAD

**Issue by Raziel0315** [OpenShot/openshot-qt#4131]
I tried to find a report on this bug.  I was unsuccessful.

**Describe the bug:**

When scaling the timeline, aka zooming in, the scale has issues.  Using the scaling bar (?) doesn't immediately get you the size you want.  On top of that, IF you are able to zoom into the timeline at the size you want, the sliding bar begins to move separately from the playhead.
When you're at the beginning of the project, both of these items match up, but as you move further into the project, they start to separate, and when the sliding bar reaches the end of the display, (the one just above the timeline), the playhead gets severed.  I have added images to clarify.

**Steps to reproduce the behavior:**

Easy to reproduce: zoom in as much as possible, then move the slider all the way to the end.

**Expected behavior:**

The slider should match up with the playhead, I believe, and the playhead shouldn't get severed.

**System Details:**
- OpenShot Version:  2.5.1, May 9th, 2021 daily build
- Operating System:  Windows 10, 64 Bit

**Screenshots:** (Optional)

In the top part of the image, you can see where the slider doesn't match up with the playhead.
In the bottom half, you can see where the playhead is severed because the slider went off of the end of the timeline display or scale or whatever it is.
In both cases, you can see that the slider is well past where the clips ends.

![OpenShot Bug Report](https://user-images.githubusercontent.com/47090619/117676842-ea9a3300-b17b-11eb-9082-68525c4c5ee8.png)

**Comment by JacksonRG** [comment]
I've done a rework of the ruler above the timeline.

From my testing the 'severed playhead' only occurs at the highest degree of zoom.

Looks like we're getting close to solving this.
