### ISSUE TITLE
Freeze when playing video

### ISSUE THREAD

**Issue by MontrealSoft** [OpenShot/openshot-qt#4132]
**Describe the bug**
When playing a 72m MP3 video file (from my Hikvision recorder), will be fine for a few seconds, then stop playing. I have to click Pause then Start to get one more second or so. If I leave it as it, the software will freeze after a while and crash. Same behaviour on my Lenovo (older) notebook.
Could be the software having problems with the codec ? VLC plays them fine.
Video card Nvidia Quadro K420

**Steps to reproduce the behavior:**
1- Import an MP4 file (I can send an example)
2- Slid it in the 1 row of the timeline.
3- Hit play. then wait.

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev3
- Platform: Windows-7-6.1.7601-SP1
- Processor: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel  i7-6700 3.4Ghz, SSD, 16Gigs, Win7Pro
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['fr-FR']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-daily-7454-6a004ed9-92ff6084-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/4p7m2k90t5mejacktj7hwp2ph0wyl4w6/openshot-qt.zip) (184 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/4p7m2k90t5mejacktj7hwp2ph0wyl4w6/libopenshot.zip) (0 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by JacksonRG** [comment]
I'm looking into this and trying to reproduce the issue. You specified an mp4 file. Does this not occur with other file types?

**Comment by DanPinGF** [comment]
Does it crash with MSVCRT.DLL? It may be associated with #4319 if changing OpenShot settings and playing back a pre-existing project.
