### ISSUE TITLE
Korean translation of user-guide

### ISSUE THREAD

**Issue by sebuls** [OpenShot/openshot-qt#4134]
**Question:**
Is there Korean translation of https://www.openshot.org/user-guide/ ?

I want to contribute to the translation of the user-guide. What should I do?

**Comment by sebuls** [comment]
@USATechDude I know two links
Desktop Application: https://translations.launchpad.net/openshot/2.0/+translations
Website: https://translations.launchpad.net/openshot/website/+pots/django
But I don't know where can I contribute Korean translation of 
https://www.openshot.org/user-guide/
Help me please.

**Comment by USATechDude** [comment]
I'm not exactly sure what else I can do.  According to the instructions, you need to log in to LaunchPad and use one of our templates to translate our website or our application into your language.

Does this help you?
[Become a Translator.pdf](https://github.com/OpenShot/openshot-qt/files/6468059/Become.a.Translator.pdf)

**Comment by sebuls** [comment]
Is there translations of  https://cdn.openshot.org/static/files/user-guide/ ?
How can I make Korean translation of it ?

**Comment by ycatch** [comment]
Hi @sebuls. I am also trying to make a Japanese translation of the user guide. 
However, I don't know where to put it in the project. 
I think to put the rst.txt file in my own repository once.
