### ISSUE TITLE
No sound in the video after exporting the video. Tried many videos to test it. Windows 10 is working...

### ISSUE THREAD

**Issue by secure75** [OpenShot/openshot-qt#4136]
**Beschreiben Sie den Fehler**
I could export (render) a video, but no sound is in there. Playing in openshot it self works fine. 
I have no idea what it could be. Last months it works fine, after update it is damaged.
Tried 2 Laptops with arch, everyone was on latest state of the system. 

For direct questions ..... mic - at - altimate.net ... sorry I am not expirienced with github.

**Schritte zum Reproduzieren des Verhaltens**
1. Gehe Sie nach '...'
2. Klicken Sie auf '....'
3. Scrollen Sie hinunter nach '....'
4. Sehen Sie den Fehler

**Erwartetes Verhalten**
Eine klare und prägnante Beschreibung dessen, was Sie erwartet haben.

**Systemdetails**
- OpenShot Version: 2.5.1
- libopenshot Version:  0.2.5
- Platform: Linux-5.12.2-arch1-1-x86_64-with-glibc2.33
- Processor: 
- Machine: x86_64
- Python version: 3.9.5
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['de-DE']
- LANG Environment Variable: de_DE.utf8
- LOCALE Environment Variable: 
- Daily Build: Not able to verify issue still exists in daily build

**Logdateien**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/89q1ajt7f7gm92ub97tqa61av5sqexwd/openshot-qt.zip) (19 KB)
- libopenshot.log: Datei zu klein oder leer (nicht hochgeladen)

**Ausnahme / Stapelverfolgung**
```No stacktrace found in log files```

**Bildschirmfotos** (Optional)
Wenn möglich, fügen Sie Screenshots zur unterstützenden Erklärung Ihres Problems hinzu. Sie können Screenshots einfügen,
indem Sie diese kopieren und auf Github einfügen oder durch Drag and Drop zur GitHub-Seite hinzufügen. Alle Bilder sind öffentlich zugänglich, posten Sie deshalb keine Screenshots die persönliche Informationen enthalten.

**Comment by LeosWelt** [comment]
The same in my case... You can download the Dayly Buid, this renders with tone, but has some other problems with interface, its harder to get videos finished cause the system does not react the same speed as the older version. Am also using Arch Linux...
Ths is one of the problems using a Linux with rolling release, it may (ans perhaps is happedend in this case) happen that a library was updated by Arch Linux and contains errors.

**Comment by secure75** [comment]
THX for your help.

    Am Sonntag, 16. Mai 2021, 21:05:31 MESZ hat LeosWelt ***@***.***> Folgendes geschrieben:  
 
 


The same in my case... You can download the Dayly Buid, this renders with tone, but has some other problems with interface, its harder to get videos finished cause the system does not react the same speed as the older version. Am also using Arch Linux...
Ths is one of the problems using a Linux with rolling release, it may (ans perhaps is happedend in this case) happen that a library was updated by Arch Linux and contains errors.

**Comment by secure75** [comment]
Version 2.5.1-dev2
libopenshot: 0.2.5-dev3

Does not solve the issue

(via git checkout)
    Am Montag, 17. Mai 2021, 11:59:15 MESZ hat michael müller ***@***.***> Folgendes geschrieben:  
 
  THX for your help.

    Am Sonntag, 16. Mai 2021, 21:05:31 MESZ hat LeosWelt ***@***.***> Folgendes geschrieben:  
 
 


The same in my case... You can download the Dayly Buid, this renders with tone, but has some other problems with interface, its harder to get videos finished cause the system does not react the same speed as the older version. Am also using Arch Linux...
Ths is one of the problems using a Linux with rolling release, it may (ans perhaps is happedend in this case) happen that a library was updated by Arch Linux and contains errors.

**Comment by makeworld-the-better-one** [comment]
Am also on Arch Linux and had this issue. For now I resolved it by installing OpenShot from Flathub, [here](https://flathub.org/apps/details/org.openshot.OpenShot).

@JacksonRG I assume this is fixed and it will work again in the next release, since you closed the issue? Thanks.

**Comment by JacksonRG** [comment]
@makeworld-the-better-one That was my understanding, as it appears that the daily build doesn't have this issue.

**Comment by LeosWelt** [comment]
OK, the daily-build has this issue cleaned, but has more and more issues:
No sorting in file-select : I am not able to sort files by names, date or whatever when trying to insert them...
Problems navigating through the timeline, bad answer-times, almost unable to locate the time to the start

**Comment by JacksonRG** [comment]
Glad to hear the daily build has addressed this error. We are working towards a new stable release. To address the other issues you are having.
