### ISSUE TITLE
Audio Cuts Out

### ISSUE THREAD

**Issue by janagyjr** [OpenShot/openshot-qt#414]
I've started making game videos to post to Facebook, and to some of them I add audio external to the recorded session (mp3s right now). However, about 2:35 seconds into the the video (first track),the audio buzzes and then cuts out. The audio resumes when it hits the cue for the next track, but then cuts out yet again at 6:05 into the video. This continues on for all the audio tracks, but /only/ for audio external to the recorded video. By default I export to mp4 (h.264) preset for high quality, however I have had it happen when I did a full export using the YouTube-HD preset as well.

https://www.youtube.com/watch?v=hVyAUP6StCA

I'm not sure what the issue is, as none of my audio apps quit playing the music like OpenShot does (MusicBee and WiMP, machine specs and software versions at end). This is really frustrating. I've volunteered to also encode videos for my church and I need to be able to sync up audio with video, but there is no point in running the export if the audio craps out less than 3 minutes into the export.

OpenShot 2.1.0
Windows 7 Pro SP1
Intel Xeon W3550 8-core 3.05GHz
12GB DDR-3

**Comment by deechte** [comment]
I'm seeing this exact same behaviour. Tried it with three different MP3 audio files. Always at the exact same spot of 2 min 35 sec.

**Comment by DylanC** [comment]
@janagyjr - Does this issue occur in OpenShot v2.3.4?

**Comment by janagyjr** [comment]
I no longer use OpenShot. I have since moved on to using a different editor. Following up 9 months later is pretty slow.

**Comment by DylanC** [comment]
@janagyjr - No problem. Feel free to try it again in the future! ;)
