### ISSUE TITLE
Loop at start

### ISSUE THREAD

**Issue by juhopohjonen** [OpenShot/openshot-qt#4141]
When you have started the excutable and you have deleted the media files, it begins to ask user where the media file path is. When i have not the media files anymore, i cant open the project, but i cannot create a new project.

(Openshot Video Editor, Finnish Lang)

Thank you, have a nice day! :)

**Comment by USATechDude** [comment]
When OpenShot prompts you to locate the missing files, press the Esc key repeatedly until the project opens.  From the File menu, click the New Project option, then close OpenShot.  The next time you launch OpenShot, you should not be prompted to locate missing files.

If that process does not work, try resetting OpenShot to its default settings.  Open File Explorer and delete the `C:\Users\(USERNAME)\.openshot_qt` folder.  Removing this folder removes settings and many things that can, in theory, become corrupt.  OpenShot automatically recreates the folder with the default settings when you relaunch the program.  This folder is not deleted when the program is uninstalled, so your previous settings are saved, often causing projects to fail.

**Comment by wasimafser** [comment]
@juhopohjonen , can you confirm if the issue is similar to #4145 ?
If yes, we can close this issue.

**Comment by juhopohjonen** [comment]
Yes

su 16.5.2021 klo 7.47 Wasim Afser ***@***.***> kirjoitti:

**Comment by juhopohjonen** [comment]
its good now
