### ISSUE TITLE
invalid load key

### ISSUE THREAD

**Issue by sharris88** [OpenShot/openshot-qt#4142]
**Question:**

Was editing a project, saved it, next morning tried to open project and get an error. "invalid load key"  anyway to fix this?  i attached the project file in the zip

**System Details:**
- OpenShot Version 2.4.1
- Operating System : Windows 10
**Screenshots:** 

![openshot error](https://user-images.githubusercontent.com/73490596/118310316-4bd74480-b4a3-11eb-8e64-69fa3b919842.jpg)

[project file.zip](https://github.com/OpenShot/openshot-qt/files/6480467/project.file.zip)

**Comment by JacksonRG** [comment]
Issue #4120 had a similar problem. This means that the file you are trying to open has no data.

You may be able to recover your project from an automatic backup.
OpenShot makes periodic (every three minutes by default) backups after you save a project for the first time. They are stored in:
`C:\Users\(*USERNAME*)\.openshot_qt\recovery`
Look for the most recent file with your project's name.
Going forward it may be also be helpful to save your work at the end of a day, keeping the last one or two versions.
