### ISSUE TITLE
Program Crashes When I Load a Previously Saved Project

### ISSUE THREAD

**Issue by HailHydreigon19** [OpenShot/openshot-qt#4143]
I have spent about 7 hours on a video I'm working on, and after importing a short video clip, the program crashed.  After that, I installed the newest version, but the same thing is still happening.  Does anyone have any idea what the issue could be?  Thanks so much for any help!

**Comment by wasimafser** [comment]
Could you please provide logs ? It can be found at `<YOUR_HOME_PATH>/.openshot_qt/` with the name `openshot-qt.log`

**Comment by HailHydreigon19** [comment]
> Could you please provide logs ? It can be found at `<YOUR_HOME_PATH>/.openshot_qt/` with the name `openshot-qt.log`

[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/6488246/openshot-qt.log)

**Comment by JacksonRG** [comment]
Taking a look over the logs. While I do:

Openshot also creates periodic backups of projects (after they've been saved once) in `$HOME/.openshot_qt/recovery`.You might check there for a version of your project that can open.

**Comment by carlosnewmusic** [comment]
The same thing happens to me https://pastebin.com/Bq7JmNtq
