### ISSUE TITLE
How can make Korean at openshot.org

### ISSUE THREAD

**Issue by sebuls** [OpenShot/openshot-qt#4144]
Hello. I translate OpenShot website into Korean.
https://translations.launchpad.net/openshot/website/+translations
But I can't see Korean at
Features - Language menu of https://www.openshot.org/
How can do it ?
Help me please.

**Comment by Drakesdrs** [comment]
Install the google translate extension for your browser for now.

**Comment by sebuls** [comment]
@Drakesdrs 
Click on the upper right globe at https://www.openshot.org/.
There are multiple language lists.
But there is no Korean.
Who can add Korean to this menu?

I translated the open shop website into Korean.

https://translations.launchpad.net/openshot/website/+pots/django/ko/+translate

**Comment by jonoomph** [comment]
@sebuls Sure thing, I can take a look. It's a manual process to add a new language to the website, but I will try and get this done by Monday. I'll let you know once it's ready. Thanks again for your contribution!

**Comment by sebuls** [comment]
@jonoomph Thank you.

I have one more question.
The OpenShot website has two language menus:
Features - Language
Earth (top right of website)

What is the difference between the two menus?

Thank you again for your reply.

**Comment by jonoomph** [comment]
They are essentially the same thing. The Features->Language contains a direct hyperlink to the various language versions of the current page. The Earth (top right) or Language name in the page footer, show a menu, which uses Javascript to hyperlink you to the correct language page. They both go to the same place though:

For example:
https://www.openshot.org/features/   - English (default)
https://www.openshot.org/es/features/  - Spanish
https://www.openshot.org/LANG-CODE/features/  - Any language we have available

**Comment by jonoomph** [comment]
@sebuls Our website has been updated now, and your latest translations are available:
https://www.openshot.org/ko/

I also noticed there is still lots of English mixed into the Korean translation. For example:
https://translations.launchpad.net/openshot/website/+pots/django/ko/+translate?batch=10&show=all&search=We+designed+OpenShot+Video+Editor

Thanks again for your help!

**Comment by jonoomph** [comment]
I've added 3 new translations in total:
 - Russian
 - Croatian
 - Korean

**Comment by jonoomph** [comment]
Closing ticket for now. Please reopen if you need me to update the translations again. Thanks!

**Comment by sebuls** [comment]
Hello. 
I translated more strings to Korean.
But, I don't know how reopen this issue.
Help me please.

**Comment by JacksonRG** [comment]
Collaborators, as well as the creator of the issue should have a button under the comment window to reopen an issue.
![GithubReopenButtonsCircle](https://user-images.githubusercontent.com/42394129/121088362-3eb02b80-c7ab-11eb-9599-f4faf9dc1a79.png)
Anyways, I reopened it. Why did you want it open?

**Comment by sebuls** [comment]
@JacksonRG Thank you.
@jonoomph said "Please reopen if you need me to update the translations again."
And I updated Korean translation.
So, I want it  reopen.
