### ISSUE TITLE
endless cycle of 'find directory that contains: xxx'

### ISSUE THREAD

**Issue by chucklepie** [OpenShot/openshot-qt#4145]
**Describe the bug**
I opened a file that had a missing file. It opened a dialog asking me to find it, the file does not exist but I still want the project to make use of the other assets it had. I click cancel, it asks me for the file again, I click cancel, it repeats. You cannot escape this cycle and have to force shut openshot via the terminal window.

**Steps to reproduce the behavior:**
As above

**Expected behavior**
Cancel should abort the open and continue with the project.

**System Details**
- OpenShot Version: 2.5.1
- libopenshot Version:  0.2.5
- Platform: Linux-4.15.0-140-generic-x86_64-with-glibc2.2.5
- Processor: 
- Machine: x86_64
- Python version: 3.8.8
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.1
- Qt Detected Languages: ['en-GB', 'en']
- LANG Environment Variable: en_GB.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Skipped this step

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/vvacdzjh3mf9a2z78wii5cxsrqgc8tn1/openshot-qt.zip) (4 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Comment by wasimafser** [comment]
It seems like it's missing multiple files ?

```
project_data:INFO Removed missing file: flip2_2_4.mp4
project_data:INFO checking file /home/neil/Videos/flip2_2_3.mp4
project_data:INFO Removed missing file: flip2_2_3.mp4
project_data:INFO checking file /home/neil/Videos/flip2_2_2.mp4
project_data:INFO Removed missing file: flip2_2_2.mp4
project_data:INFO checking file /home/neil/Videos/flip2_2_1.mp4
project_data:INFO Removed missing file: flip2_2_1.mp4
```

can you make sure that the dialog doesn't show the same file name each time ?

**Comment by chucklepie** [comment]
Yes there were the mp4 files missing, but it goes on forever, with Cancel bringing up the same missing file over and over again. I got bored after 15 tries of flip2_2_4.mp4 and had to terminate. I rebooted tried it again and it does the same.

I'm sure it'll be pretty easy to recreated, just add some titles, images, mp4, delete the mp4 and open...

**Comment by wasimafser** [comment]
I did the same, For the one file I deleted, it did prompt me two times to select the file, ( one for the file and one for clip ), but was not in an endless loop. 

> Daily Build: Skipped this step

Can you try with the daily build ?

**Comment by chucklepie** [comment]
I have downloaded
OpenShot-v2.5.1-dev2-daily-7481-42f9aeec-92ff6084-x86_64.AppImage

As you can see from video below it just repeats the same one after it finishes the 3 it cannot find...

https://user-images.githubusercontent.com/12863685/118366112-4f4bf800-b597-11eb-95ae-d73f1a1011cc.mp4

**Comment by wasimafser** [comment]
Also can you please confirm if the files "flip2_2_4.mp4", "flip2_2_3.mp4" ... Are being asked for more than two times ?

As mentioned above, it did repeat the prompt for the second time, but not further. 

Please check if any more files are missing.

This will narrow down the problem.

**Comment by chucklepie** [comment]
If you notice it is asking for the last file about 5 times. I went on for
about 15 times of that same last file.

**Comment by chucklepie** [comment]
The problem is regardless the issue, cancel shouldn't be repeating.

I wonder if the bug is if I split the file in the editor it is trying to
load the same file over and over for each split I created?

**Comment by wasimafser** [comment]
> The problem is regardless the issue, cancel shouldn't be repeating.
> 
> I wonder if the bug is if I split the file in the editor it is trying to
> load the same file over and over for each split I created?

Yes, you should have mentioned this earlier, anyways, as mentioned above it searches for clips too. So, the number of times you created that split, the same number of times you'll be prompted to search for it.

Also, true, like in this case, if someone created a lot of clips, they'll be in trouble. Will discuss about it and push a solution soon !

**Comment by chucklepie** [comment]
Thanks, I just presumed it was loading actual resources.

I think resources should only be loaded or tried to be loaded once. I mean
I don't know openshot but I'm figuring a clip is just a reference to a
start and end point of an actual resource?

**Comment by USATechDude** [comment]
You should be able to work around the missing file error by placing **all** of your source files into the same folder as your project OSP file.  When you load your project, you will still be prompted to locate the file(s), but once you point OpenShot to the folder with all of your clips, it should load your project.
​
If OpenShot enters the endless loop of asking for missing files, you can repeatedly press the _Escape_ key to escape the loop and load your project.  You may have to press the Escape key many times, but OpenShot will eventually bypass all of the missing files and open your project.

**Comment by chucklepie** [comment]
Thanks. I don't know the software. But surely if you have 1 file split into
100 slices, openshot shouldn't be trying to find the same file 100 times.
It should be trying to find the resource once then skipping subsequent
checks on the same file...

Then it'll load faster too?

**Comment by JacksonRG** [comment]
The issue with that approach would likely be either loading files into memory, or spending time copying them to Openshot's own location.

However, I will look into creating  a 'skip all' option. If a user know's their links are broken, and doesn't need to fix them.

If you don't mind, I'll close this issue, as I believe you're able to access your project.
