### ISSUE TITLE
Add "Yes to All" and "No to All" to dialog asking whether to import file as image sequence.

### ISSUE THREAD

**Issue by Jwolter0** [OpenShot/openshot-qt#4146]
**Describe the new feature:**
when importing image files, if the filenames look like they could be an image sequence, a dialog appears asking whether to import files as an image sequence. The dialog reappears for all of the files being imported. 

Thank you for this great piece of software!

**Describe the solution you'd like:**
A "No to All" option in the dialog would save many clicks.

**Describe alternatives you have considered:**
Rename the files

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your request.
![Screenshot from 2021-05-15 13-09-57](https://user-images.githubusercontent.com/3505047/118394998-05eebd80-b616-11eb-9e2c-0dd940fa6d51.png)

**Comment by jandermoreira** [comment]
I think a single 'no' should be enough to import each image separately, the same way as a single 'yes' already works to import them as a sequence.

**Comment by jandermoreira** [comment]
I still think this feature should be implemented! :)
I use a lot of slides and choosing "No" to every single one is annoying...

**Comment by JacksonRG** [comment]
Hi, I just tried this with files `01.jpg` `02.jpg` `03.jpg`. Clicked import files, and selected the three at once.

I saw the dialog and clicked no (once) and the three imported separately. I also tried two sets of numbered files (which I thought was the issue you were talking about) and clicking no once brought all the files in individually.

What Operating System are you using, and how are you importing your images? (i.e. Right clicking the files window and selecting import files, or dragging files from a file explorer into the file window)

**Comment by Jwolter0** [comment]
Yes, this behavior has been fixed. I didn't realize the issue hadn't been closed. If you are using a current version and still having this issue, there's something else going on.

**Comment by jandermoreira** [comment]
Everything is working just fine with 2.6.0!
Thanks!

**Comment by JacksonRG** [comment]
Good to hear!
