### ISSUE TITLE
Timeline Scale Too Big

### ISSUE THREAD

**Issue by ramzor** [OpenShot/openshot-qt#415]
I am often making very short videos (<2 seconds) and it is very inconvenient to not be able to zoom in on a short clip to optimize timing of titles, audio, etc. It's a shame since I see this nice, long timeline along the bottom of the window, but only a tiny sliver actually holds the media I'm editing (I think a video has to be a minimum of 2 minutes long to fill the timeline at max zoom.)

Also, with choppy clip previewing, manual timing can be near impossible. If frame-by-frame traversing was more visible (i.e. if the timeline was more zoomed in) then my job would be much easier.

**Comment by JtLively** [comment]
For now, your best bet is to use the "resize" tool or use a web solution such as http://ezgif.com/

**Comment by DylanC** [comment]
@ramzor  - This will be tracked in #160
