### ISSUE TITLE
OpenShot on Chrome OS crashes when adding video to timeline

### ISSUE THREAD

**Issue by GabrielBrangers** [OpenShot/openshot-qt#4150]
Installed OpenShot with Chrome OS installer from downloads page. App launches and runs but after importing video, adding it to timeline causes OpenShot to shut down. Verified on two devices. Issue does not appear on the daily build appimage.

**Comment by JacksonRG** [comment]
Does this happen with multiple videos, a specific video, or a specific file type?

**Comment by JacksonRG** [comment]
Closing this issue, as it's being discussed at #4135
