### ISSUE TITLE
When playing it immediately pauses but moves to the next frame by one

### ISSUE THREAD

**Issue by galaxyentity904** [OpenShot/openshot-qt#4154]
**Describe the bug:**

When I use open shot and try to play back, even with nothing in the tracks, it goes forward a single frame then immediately stops. I've played around with performance and nothing worked. It gives me the code preview_thread:INFO onModeChanged twice when pressing the play button

**Steps to reproduce the behavior:**
Unknown

**Expected behavior:**

The player playing

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 2.5.1 {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1] Xubuntu 20.10

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by galaxyentity904** [comment]
Uh- I added a file and it worked again? The first time I tried adding a file it just lagged a lot

**Comment by JacksonRG** [comment]
Would you mind posting your log files of the issue?

Instructions [here](https://www.openshot.org/issues/new/) to help.
In short:
1. Delete your log file
2. Replicate the bug
3. Drag the new log file into a github comment to link the log.
