### ISSUE TITLE
Jack + Pulsaudio crash on video rendering

### ISSUE THREAD

**Issue by Reyadeyat** [OpenShot/openshot-qt#4156]
**Describe the bug:**
When I click red button Export Video the exported video run as muted video only and noticed QjackCtl always crashes with this message every time the export video start running and the journalctl log show  "This file contains no playable streams".

journalctl -xe log:
Starting Tracker metadata extractor...
Successfully activated service 'org.freedesktop.Tracker3.Miner.Extract'
Started Tracker metadata extractor.
Call to gst_discoverer_discover_uri(file:///Vids/Test_video.mp4) failed: This file contains no playable streams.
tracker-extract-3.service: Deactivated successfully.
tracker-extract-3.service: Consumed 2.874s CPU time.

QjackCtl log:
Sat May 22 09:52:14 2021: New client 'qjackctl' with PID 813
10:37:16.461 XRUN callback (1).
10:37:16.753 XRUN callback (2 skipped).
Sat May 22 10:37:16 2021: ERROR: JackEngine::XRun: client = PulseAudio JACK Sink was not finished, state = Running
Sat May 22 10:37:16 2021: ERROR: JackEngine::XRun: client a2j finished after current callback
Sat May 22 10:37:16 2021: ERROR: JackEngine::XRun: client PulseAudio JACK Source finished after current callback
Sat May 22 10:37:16 2021: ERROR: JackAudioDriver::ProcessGraphAsyncMaster: Process error
10:37:23.432 XRUN callback (4).
10:37:48.625 XRUN callback (5).

**Steps to reproduce the behavior:**
1. start QjackCtl with Pulsaudio start up script to enable (Pulseaudio Jack Sink) => pactl set-default-sink jack_out && pactl set-default-source jack_in
2. add video to track 1
2. add another sound clip to track 2
3. mute video sound
4. Export Video

**Expected behavior:**
Video with sound

**System Details:**
- OpenShot Version: 2.5.1 with libopenshot: 0.2.5
- Operating System / Distro: Arch Linux / rolling => latest full update pacman -Syyu on 2021.05.20
   uname -a => Linux archlinux 5.12.5-arch1-1 #1 SMP PREEMPT Wed, 19 May 2021 10:32:40 +0000 x86_64 GNU/Linux
- Pulseaudio: 
pulseaudio 14.2-3
pulseaudio-alsa 1:1.2.2-2
pulseaudio-bluetooth 14.2-3
pulseaudio-equalizer 14.2-3
pulseaudio-jack 14.2-3
pulseaudio-lirc 14.2-3
pulseaudio-zeroconf 14.2-3
- ALSA:
alsa-card-profiles 1:0.3.28-1
alsa-firmware 1.2.4-2
alsa-oss 1.1.8-3
alsa-plugins 1:1.2.2-2
alsa-utils 1.2.4-2
- JACK Audio Connection Kit: 
QjackCtl: 0.9.3-1 with Qt 6.1.0
cadence 0.9.1-4
jack-stdio 1.6-1
jack2-dbus 1.9.18-1
jack_capture 0.9.73-8
jack_delay 0.4.2-1
jack_mixer 16-1
jack_utils 0.0.1-1
jackmeter 0.4-2
jackminimix 0.2.1-2
jacktrip 1.3.0-1
jalv 1.6.6-1
japa 0.9.2-2
jconvolver 1.0.3-2
jdk-openjdk 15.0.2.u7-1
jnoisemeter 0.2.2-2
jsampler 0.9-9

**Log Files:**

journalctl -xe

May 22 12:01:44 archlinux systemd[693]: Starting Tracker metadata extractor...
░░ Subject: A start job for unit UNIT has begun execution
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit UNIT has begun execution.
░░ 
░░ The job identifier is 351.
May 22 12:01:47 archlinux dbus-daemon[709]: [session uid=1000 pid=709] Successfully activated service 'org.freedesktop.Tracker3.Miner.Extract'
May 22 12:01:47 archlinux systemd[693]: Started Tracker metadata extractor.
░░ Subject: A start job for unit UNIT has finished successfully
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit UNIT has finished successfully.
░░ 
░░ The job identifier is 351.
May 22 12:01:47 archlinux tracker-extract[20552]: Call to gst_discoverer_discover_uri(file:///Vids/Test_video.mp4) failed: This file contains no playable streams.
May 22 12:02:00 archlinux systemd[693]: tracker-extract-3.service: Deactivated successfully.
░░ Subject: Unit succeeded
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ The unit UNIT has successfully entered the 'dead' state.
May 22 12:02:00 archlinux systemd[693]: tracker-extract-3.service: Consumed 2.874s CPU time.
░░ Subject: Resources consumed by unit runtime
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ The unit UNIT completed and consumed the indicated resources.

**Exception / Stacktrace:**

**Screenshots:** (Optional)

**Comment by JacksonRG** [comment]
For clarification, are you only muting one clip, or the whole video before exportin?

**Comment by Reyadeyat** [comment]
I tried it again now, even without muting any clips it gives these mentioned errors, and the video is muted despite the fact plays correctly inside OpenShot priview before extracting and even after Jack reports the error and exporting the video, the preview is correct the output video is muted.
I mute the track by turning off track property "Enable Audio" on side menu and the preview is correct, also to mention, kdenlive exports correctly without muting or JACK crash that's why I believed it would be some sort of bug here.

**Comment by JacksonRG** [comment]
Also the log files you included are from pulse audio and JACK correct?

Could you drag your openshot logs into a GitHub comment so I can take a look at them?

**Comment by Reyadeyat** [comment]
yes they are from QjackCtl and from journalctl -xe
the openshot directory is attached compressed
[home.openshot_qt.zip](https://github.com/OpenShot/openshot-qt/files/6528578/home.openshot_qt.zip)

**Comment by JacksonRG** [comment]
Thank you! Taking a look

**Comment by ferdnyc** [comment]
Just to clarify, @Reyadeyat : Does the crash happen _while_ exporting the video, or when you try to play the exported video AFTER the export?

We don't support Jack at all, technically. (Nor even PulseAudio, directly, since audio out is done using its ALSA emulation layer.) But, no audio device of any kind needs to be opened or should be opened during export, so if that's when the crashes are happening then that's extremely odd. Most likely either ffmpeg is doing it for some reason, or there's some JUCE code that's misbehaving. ...If the problem is playback of the file after export, though, there are a few reasons I can think of why that may be happening.

**Comment by ferdnyc** [comment]
@Reyadeyat Did you intend to close this?
