### ISSUE TITLE
Truncation of generated assets folder filename clobbers versioning

### ISSUE THREAD

**Issue by Geep1** [OpenShot/openshot-qt#4158]
**Describe the bug & Steps to reproduce the behavior:**
When a project is saved, it appears as _filename1_.osp and as folder _filename1_ _assets.
But, for the folder only, the filename1 is truncated to 32 characters before appending "_assets".

This causes silent overwrite of the assets folder when _filename1_ is not unique in the first 32 characters across projects. The use case where this is most likely to be encountered is in versioning, i.e.:

Save as: "My video project with a long name version 1"
Save as: "My video project with a long name version 2"

Both will generate an assets folder like:
"My video project with a long nam _assets"

The second save will cause assets folder overwrite, losing version 1 edit.

**Expected behavior:**
Possible solutions:
1) Remove truncation of _filename1_ when generating _assets name. This is preferred solution.
2) Truncate .osp name as well. Check for existing file, and if found provide Overwrite. Are You Sure? dialog THAT SHOWS THE TRUNCATED NAME.

**System Details:**
- OpenShot Version 2.5.1
- Windows 10

**Comment by JacksonRG** [comment]
Thanks for reporting this! I'll get testing.

**Comment by JacksonRG** [comment]
Thanks for reporting this! We've raised the truncation length to the file name limit for Linux and Windows. Tomorrow's [daily build](https://www.openshot.org/download/) should have these changes!
