### ISSUE TITLE
Custom Plugins and Skins with third-party support (through an API or something)

### ISSUE THREAD

**Issue by nightwing2994** [OpenShot/openshot-qt#4160]
**Describe the new feature:**
Support for third-party plugins, extensions, effects, filters, or themes.

**Describe the solution you'd like:**
Support for third-party plugins, extensions, effects, filters, or themes.

**Describe alternatives you have considered:**
N/A

**Screenshots:** (Optional)
N/A

**Comment by JacksonRG** [comment]
This is a really interesting idea. Do you have a specific filter or effect you wish you could implement?

**Comment by nightwing2994** [comment]
I make YouTube videos, so some fancy transitions and colour blending would be a huge bonus for me. I currently stick to the fade transition because it's the most professional-looking. The others, sorry to say, seem a little amateurish. I love OpenShot because of its simplicity and speed, and I obviously don't expect it to compete with Vegas Pro or Premiere Pro, but plugin or extension support will be an amazing feature for the next major update.
