### ISSUE TITLE
2 bytes character language is not dispayed in Title on Ubuntu 20.04

### ISSUE THREAD

**Issue by hajime651118** [OpenShot/openshot-qt#4161]
**Describe the bug**
Title does not show 2 bytes characters on Ubuntu 20.04.  However, it is no problem on Windows 7.

**Steps to reproduce the behavior:**
1. Go to 'Title'
2. Select 'Footer 2' (for example)
3. Copy Japanese words from other software
4. Type 'A'  into Line 1.  You can see 'A'
5. Paste the Japanese words to append after 'A'.  No Japanese word can be seen

**Expected behavior**
Both 'A' and the Japanese word can be seen.

**System Details**
- OpenShot Version: OpenShot-v2.5.1-dev2-daily-7531-b09416c2-92ff6084-x86_64
- libopenshot Version:  "0.2.0-dev4"
- Platform: Linux-5.4.0-73-generic-x86_64-with-Ubuntu-20.04-focal
- Processor: x86_64
- Machine: x86_64
- Python version: 3.6.9
- Qt5 version: 5.9.5
- PyQt5 version: 5.10.1
- Qt Detected Languages: ['en-US', 'en']
- LANG Environment Variable: en_US.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-daily-7531-b09416c2-92ff6084-x86_64.AppImage

**Log file**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/jz6jsdemudagesjckxnlv3u84leckdfp/openshot-qt.zip) (16 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/jz6jsdemudagesjckxnlv3u84leckdfp/libopenshot.zip) (415 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Comment by JacksonRG** [comment]
Did you try editing a the title in Inkscape? Also, where are you copying the character from? I just tried copying from the Wikipedia article of Kana, and it worked.

**Comment by hajime651118** [comment]
Any kana words in Wikipedia should be fine.

Inkscape:
I select "Footer 2" and paste "アプリ".  
- No word can be seen in Openshot on UBUNTU 20.04.
- The word can be seen on Windows 7.

After that, I pressed edit button and Inkscape was opened by itself.
The word can been seen.  (UBUNTU 20.04)

I saved without changing anything and close Inkscape.  But no word can be seen in Openshot.

Thank you.

**Comment by JacksonRG** [comment]
Have you tried changing the font being used? Also, you might try creating the title Entirely in Inkscape, then exporting it as an image. This should get around the font issue, though that's still something to look into.

**Comment by hajime651118** [comment]
Yes, I changed font but it does not help.
I have been making Title by GIMP and importing as PNG image.  It is quite time consuming because I need outline on the words.
This is the reason I really need to use Title function in OpenShot.  1 movie has more than 50 Titles.  I do not want to go back to PNG title.
This problem exists only on Ubuntu.  I had been tested on 18.04 and 20.04.  Both don't work.
