### ISSUE TITLE
Export Error 

### ISSUE THREAD

**Issue by Vaalerbonde** [OpenShot/openshot-qt#4162]
![Capture457475](https://user-images.githubusercontent.com/83236249/119958735-98db1080-bfa3-11eb-9640-362a0fc20791.JPG)

Help what to do

**Comment by JacksonRG** [comment]
Could you include the log files from when this happened?
You can do this by deleting the log file, recreating the error, and then dragging the log file into your issue while editing it.

The page on [reporting bugs](https://www.openshot.org/issues/new/) tells that you can find your logs here:
/home/USER/.openshot_qt/openshot-qt.log
/home/USER/.openshot_qt/libopenshot.log

Could you also include details like your operating system, and version of openshot?

**Comment by DanPinGF** [comment]
Maybe try updating to the latest OpenShot?
