### ISSUE TITLE
Exported video recorded on Android phone has no audio

### ISSUE THREAD

**Issue by dwlegg** [OpenShot/openshot-qt#4164]
See attached file:
[output_from_daily_build_when_run_in_bash_window.txt](https://github.com/OpenShot/openshot-qt/files/6561253/output_from_daily_build_when_run_in_bash_window.txt)
The latest daily build crashed when I ran it. See the extra attachment.

Briefly, even when I record a very short video on my Android phone and import it into Openshot (which is looking really good nowadays!), when I export the video, using the default settings, the resulting .mp4 file seems to have no audio when I play it using vlc.

**Steps to reproduce the behaviour:**
1. Import single .mp4 file recorded on phone.
2. Drag file to Track 5.
3. Click Export Video button.
4. View exported file using vlc or dragon player.

**Expected behaviour**
Both video and audio should play.

**Actual behaviour**
Only audio plays

**Fedora RPMs**
libopenshot-audio-0.2.0-4.fc34.x86_64
libopenshot-0.2.5-8.fc34.x86_64
python3-libopenshot-0.2.5-8.fc34.x86_64
openshot-2.5.1-6.fc34.noarch
openshot-lang-2.5.1-6.fc34.noarch

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev3
- Platform: Linux-5.12.7-300.fc34.x86_64-x86_64-with-fedora-34-Thirty_Four
- Processor: x86_64
- Machine: x86_64
- Python version: 3.6.9
- Qt5 version: 5.9.5
- PyQt5 version: 5.10.1
- Qt Detected Languages: ['en-GB']
- LANG Environment Variable: en_GB.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Not able to verify issue still exists in daily build

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/5cqwjely6ztmlgq4awkupbde1usoclnk/openshot-qt.zip) (6 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/5cqwjely6ztmlgq4awkupbde1usoclnk/libopenshot.zip) (14 KB)

**Exception / Stacktrace**
```/lib64/libc.so.6               abort                                    0x116  [0x7f2cda9ae8a4]
/tmp/.mount_uDMRdA/usr/bin/libQt5Core.so.5                                          0x96fb7  [0x7f2ccc424fb7]
/tmp/.mount_uDMRdA/usr/bin/libQt5QuickWidgets.so.5                                          0xa9f0  [0x7f2cbc1329f0]
/tmp/.mount_uDMRdA/usr/bin/libQt5QuickWidgets.so.5                                          0xad5a  [0x7f2cbc132d5a]
/tmp/.mount_uDMRdA/usr/bin/libQt5QuickWidgets.so.5 QQuickWidget::resizeEvent(QResizeEvent*) 0x38e  [0x7f2cbc134f8e]
/tmp/.mount_uDMRdA/usr/bin/libQt5WebEngineWidgets.so.5                                          0x307fd  [0x7f2cc34817fd]
/tmp/.mount_uDMRdA/usr/bin/libQt5Widgets.so.5 QWidget::event(QEvent*)                  0xda2  [0x7f2cc88f8bf2]
/tmp/.mount_uDMRdA/usr/bin/libQt5QuickWidgets.so.5 QQuickWidget::event(QEvent*)             0x19b  [0x7f2cbc1359eb]
/tmp/.mount_uDMRdA/usr/bin/libQt5WebEngineWidgets.so.5                                          0x30b1b  [0x7f2cc3481b1b]
/tmp/.mount_uDMRdA/usr/bin/libQt5Widgets.so.5 QApplicationPrivate::notify_helper(QObject*, QEvent*) 0x9c  [0x7f2cc88b983c]
/tmp/.mount_uDMRdA/usr/bin/libQt5Widgets.so.5 QApplication::notify(QObject*, QEvent*)  0x2a4  [0x7f2cc88c1104]
/tmp/.mount_uDMRdA/usr/bin/lib/PyQt5/QtWidgets.cpython-36m-x86_64-linux-gnu.so                                          0x3ab97e...

**Comment by dwlegg** [comment]
Let me know if there is anything else I can do to narrow this one down, e.g. how to get the daily build to run without crashing.

**Comment by JacksonRG** [comment]
Is there audio when playing the preview?

**Comment by DanPinGF** [comment]
It might be the codec. Try using different export settings.
