### ISSUE TITLE
QT WebEngine slated to return in Qt 6.2

### ISSUE THREAD

**Issue by ferdnyc** [OpenShot/openshot-qt#4166]
Phoronix [noted](https://www.phoronix.com/scan.php?page=news_item&px=Qt-2021-Roadmap) that Qt's [2021 roadmap](https://www.qt.io/blog/qt-roadmap-for-2021) is out, and QtWebEngine is still on it, though it's been pushed back to Qt 6.2. That's scheduled for release around September of this year.

No word on whether either QtWebEngine (official) or QtWebKit (third-party) will be available for Qt 6 when running under MinGW, so I wouldn't hold your breath. But at least for Linux and macOS, we may be able to add Qt 6 compatibility by the end of the year, if they keep their schedule.

**Comment by a17r** [comment]
Is there any ETA for a release ported to Qt5WebEngine? We can't keep Qt5WebKit running for much longer.

**Comment by krop** [comment]
Same question. We removed qtwebkit support in openSUSE's PyQt5 packages.

**Comment by ferdnyc** [comment]
@a17r We've been using QtWebEngine since OpenShot 2.5.0. QtWebKit compatibility is retained, for use on Windows where QtWebEngine doesn't exist (MinGW), but QtWebEngine is the default now.

**Comment by ferdnyc** [comment]
(Also @krop.)

**Comment by ferdnyc** [comment]
Wait, sorry, I'm completely wrong about that. I guess we _haven't_ released since the WebEngine switchover yet!

**Comment by ferdnyc** [comment]
That's... unfortunate, because there have been a _lot_ of other changes made since then, a few of which are fairly new and not quite ready for prime time yet.

My personal preference would be to release a 2.5.2 selectively branched from around 2-3 months ago, incorporating the WebEngine-based Timeline and various other fixes done over the past year, but keeping the bulk of recent major changes simmering in `develop` until the next release.

Not **just** because some of the current code isn't ready to release yet, but because even if it all **WAS** — even if we got everything into release shape by next week — at this point IMHO releasing it all together would be too big. There'd be too many big changes coming at users all at the same time. And most likely, too many followup issues that would end up being dropped because we couldn't keep up with it all ourselves.

But, like I said, that's _**my**_ take, and I'm often in the minority on questions like this. I already floated one proposal for something kind of similar a few months ago, and the reaction was resoundingly unenthusiastic. So I don't really know what the official plan will end up looking like, or if there is one yet. @jonoomph ?

**Comment by krop** [comment]
How are things going? I'm currently cleaning the last packages depending on QtWebkit in openSUSE.

**Comment by ferdnyc** [comment]
No updates, sorry. I'll send email to @jonoomph and see if he can weigh in. Releases aren't my area, he's the only one with that ability. 

(I don't know that I'd release a new version completely on my own even if I _could_,  but I can't so the point is moot.)

**Comment by bnavigator** [comment]
> My personal preference would be to release a 2.5.2 selectively branched from around 2-3 months ago, incorporating the WebEngine-based Timeline and various other fixes done over the past year, but keeping the bulk of recent major changes simmering in `develop` until the next release.

That sounds like a very reasonable approach.

**Comment by krop** [comment]
As there's not much happening, can you point us to a git revision we could use?

**Comment by a17r** [comment]
@krop according to Gentoo maintainer of recently branch containing qtwebengine support is not usable.

**Comment by krop** [comment]
@a17r which branch did you try?

**Comment by ferdnyc** [comment]
Hands off, robot! Qt WebEngine _is_ actually back as promised, with the release of Qt 6.2.

The barriers to porting **OpenShot** to use 6.2 are:

1. PyQt6 dropped all support for the Qt resource file system, handwavingly suggesting that we use Python's [ResourceManager API](https://setuptools.pypa.io/en/latest/pkg_resources.html#resourcemanager-api) (aka `pkg_resources`) instead.
    1. That is normally a very fair suggestion, however our packaging is currently woefully ill-equipped to make use of `pkg_resources` in any workable fashion.
    1. Even if we do make the switch, we'd still need to port all of our `QFile(":/resource/path")` calls to instead use `pkg_resources` to access the necessary files.
    1. This would probably involve setting up each resource path (of which we  have far too many; consolidation of resources would be a necessary prerequisite here) to do a `set_extraction_path()` call at launch, along with a `cleanup_resources()` call added to the application's exit points.
1. There are other deprecated APIs used in both OpenShot and libopenshot that are never coming back to Qt 6. Things like `QRegExp` need to be replaced. Fortunately our uses of those APIs should be very minimal.
