### ISSUE TITLE
Audio will not export on Linux

### ISSUE THREAD

**Issue by mrbrklyn** [OpenShot/openshot-qt#4167]
**Describe the bug**
It doesn't export audio

**Steps to reproduce the behavior:**
1. Go to export video
2. Click on export video
3. Scroll down to nowhere

**Expected behavior**
to export videos with audio

**System Details**

flatbush:[ruben]:~/Downloads$ openshot-qt

Loaded modules from installed directory: /usr/lib/python3.9/site-packages/openshot_qt

QApplication: invalid style override 'gtk' passed, ignoring it.

Available styles: bb10dark, bb10bright, cleanlooks, gtk2, cde, motif, plastique, Oxygen, Windows, Fusion

app:INFO ------------------------------------------------

app:INFO Mon May 31 03:07:12 2021

app:INFO Starting new session

app:INFO ------------------------------------------------

app:INFO OpenShot (version 2.5.1)

app:INFO ------------------------------------------------

app:INFO openshot-qt version: 2.5.1

app:INFO libopenshot version: 0.2.5

app:INFO platform: Linux-5.12.8-artix1-1-x86_64-with-glibc2.33

app:INFO processor:

app:INFO machine: x86_64

app:INFO python version: 3.9.5

app:INFO qt5 version: 5.15.2

app:INFO pyqt5 version: 5.15.4

metrics:ERROR Error determining OS version in metrics.py

language:INFO Qt Detected Languages: ['en-US']

language:INFO LANG Environment Variable: en_US.UTF-8

language:INFO LOCALE Environment Variable:

language:INFO OpenShot Preference Language: Default

project_data:INFO Setting default profile to HD 720p 30 fps

app:INFO Setting font to /usr/lib/python3.9/site-packages/openshot_qt/images/fonts/Ubuntu-R.tt f

logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556

I can hear it in the preview and there everything just works. But not the exported files.

**Log Files**

[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/6568697/openshot-qt.log)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/6568698/libopenshot.log)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by mrbrklyn** [comment]
here is a broken video

http://www.mrbrklyn.com/vids/broken.mp4

**Comment by manofsticks** [comment]
Same here, attempted multiple export options.

**Comment by JacksonRG** [comment]
Have you tried closing openshot before trying to view the exported video? That's been a problem we've seen with a few users

**Comment by trougnouf** [comment]
> Is openshot open when you try viewing the exported video? It may be preventing other audio output.

same issue, no difference.

**Comment by Dyspy** [comment]
What audio codec are you using?

I had a similar issue yesterday and solved it by downgrading ffmpeg to version 4.2.4. It looks like the 4.4 upgrade broke it for me.

**Comment by dkeats** [comment]
Also had to downgrade ffmpeg, and it worked

**Comment by trougnouf** [comment]
ffmpeg 4.4, I tried saving the audio as aac or flac.

Downgrading ffmpeg is not straightforward on Arch Linux, I have to compile a previous version of the package and it fails (due to changing dependencies?). I guess that would be a workaround though, per @Dyspy and @dkeats

**Comment by jose1711** [comment]
Being hit by this issue on my Arch Linux box this is a workaround I used:
```
yay -S downgrade
sudo downgrade x264==3:0.159.r2999.296494a-1 x265==3.4-1 ffmpeg=2:4.2.3-2 dav1d==0.7.1-1 aom==2.0.2-1 srt==1.4.1-1
```
Of course this can break other things depending on the downgraded packages but at least the audio was finally there in the exported file.

**Comment by mitchweaver** [comment]
still an issue. on fedora I can't downgrade any lower than 4.4

**Comment by JacksonRG** [comment]
@mitchweaver While I look into solving this dependency, have you tried running the appimage?

**Comment by atomGit** [comment]
same here - audio is missing when exporting video no matter what i've tried

ffmpeg 4.4
openshot 2.5.1
manjaro/kde

**Comment by JacksonRG** [comment]
We recently implemented a [fix](https://github.com/OpenShot/libopenshot/pull/698) just last week for compatibility with FFMPEG 4.

@atomGit If you're on the current daily build, and experiencing this issue, please let me know. As that would be a big surprise.

**Comment by atomGit** [comment]
hi @JacksonRG - i'm not yet intimately familiar with Linux, but i'm looking in my package manager and i see v2.5.1-4 in the stable repo, which uses libopenshot v0.2.5-10, and openshot-git which is v2.4.4.r601 which i assume is an older version

so i assume the newest version hasn't hit the Manjaro stable repo yet

**Comment by JacksonRG** [comment]
@atomGit I understand. So the software repos are all run differently, and we can't control when the package manager updates to our newest daily build. (You would also have to look up whether you've installed the stable build or the daily build).

To bypass the package manager, and get our latest code, go to the [downloads](https://www.openshot.org/download/) page. There's an AppImage.
