### ISSUE TITLE
Poblem scissors

### ISSUE THREAD

**Issue by Galdino76** [OpenShot/openshot-qt#417]
Hello,
I installed openshot but I can not cut out the clpi because the toolbar there is the icon of scissors. How do you then?
Thank you

**Comment by Bentsman** [comment]
Can I add the scissors to the edit bar. Just above the time line.

**Comment by Galdino76** [comment]
Hello and thanks,
But how do I add the scissors? There are not above it in the timeline.
I attach screenshots
Thank you

![senza titolo 3](https://cloud.githubusercontent.com/assets/23727466/20630408/0bcfc45c-b331-11e6-982a-14b0c9093bcd.jpg)

**Comment by jonoomph** [comment]
Duplicate of https://github.com/OpenShot/openshot-qt/issues/502
