### ISSUE TITLE
playback of any file Video/Audio skipped and was slow (no sound) There was program crash when adding...

### ISSUE THREAD

**Issue by ZodiacSun** [OpenShot/openshot-qt#4173]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev3
- Platform: Windows-8-6.2.9200-SP0
- Processor: Intel64 Family 6 Model 62 Stepping 4, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Skipped this step

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/ruebklsx5v3ayc9cjihjthnojir6vzjp/openshot-qt.zip) (271 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/ruebklsx5v3ayc9cjihjthnojir6vzjp/libopenshot.zip) (194 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by DanPinGF** [comment]
This may be caused by #4303.
