### ISSUE TITLE
Problems with the font size of titles in OpenShot Video Editor

### ISSUE THREAD

**Issue by janmswart** [OpenShot/openshot-qt#4179]
I'm using OpenShot version 2.4.3 on a Linux machine. I am trying to create a title using the template Standard 4. The preset font size seems to be 14. When I click on change font, I can change the font, color and size. However, after I confirm, only the font and color are changed according to my choices. The size is always changed to 11, regardless of my choice. Note that this is different from the present size 14. In fact, just opening the dialog "change font", not changing anything, but only pushing the apply button will already change the size to 11. So effectively, I have only two sizes to my disposal: 14, which has to be blue (the preset color) and the preset font, or 11 (if I want anything else). I have not tried all the other templates but Standard 3 seems to work in the same way.

**Comment by JacksonRG** [comment]
This is a really interesting bug, and thanks for the detail. I'm taking a look.

**Comment by janmswart** [comment]
Thanks. Now that you wrote me back I experimented with it again to
make sure my description is correct and I also exported the video
to see if is the same as the preview, but it seems my description of
the bug is indeed 100% correct. It is of course rather irritating as
changing the size is one of the most basic things one needs. Let me
know if you need any more detail.

Jan


On Tue, 06/08/2021 03:40 AM, JacksonRG ***@***.***> wrote:
> 
This is a really interesting bug, and thanks for the detail. I'm taking a look.

**Comment by JacksonRG** [comment]
You also mentioned a 2.4 version of openshot. Have you verified that this issue persists on a current version?

**Comment by janmswart** [comment]
I had not tried this, but now I downloaded version 2.5.1 in the form of a file that does not
have to be installed. (In contrast, the 2.4.3 version seems to be installed on my Kubuntu system).
The version 2.5.1 behaves similarly, but in a sense worse:
-if I do not change the font, it does not show the title at all.
-if I change the color to white, I get black instead.
But otherwise it is still true that I can change the font (style) but always get the same size.

Pity, because otherwise it is a nice program for beginners like me.


On Tue, 06/08/2021 06:37 PM, JacksonRG ***@***.***> wrote:
> 
You also mentioned a 2.4 version of openshot. Have you verified that this issue persists on a current version?

**Comment by JacksonRG** [comment]
From looking into this, I think it may be we need to carefully select which fonts we include by default. I am seeing similar problems depending on what font I choose. Some don't allow me to change the color, and _most_ don't show up without changing the font at least once.
I haven't seen the **All font sizes result in the same size** that you're experiencing, but for now would recommend switching through fonts (as in courier, sans, etc.) I'll try to figure out if we are giving font options that don't exist on the user's computer.

**Comment by janmswart** [comment]
Sorry for my late reaction to the email below.
I discovered that it is possible to prepare titles as gif images in a different program and then import them into OpenShot.
For me, this is the best solution, but of course for people who are beginners with OpenShot it would still be nice
if the templates from OpenShot worked better...

Best wishes and thanks for your reactions and suggestions,
Jan Swart

On Wed, 06/09/2021 10:06 PM, JacksonRG ***@***.***> wrote:
> 
From looking into this, I think it may be we need to carefully select which fonts we include by default. I am seeing similar problems depending on what font I choose. Some don't allow me to change the color, and most don't show up without changing the font at least once.
> 
I haven't seen the All font sizes result in the same size that you're experiencing, but for now would recommend switching through fonts (as in courier, sans, etc.) I'll try to figure out if we are giving font options that don't exist on the user's computer.

**Comment by JacksonRG** [comment]
Well thanks for pointing it out, and I'm glad you found a solution. If you want to use the Openshot titles editor, I can help troubleshoot the issue.

I'll close this issue for now. But please feel free to reopen it if you'd like more help.
