### ISSUE TITLE
Nomenclature of .qm translation files

### ISSUE THREAD

**Issue by a7k** [OpenShot/openshot-qt#418]
See https://bugzilla.rpmfusion.org/show_bug.cgi?id=4358
and https://wiki.qt.io/How_to_create_a_multi_language_application#File_system_structure_of_the_application

The .qm files are not presented in a standard nomenclature, therefore it's difficult to pick them using standard tools.

**Comment by ctsdownloads** [comment]
Unreproducible, old version of OpenShot
