### ISSUE TITLE
Undo Command Not Working Correctly

### ISSUE THREAD

**Issue by Raziel0315** [OpenShot/openshot-qt#4180]
Was unable to find anything similar

**Describe the bug:**
The undo command doesn't work correctly.  Upon pressing control + Z or selecting Undo from the list, the most recent action is not what is undone.  For me, instead, one of the clips located more toward the beginning of the project gets extended well past its actual length.  Any attempts to undo that problem only creates more, similar problems.

**Steps to reproduce the behavior:**
Use undo command

**Expected behavior:**
Undo should undo the most recent action

**System Details:**
- OpenShot Version [e.g. 2.5.1]: Jun 4, 2021 daily build used
- Operating System / Distro: Windows 10

**Comment by JacksonRG** [comment]
In order to get a better idea of what's happening here, could you:
1. Delete your openshot-qt.log and libopenshot.log files
    - These are usually in  c:\Users\<username>\.openshot-qt\
2. In openshot go to Edit -> Preferences -> Debug
3. Check Debug mode (verbose)
4. Try performing and undoing the action
5. Drag the debug files into a github comment.
This will give us a better idea of what the program is doing.

**Comment by drking-c** [comment]
I can confirm this issue with OpenShot 0.2.6 I did not have this with the previous version

I have deleted all my logfiles and will try to find an instance of this happening. I cannot recreate it with simple cut, move and resize edits on a fresh project. So it either only occurs with some types of edits or some kind of projects. I will keep this ticket updated if I find something.

Two questions:

I have noticed that OpenShot's undo mechanism undoes some actions in multiple steps that are only one step to the user. Is this documented somewhere? That might help me understand what is going on.

Is there a way to cleanup an existing project or check it for inconsistencies? (I remember an issue with Audacity where the project directory got corrupted and the bugs had nothing to do with the observed behavior but with the corrupt project)

PS: I am a newbie to this project, so please educate me on any misbehavior :-)

**Comment by JacksonRG** [comment]
@drking-c 
If this answers your question, there is a feature to restore corrupt projects in most cases.

The undo in multiple steps has been pointed out. And we're discussing the pros and cons of changing how the undo functionality works.

Let me know if there are any other questions!

**Comment by speedytechdev** [comment]
I believe #4419 is the same bug but might have more infomation.
