### ISSUE TITLE
Trying to use openshot in chrome os linux and not working when trying to add a video to the track

### ISSUE THREAD

**Issue by Pusdk8** [OpenShot/openshot-qt#4181]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**

**Expected behavior**
I expected it to work and have no issue with trying to edit a video and export it.

**System Details**
- OpenShot Version: 2.5.1
- libopenshot Version:  0.2.5
- Platform: Linux-5.4.99-12983-g8b7876ab9f5e-x86_64-with-debian-10.9
- Processor: 
- Machine: x86_64
- Python version: 3.4.3
- Qt5 version: 5.2.1
- PyQt5 version: 5.2.1
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: en_US.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Not able to verify issue still exists in daily build

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/974qnv1ndh50bf3956vio8dn0m9kwu2b/openshot-qt.zip) (84 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/974qnv1ndh50bf3956vio8dn0m9kwu2b/libopenshot.zip) (0 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by JacksonRG** [comment]
Just to clarify, the dragging of a clip to the timeline is what isn't working?

**Comment by Pusdk8** [comment]
> Just to clarify, the dragging of a clip to the timeline is what isn't working?

once you drag it over the timeline it crashes and i do nothing while it doenloads i have downloaded like 3 different coppies because it is not add an opener to the start screen

**Comment by KnowHowGaming** [comment]
This has happened to me too. I even reported this bug

**Comment by aaroncraigongithub** [comment]
I had this issue as well, It's a configuration issue with the openssl. I fixed this by adding `SSL_CONF` to my environment, ie:

```
$ export OPEN_SSL=/etc/ssl
```

To make this a permanent addition, add that same line to your `.bashrc` or equivalent.

If for some reason you don't have openssl installed, you can do that by running 
```
$ sudo apt install openssl-dev
```

I'm pasting the output from my terminal session that shows the missing libs error so people searching for that in the future will find the fix here.

```
timeline_webview:INFO SortItems
timeline_webview:INFO UpdateLayerIndex
Auto configuration failed
132842613369728:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libssl_conf.so): libssl_conf.so: cannot open shared object file: No such file or directory
132842613369728:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
132842613369728:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=ssl_conf, path=ssl_conf
132842613369728:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=ssl_conf
QMutex: destroying locked mutex
```

**Comment by BoTheBanana** [comment]
Thank You!
