### ISSUE TITLE
Openshot Crashes When Trying to Preview Sped Up Clip

### ISSUE THREAD

**Issue by PlayerEngineer** [OpenShot/openshot-qt#4183]
When I preview a clip that has been sped up the video editor just crashes instantly.

**Steps to reproduce the behavior:**
1. Go and right-click on a clip.
2. Click on time
3. Set it to Fast, and then Forward
4. Set it to any number.
5. Try to play it
6. Video Editor Crashes

**Expected behavior**
Normally it lags a bit but plays the clip.
**System Details**
- OpenShot Version: 2.5.1-dev3
- libopenshot Version:  0.2.5-dev3
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 126 Stepping 5, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev3-daily-7627-d9ea98eb-92ff6084-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/x1vv3181nuuz8gpl3hz6e7szn0rzwecn/openshot-qt.zip) (8 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by JacksonRG** [comment]
Does this happen with all files and file types types?

**Comment by JacksonRG** [comment]
Also if you enable verbose logging, I may be able to get a better idea of what's going on. Just go to Edit->Preferences->Debug, and check debug verbose mode.

**Comment by PlayerEngineer** [comment]
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/6641125/openshot-qt.log)

Turns out verbose logging was disabled when I used the daily build.
The file type was .mp4

**Comment by DanPinGF** [comment]
Duplicate of #1197, but it fixed for me after resetting OpenShot.
