### ISSUE TITLE
Audio does not play in Windows 10

### ISSUE THREAD

**Issue by XQ22** [OpenShot/openshot-qt#4184]
**Describe the bug:**
When audio is imported onto the track, it is not audible, and causes other processes on the computer to mute.

**Steps to reproduce the behavior:**
1. Import an .mp3 file
2. Place this .mp3 file on the track
3. Press "play" button in preview

**Expected behavior:**
Audio was expected to be audible and to play back.

**System Details:**
- OpenShot Version: 2.5.1-dev3
- Operating System / Distro: Windows 10

**Comment by JacksonRG** [comment]
Thanks for pointing this out! We'll look into it, and I know some audio fixes are currently being worked on. Could you also include your log files?

1. Just go to 
`%userprofile%\.openshot_qt\` and delete `openshot-qt.log` and `libopenshot.log`
1.  Then put your openshot in verbose debug mode
`Edit` -> `Preferences` -> `Debug` -> `Debug Mode (Verbose)`
1. Then recreate the bug.
2. Drag your log files into a comment window on this issue.

**Comment by XQ22** [comment]
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/6643086/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/6643087/openshot-qt.log)

**Comment by JacksonRG** [comment]
Thanks! I'll look these over
