### ISSUE TITLE
while joining videos, OpenShot should be able to preserve the common/minimum video properties automatically.  

### ISSUE THREAD

**Issue by raindropsfromsky** [OpenShot/openshot-qt#4185]
**Describe the new feature:**
Many users want to join videos without any transition effects.
All they want is to preserve the input video quality, and not to get caught in a large number of experiments.

But OpenShot is not designed to carry out this simple task!

Specifically, this happens because of two reasons:
1. Openshot does not copy the properties of the input videos to the output video. <br> It makes you think and select from a different set of parameters. This is confusing.
2. The **Quality** drop-down does not offer "same as input videos" option. <br> Instead,  it offers "High", "medium" and "low". <br> The problem with this is that the user does not know how each option will turn out.<br> Will he lose too much of the quality?<br> So he dare not choose anything other than "High".

Thus even when the input videos have poor quality audio and video, the transcoding makes the output video much larger!

**Describe the solution you'd like:**

Introduce some smart behavior in the **Export Video** dialog:
First of all, tell the user the effect of the **Quality** drop-down. <br> When he selects any option, tell him what would be the size and the quality parameters of the output video. (e.g. resolution, bit rate, etc.).  <br>If he does not like it, he can experiment with the other options, rather than choosing one option blindly.

Secondly, let the **Quality** drop-down list have an additional option called "same as input"
- How OpenShot should behave in two different scenarios
  - If the joined videos have the same properties (size, resolution and bit rates for audio+video), <br>the output video must have the same properties (copy the properties as default values for the output video). <br> In this case, add one more option to the **Quality** drop-down list: "Same as input"
  - If the input videos have different properties, offer two choices: **High** and **low**. <br>If the "high" option is chosen, select the maximum of the input videos. <br>If the "low" option is chosen, select the minimum quality parameters from all input videos.

Thirdly, the path for the output video should be the same folder as input videos <br> If the videos are from different folders, the output video should be placed in the folder of the first video.

Note: In all the above cases, allow the user to edit the default values. <br> But most users will like the default values and press ENTER without editing them.

**Describe alternatives you have considered:**
NA

**Screenshots:** (Optional)

**Comment by JacksonRG** [comment]
There's a lot of cool ideas in here. I'll try to respond to it.

First of all, I think you're onto something. Suggesting the quality and format of the highest quality imported clip would minimize degradation on export, and make the choice simple for users.

With regards to the suggestion that the export path should be the same as the import path:
The trouble is, there's no requirement that all the input videos have to be in the same place, so the software could end up choosing a directory _for_ the user - potentially hiding it somewhere they wouldn't look. To have input and output videos in the same place, the user already has this freedom by starting their project in that folder.

**Comment by raindropsfromsky** [comment]
IMHO the **Preferences** dialog should have a separate tab called "Paths", where the operating directory also should be added. Meaning that whenever we want to import any clip, OpenShot looks there.

Now suppose the user has stored his clips somewhere else.
In that case, Openshot should offer to export the output to- 
(a) the working directory
(b) same as the _first_ import clip

(The user may have collected his clips from various folders. In that case, the best we can do is to offer him to export to the folder where the first clip lies. Optionally, offer the folders of all clips as possible destinations.
