### ISSUE TITLE
Incorrect msgid maker or marker at openshot doc po file

### ISSUE THREAD

**Issue by sebuls** [OpenShot/openshot-qt#4186]
**Question:**
I think that
msgid "Seek to previous maker (if any)"
is typo.
Is maker correct ?
I think marker is correct.

https://translations.launchpad.net/openshot/openshot-docs/+pots/openshot/ko/+translate

**Comment by JacksonRG** [comment]
You're right! Thanks for pointing this out and thanks for all your translating. I'll get the English changed.
