### ISSUE TITLE
There's an ominous aura surrounding release 2.5.1?

### ISSUE THREAD

**Issue by ballsystemlord** [OpenShot/openshot-qt#4187]
```
% du -sh ~/working/openshot-qt
666M    ~/working/openshot-qt
```
This is the first repo to give me that result after a build, so I had to post. ;)
Thanks for the FLOSS SW!

**Comment by ferdnyc** [comment]
\*chuckle* Off-by-one error, it was actually 2.5.*0* that was the release from hell. 😆
