### ISSUE TITLE
Critical: Segfault when exporting video normally.

### ISSUE THREAD

**Issue by ballsystemlord** [OpenShot/openshot-qt#4189]
**Describe the bug:**
Openshot-qt 2.5.1 crashes when trying to export video.

**Steps to reproduce the behavior:**
1. I open my project.
2. I select file menu->export project->export video and then click export video without changing the settings.
4. Openshot-qt dies horribly.

**Expected behavior:**
I expect it to output edited video.

**System Details:**
- OpenShot 2.5.1 (latest) (compiled without any options -- ex: -OINSANITY)
- libopenshot 0.2.5 (latest) (compiled without any options -- ex: -OINSANITY)
- libopenshot-audio 0.2.0 (latest)
- Operating System Devuan (Debian) ascii 2.1 Linux. Latest is Beowulf 3.1.
- cmake/oldstable,now 3.7.2-1
- libasound2-dev 1.1.3-5
- libavcodec-dev 7:3.2.15-0+deb9u2
- libavdevice-dev 7:3.2.15-0+deb9u2
- libavfilter-dev 7:3.2.15-0+deb9u2
- libavformat-dev 7:3.2.15-0+deb9u2
- libavresample-dev 7:3.2.15-0+deb9u2
- libavutil-dev 7:3.2.15-0+deb9u2
- libfdk-aac-dev 0.1.4-2+b1
- libfreetype6-dev 2.6.3-3.2+deb9u2
- libjsoncpp-dev 1.7.4-3
- libmagick++-dev 8:6.9.7.4+dfsg-11+deb9u13
- libswscale-dev 7:3.2.15-0+deb9u2
- libunittest++-dev 1.4.0-3.1
- libx11-dev 2:1.6.4-3+deb9u4
- libxcursor-dev 1:1.1.14-1+deb9u2
- libxinerama-dev 2:1.1.3-1+b3
- libxrandr-dev 2:1.5.1-1
- libzmq3-dev 4.2.1-4+deb9u4
- pkg-config 0.29-4+b1
- python3-dev 3.5.3-1
- python3-zmq 16.0.2-2
- qtmultimedia5-dev 5.7.1~20161021-2
- swig 3.0.10-1.1

**Log Files:**
[openshot-qt.log.gz](https://github.com/OpenShot/openshot-qt/files/6650719/openshot-qt.log.gz)
[libopenshot.log.gz](https://github.com/OpenShot/openshot-qt/files/6650720/libopenshot.log.gz)

**Exception / Stacktrace:**
Ummm, it's not small.
Terminal output: [crash1.txt](https://github.com/OpenShot/openshot-qt/files/6650697/crash1.txt)

This is a critical bug as it stops any and all of my projects from being rendered -- it seems. My project I was working on is very simple. No transitions, some muted audio and an overlay video clip. Unfortunately, I'm unwilling to share it and the mp4 source file.
I'm rendering at 1080p. I'm not doing anything the least bit less that absolutely normal so I can't think of why this wasn't spotted before. Maybe it's a bug in one of the dependencies. It will take me a while to update my OS, though.

Thanks!

**Comment by JacksonRG** [comment]
Thanks for the details on your system, and the log files. I'll look over them.

Does this also occur with the appimage? Also I see you're building from source. Does this still happen if you go back one commit?

**Comment by ballsystemlord** [comment]
Ok, the appimage died as soon as I loaded my project because of some va-api problem. I did not experience this with the self-compiled version.

I'm going to post the relevant files and then changing the preferences.

[libopenshot.log.gz](https://github.com/OpenShot/openshot-qt/files/6652029/libopenshot.log.gz)
[openshot-qt.log.gz](https://github.com/OpenShot/openshot-qt/files/6652028/openshot-qt.log.gz)
[crash2.txt](https://github.com/OpenShot/openshot-qt/files/6652030/crash2.txt)

**Comment by ballsystemlord** [comment]
And changing the preferences also causes it to segfault.
I'll back up the ~/.openshot_qt dir and start from scratch by deleting it.

[crash3.txt](https://github.com/OpenShot/openshot-qt/files/6652040/crash3.txt)
[openshot-qt.log.gz](https://github.com/OpenShot/openshot-qt/files/6652042/openshot-qt.log.gz)
[libopenshot.log.gz](https://github.com/OpenShot/openshot-qt/files/6652044/libopenshot.log.gz)

**Comment by ballsystemlord** [comment]
Ok, the appimage will happily export my project. BUT I can't change a single preference. Not even the keybindings!

I'll test with the older version later.

**Comment by ballsystemlord** [comment]
Since this seems to be GPU related. My GPU is a Radeon HD7770 GHz edition from MSI (I'd love to update it, but the bitcoin miners are crazy people!)

My kernel is:
```Linux Zen-II-x12 5.11.17-nopreempt-AMDGPU-dav12 #5 SMP Sat May 1 02:29:27 UTC 2021 x86_64 GNU/Linux```

I'm using the AMDGPU driver as you can guess.

**Comment by ballsystemlord** [comment]
Ok, I've now tested with version 2.5.0 as you requested. I did not change the library versions (libopenshot and libopenshot-audio).
I'm getting the same crash. The stacktrace looks identical also.

**Comment by JacksonRG** [comment]
Well, thanks for doing that. Makes me curious about the recent changes to libopenshot and libopenshot-audio. If that's the only thing you didn't change, and are still getting the crash

**Comment by ballsystemlord** [comment]
Not that I want to place pressure on you, but is there anything else you need/want me to provide to help you debug this problem?

**Comment by JacksonRG** [comment]
Apologies! I thought this was solved, as you found a way to export your video. I see now that wasn't a full solution, as you couldn't edit your preferences. You also said that you got the same crash when you went back a version on openshot-qt. Have you similarly reverted your versions of libopenshot and libopenshot-audio? That sounds like it could be the source of this.

**Comment by ballsystemlord** [comment]
Libopenshot will not build because it's not including something that it should. I tried to figure it out myself, but it's not too obvious where I can find the definition of AV_HWDEVICE_TYPE_NONE for the file include/FFmpegReader.h.
Thanks!

**Comment by ballsystemlord** [comment]
I am exporting via CPU -- it's not too bad. The comment on the GPU was regarding the AppImage crashes when trying to utilize the preferences I had set with my own hand build version and when trying to access the preferences after removing the .openshot-qt folder from my home dir -- again, this is only with the AppImage.

**Comment by moonstone77** [comment]
Did this get solved as I am having the same issue. Crashes at about 11%.

**Comment by moonstone77** [comment]
Mine didn't like CPU or 59FPS I finally discovered it like MOV 264 and 50 fps. That uploaded. Not happy about it but at least it works.

**Comment by ballsystemlord** [comment]
Unfortunately, the latest appimage requires a slightly newer glibc so I can't test it. I'll try building from source later.

**Comment by ballsystemlord** [comment]
libopenshot-audio and libopenshot require newer versions of alsa's libraries and cmake respectively so I can't test the latest openshot at this time.
I will continue to work towards upgrading my system and then I can get back to you.

**Comment by ballsystemlord** [comment]
I have updated my system. The bug does not persist in the latest release's appimage. I'm assuming building from source would be the same. I'll re-open this if I'm still affected when building from source.
As I originally tested this with both source and appimage, I'm uncertain what SW could possibly have affected the running of the program.
