### ISSUE TITLE
OpenShot won't play (preview) or save (export video)

### ISSUE THREAD

**Issue by foutsy** [OpenShot/openshot-qt#419]
I've used OpenShot many times without issues, but this time, just as I finished a project and went to preview a final time, it returned an error. Then trying to export to video is returned a different error. Restarting the computer, removing the last edit, etc. isn't fixing it. I'm using tracks 2-5, so I tried removing track 1 or 0, but then the program stops responding. I opened the project file in Notepad, and the file itself isn't corrupt. I'm lost for other things to try, and I'm afraid to spend several hours recreating my video for fear it will end up the same way. I'm doing this for a school project so don't have endless time to waste on this. Please help.

Error trying to play the file as a preview:
![image](https://cloud.githubusercontent.com/assets/24214510/20653451/3bad6ba4-b4d3-11e6-9bcc-246bc4f96ba0.png)

Trying to export as a video:
![image](https://cloud.githubusercontent.com/assets/24214510/20653440/0fe8791e-b4d3-11e6-9df8-1fe8a1c4a359.png)

**Comment by DylanC** [comment]
@foutsy - Does this issue occur in OpenShot v2.3.4?

**Comment by DylanC** [comment]
Does not occur in v2.4. Please try again in the latest version.
