### ISSUE TITLE
Video size still too large

### ISSUE THREAD

**Issue by freebrowser1** [OpenShot/openshot-qt#4191]
**Question:**
When setting frame rate to 30fps, size 1920x1080, 8 bits per channel, and bitrate to 1.5Mbit/sec, and using h.264 (libx264) videos are still rather large, e.g. 30MB for a video of 45 seconds.
When I convert it with Handbrake with the same parameters, it is only one third or at most half of the size (10MB in this example) without discernible quality loss.
What am I doing wring ?

**System Details:**
- OpenShot Version [e.g. 2.5.1]:
- Operating System : Both macOS 10.16 BigSur and Ubuntu 18.04 

**Screenshots:** 
<img width="573" alt="Screenshot 2021-06-15 at 17 15 20" src="https://user-images.githubusercontent.com/26625141/122079113-6469b000-cdfd-11eb-8c05-89df0e23ef70.png">
<img width="524" alt="Screenshot 2021-06-15 at 17 15 30" src="https://user-images.githubusercontent.com/26625141/122079123-66337380-cdfd-11eb-8927-260a65ab9efe.png">

**Comment by JacksonRG** [comment]
Thanks for pointing this out. We'll take a look at where the extra data is coming form. Have you experimented at all with changing the audio quality?

**Comment by freebrowser1** [comment]
Audio won't blow up the size of a video file.

48kHz and 192 bits/sec AAC is not exciting in the sense of file size.
![Screenshot 2021-06-17 at 11 30 46](https://user-images.githubusercontent.com/26625141/122370714-94c95f80-cf5f-11eb-95f4-e95e75ba7fb1.png)

**Comment by sunkin351** [comment]
Ok, so, I too have a serious issue with this. A rather extreme case is a 2+ hour MP4 recorded in OBS who's original filesize is 2+ GB. The resulting exported file after editing small snippets **out of the video** is a **14GB MP4**. Whatever you are using for H.264 is crap for compression. OBS was using H.264 and got to less than 3GB.

**Comment by freebrowser1** [comment]
I use Handbrake as postprocessing tool which shrinks video filesize to less than 30%, sometimes even 10% without discernible loss of quality, using the same H.264.

**Comment by sunkin351** [comment]
For how much time it takes to render the final video, cause all we got is CPU rendering options, it's compression really shouldn't be this bad.

**Comment by ykoc** [comment]
Not sure this is a right place to post it, but...
there is another problem in last version with it. After updating to 2.6.0 I found that my resulting files become larger a lot. So I made an experiment - took an old file and reexport it with exactly the same parameters (864x480, H.265, audio 64, video 26 crf) as at the first export. And instead of 25 MB I get a 37 MB file. OK, this prove nothing, so I revert back to 2.5.1 and repeat this procedure - and get 23 MB. There is something definitely wrong with it.

**Comment by ksterne** [comment]
I am finding much of the same problem after updating last week (version 2.6.0) from a version from last year about this same time (unsure of version number).  For comparable length videos, I'm getting 2-3 times the file size with a data rate that's an order of magnitude higher (1288 kbps on latest version versus 131 kbps on older version). I have tried using h.264 and h.265.  OS is Windows 10.

**Comment by ksterne** [comment]
This seems to be introduced with version 2.6.0 as I installed version 2.5.1 on a Windows 10 machine today and did not have this large file size issue.

**Comment by sunkin351** [comment]
I don't agree with the practice of closing stale issues, because the issues themselves are as yet not fixed.
