### ISSUE TITLE
Installing code from github is missing sentry_sdk module in openshot-qt

### ISSUE THREAD

**Issue by pattai** [OpenShot/openshot-qt#4194]
The git clone and the make went without error.  Attempting to launch resulted in: (Ubuntu 20.04 Python 3.8.5)

`Traceback (most recent call last):
  File "src/launch.py", line 73, in <module>
    from classes import info, exceptions
  File "/home/appa/openshot-dev/openshot-qt/src/classes/exceptions.py", line 32, in <module>
    import sentry_sdk
ModuleNotFoundError: No module named 'sentry_sdk'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/launch.py", line 77, in <module>
    from classes import info, exceptions
  File "/home/appa/openshot-dev/openshot-qt/src/classes/exceptions.py", line 32, in <module>
    import sentry_sdk
ModuleNotFoundError: No module named 'sentry_sdk'`

**Comment by ferdnyc** [comment]
Yeah, that's an _external_ third-party module. My PR #4182 will make it at least optional (it'll fail gracefully if it's not available) — I'll merge that now so that this won't interfere with people in the future.

**Comment by ferdnyc** [comment]
Merged, so this shouldn't cause any more problems.

(You can, however, still `pip install sentry_sdk` if you'd like to have Sentry telemetry activated. It sends back anonymous logs and crash reports that help us track problems with the code.)

**Comment by pattai** [comment]
Should i refresh just openshot-qt from git?Sent from my Galaxy
-------- Original message --------From: Frank Dana ***@***.***> Date: 6/21/21  12:55 AM  (GMT-05:00) To: OpenShot/openshot-qt ***@***.***> Cc: pattai ***@***.***>, Author ***@***.***> Subject: Re: [OpenShot/openshot-qt] Installing code from github is missing sentry_sdk module in openshot-qt (#4194) 
Merged, so this shouldn't cause any more problems.
(You can, however, still pip install sentry_sdk if you'd like to have Sentry telemetry activated. It sends back anonymous logs and crash reports that help us track problems with the code.)
