### ISSUE TITLE
Wrong zoom in Windows

### ISSUE THREAD

**Issue by ncabanes** [OpenShot/openshot-qt#4199]
My main computer is a Windows Laptop with a FullHD screen, which is set in Windows Configuration to 150% text size.

This is how I see LibreOffice, very comfortable to use.

![libreOffice](https://user-images.githubusercontent.com/7532180/122781436-1ac30e80-d2b0-11eb-8a5d-4f84646cc641.png)

And this is how I see OpenShot, barely usable. I need to change Windows screen configuration each time I use OpenShot.

![openshot-wrongZoom](https://user-images.githubusercontent.com/7532180/122781559-39c1a080-d2b0-11eb-908a-7017d8681c88.png)

I am testing the latest daily version (OpenShot-v2.5.1-dev3-daily-7635-d9ea98eb-92ff6084-x86_64.exe (64-bit)), but this has been happening for a very long time.

**Comment by USATechDude** [comment]
I have a 4k monitor, and I wanted to change the scaling of OpenShot on my system.  I added the following to my User variables for my account under Advanced system properties in my Windows 10 environment:

`QT_ENABLE_HIGHDPI_SCALING=1`
`QT_SCALE_FACTOR=.875` *(which is equal to Windows scaling of 125%)*

The QT_SCALE_FACTOR seemed backward to me. I initially set the value to 1.5, and OpenShot's screen was huge, equal to 1080p. I changed the value to .5, and the screen was tiny.  I think a Windows value of 150% magnification is a scale factor of .75.  Play with the values until the OpenShot window is properly scaled to your preferences.
