### ISSUE TITLE
Support for a <encoderargs> in presets (let experts tweak to achieve better quality output)

### ISSUE THREAD

**Issue by nwgat** [OpenShot/openshot-qt#42]
Presets passthru arguments that basicly adds alot of stuff like crf support
and every option that ffmpeg has itself from here http://ffmpeg.org/documentation.html

current:
`<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE openshot-export-option>
<export-option>
    <type translatable="True">nwgat.ninja</type>
    <title translatable="True">Nwgat MKV (x264/Opus)</title>
    <videoformat>mkv</videoformat>
    <videocodec>libx264</videocodec>
    <audiocodec>libopus</audiocodec>
    <audiochannels>2</audiochannels>
    <videobitrate
     low="6 Mb/s"
     med="12 Mb/s"
     high="24.00 Mb/s"></videobitrate>
    <audiobitrate
     low="96 kb/s"
     med="169 kb/s"
     high="256 kb/s"></audiobitrate>
    <samplerate>44100</samplerate>
</export-option>`

for the expert i would like to see support for encoderargs that basicly passthrus the content to the encoder like this example

`<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE openshot-export-option>
<export-option>
    <type translatable="True">Constant Rate Factor</type>
    <title translatable="True">arguments support</title>
    <videoformat>mkv</videoformat>
        <encoderargs>-c:v libx264 -preset slow -crf 22 -c:a opus -b:a 169k</encoderargs>
</export-option>`

**Comment by ctsdownloads** [comment]
Thanks for the input, it's been added to the enhancement wishlist.

**Comment by ahxxm** [comment]
+1 supporting args like `-perset` and `-crf` would really help to better control output file
