### ISSUE TITLE
Lines of text in a Title disappear and never return...

### ISSUE THREAD

**Issue by ncabanes** [OpenShot/openshot-qt#4200]
This bug has been there for years, and I've checked that it persists in the last daily snapshot (OpenShot-v2.5.1-dev3-daily-7635-d9ea98eb-92ff6084-x86_64.exe (64-bit)).

The steps to reproduce it are simple:

- Add a Title with several lines, such as Standard 4
- Leave the text in line 3 empty
- Edit the title. Line 3 is totally gone. There is no way to add a third line before the 4th one.

<img width="781" alt="bugOpenshot-titling" src="https://user-images.githubusercontent.com/7532180/122782944-6c1fcd80-d2b1-11eb-8ced-8f5f6da283ce.png">

Yes, I know I can fix it from Inkscape, but that's not the point. Titling is, in my opinion, one of the weakest points in OpenShot, specially if you expect to attract new users looking for easy video editing. Inkscape should be a plus for power users, but not a nightmare for novice users.

**Comment by DanPinGF** [comment]
Try updating to the latest OpenShot (2.6.1); it may have been fixed there.
