### ISSUE TITLE
NVENC encoding option is not appearing in the export menu even though my laptop is equipped with a RTX 3070.

### ISSUE THREAD

**Issue by alaingraham13** [OpenShot/openshot-qt#4204]
Exactly as it is described. 

Here is the exact hardware I'm using;
https://www.box.co.uk/FX516PR-HN002T-ASUS-TUF-DASH-F15-Intel-Core-i7-16GB-RAM_3557456.html
![image](https://user-images.githubusercontent.com/25529451/123243542-0878e880-d4db-11eb-93a2-67c8c06fe984.png)

**Comment by JacksonRG** [comment]
Are you using a daily build AppImage, or the stable 2.5.1?

Also could you include your operating system?

**Comment by alaingraham13** [comment]
I tried both the stable and the daily (at the time that I posted) and the
OS is Windows 10 Home

**Comment by christopher317** [comment]
I'm experiencing the same issue on my gtx 1660 super.

**Comment by USATechDude** [comment]
Hardware acceleration is still experimental in OpenShot Video Editor and primarily only for Linux.  The [latest Daily Build](https://www.openshot.org/download/#daily) supports Intel QSV acceleration in Windows minimally.  We do not have any other hardware acceleration in Windows.
