### ISSUE TITLE
Cannot start AppImage: libpango-1.0.so.0: undefined symbol: g_list_model_get_n_items

### ISSUE THREAD

**Issue by stu** [OpenShot/openshot-qt#4205]
running the latest appimage of 2.5.1

```
Loaded modules from current directory: /tmp/.mount_cwSKuu/usr/bin                                                                                             
         app:INFO ------------------------------------------------                                                                                            
         app:INFO             Thu Jun 24 13:49:44 2021                                                                                                        
         app:INFO               Starting new session                                                                                                          
         app:ERROR OpenShotApp::Import Error: /lib/x86_64-linux-gnu/libpango-1.0.so.0: undefined symbol: g_list_model_get_n_items                             
```

both libpango-1.0-0:amd64 and libpango1.0-0:amd64 are installed.

libpango symlinks to;
```/lib/x86_64-linux-gnu/libpango-1.0.so.0 -> libpango-1.0.so.0.4600.2```

ldd shows no missing dependancies on libpango-1.0

**Comment by stu** [comment]
shifted to daily build. Since this turned out to be a known issue, maybe the project should fix the download and move to a newer build than keeping a broken app as the main download....

**Comment by clemans** [comment]
> shifted to daily build. Since this turned out to be a known issue, maybe the project should fix the download and move to a newer build than keeping a broken app as the main download....

Same thing worked for me... truly annoying. Thanks for the heads up on this one.

**Comment by JacksonRG** [comment]
We understand, and are currently in the process of branching a new release with all the features and bug fixes since the last
