### ISSUE TITLE
openshot 2.5.1 for mac won't open

### ISSUE THREAD

**Issue by patdiddy** [OpenShot/openshot-qt#4206]
**Describe the bug:**
OpenShot version 2.5.1 won't launch. The daily build will open properly though.

**Steps to reproduce the behavior:**
Try to launch openshot 2.5.1 and nothing happens. 
Run "/Applications/OpenShot Video Editor.app/Contents/MacOS/launch-openshot" from a terminal window, and you'll see that there's two "ModuleNotFoundErrors." 
It says "No module named 'openshot_qt'" and "No module named 'PyQt5'"

**Expected behavior:**
Version 2.5.1 should run as promised, but it does not. 

**System Details:**
- OpenShot Version 2.5.1
- Operating System / Distro: macOS 10.15.7 on a MacBook Pro (16-inch, 2019)

**Log Files:**
The log files are from the daily build, not version 2.5.1, so I don't have any to include

**Exception / Stacktrace:**
When I tried to run OpenShot Video Editor.app (version 2.5.1 for mac), it won't load. When I ran it in a terminal window, this is what happens:

 "/Applications/OpenShot\ Video\ Editor.app/Contents/MacOS/launch-openshot"

Traceback (most recent call last):
  File "/Applications/OpenShot Video Editor.app/Contents/MacOS/launch-openshot", line 47, in <module>
    from classes import info
  File "/Applications/OpenShot Video Editor.app/Contents/MacOS/classes/info.py", line 30, in <module>
    from PyQt5.QtCore import QDir
ModuleNotFoundError: No module named 'PyQt5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/OpenShot Video Editor.app/Contents/MacOS/launch-openshot", line 50, in <module>
    import openshot_qt
ModuleNotFoundError: No module named 'openshot_qt'

"/Applications/OpenShot\ Video\ Editor.app/Contents/MacOS/launch.py"

Traceback (most recent call last):
  File "/Applications/OpenShot Video Editor.app/Contents/MacOS/launch.py", line 47, in <module>
    from classes import info
  File "/Applications/OpenShot Video Editor.app/Contents/Resources/classes/info.py", line 30, in <module>
    from PyQt5.QtCore import QDir
ModuleNotFoundError: No module named 'PyQt5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/OpenShot Video Editor.app/Contents/MacOS/launch.py", line 50, in <module>
    import openshot_qt
ModuleNotFoundError: No module named 'openshot_qt'
 

**Screenshots:** (Optional)
N/A

**Comment by JacksonRG** [comment]
Thanks for reporting this. I believe that an update on the MacOS side broke the 2.5.1 version.

We are currently working out any critical bugs from the daily build of openshot for a new stable build. (That will include the many changes made since 2.5.1)

**Comment by USATechDude** [comment]
On my MacBook Pro 16, the script to launch OpenShot is:
 `/Applications/OpenShot Video Editor.app/Contents/MacOS/openshot-qt`

If I need the debug options, then I use this script: 
`/Applications/OpenShot Video Editor.app/Contents/MacOS/launch-mac.sh`
