### ISSUE TITLE
How can I run the Python code bundled with the program? (For automation purposes)

### ISSUE THREAD

**Issue by lordscales91** [OpenShot/openshot-qt#4209]
**Question:**
How can I run the Python code bundled with the program? 
I want to automate a process of merging a set of videos together. I tried to add the `lib` folder to the OS `PATH` environment variable, and also to Python's `sys.path`. Still, when I try to `import openshot` it doesn't find the module. I was trying it with Python 3.7.9.

**System Details:**
- OpenShot Version: 2.5.1
- Operating System / Distro: Windows 10

**Comment by ferdnyc** [comment]
@lordscales91 

The code in this repo is basically just the UI, to write Python code for working with video you'd want to build [OpenShot/libopenshot](/OpenShot/libopenshot) from source, which will create a set of Python bindings for the library.

That's a _fairly_ daunting task on Windows, and requires building in an MSYS2/MinGW environment — we don't support native Windows Python/compilers at this time.

**Comment by ferdnyc** [comment]
(Also, at this time roughly 0% of the UI code is automatable, I'm afraid. All of the PyQt5 code requires a running GUI and there really aren't any scripting hooks present at all.)

Scripting could be done sans UI, using the `openshot.py` bindings module from libopenshot... but it's be very low-level, and completely divorced from the GUI.

**Comment by lordscales91** [comment]
> @ferdnyc 
> That's a _fairly_ daunting task on Windows, and requires building in an MSYS2/MinGW environment — we don't support native Windows Python/compilers at this time.

Yeah, that's _precisely_ what I wanted to avoid. I guess I will have to settle with some macro software like Autohotkey. I just wanted to confirm if there was a cleaner way without involving building the library. Now I see the answer is **no**

Thanks for your info.

**Comment by JacksonRG** [comment]
@lordscales91 In terms of automating your video editing openshot does offer an API that you can run on a server from AWS or Azure that starts at $0.15 per hour.
It would allow you to edit videos in an automated way. (This also works well with openshot desktop. As an example, you can build a template and upload it to render with different files)
