### ISSUE TITLE
Won't even run!

### ISSUE THREAD

**Issue by ingeva** [OpenShot/openshot-qt#421]
I'm running Linux Mint MATE 18, and just downloaded OpenShot 2.1.
It doesn't execute at all, even after setting the execute bit and removing the AppImage extension.
OpenShot 1.4.3 works, but won't start Blender - which works fine when started separately, and the path is set correctly (it's even in PATH).
So - ideas?

**Comment by JtLively** [comment]
Do you receive an error when you attempt to start Blender from Openshot?
Have you tried the newest OpenShot from Openshot.org?

**Comment by jreynojustin** [comment]
As per @JtLively's request we need more information to analyze the issue. Please re-open this when you have more details to give. Thanks for providing feedback!
