### ISSUE TITLE
Windows: OpenShot crashes when trying to open Preferences

### ISSUE THREAD

**Issue by lordscales91** [OpenShot/openshot-qt#4214]
**Describe the bug:**
When trying to open the Preferences Window it crashes.

**Steps to reproduce the behavior:**
1. Go to Edit > Preferences

**Expected behavior:**
The Preferences Window is opened to allow the user changing the preferences.

**System Details:**
- OpenShot Version: 2.5.1
- Operating System / Distro: Windows 10

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

The log files contain some sensible data (Personal names), with the trace provided below it should be enough to determine the issue.

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

```
timeline_webview:INFO UpdateLayerIndex
     ui_util:INFO Initializing UI for dlgPreferences
Hardware decoding device number: 0
Hardware decoding device number: 0
[swscaler @ 0000000017a5d140] Warning: data is not aligned! This can lead to a speed loss
[swscaler @ 0000000017b1b480] Warning: data is not aligned! This can lead to a speed loss
 preferences:WARNING CheckPixel failed testing hardware decoding in preferences (i.e. wrong color found): 3-0
Hardware decoding device number: 1
Hardware decoding device number: 1
 preferences:WARNING CheckPixel failed testing hardware decoding in preferences (i.e. wrong color found): 3-1
Hardware decoding device number: 0
Hardware decoding device number: 0
[h264 @ 0000000012915700] Invalid setup for format dxva2_vld: does not match the type of the provided device context.
 preferences:WARNING CheckPixel failed testing hardware decoding in preferences (i.e. wrong color found): 4-0
Hardware decoding device number: 1
Hardware decoding device number: 1
[h264 @ 0000000012914e00] Invalid setup for format dxva2_vld: does not match the type of the provided device context.
 preferences:WARNING CheckPixel failed testing hardware decoding in preferences (i.e. wrong color found): 4-1
Hardware decoding device number: 0
[AVHWDeviceContext @ 0000000013e85a00] Error setting child device handle: -16
```

**Comment by USATechDude** [comment]
Many problems that OpenShot users experience with the application are resolved by resetting OpenShot to its default settings.  Open your file manager (File Explorer, Finder, Files, etc.) and delete the `C:\Users\(USERNAME)\.openshot_qt` folder (`~/.openshot_qt` in macOS and Linux). Removing this folder removes settings and many things that can, in theory, become corrupt. OpenShot automatically recreates the folder with the default settings when you relaunch the program. This folder is not deleted when the program is uninstalled, so your previous settings are saved, often causing projects to fail.
