### ISSUE TITLE
libp11-kit.so required by AppImage

### ISSUE THREAD

**Issue by smunaut** [OpenShot/openshot-qt#4215]
App image fails to start, looking for libp11-kit.so  in my system libraries (which I don't have).

If it's required by OpenShot, it should be in the AppImage. If it's not required, then none of the libs in the AppImage should link to it ...

**Comment by JacksonRG** [comment]
Thanks for pointing this out!

@ferdnyc I'll be honest, I'm unfamiliar with the packaging formats. Where would I start looking for the AppImage dependencies?

**Comment by smunaut** [comment]
No clue really but it's listed in https://github.com/AppImage/pkg2appimage/blob/83483c2971fcaa1cb0c1253acd6c731ef8404381/excludelist  which is probably why it doesn't end up bundled, but the assumption listed at the beginning "This file lists libraries that we will assume to be present on the host system" is just wrong here, you can have a perfectly working linux system without that library in the host system.

**Comment by JacksonRG** [comment]
I see. Don't know why appimage made that choice. Have you tried installing libp11-kit from your package manger?

**Comment by smunaut** [comment]
I didn't, but I'm sure that'd work ...

**Comment by JacksonRG** [comment]
If that doesn't fix this just let me know. And thanks for finding that list! That's very helpful
