### ISSUE TITLE
org.openshot.OpenShot.desktop shoud not be executable

### ISSUE THREAD

**Issue by drws** [OpenShot/openshot-qt#4217]
**Describe the bug:**
OpenShot's XDG [.desktop file](https://github.com/OpenShot/openshot-qt/blob/develop/xdg/org.openshot.OpenShot.desktop) is unnecessarily marked as executable. These files do not need the execution permission.

**Comment by JacksonRG** [comment]
I'll ask around. As far as I can tell, this works without executable permissions. But I'll try to verify this is safe to change on all distros.
