### ISSUE TITLE
when the project file is exported the video lags

### ISSUE THREAD

**Issue by pault149** [OpenShot/openshot-qt#4224]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 2.5.1-dev3
- libopenshot Version:  0.2.5-dev3
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev3-daily-7766-ed1bee37-c31fac5e-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/m66tn4anaxjujrz57jpxktsi30p5gzwc/openshot-qt.zip) (80 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by JacksonRG** [comment]
Hi, Could you include more information about your bug? What you did leading up to the bug, what version of openshot you're using, what operating system you're using, that sort of thing.
