### ISSUE TITLE
whirpool vs. whirlpool

### ISSUE THREAD

**Issue by scootergrisen** [OpenShot/openshot-qt#4227]
Should "whirpool" be spelled "whirlpool"?
In https://github.com/OpenShot/openshot-qt/blob/develop/src/language/OpenShot/OpenShot_transitions.pot#L363-L364 and the four files in https://github.com/OpenShot/openshot-qt/tree/develop/src/transitions/extra

    whirpool_1.jpg
    whirpool_2.jpg
    whirpool_3.jpg
    whirpool_4.jpg

**Comment by JacksonRG** [comment]
Thanks for pointing this out! Should be a quick fix
