### ISSUE TITLE
Slow clip to 1/8x Crashes OpenShot

### ISSUE THREAD

**Issue by earthuni** [OpenShot/openshot-qt#423]
If you try to slow down the clip to 1/8x speed it crashes the program. Can you fix this?

**Comment by philiplb** [comment]
Same happens here. Sometimes it works, sometimes not.
macOS 10.12.4
Reproduction:
- Add an AV clip to a timeline
- Rightclick on it -> Time -> Slowdown -> Forward -> 1/8

**Comment by DylanC** [comment]
@earthuni - What version of OpenShot was tested? Does the issue happen in v2.3.4?

**Comment by DylanC** [comment]
Could not reproduce in v2.4. Please try the latest version.
