### ISSUE TITLE
i sadly dont have very much of info about this bug- so i cant add images or videos to the tracks anymore it just happened out of nowhere so i cant really help when it comes to files im sorry!

### ISSUE THREAD

**Issue by Emma69Himata** [OpenShot/openshot-qt#4231]
idk how it happened and im not a pro when it comes to files all i know is it happened at about 11 pm while i was animating with openshot it just stopped adding the images and videos to the tracks

**Comment by JacksonRG** [comment]
Did you lock the track you were adding the videos to?

Also in some cases, when dragging, a clip will drop onto the top most track, and be outside the view if you're scrolled down.
