### ISSUE TITLE
Audio problem

### ISSUE THREAD

**Issue by Marniehld** [OpenShot/openshot-qt#4232]
My sound from track 2 is too low when I export the video whereas the audio is find when I listen it on Openshot ( i have 3 tracks, and there are different sound on each ones, but i can only hear the music when i export, and not the audio from others tracks).

Any suggestions ?

Thx.

**Comment by JacksonRG** [comment]
You might want to check the volume, and volume mixing options in the preferences of your audio clips.

Also check the 'enable audio' preference. If you right click it, and try `on` rather than `auto`

**Comment by USATechDude** [comment]
Try downloading and installing the [latest Daily Build](https://www.openshot.org/download/#daily) of OpenShot Video Editor from our website.  Jonathan and the development rewrote the audio libraries to address many of the audio issues we see here, Reddit, and our support website.
