### ISSUE TITLE
Crashes when opening project

### ISSUE THREAD

**Issue by Rickelstein** [OpenShot/openshot-qt#4235]
**Describe the bug**
Openshot closes when I try to open a project i've been working on for many hours. It is large and I could break it into smaller parts, but I must get back to pare it down.

**Steps to reproduce the behavior:**
1.Start Openshot
2. Click on open project
3. Choose project file i've been working on
4. Openshot closes down

**Expected behavior**
Project opens and I can finish it.

**System Details**
- OpenShot Version: 2.5.1-dev3
- libopenshot Version:  0.2.5-dev3
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 61 Stepping 4, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev3-daily-7813-70aedd35-c31fac5e-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/ymbz199o1s38ydtjtmopjj837ucbi7db/openshot-qt.zip) (10 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/ymbz199o1s38ydtjtmopjj837ucbi7db/libopenshot.zip) (20 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by JacksonRG** [comment]
First of all, `%USERPROFILE%\.openshot_qt\recovery\` should have periodic backups of your project. You could try opening one of those.

**Comment by JacksonRG** [comment]
And I'm taking a look at the logs. I'll let you know what I find.

**Comment by Rickelstein** [comment]
Thanks, Jackson. My machine is showing that folder empty. 
I have tried reinstalling openshot several times.

**Comment by JacksonRG** [comment]
Strange. `C:\Users\userName\.openshot_qt\` should be created on startup, and the recovery folder should be created when projects are backed up.

**Comment by Rickelstein** [comment]
The folder C:\Users\userName\.openshot_qt\recovery is there. It's just empty.

**Comment by USATechDude** [comment]
@Rickelstein I may be able to repair your OSP file.  Please attach it to a post in this thread so I may download it.

**Comment by Rickelstein** [comment]
[ISO Class vid zipped.zip](https://github.com/OpenShot/openshot-qt/files/6851415/ISO.Class.vid.zipped.zip)
Will this work? Doesn't seem to like .osp files

**Comment by USATechDude** [comment]
@Rickelstein Thank you.  The ZIP archive worked.  I downloaded the file and extracted it to my computer.  I made several changes to the JSON code and attempted to load the project in OSVE but it crashed my app too.  I am still digging through the OSP code, the console debug text, and the error logs to see if I can find the reason for the crash.

**Comment by Rickelstein** [comment]
Magically, when i tried opening the project yesterday, it worked! Thank you so much for your attention to my issue. I'm not sure how, but I'm back in business. There was a Windows update on my machine earlier in the week, maybe that had something to do with it? Or maybe USATechDude or JacksonRG performed a miracle. I split the project into several smaller projects and will piece them together for the final build. I really like this editor and am beyond elated at being able to continue using it. Thank you again.
