### ISSUE TITLE
Crashes when I try to add a title

### ISSUE THREAD

**Issue by MadEditor** [OpenShot/openshot-qt#4236]
I just downloaded Openshot. When I try to add a title (a regular one, not an animated title) the program just closes right away.
It shows the list with all the titles options and all, but whenever I pick up any of them (to add it or edit it) the program
just crashes. I read somewhere that in order to have working titles I had to install InkScape, and so I did, but it didn't work either.

I am using the version 2.5.1 in windows 10, 64 bits, 8GB of RAM.

I have attached the "log" files, in case it might help.

[libopenshot.zip](https://github.com/OpenShot/openshot-qt/files/6848161/libopenshot.zip)

Here I post a screenshot of the moment right before it crashes:

![Sin título](https://user-images.githubusercontent.com/87704556/126322670-0272f19b-4076-4dc1-8f95-c48a20761d6b.jpg)

I feel kinda dissapointed about this bug because otherwise OpenShot is just what I've been looking for. I hope it can be fixed!

Thanks,

Tygon.

**Comment by JacksonRG** [comment]
Hi, Sorry for the delay. Have you checked if this behavior exists on the daily builds?

You can try downloading it [here](https://www.openshot.org/download/)

**Comment by MadEditor** [comment]
Hi, no problem. Yes, in fact, that was the very first thing I tried right after I noticed the problem, however the daily build did exactly the same.

**Comment by JacksonRG** [comment]
@MadEditor 
Sorry for not replying. I'm supposed to get a notification when an issue gets a new comment. We've updated to 2.6.0 with many bug fixes.

Also in preferences you can ensure that openshot has the correct location for inkscape.
