### ISSUE TITLE
Custom speed

### ISSUE THREAD

**Issue by pofart** [OpenShot/openshot-qt#4239]
How i can make custom speed video? For example 1,25 or 1,75? I read many articles with calculator keyframe, but maybe openshot have something more simple? Thanks for anwser!

**Comment by JacksonRG** [comment]
We can look at a smoother way to do this. However here's what I've found.

1) Right click your clip, and set the speed to normal (1x).
    + This will add a `time` key frame at the end of the video, explicitly indicating that that is the last frame of the video.
2) Note this number.
3) Shorten, or lengthen the video as you like.
4) Set a `time` keyframe at the end of that video (ctrl + rightArrow) to jump to the end of a selected clip

**Comment by JacksonRG** [comment]
I'm currently testing whether the bezier curves will allow time ramping. Let me know if this fixes your issue.
