### ISSUE TITLE
Cpu usage is low when encoding low-res video

### ISSUE THREAD

**Issue by k79e** [OpenShot/openshot-qt#4246]
**Question:**
When encoding a 352x240 video it only use 60% cpu
But a 1024x768 use 80% cpu.
But a ffmpeg command will using 95-96% cpu. (low res)
Why the program don't use more cpu? Lesser cpu usage makes encode slower.
I enabled/disabled parallel encoding but it's no difference.

**System Details:**
- OpenShot Version v2.5.1
- Operating System / Distro: win7 x64

**Comment by OldSpiceAfterHoursDeodorant** [comment]
The CPU may be using minimal power mode. If you don't need more power, it won't use it.

352 is approximately 35% of 1024, and 240 is approximatly 30 percent of 768. so we expect a 30 percent decrease from 100%, which is 70. plus an extra 10 percent margin of error, for extra things it could be doing, we have the answer.

Unfortunately I do not know how to fix it. But the math checks out. try increasing the resolution.

**Comment by JacksonRG** [comment]
There may be a few factors. Openshot might be working as fast as it can, but can only export video as quickly as the computer can fetch the video data from the individual files in your project. At a lower resolution, openshot may be working faster than the data is read.

**Comment by k79e** [comment]
Why not add a feature to use external encoders?
When use other encoder it's always very fast.
