### ISSUE TITLE
Tracks in output video do not line up as they do in the timeline

### ISSUE THREAD

**Issue by Jwolter0** [OpenShot/openshot-qt#4251]
Did the best I could to try to find a report, but found nothing

**Describe the bug:**
When generating a video containing an audio track and a video track (static images), the resulting video is longer that it should be. The audio track is the correct length, but the video track is stretched out by ~10%.

**Steps to reproduce the behavior:**
1. Start a new layout
2. Import an audio file (I used a .ogg file) and one or more image files (.jpg)
3. Add the audio and image files to separate tracks. Transition between two images at a memorable moment in the audio track. End both tracks at the same time marker.
4. Generate video.
5. The visual transition will happen after the memorable moment in the audio track and the audio track will complete before the image track, leaving several seconds of "dead air".

**Expected behavior:**
The audio and video tracks stay synchronized as they were in the layout.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Error occurs for OpenShot-v2.5.1-dev3-daily-7832-70aedd35-c31fac5e-x86_64.AppImage and subsequent versions; error does not occur for OpenShot-v2.5.1-dev3-daily-7813-70aedd35-c31fac5e-x86_64.AppImage and previous versions.
- Operating System / Distro: 
- NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"

**Log Files:**
Rather large log files can be found at https://drive.google.com/drive/folders/18sPLkp5aK1XS6veDRkM-voGbWLPIKnE_?usp=sharing

**Exception / Stacktrace:**
No crash

**Comment by JacksonRG** [comment]
Were your preview settings different than your export settings? Taking a look at the logs, but this is my first thought.

**Comment by Jwolter0** [comment]
The audio sample rate in the preview is 44100, while the export is 48000. If I change the export to match the preview, that does fix the issue. However, this is a change in behavior from previous versions. Which is the correct behavior?

**Comment by Jwolter0** [comment]
Thank you, @JacksonRG!
