### ISSUE TITLE
Image sequence creation

### ISSUE THREAD

**Issue by phillmeup123** [OpenShot/openshot-qt#426]
Hi I have tried to create an image sequence but the option does not come into the drop down menu  when i right click on a .mov  clip. Any ideas why this might be or what I am doing wrong? Please help

**Comment by Sr-Polilla** [comment]
I have the same problem here.

I can export in Debian (Jessie version, with Openshot 1.4.0), but only exports images at 320x240.

With Openshot 2.2.0 the program NOT show any option about export a clip to image sequence.
Tested in Linux (Debian) and Mac (Sierra).

**Comment by simbalion** [comment]
Same, this option simply does not exist, at least in the Windows version. Further, the image sequence option from the export dialog is also non-functional in Windows. So there is apparently no way at all to export images from a video in Windows.

This is why people do not send your money to Microsoft.

**Comment by waystar** [comment]
Can select the options for image sequence, but it results in mp4 file. This is with 2.3.1 on Windows 7, Windows 10 and on Linux Mint 18.1.  

Image export with version 1.4.3 on Linux Mint 18.1 works fine.

**Comment by johnLIC** [comment]
I'm on Centos 7.  I choose image sequence and get an .mp4 file.  I was hoping to find a solution on here.

**Comment by DylanC** [comment]
@phillmeup123 - Does this issue still happen in the daily build or v2.3.4?

**Comment by DylanC** [comment]
@phillmeup123 - Closing duplicate issue here. We will track this in #171
