### ISSUE TITLE
Menu items like "Rotate 90 (Right)" is missing degree "°" sign

### ISSUE THREAD

**Issue by scootergrisen** [OpenShot/openshot-qt#4265]
OpenShot 2.5.1-dev3
Windows 7

Right click a clip and select rotation to see:

    Rotate 90 (Right)
    Rotate 90 (Left)
    Rotate 180 (Flip)

I guess it is not correct to just write the number. 90 what? Degree i presume.
So maybe:

    Rotate 90° (Right)
    Rotate 90° (Left)
    Rotate 180° (Flip)

**Comment by scootergrisen** [comment]
https://github.com/OpenShot/openshot-qt/pull/4266

**Comment by JacksonRG** [comment]
> #4266

Just so you know: If you write something like "Closes: #4265" in your pull request, this issue will automatically close when that PR is merged.
