### ISSUE TITLE
Video plays only audio after uploading to YouTube when the starting clip is a picture (png) and other issues

### ISSUE THREAD

**Issue by IndyDe** [OpenShot/openshot-qt#4267]
Steps to Reproduce :
Issue 1 - After uploading the exported video (mp4) to to the  YouTube , YouTube does not play the video part, it will display a static picture while playing the audio.
1.  Create a project with two 2 simple mp4 videos. 
2.  combine the 2 videos on the same track with a transition  - track 5
3.  add a small picture file to the track 4 to align before the first video on track 5  - NO overlap , NO transition , create a gap about 3 seconds between the picture and video.
4. save and export video.
5. Test Video on Windows (Win 10). video plays as expected. 
6. upload to YouTube. 

Issue 2 - Adding a Transition between the first picture and the video causes audio disturbance in the video that follows.  The disturbance sounds almost like something that an  electric spark produces .  ( this disturbance was apparent on the project replay )

The only way to get rid of this was to remove the transition and create a gap.

**Comment by JacksonRG** [comment]
Hi, could you include the version of openshot, and computer, and operating system you're running them on?
