### ISSUE TITLE
Keyboard shortcut for Play and Pause

### ISSUE THREAD

**Issue by vanimurarka** [OpenShot/openshot-qt#4268]
I am coming to Open Shot VE repeatedly while preparing the transcript for a video (there is a reason why I'm using the OSP file and not the exported video file), and wish there was a keyboard shortcut for Play and Pause of the preview. Would make things faster for me.

**Comment by JacksonRG** [comment]
Hi @vanimurarka, pressing `k` with the timeline selected should play or pause the video preview. If you have other questions about keyboard shortcuts, you can see them in `Edit`, `Preferences`, `Keyboard`

**Comment by JacksonRG** [comment]
Closing, as I believe this is answered. If this isn't working, please feel free to reopen it.

**Comment by ferdnyc** [comment]
In fact, there are something like _**four**_ shortcuts to toggle play/pause. You can press <kbd>k</kbd>, as @JacksonRG mentioned, but there's also _both_ <kbd>↑</kbd> and <kbd>↓</kbd>, as well as <kbd>Space</kbd>. All four of those are customizable in the preferences, if you'd prefer something different.
