### ISSUE TITLE
Playing preview stops sound until OpenShot closed

### ISSUE THREAD

**Issue by Pallieguy** [OpenShot/openshot-qt#4275]
This bug has been somewhat reported, but mine appears to have a unique twist.  On my laptop I will lose all audio once I click the play button on the preview.  I've gone into the audio settings and changed away from "default" to "DirectSound", I can adjust the volume from the sound icon on the task bar and hear the windows noise.  Once I click the play button all the audio dies, no matter the source, my speakers do not work, though there is detectable sound being send to them according to the system playback/volume settings.  The lack of audio remains until I close OpenShot at which point it returns.
If I'm running something with constant noise in the background, IE a youtube video, then clicking play causes a moment of sound lag in the constant source, but then the preview plays at a speed of <1ms/s.

Openshot version 2.5.1
libopenshot 0.2.5
Windows 10 Pro
Happens identically when playing through built in speakers, earphone jack, bluetooth headset or USB headset
i7-9750H
16 GB RAM
500GB SSD that's <50% used

**Comment by JacksonRG** [comment]
Thanks for reporting this. Have you checked if this is fixed by using the current daily build?

**Comment by Pallieguy** [comment]
Sorry for the delayed response.  I tried reinstalling OpenShot-v2.5.1-dev3-daily-7878-8e062b8e-c331fac5e-x86_64.exe from July 29, 2021.

'default' still plays no sound until Openshot is closed.
'DirectSound' slows the playback to <1ms/s, but the audio still works.
'Windows Audio' doesn't actually change the output device.  No error message pops up nor the notification to restart OpenShot when switching to 'Windows Audio'.

Those are my only playback device options.

**Comment by JacksonRG** [comment]
That's very interesting. Thanks for the additional information!
