### ISSUE TITLE
how i make vertical video in openshot

### ISSUE THREAD

**Issue by usmaniazhar** [OpenShot/openshot-qt#4278]
**Question:**
A clear and concise question. Your question should provide enough context and explanation for people to answer it. Avoid excessive background or irrelevant details, as they can obscure your actual question.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your question. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by JacksonRG** [comment]
This will allow you to preview, and export your video in vertical mode

1) Press `ctrl+p` or click 'choose profile' in the tool bar at the top
2) Choose an option starting with 'HD Vertical'
