### ISSUE TITLE
Can’t export audio

### ISSUE THREAD

**Issue by soshimee** [OpenShot/openshot-qt#4279]
Audio gets deleted when I export. I tried all formats and encoders that work. My operating system is Arch Linux.

**Comment by JacksonRG** [comment]
Hi, thanks for reporting this. What version of Openshot are you using? Also what version of ffmpeg does your system have?

**Comment by soshimee** [comment]
I’m pretty sure OpenShot is latest (since I installed it the day I reported this issue from AUR)
FFmpeg was 2.4.4 as far as I can remember

**Comment by JacksonRG** [comment]
That's interesting. `ffmpeg -version` for me shows 4.2.4.

I would try using the daily build appimage to see if this still happens. You can download it [here](https://www.openshot.org/download/). We're currently testing a new release which will contain many fixes, and be added to the various software repositories.

**Comment by soshimee** [comment]
It says for me in `ffmpeg -version` n4.4? I don't even recognize that version.

**Comment by JacksonRG** [comment]
Makes sense. The Appimage is bundled with an appropriate version of ffmpeg. We've added support for ffmpeg versions after 3, so the AUR version should be fixed at release.

**Comment by soshimee** [comment]
Ah, so the AUR is a bit outdated?

**Comment by JacksonRG** [comment]
Ok. We don't yet have a definite time on release, as we're currently working to make it as polished as possible. If you try the daily let me know if your issue persists.

**Comment by makingglitches** [comment]
I can verify this in the rpmfusion version of openshot on Fedora 34,  openshot version 2.5.1
Again for some reason.

**Comment by makingglitches** [comment]
I am noting also that changing the audio codec field to another encoder is not working anymore either since you people reset all the decent folk back to their starting points again. you people are so weird.

libmp3lame in the audio codec selection field used to work.

goddamn it all i want to do is make some fucking tech videos that don't get deleted, for something far different than what all the garbage presently on youtube are doing !!!!

**Comment by JacksonRG** [comment]
@soshimee We've released 2.6.0 (not sure if it's made it to the AUR, but it's on most repos) Additionally, we've added support for later versions of FFMPEG.

If you still have any dependency issues, I'd recommend using the appimage, as it is meant to contain (nearly) all the libraries it needs
