### ISSUE TITLE
Crash after playing a movie for ~5 seconds

### ISSUE THREAD

**Issue by chookapp** [OpenShot/openshot-qt#428]
I'm trying edit an MP4 movie (cutting out some parts). But each time I play the movie (in the "video preview" window for more than 5 seconds, the application crashes.

Here is the stacktrace:

review_thread:INFO previewFrame: 10855
preview_thread:INFO self.player.Position(): 10855
preview_thread:INFO onModeChanged
*** Error in `/usr/bin/python3': malloc(): smallbin double linked list corrupted: 0x00007f384c8ae530 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f395fba37e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x81d61)[0x7f395fbadd61]
/lib/x86_64-linux-gnu/libc.so.6(__libc_malloc+0x54)[0x7f395fbaf5d4]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_Znwm+0x18)[0x7f395baaae78]
/usr/lib/x86_64-linux-gnu/libopenshot.so.9(+0x63bcd)[0x7f3949486bcd]
/usr/lib/x86_64-linux-gnu/libopenshot.so.9(_ZN8openshot12FFmpegReader17CheckMissingFrameEl+0x244)[0x7f394948fb84]
/usr/lib/x86_64-linux-gnu/libopenshot.so.9(+0x707cc)[0x7f39494937cc]
/usr/lib/x86_64-linux-gnu/libgomp.so.1(+0xf3a6)[0x7f394605c3a6]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x770a)[0x7f395fefc70a]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7f395fc3282d]
======= Memory map: ========

**Comment by DylanC** [comment]
@chookapp - Does this issue exist in OpenShot v2.3.4? Please confirm.

**Comment by DylanC** [comment]
Try OpenShot v2.4. The preview is much better and no lag detected in my testing.
