### ISSUE TITLE
Program not responding while exporting

### ISSUE THREAD

**Issue by trashmouthuris** [OpenShot/openshot-qt#4287]
**Describe the bug**
While attempting to export a project, the program will freeze and stop responding at the same progress point every time.

**Steps to reproduce the behavior:**
1. Open project file
2. Click on 'Export Video'
3. Wait for project to export

**Expected behavior**
The video should export without any issues.

**System Details**
- OpenShot Version: 2.5.1
- libopenshot Version:  0.2.5
- Platform: Windows-10-10.0.19041
- Processor: AMD64 Family 23 Model 96 Stepping 1, AuthenticAMD
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev3-daily-7861-8e062b8e-c31fac5e-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/c29pd8fatppm6v5ehooauzs4xhejcxre/openshot-qt.zip) (18 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/c29pd8fatppm6v5ehooauzs4xhejcxre/libopenshot.zip) (8 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Comment by speedytechdev** [comment]
Hi @trashmouthuris , Could you see if this is still a problem in the [daily build](https://www.openshot.org/download/) if not I'm happy to file this as a bug.
