### ISSUE TITLE
English language is used first time after new installation

### ISSUE THREAD

**Issue by scootergrisen** [OpenShot/openshot-qt#4289]
OpenShot 2.5.1-dev3
Windows 7

I had a OpenShot installation with danish language already installed.
After i download and install a newer daily build the first time OpenShot starts after the installation the language is english.
If i quit and start OpenShot again it is danish again.

I would like it to be danish the first time OpenShot starts after an installation.

**Comment by JacksonRG** [comment]
Thanks for letting us know about this. I'll take a look.

Could you include your log files? They may help in finding what happened.

**Comment by scootergrisen** [comment]
I will try again when the next daily build comes.
Seems when choosing "Default" it does not show danish even though i think it did earlier.
Could it be that Default only means "da-DK" and not "da"?

**Comment by scootergrisen** [comment]
Strange.
Now i try installing the same nightly build again and now "Default" gives me the UI in danish (note that LANG Environment Variable does not contain DA now):

    20:17:16 INFO language: Qt Detected Languages: ['da-DK', 'en-US']
    20:17:16 INFO language: LANG Environment Variable: 
    20:17:16 INFO language: LOCALE Environment Variable: 
    20:17:16 INFO language: OpenShot Preference Language: Default

**Comment by scootergrisen** [comment]
Are OpenShot using other folders then these in Windows 7?:

    C:\Program Files (x86)\OpenShot Video Editor\
    C:\Users\[USERNAME]\.openshot_qt\

When i run openshot-qt.exe on a commandline i see a window opening/closing fast.
In the title is [...]git.exe
But it happens fast so i can't see anything in the commandline.

**Comment by scootergrisen** [comment]
Does OpenShot ever set the value of the LANG Environment Variable?

When LANG is set to "DA" with big characters OpenShot will open in english (when language preferences is set til Default).
When LANG is set to "da" with small characters OpenShot will open in danish.

I don't know what causes LANG to be "DA".
Maybe i have set it myself but i don't remember.

Will test again with the next daily build.
It seems like i only get the problem when there is a newer daily build but i could be wrong.

**Comment by scootergrisen** [comment]
I just installed OpenShot-v2.6.0-release-candidate-8000-73b009d3-6a84f7ee-x86_64.exe (64-bit)
With a 32 bit version of OpenShot already installed in case it matters.

At the end of the installation i leave the checkbox checked to launch OpenShot.
OpenShot launches with danish translation.
Log says:

    21:37:27 INFO language: LANG Environment Variable: 

I close OpenShot and launches openshot-qt.exe from the `C:\Program Files\OpenShot Video Editor` folder in explorer. This time OpenShot UI is in english.
Log says:

    21:38:32 INFO language: LANG Environment Variable: DA

Seems to me like OpenShot or something that OpenShot uses is setting the LANG environment variabel on my system to "DA".
Like it is running inside its own environment/sandbox with it's own evironment variables not following what the system have.

I can start cmd.exe and run `set LANG=` and openshot-qt.exe to get danish UI but if i start openshot-qt.exe from explorer it will be in english.
