### ISSUE TITLE
No sound on exported video

### ISSUE THREAD

**Issue by SaptakBhoumik** [OpenShot/openshot-qt#4290]
I'm new to OpenShot and trying to export my first video. When I do, I lose the sound.
There is also a similar issue here https://github.com/OpenShot/openshot-qt/issues/1111 but this solution didn't work for me. I also have the required codecs installed
OpenShot version 2.5.1
Garuda linux

**Comment by JacksonRG** [comment]
Hi, when you run `ffmpeg -version`, what version does it display?

**Comment by JacksonRG** [comment]
Am I understanding correctly that you stop hearing sound from your computer when you export the video?

Or is it that the video that you export is silent?

**Comment by SaptakBhoumik** [comment]
> Hi, when you run `ffmpeg -version`, what version does it display?


I am using version n4.4 of ffmpeg

**Comment by SaptakBhoumik** [comment]
> Am I understanding correctly that you stop hearing sound from your computer when you export the video?
> 
> Or is it that the video that you export is silent?

The video that I export is silent

**Comment by rdoxenham** [comment]
> > Am I understanding correctly that you stop hearing sound from your computer when you export the video?
> > Or is it that the video that you export is silent?
> 
> The video that I export is silent

I downgraded to FFmpeg-libs-4.3 and this resolved the issue for me.

**Comment by SaptakBhoumik** [comment]
> > > Am I understanding correctly that you stop hearing sound from your computer when you export the video?
> > > Or is it that the video that you export is silent?
> > 
> > 
> > The video that I export is silent
> 
> I downgraded to FFmpeg-libs-4.3 and this resolved the issue for me.

How do I downgrade it?

**Comment by SaptakBhoumik** [comment]
> > > Am I understanding correctly that you stop hearing sound from your computer when you export the video?
> > > Or is it that the video that you export is silent?
> > 
> > 
> > The video that I export is silent
> 
> I downgraded to FFmpeg-libs-4.3 and this resolved the issue for me.

It is still not working

**Comment by rdoxenham** [comment]
> > I downgraded to FFmpeg-libs-4.3 and this resolved the issue for me.
> 
> It is still not working

In my ~/.openshot-qt/openshot-qt.log I saw errors with ffpmeg writer, invalid argument. Check that out to see if it shows any errors.

**Comment by grahamwhiteuk** [comment]
I've been having the same problem this morning.  Using the latest development version of Open Shot seems to fix the issue for me, I fired up `OpenShot-v2.5.1-dev3-daily-7878-8e062b8e-c31fac5e-x86_64.AppImage` from the [Downloads Page](https://www.openshot.org/download/) (_Note: you need to hit the "Daily Builds" button to find it_).

**Comment by SaptakBhoumik** [comment]
Ok I will try
