### ISSUE TITLE
Issues using AppImage. The appimage doesn't work.

### ISSUE THREAD

**Issue by Cloud-Mak** [OpenShot/openshot-qt#4295]
**Describe the bug:**
https://youtu.be/XdHv3yyMsBA 
Its bit difficult to epress issues in writing, so I have created this video explaining issues. 

**Steps to reproduce the behavior:**
Run any appimage of latest openshot. 

**System Details:**
- OpenShot Version Get any latest appimage.
- Operating System / Distro: OS: Linux Mint 19.3 Tricia x86_64

**Comment by JacksonRG** [comment]
That's very interesting. Could you include your log files when having that unresponsiveness bug? [Here](https://github.com/OpenShot/openshot-qt/wiki/Issue-Logging) are instructions for getting log files.

**Comment by Cloud-Mak** [comment]
> That's very interesting. And thanks for the video to demonstrate the issue you're having! Could you include your log files when having that unresponsiveness bug? [Here](https://github.com/OpenShot/openshot-qt/wiki/Issue-Logging) are instructions for getting log files.

Sure. Let me try. But as explained in the video....the app just starts hanging from 1st second while running from appimage. So not sure if I click on file/edit menu & turn on log.

**Comment by Cloud-Mak** [comment]
@JacksonRG 
How do I find the log files for appimage of opnshot? App image is just one monolithik file whcih I run directly from my machine. Also, since I have OPS 2.4.1 installed on same system using apt. This app image runs on same machine. So where should I look for logs for appimage run of OPS?
