### ISSUE TITLE
Ton hat ein unerwünschtes Echo

### ISSUE THREAD

**Issue by Jeromir1611** [OpenShot/openshot-qt#4298]
**Beschreiben Sie den Fehler**
Der Ton meiner Videoclips hat beim Abspielen ein unerwünschtes, von mir nicht gewolltes oder ausgewähltes Echo. Ich finde keine Möglichkeit, das abzustellen !

Außerdem funktioniert nach dem Update mit der heutigen Daily Update Datei das Abspielen in der Vorschau nicht mehr.

**Schritte zum Reproduzieren des Verhaltens**
1. Gehe Sie nach '...'
2. Klicken Sie auf '....'
3. Scrollen Sie hinunter nach '....'
4. Sehen Sie den Fehler

**Erwartetes Verhalten**
Eine klare und prägnante Beschreibung dessen, was Sie erwartet haben.

**Systemdetails**
- OpenShot Version: 2.5.1-dev3
- libopenshot Version:  0.2.5-dev3
- Platform: Windows-10-10.0.19041
- Processor: AMD64 Family 21 Model 2 Stepping 0, AuthenticAMD
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['de-DE', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Diesen Schritt übersprungen

**Logdateien**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/i8pu8mhscvv2ewueorouhio65p0i2tk0/openshot-qt.zip) (27 KB)

**Ausnahme / Stapelverfolgung**
```No stacktrace found in log files```

**Bildschirmfotos** (Optional)
Wenn möglich, fügen Sie Screenshots zur unterstützenden Erklärung Ihres Problems hinzu. Sie können Screenshots einfügen,
indem Sie diese kopieren und auf Github einfügen oder durch Drag and Drop zur GitHub-Seite hinzufügen. Alle Bilder sind öffentlich zugänglich, posten Sie deshalb keine Screenshots die persönliche Informationen enthalten.

**Comment by JacksonRG** [comment]
Thanks for letting us know about this! I'll take a look
