### ISSUE TITLE
Very minor: Quit dialog still has menu bar visible

### ISSUE THREAD

**Issue by jarlarntzen** [OpenShot/openshot-qt#43]
When window bar is hovered, the menu bar appears, as it does on every window,  on Ubuntu 14.04 LTS
![openshot-quit confirm](https://cloud.githubusercontent.com/assets/2108412/12366325/bc8088bc-bbda-11e5-9827-b12b4de94f92.png)

**Comment by jonoomph** [comment]
That's weird, I don't get this at all on 14.04. Have you disabled the global menu in Ubuntu?

**Comment by jonoomph** [comment]
![openshot-2-0-ubuntu-14-04](https://cloud.githubusercontent.com/assets/5551883/12375898/1ced5e4c-bc9d-11e5-9129-4304ea766584.png)

This is OpenShot 2.0 running in Ubuntu 14.04 LTS (on my system)

**Comment by jarlarntzen** [comment]
Yeah. Sorry. I should have mentioned that one immediately. I've gone for "Show the menus for a window: In the window's title bar".

**Comment by jonoomph** [comment]
Closing due to not something I can control in OpenShot. =)
