### ISSUE TITLE
Cannot export MP4 H.264 video using any profile

### ISSUE THREAD

**Issue by surfrock66** [OpenShot/openshot-qt#4301]
![Screenshot at 2021-08-07 11-59-31](https://user-images.githubusercontent.com/1345467/128611213-bae2a8a3-811a-4e7e-ab07-5beff90aa57c.png)
![Screenshot at 2021-08-07 11-59-50](https://user-images.githubusercontent.com/1345467/128611215-011cdfa5-ca61-4b6a-aca8-9962edfaa510.png)
![Screenshot at 2021-08-07 12-00-30](https://user-images.githubusercontent.com/1345467/128611216-3dcb55ff-4222-44fb-afaf-b7703a1c1d6b.png)
**Describe the bug**
Using the Debian repository package, the stable appimage, or the daily appimage, I cannot get a video to render at all using an H.264 MP4 profile.  Using the CPU profile, I get an error saying "Hardware device create failed" and using VA-API I get an error saying "Could not create hwdevice."  I do not have an nvidia card.  The output video is exactly the same media format in resolution and framerate as the source video.

**Steps to reproduce the behavior:**
1. Go to render a project, select the profile desired, and hit "Export Video"
2. See error

**Expected behavior**
The video should render

**System Details**
- OpenShot Version: 2.5.1-dev3
- libopenshot Version:  0.2.5-dev3
- Platform: Linux-5.10.0-8-amd64-x86_64-with-debian-11.0
- Processor: 
- Machine: x86_64
- Python version: 3.6.9
- Qt5 version: 5.9.5
- PyQt5 version: 5.10.1
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: en_US.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev3-daily-7891-8e062b8e-c31fac5e-x86_64.AppImage

**Log Files**
- openshot-qt.log: File too small or empty (not uploaded)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/pcf6qgdc5qn9yjvulu01bj7ykugakmji/libopenshot.zip) (22 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)

**Comment by fandres** [comment]
Hello, I'm here to report that I can not export with NVIDIA card:
 Could not create hwdevice
Debian 10 Buster
Openshot 2.6

terminal:
INFO main_window: updateStatusChanged
INFO project_data: Scale all keyframes by a factor of 0.8333333333333334
Encoding Device Nr: 0
INFO export: Error type string: Could not create hwdevice

**Comment by speedytechdev** [comment]
Hi @surfrock66 , Could you see if this is still a problem in the [daily build](https://www.openshot.org/download/) if not I'm happy to file this as a bug.

**Comment by speedytechdev** [comment]
Hi @fandres , Are you saying you're experiencing the same bug or just lost on where to create an issue?

**Comment by fandres** [comment]
Hi @speedytechdev , thanks for responding so soon. It is not the same problem, it is a similar problem, Ok, I will publish a new one and I will be pending, thanks.

**Comment by surfrock66** [comment]
This did not work; interestingly it started this time, but I got the same error about 16% in: 
![Screenshot at 2021-09-01 12-31-46](https://user-images.githubusercontent.com/1345467/131732610-3b436dd5-71c4-40a2-b933-cebf6ad2ea65.png)

**Comment by speedytechdev** [comment]
Hi @surfrock66 , Thank you for that. I will mark this as a bug since it still appears to be happening in daily builds.
