### ISSUE TITLE
Audio Not Synching When Rendering

### ISSUE THREAD

**Issue by Raziel0315** [OpenShot/openshot-qt#4302]
**Describe the bug:**
The audio is not lining up with the video in the rendered file using the newest daily build.
The audio lines up in the editor, but the play file doesn't, no matter what player is used.
I've tried multiple times.  The same thing happens.
Has anyone else noticed this issue?

**Steps to reproduce the behavior:**
Render a file
Check to see if the audio matches up

**Expected behavior:**
Audio should match video

**System Details:**
- OpenShot Version  2.5.1, Aug 5, 21 daily build
- Operating System / Distro: Windows 10

**Screenshots:** (Optional)
Can't really screenshot.

**Comment by secure75** [comment]
Yes, on W10 and Arch linux, the same Problem.

**Comment by Raziel0315** [comment]
I've noticed that the audio in the rendered files is sped up.
I don't know if this was previously known, but it might explain the problem: the sound is going faster than the picture....

**Comment by secure75** [comment]
Yup, do you hava a faster CPU for the sound than for the video :-)
Big Problem :-<
Plz guys fix it <3

**Comment by Raziel0315** [comment]
I didn't change any of those settings.  I used the same settings I've been using for the last 2 years.  Are you saying that adjusting the audio fixes the problem?

**Comment by secure75** [comment]
No sorry that was a gag.
It is a bug an I have the same one on Windows 10 & Arch Linux.

**Comment by secure75** [comment]
These version works for me on Windows.
OpenShot-v2.5.1-dev3-daily-7766-ed1bee37-c31fac5e-x86.exe
OpenShot-v2.5.1-dev3-daily-7770-ed1bee37-c31fac5e-x86_64.exe

**Comment by JacksonRG** [comment]
@secure75 Thanks for finding a build that doesn't have this bug!
