### ISSUE TITLE
no sound if headphone is added or removed

### ISSUE THREAD

**Issue by uselessgames** [OpenShot/openshot-qt#4303]
**Describe the bug:**
Whenever a microphone is plugged in, or unplugged the audio stops working. The preview speed is also slowed down significantly.

Unsure if this is related or separate to #2565 

**Steps to reproduce the behavior:**
1. Open the program with headphones plugged in
2. Preview video / audio, works.
3. remove headphones
4. preview video / audio, the audio does not work and the video is slowed down significantly.
5. no error is returned. only way to fix is to close and re-open the program

**Expected behavior:**
The audio is expected to continue to work as normal and switch between speaker or headphones without any troubles.

**System Details:**
- OpenShot Version 2.5.1 : {{ log_context.openshot_qt_version }}
- Operating System / Distro: Windows 10 Pro

**Log Files:**
n/a, no crash or errors presented

**Exception / Stacktrace:**
n/a, no crash or errors presented

**Screenshots:** (Optional)

**Comment by scottg299** [comment]
I have also experienced this issue. Seems like it just can't handle a change in audio output device while the program is open.

**Comment by speedytechdev** [comment]
Hi @uselessgames @scottg299 , Could you two please tell me if this problem has been fixed in the [daily build](https://www.openshot.org/download/) if not I'm happy to file this as a bug.

**Comment by uselessgames** [comment]
@speedytechdev 
tried daily build v 2.6 64 bit and the problem as originally described above persists.

Additionally, I noticed that the audio was high pitch voice, to fix I had to chnge the project rate to match the audio/video rate, save and restart. easy fix, albeit a bit annoying.

**Comment by uselessgames** [comment]
oh, also, I like the changes to the ui done from 2.5.1 to 2.6 👍

**Comment by JacksonRG** [comment]
@scottg299 Is this bug on windows 10 for you as well?

**Comment by uselessgames** [comment]
I have tested on debian 10 buster (kernel 4.19) and the program performs as expected, no issues there.

@JacksonRG @speedytechdev

**Comment by DanPinGF** [comment]
See also #4376.

**Comment by DanPinGF** [comment]
This problem is still yet to be fixed.

**Comment by alina104** [comment]
You, just need to update the audio driver. Plz, fix this issue. You can get help to updating drivers from the below given links.

https://www.iobit.com/en/knowledge-how-to-fix-no-audio-output-device-is-installed-error-in-windows-11,-10,-8,-7,-xp-133.php
https://www.systweak.com/blogs/how-to-fix-no-audio-output-device-is-installed-in-windows-10/

**Comment by Colorjet3** [comment]
> This problem is still yet to be fixed.

https://trello.com/c/jL7t92qC/36-no-audio-after-resuming-from-sleep-windows

Oops, I incorrectly pasted the link to another issue.  Please test this again with the latest DEV Daily Build of v3.0.0.

Thank you!

**Comment by DanPinGF** [comment]
The crawling issue has been fixed in version 3.0.0, but not the audio problem. Today, when I tried reproducing it on the latest version, playback appeared to be working smoothly, but no sound is being emitted from the Video Preview.

**Comment by Colorjet3** [comment]
Headphones have been a known issue in the Windows environment.  Try, this:
1. Close OpenShot. 
2. Plug-in your headphone.
3.  Test the audio in Windows (outside of OpenShot to ensure it is working).
4.  Start OpenShot and go to Edit | Preferences | Preview.
5.  Check the "Playback Audio Device" and if it is set to Default, click on drop down arrow and find an entry for your headphone.  It will be something like "Windows Audio:  thenameofyourheadphone".  Select it.
6. Restart OpenShot and see if that takes care of the audio issue.
7. You may have to do the reverse if/when you remove the headphone.

**Comment by Colorjet3** [comment]
Hello @DanPinGF .  I am going to close this ticket.  As I mentioned in my previous response, OpenShot does not handle on the fly changes to Windows audio.  If you plug-in or unplug and audio device while OpenShot is running then you will need to restart OpenShot.
