### ISSUE TITLE
Please add some Sample Music and Sample Sound effects for use in videos.

### ISSUE THREAD

**Issue by ghost** [OpenShot/openshot-qt#4305]
Hello all developers of Openshot. I really love Openshot and I use it to edit my videos. However It would be nice if some sample music and sample sound effects were included within the editor like any other video editor. Anyway I also waiting for Openshot 3.0 release 😀😃😊😍🥰. Please add some sample music and sample sound effects for using in video as soon as possible. Thank you 😀😃😊😍🥰.

**Comment by JacksonRG** [comment]
Thanks for the suggestion! And we do have audio effects in the works!
