### ISSUE TITLE
Changing timeline/zoom area width triggers unsaved changes (adds * in title)

### ISSUE THREAD

**Issue by scootergrisen** [OpenShot/openshot-qt#4306]
OpenShot-v2.5.1-dev3-daily-7895-9662bcbe-c31fac5e-x86.exe
Windows 7

If i launch OpenShot and only maximizes the window the unsaved changes star (*) will appear in the title as if i changed something.
But the only thing i did was to maximize the window.

I don't think maximizing the window should trigger some kind of unsaved changes in the content.

Seems like it got something to do with the zoom area in the timeline.
When the timeline dock width is changed the zoom area will automatically change.

![unsaved](https://user-images.githubusercontent.com/1836590/128887943-523c765b-4dae-48a0-9d95-c17b7109ec0c.gif)

**Comment by speedytechdev** [comment]
Hi @scootergrisen , Could you see if this is still a problem in the [daily build](https://www.openshot.org/download/) if not I'm happy to file this as a bug.

**Comment by scootergrisen** [comment]
It's the same in OpenShot-v2.6.0-dev-daily-8190-d58febf1-5ec3bc21-x86_64
