### ISSUE TITLE
OpenShot not exporting audio

### ISSUE THREAD

**Issue by tigerjack** [OpenShot/openshot-qt#4309]
**Describe the bug:**
OpenShot Video Editor, as per the title, is not exporting audio. 

**Steps to reproduce the behavior:**
1. Go to 'Export Video'
2. Click on 'Advanced' > 'Export to': 'Video & Audio'
3. Scroll down to 'Audio Settings' > 'Audio Codec': 'aac'
4. Click on 'Export Video'
5. The output will not have any audio.

**Expected behavior:**
The audio should be there.

**System Details:**
- OpenShot Version: 2.5.1
- Operating System / Distro: ArchLinux
- **ffmpeg version n4.4**

**Log Files:**
Include cli stdout/stderr.
[logs.tar.gz](https://github.com/OpenShot/openshot-qt/files/6966574/logs.tar.gz)

**Comment by JacksonRG** [comment]
Hi, my understanding is that arch uses the most recent FFmpeg version (4+). Openshot 2.5.1 released when most distros' package reopos only had version 3.

To gain the support for version 4, I would reccomend using the daily build. (Or any appimage, as they are bundled with the correct versions of software)

Those files are available [here](https://www.openshot.org/download/)

**Comment by tigerjack** [comment]
> Hi, my understanding is that arch uses the most recent FFmpeg version (4+). Openshot 2.5.1 released when most distros' package reopos only had version 3.
> 
> To gain the support for version 4, I would reccomend using the daily build. (Or any appimage, as they are bundled with the correct versions of software)
> 
> Those files are available [here](https://www.openshot.org/download/)

Thanks. For now I think I will stick to the normal build since I'm not planning to use Openshot again in the next few weeks. Do you know if there's a release plan for the next official version of Openshot?

**Comment by speedytechdev** [comment]
Hi @tigerjack , Could you see if this is still a problem in the [daily build ](https://www.openshot.org/download/) if not I'm happy to file this as a bug.

**Comment by JacksonRG** [comment]
@tigerjack Also, happy to say 2.6.0 is out!

**Comment by tigerjack** [comment]
Sorry for the late reply. I'm on 2.6.1, and I can confirm that it works. Thanks everyone for the effort.

**Comment by speedytechdev** [comment]
Hi @tigerjack , Glad to hear it. Are you happy for me to close this issue? 

Thank You and enjoy the rest of your day.
Speedytechlive - Support Team

**Comment by tigerjack** [comment]
@speedytechdev of course :)

**Comment by zesterer** [comment]
Would it be possible to have OpenShot warn the user about an out of date `ffmpeg`? I just spent quite some time hitting my head against my keyboard wondering why this wasn't working before finding this issue. A simple update fixed the issue, but the program telling me what was wrong would have been extremely useful.

**Comment by iljamm** [comment]
installed 2.6.1 on osx 10.15 and getting the same issue, no audio after export. anything i should try?
