### ISSUE TITLE
Render Freezes Approximately 400 Frames In

### ISSUE THREAD

**Issue by gamefb** [OpenShot/openshot-qt#431]
I have an i7-2660k w/ 16 GB of RAM running Windows 10 and I can't get my video to render all the way. If I set it to render 500 frames, it gets to about 82% and stays there. It will only finish if I set it really short.

**Comment by DylanC** [comment]
@gamefb - Does this issue exist in OpenShot v2.3.4? Please confirm.

**Comment by DylanC** [comment]
No enough detail here for us to test. If you have more detail or even a sample project to show us the issue I can reopen. Thanks.
