### ISSUE TITLE
OpenShot crashes when playing on the Video Preview

### ISSUE THREAD

**Issue by scottg299** [OpenShot/openshot-qt#4319]
**Describe the bug:**
Shortly after opening my existing project and pressing "Play" in the main Video Preview window, I see maybe 1-2 frames of the video, then OpenShot hangs for a few seconds and crashes.

Note, prior to the crash I can easily navigate to anywhere on the timeline and see still frames of the videos that I would expect. I can also right-click on individual project video files and preview them in a separate window, and that works too. So the video files are definitely there and nothing seems to be wrong with them individually.

If I delete everything from the timeline then add the same clips again, I can get it to work. But then when I save an re-open I will get the same problem again and this is clearly not a practical solution!

Note, this is a relatively small/new project with only 3 clips on the timeline so far and 20 clips in the library. So it is not a massive problem to start fresh with a new project and recreate everything, but I wouldn't want to go through the trouble if this is going to keep happening!

I could not reproduce the issue in a totally new project.

Many thanks.

**Steps to reproduce the behavior:**
1. Open existing project
2. Press play on video preview
3. Crash!

**Expected behavior:**
Video plays without crashing.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 2.5.1-dev3
- Operating System / Distro: Windows 10

**Log Files:**
[libopenshot - Copy.log](https://github.com/OpenShot/openshot-qt/files/7002778/libopenshot.-.Copy.log)
[openshot-qt - Copy.log](https://github.com/OpenShot/openshot-qt/files/7002779/openshot-qt.-.Copy.log)

**Exception / Stacktrace:**
None available.

**Screenshots:** (Optional)
N/A

**Comment by dLindley** [comment]
I've been having this same problem for a couple of weeks. I does it on large and small mp4 files.

**Comment by speedytechdev** [comment]
Hi @scottg299 , Could you see if this is still a problem in the [daily build](https://www.openshot.org/download/) if not I'm happy to file this as a bug. Could you do the same please @dLindley . Thank you 😀

**Comment by scottg299** [comment]
Hi @JacksonRG, all my files are on the same drive that OpenShot is installed on. I am afraid I will be away from my workstation for an extended time but I can try to repro with the daily build in a few weeks.

**Comment by DanPinGF** [comment]
If you've just changed OpenShot settings, you're in tough luck now that your pre-existing project has left prior app-wide settings intact. Playing back the project that way will cause MSVCRT.DLL to crash OpenShot, something that appears to be a #1197 ex-Machina kinda thing.

**Comment by DanPinGF** [comment]
Someone's probably gonna have to add a '🔥 hot' label to this issue, if it is affecting everyone using the Windows version.

**Comment by DanPinGF** [comment]
@speedytechdev - HELP!

**Comment by DanPinGF** [comment]
@JacksonRG - I'd probably add this issue to 'Bug Control', since it is very common as of 2.5.1 (probably?).

**Comment by DanPinGF** [comment]
This issue is still yet to be resolved.

**Comment by DanPinGF** [comment]
@JacksonRG - We really need to sort this. I tried playing back one of my older project files in OpenShot, and MSVCRT.DLL crashed it. Do not let stale[bot] close this.

**Comment by AntonSax** [comment]
I'm still experiencing this.

**Comment by Colorjet3** [comment]
Hello @AntonSax What operating system are you running and what version of OpenShot are you running?  For openshot please check Help | About Openshot and let us know if you see v2.6.1-Release-Candidate.

**Comment by AntonSax** [comment]
Windows 10 and yes I'm running the v2.6.1-Release-Candidate.
This [reddit thread](https://www.reddit.com/r/OpenShot/comments/qz67r9/comment/hlkmg4t/) suggests downloading a Dev build. So I'm looking into doing that.

**Comment by AntonSax** [comment]
I've also since downgraded from a profile of HD 1080p 60 fps to QVGA 15 fps while working on the project, but the issue still occurs.

**Comment by Colorjet3** [comment]
Hi @AntonSax .  You are running a very buggy version.  Please go to openshot.org/download/#build and download the latest DEV Daily Build.  Install it and give it a try.  Let us know if this resolved your issue.

**Comment by AntonSax** [comment]
Thanks for the help. Only issue I've had so far is on the latest DEV build, it always plays back the audio at a faster speed than what the track shows. I'm looking for how to resolve that now.

Edit: And it looks like deleting .openshot_qt and restarting OpenShot fixed that.

**Comment by Colorjet3** [comment]
That is awesome @AntonSax .  Most likely the issue with the audio was a mismatch of the sample rate settings between Openshot (Edit | Preference | Preview tab) and the default audio device in Windows.  When you deleted the .openshot_qt folder you also deleted the openshot.settings file which contains the sample rate (most likely set at 44100).  When Openshot recreates it it sets it to 48000 to match what Windows default is now (it used to be 44100 also, but Microsoft changed that a few months back with one of its windows updates).

If you are all satisfied at this point with your configuration please feel free to close this ticket.
