### ISSUE TITLE
images get choppy when added to track

### ISSUE THREAD

**Issue by sehrguey** [OpenShot/openshot-qt#432]
hi,
i'ts debian 8 on a desktop i386, I can't use openshot for anything decent because when I add images to a track they get distorted (patches of negative) both in preview and saved in a video.
I re-installed this OpenShot 1.4.3 via Synaptic (after complete removal) to no avail.
any remedy?

yours`
sehrguey

**Comment by jebeld17** [comment]
I'm having tons of performance issues with OpenShot as well, albeit is x86_64 Windows 10 Pro.
#550

**Comment by sehrguey** [comment]
by me it's only this one. Possibly I screwed it up when playing with the
effects I can't tell for sure; as a workaround I added a user (it's debian
8) and OpenShot did the job I wanted

**Comment by DylanC** [comment]
Closing due to version 1.4 being tested. Focus is now on the v2 series.
