### ISSUE TITLE
./OpenShot-v2.1.0.AppImage -> Segmentation fault

### ISSUE THREAD

**Issue by juckendesAuge** [OpenShot/openshot-qt#433]
./OpenShot-v2.1.0.AppImage 
/tmp/.mount_7PgTCF/usr/bin/openshot-qt.wrapper
Loaded modules from current directory: /tmp/.mount_7PgTCF/usr/bin
Segmentation fault (Speicherabzug geschrieben)

cat /etc/fedora-release 
Fedora release 25 (Twenty Five)

uname -a
Linux localhost.localdomain 4.8.13-300.fc25.x86_64 #1 SMP Fri Dec 9 14:52:00 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ankitpati** [comment]
Dupe of #392.
