### ISSUE TITLE
I feel I must ask... about some rpmfusion dependencies.

### ISSUE THREAD

**Issue by makingglitches** [OpenShot/openshot-qt#4330]
This is not so much a bug as a question and observation.

Why are proj and gdal being imported into a video editing program  as dependencies ?

![Screenshot from 2021-08-20 16-42-25](https://user-images.githubusercontent.com/53788764/130291392-29ab7f61-a8de-4f4a-aafd-8c4875c69423.png)
![Screenshot from 2021-08-20 16-42-33](https://user-images.githubusercontent.com/53788764/130291395-bc0d0550-0d8c-49e2-9714-08780858a235.png)

**Comment by leigh123linux** [comment]
openshot has a weak dep on blender which requires them.

**Comment by ferdnyc** [comment]
And a strong dep on OpenCV (`opencv-core`), which also pulls in both. (It directly requires `gdal-libs`, and _that_ requires `proj`.)
