### ISSUE TITLE
Split Clip on an ISO with 2 Sessions gets confused

### ISSUE THREAD

**Issue by scotsmist** [OpenShot/openshot-qt#4332]
**Describe the bug:**
Import a DVD ISO that has 2 sessions and a menu. Right click and select Split Clip. Cut and save some split clips. In Project Files, the split clip doesn't represent what was created. Its getting mixed up with sessions.

**Expected behavior:**
Expected the split clip to work across several titles on same DVD. Its seeing them, it previews them as one long file, its once the clip is split that there's a mix up.

**System Details:**
- OpenShot Version 2.5.1
- Operating System / Distro: Linux Mint 20.2

**Comment by speedytechdev** [comment]
Hi @scotsmist , Could you include your log files if possible. It will allow our dev team to pinpoint the issue.
