### ISSUE TITLE
Remove beginning of context lines in pot files (#: /home/...)

### ISSUE THREAD

**Issue by scootergrisen** [OpenShot/openshot-qt#4338]
3 of the pot files on https://github.com/OpenShot/openshot-qt/tree/develop/src/language/OpenShot contain lines with context (where the string is found in the source code).

But each line begins with `/home/[USERNAME]/apps/openshot-qt-git/` which does not need to be there.

I sugges changing lines like:

    #: /home/[USERNAME]/apps/openshot-qt-git/src/windows/ui/main-window.ui:987

To:

    #: src/windows/ui/main-window.ui:987

That way it will match the root folder on https://github.com/OpenShot/openshot-qt where src/ is found.

36 characters * 1127 matches = 40572 less characters per language.
Such wow. :dog:

**Comment by speedytechdev** [comment]
Hi @scootergrisen , Thank you for bringing up this improvement. Our dev team will look through this and will contact you if they have any questions or concerns. Enjoy the rest of your day 😀
