### ISSUE TITLE
Add button to open folder after rendering is done

### ISSUE THREAD

**Issue by scootergrisen** [OpenShot/openshot-qt#4339]
OpenShot-v2.6.0-release-candidate-8000-73b009d3-6a84f7ee-x86_64.exe
Windows 7

After opening the export video dialog and the rendering is finish i would like to have a button to open the folder where the file was saved.
I would think many people would be interesting in opening the folder right after to watch the result.

So i don't have to remember the path and open explore and find the folder manually.

Like an "Open folder" button next to the "Done" button.
Perhaps a button that both opens the folder and closes the dialog at the same time. The content of the dialog is disabled anyway so not much to do after a render other then look and close.

Or perhaps add a button next to the "Browse..." button so the user would also be able to open the folder not just select the folder. But then it should not be disabled at the end of the render so the users can't select it.

**Comment by speedytechdev** [comment]
Hi @scootergrisen  , Thank you for bringing up this amazing idea. Our dev team will look through this and will contact you if they have any questions or concerns. Hopefully, you can see it in Openshot one day. Enjoy the rest of your day 😀
