### ISSUE TITLE
distorted images

### ISSUE THREAD

**Issue by sehrguey** [OpenShot/openshot-qt#434]
debian 8 i386, images added to track get choppy in playing back or made into a video. Reinstallation of openshot did'n help
yours`
sehrguey

**Comment by JtLively** [comment]
Can you define _choppy playback_ with images? Is it Openshot or accompanying audio alongside the images in the timeline?

**Comment by sehrguey** [comment]
Audio is OK. images loose some of their parts or rather those parts turn
negative and an image becomes a patch of normal and negative parts.
I attach a screen shot in case  you can open it

**Comment by DylanC** [comment]
@sehrguey - Can you attach a screenshot please?

**Comment by DylanC** [comment]
Ignore my previous comment. Closing due to older version 1.4 being tested. Focus is on v2 series.

**Comment by sehrguey** [comment]
here you are
