### ISSUE TITLE
Common button in Transitions dock is not so useful

### ISSUE THREAD

**Issue by scootergrisen** [OpenShot/openshot-qt#4340]
OpenShot-v2.6.0-release-candidate-8000-73b009d3-6a84f7ee-x86_64.exe
Windows 7

Select Transitions dock.
Switch between Show All and Common.

Selecting Common is not really that useful.
It shows the first 7 transitions which are the same as in Show All and in the same position.

Maybe a few more transitions could be added or something else done to make it more useful then just hiding everything after number 7.

![1](https://user-images.githubusercontent.com/1836590/130377085-85a50f91-1872-4474-8383-9c06a6a340e4.gif)

**Comment by speedytechdev** [comment]
Hi @scootergrisen , Thank you for bringing up this amazing idea. Our dev team will look through this and will contact you if they have any questions or concerns. Hopefully, you can see it in Openshot one day. Enjoy the rest of your day 😀
