### ISSUE TITLE
"No Theme" and "Humanity" looks the same

### ISSUE THREAD

**Issue by scootergrisen** [OpenShot/openshot-qt#4342]
OpenShot-v2.6.0-release-candidate-8041-73b009d3-6a84f7ee-x86_64.exe
 Windows 7

Choose:
Edit
Preferences
Standard theme

Seems to me like the themes "No Theme" and "Humanity" looks the same except the font is slightly different.

![t](https://user-images.githubusercontent.com/1836590/130726612-f48f52e1-c764-4d81-8afd-8a4ef622b00b.gif)

Maybe instead of having:
Default theme: No Theme

Have:
Theme: None

**Comment by speedytechdev** [comment]
Hi @scootergrisen Has the daily build been able to fix this issue? If not I can mark this as a bug and our dev team to check it out.

**Comment by scootergrisen** [comment]
It's the same in OpenShot-v2.6.0-dev-daily-8190-d58febf1-5ec3bc21-x86_64
