### ISSUE TITLE
Slow playback speed

### ISSUE THREAD

**Issue by scootergrisen** [OpenShot/openshot-qt#4343]
OpenShot-v2.6.0-release-candidate-8041-73b009d3-6a84f7ee-x86_64.exe
Windows 7

Playback speed is slow and gets slower frame by frame.
The more frames is played the slower the playback gets.

![1](https://user-images.githubusercontent.com/1836590/130734046-18ae3d5f-e59a-4d48-a143-bf491b0fc4b8.gif)

**Comment by scootergrisen** [comment]
If i start openshot-qt-cli.exe i get the following in the terminal when i open Edit > Preferences dialog.

```
INFO ui_util: Initializing UI for dlgPreferences
Hardware decoding device number: 0
Hardware decoding device number: 0
Hardware decoding device number: 1
Hardware decoding device number: 1
Hardware decoding device number: 0
Hardware decoding device number: 0
[h264 @ 000000002ba98580] Invalid setup for format dxva2_vld: does not match the type of the provided device context.
Hardware decoding device number: 1
Hardware decoding device number: 1
[h264 @ 000000002ba997c0] Invalid setup for format dxva2_vld: does not match the type of the provided device context.
```

In Performance tab there is only "CPU No acceleration" at Hardware Decoder Mode.

**Comment by speedytechdev** [comment]
Hi @scootergrisen , Has the daily build been able to fix this issue? If not I can mark this as a bug and our dev team to check it out.

**Comment by scootergrisen** [comment]
It's the same in OpenShot-v2.6.0-dev-daily-8190-d58febf1-5ec3bc21-x86_64

**Comment by Morphy99** [comment]
Same here Windows 7 x64

**Comment by DanPinGF** [comment]
Duplicate of #4303 - The issue is happening because OpenShot relies on a single audio source in order to output the complete video playback. It cannot detect all audio sources at one time. Putting the system to sleep or disconnecting an in-use audio source induces this problem.

**Comment by DanPinGF** [comment]
@JacksonRG - Looks like a duplicate of #4375.
