### ISSUE TITLE
OpenShot 2.6 Windows 64 Bits does not start / launch

### ISSUE THREAD

**Issue by Quickstepbr** [OpenShot/openshot-qt#4346]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 2.6.0-dev
- libopenshot Version:  0.2.6-dev
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['pt-BR', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.0-dev-daily-8112-fc05893b-5ec3bc21-x86_64.exe

**Log Files**
- openshot-qt.log: File too small or empty (not uploaded)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/l0gn658w80igeaasxih0fymdzglbxr19/libopenshot.zip) (2 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by JacksonRG** [comment]
Hi, It looks like this is an issue with translations. We have made some changes to fix it. Could you try our newest daily build at https://www.openshot.org/download/ ? Please let me know if this doesn't fix it so we can help.

**Comment by ericswpark** [comment]
@JacksonRG I can verify the same issue on my machine. I'm running Windows 10 21H1 (Build 19043), language set to Korean, and the release build on the website (2.6.0) crashes on launch. I see two windows flash briefly and then nothing happens. The log is identical as far as I can see to the ones uploaded by @Quickstepbr.

The newest daily build (OpenShot-v2.6.0-dev-daily-8190-d58febf1-5ec3bc21-x86_64) works fine.

**Comment by Quickstepbr** [comment]
Hi JacksonRG.

I did as you suggested and now it is working.
Thank you for your kind support.

Em ter., 31 de ago. de 2021 às 18:02, JacksonRG ***@***.***>
escreveu:

**Comment by JacksonRG** [comment]
Good to hear! 2.6.1 is coming very soon with this fix!
