### ISSUE TITLE
Cant open openshot

### ISSUE THREAD

**Issue by DosOsi** [OpenShot/openshot-qt#4347]
(Srry for the bad English)
On reinstallation, this error appears after opening, and if I try to open it again, it just doesn't open.

1. Reinstall 
2. And... Error

The program open normally

**System Details**
- OpenShot Version: 2.6.0
- libopenshot Version:  0.2.6
- Platform: Windows-10-10.0.19041
- Processor: x86 Family 6 Model 23 Stepping 10, GenuineIntel
- Machine: x86
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['pt-BR', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.0-dev-daily-8112-fc05893b-5ec3bc21-x86.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/4yi1z63fg8h504cr3jnkgtj8b4f6im22/openshot-qt.zip) (2 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Capturas de Ecrã** (Optional)

![image](https://user-images.githubusercontent.com/89557286/130881717-4cd0e60f-56a8-4592-b093-9942dacf458c.png)

**Comment by JacksonRG** [comment]
We've discovered a bug that caused certain translations of OpenShot to have trouble launching. Could you try launching the daily build and let us know if you still have the problem?
You can download the latest daily build here:
https://www.openshot.org/download/

**Comment by Colorjet3** [comment]
Many issues have been fixed in v3.0.0.  Please download the latest DEV Daily Build and give it a try.
