### ISSUE TITLE
Crop feature is broken

### ISSUE THREAD

**Issue by cagnol** [OpenShot/openshot-qt#4349]
**Describe the bug:**
Project created with version 2.5.1 with a cropped track no longer appears cropped in version 2.6.0

**Steps to reproduce the behavior:**
1. Create a Project with OpenShot 2.5.1
2. Crop one track (set Crop X / Y / Height / Width)
3. Save
4. Open the project with OpenShot 2.6.0

**Expected behavior:**
Track should be cropped.

**System Details:**
- OpenShot Version: 2.6.0 
- Operating System / Distro: MacOS BigSur v11.5.2 (20G95)

**Comment by cagnol** [comment]
No. The feature has disappeared.
![Properties](https://user-images.githubusercontent.com/1852734/131212024-16739040-5b8f-4172-b69e-1eacdc941014.png)

**Comment by JacksonRG** [comment]
@cagnol 
Oh! I see. In 2.6.0 cropping is an effect. You can find it in the effects tab and drop it onto a clip.

**Comment by cagnol** [comment]
Thanks for pointing out the change of location of the crop feature (now a crop effect).

However, the consequence seems to be that all projects created with version 2.5.1 that use the crop feature will not have the expected rendition when they are opened with version 2.6.0.

**Comment by JacksonRG** [comment]
Thats right. We are currently working on translating 2.5.1 crops into the new effects. That fix will be out shortly. But until then, we do have the crop effect

**Comment by Colorjet3** [comment]
Crop is now an actual Effect that you drag onto a clip.  It has been since 2.6.x and beyond.
