### ISSUE TITLE
File Naming Sceme?

### ISSUE THREAD

**Issue by satovey** [OpenShot/openshot-qt#435]
FYI

On your downloads page listed under "Other Windows Downloads"
Files have the naming scheme with x86_64. This is typically designated
as having both the 32 bit and 64 bit versions within the installer.

However, when I attempt to install the following file:
OpenShot-v2.1.0-44-g368f334-49-592-x86_64.exe
The installer stops and issues an error message
stating that it is only for the 64 bit version of Windows.

Please correct this naming scheme so that others are not
mislead into believing that OpenShot will work on 32 bit
versions of windows.

Please follow long standing naming schemes for installers.

**Comment by jonoomph** [comment]
Thanks for the suggestion, but I think it is correctly labeled: https://en.wikipedia.org/wiki/X86-64

**Comment by jonoomph** [comment]
I agree though that it can be confusing, however that naming scheme is used by some of my build software, due to the fact I'm only producing 64 bit versions at this point.

**Comment by satovey** [comment]
Yeah, It's like the guy who disputes that 2 + 2 = 4 because you have apples and oranges.

It's like when developers claim to have a better application and then when you use it, you find out it can't do the things the previous version was able to do.

Leave it up to the advance IT crowd to use a naming scheme that implies one thing yet means something totally different.

I really hate when people do stupid like that.

Is the libopenshot: OpenShot Library 64 bit as well?
If there's a 32 bit version, I may attempt to compile the code for my 32 bit Win7 system.

**Comment by jonoomph** [comment]
The library and all dependencies are currently 64 bit. I might setup a 32-bit build server at some point, if there is enough demand. But so far, I've really only seen limited requests for a 32 bit version.

**Comment by satovey** [comment]
Yeah, It's like the guy who disputes that 2 + 2 = 4 because you have apples and oranges.

It's like when developers claim to have a better application and then when you use it, you find out it can't do the things the previous version was able to do.

Leave it up to the advance IT crowd to use a naming scheme that implies one thing yet means something totally different.

I really hate when people do stupid like that.

Is the libopenshot: OpenShot Library 64 bit as well?
If there's a 32 bit version, I may attempt to compile the code for my 32 bit Win7 system.

**Comment by satovey** [comment]
OK, thanks.
