### ISSUE TITLE
Downloads announced to work with macOS 10.9+ but actually requires 10.15

### ISSUE THREAD

**Issue by Sciss** [OpenShot/openshot-qt#4350]
**Describe the bug:**
The downloads, both 2.6.0 and 'daily' cannot be run on macOS 10.13 (High Sierra), although the website claims the mac downloads need 10.9 or newer. The macOS reports that the application requires at least 10.15 to run. Please provide link to latest version that works on 10.13.

**System Details:**
- OpenShot Version: 2.6.0 via https://www.openshot.org/download/
- Operating System / Distro: macOS 10.13.6 intel 64-bit

<img width="642" alt="Screen Shot 2021-08-26 at 16 31 23" src="https://user-images.githubusercontent.com/131300/130982136-7bb490c5-665e-4b0f-8a5e-a4fa70805e47.png">

**Comment by JacksonRG** [comment]
We've updated web page to accurately show what versions we support.
