### ISSUE TITLE
Video Start Cue Always 00:00:01

### ISSUE THREAD

**Issue by SgtBash** [OpenShot/openshot-qt#4352]
**System Details:**
- OpenShot Version 2.5.1
- Operating System / Distro: Linux Mint 20]

I cannot find a way to start my videos at 00:00:00 no matter what I try, it starts them at 00:00:01
I suspect this is why when I put them on my website, the screen is black until you actually start the video. 
It looks bad to me.

What and where is the adjustment or setting to start the videos at 00:00:00?

Thanks much to anyone with the answer!

**Comment by SgtBash** [comment]
@JacksonRG Upgraded to 2.6.0 same problem. Always starts at 00:00:01 no matter what I do.

**Comment by JacksonRG** [comment]
@SgtBash When Exporting, there should be an option to specify the starting and ending frame of your export. (by default this is supposed go from the first frame to the end). Have you tried specifying `starting frame` in the `Advanced>Advance Options` in the export menu?
