### ISSUE TITLE
Title text does not show up in previews/videos on ChromeOS

### ISSUE THREAD

**Issue by stangri** [OpenShot/openshot-qt#4357]
When I create a new title (logs attached) or open a title creating on another system (macOS), the text of the title is not visible in OpenShot 2.6.0-dev on Chromebook  (version information below), title text is not visible in the preview or the final video.

I've tried re-selecting the font, fore/back-ground colors, I can't get title text to show up.

ChromeOS: Version 92.0.4515.162 (Official Build) (64-bit), 
$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

1. Start OpenShot: ~/OpenShot-v2.6.0-dev-daily-8121-d58febf1-5ec3bc21-x86_64.AppImage
2. Create new title (Ctrl-T or from menu)
3. Select any template
4. Verify that only template graphic shows up, no text is visible whatever you enter in the text field

Expected behavior
Text is visible on the title 

**System Details**
- OpenShot Version: 2.6.0-dev
- libopenshot Version:  0.2.6-dev
- Platform: Linux-5.4.119-14945-gafc97d54f809-x86_64-with-debian-10.10
- Processor: 
- Machine: x86_64
- Python version: 3.6.9
- Qt5 version: 5.9.5
- PyQt5 version: 5.10.1
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: en_US.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.0-dev-daily-8121-d58febf1-5ec3bc21-x86_64.AppImage

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/ym2unwx0a7we66ia62i2sugycnvnk372/openshot-qt.zip) (10 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/ym2unwx0a7we66ia62i2sugycnvnk372/libopenshot.zip) (484 KB)

Screenshots
![image](https://user-images.githubusercontent.com/4768176/131044981-60fae7c9-0c68-4a02-9fdd-f2f114c4eda6.png)

**Comment by speedytechdev** [comment]
Hi @stangri , Thank you for filling out all the info our dev team might need. I have marked this as a bug and hopefully, we can fix this issue for you. Enjoy the rest of your day 😀
