### ISSUE TITLE
openshot freezes on startup

### ISSUE THREAD

**Issue by leigh123linux** [OpenShot/openshot-qt#4358]
openshot freezes on startup

**Steps to reproduce the behavior:**
1. Just starting it is enough

**Expected behavior:**
I expect to be able to dismiss the welcome screen and use app.

**System Details:**
- OpenShot Version 2.6.0
- Operating System / Distro: Fedora 35

**Log Files:**
[openshot-qt.log.zip](https://github.com/OpenShot/openshot-qt/files/7063088/openshot-qt.log.zip)

**Exception / Stacktrace:**
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/openshot_qt/windows/video_widget.py", line 202, in paintEvent
    viewport_rect = self.centeredViewport(self.width(), self.height())
  File "/usr/lib/python3.10/site-packages/openshot_qt/windows/video_widget.py", line 424, in centeredViewport
    return QRect(left_padding, ((height - heightFromWidth) / 2) + top_padding, width, heightFromWidth)
TypeError: arguments did not match any overloaded call:
  QRect(): too many arguments
  QRect(int, int, int, int): argument 1 has unexpected type 'float'
  QRect(QPoint, QPoint): argument 1 has unexpected type 'float'
  QRect(QPoint, QSize): argument 1 has unexpected type 'float'
  QRect(QRect): argument 1 has unexpected type 'float'
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QPaintDevice: Cannot destroy paint device that is being painted
```

**Screenshots:** (Optional)
![screenshot-area-2021-08-26-234829](https://user-images.githubusercontent.com/1299302/131045925-2862637f-1bd4-43d8-bee7-a282299dc061.png)

**Comment by JustAKat** [comment]
Can confirm the same issue, however, OS is Windows 10.

**Comment by speedytechdev** [comment]
Hi @leigh123linux @JustAKat , Has the daily build been able to fix this issue? If not I can mark this as a bug and our dev team to check it out.

**Comment by leigh123linux** [comment]
Latest git code is the same. https://github.com/OpenShot/openshot-qt/commit/443585a474dd297d9fcae47c9be4e1db2f6ad08c

```
INFO app: ------------------------------------------------
INFO app:             Tue Aug 31 14:17:04 2021            
INFO app:               Starting new session              
INFO app: ------------------------------------------------
INFO app:           OpenShot (version 2.6.0-dev)          
INFO app: ------------------------------------------------
INFO app: openshot-qt version: 2.6.0-dev
INFO app: libopenshot version: 0.2.6
INFO app: platform: Linux-5.14.0-0.rc7.54.fc35.x86_64-x86_64-with-glibc2.34
INFO app: processor: x86_64
INFO app: machine: x86_64
INFO app: python version: 3.10.0rc1
INFO app: qt5 version: 5.15.2
INFO app: pyqt5 version: 5.15.4
INFO project_data: Setting default profile to HD 720p 30 fps
INFO language: Qt Detected Languages: ['en-GB']
INFO language: LANG Environment Variable: en_GB.UTF-8
INFO language: LOCALE Environment Variable: 
INFO language: OpenShot Preference Language: Default
INFO logger_libopenshot: Connecting to libopenshot with debug port: 5556
INFO app: Setting font to /usr/lib/python3.10/site-packages/openshot_qt/images/fonts/Ubuntu-R.ttf
INFO app: Setting custom dark theme
INFO ui_util: Initializing UI for MainWindow
INFO webkit: WebKit backend initializing
INFO thumbnail: Starting thumbnail server listening on port 54469
INFO transition_model: updating transitions model.
INFO effects_model: updating effects model.
INFO emoji_model: updating emoji model.
INFO version: Found current version: {'error_rate_unstable': 0.05, 'error_rate_stable': 0.05, 'openshot_version': '2.6.0'}
INFO main_window: InitCacheSettings
INFO main_window: cache-mode: CacheMemory
INFO main_window: cache-limit-mb: 250
INFO main_window: Creating CacheMemory object with 262144000 byte limit
INFO preview_thread: QThread Start Method Invoked
ERROR main_window: Unhandled crash detected: No Log Detected
INFO main_window: updateStatusChanged
INFO main_window: recover_backup
INFO project_data: Setting default profile to HD 720p 30 fps
INFO preview_thread: player Position(): 1
INFO video_widget: Load: Set video widget display aspect ratio to: 1.7777777910232544
INFO video_widget: Set video widget pixel aspect ratio to: 1.0
INFO main_window: updateStatusChanged
INFO webkit: Registering objects with WebKit
INFO preview_thread: player Position(): 1
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/openshot_qt/windows/video_widget.py", line 202, in paintEvent
    viewport_rect = self.centeredViewport(self.width(), self.height())
  File "/usr/lib/python3.10/site-packages/openshot_qt/windows/video_widget.py", line 424, in centeredViewport
    return QRect(left_padding, ((height - heightFromWidth) / 2) + top_padding, width, heightFromWidth)
TypeError: arguments did not match any overloaded call:
  QRect(): too many arguments
  QRect(int, int, int, int): argument 1 has unexpected type 'float'
  QRect(QPoint, QPoint): argument 1 has unexpected type 'float'
  QRect(QPoint, QSize): argument 1 has unexpected type 'float'
  QRect(QRect): argument 1 has unexpected type 'float'
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QPaintDevice: Cannot destroy paint device that is being painted
```

**Comment by leigh123linux** [comment]
@ferdnyc

**Comment by ferdnyc** [comment]
Assuming this isn't already fixed in 2.6.1, I'll take a look.

**Comment by leigh123linux** [comment]
@ferdnyc  2.6.1 is the same.

https://github.com/OpenShot/openshot-qt/issues/4358#issuecomment-909231061

**Comment by leigh123linux** [comment]
I believe python-3.10 changes have caused the issue.

https://docs.python.org/3.10/whatsnew/3.10.html

**Comment by ferdnyc** [comment]
@leigh123linux 
Yeah, I was about to comment the same thing, after reading the traceback. Everything works fine in Python 3.9, but 3.10 blows up.

I've known for a while that we were taking advantage of Python's automatic float<->int conversion in a lot of places (Python3.8/3.9 would emit warnings to that effect, with debugging enabled), and they've been _saying_ for a while that it's going away, but it looks like they finally pulled the trigger. 

The unfortunate thing is, even our Codacy scanning can't catch these, as it doesn't have the definitions of the PyQt5 methods to type-check their arguments. 

Still, I'll try to dig through the code and fix what I can find, starting with the `QRect()` calls.

**Comment by ferdnyc** [comment]
\*grumble\* This would be a lot easier to attack with a working F35 beta release, I could just install it in a VM. Originally that was supposed to happen this coming Tuesday, but it got pushed back at least another week. (Which makes it more difficult to test this, since I don't have a machine with Python 3.10 installed as the default system Python.)

There's a non-default Python 3.10 package for Fedora 34, and I'm compiling libopenshot inside a venv created with it now. To my surprise, CMake's UseSWIG seems to handle that just fine, and configured to build for and use 3.10 automatically. So, I should still be able to test under Python 3.10.

**Comment by leigh123linux** [comment]
> *grumble* This would be a lot easier to attack with a working F35 beta release, I could just install it in a VM. Originally that was supposed to happen this coming Tuesday, but it got pushed back at least another week. (Which makes it more difficult to test this, since I don't have a machine with Python 3.10 installed as the default system Python.)
> 
The cinnamon pre-beta iso should work ok, it installed and works fine here on bare-metal.

https://koji.fedoraproject.org/koji/buildinfo?buildID=1834473

**Comment by ferdnyc** [comment]
@leigh123linux Thanks, I've been getting by just running in Python 3.9 with warnings enabled (`PYTHONWARNINGS=always` set in the environment), which makes it spew `DeprecationWarning`s every time there's an implicit conversion that will fail in Python 3.10.

Spoiler: We have a **lot** of those. (And the worst part is, I'll never be able to guarantee I've found _all_ of the ones hiding down rarely-used code paths, since the warnings are only emitted when the code is actually executed. Wow, do I _really_ wish this codebase actually had unit tests, now.)
