### ISSUE TITLE
Still Can't Drag and Drop File from File Explorer to OpenShot

### ISSUE THREAD

**Issue by daslooney** [OpenShot/openshot-qt#4359]
**Describe the bug**
Cannot drag and drop files from Windows File Explorer to OpenShot 
**Steps to reproduce the behavior:**
1. Launch OpenShot
2. Open Directory where files are to be used
3. Select file with mouse
4. Click and drag to OpenShot
5. See the same old no symbol that's plagued this program for years. Sorry that's not helpful but continued issue sucks.

**Expected behavior**
Expected it to work. Didn't. Can't really say I was expecting it to work, I almost never does for years.

**System Details**
- OpenShot Version: 2.6.0-dev
- libopenshot Version:  0.2.6-dev
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 63 Stepping 2, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.0-dev-daily-8138-d58febf1-5ec3bc21-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/y724vnz4bqbuhd4vpxc4w3m4gccey7kl/openshot-qt.zip) (125 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/y724vnz4bqbuhd4vpxc4w3m4gccey7kl/libopenshot.zip) (87 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by daslooney** [comment]
[UPDATE] Problem occurs if OpenShot is run in ADMINISTRATION mode. Don't understand why this would affect drag and drop but it does. Run normally drag and drop works. Perhaps this could be investigated.

**Comment by speedytechdev** [comment]
> [UPDATE] Problem occurs if OpenShot is run in ADMINISTRATION mode. Don't understand why this would affect drag and drop but it does. Run normally drag and drop works. Perhaps this could be investigated.

Thank you for that @daslooney I will mark that and hopefully, our team can fix that. Sorry for the continued issue hopefully we can have this fixed for you.

**Comment by speedytechdev** [comment]
Hi @daslooney , So I spoke to our dev team about this. They suggest you run Windows File Explorer as administrator, it will allow you to use drag n drop. Unfortunately, this might take some time for our team to look into a permanent solution since it's a difficult issue to fix.  Sorry for any inconvenience this has caused you. Thank you for your help, our team will contact you if we need anything else. Enjoy the rest of your day 😀

**Comment by daslooney** [comment]
Thank you for the help, speedy! I'll do that for now. Appreciate it!

**Comment by speedytechdev** [comment]
No worries, Happy to help 😀

**Comment by Keex0r** [comment]
This is a normal behavior of Windows. Basically processes with lower privileges (Windows Explorer is run in non-admin mode) can't send messages to processes with higher privileges (e.g. Openshot in Admin mode). It's a security measure. These messages are required for drag & drop. So I doubt there is much that can be changed.
You can see that by e.g. opening an admin command shell, run explorer.exe from there (so explorer runs in admin mode as well). Then you can again drag & drop files to Openshot.
The best course of action is probably to not run Openshot as Admin in the first place. Don't see why that would be required.

**Comment by JacksonRG** [comment]
@Keex0r Thanks for the info! Good to know why this happens. It's out of our hands.
