### ISSUE TITLE
Failure to launch v2.2.0 on Ubuntu 16.04

### ISSUE THREAD

**Issue by clockworkpc** [OpenShot/openshot-qt#436]
OS: Ubuntu 16.04

Just cloned from Github.

Executed: sudo python3 launch.py from openshot-qt/src/ folder

Terminal output:

Loaded modules from current directory: /home/alexander/Downloads/openshot-qt/src
      launch:INFO ------------------------------------------------
      launch:INFO    OpenShot (version 2.2.0)
      launch:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.2.0
         app:INFO libopenshot version: 0.1.2
         app:INFO platform: Linux-4.4.0-53-generic-x86_64-with-Ubuntu-16.04-xenial
         app:INFO processor: x86_64
         app:INFO machine: x86_64
         app:INFO python version: 3.5.2
         app:INFO qt5 version: 5.5.1
         app:INFO pyqt5 version: 5.5.1
    language:INFO Attempting to load qt_en_AU.UTF-8 in '/usr/share/qt5/translations'
    language:INFO Attempting to load qt_en in '/usr/share/qt5/translations'
    language:INFO Attempting to load en_AU.UTF-8/LC_MESSAGES/OpenShot in '/home/alexander/Downloads/openshot-qt/src/locale'
    language:INFO Attempting to load en/LC_MESSAGES/OpenShot in '/home/alexander/Downloads/openshot-qt/src/locale'
    language:INFO Attempting to load qt_en_AU in '/usr/share/qt5/translations'
    language:INFO Attempting to load qt_en in '/usr/share/qt5/translations'
    language:INFO Attempting to load en_AU/LC_MESSAGES/OpenShot in '/home/alexander/Downloads/openshot-qt/src/locale'
    language:INFO Successfully loaded en_AU/LC_MESSAGES/OpenShot in '/home/alexander/Downloads/openshot-qt/src/locale'
    language:INFO Qt Detected Languages: ['en-AU', 'en']
    language:INFO LANG Environment Variable: en_AU.UTF-8
    language:INFO LOCALE Environment Variable: en_AU
    language:INFO Attempting to load qt_en_AU.UTF-8 in '/usr/share/qt5/translations'
    language:INFO Attempting to load qt_en in '/usr/share/qt5/translations'
    language:INFO Attempting to load qtbase_en_AU.UTF-8 in '/usr/share/qt5/translations'
    language:INFO Attempting to load qtbase_en in '/usr/share/qt5/translations'
    language:INFO Attempting to load qt_en_AU.UTF-8 in '/home/alexander/Downloads/openshot-qt/src/locale/QT'
    language:INFO Attempting to load qt_en in '/home/alexander/Downloads/openshot-qt/src/locale/QT'
    language:INFO Attempting to load qtbase_en_AU.UTF-8 in '/home/alexander/Downloads/openshot-qt/src/locale/QT'
    language:INFO Attempting to load qtbase_en in '/home/alexander/Downloads/openshot-qt/src/locale/QT'
    language:INFO Attempting to load en_AU.UTF-8/LC_MESSAGES/OpenShot in '/home/alexander/Downloads/openshot-qt/src/locale'
    language:INFO Attempting to load en/LC_MESSAGES/OpenShot in '/home/alexander/Downloads/openshot-qt/src/locale'
    language:INFO Attempting to load qt_en_AU in '/usr/share/qt5/translations'
    language:INFO Attempting to load qt_en in '/usr/share/qt5/translations'
    language:INFO Attempting to load qtbase_en_AU in '/usr/share/qt5/translations'
    language:INFO Attempting to load qtbase_en in '/usr/share/qt5/translations'
    language:INFO Attempting to load qt_en_AU in '/home/alexander/Downloads/openshot-qt/src/locale/QT'
    language:INFO Attempting to load qt_en in '/home/alexander/Downloads/openshot-qt/src/locale/QT'
    language:INFO Attempting to load qtbase_en_AU in '/home/alexander/Downloads/openshot-qt/src/locale/QT'
    language:INFO Attempting to load qtbase_en in '/home/alexander/Downloads/openshot-qt/src/locale/QT'
    language:INFO Attempting to load en_AU/LC_MESSAGES/OpenShot in '/home/alexander/Downloads/openshot-qt/src/locale'
    language:INFO Successfully loaded en_AU/LC_MESSAGES/OpenShot in '/home/alexander/Downloads/openshot-qt/src/locale'
    language:INFO Exiting translation system (since we successfully loaded: en_AU)
project_data:INFO Setting default profile to HDV 720 24p
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
         app:INFO Setting font to /home/alexander/Downloads/openshot-qt/src/images/fonts/Ubuntu-R.ttf
         app:INFO Setting custom dark theme
link SVGID_18_-5 hasn't been detected!
link SVGID_18_-5 hasn't been detected!
link SVGID_22_-5 hasn't been detected!
link SVGID_24_-2 hasn't been detected!
link SVGID_24_-2 hasn't been detected!
     metrics:INFO Track metric: {'x-content-type-options': 'nosniff', 'expires': 'Mon, 01 Jan 1990 00:00:00 GMT', 'access-control-allow-origin': '*', 'status': '200', 'content-length': '35', 'last-modified': 'Sun, 17 May 1998 03:00:00 GMT', 'date': 'Wed, 21 Dec 2016 00:28:53 GMT', 'cache-control': 'no-cache, no-store, must-revalidate', 'server': 'Golfe2', 'pragma': 'no-cache', 'content-type': 'image/gif', 'age': '45622', 'content-location': 'http://www.google-analytics.com/collect?an=OpenShot+Video+Editor&tid=UA-4381101-5&t=screenview&cd4=5.5.1&cd5=Ubuntu-16.04-xenial&cd3=5.5.1&cd2=3.5.2&ua=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&av=2.2.0&aid=org.openshot.openshot-qt&cd1=0.1.2&cd=initial-launch-screen&v=1&ul=en-au&aip=1&cid='} (b'GIF89a\x01\x00\x01\x00\x80\xff\x00\xff\xff\xff\x00\x00\x00,\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x02D\x01\x00;')
     metrics:INFO Track metric: {'x-content-type-options': 'nosniff', 'expires': 'Mon, 01 Jan 1990 00:00:00 GMT', 'access-control-allow-origin': '*', 'status': '200', 'content-length': '35', 'last-modified': 'Sun, 17 May 1998 03:00:00 GMT', 'date': 'Wed, 21 Dec 2016 00:28:53 GMT', 'cache-control': 'no-cache, no-store, must-revalidate', 'server': 'Golfe2', 'pragma': 'no-cache', 'content-type': 'image/gif', 'age': '45622', 'content-location': 'http://www.google-analytics.com/collect?an=OpenShot+Video+Editor&tid=UA-4381101-5&t=screenview&cd4=5.5.1&cd5=Ubuntu-16.04-xenial&cd3=5.5.1&cd2=3.5.2&ua=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&av=2.2.0&aid=org.openshot.openshot-qt&cd1=0.1.2&cd=main-screen&v=1&ul=en-au&aip=1&cid='} (b'GIF89a\x01\x00\x01\x00\x80\xff\x00\xff\xff\xff\x00\x00\x00,\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x02D\x01\x00;')
     metrics:INFO Track metric: {'x-content-type-options': 'nosniff', 'expires': 'Mon, 01 Jan 1990 00:00:00 GMT', 'access-control-allow-origin': '*', 'status': '200', 'content-length': '35', 'last-modified': 'Sun, 17 May 1998 03:00:00 GMT', 'date': 'Wed, 21 Dec 2016 00:28:53 GMT', 'cache-control': 'no-cache, no-store, must-revalidate', 'server': 'Golfe2', 'pragma': 'no-cache', 'content-type': 'image/gif', 'age': '45622', 'content-location': 'http://www.google-analytics.com/collect?an=OpenShot+Video+Editor&tid=UA-4381101-5&t=screenview&cd4=5.5.1&cd5=Ubuntu-16.04-xenial&cd3=5.5.1&cd2=3.5.2&ua=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&av=2.2.0&aid=org.openshot.openshot-qt&cd1=0.1.2&cd=launch-app&sc=start&v=1&ul=en-au&aip=1&cid='} (b'GIF89a\x01\x00\x01\x00\x80\xff\x00\xff\xff\xff\x00\x00\x00,\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x02D\x01\x00;')
     ui_util:INFO Initializing UI for MainWindow
     ui_util:INFO Binding event MainWindow:actionNew_trigger
     ui_util:WARNING Icon theme document-new not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionOpen_trigger
     ui_util:WARNING Icon theme document-open not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionSave_trigger
     ui_util:WARNING Icon theme document-save not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionUndo_trigger
     ui_util:WARNING Icon theme edit-undo not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionSaveAs_trigger
     ui_util:WARNING Icon theme document-save-as not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionImportFiles_trigger
     ui_util:WARNING Icon theme list-add not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionImportImageSequence_trigger
     ui_util:WARNING Icon theme list-add not found. Will use backup icon.
     ui_util:WARNING Icon theme list-add not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionRedo_trigger
     ui_util:WARNING Icon theme edit-redo not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionRemoveClip_trigger
     ui_util:WARNING Icon theme list-remove not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionRemoveTransition_trigger
     ui_util:WARNING Icon theme list-remove not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionExportVideo_trigger
     ui_util:WARNING Icon theme media-record not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionUploadVideo_trigger
     ui_util:WARNING Icon theme folder-remote not found. Will use backup icon.
     ui_util:WARNING Icon theme gtk-quit not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAddTrack_trigger
     ui_util:WARNING Icon theme list-add not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionPreferences_trigger
     ui_util:WARNING Icon theme document-properties not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionPlay_trigger
     ui_util:WARNING Icon theme media-playback-start not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionJumpStart_trigger
     ui_util:WARNING Icon theme go-first not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionRewind_trigger
     ui_util:WARNING Icon theme media-seek-backward not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionFastForward_trigger
     ui_util:WARNING Icon theme media-seek-forward not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionJumpEnd_trigger
     ui_util:WARNING Icon theme go-last not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionArrowTool_trigger
     ui_util:INFO Binding event MainWindow:actionSnappingTool_trigger
     ui_util:INFO Binding event MainWindow:actionAddMarker_trigger
     ui_util:INFO Binding event MainWindow:actionPreviousMarker_trigger
     ui_util:WARNING Icon theme go-first not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionNextMarker_trigger
     ui_util:WARNING Icon theme go-last not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionFilesShowAll_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowVideo_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowAudio_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowImage_trigger
     ui_util:WARNING Icon theme edit-clear not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionTransitionsShowAll_trigger
     ui_util:INFO Binding event MainWindow:actionTransitionsShowCommon_trigger
     ui_util:WARNING Icon theme edit-clear not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionEffectsShowAll_trigger
     ui_util:INFO Binding event MainWindow:actionEffectsShowVideo_trigger
     ui_util:INFO Binding event MainWindow:actionEffectsShowAudio_trigger
     ui_util:WARNING Icon theme edit-clear not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionTimelineZoomIn_trigger
     ui_util:WARNING Icon theme zoom-in not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionTimelineZoomOut_trigger
     ui_util:WARNING Icon theme zoom-out not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionTitle_trigger
     ui_util:WARNING Icon theme font not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAnimatedTitle_trigger
     ui_util:WARNING Icon theme video-x-generic not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionFullscreen_trigger
     ui_util:WARNING Icon theme view-fullscreen not found. Will use backup icon.
     ui_util:WARNING Icon theme zoom-in not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAbout_trigger
     ui_util:WARNING Icon theme gtk-info not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionThumbnailView_trigger
     ui_util:WARNING Icon theme view-preview not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionDetailsView_trigger
     ui_util:WARNING Icon theme view-list-details not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionReportBug_trigger
     ui_util:WARNING Icon theme dialog-error not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAskQuestion_trigger
     ui_util:WARNING Icon theme im-message-new not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionTranslate_trigger
     ui_util:WARNING Icon theme stock_person not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionDonate_trigger
     ui_util:WARNING Icon theme bookmark-new not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionHelpContents_trigger
     ui_util:WARNING Icon theme help not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionSimple_View_trigger
     ui_util:WARNING Icon theme go-home not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAdvanced_View_trigger
     ui_util:WARNING Icon theme get-hot-new-stuff not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionFreeze_View_trigger
     ui_util:WARNING Icon theme locked not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionUn_Freeze_View_trigger
     ui_util:WARNING Icon theme locked not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionShow_All_trigger
     ui_util:WARNING Icon theme zoom-in not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionProfile_trigger
     ui_util:WARNING Icon theme video-x-generic not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAdd_to_Timeline_trigger
     ui_util:WARNING Icon theme list-add not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionPreview_File_trigger
     ui_util:WARNING Icon theme media-playback-start not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionRemove_from_Project_trigger
     ui_util:WARNING Icon theme list-remove not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionFile_Properties_trigger
     ui_util:WARNING Icon theme video-x-generic not found. Will use backup icon.
     ui_util:WARNING Icon theme edit-clear not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionRemoveTrack_trigger
     ui_util:WARNING Icon theme list-remove not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionRemoveMarker_trigger
     ui_util:WARNING Icon theme list-remove not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAddTrackAbove_trigger
     ui_util:WARNING Icon theme list-add not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAddTrackBelow_trigger
     ui_util:WARNING Icon theme list-add not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionRemoveEffect_trigger
     ui_util:WARNING Icon theme list-remove not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionSplitClip_trigger
     ui_util:WARNING Icon theme edit-cut not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionProperties_trigger
     ui_util:WARNING Icon theme document-properties not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionRenameTrack_trigger
     ui_util:WARNING Icon theme gtk-edit not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionUpdate_trigger
     ui_util:INFO Binding event MainWindow:actionTutorial_trigger
     ui_util:WARNING Icon theme im-message-new not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAnimation_trigger
     ui_util:WARNING Icon theme video-x-generic not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionLockTrack_trigger
     ui_util:INFO Binding event MainWindow:actionUnlockTrack_trigger
 files_model:INFO updating files model.
transition_model:INFO updating transitions model.
timeline_webview:INFO Qt Found!
timeline_webview:INFO $scope.Qt = true;
timeline_webview:INFO UpdateLayerIndex
effects_model:INFO updating effects model.
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
properties_model:INFO updating clip properties model.
 main_window:INFO InitCacheSettings
 main_window:INFO cache-mode: CacheMemory
 main_window:INFO cache-limit-mb: 250
 main_window:INFO Creating CacheMemory object with 262144000 byte limit
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "launch.py", line 77, in <module>
    main()
  File "launch.py", line 70, in main
    app = OpenShotApp(sys.argv)
  File "/home/alexander/Downloads/openshot-qt/src/classes/app.py", line 162, in __init__
    self.window = MainWindow(mode)
  File "/home/alexander/Downloads/openshot-qt/src/windows/main_window.py", line 1967, in __init__
    self.InitCacheSettings()
  File "/home/alexander/Downloads/openshot-qt/src/windows/main_window.py", line 1855, in InitCacheSettings
    new_cache_object = openshot.CacheMemory(cache_limit)
AttributeError: module 'openshot' has no attribute 'CacheMemory'
     version:INFO Found current version: {'server': 'Apache/2.2.22 (Ubuntu)', 'status': '200', 'content-type': 'application/json', 'transfer-encoding': 'chunked', 'content-location': 'http://www.openshot.org/version/json/', 'date': 'Wed, 21 Dec 2016 13:10:59 GMT'} (b'{"openshot_version": "2.2.0"}')
     metrics:INFO Track exception: {'connection': 'close', 'server': 'Apache/2.2.22 (Ubuntu)', 'status': '500', 'content-type': 'text/html; charset=utf-8', 'content-length': '10086', '-content-encoding': 'gzip', 'vary': 'Accept-Encoding', 'date': 'Wed, 21 Dec 2016 13:10:59 GMT'} (b'<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html xmlns="http://www.w3.org/1999/xhtml">\n<head>\n  <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />\n  <meta name="language" content="en" />\n  <meta name="rating" content="General" />\n  <meta name="doc-type" content="Public" />\n  <meta name="doc-class" content="Living Document" />\n  <meta name="robots" content="index" />\n  <meta name="revisit-after" content="2 Days" />\n  <meta name="keywords" content="video editor, non linear, linux, open source, linux video editor, free, easy to use, flexible" />\n  <meta name="description" content="A simple, powerful, and free open-source video editor for Linux with a focus on usability, flexibility, and style." />\n\n  <title>OpenShot Video Editor | 500 Internal Server Error</title>\n<link href=\'/images/favicon.png\' rel=\'shortcut icon\' type=\'image/png\'/> \n<link href=\'/images/favicon.png\' rel=\'icon\' type=\'image/png\'/> \n<link href=\'/css/style-1.css\' rel=\'stylesheet\' type=\'text/css\' />\n<link href=\'/css/style.css\' rel=\'stylesheet\' type=\'text/css\' />\n\n\n\n<script type="text/javascript" src="/scripts/jquery.min.js"></script>\n<script type="text/javascript" src="/scripts/sansation_custom.js"></script>\n<script type="text/javascript" src="/scripts/fancyzoom.js"></script>\n<script language="text/javascript">\n\n</script>\n\n\n<script type="text/javascript">\n$(document).ready(function() {\n\n\t// Check for ad container\n\tif($(".openshot-ad").size())\n  \t\t$(".openshot-ad").load("http://www.openshotstudios.com/ad/get/");\n\n    // Inject page scripts\n    \n\n});\n\n  // Google Analytics\n  var _gaq = _gaq || [];\n  _gaq.push([\'_setAccount\', \'UA-4381101-5\']);\n  _gaq.push([\'_trackPageview\']);\n\n  (function() {\n    var ga = document.createElement(\'script\'); ga.type = \'text/javascript\'; ga.async = true;\n    ga.src = (\'https:\' == document.location.protocol ? \'https://ssl\' : \'http://www\') + \'.google-analytics.com/ga.js\';\n    var s = document.getElementsByTagName(\'script\')[0]; s.parentNode.insertBefore(ga, s);\n  })();\n  \n</script>\n\n</head>\n<body>\n<div id="header">\n  <div class="center relative">\n  <h1 class="ss_logo"><a href="/"><img src="/images/logo.png" alt="" style="margin-top: 14px;"/></a></h1>\n  <div id="nav_main">\n  <ul class="sf-menu">\n      \n  <li ><a href="/">Home</a></li>\n    <li ><a href="/download/">Download</a></li>\n    <li ><a href="/features/">Features</a>\n    <ul>\n    \t<li><a href="/features">Feature List</a></li>\n    \t<li><a href="/screenshots">View Screenshots</a></li>\n    \t<li><a href="/videos">Watch Videos</a></li>\n    </ul>\n\t</li>\n\t<li ><a href="/about/">About Us</a>\n    <ul>\n    \t<li><a href="/about/">About OpenShot</a></li>\n\t\t<li><a href="/developers/">Meet the Developers</a></li>\n\t\t<li><a href="/reviews/">Reviews & Articles</a></li>\n\t\t<li><a href="/story/">Our Story</a></li>\n\t\t<li><a href="/sponsors/">Sponsors</a></li>\n\t\t<li><a href="/contact/">Contact Us</a></li>\n    </ul>\n\t</li>\n\t<li class="donate_page"><a href="/donate/">Donate</a>\n    <ul>\n    \t<li><a href="/donate/">Make Donation</a></li>\n    \t<li><a href="/donations/">View Donations</a></li>\n    </ul>\n\t</li>\n    <li ><a href="/support/">Need Help?</a>\n    <ul>\n      <li><a href="http://www.openshotusers.com/help/1.3/en" target="_blank">Help Manual</a></li>\n      <li><a href="http://openshotusers.com/forum/" target="_blank">Visit Forums</a></li>\n      <li><a href="https://github.com/OpenShot/openshot-qt/issues" target="_blank">Ask a Question</a></li>\n      <li><a href="https://github.com/OpenShot/openshot-qt/issues" target="_blank">Report a Bug</a></li>\n      <li><a href="https://translations.launchpad.net/openshot/2.0/+translations" target="_blank">Translations</a></li>\n    </ul>\n    </li>\n\t<li><a href="http://www.openshotvideo.com/?bloglink-header">Blog</a></li>\n  </ul>\n  </div>\n  </div>\n  \n</div>\n\n\n\n\n<div id="interiorbanner">\n\t<div class="center">\n\t\t<h2 class="ptitle" style="width: 600px;">500 Internal Server Error</h2>\n\t</div>\n</div>\n\n\n\n\n<div id="content_wrap" class="nobg">\n\n\t<div id="full_width">\n\t\t<div class="center">\n\n\t\t\t<h4 style="margin-top: 50px;">Whoops! Something has gone <strong>very wrong</strong>. Please try again or visit our home page at \n\t\t\t<a href="http://www.openshot.org/">www.openshot.org</a>.</h4>\n\n\t\t</div>\n\t</div>\n</div>\n\n\n\n\n</div>\n\n\n\n\n<div style="text-align: center; padding-bottom: 20px; padding-top: 10px;">\n\t<script src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>\n\t\n\t<ins class="adsbygoogle"\n\t     style="display:inline-block;width:728px;height:90px"\n\t     data-ad-client="ca-pub-6992519260108226"\n\t     data-ad-slot="4963807571"></ins>\n\t<script>\n\t(adsbygoogle = window.adsbygoogle || []).push({});\n\t</script>\n</div>\n\n<div id="footer">\n<div class="center">\n  <div class="fourcol_footer">\n  <h2>Recent Posts</h2>\n\n \t \t\n\t\t<ul>\n\t\n\t<li style="line-height: 24px; padding-bottom: 5px;"><a href="http://feedproxy.google.com/~r/OpenshotVideoEditor/~3/xrvaubRmfBw/openshot-22-released-4k-video-editing.html" target="_blank">OpenShot 2.2 Released | 4K Video Editing!</a></li>\n\t\n\t<li style="line-height: 24px; padding-bottom: 5px;"><a href="http://feedproxy.google.com/~r/OpenshotVideoEditor/~3/LELA8G0d9EA/help-needed-with-translations.html" target="_blank">Help Needed with Translations</a></li>\n\t\n\t<li style="line-height: 24px; padding-bottom: 5px;"><a href="http://feedproxy.google.com/~r/OpenshotVideoEditor/~3/cypd3G_CQzc/openshot-21-released.html" target="_blank">OpenShot 2.1 Released!</a></li>\n\t\n\t<li style="line-height: 24px; padding-bottom: 5px;"><a href="http://feedproxy.google.com/~r/OpenshotVideoEditor/~3/EXMxZzB4Uck/openshot-texas-linux-fest-2016.html" target="_blank">OpenShot @ Texas Linux Fest 2016</a></li>\n\t\n\t<li style="line-height: 24px; padding-bottom: 5px;"><a href="http://feedproxy.google.com/~r/OpenshotVideoEditor/~3/uc_0M3UM6OQ/openshot-20-beta-4-released.html" target="_blank">OpenShot 2.0 - Beta 4 Released!</a></li>\n\t\n</ul>\n\n  </div>\n\n  <div class="fourcol_footer">\n  <h2>Menu</h2>\n    <ul>\n      <li><a href="/download/">Download</a></li>\n      <li><a href="/features/">Features</a></li>\n      <li><a href="/about/">About Us</a></li>\n      <li><a href="/sponsors/">Sponsors</a></li>\n      <li><a href="/donate/">Donate</a></li>\n      <li><a href="/support/">Need Help?</a></li>\n\t  <li><a href="http://www.openshotvideo.com/?bloglink-footer">Blog</a></li>\n    </ul>\n  </div>\n\n\n\n\n  <div class="fourcol_footer">\n  <h2 style="margin-bottom: 15px;"><span class="socialheader">follow us</span></h2>   \n  <div id="sidebar_social_wrap" style="margin-left: 9px;">\n    \t<div class="social_button"><a href="http://www.facebook.com/openshot" target="_blank"><img src="/images/facebook64.png" border="0"></a></div>\n\t\t<div class="social_button"><a href="http://feeds.feedburner.com/OpenshotVideoEditor" target="_blank"><img src="/images/rss64.png" border="0"></a></div>\n\t\t<div class="social_button"><a href="http://vimeo.com/channels/openshot" target="_blank"><img src="/images/vimeo64.png" border="0"></a></div>\n\t\t<div class="social_button"><a href="http://www.openshotvideo.com/?blogger-button" target="_blank"><img src="/images/blogger64.png" border="0"></a></div>\n  </div>\n  <br />\n  </div>\n\n\n\n  <div class="fourcol_footer_last">\n    <h2>About</h2>\n    <p style="font-size: 0.75em;">\n      OpenShot Video Editor&trade; is free software: you can redistribute it and/or modify it under the terms of the <a href="http://www.gnu.org/licenses/gpl.html" target="_blank">GNU General Public License</a> as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.\n    </p>\n    <p style="padding: 0px; padding-left: 36px;">\n        <a href="http://aws.amazon.com/what-is-cloud-computing"><img src="http://awsmedia.s3.amazonaws.com/AWS_logo_poweredby_black_127px.png" alt="Powered by AWS Cloud Computing"></a>\n\n        <a style="margin: 10px;" href="https://www.patreon.com/bePatron?u=4032784&redirect_uri=http%3A%2F%2Fwww.openshot.org%2Fdonations%2F">\n           <img style="padding-top: 10px;" align="middle" height="30" src="https://s3-us-west-1.amazonaws.com/widget-images/become-patron-widget-medium%402x.png">\n        </a>\n    </p>\n\t<p>\n\t\t\n\t\t\t\t<div style="background-color: #303030; padding-left: 15px; padding-top: 6px; padding-bottom: 0px; border-radius: 20px; width: 180px; margin: auto;">\n\t\t    <h4 style="color: #ffffff;">\n\t\t\t\t<a href="/download" style="color: #ffffff;">Current Version: <strong>2.2.0</strong></a>\n\t\t    </h4>\n\t\t</div>\n\t</p>\n  </div>\n\n\n\n\n  <div id="copyright">\n  <p>OpenShot Video Editor&trade;. Copyright &copy; 2008-2013 <a target="_blank" href="http://www.openshotstudios.com/">OpenShot Studios, LLC</a>. All Rights Reserved.</p>\n  </div>\n</div>\n</div>\n\n\n<script type="text/javascript">\n//<![CDATA[\n    jQuery(function(){\n      jQuery(\'ul.sf-menu\').superfish();\n    });\n//]]>\n</script>\n\n\n<script type="text/javascript" src="/scripts/jquery.cycle.all.js"></script>\n<script type="text/javascript">\n//<![CDATA[\n\n$(function() {\n\n    $(\'#home_slider\').cycle({\n        fx:      \'fade\',\n        timeout:  5500,\n        pager:   \'#home_slider_nav\',\n        pagerAnchorBuilder: pagerFactory,\n    pause:  true,\n\tnowrap: true\n    });\n\n    function pagerFactory(idx, slide) {\n        return \'<ul><li><a href="#">\'+(idx+1)+\'</a></li></ul>\';\n    };\n    \n});\n//]]>\n</script>\n\n\n<script type="text/javascript" src="/scripts/piroBox.1_2.js"></script>\n\n\n</body>\n</html>\n')

**Comment by david-geiger** [comment]
Same issue here on Mageia and openshot-qt 2.2.0:

AttributeError: module 'openshot' has no attribute 'CacheMemory'

**Comment by IMBJR** [comment]
Same issue here on Arch and openshot 2.2.0-1.

...
properties_model:INFO updating clip properties model.
 main_window:INFO InitCacheSettings
 main_window:INFO cache-mode: CacheMemory
 main_window:INFO cache-limit-mb: 250
 main_window:INFO Creating CacheMemory object with 262144000 byte limit
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "/usr/bin/openshot-qt", line 11, in <module>
    load_entry_point('openshot-qt==2.2.0', 'gui_scripts', 'openshot-qt')()
  File "/usr/lib/python3.5/site-packages/openshot_qt/launch.py", line 70, in main
    app = OpenShotApp(sys.argv)
  File "/usr/lib/python3.5/site-packages/openshot_qt/classes/app.py", line 162, in __init__
    self.window = MainWindow(mode)
  File "/usr/lib/python3.5/site-packages/openshot_qt/windows/main_window.py", line 1967, in __init__
    self.InitCacheSettings()
  File "/usr/lib/python3.5/site-packages/openshot_qt/windows/main_window.py", line 1855, in InitCacheSettings
    new_cache_object = openshot.CacheMemory(cache_limit)
AttributeError: module 'openshot' has no attribute 'CacheMemory'

**Comment by seindal** [comment]
I have the same problem on Debian with Openshot 2.2.0 installed from the unstable repository.

**Comment by viktor-c** [comment]
This seems to be caused from an _openshot.settings_ file in your home folder from an older version of openshot like is the case with me.

Open a file manager, go to the menu to show hidden files, enter _.openshot_qt_ folder, then delete the file _openshot.settings_

Now openshot should start

**Comment by anhtuann** [comment]
Issue solved on Arch after libopenshot updated to v0.1.3-1

**Comment by david-geiger** [comment]
Yeah! for me too libopenshot 0.1.3 fixes this issue :)

**Comment by jonoomph** [comment]
Looks like this issue is resolved. The web error has been fixed by me, and the CacheMemory errors are related to running an older version of libopenshot. Thx.

**Comment by Hooloovoo** [comment]
Hi,

I just tried to download and use the latest Openshot. I went to the main Openshot page and added the PPA as per:
http://www.openshot.org/ppa/

Trying to open from command line gives essentially the error above:
http://paste.ubuntu.com/23926420/

That may be expected, given it looks like the PPA still has libopenshot 0.1.2 and this issue is fixed in 0.1.3, but I thought I would comment in case it was supposed to be fixed in the PPA.
