### ISSUE TITLE
name 'ex' is not defined example

### ISSUE THREAD

**Issue by ZoharML** [OpenShot/openshot-qt#4363]
[testy.zip](https://github.com/OpenShot/openshot-qt/files/7069215/testy.zip)
I read on reddit that you wish to send you OSP files with this error.

I was working on a project and while trying to add some texts to the video the program crashed.
After that the EX error started and I found myself stuck.

(Adding a backup option to the save could have helped me allot)

OpenShot V2.6.0
windows 10 64bit

Thanks

**Comment by JacksonRG** [comment]
Oh, and you might check this directory.
`C:\Users\(*USERNAME*)\.openshot_qt\recovery`
After the first time a project is saved, OpenShot by default makes periodic backups.

**Comment by ZoharML** [comment]
Thanks for your your fast fix!
I installed daily 8183 and the flie load without a problem.

BUT... You have a new bug :)
Open the osp file (by double click in the file explorer), and now just close the project.
the .osp file dissapear, and you only left with the .osp.bck  (thanks for this backup!)

Renaming the file back to .osp fix it all back.

**Comment by JacksonRG** [comment]
Sorry, I don't think I'm quite understanding. Do you want to open a new issue about this?

Are all project files disappearing if you open them without saving?

**Comment by ZoharML** [comment]
Yes, It might be a new isssue...
I only oppened two projects and had the same effect on them both.
