### ISSUE TITLE
name 'ex' is not defined

### ISSUE THREAD

**Issue by benoe77** [OpenShot/openshot-qt#4368]
**Describe the bug:**

When I try to open a saved project, I got this error message:
"name 'ex' is not defined"

**Steps to reproduce the behavior:**
1. Save a project
2. Close OpenShot
3. Start OpenShot
4. Open saved project: "name 'ex' is not defined" 

**Expected behavior:**
I can open my project and continue the work on it.

**System Details:**
- OpenShot Version:  2.6.0

- Operating System / Distro:Windows 10

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/7071255/openshot-qt.log)

.osp renamed to .txt:
[project.txt](https://github.com/OpenShot/openshot-qt/files/7071256/project.txt)

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by alonsoac** [comment]
I have this same problem in Windows 8.1

**Comment by benoe77** [comment]
They fixed it in the latest daily:
https://www.openshot.org/download/
Click on Daily Builds

**Comment by speedytechdev** [comment]
@benoe77 Has the daily build fixed your issue? If so are you happy for me to close the report?
