### ISSUE TITLE
name 'ex' is not defined

### ISSUE THREAD

**Issue by Salamancd8** [OpenShot/openshot-qt#4369]
**Describe the bug:**

I can open empty projects and one project I did months back, but not anything new I make. I've attached the osp as a txt file.
[goon1.txt](https://github.com/OpenShot/openshot-qt/files/7071829/goon1.txt)

**Steps to reproduce the behavior:**

**Expected behavior:**

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by speedytechdev** [comment]
Hi, @Salamancd8 have you tried the daily build? We believe this could fix your issue.

**Comment by pra5h** [comment]
I was getting this error with version 2.6 installed on 2nd Sept 2021, while opening an existing project or .OSP file. I updated to the daily build (link below) and it resolved the issue.
However, with the new build it seems like while exporting the project name is not being considered and file is saved as "Untitled....".

https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.6.0-dev-daily-8219-5a8ffe36-5ec3bc21-x86_64.exe

**Comment by speedytechdev** [comment]
Hi @pra5h , Could you file this as a new issue, please since this one is going to get closed for inactive soon.

**Comment by osowiecki** [comment]
Same error on 2.6.0. Made a project, exported it, closed everything down, worked on another project and now I can't open the previous project "name ex is not defined".

**Comment by speedytechdev** [comment]
**THIS ISSUE HAS BEEN FIXED IN 2.6.1**
