### ISSUE TITLE
OpenShot 2.2.0 froze after sitting idle

### ISSUE THREAD

**Issue by dhighley** [OpenShot/openshot-qt#437]
Running on Fedora 25 OpenShot 2.2.0. Just was starting to look at a new project. Imported bunch of video segments. Dropped two onto the time line. Played them a few times. Then left it sitting and the screen timed out and locked. Gnome window system by the way and it is now using Wayland. After unlocking the screen I found OpenShot frozen. No menus or buttons would work. So I did  a window frame close and it popped up dialog to asking save yes, no, cancel. Clicking on the buttons did nothing. Finally figured out I could type n for not saving. I ran top but did not see any issues there.

**Comment by dhighley** [comment]
Found that you can also create this issue by maximizing the OpenShot window. I should have indicated that the host is a 64 bit x86 host.

**Comment by revjdc** [comment]
If you log out of the standard Wayland session and log back in to "Gnome on X" OpenShot should work as expected.

Fedora indicates that Wayland and QT4 don't interact very well. Maybe there's some QT4 code left in OpenShot somewhere.

I suggest filing a report with Fedora's bug tracking system, or looking up Fedora's package maintainer.

**Comment by dhighley** [comment]
Thanks for the response. I did not try that yet. I have created an Ubuntu 16.4 VM and have been running in that. Only current issue I'm having with the Ubuntu VM is the eye and audio icons are no where to be found so I have not been able to separate audio and video.

I will try the login without Wayland and let you know if that solves frozen GUI.

**Comment by dhighley** [comment]
Yes it seems to be stable if you login with Gnome.Xorg session option. Tried several different things that had caused the GUI to freeze before. Did notice the same issue of not seeing the eye and audio icons. Has there been a change in how you separate, turn off video or audio for clips, that has not been updated in the user manual?
