### ISSUE TITLE
Drag and drop, cut and crop, resize and move, scale,... too, all should be able to do in the Video preview, just like other editors (ex: Camtasia)

### ISSUE THREAD

**Issue by shadichy** [OpenShot/openshot-qt#4370]
**Describe the new feature:**
Yeah, this is about ui/ux, especially "user-friendly"
Long time ago, when i was still using Windows, i have tried out some of the best video editors for it, and i appreciate those because those are so functional, like, instead of `right click over clips and modify those propterties` i just have to `click the clip on the preview and drag, move, drop, even crop, scale, resize,...` 
I've switched to GNU/Linux for a _slightly_ better performance, it does improve gaming fps and quality compare to my old windows, but, less support is always a linux problem. You know, linux is rising today, despite that, there is still less support for linux, compare to Windows and Mac, the biggest problem i think is software. I didn't say i want Camtasia on Linux, but, if you guys "can" `bring similar or even better way to create video`, i mean same or improved functionallities compare to Camtasia on Win/Mac, that would be great, i mean wondershare, no, wonderful, sorry... =))

**Describe the solution you'd like:**
Soooo, how can i change clips properties using the Video preview, is it possible? If not, when will it be possible?

**Describe alternatives you have considered:**
Just Camtasia Studio, Wondershare Filmora, Adobe Premiere Pro, and some others

**Screenshots:** (Optional)
![a random stuff, see those?](https://phanmemnet.com/wp-content/uploads/2021/04/Camtasia-Studio-2021-1024x692.png)

**Comment by JacksonRG** [comment]
Unless I'm misunderstanding, the feature you're asking about currently exists in OpenShow. You can drag and resize your videos in the preview window.

https://user-images.githubusercontent.com/42394129/157301954-43dcbe84-85f2-448d-85c4-6ea5d544011d.mp4

Cropping is the only exception, as that's done through one of our effects.

https://user-images.githubusercontent.com/42394129/157302330-13ffab1f-82ea-495d-9a2a-c9cbafecaa54.mp4

**Comment by shadichy** [comment]
maybe i havent updated for a while
dunno how 2 do that be4
btw thanks
ill close this
