### ISSUE TITLE
v2.6.0 requires OSX 10.15, claims it's compatible with 10.9+

### ISSUE THREAD

**Issue by gradha** [OpenShot/openshot-qt#4371]
[Openshot website](https://www.openshot.org/download/) claims v2.6.0 of the software is compatible with OSX 10.9+:

![Captura de pantalla 2021-08-29 a las 21 13 53](https://user-images.githubusercontent.com/101927/131262653-185fe01d-2773-496a-926f-9eef175c8c2f.png)

After downloading the software and attempting to open, it says 10.14.6 Mojave is not supported:

![Captura de pantalla 2021-08-29 a las 21 12 42](https://user-images.githubusercontent.com/101927/131262674-2d3b0c0b-f5b1-4ae9-9788-0a2215355d71.png)

**Comment by speedytechdev** [comment]
Hi @gradha from what I can see on our website It has been updated to support OS X 10.15+ . This was probably a mistake by our team. It should hopefully be fixed now. If not I would be happy to mark this as a bug and our dev team to check it out.

![image](https://user-images.githubusercontent.com/40452959/131498680-d3203719-9aea-4e63-9f9b-7610c709e543.png)

**Comment by speedytechdev** [comment]
Seems to be the same as #4350 Need someone from the dev team to confirm.

**Comment by speedytechdev** [comment]
@JacksonRG Can you confirm if this has been fixed?

**Comment by gradha** [comment]
Web is updated.
