### ISSUE TITLE
Live audio recording feature

### ISSUE THREAD

**Issue by luisalvarado** [OpenShot/openshot-qt#4372]
**Describe the new feature:**
A clear and concise description of what the new feature or problem is.

Hi, so I have been a user for several years now, using openshot on Ubuntu. But found, I would say about 2 months ago why my wife would not use it often. It is because there is an app called filmora wondershare on windows and THE ONLY benefit she says that it has over openshot for her is the ability to record audio on the spot, in real time.

So basically it works like this. She creates a video, typically a cooking recipe. Then she goes to wondershare and puts the pieces in it, cuts, moves the video parts around and then she clicks on a button to start recording her voice in real time while watching the video.

The tool is very good but it is missing noise cancelation during the real-time recording or a better audio editing (noise cancelation, loud noise detection and normalization like audacity, etc) but all in all, it is the specific simplified ability to record on the go when editing the video that does not let her use openshot.

**Describe the solution you'd like:**

**Describe alternatives you have considered:**

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your request.

**Comment by speedytechdev** [comment]
Hi @luisalvarado , Thank you for bringing up this amazing idea. Our dev team will look through this and will contact you if they have any questions or concerns. Hopefully, you can see it in Openshot one day.  Enjoy the rest of your day 😀

**Comment by luisalvarado** [comment]
Love it. Thank you friend.

**Comment by schuellerf** [comment]
As I would also love to see this feature in OpenShot and in the original request there is no "Screenshot" explanation, I'll try to explain what I understood (and which I would also need ;) )
@luisalvarado please comment if this is correct and matches your request

e.g. some button to "play the video while recording to a new/empty track

here some faked-screenshots:

![OpenShotSoundRecord_1_before](https://user-images.githubusercontent.com/8057963/141489928-1aa2032d-4443-486d-afbe-5edef9ed5c21.png)
---
![OpenShotSoundRecord_2_after](https://user-images.githubusercontent.com/8057963/141489947-1bd59a1d-7afa-4e68-8a48-3a6d6f458e66.png)

**Comment by luisalvarado** [comment]
> As I would also love to see this feature in OpenShot and in the original request there is no "Screenshot" explanation, I'll try to explain what I understood (and which I would also need ;) ) @luisalvarado please comment if this is correct and matches your request
> 
> e.g. some button to "play the video while recording to a new/empty track
> 
> here some faked-screenshots:
> 
> ## ![OpenShotSoundRecord_1_before](https://user-images.githubusercontent.com/8057963/141489928-1aa2032d-4443-486d-afbe-5edef9ed5c21.png)
> ![OpenShotSoundRecord_2_after](https://user-images.githubusercontent.com/8057963/141489947-1bd59a1d-7afa-4e68-8a48-3a6d6f458e66.png)

Exactly like that for the live recording. Filmora has an option for that which is to be frank the only reason she uses it. Also note. Took her about a week to learn filmora and about 3 minutes to learn openshot. So with this live audio recording she will be very excited. Thank you friend.

**Comment by schuellerf** [comment]
Might be related to https://github.com/OpenShot/libopenshot-audio/issues/1

**Comment by luisalvarado** [comment]
Well yes, it looks similar, it is just that for the idea in practice, there is no additional requirements for it except recording the audio to another track in a live way, like filmora. If it is able to record live while the video is playing then awesome, that was it. This is mainly because she does cooking videos, so basically spents like 4 hours doing the cooking part in a 10 to 15 minute video, then goes to Filmora, edits the video and then it clicks on audio recording to start recording her voice while explaining what is happening in the video.

**Comment by luisalvarado** [comment]
Hi @stale hopefully this can be brought to light. Yes the feature proposal is still relevant and it is my believe, at least from my end, that it is one that is critical for me to move a couple of users, including my wife to ONLY using openshot. Thank you very much.

**Comment by jonoomph** [comment]
This is a great feature idea, and I would love to support it soon! If anyone is interested in helping to contribute some code, I would be happy to assist and mentor. Thx!

**Comment by luisalvarado** [comment]
Hi guys, just letting you know that I was hoping between video editors and learned about shotcut, but also kdenlive. I did notice both of the them had voiceover, but only on kdenlive does it work in an easy way. Just add a new audio track, select that one, and then on the far right, select the properties of that new audio track and select the microphone. From there you can now record in a live way, meaning voiceover. So this is the idea I was asking for openshot, although a MUCH FRIENDLIER approach would be to create the audio track and have a red button there to "Live Record" instead of so much clicking on kdenlive.

Currently most of the videos here https://www.youtube.com/@xtremelinux were done with kdenlive (After I found out about the voiceover), but the ones that did not have any voice were done with openshot.

**Comment by Colorjet3** [comment]
An internal ticket has been submitted to get this request in the queue:  https://trello.com/c/MnkjbFQ7/132-live-audio-recording.

**Comment by Colorjet3** [comment]
This is still in the queue for review.
