### ISSUE TITLE
OpenShot 2.6.0 So Sluggish It's Not Useable Anymore

### ISSUE THREAD

**Issue by tominterval** [OpenShot/openshot-qt#4375]
UPDATE (09.01.2021): I just uploaded a video screenshot of the sluggish performance in OpenShot. As you can see, playback is painfully slow. For your reference, please look at the following YouTube video to see the video at its normal speed: https://www.youtube.com/watch?v=TyugzpC8byo

https://user-images.githubusercontent.com/58096621/131745549-f336c4cd-3926-41d0-87ff-f4b0091eb513.mp4

**Describe the bug**
OpenShot no longer allows me to preview imported videos without being so sluggish it's not even operable.

**Steps to reproduce the behavior:**
1. Open OpenShot.
2. Import any video in any format.
3. Try to do any normal functions, such as scrubbing, playing, or anything else, and it halts to such a degree that it the program cannot be used. It doesn't crash. It just sits there while being sluggish.

**Expected behavior**
I expected it to work as it usually had for many videos I've made in the past. I can no longer use OpenShot.

**System Details**
- OpenShot Version: 2.6.0-dev
- libopenshot Version:  0.2.6-dev
- Platform: Windows-8.1-6.3.9600
- Processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Skipped this step

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/fftpu0kt6vfgfjvgtlg3ona1sj3lq7gl/openshot-qt.zip) (38 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/fftpu0kt6vfgfjvgtlg3ona1sj3lq7gl/libopenshot.zip) (0 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional) - 09/01/2021: Please see the video screenshot and note above. Added today.
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by speedytechdev** [comment]
Hi @tominterval , If you could try the daily build and see if that fixes your issue. Our dev team are pretty quick with fixing bugs. If that doesn't fix your issue we can mark the report as a bug and our dev team will be happy to fix the issue.

**Comment by Gabriele02** [comment]
> Hi @tominterval , If you could try the daily build and see if that fixes your issue. Our dev team are pretty quick with fixing bugs. If that doesn't fix your issue we can mark the report as a bug and our dev team will be happy to fix the issue.

Hi @speedytechdev,
I'm having the same issue with the latest daily build (OpenShot-v2.6.0-dev-daily-8190-d58febf1-5ec3bc21-x86_64.exe (64-bit)).
When I hit the play button, to show the preview of the video, the playback is really slow and the CPU is not utilized fully: Task manager shows 2-12% of CPU utilization. Previous versions pinned the CPU at 100% during playback.

**Comment by speedytechdev** [comment]
> > Hi @tominterval , If you could try the daily build and see if that fixes your issue. Our dev team are pretty quick with fixing bugs. If that doesn't fix your issue we can mark the report as a bug and our dev team will be happy to fix the issue.
> 
> Hi @speedytechdev,
> I'm having the same issue with the latest daily build (OpenShot-v2.6.0-dev-daily-8190-d58febf1-5ec3bc21-x86_64.exe (64-bit)).
> When I hit the play button, to show the preview of the video, the playback is really slow and the CPU is not utilized fully: Task manager shows 2-12% of CPU utilization. Previous versions pinned the CPU at 100% during playback.

Hi @Gabriele02 , Thank you for that. I will mark it as a bug and hopefully, our dev team can look into this and fix this. Enjoy the rest of your day :)

**Comment by tominterval** [comment]
> Hi @tominterval , If you could try the daily build and see if that fixes your issue. Our dev team are pretty quick with fixing bugs. If that doesn't fix your issue we can mark the report as a bug and our dev team will be happy to fix the issue.

Hi @speedytechdev. Thanks for looking into that. Yeah, I did all the troubleshooting steps first, including an uninstall, reinstall, downloading the daily build, deselecting bug report, etc., but nothing seemed to work. And I've never seen the audio not come through when playing (or trying to play) the preview. To clarify, this issue is not specific to v2.6.0. It started happening with the previous version/daily build I had. Although my PC couldn't launch a space shuttle, it's not ancient or anything, so it should have the resources to run OpenShot at least as quickly as it used to, say 9 or 10 months ago (roughly). Whatcha think? PC: ASUS; Processor: Intel Core i5-4460 CPU @ 3.20GHz; Installed RAM: 4.00GB (3.88 GB usable); OS: Windows 8.1. OpenShot never ran _super_ fast on my computer, but it was definitely useable. Do you think it might be more about older system resources just not keeping up? Thanks again.

**Comment by speedytechdev** [comment]
> > Hi @tominterval , If you could try the daily build and see if that fixes your issue. Our dev team are pretty quick with fixing bugs. If that doesn't fix your issue we can mark the report as a bug and our dev team will be happy to fix the issue.
> 
> Hi @speedytechdev. Thanks for looking into that. Yeah, I did all the troubleshooting steps first, including an uninstall, reinstall, downloading the daily build, deselecting bug report, etc., but nothing seemed to work. And I've never seen the audio not come through when playing (or trying to play) the preview. To clarify, this issue is not specific to v2.6.0. It started happening with the previous version/daily build I had. Although my PC couldn't launch a space shuttle, it's not ancient or anything, so it should have the resources to run OpenShot at least as quickly as it used to, say 9 or 10 months ago (roughly). Whatcha think? PC: ASUS; Processor: Intel Core i5-4460 CPU @ 3.20GHz; Installed RAM: 4.00GB (3.88 GB usable); OS: Windows 8.1. OpenShot never ran _super_ fast on my computer, but it was definitely useable. Do you think it might be more about older system resources just not keeping up? Thanks again.

Hi @tominterval From what I can tell you have done everything right but it might be better if someone from our dev team just double checks. Openshot should also be able to run on low-end systems. Sorry if Im not much help.

**Comment by tominterval** [comment]
> > > Hi @tominterval , If you could try the daily build and see if that fixes your issue. Our dev team are pretty quick with fixing bugs. If that doesn't fix your issue we can mark the report as a bug and our dev team will be happy to fix the issue.
> > 
> > 
> > Hi @speedytechdev. Thanks for looking into that. Yeah, I did all the troubleshooting steps first, including an uninstall, reinstall, downloading the daily build, deselecting bug report, etc., but nothing seemed to work. And I've never seen the audio not come through when playing (or trying to play) the preview. To clarify, this issue is not specific to v2.6.0. It started happening with the previous version/daily build I had. Although my PC couldn't launch a space shuttle, it's not ancient or anything, so it should have the resources to run OpenShot at least as quickly as it used to, say 9 or 10 months ago (roughly). Whatcha think? PC: ASUS; Processor: Intel Core i5-4460 CPU @ 3.20GHz; Installed RAM: 4.00GB (3.88 GB usable); OS: Windows 8.1. OpenShot never ran _super_ fast on my computer, but it was definitely useable. Do you think it might be more about older system resources just not keeping up? Thanks again.
> 
> Hi @tominterval From what I can tell you have done everything right but it might be better if someone from our dev team just double checks. Openshot should also be able to run on low-end systems. Sorry if Im not much help.

Thanks, really appreciate your time. Hopefully there's something for them to find so I (and others?) can get back to using it.

**Comment by tominterval** [comment]
> I'll look into why it wouldn't be making of your computer resources.
> 
> One thing I might suggest is lowering the preview resolution to make editing easier, and then export at a higher resolution

Thanks, JacksonRG. I'll definitely try that, but I've never had to do that in the past, and the audio still doesn't work while previewing. BTW, I just uploaded a video screenshot of the issue a few minutes ago. Thanks again.

**Comment by tominterval** [comment]
> > > > Hi @tominterval , If you could try the daily build and see if that fixes your issue. Our dev team are pretty quick with fixing bugs. If that doesn't fix your issue we can mark the report as a bug and our dev team will be happy to fix the issue.
> > > 
> > > 
> > > Hi @speedytechdev. Thanks for looking into that. Yeah, I did all the troubleshooting steps first, including an uninstall, reinstall, downloading the daily build, deselecting bug report, etc., but nothing seemed to work. And I've never seen the audio not come through when playing (or trying to play) the preview. To clarify, this issue is not specific to v2.6.0. It started happening with the previous version/daily build I had. Although my PC couldn't launch a space shuttle, it's not ancient or anything, so it should have the resources to run OpenShot at least as quickly as it used to, say 9 or 10 months ago (roughly). Whatcha think? PC: ASUS; Processor: Intel Core i5-4460 CPU @ 3.20GHz; Installed RAM: 4.00GB (3.88 GB usable); OS: Windows 8.1. OpenShot never ran _super_ fast on my computer, but it was definitely useable. Do you think it might be more about older system resources just not keeping up? Thanks again.
> > 
> > 
> > Hi @tominterval From what I can tell you have done everything right but it might be better if someone from our dev team just double checks. Openshot should also be able to run on low-end systems. Sorry if Im not much help.
> 
> Thanks, really appreciate your time. Hopefully there's something for them to find so I (and others?) can get back to using it.

Hello again, @speedytechdev. Just FYI, I uploaded a video screencap a few minutes ago for everyone's reference. Thanks again.

**Comment by tominterval** [comment]
> I'll look into why it wouldn't be making of your computer resources.
> 
> One thing I might suggest is lowering the preview resolution to make editing easier, and then export at a higher resolution

Hello again, JacksonRG. I just tried your suggestion and changed the preview from HD 1080p 24fps to HD 720p 24fps (via Edit > Preferences > Preview), restarted OpenShot, and it's just as slow. Should I try another preview setting? If so, which one would you recommend? Also, still puzzled by the zero-audio thing. Thanks.

**Comment by c2farr** [comment]
I had the problem of ultra slow preview with v 2.5. Restarting the program always fixed it. I upgraded today to 2.6 and the problem is constant. No usable playback. I increased cache to 2048. Decreased preview res to Mobile 360. Neither did anything to fix it. I can still output MP4 of any previous edit, but cannot edit anything new.

**Comment by speedytechdev** [comment]
Thank you to everyone for providing more information about the bug. It helps our team a lot. If you think of anything else please feel free to add on. 

Thank You and enjoy the rest of your day.
Speedytechlive - Support Team

**Comment by tominterval** [comment]
> I had the problem of ultra slow preview with v 2.5. Restarting the program always fixed it. I upgraded today to 2.6 and the problem is constant. No usable playback. I increased cache to 2048. Decreased preview res to Mobile 360. Neither did anything to fix it. I can still output MP4 of any previous edit, but cannot edit anything new. Win 7, 64 bit.

Thanks for sharing. It's good to know I'm not the only one experiencing this problem.

**Comment by tominterval** [comment]
> Thank you to everyone for providing more information about the bug. It helps our team a lot. If you think of anything else please feel free to add on.
> 
> Thank You and enjoy the rest of your day.
> Speedytechlive - Support Team

Thanks so much, Speedytechlive! Looking forward to the day when I can use OpenShot again.

**Comment by structre40** [comment]
I have a similar issue but can't even get the preview to load or play back. The timeline moves but the preview pane remains black. I have followed the same steps of uninstalling/reinstalling and lowering the quality while editing and there is no change. 
Proc: Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz   2.30 GHz
Ram: 6GB
OS: Windows 10 Home x64 20H2

This was working on a previous version but I can not seem to find which version it was before upgrading 3 days ago.

**Comment by structre40** [comment]
> I have a similar issue but can't even get the preview to load or play back. The timeline moves but the preview pane remains black. I have followed the same steps of uninstalling/reinstalling and lowering the quality while editing and there is no change.
> Proc: Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz 2.30 GHz
> Ram: 6GB
> OS: Windows 10 Home x64 20H2
> Version: OpenShot-v2.6.0-release-candidate-8083-73b009d3-6a84f7ee
> This was working on a previous version but I can not seem to find which version it was before upgrading 3 days ago.

I tried 3 different installs and finally got one to work again in the preview pane.
Didn't work:
OpenShot-v2.6.0-dev-daily-8261-2dbb8d53-5ec3bc21-x86_64
OpenShot-v2.5.2-release-candidate-6913-f344214c-5487efb2-x86_64

WORKED:
OpenShot-v2.4.5-release-candidate-1578826573-x86_64

I can confirm CPU usage on 2.4.5 is much higher(52%) compared to 2.5.2 or 2.6(5-6%).

**Comment by tominterval** [comment]
> > I have a similar issue but can't even get the preview to load or play back. The timeline moves but the preview pane remains black. I have followed the same steps of uninstalling/reinstalling and lowering the quality while editing and there is no change.
> > Proc: Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz 2.30 GHz
> > Ram: 6GB
> > OS: Windows 10 Home x64 20H2
> > Version: OpenShot-v2.6.0-release-candidate-8083-73b009d3-6a84f7ee
> > This was working on a previous version but I can not seem to find which version it was before upgrading 3 days ago.
> 
> I tried 3 different installs and finally got one to work again in the preview pane.
> Didn't work:
> OpenShot-v2.6.0-dev-daily-8261-2dbb8d53-5ec3bc21-x86_64
> OpenShot-v2.5.2-release-candidate-6913-f344214c-5487efb2-x86_64
> 
> WORKED:
> OpenShot-v2.4.5-release-candidate-1578826573-x86_64
> 
> I can confirm CPU usage on 2.4.5 is much higher(52%) compared to 2.5.2 or 2.6(5-6%).

Hi structre40. Interesting. So performance is good with v2.4.5 as listed above? Admin, would you recommend we download that daily build until the latest version is fixed?

**Comment by structre40** [comment]
> > > I have a similar issue but can't even get the preview to load or play back. The timeline moves but the preview pane remains black. I have followed the same steps of uninstalling/reinstalling and lowering the quality while editing and there is no change.
> > > Proc: Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz 2.30 GHz
> > > Ram: 6GB
> > > OS: Windows 10 Home x64 20H2
> > > Version: OpenShot-v2.6.0-release-candidate-8083-73b009d3-6a84f7ee
> > > This was working on a previous version but I can not seem to find which version it was before upgrading 3 days ago.
> > 
> > 
> > I tried 3 different installs and finally got one to work again in the preview pane.
> > Didn't work:
> > OpenShot-v2.6.0-dev-daily-8261-2dbb8d53-5ec3bc21-x86_64
> > OpenShot-v2.5.2-release-candidate-6913-f344214c-5487efb2-x86_64
> > WORKED:
> > OpenShot-v2.4.5-release-candidate-1578826573-x86_64
> > I can confirm CPU usage on 2.4.5 is much higher(52%) compared to 2.5.2 or 2.6(5-6%).
> 
> Hi structre40. Interesting. So performance is good with v2.4.5 as listed above? Devs, would you recommend we download that daily build until the latest version is fixed?

I wouldn't call the performance good but that is more related to my underpowered machine. The Preview pane is usable though in 2.4.5 so I could continue on with the movie editing.

**Comment by tominterval** [comment]
> > > > I have a similar issue but can't even get the preview to load or play back. The timeline moves but the preview pane remains black. I have followed the same steps of uninstalling/reinstalling and lowering the quality while editing and there is no change.
> > > > Proc: Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz 2.30 GHz
> > > > Ram: 6GB
> > > > OS: Windows 10 Home x64 20H2
> > > > Version: OpenShot-v2.6.0-release-candidate-8083-73b009d3-6a84f7ee
> > > > This was working on a previous version but I can not seem to find which version it was before upgrading 3 days ago.
> > > 
> > > 
> > > I tried 3 different installs and finally got one to work again in the preview pane.
> > > Didn't work:
> > > OpenShot-v2.6.0-dev-daily-8261-2dbb8d53-5ec3bc21-x86_64
> > > OpenShot-v2.5.2-release-candidate-6913-f344214c-5487efb2-x86_64
> > > WORKED:
> > > OpenShot-v2.4.5-release-candidate-1578826573-x86_64
> > > I can confirm CPU usage on 2.4.5 is much higher(52%) compared to 2.5.2 or 2.6(5-6%).
> > 
> > 
> > Hi structre40. Interesting. So performance is good with v2.4.5 as listed above? Devs, would you recommend we download that daily build until the latest version is fixed?
> 
> I wouldn't call the performance good but that is more related to my underpowered machine. The Preview pane is usable though in 2.4.5 so I could continue on with the movie editing.

Thanks. Yeah, my machine is not that robust. Maybe I'll give that a go for now.

**Comment by DanPinGF** [comment]
Hmm... from what I'm seeing in the video the problem appears to be quite identical to #4303. OpenShot can only rely on a single audio output source, and if that source is disabled or disconnected or if the system goes to sleep it acts that way.

**Comment by tominterval** [comment]
> Hmm... from what I'm seeing in the video the problem appears to be quite identical to #4303. OpenShot can only rely on a single audio output source, and if that source is disabled or disconnected or if the system goes to sleep it acts that way.

That's not the problem. My habits hadn't changed over the years I was using the program. OpenShot changed. And the audio was only one issue. The other, bigger, issue was that OpenShot lagged to the point of me not being able to use it. I uninstalled it and now use VSDC, which works beautifully every time.

**Comment by tominterval** [comment]
> Hmm... from what I'm seeing in the video the problem appears to be quite identical to #4303. OpenShot can only rely on a single audio output source, and if that source is disabled or disconnected or if the system goes to sleep it acts that way.

But thank you, anyway. Appreciate you taking the time to comment.

**Comment by awunes** [comment]
I'm having the same issue. Can't give any more details than they did. Though my PC is a bit buffer:

OS: Win 7 Enterprise 64-bit, CPU: Intel Core i3-3220 CPU 3.30GHz, RAM: 12GB
Gonna go try OpenShot-v2.4.5-release-candidate-1578826573-x86_64 as @structre40 informed it seemed to work.

Edit: Decided to try a slightly newer release to help narrow down the changes that caused the issue... Used: OpenShot-v2.5.1-release-candidate-1583020661-x86_64 and it's working the video previews at the proper speed with sound :)

**Comment by VINT64** [comment]
Same issue for me. Everything works fine till version 2.5.1, starting from 2.6.0 preview is painfully slow no matter the settings. 
OS: Win 7 Pro 64-bit, CPU: AMD FX(tm)-8350 Eight-core Processor 4.00GHz, RAM: 16GB

Ping me if you need any more info about program preferences.

**Comment by awunes** [comment]
Do we have any progress on this issue? I'm about to try a more recent version. I need the updated 2.6.x as it has "stabilize" effect that I'm looking for.

**Comment by awunes** [comment]
In the #4568 bug they had some luck removing the .openshot_qt folder on fedora and 2.6.2 - go see [robin-a-meade's](https://github.com/OpenShot/openshot-qt/issues/4568#issuecomment-1045149842) comment. I attempted the same and found a new bug #4688. 

I also attempted using build: OpenShot-v2.6.1-dev-daily-9097-a86097a3-2b8b05c7-x86_64 and removing the same folder. 

Seemed to help except it's not playing sound and the playback is too fast, about 4x speed. I tried reducing via time>slow>forward>1/4 and manually setting to .25 but didn't slow it down.

here's the openshot-qt.log file (modified for privacy only
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/8101473/openshot-qt.log)

**Comment by 420pootang69** [comment]
> OpenShot-v2.4.5-release-candidate-1578826573-x86_64

Thanks SO MUCH for this. I only recently found out about open shot and it's exactly what I've been looking for, but neither the stable or daily builds work for me. The preview is completely broken and the software crashes constantly.

Closest version to 2.4.5 I could find on the repo was release V2.4.4, but it works wonderfully. All videos preview in full resolution without issue and I haven't had one crash. The application is also far snappier.

It's clear someone broke something and it's clear when it happened. I'm not a programmer, but surely someone can look at the changes made between the working and broken builds and start reverting code until the issue is fixed, highlighting where it is?

I'm on a Ryzen 3700X by the way. I'm mentioning this as I see lots with the same type of issues since 2.5 seem to be on AMD systems.

**Comment by awunes** [comment]
> It's clear someone broke something and it's clear when it happened. I'm not a programmer, but surely someone can look at the changes made between the working and broken builds and start reverting code until the issue is fixed, highlighting where it is?

I really hope they take this advice/suggestion - It'd be nice to have access to the improved version :(

**Comment by DanPinGF** [comment]
OpenShot has not been updated since May. This makes the software so unstable, I think it's the time to start sorting thousands of issues with it.

**Comment by Colorjet3** [comment]
Please download the latest DEV Daily build of v3.0.0 and give it a try.
