### ISSUE TITLE
Playback crawls/fails after resuming from sleep

### ISSUE THREAD

**Issue by StefanCamilleri** [OpenShot/openshot-qt#4376]
**Describe the bug**
When OpenShot is left open during a sleep, playback does not work after resuming.

**Steps to reproduce the behavior:**
1. Open a project
2. Put PC to sleep
3. Resume PC
4. Press play
5. Speed is extremely slow with no audio. There are no error messages.

**Expected behavior**
Video should play as before sleep.

**System Details**
- OpenShot Version: 2.5.1
- libopenshot Version:  0.2.5
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.0-dev-daily-8190-d58febf1-5ec3bc21-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/yk5rdi1iupea2hw0i3y2psrw3crm6d2z/openshot-qt.zip) (5 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by speedytechdev** [comment]
Hi @StefanCamilleri , Thank you for bringing this to our attention. I will mark this issue as a bug and hopefully, our dev team can fix this. Enjoy the rest of your day 😀

**Comment by DanPinGF** [comment]
I'm having this issue, too. It even occurs when a different audio source is disconnected and OpenShot is using that source. It's easy to interpret that OpenShot cannot detect audio sources all at once. It can only rely on a single source; therefore changing the audio output does nothing.

**Comment by DanPinGF** [comment]
Duplicate of #4303 - Okay... I'm seeing someone else has the same problem.

**Comment by pletiplot** [comment]
I am confirming the issue as well. The only recovery from the state is to save the project, restart the openshot and reopen the project.

**Comment by JacksonRG** [comment]
Just to rule out Openshot slowing down after being open too long (a whole different kind of issue), does the performance drop even if you have a very short time set for your machine to sleep?

**Comment by StefanCamilleri** [comment]
That is correct.

**Comment by JacksonRG** [comment]
Cool, Thanks for checking that for me

**Comment by DanPinGF** [comment]
@JacksonRG - This still needs to be resolved.

**Comment by Colorjet3** [comment]
Hello @DanPinGF Please verify if this issue still exists in the latest DEV Daily Build (oepnshot.org/download/#daily).
Two issues you have reported:
1.  Playback crawls/fails after resuming from sleep.
2.  No audio after resuming from sleep (this is a documented and in the queue to be fixed -https://trello.com/c/jL7t92qC/36-no-audio-after-resuming-from-sleep-windows)

Thank you!

**Comment by DanPinGF** [comment]
@Colorjet3 - The crawling issue has been fixed in version 3.0.0, but not the audio problem. Today, when I tried reproducing it on the latest version, playback appeared to be working smoothly, but no sound is being emitted from the Video Preview.

**Comment by Colorjet3** [comment]
Hello @DanPinGF Like I mentioned above, no audio after resuming from Sleep mode in Windows is a known issue and is in the queue to be fixed.  For now, you need to restart OpenShot.

If you are having a different issue then please create a new ticket.

**Comment by Chealer** [comment]
> Hello @DanPinGF Like I mentioned above, no audio after resuming from Sleep mode in Windows is a known issue and is in the queue to be fixed.

Thanks @Colorjet3 but where is it tracked?
