### ISSUE TITLE
open shot file openning problem

### ISSUE THREAD

**Issue by SreeMallick** [OpenShot/openshot-qt#4377]
**Describe the bug:**

**Steps to reproduce the behavior:**

**Expected behavior:**

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by JacksonRG** [comment]
Hi, if you're using windows, and are seeing a `"Error Opening Project, name "ex" is not defined"`, Please try downloading our daily build on https://www.openshot.org/download/ .

Otherwise, could you describe the issue you're having?

**Comment by xAzhyx** [comment]
Hi! 
I downloaded the app today and use it and I had this problem too in all my projects saved.
The only way to app open the project again that I found was:
1 - Open project file with a code editor.
2 - In all the project, all `path:` words were without quotation marks.
3 - Update all path words with quotes `"path":`
4 - Save again project file.
5 - And then I could open the project.

If I save again and close the project, the app saves again with this error.
Maybe this problem has already been solved but he sent this comment in case it helps in any way. Thanks!

**Comment by JacksonRG** [comment]
hi @xAzhyx props to you for troubleshooting it yourself. I made a fix, and if you download the daily build [here](https://www.openshot.org/download/) I made a change so that it no longer creates invalid project files, and also it will repair any project files that were broken.

Let me know if that helps!

**Comment by Pegiou** [comment]
Hi! I have the same issue - I ve recently downloaded the App, used today saved my project and cannot open it anymore getting the "ex not defined" error. I downloaded again the daily build you recommended and still no ..I hope it is possible to recover my work in a way..

**Comment by JacksonRG** [comment]
@Pegiou If you have downloaded the daily build, you should no longer be getting the "ex not defined". I made a fix so you should at least get a more descriptive error message. Are you?

Also could you attatch your log files?
Instructions [here](https://github.com/OpenShot/openshot-qt/wiki/Issue-Logging) for getting log files

**Comment by xAzhyx** [comment]
Hi @JacksonRG , it works now! Thanks and nice job =)

**Comment by Pegiou** [comment]
Indeed @JacksonRG, it works now!
I downloaded indeed the daily build and worked and even recovered my
project !
Super thanks!
