### ISSUE TITLE
OpenShot (2.6.0 Appimage) does not render using the graphic card in Debian Buster with Optimus 

### ISSUE THREAD

**Issue by fandres** [OpenShot/openshot-qt#4379]
Hi, I am trying to render using the NVIDIA graphic card, but I can not do it. I have no problem rendering with the CPU. 

![Op1](https://user-images.githubusercontent.com/7121772/131678976-d7cfa3d1-4ad5-4a3a-80b9-14406cd3a943.png)

  OpenShot version: 2.6.0 Appimage 
  OS: Debian 10 Buster
  Graphic card: Optimus Intel/ NVIDIA Corporation GM107M [GeForce GTX 860M] (rev a2
  Driver Version: 460.73.01 

I am running the application from the terminal using the command: 
  vblank_mode=0 primusrun ./OpenShot-v2.6.0-x86_64.AppImage

Terminal Log:
  INFO main_window: updateStatusChanged
  INFO project_data: Scale all keyframes by a factor of 0.8333333333333334
  Encoding Device Nr: 0
  INFO export: Error type string: **Could not create hwdevice**

**Comment by speedytechdev** [comment]
Hi @fandres, Our dev team is looking into this bug. If you could provide us with more info that would be greatly appreciated. We need the following information please:

- [ ] Steps to reproduce the behaviour: 
- [ ] Any log files (Only if they are generated )

Thank You and enjoy the rest of your day.
Speedytechlive - Support Team

**Comment by fandres** [comment]
Steps to reproduce the behaviour:

![ops26](https://user-images.githubusercontent.com/7121772/131920229-ef294940-c0dd-4280-aaf9-6134e410c3b2.gif)

**Comment by fandres** [comment]
> 
>     * [ ]  Any log files (Only if they are generated )
> 
[log.txt](https://github.com/OpenShot/openshot-qt/files/7101937/log.txt)

**Comment by speedytechdev** [comment]
Hi @fandres , Thank you for getting all of that info for me it really helps. Sorry for the delayed response. Our dev team will check this out and will hopefully have a fix for you soon. They will contact you if they need anything else.

Thank You and enjoy the rest of your day.
Speedytechlive - Support Team

**Comment by fandres** [comment]
Great, thank you very much, a hug
