### ISSUE TITLE
Render Video in Command Line?

### ISSUE THREAD

**Issue by leizongmin** [OpenShot/openshot-qt#438]
Is there any way to export video from a *.osp file in command line. I have found that OpenShot (version 1.4.3) includes a command **openshot-render**, but it's not found in OpenShot (version 2.2).

**Comment by DylanC** [comment]
@leizongmin - Not at the moment but it may become an option in the future. Thanks.

**Comment by scottkosty** [comment]
Has this been implemented yet? If not, can we reopen this as a feature request? The 15 thumbs up make me think several people would be interested in this potential feature.

Thank you!

**Comment by DylanC** [comment]
@scottkosty - Just saw this notification now. Thanks for the suggestion. Reopened.

**Comment by scottkosty** [comment]
I went through the recent release notes and did not see anything related to this (I only saw something related to *Blender* command line).

**Comment by scottkosty** [comment]
I believe that the feature proposal is still relevant.

**Comment by Colorjet3** [comment]
Hello @scottkosty Please provide me with the "Why" this is a nice feature to have and a use case.  Meanwhile, I am going to contact the lead developer to see this is currently available, and if yes, is there any documentation on it.  If not, is it something worth exploring.

Thank you in advance!

**Comment by tomislacker** [comment]
@Colorjet3 I have been following this issue as well and I think it would be a great value-add for when you're composing a larger project, being able to zip/tar up the contents and send to a more powerful machine that is headless to complete the final rendering. Something like pushing to an AWS S3 Bucket, that I can trigger a workflow from, that runs on a headless machine under one of the managed services (EC2, ECS, Fargate, Batch).

**Comment by Colorjet3** [comment]
> @Colorjet3 I have been following this issue as well and I think it would be a great value-add for when you're composing a larger project, being able to zip/tar up the contents and send to a more powerful machine that is headless to complete the final rendering. Something like pushing to an AWS S3 Bucket, that I can trigger a workflow from, that runs on a headless machine under one of the managed services (EC2, ECS, Fargate, Batch).

Thank you @tomislacker for this feedback.  I already have informed the lead developer of this issue/request and your explanation/reasoning will help further give this a higher priority as an enhancement request.

I know that one of the future enhancements is to have the ability to queue exports like some other applications do.  I do understand that it is not the same as what you describe so we'll see what the DEV team will say about it.

**Comment by Colorjet3** [comment]
This has been logged as an enhancement request.
