### ISSUE TITLE
Add to 'to the effects' effect of blinking.

### ISSUE THREAD

**Issue by xb3b6** [OpenShot/openshot-qt#4384]
This effect is present in many editors (damn, even on Android). 
Why is it still not and should it be expected?

**Comment by JacksonRG** [comment]
What do you mean by effect of blinking?

**Comment by xb3b6** [comment]
![OpenShot](https://user-images.githubusercontent.com/80679015/131949277-1174afeb-401c-4a83-ae42-846e62603b43.gif)
I did all this from Android in a few clicks.
