### ISSUE TITLE
OpenShot keeps force closing! 

### ISSUE THREAD

**Issue by ghost** [OpenShot/openshot-qt#4385]
**Describe the bug**
Basically the application likes to force close it self after using OpenShot within a half hour period.

**Expected behavior**
The application to force close it self all the time now 😞.

**System Details**
- OpenShot Version: 2.6.0
- libopenshot Version:  0.2.6
- Platform: Windows-10-10.0.19041
- Processor: AMD64 Family 23 Model 8 Stepping 2, AuthenticAMD
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-GB', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.0-dev-daily-8190-d58febf1-5ec3bc21-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/px0lhoi8jvcurc3ckickbvxi5b7xulla/openshot-qt.zip) (135 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Comment by speedytechdev** [comment]
Hi @DanTMan64 , We believe this is a common issue at the moment. Our dev is working as fast as they can to fix the issue. Just to help speed how the fix could you please let us know what steps you took the recreate the bug or is it completely random? 

Thank You and enjoy the rest of your day.
Speedytechlive - Support Team

**Comment by DanTMan64** [comment]
No the daily build did nothing but the same problem had happened after installing the daily build.

I didn’t cause this bug to happen it just did it unexpectedly.

**Comment by speedytechdev** [comment]
Thank you for that 😃 

Sorry If It sounded like I was blaming you.

Thank You and enjoy the rest of your day.
Speedytechlive - Support Team

**Comment by DanTMan64** [comment]
@speedytechdev no worries 👍 🙏 when will this be fixed do you think?

**Comment by speedytechdev** [comment]
@DanTMan64 Unfortunately I don't have an answer for this. It depends on many things. Since your bug stops Openshot from working it's probably high on the list for our dev team. 

Thank You and enjoy the rest of your day.
Speedytechlive - Support Team

**Comment by DanPinGF** [comment]
I've actually noticed that problem, too. If you play too rough with OpenShot's features, it crashes with libopenshot.dll and 0xc0000005. There's probably a defect in said module.
