### ISSUE TITLE
New GUI & Update

### ISSUE THREAD

**Issue by ghost** [OpenShot/openshot-qt#4386]
**Describe the new feature:**
A new Graphical User Interface and make a 'Check for Updates' within the program.

**Describe the solution you'd like:**
Newer GUI and a Check for Update.

**Comment by speedytechdev** [comment]
Hi @DanTMan64, Thank you for bringing up this amazing idea. Our dev team will look through this and will contact you if they have any questions or concerns. Hopefully, you can see it in Openshot one day. Enjoy the rest of your day 😀

**Comment by DanTMan64** [comment]
Hi 👋 @speedytechdev thanks 🙏 for letting me know.
