### ISSUE TITLE
Animated Titles 😊

### ISSUE THREAD

**Issue by ghost** [OpenShot/openshot-qt#4388]
**Describe the new feature:**
New animated titles (blender)

**Describe the solution you'd like:**
Basically make new blender animated titles.

**Comment by speedytechdev** [comment]
Thank you for bringing up this amazing idea. Our dev team will look through this and will contact you if they have any questions or concerns. Hopefully, you can see it in Openshot one day. Enjoy the rest of your day 😀

Speedytechlive - Support Team

**Comment by JacksonRG** [comment]
I like the idea. Do you have any specific ideas of the kind of titles you'd like to see?
