### ISSUE TITLE
The application does not start in w10 x64 v2.2.0

### ISSUE THREAD

**Issue by carlosnewmusic** [OpenShot/openshot-qt#439]
![imagen](https://cloud.githubusercontent.com/assets/19379457/21461467/f8340cc8-c951-11e6-8887-793abba06f8b.png)

**Comment by BF3000** [comment]
It is working now.
But sometimes it is happened with fresh beta builds.
Mostly because someone forget to delete some links, and not testing it on the clear windows instalation.

**Comment by carlosnewmusic** [comment]
Ok thanks, I already closed two bugs with this
