### ISSUE TITLE
When selecting the imported file, I right click "split clip". Once selected, I play video. The video...

### ISSUE THREAD

**Issue by CheezieCheeze420** [OpenShot/openshot-qt#4391]
When selecting the imported file, I right click "split clip". Once selected, I play video. The video in preview is choppy/glitch. I pause and close miniwindow. Program carshes. I start openshot and import different file and same thing happens. I try a third time, but this time, after importing a 3rd different file, I dont split clip, instead, I drag imported clip to track one. When I review the video, and it is choppy. I watch video without OpenShot and the video works very well. I cannot edit videos due to poor quality of OpenShot, and my app crashes when I try to close out.

**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 2.6.1
- libopenshot Version:  0.2.7
- Platform: Windows-10-10.0.19041
- Processor: AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-release-candidate-8238-59878784-d588dbd6-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/x8hiryqt8sjqm6f1vaz4u7k67vc1cnw2/openshot-qt.zip) (104 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by speedytechdev** [comment]
Hi @CheezieCheeze420 , Have you tried the [daily build](https://www.openshot.org/download/)? If the issue still appears their I'm happy to file this as a bug?

**Comment by speedytechdev** [comment]
@JacksonRG Could be related but not sure https://github.com/OpenShot/openshot-qt/issues/4375

**Comment by CheezieCheeze420** [comment]
Yes, I have tried the daily debug.

**Comment by JacksonRG** [comment]
@speedytechdev Looks like it is.

@CheezieCheeze420 When you preview the clip, how does the CPU usage behave? You can open task manager, and view CPU under the performance tab. I'm asking because I've also seen reports of the CPU usage staying low when preview is slow

**Comment by Colorjet3** [comment]
Please download the latest DEV daily build from openshot.org/download/#daily and let us know if the problem persists.

**Comment by Colorjet3** [comment]
No response from user.
