### ISSUE TITLE
slow preview

### ISSUE THREAD

**Issue by c2farr** [OpenShot/openshot-qt#4393]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 2.6.0
- libopenshot Version:  0.2.6
- Platform: Windows-7-6.1.7601-SP1
- Processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Skipped this step

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/q5u3y73wbw709zylnnke8ekpmess11y2/openshot-qt.zip) (7 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by speedytechdev** [comment]
Hi @c2farr , From what I can tell it looks like the same issue as [this](https://github.com/OpenShot/openshot-qt/issues/4375). Am I wrong?

**Comment by c2farr** [comment]
Yes. In v 2.5 I had the identical problem that I have now with 2.6, except now with 2.6, I cannot rectify it. With 2.5, closing the program then reopening it fixed the problem. Not so with 2.6. Playback creeps along at a speed that would take literally about 1 minute to get through 1 second. The first few hundredths of a second were a little faster than than those that followed, Then by maybe 50/100 it would grind to a halt. I tried uninstalling and reinstalling a couple of times. The most recent install was 32 bit and I still have the issue.  Win 7, 64 bit, 16 GB, intel i5 3470 3.20 Ghz

**Comment by speedytechdev** [comment]
Since it's the same bug can you put all your notes about the issue in this [one](https://github.com/OpenShot/openshot-qt/issues/4375) since it will make it a lot faster to find a solution. Hopefully, you understand and I'm sorry for any inconvenience this causes you.

Thank You and enjoy the rest of your day.
Speedytechlive - Support Team
