### ISSUE TITLE
Waveform disappears from view on timeline after segment is split

### ISSUE THREAD

**Issue by SoftwareTesterScott** [OpenShot/openshot-qt#4394]
**Describe the bug**
When editing a video with waveform enabled, splitting the video may result in a segement no longer showing the waveform, instead clip shows all black. NOTE: Several other issues were identified during a video capture for this and are mentioned below, but this bug report focuses on disappearing waveforms. 

**Steps to reproduce the behavior:** Note: behaviour is intermittent and cannot be reliably produced on demand but was happening frequently. 
1. Import a file to a timeline, enable waveform view.
2. Use the split icon to do multiple splits of a file,  EG: import an 18 minute file and split file to create a 30 second trim
3. delete the 30 second trim, and adjust the right part of the original video to join the left part.
4. Repeat several times.
NOTE: A Video recording was made when this occurred, See https://youtu.be/swaMuWVQtkw?t=864 approx 10 trims has been before this first appeared. 

**Expected behavior**
After a split of a video where waveform is shown, both parts of the split still show a waveform.

**System Details**
- OpenShot Version: 2.6.0-dev
- libopenshot Version:  0.2.6-dev
- Platform: Linux-5.11.0-27-generic-x86_64-with-glibc2.29
- Processor: x86_64
- Machine: x86_64
- Python version: 3.8.10
- Qt5 version: 5.12.8
- PyQt5 version: 5.14.1
- Qt Detected Languages: ['en-AU', 'en']
- LANG Environment Variable: en_AU.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-release-candidate-8238-59878784-d588dbd6-x86_64.AppImage NOTE: Issue present in daily build which was the latest available when it was recorded, which was several days ago and has not been reverified since.

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/ig6wi9u40l57ad4soy6uthg00b3uhfe4/openshot-qt.zip) (304 KB)
- libopenshot.log: File too small or empty (not uploaded) 132 bytes.

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
A screen recording was done showing the issue, see https://www.youtube.com/watch?v=swaMuWVQtkw This recording doesnt contain any personal information and several other anomalies were identified in the recording. I havent created a bug for each, but am happy to be contacted to provide further details. 

This video is a capture ive made while doing a video editing of a recording of me talking using Openshot. Volume of me speaking in the video being edited has been deliberately turned down to enable differentiation between me narrating the editing and reading the text in the video being edited. (please dont turn up to try to hear me talking in the video being edited as when i narrate, it p...

**Comment by speedytechdev** [comment]
Hi @SoftwareTesterScott , So I looked through your issue report and just have to say well done. It has so much detail and makes finding bugs easy.  I'm happy to file this as a bug since there is plenty of evidence.  

I know it's probably a pain but if you could create new issues for the other bugs you found in the video. This will allow our dev team to be able to find fixes faster. 

Our dev team will contact you if they need any other information. If you have any questions or concerns please feel free to let us know.

Thank You and enjoy the rest of your day.
Speedytechlive - Support Team

**Comment by SoftwareTesterScott** [comment]
No Problem, im starting now.

I wlll also put in an enhancement request to see if viewing the waveforms
can be made default as an opt-in checkbox in settings too.

Thanks,
Scott.

**Comment by DanPinGF** [comment]
I'm having a similar issue on Windows. Zooming in or out the timeline, or altering the track, while a waveform is shown disappears. I would have to right-click on the track and select 'Show > Waveform' again for it to appear.
