### ISSUE TITLE
Closes randomly when various parameters are being changed

### ISSUE THREAD

**Issue by mapandauk** [OpenShot/openshot-qt#4395]
**Describe the bug**
Whilst dragging parameters to adjust, Openshot closes without displaying any error.  I've experienced this adjusting effects such as chroma/saturation (as per the attached log files) but also many other parameters on the track itself, and I think whilst adding media to tracks.  This has been consistently replicable, but not when I set logging to verbose, so whether that has any effect on memory handling I don't know.  I may just have been unlucky.

**Steps to reproduce the behavior:**
1. Open Openshot
2. Add media to library
3. Add media from library to any track
4. Add an overlay effect such as Chroma
5. Adjust the level of the effect
6. You may need to do this several times
7. App closes

**Expected behavior**
Expected App not to close

The system details below are not correct.  The processor is M1

**System Details**
- OpenShot Version: 2.6.1
- libopenshot Version:  0.2.7
- Platform: Darwin-20.5.0-x86_64-i386-64bit
- Processor: i386
- Machine: x86_64
- Python version: 3.7.11
- Qt5 version: 5.15.0
- PyQt5 version: 5.15.1.dev2007111314
- Qt Detected Languages: ['en-GB']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-release-candidate-8238-59878784-d588dbd6-x86_64.dmg

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/q99sl56f4nnt6wagpaazli4m0fhdi5mh/openshot-qt.zip) (178 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/q99sl56f4nnt6wagpaazli4m0fhdi5mh/libopenshot.zip) (0 KB)

**Exception / Stacktrace**
```4   libopenshot.21.dylib                0x000000013be56952 _ZNopenshot::CacheMemory::GetFrame + 162
5   libopenshot.21.dylib                0x000000013be56af8 _ZNopenshot::CacheMemory::GetSmallestFrame + 232
6   libopenshot.21.dylib                0x000000013bf12a35 _ZNopenshot::VideoCacheThread::run + 949
7   libopenshot-audio.8.dylib           0x000000013c299a2a _ZNjuce::Thread::threadEntryPoint + 282
8   libopenshot-audio.8.dylib           0x000000013c2c0f9a _ZNjuce::threadEntryProc + 26
9   libsystem_pthread.dylib             0x00007fff2035e8fc _pthread_start + 224
10  libsystem_pthread.dylib             0x00007fff2035a443 thread_start + 15
```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by speedytechdev** [comment]
Hi @mapandauk, Thank you for bringing this issue up. I will label this issue as a bug and hopefully, someone from our dev team can get this sorted for you.

Thank You and enjoy the rest of your day.
Speedytechlive - Support Team

**Comment by speedytechdev** [comment]
Hi @mapandauk, Have you tried the [daily build](https://www.openshot.org/download/) if the issue still happens using the daily build I'm happy to mark this as a bug.

Thank You and enjoy the rest of your day.
Speedytechlive - Support Team

**Comment by mapandauk** [comment]
Hi @speedytechdev, Yes I had tried several dailies before downloading the most recent release candidate.  I've just gone back to the most recent daily - OpenShot-v2.6.0-dev-daily-8224-5a8ffe36-5ec3bc21-x86_64.dmg - and it still happens

**Comment by speedytechdev** [comment]
No worries then. I will label it as a bug now.

Thank You and enjoy the rest of your day.
Speedytechlive - Support Team

**Comment by DanPinGF** [comment]
The problem affects Windows, too. If I play too rough with OpenShot's features, say the Timeline's scrub, it crashes with libopenshot.dll and 0xc0000005. It must be a defect of some sort... probably.
