### ISSUE TITLE
Ctrl+Mouse scroll on the timeline should zoom into where the mouse cursor is positioned

### ISSUE THREAD

**Issue by aneurysm1985** [OpenShot/openshot-qt#4397]
Firstly, a **big thanks** to the team, especially @JacksonRG who notified me that you had implemented [my last feature request](https://github.com/OpenShot/openshot-qt/issues/4219) into OpenShot. It is great to now be able to see frame-by-frame increments on the timeline. Thanks for incorporating this into the software!

My current observation is that **the timeline zooming-in behaviour is not as intuitive as other editing software** that I have tried. I use Windows, and usually hold down the **Ctrl key**, and then use my **mouse wheel** to scroll into a particular point on the timeline that I want a closer look at.

Other software such as Audacity seem to notice where the mouse cursor is positioned on the timeline, and then use **the cursor** as the 'target' that the zooming centres on. However, OpenShot seems to zoom in and out, with the **play-head** as the point that the zooming is centred on.

My feature request is to **make zooming to the mouse cursor position on the timeline to be the default behaviour**, as this is what makes the most sense to me as a user. Does anyone else agree or disagree?

**Comment by JacksonRG** [comment]
Glad you like it!

I suppose in things like gimp I find myself zooming "away" from one side, and then "into" the position I'm trying to get to.

I'll take a look into zooming relative to the position of the mouse instead of the playhead.
