### ISSUE TITLE
v. 2.6.1 - Not translated string in the installer

### ISSUE THREAD

**Issue by bovirus** [OpenShot/openshot-qt#4398]
There is an untranslated string in the installer

![image](https://user-images.githubusercontent.com/1262554/132312042-b192cc43-f1e7-4ecc-9417-e9e507efc04e.png)

The italian string is

"Aggiungi un'eccezione al firewall di Windows per l'invio di statistiche anonime sull'uso del programma e sugli errori (opzionale)."

**Describe the bug:**

**Steps to reproduce the behavior:**

**Expected behavior:**

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by speedytechdev** [comment]
Hi @bovirus , Thank you for bringing this up. I will mark this as a bug and someone from our dev team will check it out.


Thank You and enjoy the rest of your day.
Speedytechlive - Support Team

**Comment by bovirus** [comment]
@stale

Sorry but i beleive that has a sense to close if the user no answer.

I believe that has no sense to close if if none of author answer that the problem is fixed.

speedytechdev answer that it will be fixed but no one confirm it now.

Then please close this issue only if the problem is fixed.
