### ISSUE TITLE
OpenShot 2.2 not recognize Blender and Inkscape (macOS Sierra)

### ISSUE THREAD

**Issue by in3pid0** [OpenShot/openshot-qt#440]

**Comment by juckendesAuge** [comment]
Same here under Fedora 25 (64 Bit) i have used OpenShot-v2.2.0-2-g5a2acb8-49-603-x86_64.AppImage.

**Comment by Kagetsuki** [comment]
Have you tried setting the paths to blender and inkscape to absolute paths in the preferences window?

**Comment by ankitpati** [comment]
Can you please try the latest stable [release](https://github.com/OpenShot/openshot-qt/releases/download/v2.2.0/OpenShot-v2.2.0-x86_64.dmg "OpenShot 2.2), and let us know if the issue persists?

**Comment by Kagetsuki** [comment]
Seconding @ankitpati and I suggest this issue be closed until further feedback.

**Comment by ankitpati** [comment]
Owing to lack of activity, this issue is being closed. Please reopen if necessary.
