### ISSUE TITLE
Splitting and removing a segment from a clip removes two segments. 

### ISSUE THREAD

**Issue by SoftwareTesterScott** [OpenShot/openshot-qt#4403]
**Describe the bug**
When splitting and removing a segments from a clip, the segment selected was removed as well as other segments before it. 

**Steps to reproduce the behavior:**
Note: steps to reproduce cannot reproduce the bug on demand. Several clips were removed successfully before this bug was found
1. Add a file to a timeline
2. Split video into smaller segments (remove gaffes made in imported video) and delete those segments 
3. Repeat several times.
4. On deletion of a segment

**Expected behavior**
Only that segment is deleted,  Actual behaviour  deleted segments prior to it.  See below for a recording of the issue happening. 

**System Details**
- OpenShot Version: 2.6.0-dev
- libopenshot Version:  0.2.6-dev
- Platform: Linux-5.11.0-27-generic-x86_64-with-glibc2.29
- Processor: x86_64
- Machine: x86_64
- Python version: 3.8.10
- Qt5 version: 5.12.8
- PyQt5 version: 5.14.1
- Qt Detected Languages: ['en-AU', 'en']
- LANG Environment Variable: en_AU.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Not able to verify issue still exists in daily build

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/ig6wi9u40l57ad4soy6uthg00b3uhfe4/openshot-qt.zip) (304 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)

A screen recording was done showing the issue, see https://youtu.be/swaMuWVQtkw?t=1371 This recording doesnt contain any personal information and several other anomalies were identified in the recording.

**Comment by SoftwareTesterScott** [comment]
I have another video and log files (debug enabled) where this occurs.  Im unsure how to get you copies of the logs (Note To Self: so i can find them easier later, stored on my computer with "8Sep21_3-MultipleYellowBarsAndTwoSegmentsDeleted" )
Video is split into approx 9 segments and when segment 8/9 is deleted, Segment 1/9 gets removed too.  See deletion at 0:35 videotime, about 5 seconds after where the video should start. https://youtu.be/UjxwHtq-x14?t=30

**Comment by ghost** [comment]
Ive seen another case where this happened, check clip removal approx 15 seconds in https://youtu.be/PLRdEnCU8WQ?t=12 Recording doesnt contain any personal information.  Logs are of 2.6.1dev and had debug enabled. 
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/7153154/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/7153155/openshot-qt.log)
