### ISSUE TITLE
Undo function doesnt undo previous item and undoes item many steps prior (add project file)

### ISSUE THREAD

**Issue by SoftwareTesterScott** [OpenShot/openshot-qt#4404]
**Describe the bug**
Undo functionality doenst undo previous actions. A file edit where approximately 15 splits and deletes was undone three or four times and this resulted in the only project file present being removed. 

Note: bug may be a result of a cascading issue as this bug was seen immediately after another bug (raised seperately) which deleted two segments after the program was commanded to remove one.  See video for a recording of bug below

**Steps to reproduce the behavior:**
1. Load and import a file, add to a track
2. Split trim and condense file approx 15 times. 
3. Trigger undo function

**Expected behavior**
Undo feature would undo split and trims before removing the file from the Project Files. 

**System Details**
- OpenShot Version: 2.6.0-dev
- libopenshot Version:  0.2.6-dev
- Platform: Linux-5.11.0-27-generic-x86_64-with-glibc2.29
- Processor: x86_64
- Machine: x86_64
- Python version: 3.8.10
- Qt5 version: 5.12.8
- PyQt5 version: 5.14.1
- Qt Detected Languages: ['en-AU', 'en']
- LANG Environment Variable: en_AU.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Not able to verify issue still exists in daily build

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/ig6wi9u40l57ad4soy6uthg00b3uhfe4/openshot-qt.zip) (304 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
A screen recording was done showing the issue, see https://youtu.be/swaMuWVQtkw?t=1369  The video contains a complete recording from opening to this bug and shows it behaving normally,, me doing a split and trim, then doing an undo after the program removes two clips instead of one (two clip removal already raised as seperate bug), Undo is triggered. 

I should be able to spend some time investigating this further and focusing on getting steps to quickly reproduce the Undo bug if requested. 

This recording doesnt contain any personal information and several other anomalies were identified in the recording but video hasnt been trimmed in case it can be used to help determine complete steps to reproduce.

**Comment by JacksonRG** [comment]
Not sure if you've opened that second bug in another issue, but it looks like you didn't deselect other files before right clicking to delete a file.

It is true that undo will work a single action at a time, even if a single user action involves multiple actions of openshot. A solution to that issue is being worked on.

**Comment by SoftwareTesterScott** [comment]
RE: "deselect other files before right clicking to delete a file". The file 2p3p2.mkv should be selected throughout the entire editing process. Once it was added to Track 5, i dont remember clicking on it again. 

I may have somehow selected the trimmed sections prior for them to be deleted by the Remove Clip action at 23:12 in the screen recording, but i thought i did the same process i did for each trim prior. 

The video still shows 11 edited segments in the zoom bar as present and would think that Undo would rejoin these and readd the previously deleted segments prior to removing the 2p3p2.mkv file from the Project files. 

Undo is clicked for the first time in the recording at 23:23 and results in text reappearing in the video display, but not clip appearing back on Track5. 

Im happy if this is closed as a duplicate bug of an existing one, but was requested to raise them individually by SpeedyTechDev

**Comment by Raziel0315** [comment]
1/29/22
Undo still is not working properly.  I tried to undo the most recent trim, but, instead, one of the clips just reverted to its previous size and left the slice untouched.  The malfunctioning undo command is easy to duplicate.

**Comment by drking-c** [comment]
This is such a major problem that stops me to update from 2.5 Not being able to undo stuff you tried out completely breaks the creative process. Is there anything I is a user can do to help getting this fixed anytime soon?

**Comment by JacksonRG** [comment]
@drking-c I know I've started a branch to fix this. Also, the current work around is to press `ctrl+z` two additional times. Far from ideal, but still allowing for experimenting. I'm taking another look at how our action history is stored, and how we can rework the razor into one "action"

**Comment by jonoomph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Transactions in action history](https://trello.com/c/rKih0kbs/71-transactions-in-action-history)

**Comment by drking-c** [comment]
This should not be stalled. That is a major problem. Or is there another active ticket for this issue?

**Comment by Colorjet3** [comment]
This should be resolved in the latest DEV Daily Build of v3.0.0.  Please give it a try and let us know either way.
