### ISSUE TITLE
NO SE REPRODUCE EL SONIDO

### ISSUE THREAD

**Issue by hbrsystems** [OpenShot/openshot-qt#4406]
**Describa el problema**
Pruebo en windows 10 los controladores de sonido 
Altavoces (Realtek(R) Audio) y Altavoces (FxSound Audio Enhancer)
y en ambos la música se escucha perfectamente.

Cuando se carga OPENSHOT muestra la ventana "Error de audio" con el mensaje:
"Corrija el siguiente error y reinicie OpenShot
No such device: Altavoces (Realtek(R) Audio)
 
Hago el cambio en preferencias de previsualización, reinicio OPENSHOT pero muestra el error con el controlador que le definí.

**Comment by ghost** [comment]
from google translate:
test in windows 10 the Sound drivers
Speakers (Realtek (R) Audio) and Speakers (FxSound Audio Enhancer)
and in both the music is heard perfectly.

When OPENSHOT loads it displays the "Audio Error" window with the message:
"Please correct the following error and restart OpenShot
No such device: Speakers (Realtek (R) Audio)

I make the change in preview preferences, I restart OPENSHOT but it shows the error with the controller that I defined for it.
