### ISSUE TITLE
OpenShot doesn't open on Windows 10

### ISSUE THREAD

**Issue by marconimayer** [OpenShot/openshot-qt#4408]
**Describe the bug**
I installed OpenShot today, but when I try to open, it just appear a small windows for less than a second and than close.

**Steps to reproduce the behavior:**
1. Open the software
2. See error

**Expected behavior**
Should open normally

**System Details**
- OpenShot Version: 2.6.0
- libopenshot Version:  0.2.6
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['pt-BR', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-release-candidate-8238-59878784-d588dbd6-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/ei0ct18e5v5hfmj3h42ct6hy95qwo0p7/openshot-qt.zip) (2 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Comment by speedytechdev** [comment]
Hi, @marconimayer Sorry for the late response. Have you tried uninstalling Openshot and downloading the latest [daily build](https://www.openshot.org/download/)

Thank You and enjoy the rest of your day.
Speedytechlive - Support Team
