### ISSUE TITLE
Crash on start Lubuntu 16.10 x64 "XCB error: 3"

### ISSUE THREAD

**Issue by sol8712** [OpenShot/openshot-qt#441]
Added repository
Installed with apt-get

Any ideas? I edited my video on a crappy laptop with openshot 2.1 and it couldnt handle exporting a nice HD video, now i have a beast of a pc and openshot wont open =( help?

`sol@sol:~$ openshot-qt
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
      launch:INFO ------------------------------------------------
      launch:INFO    OpenShot (version 2.2.0)
      launch:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.2.0
         app:INFO libopenshot version: 0.1.3
         app:INFO platform: Linux-4.8.0-32-generic-x86_64-with-Ubuntu-16.10-yakkety
         app:INFO processor: x86_64
         app:INFO machine: x86_64
         app:INFO python version: 3.5.2+
         app:INFO qt5 version: 5.6.1
         app:INFO pyqt5 version: 5.7
    language:INFO Qt Detected Languages: ['en-US']
    language:INFO LANG Environment Variable: en_US.UTF-8
    language:INFO LOCALE Environment Variable: en_US
    language:INFO Skipping English language (no need for translation): en_US.UTF-8
    language:INFO Skipping English language (no need for translation): en_US
project_data:INFO Setting default profile to HDV 720 24p
ZmqLogger::Connection - Error binding to tcp://*:5556. Switching to an available port.
ZmqLogger::Connection - Error binding to tcp://*:5556. Switching to an available port.
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
         app:INFO Setting font to /usr/lib/python3/dist-packages/openshot_qt/images/fonts/Ubuntu-R.ttf
         app:INFO Setting custom dark theme
link SVGID_18_-5 hasn't been detected!
link SVGID_18_-5 hasn't been detected!
link SVGID_22_-5 hasn't been detected!
link SVGID_24_-2 hasn't been detected!
link SVGID_24_-2 hasn't been detected!
     ui_util:INFO Initializing UI for MainWindow
     ui_util:INFO Binding event MainWindow:actionNew_trigger
     ui_util:WARNING Icon theme document-new not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionOpen_trigger
     ui_util:WARNING Icon theme document-open not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionSave_trigger
     ui_util:WARNING Icon theme document-save not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionUndo_trigger
     ui_util:WARNING Icon theme edit-undo not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionSaveAs_trigger
     ui_util:WARNING Icon theme document-save-as not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionImportFiles_trigger
     ui_util:WARNING Icon theme list-add not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionImportImageSequence_trigger
     metrics:INFO Track metric: {'content-length': '35', 'pragma': 'no-cache', 'expires': 'Mon, 01 Jan 1990 00:00:00 GMT', 'access-control-allow-origin': '*', 'age': '161131', 'status': '200', 'content-type': 'image/gif', 'x-content-type-options': 'nosniff', 'date': 'Thu, 22 Dec 2016 21:41:54 GMT', 'server': 'Golfe2', 'cache-control': 'no-cache, no-store, must-revalidate', 'content-location': 'http://www.google-analytics.com/collect?cd2=3.5.2%2B&v=1&ul=en&cid=&cd4=5.7&aip=1&tid=UA-4381101-5&aid=org.openshot.openshot-qt&ua=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&cd5=Ubuntu-16.10-yakkety&cd=main-screen&av=2.2.0&cd1=0.1.3&t=screenview&cd3=5.6.1&an=OpenShot+Video+Editor', 'last-modified': 'Sun, 17 May 1998 03:00:00 GMT'} (b'GIF89a\x01\x00\x01\x00\x80\xff\x00\xff\xff\xff\x00\x00\x00,\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x02D\x01\x00;')
     ui_util:WARNING Icon theme list-add not found. Will use backup icon.
     ui_util:WARNING Icon theme list-add not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionRedo_trigger
     ui_util:WARNING Icon theme edit-redo not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionRemoveClip_trigger
     ui_util:WARNING Icon theme list-remove not found. Will use backup icon.
     metrics:INFO Track metric: {'content-length': '35', 'pragma': 'no-cache', 'expires': 'Mon, 01 Jan 1990 00:00:00 GMT', 'access-control-allow-origin': '*', 'age': '160651', 'status': '200', 'content-type': 'image/gif', 'x-content-type-options': 'nosniff', 'date': 'Thu, 22 Dec 2016 21:49:54 GMT', 'server': 'Golfe2', 'cache-control': 'no-cache, no-store, must-revalidate', 'content-location': 'http://www.google-analytics.com/collect?cd2=3.5.2%2B&v=1&ul=en&cid=&cd4=5.7&aip=1&tid=UA-4381101-5&aid=org.openshot.openshot-qt&ua=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&cd5=Ubuntu-16.10-yakkety&cd=initial-launch-screen&av=2.2.0&cd1=0.1.3&t=screenview&cd3=5.6.1&an=OpenShot+Video+Editor', 'last-modified': 'Sun, 17 May 1998 03:00:00 GMT'} (b'GIF89a\x01\x00\x01\x00\x80\xff\x00\xff\xff\xff\x00\x00\x00,\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x02D\x01\x00;')
     ui_util:INFO Binding event MainWindow:actionRemoveTransition_trigger
     ui_util:WARNING Icon theme list-remove not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionExportVideo_trigger
     ui_util:WARNING Icon theme media-record not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionUploadVideo_trigger
     ui_util:WARNING Icon theme folder-remote not found. Will use backup icon.
     ui_util:WARNING Icon theme gtk-quit not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAddTrack_trigger
     metrics:INFO Track metric: {'content-length': '35', 'pragma': 'no-cache', 'expires': 'Mon, 01 Jan 1990 00:00:00 GMT', 'access-control-allow-origin': '*', 'age': '159818', 'status': '200', 'content-type': 'image/gif', 'x-content-type-options': 'nosniff', 'date': 'Thu, 22 Dec 2016 22:03:47 GMT', 'server': 'Golfe2', 'cache-control': 'no-cache, no-store, must-revalidate', 'content-location': 'http://www.google-analytics.com/collect?cd2=3.5.2%2B&v=1&ul=en&cid=&cd4=5.7&aip=1&tid=UA-4381101-5&aid=org.openshot.openshot-qt&ua=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&cd5=Ubuntu-16.10-yakkety&cd=launch-app&av=2.2.0&cd1=0.1.3&t=screenview&cd3=5.6.1&sc=start&an=OpenShot+Video+Editor', 'last-modified': 'Sun, 17 May 1998 03:00:00 GMT'} (b'GIF89a\x01\x00\x01\x00\x80\xff\x00\xff\xff\xff\x00\x00\x00,\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x02D\x01\x00;')
     ui_util:WARNING Icon theme list-add not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionPreferences_trigger
     ui_util:WARNING Icon theme document-properties not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionPlay_trigger
     ui_util:WARNING Icon theme media-playback-start not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionJumpStart_trigger
     ui_util:WARNING Icon theme go-first not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionRewind_trigger
     ui_util:WARNING Icon theme media-seek-backward not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionFastForward_trigger
     ui_util:WARNING Icon theme media-seek-forward not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionJumpEnd_trigger
     ui_util:WARNING Icon theme go-last not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionArrowTool_trigger
     ui_util:INFO Binding event MainWindow:actionSnappingTool_trigger
     ui_util:INFO Binding event MainWindow:actionAddMarker_trigger
     ui_util:INFO Binding event MainWindow:actionPreviousMarker_trigger
     ui_util:WARNING Icon theme go-first not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionNextMarker_trigger
     ui_util:WARNING Icon theme go-last not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionFilesShowAll_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowVideo_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowAudio_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowImage_trigger
     ui_util:WARNING Icon theme edit-clear not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionTransitionsShowAll_trigger
     ui_util:INFO Binding event MainWindow:actionTransitionsShowCommon_trigger
     ui_util:WARNING Icon theme edit-clear not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionEffectsShowAll_trigger
     ui_util:INFO Binding event MainWindow:actionEffectsShowVideo_trigger
     ui_util:INFO Binding event MainWindow:actionEffectsShowAudio_trigger
     ui_util:WARNING Icon theme edit-clear not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionTimelineZoomIn_trigger
     ui_util:WARNING Icon theme zoom-in not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionTimelineZoomOut_trigger
     ui_util:WARNING Icon theme zoom-out not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionTitle_trigger
     ui_util:WARNING Icon theme font not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAnimatedTitle_trigger
     ui_util:WARNING Icon theme video-x-generic not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionFullscreen_trigger
     ui_util:WARNING Icon theme view-fullscreen not found. Will use backup icon.
     ui_util:WARNING Icon theme zoom-in not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAbout_trigger
     ui_util:WARNING Icon theme gtk-info not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionThumbnailView_trigger
     ui_util:WARNING Icon theme view-preview not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionDetailsView_trigger
     ui_util:WARNING Icon theme view-list-details not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionReportBug_trigger
     ui_util:WARNING Icon theme dialog-error not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAskQuestion_trigger
     ui_util:WARNING Icon theme im-message-new not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionTranslate_trigger
     ui_util:WARNING Icon theme stock_person not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionDonate_trigger
     ui_util:WARNING Icon theme bookmark-new not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionHelpContents_trigger
     ui_util:WARNING Icon theme help not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionSimple_View_trigger
     ui_util:WARNING Icon theme go-home not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAdvanced_View_trigger
     ui_util:WARNING Icon theme get-hot-new-stuff not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionFreeze_View_trigger
     ui_util:WARNING Icon theme locked not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionUn_Freeze_View_trigger
     ui_util:WARNING Icon theme locked not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionShow_All_trigger
     ui_util:WARNING Icon theme zoom-in not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionProfile_trigger
     ui_util:WARNING Icon theme video-x-generic not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAdd_to_Timeline_trigger
     ui_util:WARNING Icon theme list-add not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionPreview_File_trigger
     ui_util:WARNING Icon theme media-playback-start not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionRemove_from_Project_trigger
     ui_util:WARNING Icon theme list-remove not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionFile_Properties_trigger
     ui_util:WARNING Icon theme video-x-generic not found. Will use backup icon.
     ui_util:WARNING Icon theme edit-clear not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionRemoveTrack_trigger
     ui_util:WARNING Icon theme list-remove not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionRemoveMarker_trigger
     ui_util:WARNING Icon theme list-remove not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAddTrackAbove_trigger
     ui_util:WARNING Icon theme list-add not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAddTrackBelow_trigger
     ui_util:WARNING Icon theme list-add not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionRemoveEffect_trigger
     ui_util:WARNING Icon theme list-remove not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionSplitClip_trigger
     ui_util:WARNING Icon theme edit-cut not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionProperties_trigger
     ui_util:WARNING Icon theme document-properties not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionRenameTrack_trigger
     ui_util:WARNING Icon theme gtk-edit not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionUpdate_trigger
     ui_util:INFO Binding event MainWindow:actionTutorial_trigger
     ui_util:WARNING Icon theme im-message-new not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAnimation_trigger
     ui_util:WARNING Icon theme video-x-generic not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionLockTrack_trigger
     ui_util:INFO Binding event MainWindow:actionUnlockTrack_trigger
files_listview:INFO currentChanged
files_listview:INFO updateSelection
 files_model:INFO updating files model.
transition_model:INFO updating transitions model.
timeline_webview:INFO Qt Found!
timeline_webview:INFO $scope.Qt = true;
timeline_webview:INFO UpdateLayerIndex
     version:INFO Found current version: {'date': 'Sat, 24 Dec 2016 18:29:18 GMT', 'transfer-encoding': 'chunked', 'server': 'Apache/2.2.22 (Ubuntu)', 'content-location': 'http://www.openshot.org/version/json/', 'status': '200', 'content-type': 'application/json'} (b'{"openshot_version": "2.2.0"}')
 main_window:INFO foundCurrentVersion: Found the latest version: 2.2.0
effects_model:INFO updating effects model.
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
properties_model:INFO updating clip properties model.
QWidget::setMinimumSize: (dockProperties/QDockWidget) Negative sizes (20,-1) are not possible
QWidget::setMaximumSize: (dockProperties/QDockWidget) Negative sizes (524287,-1) are not possible
QWidget::setMinimumSize: (dockFiles/QDockWidget) Negative sizes (20,-1) are not possible
QWidget::setMaximumSize: (dockFiles/QDockWidget) Negative sizes (524287,-1) are not possible
QWidget::setMinimumSize: (dockTransitions/QDockWidget) Negative sizes (20,-1) are not possible
QWidget::setMaximumSize: (dockTransitions/QDockWidget) Negative sizes (524287,-1) are not possible
QWidget::setMinimumSize: (dockEffects/QDockWidget) Negative sizes (20,-1) are not possible
QWidget::setMaximumSize: (dockEffects/QDockWidget) Negative sizes (524287,-1) are not possible
QWidget::setMinimumSize: (dockVideo/QDockWidget) Negative sizes (18,-1) are not possible
QWidget::setMaximumSize: (dockVideo/QDockWidget) Negative sizes (524287,-1) are not possible
 main_window:INFO InitCacheSettings
 main_window:INFO cache-mode: CacheMemory
 main_window:INFO cache-limit-mb: 250
 main_window:INFO Creating CacheMemory object with 262144000 byte limit
preview_thread:INFO QThread Start Method Invoked
preview_thread:INFO initPlayer
 main_window:ERROR Unhandled crash detected... will attempt to recover backup project: /home/sol/.openshot_qt/backup
QWidget::setMinimumSize: (MainWindow/MainWindow) The largest allowed size is (16777215,16777215)
QWidget::setMinimumSize: (MainWindow/MainWindow) The largest allowed size is (16777215,16777215)
    tutorial:INFO process tutorial dialogs
         app:INFO Process command-line arguments: ['/usr/bin/openshot-qt']
 main_window:INFO updateStatusChanged
preview_thread:INFO onModeChanged
 main_window:INFO recover_backup
QXcbConnection: XCB error: 3 (BadWindow), sequence: 423, resource id: 46137348, major code: 2 (ChangeWindowAttributes), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 424, resource id: 46137348, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 425, resource id: 46137348, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 426, resource id: 46137348, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 428, resource id: 46137348, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 429, resource id: 46137348, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 430, resource id: 46137348, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 433, resource id: 46137348, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 437, resource id: 46137348, major code: 2 (ChangeWindowAttributes), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 438, resource id: 46137348, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 439, resource id: 46137348, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 440, resource id: 46137348, major code: 20 (GetProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 444, resource id: 46137348, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 445, resource id: 46137348, major code: 19 (DeleteProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 448, resource id: 46137348, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 449, resource id: 46137348, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 452, resource id: 46137348, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 453, resource id: 46137348, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 470, resource id: 46137348, major code: 2 (ChangeWindowAttributes), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 471, resource id: 46137348, major code: 2 (ChangeWindowAttributes), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 472, resource id: 46137348, major code: 20 (GetProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 473, resource id: 46137348, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 474, resource id: 46137348, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 475, resource id: 46137348, major code: 20 (GetProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 476, resource id: 46137348, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 477, resource id: 46137348, major code: 20 (GetProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 478, resource id: 46137348, major code: 19 (DeleteProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 479, resource id: 46137348, major code: 8 (MapWindow), minor code: 0
QWidget::setMinimumSize: (MainWindow/MainWindow) The largest allowed size is (16777215,16777215)
    tutorial:INFO process tutorial dialogs
QWidget::setMinimumSize: (dockFiles/QDockWidget) Negative sizes (20,-1) are not possible
QWidget::setMaximumSize: (dockFiles/QDockWidget) Negative sizes (524287,-1) are not possible
QWidget::setMinimumSize: (dockVideo/QDockWidget) Negative sizes (18,-1) are not possible
QWidget::setMaximumSize: (dockVideo/QDockWidget) Negative sizes (524287,-1) are not possible
QWidget::setMinimumSize: (dockTransitions/QDockWidget) Negative sizes (20,-1) are not possible
QWidget::setMaximumSize: (dockTransitions/QDockWidget) Negative sizes (524287,-1) are not possible
QWidget::setMinimumSize: (dockEffects/QDockWidget) Negative sizes (20,-1) are not possible
QWidget::setMaximumSize: (dockEffects/QDockWidget) Negative sizes (524287,-1) are not possible
QWidget::setMinimumSize: (MainWindow/MainWindow) The largest allowed size is (16777215,16777215)
    tutorial:INFO process tutorial dialogs
QWidget::setMinimumSize: (dockFiles/QDockWidget) Negative sizes (20,-1) are not possible
QWidget::setMaximumSize: (dockFiles/QDockWidget) Negative sizes (524287,-1) are not possible
QWidget::setMinimumSize: (dockVideo/QDockWidget) Negative sizes (18,-1) are not possible
QWidget::setMaximumSize: (dockVideo/QDockWidget) Negative sizes (524287,-1) are not possible
QWidget::setMinimumSize: (dockTransitions/QDockWidget) Negative sizes (20,-1) are not possible
QWidget::setMaximumSize: (dockTransitions/QDockWidget) Negative sizes (524287,-1) are not possible
QWidget::setMinimumSize: (dockEffects/QDockWidget) Negative sizes (20,-1) are not possible
QWidget::setMaximumSize: (dockEffects/QDockWidget) Negative sizes (524287,-1) are not possible
QWidget::setMinimumSize: (MainWindow/MainWindow) The largest allowed size is (16777215,16777215)
    tutorial:INFO process tutorial dialogs
QXcbConnection: XCB error: 3 (BadWindow), sequence: 481, resource id: 46137348, major code: 18 (ChangeProperty), minor code: 0
properties_model:INFO Update item: 
properties_model:INFO updating clip properties model.
     metrics:INFO Track metric: {'content-length': '35', 'pragma': 'no-cache', 'expires': 'Mon, 01 Jan 1990 00:00:00 GMT', 'access-control-allow-origin': '*', 'age': '160968', 'status': '200', 'content-type': 'image/gif', 'x-content-type-options': 'nosniff', 'date': 'Thu, 22 Dec 2016 21:44:37 GMT', 'server': 'Golfe2', 'cache-control': 'no-cache, no-store, must-revalidate', 'content-location': 'http://www.google-analytics.com/collect?cd2=3.5.2%2B&v=1&ul=en&cid=&cd4=5.7&aip=1&tid=UA-4381101-5&aid=org.openshot.openshot-qt&ua=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&exf=1&cd5=Ubuntu-16.10-yakkety&exd=unhandled-crash&av=2.2.0&cd1=0.1.3&t=exception&cd3=5.6.1&an=OpenShot+Video+Editor', 'last-modified': 'Sun, 17 May 1998 03:00:00 GMT'} (b'GIF89a\x01\x00\x01\x00\x80\xff\x00\xff\xff\xff\x00\x00\x00,\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x02D\x01\x00;')

^Z
[1]+  Stopped                 openshot-qt

`

**Comment by jonoomph** [comment]
Please test using our latest AppImage daily build. Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot. It seems like this might be environment related, and the AppImage contains many of the needed dependencies and doesn't rely on your system's versions. If it only crashes on your PPA/Repo installed version, then it sounds like a packaging issue, or a possible issue with Qt's packaging, but nothing I can fix in OpenShot's source code. Please reopen this issue if the AppImage also crashes. Thanks!
