### ISSUE TITLE
Unable to edit or preview mp4 files

### ISSUE THREAD

**Issue by AcmeUK** [OpenShot/openshot-qt#4411]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**
1. Go to 'File>Import Files select mp4 to import'
2. Click on '....Play button in Video Preview'
4. See error 'Nothing happens!'

**Expected behavior**
I expect to see the mp4 file play in the Video Preview window. I am unable to edit the file.

**System Details**
- OpenShot Version: 2.6.0-dev
- libopenshot Version:  0.2.6-dev
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-GB', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.0-dev-daily-8261-2dbb8d53-5ec3bc21-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/qpy50j3gwhi3d7wuhv5rpjc5t02lsfza/openshot-qt.zip) (5 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/qpy50j3gwhi3d7wuhv5rpjc5t02lsfza/libopenshot.zip) (5 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by speedytechdev** [comment]
Hi, @AcmeUK have you tried Openshot version 2.6.1 or the daily build? We have fixed a lot of bugs in these versions.

Thank You and enjoy the rest of your day.
Speedytechlive - Support Team

**Comment by AcmeUK** [comment]
Hi
Found issue, user error!!!
Sorry
