### ISSUE TITLE
Opening project file crashes Openshot in windows 10

### ISSUE THREAD

**Issue by jridge76** [OpenShot/openshot-qt#4412]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**
1. Go to 'file + recent project.'
2. Click on 'project name + select'
3. Scroll down to 'software crashes'
4. See error Window Application Error only
Faulting application name: openshot-qt.exe, version: 2.6.0.0, time stamp: 0x607466f6
Faulting module name: ntdll.dll, version: 10.0.19041.1110, time stamp: 0xe7a22463
Exception code: 0xc0000374
Fault offset: 0x00000000000ff259
Faulting process id: 0x3958
Faulting application start time: 0x01d7a5f40fa051dd
Faulting application path: C:\Program Files\OpenShot Video Editor\openshot-qt.exe
Faulting module path: C:\windows\SYSTEM32\ntdll.dll
Report Id: 63a2f774-b930-4b7a-88b8-7de4e260cf7e
Faulting package full name: 
Faulting package-relative application ID: 

**Expected behavior**
I expect a 30sec to 60sec load time and population of previously loaded files

**System Details**
Intel(R) Core(TM) i5-3470 CPU @ 3.2Ghz
16 GB (15.9 GB usable)
A8579B7D-4553-442F-95BD-F57AFBE2EA19
00330-75078-98863-AAOEM
64-bit operating system, x64-based processor
Wingows 10 Pro
OS Build 19041.1165
Windows Feature Experience Pack 120.2212.3530.0

- OpenShot Version: 2.6.0-dev
- libopenshot Version:  0.2.6-dev
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
- Machine: Intel i5
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: US
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.0-dev-daily-8261-2dbb8d53-5ec3bc21-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/eutg5hmibkzdqrjgi07ffp9d5jitn88j/openshot-qt.zip) (56 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/eutg5hmibkzdqrjgi07ffp9d5jitn88j/libopenshot.zip) (159 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by speedytechdev** [comment]
Hi @jridge76 I see you are using version 2.6.0 of Openshot. Could you try our latest version 2.6.1 and try the daily build of that. We fixed a lot of bugs in the new build. Please let me know if you get stuck.

Thank You and enjoy the rest of your day.
Speedytechlive - Support Team

**Comment by jridge76** [comment]
Hi,

Sorry, this has taken me a couple of days to get back to you.

2.6.1 downloaded straight has a problem. When I try to load a previous 2.5 project, it crashes and doesn't load or open. When I applied the day's build, I believe the last was from the 10th of Sept. It opened one project. I was surprised, but then the preview was running slow and bringing in new videos and jpeg files loading slow, and finally, it just closed or crashed.

I then deleted everything. I took it out of the Control panel, and there are two files there. One is x64, and the other is x32. Then I did a reload, and the same things were happening. Next, I deleted the user files and program files from the program file and the control panel.

After the reload, this is where things got strange. When It loaded, I couldn't see any program files, not even in windows explorer. I had to get up, and when I came back, every file in every project was in the project window. I could see the project files, but the individual files were gone from the folders, which I used to prep everything. I messed around with this for a while with mixed results. I was shocked to see the files go missing and come back from the explorer folders.

As a sidelight, when I opened a project, it would always come up with a file that couldn't be found, and when I would try to direct it to the path, nothing was there, but Openshot knew the file name.

I can spend some time on it if you want me to run some tests and send you the log files.

I hope this helps.

Thanks

Jerry

I love using the program. I have the old copy, and I am still using it.


Best,




________________________________

**Comment by speedytechdev** [comment]
Hi, 

That is really odd. I haven't heard about anything similar to this. I'm going to mark this as a bug and hopefully, someone from our dev team can check this out. Thank you for all your help.

If you could test it out that would be amazing since it would help our team out a lot. 

Sorry for any inconvenience this has caused you. Please feel free to reach out if you need anything.

Thank You and enjoy the rest of your day.
Speedytechlive - Support Team

**Comment by jridge76** [comment]
here are some screenshots and log files.


Hopefully the file names will help here.


Essentially I wasn't able to duplicate brining in every project video and jpeg


What I captured was opening a project and being asked for a file every time I have opened a file even untitled I get a request for a lost file. Sometimes the project closes and today it was leading me to find the file but the files were disappeared out of the windows explorer.


libopen log was blank all the time.


If you want me to do something else let me know.


Thank you.




________________________________

**Comment by speedytechdev** [comment]
I don't see any screenshots but thank you for the help 😃

Thank You and enjoy the rest of your day.
Speedytechlive - Support Team

**Comment by jridge76** [comment]
sorry I do see them in the sent email. I will attach only the screenshots here.


They loaded right away and I see them in this email. The text I didn't send this time.


I'm a day sleeper so it takes me a little longer to respond.


Thank you

Jerry


________________________________

**Comment by speedytechdev** [comment]
I'm still not seeing them, unfortunately. Made try using [https://imgur.com/](https://imgur.com/) 

That's really odd.

No Worries. 

No worries 

Speedytechlive - Support Team

**Comment by jridge76** [comment]
https://imgur.com/a/9cplick


The pages in explorer are exactly the same the user root. But when Openshot grabs a project all of them disappear then I get a file cannot be found.


Let me know what else I can do


thanks


________________________________

**Comment by DanPinGF** [comment]
The 'Blur' effect might be to blame. See #4202.
