### ISSUE TITLE
Failed, Install Openshot2.6.0&2.6.1 on win7 32bit

### ISSUE THREAD

**Issue by vfy2012** [OpenShot/openshot-qt#4416]
cx_Freeze:Python error in main script
--------------------------------------------------------
Traceback (most recent call last):
File "C:/msys64/mingw32/lib/python3.8/site-packages/cx_Freeze/initscripts/_startup_.py:,line40, in run file "C:/msys64/mingw32/lib/python3.8/site-packages/cx_Freeze/initscripts/Console.py",line27, in <module> File "C:/msys64/ming32/ling/python3.8/site-packages/PyQt5/_init_.py",line49,
(....                        )
in find_qt File "C:/msys64/mingw32/lib/python3.8/os.py", line1109,
in add_all_directory OSError"[WinError 127] 找不到指定的程序 :"'C:\\Prigram Files\\OpenShot Video Editor'

**Comment by speedytechdev** [comment]
Hi @vfy2012, since this can be a completed bug could you provide us with the following information:

- [x] Log Files 
- [x] System Details 
- [x] Steps to reproduce the behaviour 

Just to double-check this issue still happens in the daily build?

Thank You and enjoy the rest of your day.
Speedytechlive - Support Team

**Comment by vfy2012** [comment]
Thanks, 
But i don't find the log files in "c:/user/myusername/"  and don't  find  the folder ".openshot_qt";

**My system:** is windows 7.0 sp1 chinese;
I also installed it on another computer. After the installation, the same error occurred when starting the software.

**Steps to reproduce the behaviour:** Install openshot 2.6.0 or 2.6.1, then run.

**Comment by speedytechdev** [comment]
@vfy2012 Thanks for including everything. I'm wondering if you can't find the log files because you told Openshot to save your files somewhere else? Have you tried using the search feature in file explorer to find it?

Thank You and enjoy the rest of your day.
Speedytechlive - Support Team

**Comment by vfy2012** [comment]
I use the default installation directory of the software.  Version 2.6.1 does not create the folder ". Openshot_qt";  
The following log file is version 2.5.1,  I reinstalled 2.5.1,  2.5.1 works normally.
------------------------------------
         app:INFO ------------------------------------------------
         app:INFO             Mon Sep 13 05:36:56 2021            
         app:INFO               Starting new session              
         app:INFO ------------------------------------------------
         app:INFO             OpenShot (version 2.5.1)            
         app:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.5.1
         app:INFO libopenshot version: 0.2.5
         app:INFO platform: Windows-7-6.1.7601-SP1
         app:INFO processor: x86 Family 6 Model 42 Stepping 7, GenuineIntel
         app:INFO machine: x86
         app:INFO python version: 3.7.4
         app:INFO qt5 version: 5.12.4
         app:INFO pyqt5 version: 5.12.3
    language:INFO Qt Detected Languages: ['zh-CN', 'en-US']
    language:INFO LANG Environment Variable: 
    language:INFO LOCALE Environment Variable: 
    language:INFO OpenShot Preference Language: Default
project_data:INFO Setting default profile to HD 720p 30 fps
         app:INFO Setting font to C:\Program Files\OpenShot Video Editor\images\fonts\Ubuntu-R.ttf
         app:INFO Setting custom dark theme
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
     ui_util:INFO Initializing UI for MainWindow
files_listview:INFO currentChanged
files_listview:INFO updateSelection
 files_model:INFO updating files model.
transition_model:INFO updating transitions model.
effects_model:INFO updating effects model.
properties_model:INFO updating clip properties model.
transition_model:INFO updating transitions model.
     version:INFO Found current version: {"openshot_version": "2.6.1", "error_rate_unstable": 0.05, "error_rate_stable": 0.05}
 files_model:INFO updating files model.
 main_window:INFO InitCacheSettings
 main_window:INFO cache-mode: CacheMemory
 main_window:INFO cache-limit-mb: 250
 main_window:INFO Creating CacheMemory object with 262144000 byte limit
preview_thread:INFO QThread Start Method Invoked
preview_thread:INFO initPlayer
 main_window:INFO Clear all thumbnails: C:\Users\Username\.openshot_qt\thumbnail
 main_window:INFO Clear all animations: C:\Users\Username\.openshot_qt\blender
 main_window:INFO Clear all titles: C:\Users\Username\.openshot_qt\title
 main_window:INFO updateStatusChanged
 main_window:INFO updateStatusChanged
         app:INFO Process command-line arguments: ['C:\\Program Files\\OpenShot Video Editor\\openshot-qt.exe']
 main_window:INFO recover_backup
project_data:INFO Setting default profile to HD 720p 30 fps
preview_thread:INFO refreshFrame
preview_thread:INFO self.player.Position(): 1
video_widget:INFO Load: Set video widget display aspect ratio to: 1.7777777777777777
video_widget:INFO Set video widget pixel aspect ratio to: 1.0
 main_window:INFO updateStatusChanged
 main_window:INFO foundCurrentVersion: Found the latest version: 2.6.1
preview_thread:INFO onModeChanged
properties_model:INFO Update item: 
properties_model:INFO updating clip properties model.
    timeline:INFO Adjusting max size of preview image: PyQt5.QtCore.QSize(722, 406)
preview_thread:INFO refreshFrame
preview_thread:INFO self.player.Position(): 1
preview_thread:INFO refreshFrame
preview_thread:INFO self.player.Position(): 1
timeline_webview:INFO Qt Found!
timeline_webview:INFO $scope.Qt = true;
timeline_webview:INFO SetThumbAddress: http://127.0.0.1:60498/thumbnails/
timeline_webview:INFO UpdateLayerIndex
timeline_webview:INFO SortItems
timeline_webview:INFO UpdateLayerIndex
 main_window:INFO ---------------- Shutting down -----------------
preview_thread:INFO onModeChanged
preview_thread:INFO exiting thread
   thumbnail:INFO Shutting down thumbnail server: ('127.0.0.1', 60498)
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "C:\Program Files\OpenShot Video Editor\windows\views\timeline_webview.py", line 2929, in render_cache_json
    cache_object = get_app().window.timeline_sync.timeline.GetCache()
AttributeError: 'NoneType' object has no attribute 'GetCache'
         app:INFO             OpenShot's session ended            
         app:INFO             Mon Sep 13 05:37:15 2021            
         app:INFO ================================================

**Comment by speedytechdev** [comment]
That's very odd. If that's the only log file you can get then no worries. Thank you for taking the time to look for it. I'm happy to mark this as a bug so our dev team can find a fix for you.

Thank You and enjoy the rest of your day.
Speedytechlive - Support Team

**Comment by DanPinGF** [comment]
It's very important to recognize that Windows 7 is longer being maintained as of 2020. If I were any of you I'd keep my system secure and more stable with a newer Windows. I'm on Win11, BTW.
