### ISSUE TITLE
Exported Video Audio Lag

### ISSUE THREAD

**Issue by spawnofthestorm** [OpenShot/openshot-qt#4417]
Hello, I have tried exporting my video 3 separate times and each time the audio is lagging behind the video. This only happens after exporting not when in OpenShot so I know my footage is synced up. Is there any solution for this?

**Comment by speedytechdev** [comment]
Hi @spawnofthestorm , have you tried the daily build? Our daily builds normal fix most issues. If you are still having this issue we are happy to sit down with you to work it out.

Thank You and enjoy the rest of your day.
Speedytechlive - Support Team

**Comment by spawnofthestorm** [comment]
Hello, where can I find the daily builds?

**Comment by speedytechdev** [comment]
Sorry, my bad I forgot to include it. If you go to our [download page](https://www.openshot.org/download/) and click on the button that says daily build it will show you the latest one there. 

![image](https://user-images.githubusercontent.com/40452959/133583777-96a1602b-674c-49b3-9d7b-b4a8bafb187b.png)

Thank You and enjoy the rest of your day.
Speedytechlive - Support Team
