### ISSUE TITLE
CRYPTO_atomic_read could not be located

### ISSUE THREAD

**Issue by RasheedAZ** [OpenShot/openshot-qt#4418]
**Question:**
Hi. I got the following error message upon the first start of OpenShot:

`The procedure CRYPTO_atomic_read could not be located in the dynamic link library C:\Programs\Intel(R) Management Engine Components\iCLS\libssl-1_1-x64.dll`

Can anyone please tell me ifs this related to OpenShot or something else? Thanks.

**System Details:**
- OpenShot Version: 2.6.1
- Operating System: Windows 10

**Screenshot:**
![Screenshot 2021-09-13 003804](https://user-images.githubusercontent.com/16827461/133030016-a4ba8280-6f9c-4377-bd69-d6ba1b2ef399.png)

**Comment by speedytechdev** [comment]
@JacksonRG Can you confirm this, please?

**Comment by ghost** [comment]
I'm getting the same issue. It will pop up every time I open OpenShot with the latest build. I can just hit ok and OpenShot will open normally after that.

**Comment by speedytechdev** [comment]
> I'm getting the same issue. It will pop up every time I open OpenShot with the latest build. I can just hit ok and OpenShot will open normally after that.

Have you tried the daily build? Since I have tested this with the daily build and can't seem to recreate the bug. 

Thank You and enjoy the rest of your day.
Speedytechlive - Support Team

**Comment by rosmont57** [comment]
I'm getting the same issue The procedure CRYPTO_atomic_read could not be located in the dynamic link library C:\Programs\Intel(R) Management Engine Components\iCLS\libssl-1_1-x64.dll   ..

**Comment by speedytechdev** [comment]
Hi @rosmont57 Sorry about any inconvenience this has caused you. Someone from our dev team can hopefully help you out with this issue.

Thank You and enjoy the rest of your day.
Speedytechlive - Support Team

**Comment by sc0nway** [comment]
The library is part of OpenSSL, and you may have to [reinstall the program](https://www.thewindowsclub.com/procedure-entry-point-could-not-be-located-in-the-dynamic-link-library) to resolve the error message.  You can also try [downloading the missing DLL](https://www.pconlife.com/viewfileinfo/libssl-1-1-x64-dll/) file, copying it to the folder listed in the error message, then registering the DLL with Windows.
