### ISSUE TITLE
Undoing a trim results in two lots of audio on track timelines

### ISSUE THREAD

**Issue by ghost** [OpenShot/openshot-qt#4419]
**Describe the bug:**
After selecting an area to trim out and compress, undoing these actions can result in two seperate lots of clips appearing on the timeline. 
![Screenshot from 2021-09-13 19-47-22](https://user-images.githubusercontent.com/87929444/133063855-f278af14-b831-4a28-aa55-6616d07c0fed.png)
The top track was not expected to extend beyond the start of the bottom track, but remains present. 

I suspect this is part of the Undo bug already logged as #4180 , but raising a new bug in case i can provide extra fault finding data and steps to reproduce. 

I have also made several other recordings of where i noted it took about 18 undo clicks to undo 6 or 7 actions.  This was going to be logged as several items, but i will add below if requested as the comment in #4180 that lead me to believe it was a known issue. It was confired in one of those that another undo would remove the duplicaton of tracks. 

**Steps to reproduce the behavior:**
1. Add file to project
2. Add file to track
3. Trim several times in the file and remove a part in the middle and compress the remaining clip forward.
4. Press Undo to add the clip back in. several undos may be required. 
See a recording at  https://youtu.be/Ma9FJFr_zeE?t=41 Video should start at 40 seconds in where edits are made and duplication can be seen at 1:00.

**Expected behavior:**
Any clip added in would only be the same for the section deleted and not extend beyond.  See screenshots
![Screenshot from 2021-09-13 19-53-28 Cornered Edge](https://user-images.githubusercontent.com/87929444/133063916-d69420a9-39c2-4d94-853b-b4560c44e9f3.png) A normal clip with a cornered edge at top right
![Screenshot from 2021-09-13 19-53-53 Cornered Edge missing](https://user-images.githubusercontent.com/87929444/133063921-392eccda-e53f-435f-979f-d1d7ead57e32.png) A clip extending into another clip unexpectedly without a cornered edge on top right.

**System Details:**
- OpenShot Version  2.6.1-dev libopenshot: 0.2.7-dev
- Ubuntu 20.04 LTS

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by ghost** [comment]
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/7153472/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/7153479/openshot-qt.log)
Forgot to add log files.

**Comment by speedytechdev** [comment]
Hi @SoftwareTesterScott , so it does look like the same bug but you might have more information about it. So I'm going to mark this as a bug and just link it in the other issue, Thanks for bringing this up.

Thank You and enjoy the rest of your day.
Speedytechlive - Support Team
