### ISSUE TITLE
Audio on pc is killed when I try to preview any video file. 

### ISSUE THREAD

**Issue by antthunderfun** [OpenShot/openshot-qt#4420]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**
1. import video 
2. preview video
3. all audio on my PC is then muted and will not return unless I quit OpenShot

**Expected behavior**

**System Details**
- OpenShot Version: 2.6.1
- libopenshot Version:  0.2.7
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 165 Stepping 5, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-dev-daily-8289-21597c8a-73c519f0-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/z22essvlh11qzvn2hjp238mf8k5wf1uk/openshot-qt.zip) (16 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by speedytechdev** [comment]
Hi @antthunderfun I believe that you're having the same bug as this [user.](https://github.com/OpenShot/openshot-qt/issues/4303l) Can you please confirm? Our dev team believes it has something to do with headphones and Windows.

Thank You and enjoy the rest of your day.
Speedytechlive - Support Team
