### ISSUE TITLE
"Time -> Fast Forward" broken with custom preset

### ISSUE THREAD

**Issue by N3WWN** [OpenShot/openshot-qt#4422]
**Describe the bug:**
I often use OpenShot to take one long video which has content at the start and at the end, with a middle part that is not interesting, and speed up the middle part.

I was using OpenShot 2.5.1 until this month and it worked perfectly.  Now, the keyframes are correct, but the rendered result contains a sped up section that is more than the middle slice of the original clip.

**Steps to reproduce the behavior:**

1. New project (I'm using a custom "HD 1080p 100 fps" profile)
2. Import clip (100 fps clip)
3. Locate two points in the video and add markers - what is between the markers will be sped up
4. Slice the clip at both points (Keep both sides)
5. Select the middle slice of the original clip
6. Right-Click -> Time -> Fast Forward -> 8x - the clip shortens, producing a gap between the middle slice and the right slice
7. Drag the right slice to meet up with the middle slice to remove the gap
8. Export the video

**Expected behavior:**
With 2.5.1 (and earlier, IIRC), this worked perfectly.

With 2.6.1, the entire end of the clip (middle+right slices, not just the middle slice) is sped up into 1/8 the time of the middle slice.  

In my current video, the full clip is 63.90s, the left slice is 16.01s, the middle slice is 27.96s and the right slice is 19.93s.
After applying the 8x time effect, the middle slice is 3.50s (3.495s would be exactly 1/8 of 27.96s, so 3.50s is right).  

The middle slice has Time keyframes at 1604.00 at the start and 4396.00 at the end of the clip.
The clip durations on the timeline and the keyframe values confirm that the keyframes are correct.

After rendering, the video is 39s long, as expected, but from 16s to 19.5s contains approx 47s of video (27.96+19.93).  At 19.5s, the right slice is correctly played at normal speed.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 2.6.0 and 2.6.1 (OpenShot-v2.6.0-dev-daily-8190-d58febf1-5ec3bc21-x86_64.AppImage and OpenShot-v2.6.1-dev-daily-8289-21597c8a-73c519f0-x86_64.AppImage)
- Operating System / Distro: Fedora 31

**Comment by N3WWN** [comment]
More info...

I was able to replicate the issue using OpenShot v2.5.1.

Digging deeper, I've narrowed down this issue to custom presets.  

I've been using a custom preset `~/.openshot_qt/presets/format_mp4_x264.xml` for a while now in order to increase the default video bitrate up to 60 Mb/s.   I noticed that, after adding the preset, the export video profile would default to "1024x576 16:9 PAL (2014x576)" and I'd have to just it back to "HD 1080p 100 fps".  This was a little annoying, but not a big problem.  

I figure there was just something about custom presets that didn't work with my custom profile and I'd figure it out later.

Today, I switched back to v2.5.1 so I could get this Fast Forward section completed for my next video and v2.5.1 would have the same Fast Forward problem that v2.6.x has been having.

I removed the custom preset and now v2.5.1 and v2.6.1 can both correctly render the "HD 1080p 100 fps" video with `Time -> Fast Forward`.

So, not sure where the issue resides just yet and haven't had chance to narrow it down further, but it seems custom profile and custom presets don't play well with Fast Forward.

**Comment by N3WWN** [comment]
I can confirm that the custom preset issue (at least in part, if not in whole) is still present in OpenShot-v2.6.1-dev-daily-9348-04db6ce8-46255e46-x86_64.AppImage (daily build from Mar 26, 2022)

When using a custom preset, the export video profile defaults to "1024x576 16:9 PAL (2014x576)" and I still have to reselect "HD 1080p 100 fps" for every video export.

**Comment by JacksonRG** [comment]
Could you link your custom preset for testing this?

**Comment by N3WWN** [comment]
Sure thing, @JacksonRG !

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE openshot-export-option>
<export-option>
	<type translatable="True">All Formats</type>
	<title translatable="True">MP4 (h.264)</title>
	<videoformat>mp4</videoformat>
	<videocodec>libx264</videocodec>
	<audiocodec>aac</audiocodec>
	<audiochannels>2</audiochannels>
	<audiochannellayout>3</audiochannellayout>
	<videobitrate
	 low="1 Mb/s"
	 med="7 Mb/s"
	 high="60.00 Mb/s"></videobitrate>
	<audiobitrate
	 low="64 kb/s"
	 med="64 kb/s"
	 high="64 kb/s"></audiobitrate>
	<samplerate>32000</samplerate>
	<projectprofile>HD 720p 23.98 fps</projectprofile>
	<projectprofile>HD 720p 24 fps</projectprofile>
	<projectprofile>HD 720p 25 fps</projectprofile>
	<projectprofile>HD 720p 29.97 fps</projectprofile>
	<projectprofile>HD 720p 30 fps</projectprofile>
	<projectprofile>HD 1080p 23.98 fps</projectprofile>
	<projectprofile>HD 1080p 24 fps</projectprofile>
	<projectprofile>HD 1080p 25 fps</projectprofile>
	<projectprofile>HD 1080p 29.97 fps</projectprofile>
	<projectprofile>HD 1080p 30 fps</projectprofile>
	<projectprofile>HD 1080p 100 fps</projectprofile>
</export-option>
```

**Comment by N3WWN** [comment]
This custom preset issue is still present in recent daily builds.

**Comment by N3WWN** [comment]
As I mentioned 14 days ago, "This custom preset issue is still present in recent daily builds."  

I just reconfirmed the issue with OpenShot-v2.6.1-dev-daily-9926-9954b53b-46255e46-x86_64.AppImage from Oct 13.
