### ISSUE TITLE
Maximum timeline zoom level for stopmotion too low

### ISSUE THREAD

**Issue by brmmm3** [OpenShot/openshot-qt#443]
Openshot 2.2.0:
The maximum zoom level should be at least 0.1 seconds instead of 1 second.
Or better for videos adjust the maximum zoom level to 0.04s.
AND: Please Add a tooltip for the currently selected picture in the timeline! There is currently no way to find out which picture is currently selected.

Best regards,

Martin

**Comment by DylanC** [comment]
@brmmm3 - Zoom issue will be tracked via #160
