### ISSUE TITLE
I cannot get the transitions to show up on playback - how do I get them to show?  I can send a file if that helps..

### ISSUE THREAD

**Issue by bubistaii** [OpenShot/openshot-qt#4430]
**Question:**
A clear and concise question. Your question should provide enough context and explanation for people to answer it. Avoid excessive background or irrelevant details, as they can obscure your actual question.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your question. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by bubistaii** [comment]
Transitions are not showing up in playback.
I just upgraded to version 2.6.1
I am a novice user and have read the user guide, with no progress.
![image](https://user-images.githubusercontent.com/90986829/133907852-f26e5779-da58-4e79-a6bb-ea1e61573c5b.png)
I hope this image shows the transition location.  When I playback the image goes to black until the next clip/image.  I have tried upping both the bridghtness and the contrast.
But, I cannot attach the openshot file.

Frustrating....I hope someone can help.

**Comment by megabugman** [comment]
Track 5 has two transitions, But the playhead is located in between.
Hard to tell what's wrong from screenshots alone, You can create and post a video (GIF) here,

Watch this tutorial in case you want to know how to create a GIF:
https://youtu.be/G4UoZE7W5kw?list=PLxXn36qM4OUvjJCwyCNCpdbj2LTc7SeJJ

**Comment by bubistaii** [comment]
OK, I tried to do the GIF creation, but it doesn't record more than a few tenths of a second - then seems to reset to RECORD.  Here is what I was able to record
![transition issues](https://user-images.githubusercontent.com/90986829/133950853-7b3b0767-e0ae-4592-b06e-1ec4233129bb.gif)
If you can tell, the recording doesn't go as far to show the (non)transition.  I will try a couple of times to see if this can be improved.
d.

**Comment by bubistaii** [comment]
I moved the playback head a little closer to the actual fault.  Possibly you can see the problem in this clip.
![transition issues](https://user-images.githubusercontent.com/90986829/133951046-c4f87657-7eee-4d5d-a6a0-68f9f48f14d4.gif)
Thanks so much for your help.
