### ISSUE TITLE
Microsoft Store

### ISSUE THREAD

**Issue by ghost** [OpenShot/openshot-qt#4433]
https://www.microsoft.com/en-us/p/openshot-video-editor/9n8rtfjzjs7v?activetab=pivot:overviewtab

Why is this developer Mediacenterapp charging $3.99, when is open source? Which means free right? 😠

**Comment by sc0nway** [comment]
Hi @DanTMan64!  I've had to reread the GNU General Public License several times to understand it.  Our license doesn't guarantee free software. It ensures the freedom of software.  The right to sell copies is part of the definition of free software.  The GNU GPL allows anyone to download our source code, modify it, distribute it, or sell it.  The other vendors are supposed to attribute OpenShot Studios for creating the software, and they are required to provide all support for the app they distribute and sell.

If you're interested, the GNU GPL [Frequently Asked Questions](https://www.gnu.org/licenses/gpl-faq.html) page helps explain the license we use.
