### ISSUE TITLE
OpenShot crashes while animating svg and scrubbing through timeline

### ISSUE THREAD

**Issue by yoSachinkr** [OpenShot/openshot-qt#4441]
**Describe the bug:**
Openshot is crashing while animating svg files and scrubbing through timeline. It basically happens when I  add 2 svg files in different timelines and animate them and check the animation by scrubbing through timeline.

**Steps to reproduce the behavior:**
1. Create 2 or 3 svg animation in different timelines at different time.
2. Try to check the animation by scrubbing through timeline few times.
3. Openshot will crash immediately.

**Expected behavior:**
Crash shouldn't happen.

**System Details:**
- OpenShot Version 2.6.1
- Windows 10 64bit 21H1

**Log Files:**
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/7207540/openshot-qt.log)

**Comment by ZachIsAGardner** [comment]
I am also having this issue with .mkv files. https://github.com/OpenShot/openshot-qt/issues/4472

**Comment by DanPinGF** [comment]
It's happening because of a defect in libopenshot.dll, which will induce a crash if you play too rough with OpenShot. I actually have this problem, too.

**Comment by DanPinGF** [comment]
Someone's probably gonna have to add a '🔥 hot' label to this issue, if it is affecting everyone using the Windows version.

**Comment by DanPinGF** [comment]
@JacksonRG - This issue is still not fixed.

**Comment by DanPinGF** [comment]
@speedytechdev - We need help here...

**Comment by Colorjet3** [comment]
Please download the latest DEV Daily Build of v3.0.0 and give it a try:  openshot.org/download/#daily

**Comment by DanPinGF** [comment]
It looks like it's been fixed in version 3.0.0. I am not experiencing crashes moving through the timeline and animating objects.

**Comment by Colorjet3** [comment]
Awesome and thank you for the FYI @DanPinGF
