### ISSUE TITLE
Openshot will not start on windows 10 64 bits

### ISSUE THREAD

**Issue by AkkiDiamond** [OpenShot/openshot-qt#4443]
**Describe the bug**
Openshot will not start on windows 10 64 bits.
Tries latest build as well, tried an older version 2.5.1, same result.
Tried as administrator, tried to turn off windows defender, tried in loweer resolution, same result.

**Steps to reproduce the behavior:**

**Expected behavior**
Openshot should open like any other program

**System Details**
- OpenShot Version: 2.5.1-dev3
- libopenshot Version:  0.2.6-dev
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['ro-RO', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-dev-daily-8320-21597c8a-73c519f0-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/1c1h7i1art1vceeyqbz71tbd9x6gbhmm/openshot-qt.zip) (73 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/1c1h7i1art1vceeyqbz71tbd9x6gbhmm/libopenshot.zip) (3 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by AkkiDiamond** [comment]
It seems that from a secondary account on the PC it starts just fine.
Could it be some paths? I have PyCharm installed on the account that it is working. Could that have any influence?

**Comment by AkkiDiamond** [comment]
windows 11 same issue

**Comment by JacksonRG** [comment]
@AkkiDiamond Hi, looks like this issue is with 2.5.1 . Our current release version is 2.6.1 . Could you let me know if this issue persists with the current version?
