### ISSUE TITLE
OpenShot (2.6.1) crashes if user-created transition file is missing from transitions folder

### ISSUE THREAD

**Issue by Jason-Lee-Quinn** [OpenShot/openshot-qt#4450]
**Describe the bug:**
1. Create a B&W image to be used for a transition (I used a B&W .jpg but probably doesn't matter) 
2. Add the image to the .openshot_qt/transitions folder.
3. Make a project that uses a transition based on that file. Save it and close OpenShot.
4. Delete the transition image file from the .openshot_qt/transitions folder.
5. Start OpenShot and try to load the project. It will crash and be unable to recover.

**Expected behavior:**
The project should report that a file required by the project is missing and tell the user which one, then gracefully handle the issue. Perhaps an error dialog saying "Project X could not be opened because file Y it depends upon is missing." 

**System Details:**
- OpenShot Version [e.g. 2.6.1]:
- Operating System / Distro: Windows 10

**Logs/stacktraces**
I'm not attaching any logs or stacktraces because I think the bug should be quicker to reproduce than it would take to read them and probably effects all OS versions. This bug is probably not limited to just this specific case of transitions. Anytime a project is opened, if a needed file is missing, OpenShot should provide the user a useful error message and they try to gracefully recover.

**Comment by ferdnyc** [comment]
> I'm not attaching any logs or stacktraces because I think the bug should be quicker to reproduce than it would take to read them and probably effects all OS versions.

Not a problem, this is basically a duplicate of OpenShot/libopenshot#702, as the underlying issue lies in the library code. (I'll leave this open, though, because it should really be tracked here as well.)

**Comment by Jason-Lee-Quinn** [comment]
Wow, you're fast, ferdnyc. Thanks. I'm a new user to OpenShot who was playing around with transitions to learn how to use them. That's how I came across the bug so I think that's a likely reason why users might experience this bug, something devs sometimes ask. It's also important because it impacts a new user's first impressions. Thanks again.
