### ISSUE TITLE
Export Length is HUGE

### ISSUE THREAD

**Issue by NavyBill** [OpenShot/openshot-qt#4454]
**Question:**
A clear and concise question. Your question should provide enough context and explanation for people to answer it. Avoid excessive background or irrelevant details, as they can obscure your actual question.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your question. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by NavyBill** [comment]
I imported a short (12Mb) MP4 video which was 9 minutes long. After cutting it to 3 minutes and 12 seconds, the exported file was 306.3 MB long. Is this normal? If so, I'll have to go elsewhere for video editing software. I accepted all the defaults for output to MP4. Running Xubuntu (Ubuntu) 20.04.

Bill

**Comment by ksterne** [comment]
This seems like a duplication of #4191.  Can you check that issue?
