### ISSUE TITLE
Where are the scissors for editing? 

### ISSUE THREAD

**Issue by DerpyCoder123** [OpenShot/openshot-qt#446]
On older versions there were scissors in order to split your video: 
https://gyazo.com/48e9773c1da37cd1630e45943ef20e0f
Now there isn't:
https://gyazo.com/325b509690d75aa39862ac088834fe4c

**Comment by kitchendevil** [comment]
same problem with me!
Just installed openshot 2.2 to my ubuntu 16.04 via ppa as described on openshot-webpage.
No Razor-Tool, no Trimming-Tool (as shown in the pictures above) and imported videos running unstable, crashing after 20, 30 seconds.

**Comment by Just-Curious** [comment]
![20170101_sliceaway](https://cloud.githubusercontent.com/assets/16257232/21582207/5623e544-d01c-11e6-9828-48e3ec2dfde6.jpg)

**Comment by kitchendevil** [comment]
OK - Thanks, THIS problem is solved !!!!

**Comment by JoshKisb** [comment]
IMHO much as right clicking and looking for slice option could work, i would still prefer the scissors 
right clicking does not have much precision. **Scissors** please

**Comment by nbvcxz** [comment]
> IMHO much as right clicking and looking for slice option could work, i would still prefer the scissors right clicking does not have much precision. Scissors please
Right - same issue here (Windows 10 instance) and Slice All is only kind of hack to override it.

**Comment by jonoomph** [comment]
CTRL + K slices and keeps both sides. This can be adjusted in the preferences. Moving the playhead to a specific location is more accurate (i.e. since we have a preview) than just clicking and cutting. But I understand a lot of people are used to the razor and we might bring it back soon. thx.

**Comment by jonoomph** [comment]
Just a quick update. I just added back in the razor tool to OpenShot 2.0. More powerful than before, but still easy to use. Point and click to cut a clip or transition. Also, you can hold CTRL or SHIFT to modify it, to only keep the left or right side. Feels really good, and is much more discoverable as a tool. Of course, it still works as a keyboard shortcut to, for the power users. Thanks!
