### ISSUE TITLE
Crash if i try opening my last project, last bakup files not helping.

### ISSUE THREAD

**Issue by xaneta** [OpenShot/openshot-qt#4461]
Describe the bug
Openshot closes when I try to open a project i've been working on. 

1.Start Openshot
2. Click on open project
3. Choose project file i've been working on
4. Openshot closes down

**Systemdetails**
- OpenShot Version: 2.6.1-dev
- libopenshot Version:  0.2.7-dev
- Platform: Windows-10-10.0.19041
- Processor: AMD64 Family 16 Model 10 Stepping 0, AuthenticAMD
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['de-DE', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verifiziertes Problem exsitiert immer noch im Daily Build:  http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-dev-daily-8350-21597c8a-73c519f0-x86_64.exe

**Logdateien**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/omxmj2noo6a5p1k5idoeyvralu0v33hf/openshot-qt.zip) (19 KB)
- libopenshot.log: Datei zu klein oder leer (nicht hochgeladen)

**Ausnahme / Stapelverfolgung**
```No stacktrace found in log files```

**Comment by JacksonRG** [comment]
Did you have project files stored on different drives than your project file? There was a bug related to that, which should be in the current release build.

Also, if you didn't have verbose mode, could you enable it and recreate the error?

Instructions for that are here: https://github.com/OpenShot/openshot-qt/wiki/Issue-Logging

**Comment by DanPinGF** [comment]
Did you change OpenShot settings when you were working on the project? #4407 might be your case, then.
