### ISSUE TITLE
Unable to export WEBM using Flatpak build.

### ISSUE THREAD

**Issue by potatoleek** [OpenShot/openshot-qt#4462]
**Describe the bug**
Using the Flatpak build of OpenShot, I am unable to export a video using the WEBM (vpx) target. The error message is "A valid audio codec could not be found for this file." The export works correctly using the AppImage build.

**Steps to reproduce the behavior:**
1. Run the Flatpak build of OpenShot.
2. Place a video on to the timeline.
3. Go to File -> Export Project -> Export Video.
4. Change the target to WEBM (vpx).
5. Click Export Video.

**Expected behavior**
The video should be successfully exported with audio.

**System Details**
- OpenShot Version: 2.6.1
- libopenshot Version:  0.2.7
- Platform: Linux-5.4.0-88-generic-x86_64-with-glibc2.2.5
- Processor: 
- Machine: x86_64
- Python version: 3.8.8
- Qt5 version: 5.15.3
- PyQt5 version: 5.15.1
- Qt Detected Languages: ['en-CA', 'en']
- LANG Environment Variable: en_CA.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Skipped this step

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/mefftnrfp58951uz5whinjamksvhl1ry/openshot-qt.zip) (12 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/mefftnrfp58951uz5whinjamksvhl1ry/libopenshot.zip) (7 KB)

**Exception / Stacktrace**
```/usr/lib/x86_64-linux-gnu/libc.so.6 abort                                    0x127  [0x7f5fe7e1d855]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5                                          0x9db91  [0x7f5fe6e81b91]
/app/lib/python3.8/site-packages/PyQt5/QtCore.so                                          0xb9222  [0x7f5fe74e6222]
/app/lib/python3.8/site-packages/PyQt5/QtCore.so                                          0x21dd3d  [0x7f5fe764ad3d]
/app/lib/python3.8/site-packages/PyQt5/QtCore.so                                          0x21e87f  [0x7f5fe764b87f]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5                                          0x2ffe80  [0x7f5fe70e3e80]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5                                          0x30b1a8  [0x7f5fe408f1a8]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5                                          0x300170  [0x7f5fe70e4170]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 QAbstractButton::clicked(bool)           0x42  [0x7f5fe3febe82]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5                                          0x2687ea  [0x7f5fe3fec7ea]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5                                          0x26a13f  [0x7f5fe3fee13f]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 QAbstractButton::mouseReleaseEvent(QMouseEvent*) 0xf1  [0x7f5fe3fee311]
/app/lib/python3.8/site-packages/PyQt5/QtWidgets.so                                          0x2ee743  [0x7f5fe4715743]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 QWidget::event(QEvent*)                  0x1ce  [0x7f5fe3f3f02e]
/app/lib/python3.8/site-packages/PyQt5/QtWidgets.so                                          0x2eefb3  [0x7f5fe4715fb3]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 QApplicationPrivate::notify_helper(QObject*, QEvent*) 0x7f  [0x7f5fe3eff17f]
/usr/l...

**Comment by ferdnyc** [comment]
@potatoleek 

Apologies for the runaround, but we don't build the Flatpak releases of OpenShot.

It sounds like the Flatpak build might be missing libvorbis (the audio codec used with the WEBM preset), since the last line in your log file is:
> `INFO export: Error type string: A valid audio codec could not be found for this file.`

Best option would probably be to report this at https://github.com/flathub/org.openshot.OpenShot/issues

**Comment by ferdnyc** [comment]
Actually I've gone ahead and done that (see flathub/org.openshot.OpenShot#19)

**Comment by ferdnyc** [comment]
The Flatpak team have submitted PR  flathub/org.openshot.OpenShot#21 to fix libvorbis support, there's a build running there now. Once it's finished building, it can be tested from that PR. Hopefully it should fix this.

**Comment by potatoleek** [comment]
Thanks for looking into this. I downloaded the latest Flatpak from the testing repo and confirmed that WEBM can be exported now.

**Comment by ferdnyc** [comment]
@potatoleek Thanks for testing that out! I'll inform the Flatpak maintainers that all is well now and close this as solved, then.
