### ISSUE TITLE
We need more video effects...

### ISSUE THREAD

**Issue by DanPinGF** [OpenShot/openshot-qt#4463]
**Describe the new feature:**
OpenShot 2.6 provided a very nice expansion of the effects list, but would it be cool if we brought even more of those in the next major release? The new effects should be kept bug-free and fully stable on Windows.

**Describe the solution you'd like:**
I'm thinking of adding two of these effects:

- 'Film': Gives the image or video a seeming effect as if it were produced on a film gauge. The color saturation and bloom could be configured using any given film type (18mm, 35mm, 75mm, Super 85mm). Adjusting the 'Age' field can also increase the wobble intensity and the number of grain/dust outputted.
- 'Analog distortion' - Gives an image or video a typical 1960s/70s/80s/90s/early 2000's analog TV effect, reducing the color gamma, rendering briefly-visible flickering RGB fragments around edges, and vice versa. The distortion style could be configured using various input types (composite or VHS). For VHS, adjusting the 'Age' creates more distortion and grain than usual.

**Describe alternatives you have considered:**
N/A

**Screenshots:** (Optional)
N/A

**Comment by NanaMizukiAnother7** [comment]
That will be nice if the author added these effects. :D

Also, did not mean 8mm, 70mm, and Super 8mm, not 18mm, 75mm, and Super 85mm?

Also, there is also 16mm around here.

**Comment by clort81** [comment]
These are complex effects DanPinGF and it's great you're thinking about adding them.
Have you made any progress?
