### ISSUE TITLE
Timeline related crashes on windows

### ISSUE THREAD

**Issue by ZachIsAGardner** [OpenShot/openshot-qt#4472]
**Describe the bug**
The application crashes when I try to scrub the timeline.

**Steps to reproduce the behavior:**
It seems to be whenever I move the playhead around or do any kind of interaction in the timeline.

**System Details**
- OpenShot Version: 2.6.1
- libopenshot Version:  0.2.7
- Platform: Windows-10-10.0.19041
- Processor: AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Skipped this step

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/i7aar8pnw0an6q4hy9kia6xb48h2946g/openshot-qt.zip) (74 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Screenshots** (Optional)
![207](https://user-images.githubusercontent.com/30502195/136427629-6a80e50d-ef71-4b9b-86e7-723886133683.gif)

**Comment by ZachIsAGardner** [comment]
May be related to https://github.com/OpenShot/openshot-qt/issues/4441

**Comment by DanPinGF** [comment]
It's happening because of a defect in libopenshot.dll, which will induce a crash if you play too rough with OpenShot. I actually have this problem, too.

**Comment by DanPinGF** [comment]
@speedytechdev - We got a problem here...

**Comment by DanPinGF** [comment]
@JacksonRG - This issue still needs fixing.
