### ISSUE TITLE
Support the XDG Base Directory Specification

### ISSUE THREAD

**Issue by itaranto** [OpenShot/openshot-qt#4477]
Please support the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) on Linux/*nix systems.

Right now OpenShot dumps everything user related to `~/.openshot_qt` which is **not** nice for several reasons.

If you think that splitting this data between cache, config and user data is not feasible to do right now, **at the bare minimum** put everything under `$XDG_DATA_HOME/openshot_qt` (with a fallback to `~/.local/share/openshot_qt`)

Thanks.

**Comment by ChristianTacke** [comment]
@itaranto Can you take a look at #4624?

Especially of interest: Do you think, more directories should be moved from the default XDG_DATA_HOME to other places?

**Comment by itaranto** [comment]
> @itaranto Can you take a look at #4624?
> 
> Especially of interest: Do you think, more directories should be moved from the default XDG_DATA_HOME to other places?

That's looks really nice, I'm not familiar with the internals of this project, but splitting files between cache, config and user data seems to be the way to go!

I'm not a contributor here, but I have one question regarding `pyxdg`: So, you are basically detecting if `pyxdg` is installed and then use it right? Wouldn't be better to add `pyxdg` as a dependency for OpenShot?

**Comment by ChristianTacke** [comment]
> That's looks really nice, I'm not familiar with the internals of this project, but splitting files between cache, config and user data seems to be the way to go!

To further order things, we need someone with more insight into the internals. For example `thumbnail` really also sounds like "cache", but I am not sure at all.

> […] I have one question regarding `pyxdg`: So, you are basically detecting if `pyxdg` is installed and then use it right? Wouldn't be better to add `pyxdg` as a dependency for OpenShot?

It might!

Two points:

* I am new to the openshot codebase (just took a look today). And I haven't found the point for dependency management. So I have no idea where to add it!
* XDG should be used on Linux/Unix. But probably not on windows or macos. So one idea was: If a user actually installs `pyxdg` on windows/macos, they hopefully know, why they're doing so. On the other hand, I hope for it to be "just" installed on a typical Linux workstation.
* Actual packaging by distros hopefully will add it later on.

**Comment by itaranto** [comment]
> * XDG should be used on Linux/Unix. But probably not on windows or macos. So one idea was: If a user actually installs pyxdg on windows/macos, they hopefully know, why they're doing so. On the other hand, I hope for it to be "just" installed on a typical Linux workstation.

Yeah that makes sense, If only there were a way to specify dependencies per-platform, but from what I'm seeing there isn't.

**Comment by ChristianTacke** [comment]
Let's see, what the maintainers say about my Pull Request.

**Comment by m00nwtchr** [comment]
Log files should go under `$XDG_STATE_HOME` (`~/.local/state/`), btw

Some additional references:
https://wiki.debian.org/XDGBaseDirectorySpecification
https://wiki.archlinux.org/title/XDG_Base_Directory

**Comment by itaranto** [comment]
> Log files should go under `$XDG_STATE_HOME` (`~/.local/state/`), btw
> 
> Some additional references: https://wiki.debian.org/XDGBaseDirectorySpecification https://wiki.archlinux.org/title/XDG_Base_Directory

Yes, but take into account that `$XDG_STATE_HOME` is a relatively recent addition, putting logs in `$XDG_DATA_HOME` isn't that terrible.

**Comment by m00nwtchr** [comment]
Definitely should be reopened

**Comment by Daryl-Lawton** [comment]
I second that this needs to be supported
