### ISSUE TITLE
APP CRASH

### ISSUE THREAD

**Issue by yeye2stars** [OpenShot/openshot-qt#4483]
Reported for MOV files, not for mp4.

**Describe the bug:**
App crashes when uploading SOME (not all) *.mp4 files. 

**Steps to reproduce the behavior:**
1. open app
2. drag the mp4 file in OR file->import file
3. app crashes
4. No error code reported

**Expected behavior:**
upload/open designated file and edit

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/7338959/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/7338960/openshot-qt.log)

**Comment by JacksonRG** [comment]
Hi, I'm looking into this. If you find any connections between the files that cause a crash, or have one that you're willing to share that may help in solving it.

---
Possibly related issues: 
#4480
#4476

**Comment by Colorjet3** [comment]
Fixed in the latest DEV Daily Build of v3.0.0.
