### ISSUE TITLE
Can't start openshot - Fresh install from ppa. It halts with "TypeError: not all arguments converted during string formatting...

### ISSUE THREAD

**Issue by josircg** [OpenShot/openshot-qt#4486]
**Describe the bug**

$>sudo add-apt-repository ppa:openshot.developers/ppa
$>sudo apt-get update
$>sudo apt install openshot-qt

$>openshot-qt

  File "/usr/lib/python3/dist-packages/openshot_qt/windows/models/transition_model.py", line 152, in update_model
    trans_name = self.app._tr(trans_name) % suffix_number
TypeError: not all arguments converted during string formatting

**Expected behavior**
The software should open

**System Details**
- OpenShot Version: 2.6.0-dev
- libopenshot Version:  0.2.6-dev
- Platform: Linux-4.15.0-156-generic-x86_64-with-Ubuntu-18.04-bionic
- Processor: x86_64
- Machine: x86_64
- Python version: 3.6.9
- Qt5 version: 5.9.5
- PyQt5 version: 5.10.1
- Qt Detected Languages: ['pt-BR', 'pt', 'en']
- LANG Environment Variable: pt_BR.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Not able to verify issue still exists in daily build

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/uss2n3frl4n7t6f1kgya0o39vmjmxkuc/openshot-qt.zip) (8 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Comment by dukercs** [comment]
Same here, my system:

Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.11.0-40-generic
OS Type: 64-bit
Processors: 12 × AMD Ryzen 5 3600 6-Core Processor
Memory: 31,3 GiB

LOG: https://pastebin.com/KW9KxXFu

**Comment by viniciusao** [comment]
Same here...

**Comment by JacksonRG** [comment]
@viniciusao Are you getting the same error, of string formatting, also what version of Openshot are you using, and in what language? The language substitution sounds like where this error is coming from.

**Comment by viniciusao** [comment]
> @viniciusao Are you getting the same error, of string formatting, also what version of Openshot are you using, and in what language? The language substitution sounds like where this error is coming from.

Yes, string formatting. Openshot version: 2.6.0 

About language: 

> INFO language: Qt Detected Languages: ['pt-BR', 'en']
> INFO language: LANG Environment Variable: pt_BR.UTF-8

**Comment by jandermoreira** [comment]
Same here.
Ubuntu and pt-BR.

If I run `LANG=en.US openshot-qt` everything goes smooth!
