### ISSUE TITLE
Hardware acceleration for raspberry pi

### ISSUE THREAD

**Issue by myier** [OpenShot/openshot-qt#4491]
Hi, having a raspberry pi 4, since it's a particularly slow computer, it would be very nice to have the hardware acceleration working for decoding and encoding.
I know that mpv can use the hardware decoding, I'm not sure ffmpeg can use the hardware encoding.
In the performance tab of the preferences, nothing seems available. I'm using debian's version, 1.5.1.

Thank you

**Comment by Colorjet3** [comment]
Hardware acceleration in general should be made functional as I have seen references that this used to work in Linux and that it would be coming to Windows also.  At this time I am not sure if it is functional any where.  There is a reason why there is a "Performance" tab in Edit | Preferences.  This is a much needed/required/essential feature!
