### ISSUE TITLE
OpenShot spontaneously crashes whenever I add *ANYTHING* to a timeline track

### ISSUE THREAD

**Issue by shayaknyc** [OpenShot/openshot-qt#4495]
**Describe the bug**
Minding my own business, dragging photos or videos or transitions into the timeline, and then the whole program just crashes. No error, no nothing. Just spontaneous shutdown.

**Steps to reproduce the behavior:**
1. Add multimedia assets to the library
2. Drag any one of them into a track in the timeline
3. Program spontaneously closes for no reason with no error message.

**Expected behavior**
I expect the program to remain open and not close so I can continue producing the video.

**System Details**
- OpenShot Version: 2.6.1-dev
- libopenshot Version:  0.2.7-dev
- Platform: Linux-5.14.12-xanmod1-cacule-1-x86_64-with-Garuda-Soaring-Harpy-Eagle
- Processor: 
- Machine: x86_64
- Python version: 3.6.9
- Qt5 version: 5.9.5
- PyQt5 version: 5.10.1
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: en_US.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-dev-daily-8438-dae8ca5e-73c519f0-x86_64.AppImage

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/rtlh4os5eoagqoel33jnyzwyy2j9mg6n/openshot-qt.zip) (57 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/rtlh4os5eoagqoel33jnyzwyy2j9mg6n/libopenshot.zip) (47 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
Can't help here because the software just CLOSES.

**Comment by DanPinGF** [comment]
@JacksonRG - Seems like a duplicate of #4441.
