### ISSUE TITLE
Video frame freezes towards end of track, also affecting file preview

### ISSUE THREAD

**Issue by DanPinGF** [OpenShot/openshot-qt#4496]
**Describe the bug:**
This may be another long-term issue I've seen. All videos in OpenShot tend to have their frames freeze shortly before the end of their exact original duration. Audio also sounds very crappy as that happens.

**Steps to reproduce the behavior:**
N/A

**Expected behavior:**
Playback of the video files should have a smooth ending when playing in whole.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: possibly present since 2.5x?
- Operating System / Distro: Windows 11

**Log Files:**
N/A

**Exception / Stacktrace:**
N/A

**Comment by DanPinGF** [comment]
@JacksonRG - I need help! :'(

**Comment by JacksonRG** [comment]
The fix for this issue is currently being worked on. We're fixing a few related issues with how openshot deals with issues in the time marks within video files. I'll make a note to update you when It's ready, and we can make sure your use case is fixed.

**Comment by DanPinGF** [comment]
Anything yet? It's been a while.

**Comment by DanPinGF** [comment]
@JacksonRG - Please reopen this. This issue is NOT fixed at all.

**Comment by Colorjet3** [comment]
Have you tried the latest DEV Daily Build?  There was a fix in one of the Daily Builds.  Go to openshot.org/download/#daily and download the latest available.  Install it and give it a try.

Please let us know the result.

**Comment by DanPinGF** [comment]
I tried the Daily Build, and indeed, it was fixed there. But still other bugs to come.

**Comment by Colorjet3** [comment]
Glad this was fixed for you.  Keep the bugs coming so they can be taken care of.
