### ISSUE TITLE
autosave missing in action

### ISSUE THREAD

**Issue by nwgat** [OpenShot/openshot-qt#45]
the autosave options seem to be missing and please turn it on by default
![autosave_mia](https://cloud.githubusercontent.com/assets/5809156/12409905/7024dd28-be6f-11e5-83df-10fa924bde5f.png)

**Comment by nwgat** [comment]
with the current unstable windows build, its a pain to have to save everytime

**Comment by telelauro** [comment]
I agree with this, every time I do a test and when the program crashes, we are obliged to redo all operations.
It's a shame you do not have the autosave option, or automatically save you from time to time.

**Comment by jonoomph** [comment]
Autosave has been added to the newest build! Check the preferences now. Also, a new 'recovery' mode is enabled, which will auto save a 'backup.osp' project file for any unsaved projects (uses the same auto save interval setting), and is automatically restored after a crash. =)
