### ISSUE TITLE
Synchronizing issues open shot version 2.4.3

### ISSUE THREAD

**Issue by Kleurgevoel** [OpenShot/openshot-qt#4500]
After editing and exporting the sound comes after the images. How can I synchronize this? I already tried: edit -> preferences -> performance -> process video frames in parrallel to disable this (found a tip on the internet) this didn't work.
Does anybody know how to fix this?

**System Details:**
- OpenShot Version  2.4.3
- Operating System Ubuntu studio

**Comment by JacksonRG** [comment]
I would suggest separating the video from the audio to account for any issues with sound sync.

This also may have been fixed. The current release version of openshot is 2.6.1
