### ISSUE TITLE
Broken symbolic link

### ISSUE THREAD

**Issue by lfam** [OpenShot/openshot-qt#4502]
**Describe the bug:**

Since commit df1e4845ff7789c2735cc4a9a6691ff782b34052, the file `images/Humanity/actions/custom/razor_line_with_razor.png` has pointed to `../../../../timeline/media/images/razor_line_with_razor.png`, which does not exist.

This relative path should be adjusted to `../../../../src/timeline/media/images/razor_line_with_razor.png`

**Comment by JacksonRG** [comment]
Thanks for pointing this out. Know of any other broken links?

**Comment by JacksonRG** [comment]
NVM. just searched for links in the project, and didn't find any others.

**Comment by JacksonRG** [comment]
Just looked back at this and this file is no longer a link
