### ISSUE TITLE
External fonts for titles aren't recognized by OpenShot if installed on any account [Windows]

### ISSUE THREAD

**Issue by DanPinGF** [OpenShot/openshot-qt#4503]
**Describe the bug:**
I believe this is another long-term issue that's been around lately. OpenShot can't seem to recognize externally installed fonts for titles if they're installed on standard accounts, thereby falling back to the generic serif font.

**Steps to reproduce the behavior:**
1. Install any font from the Internet (e.g., from Google Fonts)
2. In OpenShot, go to 'Title' > 'Title'.
3. Click 'Change Font' and search for the font that was installed.
4. Result explained below upon clicking 'OK'.

**Expected behavior:**
The third-party external fonts would normally render just like the other system (internal) fonts. However, such font isn't recognized by OpenShot if they're installed on standard accounts, and as a result they fall back to the 'Times New Roman' generic serif font. The bug is also seen when the 'Ubuntu' font is chosen by default, which OpenShot installs right out of the box.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: possibly affecting v2.5.1+
- Operating System / Distro: Windows 11

**Log Files:**
N/A

**Exception / Stacktrace:**
N/A

**Screenshots:** (Optional)
![image](https://user-images.githubusercontent.com/28827920/138571967-154d0381-2f9b-4dea-9e76-7a8349ef5a9b.png)

**Comment by DanPinGF** [comment]
@JacksonRG - Is this ever going to get fixed?

**Comment by Colorjet3** [comment]
Hello @DanPinGF Try copying those External fonts in c:\windows\fonts folder.  Restart Openshot and now Openshot will pickup these new fonts.

Please confirm either way.
