### ISSUE TITLE
'Brightness & Contrast' and 'Hue' effects not doing very well

### ISSUE THREAD

**Issue by DanPinGF** [OpenShot/openshot-qt#4506]
**Describe the bug:**
The 'Brightness & Contrast' and 'Hue' effects in OpenShot have gone into a glitchy state since 2.6.0, making them completely useless.

**Steps to reproduce the behavior:**
1. Go to 'Effects'
2. Drag 'Brightness & Contrast' or 'Hue' to any video or image
3. Adjust the value of 'Brightness' above 0, for instance 0.08 (for 'Hue', this is done similarly)
4. Problem result explained below.

**Expected behavior:**
It should render correctly like in prior versions. However, the 'Brightness & Contrast' and 'Hue' effects seem to be broken since 2.6.0, resulting in glitching artifacts on the preview, and on export as well.

**System Details:**
- OpenShot Version: 2.6.1
- Operating System / Distro: Windows 11

**Log Files:**
N/A

**Exception / Stacktrace:**
N/A

**Screenshots:** (Optional)
![image](https://user-images.githubusercontent.com/28827920/138948211-8750cf9d-ef8b-4744-b525-862cbc0d78a9.png)

**Comment by DanPinGF** [comment]
@JacksonRG - This issue still needs to be resolved.

**Comment by JacksonRG** [comment]
@DanPinGF Heres the behavior I'm seeing for those effects. (Same on windows as well) Could you show me what glitchy behavior you're seeing?

https://user-images.githubusercontent.com/42394129/173715853-afd2375f-3caa-4a70-89d1-3d1d7a76dbaf.mp4

**Comment by DanPinGF** [comment]
@JacksonRG - When applying the 'Brightness & Contrast' or 'Hue' effects to an image that has alpha (transparency), no matter the value or intensity, they produce irregular colors on the affected image (see screenshot below).

![image](https://user-images.githubusercontent.com/28827920/173716693-7cd6c7dc-3b22-4118-8bcd-2e3c0b9a3030.png)

You can see here that, with 'Brightness & Contrast' applied to one of the images containing alpha (bottom left), as the video progresses, color distortion occurs, resulting in a crappy color corruption effect.

**Comment by JacksonRG** [comment]
Can you share the project file? I'm confused about the effect you're trying to achieve

**Comment by DanPinGF** [comment]
@JacksonRG - This is the project:

![image](https://user-images.githubusercontent.com/28827920/173896015-455f4628-3a3e-42c4-bc18-30b7706ef7ad.png)

The image selected in the timeline has the 'Brightness & Contrast effect applied to it.

**Comment by DanPinGF** [comment]
@JacksonRG - The problem continues to persist as of version 3.0.0. It has never been fixed in the Daily Builds.

**Comment by jonoomph** [comment]
Taking a look now

**Comment by jonoomph** [comment]
Yup, this is very strange! I can successfully reproduce it.

**Comment by Colorjet3** [comment]
@jonoomph I created a Trello card for this in the Backlog board.

**Comment by jonoomph** [comment]
A new daily build should be ready in about an hour with the fix for the following effects:
- Hue
- Brightness & Contrast
- Saturation

https://www.openshot.org/download/#daily
