### ISSUE TITLE
Importing MP4 results in "file is not a valid video, audio, or image file."

### ISSUE THREAD

**Issue by surfrock66** [OpenShot/openshot-qt#4508]
**Describe the bug:**
When attempting to import video into a project, I get a popup with the error "file is not a valid video, audio, or image file."  

**Steps to reproduce the behavior:**
1. In file browser, drag video file into open shot.
2. Popup happens.

**Expected behavior:**
Video should import

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 2.6.0-x86_64 AppImage and 2.6.1-x86_64 Appimage
- Operating System / Distro: Ubuntu 21.10

**Log Files:**
```
12:28:01 INFO main_window: Clear all thumbnails: /home/surfrock66/.openshot_qt/thumbnail
12:28:01 INFO main_window: Clear all animations: /home/surfrock66/.openshot_qt/blender
12:28:01 INFO main_window: Clear all titles: /home/surfrock66/.openshot_qt/title
12:28:01 INFO project_data: Setting default profile to HD 1080p 60 fps
12:28:01 INFO project_data: Loading project file: /home/surfrock66/Projects/StreamingVideos/2021.10.27.BellatrixPotionShop/2021.10.27.BellatrixPotionShop.osp
12:28:01 INFO project_data: checking project files...
12:28:01 INFO project_data: checking file /home/surfrock66/Projects/StreamingVideos/2021.10.27.BellatrixPotionShop/Titles.03.png
12:28:01 INFO project_data: checking file /home/surfrock66/Projects/StreamingVideos/2021.10.27.BellatrixPotionShop/Titles.02.png
12:28:01 INFO project_data: checking file /home/surfrock66/Projects/StreamingVideos/2021.10.27.BellatrixPotionShop/Titles.01.png
12:28:01 INFO project_data: checking file /home/surfrock66/Projects/StreamingVideos/2021.09.10.StillagerTest/Teh3l3m3nts.Titles.02.png
12:28:01 INFO project_data: checking file /home/surfrock66/Projects/StreamingVideos/2021.09.10.StillagerTest/Teh3l3m3nts.Titles.01.png
12:28:01 INFO project_data: checking file /home/surfrock66/Projects/StreamingVideos/teh3l3m3nts.ThemeSong.Extended.mp3
12:28:01 INFO project_data: checking file /home/surfrock66/Projects/StreamingVideos/Teh3l3m3nts.Intro.v01.mkv
12:28:01 INFO project_data: checking file /home/surfrock66/Projects/StreamingVideos/Teh3l3m3nts.Title.Thanks.png
12:28:01 INFO project_data: Project data: openshot 2.6.1, libopenshot 0.2.7
12:28:01 INFO preview_thread: player Position(): 1
12:28:01 INFO video_widget: Load: Set video widget display aspect ratio to: 1.7777777910232544
12:28:01 INFO video_widget: Set video widget pixel aspect ratio to: 1.0
12:28:01 INFO main_window: updateStatusChanged
12:28:01 INFO main_window: updateStatusChanged
12:28:01 INFO main_window: updateStatusChanged
12:28:01 INFO main_window: updateStatusChanged
12:28:01 INFO preview_thread: player Position(): 1
12:28:01 INFO main_window: Loaded project /home/surfrock66/Projects/StreamingVideos/2021.10.27.BellatrixPotionShop/2021.10.27.BellatrixPotionShop.osp
12:28:14 INFO files_treeview: Processing drop event for 1 urls
12:28:14 WARNING files_model: Failed to import /home/surfrock66/Projects/StreamingVideos/2021.10.27.BellatrixPotionShop/2021.10.26.BellatrixPotionShop.Replay.mp4: No Reader has been initialized for this Clip.  Call Reader(*reader) before calling this method.

```

Below is the description of the file; it is a "replay" made from minecraft's ReplayMod, which has worked in past versions (but it's been a while and I don't know which):

```
surfrock66@sr66-thelio:~/Projects/StreamingVideos/2021.10.27.BellatrixPotionShop$ mediainfo 2021.10.26.BellatrixPotionShop.Replay.mp4 
General
Complete name                            : 2021.10.26.BellatrixPotionShop.Replay.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41)
File size                                : 147 MiB
Duration                                 : 1 min 1 s
Overall bit rate                         : 20.1 Mb/s
Writing application                      : Lavf58.76.100

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.2
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 4 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 1 min 1 s
Bit rate                                 : 21.0 Mb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 60.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.169
Stream size                              : 147 MiB (100%)
Writing library                          : x264 core 160 r3011 cde9a93
Encoding settings                        : cabac=1 / ref=3 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=24 / lookahead_threads=4 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=25 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=abr / mbtree=1 / bitrate=20971 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00
Codec configuration box                  : avcC
```

**Screenshots:** (Optional)
![Openshot 01](https://user-images.githubusercontent.com/1345467/139135193-f4941153-136c-437d-b903-fd2bd497b259.png)

**Comment by surfrock66** [comment]
This is NOT an issue in the ubuntu openshot developers ppa, which is currently on 2.6.0-dev

**Comment by PurpleAlien** [comment]
Seeing the same on Gentoo (with media-video/openshot-2.6.1:1::gentoo, media-libs/libopenshot-0.2.7:0/21::gentoo).

**Comment by PurpleAlien** [comment]
Can be fixed by removing $HOME/.openshot_qt/openshot.settings
Related: https://github.com/OpenShot/openshot-qt/issues/4538

**Comment by kyrsjo** [comment]
Same on Fedora 35, both official AppImage 2.6.1, AppImage (daily build from today), Flatpack from Flathub (2.6.1), and RPM installed from rpmfusion (2.6.2). MKV file and MP4 files made in OBS does not load, neither does MP4 file from ZOOM which I have edited in OpenShot before, about 1 year ago.

**Comment by kyrsjo** [comment]
Renaming the openshot.settings worked. If the error is likely to be related to GPU, I recently switched from an older (Kepler) workstation GPU to a new AMD GPU.

**Comment by kyrsjo** [comment]
Finally, after renaming the settings file, the rpmfusion package worked! For some reason the AppImage version was missing the tracks on the bottom of the window.

**Comment by stepcodebox** [comment]
> Can be fixed by removing $HOME/.openshot_qt/openshot.settings Related: #4538

Thank you, this has helped. The issue is still present if you run an older version of OpenShot and then you download and switch to the latest version. The settings folder from the older version is causing this error. I solved it exactly by deleting the whole folder ~/.openshot_qt

**Comment by izzostar** [comment]
This bug still exists with OpenShot v.3.0 AppImage

**Comment by artemis-prime** [comment]
Same issue on 3.1.1 AppImage on Linux mint 21.3 86_64.  Why is this closed??

**Comment by leogallego** [comment]
I solved this by going to  **Edit > Preferences**, the **Performance** tab, and switching the "Hardware Decoder Mode", from **"Linux VDPAU"**  to **"Linux VA-API"**. Your options might vary depending on your GPU and installed libraries.

I have an AMD Radeon, supposedly it should support VDPAU, but for some reason it wasn't working. Deleting the `openshot.settings` file didn't fix it.

**Comment by Colorjet3** [comment]
Hardware acceleration in general hasn't been working well in OpenShot starting somewhere with v2.6.1 (daily builds and forward).  I am really surprised that deleting openshot.settings didn't fix the issue because that clears up all of the hardware acceleration settings and things work normally.

Thank you for the update and detailing the resolution as this can help others as well.

**Comment by Colorjet3** [comment]
> Same issue on 3.1.1 AppImage on Linux mint 21.3 86_64. Why is this closed??

This issue has been documented and is in the queue to be fixed.  It was closed because of the automated bot which does not matter since the it will be addressed when the lead developer has time to work on it.

I recommend for anyone reading this to go to openshot.org/download/#daily and get the latest dev daily build #11627.
