### ISSUE TITLE
Video Preview is not at expected Normal speed, it is too slow...waaaay toooo sloooow

### ISSUE THREAD

**Issue by TeleTwanger** [OpenShot/openshot-qt#4515]
**Describe the bug**
This is an issue several  others have reported, and has not been properly addressed.
I have tried this on two computers.  Both fresh, new installs of OS.  
Just as a first time test, I created a simple video based on four pics, and the default transition.  

I immediately found the The Video Preview is too slow. UNUSABLE.   The only way I can see the video as it should be is to Export it.

I repeat, hopefully you will hear me...straight out of the box install of OS, and The Video Preview is too slow. UNUSABLE.

How do we make it play at a NORMAL speed, just as it would look after an Export?

**Steps to reproduce the behavior:**

**Expected behavior**
Normal speed of the video in the Video Preview window.

**System Details**
- OpenShot Version: 2.6.1
- libopenshot Version:  0.2.7
- Platform: Windows-7-6.1.7601-SP1
- Processor: Intel64 Family 6 Model 45 Stepping 7, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Skipped this step

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/4gteewoqgmeu7h1u2lato4eyp85gu94q/openshot-qt.zip) (188 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)

**Comment by DanPinGF** [comment]
I'm having this problem, too. It doesn't affect QVGA/QCIF 15fps, however. @speedytechdev or @JacksonRG, kindly need some help over here...

**Comment by lookingafar** [comment]
I have the same problem on Manjaro 21.1

**Comment by Alfonsorb** [comment]
Experienced this exact same issue. Video preview was incredibly slow. Although for me it stopped showing any video altogether.

**Comment by DanPinGF** [comment]
It's almost been a year that OpenShot hasn't seen any feature updates. And with that it has a negative impact on its usefulness.

**Comment by awunes** [comment]
This seems to be duplicate of a previous issue: #4375

**Comment by DanPinGF** [comment]
> This seems to be duplicate of a previous issue: #4375

That's a little quite different, because the slowness happens only when an in-use audio output source is removed or disabled. I'd probably refer to #4303 in any case.

For OpenShot 2.6x, in general its playback performance is highly unreliable.

**Comment by awunes** [comment]
> > This seems to be duplicate of a previous issue: #4375
> 
> That's a little quite different, because the slowness happens only when an in-use audio output source is removed or disabled. I'd probably refer to #4303 in any case.
> 
> For OpenShot 2.6x, in general its playback performance is highly unreliable.

I'm a bit confused where you see "in-use audio output source" in either this #4515 or #4375. 

#4303 does refer to sound issues but both this issue (the one we're commenting on) and the one I suggested this to be duplicate of state the video preview is the issue. Yes #4375 does say there's no sound but I'd kind of expect that when the preview is going 1 frame per second.

Edit: Okay reading #4303 now - will edit this comment if needed (or remove)

So you're insisting that it "only when an in-use audio output source is removed or disable." is not accurate ... In my case I'm not changing the in-use audio devices at all.

**Comment by DanPinGF** [comment]
@JacksonRG - This issue still needs to be resolved.
