### ISSUE TITLE
Immediate crash whenever I try to import a particular video file (even converted to different format...

### ISSUE THREAD

**Issue by rmancinelli** [OpenShot/openshot-qt#4519]
**Describe the bug**
Whenever trying to import one particular *.mov video file into OpenShot, the program immediately crashes. I've tried converting to *.mp4, and even removing audio file, but no luck. This happens both when attempting to drag the file into OpenShot, and using the menu to "Import".

**Steps to reproduce the behavior**
Attempt to add video file to the library, either by dragging into OpenShot or File > Import Files
Program immediately closes for no reason with no error message

**Expected behavior**
I expect the program to remain open and not close so I can continue producing the video.

**System Details**
- OpenShot Version: 2.6.1-dev
- libopenshot Version:  0.2.7-dev
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-dev-daily-8563-f7cebb7f-73c519f0-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/j3evs580x503kktyld5g9xba3uveebi2/openshot-qt.zip) (5 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/j3evs580x503kktyld5g9xba3uveebi2/libopenshot.zip) (182 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Comment by DanPinGF** [comment]
Duplicate of #4480
