### ISSUE TITLE
Video stuttering (incl. sample file)

### ISSUE THREAD

**Issue by theelectricsoul** [OpenShot/openshot-qt#452]
To reproduce use 2.2.0

1. drop [Sample file](electricsoul.org/files/temp/00053.MTS) onto Track 01
2. Set profile to "HD 1080p 50fps"
3. Play file..... it should stútter
4. Change profile to "HD 720p 25fps"
5. Play file, it should stutter less

**OS Name**	Microsoft Windows 10 Pro
**Version**	10.0.14393 Build 14393
**OS Manufacturer**	Microsoft Corporation
**System Type**	x64-based PC
**Processor**	Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz, 3501 Mhz, 4 Core(s), 8 Logical Processor(s)
**Hardware Abstraction Layer**	Version = "10.0.14393.206
`

`    General
    Complete name                            : E:\temp\sample.mp4
    Format                                   : MPEG-4
    Format profile                           : Base Media
    Codec ID                                 : isom (isom/iso2/avc1/mp41)
    File size                                : 104 MiB
    Duration                                 : 34 s 560 ms
    Overall bit rate mode                    : Variable
    Overall bit rate                         : 25.2 Mb/s
    Writing application                      : Lavf57.25.100

    Video
    ID                                       : 1
    Format                                   : AVC
    Format/Info                              : Advanced Video Codec
    Format profile                           : High@L4.2
    Format settings, CABAC                   : Yes
    Format settings, ReFrames                : 2 frames
    Format settings, GOP                     : M=1, N=12
    Codec ID                                 : avc1
    Codec ID/Info                            : Advanced Video Coding
    Duration                                 : 34 s 560 ms
    Bit rate mode                            : Variable
    Bit rate                                 : 24.7 Mb/s
    Maximum bit rate                         : 26.0 Mb/s
    Width                                    : 1 920 pixels
    Height                                   : 1 080 pixels
    Display aspect ratio                     : 16:9
    Frame rate mode                          : Constant
    Frame rate                               : 50.000 FPS
    Color space                              : YUV
    Chroma subsampling                       : 4:2:0
    Bit depth                                : 8 bits
    Scan type                                : Progressive
    Bits/(Pixel*Frame)                       : 0.238
    Stream size                              : 102 MiB (98%)

    Audio
    ID                                       : 2
    Format                                   : AC-3
    Format/Info                              : Audio Coding 3
    Mode extension                           : CM (complete main)
    Format settings, Endianness              : Big
    Codec ID                                 : ac-3
    Duration                                 : 34 s 144 ms
    Bit rate mode                            : Constant
    Bit rate                                 : 448 kb/s
    Channel(s)                               : 6 channels
    Channel positions                        : Front: L C R, Side: L R, LFE
    Sampling rate                            : 48.0 kHz
    Frame rate                               : 31.250 FPS (1536 spf)
    Bit depth                                : 16 bits
    Compression mode                         : Lossy
    Stream size                              : 1.82 MiB (2%)
    Language                                 : unk
    Default                                  : Yes
    Alternate group                          : 1`

**Comment by jebeld17** [comment]
#550 
I'm having tons of performance issues on Windows 10 Pro (x64) as well. 😞

**Comment by DylanC** [comment]
@theelectricsoul - Thanks for the feedback. I will try this later today.

**Comment by DylanC** [comment]
@theelectricsoul -  Could not reproduce this one on the latest daily build.
