### ISSUE TITLE
WAV files don't play while editing video

### ISSUE THREAD

**Issue by patanoia** [OpenShot/openshot-qt#4521]
**Describe the bug**
When I add WAV files to the Timeline in the latest version, they do not play audio. Also, the timeline plays very slowly (a frame per second) even if it only contains a WAV file. I tried separating the audio (all channels) from the WAV file to see if that fixed it, but it did not.

When I export the video, the audio plays properly, so it is only an issue while editing.
**Steps to reproduce the behavior:**
1. Start a new project
2. Add a WAV file to the project.
3. Move the WAV file to the timeline.
4. Click Play.
5. No audio is heard.

**Expected behavior**
I expect to hear my audio, even if it is "stuttering" due to slow playback. This worked in the previous version.

**System Details**
- OpenShot Version: 2.6.1-dev
- libopenshot Version:  0.2.7-dev
- Platform: Windows-8.1-6.3.9600
- Processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-dev-daily-8572-aee3a44b-73c519f0-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/x44c20jeauylhtiazg7hefhyhlpb41v4/openshot-qt.zip) (82 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/x44c20jeauylhtiazg7hefhyhlpb41v4/libopenshot.zip) (402 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by awunes** [comment]
This also seems to be a duplicate of a previous issue: #4375 (a little different here though)
