### ISSUE TITLE
Cannot merge heterogeneous video formats

### ISSUE THREAD

**Issue by KloudKoder** [OpenShot/openshot-qt#4529]
**Describe the bug:**

This is probably due to a flaw in FFMPEG, which I assume you're using as a library. In any case, I have 2 videos that I want to concatenate, one after the other. I can neither merge them in OpenShot, nor commandline FFMPEG, but they can play just fine on their own. When I run "ffpeg -i" on the respective source MOV files, I get the following:

Stream #0:0(eng): Video: hevc (Main 10) (hev1 ...), yuv420p10le(tv, bt2020nc/bt2020/smpte2084, progressive), 3840x2160 [SAR 1:1 DAR 16:9], 23751 kb/s, 30 fps, 30 tbr, 15360 tbn, 30 tbc (default)
Metadata:
handler_name    : VideoHandle
encoder         : Lavc58.54.100 libx265
Stream #0:1(eng): Audio: aac (LC) (mp4a ...), 48000 Hz, stereo, fltp, 128 kb/s (default)

for the first MOV and

Stream #0:0(eng): Video: h264 (High) (avc1 ...), yuv420p(tv, bt709/bt709/smpte170m), 3840x2160, 48080 kb/s, SAR 1:1 DAR 16:9, 30.04 fps, 30 tbr, 90k tbn, 180k tbc (default)
Metadata:
handler_name    : VideoHandle
Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 255 kb/s (default)

for the second MOV.

When I merge them at the commandline, the first MOV plays just fine, but the second MOV plays audio only because the video stream is null, so the video freezes on the last frame of the first MOV.

When I merge them with OpenShot, everything plays just fine, but the first MOV contains faded colors because something is wrong is with the color palette processing. The second MOV looks normal. I've also seen this sort of behavior from FFMPEG from to time.

What I haven't mentioned is that the first MOV was upscaled from 1920x1080 to 3840x2160 using the following command, while the second was natively 3840x2160. The "color" parameters below are necessary to ensure that color fading/washout does not occur (which it _does_ with OpenShot):

ffmpeg -i FHD.MOV -vf scale=3840:2160,fps=30 -c:v libx265 -x265-params colorprim=bt2020:transfer=smpte2084:colormatrix=bt2020nc 4K.MOV

Unfortunately, doing this scaling results in a video which then cannot be merged with the second MOV, causing the aforementioned frame freeze at the command line (or reverting to faded colors in the case of OpenShot).

All this should "just work". OpenShot should know, based on my requested output resolution and framerate, what to do. It presumably knows the color encoding, resolution, and framerate of the input videos, so even if they're heterogenous, it should be able to transcode and render a video of the required output description and target bitrate.

**Steps to reproduce the behavior:**

I can't provide more details beyond what I've written above. Hopefully you won't literally need my videos in order to reproduce this. Worst case, use a Samsung phone and record a video in FHD 30 and another in UHD 30, and try to merge them in OpenShot, with the latter as the target resolution and framerate. You should see the color fade I mentioned (but just for the scaled-up FHD 30 portion).

**Expected behavior:**

The color should be faithfully reproduced even though transcoding is a lossy process.

**System Details:**

Latest OpenShot on Ubuntu 21.

**Log Files:**
N/A

**Exception / Stacktrace:**
N/A

**Screenshots:** (Optional)
N/A

**Comment by Anubhav-developr** [comment]
i didn't understand you should wait for the maintainer to see this issue, what prerequisites should i have to follow to contribute in this code base , i had seen there are less people contributing , it have to change .
i just knew c++ basics learnt in high school for 2 years including OOPs and data structures.
if i had great knowledge i could have definetly supported this for more advancement with my creativity.
P.S - i am not  maintainer of repository , i am just a random guy

**Comment by ferdnyc** [comment]
@KloudKoder 

Yeah, the basic problem here (I suspect) is that OpenShot is lacking in its support for 10-bit color / the BT2020 HDR colorspace.

I am curious, though -- if you export _only_ the first clip with OpenShot, do you get the same results? (Probably yes, which would indicate that we simply don't handle HDR video correctly, even on its own.)

The issue when trying with ffmpeg is that you can't switch colorspaces mid-stream, and since your second video uses the BT709 colorspace, trying to encode it to HDR fails. 

It's probably possible to do what you want with ffmpeg, but you'd have to apply a filter on the second video to resample it's color values into the BT2020 space. (Or, you could run a conversion job on it and create an intermediate video in the BT2020 space, before concatting it with the first stream.)

**Comment by ferdnyc** [comment]
The same command you used to upconvert the first vid _might_ even work to color-convert the second, just without the scaling:

`ffmpeg -i VID2.MOV -c:v libx265 -x265-params colorprim=bt2020:transfer=smpte2084:colormatrix=bt2020nc VID2HDR.MOV`

...But I doubt it, I think you'll need a filter to change colorspaces. I'm just not sure exactly what the syntax is, and I'm not able to check the ffmpeg docs right now. I'll try to remember to check into it later today.

**Comment by Anubhav-developr** [comment]
Wow, how many years of experience you guys have ?

**Comment by ferdnyc** [comment]
It looks like you may be able to just add a `-vf colorspace=bt2020`, to convert your second (BT.709) video into the HDR colorspace. That should allow you to combine it with the first video using `ffmpeg`. (It'll probably make them BOTH incompatible with OpenShot, unfortunately, which I still suspect mishandles any video in the BT.2020 space.)

**Comment by KloudKoder** [comment]
> Wow, how many years of experience you guys have ?

@Anubhav-developr Decades. If you want to get involved in the project, please discuss in the forum, not in a bug report that few people read anyway.

https://www.reddit.com/r/OpenShot

**Comment by KloudKoder** [comment]
@ferdnyc Thanks for the in-depth reply. Unfortunately, your BT2020 hack didn't work. After the merge, the first video plays normally, then the frame freezes for the remaining duration of the video (which should of course be the second video).

"if you export only the first clip with OpenShot, do you get the same results?" -- Yes. Pale colors.

Given the attributes displayed in the original report first posted above, could you suggest a set of FFMPEG commands that would merge them properly? (It's OK if I first need to convert the videos to some other format, so long as it preserves the signal for all practical purposes. And BTW I'm not worried about -crf stuff, which I can calibrate on my own. Just getting the colors, FPS, and resolution right without having these nonsensical outcomes.)

Honestly, FFMPEG is the only piece of software I've ever used which is actually less reliable than Windows 95. It's unfortunately the only option I'm aware of. I once tried to fix a similar problem on a MacBook but got similar garbage outputs. All this should "just work" with FFMPEG (or fail gracefully with a message about lack of support). It's absurd that it doesn't. Color spaces, resolutions, and framerates are well defined; one could convert everything to some superresolution intermediate frame format, then reencode back out to to the target format, but clearly that obvious solution is not happening with FFMPEG. And I often (not always) get this message about "nonmonotonous DTS". I mean WTF? You know the order and timing of the videos and their frames. Stop telling me that the clock is misaligned or something. Just fix it. And did I mention that FFMPEG sucks?

OK enough rant. I'm listening and very eager to try your next suggested experiment.

**Comment by Anubhav-developr** [comment]
> > Wow, how many years of experience you guys have ?
> 
> @Anubhav-developr Decades. If you want to get involved in the project, please discuss in the forum, not in a bug report that few people read anyway.
> 
> https://www.reddit.com/r/OpenShot

ok thanks sir.
