### ISSUE TITLE
Can not open OpenShot

### ISSUE THREAD

**Issue by dacorsa** [OpenShot/openshot-qt#4530]
i try to compile openshot from last source on github but when i launch i see:

19:03:44 dacorsa@NanoKDE /app/openshot-qt/src develop$ /usr/bin/python3.9 launch.py
Loaded modules from: /app/openshot-qt/src
INFO app: ------------------------------------------------
INFO app:             Mon Nov  8 19:11:11 2021            
INFO app:               Starting new session              
INFO app: ------------------------------------------------
INFO app:           OpenShot (version 2.6.1-dev)          
INFO app: ------------------------------------------------
INFO app: openshot-qt version: 2.6.1-dev
INFO app: libopenshot version: 0.2.7-dev
INFO app: platform: Linux-5.11.0-40-lowlatency-x86_64-with-glibc2.33
INFO app: processor: x86_64
INFO app: machine: x86_64
INFO app: python version: 3.9.7
INFO app: qt5 version: 5.15.2
INFO app: pyqt5 version: 5.15.4
INFO project_data: Setting default profile to HD 720p 30 fps
Screen DisplayPort-0
   devicePixelRatio: 1.0
   logicalDotsPerInch: 108.0
   physicalDotsPerInch: 163.33129935391244
   availableSizes: PyQt5.QtCore.QSize(3840, 2096)
INFO language: Qt Detected Languages: ['it']
INFO language: LANG Environment Variable: it_IT.UTF-8
INFO language: LOCALE Environment Variable: 
INFO language: OpenShot Preference Language: Default
INFO logger_libopenshot: Connecting to libopenshot with debug port: 5556
INFO app: Setting font to /app/openshot-qt/src/images/fonts/Ubuntu-R.ttf
INFO app: Setting custom dark theme
ERROR webview: Import failure loading WebKit backend
Traceback (most recent call last):
  File "/app/openshot-qt/src/windows/views/webview.py", line 163, in <module>
    from .webview_backend.webengine import TimelineWebEngineView as WebViewClass
  File "/app/openshot-qt/src/windows/views/webview_backend/webengine.py", line 38, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView, QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/openshot-qt/src/windows/views/webview.py", line 167, in <module>
    from .webview_backend.webkit import TimelineWebKitView as WebViewClass
  File "/app/openshot-qt/src/windows/views/webview_backend/webkit.py", line 36, in <module>
    from PyQt5.QtWebKitWidgets import QWebView, QWebPage
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'
Traceback (most recent call last):
  File "/app/openshot-qt/src/windows/views/webview.py", line 163, in <module>
    from .webview_backend.webengine import TimelineWebEngineView as WebViewClass
  File "/app/openshot-qt/src/windows/views/webview_backend/webengine.py", line 38, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView, QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/openshot-qt/src/launch.py", line 212, in <module>
    main()
  File "/app/openshot-qt/src/launch.py", line 207, in main
    app.gui()
  File "/app/openshot-qt/src/classes/app.py", line 263, in gui
    from windows.main_window import MainWindow
  File "/app/openshot-qt/src/windows/main_window.py", line 76, in <module>
    from windows.views.webview import TimelineWebView
  File "/app/openshot-qt/src/windows/views/webview.py", line 173, in <module>
    raise RuntimeError(
RuntimeError: Need PyQt5.QtWebEngine (or PyQt5.QtWebView on Win32)
INFO app:             OpenShot's session ended            
INFO app:             Mon Nov  8 19:11:12 2021            
INFO app: ================================================
19:11:12 dacorsa@NanoKDE /app/openshot-qt/src develop$ 

Someone can help me to solve?

Thanks 
Best regards

**Comment by bieli** [comment]
After `sudo apt upgrade` from last month on my Linux Ubuntu `20.04.3 LTS (Focal Fossa)` desktop, I can see the same problem.
@dacorsa I try to solve problems with [developer instruction](https://github.com/OpenShot/openshot-qt/blob/develop/doc/developers.rst) and compiling components from scratch, but sth. I can see is similar to you:
```bash
user@machine:~/openshot-qt$ python3 src/launch.py -d
Loaded modules from: /openshot-qt/src
INFO app: ------------------------------------------------
INFO app:             Sat Jan  8 23:16:54 2022            
INFO app:               Starting new session              
DEBUG app: Command line: ['src/launch.py']
INFO app: ------------------------------------------------
INFO app:           OpenShot (version 2.6.1-dev)          
INFO app: ------------------------------------------------
INFO app: openshot-qt version: 2.6.1-dev
INFO app: libopenshot version: 0.2.7-dev
INFO app: platform: Linux-5.11.0-38-generic-x86_64-with-glibc2.29
INFO app: processor: x86_64
INFO app: machine: x86_64
INFO app: python version: 3.8.10
INFO app: qt5 version: 5.15.2
INFO app: pyqt5 version: 5.15.4
INFO project_data: Setting default profile to HD 720p 30 fps
Screen eDP-1
   devicePixelRatio: 1.0
   logicalDotsPerInch: 96.0
   physicalDotsPerInch: 141.95107844318593
   availableSizes: PyQt5.QtCore.QSize(1920, 1080)
Screen HDMI-1
   devicePixelRatio: 1.0
   logicalDotsPerInch: 96.0
   physicalDotsPerInch: 123.92083938660211
   availableSizes: PyQt5.QtCore.QSize(2560, 1440)
Screen DP-1
   devicePixelRatio: 1.0
   logicalDotsPerInch: 96.0
   physicalDotsPerInch: 108.88753290260826
   availableSizes: PyQt5.QtCore.QSize(2560, 1440)
DEBUG language: Using compiled translation resources
INFO language: Qt Detected Languages: ['pl-PL']
INFO language: LANG Environment Variable: pl_PL.UTF-8
INFO language: LOCALE Environment Variable: 
INFO language: OpenShot Preference Language: Default
DEBUG language: Attempting to load qt_pl_PL.UTF-8 in '/usr/local/lib/python3.8/dist-packages/PyQt5/Qt5/translations'
DEBUG language: Attempting to load qtbase_pl_PL.UTF-8 in '/usr/local/lib/python3.8/dist-packages/PyQt5/Qt5/translations'
DEBUG language: Successfully loaded qtbase_pl_PL.UTF-8 in '/usr/local/lib/python3.8/dist-packages/PyQt5/Qt5/translations'
DEBUG language: Attempting to load qt_pl_PL.UTF-8 in '/openshot-qt/src/language'
DEBUG language: Attempting to load qtbase_pl_PL.UTF-8 in '/openshot-qt/src/language'
DEBUG language: Attempting to load OpenShot_pl_PL.UTF-8 in ':/locale/'
DEBUG language: Successfully loaded OpenShot_pl_PL.UTF-8 in ':/locale/'
DEBUG language: Exiting translation system (since we successfully loaded: pl_PL.UTF-8)
DEBUG app: Testing write access to user directory
ZmqLogger::Connection - Error binding to tcp://*:5556. Switching to an available port.
ZmqLogger::Connection - Error binding to tcp://*:5556. Switching to an available port.
DEBUG app: Loading UI theme
INFO logger_libopenshot: Connecting to libopenshot with debug port: 5556
INFO app: Setting font to /openshot-qt/src/images/fonts/Ubuntu-R.ttf
INFO app: Setting custom dark theme
ERROR webview: Import failure loading WebKit backend
Traceback (most recent call last):
  File "/openshot-qt/src/windows/views/webview.py", line 163, in <module>
    from .webview_backend.webengine import TimelineWebEngineView as WebViewClass
  File "/openshot-qt/src/windows/views/webview_backend/webengine.py", line 38, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView, QWebEnginePage
ImportError: /lib/x86_64-linux-gnu/libQt5Network.so.5: undefined symbol: _ZN15QIPAddressUtils8toStringER7QStringPh, version Qt_5

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/openshot-qt/src/windows/views/webview.py", line 167, in <module>
    from .webview_backend.webkit import TimelineWebKitView as WebViewClass
  File "/openshot-qt/src/windows/views/webview_backend/webkit.py", line 36, in <module>
    from PyQt5.QtWebKitWidgets import QWebView, QWebPage
ImportError: /lib/x86_64-linux-gnu/libQt5Network.so.5: undefined symbol: _ZN15QIPAddressUtils8toStringER7QStringPh, version Qt_5
Traceback (most recent call last):
  File "/openshot-qt/src/windows/views/webview.py", line 163, in <module>
    from .webview_backend.webengine import TimelineWebEngineView as WebViewClass
  File "/openshot-qt/src/windows/views/webview_backend/webengine.py", line 38, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView, QWebEnginePage
ImportError: /lib/x86_64-linux-gnu/libQt5Network.so.5: undefined symbol: _ZN15QIPAddressUtils8toStringER7QStringPh, version Qt_5

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/launch.py", line 216, in <module>
    main()
  File "src/launch.py", line 211, in main
    app.gui()
  File "/openshot-qt/src/classes/app.py", line 259, in gui
    from windows.main_window import MainWindow
  File "/openshot-qt/src/windows/main_window.py", line 76, in <module>
    from windows.views.webview import TimelineWebView
  File "/openshot-qt/src/windows/views/webview.py", line 173, in <module>
    raise RuntimeError(
RuntimeError: Need PyQt5.QtWebEngine (or PyQt5.QtWebView on Win32)
INFO app:             OpenShot's session ended            
INFO app:             Sat Jan  8 23:16:55 2022            
INFO app: ================================================

```
After operation:
```bash
$ sudo apt-get install --reinstall libqt5network5
```
I can see the same problem with `ImportError: /lib/x86_64-linux-gnu/libQt5Network.so.5: undefined symbol: _ZN15QIPAddressUtils8toStringER7QStringPh, version Qt_5`

**Comment by bieli** [comment]
I can see a conflict with my Python3 PyQt5 version - based on [this](https://github.com/OpenShot/openshot-qt/issues/3615) issue thread:
```bash
$ python3
Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyQt5.QtWebKitWidgets import QWebView
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /usr/local/lib/python3.8/dist-packages/PyQt5/QtCore.abi3.so)
>>> 
```
and I can see problems with different Qt version installed in operating system `5.12` and in Python module `5.15`:
```bash
$ sudo dpkg -l | grep libqt5 | grep -i network
ii  libqt5network5:amd64                       5.12.8+dfsg-0ubuntu2.1                            amd64        Qt 5 network module
ii  libqt5networkauth5:amd64                   5.12.8-0ubuntu1                                   amd64        online account access for Qt apps - Library
ii  libqt5networkauth5-dev:amd64               5.12.8-0ubuntu1                                   amd64        online account access for Qt apps - Development Files
```
This is not major change in semantic versioning, but I assume this is potentially bug.

What is interesting - I can see in shared library `/lib/x86_64-linux-gnu/libQt5Network.so.5` specific symbol from stack trace "_ZN15QIPAddressUtils8toStringER7QStringPh":

```bash
$ nm -D /lib/x86_64-linux-gnu/libQt5Network.so.5 | grep _ZN15QIPAddressUtils8toStringER7QStringPh
                 U _ZN15QIPAddressUtils8toStringER7QStringPh
```
but **I can't see version 5.15 symbols for Qt API in shared library** - I can see only:
```bash
0000000000000000 A Qt_5
0000000000000000 A Qt_5.0
0000000000000000 A Qt_5.1
0000000000000000 A Qt_5.10
0000000000000000 A Qt_5.11
0000000000000000 A Qt_5.12
0000000000000000 A Qt_5.2
0000000000000000 A Qt_5.3
0000000000000000 A Qt_5.4
0000000000000000 A Qt_5.5
0000000000000000 A Qt_5.6
0000000000000000 A Qt_5.7
0000000000000000 A Qt_5.8
0000000000000000 A Qt_5.9
0000000000000000 A Qt_5_PRIVATE_API

```

After about a few moments  of debugging this problem I think I can't install the proper version for Python PyQt module, because it isn't maintaining today:

```bash
$ pip3 install --pre pyqt5-tools==5.12.8
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement pyqt5-tools==5.12.8 (from versions: 5.14.0.1.7b3, 5.14.0.1.7, 5.14.0.1.7.1, 5.14.0.1.7.2, 5.14.0.1.7.3, 5.14.0.1.7.4, 5.14.0.1.7.5, 5.14.0.2, 5.14.0.3, 5.14.0.3.0.1, 5.14.0.3.0.2, 5.14.0.3.0.3, 5.14.0.3.1, 5.14.0.3.2, 5.14.1.1.7b3, 5.14.1.1.7, 5.14.1.1.7.1, 5.14.1.1.7.2, 5.14.1.1.7.3, 5.14.1.1.7.4, 5.14.1.2, 5.14.1.3, 5.14.1.3.0.1, 5.14.1.3.0.2, 5.14.1.3.0.3, 5.14.1.3.1, 5.14.1.3.2, 5.14.2.1.7b2, 5.14.2.1.7b3, 5.14.2.1.7, 5.14.2.1.7.1, 5.14.2.1.7.2, 5.14.2.1.7.3, 5.14.2.1.7.4, 5.14.2.1.7.5, 5.14.2.2b1, 5.14.2.2, 5.14.2.3, 5.14.2.3.0.1, 5.14.2.3.0.2, 5.14.2.3.0.3, 5.14.2.3.1, 5.14.2.3.2, 5.15.0.1.7, 5.15.0.1.7.1, 5.15.0.1.7.2, 5.15.0.1.7.3, 5.15.0.1.7.4, 5.15.0.1.7.5, 5.15.0.2, 5.15.0.3, 5.15.0.3.0.1, 5.15.0.3.0.2, 5.15.0.3.0.3, 5.15.0.3.1, 5.15.0.3.2, 5.15.1.1.7.2, 5.15.1.1.7.3, 5.15.1.1.7.4, 5.15.1.2b1, 5.15.1.2, 5.15.1.3, 5.15.1.3.0.1, 5.15.1.3.0.2, 5.15.1.3.0.3, 5.15.1.3.1, 5.15.1.3.2, 5.15.2.3, 5.15.2.3.0.1, 5.15.2.3.0.2, 5.15.2.3.0.3, 5.15.2.3.1, 5.15.2.3.2, 5.15.3.3.0.3, 5.15.3.3.1, 5.15.3.3.2, 5.15.4.3.0.3, 5.15.4.3.1, 5.15.4.3.2)
ERROR: No matching distribution found for pyqt5-tools==5.12.8

```
I assume - I need to switch to next level - compiling/preparing `PyQt 5.12.8 version` required for OpenShot from sources :-)

**Comment by bieli** [comment]
What I try to solve is compiling Qt from scratch for version 5.15 and install into OS (based on [this](https://wiki.qt.io/Building_Qt_5_from_Git#Getting_the_source_code) instruction - you need ~10GB free disk space for sources and dependencies, and ~1 hour time for compiling all stuff):

 ```bash
 sudo apt install llvm
 git clone git://code.qt.io/qt/qt5.git
 cd qt5/
 git checkout 5.15
 perl init-repository
 export LLVM_INSTALL_DIR=/usr/lib/llvm-10/
 mkdir qt5-build
 cd qt5-build
 ../configure -developer-build -opensource -nomake examples -nomake tests
### Do you accept the terms of either license? y
 make -j$(nproc)
 make install
```
and I can see ... ~30 GB allocated by compilation ;-)

In the meantime, I prepared my short [video](https://www.youtube.com/watch?v=hxa4y5ewQPU&list=PL5pu3VreT7bPVhfGlbLPHqTk882IFl96x&index=7) with Blender Video Editing :-)

**Comment by dacorsa** [comment]
Thanks @bieli but i don't know how fix it, i tried in virtual machine (virtualbox) if i install a fresh ubuntu all runs well....so is something installed after that breaks openshot.

**Comment by dacorsa** [comment]
@bieli remove all packages from develop ppa and install openshot-qt from the stable, now works!
ciao

**Comment by Cyborgscode** [comment]
Your OS should give you the latest version of QT5(now QT6). If it doesn't think of a distro change away from LTS to something more bleeding edge : Fedora, Arch, Suse etc
