### ISSUE TITLE
First Time User - several bugs and inconsistencies

### ISSUE THREAD

**Issue by www-MKRD-info** [OpenShot/openshot-qt#4531]
Hello,
As a OpenShot First Time User, but a professional user of Linux and Windows software, I immediately saw the following issues with OpenShot. This was from a Windows environment, so I am quite confused as to why I am seeing so many issues from the get-go:

1) There is no audio from the preview window, when importing a perfectly fine .mp4 file that is always playable with any other player on the same OS. I tried to choose a different audio output device in settings, but choosing any other device, and restarting, I get an error that audio output device is invalid. Never got audio working.

2) When exporting a project to a video file, OpenShot defaults to 720p, for a file which is natively 1920x1080p. Can file export default to resolution of file which was imported to OpenShot???

3) When exporting a project to a video, can it also auto-detect and match settings like framerate? I have a rather unusal 8fps webcam file I was editing. YES, I can manually overwrite this later in Advanced settings, but I am trying to avoid "transcoding" my file as much as possible.

4) When choosing "HD 1080p 23.98 fps" Simple pre-set menu option, in Advanced area I get a rather bizarre framerate of "24000". While selecting "HD 1080p 60 fps" option, I get a much more appropriate frame rate of 60.

5) After the export has been completed, and using the 1080p setting, I was having videos that said they were 1920x1078. What happened to two lines??? Unfortunately, I can't recreate this on subsequent exports... It IS possible I accidentally mouse-wheel-scrolled near the vertical resolution line... Which brings me to the point that the export options are somewhat unintuitive... Some settings like bitrate (even after using manual Medium quality, I then had to enter 1MB/s) it is not quite intuitive that I can change them, while other settings like vertical resolution of export, given my import file, should perhaps be a bit "harder" to overwrite???

So, if you address such inconsistencies for a first-time user, otherwise this is a solid software so far for my simple task of cutting out a section of a video file that had an inappropriate audio happen there. Thanks!

Last but not least, is there a way to cut/splice/trim a file NATIVELY, without import-project-edit-export??? I would prefer to avoid re-encoding a lossy codec into another lossy codec! Perhaps think about releasing a "YouTube"-grade video editor that works natively with files to do common operations like rotate/crop/beep out/watermark/trim/cut/splice/split natively right on the source file without having to transcode???

**Comment by DanPinGF** [comment]
That might be a question, but OpenShot is particularly known to have bugs in the stable release channel. You might want to check out #2725 for a (mostly) complete list of known problems since 2.4x

**Comment by www-MKRD-info** [comment]
> That might be a question, but OpenShot is particularly known to have bugs in the stable release channel. You might want to check out #2725 for a (mostly) complete list of known problems since 2.4x

Checked the listing out... And I thought my list was long! Are you telling me this thing is only slightly more polished compared to the Dia software [really scared face]???

**Comment by DanPinGF** [comment]
Well, I wanted to face the facts. Some of them were resolved, while others continue to exist (given that #1197, #4303 and #4319 are considered long-term bugs that occur in later versions).

**Comment by DanPinGF** [comment]
And to be completely exact, OpenShot isn't really considered that stable, though I do my best to try to deal with these bugs.

**Comment by www-MKRD-info** [comment]
> And to be completely exact, OpenShot isn't really considered that stable, though I do my best to try to deal with these bugs.

OK. As long as it is better than Dia, it must be better by a lot...
