### ISSUE TITLE
OpenShot ask for update but update does not install

### ISSUE THREAD

**Issue by Cosmolem** [OpenShot/openshot-qt#4540]
New to the software, never used it. Quite new to Linux too.
Right after a fresh install through the Ubuntu library on 20.04.3 LTS, OpenShot is already asking (or offering should I say) an update. When I click on the update button it direct me to the website page (not https but http... triggering a browser warning by the way...) where I can download the new version file v2.6.1
I've tried various way to start the install process of this file but nothing happen. What am I doing wrong ?
Thanks for your support :-)

**Comment by JacksonRG** [comment]
The default option at www.openshot.org/download from a linux machine will be an AppImage.

Try checking your downloads folder, here you should be able to right click on the `.AppImage` file, and enable executable permissions.

Non-gui way:
```bash
cd ~/Downloads/
chmod +x OpenShot-v2.6.1-x86_64.AppImage
```
This also just means "add executable permission"

Then you should be able to double click on the file.

Just @ me if you have any trouble with this

**Comment by Cosmolem** [comment]
Thank you very much for the fast and complete reply !
I didn't know about the "permission" thing. Now everything is fine, great.

**Comment by JacksonRG** [comment]
Good to hear. I'll close the issue then.
