### ISSUE TITLE
Star Wars animated title does not accept "\n" character, generating a single line title

### ISSUE THREAD

**Issue by manuellucena** [OpenShot/openshot-qt#4541]
**Describe the bug**
Star Wars animated title shows "\n" instead of doing a new line

**Steps to reproduce the behavior:**
1. Launch opehshot
2. Select "Animated Title"
3. Select the star wars intro like animated title generator
4. Move the slider preview to a frame near 100

**Expected behavior**
A two line blue text should appear, but instead you view a single line  with "\n" inside.

**System Details**
- OpenShot Version: 2.6.1
- libopenshot Version:  0.2.7
- Platform: Linux-5.11.0-40-generic-x86_64-with-Ubuntu-20.04-focal
- Processor: x86_64
- Machine: x86_64
- Python version: 3.6.9
- Qt5 version: 5.9.5
- PyQt5 version: 5.10.1
- Qt Detected Languages: ['es-ES']
- LANG Environment Variable: es_ES.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Skipped this step (Daily build interface looks too bad to be usable in my computer)

**Additional info**
Tried in several computers with both Appimage and Flatpak versions, and several Blender versions (2.80 to 2.95).

![Captura de pantalla de 2021-11-16 12-00-11](https://user-images.githubusercontent.com/34090706/141974026-467540f6-c26f-49d2-9d1a-c01c06246850.png)

**Comment by JacksonRG** [comment]
I made a change a couple months ago to the title editor, and was worried that was the cause. Rolled back to before that change, and the `\n` characters are still showing up... I'll have to keep looking into this
