### ISSUE TITLE
OpenShot Video Editor does not launch (Windows 10 64bit)

### ISSUE THREAD

**Issue by rbtrt** [OpenShot/openshot-qt#4545]
**Describe the bug:**
When launching the program, it closes immediately.

**Steps to reproduce the behavior:**
1. Launch OpenShot 2.6.1 on Windows 10 via the Shortcut or "C:\Program Files\OpenShot Video Editor\openshot-qt.exe" directly.
2. It appears on the Task Manager for a moment, then disappears, no error message is given.

**Expected behavior:**
The program should launch.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 2.6.1
- Operating System / Distro: Windows 10 64 bit 10.0.19043

**Log Files:**
18:09:50 INFO app: ------------------------------------------------
18:09:50 INFO app:             Sat Nov 20 18:09:50 2021            
18:09:50 INFO app:               Starting new session              
18:09:50 ERROR app: OpenShotApp::Import Error
Traceback (most recent call last):
  File "C:\Program Files\OpenShot Video Editor\classes\app.py", line 99, in __init__
    from classes import settings, project_data, updates
  File "C:\Program Files\OpenShot Video Editor\classes\project_data.py", line 48, in <module>
    import openshot
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\Administrator\builds\7546b651\0\OpenShot\openshot-qt/openshot.py", line 15, in <module>
ImportError: DLL load failed while importing _openshot: Das angegebene Modul wurde nicht gefunden.
18:09:50 INFO app:             OpenShot's session ended            
18:09:50 INFO app:             Sat Nov 20 18:09:50 2021            
18:09:50 INFO app: ================================================

**Comment by JacksonRG** [comment]
Did you install version 2.6.1 (the large blue button on our [download page](https://www.openshot.org/download/), or one of the daily builds?

Also, whichever you're using, does it also occur when you try the other?

**Comment by diegueno** [comment]
The same behavior occurs with OpenShot-v2.6.1-dev-daily-8737-18bdad43-0fb4ab09-x86_64
I installed it following instructions in the process of reporting how I can't add project files with OpenShot-v2.6.1-x86_6
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/7584932/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/7584933/openshot-qt.log)

**Comment by rbtrt** [comment]
> Did you install version 2.6.1 (the large blue button on our [download page](https://www.openshot.org/download/), or one of the daily builds?
> 
> Also, whichever you're using, does it also occur when you try the other?

I'm pretty sure I ran the daily build as well, I certainly tried the official version 2.6.1. Unfortunately, I don't have access to the "offending" PC at the moment, so I could verify if I tested the daily build.

**Comment by louagej** [comment]
Hi,
I'm experiencing the same problem.
System Details:
OpenShot Version: 2.6.1
Operating System: Windows 10 Pro
- Version 21H2
- OS Build: 19044.1348

I downloaded the latest version( today on the website)
![image](https://user-images.githubusercontent.com/7229592/145471668-6025c364-650a-4801-88d5-f5e4d303600e.png)


But when I'm trying to start the program, it just doesn't launch.
No Information in the EventViewer
The "C:\Users\ `My Username` \\.openshot_qt\openshot-qt.log" file stays empty

**Comment by PlayerIn3D** [comment]
Hello,
I have stumbled uppon almost the same error type where i can not open the program and i do not rly know that to do so i will paste the log file in hope that an sollution might arrise.


00:54:14 INFO app: ------------------------------------------------
00:54:14 INFO app:             Sun Dec 12 00:54:14 2021            
00:54:14 INFO app:               Starting new session              
00:54:14 INFO app: ------------------------------------------------
00:54:14 INFO app:             OpenShot (version 2.6.1)            
00:54:14 INFO app: ------------------------------------------------
00:54:14 INFO app: openshot-qt version: 2.6.1
00:54:14 INFO app: libopenshot version: 0.2.7
00:54:14 INFO app: platform: Windows-10-10.0.19041
00:54:14 INFO app: processor: Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
00:54:14 INFO app: machine: AMD64
00:54:14 INFO app: python version: 3.8.9
00:54:14 INFO app: qt5 version: 5.15.2
00:54:14 INFO app: pyqt5 version: 5.15.4
00:54:14 INFO app: Frozen version info from build server:
{
    "build_name": "OpenShot-v2.6.1-release-candidate-8238-59878784-d588dbd6",
    "date": "2021-09-04 23:49",
    "libopenshot": {
        "CI_COMMIT_REF_NAME": "release-20210904",
        "CI_COMMIT_SHA": "59878784732fa399c47ac5d282bfc9dfe470d0dc",
        "CI_JOB_ID": "27419",
        "CI_PIPELINE_ID": "8237",
        "CI_PROJECT_NAME": "libopenshot",
        "SO": "21",
        "VERSION": "0.2.7"
    },
    "libopenshot-audio": {
        "CI_COMMIT_REF_NAME": "release-20210904",
        "CI_COMMIT_SHA": "d588dbd6057f71c987dc6d8448322aa6b6e86f1a",
        "CI_JOB_ID": "27414",
        "CI_PIPELINE_ID": "8236",
        "CI_PROJECT_NAME": "libopenshot-audio",
        "SO": "8",
        "VERSION": "0.2.2"
    },
    "openshot-qt": {
        "CI_COMMIT_REF_NAME": "release-20210904",
        "CI_COMMIT_SHA": "11f8e5050bd95c7731beccda28a01fbb481fcf7d",
        "CI_JOB_ID": "27424",
        "CI_PIPELINE_ID": "8238",
        "CI_PROJECT_NAME": "openshot-qt",
        "SO": null,
        "VERSION": "2.6.1"
    }
}
00:54:14 INFO project_data: Setting default profile to HD 720p 30 fps
00:54:14 INFO language: Qt Detected Languages: ['en-US']
00:54:14 INFO language: LANG Environment Variable: 
00:54:14 INFO language: LOCALE Environment Variable: 
00:54:14 INFO language: OpenShot Preference Language: Default
00:54:14 INFO logger_libopenshot: Connecting to libopenshot with debug port: 5556
00:54:14 INFO app: Setting font to C:\Program Files\OpenShot Video Editor\images\fonts\Ubuntu-R.ttf
00:54:14 INFO app: Setting custom dark theme
00:54:15 INFO ui_util: Initializing UI for MainWindow
00:54:15 INFO webkit: WebKit backend initializing
00:54:15 INFO thumbnail: Starting thumbnail server listening on port 8701
00:54:15 INFO transition_model: updating transitions model.
00:54:15 INFO app:             OpenShot's session ended            
00:54:15 INFO app:             Sun Dec 12 00:54:15 2021            
00:54:15 INFO app: ================================================
00:54:15 INFO version: Found current version: {'error_rate_unstable': 0.05, 'openshot_version': '2.6.1', 'error_rate_stable': 0.05}

**Comment by TOADERFL** [comment]
> **Descrieți eroarea:** La lansarea programului, acesta se închide imediat.
> 
> **Pași pentru a reproduce comportamentul:**
> 
> 1. Lansați OpenShot 2.6.1 pe Windows 10 prin intermediul comenzii rapide sau direct „C:\Program Files\OpenShot Video Editor\openshot-qt.exe”.
> 2. Apare pentru un moment în Task Manager, apoi dispare, nu este dat niciun mesaj de eroare.
> 
> **Comportament așteptat:** programul ar trebui să se lanseze.
> 
> **Detalii sistem:**
> 
> * Versiunea OpenShot [de ex. 2.4.3]: 2.6.1
> * Sistem de operare / Distribuție: Windows 10 64 biți 10.0.19043
> 
> **Fișiere jurnal:** 18:09:50 Aplicație INFO: --------------------------------------- --------- 18:09:50 Aplicația INFO: sâmb. 20 noiembrie 18:09:50 2021 18:09:50 Aplicația INFO: Începe o nouă sesiune 18:09:50 EROARE aplicație: OpenShotApp::Eroare de import traceback (apel cele mai recente ultima): File "C: \ program Files \ OpenShot Video Editor \ clase \ app.py", linia 99, în **init** din clasele de import setări, project_data, actualizări de fișier „C: \ program Files \ OpenShot Video Editor\classes\project_data.py", linia 48, în importarea fișierului openshot "", linia 259, în fișierul load_module "C:\Users\Administrator\builds\7546b651\0\OpenShot\openshot-qt/openshot.py", rândul 15, în ImportError: încărcarea DLL a eșuat la import _openshot: Das angegebene Modul wurde nicht gefunden. 18:09:50 Aplicația INFO: Sesiunea OpenShot s-a încheiat 18:09:50 Aplicația INFO: sâmb. 20 noiembrie 18:09:50 2021 18:09:50 Aplicația INFO: ============== ===================================

Set the display language of win 10 to English US (for example I had Romanian and so on, it didn't start). It worked for me width EN US!(for 30 computers)

**Comment by louagej** [comment]
![image](https://user-images.githubusercontent.com/7229592/148411038-80fa24db-feed-43f9-bce7-d1a7ebaf98da.png)

My Windows language is English US, so that won't do the trick

**Comment by Frari489** [comment]
Hi, had the same issue, found the solution.

It appears the issue is because Windows N does not include Microsoft Media Future pack by default.    

I fixed the issue by following method 1 in following link: https://ugetfix.com/ask/how-to-fix-mfplat-dll-missing-on-windows-10/

You will probably have to find the correct version of the media pack by going to: https://support.microsoft.com/en-us/topic/media-feature-pack-list-for-windows-n-editions-c1c6fffa-d052-8338-7a79-a4bb980a700a

**Comment by tkazik** [comment]
Thx a lot @Frari489, the media future pack was also missing in my case (W11): Please find it [here](https://support.microsoft.com/en-us/windows/media-feature-pack-for-windows-n-8622b390-4ce6-43c9-9b42-549e5328e407)

Cheers

**Comment by JacksonRG** [comment]
@tkazik Could you share some details about your computer setup like your processor, and the OpenShot versions involved? (I'd ask what OS, but I assume from your comment you're using Windows 11.3)

I'd love to track this issue down, and see if we can include those media packs in openshot's installer.

**Comment by tkazik** [comment]
@JacksonRG sorry for the delay:

* MS Windows Version 21H2
* AMD Ryzen 7 PRO 5850U with Radeon Graphics
* OpenShot version 2.6.1

Hope this helps.

**Comment by stonefrango** [comment]
I'm experiencing this same issue. I don't have Windows N. The language on my PC is English and the language I selected during OpenShot installation is also English.

OpenShot version: 2.6.1
CPU: AMD FX(tm)-6300 Six-Core Processor
OS: Windows 10 Pro
Version: 21H2
OS Build: 19044.1766

I'm happy to provide any logs I can, just not sure where to get them.

**Comment by JacksonRG** [comment]
@tkazik Unfortunately I don't have an `N` edition of windows to test on, but several users have reported that
https://support.microsoft.com/en-us/windows/media-feature-pack-for-windows-n-8622b390-4ce6-43c9-9b42-549e5328e407
support page from microsoft explains that `N` editions are missing the media futures pack, which has to be manually enabled to allow windows to access several types of media.

If that helps you, I can work on adding a special error message to openshot which directs people to install that media pack.

**Comment by JacksonRG** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Windows N Wont start](https://trello.com/c/JbbesAQj/151-windows-n-wont-start)

**Comment by tkazik** [comment]
> If that helps you, I can work on adding a special error message to openshot which directs people to install that media pack.

If you can detect that, yes, please. This will certainly be appreciated by someone running into the same surprise :)

**Comment by slimbyte** [comment]
In my installation: v.2.6.1, Win10 Pro 21H2 the issue seems to be related to transitions translation.
Source files of error: `C:\Program Files\OpenShot Video Editor\windows\models\transition_model.py`
code lines:
```
                    if suffix_number:
                        trans_name = trans_name.replace(suffix_number, "%s")
                        trans_name = self.app._tr(trans_name) % suffix_number
                    else:
                        trans_name = self.app._tr(trans_name)
```
More exactly, Luminous boxes transition models failed to translate. In my case (romanian language) **Luminous boxes %s** translates to **Cutii luminoase %**. Please note the missing **s**. So, with this translation, the following code block which should replace the **%s** with the  **suffix_number** will fail.

Putting the affected code into a try: except: block solved the issue and the launch of OpenShot completed successfully.
```
                try:
                    if suffix_number:
                        trans_name = trans_name.replace(suffix_number, "%s")
                        trans_name = self.app._tr(trans_name) % suffix_number
                    else:
                        trans_name = self.app._tr(trans_name)
                except:
                    log.info("Failed to translate {}".format(trans_name.replace("%s", suffix_number)))
```

Luminous boxes transitions remains untranslated, which is not a big deal.

**Comment by JacksonRG** [comment]
@slimbyte Thanks for your debugging on this issue. What language are you running openshot in? We have automatic tests of our translation code, so this may help us find a gap in that testing.

**Comment by slimbyte** [comment]
@JacksonRG I was running OpenShot in Romanian language.

**Comment by vadrian89** [comment]
> In my installation: v.2.6.1, Win10 Pro 21H2 the issue seems to be related to transitions translation. Source files of error: `C:\Program Files\OpenShot Video Editor\windows\models\transition_model.py` code lines:
> 
> ```
>                     if suffix_number:
>                         trans_name = trans_name.replace(suffix_number, "%s")
>                         trans_name = self.app._tr(trans_name) % suffix_number
>                     else:
>                         trans_name = self.app._tr(trans_name)
> ```
> 

> More exactly, Luminous boxes transition models failed to translate. In my case (romanian language) **Luminous boxes %s** translates to **Cutii luminoase %**. Please note the missing **s**. So, with this translation, the following code block which should replace the **%s** with the **suffix_number** will fail.
> 
> Putting the affected code into a try: except: block solved the issue and the launch of OpenShot completed successfully.
> 
> ```
>                 try:
>                     if suffix_number:
>                         trans_name = trans_name.replace(suffix_number, "%s")
>                         trans_name = self.app._tr(trans_name) % suffix_number
>                     else:
>                         trans_name = self.app._tr(trans_name)
>                 except:
>                     log.info("Failed to translate {}".format(trans_name.replace("%s", suffix_number)))
> ```
> 
> Luminous boxes transitions remains untranslated, which is not a big deal.

Same issue with romanian language, thank you for the work around!.

Windows 11 PRO

**Comment by Colorjet3** [comment]
Please try the latest DEV Daily Build of v3.0.0 and confirm either way.

**Comment by conterio** [comment]
my fix was
```
On Windows 10 N: Select Start, then select Settings > Apps > Apps and Features > Optional features > Add a feature. Find the Media Feature Pack in the list of available optional features.

On Windows 11 N: Select Start, then select Settings > Apps > Optional features. Select View features next to Add an optional feature, and then select the Media Feature Pack in the list of available optional features.
```
