### ISSUE TITLE
Keyframes do not move when resizing transition clip.

### ISSUE THREAD

**Issue by mader-levap** [OpenShot/openshot-qt#4546]
**Describe the bug:**
When you resize transition, keyframes stay in place. That results in unexpected and usually undesirable behavior, like transition not working or only partially working.

**Steps to reproduce the behavior:**
1. In OpenShot drag and drop some transition onto some track.
2. Note that at beginning of transition there is Brightness value 1,0 and at end (10 sec is default length of transition) is value -1,0.
3. Move head to say 00:00:01,30 (exact place is not important). Note value of Brightness - for this example it should be 0,88.
4. Change End property of transition clip to 1,3, so now transition ends where your head is.
5. Note that Brightness at 00:00:01,30 is still 0,88. Transition is shorter, but keyframe stays at 10,0 (though invisible).

**Expected behavior:**
When I change End property of transition, I expect keyframes to be scaled proportionally, so if at old end there was keyframe with value -1, then after resize keyframe should move where new end is.

If you want keyframes to stay where they were even after resize (I think it will be rare case), you could add "Lock Keyframes"/"Unlock Keyframes" option to transition clip popup menu or something like that.

**System Details:**
- OpenShot Version: 2.6.1-dev-daily-8737
- Operating System: Windows 10

**Comment by ivab-test** [comment]
Reproduced on OpenShot 3.0.0. Windows defender blocked daily build installation, that is why I didn't check it on the daily build.

Additional note regarding steps to reproduce:
The issue appears only if you type the **End** value in transition properties. 

- If you drag the transition borders (i.e., resize with a mouse), then the missing key frame appears. There is no way to set duration precisely in this way, so I do not consider it as a workaround.
- **If you drag the transition itself within the track, then the missing key frame appears too.** This is more suitable as a workaround, considering that you can use snapping or type precise **Position** value to put the transition back to its original position.

**Comment by Colorjet3** [comment]
Hello @ivab-test.  Thank you for the update.  I still would like you to try the daily build. Defender doesn't block but rather flags it as unsafe.  Currently this is do to an expired certificate which has been updated but will take time to get validated.  For now, when the warning screen is displayed, click on "More Info" and you can continue with the download/installation.

The latest available Daily Build is v3.1.0-release-candidate soon to be released as production.  I am curious if this issue still persists in v3.1.0.

**Comment by ivab-test** [comment]
Hi, Yep, I clicked on the More Info, and there was nothing about continue installation. So, it is blocked. Perhaps, there is some group policy in action, since I was installing it on my workstation and I am not an admin there. So, i can try with the daily build, but only when the new certificate get validated. Please forgive me for not satisfying your curiosity earlier 😊Best regards,Ivan
