### ISSUE TITLE
frame by frame

### ISSUE THREAD

**Issue by citizen6141** [OpenShot/openshot-qt#4548]
how to move thru video frame by frame with mouse or shortcut key

**Comment by JacksonRG** [comment]
Right and left arrows should move forward and back one frame respectively

**Comment by citizen6141** [comment]
thanks that makes too much sense DUHHHHHHHH
pause video and hit right or left arrow to move frame by frame
also hold down arrow to move faster

BTW its great F*n software
wish i had it sooner to save big bucks

**Comment by JacksonRG** [comment]
No problem! Let us know if you have any other questions!

By the way, Ctrl+[left or right] will skip to the beginning or end of a clip. It's a good way to make sure you're setting any gradual effects to start on the first frame of a clip.
