### ISSUE TITLE
impossible to export projects.

### ISSUE THREAD

**Issue by jordi60** [OpenShot/openshot-qt#4555]
Impossible to export projects

[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/7601557/libopenshot.log)

[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/7601558/openshot-qt.log)
[Doc1.docx](https://github.com/OpenShot/openshot-qt/files/7601559/Doc1.docx)

**Comment by nikescar1** [comment]
Same. When exporting I get the "Could not write header to file" regardless of where I try to export. Tried running in admin mode with the same result. Seems like OpenShot doesn't have permission to write files and I don't know how to fix it

**Comment by JacksonRG** [comment]
From that screenshot, it looks like you're exporting a `.3gp` file. Does this happen with Other video file types? For instance, could you try with an mp4 file?

@nikescar1 @jordi60 could you both include some info on your computers to help us diagnose? (ie Operating System, Computer Hardware, etc)

Also, @nikescar1 what type of video file did you have this problem with?
