### ISSUE TITLE
crash when separating audio from audio-only file

### ISSUE THREAD

**Issue by jakobssvar** [OpenShot/openshot-qt#4559]
**Describe the bug:**
crash / silent immediate exit of the program

**Steps to reproduce the behavior:**
1. I tok a videoclip and separated the sound. 
2. I did it again from the audio clip by a mistake
3. the program crashed.

**Expected behavior:**
nothing, block the option to separate out audio from audio or a popup telling me I can't do that, anything but the program crashing really.
I would be happy with a  safe fallback

**System Details:**
- OpenShot Version 2.6.1
- Operating System  Windows 10

**Comment by JacksonRG** [comment]
Thanks for pointing this out!

**Comment by JacksonRG** [comment]
Actually, I just tried this, and didn't have a crash. Could you include your [log file](https://github.com/OpenShot/openshot-qt/wiki/Issue-Logging), and what video format this happened with? (e.g. `.mp4` `.mov`) If you're willing to share the file that does this, that may also help.
