### ISSUE TITLE
Rendered 60fps video in slow motion is broken

### ISSUE THREAD

**Issue by jk-85** [OpenShot/openshot-qt#4562]
I had an old version and updated to latest version 2.6.1, but the bug still exists. Simply put [this ](https://filehorst.de/d/eehCkuuc) clip in and drag it to the timeline and than use that clip again and drag the same clip into the timeline and make 1/2 or 1/4 slowmotion and the rendered output broken. Note that this clip is 60fps. I tried different output codecs but it didn't work.

**Comment by otherwayup** [comment]
I have an issue that Stabilization is not in the rendered output when I select any 60fps output, but it is in the output if I select any 30 fps output format (resolution).

If your source is 60 fps, then I guess you could be selecting a 60 fps output.  What happens if you select 30 fps output?

If it works ok, then maybe there is a general issue with 60 fps output.

**Comment by jk-85** [comment]
30fps works, only 60fps is the problem.

**Comment by JacksonRG** [comment]
Could you include info about your setup? (ie operating system, and computer hardware)

Also what video formats does this happen with? (mp4, MOV, AVI etc.) And if you have multiple formats does this happen with all of them?

**Comment by jk-85** [comment]
I tried different formats, but no one worked. I use Windows 7 SP1 (Phenom X4 910 E, 16 GB RAM). 30fps works, but 60fps not. Thanks.

**Comment by JacksonRG** [comment]
Thanks, and are you using 2.6.1 the official release or the daily build? Whichever one you are using could you try the other? That might narrow down where this issue appeared.

**Comment by jk-85** [comment]
Hi, I tested latest daily build (64 bit) and tried some 60fps formats, but the same problem again. Slowmotion seems that there were cut some seconds off, but 30fps works.

**Comment by otherwayup** [comment]
I had an issue (#4557) with stabilization not applied to 60 fps export.  I've managed to get it working by changing the default preview to 1080 60 fps and starting a new project, adding the effect and exporting a 60 fps with stabilization applied successfully.

However, when I open my old project (which was created when default preview was 720 30 fps), it has [HD 720p 30fps] in the top left corner after project name even though the default preview is still set as 1080 60 fps and the stabilization is not applied to 60 fps exports (ok for 30 fps exports).

So, where does OpenShot get the [HD 720p 30fps] info. from for the old project, that it displays in top left corner and how can I reset this on my old project to [HD 1080p 60fps], as that MAY fix it?

**Comment by otherwayup** [comment]
jk, have you tried changing default preview to a 60 fps option in settings, restarting OpenShot, then re-creating the Project again from New?  I got stabilization to work on 60fps by doing this, so maybe that will fix Slowmotion as well?

**Comment by jk-85** [comment]
I did it, crazy, now it works.
