### ISSUE TITLE
Updating source files does not update clip properties

### ISSUE THREAD

**Issue by xtremeqg** [OpenShot/openshot-qt#4563]
**Describe the bug:**
A project I was working on included a backing sound track. After modifying the source audio file and extending it, OpenShot did not update any of the clip, project or track properties and continued to use old values for length, size, etc. Closing and re-opening OpenShot did nothing. Re-importing the file did nothing. Removing the clip from the timeline and re-adding it was not an option as it had several dozen key frames adjusting clip parameters.

**Steps to reproduce the behavior:**
1. Create a new project.
2. Import an audio file.
3. Add audio file to timeline.
4. Save project.
4. Close OpenShot.
5. Replace source audio file with a longer audio file.
6. Reopen Openshot.
7. Reopen project.
8. Observe both the imported file and clip retain original length.

**Expected behavior:**
* Imported details should respect on-disk properties (length, size, etc).
* Clip properties should respect on-disk properties (length, size, etc).

**System Details:**
- OpenShot Version 2.4.3.
- Operating System / Distro: Linux Mint 20.1

**Workaround:**
Editing osp project file by hand and updating all incorrect values is possible, though very non-user friendly.

**Comment by JacksonRG** [comment]
To keep all the keyframes you've worked on, right click on the clip, and under `copy` you should find options to copy both keyframes and effects.

Also, all items on the timline are clips (even if you drop the file onto the timeline, then the start and end are set to the file's values).

If the updated file is in the same location, and has the same name, you should be able to either drag the right side of that clip farther than previously, or edit the `end` property in the clip's properties.

Let me know if this helps
