### ISSUE TITLE
Can't seem to get out of waveform view on tracks...

### ISSUE THREAD

**Issue by DanPinGF** [OpenShot/openshot-qt#4566]
**Describe the bug:**
I've started seeing this lately. Showing a track's waveform appears to be permanent. I cannot go back to thumbnail display.

**Steps to reproduce the behavior:**
1. Import a track, drag it to timeline
2. Right-click on track and choose 'Display' > 'Show waveform'
3. Right-click again and choose 'Display' > 'Show thumbnail'
4. And nothing happens; waveform on track is still shown.

**Expected behavior:**
It should have been possible to configure the tracks to be shown as thumbnail or waveform. But it has now become apparent that the 'Show waveform' setting permanently locks the other setting ('Show thumbnail') so that the waveform will always be shown. A workaround to this, however, is to remove the track and undo--or in the case of a saved project, close the session and reopen.

**System Details:**
- OpenShot Version: 2.6.1
- Operating System / Distro: Windows 11

**Log Files:**
N/A

**Exception / Stacktrace:**
N/A

**Comment by Colorjet3** [comment]
I just tested this and experience the same symptom.  I am running Windows 10 and OpenShot version 2.6.1.-dev daily build #8775.

**Comment by DanPinGF** [comment]
@JacksonRG @speedytechdev - Kinda need some help over here...

**Comment by DanPinGF** [comment]
@JacksonRG - This issue still needs to be resolved.

**Comment by Colorjet3** [comment]
Hi @JacksonRG.  This issue most likely is related to Trello card #76 (Waveforms disappear when re-opening a project).  This Trello card #76 also makes references to issue numbers 4769 and 4819.

**Comment by JacksonRG** [comment]
@Colorjet3 was this on the most recent daily? I can't seem to reproduce, but I'll try it on windows as well

**Comment by JacksonRG** [comment]
@Colorjet3 was this on the most recent daily? I can't seem to reproduce, but I'll try it on windows as well

**Comment by Colorjet3** [comment]
This is still an issue with build #9498 in both Windows 10 & Windows 11.  I confirmed that this is working in Ubuntu.

**Comment by DanPinGF** [comment]
Hmm... it appears to have been fixed starting with version 3.0.0.

**Comment by Colorjet3** [comment]
Yes, it was actually fixed in one of the v3.0.0 daily builds and now it is in production.
