### ISSUE TITLE
Menu bar is missing

### ISSUE THREAD

**Issue by claydoh** [OpenShot/openshot-qt#4567]
**Describe the bug**
There are no menus when opening the application - there is no way to access settings, views, etc as there is no menu bar.
The usual ctrl-m does not reveal them.

This is in both 2.6.1, as well as current daily builds of both appimages and from the PPA
Not sure if I am missing something stupid here.

KDE Neon - Ubuntu 20.04 based. 

**Steps to reproduce the behavior:**
1.Open Openshot
2. see missing menus/menu bar

**Expected behavior**
APpplication should show all menus

**System Details**
- OpenShot Version: 2.6.1-dev
- libopenshot Version:  0.2.7-dev
- Platform: Linux-5.13.0-22-generic-x86_64-with-neon-20.04-focal
- Processor: x86_64
- Machine: x86_64
- Python version: 3.6.9
- Qt5 version: 5.9.5
- PyQt5 version: 5.10.1
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: en_US.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-dev-daily-8775-18bdad43-0fb4ab09-x86_64.AppImage

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/dwzs3ebk1cic9747bu3fgd1s3z4f7jzo/openshot-qt.zip) (5 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Comment by JacksonRG** [comment]
Do you have KDE configured to hide menu bars by default? I know that's an issue I ran into when I ran KDE. Often `alt` or `alt+f3` can bring up the menu.

Also just to make sure we're talking about the same thing:
![MenuBar](https://user-images.githubusercontent.com/42394129/144493469-5cc8da61-e1ce-4939-91f7-4d35d09d5143.png)

Its the top row row in this picture, right?

**Comment by claydoh** [comment]
We can close this.
The menus are visible again. 

It was not hidden, and though KDE does often hide the menus, they are easily found via hamburger menus.
The bug is still with Plasma, and unrelated to OpenShot but I am not sure where, as this somehow fixed itself, or I did something that fixed it.  It is also highly likely I did something that caused it to begin with.

**Comment by JacksonRG** [comment]
Good to hear!
