### ISSUE TITLE
2.6.x runs incredibly slowly

### ISSUE THREAD

**Issue by danielrcollins1** [OpenShot/openshot-qt#4568]
**Describe the bug:**
OpenShot version 2.6 (both 2.6.0 and 2.6.1) run so incredibly slowly on my system as to be nonfunctional. Any preview clip runs at about 1 second of footage every 30 real-time seconds. Meanwhile, CPU usage stays close to zero (0-2% on four cores) throughout the process. This was not the case with prior versions.

**Steps to reproduce the behavior:**
1. Open OpenShot
2. Add any video to Project Files
3. Add that file to a track
4. Preview play the video

**Expected behavior:**
A single short video track should play at normal speed, as was the case for any version of OpenShot up to 2.5.1 for me.

**System Details:**
- OpenShot Version 2.6.0 and 2.6.1
- Operating System / Distro: Windows 7 SP 1, Intel Core i3-3240 @ 3.4 Ghz, 8 GB, 64-bit

**Log Files:**
N/A (not a crash)

**Exception / Stacktrace:**
N/A

**Screenshots:** (Optional)
N/A

**Comment by DanPinGF** [comment]
Looks like a duplicate of #4515.

**Comment by awunes** [comment]
> Looks like a duplicate of #4515.

which is a duplicate of #4375

**Comment by DanPinGF** [comment]
> > Looks like a duplicate of #4515.
> 
> which is a duplicate of #4375

But #4375 is different! That issue has to do with audio output devices, and OpenShot can only handle one output source per session (see #4303). Removing or disabling the device simply induces the problem.

**Comment by awunes** [comment]
> > > Looks like a duplicate of #4515.
> > 
> > 
> > which is a duplicate of #4375
> 
> But #4375 is different! That issue has to do with audio output devices, and OpenShot can only handle one output source per session (see #4303). Removing or disabling the device simply induces the problem.

Except #4375 doesn't have anything to do with audio output devices. It's literally only about opening the program, adding a video source, trying to preview it. You were the first to say it had to do with #4303 however the OP stated "That's not the problem." right after your post: https://github.com/OpenShot/openshot-qt/issues/4375#issuecomment-946323329

**Comment by DanPinGF** [comment]
Oh...

**Comment by braintweak** [comment]
Same for me.
Win 10 Version 10.0.17763.2330
Ryzen 3600, AMD r9 280 gpu.
2.6.1 is a slideshow while previewing a an imported video.
Old 2.4.4 I've been using for a long time has no such issues.

Tested OpenShot-v2.5.1-x86_64 - works fine.
v2.6.1-dev-daily-8906-3c8dc71b-2b8b05c7-x86_64 has preview sped up and no sound, but at least not that laggy.

**Comment by robin-a-meade** [comment]
I had some luck after deleting the `~/.openshot_qt` directory; preview speed returned to normal. (I use the openshot-2.6.2-0.1.20211104gitb72327d.fc35 package from rpmfusion on Fedora 35). Warning: deleting that directory will delete your OpenShot preferences.

**Comment by danielrcollins1** [comment]
> I had some luck after deleting the `~/.openshot_qt` directory; preview speed returned to normal. (I use the openshot-2.6.2-0.1.20211104gitb72327d.fc35 package from rpmfusion on Fedora 35). Warning: deleting that directory will delete your OpenShot preferences.

I just tried that on Windows 7. Fails to fix the behavior for me; OpenShot 2.6 still an unusable slideshow.

**Comment by DanPinGF** [comment]
> I just tried that on Windows 7. Fails to fix the behavior for me; OpenShot 2.6 still an unusable slideshow.

Well, doing a fix that doesn't apply to your operating system won't work. The fix that @robin-a-meade did is perhaps a Linux-only thing.

**Comment by awunes** [comment]
> Well, doing a fix that doesn't apply to your operating system won't work.

Doesn't hurt to try. 

Though I had already tried and found further issues. See #4688 The last 2 daily builds fail to open. Also, the OP here was for 2.6.2 which isn't a thing for windows from what I can see.

**Comment by danielrcollins1** [comment]
> Also, the OP here was for 2.6.2 which isn't a thing for windows from what I can see.

That's a good point. I tested against the most recent version (for Windows) which is what I assumed we were talking about. But indeed, that's 2.6.1, not 2.6.2.
