### ISSUE TITLE
Ubuntu 14.04 OpenShot 2.2 does not load

### ISSUE THREAD

**Issue by jarlarntzen** [OpenShot/openshot-qt#457]
Hi. I just uploaded from 2.1 to 2.2 and now it does not load at all. 
The terminal shows how far it gets. Any advice?

Thanks.

```
openshot-qt 
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
      launch:INFO ------------------------------------------------
      launch:INFO    OpenShot (version 2.2.0-dev)
      launch:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.2.0-dev
         app:INFO libopenshot version: 0.1.1
         app:INFO platform: Linux-3.13.0-92-generic-x86_64-with-Ubuntu-14.04-trusty
         app:INFO processor: x86_64
         app:INFO machine: x86_64
         app:INFO python version: 3.4.3
         app:INFO qt5 version: 5.2.1
         app:INFO pyqt5 version: 5.2.1
    language:INFO Attempting to load qt_nb_NO.UTF-8 in '/usr/share/qt5/translations'
    language:INFO Attempting to load qt_nb in '/usr/share/qt5/translations'
    language:INFO Attempting to load nb_NO.UTF-8/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Attempting to load nb/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Successfully loaded nb/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Qt Detected Languages: ['nb-NO', 'en-US', 'en']
    language:INFO LANG Environment Variable: nb_NO.UTF-8
    language:INFO LOCALE Environment Variable: nb_NO
    language:INFO Attempting to load qt_nb_NO.UTF-8 in '/usr/share/qt5/translations'
    language:INFO Attempting to load qt_nb in '/usr/share/qt5/translations'
    language:INFO Attempting to load qtbase_nb_NO.UTF-8 in '/usr/share/qt5/translations'
    language:INFO Attempting to load qtbase_nb in '/usr/share/qt5/translations'
    language:INFO Attempting to load qt_nb_NO.UTF-8 in '/usr/lib/python3/dist-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load qt_nb in '/usr/lib/python3/dist-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load qtbase_nb_NO.UTF-8 in '/usr/lib/python3/dist-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load qtbase_nb in '/usr/lib/python3/dist-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load nb_NO.UTF-8/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Attempting to load nb/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Successfully loaded nb/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Exiting translation system (since we successfully loaded: nb_NO.UTF-8)
project_data:INFO Setting default profile to HDV 720 24p
         app:INFO Setting font to /usr/lib/python3/dist-packages/openshot_qt/images/fonts/Ubuntu-R.ttf
         app:INFO Setting custom dark theme
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
link SVGID_18_-5 hasn't been detected!
link SVGID_18_-5 hasn't been detected!
link SVGID_22_-5 hasn't been detected!
link SVGID_24_-2 hasn't been detected!
link SVGID_24_-2 hasn't been detected!
     metrics:INFO Track metric: {'server': 'Golfe2', 'expires': 'Mon, 01 Jan 1990 00:00:00 GMT', 'x-content-type-options': 'nosniff', 'content-location': 'http://www.google-analytics.com/collect?an=OpenShot+Video+Editor&t=screenview&av=2.2.0-dev&cd=main-screen&cd1=0.1.1&v=1&aip=1&ul=nb-no&aid=org.openshot.openshot-qt&cd3=5.2.1&ua=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&tid=UA-4381101-5&cid=9adb873b-ca12-4ac5-b137-6c91ebe7815c&cd5=Ubuntu-14.04-trusty&cd2=3.4.3&cd4=5.2.1', 'age': '271274', 'status': '200', 'content-type': 'image/gif', 'pragma': 'no-cache', 'access-control-allow-origin': '*', 'last-modified': 'Sun, 17 May 1998 03:00:00 GMT', 'cache-control': 'no-cache, no-store, must-revalidate', 'date': 'Tue, 27 Dec 2016 21:20:58 GMT', 'content-length': '35'} (b'GIF89a\x01\x00\x01\x00\x80\xff\x00\xff\xff\xff\x00\x00\x00,\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x02D\x01\x00;')
     metrics:INFO Track metric: {'server': 'Golfe2', 'expires': 'Mon, 01 Jan 1990 00:00:00 GMT', 'x-content-type-options': 'nosniff', 'content-location': 'http://www.google-analytics.com/collect?an=OpenShot+Video+Editor&t=screenview&av=2.2.0-dev&cd=launch-app&cd1=0.1.1&v=1&aip=1&ul=nb-no&aid=org.openshot.openshot-qt&cd3=5.2.1&ua=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&tid=UA-4381101-5&cid=9adb873b-ca12-4ac5-b137-6c91ebe7815c&sc=start&cd5=Ubuntu-14.04-trusty&cd2=3.4.3&cd4=5.2.1', 'age': '271274', 'status': '200', 'content-type': 'image/gif', 'pragma': 'no-cache', 'access-control-allow-origin': '*', 'last-modified': 'Sun, 17 May 1998 03:00:00 GMT', 'cache-control': 'no-cache, no-store, must-revalidate', 'date': 'Tue, 27 Dec 2016 21:20:58 GMT', 'content-length': '35'} (b'GIF89a\x01\x00\x01\x00\x80\xff\x00\xff\xff\xff\x00\x00\x00,\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x02D\x01\x00;')
     ui_util:INFO Initializing UI for MainWindow
     ui_util:INFO Binding event MainWindow:actionNew_trigger
     ui_util:INFO Binding event MainWindow:actionOpen_trigger
     ui_util:INFO Binding event MainWindow:actionSave_trigger
     ui_util:INFO Binding event MainWindow:actionUndo_trigger
     ui_util:INFO Binding event MainWindow:actionSaveAs_trigger
     ui_util:INFO Binding event MainWindow:actionImportFiles_trigger
     ui_util:INFO Binding event MainWindow:actionImportImageSequence_trigger
     ui_util:INFO Binding event MainWindow:actionRedo_trigger
     ui_util:INFO Binding event MainWindow:actionRemoveClip_trigger
     ui_util:INFO Binding event MainWindow:actionRemoveTransition_trigger
     ui_util:INFO Binding event MainWindow:actionExportVideo_trigger
     ui_util:INFO Binding event MainWindow:actionUploadVideo_trigger
     ui_util:INFO Binding event MainWindow:actionAddTrack_trigger
     ui_util:INFO Binding event MainWindow:actionPreferences_trigger
     ui_util:INFO Binding event MainWindow:actionPlay_trigger
     ui_util:INFO Binding event MainWindow:actionJumpStart_trigger
     ui_util:INFO Binding event MainWindow:actionRewind_trigger
     ui_util:INFO Binding event MainWindow:actionFastForward_trigger
     ui_util:INFO Binding event MainWindow:actionJumpEnd_trigger
     ui_util:INFO Binding event MainWindow:actionArrowTool_trigger
     ui_util:INFO Binding event MainWindow:actionSnappingTool_trigger
     ui_util:INFO Binding event MainWindow:actionAddMarker_trigger
     ui_util:INFO Binding event MainWindow:actionPreviousMarker_trigger
     ui_util:INFO Binding event MainWindow:actionNextMarker_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowAll_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowVideo_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowAudio_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowImage_trigger
     ui_util:INFO Binding event MainWindow:actionTransitionsShowAll_trigger
     ui_util:INFO Binding event MainWindow:actionTransitionsShowCommon_trigger
     ui_util:INFO Binding event MainWindow:actionEffectsShowAll_trigger
     ui_util:INFO Binding event MainWindow:actionEffectsShowVideo_trigger
     ui_util:INFO Binding event MainWindow:actionEffectsShowAudio_trigger
     ui_util:INFO Binding event MainWindow:actionTimelineZoomIn_trigger
     ui_util:INFO Binding event MainWindow:actionTimelineZoomOut_trigger
     ui_util:INFO Binding event MainWindow:actionTitle_trigger
     ui_util:INFO Binding event MainWindow:actionAnimatedTitle_trigger
     ui_util:INFO Binding event MainWindow:actionFullscreen_trigger
     ui_util:INFO Binding event MainWindow:actionAbout_trigger
     ui_util:INFO Binding event MainWindow:actionThumbnailView_trigger
     ui_util:WARNING Icon theme view-preview not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionDetailsView_trigger
     ui_util:WARNING Icon theme view-list-details not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionReportBug_trigger
     ui_util:INFO Binding event MainWindow:actionAskQuestion_trigger
     ui_util:INFO Binding event MainWindow:actionTranslate_trigger
     ui_util:INFO Binding event MainWindow:actionDonate_trigger
     ui_util:INFO Binding event MainWindow:actionHelpContents_trigger
     ui_util:INFO Binding event MainWindow:actionSimple_View_trigger
     ui_util:INFO Binding event MainWindow:actionAdvanced_View_trigger
     ui_util:WARNING Icon theme get-hot-new-stuff not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionFreeze_View_trigger
     ui_util:INFO Binding event MainWindow:actionUn_Freeze_View_trigger
     ui_util:INFO Binding event MainWindow:actionShow_All_trigger
     ui_util:INFO Binding event MainWindow:actionProfile_trigger
     ui_util:INFO Binding event MainWindow:actionAdd_to_Timeline_trigger
     ui_util:INFO Binding event MainWindow:actionPreview_File_trigger
     ui_util:INFO Binding event MainWindow:actionRemove_from_Project_trigger
     ui_util:INFO Binding event MainWindow:actionFile_Properties_trigger
     ui_util:INFO Binding event MainWindow:actionRemoveTrack_trigger
     ui_util:INFO Binding event MainWindow:actionRemoveMarker_trigger
     ui_util:INFO Binding event MainWindow:actionAddTrackAbove_trigger
     ui_util:INFO Binding event MainWindow:actionAddTrackBelow_trigger
     ui_util:INFO Binding event MainWindow:actionRemoveEffect_trigger
     ui_util:INFO Binding event MainWindow:actionSplitClip_trigger
     ui_util:INFO Binding event MainWindow:actionProperties_trigger
     ui_util:INFO Binding event MainWindow:actionRenameTrack_trigger
     ui_util:INFO Binding event MainWindow:actionUpdate_trigger
     ui_util:INFO Binding event MainWindow:actionTutorial_trigger
     ui_util:INFO Binding event MainWindow:actionAnimation_trigger
     ui_util:INFO Binding event MainWindow:actionLockTrack_trigger
     ui_util:INFO Binding event MainWindow:actionUnlockTrack_trigger
 files_model:INFO updating files model.
transition_model:INFO updating transitions model.
timeline_webview:INFO Qt Found!
timeline_webview:INFO $scope.Qt = true;
timeline_webview:INFO UpdateLayerIndex
effects_model:INFO updating effects model.
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
properties_model:INFO updating clip properties model.
 main_window:INFO InitCacheSettings
 main_window:INFO cache-mode: CacheMemory
 main_window:INFO cache-limit-mb: 250
 main_window:INFO Creating CacheMemory object with 262144000 byte limit
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "/usr/bin/openshot-qt", line 9, in <module>
    load_entry_point('openshot-qt==2.2.0-dev', 'gui_scripts', 'openshot-qt')()
  File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 70, in main
    app = OpenShotApp(sys.argv)
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 162, in __init__
    self.window = MainWindow(mode)
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/main_window.py", line 1968, in __init__
    self.InitCacheSettings()
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/main_window.py", line 1856, in InitCacheSettings
    new_cache_object = openshot.CacheMemory(cache_limit)
AttributeError: 'module' object has no attribute 'CacheMemory'
     version:INFO Found current version: {'server': 'Apache/2.2.22 (Ubuntu)', 'status': '200', 'content-type': 'application/json', 'content-location': 'http://www.openshot.org/version/json/', 'transfer-encoding': 'chunked', 'date': 'Sat, 31 Dec 2016 00:44:24 GMT'} (b'{"openshot_version": "2.2.0"}')
     metrics:INFO Track exception: {'server': 'Apache/2.2.22 (Ubuntu)', 'status': '200', '-content-encoding': 'gzip', 'content-type': 'text/html; charset=utf-8', 'vary': 'Accept-Encoding', 'date': 'Sat, 31 Dec 2016 00:44:25 GMT', 'content-length': '29'} (b'*duplicate-exception-ignored*')
```

`

**Comment by jabi27** [comment]
I see the same issue on ubuntu 16.10
-----------------
openshot-qt
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
      launch:INFO ------------------------------------------------
      launch:INFO    OpenShot (version 2.2.0)
      launch:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.2.0
         app:INFO libopenshot version: 0.1.2
         app:INFO platform: Linux-4.8.0-34-generic-x86_64-with-Ubuntu-16.10-yakkety
         app:INFO processor: x86_64
         app:INFO machine: x86_64
         app:INFO python version: 3.5.2+
         app:INFO qt5 version: 5.6.1
         app:INFO pyqt5 version: 5.7
    language:INFO Attempting to load qt_da_DK.UTF-8 in '/usr/share/qt5/translations'
    language:INFO Successfully loaded qt_da_DK.UTF-8 in '/usr/share/qt5/translations'
    language:INFO Attempting to load da_DK.UTF-8/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Attempting to load da/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Successfully loaded da/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Qt Detected Languages: ['da', 'en']
    language:INFO LANG Environment Variable: da_DK.UTF-8
    language:INFO LOCALE Environment Variable: da_DK
    language:INFO Attempting to load qt_da in '/usr/share/qt5/translations'
    language:INFO Successfully loaded qt_da in '/usr/share/qt5/translations'
    language:INFO Attempting to load qtbase_da in '/usr/share/qt5/translations'
    language:INFO Attempting to load qt_da in '/usr/lib/python3/dist-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load qtbase_da in '/usr/lib/python3/dist-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load da/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Successfully loaded da/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Exiting translation system (since we successfully loaded: da)
project_data:INFO Setting default profile to HDV 1080 25p 1920x1080
ZmqLogger::Connection - Error binding to tcp://*:5556. Switching to an available port.
ZmqLogger::Connection - Error binding to tcp://*:5556. Switching to an available port.
         app:INFO Setting font to /usr/lib/python3/dist-packages/openshot_qt/images/fonts/Ubuntu-R.ttf
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
         app:INFO Setting custom dark theme
link SVGID_18_-5 hasn't been detected!
link SVGID_18_-5 hasn't been detected!
link SVGID_22_-5 hasn't been detected!
link SVGID_24_-2 hasn't been detected!
link SVGID_24_-2 hasn't been detected!
     ui_util:INFO Initializing UI for MainWindow
     ui_util:INFO Binding event MainWindow:actionNew_trigger
     metrics:INFO Track metric: {'status': '200', 'server': 'Golfe2', 'expires': 'Mon, 01 Jan 1990 00:00:00 GMT', 'content-type': 'image/gif', 'pragma': 'no-cache', 'content-location': 'http://www.google-analytics.com/collect?cd3=5.6.1&aip=1&cd5=Ubuntu-16.10-yakkety&cid=459c6232-c648-4995-bec1-4979e507b835&ua=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&tid=UA-4381101-5&av=2.2.0&cd4=5.7&an=OpenShot+Video+Editor&cd2=3.5.2%2B&sc=start&ul=da-dk&t=screenview&cd1=0.1.2&cd=launch-app&v=1&aid=org.openshot.openshot-qt', 'content-length': '35', 'age': '1285776', 'last-modified': 'Sun, 17 May 1998 03:00:00 GMT', 'x-content-type-options': 'nosniff', 'date': 'Tue, 27 Dec 2016 23:03:14 GMT', 'access-control-allow-origin': '*', 'cache-control': 'no-cache, no-store, must-revalidate'} (b'GIF89a\x01\x00\x01\x00\x80\xff\x00\xff\xff\xff\x00\x00\x00,\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x02D\x01\x00;')
     ui_util:INFO Binding event MainWindow:actionOpen_trigger
     ui_util:INFO Binding event MainWindow:actionSave_trigger
     ui_util:INFO Binding event MainWindow:actionUndo_trigger
     metrics:INFO Track metric: {'status': '200', 'server': 'Golfe2', 'expires': 'Mon, 01 Jan 1990 00:00:00 GMT', 'content-type': 'image/gif', 'pragma': 'no-cache', 'content-location': 'http://www.google-analytics.com/collect?cd3=5.6.1&aip=1&cd5=Ubuntu-16.10-yakkety&cid=459c6232-c648-4995-bec1-4979e507b835&ua=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&tid=UA-4381101-5&av=2.2.0&cd4=5.7&an=OpenShot+Video+Editor&cd2=3.5.2%2B&ul=da-dk&t=screenview&cd1=0.1.2&cd=main-screen&v=1&aid=org.openshot.openshot-qt', 'content-length': '35', 'age': '1285776', 'last-modified': 'Sun, 17 May 1998 03:00:00 GMT', 'x-content-type-options': 'nosniff', 'date': 'Tue, 27 Dec 2016 23:03:14 GMT', 'access-control-allow-origin': '*', 'cache-control': 'no-cache, no-store, must-revalidate'} (b'GIF89a\x01\x00\x01\x00\x80\xff\x00\xff\xff\xff\x00\x00\x00,\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x02D\x01\x00;')
     ui_util:INFO Binding event MainWindow:actionSaveAs_trigger
     ui_util:INFO Binding event MainWindow:actionImportFiles_trigger
     ui_util:INFO Binding event MainWindow:actionImportImageSequence_trigger
     ui_util:INFO Binding event MainWindow:actionRedo_trigger
     ui_util:INFO Binding event MainWindow:actionRemoveClip_trigger
     ui_util:INFO Binding event MainWindow:actionRemoveTransition_trigger
     ui_util:INFO Binding event MainWindow:actionExportVideo_trigger
     ui_util:INFO Binding event MainWindow:actionUploadVideo_trigger
     ui_util:INFO Binding event MainWindow:actionAddTrack_trigger
     ui_util:INFO Binding event MainWindow:actionPreferences_trigger
     ui_util:INFO Binding event MainWindow:actionPlay_trigger
     ui_util:INFO Binding event MainWindow:actionJumpStart_trigger
     ui_util:INFO Binding event MainWindow:actionRewind_trigger
     ui_util:INFO Binding event MainWindow:actionFastForward_trigger
     ui_util:INFO Binding event MainWindow:actionJumpEnd_trigger
     ui_util:INFO Binding event MainWindow:actionArrowTool_trigger
     ui_util:INFO Binding event MainWindow:actionSnappingTool_trigger
     ui_util:INFO Binding event MainWindow:actionAddMarker_trigger
     ui_util:INFO Binding event MainWindow:actionPreviousMarker_trigger
     ui_util:INFO Binding event MainWindow:actionNextMarker_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowAll_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowVideo_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowAudio_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowImage_trigger
     ui_util:INFO Binding event MainWindow:actionTransitionsShowAll_trigger
     ui_util:INFO Binding event MainWindow:actionTransitionsShowCommon_trigger
     ui_util:INFO Binding event MainWindow:actionEffectsShowAll_trigger
     ui_util:INFO Binding event MainWindow:actionEffectsShowVideo_trigger
     ui_util:INFO Binding event MainWindow:actionEffectsShowAudio_trigger
     ui_util:INFO Binding event MainWindow:actionTimelineZoomIn_trigger
     ui_util:INFO Binding event MainWindow:actionTimelineZoomOut_trigger
     ui_util:INFO Binding event MainWindow:actionTitle_trigger
     ui_util:INFO Binding event MainWindow:actionAnimatedTitle_trigger
     ui_util:INFO Binding event MainWindow:actionFullscreen_trigger
     ui_util:INFO Binding event MainWindow:actionAbout_trigger
     ui_util:INFO Binding event MainWindow:actionThumbnailView_trigger
     ui_util:INFO Binding event MainWindow:actionDetailsView_trigger
     ui_util:INFO Binding event MainWindow:actionReportBug_trigger
     ui_util:INFO Binding event MainWindow:actionAskQuestion_trigger
     ui_util:INFO Binding event MainWindow:actionTranslate_trigger
     ui_util:INFO Binding event MainWindow:actionDonate_trigger
     ui_util:INFO Binding event MainWindow:actionHelpContents_trigger
     ui_util:INFO Binding event MainWindow:actionSimple_View_trigger
     ui_util:INFO Binding event MainWindow:actionAdvanced_View_trigger
     ui_util:INFO Binding event MainWindow:actionFreeze_View_trigger
     ui_util:INFO Binding event MainWindow:actionUn_Freeze_View_trigger
     ui_util:INFO Binding event MainWindow:actionShow_All_trigger
     ui_util:INFO Binding event MainWindow:actionProfile_trigger
     ui_util:INFO Binding event MainWindow:actionAdd_to_Timeline_trigger
     ui_util:INFO Binding event MainWindow:actionPreview_File_trigger
     ui_util:INFO Binding event MainWindow:actionRemove_from_Project_trigger
     ui_util:INFO Binding event MainWindow:actionFile_Properties_trigger
     ui_util:INFO Binding event MainWindow:actionRemoveTrack_trigger
     ui_util:INFO Binding event MainWindow:actionRemoveMarker_trigger
     ui_util:INFO Binding event MainWindow:actionAddTrackAbove_trigger
     ui_util:INFO Binding event MainWindow:actionAddTrackBelow_trigger
     ui_util:INFO Binding event MainWindow:actionRemoveEffect_trigger
     ui_util:INFO Binding event MainWindow:actionSplitClip_trigger
     ui_util:INFO Binding event MainWindow:actionProperties_trigger
     ui_util:INFO Binding event MainWindow:actionRenameTrack_trigger
     ui_util:INFO Binding event MainWindow:actionUpdate_trigger
     ui_util:INFO Binding event MainWindow:actionTutorial_trigger
     ui_util:INFO Binding event MainWindow:actionAnimation_trigger
     ui_util:INFO Binding event MainWindow:actionLockTrack_trigger
     ui_util:INFO Binding event MainWindow:actionUnlockTrack_trigger
files_treeview:INFO currentChanged
 files_model:INFO updating files model.
transition_model:INFO updating transitions model.
timeline_webview:INFO Qt Found!
timeline_webview:INFO $scope.Qt = true;
timeline_webview:INFO UpdateLayerIndex
     version:INFO Found current version: {'status': '200', 'server': 'Apache/2.2.22 (Ubuntu)', 'transfer-encoding': 'chunked', 'date': 'Wed, 11 Jan 2017 20:15:39 GMT', 'content-type': 'application/json', 'content-location': 'http://www.openshot.org/version/json/'} (b'{"openshot_version": "2.2.0"}')
 main_window:INFO foundCurrentVersion: Found the latest version: 2.2.0
effects_model:INFO updating effects model.
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
properties_model:INFO updating clip properties model.
 main_window:INFO InitCacheSettings
 main_window:INFO cache-mode: CacheMemory
 main_window:INFO cache-limit-mb: 250
 main_window:INFO Creating CacheMemory object with 262144000 byte limit
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "/usr/bin/openshot-qt", line 11, in <module>
    load_entry_point('openshot-qt==2.2.0', 'gui_scripts', 'openshot-qt')()
  File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 70, in main
    app = OpenShotApp(sys.argv)
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 162, in __init__
    self.window = MainWindow(mode)
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/main_window.py", line 1967, in __init__
    self.InitCacheSettings()
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/main_window.py", line 1855, in InitCacheSettings
    new_cache_object = openshot.CacheMemory(cache_limit)
AttributeError: module 'openshot' has no attribute 'CacheMemory'
     metrics:INFO Track exception: {'server': 'Apache/2.2.22 (Ubuntu)', '-content-encoding': 'gzip', 'date': 'Wed, 11 Jan 2017 20:15:40 GMT', 'content-type': 'text/html; charset=utf-8', 'status': '200', 'vary': 'Accept-Encoding', 'content-length': '29'} (b'*duplicate-exception-ignored*')


-----------------
/Jan

**Comment by nschapiro** [comment]
I'm having the same problem as the OP

**Comment by legolas108** [comment]
Had the same problem. Solved it by removing/re-installing all openshot packages that were installed (using Synaptic Package Manager):

openshot-qt, python3-openshot, libopenshot-audio3, libopenshot9

Then re-installed everything (with latest version where available):

openshot-qt, python3-openshot, libopenshot-audio3, libopenshot10

Might be enough to just upgrade to libopenshot10. Now OpenShot 2.2.0 runs on kubuntu 14.04.5.
HTH
Ole

**Comment by haudren** [comment]
Thanks @legolas108 ! You just solved my issue :)

To be clear, I only ran
> apt-get remove libopenshot9

And I was prompted to install `libopenshot10`, and it fixed that problem!

**Comment by jreynojustin** [comment]
Glad to hear the community helped resolve this! Thanks @legolas108. Good work!
