### ISSUE TITLE
Images go black despite there being no effects or other transformations applied

### ISSUE THREAD

**Issue by MenooMeow** [OpenShot/openshot-qt#4574]
**Describe the bug:**
Images go dark despite there being no effects or other transformations applied.  It briefly goes dark for a fraction of a second, but comes back.  I've had this happen on various images in a large project now.  I can scroll the timeline to it and it's black in the editor and in the resultant video.  I can find no reason for that temporary black few frames.  

**Steps to reproduce the behavior:**
Create a complex project. 
Use 6 tracks
Add videos, images, and sound tracks (no video).

**Expected behavior:**
No black flashes

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 2.6.1-dev
- Operating System / Distro: Windows 10

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.
[openshot_qt.zip](https://github.com/OpenShot/openshot-qt/files/7663161/openshot_qt.zip)

**Exception / Stacktrace:**

**Screenshots:** (Optional)
![2021-12-06 13_44_18-intro video 1  HD 1080p 29 97 fps  - OpenShot Video Editor](https://user-images.githubusercontent.com/44622158/144911939-c794348c-63a7-4956-a0ef-b421f7adef11.png)

**Comment by JacksonRG** [comment]
Does the black frame appear at the start of the `dark ambient` clip, no matter where it is?

Also, to start with I'd click on each clip on the timeline, and make sure none have keyframes affecting `alpha` or `has-video` that you don't know about.
