### ISSUE TITLE
Aspect ratio is inaccurate for 16:9 video produced in 854x480

### ISSUE THREAD

**Issue by DanPinGF** [OpenShot/openshot-qt#4580]
**Describe the bug:**
This also appears to be a long-term issue, quite similar to #3915 (resolved since). For roughly all 854x480 video files, the aspect ratio on imported content appears purely incorrect on export.

**Steps to reproduce the behavior:**
1. Import an 854x480 video
2. Drag video to timeline
3. Export, in any profile
4. You should see some awkward pillar-boxing in the exported file, but it only appears on the right.

**Expected behavior:**
It aspect ratio SHOULD be correct for 854x480 video content, not pillar-boxed. The problem seems to only have been fixed in the Preview in 2.6.0, however. To workaround this, set 'Gravity' to 'Left' and adjust 'Scale X' to 1.01

**System Details:**
- OpenShot Version: 2.6.1
- Operating System / Distro: Windows 11

**Log Files:**
N/A

**Exception / Stacktrace:**
N/A

**Comment by JacksonRG** [comment]
Unusual video resolution. Mind providing a short example file? Also any pictures or examples of how the export looks "incorrect" may help us find what's going wrong.

**Comment by DanPinGF** [comment]
![image](https://user-images.githubusercontent.com/28827920/145303393-b0585609-66a4-4849-9bd0-46a649a5c092.png)
This is a screenshot I took on my desktop illustrating this behavior. You can clearly see the half-pillarboxing right here in the export, but not in the Preview.

**Comment by JacksonRG** [comment]
By half-pillarboxing, do you mean the black strip on the right side?

Edit: you probably do. I looked up [pillarboxing](https://en.wikipedia.org/wiki/Pillarbox)

**Comment by JacksonRG** [comment]
Hm, well if nothing else, we should balance it on both sides. And ideally just export so that there's no black strips.

**Comment by DanPinGF** [comment]
> By half-pillarboxing, do you mean the black strip on the right side?
> 
> Edit: you probably do. I looked up [pillarboxing](https://en.wikipedia.org/wiki/Pillarbox)

Why, of course. That's the alpha part of the clip, which isn't supposed to look that way.

**Comment by DanPinGF** [comment]
@JacksonRG - This issue still needs to be resolved... perhaps.

**Comment by DanPinGF** [comment]
@JacksonRG - We were not done! Please reopen this.
