### ISSUE TITLE
Openshot ne trouve pas mes fichiers et les transforme au format .png

### ISSUE THREAD

**Issue by radmilove** [OpenShot/openshot-qt#4581]
**Décrire le bogue**
Une fois un projet créé, si j'ouvre l'application Openshot après l'avoir fermée, elle ne trouve plus mes fichiers et les change au format .png

**Étapes pour reproduire ce comportement :**
1. Ouvrez l'application Openshot, ajoutez des fichiers video/audio (.mp4/.wav)
2. Enregistrez le projet sous le Bureau (nomdufichier.osp), puis fermez l'application
3. Ouvrez de nouveau l'application, que ce soit depuis le fichier créé ou en relançant l'application et en ouvrant le projet nomdufichier.osp
4. Visualisez l'erreur (apparition du message "fichiers manquants" : l'application ne trouve pas les fichiers)

**Comportement attendu**
Quand j'ouvre à nouveau un projet créé, mes fichiers sont bien enregistrés dans la bibliothèque, et je peux procéder au montage.

**Détails du système**
- OpenShot Version: 2.5.0
- libopenshot Version:  0.2.4
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['fr-FR', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Version Daily : Impossible de vérifier que le problème existe toujours dans la version Daily

**Fichiers journaux**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/o8rs2o9g30tqnggqc6tldn3pzdddh68c/openshot-qt.zip) (30 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/o8rs2o9g30tqnggqc6tldn3pzdddh68c/libopenshot.zip) (0 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Captures d’écran** (Facultatif)
Le cas échéant, ajoutez des captures d'écran pour expliquer votre problème. Vous pouvez inclure des captures d'écran par
copier/coller sur GitHub ou glisser-déposer dans la page GitHub. Toutes les images sont publiques,
alors veuillez ne pas publier de captures d'écran contenant des informations personnelles.

**Comment by JacksonRG** [comment]
Are your files on the same windows drive as you are editing from? We've had occasional issues with files on different drives.

Also, it looks like you're using an older version of openshot. I recommend checking out our latest version. This issue may have been fixed.

You can download here. If you have an issue in the current official (2.6.1), you can also try the daily builds.
https://www.openshot.org/download/

**Comment by radmilove** [comment]
Thanks for your reply!! I use the same Windows drive, but not the latest version. This is maybe the reason why I still have this issue.
Kind regards
