### ISSUE TITLE
GNOME/Nautilus: Icon too big

### ISSUE THREAD

**Issue by rugk** [OpenShot/openshot-qt#459]
When you go to `/usr/share/applications` in Nautilus you'll see that the icon of OpenShot is way too big in contrast to all other icons:

![iconwaytoobig](https://cloud.githubusercontent.com/assets/11966684/21587858/25dc633c-d0e1-11e6-8574-220380959c95.png)

openshot v1.4.3-1.1 from Debian repos

**Comment by rugk** [comment]
The worst thing is, that this even happens with `.osp` project files…

**Comment by jonoomph** [comment]
Agreed, that is weird (and obnoxiously large). =)  However, this issue is happening on our old version of OpenShot, which is no longer being worked on. We are focused on OpenShot 2.x now, and I'm pretty sure we have solved that problem in the 2.x branch.
