### ISSUE TITLE
Option to set Folder paths

### ISSUE THREAD

**Issue by Colorjet3** [OpenShot/openshot-qt#4590]
**Describe the new feature:**
The ability to set default paths for the following:  New Project/Open Project, Save Project, Import Files, Export Folder Path.  I had submitted this request via email long time ago and see no reference to it at this time.

**Describe the solution you'd like:**
1.  In Edit | Preference there would be a tab named "Folder Paths".

2.   In this tab there would be the following options to override:
a.  New Project/Open Project path:  (default to c:\users\username)
b.  Save Project:                               (default to c:\users\username)
c.  Import Files:                                (default to c:\users\username)
- Music:                                           (default to c:\users\username)
- Sound:                                          (default to c:\users\username)
- Images:                                          (default to c:\users\username)
- Videos:                                          (default to c:\users\username)
d.  Import Project:                           (default to c:\users\username)
e.  Export Project:
- Video:                       (default to c:\users\username)
- EDL:                          (default to c:\users\username)
- XM (Final Cut Pro):    (default to c:\users\username)
g.  Export Folder path:  (defaults to c:\users\username)

The default paths obviously would be different for the different operating systems.

OpenShot should continue to maintain certain folders paths settings as it does currently.

**Describe alternatives you have considered:**
Implement it in phases if needed but I don't see it couldn't be implemented all at once.

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your request.

**Comment by whismerhill** [comment]
I was literally looking for this.
I'm always under the assumption that the software will remember the last save path of the previous project
but alas this is not the case. (I only use OpenShot for quick projects which I don't even save, just export)

additionally "c:\users\username"
is actually horrible of a default path anyway for exports
I suggest  GUID {18989B1D-99B5-455B-841C-AB7C74E4DDFC} 
accessible through : `Knownfolder:{18989B1D-99B5-455B-841C-AB7C74E4DDFC}` (copy paste this in explorer to see what this looks like)
which defaults to %USERPROFILE%\Videos (but user may have changed it)

documentation : 
https://docs.microsoft.com/en-us/previous-versions//bb762584(v=vs.85)?redirectedfrom=MSDN
