### ISSUE TITLE
Caption Effect should have a "Line Spacing" property to control line spacing between multiple lines of text.

### ISSUE THREAD

**Issue by Colorjet3** [OpenShot/openshot-qt#4594]
**Describe the new feature:**
The Caption effect should have the property "Line Spacing" where we can change the value to control the spacing between multiple lines of text.

**Describe the solution you'd like:**
In the Properties window of the Caption Effect, add a new property named "Line Spacing".  The Values can be .25, .5, 1, 1.5, 2.  The value 1 could be the default (as it is right now) and the other values shrink or expand the spacing.  This should be independent of the Font Size.

**Describe alternatives you have considered:**

No other alternative considered.

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your request.

**Comment by JacksonRG** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Change line spacing of captions](https://trello.com/c/WIYHEvyK/145-change-line-spacing-of-captions)

**Comment by Colorjet3** [comment]
This has been fixed in v3.0.0 - https://trello.com/c/WIYHEvyK/145-caption-improvements-line-spacing-background-color-centering
