### ISSUE TITLE
crash after import of .mov file

### ISSUE THREAD

**Issue by selbstlesebuch** [OpenShot/openshot-qt#4595]
openshot gives a crash after import of .mov file

**Steps to reproduce the behavior:**
1. open openshot new projekt
2. have a .mov file (from mobile?)
3. drag it into Openshot
4. crash

**Expected behavior**
Import of the file

**System Details**
- OpenShot Version: 2.6.1-dev
- libopenshot Version:  0.2.7-dev
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 165 Stepping 3, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['de-DE', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-dev-daily-8906-3c8dc71b-2b8b05c7-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/hkw07xony7mb2tv27x9sytccnb23nk0m/openshot-qt.zip) (5 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/hkw07xony7mb2tv27x9sytccnb23nk0m/libopenshot.zip) (2 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)

**Comment by selbstlesebuch** [comment]
And I tried this: I converted the -mov file into MP4, mpeg, mpg, avi, Always a crash. I used diffent converter
convertio, Adobe, online-umwandlen.de
Always the same. Is it a problem with the codec?

**Comment by LexiconCode** [comment]
**Describe the bug**
I dragged and dropped `IMG_8558 play mat.MOV` in into project files and then the program crashed exiting without error message

**Edit**: similar to https://github.com/OpenShot/openshot-qt/issues/4476

**Steps to reproduce the behavior:**
1. drag into  `IMG_8558 play mat.MOV` project file
2. openshot crashed exiting without error message

**System Details**
- OpenShot Version: 2.6.1-dev
- libopenshot Version:  0.2.7-dev
- Platform: Windows-11-10.0.22523
- Processor: AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-dev-daily-8946-3c8dc71b-2b8b05c7-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/vymho3itmnz8c5vc6rn9minsnl6z6enn/openshot-qt.zip) (127 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/vymho3itmnz8c5vc6rn9minsnl6z6enn/libopenshot.zip) (235 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

Other .MOV files seem to work just fine. The file `IMG_8558 play mat.MOV` plays back in other programs.

**Comment by selbstlesebuch** [comment]
I just got the same error with the latest daily and a .mp4 file.


[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/8031294/openshot-qt.log)
with that video and other
https://user-images.githubusercontent.com/96125689/153165705-97897166-3347-48da-9a07-422f3345d2f6.mp4

.
