### ISSUE TITLE
Application will not start

### ISSUE THREAD

**Issue by DaveRogala** [OpenShot/openshot-qt#4598]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**
1. Open Launchpad
2. Click on the Openshot icon
3. Observe that the Openshot icon displays in the tray
4. Observe that the Openshot icon disappears from the tray

**Expected behavior**
The application actually starts

**System Details**
- OpenShot Version: 2.6.1
- libopenshot Version:  0.2.7
- Platform: Darwin-21.1.0-x86_64-i386-64bit
- Processor: i386
- Machine: x86_64
- Python version: 3.7.11
- Qt5 version: 5.15.0
- PyQt5 version: 5.15.1.dev2007111314
- Qt Detected Languages: 
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-dev-daily-8930-3c8dc71b-2b8b05c7-x86_64.dmg

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/qkfuvknbiy5q1qy1l681dv555ii1h8of/openshot-qt.zip) (10 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by JacksonRG** [comment]
Hi, sorry we missed this issue. I'd recommend updating your python version, and trying with our most recent daily build. If that doesn't work, could you try running by command with the `--debug` flag?
