### ISSUE TITLE
German text in the Keyboard settings is too long

### ISSUE THREAD

**Issue by NeoTheThird** [OpenShot/openshot-qt#460]
OS: Ubuntu 16.10
OpenShot Version: 2.2 (installed from `ppa:openshot.developers/ppa`)
If i activate the german translations and go to Keyboard settings, some words are too long which causes some weird line wrapping.

I don't seem to be able to upload images to GitHub, so i uploaded a screenshot here: http://imgur.com/gallery/Loyg1

**Comment by DylanC** [comment]
@NeoTheThird - Does this issue exist in OpenShot v2.3.4? Please confirm.

**Comment by NeoTheThird** [comment]
Yep, it's also there in the english version: 
![os-bug](https://user-images.githubusercontent.com/12068939/29681311-98d336fc-8907-11e7-92e0-2b07e35cd6e0.png)

Of course it's not a severe issue that keeps you from using it, but for the sake of polish it might make sense to adjust the beginning of the text fields a little so they align more nicely.

**Comment by DylanC** [comment]
@NeoTheThird - Thanks for the feedback. We will take this on board for future versions.

**Comment by NeoTheThird** [comment]
Sure thing :) Keep up the good work and thanks

**Comment by DylanC** [comment]
@NeoTheThird - No problem. Happy to help! :)
