### ISSUE TITLE
Missing advertised IRC link

### ISSUE THREAD

**Issue by JLuc** [OpenShot/openshot-qt#4600]
On openshot.org website, the ["About" page](https://www.openshot.org/en/about/) mentions irc as one of the "ways to contact the OpenShot team" but the linked ["Contact Us" page](https://www.openshot.org/en/contact/) doesnt provide any way about that irc chan.

When there is such an irc chan, it should be stated on the "Contact us" page.
When there is none, it should not be mentioned in the "About us" page.
See screenshot :
![2022 12 21 about page](https://user-images.githubusercontent.com/443278/208849957-9bfaab48-2139-445f-a803-3b0ef0a35429.png)

**Comment by JLuc** [comment]
The issue is still there. 
No link to the said irc chan.

**Comment by JLuc** [comment]
Oups reopen because the issue is still there.
No link to the said irc chan.

**Comment by JacksonRG** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [IRC on "About Us" Page](https://trello.com/c/KTdWsQBS/141-irc-on-about-us-page)

**Comment by JLuc** [comment]
When there is an irc channel, where is it ?

**Comment by Colorjet3** [comment]
Hello @JLuc Where exactly are you seeing the mention of IRC?  Please tell me click-by-click.

thank you!

**Comment by JLuc** [comment]
It's easy to find : it's in the last paragraph = "Contact Us" of the "about page", where one is wellcomed on the IRC chan. Click  https://www.openshot.org/en/about , scroll down and see for yourself. A couple of hours ago, i uploaded a screenshot in the original ticket. With it you can also see how it looks like before opening this page...
Since the about page is translated in various langages, that mention appears also in the "Nous contacter" paragraph of the french version : https://www.openshot.org/fr/about/ 
And in the "Kontaktieren Sie uns" paragraph of the  https://www.openshot.org/fr/about/  ... where it was translated into "IRV"
I didnt look further langages.
When there is an irc, please mention it in the contact pages (https://www.openshot.org/en/contact/ etc)

**Comment by Colorjet3** [comment]
Thank you @JLuc I see it now.  I will submit a request to fix it either way (either remove it or provide information on how to use it).

**Comment by Colorjet3** [comment]
https://trello.com/c/CUJYAKMZ/65-missing-advertised-irc-link

**Comment by Colorjet3** [comment]
This is in the queue for review and resolution.

**Comment by JLuc** [comment]
Thanks  !
