### ISSUE TITLE
Error at program start

### ISSUE THREAD

**Issue by dacorsa** [OpenShot/openshot-qt#4601]
With Ubuntu studio Hirsute i have this error at start:

$ openshot-qt 
Loaded modules from: /usr/lib/python3/dist-packages/openshot_qt
INFO app: ------------------------------------------------
INFO app:             Thu Dec 16 21:44:49 2021            
INFO app:               Starting new session              
ERROR app: OpenShotApp::Import Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 95, in __init__
    from classes import settings, project_data, updates, sentry
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/project_data.py", line 48, in <module>
    import openshot
  File "/usr/local/lib/python3.9/dist-packages/openshot.py", line 15, in <module>
    import _openshot
ImportError: /usr/local/lib/python3.9/dist-packages/_openshot.so: undefined symbol: _ZN8openshot5Frame14AddMagickImageESt10shared_ptrIN6Magick5ImageEE
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 189, in main
    app = OpenShotApp(argv)
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 95, in __init__
    from classes import settings, project_data, updates, sentry
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/project_data.py", line 48, in <module>
    import openshot
  File "/usr/local/lib/python3.9/dist-packages/openshot.py", line 15, in <module>
    import _openshot
ImportError: /usr/local/lib/python3.9/dist-packages/_openshot.so: undefined symbol: _ZN8openshot5Frame14AddMagickImageESt10shared_ptrIN6Magick5ImageEE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/openshot-qt", line 33, in <module>
    sys.exit(load_entry_point('openshot-qt==2.6.1.dev0', 'gui_scripts', 'openshot-qt')())
  File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 191, in main
    app.show_errors()
AttributeError: 'NoneType' object has no attribute 'show_errors'
INFO app:             OpenShot's session ended            
INFO app:             Thu Dec 16 21:44:49 2021            
INFO app: ================================================
Sentry is attempting to send 1 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit

Also launching in this way:

$ python3 /app/openshot-qt/src/launch.py
Loaded modules from: /app/openshot-qt/src
INFO app: ------------------------------------------------
INFO app:             Thu Dec 16 22:22:21 2021            
INFO app:               Starting new session              
ERROR app: OpenShotApp::Import Error
Traceback (most recent call last):
  File "/app/openshot-qt/src/classes/app.py", line 99, in __init__
    from classes import settings, project_data, updates
  File "/app/openshot-qt/src/classes/project_data.py", line 48, in <module>
    import openshot
  File "/usr/local/lib/python3.9/dist-packages/openshot.py", line 15, in <module>
    import _openshot
ImportError: /usr/local/lib/python3.9/dist-packages/_openshot.so: undefined symbol: _ZN8openshot5Frame14AddMagickImageESt10shared_ptrIN6Magick5ImageEE
Traceback (most recent call last):
  File "/app/openshot-qt/src/launch.py", line 185, in main
    app = OpenShotApp(argv)
  File "/app/openshot-qt/src/classes/app.py", line 99, in __init__
    from classes import settings, project_data, updates
  File "/app/openshot-qt/src/classes/project_data.py", line 48, in <module>
    import openshot
  File "/usr/local/lib/python3.9/dist-packages/openshot.py", line 15, in <module>
    import _openshot
ImportError: /usr/local/lib/python3.9/dist-packages/_openshot.so: undefined symbol: _ZN8openshot5Frame14AddMagickImageESt10shared_ptrIN6Magick5ImageEE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/openshot-qt/src/launch.py", line 212, in <module>
    main()
  File "/app/openshot-qt/src/launch.py", line 187, in main
    app.show_errors()
AttributeError: 'NoneType' object has no attribute 'show_errors'
INFO app:             OpenShot's session ended            
INFO app:             Thu Dec 16 22:22:21 2021            
INFO app: ================================================
Sentry is attempting to send 1 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit

What happened? How can i solve it?

Thanks

**Comment by JacksonRG** [comment]
Hi, sorry we missed this issue. Could you try running with the `--debug` flag in your command, and then attach the log files from the folder  `~/.openshot_qt/`. You can drag the files into a github comment so we can view them a little easier

**Comment by dacorsa** [comment]
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/10275195/openshot-qt.log)

this is my new log and my new error:

07:41:51 dacorsa@NanoKDE /home/dacorsa $ openshot-qt --debug
Loaded modules from: /usr/lib/python3/dist-packages/openshot_qt
INFO app: ------------------------------------------------
INFO app:             Wed Dec 21 07:42:55 2022            
INFO app:               Starting new session              
DEBUG app: Command line: ['/usr/bin/openshot-qt']
INFO app: ------------------------------------------------
INFO app:             OpenShot (version 3.0.0)            
INFO app: ------------------------------------------------
INFO app: openshot-qt version: 3.0.0
INFO app: libopenshot version: 0.3.0
INFO app: platform: Linux-5.19.0-1012-lowlatency-x86_64-with-glibc2.36
INFO app: processor: x86_64
INFO app: machine: x86_64
INFO app: python version: 3.10.8
INFO app: qt5 version: 5.15.6
INFO app: pyqt5 version: 5.15.7
INFO project_data: Setting default profile to HD 720p 30 fps
INFO project_data: Apply default audio playback settings: 44100, 2 channels
INFO app: checking babl_ext_path: /usr/lib/python3/dist-packages/openshot_qt/lib/babl-ext
Screen DisplayPort-0
   devicePixelRatio: 1.0
   logicalDotsPerInch: 108.0
   physicalDotsPerInch: 163.33129935391244
   availableSizes: PyQt5.QtCore.QSize(3840, 2096)
DEBUG language: Using compiled translation resources
INFO language: Qt Detected Languages: ['it', 'it-IT', 'it-Latn-IT']
INFO language: LANG Environment Variable: it_IT.UTF-8
INFO language: LOCALE Environment Variable: 
INFO language: OpenShot Preference Language: Default
DEBUG language: Attempting to load qt_it_IT.UTF-8 in '/usr/share/qt5/translations'
DEBUG language: Successfully loaded qt_it_IT.UTF-8 in '/usr/share/qt5/translations'
DEBUG language: Attempting to load qtbase_it_IT.UTF-8 in '/usr/share/qt5/translations'
DEBUG language: Successfully loaded qtbase_it_IT.UTF-8 in '/usr/share/qt5/translations'
DEBUG language: Attempting to load qt_it_IT.UTF-8 in '/usr/lib/python3/dist-packages/openshot_qt/language'
DEBUG language: Attempting to load qtbase_it_IT.UTF-8 in '/usr/lib/python3/dist-packages/openshot_qt/language'
DEBUG language: Attempting to load OpenShot_it_IT.UTF-8 in ':/locale/'
DEBUG language: Successfully loaded OpenShot_it_IT.UTF-8 in ':/locale/'
DEBUG language: Exiting translation system (since we successfully loaded: it_IT.UTF-8)
DEBUG app: Testing write access to user directory
DEBUG app: Loading UI theme
INFO app: Setting font to /usr/lib/python3/dist-packages/openshot_qt/images/fonts/Ubuntu-R.ttf
INFO app: Setting custom dark theme
/home/dacorsa/.local/lib/python3.10/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.8) or chardet (5.0.0)/charset_normalizer (2.0.10) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/usr/bin/openshot-qt", line 33, in <module>
    sys.exit(load_entry_point('openshot-qt==3.0.0', 'gui_scripts', 'openshot-qt')())
  File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 218, in main
    app.gui()
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 271, in gui
    from windows.main_window import MainWindow
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/main_window.py", line 77, in <module>
    from windows.views.webview import TimelineWebView
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/views/webview.py", line 162, in <module>
    from .webview_backend.webengine import TimelineWebEngineView as WebViewClass
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/views/webview_backend/webengine.py", line 38, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView, QWebEnginePage
RuntimeError: PyQt5.QtWebEngineWidgets cannot import type '����' from PyQt5.QtCore
INFO app:             OpenShot's session ended            
INFO app:             Wed Dec 21 07:42:55 2022            
INFO app: ================================================

**Comment by Colorjet3** [comment]
Please download the latest DEV Daily Build from openshot.org/download/#daily and see if that takes care of the issue.  If it crashes, please share your log file again.
