### ISSUE TITLE
Move clip with keyboard

### ISSUE THREAD

**Issue by cephas5776** [OpenShot/openshot-qt#4604]
**Describe the new feature:**
Hi, is there a way to move clip left/right by using a keyboard? This is the exact issue submitted bak in 2011 but haven't seen any updates since.  Thank you =D

I will copy & paste the issue here

"Currently I can only use the mouse to move clips around on the timeline.

Sometimes I need to move clips one or two frames to the left/right. At other times, I need to move it to another track without moving it within the time.

With the mouse, this is impossible. It'd be helpful if I could use the keyboard to move the clips."

[https://bugs.launchpad.net/openshot/+bug/890883](https://bugs.launchpad.net/openshot/+bug/890883)

**Describe the solution you'd like:**
Able to select a clip and move it frame by frame with keyboard (instead of the mouse)

**Describe alternatives you have considered:**
I tied moving the clip

**Screenshots:** (Optional)
n/a

**Comment by Colorjet3** [comment]
Select the clip and then use the combination of Shift+Left or Shift+Right.  If you go to Edit | Preference and click on Keyboard tab you will see all of the keyboard shortcuts.  This also works if you selected multiple clips at once.

**Comment by JacksonRG** [comment]
Thanks to @Colorjet3 for the quick answer. Closing this issue. @cephas5776 you can reopen if this didn't solve your issue.
