### ISSUE TITLE
Display "File Path:" in the "Project Files" window when in "Detail View"

### ISSUE THREAD

**Issue by Colorjet3** [OpenShot/openshot-qt#4605]
**Describe the new feature:**
I often find myself looking for the folder path for a clip when working with existing projects as I can have imported content from different locations.  To find the folder path I need to right click on an imported clip and then select "File Properties".   It would be nice to display the "File Path" when I choose "Details View".  Currently the program displays the Thumbnail, Name, and Tags (not sure how Tags are used).  Make the columns adjustable so we can deal with long "File Path" names as well.

**Describe the solution you'd like:**
Two solutions and may be both can be implemented.

**Solution 1**

When I choose "Details View", the view will include the Thumbnail, Name, **File Path**, and Tags columns.  File path will display the absolute path (i.e., c:\images\image01.jpg).

The "File Path" column should also be adjustable so you can expand it to display long folder path names(May be 128 characters if there are limitations).

**Solution 2**
In "Thumbnail View", when you hover over a clip it currently displays the name of the clip.   You can add another line below it to include the "Folder Path" and/or display the absolute path+name.

**Solution 3**
Implement both Solution 1 & 2

This feature Should Not replace the existing "File Path:" field when you right click on a clip and select "File Properties:".

**Describe alternatives you have considered:**
Not so much alternatives but additional functionality where the "Folder Path" itself is clickable which opens the "File Explorer

** Screen Shot
[Screenshot 2021-12-18 150107-New1.zip](https://github.com/OpenShot/openshot-qt/files/7740015/Screenshot.2021-12-18.150107-New1.zip)

**Comment by JacksonRG** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Show Path in Files Details View](https://trello.com/c/BFjFmds8/142-show-path-in-files-details-view)
