### ISSUE TITLE
Enable Hardware Acceleration in Windows, Linux, Mac environments

### ISSUE THREAD

**Issue by Colorjet3** [OpenShot/openshot-qt#4606]
**Describe the new feature:**
In Edit | Preferences, at least in Windows, when you click on Edit | Preferences and select the Performance tab you will see the following options:
Hardware Decoder Mode (Default value = CPU No acceleration)
Hardware Decoder Graphics Card (Default value = CPU No acceleration)
Hardware Encoder Graphics Card (Default value = CPU No acceleration)

None of these options are enabled or seem to be configurable/functional.

**Describe the solution you'd like:**
Activate these features in an effort to enhance the performance of OpenShot.

**Describe alternatives you have considered:**
I suppose buying a higher end computer and/or upgrading an existing one might provide some relief of performance issues.  However, that is not always affordable and many of us already have more than capable hardware and would like to see OpenShot take advantage of that.

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your request.

**Comment by ginger-tek** [comment]
Idk if this is an "improvement" as much as it's a missing feature. The dropdown in the settings has been asked about for over 2 years now, and there have been no updates on the status of hardware acceleration for Windows :/

**Comment by Colorjet3** [comment]
There is some traction on this and hopefully a near future release (Daily Build) will have this missing feature enabled in Windows.  Stay tuned...
