### ISSUE TITLE
Application Settings issue

### ISSUE THREAD

**Issue by ghost** [OpenShot/openshot-qt#4607]
**Question:**
Why Openshot not store settings in Appdata / Roaming, but inside User folder, not even hidden? What stays behind that behaviour many applications do that and make mess in that folder ?

**System Details:**
Windows 8.1

**Screenshot**
https://i.imgur.com/hhHBNMa.jpg

**Comment by JacksonRG** [comment]
Hi, I believe this folder is hidden, unless you have hidden files set to display.

I brought up this improvement with our team, but it would cause some disruption in helping users find their log files, and as a small group we are focusing our time enhancements to help the largest number of users we can. Thanks for your feedback, and let me know if you have any other issues with the program.
