### ISSUE TITLE
Remove music from video.

### ISSUE THREAD

**Issue by NazmusShakib** [OpenShot/openshot-qt#461]
I can't found the music/mike icon on the track bar. my openshot video editer  version is 2.2.0  How can i get this?

**Comment by JtLively** [comment]
You can mute or hide a track by selecting the speaker or eye icon respectively on the left side of each track under the track name. If you can't see it, you may need to change your color theme.

You can also mute or hide specific sections by selecting its options and the audio and video sections.

If you have any other issue, please ask in #openshot IRC or open a new issue.

**Comment by NazmusShakib** [comment]
thinks Just fixed it up.

**Comment by NeonGahoole** [comment]
I looked under the Track name and there was no option that read "Remove Music"
cuz I'm using Openshot for Gaming Editing

**Comment by ferdnyc** [comment]
@NeonGahoole That's correct, no such option exists. And the advice here is for a much older version of OpenShot, it no longer describes the current interface so none of it would be useful when using OpenShot 2.4.x.

If you have an imported video and you want to simply _remove_ the original audio completely, you can do that in a few different ways.

After you place your video on the Timeline as a Clip, you can:

-  Go into the Clip's Properties and set "Has Audio" to 0 (false)

Or...

- Right-click on the Clip, then choose Volume > Entire Clip > Level 0% from the menus, to mute the audio for the entire duration of the Clip.

Or, if you don't plan to replace the original sound with _different_ audio, and you just want to export the video only...

- In the Export dialog, under Advanced > Advanced Options, choose Export To: Video Only to encode your video without an audio track.
