### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by AJamesPhillips** [OpenShot/openshot-qt#4610]
**Describe the bug:**
I saved a project whilst there was a strange UI bug and on reopening I get the error: `'NoneType' object is not subscriptable`

**Steps to reproduce the behavior:**
1. Open the attached project file

**Expected behavior:**
It should open without error

**System Details:**
- OpenShot Version: 2.6.1
- Operating System / Distro: Mac Big Sur 11.6.1

**Log Files:**
[openshot-qt.log.zip](https://github.com/OpenShot/openshot-qt/files/7755917/openshot-qt.log.zip)

**Exception / Stacktrace:**
n/a

**Additional context:**
* I had pressed paused.  The "timeline" vertical red line was mid way through a clip.
* I right clicked the clip to show the "context menu".
* I chose "Split" > "Keep right" (or "keep both"? I can't remember it was last night).
* First potential other bug: the split seemed to occur in a position to the right of where the current time was.
* I then tried to undo with Ctrl+z
* I think it then put in two clips, the original, with the new partial clip overlaying it.  I could not only select one.  They also had a "strange" (different) yellow outline instead of the normal red outline when there were selected.
* I pressed save, closed the program and went to bed.
* On opening the project I see the above error: "'NoneType' object is not subscriptable"

The project file is here:

[2__focused_mode_and_filters.osp.zip](https://github.com/OpenShot/openshot-qt/files/7755947/2__focused_mode_and_filters.osp.zip)

**Comment by AJamesPhillips** [comment]
I fixed it by deleting the null values and clearing the undo / redo history.

For any one else with the same problem.  Make a backup copy of your .osp file then:

1. Open your .osp file in a text editor like TextEdit or NotePad and open your browsers developer terminal then:
  1. type `your_project_data = ` in your browser developer terminal
  2. copy the contents of the .osp file and then paste the contents into your browser terminal
  3. wait a long time for your browser to parse it all (perhaps a couple of minutes)
  4. press enter
  5. wait some more time for your browser to display it
2. then type `your_project_data.history = {undo: [], redo: []}`
3. check the last entry in "clips" is not null using: `your_project_data.clips[your_project_data.clips.length - 1]` and press enter
4. if it shows as `null`, you need to remove this entry, otherwise skip to point 5 below:
  1. your_project_data.clips = your_project_data.clips.slice(0, -1)
5. To get this repaired data back out:
  1. type: `console.log(JSON.stringify(your_project_data))`
  2. Copy this
  3. Paste into your .osp file and save it using your text editor
  4. close your text editor
6. Open OpenShot and try to reopen your project.  🤞  hopefully it now works.

**Comment by AJamesPhillips** [comment]
Maybe related to #1151 or #4505 ?

**Comment by JacksonRG** [comment]
@AJamesPhillips I appreciate you troubleshooting your issue yourself. Apologies that we missed your issue.

If you've found this happening to many projects let us know, and we can try to find how the projects are getting corrupted. Otherwise closing this issue.
