### ISSUE TITLE
Issues with making titles with inbuilt editor

### ISSUE THREAD

**Issue by MrGenie151** [OpenShot/openshot-qt#4613]
**System Details:**
- Latest
- Linux Mint

Hello! Currently I'm using Linux Mint and trying to edit Youtube videos with OpenShot. However, there is one HUGE issue I'm having...

Titles aren't appearing as intended. And it is starting to get REALLY annoying. I have Inkscape properly installed, but all the text is just gone on the titles. Bumping up the text size helps, but for templates like the movie rating ones, it just sizes all of them the same size. I haven't heard anyone else talk about this, and it needs to be fixed if it is an internal problem. If not, tell me what I should do to fix this myself.

**Comment by JacksonRG** [comment]
Sorry to hear about this. Could you include screenshots of the problems you're seeing?

We're currently making sure Openshot works properly with a recent update to Inkscape.

Are you able to change the text in Inkscape, and do those titles show up correctly in OpenShot?

**Comment by MrGenie151** [comment]
> Sorry to hear about this. Could you include screenshots of the problems you're seeing?
> 
> We're currently making sure Openshot works properly with a recent update to Inkscape.
> 
> Are you able to change the text in Inkscape, and do those titles show up correctly in OpenShot?

Yes, I am able to change the text in Inkscape, however it is kind of a hassle to have to do it everytime for the special titles or any titles that involve any kind of differing font sizes.
Screenshots:
_What it should look like_
![whatshould](https://user-images.githubusercontent.com/83074931/147485192-cdaa001a-5903-4bb5-8345-926f9535d7ae.png)
_What it actually looks like_
![whatis](https://user-images.githubusercontent.com/83074931/147485212-9c6ee7a9-79f0-4839-8dd7-96a0f8b9043d.png)
_What it actually looks like if you put it at the 2nd to last font scaling option_
![whatis2](https://user-images.githubusercontent.com/83074931/147485217-885ab2f6-ca59-4ee5-b2e0-f20bfb5f2ef8.png)

**Comment by JacksonRG** [comment]
I'm looking for the PR. I know a fix for scaling fonts _relatively_ rather than changing them all to the same font size is being worked on. I'll get back to you on whether it's in the current daily build.
