### ISSUE TITLE
How to configure Blender path on Linux OpenShot version?

### ISSUE THREAD

**Issue by AyProductions** [OpenShot/openshot-qt#4614]
I installed OpenShot just now w/ Blender & Inkscape. And I have to add an animated title for a party video. I tried to do that, but I can't seem to find the 'blender' path to configure. How to do it?

Error: 
![Screenshot from 2021-12-24 16-04-56](https://user-images.githubusercontent.com/76834319/147345468-95dce227-54f7-4feb-9a71-12981bbee4c6.png)

**Comment by Ilmarinen946** [comment]
I'm not sure if this is related to the install path.
I have the same issue but I get a more detailed error report in Fedora Problem Reporting.
![20220205_202117](https://user-images.githubusercontent.com/11019700/152657616-5f5294ab-f30a-4cc1-bef3-db0c36194d0e.jpg)
Not an expert but it says the script is looking for an integer (script default is 5000) but gets given a float (when I opened the magic wand animation, the default was 5000.00)

Think this could be linked?

**Comment by AyProductions** [comment]
It can be. But wait let me test it

**Comment by JacksonRG** [comment]
@AyProductions If you open `Edit > Preferences` in the top left, the general tab has a field for "Blender Path".

You can then run the command `which blender`. Do the two match?

**Comment by eliboni** [comment]
ref. #4518

**Comment by JacksonRG** [comment]
OP gave a 👍. Assuming this issue is fixed.

Feel free to reopen if that's not the case.
