### ISSUE TITLE
Text Titles Template issues - Keyboard lag and "not responding" message

### ISSUE THREAD

**Issue by Colorjet3** [OpenShot/openshot-qt#4625]
**Describe the bug:**
Several issues to report
1.  Typing "Delay" in Text fields when keying(  Keyboard lag) for all Title templates that allow text keying with a few exceptions.

Exceptions
Creative commons1 - Still lags but not as bad as the others
Creative commons2 -  Still lags but not as bad as the others
Film rating 1 - Still lags but not as bad as the others
Film rating 2 - Still lags but not as bad as the others
Film rating 3 - Still lags but not as bad as the others
Film rating 4 - Still lags but not as bad as the others

2.  Bubbles1, Bubbles2, Post it, and Sunset exhibit this behavior
Very delayed and when you click anywhere in the window it goes into "Not Responding" state after trying to type in line 1, line 2, etc. If you wait long enough it recovers from "Not responding" and you can continue typing again but with the same symptoms.
1. Go to Title | Titles and select any template.
2. Click on a text field (line 1, line2, etc.) and you will notice the keyboard lag.

**Steps to reproduce the behavior:**
Situation 1 - keyboard lag only
1. Go to Title | Titles and select any template.
2. Click on a text field (line 1, line2, etc.) and you will notice the keyboard lag.

Situation 2 - keyboard lag and "Not Responding".
This applies to Bubbles1, Bubbles2, Post it, and Sunset.
1. Go to Title | Titles and select any template.
2. Click on a Line 1 and start typing.  You will notice a delay.
3. Not knowing what is happening click on Line 2 and try typing something.  Nothing happens.
4. You hover over that window contemplating what is going on.
5. You click a few times on the window in hopes it responds and you will notice the "Not Responding".
6. You wait a bit and it comes back.
7. You can continue completing your text input but will continue the same issue.

**Expected behavior:**
I expect no lag during keyboard input.
I expect no "Not responding" message during keyboard input.

**System Details:**
- OpenShot Version 2.6.1-dev, libopenshot: 0.2.7-dev, Openshot-v2.6.1-dev-daily-8945-3c8dc71b-2b8b05c7
- Operating System / Distro: Windows 10 with the latest updates
- Windows 10 with 1TB NVMe, Nvidia GeForce 2060 w/6GB RAM, and 32GB RAM, AMD Ryzen 7 3700x 8-Core processor

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

No crashing

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by roelandschoukens** [comment]
I got hit by this as well, I think in my case the computer is not fast enough to render a preview after every key stroke in the title field.

**Comment by JacksonRG** [comment]
Hm... I saw the lag, but not the error message. Looks like we need to either find a way to preview the svg faster, or add a wait, so we don't preview until the user hasn't typed for a second or more. Thanks for pointing this out!

**Comment by Colorjet3** [comment]
I tested this again today, using build #9122, and experienced both the lag and the "not responding".  Use the either Bubbles 1 or Bubbles 2 template.  Type a sentence in Line 1 or Line 2 and you will see a very long delay.  If you get impatient, like most users will, and click in the text field not knowing why things are getting delayed then OpenShot will go into "Not Responding" mode.  If you wait long enough it will eventually come back with the text you typed.  Let me know if you would like a video of this so you can see what I am experiencing.

**Comment by JacksonRG** [comment]
Ok. I just got the "not responding" by trying with Bubbles 1. Very odd. We'll take a look at the svg rendering. But I'm guessing that's a library we're importing, and it's out of our hands. So what we could do is keep the editor from waiting on the svg to render.

**Comment by Colorjet3** [comment]
Sounds good @JacksonRG .
