### ISSUE TITLE
Die Hintergrundfarbe beim Erstellen eines Titels wird nicht übernommen.

### ISSUE THREAD

**Issue by ONTHIEL** [OpenShot/openshot-qt#4631]
Die Hintergrundfarbe beim Erstellen eines Titels wird nicht übernommen.
HTML Code: #154e3d

**Comment by Colorjet3** [comment]
This may be related to https://github.com/OpenShot/openshot-qt/issues/4626

**Comment by Pepper1983** [comment]
Korrekt, Hintergrundfarbe wird nicht übernommen.
Workaround: Zuerst "Eine Farbe vom Bildschirm wählen" und bestätigen, danach geht auch HTML Code: #154e3d

**Comment by ONTHIEL** [comment]
Dankeschön!
