### ISSUE TITLE
Crash on import multiple mediq

### ISSUE THREAD

**Issue by Brobit** [OpenShot/openshot-qt#4643]
Hi , openshot crash when i import multiple video.

i import like 50 videos of approximatly 10 sec each but it crash when import them, i can import maximum 5 video so it make like 50 sec of video in total , if i want to import one more, it crash.

**Describe the bug:**

**Steps to reproduce the behavior:**
1. Go to 'openshot'
2. Click on 'import media'
3. Select the media
4. click on 'open'
5. See error

**Expected behavior:**

I excpected to import the medias and work 

**System Details:**
- OpenShot Version 2.6.1
- Operating System / Distro: win 10 pro 20h2

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/7847060/libopenshot.log)

[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/7847067/openshot-qt.log)

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
I just copied 76 video files (.mp4 & .mov) of various duration, all at once, and OpenShot had no issues with it.  I am running OpenShot v2.6.1-dev-daily-8946.  My environment is:  Windows 10 Pro, 21H2 w/32GB of RAM, AMD Ryzen 7 3700X 8-Core processor, 1TB Nvme drive.

**Comment by Brobit** [comment]
i have an i5-10600k with rx580 , 16gb of ram and 500g ssd nvme , and i'm on win 10 pro 21h2 too , so i don't see the problem ,i have already do this issues but it doesn't help me unfotunetly :/ . By the way thanks for your answer .

**Comment by Colorjet3** [comment]
What I am suggesting is for you to uninstall version 2.6.1-Release-Candidate (Help | About OpenShot) and install the latest "Daily Build" dev version and give it a try.  See https://github.com/OpenShot/openshot-qt/wiki/Clean-Installation-of-OpenShot for a clean installation.

Let us know if this helped or not.
