### ISSUE TITLE
Track renaming allows for duplicate names.

### ISSUE THREAD

**Issue by Colorjet3** [OpenShot/openshot-qt#4645]
**Describe the bug:**
I am able to rename a track to an existing track in the same project.

**Steps to reproduce the behavior:**
1.  Start OpenShot
2. Right click on Track 5 and select "Rename Track"
3. Change Track 5 to Track 4 (just replace the 5).
4. Now you have two tracks with the same name.

**Expected behavior:**
A message should popup indicating that a track with that name already exists and not allow me to rename it until I select a unique name.

**System Details:**
- OpenShot Version v2.6.1-dev-daily-8946
- Operating System / Distro: Windows 10

**Log Files:**
Not crashing.

**Exception / Stacktrace:**
Not crashing.

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by HamaBarhamou** [comment]
salu jaimerai me pencher sur ce probleme

**Comment by JacksonRG** [comment]
I'm not sure this is a problem. Behind the scenes, OpenShot uses a number to *keep track* of all the different tracks. Unless this causes any issue in preview or exporting a video, I think we can let users name tracks anything they want.
