### ISSUE TITLE
OpenShot is slow and freeeeeeze on Mac os x Catalina and Windows 11

### ISSUE THREAD

**Issue by ghost** [OpenShot/openshot-qt#4646]
```
System 

      Win 11 
      AMD Ryzen 5 3400G with Radeon Vega Graphics       3.70 GHz
      RAM 8,00 Go
      
      or 
      Mac os x Catalina
      RAM 8,00 Go
```

```
Problems 

        with OpenShot options cache limit : 1024  (or 2048) with rendering at  "HD 72p 30"  or "mobil 360 p"
        
        OpenShot is slow and freeeeeeze on Mac os x Catalina and windows 11.
        
        Drag and drop the first 50p video is ok. The second : disaster...
        
        It wasn't like that before.
        
```

  Thanks for your helping.

**Comment by hel1o-wor1d** [comment]
And cannot open on MacOS 12.1 monterey  x86_64

**Comment by ghost** [comment]
Hello,
i have installed a 16 GB  (20 GB in total) and reinstall Windows 11 and OpenShot is good now.
I haven't problems now...

**Comment by ghost** [comment]
Hello, it freezes again.
This happens right after a clean installation of Windows 11 with OpenShot-v2.6.1-x86_64.exe

**Comment by JacksonRG** [comment]
@fredOnGitHub Hi, did this happen with the release version 2.6.1? If so, could you compare to the daily build, and let us know if you still see this freeze?

**Comment by ghost** [comment]
With OpenShot-v2.6.1-dev-daily-9481-664c5db8-46255e46-x86_64.exe, the problem seems to disappear.

But I have a new problem: 

to re-test I uninstalled and installed OpenShot-v2.6.1-x86_64.exe and when it starts it shows 2 times 'out is not a valid transition file' and I can't access the preferences (freeze).

With the uninstallation, then again the installation of OpenShot-v2.6.1-dev-daily-9481-664c5db8-46255e46-x86_64.exe (this time) and the English language (or other) I always get 2 times the display 'out is not a valid transition file' and the context menu is always stuck on the old language.

**Comment by ghost** [comment]
It seems be good 👍 

I uninstalled it with Windows uninstaller.
According  https://www.youtube.com/watch?v=WmkAYOP_HEU I deleted .openshot_qt.

So when I install OpenShot-v2.6.1-x86_64.exe with cache to 8000 (MB) it is uncomfortable (not fluid).

After a new clean uninstall according mentioned before and when I install OpenShot-v2.6.1-dev-daily-9481-664c5db8-46255e46-x86_64.exe ( Daily Builds) with cache to 8000 (MB) it is fluid.

But in the 2 installation the context menu is always stuck on the old language. Not the new one I chose during installing...

**Comment by JacksonRG** [comment]
@fredOnGitHub I understand the confusion. The language you select during the installation progress is actually just the language used *during* installation. Not when Openshot first opens. That still has to be set in the settings.

And thanks for the info. Good to know the windows one is working. I'll keep looking into that new issue with the Mac installation.
