### ISSUE TITLE
Imported Audio Plays as Static

### ISSUE THREAD

**Issue by Malphrush** [OpenShot/openshot-qt#4647]
**Describe the bug:**
Anytime I play imported audio, I hear static instead of the actual audio. 

**Steps to reproduce the behavior:**
1. Import an audio file
2. Right click file -> Preview -> "Click Play Button"

Or

1. Import an audio file
2. Drag it to a track
3. Preview Video

**Expected behavior:**
I should hear the actual audio

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 2.6.1-dev
- Operating System / Distro: Windows 10 64bit

**Log Files**
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/7875154/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/7875155/openshot-qt.log)

**Comment by JacksonRG** [comment]
@Malphrush Is this happening with a variety of different types of audio files, from multiple different sources, or are all these audio files gathered in the same way?

Also, have you verified that the videos have sound by playing them in another program?
