### ISSUE TITLE
Pack with subdirectory (v2.2.0)

### ISSUE THREAD

**Issue by leventelist** [OpenShot/openshot-qt#465]
It would be nice if the released tar.gz file contained a directory. Now the root of the tarball contains the src/ and other files etc. This can ruin your day when you forget to make some directory for it. Same goes for libopenshot(-audio).

Just a wish though.

**Comment by jonoomph** [comment]
Thanks for the suggestion, but for the moment, I'm going to leave things the way they are. For example, changing the layout of my tar.gz file will literally break everything on our 3 build servers, and will break all the various Linux distro build servers also. So, in an effort to not break everything, I'm going to leave this alone. =)

**Comment by leventelist** [comment]
On Wed, 01 Mar 2017 23:23:13 -0800
Jonathan Thomas <notifications@github.com> wrote:

> Thanks for the suggestion, but for the moment, I'm going to leave
> things the way they are. For example, changing the layout of my
> tar.gz file will literally break everything on our 3 build servers,
> and will break all the various Linux distro build servers also. So,
> in an effort to not break everything, I'm going to leave this alone.
> =) 

Yeah... I had been a build and release engineer for long time... I know
the story.

Levente

-- 
73 de HA5 OpenGL
Op.: Levente
