### ISSUE TITLE
Openshot is scaled too largely

### ISSUE THREAD

**Issue by chraxo** [OpenShot/openshot-qt#4650]
**Describe the bug**
Openshot is scaled too largely on the notebook screen. At the connected monitor the sizes are correct (see attached screenshots). The window title is always in the correct size (in both cases).

**Steps to reproduce the behavior:**
I tried some ways to avoid the bug, but without success. Therefore I cannot say which are the steps to reproduce.

What I did:
1. Install OpenShot for the very first time, while the monitor was attached to the notebook (I do not know if this is relevant or not).
2. Use OpenShot on the attached monitor. I think the issue then already was present, but I did not notice it, as I placed OpenShot always on the external monitor.
3. Continue working with OpenShot. Shutdown PC. Restart PC, and so on.
4. Disconnect the external montor and detecting the described problem.

To investigate the problem I further did the following:
1. Uninstall Openshot.
2. Install Openshot while the external monitor is disconnected.
3. The problem still exists.

**Expected behavior**
The controls and the texts should have the correct size (see screenshot of Screen 2). The size of the text at the menu should be roughly the size of the window title bar.

**System Details**
- OpenShot Version: 2.6.1
- libopenshot Version:  0.2.7
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-GB', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Skipped this step

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/ajy5vddgwphqb22rbqpugjx8adifzieh/openshot-qt.zip) (82 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/ajy5vddgwphqb22rbqpugjx8adifzieh/libopenshot.zip) (58 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots**
<img width="2560" alt="OpenShot_Screen1(Laptop)_too large" src="https://user-images.githubusercontent.com/20266035/150021860-64c8dcea-869f-4682-804f-24811ca2e8f3.PNG">

<img width="2560" alt="OpenShot_Screen2(ExternalMonitor)_correct" src="https://user-images.githubusercontent.com/20266035/150021833-14218b47-1819-4ec9-9626-96b519644f3d.PNG">

**Comment by JacksonRG** [comment]
Does anything happen if you delete your `C:\Users\userName\.openshot_qt\` folder, and then start OpenShot (with the monitor disconnected)?

**Comment by pxldevv** [comment]
Is there a fix to this yet?

**Comment by Colorjet3** [comment]
Hello @Techpro709 .  No fix yet but in the queue.
