### ISSUE TITLE
pause-play toggle doesn't react at all or lags a lot. slow playback. slow "next frame"

### ISSUE THREAD

**Issue by gaboychabela** [OpenShot/openshot-qt#4654]
**Describe the bug**
pause-play toggle doesn't react at all or lags a lot. slow playback. slow "next frame"

**Steps to reproduce the behavior:**
Click play
Click pause
It doesn't pause at all or pauses after a long time, makes it impossible to use if you can't make it stop or pause exactly where you need it in the timeline.
Click arrow right, it takes forever to get to next frame, makes it for an impossible way to review and edit clips. 

**Expected behavior**
The above problems were not present when using OpenShot 2.5, I updated due to pop-up sayig updates were available. 

**System Details**
- OpenShot Version: 2.6.1-dev
- libopenshot Version:  0.2.7-dev
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 23 Stepping 6, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-dev-daily-9005-49d6ba3b-2b8b05c7-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/71d4hkaw1olnzm51z6yr2xio1nfdv64e/openshot-qt.zip) (20 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by Bartheleway** [comment]
Same here

**Comment by JacksonRG** [comment]
Good news! We are currently working on a general refactor of our cache and video timing code. I would link this issue to that PR, but it's on our library repo. We'll update this issue when that's done.

**Comment by gaboychabela** [comment]
> Good news! We are currently working on a general refactor of our cache and video timing code. I would link this issue to that PR, but it's on our library repo. We'll update this issue when that's done.

Looking forward to update.

**Comment by JacksonRG** [comment]
Well the current daily build has our most up to date changes to the cache. We've made changes to keep the cache from interfering with playback. I'd love to hear what you think if you test it out.
https://www.openshot.org/download/
