### ISSUE TITLE
Imported and moved 2 hour clip (x264) to OpenShot, "razored" and deleted, and razored again. Moved n...

### ISSUE THREAD

**Issue by SlackedMarcel** [OpenShot/openshot-qt#4655]
[Bug with more untrimmed stuff.txt](https://github.com/OpenShot/openshot-qt/files/7927816/Bug.with.more.untrimmed.stuff.txt)
**Describe the bug**
Imported and moved 2 hour clip (x264) to OpenShot, "razored" and deleted, and razored again. Moved newly razored piece to a new track. razored new clip > crash.

**Steps to reproduce the behavior:**
1. Dragged into workspace area (not track) 2 hour video (no other clips) (can be provided - d00mer-cmc.disk1.1080p.bluray.x264)
2. Deleted 4 blank tracks (leaving 1 blank track left)
3. Dragged clip to Track 1
4. Track 1 rendered
5. Used left/right cursor and mouse clicking around on timeline to review clip.
6. Moved to selection of timeline
7. Used razor tool to cut (left side of highlighted frame)
8. Deleted the left side of the razor cut.
9. Moved down the timeline about 20 minutes (back and forth using keypresses and mouseclicks)
10. Select the razor tool, razor to the left of the selector.
11. Create Track 2
12. Move the 20 minute segment down to Track 2 (aligned to where it was on Track 1)
13. Move back to Track 1, and move the selector 2 or 3 minutes on the timeline
14. Select the Razor tool
15. Razor the RIGHT (long clip side of the selector, previous clips have been on the short side/LEFT side).
16. OpenShot crashes (windows crash window, NOT hang > crash, immediate crash.)

Notes:
1. I did not make the original video.
2. I haven't tried to repro, I will after submitting this. 
3. Running 64GB, a i9-9900k on a M2SSD... don't think I'm starving for resources.
4. I am watching GPU powered YouTube, and my machine network is very busy.
5. I'm running a ultrawide monitor, and was in windowed mode (about 900x720 or something)
6. My 2080RTX is running the latest drivers (checked this morning before crash)

7. Event info:
Faulting application name: openshot-qt.exe, version: 2.6.1.0, time stamp: 0x607466f6
Faulting module name: libopenshot.dll, version: 0.0.0.0, time stamp: 0x613402ee
Exception code: 0xc0000005
Fault offset: 0x00000000000db6f1
Faulting process id: 0x2ffc
Faulting application start time: 0x01d81145c8ed2476
Faulting application path: C:\Program Files\OpenShot Video Editor\openshot-qt.exe
Faulting module path: C:\Program Files\OpenShot Video Editor\lib\libopenshot.dll
Report Id: 0703fa93-51e1-4357-a469-ec9f2c6c11ba
Faulting package full name: 
Faulting package-relative application ID: 

8. More info (WER's are not available):
Fault bucket 1201591712937092271, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: openshot-qt.exe
P2: 2.6.1.0
P3: 607466f6
P4: libopenshot.dll
P5: 0.0.0.0
P6: 613402ee
P7: c0000005
P8: 00000000000db6f1
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD87C.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERDA52.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERDA63.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERDA61.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERDA81.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_opens...

**Comment by JacksonRG** [comment]
Could you include the logs from when this happened? Ideally clearing them then re-creating the bug.

Instructions on doing that can be found [here](https://github.com/OpenShot/openshot-qt/wiki/Issue-Logging)

**Comment by SlackedMarcel** [comment]
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/7929350/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/7929351/openshot-qt.log)

**Comment by JacksonRG** [comment]
Looking through your log, it looks like the python package `urllib3` is the start of the error, then there seems to be feedback of a few packages passing errors back and forth.

How do you have openshot installed? Did you install python separately?

**Comment by SlackedMarcel** [comment]
I run the installer off one of the mirrors from the website. I didn’t make any selections through the install process that weren’t default. I haven’t implicitly installed python separately (but there probably are previous installs of it that came with other pieces of software (unrelated to openshot).

Let me know what else I can do to help. Fresh install of python maybe, and see if I can repro?

hi @jonoomph from the raptr days.
