### ISSUE TITLE
Video file preview playback speed is either very slow with 2.6.1, or very fast in the daily build.

### ISSUE THREAD

**Issue by Russs63** [OpenShot/openshot-qt#4658]
**Describe the bug**
Video preview playback speed is either very slow with 2.6.1, or very fast in the daily build.

**Steps to reproduce the behavior:**
1. Load any video file.
2. Click on Preview
3. Video playback speed is very wrong, either too slow w/ 2.61, or too fast w/ 2.6.1-dev.

**Expected behavior:**
I expect the videos to play back at the normal speed, like every other video rendering program does, with these same files.

**System Details**
- OpenShot Version: 2.6.1-dev
- libopenshot Version:  0.2.7-dev
- Platform: Windows-7-6.1.7601-SP1
- Processor: Intel64 Family 6 Model 45 Stepping 7, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-dev-daily-9005-49d6ba3b-2b8b05c7-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/r90ea25coyyjtq1xbzsw1zd2l4uqtiqu/openshot-qt.zip) (7 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by Russs63** [comment]
Just verified that 2.5.0 is working fine... but 2.6.x is very broken wrt preview speeds.

**Comment by JacksonRG** [comment]
Thanks for your feedback! We're currently working on a fix for this, and will love to hear your feedback when that's complete.
