### ISSUE TITLE
importing AVCHD video

### ISSUE THREAD

**Issue by mistergarth** [OpenShot/openshot-qt#466]
I'm new to OpenShot. I'm doing fine importing Quicktime videos, but I can't get my AVCHD video to import. It's listed on the features page, but I can't figure it out. How do I import AVCHD to OpenShot?
Mac OS 10.11.6, OpenShot 2.2

**Comment by DylanC** [comment]
@mistergarth - Does this issue exist in OpenShot v2.3.4? Please confirm.

**Comment by mistergarth** [comment]
I do not know. Back when I wrote this, I was experimenting with several free/inexpensive video editors. I settled on HitFilm. But to edit AVCHD footage in most current editors, you need to convert it to a more editable format. I use EditReady to convert it to Quicktime using a ProRes codec.

**Comment by DylanC** [comment]
@mistergarth - No problem. Thanks for the feedback.
