### ISSUE TITLE
NVENC/VDPAU not working (Linux,Nvidia 495)

### ISSUE THREAD

**Issue by freakedenough** [OpenShot/openshot-qt#4662]
17:23:04 INFO app: openshot-qt version: 2.6.1-dev
17:23:04 INFO app: libopenshot version: 0.2.7-dev
17:23:04 INFO app: platform: Linux-5.13.0-28-generic-x86_64-with-glibc2.34
17:23:04 INFO app: processor: x86_64
17:23:04 INFO app: machine: x86_64
17:23:04 INFO app: python version: 3.9.7
17:23:04 INFO app: qt5 version: 5.15.2
17:23:04 INFO app: pyqt5 version: 5.15.4
17:23:04 INFO project_data: Setting default profile to HD 720p 30 fps

None of the available HW acc export options (H264,HEVC VAAPI/VDPAU/NVENC) work for me.
NVENC as such should be fine because https://github.com/elFarto/nvidia-vaapi-driver works for me.
I expect to get at least NVENC to work, I am aware that VAAPI is unsupported by nVidia drivers (using v495 one).

```
17:23:20 INFO export: Export path: /home/besitzer/Unbenanntes Projekt.mp4
17:23:21 INFO project_data: _set key: ['export_path'] values: /home/besitzer add: False partial: False remove: False
17:23:21 INFO main_window: updateStatusChanged
17:23:21 INFO export: Error type string: Could not open video codec for file /home/besitzer/Unbenanntes Projekt.mp4
17:23:21 INFO logger_libopenshot: FrameMapper::ChangeMapping (target_fps.num=30.0000, target_fps.den=1.0000, target_pulldown=2.0000, target_sample_rate=48000.0000, target_channels=2.0000, target_channel_layout=3.0000)
17:23:21 INFO logger_libopenshot: FFmpegWriter::SetVideoOptions (hevc_vaapi) (width=1280.0000, height=720.0000, size.num=16.0000, size.den=9.0000, fps.num=30.0000, fps.den=1.0000)
17:23:21 INFO logger_libopenshot: FFmpegWriter::SetAudioOptions (aac) (sample_rate=48000.0000, channels=2.0000, bit_rate=192000.0000)
17:23:21 INFO logger_libopenshot: FFmpegWriter::PrepareStreams [/home/besitzer/Unbenanntes Projekt.mp4] (info.has_audio=1.0000, info.has_video=1.0000)
17:23:21 INFO logger_libopenshot: FFmpegWriter::initialize_streams (fmt->video_codec=173.0000, fmt->audio_codec=86018.0000, AV_CODEC_ID_NONE=0.0000)
17:23:21 INFO logger_libopenshot: FFmpegWriter::add_video_stream (mp4 : vaapi_vld) (c->codec_id=173.0000, c->bit_rate=15000000.0000, c->pix_fmt=46.0000, oc->oformat->flags=327744.0000)
17:23:21 INFO logger_libopenshot: FFmpegWriter::add_audio_stream (c->codec_id=86018.0000, c->bit_rate=192000.0000, c->channels=2.0000, c->sample_fmt=8.0000, c->channel_layout=3.0000, c->sample_rate=48000.0000)
17:23:21 INFO logger_libopenshot: Encode Device not present, using default ()
17:23:22 INFO logger_libopenshot: Timeline::Close ()
```

Can you please help be to get it working? Intel and AMD systems just work out of the box, unfortunately my powerhorse with nvidia 2060 does not.

**Comment by freakedenough** [comment]
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/7952166/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/7952168/openshot-qt.log)
[openshot.settings.log](https://github.com/OpenShot/openshot-qt/files/7952170/openshot.settings.log)

**Comment by freakedenough** [comment]
![Screenshot_20220127_173515](https://user-images.githubusercontent.com/93607470/151402598-95f3301b-0ae6-41ab-9ecb-fdd65b875218.png)

**Comment by Cyborgscode** [comment]
I have another bug open since September 2021 for nvidia 470-510.60.02. where OS-QT also does not work on Fedora Linux.
