### ISSUE TITLE
Openshot cutting down my clips

### ISSUE THREAD

**Issue by GG-Hernandez** [OpenShot/openshot-qt#4663]
**Question:**
I am trying to edit an animation I  made. I already rendered the clips. When I import them into Openshot, add them to the timeline and hit play it seems to cut my animated clip by .5 of a second. 
**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
I am using the lastest system of Openshot and animating in Krita. 
**Screenshots:** (Optional)

**Comment by matwolf** [comment]
I think, I posted the same question 1½ yrs. ago ([#3635](https://github.com/OpenShot/openshot-qt/issues/3635)). The issue was closed after 180 days of inactivity without even assigning someone to it.

I now use [Shotcut](https://www.shotcut.org/) and am happy. After one day of practicing, I can do everything I need (and most of it quicker and at higher quality. I kid you not.)

**Comment by JacksonRG** [comment]
@GG-Hernandez so is it the _last_ 1/2 second that isn't showing? Also what video file format are your animations in?

**Comment by neekt** [comment]
In addition to #3635, I reported this bug a year ago #4023. I tested it again yesterday with the latest daily build - to prevent the issue from being closed by the stale bot - and the issue persists.

It's a pretty substantial bug, so I'm not sure why it hasn't received any attention, given the active - indeed daily - development of the app.

**Comment by JacksonRG** [comment]
@neekt It's been a long bug to find. My partial understanding is it only happens in specific videos whose timestamps for audio and video start at different times (sometimes before 0 seconds... encoding is weird) We just merged a fix for cases where the video file is longer than the audio track, and are working to find how this happens.

@GG-Hernandez There may be a similar discrepancy in your video file. Can you manually set the `end` property of your animations and add a few seconds? (in right click -> properties)
    - If you find there's audio clicking, because you're playing after the end of the audio, just download the daily build. We just prevented that from happening.

**Comment by Popolon** [comment]
There was no video on the video clip I mentioned here on September 2020: 
https://github.com/OpenShot/openshot-qt/issues/3635#issuecomment-694193745
The clip is cut during import (open file), there is no way to correct it after that as last frame already
