### ISSUE TITLE
Wrong time range exported from the video

### ISSUE THREAD

**Issue by gileli121** [OpenShot/openshot-qt#4665]
**Describe the bug:**
When you try to split video and take from it specific time frame, it will export wrong range

**Steps to reproduce the behavior:**
1. Cut the video somewhere in the middle so it split to 2 pieces 
2. Cut the video again after the first cut so you will have 3 pieces
3. Remove the first piece and the last piece so now you have only one piece that is the middle
4. Move the middle to the start of the video track
5. Change the payback speed of this piece to 4x
6. Select: File->Export Project->Export Video and export it
7. Wait for the export to finish
8. Open the exported video and play it

**Expected behavior:**
You should see the middle piece with the modified 4x speed

**Actual behavior*
You will see some other part of the video in 4x speed. It did not took the right frames from the middle piece.

**System Details:**
- OpenShot Version 2.6.1
- Operating System: Windows 11 22000.434

**Log Files:**
No crash so no logs

**Comment by Colorjet3** [comment]
I tested this with daily build #9122 and had no issues.  Please download and perform a clean installation using these instructions:  https://github.com/OpenShot/openshot-qt/wiki/Clean-Installation-of-OpenShot.  Let us know if this worked for you.
