### ISSUE TITLE
Audio Doesn't Line Up During Editing.

### ISSUE THREAD

**Issue by Raziel0315** [OpenShot/openshot-qt#4666]
Describe the bug:
When a second audio clip is added, the audio from both clips starts to lag.  I have not found any consistent "fixes"

Simply play 2 audio clips at the same time.  
This is a new issue for me.  The 2.6.1 official download does not do this.

Expected behavior:
audio should play when it's supposed to.

OpenShot Version 2.6.1  Daily Build 64x from January 25, 2022
Operating System: Windows 10

**Comment by Colorjet3** [comment]
Please providethe Daily Build #.  In OpenShot, you will find this by going to Help | About Openshot.  Also, please export your project and let us know if the problem persists.

**Comment by Colorjet3** [comment]
Please download the latest DEV daily build of v3.0.0.  Install it.  In Openshot, ensure that the Default Audio Sample Rate is set to 48000.  Restart Openshot and all should be good.
