### ISSUE TITLE
Arrow Keys not working in latest Daily Build

### ISSUE THREAD

**Issue by gcleaves** [OpenShot/openshot-qt#4667]
This bug is still in effect on Mac: https://github.com/OpenShot/openshot-qt/issues/3760

**Comment by JacksonRG** [comment]
Thanks for pointing this out.

Just to get an idea of what's broken, can you use your arrow keys anywhere in openshot, (like in the project files window, or to scroll the timeline left and right, to move forward and back a frame)

**Comment by john-harvey** [comment]
These do not work for me:
SHIFT-LEFT/SHIFT-RIGHT nudge
UP/DOWN play/pause toggle alternates 1&2

These DO work:
LEFT/RIGHT previous/next frame
CMD-LEFT/CMD-RIGHT previous/next markers (on a clip)
CMD-LEFT/CMD-RIGHT jump to beginning/end of timeline 

Running on a Mac powerbook.  See attached About dialog for version and build info
<img width="536" alt="Screen Shot 2022-02-25 at 7 32 53 AM" src="https://user-images.githubusercontent.com/13237144/155723952-8ee3e3d9-9d5f-45cf-b931-ffc997a723cb.png">

**Comment by JacksonRG** [comment]
Hmm... as a temporary work around, you can zoom with `+/-` (or ctrl+scroll) until you can see individual frame marks. Also what version of MacOS is this happening on? That may be a factor.

**Comment by john-harvey** [comment]
Mac OS version
Big Sur 
11.6.3
