### ISSUE TITLE
Zoom Tracks Bug

### ISSUE THREAD

**Issue by Bropii** [OpenShot/openshot-qt#4668]
Theres this bug where the track is very dense even when I zoomed in the most possible. Its not the video its the track with the clips. I want to make the clips bigger by zooming in to it but the maximum zoom only allows so little

ss: 

https://gyazo.com/9c06cf5a3ba776de95a2f27eec135278

Hopefully someone can help.

**Comment by JacksonRG** [comment]
Hi, @Bropii `ctrl+scrollwheel` or the `+/-` buttons will allow you to zoom in further than the zoom slider allows.

In addition I'm currently working on a fix so that the timeline will shorten when a project isn't as long as it used to be.

**Comment by JacksonRG** [comment]
@Bropii Let me know if that didn't fix your problem, but I'll close this issue for now.
