### ISSUE TITLE
OPENSHOT I MESSED UP. NEED HELP

### ISSUE THREAD

**Issue by Bropii** [OpenShot/openshot-qt#4669]
I messed around with some buttons and now my openshot looks like this
https://gyazo.com/f0ac3b55d57b1a16e31b52ee759ed4bf

How can i fix this?

**Comment by JacksonRG** [comment]
I'm guessing you solved this as you closed the issue. But for anyone else in this position: you can click on `View > Views > Simple View` in the top left toolbar to return OpenShot to it's default layout.
