### ISSUE TITLE
 accented characters in name of file or directory

### ISSUE THREAD

**Issue by jpboussac** [OpenShot/openshot-qt#467]
Hello

Impossible to open a OSP if there are accented characters in name of file or directory
example : "export_path": "/home/myname/Vidéos"

Thank you

Jean-Paul BOUSSAC

**Comment by DylanC** [comment]
@jpboussac - Does this issue exist in OpenShot v2.3.4? Please confirm.

**Comment by AdrienTD** [comment]
@DylanC Yes, the issue still exists in OpenShot v2.3.4.

**Comment by DylanC** [comment]
@AdrienTD - Thanks! I will test in the daily build now.

**Comment by DylanC** [comment]
@jpboussac @AdrienTD - Hi guys, this has been fixed now. Try the latest daily build for your system to confirm. Thanks.

**Comment by DylanC** [comment]
Dup of #677
