### ISSUE TITLE
Video speed error

### ISSUE THREAD

**Issue by kerbinsphere** [OpenShot/openshot-qt#4674]
**Description**
Speeding up videos by 2x cuts them in half

1. Open a .mp4 file in openshot
2. right click -> speed -> fast -> forward -> 2x
3. export as .mp4
4. See error, video will be cut in half

**Expected behavior**
video will be half the length and playing at normal speed. Note that this only occurs AFTER export, it will appear normal in the editor

**System Details**
- OpenShot Version: 2.6.1
- libopenshot Version:  0.2.7
- Platform: Windows-10-10.0.19043
- Processor: Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz, 3000Mhz, 8 Core(s), 8 Logical Processor(s)
- Python version: unknown
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-dev-daily-9077-a86097a3-2b8b05c7-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/rakpwcqslcakx189oszhnd7pkuuuoy63/openshot-qt.zip) (15 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Comment by JacksonRG** [comment]
Just tried to replicate this on Linux and Windows, but couldn't. When you set the speed, could you also put an unaltered clip on the timeline and tell me whether the `time` and `end` properties are different in the properties window?

**Comment by kerbinsphere** [comment]
Hello thank you for replying

yes I can confirm that the time and end values in the properties window
change when sped up and when it's not the end point is at the end of the
clip and the time value stays at 0, when I sped it up the end value
decreased by half and the time value went from 1 at the start of the clip
to 561 at the end. I tested exporting the clip as without modifying it and
had no issues, it seems to only be a problem when sped up.

**Comment by JacksonRG** [comment]
Just to rule out causes, is this happening with any file you try, and any file type? Also does anything change if you change the export settings like frame rate, or video file type exported?

**Comment by kerbinsphere** [comment]
actually it turns out it was only happening with one file, I'm not quite
sure what the problem with it was, but it seems to work fine on other
files, sorry for the trouble

**Comment by JacksonRG** [comment]
@kerbinsphere No, problem. If that's a mission critical file, I'd try re-encoding it with a tool like [handbrake](https://handbrake.fr/).
