### ISSUE TITLE
Update "YouTube" and "YouTube-HD" target options in the "Simple" export video tab

### ISSUE THREAD

**Issue by Trainax** [OpenShot/openshot-qt#4675]
**Describe the new feature:**

I think it would be a nice idea to update and expand the `YouTube` and `YouTube-HD` target profiles in the `Simple` export video tab to follow the official [recommended upload encoding settings](https://support.google.com/youtube/answer/1722171?hl=en) guide since for example at the moment 2K and 4K video export options are not present in the video profile selection in the `Simple` tab.

**Describe the solution you'd like:**

- Move the 720p export options from the `YouTube-HD` to the `YouTube` target menu since YouTube has removed the HD tag from 720p videos in 2020
- Update the already present export options if necessary
- Add 2K and 4K export options
- Add 48, 50 and 60 FPS export options for all video profiles under the `YouTube` and `YouTube-HD` targets

**Describe alternatives you have considered:**

In alternative I think users could continue to manually set the export options (for example for 4K videos) using the `Advanced` tab following the beforementioned guide for recommended upload encoding, but since the paramenters are well explained I think it would be nice to add them all in the `Simple` tab

**Comment by JacksonRG** [comment]
Thanks for pointing this out! We can make sure we're matching the youtube formats.
