### ISSUE TITLE
WARNING webengine: WebEngine backend still not ready after # retries.

### ISSUE THREAD

**Issue by Ednaordinary** [OpenShot/openshot-qt#4676]
**Describe the bug:**
Openshot starts, but is giving me the error in the terminal that the webengine is failing (qt webengine?), and the timeline panel is failing to render

**Steps to reproduce the behavior:**
1. Install the daily build of (X)Ubuntu Jammy (22.04)
2. Update (sudo apt update && sudo apt upgrade)
3. Install linux kernel 5.15 low-latency (via Mailing Kernel PPA)
4. Run openshot (appimage)

**Expected behavior:**
Openshot opens perfectly, with timelines rendering

**System Details:**
- OpenShot Version [e.g. 2.4.3]: Stable Openshot 2.6.1 AppImage, AND Daily AppImage 9097
- Operating System / Distro: Xubuntu 22.04 with linux kernel 5.15

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/8054754/openshot-qt.log)

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

WARNING webengine: WebEngine backend still not ready after 5 retries.
WARNING webengine: WebEngine backend still not ready after 5 retries.
WARNING webengine: WebEngine backend still not ready after 5 retries.
etc

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.
![image](https://user-images.githubusercontent.com/88869424/153733341-9c101261-4715-47d6-be56-b782b2d72e7f.png)

**Comment by JacksonRG** [comment]
Have you tried installing openshot? I'm just wondering if we can narrow this down to an Appimage problem

**Comment by Ednaordinary** [comment]
> Have you tried installing openshot? I'm just wondering if we can narrow this down to an Appimage problem

@JacksonRG 
Yes I have, the version in the Ubuntu jammy repo and in the stable ppa repo (hirsute) fail to launch at all, where the appimage only fails to render the timeline. Should have mentioned that

**Comment by Ednaordinary** [comment]
After looking into it further, the error seems to be in
src/windows/views/webview_backend/webengine.py
at the following section:
`    def run_js(self, code, callback=None, retries=0):
        """Run JS code async and optionally have a callback for response"""
        # Check if document.Ready has fired in JS
        if not self.document_is_ready:
            # Not ready, try again in a few moments
            if retries == 0:
                # Log the script contents, the first time
                log.debug(
                    "run_js() called before document ready event. Script queued: %s",
                    code)
            elif retries % 5 == 0:
                log.warning(
                    "WebEngine backend still not ready after %d retries.",
                    retries)
            else:
                log.debug("Script queued, %d retries so far", retries)
            QTimer.singleShot(200, partial(self.run_js, code, callback, retries + 1))
            return None
        # Execute JS code
        if callback:
            return self.page().runJavaScript(code, callback)
        # else
        return self.page().runJavaScript(code)`
Which means something called "document.Ready" did not fire in JS, and the timeline did not render because of that

I also tried reinstalling and installing different versions of PyQt5 and PyQtwebengine, which did not work

**Comment by Bert-H** [comment]
Duplicate issue of 4633 & 4657.
As mentioned under #4633, this issue only started happening in Fedora35. It is fine before that.
Appears to be some issue between the QtWebengine and Openshot, as mentioned here.

**Comment by AppTester7** [comment]
I have the same problem using .AppImage version 2.6.1 on opensuse tumbleweed

Here are the 3 logs in a .7z zip archive
[openshot LOGS.zip](https://github.com/OpenShot/openshot-qt/files/8512906/openshot.LOGS.zip)



OS Details:

Operating System: openSUSE Tumbleweed 20220414
KDE Plasma Version: 5.24.4
KDE Frameworks Version: 5.93.0
Qt Version: 5.15.2
Kernel Version: 5.17.2-1-default (64-bit)
Graphics Platform: Wayland
Processors: 4 × Intel® Core™ i5-3570K CPU @ 3.40GHz
Memory: 15.3 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 4000

**Comment by Ednaordinary** [comment]
Like stated in a different issue, adding --no-sandbox seems to work, but it gives you a warning (ignore it) and audio doesn't seem to work for me

**Comment by MoiCJarod** [comment]
Same problem for me (just after an upgrade from Xubuntu 20.04 to 22.04) and the workaround told by Ednaordinary works (and sound is working), but it seemed that OpenShot is only trying to open a file named --no-sandbox and can't achieve it (maybe using anything not known instead of --no-sandbox would work ?). Bytheway it makes the bug not happening when using it. Thx :+1:  !

**Comment by Ednaordinary** [comment]
> Same problem for me (just after an upgrade from Xubuntu 20.04 to 22.04) and the workaround told by Ednaordinary works (and sound is working), but it seemed that OpenShot is only trying to open a file named --no-sandbox and can't achieve it (maybe using anything not known instead of --no-sandbox would work ?). Bytheway it makes the bug not happening when using it. Thx :+1:  !

@MoiCJarod 

Thanks for your comment!
--no-sandbox does two things (as far as I know), the first being some internal signal that tells openshot not to sandbox something. The second is openshot trying to open anything listed after argument 1 as a file name, even when there's no file, in this case "--no-sandbox". Using just any non-existent file wouldn't work, because Qt's WebEngine would still give out errors because it is sandboxed

**Comment by MoiCJarod** [comment]
Ok, it explains the quite weird behavior. Thx for the explanation.

**Comment by ChuckNorrison** [comment]
i faced the same behaviour with my fresh upgraded Ubuntu 22.04. Replaced my appimage with current version 2.6.1, but doesn solved the issue.

**Comment by wiwichips** [comment]
I can also report its still present on Ubuntu 22.04 with version 2.6.1

**Comment by erikaheidi** [comment]
Also reporting that it is happening with my Ubuntu 22.04 system, I tried a system upgrade and it didn't solve the problem. Using the latest stable AppImage 2.6.1 .

**Comment by autay27** [comment]
I am also experiencing this issue and --no-sandbox still makes it work

**Comment by ajesaramos** [comment]
For anyone using Kali (or debian based distros perhaps) adding --no-sandbox fixes the rendering of timeline.

**Comment by swarmcommerce** [comment]
I have installed OpenShot AppImage ver 3.1.1 on Google ChromeOS Version 113.0.5672.134 (Official Build) (64-bit) / Debian 11 (Bullseye)

Note that the AppImage file is not installed in the root directory, and when I run it from the terminal, I get the following output:

    ~/appimage_files$ ./OpenShot.AppImage &
    [1] 809
    ~/appimage_files$ Loaded modules from: /tmp/.mount_OpenShI4wpOn/usr/bin
    INFO app: ------------------------------------------------
    INFO app:             Wed Jun 14 15:57:36 2023            
    INFO app:               Starting new session              
    INFO app: ------------------------------------------------
    INFO app:             OpenShot (version 3.1.1)            
    INFO app: ------------------------------------------------
    INFO app: openshot-qt version: 3.1.1
    INFO app: libopenshot version: 0.3.2
    INFO app: platform: Linux-5.15.103-17409-g07029265d738-x86_64-with-glibc2.4
    INFO app: processor: 
    INFO app: machine: x86_64
    INFO app: python version: 3.8.10
    INFO app: qt5 version: 5.12.8
    INFO app: pyqt5 version: 5.14.1
    INFO app: Frozen version info from build server:
    {
        "build_name": "OpenShot-v3.1.1-release-candidate-11392-7100dc7a-e47da46f",
        "date": "2023-04-20 05:28",
        "libopenshot": {
            "CI_COMMIT_REF_NAME": "release-20230417",
            "CI_COMMIT_SHA": "7100dc7a94a72cbddab135e9dde7c161a6ba056b",
            "CI_JOB_ID": "36000",
            "CI_PIPELINE_ID": "11389",
            "CI_PROJECT_NAME": "libopenshot",
            "SO": "25",
            "VERSION": "0.3.2"
        },
        "libopenshot-audio": {
            "CI_COMMIT_REF_NAME": "release-20230417",
            "CI_COMMIT_SHA": "e47da46fea0781941aacf86ece2bbe976f8a030a",
            "CI_JOB_ID": "35923",
            "CI_PIPELINE_ID": "11367",
            "CI_PROJECT_NAME": "libopenshot-audio",
            "SO": "9",
            "VERSION": "0.3.2"
        },
        "openshot-qt": {
            "CI_COMMIT_REF_NAME": "release-20230417",
            "CI_COMMIT_SHA": "5416a16b93923d7488d62ae23073e57c8c961e55",
            "CI_JOB_ID": "36012",
            "CI_PIPELINE_ID": "11392",
            "CI_PROJECT_NAME": "openshot-qt",
            "SO": null,
            "VERSION": "3.1.1"
        }
    }
    INFO project_data: Setting profile to HD 720p 30 fps
    INFO project_data: Apply default audio playback settings: 48000, 2 channels
    INFO app: checking babl_ext_path: /tmp/.mount_OpenShI4wpOn/usr/bin/lib/babl-ext
    INFO app: setting BABL_PATH: /tmp/.mount_OpenShI4wpOn/usr/bin/lib/babl-ext
    Screen XWAYLAND0
       devicePixelRatio: 3.0
       logicalDotsPerInch: 85.0
       physicalDotsPerInch: 85.08520638012907
       availableSizes: PyQt5.QtCore.QSize(1280, 720)
    INFO language: Qt Detected Languages: ['en-US']
    INFO language: LANG Environment Variable: en_US.UTF-8
    INFO language: LOCALE Environment Variable: 
    INFO language: OpenShot Preference Language: Default
    INFO app: Setting font to /tmp/.mount_OpenShI4wpOn/usr/bin/images/fonts/Ubuntu-R.ttf
    INFO app: Setting custom dark theme
    INFO logger_libopenshot: Connecting to libopenshot with debug port: 5556
    INFO ui_util: Initializing UI for MainWindow
    INFO thumbnail: Starting thumbnail server listening on ('127.0.0.1', 56401)
    Sandboxing disabled by user.
    Installed Qt WebEngine locales directory not found at location /tmp/.mount_OpenShI4wpOn/usr/bin/translations/qtwebengine_locales. Trying application directory...
    Qt WebEngine locales directory not found at location /tmp/.mount_OpenShI4wpOn/usr/bin/qtwebengine_locales. Trying fallback directory... Translations MAY NOT not be correct.
    Path override failed for key ui::DIR_LOCALES and path '/home/matgarland/.openshot'
    [0614/155739.082561:WARNING:resource_bundle_qt.cpp(116)] locale_file_path.empty() for locale 
    Installed Qt WebEngine locales directory not found at location /tmp/.mount_OpenShI4wpOn/usr/bin/translations/qtwebengine_locales. Trying application directory...
    Qt WebEngine locales directory not found at location /tmp/.mount_OpenShI4wpOn/usr/bin/qtwebengine_locales. Trying fallback directory... Translations MAY NOT not be correct.
    Path override failed for key ui::DIR_LOCALES and path '/home/matgarland/.QtWebEngineProcess'
    [0614/155739.158039:WARNING:resource_bundle_qt.cpp(116)] locale_file_path.empty() for locale 
    INFO webengine: WebEngine backend initializing
    INFO transition_model: updating transitions model.
    INFO version: Found current version: {'error_rate_unstable': 0.05, 'error_rate_stable': 0.5, 'openshot_version': '3.1.1', 'trans_rate_stable': 0.01, 'trans_rate_unstable': 0.001}
    INFO effects_model: updating effects model.
    INFO emoji_model: updating emoji model.
    INFO sentry: Sentry initialized for 'production': 0.5 sample rate, 0.01 transaction rate
    INFO main_window: InitCacheSettings
    INFO main_window: cache-mode: CacheMemory
    INFO main_window: cache-limit-mb: 512
    INFO main_window: cache-ahead-percent: 0.7
    INFO main_window: cache-preroll-min-frames: 24
    INFO main_window: cache-preroll-max-frames: 48
    INFO main_window: cache-max-frames: 600
    INFO main_window: Creating CacheMemory object with 536870912 byte limit
    INFO preview_thread: QThread Start Method Invoked
    INFO main_window: Cleared temporary files: /home/matgarland/.openshot_qt/thumbnail
    INFO main_window: Cleared temporary files: /home/matgarland/.openshot_qt/blender
    INFO main_window: Cleared temporary files: /home/matgarland/.openshot_qt/title
    INFO main_window: updateStatusChanged
    INFO main_window: recover_backup
    INFO project_data: Setting profile to HD 720p 30 fps
    INFO project_data: Apply default audio playback settings: 48000, 2 channels
    INFO video_widget: Load: Set video widget display aspect ratio to: 1.7777777910232544
    INFO video_widget: Set video widget pixel aspect ratio to: 1.0
    INFO main_window: updateStatusChanged
    INFO timeline: Adjusting max size of preview image: PyQt5.QtCore.QSize(1764, 996)
    WARNING preview_thread: Your active audio device (||) does not match OpenShot (). Adjusting your 'Preferences->Playback->Audio Device' to match your active audio device: ||
    INFO timeline: Adjusting max size of preview image: PyQt5.QtCore.QSize(1668, 936)
    INFO webengine: Registering WebChannel connection with WebEngine
    WARNING webengine: WebEngine backend still not ready after 5 retries.
    WARNING webengine: WebEngine backend still not ready after 5 retries.
    WARNING webengine: WebEngine backend still not ready after 5 retries.
    WARNING webengine: WebEngine backend still not ready after 5 retries.
    WARNING webengine: WebEngine backend still not ready after 5 retries.
    WARNING webengine: WebEngine backend still not ready after 5 retries.
    WARNING webengine: WebEngine backend still not ready after 5 retries.
    WARNING webengine: WebEngine backend still not ready after 5 retries.
    WARNING webengine: WebEngine backend still not ready after 5 retries.
    Property 'modal'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'windowModality'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'enabled'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'geometry'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'frameGeometry'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'normalGeometry'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'x'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'y'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'pos'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'frameSize'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'size'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'width'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'height'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'rect'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'childrenRect'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'childrenRegion'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'sizePolicy'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'minimumSize'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'maximumSize'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'minimumWidth'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'minimumHeight'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'maximumWidth'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'maximumHeight'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'sizeIncrement'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'baseSize'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'palette'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'font'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'cursor'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'mouseTracking'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'tabletTracking'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'isActiveWindow'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'focusPolicy'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'focus'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'contextMenuPolicy'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'updatesEnabled'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'visible'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'minimized'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'maximized'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'fullScreen'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'sizeHint'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'minimumSizeHint'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'acceptDrops'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'windowOpacity'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'windowModified'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'toolTip'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'toolTipDuration'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'statusTip'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'whatsThis'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'accessibleName'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'accessibleDescription'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'layoutDirection'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'autoFillBackground'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'styleSheet'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'locale'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'windowFilePath'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'inputMethodHints'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'title'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'url'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'selectedText'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'hasSelection'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'zoomFactor'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    INFO webview: Qt Ready
    INFO webview: Angular Ready

After reading through the errors, I copied the .AppImage file to the root directory and re-ran the program. The multiple line error, "WARNING webengine: WebEngine backend still not ready after 5 retries" is noticeably absent from the following log. Running the application from the root directory has eradicated the aforementioned warning.

Having said that, the spurious, " Property X of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!" error messages still persist.

Food for thought...

    ~$ ./OpenShot.AppImage 
    Loaded modules from: /tmp/.mount_OpenShOMw1k8/usr/bin
    INFO app: ------------------------------------------------
    INFO app:             Wed Jun 14 16:27:25 2023            
    INFO app:               Starting new session              
    INFO app: ------------------------------------------------
    INFO app:             OpenShot (version 3.1.1)            
    INFO app: ------------------------------------------------
    INFO app: openshot-qt version: 3.1.1
    INFO app: libopenshot version: 0.3.2
    INFO app: platform: Linux-5.15.103-17409-g07029265d738-x86_64-with-glibc2.4
    INFO app: processor: 
    INFO app: machine: x86_64
    INFO app: python version: 3.8.10
    INFO app: qt5 version: 5.12.8
    INFO app: pyqt5 version: 5.14.1
    INFO app: Frozen version info from build server:
    {
        "build_name": "OpenShot-v3.1.1-release-candidate-11392-7100dc7a-e47da46f",
        "date": "2023-04-20 05:28",
        "libopenshot": {
            "CI_COMMIT_REF_NAME": "release-20230417",
            "CI_COMMIT_SHA": "7100dc7a94a72cbddab135e9dde7c161a6ba056b",
            "CI_JOB_ID": "36000",
            "CI_PIPELINE_ID": "11389",
            "CI_PROJECT_NAME": "libopenshot",
            "SO": "25",
            "VERSION": "0.3.2"
        },
        "libopenshot-audio": {
            "CI_COMMIT_REF_NAME": "release-20230417",
            "CI_COMMIT_SHA": "e47da46fea0781941aacf86ece2bbe976f8a030a",
            "CI_JOB_ID": "35923",
            "CI_PIPELINE_ID": "11367",
            "CI_PROJECT_NAME": "libopenshot-audio",
            "SO": "9",
            "VERSION": "0.3.2"
        },
        "openshot-qt": {
            "CI_COMMIT_REF_NAME": "release-20230417",
            "CI_COMMIT_SHA": "5416a16b93923d7488d62ae23073e57c8c961e55",
            "CI_JOB_ID": "36012",
            "CI_PIPELINE_ID": "11392",
            "CI_PROJECT_NAME": "openshot-qt",
            "SO": null,
            "VERSION": "3.1.1"
        }
    }
    INFO project_data: Setting profile to HD 720p 30 fps
    INFO project_data: Apply default audio playback settings: 48000, 2 channels
    INFO app: checking babl_ext_path: /tmp/.mount_OpenShOMw1k8/usr/bin/lib/babl-ext
    INFO app: setting BABL_PATH: /tmp/.mount_OpenShOMw1k8/usr/bin/lib/babl-ext
    Screen XWAYLAND0
       devicePixelRatio: 3.0
       logicalDotsPerInch: 85.0
       physicalDotsPerInch: 85.08520638012907
       availableSizes: PyQt5.QtCore.QSize(1280, 720)
    INFO language: Qt Detected Languages: ['en-US']
    INFO language: LANG Environment Variable: en_US.UTF-8
    INFO language: LOCALE Environment Variable: 
    INFO language: OpenShot Preference Language: Default
    INFO app: Setting font to /tmp/.mount_OpenShOMw1k8/usr/bin/images/fonts/Ubuntu-R.ttf
    ZmqLogger::Connection - Error binding to tcp://*:5556. Switching to an available port.
    INFO app: Setting custom dark theme
    ZmqLogger::Connection - Error binding to tcp://*:5556. Switching to an available port.
    INFO logger_libopenshot: Connecting to libopenshot with debug port: 5556
    INFO ui_util: Initializing UI for MainWindow
    INFO thumbnail: Starting thumbnail server listening on ('127.0.0.1', 43085)
    Sandboxing disabled by user.
    Installed Qt WebEngine locales directory not found at location /tmp/.mount_OpenShOMw1k8/usr/bin/translations/qtwebengine_locales. Trying application directory...
    Qt WebEngine locales directory not found at location /tmp/.mount_OpenShOMw1k8/usr/bin/qtwebengine_locales. Trying fallback directory... Translations MAY NOT not be correct.
    Path override failed for key ui::DIR_LOCALES and path '/home/matgarland/.openshot'
    [0614/162727.488800:WARNING:resource_bundle_qt.cpp(116)] locale_file_path.empty() for locale 
    Installed Qt WebEngine locales directory not found at location /tmp/.mount_OpenShOMw1k8/usr/bin/translations/qtwebengine_locales. Trying application directory...
    Qt WebEngine locales directory not found at location /tmp/.mount_OpenShOMw1k8/usr/bin/qtwebengine_locales. Trying fallback directory... Translations MAY NOT not be correct.
    Path override failed for key ui::DIR_LOCALES and path '/home/matgarland/.QtWebEngineProcess'
    [0614/162727.564593:WARNING:resource_bundle_qt.cpp(116)] locale_file_path.empty() for locale 
    INFO webengine: WebEngine backend initializing
    INFO transition_model: updating transitions model.
    INFO effects_model: updating effects model.
    INFO emoji_model: updating emoji model.
    INFO main_window: InitCacheSettings
    INFO main_window: cache-mode: CacheMemory
    INFO main_window: cache-limit-mb: 512
    INFO main_window: cache-ahead-percent: 0.7
    INFO main_window: cache-preroll-min-frames: 24
    INFO main_window: cache-preroll-max-frames: 48
    INFO main_window: cache-max-frames: 600
    INFO main_window: Creating CacheMemory object with 536870912 byte limit
    INFO preview_thread: QThread Start Method Invoked
    INFO main_window: Cleared temporary files: /home/matgarland/.openshot_qt/thumbnail
    INFO main_window: Cleared temporary files: /home/matgarland/.openshot_qt/blender
    INFO main_window: Cleared temporary files: /home/matgarland/.openshot_qt/title
    INFO version: Found current version: {'error_rate_unstable': 0.05, 'error_rate_stable': 0.5, 'openshot_version': '3.1.1', 'trans_rate_stable': 0.01, 'trans_rate_unstable': 0.001}
    INFO main_window: updateStatusChanged
    INFO main_window: recover_backup
    INFO project_data: Setting profile to HD 720p 30 fps
    INFO project_data: Apply default audio playback settings: 48000, 2 channels
    INFO video_widget: Load: Set video widget display aspect ratio to: 1.7777777910232544
    INFO video_widget: Set video widget pixel aspect ratio to: 1.0
    INFO main_window: updateStatusChanged
    INFO sentry: Sentry initialized for 'production': 0.5 sample rate, 0.01 transaction rate
    INFO timeline: Adjusting max size of preview image: PyQt5.QtCore.QSize(1668, 936)
    INFO webengine: Registering WebChannel connection with WebEngine
    Property 'modal'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'windowModality'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'enabled'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'geometry'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'frameGeometry'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'normalGeometry'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'x'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'y'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'pos'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'frameSize'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'size'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'width'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'height'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'rect'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'childrenRect'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'childrenRegion'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'sizePolicy'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'minimumSize'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'maximumSize'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'minimumWidth'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'minimumHeight'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'maximumWidth'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'maximumHeight'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'sizeIncrement'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'baseSize'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'palette'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'font'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'cursor'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'mouseTracking'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'tabletTracking'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'isActiveWindow'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'focusPolicy'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'focus'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'contextMenuPolicy'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'updatesEnabled'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'visible'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'minimized'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'maximized'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'fullScreen'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'sizeHint'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'minimumSizeHint'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'acceptDrops'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'windowOpacity'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'windowModified'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'toolTip'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'toolTipDuration'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'statusTip'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'whatsThis'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'accessibleName'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'accessibleDescription'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'layoutDirection'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'autoFillBackground'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'styleSheet'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'locale'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'windowFilePath'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'inputMethodHints'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'title'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'url'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'selectedText'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'hasSelection'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    Property 'zoomFactor'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
    INFO webview: Qt Ready
    INFO webview: Angular Ready
