### ISSUE TITLE
Clip Speed Error

### ISSUE THREAD

**Issue by MrGenie151** [OpenShot/openshot-qt#4677]
**Describe the bug:**
Speeding up clips breaks them. In the preview, speeding them up works as intended. As soon as you export it though, the audio becomes garbled and the video is displaying the exact wrong place in the video.

**Steps to reproduce the behavior:**
1. Get a video, any video.
2. Speed it up AT ALL.
3. Export.
4. Congrats, you have a broken video that you can blame on the editor.

**Expected behavior:**
The exported video should display the clip sped up properly with no garbled sounds and it is the actual content on the clip just sped up.

**System Details:**
- OpenShot Version: 1.6.1
- OS: Linux Mint 19

**Video Proof**
In both this [video](https://www.youtube.com/watch?v=QhDRuGX6LTI) and this [one](https://youtu.be/xunbuXQOYCs), the parts with the garbled audio and clips that do not fit with the current events of the story are caused because of me attempting to speed up clips.

**Comment by JacksonRG** [comment]
How are you speeding up the videos?

Does this happen if you change speed by right clicking on a clip and choosing `time > fast > forward > x2`?

Also could you include timestamps where the messed up audio can be found?

**Comment by MrGenie151** [comment]
> How are you speeding up the videos?
> 
> Does this happen if you change speed by right clicking on a clip and choosing `time > fast > forward > x2`?
> 
> Also could you include timestamps where the messed up audio can be found?

I am right-clicking and doing exactly as you said.
Timestamps wise, [here](https://youtu.be/QhDRuGX6LTI?t=101) is one.
