### ISSUE TITLE
Audio Choppiness With Daily Build 2/13 x64

### ISSUE THREAD

**Issue by Raziel0315** [OpenShot/openshot-qt#4679]
I was asked to report my findings on yesterday's daily build, 2/13 x64, by another tech.

**Describe the bug:**
I downloaded yesterday's daily build and tried it out.  The audio is choppy, but better than it was over the last few builds.  It only seems to be an issue when there is more than 1 video clip.  The choppiness doesn't happen if there is 1 video track and 1 audio track stacked.  I checked the audio in both a project already begun and a completely new project.  I did notice that when the resolution on the second video clip is higher, the choppiness happens more.  The first video clip is 1920 x 1080 resolution.  When the second video clip is 1280 x 720, there is some choppiness.  When the second video clip is 1920 x 1080, the choppiness increases.  Increasing the amount of cache used by the program does not fix this issue.

**Steps to reproduce the behavior:**
Use multiple clips and the audio should sound choppy, as if it's struggling to keep up with the playhead.

**Expected behavior:**
Both audio and video should play normally at a reasonable pace.

**System Details:**
- OpenShot Version e.g. 2.6.1 Daily Build from 2/13 x64
- Operating System / Distro:  Windows 10

**Comment by Raziel0315** [comment]
Upon further inspection, it appears that the issue lies with the cache.  Going by the cache limit indicator, the choppiness starts happening once the playhead has caught up to the end of the cache indicator.  Increasing the amount of cache used by the program doesn't fix it, either.  All that does is increase the amount of the project stored in the cache BEHIND the playhead.  If the cache can lead the playhead more, many problems would be alleviated, I think.

**Comment by JacksonRG** [comment]
Thanks for the feedback! We've been tweaking the cache behaviour. How does the cache behave if you leave Openshot paused for a little while before previewing a section?

**Comment by Raziel0315** [comment]
When the preview is paused, there is a small amount of lead time on the indicator, but the playhead catches up very quickly.  I would say about 5 seconds max.
