### ISSUE TITLE
Animated Title/Picture Frames - Image folder paths Do NOT get updated when performing "Save Project As...".

### ISSUE THREAD

**Issue by Colorjet3** [OpenShot/openshot-qt#4681]
**Describe the bug:**
You have a saved project that you have used the Animated Title (Blender) option to leverage the Picture Frames template.  You now decide to save this project to another folder.  To do this, you open the project and perform File | Save Project As... and save it to another location keeping the same project name.  OpenShot successfully creates the new .osp and the assets folder that goes with it in the new location.  You delete the .osp and the assets content from the previous folder.  You now open the project from the new location and notice that your Picture Frames no longer display the image clips you added.

Upon some debugging I noted that if I click on the .png file in the Project Files tab and check the "File Path:" in the Properties, I see that the path is not updated to reflect the new folder location.

At this time I am able to update the folder path manually ("File Path:") and click update and OpenShot now plays the Picture Frames properly.  I have to do this for each .png file.

**Steps to reproduce the behavior:**
1. Ensure you have Blender installed.
2. Start OpenShot and configure in Preferences to the Blender executable.
3. Import 4 .jpg files.
4. Save your project.
5. Click on Title | Animated titles | Picture Frames template.
6. Keep the File Name as is.
7. For Picture 1, 2, 3, and 4 select one of the 4 images you imported.
8. Click Render.
9. Move this new clip onto your project and play it to ensure it looks good in the Preview.  Not need to Export.
10. Save your project.
11. Restart OpenShot.
12. Open your save project.
13. Click on File | Save Project As.. and save it to another folder.  Keep the same project name.
14. Close OpenShot.
15. Go to the original folder and manually delete the .osp and accompanying assets folder (this is the original project).
16. Start OpenShot and open the project from the new folder location.
17. Play to preview and you will note that the Picture Frames is missing your images.
18. Right click on any of the .png clips in the Project Files tab and select Properties.
19. Verify the File Path:  and you will not that it is still pointing to the original folder location.
20. Update it manually to point to the new folder path and click on Update.
21. You will need to do this for every .png clip.
22. Now your Preview will display the images properly.

**Expected behavior:**
OpenShot should automatically search for these types of clips and update the folder path during the "Save Project As.." process.  The user should not have to update the folder path manually.

**System Details:**
- OpenShot Version:  v2.6.1 dev daily build 9122
- Operating System / Distro: Windows 10 with the latest patches.

**Log Files:**
Can provide logs if needed.

**Exception / Stacktrace:**
Not experiencing any crashes with this process.

**Screenshots:** (Optional)
I can provide screen shots if needed.

**Comment by jonoomph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Blender file paths are not correctly updated when "Save Project As..."](https://trello.com/c/9ZfziAwG/113-blender-file-paths-are-not-correctly-updated-when-save-project-as)

**Comment by Colorjet3** [comment]
This has been fixed in the latest DEV Daily Build.
