### ISSUE TITLE
OpenShot crashes on initial open after installation (Windows 7 64bit)

### ISSUE THREAD

**Issue by awunes** [OpenShot/openshot-qt#4688]
**Describe the bug**
I've been dealing with the "OpenShot 2.6.0 So Sluggish It's Not Useable Anymore #4375" bug. And in an attempt to use the latest build to solve it by deleting the contents of the "C:\Users\sysadmin\.openshot_qt" folder. I came across this issue with the latest daily build. (actually it happens with the last 2 daily builds - also tried: OpenShot-v2.6.1-dev-daily-9122-f2b89e32-2b8b05c7-x86_64 and the 32bit ver as well :cry: 

**Steps to reproduce the behavior:**
1. Delete the .openshot_qt folder and install latest daily build
2. Attempt to open the program
3. Crash occurs soon after the program opens and usually before you can click hide tutorial or next

**Expected behavior**
The program to continue running and not crash.
I'll add a quick video of what happens soon. rebooting first - reboot had no effect on solution. Also need to install previous version of OpenShot to get proper file format as the system won't accept mkv file format

**System Details**
- OpenShot Version: 2.6.1-dev
- libopenshot Version:  0.2.7-dev
- Platform: Windows-7-6.1.7601-SP1
- Processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-dev-daily-9138-f2b89e32-2b8b05c7-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/ak41m1vzdz7olxg68r034pwn3jmpd0is/openshot-qt.zip) (69 KB)
- libopenshot.log: File too small or empty (not uploaded) *following are it's contents*
```
    ------------------------------------------
    libopenshot logging: Fri Feb 18 19:16:17 2022
    ------------------------------------------
    ------------------------------------------
    libopenshot logging: Fri Feb 18 19:18:53 2022
    ------------------------------------------
    ------------------------------------------
    libopenshot logging: Fri Feb 18 19:25:55 2022
    ------------------------------------------
```

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)

https://user-images.githubusercontent.com/31239393/154786147-2a37de51-39cf-4a81-82f9-38b0e427a73e.mp4

**Comment by DanPinGF** [comment]
It happens to me, too, but only sometimes.  I'm on Windows 11, but consider this a long-term issue as it has been happening since 2.5x (at the most).

**Comment by DanPinGF** [comment]
It doesn't just happen on first-use, though. I've been seeing this access-violation crash sometimes when I launch OpenShot, and the report logs indicate a fault in libopenshot.dll
