### ISSUE TITLE
voice over narrations

### ISSUE THREAD

**Issue by rayandlise** [OpenShot/openshot-qt#469]
I noticed that both Filmora and VideoPad have the ability to do voice over narrations of the video - it opens a window with the video and then a record button so narration can go at specific places in the video -- like going subtitles. 
 It seems to be an easy process to code and would be useful with OpenShot.   
Any chance of coding such a feature into OpenShot  in the near future?  (I have done some coding in the past in C but would need some pointers to contribute much).

**Comment by JtLively** [comment]
Thanks for the feature request.
@jonoomph Would be the best to answer that.
In the meantime, I'd suggest exporting your completed video, recording a narration in Audacity or Qtractor, and importing that narration back into your OpenShot project as a workaround.

**Comment by TharenaMelishka** [comment]
Dragging this open but sleeping issue back into daylight.  @jonoomph was the best to answer 2 years ago, but that was then, this is now.   Any chance on recording voiceover coming to OpenShot?

**Comment by ruidazeng** [comment]
Would really love to have voiceover
