### ISSUE TITLE
Openshot (2.0.5) Beta 2 won't start on Ubuntu 15.10 64 bit

### ISSUE THREAD

**Issue by gmellini** [OpenShot/openshot-qt#47]
After today upgrade on Ubuntu 15.10 (64bit) using PPA, Openshot stopped working.
Launching from terminal I see some error on module import

gmellini@jellyfish:~$ /usr/bin/launch-openshot
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
launch-openshot:INFO ------------------------------------------------
launch-openshot:INFO    OpenShot (version 2.0.5)
launch-openshot:INFO ------------------------------------------------
    language:INFO Qt Detected Languages: ['it']
    language:INFO LANG Environment Variable: it_IT.UTF-8
    language:INFO LOCALE Environment Variable: it_IT
    language:INFO Attempting to load qt_it_IT.UTF-8 in '/usr/share/qt5/translations'
    language:INFO Successfully loaded qt_it_IT.UTF-8 in '/usr/share/qt5/translations'
    language:INFO Attempting to load it_IT.UTF-8/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Attempting to load it/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Successfully loaded it/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Exiting translation system (since we successfully loaded: it_IT.UTF-8)
      logger:ERROR Traceback (most recent call last):
      logger:ERROR   File "/usr/bin/launch-openshot", line 77, in <module>
      logger:ERROR main()
      logger:ERROR   File "/usr/bin/launch-openshot", line 70, in main
      logger:ERROR app = OpenShotApp(sys.argv)
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 66, in __init__
      logger:ERROR self.project = project_data.ProjectDataStore()
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot_qt/classes/project_data.py", line 57, in __init__
      logger:ERROR self.new()
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot_qt/classes/project_data.py", line 253, in new
      logger:ERROR import openshot
      logger:ERROR ImportError
      logger:ERROR :
      logger:ERROR No module named 'openshot'
gmellini@jellyfish:~$ 

Beta1 started without problems, so the problem appeared after beta2 update
Let me know if you need more information
Giovanni

**Comment by jonoomph** [comment]
Okay, thanks for the heads up. I'll give this a test. I am also in the process of upgrading the PPA with improved packages. So, expect a few updates over the next day or two... and I'll make sure it's working properly. =)

**Comment by jarlarntzen** [comment]
Ok. I had no trouble running Openshot 2.0.5 on Ubuntu 14.04 LTS 64 bit.
Starts without a hitch here.

**Comment by nwgat** [comment]
try running it with 
`python3 /usr/lib/python3/dist-packages/openshot_qt/launch-openshot`

**Comment by jarlarntzen** [comment]
Although it starts without any problems I'm failing to capture the full log as it's spewed out during the launch. Anyone got any tips here? I tried naively: `$launch-openshot | nano` but that didn't help.

**Comment by jonoomph** [comment]
I have updated the Debian packages used by the daily PPA (they are much improved due to help from our new Debian packager, Ghislain). I have manually tested them (on Ubuntu 14.04 and 15.04), and they seem to work great. You should also have a launcher created automatically. To manually launch this newly packaged version, run the following command (the old launch-openshot command is gone):
```
openshot-qt 
```
![ubuntu_15_04_installing](https://cloud.githubusercontent.com/assets/5551883/12473158/474fe494-bfd5-11e5-9ede-ae50ec425520.png)

![ubuntu_15_04_launcher](https://cloud.githubusercontent.com/assets/5551883/12473254/3876fca4-bfd6-11e5-8664-b902b82a6091.png)

**Comment by gmellini** [comment]
Again problem on Ubuntu 15.10 64bit
Now, after update, the problem is different but the result is the same, Openshot won't start.
Follow the new command line output, seems now a cast error:

gmellini@jellyfish:~$ openshot-qt 
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
 openshot-qt:INFO ------------------------------------------------
 openshot-qt:INFO    OpenShot (version 2.0.5)
 openshot-qt:INFO ------------------------------------------------
    language:INFO Qt Detected Languages: ['it']
    language:INFO LANG Environment Variable: it_IT.UTF-8
    language:INFO LOCALE Environment Variable: it_IT
    language:INFO Attempting to load qt_it_IT.UTF-8 in '/usr/share/qt5/translations'
    language:INFO Successfully loaded qt_it_IT.UTF-8 in '/usr/share/qt5/translations'
    language:INFO Attempting to load it_IT.UTF-8/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Attempting to load it/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Successfully loaded it/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Exiting translation system (since we successfully loaded: it_IT.UTF-8)
project_data:INFO Setting default profile to HDV 720 24p
         app:INFO Setting font to /usr/lib/python3/dist-packages/openshot_qt/images/fonts/Ubuntu-R.ttf
         app:INFO Setting custom dark theme
    uiparser:DEBUG UI version is 4.0
    uiparser:DEBUG uiname is MainWindow
    uiparser:DEBUG toplevel widget is MainWindow
  properties:DEBUG setting property geometry
  properties:DEBUG setting property sizePolicy
  properties:DEBUG setting property focusPolicy
  properties:DEBUG setting property windowTitle
  properties:DEBUG setting property windowIcon
link SVGID_18_-5 hasn't been detected!
link SVGID_18_-5 hasn't been detected!
link SVGID_22_-5 hasn't been detected!
link SVGID_24_-2 hasn't been detected!
link SVGID_24_-2 hasn't been detected!
  properties:DEBUG setting property documentMode
  properties:DEBUG setting property tabShape
  properties:DEBUG setting property dockNestingEnabled
    uiparser:DEBUG push MainWindow MainWindow
  properties:DEBUG setting property sizePolicy
  properties:DEBUG setting property autoFillBackground
    uiparser:DEBUG push QWidget centralwidget
  properties:DEBUG setting property leftMargin
  properties:DEBUG setting property topMargin
  properties:DEBUG setting property rightMargin
  properties:DEBUG setting property bottomMargin
  properties:DEBUG setting property spacing
  properties:DEBUG setting property pyuicMargins
  properties:DEBUG setting property pyuicSpacing
    uiparser:DEBUG push QGridLayout gridLayout
    uiparser:DEBUG push QVBoxLayout frameWeb
    uiparser:DEBUG pop layout QVBoxLayout frameWeb
    uiparser:DEBUG pop layout QGridLayout gridLayout
    uiparser:DEBUG pop widget QWidget centralwidget
    uiparser:DEBUG new topwidget <windows.main_window.MainWindow object at 0x7ff7aa6b2c18>
  properties:DEBUG setting property geometry
    uiparser:DEBUG push QMenuBar menubar
  properties:DEBUG setting property title
    uiparser:DEBUG push QMenu menuFile
    uiparser:DEBUG pop widget QMenu menuFile
    uiparser:DEBUG new topwidget <PyQt5.QtWidgets.QMenuBar object at 0x7ff7722e5708>
  properties:DEBUG setting property title
    uiparser:DEBUG push QMenu menu_Edit
    uiparser:DEBUG pop widget QMenu menu_Edit
    uiparser:DEBUG new topwidget <PyQt5.QtWidgets.QMenuBar object at 0x7ff7722e5708>
  properties:DEBUG setting property title
    uiparser:DEBUG push QMenu menuTitle
    uiparser:DEBUG pop widget QMenu menuTitle
    uiparser:DEBUG new topwidget <PyQt5.QtWidgets.QMenuBar object at 0x7ff7722e5708>
  properties:DEBUG setting property title
    uiparser:DEBUG push QMenu menuView
  properties:DEBUG setting property title
    uiparser:DEBUG push QMenu menuViews
    uiparser:DEBUG pop widget QMenu menuViews
    uiparser:DEBUG new topwidget <PyQt5.QtWidgets.QMenu object at 0x7ff772211048>
    uiparser:DEBUG pop widget QMenu menuView
    uiparser:DEBUG new topwidget <PyQt5.QtWidgets.QMenuBar object at 0x7ff7722e5708>
  properties:DEBUG setting property title
    uiparser:DEBUG push QMenu menuHelp
    uiparser:DEBUG pop widget QMenu menuHelp
    uiparser:DEBUG new topwidget <PyQt5.QtWidgets.QMenuBar object at 0x7ff7722e5708>
    uiparser:DEBUG pop widget QMenuBar menubar
    uiparser:DEBUG new topwidget <windows.main_window.MainWindow object at 0x7ff7aa6b2c18>
    uiparser:DEBUG push QStatusBar statusbar
    uiparser:DEBUG pop widget QStatusBar statusbar
    uiparser:DEBUG new topwidget <windows.main_window.MainWindow object at 0x7ff7aa6b2c18>
  properties:DEBUG setting property windowTitle
    uiparser:DEBUG push QToolBar toolBar
    uiparser:DEBUG pop widget QToolBar toolBar
    uiparser:DEBUG new topwidget <windows.main_window.MainWindow object at 0x7ff7aa6b2c18>
  properties:DEBUG setting property sizePolicy
  properties:DEBUG setting property windowTitle
    uiparser:DEBUG push QDockWidget dockFiles
    uiparser:DEBUG push QWidget dockWidgetContents
    uiparser:DEBUG push QGridLayout gridLayout_2
    uiparser:DEBUG push QVBoxLayout tabFiles
    uiparser:DEBUG pop layout QVBoxLayout tabFiles
    uiparser:DEBUG pop layout QGridLayout gridLayout_2
    uiparser:DEBUG pop widget QWidget dockWidgetContents
    uiparser:DEBUG new topwidget <PyQt5.QtWidgets.QDockWidget object at 0x7ff772211318>
    uiparser:DEBUG pop widget QDockWidget dockFiles
    uiparser:DEBUG new topwidget <windows.main_window.MainWindow object at 0x7ff7aa6b2c18>
  properties:DEBUG setting property sizePolicy
  properties:DEBUG setting property windowTitle
    uiparser:DEBUG push QDockWidget dockVideo
    uiparser:DEBUG push QWidget dockWidgetContents_2
    uiparser:DEBUG push QGridLayout gridLayout_3
    uiparser:DEBUG push QVBoxLayout tabVideo
    uiparser:DEBUG pop layout QVBoxLayout tabVideo
    uiparser:DEBUG pop layout QGridLayout gridLayout_3
    uiparser:DEBUG pop widget QWidget dockWidgetContents_2
    uiparser:DEBUG new topwidget <PyQt5.QtWidgets.QDockWidget object at 0x7ff772211558>
    uiparser:DEBUG pop widget QDockWidget dockVideo
    uiparser:DEBUG new topwidget <windows.main_window.MainWindow object at 0x7ff7aa6b2c18>
  properties:DEBUG setting property windowTitle
    uiparser:DEBUG push QDockWidget dockTransitions
    uiparser:DEBUG push QWidget dockWidgetContents_3
    uiparser:DEBUG push QGridLayout gridLayout_4
    uiparser:DEBUG push QVBoxLayout tabTransitions
    uiparser:DEBUG pop layout QVBoxLayout tabTransitions
    uiparser:DEBUG pop layout QGridLayout gridLayout_4
    uiparser:DEBUG pop widget QWidget dockWidgetContents_3
    uiparser:DEBUG new topwidget <PyQt5.QtWidgets.QDockWidget object at 0x7ff772211798>
    uiparser:DEBUG pop widget QDockWidget dockTransitions
    uiparser:DEBUG new topwidget <windows.main_window.MainWindow object at 0x7ff7aa6b2c18>
  properties:DEBUG setting property windowTitle
    uiparser:DEBUG push QDockWidget dockEffects
    uiparser:DEBUG push QWidget dockWidgetContents_4
    uiparser:DEBUG push QGridLayout gridLayout_5
    uiparser:DEBUG push QVBoxLayout tabEffects
    uiparser:DEBUG pop layout QVBoxLayout tabEffects
    uiparser:DEBUG pop layout QGridLayout gridLayout_5
    uiparser:DEBUG pop widget QWidget dockWidgetContents_4
    uiparser:DEBUG new topwidget <PyQt5.QtWidgets.QDockWidget object at 0x7ff7722119d8>
    uiparser:DEBUG pop widget QDockWidget dockEffects
    uiparser:DEBUG new topwidget <windows.main_window.MainWindow object at 0x7ff7aa6b2c18>
  properties:DEBUG setting property floating
  properties:DEBUG setting property allowedAreas
  properties:DEBUG setting property windowTitle
    uiparser:DEBUG push QDockWidget dockProperties
    uiparser:DEBUG push QWidget dockPropertiesContent
    uiparser:DEBUG push QGridLayout gridLayout_6
  properties:DEBUG setting property font
  properties:DEBUG setting property text
    uiparser:DEBUG push QLabel lblSelectedItem
    uiparser:DEBUG pop widget QLabel lblSelectedItem
    uiparser:DEBUG new topwidget <PyQt5.QtWidgets.QWidget object at 0x7ff772211ca8>
  properties:DEBUG setting property inputMask
  properties:DEBUG setting property text
  properties:DEBUG setting property placeholderText
    uiparser:DEBUG push QLineEdit txtPropertyFilter
    uiparser:DEBUG pop widget QLineEdit txtPropertyFilter
    uiparser:DEBUG new topwidget <PyQt5.QtWidgets.QWidget object at 0x7ff772211ca8>
    uiparser:DEBUG pop layout QGridLayout gridLayout_6
    uiparser:DEBUG pop widget QWidget dockPropertiesContent
    uiparser:DEBUG new topwidget <PyQt5.QtWidgets.QDockWidget object at 0x7ff772211c18>
    uiparser:DEBUG pop widget QDockWidget dockProperties
    uiparser:DEBUG new topwidget <windows.main_window.MainWindow object at 0x7ff7aa6b2c18>
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property shortcut
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property shortcut
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property shortcut
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property shortcut
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property shortcut
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property shortcut
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property shortcut
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property shortcut
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property shortcut
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property shortcut
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property shortcut
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property shortcut
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property shortcut
  properties:DEBUG setting property menuRole
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property shortcut
  properties:DEBUG setting property menuRole
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property checkable
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property checkable
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property checkable
  properties:DEBUG setting property checked
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property checkable
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property checkable
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property checkable
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property checkable
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property checkable
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property checkable
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property checkable
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property checkable
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property checkable
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property shortcut
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property shortcut
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property shortcut
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property shortcut
  properties:DEBUG setting property checkable
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property shortcut
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property shortcut
  properties:DEBUG setting property visible
  properties:DEBUG setting property checkable
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property shortcut
  properties:DEBUG setting property menuRole
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property visible
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property checkable
  properties:DEBUG setting property text
  properties:DEBUG setting property visible
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property shortcut
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
  properties:DEBUG setting property menuRole
  properties:DEBUG setting property icon
  properties:DEBUG setting property text
  properties:DEBUG setting property toolTip
    uiparser:DEBUG pop widget MainWindow MainWindow
    uiparser:DEBUG new topwidget None
    uiparser:DEBUG add action actionNew to menuFile
    uiparser:DEBUG add action actionOpen to menuFile
    uiparser:DEBUG add action actionRecent_Placeholder to menuFile
    uiparser:DEBUG add action actionSave to menuFile
    uiparser:DEBUG add action actionSaveAs to menuFile
    uiparser:DEBUG add action actionImportFiles to menuFile
    uiparser:DEBUG add action actionProfile to menuFile
    uiparser:DEBUG add action actionExportVideo to menuFile
    uiparser:DEBUG add action actionQuit to menuFile
    uiparser:DEBUG add action actionUndo to menu_Edit
    uiparser:DEBUG add action actionRedo to menu_Edit
    uiparser:DEBUG add action actionPreferences to menu_Edit
    uiparser:DEBUG add action actionTitle to menuTitle
    uiparser:DEBUG add action actionAnimatedTitle to menuTitle
    uiparser:DEBUG add action actionSimple_View to menuViews
    uiparser:DEBUG add action actionAdvanced_View to menuViews
    uiparser:DEBUG add action actionFreeze_View to menuViews
    uiparser:DEBUG add action actionUn_Freeze_View to menuViews
    uiparser:DEBUG add action actionShow_All to menuViews
    uiparser:DEBUG add action actionView_Toolbar to menuView
    uiparser:DEBUG add action actionFullscreen to menuView
    uiparser:DEBUG add action actionExit_Fullscreen to menuView
    uiparser:DEBUG add action menuViews to menuView
    uiparser:DEBUG add action actionHelpContents to menuHelp
    uiparser:DEBUG add action actionReportBug to menuHelp
    uiparser:DEBUG add action actionAskQuestion to menuHelp
    uiparser:DEBUG add action actionTranslate to menuHelp
    uiparser:DEBUG add action actionDonate to menuHelp
    uiparser:DEBUG add action actionAbout to menuHelp
    uiparser:DEBUG add action menuFile to menubar
    uiparser:DEBUG add action menu_Edit to menubar
    uiparser:DEBUG add action menuTitle to menubar
    uiparser:DEBUG add action menuView to menubar
    uiparser:DEBUG add action menuHelp to menubar
    uiparser:DEBUG add action actionNew to toolBar
    uiparser:DEBUG add action actionOpen to toolBar
    uiparser:DEBUG add action actionSave to toolBar
    uiparser:DEBUG add action actionUndo to toolBar
    uiparser:DEBUG add action actionRedo to toolBar
    uiparser:DEBUG add action actionImportFiles to toolBar
    uiparser:DEBUG add action actionProfile to toolBar
    uiparser:DEBUG add action actionFullscreen to toolBar
    uiparser:DEBUG add action actionExit_Fullscreen to toolBar
    uiparser:DEBUG add action actionExportVideo to toolBar
     ui_util:INFO Initializing UI for MainWindow
     ui_util:INFO Binding event MainWindow:actionNew_trigger
     ui_util:INFO Binding event MainWindow:actionOpen_trigger
     ui_util:INFO Binding event MainWindow:actionSave_trigger
     ui_util:INFO Binding event MainWindow:actionUndo_trigger
     ui_util:INFO Binding event MainWindow:actionSaveAs_trigger
     ui_util:INFO Binding event MainWindow:actionImportFiles_trigger
     ui_util:INFO Binding event MainWindow:actionImportImageSequence_trigger
     ui_util:INFO Binding event MainWindow:actionRedo_trigger
     ui_util:INFO Binding event MainWindow:actionRemoveClip_trigger
     ui_util:INFO Binding event MainWindow:actionRemoveTransition_trigger
     ui_util:INFO Binding event MainWindow:actionExportVideo_trigger
     ui_util:INFO Binding event MainWindow:actionUploadVideo_trigger
     ui_util:INFO Binding event MainWindow:actionAddTrack_trigger
     ui_util:INFO Binding event MainWindow:actionPreferences_trigger
     ui_util:INFO Binding event MainWindow:actionPlay_trigger
     ui_util:INFO Binding event MainWindow:actionJumpStart_trigger
     ui_util:INFO Binding event MainWindow:actionRewind_trigger
     ui_util:INFO Binding event MainWindow:actionFastForward_trigger
     ui_util:INFO Binding event MainWindow:actionJumpEnd_trigger
     ui_util:INFO Binding event MainWindow:actionArrowTool_trigger
     ui_util:INFO Binding event MainWindow:actionSnappingTool_trigger
     ui_util:INFO Binding event MainWindow:actionAddMarker_trigger
     ui_util:INFO Binding event MainWindow:actionPreviousMarker_trigger
     ui_util:INFO Binding event MainWindow:actionNextMarker_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowAll_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowVideo_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowAudio_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowImage_trigger
     ui_util:INFO Binding event MainWindow:actionTransitionsShowAll_trigger
     ui_util:INFO Binding event MainWindow:actionTransitionsShowCommon_trigger
     ui_util:INFO Binding event MainWindow:actionEffectsShowAll_trigger
     ui_util:INFO Binding event MainWindow:actionEffectsShowVideo_trigger
     ui_util:INFO Binding event MainWindow:actionEffectsShowAudio_trigger
     ui_util:INFO Binding event MainWindow:actionTimelineZoomIn_trigger
     ui_util:INFO Binding event MainWindow:actionTimelineZoomOut_trigger
     ui_util:INFO Binding event MainWindow:actionTitle_trigger
     ui_util:INFO Binding event MainWindow:actionAnimatedTitle_trigger
     ui_util:INFO Binding event MainWindow:actionFullscreen_trigger
     ui_util:INFO Binding event MainWindow:actionExit_Fullscreen_trigger
     ui_util:INFO Binding event MainWindow:actionAbout_trigger
     ui_util:INFO Binding event MainWindow:actionThumbnailView_trigger
     ui_util:WARNING Icon theme view-preview not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionDetailsView_trigger
     ui_util:WARNING Icon theme view-list-details not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionReportBug_trigger
     ui_util:INFO Binding event MainWindow:actionAskQuestion_trigger
     ui_util:INFO Binding event MainWindow:actionTranslate_trigger
     ui_util:INFO Binding event MainWindow:actionDonate_trigger
     ui_util:INFO Binding event MainWindow:actionHelpContents_trigger
     ui_util:INFO Binding event MainWindow:actionSimple_View_trigger
     ui_util:INFO Binding event MainWindow:actionAdvanced_View_trigger
     ui_util:WARNING Icon theme get-hot-new-stuff not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionFreeze_View_trigger
     ui_util:INFO Binding event MainWindow:actionUn_Freeze_View_trigger
     ui_util:INFO Binding event MainWindow:actionShow_All_trigger
     ui_util:INFO Binding event MainWindow:actionProfile_trigger
     ui_util:INFO Binding event MainWindow:actionAdd_to_Timeline_trigger
     ui_util:INFO Binding event MainWindow:actionPreview_File_trigger
     ui_util:INFO Binding event MainWindow:actionRemove_from_Project_trigger
     ui_util:INFO Binding event MainWindow:actionRemoveTrack_trigger
     ui_util:INFO Binding event MainWindow:actionRemoveMarker_trigger
     ui_util:INFO Binding event MainWindow:actionAddTrackAbove_trigger
     ui_util:INFO Binding event MainWindow:actionAddTrackBelow_trigger
     ui_util:INFO Binding event MainWindow:actionRemoveEffect_trigger
     ui_util:INFO Binding event MainWindow:actionSplitClip_trigger
     ui_util:INFO Binding event MainWindow:actionProperties_trigger
     ui_util:INFO Binding event MainWindow:actionRenameTrack_trigger
 files_model:INFO updating files model.
transition_model:INFO updating transitions model.
timeline_webview:INFO Qt Found!
timeline_webview:INFO $scope.Qt = true;
      logger:ERROR Traceback (most recent call last):
      logger:ERROR   File "/usr/bin/openshot-qt", line 77, in <module>
      logger:ERROR main()
      logger:ERROR   File "/usr/bin/openshot-qt", line 70, in main
      logger:ERROR app = OpenShotApp(sys.argv)
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 114, in __init__
      logger:ERROR self.window = MainWindow()
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot_qt/windows/main_window.py", line 1386, in __init__
      logger:ERROR self.transitionsTreeView = TransitionsListView(self)
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot_qt/windows/views/transitions_listview.py", line 112, in __init__
      logger:ERROR self.refresh_view()
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot_qt/windows/views/transitions_listview.py", line 85, in refresh_view
      logger:ERROR self.transition_model.update_model()
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot_qt/windows/models/transition_model.py", line 118, in update_model
      logger:ERROR trans_name = self.app._tr(trans_name) % suffix_number
      logger:ERROR TypeError
      logger:ERROR :
      logger:ERROR not all arguments converted during string formatting
gmellini@jellyfish:~$

**Comment by jonoomph** [comment]
@gmellini, this is related to a broken translation. Some of the translations have removed a placeholder that Python is expecting. https://translations.launchpad.net/openshot/2.0/+pots/openshot/it/

**Comment by jonoomph** [comment]
@gmellini, it looks like the translations have all been recently fixed. I'm going to merge the latest translations into the OpenShot branch, which should fix this on your next update of the openshot-qt package (might take a few hours for them to show up in the PPA).

**Comment by gmellini** [comment]
ok, just updated.
Now it works :)
Tks
