### ISSUE TITLE
Ubuntu 16.04 No Frame from Blender Output

### ISSUE THREAD

**Issue by JustUseLinux** [OpenShot/openshot-qt#470]
> Blender, the free open source 3D content creation suite is required for this action (http://www.blender.org).
> 
> Please check the preferences in OpenShot and be sure the Blender executable is correct.  This setting should be the path of the 'blender' executable on your computer.  Also, please be sure that it is pointing to Blender version 2.62 or greater.
> 
> Blender Path:
> blender
> 
> Error Output:
> No frame was found in the output from Blender

It doesn't mater if I use OpenShot 1.4.3-1.2 or OpenShot-QT 2.2.0+0+714+106+201612210003~ubuntu16.04.1

Blender 2.78a~1477311627-0thomas~xenial1

I can download Blender from the blender site, and point it at it and it won't work either.

**Comment by JustUseLinux** [comment]
I have a new error, I didn't have before. When attempting to run blender:

> blender
> /usr/lib/blender/blender: error while loading shared libraries: libosdGPU.so.3.0.5: cannot open shared object file: No such file or directory

**Comment by mixedbredie** [comment]
Can you open Inkscape from the Advanced Editor from the simple Titler?
What does ```which blender``` and ```which inkscape``` return?  Are those paths set in the Openshot preferences?
Can you run the __snow__ animation from the Animated Titler?  There is no text in that animation.
Can you run the blend file and python script from the command line and check any errors that are returned?
```/path/to/blender -b /path/to/blend/file.blend -P /path/to/python/script.py```

Regarding your other error - have you got the latest version of opensubdiv installed? See https://launchpad.net/~thomas-schiex/+archive/ubuntu/blender

**Comment by jonoomph** [comment]
Please test again with the latest daily build of OpenShot. I've merged in changes to the text alignment, and updated the minimum version compatibility to 2.78. I've tested all animation on Linux, Mac, and Windows with Blender 2.78 and everything works great.

Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot. _It might take a couple hours for the latest version to appear._

If you have other issues, please file additional bugs for each one. Thanks!

**Comment by JustUseLinux** [comment]
Thanks. How soon will this be in the main version ? The daily build lacks
some effects, and stuff.

**Comment by brylie** [comment]
I am experiencing this issue with OpenShot installation from PPA and Blender version 2.78.c.

Blender path is `/usr/bin/blender`

**Comment by chrismahn** [comment]
hello everybody i found a quick fix.if you place blender folder in /opt/
then create a symbolic link to the /usr/bin/
it should work just fine.

**Comment by JohnnyBizzel** [comment]
> place blender folder in /opt/

Do you mean move files from `/usr/bin` ?

then create a symbolic link to the /usr/bin/

I don't know how to do that. Perhaps r-click make link?

**Comment by brylie** [comment]
It seems like the *path to Blender executable* should be configurable. But admittedly, I don't have OpenShot installed right now.

Also, as I recall, this seemed to me to be related to the Blender version, but may not be (as the original issue indicates).
