### ISSUE TITLE
How do I turn on key frame markers?

### ISSUE THREAD

**Issue by monohydroxy** [OpenShot/openshot-qt#4700]
According to the OpenShot user manual (https://www.openshot.org/user-guide/) under animation, there are "Key frame Markers", described as "Small green tick marks are drawn at all key frame positions (on a clip)".  I don't see those in my project.  How do I turn these key frame markers on?

**System Details:**
- OpenShot Version 2.6.1.  (OpenShot-v2.6.1-release-candidate-8238-59878784-d588dbd6)
- Operating System / Distro: Ubuntu 20.04
- 4K Monitor, at 150%, in case this is a scaling issue.

**Comment by JacksonRG** [comment]
Have you added any keyframes to your project? If you right click a clip and move the playhead somewhere in the middle, then change something like the `alpha` value, you should see one. (If not then that's an issue and we'll see how to fix it.)

Also key frames are now shown as grey shape under the clip. Thanks for pointing that out, we'll make sure the documentation changes.

**Comment by monohydroxy** [comment]
Thanks for your comment.  I definitely added a keyframe.  If I load the project in the daily build "OpenShot-v2.6.1-dev-daily-9246-f29ce408-2b8b05c7-x86_64.AppImage", then I can see the grey diamond.  I can't see it in the stable build "OpenShot-v2.6.1-x86_64.AppImage".  I can't tell what version the documentation is describing, so now I'm not sure if I should see keyframe markers in v2.6.1.

**Comment by r-lippert** [comment]
I think this calls for a 2.6.2 release some time soon. In 2.6.0 and 2.6.1 on Linux, the key frame markers are still missing. Daily 9387 has them.
Trying to scroll to an invisible key frame is possible, but quite annoying.

Thank you!

**Comment by r-lippert** [comment]
A minor suggestion while we're on the topic: When I click on a key frame marker, the properties of the clip owning this key frame are opened. However, if the key frame changes the properties of an effect, I have to click the effect after clicking the key frame.
Clicking on a key frame should open the properties pane containing properties that are affected by this key frame. If the same key frame affects properties of more than one object, it gets a bit more complicated. Most of the times, I would want to keep the already open properties pane.
