### ISSUE TITLE
Application crash while on split clip window

### ISSUE THREAD

**Issue by mrleokarthik** [OpenShot/openshot-qt#471]
Steps to reproduce issue:
Imported a mkv movie into project files. Right click on the file, choose split clip to open Clip window. Play video and quickly in some time Application crash and closes the program.

Windows 10 home
Open shot Version: 2.2.0
Editing MKV File.

**Comment by DylanC** [comment]
@mrleokarthik - Does this issue exist in OpenShot v2.3.4? Please confirm.

**Comment by DylanC** [comment]
Not able to reproduce on v2.4.1.
