### ISSUE TITLE
Error: "std::bad_alloc" while exporting.

### ISSUE THREAD

**Issue by TomoJR** [OpenShot/openshot-qt#4711]
**Describe the bug**
When I try to export my ~30 minute project I receive the error: "std::bad_alloc" between 55 and 75 percent completion.

**Steps to reproduce the behaviour:**
1. Export
2. Wait
3. Wait

**Expected behaviour**
I expected my video to export...

**System Details**
- OpenShot Version: 2.6.1
- libopenshot Version:  Unsure
- Platform: Windows?
- Processor: Intel i5?
- Machine: Aspire 7 Laptop
- Python version: Unsure
- Qt5 version: Unsure
- PyQt5 version: Unsure
- Qt Detected Languages: English? I'm not sure what Qt is...
- LANG Environment Variable: I think I might have ended up on the wrong site I don't know what any of this means...
- LOCALE Environment Variable: I was tryna make a bug report via the OpenShot website, clicked continue after completing Stage 4, then clicked again after nothing happened for a while and it asked me to sign into GitHub but since I don't understand these questions I think I might be in the wrong place...
- Daily Build: I used installed the Daily Build yesterday: the 4th of March.

**Log Files**
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/8191226/openshot-qt.log)

**Comment by TomoJR** [comment]
This probably isn't helpful at all but I asked on the subreddit and was told to make a bug report. Sorry.

https://www.reddit.com/r/OpenShot/comments/t3ijl6/when_i_try_to_export_i_get_stdbad_alloc/

**Comment by JacksonRG** [comment]
@TomoJR Don't worry about those fields. Usually we pull that info out of the log file you attach.

Is this happening with all file types, or only certain ones? Also, could you include a screenshot of your `cache` and `performance` tabs in the preferences menu? (ctrl+shift+p to open that)

**Comment by TomoJR** [comment]
@JacksonRG I have only tried to export the video in MP4 but now that you've mentioned it I'll try MP2.

![Preferences 1](https://user-images.githubusercontent.com/101016296/157237209-3633f084-c42b-40a8-9bde-3d7889fdc7dd.png)
![Preferences 2](https://user-images.githubusercontent.com/101016296/157237227-972af783-e703-4f9a-8a60-aa609c5b0850.png)
