### ISSUE TITLE
Crashes whole computer when rendering

### ISSUE THREAD

**Issue by Chubby-Unicorn** [OpenShot/openshot-qt#4714]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**
1. Import MP4 file
2. Cut MP4 file into a 1.5 minute section
3. Export to 1080p 16:9 -24 fps (same as the source)
4. repeat export steps until the computer shuts down suddenly 

**Expected behavior**
the video should export and not crash at all

**System Details**
- OpenShot Version: 2.4.3+dfsg1-1
- libopenshot Version:  ?
- Platform: Linux Mint 20.3
- Processor: AMD Ryzen 5 3600
- GPU: 3080 TI Founders edition
- GPU Driver: Nvidea proprietary drivers
- Machine: ??
- Python version: 2.7.17-4 | 3.8.2-0ubuntu2
- Qt5 version: --
- PyQt5 version: --
- Qt Detected Languages: --
- LANG Environment Variable: --
- LOCALE Environment Variable: --
- Daily Build: 2.4.3+dfsg1-1 (latest version available over apt-get)
   (latest build from the website does not display correctly at all)

**Log Files**
N/A

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by JacksonRG** [comment]
The issue description says you're running openshot version 2.4.3. Does this issues still occur if you download the latest release, or daily build of openshot?

The release and daily build can both be found here:
https://www.openshot.org/download/

**Comment by Chubby-Unicorn** [comment]
I found a version that renders and works properly so far. (2.6.0-dev) The others I downloaded directly from the downloads page looked like the image below. It was probably a power management issue on NVIDIAs end anyway, Thanks for the help anyway.  


![Screenshot from 2022-03-09 11-32-08](https://user-images.githubusercontent.com/24718109/158134905-13c20de2-ab47-49e5-a272-41a0a59aba0f.png)
