### ISSUE TITLE
Crashes when trying to import webm

### ISSUE THREAD

**Issue by cf8geek** [OpenShot/openshot-qt#4715]
**Describe the bug**
OpenShot crashes when trying to import webm video(s).

**Steps to reproduce the behavior:**
1. Click green + button
2. Navigate to a webm video file
3. Double-click on the file
4. OpenShot crashes
5. Try again using shift-click to select multiple, and using [enter] key on keyboard vs clicking "open" button; all yield same behavior (crash)

**Expected behavior**
OpenShot should import the file(s) without crashing.

**System Details**
- OpenShot Version: 2.6.1-dev
- libopenshot Version:  0.2.7-dev
- Platform: Linux-5.4.0-100-generic-x86_64-with-Ubuntu-20.04-focal
- Processor: x86_64
- Machine: x86_64
- Python version: 3.6.9
- Qt5 version: 5.9.5
- PyQt5 version: 5.10.1
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: en_US.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-dev-daily-9246-f29ce408-2b8b05c7-x86_64.AppImage

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/o5hlhgpq42bxw2bfklkd25dskspsug5v/openshot-qt.zip) (4 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/o5hlhgpq42bxw2bfklkd25dskspsug5v/libopenshot.zip) (7 KB)

**Exception / Stacktrace**
```/tmp/.mount_5kpDci/usr/bin/libavutil.so.55 av_image_copy                            0x29e  [0x7fce6960e77e]
/tmp/.mount_5kpDci/usr/bin/libopenshot.so.21 openshot::FFmpegReader::GetAVFrame()     0x1bc  [0x7fce51eae49c]
/tmp/.mount_5kpDci/usr/bin/libopenshot.so.21 openshot::FFmpegReader::CheckFPS()       0x110  [0x7fce51eaf830]
/tmp/.mount_5kpDci/usr/bin/libopenshot.so.21 openshot::FFmpegReader::UpdateVideoInfo() 0x5b0  [0x7fce51eb2180]
/tmp/.mount_5kpDci/usr/bin/libopenshot.so.21 openshot::FFmpegReader::Open()           0x109a  [0x7fce51eb3a1a]
/tmp/.mount_5kpDci/usr/bin/libopenshot.so.21 openshot::FFmpegReader::FFmpegReader(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) 0x4b8  [0x7fce51eb5678]
/tmp/.mount_5kpDci/usr/bin/libopenshot.so.21 openshot::Clip::Clip(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) 0x5ad  [0x7fce51e8c90d]
/tmp/.mount_5kpDci/usr/bin/lib/_openshot.so                                          0xc2daa  [0x7fce58317daa]
/tmp/.mount_5kpDci/usr/bin/libpython3.6m.so.1.0 PyCFunction_Call                         0xc1  [0x7fce7caf2761]
/tmp/.mount_5kpDci/usr/bin/libpython3.6m.so.1.0 _PyEval_EvalFrameDefault                 0x76e0  [0x7fce7ca63b20]
/tmp/.mount_5kpDci/usr/bin/libpython3.6m.so.1.0                                          0x17ba0f  [0x7fce7ca5aa0f]
/tmp/.mount_5kpDci/usr/bin/libpython3.6m.so.1.0 _PyFunction_FastCallDict                 0x1e4  [0x7fce7ca5ad34]
/tmp/.mount_5kpDci/usr/bin/libpython3.6m.so.1.0 _PyObject_FastCallDict                   0x131  [0x7fce7cb45fd1]
/tmp/.mount_5kpDci/usr/bin/libpython3.6m.so.1.0 _PyObject_Call_Prepend                   0xcd  [0x7fce7cb466fd]
/tmp/.mount_5kpDc...

**Comment by JacksonRG** [comment]
Is this happening with all Webm videos, or a specific few?

**Comment by cf8geek** [comment]
All that I have tested. Digging through the GitHub issues it appears it may be bigger than WebM, lots of people appear to be experiencing issues importing videos at all with recent releases (but they didn't show up when I searched before submitting).

(I didn't find an obvious link on the OpenShot website to GitHub; I was only brought here after submitting the bug.)

**Comment by FireByTrial** [comment]
I downloaded and installed 2.6.0 from GitHub releases, that version was able to import my webm just fine.
This was the version I installed on windows: https://github.com/OpenShot/openshot-qt/releases/tag/v2.6.0

before that I tried 2.6.1 and 2.6.1-dev for me both crashed on import. 

(edit: add link to release)

**Comment by JacksonRG** [comment]
@FireByTrial If you have an example of a file that does this, and what operating system, and computer setup it happened on, that may help us solve this.

**Comment by JacksonRG** [comment]
@FireByTrial If you have an example of a file that did this, and info on your operating system, and computer, that may help us reproduce this issue, so we can track down the cause.

**Comment by claydegruchy** [comment]
[pelican water landing.webm](https://user-images.githubusercontent.com/13542565/214410604-d51083b4-fdf8-4e19-85fb-10dfa81f2497.webm)
Same issue, heres the file that crashes it for me

**Comment by Colorjet3** [comment]
Thank you @claydegruchy I am able to replicate this issue with the latest DEV Daily build v3.0.0 as well in both Windows and Linux.  I will be opening an internal ticket to get this resolved.  Meanwhile, I was able to run this file through a converter and converted it to .mp4 and I can import it into OpenShot and it works.  I used ShutteEncoder but you can also use Handbrake or VLC as well.

**Comment by Colorjet3** [comment]
Here is the link to the internal ticket:  https://trello.com/c/5smONirX/104-webm-file-causes-openshot-to-crash-in-both-windows-and-ubuntu
