### ISSUE TITLE
Support proper borders on text.

### ISSUE THREAD

**Issue by roelandschoukens** [OpenShot/openshot-qt#4716]
**Describe the new feature:**

I want to put text captions on a video. Without border it will always be very hard to read on some backgrounds. It must have a border.

(the following 3 images are screenshots of Inkscape)

![image](https://user-images.githubusercontent.com/7564011/157204201-5d38b17a-4f4c-4699-85f4-bdcade7bbab4.png)

Putting up a border with symmetric thickness kind of ruins the font, and often makes text illegible:

![image](https://user-images.githubusercontent.com/7564011/157204279-66f75b1f-d5f6-4fb3-b863-f94e517defc7.png)

SVG has a paint-order attribute, so the border can be rendered behind the fill. This is the usual way to do subtitles:

![image](https://user-images.githubusercontent.com/7564011/157201930-4bf7a517-d4e1-468f-a5f6-7ac2162aa6c6.png)

![image](https://user-images.githubusercontent.com/7564011/157204374-0b66dd02-8763-4450-b22c-5b25d3214c99.png)

And this is the 3 examples in OpenShot. Unfortunately the paint-order attribute is ignored in OpenShot and the example with the border behind the fill is not rendered correctly.
![image](https://user-images.githubusercontent.com/7564011/157206278-9f2930e3-63a4-48b4-a415-9d8145dcb908.png)

Here is the SVG file with those title text elements: 
[title text](https://user-images.githubusercontent.com/7564011/157205296-0a725a07-9630-4b4b-b77f-e2b3951fcf2a.svg)

**Describe the solution you'd like:**

I assume it is up to whatever SVG library that is being used to render the SVG files.

**Describe alternatives you have considered:**

I am currently using text-shadow but this is not a perfect approximation.

(I’m in a situation where it is not feasible to add an actual text stream to the video file)

**Comment by JacksonRG** [comment]
Thanks for the  very thorough feature request! :trophy: We can take a look at the svg you attached for the parameters we need.
