### ISSUE TITLE
Openshot v.2.6.1 (AppImage) doesn't finish starting after upgrade Fedora Linux from 34 to 35

### ISSUE THREAD

**Issue by huubvanniekerk** [OpenShot/openshot-qt#4717]
**Describe the bug**
Openshot v.2.6.1 doesn't finish starting after upgrade Fedora Linux from 34 to 35. Before the upgrade, the AppImage nicely loaded with green time bar and 5 edit lines. Now, both the time bar and the edit lines don't appear. The attached screenshot shows how the loading ends, which goes for both v2.6.1 and the daily build.

**Steps to reproduce the behavior:**
Start the AppImage and wait for it to load.

**Expected behavior**
After loading the program, I expect the timebar and edit lines to appear, ready to put videos and svg files on them.

**System Details**
- OpenShot Version: 2.6.1
- libopenshot Version:  0.2.7
- Platform: Linux-5.16.12-200.fc35.x86_64-x86_64-with-fedora-35-Thirty_Five
- Processor: x86_64
- Machine: x86_64
- Python version: 3.6.9
- Qt5 version: 5.9.5
- PyQt5 version: 5.10.1
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: en_US.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-dev-daily-9246-f29ce408-2b8b05c7-x86_64.AppImage

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/l6a59sw1d6ptre67upx94d4tl11ldv1s/openshot-qt.zip) (9 KB)
- libopenshot.log: File too small or empty (not uploaded) (I DID select it, so probably too small)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots**
![Screenshot from 2022-03-08 14-08-08](https://user-images.githubusercontent.com/13077765/157245954-f57f82c1-cb5b-498d-98c0-1d5d86e2263d.png)

**Comment by Bert-H** [comment]
This is a duplicate issue of #4633.
A workaround is provided there.

**Comment by huubvanniekerk** [comment]
Thank you. It indeed does show the tracks with the work-around. Tomorrow I'll check if the editing is functional.

**Comment by jonoomph** [comment]
Fixed in https://github.com/OpenShot/openshot-qt/pull/4787
