### ISSUE TITLE
Open Shot Video Editor

### ISSUE THREAD

**Issue by wsowens101** [OpenShot/openshot-qt#472]
I installed blender and inkscape to work with Open Shot Video Editor. I made sure the path to the exe file was correct. The video editor is not working with them preventing me from being able to create advance or automated titles. please assist

Thanks 
scott

**Comment by mixedbredie** [comment]
@wsowens101 can you give some more information?  What error messages are you getting?  What operating system are you using?

**Comment by wsowens101** [comment]
The issue has been resolved. I had to change the script under the blender file from align to align_x. now it works good. you may want to let the developers know this is an issue so that it can be fixed in the next updates. I am using windows 10 on my surface pro tablet and my dell touch screen laptop. both are only a year old. I like the video editor very much but the release is very buggy.

Thanks,

William "Scott" Owens 

Warrior Ambassador/Public Speaker 

 
(M)727-919-7196 

This email is intended for the named recipient(s) only and may contain 
information that is proprietary, privileged, confidential, or otherwise 
legally exempt from disclosure. If you are not the named addressee, you 
are not authorized to read, print, retain, copy, or disseminate this 
message or any part of it. Nothing in this email is intended to 
constitute a waiver of any privilege or the confidentiality of this 
message. If you have received this email in error, please notify the 
sender immediately and delete this message. Thank you

**Comment by mixedbredie** [comment]
Glad you got it sorted.  I have submitted a pull request to get the scripts updated to ```align_x```.

**Comment by jonoomph** [comment]
I have merged this pull request, and verified the latest version of Blender 2.76 now works great with OpenShot. Please retest with our latest daily build and Blender version 2.76. Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot. Please re-open this issue if you still have an issue. Thanks!
