### ISSUE TITLE
Is timecode audio sync possible?

### ISSUE THREAD

**Issue by Jiehong** [OpenShot/openshot-qt#4729]
**Question:**

While recording shots with multiple audio sources, it's common to use timecode metadata in video and audio files produced by a main source on set. For example with a tentacle sync. This ensures that all video segments and audio files have a synchronized timecode stored in their metadata.

This allows to automatically synchronize multiple shots and multiple audio sources automatically.

I tried to synchronize just 2 video clips and 1 audio clip that have timecode metadata (tentacle sync), but openshot doesn't seem to even know this metadata is there, and doesn't offer any automatic sync.

Perhaps I just was unable to find how to do that. Is that possible?

**System Details:**
- OpenShot Version: 2.6.1
- Operating System / Distro: NixOS

**References:**

Other video editors usually provide this functionality, such as Da Vinci Resolve (ex: https://teckers.com/how-to-sync-audio-davinci-resolve/) or Final Cut Pro (https://support.apple.com/guide/final-cut-pro/sync-audio-and-video-verc1fabc30/mac, section "Sync Clips using custom settings", and then "9 > Timecode").

It also seems that other open source video editor do not support that feature (I checked Pitivi and Shotcut for example).

**Comment by JacksonRG** [comment]
I don't believe Openshot currently has the ability to sync clips like this, but I'll suggest we add it!

**Comment by Jiehong** [comment]
@JacksonRG : should this be turned into a feature request instead of a question then?

**Comment by jonoomph** [comment]
@Jiehong Can you please share some of these files with us, or point us to some example files with timecode sync metadata. I would love to see what this metadata looks like, and how we might be able to use it to align clips (clips that contain this metadata). Thanks!

**Comment by Jiehong** [comment]
@jonoomph sure.

Here is an example containing 2 small files:

- audio_with_timecode.wav is a [BMF wav file](https://en.wikipedia.org/wiki/Broadcast_Wave_Format) containing [SMPTE 12M timecode](https://en.wikipedia.org/wiki/SMPTE_timecode) metadata. The framerate of the timecode is 30fps. The audio recording was started before the video recording.
- video_with_timecode.mov contains a video track and an audio track as well as the same time code (and is also 30fps). The recording was started a few seconds after the audio recording.

The audio recording was stopped after the video recording was done.

[examples.zip](https://github.com/OpenShot/openshot-qt/files/8654912/examples.zip)
 
Graphically, the recordings would look like this once aligned:

```
                                      audio track
|---------------------------------------------------------------------------------------|
                |------------------------------------------------|                             
                |              video + video audio               |                             

```

**Comment by Jiehong** [comment]
This is still relevant

**Comment by Jiehong** [comment]
This new feature is still relevant

**Comment by Sitwon** [comment]
https://github.com/arikrupnik/ltcsync <-- How about integrating something like this?

**Comment by Sitwon** [comment]
This is a feature I would very much appreciate being added to OpenShot. Most of my shoots involve multiple cameras and aligning the clips manually is such a tedious process it can take me about as much time as the rest of the editing.

I have been considering buying or building devices to embed LTC audio tracks into each camera feed. I could then, in theory, just use `ltcsync` and import the clips into OpenShot along with the padding files to align the tracks. But it would be preferable to me if I could do the sync within OpenShot without needing the external workflow step of generating and importing padding files.

It would be even better if the alignment could be done (even if roughly) based on matching up the embedded audio tracks w/o needing synced timecode audio on each camera. I realize that this would require solving a number of interesting challenges that might be outside the scope of this project.

**Comment by lutzray** [comment]
It shouldn't be that difficult, even ffprobe can read the embedded timecode, so read it all along with other clip metadata and use it to place the clip on the timeline. Done.

As a workaround in kdenlive, my TicTacSync project will output OTIO files (dunno what I could use for OpenShot)
