### ISSUE TITLE
Animated title / Blender (solved, thanks to mixedbredie)

### ISSUE THREAD

**Issue by marron-glace** [OpenShot/openshot-qt#473]
Openshot 2.2.0 / Blender 2.78
It seems "Title/Animated" **with text**, is not working with blender 2.78 (at least this last version).
Also, "Import files", a text.svg from Inkscape 0.92, doesn't display the 'filters' associated in text.svg.

**Comment by cvermejo** [comment]
I have the same problem, is there a workaround?

**Comment by mixedbredie** [comment]
@marron-glace What error message do you get? Is the path to the Blender exe set correctly?

```C:\Program Files\Blender Foundation\Blender\blender.exe```

Can you run the blend file from the command line?  What error messages do you get when you run, for example, blur.blend and blur.py?

```/path/to/blender.exe -b /path/to/blend/file.blend -P /path/to/python/script.py ```

Can you generate the snow animated title from within openshot? It has no text.

**Comment by marron-glace** [comment]
1-The path to blender is ok (see 2-).
French error window says to check paths to blender, and at the end :
_Erreur de sortie : 
Aucune image n'a été trouvée en sortie de Blender_

2- Yes, I can generate the snow animated title from within openshot.

3- from command line, blur.blend is running ok (... python interactive console 3.5.1 ...)
     blur.py doesn't seem doing anything (?)
_C:\Program Files\OpenShot Video Editor\blender\blend\blur.blend -P C:\Program Files\OpenShot Video Editor\blender\scripts\blur.py_

**Comment by mixedbredie** [comment]
1. I got the same error this morning.  Rebooted and it started working again.  Strange.
2. If snow is working then you need to check your openShot python scripts and make sure that all the scripts that use text as input are updated.  Find ```text_object.align``` and change it to ```text_object.align_x```
3. It takes a long time to render the whole animation (~11 seconds per frame on my i7 laptop).  Does the blender window open?   Where is it writing the files to? C:\tmp\test.avi possibly.

**Comment by cvermejo** [comment]
Blender.exe is not on the systems path, do I need to put it on the path environment variable? 

Best regards, 



Carlos Vermejo Ruiz 
Gerente de Sistemas e Ingeniería de Software Libre 
Red Hat Certified Datacenter Specialist RHCDS 
Red Hat Certified Virtualization Administrator RHCVA 
Red Hat Certified Engineer 100-001-866 
MySQL Certified Professional and Trainer 
Telf.: 610-9800 Anexo 202 Cel: [ callto:999573755 | 999573755 ] 


De: "Ross McDonald" <notifications@github.com> 
Para: "OpenShot/openshot-qt" <openshot-qt@noreply.github.com> 
CC: "cvermejo" <cvermejo@tygperu.com>, "Comment" <comment@noreply.github.com> 
Enviados: Martes, 24 de Enero 2017 7:02:44 
Asunto: Re: [OpenShot/openshot-qt] Animated title / Blender (#473) 



[ https://github.com/marron-glace | @marron-glace ] What error message do you get? Is the path to the Blender exe set correctly? 

C:\Program Files\Blender Foundation\Blender\blender.exe 

Can you run the blend file from the command line? What error messages do you get when you run, for example, blur.blend and blur.py? 

/path/to/blender.exe -b /path/to/blend/file.blend -P /path/to/python/script.py 

Can you generate the snow animated title from within openshot? It has no text.

**Comment by marron-glace** [comment]
@mixedbredie 
1- I add '_x' at the end of 'text_object.align' in each scripts, and all are running now.

2- But, all scripts _generate_, give texts only in white and grey.
For example, _Courbe Néons_ script, generates animated curves in blue colours, except texts wich stay in grey.
Same way, snow script lacks colour, flakes are only in white and grey.

@cvermejo  I check my system paths, blender is not in, so I guess paths to blender in OpenShot  is enough.

**Comment by cvermejo** [comment]
In my case, no animation and still I have the error with the path of blender, did you use double quotes? 

Best regards, 



Carlos Vermejo Ruiz 
Gerente de Sistemas e Ingeniería de Software Libre 
Red Hat Certified Datacenter Specialist RHCDS 
Red Hat Certified Virtualization Administrator RHCVA 
Red Hat Certified Engineer 100-001-866 
MySQL Certified Professional and Trainer 
Telf.: 610-9800 Anexo 202 Cel: [ callto:999573755 | 999573755 ] 


De: "marron-glace" <notifications@github.com> 
Para: "OpenShot" <openshot-qt@noreply.github.com> 
CC: "cvermejo" <cvermejo@tygperu.com>, "Mention" <mention@noreply.github.com> 
Enviados: Miércoles, 25 de Enero 2017 10:44:41 
Asunto: Re: [OpenShot/openshot-qt] Animated title / Blender (#473) 



[ https://github.com/mixedbredie | @mixedbredie ] 
1- I add '_x' at the end of 'text_object.align' in each scripts, and all are running now. 

2- But, all scripts generate , give texts only in white and grey. 
For example, Courbe Néons script, generates animated curves in blue colours, except texts wich stay in grey. 
Same way, snow script lacks colour, flakes are only in white and grey. 

[ https://github.com/cvermejo | @cvermejo ] I check my system paths, blender is not in, so I guess paths to blender in OpenShot is enough.

**Comment by marron-glace** [comment]
@mixedbredie 
2- Oops, no more problem here : Animated Title scripts give animated texts **with** colours, chosen in OpenShot menu, before _generate_.

4- I have Colours (and filter ?) issues in Title.
**From Openshot**, when in Title (Ctrl+T) you edit a title with _Utiliser l'éditeur avancé_ (>**Inkscape**).
If ie you give different colours to letters, back to OpenShot, the default colour from OpenShot menu remain.
While this text.svg file is multicolour when Inkscape open it again.

**Comment by marron-glace** [comment]
@mixedbredie 
4- Not a scoop I think, to keep various colours and filters effects when editing a text with Inkscape from OpenShot (or in order to be import in OpenShot), I export the file to text.png.
I got a bitmap file, losing vectors, but it's okay, and usable. Thanks to you.

**Comment by mixedbredie** [comment]
Glad you got it sorted.  Hopefully the pull request #398 will be accepted at some point and then all these issues will go away.

**Comment by bref27** [comment]
I got very similar problem with dissolve.py
Added '_x'  after 'ActiveObjectText.data.align' , and everything is OK now.
Thanks

**Comment by jonoomph** [comment]
Please test again with the latest daily build of OpenShot. I've merged in changes to the text alignment, and updated the minimum version compatibility to 2.78. I've tested all animation on Linux, Mac, and Windows with Blender 2.78 and everything works great.

Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot. _It might take a couple hours for the latest version to appear._

If you have other issues, please file additional bugs for each one. Thanks!
