### ISSUE TITLE
selecting Slow Motion Forward 1/16X speed causes bizarre results and system crashes. 

### ISSUE THREAD

**Issue by psa-ewave** [OpenShot/openshot-qt#4730]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**
Selecting Time->Slow->Forward->16X causes the system to crash, or bizarre behavior.

**Expected behavior**
I expect 16X slow speed (1/2X, 1/4X and 1/8X all work fine.)

**System Details**
- OpenShot Version: 2.6.1-dev
- libopenshot Version:  0.2.7-dev
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-dev-daily-9296-9adb94c3-46255e46-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/vzf6egvv4j8qgvdmdbqp9oicw5sy4jri/openshot-qt.zip) (11 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by JacksonRG** [comment]
Thanks for pointing this out. Is this happening with all files you test?

**Comment by psa-ewave** [comment]
I've never had slow speed 1/16X work on any file. 1/8X typically works.

Btw- if you are into screech owls, and you'd like to see some short videos
created with your OpenShot, here's a link to a few videos. All the screech
owl videos on my channel were made using OpenShot:

https://m.youtube.com/watch?v=jqOGgmqtGTM


https://m.youtube.com/watch?v=rJv9fPQPL4c

I really appreciate you flowing up my buf report.  I'm in North Dallas.  I
think you are in Rockwall?

Regards,
Paul

**Comment by JacksonRG** [comment]
Could you include a recording of the bizzare results? Also, can you make sure you have debug logging enabled? Its under `Edit > Preferences > Debug`. That may give us more information in your log file.

**Comment by psa-ewave** [comment]
OK-  This is weird.  After constantly causing me problems, it now appears
to be working perfectly. (1/16x slow motion.)

I did upload log files (when I reported the bug originally) of the
procedure to get the bug.

**Comment by JacksonRG** [comment]
Odd. But good to hear. Let me know if you have any other issues.

**Comment by psa-ewave** [comment]
When I had the debug on (verbose) the files were 24 Meg-  Too large for
upload on your bug page.  (maximum size was set to 0.5Meg. )

The procedure that causes problems:

Load 3 minute video.

Slice the video in half.

Select the second half and try to slow it by 1/16X.  Watch the
length shorten to 1/16, when it should be 16X.  Try to play it.  *crash* or
other unwanted behavior.
