### ISSUE TITLE
Timeline barely usable but everything else seems up to speed.

### ISSUE THREAD

**Issue by tevoran** [OpenShot/openshot-qt#4731]
Hello there,

my OpenShot makes it very hard to use the the cursor that indicates the what is displayed properly. It seems to lag. And when I want to use space to find the best moment to cut a clip or where I want to add something then it doesn't react fast. It might need a second or two to react. During this time the clip still plays until it stops. Which makes it very hard to use it sadly. This is also happening when I just have a 4s clip and a static image in the timeline.

Surprisingly the playing of the clip itself works flawlessly and doesn't stutter.

**Steps to reproduce the behavior:**
1. Add a short clip
2. Add a static image after the clip
3. Play the clip
4. Press space/pause
5. Seeing the lag until the video playback stops and the time line cursor stops moving as well

**Expected behavior:**
The video playback should stop immediately when I press pause/space.

**System Details:**
Hardware:
-CPU i7 3770
-32GB DDR3 RAM
-512GB SSD

Software:
- OpenShot 2.6.1
- Gentoo Linux amd64, Kernel 5.15.23
- Libopenshot 0.2.7

https://user-images.githubusercontent.com/6130298/158648203-840340b6-e1f7-4d47-a867-5f2d0a55bd89.mov

**Comment by JacksonRG** [comment]
Strange... We've made several performance improvements since our last release. Are you using the [daily build](https://www.openshot.org/download/)?

**Comment by tevoran** [comment]
I am not exactly sure. I use the testing version of OpenShot in Gentoo which usually means that it should be the latest version of the repo. Although I can't guarantee that. There is probably a way to check out where the ebuild builds OpenShot from.
