### ISSUE TITLE
Could not create hwdevice - latest daily build

### ISSUE THREAD

**Issue by lemur117** [OpenShot/openshot-qt#4734]
**Describe the bug:**
While trying to export a file with the h264_vaapi codec, I am receiving the following error

Sorry, there was an error exporting your video: 
Could not create hwdevice for file /home/jon/abc.mp4

**Steps to reproduce the behavior:**
1. Launch OpenShot-v2.6.1-dev-daily-9309-08b49756-46255e46-x86_64.AppImage
2. Open saved project
3. Export video with VA-API MP4 (h.264 va)

Sorry, there was an error exporting your video: 
Could not create hwdevice for file /home/jon/abc.mp4

![image](https://user-images.githubusercontent.com/66752884/158929579-bfc9d475-e4e2-4465-8232-1d3bef6610f5.png)

**Expected behavior:**
Video should be exported with va-api acceleration

**System Details:**
- OpenShot-v2.6.1-dev-daily-9309-08b49756-46255e46-x86_64.AppImage
- Operating System: Linux Mint 20.2
- Ryzen 7 with Radeon VEGA

**Log Files:**
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/8299920/openshot-qt.log)

**Comment by JacksonRG** [comment]
I believe there's a current issue in hardware acceleration through appimage. Have you tried installing via apt?

**Comment by dhjw** [comment]
On my Ubuntu 20.04 system with Ryzen CPU I ran `sudo apt install mesa-va-drivers` and now it works. I installed openshot via the official PPA. I'm using the kisak-mesa repo for GPU drivers.

**Comment by JacksonRG** [comment]
@lemur117 We've made a change to what libraries are bundled into our appimage. Is this issue still present for you? If so have you tried either the newest daily build, or dhjw's solution?
