### ISSUE TITLE
openshot shuts down

### ISSUE THREAD

**Issue by lucanewuser** [OpenShot/openshot-qt#4737]
https://user-images.githubusercontent.com/102053234/159311307-ef4f412b-6dc0-41db-a757-8d3bdd967c98.mp4

Openshot shuts down
Whenever i select the .mp4 file it shows me a loading mouse, then it shuts down openshot

I sellect to import new file
1. Go to '"C:\Users\(main user)\Downloads\Kvyat torpedoes into Kimi.mp4"'
2. Click on 'add new file'
3. 'loading screen'
4. See error (shut down)

**Expected behavior**
To add the file

**System Details**
- OpenShot Version: 2.6.1-dev
- libopenshot Version:  0.2.7-dev
- Platform: Windows-10-10.0.22000
- Processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-GB', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-dev-daily-9309-08b49756-46255e46-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/9f579l40q6m4g7iq9qy5812bq88znfn5/openshot-qt.zip) (13 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/9f579l40q6m4g7iq9qy5812bq88znfn5/libopenshot.zip) (6 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by JacksonRG** [comment]
Does this issue only happen with one file in particular?

If so, could you try re-encoding it with a tool like [handbrake](https://handbrake.fr/), and then see if it still causes the problem?

Also for additional info in the log files you can go to `Edit -> Preferences -> Debug` and make sure debug mode is enabled. If you re-create the error, and upload your new log files, they may have more info for us in them.

**Comment by lucanewuser** [comment]
Thank you for your help!
Yes, it happens with that file in particular, i also have debug mode activated.
I think i am gonna re-download it. If it won't work, i will try with "hanbrake"


P.S. didn't work
