### ISSUE TITLE
Language incompatibility (BR)

### ISSUE THREAD

**Issue by souzaperez** [OpenShot/openshot-qt#474]
Windows 7 SO - App Version 2.2.0

In the Brazilian Portuguese version, most of the app is in Portuguese, but the superior toolbar is in English.

![1](https://cloud.githubusercontent.com/assets/25093493/21917774/1807003c-d929-11e6-914b-1c9c3e43fc05.png)
![2](https://cloud.githubusercontent.com/assets/25093493/21917772/180511e6-d929-11e6-8cd2-6adbd7ca03d2.png)
![3](https://cloud.githubusercontent.com/assets/25093493/21917773/180690d4-d929-11e6-8742-2af6b30589ab.png)
![4](https://cloud.githubusercontent.com/assets/25093493/21917770/1803a52c-d929-11e6-87fc-27c53bc78618.png)
![5](https://cloud.githubusercontent.com/assets/25093493/21917769/17ffce16-d929-11e6-925f-91436f20e654.png)

**Comment by jonoomph** [comment]
We have 127 untranslated words/phrases in Brazilian Portuguese. To help with translations, please visit: https://translations.launchpad.net/openshot/2.0/+pots/openshot/pt_BR/+translate. Be sure to read the instructions there before you contribute. Translations get automatically pulled into OpenShot before we release each new version. =) Thanks!
