### ISSUE TITLE
The interface is broken on daily builds starting from build 8572

### ISSUE THREAD

**Issue by NorbiPeti** [OpenShot/openshot-qt#4740]
**Describe the bug:**
I was trying daily builds for another issue (excessive memory use) and all of the recent ones gave me the interface below. Everything can be interacted with, but most of the text is unreadable, especially in dialogs.

**Steps to reproduce the behavior:**
1. Download the AppImage OpenShot-v2.6.1-dev-daily-8572-aee3a44b-73c519f0-x86_64.AppImage from GitHub
2. Start OpenShot

**Expected behavior:**
The interface to be displayed correctly.

**System Details:**
- OpenShot Version: 2.6.1 build 8572
- Operating System / Distro: Ubuntu 20.04.4

**Screenshots:** (Optional)
![image of interface](https://user-images.githubusercontent.com/13187743/159596511-c2e7078b-d594-48e9-ad7d-fa51aa784045.png)

**Comment by NorbiPeti** [comment]
This got fixed at some point. I tested build 9387.

Edit: No, it just seems to work sometimes. I'm not sure anymore.

**Comment by Colorjet3** [comment]
This is fixed in the latest DEV daily build of v3.0.0
