### ISSUE TITLE
"Entry Point Not Found" Error (same as issue#4467)

### ISSUE THREAD

**Issue by ultrawow65** [OpenShot/openshot-qt#4745]
**Describe the bug**
When the application is opened, this error message pops up. After clicking the OK button, the program comes up with no noticable problems.

**Steps to reproduce the behavior:**
1.  Open the application.
2. See error

**Expected behavior**
Expected to not get an error.

**System Details**
- OpenShot Version: 2.6.1-dev
- libopenshot Version:  0.2.7-dev
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 158 Stepping 12, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['he-IL', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-dev-daily-9338-04db6ce8-46255e46-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/kdoj86lbbmv07rgyrby08r1rt7avrjzv/openshot-qt.zip) (31 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/kdoj86lbbmv07rgyrby08r1rt7avrjzv/libopenshot.zip) (0 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots**

![2022-03-26 02_31_55-Window](https://user-images.githubusercontent.com/81269580/160215504-8adef024-6f7a-4065-bfd7-50b8f20d337f.jpg)

**Comment by Boejunda** [comment]
This problem appears in the latest build, 3.0.0:

![image](https://user-images.githubusercontent.com/13823838/211860295-df3ac4b8-9a6e-4b58-b85b-5b9132105a90.png)

Can this issue be reopened? It clearly is still happening. Any way to fix it?

**Comment by Colorjet3** [comment]
Please check this out:  https://www.thewindowsclub.com/procedure-entry-point-could-not-be-located-in-the-dynamic-link-library

**Comment by Boejunda** [comment]
> Please check this out: https://www.thewindowsclub.com/procedure-entry-point-could-not-be-located-in-the-dynamic-link-library

That's not a terribly helpful article. This one seems to be more to the point:
https://www.reddit.com/r/OpenShot/comments/qvqlvu/i_updated_now_have_this_error_opens_freezes/

**Comment by Boejunda** [comment]
The copy of libssl-1_1-x64.dll included with Openshot 3.0.0 isn't digitally signed, and seemingly is meant to replace a digitally signed copy on the system. I'm not comfortable with this, and will be ceasing to use OpenShot until this is addressed. In the meantime, this issue should be reopened.

**Comment by Colorjet3** [comment]
Thank you @Boejunda I am not a developer so I am going to ask the lead developer take a look at this.

**Comment by JBoysen1** [comment]
I just installed 3.1.1 and got this error. I posted a workaround here: https://www.reddit.com/r/OpenShot/comments/qvqlvu/i_updated_now_have_this_error_opens_freezes/
