### ISSUE TITLE
Is the source code still compileable with Mac OS X 10.14.3 (Mojave)?

### ISSUE THREAD

**Issue by lollisoft** [OpenShot/openshot-qt#4749]
Before I try to download and setup Qt on my MacBook, I like to ask, if this is possible to avoid time wasting...

Thanks

Lothar

**Comment by JacksonRG** [comment]
Most of our development happens on linux. Is this macbook an intel, or M1 machine?

**Comment by JacksonRG** [comment]
Part of our automatic testing is a macOS build. So since those are succeeding there shouldn't be an issue. Let us know if you have any trouble compiling.

**Comment by lollisoft** [comment]
My email may be late. I try to build it on my laptop :-)

**Comment by lollisoft** [comment]
I have an Intel Late 2013 MacBook Pro Retina with Intel Intel Core i5. I just wonder, that the Mojave is still a relative new OS version.
