### ISSUE TITLE
Application hangs/crashes after playback of 2 video strips

### ISSUE THREAD

**Issue by Artoooooor** [OpenShot/openshot-qt#475]
Hi,

Program crashes in 8/10 cases after performing the following steps:

1.  Start a new project,
2.  import 2 video files,
3.  rearrange them so that they overlap on tracks 3 and 4,
4.  change alpha value to 0,5 for video on track 4,
5.  playback from the middle of the overlapping part,
6.  pause playback,
7.  rearrange tracks and playback from the middle few times.
At this point clicking play/pause has no effect - frame in preview is stationary,
8.  Try to close the program with 'x' button.
At this point Windows crash information appears.

OS: Windows 7 Professional 64 Bit, SP 1

Codec info (from VLC Media Player):
> Codec: H264 - MPEG-4 AVC (part 10) (h264)
> Original identifier: 4113
> Resolution: 1440x1090
> Framerate: 25

Windows crash information (in Spanish, sorry):
> Descripción:
>   Este programa dejó de interactuar con Windows por un problema.
> 
> Firma con problemas:
>   Nombre del evento de problema:	AppHangB1
>   Nombre de aplicación:	launch.exe
>   Versión de la aplicación:	0.0.0.0
>   Marca de tiempo de la aplicación:	57a98a3e
>   Firma de bloqueo:	a84d
>   Tipo de bloqueo:	0
>   Versión del sistema operativo:	6.1.7601.2.1.0.256.48
>   Id. de configuración regional:	1045
>   Firma adicional de bloqueo 1:	a84d630f5c7cedfebf6a69beedc1f92a
>   Firma adicional de bloqueo 2:	9471
>   Firma adicional de bloqueo 3:	94719a3be7dc6beb400216d88eb25c1f
>   Firma adicional de bloqueo 4:	a84d
>   Firma adicional de bloqueo 5:	a84d630f5c7cedfebf6a69beedc1f92a
>   Firma adicional de bloqueo 6:	9471
>   Firma adicional de bloqueo 7:	94719a3be7dc6beb400216d88eb25c1f

**Comment by marron-glace** [comment]
I exactly do what you indicate, and a bit more (3 videos 'alpha').
No problem at all.
Windows 10-64, videos : x264/avc1_Ac3.mp4

**Comment by Artoooooor** [comment]
So the problem can lie somewhere outside the application. I don't know. How can I gather some more logs to check exactly which module/library/codec crashed?

**Comment by jonoomph** [comment]
@Artoooooor Thanks for the bug report. Please verify this bug still happens for you on our latest daily build. We have recently fixed some issues with crashes and freezes, and I have a hunch this will be fixed for you. Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot. 

If it still crashes, please see the instructions (https://github.com/OpenShot/openshot-qt/blob/master/.github/CONTRIBUTING.md) for enabling debug and attaching log files, and re-open this issue. Thanks!
