### ISSUE TITLE
No sound on preview

### ISSUE THREAD

**Issue by alx359** [OpenShot/openshot-qt#4752]
There's no sound during preview with latest OpenShot (**2.6.1**) in Windows 7-x64.

- This issue seems a reoccurring old issue #[3116](https://github.com/OpenShot/openshot-qt/issues/3116)
- The fix suggested by [SuslikV](https://github.com/SuslikV) in [#3116](https://github.com/OpenShot/openshot-qt/issues/3116#issuecomment-563961204) by installing the [OpenShot-v2.4.4-dev2](https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.4.4-dev2-1573705361-c2713520-12a15298-x86.exe) worked for me.
- Also, the release version of [OpenShot-v2.5.1](https://github.com/OpenShot/openshot-qt/releases/download/v2.5.1/OpenShot-v2.5.1-x86_64.exe) worked for me.
- However, starting with [OpenShot-v2.6.0](https://github.com/OpenShot/openshot-qt/releases/download/v2.6.0/OpenShot-v2.6.0-x86_64.exe) there's no sound again, and neither of the suggested workarounds helped. So it seems reasonable to suspect that something regressed in the codebase during the 2.6.x series.

EDIT: Also just tested [OpenShot-v2.4.3](https://github.com/OpenShot/openshot-qt/releases/download/v2.4.3/OpenShot-v2.4.3-x86_64.exe), to check if that's an issue specifically addressed in #[3116] with OpenShot-v2.4.4-dev2. Interestingly, there IS sound.

**Comment by bellera** [comment]
Same problem on Win10. Tried latest daily build (2022-06-30) and it crashes.
Usually I work on Ubuntu 20.04 with 2.4.3 (Ubuntu repository) without problems.
Downloaded 2.4.3 for Win10 from videohelp.com worked for me.

**Comment by JacksonRG** [comment]
@bellera You said same issue in the daily build. Do you mean that there was no sound when you used the daily build before it crashed?

Also did it crash immediately, whenever you performed a certain action?

**Comment by bellera** [comment]
I'm sorry! The daily build crashes immediately. Not usable. On Acer TravelMate B311. It has a Realtek audio chip.
Finally I used a bigger laptop from a friend. And 2.6.1 worked fine. I don't know the model. It's a big HP.

**Comment by Colorjet3** [comment]
There has been many improvements (bug fixes and enhancements) in v3.0.0.  Please go to openshot.org/download/#daily and get the latest .exe (windows) or AppImage (linux).

In Windows, it will be best if you perform a clean installation:  https://github.com/OpenShot/openshot-qt/wiki/Clean-Installation-of-OpenShot
