### ISSUE TITLE
Dragging videos into OpenShot sometimes makes them disappear (from disk)

### ISSUE THREAD

**Issue by JohanX123** [OpenShot/openshot-qt#4756]
Dragging video files into the Project Files area usually makes them available to work with in OpenShot but they are also still available in the Windows file explorer. On two occasions I have lost the file(s) I have dragged. It still looks like it is dragged into the Project Files area but at the same time it has been removed from the File Explorer (since I dragged them from my NAS that isn't setup with a recycle bin the files are lost forever). While the files still look as they are available in the Project Files area it isn't possible to drag them to the timeline.

I don't know how to reproduce it, I have probably dragged a hundred files or so into OpenShot and three of them has been deleted in the process, The first time I thought that i did something strange and maybe dropped the file on some other folder in Windows Explorer "on the way" to OpenShot but the second time I am 100% certain I dropped the files into OpenShot's Project Files area.

I would not expect OpenShot to delete my original files.

OpenShot Version 2.6.1 (by the way, you could get more details if it was possible to select and copy text in the about box)

OS:
Edition	Windows 10 Pro
Version	21H1
Installed on	‎2022-‎01-‎07
OS build	19043.1586
Experience	Windows Feature Experience Pack 120.2212.4170.0

Extract from log below (the files VID_20210319_075754.mp4 and VID_20210319_080027.mp4 was immediately removed from disk when I dragged them to OpenShot):

[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/8413463/openshot-qt.log)

**Comment by Cyborgscode** [comment]
FYI: Depending on the NAS in use, you can ssh into the NAS system and start recovering lost files manually. If not too much data has been written to disk, you can get them back. 

In case, you can't start QPHOTOREC on your NAS. Power the NAS down, put the drive into a normal PC with Linux and start recovering there with QPHOTOREC. Scan for the empty blocks only and select your file types wisely, otherwise you will end up with tons of files on the recovery drive.

**Comment by JacksonRG** [comment]
@JohanX123 Without access to your specific NAS setup, I think the best I can do is help prevent this in the future. If OpenShot has any control over this issue I hope we can find out.

If you can take some *Copied* files on your NAS and experiment with what steps lead to the file dissapearing. Then we can find out if OpenShot can do anything.

**Comment by JohanX123** [comment]
The files that disappeared is not extremely important, I can live without them. My NAS setup is kind of irrelevant for this bug report. Shouldn't have included that, sorry. I don't think I can do much more than what I described above. As I mentioned, I have done the same with probably a hundred files without problems. One thing I can think of is that when dragging files into OpenShot there is a label by the mouse pointer saying "Copy" (or something similar, not by the computer right now). That is probably not true (is it?). My feeling is that the file isn't copied at all but just linked to the place where it is dragged from. If there is some missunderstanding between OpenShot and Windows making Windows believe it is a move instead of a copy operation, then the file would disappear. But what do I know, the label is maybe just a label...

**Comment by JacksonRG** [comment]
You're right that OpenShot only stores the location of the file. I don't know of any situation where OpenShot would delete a file.
