### ISSUE TITLE
When exporting video with MP4 VideoToolbox openshot crashes

### ISSUE THREAD

**Issue by fatman00** [OpenShot/openshot-qt#4762]
**Describe the bug**
When exporting video with MP4(H.264) VideoToolbox openshot crashes

**Steps to reproduce the behavior:**
Create a project
Change video speed to 2x in the context menu. Time > Fast > Forward > 2X
Export video as MP4 with HD1080P30 with videotoolbox
OpenShot Crashes and closes

**Expected behavior**
The file should be exported

**System Details**
- OpenShot Version: 2.6.1-dev
- libopenshot Version:  0.2.7-dev
- Platform: Darwin-21.2.0-x86_64-i386-64bit
- Processor: i386
- Machine: x86_64
- Python version: 3.7.11
- Qt5 version: 5.15.0
- PyQt5 version: 5.15.1.dev2007111314
- Qt Detected Languages: ['en-DK', 'da-DK']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-dev-daily-9379-d909eccd-46255e46-x86_64.dmg

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/fj654e75ksw56bcr4fbf8eg9lsvp7wrc/openshot-qt.zip) (109 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/fj654e75ksw56bcr4fbf8eg9lsvp7wrc/libopenshot.zip) (312 KB)

**Exception / Stacktrace**
```4   libopenshot.21.dylib                0x0000000116bbd1a4 _ZNopenshot::FFmpegWriter::write_queued_frames + 2132
5   libopenshot.21.dylib                0x0000000116bbc704 _ZNopenshot::FFmpegWriter::WriteFrame::__::shared_ptrINS_::Frame + 1204
6   _openshot.so                        0x0000000116760f40 _ZL29_wrap_FFmpegWriter_WriteFrameP7_objectS0_ + 960
7   Python                              0x000000010967746d PyCFunction_Call + 321
8   Python                              0x000000010970a5aa _PyEval_EvalFrameDefault + 26573
9   Python                              0x000000010970d4ff _PyEval_EvalCodeWithName + 1863
10  Python                              0x0000000109677122 _PyFunction_FastCallKeywords + 222
11  Python                              0x000000010970cc66 call_function + 737
12  Python                              0x000000010970a1b8 _PyEval_EvalFrameDefault + 25563
13  Python                              0x000000010970d4ff _PyEval_EvalCodeWithName + 1863
14  Python                              0x0000000109676d90 _PyFunction_FastCallDict + 444
15  Python                              0x0000000109677e93 _PyObject_Call_Prepend + 131
16  Python                              0x0000000109677267 PyObject_Call + 136
17  QtCore.so                           0x000000010a0ecac7 _ZNPyQtSlot::call::_object::_ + 39
18  QtCore.so                           0x000000010a0ec9d6 _ZNPyQtSlot::invoke::_object::_ + 374
19  QtCore.so                           0x000000010a0ed5c5 _ZNPyQtSlotProxy::unislot + 85
20  QtCore.so                           0x000000010a0ed53a _ZNPyQtSlotProxy::qt_metacall::QMetaObject::Call + 58
21  QtCore                              0x000000010af242be _Z10doActivateILb0EEvP7QObjectiPPv + 1118
22  QtWidgets                           0x000000010e4240ac _ZNQDialogButtonBoxPrivate::_q_handleButtonClicked...

**Comment by fatman00** [comment]
If you need me to test anything please let me know?

**Comment by JacksonRG** [comment]
Hi, I'm not entirely sure what you mean by video toolbox. Also for other testing, is this only happening with this specific export setting?

**Comment by fatman00** [comment]
Hi @JacksonRG. Yes this is only an issue when I export with VideoToolbox(https://developer.apple.com/documentation/videotoolbox). The CPU based exports seems to work without issues.

**Comment by JacksonRG** [comment]
Ah, That's why I wasn't seeing it. Since I don't have an apple computer to test on, would you mind telling me if this crash happens in the 2.6.1 release version? (Not the daily build) that would tell me if some recent change disrupted this.

**Comment by fatman00** [comment]
This is also an issue on the 2.6.1 release.
