### ISSUE TITLE
Openshot keeps crashing when I open a specific project.

### ISSUE THREAD

**Issue by thenimble** [OpenShot/openshot-qt#4763]
It took me 1 month to create part - 1 of a documentary video I'm creating. My laptop is so old, it started hanging a lot. So decided to install a new SSD (480 GB). Bought one. Transferred the Openshot project files to the ssd as it is (at the same location) and also copied the openshot_qt folder as it is in the same location (renamed every folder and drive as it is). Installed a new window in the new SSD and downloaded Openshot, but whenever I try to open the project, Openshot crashes. No errors, no nothing. It just gets shut down. Tried re-installing, deleting the openshot_xt folder's log files, etc. But nothing helped. Other projects are opening and working fine, no crash but when I open this specific project, Openshot crashes. But it doesn't crash in the old hard drive.

Please help. It took me so much time and effort creating the part - 1 of this documentary and remaining parts will definitely take 1-2 extra months.

**System Details**
- OpenShot Version: 2.6.1-dev (also checked it by installing the daily dev)

Device name:	SachinBishnoi
Processor:	Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz   2.00 GHz
Installed RAM:	4.00 GB
Device ID:	F9D3CB3D-CD1E-4FEE-840A-AECE094B7096
Product ID:	00331-10000-00001-AA622
System type:	64-bit operating system, x64-based processor
Pen and touch:	No pen or touch input is available for this display

Edition:	Windows 10 Pro
Version:	21H1
Installed on:	‎4/‎5/‎2022
OS build:	19043.1021
Experience:	Windows Feature Experience Pack 120.2212.2020.0

**Comment by JacksonRG** [comment]
Hi, to help us solve this, could you clear your log files, try to open the project, and then upload the log files? Instructions on where to find them can be found [here](https://github.com/OpenShot/openshot-qt/wiki/) and you can drag them into a comment.

**Comment by JacksonRG** [comment]
Also, for re-installing, you would want to uninstall openshot, and remove the `.openshot_qt` folder just to clear any settings whose paths are no longer valid.

**Comment by thenimble** [comment]
There you go!

**Comment by JacksonRG** [comment]
Oh, Did you attach it as an email? That didn't come through to github. Could you upload it to something like google drive and share the link?

**Comment by thenimble** [comment]
Hey!

I am already talking to the OpenShot support with this email:
***@***.***

And from this side, you're also solving my issue.

They already asked me about the project file that wasn't opening and they
asked me to send it. I sent the file and they edited it and now the
issue is solved.

The project file is opening now.

But why is the audio not good enough? When I play the video within the
project, the audio is so heavy.. like the tone/pitch has been changed. The
voice is not real and so heavy. Why is this so?

Please solve this.
(The project file has been attached)

Thanks,
Sachin
