### ISSUE TITLE
Los clips cambian de sitio y se sobreponen entre ellos a la hora de exportarlos cuando pongo velocida...

### ISSUE THREAD

**Issue by markeling** [OpenShot/openshot-qt#4764]
Cuando edito un video al poner la velocidad superior a el 1x en cualquier clip ,a la hora de exportalos clips se sobreponen entre ellos y en el la plicacion mientrad lo estoy editando no se sobreponen

**Comment by JacksonRG** [comment]
(Via google translate. Feel free to correct):
>When I edit a video by putting the speed higher than 1x in any clip, when exporting the clips they overlap each other and in the application while I am editing it they do not overlap

Hi, thanks for pointing this out. Could you add a screenshot, or make a small project that shows this effect and upload it? That will make it easier for us to test this.

(Respuesta usando el traductor de Google)
Hola, gracias por señalar esto. ¿Podría agregar una captura de pantalla o hacer un pequeño proyecto que muestre este efecto y subirlo? Eso hará que sea más fácil para nosotros probar esto.
