### ISSUE TITLE
Missing frame enters into an infinite loop

### ISSUE THREAD

**Issue by fjrg76-com** [OpenShot/openshot-qt#4765]
**Describe the bug:**
Whenever move the cursor to a mark the program enters into an infinite loop because of a missing frame:

**Steps to reproduce the behavior:**
1. Open a terminal in Linux and start the app
2. Load a project with some marks
3. Jump to a mark
4. The terminal shows that the program has enter into an infinite loop due to missing frames. The log files grows as crazy

**Expected behavior:**
The app must move the cursor and play the project

**System Details:**
- OpenShot Version [2.6.0-dev and 2.6.1 (daily build)]
- Linux Mint Cinnamon 20.3

**Log Files:**
In zip format

**Exception / Stacktrace:**
```
INFO logger_libopenshot: FFmpegReader::CheckMissingFrame (Is Previous Video Frame Final) (requested_frame=10258.0000, missing_frame->number=10258.0000, missing_source_frame=10255.0000)
INFO logger_libopenshot: FFmpegReader::CheckMissingFrame (AddImage from Previous Video Frame) (requested_frame=10258.0000, missing_frame->number=10258.0000, missing_source_frame=10255.0000)
INFO logger_libopenshot: FFmpegReader::CheckWorkingFrames (requested_frame=9947.0000, frame_number=10258.0000, is_video_ready=1.0000, is_audio_ready=1.0000, checked_count=1.0000, checked_frames_size=86.0000)
INFO logger_libopenshot: FFmpegReader::CheckWorkingFrames (mark frame as final) (requested_frame=9947.0000, f->number=10258.0000, is_seek_trash=0.0000, Working Cache Count=96.0000, Final Cache Count=20.0000, end_of_stream=0.0000)
INFO logger_libopenshot: FFmpegReader::CheckMissingFrame (requested_frame=10259.0000, has_missing_frames=1.0000, missing_video_frames.size()=246.0000, checked_count=1.0000)
INFO logger_libopenshot: FFmpegReader::CheckWorkingFrames (requested_frame=9947.0000, frame_number=10259.0000, is_video_ready=1.0000, is_audio_ready=1.0000, checked_count=1.0000, checked_frames_size=86.0000)
INFO logger_libopenshot: FFmpegReader::CheckWorkingFrames (mark frame as final) (requested_frame=9947.0000, f->number=10259.0000, is_seek_trash=0.0000, Working Cache Count=95.0000, Final Cache Count=20.0000, end_of_stream=0.0000)
^Z
```

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.
[openshot_qt.zip](https://github.com/OpenShot/openshot-qt/files/8448632/openshot_qt.zip)

**Comment by JacksonRG** [comment]
Thanks for pointing this out. We are working on a fix for this timing issue. We'll be sure to test this sequence when that fix is ready.
