### ISSUE TITLE
Unhandled exception during startup

### ISSUE THREAD

**Issue by spacendtime** [OpenShot/openshot-qt#4767]
Error message saying "Program needs to be closed".
Trying to debug the error yields to following result:

Unhandled exception at "address" (libopenshot.dll) in openshot-qt.exe: 0xC0000005: Access violation reading location 0x0000000000000000.

Thx

**Comment by JacksonRG** [comment]
Hi, Could you attach your log files? There are instructions [here](https://github.com/OpenShot/openshot-qt/wiki/Issue-Logging) on how to find them.

**Comment by spacendtime** [comment]
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/8470492/openshot-qt.log)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/8470494/libopenshot.log)

Here we go

**Comment by JacksonRG** [comment]
Ok... That's *very* interesting. What audio device are you using? OpenShot is detecting a sample rate over 10^111. (which is beyond impossibly high). Also does OpenShot behave any differently if you plug in a different audio device?

**Comment by CryVICSky** [comment]
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/8500347/openshot-qt.log)

Caught a similar issue when installing at least a few recent daily builds (dev-daily-9376-04db6ce8-46255e46-x86_64; dev-daily-9379-d909eccd-46255e46-x86_64; dev-daily-9387-d909eccd-46255e46-x86_64). The application window opens for a few seconds and then closes for no apparent reason.
