### ISSUE TITLE
want new object property: end position (sum of position and duration)

### ISSUE THREAD

**Issue by feldmark** [OpenShot/openshot-qt#4768]
**Describe the new feature:**
Properties of a clip or other object like a fade has "Position" and "Duration" but in order to accurately align clips that I am putting together, along with an appropriately overlapped transition, I also need the "End Position" which is the sum of Position and Duration.

**Describe the solution you'd like:**
Rename Position to something like Position Start and add a new property like "Position End" which is the sum of Position Start and Duration.  (I prefer Start Position and End Position but reversing the words make it clear how they are related.)

**Describe alternatives you have considered:**
Without this I have to add position and duration for every clip I want to add. In my application, I am condensing a tennis match to only the actual playing time.  So I need to cut out time in between every point.  There can be 200 or 300 points in a 3 set match (easily 75 in a close set) so that's a lot of manual calculation I have to do to add transitions precisely.

**Screenshots:** (Optional)
NA

**Comment by JacksonRG** [comment]
This is a great idea. We've been considering an upgrade to how we deal with time, to "stretch" clips in a user friendly way. I'm noting this as well for a representation of that feature in the properties.
