### ISSUE TITLE
cant open

### ISSUE THREAD

**Issue by bell18** [OpenShot/openshot-qt#477]
it doesn't let me open openshot unless I'm on an administrators account

**Comment by gebeleixis** [comment]
true that, on windows 10 insider preview 64bit,with latest trunk.

**Comment by JtLively** [comment]
@bell18 Are you on Windows as well?
Also, did you both download it from a standard user account?
What is the error you get?

**Comment by bell18** [comment]
@JtLively  Yes, I'm on windows

**Comment by bell18** [comment]
I'm running widows 10 home 64 bit. Tried installing with standard and admin accounts, no difference. The issue is only on the laptop. I'm not on that computer now so I can't get the exact error but it said something about python.

**Comment by jonoomph** [comment]
Hmmm. Sounds like maybe it was installed as Administrator? Please uninstall, and reinstall as a normal user account... and see if you have any issue. Also, please use our latest daily build: Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot. 

If the issue still happens, please reopen this issue and attach screenshots of the error (or copy paste the error here). Thanks!

**Comment by bell18** [comment]
i installed on a regular account

**Comment by bell18** [comment]
and i had the issue then

**Comment by bell18** [comment]
@jonoomph
![image](https://cloud.githubusercontent.com/assets/25139935/23589985/d8816830-01a5-11e7-8e6b-635df99e5fb7.png)
it still gives me the same error
