### ISSUE TITLE
OpenShot fails to launch at all after configuring Prefs; resolved, randomly crashes during timeline ...

### ISSUE THREAD

**Issue by vincelaconte** [OpenShot/openshot-qt#4773]
**Describe the bug**
First launch was fine, configured some preferences, upgraded to 2.6.1 appimage, and OpenShot failed to launch a second time. Rollback to version 2.6.0 did not  fix. Deleting .settings file did, however the app still crashes after a few minutes of use, most commonly during timeline scrubbing. This issue more or less exactly reproduces my last experience with OpenShot v.?? (early 2019) , with an earlier Ubuntu on a different machine.

**Steps to reproduce the behavior:**
1. modify preferences (not sure which but probably GPU/Nvidia related); 
2. quit and reload app, it fails to launch but doesn't catch the exception, so is mysterious to GUI user without command line.
3. revert to default prefs permits launch, but app still crashes in a few minutes during some   basic timeline operation.

**Expected behavior**
Failure on launch should present a clue-ful error message, maybe suggest reloading with default preferences for GUI users unable to find the .settings file.
Crashes during normal a/v scrubbing are too frequent to use the app, and unfortunately still persist after a couple of versions, and on different Ubuntu distros and platforms.

**System Details**
- OpenShot Version: 2.6.1
- libopenshot Version:  0.2.7
- Platform: Linux-5.16.19-76051619-generic-x86_64-with-Ubuntu-21.10-impish
- Processor: x86_64
- Machine: x86_64
- Python version: 3.6.9
- Qt5 version: 5.9.5
- PyQt5 version: 5.10.1
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: en_US.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-dev-daily-9387-d909eccd-46255e46-x86_64.AppImage

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/obvckzolzko2agfsjyx0v8o3n1mvpn5w/openshot-qt.zip) (124 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/obvckzolzko2agfsjyx0v8o3n1mvpn5w/libopenshot.zip) (54 KB)

**Exception / Stacktrace**
```/tmp/.mount_MrV6wz/usr/bin/libopenshot-audio.so.8 juce::Thread::threadEntryPoint()         0xc5  [0x7fe528d19da5]
/tmp/.mount_MrV6wz/usr/bin/libopenshot-audio.so.8                                          0x152ef9  [0x7fe528d19ef9]
/lib/x86_64-linux-gnu/libc.so.6                                          0x94947  [0x7fe5542e6947]
/lib/x86_64-linux-gnu/libc.so.6 clone                                    0x44  [0x7fe554376a44]
/tmp/.mount_MrV6wz/usr/bin/libQt5Core.so.5 QAbstractEventDispatcher::registerTimer(int, Qt::TimerType, QObject*) 0x19  [0x7fe552f3c309]
/tmp/.mount_MrV6wz/usr/bin/libQt5Core.so.5 QObject::startTimer(int, Qt::TimerType)  0x6e  [0x7fe552f7006e]
/tmp/.mount_MrV6wz/usr/bin/libQt5WebEngineCore.so.5                                          0x6ca11d  [0x7fe54694311d]
/tmp/.mount_MrV6wz/usr/bin/libQt5Core.so.5 QObject::event(QEvent*)                  0x9b  [0x7fe552f6f07b]
/tmp/.mount_MrV6wz/usr/bin/libQt5Widgets.so.5 QApplicationPrivate::notify_helper(QObject*, QEv...

**Comment by Colorjet3** [comment]
Please go to openshot.org/download. click on Daily Build and download the latest DEV Daily Build available (AppImage).  Give this a try and let us know if it resolved you issue.  It might be worth deleting the entire /home/username/.openshot_qt/ folder before running the latest AppImage.
