### ISSUE TITLE
Rendering super slow 2.6.1 w/dual videos.

### ISSUE THREAD

**Issue by tdhintz** [OpenShot/openshot-qt#4778]
**Question:**
I have 3 tracks: a screen recording from an android 12 phone, video from a laptop camera, and a sound track.  Either of the two videos play fine, but combined is super slow.  Rendering using the CPU HD 720p at 30fps (1280x720) takes a whole day for even a couple minutes of video.  Disk is idle, hardly any memory is used, CPU 80% idle and GPU is idle.  Feels like the laptop has a lot more to give.

**System Details:**
- OpenShot Version 2.6.1
- Operating System / Distro: Windows 11
- i7-10750H 2.60GHz, 6 cores (12 logical), 32 gig Lenovo engineering workstation, integrated video

**Comment by Bert-H** [comment]
Have you tried the latest Daily Build?

**Comment by tdhintz** [comment]
Yes, the latest 64-bit Windows build from April 6.

**Comment by tdhintz** [comment]
The android screen recording shows just the recording, not the screen that was recorded.  If I render the android all by itself I don't see these frames, but when combined with another video I do.  Android is 60fps and I'm reducing to 30fps if that matters.
![image](https://user-images.githubusercontent.com/10895586/165493815-dffeda70-ca95-41a8-9ae0-f2d35e265506.png)
