### ISSUE TITLE
Timeline / Tracks Missing in Ubuntu 22.04

### ISSUE THREAD

**Issue by avazrod** [OpenShot/openshot-qt#4782]
**Describe the bug**
A clear and concise description of the issue

I can't add video tracks to my projects. When I load a project I can't see the video tracks.

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 2.6.1-dev
- libopenshot Version:  0.2.7-dev
- Platform: Linux-5.15.0-27-generic-x86_64-with-Ubuntu-22.04-jammy
- Processor: x86_64
- Machine: x86_64
- Python version: 3.6.9
- Qt5 version: 5.9.5
- PyQt5 version: 5.10.1
- Qt Detected Languages: ['es-ES']
- LANG Environment Variable: es_ES.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-dev-daily-9410-a956c1a9-46255e46-x86_64.AppImage

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/ecfxdqx7en3436oo55vucmaajtgid767/openshot-qt.zip) (68 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by JoergZ2** [comment]
Same problem too.

**Comment by ChrisRolando** [comment]
Same here

**Comment by jonoomph** [comment]
Fixed in https://github.com/OpenShot/openshot-qt/pull/4787
