### ISSUE TITLE
Hardware decoder doesn't work

### ISSUE THREAD

**Issue by Terrafin72** [OpenShot/openshot-qt#4785]
Question :
I can't activate the hardware decoder, it tells me that I don't have any, should I download them?

     System Details :
- OpenShot Version [e.g. 2.6.1]: {{ log_context.openshot_qt_version }}
- Operating System : Windows 10
- Spec : Intel Core i7 ; NVIDIA GeForce RTX 2060 ; 16 GO

![image](https://user-images.githubusercontent.com/69458987/166109118-3aa86727-dac2-4627-af9a-90b115b86380.png)

**Comment by davidhbrown** [comment]
When you hover the disabled menus, there's a tooltip popup that reads, "Graphics card selection not supported in Windows." Performance is painfully slow trying to display a waveform so I can synchronize a couple of video tracks, even having allocated 8GB RAM to cache. Seems like the sort of thing that would benefit from hardware decoding.
