### ISSUE TITLE
Ubuntu 22.04 Appimage 2.6.1 can't add Audio Track and Video Track

### ISSUE THREAD

**Issue by Tibsun75** [OpenShot/openshot-qt#4786]
Hello,

i have a fresh installed Ubuntu 22.04. I can start Openshot-qt.
But the timeline is empty. I can't add a audiotrack and/ or videotrack.
Therefore i can't work with openshot

[openshot-qt.txt](https://github.com/OpenShot/openshot-qt/files/8603307/openshot-qt.txt)

Same Issue with Daily build

**Comment by jonoomph** [comment]
This is fixed in https://github.com/OpenShot/openshot-qt/pull/4787
