### ISSUE TITLE
bug with audio on .wmv file imports

### ISSUE THREAD

**Issue by deadlyespresso** [OpenShot/openshot-qt#4788]
Notice: I am using Openshot 2.6.1 on Windows 10.

So i was editing a video (.wmv file format) on Openshot. When i put the file in the timeline, the audio was glitchy, being completely silent in some places. The audio for the video file had not been edited previously, and the only edits made to the file inside Openshot was trimming the video and adding a crop effect. While editing the video, I initially just thought it was just the preview, since it often tends to be a bit inaccurate the final project. However, when I exported the edited project, it had the same audio issues. What's strange about this is that .mp3 files or .wav files dont have weird audio when placed in Openshot. Is this a bug specific to .wmv files? Is there any way to make the file's audio work correctly?

**Comment by JacksonRG** [comment]
If you have a small sample of the file you're willing to share, we can take a look at the issue you're seeing.

As a quick fix, you might try converting the audio to an mp3 file, and see if the issue persists.
