### ISSUE TITLE
Ubuntu 22.04: Appimage doesn't start : libfuse.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Tibsun75** [OpenShot/openshot-qt#4789]
**Describe the bug:**

Daily Appimage OpenShot-v2.6.1-dev-daily-9432-50a9a648-46255e46-x86_64.AppImage doesn't start.

./OpenShot-v2.6.1-dev-daily-9432-50a9a648-46255e46-x86_64.AppImage: error while loading shared libraries: libfuse.so.2: cannot open shared object file: No such file or directory

**Comment by Tibsun75** [comment]
ok, i found the solution ti fix:

sudo apt install libfuse2


now it works

**Comment by JacksonRG** [comment]
@Tibsun75 Thanks for the report, and the update! We might be able to include that in our AppImage to avoid that in future.

**Comment by jonoomph** [comment]
libfuse2 must be installed to use an AppImage. It is not something we can include in our AppImage. The newer distros are switching to fuse3 though, and this is the reason so many users are seeing the libfuse2 errors. We probably need to update our AppImage to use fuse3, so they will work on the latest distros without needing to install additional libraries. But if we do that, what will happen to support on older distros, that might not have access to fuse3. This needs more research I suppose.

**Comment by haolilili** [comment]
thank you for your update, it stuck me whole day

**Comment by neoaraxis** [comment]
there is still an issue on Ubuntu 22.10

**Comment by ch4dwick** [comment]
Just sharing this warning. I just tried installing fuse libfuse2 and it practically nuked all the UI components for ubuntu 23.04.

![image](https://github.com/OpenShot/openshot-qt/assets/5561868/1de83f8b-994f-4eea-8432-fb2adf2b5367)

This is also discussed here: https://bugs.launchpad.net/ubuntu/+source/fuse/+bug/1978310

**Comment by Panzerwaffe** [comment]
+1, libfuse2 crush UI and OS booting on 23.04 Ubuntu

I described steps how to boot successfully after that (just reinstall UI):
https://askubuntu.com/a/1486019/1123066

**Comment by Colorjet3** [comment]
Hello @Panzerwaffe.  Thank you for the FYI.  
1. What prompted you to install libfuse2? 
2. What version of OpenShot are you trying to run?
3.  Are you trying to run the AppImage?
4.  Have you tried installing OpenShot using the [PPA installation](https://www.openshot.org/ppa/)?  If you give the PPA a try be sure to run the Daily Build PPA instructions.
5.  Have you tried running

**Comment by Panzerwaffe** [comment]
Hi, @Colorjet3 !

1. The message in a terminal: `dlopen(): error loading libfuse.so.2`. But in Ubuntu 23.04 fuse3 is installed by default (3.14.0-3).
2. OpenShot-v3.1.1-x86_64.AppImage file
3. Yes, as said @ch4dwick it is a bug of Ubuntu 23.04 :) Becuase other projects with appimages returns the same error about libfuse version.
4. No, I didn't try. I just tested running of appimages of different projects in GitHub
5. I am confident, that it will be installed properly via PPA ;) 

OS: Ubuntu 23.04 (kernel 6.4.11)

Thank you for your message!

**Comment by Colorjet3** [comment]
Thank you so much @Panzerwaffe for the fyi.  I know that the lead developer, @jonoomph, is aware of this issue and his response from May 26, 2022, in this thread, clearly describes the challenge with older distros vs. newer distros.  I am not a developer so this is something @jonoomph will have to deal with.  I wonder if he can somehow identify older distro vs. newer distro and load the appropriate libraries.

I've assigned this to him so he will have to review it and decide the next steps.

**Comment by chancecardona** [comment]
Can't we just install both in the appimage? There's no conflicts afaik.
Else, should be simple enough to detect the existence of libfuse3 shared lib, try to use that first, and then fall back to the current behavior if it's not installed.

**Comment by Colorjet3** [comment]
> Can't we just install both in the appimage? There's no conflicts afaik. Else, should be simple enough to detect the existence of libfuse3 shared lib, try to use that first, and then fall back to the current behavior if it's not installed.

This is why I assigned this issue to the lead developer.  He will be the one to decide the solution moving forward.

**Comment by Panzerwaffe** [comment]
@chancecardona @Colorjet3 
Hello again :D
I have noticed, if not run appimage as a program, but unpack it via
`./OpenShot-v3.1.1-x86_64.AppImage  --appimage-extract`
and then execute `./AppRun` in unpacked directory - everything works fine without error

**Comment by Cprime50** [comment]
For anyone who is having an issue getting libfuse2 by running `sudo apt install libfuse2`, heres a solution that you could try:
Get the main ubuntu repo `sudo add-apt-repository main` 
then try `sudo apt install libfuse2` again.

If this still doesn't work, another solution is to get the source package directly and install it:
The following command will download a .deb file with the binary package of libfuse2
For Ubuntu23.04(lunar Lobster) use this:
`sudo wget -P /home/ubuntu/Desktop http://archive.ubuntu.com/ubuntu/pool/universe/f/fuse/libfuse2_2.9.9-6_amd64.deb`

For Ubuntu22.04(Jammy Jellyfish) use this:
`sudo wget -P /home/ubuntu/Desktop http://archive.ubuntu.com/ubuntu/pool/universe/f/fuse/libfuse2_2.9.9-5ubuntu3_amd64.deb`

If I did not include your version(23.10, 20.04) or your distro(debain, openSUSE), please [visit here](https://pkgs.org/search/?q=Libfuse2), you'll find a list of all the distros and versions available, select yours, copy the download url and replace it in the command I showed above.

Next cd into the directory where you saved the file, in the example I gave above that would be:
`cd /home/ubuntu/Desktop` from your root directory.

 Now install the .deb file:
`dpkg -i libfuse2_2.9.9-6-amd64.deb`
That should work it hopefully.

SIDE NOTE: Do not by any chance remove or purge fuse3. Alot of immportant packages like ubuntu-desktop, gnome shell extension and many other important packages are dependent on fuse3, so you will completely crash your OS.

**Comment by boriel** [comment]
I solved this with `apt install libfuse2t64` which comes with Ubuntu 24.04 and can coexist with `libfuse3-3` :-)

**Comment by maresmar** [comment]
It's `sudo dnf install fuse-libs` for Fedora 41.

**Comment by sunsun8170** [comment]
> It's `sudo dnf install fuse-libs` for Fedora 41.

Thanks! This works for me.
