### ISSUE TITLE
can't export

### ISSUE THREAD

**Issue by bell18** [OpenShot/openshot-qt#479]
it won't let me export

**Comment by TombyT** [comment]
I am usually able to only get to 51% exporting to 1080p 60fps MP4. Sometimes if I'm lucky I can still view the halfway created file.

**Comment by bell18** [comment]
i was able to export 93%

**Comment by chibill** [comment]
My openshot goes non-responsive on export.

**Comment by bell18** [comment]
can this be fixed?

**Comment by reaposowitory** [comment]
The best I've ever gotten on any export setting was 20% of a < 6 min clip.  It usually freezes at 7% or lower.  The lowest resolution export I've attempted was a HD 720
25 fps (after getting frustrated tyring to use the file's native 1080p format.)

When it's frozen 'htop' reports the following for the process command associated with the clip conversion:
PRI = 20
NICE = 0
CPU% > 100 (observed registering 99.8% - 107%)
MEM% = 1.2
RES = 84168
SHR = 3180
VIRT = 6051M
STATE (S) = R

System MEM bar is almost maxed: 6.16G/6.77G
System Swap registers: 4.68G/G.96G

The proceass also seems to be exlclusively maxing out one of the four CPU cores, while not not doing much with the others.  The core that is affected varies during the frozen phase.  Every minute or two, the core registering  the 100% usage changes to a different core. 
The rest vary from 8% - to about 20% (depending on if anything else is consuming resources.) which changes from time to time.

System specs for reference (laptop):
Ubuntu 16.04 LTS 64-bit
Mem: 6.8 Gb
Proc: AMD A8-6410 APU with AMD Radion R5 Graphics x 4
Graphics: Gallium 0.4 on AMD MULLINS (DRM 2.43.0, LLVM 3.8.0)

I've accessed the project data from a networked drive, a USB 3.0 external SSD and an internal SSD.  All result in the same behavior.

I have to xkill or other wise manually disrupt the process, as the conversion window will not respond.  Interestingly, the main window will respond to most commands.  Except to close or quit.

I don't know if any of this info helps.

**Comment by jonoomph** [comment]
We have recently solved a bunch of similar issues with freezing exports. This should be fixed now in our latest daily builds. Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot. If the problem still occurs on the latest daily build, please see these instructions (https://github.com/OpenShot/openshot-qt/blob/master/.github/CONTRIBUTING.md) for generating log files, and reopen this issue with logs attached, and I'll take another look. Thanks!
