### ISSUE TITLE
Ubuntu 22.04 , Blender is not working, AppImage dailyfrom 03 may

### ISSUE THREAD

**Issue by Tibsun75** [OpenShot/openshot-qt#4790]
**Describe the bug:**
Blender, tested with several Versions is not working.
I tested this with latest daily from 03 May and with several blender versions from 2.8.3 up 3.1

[logfile.txt](https://github.com/OpenShot/openshot-qt/files/8633574/logfile.txt)

**Comment by eliboni** [comment]
ref. #4518  - it works installing from ppa, not with appimage - but  ppa has only 2.6.0 stable, not daily

**Comment by JacksonRG** [comment]
@eliboni Just had good luck testing with the new daily build. @Tibsun75 Could you see if the new version fixes this issue?

**Comment by Colorjet3** [comment]
Not sure what you mean with not working but with the latest DEV Daily Build AppImage of OpenShot, I am able to integrate it with Blender and create Animated Titles.  Go to openshot.org/download/#daily.  Download the latest available Daily Build and give it a try.

**Comment by Colorjet3** [comment]
Hello @Tibsun75   I dug into this further and found some issues with integrating smoothly with Blender and Inkscape with Ubuntu.

Check this out:  https://github.com/OpenShot/openshot-qt/wiki/Blender-and-Inkscape-Guide

I had to uninstall both inkscape and blender via the software manager (snap) and then using the command prompt to reinstall blender and inkscape.  And now I can easily integrate the apps.
