### ISSUE TITLE
"Openshot Video Editor has stopped working" after start

### ISSUE THREAD

**Issue by Fitnesator** [OpenShot/openshot-qt#4791]
**Describe the bug**
A clear and concise description of the issue

I had some issues on 2.5.1.  (freezing during exporting video files) so I followed advice here
https://www.reddit.com/r/OpenShot/comments/qxshdm/openshot_issues_before_and_after_update_261/

And reinstalled using last daily buds. Now I receive win10 pop-up "Openshot Video Editor has stopped working"  immediately after start

**Steps to reproduce the behavior:**
1. Start Open shot
2. See message
3. Try do not cry

**Expected behavior**
Use the program

**System Details**
- OpenShot Version: 2.6.1-dev
- libopenshot Version:  0.2.7-dev
- Platform: Microsoft Windows 10 Pro	10.0.18363 Build 18363
- Processor: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz, 1800 Mhz, 4 Core(s), 8 Logical Processor(s)

- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-dev-daily-9432-50a9a648-46255e46-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/piteee8dkrejqh5f441nmpqi6yeu63dt/openshot-qt.zip) (51 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/piteee8dkrejqh5f441nmpqi6yeu63dt/libopenshot.zip) (4 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You ca
![image](https://user-images.githubusercontent.com/105044008/167093661-0007ac9b-1309-4fd5-be54-d77be2cc0797.png)
n include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by JacksonRG** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Failed to get Version](https://trello.com/c/dl1fzNQM/118-failed-to-get-version)

**Comment by JacksonRG** [comment]
Interesting... For one thing, your log files say that we're detecting 44100 Hz, 2 channel for your audio sampling frequency. But we're setting your Samples per second to 2 instead of 44100.

But the last line of the log is a failure to get version info for issue logging. I'll look into how we can handle it better if that request fails.

**Comment by JacksonRG** [comment]
I think I had the wrong idea here. Our version checking code is quite safe. I just forced it to error, and had no issue. If you start in debug mode, we may get more info on what happened here.
Could you open powershell and launch openshot with these commands?

`cd 'C:\Program Files\OpenShot Video Editor\'`
`.\openshot-qt.exe --debug`

I assumed that Openshot was failing where your log ends, but debug mode may give a little more info in the logs.

**Comment by Colorjet3** [comment]
This is a known bug and is fixed in the latest DEV Daily Build of v3.0.0.  Please go to openshot.org/download/#daily, download and install it.  This should fix it.

**Comment by Colorjet3** [comment]
No Response
