### ISSUE TITLE
Simple mouse double click issue

### ISSUE THREAD

**Issue by PeteCrowe** [OpenShot/openshot-qt#4792]
iMac - Monterey

1. Go to Export video file (Cmd + E), or any dialog box generated by OpenShot (e.g. Cmd + T), and attempt to double click any word in user editable fields. The normal convention of selecting the entire word when double clicking on that word is not working.

Works fine in Windows (10).

Daily build still the same issue.

Thx.

**Comment by JacksonRG** [comment]
@PeteCrowe Thanks for pointing this out. Is this true anywhere else in the Program? Could you try the text boxes in the Preferences window, and let us know if that has the same issue?

**Comment by PeteCrowe** [comment]
Same issue with the Preference window, and the Titles dialog (all areas
including color selection).

Essentially, any area in the program where text input is offered, the
double-click word selection standard is not functioning. Oddly, it seems to
always attempt to select half of the word. If there are seven characters,
the first 3 get selected.

Not sure if that helps with finding the cause.

Regards,

Peter

**Comment by JacksonRG** [comment]
Very interesting. We can take a look. Though that may be an issue in *Qt*, the UI library we make use of. In general, we tell Qt to place a textbox, and the specifics of how textboxes work is up to the library.

All that to say, this may not be a quick fix, but I'm glad you pointed it out.

**Comment by PeteCrowe** [comment]
Wish I could help out with that! Love this software, but am still a newbie
with much to learn.

Thanks for your great work.

Peter

**Comment by JacksonRG** [comment]
And thanks for your attention to detail! This is certainly intriguing. May indicate that our Qt version could be updated. I hope you can abide this quirk for a little while, as our team has to prioritize bugs that keep people from using OpenShot, and affect lots of people.

As a work-around, I'd recommend trying `ctrl+shift+arrowkey` (ctrl might be option or cmd on a mac keyboard) to quickly select text. If that *doesn't* work... then that's even more interesting.

**Comment by Colorjet3** [comment]
Please download the latest DEV Daily Build from openshot.org/download/#daily and give it a try.
