### ISSUE TITLE
Part of screen footage x2 speed after export

### ISSUE THREAD

**Issue by Oz8400** [OpenShot/openshot-qt#4794]
Hi,

I just started to make videos and a youtube channel. I use openshot as my editing software and i recorded a video in obs using my screen recording and my webcam to catch my reaction (in the corner of my screen) while i was recording some gaming footage. When the record was done i went in openshot for the editing and everything was perfect in the preview, so i hit the export button without touching the settings as i'm still a beginnner. The issue is when the video gets exported my webcam goes x2 speed while the audio and the rest of the video goes at the normal speed, after 10 minutes of video the webcam become normal again but is not in sync at all with the rest of the video. Tried multiple export with same result...

It's weird because in the preview none of that happens, so if you guys could help me out, didn't found anybody with the same problem. Is the video too long ? it's 1h30m +- maybe that could be  the cause?

Let me know =)

Cheers,
Oz

**Comment by Oz8400** [comment]
nvm, updated my software and exported another time and everything is fine :)

**Comment by JacksonRG** [comment]
Glad to hear it! Let us know if you have any other problems!
