### ISSUE TITLE
windows: Title installed inkscape

### ISSUE THREAD

**Issue by telelauro** [OpenShot/openshot-qt#48]
I try to insert a title in my computer already installed Inkscape, and still will not let me insert a text in the project.

**Comment by ankitpati** [comment]
Can you please clarify the wording, and confirm if the issue persists in the latest stable [release](http://github.com/OpenShot/openshot-qt/releases/download/v2.2.0/OpenShot-v2.2.0-x86_64.AppImage "OpenShot 2.2")?

Closing due to age of the issue. Please reopen if necessary.
