### ISSUE TITLE
My Project Stops Opening

### ISSUE THREAD

**Issue by WildxBella** [OpenShot/openshot-qt#480]
This is not like the other ones, hopefully, but I made this music video for a game online using OpenShot Video Editor. It is on an acer laptop, and ubuntu is used for sure. After a long, long time, I finally finished it. I was ready to export the video, and I did export it. I opened the mp4 to the final exported video, and it says:

"Error, this file contains no streams." OK

It's odd, since it works on all my other videos, but this one... strange.

I decided to export my project into an mp4 again, but this time, while it was exporting, my whole laptop froze. I had only one choice but to shut it down forcefully.

I finally got it back on, and it left me another exported video that still contained no streams, so I deleted both of those failed mp4s and tried to export it one more time,

but while I was opening my project, it opens, but another small OpenShot tab is open, but it is blank, and it has the same box shape as the "Export Video". 

Then 5 seconds of loading and it closes automatically. Both my project and that small tab closes without any control of clicking on the project. You can't close the tab, or it will say, "Cannot close, force quit?"

It keeps happening whenever I open that Project, no matter what way I try to open it. My hard work is down the drain. The files are attached if you do not get what I mean. Thanks.

![screenshot 2017-01-17 14 57 48](https://cloud.githubusercontent.com/assets/25186172/22043646/70b85402-dcc5-11e6-8e2e-5cf3c5239aef.png)
![screenshot 2017-01-17 14 57 42](https://cloud.githubusercontent.com/assets/25186172/22043644/70b6083c-dcc5-11e6-96c0-ab2b3b2bcee3.png)
![screenshot 2017-01-17 14 57 27](https://cloud.githubusercontent.com/assets/25186172/22043645/70b620b0-dcc5-11e6-9dc8-da15b2cbc326.png)

**Comment by jonoomph** [comment]
Hi @WildxBella Please test with our latest daily build of OpenShot 2.x. Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot. Your screenshots posted are from OpenShot 1.4.3, a very old version. Please reopen this issue if OpenShot 2.x does not solve your problem. Thanks!
