### ISSUE TITLE
Improve default render target

### ISSUE THREAD

**Issue by dhjw** [OpenShot/openshot-qt#4801]
**Describe the new feature:**
When clicking Render the default Target is always CPU MP4 (h.264), despite having set all Hardware Encoder and Decoder options to VA-API in Preferences > Performance.

Default Target could match the setting for Hardware Encoder Graphics Card, i.e. VA-API MP4 (h.264 va), so it doesn't have to be manually selected on every render.

In the alternative, it could simply default to the last used target, which would be helpful to both me and people who prefer some other setting.

**Comment by JacksonRG** [comment]
This is a good idea. I think preserving the last used setting will be useful to the most people. It means fewer assumptions made by OpenShot, and we could take it a bit further preserving other export settings between exports.

**Comment by DevSelchow** [comment]
This would be a very good improvement.
Preserving the last export settings would save a lot of time.
