### ISSUE TITLE
'NoneType' has no attribute 'get'

### ISSUE THREAD

**Issue by Ednaordinary** [OpenShot/openshot-qt#4804]
**Describe the bug:**

Openshot installed from development ppa (or built from source) fails to open a recent project, and imports are weird.

**Steps to reproduce the behavior:**
1. Install openshot development branch
2. run
3. Attempt to open a recent project, or import a file

**Expected behavior:**

Openshot properly imports the file, or opens the recent project

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 2.6.1-dev
- Operating System / Distro: Ubuntu 22.04

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/8759490/openshot-qt.log)

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/main_window.py", line 468, in open_project
    app.project.load(file_path, clear_thumbnails)
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/project_data.py", line 366, in load
    self.check_if_paths_are_valid()
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/project_data.py", line 959, in check_if_paths_are_valid
    path = clip.get("reader", {}).get("path", "")
AttributeError: 'NoneType' object has no attribute 'get'

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

![image](https://user-images.githubusercontent.com/88869424/169948044-f475cbe4-92f8-43e4-91d0-525e3a9cbc29.png)

**Comment by Ednaordinary** [comment]
I might have just corrupted the .osp, which I'm not entirely sure how happened given I was only working with it in openshot (but they are different versions, and some are somewhat broken, so that could be it)
Anyways someone can close this or delete it if they want, or keep it open if it's interesting. I have to rebuild the entire project from scratch which isn't great but at least I have a working version of openshot

**Comment by JacksonRG** [comment]
Sorry to hear that. If you have any similar problems in the future, openshot makes periodic backups of projects (after you've saved them a first time) [here](https://github.com/OpenShot/openshot-qt/wiki/Project-Recovery) are instructions on finding those backups, in case one is not corrupted.
