### ISSUE TITLE
Crash when moving timeline area on Mac

### ISSUE THREAD

**Issue by petri-lipponen-movesense** [OpenShot/openshot-qt#4805]
**Describe the bug:**
OpenShot crashes often when manipulating timeline and previewing on Mac. Sometimes the issue is accompanied with stuttering of the preview but not always.

**Steps to reproduce the behavior:**
1. Add a bunch of clips to timeline
2. Play preview
3. Move the timeline hilite area (blue thing)
4. See the app crash away

**Expected behavior:**
App doesn't crash

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: MacbookPro OSX 11.3.1

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

[Openshot_logs.zip](https://github.com/OpenShot/openshot-qt/files/8762369/Openshot_logs.zip)

**Exception / Stacktrace:**
`14:47:30 ERROR main_window: Unhandled crash detected: mac-read16threadEntryPointEv + 282`

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by DanPinGF** [comment]
Possibly related to issue #4441.

**Comment by Colorjet3** [comment]
Please download the latest DEV Daily build of v3.0.0 and give it a try:  openshot.org/download/#daily
