### ISSUE TITLE
"NoneType" object is not subscriptable

### ISSUE THREAD

**Issue by twinda** [OpenShot/openshot-qt#4806]
**Descrivi il bug**
A clear and concise description of the issue

**Passi per riprodurre questo comportamento:**
1. Vai su '...'
2. Fai clic su '....'
3. Scorri fino a '....'
4. Nota l'errore

**Comportamento atteso**
Una descrizione breve e concisa di cosa ci si aspetta dovrebbe succedere.

**Dettagli di sistema**
- OpenShot Version: 2.6.1-dev
- libopenshot Version:  0.2.7-dev
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['it-IT', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-dev-daily-9481-664c5db8-46255e46-x86_64.exe

**File di registro**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/07vcar0rztn65eo6igkjv93bcyercmp9/openshot-qt.zip) (6 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Errore / Stack trace**
```No stacktrace found in log files```

**Schermate** (Facoltativo)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by JacksonRG** [comment]
@twinda Hi, could you include more info on what issue you're running into? For instance you could tell us what you were doing when it happened, or how you can repeat this problem.

Thanks
