### ISSUE TITLE
Can't import some mp4 files.

### ISSUE THREAD

**Issue by MCCatYt** [OpenShot/openshot-qt#4807]
I can't import some files(some of the MP4) Everytime I do IT CRASHES, Please fix this, It ruined so many stuff.

**Comment by JacksonRG** [comment]
@MCCatYt You mentioned ruined stuff. If you have projects you can't open, a previous version of the project may have been saved by OpenShot. [Here](https://github.com/OpenShot/openshot-qt/wiki/Project-Recovery) are instructions for attempting to recover your projects.

Do all file imports crash OpenShot? If not, could you include one that is causing this?
Also you can import files by dragging the file onto the timeline, or by right clicking the files window. Do both of these methods cause a crash?

**Comment by MCCatYt** [comment]
Yes both methods crash and for some reason I discovered something. OpenShot
only imports full screen video so like 16:9 it doesn't work on Other Aspects

**Comment by Colorjet3** [comment]
Please download the latest DEV daily build from openshot.org/download/#daily and give it a try.
