### ISSUE TITLE
Alpha masks don't work in version 2.6.1

### ISSUE THREAD

**Issue by VisionaryMind** [OpenShot/openshot-qt#4809]
**Describe the bug:**
It is currently not possible to select the source for an alpha mask in Openshot version 2.6.1. I am using the latest AppImage.

**Steps to reproduce the behavior:**
1. Import clip
2. Import clip with mask
3. Drag and drop and Alpha Mask filter onto the first clip.
4. Click on the alpha mask filter icon to open the panel
5. There is a source field, but it is not possible to populate it.

**Expected behavior:**
Either type of the name of the file to use as the mask (image or video clip) or, optimally, right-click on the Source field to select an item from the file list. Typing the name of the file and hitting enter does nothing. The field remains blank. There is no menu available when right-clicking on the source field (either the label or the field itself).

This is a useful feature. It seems to have been added quite some time ago, so it's unclear at which point it broke. 

**System Details:**
- OpenShot Version 2.6.1
- Operating System / Distro: Ubuntu 20.04 LTS

**Comment by JacksonRG** [comment]
Hi @VisionaryMind, thanks for reporting this. Just to make sure this hasn't been fixed yet, does the right click still not work on the most recent [daily build](https://www.openshot.org/download/)?
