### ISSUE TITLE
Unable to change language or theme

### ISSUE THREAD

**Issue by Caloxeno** [OpenShot/openshot-qt#481]
When I change the language and the theme, it tells me to restart the application to see the changes. But when I do, everything is as it was. It doesn´t matter how many times I try, the same happens always.

**Comment by jreynojustin** [comment]
Hi @Caloxeno some additional details would be helpful on this matter. Could you let us know what operating system you are running and the language/theme you are trying to switch to. Thank you!

**Comment by jonoomph** [comment]
@Caloxeno Please let us know the version of OpenShot, the operating system, and what language and theme options you are selecting. Also, please attach your settings files (~/.openshot_qt/openshot.settings). Please reopen this issue once those things are done. Thanks!
