### ISSUE TITLE
openshot is closing 1sec after openning

### ISSUE THREAD

**Issue by adgm1** [OpenShot/openshot-qt#4810]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 2.6.1-dev
- libopenshot Version:  0.2.7-dev
- Platform: Windows-10-10.0.19041
- Processor: AMD64 Family 23 Model 1 Stepping 1, AuthenticAMD
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['fr-FR', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-dev-daily-9495-664c5db8-46255e46-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/tusg6fn81z6kcjspelt0a8bo65n96s7j/openshot-qt.zip) (12 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/tusg6fn81z6kcjspelt0a8bo65n96s7j/libopenshot.zip) (190 KB)

**Exception / Stacktrace**
```_C_specific_handler            7ffb894d7f60
_chkstk                        7ffb8a2f1f80
RtlRaiseException              7ffb8a2a1020
KiUserExceptionDispatcher      7ffb8a2f0ba0
ZNopenshot::TrackedObjectBBox::SetJsonValue::Json::Value 7ffb1b815870
ZNopenshot::Tracker::SetJsonValue::Json::Value 7ffb1b8222f0
ZNopenshot::Clip::SetJsonValue::Json::Value 7ffb1b74b6a0
ZNopenshot::Timeline::SetJsonValue::Json::Value 7ffb1b7b6800
ZNopenshot::Timeline::SetJson::__cxx::basic_stringIcSt::char_traits 7ffb1b7a7740
???
PyLong_FromUnsignedLong        7ffb4e5af890
PyEval_EvalFrameDefault        7ffb4e590a00
PyEval_EvalCodeWithName        7ffb4e58cbd0
PyFunction_Vectorcall          7ffb4e5a0770
PyEval_EvalFrameDefault        7ffb4e590a00
PyCell_New                     7ffb4e5a0990
PyEval_EvalFrameDefault        7ffb4e590a00
PyCell_New                     7ffb4e5a0990
PyEval_EvalFrameDefault        7ffb4e590a00
PyCell_New                     7ffb4e5a0990
PyEval_EvalFrameDefault        7ffb4e590a00
PyEval_EvalCodeWithName        7ffb4e58cbd0
PyFunction_Vectorcall          7ffb4e5a0770
PyEval_EvalFrameDefault        7ffb4e590a00
PyEval_EvalCodeWithName        7ffb4e58cbd0
PyFunction_Vectorcall          7ffb4e5a0770
PyMethod_New                   7ffb4e5ac0c0
PyEval_EvalFrameDefault        7ffb4e590a00
PyCell_New                     7ffb4e5a0990
PyMethod_New                   7ffb4e5ac0c0
PyVectorcall_Call              7ffb4e5ac590
PyInit_QtCore                  7ffb21f4a730
PyInit_QtCore                  7ffb21f4a730
PyInit_QtCore                  7ffb21f4a730
PyInit_QtCore                  7ffb21f4a730
PyInit_QtCore                  7ffb21f4a730
ZNQMimeType::qt_static_metacall::QObject::QMetaObject::Call 7ffb20216800
PyInit_QtCore                  7ffb21f4a730
PySet_New                      7ffb4e5bab00
PyEval_EvalFrameDefault        7ffb4e590a00
PyCell_New                     7ffb4e5a09...

**Comment by JacksonRG** [comment]
Hi @adgm1 have you installed openshot before, and just upgraded? Or is this your first time installing?

**Comment by adgm1** [comment]
hi. yes I have already installed it before. I uninstalled it and reinstall many times but still the same.

**Comment by adgm1** [comment]
any idea why it does not load?

**Comment by JacksonRG** [comment]
I'm not sure. But in some cases there's an old setting that's causing problems. Could you try renaming the file `openshot.settings` in `C:\Users\<your user name>\.openshot_qt\` to `openshot.settings_old`?

Openshot will create a new settings file. Just in case the issue is there.

**Comment by adgm1** [comment]
no infortunately it doesn t work. Still shuting down after 1 second. the 2 logs I posted can not help to understand the origin of the problem?

**Comment by adgm1** [comment]
Yes I had already installed it before. But I uninstall it and reinstall and still the same

Le 1 juin 2022 à 23:38, à 23:38, JacksonRG ***@***.***> a écrit:

**Comment by Colorjet3** [comment]
Please download the latest DEV daily build of v3.0.0 from openshot.org/download/#daily and this should fix the issue.
