### ISSUE TITLE
Buenas tardes

### ISSUE THREAD

**Issue by marsa-coder** [OpenShot/openshot-qt#4811]
**Question:**
A clear and concise question. Your question should provide enough context and explanation for people to answer it. Avoid excessive background or irrelevant details, as they can obscure your actual question.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your question. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by JacksonRG** [comment]
I'm closing this issue, as I believe it was accidentally posted.

I'll help you on issue #4812

**Comment by marsa-coder** [comment]
Buenos dias
Ya consegui solucionarlo
Gracias

De: JacksonRG ***@***.***>
Enviat: dimecres, 1 de juny de 2022 23:44
Per a: OpenShot/openshot-qt ***@***.***>
A/c: Marsa Amenos ***@***.***>; Author ***@***.***>
Tema: Re: [OpenShot/openshot-qt] Buenas tardes (Issue #4811)


Closed #4811<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOpenShot%2Fopenshot-qt%2Fissues%2F4811&data=05%7C01%7Camenos%40tnc.cat%7C42cc608f716f4117ba6d08da4417e477%7Ce83d3a0945e64dfe90e6ed0a3dac50b8%7C1%7C0%7C637897166661128224%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Z32KwMRKZ1mDb7yzk38ZR5iziUEwClwFPic5rJ8x2rM%3D&reserved=0> as completed.

-
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOpenShot%2Fopenshot-qt%2Fissues%2F4811%23event-6723328718&data=05%7C01%7Camenos%40tnc.cat%7C42cc608f716f4117ba6d08da4417e477%7Ce83d3a0945e64dfe90e6ed0a3dac50b8%7C1%7C0%7C637897166661128224%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=gXPZQJA1TlCFWQ1OnPAFMiGlZe0wBArULvORorb2v%2FU%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAZLW7QUAEH5WJ65CDQMI4JTVM7KTNANCNFSM5XEPEDEQ&data=05%7C01%7Camenos%40tnc.cat%7C42cc608f716f4117ba6d08da4417e477%7Ce83d3a0945e64dfe90e6ed0a3dac50b8%7C1%7C0%7C637897166661128224%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QJ%2FwAYOQrikEJuQ2gs%2Flby0JMhsXsalUIo6%2BzcK3EyA%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

[https://www.tnc.cat/uploads/20220523/TNC-2022-2023_Firma_600x200px.jpg] FIRMA CORREU ELECTR?NIC CORPORATIU D'acord amb la Llei de protecci? de dades de car?cter personal, li fem saber que les dades que figuren en aquesta comunicaci? estan incloses en els sistemes d'informaci? propietat del Teatre Nacional de Catalunya, SA. En qualsevol moment vost? podr? exercir els drets d'acc?s, rectificaci?, oposici?, limitaci? i, si escau, portabilitat o cancel*laci?, comunicant-ho per escrit i indicant les seves dades personals a l'adre?a ***@***.*** Pot accedir a m?s informaci?, mitjan?ant l'enlla? seg?ent: https://www.tnc.cat/ca/politica-privacitat
