### ISSUE TITLE
Crashes On Import Of MP4

### ISSUE THREAD

**Issue by Ruby-Dragon** [OpenShot/openshot-qt#4814]
**Describe the bug:**
openshot crashes immideately after importing any MP4 file.

**Steps to reproduce the behavior:**
1. Open OpenShot
2. Drag and drop MP4 file into timeline
3. ???
4. crash

**Expected behavior:**
video is put into openshot

**System Details:**
OpenShot (version 2.6.1)            

openshot-qt version: 2.6.1
libopenshot version: 0.2.7
platform: Windows-10-10.0.19041
processor: AMD64 Family 25 Model 80 Stepping 0, AuthenticAMD
machine: AMD64
python version: 3.8.9
qt5 version: 5.15.2
pyqt5 version: 5.15.4

**Log Files:**
[.openshot_qt.zip](https://github.com/OpenShot/openshot-qt/files/8793795/default.openshot_qt.zip)

**Comment by JacksonRG** [comment]
Taking a look at your log file. Have you tested this issue on our daily build? You can download it [here](https://www.openshot.org/download/).

**Comment by JacksonRG** [comment]
Also, I'm curious if anything different happens if you right click on the files section and click `import files`.

**Comment by Ruby-Dragon** [comment]
that also failed

**Comment by Ruby-Dragon** [comment]
i am getting around it by using an older version of openshot

**Comment by JacksonRG** [comment]
By "that also failed" do you mean the daily build, or importing by right click? Just so I know where to look for this issue.

**Comment by Ruby-Dragon** [comment]
importing via file>import

**Comment by aaflatooni** [comment]
I have noticed that it isn't all the video files. There are certain ones that takes a while and then crashes.

**Comment by JacksonRG** [comment]
@aaflatooni Are any of the crashing files one you'd be willing to share? And what Openshot Version and Operating System are you seeing this issue on?

**Comment by aaflatooni** [comment]
OpenShot 2.6.1
libopenshot: 0.2.7
Edition	Windows 10 Home
Version	21H1
Installed on	‎1/‎20/‎2021
OS build	19043.1706
Experience	Windows Feature Experience Pack 120.2212.4170.0


Attaching the video file as well.
https://user-images.githubusercontent.com/42128476/172478394-d972b6f9-cdf1-432a-b842-b8dd6c82a5ff.mp4

**Comment by Colorjet3** [comment]
Please go to openshot.org/download/#daily and download the latest DEV Daily Build of v3.0.0.  Install and give it a try.
