### ISSUE TITLE
Einsprungpunkt nicht gefunden!

### ISSUE THREAD

**Issue by SteffenDue** [OpenShot/openshot-qt#4815]
"Der Prozedureinsprungpunkt "CRYPTO_atomic_read" wurde in der DLL .. libssl-1-x64.dll nicht gefunden."
Schade das man hier keinen Screenshot einfügen kann..
Habe es mit neu installierter Version 2.6.1 mal wieder probiert.
mfg Steffen Dünnebier

**Comment by JacksonRG** [comment]
@SteffenDue Have you tried downloading the latest daily build here: https://www.openshot.org/download/

If that doesn't work, could you include what operating system you were using, and the log files?

 Those files can be found here:
`C:\Users\userName\.openshot_qt\` on windows
or here
`/home/userName/.openshot_qt` on linux or mac
Both end in `.log`

**Comment by Colorjet3** [comment]
Hello, did you download the latest daily build and gave it a try?

**Comment by Colorjet3** [comment]
No response from user.
