### ISSUE TITLE
Unable to edit or duplicate the title

### ISSUE THREAD

**Issue by Ennazus1234** [OpenShot/openshot-qt#4816]
[

**Describe the bug:**
I created a title, using InkSkape. But when I tried to dubplicate the title, it does not work. Also, when I click on edit title, the editing window doesn't appear. The problem only occurs with this one title I created myself with InkScape, not with the other titles.

**Steps to reproduce the behavior:**
1. Go to 'Title'
2. Click on 'Duplicate Title' or 'Edit Title'
3. Nothing happens.. 

**Expected behavior:**
When I clicked on 'Duplicate Title', I was expecting the title would duplicate, but nothing happens. When I click on Edit Title, I expected that the Editing Window would appear, but this also does not happen.

**System Details:**
- OpenShot Version 2.6.1-dev 
- Operating System / Distro: Windows 10 Home

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs

[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/8800507/libopenshot.log)

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by JacksonRG** [comment]
@Ennazus1234 It looks like you copied our changelog into `libopenshot.log`. [Here](https://github.com/OpenShot/openshot-qt/wiki/Issue-Logging) are instructions for finding your log files. You don't have to delete and re-create the issue. But could you drag those into a comment to share them?
