### ISSUE TITLE
OpenShot Timeline Glitch

### ISSUE THREAD

**Issue by KKaydoom** [OpenShot/openshot-qt#4817]
When I click above the timeline it moves the marker but not the line below and then I can no longer move it.
![image](https://user-images.githubusercontent.com/106564078/171069169-b88772a7-0f18-432e-bb71-75309f2e34f1.jpg)

**Comment by JacksonRG** [comment]
@KKaydoom Hi, could you include some more info about how you got this to occur? Some useful info would be:
- What operating system you're using
- What version of OpenShot this happened with
- Instructions to repeat this bug
- Also attaching your log files for us to look at. (Instructions [here](https://github.com/OpenShot/openshot-qt/wiki/Issue-Logging))

Thanks for pointing out this issue, with that extra info, we should have a much better time finding a solution.

**Comment by Colorjet3** [comment]
Please download the latest available version and give it a try.

**Comment by Colorjet3** [comment]
The latest DEV Daily Build v3.0.0 fixes this issue.
