### ISSUE TITLE
Openshot-qt opent niet op ubuntu 22.04lts

### ISSUE THREAD

**Issue by quintenvg1** [OpenShot/openshot-qt#4818]
**Omschrijf het probleem**
Openshot doensn't open on ubuntu.

**Stappen om het probleem te reproduceren:**
clean install ubuntu 22.04lts.
run sudo apt update && sudo apt upgrade -y
then run sudo apt install openshot-qt
try to open openshot from terminal
watch as it gives a debug prompt but doesn't open the program itself.

**Verwacht gedrag**
open openshot from terminal
window pops up and openshot is ready to build a new project?

**Systeemgegevens**
- OpenShot Version: 2.5.1
- libopenshot Version:  0.2.5
- Platform: Linux-5.15.0-33-generic-x86_64-with-glibc2.35
- Processor: x86_64
- Machine: x86_64
- Python version: 3.10.4
- Qt5 version: 5.15.3
- PyQt5 version: 5.15.6
- Qt Detected Languages: ['nl-BE', 'nl']
- LANG Environment Variable: nl_BE.UTF-8
- LOCALE Environment Variable: 
- Dagelijkse build: niet in staat om te verifiëren of het probleem nog steeds bestaat in de dagelijkse build

**Logbestanden**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/w9gd60rrv8hhtu80gbtp4a3zu7t4ol73/openshot-qt.zip) (20 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/w9gd60rrv8hhtu80gbtp4a3zu7t4ol73/libopenshot.zip) (1 KB)

**Uitzondering / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Naar keuze)
Voeg, indien van toepassing, een schermafdruk toe om uw probleem te helpen verduidelijken.
U kunt afbeeldingen toevoegen door ze GitHub te kopiëren/plakken, of ze naar de GitHub-pagina te 
slepen. Alle afbeeldingen zijn openbaar, dus plaats geen afbeeldingen die persoonlijke informatie bevatten.

**Comment by JacksonRG** [comment]
Your issue post says you're using version 2.5.1, Is that true? Looking at your logs, it looks like the issue you're having was fixed in pr #3702. Are you able to download version 2.6.1, or the daily build? They're available at https://www.openshot.org/download/

**Comment by Colorjet3** [comment]
Go to openshot.org/download/#daily and download the latest DEV Daily Build available.  The AppImage should work.

**Comment by Colorjet3** [comment]
No response from user.
