### ISSUE TITLE
deinterlaced mp4 h264

### ISSUE THREAD

**Issue by gofatas** [OpenShot/openshot-qt#482]
Hi, Im trying to export an mp4 in h264 codec with deinterlaced fields. My proyect is 1920x1080 25i. After changing the export parameters several times the final result is always a progressive video.

I have tried with false and true interlaced and has never worked.

What Im doing wrong?

Thank you

**Comment by Kagetsuki** [comment]
This may sound stupid but have you tried de-interlacing your source video by transcoding it with something like ffmpeg, then importing the result of the transcode instead? Generally you should have all source materials in as generic a format as possible - so importing interlaced video just sounds like a bad idea to begin with.

**Comment by Kagetsuki** [comment]
@jonoomph These import issues are so common I'm thinking maybe it would be a good idea to decide on an intermediary format that's easy/quick to work with, and when a video is imported that's not in that format prompt the user to covert it like "This video is in a format that may be difficult for OpenShot to work with, would you like us to convert it to an intermediary format?" and if so just run it through ffmpeg or avconv and save the output in a temporary folder. There's definitely a few formats and variants that OpenShot doesn't like and that's something I had to find out the hard way myself.

As for this issue - @gofatas was this resolved? Can we close this?

**Comment by jonoomph** [comment]
@gofatas, please use the de-interlace effect on your source video clip, and then export using any format. I need to revisit the "Interlaced" profile setting on the Advanced tab and see if we still need that. If the problem still happens, please reopen and we'll take another look.

@Kagetsuki Thanks for the suggestion, but OpenShot already does something very similar. All videos are processed by FFmpeg in realtime, and converted to an OpenShot specific data structure, so they can be merged, previewed, edited, etc... Now, some are more CPU intensive than others, and it might make sense to auto-convert those into another codec... but that is a pretty big feature. =)
