### ISSUE TITLE
Implement custom speed Time Fast/Slow Forward/Backward values

### ISSUE THREAD

**Issue by mzagrabe** [OpenShot/openshot-qt#4822]
**Describe the new feature:**

There isn't an easy, user-friendly way to use a non-default speed value for Time -> Fast -> Forward (and other Time Fast/Slow operations). For instance, I'd like to be able to use a speed of 1.5x for Fast Forward.

**Describe the solution you'd like:**

It would be great to have a "Custom" value in the list that pops up a dialog box where you can enter the speed that you'd like to use.

**Describe alternatives you have considered:**

One can set the number of rendered frames to work-around this limitation, but it would be great to have the feature be part of the standard offering.

**Comment by JacksonRG** [comment]
@mzagrabe This is certainly a point we want to improve, and make more graphical. But for the time being, here's how you can speed up or slow down videos outside of the `right click` -> `time` options:


**These instructions allow you to create a video of whatever length you like:**
1. Right click and choose "time > normal > forward > 1X"
1. Click on the keyframe that appears at the end of the clip and open the properties menu (Ctrl+i or right click to open)
1. The "Time" property of that keyframe is number of frames in your file. Copy that number.
1. Now edit the "end" property to how long you want the video to last in seconds. (For instance 1 hour, 3600 seconds)
1. Use ctrl+arrowkeys to move to the end of the clip, and set the "time" property to the number copied in step 3.
1. Right click on the "time" and make sure the curve is linear if you don't want the speed to change.

**For manipulating time:**
If you want to manipulate the speed, the `time` property means the frame of your video that will show at that point on the timeline. Once you've found the number of frames in your video, you can set that time with a keyframe wherever you want your video to end.

If you have any trouble, let me know! We're planning out a more graphical method for manipulating the time of videos.
