### ISSUE TITLE
Can’t add keyframes

### ISSUE THREAD

**Issue by thewulfe8** [OpenShot/openshot-qt#4823]
Instead of adding keyframes when I adjust values the program is just changing the value for the entire clip. This is happening on some clips but not others in the same project.

**Comment by JacksonRG** [comment]
@thewulfe8 could you attach an example project where this is happening, and maybe a short video showing how this is happening? Log files can also help us see what Openshot is doing. [This page](https://github.com/OpenShot/openshot-qt/wiki/Issue-Logging) has instructions for finding your log files.

Also, are there any other patterns you notice? Like are certain properties affecting the whole clip, or is a certain file type affected?
