### ISSUE TITLE
Keyframes for properties attach to the wrong time

### ISSUE THREAD

**Issue by ShoofLLC** [OpenShot/openshot-qt#4826]
**Describe the bug:**
When the time is sped up (time is keyframed); Adding a property keyframe, attaches the property keyframe to an unexpected timestamp.
 
**Steps to reproduce the behavior:**
1. Speed up a clip by 8x (a large number shows the effect better) -- Assume clip time after speeding up is 10s
2. Go to the start of the clip and add Alpha Keyframe -> Set Alpha to 0 -- Project time: 0.0s, Clip Time: 0.0s
3. Go the middle of the clip and add Alpha Keyframe -> Set Alpha to 1 -- Project time: 5.0s, Clip Time: 40.0s
4. Go to the end of the clip and add Alpha Keyframe -> Set Alpha to 0 -- Project time: 10.0s, Clip Time: 80.0s

Playing the clip now will fade-in the clip for about 0.2 seconds and fade out for another 0.2 seconds, rest of the clip remains dark -- about 9 seconds dark.

Note: The GUI display value for alpha doesn't match the actual alpha value anymore, the GUI displays the expected behavior only but not the actual behavior.

**Expected behavior:**
The clip is faded-in till half of the clip and faded out till the end.

**System Details:**
- OpenShot Version : 2.6.1
- Operating System / Distro: Ubuntu 20.04

**Comment by JacksonRG** [comment]
Hi, by "actual behavior" do you mean the result when you render the video?

**Comment by ShoofLLC** [comment]
> Hi, by "actual behavior" do you mean the result when you render the video?

yes, and the result in the preview window.

**Comment by Colorjet3** [comment]
Download the latest DEV Daily Build of v3.0.0 and see if that resolved your issue.
