### ISSUE TITLE
Windows build 9523: icon asset name issue

### ISSUE THREAD

**Issue by mportuesisf** [OpenShot/openshot-qt#4828]
**Describe the bug:**
I get the following error popup on startup:  `C:\Program Files\OpenShot Video Editor\effects\icons\objectdetection.png is not a valid image file.`

I went to that folder and I can find two files `objectdetector.png` and `objectdetector@2x.png`, but not the file named in the error popup.

**Steps to reproduce the behavior:**
1. Launch OpenShot.  Error appears before main application window appears.

**Expected behavior:**
I renamed the two files `objectdetector.png` and `objectdetector@2x.png` to `objectdetection.png` and `objectdetection@2x.png` and that appears to resolve the issue; the error popup no longer appears.

**System Details:**

With Windows 64-bit build 9523 running on Windows 11:
[OpenShot-v2.6.1-dev-daily-9523-7c6fcb0c-46255e46-x86_64.exe (64-bit)](https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.6.1-dev-daily-9523-7c6fcb0c-46255e46-x86_64.exe)

**Screenshots:** (Optional)
![Screenshot 2022-06-20 180909](https://user-images.githubusercontent.com/306358/174695675-f4d3b43e-6c35-4be0-a8c6-b293ed889c2e.jpg)
![Screenshot 2022-06-20 181259](https://user-images.githubusercontent.com/306358/174695972-fabfca98-d554-4be2-b9f3-db7a4930e117.jpg)

**Comment by JacksonRG** [comment]
Hi, thanks for pointing this out! We've got a fix in review currently to address this.
