### ISSUE TITLE
2.5.0 old version .dmg file broken

### ISSUE THREAD

**Issue by FluffyCrimsonBirkenstocks** [OpenShot/openshot-qt#4829]
The old version of openshot 2.5.0 isnt working
This is happening in mac os 10.10.5 but might happen for all older versions of macOS

![Screen Shot 2022-06-21 at 5 09 56 pm](https://user-images.githubusercontent.com/107928309/174792080-d4a8bded-705e-49b2-8477-315d29583903.png)

**Comment by JacksonRG** [comment]
Is this only happening with 2.5.0? Or are the 2.6.1 and daily build versions also not working?
