### ISSUE TITLE
Resizing video is too slow

### ISSUE THREAD

**Issue by Evil-Spirit** [OpenShot/openshot-qt#4832]
When I start to drag video to resize, it moves very slow and laggy

**Expected behavior:**
Should be fast since I have very performant hardware (Aero 15 notebook with good CPU and GPU)

**System Details:**
- OpenShot Version 2.6.1
- Operating System: Windows 10

![_ Безымянный проект  HD Vertical 720p 30 fps  - OpenShot Video Editor 2022-06-22 17 00 56](https://user-images.githubusercontent.com/1980537/175002223-9c1c0ecc-749d-47ee-b557-4973c96eda42.png)

**Comment by Colorjet3** [comment]
Please try the latest DEV Daily Build as this was reported previously and it should be fixed now.  Go to https://www.openshot.org/download/ and download build #9537.  Let us know if this takes care of the issue for you.
