### ISSUE TITLE
Openshot doesn't start

### ISSUE THREAD

**Issue by montfalcon** [OpenShot/openshot-qt#4837]
**Descrivi il bug**
I  run it and nothing happen, if i run trough the terminal it stuck for several minutes at:

INFO version: Found current version: {'error_rate_stable': 0.16, 'error_rate_unstable': 0.05, 'openshot_version': '2.6.1', 'trans_rate_unstable': 0.001, 'trans_rate_stable': 0.01}

then continue and stuck for other minutes at:

INFO emoji_model: updating emoji model.

then continue till the Stack Trace error.

**Passi per riprodurre questo comportamento:**
Just run it.

**Comportamento atteso**
open a window

**Dettagli di sistema**
- OpenShot Version: 2.6.1-dev
- libopenshot Version:  0.2.7-dev
- Platform: Linux-5.15.0-40-generic-x86_64-with-Ubuntu-22.04-jammy
- Processor: x86_64
- Machine: x86_64
- Python version: 3.6.9
- Qt5 version: 5.9.5
- PyQt5 version: 5.10.1
- Qt Detected Languages: ['it-IT']
- LANG Environment Variable: it_IT.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-dev-daily-9537-5776efd7-46255e46-x86_64.AppImage

**File di registro**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/t6tt4tlej9atnaud4lar6djnx0wvcgme/openshot-qt.zip) (4 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/t6tt4tlej9atnaud4lar6djnx0wvcgme/libopenshot.zip) (6 KB)

**Errore / Stack trace**
```/lib/x86_64-linux-gnu/libc.so.6 raise                                    0x16  [0x7ff66f21a476]
/lib/x86_64-linux-gnu/libc.so.6 abort                                    0xd3  [0x7ff66f2007f3]
/usr/lib/x86_64-linux-gnu/dri/crocus_dri.so                                          0xa4ced  [0x7ff63670eced]
/usr/lib/x86_64-linux-gnu/dri/crocus_dri.so                                          0x101e6b4  [0x7ff6376886b4]
/usr/lib/x86_64-linux-gnu/dri/crocus_dri.so                                          0x1a2a6d  [0x7ff63680ca6d]
/usr/lib/x86_64-linux-gnu/dri/crocus_dri.so                                          0xb6405  [0x7ff636720405]
/lib/x86_64-linux-gnu/libGLX_mesa.so.0                                          0x51611  [0x7ff667860611]
/lib/x86_64-linux-gnu/libGLX_mesa.so.0                                          0x44695  [0x7ff667853695]
/tmp/.mount_bsFkVH/usr/bin/plugins/xcbglintegrations/libqxcb-glx-integration.so                                          0x8902  [0x7ff63c808902]
/tmp/.mount_bsFkVH/usr/bin/libQt5Gui.so.5 QOpenGLContext::swapBuffers(QSurface*)   0xaa  [0x7ff668b3b10a]
/tmp/.mount_bsFkVH/usr/bin/libQt5Gui.so.5 QPlatformBackingStore::composeAndFlush(QWindow*, QRegion const&, QPoint const&, QPlatformTextureList*, QOpenGLContext*, bool) 0xa2f  [0x7ff668defd4f]
/tmp/.mount_bsFkVH/usr/bin/libQt5XcbQpa.so.5                                          0x5be97  [0x7ff640c5be97]
/tmp/.mount_bsFkVH/usr/bin/libQt5Widgets.so.5                                          0x161077  [0x7ff669361077]
/tmp/.mount_bsFkVH/usr/bin/libQt5Widgets.so.5                                          0x16277e  [0x7ff669...

**Comment by JacksonRG** [comment]
@montfalcon Does this still happen if you delete or rename your settings file? `/home/<user_name>/.openshot_qt`

**Comment by montfalcon** [comment]
Yes @JacksonRG

**Comment by Colorjet3** [comment]
Please go to openshot.org/download.  Click on Daily Builds and download the latest available build.  It will be an AppImage.  This should work for you.

**Comment by montfalcon** [comment]
Thanks, but still doesn't work

Il giorno gio 3 nov 2022 alle ore 03:41 Colorjet3 ***@***.***>
ha scritto:

**Comment by Colorjet3** [comment]
Please try install it using the PPA Daily and see if that works for you:  https://www.openshot.org/ppa/.  Ensure you are executing the Daily PPA and not the Stable PPA commands.   After you run this look for the OpenShot icon to start it that way.

**Comment by montfalcon** [comment]
Great! It works! Thanks

Il giorno sab 19 nov 2022 alle ore 20:13 Colorjet3 ***@***.***>
ha scritto:

**Comment by Colorjet3** [comment]
That is awesome and thank you for the update.  I will ping one of the technical staff to see why the AppImage is not working but at least you are on your way.
