### ISSUE TITLE
Crashes after importing MOV file (not drag and drop) after importing multiple files including other ...

### ISSUE THREAD

**Issue by MikeD579** [OpenShot/openshot-qt#4839]
**Describe the bug**
I have already imported many other videos. I did this by selecting all of them at once. then when selecting only one mov file it crashes.

**Steps to reproduce the behavior:**
1. Go to file > import
2. Choose MOV file and Click on import
3. Wait for it to import.
4. Then crashes

**Expected behavior**
Should import video properly and show up in the workspace.

**System Details**
- OpenShot Version: 2.6.1-dev
- libopenshot Version:  0.2.7-dev
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 158 Stepping 13, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-dev-daily-9566-5776efd7-46255e46-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/2rj0wervcg2e3u2vgxoyts7hn4dhq0wm/openshot-qt.zip) (11 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/2rj0wervcg2e3u2vgxoyts7hn4dhq0wm/libopenshot.zip) (157 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by MikeD579** [comment]
init

**Comment by Colorjet3** [comment]
Please download the latest DEV Daily Build of v3.0.0 and give it a try.
