### ISSUE TITLE
missing effects under windows10 and fedora 25

### ISSUE THREAD

**Issue by juckendesAuge** [OpenShot/openshot-qt#484]
Hello,
some effects are missing under windows10 and linux fedora 25.
I have test it with the last version OpenShot-v2.2.0-2-g5a2acb8-49-603-x86_64.AppImage.
Audio effects are all gone. Video effects only 7. This problem is at least since Sep. 10 2016. All newer Versions have the Problem too.

![bildschirmfoto_2017-01-21_01-04-42](https://cloud.githubusercontent.com/assets/24550429/22169658/25eb29e6-df76-11e6-9460-de3d7057380b.png)
![bildschirmfoto_2017-01-21_01-05-01](https://cloud.githubusercontent.com/assets/24550429/22169660/25ef1858-df76-11e6-92e7-45fcfd827d88.png)
![bildschirmfoto_2017-01-21_01-05-12](https://cloud.githubusercontent.com/assets/24550429/22169661/25f09fe8-df76-11e6-9637-16215690c399.png)
![bildschirmfoto_2017-01-21_01-06-04](https://cloud.githubusercontent.com/assets/24550429/22169659/25eda2b6-df76-11e6-86fe-d7c4e9faafe4.png)

**Comment by mixedbredie** [comment]
See this [thread](https://github.com/OpenShot/openshot-qt/issues/498#issuecomment-281090097) for the same issue.

**Comment by jonoomph** [comment]
Closing issue. More effects are on the way, but they aren't missing, they just don't exist yet. =)
