### ISSUE TITLE
Frame number does not show if video is clipped

### ISSUE THREAD

**Issue by dogmatic69** [OpenShot/openshot-qt#4840]
**Describe the bug:**
Selecting to show frame numbers for a clip does not show when a video has been clipped.

**Steps to reproduce the behavior:**
1. Adjust scale and location to "clip" the section (indicated by *A*)
2. The section where frame is show is off the screen (indicated by *B*)

![image](https://user-images.githubusercontent.com/94674/176672700-8c015320-f0e1-4429-8542-6aa2b2b286d9.png)

3. If I move the clip so that the top left corner is visible, the frame number is shown. 

![image](https://user-images.githubusercontent.com/94674/176672970-58a5d599-1a86-4f36-a2e5-ea89133f5a58.png)

**Expected behavior:**

If selecting to show frame number, it should be visible regardless of what other settings are in play.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 2.6.1-dev, latest as of today
- Operating System / Distro: ubuntu

**Comment by dogmatic69** [comment]
I'm guessing this would show on the actual video when exporting? If so is there a way to just show it somewhere in the UI so that I can easily identify the frame for exporting small sections.

I've got an all day meeting recording that I want to split into sections and export each section as individual clips.

[This post](https://www.reddit.com/r/OpenShot/comments/g32m05/exporting_sections_and_frame_numbers/) seems to confirm it's a bit of a pain. Would be nice to just show the frame numbers in the UI by default, either with the time in the timeline, or option to switch between time and frame number. Another option would be like the debug fps display, that would be a good location for permanent display of frame numbers

**Comment by JacksonRG** [comment]
@dogmatic69 I'd suggest applying a `crop` effect to the clip. You can chop off the top of your video, but the frame number will still be pasted on top of that.

But this is definitely an interesting issue. I'll bring up the idea of turning this into an effect, so the frame number could have it's own position. But that will take time. I hope cropping the video helps in the short term.

More cumbersome workaround:

If you have to resize your video, and want the frame numbers in the final export,
you can overlay a copy of the clip on top (on a track above), enable frame numbers, and disable audio and video. Then you would have the freedom to Position it as you like. But as I said, we could do this more gracefully.

**Comment by JacksonRG** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Frame number as an effect](https://trello.com/c/9aIbjZw6/152-frame-number-as-an-effect)

**Comment by Colorjet3** [comment]
This is fixed in v3.0.0.
