### ISSUE TITLE
unable to drag image duration past 3600 seconds

### ISSUE THREAD

**Issue by dogmatic69** [OpenShot/openshot-qt#4841]
**Describe the bug:**
Unable to drag the duration of a png image more than 3600 seconds. It is however possible to make it longer in the properties. If making it for example 20,000 seconds and then dragging, it will spring back to 3600.

**Steps to reproduce the behavior:**
1. add image to the timeline
2. drag it past 3600 seconds, not possible
3. adjust properties to manually make it any value higher than 3600
4. dragging once again results in springing back to 3600

**Expected behavior:**
ability to drag any distance

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 2.6.1-dev latest as of today
- Operating System / Distro: ubuntu

**Comment by Colorjet3** [comment]
This now works in v3.0.0.
