### ISSUE TITLE
Timeline frame number does not correlate

### ISSUE THREAD

**Issue by dogmatic69** [OpenShot/openshot-qt#4842]
**Describe the bug:**
Using the property to view the frame number I export a clip using that frame number. The resulting clip is much longer than expected.

**Steps to reproduce the behavior:**
1. select clip and edit preference to show timeline frame number
2. export video, in advanced settings enter frame number from step 1
3. exported video does not end at specified frame.

In my case the frame I want according to the timeline frame number is 11214, in the timeline view that is 06:13.24 seconds. 

The exported video is 7:28 long.

Recorded as H.264 1920x1080 @ 25 fps 
Source is H.264 1920x1080 @ 15 fps

**Expected behavior:**
When using a frame number from the UI for an end, it should end at that frame.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 2.6.1-dev latest as of today
- Operating System / Distro: ubuntu

**Comment by dogmatic69** [comment]
Playing around with this more, as soon as I click export the end frame changes in the UI.
[Screencast from 30-06-22 15:11:55.webm](https://user-images.githubusercontent.com/94674/176686261-82f75709-44d6-4c55-91ed-02c551d06b3a.webm)

**Comment by dogmatic69** [comment]
I can't to make this work. Seems that exporting a specific length of the video is completely unusable.

**Comment by dogmatic69** [comment]
I've opened up the project in the 2.6.1 official release with the `--no-sandbox` flag to make the timeline work. When using this version the end frame number remains as entered after clicking `export video`. The exported video contains what was expected.

Seems like something has broken in the latest daily.

**Comment by JacksonRG** [comment]
@dogmatic69 Just to narrow down the problem, If you change your project format to 15 fps, and export your choice of frames does this work properly?

**Comment by dogmatic69** [comment]
nope, should have been more specific in the second comment. That was one of the things I tried. Regardless of settings the end frame value changes when you click "export video"

**Comment by JacksonRG** [comment]
To be clear I don't mean to sound patronizing, but I'm gonna ask the questions I'd ask myself if I had this issue.

1) Are you choosing the frame numbers at the same frame rate you're exporting at? frame 1 through frame 30 is 2 seconds at 15 FPS, but 0.5 seconds at 60 fps
2) Are the frame numbers set to `Timeline`? The frame numbers may be affected by trimming the beginning off, or by moving somewhere along the timeline.

Otherwise, I'm looking into any code that affects `end frame` for a math error when the FPS changes.

**Comment by dogmatic69** [comment]
As mentioned [here](https://github.com/OpenShot/openshot-qt/issues/4842#issuecomment-1172097745), it works perfectly fine in the current official release with exactly the same project and exactly the same export options. 

There is also a video attached showing how the end frame number jumps as soon as the export button is clicked. The exact moment is seconds 38-39 where it changes.
