### ISSUE TITLE
Openshot crashing on specific video file

### ISSUE THREAD

**Issue by ericgottmann** [OpenShot/openshot-qt#4844]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**
1. Go to 'File'
2. Click on 'Import Files'
3. Scroll down to 'File to add and hit the open button'
4. See error. (No error, just crashes)

**Expected behavior**
File to be imported successfully. I've imported other files that are longer/shorter. I've recreated the video and it still crashes.  set the max ram to 2048. Imported other files first and it still crashes on this one.

**System Details**
- OpenShot Version: 2.6.1-dev
- libopenshot Version:  0.2.7-dev
- Platform: Windows-10-10.0.19041
- Processor: AMD64 Family 23 Model 8 Stepping 2, AuthenticAMD
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-dev-daily-9570-5776efd7-46255e46-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/u7cqh27t6lrpzlqrlhq2m7871l2qbcb8/openshot-qt.zip) (5 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/u7cqh27t6lrpzlqrlhq2m7871l2qbcb8/libopenshot.zip) (8 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
Download the latest DEV Daily Build v3.0.0.  If the video is still failing then run your video through a converter such as Handbrake or VLC and convert it to .mp4.  If it is a .mp4 already, just convert it to .mp4 again.
