### ISSUE TITLE
Failure to start (Python exception/stack trace)

### ISSUE THREAD

**Issue by davison** [OpenShot/openshot-qt#4846]
**Describe the bug**
Application will not start (hangs) need to kill process or start from CLI and use Ctrl-C to kill. No window is ever created for it by the WM. Was unable to d/l daily snapshot to test (HTTP 404).

**Steps to reproduce the behavior:**
1. Run the application from CLI by invoking `openshot-qt`

**Expected behavior**
The application starts.

**System Details**
- OpenShot Version: 2.5.1
- libopenshot Version:  0.2.5
- Platform: Linux-5.15.0-40-generic-x86_64-with-glibc2.35
- Processor: x86_64
- Machine: x86_64
- Python version: 3.10.4
- Qt5 version: 5.15.3
- PyQt5 version: 5.15.6
- Qt Detected Languages: ['en-GB', 'en']
- LANG Environment Variable: en_GB.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-dev-daily-9576-5776efd7-46255e46-x86_64.AppImage

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/nnkt1stp744wd075uademp2os1kacaa0/openshot-qt.zip) (2 KB)
- libopenshot.log: File too small or empty (was uploaded)

**Exception / Stacktrace**
```  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "/usr/bin/openshot-qt", line 33, in <module>
    sys.exit(load_entry_point('openshot-qt==2.5.1', 'gui_scripts', 'openshot-qt')())
  File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 97, in main
    app = OpenShotApp(argv)
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 219, in __init__
    self.window = MainWindow(mode)
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/main_window.py", line 2521, in __init__
    self.timeline = TimelineWebView(self)
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/views/timeline_webview.py", line 3000, in __init__
    self.cache_renderer.setInterval(0.5 * 1000)
TypeError: setInterval(self, int): argument 1 has unexpected type 'float'
     version:INFO Found current version: {"trans_rate_stable": 0.01, "error_rate_stable": 0.16, "error_rate_unstable": 0.05, "openshot_version": "2.6.1", "trans_rate_unstable": 0.001}
```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by JacksonRG** [comment]
Looks like you're using `2.5.1`, and the current release that we're supporting is `2.6.1`.

You mentioned you weren't able to download the appimage version? It can be found [here](https://www.openshot.org/download/) let me know if there's any other ways I can help.

**Comment by davison** [comment]
yep, 2.6.1 starts up without error, thanks. The bug creation wizard obviously tries to link to a nightly build that doesn't appear to exist. 

Unfortunately the latest version of Ubuntu (22.04) is shipping 2.5.1 - guessing it's probably incompatible with the Python 3.10.4 they also ship. I'd raise the bug with Ubuntu but my experience of this in the past has been entirely negative :( 

I'll close this one.. thanks for the response.

**Comment by JacksonRG** [comment]
Odd about the bug creation wizard. I can look into that.
