### ISSUE TITLE
OpenShot and UbuntuStudio 22

### ISSUE THREAD

**Issue by madpaul** [OpenShot/openshot-qt#4847]
Use this and enjoy it.

sudo add-apt-repository ppa:openshot.developers/libopenshot-daily
sudo apt update
sudo apt install openshot-qt python3-openshot 

Nothing else works for me.

**Comment by JacksonRG** [comment]
@madpaul Do you mean that this is the only way you managed to install OpenShot, or that you tried installing openshot that way and it didn't work?

**Comment by rl-musik** [comment]
@madpaul  
 
- Before starting to add the repository, i found out via Synaptic that openshot was called "transitional package" (openshot-qt (2.4.3+dfsg1-1) unstable; urgency=medium). Then by using the Software Manager Mintinstall (`mintinstall`) i found out that Mintinstall said that the OpenShot Video Editor was "not installed". Installing the Editor again via `mintinstall` for me solved the problem. 

 System: Kernel: 5.4.0-91-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: MATE 1.26.0 
            wm: marco dm: LightDM Distro: Linux Mint 20.3 Una base: Ubuntu 20.04 focal 

----------------------------------------------------------------------------------------

Changes: 

System: Kernel: 5.15.0-47-generic x86_64 bits: 64 compiler: gcc v: 11.2.0 Desktop: MATE 1.26.0 
wm: marco dm: LightDM Distro: Linux Mint 21 Vanessa base: Ubuntu 22.04 jammy

 ​ ​ ​ ​    ▶      ​ ​ ​ ​ Ubuntu 22.04 "ppa does not have release file" 
 ​ ​ ​  ​ ​ ​     ​ ​ ​     ​ ​ ​   [https://github.com/OpenShot/openshot-qt/issues/4894#issuecomment-1236293467]

 ​ ​ ​ ​    ▶      ​ ​ ​ ​ Note: meanwhile some updates appeared 
 ​ ​ ​  ​ ​ ​     ​ ​ ​     ​ ​ ​   (automatically installed by the Update Manager / Software Updater 
  ​ ​ ​ ​ ​ ​     ​ ​ ​     ​ ​ ​   (resp. `mintupdate `(Aktualisierungsverwaltung)), 
 ​ ​ ​  ​ ​ ​     ​ ​ ​     ​ ​ ​   or with `sudo apt update` and `sudo apt upgrade`)
   ​ ​ ​     ​ ​ ​     ​ ​ ​              ​ ​ ​ ​

**Comment by Colorjet3** [comment]
Please get the latest DEV Daily Build of v3.0.0 and see if that works for you.
