### ISSUE TITLE
Program crashes

### ISSUE THREAD

**Issue by Mrabiff** [OpenShot/openshot-qt#4849]
**Describe the bug**
OpenShot crashes when importing or copying mp3 to timeline

**Steps to reproduce the behavior:**
1. Go to 'OpenShot'
2. Click on 'plus sign'
3. Scroll down to 'go to file to import and click open'
4. OpenShot crashes

**Expected behavior**
I expected the mp3 to be added to the timeline.

**System Details**
- OpenShot Version: 2.6.1-dev
- libopenshot Version:  0.2.7-dev
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 69 Stepping 1, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-dev-daily-9576-5776efd7-46255e46-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/0sxdzldwqwqjqj1tunwmutj20969mp5m/openshot-qt.zip) (9 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/0sxdzldwqwqjqj1tunwmutj20969mp5m/libopenshot.zip) (2 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by ManuelGraf** [comment]
same ever since the 2.6 update I get silent crashes ALL THE TIME after editing a fewthings... not usable atm and destroys progress.

I only changed use disk for preview storage with 8 gig and updated to 2.6.1 from ^2.5.0

**Comment by Mrabiff** [comment]
I went back to an older version of the software and fix my problem.

**Comment by Colorjet3** [comment]
The latest DEV Daily Build fixes many of the issues that v2.6.1-Release-Candidate (Help | About Openshot) had.  Please go to openshot.org/download, click on Daily Builds, download the latest DEV daily build available.  Many fixes, and features in this version.  Revisit often to get the latest as this is DEV and other issues exist and actively being worked on.

**Comment by Colorjet3** [comment]
No Response.

**Comment by Colorjet3** [comment]
Version 3.0.0 is out now.  If you are interested you should go to openshot.org/download/#daily and get the latest DEV Daily Build.
