### ISSUE TITLE
openshot 2.2 memory leak on startup

### ISSUE THREAD

**Issue by TombyT** [OpenShot/openshot-qt#485]
have been trouble getting openshot to do anything correctly recently. Before had issues with playback, then issues exporting an entire sequence.

Most recently openshot crashed immediately after clicking the red export button. After which trying to re-open the program does nothing but consume ram until all 24 Gb are used. The gui doesn't even pop up.

If someone could point me in the right way to debug this / check a log file that'd be great.

Ubuntu 16.10, gtx 460m, i72630QM, 24GB ram, 256 SSD, 1080 60fps mp4(h.264) goprofootage.

I'm not expecting much, but is there anyways to convert openshot-qt(2.2) project files down to openshot (1.4). That version for the most part is at least stable and preview isn't laggy/jerky.

**Comment by TombyT** [comment]
in an attempt to see if I can figure out a solution or cause, here is what the logger shows right before the system spikes from 0% to 100% memory (24GB):

preview_thread:INFO initPlayer
logger_libopenshot:INFO Timeline::SortClips (clips.size()=0.0000)
logger_libopenshot:INFO Timeline::GetFrame (requested_frame=1.0000, minimum_frames=8.0000, OPEN_MP_NUM_PROCESSORS=8.0000)
logger_libopenshot:INFO Timeline::GetFrame (processing frame) (frame_number=1.0000, omp_get_thread_num()=0.0000)
logger_libopenshot:INFO Timeline::GetFrame (processing frame) (frame_number=6.0000, omp_get_thread_num()=5.0000)
logger_libopenshot:INFO Timeline::GetFrame (processing frame) (frame_number=3.0000, omp_get_thread_num()=2.0000)
logger_libopenshot:INFO Timeline::GetFrame (processing frame) (frame_number=4.0000, omp_get_thread_num()=3.0000)
logger_libopenshot:INFO Timeline::GetFrame (processing frame) (frame_number=8.0000, omp_get_thread_num()=7.0000)
logger_libopenshot:INFO Timeline::GetFrame (processing frame) (frame_number=7.0000, omp_get_thread_num()=6.0000)
logger_libopenshot:INFO Timeline::GetFrame (processing frame) (frame_number=5.0000, omp_get_thread_num()=4.0000)
logger_libopenshot:INFO Timeline::GetFrame (Adding solid color) (frame_number=1.0000, info.width=1920.0000, info.height=1080.0000)
logger_libopenshot:INFO Timeline::GetFrame (processing frame) (frame_number=2.0000, omp_get_thread_num()=1.0000)
logger_libopenshot:INFO Timeline::GetFrame (Adding solid color) (frame_number=6.0000, info.width=1920.0000, info.height=1080.0000)
logger_libopenshot:INFO Timeline::GetFrame (Adding solid color) (frame_number=3.0000, info.width=1920.0000, info.height=1080.0000)
logger_libopenshot:INFO Timeline::GetFrame (Adding solid color) (frame_number=4.0000, info.width=1920.0000, info.height=1080.0000)
logger_libopenshot:INFO Timeline::GetFrame (Adding solid color) (frame_number=8.0000, info.width=1920.0000, info.height=1080.0000)
logger_libopenshot:INFO Timeline::GetFrame (Adding solid color) (frame_number=7.0000, info.width=1920.0000, info.height=1080.0000)
logger_libopenshot:INFO Timeline::GetFrame (Adding solid color) (frame_number=5.0000, info.width=1920.0000, info.height=1080.0000)
logger_libopenshot:INFO Timeline::GetFrame (Adding solid color) (frame_number=2.0000, info.width=1920.0000, info.height=1080.0000)
logger_libopenshot:INFO Timeline::GetFrame (Loop through clips) (frame_number=1.0000, requested_time=0.0000, clips.size()=0.0000, nearby_clips.size()=0.0000)
logger_libopenshot:INFO Timeline::GetFrame (Loop through clips) (frame_number=3.0000, requested_time=0.0333, clips.size()=0.0000, nearby_clips.size()=0.0000)
logger_libopenshot:INFO Timeline::GetFrame (Loop through clips) (frame_number=6.0000, requested_time=0.0833, clips.size()=0.0000, nearby_clips.size()=0.0000)
logger_libopenshot:INFO Timeline::GetFrame (Loop through clips) (frame_number=4.0000, requested_time=0.0500, clips.size()=0.0000, nearby_clips.size()=0.0000)
logger_libopenshot:INFO Timeline::GetFrame (Loop through clips) (frame_number=8.0000, requested_time=0.1167, clips.size()=0.0000, nearby_clips.size()=0.0000)
logger_libopenshot:INFO Timeline::GetFrame (Loop through clips) (frame_number=7.0000, requested_time=0.1000, clips.size()=0.0000, nearby_clips.size()=0.0000)
logger_libopenshot:INFO Timeline::GetFrame (Loop through clips) (frame_number=5.0000, requested_time=0.0667, clips.size()=0.0000, nearby_clips.size()=0.0000)
logger_libopenshot:INFO Timeline::GetFrame (Loop through clips) (frame_number=2.0000, requested_time=0.0167, clips.size()=0.0000, nearby_clips.size()=0.0000)
logger_libopenshot:INFO Timeline::GetFrame (Add frame to cache) (frame_number=1.0000, info.width=1920.0000, info.height=1080.0000)
logger_libopenshot:INFO Timeline::GetFrame (Add frame to cache) (frame_number=3.0000, info.width=1920.0000, info.height=1080.0000)
logger_libopenshot:INFO Timeline::GetFrame (Add frame to cache) (frame_number=6.0000, info.width=1920.0000, info.height=1080.0000)
logger_libopenshot:INFO Timeline::GetFrame (Add frame to cache) (frame_number=4.0000, info.width=1920.0000, info.height=1080.0000)
logger_libopenshot:INFO Timeline::GetFrame (Add frame to cache) (frame_number=8.0000, info.width=1920.0000, info.height=1080.0000)
logger_libopenshot:INFO Timeline::GetFrame (Add frame to cache) (frame_number=7.0000, info.width=1920.0000, info.height=1080.0000)
logger_libopenshot:INFO Timeline::GetFrame (Add frame to cache) (frame_number=5.0000, info.width=1920.0000, info.height=1080.0000)
logger_libopenshot:INFO Timeline::GetFrame (Add frame to cache) (frame_number=2.0000, info.width=1920.0000, info.height=1080.0000)
logger_libopenshot:INFO Timeline::GetFrame (end parallel region) (requested_frame=1.0000, omp_get_thread_num()=0.0000)

it hangs on the last line and then the memory spikes to 100% in 4-5 seconds. No GUI is ever displayed.

**Comment by TombyT** [comment]
I have been succesfull running openshot-qt 2.06 and 2.07 but 2.1 and 2.2 both results in the same issue where upon starting the application, the memory usage will climb to 100% within a few seconds while the GUI willl not display.

No major issues running the application. Playback is still pretty laggy and i'm going to see if I can properly run a 15 minute HD export operation.

**Comment by TombyT** [comment]
same issue with exporting video. I got to 49% and the program now freezs indefinitley. From the terminal it seems the error occured when dealing with an .mp3 resulting in 

"mp3_path : error while seeking video stream"

**Comment by jonoomph** [comment]
Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily AppImage build of OpenShot. We've recently fixed some issues that I think might solve this. I'm going to close this ticket, but please reopen the issue if you still experience the problem. Thanks.
