### ISSUE TITLE
Openshot UI isn't rendered/transparent Linux

### ISSUE THREAD

**Issue by afro-coder** [OpenShot/openshot-qt#4850]
**Describe the bug:**
I have archlinux with i3wm+picom and the openshot GUI doesn't load, I can see the menus if I do a right-click but other than that everything is transparent. I've tried disabling all compositing by killing picom, and even added this to the exclude option in QT5/6 Settings.

**Steps to reproduce the behavior:**
1. Open openshot
2. Right click to see the options

This works if I switch the backend to webkit. 
`openshot-qt -d -b webkit`

**Expected behavior:**
I expected the windows to render and the UI to load up with all the components.

**System Details:**
- OpenShot Version 2.6.1-dev
- Operating System / Distro: Archlinux 
Linux afro-pc 5.18.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 02 Jul 2022 21:03:06 +0000 x86_64 GNU/Linux

I have python 3.10, qt5 and qt6 and gtk packages installed.

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.
[openshot.log](https://github.com/OpenShot/openshot-qt/files/9078715/openshot.log)

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

![image](https://user-images.githubusercontent.com/8469842/178137081-3e167202-8f8e-4257-a88e-7e9199c9335d.png)

**Comment by JacksonRG** [comment]
If `-b webkit` fixes this issue, you can add that to the launch command for openshot.

If you're using the appimage, there should be a file called `appimagekit-openshot-qt.desktop` in `~/.local/share/applications/`. You can add `-b webkit` to the end of the launch command (Inside the quotes on the line starting with `Exec=`

**Comment by afro-coder** [comment]
Ah alright thanks, is there any significant difference between webengine and webkit?

**Comment by JacksonRG** [comment]
Not that I know of. They're just two different web renderers, and our timeline uses web techniques to render. Different OSes may only support one, so we offer both.

**Comment by afro-coder** [comment]
Ah cool thanks!
