### ISSUE TITLE
split video and export 

### ISSUE THREAD

**Issue by hitbuyi** [OpenShot/openshot-qt#4851]
**Question:**
split video on track 1, select one of the clips to export, it failed, it exports the whole video all the time  .

**System Details:**
- OpenShot Version: 2.6.1,libopenshot 0.2.7
- Operating System: ubuntu20.04

**Screenshots:** (Optional)
![openshot_bug](https://user-images.githubusercontent.com/10301777/178196941-b500a906-79d0-4778-aab1-bacb2a716781.png)

**Comment by JacksonRG** [comment]
@hitbuyi After you split the clip, did you remove the parts of the video that you don't want? Everything on the timeline will export by default.

**Comment by dogmatic69** [comment]
you need to look at the frame number at the start and end, then in export on the advanced tab enter those values. 

https://www.reddit.com/r/OpenShot/comments/g32m05/exporting_sections_and_frame_numbers/

**Comment by hitbuyi** [comment]
> you need to look at the frame number at the start and end, then in export on the advanced tab enter those values.
> 
> https://www.reddit.com/r/OpenShot/comments/g32m05/exporting_sections_and_frame_numbers/

I'll try again, thanks

**Comment by hitbuyi** [comment]
> @hitbuyi After you split the clip, did you remove the parts of the video that you don't want? Everything on the timeline will export by default.

That's the point!  if I just want small piece of the whole clip, and then It take lots of time to move the small parts manually.

**Comment by JacksonRG** [comment]
@hitbuyi If you right click on the file, you'll see an option to `Split Clip` That gives you a menu where you can move the slider to the part you want, and choose the Start and End of the clip you're creating.

In this menu, right and left arrow keys move you by 1 second. That way you don't have to put the whole long file on the timeline to cut it.
