### ISSUE TITLE
Which is the hotkey to move a clip to the specified time axis, not using mouse dragging

### ISSUE THREAD

**Issue by hitbuyi** [OpenShot/openshot-qt#4852]
**Question:**
Think about a video is very long(10hour), I want just 10 minutes of it ,which is at the end of the vedio, far away from the vedio's beginning ,  When I get this clip, I wanna put it at the time of beginning,  It is possible to use mouse to drag it to the beginning, is there a hotkey to do the some thing?

**System Details:**
- OpenShot Version: 2.6.1
- Operating System : ubuntu20.04

**Comment by JacksonRG** [comment]
@hitbuyi Ctrl + right or left arrow keys will move you to the beginning or end of whatever clip you have highlighted.

But if you just want the end of a very long clip, I'd suggest right clicking on it in the files view, and clicking on the `Split Clip` option. That will let you choose a small part of the file to put on the timeline.
