### ISSUE TITLE
I was working on my video proyect and my pc crashed, after put it on again my file of openshot cannot be open and tells: invalid load key, '\x00'. 

### ISSUE THREAD

**Issue by Gatopardotis** [OpenShot/openshot-qt#4858]
**Describe the bug:**

**Steps to reproduce the behavior:**

**Expected behavior:**

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by JacksonRG** [comment]
@Gatopardotis It may be trying to reopen the the project, but unable to. You can remove the settings folder `C:\Users\<Your User Name>\.openshot_qt\` or `/home/<user name>/.openshot_qt/`. That way openshot will open without trying to open a project.
