### ISSUE TITLE
[MacBook Air M1] Preview does not show in high quality, despite setting Default Profile as '4K UKD 2160p 60 fps'

### ISSUE THREAD

**Issue by penalvch-zz** [OpenShot/openshot-qt#4860]
**Describe the bug:**
When importing a .mkv file (default file format for https://obsproject.com/) the preview is extremely low quality, to the point of being unusable.

Unfortunately, when attempting to upload this file format, Gibhub notes 'We don't support that file type.' However, this shouldn't be that hard to replicate as it's consistently reproducible, and relies on no proprietary, fee based application to reproduce.

WORKAROUND 1: Open mkv file in VLC to confirm quality.

WORKAROUND 2: Use Shotcut > https://www.shotcut.org/

**System Details:**
- OpenShot Version 
![image](https://user-images.githubusercontent.com/8216601/179424591-f2360b18-7174-491a-ba14-37454548e6f8.png)

- Operating System / Distro:
![image](https://user-images.githubusercontent.com/8216601/179424612-5961fc41-2eb9-4191-a064-6b78fb7b07a0.png)

**Screenshots:**
Openshot:
![image](https://user-images.githubusercontent.com/8216601/179424689-3f0add1b-32fd-4fd1-9491-19bae0cb180a.png)

VLC:
![image](https://user-images.githubusercontent.com/8216601/179424713-6d172449-3fc7-4801-a3fa-c0b78d1c18cc.png)

**Comment by JacksonRG** [comment]
@penalvch Does this quality remain in the exported video?

Other things I'd recommend trying:
1) In preferences, under performance, do you have hardware decoder max width and height set?
2) Does anything change if you turn off hardware decoding?
3) Under Cache in preferences, You can change the cache mode to Disk, and try different image formats, or try increasing the cache limit.

**Comment by penalvch-zz** [comment]
Hi @JacksonRG thanks for the response.

> @penalvch Does this quality remain in the exported video?

No.

>     1. In preferences, under performance, do you have hardware decoder max width and height set?
The defaults found are below without me adjusting anything (despite GUI stating 0 is default):
![image](https://user-images.githubusercontent.com/8216601/180621345-51a58c63-82dd-4f86-b213-098c87552a8f.png)

>     2. Does anything change if you turn off hardware decoding?

It is not adjustable.
 
>     3. Under Cache in preferences, You can change the cache mode to Disk, and try different image formats, or try increasing the cache limit.

No change.

Also, I applied latest update 12.5, no change.

**Comment by JacksonRG** [comment]
Do you only lose quality on 4k? Is 2.5K or HD similarly pixelated? Also are you recording video on a very wide monitor?

I know this is more of  a workaround (if it works) but in OBS, you can click `File` -> `Settings` -> `Output` -> `Recording Format`. Changing to MP4, or playing with the `Encoder` settings may help. (If it does, we may need to update how we're decoding MKV videos)

**Comment by Colorjet3** [comment]
Please verify if this is still an issue in the latest DEV daily build v3.0.0 (openshot.org/download/#daily).
