### ISSUE TITLE
Black, blank, preview window 

### ISSUE THREAD

**Issue by Ensio700** [OpenShot/openshot-qt#4862]
The preview window in Openshot 2.5.1 is black.
I have deleted the log files, but it did not help.

I have tried the latest version of Openshot, and get a message: "float"  object has no attribute "get".
And still no picture in preview window.

Best Regards: Ensio Salmela, Finland

**Comment by JacksonRG** [comment]
Could you attach the log files when you used the latest build? The `"float" object has no attribute "get"` should be relatively quick to fix, as it means some data was stored incorrectly.

[Here](https://github.com/OpenShot/openshot-qt/wiki/Issue-Logging) are instructions on doing that.

**Comment by Ensio700** [comment]
Hello, hi,

Many thanks for your message.

The original log file was big: 1.6 MB.
What I mean with the "preview window", is the main preview window (editing 
window for timeline). 

The Linux Mints Text Editor could not open the log file, because it was too big, but,
the LibreOffice could open it,  and then I saw, 
that one line was very long.  But,  it was impossible to read, because
it was over written with one or two other lines.

Before,  I had on my old Acer computer 8 MB RAM, now I have 16 MB RAM.
I use Linux Mint  20.3 Cinnamon.

My OpenShot folder shows: 1410 items, totalling 581,6 MB

 My OpenShot project  is so far 5 minutes long, and contains only photos).

Okay then, now I will try to send the latest log file to You.


Best Regards: 

Ensio Salmela
Finland

[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/9166184/libopenshot.log)

[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/9166185/openshot-qt.log)

PS. I have the original files in my Trash, if you want to see them,
or a screenshot of the "trouble lines".

**Comment by JacksonRG** [comment]
Second question, did you try our latest version? You mention using 2.5.1, but our current release is 2.6.1 . Also you can try our daily builds for even more recent changes here: https://www.openshot.org/download/

**Comment by Ensio700** [comment]
Hello,

Yes, I did tried the latest OpenShot, I downloaded it as Applimage.
The program gave an error message, when I tried to open the original
project.

I think, one problem is the Linux Mint OS, because it is based on Ubuntu,
but the team behind Linux
Mint has change many things, and the program (Linux Mint) is not stable.
(I don't like Ubuntu, because it has a bad interface.)

I have downloaded the latest version of Openshot (as Applimage), and I have
started
a new project using the same "old" photos.

My question to You is: What OS is most stable to use OpenShot?
(I have only 2 alternatives: Win 10 or some of the Linux OS.)

I started the new project with the old photos, and I used the latest
OpenShot, but it crashed after a while. I started the program again, and
it works now.

 Best Regards: Ensio

**Comment by Ensio700** [comment]
Hello again, hi,

I think, I have found the problem: It was my computer, and it's graphic card. That caused
two problems: it was impossible to edit Titles, and the preview window was black.
(I have ordered a new computer).

So far, I use my very old laptop; HP Elitebook, (year 2011) with 16 MB RAM, and OpenShot works well.
The Elitebook has intel core 5 processor.

So, OpenShot did not have any bugs, it was my computer, which caused the problems.


Best Regards:

Ensio Salmela


PS. 
I have checked other, free editing software, but the OpenShot is the best, 
because it's interface is so easy to understand, it's easy to find what 
you want, and you work very fastly. (Everything is so logically made.)

**Comment by JacksonRG** [comment]
If the issue you were having is the titles editor, openshot should be notifying you that it needs Blender installed. Blender does require a graphics card, so a newer computer may be helpful for that.

Also, as far as operating systems, I can't see why Mint wouldn't work. We develop and test the most on ubuntu, so ubuntu, Xubuntu, or Kubuntu may be the easiest. however, you really shouldn't have to switch distros just for openshot we design it to run on the majority linux distros. Let me know if you run into any other issues.

**Comment by Ensio700** [comment]
Hi,

Many thanks your reply.

I bought a new computer, it has 8 Mb RAM, (DDR4).
I must use a desktop computer, because my laptop has 14' monitor, and it's
too little, small?
(I don't know when to use "little" and "small").

The old laptop works well with Openshot, except editing titles.
I have installed Blender and Inkscape, but editing titles in openshot causes
crash, and the hole program (Openshot) disappears, and I must start the
program
all over again. (I have 1400 photos in my project.)

I have a new computer now with win11, but I think, I must install a Linux
OS also there. But, which one?

You wrote, that ubuntu, kubuntu and xubuntu are ok.
Obviesly Linux Mint has problem.

 I don't know which Linux OS is best to my new desktop computer.
(I have tried before ubuntu, kubuntu and Xubuntu , and maybe
Xubuntu is the correct one).

I  transfered my Openshot project from linux mint to win11, but Openshot
shows
very slowly each frame. One second frame takes 3 seconds to show in the
preview window.

Best Regards: Ensio

**Comment by JacksonRG** [comment]
Ok, so now you're on a different computer and the title editor crashes?

Could you repeat [these](https://github.com/OpenShot/openshot-qt/wiki/Issue-Logging) instructions and attach the new log files, so I can take a look at what's crashing on windows for you?

**Comment by Ensio700** [comment]
Hello again,

I tried OpenShot on win 11, but it took 1 minute to show one second.
(The computer is new. SSD, 8 Gb DDR 4 ram.)

I installed Xubuntu alongside win 11,
Xubuntu did show any tracks. It was impossible to edit the video.

Then I installed Ubuntu, but it did not find Inkscape, even it was
installed on ubuntu.
It was too difficult find the path to Inscape, so I gave up, and...

and now I try to install Kubuntu alongside win 11.


Best Regards:

 Ensio

**Comment by Colorjet3** [comment]
Both Windows 11 and Ubuntu with the latest daily build are now working properly.  There were many issues that are now resolved with the latest DEV Daily Build.

Also, Ubuntu, being Ubuntu, introduces issues with Blender and Inkscape.  Please see https://github.com/OpenShot/openshot-qt/wiki/Blender-and-Inkscape-Guide.

Let us know your experience and what additional support you need to get up and running.

**Comment by Ensio700** [comment]
Thanks for the message. Openshot works very well in my new laptop (Lenovo,
Win 11, and AMD processor).

**Comment by Colorjet3** [comment]
Great.  Please feel free to close this ticket.
