### ISSUE TITLE
What settings were used for the first example in the Jonathan Thomas "3D Animated Titles in OpenShot!" video?

### ISSUE THREAD

**Issue by Klawdek** [OpenShot/openshot-qt#4863]
**Question:**
In the following video https://www.youtube.com/watch?v=nmPTNpjWpzk
Jonathan Thomas demonstrates 3D titles.  The movement is that of the "Fly Towards Camera (two titles)" template.
However the letters do not look anything like the ones in the video.  They look pretty bad compared to the video.
I have enclosed two screenshots of what the Jonathan Thomas video looks like and one of what it really looks like in OpenShot.
I have tried messing with the settings but you have to spend  a really long time after every small change to render it and see what effect it had.  I have tried and tried and I cannot even get anything that looks like those letters in the video. Or anything that looks very good at all. 😞
Can anyone tell what the settings are used to get the letters to look that good?

**System Details:**
- OpenShot Version2.61 dev daily 9604
- Operating System Windows 10
-
**Screenshots:** (Optional)
If applicable, add screenshots to help explain your question. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.
![Screenshot (15778)](https://user-images.githubusercontent.com/45950944/180347962-75776124-d945-4574-b546-6a9c3ab911a1.png)
![Screenshot (15779)](https://user-images.githubusercontent.com/45950944/180347973-5a4081f3-19ce-478e-bf36-67062477f320.png)
![Frame-03547](https://user-images.githubusercontent.com/45950944/180349552-618b9f03-94b8-4bec-ae8c-292c89a11f0f.png)
![Frame-03597](https://user-images.githubusercontent.com/45950944/180349561-c94ebaab-c813-4640-8947-0db3b9fbabe3.png)

**Comment by JacksonRG** [comment]
I'm sorry to hear that renders are taking a long time. I'd recommend moving the slider to later in the animation so the text is clearly visible.

![Screenshot from 2022-07-22 23-03-00](https://user-images.githubusercontent.com/42394129/180589845-72b55832-2b2b-43a2-aeb9-ba34fd617c50.png)

Then you can change your settings and hit the refresh button.

![Screenshot from 2022-07-22 23-03-00_2](https://user-images.githubusercontent.com/42394129/180589912-8877cac3-5706-445d-8611-f953c48be610.png)


In our latest daily build, you should also be able to cancel a partial render, and still view it to see how those settings look. So you can see it in motion as well.

I'll look into this, and see how close I can mimic that video.
