### ISSUE TITLE
Animated Titles do not work.  No frame in output Blender installed correctly

### ISSUE THREAD

**Issue by Klawdek** [OpenShot/openshot-qt#4864]
Some  animated templates do not work.  I get the error "No frame was found in output of Blender"

Then after trying to change between a few different templates OpenShot crashes and the entire system is slow for a while.
Exploding text and magic wand are two of them hat gives the "No frame was found in output of Blender"
I cannot test others  as it is freezing my computer all the time.
**Describe the bug:**

**Steps to reproduce the behavior:**
1. Go to Exploding test animated title
2. Click on Exploding text template
3. See error

**Expected behavior:**

**System Details:**
- OpenShot Version [e.g. 2.6.1 daily dev 9604
- Operating System Windows 10,

**Log Files:**
Here are the logs they are small.
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/9166009/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/9166010/openshot-qt.log)

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

**Screenshots:** (Optional)
Here is screenshot of the error
![Screenshot (15780)](https://user-images.githubusercontent.com/45950944/180395101-8df6adad-b799-431b-b98d-ab64e29a3d7b.png)

**Comment by JacksonRG** [comment]
Hi, sorry, looks like your log files are our git logs. There are instructions on finding your log files [here](https://github.com/OpenShot/openshot-qt/wiki/Issue-Logging)

**Comment by Colorjet3** [comment]
This has been fixed in the latest DEV Daily Build.  Please go to openshot.org/download/#daily and give it a try.

**Comment by ammgws** [comment]
Do you know which commit fixed it? Want to see what I missed when I was trying to debug/fix this issue..

**Comment by Colorjet3** [comment]
I really couldn't tell you.  I am just doing a search in Github and Reddit and responding to users reporting the issue.  If you really need to know you can contact @jonoomph (product owner/developer).

**Comment by ammgws** [comment]
Works for me now using Openshot 3.0 from Arch Linux repos

**Comment by Colorjet3** [comment]
@Klawdek If this is still an issue for you please reopen this ticket.
