### ISSUE TITLE
File can't add to timeline and timeline track missing on Ubuntu 22.04

### ISSUE THREAD

**Issue by lwinmoe51** [OpenShot/openshot-qt#4865]
I installed with AppImage file.
Ubuntu version: 22.04
OpenShot version: 2.6.1
[Screencast from 07-23-2022 07:52:42 AM.webm](https://user-images.githubusercontent.com/47312069/180585054-b673fb95-171a-4370-9737-57a16abbc738.webm)

Please explain me in noob way because I'm not familiar with Ubuntu.

**Comment by JacksonRG** [comment]
This looks like an issue that we've fixed in our daily build. You can find that [here](https://www.openshot.org/download/). Let me know if that helps with this problem.

**Comment by mydeveloperplanet** [comment]
Latest daily build does not have the problem anymore.

**Comment by JacksonRG** [comment]
@lwinmoe51 Let me know if you've tried this in the daily build, and if you noticed any differences.

**Comment by phcavelar** [comment]
Had the same issue, daily build solved it.

**Comment by JacksonRG** [comment]
Glad to hear it's fixed.

**Comment by emc2tln** [comment]
Hello @JacksonRG ,

I have the same problem as @lwinmoe51 since the Ubuntu 22.04.1 LTS update I just did today.
The timeline is not displayed and the software is therefore unusable.

By launching the software by command line, the last message is repeated ad infinitum:
"WARNING webengine: WebEngine backend still not ready after N retries."
See attached file : [WARNING WebEngine backend.txt](https://github.com/OpenShot/openshot-qt/files/9365090/WARNING.WebEngine.backend.txt)
And see : https://user-images.githubusercontent.com/47312069/180585054-b673fb95-171a-4370-9737-57a16abbc738.webm

Do I need to create another ticket or can you re-open this one?
Thanks for your help !

Related to https://github.com/OpenShot/openshot-qt/pull/4787 ???

**Comment by JacksonRG** [comment]
@emc2tln My understanding is that this issue no longer exists in the daily build, so that fix will be in the next release. That build can be found [here](https://www.openshot.org/download/). Please let me know if that version still has this issue.

**Comment by emc2tln** [comment]
Hello @JacksonRG ,

I again uninstalled and reinstalled Openshot Video after downloading the image again.
I copied and pasted the commands I used and the logs.
I still don't have a timeline, in the menu the box is grayed out as well as that of the tutorial.
I'll send you screenshots.

File to see logs : [Re install OpenShot Video Editor.txt](https://github.com/OpenShot/openshot-qt/files/9377045/Re.install.OpenShot.Video.Editor.txt)

Can't add image on no-timeline :
![Cant add image on timeline](https://user-images.githubusercontent.com/111446124/185480469-7ccfa07d-ff4f-429d-ba11-61c18112f0c5.png)

Can't add a new timeline :
![Cant Add Timeline](https://user-images.githubusercontent.com/111446124/185480475-4699756b-2033-439d-a4a7-d182b8323023.png)

Timeline menu disabled :
![Timeline menu disactived](https://user-images.githubusercontent.com/111446124/185481736-6de6ffbb-0329-42a2-b4e9-f276eed3d03e.png)

**Comment by JacksonRG** [comment]
@emc2tln I'm sorry, I should clarify. When I say fixed in the daily build, I mean that the fix hasn't made it to the release that's in the package repositories yet. It's available as an AppImage on our website.

**Comment by emc2tln** [comment]
Hello @JacksonRG,
I think I understood and in any case after downloading the latest daily version I can use the timeline!
Thanks for your help !

log file :
[Install daily image OpenShot Video Editor.txt](https://github.com/OpenShot/openshot-qt/files/9379249/Install.daily.image.OpenShot.Video.Editor.txt)

Link downloaded : 
![Telechargement](https://user-images.githubusercontent.com/111446124/185545911-4cb6725e-05c1-40dd-923c-fa1071f84c74.png)

Software version : 
![Version image](https://user-images.githubusercontent.com/111446124/185545999-af3223e9-6a17-4aa1-af6c-28a91e171d5d.png)

Greyed box of the timeline... but it should be normal ^^ :
![Menu timeline](https://user-images.githubusercontent.com/111446124/185546140-00380bf6-0fb8-45a4-a40f-2da3b0b4b571.png)

**Comment by JacksonRG** [comment]
@emc2tln happy to hear it!
