### ISSUE TITLE
Openshot crashes when I import these certain videos

### ISSUE THREAD

**Issue by Lefty-Child** [OpenShot/openshot-qt#4866]
Hello,
I would like some assistance on how this resolve this problem with Openshot.
There are these videos I have taken on my phone and have emailed to myself so that I could access them on my computer, where I have Openshot installed. However, when I import the videos onto Openshot, it crashes immediately. I was wondering if there is a setting I need to apply or something that I'm not doing right.
Thank you,

**Comment by JacksonRG** [comment]
Could you include log files? (Preferably after turning on debug mode, and repeating the problem)

That may give some clues to where the crash is happening.

Instructions on how to do that are found [here](https://github.com/OpenShot/openshot-qt/wiki/Issue-Logging)

**Comment by Colorjet3** [comment]
Please download the latest dev daily build from openshot.org/download/#daily and give it a try.
