### ISSUE TITLE
Any clip added to the project has the video freeze 1-2 seconds before the end of the clip

### ISSUE THREAD

**Issue by SARITAN** [OpenShot/openshot-qt#4867]
still same issue, Any clip added to the project has the video freeze 1-2 seconds before the end of the clip.
Downloaded openshot from openshot website itself ,the latest available option for download

**Comment by JacksonRG** [comment]
Hi, what os, and computer setup is this happening on? Also, can you attach logs with verbose logging mode turned on? (instructions [here](https://github.com/OpenShot/openshot-qt/wiki/Issue-Logging))

When you say freeze, does the audio continue and the video pauses? Does the video pause and the audio just stop? Any description might help us.

Also are all the clips you're using recorded on the same device? Some recorders will "preroll" audio, and we're currently testing improvements to take care of that.

If you open the video files in another video viewer, and notice anything different, (like audio and no video at the beginning) that might give us a clue.

**Comment by Colorjet3** [comment]
This has been fixed in the latest DEV Daily Build.  Please go to openshot.org/download/#daily.  Download and install the latest DEV daily build and give it a try.
