### ISSUE TITLE
Application Crash

### ISSUE THREAD

**Issue by jonmcarr** [OpenShot/openshot-qt#4868]
**Describe the bug:**
Application crashes while attempting to edit a video. The crash appears to be random and started today There does not appear to be a specific action that causes the crash, it appears to be more of a timing thing.

**Steps to reproduce the behavior:**

**Expected behavior:**
In all prior efforts no crash has occurred and I can edit the video..

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ l2.6.1-dev}}
- Operating System / Distro: [Windows 10]

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

**Exception / Stacktrace:**
[libopenshot.zip](https://github.com/OpenShot/openshot-qt/files/9176439/libopenshot.zip)

If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by JacksonRG** [comment]
What do you mean by a timing thing? Do you mean that the crash happens when you input a lot of actions into OpenShot in a short time?

**Comment by jonmcarr** [comment]
I believe the application will crash within a few minutes regardless of what actions are taken. 
I am simply trying to edit 9 minutes of silence from a video. When I mark the point for the cut and attempt to make the cut, the application is crashing. I was working fine on Saturday and Sunday it is no longer working. I updated the code with the daily version and I have reset my computer a few times.
I see nothing in the logs reporting an error or failure.
Hope this helps.
 

    On Monday, July 25, 2022 at 12:45:05 PM CDT, JacksonRG ***@***.***> wrote:  
 
 


What do you mean by a timing thing? Do you mean that the crash happens when you input a lot of actions into OpenShot in a short time?

**Comment by Colorjet3** [comment]
Please download the latest dev daily build from openshot.org/download/#daily and give it a try.

**Comment by Colorjet3** [comment]
This should be fixed in the latest DEV daily build of v3.0.0
