### ISSUE TITLE
blender: animated title 3D problème 

### ISSUE THREAD

**Issue by masterchief1450555599999** [OpenShot/openshot-qt#487]
Hello,
I have a problem with openshot. I would like to use the animated 3D title but when i click on the button a message is say: "the access path is wrong".
My access path: C:\Program Files (x86)\Blender Foundation\Blender
Thanks

**Comment by mixedbredie** [comment]
The path needs to include the blender.exe so try this:

```C:\Program Files (x86)\Blender Foundation\Blender\blender.exe```

**Comment by masterchief1450555599999** [comment]
Hello 

I also tried this but it does not work. I have tried others too that do not work either. What to do?

Good afternoon

**Comment by mixedbredie** [comment]
Hi @masterchief1450555599999 

Try to run one of the blend file and python scripts from the command line and check the errors.

```/path/to/blender.exe -b /path/to/blend/file.blend -P /path/to/python/script.py```

The blend files are in C:\Program Files\OpenShot Video Editor\blender\blend and the python scripts are in C:\Program Files\OpenShot Video Editor\blender\scripts.

**Comment by masterchief1450555599999** [comment]
I have just tried this path C: \ Program Files (x86) \ Blender Foundation \ Blender \ Blender.exe but a black blender command opens and closes, and the message "No image was found Blender Output "appears on Openshot.

**Comment by masterchief1450555599999** [comment]
I will try what you advised me with the mixing files

**Comment by masterchief1450555599999** [comment]
I went into the scripts folder, there are plenty of white files for example "Explode" to ".py". When I insert them in Openshot it puts me invalid file. I can not execute it, it does not work. What else can I do?

**Comment by masterchief1450555599999** [comment]
Sorry to post a lot of messages but I tried in preferences to put this command /path/to/blender.exe -b /path/to/blend/file.blend -P / path / to / python / script. Py but it always puts me "check that the path is correct"

**Comment by mixedbredie** [comment]
Okay @masterchief1450555599999 
Open up a command prompt (start > programs > accessories > command prompt)
In the black window that opens type the following (making sure path is correct for 32bit or 64bit windows):

```"C:\Program Files (x86)\Blender Foundation\Blender\blender.exe" -b "C:\Program Files\OpenShot Video Editor\blender\blend\blinds.blend" -P "C:\Program Files\OpenShot Video Editor\blender\scripts\blinds.py"```

![os_blend_cmd](https://cloud.githubusercontent.com/assets/3995787/22249508/294c6bb4-e23b-11e6-81b3-1b5f755a6d99.jpg)

Press Return and you'll get some text like this:

![os_blend](https://cloud.githubusercontent.com/assets/3995787/22249357/9a526f3a-e23a-11e6-988d-85102aae6a4c.jpg)

There may be an error about __text objects__ and __align__ in which case you need to update some of the scripts. It will probably complain about KeyErrors but at least Blender is reading the correct file and calling the correct script.

Now try in OpenShot by opening the Title > Animated Title tool.  Can you generate the Snow animation?  Try the Blinds animation with some short words.

Also, in OpenShot preferences enable Debug mode and check the debug log in C:\Users\username\\.openshot-qt\ as it might have some more information.

**Comment by masterchief1450555599999** [comment]
![capture](https://cloud.githubusercontent.com/assets/25292967/22250738/545f8db0-e248-11e6-97ec-b0a643164f41.PNG)


I made the manipulation that you suggested to me and I got a message quite different from yours

Come that did not work since I still tried to put the snow text but there is always the same error message (no image found out of blender) is there anything else to do?

**Comment by masterchief1450555599999** [comment]
![capture](https://cloud.githubusercontent.com/assets/25292967/22251551/6da77280-e24b-11e6-82f2-7044d7747b6c.PNG)

**Comment by mixedbredie** [comment]
Is there anything in the debug logfile?  
Are you using Blender 2.62? The latest version of Blender is 2.78a.
Otherwise I'm all out of ideas just now.

**Comment by masterchief1450555599999** [comment]
At first I had version 2.78 then as it did not work I tried with the 2.62. But I did not find the debug file.
You think there are other solutions? Will this be corrected in the next openshot update?

**Comment by mixedbredie** [comment]
I had the same issues as you and after several reboots and testing from the command line and trying different animations it started working.  I had to fix several of the Blender scripts with updated text_object options.  If you look at the pull requests log you'll see some of them.  I am running 64bit Blender with OpenShot, not sure if that makes a difference.

There are a lot of issues logged about Blender integration but I am not sure how much attention they get.

The log file is in C:\Users\username\openshot_qt and should be called openshot-qt.log.  You need to enable debug logging in the OpenShot preferences.

**Comment by masterchief1450555599999** [comment]
i have find openshot qt

**Comment by masterchief1450555599999** [comment]
blender_treeview:INFO onBlenderErrorMessage
 main_window:INFO animated title add cancelled
    tutorial:INFO minimize tutorial

**Comment by masterchief1450555599999** [comment]
i have installed blender 2.78, bug it doesn't working (animated title)

**Comment by masterchief1450555599999** [comment]
As I think it does not come from my computer, I hope this will be corrected since it is a beta version.

**Comment by marron-glace** [comment]
Have a look here #473 (cela peut, peut-être, vous aider).

**Comment by masterchief1450555599999** [comment]
thanks

**Comment by masterchief1450555599999** [comment]
I installed the latest version of openshot released on January 26, and when I run I get this error: screenshot attached
![capture](https://cloud.githubusercontent.com/assets/25292967/22395300/93bc0940-e539-11e6-976a-bfa2ba8b6ed7.PNG)


But when I release the December 29th version, everything reads ... How can I use the latest version? thank you in advance

**Comment by masterchief1450555599999** [comment]
Is there a solution please?

**Comment by marron-glace** [comment]
You use Python / MSys (unix), so I'm not able to help.
I do not install any Python, my Python (3.5.1) apis are those installed by Blender or others on my Windows 10 64 system.

**Comment by masterchief1450555599999** [comment]
I have not installed python it installed with windows. Like yours. :)

**Comment by mixedbredie** [comment]
I think those Python errors come from some reference to the developer's build system.  CX_freeze is used to build the OpenShot package with all included dependencies on Mac and Windows.  There is either a missing dependency or a path is incorrect - see https://github.com/OpenShot/openshot-qt/issues/341#issuecomment-268336555

**Comment by jonoomph** [comment]
Please test again with the latest daily build of OpenShot. I've merged in changes to the text alignment, and updated the minimum version compatibility to 2.78. I've tested all animation on Linux, Mac, and Windows with Blender 2.78 and everything works great.

Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot. _It might take a couple hours for the latest version to appear._

If you have other issues, please file additional bugs for each one. Thanks!a
