### ISSUE TITLE
Crash on importing certain .mp4 video

### ISSUE THREAD

**Issue by coffeeflake** [OpenShot/openshot-qt#4871]
**Describe the bug:**
OpenShot crashes upon importing a specific .mp4 video.

**Steps to reproduce the behavior:**
1. Launch OpenShot.
2. Add "[corba.mp4](https://user-images.githubusercontent.com/24939250/181751318-f30afac1-5838-4ec8-b9db-20beef110c85.mp4)" to project files via dragging or with "Import Files" button.
3. Program freezes and then crashes

**Expected behavior:**
The program should import the video without crashing.

**System Details**
- OpenShot Version: 2.6.1-dev
- libopenshot Version:  0.2.7-dev
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-dev-daily-9604-5776efd7-46255e46-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/q7svv4gyd9y0cfcupmtizlu7t9ljrzen/openshot-qt.zip) (8 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/q7svv4gyd9y0cfcupmtizlu7t9ljrzen/libopenshot.zip) (16 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Comment by cpt-westphalen** [comment]
I have a simillar issue, while trying to import an mp4 recording from my Sansung Galaxy S10 phone.

```
INFO files_model: Imported media file /home/rbwestphalen/Videos/20230203_104033.mp4
Caught signal 11 (SIGSEGV)
---- Unhandled Exception: Stack Trace ----
  /usr/lib/python3/dist-packages/_openshot.cpython-310-x86_64-linux-gnu.so ( swig::SwigPyForwardIteratorOpen_T<std::_Rb_tree_iterator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, swig::from_oper<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::value() const  + 0x16  )  [0x7f95abcf5ec6]
  /usr/lib/python3/dist-packages/_openshot.cpython-310-x86_64-linux-gnu.so (                                           + 0xbc8fd)  [0x7f95abc048fd]
  /usr/bin/python3               (                                           + 0x15b564)  [0x55f33865e564]
  /usr/bin/python3               ( _PyEval_EvalFrameDefault                  + 0x2a70)  [0x55f33864a3b0]
  /usr/bin/python3               ( _PyFunction_Vectorcall                    + 0x7c  )  [0x55f33865f3ac]
  /usr/bin/python3               ( _PyEval_EvalFrameDefault                  + 0x80a )  [0x55f33864814a]
  /usr/bin/python3               ( _PyFunction_Vectorcall                    + 0x7c  )  [0x55f33865f3ac]
  /usr/bin/python3               ( _PyEval_EvalFrameDefault                  + 0x6c5 )  [0x55f338648005]
  /usr/bin/python3               (                                           + 0x16a391)  [0x55f33866d391]
  /usr/bin/python3               ( _PyEval_EvalFrameDefault                  + 0x6c5 )  [0x55f338648005]
  /usr/bin/python3               ( _PyFunction_Vectorcall                    + 0x7c  )  [0x55f33865f3ac]
  /usr/bin/python3               ( _PyEval_EvalFrameDefault                  + 0x80a )  [0x55f33864814a]
  /usr/bin/python3               ( _PyFunction_Vectorcall                    + 0x7c  )  [0x55f33865f3ac]
  /usr/bin/python3               ( _PyEval_EvalFrameDefault                  + 0x80a )  [0x55f33864814a]
  /usr/bin/python3               ( _PyObject_FastCallDictTstate              + 0xc4  )  [0x55f338654964]
  /usr/bin/python3               (                                           + 0x166594)  [0x55f338669594]
  /usr/bin/python3               ( _PyObject_MakeTpCall                      + 0x1fc )  [0x55f33865577c]
  /usr/bin/python3               ( _PyEval_EvalFrameDefault                  + 0x6b4e)  [0x55f33864e48e]
  /usr/bin/python3               ( _PyFunction_Vectorcall                    + 0x7c  )  [0x55f33865f3ac]
  /usr/bin/python3               ( _PyEval_EvalFrameDefault                  + 0x80a )  [0x55f33864814a]
  /usr/bin/python3               (                                           + 0x16a4de)  [0x55f33866d4de]
  /usr/bin/python3               ( _PyEval_EvalFrameDefault                  + 0x2a70)  [0x55f33864a3b0]
  /usr/bin/python3               ( _PyFunction_Vectorcall                    + 0x7c  )  [0x55f33865f3ac]
  /usr/bin/python3               ( _PyEval_EvalFrameDefault                  + 0x2a70)  [0x55f33864a3b0]
  /usr/bin/python3               ( _PyFunction_Vectorcall                    + 0x7c  )  [0x55f33865f3ac]
  /usr/bin/python3               ( _PyEval_EvalFrameDefault                  + 0x6132)  [0x55f33864da72]
  /usr/bin/python3               ( _PyFunction_Vectorcall                    + 0x7c  )  [0x55f33865f3ac]
  /usr/bin/python3               ( _PyEval_EvalFrameDefault                  + 0x80a )  [0x55f33864814a]
  /usr/bin/python3               (                                           + 0x16a5f1)  [0x55f33866d5f1]
  /usr/bin/python3               (                                           + 0x297aaa)  [0x55f33879aaaa]
  /usr/bin/python3               (                                           + 0x28dd38)  [0x55f338790d38]
  /lib/x86_64-linux-gnu/libc.so.6 (                                           + 0x94b43)  [0x7f95acd4ab43]
  /lib/x86_64-linux-gnu/libc.so.6 (                                           + 0x126a00)  [0x7f95acddca00]
---- End of Stack Trace ----
QObject::~QObject: Timers cannot be stopped from another thread

```

**I did, however, manage to import it** after running `ffmpeg -i filename.mp4 -filter:v fps=fps=30 filename-2.mp4`, which actually didn't change framerate, as it was should already be 30fps, but did change something.

I'm not sure if this helps, but that is from ffmpeg log:
```
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
  Stream #0:1 -> #0:1 (aac (native) -> aac (native))

```

**Comment by Colorjet3** [comment]
Please download the latest DEV Daily build from openshot.org/download/#daily and give it a try.

Please let me know how it went either way.

**Comment by smittie** [comment]
I am seeing the same issue.

Linux Mint 21.1
Cinnamon Version 5.6.7

OpenShot installed and updated from:
`-rw-r--r-- 1 root root  370 Feb 26 14:05 openshot_developers-libopenshot-daily-jammy.list`


```
INFO app: ------------------------------------------------
INFO app:             Fri Mar  3 10:20:21 2023            
INFO app:               Starting new session              
INFO app: ------------------------------------------------
INFO app:             OpenShot (version 3.0.0)            
INFO app: ------------------------------------------------
INFO app: openshot-qt version: 3.0.0
INFO app: libopenshot version: 0.3.0
INFO app: platform: Linux-5.15.0-60-generic-x86_64-with-glibc2.35
INFO app: processor: x86_64
INFO app: machine: x86_64
INFO app: python version: 3.10.6
INFO app: qt5 version: 5.15.3
INFO app: pyqt5 version: 5.15.6
INFO project_data: Setting profile to 4K UHD 2160p 29.97 fps
INFO project_data: Apply default audio playback settings: 48000, 2 channels
INFO app: checking babl_ext_path: /usr/lib/python3/dist-packages/openshot_qt/lib/babl-ext
```
Video was recorded using a Pixel 7 (Android 13). Video file that causes the crash is too big to be attached here but I can make it available if that would be helpful. Attached are the libopenshot.log and the openshot-qt.log.

OpenShot crashes when:
1. The video file is dragged to the Project Files panel on a new project.
2. The video file is imported via the File menu on a new project.
3. The video file is dragged to the Project Files panel on an existing project.
4. The video file is imported via the File menu on an existing project.

Other video files can be added successfully in all of the above cases.

Willing to provide any additional information or testing as requested. I had some difficulty ensuring that I am running the daily build. I believe that I am on the latest DEV Daily build. If I am not, let me and I will fix that.


[libopenshot.log_for_4871.txt](https://github.com/OpenShot/openshot-qt/files/10884929/libopenshot.log_for_4871.txt)
[openshot-qt.log_for_4871.txt](https://github.com/OpenShot/openshot-qt/files/10884930/openshot-qt.log_for_4871.txt)

**Comment by smittie** [comment]
Had a similar or maybe the same issue (as you might have seen in the report that I filed and then deleted). I downloaded the latest AppImage from openshot.org/download/#daily and was able to import the video file without issue.

**Comment by Colorjet3** [comment]
This is great @smittie.  I'll close this ticket as resolved.
