### ISSUE TITLE
Close/crash when clipping videos

### ISSUE THREAD

**Issue by Ninko85** [OpenShot/openshot-qt#4872]
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/9222389/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/9222390/openshot-qt.log)

**Describe the bug:**
When clipping a video, the program will just randomly close/crash.

**Steps to reproduce the behavior:**
1. Import a video clip.
2. Right click on video and go to Clip Video
3. Use Left and Right keyboard buttons to go through frames and the close/crash will randomly occur.

**Expected behavior:**
It shouldn't close/crash.

**System Details:**
- OpenShot Version 2.6.1
- Operating System / Distro: Windows 10

**Comment by Colorjet3** [comment]
This has been fixed in v3.0.0.  As of this reply, please go to openshot.org/download/#daily and get the latest DEV Daily build of v3.0.0.
