### ISSUE TITLE
Forward Time + Backward Time loop does not work correctly and leads to frame skipping.

### ISSUE THREAD

**Issue by SkybuckFlying** [OpenShot/openshot-qt#4875]
The idea is as follows:
Video input:
Frame 1, Frame 2, Frame 3, Frame 4

Video output should be:
Frame 1, Frame 2, Frame 3, Frame 4, Frame 3, Frame 2, Frame 1

Like ping pong but in time. 

I tried to create this ping pong/time/reverse time loop by duplicating the video and then set time to backward.

After exporting the video, it leads to frame skipping in the center.

It's amazing how OpenShot video cannot do a basic job like this.

The playback is bad with VCL media player.

H.264 was tried, for mpg and avi, both with same bad playback.

Maybe bug is with gpu and/or VCL media player, but check for yourself.

**Comment by Colorjet3** [comment]
Please go to openshot.org/download/#daily and download the latest DEV daily build.  Many fixes and enhancements.  Please confirm if this issue is fixed or still exists.
