### ISSUE TITLE
Remember last folder traverse

### ISSUE THREAD

**Issue by SkybuckFlying** [OpenShot/openshot-qt#4876]
99.9% of windows software is super annoying it doesn ot remember the last folder that was opened or traverse !

Remember it, it can save huge ammounts of time.

Add a reset to default folder/button if you must.

Get rid of this HUGE time wasting.

**Comment by JacksonRG** [comment]
@SkybuckFlying have you tried our daily [build](https://www.openshot.org/download/)? I wrote a change so that Openshot remembers the location of the last folder you import from, and an option to remember the last location you exported to.

**Comment by Colorjet3** [comment]
Hello @SkybuckFlying .  Starting with daily builds of 2.6.x (I can not remember which build #) a new Location tab has been added to Edit | Preferences where you can control some of the behavior of Importing, saving, and Exporting location.  There is still room for improvement and enhancements request to further improve this is in the queue.

Give the latest DEV Daily Build a try (openshot.org/download/#daily).
