### ISSUE TITLE
Appears incompatible with Ubuntu 22.04

### ISSUE THREAD

**Issue by qualquiere** [OpenShot/openshot-qt#4878]
Unable to open app under Ubuntu 22.04. Deinstallation/reinstallation does not change logged error:
" metrics:ERROR Error determining OS version in metrics.py", among others
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/9229746/openshot-qt.log)

**Comment by ciamarie** [comment]
I'm having this same issue. I could open it under 20.04, but after a recent upgrade to 22.04 it won't open. It appears to be running in the system monitor, and trying to launch it a 2nd time brings up a 2nd instance in the system monitor. After reading an older issue I launched it again to see if it was just going to take a while, but it's now been 20 minutes, and it's still not open.I just ended the process.

**Comment by rl-musik** [comment]
Here it's working quite fine (OpenShot Version 2.6.1, libopenshot: 0.2.7) except 
an issue with PPA (https://github.com/OpenShot/openshot-qt/issues/4905#issue-1361086008) 

System: Kernel: 5.15.0-47-generic x86_64 bits: 64 compiler: gcc v: 11.2.0 Desktop: MATE 1.26.0 wm: marco dm: LightDM Distro: Linux Mint 21 Vanessa base: Ubuntu 22.04 jammy

**Comment by rogonow** [comment]
This worked for me to launch it:
```
sudo add-apt-repository ppa:openshot.developers/libopenshot-daily
sudo apt update
sudo apt-get upgrade
sudo apt install openshot-qt python3-openshot
```
