### ISSUE TITLE
Time line blocked

### ISSUE THREAD

**Issue by sfortin1966** [OpenShot/openshot-qt#4879]
**Describe the bug:**

**Steps to reproduce the behavior:**

**Expected behavior:**

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by sfortin1966** [comment]
The timeline cursor is no longer accessible on one of my project. The icon to reduce or inlarge my projet is not active. It works for all other projects?? Any idea why?
![timeline](https://user-images.githubusercontent.com/110402736/182175504-b6700fba-b02d-4e5c-82a6-c3867122e298.png)

**Comment by JacksonRG** [comment]
Does this mean that clicking and dragging the right handle of the resize bar doesn't cause it to move? 

Also you can try the keyboard shortcut to see if that works. To do this, click somewhere on the timeline, then press the `+` or `-` keys. If you do this, does it change whether you can drag the right handle with your mouse?

Lastly, it might help if you include your log files. Instructions to find them are found [here](https://github.com/OpenShot/openshot-qt/wiki/Issue-Logging).

**Comment by sfortin1966** [comment]
Hi,


Does this mean that clicking and dragging the right handle of the resize bar doesn't cause it to move? Yes exactly

The + or – doesn’t work on this particular project or any other one



[Maison Russet]<https://www.maisonrusset.com/>
Stéphane Fortin
Conseiller en développement
Tél.     : 450 631 4558 <tel:+18882649449>
Téléc. : 450 264-9451 <tel:+14502649451>
***@***.*** ***@***.***>
142, route 202, Suite 103, Huntingdon (QC) JOS 1H0
maisonrusset.com <https://maisonrusset.com/>
[http://agencezel.com/mail-signature/russet/icon-facebook-16x16.jpg]<https://www.facebook.com/RussetHouse/>
[http://agencezel.com/mail-signature/russet/icon-instagram-16x16.jpg]<https://www.instagram.com/maisonrusset/>
[http://agencezel.com/mail-signature/russet/icon-linkedin-16x16.jpg]<https://www.linkedin.com/company/maison-russet/>

[http://agencezel.com/mail-signature/russet/icon-arbre-16x16.jpg]
Faites bonne impression et imprimez seulement au besoin.

Ce message peut contenir de l’information privilégiée ou confidentielle. Si ce message ne vous est pas adressé ou si vous
l’avez reçu par erreur, veuillez aviser l’émetteur immédiatement et effacer l’original, sans en tirer de copie ni en dévoiler le contenu.


De : JacksonRG ***@***.***>
Envoyé : 2 août 2022 01:19
À : OpenShot/openshot-qt ***@***.***>
Cc : Stephane Fortin ***@***.***>; Author ***@***.***>
Objet : [InfoMail] - Re: [OpenShot/openshot-qt] Time line blocked (Issue #4879)



[EXTERNE/EXTERNAL]


Ce courriel provient de l'extérieur de Maison Russet. Veuillez nous aider à assurer la sécurité de notre organisation et de nos partenaires. Ceci dépend de nous; Pensez avant de cliquer.
This email is from outside Russet House. Please help us keep our organization and partners safe. It is up to all of us; Think before you click.

Does this mean that clicking and dragging the right handle of the resize bar doesn't cause it to move?

Also you can try the keyboard shortcut to see if that works. To do this, click somewhere on the timeline, then press the + or - keys. If you do this, does it change whether you can drag the right handle with your mouse?

Lastly, it might help if you include your log files. Instructions to find them are found here<https://github.com/OpenShot/openshot-qt/wiki/Issue-Logging>.

**Comment by JacksonRG** [comment]
You said only one project froze like this. Can you get this issue again if you create another project with the same files?

**Comment by Colorjet3** [comment]
This timeline issue has been fixed in the latest DEV Daily Build (openshot.org/download/#daily).  Please confirm either way.
