### ISSUE TITLE
I cant use my GPU to have better performance/experience because the GPU encoder option is not there. Need Help

### ISSUE THREAD

**Issue by Aarishmughal** [OpenShot/openshot-qt#4882]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 2.6.1
- libopenshot Version:  0.2.7
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-dev-daily-9604-5776efd7-46255e46-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/8ej51i4eqqppvsqk305flngllms7jwk7/openshot-qt.zip) (9 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.
               
![GrjslnEwDs5G](https://user-images.githubusercontent.com/110604636/182830418-14a6d8f9-cfc1-423d-8b51-39ace7f7dcd0.png)

**Comment by JacksonRG** [comment]
Hi, we don't support GPU acceleration on Windows currently. If your video's performance is too low in preview, I recommend lowering the resolution, while editing, and increasing it when exporting.
