### ISSUE TITLE
OpenShot keeps crashing after a minute of use

### ISSUE THREAD

**Issue by tomseim** [OpenShot/openshot-qt#4883]
**Describe the bug:**
Program repeatedly crashes after a short period of use.
**Steps to reproduce the behavior:**
1. Add video to Track 1.
2. Change video time > fast > forward > 16x
3. Cut video left, then right.
4. Repeat 3 a few times

**Expected behavior:**
Normal operation w/o crashing.

**System Details:**
- OpenShot Version 2.6.1
- Operating System Win 11

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/9263613/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/9263615/openshot-qt.log)

**Comment by JacksonRG** [comment]
Hi, looked into your log files, but couldn't find much. Could you open preferences and under `Debug` enable `Debug Mode (Verbose)`?

That may give some more info in your log files if you re-upload them.

**Comment by Colorjet3** [comment]
Download and install the latest DEV Daily build #9856.  I tested this build in Windows 11 and it worked.  OpenShot does go into "Not Responding" mode for a while but eventually completes the task.  If you watch Task Manager you will notice that OpenShot CPU consumption goes up.  It took 2.5min+ to complete the task.

Go to openshot.org/download, click on Daily Builds, download the latest available build and install.
