### ISSUE TITLE
Can't open webm file

### ISSUE THREAD

**Issue by HoneHoneo** [OpenShot/openshot-qt#4884]
**Describe the bug:**
I can't open file webm file,and close Openshot.

**Steps to reproduce the behavior:**
I drag "import file",which is Japanese "ファイルをインポート"
I choose webm file
Openshot closed

Why?

**Comment by JacksonRG** [comment]
Could you attach your log files? And include any other information, like what kind of computer, and operating system you're using?

Instructions for finding log files are [here](https://github.com/OpenShot/openshot-qt/wiki/Issue-Logging). And have you already tested if this happens in our [daily build](https://www.openshot.org/download/)?

**Comment by Colorjet3** [comment]
Please download the latest DEV Daily Build #9856 and install it.  Give it a try and let us know if you are still having an issue.  If you are then see if you can run your .webm file through a converter and convert it to a .mp4 file.  Import this .mp4 file into OpenShot.  does it work?  

Also, does your .webm file play outside of OpenShot?
