### ISSUE TITLE
please share documentry of openshort

### ISSUE THREAD

**Issue by mitulsojitra1777** [OpenShot/openshot-qt#4887]
**Question:**
A clear and concise question. Your question should provide enough context and explanation for people to answer it. Avoid excessive background or irrelevant details, as they can obscure your actual question.

**System Details:**

- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your question. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

i can use oenshort for news editor we can autometicaly create project and add images video and music on project files but we can not get progrommar gide lik documentation of this project

**Comment by JacksonRG** [comment]
@mitulsojitra1777 You can find our documentation [here](https://www.openshot.org/user-guide/). And I'm happy to answer any other questions that you have.
