### ISSUE TITLE
File | Save Project is not enabled when changes are made after a Save.

### ISSUE THREAD

**Issue by GollyRojer** [OpenShot/openshot-qt#4889]
**Describe the bug:**
I saved my project using File | Save Project. I then made changes and went to save again, but File | Save Project was not enabled. It was necessary for me to use "Save Project As..." and overwrite the project file I had open.

**Steps to reproduce the behavior:**
1. Save an open project using File | Save Project
2. Add a clip to the timeline
3. Edit the clip to set Volume | Entire Clip | Level 0
4. Edit the clip to set Time | Fast | Forward | 2x
5. Attempt to save the project using File | Save Project
6. Error: File | Save Project is not enabled

**Expected behavior:**
File | Save Project should be enabled after edits are made

**System Details:**
- OpenShot Version: 2.6.1 
- Operating System / Distro: Windows 11 Home, Version 21H2, OS Build 22000.856

**Comment by JacksonRG** [comment]
I'm having some trouble reproducing this bug. Did you test it on the [daily build](https://www.openshot.org/download/)?

**Comment by Colorjet3** [comment]
Are you able to replicate this?  If yes, please tell us what kind of changes you are making then trying to save the project?  This could be a bug where specific changes don't trigger the flag indicating something has changed in the project and this will help the developers to better track and resolve the issue.

**Comment by Colorjet3** [comment]
No Response
