### ISSUE TITLE
Error in `/usr/bin/python': malloc(): 

### ISSUE THREAD

**Issue by matschi-klickme** [OpenShot/openshot-qt#489]
Hello, 
I ran into this error soon after starting to render: 

*** Error in `/usr/bin/python': malloc(): smallbin double linked list corrupted: 0x00007fd05c051d10 ***

Log after Error:
[openshot_log.txt](https://github.com/OpenShot/openshot-qt/files/735671/openshot_log.txt)

System: 
4.8.13-1-ARCH x86_64 Linux
Python 3.6.0
ffmpeg version 3.2.2
openshot-qt 2.0.6-2

Thank you for your time. 
Best regards

**Comment by jonoomph** [comment]
Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build **AppImage** of OpenShot. This is a few versions too old. =) Please reopen this ticket if you still experience the issue with our latest AppImage.

**Comment by felixsanz** [comment]
@jonoomph I'm getting the error using **2.3.4-dev3** :/
