### ISSUE TITLE
The problem is that the video and audio are not downloaded on openShot

### ISSUE THREAD

**Issue by basem88888** [OpenShot/openshot-qt#4890]
**Question:**
A clear and concise question. Your question should provide enough context and explanation for people to answer it. Avoid excessive background or irrelevant details, as they can obscure your actual question.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your question. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by basem88888** [comment]
The problem is that the video and audio are not downloaded on openShot

**Comment by JacksonRG** [comment]
@basem88888 what do you mean by not downloaded? Are you not able to import files into your openshot projects?

**Comment by Colorjet3** [comment]
No Response.
