### ISSUE TITLE
File import triggers SIGABRT: 'corrupted size vs. prev_size' and other memory errors

### ISSUE THREAD

**Issue by johnruemker** [OpenShot/openshot-qt#4891]
**Describe the bug:**
Upon importing a video file recorded by my Google Pixel 3XL phone camera, Openshot crashes/freezes and the terminal output shows SIGABRT and memory error. 

**Steps to reproduce the behavior:**
1. Launch Openshot
2. Click on + (Import Files)
3. Choose a video recorded by my phone.  [Here](https://drive.google.com/file/d/1ASEkCWXZ6JpYXCrKG2R4SIur3wNT8XkA/view?usp=sharing) is a link to a file I'm reproducing this with right now
4. With many (but not all) of my video files, Openshot freezes.  System dialog notifies me that python3 is not responding, offering to Force Quit or Wait).  Error below is seen in terminal. 
    + The crashing is inconsistent, even with the same video file.  I am attaching a log file from one session where I loaded a video file, removed it from the project, then loaded the same file and it crashed. 
5. I have not been able to reproduce this behavior with videos from any other source other than my phone.  I recognize this possibly implicates my phone, but I am recording with the Google Camera app on a very standard Google Pixel 3XL so I'm hesitant to blame this device. And again, seems like openshot should handle the file gracefully regardless. 

**Expected behavior:**
openshot does not crash. If there is a problem with the video file, report the error and continue allowing user action. Or better yet, skip malformed sections of the video if possible

**System Details:**
- OpenShot Version: 
    + Initially encountered problem on rpmfusion's openshot-2.6.2-0.2.20211104gitb72327d.fc36
    + Problem reproduced on latest git: 2.6.1-dev git d5a485b
    + Problem is NOT reproduceable when launching via the latest AppImage: OpenShot-v2.6.1-dev-daily-9604-5776efd7-46255e46
- Operating System / Distro: Fedora 36

**Log Files:**
Attached:
- [openshot-debug.log](https://github.com/OpenShot/openshot-qt/files/9352605/openshot-debug.log)
- [openshot-debug2.log](https://github.com/OpenShot/openshot-qt/files/9352742/openshot-debug2.log) - this is an instance where I was able to import a video, remove it from the project, import the same video, and the problem is triggered. 
- [openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/9352603/openshot-qt.log)
- [libopenshot.log](https://github.com/OpenShot/openshot-qt/files/9352602/libopenshot.log)

**Exception / Stacktrace:**
```
INFO files_model: Imported media file /home/jruemker/Content/Local Videos/aug16/PXL_20220815_122514300.mp4
INFO logger_libopenshot: Decode in software is used
 ()
INFO project_data: _set key: ['files'] values: {'acodec': 'aac', 'audio_bit_rate': 127999, 'audio_stream_index': 1, 'audio_timebase': {'den': 44100, 'num': 1}, 'channel_layout': 3, 'channels': 2, 'display_ratio': {'den': 16, 'num': 9}, 'duration': 5.967528343200684, 'file_size': '6309954', 'fps': {'den': 1, 'num': 30}, 'has_audio': True, 'has_single_image': False, 'has_video': True, 'height': 1920, 'interlaced_frame': False, 'metadata': {'compatible_brands': 'isommp42', 'creation_time': '2022-08-15T12:25:21.000000Z', 'encoder': 'Google', 'handler_name': 'ISO Media file produced by Google Inc.', 'language': 'eng', 'location': '+35.7944-78.9138+000.000/', 'major_brand': 'mp42', 'minor_version': '0', 'vendor_id': '[0][0][0][0]'}, 'path': '/home/jruemker/Content/Local Videos/aug16/PXL_20220815_122514300.mp4', 'pixel_format': 0, 'pixel_ratio': {'den': 1, 'num': 1}, 'sample_rate': 44100, 'top_field_first': True, 'type': 'FFmpegReader', 'vcodec': 'h264', 'video_bit_rate': 1057297, 'video_length': '177', 'video_stream_index': 0, 'video_timebase': {'den': 15360, 'num': 1}, 'width': 1080, 'media_type': 'video', 'id': 'DNUV8TSN5G'} add: True partial: False remove: False
INFO logger_libopenshot: FFmpegReader::UpdateVideoInfo (info.fps.num=30.0000, info.fps.den=1.0000)
INFO logger_libopenshot: FFmpegReader::UpdateVideoInfo (pStream->avg_frame_rate) (num=30.0000, den=1.0000)
INFO logger_libopenshot: FFmpegReader::Close ()
corrupted size vs. prev_size
Caught signal 6 (SIGABRT)
---- Unhandled Exception: Stack Trace ----
```

NOTE that I have also seen other errors in my various tests. The above "corrupted_size vs prev_size" is almost always what happens, but I have also seen the following errors earlier today, which unfortunately I did not capture the logs from.  The terminal output looked about the same up until the error - no other stack traces or anything grabbed my attention in those instances. 

- corrupted double linked-list
- malloc(): corrupted top size

**Comment by johnruemker** [comment]
Using the latest daily AppImage seems to be a viable workaround for the time being.

**Comment by JacksonRG** [comment]
@johnruemker Awesome, glad to hear that. That video worked for me on the most recent code as well. That means that the change that fixed it will be in the next stable release.

**Comment by JacksonRG** [comment]
Even better news: I just tested with the 2.6.1 release, and I saw the freeze as well, so the issue was reproduced on my system as well.

**Comment by johnruemker** [comment]
> Even better news: I just tested with the 2.6.1 release, and I saw the freeze as well, so the issue was reproduced on my system as well.

Is it actually fixed though, or does executing in AppImage just avoid it somehow?  I am able to reproduce the issue on the latest git by executing directly (python src/launch.py).  I was interpreting that to mean that the issue is still present, but AppImage execution does something different with memory handling.

**Comment by JacksonRG** [comment]
Strange. I was running both versions from source, when I reproduced the crash, and then avoided the crash.

Are you also updating to the latest libopenshot code when you run from source?

**Comment by johnruemker** [comment]
> Are you also updating to the latest libopenshot code when you run from source?

Oh, no, I suppose I am not.  That would make sense as an explanation. I will trust then that this is indeed fixed in the latest, whether with AppImage or normal execution.  I'll look forward to this fix making it into fedora / rpmfusion releases so I can use that again.  Thanks for the tip and the help. Feel free to close this if it's ready.

**Comment by JacksonRG** [comment]
Great, until then, I hope the appimage or running from source (With updated libopenshot) solves your issues.

**Comment by taq** [comment]
Just got this error here on Ubuntu 23.10:

```
corrupted size vs. prev_size
Caught signal 6 (SIGABRT)
---- Unhandled Exception: Stack Trace ----
```

Please correct me if I'm wrong, but the PPA don't have a mantic (23.10) tag yet, right?
