### ISSUE TITLE
openshot crashed while running

### ISSUE THREAD

**Issue by zzzbbs** [OpenShot/openshot-qt#4892]
**Describe the bug:**
sometimes when i move the timeline in the channel ,the openshot crashed.

**System Details:**
- OpenShot Version : 2.6.1
- Operating System / Distro: Ubuntu 20.04

the following is what i caught from the log file:
09:21:43 INFO version: Found current version: {'trans_rate_unstable': 0.001, 'error_rate_stable': 0.16, 'trans_rate_stable': 0.01, 'error_rate_unstable': 0.05, 'openshot_version': '2.6.1'}
09:21:43 INFO sentry: Sentry initialized with 0.16 error reporting rate (production)
09:21:43 INFO main_window: InitCacheSettings
09:21:43 INFO main_window: cache-mode: CacheMemory
09:21:43 INFO main_window: cache-limit-mb: 1000
09:21:43 INFO main_window: Creating CacheMemory object with 1048576000 byte limit
09:21:43 INFO preview_thread: QThread Start Method Invoked
09:21:43 ERROR main_window: Unhandled crash detected: -linux-Timeline::GetFrame (Add frame to cache) 
09:21:43 INFO main_window: updateStatusChanged
09:21:43 INFO main_window: recover_backup
09:21:43 INFO project_data: Setting default profile to HD 720p 30 fps
09:21:43 INFO preview_thread: player Position(): 1
09:21:43 INFO video_widget: Load: Set video widget display aspect ratio to: 1.7777777910232544
09:21:43 INFO video_widget: Set video widget pixel aspect ratio to: 1.0
09:21:43 INFO main_window: updateStatusChanged
09:21:43 INFO preview_thread: player Position(): 1
09:21:43 INFO timeline: Adjusting max size of preview image: PyQt5.QtCore.QSize(640, 360)
09:21:43 INFO preview_thread: player Position(): 1
09:21:43 INFO webengine: Registering WebChannel connection with WebEngine
09:21:43 INFO webview: Qt Ready
09:21:43 INFO webview: Angular Ready
09:21:46 INFO main_window: ---------------- Shutting down -----------------
09:21:46 INFO thumbnail: Shutting down thumbnail server: ('127.0.0.1', 47487)
09:21:46 WARNING logger_libopenshot: 对非套接字进行套接字操作
09:21:46 INFO app:             OpenShot's session ended            
09:21:46 INFO app:             Wed Aug 17 09:21:46 2022            
09:21:46 INFO app: ================================================

**Comment by JacksonRG** [comment]
HI, could you clarify what you mean by moving the timeline in the channel? Also have you given our daily build a try to see if this problem appears there too? You can find the daily build [here](https://www.openshot.org/download/).

Also if it is still present, are there any specific steps to cause this crash?
