### ISSUE TITLE
Spaces at the end in the directory name

### ISSUE THREAD

**Issue by thereticle** [OpenShot/openshot-qt#4895]
**Describe the bug:**
By mistake I wrote the name of a directory with a space at the end.
When I tried to create the video, Openshot gave me a generic error without recognizing the problem.

The directory name was "23.08.2022 - Lamon " (containing trailing space)

Openshot generated the following error: 
An error occurred while exporting the video: Could not open or write file. for file /home/vimo/Gopro/23.08.2022 - Lamon/Lamon2.mp4

As you can see, there is no space at the end of the directory in the error message and there is no clue as to what could have generated the error

**Steps to reproduce the behavior:**
1. Add a trailing space to a working directory
2. Click on '.Export video'
3. Select video characteristics
4. Click on "Export video"
5. See error

**Expected behavior:**
The error message should warn the user that there is a space at the end of the directory name

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 2.6.1-dev
- libopenshot Version: 0.2.7-dev
- Operating System / Distro: Ubuntu 22.04 

**Log Files:**
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/9417302/openshot-qt.log)

**Exception / Stacktrace:**
N.A.

**Screenshots:** (Optional)
![immagine](https://user-images.githubusercontent.com/20416601/186454337-451879f6-628e-4cc9-86c6-99926bd96df7.png)

**Comment by JacksonRG** [comment]
Interesting... I didn't know files with trailing whitespaces were allowed. But I'll take a look.

In the short term, I'd reccomend copying both the project file (ending in `.osp`) and the assets folder with the same name. And rename them without the space. That should allow you to export your video. If not, let me know, and I'll see how else I can help.

**Comment by JacksonRG** [comment]
Oh, nevermind my above comment, I just understood that the folder you're *exporting to* has the space, not the name of the project file. I'll see why Openshot is losing the trailing whitespace.

**Comment by JacksonRG** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Export fails if folder ends with whitespace](https://trello.com/c/K4r0cBXT/161-export-fails-if-folder-ends-with-whitespace)

**Comment by JacksonRG** [comment]
@thereticle I made a change to code for the edge case where folders may end in a whitespace. As for the error message, I'm sorry to say I don't think there's a way for openshot to warn the user about the space at the end of the path.

To a computer "/home/user/folder_name" and "/home/user/folder_name " are completely unrelated names, and it couldn't make the inference as to what the user means.

Let me know if you have any other issues.
