### ISSUE TITLE
can't use graphic interface

### ISSUE THREAD

**Issue by MesterPerfect** [OpenShot/openshot-qt#4896]
hi
I am using OpenShot Video Editor to edit videos
I have a problem with GUI

In the screenshots, the program's graphic interface appears in an organized and simple form
But it appears to me overlapping and difficult to use

I am using OpenShot-v2.6.1-x86_64 on windows8.1

![1](https://user-images.githubusercontent.com/44323153/186633476-490cc030-8000-443d-82a8-3556eaa26cfb.jpg)
![2](https://user-images.githubusercontent.com/44323153/186633500-626294af-06b1-4e4c-9df2-af54a71e0bd9.jpg)
![3](https://user-images.githubusercontent.com/44323153/186633524-299d1055-567f-4934-b173-d78ea087c0e3.jpg)

**Comment by JacksonRG** [comment]
I'm not sure I understand what you mean by overlapping and difficult to see. You can click on the `.....` symbol right above the timeline to make the timeline taller. Also under `View -> Views` in the top menu bar, you can choose a different layout for the windows. Otherwise, you can drag them to any positions you like.

**Comment by MesterPerfect** [comment]
> I'm not sure I understand what you mean by overlapping and difficult to see. You can click on the `.....` symbol right above the timeline to make the timeline taller. Also under `View -> Views` in the top menu bar, you can choose a different layout for the windows. Otherwise, you can drag them to any positions you like.

I actually had a problem with the view of the program and I was able to change the view from the View menu
View >> Views >> Simple View
I have another problem
When I add audio and photo files to Timeline
The audio files will work without sound

![image](https://user-images.githubusercontent.com/44323153/188210472-dbcc4971-a193-4d29-98b7-19dc11bb9f90.png)

**Comment by JacksonRG** [comment]
Interesting, what format of audio file are you using? It may help to convert them to a common format like MP3. You can use a tool like [handbreak](https://handbrake.fr/) for conversions like that.

**Comment by MesterPerfect** [comment]
> Interesting, what format of audio file are you using? It may help to convert them to a common format like MP3. You can use a tool like [handbreak](https://handbrake.fr/) for conversions like that.

I already use mp3 files
I have this problem even with video files
If you want, I can make a short video showing the steps I'm doing
![image](https://user-images.githubusercontent.com/44323153/188259348-4338d3f1-1bb8-4f00-96e8-529bb6fb3cbb.png)

**Comment by MesterPerfect** [comment]
@JacksonRG

**Comment by Colorjet3** [comment]
Please download the latest DEV Daily Build v3.0.0 at openshot.org/download/#daily and give it a try.  Let us know if your problem persists.

**Comment by MesterPerfect** [comment]
> Please download the latest DEV Daily Build v3.0.0 at openshot.org/download/#daily and give it a try. Let us know if your problem persists.
ok
