### ISSUE TITLE
Mouse pointer can not be seen in Appimage program using Ubuntu 22.04LTS

### ISSUE THREAD

**Issue by poconotrainman** [OpenShot/openshot-qt#4899]
Tried several Appimage files since the ppo file does not work but although the file open the mouse pointer cannot be see but if you move it around the screen you can make menus work. As soon as you close a menu the mouse disappears.
![Screenshot from 2022-08-28 16-49-58](https://user-images.githubusercontent.com/112350079/187094464-b70c952c-4701-4c38-ac13-09dc398fff2e.png)

**Comment by JacksonRG** [comment]
Odd, I'm not able to reproduce this on my machine. What desktop environment are you using, and do you have any custom theming? I ask because I see that the about window isn't it's default dark color.

**Comment by poconotrainman** [comment]
If I use the menu I can see the pointer as long as the menu is down. The second the menu closes the pointer is gone. Been using OpenShot many years and never had any problems with the mouse until Ubuntu 22.04LTS.
  
-----Original Message-----

**Comment by Colorjet3** [comment]
Please try one of the latest DEV Daily Build.  It is working fine for me in Ubuntu 22.04 LTS without any mouse pointer issues anywhere in OpenShot.  By the way, I am running the AppImage.

**Comment by poconotrainman** [comment]
Downloaded build 98
As long as I keep a menu box open I can see the mouse pointer.
As soon as I close the menu box the mouse disappears.

Unfortunately as long as the menu box is open the mouse 
can't open any other menus or functions to work. 

Fortunately it works perfectly in Windows 11 but I much prefer Ubuntu 22.04LTS.
I tried to install Flatpak but it seems it will not complete the installation of it's repository.
Please keep up your efforts to get this working in Ubuntu 22.04
Sincere Thanks,John
 
 
 
-----Original Message-----

**Comment by Colorjet3** [comment]
Version 3.0.0 has been released.  Give it a try.

**Comment by poconotrainman** [comment]
Thanks for not forgetting about this issue. I did download and try the new version on two different Ubuntu 22.04LTS computers, the mouse still disappears when no menu is activated. If I click on any menu, left click or right click the mouse appears. As soon as I click on the OpenShot desktop the menus and mouse pointer disappear simultaneously. I have no idea why. Fortunately I have a Windows 11 HP Laptop and in there it works perfectly, but I much prefer to work in my main desktop computer which has the Ubuntu 22.04LTS version.

Merry Christmas,John
 
 
 
-----Original Message-----

**Comment by Colorjet3** [comment]
Hello @poconotrainman You are welcome.  I am going to have someone from the DEV team take a look at this.  I am primarily a Windows user and only run different Linux flavors in a Virtual environment for testing.  This is a very small DEV team and they are in the middle of many fixes and enhancements.  I will bring their attention to this, but I don't know how quickly they will look at it.

Merry Christmas and Happy New Year to you also!

Raffi
