### ISSUE TITLE
Lack of writtten tutorial

### ISSUE THREAD

**Issue by AleSprea97** [OpenShot/openshot-qt#490]
In the program there isn't a tutorial ( yes I know  the interactive tutorial, but in not very usefull ) in pdf or txt.
I spent 15 minutes searching online for such a simple thing as split a video into two part : the command was CTRL-K, but I didn't know so I tried CTRL-C  (cut) , CTRL-S (split), s, c  etc etc.

Please insert a well done tutorial document!

P.S. I found the comand a  forum  where people are complaining about it, so I'm not the only one who have problems.

**Comment by jonoomph** [comment]
I appreciate the suggestion, and plan on building a more in-depth tutorial soon (it's already partially started in the source code under /doc/). Feel free to contribute instead of demanding. Thanks.
