### ISSUE TITLE
Just copy input file codecs to export

### ISSUE THREAD

**Issue by Ygarr** [OpenShot/openshot-qt#4900]
After cutting video - option in Export video (Audio - copy from source, Video - copy from source)
Because, for example input file 4.5 Mb after choosing suggested codecs got 40+Mb of shorter video

**Comment by JacksonRG** [comment]
@Ygarr I understand your thinking here, but what I've found from working in video editing is that isn't really possible unless you have the raw footage. Taking a piece of one file, and making it into it's own file, requires opening the video packets, reading them, and creating new ones.

You can also make sure you're not increasing the resolution or frame rate. You can see what these are on your source file by right clicking on your source file in openshot and clicking `file properties`.

Let me know if that helps.
