### ISSUE TITLE
I cannot insert any video. The project files windows stays empty. Error: Failed to establish a new c...

### ISSUE THREAD

**Issue by archer-v** [OpenShot/openshot-qt#4902]
I can't import any new video file.  The project files window stays empty.

I'm using Windows 10 64bit.
It's a new openshot installation and it had never been installed on this system before
I tried to reinstall, installed latest daily build, remove folders, turned windows firewall off, nothing changed.

Log files contains error on video file import:

11:47:28 ERROR updates: Couldn't apply 'insert' to update listener: <windows.models.files_model.FilesModel object at 0x000001955da283a0>
HTTPConnectionPool(host='127.0.0.1', port=51757): Max retries exceeded with url: /thumbnails/P2AQKML20U/1/path/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001955db28a00>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))

I found several similar cases, but they reported about proxy connection error.
https://github.com/OpenShot/openshot-qt/issues/3307

I don't use proxy, and as I understand it, here is a problem with connection to some openshot internal service. I don't know is it because the service is failed to start, or some windows network or security related issue.
I checked port listenteners with `netstat -anp` and there is no listener on 127.0.0.1:51757

Also I checked that .openshot_qt folder and thumbnails folder are writable for user and tried to start openshot as administrator. nothing changed.

System information:

- OpenShot Version: 2.6.1-dev
- libopenshot Version:  0.2.7-dev
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 23 Stepping 10, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['ru-RU', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Ежедневное обновление: Проблема все еще присутствует в ежедневном обновлении: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-dev-daily-9712-61b22218-46255e46-x86_64.exe

**Файлы журнала**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/vdjjo1wgfpv21h36hkbn7lmd6t79avqz/openshot-qt.zip) (184 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/vdjjo1wgfpv21h36hkbn7lmd6t79avqz/libopenshot.zip) (142 KB)

**Comment by Colorjet3** [comment]
Which version of Windows 10 (home, N, Pro?).  Also, which DEV version (Build #?) of OpenShot are you running (Help | About Openshot)?

**Comment by Colorjet3** [comment]
No Response!
