### ISSUE TITLE
OpenShot: Copied clips and effects

### ISSUE THREAD

**Issue by MoodsinMusic** [OpenShot/openshot-qt#4904]
Using OpenShot, when I copy a clip that includes an effect, the copied clip doesn't act as expected. The clip will show the effects of the original clip, and it will show the keyframe marks in the clip where the effects have been set, but the values showing in the property screen don't change when scrolling through time. If you try to insert new values, the clip will continue to display the effects of the original clip. What I want to do is create multiple copies, then edit to make small adjustments to each copy. Is this a bug or a feature? 

Moods In Music

ETA: The normal properties work as expected. You can edit each copied clip, and they show the property values correctly. Only effects act in the unexpected manner. This would suggest a bug rather than a feature.

**Comment by MoodsinMusic** [comment]
I tried copy and paste of the effects. They appear to copy fine, but the keyframes for the effects can't be edited in the copy. The standard properties, such as scale can be copied then edited as one would expect.

**Comment by MoodsinMusic** [comment]
So, I was going to delete the effects (color saturation and hue) from each copied clip, and then manually input the values. The problem is that it deleted the effects not only from all the clips that the effects were copied to, but it deleted the effects from the original clip that was otherwise working correctly. The standard properties (scaling, alpha) were unaffected.

**Comment by Colorjet3** [comment]
Hello @MoodsinMusic please download the latest DEV Daily Build (openshot.org/download/#daily) and confirm that the problem persists or is fixed.
