### ISSUE TITLE
PPA-Schlüssel im veralteten Schlüsselbund trusted.gpg gespeichert (/etc/apt/trusted.gpg)

### ISSUE THREAD

**Issue by rl-musik** [OpenShot/openshot-qt#4905]
**Beschreiben Sie den Fehler**

Nach Updates erscheint regelmässig die Warnung 
"W: http://ppa.launchpad.net/openshot.developers/libopenshot-daily/ubuntu/dists/jammy/InRelease: Schlüssel ist im veralteten Schlüsselbund trusted.gpg gespeichert (/etc/apt/trusted.gpg), siehe den Abschnitt MISSBILLIGUNG in apt-key(8) für Details." 

--------------------------------------------------------------------------------------

**Schritte zum Reproduzieren des Verhaltens**

1. Enfügung des PPA-Schlüssels (eventuell veraltet) zu "Anwendungspaketquellen"
2. Update mit sudo apt-get update
3. Siehe Fehlermeldung

--------------------------------------------------------------------------------------

**Erwartetes Verhalten**
Keine Fehlermeldung

--------------------------------------------------------------------------------------

**Systemdetails**
- OpenShot Version: 2.6.1
- libopenshot Version:  0.2.7
- Platform: Linux-5.15.0-47-generic-x86_64-with-glibc2.33
- Processor: 
- Machine: x86_64
- Python version: 3.9.9
- Qt5 version: 5.15.3
- PyQt5 version: 5.15.1
- Qt Detected Languages: ['de-DE']
- LANG Environment Variable: de_DE.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Not able to verify issue still exists in daily build

--------------------------------------------------------------------------------------

**Logdateien**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/ibhtztepn7tg4flkmx54m6zv8g9zs68e/openshot-qt.zip) (26 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/ibhtztepn7tg4flkmx54m6zv8g9zs68e/libopenshot.zip) (17 KB)

--------------------------------------------------------------------------------------

**Ausnahme / Stapelverfolgung**
```No stacktrace found in log files```

--------------------------------------------------------------------------------------

**Bildschirmfotos** (Optional)
![PPA-Schlüsselproblem](https://user-images.githubusercontent.com/110280475/188305532-3174d321-a237-4580-87e5-204a74c47a90.png)

**Comment by Colorjet3** [comment]
For now, try running the AppImage instead.  Go to openshot.org/download.  Click on "Daily Builds".  Download the latest DEV Daily Build available.

Let us know if this helped resolve your issue.

**Comment by Colorjet3** [comment]
No response from user.
