### ISSUE TITLE
openshot does not launch 

### ISSUE THREAD

**Issue by ajRiverav** [OpenShot/openshot-qt#4906]
**Describe the bug:**
Upon launching openshot, it bounces in the taskbar and then disappears. 

**Steps to reproduce the behavior:**
Launch openshot and observed described bug. 

**System Details:**
- OpenShot Version: OpenShot-v2.6.1-x86_64
- Operating System / Distro: macOS Monterrey 12.5.1 (21G83)

**Comment by tsugabloom** [comment]
Use the daily build: OpenShot-v2.6.1-dev-daily-9733-cfca6e77-46255e46-x86_64.dmg | Sept. 5, 2022, 10:27 a.m. at https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.6.1-dev-daily-9733-cfca6e77-46255e46-x86_64.dmg
