### ISSUE TITLE
OpenShot: Slicing creates gap

### ISSUE THREAD

**Issue by MoodsinMusic** [OpenShot/openshot-qt#4907]
When slicing a track keeping both sides, a single blank frame results in between the two new clips. Also, the right-hand clip has its keyframes shifted to the left by one frame. If you then slide the clip to the right by one frame to reposition the keyframes, the gap between the clips will then be two frames.

**Comment by Colorjet3** [comment]
This has been fixed in the latest DEV Daily Build.  Go to openshot.org/download, click on Daily Builds and download the latest available for your operating system.  If running Linux, download the latest AppImage.

**Comment by MoodsinMusic** [comment]
Great! It seems to be working! Thanks!

**Comment by Colorjet3** [comment]
Great and thank you for the feedback.
