### ISSUE TITLE
Openshot-qt 2.2.0 and blender 2.78a on D drive

### ISSUE THREAD

**Issue by 07pepa** [OpenShot/openshot-qt#491]
I cannot use animated title even I have instaled and path to it is corect (even terminal winow flashesh.

I suspect that problem is i am using everything (exept windows, and few programs) on D drive not C....
and no i cannot move it because my tiny ssd is just enought for windows ( 24GB)

**Comment by mixedbredie** [comment]
Do you get the same errors as reported in #487?

It shouldn't matter where Blender and Inkscape are installed as long as the path is correct.

There are some fixes that need to be applied to the Blender scripts in order for them to work.  If you search the issues log you'll find the solution or check pull request #398

**Comment by 07pepa** [comment]
@mixedbredie  Yes I do ( however Czech translation is Bad! does not say wich error it is causing it)

I will try your fix and report back (bcs i  am programator too :) )

**Comment by 07pepa** [comment]
@mixedbredie It fix most of it.... but there is no prewiev (refresh buton and slider seem to do nothing)

and some of titles crashes same error  (colour titles, disolving/exploding text, glass slider, frame picture( this one is special after i tried it nothing else work aftervards until restart of program))
everything else vork

btw.  i just replaced every ocurance of text_object.align to text_object.align_x   and i gues it should fix it but it does not do it for 100%

**Comment by jonoomph** [comment]
Please test again with the latest daily build of OpenShot. I've merged in changes to the text alignment, and updated the minimum version compatibility to 2.78. I've tested all animation on Linux, Mac, and Windows with Blender 2.78 and everything works great.

Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot. _It might take a couple hours for the latest version to appear._

If you have other issues, please file additional bugs for each one. Thanks!

**Comment by 07pepa** [comment]
will do in aprox 2 days... btw it there is a log or error output... i can use it ( as programer :D )

**Comment by 07pepa** [comment]
confirming fixed !
