### ISSUE TITLE
Openshot crashes immediately if no audio device is enabled (Windows 10)

### ISSUE THREAD

**Issue by jrchampi** [OpenShot/openshot-qt#4910]
**Describe the bug:**

Sometimes I do not notice that Windows 10 is showing Speaker icon with Red X (flyover says 'no audio device is enabled') prior to opening Openshot. 
If I attempt to start Openshot (by double clicking on an .osp file) in this condition, It opens a UI briefly but within a second or so, it crashes with no explanation...  It is confusing and not obvious that all that is needed is an enabled audio device.
(Reported this once on build 9432 and on 9481... but still exists on build 9733. )

This problem shows up as 'Openshot crashes upon start'.   It is not obvious that an audio device is the problem.

**Steps to reproduce the behavior:**
1. Go to windows 10 sound settings and disable the current sound device (Red X shows up on tray speaker icon).
2. Double click on an existing Openshot .osp file
3. Openshot crashes.
4. Repeat 1-3 to see that this is repeatable.
5.  Go to windows 10 sound settings and ENABLE the current sound device (speaker icon appears normal).
6. Double click on an existing Openshot .osp file
7. Openshot opens normally without failure.

**Expected behavior:**

1) Openshot should check to see if an audio device is enabled and show  an error message indicating 'no audio device is enabled' before closing.  Then the user knows to go get Windows 10 configured properly.

**System Details:**
- OpenShot Version [2.6.1 daily build 9733 64bit]
- Operating System / Distro: [Windows 10]

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.
--------------------------------------------------------------------
Failed to start logs: (audio device disabled)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/9532299/openshot-qt.log)

[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/9532304/libopenshot.log)

------------------------------------------------------------------------
Normal start logs (with audio device enabled)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/9532323/openshot-qt.log)

[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/9532324/libopenshot.log)

**Comment by Colorjet3** [comment]
Hello @jrchampi Please got to openshot.org/download/#daily v3.0.0 and download the latest DEV Daily Build.  Install it and give it a try.  Let us know if the problem persists.

**Comment by jrchampi** [comment]
Tested this with OpenShot-v3.0.0-daily-10947 on Windows 10 Pro (21H2) and nice error message pops up that tells the user how to recover.   Fixed
Thanks!
