### ISSUE TITLE
Zoom into picture, in the exported video is black

### ISSUE THREAD

**Issue by schwares** [OpenShot/openshot-qt#4912]
**Describe the bug:**
If I have a picture and zoom in into the timeline then in the exported video there is only a black window.
In the preview in openshot it looks fine.
If I use the same picture without the zoom it works fine.

**Steps to reproduce the behavior:**
1. Put a picture in the timeline
2. Create a zoom into the picture. 
3. Change in a late time of the picture the 'location x and y' to the point you would like to zoom in
4. Increase the 'Scale x and y'
5. export video
6. open the video - it is black

**Expected behavior:**
All should be exported.

**System Details:**
- OpenShot Version [2.6.1]: {{ OpenShot-v2.6.1-dev-daily-9733-cfca6e77-46255e46 }}
- Operating System / Distro: [ Linux-5.15.0-47-generic-x86_64-with-Ubuntu-22.04-jammy ]

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/9537267/openshot-qt.log)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/9537270/libopenshot.log)

**Comment by schwares** [comment]
I installed also Openshot in Windows 10 and had the same issue.

**Comment by Colorjet3** [comment]
Hello @schwares I just tested this with v3.0.0 build #10947 and I could not reproduce your issue.  Please go to openshot.org/download/#daily and download and install the latest DEV Daily Build and give it a try.
