### ISSUE TITLE
Doesn't start on LinuxMint.

### ISSUE THREAD

**Issue by caralu74** [OpenShot/openshot-qt#4913]
$ openshot-qt
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
         app:INFO ------------------------------------------------
         app:INFO             Tue Sep  6 13:52:29 2022            
         app:INFO               Starting new session              
         app:INFO ------------------------------------------------
         app:INFO             OpenShot (version 2.5.1)            
         app:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.5.1
         app:INFO libopenshot version: 0.2.5
         app:INFO platform: Linux-5.15.0-43-generic-x86_64-with-glibc2.35
         app:INFO processor: x86_64
         app:INFO machine: x86_64
         app:INFO python version: 3.10.4
         app:INFO qt5 version: 5.15.3
         app:INFO pyqt5 version: 5.15.6
     metrics:ERROR Error determining OS version in metrics.py
    language:INFO Qt Detected Languages: ['es-CO', 'es']
    language:INFO LANG Environment Variable: es_CO.UTF-8
    language:INFO LOCALE Environment Variable: 
    language:INFO OpenShot Preference Language: Default
project_data:INFO Setting default profile to HD 720p 30 fps
ZmqLogger::Connection - Error binding to tcp://*:5556. Switching to an available port.
ZmqLogger::Connection - Error binding to tcp://*:5556. Switching to an available port.
         app:INFO Setting font to Cantarell
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
         app:INFO Setting custom dark theme
QMainWindow::addDockWidget: invalid 'area' argument
     ui_util:INFO Initializing UI for MainWindow
     version:ERROR Failed to get version from: http://www.openshot.org/version/json/
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "/usr/bin/openshot-qt", line 33, in <module>
    sys.exit(load_entry_point('openshot-qt==2.5.1', 'gui_scripts', 'openshot-qt')())
  File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 97, in main
    app = OpenShotApp(argv)
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 219, in __init__
    self.window = MainWindow(mode)
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/main_window.py", line 2521, in __init__
    self.timeline = TimelineWebView(self)
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/views/timeline_webview.py", line 3000, in __init__
    self.cache_renderer.setInterval(0.5 * 1000)
TypeError: setInterval(self, int): argument 1 has unexpected type 'float'

^C      logger:ERROR Exception ignored in:
      logger:ERROR <module 'threading' from '/usr/lib/python3.10/threading.py'>
      logger:ERROR Traceback (most recent call last):
      logger:ERROR   File "/usr/lib/python3.10/threading.py", line 1560, in _shutdown
      logger:ERROR lock.acquire()
      logger:ERROR KeyboardInterrupt
      logger:ERROR :
         app:INFO             OpenShot's session ended            
         app:INFO             Tue Sep  6 13:53:34 2022            
         app:INFO ================================================

**Comment by AXFOX** [comment]
Me too.....
Try use daily builds,26.1 Appimage and openshot-qt.deb  can't work normaly in my Mint21 laptop,but Daily Build was OK.
![image](https://user-images.githubusercontent.com/57279704/198873181-c6e70fea-8327-4614-a071-5ad0e3afc14f.png)

<pre>         app:INFO ------------------------------------------------
         app:INFO             Sun Oct 30 18:03:58 2022            
         app:INFO               Starting new session              
         app:INFO ------------------------------------------------
         app:INFO             OpenShot (version 2.5.1)            
         app:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.5.1
         app:INFO libopenshot version: 0.2.5
         app:INFO platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.35
         app:INFO processor: x86_64
         app:INFO machine: x86_64
         app:INFO python version: 3.10.6
         app:INFO qt5 version: 5.15.3
         app:INFO pyqt5 version: 5.15.6
     metrics:ERROR Error determining OS version in metrics.py
    language:INFO Qt Detected Languages: [&apos;zh-CN&apos;, &apos;zh&apos;]
    language:INFO LANG Environment Variable: zh_CN.UTF-8
    language:INFO LOCALE Environment Variable: 
    language:INFO OpenShot Preference Language: Default
project_data:INFO Setting default profile to HD 720p 30 fps
         app:INFO Setting font to Cantarell
         app:INFO Setting custom dark theme
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
     ui_util:INFO Initializing UI for MainWindow
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File &quot;/usr/bin/openshot-qt&quot;, line 33, in &lt;module&gt;
    sys.exit(load_entry_point(&apos;openshot-qt==2.5.1&apos;, &apos;gui_scripts&apos;, &apos;openshot-qt&apos;)())
  File &quot;/usr/lib/python3/dist-packages/openshot_qt/launch.py&quot;, line 97, in main
    app = OpenShotApp(argv)
  File &quot;/usr/lib/python3/dist-packages/openshot_qt/classes/app.py&quot;, line 219, in __init__
    self.window = MainWindow(mode)
  File &quot;/usr/lib/python3/dist-packages/openshot_qt/windows/main_window.py&quot;, line 2521, in __init__
    self.timeline = TimelineWebView(self)
  File &quot;/usr/lib/python3/dist-packages/openshot_qt/windows/views/timeline_webview.py&quot;, line 3000, in __init__
    self.cache_renderer.setInterval(0.5 * 1000)
TypeError: setInterval(self, int): argument 1 has unexpected type &apos;float&apos;
     version:INFO Found current version: {&quot;trans_rate_unstable&quot;: 0.001, &quot;error_rate_unstable&quot;: 0.05, &quot;openshot_version&quot;: &quot;2.6.1&quot;, &quot;trans_rate_stable&quot;: 0.01, &quot;error_rate_stable&quot;: 0.16}
</pre>

And in 26.1AppImage ，I can launch it but I cant add video to time-base.
![198873431-6b87da4a-312c-46bc-a891-ac4584f84bb9](https://user-images.githubusercontent.com/57279704/198874945-aa0dcd2d-d4e2-4a29-a449-5aed4bebc47b.png)

As you see,time-base was not show for user.

**Comment by Colorjet3** [comment]
Please go to openshot.org and download v3.0.0 and give it a try.

**Comment by caralu74** [comment]
Thank you so much! I will update my system and try, or even better enjoy the editor.
