### ISSUE TITLE
Crashes when loading video

### ISSUE THREAD

**Issue by slwslw1** [OpenShot/openshot-qt#4914]
**Describe the bug**
This the second time I have had to do this - fix your github handshake process, please
-------------------------------
Error and crash when loading video

**Steps to reproduce the behavior:**
1. Go to Add File (+)
2. Click on folder
3. Scroll down to file
4. crashes and looks for solutions

**Expected behavior**
supposed to add video to files being used in open shot

**System Details**
- OpenShot Version: 2.6.1
- libopenshot Version:  0.2.7
- Platform: Windows-7-6.1.7601-SP1
- Processor: Intel64 Family 6 Model 26 Stepping 4, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Skipped this step

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/xlj34q2j445hjs9jhzrk5t2y7f92apal/openshot-qt.zip) (5 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
Please download v3.0.0 from openshot.org and see if that resolves your issue.
