### ISSUE TITLE
razor tool causes newly created clip on right side to shorten

### ISSUE THREAD

**Issue by antiochtech** [OpenShot/openshot-qt#4915]
**Describe the bug:**
razor tool causes newly created clip on right side to shorten

**Steps to reproduce the behavior:**
1. add video to timeline
2. click razor tool
3. click on desired spot of clip in timeline
4. newly minted clip on right side is shortened.

**Expected behavior:**
clip should be cut where indicated with both halves adding up to the same length as the original.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 2.6.1
- Operating System / Distro: ubuntu 18.04

**Screenshots:** (Optional)

![Screenshot from 2022-09-13 11-33-19](https://user-images.githubusercontent.com/59234093/189957906-d3c8e7b0-d6f5-488b-a296-bcc6f77be41a.png)
![Screenshot from 2022-09-13 11-32-23](https://user-images.githubusercontent.com/59234093/189957928-37b9029d-7377-4d07-a9ed-a0c2f2284c79.png)

**Comment by antiochtech** [comment]
just noticed that it only happens when the source video is shot in slow motion (in this case, a frame rate of 240).

**Comment by Colorjet3** [comment]
There was a fix release to splitting and splicing actions in the latest DEV Daily Build.  Please go to openshot.org/download and click on Daily Builds.  Download the latest available Daily Build (AppImage) and let us know if this resolved your issue.
