### ISSUE TITLE
I moved the transform in the preview pan to pan/zoom, creating hundreds of keyframes, how do I delete the bad ones ? 

### ISSUE THREAD

**Issue by shodanx2** [OpenShot/openshot-qt#4917]
Hi,

So I have a clip I need to center and crop, while the video was playing I was moving it around and resizing it.
This created a new keyframe on every mouse movement event.

When I figured where I needed my clip to be on screen, I tried going back and adding the right location and scale at the beginning of the scene. But this does nothing as the next keyframe will override these values.

I've been searching and searching for a way to efficiently remove key frame but it seems the only way to do this is to zoom in on the timeline to see each and every keyframe 

![image](https://user-images.githubusercontent.com/10621885/190110359-12b05901-35f4-4504-99a8-3b3f465e4c28.png)

Then for each one, in the properties pane, find each property that is modified by this keyframe, right click it and choose delete keyframe. When you have deleted all of them that one keyframe will be deleted. 

Now you have to repeat this step for the hundreds more time the mouse moved ? 

Surely there is a better way to mass delete them ?

The only thing I found was right clicking on the clip and click animation -> no animation

But this appears to delete every last one of them.  So if you make a mistake, you have to start over because there is no edit, only delete all. 

Also doing this, will override the previously existing location and scale keyframe at the beginning of the clip to the default values.  And to restore it you need to somehow place the cursor/playhead on the very first frame of the clip, and then manually reset all the keyframe values to that of the frame before.

**Comment by Colorjet3** [comment]
Unfortunately there is not a better way of doing that.  That is one of the downsides of animating while previewing/playing. When you have so many keyframes entered then trying to figure out which is which.

**Comment by shodanx2** [comment]
Could there be a way, in the future, to delete all keyframes from a clip, or maybe delete all keyframe between time stamp A and time stamp B ? Or better yet, since the keyframes are visible on the timeline, maybe a keyframe delete tool that you just drag over a portion of the timeline which you want to delete all keyframes from ?

Is there a way to input commands into openshot from the command line, from a scripting language like vbscript ? Maybe I could list all keyframe and then make a script to delete them by reference number ?

**Comment by Colorjet3** [comment]
Hi @shodanx2 I am not a developer.  I am going to ask one of the DEV team to look at your proposal/suggestion and have them respond to you.

**Comment by shodanx2** [comment]
Why was this closed ?
Is there a tool to efficiently remove excess keyframes added in 3.0.0 ?

**Comment by Colorjet3** [comment]
Hello @shodanx2 No solution at this time.  I just pinged the lead developer to take a look at this.  We'll see what his response is when he gets to it.

**Comment by jonoomph** [comment]
Yes, this is a great idea of course, to provide a way of selecting a range of keyframes, and either "moving them" or "deleting them". However, a work-around would be to leverage the undo/redo history, and back-up to the point before you made all these keyframes... if possible. A more technical work-around would be to write a quick programming script, to parse the *.JSON project file, and remove all the keyframes objects for this clip in the range you are interested in. This sounds complex, but would probably take less than 15 minutes to create. Just a thought, but of course, back to the original point, I would love to incorporate an easy way to do this inside OpenShot. 👍

**Comment by shodanx2** [comment]
I imagine in it's most basic form it would be a new tool pane

You would supply

reference to element on timeline
operation to perform (delete, set value,  add/subtract value, maybe multiply and other funkier operations ?)
range of affected keyframes (beginning and end timestamp(relative, absolute timestamps ?), or maybe if the keyframe elements have index numbers ?)
Specific keyframe element to perform operation
Value to apply

So example operation could be like

This would set the x/y scale to 0.56 on all keyframes, presumably only keyframe that change this value
Element : video - myfile.mp4
operation : set value
range : ALL
element : scale x, scale y
value : 0.56

This would clear x/y location and scale from all keyframes between 0:45 - 2:50 of the currently selected element 

Element : "currently selected element"
operation : delete
range : 0:45 - 2:50
element : location x, location y, scale x, scale y
value : (blank)

This would increase location x for all keyframe elements that change this value between the timestamps. I imagine the timestamps would be relative to the element's start and not absolute timestamp on the timeline

Element : "currently selected element"
operation : addition
range : 0:45 - 2:50
element : location x
value : 0.055

The keyframe system is very powerful, but also crippled by its user interface.

Perhaps if there was a console where you could type up commands to edit the keyframes, kind of like VBA in excel, that would be awesome !

**Comment by Colorjet3** [comment]
@shodanx2 and @jonoomph I have created this Trello:  https://trello.com/c/dJab9QU3/106-keyframes-how-to-delete-bad-ones for future enhancement.

@jonoomph, due to lots of detail I just inserted the link of this Git ticket into the Trello card.  You have a better understanding of this issue and how to write it up when the time comes to work on it.
