### ISSUE TITLE
I have Openshot  2,2 installed but am using the oldee 1.34    @.2 opens andis running but is not visable on the desk top. I tried deleting it and reinstall through the lates PPA but still does not show on desktop. I know it is running as when I shut down my Machine I get a small window  with as may as 5 or 5 instances of Openshot.  Thanks for any help. Dougot

### ISSUE THREAD

**Issue by douglaspollard** [OpenShot/openshot-qt#492]

**Comment by mixedbredie** [comment]
It might be worth reformatting your issue and giving some more information about your system and someone may be able to help:  

- What operating system are you using?
- What error messages are you getting?
- can you start it from the command line?
- which PPA are you using?

**Comment by douglaspollard** [comment]
I am using Ubuntu Mint. Ia m getting no error message open-shot just does not appear on screen but appears to be in the back ground when I shut down. I tried to open in camand line using "Openshot" I am getting no such command error message.   I am using openshot xenial main  Thanks  Doug

**Comment by douglaspollard** [comment]
That is Ubuntu Mint 16.10

**Comment by jonoomph** [comment]
Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot. _It might take a couple hours for the latest version to appear._ Try the AppImage format, and reopen if you still have issues. Thanks.
