### ISSUE TITLE
Is there any stable PPA that can be used if not none when you're on Ubuntu 22.04 jammy ?

### ISSUE THREAD

**Issue by rl-musik** [OpenShot/openshot-qt#4921]
### Looking for a stable PPA for OpenShot Video Editor Version 2.6.1 with libopenshot 0.2.7 in Linux Mint 21 Vanessa on Ubuntu 22.04 jammy 

**Question: Is there any stable PPA that can be used 
(although the version is also working without any PPA) on Ubuntu 22.04 jammy ?**

Trying the following order in a terminal 

sudo add-apt-repository ppa:openshot.developers/libopenshot-daily
**terminal says 
"These packages are only intended for testers of OpenShot 2.0, as the source code can be highly unstable"** 

trying with

sudo add-apt-repository ppa:openshot.developers/ppa
**terminal says 
"PPA kann nicht hinzugefügt werden: »'Dieses PPA unterstützt jammy nicht'«."**

----------------------------

 🅢🅞 ​ 🅦🅗🅐🅣 ​ ? ​ 🙁 ​

**Comment by esteinmann** [comment]
Edit: sorry I misunderstood your question. Thought you wanted to get the daily builds but it's stated clearly in the title you are looking for the stable version. Don't think there is a PPA for Jammy then and the only way for now to get a working stable version on Jammy is downloading the AppImage?

**Comment by rl-musik** [comment]
Although like I told the OpenShot Video Editor i'm using in my system is working quite fine, we only have to have patience in between, a new AppImage would be also nice, 😁.

**Comment by esteinmann** [comment]
> Although like I told the OpenShot Video Editor i'm using in my system is working quite fine, we only have to have patience in between, a new AppImage would be also nice, grin.

Just to make sure we are on the same page: which version are you using now on your system? Jammy seems to have version 2.5.1 in the repos.

There is a 2.6.1 stable AppImage available on the downloads page on the OpenShot website and also daily builds that (and this confused me at first) have version 2.6.1 but with the -dev suffix so 2.6.1-dev. My point is that you can use the latest stable on Jammy (2.6.1 instead of the 2.5.1 from the official Jammy repos) if you want, but you have to download it manually instead of installing from PPA using APT.

**Comment by rl-musik** [comment]
Dont know which version I have, inxi says: 
Distro: Linux Mint 21 Vanessa
Base: Ubuntu 22.04 jammy

My PPA is: deb http://ppa.launchpad.net/ubuntustudio-ppa/backports/ubuntu jammy main

**Comment by jonoomph** [comment]
Our AppImages are available after every single bug fix: https://openshot.org/download/#daily. They support all the latest distros, and are easy to download and run. I highly recommend taking a look at them. I will also double check our 2 PPAs we maintain: https://www.openshot.org/ppa/, and be sure the latest Ubuntu distros are supported (sometimes things break on the PPAs, and they fail to get much attention). I'll update this ticket shortly.

**Comment by jonoomph** [comment]
Our daily PPA has now been updated for Kinetic, Jammy, Focal, and Bionic

OpenShot Daily PPA
---
sudo add-apt-repository ppa:openshot.developers/libopenshot-daily
sudo apt update
sudo apt install openshot-qt python3-openshot

**Comment by rl-musik** [comment]
▲  Thanks  ▲
