### ISSUE TITLE
Video stuck on preview/export even there's nothing on that track

### ISSUE THREAD

**Issue by senbonn** [OpenShot/openshot-qt#4922]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 2.6.1
- libopenshot Version:  0.2.7
- Platform: Windows-10-10.0.22000
- Processor: Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Skipped this step

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/q3z5hldbxhoew7dmpe3umrd5rt2cay0x/openshot-qt.zip) (483 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

![image](https://user-images.githubusercontent.com/104094737/190915397-84a361da-00c8-469e-879f-59849f21a9bd.png)

**Comment by JacksonRG** [comment]
Did this last very long, or did restarting the program help at all?
