### ISSUE TITLE
OpenShot locks up doing almost anything

### ISSUE THREAD

**Issue by JustinWebDev** [OpenShot/openshot-qt#4923]
**Describe the bug**
OpenShot locks up doing almost anything.  I can't even test out this app because it is so flaky.

**Steps to reproduce the behavior:**
1. add a TS video (mine is 30min, 704x480)
2. drag the video to a timeline
3. play the preview
4. OpenShot locks up with the CPU cycling ('busy' forever) and I have to kill it; same for showing waveform

**Expected behavior**
The app should not lock up.

**System Details**
- OpenShot Version: 2.6.1
- libopenshot Version:  0.2.7
- Platform: Windows-10-10.0.19041
- Processor: AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Skipped this step

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/psdsf797fae6ypq19jxkvm8nlk01jvwx/openshot-qt.zip) (10 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/9595539/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/9595540/openshot-qt.log)

**Comment by JacksonRG** [comment]
@JustinWebDev Is openshot's performance any better in the daily build? You can download it [here](https://www.openshot.org/download/). There are a lot of improvements in the daily build.

Also are you running the app as an administrator? If you do, does that change anything? That could be related to what permissions the app was installed with.

**Comment by JustinWebDev** [comment]
My OS account is an admin account.  Are you saying I should also run the app 'as administrator'?  And what do permissions have to do with this issue?  Shouldn't OpenShot work with whatever permissions it arranged during install?  I don't understand the logic at all about permissions.
