### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Cw1rl** [OpenShot/openshot-qt#4924]
This probably isn't exactly a report but I accidently clicked something and made the part where I enter the files removed and aswell where it shows the video. I don't know how to make my openshot normal with all the things again help me
![Screenshot (84)](https://user-images.githubusercontent.com/114032451/191378045-36261b5e-292e-404f-9a91-838d1b7cb667.png)

**Comment by JacksonRG** [comment]
In the top right there's a button that says `View`. Under that you can click `Views` then `Simple View` to return to the default layout.

**Comment by Colorjet3** [comment]
A solution has been provided.
