### ISSUE TITLE
No timeline openhost 2.6.1

### ISSUE THREAD

**Issue by doguibnu** [OpenShot/openshot-qt#4927]
Hello!
How are you?

I downloaded the last version AppImage Openshot 2.6.1 version. When open up the timeline does not appear (stay invisible) 

Operating System : Linux Mint 21 Cinnamon
kernel: 5.15.0-48-generic
Ram: 7.2 GiB
video: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller

Follow the screenshots 
![openshot-v253-59](https://user-images.githubusercontent.com/38897311/191879243-5fec5faf-4b6e-42ae-84cc-1aaf7f626d95.png)

![opshot-v1-28](https://user-images.githubusercontent.com/38897311/191879271-2df86729-d702-4624-b390-5e938e84ad11.png)

Thank you!

Douglas

**Comment by joelgrus** [comment]
I am having the same problem on Ubuntu 22.04, same Openshot release version

**Comment by esteinmann** [comment]
This should be fixed in the latest daily, see: https://github.com/OpenShot/openshot-qt/issues/4865
