### ISSUE TITLE
Hardware acceleration is not enabled

### ISSUE THREAD

**Issue by JustinWebDev** [OpenShot/openshot-qt#4928]
**Describe the bug:**
Hardware acceleration is not enabled in Preferences > Performance.
I've tried with an NVIDIA Quadro P400 and a RTX A5000 GPU.

**Steps to reproduce the behavior:**
1. open Preferences
2. Click on Performance tab
3. observe a GPU is not select or selectable for any of the 'hardware' options

**Expected behavior:**
Hardware encoding/decoding should be enabled for eligible hardware.

**System Details:**
- OpenShot Version 2.6.1
- Operating System / Distro: Windows 10, 11 x64

**Comment by Colorjet3** [comment]
Currently, hardware acceleration in Windows is not available.  This is a documented request and will be available in a future release (ETA = TBD).

**Comment by JustinWebDev** [comment]
Okay.  If there is an update in the near-term, it would be helpful to hide the UI or disable with a msg until it is enabled.
