### ISSUE TITLE
Audio issue

### ISSUE THREAD

**Issue by Cw1rl** [OpenShot/openshot-qt#4929]
**Describe the bug:**
Does not capture any audio in the files I put even before exporting.
**Steps to reproduce the behavior:**
1. Go to 'open shot and a add a file'
2. Click on 'trim or drag file into one of the video bar'
3. Scroll down to 'the play button'
4. See error Audio will not come out of clips

**Expected behavior:**
i expected the audio from the files to come out
**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

*

**Comment by Colorjet3** [comment]
Please provide the following so we can assist you better:
1.  What operating system are you running and what version (Windows, Linux, etc.)?
2.  What version of OpenShot are you running (Help | About Openshot)?
3. What type of a file is your video file (.mp4, .mov, etc.)?
4.  Does your video file play outside of OpenShot?
5.  What type of an audio output device are you playing to (speakers, headphones, etc.)?
