### ISSUE TITLE
Openshot Video Editor crashes when I export a video with YouTube format

### ISSUE THREAD

**Issue by AlanReviews** [OpenShot/openshot-qt#4935]
**Describe the bug:**
I am trying to export a YouTube video with a YouTube format. The profile is 1080p 30 FPS. After selecting the YouTube format, Openshot Video editor closes. I don't know why.

**Steps to reproduce the behavior:**
1. Select the video project you want to export.
2. Select export video or use the shortcut Ctrl + E
3. Select the format to be web. Select the target to be YouTube-HD. The video profile and quality can be any setting.
4. Press export video, then ok.

**Expected behavior:**
Openshot video editor creates the video. The video gets exported succesfully.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 2.6.1
- Operating System / Distro: Pop OS 22.04

**Log Files:**
[openshot qt.log](https://github.com/OpenShot/openshot-qt/files/9690978/openshot.qt.log)

**Screenshots:** (Optional)
![Screenshot from 2022-10-01 14-49-00](https://user-images.githubusercontent.com/54216387/193423940-9ff165a0-6c0b-4d05-870e-187741eb410a.png)

**Comment by Colorjet3** [comment]
Please download the latest DEV Daily Build AppImage and give it a try.  Let us know the result.

**Comment by AlanReviews** [comment]
I found a workaround to create videos in an mp4 format by exporting the project.

**Comment by Colorjet3** [comment]
Thank you for the update @AlanReviews and glad you found a workaround.  Just as an FYI, v3.0.0 has been release to production.  In the Export process there are now 4 Youtube settings you can pick from (YouTube HD, YouTube HD (2k), Youtube HD (4k), and Youtube Standar).

Best of luck with your projects.
