### ISSUE TITLE
Stutter in 4K exported video

### ISSUE THREAD

**Issue by Trainax** [OpenShot/openshot-qt#4937]
Hello everyone. I recently shot a video in 4K 30fps using my phone. After editing it I exported it with the `4K UHD 2160p 30 fps` profile however the exported video is not fluid and it micro-stutters. I don't know how to properly describe this, so I uploaded 2 videos to show it to you. The first is the original clip uploaded from my phone to YouTube using the YouTube Android app, the second one is the same clip, imported into OpenShot and exported with 80 Mbit/s bitrate without touching it. The profile used is `4K UHD 2160p 30 fps` which matches the original resolution and framerate.
- [Original video](https://youtu.be/kaPf8HsKllM)
- [The same video, imported and exported with OpenShot](https://youtu.be/LhOBJb5DDEM)

My pc specs:
- OS: Windows 11 x64
- OpenShot version: 2.6.1
- CPU: i7 8700k
- RAM: 16GB DDR4

Also, on a side note: 7 months ago I opened a PR (#4723) but I haven't received a reply yet. Could you also take a look at it?

Thank you!

**Comment by Colorjet3** [comment]
Please go to openshot.org/download and download v3.0.0 and give it a try.

**Comment by Trainax** [comment]
> Please go to openshot.org/download and download v3.0.0 and give it a try.

Version 3.0.0 seems to have fixed the problem
