### ISSUE TITLE
ARM build for Apple silicon Macs

### ISSUE THREAD

**Issue by dploeger** [OpenShot/openshot-qt#4938]
**Describe the new feature:**
A build suitable for Apple silicon macs would be great, preferably a universal binary which works on Intel as well as on the ARM architecture.

**Describe alternatives you have considered:**
The current version only runs on Intel using the Rosetta 2 emulator layer, which reduces OpenShot performance on Apple silicon mac. Additionally, Rosetta will be deprecated in a future macOS release making OpenShot unavailable in the future.

**Comment by kfhoward** [comment]
I would like to second this request.  Even emulating Intel on my Macbook is a bit faster than Windows, but a native ARM build would do even better.  As original poster says too, at some point, Apple will no longer be supportive of this emulation.
