### ISSUE TITLE
unable to uninstall. Error message: "The following packages have unmet dependencies"

### ISSUE THREAD

**Issue by Walteriot** [OpenShot/openshot-qt#4939]
**Describe the bug:**
Unable to uninstall. Error message: "The following packages have unmet dependencies" without further details.

**Steps to reproduce the behavior:**
1. Go to Ubunto Software
2. Search OpenShot
3. Click on trash icon to uninstall
4. See error "No se puede quitar OpenShot Video Editor: The following packages have unmet dependencies: " without further details.

**Expected behavior:**

**System Details:**
- OpenShot Version 2.5.1+dfsg1
- Operating System / Distro: Ubuntu 22.04.1 LTS

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
If this is still an issue please reopen the ticket.
