### ISSUE TITLE
Titles

### ISSUE THREAD

**Issue by Espresso911** [OpenShot/openshot-qt#4942]
I am at a total loss I cannot get titles to work. When I click on titles the program just closes it self. I have tried to create a error log file bur=t thta doesn't work either. I have noticed thta there have been others with the same problem in the past but i haven't seen any solutions......are there any? I find the program is very tempermental!

**Comment by Colorjet3** [comment]
Please tell us what version of OpenShot you are running (Help | About Openshot).  Make a not if you see 2.6.1-Release-Candidate.  Also, what operating system are you running (windows, linux, mac?).
