### ISSUE TITLE
Timeline not displayed on ubuntu

### ISSUE THREAD

**Issue by benmouh** [OpenShot/openshot-qt#4943]
**Describe the bug:**
Timeline cannot be shown when i add files to the timeline, I tryed using two version of the software including the most recent one.
**Steps to reproduce the behavior:**
1. Go to 'add new file'
2. Click on 'try to drag and drop the file in timeline or click left and add to timeline'
3. Scroll down to 'the file is not added but you can play the file'

**Expected behavior:**
When I add the file to the timeline it should be visible

**System Details:**
- OpenShot Version [ 2.6.0] and [ 2.6.1]
- Operating System / Distro: [5.15.0-50-generic #56-Ubuntu SMP Tue Sep 20 13:23:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
]
**Screenshots:** (Optional)
![Capture d’écran du 2022-10-12 21-52-39](https://user-images.githubusercontent.com/3764614/195435191-bd2fa22d-94a9-4a59-ad51-57050f97de73.png)

**Comment by samwilson** [comment]
I was getting this issue, and (as mentioned [here](https://github.com/OpenShot/openshot-qt/issues/4676#issuecomment-1103415589)) solved it by adding `--no-sandbox` when launching Openshot, e.g.:

    $ ./OpenShot-v2.6.1-x86_64.AppImage --no-sandbox

**Comment by Colorjet3** [comment]
Thank you @samwilson for that solution.  You can also download the latest DEV Daily Build as this has been fixed.  Go to openshot.org/download.  click on Daily Builds.  download the latest DEV version available (AppImage).
