### ISSUE TITLE
Windows 10 no NVENC 

### ISSUE THREAD

**Issue by nearinthel** [OpenShot/openshot-qt#4946]
**Describa el problema**
I have a RTX 2060 in Windows 10, and NVENC codec does not appear, just CPU and QSV (I don't know why cause I'm using a Ryzen 2600).
 

**Comportamiento esperado**
NVENC or any hardware acceleration on the list (that is not from Intel)

**Detalles del sistema**
- OpenShot Version: 2.6.1-dev
- libopenshot Version:  0.2.8-dev
- Platform: Windows-10-10.0.19041
- Processor: AMD64 Family 23 Model 8 Stepping 2, AuthenticAMD
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['es-MX', 'es-ES', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Compilación diaria: Todavía existe el problema verificado en la compilación diaria:http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-dev-daily-9926-9954b53b-46255e46-x86_64.exe

**Archivos de registro**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/l62uxfk9i08s0jnlo9h0zkdmhnm8qnrh/openshot-qt.zip) (593 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/l62uxfk9i08s0jnlo9h0zkdmhnm8qnrh/libopenshot.zip) (0 KB)

**Excepción / Rastreo de pila**
```No stacktrace found in log files```
![Captura de pantalla (43)](https://user-images.githubusercontent.com/65672854/195948630-58ed40dd-37af-47a5-8a88-960d6f0b9cba.png)
![Captura de pantalla (42)](https://user-images.githubusercontent.com/65672854/195948640-2577a361-93c6-4a60-9d72-a820c9a5d47d.png)

**Comment by Colorjet3** [comment]
Currently hardware acceleration is not working in Windows 10 or Windows 11, or any Windows that I am aware of.  There is a an enhancement request asking for this feature/function be enabled.  ETA = TBD
