### ISSUE TITLE
Constant crashes

### ISSUE THREAD

**Issue by macleanflood** [OpenShot/openshot-qt#4948]
**Describe the bug:**
Last several weeks of Openshot daily builds have lead to more and increased crashes. No errors. Program just closes. Have deleted openshot.qt folder. Have updated video card drivers. Have run sfc /scannow.

**Steps to reproduce the behavior:**
1. Open Openshot.
2. Scroll over to about 20m in on my video where I last left off editing.
3. Click on the timeline to move the shuttle to where I left off editing.
4. Click Play. Program immediately crashes and closes.

Prior to the last daily build I could get between 5-10 clicks/edits/cuts before program would close and have been limping by editing videos by click, save, click saving and it's increased my editing time 400 percent.

If I open Openshot and do not open any files or click anything it remains stable in the background.

**Expected behavior:**
Program to stay stable

**System Details:**
08:27:07 INFO app: ------------------------------------------------
08:27:07 INFO app:             Tue Oct 18 08:27:07 2022            
08:27:07 INFO app:               Starting new session              
08:27:07 INFO app: ------------------------------------------------
08:27:07 INFO app:           OpenShot (version 2.6.1-dev)          
08:27:07 INFO app: ------------------------------------------------
08:27:07 INFO app: openshot-qt version: 2.6.1-dev
08:27:07 INFO app: libopenshot version: 0.2.8-dev
08:27:07 INFO app: platform: Windows-10-10.0.19041
08:27:07 INFO app: processor: Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
08:27:07 INFO app: machine: AMD64
08:27:07 INFO app: python version: 3.8.9
08:27:07 INFO app: qt5 version: 5.15.2
08:27:07 INFO app: pyqt5 version: 5.15.4
08:27:07 INFO app: Frozen version info from build server:
{
    "build_name": "OpenShot-v2.6.1-dev-daily-9949-b890417a-46255e46",
    "date": "2022-10-17 14:43",
    "libopenshot": {
        "CI_COMMIT_REF_NAME": "develop",
        "CI_COMMIT_SHA": "b890417ada3ef417b64ab72cc8d01aec7878206a",
        "CI_JOB_ID": "32063",
        "CI_PIPELINE_ID": "9944",
        "CI_PROJECT_NAME": "libopenshot",
        "SO": "22",
        "VERSION": "0.2.8-dev"
    },
    "libopenshot-audio": {
        "CI_COMMIT_REF_NAME": "develop",
        "CI_COMMIT_SHA": "46255e46a46cad990236f941130e096155e2577a",
        "CI_JOB_ID": "31533",
        "CI_PIPELINE_ID": "9757",
        "CI_PROJECT_NAME": "libopenshot-audio",
        "SO": "8",
        "VERSION": "0.2.2-dev"
    },
    "openshot-qt": {
        "CI_COMMIT_REF_NAME": "develop",
        "CI_COMMIT_SHA": "70ce11690845e106bca4a8f57833f396ee2145de",
        "CI_JOB_ID": "32082",
        "CI_PIPELINE_ID": "9949",
        "CI_PROJECT_NAME": "openshot-qt",
        "SO": null,
        "VERSION": "2.6.1-dev"

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files o
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/9812271/libopenshot.log)
ver 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/9812268/openshot-qt.log)

**Comment by Colorjet3** [comment]
Just wanted to let you know that I was able to replicate your issue and an internal ticket has been generated to work on a resolution.  Meanwhile, make small changes in increments and save often.

**Comment by macleanflood** [comment]
Seems like the most recent daily build is far more stable.

Thanks for the hard work!

-Mac

**Comment by Colorjet3** [comment]
Thank you @macleanflood for that feedback.  Yes, the latest daily build is much more stable now.  Still more work to be done.  Visit the openshot.org/download then Daily Builds often for the latest DEV version for now.  Not sure yet when a production release will be published.

**Comment by macleanflood** [comment]
Afraid to install a newer one at the moment...that was three weeks of hell trying to get a couple of videos edited. Probably going to wait for a production release. Bonus points if it includes video card acceleration!

I appreciate all the work you folks are putting into this project!

Thanks!
Mac

**Comment by Colorjet3** [comment]
Hi @macleanflood I completely understand your hesitation.  No production date has been set at this time, unfortunately, until the Caching and performance has been vetted.  Video card acceleration is in the works but I don't have a status update on that (will check into it).

I am going to make a note for myself to come back to this post and give you an update as more Daily Builds are published.  I just started testing with build #10080 and as I mentioned it is much more stable than previous daily builds, specially with large project.  Additionally, there are some Caching improvements that you will benefit from with editing/previewing.

Good luck with your project(s)!

**Comment by macleanflood** [comment]
10080 Build is stable. Thanks!

**Comment by Colorjet3** [comment]
That is great @macleanflood .  Keep revisiting the Daily Builds download page for updated DEV versions and best of luck with your project(s).

**Comment by FireCulex** [comment]
All daily builds 11-18 open and immediately close for me. Win11.

**Comment by Colorjet3** [comment]
Hello @FireCulex .  Please start a new thread providing much more details about the version of OpenShot your are running (Help | About Openshot).

This topic "Constant Crashes" is not the same as "immediately close for me".  A new thread would make it easier to help you and better for other users to find issues/answers.  If you are not willing to do so, I can just recommend that you at minimum, go to openshot.org/download/#daily and download the latest available Daily Build and give it a try.
