### ISSUE TITLE
Different colors in title text (through Inkscape) not supported

### ISSUE THREAD

**Issue by RodenLuo** [OpenShot/openshot-qt#4949]
**Describe the bug:**

In Inkscape, one line of text is designed to have different colors. But in OpenShot, it only shows one color. If one can point me to the right section of the code (where the svg format is parsed and where the color is added to the text rendering), I might be able to fix it. Thanks. 

**Steps to reproduce the behavior:**

Import this svg (right click and save as):

![multi_color_text](https://user-images.githubusercontent.com/8460424/196762562-b3c08b01-06c2-4323-8d1a-cfb454ed3003.svg)

**Expected behavior:**

Multiple colors being rendered. 

**System Details:**
- OpenShot Version: 2.6.1-dev, libopenshot:0.2.7-dev
- Operating System / Distro: Windows 10 + Msys

**Screenshots:** (Optional)

This is shown in Openshot: 

![image](https://user-images.githubusercontent.com/8460424/196763773-668353d9-f4aa-4254-87fa-9f832c2c0a94.png)

**Comment by Colorjet3** [comment]
Which build # of OpenShot are you running (help | About Openshot)?  I am running the latest DEV Daily build #9949 in Windows 10 and Windows 11 and the colors come through just fine.  In addition to importing this .svg file, I was able to create a Title from withing OpenShot (Title | Title), then selecting "Bar 3" template, then selecting "Use Advanced Editor" which will start Inkscape (if you have it configured properly in Edit | Preference), then in Inkscape, I modified each letter to different colors, closed Inkscape (save during exit), and the colors of each of the letters came through just fine in OpenShot.

**Comment by RodenLuo** [comment]
Hi, I'm on a self-build (following the official building instructions) with the original code (openshot-qt version: 2.6.1-dev, libopenshot version: 0.2.7-dev). More details below. Will try the version you suggested. Thanks. 

```
$ python src/launch.py
Loaded modules from: D:/msys64/home/luod/openshot/openshot-qt/src
INFO sentry: No sentry_sdk module detected (error reporting is disabled)
INFO app: ------------------------------------------------
INFO app:             Thu Oct 20 07:36:25 2022
INFO app:               Starting new session
INFO app: ------------------------------------------------
INFO app:           OpenShot (version 2.6.1-dev)
INFO app: ------------------------------------------------
INFO app: openshot-qt version: 2.6.1-dev
INFO app: libopenshot version: 0.2.7-dev
INFO app: platform: Windows-10-10.0.19044-SP0
INFO app: processor: Intel64 Family 6 Model 85 Stepping 7, GenuineIntel
INFO app: machine: AMD64
INFO app: python version: 3.10.7
INFO app: qt5 version: 5.15.3
INFO app: pyqt5 version: 5.15.7
```

**Comment by RodenLuo** [comment]
Oh, this is very awkward. I tested with the official release build: openshot-qt version: 2.6.1, libopenshot version: 0.2.7. And it worked fine. Probably there are some building-related warnings I missed. Thanks!
