### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by Neustradamus** [OpenShot/openshot-qt#4954]
Dear @jonoomph and @openshot team,

It is possible to have a new release build?
Same for libs of course.

Thanks in advance.

Regards.

**Comment by Colorjet3** [comment]
v3.0.0 has been published.  Is there something specific you are looking for?  There are man bug fixes and enhancements and a minor release is already in the works with more fixes and enhancements.

I will close this ticket.  Please open a new ticket with an issue and/or request for a feature/enhancement.

**Comment by Neustradamus** [comment]
@Colorjet3: Thanks for your information!

Good job to @OpenShot team and @jonoomph!

It is possible to update all "master" branches?
- https://github.com/OpenShot/openshot-qt/tree/master
- https://github.com/OpenShot/libopenshot/tree/master
- https://github.com/OpenShot/libopenshot-audio/tree/master
