### ISSUE TITLE
Audio is not synced after exporting video

### ISSUE THREAD

**Issue by mydeveloperplanet** [OpenShot/openshot-qt#4958]
**Describe the bug:**
I created a video with the latest daily build. The preview of the video is working just fine, that is, the video and the audio are in sync. Exporting the video with:
* Target: MP4 (h.264)
* Video Profile (HD 720p 30 fps (1280x720)
* Quality (High)

Result: the audio and video are out of sync
Tried the same with 60 fps and then it is even worse. The audio starts later than the video.

**Expected behavior:**
Exported video and audio are in sync.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: v2.6.1-dev-daily-9975-b890417a-46255e46, build date: 2022-10-20 20:23
- Operating System / Distro: Ubuntu 22.04.1 LTS

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

**Exception / Stacktrace:**
No crash or exception

**Comment by Colorjet3** [comment]
Please download the latest dev daily build #10080.  Many fixes since 9975.  Let us know the results and we can continue troubleshooting.

**Comment by mydeveloperplanet** [comment]
I tried build #10153. It is, however, not fixed yet.

**Comment by sc0nway** [comment]
Hi @mydeveloperplanet. Have you tried the latest Daily Build of OpenShot v3.0.0? You can download our AppImage from this link https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v3.0.0-daily-10810-94e5f740-f55ec5d0-x86_64.AppImage.

**Comment by mydeveloperplanet** [comment]
Hi, I have tried v3.0.0 build date 20-12-2022, same result.
Is there anything else I can do? Maybe create a small video with the issue and then upload it somewhere?

**Comment by Colorjet3** [comment]
From a terminal session check your audio sample rate in Ubuntu by running "pacmd list-sinks".  Now go into OpenShot and Edit | Preferences | Preview tab and ensure the Default Audio Sample rate matches it.   Typically, this mainly impacts the Video Preview but let's see if it might resolve the Export issue as well.

Also, when you click on Export, what are your values in the Simple tab?

**Comment by mydeveloperplanet** [comment]
the output of `pacmd list-sinks` is (at least, the default audio sample rate):
```
sample spec: s16le 2ch 44100Hz
channel map: front-left,front-right
             Stereo
```
the default audio sample rate in the preferences window is 44100, default audio channels is Stereo.
Seems the same to me.

the settings in the simple tab are the following (I also tried 60 fps but with same result):
![image](https://user-images.githubusercontent.com/33178014/209356381-82b4e93f-1c2f-44ea-ab1f-8a17fbc7aaad.png)

**Comment by Colorjet3** [comment]
Please check this out and let me know if any of the workarounds resolved your issue:  https://www.reddit.com/r/OpenShot/comments/hp169g/audio_is_out_of_sync/

**Comment by mydeveloperplanet** [comment]
First of all, many, many thanks for your support, it solved my problem. 

I had to set the correct sample rate in the Export-Advanced window in the Audio section. It always seems to default to 48000 on my system. After changing it into 44100, the synchronisation issue is gone. 
The Preview Window defaults to 44100.

How are these values defined? It seems that the Preview window defaults to the correct value, but the Export window doesn't and also does not remember the last used value. Shouldn't this require some fix?

**Comment by Colorjet3** [comment]
You are welcome @mydeveloperplanet .  Ideally, we would want OpenShot to check the Default Audio device that is setup defined in the operating system and match that setting in OpenShot (edit | preferences | Preview tab).  During the export I would think that the  Audio Setting Sample Rate (Export | Advanced | Sample Rate) would match the Preview tab sample rate.

I am not a developer and really don't understand all the complexities that go into decoding/encoding during the Preview and/or the Export process.  

Additionally, there have been some discussions regarding "Default" settings, both global (when you start a new project) and project specific (a project will have their own unique settings).  Nothing is approved on this yet.  If you have suggestions submit an enhancement request in a separate ticket.
