### ISSUE TITLE
Problem with the Chrominance effect in Openshot

### ISSUE THREAD

**Issue by ghost** [OpenShot/openshot-qt#4959]
Hello.

I have installed Openshot 2.6.1 on my computer. I am under Ubuntu 22.10 and the software opens normally. I want to make montages with green backgrounds and to do this I need to use the Chrominance effect and modify one of the values corresponding to the colour that should be made transparent (green). The problem is that it is impossible for me to modify this value because double-clicking on it has no effect. Do you have any idea what is going on and how to fix it?

Thanks in advance.

**Comment by Colorjet3** [comment]
Please go to openshot.org/download/#daily and get the latest DEV Daily Build (3.0.0).  Give it a tray and let us know if your issue has been resolved.
