### ISSUE TITLE
Can't install openshot 2.2

### ISSUE THREAD

**Issue by leifjohn** [OpenShot/openshot-qt#497]
I installed openshot following the ppa instructions - yet when I click on the "help -> about openshot" it shows version 2.1

I have run sudo apt-get update but this does not update. What am I missing?

**Comment by leifjohn** [comment]
So it looks like the 2.2 package does not exist for Wily 15.1

https://launchpad.net/~openshot.developers/+archive/ubuntu/ppa/+packages

**Comment by jreynojustin** [comment]
Hi @leifjohn,

You can always install from the binaries on our website if you so choose to get the latest version. I'm not sure why Wily only has 2.1 but it is not an issue to be addressed here.
