### ISSUE TITLE
Hi, doesn't start on my windows 10...

### ISSUE THREAD

**Issue by corentin-garrault** [OpenShot/openshot-qt#4970]
**Describe the bug**
After a fresh install (daily one) openshot doesn't open.

**Steps to reproduce the behavior:**
1. double click on openshot
2. a blue circle during 5 s
3. Nothing more happen

**Expected behavior**
Open openshot...

**System Details**
- OpenShot Version: 2.6.1-dev
- libopenshot Version:  0.2.8-dev
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: 
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-dev-daily-10112-670baa5a-46255e46-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/d3ru9waax5b6a80g5az2agwccalxb31w/openshot-qt.zip) (4 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
1.  How much disk space do you have left on your primary hard drive?
2.  Looking at your log, open File Explorer, navigate to c:\users\coren\.openshot_qt folder.  See if you can create a simple text file.  Just trying to rule out possible permissions issue or just an issue with creating a file.

**Comment by corentin-garrault** [comment]
Hi, thank's for your answer.
1. 30 Go left on my primary hard drive.
2. I can create a file in this folder (i.e. test.txt has been created in this folder).

Note : i don't know if it's important or not, but i have installed ANKI (before openshot) with qt 6. I don't want to deinstall it to try to solve my problem with openshot because i can loose my work on this software. (sorry for my arwfull english, i am french).

**Comment by Colorjet3** [comment]
Your English is great.  Thank you for the information.

Let's check one more thing.  You may be running into Display driver issue.  Let's try these:
1.  Ensure that you are all up-to-date on your Windows 10 updates.  From the search field in the task bar, type "check for updates" excluding the quotes.  Select it from the window and run and install the updates, if any.
2.  Ensure that you have all the latest drivers for your hardware.  More importantly your display driver.
3.  Perform a clean installation of OpenShot following these instructions:  https://github.com/OpenShot/openshot-qt/wiki/Clean-Installation-of-OpenShot.  When you get to step 6 make sure to execute step 6.2 only.

OpenShot should coexist with other applications so don't worry about uninstalling ANKI.

by the way, what is your hardware, laptop or desktop?

**Comment by corentin-garrault** [comment]
Thank's for your answer.
I got it !
Now it's working fine.
My trouble is only my fault...
I explain it :
I did what you said in your previous message.
And all work well.
On my desktop i see the folder .openshot-qt
And i hide it...
It was a wrong idea, openshot couldn't work anymore.
So i did the opposite and it worked well !
Thank's for your attention and your support.
Corentin GARRAULT

**Comment by corentin-garrault** [comment]
My computer is a laptop.

**Comment by corentin-garrault** [comment]
Thank's

**Comment by Colorjet3** [comment]
I am glad it is all working for you now.  Feel free to close this ticket and reopen a new one if you run into other issues.
