### ISSUE TITLE
When add the audio (mp3) file application automatically get closed

### ISSUE THREAD

**Issue by RAJENDRANSRN** [OpenShot/openshot-qt#4972]
When upload the MP3 file it automatically get closed

**Comment by Colorjet3** [comment]
What version of OpenShot are you running?

Without much details, please go to openshot.org/download, click on Daily Builds.  Download the latest DEV Daily Available and give it a try.

**Comment by Colorjet3** [comment]
Hello @RAJENDRANSRN .  Any update on this?
