### ISSUE TITLE
Poor audio of .mp4 file exported from .mkv file

### ISSUE THREAD

**Issue by KBGregory** [OpenShot/openshot-qt#4973]
**Describe the bug**
I export a MKV video file to a HD 720p 25fps (1280x720) .mp4 file. The sound quality is very bad.

**Steps to reproduce the behavior:**
1. Put a .mkv video file into track 1 (the file has excellent sound)
2. Click on 'Export Video'
3. Select Profile: Web
4. Select Target: YouTube Standard
5. Select Video Profile: HD 720p 25 fps (1280x720)
6. Select Quality: High
7. Select Export Video
8. Play the new .mp4 video file

**Expected behavior**
The .mp4 file should play with clear sound. The sound is jittery.

**System Details**
- OpenShot Version: 2.6.1-dev
- libopenshot Version:  0.2.8-dev
- Build Date: 2022-11-01 04:33
- Platform: Windows 10 Pro, Desktop
- Processor: Processor AMD Athlon(tm) II X2 255 Processor, 3100 Mhz, 2 Core(s), 2 Logical Processor(s)

- Machine: 
- Python version: 
- Qt5 version: 
- PyQt5 version: 
- Qt Detected Languages: 
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Skipped this step

**Log Files**
N/A

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
I just downloaded a sample .mkv video/audio from the internet to test with.  Followed your instructions to reproduce and I am unable to decipher the issue.

Can you elaborate what is wrong with the sound?  Also, are you willing to share your .mkv with me so I can test it?

**Comment by KBGregory** [comment]
[Here is a link](https://www.dropbox.com/s/etm2u126m2st0lu/2022-10-30%2021-54-26.mkv?dl=0) to the .mkv file.  It is 245,014 KB and 38:40 minutes

[Here is a link](https://www.dropbox.com/s/39wqin9hebm4uxp/test%20Health%202.mp4?dl=0) to the .mp4 file of the first 3:11 minutes of the converted .mkv file. It is 168,459 KB.

**Comment by Colorjet3** [comment]
Thank you @KBGregory .  I have downloaded the files and will experiment and get back to you hopefully by tomorrow or Saturday.

**Comment by Colorjet3** [comment]
Hello @KBGregory .  I listened to the first 2 minutes of the .mkv and then the first 30 seconds of the .mp4 and I see what you mean about the poor quality.

I imported the .mkv then exported the first 5781 frames which equates to about 3:12 minutes and the audio quality matched the .mkv.

Please check the "Default Audio Sample Rate" in OpenShot (Edit | Preferences | Preview tab).  What is it set to?  Mine is set to 48000.  In this same tab, the "Default Audio Channels" is set to Stereo(2 Channel).

Please ensure that the Windows audio sample rate matches OpenShot.  Here is a nice article about the Windows 10 sample rate:  https://samsontech.zendesk.com/hc/en-us/articles/1260802890449-Fix-Windows-10-sample-rate-mismatch-causing-garbled-audio.

If you make any changes to the Windows environment then ensure to restart OpenShot.

Also, what audio devices do you use (speakers-internal/external, monitor speakers, headphones, etc.).  If you are using headphones, unplugs those for now and just user your speakers and try exporting again.

**Comment by KBGregory** [comment]
Default Audio Sample Rate is = 44100
Default Audio Channels =  Stereo (2 Channel)

I changed the Default Audio Sample Rate to 48000. 
The article says the headphones sound playback and recording default format should be the same.

My Sound, Playback, Headphones, Properties, Advanced, default format is '2 channel, 16 bit, 48000 Hz (DVD Quality)

My Sound, Recording, Headphones, Properties, Advanced, default format is '1 channel, 16 bit, 48000 Hz (DVD Quality). This can't be changed, ie, the dropdown is greyed out. 

I restarted Openshot, loaded the mkv file, cut it to 2:50 minutes, exported to YouTube Stardard, HD 720p 25 fps, and the resulting mp4 file has the same bad audio quality.

I don't see how unplugging the headphones and using the external speakers can affect the exported video audio quality.  But I will try that and report back.

**Comment by KBGregory** [comment]
With the headphones unplugged and the external speakers working, I restarted Openshot, exported a 1:20 minute segment of the .mkv file to HD 720 p 25 fps .mp4 file and the audio quality is still bad.

**Comment by KBGregory** [comment]
I downloaded and installed the previous version of Openshot v2.5.1 and installed it. I loaded the mkv file, cut it to 2 minutes, exported to YouTube  HD 720p 25 fps, and the resulting mp4 file has excellent sound quality.

**Comment by Colorjet3** [comment]
Hello @KBGregory.  I am hoping that one of the developers will see this and respond to you accordingly.

**Comment by jonoomph** [comment]
@Colorjet3 Were you able to reproduce the bad audio in your exported videos? I have tried exporting this MKV in a number of formats, with different video and audio settings, and I always get smooth audio playback. I would love to know the specific steps to reproduce this?

NOTE: I have only tried this on Linux at the moment - so I suppose it's possible this is a Windows-only issue?

**Comment by jonoomph** [comment]
Also, should this GitHub issue be closed? Or should it remain open?

**Comment by Colorjet3** [comment]
@jonoomph I just tested this, in Windows 10, using v3.0.0-10996 and the audio was very smooth during playback.
