### ISSUE TITLE
open shot ne s'ouvre pas

### ISSUE THREAD

**Issue by francksideflat** [OpenShot/openshot-qt#4976]
bonjour, j'utilise open shot video sous ubuntu. le logiciel ne veut plus s'ouvrir, Je l'ai desinstllé puis réinstallé, rien n'y fait . pouvez vous m'aider. Cordialement

**Comment by Colorjet3** [comment]
Which version of Ubuntu are you running?
Which version of OpenShot are you running?

Try running the latest DEV Daily Build AppImage and see if that works for you:  Go to openshot.org/download/#daily, download the latest available AppImage (32bit or 64 bit).  There is no installation with the AppImage.  After you download it, modify the file Properties and make the AppImage executable.

**Comment by Colorjet3** [comment]
Veuillez télécharger la dernière version de DEV Daily et essayez-la : openshot.org/download/#daily.
