### ISSUE TITLE
"'NoneType' object is not subscriptable" error

### ISSUE THREAD

**Issue by whentington** [OpenShot/openshot-qt#4977]
I recently started using openshot and this exact situation has happened to me, "'NoneType' object is not subscriptable" error, the program began to behave strangely, so i closed it and tried to open it and it gave me this error, it looks like you were able to fix it for this person so i was wondering if you could fix it for me too?

Describe the bug:
I did my project, and at this time the program began to behave strangely. Objects stopped selecting. Objects did not respond to a mouse click. I close program. Then start program again and I began to get an error when opening a project. 'NoneType' object is not subscriptable

1. try to open project
2. See error

System Details:
- OpenShot Version 2.6.1
- Operating System: windows 11

here is the zip file for my project:
[vid.zip](https://github.com/OpenShot/openshot-qt/files/9940264/vid.zip)
thanks.

        @a3nm your repaired project file:

About 3KB to download, CRC of the zip archive MD5:CE373548057B39A67BDA9A1D754C7EC7
[video - repaired.zip](https://github.com/OpenShot/openshot-qt/files/4394912/video.-.repaired.zip)

v2.5.1 compatible:
About 3KB to download, CRC of the zip archive MD5:FF5123CD992CC21D99E6625BDDA92D9D
[video - repaired-251compatible.zip](https://github.com/OpenShot/openshot-qt/files/4394922/video.-.repaired-251compatible.zip)

When you complete your project, consider to upgrade to the latest version available (v2.5.1)

**Info for the developers:**
project file has`null` object after 16750 position in the file (end of the `"clips"` section)
Also, may suffer form the https://github.com/OpenShot/openshot-qt/issues/3227 that was solved in v2.5.1

_Originally posted by @SuslikV in https://github.com/OpenShot/openshot-qt/issues/3171#issuecomment-605117577_

**Comment by Colorjet3** [comment]
Version 2.6.1-Relase-Candidate (Help | About Openshot) is very buggy.  I recommend you go to openshot.org/download, click on Daily Builds, download the latest DEV Daily Build available and give it a try.

**Comment by whentington** [comment]
> 

i downloaded the latest daily build as above, and now instead of giving me a "not subscriptable" error, im getting a "get" error, "'NoneType' object has no attribute 'get'" instead of "'NoneType' object is not subscriptable"

**Comment by Colorjet3** [comment]
I am not going to be able to decipher your .osp file.  Most likely there is an issue with either one of the clips or features you are using.

I recommend that you redo your project rather than to try and open the existing project that you are originally having issues with.

**Comment by whentington** [comment]
> I am not going to be able to decipher your .osp file. Most likely there is an issue with either one of the clips or features you are using.
> 
> I recommend that you redo your project rather than to try and open the existing project that you are originally having issues with.

that sucks, thanks for trying.
