### ISSUE TITLE
New Effects

### ISSUE THREAD

**Issue by dave821** [OpenShot/openshot-qt#498]
Hello.  

I'm currently using openshot 1.4.3, which has a good amount of effects.

It has been crashing quite a bit, and I realized there is a 2.2 version out there.  I installed the latest version, but it only came with a small handful of effects.

Is there an easy way to install a large amount of effects in one go?  

The other unfortunate part is I can't open my 1.4.3 project in 2.2, so I'm going to deal with the crashing until I finish the project.

**Comment by gebeleixis** [comment]
Are you on windows?

**Comment by dave821** [comment]
Linux Mint

**Comment by gebeleixis** [comment]
So it seems is not os depended, but what could it be? I can't seem to find anything on debug log.

**Comment by dave821** [comment]
I think maybe I should mention the main issue I want help with.  How can I import more effects?  right now there is only 7.  As compared to version 1.4.3 which had a few dozen.

**Comment by mixedbredie** [comment]
There are a number of effects available in https://github.com/OpenShot/openshot-qt/tree/master/src/effects but these depend on [libopenshot](https://github.com/OpenShot/libopenshot) and this library only has seven effects coded up [here](https://github.com/OpenShot/libopenshot/tree/master/src/effects) and [here](https://github.com/OpenShot/libopenshot/tree/master/include/effects).

If anyone knows how to code up the new effects or can port the code from version 1.4.x to 2.x then we'll all be winners.

@dave821 I don't think there is a way to import new effects.

**Comment by Dehir** [comment]
I also love to see more effects. Specially the lens correction aka "fish eye"-effect which i am using most on youtube videos. 

Thats the only reason im forced to use older 1.4.x now

**Comment by Dehir** [comment]
@mixedbredie That would be ideal. 

Even dont know shit about coding searched abit the 1.4.3 code and it seems to me that 1.4.x and older code is relying pretty much against python-code which isnt so simple to just "copy paste" to cpp as the new 2.x appears to be written in. 

So i think its pretty much anyway asking someone doing the effects from scratch and have some idea how they are done in general anyway.

**Comment by jonoomph** [comment]
Hi @dave821, you should be able to open your 1.4.3 project file in OpenShot 2.+ (using our most recent daily build). If that is breaking, please open another bug for that issue, and attach a small project file that is causing the crash (or not being detected). 

Regarding the effects, please feel free to list your favorite ones here. Since these effects must be re-coded for OpenShot 2.0, I'm always interested to work on the most popular effects first... 

However, I am going to go ahead and close this issue, since there is nothing to fix at the moment. Thanks!

**Comment by KuumuuK** [comment]
Hi
I just installed the program and started working with it. It seems great, but I also just have 7 effects to use. How can I get more? Did you recode them yet jonoomph ? I use Win 10.
Thanks
Kolja

**Comment by itschris2003** [comment]
Please re-code them. I'm on Windows 7 and it's really bugging me that there's only 7 effects. I wanted to do some weird and wonderful audio effects but there are none.

**Comment by IzzySoft** [comment]
I strongly miss an option for color correction. I vaguely remember 1.4.3 had an effect labeled "Level" or similar – but I cannot find it in the latest version (or the one before). Ideally, it would work like "Colors › Levels" does in Gimp (and "Colors › Curves" would be very welcome, too). I do a lot of diving videos, and those would much profit from at least basic color corrections – which OpenShot currently doesn't seem to provide. Any chance?

If I just missed something, pointers are of course welcome. I've already searched the website (documentation), issues here, plus a bunch of Youtube tutorials, but no dice. So as @jonoomph called to list favorites here, I thought to mention it :wink:
