### ISSUE TITLE
Openshot crashes immediately when adding a new .mp4 file

### ISSUE THREAD

**Issue by JamesRichards22** [OpenShot/openshot-qt#4980]
**Describe the bug:**
When adding a new .mp4 file, recorded on a Google Pixel 6 in portrait mode, OpenShot crashes immediately. Opening previous files worked, just the files today. The files play fine in other Gnome video software on Ubuntu.

Video
1920x1080
H.265
25 frame/sec
19657 kbps

Audio
MPEG-4 AAC
Stereo
48000 Hz
192 Kbps

**Steps to reproduce the behavior:**
1. Start OpenShot
2. Add mp4 file to project

**Expected behavior:**
It doesn't crash.

**System Details:**
5:37:53 INFO app: ------------------------------------------------
15:37:53 INFO app:             Sun Nov  6 15:37:53 2022            
15:37:53 INFO app:               Starting new session              
15:37:53 INFO app: ------------------------------------------------
15:37:53 INFO app:           OpenShot (version 2.6.1-dev)          
15:37:53 INFO app: ------------------------------------------------
15:37:53 INFO app: openshot-qt version: 2.6.1-dev
15:37:53 INFO app: libopenshot version: 0.2.8-dev
15:37:53 INFO app: platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.35
15:37:53 INFO app: processor: x86_64
15:37:53 INFO app: machine: x86_64
15:37:53 INFO app: python version: 3.10.6
15:37:53 INFO app: qt5 version: 5.15.3
15:37:53 INFO app: pyqt5 version: 5.15.6

**Log Files:**
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/9945163/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/9945164/openshot-qt.log)

**Exception / Stacktrace:**
```
--- Unhandled Exception: Stack Trace ----
  /usr/lib/python3/dist-packages/_openshot.cpython-310-x86_64-linux-gnu.so swig::SwigPyForwardIteratorOpen_T<std::_Rb_tree_iterator<std::pair<std::__cxx11::ba
sic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, st
d::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::a
llocator<char> > >, swig::from_oper<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_strin
g<char, std::char_traits<char>, std::allocator<char> > > > >::value() const 0x16  [0x7f15206e5ee6]
  /usr/lib/python3/dist-packages/_openshot.cpython-310-x86_64-linux-gnu.so                                          0xbc8fd  [0x7f15205f48fd]
  /usr/bin/python3                                                        0x15bd24  [0x55a212793d24]
  /usr/bin/python3               _PyEval_EvalFrameDefault                 0x289f  [0x55a21277f84f]
  /usr/bin/python3               _PyFunction_Vectorcall                   0x7c  [0x55a212794b6c]
  /usr/bin/python3               _PyEval_EvalFrameDefault                 0x8b6  [0x55a21277d866]
  /usr/bin/python3               _PyFunction_Vectorcall                   0x7c  [0x55a212794b6c]
  /usr/bin/python3               _PyEval_EvalFrameDefault                 0x6c5  [0x55a21277d675]
  /usr/bin/python3                                                        0x16a5c1  [0x55a2127a25c1]
  /usr/bin/python3               _PyEval_EvalFrameDefault                 0x6c5  [0x55a21277d675]
  /usr/bin/python3               _PyFunction_Vectorcall                   0x7c  [0x55a212794b6c]
  /usr/bin/python3               _PyEval_EvalFrameDefault                 0x8b6  [0x55a21277d866]
  /usr/bin/python3               _PyFunction_Vectorcall                   0x7c  [0x55a212794b6c]
  /usr/bin/python3               _PyEval_EvalFrameDefault                 0x8b6  [0x55a21277d866]
  /usr/bin/python3               _PyObject_FastCallDictTstate             0xc4  [0x55a212789fd4]
  /usr/bin/python3                                                        0x1667c4  [0x55a21279e7c4]
  /usr/bin/python3               _PyObject_MakeTpCall                     0x1fc  [0x55a21278adec]
  /usr/bin/python3               _PyEval_EvalFrameDefault                 0x6ad1  [0x55a212783a81]
  /usr/bin/python3               _PyFunction_Vectorcall                   0x7c  [0x55a212794b6c]
  /usr/bin/python3               _PyEval_EvalFrameDefault                 0x8b6  [0x55a21277d866]
  /usr/bin/python3                                                        0x16a70e  [0x55a2127a270e]
  /usr/bin/python3               _PyEval_EvalFrameDefault                 0x289f  [0x55a21277f84f]
  /usr/bin/python3               _PyFunction_Vectorcall                   0x7c  [0x55a212794b6c]
  /usr/bin/python3               _PyEval_EvalFrameDefault                 0x289f  [0x55a21277f84f]
  /usr/bin/python3               _PyFunction_Vectorcall                   0x7c  [0x55a212794b6c]
  /usr/bin/python3               _PyEval_EvalFrameDefault                 0x61a2  [0x55a212783152]
  /usr/bin/python3               _PyFunction_Vectorcall                   0x7c  [0x55a212794b6c]
  /usr/bin/python3               _PyEval_EvalFrameDefault                 0x8b6  [0x55a21277d866]
  /usr/bin/python3                                                        0x16a821  [0x55a2127a2821]
  /usr/bin/python3                                                        0x2964ca  [0x55a2128ce4ca]
  /usr/bin/python3                                                        0x28c7e8  [0x55a2128c47e8]
  /lib/x86_64-linux-gnu/libc.so.6                                          0x94b43  [0x7f155d73cb43]
  /lib/x86_64-linux-gnu/libc.so.6                                          0x126a00  [0x7f155d7cea00]
---- End of Stack Trace ----
```

**Comment by Colorjet3** [comment]
Can you tell us what build # you are running?  Help | About OpenShot and you should see v2.6.1-DEV-nnnn-........  We need the value of the nnnn's?

**Comment by JamesRichards22** [comment]
This is what I see
I'm getting it from the ppa of OpenShot
```
deb [arch=amd64] https://ppa.launchpadcontent.net/openshot.developers/libopenshot-daily/ubuntu/ jammy main
```
the details are
```
$ dpkg -s openshot-qt
Package: openshot-qt
Status: install ok installed
Priority: optional
Section: video
Installed-Size: 134442
Maintainer: Ghislain Antony Vaillant <ghisvail@gmail.com>
Architecture: all
Version: 2.6.1+dfsg2+1587+202211050302~ubuntu22.04.1
Depends: python3-defusedxml, python3-distro, python3-openshot, python3-pyqt5, python3-pyqt5.qtopengl, python3-pyqt5.qtsvg, python3-pyqt5.qtwebengine, python3-requests, base-files (<< 11) | python3-sentry-sdk, python3-xdg, python3-zmq, qttranslations5-l10n, python3:any
Suggests: openshot-qt-doc
Description: OpenShot video editor
 OpenShot Video Editor is a free, open-source, non-linear video editor. It can
 create and edit videos and movies using many popular video, audio, and image
 formats. Create videos for YouTube, Flickr, Vimeo, Metacafe, Xbox, and many
 more common formats!
 .
 This package provides the OpenShot application.
Homepage: http://www.openshot.org/
```
![image](https://user-images.githubusercontent.com/117557126/200202561-4c52c491-bb04-4ef4-84f9-c84a355e09eb.png)

**Comment by Colorjet3** [comment]
Thank you for that.  I am a novice linux user and I typically download and run the AppImage from openshot.org/downloads/#daily.  The AppImage shows the daily build # when you perform Help | About Openshot.   So, you must have ran the Daily PPA commands from here:  https://www.openshot.org/ppa/.  I will report this to the development team so that they can add the build # to the help about screen.

Back to your issue: 
1.  Does this happen with other .mp4 files?
2.  Try to run your .mp4 video through a converter like HandBrake, VLC, or ShutterEncoder and convert back to .mp4 again.  Sometimes this will fix a possibly trouble video/audio file.
3.  Can you import other files types (.mov, .mkv, etc.), how about image files, .jpg, .png, etc.?

If all fails, try downloading the AppImage and give that a try.

Update:  I just confirmed that if you install OpenShot via the Daily PPA it does not include the Build #.

Update 2:  I just confirmed that I am able to import .mp4 into OpenShot (installing the Daily PPA) in both Linux Mint and in Ubuntu without OpenShot crashing.

**Comment by JamesRichards22** [comment]
In Answer ...
1. No, it seems to be just these specific videos I made on my Google Pixel 6 in portrait mode. Other videos worked fine.
1. I ended up using `ffmpeg` to resize them and output new files, which worked.
1. Yes.

I'll make a short sample file and attach it here later.
The AppImage version didn't work. the UI didn't accept click events so I couldn't do anything. Had to kill the process.

Here's a short video which reproduces the issue using H265 format (this doesn't play in the preview here)

[GooglePixel6Portrait.mp4](https://user-images.githubusercontent.com/117557126/200437962-cbbce716-7b1d-46b0-a16e-127851fabe37.mp4)

Here's another using H264 format (this does play in the preview here)

[GooglePixel6Portrait-H264.mp4](https://user-images.githubusercontent.com/117557126/200438487-db6b0885-c28a-4773-9db7-1583d82be587.mp4)

**Comment by Colorjet3** [comment]
Thank you for the sample files.
Testing in Ubuntu 22.04 LTS:
1.  I can confirm that both of these .mp4 files cause the PPA Daily installation of Openshot to crash.  This is a good thing as we have a repeatable process.
2. I confirmed that when I ran the AppImage (DEV Daily Build #10213), I was able to import both .mp4s and edit them.  Although they are somewhat difficult to manage unlike other .mp4 files.  The 2nd video is much more difficult to resize, etc., then the first one. 
3. Please go to openshot.org/downloads/#daily and download build #10213(DO NOT DOWNLOAD BUILD #10218).  After you download it, right click on the Image, select Properties, click on the Permissions tab, and check the Execution box "Allow executing file as program".
4. Now double click the AppImage and start OpenShot.
5. Import those two .mp4 files you shared with me and note that they should work.

If you can not get the AppImage to work then let's debug that to get it working as I am not having any issues with this build in Ubuntu.

**Comment by JamesRichards22** [comment]
Okay, this is interesting ...

I'm running OpenShot-v2.6.1-dev-daily-10213-854a3aa3-46255e46-x86_64.AppImage. Interestingly, the UI works fine.

I took the original file I tried a few weeks ago and it imported correctly. This is the console output
```
INFO files_treeview: Processing drop event for 1 urls
INFO files_model: Imported media file /home/grumpy/Videos/Twisty Puzzles/Short - Plus 2 Scramble/PXL_20221106_035010848.TS.mp4
INFO main_window: updateStatusChanged
```

The video file above of the outside building worked
```
INFO files_treeview: Processing drop event for 1 urls
INFO files_model: Imported media file /home/grumpy/Desktop/200437962-cbbce716-7b1d-46b0-a16e-127851fabe37.mp4
INFO main_window: updateStatusChanged
```

But the one of my desk with the coffee cup and pyraminx did not work
```
INFO files_treeview: Processing drop event for 1 urls
Hardware decoding device number: 0
Hardware decoding device number: 0
WARNING files_model: Failed to import /home/grumpy/Desktop/200438487-db6b0885-c28a-4773-9db7-1583d82be587.mp4: No Reader has been initialized for this Clip.  Call Reader(*reader) before calling this method.
```
![Screenshot from 2022-11-11 20-35-43](https://user-images.githubusercontent.com/117557126/201312388-0992e09a-0e4c-4101-91cd-861e9ff4214b.png)

**Comment by Colorjet3** [comment]
hello @JimRichards22 .  I will need to get the attention of one of the developers to look at this as it is beyond my pay grade ;-).

Meanwhile, run the trouble .mp4 through a converter like HandBrake or Shutter Encoder and convert back to .mp4 or some other video format and see if you can then import that into OpenShot.  This isn't the end solution but at least it will keep you going forward with your project(s).

**Comment by Colorjet3** [comment]
hello @JimRichards22 .  I just found out that the error message regarding "...not a valid video, audio, or image file." is currently a bug in the Linux environment.  It has to do something with the version of ffmpeg.  A fix is on the way.

**Comment by JamesRichards22** [comment]
@Colorjet3 did this get fixed? I've got the latest daily build as .AppImage and it plays a H.265 if imported by itself, but added to other videos it shows only the first frame of the clip. But cutting it up the first frame of each clip is shown.

**Comment by Colorjet3** [comment]
Hello @JamesRichards22 No, I have not seen a fix for this at this time and I can not give you an ETA on it.

As a workaround, try converting the h.265 to h.264 and then import that into OpenShot.  Let me know if this an acceptable/workable workaround at this time.

**Comment by JamesRichards22** [comment]
I've been trying a few different things to convert it. If I bring the file in directly to Openshot with nothing else, it plays. I can export it as a different MP4 format and bring it into the project it doesn't play. I can convert it with `ffmpeg` to another MP4 format, and it doesn't play in the project. I suspect it's not the video format but maybe something about the project file itself. The file was exported from Adobe After Effects. (I have 3 of them, all the same issue).)

It will show the first frame in my project. If I move the playhead, then the frame under the playhead shows, but when I click play, there's no video progression. I've also been messing with renaming files, etc. I think that's more likely the issue. As I can rename the source file, drag it in and it plays. It's just when I rename it to match the original file it breaks.

Let me work out what I broke, but I think this is a different issue. For now, Openshot plays H.265 files now.

**Comment by NBoumakis** [comment]
I have the same problem. Can I help somehow? The video I am trying to edit uses H.264. When importing the file I am getting a SIGSEGV in _openshot.so+0x180270.

Unfortunately,  I cannot share the video, sorry...

**Comment by Colorjet3** [comment]
Hello @NBoumakis Please provide the following:
1.  What operating system/version are you running (windows 11 Pro?  Ubuntu 22.04 lts? etc?)
2.  Which version of OpenShot are you running (help | about openshot)?

Give this a try:
1.  Run your video file through a converter like VLC, ShutterEncoder, or HandBrake and convert it to .mp4 (even if the original file is .mp4) and give it a new name.
2. Now import this new file into OpenShot.
3. Did this work?

**Comment by NBoumakis** [comment]
Hi @Colorjet3,

Sorry I didn't include this basic information, I was in too much a hurry, my bad. Here you go:

OS: Manjaro 24.1.2, Linux Kernel 6.6.54
Openshot: 3.2.1, libopenshot: 0.3.3
Video created in phone: TCL 40 SE, Android 13
Camera app version: 6.00.04.2301.0046.10.0

After running the file through VLC's default conversion to H.264+MP3 (MP4), I again get a crash. After the conversion, the video is much smaller, both in resolution and size so I don't think the bug has anything to do with those. What actually remains constant is the rotation (-90deg).

It then occurred to me that I could create a second video that I can share. It still crashes.

https://github.com/user-attachments/assets/3d136e3a-6a24-470e-96bf-b6e4cef7077a

**Comment by Colorjet3** [comment]
Hello @NBoumakis Thank you for all the information you provided.  

1.  When I play the video I see nothing.  It plays for 3 seconds and done.
2.  Have you tried running the AppImage?  If not,
a.  Close openshot if running.
b.  Go to OpenShot.org/download/#daily and download the latest dev daily build #12980 as of this writing.
c.  Make the AppImage executable.
d.  You may need to install libfuse2 to make the AppImage run (sudo apt install libfuse2).

Let us know if the AppImage works.

**Comment by NBoumakis** [comment]
There is nothing to see in the video, just a few seconds of a wall. It's just a video you can use to test the problem if interested. When you try to import it, at least in my case, the whole OpenShot crashes.

I will try the AppImage tomorrow (late at night over here), maybe it is fixed there. Thank you for the instructions.

**Comment by Colorjet3** [comment]
Hello @NBoumakis I have Manjaro running in an Oracle Virtualbox environment as guest session.   I downloaded the sample file you provided and imported it into OpenShot v3.2.1 (AppImage build #12980).  Everything worked fine.

**Comment by NBoumakis** [comment]
Hello @Colorjet3,

Well, I guess that everything is good then. I didn't test yet using the AppImage. Maybe it's something specific to my system. If I have time, I might build OpenShot from source and investigate further. If I make any progress, I will let you know, maybe along with a PR. Until then, thank you for the time you spend on this.
