### ISSUE TITLE
Crashes immediately on Mac with memoryerror

### ISSUE THREAD

**Issue by cosypjs** [OpenShot/openshot-qt#4989]
Hey there,

I have downloaded and installed the latest Mac Amd64 build of Openshot (v2.6.1-x86_64). I am running on a Macbook Pro Intel architecture 16 inch 2019 model, running MacOS 12.6.1.

Upon trying to launch Openshot-QT, it immediately fails. If I launch from the command line I get the following error output:

Compiled translation resources missing!
Loading translations from: /Applications/OpenShot Video Editor.app/Contents/Resources/language
Loaded modules from: /Applications/OpenShot Video Editor.app/Contents/Resources
INFO app: ------------------------------------------------
INFO app:             Fri Nov 11 11:08:31 2022            
INFO app:               Starting new session              
INFO app: ------------------------------------------------
INFO app:             OpenShot (version 2.6.1)            
INFO app: ------------------------------------------------
INFO app: openshot-qt version: 2.6.1
INFO app: libopenshot version: 0.2.7
INFO app: platform: Darwin-21.6.0-x86_64-i386-64bit
INFO app: processor: i386
INFO app: machine: x86_64
INFO app: python version: 3.7.11
INFO app: qt5 version: 5.15.0
INFO app: pyqt5 version: 5.15.1.dev2007111314
INFO app: Frozen version info from build server:
{
    "build_name": "OpenShot-v2.6.1-release-candidate-8238-59878784-d588dbd6",
    "date": "2021-09-04 18:49",
    "libopenshot": {
        "CI_COMMIT_REF_NAME": "release-20210904",
        "CI_COMMIT_SHA": "59878784732fa399c47ac5d282bfc9dfe470d0dc",
        "CI_JOB_ID": "27418",
        "CI_PIPELINE_ID": "8237",
        "CI_PROJECT_NAME": "libopenshot",
        "SO": "21",
        "VERSION": "0.2.7"
    },
    "libopenshot-audio": {
        "CI_COMMIT_REF_NAME": "release-20210904",
        "CI_COMMIT_SHA": "d588dbd6057f71c987dc6d8448322aa6b6e86f1a",
        "CI_JOB_ID": "27413",
        "CI_PIPELINE_ID": "8236",
        "CI_PROJECT_NAME": "libopenshot-audio",
        "SO": "8",
        "VERSION": "0.2.2"
    },
    "openshot-qt": {
        "CI_COMMIT_REF_NAME": "release-20210904",
        "CI_COMMIT_SHA": "11f8e5050bd95c7731beccda28a01fbb481fcf7d",
        "CI_JOB_ID": "27423",
        "CI_PIPELINE_ID": "8238",
        "CI_PROJECT_NAME": "openshot-qt",
        "SO": null,
        "VERSION": "2.6.1"
    }
}
INFO project_data: Setting default profile to HD 720p 30 fps
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/cx_Freeze-6.4.2-py3.7-macosx-10.15-x86_64.egg/cx_Freeze/initscripts/__startup__.py", line 41, in run
  File "/usr/local/lib/python3.7/site-packages/cx_Freeze-6.4.2-py3.7-macosx-10.15-x86_64.egg/cx_Freeze/initscripts/Console.py", line 36, in run
  File "openshot_qt/launch.py", line 203, in <module>
    main()
  File "openshot_qt/launch.py", line 198, in main
    app.gui()
  File "/Applications/OpenShot Video Editor.app/Contents/MacOS/lib/classes/app.py", line 190, in gui
    from classes import language, sentry, ui_util, logger_libopenshot
  File "/Applications/OpenShot Video Editor.app/Contents/MacOS/lib/classes/logger_libopenshot.py", line 34, in <module>
    import zmq
  File "/usr/local/lib/python3.7/site-packages/zmq/__init__.py", line 50, in <module>
  File "/usr/local/lib/python3.7/site-packages/zmq/__init__.py", line 16, in _load_libzmq
    the Free Software Foundation, either version 3 of the License, or
  File "/usr/local/Cellar/python@3.7/3.7.11/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 551, in <module>
  File "/usr/local/Cellar/python@3.7/3.7.11/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 273, in _reset_cache
MemoryError
INFO app:             OpenShot's session ended            
INFO app:             Fri Nov 11 11:08:32 2022            
INFO app: ================================================

**Comment by Colorjet3** [comment]
Please go to openshot.org/download/#daily and download build #10213.  DO NOT INSTALL BUILD #10218.

Install #10213 and let us know if it resolved your issue.

**Comment by JonBendtsen** [comment]
build #10213 does start for me :-)

Before downloading that I had the same error as [cosypjs]

**Comment by Colorjet3** [comment]
That is great @JonBendtsen .  Thank you for the FYI.  Hopefully this will help others as well.  Please visit the Daily Build site often for the latest updates as more fixes are in the pipeline until a production version has been released (ETA?).

**Comment by cosypjs** [comment]
Hey @Colorjet3 thanks for the response. I can also confirm that build OpenShot-v2.6.1-dev-daily-10327-7617e916-46255e46-x86_64.dmg works for me now! 

Happy to close this issue as it seems to be fixed in daily!
