### ISSUE TITLE
The video preview stops at a certain part.

### ISSUE THREAD

**Issue by DatGreninja** [OpenShot/openshot-qt#499]
When I play the video it stops at a certain part and the video stops working entirely i'm using an audio.

**Comment by JtLively** [comment]
Can you define "_using an audio_"?
Also, version of Openshot?
OS/distro?
When do you get this issue?

**Comment by jonoomph** [comment]
Also, please retest this with our latest daily build. Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot. Please reopen this issue if the problem is still happening. Thanks!
