### ISSUE TITLE
"Crop" does not crop.  It is more like pan-and-scan.

### ISSUE THREAD

**Issue by HarlanRosenthal** [OpenShot/openshot-qt#4990]
**Describe the bug**
"crop" does not crop as expected. It operates as a transition over the span of the clip, not an effect that masks the selected area for the duration of the clip. 

**Steps to reproduce the behavior:**
OpenShot 2.6.1  0.2.7   build Date 2021-09-04 (the latest Windows version downloaded from your system yesterday!)

I successfully used OpenShot to trim leading and trailing sections from a video and export the desired portion.

Next project:  Starting with an .mp4 recorded by Microsoft Xbox Game Bar (on Windows 10) of my full computer screen with a small 480x640 video area, attempting to mask out everything outside that video area so that the resulting video is smaller.

Found instructions on "crop".  Used "crop" and adjusted the settings to letterbox everything outside the desired area (with small margins because crop doesn't seem to give pixel-level control)

Playing the video, it started with the entire screen showing, and gradually added the letterboxing until the video *ended* with the desired area

**Expected behavior**

I expected the entire video to play with the letterbox mask being consistent for the entire span of the video.

**System Details**
- OpenShot Version: 2.6.1
- libopenshot Version:  0.2.7
- Platform: Windows-10-10.0.19041
- Processor: AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Skipped this step

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/vy56ag3zprkwuy44zd859sxu4da2usrs/openshot-qt.zip) (1600 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/vy56ag3zprkwuy44zd859sxu4da2usrs/libopenshot.zip) (0 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
Most likely you had the Playhead somewhere on the clip other than the beginning.  This then causes an animated Crop or any other effect that you apply.

Here is what you do:
1. Right Click on the Crop effect and select Remove Effect.
2. Select your clip so it has the red border line.
3. Press the Previous Key Point or Next Key Point icon in the tools menu above the timeline (CTRL + right arrow or CTRL + left arrow) until the playhead is at the left edge of your clip.
4. Now drag the Crop effect onto your clip and make the necessary adjustments.  Ensure that the Playhead does not get moved to another position on the clip.
5. This should do it.

Let us know if this worked for you.
