### ISSUE TITLE
Can't insert files into OpenShot

### ISSUE THREAD

**Issue by CoalaConnoisseur** [OpenShot/openshot-qt#4994]
When I try the drag and drop method, nothing happens even though the insert icon appears when I hover over the OpenShot interface with the file in question. Yet, when I drop it, it doesn't show up at all. 

When I try to use the import function, OpenShot doesn't show me my folders. Even if I try to copy paste the path into the search box, it still doesn't work. On any such attempt, the programme tells me that such and such file doesn't exist. I tried multiple files with all sorts of ending but no one would work.

I use the newest version of OpenShot on a chromebook (Version 107.0.5304.92 (Official Build) (64-bit)).

I appreciate your time.
CC

**Comment by Colorjet3** [comment]
There is a fix for that in the latest Daily Build.  Go to openshot.org/download/#build and download the latest available and give that a try.

Assuming that this should fix your issue, revisit this site often for the latest Daily Build until a new production release is published (no ETA yet).

**Comment by CoalaConnoisseur** [comment]
> There is a fix for that in the latest Daily Build. Go to openshot.org/download/#build and download the latest available and give that a try.
> 
> Assuming that this should fix your issue, revisit this site often for the latest Daily Build until a new production release is published (no ETA yet).

Thank you. Unfortunately, I'm still unable to insert files.

**Comment by Colorjet3** [comment]
Please let me know the build # you are running (help | About OpenShot).  I will have to have one of the technical staff take a look at this to help you out.

**Comment by Colorjet3** [comment]
Here is what I got back from the technical staff:

"You must share the Chrome OS folders with the Linux partition in Chrome OS. To access the Downloads folder in Chrome OS, use the File Manager, right-click the Downloads folder, then choose the "Share with Linux" option. The Downloads folder is now available to OpenShot in Linux under the /mnt folder.

Once the folder is shared with Linux, you can use the drag-and-drop feature because the path is mapped to Linux."

I also found this link:  https://www.techrepublic.com/article/how-to-share-files-with-linux-apps-on-chrome-os/ just in case you need assistance with that.

**Comment by CoalaConnoisseur** [comment]
> Here is what I got back from the technical staff:
> 
> "You must share the Chrome OS folders with the Linux partition in Chrome OS. To access the Downloads folder in Chrome OS, use the File Manager, right-click the Downloads folder, then choose the "Share with Linux" option. The Downloads folder is now available to OpenShot in Linux under the /mnt folder.
> 
> Once the folder is shared with Linux, you can use the drag-and-drop feature because the path is mapped to Linux."
> 
> I also found this link: https://www.techrepublic.com/article/how-to-share-files-with-linux-apps-on-chrome-os/ just in case you need assistance with that.

Thank you. 

My files are shared with linux. Still I can't insert them somehow. I'm at the end of my wits here.

**Comment by Colorjet3** [comment]
I am going to ask one of the technical staff to jump in here and directory work with you to avoid delays in troubleshooting.  Stay tuned...

**Comment by sc0nway** [comment]
Hi @CoalaConnoisseur!  To help me understand your problem a little better, which version of Chrome OS and OpenShot Video Editor are you running?

**Comment by CoalaConnoisseur** [comment]
Hi there,

My Chrome OS is: Version 107.0.5304.110 (Official Build) (64-bit).

I use OpenShot version: 2.6.1 (it also says "libopenshot 0.2.7." whatever this is meant to mean)

Thanks a lot!

**Comment by CoalaConnoisseur** [comment]
> Hi @CoalaConnoisseur! To help me understand your problem a little better, which version of Chrome OS and OpenShot Video Editor are you running?

Hi there,

My Chrome OS is: Version 107.0.5304.110 (Official Build) (64-bit).

I use OpenShot version: 2.6.1 (it also says "libopenshot 0.2.7." whatever this is meant to mean)

Thanks a lot!

**Comment by sc0nway** [comment]
@CoalaConnoisseur 

You are running our release version, which is over a year old.  We are very close to releasing a new version, thoroughly testing our Daily Build in preparation for the latest release.  Our Daily Builds are a significant improvement over our previous release version.

Would you please try downloading and installing our Daily Build for Chrome OS?  You can copy and paste the following command to your Linux terminal:

`sudo bash <(wget -O – http://openshot.org/files/chromeos/install-daily.sh)`

After upgrading to the Daily Build, please try dragging and dropping from the File Manager again.  I would appreciate it if you would let us know if the drag and drop is successful or fails.

**Comment by CoalaConnoisseur** [comment]
> 

Thank you. 

I copy and pasted it into the linux terminal. I'm however not quite sure whether it worked for it says **"-bash: $'\E[200~sudo': command not found"**. This is the whole response I got:

> coala@penguin:~$ ^[[200~sudo bash <(wget -O – http://openshot.org/files/chromeos/install-daily.sh)
> -bash: $'\E[200~sudo': command not found
> coala@penguin:~$ 
> coala@penguin:~$ ~--2022-11-18 16:13:24--  http://openshot.org/files/chromeos/install-daily.sh
> Resolving openshot.org (openshot.org)... 52.22.149.119
> Connecting to openshot.org (openshot.org)|52.22.149.119|:80... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 1388 (1.4K) [text/x-sh]
> Saving to: ‘–’
> 
> –                    100%[===================>]   1.36K  --.-KB/s    in 0s    

I'm so sorry to bother you.

I still can't insert files into OpenShot.

**Comment by Colorjet3** [comment]
Hello @sc0nway  and @CoalaConnoisseur .  I just found that this is a documented issue in our daily build and is in the "approved" list to be fixed.

@CoalaConnoisseur .  Instead of dragging from File Manager, click on the green + sign from the menu tool bar and select the files you want to import into OpenShot.  This should still function and get you going until the fix is in place for dragging via File Manager.
