### ISSUE TITLE
Can't Get Timeline On Screen

### ISSUE THREAD

**Issue by H20GUY27** [OpenShot/openshot-qt#4997]
**Question:**
A clear and concise question. Your question should provide enough context and explanation for people to answer it. Avoid excessive background or irrelevant details, as they can obscure your actual question.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your question. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

I cannot get the timeline on the screen.  I have everything else but that.  When I right click the timeline box is dark and doesn't allow me to check it.  What am I doing wrong?
<img width="1440" alt="Screenshot 2022-11-16 at 9 35 17 AM" src="https://user-images.githubusercontent.com/118374981/202225355-5ae316f8-9af9-4e5a-867d-88886c463e32.png">

**Comment by H20GUY27** [comment]
I fixed it!!  So sorry to bother ya'll and waste your time!

**Comment by Colorjet3** [comment]
What was the fix?  It will help others.  Thank you in advance!
