### ISSUE TITLE
Animate no longer present in 2.0

### ISSUE THREAD

**Issue by stephenwithav** [OpenShot/openshot-qt#5]
In 1.4.3, I could right-click on an image in the timeline and choose Right to Left, Top to Bottom, etc.

In 2.0, no Animate menu appears when right-clicking.

Is the feature not yet implemented in 2.0--or is it simply not yet an option in libopenshot 0.0.5?

**Comment by Kagetsuki** [comment]
Muting a clip or separating audio from a clip is also not available. @jonoomph is there a public feature list / task list like maybe a trello board or maybe put something on waffle? It would be nice to see who's handling what and if there are tasks in the list being processed or tasks yet to be claimed.

All in all good work though. Everything is snappy and feels stable, just missing a lot of features that are probably (we're all hoping) in line to be implemented.

**Comment by jonoomph** [comment]
Thanks! This is now resolved. Closing issue.
