### ISSUE TITLE
Is there any 32 bit version of openshot?

### ISSUE THREAD

**Issue by SADEGH-H** [OpenShot/openshot-qt#500]
Hi,
I want to download OpenShot for windows 7 32-bit. but in download section of the openshot.org there is only 64-bit version.
Please tell me is there any 32 bit version of openshot?
Thanks

**Comment by mixedbredie** [comment]
From the OpenShot [blog](http://www.openshotvideo.com/2016/08/openshot-21-released.html):

> Windows 64-bit Support
We have invested a ton of time on the Windows version of OpenShot, especially the dependencies (Qt, FFmpeg, Python 3), and I'm happy to report it works great now. We also changed the installer, and upgraded everything to 64-bit (which means no more 32-bit support for the moment).

**Comment by mixedbredie** [comment]
From the OpenShot [blog](http://www.openshotvideo.com/2016/08/openshot-21-released.html):

> Windows 64-bit Support
We have invested a ton of time on the Windows version of OpenShot, especially the dependencies (Qt, FFmpeg, Python 3), and I'm happy to report it works great now. We also changed the installer, and upgraded everything to 64-bit (which means no more 32-bit support for the moment).

**Comment by jonoomph** [comment]
Sorry, we only support 64 bit on Windows currently. If enough people request 32 bit builds, I'll certainly consider adding them, but it is really painful to setup a build environment and server for both 32 and 64 bit, not to mention it adds additional time and costs (bandwidth).
