### ISSUE TITLE
Video preview sound plays in incorrect pitch if sample rates do not match

### ISSUE THREAD

**Issue by DanPinGF** [OpenShot/openshot-qt#5000]
**Describe the bug:**
When playing back a project in OpenShot, the audio presented in the video has its sound pitched increased, making it feel like if it was presented in PAL format. This does NOT affect video exports.

**Steps to reproduce the behavior:**
1. Import a video or audio file.
2. Drag any video or audio file into the timeline.
3. Press 'Play'.
4. The result? An unexpected change in audio pitch, roughly by 2%.

**Expected behavior:**
The video preview should be playing at normal pitch.

**System Details:**
- OpenShot Version: 2.6.1 [latest daily build]
- Operating System / Distro: Windows 11

**Comment by Colorjet3** [comment]
Try a couple of things:
1.  Check your Preview audio sample rate in OpenShot.  In OpenShot, go to Edit | Preferences | Preview button.  Note the "Default Audio Sample Rate" value.  It is most likely set to 44100.  Change this to 48000.  Restart OpenShot and try again.  This should take care of it.

If you are still having issues, double check the audio sample rate in Windows 11 for your default audio sample rate.  Make sure that OpenShot matches what Windows 11 is set to.

3. Comment on version 2.6.1 (Help | About Openshot) should reveal that you are running 2.6.1-Release-Candidate.  This has proven to be a very buggy version.  If you start running into other issues I highly recommend that you go to openshot.org/download/#daily and download the latest DEV Daily Build available.  Many bug fixes and enhancements.  Do this only if you have a reason to do so.

**Comment by DanPinGF** [comment]
I just adjusted the sample rate in OpenShot. That was causing the problem! Now I no longer need to worry about this. :P

**Comment by DanPinGF** [comment]
I’m reopening this because it appears to be a known issue in the latest Daily Builds where the sample rate configurations between the sound hardware and OpenShot do not match, causing the pitch to change. I’m sure everyone has the same issue, so there’s no point of closing this.

**Comment by Colorjet3** [comment]
Hello @DanPinGF This can be considered an issue or an enhancement or both.  Pre-some Windows updates, the Windows default audio sample was set to 44100.  Openshot, by default, was set to 44100 also.  After some Windows updates, Microsoft changed the default Audio sample to 48000.  The issue with Openshot is that it doesn't check that.  However, it does log it.

IMHO I think OpenShot code should be modified to at least warn you that the sample rate in Openshot does not match the sample rate in in the Windows environment.  Capturing it in the Log file is fine but not very user friendly.

@jonoomph Please review this and let us know what your thoughts are on this?

**Comment by thevalleyy** [comment]
Still having the same exact problem, even unable to change my sample rate at all.

**Comment by Colorjet3** [comment]
Hello @thevalleyy.
1.  What version of OpenShot are your running (help | about Openshot)?
2.  What operating system/version are your running (Windows 10 Pro? Ubuntu 22.04 lts? etc?).
3. What is your default output audio device?

**Comment by thevalleyy** [comment]
1. OpenShot-v3.1.1-release-11392-71OOdc7a-e47da46f (Official)
2. Microsoft Windows [Version 10.0.19045.3086] (Pro version)
3. ![grafik](https://github.com/OpenShot/openshot-qt/assets/74456686/7bbd494e-0359-4114-851e-c5119ebd61f6)


Every time I change the sample rate setting and restart, it's reverted to the default setting of 22050Hz.

**Comment by Colorjet3** [comment]
Thank you @thevalleyy for all that information.  What is happening is that OpenShot, by design, matching the sample rate of your Windows Default Audio device.  In Windows Default Audio device, go ahead and change the sample rate to 48000.  Now restart OpenShot and it should set sample rate to match your Windows.

Before you do too much in OpenShot after making the change above is to play some audio outside of OpenShot to ensure everything sound ok.  Play some .mp3, .mp4, etc., files to ensure audio sounds good.  Once confirmed all is ok, now work in OpenShot and see if the audio plays ok as well.
