### ISSUE TITLE
Crash on Export

### ISSUE THREAD

**Issue by c-git** [OpenShot/openshot-qt#5003]
**Describe the bug:**
Application crashes when I try to export video. Not related to titles just used as example with no file dependencies.

**Steps to reproduce the behavior:**
1. Go to 'Title'
2. Click on 'Title'
3. Select any Title
4. Click Save
5. Add title to a track
6. Go to 'File'
7. Go down to 'Export Project'
8. Click on 'Export Video'
9. Click on 'Export Video'
10. App crashes

**Expected behavior:**
Exported video created.

**System Details:**
- OpenShot Version 2.6.1-dev: qt5 version: 5.9.5
- OpenShot-v2.6.1-dev-daily-10349-5aa9487e-46255e46-x86_64.AppImage
- Operating System / Distro: `Linux 5.15.0-53-generic #59-Ubuntu SMP Mon Oct 17 18:53:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Log Files:**
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/10053409/libopenshot.log)

**Exception / Stacktrace:**
Full console output [here](https://github.com/OpenShot/openshot-qt/files/10053447/ConsoleOutput.txt) and stack trace below.

Caught signal 11 (SIGSEGV)
---- Unhandled Exception: Stack Trace ----
  /lib/x86_64-linux-gnu/libc.so.6 ( __strdup                                  + 0x13  )  [0x7f8165680603]
  /tmp/.mount_d1Imgl/usr/bin/libx264.so.164 (                                           + 0x5d6b)  [0x7f8134005d6b]
  /tmp/.mount_d1Imgl/usr/bin/libx264.so.164 (                                           + 0x8e313)  [0x7f813408e313]
  /tmp/.mount_d1Imgl/usr/bin/libx264.so.164 ( x264_encoder_open_164                     + 0x179 )  [0x7f813400b339]
  /tmp/.mount_d1Imgl/usr/bin/libavcodec.so.58 (                                           + 0xb66fd)  [0x7f813a4b66fd]
  /tmp/.mount_d1Imgl/usr/bin/libavcodec.so.58 ( avcodec_open2                             + 0x88e )  [0x7f813a5cbeae]
  /tmp/.mount_d1Imgl/usr/bin/libopenshot.so.22 ( openshot::FFmpegWriter::open_video(AVFormatContext*, AVStream*)  + 0x402 )  [0x7f8119ac4aa2]
  /tmp/.mount_d1Imgl/usr/bin/libopenshot.so.22 ( openshot::FFmpegWriter::Open()            + 0x3e  )  [0x7f8119ac9fce]
  /tmp/.mount_d1Imgl/usr/bin/lib/_openshot.so (                                           + 0x71288)  [0x7f811a071288]
  /tmp/.mount_d1Imgl/usr/bin/libpython3.6m.so.1.0 ( PyCFunction_Call                          + 0xc1  )  [0x7f8165a13761]
  /tmp/.mount_d1Imgl/usr/bin/libpython3.6m.so.1.0 ( _PyEval_EvalFrameDefault                  + 0x76e0)  [0x7f8165984b20]
  /tmp/.mount_d1Imgl/usr/bin/libpython3.6m.so.1.0 (                                           + 0x17ba0f)  [0x7f816597ba0f]
  /tmp/.mount_d1Imgl/usr/bin/libpython3.6m.so.1.0 (                                           + 0x17c0fc)  [0x7f816597c0fc]
  /tmp/.mount_d1Imgl/usr/bin/libpython3.6m.so.1.0 ( _PyEval_EvalFrameDefault                  + 0x4ec3)  [0x7f8165982303]
  /tmp/.mount_d1Imgl/usr/bin/libpython3.6m.so.1.0 (                                           + 0x17ba0f)  [0x7f816597ba0f]
  /tmp/.mount_d1Imgl/usr/bin/libpython3.6m.so.1.0 ( _PyFunction_FastCallDict                  + 0x1e4 )  [0x7f816597bd34]
  /tmp/.mount_d1Imgl/usr/bin/libpython3.6m.so.1.0 ( _PyObject_FastCallDict                    + 0x131 )  [0x7f8165a66fd1]
  /tmp/.mount_d1Imgl/usr/bin/libpython3.6m.so.1.0 ( _PyObject_Call_Prepend                    + 0xcd  )  [0x7f8165a676fd]
  /tmp/.mount_d1Imgl/usr/bin/libpython3.6m.so.1.0 ( PyObject_Call                             + 0x48  )  [0x7f8165a67768]
  /tmp/.mount_d1Imgl/usr/bin/lib/PyQt5/QtCore.cpython-36m-x86_64-linux-gnu.so (                                           + 0x1efc30)  [0x7f81649efc30]
  /tmp/.mount_d1Imgl/usr/bin/lib/PyQt5/QtCore.cpython-36m-x86_64-linux-gnu.so (                                           + 0x1f0108)  [0x7f81649f0108]
  /tmp/.mount_d1Imgl/usr/bin/lib/PyQt5/QtCore.cpython-36m-x86_64-linux-gnu.so (                                           + 0x1f0390)  [0x7f81649f0390]
  /tmp/.mount_d1Imgl/usr/bin/lib/PyQt5/QtCore.cpython-36m-x86_64-linux-gnu.so (                                           + 0x1f0d07)  [0x7f81649f0d07]
  /tmp/.mount_d1Imgl/usr/bin/libQt5Core.so.5 ( QMetaObject::activate(QObject*, int, int, void**)  + 0x929 )  [0x7f81642b95e9]
  /tmp/.mount_d1Imgl/usr/bin/libQt5Widgets.so.5 (                                           + 0x2e6660)  [0x7f815f8e6660]
  /tmp/.mount_d1Imgl/usr/bin/libQt5Core.so.5 ( QMetaObject::activate(QObject*, int, int, void**)  + 0x865 )  [0x7f81642b9525]
  /tmp/.mount_d1Imgl/usr/bin/libQt5Widgets.so.5 ( QAbstractButton::clicked(bool)            + 0x42  )  [0x7f815f845b12]
  /tmp/.mount_d1Imgl/usr/bin/libQt5Widgets.so.5 (                                           + 0x245d2a)  [0x7f815f845d2a]
  /tmp/.mount_d1Imgl/usr/bin/libQt5Widgets.so.5 (                                           + 0x24710a)  [0x7f815f84710a]
  /tmp/.mount_d1Imgl/usr/bin/libQt5Widgets.so.5 ( QAbstractButton::mouseReleaseEvent(QMouseEvent*)  + 0xfd  )  [0x7f815f8472fd]
  /tmp/.mount_d1Imgl/usr/bin/lib/PyQt5/QtWidgets.cpython-36m-x86_64-linux-gnu.so (                                           + 0x3599a3)  [0x7f81603599a3]
  /tmp/.mount_d1Imgl/usr/bin/libQt5Widgets.so.5 ( QWidget::event(QEvent*)                   + 0x1f8 )  [0x7f815f793038]
  /tmp/.mount_d1Imgl/usr/bin/lib/PyQt5/QtWidgets.cpython-36m-x86_64-linux-gnu.so (                                           + 0x35af93)  [0x7f816035af93]
  /tmp/.mount_d1Imgl/usr/bin/libQt5Widgets.so.5 ( QApplicationPrivate::notify_helper(QObject*, QEvent*)  + 0x9c  )  [0x7f815f75483c]
  /tmp/.mount_d1Imgl/usr/bin/libQt5Widgets.so.5 ( QApplication::notify(QObject*, QEvent*)   + 0x7ff )  [0x7f815f75c65f]
  /tmp/.mount_d1Imgl/usr/bin/lib/PyQt5/QtWidgets.cpython-36m-x86_64-linux-gnu.so (                                           + 0x3ab97e)  [0x7f81603ab97e]
  /tmp/.mount_d1Imgl/usr/bin/libQt5Core.so.5 ( QCoreApplication::notifyInternal2(QObject*, QEvent*)  + 0x118 )  [0x7f816428a8a8]
  /tmp/.mount_d1Imgl/usr/bin/libQt5Widgets.so.5 ( QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool)  + 0x1d2 )  [0x7f815f75b632]
  /tmp/.mount_d1Imgl/usr/bin/libQt5Widgets.so.5 (                                           + 0x1ae15b)  [0x7f815f7ae15b]
  /tmp/.mount_d1Imgl/usr/bin/libQt5Widgets.so.5 (                                           + 0x1b07ca)  [0x7f815f7b07ca]
  /tmp/.mount_d1Imgl/usr/bin/libQt5Widgets.so.5 ( QApplicationPrivate::notify_helper(QObject*, QEvent*)  + 0x9c  )  [0x7f815f75483c]
  /tmp/.mount_d1Imgl/usr/bin/libQt5Widgets.so.5 ( QApplication::notify(QObject*, QEvent*)   + 0x2a4 )  [0x7f815f75c104]
  /tmp/.mount_d1Imgl/usr/bin/lib/PyQt5/QtWidgets.cpython-36m-x86_64-linux-gnu.so (                                           + 0x3ab97e)  [0x7f81603ab97e]
  /tmp/.mount_d1Imgl/usr/bin/libQt5Core.so.5 ( QCoreApplication::notifyInternal2(QObject*, QEvent*)  + 0x118 )  [0x7f816428a8a8]
  /tmp/.mount_d1Imgl/usr/bin/libQt5Gui.so.5 ( QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*)  + 0x70b )  [0x7f815ef015eb]
  /tmp/.mount_d1Imgl/usr/bin/libQt5Gui.so.5 ( QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*)  + 0x135 )  [0x7f815ef030b5]
  /tmp/.mount_d1Imgl/usr/bin/libQt5Gui.so.5 ( QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>)  + 0xab  )  [0x7f815eeda33b]
  /tmp/.mount_d1Imgl/usr/bin/libQt5XcbQpa.so.5 (                                           + 0x9f260)  [0x7f812e09f260]
  /tmp/.mount_d1Imgl/usr/bin/libglib-2.0.so.0 ( g_main_context_dispatch                   + 0x2e7 )  [0x7f8162c4c537]
  /tmp/.mount_d1Imgl/usr/bin/libglib-2.0.so.0 (                                           + 0x4c770)  [0x7f8162c4c770]
  /tmp/.mount_d1Imgl/usr/bin/libglib-2.0.so.0 ( g_main_context_iteration                  + 0x2c  )  [0x7f8162c4c7fc]
  /tmp/.mount_d1Imgl/usr/bin/libQt5Core.so.5 ( QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>)  + 0x5f  )  [0x7f81642e385f]
  /tmp/.mount_d1Imgl/usr/bin/libQt5Core.so.5 ( QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>)  + 0x13a )  [0x7f81642888da]
  /tmp/.mount_d1Imgl/usr/bin/libQt5Widgets.so.5 ( QDialog::exec()                           + 0x207 )  [0x7f815f93eed7]
  /tmp/.mount_d1Imgl/usr/bin/lib/PyQt5/QtWidgets.cpython-36m-x86_64-linux-gnu.so (                                           + 0x38df77)  [0x7f816038df77]
  /tmp/.mount_d1Imgl/usr/bin/libpython3.6m.so.1.0 ( _PyCFunction_FastCallDict                 + 0x1bb )  [0x7f8165a1353b]
  /tmp/.mount_d1Imgl/usr/bin/libpython3.6m.so.1.0 (                                           + 0x17c1ec)  [0x7f816597c1ec]
  /tmp/.mount_d1Imgl/usr/bin/libpython3.6m.so.1.0 ( _PyEval_EvalFrameDefault                  + 0x4ec3)  [0x7f8165982303]
  /tmp/.mount_d1Imgl/usr/bin/libpython3.6m.so.1.0 (                                           + 0x17ba0f)  [0x7f816597ba0f]
  /tmp/.mount_d1Imgl/usr/bin/libpython3.6m.so.1.0 ( _PyFunction_FastCallDict                  + 0x1e4 )  [0x7f816597bd34]
---- End of Stack Trace ----
**Screenshots:** (Optional)
N/A

**Comment by c-git** [comment]
Is there a known working version on Ubuntu?

**Comment by VanackSabbadium** [comment]
I found out that this happens with a version of OpenShot newer than this one:

OpenShot-v2.6.1-dev-daily-10243-854a3aa3-46255e46-x86_64

With this one i can export any video without issues.

**Comment by Colorjet3** [comment]
Hell @VanackSabbadium That is great that you have it working.  Many fixes are making it into the Daily Builds.  Revisit often to download the latest DEV Daily Build.

More importantly, keep an eye on an upcoming production release just around the corner.

**Comment by VanackSabbadium** [comment]
Of course @colorjet3, it's a regression bug. I'll keep an eye on future releases!

**Comment by c-git** [comment]
I don't seem to have put the version I was using in my original post it was the most recent daily build `OpenShot-v2.6.1-dev-daily-10349-5aa9487e-46255e46-x86_64.AppImage` I've updated the post with the version and I noticed there is a newer one available today. I will try it later and report back.

**Comment by c-git** [comment]
The problem still exists in the most recent build from today, `OpenShot-v2.6.1-dev-daily-10387-bcd54c02-46255e46-x86_64.AppImage`.

> I found out that this happens with a version of OpenShot newer than this one:
> 
> OpenShot-v2.6.1-dev-daily-10243-854a3aa3-46255e46-x86_64
> 
> With this one i can export any video without issues.


Thank you very much @VanackSabbadium really appreciate it, that one works for me.

**Comment by Colorjet3** [comment]
I also confirmed that this exists in v2.6.1-dev-daily-10387-..... published on 11/24/22.  I will get the attention of the development team to get this resolved.

**Comment by fufesou** [comment]
Ubuntu 20.04, Python 3.8.10.

It may be the same problem. The invalid `NaN` array causes exporting failure.
I've tested `ExtractSamples` in `libopenshot`, but it seems fine.

![image](https://user-images.githubusercontent.com/13586388/204129506-13e29a8e-0010-4b64-9483-bbc60e8c652d.png)

**Comment by fufesou** [comment]
![image](https://user-images.githubusercontent.com/13586388/204131350-e32d158e-4da9-4722-8ae4-dffba5d3478a.png)


``` Python
PYTHONPATH=./build/bindings/python python3

import openshot

r = openshot.FFmpegReader("./examples/test.mp4")
r.Open()

waveformer = openshot.AudioWaveformer(r)
file_audio_data = waveformer.ExtractSamples(-1, 20, True)
samples_vectors = file_audio_data.vectors()
samples_vectors
```

**Comment by Colorjet3** [comment]
Please go to openshot.org and download the production Release-Candidate version (AppImage) and give it a try.

**Comment by c-git** [comment]
Will try to test at my soonest available opportunity

**Comment by c-git** [comment]
Confirmed to be working on export now.

**Comment by Colorjet3** [comment]
Awesome and thank you for the fyi!

**Comment by c-git** [comment]
Very welcome and thank you very much for all the work you guys do on this project.

**Comment by VanackSabbadium** [comment]
I tested the newest daily build, and it works without issues.
Thank you so much for your amazing work!

**Comment by Colorjet3** [comment]
That is awesome @VanackSabbadium and thank you for the feedback.
