### ISSUE TITLE
Incomplete save of project: files' tags are not recorded

### ISSUE THREAD

**Issue by Madpentiste** [OpenShot/openshot-qt#5005]
**Describe the bug:**
In the project's files widow, there is a column labelled "Tags" ("Balise" in French), in which the user can type something. Whatever the user types there is not saved when the project is saved.
This is a regression: it did not happen in 1.x versions.

**Steps to reproduce the behaviour:**
1. Open a project that contains video/photo/sound files
2. In the "Project's files" window, select any file
3. Double click in the "Tags" column of that file: a cursor will appear
4. Type anything in there, and hit the return key
5. Save the project and quit
6. Reopen the project 
7. In the "Project's files" window, look for the file you had chosen at step 2: whatever you had typed at step 5 is missing.

**Expected behavior:**
At step 7 above, one should retrieve whatever was typed at step 4

**System Details:**
- OpenShot Version 2.6.1 (appimage) - French version
- Operating System / Distro: Ubuntu 20.04

**Comment by Colorjet3** [comment]
Hello @Madpentiste .  I was able to replicate this issue in the English version as well.  I have opened up an internal Bug for this to be worked on sometime in the future.  For now, I found a way that you can still save the tags.

1.  Open your project.
2.  Right click on a file in the Preview Window.
3.  Select File Properties.  It doesn't matter if you are in Detail View or Thumbnail view.
4. Find the Tags field and type what you need.
5. Click on Update.
6. Save your project and reopen it.
7. Right click in the Preview Window  and select Detail View.
8. You should now see the tags you keyed.  You should also be able to search on those tags.

**Comment by Colorjet3** [comment]
Hello @Madpentiste This has been fixed in the latest DEV Daily Build.  If you want to test it, go to openshot.org/download/#daily and download the latest AppImage.
