### ISSUE TITLE
French translation of "tag": inconsistancy creating confusion

### ISSUE THREAD

**Issue by Madpentiste** [OpenShot/openshot-qt#5006]
**Describe the bug:**

The user can give tags to his/her project's files, but this is translated into "Etiquette" in the "File properties" pop-up window, and into "Balise" in the detailed view of project's files window, making the user believe that these are two different features/attributes/properties. 

**Steps to reproduce the behavior:**
1. Open a project in a French version of OpenShot
2. In the project's files window, right click on a file and select "Propriétés du fichier" in the pop-up window
3. In the "Propriétés du fichier" window, the second field is called "
4. Go back to the project's files window, and select the detail view if needed
5. The right column is labelled "Balises", although it (rightfully) displays the same attribute (if the file has any) as "Étiquettes"

**Expected behavior:**

Since "Étiquettes" and "Balises" refer to the same attribute, it should be labelled identically on any relevant window

**System Details:**
- OpenShot Version [e.g. 2.4.3]:  2.6.1 AppImage
- Operating System / Distro: Ubuntu 20.04
- 

**Screenshots:** (Optional)

![OpenShot fr-FR Etiquettes](https://user-images.githubusercontent.com/36817897/204262082-ffcd7c0f-9d93-4bcf-866a-2ce448de5add.jpg)
![OpenShot fr-FR Balises](https://user-images.githubusercontent.com/36817897/204262077-642c7d13-31a9-4554-ba8f-a72b97058fe1.jpg)"

**Comment by Colorjet3** [comment]
Hello @Madpentiste Thank you for bringing this to our attention.  An Enhancement request has been submitted to make the translation of Tags consistent in both the Project Files (details view) and when you select File Properties from the Project Files window.

**Comment by Colorjet3** [comment]
Hello @Madpentiste .  You should see this change in one of the latest DEV Daily Builds.  go to openshot.org/download/#build and get the latest DEV Daily Build.
