### ISSUE TITLE
Se cierra al aplicar efectos como acelerar el timpo.

### ISSUE THREAD

**Issue by cristg12** [OpenShot/openshot-qt#501]
Estoy haciendo un trabajo y necesito adelantar el timepo del video pero Openshot se me cierra.
Que hago?

**Comment by jreynojustin** [comment]
Disculpas como mi español es pobre. ¿Podría proporcionar un rastro de la pila del accidente?

**Comment by jonoomph** [comment]
Please include the following details:
OS: 
OpenShot Version: 
Please attach log files if crashing

Please reopen this issue once you have included the above details. Thanks!
