### ISSUE TITLE
Openshot not working monterey 12

### ISSUE THREAD

**Issue by dolfandds** [OpenShot/openshot-qt#5013]
**Describe the bug:**
App doesn't Start

**Steps to reproduce the behavior:**
1. Start App
2. See nothing Happen (The Bug)

**Expected behavior:**
App Start

**System Details:**
- OpenShot 2.6.1
- Operating System MacBook Pro with Monterey 12 (Latest Version Currently)

**Log Files:**
How Am I supposed to know  not even an error message appears!

**Exception / Stacktrace:**
NOT POSSIBLE How do I know if I did I would've solved it by now!

**Screenshots:** (Optional)
My Screenvideo: Clicks OpenShot from the dock OpenShot Icon bounces... next... ERR Window did not open.

**Comment by dolfandds** [comment]
PLZ help me with this I've downloaded the MOST RECENT version of OpenShot and It just will NOT work!

**Comment by Colorjet3** [comment]
v2.6.1 does not work in Monterey.  Please download the latest DEV Daily Build from openshot.org/download/#daily and give it a try.

**Comment by dolfandds** [comment]
THX

**Comment by dolfandds** [comment]
(Thanks)

**Comment by Colorjet3** [comment]
Hello @dolfandds Did the latest daily build work?  I just want to be sure before I close this ticket.

**Comment by dolfandds** [comment]
It did work.
