### ISSUE TITLE
unexpectedly closes while playing project

### ISSUE THREAD

**Issue by yahyahameed** [OpenShot/openshot-qt#5019]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**
1. Open a saved project
2. Play
3. Suddenly window is closed after playing for sometime
4. No error message shown

**Expected behavior**
Expected the video to play till end

**System Details**
- OpenShot Version: 3.0.0
- libopenshot Version:  0.3.0
- Platform: Windows-10-10.0.22000
- Processor: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.0.0-release-candidate-10627-264205da-ba27794b-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/by0imd5qstn21wnzclctumcnjxdkg5t9/openshot-qt.zip) (596 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/by0imd5qstn21wnzclctumcnjxdkg5t9/libopenshot.zip) (19984 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
Hello @yahyahameed .

1.  Can you please elaborate on "Suddenly closes after playing some time"?   How long, approximately, and is it repeatable?  If it is repeatable, can you tell which clip on a track the playhead is at the time Openshot crashes?
2. How much RAM do you have in your device?
3. How much free disk space do you have?
4. Is this the first time you used OpenShot or did you install on top of a previous version?  If you installed over a previous version, please do the following:
a.  Close Openshot
b.  Make a backup of c:\users\username\.openshot_qt folder.  The entire folder.
c.  Delete c:\users\username\.openshot_qt folder.
d. Start OpenShot and open your project.
e.  Play and see if the crash happens again.
5.  Have you performed a health check in your Windows 10 environment?  Ensure you have all the latest Microsoft updates, updated drivers, most importantly your display driver.

Meanwhile, we'll look at your log files.

**Update:** what is your hardware (laptop, computer, etc?).

**Comment by Colorjet3** [comment]
Please make this change right away in OpenShot. Go to Edit | Preference | Preview tab and change the audio sample rate from 44100 to 48000.  Restart OpenShot.  This setting will match your Windows 10 default audio sample rate.  Might not be the culprit but it can cause other audio issues if not matched.

**Comment by jonoomph** [comment]
@yahyahameed Are you able to reproduce this crash reliably? If so, does it crash in the same place each time? We will need more info in order to help identify and fix the issue.
