### ISSUE TITLE
After install version 3 candidate, Edit preferences crashes OpenShot

### ISSUE THREAD

**Issue by colbec** [OpenShot/openshot-qt#5020]
**Describe the bug:**
On Linux openSUSE Leap 15.4 X11 windowing, Edit Preferences crashes OpenShot

Edit preferences used to work fine in previous versions, but after running a version 3 candidate, edit preferences crashes my previous 2.6.1 versions as well.

**Steps to reproduce the behavior:**
1. Go to Edit
2. Click on Preferences

**Expected behavior:**
Preferences window opens

**System Details:**
- OpenShot Version 10629
- Operating System / Distro: Linux openSUSE Leap 15.4 X11 windowing

**Log Files:**

[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/10148384/libopenshot.log)

**Comment by Colorjet3** [comment]
1. Make sure OpenShot is not running
2. Please backup your ~/.openshot_qt folder.
3. Now delete ~/.openshot_qt folder.
4. Start Openshot and try again.

**Comment by colbec** [comment]
Thanks for the offer of help.

I followed your instructions twice and each time on restart OpenShot I get a message offering me a tutorial, I dismiss this and OpenShot opens normally. I then try Edit Preferences again and OpenShot crashes again.

**Comment by Colorjet3** [comment]
Sorry to hear that didn't resolve the issue.  

Let's enable verbose logging so we can have you upload your log files in hopes that they reveal the issue.  In order to enable Verbose logging we need to get into Edit | Preferences.  Since this causes OpenShot to crash we will do it manually.

1.  Close OpenShot.
2.  Go to ~/openshot_qt folder.
3. Find Openshot.settings file and make a backup of it, just in case.
4.  Edit openshot.settings.  Be very careful about what you change in here.
5.  Search for "Verbose".
6. You should find a line that looks like this "title": "Debug Mode (Verbose)",
7. Right above this line you will see "value:" false,
8. Carefully modify false to true.  make sure you type it in lower case.
9. Save openshot.settings and exit the editor.
10. In .openshot_qt folder find and delete these two log files (libopenshot.log & openshot-qt.log).
11. Start OpenShot and try Edit | Preferences.
12. After the crash, please share those two log files so we an analyze them.

**Comment by colbec** [comment]
OK, as expected it crashed again but created these two files:
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/10149503/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/10149504/openshot-qt.log)

**Comment by Colorjet3** [comment]
Thank you @colbec for the log files.  It looks like something to do with hardware acceleration checking by OpenShot.  I am not a developer and going to ask one of the DEV team members to look into this.

**Comment by colbec** [comment]
FYI I have `glxinfo` installed and it reports that 

```
name of display: :1
display: :1  screen: 0
direct rendering: Yes
server glx vendor string: SGI
server glx version string: 1.4
```

but there is no dedicated graphics card on this machine.

**Comment by evalero** [comment]
Hi everyone.

I have the same problem but I have managed to solve it with the following workaround. Check if it works to you @colbec 

In a terminal, remove the packages installed using apt

```

sudo apt remove openshot-qt python3-openshot

``` 

In same terminal, download the AppImage,  make it executable and execute the program:

``` 
wget https://github.com/OpenShot/openshot-qt/releases/download/v2.6.1/OpenShot-v2.6.1-x86_64.AppImage -O Openshot.AppImage
chmod +x Openshot.AppImage
./Openshot.AppImage

```

Now, you will be able to open preferences menu (or at least I has able to do it)

**Comment by colbec** [comment]
Thanks @evalero for the suggestion. I am already running an AppImage, and I am sure that if I were to completely strip my machine of all OpenShot 3 programs and support files I could restore a fresh 2.6.1 version from my collection of old images, some of which were working well.

My intention in reporting the problem and maintaining my current situation, even if broken, is to try to help the devs eliminate problems at the candidate level before the final version is released. I do not use the edit preferences option very often so it is not a big problem for me not to be able to use it.

**Comment by jonoomph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GPU detection crashes preferences window](https://trello.com/c/VM4avQTc/159-gpu-detection-crashes-preferences-window)

**Comment by jonoomph** [comment]
@colbec I have made some improvements to the Preferences screen initialization, to no longer test for graphic card support. Instead, I've added a **Test** button to the `Performance` tab, to allow a user to manually invoke the hardware acceleration testing. 

This will accomplish 3 things:
- No more crashes on launch of Preferences screen
- Faster launching of Preferences screen
- Advanced users can still experiment with hardware acceleration, and it might still crash with invalid settings, but this seems much safer to make the user click a "Test" button first.

![OpenShot-Preferences-Test-Button](https://user-images.githubusercontent.com/5551883/205755382-77764ccc-29cd-45e4-adc4-33a8569b9ebf.png)

NOTE: You should find a new release candidate here: https://www.openshot.org/download/#daily. I'm closing this ticket for now, but please re-open if you still experience a crash on launch of Preferences.

**Comment by colbec** [comment]
Thanks for this, I can confirm that the preferences window opens properly in 10638. I have to be careful not to select VDPAU and try to test this since it immediately crashes OpenShot as before.

**Comment by jonoomph** [comment]
Interesting! Thanks for verifying the fix, and now we know that VDPAU crashes on some systems!  On my system however, VDPAU works fine, but does not improve decoding performance much when compared to my CPU - almost identical performance. However, NVENC encoding does in fact make a large performance difference, compared to CPU encoding, when rendering videos.

**Comment by Colorjet3** [comment]
This is in the queue to be fixed in a future release (no ETA at this time).
