### ISSUE TITLE
cannot upload file to openshot it crashes every time

### ISSUE THREAD

**Issue by kingcole18** [OpenShot/openshot-qt#5024]
**Describe the bug:**

**Steps to reproduce the behavior:**

**Expected behavior:**

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
Hello @kingcole18 .  You are not providing enough information for us to help you with.  I am going to assume that when you say "upload" you mean "importing".  Importing using File manager, or clicking on the + import icon from the main menu.

If this is the case, please provide the following:
1.  what version of OpenShot are you running (Help | About Openshot).  Provide all the details you see on this screen.
2. what operating system are you running (Linux, Windows, Mac?)  Also, which version of the operating system.
3. Please tell us exactly how you are trying to "Import".  Again, I am assuming you are trying to import vs. upload.
