### ISSUE TITLE
Start and crash (Windows 8)

### ISSUE THREAD

**Issue by erwinlr** [OpenShot/openshot-qt#5025]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 2.6.1-dev
- libopenshot Version:  0.2.8-dev
- Platform: Windows-8.1-6.3.9600
- Processor: AMD64 Family 21 Model 48 Stepping 1, AuthenticAMD
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.0.0-release-candidate-10644-264205da-ba27794b-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/vqhzmlw38i2erl5fyoxm9hhv7xz5j211/openshot-qt.zip) (9 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/vqhzmlw38i2erl5fyoxm9hhv7xz5j211/libopenshot.zip) (12 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
1. What version did you start with before you dowloaded build #10644?
2. Try this:
- uninstall using Add or Remove programs.
- backup c:\users\username\.openshot_qt folder.
- delete c:\users\username\.openshot_qt folder.
- install build 10644
- Did this work?

**Comment by erwinlr** [comment]
erase everything and install v3,0,0  RC10676,  and crash again
Log included

*Erwin López Rei, MA, PPNL, TAP*
Psicología, Coaching & Consultoría
***@***.*** *
Coach Profesional Certificado de Vida, Ejecutivo & Organizacional
Practitioner en: Prog Neurolinguística, Neuroeducación y Análisis
Transaccional

Psicólogo, especializado en Matrimonio y Familia
Diplomado en Logoterapia
Facilitador INFOTEP

Armonía Vital
Psicología, Coaching, PNL & Desarrollo Humano

e: ***@***.*** ***@***.***>
Tel. 849-350-1216   809-350-1216

Síguenos en Facebook:  http://www.facebook.com/erwinlopezrei
<http://www.facebook.com/ErwinLopezRei>

Instagram:  http://www.instagram.com/erwinlopezrei
<http://www.facebook.com/ErwinLopezRei>

Linkedin   https://www.linkedin.com/in/erwinlopezrei
<https://www.linkedin.com/in/erwinlopezrei?trk=hp-identity-name>

**Comment by Colorjet3** [comment]
Sorry to hear that.  Let's enable Verbose logging so we can get more information regarding the crash.

1.  go to c:\users\username\.openshot_qt folder.
2.  make a backup of openshot.settings.
3.  Edit openshot.settings.
4. Search for "Verbose" excluding the quotes.
5. Right above the "title": "Debug Mode (Verbose)", you will find "value": false,
6. Change false to true
7.  save openshot.settings.
8. start OpenShot and after the crash please upload your log files again (libopenshot.log & openshot-qt.log)

**Comment by erwinlr** [comment]
*Erwin López Rei, MA, PPNL, TAP*
Psicología, Coaching & Consultoría
***@***.*** *
Coach Profesional Certificado de Vida, Ejecutivo & Organizacional
Practitioner en: Prog Neurolinguística, Neuroeducación y Análisis
Transaccional

Psicólogo, especializado en Matrimonio y Familia
Diplomado en Logoterapia
Facilitador INFOTEP

Armonía Vital
Psicología, Coaching, PNL & Desarrollo Humano

e: ***@***.*** ***@***.***>
Tel. 849-350-1216   809-350-1216

Síguenos en Facebook:  http://www.facebook.com/erwinlopezrei
<http://www.facebook.com/ErwinLopezRei>

Instagram:  http://www.instagram.com/erwinlopezrei
<http://www.facebook.com/ErwinLopezRei>

Linkedin   https://www.linkedin.com/in/erwinlopezrei
<https://www.linkedin.com/in/erwinlopezrei?trk=hp-identity-name>

**Comment by jonoomph** [comment]
Thanks for the bug report @erwinlr. As @Colorjet3 mentioned, we need you to enable verbose debug, install the official 3.0 release (https://github.com/OpenShot/openshot-qt/releases/download/v3.0.0/OpenShot-v3.0.0-x86_64.exe), delete your `.openshot_qt` folder, and try again to crash OpenShot. This will hopefully produce log files with more useful info that we can use to troubleshoot this problem.

It is also possible that something inside your Windows home folder is corrupt (or permission errors) etc... So it might be an interesting test to create a new local Windows user, login as them, and then install OpenShot 3.0. Hope that helps.

**Comment by erwinlr** [comment]
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/10208973/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/10208975/openshot-qt.log)

Install official 3.0  and crash

**Comment by erwinlr** [comment]
Official version 3.0
crash again

This part is making noise to me:
INFO preview_thread: Detected default audio device sample rate: 0
10:35:36 WARNING preview_thread: Your sample rate (0) does not match
OpenShot (48000). This can potentially play audio too fast/slow if not
fixed. Adjust your 'Preferences->Preview->Default Sample Rate to match your
system rate: 0, and restart OpenShot.

*Erwin López Rei, MA, PPNL, TAP*

**Comment by Colorjet3** [comment]
Hello @erwinlr .  We need Verbose logging enabled to capture more information in regards to your crash issue.  Additionally, the warning regarding the Default Audio Sample rate should not be causing the crash.  It does cause other issues with audio while previewing though.

Please do this to enable verbose logging:
1.  Ensure OpenShot is not running.
2.  Make a backup of your c:\users\username\.openshot_qt\openshot.settings file.
3.  Edit openshot.settings file.
4.  From top of this file search for "Verbose".
5.  Right above this line you will find this:  ("value": false,)  Change the false to true (maintain lowercase) and ensure you don't change anything else.
6.  Save the file and close it.
7.  Start it OpenShot.
8.  If/when it crashes share your log files.

After you do this let's go back into openshot.setting file and change the sample rate.
1.  Repeat steps 1-3 above.
2.  From the top of this file search for "sample".
3.  A few lines below you will find this:  ("value": 44100,)  Change 44100 to 48000.  Ensure you don't make any other changes.
4.  Save the file and exit.
5.  Start OpenShot.

**Comment by erwinlr** [comment]
Crash again

**Comment by Colorjet3** [comment]
Did you enable Verbose logging per the instructions above?  If yes, please share your log files.

**Comment by erwinlr** [comment]
Yes. Check attachment

**Comment by Colorjet3** [comment]
The log files just aren't looking like Verbose logging is enabled.  Without seeing that it is going to be difficult to diagnose your issue.

One question:  After you enabled the Verbose logging, did OpenShot complain that something was not right with the openshot.settings file or it just crashed upon startup?

**Comment by erwinlr** [comment]
verbose true
Default Audio Sample Rate  48000

Start and crash
i run twice

**Comment by erwinlr** [comment]
15:40:12 INFO main_window: InitCacheSettings
15:40:12 INFO main_window: cache-mode: CacheMemory
15:40:12 INFO main_window: cache-limit-mb: 2048
15:40:12 INFO main_window: cache-ahead-percent: 0.7
15:40:12 INFO main_window: cache-preroll-min-frames: 24
15:40:12 INFO main_window: cache-preroll-max-frames: 48
15:40:12 INFO main_window: cache-max-frames: 600
15:40:12 INFO main_window: Creating CacheMemory object with 2147483648 byte limit
15:40:12 INFO preview_thread: QThread Start Method Invoked
15:40:12 ERROR main_window: Unhandled crash detected: -windows-VideoPlaybackThread::run (before render) 

i incremented cache-limit-mb from 512 to 2048 and now crash latter in this point

Any idea what happening?

**Comment by Colorjet3** [comment]
Not yet.  I am running out of ideas as to what it can be.

Try one more thing:
1.  Go to Control Panel
2.  Select Programs | Programs and Features.  Like you are going to uninstall an application.
3. When you click on "Programs and Features" do you only see one instance of OpenShot installed or two?
4. If you see two instances, please uninstall both of them.
5. Then, perform a clean installation of v.3.0.0 using these instructions:   https://github.com/OpenShot/openshot-qt/wiki/Clean-Installation-of-OpenShot

**Comment by erwinlr** [comment]
After OpenShot-v3.0.0-daily-10786 (Dec 19), is working fine without crashing.  Also audio when playing videos is working well.

**Comment by Colorjet3** [comment]
That is awesome and thank you so much for the confirmation!
