### ISSUE TITLE
Can't Edit Title Text After Saving it

### ISSUE THREAD

**Issue by Maxop1** [OpenShot/openshot-qt#5026]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**
1. Go to Project Files
2. Right click Title file
3. Select Edit Title
4. See error: Error: nothing happens Text Editor will not open at all.

**Expected behavior**
Expecting to see it opens and allow me to edit Title

**System Details**
- OpenShot Version: 3.0.0
- libopenshot Version:  0.3.0
- Platform: Windows-10-10.0.22000
- Processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.0.0-release-candidate-10644-264205da-ba27794b-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/8938nfclf5j0a8bg3isht60402eb3ts4/openshot-qt.zip) (7 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/8938nfclf5j0a8bg3isht60402eb3ts4/libopenshot.zip) (1 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
I just tested with build 10644 and it worked for me.  Please provide some information regarding the steps you are performing so we can better understand the issue and provide a quicker solution.

**Comment by Maxop1** [comment]
Hi Colorjet3 thank you so much for looking into this. i try to replicate the problem to give you step by step instructions on how its happening. i found that it's not happening to all titles, I mostly found that you can not edit Title when the text in the title are long, with specific colors, in some cases after save the file you can not edit it anymore. Please check the openshot project attach here this is one of the good example. I was able to edit this file many times, after i export this file to video, then i go back trying to edit its not happening. When i right click on the file and select edit nothing happens. I attach it here for you to see. This is exactly what is happening. I hope this will help you understand my problem. Thanks
[Cant Edit Title Test Sample.zip](https://github.com/OpenShot/openshot-qt/files/10195310/Cant.Edit.Title.Test.Sample.zip)

**Comment by Colorjet3** [comment]
The two titles are missing in the assets folder.  If you tell me which Title templates you used and give me an idea of how long your text is and what colors you used I'll give it a try.

Just out of curiosity, are you right clicking and selecting File Properties in the "Project Files" window?

By the way, if you are not sure where your .svg files are located, all you have to do is right click on the title file in the "Project Files" window, select "File Properties", and check the File Path attribute.

**Comment by jonoomph** [comment]
@Maxop1 I don't see anything in your log files about the Title editor. If possible, it would be great if you can trigger the bug, and then attach the `/Users/USER/.openshot_qt/openshot_qt.log` file, and hopefully it contains an error message for us to dig into.
