### ISSUE TITLE
v3.0.0 crash at startup (Fedora 37)

### ISSUE THREAD

**Issue by aosan** [OpenShot/openshot-qt#5028]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**
1. Go to 'AppImage'
2. Click on 'chmod +x OpenShot.appimage'

Loaded modules from: /tmp/.mount_OpenSh4y1Yge/usr/bin
INFO app: ------------------------------------------------
INFO app:             Sun Dec 11 14:00:02 2022
INFO app:               Starting new session
ERROR app: OpenShotApp::Import Error
Traceback (most recent call last):
File "/tmp/.mount_OpenSh4y1Yge/usr/bin/classes/app.py", line 100, in __init__
from classes import settings, project_data, updates, sentry
File "/tmp/.mount_OpenSh4y1Yge/usr/bin/classes/project_data.py", line 48, in <module>
import openshot
File "<frozen zipimport>", line 259, in load_module
File "/home/gitlab-runner/builds/c8488186/0/OpenShot/openshot-qt/openshot.py", line 15, in <module>
ImportError: /tmp/.mount_OpenSh4y1Yge/usr/bin/libm.so.6: version `GLIBC_2.35' not found (required by /lib64/libcairo.so.2)
Traceback (most recent call last):
File "openshot_qt/launch.py", line 196, in main
app = OpenShotApp(argv)
File "/tmp/.mount_OpenSh4y1Yge/usr/bin/classes/app.py", line 100, in __init__
from classes import settings, project_data, updates, sentry
File "/tmp/.mount_OpenSh4y1Yge/usr/bin/classes/project_data.py", line 48, in <module>
import openshot
File "<frozen zipimport>", line 259, in load_module
File "/home/gitlab-runner/builds/c8488186/0/OpenShot/openshot-qt/openshot.py", line 15, in <module>
ImportError: /tmp/.mount_OpenSh4y1Yge/usr/bin/libm.so.6: version `GLIBC_2.35' not found (required by /lib64/libcairo.so.2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/cx_Freeze/initscripts/__startup__.py", line 40, in run
File "/usr/local/lib/python3.8/dist-packages/cx_Freeze/initscripts/Console.py", line 37, in run
File "openshot_qt/launch.py", line 223, in <module>
main()
File "openshot_qt/launch.py", line 198, in main
app.show_errors()
AttributeError: 'NoneType' object has no attribute 'show_errors'
INFO app:             OpenShot's session ended
INFO app:             Sun Dec 11 14:00:03 2022
INFO app: ================================================

**Expected behavior**
app startup without any blocking errors

**System Details**
- OpenShot Version: 3.0.0
- libopenshot Version:  libopenshot-0.3.0-1.fc37.x86_64
- Platform:Linux fedora 6.0.11-300.fc37.x86_64 fedora-37
- Processor: x86_64
- Machine: x86_64
- Python version: python3-3.11.0-1.fc37.x86_64
- Qt5 version: 5.15.7
- PyQt5 version: python3-qt5-5.15.6-9.fc37.x86_64
- Qt Detected Languages: ['en-AU']
- LANG Environment Variable: en_AU.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.0.0-daily-10695-89e4b1da-fab6e6ab-x86_64.AppImage

**Log Fi...
[daily_2022-12-11_v3.0.0_openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/10201422/daily_2022-12-11_v3.0.0_openshot-qt.log)

**Comment by ip1981** [comment]
Your host system is too old, namely glibc. Upgrade, or build and install regular RPMs, or just install from sources.

**Comment by jonoomph** [comment]
I will give fedora 37 a quick try, and see if we are missing a glibc dependency - since we actually package up some glibc libs to make our AppImage more compatible (in theory)

**Comment by jonoomph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fedora 37 does not run AppImage (.mount.../usr/bin/libm.so.6)](https://trello.com/c/f5cVtOnf/256-fedora-37-does-not-run-appimage-mount-usr-bin-libmso6)

**Comment by jonoomph** [comment]
@aosan A new daily build will be available in an hour or so with a fix: https://www.openshot.org/download/#daily - I have verified it works on Fedora 37, Ubuntu 22.04, Ubuntu 20.04, and a couple other distros. But if the distro is too old (more than 2 or 3 years) it will likely fail due to glibc.

**Comment by aosan** [comment]
> @aosan A new daily build will be available in an hour or so with a fix: https://www.openshot.org/download/#daily - I have verified it works on Fedora 37, Ubuntu 22.04, Ubuntu 20.04, and a couple other distros. But if the distro is too old (more than 2 or 3 years) it will likely fail due to glibc.

Thank you, looking forward to trying it!

**Comment by kemzops** [comment]
> **Describe the bug** A clear and concise description of the issue
> 
> **Steps to reproduce the behavior:**
> 
>     1. Go to 'AppImage'
> 
>     2. Click on 'chmod +x OpenShot.appimage'
> 
>     3. Scroll down to '....'
> 
>     4. See error
> 
> 
> Loaded modules from: /tmp/.mount_OpenSh4y1Yge/usr/bin INFO app: ------------------------------------------------ INFO app: Sun Dec 11 14:00:02 2022 INFO app: Starting new session ERROR app: OpenShotApp::Import Error Traceback (most recent call last): File "/tmp/.mount_OpenSh4y1Yge/usr/bin/classes/app.py", line 100, in **init** from classes import settings, project_data, updates, sentry File "/tmp/.mount_OpenSh4y1Yge/usr/bin/classes/project_data.py", line 48, in import openshot File "", line 259, in load_module File "/home/gitlab-runner/builds/c8488186/0/OpenShot/openshot-qt/openshot.py", line 15, in ImportError: /tmp/.mount_OpenSh4y1Yge/usr/bin/libm.so.6: version `GLIBC_2.35' not found (required by /lib64/libcairo.so.2) Traceback (most recent call last): File "openshot_qt/launch.py", line 196, in main app = OpenShotApp(argv) File "/tmp/.mount_OpenSh4y1Yge/usr/bin/classes/app.py", line 100, in __init__ from classes import settings, project_data, updates, sentry File "/tmp/.mount_OpenSh4y1Yge/usr/bin/classes/project_data.py", line 48, in <module> import openshot File "<frozen zipimport>", line 259, in load_module File "/home/gitlab-runner/builds/c8488186/0/OpenShot/openshot-qt/openshot.py", line 15, in <module> ImportError: /tmp/.mount_OpenSh4y1Yge/usr/bin/libm.so.6: version `GLIBC_2.35' not found (required by /lib64/libcairo.so.2)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/usr/local/lib/python3.8/dist-packages/cx_Freeze/initscripts/**startup**.py", line 40, in run File "/usr/local/lib/python3.8/dist-packages/cx_Freeze/initscripts/Console.py", line 37, in run File "openshot_qt/launch.py", line 223, in main() File "openshot_qt/launch.py", line 198, in main app.show_errors() AttributeError: 'NoneType' object has no attribute 'show_errors' INFO app: OpenShot's session ended INFO app: Sun Dec 11 14:00:03 2022 INFO app: ================================================
> 
> **Expected behavior** A clear and concise description of what you expected to happen. app startup without any blocking errors
> 
> **System Details**
> 
>     * OpenShot Version: 3.0.0
> 
>     * libopenshot Version:  libopenshot-0.3.0-1.fc37.x86_64
> 
>     * Platform:Linux fedora 6.0.11-300.fc37.x86_64 fedora-37
> 
>     * Processor: x86_64
> 
>     * Machine: x86_64
> 
>     * Python version: python3-3.11.0-1.fc37.x86_64
> 
>     * Qt5 version: 5.15.7
> 
>     * PyQt5 version: python3-qt5-5.15.6-9.fc37.x86_64
> 
>     * Qt Detected Languages: ['en-AU']
> 
>     * LANG Environment Variable: en_AU.UTF-8
> 
>     * LOCALE Environment Variable:
> 
>     * Daily Build: Verified issue still exists in daily build: [http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.0.0-daily-10695-89e4b1da-fab6e6ab-x86_64.AppImage](https://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.0.0-daily-10695-89e4b1da-fab6e6ab-x86_64.AppImage)
> 
> 
> **Log Fi... [daily_2022-12-11_v3.0.0_openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/10201422/daily_2022-12-11_v3.0.0_openshot-qt.log)

im having the same issue with the exact same output on fedora workstation 37... looking forward for solution. **ill give the daily build a try**

**Comment by kemzops** [comment]
Daily Build Installer | Date
-- | --
OpenShot-v3.0.0-daily-10873-99aab0a1-f55ec5d0-x86_64.AppImage | Dec. 22, 2022, 5 a.m.

**The Daily Build Worked Without Any Issues At All, Thanks.**

**Comment by Colorjet3** [comment]
Awesome and thank you for the FYI.

**Comment by huubvanniekerk** [comment]
I had the same issue on Fedora 36, but this daily build of Dec 22 fixed it. Thank you.
