### ISSUE TITLE
Installe script issues

### ISSUE THREAD

**Issue by bovirus** [OpenShot/openshot-qt#5029]
**Describe the bug:**
 Installer script issues .

In main window caption "versione" is not necessary

In main window caption is misisng the info if you are installing 32bit or 64bit program version.

In installer exe properties (exe file -> right click -> prtoprerties) in copyright info teh company is truincated because too long "C" and "Copyright" that have the same emaning.
I suggest to use "(c) xxx" without Copyright ("/C) have same emaninG" and xxx company name.

**Steps to reproduce the behavior:**
Install the program

**Expected behavior:**

**System Details:**
Windows 10 64bit.

**Log Files:**

**Exception / Stacktrace:**

**Screenshots:** (Optional)

![image](https://user-images.githubusercontent.com/1262554/206896049-81a029fd-e4fd-4faf-a8fa-7a475c26a017.png)

![image](https://user-images.githubusercontent.com/1262554/206895948-8e31a273-0170-487e-bd09-fc9241bf25a8.png)

**Comment by jonoomph** [comment]
Can you reproduce with the final 3.0.0 installer for Windows? 
https://github.com/OpenShot/openshot-qt/releases/download/v3.0.0/OpenShot-v3.0.0-x86_64.exe

We actually removed the word "version" from the title in our final installer. However, the 32 or 64 bit text is only added if you try and install both installers (I think).

**Comment by bovirus** [comment]
@jonoomph 

Thanks for the fix.

In your new installer "versione" is fixed.
But is not fixed the Copyright message for exe file properties.

I get here 32bit and 64bit versiuoin

https://www.videohelp.com/software/OpenShot-Video-Editor

If there is a 32bit and 64bit verson could be intersting to have on top left info if the installer is 32bit or 64bit.

What's the negative point to explain 32bit or 64bit in mainw window?

**Comment by bovirus** [comment]
@jonoomph

New .iss (Inno Setup) sissue.

In Windows program list program name should be reported without "versione x.x.x.x"

![image](https://user-images.githubusercontent.com/1262554/206914980-f07d606d-04ed-44b1-aa5a-dae484f8e701.png)

Fixes in https://github.com/OpenShot/openshot-qt/blob/develop/installer/windows-installer.iss

changes in [Setup] section

- Fix Windows program list OpenShot Video Edito name without version

UninstallDisplayName={#MyAppName}

- Fix Copyright name truncated

AppCopyright=(c) 2008-2019 {#MyAppPublisher}

- Fix 32bit/64bit info in main window

replace

AppVerName={#MyAppName} {#VERSION}

with 

#if ONLY_64_BIT == "x64"
  AppVerName={#MyAppName} {#VERSION} 64bit
@else
  AppVerName={#MyAppName} {#VERSION} 32bit
#endif

Thanks.

**Comment by bovirus** [comment]
@jonoomph

For the copyright message I beleive that should include current year. You can get in this way

#define CurrentYear        GetDateTimeString('yyyy','','')

[Setup]
AppCopyright=(c) 2008-{#CurrentYear} {#MyAppPublisher}

**Comment by jonoomph** [comment]
Thanks, appreciate the code snippets and suggestions! I'll give the copyright improvements a try. Regarding the 32/64 bit in the title, keep in mind that 99% of OpenShot users install the 64-bit version, and very few people install the 32-bit one. So, I don't think it's particularly useful or necessary to display it prominently in the Title bar and App launchers, etc...

**Comment by jonoomph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve Copyright in Windows Installer](https://trello.com/c/3bZFBaDi/255-improve-copyright-in-windows-installer)

**Comment by bovirus** [comment]
@jonoomph

The use of "32bit" "64bit" after version for me has no negative point but only positive points.

You have two installer type (32bit and 64bit) and when you run it the user cannot understand if it's 32bit or 64bit version.

And also if there is only version (ex. 64bit) to have "64bit" in top left main window add info and avoid misunderstanding.

Please also remind the request of other fixes (ex. progran name without version in Windows program list).

**Comment by Colorjet3** [comment]
This has been resolved.
