### ISSUE TITLE
crashes during export in Windows

### ISSUE THREAD

**Issue by Soul-Proprietor** [OpenShot/openshot-qt#503]
First project I made was taking forever to export, then became unresponsive. I shut it down but it won't start, even after re-install. Message= "this application has requested to terminate Runtime in an unusual way" 

I'm hoping you have some solution for this. 

Thanks, Dan

**Comment by jonoomph** [comment]
Duplicate of https://github.com/OpenShot/openshot-qt/issues/513 (I think). If not, please reopen this issue. Thanks!
