### ISSUE TITLE
AppImage not opening on my Ubuntu 22.10

### ISSUE THREAD

**Issue by izzostar** [OpenShot/openshot-qt#5031]
**Describe the bug**
AppImage not opening on my Ubuntu 22.10

**Steps to reproduce the behavior:**
On Ubuntu 22.10 Download OpenShot-v3.0.0-x86_64.AppImage
mark as excecutive
click on it
nothing

went to terminal
typed ./Openshot....something

shows:
dlopen(): error loading libfuse.so.2

AppImages require FUSE to run

installed libfuse2  (installed now alongside version3)
typed ./Openshot....something
long texts appear, in end seems for a millisecond OpenShot opens, then closes its window.

clicked AppImage
OpenShot window opens, but cant click anything, gnome window pops up: Force quit or wait.

quited, uninstalled libfuse2. 
for some reason installed libfuse2 again.
This time OpenShot window opened normally so i can click the menus in the program.

**Expected behavior**
Clicking on AppImage opens OpenShot window.

**System Details**
- OpenShot Version: 3.0.0
- libopenshot Version:  0.3.0
- Platform: Linux-5.19.0-26-generic-x86_64-with-glibc2.4
- Processor: x86_64
- Machine: x86_64
- Python version: 3.8.10
- Qt5 version: 5.12.8
- PyQt5 version: 5.14.1
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: en_US.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Skipped this step

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/j7dkh7jfe9dzocuyxg23ebz23fuaven7/openshot-qt.zip) (46 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/j7dkh7jfe9dzocuyxg23ebz23fuaven7/libopenshot.zip) (14 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
Please run this command "sudo apt install libfuse2" from a terminal console.  After that it should start.

Please confirm, either way.

**Comment by izzostar** [comment]
Yes after few attempts it opened, not sure why it hanged the first time and suggested force quit. Maybe another terminal instance was not closed yet. Previewing a video crashed it tho (closed the window), but thats for another bugreport i guess.

**Comment by Colorjet3** [comment]
Good to know you are now able to start OpenShot.  Yes, please start a new thread regarding the bug report regarding the preview and crashing.
