### ISSUE TITLE
terminal error when running openshot appimage version 3.0.0-x86_64 on ubuntu 18.04

### ISSUE THREAD

**Issue by dln949** [OpenShot/openshot-qt#5033]
This is what appears in the terminal when starting Openshot appimage 3.0 on Ubuntu 18.04:  

```
main1@system1:~$ /home/main1/applications/AppImages/openshot/OpenShot.AppImage
/tmp/.mount_OpenShBf32Uz/usr/bin/openshot-qt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_OpenShBf32Uz/usr/bin/lib/libpython3.8.so.1.0)
main1@system1:~$ 
```

**Comment by Colorjet3** [comment]
Have you tried installing GLIBC?  If not, please install it then try OpenShot again.

**Comment by grapemix** [comment]
I guess it is hardly to find a linux desktop without GLIBC installed nowadays. It would be nice if openshot team can give us more detail on the requirement.

` strings /lib/x86_64-linux-gnu/libc.so.6 | grep GLIBC` to see if GLIBC_2.28 is installed. It is probably not. Try to download https://github.com/OpenShot/openshot-qt/releases/download/v2.6.1/OpenShot-v2.6.1-x86_64.AppImage and try again. This version should be fine.

Finally, if anyone see it, we need the API in Linux too! Thanks.

**Comment by dln949** [comment]
Using version 2.6.1 of the AppImage works with no problem.

**Comment by Colorjet3** [comment]
There were some changes made to FFMPeg (I have to confirm with the Developer on this) that requires this statement to be run in Ubuntu for v3.0.0 (sudo apt install libfuse2).  I am not an Linux expert but please try this and let us know if v3.0.0 AppImage works for you.

**Comment by dln949** [comment]
Thanks.  

I already had libfuse2 installed, but still had the problem originally shown with version 3.0.0 in the first post.

**Comment by Colorjet3** [comment]
Thank you for the FYI.  I am going to need to get a developer involved to get to the bottom of this.

**Comment by sc0nway** [comment]
Hi @dln949!

Would you please try downloading and installing our [latest Daily Build](https://www.openshot.org/download/#daily) and verify the issues are still happening?  Jonathan modified our Linux AppImages to include the correct libraries, and OpenShot should run correctly on Ubuntu 18.04.

**Comment by dln949** [comment]
I am so, so sorry!  Since I last heard from anyone on this thread, I somewhat unexpectedly got a new computer, and no longer have the one with Ubuntu 18.04 on it.

**Comment by Colorjet3** [comment]
Thanks for the update @dln949 What operating system are you running now and is OpenShot working for you?

**Comment by dln949** [comment]
Ubuntu 22.04.  I have version 3.0.0 of Openshot - both flatpak and appimage - installed, and both seem to be working just fine.

**Comment by Colorjet3** [comment]
Excellent and thank you again for the prompt update.  Best of luck with your project(s).
