### ISSUE TITLE
Importing MP4 results in "file is not a valid video, audio, or image file."

### ISSUE THREAD

**Issue by izzostar** [OpenShot/openshot-qt#5037]
**Describe the bug**
Importing MP4 results in "file is not a valid video, audio, or image file."

**Steps to reproduce the behavior:**
1. Go to 'File'
2. Click on 'Import Files'
3. Click 'Open'

**Expected behavior**
Video should import

**System Details**
- OpenShot Version: 3.0.0
- libopenshot Version:  0.3.0
- Platform: Linux-5.4.0-131-generic-x86_64-with-glibc2.4
- Processor: x86_64
- Machine: x86_64
- Python version: 3.8.10
- Qt5 version: 5.12.8
- PyQt5 version: 5.14.1
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: en_US.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.0.0-daily-10705-89e4b1da-fab6e6ab-x86_64.AppImage

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/5qib3pe4ggm6hf5rjur0uojduyrfqxrw/openshot-qt.zip) (6 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
Sorry, no idea how to reopen a bug, so i made a new one.
                
![bug1](https://user-images.githubusercontent.com/15717394/207093387-cb421384-6704-4d75-984f-54075e2d8aed.png)

**Comment by Colorjet3** [comment]
Does this happen with all .mp4 files or just this one?  If only this one, then please run it through a converter.  This is a common issue we've seen even with previous versions of OpenShot.  Use something like Handbrake, vlc, or shutter encoder and convert it back to .mp4 then try your import.

**Comment by izzostar** [comment]
Different files, originals copied from my phone and used for creating videos previously with older version of openshot (2.5.1? probably). JPG-load fine. 
.mp4 load after i delete the Openshot.settings file.
Now you want to close the issue, but that does not solve the bug, does it?

**Comment by Colorjet3** [comment]
Yes and No.  Yes, you can go ahead and close the ticket if you wish or keep it open.  It is very challenging to find these types of bugs because there are so many variables than can cause the issue.  For instance, the fact that deleting Openshot.settings fixed the issue, we now must somehow track back the exact steps/actions that caused it to be corrupted to the point where you can no longer import .mp4 files(probably other video file types as well).

I am glad you are passed this issue.

**Comment by Alllgator343** [comment]
I have the same problem. I'm use appimage 3.1.1

**Comment by Colorjet3** [comment]
Hello @Alllgator343.  What operating system are you running?

**Comment by Alllgator343** [comment]
> Hello @Alllgator343. What operating system are you running?

Hello! Linux Mint 21.2 xfce

**Comment by Colorjet3** [comment]
Hello @Alllgator343.

1.  Close OpenShot if running.
2.  Make a backup of /home/username/.openshot_qt folder.
3.  Delete /home/username/.openshot_qt folder.
4.  Start OpenShot and try the import now.

If still not working you can try the following:
1.  Convert one of your .mp4 files to .mp4 again using something like Shutter Encoder or Handbrake.
2.  Import this newly created .mp4 file and see if that fixes the issue.  This may not be a 100% resolution but rather a workaround.

or,

1.  Close Openshot.
2.  go to https://www.openshot.org/ppa/.
3.  Execute the "Daily PPA" installation instructions.
4.  Start OpenShot via the shortcut icon and give the import a try.

**Comment by Alllgator343** [comment]
> Hello @Alllgator343.
> 
>     1. Close OpenShot if running.
> 
>     2. Make a backup of /home/username/.openshot_qt folder.
> 
>     3. Delete /home/username/.openshot_qt folder.
> 
>     4. Start OpenShot and try the import now.
> 
> 
> If still not working you can try the following:
> 
>     1. Convert one of your .mp4 files to .mp4 again using something like Shutter Encoder or Handbrake.
> 
>     2. Import this newly created .mp4 file and see if that fixes the issue.  This may not be a 100% resolution but rather a workaround.
> 
> 
> or,
> 
>     1. Close Openshot.
> 
>     2. go to https://www.openshot.org/ppa/.
> 
>     3. Execute the "Daily PPA" installation instructions.
> 
>     4. Start OpenShot via the shortcut icon and give the import a try.

Thanks! I hope it will be fixed in the future.

**Comment by Colorjet3** [comment]
Hello @Alllgator343.  Was this resolved for you?  If yes, which option did you go with?  Your feedback will help others as well.

**Comment by Alllgator343** [comment]
> Hello @Alllgator343. Was this resolved for you? If yes, which option did you go with? Your feedback will help others as well.

Yes, I installed the application via ppa:openshot.developers/ppa

**Comment by bullyer** [comment]
hello @Colorjet3  i am also having the same problem with v. 3.1.1 windows 11. Pls help me

**Comment by Colorjet3** [comment]
Hello @bullyer.  

1.  Close Openshot if running.
2.  Go to openshot.org/download/#daily.
3.  Download the latest DEV DAILY build available.
4.  Install it and try the import.

Let me know the result.
