### ISSUE TITLE
UI briefly opens, then abruptly exits. O/S is Windows Server 2019 Datacenter, NOT Windows 10. OpenSh...

### ISSUE THREAD

**Issue by jsmorada** [OpenShot/openshot-qt#5038]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 3.0.0
- libopenshot Version:  0.3.0
- Platform: Windows-10-10.0.17763
- Processor: Intel64 Family 6 Model 62 Stepping 4, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.0.0-daily-10705-89e4b1da-fab6e6ab-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/fl8aappvbl00qx9d1n8lewnzm9hsw312/openshot-qt.zip) (4 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/fl8aappvbl00qx9d1n8lewnzm9hsw312/libopenshot.zip) (0 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.
                
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/10218124/openshot-qt.log)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/10218125/libopenshot.log)

**Comment by Colorjet3** [comment]
There is a fix on the way that may fix this issue.  We've seen some similar reports of crashing in Win 7, Win 8.1, Win 10, & Win 11.
Stay tuned as a Daily Build is on its way.

**Comment by jsmorada** [comment]
Thanks, I'll be waiting with bated breath...:)

**Comment by Colorjet3** [comment]
A fix has been released:  Go to openshot.org/daily/#build and download the latest available and give it a try.  Please confirm either way.

**Comment by Colorjet3** [comment]
Hello @jsmorada Any update on this?

**Comment by Colorjet3** [comment]
No Response

**Comment by jsmorada** [comment]
Sorry I dropped the ball...distracted by the holidays. It's working now!

Thanks,
Jon

**Comment by Colorjet3** [comment]
No worries @jsmorada and glad it is working for you.
