### ISSUE TITLE
Segmentation fault on latest dailybuild appimage

### ISSUE THREAD

**Issue by jEsuSdA** [OpenShot/openshot-qt#5040]
**Describe the bug:**
Segmentation fault on launch

**Steps to reproduce the behavior:**
1. Download latest dailybuild appimage
2. Run it...
3. This happens:
![imagen](https://user-images.githubusercontent.com/5833446/207660363-00e097f3-c5c8-4b59-87c8-1411b94f5bdd.png)

**Expected behavior:**
Openshot starts.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: OpenShot-v3.0.0-daily-10705-89e4b1da-fab6e6ab-x86_64.AppImage
- Operating System / Distro: 
```

         _,met$$$$$gg.           jesusda@lucas
      ,g$$$$$$$$$$$$$$$P.        OS: Debian oldstable-updates sid
    ,g$$P""       """Y$$.".      Kernel: x86_64 Linux 5.15.49-xanmod1
   ,$$P'              `$$$.      Uptime: 12d 23h 21m
  ',$$P       ,ggs.     `$$b:    Packages: 4933
  `d$$'     ,$P"'   .    $$$     Shell: bash
   $$P      d$'     ,    $$P     Resolution: 3600x1200
   $$:      $$.   -    ,d$$'     DE: XFCE
   $$\;      Y$b._   _,d$P'      WM: Xfwm4
   Y$$.    `.`"Y$$$$P"'          WM Theme: Greybird-kgt-3
   `$$b      "-.__               GTK Theme: Greybird [GTK2]
    `Y$$                         Icon Theme: ePapirus
     `Y$$.                       Font: Droid Sans 7.5
       `$$b.                     CPU: Intel Xeon E5-2678 v3 @ 24x 3.3GHz [39.8°C]
         `Y$$b.                  GPU: Radeon RX550/550 Series (POLARIS12, DRM 3.42.0, 5.15.49-xanmod1, LLVM 11.0.1)
            `"Y$b._              RAM: 6485MiB / 32013MiB
                `""""   

```

**Log Files:**

log files are empty.

Thanks a lot

**Comment by snooppr** [comment]
### Segmentation fault
GNU/Linux Deb10 Neither 3.0 release nor latest build starts

It runs openshot v2.6.0-dev without a problem.

`$ journalctl -f`

> kernel: openshot-qt[4744]: segfault at 23a0 ip 00000000000023a0 sp 00007ffcdac48d88 error 14 in openshot-qt[55da0468f000+1000]
kernel: Code: Bad RIP value.
systemd[1]: tmp-.mount_OpenShqgFwQ5.mount: Succeeded.
systemd[2565]: tmp-.mount_OpenShqgFwQ5.mount: Succeeded.

**Comment by Colorjet3** [comment]
Hello @snooppr There were a few more fixes released in DEV Daily Build.  Please get the latest and try again:  openshot.org/downlaod/#daily.

**Comment by snooppr** [comment]
> Hello @snooppr There were a few more fixes released in DEV Daily Build. Please get the latest and try again: openshot.org/downlaod/#daily.

Hello. I just downloaded the latest build ''OpenShot-v3.0.0-daily-10947-510a7690-b5bbab66-x86_64.AppImage'', unfortunately the same error. It just won't run on GNU/Linux.
https://www.openshot.org/download/#daily

`$ journalctl -f`

> 
> янв 21 12:20:18 user kernel: openshot-qt[7898]: segfault at 23a0 ip 00000000000023a0 sp 00007fff1701b6b8 error 14 in openshot-qt[5594c5334000+1000]
> янв 21 12:20:18 user kernel: Code: Bad RIP value.
> янв 21 12:20:18 user systemd[1]: tmp-.mount_OpenShgQqCp2.mount: Succeeded.
> янв 21 12:20:18 user systemd[2594]: tmp-.mount_OpenShgQqCp2.mount: Succeeded

**Comment by jonoomph** [comment]
Taking a look using Debian 10 and Debian 11 - I'll share my feedback shortly.

**Comment by jonoomph** [comment]
I just installed Debian 11 in a VM, and it runs the latest daily build of OpenShot's *.Appimage just fine. However, in Debian 10, it uses an old version of GLIBC (2.28 - released on August 1st 2018). This is too old for our *.Appimage dependencies unfortunately. Sorry, but there is not an easy fix for this, with respect to the *.Appimage.

You can build OpenShot from source, or hopefully find a PPA that uses our latest source code - those can be compiled against GLIBC 2.28 with no problem, and is probably your best bet. Hopefully this helps!

**Comment by jEsuSdA** [comment]
> I just installed Debian 11 in a VM, and it runs the latest daily build of OpenShot's *.Appimage just fine. However, in Debian 10, it uses an old version of GLIBC (2.28 - released on August 1st 2018). This is too old for our *.Appimage dependencies unfortunately. Sorry, but there is not an easy fix for this, with respect to the *.Appimage.
> 
> You can build OpenShot from source, or hopefully find a PPA that uses our latest source code - those can be compiled against GLIBC 2.28 with no problem, and is probably your best bet. Hopefully this helps!

Thank you for the information.
I need to update my Debian. ;)
