### ISSUE TITLE
OpenShot crashes with an error immediately upon startup

### ISSUE THREAD

**Issue by f2065** [OpenShot/openshot-qt#5041]
**Describe the bug**
OpenShot crashes with an error immediately upon startup. I tried release 3.0.0, and tried nightly builds. All versions are crashes.
I reinstalled OpenShot several times, deleted C:\Users\<profile>\.openshot_qt. It did not help.

**System Details**
- OpenShot Version: 3.0.0
- libopenshot Version:  0.3.0
- Platform: Windows-8.1-6.3.9600
- Processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['ru-RU', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.0.0-daily-10705-89e4b1da-fab6e6ab-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/x22p9nyphqvrmm4ty1dtdbw44b4lvh9p/openshot-qt.zip) (8 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Screenshot of crash in debugger**
![openshot_crash1](https://user-images.githubusercontent.com/29691031/207700872-977f1dca-3dd6-4f03-a0af-ffa60ee12f42.png)

**Comment by Colorjet3** [comment]
A fix has been released:  Go to openshot.org/daily/#build and download the latest available and give it a try.  Please confirm either way.

**Comment by f2065** [comment]
Yes, problem solved. The OpenShot-v3.0.0-daily-10786-186a4ca5-fab6e6ab-x86_64.exe works fine.

**Comment by Colorjet3** [comment]
Awesome and thank you so much for the FYI.
