### ISSUE TITLE
Program will run successfully, get through to the window, and then exit

### ISSUE THREAD

**Issue by StarProgamGamer** [OpenShot/openshot-qt#5042]
**Describe the bug:**
I have added and reinstalled the AppImage multiple times, and have tried the daily build as well after looking at past solutions but nothing works. It ran fine the first time but then eventually crashed and haven't been able to open it since without it crashing almost immediately once the window is open

**Steps to reproduce the behavior:**
1. Run the AppImage in the terminal
2. Window will open
3. See error
4. It then crashes and the process finishes

**Expected behavior:**
1. Run the AppImage in the terminal
2. Window will open
3. No unusual messages
4. Doesn't crash

**System Details:**
- OpenShot Version : {{ 3.0.0 }}
- Operating System / Distro: Chrome OS/Debian GNU/Linux 11
**Log Files:**
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/10232805/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/10232854/openshot-qt.log)

**Exception / Stacktrace:**
INFO project_data: Apply default audio playback settings: 48000, 2 channels
terminate called after throwing an instance of 'openshot::InvalidFile'
  what():  File could not be opened.
Caught signal 6 (SIGABRT)
---- Unhandled Exception: Stack Trace ----
  /lib/x86_64-linux-gnu/libc.so.6 ( abort                                     + 0x123 )  [0x7f1fc495c537]
  /lib/x86_64-linux-gnu/libstdc++.so.6 (                                           + 0x9a7ec)  [0x7f1fc27977ec]
  /lib/x86_64-linux-gnu/libstdc++.so.6 (                                           + 0xa5966)  [0x7f1fc27a2966]
  /lib/x86_64-linux-gnu/libstdc++.so.6 (                                           + 0xa4a49)  [0x7f1fc27a1a49]
  /lib/x86_64-linux-gnu/libstdc++.so.6 ( __gxx_personality_v0                      + 0x271 )  [0x7f1fc27a2381]
  /tmp/.mount_OpenShFLWAeY/usr/bin/libopenshot.so.23 (                                           + 0x1d680b)  [0x7f1fc3bdb80b]
  /tmp/.mount_OpenShFLWAeY/usr/bin/libopenshot.so.23 (                                           + 0x1d71fa)  [0x7f1fc3bdc1fa]
  /tmp/.mount_OpenShFLWAeY/usr/bin/libopenshot.so.23 (                                           + 0x8669f)  [0x7f1fc3a8b69f]
  /tmp/.mount_OpenShFLWAeY/usr/bin/libopenshot.so.23 ( openshot::Mask::SetJsonValue(Json::Value)  + 0x365 )  [0x7f1fc3b4ca45]
  /tmp/.mount_OpenShFLWAeY/usr/bin/libopenshot.so.23 ( openshot::Timeline::SetJsonValue(Json::Value)  + 0x457 )  [0x7f1fc3b2ce67]
  /tmp/.mount_OpenShFLWAeY/usr/bin/libopenshot.so.23 ( openshot::Timeline::SetJson(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)  + 0xbd  )  [0x7f1fc3b2016d]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/_openshot.so (                                           + 0x152cf1)  [0x7f1fc3d81cf1]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/libpython3.8.so.1.0 (                                           + 0x2a8697)  [0x7f1fc4dc2697]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/libpython3.8.so.1.0 ( _PyEval_EvalFrameDefault                  + 0x8dd8)  [0x7f1fc4b97f48]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/libpython3.8.so.1.0 ( _PyEval_EvalCodeWithName                  + 0x8fb )  [0x7f1fc4ce4e4b]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/libpython3.8.so.1.0 ( _PyFunction_Vectorcall                    + 0x94  )  [0x7f1fc4dc2124]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/libpython3.8.so.1.0 (                                           + 0x74d6d)  [0x7f1fc4b8ed6d]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/libpython3.8.so.1.0 ( _PyEval_EvalFrameDefault                  + 0xea8 )  [0x7f1fc4b90018]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/libpython3.8.so.1.0 (                                           + 0x8006b)  [0x7f1fc4b9a06b]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/libpython3.8.so.1.0 (                                           + 0x74d6d)  [0x7f1fc4b8ed6d]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/libpython3.8.so.1.0 ( _PyEval_EvalFrameDefault                  + 0xea8 )  [0x7f1fc4b90018]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/libpython3.8.so.1.0 (                                           + 0x8006b)  [0x7f1fc4b9a06b]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/libpython3.8.so.1.0 (                                           + 0x74d6d)  [0x7f1fc4b8ed6d]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/libpython3.8.so.1.0 ( _PyEval_EvalFrameDefault                  + 0xea8 )  [0x7f1fc4b90018]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/libpython3.8.so.1.0 (                                           + 0x8006b)  [0x7f1fc4b9a06b]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/libpython3.8.so.1.0 (                                           + 0x74d6d)  [0x7f1fc4b8ed6d]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/libpython3.8.so.1.0 ( _PyEval_EvalFrameDefault                  + 0xea8 )  [0x7f1fc4b90018]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/libpython3.8.so.1.0 ( _PyEval_EvalCodeWithName                  + 0x8fb )  [0x7f1fc4ce4e4b]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/libpython3.8.so.1.0 ( _PyFunction_Vectorcall                    + 0x94  )  [0x7f1fc4dc2124]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/libpython3.8.so.1.0 (                                           + 0x74d6d)  [0x7f1fc4b8ed6d]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/libpython3.8.so.1.0 ( _PyEval_EvalFrameDefault                  + 0xea8 )  [0x7f1fc4b90018]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/libpython3.8.so.1.0 ( _PyEval_EvalCodeWithName                  + 0x8fb )  [0x7f1fc4ce4e4b]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/libpython3.8.so.1.0 ( _PyFunction_Vectorcall                    + 0x94  )  [0x7f1fc4dc2124]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/libpython3.8.so.1.0 (                                           + 0x2a8dba)  [0x7f1fc4dc2dba]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/libpython3.8.so.1.0 (                                           + 0x74d6d)  [0x7f1fc4b8ed6d]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/libpython3.8.so.1.0 ( _PyEval_EvalFrameDefault                  + 0x45a3)  [0x7f1fc4b93713]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/libpython3.8.so.1.0 (                                           + 0x8006b)  [0x7f1fc4b9a06b]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/libpython3.8.so.1.0 (                                           + 0x2a8e3b)  [0x7f1fc4dc2e3b]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/libpython3.8.so.1.0 ( PyVectorcall_Call                         + 0x60  )  [0x7f1fc4dc2840]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/PyQt5/QtCore.cpython-38-x86_64-linux-gnu.so (                                           + 0x217070)  [0x7f1fb6b71070]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/PyQt5/QtCore.cpython-38-x86_64-linux-gnu.so (                                           + 0x217518)  [0x7f1fb6b71518]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/PyQt5/QtCore.cpython-38-x86_64-linux-gnu.so (                                           + 0x21780e)  [0x7f1fb6b7180e]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/PyQt5/QtCore.cpython-38-x86_64-linux-gnu.so (                                           + 0x2182d7)  [0x7f1fb6b722d7]
  /tmp/.mount_OpenShFLWAeY/usr/bin/libQt5Core.so.5 ( QMetaObject::activate(QObject*, int, int, void**)  + 0x88c )  [0x7f1fc2f2c28c]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/PyQt5/QtCore.cpython-38-x86_64-linux-gnu.so (                                           + 0x213bfe)  [0x7f1fb6b6dbfe]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/libpython3.8.so.1.0 (                                           + 0x2a171e)  [0x7f1fc4dbb71e]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/libpython3.8.so.1.0 (                                           + 0x74d6d)  [0x7f1fc4b8ed6d]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/libpython3.8.so.1.0 ( _PyEval_EvalFrameDefault                  + 0xea8 )  [0x7f1fc4b90018]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/libpython3.8.so.1.0 (                                           + 0x8006b)  [0x7f1fc4b9a06b]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/libpython3.8.so.1.0 (                                           + 0x2a8dba)  [0x7f1fc4dc2dba]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/libpython3.8.so.1.0 (                                           + 0x74d6d)  [0x7f1fc4b8ed6d]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/libpython3.8.so.1.0 ( _PyEval_EvalFrameDefault                  + 0x7d86)  [0x7f1fc4b96ef6]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/libpython3.8.so.1.0 (                                           + 0x8006b)  [0x7f1fc4b9a06b]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/libpython3.8.so.1.0 (                                           + 0x74d6d)  [0x7f1fc4b8ed6d]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/libpython3.8.so.1.0 ( _PyEval_EvalFrameDefault                  + 0x12fd)  [0x7f1fc4b9046d]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/libpython3.8.so.1.0 ( _PyEval_EvalCodeWithName                  + 0x8fb )  [0x7f1fc4ce4e4b]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/libpython3.8.so.1.0 ( PyEval_EvalCodeEx                         + 0x42  )  [0x7f1fc4ce51d2]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/libpython3.8.so.1.0 ( PyEval_EvalCode                           + 0x1f  )  [0x7f1fc4ce55bf]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/libpython3.8.so.1.0 (                                           + 0x1cfc01)  [0x7f1fc4ce9c01]
  /tmp/.mount_OpenShFLWAeY/usr/bin/lib/libpython3.8.so.1.0 (                                           + 0x25f547)  [0x7f1fc4d79547]
---- End of Stack Trace ----

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
A fix has been released:  Go to openshot.org/daily/#build and download the latest available and give it a try.  Please confirm either way.

**Comment by StarProgamGamer** [comment]
It's running currently, but got this: 
locales directory not found at location /tmp/.mount_OpenShKBfqRk/usr/bin/translations/qtwebengine_locales. Trying application directory...
Qt WebEngine locales directory not found at location /tmp/.mount_OpenShKBfqRk/usr/bin/qtwebengine_locales. Trying fallback directory... Translations MAY NOT not be correct.
Path override failed for key ui::DIR_LOCALES and path '/home/x/.openshot'
[1227/193321.276380:WARNING:resource_bundle_qt.cpp(116)] locale_file_path.empty() for locale 
Installed Qt WebEngine locales directory not found at location /tmp/.mount_OpenShKBfqRk/usr/bin/translations/qtwebengine_locales. Trying application directory...
Qt WebEngine locales directory not found at location /tmp/.mount_OpenShKBfqRk/usr/bin/qtwebengine_locales. Trying fallback directory... Translations MAY NOT not be correct.
Path override failed for key ui::DIR_LOCALES and path '/home/x/.QtWebEngineProcess'
[1227/193321.720458:WARNING:resource_bundle_qt.cpp(116)] locale_file_path.empty() for locale 
WARNING preview_thread: Your active audio device (||) does not match OpenShot (). Adjusting your 'Preferences->Playback->Audio Device' to match your active audio device: ||
WARNING webengine: WebEngine backend still not ready after 5 retries.
WARNING webengine: WebEngine backend still not ready after 5 retries.
WARNING webengine: WebEngine backend still not ready after 5 retries.
WARNING webengine: WebEngine backend still not ready after 5 retries.
WARNING webengine: WebEngine backend still not ready after 5 retries.
WARNING webengine: WebEngine backend still not ready after 5 retries.
WARNING webengine: WebEngine backend still not ready after 5 retries.
WARNING webengine: WebEngine backend still not ready after 5 retries.
Property 'modal'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'windowModality'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'enabled'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'geometry'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'frameGeometry'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'normalGeometry'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'x'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'y'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'pos'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'frameSize'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'size'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'width'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'height'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'rect'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'childrenRect'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'childrenRegion'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'sizePolicy'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'minimumSize'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'maximumSize'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'minimumWidth'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'minimumHeight'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'maximumWidth'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'maximumHeight'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'sizeIncrement'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'baseSize'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'palette'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'font'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'cursor'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'mouseTracking'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'tabletTracking'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'isActiveWindow'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'focusPolicy'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'focus'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'contextMenuPolicy'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'updatesEnabled'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'visible'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'minimized'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'maximized'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'fullScreen'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'sizeHint'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'minimumSizeHint'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'acceptDrops'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'windowOpacity'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'windowModified'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'toolTip'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'toolTipDuration'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'statusTip'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'whatsThis'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'accessibleName'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'accessibleDescription'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'layoutDirection'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'autoFillBackground'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'styleSheet'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'locale'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'windowFilePath'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'inputMethodHints'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'title'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'url'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'selectedText'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'hasSelection'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'zoomFactor'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
WARNING webengine: WebEngine backend still not ready after 5 retries.
WARNING webengine: WebEngine backend still not ready after 5 retries.

**Comment by Colorjet3** [comment]
Please confirm the daily build # you are running.

**Comment by StarProgamGamer** [comment]
OpenShot-v3.0.0-daily-10873-99aab0a1-f55ec5d0-x86_64

**Comment by Colorjet3** [comment]
Thank you for that.  I am going to ask someone else for assistance as this is beyond my expertise.

Hello @sc0nway Please check this out, thank you!

**Comment by Colorjet3** [comment]
Hello @StarProgamGamer There have been many recent Daily Builds since 10873 and this issue may have been fixed.  Please go to openshot.org/download/#daily and download the latest DEV Daily available and let me know if you are still experiencing the issue.

One additional thing you can try is to:
1. Close Openshot if running. 
2. Make a backup of your /home/username/.openshot_qt folder.
3.  Delete /home/username/.openshot_qt folder.
4.  Start Openshot and see if it is any better.

**Comment by StarProgamGamer** [comment]
Still same errors unfortunately

**Comment by Colorjet3** [comment]
Hello @StarProgamGamer I need to get on of the developers to look into this.

**Comment by StarProgamGamer** [comment]
Just noting that I have a different laptop now so I won't be using Linux but I can still go on it occasionally to test if needed

**Comment by Colorjet3** [comment]
Thank you for the update.

**Comment by Colorjet3** [comment]
Hello @StarProgamGamer.  Version 3.1.1 has been released.  I realize that you have a different laptop and hope all is going well with your projects.

I am going to close this ticket, but feel free to reopen if you still need to work in the Linux environment.
