### ISSUE TITLE
Open shot closes a few seconds after launch

### ISSUE THREAD

**Issue by lucabechini** [OpenShot/openshot-qt#5043]
**Describe the bug**
OpenShot shuts down unexpectedly a few seconds after it is launched. In the short time when I can see the graphical user interface I cannot run any command (the program is not responsive to mouse clics).

**Steps to reproduce the behavior:**
1. Launch the program
2. The program window appears
3. Wait a few seconds
4. The program window closes

Note: the content of libopenshot.log is the following:
libopenshot logging: Thu Dec 15 11:27:10 2022

**Expected behavior**
The program shall remain open.

**System Details**
- OpenShot Version: 3.0.0
- libopenshot Version:  0.3.0
- Platform: Windows-10-10.0.17763
- Processor: Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['it-IT', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.0.0-daily-10705-89e4b1da-fab6e6ab-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/7zx7y3zmy5m5937byrhrlt2u7338veo9/openshot-qt.zip) (4 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
This issue has been identified and a fix is in the way.  Stay tuned...

**Comment by Colorjet3** [comment]
A fix has been release:  Go to openshot.org/daily/#build and download the latest available and give it a try.  Please confirm either way.

**Comment by lucabechini** [comment]
Dear OpenShot developers,
now the program works properly. The issue is resolved.

Thank you very much for providing such a prompt solution!

Kind regards,
Luca Bechini

**Comment by Colorjet3** [comment]
That is awesome @lucabechini!  Best of luck with your projects.

-Raffi
