### ISSUE TITLE
Archivos .webm Crashean el equipo comppleto

### ISSUE THREAD

**Issue by inter-web** [OpenShot/openshot-qt#5044]
**Describa el problema**
Cargué varias veces un archivo en formato .WEBM y crasheo mi equipo completamente, tuve que desconectar la corriente eléctrica para poder reiniciarlo cada vez que intentaba trabajar con ese tipo de archivos. Use archivos .MP4 y no tuve ningún problema tampoco usando imágenes JPG pra crear un video.

**Pasos para reproducir el comportamiento:**
1. Cargar archivo .WEBM
2. Colocarlo en la pista superior.
3. Colocarlo nuevamente en la pista inferior,para hacer una mezcla y el Openshot comienza a ralentizar el equipo completo hasta el grado de bloquear todo el equipo.
4. Apagar el equipo para poderlo iniciar nuevamente.

**Comportamiento esperado**
Hasta la actualización de hace unos días, este error no ocurría, trabajábamos con vídeos o imágenes  de cualquier tipo y nunca hubo problema.

**Detalles del sistema**
- OpenShot Version: 3.0.0
- libopenshot Version:  0.3.0
- Platform: Linux-5.4.0-135-generic-x86_64-with-glibc2.29
- Processor: x86_64
- Machine: x86_64
- Python version: 3.8.10
- Qt5 version: 5.12.8
- PyQt5 version: 5.14.1
- Qt Detected Languages: ['es-MX', 'es']
- LANG Environment Variable: es_MX.UTF-8
- LOCALE Environment Variable: 
- Compilación diaria: Saltar este paso

**Archivos de registro**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/8x46lcqob65z5zmdw11uin9cxecp3kz6/openshot-qt.zip) (72 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/8x46lcqob65z5zmdw11uin9cxecp3kz6/libopenshot.zip) (0 KB)

**Excepción / Rastreo de pila**
```No stacktrace found in log files```

**Capturas de pantalla** (Opcional)
No hay tiempo de capturar pantallas ni en imagen menos con SimpleScreen Recorder.

**Comment by Colorjet3** [comment]
You most likely have a corrupt .webm file.  Are you able to play it outside of Openshot in a media player?

Since you are able to work with .mp4 files I would try converting your .webm file to a .MP4 and then import it into OpenShot.

What version of Linux are you running?

**Comment by Colorjet3** [comment]
No response from user.
