### ISSUE TITLE
Crash nach dem Start in Ubuntu MATE 22/10

### ISSUE THREAD

**Issue by mtw171** [OpenShot/openshot-qt#5046]
**Beschreiben Sie den Fehler**
Openshot startet, zeigt kurz die Benutzeroberfläche und eine Messagebox und crasht dann mit Stack-Trace

**Schritte zum Reproduzieren des Verhaltens**
1. starten - in Ubuntu Mate 22/10 mit Nvidia Xorg nouveau display driver

**Systemdetails**
- OpenShot Version: 3.0.0 daily build 10705
- libopenshot Version:  0.3.0  daily build 10705
- Platform: Linux-5.19.0-26-generic-x86_64-with-glibc2.4
- Processor: x86_64
- Machine: x86_64
- Python version: 3.8.10
- Qt5 version: 5.12.8
- PyQt5 version: 5.14.1
- Qt Detected Languages: ['de-DE', 'en']
- LANG Environment Variable: de_DE.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Verifiziertes Problem exsitiert immer noch im Daily Build:  http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.0.0-daily-10705-89e4b1da-fab6e6ab-x86_64.AppImage

**Logdateien**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/iq4f6966ylfwnypttg8fx9y4xdo1t5o1/openshot-qt.zip) (6 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/iq4f6966ylfwnypttg8fx9y4xdo1t5o1/libopenshot.zip) (9 KB)

**Ausnahme / Stapelverfolgung**
```/lib/x86_64-linux-gnu/libc.so.6 gsignal                                  0x16  [0x7fc87ac3bc46]
/lib/x86_64-linux-gnu/libc.so.6 abort                                    0xd7  [0x7fc87ac227fc]
/lib/x86_64-linux-gnu/libc.so.6                                          0x2271b  [0x7fc87ac2271b]
/lib/x86_64-linux-gnu/libc.so.6                                          0x33596  [0x7fc87ac33596]
/lib/x86_64-linux-gnu/libdrm_nouveau.so.2                                          0x4e77  [0x7fc862d03e77]
/lib/x86_64-linux-gnu/libdrm_nouveau.so.2 nouveau_pushbuf_data                     0x67  [0x7fc862d03dd7]
/lib/x86_64-linux-gnu/libdrm_nouveau.so.2                                          0x4efc  [0x7fc862d03efc]
/lib/x86_64-linux-gnu/libdrm_nouveau.so.2                                          0x5177  [0x7fc862d04177]
/lib/x86_64-linux-gnu/libdrm_nouveau.so.2 nouveau_pushbuf_kick                     0x14  [0x7fc862d04784]
/usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so                                          0x97179d  [0x7fc86117179d]
/usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so                                          0x18af9a  [0x7fc86098af9a]
/usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so                                          0xb4bee  [0x7fc8608b4bee]
/lib/x86_64-linux-gnu/libGLX_mesa.so.0                                          0x51ec2  [0x7fc8630ddec2]
/lib/x86_64-linux-gnu/libGLX_mesa.so.0                                          0x44a25  [0x7fc8630d0a25]
/lib/x86_64-linux-gnu/libGLX_mesa.so.0                                          0x33d5f  [0x7fc8630bfd5f]
/tmp/.mount_OpenShvr9AyF/usr/bin/plugins/xcbglintegrations/libqxcb-glx-integration.so                                          0xad6a  [0x7fc863f0ed6a]
/tmp/.mount_OpenShvr9AyF/usr/bin/libQt5Gui.so.5 QOpenGLContext::swapBuffers(QSurface*)   0xa1  [0x7fc878d635c1]
/tmp/.mount_OpenShvr9...

**Comment by Colorjet3** [comment]
Please run this "sudo apt install libfuse2" from a Terminal session and give it a try.

**Comment by mtw171** [comment]
libfuse2 is already installed  (2.9.9-5ubuntu3)

**Comment by Colorjet3** [comment]
Hello @mtw171 A new daily build has been released that may solve your issue.  Please go to openshot.org/download/#daily and get the latest available.

Let me know if this fixed your issue.  If not, I will ask one of the DEV members to look into this.

**Comment by mtw171** [comment]
Version 10834 and 10840 show the same crash...

**Comment by mtw171** [comment]
Found a workaround: using the nvidia470 driver openshot works fine. Using the openesource-XOrg driver it crashes...

**Comment by sc0nway** [comment]
Hardware acceleration in OpenShot requires using the proprietary drivers from the distribution package manager instead of the NVIDIA drivers.  You cannot use the Nouveau, Xorg, or open-source drivers.
