### ISSUE TITLE
effectively usable since updating to version 3.0.0

### ISSUE THREAD

**Issue by Paul215821** [OpenShot/openshot-qt#5047]
**Describe the bug**
Since updating to 3.0.0 today, I can't even use OpenShot anymore. Audio is sped up so runs out of sync and it sounds like everyone is on helium, and I can't even scrub through the time line because it's so laggy that it becomes unresponsive. Even trying to close the program takes ~20 seconds for the dialog prompt to show up to ask if you want to save before closing. 

**Steps to reproduce the behavior:**
Just import any video and try to play it

**Expected behavior**
Playback as it used to be

**System Details**
- OpenShot Version: 3.0.0
- libopenshot Version:  0.3.0
- Platform: Windows-10-10.0.22621
- Processor: AMD64 Family 23 Model 24 Stepping 1, AuthenticAMD
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.0.0-daily-10705-89e4b1da-fab6e6ab-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/c3wdmtqqgp5fiu3ne7uqs4p3q2u95l7s/openshot-qt.zip) (17 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
go to Edit | Preference | Preview tab and change the Default Audio Sample rate from 44100 to 48000.  Restart OpenShot.

should be good to go.
