### ISSUE TITLE
OpenShot can't process TS files

### ISSUE THREAD

**Issue by JustinWebDev** [OpenShot/openshot-qt#5048]
**Describe the bug:**
I import a .TS file (480p TV program), then I can't do anything with it.  Preview shows nothing, display waveform puts it into an eternal loop.

**Steps to reproduce the behavior:**
1. import a TS file
2. drag it to the timeline
3. play to preview - (v3.0) the playhead moves but nothing plays; same for preview
(v2.6) the CPU ramps up, the playhead does not move, still nothing plays

**Expected behavior:**
The video should process normally.

**System Details:**
- OpenShot Version 3.0
- Operating System Win10 x64 21H2

**Log Files:**
(https://github.com/OpenShot/openshot-qt/files/10252228/openshot-qt.log)

**Comment by Colorjet3** [comment]
For now, see if you can convert your .ts file to .mp4 using something like HandBrake or VLC.  I am going to try and find a .TS file to test with as well.

**Comment by JustinWebDev** [comment]
Well, that doesn't work either.  I converted 32 files to MP4, imported them into my project, then split each one. If I play or export the clips I get audio but green and scrambled video.

I thought the split, then add all in one go (with transitions!) would be perfect for what I need to do, but nope.  Ugh, I should have tested a couple before I did the whole batch.

**Comment by Colorjet3** [comment]
Is it possible that you can share your .ts file with me so I can play with it.  I am also going to ask the developer of the product to see if he has any ideas.

Couple of questions that I should have asked before:
1. Do these .ts files play ok outside of Openshot?
2. When you import a .ts file, can you preview it properly before you split them?

**Comment by JustinWebDev** [comment]
1. They play fine outside of OpenShot.
2. Playing Preview shows a black picture and no audio.

I can share a TS file.  Some place I can upload?

**Comment by Colorjet3** [comment]
hello @JustinWebDev If you have, Google drive, OneDrive, iCloud, or some cloud service, you can then share it with me.

**Comment by Colorjet3** [comment]
No response from user.
