### ISSUE TITLE
Openshot overwrites with corrupted JSON if disk runs out of space.

### ISSUE THREAD

**Issue by HubertMajewski** [OpenShot/openshot-qt#5049]
**Describe the bug:**
When saving a project where disk space is very scarce. The project will begin to save, run into an 'out of space issue', and save a corrupt file. 

**Steps to reproduce the behavior:**
1. Have disk containing very little storage space.
2. Save an .osp file
3. Open a text editor like Notepad++ to see JSON is malformed at the eof.

**Expected behavior:**
Save file would NOT be overwritten with a corrupted/unfinished JSON.

**System Details:**
- OpenShot Version: V3.0.0, libopenshot: 0.3.0
- Operating System / Distro: Linux PC 6.0.12-arch1-1 1 SMP PREEMPT_DYNAMIC Thu, 08 Dec 2022 11:03:38 +0000 x86_64 GNU/Linux

[Corrupt Save.osp.txt](https://github.com/OpenShot/openshot-qt/files/10252289/Corrupt.Save.osp.txt)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/10252290/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/10252291/openshot-qt.log)

**Comment by HubertMajewski** [comment]
Accidentally closed. Ignore "Closed as completed"

**Comment by Colorjet3** [comment]
Well, not much can be done if you run out of disk space or get very low.  Having plenty of disk space is one of the requirements of not only OpenShot but other video editors and application.  As you get close to low disk space even the operating system will have issues that eventually will cause issues for other applications.

Every effort should be made to maintain 15-20% free.  10% absolute minimum IMHO!

**Comment by HubertMajewski** [comment]
I do agree, I didn't expect this project to creep up on me like so. Though, it is unfortunate that there is no check in place to prevent such scenarios while overwriting a save. What would happen if there was another IO error besides a disk full? Without a backup, the entire project is lost.

**Comment by Colorjet3** [comment]
Good point.  For that you can take advantage of the recovery folder.  In your home directory (/home/username/.openshot_qt/ folder you will find a folder name Recovery.  You should be able to salvage the latest graceful save.  You may lose some but you should be able to recover most of it.

**Comment by HubertMajewski** [comment]
That is great to know! Though as a end-user, I didn't know a copy was saved anywhere when the error popped up. Re-opening the project causes an error message saying something similar to "Legacy osp file loaded" despite being a malformed JSON. So, I couldn't have known where a last saved copy was kept, or why all of a sudden I was using a "legacy" file version.

**Comment by Colorjet3** [comment]
I don't know all the technical details as to why that would happen.  When a system crashes, it becomes difficult to predict what happens to the operating system (which many now days can recover on their own) and other running applications will have their own challenges.  Save often (ctrl+S) and maintain a clean and healthy operating system environment.
