### ISSUE TITLE
Crashes every 5 minutes on Mac

### ISSUE THREAD

**Issue by Fikayo** [OpenShot/openshot-qt#505]
Version 2.2 crashes practically every five minutes on my MacBook Pro, Sierra 10.12.3 (I mean it very literally - sometimes not up to 2 minutes). I keep having to force quit via Activity Monitor and open my project again. Unfortunately, I don't have any logs to submit. Please try to reproduce. Thanks

**Comment by jreynojustin** [comment]
Hi @Fikayo,

If you cannot provide log information of any capacity we won't be able to properly track down what causes the bug. The information you provided is vague to find a programatic solution to the issue. If you can provide us with the log information please feel free to re-open the issue.

Thank you for providing feedback!
