### ISSUE TITLE
OpenShot-v2.2.0-4-gfe74b04-49-607-x86_64.AppImage export video 1 frame far too right

### ISSUE THREAD

**Issue by juckendesAuge** [OpenShot/openshot-qt#506]
Test with OpenShot-v2.2.0-4-gfe74b04-49-607-x86_64.AppImage

when i add a video, the export is 1 frame far too right. i use a picture to indecipherable a section of the video. 1 frame i see the clear text
in the preview it is correct, after export, 1 frame far too right.

I need it, because no effect to pixelize a section from a video

sorry for my poor english

**Comment by jonoomph** [comment]
Hi @juckendesAuge. Please include a screenshot so we can understand what's happening, and step by step instructions for us to reproduce. Once you provide that info, please reopen this issue. Thanks!

**Comment by juckendesAuge** [comment]
Hello,
here the Screenshots!

![01_openshot_bildschirmfoto_2017-03-03_22-34-42](https://cloud.githubusercontent.com/assets/24550429/23570619/4c63a412-0065-11e7-93c2-f3451ec66634.png)
![02_openshot_bildschirmfoto_2017-03-03_22-35-18](https://cloud.githubusercontent.com/assets/24550429/23570617/4c5ffa24-0065-11e7-9914-ca2177b88114.png)
![03_video_export_bildschirmfoto_2017-03-03_22-36-59](https://cloud.githubusercontent.com/assets/24550429/23570615/4c5d6e6c-0065-11e7-89b9-3b6aebf95263.png)
![04_video_export_bildschirmfoto_2017-03-03_22-37-24](https://cloud.githubusercontent.com/assets/24550429/23570616/4c5ff9ac-0065-11e7-93b4-8c19d3f1b7b8.png)
![05_video_export_bildschirmfoto_2017-03-03_22-37-40](https://cloud.githubusercontent.com/assets/24550429/23570618/4c60f79e-0065-11e7-8a19-26f24d2ec217.png)

**Comment by juckendesAuge** [comment]
Hello,
i have upload 6 pics. I dont know how can i reopen the issue.
https://github.com/OpenShot/openshot-qt/issues/506#event-979734633

Thanks

2017-02-28 9:29 GMT+01:00 Jonathan Thomas <notifications@github.com>:
