### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by cemmerven** [OpenShot/openshot-qt#5061]
Crash on start on both v3.0.0.0 and daily build ( without rendering any GUI element ) 
windows-10 professional 
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/10285873/openshot-qt.log)

**Comment by Colorjet3** [comment]
A small group of users had reported this issue on Win 7, Win 8.1, Win 10 & Win 11.  Please download the latest DEV Daily Build from openshot.org/download/#daily.  Install it and let us know if the issue is resolved.

**Comment by Komprogue** [comment]
> A small group of users had reported this issue on Win 7, Win 8.1, Win 10 & Win 11. Please download the latest DEV Daily Build from openshot.org/download/#daily. Install it and let us know if the issue is resolved.

Has the same crash after launching the stable 3.0 ver,, but the last dev build ([OpenShot-v3.0.0-daily-10873-99aab0a1-f55ec5d0](https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v3.0.0-daily-10873-99aab0a1-f55ec5d0-x86_64.exe)) works fine.

**Comment by cemmerven** [comment]
Still crashing on start with the daily build: OpenShot-v3.0.0-daily-10873-99aab0a1-f55ec5d0-x86_64.exe
and the same error
 File "<frozen zipimport>", line 259, in load_module
 File "C:\gitlab-runner\builds\4cf61635\0\OpenShot\openshot-qt/openshot.py", line 15, in <module>

**Comment by Colorjet3** [comment]
Hello @cemmerven Let's take a different approach:
1.  Go to Add or Remove Programs.
2.  Search for OpenShot and Uninstall.  There is a chance you may find two entries.  Uninstall both of them.  If you get any error message document them and share with me later.
3.  Backup c:\users\username\.openshot_qt folder.
4.  Delete c:\users\username\.openshot_qt folder.
5.  Delete c:\program files\OpenShot Video Editor folder.
6.  Install Openshot-v3.0.0-daily-10873....
7.  Did this fix it?

**Comment by tonylost** [comment]
Same crash after on stable 3.0 release on Windows 7 x64
...however last dev. build OpenShot-v3.0.0-10873.... works fine.
