### ISSUE TITLE
Upload of some videos not working, shows up as black/blank videos

### ISSUE THREAD

**Issue by iseeissuesfixed** [OpenShot/openshot-qt#5062]
Hi,

I transferred old videos that were in DVD format to my computer (VOB format), and I can play all of them with VLC media player. When I try to upload them to OpenShot, for some reason, only the first video of a set of videos (usually a DVD had a set of 4-5 short videos), the one which starts with VTS_01_1, uploads as intended, while the following ones upload as blank / black videos. Also when I try to preview the videos they only show a black screen with a number (starting at 2) on the right-hand corner increasing quickly as the video runs.
The issue persists when I close OpenShot, start a new project, and then only upload from VTS_01_2 onwards, as in, every time, no matter what I do, it only lets me upload the VTS_01_1 files. Also when I change the name of the files the pattern remains the same, the ones which were originally not VTS_01_1 files just upload as blank.

Would really appreciate your help on this,
Thank you

![OpenShot issue1](https://user-images.githubusercontent.com/121245439/209168162-6ba760d9-2729-466d-be8b-c26e4f503a20.png)
![OpenShot issue2](https://user-images.githubusercontent.com/121245439/209168185-f9b7ce2d-2145-4487-aaa4-6262bf097633.png)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/10288082/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/10288083/openshot-qt.log)

**Comment by Colorjet3** [comment]
I am not sure if OpenShot can do this.  I am going to ask the lead developer.  Meanwhile, try to convert VTS_01_2.VOB to .mp4 using something like HandBrake.

**Comment by Colorjet3** [comment]
Hello @iseeissuesfixed I just confirmed that there is no guarantee that these will work in OpenShot.  The best thing is to convert them to .mp4 using Handbrake or any other converter (i.e., VLC).
