### ISSUE TITLE
my video clips have all now higher pitch/tone and everything is set to normal. What happened?

### ISSUE THREAD

**Issue by JeanTheYeetKing** [OpenShot/openshot-qt#5067]
**Describe the bug**
my clips and videos have high pitch than normal. this never happened before and somehow this happened just now

**Steps to reproduce the behaviour:**
1. Go to import files
2. Click on your selected video
3. drag your video to the track
4. click play
5. problem has arrived. Higher pitch
(This just happened to me and I don't know what I did and how to fix this back to normal. Even uninstalling openshot didn't fix it)

**Expected behaviour**
All my other videos and clips that I exported before were normal. I don't know what happened or what did I press on.

**System Details**
- OpenShot Version: 3.0.0
- libopenshot Version:  0.3.0
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 61 Stepping 4, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-GB', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Skipped this step

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/ast7r26sj0769j5ktbbrlgeptlfkmgyp/openshot-qt.zip) (72 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
In Edit | Preferences | Preview tab, change your Default Audio Sample Rate to 48000 (probably set at 44100 right now).

**Comment by vdv2013** [comment]
It seems that I have a similar issue, but the voice not in the higher tone, but actually **in a lower tone**:
https://github.com/OpenShot/openshot-qt/issues/5068 

Changing Default Audio Sample Rate to 48000 didn't help. 

Also it was not an issue in 2.6.1 for the same imported files. It seems that is started with 3.0. @JeanTheYeetKing  I assume you've recently updated to 3.0?

**Comment by Colorjet3** [comment]
If you updated to v3.0.0 then make sure to download the latest DEV Daily Build as there were some updates to the Audio behavior.  Go to openshot.org/download/#daily and get the latest DEV Daily Build available.  Ensure you download the proper bit (32 bit vs. 64 bit) per your Windows 10 architecture (In windows, type About in the search box and it will tell you).
