### ISSUE TITLE
Audio playback slows down when I import a video in 3.0 (no issue in 2.6.1)

### ISSUE THREAD

**Issue by vdv2013** [OpenShot/openshot-qt#5068]
**Describe the bug:**
Wen I import a video to OpenShot, it's audio becomes "low", as if the playback is slowed down. 

**Steps to reproduce the behavior:**
1. Import a video file, add it to the video
2. Start playback in the preview 
3. Hear the audio being delayed

**Expected behavior:**
Audio is now slowed down.

**System Details:**
- OpenShot Version: "build_name": "OpenShot-v3.0.0-daily-10873-99aab0a1-f55ec5d0",
- Operating System / Distro: Windows-10-10.0.19041

**Log Files:**
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/10313470/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/10313473/openshot-qt.log)

**Exception / Stacktrace:**
no

**Screenshots:** (Optional)
no

**Comment by vdv2013** [comment]
With the old version with THE SAME file, there is no such issue.

Here are the longs for the same file for 2.6.1:
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/10313757/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/10313758/openshot-qt.log)

**Comment by Colorjet3** [comment]
In Edit | Preferences | Preview tab, change the Default Audio Sample rate to 48000.  Restart OpenShot.

let me know if this fixed the issue for you.

**Comment by vdv2013** [comment]
> In Edit | Preferences | Preview tab, change the Default Audio Sample rate to 48000. Restart OpenShot.
> 
> let me know if this fixed the issue for you.

@Colorjet3 
I did exactly what you've suggested, but it didn't work, unfortunately. 

Here are the logs:
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/10319197/openshot-qt.log)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/10319195/libopenshot.log)

**Comment by vdv2013** [comment]
P.S. That's the setting I've changed as you've suggested: 
<img width="610" alt="image" src="https://user-images.githubusercontent.com/117525236/209946009-b0743fd0-b8a7-4f59-9bb3-3c7ef9b49f36.png">
(also restarted Open Shot after changing the setting)

**Comment by Colorjet3** [comment]
In Windows 10, got to Control Panel | Hardware and Sound | Manage Audio Devices.  Tell us what is the device that says "Default Device".  Additionally, select it and then click on Properties | Advanced.  In the Default Format field what is the sample rate set at?

Make sure that OpenShot sample rate matches what is setup here.  You can also choose to change the Windows Audio sample rate to 48000 to match OpenShot.

Let me know what happens.

**Comment by vdv2013** [comment]
@Colorjet3 thanks for the suggestions:

1. When I use the speakers without the headphones, it's device's default format sample rate is 48000, like in Open Shot, and everything is OK with the sound. The device name is "Speaker/Headphone" / "Realtek High Definition Audio".   
![image](https://user-images.githubusercontent.com/117525236/210180524-ab39a8be-b43e-4d9c-9ffb-8e69b28943a5.png)
![image](https://user-images.githubusercontent.com/117525236/210180529-ea719d5f-43be-41f4-8069-61680c6055fe.png)

2. However, if I connect my headphones BULLETS WIRELESS Z / OnePlus Bullets Wireless Z, the default sample rate is 16000, and I simple can't change this setting:
![image](https://user-images.githubusercontent.com/117525236/210180662-c9b4e259-0dfe-4fc3-8d4f-351ec773c955.png)
...and the sound is slowing down.

3. I wish I could try to change the sample rate setting in OpenShot to 16000 to match it, but there is simply no such option for this setting in OpenShot, the lowest is 22050:
![image](https://user-images.githubusercontent.com/117525236/210180701-5d8b1e6a-78ef-4999-aa77-525b6a5d0bd9.png)

**Comment by Colorjet3** [comment]
Hello @vdv2013 I was unable to figure out a way to override the sample rate in OpenShot.  I am going to ask the lead developer to take a look at this.

**Comment by sc0nway** [comment]
Hi @vdv2013!
You can add the 16kHz sample rate specification to the dropdown menu. Browse to your `C:\Program Files\OpenShot Video Editor\settings` folder. Edit the `_default.settings` file using notepad, notepad++, or your favorite text editor. In the section that begins
```
 {
  "max": 192000,
  "title": "Default Audio Sample Rate",
  "category": "Preview",
  "min": 22050,
  "setting": "default-samplerate",
  "value": 48000,
  "values": [
   {
    "value": 22050,
    "name": "22050"
   },
```
Change the line `"min": 22050,` to
```
"min": 16000,
```
Add the following code after `"values": [`
```
   {
    "value": 16000,
    "name": "16000"
   },
```
Save the file and relaunch OpenShot.  Open the Preferences window and select the Preview Tab. Change the Default Audio Sample Rate to 16000, then click the Close button. Relaunch OpenShot for the change to take effect. Please make sure you use the 16kHz device before launching OpenShot, or the application will crash.

**Comment by Colorjet3** [comment]
Hello @vdv2013 Any update on this?

**Comment by laiusgran** [comment]
Hello, i was having the same issue and the fix to change the audio sample rate to match the audio device worked.
Tysm.

**Comment by Colorjet3** [comment]
Thank you @laiusgran for he feedback.

**Comment by dperygin** [comment]
> Hi @vdv2013! You can add the 16kHz sample rate specification to the dropdown menu. Browse to your `C:\Program Files\OpenShot Video Editor\settings` folder. Edit the `_default.settings` file using notepad, notepad++, or your favorite text editor. In the section that begins
> 
> ```
>  {
>   "max": 192000,
>   "title": "Default Audio Sample Rate",
>   "category": "Preview",
>   "min": 22050,
>   "setting": "default-samplerate",
>   "value": 48000,
>   "values": [
>    {
>     "value": 22050,
>     "name": "22050"
>    },
> ```
> 
> Change the line `"min": 22050,` to
> 
> ```
> "min": 16000,
> ```
> 
> Add the following code after `"values": [`
> 
> ```
>    {
>     "value": 16000,
>     "name": "16000"
>    },
> ```
> 
> Save the file and relaunch OpenShot. Open the Preferences window and select the Preview Tab. Change the Default Audio Sample Rate to 16000, then click the Close button. Relaunch OpenShot for the change to take effect. Please make sure you use the 16kHz device before launching OpenShot, or the application will crash.

This worked for me. Thank you!

**Comment by Colorjet3** [comment]
> > Hi @vdv2013! You can add the 16kHz sample rate specification to the dropdown menu. Browse to your `C:\Program Files\OpenShot Video Editor\settings` folder. Edit the `_default.settings` file using notepad, notepad++, or your favorite text editor. In the section that begins
> > ```
> >  {
> >   "max": 192000,
> >   "title": "Default Audio Sample Rate",
> >   "category": "Preview",
> >   "min": 22050,
> >   "setting": "default-samplerate",
> >   "value": 48000,
> >   "values": [
> >    {
> >     "value": 22050,
> >     "name": "22050"
> >    },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Change the line `"min": 22050,` to
> > ```
> > "min": 16000,
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Add the following code after `"values": [`
> > ```
> >    {
> >     "value": 16000,
> >     "name": "16000"
> >    },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Save the file and relaunch OpenShot. Open the Preferences window and select the Preview Tab. Change the Default Audio Sample Rate to 16000, then click the Close button. Relaunch OpenShot for the change to take effect. Please make sure you use the 16kHz device before launching OpenShot, or the application will crash.
> 
> This worked for me. Thank you!

Hello @dperygin.  Thank you for the FYI.
1.  Which version of OpenShot are you running (help | about Openshot?)
2.  What operating system/version are you running (Windows 10 Pro? Ubuntu 22.04 lts? etc?

I am asking because in the later versions of 3.1.1, including the daily builds, OpenShot will check the Default Audio Device that is set in the operating system, and whatever that default sample rate is, OpenShot will set the sample rate withing OpenShot to that.

**Comment by dperygin** [comment]
I am running OpenShot on:

Device name DESKTOP-4JSHRTD
Processor   AMD Ryzen 5 1600 Six-Core Processor               3.20 GHz
Installed RAM     16.0 GB
Device ID   869E05B0-7CEA-484A-91EF-EAEF6CAFDE89
Product ID  00326-10000-00000-AA989
System type 64-bit operating system, x64-based processor
Pen and touch     Pen support
Edition    Windows 10 Home
Version     22H2
Installed on      ‎2/‎25/‎2023
OS build    19045.3393
Experience  Windows Feature Experience Pack 1000.19044.1000.0

I'm not sure why I am running an older version of Openshot. I downloaded it fairly recently.

Open Shot Version:

[cid:e22d97b5-3fad-48fc-bb4a-c1f4764bb7f6]
________________________________

**Comment by Colorjet3** [comment]
Thank you for that @dperygin.  It is difficult for me to decipher the CID to a version and build #.  In OpenShot, click on Help | About OpenShot.  Then please provide the information highlighted in Red in the image provided.

Thank you!

![image](https://github.com/OpenShot/openshot-qt/assets/59097181/5deaad1b-eaed-43d4-8b34-b3c2b9e4ddd9)

**Comment by globalstudiosai** [comment]
Hey guys I am having a similar problem, however, my operating system is Ubuntu 20. How do I change the default audio sample rate to 16000 on Ubuntu?
