### ISSUE TITLE
OpenShot won't open

### ISSUE THREAD

**Issue by ComradeJarif** [OpenShot/openshot-qt#5069]
***-----RESOLVED (Solution Below)-----***

**Describe the bug:**
When I run `openshot-qt.exe`, nothing happens.

**Steps to reproduce the behavior:**
Run `openshot-qt.exe`

**Expected behavior:**
OpenShot is supposed to open.

**System Details:**
- OpenShot Version: 3.3.0 
- Operating System: Windows 10 Home N

**Log Files:**
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/10315294/openshot-qt.log)

***-----SOLUTION-----***
Install the *Media Feature Pack* from here https://www.microsoft.com/en-us/software-download/mediafeaturepack

**Comment by Colorjet3** [comment]
Please download the latest DEV Daily Build from openshot.org/download/#daily and give it a try.

**Comment by ComradeJarif** [comment]
> Please download the latest DEV Daily Build from openshot.org/download/#daily and give it a try.

This is what pops up when I click the latest Dev Build link (https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v3.0.0-daily-10873-99aab0a1-f55ec5d0-x86_64.exe):

![image](https://user-images.githubusercontent.com/121558436/209850865-1a2ff7b4-f446-425c-9697-4a8ff72f3b67.png)

**Comment by ComradeJarif** [comment]
> Please download the latest DEV Daily Build from openshot.org/download/#daily and give it a try.

This is what I got...

![image](https://user-images.githubusercontent.com/121558436/209855505-e6278c47-d92c-4718-a12e-e5a713320d77.png)

**Comment by Colorjet3** [comment]
1.  Which version of Windows 10 (home, N, Pro?)
2.  Right click on the Openshot shortcut and select "Run As Administrator".   did this work?
3.  If step 2 did not work, did you get the same message?
4.  You should uninstall using Add or Remove Programs.
5.  Re-download the latest DEV Daily Build and install it again.
6.  Did step 5 make it work?  If not, continue with step 7.
7.  You most likely have something going on in your Windows 10 setup.  Do a search on the error message and see what steps you need to take to remedy this issue.

**Comment by ComradeJarif** [comment]
1. Windows 10 Home N.
2. This didn't work.
3. I didn't get any message. Nothing happened.
4. Done.
5. Installed `OpenShot-v3.0.0-daily-10873-99aab0a1-f55ec5d0-x86_64.exe (64-bit)`.
6. It did not make it work. I got the same error message as in my previous comment. For some reason, the error message doesn't pop up when I run the `openshot-qt.exe`, only when I tick "Launch OpenShot" during setup.
7. I'll look into it.

BTW, have you checked the `openshot-qt.log` file? It says something about not being able to import something. 

Anyways, thank you.

**Comment by Colorjet3** [comment]
The fact that you have Windows 10 Home you need to install the windows 10 media feature pack.  https://www.microsoft.com/en-us/software-download/mediafeaturepack

**Comment by ComradeJarif** [comment]
> The fact that you have Windows 10 Home you need to install the windows 10 media feature pack. https://www.microsoft.com/en-us/software-download/mediafeaturepack

Thank you very much! OpenShot is working now. That is what I was missing.

**Comment by Colorjet3** [comment]
That is great @ComradeJarif and thank you for your confirmation as it will help other users as well.
