### ISSUE TITLE
Fade from Click n Drag causes crash

### ISSUE THREAD

**Issue by eliot2** [OpenShot/openshot-qt#507]
Right click video in timeline > fade >  play in-editor = no crash
drag fade from transition menu > play in-editor = crash

Willing to assist in debugging, need to know what needs to be tried.

**Comment by jreynojustin** [comment]
Hi Elliot,

Please make sure you have the latest version by downloading our latest daily installer:

1.  www.openshot.org/download - click '**Other Downloads**' link and grab the newest one
2.  Then enable 'Debug Mode (Verbose)' in the Preferences
3.  Quit OpenShot and delete both log files:
  - **/.openshot_qt/openshot_qt.log**
  - **/.openshot_qt/libopenshot.log**
4.  Re-launch OpenShot and trigger the crash as quickly as possible (to keep the log files small)
5.  Attach **both** log files here

Hopefully we can determine from the .log files what is happening (and crashing). Please also identify the operating system and version in which you are running the application and any specific steps to help reproduce this bug.

Once you obtain the necessary logs and other information please reply to the issue and we will try to recreate and address it.

Thanks for contributing feedback! If we don't receive a response after 72 hours your issue may be closed.

**Comment by jonoomph** [comment]
@eliot2 Also, please include the following details:
OS: 
OpenShot Version:
And please test with our latest daily build.

Please reopen this issue if you still experience the issue after testing the latest build. Thanks!
