### ISSUE TITLE
Programm start an crash by Windows 7 last Version!

### ISSUE THREAD

**Issue by Ragnaroeko** [OpenShot/openshot-qt#5072]
Hello i am from Germany.

Programm start an crash by Windows 7 last Version!

Problemsignatur:
Problemereignisname: APPCRASH
Anwendungsname: openshot-qt.exe
Anwendungsversion: 3.0.0.0
Anwendungszeitstempel: 607466f6
Fehlermodulname: libopenshot.dll
Fehlermodulversion: 0.0.0.0
Fehlermodulzeitstempel: 63892647
Ausnahmecode: c0000005
Ausnahmeoffset: 00000000000d5f62
Betriebsystemversion: 6.1.7601.2.1.0.256.1
Gebietsschema-ID: 1031
Zusatzinformation 1: bba5
Zusatzinformation 2: bba5427d622b981542e41f3d908fc5bc
Zusatzinformation 3: a303
Zusatzinformation 4: a30337ce5b58c7c892dbc13342222adf

eM@il: Andre-Jaeger@gmx.net

Mit freundlichen Grüßen aus Unterfranken
best regards from germany unterfranken

**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 3.0.0
- libopenshot Version:  0.3.0
- Platform: Windows-7-6.1.7601-SP0
- Processor: Intel64 Family 6 Model 30 Stepping 5, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['de-DE']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.0.0-daily-10873-99aab0a1-f55ec5d0-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/5vd02heye591cudfk8cktwyk4q8l6bo3/openshot-qt.zip) (9 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by Ragnaroeko** [comment]
Old Version 2.6.1 Work on Windows 7

The New Version 3.0 Crash by Start

**Comment by Colorjet3** [comment]
This is a known bug.  Go to openshot.org/download/#daily and download the latest DEV Daily Build.  Install and give it a try.

**Comment by Ragnaroeko** [comment]
> This is a known bug. Go to openshot.org/download/#daily and download the latest DEV Daily Build. Install and give it a try.

Thank you, it Works ;-)

**Comment by Colorjet3** [comment]
That is awesome @Ragnaroeko and thank you for the FYI.

**Comment by radorn** [comment]
How can a major version have such an obvious bug and be left as the recommended download for about a month and a half? I'm on a rather stringent mobile data plan and I just blew 185MB on the crashy v3.0.0 for nothing.

Oh well... Thanks for the tip on the dev versions. It does work now.

**Comment by Colorjet3** [comment]
Hello @radorn I can empathize with you and completely understand your frustration.  However, and this is not an excuse, but with very limited staff resources (developers and testers), mainly depending on volunteers, and limited funding, it is bound to happen.  It is OpenSource, but I myself expect a more stable product.  The technical lead has taken over the main/major development cycle process and changes will be coming fast.  So, here and there one or two issue will slip through.  So, my realistic expectation is that there will be more minor release with several daily builds in between for a good year yet.  After that I expect the product to be very stable on all platforms.

The OpenShot team is alway looking for volunteers (developers, testers, support, etc.).  If you know anyone that is interested, give them a nudge.

Best of luck with you projects.

**Comment by radorn** [comment]
I understand the limitations of an open source project with no stable funding.
I understand somewhat less why there isn't a note in the download page about what you qualified as a "KNOWN bug".
I don't know, something to the effect of "This release has been reported to crash on startup by some users. You may find a fixed release in the development builds section".
I don't know what's the organizational structure of the OpenShot team, and maybe I'm wrong, but from where I'm standing, it doesn't sound like something terribly hard to do. Maybe there's a problem impeding that? I have no idea.

**Comment by Colorjet3** [comment]
Hello @radorn. Thank you again for your feedback.  Everything you have said is spot on.  Even the simplest things take time.  Just know that this team is trying their best to get back on track.
