### ISSUE TITLE
Sometimes unable to resize timeline overview (fixed by ctrl+scroll zoom in)

### ISSUE THREAD

**Issue by shodanx2** [OpenShot/openshot-qt#5075]
Using Openshot 3.0.0

Here is a demonstration, I try to resize the timeline overview window but cannot. 
The cursor changes to resize but nothing happens.
On the right side I cannot even catch the edge to resize

Then I ctrl-scroll in to zoom in, now I can move the window and resize it

https://user-images.githubusercontent.com/10621885/210306122-196f1d06-f6dc-49a8-ab5d-b5748ab27086.mp4

**Comment by Colorjet3** [comment]
What operating system are you running?  I am unable to replicate this issue in Windows 10 or Windows 11.

**Comment by shodanx2** [comment]
This is on windows 10. I haven't used openshot since, I will report back if I hit this bug again.

**Comment by Colorjet3** [comment]
Sounds good @shodanx2.  Good luck with your projects.
