### ISSUE TITLE
3.0.0 release tarball has been altered

### ISSUE THREAD

**Issue by dvzrv** [OpenShot/openshot-qt#5079]
**Describe the bug:**
Hi! I package this project for Arch Linux.
Due to a current rebuild I noticed, that the (autogenerated) tarball for 3.0.0 (https://github.com/OpenShot/openshot-qt/archive/refs/tags/v3.0.0.tar.gz) has been changed some time between 2022-12-02 (where I first downloaded it) and 2023-01-03 (where I'm now trying to reproduce the package).

Old checksums:
sha512sum: `c44c4ad25d321ea26e6fbafd8df0fca7dd2d7fc0827de208f60ebe98b0615e0f3d594660e6b482ebab25216cc26c9ece5b92bb6f26ab60d2e731d2194cc3e774`
b2sum: `777f3e12932e08b2b2811ae10ba3c86ef8b64e821b1742d54e8b0c1cb3de544bcbd9b2a1544bc5b48c38066c9d106ac224888b4f3064b15963c69b36dcfabc51`

New checksums:
sha512sum: `d1115095b34937419d0f08aadacc849768a97ba5d3866a46cb8d416a26ac7fbb754b383c99ea8cb70291bd08cec0343191e71cfdd19c046bbd1a43541fc0673a`
b2sum: `1e7bd8921a472e4ff62b160d67fcb5a8d8c0e6614a28cce87db5078fae5401c69610bd44801344da55fc4df3c8f973263b75a8567d4372fc350f76dbeec428a1`

The diffoscope log  between the old and the new 3.0.0 is *huge* (and implies the new tarball has been created on 2022-12-08):
[openshot-3.0.0-diffoscope.log](https://github.com/OpenShot/openshot-qt/files/10335403/openshot-3.0.0-diffoscope.log)

*Please* respond to this ticket so it can be assessed whether this is a [supply chain attack](https://en.wikipedia.org/wiki/Supply_chain_attack) or whether you have moved the 3.0.0 tag.

Even though my current assumption is, that you have moved the tag, it is impossible for me to judge from the outside, as I would need to do an in-depth code analysis. This is not feasible for a volunteer like me.
Please do not move tags, as this breaks reproducible builds downstream, raises alarm bells and requires people to write lengthy tickets ;-)

**Steps to reproduce the behavior:**
1. Download tarball for 3.0.0 on 2022-12-02
2. Download tarball for 3.0.0 on 2023-01-03

**Expected behavior:**
Tags are *never* moved. Tarballs *never* change.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 3.0.0
- Operating System / Distro: Arch Linux

**Log Files:**
n/a

**Exception / Stacktrace:**
n/a

**Screenshots:** (Optional)
n/a

**Comment by dvzrv** [comment]
Had forgotten a dependency when creating the diffoscope log, which now gives a clearer picture of the changes in the JSON and JavaScript files: 
[openshot-3.0.0-diffoscope.log](https://github.com/OpenShot/openshot-qt/files/10335544/openshot-3.0.0-diffoscope.log)

**Comment by dvzrv** [comment]
The new tarball seems to include e.g. the changes from https://github.com/OpenShot/openshot-qt/commit/8745abe621c7b8b35b2a474908693a4b11aecde9, https://github.com/OpenShot/openshot-qt/commit/ef046acd52e4edc15ffc5fd11e511cb2f31fdce1, etc.
Basically a bunch of commits created some time between 2022-12-01 and 2022-12-08.

@jonoomph why was no prerelease version used for the initial 3.0.0 tag (e.g. 3.0.0-beta1 or similar), if there have been obvious changes to the codebase afterwards? This would have prevented this problem and have given you the time to test the release in a safe environment.
A follow-up patch level release (e.g. 3.0.1) would have also been fine. Moving tags on the other hand is really problematic, as I just spent a couple of hours trying to figure out whether these are malicious changes or not :(

**Comment by Neustradamus** [comment]
A 3.0.1 version was the solution...

**Comment by dvzrv** [comment]
@Neustradamus maybe I'm missing something, but there is no 3.0.1 version released in this repository?

@Colorjet3 I understand you would like to close this issue, but could someone please at least acknowledge the problem? :cry:

**Comment by Colorjet3** [comment]
Hello @Neustradamus You are correct that there is no 3.0.1 release in the repository.  I will ping the lead developer for his input.

**Comment by Neustradamus** [comment]
@Colorjet3: Can you reopen this ticket before solution?
Thanks in advance.

**Comment by Colorjet3** [comment]
@Neustradamus Ticket is Open.

**Comment by jonoomph** [comment]
@dvzrv On Dec 1, 2022 I created the "Pre-Release" 3.0.0 release on GitHub, which also created the 3.0.0 tag. However, we made many changes between Dec 1st and Dec 8, 2022, which was our final commit in the 3.0.0 release. We then changed the "Pre-Release" status on GitHub to "Release". I do believe we had to delete the 3.0.0 tag in this timeframe, and re-generate it - during our publishing process. 

Hopefully this helps to explain what might have happened. I do not believe there was any bad actor involved, but more likely some confusion on the 3.0.0 "Pre-Release" tag vs the 3.0.0 "Release". Not sure how to avoid this in the future though... I'm open to suggestions. Thx!

**Comment by Neustradamus** [comment]
Currently the 3.0.0 tag: https://github.com/OpenShot/openshot-qt/releases/tag/v3.0.0 is https://github.com/OpenShot/openshot-qt/commit/8aaee8d12a4b61c61f782bd4369d443120205294

Previously I think it was another commit.

When you want to create a pre-release (tag + unstable release), you can tag x.x.x-dev1, x.x.x-alpha1, x.x.x-beta1, x.x.x-rc1...

**Comment by jonoomph** [comment]
I think the confusion is that GitHub creates the 3.0.0 label when I create the 3.0.0 "Pre-Release" object. However, it makes sense that people might see the 3.0.0 label and immediately assume this is the official release. Yeah, I probably need to append a `-rc` suffix to the initial label / pre-release... I'll see what I can do in the future.
