### ISSUE TITLE
Continuous integration with Travis ?

### ISSUE THREAD

**Issue by hadim** [OpenShot/openshot-qt#508]
Would that help @jonoomph ? I can try to submit a PR ?

**Comment by jonoomph** [comment]
Currently we use a home-brewed (and simple) continuous build strategy, which is compatible with Windows, Linux, and Mac. I also use BuildKite for GitHub integration on merge requests (to compile and run unit tests). I don't have any plans for Travis integration, unless you have something to contribute. Thanks.
