### ISSUE TITLE
Debian 12 support

### ISSUE THREAD

**Issue by Neustradamus** [OpenShot/openshot-qt#5081]
@jonoomph: It is planned to add in Debian 12 before freeze?
- https://tracker.debian.org/pkg/openshot
- https://release.debian.org/bookworm/freeze_policy.html

**Comment by jonoomph** [comment]
Sorry, I do not maintain the Debian side of things. I do make adjustments to the actual packaging (and version labels), but I have no idea when specific Debian releases are merged in, etc...
