### ISSUE TITLE
Cannot move clip along timeline

### ISSUE THREAD

**Issue by stephane-tessier** [OpenShot/openshot-qt#5082]
**Describe the bug:**
When I put a movie in the timeline it's ok.  
If I try to move it, it's moved in the main timeline, but **NOT** in the preview (blue) timeline.  
Also, the movie is **still played at the old location**.

**Steps to reproduce the behavior:**
1. Add a movie clip to timeline
2. Move it
3. Play the timeline

**Expected behavior:**
Everything should be updated as expected.

**System Details:**
- OpenShot Version : 3.0.0
- Operating System / Distro: Ubuntu 22.04 LTS

**Error log**
```
Could not convert argument QJsonValue(object, QJsonObject()) to target type QString .
```

**Screenshots:** 
![Screenshot from 2023-01-04 09-55-46](https://user-images.githubusercontent.com/2227881/210518850-4f581b02-749a-4f36-9df3-e299e3123c6e.png)
![Screenshot from 2023-01-04 09-54-25](https://user-images.githubusercontent.com/2227881/210518858-a1f34484-33b3-4573-8137-dded4c6c3963.png)

**Comment by Colorjet3** [comment]
Please go to openshot.org/download/#daily and download the latest DEV Daily build AppImage and give it a try.

**Comment by stephane-tessier** [comment]
Hi
It seems to solve the problem indeed.
Thanks!

**Comment by Colorjet3** [comment]
That is great @stephane-tessier
