### ISSUE TITLE
"Openshot Video Editor has stopped working" v3.0.0

### ISSUE THREAD

**Issue by ATOMICOOOOO** [OpenShot/openshot-qt#5086]
**Describe the bug:**
Openshot Video Editor crash immediately after start.

Installed Openshot v3.0.0. "Openshot Video Editor has stopped working" immediately after start
**Steps to reproduce the behavior:**
1. Start Open shot
2. See message: "Openshot Video Editor has stopped working. A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available"
3. Click "close program".

**Expected behavior:**
Use the program. 

**System Details:**
- OpenShot Version: 3.0.0
- Operating System" Windows 8.1

**Log Files:**
[openshot-qt.zip](https://github.com/OpenShot/openshot-qt/files/10369260/openshot-qt.zip)
[libopenshot.zip](https://github.com/OpenShot/openshot-qt/files/10369264/libopenshot.zip)

**Exception / Stacktrace:**
-

**Screenshots:** (Optional)
![OPENSHOT LOG](https://user-images.githubusercontent.com/122221684/211214328-b1a9f6ec-4028-4619-8628-7a51b53f6938.JPG)

**Comment by Colorjet3** [comment]
Please download the latest DEV Daily build from openshot.org/download/#daily and give it a try.

**Comment by ATOMICOOOOO** [comment]
> Please download the latest DEV Daily build from openshot.org/download/#daily and give it a try.

Thanks! it worked.

**Comment by Colorjet3** [comment]
That is awesome @ATOMICOOOOO!
