### ISSUE TITLE
Newer Daily versions won't open (Appimages)

### ISSUE THREAD

**Issue by TombyT** [OpenShot/openshot-qt#509]
I can no longer open openshot-qt past 2.10 including the daily releases. Upon opening the gui won't show up and the process consumes all available memory. The last lines in the output log are as follows :+1: 

logger_libopenshot:INFO Timeline::GetFrame (Add frame to cache) (frame_number=2.0000, info.width=1920.0000, info.height=1080.0000)
logger_libopenshot:INFO Timeline::GetFrame (Add frame to cache) (frame_number=4.0000, info.width=1920.0000, info.height=1080.0000)
logger_libopenshot:INFO Timeline::GetFrame (Add frame to cache) (frame_number=8.0000, info.width=1920.0000, info.height=1080.0000)
logger_libopenshot:INFO Timeline::GetFrame (Add frame to cache) (frame_number=5.0000, info.width=1920.0000, info.height=1080.0000)
logger_libopenshot:INFO Timeline::GetFrame (end parallel region) (requested_frame=1.0000, omp_get_thread_num()=0.0000)

**Comment by jonoomph** [comment]
Please let me know the following:
OS:
OpenShot Version:
Please attach log files (if possible)
Also, please test on the very latest daily AppImage.

Please reopen the issue if you are still having issues. Thanks!
