### ISSUE TITLE
When dragging a reversed transition (e.g. "Barr ripple 12"), it loses its reversedness

### ISSUE THREAD

**Issue by peterdemaeyer** [OpenShot/openshot-qt#5090]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior**
1. Create some video fragments on the timeline and a transition (I used "Barr ripple 12") between them that needs to be reversed.
2. Right-click and do 'Reverse Transition'.
3. Drag the marker a little bit before the transition and play the preview to verify that the transition has indeed been reversed. 
4. Drag the transition away from its original position.
5. Drag the transition back to its original position.
6. Drag the marker again to verify like before. You'll see that the reversedness of the transition has been undone.

**Workaround**
Re-apply 'Reverse Transition' on the transition.

**Expected behavior**
Dragging transitions around on the timeline should preserve their reversedness.

**System Details**
- OpenShot Version: 3.0.0
- libopenshot Version:  0.3.0
- Platform: Linux-5.19.0-29-generic-x86_64-with-glibc2.4
- Processor: x86_64
- Machine: x86_64
- Python version: 3.8.10
- Qt5 version: 5.12.8
- PyQt5 version: 5.14.1
- Qt Detected Languages: ['en']
- LANG Environment Variable: en_US.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.0.0-daily-10912-510a7690-b5bbab66-x86_64.AppImage

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/a4en7bddqm2l8r4jgav64vvwi9j2irgs/openshot-qt.zip) (24 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by izzostar** [comment]
I have some weirdness too with transitions, by memory it was just dragging new clips to the end of previous one.
Have not changed transition options myself in this version 3 of openshot.

**Comment by Colorjet3** [comment]
I am able to replicate this issue as well.  I am going to submit an internal issue ticket for the lead developer to review and approve to be fixed in a future release.

Really appreciate you bringing this to the attention of the team.

**Comment by Colorjet3** [comment]
There is a new release of v3.0.0 Daily Build that fixes some of the issues with Transitions and how they are applied.  Please go to openshot.org/download/#daily.  Download the latest DEV Daily available, install it and give it try.  The "Reverse Transition" function is still an issue and you just need to be aware of it.  The "Reverse Transition" has some additional implications and in it's current implementation requires some more planning to decide how to move forward.

If you run into other issues with transitions, it would really help if you provide a step-by-step of what exactly your are doing.  The more detail you provide, it will make it easier to try and replicate it.  This will make it easier to troubleshoot.
