### ISSUE TITLE
Add Build for Windows on ARM

### ISSUE THREAD

**Issue by fzhwenzhou** [OpenShot/openshot-qt#5094]
By now, OpenShot doesn't have an official build for Windows on ARM. But it's totally possible, because Python and Qt announced that they support Windows on ARM natively. I would be happy to see that OpenShot can run on this platform too. Thank you very much. I would like to offer my hand to compile and test as I just bought a WoA laptop.

**Comment by AaronNGray** [comment]
OpenShot is avaliable on Debian, and thus Armbian for example :- https://packages.debian.org/source/bookworm/openshot-qt
Being Python based it should work on both armv7h, and arm64.
