### ISSUE TITLE
Cyrillic characters not rendered in animated titles 

### ISSUE THREAD

**Issue by Sidder3** [OpenShot/openshot-qt#5095]
**Describe the bug**
Cyrillic characters not rendered in animated titles 

**Steps to reproduce the behavior:**
1. Go to 'Title/Animated Title'
2. Click on 'Template Blur'
3. Start entering Cyrillic font in titles (ex. Russian, Ukrainian), click refresh
4. See error - Latin characters are rendered, Cyrillic are not

**Expected behavior**
I expect Cyrillic characters to be rendered in same way as Latin

**System Details**
- OpenShot Version: 3.0.0
- libopenshot Version:  0.3.0
- Platform: Windows-10-10.0.19041
- Processor: AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.0.0-daily-10926-510a7690-b5bbab66-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/iozyi22l17uywnzafoxg7opwisy54882/openshot-qt.zip) (7 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/iozyi22l17uywnzafoxg7opwisy54882/libopenshot.zip) (1 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
             
![Screenshot 2023-01-15 095924](https://user-images.githubusercontent.com/122721917/212534925-c2d9ad0e-c17d-4b59-adee-78edfc51a41c.png)

**Comment by Colorjet3** [comment]
This issue has been replicated and seems to be a bug.  An internal ticket has been created to work on the issue:  https://trello.com/c/xQ5IoR2k/94-blender-and-windows-default-and-custom-fonts-integration-in-windows-this-should-be-looked-at-in-linux-as-well

**Comment by Colorjet3** [comment]
An internal ticket has been created to address this issue.
