### ISSUE TITLE
il file audio inserito, viene riprodotto accelerato

### ISSUE THREAD

**Issue by lianascia** [OpenShot/openshot-qt#5098]
**Descrivi il bug**
A clear and concise description of the issue

**Passi per riprodurre questo comportamento:**
1. Vai su '...'
2. Fai clic su '....'
3. Scorri fino a '....'
4. Nota l'errore

**Comportamento atteso**
Una descrizione breve e concisa di cosa ci si aspetta dovrebbe succedere.

**Dettagli di sistema**
- OpenShot Version: 3.0.0
- libopenshot Version:  0.3.0
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['it-IT', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Build giornaliera: Passaggio ignorato

**File di registro**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/ikf33i39fm8u48f205erj11uh3bklpxm/openshot-qt.zip) (5 KB)
- libopenshot.log: File troppo piccolo o vuoto (non caricato)

**Errore / Stack trace**
```No stacktrace found in log files```

**Schermate** (Facoltativo)
Ove possibile e pertinente, aggiungi screenshot per spiegare il problema. Per farlo, copiali e incollali su GitHub o trascinali direttamente nella pagina GitHub. Dal momento che tutte le immagini condivise sono pubbliche,
ti suggeriamo di non pubblicare mai screenshot contenenti informazioni personali.

**Comment by Colorjet3** [comment]
Hello @lianascia,

Este es un problema con v3.0.0-Release-Candidate. Para solucionar el problema:

1. Vaya a openshot.org/download/#daily.

2. Descargue el último DEV Daily disponible e instálelo.

3. Inicie Openshot y vaya a Editar | Preferencias | Pestaña de vista previa.

4. Cambie la frecuencia de muestreo de audio predeterminada a 48000.

5. Reinicie Openshot y todo debería estar bien.
