### ISSUE TITLE
Audio-Spur wird mit 1 Sekunde Verzögerung zum Video abgespielt

### ISSUE THREAD

**Issue by DJ1NG** [OpenShot/openshot-qt#5100]
**Beschreiben Sie den Fehler**
Wenn ich ein Video importiere und anschliessend auf einen Track in der Zeitleiste ziehe und wiederum dann das Playback starte, wird der Audio-Track mit mindestens einer Sekunde Verzögerung abgespielt. 

**Schritte zum Reproduzieren des Verhaltens**
1. Video importieren (Formatunabhängig)
2. Video in Timeline schieben
3. Playbaack starten

**Erwartetes Verhalten**
Wenn ich das gleiche Stück Video beispielsweise mit dem VLC-Player abspiele, dann ist alles synchron. Nur wenn ich das Video über OpenShot abspiele, ist nichts mehr synchron. Die Verzögerung beträgt mindestens eine Sekunde.

Die Fehlerhistory (vielleicht hilft das was):
Nach 14 Tagen "Nicht-Nutzung" wollte ich ein Video schneiden. Beim Playback hab eich festgestellt, dass der Tone ca. 25% langsamer abgespielt wird als das Video selbst.
Dann habe ich erstmalig auf den Daily Build upgedatet. Und dann kam das oben beschriebene Verhalten: Der Ton war wieder in der richtigen Geschwindigkeit, aber eben mit Verzögerung.
Ein erneutes Update auf den Daily build hat nichts gebracht.

**Systemdetails**
- OpenShot Version: 3.0.0
- libopenshot Version:  0.3.0
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['de-DE', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verifiziertes Problem exsitiert immer noch im Daily Build:  http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.0.0-daily-10937-510a7690-b5bbab66-x86_64.exe

**Logdateien**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/d35s15uuztdinwonbha11ktmdyawakbc/openshot-qt.zip) (76 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/d35s15uuztdinwonbha11ktmdyawakbc/libopenshot.zip) (1 KB)

**Ausnahme / Stapelverfolgung**
```No stacktrace found in log files```

**Bildschirmfotos** (Optional)
Wenn möglich, fügen Sie Screenshots zur unterstützenden Erklärung Ihres Problems hinzu. Sie können Screenshots einfügen,
indem Sie diese kopieren und auf Github einfügen oder durch Drag and Drop zur GitHub-Seite hinzufügen. Alle Bilder sind öffentlich zugänglich, posten Sie deshalb keine Screenshots die persönliche Informationen enthalten.

**Comment by Colorjet3** [comment]
1. Start Openshot
2. Go to Edit | Preferences | Preview tab.
3. Change the Default Audio Sample rate to 48000.
4. Restart OpenShot.

This should fix the issues.

Translated/Übersetzt
1. Starten Sie OpenShot
2. Gehen Sie zu Bearbeiten | Einstellungen | Registerkarte „Vorschau“.
3. Ändern Sie die Standard-Audio-Abtastrate auf 48000.
4. Starten Sie OpenShot neu.

Dies sollte die Probleme beheben.

**Comment by DJ1NG** [comment]
Unfortunately it did not help.
The Sample rate was preset to 48000 after installation.
I've changed the sample rate to 44100 (with restart), tested it (failure still there).
The i've changed it back to 48000 (with restart), tested it - failure still there!

I've made a movie from this behaviour. As you can see: On playback the cursor starts moving, the video starts moving - and the sound came about 1 second later. 

I've placed the movie here: https://app.box.com/s/69ydsufi52tn1q6pugs2x23oknylvwi1
-------------------
Leider gab es keine Abhilfe durch den Tipp.
Die Voreinstellung nach der INstallation war bereits 48000.
Zum testen habe ich auf 44100 gestellt, neu gebootet - Fehler noch vorhanden
Dann wieder zurück auf 48000, neu gebootet - Fehler immer noch vorhanden.

Ich habe ein Testvideo erstellt. Dort kann man ganz genau sehen, dass beim Playback-Start Video und Cursor loslaufen - aber der Ton erst nach 1 Sekunde verzögerung kommt.

Das Video ist hier zu finden: https://app.box.com/s/69ydsufi52tn1q6pugs2x23oknylvwi1

**Comment by Colorjet3** [comment]
Thank you @DJ1NG for all the information and the video.  If this is the original video it is off by a 2nd from the start.  OpenShot do not have a feature to fix audio/video synchronization issues.  You will need to use a tool like VLC or Audacity to fix it.  However, one thing you can do in OpenShot is this:

1.  Select and right click on your video clip on Track 5.
2.  Select Separate Audio | Single Clip.  This will separate the audio from the video.  The audio clip will be right below the video clip on Track 4.
3.  Make sure that your video clip is still selected (should have the Red border line).
4. Right click and select Properties so you can see the Properties window.
5. Find the Position attribute and change the value of 0 to 1.0.  You can use your mouse to click on the 0.00 and drag back and forth or double click on the 0.00 value and type 1.0 and press the Enter key.  This will move your clip 1 second over on the timeline.
6. Now click on play and your audio should be in sync.  Adjust the position until you are happy with the result.

Translated to German

Danke @DJ1NG für all die Informationen und das Video. Wenn dies das Originalvideo ist, ist es von Anfang an um eine Sekunde daneben. OpenShot verfügt nicht über eine Funktion zur Behebung von Audio-/Video-Synchronisationsproblemen. Sie müssen ein Tool wie VLC oder Audacity verwenden, um das Problem zu beheben. Eine Sache, die Sie jedoch in OpenShot tun können, ist dies:

1. Wählen Sie Ihren Videoclip auf Spur 5 aus und klicken Sie mit der rechten Maustaste darauf.
2. Wählen Sie Separates Audio | Einzelklipp. Dadurch wird das Audio vom Video getrennt. Der Audioclip befindet sich direkt unter dem Videoclip auf Spur 4.
3. Stellen Sie sicher, dass Ihr Videoclip immer noch ausgewählt ist (sollte die rote Umrandung haben).
4. Klicken Sie mit der rechten Maustaste und wählen Sie Eigenschaften, damit Sie das Eigenschaftenfenster sehen können.
5. Suchen Sie das Attribut Position und ändern Sie den Wert von 0 auf 1,0. Sie können mit der Maus auf 0,00 klicken und hin und her ziehen oder auf den Wert 0,00 doppelklicken und 1,0 eingeben und die Eingabetaste drücken. Dadurch wird Ihr Clip auf der Timeline um 1 Sekunde verschoben.
6. Klicken Sie nun auf Play und Ihr Audio sollte synchron sein. Passen Sie die Position an, bis Sie mit dem Ergebnis zufrieden sind.

**Comment by Colorjet3** [comment]
Hello @DJ1NG Did you get a chance to try this?

**Comment by DJ1NG** [comment]
CAUGHT IT!!!!

It was a settings problem. 
The preview Tab of the settings menu has a parameter calld "Audio playback device". I've compared the settings to different computer without that issue and discovered the the audio device was using "Direct sound: USB Speaker". 

The different computer uses "Preset" and so i switched it back to "preset" 
BAAMMM
The issue disappeared. - MAGIC ;-)

I can reproduce this issue at any time by switching the audio playback device to the "Direct sound" setting.
Put it back to "preset", the audio playback is on time again. 

I wouldn't have found it, if i hadn't the chance to compare the settings with a different computer.

Thank you for help.

--------------------
German:

Der Fehler des verzögerten Abspielens liegt in den Einstellungstab VORSCHAU. Hier war das Audiowiedergabegerät (warum auch immer) so eingestellt, dass es "Directsound USB Audio" nutzte.

Nach dem Vergleich mit einer INstallation auf einem anderen Computer habe ich das Audiowiedergabegerät auf "Vorgabe" gestellt: Das hat geholfen. Nun wird der Autio-Track ohne Verzögerung abgespielt. 

Der Fehler lässt sich jederzeit reproduzieren in dem man zu einem Directsound-Device wechselt.

Danke für den Support.

**Comment by Colorjet3** [comment]
This is great @DJ1NG Best of luck with your project(s).
