### ISSUE TITLE
Importing files closes OpenShot

### ISSUE THREAD

**Issue by izzostar** [OpenShot/openshot-qt#5101]
**Describe the bug**
Importing video files closes OpenShot

**Steps to reproduce the behavior:**
1. Go to File->Import Files
2. Select some videos in a folder
3. Click open
4. OpenShot kills itself (window disappears)
Sometimes the first import succeeds, and importing additional files mishappens.

**Expected behavior**
OpenShot imports video files.

**System Details**
- OpenShot Version: 3.0.0
- libopenshot Version:  0.3.0
- Platform: Linux-5.15.0-58-generic-x86_64-with-glibc2.35
- Processor: x86_64
- Machine: x86_64
- Python version: 3.10.6
- Qt5 version: 5.15.3
- PyQt5 version: 5.15.6
- Qt Detected Languages: ['en-GB']
- LANG Environment Variable: en_GB.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Skipped this step

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/q66lst91wb93cwlj1tam6h3rfnulm56z/openshot-qt.zip) (69 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/q66lst91wb93cwlj1tam6h3rfnulm56z/libopenshot.zip) (24 KB)

**Exception / Stacktrace**
```/usr/lib/python3/dist-packages/_openshot.cpython-310-x86_64-linux-gnu.so swig::SwigPyForwardIteratorOpen_T<std::_Rb_tree_iterator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, swig::from_oper<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::value() const 0x16  [0x7fbc091e1ec6]
/usr/lib/python3/dist-packages/_openshot.cpython-310-x86_64-linux-gnu.so                                          0xbc8fd  [0x7fbc090f08fd]
/usr/bin/python3                                                        0x15b564  [0x557daa099564]
/usr/bin/python3               _PyEval_EvalFrameDefault                 0x2a70  [0x557daa0853b0]
/usr/bin/python3               _PyFunction_Vectorcall                   0x7c  [0x557daa09a3ac]
/usr/bin/python3               _PyEval_EvalFrameDefault                 0x80a  [0x557daa08314a]
/usr/bin/python3               _PyFunction_Vectorcall                   0x7c  [0x557daa09a3ac]
/usr/bin/python3               _PyEval_EvalFrameDefault                 0x6c5  [0x557daa083005]
/usr/bin/python3                                                        0x16a391  [0x557daa0a8391]
/usr/bin/python3               _PyEval_EvalFrameDefault                 0x6c5  [0x557daa083005]
/usr/bin/python3               _PyFunction_Vectorcall                   0x7c  [0x557daa09a3ac]
/usr/bin/python3               _PyEval_EvalFrameDefault                 0x80a  [0x557daa08314a]
/usr/bin/python3               _PyFunction_Vectorcall                   0x7c  [0x557daa09a3ac]
/usr/bin/python3               _PyEval_EvalFrame...

**Comment by izzostar** [comment]
That was with brand new Lubuntu 22.04 install, but i already had shotcut installed too. Hopefully it does not interfere somehow.
Now im gonna try that DEV PPA of openshot.
Nope, still closes itself.

**Comment by Colorjet3** [comment]
Please try the latest DEV Daily Build AppImage and see if that works.  You can find the latest DEV Daily build at openshot.org/download/#daily.

**Comment by izzostar** [comment]
In the ppa versions i tried importing with select all... that throw a "Path /bla-bla/ does not exist" error.
So now, the 16. of january dev AppImage so far so good. Loading in the middle of 1300 files right now, since i selected all again for some no reason. 
Can one stop the import in the middle of working or cancel it altogether somehow :P
I guess a feature request is needed for that kind of button.

(Another thing that closes the old PPA version is when selecting VA-API in perfomance preferences and hit "test".
In daily AppImage the "x" shows in the test button.)

Yes, the daily AppImage imported files without closing itselt.

**Comment by Colorjet3** [comment]
Hello @izzostar Glad things are working better for your with the latest DEV Daily.
1. Stopping importing - this would be a feature enhancement.  So, no, you can not stop the importing process.  It just needs to complete.
2. VA-API causes the old PPA to crash.  There were a few fixes in the latest DEV Daily build and also some new experimental features in the Performance.  All I can tell you is that those features are not fully baked.  Tread lightly.

Good luck with your project(s).

**Comment by izzostar** [comment]
Openshot closing while importing files again.
Terminal output:

`~$` openshot-qt
Loaded modules from: /usr/lib/python3/dist-packages/openshot_qt
INFO app: ------------------------------------------------
INFO app:             Mon Apr 10 18:28:49 2023            
INFO app:               Starting new session              
INFO app: ------------------------------------------------
INFO app:             OpenShot (version 3.1.0)            
INFO app: ------------------------------------------------
INFO app: openshot-qt version: 3.1.0
INFO app: libopenshot version: 0.3.1
INFO app: platform: Linux-5.15.0-69-generic-x86_64-with-glibc2.35
INFO app: processor: x86_64
INFO app: machine: x86_64
INFO app: python version: 3.10.6
INFO app: qt5 version: 5.15.3
INFO app: pyqt5 version: 5.15.6
INFO project_data: Setting profile to FHD 1080p 30 fps
INFO project_data: Apply default audio playback settings: 48000, 2 channels
INFO app: checking babl_ext_path: /usr/lib/python3/dist-packages/openshot_qt/lib/babl-ext
Screen eDP-1
   devicePixelRatio: 1.25
   logicalDotsPerInch: 96.0
   physicalDotsPerInch: 133.07929258454854
   availableSizes: PyQt5.QtCore.QSize(1536, 840)
INFO language: Qt Detected Languages: ['en-GB']
INFO language: LANG Environment Variable: en_GB.UTF-8
INFO language: LOCALE Environment Variable: 
INFO language: OpenShot Preference Language: Default
INFO app: Setting font to /usr/lib/python3/dist-packages/openshot_qt/images/fonts/Ubuntu-R.ttf
INFO app: Setting custom dark theme
INFO logger_libopenshot: Connecting to libopenshot with debug port: 5556
INFO ui_util: Initializing UI for MainWindow
INFO thumbnail: Starting thumbnail server listening on ('127.0.0.1', 54357)
Sandboxing disabled by user.
INFO webengine: WebEngine backend initializing
INFO transition_model: updating transitions model.
INFO version: Found current version: {'trans_rate_stable': 0.01, 'error_rate_unstable': 0.05, 'trans_rate_unstable': 0.001, 'openshot_version': '3.1.0', 'error_rate_stable': 0.5}
INFO effects_model: updating effects model.
INFO emoji_model: updating emoji model.
INFO sentry: Sentry initialized for 'production': 0.5 sample rate, 0.01 transaction rate
INFO main_window: InitCacheSettings
INFO main_window: cache-mode: CacheMemory
INFO main_window: cache-limit-mb: 512
INFO main_window: cache-ahead-percent: 0.7
INFO main_window: cache-preroll-min-frames: 24
INFO main_window: cache-preroll-max-frames: 48
INFO main_window: cache-max-frames: 600
INFO main_window: Creating CacheMemory object with 536870912 byte limit
INFO preview_thread: QThread Start Method Invoked
ERROR main_window: Unhandled crash detected: linux-/usr/lib/python3/dist-packages/_openshot.cpython-310-x86_64-linux-gnu.so swig::SwigPyForwardIteratorOpen_T<std::_Rb_tree_iterator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, swig::from_oper<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::value const 0x16 [0x7f40a681a9a6]
INFO main_window: updateStatusChanged
INFO main_window: recover_backup
INFO main_window: Recovering backup file: /home/meie/.openshot_qt/backup.osp
INFO settings: reducing file: /home/meie/.openshot_qt/backup.osp to dir: /home/meie/.openshot_qt
INFO settings: Ignore setting recent path: /home/meie/.openshot_qt, most likely due to backup recovery
INFO timeline: Adjusting max size of preview image: PyQt5.QtCore.QSize(775, 435)
INFO project_data: Setting profile to FHD 1080p 30 fps
INFO project_data: Apply default audio playback settings: 48000, 2 channels
INFO project_data: Loading project file: /home/meie/.openshot_qt/backup.osp
INFO project_data: checking project files...
INFO project_data: checking file /home/meie/Desktop/upload 2023.04.06/IMG_20230329_212006.jpg
INFO project_data: checking file /home/meie/Desktop/upload 2023.04.06/IMG_20230329_204017.jpg
INFO project_data: checking file /home/meie/Desktop/upload 2023.04.06/IMG_20230329_204012.jpg
INFO project_data: checking file /home/meie/Desktop/upload 2023.04.06/IMG_20230329_203805.jpg
INFO project_data: checking file /home/meie/Desktop/upload 2023.04.06/IMG_20230329_203752.jpg
INFO project_data: checking file /home/meie/Desktop/upload 2023.04.06/IMG_20230329_203741.jpg
INFO project_data: checking file /home/meie/Desktop/upload 2023.04.06/IMG_20230329_203322.jpg
INFO project_data: checking file /home/meie/Desktop/upload 2023.04.06/IMG_20230329_203320.jpg
INFO project_data: checking file /home/meie/Desktop/upload 2023.04.06/IMG_20230329_184534316.jpg
INFO project_data: checking file /home/meie/Desktop/upload 2023.04.06/IMG_20230329_175839.jpg
INFO project_data: checking file /home/meie/Desktop/upload 2023.04.06/IMG_20230329_175409.jpg
INFO project_data: checking file /home/meie/Desktop/upload 2023.04.06/IMG_20230329_175358.jpg
INFO project_data: checking file /home/meie/Desktop/upload 2023.04.06/IMG_20230329_175343.jpg
INFO project_data: checking file /home/meie/Desktop/upload 2023.04.06/IMG_20230329_175339.jpg
INFO project_data: checking file /home/meie/Desktop/upload 2023.04.06/IMG_20230329_175338.jpg
INFO project_data: checking file /home/meie/Desktop/upload 2023.04.06/IMG_20230329_175330.jpg
INFO project_data: checking file /home/meie/Desktop/upload 2023.04.06/IMG_20230329_175327.jpg
INFO project_data: checking file /home/meie/Desktop/upload 2023.04.06/IMG_20230329_175321.jpg
INFO project_data: checking file /home/meie/Desktop/upload 2023.04.06/IMG_20230329_175159.jpg
INFO project_data: checking file /home/meie/Desktop/upload 2023.04.06/IMG_20230329_175154.jpg
INFO project_data: checking file /home/meie/Desktop/upload 2023.04.06/IMG_20230329_175143.jpg
INFO project_data: checking file /home/meie/Desktop/upload 2023.04.06/IMG_20230329_175136.jpg
INFO project_data: checking file /home/meie/Desktop/upload 2023.04.06/IMG_20230329_175123.jpg
INFO project_data: checking file /home/meie/Desktop/upload 2023.04.06/IMG_20230329_175045.jpg
INFO project_data: checking file /home/meie/Desktop/upload 2023.04.06/IMG_20230329_175038.jpg
INFO project_data: checking file /home/meie/Desktop/upload 2023.04.06/IMG_20230329_175024.jpg
INFO project_data: checking file /home/meie/Desktop/upload 2023.04.06/IMG_20230329_175020.jpg
INFO project_data: checking file /home/meie/Desktop/upload 2023.04.06/IMG_20230329_175005.jpg
INFO project_data: checking file /home/meie/Desktop/upload 2023.04.06/IMG_20230329_174739.jpg
INFO project_data: checking file /home/meie/Desktop/upload 2023.04.06/IMG_20230329_174658.jpg
INFO project_data: checking file /home/meie/Desktop/upload 2023.04.06/IMG_20230329_174547.jpg
INFO project_data: checking file /home/meie/Desktop/upload 2023.04.06/IMG_20230329_174544.jpg
INFO project_data: checking file /home/meie/Desktop/upload 2023.04.06/IMG_20230329_133840008.jpg
INFO project_data: Project data: openshot 3.1.0, libopenshot 0.3.1
INFO project_data: Setting profile to FHD 1080p 30 fps
INFO project_data: Apply default audio playback settings: 48000, 2 channels
INFO video_widget: Load: Set video widget display aspect ratio to: 1.7777777910232544
INFO video_widget: Set video widget pixel aspect ratio to: 1.0
INFO main_window: updateStatusChanged
INFO main_window: updateStatusChanged
INFO main_window: updateStatusChanged
INFO timeline: Adjusting max size of preview image: PyQt5.QtCore.QSize(776, 469)
INFO main_window: Loaded project /home/meie/.openshot_qt/backup.osp
INFO webengine: Registering WebChannel connection with WebEngine
WARNING webengine: WebEngine backend still not ready after 5 retries.
Property 'modal'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'windowModality'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'enabled'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'geometry'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'frameGeometry'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'normalGeometry'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'x'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'y'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'pos'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'frameSize'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'size'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'width'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'height'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'rect'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'childrenRect'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'childrenRegion'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'sizePolicy'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'minimumSize'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'maximumSize'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'minimumWidth'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'minimumHeight'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'maximumWidth'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'maximumHeight'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'sizeIncrement'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'baseSize'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'palette'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'font'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'cursor'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'mouseTracking'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'tabletTracking'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'isActiveWindow'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'focusPolicy'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'focus'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'contextMenuPolicy'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'updatesEnabled'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'visible'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'minimized'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'maximized'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'fullScreen'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'sizeHint'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'minimumSizeHint'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'acceptDrops'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'windowOpacity'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'windowModified'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'toolTip'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'toolTipDuration'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'statusTip'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'whatsThis'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'accessibleName'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'accessibleDescription'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'layoutDirection'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'autoFillBackground'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'styleSheet'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'locale'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'windowFilePath'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'inputMethodHints'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'title'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'url'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'selectedText'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'hasSelection'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'zoomFactor'' of object 'TimelineWebView' has no notify signal and is not constant, value updates in HTML will be broken!
WARNING webengine: WebEngine backend still not ready after 5 retries.
WARNING webengine: WebEngine backend still not ready after 5 retries.
INFO webview: Qt Ready
INFO webview: Angular Ready
INFO main_window: Cleared temporary files: /home/meie/.openshot_qt/thumbnail
INFO main_window: Cleared backup: /home/meie/.openshot_qt/backup.osp
INFO main_window: Cleared temporary files: /home/meie/.openshot_qt/blender
INFO main_window: Cleared temporary files: /home/meie/.openshot_qt/title
INFO project_data: Setting profile to FHD 1080p 30 fps
INFO project_data: Apply default audio playback settings: 48000, 2 channels
INFO video_widget: Load: Set video widget display aspect ratio to: 1.7777777910232544
INFO video_widget: Set video widget pixel aspect ratio to: 1.0
INFO main_window: updateStatusChanged
INFO main_window: updateStatusChanged
INFO main_window: updateStatusChanged
INFO main_window: New Project created.
INFO timeline: Adjusting max size of preview image: PyQt5.QtCore.QSize(776, 469)
INFO files_model: Imported media file /home/meie/Desktop/upload 2023.04.06/VID_20230329_172539_T mängib hiiretipsu viiuliga Kullos.mp4
INFO main_window: updateStatusChanged
INFO files_model: Imported media file /home/meie/Desktop/upload 2023.04.06/VID_20230329_174409_T näitab ilusat poognakätt Kullos.mp4
Caught signal 11 (SIGSEGV)
---- Unhandled Exception: Stack Trace ----
  /usr/lib/python3/dist-packages/_openshot.cpython-310-x86_64-linux-gnu.so ( swig::SwigPyForwardIteratorOpen_T<std::_Rb_tree_iterator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, swig::from_oper<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::value() const  + 0x16  )  [0x7fd35fa439a6]
  /usr/lib/python3/dist-packages/_openshot.cpython-310-x86_64-linux-gnu.so (                                           + 0xbcf6d)  [0x7fd35f950f6d]
  /usr/bin/python3               (                                           + 0x15c3a4)  [0x56423b2253a4]
  /usr/bin/python3               ( _PyEval_EvalFrameDefault                  + 0x2a40)  [0x56423b210af0]
  /usr/bin/python3               ( _PyFunction_Vectorcall                    + 0x7c  )  [0x56423b2261ec]
  /usr/bin/python3               ( _PyEval_EvalFrameDefault                  + 0x81b )  [0x56423b20e8cb]
  /usr/bin/python3               ( _PyFunction_Vectorcall                    + 0x7c  )  [0x56423b2261ec]
  /usr/bin/python3               ( _PyEval_EvalFrameDefault                  + 0x6d5 )  [0x56423b20e785]
  /usr/bin/python3               (                                           + 0x16ac31)  [0x56423b233c31]
  /usr/bin/python3               ( _PyEval_EvalFrameDefault                  + 0x6d5 )  [0x56423b20e785]
  /usr/bin/python3               ( _PyFunction_Vectorcall                    + 0x7c  )  [0x56423b2261ec]
  /usr/bin/python3               ( _PyEval_EvalFrameDefault                  + 0x81b )  [0x56423b20e8cb]
  /usr/bin/python3               ( _PyFunction_Vectorcall                    + 0x7c  )  [0x56423b2261ec]
  /usr/bin/python3               ( _PyEval_EvalFrameDefault                  + 0x81b )  [0x56423b20e8cb]
  /usr/bin/python3               ( _PyObject_FastCallDictTstate              + 0xc4  )  [0x56423b21b634]
  /usr/bin/python3               (                                           + 0x166e94)  [0x56423b22fe94]
  /usr/bin/python3               ( _PyObject_MakeTpCall                      + 0x1fc )  [0x56423b21c44c]
  /usr/bin/python3               ( _PyEval_EvalFrameDefault                  + 0x6db6)  [0x56423b214e66]
  /usr/bin/python3               ( _PyFunction_Vectorcall                    + 0x7c  )  [0x56423b2261ec]
  /usr/bin/python3               ( _PyEval_EvalFrameDefault                  + 0x81b )  [0x56423b20e8cb]
  /usr/bin/python3               (                                           + 0x16ad7e)  [0x56423b233d7e]
  /usr/bin/python3               ( _PyEval_EvalFrameDefault                  + 0x2a40)  [0x56423b210af0]
  /usr/bin/python3               ( _PyFunction_Vectorcall                    + 0x7c  )  [0x56423b2261ec]
  /usr/bin/python3               ( _PyEval_EvalFrameDefault                  + 0x2a40)  [0x56423b210af0]
  /usr/bin/python3               ( _PyFunction_Vectorcall                    + 0x7c  )  [0x56423b2261ec]
  /usr/bin/python3               ( _PyEval_EvalFrameDefault                  + 0x63b2)  [0x56423b214462]
  /usr/bin/python3               ( _PyFunction_Vectorcall                    + 0x7c  )  [0x56423b2261ec]
  /usr/bin/python3               ( _PyEval_EvalFrameDefault                  + 0x81b )  [0x56423b20e8cb]
  /usr/bin/python3               (                                           + 0x16ae91)  [0x56423b233e91]
  /usr/bin/python3               (                                           + 0x296e5b)  [0x56423b35fe5b]
  /usr/bin/python3               (                                           + 0x28cf58)  [0x56423b355f58]
  /lib/x86_64-linux-gnu/libc.so.6 (                                           + 0x94b43)  [0x7fd360d0db43]
  /lib/x86_64-linux-gnu/libc.so.6 (                                           + 0x126a00)  [0x7fd360d9fa00]
---- End of Stack Trace ----
QSocketNotifier: Socket notifiers cannot be enabled or disabled from another thread
QObject::~QObject: Timers cannot be stopped from another `thread`

**Comment by Colorjet3** [comment]
Hello @izzostar.  

1.  Are you running the PPA in the AppImage?  
2.  Did you make any changes in Edit | Preferences section?  If yes, what?
3.  Does this happen with all files or just a specific one?  Have you tried different types (.mp4, .jpg, .mov, .mp3, etc?)  What are the results of those?

**Comment by izzostar** [comment]
1. I'm running both in parallel. 
    Because the PPA version kills itself, i import files with Appimage.
    The file selectors look different if im not mistaken, Lubuntu lets you sort files by name, date, etc. Appimage does not.
2. For starters i deleted the old settings file, after that definetly set resolution to FHD 30p. The PPA version has GPU-acceleration available, from last version that i updated from (3.0), but its not enabled for decode i think? I only use it for rendering (export video).
3. Type of files is the same, mp4-s from android phone. Only thing, they are renamed already before importing. 
   Some of them import, some dont, i need to test more i guess, if there is something in the filenames? But Appimage imports just fine.

(The VAAPI-exporting kills itself too with that project, havent tried other projects yet, but lastones GPU-exported fine in version 3.0 PPA)

**Comment by Colorjet3** [comment]
Hello @izzostar.  I am not sure running both versions in parallel is supported.  The issue is that both PPA and AppImage share the same /home/usersname/.openshot_qt folder.

I am going to escalate this to one of the technical support guys to look into.

**Comment by izzostar** [comment]
Hey, found it. Sorry i did not realize it before. Those android phone videos that crash my PPA version are vertical (the thumbnails in pcmanfm-qt file manager at least)
VLC info shows resolution is 1920x1080, orientation is: Left bottom. 
The AppImage version does not crash when importing the same files.

**Comment by Colorjet3** [comment]
Hello @izzostar.  Thank you for the update.  Is it possible to share one of your videos so I can play with it?  If you don't want to share it here feel free to send it to raffi@openshot.org.  Otherwise, just create some generic video with your phone and share it here.

**Comment by izzostar** [comment]
https://user-images.githubusercontent.com/15717394/231837711-a3ff001c-dd4d-41b7-8122-906067599545.mp4

**Comment by Colorjet3** [comment]
Hello @izzostar Thank you so much for sharing this file.  I used Ubuntu 22.04 lts and upon importing this file Openshot crashed as you indicated.  When I test importing on my Windows 10 environment it had no issue.

I went ahead and ran this file through Shutter Encoder and converted it (that's hard to type and read...LOL!) to h.264 mp4 and now I am able to import it.  Please See attached.

As of this writing there have been some additional bug fixes that may take care of this issue for you without having to convert.  However, you will need to run the AppImage instead for now.  You can decide which way to go.

1.  Go to openshot.org/download/#daily.
2.  Download the latest DEV Daily Build AppImage available.
3.  Run it and import your shared .mp4 (your trouble one) and see if it works. Then the fixes the DEV team just implemented is working.

Please keep me updated.

https://user-images.githubusercontent.com/59097181/231848540-a76219b5-1dfd-4ff4-b3e4-0d4b1ab59cfa.mp4
