### ISSUE TITLE
Openshot does not launch on ubuntu 22.04 64Bit

### ISSUE THREAD

**Issue by ArnoVersfeld** [OpenShot/openshot-qt#5103]
I used openshot on ubuntu 20.04 LTS. I then upgraded to ubuntu 22.04 LTS and had to reinstall openshot. 
I reinstalled openshot 2.5.1+dfsg1 from ubuntu-jammy-universe(deb) yesterday. 

**When I tried launching it, nothing happened. It didn't launch.** 

I uninstalled it today and reinstalled it. 
I tried launching it again but nothing happens. 
I get no error messages.

I would expect the icon to appear and disappear
or perhaps display an error message indicating the type of error.

**System Details:**
- OpenShot Version 2.5.1+dfsg1: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [Ubuntu 22.04.1 LTS  64Bit ]

**Log Files:**
I looked in /var for log files but found none. The only log files I found were from June 2022 when I last was able to use openshot on Ubuntu 20.04. 
In /home/arno/.openshot_qt I found libopenshot.log with the following entries for today:
------------------------------------------
libopenshot logging: Thu Jan 19 05:58:25 2023
------------------------------------------
------------------------------------------
libopenshot logging: Thu Jan 19 06:00:33 2023
------------------------------------------
------------------------------------------
libopenshot logging: Thu Jan 19 17:12:00 2023
------------------------------------------
------------------------------------------
libopenshot logging: Thu Jan 19 17:17:40 2023
------------------------------------------

**Exception / Stacktrace:**
n/a
**Screenshots:** (Optional)
nothing visible takes place.

**Comment by snooppr** [comment]
I think this one is the same: https://github.com/OpenShot/openshot-qt/issues/5040
run **console**: 
`$ ~./OpenShot-v3.0.0xxxxxx.AppImage` 
log:
`$ journalctl -f`

`chmod +x ~./OpenShot-v3.0.0xxxxxx.AppImage` ?

**Comment by ArnoVersfeld** [comment]
I reinstalled openshot version 2.5.1+dfsg1 this morning again. One again did not launch !
I found the following in the log file:

 app:INFO ------------------------------------------------
         app:INFO             Sat Jan 21 11:34:00 2023            
         app:INFO               Starting new session              
         app:INFO ------------------------------------------------
         app:INFO             OpenShot (version 2.5.1)            
         app:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.5.1
         app:INFO libopenshot version: 0.2.5
         app:INFO platform: Linux-5.15.0-58-generic-x86_64-with-glibc2.35
         app:INFO processor: x86_64
         app:INFO machine: x86_64
         app:INFO python version: 3.10.6
         app:INFO qt5 version: 5.15.3
         app:INFO pyqt5 version: 5.15.6
     metrics:ERROR Error determining OS version in metrics.py
    language:INFO Qt Detected Languages: ['en-GB', 'en']
    language:INFO LANG Environment Variable: en_GB.UTF-8
    language:INFO LOCALE Environment Variable: 
    language:INFO OpenShot Preference Language: Default
project_data:INFO Setting default profile to HD 720p 30 fps
         app:INFO Setting font to Cantarell
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
         app:INFO Setting custom dark theme
     ui_util:INFO Initializing UI for MainWindow
     metrics:INFO Track metric: [200] http://www.google-analytics.com/collect?cid=e5d076df-48f1-4681-a978-38f36aa5c28d&v=1&tid=UA-4381101-5&an=OpenShot+Video+Editor&aip=1&aid=org.openshot.openshot-qt&av=2.5.1&ul=en-us&ua=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&cd1=0.2.5&cd2=3.10.6&cd3=5.15.3&cd4=5.15.6&cd5=None&t=screenview&sc=start&cd=launch-app | (35 bytes)
     metrics:INFO Track metric: [200] http://www.google-analytics.com/collect?cid=e5d076df-48f1-4681-a978-38f36aa5c28d&v=1&tid=UA-4381101-5&an=OpenShot+Video+Editor&aip=1&aid=org.openshot.openshot-qt&av=2.5.1&ul=en-us&ua=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&cd1=0.2.5&cd2=3.10.6&cd3=5.15.3&cd4=5.15.6&cd5=None&t=screenview&sc=start&cd=launch-app | (35 bytes)
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "/usr/bin/openshot-qt", line 33, in <module>
    sys.exit(load_entry_point('openshot-qt==2.5.1', 'gui_scripts', 'openshot-qt')())
  File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 97, in main
    app = OpenShotApp(argv)
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 219, in __init__
    self.window = MainWindow(mode)
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/main_window.py", line 2521, in __init__
    self.timeline = TimelineWebView(self)
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/views/timeline_webview.py", line 3000, in __init__
    self.cache_renderer.setInterval(0.5 * 1000)
TypeError: setInterval(self, int): argument 1 has unexpected type 'float'
     metrics:INFO Track metric: [200] http://www.google-analytics.com/collect?cid=e5d076df-48f1-4681-a978-38f36aa5c28d&v=1&tid=UA-4381101-5&an=OpenShot+Video+Editor&aip=1&aid=org.openshot.openshot-qt&av=2.5.1&ul=en-us&ua=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&cd1=0.2.5&cd2=3.10.6&cd3=5.15.3&cd4=5.15.6&cd5=None&t=screenview&cd=main-screen | (35 bytes)
     metrics:INFO Track metric: [200] http://www.google-analytics.com/collect?cid=e5d076df-48f1-4681-a978-38f36aa5c28d&v=1&tid=UA-4381101-5&an=OpenShot+Video+Editor&aip=1&aid=org.openshot.openshot-qt&av=2.5.1&ul=en-us&ua=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&cd1=0.2.5&cd2=3.10.6&cd3=5.15.3&cd4=5.15.6&cd5=None&t=screenview&cd=main-screen | (35 bytes)
     version:INFO Found current version: {"error_rate_stable": 0.5, "error_rate_unstable": 0.05, "trans_rate_stable": 0.01, "trans_rate_unstable": 0.001, "openshot_version": "3.0.0"}
     metrics:INFO Track exception: [200] http://www.openshot.org/exception/json/ | *old-exception-ignored*

I notice  "metrics:ERROR Error determining OS version in metrics.py"

Is it something I can fix ?

**Comment by AzothAmmo** [comment]
This appears to be fixed in the latest version of Openshot (3.0). You can get it directly here: https://www.openshot.org/download/ or add the PPA and update through apt. The version in the Ubuntu apt repo is out of date, unfortunately.

**Comment by Colorjet3** [comment]
Openshot v3.1.1 has been released.  If you don't want to run the AppImage you can install the Stable PPA which will install v3.1.1

# sudo apt purge openshot-qt
# sudo apt autoremove
# sudo apt-add-repository ppa:openshot.developers/ppa
# sudo apt update
# sudo apt install openshot-qt
