### ISSUE TITLE
Projects with Zoom & Crop Crash

### ISSUE THREAD

**Issue by redsolocup123** [OpenShot/openshot-qt#5106]
**Describe the bug**
I have an mp4 video that I have loaded into OpenShot.  It plays fine when unedited.  As soon as I edit it, specifically crop and zoom, OpenShot crashes.  I've managed to save the project in the seconds before it crashes so that when I open it back up I can pick up where I left off but the program crashes within 5 seconds every time I try to reopen it. I tried this with a 2nd project and dif mp4, same result.  The program just doesn't like the zoom/crop work.  All other projects that don't use zoom and crop operate smoothly.  The project file mp4s in the 2 problem projects are small, around 80,000 KB or less (a minute or less).

**Steps to reproduce the behavior:**
1. Start a new project with only 1 project file (mp4)
2. Zoom and crop the mp4
3. Save (if I'm lucky enough to be able to)
4. CRASH
5. Reopen project
6. CRASH

I deleted my log files as the troubleshooting recommends (repeated the crash a few times before uploading them).  I can't install the daily build because I get errors on most files during the install. I guess there's an admin conflict when the installer tries to delete old files.

**Expected behavior**
I just want OpenShot to take the zoom/crop edits and not crash

**System Details**
- OpenShot Version: 3.0.0
- libopenshot Version:  0.3.0
- Platform: Windows-10-10.0.22000
- Processor: Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Not able to verify issue still exists in daily build

**Log Files**
- openshot-qt.log: File too small or empty (not uploaded)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/esuz3g69dbxzj73kjjlwk0lemy60pnvv/libopenshot.zip) (18 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
Please download the latest DEV Daily Build from openshot.org/download/#daily and install it.  This should fix the issue.

**Comment by redsolocup123** [comment]
Just realized my virus protection was blocking the daily build install. I fixed that and successfully installed the daily build, then went into debug mode and the same crashing is occurring.

**Comment by Colorjet3** [comment]
In Windows, go to Control Panel | Hardware & Sounds | Manage audio devices.  Find the audio device that set as "Default Device".  Click on it, then select Properties.  Now select the Advanced tab.  In the Default Format sections verify the sample rate.  Set this same sample rate in OpenShot (Edit | Preferences | Preview tab).  Restart Openshot and give it a try.

If you still are experiencing the issue:
1.  Make sure Openshot is closed.
2.  Make a backup of c:\users\username\.openshot_qt folder.
3.  Delete c:\users\username\.openshot_qt folder.
4. Start Openshot and work on your project.

If the problem persists, try converting your .mp4 file using VLC or Handbrake and convert it to .mp4 again.  Import this new converted .mp4 and start editing.

Let me know and we can continue troubleshooting if needed.

**Comment by Colorjet3** [comment]
Hello @redsolocup123 It has been 3 weeks since you have responded.  Please feel free to reopen if this is still an issue after you tried the possible solution I provided.
