### ISSUE TITLE
Openshot video preview pitchy

### ISSUE THREAD

**Issue by MixMatch53** [OpenShot/openshot-qt#5107]
**Describe the bug**
When I use the video preview, for some reason the video sounds high pitch chipmunk like. I tried changing and keeping the sampling rate in the software to 48000 but it didn't work. I tried going into the computer and change the sampling rate to 48000 but its still pitchy. It only seems to work when i lower the sampling rate to 44100

**Steps to reproduce the behavior:**
1. Import video files
2. Make sure to see if the sampling rate is at 48000 in the software and in sound settings on the computer
3. Play a video on preview it should sound pitchy
4. Go to computer to headphone device and change the sampling rate to 44100 and it doesn't sound pitchy. Going any higher would make the video preview pitch.

**Expected behavior**
The preview sound pitchy when the sampling rate is at 48000 but when you lower the sampling rate to 44100 in the sound settings on the computer, it sounds normal.

**System Details**
- OpenShot Version: 3.0.0
- libopenshot Version:  0.3.0
- Platform: Windows-10-10.0.19041
- Processor: AMD64 Family 23 Model 96 Stepping 1, AuthenticAMD
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.0.0-daily-10947-510a7690-b5bbab66-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/nr3af5x951i4qvhfjo02qr6p6nftow9u/openshot-qt.zip) (7 KB)
- libopenshot.log:[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/10482304/libopenshot.log)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
Hello @MixMatch53 This is most likely is related to the fact that your headphone device does not support 48000 sample rate requiring 44100.

You may want to try and see if you can change the Device Audio Sample Rate, in Windows, of your headphone to 48000.  That will then match Openshot as well and hopefully that will take care of the issue.
