### ISSUE TITLE
Sometimes playhead and line of the playhead are mismatched

### ISSUE THREAD

**Issue by shodanx2** [OpenShot/openshot-qt#5108]
Not sure why this happens, but it's not the first time I've noticed this issue

I'm running 3.0.0 daily 2023-01-18 07:05

Here is what it looks like

![image](https://user-images.githubusercontent.com/10621885/214224246-b286b500-9c59-49c6-9228-8c17d5f411f6.png)

I also notice that when I snap a clip to the end of the other clip, there are 2-3 frames of overlap, which might be unrelated as the mismatch of the playhead shown here is much more than 2-3 frames 

Zooming in fixed the mismatch (although I observe the playhead jumping all over the place while I zoom on on the timeline)

![image](https://user-images.githubusercontent.com/10621885/214224655-6e51af41-71db-4ea7-ad82-1f0ad065bc39.png)

**Comment by Colorjet3** [comment]
Please download the latest DEV Daily build of v3.0.0.  Go to openshot.org/download/#daily.  Install it and give it a try.  By the way, the Playhead blue handle separating from the red line has been reported and it is very challenging to reproduce it.

If you are able to reproduce this then please provide us with the exact steps so we can document it for the lead developer to fix it.

**Comment by Colorjet3** [comment]
No response from user.

**Comment by shodanx2** [comment]
I have updated and it hasn't happenned again. It was a rare occurance.
I will post back here if I capture that again
