### ISSUE TITLE
Openshot daily version for Ubuntu 20.04.5 trying install from PPA not start

### ISSUE THREAD

**Issue by Augusto7743** [OpenShot/openshot-qt#5109]
Hello.
Only reporting an issue.

Trying install Openshot daily version from PPA
https://launchpad.net/~openshot.developers/+archive/ubuntu/libopenshot-daily

The files are downloaded and installed correctly. but the software not start.
Openshot daily version only work if using the appimage daily version.

List below are the files installed when trying install openshot from PPA
Have an nice day.

gdal-data_3.4.1+dfsg-1build2~20.04.sav0_all.deb
geoclue-2.0_2.5.6-0ubuntu1_amd64.deb
ibverbs-providers_28.0-1ubuntu1_amd64.deb
iio-sensor-proxy_2.8-1ubuntu2_amd64.deb
libaec0_1.0.4-1_amd64.deb
libarmadillo10_1%3a10.8.2+dfsg-1~20.04.sav0_amd64.deb
libarpack2_3.8.0-1~20.04.sav0_amd64.deb
libblosc1_1.21.1+ds2-2~20.04.sav0_amd64.deb
libcfitsio9_4.0.0-1~20.04.sav0_amd64.deb
libcharls2_2.3.4-1~20.04.sav0_amd64.deb
libevent-core-2.1-7_2.1.11-stable-1_amd64.deb
libevent-pthreads-2.1-7_2.1.11-stable-1_amd64.deb
libfabric1_1.6.2-3_amd64.deb
libfreexl1_1.0.6-1~20.04.sav0_amd64.deb
libfyba0_4.1.1-6build1_amd64.deb
libgdal30_3.4.1+dfsg-1build2~20.04.sav0_amd64.deb
libgdcm3.0_3.0.14-1~20.04.sav0_amd64.deb
libgeos3.10.2_3.10.2-1~20.04.sav0_amd64.deb
libgeos-c1v5_3.10.2-1~20.04.sav0_amd64.deb
libgeotiff5_1.7.0-2build1~20.04.sav0_amd64.deb
libgl2ps1.4_1.4.2+dfsg1-2~20.04.sav0_amd64.deb
libhdf4-0-alt_4.2.14-1ubuntu1_amd64.deb
libhdf5-103_1.10.4+repack-11ubuntu1_amd64.deb
libhdf5-openmpi-103_1.10.4+repack-11ubuntu1_amd64.deb
libhwloc15_2.8.0-1~20.04.sav0_amd64.deb
libhwloc-plugins_2.8.0-1~20.04.sav0_amd64.deb
libibverbs1_28.0-1ubuntu1_amd64.deb
libjson-c5_0.15-2~20.04.sav0_amd64.deb
libjsoncpp25_1.9.5-3~20.04.sav0_amd64.deb
libkmlbase1_1.3.0-8build1_amd64.deb
libkmldom1_1.3.0-8build1_amd64.deb
libkmlengine1_1.3.0-8build1_amd64.deb
liblept5_1.79.0-1.1~20.04.sav0_amd64.deb
libnetcdf15_1%3a4.7.3-1_amd64.deb
libnetcdf19_1%3a4.8.1-1~20.04.sav0_amd64.deb
libnetcdf-c++4_4.2-11build2_amd64.deb
libodbc1_2.3.6-0.1build1_amd64.deb
libogdi4.1_4.1.0+ds-5~20.04.sav0_amd64.deb
libopencv-calib3d4.2_4.2.0+dfsg-5+20.04.sav4.1_amd64.deb
libopencv-contrib4.2_4.2.0+dfsg-5+20.04.sav4.1_amd64.deb
libopencv-dnn4.2_4.2.0+dfsg-5+20.04.sav4.1_amd64.deb
libopencv-features2d4.2_4.2.0+dfsg-5+20.04.sav4.1_amd64.deb
libopencv-flann4.2_4.2.0+dfsg-5+20.04.sav4.1_amd64.deb
libopencv-highgui4.2_4.2.0+dfsg-5+20.04.sav4.1_amd64.deb
libopencv-imgcodecs4.2_4.2.0+dfsg-5+20.04.sav4.1_amd64.deb
libopencv-ml4.2_4.2.0+dfsg-5+20.04.sav4.1_amd64.deb
libopencv-objdetect4.2_4.2.0+dfsg-5+20.04.sav4.1_amd64.deb
libopencv-photo4.2_4.2.0+dfsg-5+20.04.sav4.1_amd64.deb
libopencv-shape4.2_4.2.0+dfsg-5+20.04.sav4.1_amd64.deb
libopencv-stitching4.2_4.2.0+dfsg-5+20.04.sav4.1_amd64.deb
libopencv-superres4.2_4.2.0+dfsg-5+20.04.sav4.1_amd64.deb
libopencv-video4.2_4.2.0+dfsg-5+20.04.sav4.1_amd64.deb
libopencv-videoio4.2_4.2.0+dfsg-5+20.04.sav4.1_amd64.deb
libopencv-videostab4.2_4.2.0+dfsg-5+20.04.sav4.1_amd64.deb
libopencv-viz4.2_4.2.0+dfsg-5+20.04.sav4.1_amd64.deb
libopenmpi3_4.1.4-2ubuntu1~20.04.sav0_amd64.deb
libopenshot23_0.3.0+dfsg2+1157+202212221932+daily~ubuntu20.04.1_amd64.deb
libopenshot-audio9_0.3.0+dfsg2+149+202212192316~ubuntu20.04.1_amd64.deb
libpmix2_4.1.2-3ubuntu0~20.04.sav0_amd64.deb
libpq5_12.12-0ubuntu0.20.04.1_amd64.deb
libproj22_8.2.1-1~20.04.sav0_amd64.deb
libprotobuf23_3.12.4-1ubuntu1~20.04.sav0_amd64.deb
libpsm2-2_11.2.86-1_amd64.deb
libpsm-infinipath1_3.3+20.604758e7-6_amd64.deb
libqhull-r8.0_2020.2-4~20.04.sav0_amd64.deb
libqt5positioning5_5.12.8+dfsg-0ubuntu1_amd64.deb
libqt5webchannel5_5.12.8-0ubuntu1_amd64.deb
libqt5webengine5_5.12.8+dfsg-0ubuntu1.1_amd64.deb
libqt5webenginecore5_5.12.8+dfsg-0ubuntu1.1_amd64.deb
libqt5webengine-data_5.12.8+dfsg-0ubuntu1.1_all.deb
libqt5webenginewidgets5_5.12.8+dfsg-0ubuntu1.1_amd64.deb
librdmacm1_28.0-1ubuntu1_amd64.deb
libre2-5_20200101+dfsg-1build1_amd64.deb
librttopo1_1.1.0-1_amd64.deb
libsocket++1_1.12.13-10build1_amd64.deb
libspatialite7_5.0.1-2build2~20.04.sav0_amd64.deb
libsuperlu5_5.3.0+dfsg1-2~20.04.sav0_amd64.deb
libsz2_1.0.4-1_amd64.deb
libtesseract4_4.1.1-2build2_amd64.deb
libucx0_1.13.0-1~20.04.sav0_amd64.deb
libvtk6.3_6.3.0+dfsg2-8~20.04.sav0.1_amd64.deb
libxerces-c3.2_3.2.2+debian-1build3_amd64.deb
libxnvctrl0_470.57.01-0ubuntu0.20.04.3_amd64.deb
odbcinst1debian2_2.3.6-0.1build1_amd64.deb
odbcinst_2.3.6-0.1build1_amd64.deb
openshot-qt_3.0.0+dfsg2+1617+202212221948~ubuntu20.04.1_all.deb
proj-bin_8.2.1-1~20.04.sav0_amd64.deb
proj-data_8.2.1-1~20.04.sav0_all.deb
python3-defusedxml_0.6.0-2_all.deb
python3-openshot_0.3.0+dfsg2+1157+202212221932+daily~ubuntu20.04.1_amd64.deb
python3-pyqt5.qtopengl_5.14.1+dfsg-3build1_amd64.deb
python3-pyqt5.qtsvg_5.14.1+dfsg-3build1_amd64.deb
python3-pyqt5.qtwebchannel_5.14.1+dfsg-3build1_amd64.deb
python3-pyqt5.qtwebengine_5.14.0-2build1_amd64.deb
python3-sentry-sdk_0.12.2-1_all.deb
python3-zmq_18.1.1-3_amd64.deb

**Comment by Colorjet3** [comment]
Please give the Daily Build PPA a try:  https://www.openshot.org/ppa/  Make sure you perform the Daily and not the Stable version.

**Comment by tlhingan** [comment]
Openshot 3.0 requires QT5 version 5.15. This user only has 5.14.
