### ISSUE TITLE
Title rendering not working.

### ISSUE THREAD

**Issue by Mates555CZ** [OpenShot/openshot-qt#511]
**System Details:**
 Operating System / Distro: Windows 7 Pro CZ
 OpenShot Version: 2.2.0
Issue Description and steps to reproduce:Can't render any animated title. Open settings, set blender directory, close settings, open animated title, try to render any title

**Comment by mixedbredie** [comment]
Check this [wiki](https://github.com/OpenShot/openshot-qt/wiki/How-to-troubleshoot-errors-with-animated-titles) page for some things to try.

**Comment by jonoomph** [comment]
I will be fixing this soon. =)

**Comment by jonoomph** [comment]
Please test again with the latest daily build of OpenShot. I've merged in changes to the text alignment, and updated the minimum version compatibility to 2.78. I've tested all animation on Linux, Mac, and Windows with Blender 2.78 and everything works great.

Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot. _It might take a couple hours for the latest version to appear._

If you have other issues, please file additional bugs for each one. Thanks!
