### ISSUE TITLE
Sometimes parts of the timeline indentations disappear when zoomed in a lot

### ISSUE THREAD

**Issue by shodanx2** [OpenShot/openshot-qt#5110]
Hi,

running 3.0.0 2023-01-18

![image](https://user-images.githubusercontent.com/10621885/214239098-61732ced-c843-4f7f-b302-a1c56b754a7d.png)

**Comment by Colorjet3** [comment]
Please download the latest DEV Daily Build #10947 and try again.  I was not able to replicate this issue with this latest DEV Daily build.

**Comment by shodanx2** [comment]
Specifically it was running

![image](https://user-images.githubusercontent.com/10621885/214402944-b92b67da-7918-46df-aaff-432655496478.png)

Note : This portion of the about page should be copy pastable for bug reporting convenience

I also can't reproduce the bug, so consider this just a "bug sighting"

**Comment by Colorjet3** [comment]
Hello @shodanx2 Thank you for the FYI.  I also like your suggestion regarding the ability to copy the About Page.  Are you thinking the copy would be the image above or some sort of formatted text?  Let me know your thoughts and I will submit an enhancement request.

**Comment by shodanx2** [comment]
The text should be selectable, just put it all in a text box that way it is intuitively selectable
Maybe have a copy version text button next to it

![image](https://user-images.githubusercontent.com/10621885/214465384-078ff453-2a1b-4e48-b74d-864ad5e78119.png)

**Comment by Colorjet3** [comment]
Thank you for that!  I have created an internal ticket for an enhancement request and will be closing this ticket.
