### ISSUE TITLE
Mismatch between export Bit Rate quality and the actual exported bitrate

### ISSUE THREAD

**Issue by andbaraks** [OpenShot/openshot-qt#5119]
**Describe the bug:**
Exporting a video with Quality High and/or Video Bit Rate / Quality custom, in my case, 15.00 Mb/s will still be exported with 5 MB/s

I tried to use also 10 Mb/s and result was the same, the exported file was resulted with 5 MB/s. But if I set 3 MB/s in custom in OpenShot, it will export it with 3 MB/s. My theory is that OpenShot is not able to export more than 5 MB/s video bitrate.

**Steps to reproduce the behavior:**
1. Add a video in OpenShot
2. Export
3. Simple -> Profile: All Formats | Target: CPU MP4 (h.264) | Video Profile: HD 1080p 30fps (1920x1080) | Quality: High
4. Advanced -> Default settings, including Video Settings -> Bit Rate / Quality: 15.00 MB/s. I only changed Audio Settings -> Bit Rate / Quality: 320 kb/s (but this should be unrelated)

When I check in Windows the resulted file -> Properties -> Details -> I see under Video -> Data rate 5070kbps and Total bitrate 5382kbps

**Expected behavior:**
When I check in Windows, I would expect a ~15.00 MB/s video bitrate.

**System Details:**
- OpenShot Version 3.0.0
- Operating System / Distro: Windows 11

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.
What I select in OpenShot:
![image](https://user-images.githubusercontent.com/68290745/215197775-e002fae7-5c72-48cb-8673-f1472c59e237.png)

The result of the video:
![image](https://user-images.githubusercontent.com/68290745/215197962-c0395990-c1d9-4517-8cd9-4113252fb3f4.png)

**Comment by sc0nway** [comment]
Hi @andbaraks!  I am the IT Support Specialist for OpenShot, and @Colorjet3 assigned your issue to me, asking for help with this problem.  I want to give you an update on this issue.  I've been working on this issue in the background, rendering a single project in multiple ways on all four supported operating systems to see my results.  I see problems across the different operating systems and report them to Jonathan.  He asks me for more information each time I speak with him about this issue, so it takes me more time to run the tests, collect the data, then report back to him.  We are working on this issue, but we have yet to have any more to update you with at this time.

To help me continue troubleshooting, please provide me with the following information.
* What is the resolution and bitrate of your source clip(s)?
* Do you render only one source clip or create a complete project to render at 15.00 Mb/s?
* Did you try downloading and installing our latest Daily Build: https://www.openshot.org/download/#daily?
* Have you tried any additional renders, and do you have any additional information to add to this issue?

**Comment by Colorjet3** [comment]
No response from user.
