### ISSUE TITLE
OpenShot crashes immediately after running.

### ISSUE THREAD

**Issue by ghost** [OpenShot/openshot-qt#5122]
**Describe the bug**
I recently updated my OpenShot and now OpenShot crashes when I'm trying to run it. I had experience no sound in the previous version
so I have updated it which resulted to this problem.

MinGW Backtrace:

```
openshot-qt.exe caused an Access Violation at location 00007FFAAE735F62 in module libopenshot.dll Reading from location 0000000000000000.

AddrPC           Params
00007FFAAE735F62 000001ED0000AC44 000001ED00000002 0000000000000018  libopenshot.dll!openshot::AudioDeviceManagerSingleton::Instance
00007FFAAE73642A 0000000000000000 00007FFAEB36B1CB 0000000000000000  libopenshot.dll!openshot::AudioPlaybackThread::run
00007FFAA9C23FB9 0000000000000000 00007FFAEDE5AADB 000001ED376D1EB0  libopenshot-audio.dll!juce::Thread::threadEntryPoint
00007FFAA9C24146 000001ED376D1EB0 0000000000000000 000001ED376D1EB0  libopenshot-audio.dll!juce::threadEntryProc
00007FFAEDE5B04A 00007FFAEDEB06D0 000001ED376D1EB0 0000000000000000  msvcrt.dll!_callthreadstartex
00007FFAEDE5B11C 0000000000000000 0000000000000000 0000000000000000  msvcrt.dll!_threadstartex
00007FFAEDFB7C24 0000000000000000 0000000000000000 0000000000000000  KERNEL32.DLL!BaseThreadInitThunk
00007FFAEE10D4D1 0000000000000000 0000000000000000 0000000000000000  ntdll.dll!RtlUserThreadStart

```

**Steps to reproduce the behavior:**
1. Run OpenShot
**Expected behavior**
OpenShot runs and shows main window.

**System Details**
- OpenShot Version: 3.0.0
- libopenshot Version:  0.3.0
- Platform: Windows-10-10.0.18362
- Processor: Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Skipped this step

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/3empsu3m6zr0gx9fz1gg6lqrfgpz4wx8/openshot-qt.zip) (16 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Comment by Colorjet3** [comment]
There have been several reported crashing issues with v3.0.0-Releaes-Candidate right after installation.  Please go to openshot.org/download/#daily and get the latest DEV daily build.  Install it and give it a try.

**Comment by Colorjet3** [comment]
Hell @harieamjari It has been 2 weeks and I have not received an update from you.  I am closing this ticket for now.  Please feel free to reopen it if the issue persists once you tried the latest DEV Daily build.  Or, let us know if the latest DEV daily build fixed the issue.

**Comment by SpaceBison** [comment]
I'm getting the same crash:

```
ERROR main_window: Unhandled crash detected: linux-/usr/lib/libopenshot.so.23 openshot::AudioPlaybackThread::run 0xa6 [0x7fda5eb82416]
Caught signal 11 (SIGSEGV)
---- Unhandled Exception: Stack Trace ----
  /usr/lib/libopenshot.so.23     ( openshot::AudioPlaybackThread::run()      + 0xa6  )  [0x7fe5c2582416]
  /usr/lib/libopenshot-audio.so.9 ( juce::Thread::threadEntryPoint()          + 0x74  )  [0x7fe5c238b024]
  /usr/lib/libopenshot-audio.so.9 (                                           + 0x13c5be)  [0x7fe5c23bf5be]
  /usr/lib/libc.so.6             (                                           + 0x85bb5)  [0x7fe5c3a9ebb5]
  /usr/lib/libc.so.6             (                                           + 0x107d90)  [0x7fe5c3b20d90]
---- End of Stack Trace ----
```

**System Details**

- OpenShot Version: 3.0.0
- libopenshot Version: 0.3.0
- Platform: Linux-6.1.22-1-MANJARO-x86_64-with-glibc2.37
- Processor:
- Machine: x86_64
- Python version: 3.10.10
- Qt5 version: 5.15.8
- PyQt5 version: 5.15.9
- Qt Detected Languages: ['en-US', 'en', 'en-Latn-US']
- LANG Environment Variable: en_US.UTF-8
- LOCALE Environment Variable:

**Comment by Colorjet3** [comment]
Hello @harieamjari There is a new v3.1.1-Release-candidate.  Please go to openshot.org/download/#daily and download this AppImage and give it a try.

Let us know if you are still having the issue.
