### ISSUE TITLE
No deja exportar ni previsualizar el video

### ISSUE THREAD

**Issue by LozanoJohan** [OpenShot/openshot-qt#5125]
**Describa el problema**
Estuve trabajando durando algunos días en un video, de un día a otro todo el proyecto dejó de funcionar y no me deja hacer absolutamente nada, a la mínima que trato de mover algo el programa deja de responder y al tratar de previsualizar el video o tratar de exportarlo no pasa absolutamente nada, la previsualización queda en negro como si no tuviera nada en el proyecto.

**Pasos para reproducir el comportamiento:**
1. Abrir el proyecto
2. Tratar de previsualizar o exportar y no ver absolutamente nada

**Comportamiento esperado**
Esperaba poder exportar el proyecto, ya que justo lo había terminado.

**Detalles del sistema**
- OpenShot Version: 3.0.0
- libopenshot Version:  0.3.0
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['es-ES', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Compilación diaria: Todavía existe el problema verificado en la compilación diaria:http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.0.0-daily-10947-510a7690-b5bbab66-x86_64.exe

**Archivos de registro**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/f7zza6lfpwuoefo7kgn03efr3c93265l/openshot-qt.zip) (3 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/f7zza6lfpwuoefo7kgn03efr3c93265l/libopenshot.zip) (10498 KB)

**Excepción / Rastreo de pila**
```No stacktrace found in log files```

**Capturas de pantalla** (Opcional)
![image](https://user-images.githubusercontent.com/108693709/216175759-d9d5ff69-fbd5-4247-a139-78fe86e7f9e1.png)
![image](https://user-images.githubusercontent.com/108693709/216175854-2782424d-d94c-43a2-b888-0a308ef84ee5.png)

**Comment by Colorjet3** [comment]
Translated from English to Spanish
1. Inicie Openshot.
2. En el menú, haga clic en Ayuda | Acerca de Openshot y verifique que esté ejecutando la compilación n.º 10947.
3. Cerrar tiro abierto
4. Haga una copia de seguridad de la carpeta c:\users\username\.openshot_qt.
5. Elimine la carpeta c:\users\username\.openshot_qt.
6. Inicie Openshot.
7. Abra su proyecto y vea si las cosas están mejor.


English
1. Start Openshot.
2. On the menu, click Help | About Openshot and verify that you are running build #10947.
3. Close open shot
4. Make a backup of the c:\users\username\.openshot_qt folder.
5. Delete the c:\users\username\.openshot_qt folder.
6. Start Openshot.
7. Open your project and see if things are better.

**Comment by Colorjet3** [comment]
No response from user.
