### ISSUE TITLE
When adding an audio file to project, OpenShot crashes completely.

### ISSUE THREAD

**Issue by drtoddbritton** [OpenShot/openshot-qt#5129]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 3.0.0
- libopenshot Version:  0.3.0
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.0.0-daily-10996-70e86ef0-b5bbab66-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/85pnnvkjuwivdvs0c2qgmk1kndrtkygm/openshot-qt.zip) (13282 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/85pnnvkjuwivdvs0c2qgmk1kndrtkygm/libopenshot.zip) (25727 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
Hello @drtoddbritton This is a known issue with v3.0.0-Release-Candidate on some machines.  Please do this:
1.  Go to openshot.org/download/#daily and download the latest DEV Daily build.  Install it.
2.  When you start Openshot go to Edit | Preferences | Preview tab and change the Default Audio Sample Rate to 48000 if it is something different.
3. Import your file and it should work.

Let us know if this fixed your issue.

**Comment by drtoddbritton** [comment]
Hi Colorjet3,

   I did as instructed and it still doesn't import. I've tried two different MP4 type audio files. I own the music and exported just those two tracks that I wish to put into the project. I've tried both the drag and drop method and the import file method. Both garner the same result. What else can I try?

**Comment by Colorjet3** [comment]
Hell @drtoddbritton That is very strange as Openshot works very well with .mp4 files.  I want to clarify something, you say that the .mp4 is an audio file.  Typically .mp4 is both video and audio, is this not the case?  If so, that could be the issue.

1.  If your .mp4 is just audio, then please run it through a converter like Handbrake or Audacity and just extract the audio creating a .mp3 file then import this into Openshot.

2.  Other things to try is:
a.  Close openshot.
b.  backup c:\users\username\.openshot_qt folder.
c.  delete c:\users\username\.openshot_qt folder.
d.  start openshot and give the .mp4 a try again.

Do you have any other .mp4 files to test with?

**Comment by drtoddbritton** [comment]
Hi Colorjet3,

    I fixed it. The problem was that these were from iTunes, which apparently is locked or encrypted to only be used in their platform. Even though I own the album, I couldn't extract them. So thanks for your help. Add that to your knowledgebase to help others.

**Comment by Colorjet3** [comment]
Hell @drtoddbritton That is very interesting and thank you so much for telling us what the fix was.  This is one to remember and hope it helps others as well.
