### ISSUE TITLE
[Windows] Crashing because of recovering file

### ISSUE THREAD

**Issue by jGRite** [OpenShot/openshot-qt#513]
**https://www.youtube.com/watch?v=8eYS7leFKhI** it's there.
* Windows 7 Pro 64 bit
* OpenShot Version: 2.2.0
* can't open

**Issue Description and steps to reproduce:**
I've uninstalled and reinstalled. When I open it it crashes because

"Microsoft Visual C + + Runtime Library
X
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information."

then I see

"Backup Recovered
Your most recent unsaved project has been recovered."

I click "ok"

then launch.exe crashes.

If I could find the recovery and delete it I'd probably be able to use this program in windows again. AGAIN uninstalling and reinstalling or deleting to folder in program files doesn't fix this. Where is the recovery folder/file?

**Comment by jonoomph** [comment]
Hi @jGRite, thanks for the bug report. Please take a look at this folder: _C:/Users/USER/.openshot_qt/backup/_

Please attach the **backup.osp** file to this issue, and then delete it. OpenShot should launch fine after that, but I really want to see what's in the file before you delete it. =) Thanks!

**Comment by jGRite** [comment]
Alright, that fixed that. I see the file (can't share it here so I put it in my pCloud [https://my.pcloud.com/publink/show?code=XZgWJqZDTofYCnoswjG2Bbr0vAx1uky5UTX](url)

**Comment by jonoomph** [comment]
I have a guess about what's happening. Does this file exist anymore? F:/Users/Administrator/Videos/Done/Maestro SW setup (incomplete).mp4

It looks like OpenShot crashes when loading a project which refers to a file that no longer exists. I'm going to add some additional checks when loading projects, so we don't blow up. =)

**Comment by jGRite** [comment]
I move files when I'm done editing a video. In Linux, version 1, this want a big issue, but version 2 can't handle it. It would be nice if I could replace it with the moved file's location or something like that.

**Comment by jonoomph** [comment]
The latest daily build now prompts to find missing files when loading a project. Also, all projects are saved with relative paths, to avoid the issue of moving project files... however, if a crash happens, it attempts to load a "backup.osp" project, which does need to use absolute paths... thus this fix should now prompt you to fix the missing file, instead of just crashing.

**Comment by PGB75** [comment]
Hello, I'm experiencing the same error: as the recovery backup ends loading, the software crashes.
 
1) I removed all the content of the .openshot_qt folder and it starts (as freshly installed).
2) I tried to open the backup.osp projects from the folder I copied before deleting the .openshot_qt and it starts but does not find the images.
3) I re-copied the old folders to the  .openshot_qt renaming the backup.osp file to _backup.osp and it starts. I tried to open _backup.osp file and it loads all the project, creating _backup folder and subfolders, but when it's finished the error comes back.
4) I tried to open the project in the notepad application, but I'm not able to find what's wrong.

I attach the backup.osp file.

I would be very grateful if you can help me.
Thanks in advance and regards!
PG

[backup.zip](https://github.com/OpenShot/openshot-qt/files/4441081/backup.zip)

**Comment by ferdnyc** [comment]
@PGB75 I'm going to transfer your comment to a new issue, as this issue is closed. It's always better to open a new issue rather than resurrect closed ones from completely different versions of the software. The error you're experiencing is really not that similar to the one reported here. (Especially if I'm right about what the problem is.)
