### ISSUE TITLE
Can't add keyframe without changing a property

### ISSUE THREAD

**Issue by frederikheld** [OpenShot/openshot-qt#5130]
**Describe the new feature:**

This should be a bug report but I'm sure you consider this as a new feature so here we are.

[As the docs state](https://www.openshot.org/static/files/user-guide/animation.html#key-frames), keyframes can be added by editing the properties at any given point in time. There seems to be no way of creating a keyframe WITHOUT changing properties. The workaround is to change properties and then change them back. This is very annoying when I need a keypoint that has the same properties as the last one.

Let's take this use case for example:

I want to temporarily zoom into the video, then - after a while - zoom out again.

I need 4 key points:

* video at scale 1,0
* video at scale 2,0 (when the zoom in transition ends)
* video at scale 2,0 (when the zoom out transition starts)
* video at scale 1,0

Setting the third keypoint is the one that needs to be fixed.

**Describe the solution you'd like:**
Add an entry that adds a keyframe at the given position to the context menu of a track.

**Describe alternatives you have considered:**
Buy an adobe premiere license.

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your request.

**Comment by Colorjet3** [comment]
Hello @frederikheld Are you saying that at scale 2,0 you want to have two keyframes?   What are you trying to accomplish?  If I try to guess, are you trying to:

1.  Play normal at the beginning (Scale 1,0) for so many seconds.
2.  Then at some point start zooming in for so many seconds to Scale 2,0)
3.  Then at some point start zooming out for so many seconds.
4.  Then at some point go back to Scale 1.00

Is this what you are trying to accomplish?  If not, please give me just a bit more details so I can try and replicate what you are trying to accomplish, if possible.

By the way, what version of Openshot are you running?
What operating system and version?

**Comment by frederikheld** [comment]
Thanks for your prompt reply.

No. It is as I described it: Zoom in until I'm at a specific point in time. Then keep the video at that zoom level for some time. Then zoom out again at later point in time. To keep it zoomed in, I need two key points with the same scale properties.

I'm on version 3.0.0, which I installed through the Flatpak link on your website. I'm on Ubuntu 22.04.1 LTS

In the meanwhile I found this feature in every single context menu of the properties in the properties view. Which somehow implies that a keyframe is related to one specific property. Maybe I don't get the concept of a "keyframe" in OpenShot, but for me a keyframe is a frame of the video at a specific point in time. So I would expect it on the timeline or related to the play head.

**Comment by Colorjet3** [comment]
Hello @frederikheld Thank you for the additional information.  Here is how you can accomplish what you want to do.  Here is the use case:

a.  I have a .mp4 video/audio that is 90 seconds.
b.  From the beginning I want to zoom in until I get to 20 seconds.  This will be animated as it zooms in.
c.  At 20 seconds I want to stay at this zoom in level for 10 seconds.  No animation.  just playing the video.
d.  When I reach the 30th seconds I want to zoom out again back to normal until I reach the end of the clip.  this will be animated.

Here is what to do:
1.  Select your clip on the track.
2.  Right click and select Properites so you can see the properties window.
3.  Set your playead at the 20th seconds into the clip or specific point in time of your choosing.
4.  Double click Scale X and change it to 2.00.  Double Click Scale Y and change it to 2.00.  So now you have animation of zooming in from the beginning of your clip to this point.
5.  Now, move the playhead to the 30th seconds position or a specific point in time of your choosing.
6.  Right click on Scale X and select "Insert Kyeframe".  Right click on Scale Y and select "Insert Keyframe".  You have now locked in the zoom at 2.00 for scale x & y up to this point.
7.  Now move the playhead to the end of your clip (you can click on "Next Key Point" from the toolbar menu.
8.  Now change both Scale X & Y back to 1.00.

Also, wanted to let you know that depending on what you are zooming into (I don't know what your video is and the objects in it), you may have to adjust the Location X & Y attributes as well at specific point in time.  You can apply the same logic as described regarding zoom in/out.

Let me know if this is what you are trying to accomplish.

**Comment by frederikheld** [comment]
Thanks for the detailed answer. I did not complain that it is impossible to do what I wanted to do in OpenShot. I complained that it is implemented in a way that is absolutely not intuitive.

But I played around with the feature for a while now and figured out how this works in OpenShot. Still confusing, but in its own weird way it seems to make sense...

Thanks for your help!

**Comment by Colorjet3** [comment]
Hello @frederikheld I didn't take it as a complaint.  It took me a while to even grasp the notion of keyframes (I am new to video edtiting).  And after many video tutorials, trial and errors, and Reddit, I finally have a much better grasp.

I will close this ticket since you have your solution.  However, I recommend that you submit an enhancement request if you have some options that will make the Keyframe functionality more intuitive.  The lead developer is open to suggestions and will definitely review the option(s) you submit.
