### ISSUE TITLE
Segfault late into export that happens repeatedly on two different machines

### ISSUE THREAD

**Issue by ismoaulaskari** [OpenShot/openshot-qt#5132]
**Describe the bug**
Openshot segfaults every time I export my project into h264/youtube-hd. The crash happens after 60% of export is complete. I managed to export the project without fast forwarded clips so the crash might be video speed related.

The preview seems to work. I haven't crashed openshot while viewing it. I installed openshot-qt daily build to two different modern laptops to compare results, after having this same problem with openshot 3 stable ppa.

**Steps to reproduce the behavior:**
1. Open my project in openshot
2. Click ctrl+e to export and click export
3. Wait for export to go almost to the end
4. See segfault and openshot terminating
5. the formed mp4 is garbage when viewed with mplayer

**Expected behavior**
I expect the export to complete to 100% and the video to work like my other projects done with openshot 1 with same type of input clips (mp4,mov,mp3,jpg).

**System Details**
- OpenShot Version: 3.0.0
- libopenshot Version:  0.3.0
- Platform: Linux-5.15.0-58-generic-x86_64-with-glibc2.35
- Processor: x86_64
- Machine: x86_64
- Python version: 3.10.6
- Qt5 version: 5.15.3
- PyQt5 version: 5.15.6
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: en_US.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.0.0-daily-10996-70e86ef0-b5bbab66-x86_64.AppImage

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/ld31df7htahp5dkz4a32ylm2e2noa6v9/openshot-qt.zip) (31 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/ld31df7htahp5dkz4a32ylm2e2noa6v9/libopenshot.zip) (8 KB)

**Exception / Stacktrace**
```/lib/x86_64-linux-gnu/libopenshot.so.23 openshot::Clip::get_time_mapped_frame(std::shared_ptr<openshot::Frame>, long) 0x819  [0x7feadc1a9c79]
/lib/x86_64-linux-gnu/libopenshot.so.23 openshot::Clip::GetFrame(std::shared_ptr<openshot::Frame>, long, openshot::TimelineInfoStruct*) 0xdf  [0x7feadc1aa79f]
/lib/x86_64-linux-gnu/libopenshot.so.23 openshot::Timeline::GetOrCreateFrame(std::shared_ptr<openshot::Frame>, openshot::Clip*, long, openshot::TimelineInfoStruct*) 0x3ef  [0x7feadc201eef]
/lib/x86_64-linux-gnu/libopenshot.so.23 openshot::Timeline::add_layer(std::shared_ptr<openshot::Frame>, openshot::Clip*, long, bool, float) 0xc4  [0x7feadc202114]
/lib/x86_64-linux-gnu/libopenshot.so.23 openshot::Timeline::GetFrame(long)       0x1642  [0x7feadc209b22]
/usr/lib/python3/dist-packages/_openshot.cpython-310-x86_64-linux-gnu.so                                          0x163acd  [0x7feadca20acd]
/usr/bin/python3                                                        0x15bb88  [0x559ffc49cb88]
/usr/bin/python3               PyObject_Call                            0xbb  [0x559ffc4abfcb]
/usr/bin/python3               _PyEval_EvalFrameDefault                 0x2a70  [0x559ffc4883b0]
/usr/bin/python3               _PyFunction_Vectorcall                   0x7c  [0x559ffc49d3ac]
/u...

**Comment by ismoaulaskari** [comment]
New information, I managed to get preview crash after all, so I probably found the clip that breaks the export. It would be nice if the export logged the exact place it's going better.

**Comment by Colorjet3** [comment]
Thank you @ismoaulaskari and nice job isolating the trouble clip.  One thing to try is take that file (I am assuming it is a video file) and run it through a converter like Handbrake or VLC.  Then import this converted file into Openshot and see it is any better.

**Comment by ismoaulaskari** [comment]
Thanks for the tip, re-importing that clip into openshot helped, I did not convert it at all yet.
