### ISSUE TITLE
How to add audio to go with freeze frame option

### ISSUE THREAD

**Issue by ghost** [OpenShot/openshot-qt#5134]
**Question:**
Hello. I saw that OpenShot offers freeze frame option and that is great. I want to add an audio track to the frozen frame part. Also I want the frozen frame to have custom duration. Are those two options possible? If that is the case how?

**System Details:**
- OpenShot Version [e.g. 2.4.3]: v3.0
- Operating System / Distro: Windows 7

**Comment by Colorjet3** [comment]
Hello @jacktoreno Thank you for your inquiry regarding Openshot and the features you are looking for.  Both of those two options are doable in Openshot.  Here is how to go about it:

1.  Start Openshot.
2.  Import and drag your video onto a track.
3.  Move the playhead to the frame that you wan to freeze and change the duration of.
4.  Just below the "Video Preview" window and to the right of the play and forward icons you will see a Camera icon.
5.  Click on the Camera icon and Openshot will ask you to save that frame.  Provide a name and save it somewhere you can get to.
6.  Now import this new image into Openshot.
7.  Drag it onto a track.
8.  Select the clip and then grab the right most edge of the clip and extend it to change the duration as you please.
9.  For a more accurate custom duration, right click on this clip and select Properties.  In the Properties window find the End attribute.  You can double click the value and enter your own value.
10. Now import your audio and drag it onto a track below your frozen clip (you really are not leveraging the Freeze option) and align them the way you want it to be.

I don't know exactly what the end goal is but I am going to assume that you want your video clip to play and then when you reach that one frame you want that to play for whatever duration you select and the audio track then the video will continue.  If this is the case then do this to your video clip after the steps above.

1.  Select your video clip on the track.
2.  Position the Playead on that frame where you took the camera snap shot.
3.  Using the left arrow key nudge the playhead once to move it one frame to the left.
4.  Right click and select Slice | Keep both sides.  You now have to two clips comprising your single video click.
5.  Click the 2nd half so it has the red border around it.
6.  Now nudge the playhead to the right using the right arrow key.  Do this one click at a time until you pass the one frame you took a snapshot of with the Camera icon.  Should only take 2 right arrow clicks.
7. Right click and select Slice | Keep right side.  This will remove that one frame from your video and you should see a black gap between the two clips.
8. Grab the selected clip and move it to the right to make room to slide the one frame clip and do not overlap them.
9. Make sure now all three clips are snapped together.
10. Your audio clip should be below the single frame clip. 

This should do it.

Let me know if it is something else that you needed to accomplish.

**Comment by ghost** [comment]
@Colorjet3 I really cannot thank you enough for taking the time to provide this detailed answer for me. Thanks a lot. I will try this out.

**Comment by Colorjet3** [comment]
You are very welcome @jacktoreno!

**Comment by Colorjet3** [comment]
Hello @jacktoreno Did this work?  Just curios!
