### ISSUE TITLE
Laggy Video Preview

### ISSUE THREAD

**Issue by Dark-Johan** [OpenShot/openshot-qt#5137]
**Describe the bug:**
When previewing the video, it begins to lag behind while the audio remains as is.

**Steps to reproduce the behavior:**
1. Boot up OpenShot and open a project.
2. Go to 'Video Preview'
3. Click on 'Play'

**Expected behavior:**
The video and audio are supposed to be in sync.

**System Details:**
- OpenShot Version 3.0.0
- Windows 10

**Comment by Colorjet3** [comment]
Hello @Dark-Johan This is a known bug in Windows 10 & 11, specially if you upgraded from a previous version.  To fix the audio issue:
1.  Start Openshot.
2.  Go to Edit | Preferences | Preview tab.
3.  Change the Default Audio Sample Rate to 48000.
4.  Restart Openshot.

This should fix it.

**Comment by Dark-Johan** [comment]
It helped! Thank you!

**Comment by Colorjet3** [comment]
That is great @Dark-Johan and you are welcome!
