### ISSUE TITLE
cant open or add 4k videos

### ISSUE THREAD

**Issue by chris1972arg** [OpenShot/openshot-qt#5142]
im using ubuntu 22.04 openshot 3.0 dell latitude 3420 with 32gb ram

when i try to open a 4k video created with a gopro 10 or a motorola x4 cellphone, openshot doesnt open (open and close quickly)
and when I use the option to include new videos inside openshot the program just close

everything is fine with less resolution videos.

**Describa el problema**
A clear and concise description of the issue

**Pasos para reproducir el comportamiento:**
1. Ir a «...»
2. Pulsar en «....»
3. Desplazarse hasta «....»
4. Ver el error

**Comportamiento esperado**
Una descripción clara y concisa de lo que esperaba que sucediera.

**Detalles del sistema**
- OpenShot Version: 3.0.0
- libopenshot Version:  0.3.0
- Platform: Linux-5.15.0-60-generic-x86_64-with-glibc2.35
- Processor: x86_64
- Machine: x86_64
- Python version: 3.10.6
- Qt5 version: 5.15.3
- PyQt5 version: 5.15.6
- Qt Detected Languages: ['es', 'en']
- LANG Environment Variable: es_ES.UTF-8
- LOCALE Environment Variable: 
- Compilación diaria: Todavía existe el problema verificado en la compilación diaria:http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.0.0-daily-10996-70e86ef0-b5bbab66-x86_64.AppImage

**Archivos de registro**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/htmaz1hxikrvnnodj3esw1v79okzf2n5/openshot-qt.zip) (17 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/htmaz1hxikrvnnodj3esw1v79okzf2n5/libopenshot.zip) (16 KB)

**Excepción / Rastreo de pila**
```/usr/lib/python3/dist-packages/_openshot.cpython-310-x86_64-linux-gnu.so swig::SwigPyForwardIteratorOpen_T<std::_Rb_tree_iterator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, swig::from_oper<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::value() const 0x16  [0x7f9b33c63756]
/usr/lib/python3/dist-packages/_openshot.cpython-310-x86_64-linux-gnu.so                                          0xbd34d  [0x7f9b33b7134d]
/usr/bin/python3                                                        0x15b564  [0x56419c4cb564]
/usr/bin/python3               _PyEval_EvalFrameDefault                 0x2a70  [0x56419c4b73b0]
/usr/bin/python3               _PyFunction_Vectorcall                   0x7c  [0x56419c4cc3ac]
/usr/bin/python3               _PyEval_EvalFrameDefault                 0x80a  [0x56419c4b514a]
/usr/bin/python3               _PyFunction_Vectorcall                   0x7c  [0x56419c4cc3ac]
/usr/bin/python3               _PyEval_EvalFrameDefault                 0x6c5  [0x56419c4b5005]
/usr/bin/python3                                             ...

**Comment by sc0nway** [comment]
Would you please try downloading and installing our [latest Daily Build](https://www.openshot.org/download/#daily) and verify that the issues are still happening?  Our developers have addressed crashing when opening 4K videos in OpenShot.

Before importing your source clip, try changing the project profile to a lower resolution with the same aspect ratio and frame rate.  Click the Change Profile button (the orange filmstrip icon) in the toolbar at the top of the Main window.  Choose one of the WQVGA 240p profiles with the same frame rate as your source clip, then click the `Close` button.  Import the video, then add it to the Timeline.  The preview window may be slightly grainy because the preview is now 426x240 instead of 4K.  The smaller resolution in the Preview window reduces the resources OpenShot uses while editing.

**Comment by jonoomph** [comment]
@chris1972arg Thanks for the bug report! I looked in your log files, and the following frame rate is output right before a crash:

```
FFmpegReader::UpdateVideoInfo (info.fps.num=359.0000, info.fps.den=12.0000)
FFmpegReader::UpdateVideoInfo (pStream->avg_frame_rate) (num=6030000.0000, den=225451.0000)
```

This is an odd looking frame rate, but it reduces to 29.9167, which is essentially 30 FPS. If possible, can you upload / share a very short 4K video from your gopro, and attach it here (or link to it). I would love to try and reproduce this crash in a debugger.

**Comment by Colorjet3** [comment]
@chris1972arg.  I am following up on behalf of @jonoomph to see if you had a chance to upload/share a short 4k video so we can further troubleshoot this issue.

**Comment by Colorjet3** [comment]
No response from user at this time.
