### ISSUE TITLE
Compiling in debian buster

### ISSUE THREAD

**Issue by gbrea** [OpenShot/openshot-qt#5144]
**Describe the bug:**
Error running openshot-qt after compiling libopenshot and libopenshot-audio on debian buster

**Steps to reproduce the behavior:**
1. Go to a directory where you want to download the repositories, I have chosen `/opt`
2. Clone the repositories
``` 
git clone https://github.com/OpenShot/libopenshot.git
git clone https://github.com/OpenShot/libopenshot-audio.git
```
3. Run `apt install cmake pkg-config libopenshot-audio-dev libx11-dev libfreetype6-dev libasound2-dev libavcodec-dev libavformat-dev libavutil-dev libswresample-dev libswscale-dev libpostproc-dev libfdk-aac-dev libjsoncpp-dev libzmq3-dev qtbase5-dev libqt5svg5-dev libbabl-dev libopencv-dev libprotobuf-dev protobuf-compiler python3-dev swig libmagick++-dev`
4. Go to `/opt/libopenshot-audio`
5.  Run
```
cmake -B build -S .
cmake --build build
cmake --install build
```
6. Go to `/opt/libopenshot`
7. Run (I had to add `-DOpenShotAudio_ROOT` because if it didn't give me errors when compiling, it ended the process without reporting any errors)
```
cmake -B build -S . -DOpenShotAudio_ROOT=../libopenshot-audio/build
cmake --build build
cmake --install build
```
8. Go to & clone `cd /opt && git clone https://github.com/OpenShot/openshot-qt.git`
9.  And go to `/opt/openshot-qt`
10.  Run `python3 src/launch.py`

**Expected behavior:**
A normal execution of the program

**System Details:**
- OpenShot Version : Latest, `v3.0.0`
- Operating System / Distro: `Debian buster`

**Exception / Stacktrace:**
```
$ python3 src/launch.py 
Loaded modules from: /opt/openshot-qt/src
INFO sentry: No sentry_sdk module detected (error reporting is disabled)
INFO app: ------------------------------------------------
INFO app:             Mon Feb 13 16:44:04 2023            
INFO app:               Starting new session              
INFO app: ------------------------------------------------
INFO app:             OpenShot (version 3.0.0)            
INFO app: ------------------------------------------------
INFO app: openshot-qt version: 3.0.0
INFO app: libopenshot version: 0.2.5
INFO app: platform: Linux-5.18.0-0.deb11.4-amd64-x86_64-with-debian-10.10
INFO app: processor: 
INFO app: machine: x86_64
INFO app: python version: 3.7.3
INFO app: qt5 version: 5.11.3
INFO app: pyqt5 version: 5.11.3
Traceback (most recent call last):
  File "src/launch.py", line 196, in main
    app = OpenShotApp(argv)
  File "/opt/openshot-qt/src/classes/app.py", line 131, in __init__
    self.project = project_data.ProjectDataStore()
  File "/opt/openshot-qt/src/classes/project_data.py", line 66, in __init__
    self.new()
  File "/opt/openshot-qt/src/classes/project_data.py", line 291, in new
    profile = self.get_profile(profile_desc=default_profile_desc)
  File "/opt/openshot-qt/src/classes/project_data.py", line 341, in get_profile
    if legacy_profile and legacy_profile.Key() == temp_profile.Key():
  File "/usr/lib/python3/dist-packages/openshot.py", line 3568, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, Profile, name)
  File "/usr/lib/python3/dist-packages/openshot.py", line 80, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'Profile' object has no attribute 'Key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/launch.py", line 223, in <module>
    main()
  File "src/launch.py", line 198, in main
    app.show_errors()
AttributeError: 'NoneType' object has no attribute 'show_errors'
INFO app:             OpenShot's session ended            
INFO app:             Mon Feb 13 16:44:04 2023            
INFO app: ================================================
```

**Comment by jonoomph** [comment]
@gbrea It appears that your installed libopenshot version (or perhaps python3-openshot module) is running an older version - probably something installed from a repository. The Profile::Key() method is relatively new, and it is definitely in the source code you cloned from libopenshot... thus, my theory is when you are launching `openshot-qt`, it's loading a different version of libopenshot... one that is much older.

Hope that helps!
