### ISSUE TITLE
Color Picker (Chroma Key) Always Selects Black 

### ISSUE THREAD

**Issue by sahansk2** [OpenShot/openshot-qt#5148]
**Describe the bug:**
The chroma key color picker functionality does not work on Ubuntu 22.04 (Wayland). NOTE: #1865 discusses this but it was instantly closed, citing the solution of using Xorg. I never "opted-in" to Wayland, so to speak - it was the default on my Ubuntu 22.04.

**Steps to reproduce the behavior:**
1. Add a video with a green screen and a picture to the project files.
2. Add a chroma key filter by going to "Effects" and dragging it to the video in the timeline.
3. Go to the properties tab and double click on "Key Color".
4. Click on a color on the actual editor.
5. Black is always selected no matter the region in the video selected.

**Expected behavior:**
The color picker should correctly select the color that the user selects.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 3.0.0
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]: Ubuntu 22.04 (Jammy Jellyfish)

**Log Files:**
Logs collected by specifying `-d` flag. Pastebin: https://pastebin.com/0KXTM44d

I didn't take too close a look at the debug, but I noticed something funky with some invocation of `lsb_release -a`. Here's the output on my system if it helps any.
```
(base) ➜  Downloads $ lsb_release -a    
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy                                                      /0.1s
(base) ➜  Downloads $ lsb_release --help
Usage: lsb_release [options]

Options:
  -h, --help         show this help message and exit
  -v, --version      show LSB modules this system supports
  -i, --id           show distributor ID
  -d, --description  show description of this distribution
  -r, --release      show release number of this distribution
  -c, --codename     show code name of this distribution
  -a, --all          show all of the above information
  -s, --short        show requested information in short format            /0.1s
(base) ➜  Downloads  $                 
```
Also, when doing a run of the reproducible steps to recreate the bug, I accidentally clicked a pure-green color in the color picker - heads up in case that causes confusion.

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

**Screenshots:** (Optional)
![image](https://user-images.githubusercontent.com/55329269/219373049-11de21c5-d20e-46e7-bb2c-0709c4f738bd.png)

**Additional:**: I thought it might've been a Wayland issue when I tried to bypass the problem by using `gpick`. Then, I found that `gpick` also suffered, and so I did a quick google search and came to this SA post: https://unix.stackexchange.com/questions/320070/is-there-a-colour-picker-that-works-with-wayland-or-xwayland

**Comment by sahansk2** [comment]
One more thing: the first line of the debug statement says something about setting an environment variable to specify wayland. So, I set the variable and got this output:

```
(base) ➜  Downloads $ QT_QPA_PLATFORM=wayland ./OpenShot-v3.0.0-x86_64.AppImage -d
Loaded modules from: /tmp/.mount_OpenShtnmI28/usr/bin
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

[1]    77693 IOT instruction (core dumped)  QT_QPA_PLATFORM=wayland ./OpenShot-v3.0.0-x86_64.AppImage -d 
```

**Comment by jonoomph** [comment]
@sahansk2 Thanks so much for the detailed bug report. We have been seeing more and more reports of color picker issues over the past year, and this now makes a lot of sense... that Wayland is blocking Qt from accessing the colors of other apps. I found a related Qt bug report: https://bugreports.qt.io/browse/QTBUG-81538. 

Now, with respect to OpenShot... I'm not sure what we can do about this. If Wayland is blocking access to pixel data of other applications / windows, and offers no work-around or API for Qt to use... I'm not sure what applications like OpenShot are supposed to do. I'm open to suggestions and I'll dig a bit more and research this issue.

Please feel free to attach any useful or relevant articles, bug reports, or work-arounds.

**Comment by sahansk2** [comment]
Ahhh, I see. That's unfortunate to hear.

A workaround I found: since I'm on Gnome, I'm following this advice: https://unix.stackexchange.com/a/665604. Clunky, but functional.

**Comment by Colorjet3** [comment]
Hello @sahansk2.  I submitted an internal bug ticket for this to be tracked, reviewed, and a possible solution implemented.  @jonoomph is the lead developer and now it is in his queue.

https://trello.com/c/8yAx4FQZ/142-color-picker-chorma-key-always-selects-black
