### ISSUE TITLE
Hindi title text does not render well

### ISSUE THREAD

**Issue by RiteshSingh** [OpenShot/openshot-qt#5150]
![Openshot issue](https://user-images.githubusercontent.com/351703/219539083-5bf0400d-d4da-4c07-b9ca-9db578370353.png)

क्यासुन रहे हैं आप? क्रोधित हुए जनोंके गीत

**Comment by Colorjet3** [comment]
Hello @RiteshSingh.  Please provide the following:

1.  Version of Openshot (help | about Openshot)?  Please include the build #.
2.  What operating system and version are you running?
3.  What function are you using to insert your text (Title, Caption, or Animated title)?  Also, for Title or Animated title, which template are you using?

Thank you!

**Update:**  I just copied your text and used Title | Title | Bar 3 template.  dragged it onto a track and it looked good in the "Video Preview" window.  I then proceeded to Render/Export it and the output looks good as well.  I am using v3.0.0 Dev Daily build #11044 running in Windows 10 Pro.

**Comment by RiteshSingh** [comment]
Thank you @Colorjet3 for your kind reply and interest. Your method continues to give me overlapped text in my version, both in the preview window and in the exported video. Screenshots are attached.
![Openshot issue 2](https://user-images.githubusercontent.com/351703/219830869-09cc7569-01d0-416b-8024-e10f3e920cd2.png)
![Openshot issue 3](https://user-images.githubusercontent.com/351703/219831331-fd73f4cb-b818-4d65-9317-370b1e6d45ac.png)

1. OpenShot-v3.0.0-release-candidate-10676-264205da-ba27794b
2. Windows 10 Enterprise
3. Title | Title | [Any option]

**Comment by RiteshSingh** [comment]
Dear Sir @Colorjet3 

In the interest of issue discovery and resolution, I have installed your version (OpenShot-v3.0.0-daily-11044-70e86ef0-b5bbab66-x86_64).

The issue continues to occur. Screenshot is attached.
![Openshot issue 4](https://user-images.githubusercontent.com/351703/219835420-6482e23d-d9c7-40ea-babf-3fcd4820d555.png)

The issue also occurs in the latest daily build (OpenShot-v3.0.0-daily-11058-8f92bac0-b5bbab66-x86_64). Screenshot below.
![Openshot issue 5](https://user-images.githubusercontent.com/351703/219837728-55b17a89-8f92-4b94-b7c7-f8d4fba0e9da.png)

**Comment by Colorjet3** [comment]
Hello @RiteshSingh Sorry for the delayed response as I was traveling this weekend.  Since I am not familiar with the Hindi language it is difficult for me to figure out where the overlap is happening.  Please provide me with a screen shot of what it should look like.

Also, I ran this text through Google translate to translate to English and it came back with this:  What are you listening to? songs of the angry.  Is this the correct translation?

**Comment by RiteshSingh** [comment]
Dear @Colorjet3

Thank you for your continued interest and for being so kind. Please never apologize. You are doing a great service. There cannot be any place for apology in this.

I eventually used Shotcut to make the video (OpenShot remains my top choice, having used it in many [previous projects](https://youtu.be/lvm7SSvKVKg)). The text should appear as follows (from the Shotcut video):
![Openshot issue 6](https://user-images.githubusercontent.com/351703/220600690-299495ee-3207-43f6-92d4-378a80f63148.png)

I have boxed the overlapping parts from OpenShot here:
![Openshot issue 5](https://user-images.githubusercontent.com/351703/220602189-022f4d25-4da4-4858-894e-51b1992588e7.png)

Another correct version from Microsoft Word follows:
![Openshot issue 7](https://user-images.githubusercontent.com/351703/220614849-5ca74a63-0f04-464c-8a74-72b6a0103c95.png)

**About the Translation:** Yes, it is close. The line was actually my attempt to translate in Hindi the famous revolutionary song from Les Miserables: "_Do you hear the people sing? Singing a song of angry men_". 

It has been translated into tens of languages but never in Hindi. A more accurate English translation of my Hindi line would be "_Are you able to hear, O respected one? The songs of the people who are angry_".

[English version](https://youtu.be/1q82twrdr0U) | [Hindi version (mine)](https://youtu.be/ItTGPW8RGOk)

Thank you for taking interest in the meaning of the line🙏🏼🙏🏼

**Comment by Colorjet3** [comment]
Hello @RiteshSingh.  Thank you so very much for this very informative answer.  I am not able to see and understand exactly what the issue is.  This is not something I will be able to fix myself but going to need to get the technical lead involved for a resolution.  Again, the information you have provided is very valuable in understanding the issue and to find and implement the solution.

I will provide updates as they become available.

**Comment by RiteshSingh** [comment]
Thanks a ton as always @Colorjet3 Sir 🙏🏼🙏🏼

I had raised a Hindi text rendering issue in Firefox and it was found to be an issue in the HarfBuzz text shaping engine.

[Firefox issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1817366) | [Harfbuzz issue (traced back by Firefox devs)](https://github.com/harfbuzz/harfbuzz/issues/4124) 

There is a good chance that this may be irrelevant to the current issue, but I felt that a few mins look here could save hours (in case OpenShot uses Harfbuzz or another text rendering engine for example), so I mentioned it.

**Comment by Colorjet3** [comment]
Hello @RiteshSingh That is good information to know and I will ensure that the technical lead is aware of this as well.

**Comment by jonoomph** [comment]
We actually do use the Harfbuzz text shaping engine, as part of ReSVG - the library we use to rasterize text. So, once it is fixed upstream, we will eventually pull in that fix. Feel free to update this ticket once the Harfbuzz issue is resolved, and we would be happy to prioritize updating our ReSVG library. :+1:

**Comment by RiteshSingh** [comment]
Hi Jonathan @jonoomph 

Thank you for your time, attention, and efforts. Harfbuzz is updated and the issue is [resolved](https://bugzilla.mozilla.org/show_bug.cgi?id=1817366) in Firefox.

@Colorjet3 Thank you for always being too kind 🙏🏼😊

**Comment by khaledhosny** [comment]
> We actually do use the Harfbuzz text shaping engine, as part of ReSVG

resvg uses [rustybuzz](https://github.com/RazrFalcon/rustybuzz) which is a Rust fork of HarfBuzz and is not currently kept in sync, so the fix in HarfBuzz is not directly relevant.
