### ISSUE TITLE
Openshot startet und schließt sich gleich wieder

### ISSUE THREAD

**Issue by Reneligh** [OpenShot/openshot-qt#5152]
**Beschreiben Sie den Fehler**
A clear and concise description of the issue

**Schritte zum Reproduzieren des Verhaltens**
1. Gehe Sie nach '...'
2. Klicken Sie auf '....'
3. Scrollen Sie hinunter nach '....'
4. Sehen Sie den Fehler

**Erwartetes Verhalten**
Eine klare und prägnante Beschreibung dessen, was Sie erwartet haben.

**Systemdetails**
- OpenShot Version: 3.0.0
- libopenshot Version:  0.3.0
- Platform: Windows-10-10.0.18362
- Processor: AMD64 Family 23 Model 1 Stepping 1, AuthenticAMD
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['de-DE', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Not able to verify issue still exists in daily build

**Logdateien**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/uqp117i02r6i61vhmxubq88ez5qnapoy/openshot-qt.zip) (14 KB)
- libopenshot.log: Datei zu klein oder leer (nicht hochgeladen)

**Ausnahme / Stapelverfolgung**
```No stacktrace found in log files```

**Bildschirmfotos** (Optional)
Wenn möglich, fügen Sie Screenshots zur unterstützenden Erklärung Ihres Problems hinzu. Sie können Screenshots einfügen,
indem Sie diese kopieren und auf Github einfügen oder durch Drag and Drop zur GitHub-Seite hinzufügen. Alle Bilder sind öffentlich zugänglich, posten Sie deshalb keine Screenshots die persönliche Informationen enthalten.

**Comment by Colorjet3** [comment]
Hell @Reneligh.

Dies ist ein bekanntes Problem mit v3.0.0 auf einigen Systemen.

1. Gehen Sie zu openshot.org/download/#daily.
2. Laden Sie das neueste verfügbare DEV Daily herunter und installieren Sie es.

3. Starten Sie Openshot und gehen Sie zu Bearbeiten | Einstellungen | Registerkarte „Vorschau“.

4. Stellen Sie sicher, dass die Standard-Audioabtastrate auf 48000 eingestellt ist.

5. Starten Sie openshot neu.

**Comment by Colorjet3** [comment]
No feedback from user.
