### ISSUE TITLE
Animated Titles & Blender issues

### ISSUE THREAD

**Issue by Polda18** [OpenShot/openshot-qt#516]
**System Details:**
* Operating System / Distro: Microsoft Windows 10 Home 64bit
* OpenShot Version: 2.2
* _Please attach log files if crash_ // none

**Issue Description and steps to reproduce:**

Hello. I have latest version of Blender installed (2.78). I'm using Windows 10 64bit machine, since OpenShot reached multi-platform cross support Linux/Mac/Windows.

OpenShot failed to load up Blender for advanced animated titles even after manual entering the entire path including executable file (the path is as follows: C:\Program Files\Blender Foundation\Blender\blender.exe) and it's correctly set up in registers, Blender loads up just fine when launched standalone. But when I try to make one animated title that require Blender (the one from OpenShot preview, for example), it starts the Blender console, but doesn't actually launch the renderer and keeps to showing me an error message Blender is missing and needs to be properly added (with somewhat confusingly corrupted path shown up, see attached screenshot).

What does it mean? I wanted to make an intro video for my YouTube channel, but this seems so bad :(

![Error window](https://cloud.githubusercontent.com/assets/25118993/23527304/bea0ba54-ff95-11e6-9088-c4c527c9b776.JPG)

**Comment by mixedbredie** [comment]
@Polda18 This has been fixed in a recent update.  You need to download a daily build from http://www.openshot.org/download/ and click the "other Windows downloads" link to get a recent build.

It's to do with some outdated Blender scripts in the official build.  The [wiki](https://github.com/OpenShot/openshot-qt/wiki/How-to-troubleshoot-errors-with-animated-titles) has more information.

**Comment by Polda18** [comment]
Okay, thanks for tip. I don't have time to download now (an hour is too much this time), so I'll probably do it at home.

**Comment by Polda18** [comment]
Why Blender can't work with no other font than Bfont? Any other font than Bfont makes Blender not found again :( I don't like Bfont, I want to try other fonts... This is the version of OpenShot I downloaded: OpenShot-v2.2.0-32-g4297843-49-607-x86_64.exe (March 1, 2017, 3:57 a.m.)

**Comment by DylanC** [comment]
@Polda18 - Can you confirm this issue is now fixed in a newer version please?

**Comment by Polda18** [comment]
@DylanC - Not now. I'll update and give a feedback later (if it's going to be before I replace Windows with Ubuntu)

**Comment by DylanC** [comment]
@Polda18 - Thanks! Much appreciated.

**Comment by DylanC** [comment]
@Polda18 - I'm closing this since the original issue was resolved. Feel free to open a new ticket if you have a different problem.
