### ISSUE TITLE
Audio not saving when exporting video on MacBook Pro

### ISSUE THREAD

**Issue by AlchimisteT** [OpenShot/openshot-qt#5161]
[Edit: I have abandonned OpenShot for another device, therefore this thread could be of interest for some other people, but not me anymore.]

Hi,

Exporting my video works great with all the work I've done except the audio. I've tried enabling audio under properties and even splitting audio and video; I've also downloaded the latest DEV Daily Build available, without change. Is there perhaps something to select in audio settings in advanced settings (when exporting)?

I'm using the latest version of Openshot (it's my first project on it), using a MacBook Pro 2,3 GHz Intel Core i5 with 8 Go 2133 MHz LPDDR3 running 13.2.1 (22D68). I haven't downloaded any 3rd party applications.

Thanks in advance for your help!

**Comment by Colorjet3** [comment]
Hello @AlchimisteT.  Sorry that you had issues with Openshot and glad you found something else that works for you.  I will close this ticket for now.  Without more details and troubleshooting, it doesn't make sense to keep it open.  If someone else has a similar issue, it would be best to start a new thread.

If you change your mind and want to continue troubleshooting then please feel free to reopen this issue.
