### ISSUE TITLE
It closes when I enter it. Windows 10

### ISSUE THREAD

**Issue by atarwn** [OpenShot/openshot-qt#5162]
1. I click on the application icon
2. It works with freezes of 3-5 seconds
3. It closes
Sometimes at the top of the screen (where the name of the application is usually) It writes "(Not responding)"
I don't know where is log files. So I can't understand the causeless exit

**Comment by Colorjet3** [comment]
Hello @System11X.  You don't mention which version of Openshot you are trying to run but I am going to assume v3.0.0.  If you downloaded the production release (-Release-Candidate), then that is probably the issue.

1. Go to Openshot.org/download/#daily and get the latest DEV daily build available.
2. Install it.
3. Start Openshot.
4. Got to Edit | Preferences | Preview tab and change the Default Audio sample rate to 48000.
5. Restart Openshot.
6. This should do it.
