### ISSUE TITLE
Animated titles will not open properly

### ISSUE THREAD

**Issue by therep49er** [OpenShot/openshot-qt#5163]
**Describe the bug**
A clear and concise description of the issue
When trying to use an animated title, an error message pops up about pointing to a Blender exe. file. My version of both OpenShot and Blender are current.

**Steps to reproduce the behavior:**
1. Go to '...' Title
2. Click on '....' Animated title
3. Scroll down to '....' Doubleclick on any animated title

**Expected behavior**
Select and animated title and watch it open properly.

**System Details**
- OpenShot Version: 3.0.0
- libopenshot Version:  0.3.0
- Platform: Windows-10-10.0.22621
- Processor: AMD64 Family 25 Model 80 Stepping 0, AuthenticAMD
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Skipped this step

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/2ucou6ham5f6r8gdz708f1intbzph7k5/openshot-qt.zip) (113 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/2ucou6ham5f6r8gdz708f1intbzph7k5/libopenshot.zip) (1 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

                
![Screenshot 2023-03-03 080159](https://user-images.githubusercontent.com/126837366/222607801-ebed15cd-bab3-43bf-96c7-e82c11f1103a.png)
![Screenshot 2023-03-03 080330](https://user-images.githubusercontent.com/126837366/222607838-ea135843-7951-4534-ada3-cad93207e934.png)
![image](https://user-images.githubusercontent.com/126837366/222608235-8d3d0681-aa1d-400a-9cca-f522842be6d2.png)

**Comment by Colorjet3** [comment]
Hello @therep49er.  Two things need to happen for the Animated Titles to work properly.

1.  You must have Blender installed.  Got to blender.org and download the latest available for your Operating system.
2.  You must now tell Openshot where the blender.exe file is located:
- Start Openshot
- Go to Edit | Preferences | General tab.
- Where you see "blender", click on the Browse all the way to the right and browser to where you installed Blender and click on the blender.exe and then click on Open.

My blender path looks like this:  C:/Program Files/Blender Foundation/Blender 3.4/blender.exe

This should take care of your issue.

**Comment by therep49er** [comment]
I have the latest version of both OpenShot and Blender installed. I have
looked for the blender exe. file. I am not seeing it though.

**Comment by Colorjet3** [comment]
Hello @therep49er.  
1.  Start File Explorer.
2.  Go to c:\Program Files
3.  Now look for "Blender Foundation" and double click it.
4.  No look for Blender 3.4 and double click it.
5.  You should now see Blender.exe.  You may just see Blender without the .exe because you don't have File Explorer configured to display file extensions.  If this is the case continue with step 6.
6.  While in File Explorer, click on View from the top menu.
7.  All the way to the right click on the down arrow of Options and  select "Change Folder and Search Options".
8.  From the "Folder Options" window click on the View tab.
9.  In the "Advanced settings:" section find "Hide extensions for known file types" and uncheck the box.
10. Now click on "Apply to Folders" not just "Apply".  You will be prompted to apply this to all Folders so click on Yes.

Hope this helps.

**Comment by therep49er** [comment]
@Colorjet3 

I followed your directions, thank you! 
I aslo figured out that I was trying to point from the advanced title editor. I got it on the right path and can at least get to the point of messing with the animated title settings. Lots to play with and figure out! Thank you again!

**Comment by Colorjet3** [comment]
That is great @therep49er and good luck with the Animated Titles and your projects.  I will close this ticket.  Feel free to open a new thread if you run into other issues.

**Comment by therep49er** [comment]
Thank you.
