### ISSUE TITLE
no me deja exportar video

### ISSUE THREAD

**Issue by efet4** [OpenShot/openshot-qt#5167]
**Describe the bug:**
i can´t export these project, i have the program in D unit, but when i finish the project, the export buton don´t go and i see these error when i use  the openshot-qt-cli

File "D:\OpenShot Video Editor\windows\main_window.py", line 829, in actionExportVideo_trigger
    win = Export()
  File "D:\OpenShot Video Editor\windows\export.py", line 135, in __init__
    self.timeline.SetJson(json_timeline)
  File "C:\gitlab-runner\builds\4cf61635\0\OpenShot\openshot-qt/openshot.py", line 4917, in SetJson
RuntimeError: JSON is invalid (missing keys or invalid data types)

**Steps to reproduce the behavior:**
1. Go to 'export'
2. Click on 'exporting'

**Expected behavior:**
i need to know what i have do, and if you can send me a spanish request 

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

[hablemos de Shingeki no Kyojin temporda 3_assets.zip](https://github.com/OpenShot/openshot-qt/files/10946704/hablemos.de.Shingeki.no.Kyojin.temporda.3_assets.zip)

**Comment by Colorjet3** [comment]
Hola u/efet4.

1. ¿Qué versión de Openshot está ejecutando (Ayuda | Acerca de Openshot)?

2. ¿Qué sistema operativo y versión está ejecutando (Windows 10 pro? ¿Windows 10 Home? ¿Ubuntu 22.04 LTS? etc.)

Translated from English

Hello u/efet4.

1.  What version of Openshot are you running (Help | About Openshot)?

2.  What operating system and version are you running (Windows 10 pro?  Windows 10 Home?  Ubuntu 22.04 LTS? etc?)

**Comment by Colorjet3** [comment]
Same as issue #5168.  Issue #5168 has more details in it.

**Comment by Colorjet3** [comment]
Hello @efet4.  Any update on this?  I am going to close this ticket but feel free to reopen to continue troubleshooting.
