### ISSUE TITLE
no puedo exportar ese proyecto

### ISSUE THREAD

**Issue by efet4** [OpenShot/openshot-qt#5168]
**Describa el problema**
el programa sin comenzar proyecto exportaba normal, pero ahora ya no me deja exportar cuando finalizo el proyecto

**Pasos para reproducir el comportamiento:**
1. Ir a «proyecto»
2. Pulsar en «exportar»
3. Desplazarse hasta «....»
4. Ver el error

**Comportamiento esperado**
esperaba que se abriera la ventana de exportar y crear el perfil y que se procese el video

**Detalles del sistema**
- OpenShot Version: 3.0.0
- libopenshot Version:  0.3.0
- Platform: Windows-10-10.0.22000
- Processor: AMD64 Family 23 Model 24 Stepping 1, AuthenticAMD
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['es-MX', 'es-ES', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Compilación diaria: Saltar este paso

**Archivos de registro**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/n1ztdfzwi4lhn5n3194izfr4cmw29j6w/openshot-qt.zip) (25563 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/n1ztdfzwi4lhn5n3194izfr4cmw29j6w/libopenshot.zip) (44 KB)

**Excepción / Rastreo de pila**
```No stacktrace found in log files```

**Capturas de pantalla** (Opcional)
Si se aplica, añada capturas de pantalla para ayudar a explicar el problema. Puede incluir capturas
copiando y pegando en GitHub o arrastrando y soltando en la página de GitHub. Todas las imágenes
son públicas y por tanto no debería publicar capturas que contengan información personal.

**Comment by Colorjet3** [comment]
Hola u/efet4.

Por favor hacer esto:
1. Cierre Openshot si se está ejecutando.

2. Vaya a Agregar o quitar programas, busque Openshot y desinstálelo.

3. Haga una copia de seguridad de la carpeta c:\users\username\.openshot_qt.

4. Elimine la carpeta c:\users\username\.openshot_qt.

5. Vaya a openshot.org/download/#daily y descargue la última compilación diaria de DEV disponible.

6. Instale esta última compilación diaria DEV.

7. Inicie un nuevo proyecto y guárdelo.

8. Exportarlo y ver si funciona.

Translated from English
Hello u/efet4.

Please do this:
1.  Close Openshot if running.

2.  Go to Add or Remove Programs and search for Openshot and Uninstall it.

3.  Make a backup of c:\users\username\.openshot_qt folder.

4.  Delete c:\users\username\.openshot_qt folder.

5.  Go to openshot.org/download/#daily and download the latest DEV Daily Build available.

6.  Install this latest DEV daily build.

7.  Start a new project and save it.

8.  Export it and see if it works.

**Comment by Colorjet3** [comment]
Hello @efet4.  Proporcione más detalles sobre el problema de exportación. ¿Qué sucede cuando haces clic en el botón Exportar? ves un mensaje de error? ¿etc? Cualquier detalle adicional para que podamos problemas debería mejorar.

Además, confirme el número de compilación de Openshot que está ejecutando (Ayuda | Acerca de Openshot).


Translated from English:
Please provide some more details about the Export issue.   What happens when you click on the Export button?  do you see an error message? etc?  Any additional details so we can trouble should better.

Also, please confirm the build # of Openshot you are running (Help | About Openshot).

**Comment by Colorjet3** [comment]
No response from user.
