### ISSUE TITLE
Python error in main script

### ISSUE THREAD

**Issue by hajdekr** [OpenShot/openshot-qt#517]
**System Details: HP ProBook 4540s, Core i5, 6 GB RAM**
* Operating System / Distro: Windows 10 Pro 64
* OpenShot Version: OpenShot-v2.2.0-x86_64
* https://goo.gl/photos/6ssWnTxeFNiWecbC8
**Issue Description and steps to reproduce: Program doesn't start...**

**Comment by jonoomph** [comment]
Please check a few things.
1) Try running As Administrator, and see if that solves it. 
   If so, that means you have something strange with your environment or registry. To verify, create a new Windows user, re-install OpenShot as that new user, and try launching OpenShot. If that works fine, your real user probably has some environment issues. 

2) If step 1 doesn't help, try installing the approapriate runtime: https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows

Please re-open this issue if those steps don't solve your problem. Thanks!
