### ISSUE TITLE
Audio bugs in exported video when AAC bitrate > 192k AND audio volume high enough

### ISSUE THREAD

**Issue by Kilklang26** [OpenShot/openshot-qt#5172]
**Describe the bug:**
The audio has clicks and/or artifacts when exporting with AAC codec with bitrate > 192K and when the source audio is above some volume threshold (not clipping though!)
Exported video is 1080p, 30fps, no hw acceleration, AAC codec with a single .wav track, no video, 48Khz matched between audio and project

**Steps to reproduce the behavior:**
1. Create a new project
2. Add an audio file, you can test with my pure sine wave tone : https://kodamo.org/share2cRGh/sine.wav
3. Export the video with AAC, bitrate > 192k (256, 320...)
4. The exported video has glitchy audio. Using my sine test, the sound is "wobbly". Using real music, I notice random clicks.
5. Check my exported video using my sine test: https://kodamo.org/share2cRGh/exported.mp4

NOTE : If I do the same test, but with a quieter sine wave in the source file, the problem disappears. Could this be due to some erratic auto-gain control in the AAC codec or in the way OpenShot handles audio ?
Both conditions seems to be required to trigger the bug : high enough volume, and high enough bitrate

**Expected behavior:**
Audio should be identical to the source file (minus the almost impossible to hear difference due to compression)

**System Details:**
- OpenShot Version 3.0.0: 
- Operating System / Distro: Windows 10

**Log Files:**
-
**Exception / Stacktrace:**
-
**Screenshots:** (Optional)
-

**Comment by Colorjet3** [comment]
Hello @Kilklang26 Please retest this using the latest v3.1.0-Release-Candidate-11141 as of this writing.

Go to openshot.org/download/#daily and get build 11141.  Test and see if the issue still exists.

**Comment by Colorjet3** [comment]
Hello @Kilklang26 v3.1.1 production release was just published.  You can go to the openshot.org and get the AppImage and give it a try.

I am going to close this ticket but feel free to reopen after you try v3.1.1 and the problem still persists.
