### ISSUE TITLE
Openshot does not open video files

### ISSUE THREAD

**Issue by thereticle** [OpenShot/openshot-qt#5176]
**Describe the bug:**
Trying to add an mp4 video file, I receive the message that the file is not a valid video, audio or image file. This happens either with stable and daily versions. I tried  even with repository version of Openshot (v. 2.7).
![Istantanea_2023-03-21_18-00-59](https://user-images.githubusercontent.com/20416601/226686376-f95e749a-713c-41d6-a9fb-45ea274ab8ec.png)

**Steps to reproduce the behavior:**

**Expected behavior:**

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 3.0.0
- Operating System / Distro: Ubuntu 22.10

![Istantanea_2023-03-21_18-00-59](https://user-images.githubusercontent.com/20416601/226685781-5f35a493-0d1a-4a10-8e43-fefc6920a0ee.png)
**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
Hello @thereticle.  Sorry to hear that you are having issues with Openshot.   Please try the following:

1.  Close Openshot.
2.  Make a backup of /home/username/.openshot_qt folder.
3.  Delete /home/username/.openshot_qt folder.
4.  Start Openshot and try importing your .mp4 file.
5.  This should take care of it.

**Update:**  I just wanted to mention that if you are trying different version of Openshot, what happens is the the /home/username/.openshot_qt folder and its contents get modified by the different versions.  This can/will cause issues with the ..../openshot.settings file.  Specially if you go backwards in version.

Typically, going forward in version should work but I've seen issues with that also depending how many versions your are skipping.  If you are trying different versions, then you should be taking backups of /home/username/.openshot_qt folder for the different versions (before you start running the next version of Openshot) just to be on the safe side and so you can go back if needed.

**Comment by thereticle** [comment]
Thanks a lot @colorjet3, doing as you said solved the problem. 
I had already tried deleting (just) the log files, but that obviously wasn't enough. Instead, deleting all of the .openshot_qt folder instead worked fine.
I'll also keep in mind your notes regarding installing different versions of the program.

**Comment by Colorjet3** [comment]
That is great @thereticle.  Best of luck with your projects.  By the way, keep an eye on a new production release (v3.1.0) coming out soon.
