### ISSUE TITLE
Openshot timeline weird behavior

### ISSUE THREAD

**Issue by thereticle** [OpenShot/openshot-qt#5179]
**Describe the bug:**
After inserting clips and arranging them with transitions etc, the top of the timeline window (clip position bars) is not consistent with the position of the clips as you can see from the attached image.
Playing the videos, even though the parts are adjacent, there are moments in the preview window where the screen is black, right at the separations visible at the top of the timeline.
Furthermore, once the project has been saved, when it is reopened the clips are in different positions from the previous ones, compatible with the bars placed in the upper part of the timeline.
It would seem that the position of the clips and their preview therefore follow the bars and not the position set at the bottom of the timeline.
I tried completely uninstalling Openshot and reinstalling the daily build but the problem remained.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 3.0.0 daly build 202303202247
- Operating System / Distro: Ubuntu 22.10

**Screenshots:** (Optional)
Timeline after positioning the clips (note the different position of the upper bars)

![timeline 1](https://user-images.githubusercontent.com/20416601/226879719-cbf1edb7-852b-4895-a304-577c75965994.png)

Timeline after project reload (note how the position of the upper bars remained the same, and the clips are positioned according to them)

![timeline after reload project](https://user-images.githubusercontent.com/20416601/226879869-2fd9bc66-3cac-4f0d-baa5-b5fb8c74b39c.png)

**Comment by thereticle** [comment]
After carefully uninstalling the program and associated folders, I proceeded to install the latest stable version from the PPA. Now everything works correctly. I close the thread.

**Comment by Colorjet3** [comment]
Hello @thereticle Thank you for submitting the issue and the solution. That was the first thing I was going to suggest is to get the latest DEV Daily build.  v3.0.0-Release-Candidate-xxxxxxxx, out of the gate, had some issues.  Many bug fixes and enhancements are in the latest DEV daily build.

By the way, keep an eye on release 3.1.0.  v3.1.0-Release-Candidate is out.  You can give the AppImage a try for now if you like.  go to openshot.org/download/#daily and you can find it there.

Really appreciate the feedback and the solution as well.  Good luck with your projects.
