### ISSUE TITLE
Appimage launches and crashes immediately

### ISSUE THREAD

**Issue by karagiannis** [OpenShot/openshot-qt#5180]
**Describe the bug:**
Appimage launches and crashes immediately

**Steps to reproduce the behavior:**
Run 
./OpenShot-v3.0.0-x86_64.AppImage 

**Expected behavior:**
Appimage launches and crashes immediately

**System Details:**
Downloaded appimage 21 of Mars 2023 and verified with SHA sum
Ubuntu 22.04.2 LTS

**Log Files:**
[openshot_qt.zip](https://github.com/OpenShot/openshot-qt/files/11046845/openshot_qt.zip)

**Exception / Stacktrace:**
lasse@lasse-Lenovo:~/Downloads$ ./OpenShot-v3.0.0-x86_64.AppImage 
Loaded modules from: /tmp/.mount_OpenShmPUw3k/usr/bin
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
INFO app: ------------------------------------------------
INFO app:             Thu 
Mar 23 04:57:25 2023            
INFO app:               Starting new session              

INFO app: ------------------------------------------------
INFO app:             OpenShot (version 3.0.0)            
INFO app: ------------------------------------------------
INFO app: openshot-qt version: 3.0.0
INFO app: libopenshot version: 0.3.0
INFO app: platform: Linux-5.19.0-35-generic-x86_64-with-glibc2.4
INFO app: processor: x86_64
INFO app: machine: x86_64
INFO app: python version: 3.8.10
INFO app: qt5 version: 5.12.8
INFO app: pyqt5 version: 5.14.1
INFO app: Frozen version info from build server:
{
    "build_name": "OpenShot-v3.0.0-release-candidate-10676-264205da-ba27794b",
    "date": "2022-12-08 21:32",
    "libopenshot": {
        "CI_COMMIT_REF_NAME": "release-20221201",
        "CI_COMMIT_SHA": "264205da9ff254363eb59c315c2422dcb2f22639",
        "CI_JOB_ID": "33856",
        "CI_PIPELINE_ID": "10605",
        "CI_PROJECT_NAME": "libopenshot",
        "SO": "23",
        "VERSION": "0.3.0"
    },
    "libopenshot-audio": {
        "CI_COMMIT_REF_NAME": "release-20221201",
        "CI_COMMIT_SHA": "ba27794b946bea119136d1a4356d6b774e8a9dd2",
        "CI_JOB_ID": "33850",
        "CI_PIPELINE_ID": "10603",
        "CI_PROJECT_NAME": "libopenshot-audio",
        "SO": "9",
        "VERSION": "0.3.0"
    },
    "openshot-qt": {
        "CI_COMMIT_REF_NAME": "release-20221201",
        "CI_COMMIT_SHA": "8aaee8d12a4b61c61f782bd4369d443120205294",
        "CI_JOB_ID": "34044",
        "CI_PIPELINE_ID": "10676",
        "CI_PROJECT_NAME": "openshot-qt",
        "SO": null,
        "VERSION": "3.0.0"
    }
}
INFO project_data: Setting default profile to HD 720p 30 fps
INFO project_data: Apply default audio playback settings: 48000, 2 channels
INFO app: checking babl_ext_path: /tmp/.mount_OpenShmPUw3k/usr/bin/lib/babl-ext
INFO app: setting BABL_PATH: /tmp/.mount_OpenShmPUw3k/usr/bin/lib/babl-ext
Screen XWAYLAND0
   devicePixelRatio: 1.0
   logicalDotsPerInch: 96.0
   physicalDotsPerInch: 159.3404174573055
   availableSizes: PyQt5.QtCore.QSize(1846, 1053)
INFO language: Qt Detected Languages: ['en-US']
INFO language: LANG Environment Variable: en_US.UTF-8
INFO language: LOCALE Environment Variable: 
INFO language: OpenShot Preference Language: Default
INFO app: Setting font to /tmp/.mount_OpenShmPUw3k/usr/bin/images/fonts/Ubuntu-R.ttf
INFO app: Setting custom dark theme
INFO logger_libopenshot: Connecting to libopenshot with debug port: 5556
INFO ui_util: Initializing UI for MainWindow
INFO thumbnail: Starting thumbnail server listening on port 45725
Sandboxing disabled by user.
Installed Qt WebEngine locales directory not found at location /tmp/.mount_OpenShmPUw3k/usr/bin/translations/qtwebengine_locales. Trying application directory...
Qt WebEngine locales directory not found at location /tmp/.mount_OpenShmPUw3k/usr/bin/qtwebengine_locales. Trying fallback directory... Translations MAY NOT not be correct.
Path override failed for key ui::DIR_LOCALES and path '/home/lasse/.openshot'
[0323/045727.789866:WARNING:resource_bundle_qt.cpp(116)] locale_file_path.empty() for locale 
Installed Qt WebEngine locales directory not found at location /tmp/.mount_OpenShmPUw3k/usr/bin/translations/qtwebengine_locales. Trying application directory...
Qt WebEngine locales directory not found at location /tmp/.mount_OpenShmPUw3k/usr/bin/qtwebengine_locales. Trying fallback directory... Translations MAY NOT not be correct.
Path override failed for key ui::DIR_LOCALES and path '/home/lasse/.QtWebEngineProcess'
[0323/045727.866871:WARNING:resource_bundle_qt.cpp(116)] locale_file_path.empty() for locale 
INFO webengine: WebEngine backend initializing
INFO transition_model: updating transitions model.
INFO effects_model: updating effects model.
INFO emoji_model: updating emoji model.
INFO main_window: InitCacheSettings
INFO main_window: cache-mode: CacheMemory
INFO main_window: cache-limit-mb: 512
INFO main_window: cache-ahead-percent: 0.7
INFO main_window: cache-preroll-min-frames: 24
INFO main_window: cache-preroll-max-frames: 48
INFO main_window: cache-max-frames: 600
INFO main_window: Creating CacheMemory object with 536870912 byte limit
INFO preview_thread: QThread Start Method Invoked
ERROR main_window: Unhandled crash detected: linux-/lib/x86_64-linux-gnu/libc.so.6 raise 0x16 [0x7f008cc42476]
INFO main_window: updateStatusChanged
INFO main_window: recover_backup
INFO main_window: Recovering backup file: /home/lasse/.openshot_qt/backup.osp
INFO settings: reducing file: /home/lasse/.openshot_qt/backup.osp to dir: /home/lasse/.openshot_qt
INFO settings: Ignore setting recent path: /home/lasse/.openshot_qt, most likely due to backup recovery
INFO project_data: Setting default profile to HD 720p 30 fps
INFO project_data: Apply default audio playback settings: 48000, 2 channels
INFO project_data: Loading project file: /home/lasse/.openshot_qt/backup.osp
INFO project_data: checking project files...
INFO project_data: checking file /home/lasse/Documents/Judaism/The 7 Laws of the Gentiles and More-n0_tgO5Drb8.mp4
INFO project_data: Project data: openshot 3.0.0, libopenshot 0.3.0
INFO project_data: Apply default audio playback settings: 48000, 2 channels
terminate called after throwing an instance of 'openshot::InvalidFile'
  what():  File could not be opened.
Caught signal 6 (SIGABRT)
---- Unhandled Exception: Stack Trace ----
  /lib/x86_64-linux-gnu/libc.so.6 ( raise                                     + 0x16  )  [0x7f5e36442476]
  /lib/x86_64-linux-gnu/libc.so.6 ( abort                                     + 0xd3  )  [0x7f5e364287f3]
  /lib/x86_64-linux-gnu/libstdc++.so.6 (                                           + 0xa2bbe)  [0x7f5e330a2bbe]
  /lib/x86_64-linux-gnu/libstdc++.so.6 (                                           + 0xae24c)  [0x7f5e330ae24c]
  /lib/x86_64-linux-gnu/libstdc++.so.6 (                                           + 0xad229)  [0x7f5e330ad229]
  /lib/x86_64-linux-gnu/libstdc++.so.6 ( __gxx_personality_v0                      + 0x99  )  [0x7f5e330ad999]
  /tmp/.mount_OpenShmPUw3k/usr/bin/libopenshot.so.23 (                                           + 0x1d680b)  [0x7f5e349d680b]
  /tmp/.mount_OpenShmPUw3k/usr/bin/libopenshot.so.23 (                                           + 0x1d71fa)  [0x7f5e349d71fa]
  /tmp/.mount_OpenShmPUw3k/usr/bin/libopenshot.so.23 (                                           + 0x8669f)  [0x7f5e3488669f]
  /tmp/.mount_OpenShmPUw3k/usr/bin/libopenshot.so.23 ( openshot::Mask::SetJsonValue(Json::Value)  + 0x365 )  [0x7f5e34947a45]
  /tmp/.mount_OpenShmPUw3k/usr/bin/libopenshot.so.23 ( openshot::Timeline::SetJsonValue(Json::Value)  + 0x457 )  [0x7f5e34927e67]
  /tmp/.mount_OpenShmPUw3k/usr/bin/libopenshot.so.23 ( openshot::Timeline::SetJson(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)  + 0xbd  )  [0x7f5e3491b16d]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/_openshot.so (                                           + 0x152cf1)  [0x7f5e34d52cf1]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/libpython3.8.so.1.0 (                                           + 0x2a8687)  [0x7f5e36aa8687]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/libpython3.8.so.1.0 ( _PyEval_EvalFrameDefault                  + 0x8dd8)  [0x7f5e3687df48]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/libpython3.8.so.1.0 ( _PyEval_EvalCodeWithName                  + 0x8fb )  [0x7f5e369cae3b]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/libpython3.8.so.1.0 ( _PyFunction_Vectorcall                    + 0x94  )  [0x7f5e36aa8114]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/libpython3.8.so.1.0 (                                           + 0x74d6d)  [0x7f5e36874d6d]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/libpython3.8.so.1.0 ( _PyEval_EvalFrameDefault                  + 0xea8 )  [0x7f5e36876018]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/libpython3.8.so.1.0 (                                           + 0x8006b)  [0x7f5e3688006b]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/libpython3.8.so.1.0 (                                           + 0x74d6d)  [0x7f5e36874d6d]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/libpython3.8.so.1.0 ( _PyEval_EvalFrameDefault                  + 0xea8 )  [0x7f5e36876018]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/libpython3.8.so.1.0 (                                           + 0x8006b)  [0x7f5e3688006b]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/libpython3.8.so.1.0 (                                           + 0x74d6d)  [0x7f5e36874d6d]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/libpython3.8.so.1.0 ( _PyEval_EvalFrameDefault                  + 0xea8 )  [0x7f5e36876018]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/libpython3.8.so.1.0 (                                           + 0x8006b)  [0x7f5e3688006b]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/libpython3.8.so.1.0 (                                           + 0x74d6d)  [0x7f5e36874d6d]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/libpython3.8.so.1.0 ( _PyEval_EvalFrameDefault                  + 0xea8 )  [0x7f5e36876018]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/libpython3.8.so.1.0 ( _PyEval_EvalCodeWithName                  + 0x8fb )  [0x7f5e369cae3b]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/libpython3.8.so.1.0 ( _PyFunction_Vectorcall                    + 0x94  )  [0x7f5e36aa8114]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/libpython3.8.so.1.0 (                                           + 0x74d6d)  [0x7f5e36874d6d]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/libpython3.8.so.1.0 ( _PyEval_EvalFrameDefault                  + 0xea8 )  [0x7f5e36876018]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/libpython3.8.so.1.0 ( _PyEval_EvalCodeWithName                  + 0x8fb )  [0x7f5e369cae3b]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/libpython3.8.so.1.0 ( _PyFunction_Vectorcall                    + 0x94  )  [0x7f5e36aa8114]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/libpython3.8.so.1.0 (                                           + 0x2a8daa)  [0x7f5e36aa8daa]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/libpython3.8.so.1.0 (                                           + 0x74d6d)  [0x7f5e36874d6d]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/libpython3.8.so.1.0 ( _PyEval_EvalFrameDefault                  + 0x45a3)  [0x7f5e36879713]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/libpython3.8.so.1.0 (                                           + 0x8006b)  [0x7f5e3688006b]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/libpython3.8.so.1.0 (                                           + 0x2a8e2b)  [0x7f5e36aa8e2b]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/libpython3.8.so.1.0 ( PyVectorcall_Call                         + 0x60  )  [0x7f5e36aa8830]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/PyQt5/QtCore.cpython-38-x86_64-linux-gnu.so (                                           + 0x217070)  [0x7f5e27a17070]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/PyQt5/QtCore.cpython-38-x86_64-linux-gnu.so (                                           + 0x217518)  [0x7f5e27a17518]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/PyQt5/QtCore.cpython-38-x86_64-linux-gnu.so (                                           + 0x21780e)  [0x7f5e27a1780e]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/PyQt5/QtCore.cpython-38-x86_64-linux-gnu.so (                                           + 0x2182d7)  [0x7f5e27a182d7]
  /tmp/.mount_OpenShmPUw3k/usr/bin/libQt5Core.so.5 ( QMetaObject::activate(QObject*, int, int, void**)  + 0x88c )  [0x7f5e33ab228c]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/PyQt5/QtCore.cpython-38-x86_64-linux-gnu.so (                                           + 0x213bfe)  [0x7f5e27a13bfe]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/libpython3.8.so.1.0 (                                           + 0x2a170e)  [0x7f5e36aa170e]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/libpython3.8.so.1.0 (                                           + 0x74d6d)  [0x7f5e36874d6d]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/libpython3.8.so.1.0 ( _PyEval_EvalFrameDefault                  + 0xea8 )  [0x7f5e36876018]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/libpython3.8.so.1.0 (                                           + 0x8006b)  [0x7f5e3688006b]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/libpython3.8.so.1.0 (                                           + 0x2a8daa)  [0x7f5e36aa8daa]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/libpython3.8.so.1.0 (                                           + 0x74d6d)  [0x7f5e36874d6d]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/libpython3.8.so.1.0 ( _PyEval_EvalFrameDefault                  + 0x7d86)  [0x7f5e3687cef6]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/libpython3.8.so.1.0 (                                           + 0x8006b)  [0x7f5e3688006b]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/libpython3.8.so.1.0 (                                           + 0x74d6d)  [0x7f5e36874d6d]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/libpython3.8.so.1.0 ( _PyEval_EvalFrameDefault                  + 0x12fd)  [0x7f5e3687646d]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/libpython3.8.so.1.0 ( _PyEval_EvalCodeWithName                  + 0x8fb )  [0x7f5e369cae3b]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/libpython3.8.so.1.0 ( PyEval_EvalCodeEx                         + 0x42  )  [0x7f5e369cb1c2]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/libpython3.8.so.1.0 ( PyEval_EvalCode                           + 0x1f  )  [0x7f5e369cb5af]
  /tmp/.mount_OpenShmPUw3k/usr/bin/lib/libpython3.8.so.1.0 (                                           + 0x1cfbf1)  [0x7f5e369cfbf1]
---- End of Stack Trace ----

**Screenshots:** (Optional)
Openshot did work but after trying to click at the end of the timeline, program ceased to respond would then only lauch briefly and immediatley crash

**Comment by Colorjet3** [comment]
Hello @karagiannis.  Please go to openshot.org/download/#daily and download v3.1.0-Release-Candidate-11128 AppImage.  There are many bug fixes and enhancements.

Let us know if this resolved your issue.

**Comment by Colorjet3** [comment]
Hello @karagiannis.  Any update on this?  Please be aware that a new v3.1.0-Release-Candidate-11141... has been released.  However, if you already are working with build #11128 then that is fine also.

**Comment by Colorjet3** [comment]
No feedback from user.
