### ISSUE TITLE
Unable to create new folder from the Save Project As... dialog

### ISSUE THREAD

**Issue by shodanx2** [OpenShot/openshot-qt#5191]
This is running openshot v2.6.1-release-candidate-8238-59878784-d588dbd6 build date 2021-09-04 23:49 (Please let me copy and paste this information from the about page)

![image](https://user-images.githubusercontent.com/10621885/230708059-d30205b8-8620-4e71-a166-1e000339d15f.png)

**Comment by Colorjet3** [comment]
Hello @shodanx2.  When your perform a File | Save Project As you are not creating a folder but rather a project (a .osp file).  Looking at your attachment just click on "New Folder", if that is your intention, and then save your project.

**Comment by shodanx2** [comment]
Hello,

I hadn't seen the new folder button

This is not a bug with openshot but with windows "select folder" dialog

Here is handbrake folder selection displaying the same behaviour when right click into the folder's background

![image](https://user-images.githubusercontent.com/10621885/230747856-3a982e91-29a8-4d38-9524-e406c7c03c2d.png)

Here is how I usually create folders when I'm in a folder

![image](https://user-images.githubusercontent.com/10621885/230747887-ecd2c9d3-09f3-4975-9157-8555e6016650.png)


Furthermore, I just checked on another PC and 

![image](https://user-images.githubusercontent.com/10621885/230747974-033fc88f-e8ec-4260-9e3c-b68beece5053.png)

It does not happen, so I'm closing this bug, it's my PC that is broken somehow.
