### ISSUE TITLE
I get "Not responding" at start-up

### ISSUE THREAD

**Issue by mjcoon** [OpenShot/openshot-qt#5192]
**Describe the bug:**
I started version 3.0.0 as usual and noticed it said "Update Available" so downloaded V3.1.0 and installed. But when I start it I just get "Not responding". I uninstalled and immediately re-installed from same download with exactly the same result.  I uninstalled and immediately re-installed from previous (V3.0.0) download and it works fine

**Steps to reproduce the behavior:**
See description.

**Expected behavior:**
Works as well as V3.0.0!

**System Details:**
Windows 10 64 bit, fully updated

**Log Files:**
I don't have a .openshot_qt folder in <C:\Program Files\OpenShot Video Editor> directory even though I have "Show hidden" ticked and normally see folders with initial dot OK.

**Exception / Stacktrace:**
No crash

**Screenshots:** (Optional)
Not applicable; standard status notification

**Comment by Colorjet3** [comment]
Hello @mjcoon.  Sorry to hear that you are having issues with v3.1.0-Release.  Please try the following:

1.  Close Opeshot if running.
2.  Make a backup of c:\users\username\.openshot_qt folder.  This is where the .openshot_qt folder lives and you need to "Show Hidden" files in c:\users\username folder enabled.
3.  Delete c:\users\username\.openshot_qt folder.
4.  Go to Add or Remove Programs and uninstall v3.0.0.
5.  Install v3.1.0.
6.  Let us know if this resolved your issue.

**Comment by mjcoon** [comment]
Thanks very much [Colorjet3] that did indeed resolve the problem!
Note that I install in c:\Program Files\, as I said under the heading "Log Files:"
This is where Win-10 likes to install code because, I believe, it is protected filestore and needs privilege for write access. Hence there are no logs there. So I did not choose it, I just accepted the proffered location. I have not tracked the logs down.

**Comment by Sidder3** [comment]
I was about to submit the same bug for Release version of 3.1.0
After initial install, Openshot freezes. 
openshot-qt.log is not created.

Going back to Release Candidate 11199 (form 31 March) - solves the issue.

**Comment by Colorjet3** [comment]
> Thanks very much [Colorjet3] that did indeed resolve the problem! Note that I install in c:\Program Files, as I said under the heading "Log Files:" This is where Win-10 likes to install code because, I believe, it is protected filestore and needs privilege for write access. Hence there are no logs there. So I did not choose it, I just accepted the proffered location. I have not tracked the logs down.

The program by default (64 bit) will install to c:\program files folder.  All the log files and user specific settings will be in c:\users\username\.openshot_qt folder.

**Comment by Colorjet3** [comment]
Hello @Sidder3.  Version 3.1.0-Release (Production) should work.  Please do this:
1. Close openshot.
2. Make a backup of c:\users\username\.openshot_qt folder.
3. delete c:\users\username\.openshot_qt folder.
4. Download v3.1.0-release from openshot.org home page.
5. Install it and it should work.

**Comment by Sidder3** [comment]
Hi @Colorjet3 
Thank you, I did that. Actually I always delete openshot_qt folder whenever I upgrade.

Unfortunately it didn't work...

Rolled back to 11199 (latest working for me) - and all fine.

**Comment by Colorjet3** [comment]
Hello @Sidder3.  Please do me a favor and start a new project.  I ask this because the original user that posted this the delete of the ..../.openshot_qt folder fixed the issue.  Since you are still having issues we will need to dig deeper so it would be better if we start a new thread.

When you submit your new post please provide following:
1.  What operating system/ver you are running (windows 10 Pro? Ubunut 22.04 lts? etc?)
2.  Provide the build # of the v3.1.0- that you are installing.
3.  In addition to deleting the ...\.openshot_qt folder, also uninstall build 11199 and then install v3.1.0-Release.

I may not have time to get back to you today, possibly later this evening and we can continue to troubleshoot.

**Comment by mjcoon** [comment]
Sorry, but I failed to "delete the ....\.openshot_qt folder, at least 
partly because (as I hinted) I mistook it for the installation folder. 
\AppData\... would be a more conventional place to put settings. though 
I do see some other ".xxx" folders there as well as .openshot_qt.

So it cannot have been the deletion of that folder (as you recommended) 
that cured my problem because I didn't do it!

However I have found another problem with both V3.1.0 and V3.0.0 which I 
have by passed by going back to V2.6.1 which was still in my download 
folder. Having received such a prompt response to Issue #5192 I must 
raise a fresh question for the new one.

Thanks again, Mike.

**Comment by Colorjet3** [comment]
Hello @mjcoon.  Are you then submitting another posting with the issue you are experiencing with v3.1.0 and v3.0.0?  That would be the recommended procedure.

Feel free to close this ticket or I can do it for you, assuming your issue is not related to "Not Responding".
