### ISSUE TITLE
Won't stay on chosen video profile.

### ISSUE THREAD

**Issue by OptimumPx** [OpenShot/openshot-qt#5196]
The new version won't stay on the video profile I want to use. No matter if I change it using preferences or manually on the editing screen, if I check it again it's moved to a different profile every single time.
I want to use the profile 'NTSC SD Anamorphic 480i 29.97 fps 720x480 4:3'
I select that and when I look again it's moved to 'NTSC SD Anamorphic 480i 29.97 fps 480x480 4:3'

If I try to set it to 'NTSC SD Anamorphic 480p 29.97 fps 720x480 4:3'
then it changes to 'NTSC SD Anamorphic 480p 29.97 fps 704x480 16:9'

Neither version of the profile I want to use stays there. I'm having to manually pick my profile on the export screen to get the profile I want on the finished video.

**System Details**
- OpenShot Version: 3.1.0
- libopenshot Version:  0.3.1
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.1.0-daily-11243-c472a248-b6f9fcf2-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/yvsbzjh1wldgjd0e3gdcji0cu6zcwv09/openshot-qt.zip) (19 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/yvsbzjh1wldgjd0e3gdcji0cu6zcwv09/libopenshot.zip) (5 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
https://i.imgur.com/BpYFJfi.png
https://i.imgur.com/3psd51Z.png

**Comment by Colorjet3** [comment]
Hello @OptimumPx.  I am unable to replicate your issue.

1.  When you start Openshot the Default Profile is set to HD 720p 30 fps (1280x720).
2.  If you want to change this default there are two approaches:
First approach:  
a.  Start Openshot
b.  Go to Edit | Preferences | Preview tab and change the Default Profile to your choosing.
c.  You must restart Openshot for this to take effect.
d.  From now on any time you start Openshot it will be this new profile you chose.
e.  When you Export it should default to this Profile as well, which you can override if needed.

Second approach:
a.  Start Openshot.
b.  Create a new project and save it.  The Profile defaults to whatever your preferences is setup to.
c.   If you want a different profile for this project only, then click on the "Film Strip" and select a different profile.
d.  You now must save the project for this profile to be saved for this project only.  If you don't save the project and reopen it then it will revert to whatever it was previously.

Now, if you are experiencing something different then try this before we troubleshoot further:
1.  Close Openshot.
2.  Make a backup of c:\users\username\.openshot_qt folder.
3.  Delete c:\users\username\.openshot_qt folder.
4.  Start Openshot and follow my "approaches" I provided above.

**Comment by OptimumPx** [comment]
I've tried changing the video profile from preferences (complete with a restart). I've tried deleting the entire openshot_qt folder. I've tried changing the video profile from the filmstrip icon. I've tried saving it during a project. I've tried uninstalling the entire program and reinstalling it. 
Same result every single time. It instantly changes the profile to a different one with the same name but different video size.

**Comment by Colorjet3** [comment]
Hello @OptimumPx.  I would like to see a video capture of what you are experiencing.  Thank you in advance!

**Comment by OptimumPx** [comment]
Here you go.
The 1st video shows my manually changing it via the filmstrip button twice.
The 2nd one show me trying through preferences and restarting the program and it still being on the wrong profile.

https://user-images.githubusercontent.com/130314865/230981057-c86d900b-90a3-4874-ac04-26d1e33ad81a.mp4

https://user-images.githubusercontent.com/130314865/230981134-d7473123-50d2-40c3-8943-02b24d76107d.mp4

**Comment by Colorjet3** [comment]
Hello @OptimumPx .  Thank you so much for the videos and I am able to replicated this as well.  I am going to escalate this to the lead developer to review this and come up with a fix.  Stay tuned....

**Comment by jonoomph** [comment]
Taking a look at this now...

**Comment by Colorjet3** [comment]
@OptimumPx.  Here is the internal ticket that has been created and the Technical lead/developer is looking into it:  https://trello.com/c/vdRqG8DO/23-chosen-profile-does-not-stay-selected

**Comment by OptimumPx** [comment]
Thank you guys for looking into it!

**Comment by jonoomph** [comment]
This has been fixed in https://github.com/OpenShot/openshot-qt/pull/5200. It will appear in our daily builds very shortly: https://www.openshot.org/download#daily. Thanks for the bug report!

**Comment by Colorjet3** [comment]
Hello @OptimumPx.  As @jonoomph mentioned above, Daily Build #11270 has the fix for your Profile selection issue.  Please downloaded, install it, and let us know either way.

Also, please note that in the Title section right above the main menu and next to the Project file name, the Profile name selected, now shows more of the Profile name so you can better see what you have selected.

**Comment by OptimumPx** [comment]
Thank you! I downloaded the newest version and it worked great now!
Thanks for the help!
