### ISSUE TITLE
Hardware Decoder Mode (D3D9 & D3D11) doesn't work

### ISSUE THREAD

**Issue by ghost** [OpenShot/openshot-qt#5197]
**Describe the bug:**
D3D9 and D3D11 are listed in Hardware Decoder Mode. However, none of them work. If I select any of them and try to work with any video then the video is glitched. If the 'Test' button in Performance tab is clicked, X mark is displayed. Only CPU (No acceleration) is functional but it is far from perfect.

**Steps to reproduce the behavior:**
1. Go to 'Edit'
2. Click on 'Preferences'
3. Select 'Performance' tab
4. Scroll the list
5. Select D3D9 or D3D11
6. Click on 'Test' button
7. Try out any video

**Expected behavior:**
Videos are displayed properly.

**System Details:**
- OpenShot Version [3.1.0]
- Operating System / Distro: [Windows 7 x64]
- NVIDIA GeForce Graphics Card

**Comment by Colorjet3** [comment]
Hello @Mitch037.  Hardware acceleration currently is not supported in Windows.  Please change the "Hardware Decoder Mode" back to "No acceleration".

This is a known issue and is being tracked by the DEV team.  No ETA at this time.

**Comment by Tetriser** [comment]
Got an X after testing my GPU with DirectX
GPU is GeForce GTX 1660 Super

![Image](https://github.com/user-attachments/assets/b2d252ed-d3a8-47a2-bfa1-7209516d38fd)
