### ISSUE TITLE
Edited video has static image

### ISSUE THREAD

**Issue by mjcoon** [OpenShot/openshot-qt#5198]
**Describe the bug:**
I'm a very unambitious user and my typical session involves removing boring(-est) bits of a video exactly as here. But prior to V3.0.0 & V3.1.0 the result had not been a video of a static image.

**Steps to reproduce the behavior:**
Import video and put it on the timeline.
Preview play until finding the interesting portion.
Split at that point and keep right-hand portion.
Rewind and move the remaining clip to the start of the timeline.
Preview again, but the previewed image remains static.
Export the video and the exported version also has a static image.

**Expected behavior:**
Go back to V2.6.1.0 which I happen to have in my Downloads folder and the video moves as normal

**System Details:**
- OpenShot Versions see above
- Operating System Windows 10 64 bit

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
Hello @mjcoon.

Please do the following:
1.  Close Openshot.
2.  Go to Add or Remove Programs.
3.  Search for Openshot and perform Uninstall.  There is a chance that you will find multiple entries (v2.6.x and v3.0.0 or v3.1.0).  Uninstall any Openshot entry you find.
4.  Make a backup of c:\users\username\.openshot_qt folder.
5.  Delete c:\users\username\.openshot_qt folder.
6.  Download a fresh copy of v3.1.0 and install it.
7.  Start Openshot but don't open an existing project.
8.  Import a video file and drag it onto the timeline.
9.  Preview until you find the interesting portion.
10.  Slice All and keep the right side.
11.  Shift the clip on the track to the start of the timeline.
12.  Preview again.
13.  Did this work?
14.  If not, please make a video recording and repeat your steps so we can see what is going on.

**Comment by Colorjet3** [comment]
No response from the user.
