### ISSUE TITLE
no way of prerendering and viewing whole animation in animated blender

### ISSUE THREAD

**Issue by 07pepa** [OpenShot/openshot-qt#520]
Hi there
This is rather problem of desing decision during programing than actual flaw
it one thing it i have problem with.... i canot see what blender did before final blend... sorry :D render

it is now programed in that way that Open shot can fetch only one frame.... but there is no way of checking it before final render.... aslo noobs like me do not know how whole animation look.

i understand a purpose of curent frame by frame aproach.... it is turbo fast.... and thus good for fast checking... but if you want to view whole "thing" it is useless.....

and  "live" full lenght prewiev would be nice
two ways to do it "fast"
1) perhaps store all seting parameters as "metadata" of this set of frames and then on final "render" checked if curent prewiev render was based on same parameters it just can save pre-rendered previev  (asuming it would be in same quality as final render...) full quality but slow full previev

2nd) solution/aproach for this could be low quality(resolution) fast full lenght render prewiew.. and on final render you would dump low resolution preview and re-render it in max quality

it is just idea and it is on you if you (and how) implement it

THX

**Comment by DylanC** [comment]
@07pepa - Thanks for the feedback. We will discuss this.
