### ISSUE TITLE
Crash on exiting title edit window

### ISSUE THREAD

**Issue by jake-is-ESD-protected** [OpenShot/openshot-qt#5203]
**Describe the bug:**
Opening an existing `title.svg` with right-click `Edit` in the Project Files opens the `Title`-editor which then cannot be left via `Cancel` or `Save` without the program closing if the title clip is in the timeline.

**Steps to reproduce the behavior:**
1. Open `Title` (Ctrl+T)
2. Save the new title (doesn't matter if the template has been modified or not)
3. Drag the title from the Project Files into the timeline
4. Right-click the `title.svg` in the Project Files -> `Edit`
5. Make a change
6. `Save` or `Cancel`
7. Program crashes

**Expected behavior:**
The title gets updated and can be seen in the preview if the red bar is on the title edited.

**System Details:**
- OpenShot Version 3.1.0, libopenshot 0.3.1
- Operating System / Distro: Linux Zorin OS 16.2

**Log Files:**
> **This log does not mention the crash (???)**
```
15:34:02 INFO app: ------------------------------------------------
15:34:02 INFO app:             Thu Apr 13 15:34:02 2023            
15:34:02 INFO app:               Starting new session              
15:34:02 INFO app: ------------------------------------------------
15:34:02 INFO app:             OpenShot (version 3.1.0)            
15:34:02 INFO app: ------------------------------------------------
15:34:02 INFO app: openshot-qt version: 3.1.0
15:34:02 INFO app: libopenshot version: 0.3.1
15:34:02 INFO app: platform: Linux-5.15.0-69-generic-x86_64-with-glibc2.35
15:34:02 INFO app: processor: 
15:34:02 INFO app: machine: x86_64
15:34:02 INFO app: python version: 3.10.6
15:34:02 INFO app: qt5 version: 5.15.8
15:34:02 INFO app: pyqt5 version: 5.15.1
15:34:02 INFO project_data: Setting profile to FHD 1080p 30 fps
15:34:02 INFO project_data: Apply default audio playback settings: 48000, 2 channels
15:34:02 INFO app: checking babl_ext_path: /app/lib/python3.10/site-packages/openshot_qt/lib/babl-ext
15:34:02 INFO language: Qt Detected Languages: ['en-US', 'en', 'en-Latn-US']
15:34:02 INFO language: LANG Environment Variable: en_US.UTF-8
15:34:02 INFO language: LOCALE Environment Variable: 
15:34:02 INFO language: OpenShot Preference Language: Default
15:34:02 INFO app: Setting font to /app/lib/python3.10/site-packages/openshot_qt/images/fonts/Ubuntu-R.ttf
15:34:02 INFO app: Setting custom dark theme
15:34:03 INFO logger_libopenshot: Connecting to libopenshot with debug port: 5556
15:34:03 INFO ui_util: Initializing UI for MainWindow
15:34:03 INFO thumbnail: Starting thumbnail server listening on ('127.0.0.1', 43085)
15:34:03 INFO webkit: WebKit backend initializing
15:34:03 INFO transition_model: updating transitions model.
15:34:03 INFO version: Found current version: {'trans_rate_stable': 0.01, 'openshot_version': '3.1.0', 'error_rate_unstable': 0.05, 'trans_rate_unstable': 0.001, 'error_rate_stable': 0.5}
15:34:03 INFO effects_model: updating effects model.
15:34:03 INFO emoji_model: updating emoji model.
15:34:04 INFO main_window: InitCacheSettings
15:34:04 INFO main_window: cache-mode: CacheMemory
15:34:04 INFO main_window: cache-limit-mb: 512
15:34:04 INFO main_window: cache-ahead-percent: 0.7
15:34:04 INFO main_window: cache-preroll-min-frames: 24
15:34:04 INFO main_window: cache-preroll-max-frames: 48
15:34:04 INFO main_window: cache-max-frames: 600
15:34:04 INFO main_window: Creating CacheMemory object with 536870912 byte limit
15:34:04 INFO preview_thread: QThread Start Method Invoked
15:34:04 ERROR main_window: Unhandled crash detected: linux-/usr/lib/x86_64-linux-gnu/libc.so.6 raise 0x1e [0x7f6b5bbf800e]
15:34:04 INFO main_window: updateStatusChanged
15:34:04 INFO main_window: recover_backup
15:34:04 INFO project_data: Setting profile to FHD 1080p 30 fps
15:34:04 INFO project_data: Apply default audio playback settings: 48000, 2 channels
15:34:04 INFO video_widget: Load: Set video widget display aspect ratio to: 1.7777777910232544
```

Hopefully I'm just doing something wrong, I can't be the only person editing a title clip.

**Comment by Colorjet3** [comment]
Hello @jake-is-ESD-protected.  I just testing in Ubuntu 22.10 (I don't have your version of Linux).  I've been testing with Title creation for some time now and have not noticed Openshot crashing.

Try this:
1.  Close Openshot if running.
2.  Rename /home/username/.openshot_qt folder.
3.  Start Openshot and try your steps again.

Let me know either way.

**Comment by jake-is-ESD-protected** [comment]
I renamed the folder and accordingly, a new one got created after starting the app. The app now opens as if it's the first time opening it after install. The same issue is still present.
![openshot_crash](https://user-images.githubusercontent.com/78532991/231799817-e9b5803d-9882-489f-bf82-984d1ed3dfbc.gif)

**Comment by jake-is-ESD-protected** [comment]
As Zorin OS is based on Ubuntu, I can't imagine why it would work there but not here.

**Comment by jake-is-ESD-protected** [comment]
Tried it again with a completely fresh install of the whole OS with external GPU. Still the same.

**Comment by Colorjet3** [comment]
Hello @jake-is-ESD-protected Please try running the latest DEV Daily Build AppImage.  Let's see if we can get you moving forward as we try to troubleshoot your existing issue.

1.  Go to openshot.org/download/#daily.
2.  download the latest DEV Daily build available.
3.  Make it an executable and run it.
4.  Try your Title creation again.

**Comment by Colorjet3** [comment]
Hello @jake-is-ESD-protected  A production release has been published (v3.1.1).  You can go to openshot.org home page and DOWNLOAD V3.1.1 AppImage and give it a try.

I am going to close this ticket since I haven't gotten an update from you.  Feel free to reopen and we can continue to troubleshoot.

**Comment by ankostis** [comment]
I'm having the exact same issue, Openshot v3.1.0, debian SID, crashes deterministically.

**Comment by ankostis** [comment]
I confirm that v3.1.1 crashes no more!
Well done :+1:

**Comment by Colorjet3** [comment]
That is great @ankostis and really appreciate the feedback.  Best of luck with your projects.
