### ISSUE TITLE
unable to preview videos from recent projects using earlier versions of openshot

### ISSUE THREAD

**Issue by arjava** [OpenShot/openshot-qt#5206]
I just updated openshot from 3.0.0 to 3.1.0, and I have a project on openshot 3.0.0, but when I open using 3.1.0 there is a black screen on the video preview. I've searched for this problem on the internet, but there is no answer, so what should I do to solve it?

**Comment by arjava** [comment]
I solved it, it turns out that we need to put the video track on the top track

**Comment by Colorjet3** [comment]
Hello @arjava.  Glad you were able to solve your issue.
