### ISSUE TITLE
Openshot opens and closes immediately

### ISSUE THREAD

**Issue by JandeWet7777** [OpenShot/openshot-qt#5207]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 3.1.0
- libopenshot Version:  0.3.1
- Platform: Windows-10-10.0.22621
- Processor: Intel64 Family 6 Model 154 Stepping 3, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-GB', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Skipped this step

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/rfofeed34fqbac4pvztq4ih3co5msyhp/openshot-qt.zip) (5 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
Hello @JandeWet7777.  Please go to openshot.org/download/#daily and download the latest DEV Daily Build available.  Install it and let us know if this fixed the startup issue.

**Comment by JandeWet7777** [comment]
I have done it

 

Jan de Wet

email ***@***.*** ***@***.***> 

Tel 082-902-1996

 

Jesus Christ is my Lord

**Comment by Colorjet3** [comment]
Hello @JandeWet7777.  Did the latest DEV Daily Build resolve your issue?

**Comment by Colorjet3** [comment]
Hello @JandeWet7777.  A new production release has been published.  Please go to openshot.org and click on the blue box that says DOWNLOAD v3.1.1.

I am going to close this ticket since I haven't received a response from you at this time.
