### ISSUE TITLE
Backgorund audio

### ISSUE THREAD

**Issue by JetsAudio** [OpenShot/openshot-qt#521]
Can I background music to my video.  The video does contain people talking

**Comment by ankitpati** [comment]
1. Import the video, and the music into the project using the + button in the toolbar.
2. Place the video on one track, and the music on another track.
3. Export.

Hope this solves your issue.

**Comment by JetsAudio** [comment]
Thank you.  The background audio is too loud and when I adjust to 10% for
entire clip, the volume does not change.  How can I lower the background
audio or increase the video audio?

**Comment by ankitpati** [comment]
I just tried that, and it works fine for me. Looks like another platform specific bug.

Can you please file a new issue with the details of your OS and hardware?
