### ISSUE TITLE
OpenShot Video Editor開啟沒有反應

### ISSUE THREAD

**Issue by HsuCC** [OpenShot/openshot-qt#5215]
**描述錯誤**
A clear and concise description of the issue

**重現行為的步驟：**
1. 前往「...」
2. 按下「....」
3. 往下捲動到「....」
4. 檢視錯誤

**預期的行為**
清楚簡潔地描述您期望發生的事情。

**系統詳細資料**
- OpenShot Version: 3.1.1
- libopenshot Version:  0.3.2
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['zh-TW', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- 每日構建：無法驗證每日構建中是否仍存在問題

**日誌檔**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/n2xo033te882xv3v63vllyosr6cl0h0v/openshot-qt.zip) (20 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/n2xo033te882xv3v63vllyosr6cl0h0v/libopenshot.zip) (0 KB)

**異常情況 / 堆疊追踪**
```No stacktrace found in log files```

**螢幕擷圖** (選填)
如果可以，請加入畫面截圖，可以有助說明情況。請截取
畫面並將之貼到 GitHub，又或將之拖曳到 GitHub 頁面。
所有圖片都是公開的，所以請勿貼上帶有個人資料的圖片。

**Comment by Colorjet3** [comment]
1. 进入 c:\users\username\.openshot_qt 文件夹。
2. 使用文本编辑器编辑 openshot.settings 文件。
3. 搜索“默认采样率”。
4. 在此行下方，您会发现：“值”：44100。
5.将44100改为48000
6. 小心不要添加任何额外的字符或删除任何字符。
7. 保存这个文件。
8. Openshot 现在应该开始了。

1. Jìnrù c:\Users\username\.Openshot_qt wénjiàn jiā.
2. Shǐyòng wénběn biānjí qì biānjí openshot.Settings wénjiàn.
3. Sōusuǒ “mòrèn cǎiyàng lǜ”.
4. Zài cǐ xíng xiàfāng, nín huì fāxiàn:“Zhí”:44100.
5. Jiāng 44100 gǎi wèi 48000
6. Xiǎoxīn bùyào tiānjiā rènhé éwài de zìfú huò shānchú rènhé zìfú.
7. Bǎocún zhège wénjiàn.
8. Openshot xiànzài yīnggāi kāishǐle.

**Comment by Colorjet3** [comment]
No response from user.
