### ISSUE TITLE
openshot_version": "3.1.0" - Ubuntu 22.04 Not loading

### ISSUE THREAD

**Issue by kpsanal** [OpenShot/openshot-qt#5216]
`Apr 18 22:33:08 my-machine-g systemd[4809]: Started Application launched by gnome-shell.
Apr 18 22:33:08 my-machine-g org.openshot.OpenShot.desktop[13038]:          app:INFO ------------------------------------------------
Apr 18 22:33:08 my-machine-g org.openshot.OpenShot.desktop[13038]:          app:INFO             Tue Apr 18 22:33:08 2023
Apr 18 22:33:08 my-machine-g org.openshot.OpenShot.desktop[13038]:          app:INFO               Starting new session
Apr 18 22:33:08 my-machine-g org.openshot.OpenShot.desktop[13038]:          app:INFO ------------------------------------------------
Apr 18 22:33:08 my-machine-g org.openshot.OpenShot.desktop[13038]:          app:INFO             OpenShot (version 2.5.1)
Apr 18 22:33:08 my-machine-g org.openshot.OpenShot.desktop[13038]:          app:INFO ------------------------------------------------
Apr 18 22:33:08 my-machine-g org.openshot.OpenShot.desktop[13038]:          app:INFO openshot-qt version: 2.5.1
Apr 18 22:33:08 my-machine-g org.openshot.OpenShot.desktop[13038]:          app:INFO libopenshot version: 0.2.5
Apr 18 22:33:08 my-machine-g org.openshot.OpenShot.desktop[13038]:          app:INFO platform: Linux-5.19.0-40-generic-x86_64-with-glibc2.35
Apr 18 22:33:08 my-machine-g org.openshot.OpenShot.desktop[13038]:          app:INFO processor: x86_64
Apr 18 22:33:08 my-machine-g org.openshot.OpenShot.desktop[13038]:          app:INFO machine: x86_64
Apr 18 22:33:08 my-machine-g org.openshot.OpenShot.desktop[13038]:          app:INFO python version: 3.10.6
Apr 18 22:33:08 my-machine-g org.openshot.OpenShot.desktop[13038]:          app:INFO qt5 version: 5.15.3
Apr 18 22:33:08 my-machine-g org.openshot.OpenShot.desktop[13038]:          app:INFO pyqt5 version: 5.15.6
Apr 18 22:33:08 my-machine-g org.openshot.OpenShot.desktop[13038]:      metrics:ERROR Error determining OS version in metrics.py
Apr 18 22:33:08 my-machine-g org.openshot.OpenShot.desktop[13038]:     language:INFO Qt Detected Languages: ['en-IN', 'en']
Apr 18 22:33:08 my-machine-g org.openshot.OpenShot.desktop[13038]:     language:INFO LANG Environment Variable: en_IN
Apr 18 22:33:08 my-machine-g org.openshot.OpenShot.desktop[13038]:     language:INFO LOCALE Environment Variable:
Apr 18 22:33:08 my-machine-g org.openshot.OpenShot.desktop[13038]:     language:INFO OpenShot Preference Language: Default
Apr 18 22:33:08 my-machine-g org.openshot.OpenShot.desktop[13038]: project_data:INFO Setting default profile to HD 720p 30 fps
Apr 18 22:33:08 my-machine-g org.openshot.OpenShot.desktop[13038]: ZmqLogger::Connection - Error binding to tcp://*:5556. Switching to an available port.
Apr 18 22:33:09 my-machine-g org.openshot.OpenShot.desktop[13038]: ZmqLogger::Connection - Error binding to tcp://*:5556. Switching to an available port.
Apr 18 22:33:09 my-machine-g org.openshot.OpenShot.desktop[13038]:          app:INFO Setting font to Cantarell
Apr 18 22:33:09 my-machine-g org.openshot.OpenShot.desktop[13038]: logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
Apr 18 22:33:09 my-machine-g org.openshot.OpenShot.desktop[13038]:          app:INFO Setting custom dark theme
Apr 18 22:33:09 my-machine-g org.openshot.OpenShot.desktop[13038]: QMainWindow::addDockWidget: invalid 'area' argument
Apr 18 22:33:09 my-machine-g org.openshot.OpenShot.desktop[13038]:      ui_util:INFO Initializing UI for MainWindow
Apr 18 22:33:09 my-machine-g org.openshot.OpenShot.desktop[13038]:   exceptions:ERROR Unhandled Exception
Apr 18 22:33:09 my-machine-g org.openshot.OpenShot.desktop[13038]: Traceback (most recent call last):
Apr 18 22:33:09 my-machine-g org.openshot.OpenShot.desktop[13038]:   File "/usr/bin/openshot-qt", line 33, in <module>
Apr 18 22:33:09 my-machine-g org.openshot.OpenShot.desktop[13038]:     sys.exit(load_entry_point('openshot-qt==2.5.1', 'gui_scripts', 'openshot-qt')())
Apr 18 22:33:09 my-machine-g org.openshot.OpenShot.desktop[13038]:   File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 97, in main
Apr 18 22:33:09 my-machine-g org.openshot.OpenShot.desktop[13038]:     app = OpenShotApp(argv)
Apr 18 22:33:09 my-machine-g org.openshot.OpenShot.desktop[13038]:   File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 219, in __init__
Apr 18 22:33:09 my-machine-g org.openshot.OpenShot.desktop[13038]:     self.window = MainWindow(mode)
Apr 18 22:33:09 my-machine-g org.openshot.OpenShot.desktop[13038]:   File "/usr/lib/python3/dist-packages/openshot_qt/windows/main_window.py", line 2521, in __init__
Apr 18 22:33:09 my-machine-g org.openshot.OpenShot.desktop[13038]:     self.timeline = TimelineWebView(self)
Apr 18 22:33:09 my-machine-g org.openshot.OpenShot.desktop[13038]:   File "/usr/lib/python3/dist-packages/openshot_qt/windows/views/timeline_webview.py", line 3000, in __init__
Apr 18 22:33:09 my-machine-g org.openshot.OpenShot.desktop[13038]:     self.cache_renderer.setInterval(0.5 * 1000)
Apr 18 22:33:09 my-machine-g org.openshot.OpenShot.desktop[13038]: TypeError: setInterval(self, int): argument 1 has unexpected type 'float'
Apr 18 22:33:11 my-machine-g org.openshot.OpenShot.desktop[13038]:      version:INFO Found current version: {"error_rate_unstable": 0.05, "error_rate_stable": 0.5, "openshot_version": "3.1.0", "trans_rate_unstable": 0.001, "trans_rate_stable": 0.01}

`

**Comment by Colorjet3** [comment]
Hello @sethuit.
1.  go to openshot.org/download/#daily
2.  download the latest DEV Daily Build AppImage available.  It should be v3.1.1-Release-Candidate.
3.  Run this and let me know if it works for you.

This doesn't resolve your existing issue but we can troubleshoot further, if needed, based on the AppImage result.

**Comment by newt** [comment]
> Hello @sethuit.
> 
> 1. go to openshot.org/download/#daily
> 2. download the latest DEV Daily Build AppImage available.  It should be v3.1.1-Release-Candidate.
> 3. Run this and let me know if it works for you.
> 
> This doesn't resolve your existing issue but we can troubleshoot further, if needed, based on the AppImage result.

I don't see deb-package, where can I get daily .deb?

**Comment by Colorjet3** [comment]
I did not say deb-package.  I am asking you to download the AppImage found at openshot.org/download/#daily.

**Comment by Colorjet3** [comment]
Hi newt,
  Here is a direct link to the latest [v3.1.1-Release-Candidate](https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v3.1.1-release-candidate-11382-639e8460-e47da46f-x86_64.AppImage).

Please run this and let us know if you are still having issues.

Thank you!

**Comment by HusseinyAH** [comment]
I have downloaded the appimage, changed to executable yet it doesn't work..

**Comment by Colorjet3** [comment]
Hello @HusseinyAH.  This may be due to so some missing libraries.  From a terminal session please run this command:

sudo apt isntall libfuse2

After this installation is complete give the AppImage a try again.

**Comment by HusseinyAH** [comment]
it worked, thanks a lot

**Comment by Colorjet3** [comment]
That is awesome @HusseinyAH.  Best of luck with your projects.
