### ISSUE TITLE
Open and close after recover project

### ISSUE THREAD

**Issue by robjreis** [OpenShot/openshot-qt#5217]
**Describe the bug**
On open the program restores last project. After a while it closes automaticly

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 3.1.0
- libopenshot Version:  0.3.1
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['pt-PT', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Skipped this step

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/6mmmjen30f79e9ve15idgw98qg7k0ruc/openshot-qt.zip) (113 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/6mmmjen30f79e9ve15idgw98qg7k0ruc/libopenshot.zip) (13 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
Hello @robjreis

1. Did this just start happening or this is the first time?
2. Try this:

- Backup c:\users\username\.openshot_qt folder.
- Delete c:\users\username\.openshot_qt folder.
- Start Openshot.
- If it closes again then continue to step 3.

3.  Edit c:\users\username\.openshot_qt\openshot.settings file using notepad

- Search for default-samplerate
- The next line below this line is "value":  44100,
- Change the 44100 to 48000  <-- this line should look like this now:  "value":  48000,
- Make sure you are absolutely not inserting or deleting any other character or lines.  Not even adding an extra space anywhere.
- Save it and start Openshot

Let me know the results.

**Comment by robjreis** [comment]
Solved with step 2. Thank you very much

**Comment by Colorjet3** [comment]
Thank you @robjreis for the FYI and good luck with your projects.

By the way, keep an eye on v3.1.1 being released in about a week or so.
