### ISSUE TITLE
Uploading log files when submitting a bug fails with error 

### ISSUE THREAD

**Issue by BloodBaz** [OpenShot/openshot-qt#5219]
I'm trying to submit a bug relating to Audio playback in Preview is completely distorted even when there is just a WAV file and nothing else.  I've followed the "report a bug" process but when uploading the two log files I get the following error message back.:

Error: Log files are missing OpenShot version information.
If you are having issues finding your log files, or if the log files are not yet created, you can also submit a bug report [directly on GitHub](https://github.com/OpenShot/openshot-qt/issues/new/choose).

The log file contents looks perfectly acceptable.

**Steps to reproduce the behavior:**
1. Go to [Report a bug](https://www.openshot.org/en/issues/new/)
2. Delete log files as instructed
3. Run Openshot to create log files while using Debug (Verbose) setting in Preferences (as advised)
4. Upload log files as per step 3

**Expected behavior:**
Log files to be accepted by "Report a bug"

**System Details:**
- OpenShot-v3.1.1-release-11392-7100dc7a-e47da46f (Official)
- Windows 11 Professional
- AMD Ryzen 9 3900 12-Core Processor 3.40 GHz
- 32GB RAM

**Log Files:**
Log files that are NOT accepted by "Report a bug" are attached.
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/11291093/openshot-qt.log)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/11291094/libopenshot.log)

**Comment by BloodBaz** [comment]
Maybe I still had OpenShot open when I tried to upload the log files (sure I didn't) but eventually it did work.

**Comment by Colorjet3** [comment]
Hello @BloodBaz 
1.  Did you happen to upgrade from a previous version or is this the first time you have installed Openshot?
2.  Do you have any other .wav files to test with?  if yes, does the issue exist with other .wav files or just this one?
3.  Have you tried other file type (.mp3, .mp4, etc)?  If yes, does the issue still exist?

Try this as well,
1.  Close Openshot.
2.  Make a backup of c:\users\username\.openshot_qt folder.
3.  Delete c:\users\username\.openshot_qt folder.
4.  Start Openshot and try your .wav file again.
