### ISSUE TITLE
Audio playback in Preview completely corrupted/incomprehensible/distorted

### ISSUE THREAD

**Issue by BloodBaz** [OpenShot/openshot-qt#5220]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**
1. Open OpenShot with a new empty project
2. Drop a WAV file with sample rate of 44100 into the  Project Files area
3. Drag the WAV file from Proejct Files area onto a Track
4. Press Play on the Preview

**Expected behavior**
Clear audio as can be heard when playback is via Audacity or any other player

**Actual behavior**
Audio playback in preview is completely corrupted/incomprehensible/distorted.

Also tried with original WAV with sample rate of 48000.  

**System Details**
- OpenShot Version: 3.1.1
- libopenshot Version:  0.3.2
- Platform: Windows-10-10.0.22621
- Processor: AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-GB', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.1.1-release-candidate-11392-7100dc7a-e47da46f-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/30qkj58hb3nsjvjuczlpemky2eaanj8s/openshot-qt.zip) (1320 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/30qkj58hb3nsjvjuczlpemky2eaanj8s/libopenshot.zip) (1036 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by BloodBaz** [comment]
Was about to work around the problem by changing the output audio device under Edit > Preferences > Preview > Playback Audio Device.  
DirectSound: Primary Sound Driver worked wheras Window Audio: Speakers (RealTek(R) Audio) didn't - even through the audio ends up coming out the same speakers!

**Comment by Colorjet3** [comment]
Hello @BloodBaz Yes, I've seen that on some systems as well, and primarily in the Windows environment.  Openshot still needs some improvements in the Audio detection realm.  It is even more challenged when changing Audio devices, say plugging int headphones and then removing them.  Openshot doesn't react well and often must be restarted for the Audio detection to work properly.

Glad you found your fix and for the FYI as this will help others well.
