### ISSUE TITLE
Openshot 2.2.0 does not play webm files recorded with webcam

### ISSUE THREAD

**Issue by jkohvakk** [OpenShot/openshot-qt#523]
**System Details:**
Operating System / Distro: Ubuntu 16.04
OpenShot Version: 2.2.0

Openshot 2.2 does not play webm files recorded with my webcam. Openshot 1.4.4 played these just fine. 2.2 just shows some occasional frames and no sound at all. 

Here is a short example video I recorded and was not able to play in Openshot: https://drive.google.com/file/d/0BzUgEOw2Ju3JZXhPVXNHcXRJSUU/view?usp=sharing

I even tried to convert the file to mp4 with ffmpeg -i second_webcam.webm -qscale 0 -strict -2 second_webcam.mp4 but the result was exactly the same. Video not playing.

ffprobe says:

```
jkohvakk@janne-ZBook:~/Videos$ ffprobe short_video_with_cheese.webm 
ffprobe version 2.8.11-0ubuntu0.16.04.1 Copyright (c) 2007-2017 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Input #0, matroska,webm, from 'short_video_with_cheese.webm':
  Metadata:
    encoder         : GStreamer matroskamux version 1.8.3
    creation_time   : 2017-03-09 05:33:32
  Duration: 00:00:10.59, start: 0.000000, bitrate: 3533 kb/s
    Stream #0:0(eng): Video: vp8, yuv420p, 1280x720, SAR 1:1 DAR 16:9, 250 tbr, 1k tbn, 1k tbc (default)
    Metadata:
      title           : Video
    Stream #0:1(eng): Audio: vorbis, 44100 Hz, mono, fltp (default)
    Metadata:
      title           : Audio
```

**Comment by ankitpati** [comment]
Unable to reproduce the issue on Ubuntu 16.04 and OpenShot 2.2. The video plays back just fine. There is no sound because although the file has a soundtrack, as correctly reported by `ffprobe`, it is completely silent, as I found by examining the file with Audacity. Playing it with other media players also did not produce any sound.

Are you able to hear any sound when playing it with other media players? If not, the issue is likely with the machine not recording the sound.

Can you attach the outputs of
1. `lspci && usb-devices`
2. OpenShot 2.2 invoked from the command line, with the actions that cause the issue performed in the GUI.

**Comment by croco3008** [comment]
I did a test with OpeShot 2.2-dev and agree - it's not working. Playback is very weird compared to original.

**Comment by DFOXpro** [comment]
I find the same problem, even when I see the OpenShot rendered project notice the webm part video was complete garbage (still images and no sound). any way I also found other players like MPlayer have issues with this format, my solution was to convert the webm file [ 1 ]  and redo the openshot processing of this video

[ 1 ] ffmpeg -i one.webm -r 10 -cpu-used 5 -c:v libx264 -crf 20 -c:a aac -strict experimental -loglevel error /tmp/one.mp4

**Comment by dsx724** [comment]
+1 to this. using the latest stable with a webm 1080p video. the video preview cuts out after 2 seconds.

**Comment by stanfieldr** [comment]
I'm using 2.4, having the same issue... video and audio stop around 2 seconds.

**Comment by ndawe** [comment]
Same here. Stops after a few seconds and hangs.

**Comment by DylanC** [comment]
@jkohvakk - Is this using the AppImage or not?

**Comment by DylanC** [comment]
Confirmed as working in #829 in OpenShot v2.4.1.

**Comment by vernsix** [comment]
I am also experiencing this problem.  The video plays the first half second or so and then nothing after that even though the timer moves across like it should be playing just fine.

**Comment by DylanC** [comment]
@vernsix - Use the AppImage. I think its the PPA doesn't work well with webm.

**Comment by yeti-detective** [comment]
I was having this issue using the OpenShot PPA (playback/export of webM files was garbage) removed it & installed the AppImage & it works just fine (have to doop the audio track back a 1/2 second, but might be my webcam.)
