### ISSUE TITLE
Open shot 2.2 32bit

### ISSUE THREAD

**Issue by KryptoknightDB** [OpenShot/openshot-qt#524]
I have a 64 bit processor hp laptop but it has win 10 32 bit and i dont want to leave my oemto upgrade to 64 bit os so please!please!please!please!please!please!please!please!please!please!please!please!please!please!please!please!please!please!please!please!please!please!please!please!please!please!please!please!please!please!please!
give a 32 bit version
 
The setup file even says OpenShot-v2.2.0-x86_64.exe so why cant i use it

**Comment by KryptoknightDB** [comment]
As it is open source so can anyone edit the source code and give 32 bit installer

**Comment by ankitpati** [comment]
The OpenShot project has no plans to provide 32 bit builds for Windows, due to the additional work involved.

`OpenShot-v2.2.0-x86_64.exe` does not imply `x86` or `x64`; it means `x86_64` as a whole.
