### ISSUE TITLE
Caption Effect doesn't like decimal numbers with more than four decimal places

### ISSUE THREAD

**Issue by Delapro** [OpenShot/openshot-qt#5240]
**Describe the bug:**
Caption effect doesn't like decimal numbers with more than four decimal places

**Steps to reproduce the behavior:**
Create a new project
Import a picture and add it to a track
Add a caption effect to the picture
Move the timelinemarker to i.e 3 seconds
Replace the default caption text with any decimal number which has more than four decimal places, i. e. 4.56545
After typing the fifth place the text isn't shown anymore in the preview

**Expected behavior:**
The text should always be visible

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 3.1.1
- Operating System / Distro: Win 11

**Comment by Colorjet3** [comment]
Hello @Delapro.  I was able to replicate this issue using Openshot v3.1.1 in both Windows 11 and Ubuntu 22.04 lts.  Thank you so much for reporting this bug.

I also noted that it doesn't have anything to do with decimal, it just does like numeric number beyond the 4th digit.  I did this by replacing the default text with 1234 and once I typed 12345 the numbers disappeared.

I just submitted an internal bug ticket:  https://trello.com/c/RfqvP2hO/42-caption-effect-does-not-display-numbers-once-you-are-passed-the-4th-digit

At this time I wasn't able to find a work around for this.  I am going to ping the developer and the IT technical support to see if they have a workaround.

**Comment by jonoomph** [comment]
Thanks for the bug report @Delapro, much appreciated! I found the issue. Our regex which parses the caption text, had a look-ahead pattern for essentially 5 numeric digits (i.e. assuming that was the start of the next time code). I am going to improve this to look for this pattern instead:  ##:##, which should resolve this issue.

**Comment by Colorjet3** [comment]
Hello @Delapro.  This issue was fixed by @jonoomph in the latest DEV Daily Build.  Please do this:
1. go to openshot.org/download/#daily.
2. Download Daily Build #11447.
3. Install it and test the Caption again and confirm that all is good.

**Comment by Delapro** [comment]
Hello @Colorjet3 I verified with version OpenShot-v3.1.1-daily-11453-e91bd827-dce55693-x86_64.exe, caption effect with decimal numbers works fine now. Thanks!

**Comment by maf1024** [comment]
Possible workaround for people googling:
Add zero-width spaces within your strings of digits to prevent them from matching the pattern.

**Comment by Colorjet3** [comment]
Hello @maf1024.  Why suggest the workaround when the daily build fixes the issue?

**Comment by maf1024** [comment]
My mother always taught me to prefer stable releases 🙂
