### ISSUE TITLE
Openshot aborting export at 75% with "bad alloc", display driver crashes subsequently it seems.

### ISSUE THREAD

**Issue by Haui1112** [OpenShot/openshot-qt#5245]
**Describe the bug:**
Similar to a similar but closed issue, I get crashes/interrupted exports for my latest video, both on 1440p and on 1080p.

**Steps to reproduce the behavior:**
1. Open Project
2. Press Export
3. At 79% it displays: "Leider ist während des Videoexports ein Fehler aufgetreten:
std::bad_alloc"

**Expected behavior:**
From my experience with openshot, this has never happened before. To be fair, I did start to cut my videos more often which seems to slow the program down significantly.

**System Details:**
- OpenShot Version [3.1.0]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [Windows 10, Version 10.0.19045 Build 19045
]

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

**Exception / Stacktrace:**
"Leider ist während des Videoexports ein Fehler aufgetreten:
std::bad_alloc"

[openshot-qt.zip](https://github.com/OpenShot/openshot-qt/files/11548712/openshot-qt.zip)

**Comment by Colorjet3** [comment]
Hello @Haui1112.  I see that you are running v3.1.0.  v3.1.1 has been released with a memory fix that hopefully will take care of this issue you are experiencing.

Please do this:
1.  Close Openshot if running.
2.  Go to Openshot.org and click on DOWNLOAD v3.1.1.
3.  Download and install v3.1.1 and give your project Export a try and let us know if this fixed your issue.

**Comment by Haui1112** [comment]
Hi! Thanks, I will try this immediately. Will update you then.Am 24.05.2023 um 00:39 schrieb Colorjet3 ***@***.***>:﻿
Hello @Haui1112.  I see that you are running v3.1.0.  v3.1.1 has been released with a memory fix that hopefully will take care of this issue you are experiencing.
Please do this:

Close Openshot if running.
Go to Openshot.org and click on DOWNLOAD v3.1.1.
Download and install v3.1.1 and give your project Export a try and let us know if this fixed your issue.

**Comment by Haui1112** [comment]
Hello there! I have tried it and you are right. The video exports successfully! Thank you very much.

**Comment by Colorjet3** [comment]
That is great @Haui1112 and thank you for update.  Best of luck with your projects.

**Comment by Haui1112** [comment]
Thanks a lot! Have a good one.
