### ISSUE TITLE
Openshot 2.2 on Fedora25 crashes often

### ISSUE THREAD

**Issue by huubvanniekerk** [OpenShot/openshot-qt#525]
**System Details:** Core-i7, 16 GB RAM
* Operating System / Distro: Fedora 25 x64
* OpenShot Version: 2.2
* _Please attach log files if crash_
Where can I find it?
**Issue Description and steps to reproduce:** 
Editing a video and exporting to web/Youtube HD 720. During exporting the crash occurs at random. Also, often no audio in resulting mp4. Had NO problem in Openshot 1.2 on Mint 17.2. Alas, v. 1.2 is no longer to be found anywhere...

**Comment by croco3008** [comment]
Are you using latest version from github? Official 2.2 version contains a big audio bug. It is fixed in development version.

**Comment by DylanC** [comment]
@huubvanniekerk - Can you confirm this issue in v2.3.4 or a daily build please?

**Comment by huubvanniekerk** [comment]
@DylanC - I can confirm this issue in v.2.3.4.

**Comment by DylanC** [comment]
@huubvanniekerk - Thanks!

**Comment by huubvanniekerk** [comment]
@DylanC Btw, I assume you're talking about the .svg import issue I filed reccently.

**Comment by DylanC** [comment]
@huubvanniekerk  - No just the crashing on Fedora 25 issue.

**Comment by huubvanniekerk** [comment]
@DylanC Ok. Have you been able to successfully import an .svg file I sent you into a project such that its text is fully visible? BTW, I'm about to upgrade to to Fedora 26.

**Comment by DylanC** [comment]
@huubvanniekerk - I will test that SVG issue soon. I will respond on the other ticket.

**Comment by huubvanniekerk** [comment]
@DylanC Thank you.

**Comment by DylanC** [comment]
@huubvanniekerk - I didn't experience this crash using daily build:
OpenShot-v2.4.0-1-g8a71c3d-55-646-x86_64

Export with same settings was successful.
