### ISSUE TITLE
Windows GPU acceleration

### ISSUE THREAD

**Issue by MrRalphMan** [OpenShot/openshot-qt#5251]
Please enable GPU acceleration for deciding and encoding within the app.

Have this selectable if you have more then one GPU, for example integrated graphics.

Even better allows the use of multiple cards.

**Comment by deFrisselle** [comment]
Yes, this would be of great benefit    Render times less than 30 some hours would be very welcome 
I hope this is on the Roadmap

**Comment by Colorjet3** [comment]
Hardware acceleration in general is currently lacking in OpenShot on most platforms.  Additionally, AMD is not supported at this time.  This is a highly requested feature to be enabled and is in the queue.  Unfortunately no ETA at this time.

Please see https://trello.com/c/RrrfpdP9/49-initial-windows-hardware-acceleration-encoding-decoding
