### ISSUE TITLE
How can I select a section of the track I want, rather than razor cutting all the tracks I don't? - Openshot

### ISSUE THREAD

**Issue by Steveiiie** [OpenShot/openshot-qt#5257]
Hi All!

Is there a way to select a section of the video (track) that I want to use, rather than having to razor cut all the tracks I don't?

Some context to my question:

I filmed a drummer performing a song from 8 different angles. (Yes EIGHT)!
Each video has been edited to start at the exact same time so they all now line up with the music. 

Imported into Openshot, I now have 8 'tracks' (videos) I want to edit together 
e.g - a few seconds of track 1 then a few seconds of track 5 then a few seconds of track 7 etc etc.

Please note - I do not have the option of moving things left and right, they all have to remain locked in place so they stay synced in time with the music.

To cut out every section that I don't want is not only time consuming, but makes editing really difficult. I want to decide which 'track' to use for each section based on how the shot looks for that particular moment in the video.

There must be a way to just select the section that I want that automatically disregards the other tracks.... right???

Please help if you have any tips for me. I've only just downloaded the software today.

Thanks in advance and have a great day!

**System Details:**
Openshot version 3.1.1
libopenshot 0.3.2 (whatever that means...)

Mac OS Monterey 12.5.1

**Comment by Colorjet3** [comment]
Unfortunately that feature does not exist in OpenShot.  However, what you can do is lock the other tracks that you don't want the "Cut" to apply to.  You just right click on the Track label, for example, Track 5 and then you select Lock.  You have to do this individually for each track (no select options and then lock multiple tracks at once).  Perform your cut then remember to Unlock those tracks that you need to work with again.
