### ISSUE TITLE
Freezing at 18 seconds preview

### ISSUE THREAD

**Issue by Modsojoy** [OpenShot/openshot-qt#526]
Im on 2.2.0 and every time i try to preview a clip recorded in shadowplay it freezes 18 seconds in, record anything in Nvidia shadowplay and it will freeze.

https://vid.me/FVzZ

Video of the bug, preview frames dont change or anything.
Windows 10 64Bit
GTX1050Ti
Pentium G4560

**Comment by ankitpati** [comment]
Can you please attach the recorded clip, so we can try to reproduce the bug?

**Comment by Modsojoy** [comment]
It happens with anything recorded by Nvidia Shadowplay.

**Comment by Modsojoy** [comment]
So anything encoded with NVENC

**Comment by jonoomph** [comment]
Please visit www.openshot.org/download, and grab the latest version, 2.3.1. This should now be fixed. If not, please re-open this issue and attach an example source video that always freezes for you. Thanks!
