### ISSUE TITLE
How do I delete sections of a video?

### ISSUE THREAD

**Issue by old-dog-137** [OpenShot/openshot-qt#5268]
**Question:**
I just want to delete some sections of a video. I got as far as loading it to the timeline and opening it in the video window.

**Comment by sc0nway** [comment]
Here's a video Jonathan created to help customers learn to use OpenShot. The following topics are covered in this video: 
 - Trimming clips by dragging the edges
 - Splitting clips in the Split Clip dialog
 - Slice All (cut all clips along the play-head red line)
 - Slice (cut a specific clip along the play-head red line)
 - Clip properties (to adjust start, end, and position)
 - Razor tool (cut anywhere you want but with less precision)

https://youtu.be/BQS2tmgD_Rk
