### ISSUE TITLE
proposition: GPU rendering acceleration

### ISSUE THREAD

**Issue by carlosnewmusic** [OpenShot/openshot-qt#527]
System Details:MSI GS726QF
Operating System / Distro: Devian 9/W10 v1607 compilacion 14393.693
OpenShot Version: 2.2.0_dev

**Comment by jebeld17** [comment]
Yes, please!!

**Comment by ocoles** [comment]
Seriously. How any modern rendering software manages to avoid GPU acceleration in this era is beyond me.

**Comment by ferdnyc** [comment]
Closing as dup of #2812, which has a WIP implementation in #2825.
