### ISSUE TITLE
Unable to use certain fonts

### ISSUE THREAD

**Issue by avoura** [OpenShot/openshot-qt#5270]
Bug: when selecting certain fonts for text, some fonts do not appear but the app reverts the text to Bitstream Vera Sans instead. Some fonts work okay, others not. This is in version 3.1.1, the latest daily build AppImage file downloaded just now from the OpenShot website.

**Steps to reproduce the behavior:**
1. Create a Title entry, and Edit Title.
2. Select change font.
3. Choose a font, I chose Bahnschrift. Select size and style. Click Save.
4. Text is displayed in Bitstream Vera Sans, not in Bahnschrift. Click Title again and Edit Title, and font has reverted to Bitstream Vera Sans.

Also note that selected Use Advanced Editor should open the text as an SVG file in Inkscape, which is installed, and the path to it specified in the Preferences, but it does not open Inkscape, and I have no idea where the SVG files are being saved.

**Expected behavior:**
Font chosen should be the one used and displayed.

**System Details:**
OpenShot 3.1.1
Ubuntu Studio 22.04.2 LTS
Kernel Linux 5.15.0-41-lowlatency x86_64

Logfiles attached.

[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/11837679/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/11837680/openshot-qt.log)

**Describe the bug:**

**Steps to reproduce the behavior:**
6. Click on '....'
7. Scroll down to '....'
8. See error

**Expected behavior:**

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
Hello @avoura.  This is a known bug and is in the queue to be fixed.  No ETA at this time.
