### ISSUE TITLE
Add SVT-AV1 codec support

### ISSUE THREAD

**Issue by shockagent** [OpenShot/openshot-qt#5272]
Please add support to SVT AV1 codec in Windows version of OpenShot.

I have tried to create a preset, but it seems there is no SVT AV1 library installed with OpenShot, and it is not displayed in dropdown list.
There is even a format_mp4_librav1e.xml inside C:\Program Files\OpenShot Video Editor\presets, but it is no displayed in dropdown list
![openshot](https://github.com/OpenShot/openshot-qt/assets/74264936/2c1e6168-d90c-4ef5-b525-84e96b33060b)

SVT-AV1 encoding is very fast and efficient with ffmpeg, I'd like to use it also with OpenShot.

**Comment by sc0nway** [comment]
OpenShot v3.1.1 on Linux distributions with FFmpeg 5.1 and higher support the SVT-AV1 codec. Our [PPA](https://www.openshot.org/ppa/) and [source code](https://github.com/OpenShot/openshot-qt/wiki/Become-a-Developer) installations have full support, while the AppImage does not support the codec.
![Screenshot_20230627_011801](https://github.com/OpenShot/openshot-qt/assets/65924242/f9e4a3d5-f7ef-4e6e-9558-8474fa4ab82b)

For Windows systems, you can download and install virtualization software (e.g., [VMware Workstation Player](https://www.vmware.com/products/workstation-player.html) or [Oracle VirtualBox](https://www.virtualbox.org/) to establish a Linux distribution (e.g., [Ubuntu](https://ubuntu.com/), [Debian](https://www.debian.org/), [Fedora](https://fedoraproject.org/) in a hosted virtual environment. Most Linux distributions and the two hypervisor software examples listed are free.

According to Wikipedia, the [AV1 rav1e](https://en.wikipedia.org/wiki/AV1#Software_implementations) encoder "rav1e takes the opposite developmental approach to aomenc: start out as the simplest (therefore fastest) conforming encoder, and then improve efficiency over time while remaining fast." Our source code and PPA versions of OpenShot in Linux also support AV1 rav1e.

**Comment by sc0nway** [comment]
Since the customer has not responded for over two weeks, I designate this issue as Closed.

**Comment by wilx** [comment]
Why does the AppImage variant not have AV1 support? Can it be added?

**Comment by Colorjet3** [comment]
@jonoomph please see this request?
