### ISSUE TITLE
Using "Preview" on a clip is just black, and audio is choppy

### ISSUE THREAD

**Issue by desertdwell** [OpenShot/openshot-qt#5273]
**Describe the bug**
Using "Preview" on a clip is just black, and audio is choppy

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 3.1.1
- libopenshot Version:  0.3.2
- Platform: Windows-10-10.0.19041
- Processor: AMD64 Family 23 Model 1 Stepping 1, AuthenticAMD
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.1.1-daily-11529-95eccafc-08c2cdd1-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/hrh9jxdxp9ngn6h8i7dvvvjo9v36wc06/openshot-qt.zip) (0 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/hrh9jxdxp9ngn6h8i7dvvvjo9v36wc06/libopenshot.zip) (123 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
Hello @desertdwell.  The "Preview File" option has some known bugs.  Please review the following and let us know if this fits your experience:

1.  https://trello.com/c/aQGIdwoi/102-video-preview-window-turns-black
2. https://trello.com/c/qTWNLUV8/37-preview-file-plays-certain-file-types-with-out-of-sync-audio-timeline-works-fine

If you drag the file onto a track, does it play ok?

**Comment by Colorjet3** [comment]
No response from user.
