### ISSUE TITLE
Captions do not appear on images when I am using multiple tracks. Had to export and start over with ...

### ISSUE THREAD

**Issue by tlong-TAPE** [OpenShot/openshot-qt#5274]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 3.1.1
- libopenshot Version:  0.3.2
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.1.1-daily-11529-95eccafc-08c2cdd1-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/hy733ssiobp6r1tgtvoj8rxvabx3p2nk/openshot-qt.zip) (3239 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/hy733ssiobp6r1tgtvoj8rxvabx3p2nk/libopenshot.zip) (3 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
Please provide step-by-step instructions so we can try and replicate exactly what you are doing in an attempt to identify the issue and a resolution.

**Comment by Colorjet3** [comment]
Hello @tlong-TAPE.  Any update on the requested information?

**Comment by Colorjet3** [comment]
No response from user.
