### ISSUE TITLE
Split Clip doesn't cut video

### ISSUE THREAD

**Issue by NikitaKhoroshun** [OpenShot/openshot-qt#5275]
**Describe the bug**
When I try to cut a video from the Project Files by using Split Clip (Ctrl+X as shortcut) it just copies original video and nothing more.

**Steps to reproduce the behavior:**
1. Create new project, add any video clip in Project Files, click right mouse button or pres Ctrl+X;
2. New window appears, click on play and let video play a bit, then click "Start button" to choose the first frame for new clip, then let video play a bit and then click "End" button, then finally click Create;
3. Close the window, scroll down to where you can find new clip.
4. Choose Preview of new clip which reveals it is the same video as original without any cutting. 

**Expected behavior**
The new clip should be shorter, just between frames "Start" and "End" you've chosen in Split Clip window.

**System Details**
- OpenShot Version: 3.1.1
- libopenshot Version:  0.3.2
- Platform: Linux-6.2.6-76060206-generic-x86_64-with-glibc2.4
- Processor: x86_64
- Machine: x86_64
- Python version: 3.8.10
- Qt5 version: 5.12.8
- PyQt5 version: 5.14.1
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: en_US.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.1.1-daily-11529-95eccafc-08c2cdd1-x86_64.AppImage

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/sqxhikm9kdxnc1hz64xbdvytnpchrvmu/openshot-qt.zip) (30 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Comment by Colorjet3** [comment]
Hello @NikitaKhoroshun.  This is a known bug and is documented here:  https://trello.com/c/v8K0NHiG/34-split-clip-this-really-should-say-split-file-is-not-working-accurately.

Please note that even though previewing the split clip plays the entire video, when you drag it onto a Track it correctly plays the selected Start and End frames.

**Comment by NikitaKhoroshun** [comment]
> 
Hi @Colorjet3 
wow, thanks!
It's mean all time i spent in cutting clips was not for nothing!

**Comment by Colorjet3** [comment]
You are welcome @NikitaKhoroshun and good luck with your project(s).
