### ISSUE TITLE
Blender does not complete the animated title

### ISSUE THREAD

**Issue by AlanReviews** [OpenShot/openshot-qt#5278]
**Describe the bug:**
I tried to create an animated title with the Appimage on Openshot Video Editor. The animated title gets created but the animation is never complete. I think the file is corrupted. I don't know if the program got stuck. Openshot or Blender uses 100% of the CPU to complete the animated title. I find the process to create the animated title to be slow. Is there a way to speed it up?

**Steps to reproduce the behavior:**
1. Go to Titles then Animated Titles or press Ctrl + B.
2. Select the blur animated title
3. Click on the render button
4. When the animated title is completed, the loading bar is full, and the title is saved, press the close or cancel buttons
5. Drag the animated title file to the timeline

**Expected behavior:**
The animated title is complete and not corrupted. I don't expect 100% of the CPU to be used. 

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 3.1.1
- Operating System / Distro: Pop!_OS 22.04
- Blender version: 3.0.1 from snap
- Computer specs: Intel Core i7-9700K CPU, a GTX 1660 Ti, and 32 GB of RAM.

**Log Files:**
18:41:17 INFO logger_libopenshot: Connecting to libopenshot with debug port: 5556
18:41:17 INFO ui_util: Initializing UI for MainWindow
18:41:18 INFO thumbnail: Starting thumbnail server listening on ('127.0.0.1', 44107)
18:41:18 INFO webengine: WebEngine backend initializing
18:41:18 INFO transition_model: updating transitions model.
18:41:18 INFO version: Found current version: {'openshot_version': '3.1.1', 'trans_rate_stable': 0.01, 'trans_rate_unstable': 0.001, 'error_rate_unstable': 0.05, 'error_rate_stable': 0.25}
18:41:18 INFO effects_model: updating effects model.
18:41:18 INFO emoji_model: updating emoji model.
18:41:19 INFO sentry: Sentry initialized for 'production': 0.25 sample rate, 0.01 transaction rate
18:41:19 INFO main_window: InitCacheSettings
18:41:19 INFO main_window: cache-mode: CacheMemory
18:41:19 INFO main_window: cache-limit-mb: 250
18:41:19 INFO main_window: cache-ahead-percent: 0.7
18:41:19 INFO main_window: cache-preroll-min-frames: 24
18:41:19 INFO main_window: cache-preroll-max-frames: 48
18:41:19 INFO main_window: cache-max-frames: 600
18:41:19 INFO main_window: Creating CacheMemory object with 262144000 byte limit
18:41:19 INFO preview_thread: QThread Start Method Invoked
18:41:19 INFO main_window: Cleared temporary files: /home/alan/.openshot_qt/thumbnail
18:41:19 INFO main_window: Cleared temporary files: /home/alan/.openshot_qt/blender
18:41:19 INFO main_window: Cleared temporary files: /home/alan/.openshot_qt/title
18:41:19 INFO main_window: updateStatusChanged
18:41:19 INFO main_window: recover_backup
18:41:19 INFO project_data: Setting profile to FHD 1080p 60 fps
18:41:19 INFO project_data: Apply default audio playback settings: 44100, 2 channels
18:41:19 INFO video_widget: Load: Set video widget display aspect ratio to: 1.7777777910232544
18:41:19 INFO video_widget: Set video widget pixel aspect ratio to: 1.0
18:41:19 INFO main_window: updateStatusChanged
18:41:19 INFO timeline: Adjusting max size of preview image: PyQt5.QtCore.QSize(188, 106)
18:41:19 INFO webengine: Registering WebChannel connection with WebEngine
18:41:19 INFO timeline: Adjusting max size of preview image: PyQt5.QtCore.QSize(276, 156)
18:41:20 INFO webview: Qt Ready
18:41:20 INFO webview: Angular Ready
18:41:35 INFO ui_util: Initializing UI for Dialog
18:41:35 INFO blender_model: updating effects model.
18:41:35 INFO blender_listview: Animation param fontname set to Bfont
18:41:35 INFO blender_listview: Animation param spacemode set to CENTER
18:41:35 INFO blender_listview: Animation param length_multiplier set to 2
18:41:35 INFO blender_listview: Animation param length_multiplier set to 1
18:41:36 INFO blender_listview: Previewing frame 210
18:41:36 INFO blender_listview: Injecting GPU enable code from /tmp/.mount_OpenSh4kHyyG/usr/bin/blender/scripts/gpu_enable.py.in
18:41:37 INFO blender_listview: Found Blender version 3.0.1
18:41:38 INFO blender_listview: Blender process exited, 1 frames saved.
18:41:40 INFO blender_listview: Injecting GPU enable code from /tmp/.mount_OpenSh4kHyyG/usr/bin/blender/scripts/gpu_enable.py.in
18:41:40 INFO blender_listview: Found Blender version 3.0.1
18:42:07 INFO blender_listview: Blender process exited, 2 frames saved.
18:42:07 INFO main_window: animated title add confirmed
18:42:07 INFO blender_listview: RENDER FINISHED! Adding to project files: TitleFileName%04d.png
18:42:07 INFO files_model: Imported '/home/alan/.openshot_qt/blender/N9M0RST4J8/TitleFileName%04d.png' as image sequence with '60/1' FPS and '0.033333332588275276' duration
18:42:07 INFO main_window: updateStatusChanged
18:42:08 INFO main_window: updateStatusChanged
18:42:09 INFO webview: Dropping item on timeline - item_id: 2ORSHR13NR, item_type: clip
18:42:09 INFO main_window: updateStatusChanged
18:42:10 INFO main_window: updateStatusChanged
18:42:11 INFO webview: Dropping item on timeline - item_id: U95AHXIVON, item_type: clip
18:42:11 INFO main_window: updateStatusChanged
18:42:15 INFO timeline: Adjusting max size of preview image: PyQt5.QtCore.QSize(704, 396)
18:42:16 INFO timeline: Adjusting max size of preview image: PyQt5.QtCore.QSize(644, 364)
18:42:16 INFO timeline: Adjusting max size of preview image: PyQt5.QtCore.QSize(568, 320)
18:42:16 INFO timeline: Adjusting max size of preview image: PyQt5.QtCore.QSize(620, 348)
18:42:18 INFO main_window: updateStatusChanged
18:42:22 INFO main_window: updateStatusChanged
18:42:55 INFO ui_util: Initializing UI for Dialog
18:42:55 WARNING about: Found current release: {'date': '2023/04/21', 'notes': 'https://www.openshot.org/blog/2023/04/20/new_openshot_release_311/', 'version': '3.1.1', 'sha': '5416a16b93923d7488d62ae23073e57c8c961e55'}
18:42:55 WARNING about: Official release detected with SHA (5416a16b93923d7488d62ae23073e57c8c961e55) for v3.1.1

**Screenshots:** (Optional)
![openshot video editor animated title freezing](https://github.com/OpenShot/openshot-qt/assets/54216387/0a65626c-feaa-4cc8-953e-46170e5b71f2)

**Comment by AlanReviews** [comment]
Could Openshot video editor be stalling? Should I upgrade my hardware?

**Comment by Colorjet3** [comment]
Hello @AlanReviews.  Looking at the image you shared, you will notice the Frame:  is 6/420.  This process is very slow and not all of it is because of your hardware.  You just need to be patient and wait till all the frames (420) are processed.  Sure, you can go ahead and upgrade your hardware (not everyone can do this).  However, OpenShot still has performance issues and the fact that Blender is involved that could be an issue as well.

Hardware Acceleration might help a bit.  OpenShot still has issues with hardware acceleration, however, Blender does take advantage of Hardware Acceleration.  When you have the time, start Blender by itself and configure it so it takes advantage of your hardware.  That might help with speeding up Animated Title creation process.

1. Start Blender.
2. Click on Edit | Preferences
3. Click on System
4. Expand the "Cycle Render Devices" and click on CUDA and Optix and enable the devices that Blender supports.
5. Exit Blender and then try creating the Blur Animated Title and see if the performance is a bit better.

You may also try upgrading to the latest version of Blender as well (3.6).

**Comment by Colorjet3** [comment]
No response from user.

**Comment by AlanReviews** [comment]
Yes these steps work. Thank you so much!

**Comment by Colorjet3** [comment]
Awesome and thank you for the FYI!
