### ISSUE TITLE
glitch preview(video view blurs out completely)

### ISSUE THREAD

**Issue by eshaprasadts** [OpenShot/openshot-qt#5279]
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/11997500/libopenshot.log)
[libopenshot-audio.log](https://github.com/OpenShot/openshot-qt/files/11997501/libopenshot-audio.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/11997502/openshot-qt.log)
![openshot_vid_previewGlitch](https://github.com/OpenShot/openshot-qt/assets/29681595/607c04a8-9105-4988-9baa-c8d805140a0d)
I tried installing latest OpenShot-v3.1.1-x86_64. Not sure where this preview settings rae messed up. Audio also glitch , repeats/echos and goes out of sync compared to video. FYI:I have windows laptop(64gig ram)AMD 500 +amd radeon

**Comment by Colorjet3** [comment]
Please give this a try:
1.  Close OpenShot if running.
2.  Make a backup of c:\users\username\\.openshot_qt folder.
3.  Delete c:\users\username\\.openshot_qt folder.
4.  Start OpenShot, open your project, and see if the preview is better and the audio plays properly.

**Comment by eshaprasadts** [comment]
Thank you. This resolved the glitch.
Thanks & Regards,

*Esha Prasad*(+1)-405-761-6939

**Comment by Colorjet3** [comment]
That is great @eshaprasadts.  Good luck with your project(s).
