### ISSUE TITLE
Windows 7 x64 launch crash

### ISSUE THREAD

**Issue by urkokul** [OpenShot/openshot-qt#528]
![bug_windows7x64_20170310](https://cloud.githubusercontent.com/assets/16238066/23818120/0e9de3ee-0601-11e7-9a5e-7d248ea3d0ec.png)
**System Details:**
* Operating System / Distro: Windows 7 x64
* OpenShot Version: 2.2
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

**Comment by jebeld17** [comment]
Have you tried clearing your user data? Open a command prompt as admin and type
rmdir c:\users\<username>\.openshot_qt /s

**Comment by DylanC** [comment]
@urkokul - Does this issue still exist in a newer version?
