### ISSUE TITLE
OpenShot -- No Audio in Preview

### ISSUE THREAD

**Issue by wallendorf** [OpenShot/openshot-qt#5280]
I see that OpenShot has a bunch of reports of no audio in Preview. 

I'm currently running OpenShot 3.1.1 on Ubuntu Linux 23.04.   I've looked through all the previous iterations of this problem and the problem persists.

I have only one choice for Playback Audio Device:  Default -- not a lot of room for change.

**Comment by Colorjet3** [comment]
Most of the audio issues with OpenShot has been in Windows environment.  Give this a try:

1.  Close OpenShot if running.
2.  Make backup of /home/username/.openshot_qt folder.
3.  Delete /home/username/.openshot_qt folder.
4.  Start OpenShot and give it a try.
5.  If the issue persists, then try a different video file to see if this is a consistent issue.
6.  Verify that your source file plays ok (with audio) outside of OpenShot.

If you are still having the issue then tell us what type of a file you are working with (.mov? .mp4? etc?)

**Comment by tshelver** [comment]
Having the same issue on Ubuntu 20.04.  
Have tried suggestions 1 through 6 above, and still no sound on the .mp4 files I tested.  
They all play through VLC.  
Had a much older version of openshot before (2.x?) that worked fine.

**Comment by Colorjet3** [comment]
Hello @tshelver.  Sorry to see that you are having this issue as well.  Please try converting your .mp4 file back to .mp4 again (obviously with a different name) using something like VLC, HandBrake, or Shutter Encoder.  Import this new converted file into OpenShot and see if audio works now.

If this works, it means there is something about the source file that OpenShot is unable to process.  I've seen where some more advanced video editors handle the conversion natively.

This will also provide the lead developer with some ideas on how to handle something like this in the future.

**Update:** I am also curios if the audio works if you Export (your original .mp4).  Obviously, this is not a solution but just wanting to know if it is just a preview issue.

**Comment by tshelver** [comment]
I tried a few other mp4 files, all play fine with sound in VLC.  They don't play in OpenShot 3.1.1

I then converted one of them from mp4 to mp4 using VLC. Sound in the new file plays fine in VLC, but not in OpenShot.

I then made a clip (in Openshot) of a video (no sound still) and exported it.  The new video clip plays fine in VLC with sound, but still no sound in Openshot...

**Comment by Colorjet3** [comment]
Thank you @tshelver for all your efforts and the information.  Let's try one more thing and then we will need to get the lead developer get involved in debugging this issue.

1.  Go to openshot.org/download/#daily and download the latest DEV daily AppImage.
2.  Make this executable and launch OpenShot via the AppImage and see if the audio works during the preview process.
3.  If the audio works then you can perform a PPA installation of the Daily Build and give that a try as well:  https://www.openshot.org/ppa/.  Make sure you run the Daily PPA commands.  You can then launch OpenShot via the shortcut icon.

**Comment by tshelver** [comment]
The latest build (OpenShot-v3.1.1-daily-11529-95eccafc-08c2cdd1-x86_64.AppImage) works.  Will try to install the daily and see how it goes

**Comment by tshelver** [comment]
Adding the PPA and installing openshot-qt works as well.

**Comment by Colorjet3** [comment]
This is great news @tshelver.  I am going to close this ticket for now.  Feel free to reopen if there is something related to this issue otherwise you can start a new thread if you run into something new.

**Comment by alesmuc** [comment]
Same problem. I have ubuntu 23.04 and I have installed Openshot from Ubuntu Software in snap format.
I also have only one choice for Edit -> Settings -> Preview -> Playback Audio Device: Default
I haven't found the /home/username/.openshot_qt folder.   folder as suggested Colorjet3
My solution was uninstall Openshot from Ubuntu Software, go to the official openshot website, download OpenShot in Appimage format (it's already ready to be executed) and now it's working!  If you can't axecute the appimage file right click, propieties, execute as a program

**Comment by Colorjet3** [comment]
Hello @alesmuc.  You should be replacing the .../username/... with your login id.  If you still can not find it then you need to enable the ability to see hidden files in File Manager.

**Comment by alesmuc** [comment]
> Hello @alesmuc. You should be replacing the .../username/... with your login id. If you still can not find it then you need to enable the ability to see hidden files in File Manager.

Thank you Colorjet3, now I found it. It was a hidden folder. In my system it was at 
/home/.openshot_qt 
and not at 
/home/username/.openshot_qt folder

**Comment by Colorjet3** [comment]
Hello @alesmuc.  So, is everything working for you now?

**Comment by alesmuc** [comment]
> Hello @alesmuc. So, is everything working for you now?

Hi @Colorjet3 . Now it's working. After I installed the app in the appimage format it get stuck several times. I was forcing the closure of the app and starting it again. After some times the app stop to start again. It was starting for 1 second and suddenly crashing and disappearing. After I deleted  /home/.openshot_qt the app start to works again. Thank you vedy very much :)

**Comment by Colorjet3** [comment]
Hello @alesmuc.  Forcing the app to close can definitely cause issues with the ~/.openshot_qt folder.  One thing to keep in mind is the the recovery files for your projects are stored in ~/.openshot_qt/recovery folder.  Next time your app freezes and before you delete ~/.openshot_qt folder, make a backup of the ~/.openshot directory.  Save this backup.  When you start OpenShot it recreates this folder.  Now restore the ~/.openshot/recovery folder contents (from your backup to the original).

It is nice to have the ~/.openshot_qt/recovery folder contents when needed.
