### ISSUE TITLE
Speed up video exports

### ISSUE THREAD

**Issue by AlanReviews** [OpenShot/openshot-qt#5281]
**Question:**
How do I speed up the export time of a 1080p 60 FPS video?

**System Details:**
- OpenShot Version [e.g. 2.4.3]: v3.1.1 {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1] Pop!_OS 22.04

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your question. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
You can try enabling Hardware Acceleration in OpenShot (Edit | Preferences | Performance) and changing the "Hardware Decoder Mode".  However, note that this can also cause other issues.  What I recommend you do is to complete all your editing without changing this setting.  Save your project.  Now see if you can change this setting and try the Export.

Hardware Acceleration has been challenging to say the least on all platforms and there is enhancement request in the queue for a fix/improvement.  No ETA at this time!

**Comment by Colorjet3** [comment]
I have flagged this as an enhancement request and assigned it to the lead developer.
