### ISSUE TITLE
Openshot icons are pixelated

### ISSUE THREAD

**Issue by surveyor3** [OpenShot/openshot-qt#529]
* **System Details:**Full Hd 14 inch display
* Operating System / Distro: Ubuntu, with Gnome and Wayland
* OpenShot Version: 2.2, the lastest installed from the ubuntu ppa

**Issue Description and steps to reproduce:**
The app look terrible. All the icons are pixelated. The interface doesn't scale well.

**Comment by H2L29** [comment]
same here, very ugly ui, Openshot 2.3 freshly installed from ppa stable
https://www.lagout.org/file//f.php?h=3GQlNHHL&p=1

**Comment by DylanC** [comment]
@surveyor3 - Please attach a screenshot here. The above link is invalid.

**Comment by DylanC** [comment]
OpenShot v2.4 looks fine on my 14 inch FHD screen.
