### ISSUE TITLE
Surround Sound Channel Shifting

### ISSUE THREAD

**Issue by helpimdrowning** [OpenShot/openshot-qt#5295]
**Describe the bug:**

When attempting to export video from Openshot, the output file has surround sound channels shifted or missing from the source material. I have verified that the correct audio profile has been selected (5.1 surround) for both preview preferences and under the export video advanced menu. 

The audio that I was originally dealing with was a 5.1 FLAC file, which failed to render without popping and crackling. Looking online, it appears that Openshot doesnt handle FLAC files well, so I converted the files into WAV files. I verified these files play back correctly with correct channel configurations across multiple media players including VLC and Windows Media Player. They play with the correct channel configurations in both FLAC and in WAV, so the conversion to WAV doesn't seem to be the problem.

I then added the files to my project, and attempted to render the video (note: is AAC the only reliable audio codec for Openshot? When attempting to change codecs I got errors). So I left this as AAC with the default sample rate of 48000, and 5.1 channel layout selected. 

The video appeared to render without issue, however upon playback all audio seems to be coming out of the Left Front speaker. There is some action across other channels, it is significantly muted and could be the wrong channels entirely. 

Any recommendations from anyone?

**Steps to reproduce the behavior:**
1. Add WAV files with 6 channels (5.1)
2. Export in 4k uhd, 24 fps, aac, 48000, 192kb/s
3. attempt playback on surround sound device
4. listen

**Expected behavior:**

Audio to be in the correct channels

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }} 
- Openshot-v3.1.1-release-11392-7100dc7a-e47da46f (Official)
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
- Windows 10

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
Please try this:
1.  Go to openshot.org/download/#daily and download the latest DEV Daily Build #11529.
2.  Close OpenShot if running.
3.  Make a backup of c:\users\username\.openshot_qt folder.
4.  Delete c:\users\username\.openshot_qt folder.
5.  Install build number 11529.
6.  Render again and see if the issue with the audio is resolved.

**Comment by Colorjet3** [comment]
Hello @helpimdrowning Did you give my suggestion a try?

**Comment by Colorjet3** [comment]
No response from OP.
