### ISSUE TITLE
Wenn ich einen beliebigen animierten Titel auswähle, stürzt Openshot ab.

### ISSUE THREAD

**Issue by frerichR** [OpenShot/openshot-qt#5297]
**Beschreiben Sie den Fehler**
A clear and concise description of the issue

**Schritte zum Reproduzieren des Verhaltens**
1. Gehe Sie nach '...'
2. Klicken Sie auf '....'
3. Scrollen Sie hinunter nach '....'
4. Sehen Sie den Fehler

**Erwartetes Verhalten**
Eine klare und prägnante Beschreibung dessen, was Sie erwartet haben.

**Systemdetails**
- OpenShot Version: 3.1.1
- libopenshot Version:  0.3.2
- Platform: Linux-5.15.0-78-generic-x86_64-with-glibc2.35
- Processor: 
- Machine: x86_64
- Python version: 3.10.11
- Qt5 version: 5.15.9
- PyQt5 version: 5.15.1
- Qt Detected Languages: ['de-DE', 'de', 'de-Latn-DE']
- LANG Environment Variable: de_DE.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Not able to verify issue still exists in daily build

**Logdateien**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/mdj94k1yhyodrixriefp7ph53ve9jrtq/openshot-qt.zip) (15 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/mdj94k1yhyodrixriefp7ph53ve9jrtq/libopenshot.zip) (4 KB)

**Ausnahme / Stapelverfolgung**
```No stacktrace found in log files```

**Bildschirmfotos** (Optional)
Wenn möglich, fügen Sie Screenshots zur unterstützenden Erklärung Ihres Problems hinzu. Sie können Screenshots einfügen,
indem Sie diese kopieren und auf Github einfügen oder durch Drag and Drop zur GitHub-Seite hinzufügen. Alle Bilder sind öffentlich zugänglich, posten Sie deshalb keine Screenshots die persönliche Informationen enthalten.

**Comment by frerichR** [comment]
gelöst

**Comment by Colorjet3** [comment]
Was war die Lösung? Es wird anderen helfen, falls sie auf das gleiche Problem stoßen.

**Comment by frerichR** [comment]
O

**Comment by frerichR** [comment]
Openshot hat nicht auf Blender, daß über die Anwendungsverwaltung installiert wurde, zugegriffen. Wenn ich dann einen animierten Titel erstellen will, stürzt Openshot ab. Ich habe Blender als zip herruntergeladen, in ein Verzeichnis entpackt und in Openshot den Pfad eingestellt. Dann geht es. Besser wäre es natürlich, wenn ich das zuvor installierte Blender verwenden könnte.
Auf jeden Fall sollte sollte Openshot nicht abstürzen.

**Comment by Colorjet3** [comment]
Danke für diese Information. Ich bin ein Linux-Neuling. Der Blender, den Sie über den Anwendungsmanager installiert haben, ist wahrscheinlich eine ältere Version. Wenn Sie eine Möglichkeit finden, auf die neueste Blender-Version zu aktualisieren, würde dies das Problem höchstwahrscheinlich beheben.

Vielleicht möchten Sie dies überprüfen: https://docs.blender.org/manual/en/latest/getting_started/installing/linux.html

Nochmals vielen Dank für Ihr Feedback und ich freue mich, dass Sie eine Problemumgehung gefunden haben.

**Comment by frerichR** [comment]
Die Blender-Version scheint nicht das Problem. Openshot akzeptiert die installierte Version nicht. Das scheint ein Problem zwischen Linux und Openshot zu sein. Ich habe, bis auf den Absturz mit Inkscape das gleiche Problem.

**Comment by Colorjet3** [comment]
Bitte geben Sie die Version von Inkscape und Blender an, die über den Anwendungsmanager installiert wird. Dies wird für den leitenden Entwickler hilfreich sein.

Vielen Dank für Ihre Zeit und Bereitschaft, Informationen zur Verbesserung von OpenShot weiterzugeben.

**Comment by frerichR** [comment]
Blender installiert: 3.0.1, Download: 3.6.1
Inkscape installiert: 1.1.2
Ich denke aber es liegt nicht an den Versonen. Wenn ich den Pfad auf die installierte Version lege bekomme ich den Hinweis, ich soll Blender/Inkscape installieren. Wenn für Blender kein Pfad eingetragen ist, stürzt Openshot ab.
