### ISSUE TITLE
Selecting specific time with blue drop cursor

### ISSUE THREAD

**Issue by robertobriccola** [OpenShot/openshot-qt#5299]
By moving the blue drop cursor with the arrow keys to position itself on a specific time with 1/100s precision, the cursor moves to in the range hh.mm.ss.01 up to hh.mm.ss.30 then passes to next or previous second, all times from 0.31 to 1.00 cannot be selected

**Comment by Colorjet3** [comment]
Hello @robertobriccola.  This was very confusing to me at first until I understood the Frames per second.  When you start OpenShot the default profile is HD 720p 30 fps.  This means 30 frames per second.  So, this is how it works:

1.  With the playhead (the red line with the Blue handle), when you start a new projects, is set at 00:00:00,01 (note the comma between the last 00 & 01.  In your description you indicated hh.mm.ss.01 (it is not ss.01 but rather ss,01).
2. The ,01 means the the playhead is positioned at time 0 (00:00:00) on the first frame (,01)
3. When you move the playead using the cursor you are moving it a frame at a time.
4. When you reach 00:00:00,30 your are at 1 second marker at the 30th frame (based on the default profile of 30 fps).
5. The next right arrow click take you to the 31st frame or rather 00:00:01,01.
6. Keep pressing the right arrow key and once you reach 00:00:01,30 and one more press and you are at 00:00:02,01.

Change your default profile to HD 720p 25 fps.  Repeat the steps above and note that once your reach the 25the frame you jump from 00:00:00,25 to 00:00:01,25.

I hope this clarifies things for you.

**Comment by robertobriccola** [comment]
Thanks, now I understand.
The point is that I was trying to find a corrispondent value from the time properties of the pictures ex: Start (that I suppose is expressed in 1/100s because the range goes from 0,00 to 0,99 - there are no Unit Measure) and the position on the timeline (blue cursor).
Now I understand that there is no a direc correspondence, I need to make calculation between the time and the frame,
ex: with 30fps at 0,8s I'm at the 24th frame

**Comment by Colorjet3** [comment]
You are welcome @robertobriccola.  There is some internal discussion regarding how to improve the timeline for these types of situations.  I am going to flag this as an enhancement request for the lead developer to review.
