### ISSUE TITLE
No properties screen, version 2.2.0

### ISSUE THREAD

**Issue by pjisonline** [OpenShot/openshot-qt#530]
**System Details:** Asus n750jv laptop with SSD drive.
* Operating System / Distro: Windows 10, latest. 
* OpenShot Version: Latest (2.2.0)
* _Please attach log files if crash_

**Issue Description and steps to reproduce: I start OpenShot, add a movie file, drag is to the time line (to insert). I right click on the movie file and click "Properties" and nothing happens. I can continue, but no properties windows comes.

**Comment by pjisonline** [comment]
Never mind, I give up with this software. It's one big bug. Whatever I do, in a couple of seconds it hangs. Have to close it with the task manager.

**Comment by TheSlackOne** [comment]
Same bug as pjisonline reported but on Arch Linux:
Linux darkBit 4.10.3-1-ARCH #1 SMP PREEMPT Wed Mar 15 09:17:17 CET 2017 x86_64 GNU/Linux

**Comment by DylanC** [comment]
@pjisonline - Thanks for you feedback. I will test this later today.

**Comment by DylanC** [comment]
The properties screen does show on the left as a docked item currently. It does not appear as a window.
![properties](https://user-images.githubusercontent.com/4488048/30525262-33aa5240-9bfb-11e7-9222-4b98a868a246.png)
