### ISSUE TITLE
Openshot fails to start on Fedora38 with glibc issue - WORKAROUND

### ISSUE THREAD

**Issue by Bert-H** [OpenShot/openshot-qt#5300]
Note that this problem was first reported with issue #5182.

### PROBLEM ###
Openshot fails to start on Fedora38 with error:

./OpenShot-v3.1.1-daily-11556-95eccafc-08c2cdd1-x86_64.AppImage
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/cx_Freeze/initscripts/__startup__.py", line 40, in run
  File "/usr/local/lib/python3.8/dist-packages/cx_Freeze/initscripts/Console.py", line 37, in run
  File "openshot_qt/launch.py", line 55, in <module>
    from PyQt5.QtWidgets import QApplication
ImportError: /tmp/.mount_OpenShmAfqet/usr/bin/libm.so.6: version `GLIBC_2.35' not found (required by /lib64/libharfbuzz.so.0)

### WORKAROUND ###
Firstly, "libharfbuzz" is also used by other applications such as LibreOffice.
LibreOffice works fine so there is some difference between the Openshot image and LibreOffice.
As can be seen in the error message, the file in the Openshot appimage causing the issue is "/$PATH/usr/bin/libm.so.6".
On Fedora itself, this file is located in "/lib64/". This file is more recent than the one in the Openshot appimage.
To look at the files in the Openshot appimage run:
"./OpenShot-v3.1.1-daily-11556-95eccafc-08c2cdd1-x86_64.AppImage --appimage-extract".
This will extract the files to the "$YOUR-PATH/squashfs-root" directory. "libm.so.6" is in squashfs-root/usr/bin/.

What worked for me is to replace "libm.so.6" in the Appimage with the version in "/lib64" on Fedora and then re-packaging the appimage again by using "appimagetool".
"appimagetool" can be downloaded for your platform here:
https://github.com/AppImage/appimagetool/releases/tag/continuous
"appimagetool" is an appimage itself so there is nothing to install. Just make executable and run.

To repackage the Openshot appimage after replacing the file, run:
"./appimagetool-x86_64.AppImage -v /$YOUR-PATH/squashfs-root"
This creates the file "OpenShot_Video_Editor-x86_64.AppImage" in $YOUR-PATH
Run the appimage as per usual.

Tested it by creating a small project, previewing and exporting it. All worked fine.
More thorough testing may show an issue. Time will tell, fingers crossed.
An error message that can be seen in the "openshot-qt.log" file is a mis-match in the SHA hash.

Again, this worked for me on Fedora38. Not sure if it will work on other platforms.

**Comment by sopheck** [comment]
The workaround also works perfectly under Fedora 39, thank you very much!

**Comment by rohoog** [comment]
Wouldn't it be sufficient to just remove libm.so from the appimage?

**Comment by Colorjet3** [comment]
This has been assigned to the lead developer.  He will be the one to decide how to resolve this issue.

**Comment by ewencluley** [comment]
Deleting `usr/bin/libm.so.6` in the app image and repackaging it worked for me on Ubuntu 23.10. Basically

```
./OpenShot-v3.1.1-x86_64.AppImage --appimage-extract
cd squashfs-root
rm usr/bin/libm.so.6
~/Downloads/appimagetool-x86_64.AppImage . 
```

**Comment by jonoomph** [comment]
I will attempt to create a new AppImage without `libm.so`, and run some tests. I feel like I did this before, lol, but it's worth trying again! Thanks for the tips.

**Comment by jonoomph** [comment]
Sorry for the delay on this one, and thanks for the suggestions. I have merged the fix into our "daily build" AppImage.
https://openshot.org/download/#daily. Bye bye to `libm.so.6`.

**Comment by Colorjet3** [comment]
Thank you @jonoomph.  Build #11732 is ready for download.

**Comment by Bert-H** [comment]
Thanks Jonathan, all working good now on FC39.
