### ISSUE TITLE
.mp4 file isn't viewable?

### ISSUE THREAD

**Issue by Ada3181** [OpenShot/openshot-qt#5301]
This may just be some weird problem on my end, but I figured to get this out there in case someone can help.

I have a .mp4 file that I want to upload into the editor. Typically, you would import the file and it would show up just fine, visuals and audio working. However, one file in particular just is not working when I try to upload it. I've redownloaded the file multiple times, and even redownloaded the editor, but uploading the file produces the same result: a black screen for visuals throughout, though the audio on it still functions.

I checked the file just on my laptop, the visuals are fine. I've downloaded a different .mp4 file onto the project I'm working on, the visuals are fine there too. Nothing is inherently different about the "broken" one either; it's 40 seconds long but I've uploaded longer before that have worked. I've also tried to download the file as a .mov, but it still produces a black screen on the editor. I use OpenShot Version 3.1.1 on MacOS if that means anything. I'll also attach screenshots below. If anyone can help, I'd appreciate it. Thank you!

<img width="656" alt="Screenshot 2023-08-13 at 8 30 09 PM" src="https://github.com/OpenShot/openshot-qt/assets/96184040/33bae820-2a29-465b-8992-1d82773a0495">
<img width="1358" alt="Screenshot 2023-08-13 at 8 31 24 PM" src="https://github.com/OpenShot/openshot-qt/assets/96184040/95eaed93-d523-4719-8474-aed5ce7e6d5e">
<img width="1329" alt="Screenshot 2023-08-13 at 8 31 32 PM" src="https://github.com/OpenShot/openshot-qt/assets/96184040/408ada13-936d-4295-b340-0f65edd4fd6e">

**Comment by Colorjet3** [comment]
Hello @Ada3181.  Every so often we see OpenShot not able to encode a video file properly.  In these situations I suggest you run your source file through a converter like VLC, HandBrake, or Shutter Encoder.  When you do this convert to a .mp4 again but obviously with a different name.

Now import this new file into OpenShot and see if it works properly (video and audio).

**Comment by Ada3181** [comment]
It works like a charm now. Thank you very much for the suggestion :)

**Comment by Colorjet3** [comment]
That is great @Ada3181 and good luck with your project(s).
