### ISSUE TITLE
preview video freezes after 1 second. Have followed all instructions: reinstall w daily build etc, increased cache to 4000

### ISSUE THREAD

**Issue by lozzo52** [OpenShot/openshot-qt#5303]
![Screenshot 2023-08-18 071836](https://github.com/OpenShot/openshot-qt/assets/134746141/0288c8e3-e511-4d28-854b-487701ec706f)
[

**Describe the bug:**

**Steps to reproduce the behavior:**

**Expected behavior:**

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_q
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/12373640/openshot-qt.log)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/12373642/libopenshot.log)
t` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
1.  What Operating System/version are you running (Windows 10 pro?  Ubuntu 22.04 lts? etc?)
2.  Please provide details about your hardware (CPU, GPU/RAM, System RAM, Storage type).
3.  How much free disk space do you have?
4.  Provide some details about your project like what type files are you working with (.mov, .jpg, .mp4, etc?)
5.  Did you increase the Cache to 4000 before the freeze or after the freeze?
6.  Does this happen with one project or all projects?
7.  Any other details that might be beneficial for a speedy troubleshooting.

**Comment by lozzo52** [comment]
Hi Colorjet3,
 I read somewhere that if you convert the MP4 video files first , then it
seems to play OK.
[image: image.png]

So I used VLC convert to "video for youtube HD" and the preview works fine!

[image: image.png]

The original resolution:
[image: image.png]

and the converted file resolution:
[image: image.png]

I have no idea why this works, but maybe you do.

Thanks for a great program!

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#m_-6500503385257634278_DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Colorjet3** [comment]
Hello @lozzo52.  This is something common in the video editing world.  OpenShot, being opensource and dependent on volunteers for development, doesn't have the ability sometimes to deal with irregularities with video/audio combination files with frame rates, bit rates, etc.  So, you will need to run it through a converter which will normalize the file.

Some more advanced editors will recognize this irregularity and either converted for you or prompt you to convert it.

Glad you are moving forward with your project.
