### ISSUE TITLE
Only part of the video is imorted.

### ISSUE THREAD

**Issue by jmb-555** [OpenShot/openshot-qt#5306]
**Describe the bug:**
When you import a video, only part of it is imported. It is a trimmed version of original. 

I talk through the issue in the following video.
https://www.youtube.com/watch?v=cdmlKuORylE

**Steps to reproduce the behavior:**
Steps shown in YouTube link above.

**Expected behavior:**
The video would not be a trimmed version of the original when it is imported. 

**System Details:**
- OpenShot Version 3.1.1
- Ubuntu 22.04.3 LTS

Program does not actually give any warnings or crashes.

**Comment by Colorjet3** [comment]
Hello @jmb-555.
1.  Does the happen with this file only or other files as well when you import them into OpenShot?
2.  Have you tried importing a different type of video file (i.e., .mp4)?  If yes, did this work properly?
3.  Try running your source file through a converter like VLC, HandBrake, or Shutter Encoder and convert it to .mp4 file.  Then import this file into OpenShot and see if that fixes the issue for you.  Be sure to play the .mp4 file you created back in VLC to ensure it is still 18 seconds long.

**Comment by jmb-555** [comment]
1. It has happened on several but not all video screen recordings of the .webm format
2. I tried mp4 and it seemed to work but i have not done a lot of testing with mp4
3. Converting the file to .mp4 worked well

**Comment by Colorjet3** [comment]
Thank you for the information @jmb-555.  I am glad converting it to .mp4 worked well.  I am going to flag this as a bug and assign it to the lead developer for his review.

This is a common issue with other file types as well where OpenShot is unable to deal with certain files based on how they were originally recorded.  Some more advanced video editor do convert these during the importing process but OpenShot is not designed to do that.
