### ISSUE TITLE
błąd przy zapisie gotowego projektu

### ISSUE THREAD

**Issue by DoctorBike** [OpenShot/openshot-qt#5309]
problem występuje gdy konwertuje gotowy projekt do pliku mp4. Po około 5% zapisu wyskakuje błąd std::bad_alloc
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/12405837/openshot-qt.log)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/12405883/libopenshot.log)

**Describe the bug:**

**Steps to reproduce the behavior:**

**Expected behavior:**

**System Details
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/12405776/libopenshot.log)

[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/12405771/openshot-qt.log)
:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by DoctorBike** [comment]
![openshot_blad](https://github.com/OpenShot/openshot-qt/assets/99424940/70bd17af-046f-4f7d-b964-c4680e606e56)
dodaję zrzut ekranu z błędem

**Comment by Colorjet3** [comment]
1. Jakiej wersji OpenShot używasz?

2. Z jakiego systemu operacyjnego i wersji korzystasz?

3. Zwolnij jak najwięcej miejsca na dysku.

4. Upewnij się, że nie masz problemów z pamięcią.


Najprawdopodobniej problemem jest brak wystarczającej ilości wolnego miejsca na dysku.

**Comment by Colorjet3** [comment]
Zamykam zgłoszenie ze względu na brak odpowiedzi. Jeśli problem nadal występuje, otwórz go ponownie. Jeżeli problem został rozwiązany, prosimy o zaznaczenie tego.
