### ISSUE TITLE
Forum registration

### ISSUE THREAD

**Issue by jaimepineiroestrella** [OpenShot/openshot-qt#531]
I have just installed 2.2.0 version and want to solve some problems in the forum. When I try to register, I am supposed to inform about the "tool" I see in the top of the page, in the logo. I have no idea of what tool is that little thing in the logo. Sorry.... 
Can someone help me?

**Comment by ankitpati** [comment]
The forum is no longer actively maintained.

The “Need Help? > Ask a Question” link on [openshot.org](http://openshot.org "OpenShot") redirects to the GitHub issues page, so questions about the program may be asked here instead of seeking help with the forum.

**Comment by JtLively** [comment]
@jaimepineiroestrella don't forget there's always the #openshot IRC channel
