### ISSUE TITLE
Export Clips with no audio

### ISSUE THREAD

**Issue by dbricare** [OpenShot/openshot-qt#5310]
**Question:**
I receive an error when exporting clips created using `Split Clip...` from a video with no audio track. 

`The following error occurred while exporting this clip: 
An invalid sample rate was detected for this codec. for file XXXX`

How do I adjust the codec to allow a sample rate of 0? Or bypass audio encoding for clips?

Thanks!

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 3.1.1
- Operating System / Distro: Mac OS 13.4.1

**Comment by Colorjet3** [comment]
Hello @dbricare.  You can bypass audio encoding during the Export process.

1.  Start the Export process.
2.  From the Export window click on the Advanced tab.
3.  In the Advance Options section change the "Export To:" from "Video & Audio" to "Video Only".

Hopefully this will do the trick for you.

**Comment by dbricare** [comment]
Hi @Colorjet3,

Do you know if this option is available when using the "Export Clips" menu? If I click Export there it goes straight to exporting without allowing adjustment of export options. Then the error is raised during exporting.

I'm trying to break up a long video (with no audio) into a series of shorter clips (with no audio).

![Screenshot 2023-08-28 at 10 18 37 AM](https://github.com/OpenShot/openshot-qt/assets/14186206/37e3a014-f199-44d0-bdfc-73cc17a23382)

Thanks!

**Comment by Colorjet3** [comment]
Unfortunately that feature is not available when you use the "Export Clips" feature.

One thing you may want to do is run your .mp4 files through a converter like HandBrake, Shutter Encoder, or VLC.  Using Shutter Encoder, you can batch convert.  Convert them all to .mp4 again.  Do this with one .mp4 file first to test.  Import the new converted .mp4 file and see if the Export process works better.

**Comment by dbricare** [comment]
Thanks for the advice, I'll give that a shot.

**Comment by Colorjet3** [comment]
Hello @dbricare.  I see that you closed this.  Did the conversion take care of the issue?  Your feedback will help other users as well.
