### ISSUE TITLE
OpenShot Randomly Closing

### ISSUE THREAD

**Issue by jmb-555** [OpenShot/openshot-qt#5313]
**Describe the bug:**
I try and open an mp4 file and OpenShot closes. I have seen other cases of this and it was recommended to convert to mp4. I did so with VLC.

Here is what is going on.
https://www.youtube.com/watch?v=0UZQE9NZZ_c

**System Details:**
- OpenShot Version 3.1.1
Ubuntu 23.04

**Comment by Colorjet3** [comment]
Please try this:
1.  Go to openshot.org/download/#daily and download the latest DEV Daily AppImage available.
2.  Start OpenShot using the AppImage.
3.  Now try importing the .mp4 file.

**Comment by jmb-555** [comment]
This did fix the issue

**Comment by Colorjet3** [comment]
Hello @jmb-555.  This is great.  By the way, if prefer to run the installed version instead of the AppImage you can follow the instructions [here](https://www.openshot.org/ppa/) to download and install the latest DEV Daily Build.  Be sure to execute the "Daily PPA" commands.
