### ISSUE TITLE
The Caption Effect won't Appear in a clip.

### ISSUE THREAD

**Issue by BMART1N7** [OpenShot/openshot-qt#5315]
*Describe the bug*
A Bug that Causes the Caption affect to not show.

**Steps to reproduce the behavior:**
1. Go to Effects
2. Click on Caption
3. Drag and Apply on the Clip (May have to try on Different Clips)

**Expected behavior**
The Captions will Not Show, At all. Editing won't fix things.

**System Details**
- OpenShot Version: 3.1.1
- libopenshot Version:  0.3.2
- Platform: Windows-10-10.0.22621
- Processor: AMD64 Family 25 Model 80 Stepping 0, AuthenticAMD
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.1.1-daily-11583-95eccafc-08c2cdd1-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/c22db2og6c1q3ogm7n05msfbqsc5d5tf/openshot-qt.zip) (4341 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/c22db2og6c1q3ogm7n05msfbqsc5d5tf/libopenshot.zip) (3 KB)

**Comment by Colorjet3** [comment]
Hello @BMART1N7.  I've been using the Caption Effect in both Windows 10 & Windows 11 for a while now and have had no issues with the display with a few exceptions:
1.  If the text color (by default it is white) falls on an areas where it matches the background color which then you will need to change the color of your caption text.
2.  If your caption contains numbers in this format:  99:99.  The ":" between the number causes OpenShot to parse it as a timestamp and makes the numbers disappear.

Note that when you add the caption effect by default it fades in 0.35 seconds and fades out 0.35 seconds (beginning and end).  Meaning with the playhead positioned at the beginning of your clip, you will not see the Caption text until you click play.  If you don't want the fade in/out, right click on the letter C and select Properties.  From the Properties page change the Fade In and Fade Out values to zero or just one of them to zero.

If this didn't solve your issue, then please provide us with step-by-step instructions as to what you are doing so we can try and reproduce your issue.

**Comment by Colorjet3** [comment]
No response from user.
