### ISSUE TITLE
MP3s with thumbnails are recognized as videos

### ISSUE THREAD

**Issue by stuporglue** [OpenShot/openshot-qt#5316]
**Describe the bug:**
If I add an MP3 with a thumbnail to the project it is recognized as a video file. It is not listed in the Project Files pane under Audio, it instead shows up under Video. 

If I remove the thumbnail, and add it again, it shows up under Audio as expected.

**Steps to reproduce the behavior:**

I am using these test files: 

 * https://stuporglue.org/downloads/yes_thumbnail.mp3
 * https://stuporglue.org/downloads/no_thumbnail.mp3

The no_thumbnail.mp3 was created by running the command: 

```
kid3-cli -c 'set Picture ""' yes_thumbnail.mp3
```
To reproduce the issue, drag both files into the Project Files pane of OpenShot. 
Click on the Video or Audio filters and see that yes_thumbnail.mp3 does not show up in the Audio filtered list. 

There are no crashes. The app works, and the files work, they just don't show up where expected. 

**Expected behavior:**

I would expect mp3 files to always show up under Audio.

**System Details:**
- OpenShot Version: 2.6.1
- Operating System / Distro: Debian Testing

```
INFO app: openshot-qt version: 2.6.1
INFO app: libopenshot version: 0.2.7
INFO app: platform: Linux-6.4.0-3-amd64-x86_64-with-glibc2.37
INFO app: processor: 
INFO app: machine: x86_64
INFO app: python version: 3.11.5
INFO app: qt5 version: 5.15.10
INFO app: pyqt5 version: 5.15.9
INFO project_data: Setting default profile to HD 720p 30 fps
INFO language: Qt Detected Languages: ['en-US', 'en', 'en-Latn-US']
INFO language: LANG Environment Variable: en_US.UTF-8
INFO language: LOCALE Environment Variable: 
```

**Log Files:**

```
INFO files_listview: Processing drop event for 2 urls
[mp3 @ 0x2f90ec0] Estimating duration from bitrate, this may be inaccurate
INFO files_model: Imported media file /home/michael/Desktop/no_thumbnail.mp3
INFO project_data: _set key: ['files'] values: {'acodec': 'mp3float', 'audio_bit_rate': 128000, 'audio_stream_index': 0, 'audio_timebase': {'den': 14112000, 'num': 1}, 'channel_layout': 3, 'channels': 2, 'display_ratio': {'den': 1, 'num': 1}, 'duration': 173.1217498779297, 'file_size': '2786033', 'fps': {'den': 1, 'num': 24}, 'has_audio': True, 'has_single_image': False, 'has_video': False, 'height': 480, 'interlaced_frame': False, 'metadata': {'ASIN': 'B0006M196G', 'CATALOGNUMBER': 'TOCT-25572', 'MusicBrainz Album Artist Id': 'ee94b47c-db73-4135-b3d6-deced74b94ba', 'MusicBrainz Album Id': 'e3a7fd14-8690-4299-8d53-037128c7dfc4', 'MusicBrainz Album Release Country': 'JP', 'MusicBrainz Album Status': 'pseudo-release', 'MusicBrainz Album Type': 'album', 'MusicBrainz Artist Id': 'ee94b47c-db73-4135-b3d6-deced74b94ba', 'MusicBrainz Release Group Id': '6730876f-dd90-3b58-b462-4f9014fd30b3', 'SCRIPT': 'Latn', 'TDOR': '2005', 'TMED': 'CD', 'TSO2': 'Straightener', 'album': "Fat's Waller", 'album_artist': 'STRAIGHTENER', 'artist': "Fat's Waller", 'artist-sort': 'Straightener', 'disc': '1/1', 'genre': 'Jazz', 'title': "I'm Crazy About My Baby"}, 'path': '/home/michael/Desktop/no_thumbnail.mp3', 'pixel_format': -1, 'pixel_ratio': {'den': 1, 'num': 1}, 'sample_rate': 44100, 'top_field_first': True, 'type': 'FFmpegReader', 'vcodec': '', 'video_bit_rate': 0, 'video_length': '4154', 'video_stream_index': -1, 'video_timebase': {'den': 24, 'num': 1}, 'width': 720, 'media_type': 'audio', 'id': '8QB1DVM7JS'} add: True partial: False remove: False
INFO main_window: updateStatusChanged
INFO project_data: _set key: ['import_path'] values: /home/michael/Desktop add: False partial: False remove: False
INFO main_window: updateStatusChanged
[mp3 @ 0x2e97cc0] Estimating duration from bitrate, this may be inaccurate
INFO files_model: Imported media file /home/michael/Desktop/yes_thumbnail.mp3
INFO project_data: _set key: ['files'] values: {'acodec': 'mp3float', 'audio_bit_rate': 128000, 'audio_stream_index': 0, 'audio_timebase': {'den': 14112000, 'num': 1}, 'channel_layout': 3, 'channels': 2, 'display_ratio': {'den': 160, 'num': 159}, 'duration': 173.1217498779297, 'file_size': '2786033', 'fps': {'den': 1, 'num': 30}, 'has_audio': True, 'has_single_image': False, 'has_video': True, 'height': 320, 'interlaced_frame': False, 'metadata': {'ASIN': 'B0006M196G', 'CATALOGNUMBER': 'TOCT-25572', 'MusicBrainz Album Artist Id': 'ee94b47c-db73-4135-b3d6-deced74b94ba', 'MusicBrainz Album Id': 'e3a7fd14-8690-4299-8d53-037128c7dfc4', 'MusicBrainz Album Release Country': 'JP', 'MusicBrainz Album Status': 'pseudo-release', 'MusicBrainz Album Type': 'album', 'MusicBrainz Artist Id': 'ee94b47c-db73-4135-b3d6-deced74b94ba', 'MusicBrainz Release Group Id': '6730876f-dd90-3b58-b462-4f9014fd30b3', 'SCRIPT': 'Latn', 'TDOR': '2005', 'TMED': 'CD', 'TSO2': 'Straightener', 'album': "Fat's Waller", 'album_artist': 'STRAIGHTENER', 'artist': "Fat's Waller", 'artist-sort': 'Straightener', 'comment': 'Other', 'disc': '1/1', 'genre': 'Jazz', 'title': "I'm Crazy About My Baby"}, 'path': '/home/michael/Desktop/yes_thumbnail.mp3', 'pixel_format': 12, 'pixel_ratio': {'den': 1, 'num': 1}, 'sample_rate': 44100, 'top_field_first': True, 'type': 'FFmpegReader', 'vcodec': 'mjpeg', 'video_bit_rate': 16092, 'video_length': '5193', 'video_stream_index': 1, 'video_timebase': {'den': 90000, 'num': 1}, 'width': 318, 'media_type': 'video', 'id': '5VQKUN4JOB'} add: True partial: False remove: False
[mp3 @ 0x7f6e20004900] Estimating duration from bitrate, this may be inaccurate
[mp3 @ 0x7f6e20017200] Estimating duration from bitrate, this may be inaccurate
```

**Screenshots:** (Optional)

![image](https://github.com/OpenShot/openshot-qt/assets/16576/5843871a-8209-4e2f-a083-26286ffe5036)
![image](https://github.com/OpenShot/openshot-qt/assets/16576/43386c03-b495-4bde-8237-27a3b3ddeee0)
![image](https://github.com/OpenShot/openshot-qt/assets/16576/9fdb582d-f39c-4183-8d34-3114a1fd9837)

**Comment by Colorjet3** [comment]
Hello @stuporglue.  Thank you for reporting this issue.  This sounds like a bug in OpenShot and the lead developer will have to look into this.  However, before I assign this to him please confirm that this issue exists in v3.1.1 as well.

1.  Go to OpenShot.org/download/#daily.
2.  Download the AppImage, the latest DEV Daily Build available.
3.  Run it and see if the issue persists.

Thank you in advance!

**Comment by stuporglue** [comment]
Hi Colorjet3, 

Unfortunately I can't run the AppImage. I'm getting the same errors as reported on [this bug](https://github.com/OpenShot/openshot-qt/issues/5182) when trying to run it. 

It seems that I have GLIBC 2.37-7 installed

I see there is a workaround involving repackaging the OpenShot AppImage with a new libc. At the moment I don't have the bandwidth to do that. Hopefully someone else can verify the issue (or see that it has been fixed). 

If not, I will check back in a few weeks when I have time and see if I can get the latest version running then to verify.

**Comment by stuporglue** [comment]
I got on my Mac tonight and installed the latest 3.1.1 there (From August 20 - the latest available). The problem exists on this build too. Hopefully this counts as confirmation for the issue. 

![image](https://github.com/OpenShot/openshot-qt/assets/16576/12b06fc0-0f8e-4762-b884-cc65597a35d4)
![image](https://github.com/OpenShot/openshot-qt/assets/16576/71c7d5ee-60d9-4db4-93cf-c5bfb738d85e)

**Comment by Colorjet3** [comment]
Hello @stuporglue.  Thank you so much for the confirmation.  I am able to replicate this in Windows 11 Pro and Ubuntu 22.04 lts.  I just submitted this bug/enhancement request:  https://trello.com/c/n2GDOg0A/56-mp3-with-thumbnails-are-recognized-as-videos

Thank you again!
