### ISSUE TITLE
.mov and .avi files not importing

### ISSUE THREAD

**Issue by LukeVilla** [OpenShot/openshot-qt#5318]
**Describe the bug**
When I try to import .mov and .avi files, the program displays "0 files imported" in the bottom left corner, and the files are not imported.

**Steps to reproduce the behavior:**
1. Open OpenShot
2. Click on "Import Files"
3. Select a .mov or .avi file

**Expected behavior**
The video should show up in the tracks menu.

**System Details**
- OpenShot Version: 3.1.1
- libopenshot Version:  0.3.2
- Platform: Windows-10-10.0.22621
- Processor: Intel64 Family 6 Model 126 Stepping 5, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.1.1-daily-11583-95eccafc-08c2cdd1-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/822u18gd4jvgc6xvi1awpld7axuw57kc/openshot-qt.zip) (5 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
Hello @LukeVilla.  I just tested importing of multiple .avi and .mov files and had no issues running the latest DEV Daily Build #11583.  I tested in both Windows 10 Pro and Windows 11 Pro.

1.  I realize you are running Windows environment but what version (Win 10?  Win 11? etc?).
2.  Please perform a [clean installation](https://github.com/OpenShot/openshot-qt/wiki/Clean-Installation-of-OpenShot) of the latest DEV Daily Build.
3.  If the problem persists, please do the following:

- Try converting your .avi and/or .mov file(s) to .mp4 using VLC, HandBrake, or Shutter Encoder and import the new created files.
- If possible, share one .avi and one .mov that is not working so we can test with it.

**Comment by LukeVilla** [comment]
1. Windows version: Windows 11
2. Never mind, it's working now

**Comment by Colorjet3** [comment]
Hello @LukeVilla.  Glad it is now working.  I am curious as to what made things work.  Your answer/insight can help others.

**Comment by LukeVilla** [comment]
Maybe I was just using a too-old version.
