### ISSUE TITLE
Must run as administrator

### ISSUE THREAD

**Issue by pblitzer** [OpenShot/openshot-qt#532]
I just installed OpenShot on a Windows 10 desktop.  The installation goes uneventfully. However I must run OpenShot as an administrator or I get a Visual C++ error message and the program dies. What should I do?

**Comment by DylanC** [comment]
@pblitzer - Does v2.4 crash for you?

**Comment by pblitzer** [comment]
Don't know -- I gave up on OpenShot.

________________
Peter Blitzer
Empire, Michigan

**Comment by DylanC** [comment]
No problem. Thanks for getting back to me.
