### ISSUE TITLE
Opening a moved project fails in a loop

### ISSUE THREAD

**Issue by carlpaulsen** [OpenShot/openshot-qt#5320]
Using Windows 11, latest stable openshot build.  

When I completed an OpenShot (OS) project I moved my project files including the resources, assets folder and project file but NOT the source video .mkv file (created with OBS), to a new folder.  I generally keep the OBS source files in their own locations.  Then I realized I needed to do more on the project, so tried to open the project file.  During the opening sequence OS opened a missing file dialog warning it could not find the source .mkv file (as I expected since I'd moved things).  Clicking the OK button opens a dialog to find the .mkv file, but when I navigate to the folder where that file is located, there is no .mkv file to select, even though I've confirmed the .mkv file exists in that location.

So problem one is that there doesn't appear to be a way to open a project once it has been moved.

But there's another bigger problem.  Once I close the file select dialog box where I can't select the .mkv file, OS goes back to the "missing file" dialog box and I can't close out of that.  The "x" to close that dialog just brings up the "find directory" dialog box again where I can't select the .mkv file.  Close that box again and the missing file dialog comes back up.  It's an endless loop.  The only solution I've found at this point is to use Task Manager to end the program.

If I move the files and resources back to their original location, the project opens just fine.  So the bug has a workaround, but it sure seems like OS should be able to find the source file when searching in the folder in which it exists.  Failing that, there should at least be a way, within OS, to exit the loop and move on to another project, so the user doesn't have to go into task manager to kill the app.

**Comment by Colorjet3** [comment]
Hello @carlpaulsen.  This is a known issue.  As a matter of fact, this issue exists in other video editors as well, it just that they might handle it differently.  You just need to know how OpenShot deals with this.  What you did was exactly right to get your project back in working order.  There is an enhancement request in the queue to make this process work better.  But for now please check this out:  [Missing File Prompt](https://github.com/OpenShot/openshot-qt/wiki/Missing-File-Prompt)

**Comment by carlpaulsen** [comment]
Ah, thank you and sorry to post a dupe bug report.  I DID search but my terms didn't find any bugs like what I described.  I'm guessing because the Mac Finder handles file paths differently this bug wouldn't impact OS on macs?  I'll have to try it one day as I work on both PC and Mac (and maybe Linux one day...).  Thanks for explaining, and this report can be closed or deleted.  I'll try to be more careful.  Thanks for everything you all do!

Carl

**Comment by Colorjet3** [comment]
You are welcome @carlpaulsen and good luck with your projects.
