### ISSUE TITLE
OpenShot 3.1.1 introduces a loud buzz at the end of UHD HEVC clips

### ISSUE THREAD

**Issue by shockagent** [OpenShot/openshot-qt#5322]
**Describe the bug:**
OpenShot 3.1.1 introduces a loud buzz at the end of each clip in the project.

**Steps to reproduce the behavior:**
1. Add some clips to a project
2. Try to preview them or export the project to a video file.
3. Listen to the last moments of each clip in the video.
4. Hear the buzz

**System Details:**
- OpenShot Version 3.1.1: {{ log_context.openshot_qt_version }}
- Operating System Windows 10 Pro, 22H2, 19045.3448

The bug happens with UHD videos taken with Google Pixel 7 Pro, HEVC encoded.
Here is the FFMPEG output from one of them:

```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '.\PXL_20230827_193617520.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 131072
    compatible_brands: isomiso2mp41
    creation_time   : 2023-xx-xxTxx:xx:xx.000000Z
    location        : +xx.3903-3.6836/
    location-eng    : +xx.3903-3.6836/
    SpecialTypeID   : com.google.android.apps.camera.gallery.specialtype.SpecialType-AMETHYST
    com.android.capture.fps: 30.000000
  Duration: 00:01:40.63, start: 0.000000, bitrate: 43078 kb/s
  Stream #0:0[0x1](eng): Data: none (mett / 0x7474656D), 47 kb/s (default)
    Metadata:
      creation_time   : 2023-xx-xxTxx:xx:xx.000000Z
      handler_name    : MetaHandle
  Stream #0:1[0x2](eng): Audio: aac (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 191 kb/s (default)
    Metadata:
      creation_time   : 2023-xx-xxTxx:xx:xx.000000Z
      handler_name    : SoundHandle
      vendor_id       : [0][0][0][0]
  Stream #0:2[0x3](eng): Video: hevc (Main 10) (hvc1 / 0x31637668), yuv420p10le(tv, bt2020nc/bt2020/arib-std-b67), 3840x2160, 42833 kb/s, SAR 1:1 DAR 16:9, 29.67 fps, 30 tbr, 90k tbn (default)
    Metadata:
      creation_time   : 2023-xx-xxTxx:xx:xx.000000Z
      handler_name    : VideoHandle
      vendor_id       : [0][0][0][0]
Unsupported codec with id 0 for input stream 0
```

Please note that these videos are not corrupted: VLC and FFPLAY can play them without errors.

**Comment by shockagent** [comment]
workaround:

1. extract the audio track as a separate file
2. disable audio from the original video clip
3. add the audio file in a separate track

the buzz is not generated.

**Comment by Colorjet3** [comment]
Hello @shockagent.  This is a known issue with some video/audio files.  Thank you also for posting the workaround.  A few question to further clarify your workaround as it will help the community:
1.  What type of video/audio file are your working with (.mp4, .mov, etc?)
2.  Did you extract the audio within OpenShot or did you do it outside of OpenShot?
a.  If within OpenShot, did you use the "Separate Audio" option?
b.  If outside of OpenShot, what tool did you use to extract the audio?

Thank you again in advance for the workaround.

**Comment by shockagent** [comment]
Hello @Colorjet3 

1. I am using mp4 videos
2. I extracted audio track with FFMPEG, stream copy.
