### ISSUE TITLE
Play MP4 files from HIKVISION

### ISSUE THREAD

**Issue by iserge88** [OpenShot/openshot-qt#5323]
Good morning,

The version "OpenShot-v2.5.1-x86_64" read files from my HIKVISION cameras correctly (I can send you a TEST file)
And I managed to edit...
Since then, the following versions cannot: Why?
No picture (I also tried with windows 10 and 11 same problem)

thank you for your reply

Sincerely

Serge

**System Details**
- OpenShot Version: 2.5.1
- libopenshot Version:  0.2.5
- Platform: Windows-7-6.1.7601-SP1
- Processor: Intel64 Family 6 Model 26 Stepping 5, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['fr-FR']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.1.1-daily-11583-95eccafc-08c2cdd1-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/grzqu6hc2tdzttyhejy9wvvxzzrql3kc/openshot-qt.zip) (20 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/grzqu6hc2tdzttyhejy9wvvxzzrql3kc/libopenshot.zip) (25276 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
Did you upgrade from 2.5.1 to v3.1.1 daily build?  If yes, then give this a try:
1.  Close OpenShot if running.
2.  Make a backup of c:\users\username\.openshot_qt folder.
3.  Delete c:\users\username\.openshot_qt folder.
4.  Start OpenShot v3.1.1 daily build.
5.  Import your .mp4 file and see if the issue has been resolved.

If you are still having an issue then do this:
1.  Run your .mp4 file through a converter using VLC, HandBrake, or Shutter Encoder.
2.  Convert the file to .mp4 again (obviously a new name).
3.  Import this newly converted .mp4 into OpenShot v3.1.1 daily build.
4.  Did this resolve your issue?

**Comment by Colorjet3** [comment]
No feedback from user.  Please reopen if still an issue.
