### ISSUE TITLE
User installed fonts not working in title template

### ISSUE THREAD

**Issue by topher-h** [OpenShot/openshot-qt#5325]
**Describe the bug:**
User installed fonts appear in title template editor, but when selected are not actually applied to the title.

**Steps to reproduce the behavior:**
1. Install a new font
1. Add a title to a project
2. Right click on the template
3. Scroll down to 'Edit template'
4. Choose the newly installed font
5. Select OK

**Expected behavior:**
The font should be applied to the title template

**System Details:**
- OpenShot Version: 3.1.1
- Operating System / Distro: Windows 10

**Log Files:**
n/a

**Exception / Stacktrace:**
n/a

**Comment by Colorjet3** [comment]
This is a documented issue and in the queue to be fixed.  No ETA at this time.
