### ISSUE TITLE
App Image 3.1.1 dose not open ( yes it was made executable)

### ISSUE THREAD

**Issue by jackoniel** [OpenShot/openshot-qt#5326]
homepage download software go to downloads 
right click on options then click on make executable 
click on the App image 
or right click on the App image and click on execute
(I tried both)

**Expected behavior:**

Well the Program should do at least something but.....nothing

**System Details:**
- OpenShot Version 3.1.1 
and
- OpenShot Version Daily build 

- Operating System / Distro: 
 
MSI X570 motherbord   ( MS -7C37)
32 GB Ram DDR 4 
AMD Ryzen 7 2700X
AMD Radon RX 580 Grafik 

- Linux Ubuntu 23.04 

System was fresh and new nothing but a few Pictures from the Internet on the Hard drive yet 

**Log Files:**
I am not a real specialist but as far as i know log files are only possible if there is a somehow working Program so sorry no log files

I miss the DEB times 

since  the same Version App image 3.1.1 was working just the day before on the same system (had some kind of bad Virus)  just between other software i personally think it could be missing something like ubuntu restricted Extras maby or something the other System yesterday already had i just have no idea what that could be. And shouldn't the App image work on a new System without extras? If not please put a note on the Homepage.

**Comment by Colorjet3** [comment]
Hello @jackoniel.  Please see solution provided here:  https://github.com/OpenShot/openshot-qt/issues/4789.

Let us know if this resolved you issue as well.  Another option will be to try and run the PPA installation and run it that way.  You can find the PPA installation [here.](https://www.openshot.org/ppa/)

**Comment by Colorjet3** [comment]
Please reopen if this is still an issue.
