### ISSUE TITLE
MP4 files randomly become frozen.

### ISSUE THREAD

**Issue by IvyMycelia** [OpenShot/openshot-qt#5329]
**Describe the bug:**
When I import an MP4 file, it randomly freezes during export/workspace preview. It works fine in any other application/finder. I also tried copying it, re-downloading it etc. Even videos that worked yesterday are now breaking in openshot.
**Steps to reproduce the behavior:**
1. Go to 'Import'
2. Click on 'Any mp4 file'
3. Scroll down to 'Play the mp4 file'
4. See that the MP4 file freezes

**Expected behavior:**
MP4 file finishing.

**System Details:**
- OpenShot Version 3.1.1
- Operating System Mac Apple Silicon

**Screenshots:** (Optional)

(https://packaged-media.redd.it/q31umnnr3iqb1/pb/m2-res_720p.mp4?m=DASHPlaylist.mpd&v=1&e=1695708000&s=cc3f0ea26b7a5dd4a010b2a4745b689a234184a0#t=0)

**Comment by Colorjet3** [comment]
Hello @TrendyBananaYT.  Please see the answer here:  https://www.reddit.com/r/OpenShot/comments/16s9y1s/mp4_files_imported_freeze/

**Comment by IvyMycelia** [comment]
> Hello @TrendyBananaYT. Please see the answer here: https://www.reddit.com/r/OpenShot/comments/16s9y1s/mp4_files_imported_freeze/

Hey, that is my post as well, and the answers I received there did not help me.

**Comment by Colorjet3** [comment]
I am the same person on Reddit trying to help you, just under a different name.  I'll continue working with you in Reddit.  We can later post the solution here as well.

**Comment by Colorjet3** [comment]
Working on this in Reddit.
