### ISSUE TITLE
Runtime Error - Openshot won't open and won't un/re-install

### ISSUE THREAD

**Issue by wakwakwakwakwak** [OpenShot/openshot-qt#533]
**System Details:**
* Operating System / Distro: Windows 10 Home (64-bit)
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

Openshot stopped opening and shows a runtime error message every time I try opening it. I tried uninstalling Openshot so that I can reinstall, but there's an error when I try to do that.

http://imgur.com/a/RJfFg

Can someone help?

**Comment by DylanC** [comment]
Launch errors with launch.exe on Windows should be resolved in the latest version. Please try v2.4.
