### ISSUE TITLE
AppImage download link on website is not working

### ISSUE THREAD

**Issue by dade-ally** [OpenShot/openshot-qt#5331]
There is no trace for this bug, it is not local.  The problem is on the download page of the openshot web page.

**Screenshots:** (Optional)

![image](https://github.com/OpenShot/openshot-qt/assets/25546413/37bcc875-7446-484c-953f-ccc59c2069f2)

**Comment by Colorjet3** [comment]
Hello @dade-ally.  I just tried the download and it worked for me.  Are you saying that when you click on the blue colored "Download v3.1.1" to the right of "Linux (64-bit AppImage), that nothing is happening?  If this is the case, try a different browser.

Another thing you can try is to download the latest DEV Daily build.
1.  Go to https://www.openshot.org/download/#daily
2.  Click on "Daily Builds".
3.  Download the AppImage.

**Comment by dade-ally** [comment]
Well... to state that it worked for you is quite surprising. I tried it in
Google Chrome and Mozilla Firefox browsers and got timed out error response.

I don't want the daily built, I need 3.1.1 AppImage.

I just tried it now before responding to this email and it was not working.

Thanks for your help.

**Comment by Colorjet3** [comment]
I don't know what to tell you.  I am running Windows 11 on my laptop and unfortunately don't have access to any of my Linux builds to test in (what operating system are your running?).  I am also traveling for a month so will not be able to test.

Give the Daily Build a try, just the download part to see if that part is working.  Another thing to try is clear your browser cash.

If you have access to another computer, tablet, etc, try it there as well.

Update:  I found this link for you to try:  https://github.com/OpenShot/openshot-qt/releases/download/v3.1.1/OpenShot-v3.1.1-x86_64.AppImage

**Comment by Colorjet3** [comment]
Any update on this @dade-ally?

**Comment by dade-ally** [comment]
Yeah, the Download link worked eventually.

Regards!

David
