### ISSUE TITLE
Waveform doesn't work

### ISSUE THREAD

**Issue by maxmishkoy** [OpenShot/openshot-qt#5332]
**Describe the bug:**
Waveform is taking infinite time to execute, I see that its taking much more CPU ressources when excuting, but after 20 minutes nothing appeared even for small clip of 5 sec.

**Steps to reproduce the behavior:**
1. Load MKV video in codek H264
2. Right click on clip -> display -> show waveform

**Expected behavior:**
Waveform takes reasonable amount of time to show sound graph.

**OpenShot version**
![image](https://github.com/OpenShot/openshot-qt/assets/46538597/631cb98a-45ca-4be9-bc40-6b4b6d817cad)

**Operating System**
![image](https://github.com/OpenShot/openshot-qt/assets/46538597/a7fd5f95-1286-4e91-8ee2-c48e31f1ac81)

**Comment by Colorjet3** [comment]
Hello @xxated.  Here are a few options to try:

Option 1
1.  Download the latest AppImage from openshot.org/download/#daily.
2.  Make it executable and run it.
3.  Import you MKV file and give it a try.

Let us know the result.

Option 2
1.  Run your .mkv file through a converter like HandBrake, VLC, or ShutterEncoder and convert it to .mp4.
2.  Import the .mp4 into your current OpenShot version (not the AppImage) and see if it works.  If not, continue...
3.  Import the .mp4 into the AppImage and see if it works.

Let us know the result.

Option 3
1.  Try a different .mkv file and see if you get the same result.
2.  Try importing into both the production version and the daily AppImage.

Let us know the result.

Option 4
1.  Right click on your clip.
2.  Select Separate Audio | Single Clip.
3.  This should separate the Audio from the video and an audio clip should be displayed just below your video clip.

Let us know the result.

I am running Windows 11 and just tried two .mkv files I have and I had no issues with that functionality.  I am running Daily Build 11529.

**Comment by Colorjet3** [comment]
No comment from the user.
