### ISSUE TITLE
OpenShot hangs when loading some jpeg file...

### ISSUE THREAD

**Issue by jpragey** [OpenShot/openshot-qt#5333]
**Describe the bug**
Hangs when trying to load some jpeg files (created by Celluloid screenshot)

**Steps to reproduce the behavior:**
1) load celluloid-shot0012.jpg as image;
2) put it in some track;
3) play the track. 
OpenShot stops before showing the image. I get "Unhandled Exception: Stack Trace" messages in libopenshot.log.

![celluloid-shot0012](https://github.com/OpenShot/openshot-qt/assets/3649259/2e777362-990d-4dd7-b913-bb440d18e997)

**Expected behavior**
Play the track with fixed image in background, or show an error message...

**System Details**
- OpenShot Version: 3.1.1
- libopenshot Version:  0.3.2

- Platform: Linux-5.15.0-86-generic-x86_64-with-glibc2.4
- Processor: x86_64
- Machine: x86_64
- Python version: 3.8.10
- Qt5 version: 5.12.8
- PyQt5 version: 5.14.1
- Qt Detected Languages: ['fr-FR']
- LANG Environment Variable: fr_FR.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.1.1-daily-11583-95eccafc-08c2cdd1-x86_64.AppImage

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/cvw9s38feoz2lypxr20f39ijbxumh2m5/openshot-qt.zip) (5 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/cvw9s38feoz2lypxr20f39ijbxumh2m5/libopenshot.zip) (17 KB)

**Exception / Stacktrace**
```/lib/x86_64-linux-gnu/libc.so.6 raise                                    0x16  [0x7f278dfb6476]
/lib/x86_64-linux-gnu/libc.so.6 abort                                    0xd3  [0x7f278df9c7f3]
/tmp/.mount_OpenShSOh4mO/usr/bin/libavutil.so.56                                          0x383f6  [0x7f27895653f6]
/tmp/.mount_OpenShSOh4mO/usr/bin/libavutil.so.56 av_image_copy                            0x14d  [0x7f27895660ed]
/tmp/.mount_OpenShSOh4mO/usr/bin/libopenshot.so.25 openshot::FFmpegReader::GetAVFrame()     0x19b  [0x7f278cc42efb]
/tmp/.mount_OpenShSOh4mO/usr/bin/libopenshot.so.25 openshot::FFmpegReader::ProcessVideoPacket(long) 0x39  [0x7f278cc4a179]
/tmp/.mount_OpenShSOh4mO/usr/bin/libopenshot.so.25 openshot::FFmpegReader::ReadStream(long) 0x72b  [0x7f278cc4f7eb]
/tmp/.mount_OpenShSOh4mO/usr/bin/libopenshot.so.25 openshot::FFmpegReader::GetFrame(long)   0x8f2  [0x7f278cc50c62]
/tmp/.mount_OpenShSOh4mO/usr/bin/libopenshot.so.25 openshot::FrameMapper::GetOrCreateFrame(long) 0x372  [0x7f278cc6baa2]
/tmp/.mount_OpenShSOh4mO/usr/bin/libopenshot.so.25 openshot::FrameMapper::GetFrame(long)    0x91d  [0x7f278cc6fb0d]
/tmp/.mount_OpenShSOh4mO/usr/bin/libopenshot.so.25 openshot::Clip::GetOrCreateFrame(long, bool) 0x352  [0x7f278cc1d352]
/tmp/.mount_OpenShSOh4mO/usr/bin/libopenshot.so.25 openshot::Clip::GetFrame(std::shared_ptr<openshot::Frame>, long, openshot::TimelineInfoStruct*) 0x36e  [0x7f278cc28a1e]
/tmp/.mount_OpenShSOh4mO/usr/bin/libopenshot.so.25 openshot::Timeline::GetOrCreateFrame(std::shared_ptr<openshot::Frame>, openshot::Clip*, long, openshot::TimelineInfoStruct*) 0x373  [0x7f278cc86143]
/tmp/.mount_OpenShSOh4mO/usr/bin/libopenshot.so.25 openshot::Timeline::add_layer(std::shared_ptr<openshot::Frame>, openshot::Clip*, long, bool, float) 0xb3  [0x...

**Comment by Colorjet3** [comment]
Hello @jpragey.  I don't have access to my Linux environment to test this image.  However, on my laptop with Windows 11, I downloaded the image you shared (thank you for this) and was able to import it into OpenShot, drag it onto a track, and click Play and the image played just fine.  By the way, I am running the latest DEV Daily Build #11529 of v3.1.1.

Please try these:
1.  Download this same image you shared and import it into OpenShot and see if the issue persists.
2.  If the issue persists, then run your source image through a converter like VLC, Shutter Encoder, or Handbrake and convert it to .jpg again, obviously with a different name.  Import this file and see if the issue persists.
3. If the issue persists, go to openshot.org/download/#daily and download the latest DEV Daily build AppImage and give it a try.

If the AppImage works you can perform a complete install of OpenShot following the Daily Build PPA installation found [here.](https://www.openshot.org/ppa/)

**Comment by Colorjet3** [comment]
Please reopen if this is still an issue
