### ISSUE TITLE
2 errors in the italian translation text

### ISSUE THREAD

**Issue by alesmuc** [OpenShot/openshot-qt#5335]
Error n.1
In the italian tutorial the first sentence of the attached screenshot in incomplete. 
The current sentence is:
qui puoi visualizzare il video di anteprima della.
The right sentence is:
Qui puoi visualizzare il video di anteprima della timeline.

![Schermata del 2023-10-08 12-04-28](https://github.com/OpenShot/openshot-qt/assets/35599111/23610c6d-a3ec-441c-b91c-1f54645fa95a)

Error n.2
I found one more error. In the menù you can see in the attached screenshot below ("volume" menù and "tempo" menù) the italian word "azzera" is not correct, as it means "set to zero". The right word is "ripristina" or "resetta".

![Schermata del 2023-10-09 10-00-13](https://github.com/OpenShot/openshot-qt/assets/35599111/28473e0d-4b86-4379-a4a6-e3669c3910b9)
![Schermata del 2023-10-09 10-02-21](https://github.com/OpenShot/openshot-qt/assets/35599111/3e16c574-aec8-440a-8f9a-ab8534850c9a)

**Comment by Colorjet3** [comment]
Hello @alesmuc.  I just submitted [this request](https://trello.com/c/cEgqdjl0/63-italian-translation-errors) to fix this.  No ETA at this time.
