### ISSUE TITLE
Investigating Hardware Acceleration Issues

### ISSUE THREAD

**Issue by ghost** [OpenShot/openshot-qt#5339]
**Describe the bug:**
When footage is imported while OpenShot's Hardware Acceleration is enabled, all imported footage material appears green, both in timeline and project bin.

**Steps to reproduce the behavior:**
1. Go to Edit > Preferences
2. Click on Performance
3. Under Hardware Decoder Mode, select the OS's renderer [DirectX on Windows, Metal on MacOS, VA-API on Linux]
4. Inspect footage both in the project bin and timeline

**Expected behavior:**
Importing footage files should not appear green and should display their expected contents.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 3.1.1
- libopenshot Version: 0.3.2
- Operating System / Distro: Windows 10 Pro 64bit using Nvidia GTX 1650 GPU

**Log Files:**
No crashlogs as this is not an crashing issue

**Exception / Stacktrace:**
No strange outputs

**Screenshots:** (Optional)
![openshot-qt_MRRbNoglPu](https://github.com/OpenShot/openshot-qt/assets/37266538/86685873-7bbf-4e0e-9bb2-ce93fd6b4ede)

**Comment by Colorjet3** [comment]
Hardware Acceleration is currently broken in OpenShot.  Please set all Performance settings back to their original.  There is a ticket in the queue to improve the overall performance of OpenShot, including leveraging of hardware acceleration.  Not ETA at this time.
