### ISSUE TITLE
Smoother Cutting/Splitting Of Clips

### ISSUE THREAD

**Issue by ghost** [OpenShot/openshot-qt#5340]
**Describe the bug:**
When cutting or splitting a clip, there is a small freeze before the GUI updates to show changes.

**Steps to reproduce the behavior:**
A video has been produced to show the issue rather then explaining it in text form. The shortcuts "s" and "Ctrl+K" were used:

https://github.com/OpenShot/openshot-qt/assets/37266538/40da8718-c081-4076-928e-e7b6161386ce

**Expected behavior:**
An almost realtime cutting/splitting experience to speed up editing and workflow.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 3.1.1
- libopenshot Version: 0.3.2
- Operating System / Distro: Windows 10 Pro 64bit using an Nvidia GTX 1650 GPU

**Log Files:**
Not a crashing issue

**Exception / Stacktrace:**
No strange outputs

**Comment by Colorjet3** [comment]
That is a known performance issue that has been documented and in the queue for a fix.  No ETA on the fix.

**Comment by ghost** [comment]
Awesome. Thank you so much for the reply. Currently really wanting to replace Kdenlive with OpenShot to contribute towards my simplicity workflow.
