### ISSUE TITLE
OpenShot 3.1.1 does not run after installation

### ISSUE THREAD

**Issue by Knguyen0404** [OpenShot/openshot-qt#5342]
**Describe the bug:**
I am unable to open and run the Openshot Video Editor.  After installation, I select the OpenShot icon but nothing happens.

I have tried to install and reinstall the following versions but none of them work. I have looked at the reddit forum for OpenShot and none of the suggestions worked.  I installed OpenShot 3.1.1 and several other daily build versions but none of them work.

My laptop information are the following:

Brand: Lenovo

Model: IdeaPad1 15ADA7

Processor AMD Athlon Silver 3050U with Radeon Graphics      2.30 GHz
Installed RAM 20.0 GB (17.9 GB usable)
System type 64-bit operating system, x64-based processor

Please advise. Thank you. Regards. 

**Expected behavior:**

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
Hello @Knguyen0404 

1.  What operating system/version are you running (Windows 10 Pro?  Ubuntu 22.04 lts? etc.)?
2.  Is this the first time you are installing Openshot (excluding trying to install the daily builds)?

Try this:
1. make a backup of c:\users\username\.openshot_qt folder (if running windows) or /home/username/.openshot_qt folder (if running linux). 
2. Delete c:\users\username\.openshot_qt folder (if running windows) or /home/username/.openshot_qt folder (if running linux).
3. Try running OpenShot now.

**Comment by Knguyen0404** [comment]
Windows 11.
No I have tried to install Openshot several times.

Ok thanks for the instructions!

**Comment by Colorjet3** [comment]
Hello @Knguyen0404.  Please confirm if what I suggested worked for you.  If not, we will continue to debug.

**Comment by Knguyen0404** [comment]
Yes it worked. thank you

**Comment by Colorjet3** [comment]
Excellent and you are welcome.
