### ISSUE TITLE
Installation et désinstallation impossible :/

### ISSUE THREAD

**Issue by Clooms** [OpenShot/openshot-qt#5344]
**Describe the bug:**

Unable to install and uninstall. One of my hard drives died recently.
Since I can neither uninstall using Windows
windows error: the specified drive could not be found
nor install it again.

Openshot error: The device or network location you selected does not exist or is not accessible. Please choose another destination.

I would love to choose another destination but the installer does not offer it to me at any time.
I don't want to format my C: drive just to reinstall Openshot.

**Steps to reproduce the behavior:**

crash a disk with the installation on it and double click on the installer

**Expected behavior:**
normal installation

**System Details:**
- OpenShot Version  3.1.1
- Operating System : Windows 10

**Comment by Clooms** [comment]
RevoUninstaler manage to remove remains of the previous install. So I was able to start a new install.
Problem solved.

**Comment by Colorjet3** [comment]
Thank you @Clooms for posting this issue and more importantly the solution.  Just as an FYI, you can find the Uninstall components of any application in Windows operating system in the registry at HKLM\software\microsoft\windows\currentversion\uninstall\.........  You can search for Openshot once at the Uninstall level and delete any entries for OpenShot.

Always make a backup of your Registry before making any changes.
