### ISSUE TITLE
Long Wait For Startup

### ISSUE THREAD

**Issue by ghost** [OpenShot/openshot-qt#5345]
**Describe the bug:**
When either starting OpenShot via the executable or batch script, there is a long wait before OpenShot actually starts

**Steps to reproduce the behavior:**
1. Find your OpenShot executable
2. Double click to open
3. You may see a long wait before the application starts up

**Expected behavior:**
No long delay or wait for OpenShot to open up and start editing.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 3.1.1
- libopenshot Version: 0.3.2
- Operating System / Distro: Windows 10 Pro 64bit

**Log Files:**
No crashes for this issue

**Exception / Stacktrace:**
None for this issue

**Screenshots:** (Optional)
Video of said issue:
https://github.com/OpenShot/openshot-qt/assets/37266538/1b807e89-623c-41dd-8c3e-0be75a4eee85

**Comment by ghost** [comment]
No idea why Github did not make video files playable................

**Comment by Colorjet3** [comment]
What are your computer spec?  On my slower Windows 11 laptop it starts slow.  On my faster gaming desktop, it starts somewhat fast.

You can also try this to see if it helps:
1.  Close OpenShot if running.
2.  make a backup of c:\users\username\.openshot_qt folder.
3.  Delete c:\users\username\.openshot_qt folder.
4.  Start OpenShot.

Let us know the result.

**Comment by ghost** [comment]
Hey there, I use OpenShot on a i5-11500 @ 2.70Ghz, 32GB of DDR4 RAM in dual channel with a GTX 1650 and 450GB Crucial SSD.

I tried your instructions, still seems to have the same long startup time. 

Using OpenShot in portable mode by following this Doc from the official OpenShot Userguide: https://www.openshot.org/static/files/user-guide/installation.html#windows-portable

**Comment by Colorjet3** [comment]
My laptop is definitely less powerful than yours and it takes about 10 seconds for it to load.  I have never run the portable version so I can not compare.  Try installing it and see if that makes a difference.  The installation is very simple and it uninstalls cleanly.

**Comment by ghost** [comment]
Hmm, still seems to be the same through regular installation.

**Comment by Colorjet3** [comment]
I was doing some testing on my laptop and noted that if I logout or restart my computer, then the first time I start OpenShot it takes about 20 seconds.  From then on, and as long as I stay logged in, it only takes about 10 seconds.  So, obviously, it is loading some needed libraries, etc., on the initial start so it takes a bit longer.

What is your experience with this?  Does it take just as long if you close OpenShot and start again?  Just curios.

**Comment by ghost** [comment]
Yes it does take long to startup.

**Comment by Colorjet3** [comment]
I am assigning this to the lead developer.  Please provide the time it takes for the program to start:
1.  Restart your computer and login.
2.  Wait a bit for all Windows services to load.
3.  Start Openshot and time it.
4.  Close OpenShot.
5.  Start Openshot and time it.
6.  Please provide the times from step 3 and step 5.

thank you in advance!

**Comment by ghost** [comment]
Step 3 Startup time: 26 to 27 seconds.

Step 5 startup time: 2 to 3 seconds.

**Comment by Colorjet3** [comment]
Thank you for that information.  Wow, that is quite a difference between the two.  This just might be normal on your computer.  If you have access to other computer(s), you may want to test on those also.

We'll see what the developer has to say when he has time to look into this.  I wouldn't expect a quick response on this as this will be a low priority over so many other actual bugs and issues.
