### ISSUE TITLE
Anteprima video: audio e video rallentati

### ISSUE THREAD

**Issue by grimbeorn74** [OpenShot/openshot-qt#5347]
**Descrivi il bug**
A clear and concise description of the issue

**Passi per riprodurre questo comportamento:**
1. Vai su '...'
2. Fai clic su '....'
3. Scorri fino a '....'
4. Nota l'errore

**Comportamento atteso**
Una descrizione breve e concisa di cosa ci si aspetta dovrebbe succedere.

**Dettagli di sistema**
- OpenShot Version: 3.1.1
- libopenshot Version:  0.3.2
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['it-IT', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Build giornaliera: Il problema verificato esiste ancora nella build giornaliera: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.1.1-daily-11627-2034f45d-08c2cdd1-x86_64.exe

**File di registro**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/aez4lkfkr4yc64ukuz6hy9ov2tgx0oxr/openshot-qt.zip) (0 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/aez4lkfkr4yc64ukuz6hy9ov2tgx0oxr/libopenshot.zip) (46 KB)

**Errore / Stack trace**
```No stacktrace found in log files```

**Schermate** (Facoltativo)
Ove possibile e pertinente, aggiungi screenshot per spiegare il problema. Per farlo, copiali e incollali su GitHub o trascinali direttamente nella pagina GitHub. Dal momento che tutte le immagini condivise sono pubbliche,
ti suggeriamo di non pubblicare mai screenshot contenenti informazioni personali.

**Comment by Colorjet3** [comment]
Non stai fornendo dettagli sufficienti per consentirci di aiutarti.

Descrivi in ​​dettaglio qual è il tuo problema.

**Comment by grimbeorn74** [comment]
Ho importato un file flv, quando vado a far partire la preview per editare il video la riproduzione avviene a rallentatore sia per l'audio che per il video. Ho scaricato l'ultima versione daily ma il problema persiste

**Comment by Colorjet3** [comment]
Grazie per la descrizione dettagliata del problema. OpenShot a volte ha problemi con i file .flv. Questo è un problema documentato. Per ottenere i migliori risultati, converti il ​​tuo file FLV in un file .mp4 utilizzando qualcosa come VLC, Handbrake o ShutterEncoder. Quindi importa questo file .mp4 in OpenShot.

**Comment by grimbeorn74** [comment]
ok, grazie!
