### ISSUE TITLE
.mov files are cut off when added to the timeline 

### ISSUE THREAD

**Issue by huubvanniekerk** [OpenShot/openshot-qt#5349]
**Question:**
Using the RPMFusion version 3.1.1, I'm trying to create a video using a lot of short .mov files. All goes well, apart from 2 .mov files that are being cut off after adding them to a timelins. They both play at normal length in a videoplayer (1:30 and 5:33) but when adding them to the timeline the 1:30 .mov is cut off to 0:01 and the 5:33 is cut off to 0:44. Using CinelerraGG editor for a test, both .mov files are added to the timeline normally. So there's nothing wrong with both .mov files. What could be a reason that these .mov files are being cut off? I've worked with .mov files longer than 6 minutes with all going well. 

**System Details:**
- OpenShot Version 3.1.1
- Operating System / Distro: Fedora Linux 38

**Screenshots:** (Optional)

**Comment by Colorjet3** [comment]
When users report similar issues, usually there is something different about these files that OpenShot can not decode properly.  What I would do is run those two files through a converter like VLC, HandBrake, or ShutterEncoder and convert them to .mp4 files.  Then import them into OpenShot and add to the timeline.

Let us know if this fixes the issue.

**Comment by huubvanniekerk** [comment]
@Colorjet3 Thank you very much! Handbrake did the job for me. After that, adding it to the timeline was no issue anymore.

**Comment by Colorjet3** [comment]
That is great @huubvanniekerk.  Best of luck with your project(s).
