### ISSUE TITLE
when exporting to mp4 file the audio and viedo are not synced 

### ISSUE THREAD

**Issue by aneny2001** [OpenShot/openshot-qt#5351]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 3.1.1
- libopenshot Version:  0.3.2
- Platform: Windows-10-10.0.19041
- Processor: AMD64 Family 25 Model 80 Stepping 0, AuthenticAMD
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['nb-NO', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Skipped this step

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/f2z1el92z9rxbrtrvu2t17hrfjeyzl63/openshot-qt.zip) (654 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Skjermbilder** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
Hello @aneny2001.  Did you resolve this issue?  If yes, what was the resolution?  This will help others.
