### ISSUE TITLE
when exporting to mp4 file the audio and video are not synced 

### ISSUE THREAD

**Issue by aneny2001** [OpenShot/openshot-qt#5352]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 3.1.1
- libopenshot Version:  0.3.2
- Platform: Windows-10-10.0.19041
- Processor: AMD64 Family 25 Model 80 Stepping 0, AuthenticAMD
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['nb-NO', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Skipped this step

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/f2z1el92z9rxbrtrvu2t17hrfjeyzl63/openshot-qt.zip) (705 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/f2z1el92z9rxbrtrvu2t17hrfjeyzl63/libopenshot.zip) (2 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
Hello @aneny2001.  Did you happen to upgrade from a previous version?
Please do this:
1.  Close OpenShot if running.
2.  Make a backup of c:\users\username\.openshot_qt folder.
3.  Delete c:\users\username\.openshot_qt folder.
4.  go to openshot.org/download/#daily and download the latest DEV daily build.
5.  Install this latest DEV daily build.
6.  Start OpenShot and try your Export again.

If you are still having the issue then please provide some more details about your project:
1.  What type of files are you importing into OpenShot (.mp4? .mov? .mp3? etc.)?
2.  Are you working with any audio files?
3.  Does this happen with this project or other projects as well?
4.  Any other details that might help troubleshoot the issue.

**Comment by Colorjet3** [comment]
Hello @aneny2001.  I am closing this ticket since we haven't heard from you.  Feel free to reopen if you still need assistance.
