### ISSUE TITLE
Crash on boot after update to 3.1.1 (Windows10)

### ISSUE THREAD

**Issue by jengstro2** [OpenShot/openshot-qt#5353]
Tried full reinstall, boot, clean, install. It did not want to start, recently updated to 3.1.1.
Is that c:\gitlab-runner\.... just a debug info line from original compilation.. I do not have such folder or file. Anyway. 
I am running Windows 10 Pro N! N/KN stands for windows os which do not have proper mediakit library. But I doubt this is the root-cause here.

18:40:35 INFO app: ------------------------------------------------
18:40:35 INFO app:             Fri Nov 10 18:40:35 2023            
18:40:35 INFO app:               Starting new session              
18:40:35 ERROR app: OpenShotApp::Import Error
Traceback (most recent call last):
  File "C:\Program Files\OpenShot Video Editor\classes\app.py", line 100, in __init__
    from classes import settings, project_data, updates, sentry
  File "C:\Program Files\OpenShot Video Editor\classes\project_data.py", line 48, in <module>
    import openshot
  File "<frozen zipimport>", line 259, in load_module
  File "C:\gitlab-runner\builds\4cf61635\0\OpenShot\openshot-qt/openshot.py", line 15, in <module>
ImportError: DLL load failed while importing _openshot: The specified module could not be found.
18:40:35 INFO app:             OpenShot's session ended            
18:40:35 INFO app:             Fri Nov 10 18:40:35 2023            
18:40:35 INFO app: ================================================

**Comment by Colorjet3** [comment]
Hello @jengstro2.  Please give this a try.
1.  Make a backup of c:\users\username\.openshot_qt folder.
2.  Delete c:\users\username\.openshot_qt folder.
3.  Go to openshot.org/download/#daily and download the latest DEV Daily Build available.
4.  Go to Add or Remove Programs and uninstall v3.1.1.
5.  There is a good chance that if you upgraded from a previous version that you might see two entries for OpenShot.  If you see two entries then Uninstall both.
6.   Now install the latest DEV Daily build (download from step 3 above).
7.  Start OpenShot.

Did this resolve your issue?


**Update:**  Reading your title it makes it sound like your Windows 10 crashes on a reboot.  This is really not the case, correct?  It is OpenShot that is crashing on startup up after your upgraded to v3.1.1, correct?  If this is the case then please update the title of this posting to something like this "OpenShot crashes during startup after upgrading to v3.1.1 in Windows 10".  Then in the description, provide what version of OpenShot you were running before the upgrading to v3.1.1.

**Comment by jengstro2** [comment]
Did that. Even tried x86 version. Same error. Really odd. Long shot: could it be that some of QT framework actually utilizies Windows Media Kit. Dont shoot me :-) I just happened to have Windows 10 N version on this PC. Still, error is clearly from Python. I do not have python installed on this machine, neither exists on the PATH. 


20:32:37 INFO app: ------------------------------------------------
20:32:37 INFO app:             Mon Nov 13 20:32:37 2023            
20:32:37 INFO app:               Starting new session              
20:32:37 ERROR app: OpenShotApp::Import Error
Traceback (most recent call last):
  File "C:\Program Files (x86)\OpenShot Video Editor\classes\app.py", line 100, in __init__
    from classes import settings, project_data, updates, sentry
  File "C:\Program Files (x86)\OpenShot Video Editor\classes\project_data.py", line 48, in <module>
    import openshot
  File "<frozen zipimport>", line 259, in load_module
  File "C:\gitlab-runner\builds\4cf61635\0\OpenShot\openshot-qt/openshot.py", line 15, in <module>
ImportError: DLL load failed while importing _openshot: The specified module could not be found.
20:32:37 INFO app:             OpenShot's session ended            
20:32:37 INFO app:             Mon Nov 13 20:32:37 2023            
20:32:37 INFO app: ================================================

**Comment by jengstro2** [comment]
Hahaa... solved. It WAS the missing Media Feature Pack.  After installing new Media Feature Pack -> OpenShot opens. Seems that Microsoft just keeps removing the Media Feature Pack from N and KN versions, during Windows regular updates secretly. Then you need install manually from here (which is then pretty odd): https://support.microsoft.com/en-us/topic/media-feature-pack-list-for-windows-n-editions-c1c6fffa-d052-8338-7a79-a4bb980a700a

Well... there is some legal history behind this N and KN versions.

**Comment by jengstro2** [comment]
Still. Talking about shady error on log. Nothing points to Media Feature pack.

**Comment by Colorjet3** [comment]
Great job solving the issue and reporting the solution.  I thought the Media Pack was only related to Windows 7 and didn't realize it was for Windows 10 N version as well.
