### ISSUE TITLE
Editing VOB files

### ISSUE THREAD

**Issue by xbbdc** [OpenShot/openshot-qt#5356]
**Describe the bug:**
Editing VOB files is hit or miss it seems. Can edit a VOB file and then when trying to load the next one, it's just black picture and no audio. Even trying to edit a VOB file that worked before now has the same issue.

**Steps to reproduce the behavior:**
1. Go to '...' - Import VOB file
2. Click on '....' - Add to timeline
3. Scroll down to '....' - Play video
4. See error - No picture or audio

**Expected behavior:**
Be able to edit VOB files consistently.

**System Details:**
![image](https://github.com/OpenShot/openshot-qt/assets/59808960/bac80e86-c532-4187-9264-7f60f7a03129)

**Screenshots:** (Optional)
![image](https://github.com/OpenShot/openshot-qt/assets/59808960/ed551e8a-852d-4543-bcde-fdd690f2e340)

[logs.zip](https://github.com/OpenShot/openshot-qt/files/13368569/logs.zip)

**Comment by xbbdc** [comment]
I found https://github.com/OpenShot/openshot-qt/issues/5062 and it looks to be the same unfortunately.

**Comment by xbbdc** [comment]
I have fixed the problem! I believe the way the VOB files are written is that each file after the first doesn't include the header info. I could be wrong.

Anyway, to fix the file is you need to "merge" them together so it's one long file instead of multiple ones.

copy /b file1+file2+file3 targetfile

In my case - copy /b VTS_01_1.VOB+VTS_01_2.VOB beta01.vob

Now loading the beta01.vob files, it plays past the original VTS_01_1 and continues onto VTS_01_2 while editing!

**Comment by Colorjet3** [comment]
Hello @xbbdc.  Thank you for the posting the solution.  OpenShot has never had the feature to gracefully deal with VOB files.  Your workaround is the only way to play the entire video in OpenShot.
