### ISSUE TITLE
Missing audio from known-good source file in a portion of a clip in both preview and export

### ISSUE THREAD

**Issue by JasonHutton** [OpenShot/openshot-qt#5359]
There's a similar one, but not the same thing. (Other one only affects the preview, still exports fine. Mine doesn't work in either case.)

**Describe the bug:**
I've got a 19 second, 56MB video file, that has audio playback just fine anywhere else, but when imported into OpenShot, plays audio for 3 seconds, does not play audio for 14 seconds, then plays audio for 2 seconds. If you split the audio from the video, a waveform is present in the preview, indicating OpenShot should be reading the audio data in some fashion at least.
If desired, the actual source video clip can be provided, if requested in a reasonable timeframe.

**Steps to reproduce the behavior:**
1. Start OpenShot.
2. Drag and Drop the video file into the project.
3. Put the resultant project file clip onto a track.
4. Preview and/or export video.

**Expected behavior:**
I expected audio to play back both in preview and in export, without going silent.

**System Details:**
- OpenShot Version: OpenShot-v3.1.1-daily-11627-2034f45d-08c2cdd1-x86_64
- Operating System / Distro: Windows 11

**Log Files:**
Website will not allow me to submit these log files, and states they are missing OpenShot version information. They are verbose as requested, and are attached. Error on website: "Error: Log files are missing OpenShot version information.
If you are having issues finding your log files, or if the log files are not yet created, you can also submit a bug report [directly on GitHub](https://github.com/OpenShot/openshot-qt/issues/new/choose)."

[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/13435388/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/13435396/openshot-qt.log)

**Exception / Stacktrace:**
No errors in OpenShot.

**Screenshots:** (Optional)
Youtube-hosted videos:
Known good source clip:(contains some swearing in audio): https://youtu.be/e1fUmU_ZnMU
Test case example demonstrating the issue: https://youtu.be/RutzZ0Fh68k 

If you separate the audio from the video a waveform is visible in OpenShot: ![waveform](https://github.com/OpenShot/openshot-qt/assets/4064494/853271fb-3cc2-46eb-a57b-c94de462d680)

**Comment by Colorjet3** [comment]
Hello @JasonHutton.  Please try the following:

1.  Close OpenShot if running.
2.  Make a backup of c:\users\username\.openshot_qt folder.
3.  Delete c:\users\username\.openshot_qt folder.
4.  Go to openshot.org/download/#daily and download the latest dev daily build.
5.  Install it an run it.
6.  Open your project and test.  If the issue persists then continue to step 7.
7.  Run your video file through a converter like VLC, Handbrake, or Shutter Encoder and convert it to .mp4 again.  Obviously with a new name.
8.  Import this new file into a new project and test.

Let us know the result.

**Comment by JasonHutton** [comment]
I've already tested with the latest daily build(https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v3.1.1-daily-11627-2034f45d-08c2cdd1-x86_64.exe (October 9, 2023)) and confirmed the issue there. I do have the source video in a different format already and OpenShot can work with that without issue, but it's choking on one that plays fine elsewhere in multiple other software(MPCHC, VLC, VirtualDub, VideoPad.). Original file is from OBS. Problem file was a trimmed version by VideoPad, which again can be played with other tools fine.

**Comment by Colorjet3** [comment]
Well, this is one of the weaknesses/shortcomings of OpenShot where in some cases and for unknown reasons, at this time, it is unable to deal with certain profiles of content so it doesn't handle it well.  Running it through a converter somehow normalizes the profile enough so that OpenShot can process it properly.

This is documented for an enhancement in a future release.  No ETA at this time.

I know for a fact that other more advanced editors convert certain source files during the import process.  This is what OpenShot needs to do as well.
