### ISSUE TITLE
Crashes when exporting

### ISSUE THREAD

**Issue by gamevidsforfun** [OpenShot/openshot-qt#536]
**System Details:**
* Windows 10 
* OpenShot Version: OpenShot-v2.2.0-48-gc94e08c-49-612-x86_64.exe
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

I can export video's alone.
But when i add a (animated) title, it will crash when exporting

[openshot-qt.txt](https://github.com/OpenShot/openshot-qt/files/851457/openshot-qt.txt)

**Comment by jebeld17** [comment]
Check my instructions on #549.

**Comment by DylanC** [comment]
Could not reproduce on v2.4 daily build.
