### ISSUE TITLE
When importing videos from my Adnroid phone OpenShot crash immediatly 

### ISSUE THREAD

**Issue by FezziFezzino** [OpenShot/openshot-qt#5362]
**Describe the bug**
I try to import videos made with my Android phone in all possible ways to OpenShot but when I do so OpenShot just closes/crash down.

**Steps to reproduce the behavior:**
No Error code... It happens when importing a video file from my Android phone with Android 13, Video is a 1920 x 1080 H.265 30 fps with a 10028 kbps bit rate

**Expected behavior**
That the file get imported with out crashing and can be edited

**System Details**
- OpenShot Version: 3.1.1
- libopenshot Version:  0.3.2
- Platform: Linux-6.2.0-37-generic-x86_64-with-glibc2.35
- Processor: x86_64
- Machine: x86_64
- Python version: 3.10.12
- Qt5 version: 5.15.3
- PyQt5 version: 5.15.6
- Qt Detected Languages: ['en-GB', 'en']
- LANG Environment Variable: en_GB.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.1.1-daily-11627-2034f45d-08c2cdd1-x86_64.AppImage

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/km529yw1mpcm3pujeayes28ocunu7eo8/openshot-qt.zip) (13 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/km529yw1mpcm3pujeayes28ocunu7eo8/libopenshot.zip) (57 KB)

**Exception / Stacktrace**
```/usr/lib/python3/dist-packages/_openshot.cpython-310-x86_64-linux-gnu.so swig::SwigPyForwardIteratorOpen_T<std::_Rb_tree_iterator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, swig::from_oper<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::value() const 0x16  [0x7fdfa85b0446]
/usr/lib/python3/dist-packages/_openshot.cpython-310-x86_64-linux-gnu.so                                          0xbd6fd  [0x7fdfa84bd6fd]
/usr/bin/python3                                                        0x15f854  [0x562e096e1854]
/usr/bin/python3               _PyEval_EvalFrameDefault                 0x2b71  [0x562e096cd2c1]
/usr/bin/python3               _PyFunction_Vectorcall                   0x7c  [0x562e096e270c]
/usr/bin/python3               _PyEval_EvalFrameDefault                 0x802  [0x562e096caf52]
/usr/bin/python3               _PyFunction_Vectorcall                   0x7c  [0x562e096e270c]
/usr/bin/python3               _PyEval_EvalFrameDefault                 0x6bd  [0x562e096cae0d]
/usr/bin/python3                                                        0x16e4e1  [0x562e096f04e1]
/usr/bin/python3               _PyEval_EvalFrameDefault                 0x6bd  [0x562e096cae0d]
/usr/bin/python3               _PyFunction_Vectorcall                   0x7c  [0x562e096e270c]
/usr...

**Comment by Colorjet3** [comment]
Hello @FezziFezzino.  

1.  Are you importing directly from your phone or are you copying to your computer first and then importing?  If you are importing directly from your phone then please copy them first to your local drive then try again.
2.  Are you doing anything special when recording a video with your phone?  If yes, what is the special thing you are doing?
3.  Do you have any other videos from other sources that you can test with?
4.  Run one of your video files through a converter like VLC, HandBrake, or Shutter Encoder and convert it to .mp4 file, even if the original source file is .mp4.  Obviously create a new filename.  Import this and see if it works.  If this works, all the converter tools mentioned can perform a "bulk" conversion.

**Comment by FezziFezzino** [comment]
Hi there..
to 1... I copy it first to my computer (Ubuntu 22.04 LTS) and then using it with OpenShot
to 2... Nope, just the default settings
to 3... Yes, and they work fine... f.e. If I edit the video first with an online editor then I can use the video (same codec) with OpenShot or other (same codec) videos from GoPro 5... 
to 4... Yes, it works after I run it through a converter as mentioned in 3... but that's odd, isn't it? I didn't
't had problems with previous versions of OpenShot though

**Comment by Colorjet3** [comment]
Thank you @FezziFezzino for all the answers.  True, that it may be odd that running it through a converter make it work, but we've been seeing this symptom in OpenShot with different file types and not exactly sure why.  The workaround (converting the files) seems to be the only workaround at this time until the lead developer has time to analyze and decide on a solution.

You can give the latest DEV daily AppImage a try and see if that works any better.  If you do, the do this:
1.  Close OpenShot, if running.
2.  Make a backup of /home/username/.openshot_qt folder.
3.  Delete /home/username/.openshot_qt folder.
4.  Go to openshot.org/download/#daily and download the latest DEV daily AppImage.
5.  Make it executable and run it.
6.  Now import in a file or two and give it a try.  These are the original source files causing the issue.

**Comment by FezziFezzino** [comment]
Ok, no problem... thx for checking...
