### ISSUE TITLE
After a fresh / 1st time install of OpenShot 3.1.1 on Ubuntu 22.04.3 the app opens fine. When choosi...

### ISSUE THREAD

**Issue by I1eoThe0ne** [OpenShot/openshot-qt#5368]
**Describe the bug**
**Steps to reproduce the behavior:**

After a fresh / 1st time install of OpenShot 3.1.1 on Ubuntu 22.04.3 the app opens fine. When choosing an mp4 file (taken with iPhone) OpenShot crashes

After that I tried open the app via terminal and did see a log of errors in the output:

$ openshot-qt 
Loaded modules from: /usr/lib/python3/dist-packages/openshot_qt
INFO app: ------------------------------------------------
INFO app:             Sun Nov 26 21:05:18 2023            
INFO app:               Starting new session              
INFO app: ------------------------------------------------
INFO app:             OpenShot (version 3.1.1)            
INFO app: ------------------------------------------------
INFO app: openshot-qt version: 3.1.1
INFO app: libopenshot version: 0.3.2
INFO app: platform: Linux-5.15.0-89-generic-x86_64-with-glibc2.35
INFO app: processor: x86_64
INFO app: machine: x86_64
INFO app: python version: 3.10.12
INFO app: qt5 version: 5.15.3
INFO app: pyqt5 version: 5.15.6
INFO project_data: Setting profile to HD 720p 30 fps
INFO project_data: Apply default audio playback settings: 48000, 2 channels
INFO app: checking babl_ext_path: /usr/lib/python3/dist-packages/openshot_qt/lib/babl-ext
Screen HDMI-1
   devicePixelRatio: 1.0
   logicalDotsPerInch: 96.0
   physicalDotsPerInch: 108.88753290260826
   availableSizes: PyQt5.QtCore.QSize(2490, 1413)
INFO language: Qt Detected Languages: ['en-US']
INFO language: LANG Environment Variable: en_US.UTF-8
INFO language: LOCALE Environment Variable: 
INFO language: OpenShot Preference Language: Default
INFO app: Setting font to /usr/lib/python3/dist-packages/openshot_qt/images/fonts/Ubuntu-R.ttf
INFO app: Setting custom dark theme
INFO ui_util: Initializing UI for MainWindow
INFO logger_libopenshot: Connecting to libopenshot with debug port: 5556
INFO thumbnail: Starting thumbnail server listening on ('127.0.0.1', 61999)
Sandboxing disabled by user.
INFO webengine: WebEngine backend initializing
INFO transition_model: updating transitions model.
INFO effects_model: updating effects model.
INFO emoji_model: updating emoji model.
INFO version: Found current version: {'error_rate_unstable': 0.05, 'trans_rate_stable': 0.01, 'openshot_version': '3.1.1', 'trans_rate_unstable': 0.001, 'error_rate_stable': 0.25}
INFO main_window: InitCacheSettings
INFO main_window: cache-mode: CacheMemory
INFO main_window: cache-limit-mb: 512
INFO main_window: cache-ahead-percent: 0.7
INFO main_window: cache-preroll-min-frames: 24
INFO main_window: cache-preroll-max-frames: 48
INFO main_window: cache-max-frames: 600
INFO main_window: Creating CacheMemory object with 536870912 byte limit
INFO preview_thread: QThread Start Method Invoked
ERROR main_window: Unhandled crash detected: linux-/usr/lib/python3/dist-packages/_openshot.cpython-310-x86_64-linux-gnu.so swig::SwigPyForwardIteratorOpen_T<std::_Rb_tree_iterator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<cha...

**Comment by I1eoThe0ne** [comment]
The installation was via

sudo add-apt-repository ppa:openshot.developers/ppa
sudo apt update
sudo apt install openshot-qt python3-openshot

With the AppImage the error does not occur :)

**Comment by Colorjet3** [comment]
The PPA installation is pointing back to v2.6.1 which had issues with different file types depending on where/how they were recorded.  Many of those issue are/were fixed with version 3.1.1.  Unfortunately, the PPA installation (stable and daily) is pointing back to v2.6.1 (the lead developer needs to fix this).

Please stay with the AppImage (latest dev daily build of v3.1.1 found at openshot.org/download/#daily).

I also strongly recommend that you do not go back and forth between v2.6.1 and v3.1.1 as they both share the same /home/username/.openshot_qt folder.  You will definitely have issues with project you create if you go back and forth.  Stick with v3.1.1 only.

**Comment by Colorjet3** [comment]
Hello @I1eoThe0ne.  I did not receive confirmation from you if running the PPA installation was truly installing v.2.6.1.  I have assigned this to the lead developer to look into the PPA installation.

I am closing this since the AppImage is working for you.
