### ISSUE TITLE
When reopening project, OpenShot can't find many of the files

### ISSUE THREAD

**Issue by jasonroosdev** [OpenShot/openshot-qt#5370]
**Describe the bug:**
This issue possibly duplicates https://github.com/OpenShot/openshot-qt/issues/1510, but that issue is closed.

**Steps to reproduce the behavior:**
1. Open the app, create a new project, add media
2. Save the OSP
3. Reopen the OSP
4. Observe error messages indicating files cannot be found

I would reproduce the error in more detail but am afraid of closing the app at the moment and losing my work. But the above is essentially all I've done (i.e., nothing particularly special), other than selecting media files, including a mix of images and audio, from outside the folder containing the OSP and from many different folders, not just one.

**Expected behavior:**
The OSP loads without errors

**System Details:**
- OpenShot Version: 3.1.1
- Operating System / Distro: Windows 10

**Comment by Colorjet3** [comment]
If you are receiving "Missing File" message and then it looks like OpenShot is in some kind of a loop, then most likely you did one of the following after you created your project:
1.  Deleted some source files.
2.  Renamed some source files.
3.  Moved some source files into a different folder.
4.  Rename the folder path of your content.

OpenShot, like many other video editors expect the source files to be intact once they are imported.  Please see this for more details:  https://github.com/OpenShot/openshot-qt/wiki/Missing-File-Prompt

**Comment by Colorjet3** [comment]
Hello @jasonroosdev.  Any update on this?  Did you get your issue resolved?  Please reopen if you still need assistance.
