### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Gone167** [OpenShot/openshot-qt#5375]
**Describe the bug:**
when I open the program it says "the most recent unsaved project has been recovered" and a file is "stuck" there and then the program crashes.

**Steps to reproduce the behavior:**

**Expected behavior:**

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

**Screenshots:** (Optional)

![Copia de seguridad recuperada 11_12_2023 19_37_26](https://github.com/OpenShot/openshot-qt/assets/153573048/e7bd2222-8645-4cf0-b4e7-1f0c8c3f3bdd)

**Comment by Colorjet3** [comment]
1. Make a backup of c:\users\username\.openshot_qt folder. 
2. Delete c:\users\username\.openshot_qt folder.
3. Start OpenShot.  Did this solve your issue?

If you are still having issues, then let us know which version of OpenShot you downloaded and installed and also what Operating system you are running (Windows, Linux, or Mac).

**Comment by Colorjet3** [comment]
Hello @Gone167.  any update on this?

**Comment by Colorjet3** [comment]
No response from OP.
