### ISSUE TITLE
When I slice the video, I get a couple of black frames at the end of the video

### ISSUE THREAD

**Issue by dana86Feb** [OpenShot/openshot-qt#5377]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 3.1.1
- libopenshot Version:  0.3.2
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Skipped this step

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/pxnj4paq9d1dffg4kw1e881nlltrwumg/openshot-qt.zip) (10734 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/pxnj4paq9d1dffg4kw1e881nlltrwumg/libopenshot.zip) (108 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
Hello @dana86Feb.  Just a little bit more details so we can better understand the issue:
1.  What type of a video file are you working with (.mp4? .mov? etc?)
2.  What are the exact "slice" steps you are performing?  This will help us to replicate your steps so we can better debug the issue.
3.  When do you see the black frame, during the preview process "Video Preview" window or after you Export the project and play it outside of OpenShot?

**Comment by dana86Feb** [comment]
> Hello @dana86Feb. Just a little bit more details so we can better understand the issue:
> 
> 1. What type of a video file are you working with (.mp4? .mov? etc?)
> 2. What are the exact "slice" steps you are performing?  This will help us to replicate your steps so we can better debug the issue.
> 3. When do you see the black frame, during the preview process "Video Preview" window or after you Export the project and play it outside of OpenShot?

Hi. 
1. I work with mp4 and mkv files. More often with mp4.
2. The slider is placed at the cut spot somewhere in the video, right click, slice, and I choose either 'keep left side' or 'keep right side' - depending what I need. 
3. I can't really tell if the black frame is present in the video preview because the background is black. When I upload it to social media which loops the video files (such as "X") the black frame is there, very visible between loops. If I open teh video in photoshop, as video, it is also visible at the end. If I import by frame into photoshop (I do that to create gif from videos), the layer side window actually shows one black frame at the end of the list of all frames as layer. 

It does not happen every time, it's hit and miss. 

Thank you. 

Edit: in the previous version of openshot it was extremely rare to happen. But since I updated it happens more often, if that helps. I use windows 10.

**Comment by Colorjet3** [comment]
Hello @dana86Feb.  Thank you for that information.  I am aware of this issue with a few other users reporting it as well.  Here is a workaround:

1.  You drag your file onto a Track.
2.  Let's assume you place the playhead (the red line with blue handle at the top) somewhere to make your cut.
3.  Let's say you perform the "Keep left side".
4.  You Export and when you play it outside of OpenShot you note the blank frame or may be 2 blank frames.
5.  Export again, but this time click on the Advanced tab from the Export screen.
6.  On this screen you will find the "Start Frame:" and "End Frame:".
7.  Let's say that the "End Frame:" value is set to 450.
8.  Change the 450 value to 449 and click Export.

This should take care of the issue.  Obviously only do this if you are sure that your Export has a blank frame.

**Update:**  Obviously, if you have more than one blank frame then subtract that number from the "End Frame:" value.

**Comment by dana86Feb** [comment]
> Hello @dana86Feb. Thank you for that information. I am aware of this issue with a few other users reporting it as well. Here is a workaround:
> 
> 1. You drag your file onto a Track.
> 2. Let's assume you place the playhead (the red line with blue handle at the top) somewhere to make your cut.
> 3. Let's say you perform the "Keep left side".
> 4. You Export and when you play it outside of OpenShot you note the blank frame or may be 2 blank frames.
> 5. Export again, but this time click on the Advanced tab from the Export screen.
> 6. On this screen you will find the "Start Frame:" and "End Frame:".
> 7. Let's say that the "End Frame:" value is set to 450.
> 8. Change the 450 value to 449 and click Export.
> 
> This should take care of the issue. Obviously only do this if you are sure that your Export has a blank frame.
> 
> **Update:** Obviously, if you have more than one blank frame than subtract that number from the "End Frame:" value.

Thank you so much!!! I will do that!

**Comment by Colorjet3** [comment]
Be sure to let me know if this solved your issue so I can close this ticket or you can go ahead and close it.  An issue is in the queue for the lead developer to fix.  No ETA at this time.

**Comment by dana86Feb** [comment]
> Be sure to let me know if this solved your issue so I can close this ticket or you can go ahead and close it. An issue is in the queue for the lead developer to fix. No ETA at this time.

Yes! It absolutely solved the problem. Thank you!
