### ISSUE TITLE
Buttons rollover: tooltips are broken

### ISSUE THREAD

**Issue by php4fan** [OpenShot/openshot-qt#5380]
**Describe the bug:**
I have literally just installed Openshot and started moving the mouse cursor around. 
I haven't edited anything, I haven't even loaded any media files into my project or done anything. Literally just moved the mouse cursor over the play, rewind and forward buttons, and I'm already encountering a bug after the first three seconds of use:
![image](https://github.com/OpenShot/openshot-qt/assets/13969584/c3723b36-376c-409f-b31a-db4a0b36457c)
![image](https://github.com/OpenShot/openshot-qt/assets/13969584/0d5de5e0-bf23-4a73-bbd5-5e54b22569b6)
![image](https://github.com/OpenShot/openshot-qt/assets/13969584/9b74cc7d-23c3-4b46-af60-463d165b9605)
![image](https://github.com/OpenShot/openshot-qt/assets/13969584/fb7318b1-a440-4654-a125-3c056a3e7ed4)
![image](https://github.com/OpenShot/openshot-qt/assets/13969584/de2480c8-5e4b-497e-ba50-92b7e2ee93d1)

**Steps to reproduce the behavior:**
1. move the mouse cursor over the play, rewind, fast forward, jump to start and jump to end buttons

**Expected behavior:**

First of all, if you don't know how to properly do an animation for tooltips that appear on rollover on buttons, just don't do the animation. Make the tooltips appear and update immediately.
And secondly, just don't do the animation anyway. Even if it worked, It doesn't contribute anything. It doesn't make the UI smoother, in fact, all the contrary, it just makes it slower. Just make the UI react immediately.

**System Details:**
- OpenShot Version 3.1.1
- Operating System / Distro: Manjaro Linux

**Comment by Colorjet3** [comment]
Hello @php4fan.  

I tested this in OpenShot v3.1.1 and I am not having the issue you have reported.  I am running Windows 11 Pro.

I then fired up my Linux Mint guest in Oracle VirtualBox and not experiencing the issue either.  

Is it possible that your display drivers need to be updated?  Also, go to openshot.org/download/#daily and download the latest DEV Daily Build AppImage.  Make it "Executable" and run it and see if the issue persists.

**Comment by php4fan** [comment]
> I then fired up my Linux Mint guest in Oracle VirtualBox and not experiencing the issue either.

What DE? Can you try on KDE?

**Comment by Colorjet3** [comment]
Hello @php4fan.  Installed KDE and no issues with the tooltips when running OpenShot via the software manager installation or the AppImage,

**Comment by Colorjet3** [comment]
No response from OP.
