### ISSUE TITLE
I've recorded some stuff in obs studio and when in openshot it just shows a green color

### ISSUE THREAD

**Issue by AlecTech1** [OpenShot/openshot-qt#5382]
I recorded a video in obs studio and when i went to edit it the video was just a green color but it still plays the audio just fine
![Captura de Tela (544)](https://github.com/OpenShot/openshot-qt/assets/154699041/bdf48ae0-adef-41d3-9486-63a8157b8662)

**System Details**
- OpenShot Version: 3.1.1
- libopenshot Version:  0.3.2
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['pt-BR', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.1.1-daily-11627-2034f45d-08c2cdd1-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/c0qczi0mg85egzvka77ibngqzimccpto/openshot-qt.zip) (10 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Comment by Colorjet3** [comment]
I've seen this issue before and for some reason (I don't know what) Openshot can not handle certain .MKV files gracefully.  Run your .mkv file through a converter like VLC, HandBrake, or ShutterEncoder and convert it it .mp4 file.  Now import this into OpenShot and see if all is good.

**Comment by AlecTech1** [comment]
It did not fix the issue, i've converted the file to an mp4 and it's still showing just the green color

**Comment by Colorjet3** [comment]
Have you made any configuration changes in Edit | Preferences | Performance tab?  If you have, change them all back to the default setting.  

Hardware Decoder Mode = No acceleration.
Hardware Decoder Graphics Card = Graphics Card 0
Hardware Encoder Graphics Card = Graphics Card 0

Restart OpenShot.

**Comment by Colorjet3** [comment]
Hello @AlecTech1.  Any update on this?

**Comment by AlecTech1** [comment]
Sorry for the wait, i was editing said video. It worked, thanks for the comment

**Comment by Colorjet3** [comment]
Excellent @AlecTech1 and good luck with your project.
