### ISSUE TITLE
AppImage fails to load (v3.1.1)

### ISSUE THREAD

**Issue by luzpaz** [OpenShot/openshot-qt#5383]
**Describe the bug:**
Appimage crashes upon loading

**Steps to reproduce the behavior:**
Run AppImage (downloaded from https://github.com/OpenShot/openshot-qt/releases/download/v3.1.1/OpenShot-v3.1.1-x86_64.AppImage)

**Expected behavior:**
OpenShot runs

**System Details:**
- OpenShot Version 3.1.1 
- Operating System / Distro: Manjaro 23.1.0

**Log Files:**
n/a

**Exception / Stacktrace:**
```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/cx_Freeze/initscripts/__startup__.py", line 40, in run
  File "/usr/local/lib/python3.8/dist-packages/cx_Freeze/initscripts/Console.py", line 37, in run
  File "openshot_qt/launch.py", line 55, in <module>
    from PyQt5.QtWidgets import QApplication
ImportError: /tmp/.mount_OpenShmZhmZ0/usr/bin/libm.so.6: version `GLIBC_2.35' not found (required by /usr/lib/libharfbuzz.so.0)

```

**Screenshots:** (Optional)
n/a

**Comment by andreaconsole** [comment]
Same problem here. Apparently, Ubuntu 23.10 comes with GLIBC 2.38-1ubuntu6 and the AppImage complains it does not find older GLIBC_2.35.

**Comment by Bert-H** [comment]
Firstly, run the Daily Build (click the 'Daily Builds' button on the Downloads page). Don't run the major 3.1.1 release on the downloads page, it likely won't work (properly).
Secondly, the issue you're reporting has been known since at least March this year and has been discussed in thread 5300 and the original 5182. A workaround is provided in those threads.

**Comment by andreaconsole** [comment]
Thanks @Bert-H , your help was fundamental.

**Comment by luzpaz** [comment]
Closing as a duplicate. Workaround is at https://github.com/OpenShot/openshot-qt/issues/5182#issuecomment-1676512852
