### ISSUE TITLE
Library symbol version errror on fedora 38

### ISSUE THREAD

**Issue by rohoog** [OpenShot/openshot-qt#5387]
**Describe the bug:**
When starting the appimage, there is an error "ImportError: /tmp/.mount_OpenShM9adu1/usr/bin/libm.so.6: version `GLIBC_2.35' not found (required by /lib64/libharfbuzz.so.0)".
Either DONT include libm.so in the appimage or also include libharfbuzz.so in the appimage.

**Steps to reproduce the behavior:**
1. Start the appimage on fedora 38 system.
2. See error

**Expected behavior:**
The appimage executes normally in Fedora 38.

**System Details:**
- OpenShot Version 3.1.1
- Operating System / Distro: Fedora 38

**Log Files:**
--

**Exception / Stacktrace:**
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/cx_Freeze/initscripts/__startup__.py", line 40, in run
  File "/usr/local/lib/python3.8/dist-packages/cx_Freeze/initscripts/Console.py", line 37, in run
  File "openshot_qt/launch.py", line 55, in <module>
    from PyQt5.QtWidgets import QApplication
ImportError: /tmp/.mount_OpenShM9adu1/usr/bin/libm.so.6: version `GLIBC_2.35' not found (required by /lib64/libharfbuzz.so.0)

**Screenshots:** (Optional)
--

**Comment by Colorjet3** [comment]
Hello @rohoog.  This has been reported previously and here is a workaround for now:  https://github.com/OpenShot/openshot-qt/issues/5300 and https://github.com/OpenShot/openshot-qt/issues/5182

**Comment by Colorjet3** [comment]
Hello @rohoog.  A new dev daily build #11732 AppImage is now available here:  openshot.org/download/#daily.  I have test this on Fedora 39 and it worked for me.

**Comment by jonoomph** [comment]
Fixed in https://github.com/OpenShot/openshot-qt/pull/5423

**Comment by rohoog** [comment]
Thanks, I hope my suggestion was useful.
