### ISSUE TITLE
Sudden error in exporting

### ISSUE THREAD

**Issue by theinkworm** [OpenShot/openshot-qt#5388]
**Describe the bug:**

**Steps to reproduce the behavior:**
1. Go to 'Export'
2. Click on 'Export'
3. See error

**Expected behavior:**
Sorry, there was an error exporting your video:
Error while writing raw video frame.

**System Details:**
- OpenShot Version 3.1.1: {{ log_context.openshot_qt_version }}
- Windows 11

**Screenshots:** (Optional)
![Screenshot 2023-12-29 224939](https://github.com/OpenShot/openshot-qt/assets/155213426/dda001a4-9ee6-47bd-b972-6997e47247f0)

**Comment by Colorjet3** [comment]
This may be a sign that you are running out of disk space.  Free up as much disk space as possible and try again.

Note:  If you have been exporting many projects, those .mp4 files can get really large if you keep the default "Quality:" setting from the Export scree as "High".  You can change this to "Med" and your export file size will be much smaller without losing quality of your output.

**Comment by Colorjet3** [comment]
No response from OP.  Please reopen if you are still experiencing this issue.
