### ISSUE TITLE
Changin from Open shot 1.4.3.1-1 to Openshot 2.2.0

### ISSUE THREAD

**Issue by jaimepineiroestrella** [OpenShot/openshot-qt#539]
Linux Mint 17.3 and Windows 8
1.4.3-1.1  and 2.2.0

I had 1.4.3 for a couple of years. It was the only version available from my software administrator in Mint. Sometimes, got stopped and closed, but I could make my work fairly well. A month ago, something happened and I could not open the program again. I tried to install again, but the problem remained and had to look for a new version of openshot. 
On the official web site I found the new 2.2.0 which I installed. No problem, but..... when I started using it I found several problems that make real difficult to deal with this version.
The preview, gets stopped  all the time. It runs for 10-15 seconds and gets frozen for a while. That happens all the time. If I split a video in two and try to move one part to another track, the program shuts. For other comments I found that same problems are common. Not only me....
I tried to install it in Windows 8 with the same problems.
So.....¿Can I get 1.4.3.1-1 get back to life somehow? *¿Is any other version available that works properly not 1.4.3 or 2.2.0? 
Thanks for your help.

**Comment by jaimepineiroestrella** [comment]
I would prefer to work into Mint 17.3 but W8 would be possible too....

**Comment by DylanC** [comment]
@jaimepineiroestrella - Please try a newer build to confirm if it suits your needs. Thanks.
