### ISSUE TITLE
Videodateien importieren

### ISSUE THREAD

**Issue by ghost** [OpenShot/openshot-qt#5390]
**Beschreiben Sie den Fehler**
A clear and concise description of the issue

**Schritte zum Reproduzieren des Verhaltens**
1. Gehe Sie nach '...'
2. Klicken Sie auf '....'
3. Scrollen Sie hinunter nach '....'
4. Sehen Sie den Fehler

**Erwartetes Verhalten**
Eine klare und prägnante Beschreibung dessen, was Sie erwartet haben.

**Systemdetails**
- OpenShot Version: 3.1.1
- libopenshot Version:  0.3.2
- Platform: Linux-5.15.0-91-generic-x86_64-with-glibc2.35
- Processor: 
- Machine: x86_64
- Python version: 3.10.13
- Qt5 version: 5.15.9
- PyQt5 version: 5.15.1
- Qt Detected Languages: ['de-DE', 'de', 'de-Latn-DE']
- LANG Environment Variable: de_DE.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Diesen Schritt übersprungen

**Logdateien**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/8wfd8sr4akkm30oab698u0qifbipup1i/openshot-qt.zip) (45 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/8wfd8sr4akkm30oab698u0qifbipup1i/libopenshot.zip) (26 KB)

**Ausnahme / Stapelverfolgung**
```/usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0 PyTuple_New                              0x18  [0x7f3d9b3a1ad8]
/app/lib/python3.10/site-packages/_openshot.so swig::SwigPyForwardIteratorOpen_T<std::_Rb_tree_iterator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, swig::from_oper<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::value() const 0x1f  [0x7f3d9a02b42f]
/app/lib/python3.10/site-packages/_openshot.so                                          0xaf93b  [0x7f3d99f4793b]
/usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0                                          0x17a394  [0x7f3d9b407394]
/usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0 _PyEval_EvalFrameDefault                 0x44f8  [0x7f3d9b2ff148]
/usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0                                          0x1ca405  [0x7f3d9b457405]
/usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0 _PyEval_EvalFrameDefault                 0x7386  [0x7f3d9b301fd6]
/usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0                                          0x1ca405  [0x7f3d9b457405]
/usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0 _PyEval_EvalFrameDefault                 0x688b  [0x7f3d9b3014db]
/usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0                                          0x1ca405  [0x7f3d9b457405]
/usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0                                          0x140fd0  [0x7f3d9b3cdfd0]
/usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0 _PyEval_EvalFrameDefault                 0x688b  [0x7f3d9b3014db]
/usr/lib/x86_6...

**Comment by ghost** [comment]
Wenn ich Dateien importieren möchte, beendet sich das OpenShot sofort bei .mov und .mp4 Dateien. .mts Dateien werden importiert.

**Comment by Colorjet3** [comment]
Bitte mach das:

1. Gehen Sie zu „Programme hinzufügen oder entfernen“ und deinstallieren Sie OpenShot v3.1.1.

2. Gehen Sie zu openshot.org/download/#daily und laden Sie den neuesten DEV Daily Build herunter.

3. Erstellen Sie eine Sicherungskopie des Ordners c:\Benutzer\Benutzername\.openshot_qt.

4. Löschen Sie den Ordner c:\users\username\.openshot_qt.

5. Installieren Sie die Version, die Sie in Schritt 2 heruntergeladen haben.

6. Versuchen Sie den Import erneut.

Wenn das Problem weiterhin besteht, führen Sie Ihre .mp4- und .mov-Dateien über einen Konverter wie VLC, Handbrake oder Shutterencoder aus und konvertieren Sie sie in .mp4 (ja, sogar die ursprüngliche .mp4-Datei wandelt sie wieder in .mp4 um). Versuchen Sie nun den Import und prüfen Sie, ob das Problem dadurch behoben wird.

**Comment by Colorjet3** [comment]
No response from OP.
