### ISSUE TITLE
Cannot open animated titles

### ISSUE THREAD

**Issue by ghost** [OpenShot/openshot-qt#5395]
when opening animated titles pane and chosing a template, mouse designator changes in pause circle for more tahan 10 minutes. No results. No error messages.
Path in preferences is correct.
In Blender I activated CUDA and Optix
![opensh](https://github.com/OpenShot/openshot-qt/assets/157625112/cee139fd-530d-4c26-a1a8-d64d21b000be)

**I expected to see an animated title and wanted to use it.

[LOG.txt](https://github.com/OpenShot/openshot-qt/files/14041424/LOG.txt)

**Comment by Colorjet3** [comment]
When you select a template, the next screen you see is what you have attached.  Now, go ahead and change the Title as you wish.  Now click on the Render button and you title should be created and saved in the "Project Files" tab/window.

By the way, if you want to see the template in action before you click on render, all you have to do is move the "Frame:" slider forward or backwards (it is currently sitting on frame 125 of 250) and it will refresh the screen.

Update:  There is a possibility that you have a corrupt OpenShot installation and/or Blender.
1.  go to openshot.org/download/#daily and download the latest DEV daily build #11627.
2.  Install it and try again.  If still having the issue then reinstall Blender as well.
3.  In Blender may be disable the hardware acceleration for now.  Test without it and if it works, enable each hardware acceleration one at a time to see if one of them causes an issue.

report back and we can continue to troubleshoot

**Comment by ghost** [comment]
This did'nt help me. When I choose a template, I can change the title but
the 'render' button stays grey  and  is still not active.
So, no result. What  can I do to make it happen?


Op wo 24 jan. 2024 19:34 schreef Colorjet3 ***@***.***>:

**Comment by Colorjet3** [comment]
Hello @oopep.  Are you saying you executed each of the steps I suggested?

If yes, then:
1. What operating system/version are you running?
2. Please verify the version of OpenShot and include the build number.  the build number is in the 3rd line of information when you perform Help | about openshot.

**Comment by ghost** [comment]
Thanks voor your quick reaction!


  1.
Windows 11 Home, 23H2, Build 22631.3007
  2.
OpenShot-v3.1.1-daily-11627-2034f45d-08c2cdd1    Build Date: 2023-10-09   20:03
  3.
Blender 4.0

________________________________
Van: Colorjet3 ***@***.***>
Verzonden: vrijdag 26 januari 2024 17:10
Aan: OpenShot/openshot-qt ***@***.***>
CC: oopep ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [OpenShot/openshot-qt] Cannot open animated titles (Issue #5395)


Hello @oopep<https://github.com/oopep>. Are you saying you executed each of the steps I suggested?

If yes, then:

  1.  What operating system/version are you running?
  2.  Please verify the version of OpenShot and include the build number. the build number is in the 3rd line of information when you perform Help | about openshot.

**Comment by Colorjet3** [comment]
Hello @oopep.  Thank you for the information.  I am also running Windows 11 Pro, 23H2, Build #22631.3085 and Blender 4.0.  I have zero issues with Animated Titles.

Please try this:
1.  Close OpenShot and Blender if running.
2.  Make a backup of c:\users\username\.openshot_qt folder.
3.  Delete c:\users\username\.openshot_qt folder.
4.  Start Openshot and in a new project, try creating an Animated Title.
5.  Did this work?

If you are still having issues please provide a Screen Shot of the following:
a.  Edit | Preferences | General tab.
b.  Edit | Preferences | Cache tab.
c.  Edit | Preferences | Performance tab.

**Comment by ghost** [comment]
Hello @colorjet3 !

This helped! As you wrote, I deleted the .openshot_qt folder  and started OpenShot. Now I could choose a Title template and render it!
I restored the original  .openshot_qt folder and the problem occurred again. Why?  During installation of OpenShot the path to Blender was automatically wrong installed : it referred to blender_launcher.exe instead of blender.exe.

So, thanks to you the problem is solved! I am very gratefull !
________________________________
Van: Colorjet3 ***@***.***>
Verzonden: vrijdag 26 januari 2024 21:40
Aan: OpenShot/openshot-qt ***@***.***>
CC: oopep ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [OpenShot/openshot-qt] Cannot open animated titles (Issue #5395)


Hello @oopep<https://github.com/oopep>. Thank you for the information. I am also running Windows 11 Pro, 23H2, Build #22631.3085 and Blender 4.0. I have zero issues with Animated Titles.

Please try this:

  1.  Close OpenShot and Blender if running.
  2.  Make a backup of c:\users\username.openshot_qt folder.
  3.  Delete c:\users\username.openshot_qt folder.
  4.  Start Openshot and in a new project, try creating an Animated Title.
  5.  Did this work?

If you are still having issues please provide a Screen Shot of the following:
a. Edit | Preferences | General tab.
b. Edit | Preferences | Cache tab.
c. Edit | Preferences | Performance tab.

**Comment by Colorjet3** [comment]
You are very welcome!

There is a file in the .openshot_qt folder named openshot_settings.  When you restored the .openshot_qt folder it brought that bad setting for the Blender path.

That was the reason I was asking for a screen shot of the General tab so I could see your settings.

Glad you figured out what part was causing the issue and on your way to work on your projects.
