### ISSUE TITLE
Split Clip (Ctrl+E) and Export (Ctrl+E) shares shortcuts

### ISSUE THREAD

**Issue by jarlarntzen** [OpenShot/openshot-qt#54]
**Ubuntu 14.04 LTS:** I suggest changing **Split Clip** shortcut to something else.

**Comment by olielvewen** [comment]
Why?

**Comment by olielvewen** [comment]
Okay. Done I've changed Ctrl + E by Ctrl + C.
It is in my branch(https://github.com/olielvewen/openshot-qt). she will be merged soon.
Tell me if all is okay and I'll close this bug.
Thanks.

**Comment by nwgat** [comment]
how about a config file or a dialog in settings?

**Comment by Bugsbane** [comment]
I'd suggest changing export to Ctrl+shift+E as that's already used in a number of other FOSS apps (Gimp, Inkscape etc)

**Comment by jarlarntzen** [comment]
@Bugsbane :+1. 
@olielvewen: Okay but Ctrl+C is normally reserved for the Copy command. Shouldn't mess too much with such ubiquitous defacto standards I think. Ctrl+C is expected to perform a copy action in virtually every desktop application.

**Comment by Bugsbane** [comment]
Ctrl+C and Ctrl + V would have to be the most commonly understood and used shortcuts anywhere. I really wouldn't use them for anything other than copy/paste.

**Comment by jarlarntzen** [comment]
@Bugsbane: +1. As well as Ctrl + X for cutting,  of course.

**Comment by olielvewen** [comment]
@jarlarntzen 
@Bugsbane 
Okay. I've changed it for Ctrl + X.

@nwgat : Sorry I don't understand what do you want ?

**Comment by jonoomph** [comment]
These changes are committed to the next build. Thanks!

**Comment by qubodup** [comment]
Ctrl+x "cutting" means "move". I would advise against using it. :)

Final Cut Pro X: Command-B / Command-Shift-B
Pitivi: S
Premiere Pro: Shift-K
Shotcut: S
Kdenlive: Shift-R
Blender: K / Shift-K
Lightworks: C (not sure)
After Effects: Ctrl+Shift+D

I have no words.
