### ISSUE TITLE
video reduced to 1/2 speed crashes launch

### ISSUE THREAD

**Issue by dpchurl** [OpenShot/openshot-qt#540]
Log Name:      Application
Source:        Windows Error Reporting
Date:          20/03/2017 16:57:15
Event ID:      1001
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      New-PC
Description:
Fault bucket 120658200415, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: launch.exe
P2: 0.0.0.0
P3: 57a98a3e
P4: StackHash_4c6d
P5: 10.0.14393.479
P6: 5825887f
P7: c0000374
P8: PCH_06_FROM_ntdll+0x00000000000A6C24
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER203C.tmp.WERInternalMetadata.xml

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_launch.exe_931bdd54c99a35c4f9abe0445749bb997085ff6a_8ac0f197_007835d7

Analysis symbol: 
Rechecking for solution: 0
Report Id: e4af6c7a-432c-400a-b0d5-8030a9747fac
Report Status: 0
Hashed bucket: 8c23a717dfa4ab64a3b454eb865639f2
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows Error Reporting" />
    <EventID Qualifiers="0">1001</EventID>
    <Level>4</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-03-20T16:57:15.207267700Z" />
    <EventRecordID>14223</EventRecordID>
    <Channel>Application</Channel>
    <Computer>New-PC</Computer>
    <Security />
  </System>
  <EventData>
    <Data>120658200415</Data>
    <Data>4</Data>
    <Data>APPCRASH</Data>
    <Data>Not available</Data>
    <Data>0</Data>
    <Data>launch.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>57a98a3e</Data>
    <Data>StackHash_4c6d</Data>
    <Data>10.0.14393.479</Data>
    <Data>5825887f</Data>
    <Data>c0000374</Data>
    <Data>PCH_06_FROM_ntdll+0x00000000000A6C24</Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER203C.tmp.WERInternalMetadata.xml</Data>
    <Data>C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_launch.exe_931bdd54c99a35c4f9abe0445749bb997085ff6a_8ac0f197_007835d7</Data>
    <Data>
    </Data>
    <Data>0</Data>
    <Data>e4af6c7a-432c-400a-b0d5-8030a9747fac</Data>
    <Data>0</Data>
    <Data>8c23a717dfa4ab64a3b454eb865639f2</Data>
  </EventData>
</Event>
**System Details: Processor	Intel(R) Pentium(R) CPU G3220 @ 3.00GHz, 3000 Mhz, 2 Core(s), 2 Logical Processor(s) 
4GB RAM, 1TB hard disk

* Operating System / Windows 10 .0.14393 build 14393
* OpenShot Version: 2.2.0

12 second 1280x720 30fps mp4 clip runs OK in preview unchanged. Wanted to make it slower so used right click, time, slower, forwards,1/2x to double its length. Crashed (Windows said an error had ocurred) almost immediately on trying to preview it. Similar experience on trying to reduce speed to 1/4x.
Clip used was obtained using Video Download Helper from https://apod.nasa.gov/apod/ap140319.html

**Comment by croco3008** [comment]
Confirmed. Same happens when you speed up video. To work around problem, disable the audio of the clip.

**Comment by DylanC** [comment]
@dpchurl - Does this happen in OpenShot v2.4?

**Comment by DylanC** [comment]
@dpchurl - Could not reproduce on the latest daily build.
