### ISSUE TITLE
Copy shortcut not working (Ctrl-C)

### ISSUE THREAD

**Issue by leodf1** [OpenShot/openshot-qt#5405]
**Describe the bug:**
The 'Copy' keyboard shortcut Ctrl-C , does not work

**Steps to reproduce the behavior:**
1. Select a clip on timeline
2. Press Ctrl-C on the keyboard
3. Paste the clip onto timeline with Ctrl-V or Rt-click - Paste
4. Nothing happens
5. [Paste dialogue does not appear because nothing was copied]

**Expected behavior:**
A copy of the clip appears on the timeline where you pasted

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by leodf1** [comment]
Copy can only be done by using mouse Rt-click - Copy.  And pasted with Ctrl-V or Rt-Click - Paste

Keyboard shortcut Ctrl-C does nothing.

Paste dialogue does not appear after (trying to) copy with Ctrl-C, because the shortcut did not make a copy, therefore there is nothing to paste

**Comment by Colorjet3** [comment]
Hello @leodf1.  Can confirm this.  This has been reported previously by other user (some in openshot sub-reddit as well) but it needs to get in the queue.

Here are a few links that are somewhat related to the CTRL+ functionality.  See if you have any comments on these as well.
https://trello.com/c/W21uf79l/10-the-ctrl-and-shift-operations-dont-quite-work-like-boolean-operators-from-other-windows-programs?search_id=77c3f715-e9df-48b4-bb19-cc76d3343baa

https://trello.com/c/An0ysPVr/124-ctrla-does-not-work-in-linux-and-%E2%8C%98-a-does-not-work-in-macos?search_id=3b58aa83-26ab-45cf-bb27-6b4fbdc48cbd

**Comment by leodf1** [comment]
Cannot vouch for how the standard Ctrl-Shift mouse selection modifiers should work in an Editor, since I'm not used to mouse editing. And I don't have a copy of Resolve installed right now, to test it out. Can confirm in my OpenShot, Ctrl click does multi select as expected, but Shift click or Ctrl-Shift click does not range select as per the standard Windows method. This is not important for me.

Select All (Ctrl-A) works fine. [Windows]

The only other shortcut issue is the default 'Clear Cache' shortcut, Ctrl-Shift-Esc. Which on Windows opens the Task Manager. I did not raise this issue since it would be easy enough to change the shortcut in Preferences.
But I don't know what 'Clear Cache' does anyway [Undocumented]. So there.

**Comment by Colorjet3** [comment]
Thank you for the feedback.  At one time I knew what the "Clear Cache" was for but it escapes me right now-LOL!  The "Clear Cache" issue was/is related to performance so it should be addressed when the performance issues are addressed.

**Comment by Colorjet3** [comment]
This is now in the queue:  https://trello.com/c/JamFnb78/65-ctrlc-does-not-work

**Comment by Colorjet3** [comment]
Hello @leodf1.  This issue has been fixed in the latest dev daily build (openshot.org/download/#daily).  When you have time please test this and if all is good make a comment and "close" this ticket.

Otherwise just confirm and I can also close it.

**Comment by leodf1** [comment]
Working now

Thanks
