### ISSUE TITLE
Cannot move or change the blue timeline slider

### ISSUE THREAD

**Issue by jacksonKando** [OpenShot/openshot-qt#5416]
**Describe the bug:**
The blue slider to change the view of the timeline cannot be moved or it's size changed. After messing around with the views, I was able to decrease the size of the blue slider, but this only resulted in the actual timeline getting smaller and smaller. 

**Steps to reproduce the behavior:**
Difficult to say, I couldn't do anything to the blue slider when I opened the file. After changing the views a couple times, I could change the size of the blue slider but ended up shrinking the timeline view instead.

**Expected behavior:**
Expected to be able to move the slider and change its size like normal

**System Details:**
- OpenShot Version [3.1.1]
- Operating System / Distro: Windows 10

**Screenshots:** 
![timeline](https://github.com/OpenShot/openshot-qt/assets/159494380/8d49ca7f-f352-4182-9e4e-49ab4be9d3a2)

**Comment by jacksonKando** [comment]
Was able to solve by doing crt+ scroll wheel.

**Comment by Colorjet3** [comment]
Great.  You can also use the "-" and "=" to zoom in/out.

**Comment by jacksonKando** [comment]
@Colorjet3 ah sweet, not really familiar with any of the shortcuts lol

**Comment by Colorjet3** [comment]
In OpenShot, go to Edit | Preferences | Keyboard tab and you will see all the available shortcuts.  CTRL+C  is currently broken.
