### ISSUE TITLE
'NoneType' object is not subscriptable error in Openshot.

### ISSUE THREAD

**Issue by WaWaWiWa1** [OpenShot/openshot-qt#5417]
I was editin a video in openshot video editor when suddenly all the pathways just became empty. I closed the app and opened it again and the error
" 'NoneType' object is not subscriptable"
popped up. Here is an image of what it looks like
![image](https://github.com/OpenShot/openshot-qt/assets/159716224/1086f0a2-a158-48fb-9a09-60ffc87f2071)
I cannot export the file or open it in OBS. I opened it in Notepadd++ and there was no "null," line to delete
Someone please help me with this
[Spraining my ankle stopped me from going to a real fight (1).zip](https://github.com/OpenShot/openshot-qt/files/14233252/Spraining.my.ankle.stopped.me.from.going.to.a.real.fight.1.zip)

**Comment by Colorjet3** [comment]
Hello @WaWaWiWa1.  In order for us to open your project you must include every single file that is imported into OpenShot.  Additionally, there is an accompanying "Spraining my ankle stopped me from going to a real fight_assets" folder that gets created that you should include that to.

However, before you do all that see if you can recover your project:
1.  Close OpenShot if running.
2.  Go to c:\users\username\.openshot_qt\restore folder (if running windows) or /home/username/.openshot_qt/restore folder (if running Linux).
3.  Find your project (there could be multiple entries of your project starting with some random numbers).
4.  Double click on the most recent one and see if Openshot can open it gracefully.
5.  If that fails then try the next one, etc.
6.  You might lose some work when recovering but at least you can continue working on it.

Always let us know what operating system/version you are running and which version of OpenShot you are running.

**Update:**  I want to make sure that you **did NOT** delete any of your imported files, or renamed them, or renamed the folder they were in.  If you did any of these, then you need to restore them all to their original names and locations (including the folder path).

**Comment by WaWaWiWa1** [comment]
Here you go. I had to send separate zips as I  would exceed 25mb if I send one file
[zip 2.zip](https://github.com/OpenShot/openshot-qt/files/14241654/zip.2.zip)
[zip 1.zip](https://github.com/OpenShot/openshot-qt/files/14241675/zip.1.zip)
[zip 3.zip](https://github.com/OpenShot/openshot-qt/files/14241678/zip.3.zip)
[zip 4.zip](https://github.com/OpenShot/openshot-qt/files/14241680/zip.4.zip)
there is one video that even after compressing is too big, so I don't know how to send it.

**Comment by Colorjet3** [comment]
Thank you @WaWaWiWa1.  Let me work with these first and we'll think about the one larger video later.

Stay tuned...

**Comment by Colorjet3** [comment]
Hello @WaWaWiWa1.  There is something with the metadata of each source file that OpenShot is having an issue with.  It is most likely something with Openshot not knowing how to handle this metadata that is causing the 'NoneType' message.

I ran each of your source files through a converter.  I used ShutterEncoder but you can use VLC or HandBrake as well to do the same thing.  All I did is run each .jpg and converted to a .jpg again with a different name.  I did the same with .mp4 files and converted them back to h.264 (.mp4) files with different names.

I then imported these into Openshot (started a new project), saved it and everything is working fine.

Go ahead and run your files through a converter and confirm that this works for you as well.  May be just pick 2 .jpg and 2 .mp4 files for now just to test with.

The .jpeg and .png files seem to be ok.  no need to run these through a converter.

If everything works for you we will need to escalate this to the lead developer for his review and analysis.

**Update:**  I am curious as to how you created your content (Camera, smart phone, etc.)?

**Comment by Colorjet3** [comment]
Hello @WaWaWiWa1 Any update on this?

**Comment by WaWaWiWa1** [comment]
I ran every file through a converter but it turns out that there is a file missing which was there before but now isn't. I can't even find it in the trash bin or my OneDrive

**Comment by Colorjet3** [comment]
So, did the files that you converted work properly when imported into a new project?  If yes, then you just have to figure out what is missing file is, find it, and imported into your project.

You didn't answer this:  I am curious as to how you created your content (Camera, smart phone, etc.)?

**Comment by WaWaWiWa1** [comment]
They do work it's that the one file that's missing is nowhere to be seen, even on my OneDrive.
I sometimes use my phone camera but mainly the laptop webcam.

**Comment by Colorjet3** [comment]
Hello @WaWaWiWa1.  I don't think I can help you with your missing file.  Sounds like the images and/or videos taken with your webcam are the ones OpenShot is having an issue with.  For now, you have a workaround running the files through a converter.

You may want to play with your webcam capture settings to see if you can modify it so that OpenShot can read it.
