### ISSUE TITLE
Confusing positioning and arranging the text via animating Title rendering what do I do ?

### ISSUE THREAD

**Issue by Harryortho** [OpenShot/openshot-qt#542]
**System Details:**
64bit
* Operating System / Distro: ?
Windows 10
* OpenShot Version: ?
2.2 from the OtherDownload section 21-March-2017 
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
I don't seem to understand how to make a simple title animation, what to expect it to look like, I want to write a title such as 'THE TIME A DOG DECIDED TO PLAY FOOTBALL' Then write it in Greek '.......'
I don't know how it will look initially and animate and I can't position the text or see how it will look.
In the end the text really does not show the way I intend it to.
I think it would be good to have a similar thing to what windows movie maker does where the text is positioned first and the size of it etc and then the animation can occur. There are no tutorials on this on youtube and as a newbie I am a bit lost as to what is wrong.

**Comment by Harryortho** [comment]
for example, when I want to write text that is several words long, the renderer places the words on top of each other.
Also when I want to render moving text, for some reason the text seems to render such that only the top half is displayed at the bottom of the view.

**Comment by DylanC** [comment]
@Harryortho - Thanks for your feedback. We will work on improving the documentation and tutorials as the project progresses. Closing this ticket but your feedback will be taken on board.
