### ISSUE TITLE
Why the heck does it suddenly do this?

### ISSUE THREAD

**Issue by MesaBlack** [OpenShot/openshot-qt#5420]
**Describe the bug:**

At 7:58-9 pm CDT, I was gonna open up Openshot for a new video, but it closed on itself once it started running.

**Steps to reproduce the behavior:**
1. Go to the Openshot website
2. Click on Linux Terminal in ChromeOS
3. Paste in the downloader code and wait

**Expected behavior:**
The program shouldn't close by itself.

**System Details:**
- OpenShot Version 3.1.1: {{ log_context.openshot_qt_version 3.1.1 }}
- Operating System / Distro: ChromeOS

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

**Video:**
[files are discriminated by size, so here's a link](https://youtu.be/3LpvL7EGuBw)

**Comment by Colorjet3** [comment]
I am not familiar with ChromeOS.  Please see if this helps:  https://www.reddit.com/r/OpenShot/comments/liat5e/download_to_chrome_os/

Update:  https://www.openshot.org/user-guide/ <--- search for ChromeOS

**Comment by MesaBlack** [comment]
Deleted the qt and it works!
