### ISSUE TITLE
OpenShot sluit als het bestand geopend is. Ik zie de foto's end. die zijn toegevoegd en dan wordt pr...

### ISSUE THREAD

**Issue by asandersliemers** [OpenShot/openshot-qt#5431]
**Omschrijf het probleem**
A OpenShot sluit als het bestand geopend is. Ik zie de foto's end. die zijn toegevoegd en dan wordt programma afgesloten.

**Stappen om het probleem te reproduceren:**
1. Ga naar 'openshort app'
2. Klik op 'bestand openen.'
3. bestand wordt geopend
4. de muis blijft draaien, net of hij alles nog moet binnenhalen, ondertussen zie ik wel het gemaakte werk (foto's, overgangen, muziek etc)

**Verwacht gedrag**
Ik verwacht de het blijven draaien stopt en ik het gemaakte werk kan nakijken.

**Systeemgegevens**
- OpenShot Version: 3.1.1
- libopenshot Version:  0.3.2
- Platform: Windows-10-10.0.22621
- Processor: Intel64 Family 6 Model 154 Stepping 3, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['nl-NL', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Dagelijkse build: geverifieerd probleem bestaat nog steeds in de dagelijkse build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.1.1-daily-11796-d98b5f2f-8e9d7edc-x86_64.exe

**Logbestanden**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/aa4rfji7kq8knr6via73z7v71vxlj0bo/openshot-qt.zip) (9 KB)
- libopenshot.log: bestand te klein of leeg (niet geüpload)

**Uitzondering / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Naar keuze)
![openshot](https://github.com/OpenShot/openshot-qt/assets/153230250/6a8ed276-b730-46ca-abd6-bcf531084785)
![image](https://github.com/OpenShot/openshot-qt/assets/153230250/c84b3c40-9572-4c16-8b7e-d421048b5a50)

**Comment by Colorjet3** [comment]
Hello @asandersliemers 

Een van de bronbestanden veroorzaakt een probleem. We kunnen een paar dingen proberen. Maar voordat we iets doen, laten we dit doen:
1. Sluit OpenShot als deze actief is.
2. Maak een back-up van de map c:\users\gebruikersnaam\.openshot_qt.
3. Bewaar dit veilig voor het geval dat.

Optie 1
1. Sluit OpenShot als deze actief is.
2. Zorg ervoor dat u een back-up hebt gemaakt van de map c:\users\gebruikersnaam\.openshot_qt.
3. Verwijder de map c:\users\gebruikersnaam\.openshot_qt.
4. Start OpenShot en open uw project.


Optie 2 - Herstel uw project

1. Sluit OpenShot als deze actief is.
2. Ga naar de map c:\users\gebruikersnaam\.openshot_qt\recovery.
3. In deze map vindt u verschillende vermeldingen van uw project. Ze worden voorafgegaan door een willekeurig getal.
4. Zoek de meest recente en dubbelklik erop.
5. Als het project wordt geopend en OpenShot niet sluit/crasht, is dit een goede kopie.
6. Mogelijk bent u wat werk kwijtgeraakt, maar het grootste deel van uw project zou intact moeten zijn.
7. Als het probleem zich blijft voordoen, zorg er dan voor dat OpenShot is gesloten.
8. Ga nu naar de map .../Restore en probeer de volgende meest recente back-up.
9. Zodra u een exemplaar heeft gevonden waar u tevreden mee bent, voert u een Bestand | Project opslaan als... en sla het op over uw oorspronkelijke project.

Translated from English:
One of the source files is causing a problem. We can try a few things. But before we do anything, let's do this:
1. Close OpenShot if it is running.
2. Back up the c:\users\username\.openshot_qt folder.
3. Keep this safe just in case.

Option 1
1. Close OpenShot if it is running.
2. Make sure you have backed up the c:\users\username\.openshot_qt folder.
3. Delete the c:\users\username\.openshot_qt folder.
4. Launch OpenShot and open your project.


Option 2 - Restore your project

1. Close OpenShot if it is running.
2. Go to the c:\users\username\.openshot_qt\recovery folder.
3. In this folder you will find several entries of your project. They are preceded by a random number.
4. Find the most recent one and double-click it.
5. If the project opens and OpenShot does not close/crash, this is a good copy.
6. You may have lost some work, but the majority of your project should be intact.
7. If the problem persists, make sure OpenShot is closed.
8. Now go to the .../Restore folder and try the next most recent backup.
9. Once you've found one you're happy with, run a File | Save project as... and save it over your original project.

**Comment by Colorjet3** [comment]
No response from OP.
