### ISSUE TITLE
Provide "stuff" mode, in which a clip dropped on a track moves the clips on its right side and snug-fits all the clips again

### ISSUE THREAD

**Issue by raindropsfromsky** [OpenShot/openshot-qt#5448]
If a user wants to change the order of clips on a track, he has to follow a seven-step process:
1. Select the clip to be moved and move it to another track.
2. Choose the place where the clip is to be dropped, and select all the clips on the right.
3. Move all the clips to the right, to create a gap that's large enough to accommodate the clip to be inserted.
    If this gap turns out to be too small, the user has to repeat steps 2+3 again.
4. Drop the clip from the other track and attach it to the clip on the left.
5. Select all the clips on the right and move them against the inserted clip (to close the gap).
6. When the clip is moved, it leaves a gap behind. 
     To close it, the user selects all the clips on the right of the original position.
7. The user drags the stack till the gap is closed.

This is too tedious.

Instead, provide a "stuff" mode:
1. The user SHFT+clicks on the clip to be moved, and drags. 
2. He hovers the clip between any two clips.
   All the clips to the right of the joint automatically move just enough to make space for the clip being dropped. 
3. The user releases the clip, and it fits in the gap, leaving no space on either side.

Thus, the user just uses a single drag-n-drop operation to stuff a clip into a new position, leaving no gaps.
The entire stack closes all gaps automatically.

**NOTE:** Instead of SHFT, any other modifier key can be used (CTRL. ALT. SHFT+CTRL, ALT, etc.)

**Comment by raindropsfromsky** [comment]
Forgot to mention other possible use cases:

The user may drag-n-drop a clip from another track (it may not be from the same track). In that case, the gap left in the source track need not be addressed at all.

Similarly, the user may drag-n-drop a clip from the **Project files** panel. In this case also, a source track is not involved, so there is no gap to be filled up.

**Comment by Colorjet3** [comment]
Hello @raindropsfromsky.  I believe this goes with your "Pack" enhancment request - [#5451 ]

Please see these links:

https://trello.com/c/tyVbvi59/112-eliminating-blank-empty-spaces-in-between-clips

https://trello.com/c/2S00XNA9/151-ability-to-easily-insert-a-clip-or-set-of-clips-between-existing-clips-without-having-to-manually-shift-existing-clips-around-to

https://trello.com/c/wly7VcIS/2-snap-together-button

These are in the queue to be reviewed by the lead developer and once approved by him they will be in the queue to be worked on.)

**Comment by raindropsfromsky** [comment]
Thanks for the feedback!

Once again, sorry for the inconvenience.
I will be mindful to check Trello in the future.

**Comment by Colorjet3** [comment]
No worries @raindropsfromsky.  I am most certain that the this feature will be implemented as part of the new UI redesign phase.  No ETA at this time.
