### ISSUE TITLE
Track area with HiDPI

### ISSUE THREAD

**Issue by crouthamela** [OpenShot/openshot-qt#545]
**System Details:**
* Operating System / Distro: Ubuntu 16.04
* OpenShot Version: 2.2.0

**Issue Description and steps to reproduce:**
The track area in the lower half of the screen is very small on HiDPI screens and makes it difficult to use. Text is very small as well.
![screenshot from 2017-03-21 23-09-57](https://cloud.githubusercontent.com/assets/1750231/24180483/8e05e4aa-0e8b-11e7-9014-86e09b67f0a4.png)

**Comment by DylanC** [comment]
@crouthamela - Thanks for the feedback. We should look to enhance for UHD soon.
