### ISSUE TITLE
Please provide a "Pack" command to eliminate all gaps between clips in the selected track (to make it "gapless")

### ISSUE THREAD

**Issue by raindropsfromsky** [OpenShot/openshot-qt#5451]
After extensive editing, we often find that there are gaps between clips in our main track.

This may have happened because we have trimmed some of the clips, or we did not care to attach a clip to its predecessor clip, thus leaving a little gap.

It is tedious to move every clip one by one and snap it to the previous clip.

Let there be a "Pack" command to join all clips, and remove all the gaps in the track, to make it a "gapless" track.

**Comment by Colorjet3** [comment]
Hello @raindropsfromsky.  Thank you for submitting this enhancement request.

Many other users have requested this and related enhancements as well.

Please see these links:

https://trello.com/c/tyVbvi59/112-eliminating-blank-empty-spaces-in-between-clips

https://trello.com/c/2S00XNA9/151-ability-to-easily-insert-a-clip-or-set-of-clips-between-existing-clips-without-having-to-manually-shift-existing-clips-around-to

https://trello.com/c/wly7VcIS/2-snap-together-button

These are in the queue to be reviewed by the lead developer and once approved by him they will be in the queue to be worked on.

**Comment by raindropsfromsky** [comment]
Thanks for the info!

Sorry for the inconvenience!
Before making any suggestion, I search the existing suggestions, but somehow I didn't see a matching result!

Lesson learned: [Check Trello first!](https://trello.com/b/eHMqcIaf/backlog/table)

**Comment by Colorjet3** [comment]
Hello @raindropsfromsky.  This enhancement is now in the latest dev daily build.

The way it works is:
1.  "Remove Gap" function (Single) - If there is a gap between clips, you can right click on that gap and then sselect "Remove Gap".  This function will shift all clips to the right of the gap to the left snapping to the clip on the left. 
2.  "Remove All Gaps" - If you wish to remove all the gaps on a specific track, then right clik on the Track head (where it says Track 5, 4, etc.), then select "Remove All Gaps".  This will remove all gaps and snap all the clips on that track together and shifting them all to the left.
