### ISSUE TITLE
Export to root C:/ not allowed

### ISSUE THREAD

**Issue by leodf1** [OpenShot/openshot-qt#5457]
**Describe the bug:**
Export to C:/ root directory displays error message popup 'Could not open or write file'

**Steps to reproduce the behavior:**
1. Export project
2. Select C:/ destination
3. Commence export

**Expected behavior:**
Export should be allowed to any location on drive

**System Details:**
OpenShot Version: 3.1.1
libopenshot Version: 0.3.2
Platform: Windows-10-10.0.19041
Processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
Machine: AMD64
Python version: 3.8.9
Qt5 version: 5.15.2
PyQt5 version: 5.15.4
Qt Detected Languages: ['en-US']
LANG Environment Variable:
LOCALE Environment Variable:
Daily Build: Verified issue still exists in daily build: [http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.1.1-daily-11627-2034f45d-08c2cdd1-x86_64.exe](https://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.1.1-daily-11627-2034f45d-08c2cdd1-x86_64.exe)

**Log Files:**

**Exception / Stacktrace:**

**Screenshots:** (Optional)

![Screenshot (1983)](https://github.com/OpenShot/openshot-qt/assets/158619515/f1da4c6f-bab0-4934-a7e0-50b05c793058)

**Comment by Colorjet3** [comment]
Most likely the user account does not have permission to create a file.  This happens to me also in Windows 11.

Try this:
1.  Start File Explorer.
2.  Navigate to c:\
3.  Right click an empty area and select New.
4.  Note that you only have the option of creating a Folder and not a file.
5.  OpenShot is experiencing the same issue.

**Comment by leodf1** [comment]
You are correct. Before posting, I checked the security permissions of the root directory and they looked ok.

After further investigation, it appears since Windows 8, C: root folder is write blocked from the registry.

Thanks
