### ISSUE TITLE
Saludos tengo problema al Instalar OpenSHOT

### ISSUE THREAD

**Issue by luisito2210** [OpenShot/openshot-qt#547]
**System Details: Windows 7
* OpenShot Version2.2 y 2.1 : ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

Sale este mensaje
![error de open shot 2 1](https://cloud.githubusercontent.com/assets/26639591/24276729/1c6f64e4-100f-11e7-8886-80ec49c7f1ad.JPG)
![error de open shot 2 1](https://cloud.githubusercontent.com/assets/26639591/24276741/2e565370-100f-11e7-8fc8-bd244e0a70cc.JPG)

**Comment by DylanC** [comment]
@luisito2210 Please note this installation issue has been solved in later builds. I recommend to try a new version.
