### ISSUE TITLE
Imported videos have audio sped/pitched up

### ISSUE THREAD

**Issue by RoselleCorin** [OpenShot/openshot-qt#5472]
**Describe the bug**
Imported videos have audio pitched up (think chipmunks) and sped up, while the visual part of the video remains unchanged. This causes the audio to lag out after about 10 seconds, making the audio stutter and break off. This 10-second interval happens at whatever timestamp I start from (so, if I start at the 3-minute mark, then from 3:00 to about 3:10, the audio will play sped up, and then start to lag out. This effect can be seen in the video preview *and* via the Preview Video option in the context menu (right click).

The visual part of the video remains unchanged throughout.

Note: this happens in a brand new project with zero edits. The files aren't corrupted as they play via WMP without issue, and when uploaded to Google Drive, the videos play unaffected.

I'm honestly thinking it's something to do with my copy of the program, but I've uninstalled and reinstalled it multiple times. I don't know what's wrong.

**Steps to reproduce the behavior:**
1. Open a new project.
2. Import a video file.
3. Move video file to timeline.
4. Hit play, see error.

**Expected behavior**
The video should be added to the timeline and not have any audio lag or pitch-shift. 

**System Details**
- OpenShot Version: 3.1.1
- libopenshot Version:  0.3.2
- Platform: Windows-10-10.0.22621
- Processor: AMD64 Family 25 Model 80 Stepping 0, AuthenticAMD
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.1.1-daily-11796-d98b5f2f-8e9d7edc-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/4btpilg14i4ewarnvmgtaej9y30g8880/openshot-qt.zip) (29 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/4btpilg14i4ewarnvmgtaej9y30g8880/libopenshot.zip) (0 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
I recorded a short video of what it looks like: [**Describe the bug**
Imported videos have audio pitched up (think chipmunks) and sped up, while the visual part of the video remains unchanged. This causes the audio to lag out after about 10 seconds, making the audio stutter and break off. This 10-second interval happens at whatever timestamp I start from (so, if I start at the 3-minute mark, then from 3:00 to about 3:10, the audio will play sped up, and then start to lag out. This effect can be seen in the video preview *and* via the Preview Video option in the context menu (right click).

The visual part of the video remains unchanged throughout.

Note: that this happens in a brand new project with zero edits. The files aren't corrupted as they play via WMP without issue, and when uploaded to Google Drive, the videos play unaffected.

I'm honestly thinking it's something to do with my copy of the program, but I've uninstalled and reinstalled it multiple times. I don't know what's wrong.

**Steps to reproduce the behavior:**
1. Open a new project.
2. Import a video file.
3. Move video file to timeline.
4. Hit play, see error.

**Expected behavior**
The video should be added to the timeline and not have any audio lag or pitch-shift. 

**System Details**
- OpenShot Version: 3.1.1
- libopenshot Version:  0.3.2
- Platform: Windows-10-10.0.22621
- Processor: AMD64 Family 25 Model 80 Stepping 0, AuthenticAMD
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.1.1-daily-11796-d98b5f2f-8e9d7edc-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/4btpilg14i4ewarnvmgtaej9y30g8880/openshot-qt.zip) (29 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/4btpilg14i4ewarnvmgtaej9y30g8880/libopenshot.zip) (0 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
I recorded a short video of what it looks like: https://www.loom.com/share/4720788ea54648408578325f0803d68d?sid=728242a7-a5b8-4cef-aee3-24e196af5691](https://www.loom.com/share/4720788ea54648408578325f0803d68d?sid=728242a7-a5b8-4cef-aee3-24e196af5691)

**Comment by Colorjet3** [comment]
1.  Close OpenShot if running.
2.  Make a backup of c:\users\username\.openshot_qt folder.
3.  Delete c:\users\username\.openshot_qt folder.
4.  Start OpenShot and open your project.
5.  did your audio issue get resolved?

If you are still having issues:
1.  Are you using headphones?  If yes, remove the headphones, restart Openshot and test again.
2.  Does this happen with one file or other files as well?
3.  What type of file(s) are you working with (.mp4? .mov? etc?).

**Comment by RoselleCorin** [comment]
> 1. Close OpenShot if running.
> 2. Make a backup of c:\users\username.openshot_qt folder.
> 3. Delete c:\users\username.openshot_qt folder.
> 4. Start OpenShot and open your project.
> 5. did your audio issue get resolved?
> 
> If you are still having issues:
> 
> 1. Are you using headphones?  If yes, remove the headphones, restart Openshot and test again.
> 2. Does this happen with one file or other files as well?
> 3. What type of file(s) are you working with (.mp4? .mov? etc?).

Okay, went through the first steps, it was still broken. I turned off my headphones, turned off the audio mixer that comes with my headphones (Steelseries runs the Arctis off of a program called GG, which splits audio into one of several channels, which can output to multiple sources simultaneously). Then unplugged my speakers that were going through the 3.5mm jack. 

It plays normally through my laptop's shitty speakers. Why is this? Is there a way to work with the headphones? Having to remove practically everything to hear the audio on a file that I'm working on seems a bit out there. My laptop's speakers are also half-broken and distort the sound. Is there a patch or workaround that you know of?

To answer the other two questions, it's happened with multiple MP4s, and I think with one MOV, but I had deleted that file, thinking it was corrupted. I don't know about any others, though.

**Comment by RoselleCorin** [comment]
I guess the most frustrating part is that it worked fine when i worked on the original file, the night before this problem showed up; but I saw I had an update to the program, and it broke only after I installed the update. I have no idea what version I was on though, to try to provide more info/context :/

Edit: I should probably at least try to be clearer about the sequence of events. Worked on a file on Friday on an unknown version of OpenShot, and while exporting the final video, I went and downloaded the update and waited for the file to finish exporting before installing the update. Installed the update and set it aside. This morning, the client wants a change to the video, and I wind up having this issue. So, whatever happened between November (the last time i had to edit a video for them) and now broke it.

**Comment by Colorjet3** [comment]
Hello @RoselleCorin.  Microsoft made a change with one of the Windows Updates in Windows 10 about a year ago that affected the audio sample rate.  OpenShot had to be changed as well on how it matched this sample rate so a many changes were made in OpenShot v3.1.1.  

You were most likely running v2.6.1.  To upgrade properly you needed to cleanup the .../.openshot_qt folder (see my instructions).

I really appreciate that you removed the headphones and the mixer just so that we can troubleshoot and it looks like it plays ok through your crappy speakers (😉 ).

So here is what needs to happen:
1.  Close OpenShot if running.
2.  Make another backup of c:/users/username/.openshot_qt folder.
3.  Delete c:/users/username/.openshot_qt folder.
4.  go to openshot.org/download/#daily and get the latest DEV daily build available (v3.1.1).  There are many bug fixes and a few enhancements in this version.
5.  Do not plug in your headphones yet.
6.  Install the downloaded binary and start OpenShot.
7.  Open your project and ensure everything is ok.
8.  Close OpenShot.
9.  Plug in your headphones.
10. Start OpenShot and open your project.
11.  How is the audio now?

**Comment by leodf1** [comment]
As an aside, the manual pg.129 'Matching Rates', states mismatched audio sample rate setting  "can lead to
 audio pops,mis-alignments....in the real-time video preview'. This would be the setting under Preferences - Preview.

Just an FYI and future reference, anyone might want to check if that matches the sample rate of the media.

**Comment by Colorjet3** [comment]
So, did my suggestion work?  That is what doing those steps would have done.  OpenShot v3.1.x was rewritten to match the audio sample rate in Edit | Preferences to the Windows Default Audio Sample rate.

Keep in mind that if you change your Default audio device in Windows, you need to restart Openshot for it to match that device audio sample rate.  It can not do it dynamically.

You also have the option to change the way OpenShot communicates with your Windows default audio device if you are still experiencing issues.  Go to Edit | Preference and check the "Playback Audio Device".  This setting defaults to "Default".  If you click on it you will have other options:  "Windows Audio:...." or "Direct Sound:..." <===Several options of each.  If you have to make changes then restart OpenShot before testing.

**Comment by Colorjet3** [comment]
Hello @RoselleCorin.  Any update on this?

**Comment by RoselleCorin** [comment]
Hi @Colorjet3 Sorry about the crazy delay, ever had your life turned tail over end? 

I just managed to sit down and work on this again, and the 11-step suggestion didn't fix the issue. I also took a look at the preferences for the playback audio. I changed it and restarted openshot like it requested, but the change I applied didn't stick (it switches it back to Default after I restart it, rather than my headset, which I selected). It's got about 18 different options, so I'll have to tinker with it, so more testing will happen.

**Comment by RoselleCorin** [comment]
> As an aside, the manual pg.129 'Matching Rates', states mismatched audio sample rate setting "can lead to audio pops,mis-alignments....in the real-time video preview'. This would be the setting under Preferences - Preview.
> 
> Just an FYI and future reference, anyone might want to check if that matches the sample rate of the media.

hi @leodf1 Thanks for the input. I didn't know there was a manual, just tutorials. I did go looking for the manual just now, and found a webpage for the [User Guide](https://www.openshot.org/user-guide/?app-menu), but it doesn't have page numbers. I searched the database and found a snippet of text that reads:

> It is very important to match your source assets FPS and Sample Rate with your Project FPS and Project sample rate. If either rate does not match exactly, it requires lots of additional CPU and RAM for OpenShot to normalize the mismatching rates. This can lead to audio pops, mis-alignments, duplicate frames, and extra lag in the real-time video preview. You can right-click a file and choose File Properties, to inspect the source asset rates, and ensure they match your Project settings (shown at the top of OpenShot). See [Properties](https://www.openshot.org/static/files/user-guide/files.html#file-properties-ref).

I'm hoping you mean this? If there's another area I should be taking a look at, please let me know. 

I'm not sure what the (encoding? settings?) are for openshot by default, but I haven't changed them. This seems to happen for both audio and video files. The information listed in the bar at the top has video information ("HD 720p 30 fps"), but the audio file I imported today looks like this, and i'm not sure how that's supposed to look, or what to change it to.
![image](https://github.com/OpenShot/openshot-qt/assets/161371336/9bb74cd5-99dd-4807-9521-602a2eb331c2)

I also created the second video file in openshot that I tried to edit (which wound me up with this issue), so I'm not sure that the properties of the file and of openshot would be desynced. Do you have any idea what I might need to change these settings to?

**Comment by Colorjet3** [comment]
Thank you @RoselleCorin about all the information you provided.  Please provide me with the following:

1.  A screen shot of what you see in Windows audio devices.  Go to Control Panel | Hardware & Sound.  In the Sound section click on "Manage audio devices".  I would like to see a screen shot of the Playback tab.  Be sure to scroll down if the list is long and take another screen shot if needed.

2.  A screen shot of what you see in OpenShot:  Edit | Preferences | Preview tab.  Be sure to scroll down if the list is long and take another screen shot if needed.

3.  What is the audio sample rate of your headphone in the Windows environment (Control Panel | Hardware & Sound | "manage audio devices".   Find your Headphone (It should have the green check mark indicating it is the Default output device).  Select it and click on Properties, then Advanced tab.  In the "Default Format" what do you see for "Select the sample rate and bit....."?

I am also curios to know what device you used to record your video/audio content?  I ask because I noted in the image you shared that you file property for the audio is a single channel, Mono, with a bit rate of 126250.

**Comment by Colorjet3** [comment]
No response from OP.

**Comment by 0mrcat** [comment]
> No response from OP.

okay, so I am having the same problem and i decided to give you the information you needed. Also, disclaimer -my language is polish but it shouldn't be hard to make out what I'm showing from the context. If you need any help translating, I can help you ofc
Your video editor is exactly what I have been looking for and I'm really looking forward to using it. Could you please reopen the issue if that's not a problem?
<img width="402" height="278" alt="Image" src="https://github.com/user-attachments/assets/a980b812-b7d8-4069-a8dc-cf3efd1c4df5" />
<img width="402" height="278" alt="Image" src="https://github.com/user-attachments/assets/2d86c7ae-9da0-4767-a1de-48eb40b63d83" />
<img width="402" height="278" alt="Image" src="https://github.com/user-attachments/assets/238e0318-425e-4102-98c7-9adaf2ac64e5" />
and the "sample rate and bit"
<img width="357" height="98" alt="Image" src="https://github.com/user-attachments/assets/db5d2d20-bbd4-4fe8-b931-108abf7ed196" />

It would be useful to mention, that its a virtual audio device, not the direct audio device cause of steelseries GG (which is the program I'm running trough, same as the  OP)

**Comment by Colorjet3** [comment]
No worries @0mrcat 
1.  Which version of Windows are you running (windows 10? windows 11?).
2.  Which version of OpenSHot are you running (help | about OpenShot)?  I recommend for now to update to the latest dev daily version so we can troubleshoot with that before needing to get the lead developer involved.  You can find the latest dev daily build at openshot.org/download/#daily.
3.  In OpenSHot, go to Edit | Prefernces | Preview tab.
4.  For the "Playback Audio Device", change that from the Default to one of the "Windows Audio: devicename" options that are available.  When you make the change, be sure to restart OpenShot and test.

Let me know the result.

**Comment by 0mrcat** [comment]
> No worries [@0mrcat](https://github.com/0mrcat)
> 
>     1. Which version of Windows are you running (windows 10? windows 11?). (Im running on Windows 11)
> 
>     2. Which version of OpenSHot are you running (help | about OpenShot)?  I recommend for now to update to the latest dev daily version so we can troubleshoot with that before needing to get the lead developer involved.  You can find the latest dev daily build at openshot.org/download/#daily. (I downloaded and installed OpenShot-v3.5.1-x86_64)
> 
>     3. In OpenSHot, go to Edit | Prefernces | Preview tab.
> 
>     4. For the "Playback Audio Device", change that from the Default to one of the "Windows Audio: devicename" options that are available.  When you make the change, be sure to restart OpenShot and test. (Did that, unfortunately, it did not help)
> 
> 
> Let me know the result.
Still the problem persists. 
here is a footage of the preview of OpenShot of me sucking at Tboi:

https://github.com/user-attachments/assets/76979ab9-d5af-4ff4-aea6-6f5fe86227a0

**Comment by Colorjet3** [comment]
Did you update to the latest dev daily build of OpenSHot from openshot.org/download/#daily?  Please confirm the build number from the About OpenShot screen.

Did you try the different "Playback Audio Device" options?

**Comment by 0mrcat** [comment]
I'm sorry for the delay. Yes I updated just now to the latest dev daily build of openshot
(OpenShot-v3.5.1-dev-daily-16275-0751153d-48516e0b-x86_64.exe (64-bit) | May 10, 2026, 2:52 p.m.)

<img width="554" height="349" alt="Image" src="https://github.com/user-attachments/assets/f7350832-b507-46ed-8c65-705e511140b3" />
I have tried different audio devices, the exclusive ones too but that just made me not hear anything.

**Comment by 0mrcat** [comment]
okay, turns out i had to change my preview sound frequency to 96000, matching my headphones
