### ISSUE TITLE
File cannot be found by OpenShot after being saved multiple times

### ISSUE THREAD

**Issue by margot-dbz** [OpenShot/openshot-qt#5473]
**Describe the bug:**
I created the osp file today. I saved it and reopened it multiple time and it did work. Few hours later, I cannot open the file anymore. 
the software says: file cannot be found. 
when I open it with a text, I can see the codes from my videos. It is not an empty file. 
Can you please help?

Mac Sanomat 14.2.1 (23C71)
software - latest version installed today

**Steps to reproduce the behavior:**
1. Open the software
2. Click on file > open projects > select projects
3. I get "file cannot be found" when earlier it was found
4. I cannot cancel the file opening action, it loops endlessly, even if I click cancel... until I force quit the software. 

Note: I cannot open the file .osp from my computer folders. 

**Expected behavior:**
It should always been able to open a saved file (.ops) ...which has been opened and saved multiple times today. 

**System Details:**
- OpenShot-v3.1.1-x86_64

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

How to get it on mac?

**Comment by Colorjet3** [comment]
Does it actually say "File can not be found" or are you getting "Missing File" message?  If "Missing File" message then this means you did one of the following after you imported your file(s) into OpenShot:  Deleted, renamed it, or moved it to another location.

Please read this:  https://github.com/OpenShot/openshot-qt/wiki/Missing-File-Prompt.  It is a bit long but you need to understand it as you create more projects using OpenShot (this applies to other editors as well, however, they might handle it differently).

**Comment by margot-dbz** [comment]
We get the "file can not be found". I will read your link and come back to you if the bug still occurs. Thanks

**Comment by Colorjet3** [comment]
Helo @margot-dbz.  Any update on this?  If the Missing File article provided you the understanding of the error message and the resolution then you or I can close this ticket.

**Comment by margot-dbz** [comment]
Hi, It was not the same issue I think but we just did a new video and it worked. You can close the ticket. thanks for your help
