### ISSUE TITLE
Captions oriented wrongly for vertical format video

### ISSUE THREAD

**Issue by Noreaster76** [OpenShot/openshot-qt#5476]
**Describe the bug:**
When adding a caption to a vertical format video, the caption does not respect the video orientation.

**Steps to reproduce the behavior:**
1. Create a video with a vertical profile, such as `HD Vertical 720p 30 fps`.
2. From the Effects tab, drag the "Caption" effect onto the video track in the timeline.
3. Caption is displayed vertically, along the long edge of the video, which would be appropriate for a horizontal video profile but not for a vertical one.

**Expected behavior:**
The caption should always be displayed along the bottom edge of the video, regardless of whether the video profile is horizontal (most cases) or vertical (less common).

**System Details:**
- OpenShot Version 3.1.1
- Operating System / Distro: macOS Sonoma 14.2.1

**Screenshots:**
<img width="961" alt="Screenshot_2024-03-05_at_10_59_38 AM" src="https://github.com/OpenShot/openshot-qt/assets/344851/00b0f473-2de1-45c5-a175-d7b540415279">

**Comment by Colorjet3** [comment]
Hello @Noreaster76.  Please do this:

1.  Right Click on the letter C (Caption effect) and select Properties.
2.  In the Properties window find the "Apply Before Clip Keyframes" and change it from "Yes" to "No".
3.  This should take care of the issue.

Please confirm.

**Comment by Colorjet3** [comment]
Hello @Noreaster76 Any update on this?

**Comment by Colorjet3** [comment]
No Response from OP.
