### ISSUE TITLE
mp4 file, duration 02:00:57 and size 2.85 GB, closes the application

### ISSUE THREAD

**Issue by G1anko** [OpenShot/openshot-qt#5478]
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/14572133/openshot-qt.log)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/14572138/libopenshot.log)

**Describe the bug:**
mp4 file, duration 02:00:57 and size 2.85 GB, closes the application

**Steps to reproduce the behavior:**
1. Go to 'Import files'
2. Click on 'Add to timeline'
3. crash the application
I download the file from here
https://www.facebook.com/549148373/videos/368068012878113/

**Comment by Colorjet3** [comment]
1.  What version of OpenShot are you running (Help | About Openshot?)
2.  What operating system/version are you running (Windows 10 Pro?  Ubunut 23.10? etc?).
3.  How much free hard disk space do you have?
4.  What are your computer specs (CPU, GPU/RAM, RAM, Hard disk drive type)?

By the way, we are unable to downlod the file to test with it.

**Comment by G1anko** [comment]
1. What version of OpenShot are you running (Help | About Openshot?)
      - OpenShot-v3.1.1-daily-11796-d98b5f2f-8e9d7edc (64-bit)
2. What operating system/version are you running (Windows 10 Pro? Ubunut 23.10? etc?).
      1. Windows 11 Pro (23H2)
      2. Windows 10 Pro (22H2)
3. How much free hard disk space do you have?
      1. 122 GB free
      2. 127 GB free
4. What are your computer specs (CPU, GPU/RAM, RAM, Hard disk drive type)?
      1. *CPU:* 12th Gen Intel(R) Core(TM) i7-1255U 1.70 GHz - *GPU/RAM:* Intel Iris Xe Graphics (Alder Lake-P 282 GT2), 1 GB - *RAM:* 16 GB - *Hard disk drive type:* 512 GB SSD PCIe NVMe (Lenovo V17 G3 IAP Laptop - Type 82U1)
      2. *CPU:* Intel(R) Core(TM) i7-7700 CPU 3.60 GHz - *GPU/RAM:* Intel HD Graphics 630 (Kaby Lake-S GT2), 1 GB - *RAM:* 16 GB - *Hard disk drive type:* 500 GB SSD SATA (Fujitsu ESPRIMO P757)

You can download the file for testing with https://clipgrab.org or https://www.4kdownload.com/downloads/34
Thanks!

By the way, the file is processed without problem with Microsoft Clipchamp

**Comment by fortnern** [comment]
I get a similar crash, here is the console output. 
OpenShot 3.1.1 from Flatpak, I get a similar error using the version in the OpenSUSE Tumbleweek repo. Video files are mp4 files (HEVC I think) from a GoPro Hero 9. They play fine in VLC.

```INFO files_listview: Processing drop event for 1 urls
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55c88eefe880] Using non-standard frame rate 59/1
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55c88f106040] Using non-standard frame rate 59/1
INFO files_model: Imported media file /home/nfortne2/Videos/1_1_24/GX010229.MP4
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fce600058c0] Using non-standard frame rate 59/1
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fce6000d940] Using non-standard frame rate 59/1
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fce6000d940] Using non-standard frame rate 59/1
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fce60349b00] Using non-standard frame rate 59/1
Caught signal 11 (SIGSEGV)
---- Unhandled Exception: Stack Trace ----
  /usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0 ( PyTuple_New                               + 0x18  )  [0x7fcfdd514ad8]
  /app/lib/python3.10/site-packages/_openshot.so ( swig::SwigPyForwardIteratorOpen_T<std::_Rb_tree_iterator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, swig::from_oper<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::value() const  + 0x1f  )  [0x7fcfdc19342f]
  /app/lib/python3.10/site-packages/_openshot.so (                                           + 0xaf93b)  [0x7fcfdc0af93b]
  /usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0 (                                           + 0x17a394)  [0x7fcfdd57a394]
  /usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0 ( _PyEval_EvalFrameDefault                  + 0x44f8)  [0x7fcfdd472148]
  /usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0 (                                           + 0x1ca405)  [0x7fcfdd5ca405]
  /usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0 ( _PyEval_EvalFrameDefault                  + 0x7386)  [0x7fcfdd474fd6]
  /usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0 (                                           + 0x1ca405)  [0x7fcfdd5ca405]
  /usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0 ( _PyEval_EvalFrameDefault                  + 0x688b)  [0x7fcfdd4744db]
  /usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0 (                                           + 0x1ca405)  [0x7fcfdd5ca405]
  /usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0 (                                           + 0x140fd0)  [0x7fcfdd540fd0]
  /usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0 ( _PyEval_EvalFrameDefault                  + 0x688b)  [0x7fcfdd4744db]
  /usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0 (                                           + 0x1ca405)  [0x7fcfdd5ca405]
  /usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0 ( _PyEval_EvalFrameDefault                  + 0x7386)  [0x7fcfdd474fd6]
  /usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0 (                                           + 0x1ca405)  [0x7fcfdd5ca405]
  /usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0 ( _PyEval_EvalFrameDefault                  + 0x7386)  [0x7fcfdd474fd6]
  /usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0 (                                           + 0x1ca405)  [0x7fcfdd5ca405]
  /usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0 ( _PyObject_FastCallDictTstate              + 0x69  )  [0x7fcfdd539799]
  /usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0 ( _PyObject_Call_Prepend                    + 0xff  )  [0x7fcfdd539a8f]
  /usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0 (                                           + 0x170445)  [0x7fcfdd570445]
  /usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0 (                                           + 0x127042)  [0x7fcfdd527042]
  /usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0 ( _PyObject_MakeTpCall                      + 0x9c  )  [0x7fcfdd53961c]
  /usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0 ( _PyEval_EvalFrameDefault                  + 0x7898)  [0x7fcfdd4754e8]
  /usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0 (                                           + 0x1ca405)  [0x7fcfdd5ca405]
  /usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0 ( _PyEval_EvalFrameDefault                  + 0x7386)  [0x7fcfdd474fd6]
  /usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0 (                                           + 0x1ca405)  [0x7fcfdd5ca405]
  /usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0 (                                           + 0x140f3e)  [0x7fcfdd540f3e]
  /usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0 ( _PyEval_EvalFrameDefault                  + 0x44f8)  [0x7fcfdd472148]
  /usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0 (                                           + 0x1ca405)  [0x7fcfdd5ca405]
  /usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0 ( _PyEval_EvalFrameDefault                  + 0x7386)  [0x7fcfdd474fd6]
  /usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0 (                                           + 0x1ca405)  [0x7fcfdd5ca405]
  /usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0 ( _PyEval_EvalFrameDefault                  + 0x7386)  [0x7fcfdd474fd6]
  /usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0 (                                           + 0x1ca405)  [0x7fcfdd5ca405]
  /usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0 (                                           + 0x141063)  [0x7fcfdd541063]
  /usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0 (                                           + 0x1f947d)  [0x7fcfdd5f947d]
  /usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0 (                                           + 0x7d14c)  [0x7fcfdd47d14c]
  /usr/lib/x86_64-linux-gnu/libc.so.6 (                                           + 0x8f25a)  [0x7fcfdd08f25a]
  /usr/lib/x86_64-linux-gnu/libc.so.6 ( clone                                     + 0x44  )  [0x7fcfdd117bb4]
---- End of Stack Trace ----
QObject::killTimer: Timers cannot be stopped from another thread
QObject::~QObject: Timers cannot be stopped from another thread```

**Comment by Colorjet3** [comment]
Hello @G1anko .  I am unable to download your file to test with.  Worse yet, the ClipGrab tool has malware in it and you should be removing it from your post and find another way to share your file so we can test with it.

**Comment by fortnern** [comment]
If you have somewhere I can upload my file I can do so. It's 320 MB.

**Comment by Colorjet3** [comment]
Hello @fortnern I just sent you a link to a google drive location where you can upload your file to.  I sent the link to nfort***@hdf*****.org.

**Comment by fortnern** [comment]
> Hello @fortnern I just sent you a link to a google drive location where you can upload your file to. I sent the link to nfort***@hdf*****.org.

Done, thanks

**Comment by Colorjet3** [comment]
Hello @fortnern.  I just downloaded the file your shared with me and I am able to import it into OpenShot and preview it without any issues.  I see that it is a 45 minute bike trail video.

I tested both in Windows 11 Pro and Ubuntu 23.10.  I do not have OpenSuse to test with.

Please give this a try:
1.  Close Openshot if running.
2.  make a backup of /home/username/.openshot_qt folder.
3.  delete /home/username/.openshot_qt folder.  Hang on to your backup from step 2 for a while. 
4. Go to openshot.org/download/#daily and download the latest DEV Daily Build AppImage available.
5.  Make it executable and run it.
6.  Import your video file and try again.

**Comment by Colorjet3** [comment]
Hello @G1anko.  Please give the latest DEV Daily Build a try as well.  Since you are running Windows please do this:

Please give this a try:
1.  Close Openshot if running.
2.  Go to add or remove programs and uninstall OpenShot.  If you see multiple entries uninstall all.
3.  make a backup of c:\users\username\.openshot_qt folder.  Hang on to this for a while.
4.  delete c:\users\username\.openshot_qt folder. 
5. Go to openshot.org/download/#daily and download the latest DEV Daily Build available.
6.  Install it and start OpenShot.
7.  Import your video file and try again.

**Comment by fortnern** [comment]
@Colorjet3 the AppImage build doesn't work for me, there's a glibc version mismatch or something like that. If I delete .openshot_qt and run the flatpak install, I get the same error. I'm happily using shotcut now but I can continue debugging if you want me to.

**Comment by Colorjet3** [comment]
Hello @fortnern.  Are you positive that you downloaded the latest DEV Daily Build AppImage?  The latest dev daily build had a specific fix for the glibc version mismatch.

Please be sure you are going to openshot.org/download/#daily.  Here you should find build #11909.  Once you download the AppImage, make it executable and run it.  To confirm you have build #11909 go to Help | about OpenShot after you start OpenShot and confirm you see build #11909.

I really appreciate you making the time to test.

I am also glad that Shotcut is working for you.

**Comment by fortnern** [comment]
@Colorjet3 

> Hello @fortnern. Are you positive that you downloaded the latest DEV Daily Build AppImage? The latest dev daily build had a specific fix for the glibc version mismatch.
> 
> Please be sure you are going to openshot.org/download/#daily. Here you should find build #11909. Once you download the AppImage, make it executable and run it. To confirm you have build #11909 go to Help | about OpenShot after you start OpenShot and confirm you see build #11909.
> 
> I really appreciate you making the time to test.
> 
> I am also glad that Shotcut is working for you.

That worked, I can run build 11909 and it opens the file just fine. Thanks so much! (And sorry for reporting a bug that's been fixed)

**Comment by Colorjet3** [comment]
No worries @fortnern and glad things are working for you.
