### ISSUE TITLE
Cannot change OpenShot language (2.2.0 Windows 10)

### ISSUE THREAD

**Issue by ktecho** [OpenShot/openshot-qt#548]
**System Details:**
* Operating System / Distro: Windows 10 latest
* OpenShot Version: 2.2.0 (stable)

**Issue Description and steps to reproduce:**
I'm using a Windows 10 in spanish language. OpenShot opens in spanish too. I want to change it to english language because some stuff is badly translated. I cannot. I try with _Edit / Preferences_ and then I choose American English (en_US). When I press "Exit" button, it says you need to restart OpenShot. I restart it but it's still in spanish.

**Comment by Storm-Engineer** [comment]
My whole system (Linux) is English, I do not use Hungarian anywhere, yet OpenShot is in Hungarian and it cannot be changed.

Where the hell does it even get the Hungarian from??? Does it check for my physical location or what?

**Comment by JoelVEDY** [comment]
OpenShot started with language set to Danish after installation. I changed to American English (en_US) and restarted, but OpenShot was still in Danish.

**Workaround:**
Change Language to British English (en_GB) and restart, and OpenShot runs in English.

**System Details:**
- OpenShot Version: 2.3.1
- OS: Windows 10 Enterprise
- Windows OS Language: English (United States)
- Windows Keyboard: Danish
- Windows Region Location: Denmark
- Windows Region Format: Danish

**Comment by DylanC** [comment]
@ktecho - I saw another bug with similar information like this. Seems to be a known issue.

**Comment by DylanC** [comment]
Dup of #331

**Comment by peanutbutterandcrackers** [comment]
A commit has recently been made to the source code that should fix this. Could you please try out the latest [daily build](https://github.com/OpenShot/openshot-qt/releases/tag/daily) and see if this problem still persists or not? Thank you! :)

**Comment by ktecho** [comment]
@peanutbutterandcrackers  I've just tested with 2.4.1 (oficial, not daily) and it's working ok. I've just changed to British English (it was difficult to find it, maybe should be English (british) or something) and after reboot OpenShot, it's in english. Changed it to Default again and after reboot it's in spanish.

So I don't know what that commit is about, but it's working in 2.4.1.  :)

**Comment by peanutbutterandcrackers** [comment]
Oh. Okay. The commit should fix another problem where en_US wasn't working right for some reason. So, yeah...

I'm glad that this is working for you. Hope you create awesome videos with OpenShot!

Please do not forget to close this issue, if it has been resolved. Thanks! :)

**Comment by ktecho** [comment]
Yeah, it's closed. Thanks!!

**Comment by peanutbutterandcrackers** [comment]
Awesome! Please do keep on supporting OpenShot! :)
