### ISSUE TITLE
OpenShot can't open videos recorded by Zoom

### ISSUE THREAD

**Issue by dhdaines** [OpenShot/openshot-qt#5480]
MP4 files recorded by Zoom do not open in OpenShot.  All I see is a black screen in the preview.  Pressing the "play" button does nothing.

This is on Ubuntu 23.10, with OpenShot 2.6.1 (installed from openshot-qt .deb) and 3.1.1 (installed from snap store).

Easy to reproduce!  Record a video with zoom and try to import it ... useless!

**Comment by Colorjet3** [comment]
Please give this a try:
1.  Close OpenShot if running?
2.  Make a backup of /home/username/.openshot_qt folder.
3.  Delete /home/username/.openshto_qt folder.
4.  Run OpenShot v3.1.1
5.  Open your project or start a new project and import your .mp4 file.
6.  Preview it.  Did it work?  If not, continue...DO NOT GO BACK TO v2.6.1 at this time.
7.  Close OpenShot.
8.  Go to openshot.org/download/#daily and download the latest DEV Daily Build AppImage.
9.  Make it executable and run it.
10. Open your project or import your .mp4 file and preview.  Did this work?  If not, continue....
11.  Run your .mp4 file through converter like VLC, Handbrake, or ShutterEncoder and convert it to a .mp4 file, but obviously with a new name.
12. Import this new file into OpenShot and see if if it now works.

**Comment by dhdaines** [comment]
1-10: No, does not work.
11-12: Nope, still not working.

File plays fine in VLC and the default Gnome video player.

Converting it to `.mpeg` with ffmpeg ... still does not work.

**Comment by Colorjet3** [comment]
Thank you @dhdaines.

1.  Close Openshot if running.
2.  Go to openshot.org/download/#daily and download the latest DEV Daily Build AppImage.
3.  Make the AppImage executable and run it.
4.  Import your .mp4 file and the converted file and see if it works.

If not, please use VLC to convert your original .mp4 back to .mp4 then import this into the AppImage and see if an better.

**Comment by dhdaines** [comment]
Sorry if my last message wasn't clear, but I already did all those things, including the conversion of .mp4 to .mp4.

Here is what ffmpeg says about my video:

```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'video2240008906.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2024-03-17T16:53:03.000000Z
  Duration: 00:13:31.94, start: 0.000000, bitrate: 221 kb/s
  Stream #0:0[0x1](und): Audio: aac (LC) (mp4a / 0x6134706D), 32000 Hz, mono, fltp, 126 kb/s (default)
    Metadata:
      creation_time   : 2024-03-17T16:53:03.000000Z
      handler_name    : AAC audio
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 1680x1050, 93 kb/s, 25 fps, 25 tbr, 30k tbn (default)
    Metadata:
      creation_time   : 2024-03-17T16:53:03.000000Z
      handler_name    : H.264/AVC video
      vendor_id       : [0][0][0][0]
      encoder         : AVC Coding
```

**Comment by dhdaines** [comment]
Anyway I don't have any more time to mess around with software that clearly doesn't work.  At this point I'll just do the editing I need manually on the command line with ffmpeg.

**Comment by Colorjet3** [comment]
Understood @dhdaines.  If possible, share the file with me and I can play around with it.

**Comment by Colorjet3** [comment]
@dhdaines.  I went ahead and created a Zoom recording on my Windows 11 which then created the .mp4 file.
1.  On my Windows 11, I imported the .mp4 zoom recording and all is good.
2.  I have Ubuntu 23.10 running in an Oracle VirtualBox as guest on my Windows 11 host computer.  I imported this same .mp4 zoom recording in OpenShot AppImage Build #11796 and all works well as well.

So, I am unable to replicate your issue.  I do realize that my environment is slightly different than yours.  Most likely your host is Ubuntu 23.10 and assuming you are running Zoom on it and recording.

I'll keep this ticket open for a bit yet in hopes that you might share your .mp4 file so I can test with it.   If I don't get a response by next week then I will close it.

**Comment by Colorjet3** [comment]
Hello @dhdaines.  This post needs additional information to further troubleshoot.  Since you don't have time at the moment, I am going to close this ticket since I am unable to replicate your issue.  

If/when you have time to further troubleshoot, please feel free to reopen this ticket.
