### ISSUE TITLE
app crashes when running video stabilizer

### ISSUE THREAD

**Issue by Sal10** [OpenShot/openshot-qt#5483]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 3.1.1
- libopenshot Version:  0.3.2
- Platform: Windows-10-10.0.22621
- Processor: Intel64 Family 6 Model 183 Stepping 1, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.1.1-daily-11796-d98b5f2f-8e9d7edc-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/8hhykba4khiitl1u7fnjeij6a0h6cj5r/openshot-qt.zip) (20 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/8hhykba4khiitl1u7fnjeij6a0h6cj5r/libopenshot.zip) (0 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
Hello @Sal10.
Please provide the following:
1.  What operating system version are you running (windows 10 pro? windows 11 Pro? etc.?)
2.  It doesn't look like you enabled "Debug" mode to generate enough log file to troubleshoot this issue.  Please do this:
a.  Close OpenShot if running.  Stay with build #11796 (latest dev daily build).
b.  Open a cmd prompt.
c.  Navigate to c:\program files\openshot video editor folder.
d.  Type "openshot-qt-cli.exe --debug" excluding the quotes and press the Enter key.
e.  OpenShot will start.
f.  Open your project and perform the stabilizer effect again.
g.  When Openshot crashes, the command prompt window will stay open.  Using your mouse select all the content (with the mouse start your selection from the bottom of the command prompt screen and while highlighting, continue scrolling up with the mouse to capture everything and not just this window.
h.  After you select all, press the CTRL+A, CTRL +C, the paste it into notepad.
i.  Save this file and share it here.

If possible, share your video file so we can test with it as well.

**Comment by Colorjet3** [comment]
Hello @Sal10.  Any update on this?  I am going to close it but feel free to reopen if you still need assistance.
