### ISSUE TITLE
Can't interact with the 10th project file, under specific conditions

### ISSUE THREAD

**Issue by KiralyCraft** [OpenShot/openshot-qt#5488]
**Describe the bug:**
My display resolution is 2560 x 1080. I'm using OpenShot on this main window in a maximized form such that the project files pane contains lines of 10 tiles. Under these specific conditions, I cannot interact with the last element of the row. If I resize the Video Preview pane to allow for 11 elements to fit in the project files rows, then this issue does not happen. 

The issue also doesn't manifest if the window does not start in this form of 10-tile rows. I find it quite specific.

**Steps to reproduce the behavior:**
1. Create a project with at least 10 project files (my test worked with 11 pictures or one video and 10 pictures)
2. Shape the panels in such a way that the project files pane fits 10 columns exactly
3. Full screen the window to 2560 x 1080
4. Attempt to interact with the last element of the rows, like right clicking or attempt to drag

**Expected behavior:**
There should be no difference interacting with the last element compared to the others.

**System Details:**
```
INFO app: ------------------------------------------------
INFO app:             OpenShot (version 3.1.1)            
INFO app: ------------------------------------------------
INFO app: openshot-qt version: 3.1.1
INFO app: libopenshot version: 0.3.2
INFO app: platform: Linux-6.7.9-zen1-1-zen-x86_64-with-glibc2.39
INFO app: processor: 
INFO app: machine: x86_64
INFO app: python version: 3.11.8
INFO app: qt5 version: 5.15.11
INFO app: pyqt5 version: 5.15.10
```
- OS: Arch Linux with Wayland, KDE Plasma 6
- GPU: RX 580 with standard Mesa drivers

**Log Files:**
[logs.txt](https://github.com/OpenShot/openshot-qt/files/14822768/logs.txt)

**Exception / Stacktrace:**
None

**Screenshots:** (Optional)

https://github.com/OpenShot/openshot-qt/assets/10259742/62ef3649-cbdf-4c75-9810-4bccccce2aec

**Comment by Colorjet3** [comment]
Hello @KiralyCraft.  Please give the latest DEV Daily Build AppImage a try and see if the issue persists.
1. Go to openshot.org/download/#daily.
2. Download the latest DEV Daily Build AppImage.
3. Make it executable, run it and see if your issue persists.

If it does we will need to assign this to the lead developer.

**Comment by KiralyCraft** [comment]
It seems to work correctly with `OpenShot-v3.1.1-dev-daily-11909-a9e34a9b-8e9d7edc-x86_64.AppImage`, I can't reproduce the issue so far. I will test this build some more, as well as maybe give the AppImage version of my current build a shot, maybe the issue only happens on native builds. 

Thank you for pointing me in the right direction; I'll close this issue for now, and will use the AppImage to see if I can replicate the behavior long-term.
