### ISSUE TITLE
Choose the install location.

### ISSUE THREAD

**Issue by goldug** [OpenShot/openshot-qt#5494]
**Describe the new feature:**
Choose where OpenShot is going to be installed (Windows version)

**Describe the solution you'd like:**
I want to have the option to choose where OpenShot is installed. I don't want to install it to my C:\ drive.

**Describe alternatives you have considered:**
The only alternative is to not install it.

**Comment by Colorjet3** [comment]
If you already have it installed and either reinstalling or upgrading you may not be prompted for a location.

Please do this:
1.  Close openshot if running.
2.  go to add or remove programs and uninstall.
3.  go to c:\program files and look for "openshot video editor" folder.  If it is there then delete the entire folder and its contents.  You will need administrative rights to do this.
4. Now install OpenShot and you should be offered to install it in a different location (including a different drive).

**Comment by goldug** [comment]
I did not have it installed already. First time I installed it on this computer.

**Comment by Colorjet3** [comment]
I just re-installed again in my Windows 10 environment and it prompts me for the location.

1.  Where did you download OpenShot from?
2.  Go to openshot.org/download/#daily and download the latest dev daily build available.
3.  Uninstall the current version (I am assuming you went through the installation for the first time).
4.  Make a backup of c:\users\username\.openshot_qt folder.
5.  Delete c:\users\username\.openshot_qt folder.
6.  Install Openshot from step 2.

**Comment by Colorjet3** [comment]
Hello @goldug Any update on this?

**Comment by goldug** [comment]
Hey, sorry, got a lot going on now.
Yes, that worked. I have a feeling that I actually had used it several years ago and the .openshot_qt folder was there and made stuff weird. I know that I didn't have it on my C-drive back then, so it's weird that it chose to install it to the c-drive.

Anyway, sorry for taking your time.

**Comment by Colorjet3** [comment]
No worries @goldug and glad you have it working.  Good luck with your projects.
