### ISSUE TITLE
[solved][development] Can you provide mingw-python3.8 for win10  development?

### ISSUE THREAD

**Issue by 625781186** [OpenShot/openshot-qt#5498]
msys2 has not mingw-python3.8 ,  and I build mingw-python3.8 error (https://github.com/msys2-contrib/cpython-mingw/issues/171) .

So ,   Can you **package your c:/msys64   for me** , 

thanks .

![image](https://github.com/OpenShot/openshot-qt/assets/30521429/7f3ce7f9-179a-4e14-af51-115d3a7892b4)

![image](https://github.com/OpenShot/openshot-qt/assets/30521429/35dcab05-ab5b-4438-a4e7-7c899938a2d5)

**Comment by 625781186** [comment]
@Colorjet3  Hello , 

win 10 build Document is too old , Can you provide the latest compilation tutorial video?

[Some problems I encountered following the operations in the document](https://github.com/OpenShot/libopenshot/issues/951)

**Comment by Colorjet3** [comment]
Hello @625781186 I don't have the answer.  I have assigned this to the lead developer who should be able to provide you with the information you are asking for.

**Comment by 625781186** [comment]
I solved it using a special method to contribute to others  :

1 . 实际上应该编译这个仓库的python 3.8版本 ; 
 https://github.com/msys2/MINGW-packages/commits/master/mingw-w64-python 

2. 安装 openshot-qt.exe

4. 直接使用发布的lib , 编辑 D:\openshot-qt-3.1.1\src\launch.py

```python
sys.path.insert(0, r"C:\Program Files\OpenShot Video Editor\lib\library.zip")
sys.path.insert(0, r"C:\Program Files\OpenShot Video Editor\lib")
```
![image](https://github.com/OpenShot/openshot-qt/assets/30521429/ae7f1b8c-c9cb-4e7a-8f9b-ce9bb955c024)


5. 复制 C:\Program Files\OpenShot Video Editor\platforms 到 build出来的D:\MINGW-packages\mingw-w64-python\src\build-x86_64 路径 ;
6.  复制 C:\Program Files\OpenShot Video Editor\imageformats 到 build出来的D:\MINGW-packages\mingw-w64-python\src\build-x86_64 路径 ;

7.  运行
D:\MINGW-packages\mingw-w64-python\src\build-x86_64\python.exe D:\openshot-qt-3.1.1\src\launch.py

![image](https://github.com/OpenShot/openshot-qt/assets/30521429/d302a0f0-7771-47f5-a19d-ea0871129f86)

**Comment by Colorjet3** [comment]
Nice job @625781186 and thank you for posting your solution.

**Comment by along923928784** [comment]
> 我用一种特殊的方法解决了这个问题，希望能对其他人有所帮助：
> 
> 1. 注意应该编译这个仓库的python 3.8版本； https://github.com/msys2/MINGW-packages/commits/master/mingw-w64-python
> 
> 2. 安装 openshot-qt.exe
> 3. 直接使用发布的lib，编辑D:\openshot-qt-3.1.1\src\launch.py
> 
> sys.path.insert(0, r"C:\Program Files\OpenShot Video Editor\lib\library.zip")
> sys.path.insert(0, r"C:\Program Files\OpenShot Video Editor\lib")
> ![image](https://github.com/OpenShot/openshot-qt/assets/30521429/ae7f1b8c-c9cb-4e7a-8f9b-ce9bb955c024)
> 
> 5. 复制 C:\Program Files\OpenShot Video Editor\platforms 到 build 出来的 D:\MINGW-packages\mingw-w64-python\src\build-x86_64 路径 ;
> 6. 复制 C:\Program Files\OpenShot Video Editor\imageformats 到 build 出来的 D:\MINGW-packages\mingw-w64-python\src\build-x86_64 路径 ;
> 7. 运行
>    D:\MINGW-packages\mingw-w64-python\src\build-x86_64\python.exe D:\openshot-qt-3.1.1\src\launch.py
> 
> ![image](https://github.com/OpenShot/openshot-qt/assets/30521429/d302a0f0-7771-47f5-a19d-ea0871129f86)

能否提供一下mingw-w64-python3.8的环境包 有偿寻求帮助
