### ISSUE TITLE
backup.osp corrupted (title file missing), thereafter can not start openshot

### ISSUE THREAD

**Issue by jimav** [OpenShot/openshot-qt#5499]
Running the latest "daily" build (dated March 27, 2024, 3:07 p.m.):

Several times openshot froze and a popup asked whether to wait or force-quit.  "Wait" never worked and zero CPU was being used (except when the popup was waiting for an answer).

The nasty part is that after forcing quit,  the backup project is corrupted.  $HOME/.openshot_qt/backup.osp exists, but a Title file referenced by it is missing. The result is a SIGABORT after an "openshot::InvalidFile" exception.   Openshot can never again start unless $HOME/.openshot_qt/backup.osp is manually removed.

I will attach the console output which includes Python stack trace etc.

--> The bug might be related to trying to move the horizontal divider between the tracks on the bottom and the player window on the top, or maybe some other GUI layout adjustments.  When I grabbed the up/down arrow symbol with the mouse, the program froze.  However this was after  other anomalous behavior (two copies of a slice unexpectedly appeared *on top of each other* in the same track).  So it might have already been half-dead. 
This happened after typing 's' (perhaps more than once?) to slice at the current location.

It's not a one-off: This has happened to me three times after doing a lot of slicing and deleting and play/rewind etc.
Each time I lost a lot of work.

Sorry to not have more specific repro instructions.   The bug seems related to the sequence or speed of human input.

[Edit:] Also, I was working with a large (90 minute) video, and I noticed dragging the "playback head" over a large distance would not work, or the head would only move a short distance and I had to grab it again, etc. etc. -- so maybe some kind of race happened with the rendering machinery to destabilize the GUI.  Just a speculation of course.

**System Details:**
- OpenShot Version OpenShot-v3.1.1-dev-daily-11909-a9e34a9b-8e9d7edc-x86_64.AppImage
- Operating System: Ubuntu 23.10
- 
**Log Files:**
[console_capture.txt](https://github.com/OpenShot/openshot-qt/files/15020131/console_capture.txt)

**Comment by Colorjet3** [comment]
Hello @jimav.  I am going to play around with build #11909 in my test Ubuntu 23.10 environment (I am running 23.10 as guest in Oracle Virtualbox) to see if I can replicate the issue you mentioned.

Regarding the backups.  Obviously when an application freezes/crashing/unstable, it becomes unpredictable.  The backups may not be exactly to what you would expect.  You mention "backup.osp".  What you really should be looking for in /home/username/.openshot_qt/recovery folder is several .osp files that start with some numbers-yourprojectname.osp.  Depending on how long you have been working with your project you can have many of them.  Find the latest one and open it.  This should minimize the amount of work you may have lost.  This is also dependent on the settings in Edit | Preferences | Autosave tab.

For now, perform manual saves as often as possible to minimize loss of work.

I will update you on my findings in the next few days.

**Comment by jimav** [comment]
Question: Can the path to a .osp file be given on the command line?  The file picker used by File->Open Project refuses to access "hidden" directories like $HOME/.openshot_qt/recovery and so they can not be opened in the normal way.

**Comment by Colorjet3** [comment]
What happens if you navigate to your /home folder via the Files app, and then enable the "Show Hidden Files"?  This will expose the .../.openshot_qt folder and thus access to the Recovery folder.

**Comment by Colorjet3** [comment]
No response from OP
