### ISSUE TITLE
Openshot 2.2 for Windows 10 x64 is tremendously slow, often unresponsive. #bug

### ISSUE THREAD

**Issue by jebeld17** [OpenShot/openshot-qt#550]
**System Details:**
* Operating System / Distro: Windows 10 Pro x64.
* OpenShot Version: 2.2 for Windows x86_64.
* _Msinfo32 Export File Attached._
     [msinfo32.txt](https://github.com/OpenShot/openshot-qt/files/872830/msinfo32.txt)
* _Problem Steps via Microsoft Windows Problem Steps Recorder are also Attached._
     [ProblemSteps.zip](https://github.com/OpenShot/openshot-qt/files/872850/ProblemSteps.zip)

**Issue**
Openshot 2.2 for Windows 10 x64 is tremendously slow, especially when moving items on a track around and rearranging items. The program often is either unresponsive to commands (such as undo, cut, paste, etc.) leading to things needing to be done twice.

**Comment by jebeld17** [comment]
@ktecho is this similar to the issue you've been having?

**Comment by ktecho** [comment]
@jebeld17  No. For me it doesn't open sometimes. But I haven't done any video editing yet, so I don't know how that works.

**Comment by ankitpati** [comment]
Can you please try the [latest stable release](https://github.com/OpenShot/openshot-qt/releases/download/v2.3.1/OpenShot-v2.3.1-x86_64.exe "OpenShot 2.3.1"), and let us know if it works?

**Comment by AluminiumTech** [comment]
@ankitpati  I can confirm that similar issues occur in 2.3.1

**Comment by ankitpati** [comment]
@AluminiumTech Thank you for the report. We shall hopefully resolve it soon.

**Comment by jebeld17** [comment]
Similar issues are happening. The program is still freezing up on me whenever editing a video.

**Comment by petesimon** [comment]
similar problem for in v2.3.4 release (and v2.34 dev3, dev4, etc), in my Windows 10 x64 (1703). but other video editors such as Shotcut v17.08 and Videopad v5.xx work fine.

**Comment by DylanC** [comment]
@jebeld17 - Is the v2.4 daily build performing the same for you?

**Comment by EdGe7x** [comment]
Just adding my comments. I would live to use OpenShot regularly but it just lags and freezes all the time. Especially the preview, it just won't play so I can see the type of effects I am trying to implement. Also using Windows 10 x64, 8GB of Ram, SSD HDD. Version of OpenShot being used is 2.4.0.

**Comment by manylegged** [comment]
I am also experiencing extreme slowdowns on Win10/x64. The GUI hangs for 10-15 seconds after every timeline operation. I just installed openshot a few hours ago and have been using it to edit videos. I think it's getting worse fairly rapidly - when I started it was pretty responsive. 

The video I'm editing is 1:40 long and has 20 sections, all in one track. There are no transitions or anything. 

I tried attaching the visual studio debugger during a hang and stack traces pretty much look like this. Looks like something in python.

Let me know if there is anything else I can do to help.

	ntdll.dll!NtDelayExecution()	Unknown	Non-user code. Symbols loaded.
 	KernelBase.dll!00007ffc00ad7287()	Unknown	Non-user code. Cannot find or open the PDB file.
 	libpython3.5m.dll!000000006d72d3f0()	Unknown	No symbols loaded.
 	libpython3.5m.dll!000000006d6c6a26()	Unknown	No symbols loaded.
 	libpython3.5m.dll!000000006d6c7f9a()	Unknown	No symbols loaded.
 	libpython3.5m.dll!000000006d6c80c0()	Unknown	No symbols loaded.
 	libpython3.5m.dll!000000006d6334a3()	Unknown	No symbols loaded.
 	libpython3.5m.dll!000000006d60ac67()	Unknown	No symbols loaded.
 	libpython3.5m.dll!000000006d61f88a()	Unknown	No symbols loaded.
 	libpython3.5m.dll!000000006d60ac67()	Unknown	No symbols loaded.
 	libpython3.5m.dll!000000006d6bde07()	Unknown	No symbols loaded.
 	PyQt5.QtCore.pyd!000000006f23e801()	Unknown	No symbols loaded.
 	PyQt5.QtCore.pyd!000000006f23ec30()	Unknown	No symbols loaded.
 	PyQt5.QtCore.pyd!000000006f23edd1()	Unknown	No symbols loaded.
 	PyQt5.QtCore.pyd!000000006f2414ce()	Unknown	No symbols loaded.
 	PyQt5.QtCore.pyd!000000006f241656()	Unknown	No symbols loaded.
 	PyQt5.QtCore.pyd!000000006f182cf7()	Unknown	No symbols loaded.
 	Qt5Core.dll!00000000668e8a62()	Unknown	No symbols loaded.
 	Qt5Core.dll!000000006675e1d2()	Unknown	No symbols loaded.
 	msvcrt.dll!00007ffc01ebae06()	Unknown	Non-user code. Cannot find or open the PDB file.
 	msvcrt.dll!00007ffc01ebaedc()	Unknown	Non-user code. Cannot find or open the PDB file.
 	kernel32.dll!00007ffc01de2774()	Unknown	Non-user code. Cannot find or open the PDB file.
 	ntdll.dll!RtlUserThreadStart()	Unknown	Non-user code. Symbols loaded.

**Comment by DylanC** [comment]
@manylegged - Thanks for the stack trace. This is something we can investigate further.

**Comment by DylanC** [comment]
@manylegged - Was this OpenShot v2.4.0 or v2.4.1?

**Comment by manylegged** [comment]
I was using v2.4.0 when I captured the stack trace - however I just installed v.2.4.1 and I can confirm that it is still very slow when doing any timeline operations.

**Comment by DylanC** [comment]
@manylegged - No problem. Thanks.

**Comment by shenzj1994** [comment]
Same here. Any operations on timeline is extremely slow and makes this software completely unusable on Windows 10. Even if I only move the clip a little bit, do a drag-and-drop, any of these operations freeze the GUI for about 15s. Hopefully there would be a fix soon. Have to use other software to do my job now.
FYI, I was using 2.4.1.

**Comment by soccerguy243** [comment]
I have to click on picture, wait, drag, wait, drop, wait, move, wait.  Always waiting.  Windows even shows it as Unresponsive but I wait and it comes back.  :(

**Comment by DylanC** [comment]
Guys this is not a forum. If you have a detailed report to put in as an issue that is fine. Just saying it lags when doing anything does not help us at all.

This issue is a bit too vague anyway and out of date since the original reporter has not given recent feedback.

@manylegged - We will still use the stacktrace from this issue.
