### ISSUE TITLE
App crashing after opening specific project

### ISSUE THREAD

**Issue by zewargithub** [OpenShot/openshot-qt#5500]
**Describe the bug**
MP4 video,size approx 14GB, splitted.
Tried to export it many times but all was failed - the new MP4 file has no video or audio.
Then the same project is not opening, when I open through pressing the project, will open and crash in a second.
Opening application without loading this file is not an issue.
Tried to uninstall, delete the folder from users and program files, reinstall clean version - same issue.

**Steps to reproduce the behavior:**
Just open the .OSP file through clicking on it or through opening it after launching the app

**Expected behavior**
I expect to be able to edit, and export it to MP4 file!

**System Details**
Edition	Windows 11 Home
Version	23H2
OS build	22631.3447
Experience	Windows Feature Experience Pack 1000.22688.1000.0

Processor	13th Gen Intel(R) Core(TM) i7-1355U   1.70 GHz
Installed RAM	16.0 GB (15.7 GB usable)

System type	64-bit operating system, x64-based processor

- OpenShot Version: 3.1.1-dev
- libopenshot Version:  0.3.2
- Platform: Windows-10-10.0.22621
- Processor: Intel64 Family 6 Model 186 Stepping 3, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.1.1-dev-daily-11909-a9e34a9b-8e9d7edc-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/0thq2f8e4equ2fq0gsu9qv9zywngf8pi/openshot-qt.zip) (63 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/0thq2f8e4equ2fq0gsu9qv9zywngf8pi/libopenshot.zip) (29 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
Please try this:
1. Close Openshot if running.
2. Uninstall openshot via Add or Remove Programs.  Note:  If you had upgraded from a previous version (v2.5.x or v.6.x) then you might see additional entries for OpenShot.  Uninstall all that you see.
3. Make a backup of c:\users\username\.openshot_qt folder.  Hang on to this for a while.
4. Delete c:\users\username\.openshot_qt folder.
5. Go to openshot.org/download/#daily and get the latest DEV Daily Build.
6. Install it and start OpenShot.
7. See if you can open your existing project.  If success then skip the rest of the steps.
8. If not, then there could something that is difficult to recover from.
9. Close openshot.
10. Go to the backup folder from step 3.  Find the .....\recovery folder.
11. In this folder look for files names start with bunchofnumbers_yourprojectname.osp.  There can be several depending on how long you've been working with your project.
12. Find the most recent and double click on it.
13. Repeat step 12 until one works for you (it could be the first one you try).
14. If/when the project opens you may lose some work but you get most of it back.
15. When you are satisfied with the recovery, perform File | Save Project As.... and save it to its original location overwriting your corrupt project....OR, just create a new project name and delete the old content (.osp and accompanying assets folder).

**Comment by zewargithub** [comment]
Thank you for your reply. It didn't work. The issue is that I deleted c:\users\username.openshot_qt folder before posting here.

**Comment by Colorjet3** [comment]
Hello @zewargithub When you say it didn't work, you mean the "recovery" because you had already deleted the .../openshot_qt folder.  Correct?

What happened when you downloaded the latest dev daily build and then imported your 16GB file?  Did this part work?  If yes, then just move forward with your project.

What type of a video file are you working with (.mov?  .mp4? etc?).  An option might be to run your source video file through a converter like VLC, Handbrake, or ShutterEncoder and convert it to .mp4 file (even if the source file is .mp4).  Obviously create a new file name if the original is a .mp4.  Now import this newly created .mp4 file into OpenShot.

**Comment by zewargithub** [comment]
Hello @Colorjet3  Thank you for your reply,

1: The recovery folder is empty because I already deleted it before posting.

2: After downloading the latest dev daily build, it's the same behaviour. When I just open it, then it's ok. When trying to load the file after opening, or opening it directly, it's crashing.

3: It was a .mp4 file. The issue is that I saved the split one over the original (replaced the file), so I don't have the source file anymore. I only have the ".osp" project and the extracted file, which doesn't have audio or video.

**Comment by Colorjet3** [comment]
Well, it is going to be difficult to further troubleshoot without the original source video file.  Not sure where to go from here.

Is there any way that you can get the original source file back?

**Comment by zewargithub** [comment]
I wish, but I don't have it. It was just recorded. I didn't expect this.

**Comment by Colorjet3** [comment]
Hello @zewargithub I am closing this ticket.  Feel free to reopen if the issue comes back.
