### ISSUE TITLE
Flatpak release is missing several effects, stabilizer for example

### ISSUE THREAD

**Issue by JPT77** [OpenShot/openshot-qt#5504]
**Describe the bug:**
Several effects are missing from the flatpak build, one of these is stabilizer. For the others see pics below.

**Steps to reproduce the behavior:**
Open effects tab, see list of video effects

**Expected behavior:**
stabilizer available

**System Details:**
Flatpak: OpenShot Studios, LLC                              org.openshot.OpenShot                                   3.1.1                     stable                  system
Kubuntu 23.10, kernel 6.5.0-28-generic

**Screenshots:** 
![openshot-flatpak](https://github.com/OpenShot/openshot-qt/assets/4168125/f72adba1-0c9b-45ce-99ff-1d5af15b3dbc)
![openshot-appimage](https://github.com/OpenShot/openshot-qt/assets/4168125/a6bf0d4e-ebfb-45c8-a324-857315f3da0b)

First image from flatpak installation, second image from appimage installation.

While the appimage package still suffers from https://github.com/OpenShot/openshot-qt/pull/5423 flatpak release got this problem. Why hasn't the app image fix been released yet? (I cannot find any info on which branch or release the fix is assigned to)

**Comment by Colorjet3** [comment]
Please download the latest dev daily build AppImage and see if that has the missing effect(s).

1.  Go to openshot.org/download/#daily and download the latest DEV Daily Build AppImage.
2.  Make it executable and run it.
3.  Verify all effects are available.

**Comment by jonoomph** [comment]
Yes, we really need to release our next production version, to get many fixes out into the wild. This will happen very soon. Apologies for the delay on this release.

**Comment by jonoomph** [comment]
Also, we don't officially support the Flatpak version, so I can't really help with that. But we do officially support the AppImage.

**Comment by JPT77** [comment]
Thank you very much. I am using the Appimage version until the flatpak version is fixed. 
As about the comment by @Colorjet3 : The stable appimage release is not missing any filters. the flatpak release is. 

Until now I very often heard the phrase "flatpak version is not supported".
could you please explain why that is?
Where do I find who is responsible for flatpak releases?
flatpak is a very convenient way of maintaining and updating software that does not come from the distribution's sources. Manjaro even integrates flatpak update into the system update process.

**Comment by Colorjet3** [comment]
Hello @JPT77 I followed up with the lead developer and it is challenging to identify who maintains flatpak for different distros.

I am going to close this ticket since the lead developer has mentioned OpenShot officially support AppImage and not Flatpak.
