### ISSUE TITLE
Latest AppImage doesnt start

### ISSUE THREAD

**Issue by Moshe-Shelomov** [OpenShot/openshot-qt#5507]
**Describe the bug:**
Appimage isnt starting

**Steps to reproduce the behavior:**
Try to launch latest appimage

**Expected behavior:**
The program starts

**System Details:**
- OpenShot Version 3.1.1 (Latest version from the website)
- Endeavour OS (Arch-based), with KDE 6 as desktop environment

When trying to run the program through the terminal (to see what is the problem exactly) I receive this output:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/cx_Freeze/initscripts/__startup__.py", line 40, in run
  File "/usr/local/lib/python3.8/dist-packages/cx_Freeze/initscripts/Console.py", line 37, in run
  File "openshot_qt/launch.py", line 55, in <module>
    from PyQt5.QtWidgets import QApplication
ImportError: /tmp/.mount_OpenShbA4XYs/usr/bin/libm.so.6: version `GLIBC_2.35' not found (required by /usr/lib/libharfbuzz.so.0)

For the time being I downloaded the latest dev version from website (the one uploaded on march 27th) and it seems to work

**Comment by Colorjet3** [comment]
You need to download the latest DEV Daily build AppImage and not the production AppImage.

1. Go to openshot.org/download/#daily.
2. Download the latest dev daily build appimage.
3. make it executable and run it.

Update:  You need libfuse2 installed for the AppImage to run.  It could be missing depending on what version of Linux you are running.

**Comment by Colorjet3** [comment]
Hello @Moshe-Shelomov I haven't seen a response on this.  I am closing this ticket but feel free to reopen if you need further assistance.
