### ISSUE TITLE
I cannot launch Openshot on my Computer

### ISSUE THREAD

**Issue by CFrederik** [OpenShot/openshot-qt#5509]
**Describe the bug:**
After installing Openshot on my new computer, it does not want to start! I have tried downloading the regular download as well as the daily builds specifically the following below, but it still does not work. I have also ensured that all the media packages are installed ergo that Windows Media Player is enabled. 
Daily Build Version tested: 
- [OpenShot-v3.1.1-dev-daily-11909-a9e34a9b-8e9d7edc-x86_64.exe (64-bit)](https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v3.1.1-dev-daily-11909-a9e34a9b-8e9d7edc-x86_64.exe)

**Steps to reproduce the behavior:**
1. Go to https://www.openshot.org/download/
2. Click on "Download v.3.1.1" for windows
4. Confirm all the Download requirements
5. Attempt to launch Openshot
6. Nothing happens

**Expected behavior:**
I would expect Openshot to open up and start running

**System Details:**
- OpenShot Version [v3.1.1]
- Operating System / Distro: Microsoft Windows 11 Home Version 10.0.22631 Build 22631
- System Type: x64-based
- Processor: AMD Ryzen 9 7845HX with Radeon Graphics, 3001 Mhz, 12 Cores

**Comment by Colorjet3** [comment]
Since you are running Windows 11 Home Version you may need the Windows Media Feature Pack.

Please see https://support.microsoft.com/en-us/windows/media-feature-pack-for-windows-n-8622b390-4ce6-43c9-9b42-549e5328e407

**Comment by Colorjet3** [comment]
No response from OP.
