### ISSUE TITLE
glitch

### ISSUE THREAD

**Issue by Kribirr** [OpenShot/openshot-qt#5510]
**Describe the bug:**

**Steps to reproduce the behavior:**

**Expected behavior:**

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by Kribirr** [comment]
i have a raw file of my video of 1080p at 30fps. when I import it in openshot and editing using it, it was glitching , i thought its just the preview but when i exported it, the video still glitched. i saw the raw file , it didnt had any glitch. I delted and installed openshot 5 times, but the problem is same

**Comment by Colorjet3** [comment]
1.  go to openshot.org/download/#daily and download the latest dev daily build AppImage.
2.  make the appimage executable and run it.
3.  Let us know if it works any better.

**Comment by Colorjet3** [comment]
Hello @Kribirr Any update on this?  I am going to close this since no response but feel free to reopen if the issue persists.
