### ISSUE TITLE
Preview audio plays FAST! 

### ISSUE THREAD

**Issue by mkubiak402** [OpenShot/openshot-qt#5512]
in the edit mode previewing the video the sound plats at 100x it is doing it on 3 computers I have. 
i also did a reinstall and it did not fix any thing. 

**System Details:**
Windows 11
AMD R9 9500x 
Nvidia RTX 3070x
32gb 
Realtek sound

Windows 10
intel i7 7700k 
Nvidia 1080ti
Realtek sound

Windows 10
AMD fx-8320 
Nvidia 970
Realtek sound

- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Log Files:**
No crashing

**Comment by Colorjet3** [comment]
1.  What kind of a video/audio or audio file are you working with (.mp4? .mov? .mp3? etc.)?
2.  Can you share one of those video files so we can test with it?
3.  Does this happen with other video files or just this one?
4.  Are you using headphones?  If yes, unplug the headphones, restart OpenShot, and preview again.
5.  On one of the computers, give this a try:
a.  close Openshot if running?
b.  go to add or remove programs and uninstall OpenShot.
c.  delete c:\users\username\.openshot_qt folder.
d.  go to openshot.org/download/#daily and download the latest DEV Daily Build available.
e.  install the latest dev daily build.
f.  Start Openshot, import your video file, and preview.
g.  did this fix the issue?

**Comment by mkubiak402** [comment]
1. they are downloads from YouTube and videos from OBS so MP4 and MKV files.
3. Happens with every video file. 
4. no PC speakers
B: did not fix it
C: did not fix it
D:  I uninstalled and installed the "OpenShot-v3.1.1 11909 64.exe (64-bit March 27, 2024," same problem.
G no still have the same problem.

**Comment by Colorjet3** [comment]
Try running your source file through a converter like HandBrake, ShutterEncoder, or VLC and convert it to .mp4 file even if the original is a .mp4 but obviously with a new name.  Now import this new .mp4 file into OpenShot and try again.

By the way, stay with build #11909 as it has many other bug fixes and a few enhancements over the production release.

**Comment by Colorjet3** [comment]
Hello @mkubiak402 I haven't seen a response from you on this:

1.  There is a newer daily build that you should download and try:  openshot.org/download/#daily.
2.  Have you tried running your source file through a converter?

I am closing this ticket due to no response but feel free to reopen if you still need assistance.

**Comment by mkubiak402** [comment]
Nothing fixed it I just un-installed it and using some thing else.

**Comment by Colorjet3** [comment]
Thank you @mkubiak402 for the FYI.  

One last question:  What is your output device?  Is it headphones or speakers?  No worries if you no longer want to pursue this.
