### ISSUE TITLE
Unable toi open a video mp4 file created by Zoom.  Your open source competitors (such as VidCutter) ...

### ISSUE THREAD

**Issue by cyberoldie** [OpenShot/openshot-qt#5513]
I start your program from the most recent version and lick the green plus symbol to open the file for editing.  The file shows in the upper left window and the timeline opens.  There is no thumbnail for the file in the timeline.

Using any of the navigation symbols does not move the timeline index cursor and nothing shows in the upper right window,

**Expected behavior**

**System Details**
- OpenShot Version: 3.1.1
- libopenshot Version:  0.3.2
- Platform: Windows-10-10.0.22000
- Processor: Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.1.1-dev-daily-12180-d73763f1-5e9fa273-x86_64.exe

**Log Files**
- openshot-qt.log: File too small or empty (not uploaded)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/815odmwfuaci048e3hiaz6sf4k2fxxoj/libopenshot.zip) (5 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by cyberoldie** [comment]
[OpenShot Screen Grabs.pdf](https://github.com/OpenShot/openshot-qt/files/15295637/OpenShot.Screen.Grabs.pdf)

Screen shots added

**Comment by cyberoldie** [comment]
Why is this flagged as closed sincde I just opened it

**Comment by Colorjet3** [comment]
Hello @cyberoldie.  This ticket shows as being open, to me.

1.  What type of a file does Zoom recording create (.mp4? .mkv? etc?).
2.  Are you able to open this same file in VLC or Windows Media Player?
3.  Doe you get any error message when you try to import it?  If yes, what is the message?
4.  Can you share your file with us so we can test with it?

One thing you can try is to run your Zoom recording through a converter like HandBrake, ShutterEncoder, or VLC and convert it to .mp4 even if the source file is .mp4 but obviously with a new name.  Now import this into OpenShot.

**Comment by Colorjet3** [comment]
Closed ticket due to "No response from OP"

**Comment by cyberoldie** [comment]
I sent mhy response and never heard back

**Comment by cyberoldie** [comment]
This item is not closed.  The failure exists and the requested information was sent

**Comment by cyberoldie** [comment]
This is my second response to your inquiry.  See inline comments below.

**Comment by Colorjet3** [comment]
Hello @cyberoldie.  My apologies for not seeing your initial responses and thank you again for sharing them.

I don't have an easy way to share files.  If you have Google Drive or Microsoft OneDrive you can share your file with me (raffi@openshot.org) and I can play with your file to see if I can make it work for you.  Create a folder in your google drive or OneDirve and give me Read access only.

**Comment by cyberoldie** [comment]
The file has been shared with you in DropBox and you should receive an email with instructions for accessing the file.

**Comment by Colorjet3** [comment]
Thank you for the file.  I'll play around with it and get back to you with
my results.

**Comment by Colorjet3** [comment]
Hello @cyberoldie.  Thank you for sharing your .mp4 file with me.

I just imported your file into OpenShot.  I can confirm that there is no Thumbnail showing in the "Project Files" window or when I drag it onto the timeline.  However, I am not having any issues previewing the clip in OpenShot.  I haven't done any editing at this time but I was able to save the project.

I tried running your .mp4 file through a converter like ShutterEncoder and created a new .mp4 file and imported that into OpenShot with the same results.

So, I went forward and did some edits:
1.  Sliced the clip.
2.  Adjusted the volume on one section.
3.  Added a Blur effect to another section.
4.  Added some captions, and text.

I had no issues with any of the above animations.  I am running Windows 11 Pro with the latest Microsoft updates.  My hardware drivers are all up-to-date as well.  I am also running OpenShot v3.1.1 build #12180.  This build is the latest dev daily build and not the production release.

Let's try this:
1.  Close OpenShot if running.
2.  Go to Add or Remove Programs and Uninstall Openshot.  If you had upgraded from a previous version there is a chance that you might see two entries for OpenShot.  Uninstall any entries of OpenShot.
3.  Make a backup of c:\users\username\.openshot_qt folder.
4.  Delete c:\users\username\.openshot_qt folder.
5.  Ensure that you local drive where you are running OpenShot from has plenty of free disk space.  If not, free up as much as possible.
6.  go to openshot.org/download/#daily and download the latest dev daily build.
7.  Install the latest dev daily build.
8.  Start OpenShot...don't open your project yet.
9.  With a new project, import your source file that you shared with me and let me know how it works.

There are a few Cache preference settings that I will share with you since you are somewhat working with a large source file to better fine tune OpenShot.

Please share with me your computer specs (CPU, RAM, GPU/RAM, Hard disk type and how much free disk space you have).

**Comment by Colorjet3** [comment]
Hello @cyberoldie I am closing this ticket since I have not heard back from you.  Feel free to reopen if you need further assistance.  If you have already resolved your issue then it would be nice if you share the solution as it will help others.

**Comment by cyberoldie** [comment]
Good day,

I regret not being able to get back to you.  There have been illnesses and two deaths with which I have had to deal with.

  Please consider re-opening this.

As to the feedback you sent,

1.	The file I sent you would not load in the program.  It was not that there was no preview, it was that the program froze.
2.	I will try this week to follow your suggestion of deleting the software and downloading answer release from GitHub and get back to you.  If I do this will there be an image in the viewer with which I can work?

Thank you.

 

David M. Baum

tel: +1.703.634.9966 | fax:+1.703.832.2288 

Post Office Box 1276

McLean, VA 22101-1276

 

Please consider the environment before printing this email

NOTICE

This electronic transmission is intended for the addressees named above. It may contain information that is privileged, proprietary, or otherwise protected from use and disclosure. If you are not the intended recipient, or the authorized agent of the intended recipient, you are hereby notified that any review, disclosure, copying, or dissemination of this transmission, or the taking of any action in reliance on its contents, or other use is strictly prohibited and may result in civil liability and/or criminal sanctions. If you have received this transmission in error, please notify the sender that this message was received in error and then delete this message and any copies thereof.

**Comment by cyberoldie** [comment]
> Hello @cyberoldie. Thank you for sharing your .mp4 file with me.
> 
> I just imported your file into OpenShot. I can confirm that there is no Thumbnail showing in the "Project Files" window or when I drag it onto the timeline. However, I am not having any issues previewing the clip in OpenShot. I haven't done any editing at this time but I was able to save the project.
> 
> I tried running your .mp4 file through a converter like ShutterEncoder and created a new .mp4 file and imported that into OpenShot with the same results.
> 
> So, I went forward and did some edits:
> 
> 1. Sliced the clip.
> 2. Adjusted the volume on one section.
> 3. Added a Blur effect to another section.
> 4. Added some captions, and text.
> 
> I had no issues with any of the above animations. I am running Windows 11 Pro with the latest Microsoft updates. My hardware drivers are all up-to-date as well. I am also running OpenShot v3.1.1 build #12180. This build is the latest dev daily build and not the production release.
> 
> Let's try this:
> 
> 1. Close OpenShot if running.
> 2. Go to Add or Remove Programs and Uninstall Openshot.  If you had upgraded from a previous version there is a chance that you might see two entries for OpenShot.  Uninstall any entries of OpenShot.
> 3. Make a backup of c:\users\username.openshot_qt folder.
> 4. Delete c:\users\username.openshot_qt folder.
> 5. Ensure that you local drive where you are running OpenShot from has plenty of free disk space.  If not, free up as much as possible.
> 6. go to openshot.org/download/#daily and download the latest dev daily build.
> 7. Install the latest dev daily build.
> 8. Start OpenShot...don't open your project yet.
> 9. With a new project, import your source file that you shared with me and let me know how it works.
> 
> There are a few Cache preference settings that I will share with you since you are somewhat working with a large source file to better fine tune OpenShot.
> 
> Please share with me your computer specs (CPU, RAM, GPU/RAM, Hard disk type and how much free disk space you have).

I have performed all the steps that you suggested.  I used the latest GitHub DailyDev as of today.
The video file loads with no thumbnaill and does not play so I cannot edit it. 
 You did not provide me with the preference settings that you mentioned  so I was unable to change any preferences.
Any further suggestions.
My machine is Windows 11 Enterprise.  8 GB RAM and i7-8705G  processor.
46.2 GB free disk of 80 GB

**Comment by Colorjet3** [comment]
Hello @cyberoldie I am sorry about the life challenges that you have to deal with.

Please confirm for me which build # you have installed.
1.  Start OpenShot.
2.  Click on Help | About Openshot.
3. You should see "OpenShot-v3.1.1-dev-daily-99999-.....".  I need to confirm the value of 99999.

The Preferences settings should not have bearing on the thumbnail.  I want to resolve your issues before making other changes.

I see that you are running Windows 11 Enterprise edition.  Is this in a work environment?  If yes, do you have Microsoft Group Policies applied to your environment that possibly may be causing security issues (accessing data)?

**Comment by cyberoldie** [comment]
The number is 12440

As to your question about Active Directory Group Policy Objects, I am the Domain Administrator, and this machine is not in a group that gets any policies.

Furthermore, I made a Virtual Machine in VMWare to makae an isolated sandbox and the same problems exist there.

I can add more processor threads in the VM to test if that helps, and I can up the RAM to as high as 50GB (it’s a 64 GB RAM host).  Also, I can build a VM with other Windows versions if that would help.

While I can live without a thumbnail in the Project Files window, not seeing anything in the Video Preview window is not workable, and not being able to play the video is not much help either.  I really appreciate your working with me.  I have seen you product in a colleagues office and really like it. My wife and I are on the Board of a charity helping people whose lives are affected by Parkinson’s Disease and we have a number of meeting  videos to edit.

 

David M. Baum

tel: +1.703.634.9966 | fax:+1.703.832.2288 

Post Office Box 1276

McLean, VA 22101-1276

 

Please consider the environment before printing this email

NOTICE

This electronic transmission is intended for the addressees named above. It may contain information that is privileged, proprietary, or otherwise protected from use and disclosure. If you are not the intended recipient, or the authorized agent of the intended recipient, you are hereby notified that any review, disclosure, copying, or dissemination of this transmission, or the taking of any action in reliance on its contents, or other use is strictly prohibited and may result in civil liability and/or criminal sanctions. If you have received this transmission in error, please notify the sender that this message was received in error and then delete this message and any copies thereof.

**Comment by cyberoldie** [comment]
Still awaiting your reply and resolution of the documented problem.

David Baum

 

From: David Baum ***@***.***> 
Sent: Saturday, June 15, 2024 16:36
To: 'OpenShot/openshot-qt' ***@***.***>
Subject: RE: [OpenShot/openshot-qt] Unable toi open a video mp4 file created by Zoom. Your open source competitors (such as VidCutter) ... (Issue #5513)

 

The number is 12440

As to your question about Active Directory Group Policy Objects, I am the Domain Administrator, and this machine is not in a group that gets any policies.

Furthermore, I made a Virtual Machine in VMWare to makae an isolated sandbox and the same problems exist there.

I can add more processor threads in the VM to test if that helps, and I can up the RAM to as high as 50GB (it’s a 64 GB RAM host).  Also, I can build a VM with other Windows versions if that would help.

While I can live without a thumbnail in the Project Files window, not seeing anything in the Video Preview window is not workable, and not being able to play the video is not much help either.  I really appreciate your working with me.  I have seen you product in a colleagues office and really like it. My wife and I are on the Board of a charity helping people whose lives are affected by Parkinson’s Disease and we have a number of meeting  videos to edit.

 

David M. Baum

tel: +1.703.634.9966 | fax:+1.703.832.2288 

Post Office Box 1276

McLean, VA 22101-1276

 

Please consider the environment before printing this email

NOTICE

This electronic transmission is intended for the addressees named above. It may contain information that is privileged, proprietary, or otherwise protected from use and disclosure. If you are not the intended recipient, or the authorized agent of the intended recipient, you are hereby notified that any review, disclosure, copying, or dissemination of this transmission, or the taking of any action in reliance on its contents, or other use is strictly prohibited and may result in civil liability and/or criminal sanctions. If you have received this transmission in error, please notify the sender that this message was received in error and then delete this message and any copies thereof.

**Comment by cyberoldie** [comment]
Still awaiting your response to my reply to the questions you raised below

**Comment by Colorjet3** [comment]
Hello @cyberoldie.

There is a new release of openshot (v3.2.1).

Please perform a [Clean Installation](https://github.com/OpenShot/openshot-qt/wiki/Clean-Installation-of-OpenShot) and try again.

I would also try installing a Windows 11 Pro (not enterprise edition) and do NOT join the domain to test this latest openshot release.

**Comment by cyberoldie** [comment]
I only have w11 ENT machines.  Since some are not in domain I can use one of those.

Sent from a cellphone by dictation. Please excuse any errors 
________________________________

**Comment by cyberoldie** [comment]
What about a linux machine?

Sent from a cellphone by dictation. Please excuse any errors 
________________________________

**Comment by Colorjet3** [comment]
What is the exact question about Linux?  Are you asking if you can run OpenShot in Linux?  The answer yes and I recommend Ubuntu.  I also recommend that you download the AppImage and not try the PPA installation as it may not be up-to-date yet with version 3.2.1.

If this is not what you are asking then please provide some more details about what your question is regarding Linux.

**Comment by cyberoldie** [comment]
Yes that was the question.  After I try the latest Windows vedrsions that you suggested, I may try Open Shot on Ubuntu Cinamon

**Comment by Colorjet3** [comment]
Ubuntu is the most supported platform for OpenShot.  Make sure to download the AppImage.  Do not try the PPA installation or via the software manager as they may not be up-to-date yet (v3.2.1).

1.  download the AppImage.
2.  make it executable.
3.  Run it.

**Comment by cyberoldie** [comment]
Good afternoon,

1.	On a NON-Domain joined Windows 11 Enterprise machine with 8 processors and 8GB of RAM, and 59.6 GB of 80 GB hard disk free, I installed the software from your website.
2.	The version information displayed by HELP, ABOUT is as follows:

a.	

3.	I opened a new project and hit the green plus key to open the MP4 file.  The same results as previously reported were observe – the MP4 file did not open, even after waiting 30 minutes.
4.	I then obtained a new Windows11Pro image and installed it.  It is Version 213H2, installed pn a machine with 8GB of RAM and 31 GB free of 65DB hard disk space.
5.	The screenshot of the desktop was the same as obtained from #3 above, and it is:
6.	

 

Any suggestions?
David Baum

+1.703.634.9966

**Comment by Colorjet3** [comment]
Hello @cyberoldie 
1.  The Help | About OpenShot is not included.  However, I trust that you went to openshot.org and clicked on "Download v3.2.1" in the middle of the screen.

2.  For Windows 11 Pro, I am assuming you meant 23H2 and not 213H2 (most likely a typo).

I just thought of something....are you by any chance importing from a network drive (OneDrive, Sharepoint, network drives, etc.)?  If yes, then please copy the .mp4 file to your local computer and then import it from the local drive.

If this still fails, then if possible, please share your .mp4 file with me so I can test with it.

**Comment by cyberoldie** [comment]
I can put it in dropbox

Sent from a cellphone by dictation. Please excuse any errors 
________________________________

**Comment by Colorjet3** [comment]
Hello @cyberoldie.  You didn't answer the question about a network drive vs. local drive.

Please use raffi@openshot.org to share the file.  ty!

**Comment by cyberoldie** [comment]
Sorry I was going to answer the questions when I sent the link today. 
File was on local C drive.
And yes it was 23H2.
I don't know why image of Help About did not show. Did the other image show?  My email is not sent in text only format.
I'll send link to file later today.
Sent from a cellphone by dictation. Please excuse any errors 

________________________________

**Comment by cyberoldie** [comment]
I have sent you a link to the folder where the file is stored

**Comment by Colorjet3** [comment]
Hello @cyberoldie Thank you for sharing the .mp4 file.  I downloaded it and imported it into OpenShot.  I am able to:

1.  Right click on the file in "Project Files" and select "Preview File" and it previews just fine.
2.  I then drag it onto a Track and click Play in the "Video Preview" window without any issues.

I really don't know what you are having issues in your environment.  I recorded my screen so you can see for yourself that I was successful in working with your video file.  I uploaded the recording in the Dropbox folder you shared with me.

I am running v3.2.1-Release-12654-...............

![image](https://github.com/user-attachments/assets/92c38fd7-8bed-4a3d-acac-d420e0e33d85)

**Comment by cyberoldie** [comment]
Can you share your environment with me?
I would like to show you what happens at this eng through a Zoom session. Are you interested in that?

Sent from a cellphone by dictation. Please excuse any errors 
________________________________
