### ISSUE TITLE
cant install libfuse2 on ubuntu 

### ISSUE THREAD

**Issue by linuxnewb2086** [OpenShot/openshot-qt#5515]
when i write sudo apt install libfuse2 -y it says 
Failed to fetch http://ir.archive.ubuntu.com/ubuntu/pool/universe/f/fuse/libfuse2t64_2.9.9-8.1build1_amd64.deb  404  Not Found how do i fix it?

**Comment by linuxnewb2086** [comment]
helppppppp

**Comment by Colorjet3** [comment]
which version of Ubuntu are you running this on?

**Comment by Colorjet3** [comment]
Hello @linuxnewb2086 This should install it for you:
sudo apt-get update -y
sudo apt-get install -y libfuse2

**Comment by jouellnyc** [comment]
Sweet. That worked @Colorjet3 - Thanks!
