### ISSUE TITLE
Failed multiple attempts to start server:

### ISSUE THREAD

**Issue by vitinhacard** [OpenShot/openshot-qt#5517]
Failed multiple attempts to start server:

('127.0.0.1', 61261) 'utf-8' codec can't decode byte 0xed in position 1: invalid continuation byte
('127.0.0.1', 61262) 'utf-8' codec can't decode byte 0xed in position 1: invalid continuation byte
('127.0.0.1', 61263) 'utf-8' codec can't decode byte 0xed in position 1: invalid continuation byte

**Comment by vitinhacard** [comment]
.

**Comment by vitinhacard** [comment]
.

**Comment by Colorjet3** [comment]
Please download v3.2.1 and give it a try.  If this is still an issue then reopen this ticket.
