### ISSUE TITLE
Rare but unexpected crashes

### ISSUE THREAD

**Issue by CreamCheese-dev** [OpenShot/openshot-qt#5519]
**Describe the bug:**
I get a rare but unexpected crash when either processing effects or switching window tabs to do something else. But honesty, it seems like it can happen at any time.

**Steps to reproduce the behavior:**
There's no obvious method to replicate

**Expected behavior:**
This shouldn't be happening.

**System Details:**
- OpenShot Version 3.1.1
- Operating System / Distro: Garuda Linux BirdOfPrey Soaring x86_64
- CPU: AMD Ryzen 3 3200G with Radeon Vega Graphics (4) @ 3.60 GHz
- GPU: AMD Radeon RX 580 Series @ 0.72 GHz [Discrete]
- Memory: 16GB DDR4

**Log Files:**
[log.zip](https://github.com/OpenShot/openshot-qt/files/15449443/log.zip)

ERROR main_window: Unhandled crash detected: linux-/usr/lib/libc.so.6 gsignal 0x18 [0x7926a1e5a6c8] seems to be the issue at hand

**Comment by Colorjet3** [comment]
Try running the latest dev daily build AppImage.  There has been a few bug fixes and a few enhancements in this version.

1.  Go to openshot.org/download/#daily.
2.  Download the latest AppImage.
3.  Make it executable and run it.

The AppImage requires libfuse2 to be installed.  So, if OpenShot doesn't start via the AppImage then please instal libfus2.

Let us know if the crash happens again including the log file.  We will need to get the lead developer involved to debug.  Not able to replicate will make it challenging.

**Comment by Colorjet3** [comment]
Hello @CreamCheese-dev Any update on this?

**Comment by CreamCheese-dev** [comment]
Hey, I've been trying the new app image as suggested and I haven't experienced any issues so far.

**Comment by Colorjet3** [comment]
Thank you @CreamCheese-dev for the FYI.  I am going to close this for now, but please feel free to reopen if the issue comes back.

Also, keep an eye on a new release coming up soon that will have more bug fixes and enhancements (withing the next 2 weeks).
