### ISSUE TITLE
Openshot will not start and no error message

### ISSUE THREAD

**Issue by CFrederik** [OpenShot/openshot-qt#5520]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**
1. Go to search bar
2. Click on openshot

**Expected behavior**
Expect openshot to start, but it does not. There is not even an error message.

**System Details**
- OpenShot Version: 3.1.1-dev
- libopenshot Version:  0.3.2
- Platform: Windows-10-10.0.22621
- Processor: AMD64 Family 25 Model 97 Stepping 2, AuthenticAMD
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: 
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.1.1-dev-daily-12180-d73763f1-5e9fa273-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/rolk40v4xnucw7zod0084u546al0klxe/openshot-qt.zip) (4 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
If you are running Windows 10 home edition, there is a good chance that you need to install the Microsoft Media Pack.  Download it, install it, and try OpenShot again.

**Comment by Colorjet3** [comment]
Hello @CFrederik Any update on this?

**Comment by Colorjet3** [comment]
No response from OP.
