### ISSUE TITLE
how to export video while keeping original format(bit rate, video codec,etc)

### ISSUE THREAD

**Issue by hitbuyi** [OpenShot/openshot-qt#5522]
**Question:**
I cut the mp4 video into two parts, and export the first part I wanted, choose mp4 general quality, and foud the exported part is larger than original video. it is weird, so I want to keep the original format, how to get the orignal parameter and set them in redering parameters?

**System Details:**
- OpenShot Version : OpenShot-v2.6.1-x86_64.AppImage
- Operating System / Distro: ubuntu20.04

**Comment by Colorjet3** [comment]
When you click on Export, note the "Quality:" is is to High (in the Simple tab).  That sets the Video "Bit Rate / Quality:" to 15.00 Mb/s.  Change the "Quality:" to Med.  This sets the Bit Rate to 5.00 Mb/s.  Often, the quality of your Exported project is maintained but the file size is smaller.

If for some reason, changing the Quality from High to Med is not acceptable, take your Exported file in High Quality mode and run it through a converter like HandBrake or ShutterEncoder.  Those converters will compress your file without losing quality.

**Hint:**  Unless you have a reason to stay with v2.6.1, you should be upgrading to v3.1.2 (about to be release in the next week or so).  Many bug fixes and enhancements in v3.1.x.

**Comment by hitbuyi** [comment]
> When you click on Export, note the "Quality:" is is to High (in the Simple tab). That sets the Video "Bit Rate / Quality:" to 15.00 Mb/s. Change the "Quality:" to Med. This sets the Bit Rate to 5.00 Mb/s. Often, the quality of your Exported project is maintained but the file size is smaller.
> 
> If for some reason, changing the Quality from High to Med is not acceptable, take your Exported file in High Quality mode and run it through a converter like HandBrake or ShutterEncoder. Those converters will compress your file without losing quality.
> 
> **Hint:** Unless you have a reason to stay with v2.6.1, you should be upgrading to v3.1.2 (about to be release in the next week or so). Many bug fixes and enhancements in v3.1.x.

Thanks a lot, HandBrake solved my problem

**Comment by Colorjet3** [comment]
That is great @hitbuyi Good luck with your project(s).
