### ISSUE TITLE
Cache not working properly

### ISSUE THREAD

**Issue by johnnylingster** [OpenShot/openshot-qt#5526]
**Describe the bug:**
When trying to do a playback preview, the video catches up to the cache quickly and is not updating fast enough, which then gets glitches.

**Steps to reproduce the behavior:**
1. open a project
2. Click on play
3. wait a second or three and it catches up to the cache and then glitches

**Expected behavior:**
To not catch up to the cache?  It's never had this issue before.
[libopenshot.log](https://github.com/user-attachments/files/15738776/libopenshot.log)
[openshot-qt.log](https://github.com/user-attachments/files/15738777/openshot-qt.log)

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
This is a common and known issue with OpenShot.   Currently hardware acceleration does not work/very limited.  There are a few things that you can do to make the experience a bit better.  Your mileage will vary as well based on the complexity of your project (animation, transitions, etc.):

1.  Make the "Video Preview" smaller.
2.  Choose a lower resolution profile while editing.  This will not impact your Exported project as you can still select the Profile you wish to Export with.
3.  Make the following Cache adjustments in Edit | Preferences | Cache tab:

![image](https://github.com/OpenShot/openshot-qt/assets/59097181/339d6c83-a5ad-426e-bcde-d106bd3319f4)

Be careful with the "Cache Limit (MB)" setting.  I have a 32GB RAM system but making this too large will cause excessive caching and cause further slow down/lagging.  For my system I have found 2048-4096 to work the best.  I set it to 4096 if I am just previewing.  I set it back to 2048 when I am editing.  A smaller cache size will cause less "Cache" rebuilding.  

The good part about changing the Cache Limit is that you can do it on the fly without having to restart OpenShot.

I see that you are running v3.1.1 production release.  There are many bug fixes and enhancements in the latest DEV Daily Build.  Unfortunately not many of the fixes are related to "performance" but a few are and you may or may not notice the improvements.

Please upgrade to the latest dev daily build and then make the changes I suggested:
1.  Close OpenShot if running.
2.  go to openshot.org/download/#daily and download the latest dev daily build available.
3.  Install it, start OpenShot, and make the changes I suggested.

Let me know if this helped.

**Comment by Colorjet3** [comment]
No response from OP
