### ISSUE TITLE
Is there a way to select the whole or just a portion of a track, without having to select elements one by one?

### ISSUE THREAD

**Issue by ghevge** [OpenShot/openshot-qt#5532]
**Question:**
Is there a way to select the whole or just a portion of a track,  without having to select elements one by one?

In my case, I have a track which contains multiple separate sounds. I would like to be able to select a couple or all of those sounds and move them to the right or to the left on the time scale

There is the Ctrl+Click element approach, but this is annoying as each time I miss an element, it just deselects all the selected ones.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 3.1.1
- Operating System / Distro: Windows 10

**Comment by Colorjet3** [comment]
What you can do is zoom out on the timeline so you can see as many of your clips on the timeline.  Now, using the mouse draw, press and hold the left mouse key while the arrow is on an empty spot on the timeline and while still hold down the left mouse key, draw a rectangle over all of the clips on a track and then release the mouse.  Whatever clips the rectangle was drawn over will be selected.

Note that if the rectangle was stretched over other tracks that had clips then those will be selected.

CTRL+A will select all clips on the timeline (includes every track).

Unfortunately, the Shift option of selection does not currently work (selecting 1 clip then moving over to another then holding the shift key and clicking would select all the clips in between including the first and last clips.
