### ISSUE TITLE
Is there a way to fade in or fade out the track volume, keeping at the same time the entire track volume at max 10%? 

### ISSUE THREAD

**Issue by ghevge** [OpenShot/openshot-qt#5533]
**Question:**
Is there a way to fade in or fade out the track volume, keeping at the same time the entire track volume at max 10%? 

In the latest version, at the moment I want to set volume fade in or volume fade out, the entire track volume will be set to default. If you try to set the entire video volume to let's say 10%, while the fade effects are active, nothing will happen.

So in other words, you can either have the fade volume effects or a max entire track volume. But not both.

**System Details:**
- OpenShot Version: 3.1.1
- Operating System / Distro: Windows 10

**Comment by Colorjet3** [comment]
No, that is not possible at this time (a missing functionality/enhancement).  What you can do is start a new project, import your audio into OpenShot and drag it on the timeline.  Set the volume at 10%.  Export it.  Now open your actual project and import this new audio file, drag it onto a track and set the fade in or fade out.

There is another way to do this with keyframes but it gets a bit more complicated.

**Comment by Colorjet3** [comment]
Workaround provided.
