### ISSUE TITLE
Image element on timeline gets corrupted on duration-resize

### ISSUE THREAD

**Issue by shodanx2** [OpenShot/openshot-qt#5534]
Hello

I am running

![image](https://github.com/OpenShot/openshot-qt/assets/10621885/0703cc87-bf01-4a7f-81aa-d5a8c3a8c3df)

When I add a png image to the timeline
And then try to resize it
It goes all wonky

Please see video screenshot below

https://github.com/OpenShot/openshot-qt/assets/10621885/2d0e581a-7636-46bc-b0bc-76557e7b8ab3

**Comment by shodanx2** [comment]
It might be because I ran out of space, I had only 2gb left.
Now it's not doing it anymore.
Still, if it's because it ran out of space, it should have given a warning

**Comment by Colorjet3** [comment]
Hello @shodanx2.  Many applications do not give you warning about limited disk space.  At only 2GB available you could have been running into other issues with your operating system as well.

I always recommend a minimum of 15-20% free disk space to avoid possible issues.

You may also run a health check on your disk drive if it it getting full, even thought you freed up disk space.

**Comment by Colorjet3** [comment]
Hello @shodanx2 I am closing this ticket because I didn't see an update from you.  Feel free to reopen if you still need assistance.

**Comment by shodanx2** [comment]
Hello,
Sorry, I didn't have a reply for you. 
I have not needed to use openshot since but after a reboot and clearing some space the problem went away so I could complete the task. 
Basically I think it should have failed more gracefully and that's about it.
