### ISSUE TITLE
Importing an image sequence of PNG, causes a crash

### ISSUE THREAD

**Issue by shodanx2** [OpenShot/openshot-qt#5535]
Hi,

This is running 

![image](https://github.com/OpenShot/openshot-qt/assets/10621885/720ade80-b1f0-49ab-bd0b-4cb0337f6720)

I'm trying to import an image sequence and it crashes reliably (And I have enough disk space now, 27gb)

https://github.com/OpenShot/openshot-qt/assets/10621885/2095a8af-b109-409d-9b84-dd9c37b80484

**Comment by shodanx2** [comment]
Here are the PNG in question
[imperfect.zip](https://github.com/user-attachments/files/15779740/imperfect.zip)

**Comment by Colorjet3** [comment]
Thank you for sharing your png files.  This is a known issue and is in the queue to be fixed (no ETA at this time).  

Here is what I did to make it work:
1.  I used ShutterEncoder to convert the .png files to .jpg files.
2.  Started Shutterencoder, dragged the .png files into the "Choose files" window.
3.  For the "Choose Function" I selected JPEG.
4.  I also created a new folder to export the new files into.
5.  I started OpenShot, dragged the first .jpg file and when asked to create an image sequence I said Yes.
6.  Everything imported fine into OpenShot.  Dragged the file onto the timeline and it previews just fine.

Note:  You may try VLC or HandBrake as well to convert the files.

By the way, I am running the latest dev daily build of OpenShot v3.1.1 and in Windows 11 Pro operating system environment.

**Comment by Colorjet3** [comment]
No response from OP.
