### ISSUE TITLE
App Image keeps crashing

### ISSUE THREAD

**Issue by CreamCheese-dev** [OpenShot/openshot-qt#5536]
App Image is no longer launching despite running normally before. Other images I use operate fine and I haven't updated my system. Even rolling back to an old snapshot doesn't start it.

**Steps to reproduce the behavior:**
Type OpenShot in the search bar and wait for it to load.

**Expected behavior:**
I expect the software to open up but it immediately terminates itself

**System Details:**
Linux (64-bit AppImage)
OS: Garuda Linux BirdOfPrey Soaring x86_64
Host: A320M-S2H
Kernel: Linux 6.9.3-zen1-1-zen
CPU: AMD Ryzen 3 3200G with Radeon Vega Graphics (4) @ 3.60 GHz
GPU: AMD Radeon RX 580 Series @ 1.11 GHz [Discrete]
Memory: 5.19 GiB / 15.57 GiB (33%)

Logs return nothing but I was able to check kernel logs and this seems to be the prevailing thing every-time I run the image: segfault at 10 ip 0000619030f17465 sp 00007ffee1a4ad50 error 4 in pasystray[619030f17000+7000] likely on CPU 1 (core 1, socket 0), I've tried rolling back to periods where it ran fine and still nothing. Which I find strange.

**Comment by Colorjet3** [comment]
Hello @CreamCheese-dev Please give this a try:

1.  Go to Openshot.org/download/#daily and download the latest dev daily build AppImage.
2.  Make it executable.
3.  Start OpenShot.  If nothing happens then you might need to install libfuse2.

I am not familiar with the version of Linux you have so you can search on how to install libfuse2 on your system.

**Comment by Colorjet3** [comment]
Any update on this?

**Comment by Colorjet3** [comment]
No response from OP
