### ISSUE TITLE
OpenShot V2.2.0 Crashing in different scenarios

### ISSUE THREAD

**Issue by Stryker89** [OpenShot/openshot-qt#554]
**System Details:**
* i7-4790k OC to 4.4Ghz, 16Gb RAM
* Operating System: Windows 10 Home 64bit 
* OpenShot Version: 2.2.0
* Apologies, could not find a log file anywhere, if anyone can point me in the right direction I will be happy to add one

I have two issues that causes Launcher.exe to stop working. If I attempt to speed up or slow down a clip then is crashes and also when exporting a video. I can export at 720p24 but if I try 720p60 or 1080p60 then it eventually crashes after the export window constantly goes 'Not Responding' then jumps a couple of percent then back to 'Not Responding'. I have managed to get up to 60% complete before but in some instances it only gets to 2 - 3%.

If you need any more info that may help me fix this problem then just ask.

Cheers!

**Comment by ankitpati** [comment]
[OpenShot 2.3.1](https://github.com/OpenShot/openshot-qt/releases/download/v2.3.1/OpenShot-v2.3.1-x86_64.exe "for Windows") has been released. Can you please try to reproduce the issues on the latest version?

**Comment by DylanC** [comment]
@Stryker89 - Please try v2.4 and let us know if this version works for you.
