### ISSUE TITLE
Sound delay on video preview

### ISSUE THREAD

**Issue by h3l2f** [OpenShot/openshot-qt#5541]
**Describe the bug:**
Sound delay on the video preview

**Steps to reproduce the behavior:**
error on the video preview

**Expected behavior:**
Nothing

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 3.1.1
- Operating System / Distro: Windows 7

**Comment by Colorjet3** [comment]
Hello @h3l2f If you could provide some additional details that would be great:
1.  What type of a file are you working with (.mp4?  .mov? etc?)
2.  Does this happen with this file only or does it happen with other video/audio files as well?
3.  Is this the first time you installed OpenShot v3.1.1 or did you upgrade from a previous version?
4.  Does your video/audio file play ok outside of OpenShot (without sound delay)?

**Comment by h3l2f** [comment]
1. I used .mp4 file for my project
2. it happens to every other file 
3. This is my first time I use it
4. It's ok outside of openshot
That's it.

**Comment by Colorjet3** [comment]
Hello @h3l2f I don't have a Windows 7 to test.

Are you using external speakers or headphones?

Pleas give this a try:
1.  Close OpenShot if running.
2.  If using Headphones, then remove them and use the speakers only for now.
3.  go to openshot.org and download v3.2.1 (just released).
4.  Install it.
5.  In Windows 7, make sure that the Win 7 Media Pack is installed.
6.  Are you still getting sound delay?

**Comment by Colorjet3** [comment]
No response from OP.
