### ISSUE TITLE
Freez on Start up 

### ISSUE THREAD

**Issue by adambelis** [OpenShot/openshot-qt#5550]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**
1. inscall open shoot
2. open it
3. freez

**Expected behavior**
 run program 

**System Details**
- OpenShot Version: 3.2.0
- libopenshot Version:  0.3.3
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 79 Stepping 1, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.2.0-daily-12544-044bb224-23713d3a-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/nw67hs0rxfmucrbomvfcv11yw70h0d66/openshot-qt.zip) (9 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by RonzyC** [comment]
Hey,

+1
I have this exact same behavior, where the openshot-qt.log ends with `WARNING preview_thread: Your active audio device (||) does not match OpenShot (). Adjusting your 'Preferences->Playback->Audio Device' to match your active audio device: ||` (no idea if relevant or not)

Here's a screenshot of what is shown in my tools, even after clearing up the .openshot_qt folder and reinstalling as well
![image](https://github.com/user-attachments/assets/2dc717a7-af59-466f-8759-b9860a269420)

However, something that might differ from what @adambelis experience here is, it was fine Yesterday. I installed it Yesterday and use it to produce a video actually. I want to open it again today and it was acting like this

Would appreciate if fix ASAP

Regards

**Comment by RonzyC** [comment]
Ah nevermind, updating to 3.2.1 fixed the problem

Thanks
