### ISSUE TITLE
OpenShot crashes when importing a Video

### ISSUE THREAD

**Issue by Aipathon** [OpenShot/openshot-qt#5553]
**Describe the bug:**
Every time i try to import a Video the programm crashes immediatly

**Steps to reproduce the behavior:**
1: Open OpenShot
2: Click "Import File"
3: Select Video
4: Click Import
5: Programm crashes

**Expected behavior:**
OpenShot imports the Video(.mp4)

**System Details:**
- OpenShot Version: 3.1.1
- Operating System / Distro: Arch Linux

**Log Files:**
Cant access Logs, since the log folder isnt in my home directory, since I installed it through Flatpak

**Comment by Colorjet3** [comment]
Hello @Aipathon Flatpak isn't well support by OpenShot.

1.  Please go to openshot.org and download v3.2.1 AppImage.
2.  Make it executable and run it.
3.  Try importing again.

**Comment by Colorjet3** [comment]
Any update on this @Aipathon ?

**Comment by Aipathon** [comment]
@Colorjet3 I'm currently not at home but will return at the end of next week so I will give an update when I'm back home.

**Comment by Colorjet3** [comment]
Please reopen if you still need assistance with this.

**Comment by Aipathon** [comment]
@Colorjet3 Now it works.  It looks like the problem was, that i havent installed FUSE, since without it it wouldnt even run the AppImage.

**Comment by Colorjet3** [comment]
That is great @Aipathon.
