### ISSUE TITLE
OpenShot will not open on Windows 24H2 Preview

### ISSUE THREAD

**Issue by davidlbangs** [OpenShot/openshot-qt#5555]
**Describe the bug:**

**Steps to reproduce the behavior:**
1.  Install OpenShot 64 bit Windows version from web site. [Do special trick to override Windows blocking it for being unknown]
2.  Run the set up program and let it finish.
3. Click on "OpenShot Video Editor"
4. RESULT:  Nothing happens.
5. Follow the link to install the daily build.  Install it.  Run it again.  Nothing happens.

The app does not show up in the Task Manager, however it may briefly appear as a background task before disappearing.

**Expected behavior:**
The app should open.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

The OpenShot Video Editor 3.2.0 was installed from daily build link on 6/27
Windows 11 build 24H2.  OS Build 26100.994 running on Intel Core Ultra 9 processor with NVidia 4060 GPU.

**Log Files:**

I dragged in openshot-qt.log, which is the only log file that was created.
However, nothing was written to this log file because the program  will not start.
I included a screenshot of the installation folder and file properties.

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

[openshot-qt.log](https://github.com/user-attachments/files/16019346/openshot-qt.log)
<img width="596" alt="Screenshot 2024-06-27 112333" src="https://github.com/OpenShot/openshot-qt/assets/21370792/38e28e6d-1ccc-4b55-bf9b-c6fe3710d5d1">

**Comment by davidlbangs** [comment]
It is possible to run the app from the terminal using .\openshot-qt-cli.exe
![Screenshot 2024-06-27 113041](https://github.com/OpenShot/openshot-qt/assets/21370792/1883be76-7dca-4c66-a6e5-6a18c121992b)

**Comment by davidlbangs** [comment]
After running the software using openshot-qt-cli.exe, I still cannot launch the app normally using openshot-qt.exe.  However, log  files were created which I can include here for troubleshooting
[libopenshot.log](https://github.com/user-attachments/files/16019590/libopenshot.log)
[openshot-qt.log](https://github.com/user-attachments/files/16019591/openshot-qt.log)

**Comment by Colorjet3** [comment]
Hello @davidlbangs Please download and install v3.2.1 and see if that resolves your issue.
