### ISSUE TITLE
Program freezes at startup

### ISSUE THREAD

**Issue by yazdanif** [OpenShot/openshot-qt#5558]
**Describe the bug**
Program freezes at startup after updating to the latest version

**Steps to reproduce the behavior:**
1. Delete .openshot-qt directory
2. Uninstall openshot editor
3. Install openshot editor
4. Click to run 'openshot editor'
5. See error
6. The last stable daily Build is: https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v3.1.1-dev-daily-12180-d73763f1-5e9fa273-x86.exe

**Expected behavior**
I expected the program to startup normally without freezing.

**System Details**
- OpenShot Version: 3.2.0
- libopenshot Version:  0.3.3
- Platform: Windows-10-10.0.22621
- Processor: Intel64 Family 6 Model 154 Stepping 3, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.2.0-dev-daily-12549-044bb224-23713d3a-x86_64.exe
- - Daily Build: Verified issue still exists in daily build: https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v3.2.0-dev-daily-12590-044bb224-23713d3a-x86.exe

**Log Files** 
- [openshot-qt.log](https://github.com/user-attachments/files/16057616/openshot-qt.log)
- [libopenshot.log](https://github.com/user-attachments/files/16057609/libopenshot.log)

**above files are the result of the latest daily release of July 01 installation**

- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/ttf05h92xp72yqyp3xwj0g6u9ononfu8/openshot-qt.zip) (4 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
![image](https://github.com/OpenShot/openshot-qt/assets/174149575/348d735a-123a-4974-8a41-d069792bafdc)
![image](https://github.com/OpenShot/openshot-qt/assets/174149575/ef93462b-1362-44a7-a30e-46536150cec6)

If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by yazdanif** [comment]
I have included log files after changing "value" to "True" for Debug category in the .settings file and restarting the program.

> _**{
>   "value": true,
>   "title": "Debug Mode (Verbose)",
>   "type": "bool",
>   "category": "Debug",
>   "setting": "debug-mode",
>   "restart": false
>  },**_



[libopenshot.log](https://github.com/user-attachments/files/16037046/libopenshot.log)
[openshot-qt.log](https://github.com/user-attachments/files/16037049/openshot-qt.log)

**Comment by ScarletFields** [comment]
I had the same issue with similar system details. Symptoms matched this thread here: https://github.com/OpenShot/openshot-qt/issues/5195 

I tried similar steps as to what you describe and tried various installing/uninstalling/installing with admin/running with admin/ running Compatibility Troubleshooter/ deleting the preferences folder /made sure I have 10 percent of my hard drive space free. Nothing helped.

I rolled back to the version the OP used in this thread, and that solved the problem. https://github.com/OpenShot/openshot-qt/issues/5195

I did not try rolling back to any more recent versions, as I need to get back up and running.  Hope that helps.

Thanks!

**Comment by ionalchemist** [comment]
I am having the exact same issue.
![image](https://github.com/OpenShot/openshot-qt/assets/3453401/b08a13a1-2e42-42c8-8705-2589e1b7fcfa)

**Comment by fpapazia** [comment]
I have the same issuer, Windows 10 up to date.
[libopenshot.log](https://github.com/user-attachments/files/16052839/libopenshot.log)
[libopenshot.txt](https://github.com/user-attachments/files/16052847/libopenshot.txt)
[openshot.settings.txt](https://github.com/user-attachments/files/16052848/openshot.settings.txt)
[openshot-qt.log.txt](https://github.com/user-attachments/files/16052849/openshot-qt.log.txt)

**Comment by fpapazia** [comment]
After rolling back to 11197 - issue disappears.

**Comment by yazdanif** [comment]
> After rolling back to 11197 - issue disappears.

For me Daily Build [12180] (https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v3.1.1-dev-daily-12180-d73763f1-5e9fa273-x86.exe) is the stable build.

**Comment by fpapazia** [comment]
HI Yazdanif, 
Thanks.
I installed Build 12180. No freeze issue with this version.
Fabrice

**Comment by Colorjet3** [comment]
A new daily build has been released of vesion 3.2.0 that resolves the freezing issue.  Please go to openshot.org/download/#daily and download and install the latest DEV daily build.  OpenShot should start.

Please confirm either way.

**Comment by yazdanif** [comment]
> A new daily build has been released of vesion 3.2.0 that resolves the freezing issue. Please go to openshot.org/download/#daily and download and install the latest DEV daily build. OpenShot should start.
> 
> Please confirm either way.

Thank you,  Daily Build [12610](https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v3.2.0-dev-daily-12610-044bb224-23713d3a-x86_64.exe) resolved my freezing issue.
