### ISSUE TITLE
Open shot won't open at all.

### ISSUE THREAD

**Issue by swiftreactions** [OpenShot/openshot-qt#5559]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 
- libopenshot Version:  
- Platform: 
- Processor: 
- Machine: 
- Python version: 
- Qt5 version: 
- PyQt5 version: 
- Qt Detected Languages: 
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Skipped this step

**Log Files**
N/A

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by swiftreactions** [comment]
Can't open open shot from desktop or from existing saved project files

**Comment by Colorjet3** [comment]
1.  What version of Openshot are you running?
2.  what operating system/version are you running?
3.  Do you get any error messages?
4.  Was this working before?  if yes, what changes to your environment are you aware of?

**Comment by Colorjet3** [comment]
No response from OP.

There is a new production release (v3.2.1) that just got published.  Install that and give it a try.
