### ISSUE TITLE
OpenShot Video Editor new update crashes

### ISSUE THREAD

**Issue by MaraLearns** [OpenShot/openshot-qt#5563]
**Describe the bug**
It stops responding right after launch and displays two windows

**Steps to reproduce the behavior:**

**Expected behavior**
To launch successfully and be able to add project files

**System Details**
- OpenShot Version: 3.2.0-dev
- libopenshot Version:  0.3.3
- Platform: Windows-10-10.0.22621
- Processor: Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.2.0-dev-daily-12549-044bb224-23713d3a-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/6towwhrs54ifvpi6nmmkug9hgss2gemj/openshot-qt.zip) (4 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by MaraLearns** [comment]
![Screenshot 2024-07-01 122135](https://github.com/OpenShot/openshot-qt/assets/92562480/2d746779-4d65-43a9-ac4c-4d3bcc8ec5a5)

**Comment by rtpop** [comment]
Similar issue for me on windows. Was working just fine until I updated to the newest version. Now it won't even launch. It freezes on this.

![image](https://github.com/OpenShot/openshot-qt/assets/72130012/5015d588-f9c0-4027-9ce5-2d38b87c91c4)


Edit: Actually, I just noticed version 3.2.1 was available (previously I had downloaded 3.2.0). 3.2.1 seems to be launching at least.

**Comment by Colorjet3** [comment]
Hello @MaraLearns and @rtpop Please go to openshot.org/download/#daily and download the latest v3.2.1-Release-Candidate.  The freezing issue has been fixed in this release.

The v3.2.1-Release-Candidate is going through QA testing right now so it would be great to hear back from you if this release fixes your issue and if you can perform a few editing tasks and report back, that would be great.

**Comment by RonzyC** [comment]
@Colorjet3 I was experiencing the same problem in 3.2.0 and can confirm that 3.2.1 seems OK for now

Thanks

**Comment by Colorjet3** [comment]
> @Colorjet3 I was experiencing the same problem in 3.2.0 and can confirm that 3.2.1 seems OK for now
> 
> Thanks
Great to hear and thank you for the feedback.

**Comment by Colorjet3** [comment]
I am closing this ticket since the freezing issue has been resolved in v3.2.1 (production release has been published) and we've had many users, experiencing this issue, confirming the fix.

**Comment by MaraLearns** [comment]
Sounds good!
