### ISSUE TITLE
Can't start OpenShot (Not Responding on launch)

### ISSUE THREAD

**Issue by CubeNotFound** [OpenShot/openshot-qt#5567]
**Describe the bug:**
When I start OpenShot it shows the Not Responding window. It won't start even after waiting for some time.

**Steps to reproduce the behavior:**
1. Run OpenShot

**Expected behavior:**
OpenShot will run smoothly.

**System Details:**
- OpenShot Version 3.2.0
- Microsoft Windows 11 22H2

**Log Files:**
Please see output of `openshot-qt-cli.exe --debug` [openshot-qt.log](https://github.com/user-attachments/files/16100474/openshot-qt.log)

**Comment by Colorjet3** [comment]
Hello @ItsAndrewDev.  A fix has been released so please give this a try:

1.  Ensure all your Windows 11 udpates are applied and restart your device.
2.  go to openshot.org/download/#daily and download the latest dev daily build.
3.  Install it and start OpenShot.

**Comment by CubeNotFound** [comment]
Thank you, my problem was resolved.
