### ISSUE TITLE
Linux 64-bit AppImage fails to run on Xubuntu 16.10 64-bit

### ISSUE THREAD

**Issue by jpfleury** [OpenShot/openshot-qt#557]
**System Details:**
* _Operating System / Distro:_ Xubuntu 16.10 64-bit
* _OpenShot Version:_ OpenShot-v2.3.0-x86_64.AppImage
* _Please attach log files if crash:_ [error-output.txt](https://github.com/OpenShot/openshot-qt/files/886370/error-output.txt)

**Issue Description and steps to reproduce:**

- Download http://github.com/OpenShot/openshot-qt/releases/download/v2.3.0/OpenShot-v2.3.0-x86_64.AppImage

- Set the file to be executable.

- Run it in the console: `./OpenShot-v2.3.0-x86_64.AppImage`

**Results:** attached error output file.

**Comment by DylanC** [comment]
@jpfleury - Does the latest appimage give you the same result?

**Comment by jpfleury** [comment]
I've tested with the latest file:

http://github.com/OpenShot/openshot-qt/releases/download/v2.3.4/OpenShot-v2.3.4-x86_64.AppImage

and I don't have any errors. :-)

**Comment by DylanC** [comment]
@jpfleury - Great news. Thanks!
