### ISSUE TITLE
open shot app crashing when i try to slice a video.

### ISSUE THREAD

**Issue by himanibelsare** [OpenShot/openshot-qt#5575]
**Describe the bug:**
It just completely stops working. My cursor is unresponsive and I cant do anything with the app.

**Steps to reproduce the behaviour:**
1. Uploaded my current project.
2. Play the video
3. Try to slice a video and then the entire app crashes

**Expected behaviour:**
I wanted it to work normally i.e. slice the video and play it.

**System Details:**
- OpenShot Version: 3.2.0 x86_64.dmg
- Operating System / Distro: Mac OS Sonoma

**Log Files:**

[libopenshot.log](https://github.com/user-attachments/files/16131126/libopenshot.log)
[openshot-qt.log](https://github.com/user-attachments/files/16131127/openshot-qt.log)

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
Please download and install the latest dev daily build at openshot.org/download/#daily.

Please confirm if this resolved your issue.

**Comment by Colorjet3** [comment]
No response from OP.
