### ISSUE TITLE
Openshot

### ISSUE THREAD

**Issue by johnj506** [OpenShot/openshot-qt#5579]
**Describe the bug:**

**Steps to reproduce the behavior:**

**Expected behavior:**

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.
Any audio file I put in is playing at 100000X speed.. its sounds like its being rewind or faster forward.. i have uninstalled many times with still the same problem

**Comment by Colorjet3** [comment]
Hello @johnj506 

1.  What operating system/version are you running (windows 10? ubuntu 22.04? etc.)?
2.  What version of OpenShot are you running (help | about openshot)?
3.  What type of file(s) are you working with (.mp4? .mov? .mp3? etc?)?
4.  Are you using speakers or headphones?

Follow [clean installation instructions](https://github.com/OpenShot/openshot-qt/wiki/Clean-Installation-of-OpenShot) and try again.  Be sure to download the production version and not the daily (step 6.1)

**Comment by johnj506** [comment]
I got it to work correctly only by mistake by using my USB head set while it was in .. but on my sound card and speakers no.. its the daily build and I'm on windows 10 using  wav and mp3 files 
    On Friday, July 12, 2024 at 09:57:15 AM EDT, Colorjet3 ***@***.***> wrote:  
 
 


Hello @johnj506
   
   - What operating system/version are you running (windows 10? ubuntu 22.04? etc.)?
   - What version of OpenShot are you running (help | about openshot)?
   - What type of file(s) are you working with (.mp4? .mov? .mp3? etc?)?
   - Are you using speakers or headphones?

Follow clean installation instructions and try again. Be sure to download the production version and not the daily (step 6.1)

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>
  

|  | Virus-free.www.avg.com |

**Comment by johnj506** [comment]
now its going fast again even with the head set in 
    On Friday, July 12, 2024 at 09:57:15 AM EDT, Colorjet3 ***@***.***> wrote:  
 
 


Hello @johnj506
   
   - What operating system/version are you running (windows 10? ubuntu 22.04? etc.)?
   - What version of OpenShot are you running (help | about openshot)?
   - What type of file(s) are you working with (.mp4? .mov? .mp3? etc?)?
   - Are you using speakers or headphones?

Follow clean installation instructions and try again. Be sure to download the production version and not the daily (step 6.1)

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>
  

|  | Virus-free.www.avg.com |

**Comment by Colorjet3** [comment]
Hello @johnj506 Here are are a few more things to do and try:

1.  Definitely upgrade to the production release of v3.2.1 (go to openshot.org and follow the[ Clean Installation instructions](https://github.com/OpenShot/openshot-qt/wiki/Clean-Installation-of-OpenShot)).  Confirm after the installation that you are runing build #12654 (Help | About OpenShot).
2. Ensure your audio drivers in Windows are up-to-date.
3.  Every time you change your audio output (plugging in your USB headset or removing it) you must restart OpenShot.
4.  In Edit | Preferences | Preview tab check the "Playback Audio Device" setting.  It is set to "Default".  Click on the drop down menu and you will see options like "Windows Audio:..............." and "Direct Sound:...............".  Try these options that have the name of your output audio, restart OpenShot after the chnage and test again.
5. You may also have to change the Sample Rate in Windows environment by going to Control Panel | Sound.  Find the default output audio, go into properties and change the sample rate to 48000.  Restart OpenShot.

**Comment by Colorjet3** [comment]
No comment from OP.
