### ISSUE TITLE
Apng & Animation Gif do not play

### ISSUE THREAD

**Issue by ghost** [OpenShot/openshot-qt#558]
**System Details:**
* Operating System / Distro: Linux Mint 18.1 Cinnamon 64.Bit
* OpenShot Version: OpenShot 1.4.3
apng &  animations  gif 
 	                         support

**Comment by JtLively** [comment]
What in specific are you asking for?

**Comment by MartinTheMess** [comment]
I think he's annoyed that, when an animated .gif image is added to a video, the animation does not play.  It's treated as a still image only.  I have the same problem.

**Comment by DylanC** [comment]
Marking as an enhancement.

**Comment by mikelacsa** [comment]
The same issue was raised in [1465](https://github.com/OpenShot/openshot-qt/issues/1465)
