### ISSUE TITLE
No Camera Icon Since 3.2.0

### ISSUE THREAD

**Issue by mike-matenkosky** [OpenShot/openshot-qt#5580]
**Describe the bug**
Since 3.2.0, there is no Camera Icon so I can't create a screen shot.

**System Details**
- OpenShot Version: 3.2.1
- libopenshot Version:  0.3.3
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.2.1-daily-12662-044bb224-23713d3a-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/u35jkwngjj8szwvum2qnk7xm24e20yth/openshot-qt.zip) (5 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/u35jkwngjj8szwvum2qnk7xm24e20yth/libopenshot.zip) (0 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
The Camera icon was removed when the UI was redesigned by the lead developer.  Not exactly sure why.  However, the functionality still exists under the File menu item.  Additionally, you can add a shortcut key to it (by default one isn't assigned to it) by going to Edit | Preferences | Keyboard tab.  I assigned CTRL+SHIFT+C to it.

**Comment by mike-matenkosky** [comment]
IMO, that was a bad idea, but I was able to find the functionality under the File Menu.  

Thanks @Colorjet3

**Comment by Colorjet3** [comment]
You are welcome @mike-matenkosky and I have already conveyed the message to the lead developer.  I know there was some technical issue and he wanted to get v3.2.1 out the door.  Hopefully it will make it back in a future release.

**Comment by Colorjet3** [comment]
Hello @mike-matenkosky.  I erroneously mentioned that I assigned the CTRL+SHIFT+C.  This shortcut is already assigned to the "Duplicate Title" function.  What I really assigned is ALT+SHIFT+C.
