### ISSUE TITLE
Constant crashing

### ISSUE THREAD

**Issue by MrTAToad** [OpenShot/openshot-qt#559]
Windows 10 Professional with 16GB RAM
OpenShot version 2.3.0

The main problem is video playback of segments that have been sped up.  Openshot crashes with an error in libopenshot.dll

**Comment by DylanC** [comment]
@MrTAToad - Thanks for the report. We will investigate.

**Comment by DylanC** [comment]
Speed issues should be resolved in v2.4. Please try the latest version. Thanks.
