### ISSUE TITLE
Add Voiceover Audio, sound recording

### ISSUE THREAD

**Issue by flagsoft** [OpenShot/openshot-qt#5595]
**Describe the new feature:**
Add Voiceover Audio, sound recording

**Describe the solution you'd like:**
Add Voiceover Audio, sound recording

**Describe alternatives you have considered:**
Add Voiceover Audio, sound recording

**Screenshots:** (Optional)

User interface:

`[START]  [PAUSE]    [STOP] `

**Must record audio voice over while playing video.**
**Should directly input audio sound to timeline where timeline cursor is.**

NOTE:
- PyQt5 bindings do not seems to work for non-blocking start / stop actions. (blocking only, and only for a given time in seconds for recording audio)
- maybe `sox -d recording.wav` external process call and / or bindings will work.

**Comment by Colorjet3** [comment]
Hello @flagsoft Thank you for submitting this enhancement request.  This comes up every so often by other users as well.  I have added this to the queue of enhancements for the lead developer to review and approve/reject.

I will close this ticket but feel free to add other thoughts to further enhance this request.
