### ISSUE TITLE
loss of audio regularly enough to be quite annoying 

### ISSUE THREAD

**Issue by dg7777777** [OpenShot/openshot-qt#5597]
**Describe the bug**
I do some edits eg add titles, etc and then the sound doesn't "go" when I play..

**Steps to reproduce the behavior:**
have not identified the pattern yet, just seems to be random that the sound just stops working - only way to get it to work again is to close the program and re-open my project 

**Expected behavior**
sound to always work when play the video - what else can I try to get the sound to work again?

**System Details**
- OpenShot Version: 3.2.1
- libopenshot Version:  0.3.3
- Platform: win
- Processor: Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz   2.71 GHz 32Gb RAM
- Machine: ?
- Python version: 
- Qt5 version: 
- PyQt5 version: 
- Qt Detected Languages: 
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Skipped this step

**Log Files**
N/A

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
Do you by any chance switch between headphones and speakers?  Also, do you let your computer go t sleep while OpenShot is running?  

These two conditions often cause the audio to stop working and OpenShot must be restarted for audio to work again.

**Comment by dg7777777** [comment]
no, not ever using headphones

yes, sometimes it is allowed to go to sleep - could a solution be to add a
button that refreshes the sound so that it can work again without closing
and reopening?

**Comment by Colorjet3** [comment]
Ok, the sleep definitely causes an issue.  There is an enhancement/bug fix request in the queue.  No ETA on this time.

**Comment by dg7777777** [comment]
ok, then, a tip to that effect would be good to be displayed on opening
