### ISSUE TITLE
Ubuntu 14.04 LTS: Not possible to add any effects in 2.0.5 

### ISSUE THREAD

**Issue by jarlarntzen** [OpenShot/openshot-qt#56]
**Ubuntu 14.04 LTS:** This worked in 2.0.4...I think...

Looks like this in the terminal.

```
timeline_webview:INFO Dropping ["negate", "negate", "negate", "negate", "negate"] in timeline.
timeline_webview:INFO addEffect...
timeline_webview:INFO Dropping ["saturation", "saturation", "saturation", "saturation", "saturation"] in timeline.
timeline_webview:INFO addEffect...
timeline_webview:INFO Dropping ["brightness", "brightness", "brightness", "brightness", "brightness"] in timeline.
timeline_webview:INFO addEffect...

```

**Comment by jarlarntzen** [comment]
Version 2.0.6: 
**Good news:** It is now possible to add any and all effects to a clip or image.
**Less good news**: It's still a bit flaky when adding multiple effects in quick succession while the play head is on the clip and it is previewing. It's worse with film clips since it seems to crash whenever the preview hasn't updated with the previously added effect (example: blur) before another effect is added.
Add the effects slowly enough and OpenShot survives.

**Dying words:**
```

properties_model:INFO updating clip properties model.
 main_window:INFO updateStatusChanged
preview_thread:INFO refreshFrame
preview_thread:INFO self.player.Position(): 251
Segmentation fault (core dumped)

```

**Comment by linqcan** [comment]
I am seeing this in 2.0.7 on (X)Ubuntu 14.04 LTS.

Below is the console output. No effect is seen on the clip...
```
timeline_webview:INFO Dropping ["brightness"] in timeline.
timeline_webview:INFO addEffect...
```

**Comment by jreynojustin** [comment]
OpenShot is now in Version 2.2 if you are still noticing issues in the latest version please re-open this issue letting us know.

**Comment by jarlarntzen** [comment]
I'm testing this on MacOS 10.12.3:
It works now in 2.2 but very, very slowly. Even the simple effects (like contrast / brightness) are very slow on still images. The heavier effects like blur are almost impossible to preview.

Good that it does not crash anymore, though.
