### ISSUE TITLE
I have written a file for openshot-qt but that file contains modules like torch, torchaudio etc. When I launch the application using by launch.py it says ModuleNotFoundError: No module named 'torch' . How can  I solve this provided I work on ubuntu 22.04 LTS  and it has virtual environment issue. I tried Virtual environment method as well but it gave errors with PyQT .I am a beginner in this .Can You guys help?

### ISSUE THREAD

**Issue by aditya10avg** [OpenShot/openshot-qt#5604]
![Screenshot from 2024-08-24 18-46-46](https://github.com/user-attachments/assets/91b3c800-857b-4d9c-a7e2-9398483faa03)

**Question:**
A clear and concise question. Your question should provide enough context and explanation for people to answer it. Avoid excessive background or irrelevant details, as they can obscure your actual question.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your question. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
Duplicate:  https://github.com/OpenShot/openshot-qt/issues/5604
