### ISSUE TITLE
Export a part from Video

### ISSUE THREAD

**Issue by ThomasMeister123** [OpenShot/openshot-qt#5606]
**Question:**
How can I export PART of the timeline as a video? Under Export, Advanced I can select the start image and end image (frame number?), but that is very inconvenient. Why can't you just set a start marker and an end marker on the timeline, and then select when exporting to only export between these two markers? Or have I just not found this function yet?

**System Details:**
- OpenShot Version 3.2.0

**Comment by Colorjet3** [comment]
The Frame Start/End is the only way to Export part of a project at this time.  I'll mark this as an enhancement request.

**Comment by ThomasMeister123** [comment]
Is this already an enhancement?
