### ISSUE TITLE
No audio or video playback on videos with mpeg2video codec.

### ISSUE THREAD

**Issue by Taneblade** [OpenShot/openshot-qt#5609]
All my imported videos have no audio or video. The videos play on windows just fine but when I import them into openshot they just show up blank. I tried all the usual debugging steps, this happens at all the resolutions, audio, and video settings I've tried. This happens on the latest version and on the dev build. I used to be able to do this fine but today its just not working. They are blank whether I drag them in a timeline and play or if I just right click to preview. In preview the speaker clicks intermittently. Again I'm not new to openshot and It has worked fine before but It just isn't now.

**Comment by Colorjet3** [comment]
Hello @Taneblade Obviously something has changed in your environment and/or something has been corrupted.

1.  What operating system/version are you running?
2.  Please confirm the version of OpenShot (help | About OpenShot)?

Things to try:
1.  Restart your computer.
2.  Ensure all your operating system updates are installed.
3.  Ensure your GPU drivers are up-to-date.
4.  Close OpenShot if running.  Make a backup of c:\users\username\.openshot_qt folder (Windows) or /home/username/.openshot_qt folder (Linux).
5.  Now delete .../.openshot_qt folder.
6.  Start OpenShot and try importing a video/audio file and test.

8.

**Comment by Taneblade** [comment]
Ok I figured out that it was specifically not working on videos with the mpeg2video codec. Does openshot support that type of video?

**Comment by Taneblade** [comment]
@Colorjet3 Windows 11, Openshot 3.2.0, 3.2.1, 3.2.1 dev build. I had previously done all those steps.

**Comment by Colorjet3** [comment]
Hello @Taneblade I don't know the answer regarding support for mpeg2 video codec.  I know that Openshot works best with .mp4 files.  Please run your video file through converter like VLC, Handbrake, or Shutterencoder.  Now take the converted file and import it into Openshot

**Comment by Colorjet3** [comment]
Hello @Taneblade Any update on this?
