### ISSUE TITLE
QT scaling 2x ?

### ISSUE THREAD

**Issue by izznogooood** [OpenShot/openshot-qt#561]
QT Scaling is way off. 

**System Details:**
* Operating System / Distro: Ubuntu 17.04
* OpenShot Version: 2.3.1

UPDATE: appimage works.

I dont know if its openshot but everithing is to big. I've tried deleting the .openshot folder and start over but the issue persists. 
![openshot-qt-bug](https://cloud.githubusercontent.com/assets/23040578/24585669/5787f662-1790-11e7-946f-8d01bd361930.png)

**Comment by izznogooood** [comment]
This affects 2.3.2 as well.... From your PPA.

**Comment by DylanC** [comment]
@izznogooood - Do you know if it affects newer versions in the PPA?

**Comment by izznogooood** [comment]
Sorry, I dont use OpenShot anymore. It kept crashing...

**Comment by DylanC** [comment]
@izznogooood No problem. I found the answer on a different ticket.
