### ISSUE TITLE
Can't run Openshot 2.3.1 in Kubuntu 16.10

### ISSUE THREAD

**Issue by mfraser** [OpenShot/openshot-qt#562]
**System Details:**
* Operating System / Distro: Kubuntu 16.10
* OpenShot Version: 2.3.1

```
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
      launch:INFO ------------------------------------------------
      launch:INFO    OpenShot (version 2.3.1)
      launch:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.3.1
         app:INFO libopenshot version: 0.1.4
         app:INFO platform: Linux-4.8.0-45-generic-x86_64-with-Ubuntu-16.10-yakkety
         app:INFO processor: x86_64
         app:INFO machine: x86_64
         app:INFO python version: 3.5.2+
         app:INFO qt5 version: 5.7.0
         app:INFO pyqt5 version: 5.7
    language:INFO Attempting to load qt_en_GB.UTF-8 in '/usr/local/lib/python3.5/dist-packages/PyQt5/Qt/translations'
    language:INFO Attempting to load qt_en in '/usr/local/lib/python3.5/dist-packages/PyQt5/Qt/translations'
    language:INFO Attempting to load en_GB.UTF-8/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Attempting to load en/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Attempting to load qt_en_GB in '/usr/local/lib/python3.5/dist-packages/PyQt5/Qt/translations'
    language:INFO Attempting to load qt_en in '/usr/local/lib/python3.5/dist-packages/PyQt5/Qt/translations'
    language:INFO Attempting to load en_GB/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Successfully loaded en_GB/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Qt Detected Languages: ['en-GB']
    language:INFO LANG Environment Variable: en_GB.UTF-8
    language:INFO LOCALE Environment Variable: en_GB
    language:INFO Attempting to load qt_en_GB.UTF-8 in '/usr/local/lib/python3.5/dist-packages/PyQt5/Qt/translations'
    language:INFO Attempting to load qt_en in '/usr/local/lib/python3.5/dist-packages/PyQt5/Qt/translations'
    language:INFO Attempting to load qtbase_en_GB.UTF-8 in '/usr/local/lib/python3.5/dist-packages/PyQt5/Qt/translations'
    language:INFO Attempting to load qtbase_en in '/usr/local/lib/python3.5/dist-packages/PyQt5/Qt/translations'
    language:INFO Attempting to load qt_en_GB.UTF-8 in '/usr/lib/python3/dist-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load qt_en in '/usr/lib/python3/dist-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load qtbase_en_GB.UTF-8 in '/usr/lib/python3/dist-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load qtbase_en in '/usr/lib/python3/dist-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load en_GB.UTF-8/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Attempting to load en/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Attempting to load qt_en_GB in '/usr/local/lib/python3.5/dist-packages/PyQt5/Qt/translations'
    language:INFO Attempting to load qt_en in '/usr/local/lib/python3.5/dist-packages/PyQt5/Qt/translations'
    language:INFO Attempting to load qtbase_en_GB in '/usr/local/lib/python3.5/dist-packages/PyQt5/Qt/translations'
    language:INFO Attempting to load qtbase_en in '/usr/local/lib/python3.5/dist-packages/PyQt5/Qt/translations'
    language:INFO Attempting to load qt_en_GB in '/usr/lib/python3/dist-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load qt_en in '/usr/lib/python3/dist-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load qtbase_en_GB in '/usr/lib/python3/dist-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load qtbase_en in '/usr/lib/python3/dist-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load en_GB/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Successfully loaded en_GB/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Exiting translation system (since we successfully loaded: en_GB)
project_data:INFO Setting default profile to HDV 720 24p
         app:INFO Setting font to /usr/lib/python3/dist-packages/openshot_qt/images/fonts/Ubuntu-R.ttf
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
         app:INFO Setting custom dark theme
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "/usr/bin/openshot-qt", line 11, in <module>
    load_entry_point('openshot-qt==2.3.1', 'gui_scripts', 'openshot-qt')()
  File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 70, in main
    app = OpenShotApp(sys.argv)
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 153, in __init__
    from windows.main_window import MainWindow
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/main_window.py", line 43, in <module>
    from windows.views.timeline_webview import TimelineWebView
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/views/timeline_webview.py", line 40, in <module>
    from PyQt5.QtWebKitWidgets import QWebView
ImportError: No module named 'PyQt5.QtWebKitWidgets'
     metrics:INFO Track exception: {'content-length': '29', '-content-encoding': 'gzip', 'vary': 'Accept-Encoding', 'status': '200', 'date': 'Sun, 02 Apr 2017 10:37:15 GMT', 'server': 'Apache/2.2.22 (Ubuntu)', 'content-type': 'text/html; charset=utf-8'} (b'*exception-successfully-sent*')
^C      logger:ERROR Exception ignored in:
      logger:ERROR <module 'threading' from '/usr/lib/python3.5/threading.py'>
      logger:ERROR Traceback (most recent call last):
      logger:ERROR   File "/usr/lib/python3.5/threading.py", line 1288, in _shutdown
      logger:ERROR t.join()
      logger:ERROR   File "/usr/lib/python3.5/threading.py", line 1054, in join
      logger:ERROR self._wait_for_tstate_lock()
      logger:ERROR   File "/usr/lib/python3.5/threading.py", line 1070, in _wait_for_tstate_lock
      logger:ERROR elif lock.acquire(block, timeout):
```

I have installed both `python3-pyqt5.qtwebkit` and `python3-pyqt5.qtsvg`.

**Comment by ankitpati** [comment]
Did you happen to press `Ctrl + C` in the terminal when the log was being generated? If that is the case, can you please rerun OpenShot from the terminal, and paste the logs again?

I suspect that has happened because I can see a `^C` in the log.

**Comment by mfraser** [comment]
$ openshot-qt                        
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
      launch:INFO ------------------------------------------------
      launch:INFO    OpenShot (version 2.3.1)
      launch:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.3.1
         app:INFO libopenshot version: 0.1.4
         app:INFO platform: Linux-4.8.0-45-generic-x86_64-with-Ubuntu-16.10-yakkety
         app:INFO processor: x86_64
         app:INFO machine: x86_64
         app:INFO python version: 3.5.2+
         app:INFO qt5 version: 5.7.0
         app:INFO pyqt5 version: 5.7
    language:INFO Attempting to load qt_en_GB.UTF-8 in '/usr/local/lib/python3.5/dist-packages/PyQt5/Qt/translations'
    language:INFO Attempting to load qt_en in '/usr/local/lib/python3.5/dist-packages/PyQt5/Qt/translations'
    language:INFO Attempting to load en_GB.UTF-8/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Attempting to load en/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Attempting to load qt_en_GB in '/usr/local/lib/python3.5/dist-packages/PyQt5/Qt/translations'
    language:INFO Attempting to load qt_en in '/usr/local/lib/python3.5/dist-packages/PyQt5/Qt/translations'
    language:INFO Attempting to load en_GB/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Successfully loaded en_GB/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Qt Detected Languages: ['en-GB']
    language:INFO LANG Environment Variable: en_GB.UTF-8
    language:INFO LOCALE Environment Variable: en_GB
    language:INFO Attempting to load qt_en_GB.UTF-8 in '/usr/local/lib/python3.5/dist-packages/PyQt5/Qt/translations'
    language:INFO Attempting to load qt_en in '/usr/local/lib/python3.5/dist-packages/PyQt5/Qt/translations'
    language:INFO Attempting to load qtbase_en_GB.UTF-8 in '/usr/local/lib/python3.5/dist-packages/PyQt5/Qt/translations'
    language:INFO Attempting to load qtbase_en in '/usr/local/lib/python3.5/dist-packages/PyQt5/Qt/translations'
    language:INFO Attempting to load qt_en_GB.UTF-8 in '/usr/lib/python3/dist-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load qt_en in '/usr/lib/python3/dist-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load qtbase_en_GB.UTF-8 in '/usr/lib/python3/dist-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load qtbase_en in '/usr/lib/python3/dist-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load en_GB.UTF-8/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Attempting to load en/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Attempting to load qt_en_GB in '/usr/local/lib/python3.5/dist-packages/PyQt5/Qt/translations'
    language:INFO Attempting to load qt_en in '/usr/local/lib/python3.5/dist-packages/PyQt5/Qt/translations'
    language:INFO Attempting to load qtbase_en_GB in '/usr/local/lib/python3.5/dist-packages/PyQt5/Qt/translations'
    language:INFO Attempting to load qtbase_en in '/usr/local/lib/python3.5/dist-packages/PyQt5/Qt/translations'
    language:INFO Attempting to load qt_en_GB in '/usr/lib/python3/dist-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load qt_en in '/usr/lib/python3/dist-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load qtbase_en_GB in '/usr/lib/python3/dist-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load qtbase_en in '/usr/lib/python3/dist-packages/openshot_qt/locale/QT'
    language:INFO Attempting to load en_GB/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Successfully loaded en_GB/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Exiting translation system (since we successfully loaded: en_GB)
project_data:INFO Setting default profile to HDV 720 24p
         app:INFO Setting font to /usr/lib/python3/dist-packages/openshot_qt/images/fonts/Ubuntu-R.ttf
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
         app:INFO Setting custom dark theme
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "/usr/bin/openshot-qt", line 11, in <module>
    load_entry_point('openshot-qt==2.3.1', 'gui_scripts', 'openshot-qt')()
  File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 70, in main
    app = OpenShotApp(sys.argv)
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 153, in __init__
    from windows.main_window import MainWindow
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/main_window.py", line 43, in <module>
    from windows.views.timeline_webview import TimelineWebView
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/views/timeline_webview.py", line 40, in <module>
    from PyQt5.QtWebKitWidgets import QWebView
ImportError: No module named 'PyQt5.QtWebKitWidgets'
     metrics:INFO Track exception: {'status': '200', 'server': 'Apache/2.2.22 (Ubuntu)', 'date': 'Thu, 06 Apr 2017 07:12:43 GMT', '-content-encoding': 'gzip', 'content-length': '29', 'content-type': 'text/html; charset=utf-8', 'vary': 'Accept-Encoding'} (b'*exception-successfully-sent*')

**Comment by ankitpati** [comment]
Thank you for the response. We hope to resolve the issue soon.

**Comment by jesseakc** [comment]
I'm having a similar issue on Linux Mint installed from the PPA.

It just hangs and never continues.

Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
      launch:INFO ------------------------------------------------
      launch:INFO    OpenShot (version 2.3.1)
      launch:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.3.1
         app:INFO libopenshot version: 0.1.2
         app:INFO platform: Linux-4.4.0-21-generic-x86_64-with-LinuxMint-18-sarah
         app:INFO processor: x86_64
         app:INFO machine: x86_64
         app:INFO python version: 3.5.2
         app:INFO qt5 version: 5.5.1
         app:INFO pyqt5 version: 5.5.1
    language:INFO Qt Detected Languages: ['en-US']
    language:INFO LANG Environment Variable: en_US.UTF-8
    language:INFO LOCALE Environment Variable: en_US
    language:INFO Skipping English language (no need for translation): en_US.UTF-8
    language:INFO Skipping English language (no need for translation): en_US
project_data:INFO Setting default profile to HDV 720 24p
         app:INFO Setting font to /usr/lib/python3/dist-packages/openshot_qt/images/fonts/Ubuntu-R.ttf
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
         app:INFO Setting custom dark theme
link SVGID_18_-5 hasn't been detected!
link SVGID_18_-5 hasn't been detected!
link SVGID_22_-5 hasn't been detected!
link SVGID_24_-2 hasn't been detected!
link SVGID_24_-2 hasn't been detected!
     ui_util:INFO Initializing UI for MainWindow
     ui_util:INFO Binding event MainWindow:actionNew_trigger
     ui_util:WARNING Icon theme document-new not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionOpen_trigger
     ui_util:WARNING Icon theme document-open not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionSave_trigger
     ui_util:WARNING Icon theme document-save not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionUndo_trigger
     ui_util:WARNING Icon theme edit-undo not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionSaveAs_trigger
     ui_util:WARNING Icon theme document-save-as not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionImportFiles_trigger
     ui_util:WARNING Icon theme list-add not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionImportImageSequence_trigger
     ui_util:WARNING Icon theme list-add not found. Will use backup icon.
     ui_util:WARNING Icon theme list-add not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionRedo_trigger
     ui_util:WARNING Icon theme edit-redo not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionRemoveClip_trigger
     ui_util:WARNING Icon theme list-remove not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionRemoveTransition_trigger
     ui_util:WARNING Icon theme list-remove not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionExportVideo_trigger
     ui_util:WARNING Icon theme media-record not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionUploadVideo_trigger
     ui_util:WARNING Icon theme folder-remote not found. Will use backup icon.
     ui_util:WARNING Icon theme system-shutdown not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAddTrack_trigger
     ui_util:WARNING Icon theme list-add not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionPreferences_trigger
     ui_util:WARNING Icon theme document-properties not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionPlay_trigger
     ui_util:WARNING Icon theme media-playback-start not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionJumpStart_trigger
     ui_util:WARNING Icon theme go-first not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionRewind_trigger
     ui_util:WARNING Icon theme media-seek-backward not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionFastForward_trigger
     ui_util:WARNING Icon theme media-seek-forward not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionJumpEnd_trigger
     ui_util:WARNING Icon theme go-last not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionArrowTool_trigger
     ui_util:INFO Binding event MainWindow:actionRazorTool_trigger
     ui_util:INFO Binding event MainWindow:actionSnappingTool_trigger
     ui_util:INFO Binding event MainWindow:actionAddMarker_trigger
     ui_util:INFO Binding event MainWindow:actionPreviousMarker_trigger
     ui_util:WARNING Icon theme go-first not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionNextMarker_trigger
     ui_util:WARNING Icon theme go-last not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionFilesShowAll_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowVideo_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowAudio_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowImage_trigger
     ui_util:WARNING Icon theme edit-clear not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionTransitionsShowAll_trigger
     ui_util:INFO Binding event MainWindow:actionTransitionsShowCommon_trigger
     ui_util:WARNING Icon theme edit-clear not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionEffectsShowAll_trigger
     ui_util:INFO Binding event MainWindow:actionEffectsShowVideo_trigger
     ui_util:INFO Binding event MainWindow:actionEffectsShowAudio_trigger
     ui_util:WARNING Icon theme edit-clear not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionTimelineZoomIn_trigger
     ui_util:WARNING Icon theme zoom-in not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionTimelineZoomOut_trigger
     ui_util:WARNING Icon theme zoom-out not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionTitle_trigger
     ui_util:WARNING Icon theme font not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAnimatedTitle_trigger
     ui_util:WARNING Icon theme video-x-generic not found. Will use backup icon.
     metrics:INFO Track metric: {'x-content-type-options': 'nosniff', 'content-length': '35', 'server': 'Golfe2', 'access-control-allow-origin': '*', 'status': '200', 'date': 'Wed, 05 Apr 2017 17:13:09 GMT', 'content-type': 'image/gif', 'last-modified': 'Sun, 17 May 1998 03:00:00 GMT', 'expires': 'Mon, 01 Jan 1990 00:00:00 GMT', 'pragma': 'no-cache', 'cache-control': 'no-cache, no-store, must-revalidate', 'content-location': 'http://www.google-analytics.com/collect?ua=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&aip=1&an=OpenShot+Video+Editor&cd=launch-app&v=1&tid=UA-4381101-5&cd1=0.1.2&ul=en&t=screenview&cid=6a8fefbd-ff2a-44e5-8e31-6aba122d8e44&cd5=LinuxMint-18-sarah&aid=org.openshot.openshot-qt&av=2.3.1&cd4=5.5.1&cd2=3.5.2&sc=start&cd3=5.5.1', 'age': '547031'} (b'GIF89a\x01\x00\x01\x00\x80\xff\x00\xff\xff\xff\x00\x00\x00,\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x02D\x01\x00;')
     ui_util:INFO Binding event MainWindow:actionFullscreen_trigger
     ui_util:WARNING Icon theme view-fullscreen not found. Will use backup icon.
     ui_util:WARNING Icon theme zoom-in not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAbout_trigger
     metrics:INFO Track metric: {'x-content-type-options': 'nosniff', 'content-length': '35', 'server': 'Golfe2', 'access-control-allow-origin': '*', 'status': '200', 'date': 'Wed, 05 Apr 2017 17:13:09 GMT', 'content-type': 'image/gif', 'last-modified': 'Sun, 17 May 1998 03:00:00 GMT', 'expires': 'Mon, 01 Jan 1990 00:00:00 GMT', 'pragma': 'no-cache', 'cache-control': 'no-cache, no-store, must-revalidate', 'content-location': 'http://www.google-analytics.com/collect?ua=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&aip=1&an=OpenShot+Video+Editor&v=1&tid=UA-4381101-5&cd1=0.1.2&ul=en&t=screenview&cid=6a8fefbd-ff2a-44e5-8e31-6aba122d8e44&cd5=LinuxMint-18-sarah&aid=org.openshot.openshot-qt&av=2.3.1&cd4=5.5.1&cd2=3.5.2&cd=main-screen&cd3=5.5.1', 'age': '547031'} (b'GIF89a\x01\x00\x01\x00\x80\xff\x00\xff\xff\xff\x00\x00\x00,\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x02D\x01\x00;')
     ui_util:WARNING Icon theme gtk-info not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionThumbnailView_trigger
     ui_util:WARNING Icon theme view-list-icons not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionDetailsView_trigger
     ui_util:WARNING Icon theme view-list-details not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionReportBug_trigger
     ui_util:WARNING Icon theme dialog-error not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAskQuestion_trigger
     ui_util:WARNING Icon theme im-message-new not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionTranslate_trigger
     ui_util:WARNING Icon theme stock_person not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionDonate_trigger
     ui_util:WARNING Icon theme bookmark-new not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionHelpContents_trigger
     ui_util:WARNING Icon theme help not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionSimple_View_trigger
     ui_util:WARNING Icon theme go-home not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAdvanced_View_trigger
     ui_util:WARNING Icon theme get-hot-new-stuff not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionFreeze_View_trigger
     ui_util:WARNING Icon theme locked not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionUn_Freeze_View_trigger
     ui_util:WARNING Icon theme locked not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionShow_All_trigger
     ui_util:WARNING Icon theme zoom-in not found. Will use backup icon.
     ui_util:WARNING Icon theme document-open-recent not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionProfile_trigger
     ui_util:WARNING Icon theme video-x-generic not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAdd_to_Timeline_trigger
     ui_util:WARNING Icon theme list-add not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionPreview_File_trigger
     ui_util:WARNING Icon theme media-playback-start not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionRemove_from_Project_trigger
     ui_util:WARNING Icon theme list-remove not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionFile_Properties_trigger
     ui_util:WARNING Icon theme video-x-generic not found. Will use backup icon.
     ui_util:WARNING Icon theme edit-clear not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionRemoveTrack_trigger
     ui_util:WARNING Icon theme list-remove not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionRemoveMarker_trigger
     ui_util:WARNING Icon theme list-remove not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAddTrackAbove_trigger
     ui_util:WARNING Icon theme list-add not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAddTrackBelow_trigger
     ui_util:WARNING Icon theme list-add not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionRemoveEffect_trigger
     ui_util:WARNING Icon theme list-remove not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionSplitClip_trigger
     ui_util:WARNING Icon theme edit-cut not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionProperties_trigger
     ui_util:WARNING Icon theme document-properties not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionRenameTrack_trigger
     ui_util:WARNING Icon theme gtk-edit not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionUpdate_trigger
     ui_util:INFO Binding event MainWindow:actionTutorial_trigger
     ui_util:WARNING Icon theme im-message-new not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAnimation_trigger
     ui_util:WARNING Icon theme video-x-generic not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionLockTrack_trigger
     ui_util:INFO Binding event MainWindow:actionUnlockTrack_trigger
     ui_util:WARNING Icon theme transform-move not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionEditTitle_trigger
     ui_util:WARNING Icon theme gtk-edit not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionDuplicateTitle_trigger
     ui_util:WARNING Icon theme edit-copy not found. Will use backup icon.
 files_model:INFO updating files model.
transition_model:INFO updating transitions model.
effects_model:INFO updating effects model.
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
properties_model:INFO updating clip properties model.
 main_window:INFO InitCacheSettings
 main_window:INFO cache-mode: CacheMemory
 main_window:INFO cache-limit-mb: 250
 main_window:INFO Creating CacheMemory object with 262144000 byte limit
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "/usr/bin/openshot-qt", line 9, in <module>
    load_entry_point('openshot-qt==2.3.1', 'gui_scripts', 'openshot-qt')()
  File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 70, in main
    app = OpenShotApp(sys.argv)
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 154, in __init__
    self.window = MainWindow(mode)
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/main_window.py", line 2210, in __init__
    self.InitCacheSettings()
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/main_window.py", line 2042, in InitCacheSettings
    new_cache_object = openshot.CacheMemory(cache_limit)
AttributeError: module 'openshot' has no attribute 'CacheMemory'
     version:INFO Found current version: {'content-location': 'http://www.openshot.org/version/json/', 'content-length': '29', 'server': 'Apache/2.2.22 (Ubuntu)', 'status': '200', 'date': 'Wed, 12 Apr 2017 01:13:29 GMT', 'content-type': 'application/json'} (b'{"openshot_version": "2.3.1"}')
     metrics:INFO Track exception: {'vary': 'Accept-Encoding', 'content-length': '29', 'server': 'Apache/2.2.22 (Ubuntu)', '-content-encoding': 'gzip', 'status': '200', 'date': 'Wed, 12 Apr 2017 01:13:29 GMT', 'content-type': 'text/html; charset=utf-8'} (b'*duplicate-exception-ignored*')

**Comment by ankitpati** [comment]
@jesseakc Can you please try the latest [AppImage](https://github.com/OpenShot/openshot-qt/releases/download/v2.3.1/OpenShot-v2.3.1-x86_64.AppImage "OpenShot 2.3.1"), and let us know if it works? We will be able to isolate the fault to a library shipped with Linux Mint if that is the case.

**Comment by mfraser** [comment]
I have finally manage to get OpenShot to run. I must've had PyQt5 installed using pip and apt, and running:
sudo pip3 uninstall PyQt5
Allowed OpenShot to run.

**Comment by ankitpati** [comment]
Thank you for the report.

Closing this as fixed.

**Comment by byteptr** [comment]
This bug isn't fixed since you must revome PyQt5, if you use PyQt5 for another applicqtions, there is not reason to remove it. Also the same problem under fc27

**Comment by peanutbutterandcrackers** [comment]
@byteptr - Um... doesn't OpenShot v 2.4.1 work? o.O
