### ISSUE TITLE
Openshot crashes immediately

### ISSUE THREAD

**Issue by jamercee** [OpenShot/openshot-qt#5626]
**Describe the bug**
openshot crashes immediately on load. It does not open a window.  A fresh install of the daily-tracking software (64-bit Windows 11 Pro) yields the same result. It does not even get to the point where it generates log files (the logs attached to this report are from earlier in the day prior to reinstalling the daily tracking build).

I believe it may be a conflict with an Intel Arc driver, but I've reinstalled the latest from the vendor and the behaviour continues.

There two entries made in the windows application event log that may shed light:

Faulting application name: openshot-qt.exe, version: 3.2.1.0, time stamp: 0x607466f6
Faulting module name: igd12um64xeh.dll, version: 32.0.101.5768, time stamp: 0x66a16578
Exception code: 0xc0000409
Fault offset: 0x0000000000fd1758
Faulting process id: 0x0x64DC
Faulting application start time: 0x0x1DB1360264CE188
Faulting application path: C:\Program Files\OpenShot Video Editor\openshot-qt.exe
Faulting module path: C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_baaeaf977b92dab8\igd12um64xeh.dll
Report Id: 31890cd1-5923-4ab5-975b-5012bb3cb98f
Faulting package full name: 
Faulting package-relative application ID: 

The second is:

Fault bucket 1194052396685844475, type 5
Event Name: BEX64
Response: Not available
Cab Id: 0

Problem signature:
P1: openshot-qt.exe
P2: 3.2.1.0
P3: 607466f6
P4: igd12um64xeh.dll
P5: 32.0.101.5768
P6: 66a16578
P7: 0000000000fd1758
P8: c0000409
P9: 0000000000000005
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.9601964f-1115-4182-9217-ef813391d2a7.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.95ffd00f-035f-4b8e-84ca-f8e1f117989d.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.2c914ce9-8445-422a-82e4-a7b1ed68d87d.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.1847f3d0-7c78-4104-92a8-cde5ebc6bb25.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.c98a3019-35d5-42f1-a453-8fcc79e5a774.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_openshot-qt.exe_4688abcc76b81ac735312b80f5cb91c417bcedbe_12fc305d_39e337c4-5661-41f3-ab6e-276aaa693935

Analysis symbol: 
Rechecking for solution: 0
Report Id: 31890cd1-5923-4ab5-975b-5012bb3cb98f
Report Status: 268435456
Hashed bucket: 39674ecc43ab1c82e092205413a9dffb
Cab Guid: 0

**System Details**
- OpenShot Version: OpenShot-v3.2.1-dev-daily-12872-ee58130b-23713d3a-x86_64.exe

**Comment by jamercee** [comment]
Disregard -- this was an Intel driver issue. I switched from the one recommended by the OEM (Dell) to the native download from Intel and everything is working.

**Comment by Colorjet3** [comment]
Glad you found the issue and for sharing your solution.
