### ISSUE TITLE
Cache limiting does not work

### ISSUE THREAD

**Issue by Enfostorm** [OpenShot/openshot-qt#563]
**System Details:**
* Operating System / Distro: Ubuntu 16.04
* OpenShot Version: OpenShot-v2.3.0-1-gbe4efca-49-618-x86_64

Default cache limiting works fine, but if  I change the value in the settings (3000 MB in my case), the ram usage went up to 5.5GB before I stopped it. The blue line above the timeline did not disappear, while with default settings it did.

**Comment by DylanC** [comment]
@Enfostorm - Thanks for the feedback. I will test this to confirm.

**Comment by DylanC** [comment]
@Enfostorm   - This parameter is the cache for the video preview. It will make playback of the preview more smooth if you have a smaller cache and good settings for it. 

It does not relate to the memory usage of the program.
