### ISSUE TITLE
mp4 video files encoded with H.264 fails to preview (only green screen)

### ISSUE THREAD

**Issue by tolleif** [OpenShot/openshot-qt#5635]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**
Download example video files Big Bunny
H.264 - https://test-videos.co.uk/bigbuckbunny/mp4-h264
https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/1080/Big_Buck_Bunny_1080_10s_10MB.mp4

H.265 - https://test-videos.co.uk/bigbuckbunny/mp4-h265
https://test-videos.co.uk/vids/bigbuckbunny/mp4/h265/1080/Big_Buck_Bunny_1080_10s_10MB.mp4

Drag both into OpenShot to import them.

The H.265 shows up nicely with a little thumbnail image extracted.

The H.264 shows up as a green screen as a thumbnail. Seems like the file can't be decoded.

When righ-clicking on the video clips and seelcting Preview the H.265 shows the video nicely. The H.264 only shows the green screen with the fram number running quickly in teh upper left corner.

**Expected behavior**
Both video clips should be inserted in Project as video files with a sample thumbnail image for each.

**System Details**
- OpenShot Version: 3.2.1-dev
- libopenshot Version:  0.3.3
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 183 Stepping 1, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.2.1-dev-daily-12938-5022ce44-23713d3a-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/de4dx93glh02vpnt0tz4bj33v94sgrgu/openshot-qt.zip) (10 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/de4dx93glh02vpnt0tz4bj33v94sgrgu/libopenshot.zip) (0 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by tolleif** [comment]
I tested both stable version 3.2.1 and nightly build v3.2.1-dev-daily-12938-5022ce44-23713d3a

It's not only the preview that fails, the 264 clip can't be worked with.

**Comment by Colorjet3** [comment]
Do you by any chance have hardware acceleration enabled?  If yes, then reset them all back to normal and try again.

**Comment by tolleif** [comment]
Hi @Colorjet3 , 
spot on! I set Preferences - Performance - Hardware Decoder Mode to "No acceleration" and the H.264 clip appears fine.

What a fantastic response time, thanks a lot :)

**Comment by Colorjet3** [comment]
You are welcome @tolleif and good luck with your project(s).
