### ISSUE TITLE
OpenShot will not run

### ISSUE THREAD

**Issue by prebengh** [OpenShot/openshot-qt#5641]
**Describe the bug**
A clear and concise description of the issue
I have run the latest daily version in debug mode and copied the result into the attached txt file.
I have tried the released version 3.2.1 as well as 2.6.1 but the result is the same, the program will not run and the log file is empty.
My computer is the Lenovo Yoga Slim 7i Aura with the new Intel Core 7 258V with 32 GB RAM.

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 3.2.1-dev
- libopenshot Version:  0.3.3
- Platform: Windows-10-10.0.26100
- Processor: Intel64 Family 6 Model 189 Stepping 1, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['da-DK', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.2.1-dev-daily-12980-09ca2ced-23713d3a-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/1fe2001p3f6neathquq7t85ky4spzlym/openshot-qt.zip) (10 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by prebengh** [comment]
I will add that the program will run in debug mode, not in normal mode.

**Comment by Colorjet3** [comment]
Hello @prebengh See if you can attach the log file from the debug in this thread.

**Comment by prebengh** [comment]
I have attached the log file from the debug run.
________________________________
Fra: Colorjet3 ***@***.***>
Sendt: 16. oktober 2024 17:58
Til: OpenShot/openshot-qt ***@***.***>
Cc: prebengh ***@***.***>; Mention ***@***.***>
Emne: Re: [OpenShot/openshot-qt] OpenShot will not run (Issue #5641)


Hello @prebengh<https://github.com/prebengh> See if you can attach the log file from the debug in this thread.

**Comment by Colorjet3** [comment]
Hello @prebengh I am not seeing the attached log file?

**Comment by prebengh** [comment]
________________________________
Fra: Colorjet3 ***@***.***>
Sendt: 18. oktober 2024 16:49
Til: OpenShot/openshot-qt ***@***.***>
Cc: prebengh ***@***.***>; Mention ***@***.***>
Emne: Re: [OpenShot/openshot-qt] OpenShot will not run (Issue #5641)


Hello @prebengh<https://github.com/prebengh> I am not seeing the attached log file?

**Comment by prebengh** [comment]
[openshot-qt.log](https://github.com/user-attachments/files/17437563/openshot-qt.log)

**Comment by prebengh** [comment]
Sorry, I attached the log file in Outlook, but apparently it did not ship.
I have uploaded it here on Github.

**Comment by prebengh** [comment]
I have uploaded it to the issue on Github.
________________________________
Fra: Colorjet3 ***@***.***>
Sendt: 16. oktober 2024 17:58
Til: OpenShot/openshot-qt ***@***.***>
Cc: prebengh ***@***.***>; Mention ***@***.***>
Emne: Re: [OpenShot/openshot-qt] OpenShot will not run (Issue #5641)


Hello @prebengh<https://github.com/prebengh> See if you can attach the log file from the debug in this thread.

**Comment by Colorjet3** [comment]
Thank you for the log file.  I can not find anything that is helping to figure out why OpenShot does not start.

Please give this a try:
1.  Delete c:\users\username\.openshot_qt folder.
2.  Make sure that on your c: drive you have plenty of Free disk space.  If not, free up as much as possible.
3.  Start OpenShot via the shortcut.

**Comment by Colorjet3** [comment]
Hello @prebengh I have not seen a response to the last instructions I provided.  I am going to close this ticket but please feel free to reopen it if you are still having the issue or provide an update if the issue was resolved after you deleted the c:\users\username\.openshot_qt folder.
