### ISSUE TITLE
No playback audio; and cannot change playback audio device?

### ISSUE THREAD

**Issue by Eliahavah** [OpenShot/openshot-qt#5648]
System details—
Ubuntu 24.04 (fresh upgrade); 
Openshot 3.2.1 (fresh install). 
This problem began immediately after upgrading Ubuntu and reinstalling Openshot.

Problem behavior 1— Whenever I start Openshot, I immediately receive a message, "Audio error— Please fix the following error and restart Openshot – no channels."

Problem behavior 2— Moreover, when I open an (extremely important) Openshot project that I was working on, prior to my upgrade and reinstall, and attempt to playback, there is no sound. I have verified that my sound on my computer is working, by playing a Youtube video.

Attempted solution— A forum post online indicates that a person resolved this issue by going to edit > preferences > preview > playback audio device, and changing the device. I was also advised to do this in an Openshot subreddit post I have made requesting help with this issue. However, there are two problems with this—

(1) When I open the playback audio device menu, it displays a gigantic list of incomprehensible technical names; and I do not know what is the correct one. My system settings > sound > output device merely says, "Speakers – built-in audio," and does not give any name that appears in the Openshot playback audio device menu.

(2) However, even if I simply select a different device at random, from what is already selected, then close preferences, it gives a message that says, "Restart required— Please restart Openshot for all preferences to take effect. But, when I close and restart Openshot, then go to edit > preferences > preview > playback audio device, _it has changed it back to what it was originally. Meaning it is impossible for me to change my playback audio device, at all._

Please advise? Peace to you. <3

❗ EDIT— Solution found in [this Openshot subreddit thread](https://www.reddit.com/r/OpenShot/comments/1gcqpik/no_audio_and_cannot_change_playback_audio_device/)— _**Delete ~/.openshot_qt.**_ ❗

**Comment by Colorjet3** [comment]
With Ubuntu 24.04 it is best to run the latest dev daily build AppImage v3.2.1.  Additionally, you mention that you upgraded to v3.2.x but didn't mention which version you upgraded from.

Please do this:
1.  Close OpenShot if running.
2.  Make a backup /home/username/.openshot_qt folder.
3.  Delete /home/username/.openshot_qt folder.
4.  go to openshot.org/download/#daiy and get the latest dev daily build AppImage.
5.  Make the AppImage executable and run it.
6.  If it doesn't start you may need to install libfuse2:  sudo apt install libfuse2

**Comment by Eliahavah** [comment]
> With Ubuntu 24.04 it is best to run the latest dev daily build AppImage v3.2.1. Additionally, you mention that you upgraded to v3.2.x but didn't mention which version you upgraded from.
> 
> Please do this:
> 
>     1. Close OpenShot if running.
> 
>     2. Make a backup /home/username/.openshot_qt folder.
> 
>     3. Delete /home/username/.openshot_qt folder.
> 
>     4. go to openshot.org/download/#daiy and get the latest dev daily build AppImage.
> 
>     5. Make the AppImage executable and run it.
> 
>     6. If it doesn't start you may need to install libfuse2:  sudo apt install libfuse2

Thank you for your reply. I suspect you are the same person who responded to my Openshot subreddit thread, since your message is identical. Since I saw and replied to your message on the subreddit first, I will simply continue the conversation there. If anyone comes across this Github issue, the subreddit thread is [here](https://www.reddit.com/r/OpenShot/comments/1gcqpik/no_audio_and_cannot_change_playback_audio_device/). If a solution is found, I will also update this Github issue.
