### ISSUE TITLE
Freeze Python error in main script  

### ISSUE THREAD

**Issue by jslounissart** [OpenShot/openshot-qt#565]
**System Details:**windows 10 rofessionnel
* Operating System / Distro: ?
* OpenShot Version: ?2.3
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

bonjour, impossible d'ouvrir openshot un message d'erreur apparait 
 : Cx_Freeze Ptyhon error in main script

**Comment by jslounissart** [comment]
![image](https://cloud.githubusercontent.com/assets/26894704/24791493/96264840-1b7a-11e7-8d8d-e511eb03f6e7.png)

**Comment by Tuwase** [comment]
I am also experiencing the same issue, searching for a resolution, I see that this bug has not been properly resolved for many other users.

**Comment by DylanC** [comment]
This is working in latest version.
