### ISSUE TITLE
software sets wav file rate to 22500, unable to reset too 44100, so file plays back at half speed

### ISSUE THREAD

**Issue by rshill05** [OpenShot/openshot-qt#5650]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 3.2.1-dev
- libopenshot Version:  0.3.3
- Platform: Windows-10-10.0.22621
- Processor: Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.2.1-dev-daily-12980-09ca2ced-23713d3a-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/ioy7vzcwk4od7ck3i14ohoo30mpuoby4/openshot-qt.zip) (8 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
1.  Are you by any chance using headphones?
2.  Is you computer a laptop or desktop?
3.  Are you saying the audio plays at half speed or both the audio and video?

With version 3.x.x OpenShot will default the sample rate to whatever the output audio device sample rate is set to (in your Windows environment).

Give this a try:
1.  if using headphones, unplug them.
2.  Restart your computer.
5.  Start OpenSHot and open your project.
6.  Did this fix the issue?

Another thing you can try with your headphones:
1.  Close OpenSHot if running.
2.  In Windows environment, go to Control Panel | Sound | Playback and find your headphones.
3.  Go to Properties and change the sample rate to 44100 or 48000.
4.  Test a few of your video/audio files outside of OpenShot to ensure that things sound good.
5.  Now import these files you tested into OpenShot and preview.

**Comment by Colorjet3** [comment]
No response from OP.
