### ISSUE TITLE
Expoerted mp4 has distortion on rifgt side

### ISSUE THREAD

**Issue by Nederlansk** [OpenShot/openshot-qt#5651]
Exported mp4 has a distortion band on right side of video that seems to fluctuate in sync with the audio.

Ubuntu 20.04.6 LTS

Open Shot ver. 2.4.3

![a](https://github.com/user-attachments/assets/9b14026d-2073-49e5-9dd0-3aff93a4e55b)

**Comment by Colorjet3** [comment]
Time to upgrade OpenShot and try again.  By the way, you are so far behind on versions that if you decide to upgrade you need to consider starting your project over again.  The latest version is 3.2.1 and there is much that has changed.  I started using OpenShot with version 2.5.x and once OpenShot v3.x.x was released there were many changes introduced that required some project not to port properly.

**Comment by Nederlansk** [comment]
Upgraded and it worked...Thanks!

**Comment by Colorjet3** [comment]
That is great @Nederlansk.  good luck with your project(s).
