### ISSUE TITLE
People need to be able to select what they need to use, and then lock these settings in.

### ISSUE THREAD

**Issue by Phuxxi** [OpenShot/openshot-qt#5652]
I am tired of having to re-select ALL the processing settings, everytime I make a video. 

People need to be able to select what settings they need to use, and then to be able to lock these settings in.

So can you bring in these functions.

It would be appreciated.

These settings work are my personal preferenmces for fair quality video, smallish file sizes, for things that don't really require HD settings.

![0004](https://github.com/user-attachments/assets/debeb3a0-c2d0-406d-ab67-f2a2a8b4b168)

**Comment by Colorjet3** [comment]
Please download the latest dev daily build #12980 (as of this writing).  That feature is now available in this version.

go to openshot.org/download/#daily.  If you are running Windows, then download the .exe and install.  If you are running Linux, you should download the AppImage.

Let us know if build #12980 met your needs.

**Comment by Phuxxi** [comment]
> Please download the latest dev daily build #12980 (as of this writing). That feature is now available in this version.
> 
> go to openshot.org/download/#daily. If you are running Windows, then download the .exe and install. If you are running Linux, you should download the AppImage.
> 
> Let us know if build #12980 met your needs.

This actually works very well..... A touch unique, but not a great mystery to unravel. An explainatory note on how to use the settings would be helpful.

Good interface, and it's very flexible - to reuse the last saving location / settings used - it's very clever actually.

It allows for locked in settings and easy shifting to new settings when the occasion arises.

And it's pretty simple and easy to do.

But as a new and much needed feature - it needs to be advertised....

**Comment by Colorjet3** [comment]
That is awesome @Phuxxi.

Please note that the version you are running is in development and not production at this time.  This is why there is no documentation for it, yet.

Yes, it will be advertised and many other enhancements as well that are in build #12980.
