### ISSUE TITLE
Getting unknown error: "error while exporting raw video frame"

### ISSUE THREAD

**Issue by candygoddess** [OpenShot/openshot-qt#5653]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 3.2.1
- libopenshot Version:  0.3.3
- Platform: Windows-10-10.0.19041
- Processor: AMD64 Family 23 Model 24 Stepping 1, AuthenticAMD
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Skipped this step

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/9ogjomrkfbpdpywo6iv712kz6ygrsoqi/openshot-qt.zip) (9 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
Typically this is caused due to lack of free disk space on your computer.  Free up as much disk space as possible and try again.

**Comment by Colorjet3** [comment]
Hello @candygoddess Any update on this?

**Comment by candygoddess** [comment]
Hi, yes I apologize!
It was the disk space, I was able to complete the project with no issues after deleting some files. Thank you for your help!

Sent via the Samsung Galaxy S24, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
