### ISSUE TITLE
#56440 audio out of sync 

### ISSUE THREAD

**Issue by drnmy120** [OpenShot/openshot-qt#5656]
**Describe the bug:**

**Steps to reproduce the behavior:**

**Expected behavior:**

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by drnmy120** [comment]
#56440 audio out of sync 1 sec different  
 operation sys : Win 11
  log files don't find. 
  I can't install the English version. I choose English during installation, but it installs in Hungarian.

**Comment by Colorjet3** [comment]
Hello @drnmy120.  When you install OpenShot it will set the language to the Locality of your operating system.  So, if you Windows 11 is installed as Hungarian, that is what it will default to.

Once you install OpenShot, you can go to Edit | Preference | General tab and change the "Language" from Default to whatever you want the language to be.

For your audio sync issue give this a try:
1.  Run your video/audio file through a converter like VLC, Handbrake, or ShutterEncoder and convert it to a .mp4 file again but obviously with a new name.
2.  Now import this new file you created into OpenShot and preview to see if the audio is now in sync with the video.
