### ISSUE TITLE
#5644 audio out of sync 1 sec different   operation sys : Win 11 log files don't find. I can't install the English version. I choose English during installation, but it installs in Hungarian.

### ISSUE THREAD

**Issue by drnmy120** [OpenShot/openshot-qt#5658]
**Describe the bug:**

**Steps to reproduce the behavior:**

**Expected behavior:**

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
Hello @drnmy120 What is your primary language and what is your computer Windows 11 primary language?  If that is set to Hungarian, then OpenShot will by default match the operating system default language.  If you want to see OpenShot in English, then, after installation, need to go to Edit  | Preferences | General tab and change the Language setting from Default to English.  Restart OpenShot and it should be in English.

**Audio Sync issue.**  Is the audio sync issue happening during the editing process and/or in the final Export?  Audio sync issues have been reported by users during the editing process.  However, once the project has been Exported, the audio sync issue disappears.  Please confirm this either way.

Update:  In the Search box from the Desktop type "about your pc" without the quote and run it.  Please provide the following in the Windows specifications section:

Edition:  Windows 11 Pro or Windows Home?

Version:  23h2?  24h2? etc?

**Comment by Colorjet3** [comment]
No response from OP.
