### ISSUE TITLE
Open shot won't open 

### ISSUE THREAD

**Issue by gilmor200** [OpenShot/openshot-qt#5659]
I closed open shot through the file menu,
Click quit and now won't open again

I don't see my project 

I tried to use Msys and open with debug but could not go all the way in the process. I get a bad command text:

 MSYS /c/Program Files/OpenShot Video Editor
$ gdb openshot-qt.exe
-bash: gdb: command not found

**Comment by Colorjet3** [comment]
I am going to assume that you are running OpenShot v3.2.1.  Please do this:

1.  Make a backup of c:\users\username\.openshot_qt folder.
2.  Try starting OpenShot.  If it starts then you are all good.  If not, continue....
3.  Go to add or remove programs and uninstall OpenShot.
4.  Delete c:\users\username\.openshot_qt folder.  Be sure you performed step 1 above first.
5.  Delete c:\program files\openshot video editor folder.  This will require administrative rights.
6.  Download a fresh copy of the binaries from openshot.org.
7.  Install it and start OpenShot.

**Comment by Colorjet3** [comment]
No response from OP.
