### ISSUE TITLE
The Sound scratches (is stuttering) after export

### ISSUE THREAD

**Issue by juckendesAuge** [OpenShot/openshot-qt#566]
Hello,

* Operating System / Distro: Fedora release 25 (Twenty Five)
* OpenShot Version: 2.3.1

After 1 Minute the Sound becomes scratches. (After the 1 Minute i have a new Video add. the First was cut after 1 Minute).
https://youtu.be/qWvHl-o9ZZQ

The Music and the Soundfiles are all downloaded from Youtube
https://www.youtube.com/audiolibrary/music (Orange Topher Mohr and Alex Elena)
and
https://www.youtube.com/audiolibrary/soundeffects
Car Horn
City Traffic
Medium Bell Ringing Far

You can download for tests the Project Data and all the files here:
http://login.as35684.net/~julian/Timelaps/

For correct files i have add  md5 hashes for every file.

Sorry for my bad english

**Comment by juckendesAuge** [comment]
Over 1 Month ago and nothing have seen the video on yt?
The new version 2.3.3 crash after open the old Projectfile...

**Comment by DylanC** [comment]
@juckendesAuge - Thanks. I will take a look at this.

**Comment by DylanC** [comment]
Tested on Fedora 25 with VM. Cannot reproduce this one in the daily build.
