### ISSUE TITLE
Not launching anymore on VDI

### ISSUE THREAD

**Issue by gituser317** [OpenShot/openshot-qt#5665]
**Describe the bug:**
OpenShot is not launching anymore on Windows 11 virtual desktop. I can confirm that it was working fine some time ago on version 3.1.1 but now, version 3.1.1 and 3.2.1 are not working (same behaviour).

Windows 11 23H2 on VMware with VMware Tools 4.5.0.
The openshot log is empty - indeed the following error is logged on Windows Eventlog:

Name der fehlerhaften Anwendung: openshot-qt.exe, Version: 3.2.1.0, Zeitstempel: 0x607466f6
Name des fehlerhaften Moduls: vm3dgl64.dll, Version: 3.6.0.0, Zeitstempel: 0x66a16726
Ausnahmecode: 0xc0000005
Fehleroffset: 0x0000000000e3696d
ID des fehlerhaften Prozesses: 0x0x188C
Startzeit der fehlerhaften Anwendung: 0x0x1DB44B372A058D7
Pfad der fehlerhaften Anwendung: C:\Program Files\OpenShot Video Editor\openshot-qt.exe
Pfad des fehlerhaften Moduls: C:\Windows\SYSTEM32\vm3dgl64.dll
Berichtskennung: 060a586d-fb00-4533-880c-e7961bbefb75
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:

**Comment by Colorjet3** [comment]
Please try the following:
1.  Make a backup of c:\users\username\.openshot_qt folder.
2.  Delete c:\users\username\.openshot_qt folder.
3.  Start OpenShot.  If it started then great.  If not, continue to step 4.
4.  Download a fresh copy of v3.2.1.
5.  Go to add or remove programs and uninstall OpenShot.
6.  Reinstall using the new copy of the installation binaries.
7.  Did this fix the issue?

**Comment by gituser317** [comment]
Hi @Colorjet3, we can close this thing. We found out that it's related to VMware Tools 12.5.0. If we downgrade VMware Tools to 12.4.5 everything is working again.

**Comment by Colorjet3** [comment]
Thank you @gituser317.  I am not positive if the lead developer support OpenShot running on VMware, but if you ever figure out the issue it would be great if you post it here.

Best of luck with your project(s).

**Comment by gituser317** [comment]
For anyone else having this issue: In the meantime Broadcom confirmed a bug which causes problems with vm3dgl64.dll. That dll is a component of VMware's 3D graphics virtualization. It handles OpenGL for virtual environments. It is suspected to fail due to compatibility issues with VMware Tools 12.5. Just downgrade VMware Tools or wait for the fix to update yours.
