### ISSUE TITLE
Crash at startup on a brand new HP Win11 PC. No output, no logs, nothing...

### ISSUE THREAD

**Issue by roscofil** [OpenShot/openshot-qt#5666]
**Describe the bug:**
Purchased a brand new HP Victus 15L PC with 16Gb RAM, SSD 512 Gb and a 1Tb HDD and an Intel Arc 380 graphics card.
Installed the application ok.
At startup, the app crashes, creates the basic set (I guess) of directories under c:\users\philippe\.ope,shot-qt directory bu nothing else, no logfiles, no openshot.settings file.
I read your Common Issues page, uninstalled and removed directories probably 3 times, tried the daily build and yet, nothing happens.

Event Log event is below(translated from French):

Faulty AppName: openshot-qt.exe, version : 3.2.1.0, timestamp: 0x607466f6
Faulty Module Name: igd12um64xeh.dll, version : 31.0.101.5592, timestamp: 0x66725975
Exception code: 0xc0000409
Fault offset: 0x0000000000f08908
Faulty Process Id: 0x2FE4
Faulty App Start Time: 0x1DB47329948C0BA
Faulty App Path: C:\Program Files\OpenShot Video Editor\openshot-qt.exe
Faulty Module Path: C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch_d.inf_amd64_61c0f936bd4ab014\igd12um64xeh.dll
Report Id: b3822ad1-afd4-4195-ba4c-06439e91e720

**Steps to reproduce the behavior:**

Not sure there are any other steps that click the appname and try to run it....

**Expected behavior:**
Just that the application starts and runs...

**System Details:**
- OpenShot Version: 3.2.1
- Operating System / Distro: Windows 11 24H2

**Log Files:**
None created

**Exception / Stacktrace:**
Faulty AppName: openshot-qt.exe, version : 3.2.1.0, timestamp: 0x607466f6
Faulty Module Name: igd12um64xeh.dll, version : 31.0.101.5592, timestamp: 0x66725975
Exception code: 0xc0000409
Fault offset: 0x0000000000f08908
Faulty Process Id: 0x2FE4
Faulty App Start Time: 0x1DB47329948C0BA
Faulty App Path: C:\Program Files\OpenShot Video Editor\openshot-qt.exe
Faulty Module Path: C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch_d.inf_amd64_61c0f936bd4ab014\igd12um64xeh.dll
Report Id: b3822ad1-afd4-4195-ba4c-06439e91e720

**Screenshots:** (Optional)
None possible

**Comment by Colorjet3** [comment]
This may be related to you display driver issue.  Try reinstalling the display driver on your new computer:  https://support.microsoft.com/en-us/windows/update-drivers-manually-in-windows-ec62f46c-ff14-c91d-eead-d7126dc1f7b6.

It would be best if you go to the HP web sit and find the latest display driver for your pc.  Additionally, complete any other updates available.  Once you have completed this, I recommend you reinstall Openshot by doing this:

1.  Go to add or remove programs, find OpenShot and uninstall it.
2.  Delete c:\program files\openshot video editor folder.  The uninstall most likely did not delete it for you.  You will need administrative rights to do this.
3.  Delete c:\users\phillippe\.openshot_qt folder, if one exists.
4.  Download a fresh version of OpenShot from openshot.org.
5.  Install it and try again.

**Comment by roscofil** [comment]
Yep,

You were right…It’s due to a display driver issue, BUT:


  *   Going to the HP website and downloading the supposedly up-to-date Intel driver did not do anything any better
  *   I had to go to the Intel website and download the appropriate tools….

Thx much for giving me a heads up on this so that I can continue using your very nice and useful application!

Cheers from Paris, France

Philippe

De : Colorjet3 ***@***.***>
Envoyé : jeudi 5 décembre 2024 22:10
À : OpenShot/openshot-qt ***@***.***>
Cc : roscofil ***@***.***>; Author ***@***.***>
Objet : Re: [OpenShot/openshot-qt] Crash at startup on a brand new HP Win11 PC. No output, no logs, nothing... (Issue #5666)


This may be related to you display driver issue. Try reinstalling the display driver on your new computer: https://support.microsoft.com/en-us/windows/update-drivers-manually-in-windows-ec62f46c-ff14-c91d-eead-d7126dc1f7b6.

It would be best if you go to the HP web sit and find the latest display driver for your pc. Additionally, complete any other updates available. Once you have completed this, I recommend you reinstall Openshot by doing this:

  1.  Go to add or remove programs, find OpenShot and uninstall it.
  2.  Delete c:\program files\openshot video editor folder. The uninstall most likely did not delete it for you. You will need administrative rights to do this.
  3.  Delete c:\users\phillippe.openshot_qt folder, if one exists.
  4.  Download a fresh version of OpenShot from openshot.org.
  5.  Install it and try again.

**Comment by Colorjet3** [comment]
This is great and you are welcome.  Best of luck with your project(s).
