### ISSUE TITLE
On a timeline track, when draging the right-side of and image to change the duration the image dissapears.

### ISSUE THREAD

**Issue by warrengay** [OpenShot/openshot-qt#5669]
**Describe the bug:**

**Steps to reproduce the behavior:**

**Expected behavior:**

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
Hello @warrengay.

1.  What operating system/version are you running (windows 10 pro? ubuntu 22.04 lts? etc?)
2.  Which version of OpenShot are you running (help | about openshot)?
3.  Does this happen with all image files or just this one?
4.  Start OpenShot, click on the Emoji tab, and drag an emoji onto a track.
5.  Now grab the right edge and drag it to the right and let go.  Did this work?

A video recording of yoru issue would be great to see as I am unable to replicate this issue in my environment (windows 11 pro and openshot v3.2.1).

**Comment by Colorjet3** [comment]
No response from OP.
