### ISSUE TITLE
Como instalar más efectos / How to install more effects

### ISSUE THREAD

**Issue by Fulgenl** [OpenShot/openshot-qt#567]
ES:
Hola buenas,
me he instalado la versión2.2  en Windows 10 hace poco y esta muy bien editor.
Pero he visto tengo pocos efectos de video, pero he visto que otros usaurios tienen muchos más efectos, como el chroma key, Cartoon... Donde los puedo instalar o como hacer para que me aparezcan? Gracias

EN:
Hello,
I installed version 2.2 on Windows 10 recently and this is a very good editor.
But I have seen few video effects, but I have seen that other usaurios have many more effects, such as the chroma key, Cartoon ... Where can I install them or how to make them appear to me? Thank you

**Comment by DylanC** [comment]
@Fulgenl - Hi there, at the moment the editor does not have many effects. More will be added in the future as the effects need to be re-created for the v2 series. Thanks.

ES
Hola, en este momento el editor no tiene muchos efectos. Se agregarán más en el futuro ya que los efectos deben ser recreados para la serie v2. Gracias.
