### ISSUE TITLE
Open Shot will not open with Windows 11 24H2 on Lenovo

### ISSUE THREAD

**Issue by kerrywales04** [OpenShot/openshot-qt#5674]
I have a new laptop Lenovo Yoga Pro 9 with Windows 11 Home 32 Gb RAM 24H2 Version 10.0.26100 Build 26100
Processor is Intel(R) Core(TM) Ultra 9 185H   2.30 GHz using Intel Arc Graphics and NVIDIA GeForce RTX 4060 Laptop GPU

I have installed latest stable OpenShot 3.2.1 (as of 19/12/24).

OpenShot is installed on my iMacs and 4 year old Lenovo Laptop. All is brilliant on the other kit.

Install is clean and no errors showed. I have a shortcut on my desktop and taskbar.

**Describe the bug:**
double click icon to start app flashes but app does not start

**Expected behavior:**
app to start

This was in another thread and I copied the solution of executing from CMD. The app starts and this is the content from the DOS box.
The app does not start from the shortcut

C:\Program Files\OpenShot Video Editor>.\openshot-qt-cli.exe
Loaded modules from: C:\Program Files\OpenShot Video Editor
INFO app: ------------------------------------------------
INFO app:             Thu Dec 19 18:29:18 2024
INFO app:               Starting new session
INFO app: ------------------------------------------------
INFO app:             OpenShot (version 3.2.1)
INFO app: ------------------------------------------------
INFO app: openshot-qt version: 3.2.1
INFO app: libopenshot version: 0.3.3
INFO app: platform: Windows-10-10.0.26100
INFO app: processor: Intel64 Family 6 Model 170 Stepping 4, GenuineIntel
INFO app: machine: AMD64
INFO app: python version: 3.8.9
INFO app: qt5 version: 5.15.2
INFO app: pyqt5 version: 5.15.4
INFO app: Frozen version info from build server:
{
    "build_name": "OpenShot-v3.2.1-release-candidate-12654-044bb224-23713d3a",
    "date": "2024-07-10 21:02",
    "libopenshot": {
        "CI_COMMIT_REF_NAME": "develop",
        "CI_COMMIT_SHA": "044bb2243ffb4230dea4c30429e86fee963ec1b1",
        "CI_JOB_ID": "38887",
        "CI_PIPELINE_ID": "12542",
        "CI_PROJECT_NAME": "libopenshot",
        "SO": "26",
        "VERSION": "0.3.3"
    },
    "libopenshot-audio": {
        "CI_COMMIT_REF_NAME": "develop",
        "CI_COMMIT_SHA": "23713d3a767cba1568729bc760b66f912ba710f4",
        "CI_JOB_ID": "38869",
        "CI_PIPELINE_ID": "12535",
        "CI_PROJECT_NAME": "libopenshot-audio",
        "SO": "9",
        "VERSION": "0.3.3"
    },
    "openshot-qt": {
        "CI_COMMIT_REF_NAME": "release-20240709",
        "CI_COMMIT_SHA": "637beec94d467ad6cde32d52647fbb271aabf199",
        "CI_JOB_ID": "39198",
        "CI_PIPELINE_ID": "12654",
        "CI_PROJECT_NAME": "openshot-qt",
        "SO": null,
        "VERSION": "3.2.1"
    }
}
INFO project_data: Setting profile to HD 720p 30 fps
INFO project_data: Apply default audio playback settings: 48000, 2 channels
INFO app: checking babl_ext_path: C:\Program Files\OpenShot Video Editor\lib\babl-ext
INFO app: setting BABL_PATH: C:\Program Files\OpenShot Video Editor\lib\babl-ext
INFO language: Qt Detected Languages: ['en-US']
INFO language: LANG Environment Variable:
INFO language: LOCALE Environment Variable:
INFO language: OpenShot Preference Language: Default
INFO logger_libopenshot: Connecting to libopenshot with debug port: 5556
INFO ui_util: Initializing UI for MainWindow
INFO thumbnail: Starting thumbnail server listening on ('127.0.0.1', 50411)
INFO webkit: WebKit backend initializing
INFO transition_model: updating transitions model.
INFO version: Found current version: {'openshot_version': '3.2.1', 'trans_rate_unstable': 0.001, 'trans_rate_stable': 0.01, 'error_rate_stable': 0.25, 'error_rate_unstable': 0.05}
INFO effects_model: updating effects model.
INFO emoji_model: updating emoji model.
INFO webkit: Registering objects with WebKit
INFO sentry: Sentry initialized for 'production': 0.25 sample rate, 0.01 transaction rate
INFO main_window: InitCacheSettings
INFO main_window: cache-mode: CacheMemory
INFO main_window: cache-limit-mb: 512
INFO main_window: cache-ahead-percent: 0.7
INFO main_window: cache-preroll-min-frames: 24
INFO main_window: cache-preroll-max-frames: 48
INFO main_window: cache-max-frames: 600
INFO main_window: Creating CacheMemory object with 536870912 byte limit
INFO preview_thread: QThread Start Method Invoked
INFO main_window: Cleared temporary files: C:\Users\kerry\.openshot_qt\thumbnail
INFO main_window: Cleared temporary files: C:\Users\kerry\.openshot_qt\blender
INFO main_window: Cleared temporary files: C:\Users\kerry\.openshot_qt\title
INFO base: Setting font to C:\Program Files\OpenShot Video Editor\images\fonts\Ubuntu-R.ttf
INFO ui_util: Initializing UI for MainWindow
INFO theme: Setting Fusion dark palette
INFO main_window: updateStatusChanged
INFO main_window: recover_backup
INFO project_data: Setting profile to HD 720p 30 fps
INFO project_data: Apply default audio playback settings: 48000, 2 channels
INFO video_widget: Load: Set video widget display aspect ratio to: 1.7777777910232544
INFO video_widget: Set video widget pixel aspect ratio to: 1.0
INFO main_window: updateStatusChanged
INFO timeline: Qt Ready
INFO timeline: Angular Ready
INFO timeline: Adjusting max size of preview image: 1520x856

As a test, I told the shortcut to start with "Run as Administrator" set. This results in a dialog boxes asking if the app from an unknown publisher is allowed to change settings. I say yes

The app does not start

**Comment by Colorjet3** [comment]
Hello @kerrywales04 Is it possible to disable the Intel Arc Graphics, temporarily, to see if OpenShot will start?

**Comment by kerrywales04** [comment]
I'll give it a go. I would suspect the nVideo more. I am not sure what capabilities it has or to control them. But starting it from the CMD box works.

I have to say, I have created a .CMD file with the two lines
CD ...
.\....

And that works

**Comment by kerrywales04** [comment]
> Hello @kerrywales04 Is it possible to disable the Intel Arc Graphics, temporarily, to see if OpenShot will start?

Your comment gave me an idea. I have found that on Win 11 the Graphics settings allow me to manage a program list and set which graphics processor to use. It defaults to use ARC and then upgrade it according to the app needs. I added OpenShot and told it to only use the nVideo graphic processor and it works like a dream

**Comment by Colorjet3** [comment]
That is awesome @kerrywales04.  OpenShot at this time does not take advantage of hardware acceleration (GPU) so you are not missing much.  Make sure you do NOT enable hardware acceleration in Edit | Preferences | Performance tab as it will cause other issues.

Hardware acceleration is in the queue to be fixed.  No ETA at this time.

I am going to close this ticket but have asked the lead developer to look at this to see if this is something he thinks OpenShot should/would support (Intel Arc GPU).
