### ISSUE TITLE
'Click display > show waveform' lives on after track deleted and OpenShot is quit

### ISSUE THREAD

**Issue by David-Else** [OpenShot/openshot-qt#568]
**System Details:**
* Operating System / Distro: Fedora 25
* OpenShot Version: 2.3.1
* _Please attach log files if crash_
n/a
**Issue Description and steps to reproduce:**

1. Drag a full length .mkv 720p movie into the timeline, or drag a full length 480p .AVI movie also.
2. Click display > show waveform

Wait a million years, the CPU is going crazy, no waveform. It is either just taking so long there is no point in the option, or has crashed. There is NO quit button, that would be good :)

3. Delete the clip

The CPU is still going crazy, most of the systems RAM is being used, the task has not ended.

4. Quit Openshot

Openshot is STILL running in the system monitor, the CPU is still going crazy.

You need to kill the process to get your CPU and memory back again.

Thanks for the software, it is appreciated. Keep up the good work!

**Comment by DylanC** [comment]
@David-Else - When I closed OpenShot the process did not continue for me. However, the waveform generation was taking a million years. So that part is a bug really and should be looked at.

**Comment by David-Else** [comment]
I’m closing this issue because it has been inactive over a year. This probably means that it is not reproducible or it has been fixed in a newer version.

Please reopen if you still encounter this issue with the latest stable version.

Thank you!
