### ISSUE TITLE
Cannot Export Video - Unhandled Exception

### ISSUE THREAD

**Issue by WhitleyStriber** [OpenShot/openshot-qt#569]
**System Details:**
`Linux Aphex 4.10.8-1-ARCH #1 SMP PREEMPT Fri Mar 31 16:50:19 CEST 2017 x86_64 GNU/Linux`
* Operating System / Distro: Arch Linux with i3wm - Dell XPS 9550
* OpenShot Version: `openshot-qt 2.0.6-2`
```
     ui_util:INFO Initializing UI for Dialog
     ui_util:WARNING Icon theme media-playback-start not found. Will use backup icon.
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/openshot_qt/windows/main_window.py", line 626, in actionExportVideo_trigger
    win = Export()
  File "/usr/lib/python3.6/site-packages/openshot_qt/windows/export.py", line 88, in __init__
    get_app().window.timeline_sync.timeline.ClearAllCache()
  File "/usr/lib/python3.6/site-packages/openshot.py", line 3967, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, Timeline, name)
  File "/usr/lib/python3.6/site-packages/openshot.py", line 80, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'Timeline' object has no attribute 'ClearAllCache'
     metrics:INFO Track metric: {'access-control-allow-origin': '*', 'date': 'Wed, 05 Apr 2017 18:27:42 GMT', 'pragma': 'no-cache', 'expires': 'Mon, 01 Jan 1990 00:00:00 GMT', 'last-modified': 'Sun, 17 May 1998 03:00:00 GMT', 'x-content-type-options': 'nosniff', 'content-type': 'image/gif', 'server': 'Golfe2', 'content-length': '35', 'cache-control': 'no-cache, no-store, must-revalidate', 'age': '112196', 'status': '200', 'content-location': 'http://www.google-analytics.com/collect?cid=74fa7525-de47-4209-9754-eb57af08b261&v=1&tid=UA-4381101-5&an=OpenShot+Video+Editor&aip=1&aid=org.openshot.openshot-qt&av=2.3.1&ul=en&ua=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&cd1=0.1.3&cd2=3.6.0&cd3=5.8.0&cd4=5.8&cd5=arch--&t=screenview&cd=export-screen'} (b'GIF89a\x01\x00\x01\x00\x80\xff\x00\xff\xff\xff\x00\x00\x00,\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x02D\x01\x00;')
     metrics:INFO Track exception: {'date': 'Fri, 07 Apr 2017 01:40:26 GMT', 'server': 'Apache/2.2.22 (Ubuntu)', 'vary': 'Accept-Encoding', 'content-length': '29', 'content-type': 'text/html; charset=utf-8', 'status': '200', '-content-encoding': 'gzip'} (b'*duplicate-exception-ignored*')
```

**Issue Description and steps to reproduce:**
Create any video and export it. No window appears and you cannot export any type of video.

**Comment by bsommers** [comment]
I'm getting the same thing on 2.3.1  On Ubuntu 16.04

Linux flash 4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

<details>
link SVGID_18_-5 hasn't been detected!
link SVGID_18_-5 hasn't been detected!
link SVGID_22_-5 hasn't been detected!
link SVGID_24_-2 hasn't been detected!
link SVGID_24_-2 hasn't been detected!
     ui_util:INFO Initializing UI for Dialog
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/main_window.py", line 626, in actionExportVideo_trigger
    win = Export()
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/export.py", line 88, in __init__
    get_app().window.timeline_sync.timeline.ClearAllCache()
  File "/usr/lib/python3/dist-packages/openshot.py", line 4108, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, Timeline, name)
  File "/usr/lib/python3/dist-packages/openshot.py", line 74, in _swig_getattr
    return _swig_getattr_nondynamic(self, class_type, name, 0)
  File "/usr/lib/python3/dist-packages/openshot.py", line 69, in _swig_getattr_nondynamic
    return object.__getattr__(self, name)
AttributeError: type object 'object' has no attribute '__getattr__'
...
     metrics:INFO Track exception: {'content-type': 'text/html; charset=utf-8', '-content-encoding': 'gzip', 'server': 'Apache/2.2.22 (Ubuntu)', 'date': 'Fri, 07 Apr 2017 03:12:33 GMT', 'content-length': '29', 'vary': 'Accept-Encoding', 'status': '200'} (b'*duplicate-exception-ignored*')
</details>

**Comment by RomaneGreenTurtle** [comment]
It s the same thing with windows 7
OpenShot-v2.3.1-x86_64

**Comment by TakeonMe** [comment]
To me it happens exactly the same, my operating system is Antergos (Arch)

**Comment by mat-mo** [comment]
Same here.

**Comment by ceesco53** [comment]
Same thing - Arch 64bit

`
     ui_util:INFO Initializing UI for Dialog
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/openshot_qt/windows/main_window.py", line 626, in actionExportVideo_trigger
    win = Export()
  File "/usr/lib/python3.6/site-packages/openshot_qt/windows/export.py", line 88, in __init__
    get_app().window.timeline_sync.timeline.ClearAllCache()
  File "/usr/lib/python3.6/site-packages/openshot.py", line 3967, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, Timeline, name)
  File "/usr/lib/python3.6/site-packages/openshot.py", line 80, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'Timeline' object has no attribute 'ClearAllCache'
     metrics:INFO Track metric: {'access-control-allow-origin': '*', 'date': 'Mon, 03 Apr 2017 14:16:00 GMT', 'pragma': 'no-cache', 'expires': 'Mon, 01 Jan 1990 00:00:00 GMT', 'last-modified': 'Sun, 17 May 1998 03:00:00 GMT', 'x-content-type-options': 'nosniff', 'content-type': 'image/gif', 'server': 'Golfe2', 'content-length': '35', 'cache-control': 'no-cache, no-store, must-revalidate', 'age': '614938', 'status': '200', 'content-location': 'http://www.google-analytics.com/collect?cid=15862c17-1a58-4675-8326-619a167c43a4&v=1&tid=UA-4381101-5&an=OpenShot+Video+Editor&aip=1&aid=org.openshot.openshot-qt&av=2.3.1&ul=en&ua=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&cd1=0.1.3&cd2=3.6.0&cd3=5.8.0&cd4=5.8&cd5=arch--&t=screenview&cd=export-screen'} (b'GIF89a\x01\x00\x01\x00\x80\xff\x00\xff\xff\xff\x00\x00\x00,\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x02D\x01\x00;')
     metrics:INFO Track exception: {'date': 'Mon, 10 Apr 2017 17:07:56 GMT', 'server': 'Apache/2.2.22 (Ubuntu)', 'vary': 'Accept-Encoding', 'content-length': '29', 'content-type': 'text/html; charset=utf-8', 'status': '200', '-content-encoding': 'gzip'} (b'*duplicate-exception-ignored*')
`

**Comment by sphrak** [comment]
I am experiencing exactly the same as @ceesco53 also on Arch x64.

**Comment by ankitpati** [comment]
May I request everyone to try the latest [AppImage](https://github.com/OpenShot/openshot-qt/releases/download/v2.3.1/OpenShot-v2.3.1-x86_64.AppImage "OpenShot 2.3.1"), and let us know if the issue persists?

OpenShot 2.0.6 appears quite old; the latest is 2.3.1.

**Comment by sphrak** [comment]
Hi @ankitpati I tried the latest AppImage and it worked. However I am pretty sure the same version (2.3.1) is available in repo on archlinux and it was the version I runned into the error with. Currently http://archlinux.org/  is down so cant double check version, so not sure what happened there.. but I guess it works at least with the AppImage..

Regards

```


```

**Comment by bsommers** [comment]
I tried the AppImage.   I got further along in processing the video as opposed to a crash when hitting Export.    Now in my case at 71% through my output, I got the following with no additional detail:

Caught signal 11 (SIGSEGV)
---- Unhandled Exception: Stack Trace ----
<details>
[libx264 @ 0x3505440] VBV underflow (frame 7270, -181072 bits)
[libx264 @ 0x3505440] VBV underflow (frame 7282, -180744 bits)
[libx264 @ 0x3505440] VBV underflow (frame 7294, -181152 bits)
[libx264 @ 0x3505440] VBV underflow (frame 7306, -182280 bits)
[libx264 @ 0x3505440] VBV underflow (frame 7318, -182456 bits)
[libx264 @ 0x3505440] VBV underflow (frame 7330, -184152 bits)
[libx264 @ 0x3505440] VBV underflow (frame 7342, -183360 bits)
[libx264 @ 0x3505440] VBV underflow (frame 7354, -182776 bits)
Caught signal 11 (SIGSEGV)
---- Unhandled Exception: Stack Trace ----

</details>

**Comment by ankitpati** [comment]
@sphrak Please contact your distro packagers to resolve the issues with the packages in your repositories. One possible cause is that OpenShot 2.3.0 and 2.3.1 were released in quick succession, and 2.3.0 is known to be buggy. The maintainer may have missed the minor version bump because it was basically only announced on the internal Slack channels.

**Comment by namelivia** [comment]
I am also using Openshot from the Archlinux repos, if I execute `openshot-qt --version` I get `logger:INFO OpenShot version 2.3.1`. However whenever I click the export button for exporting a video nothing happens and I can see on the therminal the same exception as mentioned above:
`AttributeError: 'Timeline' object has no attribute 'ClearAllCache'`

**Comment by ankitpati** [comment]
@namelivia Thank you for the detailed analysis and prompt report to your distro maintainer. Please notify us when the packages are fixed there, so we can close this issue.

**Comment by bsommers** [comment]
I made an interesting find.  On my Ubuntu 16.04 system, I tried switching from my preferred default  Python 3.6.0 back to python 3.5.2 and I was able to export the video successfully.     I will see if I can replicate this on my Windows 10 system (also using Python 3.6.0 from Anaconda 4 package)

I ran from the git clone'd copy I pulled on Apr 12.  executing:

`
python3 src/launch.py
`

Here are my versions:

```
~/src/openshot/openshot-qt$ ~/anaconda4/bin/python3 --version
Python 3.6.0 :: Anaconda 4.3.1 (64-bit)
~/src/openshot/openshot-qt$ which python3 
/usr/bin/python3
~/src/openshot/openshot-qt$ python3 --version
Python 3.5.2
```

**Comment by ceesco53** [comment]
Arch 64 bit is working fine for me now.

I'm running:

community/libopenshot 0.1.4-1 [installed]
community/libopenshot-audio 0.1.2-1 [installed]
community/openshot 2.3.1-1 [installed]

**Comment by namelivia** [comment]
Thanks @ceesco53 for the notification. The library has been updated on the Arch repos so @ankitpati you can close the issue.

**Comment by ankitpati** [comment]
@namelivia Thank you for the quick updates and the heads-up.

Closing this as fixed.
