### ISSUE TITLE
Wish: Backspace key to remove clips (to support laptops)

### ISSUE THREAD

**Issue by jarlarntzen** [OpenShot/openshot-qt#57]
The delete now works wonderfully on my Ubuntu 14.04 LTS, which has a full keyboard including a delete key and numpad. Now, it does not work as well on my MacBook Pro which doesn't have a Delete key.

I would recommend adding the Backspace key in addition to the Delete key for all kinds of deletions: clips, imported files, transitions etc. Very fast, natural and easy to use.

Thanks.

**Comment by jonoomph** [comment]
I've attempted this twice now... and each time I get hung up. The backspace key is already being captured by some other element on the interface (not sure which one yet... maybe the timeline webview). So, I'm not able to capture the backspace key at the moment, until I figure it out. =)

**Comment by jonoomph** [comment]
Okay, I found it. Newest build supports Backspace key. =)

**Comment by jarlarntzen** [comment]
Yeeeeah :+1
