### ISSUE TITLE
無法開啟專案

### ISSUE THREAD

**Issue by happy4929** [OpenShot/openshot-qt#570]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
請問要怎麼解決無法開啟專案之問題?

**Comment by ankitpati** [comment]
None of the OpenShot developers or collaborators I know of speaks Chinese, so kindly consider filing the issue in English.

A rough translation through Google Translate tells me you are unable to open a project. Can you please give some details about the OS, and the OpenShot version you are using?

Finally, assuming you do not understand English at all, please use this link to get the latest OpenShot. It may just solve your issue.

[OpenShot 2.3.1](http://openshot.org/download/)

**Comment by ankitpati** [comment]
Closing due to lack of response.

**Comment by ophelia0126** [comment]
若使用中文檔名可能會導致無法順利儲存與開啟專案。
use english name for your osp file if you can't open it.
