### ISSUE TITLE
Transitions break between source files of different aspect ratios

### ISSUE THREAD

**Issue by JapaMala** [OpenShot/openshot-qt#571]
**System Details:**
Windows 10
Openshot version 2.3.1

**Issue Description and steps to reproduce:**
Put a landscape oriented clip in the timeline, and then a portrait-oriented clip after it, overlapping so an automatic transition is made. The second clip fades in properly, but the first clip simply cuts off at the end of the transition. This is not an issue when the second clip fully covers the first one, but when the first clip is visible partly through the transition, due to different aspect ratios, then it becomes a problem.

**Comment by DylanC** [comment]
@JapaMala - Is this still and issue in the latest daily build?

**Comment by speedytechdev** [comment]
**Closing Warning Reason:** Inactive
