### ISSUE TITLE
Make old version available

### ISSUE THREAD

**Issue by Storm-Engineer** [OpenShot/openshot-qt#572]
At the moment the Beta is completely unusable, it constantly crashes, it's in the wrong language, changing clip properties has no effect, and so on.

Please provide a download for the stable 1.x version so we can use that until the beta becomes usable.

**Comment by ankitpati** [comment]
We already have a [2.3.1 version](http://openshot.org/download/ "OpenShot"), which is pretty stable. Kindly consider using that instead of an older, no longer supported beta version.

Closing as invalid.
