### ISSUE TITLE
After export music glitches out after a minute

### ISSUE THREAD

**Issue by floridasummer** [OpenShot/openshot-qt#573]
**System Details:** 
[DxDiag.txt](https://github.com/OpenShot/openshot-qt/files/914248/DxDiag.txt)

* Operating System / Distro: ? Win 7, just updated 4/10/17
* OpenShot Version: ? The new beta
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
Made two videos. One was about 3 minutes long. I exported it and then watched it and about 30 seconds before it ends the music made a loud buzzing noise then silence the rest of the video. The second video I exported was about 7 minutes long and had two tracks. About two minutes in to the first track the same thing happened; there was a loud buzz and then silence until the time had elapsed when the second track was to begin. When the second track was about 30-40 seconds from ending, again a loud buzz and silence until video ended. 
edit: spellchecking

**Comment by DylanC** [comment]
Could not reproduce this on v2.4.
