### ISSUE TITLE
Silent install

### ISSUE THREAD

**Issue by olivermarshall2** [OpenShot/openshot-qt#576]
Hi

Does the Windows installer support a silent install from a batch file? We need to push this out to some primary school computers and a silent install would be ideal.

Thanks

Olly

**Comment by ankitpati** [comment]
`OpenShot-v2.3.1-x86_64.exe /VERYSILENT`

This will still prompt for UAC, but is the closest to a silent install on Windows.

Linux has completely silent installs, though, if you are in a position to try that.

**Comment by jonoomph** [comment]
If that doesn't work for you, please let us know. If you push this command out with admin permissions, it should prompt for UAC... FYI. But please test on a single computer first, and make sure that works for you. =)

**Comment by MSTigers** [comment]
This worked for me without command prompt with `OpenShot-v2.4.1-x86_64`

However, I didn't get a desktop shortcut out of the deal.
