### ISSUE TITLE
OpenShot doesn't start anymore (Couldn't load user settings file) 

### ISSUE THREAD

**Issue by TomTheDragon** [OpenShot/openshot-qt#577]
It was running fine all the time but it doesn't wanted to start any more one day. I also did some search about the error but I could not find any help so far. 
I am using the newest release of OpenShot and I am running Linuxmint 18 x64 (Ubuntu 16.04) on my machine.

Log:
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
      launch:INFO —----------------------------------------------
      launch:INFO    OpenShot (version 2.3.1)
      launch:INFO —----------------------------------------------
         app:INFO openshot-qt version: 2.3.1
         app:INFO libopenshot version: 0.1.4
         app:INFO platform: Linux-4.4.0-66-generic-x86_64-with-LinuxMint-18.1-serena
         app:INFO processor: x86_64
         app:INFO machine: x86_64
         app:INFO python version: 3.5.2
         app:INFO qt5 version: 5.5.1
         app:INFO pyqt5 version: 5.5.1
   json_data:WARNING Couldn't load user settings file, no data.
         app:ERROR Couldn't load user settings. Exiting.
Couldn't load user settings file, no data.

**Comment by DylanC** [comment]
@TomTheDragon - Can you try to remove the user settings file and launch it again?

**Comment by DylanC** [comment]
Try the above comment as a solution. Closing this ticket due to lack of activity.
