### ISSUE TITLE
Can't come back to "Pointer tool" after using "Cutter tool".

### ISSUE THREAD

**Issue by Frank-Thomas** [OpenShot/openshot-qt#579]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

Hi.

I have never written a bug report before, so I'm bound to get this wrong.

But My problem was that after using the cutter tool on on the video I was editing, there was no way of getting back to the pointer tool. There wars no "Pointer button" to click on at all, and I did not find any shortcut for it either.

So after making one cut, one editing I could not continue :-)

I'm not sure what details you mean, but I have copied my System Info Summary, and I used Version 2.3.1 of OpenShot. It did not crash, just could not use it.

Thanks for a great program. I use it to edit my YouTube videos and it's a great little program for that!

Best regards,
Frank-Thomas.

-Computer-
Processor		: 4x Intel(R) Core(TM) i3-4330 CPU @ 3.50GHz
Memory		: 3984MB (1177MB used)
Operating System		: Ubuntu 16.04.2 LTS
User Name		: rfym (rfym)
Date/Time		: to. 13. april 2017 kl. 16.47 +0200
-Display-
Resolution		: 1920x1200 pixels
OpenGL Renderer		: GeForce GTX 750 Ti/PCIe/SSE2
X11 Vendor		: The X.Org Foundation
-Multimedia-
Audio Adapter		: HDA-Intel - HDA Intel PCH
Audio Adapter		: HDA-Intel - HDA NVidia
-Input Devices-
 Power Button
 Power Button
 Logitech USB Mouse
 HDA Intel PCH Front Mic
 HDA Intel PCH Rear Mic
 HDA Intel PCH Line
 HDA Intel PCH Line Out
 HDA Intel PCH Front Headphone
 HDA NVidia HDMI/DP,pcm		: 3=
 HDA NVidia HDMI/DP,pcm		: 7=
 HDA NVidia HDMI/DP,pcm		: 8=
 Apple Inc. Apple Keyboard
 Apple Inc. Apple Keyboard
-Printers (CUPS)-
Photosmart-C5100-series		: <i>Default</i>
-SCSI Disks-
ATA KINGSTON SV300S3
ATA WDC WD5000AAKS-7

**Comment by Frank-Thomas** [comment]
Ahhh...! I found that by clocking the tool I had selected, like Cutting tool, after I have done my cutting, the marker went back to Pointer tool. So still no pointer tool button, and nothing to say that it's altered from the last version, but now I made it work.

**Comment by ankitpati** [comment]
Closing this as resolved.
