### ISSUE TITLE
WINDOWS: When another video file is inserted, and automatically trasnsicion is generated, the program crashes.

### ISSUE THREAD

**Issue by telelauro** [OpenShot/openshot-qt#58]
When another video file is inserted, and automatically trasnsicion is generated, the program crash.
![laucher exe error](https://cloud.githubusercontent.com/assets/16803007/12509031/17e94d9a-c100-11e5-914c-70c9609b8319.png)

**Comment by jonoomph** [comment]
This Windows bug has been fixed in the latest build. I'm about to release new installers with this fix. Thanks!
