### ISSUE TITLE
fedora 25 and webm

### ISSUE THREAD

**Issue by francescomeloni** [OpenShot/openshot-qt#580]
I installed openshot 2.3.1with appimage and it works very well but i can't import webm files. 
If i install openshot 2.1 from rpmfusion repo there is not problem. 
How can i add webm codec in appimage? 
thanks

**Comment by ankitpati** [comment]
No repro on Ubuntu 16.04 with 2.3.1 AppImage. `webm` files import just fine.

Please launch the AppImage from the terminal,
```
[username@hostname ~]$ ./OpenShot-v2.3.1-x86_64.AppImage
```
try importing a `webm` file, then copy the output from the terminal.

That will help us better diagnose the issue.

**Comment by francescomeloni** [comment]
[matroska,webm @ 0x2add220] Unknown/unsupported AVCodecID V_VP9.
[matroska,webm @ 0x2add220] max_analyze_duration reached
[matroska,webm @ 0x2b3cd20] Unknown/unsupported AVCodecID V_VP9.
[matroska,webm @ 0x2b3cd20] max_analyze_duration reached
 files_model:INFO updating files model.
 main_window:INFO Imported media file /home/vete/Video/Screencast_13-04-2017_00:09:39.webm

thanks

**Comment by DylanC** [comment]
@francescomeloni - This looks like it succeeded. Can you let us know what happened?

**Comment by DylanC** [comment]
@francescomeloni - Try the import again with OpenShot v2.4. It has no problem with webm.
