### ISSUE TITLE
OpenShot/Windows 7, fails to open saved/last project

### ISSUE THREAD

**Issue by MortenB2** [OpenShot/openshot-qt#581]
**System Details:**
* Operating System / Distro: Windows 7/SP1/64b
* OpenShot Version: 2.3.1

**Issue Description and steps to reproduce:**
While reopen OpenShot and trying to load last project, nothing happens, nothing is loaded.
A clue may be, if you instead try to open a project (ctrl-O) you get 3 QT error messages in a row,

![openshot - open projects - 3 equal faults](https://cloud.githubusercontent.com/assets/27488756/25040843/2eb13e80-210c-11e7-8234-2f3207acc3c5.png)

OpenShot do work fine on making a project, most likely also it saves them fine.

Best regards
Morten

**Comment by DylanC** [comment]
@MortenB2 - Still an issue in the latest daily build?

**Comment by DylanC** [comment]
Not able to reproduce on v2.4.1.
