### ISSUE TITLE
NVENC bad codec

### ISSUE THREAD

**Issue by Elrondo46** [OpenShot/openshot-qt#583]
Problem with version 2.2.0, invalid codec with correct nvenc management (100 % ok in OBS,shotcut....)
Can you solve this problem please ?

It's functionnal in openshot 1.4.x

**Comment by phly95** [comment]
How do you even attempt to use NVenc with openshot? Maybe they should add codec options next to quality settings.

**Comment by DylanC** [comment]
@Elrondo46 - How would I test this?

**Comment by andrewhatfield** [comment]
I've found this challenge also.  Is related to hardware acceleration with nvidia graphics cards

**Comment by mikelacsa** [comment]
Hi guys, Just want to check if you're still experiencing this issue with the latest version or daily build?

**Comment by mikelacsa** [comment]
The same issue was raised in [1519](https://github.com/OpenShot/openshot-qt/issues/1519)
