### ISSUE TITLE
Unable to run OpenShot for the first time on Windows 10 x64.

### ISSUE THREAD

**Issue by Xial** [OpenShot/openshot-qt#584]
**System Details:**
* Operating System / Distro: Windows 10 Pro, Anniversary Update, 64-bit.
* OpenShot Version: 2.3.1
* _Please attach log files if crash_
Unable to locate a log file. Sorry about that.

**Issue Description and steps to reproduce:**

Install OpenShot-v2.3.1-x86_64.exe from direct download. Allow the installer to launch OpenShot, or launch it directly from the start menu.
Receive the following pop-up:

```
---------------------------
cx_Freeze: Python error in main script
---------------------------
Traceback (most recent call last):
  File "C:\msys64\mingw64\lib\python3.5\site-packages\cx_freeze-5.0-py3.5-mingw.egg\cx_Freeze\initscripts\Console.py", line 21, in <module>
  File "openshot_qt/launch.py", line 53, in <module>
  File "C:\Program Files\OpenShot Video Editor\classes\app.py", line 34, in <module>
    from PyQt5.QtWidgets import QApplication, QStyleFactory
  File "ExtensionLoader_PyQt5_QtWidgets.py", line 22, in <module>
  File "ExtensionLoader_PyQt5_QtWidgets.py", line 14, in __bootstrap__
  File "C:\msys64\mingw64\lib\python3.5\imp.py", line 342, in load_dynamic
ImportError: DLL load failed: The specified procedure could not be found.

---------------------------
OK   
---------------------------
```

Go into the application directory and try to start with the `launch-win.bat` file. Receive the same error.

Follow instructions to grab the latest daily installer available, `OpenShot-v2.3.1-8-g9cc7efa-50-620-x86_64.exe`, and reinstall.
Receive the same error when launching. 

No `.openshot_qt` folder is generated, resulting in no logs available.

**Comment by Xial** [comment]
I'm going to close this for the following reason:

Suspecting the issue I was having is localized to my specific install of Windows 10 Pro 64-bit. I reinstalled Windows a couple of days ago, and just tried installing again. It installed successfully, and launched with no issues.
Said install of Windows did not have Python installed anywhere, and is currently set up with minimal amounts of my usual software.

Thanks for your time. :)

**Comment by Krzysiu** [comment]
It's not specific, based on own experiences (tried to install it in a few places, no success) and on the other issues with people still having this problem. Setting up pythonpath env var didn't help, creating symbolic link in C:\msys64\mingw64 neither.
