### ISSUE TITLE
Blender does not work

### ISSUE THREAD

**Issue by Ronald221157** [OpenShot/openshot-qt#585]
Windows 10 Operating System
OpenShot Version 2.3.1.-def
Blender 2.78c Path C:\Program Files\Blender

Animated titles gives:
 
![openshot](https://cloud.githubusercontent.com/assets/27556216/25063323/a1fd0420-21e1-11e7-8918-aa3b5145d098.jpg)

Anyone?

**Comment by MikeIronFist** [comment]
You have to include the exact path to the .exe file, as OpenShot can't really do anything with just the folder.

For example, on my Windows installation my Blender path is set to:
`C:\Program Files\Blender Foundation\Blender\blender.exe`

So just make sure your path includes the blender.exe at the end.

**Comment by Ronald221157** [comment]
Thanks,

That is the "trick".
Misunderstood the tutotial.

**Comment by ankitpati** [comment]
@MikeIronFist Thank you for the help.

Closing this as solved.

**Comment by RAWdawg1** [comment]
@ankitpati I've got the same issue but i'm using the correct path just don't know why its not working can you help 
![screenshot 11](https://user-images.githubusercontent.com/38607557/39093298-f24424d8-4614-11e8-8e64-00680c57c2d7.png)

**Comment by ankitpati** [comment]
@RAWdawg1 You need to set the Blender Path to `C:\Program Files\Blender Foundation\Blender\blender.exe`, as mentioned above. Note that the word “blender” appears twice in the path.
