### ISSUE TITLE
Open Shot 2.3.1 windows can't open a project

### ISSUE THREAD

**Issue by rlavolee** [OpenShot/openshot-qt#586]
windows 10 64 bit 
OpenShot Version: 2.3.1
Nothing appends when I use the "Open  Project ..." item and I select a .osp file that I have generated with Open Shot
Thanks

**Comment by JtLively** [comment]
Do you get any error? Did you create the project with the same OpenShot version?

**Comment by rlavolee** [comment]
No error noticeable, no crash and logs aren't helpful either. Yes I used the same version of OpenShot.

**Comment by jerowo** [comment]
Hi,
Same issue here, also W10 x64 and OpenShot 2.3.1
Switch back to 2.2.0 and same problem.
Also thought it could come from saving .osp in a NAS, but same symptoms on local HDD :
 - save any project without error
 - can't open these project : no erreor message of any kind, but nothing happend 

my .osp is attached (renamed in .txt to be uploaded)

[bug sample.txt](https://github.com/OpenShot/openshot-qt/files/926199/bug.sample.txt)

Thanks

**Comment by jerowo** [comment]
Same problem in https://github.com/OpenShot/openshot-qt/issues/581 from @MortenB2 ?

**Comment by MortenB2** [comment]
Yes, I believe this is exact the same problem I experiences on W7 only that W7 give me the attached fault message.  I assume W10 is into treating the user as an idiot (than W7) who do not understand the fault message anyway and then hides it ?

**Comment by rlavolee** [comment]
Can this issue be labeled as `bug` @JtLively ?

**Comment by osve001** [comment]
Fixed!
I tried reinstalling but still not working. Then, I realized that producing a quick test project with names by default it worked. My project folder name (and the .osp file itself) began with 2º. I removed these two first characters (from both folder and project file) and it works. I hope this helps.
Now, I've got another issue related to titles. In my project there are 5 titles (TitleFileName-1.svg to ...-5.svg) and 1 animated title (TitleFilename%04d.png). I'm trying to add another title. After doing it I save the project, close it and when I open it again an error message appears "TitleFileName-6.svg cannot be found". I'm asked to provide a folder, but the file with the title is not in the folder called "assets" (There are only 5 files: TitleFileName-1.svg to -5.svg). Is there a limit for the number of titles? Any ideas?

**Comment by wojciechsura** [comment]
I'm experiencing exactly the same problem in OpenShot 2.3.4 on Windows 7. Saved project yesterday, today I cannot open it. Then created a test project with a single movie fragment, saved, loaded and nothing happened too. No error messages either.

**Comment by mkalam-alami** [comment]
I had the same problem with 2.3.4 + W7, it was caused by an accent in a parent folder as well.

**Comment by petrhnilica** [comment]
Hi,

the same problem. Win 7 64 a czech letters in a name of project. Thanks  @mkalam-alami and others.

Walk around: Use English letters for path (parent folders) and name

**Comment by MikeSoft** [comment]
i've the same problem with Windows 8.1 x64 and openshot 2.4x64

**Comment by DylanC** [comment]
Dup of #677

**Comment by DylanC** [comment]
@rlavolee - Hi guys, this has been confirmed as solved in the latest daily build.

**Comment by DylanC** [comment]
@jerowo @MortenB2 @osve001 - See above comment.

**Comment by rlavolee** [comment]
Thanks, that's a good news. I'm closing the issue then.
