### ISSUE TITLE
Crash during Preview Playback when Time is 'FastForward' 

### ISSUE THREAD

**Issue by reddn** [OpenShot/openshot-qt#587]
**System Details:**  Dell Inspiron Laptop Intel Core i7-6500 (on AC power)
8GB ram, 256 SSD
* Operating System / Distro: Window 10-upto date
* OpenShot Version:  2.3.1
* _Please attach log files if crash_
Where are they?

**Issue Description and steps to reproduce:**
Imported Video file (dash cam 1080p), spliced (some parts were deleted, some were kept, some splices were for the speed up), set time to 4X forward(or 2X), press preview play.  It will play a little bit, about 1-5 seconds, and crash.

Debug
Unhandled exception at 0x00007FFA6E0E3F60 (msvcrt.dll) in launch.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.

If there is a handler for this exception, the program may be safely continued.

**Comment by reddn** [comment]
I started using 2.3.1-8 DEV.  I also transcoded the Dash Cam file(289mB/3min) into a mkv(189mB/3min).  At first I disabled audio via the properties window on all fast forward segments, it worked fine.  I then re-enabled the audio, and it still works.

**Comment by OldMcWeb** [comment]
I have the same issues in 2.3.2 no fast forward feature available
hard crash

**Comment by DylanC** [comment]
Confirmed as fixed in #588
