### ISSUE TITLE
Fast Forward not working

### ISSUE THREAD

**Issue by reddn** [OpenShot/openshot-qt#588]
System Details: Dell Inspiron Laptop Intel Core i7-6500 (on AC power)
8GB ram, 256 SSD

*Operating System / Distro: Window 10-upto date
*OpenShot Version: 2.3.1  & 2.3.1-8(Dev)
*Please attach log files if crash
Where are they?

Split original video(dash cam in my case) change segment to Time > Forward > 4X.  The segment will decrease in length properly.  The playback **sometimes** doesn't crash, when you export it, the video will be normal speed but only the reduced length.

The original video i used was in both a 'raw' format in 1080p(289mB/3min), and converted to mkv using handbrake, both did not work.

**Comment by deadbeatguitarist** [comment]
I have an immediate crash on Debian Stretch using the 2.3.1 Appimage whenever I use any of the Time change settings - In my case I was doing Slow 1/2.

**Comment by deadbeatguitarist** [comment]
@reddn Can you try splitting off the audio from the video track and see if it still happens, I did this and it didn't crash.  Let me know if that solves it for you too.

**Comment by reddn** [comment]
Yes, removing audio on the 2.3.1 release version fixed it.  But the main
problem is when I goto Export the video, the video doesn't Fast Forward.
The video plays in normal speed but for only the new length (eg, if 4x, the
video is shorted to a 1/4 of its original).  I've tried different speeds, 2
4 and 8x.

On Mon, Apr 17, 2017 at 7:01 PM, deadbeatguitarist <notifications@github.com

**Comment by deadbeatguitarist** [comment]
Ok, yeah I hadn't tried that - I just rendered and the render isn't slowed down down, but in Openshot the preview window did show the slow down.  I'm just a user as well, not a programmer.

**Comment by reddn** [comment]
Seems it is a ffmpeg call that is not sending the speed parameter during
Export.  Wish I had more time to help.  I've got too much going on to learn
this project.

On Tue, Apr 18, 2017 at 9:52 AM, deadbeatguitarist <notifications@github.com

**Comment by franzum** [comment]
Hello did you get this solved? I am having the same issue.

**Comment by reddn** [comment]
Nope, just downloaded the most recent 2.3.4 today (June 16th 17) and it still doesn't work.

**Comment by MMG2002** [comment]
any way to fix this or wait for the guys to update the program for a fix?

**Comment by reddn** [comment]
You might as well learn python,ffmpeg, and fix it yourself. If I had time I
would do it myself.

**Comment by DylanC** [comment]
@reddn - Still an issue in the latest daily build?

**Comment by reddn** [comment]
Its working now

**Comment by DylanC** [comment]
@reddn - Thanks. That's great news! Closing this issue now.

**Comment by DylanC** [comment]
Dup of #587
