### ISSUE TITLE
Issues with Openshot on Ubuntu (exporting)

### ISSUE THREAD

**Issue by robcassell** [OpenShot/openshot-qt#589]
* **System Details:7.7.GB RAM / Intel® Core™ i5-5200U CPU @ 2.20GHz × 4 / Intel® HD Graphics 5500 (Broadwell GT2)  / 64 bit**
* Operating System / Distro: Ubuntu 16.04 ?
* OpenShot Version: 2.3.1
* LOG (exporting to youtube basic output): 
```
[mpeg2video @ 0x33bef40] Warning min_rate > 0 but min_rate != max_rate isn't recommended!
[mpeg2video @ 0x33bef40] impossible bitrate constraints, this will fail
[mpeg @ 0x3312280] Using AVStream.codec.time_base as a timebase hint to the muxer is deprecated. Set AVStream.time_base instead.
[mpeg @ 0x3312280] Using AVStream.codec.time_base as a timebase hint to the muxer is deprecated. Set AVStream.time_base instead.
      logger:ERROR /usr/lib/python3/dist-packages/openshot_qt/windows/main_window.py:2066: PyGIWarning: Unity was imported without specifying a version first. Use gi.require_version('Unity', '7.0') before import to ensure that the right version gets loaded.
      logger:ERROR   from gi.repository import Unity
[avi @ 0x5350680] non-interleaved AVI
[AudioData @ 0x7f9dcf7fd710] invalid NULL pointer for src[0]
[AudioData @ 0x7f9dcf7fd710] invalid NULL pointer for src[0]
etc.

(exporting to AVI MPEG4)

[mpeg4 @ 0x4024260] Warning min_rate > 0 but min_rate != max_rate isn't recommended!
[mpeg4 @ 0x4024260] impossible bitrate constraints, this will fail
[avi @ 0x40231e0] Using AVStream.codec.time_base as a timebase hint to the muxer is deprecated. Set AVStream.time_base instead.
[avi @ 0x40231e0] Using AVStream.codec.time_base as a timebase hint to the muxer is deprecated. Set AVStream.time_base instead.
      logger:ERROR /usr/lib/python3/dist-packages/openshot_qt/windows/main_window.py:2066: PyGIWarning: Unity was imported without specifying a version first. Use gi.require_version('Unity', '7.0') before import to ensure that the right version gets loaded.
      logger:ERROR   from gi.repository import Unity
[avi @ 0x6045480] non-interleaved AVI
[AudioData @ 0x7f63bd4a8710] invalid NULL pointer for src[0]
```

**Issue Description and steps to reproduce: I can't make head or tail of this, but then I'm an absolute beginner when it comes to Openshot. I'm hoping someone here might be able to help. Openshot seems to crash occasionally (although the autosave function seems pretty reliable and saves me extra work every time) and I run into the above problem when I try to export (to any output type). Can anyone help? Thanks!**

**Comment by ankitpati** [comment]
Please try the latest [AppImage](https://github.com/OpenShot/openshot-qt/releases/download/v2.3.1/OpenShot-v2.3.1-x86_64.AppImage "OpenShot 2.3.1"), and let us know if the issue persists.

**Comment by jonoomph** [comment]
Does this error prevent your from successfully exporting your video project?

**Comment by robcassell** [comment]
Hi Ankit, thanks, I will try that next time (see below).

Hi Jon, yes it stops it from exporting completely. I actually have since installed an earlier version of the software (1.4.3) which works absolutely fine and can export it next to no time. Not sure what the issue is with the later one.

**Comment by robcassell** [comment]
Hi spudic,

As I recall, I used the older version successfully in the end - 1.4.3

I hope this helps!

**Comment by DylanC** [comment]
@robcassell - If you try and confirm this in OpenShot v2.4 I will reopen. For now this looks to be resolved in an alternative manner.
