### ISSUE TITLE
Windows 10 Visual C++ Runtime Error - While previewing video

### ISSUE THREAD

**Issue by telelauro** [OpenShot/openshot-qt#59]
![laucher exe error 02](https://cloud.githubusercontent.com/assets/16803007/12509309/d723e0de-c101-11e5-9cd2-427e9fd9c329.png)

**Comment by jonoomph** [comment]
Can this be reproduced consistently? Is is a specific video file that causes this error? If so, can you please attach / or link to a small sample video that causes the issue. Thanks!

**Comment by telelauro** [comment]
yes, i am trying with another videos file, but the problem is still.The video file are, mpg4 1080p from the same photo machine. SONY DSC HX9V.

**Comment by telelauro** [comment]
how can you send you the video file? by dropbox ? or another?

**Comment by jonoomph** [comment]
Sure dropbox is fine, or you can email me a link (google drive / dropbox / etc...)

**Comment by nwgat** [comment]
pretty sure this is related to https://github.com/OpenShot/openshot-qt/issues/13

**Comment by telelauro** [comment]
https://drive.google.com/a/lauro20.org/file/d/0B_mY3sJEgEBLbUQ0eFlhbm1nOTA/view?usp=sharing

2016-01-22 23:48 GMT+01:00 Jonathan Thomas <notifications@github.com>:

> Sure dropbox is fine, or you can email me a link (google drive / dropbox /
> etc...)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenShot/openshot-qt/issues/59#issuecomment-174078614>
> .
>



-- 
"Dabilen kamerari Kroma-keyrik ez"

**Comment by telelauro** [comment]
How are you? I post it many issues, have you enought time?

2016-01-23 0:04 GMT+01:00 tele lauro <telelauro@lauro20.org>:

>
> https://drive.google.com/a/lauro20.org/file/d/0B_mY3sJEgEBLbUQ0eFlhbm1nOTA/view?usp=sharing
>
> 2016-01-22 23:48 GMT+01:00 Jonathan Thomas <notifications@github.com>:
>
>> Sure dropbox is fine, or you can email me a link (google drive / dropbox
>> / etc...)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/OpenShot/openshot-qt/issues/59#issuecomment-174078614>
>> .
>>
>
>
>
> --
> "Dabilen kamerari Kroma-keyrik ez"
>



-- 
"Dabilen kamerari Kroma-keyrik ez"

**Comment by jonoomph** [comment]
I am finally able to reliably reproduce this issue. I'm also looking for some better ways to troubleshoot these issues on Windows. On Mac and Linux, the GDB debugger works great for me, but on Windows, I'm not able to use GDB without it causing additional issues. 

Still working on this one. =)

**Comment by MightyMac** [comment]
Having the same issue on Windows 2.0.8. I can skip to a different point on the timeline and when I hit play it won't play. Then if I choose I point in time a few minutes into the clip and press play it crashes and I get a C++ error.

**Comment by jonoomph** [comment]
We have recently made a ton of improvements for video freezing and crashes, and I would like to verify this issue still occurs with our latest daily build. Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot. 

If the issue still occurs, please reopen this issue and attach log files (https://github.com/OpenShot/openshot-qt/blob/master/.github/CONTRIBUTING.md), and hopefully we'll be able to nail this down and fix it. Thanks!

**Comment by pexaorj** [comment]
The same bug here.
In the first version of openshot I did not have this issue.

**Comment by larsonreever** [comment]
I was also finally able to reliably reproduce this issue. I'm also looking for some better ways to troubleshoot these issues on Windows , i like some of those mentioned here http://driverrestore.com/how-to-fix-run-time-error-339-windows/
