### ISSUE TITLE
OpenShot 2.3.1 UI crash - split, delete, undo, drag, crash

### ISSUE THREAD

**Issue by nigels-com** [OpenShot/openshot-qt#590]
**System Details:**
* Operating System / Distro: Ubuntu 16.04 + Mac Sierra
* OpenShot Version: OpenShot-v2.3.1-x86_64.dmg

```
libopenshot logging: Mon Apr 17 11:49:54 2017
------------------------------------------
---- Unhandled Exception: Stack Trace ----
  4   libsystem_c.dylib                   0x00007fffa4d12420 abort + 129
  5   libstdc++.6.dylib                   0x00000001023f63db _ZN9__gnu_cxx27__verbose_terminate_handlerEv + 315
---- End of Stack Trace ----

```

**Issue Description and steps to reproduce:**

These steps reproduce the problem on both Ubuntu 16.04 and Mac.

1. Drag play head to somewhere in the clip.
2. Right-click -> Slice All -> Keep both sides.
3. Left click on left portion to select it.
4. Press delete.
5. Press Command-Z to undo
6. Drag the undeleted clip to the next track
7.  *** Hard Crash ***

<img width="818" alt="screen shot 2017-04-17 at 11 50 26 am" src="https://cloud.githubusercontent.com/assets/545677/25076547/1297b1ec-2365-11e7-92f0-2567cd57949c.png">

<img width="493" alt="screen shot 2017-04-17 at 11 50 50 am" src="https://cloud.githubusercontent.com/assets/545677/25076549/1a6c9d7e-2365-11e7-86f1-a6367383425d.png">

**Comment by nigels-com** [comment]
<img width="13" alt="screen shot 2017-04-17 at 12 01 35 pm" src="https://cloud.githubusercontent.com/assets/545677/25076606/ad7c5ec4-2365-11e7-9f70-bae5ffd9cfe6.png">

With thanks in advance!

**Comment by jonoomph** [comment]
Haha, nice way to bring attention to this bug! **Thanks for the donation!** Have you tested this with the latest daily build? I've fixed something very similar (if not this exact bug) a few days ago.

Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot.  Fingers crossed it will not break anymore.

**Comment by jonoomph** [comment]
Okay, I just reproduced the crash! Dang. Looking into it now.

**Comment by jonoomph** [comment]
In a few hours, a new daily build will appear on openshot.org/download. Please try your steps again, and it should no longer crash. If it does, please reopen this bug. Now if I could just get a donation for every bug fixed, that would be pretty awesome! =) Thanks again.
