### ISSUE TITLE
Properties does not change for all selected clips

### ISSUE THREAD

**Issue by jkateva** [OpenShot/openshot-qt#593]
**System Details:**
* Operating System / Distro: Kubuntu 16.04
* OpenShot Version: 2.3.1

I would like to select multiple clips, maybe even all, and then change one property for all selected items. Currently Openshot changes the property only for first clip. I have tried selecting multiple clips with CONTROL + click and CONTROL + a.

**Comment by TharenaMelishka** [comment]
Would like to necro this and bring it back to life.  I concur with this.  I brought in several images at what I thought would be the correct length, then figured out I would need a different length for display.  Now I'm stuck editing the image properties one by one, as well as all the repositioning.  At least mass altering the length of the images would save me some time.

Thanks!

**Comment by titsitits** [comment]
+1

**Comment by srikarg89** [comment]
I would also love to see feature this implemented.

**Comment by ron-g** [comment]
I too would like to see this implemented.

**Comment by nettum** [comment]
Also would like to see this.  
Currently testing openshot on a project that will have a lot of clips that would need some properties adjustments to get a satisfactory final result :scream:
