### ISSUE TITLE
Run time error editor launch.exe

### ISSUE THREAD

**Issue by deb1234567** [OpenShot/openshot-qt#596]
Fixed

**System Details:** windows 10
* Operating System / windows 
* OpenShot Version: 2.31
![image26](https://cloud.githubusercontent.com/assets/27789447/25206921/3c90f278-2528-11e7-9df8-0b91526d381d.jpg)

* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

**Comment by deb1234567** [comment]
was working and just stopped

**Comment by deb1234567** [comment]
it working again thanks all

**Comment by deb1234567** [comment]
NOT WORKING AGAIN

**Comment by DylanC** [comment]
Cannot reproduce in the latest version.
