### ISSUE TITLE
exported videos (Win7 x64)

### ISSUE THREAD

**Issue by retspag** [OpenShot/openshot-qt#597]
**System Details:**
* Operating System / Distro: **Win 7 64**
* OpenShot Version:  **2.3.1**
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

When I export a video, the resulting file has no audio.
I've tried various options to no avail. 

Thanks for any help.

**Comment by oxna** [comment]
I have the same problem. No audio when exporting a video.

**Comment by raycarpenter** [comment]
I had to change the audio codec to aac. Its under advanced> Audio settings.

**Comment by DylanC** [comment]
Solved in latest daily build.
