### ISSUE TITLE
when i put in a video/audio file the sound is very jagged up.

### ISSUE THREAD

**Issue by kotstulle** [OpenShot/openshot-qt#599]
* Operating System / Distro: windows 10 (64bit)
* OpenShot Version: 2.3.1

when i put in a video/audio file the sound is very jagged up.

**Comment by DylanC** [comment]
Closing this since you seem to have resolved the issue. Thanks.

**Comment by andrechisimo** [comment]
> * Sistema operativo / Distro: Windows 10 (64 bits)
> * Versión de OpenShot: 2.3.1
> 
> Cuando coloco un archivo de video / audio, el sonido es muy irregular.

a mi me ocurre igual con el audio cuando coloco imàgenes
