### ISSUE TITLE
ImportError: No module named 'openshot'

### ISSUE THREAD

**Issue by pixelr0** [OpenShot/openshot-qt#6]
i'm using this ppa https://code.launchpad.net/~openshot.code/openshot/openshot-qt

when launch-openshot i get his error 

    import openshot  # Python module for libopenshot (required video editing module installed separately)
    ImportError: No module named 'openshot'

**Comment by pixelr0** [comment]
Traceback (most recent call last):
  File "./launch.py", line 77, in <module>
    main()
  File "./launch.py", line 70, in main
    app = OpenShotApp(sys.argv)
  File "/home/rox/openshot2/2.0/src/classes/app.py", line 103, in __init__
    from windows.main_window import MainWindow
  File "/home/rox/openshot2/2.0/src/windows/main_window.py", line 36, in <module>
    import openshot  # Python module for libopenshot (required video editing module installed separately)
ImportError: No module named 'openshot'

**Comment by jonoomph** [comment]
This should have been resolved. Please try again and feel free to re-open this ticket if you have any issues. Thanks! Closing issue.
