### ISSUE TITLE
WINDOWS:  I suggest for modify the sound easier.

### ISSUE THREAD

**Issue by telelauro** [OpenShot/openshot-qt#60]
I'm trying to change the volume, and suggest an idea that I can find in other programs, could be as follows:
![sound openshot 2 0](https://cloud.githubusercontent.com/assets/16803007/12531871/13dff2a6-c206-11e5-800b-3ad88354f213.jpg)

**Comment by jreynojustin** [comment]
@telelauro,

Feel free to make a pull request adding such feature. I don't see us being able to address or integrate such a thing anytime soon. @jonoomph may overrule me if he sees it fit.
