### ISSUE TITLE
No audio sound in video export

### ISSUE THREAD

**Issue by oxna** [OpenShot/openshot-qt#600]
I am using windows 7, open shot version 2.3.1
When I export the video the sound is lost.
Thanks for your help.

**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

**Comment by oxna** [comment]
I have managed to fix the problem, by changing the audio settings to aac for the export. No further action required!

**Comment by DylanC** [comment]
No problem. Thanks.
