### ISSUE TITLE
Where is rotation center?

### ISSUE THREAD

**Issue by j2l** [OpenShot/openshot-qt#603]
Hi,
First, thanks, this is a great project.
I have trouble understanding where is rotation center, it's only in upper left position that rotation is right (center of object, a PNG picture in my case), but when you move the object anywhere else on the screen, rotation center is moved somewhere else.
Please see https://youtu.be/tuKXZeauWgk to see this behavior.
Additionally, I can't change language, whatever I select it sticks to system default (french in my case), I prefer to use english. When looking for issues it's easier to find pages (and I don't always know what was the actual original term).
Thanks
OpenShot 2.3.1, Windows 10

**Comment by DylanC** [comment]
@j2l - Hopefully I can get an answer for you.

**Comment by DylanC** [comment]
@j2l - You might find it helpful to look here: #694

The answer is already in that ticket.
