### ISSUE TITLE
Feature request: prefetch tool

### ISSUE THREAD

**Issue by Enfostorm** [OpenShot/openshot-qt#604]
No bug report, but a feature request.
I would think it to be very handy if some kind of a prefetch tool would be available. When you play the preview, the small blue bar above the timeline shows you how much of the video has already been cached. Because the live preview is often slower than actual speed (for me at least) I often let the video play, do something else for a minute, come back and replay the video.

Performancewise I've got an Intel i5 3320, 8GB of ram and graphics card integrated in the cpu (though I don't think openshot uses the gpu(?) )

**Comment by N3WWN** [comment]
I also experience this.  Is there any benefit to precaching each track individually instead of the combined output?  Most of my work is aligning multiple tracks, but when I change the position of one track, the cache appears to be cleared for all tracks (the combined track).
