### ISSUE TITLE
soft audio

### ISSUE THREAD

**Issue by continuoman** [OpenShot/openshot-qt#605]
**System Details:** Dell PC Core i3, 1 T drive
* Operating System / Distro: ? Windows 10 x64
* OpenShot Version: ? Latest, I presume
* _Please attach log files if crash_ No crash

**Issue Description and steps to reproduce:**
Simple: I need to increase volume of video's audio track. How do I do this in OpenShot?

**Comment by DylanC** [comment]
@continuoman - I will check this out and get back to you.

**Comment by DylanC** [comment]
@continuoman - Did you try the right click menu on the clip?
