### ISSUE TITLE
importing wmv to openshot

### ISSUE THREAD

**Issue by CodeName-noIdea** [OpenShot/openshot-qt#606]
**System Details:**
* Operating System / Distro: lubuntu 16.04
* OpenShot Version: 1.4.3 & 2.3.1

I have been using OpenShot 1.4.3 for 2 years to import wmv files in the creation of many different types of mp4 files (mov, mp4, .264, etc). It has always worked until this week. The files show up in Openshot, but will not play back. When I put them in the timeline, they play as a still image for a few seconds before going to black. I have tried wmv files that I have already translated from wmv to mp4, but have the same trouble.  I installed 2.3.1 to try to import the wmv files and have the same problem.  What has changed?

**Comment by ankitpati** [comment]
No repro on Ubuntu 16.04, with both versions: 1.4.3 from the repo, and 2.3.1 AppImage.

700+ MiB `wmv` file loads and plays absolutely fine for me.

Please try the latest stable [AppImage](https://github.com/OpenShot/openshot-qt/releases/download/v2.3.1/OpenShot-v2.3.1-x86_64.AppImage "OpenShot 2.3.1"), and let us know if the issue persists.

**Comment by CodeName-noIdea** [comment]
Thank you!

**Comment by ankitpati** [comment]
Please let us know if it worked.

**Comment by CodeName-noIdea** [comment]
Yes, it worked. Everything is running well again. Thank you.
