### ISSUE TITLE
OpenShot 2.3.1 crashes while starting on Windows 10 x64

### ISSUE THREAD

**Issue by scadl** [OpenShot/openshot-qt#607]
**System Details:**
* Windows 10 x64 v1703 (build 15063.138)
* OpenShot Version: 2.3.1
* ![os_qt](https://cloud.githubusercontent.com/assets/11553857/25531013/f97a756c-2c30-11e7-898b-8a89fe07f073.PNG)

At least month or two ago, the app stopped to lunch, with this error message.
1) Tried to fully uninstall and reinstall it. With removing data from .openshot_qt folder.
2) Tried portable version. Tried older versions.
Always same error.

Any suggestions where to look?

**Comment by Midget-1980** [comment]
From Holland, 

Same issue here, i've run Pyton to see what is wrong and i receve the folowing imput.

`========= RESTART: D:\Program Files\OpenShot Video Editor\launch.py =========
Loaded modules from current directory: D:\Program Files\OpenShot Video Editor
Traceback (most recent call last):
  File "D:\Program Files\OpenShot Video Editor\launch.py", line 54, in <module>
    from classes.app import OpenShotApp
  File "D:\Program Files\OpenShot Video Editor\classes\app.py", line 37, in <module>
    from PyQt5.QtGui import QPalette, QColor, QFontDatabase, QFont
ModuleNotFoundError: No module named 'PyQt5'
>>> `

I've tried installing PyQt5 again with succes, but the program still will not start. It opens a window with a intent to show a prieview video, and then freez.

info:
Windows 10 x64 v1607 (build 14393.1066)
OpenShot Video Editor 2.0

**Comment by Midget-1980** [comment]
After A day of looking around to fix this, I found that not a compatibility mode or Administrator rights would help.   But, giving all rights to All Users in the security tab of the files [launch.exe, and launch.py] fixed my problems. 

Hope someone it will be of use to someone else.

Sincerly yours, 
Midget1980

**Comment by scadl** [comment]
>  But, giving all rights to All Users in the security tab of the files [launch.exe, and launch.py] fixed my problems.

Didn't helped here...
Any other suggestions?
![default](https://cloud.githubusercontent.com/assets/11553857/25966253/2ae76972-3693-11e7-94f7-169d25bbd9be.png)

**Comment by DylanC** [comment]
Cannot reproduce this on the latest version.

**Comment by Akkim** [comment]
There is an extension in that folder which is coming up as a Trojan in Malwarebytes.

pyqt5.qtgui.pyd

This should probably be properly addressed to prevent this happening and to alleviate concerns with the application.  Sometimes "Free" can carry unknown risks :(
