### ISSUE TITLE
how to add audio to an existing audio track in the video that they worked synchronously?

### ISSUE THREAD

**Issue by KovalskyRUS** [OpenShot/openshot-qt#608]
**System Details:**
* Operating System / Distro: Ubuntu MATE
* OpenShot Version: 2.3.1
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
how to add audio to an existing audio track in the video that they worked synchronously?

**Comment by DylanC** [comment]
Add the audio clip to a separate track and line it up as needed to the other track.
