### ISSUE TITLE
X and Y crop (property) squeezes video

### ISSUE THREAD

**Issue by franktoffel** [OpenShot/openshot-qt#609]
**System Details:**
* Operating System / Distro: Windows 7 x64
* OpenShot Version: current

When opening the properties of a video in the timeline, I found X and Y crop fields. Instead of cropping the video, these values squeeze it like if I was applying a shear force.

What I am trying is to move the video to one corner, **crop it** and add some zoom. I don't need dynamic transformations, just stills. Is this functionality available?

Thanks

**Comment by pinkartichoke** [comment]
I'm also having this problem. Help anyone?

**Comment by DylanC** [comment]
@franktoffel @pinkartichoke - That type of Crop is not currently available but may be added in the future.
