### ISSUE TITLE
Time>Fast>Forward>(any speed) Not Rendering

### ISSUE THREAD

**Issue by YouShouldBeCoding** [OpenShot/openshot-qt#610]
**System Details:**
* Operating System / Distro: Windows 10 x64
* OpenShot Version: 2.3.1
* _Please attach log files if crash_

I can apply a fast forward by any speed to any video file I bring in and it previews at high speed.  Rendered file is a few second clip of original file at normal speed.  Tried with AVI, MOV, and MP4 files with same results.

**Comment by MSXisAlive** [comment]
Also happen with "Time > Slow > Forward"
Tested with:
* Windows 8 x64
* OpenShot Version: 2.3.2

**Comment by reddn** [comment]
Dup of #588. still not fixed in 2.3.4 as of june 16th

**Comment by DylanC** [comment]
Confirmed as fixed in #588
