### ISSUE TITLE
Core Dump by selecting a clip in the timeline and pressing CTRL+C and then CTRL+V

### ISSUE THREAD

**Issue by soerendip** [OpenShot/openshot-qt#611]
**System Details: Linux 4.10.10-100.fc24.x86_64 GNU/Linux
* Operating System / Distro: Fedora 24
* OpenShot Version: 2.1.0
* Where are the log files, can't this be automated?

**Issue Description and steps to reproduce:**
Select a clip in the timeline and pressing CTRL+C and then CTRL+V to copy and paste a clip in the timeline crashes OpenShot.

```
properties_model:INFO updating clip properties model.
      logger:INFO 16777249
      logger:INFO 67
 main_window:INFO keyPressEvent: Ctrl+C
timeline_webview:INFO -1
      logger:INFO 86
 main_window:INFO keyPressEvent: Ctrl+V
timeline_webview:INFO 9
terminate called after throwing an instance of 'openshot::InvalidFile'
  what():  File could not be opened.
Aborted (core dumped)
```

**Comment by DylanC** [comment]
@soerendip - Thanks for the feedback. I will try to reproduce.

**Comment by DylanC** [comment]
@soerendip - This is working on v2.4.1.
