### ISSUE TITLE
Bug avec utilisation openshot

### ISSUE THREAD

**Issue by sylvainmunger** [OpenShot/openshot-qt#613]
Bonjour à tous,

  J'ai une problématique avec l'utilisation d'openshot.  Celui-ci plante constamment lorsque je veux exécuter un projet ou bien l'exporter ou encore le suivre à la trace via la timeline.

Je travaille sur un Win7 pro 64 bits, I5 comme processeur et 2 Go RAM.

Mon projet de départ était de faire du 1920 x 1080 en film.  J'ai deux angle de vidéo que je veux "merger".  Les vidéos sont trop gros pour être manipulable avec l'environnement que j'ai.  Alors j'ai fait un vidéo de travail avec le format 16:9.  Donc j'ai converti mes vidéos en  720x480.  Et cela a très bien marché jusqu'à ce que je copie les versions originales à la place des 720x480.  Quand je viens pour les exporter en bluray, openshot plante constamment.  J'ai même essayé de raffraichir les propriétés des vidéos.  Eux ils indiquent toujours les formats d'origine.

Merci de revenir sur une façon de régler le problème.

**Comment by DylanC** [comment]
@sylvainmunger - What version of OpenShot was this?

**Comment by DylanC** [comment]
Closing due to lack of detail to confirm issue.
