### ISSUE TITLE
I removed some toolbars and can't get them back

### ISSUE THREAD

**Issue by KobusSWTF** [OpenShot/openshot-qt#615]
So.. I pressed on one of those toolbar buttons where you see an icon of fullscreen and delete and i accidentaly pressed delete. now i can't get it back. is there any way to restore the toolbars like the playbutton or library?

**Comment by ankitpati** [comment]
From the menu bar, `View` → `Views` → `Show All` will show all views. Then, remove the unnecessary ones using the same delete button that caused this problem.

Please let us know if this solved the issue.

**Comment by KobusSWTF** [comment]
excuse me for my very late reaction. it worked. Thank you
