### ISSUE TITLE
Further zooming necessary

### ISSUE THREAD

**Issue by Turisames** [OpenShot/openshot-qt#616]
Hi, 
I'm trying to cut out a specific, small piece from a clip. I want to leave out the word 'but' from the beginning of my clip. Problem is that I can't zoom close enough into the timeline to see where that word ends and the rest of the words begin.

Win 10
Openshot 2.3

**Comment by N3WWN** [comment]
+1  

I make videos with picture-in-picture so I have to align the videos perfectly so that they are not out of sync.  Additional zoom will help that.

**Comment by DylanC** [comment]
Zoom Level bug has already been reported in #160. We will be tracking it from there and I will be closing any duplicates. Thanks.
