### ISSUE TITLE
My OpenShot close 

### ISSUE THREAD

**Issue by acrosoma** [OpenShot/openshot-qt#617]
**System Details:**
*** Operating System / Distro: ?**
Versión Linux Mint 18.1 Serena de 64-bit
Núcleo Linux 4.4.0-77-generic x86_64

* OpenShot Version: ?
2.3.1

* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
Suddenly closes

**Comment by ankitpati** [comment]
Please try the latest stable [AppImage](https://github.com/OpenShot/openshot-qt/releases/download/v2.3.1/OpenShot-v2.3.1-x86_64.AppImage "OpenShot 2.3.1"), and let us know if the issue persists.

**Comment by DylanC** [comment]
Closing due to a lack of details in the report. Please try the latest v2.4 release.
