### ISSUE TITLE
can't get new effects

### ISSUE THREAD

**Issue by dexterdy** [OpenShot/openshot-qt#619]
**System Details:**
* Operating System / Distro: windows 10
* OpenShot Version: 2.3.1

I downloaded openshot for easy and free video editing. I also wanted to give my video's some effects but there are only a few. I tried searching on internet for a guide for installing new ones and also searched for plugins but i found nothing usefull. can someone help me get more effects?

**Comment by Abdulla2** [comment]
https://github.com/OpenShot/openshot-qt/issues/498

**Comment by DylanC** [comment]
@dexterdy - Effects must be re-created for the new v2 series of OpenShot. In future versions we will have more effects. Thanks.
