### ISSUE TITLE
Videoformat .M2T 16:9 uncorrectly shown. Looks like 4:3 

### ISSUE THREAD

**Issue by PeterdeBruin** [OpenShot/openshot-qt#620]
**System Details:** 
* Operating System / Distro: ? Both in windows7 x64 as in Linux Mint 18.1 
* OpenShot Version: ? 2.3.1
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
.m2t format comes from Sony Camcorder HDR-HC7E
![openshot problem 16-9 m2t format](https://cloud.githubusercontent.com/assets/28451263/25755799/aaa81464-31c4-11e7-8d58-68be656d0408.jpg)

Openshot does not show 16:9 but 4:3 
NOTE: Same with .ts and .mpg formats.

**Comment by PeterdeBruin** [comment]
Same with .ts and .mpg formats

**Comment by DylanC** [comment]
@PeterdeBruin - Do you have a sample video to help me test this?

**Comment by DylanC** [comment]
@PeterdeBruin - For .ts you should be converting or repairing with other software before using with OpenShot.
