### ISSUE TITLE
OpenShot ssl.py ImportError on Windows

### ISSUE THREAD

**Issue by vac** [OpenShot/openshot-qt#621]
**System Details:**
* Operating System / Distro: Windows 10 x64
* OpenShot Version: v2.3.1

when running OpenShot  I get this error (same as in: #295 ):
![2017-05-06 14_29_24-cx_freeze_ python error in main script](https://cloud.githubusercontent.com/assets/200544/25772315/75f1cc66-3268-11e7-9ea1-ed89a266e546.png)

**Comment by rrzaripov** [comment]
Same issue, Windows 7

**Comment by jonoomph** [comment]
A fix is now available. Please see https://github.com/OpenShot/openshot-qt/issues/295. Thanks!
