### ISSUE TITLE
Audio stutters and stops at  minute 2:33

### ISSUE THREAD

**Issue by yodadinmd** [OpenShot/openshot-qt#623]
OpenShot Version: 2.3.1

Hi, recently i downloaded Openshot for making Twitch Highlights, and i cant go further because of a bug that stops the audio of the music at the minute 2:33
https://www.youtube.com/watch?v=rYH0xjDqlmQ&feature=youtu.be

**Comment by yodadinmd** [comment]
the sound stops after 2:30 mins from the song passed

**Comment by PIH2206** [comment]
Hi! I have the same issue - did you already find a solution?

**Comment by yodadinmd** [comment]
No...

**Comment by DylanC** [comment]
Dup of #618

**Comment by DylanC** [comment]
This is resolved in the latest daily build:
![solved](https://user-images.githubusercontent.com/4488048/31321108-155f4970-ac78-11e7-8783-0439def02c0e.png)
