### ISSUE TITLE
Where is the "Advanced" speed menu in version 2.3.1?

### ISSUE THREAD

**Issue by ubuntuslave** [OpenShot/openshot-qt#624]
**System Details:**
* Operating System / Distro: Ubuntu 16.04
* OpenShot Version: 2.3.1
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

I'm wondering why in this version  I can only choose the speeds up from a well defined set of values. I can't enter my own speed. I see previous versions allowed the use to the speed to any value through the **Advanced** options, which doesn't seem to exist anymore.

Please, help.

**Comment by reddn** [comment]
This is not a bug, but a question and/or a feature request. update to the latest version and use the forums for feature request or questions.

**Comment by DylanC** [comment]
@ubuntuslave - Select clip. Next use the dock on the left side of the screen to modify all clip values. Thanks.
