### ISSUE TITLE
I find Openshot pretty unusable - crashes every minute 

### ISSUE THREAD

**Issue by mateusz-lacki** [OpenShot/openshot-qt#625]
**System Details:**
* Operating System / Distro: OSX 10.12.4
* OpenShot Version: 2.3.1
* _Please attach log files if crash_

[logs.zip](https://github.com/OpenShot/openshot-qt/files/982569/logs.zip)

**Issue Description and steps to reproduce:**
The issue is that basically everything randomly fails.
Resizing the video in the track editor may cause the spinning ball
setting "time" from 0.0 to 4 in prefereces may cause a crash like in the attached log file

**Comment by DylanC** [comment]
@mateusz-lacki - Thanks for the report. I will look at this soon.

**Comment by DylanC** [comment]
Closing due to lack of detail to test this. Telling us things randomly fail isn't quite enough detail. If you have a more detailed report feel free to put in a new issue. Test on v2.4 of OpenShot too.
