### ISSUE TITLE
Audio problem after encoding

### ISSUE THREAD

**Issue by bambinos83** [OpenShot/openshot-qt#626]
* Operating System / Distro: Windows 7
* OpenShot Version: 2.3.1

I created a video made from pictures and clips. I also added a few sound clips to make a soundtrack. When I encoded the video, I noticed that the first sound clip stopped about 10 seconds before the time it was suppose to and I noticed that the transitions (fade in and fade out) were not the same as on the timeline in OpenShot. Any reason for that?

**Comment by DylanC** [comment]
@bambinos83 - Sounds like a technical problem. Maybe keep an eye on some of the tickets that mention your issue. Thanks.
