### ISSUE TITLE
More effects

### ISSUE THREAD

**Issue by KuumuuK** [OpenShot/openshot-qt#627]
**System Details:**
* Operating System / Distro: Win 10
* OpenShot Version: 2.3.1
**Issue Description and steps to reproduce:**

Hi 
I just started working with OpenShot and think its great. But I also just have 7 effects to work with. How do I get more? Is there an easy way?

Thanks a lot

Kolja
![screenshot](https://cloud.githubusercontent.com/assets/28563554/25849422/ba907acc-34be-11e7-80c1-1730390816f4.png)

**Comment by DylanC** [comment]
@KuumuuK - Not at the moment you will have to wait until more are added.
