### ISSUE TITLE
Openshot fails to open a project with russian letters in its name

### ISSUE THREAD

**Issue by sknaumov** [OpenShot/openshot-qt#628]
**System Details:**
* Operating System / Distro: Windows 10
* OpenShot Version: 2.3.1

**Issue Description and steps to reproduce:**
Openshot fails to open project created with it if file name contains russian letters. The window caption still shows "Unnamed project". After rename to ASCII project file could be opened just fine.

**Comment by sknaumov** [comment]
It looks like it is a duplicate of #586.

**Comment by DylanC** [comment]
Dup of #677

**Comment by DylanC** [comment]
@sknaumov - Should be fixed in latest daily build.
