### ISSUE TITLE
Split clip won't preview past 00:30:00

### ISSUE THREAD

**Issue by tallforasmurf** [OpenShot/openshot-qt#629]
* Mac OS 10.10.5 "Yosemite"
* 27-in retina iMac
* OpenShot Version: 2.3.1

Put a .mp4 captured from videotape in the media window. It is 4:3, 640x480 and 57:00 long.

Right-click on file, select Split Clip. Successfully split out two clips representing the first 13 min and 10 min. Set Start at 23:xx point and begin sliding scrubber to the right.

When the scrubber passes the 00:30:00:00 point, the preview image stops updating. The time readout continues to update to reflect the scrubber position, but the image is frozen at the 30min frame.

I set the End point "in the blind" around 40 min and split, and the resulting clip did include the video it should. Of course it isn't much use setting a start or end when you can't see the image.

Is this a known problem? I searched issues on "Split" and don't see anything like it.

**Comment by klingchristoph** [comment]
Same problem here with OpenShot 2.3.4 on Windows 8.1 x64. Any solution out there?

**Comment by DylanC** [comment]
@tallforasmurf @klingchristoph - Does this happen on v2.4.1?

**Comment by tallforasmurf** [comment]
indeed it does. Drag a 53-minute 640x480 mp4 to Project files. Right click on that file, select Split Clip. The Split Clip modal dialog opens. I don't have to split anything, I just start dragging its little scrubber button left to right, and the image above it flickers along showing frames, until the time readout hits 00:30:00 then the image stops updating -- although if I continue to drag the scrubber right, the time display updates properly.

I made you a little movie to demo it: https://cortesi.smugmug.com/Other/Misc/i-Dhtfd5V/A
This shows the file properties, then operates the scrubber.
Download this (button in bottom right) as I will delete it soon.

**Comment by DylanC** [comment]
@tallforasmurf - Thanks. I will have a look soon.

**Comment by dakujem** [comment]
I have just tried to create a clip consisting of multitude of sports camera diving clips that I cut into smaller pieces (removed unnecessary portions) and my preview stops at 00:03:59:29 (4 minutes) for some reason. Basically, I can't create a video any longer than that.

Windows 7 x64
OpenShot `2.4.1`

**Comment by PeetCleanfield** [comment]
I had the same problem.Changing ythe cache size (via the preferenc es) solved this problem.

**Comment by dakujem** [comment]
Well if this is a cache problem, maybe there should at least be a message telling the user that his cache size must be increased.

**Comment by KorgBoy** [comment]
Is there a fix for this yet? I confirm the same issue. I increased cache size via the 'Edit -> Preferences'. That didn't help. So it's interesting how it resolved the issue for some people here.

**Comment by pimzwager** [comment]
I am having this exact same issue, tried increasing the cache, but it keeps freezing on almost 30 minutes

**Comment by theodim123** [comment]
v. 2.4.4 problem still unsolved. I increased cache size and nothing. Preview freezes after 30 mins.

**Comment by SuslikV** [comment]
@theodim123 the _Project Files_ dialog? (https://github.com/OpenShot/openshot-qt/issues/2737)

**Comment by theodim123** [comment]
It's the split clip function at the project files.

**Comment by Marizza69** [comment]
I can confirm this bug. Steps to reproduce:
Start OpenShot.
Select "Import Files..." and import a video clip longer than 30 minutes
Right click on the project file,select "Split Clip..."
Move the slider to the right. Preview will not get updated once you reach 29m59s.

When activating Debug Mode (Verbose) I can see that OpenShot keeps fetching audio and video frames, even though the preview is not updated.

Environment: Ubuntu 18.04, 64 bit.
OpenShot 2.4.4 as AppImage
