### ISSUE TITLE
Split clip on timeline shows source file name?

### ISSUE THREAD

**Issue by tallforasmurf** [OpenShot/openshot-qt#630]
* 27-in retina iMac
* OSX 10.10.5 Yosemite
* OpenShot Version: 2.3.1

Made some clips with the Split Clip dialog, giving each one a name, for example "First Quarter" and "Halftime" (it's a basketball video).

When I drag a split clip to the timeline, it shows only the name of the original file, e.g. gamevideo.mp4 -- not the name of the clip. So now I have three clips on the timeline all with the same name, the filename.mp4. The filename (without the .mp4) shows in the "Selection" popup above the Properties. The clip name doesn't seem to show anywhere except the media window.

I guess this is an enhancement request? Show the clip name on the timeline?

**Comment by peanutbutterandcrackers** [comment]
Yes, I think this is an enhancement that would definitely make the user experience so much better!

**Comment by tallforasmurf** [comment]
I have not used open-shot since shortly after I filed this enhancement request. I believe it would be sensible and useful for the product as it was in 2017 but have no idea if it is relevant to the 2020 version, and no interest in following up.

Close it.
