### ISSUE TITLE
Can't find "hue" or other video effects

### ISSUE THREAD

**Issue by tallforasmurf** [OpenShot/openshot-qt#631]
* OpenShot Version: 2.3.1

Per the website, effects include "brightness, gamma, hue, greyscale, chroma key, and much more". In the Effects tab I see Blur, Brightness/Contrast, Chroma Key, Deinterlace, Alpha Mask, Negative, and Color Saturation. (No grayscale, is the saturation supposed to effect that?)

I am particularly anxious to try the Hue effect as I have a video with a bad white balance that needs to be pulled away from red. But I don't see it (or the "much more"). Is there somewhere to download more effects?

**Comment by DylanC** [comment]
@tallforasmurf - You will just need to wait until more effects are added. They have to be re-created for the v2 series of OpenShot.

**Comment by MarcelWaldvogel** [comment]
As it has been over 3 years where "gamma" and other effects have been announced to exist, but do not really exist, could you at least adapt the documentation?

**Comment by clort81** [comment]
I'll have to do gamma with ffmpeg for now.
