### ISSUE TITLE
How to add Subtitles?

### ISSUE THREAD

**Issue by defmanbogeyman** [OpenShot/openshot-qt#632]
**System Details:** 
* Operating System / Distro: Windows 10
* OpenShot Version: 3.2.1.
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

I am profoundly deaf. I don't speak very well. I wish to add text, words, much like subtitles, like in movies, "English Subtitles for the Hearing Impaired", so people can understand exactly what I say. I want to know where it this on the OpenShot software. I had used Movie Maker before, but Windows 10 don't have it, so I'm looking for an alternative, and OpenShot seems to be the best alternative. How do I add texts to my videos, like I'm speaking, so I'd be understood by my viewers?

Thanks in advance.

**Comment by DylanC** [comment]
Dup of #378

**Comment by DylanC** [comment]
@defmanbogeyman - It is not currently possible at the moment with subtitle formats unless you just want to use .svg files with text for now. However, I have confirmed that the subtitle formats may become available to use in a future version.

**Comment by audiodef** [comment]
Kdenlive does subtitles, but it's a Linux program. 

In OpenShot, you can add titles. It's not the same. I'm deaf, too, and I'm currently using titles to create accessible humorous videos.

**Comment by rivertam** [comment]
I recognize it's a lot of work, but I think this is a really important story both for the handicapped and not. I would like to not only be able to import subtitles but also be able to create in line with the video similar to how YouTube's editor has it.

Thank you for the software!

**Comment by peanutbutterandcrackers** [comment]
@audiodef @rivertam -Hey there, sorry for the extremely delayed reply. Currently, the  only way to fake subtitles is to add a lot of 'titles' and use them as subtitles. Another way would be to just use [kdenlive](https://kdenlive.org) for the time being (it is also available for windows - beta, I think). Another way would be to use a dedicated subtitle editor like this one: http://www.aegisub.org/ It is Free and Open Source, too. Hope that helps.

In the meantime, in the future, there might be some steps into implementing this. But as things stand right now, there are a lot of issues that need to be dealt with.

**Comment by rivertam** [comment]
@peanutbutterandcrackers Thanks for the links! I don't think I'd considered the idea of a separate program, for some reason. Aegisub looks really good for this.

**Comment by peanutbutterandcrackers** [comment]
@rivertam - I'm glad that it seems useful to you. All the very best!

**Comment by chenlung** [comment]
I use [Subtitle Horse](https://subtitle-horse.com) to produce subtitle scripts.

There are many formats, but import and export support of the following would be ideal (some are frame-based, millisecond, or both):
- SRT
- WebVTT
- STL (Spruce Technologies)
- iTT
- SMPTE-TT

If a developer wants to reply, I'm happy to privately provide short samples of all these (including a video) for testing.

**Comment by peanutbutterandcrackers** [comment]
@chenlung - Perhaps you should [prefer external subtitles over embedded subtitles](https://www.stmedia.co.uk/blog/embedded-subtitles-vs-subtitles-srt-files/)? Openshot does not have the capability to create or embed subtitles. You could use the aforementioned dark-horse or perhaps even something like [aegisub](www.aegisub.org) or [gaupol](https://otsaloma.io/gaupol/) (GNU/Linux only) to create subtitles, and then use something like [VLC](https://www.videolan.org/vlc/) to [embed the subtitle `.srt` file into the video](https://www.dedoimedo.com/computers/vlc-subtitles.html).

Hope that helps.

**Comment by chenlung** [comment]
> @chenlung - Perhaps you should [prefer external subtitles over embedded subtitles](https://www.stmedia.co.uk/blog/embedded-subtitles-vs-subtitles-srt-files/)? Openshot does not have the capability to create or embed subtitles. You could use the aforementioned dark-horse or perhaps even something like [aegisub](www.aegisub.org) or [gaupol](https://otsaloma.io/gaupol/) (GNU/Linux only) to create subtitles, and then use something like [VLC](https://www.videolan.org/vlc/) to [embed the subtitle `.srt` file into the video](https://www.dedoimedo.com/computers/vlc-subtitles.html).
> 
> 
> 
> Hope that helps.

Hello,

- I’m interested in softcoded and hardcoded subtitles.
- I dislike Aegisub for a few reasons, and it's not had a new version since 2014. Gaupol is indeed only available for one operating system.
- Shotcut could serve as a frame-accurate subtitle editor itself, similar to the functionality of Final Cut Pro and Premiere Pro, and offer features such as validation.
- VLC may only support SRT (which you allude to) which isn’t ideal because I need support for alignment (available in WebVTT). I would opt for another program such as Shutter Encoder anyway (partly because I don't know if ProRes and others are supported; would be great for Mac OS if they could use the official Apple encoder somehow).

**Comment by JacksonRG** [comment]
@defmanbogeyman I know this is an old issue. But as of 2.6.0 we added a caption effect, which you can drop onto clips
