### ISSUE TITLE
High FPS exported video is black if video includes fading

### ISSUE THREAD

**Issue by piobaire24** [OpenShot/openshot-qt#633]
**System Details:**
* Operating System / Distro: Ubuntu 16.04 64bit
* OpenShot Version: 2.3.1 (installed via PPA)
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
When exporting at 50 fps or higher at any resolution using h.264 or mpeg4 (any container) and at any quality, the video file is always black if the edited video contains fading at the start and/or end.

The exported video only displays properly at 30 fps or less.

The bad 'black' exported video file is quite small (e.g. 283.3 kb) as opposed to a 'working' export at 30 fps (e.g. 17.0 MB).

No errors are shown during the export.

The original (imported) video file is 1080p60 h.264.

I have tried playing the exported video back using the Ubuntu 'Videos' app, VLC 2.2.2, Handbrake 1.0.4 and Xine 0.99.9-1.2. All show the same result.

NOTE: This process works as it should in Openshot ver. 1.4.3, but not in the newer version 2.3.1.

Attached is an example of the bad 'black' video exported at 60 fps with faded start & end.
[Test - faded.mp4.zip](https://github.com/OpenShot/openshot-qt/files/991566/Test.-.faded.mp4.zip)

**Comment by DylanC** [comment]
@piobaire24 - I would recommend to try the daily build.
