### ISSUE TITLE
New installation. Error when i run program. Can't access program.

### ISSUE THREAD

**Issue by ghost** [OpenShot/openshot-qt#634]
I installed openshot. When i go to launch it, i get an python error script (see screenshot in link below). I can not access the program with this in the way.
![dsc_0001](https://cloud.githubusercontent.com/assets/27034110/25962670/7b35f8fe-3633-11e7-833a-a851b6d79dc5.JPG)

**Comment by eyetrap** [comment]
I have the same issue, Windows 7 64bit. 
Downloaded and installed on 5/10/2017

**Comment by CaitlinChoban** [comment]
Mine is windows 8 64 bit.

**Comment by jrpaphos** [comment]
Same here, installed the latest version and got the same error message as shown above. Had to uninstall.

Any suggestions? I did want to give the application a try.

**Comment by jrpaphos** [comment]
![avast notice](https://cloud.githubusercontent.com/assets/28751815/26145873/d5838246-3af6-11e7-8bc8-7b891cfedcbb.png)

Tried to install the latest May 16 build and received this notice???

**Comment by DylanC** [comment]
Cannot reproduce this issue on latest builds.
