### ISSUE TITLE
Openshot stops responding when using bigger mp4 files

### ISSUE THREAD

**Issue by TWuerdemann** [OpenShot/openshot-qt#635]
**System Details:**
* Operating System / Distro: Windows 10 Pro and Home, 64 Bit
* OpenShot Version: 2.3.1 / 2.3.2 / 2.3.3
* i5 6600, 16GB DDR4, SSD drives
Two different systems, same issue.

Using an MP4 (1080p, 60FPS, 20 Minutes, 6.5GB size).

Steps to reproduce:
- Create a new project.
- Add file by drag and drop.
- Try to split video.
- Openshot stops responding (note in window title).
- Only solution is to kill task.

**Comment by Loosethinker** [comment]
I am seeing the same thing. I have several 10+ minute 720p mp4 videos from recording my phone screen and when I hit the preview button or do just about anything after using one of the videos it says "not responding" until I kill it.

System:
AMD FX-8320 Eight-Core Processor 3.51 GHz
16GB memory
64-bit Windows 10 Home

**Comment by TombyT** [comment]
I have similar specs and used multiple OS (windows 10 and Linux 15.10, 16.04,16.10 17.04) and I think that 60 fps does seem to be part of a major issue. I was also having issues with exporting along with stability and preview but in one of the more recent app-images i was actually able to export a file entirely (though one of the audio clips simply didn't export and one other was extremely "poppy").

I use 60fps GO-Pro footage and have been having lots of issues.

**Comment by DylanC** [comment]
Solved by changing the current profile to 60fps - #854

**Comment by miriamohrn** [comment]
Hi! Please, this keeps happening even though I changed it to 60fps. Help anyone?
