### ISSUE TITLE
not valid video, audio or image file

### ISSUE THREAD

**Issue by WPaw** [OpenShot/openshot-qt#636]
**System Details:**Linux Leep
* Operating System / Distro: ?
* OpenShot Version: ? 2.3.1
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

When I import file, I have info "xxx.mp4 is not valid video, audio or image file"

**Comment by DylanC** [comment]
@WPaw - Do you have a sample file for me to test?

**Comment by DylanC** [comment]
This sounds like a corrupted video file to me. I can't reproduce this.

**Comment by D-signr** [comment]
I got this same issue after deciding to download and install OpenShot 2.4.0 image from your website. Before that, I was using OpenShot 2.2 with the same files and without problems. My video file format is mp4. Doesn't sound like corrupted files to me.
