### ISSUE TITLE
WINDOWS: does not the "split clip"

### ISSUE THREAD

**Issue by telelauro** [OpenShot/openshot-qt#64]
I'm trying to use the "sclip clip" with
![no funciona el split clip](https://cloud.githubusercontent.com/assets/16803007/12532356/8b49f70e-c212-11e5-8c96-8ce35e52dc24.jpg)
 the right mouse button but nothing appears.

**Comment by jarlarntzen** [comment]
**Related**: #55 on Ubuntu 14.04 LTS

**Comment by telelauro** [comment]
thanks that its the same


2016-01-26 22:46 GMT+01:00 Jarl Arntzen <notifications@github.com>:

> *Related*: #55 <https://github.com/OpenShot/openshot-qt/issues/55> on
> Ubuntu 14.04 LTS
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenShot/openshot-qt/issues/64#issuecomment-175247026>
> .
>



-- 
"Dabilen kamerari Kroma-keyrik ez"

**Comment by jonoomph** [comment]
Yep, this is fixed now. Thanks!
