### ISSUE TITLE
Openshot locked with custom profiles

### ISSUE THREAD

**Issue by AntonioIT** [OpenShot/openshot-qt#643]
**System Details:**
* Operating System / Distro: Ubuntu 16.04 LTS
* OpenShot Version: 2.3.2
* _Please attach log files if crash_

PC with 2 GB RAM
OS 32 bit

I apologize but I am very new with Linux and for this reason I must be "guided" to be able to supply other information.

**Issue Description and steps to reproduce:**
0. After installed OpenShot I made a simple video (using two simple titles, 2-4 videos with in-out fading and no more) that was OK.
1. I added two new custom profiles with extension .prf  in profiles folder, that seems to work OK.
2. I modified one of these profile (named "640x352 16:9.prf") but my editor created a backup file (suppose) named "640x352 16:9.prf~".
3. I re-run OpenShot but appeared only a transparent "frame" with a shadow. To close it I need to kill the process.
I tried again after reboot or switch off/on but OpenShot behaviour is always the same.
4. Using Synaptics, I uninstalled OpenShot and re-installed it, but again it exhibits the same behaviour.
5. I tried to delete all custom files (backup included) from profiles folder, re-run OpenShot but again it locks.

I attached a zip with both logs and settings:
[log_and_setting_files.zip](https://github.com/OpenShot/openshot-qt/files/1000350/log_and_setting_files.zip)

**Comment by DylanC** [comment]
@AntonioIT - Thanks for your feedback. We will investigate.

**Comment by DylanC** [comment]
@AntonioIT - I would recommend to delete the settings folder.
