### ISSUE TITLE
Feature suggestions

### ISSUE THREAD

**Issue by AntonioIT** [OpenShot/openshot-qt#644]
**System Details:**
* Operating System / Distro: Ubuntu 16.04 LTS
* OpenShot Version: 2.3.2
* _Please attach log files if crash_
System Details:
* PC with 2 GB RAM
* OS 32 bit
**Issue Description and steps to reproduce:**

Hi all!
1. How can I reduce font size in OpenShot window (and its panels)? In case it is not possible, please add this setting.
2. How to define a custom layout with smaller timelines? 
3. I work with only 2 timelines and to avoid to waste space I delete all unused timelines. Is it possible to set OpenShot to always start with a defined number of timelines? In case it is not possible, please add this setting.
4. Is it possible in some way to add the same video/volume fade in/out to all object in the timelines?
5. How to have the label displayed in the timeline instead of filenames?
Thank you in advance!

**Comment by DylanC** [comment]
@AntonioIT - The items listed are not possible just yet. We will take them as enhancement suggestions.
