### ISSUE TITLE
thumbnails disappear from timeline when project is moved

### ISSUE THREAD

**Issue by jcm69** [OpenShot/openshot-qt#645]
**System Details:**
* Operating System / Distro: ? windows 7
* OpenShot Version: ? 2.3.1
* _Please attach log files if crash_

- create a project in a dir with, say, 2 sequences, one after the other in the same timeline (files are drag and droped)
- save
- copy the saved files to a new dir, on a USB key for example
- open the .osp file. Tracks are shown but thumbnail are missing (interogation point instead)

HTH, this is just a little bug, many thanks for this great application.

**Comment by CapitainFlam** [comment]
Hi there, 
confirmation that I have the same issue. 
I moved the "osp" FILE. Moved the "assets" associated FOLDER. But didn't moved the "thumbnails" associated FOLDER... 
That was a bad idea. No way to regenerate those thumbnails, even if you choose : Right click > "show as wave" then "show as thumbnail".

**Comment by mikelacsa** [comment]
I tested this bug on the latest version and I confirm that it is fixed. Closing the issue now.
