### ISSUE TITLE
How can I make a picture zoom during a video?

### ISSUE THREAD

**Issue by bell18** [OpenShot/openshot-qt#646]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

**Comment by DylanC** [comment]
@bell18 - Right click to see this Zoom option:

![image](https://user-images.githubusercontent.com/4488048/30282030-fc62543e-970b-11e7-9169-30d27bcf91f8.png)

**Comment by bell18** [comment]
thank you!!

**Comment by DylanC** [comment]
@bell18 - You are very welcome. :)
