### ISSUE TITLE
Traceback error after double click the OpenShot v2.3.2

### ISSUE THREAD

**Issue by quelo1972** [OpenShot/openshot-qt#647]
**System Details:**
* Operating System / Distro: Windows 10 64bit
* OpenShot Version: 2.3.2
* _Please attach log files if crash_
![cattura](https://cloud.githubusercontent.com/assets/28729838/26103452/d025f742-3a39-11e7-8820-505cfda37d85.PNG)
**Issue Description and steps to reproduce:**
When I try to install OpenShot 2.3.2 to my pc with Windows 10 64bit and try to lounch it, I have the attached error.

Can you help me?

Thanks.

**Comment by DylanC** [comment]
@quelo1972 - Will test this today. Thanks.

**Comment by DylanC** [comment]
Cannot reproduce this today.

**Comment by Ravenh4wk** [comment]
I had the same issue and couldn't find any fix on the web, but have managed to sort the problem my self. What you need to do is go into your user account which is linked to Openshot.

So, go to your windows directory and select 'users' and the account which you saved your original Openshot data to and delete any folders related to Openshot. Remember to save any previous videos that you have edited (these should be .osp files that will appear at the bottom of your main user folder.)

This was an instant fix for me!
