### ISSUE TITLE
Openshot Microsoft Visual C++ runtime error

### ISSUE THREAD

**Issue by osmancoskun** [OpenShot/openshot-qt#648]
Installed Openshot on Windows 8.1 and got runtime error.
I open project that i copied from linux machine.
when i try to open it, it gives runtime error and crashes. 
also tried latest daily build. still gives error and crashes.
i run SFC /SCANNOW and restarted, didnt work.

**Comment by DylanC** [comment]
@osmancoskun - Thanks, I'll have a go at this one.

**Comment by DylanC** [comment]
No problem detected in v2.4.

**Comment by javednasir** [comment]
Installed Openshot on Windows 10 and got runtime error.
Can anyone suggest wat to do ???
![error](https://user-images.githubusercontent.com/28708156/31663321-10682fd8-b35b-11e7-9f84-e2821da5087b.jpg)
