### ISSUE TITLE
Image keeps getting a black box in the center, affecting the video.

### ISSUE THREAD

**Issue by kirbyfan173** [OpenShot/openshot-qt#653]
**System Details:**
* Operating System / Distro: Windows 10
* OpenShot Version: 2.3.2
* _Please attach log files if crash_

**Whenever an image file is placed on the timeline, a black box corrupts the file in the video preview and appears in the exported video.**

**Comment by DylanC** [comment]
@kirbyfan173 - Do you have an example project for me to test?

**Comment by DylanC** [comment]
Unable to reproduce in the latest daily build.
