### ISSUE TITLE
No audio on new install of 2.3.2. Windows 10.

### ISSUE THREAD

**Issue by ForrestErickson** [OpenShot/openshot-qt#654]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

**Comment by ForrestErickson** [comment]
I have tried wav files I made with audacity which audacity plays fine.
I got some mp3 files of test tones.
I add them to tracs but they do not play in the preview. 
I even made a new project with only audio file(s) and they do not play.

As a user for only about 24 hours I can assume it is an error on my part but I am baffled.

**Comment by ForrestErickson** [comment]
I rebooted the computer and I have audio. Something got corrupted that a reboot fixed.
I had been playing video with audio with VLC.
I think I had also used Audacity.

I have used both since with out losing audio on OpenShot.

**Comment by DylanC** [comment]
@ForrestErickson - Does this issue affect you on OpenShot v2.4?

**Comment by ForrestErickson** [comment]
Regarding, "Does this issue affect you on OpenShot v2.4?" 
I am using 2.3.2 at this time. Thanks for the question as I am now prompted to upgrade.

I think the problem was not with OpenShot but some how with my computer sound system as I have had something similar happen when running Audacity.  The details escape me I am afraid.

**Comment by DylanC** [comment]
No problem. Thanks for getting back to me. I will close this for now if you don't mind.
