### ISSUE TITLE
Software randomly crashes

### ISSUE THREAD

**Issue by bell18** [OpenShot/openshot-qt#655]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

**Comment by kirbyfan173** [comment]
same

**Comment by jdwilliam1971** [comment]
On OpenSuse Leap 42.2 Plasma 5 it seems that the program is not saving the edits automatically and will crash after a few edits if it isn't manually saved every couple of edits. If edits are made too quickly the swap out to temp backup doesn't get made and eventually program crashes.

Sure wish the old version of Openshot was still available.

**Comment by DylanC** [comment]
Not enough detail to test this issue.
