### ISSUE TITLE
cant speed up/slow down video without crashing

### ISSUE THREAD

**Issue by bell18** [OpenShot/openshot-qt#656]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

**Comment by bankhans** [comment]
Windows 7
OpenShot 2.3.3

**Comment by bankhans** [comment]
Name der fehlerhaften Anwendung: launch.exe, Version: 0.0.0.0, Zeitstempel: 0x57a98a3e
Name des fehlerhaften Moduls: msvcrt.dll, Version: 7.0.7601.17744, Zeitstempel: 0x4eeb033f
Ausnahmecode: 0xc0000005
Fehleroffset: 0x000000000000120b
ID des fehlerhaften Prozesses: 0x588
Startzeit der fehlerhaften Anwendung: 0x01d2d1828c61ec67
Pfad der fehlerhaften Anwendung: C:\Program Files\OpenShot Video Editor\launch.exe
Pfad des fehlerhaften Moduls: C:\Windows\system32\msvcrt.dll
Berichtskennung: f053a5f8-3d75-11e7-b8a3-d43d7ebde8fa

**Comment by bankhans** [comment]
Same happens under Debian Linux.

**Comment by bell18** [comment]
please fix this

**Comment by itamarc** [comment]
Same with version 2.3.3 in Windows 10.

**Comment by reddn** [comment]
Dup of #587 The playback will work in 2.3.4, but the playback speed will still not work, which is #588

**Comment by DylanC** [comment]
Confirmed as fixed in #588
