### ISSUE TITLE
Is 60fps .mp4 supported?

### ISSUE THREAD

**Issue by TombyT** [OpenShot/openshot-qt#659]
i5 6600K (4.4 GHz), GTX 1060, 16 GB ram, 256 SSD, 1 TB HDD
Ubuntu 17.04 (been having same issue on Windows 10, Ubuntu 16.04, and 16.10)*?
Version 2.0-2.33 and plenty of appimages

I've posted before but my main issue stills seems unresolved. I've been trying to make a short 10 minute clip of GoPro files from last Christmas and have been this whole time, trying/re-trying to export or even edit every 1-2 weeks with varying OS and app images or installs.

This last week I was actually able to export my entire film (normally it would get to 50% and freeze indefinitely) but the audio was ear piercingly choppy towards the end.

an example of the types of files I'm including can be found here:
https://www.dropbox.com/s/is91kqqlr1v62j3/GOPR0258.MP4?dl=0

Is this a known issue? Any hope/solution in sight? I love the work you've been doing to keep Openshot constantly updating but in my case I've been unable to really use it at all which is a shame because it looks really promising.

**Comment by TWuerdemann** [comment]
#635 seems to be the same issue here.

**Comment by fabrixx** [comment]
Solved changing profile to 60fps: https://github.com/OpenShot/openshot-qt/issues/854

https://www.osside.net/2017/08/openshot-2-a-60fps-si-puo-fare-lo-sfogo/

**Comment by DylanC** [comment]
Solved by following fabrixx comment.
