### ISSUE TITLE
Frame Number Animated Titles

### ISSUE THREAD

**Issue by sydneyjd** [OpenShot/openshot-qt#66]
Hello, i just thought i would bring this to your attention.
Im running the latest version of Blender and Openshot.
When i render a animated title or try to change what frame i'm viewing, it always says "64/128" for the frame, even though thats not the frame it is rendering. I attached an screenshot.
I'm also havign a freezing issue, but thats unrelated to this i figure. :)

Keep up the good work! This is looking awesome!

-Sydney

![screenshot_2016-01-26_14-10-30](https://cloud.githubusercontent.com/assets/8949851/12591731/38fd6d74-c437-11e5-8c84-2024bfed60d9.png)

**Comment by jonoomph** [comment]
Thanks for the bug report! This is now fixed in the latest build.
