### ISSUE TITLE
OpenShot UI is zoomed in on non-HiDPI screen

### ISSUE THREAD

**Issue by Imerion** [OpenShot/openshot-qt#660]
**System Details:**
* Operating System / Distro: Xubuntu 17.04
* OpenShot Version: 2.3.3
* _Please attach log files if crash_

When using OpenShot on my computer the UI is zoomed in. It seems like for every pixel on normal applications OpenShot draws four. I believe this might be due to some HiDPI setting, but my screen is not HiDPI. I'm using 1920x1280, and as it is now the UI of OpenShot takes so much space I can't use the program. Video tracks are barely visible, etc. I can't seem to find any option to change this.

Perhaps my computer falls under a HiDPI setting by misstake?

**Comment by LuSo58** [comment]
👍

**Comment by sanchosk** [comment]
Same thing happens to me with Ubuntu 17.04, installation from PPA repo, openshot-qt version 2.3.4.
When changing the resolution to 1360x768 the UI seems to be OK, when starting in fullHD, the UI thinks I have HiDPI display. I have 13.3" screen with fullHD resolution and the UI is not usable in this mode.
Is there some switch I can change to fix this?

**Comment by sanchosk** [comment]
The difference in log between starting on low-res and fullHD is:
FullHD
`timeline:INFO Adjusting max size of preview image: PyQt5.QtCore.QRect(0, 8, 546, 307)`
1024x768
`timeline:INFO Adjusting max size of preview image: PyQt5.QtCore.QRect(7, 0, 529, 298)`

**Comment by sanchosk** [comment]
Interestingly, this does not happen with 2.3.4 downloaded using appimage from the OpenShot.org website, although the release ID is the same...

**Comment by Imerion** [comment]
This seems to be related to something in the QT libraries. Latest version of Scribus (1.5.3) also has this problem. Solution for me was to use "export QT_AUTO_SCREEN_SCALE_FACTOR=0" before running OpenShot.

**Comment by sanchosk** [comment]
Thanks! That fixed the issue for me on Ubuntu.

**Comment by DylanC** [comment]
@Imerion @sanchosk - Is this issue resolved?

**Comment by sanchosk** [comment]
Yes, when I run the packaged application or use the shell parameter, the
issue is fixed - so apparently QT problem on Ubuntu, not OpenShot.

**Comment by DylanC** [comment]
@sanchosk - Thanks. I will close this issue for now if you don't mind.

**Comment by ChinchuC** [comment]
I am experiencing the same issue on my Windows laptop. Changing themes did not work.
![image](https://user-images.githubusercontent.com/65478691/133109998-ad9d098b-f893-46a4-9d95-1988ab4be662.png)
