### ISSUE TITLE
Traceback error after double click the OpenShot v2.3.3

### ISSUE THREAD

**Issue by quelo1972** [OpenShot/openshot-qt#663]
**System Details:** Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz 3.40GHz 16,0 GB RAM
* Operating System / Distro: Windows 10 64 bit
* OpenShot Version: 2.3.3
* _Please attach log files if crash_
[openshot-qt.txt](https://github.com/OpenShot/openshot-qt/files/1018280/openshot-qt.txt)

**Issue Description and steps to reproduce:**
OpenShot 2.3.3 crashes after launching it with the following error:
![cattura](https://cloud.githubusercontent.com/assets/28729838/26301388/5bfa9010-3ee1-11e7-90cb-dc6f12ec3aa0.PNG)

**Comment by DylanC** [comment]
Tested on Win10 with latest version and cannot reproduce. Please try a newer version.
