### ISSUE TITLE
Launch.exe has stopped working as soon as I run my encoding

### ISSUE THREAD

**Issue by piratrax** [OpenShot/openshot-qt#664]
Hello, I have the following message that appears and tells me that lauch.exe has stopped working as soon as I run my encoding? I am running windows x64.

![capture](https://cloud.githubusercontent.com/assets/28861080/26303099/b4df44c8-3ee6-11e7-99ec-c45ea2a9bbe4.PNG)

**Comment by piratrax** [comment]
Hello, I have the following message that appears and tells me that lauch.exe has stopped working as soon as I run my encoding? I am running windows 10 x64.
![capture](https://cloud.githubusercontent.com/assets/28861080/26303160/eb0e0ba6-3ee6-11e7-89f4-1b1d64558c75.PNG)

**Comment by vales** [comment]
I also have the same problem when I add a sound file to a track

Windows 10 x64

All versions of Openshot 2.3.3 also the dayli version OpenShot-v2.3.3-5-g4349753-55-629-x86_64.exe May 23, 2017, 11:55 pm

**Comment by DylanC** [comment]
@vales - Also v2.4?

**Comment by vales** [comment]
Version 2.4.0 is ok. The problem had already been resolved with version 2.3.4.

**Comment by DylanC** [comment]
@vales - Thanks, closing for now.

**Comment by soccerguy243** [comment]
Happens to me too still. Windows 10.
