### ISSUE TITLE
"Cannot Find" Project Files after moving .osp save file

### ISSUE THREAD

**Issue by 0o-o0** [OpenShot/openshot-qt#665]
**System Details:**
* Operating System / Distro: Ubuntu 14.04
* OpenShot Version: openshot-qt 2.3.3
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
1. New Project
2. Import video
3. Save project
4. Move saved project file to another directory
5. Open saved project file
6. "Cannot find" project files

When I move the file back to the original save directory it works fine, so presumably there are some relative links in there somewhere.

**Comment by DylanC** [comment]
@0o-o0 - Yes, that is correct. Usually I have the project file inside the same folder as my source files.
