### ISSUE TITLE
Stalls at 61%, then doesn't include last clip slice

### ISSUE THREAD

**Issue by brainthinks** [OpenShot/openshot-qt#666]
**System Details:**
I'm not sure what I should put here that isn't described below.  Perhaps the following:
GeForce GTX 1080 FTW
Intel i7 circa the year 2013
Gigabyte mobo
Samsung SSD
I can provide further detail if necessary

* Operating System / Distro: ?
Linux Mint 18.1

* OpenShot Version: ?
2.3.3

* _Please attach log files if crash_
No crash that I'm aware of.  In fact, I'm quite impressed with the lack of crashes.  The program will hang sometimes, likely during intensive operations, but it has become usable again EVERY TIME, except for the very last time that made me write this ticket, but still it didn't technically crash.  Kudos.  That's more than I can say for Apple's products.

**Issue Description and steps to reproduce:**
I'm not 100% about how to reproduce it, but as a new user, here is my experience.

1. One project, one mkv video file, about 2 hours long, recorded from Open Broadcaster Software (obs).
2. I cut the one mkv video file into 3 parts using the scissor tool.  Techically, I cut it into 5 parts and deleted 2 of those parts.
3. I exported the video using one of the 1080, 60 fps settings.
4. I went to bed.
5. When I woke up and checked the file, after maybe 10 minutes the video was nothing but a black screen.  The export was about 35 minutes long.
6. I tried exporting at 720p, then again at 360p, and both times, the export hung at around 61%.
7. I know this because I kept htop open, and it was at first using all 8 cores at maybe 40% each, which I figure is a good thing.  Once it hit 61%, it stopped using all of my cpu cores, and instead maxed out just one core.
8. After a while on the 360p export, after being stuck at 61%, it resumed using all 8 cores, but it only exported 2 out of my 3 file slices - meaning that it only exported 21 out of the 35 minutes, which is approximately a truncation of my last file slice.
9. I tried re-opening the project, and it seems that my 3rd slice had its time offset.  I tried to re-edit the last slice, but the program froze.  It didn't crash, but after about 10 minutes, I still couldn't do anything.

I'm not sure what else to put here.  I really want this project to work, and it came pretty close.  Let me know what other info I can provide.

**Comment by DylanC** [comment]
@brainthinks - Can you try the same project with the latest daily build and let us know how far you get. Thanks.

**Comment by DylanC** [comment]
Not able to reproduce this issue.
