### ISSUE TITLE
Openshot 2.3.3 crash when I add mp3, wav or ogg in a track. Attach vídeo of crash. BUG!

### ISSUE THREAD

**Issue by emilict** [OpenShot/openshot-qt#668]
**System Details:** Intel Core i7 3770 CPU 3,4GHz
* Operating System / Distro:  Windows 10 Professional
* OpenShot Version:  2.3.3
* _Please attach log files if crash_
Where are this log? :-)

**Issue Description and steps to reproduce:**
Windows 10 with Openshot 2.3.3 crash every time that I add a audio track in all formats: mp3, wav, ogg, with or without vídeo.
I capture the crash, look the video:
https://youtu.be/UL759EWZRdo

Thanks to all the people that collaborate for your work! :-)

**Comment by mwhite212** [comment]
I'm receiving the same error. I hope I've attached the correct logs.

It allows me to import the audio file, but it crashes when I try to move it within the timeline OR just after I play the video from within Open Shot. As soon as it reaches the end of the timeline, it crashes. Only occurs with a separate audio track.
[Uploading openshot-qt_log1.txt…]()
[Uploading openshot_settings.txt…]()
[openshot-qt_log2.txt](https://github.com/OpenShot/openshot-qt/files/1030765/openshot-qt_log2.txt)
[Uploading openshot-qt_log3.txt…]()
[Uploading libopenshot_log.txt…]()

**Comment by yg42** [comment]
Same behavior under linux.

```
[AudioData @ 0x7fd0bd4399a0] invalid NULL pointer for src[0]
Caught signal 11 (SIGSEGV)
---- Unhandled Exception: Stack Trace ----
  /tmp/.mount_yb5rQr/usr/bin/libopenshot.so.11 ( openshot::FFmpegReader::Close()           + 0x29a )  [0x7fd0cf107546]
  /tmp/.mount_yb5rQr/usr/bin/libopenshot.so.11 ( openshot::FFmpegReader::Seek(long)        + 0x5c3 )  [0x7fd0cf10ca4d]
  /tmp/.mount_yb5rQr/usr/bin/libopenshot.so.11 ( openshot::FFmpegReader::GetFrame(long)    + 0xb41 )  [0x7fd0cf108afd]
  /tmp/.mount_yb5rQr/usr/bin/libopenshot.so.11 ( openshot::FrameMapper::GetOrCreateFrame(long)  + 0x347 )  [0x7fd0cf13416f]
  /tmp/.mount_yb5rQr/usr/bin/libopenshot.so.11 (                                           + 0x105fa3)  [0x7fd0cf138fa3]
  /tmp/.mount_yb5rQr/usr/bin/libgomp.so.1 (                                           + 0x834a)  [0x7fd0ccb1134a]
  /lib/x86_64-linux-gnu/libpthread.so.0 (                                           + 0x76ba)  [0x7fd0e4bc96ba]
  /lib/x86_64-linux-gnu/libc.so.6 ( clone                                     + 0x6d  )  [0x7fd0e48ff82d]
---- End of Stack Trace ----
QLibraryPrivate::unload succeeded on "/tmp/.mount_yb5rQr/usr/bin/imageformats/libqgif.so"  
QLibraryPrivate::unload succeeded on "/tmp/.mount_yb5rQr/usr/bin/imageformats/libqico.so"  
QLibraryPrivate::unload succeeded on "/tmp/.mount_yb5rQr/usr/bin/imageformats/libqjpeg.so"  
QLibraryPrivate::unload succeeded on "/tmp/.mount_yb5rQr/usr/bin/imageformats/libqsvg.so"  
QLibraryPrivate::unload succeeded on "/tmp/.mount_yb5rQr/usr/bin/platforms/libqxcb.so"  
QLibraryPrivate::unload succeeded on "Xcursor" (faked) 
```

**Comment by DylanC** [comment]
Working on Windows 10 with OpenShot v2.4 daily build.
