### ISSUE TITLE
Animated Title Comma issue

### ISSUE THREAD

**Issue by sydneyjd** [OpenShot/openshot-qt#67]
Hello again. 
Yes, i have been testing "the tar" out of the animated title section of openshot 2. ;) Ayways, when i try to use a comma in any of the animated titles it always appears with a "\" before it. I have some screenshots attached.
Thanks for all you do!
## 

![screenshot_2016-01-27_10-09-33](https://cloud.githubusercontent.com/assets/8949851/12617761/1cf9af4a-c4df-11e5-8c3e-0e1d12c00aba.png)
![screenshot_2016-01-27_10-11-25](https://cloud.githubusercontent.com/assets/8949851/12617762/1cf9ab8a-c4df-11e5-9238-933293018cab.png)

Sydney

**Comment by jonoomph** [comment]
This was fixed a while back. Please verify this works on the latest daily build, and reopen if the problem still happens. Thanks!
