### ISSUE TITLE
Openshot 2.3.3 crash when apply Time effect. Attach vídeo of crash. BUG!

### ISSUE THREAD

**Issue by emilict** [OpenShot/openshot-qt#670]
**System Details:** Intel Core i7 3770 CPU 3,4GHz
* Operating System / Distro:  Windows 10 Professional
* OpenShot Version: 2.3.3
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
Openshot 2.3.3 crash when apply Time effect
I capture the crash, look the video:
https://www.youtube.com/watch?v=DNzEUkBLj2Y

Thanks to all the people that collaborate for your work! :-)

**Comment by mwhite212** [comment]
I'm receiving the same error.  I hope I've attached the correct logs.

It allows me to import the audio file, but it crashes when I try to move it within the timeline OR just after I play the video from within Open Shot.  As soon as it reaches the end of the timeline, it crashes.  Only occurs with a separate audio track.

[libopenshot_log.txt](https://github.com/OpenShot/openshot-qt/files/1029488/libopenshot_log.txt)
[openshot-qt_log3.txt](https://github.com/OpenShot/openshot-qt/files/1029492/openshot-qt_log3.txt)
[openshot-qt_log2.txt](https://github.com/OpenShot/openshot-qt/files/1029489/openshot-qt_log2.txt)
[openshot-qt_log1.txt](https://github.com/OpenShot/openshot-qt/files/1029490/openshot-qt_log1.txt)
[openshot_settings.txt](https://github.com/OpenShot/openshot-qt/files/1029491/openshot_settings.txt)

**Comment by reddn** [comment]
Poss dup of #587 but also will not work with 2.3.4 and you will still have the problem in #588

**Comment by DylanC** [comment]
Confirmed as fixed in #588
