### ISSUE TITLE
No sound on video or audio track

### ISSUE THREAD

**Issue by 5ulo** [OpenShot/openshot-qt#673]
**System Details:**
* Operating System / Distro: Arch + Gnome Shell 3.24 + PulseAudio
* OpenShot Version: 2.3.3-1
* [libopenshot.log.txt](https://github.com/OpenShot/openshot-qt/files/1025848/libopenshot.log.txt)
* [openshot-qt.log.txt](https://github.com/OpenShot/openshot-qt/files/1025851/openshot-qt.log.txt)

**Issue Description and steps to reproduce:**
1. Run OpenShot
2. Import files (mine example was mp4 h264 + AAC LC audio)
3. Drag n drop video or audio file in some track
4. Preview
5. No sound
6. Right click on track > Properties > Enable audio "-1" change to "0", then "1"
7. Still no sound 

If I should provide more information just ask what and where do I get them and I'll send it.

**Comment by DylanC** [comment]
@5ulo - Do you have an example project to attach here?

**Comment by Zecatfish** [comment]
When I was doing my editing, the audio would not show up in the preview,  but it would in the finished video.

**Comment by DylanC** [comment]
@5ulo - I would recommend to try the latest daily build.
