### ISSUE TITLE
Why would people use Openshot if you can't export stuff?

### ISSUE THREAD

**Issue by Theedoek** [OpenShot/openshot-qt#674]
I made a video but i can't export it?! It seems to happen to a lot of people. So how is this programm usefull if you cant export it? Is my video now useless, and should I do it all over again? On a programm that actually works?!!!!!!!!

**Comment by burtbick** [comment]
Just started working with the latest OpenShot so I may hit this problem later, but I had NO problem exporting a video I made under Linux.  Exported the video just fine.  It would be helpful if you could give some details about your system, and some details about how you were trying to export the video.

For example:
My System: Linux Mint 17.1 64 bit with an AMD Graphics card and 8 GB of RAM.  About 500 Gb of free hard disk space.

Video export took the defaults:
Profile: All Formats
Target: MP4(h.264)
Video Profile: HDV 720 24p (1280x720)
Quality: High

With a bit more information someone may have some suggestions on how to troubleshoot your problem.

So far OpenShot looks pretty good, but I had one performance issue that I'll looking to track down, but that is totally different from the issue you appear to be having.

In any case always try to give more details than just "it doesn't work".  That's true for any software.

**Comment by DylanC** [comment]
Closing due to lack of details on this ticket. We need more information to tackle issues. Thanks.
