### ISSUE TITLE
Crashed when adding sound files

### ISSUE THREAD

**Issue by danland21344** [OpenShot/openshot-qt#676]
Hi,
Not a new bug. I see others are already mentioning it, but figured I'd post a log file that might help.

I'm on Windows 10 and whenever I try to add a sound track, the program crashes. If I try to drag and drop it to the timeline it will crash. If I right click and add to timeline, the music track will appear. But if I try to preview it, program crashes. And if I try to export as video, program crashes.

I tried with a wav file, mp3, and AMR. Same issue: when I tried to preview, software crashed. Tried exporting without previewing, but it still crashed.

I tried adding this to a project that already had video and was encountering this. 

So last thing I did was a clean install and added just an audio track. No other tracks, and got the same crash. So maybe that helps you narrow down what you're looking for. Attached a log of the last incident.

 Best of luck.

Dan

[openshot (1).pdf](https://github.com/OpenShot/openshot-qt/files/1027315/openshot.1.pdf)

**Comment by JaviAibar** [comment]
Same here!

**Comment by Decoherent** [comment]
Same problem here. Attaching a log for you, I just started a new project, added an MP3 file (although I've tried with other formats), and as soon as I drag it past one of the tracks, OpenShot crashes.
[openshot-qt.zip](https://github.com/OpenShot/openshot-qt/files/1027958/openshot-qt.zip)

**Comment by DylanC** [comment]
@danland21344 - Does this happen in v2.4 or in the daily build?

**Comment by DylanC** [comment]
Unable to reproduce the crash. This is working in the v2.4 daily build. Please try the latest version.
