### ISSUE TITLE
Unsupported characters in filename

### ISSUE THREAD

**Issue by Sophia2329** [OpenShot/openshot-qt#677]
**System Details:**
* Operating System / Distro: Windows 10 Home
* OpenShot Version: 2.3.3 (downloaded the same day)

**Issue Description and steps to reproduce:**
Several recorded shots of mine had my native language's letter "é" in their names.
After both dragging en masse and individually did nothing, I tried renaming them to English, getting rid of the letter in the process; then they correctly showed up in the Project Files.
As this was the difference between correctly loading and not, I am lead to believe OpenShot lacks support for extensive character sets (agrees with #628).
Further research into the issue, consisting of creating an empty "é.mp4" file and dragging it into Project Files and renaming it to "e.mp4" and trying again supports this thought, as its results have been nothing for the former, and an expected error message from OpenShot rejecting the file as not a video or audio in the latter. The former also occured when trying to import "á.mp4", "ž.mp4" and "👌.mp4".
This might be the issue of a regular expression filtering pathnames in some manner using `\w` or some other limiting presumptions about the pathname in the code. Perhaps there was a security reason for not extending to Unicode encodings?

**Comment by PASTJL** [comment]
In 2.3.4 version, on Windows 10, I confirm this bug with accentuated character in name of files, it fails also if a parent directory has a name with an accentuated character. The whole paths of all files of the project must certainly not containing accentuated characters.
Removing all accentuated characters make OpenShot running corectly.

**Comment by DylanC** [comment]
@PASTJL @Sophia2329 

I think the latest daily build solves issues with those characters:
https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.4.0-9-g7267417-56-648-x86_64.exe

Let me know if it is now working for you.

**Comment by PASTJL** [comment]
I made a test with the last daily dev 2.4.0-10  : 
- create a folder with accent and spaces in the name
- put a mp4 with accent and spaces in the names
- create a project file with accent and spaces
- importing the mp4 file in the project, put the clip on the timeline
- I can play in monitor
- saving project is OK
- exporting towards a mp4 file with accents and space is OK

So the bug can be closed.
Out Topic : does OpenShot supports mkv files?, i can import and put in the timeline but i can't see it in the previw monitor. The timeline cursor stays immobile

**Comment by DylanC** [comment]
@PASTJL - Thanks for testing. Closing as issue is fixed.

Regarding .mkv files I will test during the week and tag you on a new issue if its not working for me.

**Comment by PASTJL** [comment]
Sorry my mkv file was corrupted : no lenght shown in vlc viewer, certainly a corrupted indexation.
I tried with another correct mkv file in the last daily version ( 2.4.0-11) and it runs correctly.

**Comment by DylanC** [comment]
@PASTJL - Sounds like good news for us then!  :)
