### ISSUE TITLE
No Sound in Exported Videos, AND Audio File Abruptly Stops at 2:30 in OpenShot

### ISSUE THREAD

**Issue by almondpunch** [OpenShot/openshot-qt#678]
**System Details:**
* Operating System / Distro: Windows 7
* OpenShot Version: 2.3.3
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

**Two big problems:**

(1) Sound does not play in exported videos. I tried exporting in .mp4 and .mov formats. The .mov was even worse - random whole-screen flashes of orange interfered in the opening slide. 

(2) While I'm working on the video in OpenShot, my song simply stops playing at around 2:30. Sometimes it goes silent, and sometimes it makes this weird ticking sound. This happened with two different .mp3 songs I imported.

Thus, I can't complete the production of my video, AND I can't get a workable export of the existing file I have. 

What is going on?

**Comment by vales** [comment]
I confirm the same problem with all versions of openhots, including OpenShot-v2.3.3-7-gca44aff-55-630-x86_64.exe

Windows 10 16Gb ram

**Comment by Redraider89** [comment]
> (2) While I'm working on the video in OpenShot, my song simply stops playing at around 2:30. Sometimes it goes silent, and sometimes it makes this weird ticking sound. This happened with two different .mp3 songs I imported.
> 
> Thus, I can't complete the production of my video, AND I can't get a workable export of the existing file I have.
> 
> What is going on?

The work around/fix for this I found is if you are using an MP3 file for your audio, convert it to Ogg Vorbis .ogg format and that works better.

**Comment by Redraider89** [comment]
> (2) While I'm working on the video in OpenShot, my song simply stops playing at around 2:30. Sometimes it goes silent, and sometimes it makes this weird ticking sound. This happened with two different .mp3 songs I imported.

The fix I have found for this issue is, if you are using an MP3 file,  to convert the file .ogg format and that fixed my issue with the corrupt sound at about 2 and a half minutes.

**Comment by Redraider89** [comment]
As for no sound in exported videos, set the Audio Codec to "aac" instead of "ac3" and that worked for me.

**Comment by DylanC** [comment]
@almondpunch - This issue has been resolved in the v2.4 daily build. Please try it.

**Comment by alexishp** [comment]
Why do you keep closing these threads. This issue is still going in v2.4.

**Comment by DylanC** [comment]
@alexishp - I can't remember the ticket numbers but it was already confirmed as fixed by multiple users. Your issue must be different.

**Comment by Redraider89** [comment]
I had two problems.  It's been a while, but the sound was cutting out I believe and also the video stopping at 2:30.  The fix to any problems I was having was to change the format of the audio file to .ogg format from .mp3 and changing from "ac3" to "aac". Note: there is no drop down list to select aac, you have to delete "ac3" and type in "aac" to change it.

**Comment by DylanC** [comment]
@alexishp - See fix was previously confirmed as working on #800.
