### ISSUE TITLE
Video Importing Issues

### ISSUE THREAD

**Issue by 109Natsu** [OpenShot/openshot-qt#679]
**System Details:**
* Operating System / Distro: Windows 10
* OpenShot Version: 2.3.3
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
Hello, first of all I'm enjoying OpenShot, it is the best free video editor that I found! Unfortunately I have had two issues and one is more significant than the other.
The first issue is where one of my files got automatically scaled horizontally. The only way I was able to fix this was by scaling the Y through properties, but I don't want to make the video smaller in size. This only happened with one of my files. I tried converting it to other formats and reimporting it but that didn't change anything.
The second issue is that when I tried to import one of my videos it suddenly freezes and stopped working. It took most of my CPU so I had to end the program with the task manager. This issue only happens with one file, but it's a different video. I tried converting this too and reimporting it but that didn't help...
Has anyone experienced something similar to this? If so, what am I doing wrong here?

Thank you for reading

**Comment by DylanC** [comment]
@109Natsu - If you try the latest daily build your experience should be much better. Thanks for your feedback.
