### ISSUE TITLE
WINDOWS: find the path of the program BLENDER and INKSCAPE more easily

### ISSUE THREAD

**Issue by telelauro** [OpenShot/openshot-qt#68]
I am trying to use those program in windows, blende and inkscape. Both of them i have instaled in my computer but i cann, t find the path to copy in openshot. I think that maybe is better to openshot find automatic this paht, ok?
![blender y inkscape](https://cloud.githubusercontent.com/assets/16803007/12629308/961ca19e-c547-11e5-9d79-ab6cf1a70d1b.png)

**Comment by jonoomph** [comment]
Yeah, this probably needs some more thought. Maybe we could start by having a "Browse" button by any preference that is a file path on the computer?

**Comment by DerGenaue** [comment]
I would also suggest a small script on installation that searches for Blender and Inkscape in the usual locations (if the commands don't work)

**Comment by dancetheskies** [comment]
A browse button might help, but I manually typed in the full path to the file, which worked.  Here is mine:

C:/program files (x86)/blender foundation/blender/blender.exe

**Comment by telelauro** [comment]
I try to typed manually but it isn´t work any... I found in C: and I copy
all but nothing works ... umm sorry

2016-02-13 15:26 GMT+01:00 dancetheskies <notifications@github.com>:

> A browse button might help, but I manually typed in the full path to the
> file, which worked. Here is mine:
>
> C:/program files (x86)/blender foundation/blender/blender.exe
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenShot/openshot-qt/issues/68#issuecomment-183676620>
> .
>



-- 
"Dabilen kamerari Kroma-keyrik ez"

**Comment by dancetheskies** [comment]
Is your blender executable file (blender.exe) spelled the same and in the exact same folders as mine?  If not, it will not work.  If that's the case, copy the path name here so we can see what you typed.  If your path is exactly the same as mine, copy and paste the path I gave above into Open Shot to rule out a possible typing error.  It should work if the correct path is spelled correctly.

**Comment by telelauro** [comment]
In my computer, this is de path for blender

C:\Program Files\Blender Foundation\Blender

and it´s doesn´t work well.


[image: Imágenes integradas 1]

2016-02-13 20:28 GMT+01:00 dancetheskies <notifications@github.com>:

> Is your blender executable file (blender.exe) spelled the same and in the
> exact same folders as mine? If not, it will not work. If that's the case,
> copy the path name here so we can see what you typed. If your path is
> exactly the same as mine, copy and paste the path I gave above into Open
> Shot to rule out a possible typing error. It should work if the correct
> path is spelled correctly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenShot/openshot-qt/issues/68#issuecomment-183729556>
> .
>



-- 
"Dabilen kamerari Kroma-keyrik ez"

**Comment by telelauro** [comment]
I try to type at the end of the path -----.exe and this is the error
[image: Imágenes integradas 1]

2016-02-13 23:04 GMT+01:00 tele lauro <telelauro@lauro20.org>:

> In my computer, this is de path for blender
>
> C:\Program Files\Blender Foundation\Blender
>
> and it´s doesn´t work well.
>
>
> [image: Imágenes integradas 1]
>
> 2016-02-13 20:28 GMT+01:00 dancetheskies <notifications@github.com>:
>
>> Is your blender executable file (blender.exe) spelled the same and in the
>> exact same folders as mine? If not, it will not work. If that's the case,
>> copy the path name here so we can see what you typed. If your path is
>> exactly the same as mine, copy and paste the path I gave above into Open
>> Shot to rule out a possible typing error. It should work if the correct
>> path is spelled correctly.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/OpenShot/openshot-qt/issues/68#issuecomment-183729556>
>> .
>>
>
>
>
> --
> "Dabilen kamerari Kroma-keyrik ez"
>



-- 
"Dabilen kamerari Kroma-keyrik ez"

**Comment by dancetheskies** [comment]
Sorry, I don't understand the error message in your last post (not my native language), but based on your path to the blender executable that you gave, entering this text string into the OpenShot entry for the blender executable should work:
C:/program files (x86)/blender foundation/blender/blender.exe

If this doesn't work and generates an error message, I can't help you.

**Comment by telelauro** [comment]
thanks, but in my computer blender is instaled in another place,
C:\Program Files\Blender Foundation\Blender

but when I copy this path doesn´t work...I dont know what I can do
and for example Inkscape works perfectly

2016-02-13 23:29 GMT+01:00 dancetheskies <notifications@github.com>:

> Sorry, I don't understand the error message in your last post (not my
> native language), but based on your path to the blender executable that you
> gave, entering this text string into the OpenShot entry for the blender
> executable should work:
> C:/program files (x86)/blender foundation/blender/blender.exe
>
> If this doesn't work and generates an error message, I can't help you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenShot/openshot-qt/issues/68#issuecomment-183766331>
> .
>



-- 
"Dabilen kamerari Kroma-keyrik ez"

**Comment by dancetheskies** [comment]
I think you need to add "\blender.exe" (without the quotes) to your path. like this:
C:\Program Files\Blender Foundation\Blender**\blender.exe**

**Comment by telelauro** [comment]
THANKS ! I did it, I istalled de version 32bit in program files x86 and it´s allright ... and works!!! BUT ONE FOR ONLY and  so slow but work! ufff I try to do second and nothing ;(
![blender render](https://cloud.githubusercontent.com/assets/16803007/13033331/9b2603f4-d313-11e5-905a-d8706e346ddf.png)

Why is the three windows

**Comment by DerGenaue** [comment]
At this point, I have the question:
Why limit it to only Blender and Inkscape?

I would suggest a general "interface" for external programs:
The settings menu should have a tab "external programs" listing the needed programs.

Each program is saved somewhere with attributes like:
Name, Standard Command, Search Regex for automatical search, Test / Version command, Test / Version command output match
e.g.:
Inkscape, inkscape, /inkscape/i, -V, /Inkscape ([0-9\.]+) .*/
Blender, blender, /blender/i, -v, /Blender ([0-9\.]+) .*/

The Tab shows a table with the supported External Programs found, greyed if not found and a button to start the automatic search.

I think I'll find enough time the next days to implement that if @jonoomph gives me advice on how he imagines the software architecture to be like

**Comment by Noneus** [comment]
I have the same issue with the command window. The blende.exe /? command tells me about a command switch --background vor blender.exe. Appending that in the preferences dialog makes openshot complain, because its not a valid path.

**Comment by MoRZiLLo** [comment]
Amigo, tal vez cambiaste la letra por default Bfont, quizá por las freeSans o FreeMono. 
A mí me pasa lo mismo. Al utilizar las Bfont si funciona, pero cambiando tipo de letra no vá.

This message is in spanish because he ask to response and i can't write well in english.

The default Bfont runs good. You do not need to change if the path is it correct.

If you change to freeSans or FreeMono, does not run and say the message in the pics. 

Thanks to all for your answers :)

**Comment by crstllracing231** [comment]
By default, (if you didn't change folder location while installing Blender and Inkscapes)
Blender is (Copy-paste this)
C:\Program Files\Blender Foundation\Blender\blender.exe

Inkscapes is (Copy-paste this)
C:\Program Files\Inkscapes\inkscapes.exe

Tried by me, it works.

**Comment by dlcarraw** [comment]
The problem is that Windows users expect to use a backslash in the path (that's what Windows uses) but OpenShot expects a forward slash in the path (that's what Linux uses).

What Windows displays as the path: C:\Program Files\Inkscape\inkscape.exe
What OpenShot expects (and this works): C:/Program Files/Inkscape/inkscape.exe

So to make it work on a Windows platform, go to Edit -> Preferences -> Advanced Title Editor (Path) and enter
C:/Program Files/Inkscape/inkscape.exe

assuming, of course, that you've installed Inkscape into this location. The key is to replace backslashes with forward slashes in the path, wherever you've installed it.

**Comment by DylanC** [comment]
I put in a change to have browse buttons in future. This will work better in newer releases:
https://github.com/OpenShot/openshot-qt/pull/2255
