### ISSUE TITLE
MP3 audio crashes system

### ISSUE THREAD

**Issue by wadester** [OpenShot/openshot-qt#680]
**System Details:**
* Operating System / Distro: ?  Fedora 25 64-bit
* OpenShot Version: ?  2.3.3 from web site
* _Please attach log files if crash_  

**Issue Description and steps to reproduce:**

Create project
import MP3 file
try to drop MP3 on a track

**Comment by 109Natsu** [comment]
I'm having the same problem... Please help, it is impossible to create anything without using mp3 files 
I get this message when I try to use mp3 on timeline
![image](https://cloud.githubusercontent.com/assets/28969934/26509515/129604c4-4227-11e7-84be-0b751a9d4e58.png)

**Comment by ulises17** [comment]
Same issue with wav files in Windows 10 64-bit Anniversary Update

**Comment by Osthar03** [comment]
Same issue here. When MP# files were inserted to Timeline, the program suddenly stopped. 
![image](https://cloud.githubusercontent.com/assets/29009768/26526141/edd55790-438c-11e7-8b44-8388f61c6acf.png)
![audio crash](https://cloud.githubusercontent.com/assets/29009768/26526143/140464e2-438d-11e7-8d7f-e114ff550d7d.jpg)

**Comment by emilict** [comment]
Yes, same problem, with all sound files: mp3, wav, ogg
In windows and OS X

**Comment by fg-ok** [comment]
**System Details:**
    Operating System / Distro: Linux Mint 18 (4.4.0-75-generic)
    OpenShot Version: 2.3.3 from web site

Nearly the same error: Openshot closes but **after** MP3/WAV (16bit, 44kHz)/OGG is imported.
I drag the audio file on a track below the video start the playback and **after** the audio was played OpenShot closes.
CLI output and sample OGG-file attached.

**Comment by prasathkk** [comment]
I am having the same issue. Now unable to open the project itself.

**Comment by Just-Curious** [comment]
Same with version 2.3.3 on Windows 10 Pro, 64-bit.  But, I was able to drag audio files to the timeline after placing a video there first.
![20170528_openshot](https://cloud.githubusercontent.com/assets/16257232/26536200/c4b556aa-4402-11e7-8901-ba5485465934.jpg)

![20170528_video](https://cloud.githubusercontent.com/assets/16257232/26536204/ce110096-4402-11e7-99bb-9282980e6544.jpg)

**Comment by DIrkCo** [comment]
I also have this problem. Adding a sound file goes well, but as soon as the preview starts at the sound file I get the error message " Lauch.exe has stopped working".
Using:
Windows 10 64 bit Version 1607
AMD Phenom II X3 B75 3.00GHz
Memory 4.00GB

**Comment by DylanC** [comment]
Working on the v2.4 daily build. Please try the latest version.

**Comment by fg-ok** [comment]
Thanks! Working for me too
