### ISSUE TITLE
Resize of audio crashes program

### ISSUE THREAD

**Issue by wadester** [OpenShot/openshot-qt#681]
**System Details:**
* Operating System / Distro: ?  Fedora 25 x86_64
* OpenShot Version: ?  2.3.3
* _Please attach log files if crash_
properties_model:INFO Update frame to 1
properties_model:INFO updating clip properties model.
properties_model:INFO Getting properties for frame 1: OrderedDict([('alpha', {'closest_point_x': 1.0, 'max
...
readonly': False, 'type': 'int', 'points': 0})])
[wav @ 0x7f6e68000f00] max_analyze_duration reached
preview_thread:INFO LoadFile /home/wadeh/work/lin_photo/video1/ds.wav
[wav @ 0x2f43980] max_analyze_duration reached
 main_window:INFO auto_save_project
Caught signal 11 (SIGSEGV)
---- Unhandled Exception: Stack Trace ----
  /tmp/.mount_SQ4AXI/usr/bin/libopenshot.so.11 ( openshot::FFmpegReader::Close()           + 0x29a )  [0x7f6ee37dd546]
  /tmp/.mount_SQ4AXI/usr/bin/libopenshot.so.11 ( openshot::FFmpegReader::Seek(long)        + 0x5c3 )  [0x7f6ee37e2a4d]
  /tmp/.mount_SQ4AXI/usr/bin/libopenshot.so.11 ( openshot::FFmpegReader::GetFrame(long)    + 0xb41 )  [0x7f6ee37deafd]
  /tmp/.mount_SQ4AXI/usr/bin/libopenshot.so.11 ( openshot::FrameMapper::GetOrCreateFrame(long)  + 0x347 )  [0x7f6ee380a16f]
  /tmp/.mount_SQ4AXI/usr/bin/libopenshot.so.11 (                                           + 0x105fa3)  [0x7f6ee380efa3]
  /tmp/.mount_SQ4AXI/usr/bin/libgomp.so.1 (                                           + 0x834a)  [0x7f6ee11e734a]
  /lib64/libpthread.so.0         (                                           + 0x76ca)  [0x7f6eff4526ca]
  /lib64/libc.so.6               ( clone                                     + 0x5f  )  [0x7f6eff18cf7f]
---- End of Stack Trace ----
QLibraryPrivate::unload succeeded on "/tmp/.mount_SQ4AXI/usr/bin/imageformats/libqgif.so"  
QLibraryPrivate::unload succeeded on "/tmp/.mount_SQ4AXI/usr/bin/imageformats/libqico.so"  
QLibraryPrivate::unload succeeded on "/tmp/.mount_SQ4AXI/usr/bin/imageformats/libqjpeg.so"  
QLibraryPrivate::unload succeeded on "/tmp/.mount_SQ4AXI/usr/bin/imageformats/libqsvg.so"  
QLibraryPrivate::unload succeeded on "/tmp/.mount_SQ4AXI/usr/bin/platforms/libqxcb.so"  
QLibraryPrivate::unload succeeded on "Xcursor" (faked) 

**Issue Description and steps to reproduce:**
Could not use MP3 so converted to wave:  mpg123 -w ds.wav origfile.mp3
Imported file into OpenShot
Dragged to a new track
Scrolled to right, grabbed edge then tried to resize
Program crashed

**Comment by DylanC** [comment]
@wadester - I would suggest the daily build of v2.4. Its better for audio.

**Comment by DylanC** [comment]
Could not reproduce on the daily build.
