### ISSUE TITLE
Tutorial Dialog Screen on Startup broken, blocks system, can not de-select metrics

### ISSUE THREAD

**Issue by COLABORATI** [OpenShot/openshot-qt#682]
On the first start of Openshot that tutorial dialog is opening and blocking the whole system - CPU goes up and some strange behaviour occurs so that I can not select other windows, very annoying. 

Also, what is extremely annoying, that select box to disable metrics collection just does **nothing** - no matter, how I try to click that box, it is always selected. 

Only after some minutes I somehow get to the Openshot menu and can close that dialogbox by closing the project. 

This was the first minute experience with Openshot and it was extremely disappointimg - did anyone test this software before release? 

http://i.imgur.com/YSoVIEW.png

**Comment by DylanC** [comment]
Dup of #307

**Comment by DylanC** [comment]
Unable to reproduce.
