### ISSUE TITLE
No concept for multi-cam editing found neither in GUI nor in the docs

### ISSUE THREAD

**Issue by COLABORATI** [OpenShot/openshot-qt#684]
I could not find any hint about the developers of this software might have been thinking about multi-cam editing, neither in the software itself, nor in the docs or on the website. Multi-cam editing should be an important feature of any video editing software and a concept of how to do that should be envisioned by the developers.

You can find some inspiration here: 
https://www.youtube.com/watch?v=79CdYQb61qY
https://www.youtube.com/watch?v=NjpdVp11MsA

**Comment by mikelacsa** [comment]
Closing this issue to give way to #1292 that has a more detailed request.
