### ISSUE TITLE
Video play back on time line, choppy, skipping

### ISSUE THREAD

**Issue by karenbear** [OpenShot/openshot-qt#688]
todays date:5-28-17.
i have windows 10 home, 64bit.
asus AMD A10  desktop PC.
8 gigs of ram, 800 GB hard drive .
openshot video editor 2.3.3.
--------------
after i dragged 3 videos into the timeline, i hit playback to see everything play as one, its choppy and skippy.
i tried lower profile and higher ones , i also used the profile details of the file, and it is still choppy and skips alot , this happened after windows 10 update "KB4020102", it was buggy before the update, but now worse after update.

**Comment by DylanC** [comment]
@karenbear - What model of the AMD A10 do you have? Can you provide the full name?
