### ISSUE TITLE
Ability to move keyframes forward/back in time within a clip

### ISSUE THREAD

**Issue by justarandomgeek** [OpenShot/openshot-qt#689]
I'm building animations using lots of images positioned and moved around the screen. However, when I get the timing on a keyframe wrong I have to track to it, write it all down, delete it, track to the new time and recreate it by hand. It would be nice if there was a way to move the keyframes around within the clip to fine-tune animations!

**Comment by DylanC** [comment]
@justarandomgeek - I think this feature exists but I will double check.

**Comment by sjjh** [comment]
@DylanC I was just looking for the same feature and couldn't find it either (openshot 2.4.2). If it does exist, could you add some explanation to the documentation? thx!

**Comment by peanutbutterandcrackers** [comment]
I'm not sure if it does exist. However, this really would be a great addition for sure!

Hopefully we'll get enough volunteers/contributors to have this feature implemented soon enough.

**Comment by hrimhari** [comment]
This is really important. I do fade-ins and outs over a music track based on what's on the screen and if I move my images around it's not easy to manage the volume keyframes.

**Comment by frederikheld** [comment]
I was just looking for this feature as well and I'm surprised that it isn't possible to move keyframes.

The whole keyframe handling is a bit cumbersome to be honest. Selecting a keyframe needs a lot of patience unless there's another way than fiddling around with the red line until it hits the keyframe marker that I can barely see without a microscope :-P Would be nice to have keyframes explicitly displayed on the timeline below each track so that I can select one by clicking it, move it around by dragging it, etc. Similar to [how they did it in Adobe Flash](https://www.youtube.com/watch?v=UPluh8Mre-c).

**Comment by henning** [comment]
I would need that too! 

And also some way of navigating to keyframes to check/change their values, too.

**Comment by Grigor77** [comment]
This would be brilliant! I thought I was missing something having to take screenshots of my properties, deleting the keyframes, then recreating them elsewhere.

**Comment by naaraanjaa** [comment]
For sure it would be a great improvement to keyframe management. I'm moving images in sync with the music, and when I realise that the keyframe is not precisely at the right time, it would feel very natural to just move it and adjust the timing.

**Comment by BruceFast** [comment]
I really believe that keyframes deserves a properties page, or a dock.  You should be able to see a list of all keyframes in the project, you should be able to see/edit all animations that begin at a keyframe, and all animations that end at the keyframe.  You should be able to precisely adjust the keyframe in time.  You should be able to have an animation end on any future keyframe, not just "the next one".

This would be a fairly large development project, but it would make OpenShot much more useful.

**Comment by LexiTheTT** [comment]
Why doesn't this exist?

**Comment by smolkrieger** [comment]
I know this sounds like a simple feature that just about anyone could make in a pull request, but is this ever even going to be added? I don't know how complex the animation system could be, but it's been more than 6 years, and as of 3.3.0, it seems like there's still no way to move keyframes. I feel like there should also be a way to copy and paste individual keyframes?

**Comment by Colorjet3** [comment]
Still in the Enhancement queue.  No ETA.

**Comment by montezumashamas** [comment]
This is the reason I am forced to stop using OpenShot. I love the project, but editing a slightly more complex video becomes such a burden without the possibility to move keyframes freely.

**Comment by Colorjet3** [comment]
Hello @montezumashamas.  There is a v3.4.0-Release-Candidate that now has this feature in it.  The release-candidate is going through testing right now and a few issues have been identified with some other enhancements and fixes that were addressed in this version.

Go to openshot.org/download/#daily and get the latest v3.4.0-release-candidate-......

So, if you are willing to test the "keyframe" enhancement, it would be great to hear back from you to see what you think.  

Here is a test case to try and of course feel free to test further yourself with your own real life activities:

1. Download and install GitLab Pipeline: [13898](http://gitlab.openshot.org/OpenShot/openshot-qt/pipelines/13898/builds)

2. Add 2 emojis (Track 5, Position 0.0, and Track 4, Position 0.0)

3. Select both clips, right click, Animate->Entire Clip->Random

4. Observe the keyframe icons appear at the start and end of each clip.

5. Scrub the playhead a bit to observe the animation of both emojis.

6. Carefully click on the keyframe icon, and drag it towards the center of the clip, to shorten the animation. Scrub the playhead again and see the result of your shorter animation (between the 2 keyframe points)

7. Try dragging all the keyframes, and observe the results.

8. Observe no crashes, glitches, or freezes

**NOTE:** If you drag the keyframe outside the clip boundary onto the timeline and drop it, it will no longer be shown. This is a current limitation of our timeline rendering - you might have to either extend your clip to reveal the keyframe icon, or delete the keyframe in the Property editor.

**NOTE:** All keyframes that are located on the icon you drag will be moved. For example, if you have set keyframes on location_x, location_y, and rotation on the same frame #, dragging it will move all 3 of these keyframes.


Also, any additional feedback to further enhance would be appreciate it.  Most likely, anything new most likely will not make the cut but at least we can get it in the queue for additional enhancement.

**Comment by LexiTheTT** [comment]
LETS GOOOOO!!!

**Comment by Colorjet3** [comment]
> LETS GOOOOO!!!

I hope you plan on testing and providing feedback!
