### ISSUE TITLE
Idea: Exchange Layers with each other

### ISSUE THREAD

**Issue by dazzafact** [OpenShot/openshot-qt#690]
**Win 10:**
* OShot 2.3 ?

possibility to move Video Layers.
if i have an extensive layer and just confound a layer to be on top. I can't just exchange the Layers with each other. The only way is to mark the whole Layer and cut and paste it to the right position.

**Comment by peanutbutterandcrackers** [comment]
Yeah, this would be pretty neat!

**Comment by mikelacsa** [comment]
Hi!

We are in the process of closing duplicate enhancement requests to streamline our ticket handling and to serve you better. Your request was also requested by another user from #309. 

We will close your ticket but do know that we really appreciate your input and we encourage you to give us more for OpenShot's improvement.

Cheers!
