### ISSUE TITLE
openshort hangs in Hallo Screen

### ISSUE THREAD

**Issue by ghost** [OpenShot/openshot-qt#691]
**System Details:
* Operating System / Distro: xubuntu
* OpenShot Version: 2.3.3
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
All i did was start openshort then the screen appeared. No way to get rid of it.
![openshotscreenblocking](https://cloud.githubusercontent.com/assets/29057515/26572853/c99709b0-451b-11e7-94a5-85e5a0f3d760.png)

**Comment by openpianist** [comment]
just click "weiter" if you want to get an online-help or  "Lehrgang verstecken" if you want to close this window.

On my Ubuntu 17.04 system with OpenShot version 2.3.4 it works perfectly

**Comment by DylanC** [comment]
Working in current version.
