### ISSUE TITLE
Error when insert title

### ISSUE THREAD

**Issue by drizt** [OpenShot/openshot-qt#692]
**System Details:**
* Operating System / Distro: Windows 7 64-bit **Russian**
* OpenShot Version: 2.3.3

**Issue Description and steps to reproduce:**

I always get error message when adding title.

    Название файла заголовка: 1.svg is not a valid video, audio, or image file.

My system and app language is Russian. If I change app language to Australian English all works fine.

**Comment by DylanC** [comment]
@drizt - Can you attach the file here for me to test?

**Comment by drizt** [comment]
No any file. Just run Openshot with new project. Change application language to Russian, restart to apply new language settings and try add a title. See at [screenshot](http://pix.academ.info/images/img/2017/09/05/3ad3e3455d1cf21facfe92b4ee3cdad2.png).

**Comment by Gilnorian** [comment]
I'm experiencing the same issue. Win 10 Russian, English title's text, English title file name - the same error message.

**Comment by DylanC** [comment]
@drizt - Try the latest daily build.
