### ISSUE TITLE
Wrong language

### ISSUE THREAD

**Issue by drizt** [OpenShot/openshot-qt#693]
**System Details:**
* Operating System / Distro: Windows 7 64-bit **Russian**
* OpenShot Version: 2.3.3

**Issue Description and steps to reproduce:**

Russian is app language when American English is choosed in settings. No problems with others languages. Problem only with American English.

**Comment by DylanC** [comment]
Dup of #331

**Comment by DylanC** [comment]
As confirmed in #331.

> Changing interface language to American English works fine in OpenShot-v2.4.1-34-g6a9257e-59-685.

Can someone confirm this here too?

**Comment by DylanC** [comment]
Confirmed as fixed in #331.
