### ISSUE TITLE
How do I rotate a video

### ISSUE THREAD

**Issue by gocush** [OpenShot/openshot-qt#694]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

**Comment by Enfostorm** [comment]
In the properties menu there is a line which rotates the clip. If you don't see the properties panel, press Ctrl+I.

**Comment by openpianist** [comment]
you can even rotate a clip via the **Transform** feature.  (please check User Guide)
http://www.openshot.org/files/user-guide/clips.html#transform

**Comment by DylanC** [comment]
Question has been answered.

**Comment by Prid13** [comment]
> In the properties menu there is a line which rotates the clip. If you don't see the properties panel, press Ctrl+I.

![Screenshot_8955](https://user-images.githubusercontent.com/27897747/146197790-5e79be4c-6c74-4a92-98b7-3209db03acf0.png)

Can't believe how hard it was to find this information when googling. Adding a picture here for future reference (hi future googlers) :)
