### ISSUE TITLE
Contrast Slider Control Does not work properly

### ISSUE THREAD

**Issue by dancetheskies** [OpenShot/openshot-qt#695]
**System Details:**
HP Envy desktop running W10 (x-65) Home Edition, build 703 (kept fully updated with patches)

* Operating System / Distro: ?
Windows 10 (x64), fully updated with build 1703 patches.

* OpenShot Version: ?
2.3.2 and 2.3.3 latests (see above)

* _Please attach log files if crash_
N/A

**Issue Description and steps to reproduce:**
The slider control for increasing/decreasing the video's contrast does not change smoothly.  There are only 2 settings that get shown in the video preview pane.  The normal contrast show at all slider control settings from 0 up to about 85 in the slider setting, where the contrast suddenly jumps to a high setting and stays there at all highrr settings.  This has been the case for many release versions, including the nightly builds.  It's still there in the latest build OpenShot-v2.3.4

EDIT: Deleted duplicate issue description and updated Open Shot version number

**Comment by DylanC** [comment]
@dancetheskies - Does this issue exist in the latest daily build?

**Comment by dancetheskies** [comment]
Hello,

Yes, it still exists, unfortunately.  Seems like it would be a simple fix.

I also notice a long delay (like 15 to 30 seconds) frequently when simply moving the marker on the time line before I can do anything).  This is on Windows 10 (x64, latest “Fall Creators” update v1709).

**Comment by DylanC** [comment]
@dancetheskies - That's some good information. Thanks!

**Comment by DylanC** [comment]
@dancetheskies - We are working on a fix for this at the moment.

**Comment by dancetheskies** [comment]
Great, thanks.  I'll watch for it in the nightlies.

**Comment by dancetheskies** [comment]
This issue  has now been fixed in the v2.4.1 nightly build dated Nov. 23, 2017!  Thanks!

**Comment by DylanC** [comment]
@dancetheskies - Great news, thank you! :)
