### ISSUE TITLE
New audio problem on exported videos.

### ISSUE THREAD

**Issue by vales** [OpenShot/openshot-qt#696]
The OpenShot-v2.3.3-7-gca44aff-55-630-x86_64.exe version fixes the problem of the launch.exe block in inserting audio tracks on the track.

However, I detect the block of audio playback on video exported from time 2 '33'' on all projects.

* Operating System / Distro: Windows 10 16Gb ram system
* OpenShot Version: OpenShot-v2.3.3-7-gca44aff-55-630-x86_64.exe

**Comment by hubertruger** [comment]
have you tested the new 

OpenShot-v2.3.3-7-gca44aff-55-631-x86_64.exe

is this version still having the 2:33 issue

**Comment by hubertruger** [comment]
that's the latest one in the daily builds

**Comment by vales** [comment]
Yes, even the mentioned version loses audio at time 2' 33''

**Comment by vales** [comment]
60/5000
The audio block at time 2 '33'' on exported videos also on version 2.3.4

**Comment by vales** [comment]
I solved converting audio files from mp3 to ac3.

**Comment by ktecho** [comment]
Yeah, confirmed mp3 audio breaks at  2'33'' on my project too.

**Comment by hubertruger** [comment]
maybe try vales solution

"I solved converting audio files from mp3 to ac3."

**Comment by DylanC** [comment]
The 2.30 or 2 '33' issue with audio has been resolved. Please try the v2.4 daily build. Thanks.

**Comment by DylanC** [comment]
Dup of #618
