### ISSUE TITLE
open shot crash on audio import

### ISSUE THREAD

**Issue by hubertruger** [OpenShot/openshot-qt#697]
**Surface pro 2 *64 8gb ram 256gb hardrive :**

* windows 10 pro/ creators editionn(latest update)?

* OpenShot 2.3.3(download 20 minutes ago from openshot.org)

[libopenshot.zip](https://github.com/OpenShot/openshot-qt/files/1040832/libopenshot.zip)

: ?
* _Please attach log files if crash_

*open shot crashes when i import an audio into the timeline

steps:
1.open openshot
2.import audio

see the following error

![openshot error](https://cloud.githubusercontent.com/assets/16621469/26625778/d6f85b12-45fd-11e7-8123-00c9b0e6a735.jpg)
![full screenshot error](https://cloud.githubusercontent.com/assets/16621469/26625792/debb2afa-45fd-11e7-81cf-9f3661a12ce4.jpg)
*

**Comment by vales** [comment]
Try the latest daily version seems to solve at least that problem.

**Comment by Enfostorm** [comment]
You go to the downloads pages, and click on the daily builds button in the looking for a different download section

**Comment by vales** [comment]
However, the issue of the audio block at 2 '33'' time remains in the exported videos

**Comment by hubertruger** [comment]
OK vales thank you I will check on it now and wait on the 2:33 issue to be resolved

**Comment by luismgallegosc** [comment]
Issue was resolved for me in version 2.3.4

**Comment by DylanC** [comment]
Solved in the latest version.
