### ISSUE TITLE
Changing clip time (slow/fast motion) causes crash

### ISSUE THREAD

**Issue by pc1972** [OpenShot/openshot-qt#698]
**System Details:**
* Operating System / Distro: Windows 7 64 bit
* OpenShot Version: 2.3.3

**Issue Description and steps to reproduce:**
   Adding slow/fast motion to a clip causes crash.

**Problem signature:**
  Problem Event Name:	APPCRASH
  Application Name:	launch.exe
  Application Version:	0.0.0.0
  Application Timestamp:	57a98a3e
  Fault Module Name:	msvcrt.dll
  Fault Module Version:	7.0.7601.17744
  Fault Module Timestamp:	4eeb033f
  Exception Code:	c0000005
  Exception Offset:	00000000000158fa
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	b0e8
  Additional Information 2:	b0e877a73ff59ac17c64cfb1b1433710
  Additional Information 3:	60bd
  Additional Information 4:	60bd9e7d7ba0c5112273700c89b302d5

**Comment by Lucario443** [comment]
I have the same problem. But it only crashes when I try to move my playhead over it or preview it.
OS Name: Microsoft Windows 10 Home
System Type: x64-based PC
Processor: Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz, 3301 Mhz, 4 Core(s), 4 Logical Processor(s)
Installed Physical Memory (RAM): 8.00 GB
Display: NVIDIA GeForce GTX 950 (Drivers up to date)

OpenShot (2.3.4)
I thought updating from 2.3.1 would fix this issue, but I was wrong.

**Comment by DylanC** [comment]
Confirmed as fixed in #588
