### ISSUE TITLE
Increasing the duration of an image clip

### ISSUE THREAD

**Issue by tmladek** [OpenShot/openshot-qt#7]
Is there a technical reason for not allowing pictures to be longer on the timeline than 5 minutes (300 seconds)?

If not, could it please be increased?

I'd very much like to use openshot in order to create videos to accompany recordings, which are by their nature pretty light on the visual side, and it's not unusual to have a static image as background for more than 5 minutes.

Thank you!

**Comment by jonoomph** [comment]
Thanks! This can be changed in the preferences between 0 to 10000. Closing issue. =)
