### ISSUE TITLE
Right Click (not pressing ctrl)

### ISSUE THREAD

**Issue by jGRite** [OpenShot/openshot-qt#701]
**AMD FX 965, 8GB Ram**
* Ubuntu 14.04 LTS 64bit * ?
* OpenShot Version: 2.3.3?
*no crash*

**Issue Description and steps to reproduce:**
If I'm using it like normal and I right click a clip and edit it in someway, the last thing I had selected isn't unselected. It shouldn't work this way. The right click should still be treated like a left click where if I left click it doesn't hold the last item I selected. This should only happen if I'm pressing ctrl. This happens if I only right click and item.

**Comment by DylanC** [comment]
@jGRite - I will find out if it should be working this way.

**Comment by DylanC** [comment]
@peanutbutterandcrackers - What do you think of this?

**Comment by peanutbutterandcrackers** [comment]
To be honest I don't fully understand what is being said. Perhaps @jGRite would like to post a few screenshots or something? That would help us help you, good sir!
