### ISSUE TITLE
Title showing black bar

### ISSUE THREAD

**Issue by IdealSchreiber** [OpenShot/openshot-qt#703]
**System Details:**
* Operating System / Windows 10
* OpenShot Version: 2.3.4

Had an existing OpenShot project, wich i opened with the new 2.3.4 (Just upgraded from last version)
Some titles, not all in project, has this litle black bar showing. The error is not visible in the advanced editor, only in preview and exportet files.
The black bar is shown at same place no matter where the title is placed.

![title_bug](https://cloud.githubusercontent.com/assets/29142344/26721566/9925f688-478c-11e7-8b75-6e4e63dd2acc.png)

**Comment by IdealSchreiber** [comment]
Here is a screenshot from the title preview.

![2](https://cloud.githubusercontent.com/assets/29142344/26815588/74176738-4a8d-11e7-99b9-66a9dccaaff9.png)

**Comment by DylanC** [comment]
@IdealSchreiber - Does this show in v2.4.1?

**Comment by IdealSchreiber** [comment]
@DylanC it has not happend for me since then, so i really dont know what went wrong. I deleted the old projects and redid most of them because of the bar showing. I have some other videos i have to edit later, ill return here if the error shows up again.

**Comment by DylanC** [comment]
@IdealSchreiber - No problem. Closing this issue for now.
