### ISSUE TITLE
Feature Request: Insert Clip

### ISSUE THREAD

**Issue by Marchhill** [OpenShot/openshot-qt#704]
Currently, if you want to add a video before another, you have to manually shift all of the videos rightways which could take a very long time in a large project. Would it be possible to implement a feature that does this automatically. PS. Thankyou for sharing your great software!

**Comment by drmoravia** [comment]
See this [old request for the same thing](https://bugs.launchpad.net/openshot/+bug/801342)

Related is the need to be able to shift left when deleting a clip.

* That site is at the top of the list in a Bing search for "OpenShot bugs", so I didn't know there was another site [this one] until I used the "report bug" menu option to get here.

**Comment by fabien7474** [comment]
I would help dramatically to have this feature
