### ISSUE TITLE
Mp3 file crash

### ISSUE THREAD

**Issue by riki123riki** [OpenShot/openshot-qt#705]
**System Details:**
* Operating System / Distro: ? Windows 10
* OpenShot Version: ? 2.3.4

**Issue Description and steps to reproduce:** Is there anyone facing the same issue where the mp3 file will not play properly after minute 2:33?

**Comment by 109Natsu** [comment]
Yes, I am having the same problem and I hope this gets fixed soon

**Comment by vales** [comment]
I solved converting audio files from mp3 to ac3.

**Comment by riki123riki** [comment]
I tried ac3 and it still isn't working.

**Comment by sabarnett** [comment]
I have the same problem too.

**Comment by DylanC** [comment]
This issue has been resolved in the v2.4 daily build. Please try the latest version. Thanks.
