### ISSUE TITLE
Open source AppImage build files

### ISSUE THREAD

**Issue by philippgille** [OpenShot/openshot-qt#706]
I was looking into AppImage and stumbled upon this project. I wanted to check out how you build it, but found out that for example the `AppRun` file necessary for building the AppImage isn't part of this repository.

Instead, in `installer/build-server.py` there's this line: `shutil.copyfile("/home/jonathan/apps/AppImageKit/AppRun", app_run_path)`.

If I'm not mistaken this means that this open source project uses closed source files to build its binary releases, potentially containing code that can't be examined by the open source community?

It would be nice if you could include all files used for building binary releases in this repository.

**Comment by DylanC** [comment]
@philippgille - Perhaps. I can check this out for you.

**Comment by DylanC** [comment]
@philippgille - I will suggest this to the team. Thanks.

**Comment by philippgille** [comment]
@DylanC: Hi, what did the team say?
