### ISSUE TITLE
Animated titles+Blender

### ISSUE THREAD

**Issue by alainbadan** [OpenShot/openshot-qt#707]
**System Details:**
* Operating System / Distro: ? windows 10
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

Hello,
Each time I want to create an animated title a window open with a message about Blender. Please see screenshot.
Thank you.
Best regards.
Alain Badan
![blender](https://cloud.githubusercontent.com/assets/11753084/26760198/c4b3e256-4912-11e7-9633-0a39f71d125e.png)

**Comment by eM-Ce** [comment]
Hi,
you probably don't have blender installed on your computer or it is installed in a different directory.
Path to blender should point to blender executable (file "blender.exe").
Check please if you have blender installed and change the path in prefferences on General tab to the full path of blender.exe (it should be something like this: "C:\Program Files\Blender Foundation\Blender\blender.exe")

**Comment by BumbleGrum** [comment]
I had the same issue! The solution is to add the executable name in the preferences dialog! I.e.
C:\Program Files\Blender Foundation\Blender\**Blender.exe**

**Comment by Kooskooskoos** [comment]
Hi
I have the same issue.Suggestion of BumblGrum did not work :-)
See further 
![cut-4](https://user-images.githubusercontent.com/30216656/28250195-8e0e1baa-6a63-11e7-94c7-addb0241b4bc.JPG)
![cut-3](https://user-images.githubusercontent.com/30216656/28250193-8e0b706c-6a63-11e7-8b7f-680389436ead.JPG)
![cut-2](https://user-images.githubusercontent.com/30216656/28250194-8e0bfa64-6a63-11e7-8685-1e7930536cbe.JPG)
![cut-1](https://user-images.githubusercontent.com/30216656/28250196-8e0e5df4-6a63-11e7-8ddb-d9270a96f241.JPG)
Help is apreciated.

**Comment by PASTJL** [comment]
The workarrou d for Windows is to add the path of Blender in the system variable PATH and put only blender in the configuration form of openshot

**Comment by bjoern89** [comment]
What on earth does that even mean Pastjl? 

I have the same issue and I'm confused to bits. I have this working on my work computer.

**Comment by DylanC** [comment]
You must have Blender installed on your PC and have the path set correctly as users have described above.
