### ISSUE TITLE
App crashes when you put effects onto a video

### ISSUE THREAD

**Issue by Theerockzz** [OpenShot/openshot-qt#708]
**System Details:**
* Windows 10 pro 64 bit
* OpenShot Version: 2.3 ?
* _I couldn't find a log file_

**Whenever I try to add effects from the right menu, the software crashes. This also happens with some other commands.**

**Comment by DylanC** [comment]
@Theerockzz - I could not reproduce this issue. Please add more detail to bug reports and give exactly how to produce it.
