### ISSUE TITLE
enhancements

### ISSUE THREAD

**Issue by openpianist** [OpenShot/openshot-qt#709]
**System Details:** 
* Operating System / Distro: ? Ubuntu17.04
* OpenShot Version: ? 2.3.4
* _Please attach log files if crash_
crashes regularly.. ;-)

**Issue Description and steps to reproduce:**
Hi,
fist of all.
THANK YOU A MILLION.
This is an awesome piece of software. I love it !!

I would like to (maybe) help a little bit by giving some feedback and some recommendations.

1) on the website, please add a "wish list for new features" , than you can do a Pareto to see which additional features users would like (need) the most.
My experience is that often with very little enhancements, you can boost the usability of an application.

2) Timeline zoom: It would be nice, if this could be zoomed out (in) more.  independently vertically and horizontally. Sometimes it is useful so see more tracks. And sometimes it is nicer to the the details better.

3) disable track: it would be nice to make a track invisible in the preview. This would come very handy while correcting other overlaying layers (tracks)

4) Property Window higher it would be nice, if this could be pulled down to the whole hight of the main window.  Sometimes it is handy to see more attributes...  It is understood that this will cost some room of the timeline window.

5) Property window scroll bar freeze
When changing to an other clip, so it is not jumping all the time.. (at least clips of the same kind, like videos, photos. )

Transform feature: 
the power of this feature is incredible.. (But it takes a while for a newbe to figure this out.)

6) Transform: Clip not centered: While pulling on the blue holding points, it would be nice, if only the pulled side would be changed, in other words, the clip would not be centered.  Or at least if there is an option to keep the clip centered or variable
 
7) Transformation: Holding points out of range: When the blue holding points are out of the preview window, it is not possible to catch them again. It would be nice, in case a clip is out of the viewable area, there would be alternative holding points.

8) Transformation: Reset Marker:  In case a user was to "creative" with the markers, (happened to me several times) it would be nice if there were an option in the right mouse menu (and property window) to reset markers. or a content menu when you click on a marker to reset/ erase it.

9) Effects: Blur Selection out: There is often a need to blue / pixel areas (faces, number plates, unwanted areas) of a clip out. It would be great if there would be an Effect "Blue Selected Area out" .   A round / rectangle. in other words, a combination of the blur effect on a mask.  (that s actually how i did my work around with Gimp. (creating a fading mask, and blur areas out)
In combination with the transformation effect, it will be easy to "follow" a blurd out face on the timeline.

10) Clip:  Drop Down Window: Add new feature "Make Clip invisible" (same idea like point 3, just for a clip)

edit:
11) Open File - Preview:  A preview window (like in Gimp) at the Open File Dialog would be great.

12) cut or add time to the timeline:  sometimes you want to add a whole sequence into an exiting project.  This can be done by select all the clips on the right side of the place you want to add more time and move them all further to the right.   It would be nice if you could right click and select a feature "insert time" than a value in seconds...

13) cropping (dimention, not lenght) of a clip.  It s often important to crop a picture or a video shot (i.e. to cut the borders with not important information. Currently it can be done by putting a mask over it and zooming the clip adequately. Nicer would be to crop the clip directly..  (maybe this essential feature exists already, and I just have not figured it out.. (it is my first day with OpenShot))

These were my quick first impressions.

Thanks again for this awesome piece of work you did
- O.

**Comment by DylanC** [comment]
@openpianist - Thanks for this excellent feedback. Full of enhancements that sound great!

**Comment by peanutbutterandcrackers** [comment]
@openpianist - your suggestion of having independent vertical and horizontal zoom level's on the time line is my favorite. It just seems that we as a community lack enthusiastic programmers to add new features, and Mr. Thomas is all by himself for now. But yeah, great feature request! 👍
