### ISSUE TITLE
Small visual issue with effect button.

### ISSUE THREAD

**Issue by firew4lker** [OpenShot/openshot-qt#71]
When applying an effect to a small piece of video, the effect button barely fits. See the attached image, witch is on full zoom. On smaller zoom it is even worse.

http://i.imgur.com/zAFOdec.png

**Comment by jarlarntzen** [comment]
:+1:

**Comment by jonoomph** [comment]
Thanks for the suggestions. I just modified the timeline to always show the effects container on hover, regardless how small the clip is. I also moved some tooltips to not cover the effects, title, or menu. Check it out on our latest daily build.

**Comment by firew4lker** [comment]
Nice!!!
