### ISSUE TITLE
Autosave appears to cause program crash if project is not on 'C:'

### ISSUE THREAD

**Issue by Filip-Michalowski** [OpenShot/openshot-qt#710]
**System Details:**
* Operating System / Distro: Windows 7 Home Premium 64-bit SP1
* OpenShot Version: 2.3.3-2.3.4

**Issue Description and steps to reproduce:**

OpenShot appears to fatally crash (without error message) when autosave occurs if the project is on a mount other than 'C:'.

**Steps to reproduce:**

1. Enable autosave or leave it as it is on fresh install.
1. Create or open a project that is on mount other than 'C:'.
2. Do some work until autosave interval is reached.
2. When autosave is attempted, the window crashes silently - UI freezes, CPU usage remains at 0%, it takes some time before Windows marks the window as crashed.

While I haven't done a "proper" repro, I am confident this is the case. The crash occured to me every time I tried to use OpenShot (~20 times since 25th May 2017) quite early after opening a project (which in retrospecitve perfectly matched default 3:00 autosave interval) and the crash **did not** occur the one time I used the program after disabling the autosave.

Plus, after the last crash, the last lines of `openshot-qt.log` were these: (paths edited for privacy, preserved case and special characters)

    properties_model:INFO Getting properties for frame 1: [blah blah blah]
    project_data:ERROR Error while converting absolute paths to relative paths: path is on mount 'C:', start on mount 'G:'
     main_window:INFO Saved project G:\My path\10 - SomETHING project\ALLCAPS\mp4 cutting board\true stories.osp
    project_data:ERROR Error while converting absolute paths to relative paths: path is on mount 'C:', start on mount 'G:'
     main_window:INFO Saved project G:\My path\10 - SomETHING project\ALLCAPS\mp4 cutting board\true stories.osp
    project_data:ERROR Error while converting absolute paths to relative paths: path is on mount 'C:', start on mount 'G:'
     main_window:INFO Saved project G:\My path\10 - SomETHING project\ALLCAPS\mp4 cutting board\true stories.osp
    project_data:ERROR Error while converting absolute paths to relative paths: path is on mount 'C:', start on mount 'G:'
     main_window:INFO Saved project G:\My path\10 - SomETHING project\ALLCAPS\mp4 cutting board\true stories.osp
        main_window:INFO Saved project G:\My path\10 - SomETHING project\ALLCAPS\mp4 cutting board\true stories.osp
         ui_util:WARNING Icon theme media-playback-pause not found. Will use backup icon.
    preview_thread:INFO onModeChanged
         ui_util:WARNING Icon theme media-playback-start not found. Will use backup icon.
    properties_model:INFO Update frame to 31
    properties_model:INFO updating clip properties model.
    properties_model:INFO Getting properties for frame 31: [blah blah blah]

I am just surprised it wasn't reported earlier.

**Comment by IdealSchreiber** [comment]
Not sure that c:\ i your problem, my projects are saved at my P:\ and it autosaves with no problems. (Win10 v/ 2.3.49)

-Schreiber

**Comment by Filip-Michalowski** [comment]
Thanks for the reply. You seem to be right - after further use, OpenShot crashes when trying to handle a small (3:57) MP3 file in a 3-layer project spanning 1:30 running time 4096MB cache limit.

My initial hunch was wrong, the log doesn't seem to show any errors for the new crash and I don't have time right now to investigate this further and produce any actually useful information. Therefore I'm closing this as no-repro, so it won't clutter your open issues.
