### ISSUE TITLE
Access to Openshot forum+access to MSI-installer or silent install code

### ISSUE THREAD

**Issue by bjoern89** [OpenShot/openshot-qt#711]
Greeting. Sorry for using Github to reach out. 

I've tried to get the activation code from your forum 5 times now, I never receive it either in mail or spam-filter? Not sure if you're having some issues?

Secondly I need access to either an MSI-installer or preferably the silent install code so I can install the .exe over Sccm.

**Comment by macxcool** [comment]
/? gets you the install switches. It's always a good thing to check with Windows software.
Just open a command prompt (or powershell) in the folder containing the installer and run the installer with /? after it.
OpenShot-v2.3.4-x86_64.exe /?

I don't know if this is the case with this installer, but often installers will place unpacked MSIs and such in your local user profiles under AppData\Local\Temp. You can look there while the installer is running.

**Comment by DylanC** [comment]
Closing due to not being a software bug report. Seems to be answered too.
