### ISSUE TITLE
Feature Request - Chroma Key

### ISSUE THREAD

**Issue by juninhosvmaggot** [OpenShot/openshot-qt#713]
**System Details:**
* Operating System / Distro: Linux - Arch Linux
* OpenShot Version: Openshot 2.3.3
* _Please attach log files if crash_

A nice idea would be to add tools well used as the fisheye effect the Chroma Key and some more used for video editing, the project itself is very nice its interface is very friendly and easy to use I liked it so much could be richer in Effects, I already used it before and in an earlier version it was exclente I was only doing the issues in it.

**Comment by peanutbutterandcrackers** [comment]
The chroma key effect works really well on OoenShot v2.4.1 https://youtu.be/2sushecqMs4 and a lot of the effects from 1.x series are currently being ported into series 2.x. Plus, plans for an effect framework is also there. So, we should soon have a plethora of video effects. Please do continue to support OpenShot. :)

**Comment by DylanC** [comment]
Since Chroma key is in Openshot v2 we can close this.
