### ISSUE TITLE
preview glitching on project with 50 images and one mp3 (old version 1.4.3 works fine)

### ISSUE THREAD

**Issue by gonerodes** [OpenShot/openshot-qt#716]
I have a i3-5010U / 8Gb ram / samsung850 SSD / Ubuntu 16

I am trying to create a simple image slideshow video from 50 images (3224x1836). I've created 14 channels, just to group the images into scences e.g. 1st scene: 5 images / 2nd scene : 8 images .. e.t.c.  There is only one song involved in separate channel. 

When previewing, It freezes the song on each image change (for some milliseconds), and there are no effects/transitions involved. I've tried to increase mem cache to 2Gb (+restart), but the same.

The strange thing is that the default version of ubuntu (1.4.3) does not have this behaviour, with the same project. Only version 2.3.4 (downloaded from site). 

What made me shift to 2.3.4 was that on 1.4.3 clicking play or moving the current position(after a change) was taking 7-8 seconds, but the preview was working fine.

**Comment by gonerodes** [comment]
My bad. 
Cache fixes the problem. I did not realize that for caching it needs to preview first for one time.
I would say (as a feature) an auto-cache option could be useful.

**Comment by DylanC** [comment]
No problem. I will close this issue for now. Thanks.
