### ISSUE TITLE
Title changes not reflected in timeline until restart

### ISSUE THREAD

**Issue by ktecho** [OpenShot/openshot-qt#718]
* Operating System:  Windows 10 x64
* OpenShot Version:  2.3.4

**Issue Description and steps to reproduce:**

1- Create a title with text.
2- Insert the title in the timeline.
3- Change words in the title.
4- The title in the timeline don't reflect the changes, and neither are in the video preview window.
5- If I restart OpenShot, the changes are reflected in the timeline.

**Comment by N3WWN** [comment]
I'm using Fedora 25 (Linux), but when I change the title, I do a save and then Open Recent and select the same project.  That refreshes the titles and retains the frame in the preview window so you can see changes "immediately".  The play-head resets to the 1st frame, but the preview window frame is where the play-head was.

Not sure if that'll help or not, or if that works with Windows, but that's what I've been doing.

**Comment by ktecho** [comment]
That seems useful. Thanks!

**Comment by DylanC** [comment]
@ktecho @N3WWN - Is this still an issue in newer versions for ye guys?

**Comment by ktecho** [comment]
I've not used OpenShot recently, so I can't comment on this, sorry.



2017-11-10 10:49 GMT+01:00 DylanC <notifications@github.com>:

**Comment by N3WWN** [comment]
Hi @DylanC !

I just tested this with 2.4.1 and the behavior appears to be better than before, but still not perfect.   If any portion of the title is cached, the preview continues to show the outdated, cached version.  Uncached portions of the timeline render with the proper updates.  This can cause unexpected results.

For instance:

- Create a new project and add a short video (say, 25s long) on track 3.
- Create a simple title and place it somewhere in the middle of the video on track 4.
- Click to move the current position of the pointer to the middle of the title, then click play for a few seconds in the preview window, leaving at least a few seconds unplayed at the end of the title.
- Now, edit the title (I just changed the text).
- Click to move the current position of the pointer to before the title and click play.
- Watching the preview window, you will see the uncached portions (start and end) of the title render properly, but the middle part, which was cached before the edit, still displayed the previously cached content.

Perhaps the editing of the title can invalidate the cache for the portion of the timeline that the title covers?

Also, I often generate images that are included in my videos by use of external scripts or apps (like GIMP).  Could OpenShot check the last modified timestamp of all project files to see which ones need to have their cached data invalidated?  This would probably need to be done each time the cache data is created or read.

Let me know if you would like me to generate any same projects or attempt to capture video of the issue.

Thanks!

**Comment by DylanC** [comment]
@N3WWN  Sounds like a good idea. I'll mark this as a bug so we remember to work on it.

**Comment by embeh** [comment]
Same problem here on Windows.

**Comment by mikelacsa** [comment]
Hey guys! I just tested this with my ver 2.4.4 and it seems to work OK.

https://youtu.be/YULO1lyWDfI

Is this still happening with yours?

**Comment by ferdnyc** [comment]
@mikelacsa This was definitely fixed in 2.4.3, I think (or maybe even earlier?), thanks for catching that. Closing.
