### ISSUE TITLE
Copy Video Projects from One Computer to an Other 

### ISSUE THREAD

**Issue by quelo1972** [OpenShot/openshot-qt#719]
**System Details:** Intel(R) i5-4460 CPU @ 3.20GHz 3.20 GHz 16 GB RAM
* Operating System / Distro: ? Windows 10 64Bit
* OpenShot Version: ? 2.3.4
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
How can I Copy Video Projects from One Computer to an Other?

**Comment by DylanC** [comment]
Save the project file inside the folder with all the project source files. Zip up the folder and copy to the new PC.
