### ISSUE TITLE
Video Capture UI

### ISSUE THREAD

**Issue by nwgat** [OpenShot/openshot-qt#72]
would be nice to have a simple dialog that uses ffmpeg built-in capture support, one window that shows the video input and a record and stop buttons

for windows (dshow)
https://www.ffmpeg.org/ffmpeg-devices.html#Examples-2
https://trac.ffmpeg.org/wiki/DirectShow

for linux (video4linux2)
https://www.ffmpeg.org/ffmpeg-devices.html#video4linux2_002c-v4l2

**Comment by nwgat** [comment]
currently i use something like
`ffmpeg -f dshow -i video="Hauppauge Cx23100 Video Capture":audio="Analog Audio In (Hauppauge USB-Live2)" -c:v huffyuv -c:a flac out.avi`

**Comment by nwgat** [comment]
might want to add a DV capture support too

**Comment by dsalo** [comment]
Considering OpenShot as a replacement for the horrible software lash-up on my old-media-rescue platform... and this feature is exactly what I'd need to ditch everything else forever. Adding my voice to this enhancement request. 👍

**Comment by kaniggl** [comment]
+1 for dv capture support

**Comment by peanutbutterandcrackers** [comment]
Also, an esteemed friend recommends [OBS Studio](https://obsproject.com/) for video capture...
