### ISSUE TITLE
Feature Request - Automatic Updates

### ISSUE THREAD

**Issue by emilict** [OpenShot/openshot-qt#720]
Hi,

Congratulations for Openshot!! :-D

One Request, Automatic Updates or a notification of new version. 

Now I think that the only way to update is montitoring the site of www.openshot.org, manually uninstall and donwload the new version to install.

Thanks a lot! :-)

**Comment by ferdnyc** [comment]
It's worth pointing out that the reason for closing this is: It exists, in the form of a toolbar icon that appears when there's a newer version detected. The check is made at application startup.

(OpenShot releases fairly infrequently, so it can be several months to almost a year between appearances of that icon. It also obviously requires that OpenShot has been allowed to access the internet, on systems where that's applicable.)
