### ISSUE TITLE
No audio on preview

### ISSUE THREAD

**Issue by mostrador** [OpenShot/openshot-qt#721]
Operating System: Windows 10 64bit
OpenShot Version: 2.3.4
When I preview a video file, I hear no sound. I've tried separating the audio track and changing the Enable Audio setting from -1 to 0 to 1 back to -1. 
Once I export the file, I hear audio just fine. I need it on the preview, though.
Thanks!

**Comment by sfeger** [comment]
Was this ever resolved?  I'm having the same issue right now. 

Thanks

**Comment by mostrador** [comment]
Nope. Uninstalled the program and moved on...
