### ISSUE TITLE
music crash at 02:32

### ISSUE THREAD

**Issue by Roeldezot** [OpenShot/openshot-qt#723]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

When I edit my music crashes at 02:32 and stops after that with the sound... The clip itself and the other sounds from the edit still work after 02:32 but the sound stops...

**Comment by fabrixx** [comment]
i have similar problem. After exportation some audio & video parts missing apparently randomly

**Comment by sphyrth** [comment]
Similar issue here. My work-around is that I cut my audio (mp3) into parts. 2:30 each in length.
Next is I join them like a jigsaw puzzle.

**Comment by DylanC** [comment]
Dup of #618

**Comment by DylanC** [comment]
I have been notified this has been fixed in the latest daily build. Please try it out.

**Comment by DylanC** [comment]
This is resolved in the latest daily build:
![solved](https://user-images.githubusercontent.com/4488048/31321108-155f4970-ac78-11e7-8783-0439def02c0e.png)
