### ISSUE TITLE
Webpage: User Guide cut off with Firefox web browser

### ISSUE THREAD

**Issue by openpianist** [OpenShot/openshot-qt#724]
**System Details:**
* Operating System / Distro: ? Ubuntu 17.04
* OpenShot Version: ?  irrelevant ;-)  /  Firefox Ubuntu 53.0.3 (64-bit)
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
The Users Guide at the webpage is not completely visible with Firefox.
It is cut off at the bottom and the "Next" button is not visible.

It works with the Chromium Browser,

- O.

**Comment by openpianist** [comment]
Operating System / Distro: ? Mac OS Sierra 10.12.5
    OpenShot Version: ? irrelevant ;-) / Firefox for Mac 53.0.3 (64bit)

A complete display of the user guide does not work on Firefox for Mac neither.
The guide is cut off, the next buttons are not visible
http://openshot.org/user-guide/

The User Guide in an external window works like a charm. (on Ubuntu as well)
http://openshot.org/static/files/user-guide/index.html

**Comment by peanutbutterandcrackers** [comment]
@openpianist - does the issue still persist?

@ferdnyc - I think here is another issue you can help close!

**Comment by peanutbutterandcrackers** [comment]
@ferdnyc - Oh... I see.

@DylanC - I think we need to get @jonoomph to see this bug report.

**Comment by DylanC** [comment]
@openpianist - Just to let you know @ferdnyc has put in a fix for this. Thanks for the report.

**Comment by ferdnyc** [comment]
Agreed, I'm the _real_ hero here. 😉

**Comment by peanutbutterandcrackers** [comment]
Haha. Yeah. lol :smile:
