### ISSUE TITLE
Ubuntu 15.10 - Today update (9 Feb) cannot be performed and broke apt

### ISSUE THREAD

**Issue by gmellini** [OpenShot/openshot-qt#73]
This morning (09:00 AM UTC+2 - Italy) update has some problem.

This is the command line output of apt-upgrade command (in italian)

[...]
I seguenti pacchetti NUOVI saranno installati:
  **libopenshot7**
0 aggiornati, 1 installati, 0 da rimuovere e 3 non aggiornati.
2 non completamente installati o rimossi.
È necessario scaricare 0 B/253 kB di archivi.
Dopo quest'operazione, verranno occupati 844 kB di spazio su disco.
Continuare? [S/n] s
(Lettura del database... 477914 file e directory attualmente installati.)
Preparativi per estrarre .../libopenshot7_0.1.0+0+506+95+201602090554~ubuntu15.10.1_amd64.deb...
Estrazione di libopenshot7:amd64 (0.1.0+0+506+95+201602090554~ubuntu15.10.1)...
**dpkg: errore nell'elaborare l'archivio**  /var/cache/apt/archives/libopenshot7_0.1.0+0+506+95+201602090554~ubuntu15.10.1_amd64.deb (--unpack):
 tentata sovrascrittura di "/usr/lib/x86_64-linux-gnu/libopenshot.so.0.1.0" presente anche nel pacchetto libopenshot5:amd64 0.1.0+0+506+94+201602090538~ubuntu15.10.1
dpkg-deb: errore: il sottoprocesso paste è stato terminato dal segnale (Pipe interrotta)
Si sono verificati degli errori nell'elaborazione:
 /var/cache/apt/archives/libopenshot7_0.1.0+0+506+95+201602090554~ubuntu15.10.1_amd64.deb
E: **Sub-process /usr/bin/dpkg returned an error code (1)**
gmellini@jellyfish:$ 

libopenshot7 cannot be installed and with this problem I cannot install/upgrade anything else on my system.

Please let me know if you need more information
Giovanni

**Comment by lundmar** [comment]
libopenshot5 and libopenshot7 contains conflicting files which cause this issue.

It can be resolved by removing and then reinstalling like so:

sudo apt-get remove -f libopenshot5 python3-openshot openshot-qt
sudo apt-get install openshot-qt

**Comment by gmellini** [comment]
Ok I can confirm that commands fixed the problem.
Tks a lot
Giovanni

**Comment by jonoomph** [comment]
Sorry about that. Yes, libopenshot5 needs to be removed first. I might need to add these previous versions to the Debian config... so it knows there is a conflict, and will prompt the user to remove them.

**Comment by jonoomph** [comment]
Okay, I've added in a "Replace:" section in the PPA Debian scripts, which should prevent this in the future. Thanks!
