### ISSUE TITLE
Can not generate 4:3 format

### ISSUE THREAD

**Issue by openpianist** [OpenShot/openshot-qt#731]
**System Details:**
* Operating System / Distro: Ubuntu 17.04
* OpenShot Version: 2.3.4

I m not able to generate a 4:3 format.
Changing the profile to any 4:3 format like "384*288 4:3 PAL" or "768*576 4:3 PAL" still leave me with a 16:8 format in the preview window.

After exporting, I receive a file in the format 768*576 but with black bars on top and bottom

- O..

**Comment by Comment-McCommentface** [comment]
I managed to fix the ratio of a 16:9 video file which contained 4:3 video in OpenShot 2.4.0 on Windows 10.

With the video in the timeline, right click and select properties. On the new window that opens, look for Scale X and set it to 1.33 (4:3 percentage). Do this to Scale Y also. Now you can export video with a 4:3 profile and everything should work out.

I had the same problem where the black bars were on the left and right of the video before editing. Then, exporting with only Scale X  to 1.33 left me with top and bottom bars - just like you said. After setting Scale Y to 1.33 the preview did cut off the top and bottom, but exporting to a 4:3 profile ended up showing what the preview cut off.

As a side note, on the export video menu, I went to advanced->profile and chose the VGA NTSC (640x480) profile but edited the width to 1024 and height to 768 along with the aspect ratio settings of 4 and 3 respectively. I left the rest as default. Also the video file I was editing was a screen capture which had 1376x776 dimensions. Setting up all the 4:3 settings didn't really mess with the end result even though the screen capture added extra pixels, in my opinion.

![export_menu](https://user-images.githubusercontent.com/32110215/30613122-f1302b64-9d54-11e7-89cd-e3cbed326402.png)

**Comment by peanutbutterandcrackers** [comment]
Does this issue still persist with the latest version (v 2.4.1) of OpenShot?

**Comment by rzr** [comment]
Thx for the tip scaling X to 1.3 before export at 4/3 ratio worked for me

**Comment by Spottedfeather** [comment]
> Thx for the tip scaling X to 1.3 before export at 4/3 ratio worked for me

didn't work for me. It just made the video squished in on the sides.

**Comment by rzr** [comment]
Here is the result, which looks correct to me:
https://peertube.debian.social/videos/watch/55582fc3-ab7a-47c2-8927-b0b82aac3044#nuttx-ieee-wf-iot-2021-rzr
