### ISSUE TITLE
Feature request: split timeline shortcut

### ISSUE THREAD

**Issue by kaleda-ubnt** [OpenShot/openshot-qt#732]
**System Details:** any
* Operating System / Distro: amy
* OpenShot Version: v2.3.x
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

You have to select scissors and split scene with mouse.
It is much easier to find cut point using left/right keys, and when you have found cut point to use shortcut to actually split scene at the cursor.
V1.4.x used to have "C" shortcut
(I remmember reporting same bug years ago, and that shortcut was added)

**Comment by eM-Ce** [comment]
Hi,
there is such a shortcut. By default it is: Ctrl+K
It splits clips on all tracks and keep both sides.
You can also find it in the context menu (right click on the clip with cursor): Slice -> Keep both sides
When selected from context menu, it splits just that clip, on which was the menu activated.

**Comment by openpianist** [comment]
Hi,
you are right, it s CTRL+K
In the preference / keyboard section it says: CTRL+X  (which is wrong)

- O,

**Comment by DylanC** [comment]
@kaleda-ubnt - This shortcut already exists as stated above by others.
