### ISSUE TITLE
2.3.1 on xubuntu 16.04 crash and weird remove clip effect

### ISSUE THREAD

**Issue by shadowvzs** [OpenShot/openshot-qt#734]
**System Details: triple core amd, 10gb ddr3 ram**
* Operating System / Distro: Chaletos 16.04 (based on xubuntu 16.04)
* OpenShot Version: 2.3.1
* Issue Description and steps to reproduce:: alot instable comapred with old version, 
example: i split a mp4 video into 2 piece and if i remove a clip from 2 then both will be removed, or if split into 3 piece a video and i remove last video then its remove first clip too when i removed the 3rd - this randomly happened but enough often
sometimes suddenly crashed when i splited/removed clips (and was only few cuts, in older version its happened when a big video was cutted/splited more than 200-300 time)

**Comment by shadowvzs** [comment]
also if i move a piece from a track to another then sometimes crash, sometimes fade effect not applyed at all and other problems.

not bug but a bit messed the video length bar, harder to select on bar a scene

**Comment by jdwilliam1971** [comment]
This is a regularly recurring issue on OpenSuse Leap 42.2 Plasma 5 with every version of Openshot 2.##.  The only way to avoid the crash is to save after every edit and this is not always a solution. Easy to see crash coming because the preview frame freezes even though the timeline it is still possible to click on the timeline in other places.

**Comment by shadowvzs** [comment]
i use ChaletOs what is based on xubuntu how i write in 1st post, not reletad with plasma, neither opensuse...

**Comment by DavidButterfield** [comment]
> i split a mp4 video into 2 piece and if i remove a clip from 2 then both will be removed, or if split into 3 piece a video and i remove last video then its remove first clip too when i removed the 3rd

This sort of thing was happening to me... I figured out that when I right-click on one of the clips in the Track timeline to select it and expose the popup menu, if some other clips were already selected, it leaves them selected.  So RightClick -> RemoveClip will remove not only the clip you RightClicked on, but also any random other clip that happened to be selected (visible or not) when you did the RightClick.

**Comment by DylanC** [comment]
@shadowvzs - Does this happen on v2.4.1?

**Comment by shadowvzs** [comment]
i don't know because when i installed the 2.3.1 was the newest stable, but also the most problematic so i allways stayed with the old 1.4.3 version what closer to bugfree
