### ISSUE TITLE
Tutorial resizes window

### ISSUE THREAD

**Issue by kentfredric** [OpenShot/openshot-qt#736]
I've just installed OpenShot, and the tutorial is running.

Naturally, the window doesn't fill my screen, so I maximise it.

However, every time the tutorial menu appears or gains focus, the window de-maximises.

Please no. Stop

- Windows 10

**Comment by kentfredric** [comment]
Demo Video On Youtube.
[![Demonstration](https://img.youtube.com/vi/QOw7G9xIVak/0.jpg)](https://www.youtube.com/watch?v=QOw7G9xIVak)

**Comment by Johann-Tree** [comment]
Same on Linux (Ubuntu 15.04.02) , very annoying,

**Comment by DylanC** [comment]
Dup of #307

**Comment by peanutbutterandcrackers** [comment]
Hey there, a fix to this issue was just merged into the source tree and is ready for testing. Could you please try out the [latest daily builds](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914) and see if this has been resolved? Thanks!

**Comment by peanutbutterandcrackers** [comment]
Please try [this](https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.4.1-168-g9b3b2fc-d8aa28ba-f32c7c30-x86_64.exe) build. Hope that helps!

**Comment by peanutbutterandcrackers** [comment]
The following are the beta-builds that contain the changes made to resolve this issue (PR #1726 by the awesome @ferdnyc). Please try them out and report whether this resolves the issue. Thanks!
1. [Windows Builds](https://drive.google.com/open?id=1n5_joUIWr4FI7daLaCj7WwFUk-sXsVKN)
2. [Mac Builds](https://drive.google.com/open?id=10zy1SQz6gGCxfmYZtMnTYHkC5NBQy6Oz)
3. [Linux Builds](https://drive.google.com/open?id=10D6BIF_n8krpYB-goNQ7jj4W33OSv4Yg)

**Comment by peanutbutterandcrackers** [comment]
Clsoing as dup of #307 and as fixed in 2.4.2
