### ISSUE TITLE
Missing support for danish Æ Ø Å

### ISSUE THREAD

**Issue by IdealSchreiber** [OpenShot/openshot-qt#737]
**System Details:**
* Operating System Windows 10
* OpenShot Version: 2.3.4

If a project is created and saved at a location where a folder has one of the following letters Æ Ø Å, it can not be opened again if the program has been shut down.

Easy fix, dont use those letters :)

**Comment by DylanC** [comment]
@IdealSchreiber - Should work now in latest daily build.

**Comment by DylanC** [comment]
Dup of #677
