### ISSUE TITLE
Audio effects missing

### ISSUE THREAD

**Issue by carnussien** [OpenShot/openshot-qt#738]
**System Details:**
* Operating System / Distro: ?  Ubuntu 14.04  i286
* OpenShot Version: ?  2.3.4
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
I have just installed  openshot  2.3.4
Openshot  seems working well  BUT:
 I have only got  7 video effects and zero audi effect?

Could you help?
Thanks
Robert

**Comment by openpianist** [comment]
that is what was distributed in the current version.
I am hoping for more to come in the next version too.

**Comment by DylanC** [comment]
@carnussien - Thanks for your feedback.  More effects will be added in a future version.
