### ISSUE TITLE
Will not start in Ubuntu Gnome 17.04

### ISSUE THREAD

**Issue by darkstar4386** [OpenShot/openshot-qt#739]
I am using a relatively clean installation of Ubuntu Gnome 17.04 (installed earlier today). I installed OpenShot using the stable PPA. clicking on the launch icon causes a bit of hard drive activity, but the app never opens. I will supply logs if someone can tell me where they would be found.

My machine is a Lenovo i5 (Haswell), 8GB RAM, 1TB HD.

**Comment by openpianist** [comment]
it runs on with a  standard Ubuntu 17.04 on my machine.

Lenovo T440, i5-4300U CPU @ 1.90GHz × 4 , 7,5 GiB, 

I used the AppImage form the website
http://openshot.org/download/

- O.

**Comment by DylanC** [comment]
@darkstar4386 - Is this still an issue for you?

**Comment by darkstar4386** [comment]
@DylanC I just installed it on on another fresh Ubuntu Gnome installation and it launches with no problems, and fast! Thanks!

**Comment by DylanC** [comment]
@darkstar4386 - Great news, thanks!
