### ISSUE TITLE
missing parts of audio/video after exporting

### ISSUE THREAD

**Issue by fabrixx** [OpenShot/openshot-qt#740]
**System Details:**
* Operating System / Distro: Arch Linux
* OpenShot Version: 2.3.3
* _Please attach log files if crash_
I am going crazy.... in preview audio & video is ok for ALL video duration

After export first 10 seconds of audio is mute, video turn black from 2 minutes to end.
I tryed several export settings but have same problem

**Comment by openpianist** [comment]
I have not seen this with version Openshot 2.3.4
Please check with latest version.

- O.

**Comment by fabrixx** [comment]
same problem on 2.3.4. Tryed with several settings. Preview is ok. After exportation first 10 seconds clip have no audio, after 44 seconds video come black. Audio is popping.
Is so frustrating, hours to arrange clip and impossible to export. Now openshot 1.4 (stable and usable) not work anymore cause gtk problems. I have several titles and have no mode to import. I have to find another pc with 1.4 working. Damn!!

**Comment by DylanC** [comment]
@fabrixx - What format of video and audio do you use?

**Comment by fabrixx** [comment]
My solution: https://github.com/OpenShot/openshot-qt/issues/854

**Comment by DylanC** [comment]
Could not reproduce on latest build.
