### ISSUE TITLE
Add to timeline - add in files sorted filename

### ISSUE THREAD

**Issue by notzippy** [OpenShot/openshot-qt#741]
**System Details:**
* Operating System / Distro: Ubuntu
* OpenShot Version: 2.3.4

**Issue Description and steps to reproduce:**
Select 30 images, click add to timeline. Add to timeline dialog appears but images not in same order as they where in project files window. 

Two fixes come to mind - 
* `add_to_timeline.py` add a sort function when dialog is created, for example (linux only)

        sorted_files = sorted(files, key=lambda k:("                            " + k.data["path"].rsplit('/', 1)[-1])[-20:] ,reverse=False)

        # Update data in model
        self.treeFiles.timeline_model.update_model(sorted_files)
* `add_to_timeline.py` add a sort button on dialog so files can be sorted

**Comment by jarileon** [comment]
I came to this page when trying to figure out why is the order of images wrong in the "Add to Timeline" dialog. I am trying to create a slideshow video and I have named the images with integers in ascending order. All is good in the Project Files panel, but in the "Add To Timeline" dialog the order is just weird and wrong. There should be a "Sort by.." option of some sort. The UX of reordering the images is just horrible - it refreshes the whole list and loses focus every time the arrow up and down sorting buttons are pressed =(

It is quite sad how pretty much all open source applications that have any kind of GUI are weird and lacking when they come to UX...and sadly OpenShot does not seem to be an exception.

**Comment by darkestmon** [comment]
For a workaround, I found that when you show them in "Details View" instead of "Thumbnails View", they are inserted in the correct order instead.

**Comment by cohnt** [comment]
Thank you @darkestmon for the workaround -- I can confirm that this works.

**Comment by SuslikV** [comment]
This is related to the fact that _Thumbnails_ view has not all indexes selected in the model (<kbd>Ctrl+A</kbd> should work well too).

**Comment by ferdnyc** [comment]
A consequence of the fix for #3492 (adding drag-and-drop folder imports) was that the import list _had_ to be sorted, because Python's default directory walk jumps all over the place and it was breaking the image sequence discovery. So, this should be at least significantly improved now (though post-import, user-controlled sorting would still be the ideal fix).
