### ISSUE TITLE
Cracking sound

### ISSUE THREAD

**Issue by rohanv4** [OpenShot/openshot-qt#743]
**System Details:**
* Operating System: Windows 10
* OpenShot Version: ?

**Issue Description and steps to reproduce:**
after about. 01:30 Seconds Is the sound, how can I solve this?

**Comment by DylanC** [comment]
@rohanv4 - What audio format did you use?

**Comment by DylanC** [comment]
@rohanv4 - Try v2.4 daily build. Its much better for audio issues.
