### ISSUE TITLE
Crash on Startup (Windows 10

### ISSUE THREAD

**Issue by jwkappel** [OpenShot/openshot-qt#745]
**System Details:**
* Operating System / Distro: Windows 10 (64-bit)
* OpenShot Version: 2.3.4
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**  I receive this message immediately after opening the program.  I've tried reopening, reinstalling, etc.  Any thoughts?

![image](https://user-images.githubusercontent.com/29587687/27362845-047c375a-55ff-11e7-8d28-f950d01403c5.png)

**Comment by DylanC** [comment]
Startup issues on Windows should be resolved. Please try again in v2.4.
