### ISSUE TITLE
separate video and audio sends video clip to start 0 but not in properties

### ISSUE THREAD

**Issue by vinthefuture** [OpenShot/openshot-qt#746]
**System Details:**
* Operating System / Distro: Win 7 x64
* OpenShot Version: 2.3.4

Already composed my clips into a rough cut using audio from DSLR. Wanted to separate audio from video after everything's been put in position. Video starts from start 0, even though the properties show the correct start, and the audio starts from the correct start.

**Comment by vinthefuture** [comment]
Follow up -- actually all clips are affected. Audio distorted, most video starts from incorrect starts.

**Comment by DylanC** [comment]
@vinthefuture - How is v2.4.1 for you?

**Comment by peanutbutterandcrackers** [comment]
@vinthefuture - Have you tried turning it off and on again? 😆 Okay. Jokes aside, could you please upgrade to the latest version (v 2.4.1) and report back on this issue?
