### ISSUE TITLE
Problem playing mp3 audio file at time 2 '31"

### ISSUE THREAD

**Issue by vales** [OpenShot/openshot-qt#748]
**System Details:**
* Operating System / Distro: Windows 10
* OpenShot Version: OpenShot-v2.3.4-1-gb335c0e-55-633-x86_64 daily

**Issue Description and steps to reproduce:**
Also the OpenShot-v2.3.4-1-gb335c0e-55-633-x86_64 daily version continues to have the block in playing audio mp3 files at time 2 '31".
The problem is resolved by converting the audio file from mp3 to ac3.

**Comment by vikinkje** [comment]
Same problem here. Audio locks at 2.41 min. Only  first mp3 .
Win10 64

**Comment by ddhhm** [comment]
Same problem here.  https://youtu.be/b89H7lbNfY0 is currently exhibiting this exact problem.  I'm on Windows 7, 64 bit.  I'll try transcoding.  FWIW, my audio begins slightly before the video, which was a AVI with audio removed by VLC.

**Comment by bakersma** [comment]
Exact same problem....OpenShot 2.3.4, Windows 10 Home - Version 1703 Build 15063.413, x64, 8GB RAM Intel Core I7-3610QM, 2.30 GHz, Lenovo IdeaPad laptop.  

MP3 audio quits working at approx 2:35 into clip....just hear soft putt-putt sound past that point.

I do not think this problem existed before the big Windows 10 "Creators" update got installed on my machine this past week but I may be mistaken.

Thank you very much !

**Comment by DylanC** [comment]
Dup of #618

**Comment by DylanC** [comment]
I have been notified this has been fixed in the latest daily build. Please try it out.

**Comment by DylanC** [comment]
This is resolved in the latest daily build:
![solved](https://user-images.githubusercontent.com/4488048/31321108-155f4970-ac78-11e7-8783-0439def02c0e.png)
