### ISSUE TITLE
Export to mpg repeatedly fails with error message - exception class 'openshot.ErrorEncodingVideo'

### ISSUE THREAD

**Issue by jdwilliam1971** [OpenShot/openshot-qt#752]
**System Details:**
* Operating System / Distro: OpenSuse Leap 42.2 Plasma 5
* OpenShot Version: 2.3.4
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
After reading the support column, I downloaded and tried the latest version.  I only tried a couple of edits because the export crashed right after it started each time.  I was working with the DVD, NTSC, High setting.  Couldn't export so there was no use editing what is supposedly a less flaky version.

Sure wish the pre version 2 Openshot editor was available.

**Comment by jdwilliam1971** [comment]
Error Message is:  Sorry, There was an error exporting your video: exception class 'openshot.ErrorEncodingVideo'

**Comment by jdwilliam1971** [comment]
I've now tried V 2.3.4 on two different systems, both running OpenSuse Leap 42.2 w/Plasma 5.  Both are up to date and both crash when attempting to export to a DVD, NTSC, High mpg file.  The crash occurs immediately after starting the export.

**Comment by DylanC** [comment]
@jdwilliam1971 - I assume this is the same in v2.4?
