### ISSUE TITLE
feature request: Please add the old "Shift Clip" to Ver. 2 of openshot

### ISSUE THREAD

**Issue by jdwilliam1971** [OpenShot/openshot-qt#753]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
I always end up cutting and editing out portions of my videos.  In the past I was able to use the menu item Shift Clip to move the clip to where I wanted it (or very close to it).  Can't seem to figure out a similar easy way to do this with Ver 2.##.  Too much cutting then dragging of the remaining clip to the left to edited clip invariably crashes the program.  Please return the Shift Clip option to the program.

**Comment by JohanG77** [comment]
Hello,

I am looking for such a feature as well.

I split my videos then I set time = 8X to some parts of it. Dragging and dropping the subsequent parts takes a lot of time. A perfect feature for me would be "stick sequence to the end of left sequence" or "stick sequence to the beginning of right sequence" but the feature described above is fine too.

**Comment by peanutbutterandcrackers** [comment]
Recently, a shift effect has been added to OpenShot. Could you please try out the latest [daily build](https://github.com/OpenShot/openshot-qt/releases/tag/daily) and see if that is the thing that you were looking for? Thanks!

**Comment by Fraifrai** [comment]
@peanutbutterandcrackers : the shift effect you are talking about has no relation with this issue which is about the lack of the possibility to shift all sequences on the right of the pointer further in the timeline.

**Comment by peanutbutterandcrackers** [comment]
Hmmm... I see. Well, let's hope we would have enough volunteers/contributors to have this feature implemented soon.

**Comment by aleksclark** [comment]
So, I was searching for how to do this, and it turns out to be simple, and easy to miss: click & drag on an empty bit of timeline to select multiple clicks, then you can move them at will

**Comment by ferdnyc** [comment]
@aleksclark If I understand the original request correctly, that's not the same thing. Multiple-selection (which you can also make by <kbd>Ctrl</kbd>-clicking additional clips, after selecting the first) will allow you to move a set of clips while maintaining their relative positions, this is about moving an individual clip forward/backward on the timeline.

OpenShot **does** now have a "Nudge" command (<kbd>Shift</kbd>+<kbd>←</kbd> and <kbd>Shift</kbd>+<kbd>→</kbd>, in the default keybindings), to move the selected clip backwards/forwards by small amounts — depending on the distance the clip needs to be moved, that might be of some use.

The feature requests in #2789 and #3057 also involve automatic placement of clips and removal of timeline gaps, which would be related to this issue.
