### ISSUE TITLE
Time/Fade in combination Crash

### ISSUE THREAD

**Issue by BumbleGrum** [OpenShot/openshot-qt#754]
**System Details:**
* Operating System / Distro: Windows 10
* OpenShot Version: 2.3.4
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
I added 3 timeline actions to an animated title in the timeline. The combination of these causes OpenShot to crash everytime when you start to play the title. It doesn't seem to matter in what sequence you add these actions!

The animation I am using is Dissolving Text. It may happen with other title types but I have not tested that.

The actions are:
1.  Fade/StartOfClip/Slow
2.  Time/Slow/Forward/1/2X
3.  Animate/StartOfClip/EdgeToCenter/BottomToCenter

All the actions are accepted, but if you try to play that part of the timeline, OpenShot crashes.

Can you please let people know where to find the Log file in the ***guidelines for contributing***. And for now please tell me where to find it!

** **Addendum** **
On further testing I have determined that it is the ***Time*** action *combined with* the ***Fade*** action causing the problem. It seems to have nothing to do with ***Animate***. 

Animate and Fade work OK, and Time and Animate work fine as well.

**Comment by DylanC** [comment]
@BumbleGrum - Thanks for the report. I will investigate with the latest build.

**Comment by charlesbillingsley** [comment]
I also am experiencing this problem on Windows 10 and version 2.4.1. I get a crash when playing back clips that are sped up 2x when they attempt to fade out.
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/1493651/openshot-qt.log)

**Comment by DylanC** [comment]
@charlesbillingsley - Thanks!

**Comment by peanutbutterandcrackers** [comment]
@BumbleGrum - Hey there, could you please upgrade to the latest version and see if the issue manifests itself there too?

**Comment by AtomicWaffle14** [comment]
I'm getting this problem on version 2.4.2

**Comment by peanutbutterandcrackers** [comment]
Does this issue still persist in the latest [daily builds](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914)?
