### ISSUE TITLE
OpenShot does not start on Ubuntu

### ISSUE THREAD

**Issue by openpianist** [OpenShot/openshot-qt#755]
**System Details:** 
* Operating System / Distro: ? 17.04 Ubuntu
* OpenShot Version: 2.3.4-1
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
After some non recreatable issues, 
maybe system crash, incl messed up config files.
maybe parallel installation of 1.4
maybe new installation of 2.3.4-1

OpenShot does not start anymore.

**Solution: **
**delete**  (or rename) the hidden OpenShot folder

**.openshot_qt**

a new one will be generated during the next start.
Issue solved.

**Comment by DylanC** [comment]
Closing as solved.
