### ISSUE TITLE
New Title Tab

### ISSUE THREAD

**Issue by OMCMDT** [OpenShot/openshot-qt#757]
With Openshot Video Editor, why is there no "new title" in the Title drop down menu. How can I create a title?

**Issue Description and steps to reproduce:**

**Comment by openpianist** [comment]
you can create a title by choosing a predefined title from the title templates

Title:
- Title (lots of templates)
- Animated Title (generate a 3D Title with Blender)

**Comment by DylanC** [comment]
Question has been answered above.
