### ISSUE TITLE
Merge an title inro a video

### ISSUE THREAD

**Issue by Pejamide** [OpenShot/openshot-qt#758]
Today I used your excellent program OPENSHOT for the first time. I have inported a video (with the chroma key) into the track 4 and created a new title in the track 3 (in order to paste it on the video. I started the preview, but I still do not see the title?! What shoud I have done wrong?

**Comment by openpianist** [comment]
track 4 is on top of track 3, 
like on a sheet of papers..
if you put track 4 on top of track 3 you will not see track3

If you make track 4 partial invisible (chroma key, transitions, etc) you should be able to see the track 3 through it.

I suggest, you try first to put track 3 on top of 4.
I assume your title should be on top of the video.

If you want to continue to have the titel "under" the video, you can play around with 
moving the tracks... 
transitions and
see through exercises, like shrinking the movie etc... 
to see if this works..

I am sure you will figure out, what you want to see.

have fun
- O,

**Comment by DylanC** [comment]
Question answered above.
