### ISSUE TITLE
First use of preview a type of media crashes it

### ISSUE THREAD

**Issue by DarrenCook** [OpenShot/openshot-qt#759]
**System Details:**
* Operating System / Distro: Mint 18.1/xfce
* OpenShot Version: 3.4.3 appimage
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

For each of jpg, mp3 and a title, when I've right-clicked in the Project Files tab, and chosen "Preview File" the whole app has crashed (suddenly vanished). I can re-open, and when I try again it is fine. It is as if it is learning what to do with that file, and it is just a bit flaky the first time.

Also, the first time I re-open my project (by double-clicking the .osp file) after a crash it starts OpenShot but without loading my file. I close, try again, and this time it works. (Double-click the .osp file after a normal shutdown seems to work reliably.)

**Comment by DylanC** [comment]
@DarrenCook - Does this happen in v2.4?

**Comment by DarrenCook** [comment]
Sorry, cannot say. (Not an OpenShot user, was just reporting the bug when trying it out a few months ago).

**Comment by DylanC** [comment]
@DarrenCook - No problem. Thanks for the report anyway. I will try it out when I get the time.

**Comment by DylanC** [comment]
No repro on the daily.
