### ISSUE TITLE
Video-Player GUI doesn't always display the correct state

### ISSUE THREAD

**Issue by DerGenaue** [OpenShot/openshot-qt#76]
Just a small one:

Editing the Clip during Playback seems to pause playback.
Nevertheless the GUI doesn't change its state so one has to click the play button twice to actually make it play

**Comment by ankitpati** [comment]
No repro with OpenShot 2.2 AppImage on Ubuntu 16.04. Playback simply does not pause upon editing the clip, so there is no need for the button to change state.

Closing this as fixed. Please reopen if necessary.
