### ISSUE TITLE
OpenShot 2.3.4 not allow Time->Fast->Forward Crashing when export or play

### ISSUE THREAD

**Issue by johnparra** [OpenShot/openshot-qt#761]
**System Details:**
* Operating System / Distro: Archlinux
* OpenShot Version: 2.3.4
preview_thread:INFO refreshFrame
preview_thread:INFO self.player.Position(): 1
properties_model:INFO Update frame to 1
properties_model:INFO updating clip properties model.
properties_model:INFO Getting properties for frame 1: OrderedDict([('alpha', {'choices': [], 'closest_point_x': 1.0, 'interpolation': 2, 'keyframe': True, 'max': 1.0, 'memo': '', 'min': 0.0, 'name': 'Alpha', 'points': 1, 'previous_point_x': 1.0, 'readonly': False, 'type': 'float', 'value': 1.0}), ('anchor', {'choices': [{'name': 'Canvas', 'selected': True, 'value': 0}, {'name': 'Viewport', 'selected': False, 'value': 1}], 'closest_point_x': -1, 'interpolation': 2, 'keyframe': False, 'max': 1.0, 'memo': '', 'min': 0.0, 'name': 'Anchor', 'points': 0, 'previous_point_x': -1, 'readonly': False, 'type': 'int', 'value': 0.0}), ('channel_filter', {'choices': [], 'closest_point_x': 1.0, 'interpolation': 2, 'keyframe': True, 'max': 10.0, 'memo': '', 'min': -1.0, 'name': 'Channel Filter', 'points': 1, 'previous_point_x': 1.0, 'readonly': False, 'type': 'int', 'value': -1.0}), ('channel_mapping', {'choices': [], 'closest_point_x': 1.0, 'interpolation': 2, 'keyframe': True, 'max': 10.0, 'memo': '', 'min': -1.0, 'name': 'Channel Mapping', 'points': 1, 'previous_point_x': 1.0, 'readonly': False, 'type': 'int', 'value': -1.0}), ('duration', {'choices': [], 'closest_point_x': -1, 'interpolation': 2, 'keyframe': False, 'max': 5184000.0, 'memo': '', 'min': 0.0, 'name': 'Duration', 'points': 0, 'previous_point_x': -1, 'readonly': True, 'type': 'float', 'value': 50.850799560546875}), ('has_audio', {'choices': [], 'closest_point_x': 1.0, 'interpolation': 2, 'keyframe': True, 'max': 1.0, 'memo': '', 'min': -1.0, 'name': 'Enable Audio', 'points': 1, 'previous_point_x': 1.0, 'readonly': False, 'type': 'int', 'value': -1.0}), ('has_video', {'choices': [], 'closest_point_x': 1.0, 'interpolation': 2, 'keyframe': True, 'max': 1.0, 'memo': '', 'min': -1.0, 'name': 'Enable Video', 'points': 1, 'previous_point_x': 1.0, 'readonly': False, 'type': 'int', 'value': -1.0}), ('end', {'choices': [], 'closest_point_x': -1, 'interpolation': 2, 'keyframe': False, 'max': 5184000.0, 'memo': '', 'min': 0.0, 'name': 'End', 'points': 0, 'previous_point_x': -1, 'readonly': False, 'type': 'float', 'value': 50.8841667175293}), ('display', {'choices': [{'name': 'None', 'selected': True, 'value': 0}, {'name': 'Clip', 'selected': False, 'value': 1}, {'name': 'Timeline', 'selected': False, 'value': 2}, {'name': 'Both', 'selected': False, 'value': 3}], 'closest_point_x': -1, 'interpolation': 2, 'keyframe': False, 'max': 3.0, 'memo': '', 'min': 0.0, 'name': 'Frame Number', 'points': 0, 'previous_point_x': -1, 'readonly': False, 'type': 'int', 'value': 0.0}), ('gravity', {'choices': [{'name': 'Top Left', 'selected': False, 'value': 0}, {'name': 'Top Center', 'selected': False, 'value': 1}, {'name': 'Top Right', 'selected': False, 'value': 2}, {'name': 'Left', 'selected': False, 'value': 3}, {'name': 'Center', 'selected': True, 'value': 4}, {'name': 'Right', 'selected': False, 'value': 5}, {'name': 'Bottom Left', 'selected': False, 'value': 6}, {'name': 'Bottom Center', 'selected': False, 'value': 7}, {'name': 'Bottom Right', 'selected': False, 'value': 8}], 'closest_point_x': -1, 'interpolation': 2, 'keyframe': False, 'max': 8.0, 'memo': '', 'min': 0.0, 'name': 'Gravity', 'points': 0, 'previous_point_x': -1, 'readonly': False, 'type': 'int', 'value': 4.0}), ('id', {'choices': [], 'closest_point_x': -1, 'interpolation': 2, 'keyframe': False, 'max': -1.0, 'memo': 'TMYNBIGLHP', 'min': -1.0, 'name': 'ID', 'points': 0, 'previous_point_x': -1, 'readonly': True, 'type': 'string', 'value': 0.0}), ('location_x', {'choices': [], 'closest_point_x': 1.0, 'interpolation': 2, 'keyframe': True, 'max': 1.0, 'memo': '', 'min': -1.0, 'name': 'Location X', 'points': 1, 'previous_point_x': 1.0, 'readonly': False, 'type': 'float', 'value': 0.0}), ('location_y', {'choices': [], 'closest_point_x': 1.0, 'interpolation': 2, 'keyframe': True, 'max': 1.0, 'memo': '', 'min': -1.0, 'name': 'Location Y', 'points': 1, 'previous_point_x': 1.0, 'readonly': False, 'type': 'float', 'value': 0.0}), ('position', {'choices': [], 'closest_point_x': -1, 'interpolation': 2, 'keyframe': False, 'max': 5184000.0, 'memo': '', 'min': 0.0, 'name': 'Position', 'points': 0, 'previous_point_x': -1, 'readonly': False, 'type': 'float', 'value': 0.0}), ('rotation', {'choices': [], 'closest_point_x': 1.0, 'interpolation': 2, 'keyframe': True, 'max': 360.0, 'memo': '', 'min': -360.0, 'name': 'Rotation', 'points': 1, 'previous_point_x': 1.0, 'readonly': False, 'type': 'float', 'value': 0.0}), ('scale', {'choices': [{'name': 'Crop', 'selected': False, 'value': 0}, {'name': 'Best Fit', 'selected': True, 'value': 1}, {'name': 'Stretch', 'selected': False, 'value': 2}, {'name': 'None', 'selected': False, 'value': 3}], 'closest_point_x': -1, 'interpolation': 2, 'keyframe': False, 'max': 3.0, 'memo': '', 'min': 0.0, 'name': 'Scale', 'points': 0, 'previous_point_x': -1, 'readonly': False, 'type': 'int', 'value': 1.0}), ('scale_x', {'choices': [], 'closest_point_x': 1.0, 'interpolation': 2, 'keyframe': True, 'max': 1.0, 'memo': '', 'min': 0.0, 'name': 'Scale X', 'points': 1, 'previous_point_x': 1.0, 'readonly': False, 'type': 'float', 'value': 1.0}), ('scale_y', {'choices': [], 'closest_point_x': 1.0, 'interpolation': 2, 'keyframe': True, 'max': 1.0, 'memo': '', 'min': 0.0, 'name': 'Scale Y', 'points': 1, 'previous_point_x': 1.0, 'readonly': False, 'type': 'float', 'value': 1.0}), ('shear_x', {'choices': [], 'closest_point_x': 1.0, 'interpolation': 2, 'keyframe': True, 'max': 1.0, 'memo': '', 'min': -1.0, 'name': 'Shear X', 'points': 1, 'previous_point_x': 1.0, 'readonly': False, 'type': 'float', 'value': 0.0}), ('shear_y', {'choices': [], 'closest_point_x': 1.0, 'interpolation': 2, 'keyframe': True, 'max': 1.0, 'memo': '', 'min': -1.0, 'name': 'Shear Y', 'points': 1, 'previous_point_x': 1.0, 'readonly': False, 'type': 'float', 'value': 0.0}), ('start', {'choices': [], 'closest_point_x': -1, 'interpolation': 2, 'keyframe': False, 'max': 5184000.0, 'memo': '', 'min': 0.0, 'name': 'Start', 'points': 0, 'previous_point_x': -1, 'readonly': False, 'type': 'float', 'value': 0.0}), ('time', {'choices': [], 'closest_point_x': 1.0, 'interpolation': 1, 'keyframe': True, 'max': 5184000.0, 'memo': '', 'min': 0.0, 'name': 'Time', 'points': 2, 'previous_point_x': 1.0, 'readonly': False, 'type': 'float', 'value': 1.0}), ('layer', {'choices': [], 'closest_point_x': -1, 'interpolation': 2, 'keyframe': False, 'max': 20.0, 'memo': '', 'min': 0.0, 'name': 'Track', 'points': 0, 'previous_point_x': -1, 'readonly': False, 'type': 'int', 'value': 5.0}), ('volume', {'choices': [], 'closest_point_x': 1.0, 'interpolation': 2, 'keyframe': True, 'max': 1.0, 'memo': '', 'min': 0.0, 'name': 'Volume', 'points': 1, 'previous_point_x': 1.0, 'readonly': False, 'type': 'float', 'value': 1.0}), ('wave_color', {'blue': {'choices': [], 'closest_point_x': 1.0, 'interpolation': 0, 'keyframe': True, 'max': 255.0, 'memo': '', 'min': 0.0, 'name': 'Blue', 'points': 1, 'previous_point_x': 1.0, 'readonly': False, 'type': 'float', 'value': 255.0}, 'choices': [], 'closest_point_x': 1.0, 'green': {'choices': [], 'closest_point_x': 1.0, 'interpolation': 0, 'keyframe': True, 'max': 255.0, 'memo': '', 'min': 0.0, 'name': 'Green', 'points': 1, 'previous_point_x': 1.0, 'readonly': False, 'type': 'float', 'value': 123.0}, 'interpolation': 0, 'keyframe': True, 'max': 255.0, 'memo': '', 'min': 0.0, 'name': 'Wave Color', 'points': 1, 'previous_point_x': 1.0, 'readonly': False, 'red': {'choices': [], 'closest_point_x': 1.0, 'interpolation': 0, 'keyframe': True, 'max': 255.0, 'memo': '', 'min': 0.0, 'name': 'Red', 'points': 1, 'previous_point_x': 1.0, 'readonly': False, 'type': 'float', 'value': 0.0}, 'type': 'color', 'value': 0.0}), ('waveform', {'choices': [{'name': 'Yes', 'selected': False, 'value': 1}, {'name': 'No', 'selected': True, 'value': 0}], 'closest_point_x': -1, 'interpolation': 2, 'keyframe': False, 'max': 1.0, 'memo': '', 'min': 0.0, 'name': 'Waveform', 'points': 0, 'previous_point_x': -1, 'readonly': False, 'type': 'int', 'value': 0.0})])

**OpenShot open:**
1. Import file .mkv
2. Add file to timeline
3. Right click over clip on timeline
4. Select Time > Fast > Forward > 2X
5. Crash without register anything on the log

**Comment by itnas19** [comment]
I Experimented the same problem. I use ubuntu 16.04 64K and 8 GB Ram. I use OpenShot-v2.3.4-x86_64.AppImage

**Comment by DylanC** [comment]
Confirmed as fixed in #588
