### ISSUE TITLE
Multiple selections (CTRL + Mouse) not working

### ISSUE THREAD

**Issue by fajabird** [OpenShot/openshot-qt#762]
**System Details:**
* Operating System / Distro: Arch Linux
* OpenShot Version: 2.3.4
* _Please attach log files if crash_

Selecting/marking multiple clips by holding CTRL and left-clicking some clips does not work really. Steps to reproduce:
1. hold CTRL
2. mark some clips
3. press DEL to delete all marked clips (same for any other action)
Expected result: all marked clips are gone
Result: only the last selected clip is beeing deleted, others stay although beeing marked

**Comment by DylanC** [comment]
@fajabird - Is this still an issue in the latest daily build?
