### ISSUE TITLE
openshot crashes

### ISSUE THREAD

**Issue by fulgorit** [OpenShot/openshot-qt#766]
Debian package with a MOV file and two tracks and two mp3

Segmentation fault

**Comment by itnas19** [comment]
I have the same problem. I use ubuntu 16.04 64K and 8 GB Ram.

**Comment by PASTJL** [comment]
Workaround try to export mp3 audios to aac files with audacity

**Comment by fulgorit** [comment]
ok thanks

**Comment by DylanC** [comment]
This has been resolved in the daily build -  See #618.

**Comment by fulgorit** [comment]
It could be great a script to make end movie credit like star wars

Two videos a line left to right grear
