### ISSUE TITLE
Cannot Split a Single Clip Correctly

### ISSUE THREAD

**Issue by cjburkey01** [OpenShot/openshot-qt#767]
**System Details:**
* Operating System / Distro: Mac OSX 10.12.4
* OpenShot Version: 2.3.4

I can't even get this program to split a clip. When it does successfully "split the clip," all it has done is removed a 10 second chunk of the video and moved the remainder back over.

This is tough to explain, but I'll see if I can't. I move the playhead to the position at which I wish to split/slice the (only) clip. I have tried CMD+K, the slice tool, and even using the slice menu on right click. Sometimes, it works, but almost all of the time, I loose 10 seconds of the video.

**Comment by DylanC** [comment]
@cjburkey01 - Is this still an issue in the latest daily build?

**Comment by DylanC** [comment]
Dup of #629
