### ISSUE TITLE
OpenShot crash during increase in speed

### ISSUE THREAD

**Issue by nuggetboo** [OpenShot/openshot-qt#768]
* Operating System / Distro: Windows 10
* OpenShot Version: 2.3.4
I'm not really sure how to post crash logs

**Issue Description and steps to reproduce:**
Clicked and dragged clip from desktop onto project
Dragged clip onto track 4
Cut about 3 minutes of video from original clip
Right-clicked clip and selected "time"
Selected "Fast" and tried x2, x4, and x8
Program crashed each time

**Comment by itnas19** [comment]
I have the same problem.

**Comment by Robbie-Koers** [comment]
I have the same problem.... :(

**Comment by cristiklein** [comment]
Same here. I am uploading the console output.

[openshot-crash-dump.txt](https://github.com/OpenShot/openshot-qt/files/1167625/openshot-crash-dump.txt)

**Comment by DylanC** [comment]
@nuggetboo - Confirmed as fixed in #587 #588

**Comment by DylanC** [comment]
Dup of #587
