### ISSUE TITLE
Application crashes on WMV import

### ISSUE THREAD

**Issue by oliversalzburg** [OpenShot/openshot-qt#77]
Windows 10 x64. I encoded a video with Microsoft Expression Encoder. When I try to import the file, OpenShot crashes.

**Comment by nwgat** [comment]
use mediainfo to get info about the file, a wmv file can have more than one codec, it can be MPEG-4 ASP codec or a VC-1 Codec

http://mediaarea.net/download/binary/mediainfo-gui/0.7.82/MediaInfo_GUI_0.7.82_Windows_x64_WithoutInstaller.7z

**Comment by oliversalzburg** [comment]
It's VC-1 IIRC. But I'll collect the mediainfo when I'm back at the office.

**Comment by oliversalzburg** [comment]
Here we go:
![](https://i.imgur.com/uxFR2FW.png)

**Comment by jonoomph** [comment]
If you have a small example video file, please attach it and re-open this issue. Some videos cause issues, and I'm happy to look into it, just need a sample video. Be sure it's pretty small, and also you don't mind others watching it. =) Thx!

**Comment by oliversalzburg** [comment]
[ScreenCapture_2016-03-18 14.17.59.zip](https://github.com/OpenShot/openshot-qt/files/179700/ScreenCapture_2016-03-18.14.17.59.zip)

This file should have the same parameters as the one where I noticed this issue. Sadly, I can't verify it right now, because OpenShot crashes instantly when I start it.

**Comment by oliversalzburg** [comment]
@jonoomph So, are you going to reopen this issue?
