### ISSUE TITLE
Cutting clip results in crash

### ISSUE THREAD

**Issue by JustCallMeStranger** [OpenShot/openshot-qt#771]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

you so last week i downloaded openshot windows version for make an amv (anime music video) but when i try to cut the cutscene is crash (not responding) and you need to take time for viewimg a video. and u need to take a lot of time just for the blur effect. thats's it jonathan thank you very much sorry for my bad english

**Comment by JustCallMeStranger** [comment]
btw my laptop spesification is i3 3217u and 4gb ddr3 ram and an intel hd 4000

**Comment by DylanC** [comment]
@JustCallMeStranger - What version of OpenShot were you using?

**Comment by JustCallMeStranger** [comment]
Latest version

**Comment by DylanC** [comment]
@JustCallMeStranger - You should try the daily build for the latest fixes and on maybe a more powerful machine. Cutting clips normally works just fine.
