### ISSUE TITLE
Can't split a video clip correctly

### ISSUE THREAD

**Issue by emaen** [OpenShot/openshot-qt#772]
intel core quad cpu q8200
Windows 7 64bits
OpenShot Version: 2.2.0 to 2.3.4

Hi all !
Each time I try to precisely split a videoclip at a particular given point ( keeping each parts of this clip ) : the result didn't match my split point.

Example :
One clip made of 1 sec of blue screen and 1 sec of red screen.
I want to split it into two clips in order to separate blue screen into a first clip and red screen in a second one.
After splitted, I always have some unwanted red images left at the end of the 'blue part' one AND unwanted blue images put at the beginning of the second 'red part' one !
Always !!
Absolutly enable to result with one clip containing only blue images and the other contaning only red images !!!

As precisly splitting is a basic operation for me... openshot is perfectly unusable.

**Comment by DylanC** [comment]
Dup of #767

**Comment by emaen** [comment]
Yes it's kind a duplicate. But it demonstrates that the problem is not platform specific (windows/mac) ;).

**Comment by DylanC** [comment]
Dup of #629
