### ISSUE TITLE
Where is transitions folder on a Mac?

### ISSUE THREAD

**Issue by Tanny2** [OpenShot/openshot-qt#774]
Hi, 

Where is this folder on a mac please?  Yosemite.  Thanks!

/.openshot_qt/transitions/ folder

**Comment by DylanC** [comment]
@Tanny2 - Maybe try a search for a folder called transitions in your system?

**Comment by DylanC** [comment]
@Tanny2 Try ~/Library/Preferences/.openshot_qt/transitions
