### ISSUE TITLE
Why do we use the G analytics?

### ISSUE THREAD

**Issue by mac010** [OpenShot/openshot-qt#776]
**System Details:**
* Linux / Fedora 25
* OpenShot Version 2.3.3-1

**Issue Description and steps to reproduce:**

Software seems to 'phone home' & 'phone google' when opened, not acceptable behaviour for linux software? Obviously not a bug.. please remove this behaviour as default, and add an option to enable it for those who choose to opt in to your market research. No compliance will result it reddit postings!

**Comment by DylanC** [comment]
@mac010 - This is to collect feedback on what areas of the program crash or have problems.
