### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by Tanny2** [OpenShot/openshot-qt#777]
**System Details:**  5 year old 27in iMac - 16gb RAM
* Operating System : OSX Yosemite
* OpenShot Version: ? 2.3.4

Love the interface and feature set.  Great combination of features and simplicity.   And a great manual, very well done, read the whole thing.  Really, nice job on that part.

But, apologies, just too many performance issues to make it worth it.  Lots of crashes, many force quits required, clips mysteriously vanish, transform really buggy, too many problems to list them all.  A twenty minute movie slowed display speed down to a crawl.  I'm fighting it every inch of the way. 

Shows a lot of promise, but just not ready yet.  I'd happily pay for this if/when it's solid.

Good luck!

**Comment by DylanC** [comment]
Thanks for your feedback.
