### ISSUE TITLE
Animating text to video

### ISSUE THREAD

**Issue by SpaceboyRoss01** [OpenShot/openshot-qt#779]
I want a way to animate a piece of text onto the screen without splitting the clips and then put on a title screen, is this possible?

**Comment by PASTJL** [comment]
With the properties tab, using keyframes, you can locate your text any place on the screen. You can rotate it, zoom it. The animation depends on the use of keyframes and the way ( linear, bezier) that you choose to go from a keyframe to the next for the correspondant effect ( location, zoom, rotation ...)

**Comment by DylanC** [comment]
Question answered above
