### ISSUE TITLE
Where is correcting lens distortion?

### ISSUE THREAD

**Issue by Ander1974** [OpenShot/openshot-qt#780]
* Operating System / Distro: Windows 7
* OpenShot Version: 2.3.4

Ok. In old version OpenShot 1.4.3 (Ubuntu) have correcring distorsion and many more effects. But in new version OpenShot not have correcting lens distorsion and only 7 effecfs. :-(

**Comment by DylanC** [comment]
@Ander1974 - Thanks for the feedback. More effects will be added in a future version.
