### ISSUE TITLE
I cant seam to split avi files? the file stays the same lenght? please help

### ISSUE THREAD

**Issue by davybarb** [OpenShot/openshot-qt#781]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

**Comment by davybarb** [comment]
win /10 
new version downloaded today,

there is no crash file

**Comment by DylanC** [comment]
@davybarb - It should be working just fine. Try the v2.4.1 release. Thanks.
