### ISSUE TITLE
Problems with windows 8.1

### ISSUE THREAD

**Issue by adamsstephen** [OpenShot/openshot-qt#782]
**System Details:**
* Operating System / Distro: Windows 8.1 X64 on toshiba Laptop
* OpenShot Version: 2.3.4
2.4gb cpu 4gb RAM
*

**I cannot get this program to display properly in windows or full screen, 
The tutorial overlays the taskbar outside the normal window and is immovable
You cannot see the clips in the timeline as it appears to be under the window.
The Project files and Video preview are immoveable, so that the rest of the screen can be seen
It is unusable in this condition, which is straight out of the box**

**Comment by DylanC** [comment]
Dup of #682

**Comment by DylanC** [comment]
Unable to reproduce.
