### ISSUE TITLE
Export Quality - High, Med, Low - Settings Meaning?

### ISSUE THREAD

**Issue by sourav-sahaji** [OpenShot/openshot-qt#783]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

Can you please help me in understanding the meaning of export quality parameter settings (high vs med vs low), as in what exactly it changes in the output video, provided the resolution is already fixed?
I tried googling about this, but couldn't find any useful information.
Thanks a lot.

**Comment by ElectricRCAircraftGuy** [comment]
I'd like to know too.

**Comment by peanutbutterandcrackers** [comment]
I think it has to do with how much detail from the original source actually makes it to the end result and not exactly the resolution. I once tried making a timelapse with openshot and the final file size was kinda' the sum of all the photographs used. Only VLC could play it well. I reckon, had I used 'low' or 'mid' quality parameters, I would have ended up with a smaller file size that had less details in the pictures.

Hope that helps.

**Comment by DylanC** [comment]
@peanutbutterandcrackers - I think people want to know exactly what those mean. I think only Mr.Thomas would know this.

**Comment by peanutbutterandcrackers** [comment]
@jonoomph - We need you here, El Capitano!

[Or maybe, we should ask him and relay the explanation here?]

**Comment by emanueleg** [comment]
When exporting, select a target format/codec/quality combination. Then, switch to the "Advanced" tab and check under the "Video Settings" and "Audio Settings"  sections the bitrate associated to the selected profile.

These values are pre-defined inside the presets/ directory using xml files. Each file describes a target profile and specifies the birates values both for audio and video at different qualities.

**Comment by jonoomph** [comment]
Yes, the presets basically adjust the bitrates for audio and video, reducing (or increasing) the visual and audio quality/clarity. However, some codecs behave differently with these values, and you will notice that "high" quality can look different on different codecs.

**Comment by DylanC** [comment]
Closing this question as answered, thanks @jonoomph!
