### ISSUE TITLE
Cannot mute/disable the whole track

### ISSUE THREAD

**Issue by gdab** [OpenShot/openshot-qt#784]
**System Details:**
* Operating System / Distro: Ubuntu 16.04
* OpenShot Version: 2.3.4
* 
I just install Openshot 2.3.4   and found it is harder to develop my video than the old version, 1.4.3.
The old version already have track and clips properties setting in hand. 
But for this version, it has many parameters I have to deal with.

**Comment by Johann-Tree** [comment]
Use the properties on the right side, set "Has Audio" to 0. That's it.

**Comment by DylanC** [comment]
@gdab -  Right click that section and select "mute clip".

**Comment by BarbzYHOOL** [comment]
Why do you close this ? you didn't answer his question

He asks how to mute an entire track, not all clips one by one. There isn't even an option "mute clip"...
Very annoying because I didn't see that and was expecting it to work normally

**Comment by gdab** [comment]
@DylanC I think it is more convenient to have muting for an entire track, so I don't have to mute for each clip in that track.

**Comment by DylanC** [comment]
@BarbzYHOOL  @gdab - Ah I understand now. Reopening this.

**Comment by abdilra7eem** [comment]
I am also having this problem, and it's making my work-flow extremely counter-intuitive.
I edit on multiple tracks, and usually isolate certain parts of clips on a muted and hidden track until I need them. and sometimes, I enable and disable semi-transparent tracks, or add titles which I need to hide and show while working.

**Comment by lenov** [comment]
I also bumped into this. Actually, I do not even know how to mute single clip. I cannot find any option anywhere. It might be a Linux issue. I am using Openshot 2.4.1 on Ubuntu 16.04.
Reverting to 1.x now, because v2 is unusable for me.

**Comment by BarbzYHOOL** [comment]
There are some things that are much faster on the new version, but some are much faster on 1.4
And it's crashing as much on both versions sadly :(

This is the only program that I use with crashes but I'm still going to use it because it has qualities

**Comment by N3WWN** [comment]
In 2.4.x, you can mute a clip by right clicking on it in the timeline and selecting `Volume` -> `Entire Clip` -> `Level 0%`.

If you want to mute and unmute (or alter the volume) at various points within a clip, you can move the playhead to where you want the volume changed and use the `Volume` in the properties frame to add a keyframe for the volume change.

Note that if you start with full volume (`Level 100%` or `1.00`) and add a single volume keyframe elsewhere in the track, the volume will adjust the entire time from the start of the track up until the keyframe.  To isolate the volume change, set two keyframes:  one at the end of the previous volume level and one at the start of the new volume level.  This way, you can set the length of the fade between levels.  

Also note that this isn't volume-specific info... this is true of all parameters that use keyframes.

**Comment by jboero** [comment]
Wow I'm super late to this party but Fedora finally upgraded to 2.4 and I was sad to see this whole-track mute missing.

One thing that isn't mentioned is it's much simpler to select multiple clips and disable them all at once.  CTRL-Click (SHIFT-Click doesn't work).  Anyway hope this helps someone in the future unless this feature gets re-added.

**Comment by jEsuSdA** [comment]
Please, add the Openshot old option to activate/deactivate mute/unmute an entire track.
It was completely useful!!

Thanks a lot!

**Comment by RobertRoberts2020** [comment]
How is this not a thing, it's literally impossible to use this, I have over 100 clips on this project and now as I'm ready to add the music, I find out there's litrerally no way to mute the tracks o I have to clikc EVERY SINGLE one of them and mute them It's like I literally lost the will to finish this project.

**Comment by pedroffranco** [comment]
This Video Editor is one of the best one out there for a beginner user. Is very important that functions of mute the entire track and the switch to turn on off the visibility of the entire track are restored. this functions, on a program of this kind, are fundamental. I hope the author consider write the code to restore this functions. Thanks a lot for your effort!!!

**Comment by SuslikV** [comment]
@pedroffranco Related PR - https://github.com/OpenShot/openshot-qt/pull/3438 or if you are Windows user, here is

Custom build (not official):
https://github.com/OpenShot/openshot-qt/issues/3383#issuecomment-638020348

**Comment by cmorse01** [comment]
Just adding to the request to be able to hide/show & mute/unmute at the track level.  In my use case I have a couple of tracks used for overlay graphics with chromakey filters to allow underlying video to show through.  But it would be handy to hide the overlays when keyframing the video clips without having to move them out of the way. That way can see the full clip I'm working on. Currently I'm dragging clips to edit into a temp track above the overlays to keyframe, then dragging them back down to their original track location under the overlays.  Thanks for all the hard work!!

**Comment by vlad88sv** [comment]
+1 to this request, I think there's enough space for a mute button there

![image](https://user-images.githubusercontent.com/91489/86985113-a4380a00-c14d-11ea-87aa-a502b0967732.png)

**Comment by jdpurnell** [comment]
I also have this problem and this is an important feature. Please add asap. I am running version 2.5.1 on WIndows.

**Comment by Innitinnuit** [comment]
This is sorely needed on the new version please!

**Comment by andyschmidt** [comment]
audio muting for the whole track is really important!

**Comment by technout** [comment]
I like this editor but on my first bigger project i bump into this.. i really need a mute whole track button. Even still in version 2.5.1 in 2021 this is the most wanted future!!
Also thank you for your great work and continues commitment to the project! Especially lead developer jonoomph :)

**Comment by evnow** [comment]
Is there a way to normalize & increase the audio ? 

No - the guidance is to use an external program like Audacity.

So, if we use audacity to edit audio - and bring it back as a track - we have to mute the current track. Its a very basic feature - given that even a basic audio feature like normalizing the volume is not available.

We need either
- mute / set volume level of entire track OR
- set volume level of all the selected clips. Currently if you select multiple clips only one clip's volume level changes - which one in particular seems unpredictable.

**Comment by JapanYoshi** [comment]
I tried OpenShot because I was getting impatient at how sluggish Resolve runs on my PC, but the lack of such a basic feature will hamper my workflow significantly. I will be searching for other alternatives for the time being, as this is a dealbreaker for me.

**Comment by N3WWN** [comment]
Track muting is still a valid and useful request, so commenting to keep this issue open.

**Comment by jondo** [comment]
OT: [Stalebot considered harmful](https://drewdevault.com/2021/10/26/stalebot.html)

**Comment by jdpurnell** [comment]
This is an extremely relevant feature. I would go so far as to say that
this is a video editing 101 basic feature! The inability to mute/toggle a
track of audio is unheard of in most basic video or audio editing
applications. I actually stopped using OpenShot for a while because this
feature was unavailable. What's even more interesting is that it appears
that initial versions of this tool had this feature and someone
actually thought it was a good idea to remove it.

Anyway, please keep open and add to the product. Once it's added then I can
come back fulltime!

**Comment by Colorjet3** [comment]
Yes, we need to differentiate the functionality/ability of muting a clip vs. muting an entire track.  On one track I can have multiple audio clips and now I want to manage another track that has audio clips and I need the ability, efficiently, to mute an entire track(s).  Recently I found out that when you use the "Separate Audio" function that the audio isn't really and truly separated from the original clip but rather it is muted.  This means the functionality is there and it just needs to be exposed as an off/on switch.  u/vlad88sv provided where it should be in https://github.com/OpenShot/openshot-qt/issues/784#issuecomment-655834598.

**Comment by N3WWN** [comment]
I consider this basic functionality that is still missing

**Comment by JapanYoshi** [comment]
Wow, it's been a year and muting a whole channel is still unimplemented?!

**Comment by jondo** [comment]
To everyone complaining: Your behavior is very rude. Please stop, unless you can offer your own implementation of the feature.

**Comment by jdpurnell** [comment]
Being able to mute an entire audio track is still relevant and should be considered basic functionality. I actually stopped using the tool because this is unavailable.

Is this software still under development/maintenance?

**Comment by Colorjet3** [comment]
Hello @jdpurnell Yes, this software is still under development and a v3.0.0 was just recently released.  The product owner/lead developer has taken more of a structured control of the product development cycle, bug fixes, and enhancements.  Lots of hard work was put in since the release of v2.6.1 to stabilize OpenShot, improve performance in some areas (still more is needed), many bug fixes and enhancements.

There is already work in-progress to get v3.0.1 out the door by January 2023 and this feature is in the queue.

https://trello.com/c/UtNKpw8B/8-mute-disable-whole-tracks

**Comment by jdpurnell** [comment]
> Hello @jdpurnell Yes, this software is still under development and a v3.0.0 was just recently released ...
> 
> There is already work in-progress to get v3.0.1 out the door by January 2023 and this feature is in the queue.
> 
> https://trello.com/c/UtNKpw8B/8-mute-disable-whole-tracks

This is fantastic news!! If possible, please notify this thread when that functionality is added! I would love to go back to using OpenShot!

**Comment by BarbzYHOOL** [comment]
lol

**Comment by Colorjet3** [comment]
@jdpurnell I will try.

**Comment by jdpurnell** [comment]
@Colorjet3 Will download this latest version and give it a go, thanks!

**Comment by N3WWN** [comment]
@Colorjet3 The latest daily build (Jan 18) does not include a way to mute tracks that I can see.  I don't see anything in the changelog or closed PRs for openshot-qt, libopenshot or libopenshot-audio that would indicate where this change was committed.  

Can you point us to the specific commit or PR that provides the ability to mute tracks? 

Thanks!

**Comment by Colorjet3** [comment]
Hello @N3WWN, the solution is not in place yet.  I am not sure if it is going to make it in v3.0.1.  Only the product owner/lead developer sets the priority on fixes and enhancements.

**Comment by jdpurnell** [comment]
@Colorjet3 So was it closed because the solution is developed but hasn't
been added to the release yet? Or did you close it because someone is
planning to fix it some day?

**Comment by Colorjet3** [comment]
Hello @jdpurnell No, the solution has not yet been developed.  It has been "approved" and is in the queue for release 3.0.1.  So, yes, it is closed because it is being planned to be fixed one day, and soon, I hope.

https://trello.com/c/UtNKpw8B/8-mute-disable-whole-tracks

**Comment by 0010110000** [comment]
Maybe some day we will finally see this happen.  I won't get my hopes up.

**Comment by nidaynere** [comment]
This is unbelievable...

**Comment by jdpurnell** [comment]
> Hello [@jdpurnell](https://github.com/jdpurnell) No, the solution has not yet been developed. It has been "approved" and is in the queue for release 3.0.1. So, yes, it is closed because it is being planned to be fixed one day, and soon, I hope.
> 
> https://trello.com/c/UtNKpw8B/8-mute-disable-whole-tracks

Now that it's been 2yrs and we are on release 3.3.0, has this been resolved?

**Comment by Colorjet3** [comment]
OpenShot Timline is going through some major architectural changes that will eventually facilitate these type of enhancements according to @jonoomph (the lead developer).

For, now, feel free to download v3.4.0-Release-Candidate where you can select multiple clips and make attribute changes that apply to all selected clips.

For example, you have many video/audio, audio, and image clips on Track 5.  Let's also assume that you have other clips on other tracks as well.  However, you want to mute all audio on Track 5.  Here is how you would do it:

1.  Hover the mouse over the first clip on Track 5 and single mouse click.  This will select the clip and all other clips to the right of it.  This is a new feature as well.
2.  Right click on the first clip and select Properties.
3.  From the Properties window, find the Volume attribute and change it from 1.0 to 0.00.
4.  This will mute all selected clips on Track 5.

Hope this helps.

Update:  You can find v3.4.0-RC at openshot.org/download/#daily.  This release is going through much testing and a few bugs have been found and are being worked on before it become ready for production release.  If you run into any issues, please submit a new post and I can report it to the lead developer.
