### ISSUE TITLE
launch.exe crash when Windows firewall control is enabled

### ISSUE THREAD

**Issue by furziger** [OpenShot/openshot-qt#790]
* Operating System / Distro: Windows 7
* OpenShot Version: 2.3.4

**Issue Description and steps to reproduce:**
Grab the tool "Windows 7 firewall control" or "Windows 8 firewall control" or "Windows 10 firewall control" and disable network communication for launch.exe and start launch.exe

**Comment by DylanC** [comment]
Dup of #601

**Comment by DylanC** [comment]
Not able to reproduce this one.
