### ISSUE TITLE
memory will 100% use

### ISSUE THREAD

**Issue by tony-snail** [OpenShot/openshot-qt#791]
HI,I am a user of fedora24(64bit),i7-4720,RAM:8Gb,openshot:2.3.4
when I export video my memory will 100% used so the OS shut it down.
it;s usually happen in timeline  have music as BGM.
How can I do and it's common?

by the way my BGM's format mp3.

**Comment by DylanC** [comment]
@tony-snail  - Try the daily build of v2.4. Should work better with the audio. Let me know if you still have the same problem.
