### ISSUE TITLE
Crash while cutting clips? 

### ISSUE THREAD

**Issue by jdwilliam1971** [OpenShot/openshot-qt#792]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

During edit which is a simple cut and shift remaining video left to meet original video; the cache save seems to be too slow and after a few cuts with resulting shift Openshot freezes and won't recover.  Have to force shutdown and restart.  Restart is often not where editing ended.  I can somewhat avoid the problem by saving after every edit and watching the hd light until it shuts off indicating cache save is complete. It is possible to to avoid the freeze most of the time with a save after every cut and shift, but this seems to be above and beyond.  Never had this issue with Openshot pre v2.  At present, I've moved on to Avidemux for real editing, but will continue to check back to see if some of the issues have been corrected.

**Comment by DylanC** [comment]
@jdwilliam1971 - Thanks for your feedback. I will test to confirm the issue.

**Comment by DylanC** [comment]
- Operating System / Distro:  OpenSuse Leap 42.2 Plasma 5
- OpenShot Version:  2.3.1

**Comment by DylanC** [comment]
@jdwilliam1971 - This is fine on the latest daily builds.
