### ISSUE TITLE
Tutorial blocked by taskbar

### ISSUE THREAD

**Issue by UncleBeer** [OpenShot/openshot-qt#794]
The tutorial and its buttons are blocked by the Windows Taskbar. It would make sense to move the tutorial balloon.

**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

**Comment by DylanC** [comment]
@UncleBeer - Do you have a screenshot of this issue?

**Comment by DylanC** [comment]
Not sure what you mean here. Closing for now unless you have details to add.
