### ISSUE TITLE
Does OpenShot support GPU rendering?

### ISSUE THREAD

**Issue by unfa** [OpenShot/openshot-qt#795]
I'm running Linux Mint.

**Is Openshot using OpenGL to process and composite the frames?
If not - is it possible in the future? How difficult that would be to implement?**

The reason why I'm asking is because I capture 3840x1080 60 FPS footage with OBS Studio, and editing this has proven very hard due to poor performance in Blender.

Rendering is also very slow. The main problem is Blender isn't even using all my 16 CPU threads to render the video sequences. I made a whole video about this a few days ago, if you're curious: https://www.youtube.com/watch?v=Y6PD6Zsh1bo

**So my question in general is: will Openshot use all the computation power I will throw at it to deliver the performance for heavy projects?**

I know Natron (an opensource compositing program similar to Nuke) is using GPU for all it's work and I've tried it - it's fast.

If that technology can be used in a video editor, it will be the fastest one in the opensource world.
And since the age of 480p is long gone, and the age of 4K is already here, that's the only way to go IMHO.

I don't want to use DaVinci Resolve (free and runs on Linux), because I want to push the opensource software and community forward, and being a part of it for many years now, I strongly believe it can deliver.

**Comment by ningwang747** [comment]
I'm using MacOS and I have same problem with you.

**Comment by DylanC** [comment]
@unfa - I think it does not at the moment but its a good idea for the future. I wouldn't be qualified to answer how much development effort it would take. I'm a developer but I have never touched OpenGL. However, I can suggest it for the development team and see what we will do depending on what it would take to implement.

I'm closing this as a question that has been answered but if I get a more detailed answer from the team I will update you.

**Comment by DylanC** [comment]
Update:

I had a quick chat with the team.

It would indeed be a huge development effort. I can't say that it will never happen for the future but we don't currently support it.

**Comment by timrohde** [comment]
That would be a profoundly worthwhile innovation!!! What kind of bounty would make sense for that?

**Comment by devalexqt** [comment]
I see in settings I can select video encoder, by default is libx264, can I select other encoder from supported libavcodec lib?

**Comment by wuast94** [comment]
+1 hardware acceleration is a must have for 4k h265 and so on

**Comment by DylanC** [comment]
#1983 - Has the most up date answer on this.

**Comment by kaos6669** [comment]
would be nice as open shot is only using 60% of 6 of my CPU cores I have 12 cores by the way, GPU isn't the best but I have an R9 390x still much more power than half my CPU and only half used

**Comment by griffinspire** [comment]
using OpenShot 2.6.1 on the following system  (lenovo ideapad 5 15.6" fhd touch, i7-1065g7, 12gb, 512gb ssd). with an optional iris accelerator. i was getting 100% CPU usage and 25% gpu while rendering an animated title.
