### ISSUE TITLE
Audio Crackle in preview and export

### ISSUE THREAD

**Issue by mokahless** [OpenShot/openshot-qt#799]
**System Details:**
* Operating System / Distro: Windows 10
* OpenShot Version: 2.3.4

**Issue Description and steps to reproduce:: Crackling audio during playback in openshot after cutting a scene (15 seconds in example). Crackling audio remains after export to default 1080p/23.98 profile (ac3 192, H264 1080p "high" quality)

Tried converting audio to vorbis before import and edit - still crackles. Crackling seems most concentrated near the cuts and near the end of the overall clip.

**Comment by petrhnilica** [comment]
The same issue

**Comment by petrhnilica** [comment]
Here is export from OpenShot https://www.youtube.com/watch?v=34m18QFaB_0

Here is export from bandicam https://www.youtube.com/watch?v=W3MJyOL3RFI&feature=youtu.be

**Comment by DylanC** [comment]
@mokahless  @petrhnilica - The v2.4 daily build is much better in relation to audio. Please try it out.

**Comment by joeostrander** [comment]
Why is this issue closed?  It seems like it's still a problem when I use it.  Using the latest daily build, trying on multiple computers.  I take video clip, crop it, add an mp3 for audio.  Nasty crackles in preview and export.  If I'm doing something wrong, please tell me, but it seems to be broken to me.
