### ISSUE TITLE
...is not a valid video, audio, or image file.

### ISSUE THREAD

**Issue by YoranSys** [OpenShot/openshot-qt#8]
From https://bugs.launchpad.net/openshot/+bug/1522780:

The problem come from local settings:
My local is french, in french we use "," for "." on float number.
JSON generated from importing a file is corrumpted exemple:
The field with french local is:
    "duration" : 113,1296844482422,

     !!!! Duration = 113 next field is 1296844482422 without value !!!!

With  english local:  
    "duration" : 113.1296844482422,

# {
        #    "acodec" : "",
        #    "audio_bit_rate" : 0,
        #    "audio_stream_index" : -1,
        #    "audio_timebase" : {
        #       "den" : 1,
        #       "num" : 1
        #    },
        #    "channel_layout" : 4,
        #    "channels" : 0,
        #    "display_ratio" : {
        #       "den" : 9,
        #       "num" : 16
        #    },
        #    "duration" : 113,1296844482422,
        #    "file_size" : "565232681",
        #    "fps" : {
        #       "den" : 1001,
        #       "num" : 60000
        #    },
        #    "has_audio" : false,
        #    "has_single_image" : false,
        #    "has_video" : true,
        #    "height" : 1080,
        #    "interlaced_frame" : false,
        #    "path" : "/home/yoran/Vidéos/DJI_0024.MP4",
        #    "pixel_format" : 0,
        #    "pixel_ratio" : {
        #       "den" : 1,
        #       "num" : 1
        #    },
        #    "sample_rate" : 0,
        #    "top_field_first" : true,
        #    "type" : "FFmpegReader",
        #    "vcodec" : "h264",
        #    "video_bit_rate" : 39970601,
        #    "video_length" : "6781",
        #    "video_stream_index" : 0,
        #    "video_timebase" : {
        #       "den" : 60000,
        #       "num" : 1
        #    },
        #    "width" : 1920
        # }

Solution :

You need to force local here :   openshot-qt/src/windows/views/files_listview.py

Insert this at line 41:

  import locale
  locale.setlocale(locale.LC_ALL, 'en_GB.utf8')

**Comment by djfun** [comment]
works also with
```
import locale
locale.setlocale(locale.LC_ALL, 'C')
```

**Comment by jonoomph** [comment]
Okay, thanks for bug report and work-around! I'll take a look. I really need to test each screen / feature using the French locale, in case we have a few more cases of numbers getting corrupted. =)

**Comment by jarlarntzen** [comment]
I can confirm that importing movie clips, pictures and audio works with regional formats set to English (United States) and does not work when set to Norwegian which uses comma (,) as the decimal separator.

**Comment by jonoomph** [comment]
Okay, I am defaulting the locale to 'C' on init, and this should force numbers to be in the 1234.56 format, which works fine. Ideally, when I have more time, I'll try and respect the locale's number format better, so the app feels a bit more native. Thanks!

**Comment by jarlarntzen** [comment]
Thanks! I'll test this on my Norwegian regional settings tonight (hopefully).
