### ISSUE TITLE
WINDOWS:  Titles should always be stored why???

### ISSUE THREAD

**Issue by telelauro** [OpenShot/openshot-qt#80]
every time we have to do a title we have to save them in a folder. I propose that it is always the same carpena or modifications are saved only in the project you are working at that time.
![titles always we have to save](https://cloud.githubusercontent.com/assets/16803007/12959181/a10d5fa0-d035-11e5-9988-02c307c6cc84.png)

**Comment by jarlarntzen** [comment]
:+1:

**Comment by BF3000** [comment]
:+1:

**Comment by jonoomph** [comment]
Yeah... this is an annoyance. I'll try to get to this soon. I have a pretty easy method of handling this - similar to the animated titles... which is, just store them in a temp folder, and copy them when the project is saved.
