### ISSUE TITLE
Error in playing audio mp3 files at time 2 '32''

### ISSUE THREAD

**Issue by vales** [OpenShot/openshot-qt#800]
* Operating System / Distro: Windows 10 16 Gb ram
* OpenShot Version: OpenShot-v2.3.4-3-gfe0f5f8-55-635-x86_64.exe daily

There is always an error in playing mp3 audio files at time 2 '32''

**Comment by JayMitsuru** [comment]
I have been experiencing this same issue. 
Operating System: Windows 7 Professional, SP1 64-bit, 16 GB RAM
OpenShot Version: 2.3.4

For what it's worth I can add that it doesn't happen with MIDI files. I have confirmed that the Mp3's are okay with WinAmp, VLC and WMP.  When setting the track to display the waveform, it's clear when the error will start.  In an attempt to be useful I'm adding a screenshot of what I'm talking about. 
![osv_mp3-error](https://user-images.githubusercontent.com/30485273/28651985-dec71b2c-7239-11e7-909d-14e39142a826.JPG)

**Comment by DylanC** [comment]
Dup of #618

**Comment by sphyrth** [comment]
The fact that this issue keeps duplicating means more people want it to be addressed. It's still an issue for me on
OpenShot 2.4.0
Linux Mint 18.2 32-bit, 4GB RAM

**Comment by DylanC** [comment]
I have been notified this has been fixed in the latest daily build. Please try it out.

**Comment by DylanC** [comment]
This is resolved in the latest daily build:
![solved](https://user-images.githubusercontent.com/4488048/31321108-155f4970-ac78-11e7-8783-0439def02c0e.png)

**Comment by JayMitsuru** [comment]
Confirmed today, yes: this is fixed. Thanks guys!

**Comment by vales** [comment]
I confirm. The latest daily release solved the problem.

https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.4.0-1-g8a71c3d-55-646-x86_64.exe
