### ISSUE TITLE
Crash when trying to slow down clip playback rate

### ISSUE THREAD

**Issue by tjsepka** [OpenShot/openshot-qt#802]
**System Details:
Motherboard:
Asus M5A99FX PRO 2.0 Rev 1.xx
BIOS: American Megatrends Inc. 2501 (04/07/2014)

CPU:
AMD FX-8350 Black Edition Vishera 8-Core 4.0 GHz (4.2 GHz Turbo) Socket AM3+ 125W FD8350FRHKBOX Desktop Processor

Memory: 
Total Size: 16384 MB
Type: Dual Channel (128 bit) DDR3-SDRAM

Graphics card: XFX RX-460P4TFG5 (4 Gbyte)

* Operating System: 64 bit Windows 10 Pro
* OpenShot Version: 2.3.4
* _Please attach log files if crash_  **** Where do I find the log files??? ****

**Issue Description and steps to reproduce:**
Right click on time, select Slow > Forward > 1/8X (or any value for that matter)
Windows says "launch.exe has stopped working"

**Comment by Yvand** [comment]
Hello, I get exactly the same problem, with same OS and same version of OpenShot

**Comment by Nodent** [comment]
Hello, I get exactly the same problem, same version of OpenShot
Microsoft Windows 10 Home
Version	10.0.14393 Build 14393
Processor	Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz, 3401 Mhz, 4 Core(s), 8 Logical Processor(s)
Installed Physical Memory (RAM)	8.00 GB

**Comment by DylanC** [comment]
Confirmed as fixed in #587 #588
