### ISSUE TITLE
Ubuntu Software Store - Ancient Version

### ISSUE THREAD

**Issue by MadMartian** [OpenShot/openshot-qt#803]
**System Details:**
* Operating System / Distro: Kubuntu 16.04
* OpenShot Version: 1.4.3

**Issue Description and steps to reproduce:**
The Ubuntu Software store is still posting the very ancient version 1.4.3 of OpenShot, which is a bit unstable.  I think it would be prudent to ask them to remove it from the store or post the up-to-date version so that window shoppers don't get the wrong idea.

**Comment by peanutbutterandcrackers** [comment]
@DylanC - I don't think this is on our part to perform an 'enhancement'. Perhaps you and I should both write to ubuntu developers regarding this? Perhaps ask them to have both OpenShot and OpenShot-QT in the app store, at the moment?

@MadMartian - Have you written to the Ubuntu Developers, good sir? Also, Openshot does have a [PPA](http://openshot.org/ppa), too.

**Comment by DylanC** [comment]
@peanutbutterandcrackers - True. Hopefully the Ubuntu devs will listen. I've had a poor experience trying to get projects into the store before.

**Comment by peanutbutterandcrackers** [comment]
@DylanC - Just wrote to the Ubuntu Package Maintainers. Let's see what happens. I think we can safely close this issue as it is not in our hands... @MadMartian - would you be so kind as to write an email to the Ubuntu and/or Debian package maintainers, regarding OpenShot 2.x? Thank you!

**Comment by peanutbutterandcrackers** [comment]
I just received a reply from a Ubuntu package maintainer. And, apparently, the newer version of OpenShot is in the repo for Ubuntu 18.04 alpha as openshot-qt. I wonder if it'll make it to the stable release. But yeah... If I get any further mails, I'll try to inform you guys here.

**Comment by peanutbutterandcrackers** [comment]
Great news! I just received a confirmation from the maintainer that OpenShot 2.x will make it to the stable release of Ubuntu 18.04!

@DylanC - Close-ble, perhaps, now? :)

**Comment by DylanC** [comment]
@peanutbutterandcrackers - Excellent! Thanks!  :)

**Comment by peanutbutterandcrackers** [comment]
@DylanC - Always happy to help my favourite project, in any small way that I can. :)

**Comment by shoogle** [comment]
#### OpenShot Debian Package (`openshot-qt`)

- __Tracker:__ https://tracker.debian.org/pkg/openshot-qt
- __Bugs:__ https://bugs.debian.org/cgi-bin/pkgreport.cgi?src=openshot-qt
- __VCS:__ https://salsa.debian.org/multimedia-team/openshot-qt
  - Patches: https://salsa.debian.org/multimedia-team/openshot-qt/tree/master/debian/patches

Patches show the changes that the Debian package maintainers have made to the upstream code. Often the changes are beneficial for everyone, not just Debian users, so the developers should consider making the same changes here.

**Comment by peanutbutterandcrackers** [comment]
@shoogle - Thanks! Are you involved with the Debian team too? Could the team also contribute to fix other bugs too? Could they makw pull requests on GitHub, too? This project really could use some more active developers.
