### ISSUE TITLE
Unhandled Exception: Stack Trace

### ISSUE THREAD

**Issue by Yo-kai-Sei-shin-kage** [OpenShot/openshot-qt#804]
**System Details:**
CPU ~ Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz
RAM ~ 8GB at 
GPU ~ Intel HD Integrated graphics; driver=i915

* Distro: Manjaro Linux (Arch based) Kernel 4.9 LTS
* System: Linux version 4.4.77-1-MANJARO
* OpenShot Version: 2.3.4
* Error Message:

Caught signal 11 (SIGSEGV)
---- Unhandled Exception: Stack Trace ----
---- End of Stack Trace ----
QObject::~QObject: Timers cannot be stopped from another thread.

**Issue Description and steps to reproduce:**
Internal memory error resulting in full app crash.

Steps to reproduce:
1.) Run openshot-qt in terminal
2.) Import  16 minute .wav audio file
3.) Import 13 min .ogv video file
4.) Fade entire track (audio and video) fast in and out.
5.) Settings for rendering:
     a.) Web profile
     b.) Flickr-HD 720 25fps
6.) Export

**Comment by DylanC** [comment]
@Yo-kai-Sei-shin-kage - Have you tried out the v2.4 daily build? Its much better with audio and may solve your crash.
