### ISSUE TITLE
I can´t add audio to my video or project

### ISSUE THREAD

**Issue by clovega** [OpenShot/openshot-qt#806]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

It does´t work for me in mp3 or mp4,when I try to reproduce the video with sound it says there are a problem and the program closes imediatly.

**Comment by DylanC** [comment]
Try out the v2.4 daily build.  Its much better with audio and may solve your issue. Thanks.
