### ISSUE TITLE
openshot.invalidCodec NVENC_h264

### ISSUE THREAD

**Issue by diamondburned** [OpenShot/openshot-qt#808]
**System Details:**
* Operating System / Distro: Ubuntu 17.04 running latest Openshot-qt
* OpenShot Version: 2.3.4

Some bonus details: I had `h264_nvenc` installed on both `ffmpeg` and `libav`. However, when I type that into Openshot, it says invalidCodec. However, on the original openshot on Ubuntu's main repository, it can still detect h264_nvenc.

**Issue Description and steps to reproduce:**
1. Compile ffmpeg+libav with nvenc
2. Export video with `h264_nvenc`/`nvenc_h264` in Video Codec

**Comment by DylanC** [comment]
Dup of #583
