### ISSUE TITLE
WINDOWS:  Blender will not render

### ISSUE THREAD

**Issue by telelauro** [OpenShot/openshot-qt#81]
I try to put a good path for the program, in inkscape I have to do well, but blender is not possible, and I open te animated tittles get this black window.
![blender no renderiza](https://cloud.githubusercontent.com/assets/16803007/12959377/6f118174-d036-11e5-95b0-7e453c7d9f6e.png)

**Comment by jonoomph** [comment]
Please retest in the latest daily build and re-open if the problem still occurs. Thanks!

**Comment by lew1s** [comment]
I have the same problem, all updated to latest version. Restarted many times.
