### ISSUE TITLE
Profiles

### ISSUE THREAD

**Issue by DarkSpartain** [OpenShot/openshot-qt#810]
Is it possiable to adjust the fps counter I record my vids at 720p 135 fps but the top fps counter for a preset profile is 60 is there a way to increase the fps ty

**Comment by DylanC** [comment]
@DarkSpartain - Not that I know of but I wouldn't be a very expert user. I'll leave this question open in case someone else knows how.

**Comment by DylanC** [comment]
@DarkSpartain - See this link:
http://www.openshot.org/static/files/user-guide/profiles.html#custom-profile
