### ISSUE TITLE
Move frame by frame in timeline not working for Mac

### ISSUE THREAD

**Issue by ematitan** [OpenShot/openshot-qt#811]
Hello

1) How can we move "frame by frame" in the timeline of Openshot?
(I'm using the arrows but it doesn't work)

2) How can we "jump" from one clip to the next in the timeline of Openshot?
(using command I can go to the end or beginning of a selected clip, but that's it)

**System Details:**
* Operating System / Distro: MacoS Sierra 10.12.6
* OpenShot Version: 2.3.4

**Issue Description and steps to reproduce:**

**Comment by Tanny2** [comment]
I have the same question.  How to move frame by frame?  

Also, is there a way to step from keyframe to keyframe?

Thanks!

Operating System / MacOSX Yosemite
OpenShot Version: 2.3.4

**Comment by Tanny2** [comment]
In preferences/keyboard I see...

Next Frame = Right

Right what?  Right arrow?

Does "Next Marker" mean next keyframe?

I've tried everything I can think of for navigating frames and keyframes.  Control everything, option everything, command everything.  The only thing that works is command right arrow/left arrow, for navigating to very beginning or very end of timeline.

I'm guessing this was coded for Windows and never adapted for the Mac?

**Comment by Tanny2** [comment]
This page....

http://www.openshotvideo.com/2009/05/frame-stepping-key-mappings.html

...clearly says that advancing the timeline frame by frame using the arrow keys has been a feature since 2009.  Simply doesn't work for me, no idea why.  MacOSX/Yosemite

**Comment by DylanC** [comment]
@Tanny2 - That link is for the older version. I will investigate the new one and find out if we can still do this.

**Comment by DylanC** [comment]
@ematitan  Not supported just yet. It has already been suggested as an enhancement.

**Comment by FunnyLadyMars** [comment]
Really want to support open-source. Was looking forward to trying OpenShot on my Mac but without the ability to step frame by frame, the program is basically useless to me though.   Already uninstalled. :(  I hope this essential feature is added so I can try again....

**Comment by N3WWN** [comment]
@FunnyLadyMars Stepping frame by frame is supported in 2.4.x (and possibly older releases, but I have no experience older than the newer 2.3.x versions.  FYI, stepping worked there, too 😁 ).  

Add your clip to the timeline, move the playhead to your area of interest using either left or right mouse clicks in the top area of the timeline with the time markers, then use the left and right arrow keys to step frame-by-frame.

**Comment by Tanny2** [comment]
@FunnyLadyMars - I solved this by moving to Hitfilm, they have both free and paid versions.  Free version working great for me.

PS: I'm guessing this frame by frame issue in OpenShot is only a problem for Mac users.

**Comment by FunnyLadyMars** [comment]
@N3WWN per the earlier thread comments, the arrow keys do **not** work to step frames in the version for Mac, and are only supported for Mac in an older release from 2009. :( 

@Tanny2 , I'll investigate Hitfilm, thanks for the suggestion, AND for looking into this issue back in 2017.  The thread saved me a lot of insanity....

**Comment by FunnyLadyMars** [comment]
@DylanC,  I saw the issue was closed a while back.
Do you know if there is any chance the arrow step frames function will be added, or should I give up trying to use Open Shot? That ability is essential to me.

**Comment by N3WWN** [comment]
@FunnyLadyMars I apologize... I completely missed that the issue was unique to the Mac version.  I should have comprehended that when I read the thread. 😀

**Comment by DylanC** [comment]
@FunnyLadyMars - This was a question type of issue and the questions were answered. (hence why it was closed)  It was not confirmed as an issue.  This feature already exists in 2.4.x. 

Perhaps this is only an issue on Mac. I can test on my own Mac if you wish, to try to confirm the issue.

**Comment by drukepple** [comment]
Same issue for me, using a Mac. I found that if you re-bind "Next/Previous Frame" to something other than "Left" and "Right," it works.  Weird you have actually type "Ctrl+" instead of just pressing the desired key combination, and also weird that "Ctrl" is actually "Cmd" on a Mac.  But it would seem that the default value of "Left" does not map to the left arrow key on a Mac.

**Comment by DylanC** [comment]
@drukepple - Thanks. I have also seen this on my Mac. Confirmed as a bug.

**Comment by peanutbutterandcrackers** [comment]
@singalen - This seems like a good issue to resolve in your first PR, BTW. :)

**Comment by N3WWN** [comment]
I can confirm that the arrow keys still do not work on Mac OS (using 2.4.2).

**Comment by Openstreetmapler** [comment]
I solved the problem by assigning the frame-by-frame advance to the `O` and `P` keys and then restarting OpenShot.

**Comment by XanderLeaDaren** [comment]
Any news on fixing this strange behaviour on macOS?

Of course biding to other keys is a (temp) solution, but having the ability to use left/right is the obvious expected way to go.

**Comment by YumaVlaicu** [comment]
I have the same issue also on macOS 10.15.4 (Openshot 2.5.1 / libopenshot 0.2.5)
It works when I change key binds to other keys like Q and W.

**Comment by N3WWN** [comment]
We should probably keep this open as it's an ongoing issue with our Mac users.

**Comment by FunnyLadyMars** [comment]
Agree. Thank you.
Tho allegedly there's a fix by remapping to any keys that aren't the left
and right arrow buttons.

I just haven't tried it to confirm

**Comment by USATechDude** [comment]
@ferdnyc provided workaround
Duplicate: Issue #3760

**Comment by sina66** [comment]
Hi.

I hope the problem with the arrow keys is resolved soon.
it is really impractical and has cost me a lot of time to find a temporary solution. Hopefully there will be no temporary solution and will be fixed :-)
I put the arrow "left" and "right" on the keys O and P.
Too bad that you can't enter the "alt-code".
Code for Left Arrow = 26
and for arrow right = 27


My OS X 10.13.6
Openshot 2.5.1 / libopenshot: 0.2.5


Best Regards

Translated by Google

**Comment by bleurose** [comment]
This issue needs to be reopened.  There is no real reason that you can't support the left and right arrows on Mac.  I am also having this problem and using letter keys for moving the timeline is barely acceptable (feels like going back to the '90s :-(

**Comment by charliemacquarie** [comment]
Just chiming in that this issue has come up for me too and I'd love for the issue to be reopened and addressed as it would really help the usability. Thank you!

**Comment by franklinewt** [comment]
I just loaded openshot 3.0.0 on Mac OS Ventura 13.0.1 and by default, the next frame is assigned to W and previous is assigned to Q which does allow you to step frame by frame. The documentation doesn't say that but if you open preferences and click on the keyboard tab, you will see how the frame step commands are defined.
