### ISSUE TITLE
Change the language "Animated name"

### ISSUE THREAD

**Issue by Ukol1** [OpenShot/openshot-qt#813]
**System Details:**
* Linux Manjaro - Mint
* OpenShot 2.3.4
Hello.
How to make an animated font name in Russian? I use Linux Manjaro, by default the Bfont font is set. In /openshot_qt/blender/dissolve.hml I slipped my fonts, but all without result. Blender understands the Russian language.

**Comment by Ukol1** [comment]
Write where the font settings are stored ...? I'll do it myself. In some animations, only Bfont works. I will be preemptive, for help.

**Comment by DylanC** [comment]
@Ukol1 - I think we don't have an option for this just yet.
