### ISSUE TITLE
Where is the documentation? Poorly documented, prone to crashes

### ISSUE THREAD

**Issue by shersk2** [OpenShot/openshot-qt#814]
**System Details:**
* Operating System / Distro: Xubuntu 16.04
* OpenShot Version: 2.3.4

**Issue Description and steps to reproduce:**

The issue I have is that I want to read about how to use this program. In other words: Where is the user manual? It seems to be a bit difficult to find answers to specific tasks, at least by following the links provided on the openshot website.

For example, the developers have made Openshot able to pan and zoom a photo. But -- where is the user manual?  Where is it explained how to use these functions?

A specific bug: I was in the process of creating my own profile, and had open a file in the .openshot-qt/profiles directory, then I rebooted, and my editor vi left a temporary file in that directory. When I tried to restart openshot, it immediately crashed (segfault). I spent a lot of time reading crash logs etc, until I remembered that this new profile file might have caused it. After I deleted that file, I was able to start openshot again. 

I have also had many other crashes.

**Comment by Tanny2** [comment]
Here you go:

http://www.openshot.org/static/files/user-guide/main_window.html#tracks-layers

**Comment by shersk2** [comment]
If I place a clip on the timeline, then right click on it, the menu shows a choice for "Transform". That seems interesting. It appears to be a way to use point-and-click (mouse) to create an animation. Where is that documented in the user guide, if I may ask?

**Comment by Tanny2** [comment]
Yes, transform is what's hooked me as well.   Here's the link:

http://www.openshot.org/static/files/user-guide/clips.html?highlight=transform#transform

Example:  Use transform to change size of clip.  Then advance along the timeline and change size of clip again.  Keyframes are automatically created where you made your edits, and your clip will morph from one size to another as it proceeds from one keyframe to the next.

Also, I just came across an old version of the manual (for a previous version of OpenShot) Perhaps it might prove helpful in some instance.

http://www.openshotusers.com/help/1.3/en/

**Comment by shersk2** [comment]
Thanks. Do you have any advice for how to avoid cluttering of clips during the editing process? How to place the cutaways somewhere temporarily in case I decide later that I want to use some part of a clip that I cut.

**Comment by Tanny2** [comment]
Perhaps you could move them to the area on the upper left of the interface, where clips first appear when you import them in to the program.  Sorry, I forget what that area is called.

**Comment by DylanC** [comment]
Question has been answered above.
