### ISSUE TITLE
Can openshot blur parts of a video?

### ISSUE THREAD

**Issue by sbhesser** [OpenShot/openshot-qt#815]
Is there a way openshot can blur parts of a video?

**Comment by Ghostboy-287** [comment]
looking for the same thing, it will be cool if they add that feature like in camtasia and also adding the capacity to zoom the video that we are editing to be able to blur the right part

**Comment by DylanC** [comment]
@sbhesser - Not at the moment but it may be a good feature to add in the future.

**Comment by Quix0r** [comment]
"Might be a good feature"? If you do educational or something like I do, a "Let's Develop", you record your screen (with e.g. OBS) and certainly want users not to see all of it. It is very common then to pixelate or blur area of the screen like taskbar or personal data. This is a must-have feature should not be missed in any good video-editing software.

**Comment by partridge420x** [comment]
They still haven't implemented an easy way to do this. and as someone who records around sensitive information, Its become too hard to use.
