### ISSUE TITLE
Support for all GoPro shooting modes?

### ISSUE THREAD

**Issue by importon** [OpenShot/openshot-qt#818]
**intel i7 16gb ram gtx970**
* windows 7 ?
* latest at time of posting?
* _Please attach log files if crash_

When I import gopro footage shot at 120fps it says in the properties that it is 9999 fps.  Can the composition settings be changed to accomodate this framerate?  Can we make custom profiles?

**Comment by DylanC** [comment]
@importon - I have seen people making custom profiles so it must be possible. I think they are just editing a custom file in the folder location of the profiles and then OpenShot loads in all those profiles from that folder.

**Comment by DylanC** [comment]
@importon - http://www.openshot.org/static/files/user-guide/profiles.html#custom-profile
