### ISSUE TITLE
Language Issue....

### ISSUE THREAD

**Issue by riggie11** [OpenShot/openshot-qt#819]
Hi Jonathan,

I use a standard english Windows 10 machine and have Open Shot Ver 2.3.4 and live in Germany,

After the installation, OpenShot automatically showed me the German version, even though I chose 
"English" before the installation.

I then went to the Edit -> Preferences section and chose "American English", and re-started Openshot, but
the German version still appeared.... only after choosing The British or Australian English, did Openshot give me the english version :-)

Thanks for this fantastic software. 
-Riggie

**Comment by DylanC** [comment]
Dup of #331

**Comment by DylanC** [comment]
As confirmed in #331.

> Changing interface language to American English works fine in OpenShot-v2.4.1-34-g6a9257e-59-685.

Can someone confirm this here too?

**Comment by DylanC** [comment]
Confirmed as fixed in #331.
