### ISSUE TITLE
Video Export hangs while encoding to MP4

### ISSUE THREAD

**Issue by kurkosdr** [OpenShot/openshot-qt#82]
There is this nasty bug: When user tries to encode to MP4 (happens regardless of chosen framerate, and even when video framerate matches the input video, and on a variety of resolutions from NTSC to 1080p), OpenShot hangs (=completely stops responding) at a random percentage of the procedure

Please note that if you cut a really short video and the encoder process makes it (by chance) to the end without hanging, the resulting video is playable by VLC and is actually quite good.

My OS is Windows 10 64-bit. Don't know if it's OS-related though.

Wish I could provide some debug info and crash dump but I don't know how.

PS: Possible duplicate of #62, the dude who opened that bug didn't even bother to insert a brief description.

**Comment by komackaj** [comment]
Hi,
I've replicated the issue on Debian Jessie with clean builds of libopenshot* from today's master and current openshot-qt. 

First I've imported a 50-mins video, cut it to about 20 seconds, saved project as test.osp and closed openshot. Then I've run it again with logging stdout+err to file - loaded the project, invoked Export dialog, used HD 720p 29.97fps profile with quality set to low.
Until 77% everything was smooth, then export froze (with 3.5G/8G RAM eaten and 1.7 MB written). Then export either completed (log - http://pastebin.com/YFxVcDfN) or crashed (log - http://pastebin.com/qyQsFDWN) - I've tried multiple times. The same happened with high quality.

Let me know if there is anything else I can try to diagnose the problem, I'll be glad to help.

**Comment by ZackTheCardshark** [comment]
I'm a Mac user (El Capitan) who just discovered OpenShot, and would like to like it—but the program hangs every time I try to export. It seems to be this issue, or https://github.com/OpenShot/openshot-qt/issues/119. This is kind of the ultimate showstopper of a bug; is anybody looking into it?

BTW, also cross-posting to similar issues, since all of them are still open: https://github.com/OpenShot/openshot-qt/issues/119 and https://github.com/OpenShot/openshot-qt/issues/179

**Comment by madscientist159** [comment]
I ran into this as well under Debian Squeeze using the latest sources from the stable PPA.

**Comment by CorvusSG** [comment]
I'm getting a very similar problem on the current version of Openshot (2.1.0) on the 64 bit version of Windows 10. I'm not sure if it is different enough to open a new issue. I have been trying to export a ~30min video using the YouTube-HD setting. The exporter reached 29% and then simply stopped without errors. I left it overnight just in case but that is as far as it got. It isn't crashing but it isn't finishing the export either - it just stops responding over and over.

My machine is a 6 month old i7-6700 with 16Gb RAM and the videos are games recorded with OBS Studio (0.15.4). Windows is up to date with the latest patches.

**Comment by MMesch** [comment]
similar issue on ubuntu 16.04 with the standard repository openshots. Video export to mp4 hangs at 34%

**Comment by IHaveADrone** [comment]
Openshot 2.2.0 on windows 10 here.  I can export 64% before hanging.

**Comment by TombyT** [comment]
If im lucky I can export a short video. Intermittent program hangs are seen but may resume and make it until the end but often the system never recovers.  Did get it to export once and video quality was mostly good though audio in general seemed low quality and parts of video were inexplicably slowed down.

**Comment by hollowdoor** [comment]
Same here on Linux, but it only gets up to 5% usually. I have 10.8GB of memory, and a quad core.

**Comment by sebasmagri** [comment]
This happens to me with any format after splitting and setting time at 2x for the second split of a segment.

**Comment by DylanC** [comment]
@kurkosdr - Does this issue still happen for you?

**Comment by DylanC** [comment]
Closing for now until we get some new activity on this.

**Comment by Simnol** [comment]
Getting this on macOS High Sierra.

**Comment by noozo** [comment]
Getting this on Manjaro Linux.

**Comment by JacksonRG** [comment]
@noozo Could you attatch [logs](https://github.com/OpenShot/openshot-qt/wiki/Issue-Logging) That will help me get an idea of how to help you.
