### ISSUE TITLE
ProRes and DNxHD profiles / render

### ISSUE THREAD

**Issue by zebulon888** [OpenShot/openshot-qt#820]
**System Details:**  Windows / Linux / MAC
* Operating System / Distro: ANY
* OpenShot Version: 2.3.4
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

I would like to render to PRORES or DNXHD. But creating or changing the presets does nothing - it would not render to PRORES or DNXHD.
Is there a way to render to DNxHD or ProRes?

**Comment by DylanC** [comment]
@zebulon888 - Not at the moment. It may be added in a future version.
