### ISSUE TITLE
Openshot audio crash

### ISSUE THREAD

**Issue by Nafion13** [OpenShot/openshot-qt#821]
**System Details:**
cpu:                                                            
                       Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz, 1794 MHz
                       Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz, 1800 MHz
                       Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz, 1796 MHz
                       Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz, 1715 MHz
keyboard:
                       Cherry Keyboard
                       Razer Copperhead Mouse
monitor:
                       SAMSUNG SMBX2450
graphics card:
                       Intel 2nd Generation Core Processor Family Integrated Graphics Controller
                       nVidia GF114 [GeForce GTX 560 Ti]
sound:
                       Intel 7 Series/C210 Series Chipset Family High Definition Audio Controller
                       nVidia GF114 HDMI Audio Controller
                       GYROCOM C&C DigiHug USB Audio
storage:
                       Intel 7 Series/C210 Series Chipset Family 6-port SATA Controller [AHCI mode]
network:
  eth0                 Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
network interface:
  eth0                 Ethernet network interface
  lo                   Loopback network interface
disk:
  /dev/sda             SAMSUNG SSD 830
  /dev/sdb             Maxtor 7L300S0
  /dev/sdc             Maxtor 6V250F0
  /dev/sdd             Crucial_CT120M50
partition:
  /dev/sda1            Partition
  /dev/sda2            Partition
  /dev/sdb1            Partition
  /dev/sdb2            Partition
  /dev/sdc1            Partition
  /dev/sdd1            Partition
  /dev/sdd2            Partition
  /dev/sdd5            Partition
cdrom:
  /dev/sr0             HL-DT-ST BD-RE  BH10LS30
usb controller:
                       Intel 7 Series/C210 Series Chipset Family USB xHCI Host Controller
                       Intel 7 Series/C210 Series Chipset Family USB Enhanced Host Controller #2
                       Intel 7 Series/C210 Series Chipset Family USB Enhanced Host Controller #1
bios:
                       BIOS
bridge:
                       Intel 2nd Generation Core Processor Family DRAM Controller
                       Intel Xeon E3-1200/2nd Generation Core Processor Family PCI Express Root Port
                       Intel 7 Series/C210 Series Chipset Family PCI Express Root Port 1
                       Intel 82801 PCI Bridge
                       Intel 7 Series/C210 Series Chipset Family PCI Express Root Port 6
                       Intel Z77 Express Chipset LPC Controller
                       ASMedia ASM1083/1085 PCIe to PCI Bridge
hub:
                       Linux Foundation 2.0 root hub
                       Linux Foundation 3.0 root hub
                       Realtek 4-Port USB 2.0 Hub
                       Linux Foundation 2.0 root hub
                       Intel Integrated Rate Matching Hub
                       Linux Foundation 2.0 root hub
                       Intel Integrated Rate Matching Hub
memory:
                       Main Memory
unknown:
                       FPU
                       DMA controller
                       PIC
                       Keyboard controller
                       Intel 7 Series/C210 Series Chipset Family MEI Controller #1
                       Intel 7 Series/C210 Series Chipset Family SMBus Controller
                       Serial controller
                       Cherry Unclassified device
                       Razer Copperhead Mouse
                       GYROCOM C&C DigiHug USB Audio

* Operating System / Distro: ?
Ubuntu 16.04 LTS

* OpenShot Version: ?
2.3.4

* _Please attach log files if crash_
[log.txt](https://github.com/OpenShot/openshot-qt/files/1196855/log.txt)

**Issue Description and steps to reproduce:**
It doesn't mind what i do - openshot crashes after a few minutes. I tried a several versions now and every version crashes! :(

**Comment by DylanC** [comment]
@Nafion13 - Can you reproduce after a specific action? We need some more details to test this.

**Comment by DylanC** [comment]
For now I have extracted this from the log provided for the devs:

Language set - DE.

logger_libopenshot:INFO FFmpegReader::GetAudioPTSLocation (Audio Gap Detected) (Source Frame=4946.0000, Source Audio Sample=1152.0000, Target Frame=4946.0000, Target Audio Sample=1152.0000, pts=9495552.0000)
Caught signal 11 (SIGSEGV)
---- Unhandled Exception: Stack Trace ----
logger_libopenshot:INFO FFmpegReader::ProcessAudioPacket (Before) (requested_frame=4949.0000, target_frame=4946.0000, starting_sample=1152.0000)
Memory access error (memory dumped)

**Comment by DylanC** [comment]
@Nafion13 - What audio format did you use?

**Comment by Nafion13** [comment]
Not really. Normally it crashes when i use the timeline. But even when i haven't used it it has crashed several times.

**Comment by Nafion13** [comment]
Doesn't mind i've used the original mp4 file and i also tried one recoded as mp3 from audacity.

**Comment by DylanC** [comment]
@Nafion13 - I would recommend to try v2.4. Lots of bugs have been fixed in this area.

**Comment by maxlefou** [comment]
I'm on 2.4.4 and still having this problem
