### ISSUE TITLE
MP4 Banned and Help "Not found"

### ISSUE THREAD

**Issue by jabowery** [OpenShot/openshot-qt#823]
Windows 7, OpenShot 2.3.4

Opened an MP4 as project file.  Attempted to drag it to a track.  Banned icon appeared (red circle with red line across).  Unable to add to a track.  

Click on Help->Contents -> Search Docs
Enter "mp4"
"Your search did not match any documents."

Uninstalling OpenShot

**Comment by DylanC** [comment]
Could not reproduce this issue. Please try v2.4.
