### ISSUE TITLE
Import not selected file to the timeline via hot CTRL-W

### ISSUE THREAD

**Issue by ELForcer** [OpenShot/openshot-qt#824]
**System Details:**
* Operating System / Distro: Linux Mint 18.2
* OpenShot Version: 2.3.4

If you select a file with the left mouse button and press CTRL-W, you will be prompted to import another file that was imported the last time. However, if you call the context menu on the same file and press CTRL-W, the file will be imported.

![2017-08-07 15-34-29](https://user-images.githubusercontent.com/30798063/29026851-f020dfee-7b8e-11e7-8ddc-dcb6cb27a516.png)

**Comment by DylanC** [comment]
@ELForcer - Thanks for the report. I hope to test this soon.

**Comment by speedytechdev** [comment]
@DylanC Is this a bug or can we close it?

**Comment by chhh** [comment]
This is still a bug in v 2.5.1
