### ISSUE TITLE
Cannot add subtitle

### ISSUE THREAD

**Issue by tif0313** [OpenShot/openshot-qt#827]
**System Details: Windows 7
* Operating System / Distro: Win 7
* OpenShot Version: 2.3.4

**Issue Description and steps to reproduce: 
I was trying to add subtitles onto the track, and while I selected subtitle template and edit the text, hit "save", then a error popped out says: .svg is not a valid image, video file format.....

please let me know how to debug this error or any plugin i should install.... THX!

**Comment by DylanC** [comment]
Dup of #632

**Comment by DylanC** [comment]
@tif0313 - This sounds like an issue with the characters used in the file. I would recommend to try this daily as the problem is solved in it.
