### ISSUE TITLE
How to create with OpenShot such a video?

### ISSUE THREAD

**Issue by KrisztaHPE** [OpenShot/openshot-qt#828]
**System Details:** WIN10
* OpenShot Version: ? Latest
http://media.now.hpe.com/program.aspx?key=NOKMRJIJEL
There is a video starting at 3:00 - is this possible to be created with OpenShot?
I wish to have 9 clickable videos on one screen basically or to have those 9 videos popping up one-by-one. 

Thanks a lot, Kriszta

**Issue Description and steps to reproduce:**

**Comment by DylanC** [comment]
Not possible at the moment. Thanks.
