### ISSUE TITLE
Minor: Linux upgrades (daily) trigger long-lasting "Processing triggers for shared-mime-info"

### ISSUE THREAD

**Issue by beat** [OpenShot/openshot-qt#83]
This is a minor annoyance, but makes daily upgrades run slowly on Linux.

**Comment by jonoomph** [comment]
Thanks for the comment. I might end up moving these commands somewhere else (moving them out of the setup.py), but they will still likely be called during an install. I'm open to suggestions. I'm going to go ahead and close this ticket, but feel free to re-open if you have more to add. Thx.
