### ISSUE TITLE
cache memory works strange

### ISSUE THREAD

**Issue by FraYoshi** [OpenShot/openshot-qt#831]
**System Details:**
OS: Arch Linux 
Kernel: x86_64 Linux 4.12.4-1-ARCH
Uptime: 37m
Packages: 1355
Shell: bash 4.4.12
Resolution: 1920x1080
DE: XFCE4
WM: Xfwm4
WM Theme: Microcurve
GTK Theme: Xfce-flat [GTK2]
Icon Theme: Adwaita
Font: Schumacher Clean 10
CPU: Intel Core2 Quad Q9550 @ 4x 2.83GHz [35.0°C]
GPU: GeForce GTX 1050 Ti
RAM: 6650MiB / 7987MiB

* OpenShot Version: 2.3.4

**Issue Description and steps to reproduce:**

Change the memory allocation on the Edit > Preferences > Cache tab to 2048 MB
keep something playing on the timeline keeping an eye to the memory usage. It hits 5700 MiB.

Change the memory allocation to 512 MB... It hits 1900MiB

seems like something is wrong with this parameter or not clear what It refers to.

**Comment by DylanC** [comment]
Dup of #563

**Comment by DylanC** [comment]
@FraYoshi  - This parameter is the cache for the video preview. It will make playback of the preview more smooth if you have a smaller cache and good settings for it. 

It does not relate to the memory usage of the program.
