### ISSUE TITLE
MP4 Audio doesn't work

### ISSUE THREAD

**Issue by solemar** [OpenShot/openshot-qt#832]
Windows 10 64 bits with latest version of Openshot (though the problem was present on the last version also.

Whenever I try to use the Video Preview of MP4 files, the audio doesn't work. In fact, the audio doesn't work in general in Openshot. I can see that it is producing audio but it doesn't sound at all.

**Comment by procod3R** [comment]
same here

**Comment by luciabal** [comment]
same problem here

**Comment by DylanC** [comment]
@solemar -  I would give the v2.4 daily build a try. It has fixed some major audio issues for people.

**Comment by DylanC** [comment]
Could not reproduce on the v2.4 daily build.
