### ISSUE TITLE
blender is not working when using openshot in mac

### ISSUE THREAD

**Issue by thunderboympm** [OpenShot/openshot-qt#833]
**System Details:**
* Operating System / Distro: MAC OSX El Caption (10.11.6)
* OpenShot Version: 2.3.4
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
I completed the installation process, and the software is working good. i download the blender version 2.78 and installed it. it is working good. I completed the blender command path with my blender location (i copied it to my application folder, so the path will be /Applications/Blender.app). For my animated title, the blender is not opening. the error message box is attaching below. it says that 

> Blender the free open source 3D content creation suite is required for this action (http://www.blender.org).
> Please check the preferences in OpenShot and be sure the Blender executable is correct.  This setting should be the path of the 'blender' executable on your computer.  Also, please be sure that it is pointing to Blender version 2.78 or greater.

> Blender Path:

> /Applications/Blender.app

<img width="1280" alt="screen shot 2017-08-13 at 8 17 04 am" src="https://user-images.githubusercontent.com/6202742/29245085-8228675c-8000-11e7-8574-a74c84007e6d.png">

**Comment by zimmxbz** [comment]
I am having the same problem. when I set the correct path to blender, I still get the popup stating blender is required. Mac 10.10.5, OpenShot 2.3.4

**Comment by DylanC** [comment]
@thunderboympm - Try the path:

/Applications/Blender/blender.app/Contents/MacOS/blender

**Comment by armaanarvind** [comment]
Thanks @thunderboympm
