### ISSUE TITLE
UI language not respecting choice during installation

### ISSUE THREAD

**Issue by clauswobbe** [OpenShot/openshot-qt#834]
**System Details:**
* Win10 64 bit
* OpenShot Version: 2.3.4
* 

**Issue Description and steps to reproduce:**
My very first installation. During installation I was asked which language to use for UI. My system language is Danish, my Win 10 is in Danish, but I selected English. However, when I opened OpenShot, UI was in Danish.

UPDATE:
Even when I select American English under Settings and restart the programme, it keeps "System" = (Danish) as UI.

![image](https://user-images.githubusercontent.com/4347320/29250318-fe67f22a-8040-11e7-9b2f-a0158a9ab8a8.png)

**Comment by thelaith** [comment]
I am having the same issue. It appears if you change it to British English (en_GB) it works fine, but that's not a selectable option in the installer.

Also, is there any install arguments that sets en_GB as default language? and sets a shortcut as well?

**Comment by DylanC** [comment]
Dup of #331

**Comment by DylanC** [comment]
As confirmed in #331.

> Changing interface language to American English works fine in OpenShot-v2.4.1-34-g6a9257e-59-685.

Can someone confirm this here too?

**Comment by DylanC** [comment]
Confirmed as fixed in #331.
