### ISSUE TITLE
Aspect Ratio incorrect for Video Preview.

### ISSUE THREAD

**Issue by trosanelli** [OpenShot/openshot-qt#835]
**System Details:**
* Operating System / Distro: ? Ubuntu 17.04
* OpenShot Version: ? 2.3.4
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
I set the video profile to HD 1080p 25 fps. I place my videos clips in the project file. The video clips are a .MTS format. When I add them to the track or preview them from the project files. The video is elongated like the aspect ratio is off.

**Comment by DylanC** [comment]
@trosanelli - Any luck with the latest daily builds?

**Comment by vitaly-zdanevich** [comment]
The same for me too, mpeg video. You can get example file here
https://cloud.mail.ru/public/4ksS/zt6oPGPaH

**Comment by trosanelli** [comment]
DylanC - I was unaware of the daily builds. I will try it out and let you know.

**Comment by DylanC** [comment]
@trosanelli - Thanks. Do let us know.

**Comment by trosanelli** [comment]
@DylanC - I just checked it with the daily build and still does the same thing. I was using Openshot 1.4.3 and it worked fine when I upgraded to the current version I started having the problems.

**Comment by DylanC** [comment]
@trosanelli  - No problem. Thanks for the feedback.
