### ISSUE TITLE
Intermittant crash on export to mp4

### ISSUE THREAD

**Issue by petep** [OpenShot/openshot-qt#836]
**System Details:**
* Operating System / Distro
Fedora 25 64bit

* OpenShot Version:
openshot-2.3.3-1.fc25.noarch (from RPMfusion)

* _Please attach log files if crash_
[AudioData @ 0x7f62530136f0] invalid NULL pointer for src[0]
Caught signal 11 (SIGSEGV)
---- Unhandled Exception: Stack Trace ----
   /lib64/libopenshot.so.11       ( openshot::FFmpegReader::Close()   + 0x53c )  [0x7f63469575bc]
   /lib64/libopenshot.so.11       ( openshot::FFmpegReader::Seek(long)      + 0x680 )  [0x7f6346958bf0]
   /lib64/libopenshot.so.11       ( openshot::FFmpegReader::GetFrame(long)    + 0xa5b )  [0x7f634695fdfb]
   /lib64/libopenshot.so.11       ( openshot::FrameMapper::GetOrCreateFrame(long)  + 0x2e9 )  [0x7f634697b589]
   /lib64/libopenshot.so.11       (       + 0xa734d)  [0x7f634697e34d]
   /lib64/libgomp.so.1            (       + 0x16de6)  [0x7f6343783de6]
   /lib64/libpthread.so.0         (       + 0x773a)  [0x7f63693b573a]
   /lib64/libc.so.6               ( clone       + 0x3f  )  [0x7f63689dfe0f]
---- End of Stack Trace ----
Caught signal 11 (SIGSEGV)
---- Unhandled Exception: Stack Trace ----
   /lib64/libQt5DBus.so.5         (       + 0x29570)  [0x7f63551c7570]
   /lib64/libQt5DBus.so.5         (       + 0x180f2)  [0x7f63551b60f2]
   /lib64/libQt5Core.so.5         (       + 0xa69ca)  [0x7f635ba1c9ca]
   /lib64/libpthread.so.0         (       + 0x773a)  [0x7f63693b573a]
   /lib64/libc.so.6               ( clone       + 0x3f  )  [0x7f63689dfe0f]
---- End of Stack Trace ----
QObject::~QObject: Timers cannot be stopped from another thread

**Issue Description and steps to reproduce:**
Sometimes when exporting a project to mp4, a crash occurs with the above trace.

The following parameters are used:
Profile: Blu-ray/AVCHD
Target: AVCHD disks
Video Profile: HD 1080p 25 fps (1920x1080)
Quality: High

**Comment by DylanC** [comment]
@petep - Does this happen in the v2.4 release?

**Comment by petep** [comment]
Sorry I haven't tried that. 2.3.3 is the default package supplied with Fedora 26:

# cat /etc/redhat-release 
Fedora release 26 (Twenty Six)
# dnf list openshot
Last metadata expiration check: 1:21:00 ago on Mon 18 Sep 2017 14:15:42 BST.
Available Packages
openshot.noarch                   2.3.3-1.fc26                    rpmfusion-free

It's supplied by the RPMfusion project.

**Comment by DylanC** [comment]
@petep - No problem. I can try on Fedora 26 with v2.4.

**Comment by petep** [comment]
RPMfusion upgraded to 2.4 today and so far it seems to be much more stable and have fixed the original problem. I'll report again in a few days once we've used it a bit more.

**Comment by petep** [comment]
All looks great since the upgrade to 2.4. Thanks for your help!

**Comment by DylanC** [comment]
@petep - Sounds good. Thanks for getting back to me.
