### ISSUE TITLE
Not Responding, Lags, Crashes in Windows 7

### ISSUE THREAD

**Issue by jsztyler** [OpenShot/openshot-qt#837]
I'm using windows 7 and OpenShot is constantly working slow, locking up and not responding. During the editing process it lags and is super slow with a 15-40 second delay time to play the video in edit mode. It has taken me 3 hours to complete a video that normally would take 1-hour then the program crashed on me and I lost the entire project! I'm using version 2.3.4
I'm not sure how to find the log files from the recent crash?
The program has crashed about 6x on me between last night and today.

**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

**Comment by petesimon** [comment]
I have similar problems with v2.3.4 (normal release, and daily release versions) in Windows 10 1703 64bit.

**Comment by jsztyler** [comment]
You may find it works best in Linux!

**Comment by DylanC** [comment]
Not enough details to test this issue. Details and logs are required. Thanks.

**Comment by petesimon** [comment]
(quote) Not enough details to test this issue. Details and logs are required. Thanks. (quote)

Please tell us how to do that.

**Comment by DylanC** [comment]
@petesimon 

Fill in the system details and a description of **exactly** how to reproduce the issue. 

> 
> System Details:
> 
> Operating System / Distro: ?
> OpenShot Version: ?
> Please attach log files if crash
> Issue Description and steps to reproduce:

Logs should also be attached:

The logs you can find the in same folder as the OpenShot preferences. 

**Linux/Mac**
HOME/.openshot_qt/openshot_qt.log

**Windows**
/Users/USERNAME/.openshot_qt/openshot_qt.log
