### ISSUE TITLE
Imported SVG file treated correct in 1.4.3, bad in 2.3.4

### ISSUE THREAD

**Issue by huubvanniekerk** [OpenShot/openshot-qt#838]
**System Details:** 
* Operating System / Distro: Linux / Fedora25 / Mint 17.2
* OpenShot Version: 1.4.3 vs. 2.3.4.
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
vs. 1.4.3 isn't available on Fedora 25, so have to use latest version.
Steps: import SVG file created with Inkscape, e.g. vs. 0.91. Then difference is already visible: in 1.4.3 full text in SVG is all there, while in 2.3.4, only first line shows. After adding to timeline is the same difference. In 1.4.3, full text of 5 lines SVG files is visible, in 2.3.4, only the first line is visible.
![screenshot-openshot-143_svg](https://user-images.githubusercontent.com/13077765/29458930-bfe5727c-8421-11e7-9d6b-9b597ab2ba89.png)
![screenshot-openshot-234-svg](https://user-images.githubusercontent.com/13077765/29458931-bfe6ee90-8421-11e7-9624-a3efd9e059cb.png)

**Comment by DylanC** [comment]
@huubvanniekerk - Can you attach the SVG file used please?

**Comment by huubvanniekerk** [comment]
@DylanC - The zip file contains 2 files with the same text, just 1 with black fontcolour, other has white fontcolour.

[Openshot-test-text.zip](https://github.com/OpenShot/openshot-qt/files/1256920/Openshot-test-text.zip)

**Comment by DylanC** [comment]
@huubvanniekerk - Thanks!

**Comment by DylanC** [comment]
@huubvanniekerk - Yes, I can confirm this is a bug.
![testsvg](https://user-images.githubusercontent.com/4488048/31358884-5d239bea-ad3f-11e7-9acc-26263edd5631.png)

**Comment by huubvanniekerk** [comment]
@DylanC Thanks, glad you can confirm and labelled it.

**Comment by N3WWN** [comment]
Confirmed that my PR (currently still a work in progress) resolves this issue.

Here is the white font:

<img width="1365" alt="issue 838 - white on black" src="https://user-images.githubusercontent.com/19431804/39450391-2bb979c2-4c99-11e8-9060-1b34c6bba71b.png">

Here is the black font:

<img width="1366" alt="issue 838 - black on image" src="https://user-images.githubusercontent.com/19431804/39450417-486094de-4c99-11e8-8d5d-f5f162650b2e.png">

**Comment by peanutbutterandcrackers** [comment]
Closing this issue as #1081 seems to have more in-depth discussions regarding the issue.
