### ISSUE TITLE
updated new version, can't save .osp

### ISSUE THREAD

**Issue by Ellicewang** [OpenShot/openshot-qt#843]
**System Details:**
* Operating System / Distro: ?windows
* OpenShot Version: ?v2.3.4
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
1. can't save it, would be blank.
2, crashed when change the speed of music

**Comment by DylanC** [comment]
@Ellicewang - What type of audio file did you use?

**Comment by Ellicewang** [comment]
thanks for reply. The video is .mov.and the music is .mp3

**Comment by DylanC** [comment]
@Ellicewang - I'll check it out. Thanks.

**Comment by DylanC** [comment]
Cannot reproduce this one on v2.4.1.
