### ISSUE TITLE
Does not save settings, only saves with administrator user privileges

### ISSUE THREAD

**Issue by CsChristian** [OpenShot/openshot-qt#844]
Windows 10 personal 64bit
OpenShot 2.3.4

If I log in whit not admin priv. user, then I can not save the settings.
The same issue, whit not admin priv. user, I can not switch off the tutorial when the app started. In the next app start tutorial shown again.

**Comment by DylanC** [comment]
@CsChristian - Same issue on v2.4.1?

**Comment by DylanC** [comment]
Cannot reproduce on v2.4.1.
