### ISSUE TITLE
Unreadable UI controls on HiDPI display 

### ISSUE THREAD

**Issue by sserg1963** [OpenShot/openshot-qt#845]
**System Details:**
* Operating System / Distro: Linux / Ubuntu 16.04.3
* OpenShot Version: 2.3.4

**Issue Description and steps to reproduce:**
My notebook has 3200x1800 HiDPI display resolution @ 13" size.
UI and controls are unreadable and hard to use. 

Tries of known workarounds like 
`export QT_AUTO_SCREEN_SCALE_FACTOR=2`
or
`export QT_SCALE_FACTOR=2`

didn't help.

**Comment by masterleo** [comment]
still unreadable on 4K hidpi 13 inch screen

**Comment by SuslikV** [comment]
Post at least screenshot of the UI. I don't think that every developer is using "4K hidpi 13 inch" displays for the work.

**Comment by ferdnyc** [comment]
In fact, I believe exactly none of us are.

If you're also running Ubuntu 16.04 like the OP, @masterleo , then I'm gonna go ahead and blame the ancient version of Qt on your system. (Heck, even with **18.04**, that's only Qt 5.5. There were some significant upgrades to HiDPI support, especially with a GTK3-based desktop, around the Qt 5.7 timeframe.)

And, of course, if you're using the AppImages then that's Qt 5.2 so I'm always surprised when people even get a GUI at all.
