### ISSUE TITLE
hangs after slowed down clip

### ISSUE THREAD

**Issue by davidak** [OpenShot/openshot-qt#846]
**System Details:**
* Operating System: OS X 10.10.5
* OpenShot Version: 2.3.4

**Issue Description and steps to reproduce:**

0. open OpenShot
1. throw clip in
2. cut short part (2 sec)
3. slow it down to 1/2X
5. ???
6. hangs forever

Clip is FullHD H.264 @25fps AAC Stereo 44kHz (downloaded from Youtube)

**Comment by DylanC** [comment]
@davidak - This seems to work in the latest daily build for me. How about you?

**Comment by DylanC** [comment]
@davidak - This is confirmed as working in v2.4.1. See #587 and #588

**Comment by davidak** [comment]
Yes, works in v2.4.1.

**Comment by peanutbutterandcrackers** [comment]
+1 for OpenShot!!! Esp. @jonoomph !!! :)
