### ISSUE TITLE
Too much bugs to be useful

### ISSUE THREAD

**Issue by 4zm0** [OpenShot/openshot-qt#847]
**System Details:**
* Operating System / Distro: Xubuntu Linux 14.04.5 LTS
* OpenShot Version: 2.3.4

Really, is this crap any good? Slow as a goddamn snail, bugged as hell, crashes everytime... still no good video editors on Linux :-1:

**Comment by DylanC** [comment]
@4zm0 - Thanks for your feedback. Perhaps in the future it will be more stable for you and you will enjoy it more. =)
