### ISSUE TITLE
Snap distribution

### ISSUE THREAD

**Issue by julian-alarcon** [OpenShot/openshot-qt#851]
HI

It will be great if you can create a Snap distribution as now is the preferred Ubuntu distribution of apps. (according to this bug info https://bugs.launchpad.net/ubuntu/+source/gnome-software/+bug/1705953 )

More info: https://snapcraft.io/

There is a try of packaging from @popey here: https://github.com/popey/openshot-snap

**Comment by DylanC** [comment]
@julian-alarcon - Good idea. Thanks.

**Comment by julian-alarcon** [comment]
No news about this? Anybody knows the source code of deb compiling? I can help to create this.

**Comment by DylanC** [comment]
@julian-alarcon - I haven't heard anything more about it. It sounds like OpenShot is having trouble with finding the libs on this attempt - https://github.com/popey/openshot-snap.

I reckon you would need either @jonoomph or @ferdnyc or @SuslikV to get involved to figure it out. I personally found learning to create .deb installers much easier than Snap. Creating a working Snap package can be tricky.

**Comment by popey** [comment]
Ooh, I haven't looked at that snap for a while, my knowledge and the tools have improved, so I think I can fix that now. Will take another look.

**Comment by ferdnyc** [comment]
Most of the work would be in specifying the necessary dependencies, but the FeatureSummary report that our `libopenshot` CMake build now outputs should help on that side of things. The `python_packages` list in `freeze.py` would be a good place to start, here on the Python front:
https://github.com/OpenShot/openshot-qt/blob/3fed6be78f1361d37869fcaafd5a2b5a0c9b9bfa/freeze.py#L72-L91

**Comment by astrojuanlu** [comment]
For the record, https://snapcraft.io/openshot-qt is now based on https://git.launchpad.net/openshot-packaging/tree/

**Comment by julian-alarcon** [comment]
So, it is solved!
