### ISSUE TITLE
Audio missing/disabled when videos are uploaded

### ISSUE THREAD

**Issue by Chaosunraveled** [OpenShot/openshot-qt#853]
HP Pavilion Notebook PC; Intel Core i7
Windows 7 64 bit SP1
OpenShot 2.3.4

When I export videos from OpenShot to my hard drive, the exported file is less than 50% the size of the source file, although both video and audio work fine.  However, when I upload to Facebook, the audio is either missing, or disabled.

**Comment by DylanC** [comment]
@Chaosunraveled - If the video has the audio already then it should be fine. If the audio is disabled maybe Facebook detects a copyright issue.
