### ISSUE TITLE
Export video at 60fps on Linux generate wrong  files

### ISSUE THREAD

**Issue by fabrixx** [OpenShot/openshot-qt#854]
**System Details:**
OS: Arch Linux 
Kernel: x86_64 Linux 4.12.8-2-ARCH
Intel Core i7-6700 @ 8x 4GHz 
GeForce GTX 1060 3GB

OpenShot Version: 2.3.4

After editing,  preview show me correct output.
When I export to 60 fps at any resolution and with any codec the video is missing some audio parts, the fade is placed wrong and most of the video is black. The exported files are small. At 25/30 fps everything works correctly.

My solution:
After dozens of attempts I found that by clicking on the "select profile" button and setting it to 60fps (usually i work on 25fps profiles for all my projects), the fades disrupt and the preview outputs is exactly the wrong file that is usually exported to 60 fps. If at this point I fix the fade, the video is exported correctly.

I think there is a problem of fade working on 25/30 and export to 60fps. I suggest to use
a 60fps profile if you want to export to this framerate, though video preview may be difficult at this fps.

**Comment by ErunamoJAZZ** [comment]
I found this issue too.

How I understand this "bug", it is that many effects are using something like a frame measure, then, if you try to export in a different fps that the actual profile, all those measure going wrong.

As user, **the solution is to edit your video in the same profile that you want to export**.

But a real fix could be an interpolation of those effects if fps change at export or so.

**Comment by DylanC** [comment]
Solved by changing the current profile to 60fps.
