### ISSUE TITLE
No Select Tool located in menu ?

### ISSUE THREAD

**Issue by iawesomatize** [OpenShot/openshot-qt#856]
**System Details:**
* Operating System / Distro: Windows 10
<img width="420" alt="openshot" src="https://user-images.githubusercontent.com/31362550/29738534-7e028774-89d9-11e7-8b1c-3881d5215f8b.PNG">

* OpenShot Version: 2.3.4
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

**Comment by DylanC** [comment]
@iawesomatize - I think this must be intentional. I don't see it in the current version either.

**Comment by DylanC** [comment]
This is intentional by design. You can select clips if you don't have another tool selected already. Thanks.
