### ISSUE TITLE
Freeze when go to export.

### ISSUE THREAD

**Issue by Redysz** [OpenShot/openshot-qt#857]
**System Details:**
* Operating System / Distro: Windows 8.1
* OpenShot Version: 2.3.4
* _Please attach log files if crash_

I only go to File -> Export. Next I need to wait approx 30 second to see export dialog. I didn't have this issue on 2.3.1 version.

**Comment by DylanC** [comment]
@Redysz - Cannot reproduce on v2.4. Please try the latest version.
