### ISSUE TITLE
QFontDatabase Error - Openshot fails to launch on Windows 10

### ISSUE THREAD

**Issue by mfat** [OpenShot/openshot-qt#86]
Upon running the app I see the following error message, then it quits:
![capture](https://cloud.githubusercontent.com/assets/423263/12980933/d6d611f4-d0f3-11e5-8617-e85642024aa0.PNG)

**Comment by jonoomph** [comment]
Has anyone else experienced this on Windows 10? Can you delete your /Users/USER/.openshot_qt/ folder and try again? Also, did the program ever launch successfully for you?

**Comment by BF3000** [comment]
I have the Windows 10 and I don't have this error.
And as far as I see, there is a different version of Phyton installed on **mfat** PC and for some reason Openshot tryed to load scripts from it.

**Comment by mfat** [comment]
What version should be installed? I installed the latest version from
Python website.

On Feb 12, 2016 05:41, "BF3000" <notifications@github.com> wrote:
>
> I have the Windows 10 and I don't have this error.
> And as far as I see, there is a different version of Phyton installed on
mfat PC and for some reason Openshot tryed to load scripts from it.

**Comment by BF3000** [comment]
Just delete it.
Openshot doesn't need any external Python installation.

**Comment by mfat** [comment]
@jonoomph I never managed to run it. Always got this error.

**Comment by BF3000** [comment]
Thats strange.
I already install it on 2 PC, and even if I can't save anything (bug #79), I still can launch it, edit and render video.

**Comment by mfat** [comment]
Tried removing my .openshot_qt folder. No luck. The same error again. I'm trying to run this on a Cherrytrail Windows tablet, for what it's worth.

**Comment by mfat** [comment]
@jonoomph any thoughts?

**Comment by jonoomph** [comment]
Please attach your /Users/USER/.openshot_qt/openshot-qt.log file... hopefully that file exists on your computer. If not, it's possible this crash is happening prior to the log file being created.

**Comment by jonoomph** [comment]
I've added some additional error logging around loading the Ubuntu-R.ttf font file (when OpenShot launches), and it will now continue launching OpenShot even if an error is detected while loading this font. This will be included in the next Windows release. Thanks!

**Comment by mfat** [comment]
problem was fixed after a windows update.
