### ISSUE TITLE
Can't add russian subtitles

### ISSUE THREAD

**Issue by Redysz** [OpenShot/openshot-qt#860]
**System Details:**
* Operating System / Distro: 8.1
* OpenShot Version: 2.3.4

Like in title. I can't add russian subtitles (also with WenQuanYiMicroHei font).

**Comment by DylanC** [comment]
Dup of #632

**Comment by DylanC** [comment]
@Redysz  - This sounds like an issue with the characters used in the file. I would recommend to try this daily as the problem is solved in it.
