### ISSUE TITLE
No English language available for the program. Not even in preferences...!

### ISSUE THREAD

**Issue by Jorrit-TheOneAndOnly** [OpenShot/openshot-qt#862]
**System Details:**
* Operating System / Distro: ? windows 7
* OpenShot Version: ? latest. 2.3.4 64 bit
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
I installed openshot and despite having about everything set to English on my laptop, except the region settings (to get € instead of pounds and some other features) openshot decided to overrule about all of my personal preference settings and install this program in Dutch and therewith be the only program on my laptop in Dutch... To make things worse, openshot even eliminated the option English in preferences! To be clear: under the preferences many many languages are available, but no English... Really strange and must be very easy to solve. Just make the most common language available next to all those other languages.

**Comment by DylanC** [comment]
Dup of #331

**Comment by DylanC** [comment]
As confirmed in #331.

> Changing interface language to American English works fine in OpenShot-v2.4.1-34-g6a9257e-59-685.

Can someone confirm this here too?

**Comment by DylanC** [comment]
Confirmed as fixed in #331.
