### ISSUE TITLE
Newbie

### ISSUE THREAD

**Issue by monamlisa** [OpenShot/openshot-qt#864]
**System Details:**
* Operating System / Distro: ?Windows  10

Hello all!
Can someone tell me where is the transition icon in openshot?

**Comment by DylanC** [comment]
![transition](https://user-images.githubusercontent.com/4488048/30222191-44d3e1ec-94be-11e7-914c-5491774feff0.png)

**Comment by DylanC** [comment]
@monamlisa - See the screenshot above. Thanks.
