### ISSUE TITLE
Blender 2.78 error. How do I go about using 3D animated Title?

### ISSUE THREAD

**Issue by SKSilangwa** [OpenShot/openshot-qt#865]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

**Comment by DylanC** [comment]
@SKSilangwa - What did you put in the preferences for the path? What OS are you running?

**Comment by SKSilangwa** [comment]
Thank you! I am running windows 8

**Comment by SKSilangwa** [comment]
I put the path of the Blender 2.78 which is on my computer.
On Sep 8, 2017 6:52 PM, "DylanC" <notifications@github.com> wrote:
>
> @SKSilangwa - What did you put in the preferences for the path? What OS
are you running?

**Comment by DylanC** [comment]
@SKSilangwa - Can you paste the path you are using right here?

**Comment by DylanC** [comment]
@SKSilangwa - I have seen the path in the other ticket. It didn't look correct. Guidance on the path and animated titles is here:

https://github.com/OpenShot/openshot-qt/wiki/How-to-troubleshoot-errors-with-animated-titles

**Comment by SKSilangwa** [comment]
Thank you so much for your support. On the preferences settings there are
only:
Language
Default theme
Image length
Volume
Blender command (path)
Advance Tittle Editor (path).

And there is no Blender Bundled script option. Those items listed which
need to be updated, are coming under Choose a Template.
Help me, where do I find the curved settings on the OpenShot?

**Comment by DylanC** [comment]
@SKSilangwa 
The main thing on the page is you need to set the path correctly:

On Windows Blender is installed by default into:

64-bit - C:\Program Files\Blender Foundation\Blender\blender.exe
32-bit - C:\Program Files (x86)\Blender Foundation\Blender\blender.exe

I'm not sure where curved is in the program.
