### ISSUE TITLE
how to set a blender path

### ISSUE THREAD

**Issue by SKSilangwa** [OpenShot/openshot-qt#866]
i am always getting this message despite putting the correct path for the blender:
 Blender, the free open source 3D content creation suite is required for this action (http://www.blender.org).

Please check the preferences in OpenShot and be sure the Blender executable is correct.  This setting should be the path of the 'blender' executable on your computer.  Also, please be sure that it is pointing to Blender version 2.78 or greater.

Blender Path:
C\Program Files\ Blender Foundation\Blender\2.78\python\bin
C\Program Files\ Blender Foundation\Blender\2.78\python\bin\python.exe

**Comment by DylanC** [comment]
Please try this:
https://github.com/OpenShot/openshot-qt/wiki/How-to-troubleshoot-errors-with-animated-titles
