### ISSUE TITLE
Preview all wrong when editing 1920:960 video

### ISSUE THREAD

**Issue by eliramk** [OpenShot/openshot-qt#867]
**System Details:**
* OSX
* OpenShot Version: 2.3.4

**Issue Description and steps to reproduce:**

1. Create custom profile for VR video (1920x960 with 2:1 ratio)

description=VR 960p
frame_rate_num=30000
frame_rate_den=1000
width=1920
height=960
progressive=1
sample_aspect_num=1
sample_aspect_den=1
display_aspect_num=2
display_aspect_den=1

2. restart
3. Add video clip with 1920x960 resolution

Bug: The video does not fit in the preview pane
Bug: All scale options are wrong in the preview pane

Exporting the movie works well, but it's impossible to work this way.

**Comment by DylanC** [comment]
@eliramk - I would recommend to try the latest daily build. It has much important fixes in it.
