### ISSUE TITLE
Is there a build/config/video format that works on W10?

### ISSUE THREAD

**Issue by Paul-DeBryone** [OpenShot/openshot-qt#868]
**System Details:**
Lenovo E70 workstation.
W10/Xeon Qcore 2.83Ghz/12GB mem/ Radeon 7870/2tbHDU.
Openshot 2.3.4-dev5

Question: Is there a version of Openshot that works properly on W10. One that doesn't stutter when playing back? Unfortunately in it's present form this software appears to be unusable on the above platform. It doesn't not seem to like most video codecs and the most obvious one, MP4 straight out of a phone camera produces significant stuttering whenever playing back. Why release software that doesn't work? I find it laudable that you are doing this but right now I seem to be wasting my time. Is there a configuration/platform where this editor does work? I find that when I drag an MP4 file into the timeline Openshot shows the wrong clip length and the video playback skips and jumps. When rendered the output contains the errors as well.

 Is there a configuration/platform where this editor does work?

**Comment by petesimon** [comment]
I have the same problem in 
I have tried the stable release v2.3.4 , and tried several recent daily releases v2.3.4-3 / v2.3.4-4 / v2.3.4-5 etc and all of them are far too slow to use. CPU usage often peaks to 100% and stays there for 1 to 2 minutes just to play a basic timeline or preview any video 1080p30fps mp4/h264 on my i7 2.5ghz. I updated Microsoft DirectX and I have have installed LAV Filters recent version just to try to help.

Other video editor software such as Shotcut v17.08 and Videopad v5.01 work fine. Media players such as VLC and MPC-HC also play all video including 4k mp4/h264 video just fine.

**Comment by Paul-DeBryone** [comment]
I have abandoned my trial of this editor and de-installed it from my machine. I have installed Shotcut and while it’s somewhat obtuse it is at least usable. I get that a lot of people in the Linux world derive entertainment from just getting code to work but if you are a PC user it usually means that you are trying to get a job done and I say that as an avid Gimp/Inkscape user. I am also evalutating Davinci Resolve and Hitfilm4 Express as possible contenders. Don’t waste any more of your time with Openshot.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by DylanC** [comment]
Try again in v2.4 and see if that works for you. Thanks.

**Comment by drnstvns** [comment]
@DylanC Hi I'm new here and might not know what Im talking about but I keep looking for solutions to this stuttering video issue and I just keep finding you closing them saying try latest build although people keep responding that isn't solving anything. Is there a reason you're closing them without there being a working solution because quite few folks are having this issue but no one is getting a solution?
