### ISSUE TITLE
Glitch/Bug Messing With Chunks of Video When I Undo & Time tool bug

### ISSUE THREAD

**Issue by TheSwanDragon** [OpenShot/openshot-qt#869]
I've been going through a video I took and using the razor tool to slice out chunks I don't want. As I'm going through the remainder and attempting to apply minor edits, the section of video I'm working on regularly changes to a part of the original video whenever I try to undo, almost always the same part. This has occasionally affected the entire file and I've lost easily half of my worktime having to restart the program without saving and redoing the work. So far, that is the only way I have found to restore the correct video. Incidentally, this does not affect the thumbnail for that section of the video.

This glitch/bug has ALWAYS triggered after undoing anything using the time option to speed up or slow down the video to 32x or 1/32x. Both of those reduce the video to 1/32x. Any other selected options crash the program. I cannot find where the log files are to add in here.

**Comment by DylanC** [comment]
@TheSwanDragon 

To enable debug mode go to Edit > Preferences > Debug and tick the box. Logs are written to (on Windows) C:\Users\username.openshot-qt\openshot-qt.log

**Comment by TheSwanDragon** [comment]
Here is the most recent log. Wouldn't let me upload it as a .log file so I zipped it.
[openshot-qt.log.3.zip](https://github.com/OpenShot/openshot-qt/files/1373585/openshot-qt.log.3.zip)

**Comment by maizuddin35** [comment]
Hello there, I face the same problem as well.
[openshot log.zip](https://github.com/OpenShot/openshot-qt/files/1405122/openshot.log.zip)

**Comment by DylanC** [comment]
@TheSwanDragon @maizuddin35 - Thanks.
