### ISSUE TITLE
Importing media file causes hang

### ISSUE THREAD

**Issue by putztzu** [OpenShot/openshot-qt#870]
openSUSE LEAP 42.3
Running the appimage from openshot website(Sept 4 2017)
With no codecs installed on machine, media can't be imported at all.
Then, installed media codecs from Packman using the steps described at
https://forums.opensuse.org/showthread.php/526222-Multimedia-Guide-for-openSUSE-Leap-42-3
BTW - If openshot is an appimage with all dependencies, why aren't codecs also included?

After the codecs are installed, it looks like the mp3 file is analyzed properly but then openshot hangs. 
The same happens if a video file is added.
A picture file (png) can be added without any problem.
The stdout **after the file is added** is the following

[mp3 @ 0x2cde400] max_analyze_duration reached
[mp3 @ 0x2cde400] Estimating duration from bitrate, this may be inaccurate                        
project_data:INFO _set key: ['files'] values: {'audio_bit_rate': 320000, 'has_video': True, 'audio_timebase': {'num': 1, 'den': 14112000}, 'media_type': 'video', 'pixel_format': 12, 'duration': 135.5608520507812, 'acodec': 'mp3', 'audio_stream_index': 0, 'top_field_first': True, 'width': 596, 'channels': 2, 'vcodec': 'mjpeg', 'video_timebase': {'num': 1, 'den': 24}, 'has_single_image': False, 'path': '/mnt/Music/Sha Na Na - The Best Of Sha Na Na (1976) Vinyl Rip Mp3 320 vtwin88cube/Disc 1/01.Get A Job (Live).mp3', 'type': 'FFmpegReader', 'interlaced_frame': False, 'id': 'MYNEJBRCX8', 'file_size': '5422434', 'has_audio': True, 'channel_layout': 3, 'display_ratio': {'num': 596, 'den': 601}, 'pixel_ratio': {'num': 96, 'den': 96}, 'video_length': '3253', 'video_bit_rate': 319999, 'fps': {'num': 24, 'den': 1}, 'height': 601, 'sample_rate': 44100, 'video_stream_index': 1} add: True partial: False remove: False
timeline_webview:INFO SortItems
timeline_webview:INFO UpdateLayerIndex
 files_model:INFO updating files model.
[mp3 @ 0x2cde400] max_analyze_duration reached
[mp3 @ 0x2cde400] Estimating duration from bitrate, this may be inaccurate                        
[mp3 @ 0x2cde400] max_analyze_duration reached                                                    
[mp3 @ 0x2cde400] Estimating duration from bitrate, this may be inaccurate

**Comment by DylanC** [comment]
@putztzu - I would suggest the daily build of v2.4. Its better for audio.
