### ISSUE TITLE
Shut down when applying speed change

### ISSUE THREAD

**Issue by leobozo** [OpenShot/openshot-qt#871]
**System Details:**
* Windows 10
* OpenShot Version: 2.3.4

Hello :)
I've got a problem with Openshot 2.3.4 running on Windows10 when I try to speed up a sequence (fast forward X2, X4, etc.). 
Here are the steps : 
I right-click on the sequence, apply the speed change dans then run the preview but as soon as the slider reaches the beginning of the modified sequence, a message shows : "Launch.exe a cessé de fonctionner" and the program shuts down. 

Here is the error repport : 

_Nom de l’application défaillante launch.exe, version : 0.0.0.0, horodatage : 0x57a98a3e
Nom du module défaillant : ntdll.dll, version : 10.0.15063.447, horodatage : 0xa329d3a8
Code d’exception : 0xc0000374
Décalage d’erreur : 0x00000000000f775f
ID du processus défaillant : 0x29a4
Heure de début de l’application défaillante : 0x01d3263fc9ac009a
Chemin d’accès de l’application défaillante : C:\Program Files\OpenShot Video Editor\launch.exe
Chemin d’accès du module défaillant: C:\WINDOWS\SYSTEM32\ntdll.dll
ID de rapport : 929926b9-f4c7-4b2f-9761-4e34d11ab2ce
Nom complet du package défaillant : 
ID de l’application relative au package défaillant :_ 

Did I do something wrong during the installation or is it a bug ? 

Kind regards

Leo

**Comment by vicklau** [comment]
I have exactly the same problem every time I do this.
OS: Windows 10 Pro 10.0.15063
Processor: Intel Core i7-6600U 2.60GHz, 2808MHz
Intel HD Graphics 520 1GB

**Comment by DylanC** [comment]
@leobozo - This is working in v2.4 from my tests. Can you try again with OpenShot v2.4 please?

**Comment by bell18** [comment]
it happens to me also....every time i try to speed up/ slow down a video openshot just crashes

**Comment by DylanC** [comment]
@bell18 - What version of OpenShot are you using?

**Comment by bell18** [comment]
@DylanC I think the newest

**Comment by DylanC** [comment]
Dup of #588

**Comment by DylanC** [comment]
Confirmed as fixed in #588
