### ISSUE TITLE
Audio not in exported video

### ISSUE THREAD

**Issue by ringo42** [OpenShot/openshot-qt#872]
**System Details:**
* Operating System / Distro: Win 7
* OpenShot Version: 2.3.4
* _Please attach log files if crash_

My video has audio, and I have added a music track. They both play in the preview, but when I export the video there is no audio at all. I've tried a couple different formats in the export. what am I missing?

**Comment by regilane** [comment]
Também estou com o mesmo problema...

**Comment by stephan75** [comment]
Please try that export with latest 2.4.0 release ... And tell us here about success or failure.

**Comment by JIMATA** [comment]
I have the same problem and it has not be solved with 2.4.0 release.

**Comment by andersonaas** [comment]
I have the same problem.

**Comment by DylanC** [comment]
This has been resolved in the daily build. See ticket - #618.
