### ISSUE TITLE
Export error

### ISSUE THREAD

**Issue by dade-ally** [OpenShot/openshot-qt#875]
**System Details:**  Embedded computer running VIA Quad Core 
* Operating System / Distro: ? Linux Xubuntu 16.04-3
* OpenShot Version: ?2.4.0
* _Please attach log files if crash_

I tried exporting the video after editing and the system gave the error attached!

**Issue Description and steps to reproduce:**
![image](https://user-images.githubusercontent.com/25546413/30153759-8b514606-93af-11e7-9e6e-6ff9c656acd6.png)

**Comment by DylanC** [comment]
@dade-ally - Do other mp4 source files export correctly?

**Comment by beattherdrum** [comment]
Having problems finding exported files...where do0 they go???? I follow the file path but it leads nowhere...then I try to export once more but it says the file is already created...getting lost here and need help!!

**Comment by DylanC** [comment]
@dade-ally - This should work in the daily build. Try it and let us know.
