### ISSUE TITLE
How to disable google-analytics ?

### ISSUE THREAD

**Issue by kyrios123** [OpenShot/openshot-qt#877]
* Operating System / Distro: Solus (Linux 64-bit)
* OpenShot Version: 2.4.0

I see openshot makes lots of connections to **google-analytics**.
How could this be disabled apart from working offline ?

Thanks.

**Comment by DylanC** [comment]
@kyrios123 - It cannot be disable currently. Note this is to collect feedback on what areas of the program crash or have problems. It is useful for the program to become more stable.
