### ISSUE TITLE
Improvement for new user for Inkscape (advanced modification of Titles)

### ISSUE THREAD

**Issue by CapitainFlam** [OpenShot/openshot-qt#879]
**System Details:**
* Operating System / Distro: ? => win 7
* OpenShot Version: ? => 2.4   /!\ french language installation. I translated the text "from french". 
* _Please attach log files if crash_ => nope.

**Issue Description and steps to reproduce:**
Hi team, 
just wondering that i didn't catch the "you have to install Inkscape" (when editing titles) or "you have to install Blender" (for animated titles). [full disclosure : I didn't yet installed Blender, no need]
Indeed, I unistalled Inkscape and re-installed it, to see that it DIDN'T WORK !
...Then, (mind blowing in progress !) i thought : "it is installed, but this program doesn't know where to catch it." So I get ot the preference and modified the path to Inkscape, from 
"inkscape" 
to 
"C:\Program Files\Inkscape". 
...Doesn't work. 

And the program says no in "advanced modification" for "title" : "You have to install C:\Program Files\Inkscape"... Hey, you're pissing me off ! 

changing again to : 
"C:\Program Files\Inkscape\inkscape.exe". 

ANNNNNNNNNNNNNNNND IT WORK !

**So, here is my proposal :**
1. modify the "help message" prompted when trying to use "advanced modification" in title or "animated title", 
in order to NOT ONLY say "you have to install [program name]", 
but accurately, say something like : 
"hi fellow user, 
keep in mind that to do that, you need : 
    1. to install [program name]
    1. declare it's full path to access it in the Preference menu"

1. and in this Preference menu, 
having more than just 
"path for advanced editing" (or something like that, i translated form french), 
but a complete tab, with 
    1. explanation of this path, 
    1. example (...you HAVE TO include the "inkscape.exe", not only the path)
    1. a small  bla-bla to help rookies in computers (like I was long time ago) and/or new users (like I'm now)

Honestly, wouldn't have I already done it for other program in my youth that I wouldn't have catch it !
 
...and same for Blender, that I don't even know where we have to advise the program that it's installed. Or maybe THIS ONE doesn't need to have a path explained ?

Have fuuuuuuuuuuuuuuuuuuuuuuuuun ! :-)

CapitainFlam.

**Comment by DylanC** [comment]
Dup of #68

**Comment by DylanC** [comment]
I put in a change to have browse buttons in future. This will work better in newer releases:
https://github.com/OpenShot/openshot-qt/pull/2255
