### ISSUE TITLE
Wish: One transition should replace another

### ISSUE THREAD

**Issue by BF3000** [OpenShot/openshot-qt#88]
Every time I connect one video with another, a simple transition is created.
And it seems logical to me if I could drag&drop another transition from menu, and it will replace previous one.

![transition](https://cloud.githubusercontent.com/assets/1564077/13000535/8014c95e-d185-11e5-93a0-78f4f283fd4f.jpg)

**Comment by jonoomph** [comment]
Agreed! I don't think this would be too difficult. I'll try and get to this soon, unless someone else beats me to it. =) Thx!
