### ISSUE TITLE
Drag and drop (and only drag and drop) doesn't work for importing file with "special caracters" (é, à, etc...)

### ISSUE THREAD

**Issue by CapitainFlam** [OpenShot/openshot-qt#880]
**System Details:**
* Operating System / Distro: ? => Win 7
* OpenShot Version: ? => 2.4.0
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
I drag and drop my file from windows file explorer to OpenShot. 
No problem until a damn file that don't want to import. 

...After try and fail, I catched it : 
the file "This is a file.svg" can be imported. 
The file "This is a file with a french name Toto.svg" can be imported.
BUT : 
The file "This is a file avec un nom accentué like éèàü etc.svg" CAN NOT BE IMPORTED !

at least, we should have a working for it.

IMPORTANT NOTE : the IMPORT through "+ Add file" button is working. It's ONLY the DRAG AND DROP that doesn't work.
...apparently, it loads, ...but imply and "not crashed but unworkable app". 
I had to quit and restart to catch back the drag and drop 'inside the app', once i had "forced" the import of this particular file.

**Comment by DylanC** [comment]
@CapitainFlam

The latest daily build solves issues with those characters:

https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.4.0-9-g7267417-56-648-x86_64.exe

Let me know if it is now working for you.

**Comment by CapitainFlam** [comment]
Hello !

Indeed, i tryed it few seconds ago, and it's working ! (we can drag and
drop files with special caracters like french words, and it doesn't crash
the machine).

great job.

Loïc

2017-11-05 19:24 GMT+01:00 DylanC <notifications@github.com>:

**Comment by DylanC** [comment]
@CapitainFlam - Great news! Thanks. Closing this ticket now if you don't mind.

**Comment by DylanC** [comment]
Dup of #677
