### ISSUE TITLE
"Português do Brasil" language available twice in preferences

### ISSUE THREAD

**Issue by glaubersm** [OpenShot/openshot-qt#881]
**System Details:**
* Operating System / Distro: Arch linux
* OpenShot Version: 2.4.0
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
open openshot preferences, open language dropdown. See my screenshot.

![openshot](https://user-images.githubusercontent.com/15967631/30214566-5b92e080-9483-11e7-8dd1-9457f016a8d9.png)

**Comment by DylanC** [comment]
@glaubersm - Thanks for the report.

**Comment by DylanC** [comment]
@glaubersm - Thanks for the report.

**Comment by glaubersm** [comment]
Bug persists in OpenShot 2.4.2 installed from flathub.

**Comment by peanutbutterandcrackers** [comment]
It says `pt` and `pt_BR`. Hmm... I wonder if we really have any control over this... but maybe we do... I am not sure...

**Comment by glaubersm** [comment]
"Português" language is duplicated in nightly build. Could anyone reopen this issue please?

![openshot](https://user-images.githubusercontent.com/15967631/98437161-ddae6100-20be-11eb-8574-7d21490d5fdf.png)
