### ISSUE TITLE
File size explodes 10-fold

### ISSUE THREAD

**Issue by Elmarts** [OpenShot/openshot-qt#882]
**System Details: CPU~Quad core Intel Core i7-6700K
* Operating System / Distro: Dual boot win 7 & Linux Mint 18.2 Sonya 64-bit, Kernel: 4.10.0-28-generic x86_64 (64 bit gcc: 5.4.0), Desktop: MATE 1.18.0 (Gtk 3.18.9-1ubuntu3.3)
* OpenShot Version: 2.4.0
* _Please attach log files if crash_ n/a

**Issue Description and steps to reproduce:**
Starting with a 91 MB mp4 (640X480, h264, vorbis audio 14351 frames total) and clipping off 23 seconds from the front and maybe 5 seconds off the back, then exporting results in a 805 MB file.  Why?  It should be smaller.  Also, I cannot save the clip as a separate file - again, why?

**Comment by DylanC** [comment]
@Elmarts - Same result in v2.4.1?

**Comment by Elmarts** [comment]
Ah - that explains it!  So the program does not take as a default the input specifications for the output, which can later be overridden if you want to upscale.  It might be good to have that settable in the preferences for newbies with simple projects like me :) Thanks for the sleuthing.

**Comment by DylanC** [comment]
@Elmarts - No problem. :)
