### ISSUE TITLE
OpenShot Windows 10 - timeline stops at 30 min

### ISSUE THREAD

**Issue by DToyos** [OpenShot/openshot-qt#883]
**System Details:**
* Operating System / Distro: Windows 10
* OpenShot Version: 2.0? Not sure

Nice program...much easier than HitFilm Express or whatever. Everything working well until I hit about 30 min 24 sec...can't add any more clips. Help!!

**Comment by DylanC** [comment]
@DToyos - How about v2.4.1, does it work better for this?

**Comment by DToyos** [comment]
@DylanC I don't believe I've upgraded but the problem seemed to go away when I restarted the program.

**Comment by DylanC** [comment]
@DToyos - No problem. Let us know if you have any more trouble again.
