### ISSUE TITLE
advanced editor wont work

### ISSUE THREAD

**Issue by yasenc137** [OpenShot/openshot-qt#884]
**System Details:**
* Operating System / Distro: i dont know
* OpenShot Version: 2.4.0
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
when i open titles , select any it doesnt matter and if i want to use advanced Editor it says pls install inkscape although i already installed inkscape ... pls help me

**Comment by DylanC** [comment]
@yasenc137 - What Operating System do you use? Regardless of the OS the path will need to be set. Make sure to set the path in the preferences:
![path](https://user-images.githubusercontent.com/4488048/30525158-6cf2c2f0-9bf9-11e7-9c55-8b25a26e5130.png)

The application needs to know where to find Inkscape.

**Comment by DylanC** [comment]
@yasenc137 - For Windows you would need to set the path to:
C:\Program Files\Inkscape\inkscape.exe
