### ISSUE TITLE
question regarding dual audio clips

### ISSUE THREAD

**Issue by rochemike** [OpenShot/openshot-qt#885]
**System Details:**
* Operating System / windows 8.1
* OpenShot Version: 2.4.0

The video I import has 2 audio channels. I'm trying to mute the one, but cannot find the (to quote tutorial)...."speaker icon, located on the clip.  This will mute the audio for this clip"

I also tried changing color themes. Can't find the speaker icon.....

Any help?

Thanks

**Comment by DylanC** [comment]
@rochemike - I don't think we have audio channel control yet. Thanks.
