### ISSUE TITLE
Audio Files Not working

### ISSUE THREAD

**Issue by HASShanea** [OpenShot/openshot-qt#886]
**System Details:**
* Operating System / Distro: Windows
* OpenShot Version: 2.3.4
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

My audio files, no matter which audio file I import, malfunctions after 2 minutes 30 seconds. On every video I try to make, it just keeps messing up and not working. I have tried it on multiple different audio clips, and even slicing them to see if that will help. But everytime at the 2 minutes and 30 second mark, the audio files malfunction and are not usable because it just emits a ticking noise.

**Comment by bell18** [comment]
@HASShanea that happened to me too. It took me a while to figure it out. What type of audio file are you using?

**Comment by HASShanea** [comment]
@bell18 mp3

**Comment by bell18** [comment]
There is a problem with openshot and mp3 files, at least on the version I was using. At 2 min 30 sec it stopped. I converted to m4a and had no more issues. Its an extra step but it enabled me to finish my project in time.

**Comment by HASShanea** [comment]
@bell18 you are a life-saver! Worked great! Thanks so much for the help!!

**Comment by bell18** [comment]
@HASShanea I'm happy I was able to help.

**Comment by bell18** [comment]
I still wish openshot would fix it to allow mp3 also. It would make my life so much easier.
