### ISSUE TITLE
Drag and Drop import files Not work Win10

### ISSUE THREAD

**Issue by movilrunnerdev** [OpenShot/openshot-qt#888]
**System Details:**
Intel core i7 2670qm 64 bits
* Operating System / Distro: ?
Windows 10 profesional.
* OpenShot Version: ?
2.4.0
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
Amazing Video Editor.
Drag and Drop import files Not work in Windows 10 profesional.
Thanks.

**Comment by DylanC** [comment]
@movilrunnerdev - Did it completely not work or cause the program to close/crash?

**Comment by DylanC** [comment]
I experienced a crash with the drag/drop import on Ubuntu. So I will mark this as a bug for now.

**Comment by DylanC** [comment]
@ankitpati - Did you find any problem with drag and drop import?

**Comment by ankitpati** [comment]
@DylanC Confirmed no repro after multiple tries on fully patched Ubuntu 16.04 x86_64 with OpenShot 2.4.0.

@movilrunnerdev @DylanC Is it possible for any of you to upload the specific videos that caused the crash?

**Comment by DylanC** [comment]
@ankitpati - I tried it again and it didn't happen. I will need to investigate some more until I figure out what caused it.  I can attach my vid clip later if you like.
