### ISSUE TITLE
If a rename a project, new renamed project, is empty.

### ISSUE THREAD

**Issue by movilrunnerdev** [OpenShot/openshot-qt#889]
**System Details:**
intel i7 2670 qm
* Operating System / Distro: ?
Windows 10 profesional
* OpenShot Version: ?
2.4.0
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
If a rename a project, this project  not work. If i open the new renamed project, is empty.
Thank you.

**Comment by DylanC** [comment]
@movilrunnerdev - Marked as a bug

**Comment by peanutbutterandcrackers** [comment]
How did you rename a project, good sir? I don't think renaming a project from the file manager is the right idea. A better way, perhaps would be to 'save as' a new file name.
