### ISSUE TITLE
There is no language change option.

### ISSUE THREAD

**Issue by BF3000** [OpenShot/openshot-qt#89]
I mean how can I even a write bug report if I don't know how the original function name.

**Comment by jonoomph** [comment]
I'm not sure what you mean. OpenShot detects the current system language, and then loads a matching translation (if found). You can also override this by setting the LANG environment variable to the locale code (en, es, fr, de, etc...).

**Comment by BF3000** [comment]
And where is the option in the GUI?
I don't need fully automatic solution.

**Comment by jonoomph** [comment]
FYI: tracking this issue on https://github.com/OpenShot/openshot-qt/issues/97

**Comment by jonoomph** [comment]
It's fixed now =)
