### ISSUE TITLE
FATAL MISTAKE. Openshot close and not recovery project

### ISSUE THREAD

**Issue by movilrunnerdev** [OpenShot/openshot-qt#890]
**System Details:**
intel i7 2670qm
* Operating System / Distro: ?
Windows 10 profesional
* OpenShot Version: ?
2.4.0
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
Suddenly the program is closed and the project is not recovered

**Comment by DylanC** [comment]
@movilrunnerdev - What did you do before the crash/program closed?

**Comment by movilrunnerdev** [comment]
Really, i know crash progrma closed, when i tried transform manually a title in preview video.
