### ISSUE TITLE
Improve zoom level more

### ISSUE THREAD

**Issue by DylanC** [OpenShot/openshot-qt#891]
It has been suggested to improve the lowest level of zoom to 0.1s instead of 1s. Something to consider in the future perhaps.

**Comment by peanutbutterandcrackers** [comment]
@DylanC Does this mean frame-by-frame mode for the timeline like KdenLive has?

**Comment by DylanC** [comment]
@peanutbutterandcrackers - I think just to improve the maximum zoom level in general.

**Comment by peanutbutterandcrackers** [comment]
@DylanC I'm so eagerly waiting for frame-by-frame mode. And a new version of OpenShot too. And a tutorial on how to actually use alpha-mask effect in OpenShot... among others.

**Comment by schorhr** [comment]
Hello :-) I love OpenShot, I want to use it for stop-motion animation with students. But zooming into single frames, even see their preview in the time-line, would be a massive improvement.

Thank you <3

**Comment by mikelacsa** [comment]
The same was requested in [#1024](https://github.com/OpenShot/openshot-qt/issues/1024)

**Comment by ferdnyc** [comment]
And in #1327, and probably others; it's kind of a perennial request.

I explain in https://github.com/OpenShot/openshot-qt/pull/1411#issuecomment-376017445 why I don't _personally_ think there's any actual benefit to doing it. Usually the people requesting it don't have any arguments for _why_ — they just "think it would be a good idea". (I'm still willing to be convinced by some argument I haven't considered, but so far nobody's offered one.)

Sometimes the request is coupled, as it was in #1024, with a request that individual frames be displayed in the Timeline. While I agree that sub-second zoom would be necessary _**for that feature**_, that feature is the only real reason I can see for implementing sub-second zoom. And, more importantly, that feature isn't happening.)

**Comment by muddipper** [comment]
Frame-by-frame will be huge improvement because massively increase accuracy to the editing. Is just that simple.
One second 'usually' contain 24, 25, 30, etc depends on the videos. So sliding 1 frame each press instead of 1 second (24 frames) will be amazing.

**Comment by SuslikV** [comment]
@muddipper 
> So sliding 1 frame each press...

_Left Arrow_ and _Right Arrow_ keys on keyboard. Now, you know how to.

Zoom depends only on pixel size between the pair of zoom points. Right now this is 100px fixed.The navigation by mouse move is not correct because it places cursor anywhere (even between the frames). Nothing else require improvement. Accuracy and speed is not for OpenShot. Simple and handy is works much better here. Mistakes in the code is other thing.

**Comment by muddipper** [comment]
> Left Arrow and Right Arrow keys on keyboard. Now, you know how to.

Uh, I know about that. Sorry if my wording is bad because I'm an ESL. What I mean is pressing left/right arrows give you 1 second not 1 frame.
I just want to explain to ferdnyc that this feature will be huge improvement to OpenShot.

**Comment by SuslikV** [comment]
@muddipper You are thinking that this is seconds, but this is frames: https://github.com/OpenShot/openshot-qt/pull/3170

**Comment by muddipper** [comment]
Yes, how dumb I am. I just realized few minutes ago. Sorry.
Off topic: displaying frame numbers would be great addition too.

**Comment by cladelpino** [comment]
Please... just display the current frame, as a bare minimum... For example, for advanced exporting...
