### ISSUE TITLE
Segfault at exit if slider is moved around

### ISSUE THREAD

**Issue by ankitpati** [OpenShot/openshot-qt#892]
**System Details:**
* Operating System / Distro: Ubuntu 16.04
* OpenShot Version: 2.4.0 AppImage

**Issue Description and steps to reproduce:**

Ran into this while closing #612.

1. Import a simple 10 second `webm` clip.
2. Drag to timeline.
3. Right click > Time > Fast > Forward > 2X
4. Drag the slider back and forth a few times.

Problems:

1. The slider feels laggy when moving over the video clip.
2. Closing the window after that prompts to save the project, and _appears_ to gracefully exit, but inspecting the command line output shows that it sometimes segfaults. No data is lost, however. Unable to reproduce it after a few tries, so no log is attached.

**Comment by DylanC** [comment]
@ankitpati - Same results on v2.4.1?

**Comment by DylanC** [comment]
Unable to reproduce.

**Comment by ankitpati** [comment]
@DylanC It appears fixed now. Sorry I missed the last comment.
