### ISSUE TITLE
Can a frame of video be taken in Open Shot and saved as a tif or jpg file?

### ISSUE THREAD

**Issue by Rogerx56** [OpenShot/openshot-qt#893]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

**Comment by Rogerx56** [comment]
Thanks Dylan. Im new to OpenShot and asking questions about it.

**Comment by DylanC** [comment]
@Rogerx56 - Not that I know of but I guess for now you could take a screenshot(print screen) using your OS and crop the image with an image editor. Not ideal but it would work.

**Comment by DylanC** [comment]
@N3WWN - Sure,  no problem! :)

**Comment by N3WWN** [comment]
@DylanC Thank you, sir!

**Comment by N3WWN** [comment]
This issue can be closed as resolved

**Comment by N3WWN** [comment]
This issue can be closed as resolved
