### ISSUE TITLE
Length of movie on timeline not long enough

### ISSUE THREAD

**Issue by myswiat** [OpenShot/openshot-qt#894]
System Details:
Distro: Linux - Ubuntu 17.10 dev
OpenShot Version: 2.4.0
Video:
https://youtu.be/pByNzRzj10k

The program is completely unusable. The reason is the length of the movie on the time line, which is not as long as it should be.

**Comment by Just-Curious** [comment]
![20160916_howlong](https://user-images.githubusercontent.com/16257232/30514943-4569ab34-9aed-11e7-988d-55ee4079ad24.jpg)

**Comment by myswiat** [comment]
The program is not usable.
To make everything clear: https://youtu.be/dHCSXEthUzA

**Comment by DylanC** [comment]
@Just-Curious - Thanks for the screenshot

**Comment by Just-Curious** [comment]
I'm not sure I've understood yet, but I think I may have at least stumbled onto something related.  If the right hand edge of a timeline video is dragged to the right (impossible), the display length shrinks.  Doing this repeatedly leaves a "blank" area on the timeline that, in fact, contains the "missing" video.  Dragging a video to the timeline and allowing it to "snap in", will result in it snapping to the correct ending of the original video.  Adjusting the time scale corrects the display.  It's on YouTube:

https://youtu.be/qVxH2ml8OXw

**Comment by Just-Curious** [comment]
Another YouTube video demonstrating double audio in the overlap, etc.

Incidentally, this is OpenShot 2.4.0 on Windows 10 Pro.

**Comment by DylanC** [comment]
@Just-Curious - Thanks!

**Comment by peanutbutterandcrackers** [comment]
Is this issue still persistent in v2.4.1 or the [daily builds](https://github.com/OpenShot/openshot-qt/releases/tag/daily)?

**Comment by DylanC** [comment]
@peanutbutterandcrackers - Was not able to produce this issue on Ubuntu 17.10 today.

**Comment by peanutbutterandcrackers** [comment]
Perhaps some commit fixed it o.O ?
