### ISSUE TITLE
Audio muteing

### ISSUE THREAD

**Issue by captainwasabi** [OpenShot/openshot-qt#897]
**System Details:**
* Operating System / Distro: ?
Windows 10
* OpenShot Version: ?
2.4.0
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
Need to be able to mute a video track, and for video tracks that have multi channel audio there should be an option for each channel to be muted separately

**Comment by Just-Curious** [comment]
![20160916_audiokeyframes](https://user-images.githubusercontent.com/16257232/30515326-61296246-9af3-11e7-847f-dfe6973abac9.jpg)
![20160916_audiomute](https://user-images.githubusercontent.com/16257232/30515327-612b56be-9af3-11e7-9108-d1084e9991d4.jpg)

**Comment by DylanC** [comment]
@captainwasabi  - Follow answer by just-curious.
