### ISSUE TITLE
File "distfiles" seems to be broken

### ISSUE THREAD

**Issue by Axxando** [OpenShot/openshot-qt#9]
Windows 7 64-bit
Installer version of 11/01/2016

![11-01-2016 10-54-52](https://cloud.githubusercontent.com/assets/9532691/12230565/aa92465e-b851-11e5-87da-76979529e934.png)

**Comment by Axxando** [comment]
Another complete download fixed the problem.

**Comment by jonoomph** [comment]
Cool, thanks for the update! Closing issue.
