### ISSUE TITLE
Openshot-qt crashes after render dialog choosing replace a file

### ISSUE THREAD

**Issue by KandaAkio** [OpenShot/openshot-qt#900]
**System Details:**
Kernel: x86_64 Linux 4.12.12-1-ARCH
Resolution: 1920x1080
DE: Gnome
WM: Gnome-Shell
GTK-Theme: OSX-Arc-Darker [GTK2/3]
CPU: Intel Core i7-4710HQ @ 8x 3.5GHz [51.0°C]
GPU: GeForce GTX 860M
RAM: 8GB

Operating System / Distro: Arch Linux
OpenShot Version: 2.4.0

**Issue Description and steps to reproduce:**
I created a video made of pictures and exported it as MP4 720p standard format and took a simple name with small characters and no special signs. Then i created a new project, imported this video made of pictures coz i wanted to add a music. Furthermore i imported a mp3 music file and put the video on channel 1 and music on channel 2. Then i exported the video as MP4 and choose the same name. Then a dialog opened, asking me if i wanna replace the file. I choose yes. Then the programm closed, no processor activity and i cant open openshot anymore. Just restart my PC and it works. But the export failed without any error report.

**Comment by DylanC** [comment]
@KandaAkio - I think this problem has been fixed in v2.4.1. Please give it a try.
