### ISSUE TITLE
Video not playing but audio still plays

### ISSUE THREAD

**Issue by MarkoA12** [OpenShot/openshot-qt#901]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

When I import a video it does not play but the audio plays. It's the same thing on the preview.

**Comment by JtLively** [comment]
We need the answers to these questions to further troubleshoot
    Operating System / Distro: ?
    OpenShot Version: ?
    Please attach log files if crash
    Screenshot.

Please try the newest version and create a new issue with details if this reoccurs .
