### ISSUE TITLE
cutting takes longer and longer as video becomes more complex

### ISSUE THREAD

**Issue by kpande** [OpenShot/openshot-qt#902]
**System Details:**
* Operating System / Distro: Gentoo amd64
* OpenShot Version: 2.3.4

**Issue Description and steps to reproduce:**

When I'm editing 2.7K GoPro footage (hero 3 black) it works alright for a while but once the project has built up with a couple hundred cuts (from 4 hours down to 45 minutes) it starts to take longer to cut the tracks.

I notice if I use `CTRL+K` to keep both sides it takes twice as long (15 seconds) as `CTRL+J|L` (8 seconds)

**Comment by omichel** [comment]
Same problem on Windows 10, OpenShot 2.4.0. This was also reported in #961.

**Comment by PontiacCZ** [comment]
Oh, I thought it was only Windows problem (I have Win 7 x64) but it is on Linux too... Odd. With 2 minutes of clips on the timeline each cut takes from 5 to 10 seconds on my machine (AMD A10-5800 (4 cores @ 3,8 GHz), 16 GB RAM (8 GB reserved for OpenShot cache)).

I stopped working on my project and I am waiting until this one is fixed...

**Comment by kpande** [comment]
@PontiacCZ I switched to kdenlive and have a much better experience as long as you disable GPU rendering. OpenShot has some render bugs too, which kdenlive does not.

**Comment by SirDaedalus** [comment]
I read a fabulous review of OpenShot in Germany's c't magazine. Downloaded it and started cutting videos. Unfortunately experiencing the same problem as reported above (also similar to #550): Cutting one .mpg (45 minutes, 720*576) into pieces on the timeline, shifting it, shortening / extending it blocks my PC at 100% CPU load for 30 - 60 seconds.

Although exporting works perfect, the forced lags make the software unable to use.

**Details:**
- Operating System: Windows 10 Pro x64
- OpenShot: 2.4.
- Intel Core i7-2677M @ 1.80GHz, 4 GB RAM

Please let me know how I can help / what Information you need to reproduce this on your end.

**Comment by kpande** [comment]
@SirDaedalus can you create an example project and upload to Github for the developers to try and reproduce it with?

**Comment by SirDaedalus** [comment]
Sure, here you go:
[1993 04 Bodensee.zip](https://github.com/OpenShot/openshot-qt/files/1813013/1993.04.Bodensee.zip)
Overall I have 8 * 1hr videos to cut. While I managed to sit through / finish one of them yesterday evening (I read two pages on my kindle after every new trim command, no need to say that this was still a bit annoying) I just realized that I just can't do this for another 7 evenings (especially since this could be cut in 1 hr overall if there were no lags).

**Comment by ronanharris09** [comment]
Does OpenShot uses any caching method ? I mean most of peoples who uses the 64 bit version mostly has  a generous amount of RAM, something should've been wrong with the way how OpenShot manages resources on Windows OS, I'll try to compare the resources usages between Windows 10 x64 and another Linux Distribution ( Solus 3.99 x64 ).

**Comment by peanutbutterandcrackers** [comment]
Perhaps trying out the latest [daily build](https://github.com/OpenShot/openshot-qt/releases/tag/daily) will help you out? It has got a few improvements to it, than v2.4.1.

v2.4.2 is on the way and will address a lot of these windows-specific issues. Please do look forward to it.

**Comment by SirDaedalus** [comment]
Awesome, I tried out OpenShot-v2.4.1-15-gbdb1546-57-674-x86_64.exe and it works like a charm!

Thanks a lot!

**Comment by kpande** [comment]
(this is a Linux issue)

**Comment by kpande** [comment]
I don't really care for OpenShot anymore, I don't use it, someone else can open the bug report because I don't want to be involved in this project.

**Comment by peanutbutterandcrackers** [comment]
@kpande - Ooops. My bad. I thought this was windows. Silly me. Perhaps you'd like to try out the latest daily build of OpenShot, too? Or, perhaps even compile it yourself (seeing that you run gentoo). We have recently got a [developer's guide](https://www.openshot.org/static/files/user-guide/developers.html) page that should help you out with this. But if you don't want to use OpenShot, then that's fine too. [Too bad, we could have used some more help here from talented people like yourself, good sir.]

**Comment by SirDaedalus** [comment]
Although using OpenShot-v2.4.1-15-gbdb1546-57-674-x86_64.exe solved the initial problem (PC blocked at 100% CPU time, see above), I just experienced that it does not yet solve it completely: While the first cuts of an an .mpg file (720*576) work great, the more cuts clips you have in one project (noticable from > 20 cuts / clips onwards), the longer each cut takes (~ 10 seconds at 100% CPU time).

**Comment by peanutbutterandcrackers** [comment]
@SirDaedalus: Okay. I will try to bring the attention of the devs to this too... Please do look forward to v2.4.2. All of these issues should be resolved by then. :)
