### ISSUE TITLE
Crashing after editing clip time #BUG#

### ISSUE THREAD

**Issue by Yo-kai-Sei-shin-kage** [OpenShot/openshot-qt#903]
**System Details:**
* Operating System / Distro: Linux 4.4.87-1-MANJARO (Arch based), 4.9 LTS  kernel
* OpenShot Version: 2.3.4
* Crash log file: https://www.dropbox.com/s/q1t82elvn130u4g/openshot-fail.png?dl=0

**Issue Description and steps to reproduce:**
1.) As either non-root user or root user, start openshot-qt from terminal.
2.) Import mp4 video file.
3.) Drag and drop imported file into track 1.
4.) Right click on clip and mouse over "time" > Fast > Forward > 2x.
5.) Click play button for preview.
Crash occurs immediately after step 5.

**My Suggestion:**
Port to C99 standard ANSI C language. Python does not handle stack tracing properly in the libraries from Qt dev kit.

**Comment by DylanC** [comment]
@Yo-kai-Sei-shin-kage - I would recommend to try the latest daily build.

**Comment by DylanC** [comment]
Dup of #588

**Comment by DylanC** [comment]
Confirmed as fixed in #588
