### ISSUE TITLE
Audio Distortion

### ISSUE THREAD

**Issue by chall7394** [OpenShot/openshot-qt#904]
**System Details:**
* Operating System / Distro: ? **Windows 10 Pro Version 1703**
* OpenShot Version: ? **2.4.0**
![openshotaudio](https://user-images.githubusercontent.com/32016310/30512737-b84e1786-9ac3-11e7-9c7b-2ca4a046465a.PNG)

* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
Any audio imported, distorts after 2 1/2 minutes.

**Comment by Just-Curious** [comment]
•Operating System / Distro: Windows 10 Pro Version 1703
•OpenShot Version: ? 2.4.0

Any?  On my system, MP3s exhibit that symptom, APEs are worse, but others appear OK.

![20170916_audiotypes](https://user-images.githubusercontent.com/16257232/30514101-e39b6222-9adc-11e7-87da-e6195b3e6da2.jpg)

**Comment by ffurano** [comment]
I am experimenting the same, with 2.4.0, tried ogg, aif, wav. The clicks disappeared when setting the project to the same frame rate of the clips (25fps)

**Comment by DylanC** [comment]
@chall7394 - This has been confirmed as fixed in the v2.4 daily build.  See #618 and related tickets.
