### ISSUE TITLE
Hidden preferences dialog blocks main window

### ISSUE THREAD

**Issue by itsharrie** [OpenShot/openshot-qt#906]
**System Details:**
* Operating System / Distro: Mint 18.2 64bit
* OpenShot Version: 2.4.0

Steps:
- Open Openshot
- Open Edit -> Preferences dialog
- Click on main window, e.g. click **Help** menu

Result:
The main window gets focus, the Preferences dialog disappears
The main window is blocked by the invisible Preferences dialog.

Remedy:
Diable main window while Preferences dialog is open.

**Comment by DylanC** [comment]
@itsharrie - Thanks, I will give it a try.
