### ISSUE TITLE
Cannot abort rendering animated title

### ISSUE THREAD

**Issue by itsharrie** [OpenShot/openshot-qt#907]
**System Details:**
* Operating System / Distro: Linux Mint 18.2 64bit
* OpenShot Version: 2.4.0

**Issue Description and steps to reproduce:**
Cannot abort rendering animated title.
Steps:

- Menu -> Title -> Animated Title
- In Animated Titles dialog select a thumbnail and click Render.
- While rendering one cannot cancel the process, **Cancel** does not work, closing the dialog (X) closes the dialog however it does not abort the rendering process. Control over the rendering process is lost.

Proposed solution:
Make both the Cancel button and the Closing the dialog window abort the rendering process and close the dialog.

**Comment by DylanC** [comment]
Confirmed.

**Comment by misscbeezy** [comment]
This is also the exact same case with Windows 7 as well!

**Comment by ferdnyc** [comment]
This is fixed as of the Blender 2.80 compatibility update in the devel tree, and will be part of the next OpenShot release. Closing.
