### ISSUE TITLE
Use clip name in title preview window

### ISSUE THREAD

**Issue by itsharrie** [OpenShot/openshot-qt#908]
**System Details:**
* Operating System / Distro: Linux Mint 18.2 64bit
* OpenShot Version: 2.4.0

**Issue Description and steps to reproduce:**
The name of Title preview windows is always **Preview**
Hence, all preview windows in the applications tray share the same name. The user cannot pick the desired preview without trying them all.

Steps:
Select a project file, right click and select **Preview File**.
Repeat this with some more files in **Project Files**.

**Proposed solution:**
Use the filename of the clip as window name.

**Comment by DylanC** [comment]
@itsharrie - Thanks for your reports. They contain some good info.
