### ISSUE TITLE
Unexpected behaviour of Rewind and Fast Forward controls

### ISSUE THREAD

**Issue by itsharrie** [OpenShot/openshot-qt#909]
**System Details:**
* Operating System / Distro: Linux Mint 18.2 64bit
* OpenShot Version: 2.4.0

**Issue Description and steps to reproduce:*

1. When the **Rewind** control (in **Video Preview**) is clicked, while the play-head is stationary, the play-head starts moving forward rather than backward (same as **Play**). Only when clicked again the playhead starts moving backward as intended. Proposed solution: Make it move backward right away.

2. The feature of increased speed on repeatedly clicking **Rewind** or **Fast Forward** is nice. However slowing down Fast Forward by clicking Rewind (and vice versa) is imho counter intuitive. Proposed solution: While playing fast foward, **Rewind** reverses the playing direction right away, whatever the current fast forward speed is. Same applies for **Fast Forward** while playing in rewind mode.

3. The expected behaviour of Rewind is moving the playhead towards the start of the track (clip) without showing the contents, which actually is the behaviour of the **Jump To Start** control. Proposed solution: Rename '**Rewind**' '**Play Backward**' or '**Play Reverse**' or any more suitable phrase.

4. The expected behaviour of **Fast Forward** is to move the play-head to the end of the track (clip) without showing the contents. A more unambiguous phrase would be **Play Fast Forward**. Because the Play control plays the clip at normal speed, the **Play Fast Forward** control should start at double speed on the first click.

**Comment by DylanC** [comment]
@itsharrie - Thanks for the feedback. We will discuss.

**Comment by ferdnyc** [comment]
1. Yeah, this is definitely broken, clicking "Rewind" from the Pause state shouldn't start the video playing _forwards_.

1. I don't think reversing _at the same speed_ makes sense. If **that** were going to be the action, I'd think it would make more sense to have a playback speed control (either Speed Up/Down buttons, or a slider, or whatever), plus a separate Reverse button that switches direction. I'm not sure what I think of that, but I think it makes more sense than having the Rewind control go from Fast-motion Forward to Fast-motion Reverse in a single click. Plus, if it reversed at the same speed then how would you slow down the play head? You'd be able to speed it up (by clicking in the same direction again), but you'd have no way to _decrease_ the speed.
    
    We should really look at what other editing-bay type systems do for their playback controls, focusing on ones that don't suck. (If there are any.) Though I suspect most that suck _less_ are using some type of hardware shuttle-wheel control, which isn't really feasible in software. At least, any attempt I've ever seen to emulate it with a WIMP* interface has been an utter disaster. (In a sense, OpenShot's current Rewind and Fast-Forward buttons act as turns of a shuttle wheel in the given direction, at least conceptually. Though I'm in agreement that it's not particularly intuitive/comfortable.)

1. & 4. I don't agree at all. "Rewind" and "Fast Forward" aren't really well defined terms anymore, as they're a bit analog and digital is more flexible. But even in digital, _Seek_ Backwards and _Seek_ Forwards (which is what the Rewind & Fast-Forward controls represent) are expected to scrub through the video, as they do. _Skip_ Backwards and _Skip_ Forwards are the controls that would be expected to instantly move to the extremes of the video, and that's what the "Jump to Start/End" buttons do. (Except, with the wrong icons, as also pointed out in #920 — they should be using 'media-skip-backward' and 'media-skip-forward' from the media icon set, not 'go-first' and 'go-last' from the navigation set, as those are also used for the skip-marker buttons on the timeline toolbar.)

\* – (Window-Icon-Mouse-Pointer)
