### ISSUE TITLE
Bug report; OpenShot 2.0.6 |  OS: Windows 10 | Hardware: Dell Inspiron 3541

### ISSUE THREAD

**Issue by 14142000** [OpenShot/openshot-qt#91]
The application hangs when playback is running making impossible to stop unless you make a lucky click, also for some reason it will not let me use system fonts or installed fonts.  Also using the stream version of blender with this is a nightmare, it keeps opening the command line on every transition switch.
![capture](https://cloud.githubusercontent.com/assets/3375830/13025423/a23d46ae-d1cc-11e5-841d-e95859e740d6.PNG)

**Comment by jonoomph** [comment]
This is similar to #116 (I think). As for the Blender issue, I'm not aware of that. We can track that bug here, if you have some screenshots and/or more details on your setup. Have your tried with the regular download of Blender?

**Comment by 14142000** [comment]
Yes I have. It still pops open the blank command prompt
