### ISSUE TITLE
Properties inputs not restricted to meaningful values

### ISSUE THREAD

**Issue by itsharrie** [OpenShot/openshot-qt#911]
**System Details:**
* Operating System / Distro: Linux Mint 18.2 64bit
* OpenShot Version: 2.4.0

**Issue Description and steps to reproduce:**
In the Clip Properties window inputs are not restricted to meaningful values. E.g. Scale X input values beyond the 0..1 range are allowed but not meaningful.

Proposed solution: Restrict all input to meaningful values.

**Comment by DylanC** [comment]
@itsharrie - We will discuss this. Thanks.
