### ISSUE TITLE
Saturation slider control does not work properly

### ISSUE THREAD

**Issue by dancetheskies** [OpenShot/openshot-qt#912]
**W10
* OS V2.3.4-dev. 5
***Issue Description and steps to reproduce:**
The saturation control filter has no effect on the visible saturation while editing until the slider control is dragged to about 85, when the saturation then suddenly jumps to a much higher level.  The same happens in reverse when the slider is then dragged back down.

This should be easily replicated as indicated above.  It has been this way for a very long time.

**Comment by DylanC** [comment]
@dancetheskies  - Did you report this already or is it a separate issue?

**Comment by dancetheskies** [comment]
I assume you must be referring to the unusual long delays I get occasionally when manipulating videos on the time line?  I have not reported that as a separate issue.  It only happens on occasion, and normally recovers after the delay and the program functions normally when it recovers.  It could be an issue with other background tasks hogging CPU time, though my PC has an Intel i7 (Skylake) CPU with 16GB of memory, so it shouldn’t have a problem like this.

**Comment by dancetheskies** [comment]
This issue can be closed.  My initial post above was in error.  I meant to say the CONTRAST control slider does not work properly, but I had reported that quite some time ago and is being address as a separate issue.  Then I got the above email from DylanC, but it did not have this issue quoted in it, and my reply above was for a different issue (long delay periods with nothing happening during editing on the time line) that I reported as a side comment.  I should have come here to answer the email.  So there's been a mixing of issues in my posts.  Issue #695 regarding the CONTRAST slider control is still valid and being worked on, and this issue #912 can be closed since it is invalid due to my brain F@&T :-{.

**Comment by dancetheskies** [comment]
DylanC,

Please disregard my email below.  I replied to your question below BEFORE I went to the GitHub to view the issue which does not get quoted in your email to me.  I thought you were referencing my prior email to you about Contrast slider not working when I mentioned long delays before the program acts on an edit.  After I went to read the issue #912 on GitHub, I see I opened this issue #912 in error regarding the Saturation slider, which works as it should.  I meant to say the CONTRAST slider control does not work properly, but post #912 wasn’t needed since I had reported this quite some time ago in issue #695.  I closed issue #912 since it’s an error on my part in more ways than one!  Sorry for my confusion.  I’ll remember to answer on GitHub from now on.



Tom

--------------------------------------------------------------------------------

**Comment by DylanC** [comment]
@dancetheskies - No problem. Thanks for sorting it out!
