### ISSUE TITLE
Rename 'Properties' 'Clip Properties'

### ISSUE THREAD

**Issue by itsharrie** [OpenShot/openshot-qt#913]
**System Details:**
* Operating System / Distro: Linux Mint 18.2 64bit
* OpenShot Version: 2.4.0

**Issue Description and steps to reproduce:**

The caption of the **Properties** frame should imho be renamed **Clip Properties**, because these properties specifically apply to individual clips.

**Comment by ferdnyc** [comment]
I know this is an ancient issue (I'm going through ancient issues), but I don't think this would be a good idea. It's not entirely accurate. The Properties list displays the properties of the currently selected Timeline object — that could be a Clip, a Transition, or an Effect. It's not exclusive to Clips.

**Comment by ferdnyc** [comment]
Closing this, for reasons explained.
