### ISSUE TITLE
Non-descriptive property values

### ISSUE THREAD

**Issue by itsharrie** [OpenShot/openshot-qt#915]
System Details:

    Operating System / Distro: Linux Mint 18.2 64bit
    OpenShot Version: 2.4.0

**Issue Description and steps to reproduce:**
In the Properties frame several non-descriptive property values are used, such as _-1_ for _None_ or _Undefined_, _0_ for _Disabled_, _1_ for _Enabled_.

Proposed solution: Use descriptive values instead.

Did I already mention that I like OpenShot very much?

**Comment by ferdnyc** [comment]
I believe I got most if not all of those, with an update a while back that added "Auto", "Off", and "On" labels in place of -1, 0, 1.
