### ISSUE TITLE
Beta 3 - Does not add the whole clip to the timeline. 

### ISSUE THREAD

**Issue by poetimp** [OpenShot/openshot-qt#92]
When I add a clip to the time line it is often truncated

**Comment by DerGenaue** [comment]
Can you give more details, as most users don't experience this?
Can you narrow it down to a specific video format?
How often does it happen?

**Comment by poetimp** [comment]
I have tried to reproduce it and have not been successful. I have updated since I tried las to it may have been addressed.  You can close this as unreproducible and if I see it again I will open a new issue with more detail.

**Comment by nwgat** [comment]
you need to close it your self and btw you can re-open it later ;)

**Comment by poetimp** [comment]
Closing myself.  Learn something new every day :)
