### ISSUE TITLE
preview and video exported doesnt match

### ISSUE THREAD

**Issue by paco2l** [OpenShot/openshot-qt#922]
**System Details: **
* Operating System / Distro: W10 ?
* OpenShot Version: 2.4 ?

**Issue Description and steps to reproduce:**
right click > time > freeze >2seconds
at some point of this do the next:
right click > time > freeze and zoom >2seconds
add another video at some point of this effect, and remove the transition
when you export you get a video different to the preview, I mean, the preview is ok, showing the effects right, but the video exported miss frames and does a completely different thing

export settings I'm using are: hd 1080 30 fps, mp4(h.264), quality high

**Comment by paco2l** [comment]
I changed export settings to avi(h.264) and it crashed

**Comment by paco2l** [comment]
it seems like the freeze time effect is the cause of the malfunction, in the preview works ok but after export it takes effect 2,5 seconds earlier the point it was programmed, missing all the frames in between

**Comment by DylanC** [comment]
@paco2l - Does this work on v2.4.1?

**Comment by DylanC** [comment]
Sync issues are resolved in v2.4.1. I suggest giving it a try.
