### ISSUE TITLE
drag and drop fail

### ISSUE THREAD

**Issue by paco2l** [OpenShot/openshot-qt#923]
**System Details:**
* Operating System / Distro: W10?
* OpenShot Version: 2.4.0?

**Issue Description and steps to reproduce:**
if the video clip name contains the spanish's letter "ñ" drag and drop doesn't work

**Comment by DylanC** [comment]
Dup of #677.

**Comment by DylanC** [comment]
@paco2l - This has been resolved in the daily builds now.
