### ISSUE TITLE
Video Preview not updated after removal of clip

### ISSUE THREAD

**Issue by itsharrie** [OpenShot/openshot-qt#926]
System Details:

Operating System / Distro: Linux Mint 18.2 64bit
OpenShot Version: 2.4.0

**Issue Description and steps to reproduce:**
Remove a clip that is currently visible in **Video Preview**.
The removed clip remains visible in **Video Preview**.

Proposed solution:
Update the **Video Preview** frame after changing the **Time Line** contents

**Comment by ctsdownloads** [comment]
Unreproducible, old version of OpenShot
