### ISSUE TITLE
Export a movie over previously saved version, Launch.exe crashed

### ISSUE THREAD

**Issue by davefrostlion** [OpenShot/openshot-qt#927]
**System Details:**
* Operating System / Distro: win 10 64
* OpenShot Version: 2.4
* _Please attach log files if crash_ 

I have had the same issue as multiple users.. to fix, to no avail I have re installed display adapt, Micro c ++, openshot, blender, and all the other alternatives one can find...  It began suddenly when I tried to export a movie over top of the previously saved version of same movie, it began exporting, crashed, and has not started since.. launches, shows display and almost simultaneously the Runtime Error halts all progress, it then announces windows must close the program... 

No changes were made to any part of pc, I installed openshot yesterday, got the paths for blender working today finally, and this afternoon, it will no longer function. 

There is no help topic that actually either fixes this directly, or acknowledges that it is "an unfixed bug".. please advise, I can not access the project obviously that we spent the day on, I can't imagine what long time users are going through...  any help would be noble and appreciated bud.... t y

**Comment by DylanC** [comment]
@davefrostlion - I'm sure saving over the same filename is a bug at the moment. I have seen similar reports of this issue.

**Comment by DylanC** [comment]
@davefrostlion - This should be working in the latest daily build.

**Comment by pavelsr** [comment]
@DylanC, I have a same problem as @davefrostlion, tried with latest 2.4.1 version but no changes, openshot is hanging during exporting video

Watched on CPU and memory utilitzation, there is no bottleneck

CPU: Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
RAM: 16 GB
OS: Windows 10 Pro

How to debug?

I love openshot but this bug is very critical and annoying, I lost hours, so I need to have this issue fixed. 

@davefrostlion, try to use for now other opensource editors, like [Kdenlive](https://kdenlive.org/) or [Shotcut](https://www.shotcut.org/)

**Comment by DylanC** [comment]
@pavelsr - Thanks. I will let the guys know.

**Comment by DylanC** [comment]
@davefrostlion - Should be working in v2.4.1 now.

**Comment by thepodfather** [comment]
First of all, thanks for a great program!
I have this issue as well with version 2.4.1 on Windows 10.  
I import an .mp4 file that I had previously saved from OpenShot, cut 15 seconds off of the front end and try exporting it to the same filename and get a C++ Runtime Library error indicating that launch.exe "has requested the Runtime to terminate in an unusual way".  
![openshot_error](https://user-images.githubusercontent.com/12435095/33431142-3a620aee-d5a1-11e7-898e-3e44ea29f567.PNG)
Tried uninstalling, reboot computer, reinstall and immediately get the same problem and interestingly enough the file that I was editing shows up automatically in the Project Files area after a clean install (which is probably causing the problem to persist).  I'm guessing something is not being cleaned up during the uninstall?

**Comment by DylanC** [comment]
@thepodfather -  Delete your backup.osp file and maybe try not to write over your input file.

**Comment by DocNoNo974** [comment]
Hello,
I uninstalled and deleted the% HOMEPATH% \. openshot_qt folder.
I redid the installation and the problem was fixed.

Openshot v2.4.1 Windows 10 x64
