### ISSUE TITLE
How to rotate an image clip around the center of the screen?

### ISSUE THREAD

**Issue by ttamttam** [OpenShot/openshot-qt#928]
I'm trying to have a gear image clip rotate continuously.

This works, but I can't figure out how I can avoid the gear to move around the frame (X and Y).

Another way to express it is I do not understand where the rotation center is located. Or better, how to specify where it should be?

Thanks

**Comment by DylanC** [comment]
@ttamttam - Does #694 answer your question?

**Comment by ttamttam** [comment]
I dont't think so.
Or there is something I did not understand?

My goal it to animate an image, without any translation. Only a rotation around it's center.

What I tried:
- Imported a square (SVG) image
- I tried to modify the Rotation property, but could not understand how to adjust the rotation center?
- I also tried the Transform tool, with the same problem.

Imagine that my image is a wheel. I would like to see it spin around it's center, without any translation of the center of the image.

I think that the video linked in #603 displays my problem?

Thanks

**Comment by DylanC** [comment]
@ttamttam - Thanks. Maybe I didn't understand at first. Perhaps we don't have this feature currently then. I can check it out for you.

**Comment by ttamttam** [comment]
@DylanC  - Thanks for answering! Yes, I would appreciate a more definitive answer. I may have a look in the code in the future, and propose a solution, but this is not possible in the near future.

**Comment by DylanC** [comment]
@ttamttam - I think we do not have this feature currently. Marking as enhancement.
