### ISSUE TITLE
No contents after double-clicking OSP if an instance of OpenShot is open.

### ISSUE THREAD

**Issue by Just-Curious** [OpenShot/openshot-qt#929]
**System Details:**
* Operating System / Distro: ? Windows 10 Pro
* OpenShot Version: ? 2.4.0
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

Start OpenShot, double-click an OSP in File Explorer, as shown in this YouTube video: https://youtu.be/AVgHzZQmt8I,

Related to #895?

**Comment by DylanC** [comment]
@Just-Curious 

The latest daily build solves issues with those special characters and spaces:

https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.4.0-9-g7267417-56-648-x86_64.exe

Let me know if it is now working for you.

**Comment by DylanC** [comment]
Dup of #677

**Comment by Just-Curious** [comment]
Not a duplicate, but appears fixed in version 2.4.1.
