### ISSUE TITLE
Provide an AppImage

### ISSUE THREAD

**Issue by probonopd** [OpenShot/openshot-qt#93]
Please consider providing an [AppImage](http://appimage.org) as suggested [earlier](https://bugs.launchpad.net/openshot/+bug/1170972). 

This would allow Linux users to just download, chmmod a+x, and run OpenShot.

By distributing OpenShot in the AppImage format, you could reach users on all major desktop distributions. Cross-platform application projects like Scribus, Krita, and Subsurface (these are all Qt-based) [are adopting AppImages](https://github.com/probonopd/AppImageKit/wiki/AppImages) as an easy way to bring bleeding-edge releases to users on all major Linux desktop distributions. 

Some examples can be found at https://github.com/probonopd/AppImages/recipes and the resulting AppImages can be downloaded [here](https://bintray.com/probono/AppImages).

**Comment by jonoomph** [comment]
I'm very much in favor of this idea! I just don't have much free time to look into it. If you (or someone else) is interested, I would be happy to answer questions and assist. I'm already responsible for packaging on Window, Mac, and Ubuntu... I can' bear to add one more. haha. =)

**Comment by jonoomph** [comment]
I've given this a try with not too much luck. I understand the basic approach, and have created an AppDir that works on my development machine (i.e. running the AppRun script launches the app). However, after compiling the AppDir into an AppImage, it throws a permission error: **execv error: : Permission denied**.

There are also a few challenges creating a portable linux version of OpenShot 2.x:
- Python 3 is required (which is why I use cx_Freeze on Windows and Mac)
- Qt5 is required, and will conflict with a different installed version (since plugins are detected and loaded at runtime)
- The version of Qt5 built by many distros is not portable, thus, I might need to create another machine with more "portable" versions of the dependencies, before trying to freeze everything.

I'll keep researching this, but so far, the OpenShot, Python3, and Qt5 binaries don't seem very agreeable to running on other platforms, regardless of the AppImage related challenges. =)

**Comment by jonoomph** [comment]
For what it's worth, here is the strace output when executing the compiled AppImage:
[AppImage-Strace-Output.txt](https://github.com/OpenShot/openshot-qt/files/180665/AppImage-Strace-Output.txt)

**Comment by jonoomph** [comment]
Okay, so I'm feeling a bit dumb. Here is what fixed my error. `chmod a+x ./AppRun`. I now have a working frozen version of OpenShot, and an AppImage that works in a few different versions of Ubuntu. Now I'll start testing on a few different distros and see what breaks. =)

**Comment by probonopd** [comment]
> Python 3 is required (which is why I use cx_Freeze on Windows and Mac)

You can (and should) bundle Python 3 inside the AppImage.

> Qt5 is required, and will conflict with a different installed version (since plugins are detected and loaded at runtime)
> The version of Qt5 built by many distros is not portable, thus, I might need to create another machine with more "portable" versions of the dependencies, before trying to freeze everything.

You can (and should) bundle Qt5 inside the AppImage. Make sure you build on a not-too-recent distribution so that the resulting binaries can run on as many distributions as possible; usually binaries work well on newer but refuse to run on older distributions than the one used for building. I have had execllent results by building Qt5 on CentOS 6, the resulting binaries run on almost all desktop distributions used today, including debian oldstable. For an example, see https://github.com/probonopd/AppImages/blob/master/recipes/scribus/Recipe

> I'll keep researching this, but so far, the OpenShot, Python3, and Qt5 binaries don't seem very agreeable to running on other platforms, regardless of the AppImage related challenges. =)

That's the main challenge indeed; luckily we have solved these things for other Qt5 and Python apps already. So feel free to look around in https://github.com/probonopd/AppImages/blob/master/recipes and ask questions.

**Comment by jonoomph** [comment]
This is done, and tested with Arch, Debian, Fedora, Gentoo, openSUSE, and Ubuntu! It's automated and integrated into our build server now. Thanks again for the suggestion and your great work on AppImage!

**Comment by probonopd** [comment]
> This is done, and tested with Arch, Debian, Fedora, Gentoo, openSUSE, and Ubuntu! It's automated and integrated into our build server now. 

Wow. Awesome, simply awesome. Thank you.
Ran instantly on my Ubuntu 14.04.1 LTS box.

Is the build script publicly available, so that it can be referenced as an example for how AppImage generation can be integrated into an automated build process?

**Comment by jonoomph** [comment]
The build server is a home-grown Python script, so I'm not sure how "general purpose" it is, but here is the relevant part relating to generating the AppImage: https://github.com/OpenShot/openshot-qt/blob/master/installer/build-server.py#L315. Thanks!

**Comment by probonopd** [comment]
Tested this successfully (in the sense of: app does run) on the following OSes:
- CentOS-7-x86_64-LiveGNOME-1511.iso
- Chromixium-1.5-amd64.iso
- debian-live-8.0.0-amd64-xfce-desktop+nonfree.iso
- elementary_OS_0.3_freya_amd64.iso
- Fedora-Live-Workstation-x86_64-22-3.iso
- Fedora-Live-Workstation-x86_64-23-10.iso
- kali-linux-2016.1-amd64.iso
- kali-linux-2.0-amd64.iso
- SL-72-x86_64-2016-02-03-LiveDVDgnome.iso
- ubuntu-14.04.1-desktop-amd64.iso
- xenial-desktop-amd64.iso

Test script used:
```
wget https://github.com/probonopd/AppImageKit/raw/master/AppImageAssistant.AppDir/testappimage
chmod a+x testappimage 
sudo find *amd64*iso -exec bash testappimage OpenShot-2.0.7.AppImage >> log 2>&1 \;
sudo find *amd64*iso -exec bash testappimage {} OpenShot-2.0.7.AppImage >> log 2>&1 \;
grep -r SUCCESS log | cut -d " " -f 3 | cut -d "/" -f 5 | sort | uniq
```
Does __not__ run on CentOS-6.7-x86_64-LiveCD.iso:
```
/mnt/usr/bin/launch: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /mnt/usr/bin/libpython3.4m.so.1.0)
```
If you would like to get it running on older systems like CentOS 6, I recommend to build the AppImage inside a CentOS 6 chroot. (However CentOS 6 is considered outdated as a desktop OS by some now so it might not be a big concern.)

**Comment by shoogle** [comment]
An OpenShot user on Facebook commented that the AppImage fonts were too small for his high-res monitor. Might be linked to https://github.com/probonopd/AppImageKit/issues/125.

**Comment by probonopd** [comment]
Thanks for the hint @shoogle so let's try with 
```
export QT_STYLE_OVERRIDE=GTK+ # use system font size
```
