### ISSUE TITLE
DO NOT USE OPENSHOT

### ISSUE THREAD

**Issue by Soc1e7y** [OpenShot/openshot-qt#930]
**System Details:**
* Operating System / Windows 10 
* OpenShot Version: It doesn't matter all your crap versions confirm the same CONSTANT issue - read others who have posted 
* _Please attach log files if crash_ No, because nobody actually uses them or looks at them

**Issue Description and steps to reproduce:**

Im not going to waste time giving details as the team responsible for this program no longer cares to support it, nor correct functional aspects of the software. If you're using Windows 10 you will NOT be able to use this without crashing nonstop and more important lose HOURS of time. The program is currently unable to remain stable for exports resulting in any editing or work completed to be a HUGE loss.

**Comment by jonoomph** [comment]
Bugs are read and investigated. This one however is not very helpful.
