### ISSUE TITLE
Error message when importing image sequence starting from num 5 or higher

### ISSUE THREAD

**Issue by zort** [OpenShot/openshot-qt#932]
* Operating System / Distro: Windows 7
* OpenShot Version: 2.4.0

When you try to import an image sequence which starts from number 5 or higher, it fails, saying "[filename] is not a valid video, audio, or image file." This confused me because I thought Openshot thought the first file was corrupt or something. It should either successfully import the image sequence or tell you to renumber it starting from 0.

Steps to reproduce:  
1. Open Openshot
1. Make a directory containing two PNGs called 5.png and 6.png (Examples: https://user-images.githubusercontent.com/535865/30814579-952a154e-a1de-11e7-9a58-045fa2429160.png https://user-images.githubusercontent.com/535865/30814578-9526350a-a1de-11e7-8556-607355578f9c.png)
1. Drag the 5.png into Openshot's Project Files area
1. Click Yes in the dialog that pops up asking if you'd like to import it as an image sequence

**Comment by Just-Curious** [comment]
- Operating System / Distro: Windows 10 Pro
- OpenShot Version: 2.4.0

Easily replicated, but it seems the sequence can begin with '4', but not '5'.  Importing Title0010.png for each of the following has different results as described:

![20170925_smallsequence](https://user-images.githubusercontent.com/16257232/30822222-06fc2c72-a1f6-11e7-80f4-5a2ef55584dd.JPG)

If a failure does occur, the 'bad' image will be imported as a single picture.  Failure or no failure, only one sequence can be imported from a single folder.  If this is correct, the user's guide might mention it.
