### ISSUE TITLE
Aspect question

### ISSUE THREAD

**Issue by SporkThis** [OpenShot/openshot-qt#933]
**System Details:**
* Operating System / Distro: Ubuntu Studio 16.10
* OpenShot Version: Unsure (current) - not at system now.

I am under the gun, timeframe wise, to produce a budget music video using old standard format (3:4) video footage along with new footage in a widescreen format. When I add in the old footage it clips the edges (as it should in current format) but I need to expand it out to the edges of the video to match the new footage. How do I change the scale of the old video to match the new footage? I can letterbox the old footage to frame what I want but it is thrown out of whack when I export the video. I need to manually change the aspect and accept cutting off portions of the top and bottom of the footage so it conforms to the widescreen format.

**Comment by gjinxers** [comment]
SporkThis --- Have you found a work-around for your aspect issue yet?? I'm just a new user of OpenShot but my video aspect got skewered in between project session saves the other day. Literally only half of my video was playing in the preview window. The only way I could finally fix it was to move the pointer guide on the track to the very beginning of my mp4 file & then right-click on the track itself and select >>TRANSFORM. Once the bullseye & expansion squares appeared over my video in the preview window I was able to click the expansion squares &/or the bullseye to move my video where it needed to be within the preview space.  If you aren't familiar with the "transform" function in openshot, you need to make sure that the timeline pointer guide is exactly where you want the transformation to start and you need to click on your actual video within the track to complete/confirm the transformation and make the bullseye & squares go away.

Hope this helps....... If NOT, my apologies for commenting out of turn.

Good luck with your issue though.

**Comment by DylanC** [comment]
@SporkThis - This question seems to have been answered by a user. This looks to be a good answer on the topic.
