### ISSUE TITLE
How can I put in text?

### ISSUE THREAD

**Issue by KaosIsTrap** [OpenShot/openshot-qt#935]
I try to look around to see if there is any place to put text into my video and I can't find it, I also did the tutorial again and did not find it can you help me?

**Comment by DylanC** [comment]
@KaosIsTrap - From the menubar up to go to Title>>New Title.

**Comment by gjinxers** [comment]
@KaosIsTrap -- Did you get your issue figured out?? If not, I may be able to assist. I'm just a new user of the OpenShot program, but I'm putting together a tips/trick word doc together for my husband to learn some basic aspects of the program.  One of the things I'm including is the "text" vs "title" issue that some contributors have had from the past posts that I have read.

**Comment by DylanC** [comment]
@KaosIsTrap - If you want actual text I would recommend to create an image with text and a transparent background. Position this in the video where you want it to appear. There is no official method of doing it just yet in the editor as far as I know
