### ISSUE TITLE
Impossible to open a saved Project on OpenSHot 2.4.0

### ISSUE THREAD

**Issue by Gwennarzh** [OpenShot/openshot-qt#936]
**System Details:**OpenShot and Blender
* Operating System / Distro: Windows 10 64bit
* OpenShot Version: 2.4.0
* _Please attach log files if crash_
No file
**Issue Description and steps to reproduce:**
- i've done my first projet during the night and saved it - 
- this morning i would like to open it and... Nothing happens

The video is during around 4mn Something very quick with videos, pictures and music.

I've tried different solution like / double click on the file ProjectV1.0.osv or to open it through  Openshot via file/open a project.

It's very hard because it's the first time that i used this programm and i've worked around 3hours to do Something very clean for my friends.

Thanks for your help

**Comment by allzzzzz** [comment]
i cant open anything either

**Comment by omichel** [comment]
I had the same problem and found that the folder containing my project had non-ascii characters, e.g., french accent like in "vidéo". This apparently prevented OpenShot from loading properly my project. I could fix the problem by avoiding paths with non-ascii characters.

**Comment by DylanC** [comment]
Dup of #677

**Comment by DylanC** [comment]
@Gwennarzh - Try the latest daily build.
