### ISSUE TITLE
How to edit the Chroma Key effect?

### ISSUE THREAD

**Issue by gabfil** [OpenShot/openshot-qt#939]
**System Details:**
* Operating System / Distro: Linux ubuntu
* OpenShot Version: 2.4.0
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
Como editar o efeito Chroma Key

**Comment by DylanC** [comment]
@gabfil - I found this last time I used it. Add the effect and click on the effect on the timeline. You should have a Chrome Key properties appear on the left side. Here you can edit the colour and other options. Thanks.
