### ISSUE TITLE
Randomly & Unexpectedly CLOSES during an open project

### ISSUE THREAD

**Issue by gjinxers** [OpenShot/openshot-qt#941]
**System Details:**
* Operating System / Distro:      OS - Windows 7 Home Premium
* OpenShot Version:    v2.4.0 with most recent daily build downloaded per outlined steps within the "contributing" guidelines hyperlink provided on the "new issue" page.
* _Please attach log files if crash_ :  I followed the steps outlined in the "contributing" hyperlink provided within the "new issue" page, so I don't have any log files as of yet. I will attempt to reproduce the "crash" after I submit this issue for review.

**Issue Description and steps to reproduce:**
OpenShot keeps randomly closing while I'm working on a project causing me to repeat hours of work already completed once or twice.

It doesn't matter if I'm dragging/dropping any type of title, audio, pic or video into a track.   Sometimes, the program lags or the program window flashes before it closes but not always.  I periodically re-save my project while working out of habit from losing hours and hours of work in other programs, so the only consistency that I have noticed is that all of my text/title svgs that I have created and dropped into a track are lost between one project "save/save as" to another project save. Thank goodness only some of the text/title svgs are lost and not my videos or audio or ALL of my work altogether.

Also, I have noticed the drop-down (pop-up) menu boxes for the tracks or the content within the track have severe lag when populating whether I choose the "arrow" icon or right-clicking my mouse. The boxes are like non-existent sometimes momentarily and sometimes altogether and require a second or third attempt at opening them to select an option from the drop-down/pop-up list.

Please send an email or notification of some kind when/if this issue is resolvable, so that I can make sure to download the daily build in which this particular solution is included. 

Thank you for your time and assistance.

**Comment by DylanC** [comment]
@gjinxers - I would recommend to try the latest daily build. It has much important fixes.
