### ISSUE TITLE
Export to a file that is used

### ISSUE THREAD

**Issue by TheMysteriouz** [OpenShot/openshot-qt#942]
**System Details:**
* Operating System / Distro: Windows 10
* OpenShot Version: 2.4.0
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
If you export a project to a file that is used in the project, openshot crashes and the file is corrupted.

**Comment by DylanC** [comment]
@TheMysteriouz - I think the latest daily build includes a fix for this.
