### ISSUE TITLE
Only shows the tracks 

### ISSUE THREAD

**Issue by Carlpapaedits** [OpenShot/openshot-qt#943]
I'm not really sure whats going on. I just downloaded OpenShot, it told me to go through the tutorial, and I did. Now I'm stuck on a page that shows just the tracks. When I try to import a video it just doesn't show up. In the beginning of the tutorial It had a little box that shows pictures/videos, I suppose, but now its gone It just shows the tracks. Ive re-downloaded it twice.  Anybody know how to fix it? 

Thank you 👍

**Comment by Sumukha** [comment]
Same here. Did you get somewhere? Weird program.

**Comment by DylanC** [comment]
@Carlpapaedits - Did you try going to View>>Simple Views?
