### ISSUE TITLE
Old versions... pleeeeeeease?

### ISSUE THREAD

**Issue by chuckkh** [OpenShot/openshot-qt#944]
**System Details:**
* Debian Stretch x86 / Windows 7 x64 
* 1.4.3 - 2.4.0

The latest stable Debian, Stretch, contains Openshot 1.4.3. I have created a fairly complex project with it and have to continue on Windows. I have learned to work around the weaknesses of 1.4.3, and now I see that 2.4.0 has made several commands more complicated, involving several mouse clicks, etc. Also the file format seems to have changed completely and it all moves slower (this could be a Windows vs. Linux thing, but in general video performs better on my Windows installation, and regardless, I prefer to try it myself than to simply be told not to do it).
I see that someone else asked for links to old versions, and the issue was closed without answering the question. Well, in so many words, the answer was "no". So is it a question of the trouble of uploading, or was there an actual decision to make pre-2.x.x versions explicitly unavailable? I see that the Sourceforge page has 0 files...
It would really help me right now to be able to continue on Windows...

**Comment by DylanC** [comment]
@chuckkh - Are you asking for 1.4.3 to be available on Windows?

**Comment by DylanC** [comment]
You can still download old releases from Launchpad:
https://launchpad.net/openshot/+download?direction=backwards&memo=20&start=10

Openshot 1.4.3 will not be made available on Windows as it would be too much work and the focus is on the v2 series of the project.

Either use 1.4.3 on Linux or v2.4 on Windows if you prefer.

**Comment by edwardudell** [comment]
2.4.1 does not work on windows -- or let's say it's very difficult to work with -- very slow, not responding, adding crackle sounds sometimes. I spent about 6 hours today trying to work with it in various ways, and finally gave up.

**Comment by bnieuwveld** [comment]
@edwardudell - Have you had any success with one of the Daily Builds? Many additions and improvements have been made since 2.4.1 was released (in fact, 2.4.2 is due to be released very soon which will incorporate these). The Daily Builds are available [here.](https://www.openshot.org/download/)

**Comment by edwardudell** [comment]
Thanks for asking. I'm afraid I lost patience and bought a different video
program.


*========================================================================*

*New book coming in May 2018:*

*Free, Equal and Mutual *

12 authors draw on Rudolf Steiner's social thinking for rebalancing society:
chapters by Steve Briault, Chris Schaefer, Martin Large, Christine Arlt,
Glen Saunders, John Bloom, Gerard Haefner, Christoph Strawe, Robert
Karp, Edward
Udell, Richard House, Andrew Scott

*'Full of concrete, exciting examples--a golden opportunity to re-imagine
Europe and the world.’*
Nicanor Perlas, Foreword

Free, Equal and Mutual
<https://www.hawthornpress.com/books/social-ecology-and-management/free-equal-and-mutual/>
Copies available for online ordering  early May 2018.
