### ISSUE TITLE
Export video fails and crash program.

### ISSUE THREAD

**Issue by EgliFalco** [OpenShot/openshot-qt#945]
**System Details:**
* Operating System / Distro: Windows 8.1 64bit
* OpenShot Version: 2.4.0
* _Please attach log files if crash_

RAM 8GB

**Issue Description and steps to reproduce:**

When i try to export a video, i have a crash.
My video is 7 seconds only and i tryied to export for youtube (normal, not HD).

[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/1353162/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/1353163/openshot-qt.log)

**Comment by DylanC** [comment]
For Devs:

Couldn't find much details in the log except:
preview_thread:INFO initPlayer
 main_window:ERROR Unhandled crash detected... will attempt to recover backup project

**Comment by EgliFalco** [comment]
I tryied another project, in this case the program not crash but I cannot export video with this error:
![bug_openshot](https://user-images.githubusercontent.com/32492264/31589988-e29388b6-b209-11e7-9e79-a91f9154902e.png)

**Comment by meareg88** [comment]
/tmp/.mount_yPRJIk/usr/bin/PyQt5.QtCore.so ( qpycore_qobject_qt_metacall(_sipSimpleWrapper*, _sipTypeDef*, QMetaObject::Call, int, void**)  + 0x42  )  [0x7f6b85386952]
  /tmp/.mount_yPRJIk/usr/bin/libQt5Core.so.5 ( QMetaObject::activate(QObject*, int, int, void**)  + 0x8ad )  [0x7f6b8b94b36d]
  /tmp/.mount_yPRJIk/usr/bin/libQt5Core.so.5 (                                           + 0x9321c)  [0x7f6b8b74f21c]
  /lib/x86_64-linux-gnu/libpthread.so.0 (                                           + 0x8184)  [0x7f6b8fd2f184]
  /lib/x86_64-linux-gnu/libc.so.6 ( clone                                     + 0x6d  )  [0x7f6b8fa5c37d]
---- End of Stack Trace ----

this error appears when trying to preview Video edited on openshot 2.4
What could be the reason?

**Comment by meareg88** [comment]
and also it crushes when clicking on export video button

**Comment by DylanC** [comment]
@EgliFalco @meareg88 - Try the v2.4.1. Its more reliable.
