### ISSUE TITLE
CTD on adding a title

### ISSUE THREAD

**Issue by JonoColwell** [OpenShot/openshot-qt#946]
**System Details:**
* Operating System / Distro: Windows 10 64 bit
* OpenShot Version: v2.4.0-1-g8a71c3d-55-646-x86_64.exe
* _Please attach log files if crash_
Unable to locate log files/log files not generated

**Issue Description and steps to reproduce:**
Add a title to a project
Openshot will CTD

Will CTD on attempting to reopen the Project.

**Comment by DylanC** [comment]
@JonoColwell - CTD = Crash to Desktop?

**Comment by DylanC** [comment]
This sounds like the issue with accent characters. Try v2.4.1 and get back to us if you have another issue. Thanks.
