### ISSUE TITLE
Mp3 files a read as 'ticks' instead of sound.

### ISSUE THREAD

**Issue by nirhp** [OpenShot/openshot-qt#948]
**System Details:**
windows 10
open shot 2.4.0

**Issue Description and steps to reproduce:**
When I play or encode some mp3 files to my movie, I hear 'ticks' instead of music.

**Steps to reproduce:**
1. Download "Eine Kleine Nachtmusik by Mozart" from Toutube Audio Library (https://www.youtube.com/audiolibrary_download?vid=5f37e1a59d003588)
2. Import the file to an OpenShot project.
3. Play a preview of the file / Add it to the movie and play the movie.
4. Forward to 3:15

Result:
Quick 'Ticks' will play instead of music.

**Workaround:**
Use wav conversion instead of the original mp3 files.

**Comment by DylanC** [comment]
@nirhp  - Can you give the daily build a try?
https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.4.0-1-g8a71c3d-55-646-x86_64.exe

**Comment by nirhp** [comment]
Checked, the issue is fixed on that daily build.

**Comment by DylanC** [comment]
@nirhp - Perfect, thanks!
