### ISSUE TITLE
When previewing a video system CPU utilization spikes and playback is super slow

### ISSUE THREAD

**Issue by poetimp** [OpenShot/openshot-qt#95]
I add a video to the timeline so as to trim some from each end of the video. I can trim at the beginning of the video fairly quickly. However when I move the video cursor to the end of the video and play/preview it the cpu is pegged with near zero I/O and the playback is extremely (as in 20-30 real seconds for each video second) slow.

The video is "mov" format and is about 25 minutes long. The video itself can be made available to you if you so desire as I am the owner of the video. 

$ mplayer -vo null -ao null -identify -frames 0 2016-Psalm_42_4-8Normal.mov  
MPlayer SVN-r37242 (C) 2000-2012 MPlayer Team
mplayer: could not connect to socket
mplayer: No such file or directory
Failed to open LIRC support. You will not be able to use your remote control.

Playing 2016-Psalm_42_4-8Normal.mov.
libavformat version 55.49.100 (internal)
libavformat file format detected.
ID_VIDEO_ID=0
[lavf] stream 0: video (h264), -vid 0
ID_AUDIO_ID=0
ID_AID_0_LANG=eng
[lavf] stream 1: audio (aac), -aid 0, -alang eng
VIDEO:  [H264]  1920x1080  24bpp  29.970 fps  7859.8 kbps (959.5 kbyte/s)
Clip info:
 major_brand: qt  
ID_CLIP_INFO_NAME0=major_brand
ID_CLIP_INFO_VALUE0=qt  
 minor_version: 0
ID_CLIP_INFO_NAME1=minor_version
ID_CLIP_INFO_VALUE1=0
 compatible_brands: qt  
ID_CLIP_INFO_NAME2=compatible_brands
ID_CLIP_INFO_VALUE2=qt  
 creation_time: 2016-02-13 15:34:50
ID_CLIP_INFO_NAME3=creation_time
ID_CLIP_INFO_VALUE3=2016-02-13 15:34:50
 comment: KODAK Zi8 Pocket Video Camera
ID_CLIP_INFO_NAME4=comment
ID_CLIP_INFO_VALUE4=KODAK Zi8 Pocket Video Camera
 comment-eng: KODAK Zi8 Pocket Video Camera
ID_CLIP_INFO_NAME5=comment-eng
ID_CLIP_INFO_VALUE5=KODAK Zi8 Pocket Video Camera
ID_CLIP_INFO_N=6
Load subtitles in ./
ID_FILENAME=2016-Psalm_42_4-8Normal.mov
ID_DEMUXER=lavfpref
ID_VIDEO_FORMAT=H264
ID_VIDEO_BITRATE=7859816
ID_VIDEO_WIDTH=1920
ID_VIDEO_HEIGHT=1080
ID_VIDEO_FPS=29.970
ID_VIDEO_ASPECT=0.0000
ID_AUDIO_FORMAT=MP4A
ID_AUDIO_BITRATE=128000
ID_AUDIO_RATE=48000
ID_AUDIO_NCH=2
ID_START_TIME=0.00
ID_LENGTH=145.14
ID_SEEKABLE=1
# ID_CHAPTERS=0

Opening video decoder: [ffmpeg] FFmpeg's libavcodec codec family
libavcodec version 55.69.100 (internal)
# Selected video codec: [ffh264] vfm: ffmpeg (FFmpeg H.264)
# ID_VIDEO_CODEC=ffh264

Opening audio decoder: [ffmpeg] FFmpeg/libavcodec audio decoders
AUDIO: 48000 Hz, 2 ch, floatle, 128.0 kbit/4.17% (ratio: 16000->384000)
ID_AUDIO_BITRATE=128000
ID_AUDIO_RATE=48000
ID_AUDIO_NCH=2
# Selected audio codec: [ffaac] afm: ffmpeg (FFmpeg AAC (MPEG-2/MPEG-4 Audio))

AO: [null] 48000Hz 2ch floatle (4 bytes per sample)
ID_AUDIO_CODEC=ffaac
Starting playback...

Exiting... (End of file)
ID_EXIT=EOF

**Comment by poetimp** [comment]
The info for the longer video that I am having trouble with. I picked the wrong one above.

$ mplayer -vo null -ao null -identify -frames 0 2016-Psalm_42_4-8Vocab.mov                                   
MPlayer SVN-r37242 (C) 2000-2012 MPlayer Team
mplayer: could not connect to socket
mplayer: No such file or directory
Failed to open LIRC support. You will not be able to use your remote control.

Playing 2016-Psalm_42_4-8Vocab.mov.
libavformat version 55.49.100 (internal)
libavformat file format detected.
ID_VIDEO_ID=0
[lavf] stream 0: video (h264), -vid 0
ID_AUDIO_ID=0
ID_AID_0_LANG=eng
[lavf] stream 1: audio (aac), -aid 0, -alang eng
VIDEO:  [H264]  1920x1080  24bpp  29.970 fps  5765.4 kbps (703.8 kbyte/s)
Clip info:
 major_brand: qt  
ID_CLIP_INFO_NAME0=major_brand
ID_CLIP_INFO_VALUE0=qt  
 minor_version: 0
ID_CLIP_INFO_NAME1=minor_version
ID_CLIP_INFO_VALUE1=0
 compatible_brands: qt  
ID_CLIP_INFO_NAME2=compatible_brands
ID_CLIP_INFO_VALUE2=qt  
 creation_time: 2016-02-13 15:06:27
ID_CLIP_INFO_NAME3=creation_time
ID_CLIP_INFO_VALUE3=2016-02-13 15:06:27
 comment: KODAK Zi8 Pocket Video Camera
ID_CLIP_INFO_NAME4=comment
ID_CLIP_INFO_VALUE4=KODAK Zi8 Pocket Video Camera
 comment-eng: KODAK Zi8 Pocket Video Camera
ID_CLIP_INFO_NAME5=comment-eng
ID_CLIP_INFO_VALUE5=KODAK Zi8 Pocket Video Camera
ID_CLIP_INFO_N=6
Load subtitles in ./
ID_FILENAME=2016-Psalm_42_4-8Vocab.mov
ID_DEMUXER=lavfpref
ID_VIDEO_FORMAT=H264
ID_VIDEO_BITRATE=5765416
ID_VIDEO_WIDTH=1920
ID_VIDEO_HEIGHT=1080
ID_VIDEO_FPS=29.970
ID_VIDEO_ASPECT=0.0000
ID_AUDIO_FORMAT=MP4A
ID_AUDIO_BITRATE=128000
ID_AUDIO_RATE=48000
ID_AUDIO_NCH=2
ID_START_TIME=0.00
ID_LENGTH=1483.88
ID_SEEKABLE=1
ID_CHAPTERS=0

Opening video decoder: [ffmpeg] FFmpeg's libavcodec codec family
libavcodec version 55.69.100 (internal)
Selected video codec: [ffh264] vfm: ffmpeg (FFmpeg H.264)

ID_VIDEO_CODEC=ffh264

Opening audio decoder: [ffmpeg] FFmpeg/libavcodec audio decoders
AUDIO: 48000 Hz, 2 ch, floatle, 128.0 kbit/4.17% (ratio: 16000->384000)
ID_AUDIO_BITRATE=128000
ID_AUDIO_RATE=48000
ID_AUDIO_NCH=2
Selected audio codec: [ffaac] afm: ffmpeg (FFmpeg AAC (MPEG-2/MPEG-4 Audio))

AO: [null] 48000Hz 2ch floatle (4 bytes per sample)
ID_AUDIO_CODEC=ffaac
Starting playback...


Exiting... (End of file)
ID_EXIT=EOF

**Comment by dahu** [comment]
I just installed Openshot 2.06 on Ubuntu and I see the same problem when trying to play back any type of video. I originally noticed the problem with a video+audio combination matching @poetimp's specs, but I tested it on several other formats and they were all slow. Playback was delayed & jittery and sound cut in and out and was out of sync. The controls became unresponsive for a long time -- I clicked the pause button and it took about 30+ seconds to stop the video. On subsequent tests, it sometimes SIGSEGV'd.

**Comment by nitehawk39** [comment]
I have experienced the same issue on my computer with 12 gb of ram and an i7.

**Comment by djevertguzman** [comment]
Same problem here im using a amd A8-4500M with 8gb of ram

**Comment by magnontobi** [comment]
+1
Needs to be fixed before OpenShot can even be taken seriously as a video editor on Ubuntu.

**Comment by DylanC** [comment]
@poetimp - Closing since this ticket relates to an older version of OpenShot. We will track any issues with the preview feature in newer tickets.
