### ISSUE TITLE
Waveform generation extremely slow and needs to be redone when cutting

### ISSUE THREAD

**Issue by credmp** [OpenShot/openshot-qt#951]
**System Details:**
* Operating System / Distro: Arch Linux
* OpenShot Version: 2.4.0
* _Please attach log files if crash_
No crash

**Issue Description and steps to reproduce:**
Generation of the waveform (Display > Show Waveform) takes a very long time. I use the waveform to determin cut points. When cutting a strip, the waveform is discarded and needs to be regenerated for the new segments.

I would expect that 1) the waveform is cached, 2) the option to display the waveform is kept on the strips it was enabled on and 3) generation of the waveform should not take so long.

I have previously used kdenlive, which displays the waveform instantaneously, perhaps there is something to learn from their implementation?

**Comment by DylanC** [comment]
Dup of #518

**Comment by credmp** [comment]
Reading #518 it seems there is overlap, the rendering of the waveform is very slow, but I have no problems with the cutting as described in the other bug.
