### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by Lakritzwolf** [OpenShot/openshot-qt#952]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

I chose English as language during installation and the program regionalized itself anyway. If the user chooses English as language then English should be the language of the installed program. 

Changing the language via preferences has no effect after a restart

**Comment by DylanC** [comment]
Dup of #331

**Comment by DylanC** [comment]
As confirmed in #331.

> Changing interface language to American English works fine in OpenShot-v2.4.1-34-g6a9257e-59-685.

Can someone confirm this here too?

**Comment by DylanC** [comment]
Confirmed as fixed in #331.
