### ISSUE TITLE
Lacking lots of buttons from the PPA installation (major issue)

### ISSUE THREAD

**Issue by BarbzYHOOL** [OpenShot/openshot-qt#953]
**System Details:** ? linux ?
* Operating System / Distro: ubuntu 14.04
* OpenShot Version: openshot-qt (2.4.0+0+834+116+201709070432~ubuntu14.04.1) ...

**Issue Description and steps to reproduce:**
There is no button to add titles, it lacks a lot of features, no idea why.

http://image.noelshack.com/fichiers/2017/40/7/1507489493-openshotbug.png

If I use the appimage openshot, it works fine, but the one from the PPA has nothing in it.

**Comment by DylanC** [comment]
@BarbzYHOOL - Is the PPA still having trouble?

**Comment by BarbzYHOOL** [comment]
It has been updated? I might reinstall it/update it then and report here

**Comment by DylanC** [comment]
@BarbzYHOOL - When I checked it has not been updated yet. I think the primary distribution is the AppImage.

**Comment by DylanC** [comment]
@BarbzYHOOL - I would suggest you use the AppImage for now.
