### ISSUE TITLE
Transitions not working

### ISSUE THREAD

**Issue by chefbt** [OpenShot/openshot-qt#955]
**System Details:**
* Operating System / Distro: ?  Windows 10 Version 1703
* OpenShot Version: ?  2.4.0
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

I have a short intro, 2 min video and an image. I have tried several transitions and they just show as a black screen. First time I have had this problem...

**Comment by chefbt** [comment]
Is there another support channel where I can get help?

**Comment by DylanC** [comment]
@chefbt - I would recommend to try the v2.4.1 release. It has much important fixes.
