### ISSUE TITLE
How do i insert a picture in OpenShot

### ISSUE THREAD

**Issue by georges18** [OpenShot/openshot-qt#956]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

**Comment by DylanC** [comment]
@georges18 - Import image. Drag and drop it to the timeline.

**Comment by georges18** [comment]
Thanks for the answer, it works fine now

**Comment by DylanC** [comment]
@georges18 - No problem. Happy to help.
