### ISSUE TITLE
Lack of effects on Windows 7

### ISSUE THREAD

**Issue by itschris2003** [OpenShot/openshot-qt#957]
**System Details:**
* Operating System / Distro: Windows 7
* OpenShot Version: 2.4.0

Lack of effects

Hi, I was just wondering why linux has so many effects and yet my openshot has no audio effects and has only 7 video effects. I really want to do some funny audio editing in openshot for my youtube channel but I cannot due to there being no ways to do this (such as pitch adjusters). Is this a bug, or is it just that windows has been left behind? I attached an image below to show MY ONLY effects

![image](https://user-images.githubusercontent.com/18634859/31404431-f81cb424-adf3-11e7-8a41-839f32a7b371.png)

**Comment by DylanC** [comment]
@itschris2003 - I'll investigate this and get back to you.

**Comment by itschris2003** [comment]
right, cheers

**Comment by ajcherry** [comment]
FYI, I am having the same issue with OpenShot 2.4.0 for Mac OS X, so this issue does not appear to be limited to Windows 7.

**Comment by itschris2003** [comment]
hm, shame really. they shouldn't lean against OS's, they should provide the same experience

**Comment by ajcherry** [comment]
@itschris2003 Actually, I see the same thing with openshot-qt on Linux.  Some further research suggests that a lot of effects have not yet been ported from OpenShot 1.x to the new framework in 2.x.   I'll bet you're running the older 1.x (non-qt) version on Linux.  So this really isn't a case of other OSes being left behind -- in fact, I'm pretty sure it's the opposite of that, since the switch from GTK to QT is likely what makes the non-Linux versions possible to begin with.

**Comment by itschris2003** [comment]
oh right, well in that case i take back what i said previously

**Comment by DylanC** [comment]
@itschris2003 - Yes, I think I gave similar answers before. The v2 series of Openshot still needs certain effects to be recreated. Its not different between operating systems.

**Comment by itschris2003** [comment]
oh okay cheers

**Comment by derei** [comment]
Still now new effects. I tried it today.
Maybe this should be pointed out on front page on the website... as people are expecting this, then start looking for answers.

**Comment by peanutbutterandcrackers** [comment]
v2.4.2 will have a few more effects, actually. Including shift, wave, crop, color shift, bars and stuff. However, there are no audio effects in the 2.x series as of yet. Mr. Thomas has plans to port all the 1.x series effects to 2.x within this year. So, yeah. That is something to look forward to.

Perhaps you'd like to use the latest [daily build](https://github.com/OpenShot/openshot-qt/releases/tag/daily) to try out the effects?
