### ISSUE TITLE
The OpenShot AppImage fails to start

### ISSUE THREAD

**Issue by limikael** [OpenShot/openshot-qt#959]
**System Details:**
* Operating System / Distro: ?

```
> lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.10
Release:	16.10
Codename:	yakkety

> uname -a
Linux S751 4.8.0-59-generic #64-Ubuntu SMP Thu Jun 29 19:38:34 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

```
* OpenShot Version: ?

2.4.0

* _Please attach log files if crash_

Please see here for full log: https://gist.github.com/limikael/5590406a8807be565139e094179e1976

The last lines of output:

```
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_ljciPF/usr/bin/generic" ... 
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_ljciPF/usr/generic" ... 
loaded library "gtk-x11-2.0" 
loaded library "gnomeui-2" 
loaded library "gnomevfs-2" 
/tmp/.mount_ljciPF/usr/bin/launch: symbol lookup error: /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined symbol: hb_buffer_set_cluster_level
```

**Issue Description and steps to reproduce:**

I just downloaded the AppImage file and `chmod`ed it, then ran the command:

./OpenShot-v2.4.0-x86_64.AppImage

**Comment by DylanC** [comment]
@limikael - What happens if you double click on the appImage. Mount and click runApp?

**Comment by limikael** [comment]
If I double click nothing happens. Or actually, it starts loading a bit (I can see my harddrive LED blinking), and then it stops. My assumption is that the same thing is happening as when I try to run it from the commandline, but the messages are eaten up/sent somewhere else. I haven't tried mounting it. How do I do that?

**Comment by DylanC** [comment]
@limikael  - If you open it with a double click then Ubuntu mounts the appImage automatically. You would see it appear like a hard drive on the left if you are using Unity.

**Comment by limikael** [comment]
I'm not using unity. I am using Caja however, part of Ubuntu MATE. In Caja I usually see folders appearing the way you mention. However... When double clicking I don't see anything... :(

**Comment by DylanC** [comment]
@limikael - No problem, I can try Ubuntu Mate to see how to do it.

**Comment by DylanC** [comment]
**Users**

If anyone is using Ubuntu Mate, feel free to help out.

**Comment by peanutbutterandcrackers** [comment]
For Ubuntu based distros, I think [PPA](https://www.openshot.org/ppa/)s are the best way to go. That way, you'll also get automatic updates.

P.S: Please close the issue if it has been solved/resolved. Thanks!
