### ISSUE TITLE
Wish - Remember where you got the last clip

### ISSUE THREAD

**Issue by poetimp** [OpenShot/openshot-qt#96]
When I add a clip to OpenShot I often go back and get something else from the same folder. Yes, I know I can add it all at the same time and not have to go back but that would require forethought :) Anyway, When I go to add another clip I have to traverse my way all the way to my deeply nested directory every time. It would be nice if it remember where it got the last clip and start me there.

**Comment by jarlarntzen** [comment]
:+1: Completely agree to this.

**Comment by schuko24** [comment]
would be very useful, I agree

**Comment by peanutbutterandcrackers** [comment]
@ferdnyc - This one has to be implemented in the source, I believe. Or do you thin PyQt5 has got something for this too? o.O Just curious.

**Comment by peanutbutterandcrackers** [comment]
@DylanC - As this has already been implemented (thanks to the awesome @ferdnyc), I think it is safe to close this issue, too. :)

**Comment by DylanC** [comment]
@peanutbutterandcrackers - Thanks! @ferdnyc is indeed awesome! :)
