### ISSUE TITLE
Why it uses a lot of RAM and CPU? 

### ISSUE THREAD

**Issue by KhArtNJava** [OpenShot/openshot-qt#961]
**System Details:**
* Win 10 Home
* OpenShot Version: 2.4.0

When I start OpenShot and add video to Track 4, it uses about 350 MB RAM and 0% CPU.
When I make first video cut, it takes about 15 seconds and 500 MB RAM to cut video. At the second cut it uses 30 sec and 600 MB RAM. For third - 45 sec and 650 MB RAM. And etc. For 20 cut of video it takes about 80 sec and 1500 MB of RAM. 

At the same time, no one of cutted pieces were deleted in that time, when I cut the video.

For example, non-free https://www.movavi.com/videoeditor/ cut and DELETE video pieces momentarily, without any time to cut the video.

Why OpenShot's cut process increases required time to cut the video at each cut operation?

**Comment by DylanC** [comment]
@KhArtNJava - Not sure but someone did report something similar that slicing takes an increasing amount of time after every slice of a clip.

**Comment by omichel** [comment]
I confirm I am experiencing the same problem as @KhArtNJava (running OpenShot 2.4.0 64 bit on Windows 10).

**Comment by DylanC** [comment]
Closing this question since we have an issue to track this problem.
