### ISSUE TITLE
MP3 Files act corrupted after 00:02:32:00 

### ISSUE THREAD

**Issue by WolfTamer0902** [OpenShot/openshot-qt#962]
* Operating System: Windows
* OpenShot Version: 2.4.0

I've been messing around with OpenShot for three days now and I'm new to video editing software. I was making a video with images and i found that after two minutes and 32 seconds it started almost skipping like the file was corrupted. I listened to the file to ensure it wasn't and the mp3 file was fine. I tested this same problem with a different mp3 file that i ensured was not corrupted on my computer and the same problem occurred at 2 minutes and 32 seconds just like the times before. I also tried uninstalling and reinstalling the program to attempt to fix this and that had no effect. I'm not sure what the best next step would be from here. 
Thank you for taking your time to read and help me with this problem. Other than this I enjoy the program very much. Its been easy to learn and grasp.

**Comment by DylanC** [comment]
@WolfTamer0902 - Can you try the v2.4 daily build please? 

https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.4.0-1-g8a71c3d-55-646-x86_64.exe

This has been resolved in the daily build.  See ticket - #618.
