### ISSUE TITLE
VOB video files loaded into OpenShot do not have audio synced to video

### ISSUE THREAD

**Issue by ShimonShore** [OpenShot/openshot-qt#963]
**System Details:**
* Operating System / Distro: Windows 10
* OpenShot Version: 2.4.0
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
I have VOB files copied from a DVD (using Windows Explorer). On each DVD the video is divided into multiple files. When I play any of the VOB files that are not the first ones from the DVD in OpenShot they play with the audio not synced to the video. In other systems (like VLC) they play OK. Once the video is saved through OpenShot the resulting video is not synced to the audio even when played in VLC.

I can send the VOB file but they are large (hundreds of MBs). 

The properties for one of the file are as follow (if this is useful):
{
    "acodec": "ac3",
    "audio_bit_rate": 384000,
    "audio_stream_index": 1,
    "audio_timebase": {
        "den": 90000,
        "num": 1
    },
    "channel_layout": 3,
    "channels": 2,
    "display_ratio": {
        "den": 3,
        "num": 4
    },
    "duration": 812.1920166015625,
    "file_size": "957949952",
    "fps": {
        "den": 1,
        "num": 25
    },
    "has_audio": true,
    "has_single_image": false,
    "has_video": true,
    "height": 576,
    "id": "2SCPC42GG1",
    "interlaced_frame": false,
    "media_type": "video",
    "path": "C:/Users/Shimon/Documents/Video-2.VOB",
    "pixel_format": 0,
    "pixel_ratio": {
        "den": 15,
        "num": 16
    },
    "sample_rate": 48000,
    "top_field_first": true,
    "type": "FFmpegReader",
    "vcodec": "mpeg2video",
    "video_bit_rate": 9435699,
    "video_length": "20301",
    "video_stream_index": 0,
    "video_timebase": {
        "den": 90000,
        "num": 1
    },
    "width": 720
}

**Comment by ShimonShore** [comment]
The issue I had was the VOB was taken from a DVD and so it was missing the header. The VOB files from the DVD needed to be concatenated together and not joined as two separate videos.

**Comment by DylanC** [comment]
@ShimonShore - No problem. Thanks.

**Comment by ShimonShore** [comment]
It would be nice if OpenShot was able to concatenate videos in this case.
