### ISSUE TITLE
Video preview slow and unusable

### ISSUE THREAD

**Issue by brandonmcewen** [OpenShot/openshot-qt#965]
**System Details:**
* Operating System / Windows 10: 
* OpenShot Version: 2.4.0

When putting a single small video file in the timeline and trying to preview it, the video plays very sluggish.  It probably plays at a rate of approx 1FPS.  When right clicking on the file and doing a "Preview", the file plays just fine.  

Working on an SSD, i5-3570K, 8Gb ram.  CPU usuage and RAM are not at 100%.

![image](https://user-images.githubusercontent.com/32827094/31593144-7fcfa636-b1f2-11e7-9b0f-a671756a352b.png)
![image](https://user-images.githubusercontent.com/32827094/31593158-936822ea-b1f2-11e7-9041-be0bda2ed132.png)

**Comment by DylanC** [comment]
See #960 for info on a solution.

**Comment by brandonmcewen** [comment]
I have tried all the suggestions in #960 to no avail.  Are there any other suggestions out there?

Thanks!

**Comment by DylanC** [comment]
@brandonmcewen - Not at the moment unfortunately.

**Comment by DylanC** [comment]
Dup of #960

**Comment by grimes869** [comment]
I found going to Edit -> Preferences -> Cache and setting Cache Mode to Memory, and lowering the Cache Limit reduces resources used on my PC and improves playback performance.

**Comment by gamersalpha** [comment]
i got the same issue, but i can't using openshoot because not working do laaaging
