### ISSUE TITLE
Problème Titre animé openshot / blender

### ISSUE THREAD

**Issue by jonathandu68** [OpenShot/openshot-qt#966]
Bonjour,

je suis novice dans les montages vidéo, mais on 'a vivement recommandé Openshot. Je souhaite ajouter un "titre animé" mais un message d'erreur d'affiche : "Blender, la suite libre et open source de création de contenu 3D est requise pour cette action (http://www.blender.org).

Dans les préférences d'OpenShot, veuillez vérifier que l'exécutable de Blender est correct. Ce paramètre devrait être le chemin d'accès à l'exécutable 'blender' sur votre système. Assurez-vous aussi qu'il pointe bien vers la version 2.78  (ou supérieure) de Blender.

Chemin vers l'exécutable de Blender :
blender"

J'ai téléchargé la version 2.0 d'openshot et la version 2.79 de Blender.

dans Les préférences d'openshot pour l'emplacement de blender, j'ai d'abord laissé l'emplacement par défaut :"blender"

j'ai ensuite testé l'emplacement réel de blender : " C:\Program Files (x86)\Blender Foundation\Blender "
je ferme la page de préférence, rallume l'application openshot, mais ça ne fonctionne toujours pas.

Pourriez vous m'aider ?

**Comment by DylanC** [comment]
EN:

Hello,

I am a novice in video editing, but we highly recommend Openshot. I want to add an "animated title" but a poster error message: "Blender, the free and open source 3D content creation is required for this action (http://www.blender.org).

In OpenShot preferences, please check that the Blender executable is correct. This parameter should be the path to the 'blender' executable on your system. Make sure that it also points to Blender version 2.78 (or higher).

Path to the Blender executable:
blender"

I have downloaded version 2.0 of openshot and version 2.79 of Blender.

in the openshot preferences for the blender location, I first left the default location: "blender"

I then tested the actual blender location: "C: \ Program Files (x86) \ Blender Foundation \ Blender"
I close the preference page, re-opens the openshot application, but it still does not work.

Could you help me ?

**Comment by DylanC** [comment]
@jonathandu68 - The correct path is:

C:\ Program Files (x86)\Blender Foundation\Blender\blender

**Comment by jonathandu68** [comment]
Thabks thanks thanks

Jonathan Rodrigues
________________________________

**Comment by DylanC** [comment]
@jonathandu68  - No problem.  :)

**Comment by Swissmovie** [comment]
bonjour, 
J'ai le même problème et ce que je ne comprends pas c'est que j'ai bien le chemin : 
C:\ Program Files (x86)\Blender Foundation\Blender\blender et toujours le même problème :'(

HELP ME

**Comment by peanutbutterandcrackers** [comment]
According to [this comment](https://github.com/OpenShot/openshot-qt/issues/1222#issuecomment-362642845), you have to put the full path.
[This tutorial](https://github.com/OpenShot/openshot-qt/issues/1400) might be of some help, too, even though it is regarding Mac OS.

Hope that helps!

**Comment by Mikoto-san** [comment]
Hello
I allways work with win 32 (sorry) and I've a similar problem. I install and used blender 3.0 but openshot said to me : **Output error:
No image was found at the Blender output**

please I need help

**Comment by ferdnyc** [comment]
@Mikoto-san 

Blender 2.80+ support in OpenShot is currently being worked on (#2915), but unfortunately not yet ready. Blender made [major changes](https://wiki.blender.org/wiki/Reference/Release_Notes/2.80/Python_API) to their Python API for version 2.80.

**Comment by ferdnyc** [comment]
(Issue #2901 tracks compatibility with Blender 2.80.)

**Comment by Mikoto-san** [comment]
@ferdnyc 
1000 thanks you very much for your answer. I have to wait ^_^
