### ISSUE TITLE
cx_Freeze: Python error in main script when trying to launch application

### ISSUE THREAD

**Issue by LuciferInlustris** [OpenShot/openshot-qt#967]
**System Details:**
* Operating System / Distro: Windows 8.1
* OpenShot Version: 2.4.0
* https://www.dropbox.com/s/8zbh1dniag9oofj/Screenshot%202017-10-16%2019.35.55.png?dl=0

**Issue Description and steps to reproduce:**

After having to forcibly restart my computer due to my speakers not working i tried opening the program and i got the cx_freeze error in main script python crash. the NameError: name 'exit' is not defined error. I tried uninstalling and reinstalling Openshot and still got the error.

**Comment by DylanC** [comment]
@LuciferInlustris - I have a Windows 8 box at home. I should be able to test during the week.  The daily build might work better at the moment though. It has some big audio bugs fixed.

https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.4.0-1-g8a71c3d-55-646-x86_64.exe

**Comment by LuciferInlustris** [comment]
I installed the link you have provided but i still get the cx_Freeze Error.

**Comment by LuciferInlustris** [comment]
I think it's a python issue is there a fix?

**Comment by DylanC** [comment]
@LuciferInlustris - I'll have a check on Windows 8 and get back to you. I haven't seen this error on Windows 10 so maybe its just a Windows 8 problem.

**Comment by aliyevanv** [comment]
I'm on Windows 10, and I get the same issue every time I try to launch.
![openshoterror1v01](https://user-images.githubusercontent.com/11650287/32416821-ab046e32-c268-11e7-8443-5bb2a8fab3a5.jpg)

**Comment by DylanC** [comment]
@LuciferInlustris @aliyevanv - How about the v2.4.1 release? Is it the same result?

**Comment by TPH1** [comment]
Hi, 
I've been having the same issue with the cx_freeze error and not being able to open the program. I, also, uninstalled, deleted the original download, re-downloaded and re-installed. The new version 2.4.1 has the same issue. I can't get any further than installing it. It won't let me past the error message. I'm on Windows 8

**Comment by DylanC** [comment]
@TPH1 - Did you try to remove the preferences folder and start again?

**Comment by DylanC** [comment]
@LuciferInlustris 

The solution here is to delete the preferences folder and restart the program. A fix has gone in to help with not loading invalid preference data, so this will not be much of a problem in the future.

**Comment by aliyevanv** [comment]
Where is the preferences folder?  I've got platforms, presets and profiles, I can't see a folder called 'preferences'

**Comment by aliyevanv** [comment]
@DylanC I've uploaded the latest daily version (23 Nov), and the error is gone.  Thank you!!

**Comment by DylanC** [comment]
@aliyevanv - Great news. Thanks!

**Comment by Fahrern** [comment]
HI, I have the same issue in my windows 10 x64. However, I donwloaded the program yesterday and it  had works. someone could help me please?
![err](https://user-images.githubusercontent.com/34237259/33550997-304a947a-d8f0-11e7-9710-a565368f32f8.png)

**Comment by EditorOfOz** [comment]
We just downloaded OpenShot this evening, and my son created a great video.  When he was almost done, the program crashed.  When we started it again, the video had thankfully saved and we made the last changes and hit the export button, but it crashed mid-download.  Restarted computer, and right after I opened OpenShot it was frozen; restarted again and when I tried to open the program I got the exact same error screen Fahrern posted above.  I downloaded the latest version, as suggested by aliyevanv from the Nov. 13th post on the blog, but the same error message appeared when I tried to open the program.  Is my son's movie lost?  Is there anything I can do to get it back?

**Comment by Fahrern** [comment]
Hi,
Sorry I'm an user as you. I really don't know where you find my email
address. However, I hope you find someone who can help you.
Have a nice day!

**Comment by raz5652** [comment]
its an old issue, but I am having the same problem. Can someone pls suggest a solution. Plus where is the preference folder?

**Comment by peanutbutterandcrackers** [comment]
@raz5652 - A solution that seems to works seems to be to delete the .openshot_qt folder on your home folder. That seems to resolve it for most people. Else, try using OpenShot with another user (admin user, perhaps). Hope that helps!

**Comment by LuciferInlustris** [comment]
@DylanC Yes still have the issue with latest release.

**Comment by peanutbutterandcrackers** [comment]
It should be in your home directory. Users/Your_user_Name directory. A folder named `.openshot_qt`.

On a side note, v2.4.2 should be out anyday now. And it has got a ton of improvements already.

**Comment by anderl80** [comment]
I got the same error, deleting preferences folder did not work for me.

**Comment by peanutbutterandcrackers** [comment]
Then I would recommend [attaching the logs](https://gist.github.com/peanutbutterandcrackers/d84c257e74b72d8b06b4daffaebc5a14) so that the developers can figure this out, soon. Sorry for the inconvenience in the meantime.

**Comment by anderl80** [comment]
![image](https://user-images.githubusercontent.com/23196828/45145553-2f968c00-b1c1-11e8-963c-50007f9ac125.png)

This is the error I get with version 2.4.2 and the daily build. The folder .openshot_qt is created with all subfolders at startup, but all completely empty.

**Comment by peanutbutterandcrackers** [comment]
@anderl80 - Could you please try deleting the `.openshot_qt` folder entirely please?

**Comment by anderl80** [comment]
Didn't change anything. Same errot. Can't start open shot.
