### ISSUE TITLE
How do I upload .osp on Youtube :(

### ISSUE THREAD

**Issue by MaloryYT** [OpenShot/openshot-qt#969]
Hello everyone,
I want to upload my edited Video on Youtube but i cant... how can i do this or can I Change the .osp? Please answer I want to make Videos for YouTube :((

**Comment by N3WWN** [comment]
You need to render the video by clicking on the red dot (Export Video), selecting "Export Video" from the File menu.  That will allow you to generate a MP4 (or other YouTube compatible file format) that you can upload to YouTube.

**Comment by MaloryYT** [comment]
It worked! I can upload it now. Thank you so much^^
