### ISSUE TITLE
User interface language selection

### ISSUE THREAD

**Issue by iiggoorr** [OpenShot/openshot-qt#97]
I need an option to select the user interface language (menus etc.). I might have overlooked something but I could not find it anywhere. I use the English version of Windows 7, with the location set to Slovenia, and now I am stuck with OpenShot's Slovenian interface (currently half-translated). (I absolutely prefer English interface because (1) I am used to it and (2) only some of the application I use are translated to Slovenian, so I would have I frustrating language mix.) Generally, all translated applications have an option so select the interface language.

**Comment by BF3000** [comment]
Well, I'm not the only one. ( #89 )

**Comment by seindal** [comment]
Sounds like a Windows issue as there are ways to do this easily on Unix / Linux.

**Comment by BF3000** [comment]
Manual switch in program GUI is always an easiest way.
And most of windows versions are locked to one user interface language.

**Comment by iiggoorr** [comment]
Let me try to shed some light on this - as I understand it (up to Windows 7 and Office 2010, I haven't installed newer versions yet):
During Windows installation, the user sets the region to his/her local region (Slovenia in my case), which sets correctly the keyboard type and keys mapping, and many other things. This (as far as I know) also sets the so called System language. It does not automatically switch the Windows (and Office) menus language. If you've installed the English version of Windows (and Office) the menus are in English. If you've installed the Slovenian one, the menus are in Slovenian (even if the region set was US or any other). I think that nowadays most people in Slovenia - the average users - use the Slovenian Windows and Office. Technically oriented people probably (as far as I know) tend to use the English version (because they use many English-only (non-localised) technical applications, technical literature is mostly in English, etc.).
Localised multi-language application generally use the following approach to language selection (e.g. VLC, Gimp, FreeFileSync, to name but a few): they default to the System language (if supported, of course) or English language, but they let the user change this setting somewhere in their menu system to any of the supported languages.
I've never came across a Windows application which would force me to use the System (Slovenian) GUI language without the possibility to change it. I believe that OpenShot should follow this practice. (I am not sure about Linux, I do use it (mostly Ubuntu), but simply never had this English-Slovenian mix problem there, the OpenShot's GUI language there is English.)

**Comment by jonoomph** [comment]
I have just committed (bdfb78ca499c837072364affd13689f494e5f904) an integrated language drop-down into the Preferences dialog, which gives a super easy way to change the langauge. On Linux/OS X users can still use the LANG=es (or whatever language code) to override things, so this new Preference just adds another way to do the same basic thing. Really useful for Windows users, who run Windows in English, but want their applications in a different language. Enjoy!

**Comment by jonoomph** [comment]
FYI: This will appear in a new installer soon on www.openshot.org/download (just click 'Other Installers' and choose the newest one). It might take a few hours to appear on the website though. =)

**Comment by BF3000** [comment]
Thanks.
It works.

**Comment by ovari** [comment]
@jonoomph Thank you for implementing this feature.

**Comment by jonoomph** [comment]
@ovari, @BF3000 You are very welcome!

**Comment by Saganus** [comment]
For some reason this option is not working on my computer. I selected en_US from the dropdown and restarted OS as isntructed by the prompt but the system's language was still in use (Spanish).

I had to manually delete the "es" folder to force OS to use the English version since I don't want to change my env vars as I'm not sure if other software is using it. 

I'm using Windows 7 btw.

**Comment by jonoomph** [comment]
@Saganus, what version of OS are you running? Also, you might try removing your user settings folder (/User/USERNAME/.openshot_qt/ folder) fr OpenShot, and launch it fresh (it will recreate the folder and settings), and then choose en_US as your language and restart again. 

If that still doesn't work, and you are on the latest version, please re-open this ticket and attach your openshot.settings file, and openshot-qt.log file. Thanks!

**Comment by BackSlasher** [comment]
Happens for me with freshly installed OpenShot 2.1.0 on Windows
Stuck on hebrew
openshot.settings - http://pastebin.com/VwaUmkw4
openshot-qt.log - http://pastebin.com/YdukLa9s

**Comment by mmKALLL** [comment]
This is happening to me as well, using 2.2.0 on Windows 10. Installed just now, changed language and default video profile, restarted the application and I'm stuck with half of the UI in Finnish.

However, I am unable to find the aforementioned files, openshot.settings and openshot-qt.log. Would be glad to help figure out this issue.

**Comment by 07416** [comment]
Version 2.2.0 on Windows 10, GUI option doesn't change language.
