### ISSUE TITLE
Drop clip to track, it stays frozen

### ISSUE THREAD

**Issue by NycAna** [OpenShot/openshot-qt#971]
**System Details:**
* Operating System / Distro: Windows 10
* OpenShot Version: Recent (as of 9:13 PM, 10/18/17 EST)
* _Please attach log files if crash_

**Issue Description and steps to reproduce:** If you "use" the cut ; drop it off a section of a video ( no clue for images), it stays frozen. Only thing you can really do with it is cut it (with right click) and deleting it.

**Comment by maigke** [comment]
Same trouble 
OS: Fedora 26 x86_64 fresh install
OpenShot Version: Default from Fedora Repositories

Description: When drop a clip to and explore for en cut scenes, openshot going to frozen

**Comment by NycAna** [comment]
Sorry, i meant to say drag off, not drop off

**Comment by DylanC** [comment]
@NycAna - What do you mean?
