### ISSUE TITLE
Audio volume adjusting for individual tracks

### ISSUE THREAD

**Issue by mm7916** [OpenShot/openshot-qt#972]
* Operating System / Windows 10
* OpenShot Version: 2.4

I am fairly new to the OpenShot community (but somewhat familiar with Final Cut Pro).  In OpenShot, I am trying to adjust the volume of an individual audio music track (Music is on one track, speaking audio and video on a second track).  The music is too loud and covers up the speaking voice on the video track.  I am trying to lower the volume of the music by selecting the music track and adjusting the volume within the properties section, but no success.  Probably simple, but can't seem to figure it out. 
 Any help would be greatly appreciated!

**Comment by itschris2003** [comment]
Hi there, if you follow these steps you will be able to lower the volume
Right click on the music you wish to lower
Go to "Volume" and then "Entire Clip"
Here you can choose to adjust it. You may have to experiment but I say around 75% - 50% if it's just a little bit too loud (don't forget there's always an undo button if it's not the volume level you want, I recommend if you choose a volume level but don't like it, press undo before you choose another to stop weird unexpected things happening to it (such as the volume going too low)

**Comment by N3WWN** [comment]
There is also a default volume setting in the General tab of the Preferences.  If you want to set the volume on all but one of your imported clips to 50%, for instance, you can set it to 50% here, import all of your clips, then increase the volume of the voice clip to 100%.

**Comment by DylanC** [comment]
Closing as answered.
