### ISSUE TITLE
Bad

### ISSUE THREAD

**Issue by nstein5** [OpenShot/openshot-qt#974]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

I had a school project and this runs extremely slow and when I exported it the clips would change into other clips.

**Comment by nstein5** [comment]
it also freezes and says its not responding

**Comment by DylanC** [comment]
@nstein5 - Please try to give us more detail. Saying something is bad is literally useless to us. If you go to the doctor you don't just say I feel bad. You tell him why you feel bad and what you think is causing it.

**Comment by nstein5** [comment]
It just runs extremely slow and swaps my titles
