### ISSUE TITLE
Welcome assistant opens each time program starts.

### ISSUE THREAD

**Issue by nirhp** [OpenShot/openshot-qt#975]
**System Details:**
windows 10
open shot 2.4.0

**Issue Description and steps to reproduce:**
The "Welcome assistant" / "Tutorials" window opens each time the program is started

Steps to reproduce:

1. Open the program - "Welcome assistant" / "Tutorials" windows will open.
2. Close that windows
3. Open the program again.

Result:
"Welcome assistant" / "Tutorials" windows will open.

![welcome](https://user-images.githubusercontent.com/14215603/31813644-dfffa484-b58f-11e7-8a93-6ebab8e4b8ce.png)

**Comment by DylanC** [comment]
Not able to reproduce.
