### ISSUE TITLE
Preview doesn't match fade & animation timings of rendered movie

### ISSUE THREAD

**Issue by jabowery** [OpenShot/openshot-qt#976]
**System Details:**
* Operating System / Distro: Windows 7
* OpenShot Version: 2.4.0

Mixing stills and videos on various tracks with fade and animation transitions I ended up with a preview with timings that was very different from the rendered movie.

In my attempt to create an osp archive file to upload here so the bug report would be reproducible, I found that when I re-opened the project, after shutting down OpenShot, that the preview matched the previously rendered movie.

I guess what I'd say to people is that to be on the safe side, before you render a movie, save the project, exit OpenShot, and then re-open the project.

**Comment by DylanC** [comment]
@jabowery - Same result in v2.4.1?
