### ISSUE TITLE
Fail to click "next" on the Tutorial "timeline"

### ISSUE THREAD

**Issue by songsammy** [OpenShot/openshot-qt#977]
**System Details:Win7 ultimate**
* Operating System / Distro: win7 x64,  1366x768
* OpenShot Version: 2.4.0

**Issue Description and steps to reproduce:**
*my monitor is 1366x768 , so I can't click "next"
I mean the Tutorial on "timeline"
![2](https://user-images.githubusercontent.com/30046778/31849471-1eeb307e-b675-11e7-9ea1-771815d423cc.PNG)

**Comment by yassir-a-p** [comment]
Same monitor resolution, same problem.
OS: Windows 10 version 1703
OpenShot Version: 2.4.0

**Comment by peanutbutterandcrackers** [comment]
Hey there, a fix to this issue was just merged into the source tree and is ready for testing. Could you please try out the [latest daily builds](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914) and see if this has been resolved? Thanks!
