### ISSUE TITLE
Voluem Control not working in 2.4.0

### ISSUE THREAD

**Issue by amandeep1singh** [OpenShot/openshot-qt#978]
**System Details:**
* Operating System / Distro:  Windows 7
* OpenShot Version: ? 2.4.0
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
Volume settings not working. I clicked volume setting of the track and selected the desired volume level for entire clip, but there is no change in the volume level.

**Comment by DylanC** [comment]
@amandeep1singh - Still an issue in v2.4.1?

**Comment by DylanC** [comment]
Cannot reproduce.
