### ISSUE TITLE
Chinese input is not supported

### ISSUE THREAD

**Issue by jingle0927** [OpenShot/openshot-qt#979]
**System Details:**
* Operating System / Distro: deepin
* OpenShot Version: 2.4.0

**Comment by DylanC** [comment]
@jingle0927  - Can you try this daily build? It should work with chose characters now:

https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.4.0-9-g7267417-56-648-x86_64.AppImage

**Comment by jingle0927** [comment]
@DylanC OK
