### ISSUE TITLE
Crash on right-click on project files

### ISSUE THREAD

**Issue by seindal** [OpenShot/openshot-qt#98]
I get a hard crash any time I right click on a project file.

The last output in the terminal is:
 main_window:INFO Loaded project /home/seindal/rene/.openshot_qt/backup/backup.osp
 files_model:INFO updating files model.
 files_model:INFO updating files model.
 files_model:INFO updating files model.
Unhandled Python exception
Aborted

This is openshot-qt version 2.0.6-dmo1 and libopenshot7 version 0.1.0-dmo2 installed on Debian testing from deb-multimedia.org.

I don't know if there's a keyboard shortcut to open the 'Add to timeline' dialog.

**Comment by seindal** [comment]
I removed everything and reinstalled.
It only happens in "Details view" not in "Thumbnail view".
It also happens if I press the Menu key on the keyboard, so it is not related to the right click as such, but to the appearance of the context menu.

**Comment by sydneyjd** [comment]
I can reproduce this as well. If i right click at all in the "details view" view it crashes instantly with: 
 main_window:INFO Switch to Details View
 files_model:INFO updating files model.
Unhandled Python exception
Aborted (core dumped)
-Sydney

**Comment by brobr** [comment]
same here, on slackware64

**Comment by zatherz** [comment]
Same here

**Comment by jonoomph** [comment]
This is fixed in latest version (to be released in the next day or two)
