### ISSUE TITLE
opeshot always crashes when exporting

### ISSUE THREAD

**Issue by DrWaleedAYousef** [OpenShot/openshot-qt#980]
**System Details:**
* Operating System / Distro: ?
Linux version 4.13.8-1-ARCH (builduser@tobias) (gcc version 7.2.0 (GCC)) #1 SMP PREEMPT Wed Oct 18 11:49:44 CEST 2017

* OpenShot Version: ?
2.4.0

* _Please attach log files if crash_
[log file](https://drive.google.com/file/d/0B1iCA_eP9jXBV09odEdpdWtpUkk/view?usp=sharing)

**Issue Description and steps to reproduce:**
Always crashes when exporting, e.g., after 11%, when export to:
Target: YouTube-HD, Video Profile: HD 720p 25 fps (1280x720), Quality: High.

. **However,** it does not crash when i export the same project to:
Target: MP4 (h.264), Video Profile: HDV 720 24p (1280x720), Quality: High.

**Comment by DylanC** [comment]
@DrWaleedAYousef - I would recommend to try v2.4.1.
