### ISSUE TITLE
Not valid video, audio or image file.

### ISSUE THREAD

**Issue by D-signr** [OpenShot/openshot-qt#981]
I installed OpenShot 2.4.0 to my computer and got an issue with video format. OpenShot 2.4 says that my .mp4 videos aren't valid video, audio or image files and refuses to open them. However, just a few minutes earlier I used the same files with OpenShot 2.2 and everything worked just fine. It doesn't sound like corrupted video files to me ( like the same issue was adressed earlier ).

System info:
Intel Core2Duo E8400 on Gigabyte GA-EP45-DS3R, with 7,8 GB DDR2 memory, GeForce GT 630/PCIe/SSE2
Kernel version: 4.1.38-nrj-desktop-2rosa-x86_64
OpenShot 2.2 -> OpenShot 2.4

**Comment by jathtech** [comment]
Same exact problem.  Not reading .mp4s

**Comment by DavidButterfield** [comment]
Openshot 2.4.0 fails to import four out of ten video files importable using openshot 1.4.3.
The four failing video clips are three .webm and one .mkv ("Matroska data", according to file(1)).
The three other .mkv files import fine.
All ten video files import fine in 1.4.3, the official version in the Ubuntu distribution.
But 1.4.3 crashes way to often to be usable, which is why I tried switching to 2.4.0.
But 2.4.0 can no longer import 40% of video files out of a sample of ten files.
Which is the most recent stable and known-working version of openshot?

**Comment by DavidButterfield** [comment]
I tried importing a few hundred more clips and looked for patterns of differences between successful and failing imports.
I noticed that all my video files state either "h264" or "vp9".
ALL of the h264 files successfully import.
ALL of the vp9 files FAIL to import.
Attached is some ffmpeg output from sample "work" and "fail" files;
also openshot output with the "Unknown/unsupported AVCodecID V_VP9" message.

[errrpt.txt](https://github.com/OpenShot/openshot-qt/files/1423616/errrpt.txt)

**Comment by DavidButterfield** [comment]
I have tried this also on openshot 2.2.0 and 2.1.0.
In both cases it behaves like 2.4.0, failing to import vp9 files.
However 1.4.3 can import the same "fail" vp9 file.

**Comment by DavidButterfield** [comment]
If I convert the failing vp9 clip to h264 then I am able to import the result using openshot 2.4.0.
$ ffmpeg -i fail.mkv -vcodec h264 out.mkv
This provides a workaround.

**Comment by D-signr** [comment]
Now after using multiple audio and video files in the same project, the program suddenly lost connection to one of the most recent audio files in the project. The file is exactly where it is supposed to be and works fine, the program just doesn't find it anymore and so it crashes after prompting me to find that missing file. Somehow the finding tool sees only folders, not files so I can only address it to the right folder.

Moreover the program tends to crash quite often and it had problems with playback too. However, exported videos were flawless and no crashing occurred during the export process.

I wanted to like the OpenShot, but it is way too unstable and I can't upgrade it to its newest version because of the #981 problem. So I've decided to rebuild my project in Shotcut. I may return to OpenShot once it's terrible issues are fixed, because regardless of all the issues I've encountered with it, the overall feeling with its user interface and functions is good.

**Comment by DylanC** [comment]
@D-signr - I would recommend to try v2.4.1.

**Comment by peanutbutterandcrackers** [comment]
@D-signr - I can confirm that mp4 files do indeed work with OpenShot v2.4.1. Perhaps you'd like to try that?

**Comment by peanutbutterandcrackers** [comment]
@DavidButterfield - Whoa. You are a really good tester! I hope you continue to test OpenShot and submit issues and perhaps even contribute patches to it (your DP looks like you are one of them UNIX hackers), good sir!

**Comment by D-signr** [comment]
I did a short test with my mp4 files and OpenShot v2.4.1. It seems that it can open those mp4 files I've edited and saved as mp4 with OpenShot v2.2.0. However, with unedited mp4 files the result is still the same, they're not valid.

**Comment by peanutbutterandcrackers** [comment]
Strange... on my elementary OS 0.4.1 'Loki' machine, mp4 files (even unedited ones) import just fine. I wonder what is causing this issue...

Perhaps you could try seeing which encoder is being used to encode the unedited mp4 files and maybe the development team could add support for that?
[But then again, OpenShot uses ffmpeg, which supports a truck load of stuffs...]

**Comment by dowens76** [comment]
This issue was closed, but it remains in 2.4.1 on Windows and Ubuntu 18.04, at least for JPEG and PNG files.

**Comment by cnighswonger** [comment]
Still an issue in 2.6.1 with the Window build.

![2 6 1_OpenShot](https://user-images.githubusercontent.com/115404/177056946-b7e17463-96c3-4932-af15-698af6d9c982.jpg)

**Comment by JacksonRG** [comment]
@cnighswonger Is this in the release version or the [daily build](https://www.openshot.org/download/)? And is this happening with all files, certain ones, or a specific format?

**Comment by mkeen** [comment]
This is happening with all video files no matter how I encode them with ffmpeg on Debian daily.. linux kernel 6.0
