### ISSUE TITLE
blender associate

### ISSUE THREAD

**Issue by team-kro19** [OpenShot/openshot-qt#982]
**System Details: PC windows 10 64bit
* Operating System / Distro: ?
* OpenShot Version: V2.4.0

bonjour , je suis nouveau et je demande votre aide pour associer BLENDER a openshot.

le chemin ne marche pas : "C:\Program Files\Blender Foundation\Blender\blender.exe"
ni  même C:\Program Files\Blender Foundation\Blender\blender.exe
ou encore "C:\Program Files\Blender Foundation\Blender" 
et C:\Program Files\Blender Foundation\Blender

que faire  ?

----Blender, la suite libre et open source de création de contenu 3D est requise pour cette action (http://www.blender.org).

Dans les préférences d'OpenShot, veuillez vérifier que l'exécutable de Blender est correct. Ce paramètre devrait être le chemin d'accès à l'exécutable 'blender' sur votre système. Assurez-vous aussi qu'il pointe bien vers la version 2.78  (ou supérieure) de Blender.

Chemin vers l'exécutable de Blender :
C:\Program Files\Blender Foundation\Blender\blender.exe ----

thanks

**Comment by PASTJL** [comment]
Le  bug report est en Anglais, je vais repondre en Anglais pour tout le monde.
With Windows, to associate Blender and Inkscape, you have to add firts the  2 pathes in the environment variables of Windows, variable PATH of course.
In the configuration panel of Openshot, you must fill the fields resp with inkscape and blender without any path.

**Comment by DylanC** [comment]
EN:
Hello, I am new and I ask your help to associate BLENDER with openshot.

the path does not work: "C: \ Program Files \ Blender Foundation \ Blender \ blender.exe"
nor even C: \ Program Files \ Blender Foundation \ Blender \ blender.exe
or "C: \ Program Files \ Blender Foundation \ Blender"
and C: \ Program Files \ Blender Foundation \ Blender

what to do ?

---- Blender, the free and open source 3D content creation suite is required for this action (http://www.blender.org).

In OpenShot preferences, please check that the Blender executable is correct. This parameter should be the path to the 'blender' executable on your system. Also make sure it points to version 2.78 (or higher) of Blender.

Path to the Blender executable:
C: \ Program Files \ Blender Foundation \ Blender \ blender.exe ----

thanks

**Comment by DylanC** [comment]
Closing this as answered. Really setting the path should work as long as Blender is installed. This feature does work in OpenShot currently.
