### ISSUE TITLE
Cant open any saved project

### ISSUE THREAD

**Issue by Ossax** [OpenShot/openshot-qt#983]
Hello,

**System Details:**                                - i5, 2.6Ghz , 8Gb, x64
* Operating System / Distro: ?              - Win10
* OpenShot Version: ?                           - 2.4.0
* _Please attach log files if crash_          - no

**Issue Description and steps to reproduce:**

I made and saved few projects as different names(like project.osp) but now I cant open anyone.
unfortunatly, I cant attach my *osp file here. than I try, I saw a lot of .png like this:
![0zyjshfl6p-24](https://user-images.githubusercontent.com/33073876/31970445-3e37e454-b918-11e7-9452-d3571840e1b3.png)

**Comment by PASTJL** [comment]
In the full path of the location of the osp project, do you have name of directories with space or accentuated characters ?

**Comment by AndyID17W** [comment]
I am having the same problem. Yes, I do have spaces in the file names and directories? This hasn't been a problem in the past. Is this a new bug with version 2.4.0?

**Comment by DylanC** [comment]
@Ossax @AndyID17W

The latest daily build solves issues with those characters:

https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.4.0-9-g7267417-56-648-x86_64.exe

Let me know if it is now working for you.

**Comment by DylanC** [comment]
Dup of #677
