### ISSUE TITLE
Suggestion: using custom image in animated title

### ISSUE THREAD

**Issue by BarbzYHOOL** [OpenShot/openshot-qt#985]
If we could use custom images in animated titles, it would make the animated title functionality useful because at the moment we are forced to have that ugly font "bfont". With our own custom image (png) we could be really more creative but at the moment I don't see any interest in using animated titles.

Even the one that brings together 4 clips is buggy/incomplete and serves no purpose. That's really missing in openshot to allow us to make something a bit more "professional" looking. Every new update I check if anything has changed regarding animated title and no :'(

Thank you for all your work !

**Comment by PASTJL** [comment]
Perhaps I don't understand your need, but Openshot has a lot of animated title associated with Blender.You can adapt the render of this title with Blender.
What i do , for custom effects in title, i create directly the animated title in Blender and render as a set of png transparent images that you can after import in Openshot project. 
Note : if you don't know Blender, the learning curve is a bit hard for a new user.

**Comment by BarbzYHOOL** [comment]
>  Note : if you don't know Blender, the learning curve is a bit hard for a new user.

Thanks for noticing. Also needs to know python. And I doubt you can make the same things as in gimp or photoshop in blender, so it's not a solution

**Comment by PASTJL** [comment]
Humm! I don't agree Blender is a powerful tool for 3D and 2D animation or images.. It has also its own Video editor Blender VSE
