### ISSUE TITLE
Application crash when applying time slowing function

### ISSUE THREAD

**Issue by Orao40** [OpenShot/openshot-qt#989]
**System Details:**
![system](https://user-images.githubusercontent.com/33151903/32100988-73a64e5a-bb16-11e7-91ab-ff6837603e76.JPG)

* Operating System / Distro: Windows 7 64-bit 
* OpenShot Version: 2.3.4 
* [Error report.txt](https://github.com/OpenShot/openshot-qt/files/1421793/Error.report.txt) 

Hi guys, the issue appears as follows:

Every time I try to slower the video or apply the transition application crash. I tried with different time slowing values and every time is the same.
Please let me know if you need more info.
Thanx in advance.

**Comment by DylanC** [comment]
@Orao40 - I would recommend to try the latest daily build. Its much better on Windows.

**Comment by Orao40** [comment]
Thank you for responding. I have to add that I've noticed later that my OpenShot version is obsolete since there was a new update. Naturally I thought that it could be a problem so I updated the OpenShot to a newest version but the results were the same. Crashing.
Can you tell me more about latest daily build cause, honestly, I have no idea what you are talking about?
Please post me a link or something.
Thank you in advance. 
Cheers!

**Comment by DylanC** [comment]
@Orao40 - Confirmed as fixed in #588. Try the OpenShot v2.4.1 version.

**Comment by DylanC** [comment]
Dup of #588
