### ISSUE TITLE
How to install Openshot 2.4.0 For Linux?

### ISSUE THREAD

**Issue by PcBrewer** [OpenShot/openshot-qt#990]
I am running Linux Mint 18.2 and trying to add the PPA's to get the new Openshot 2.4.0 to install.  I have tried both sets of PPA's with no luck.  I even uninstalled the version 1.4.3 that is in the software manager.  Any suggestions?  thank you.

**Comment by DylanC** [comment]
@PcBrewer - I think something is wrong with the PPA. I would suggest to try the AppImage for now.
