### ISSUE TITLE
Scale after rotate is broken

### ISSUE THREAD

**Issue by fjdebruijn81** [OpenShot/openshot-qt#991]
**System Details:** AMD Phenom II X4 955, 4GB, RAM 3.2Ghz
**Operating System:** Arch Linux 4.13.9-1-ARCH #1 SMP PREEMPT Sun Oct 22 09:07:32 CEST 2017 x86_64
**OpenShot Version:** 2.4.0-1

**Issue Description and steps to reproduce:**
After rotating a video shot in portrait to the left 1/4 of the video is shown on the output window and any when one tries to translate it's position (if they can grab the centre handle) the mouse sensitivity is insane and uncontrollable. when one tries to scale the video the handles operate in the wrong direction with insane sensitivity.

Demo Video of bug is here
https://youtu.be/HzB5miEnnwI

**Comment by DylanC** [comment]
@fjdebruijn81 - Same result on v2.4.1?

**Comment by peanutbutterandcrackers** [comment]
@fjdebruijn81 - Could you please also submit a patch for it, good sir? Since you're using arch, pretty sure you can fix it in an afternoon or two. It seems Mr. Jonathan, alone, does not have to time to go around fixing all the bugs...
