### ISSUE TITLE
Preview Pane Disappeared

### ISSUE THREAD

**Issue by 25skiddoo** [OpenShot/openshot-qt#992]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

Running openshot 2.4.0 on Win10 and video preview pane has disappeared.  How do I get it back?  Also, how do I get transition icons back that appeared on top left of OS?  Thanks.

**Comment by DylanC** [comment]
@25skiddoo - Can you try the menu entry Views>>Simple View ?  It should restore the default interface for you.

**Comment by 25skiddoo** [comment]
Thanks DylanC - that worked!

**Comment by DylanC** [comment]
@25skiddoo - No problem. Glad you got sorted.

**Comment by lakshit5292** [comment]
> @25skiddoo - Can you try the menu entry Views>>Simple View ? It should restore the default interface for you.

dhnyawad bhai sahab, it worked thankyou so much
