### ISSUE TITLE
OpenShot is still not useable.. stuttering video preview playback.  10fps tops!

### ISSUE THREAD

**Issue by jerrynsr** [OpenShot/openshot-qt#993]
**System Details:Xeon E5-1650 6 Core 32gb ram, dual AMD Tahiti 6GB ram
* Operating System / Distro: Ubuntu 17.04 kernel 4.13.0-16
* OpenShot Version: 2.4.0 (APP run file.. downloaded and ran from there to see if the problem exists

I use a GoPro Hero 4 Black. Video format is 1080p 60fps.  Google for my videos on Youtube.  Normandin Hobby.  The video was created with FCPX.   I am getting ready to dump MacOS.  I am running Ubuntu on my Mac,,bare metal .   OpenShot appears to be stuttering, the issue has existed for a while. If you want GoPro video to test with I can upload mine.  It plays fine with VLC

Please let me know when it's fixed.   I really want to dump MacOS.

**Comment by jerrynsr** [comment]
The H264 Codec appears to be broken.   If I re-encode my GoPro with Handbrake it works.
The OpenShot 2.4.0 app binary does not work at all...  stutters no matter what encoding
Will there be a Codec Update ?

**Comment by altermac** [comment]
I'm playing around with Openshot 2.4.0 on Windows 10, Toshiba Satellite AMD A8-6410 with Radeon R5:
When I use a H264 720p video with 60 fps from a Runcam2, preview video and sound is stuttering, final Export with 720p is fine. CPU is 100% in preview. When I use 720p or 1080p with 30fps from another cam (Medion Traveller HD), the preview runs smooth on 45% CPU.
Seems that preview or ffmpeg renders the film just in time to 30fps before showing in preview window. So maybe it's no bug, only too much data for the pipeline.

**Comment by DylanC** [comment]
@jerrynsr - This is a known issue. We will be working on a fix for this.

**Comment by DylanC** [comment]
@jerrynsr - You should try the cache limiting for the preview issue.

**Comment by DylanC** [comment]
Dup of #960
