### ISSUE TITLE
Can't Upload to YouTube?

### ISSUE THREAD

**Issue by PrisRock** [OpenShot/openshot-qt#994]
**System Details:**
* Operating System / Distro: ? Windows 10
* OpenShot Version: ? 2.4.0 (Newly downloaded today)
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

I can't upload to YouTube.  Every time that I try after exporting there is no screen that pops to sign into YouTube.

**Comment by DylanC** [comment]
@PrisRock - Did it work like this before? I don't think this is expected to happen.
