### ISSUE TITLE
Audio not exporting with video.

### ISSUE THREAD

**Issue by Stitches-KHK-27** [OpenShot/openshot-qt#996]
**System Details:**
* Operating System / Distro: Windows 7
* OpenShot Version: 2.4

I exported my video and it exported just fine with all of my transitions working fine. But my exported video has no audio, not any of the people talking or the music that I included in my video. Am I doing something incorrectly? I used the defaults for exporting. I tried a few different times to export but every time there is no sound on my video.

Thanks for your time

**Comment by DylanC** [comment]
@Stitches-KHK-27 - Can you try the daily build and get back to me? Lots of people with audio issues have had great success trying the daily build instead.

**Comment by Stitches-KHK-27** [comment]
Still nothing, I tried the top three daily builds

**Comment by DylanC** [comment]
@Stitches-KHK-27 - Alright, I will leave this open and give it a shot myself to see can it be reproduced.

**Comment by peanutbutterandcrackers** [comment]
Hey, could you please try [this solution](https://github.com/OpenShot/openshot-qt/issues/1047#issuecomment-364873556) out and get back to me, please? It could be a very simple encoder related issue and using a different encoder just might/will possibly solve it.

**Comment by DylanC** [comment]
@Stitches-KHK-27 Can you try v2.4.2 and let us know if you have success? A change was put in for the audio issues.
