### ISSUE TITLE
Please save my poor high school soul

### ISSUE THREAD

**Issue by thesadanddepressedstudent** [OpenShot/openshot-qt#997]
**System Details:** Windows 10
* Operating System / Distro: No idea
* OpenShot Version: Newest
* _Please attach log files if crash_
I've spent so long on a dumb video but it won't open each time it lags please help me I'm just a sad student trying to pass high school.

I can't even attach it I'm so done kms

**Issue Description and steps to reproduce:**
****

**Comment by DylanC** [comment]
@thesadanddepressedstudent - Is the problem it won't open or it lags after opening?
