### ISSUE TITLE
OpenShot crashes when exporting

### ISSUE THREAD

**Issue by rshrestha32** [OpenShot/openshot-qt#998]
System Details: Windows
Operating System / Distro: Windows 10
* OpenShot Version: 2.4.0
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
Everytime I try to export my video it keeps crashing when it gets to 57%. I am using several .mov files which I have either froze, slowed down, or faded into. I am also using some .m4a and .mp3 files for audio which have been clipped as well. I've checked my memory and I should be okay and I just downloaded the daily build.

**Comment by DylanC** [comment]
@rshrestha32 - I would recommend to try v2.4.1. Its much more reliable.
