### ISSUE TITLE
Border around video after export?

### ISSUE THREAD

**Issue by mnally8** [OpenShot/openshot-qt#999]
Video looks great in preview, but when exported, the video has a thick black border around the edges which looks terrible. I want to upload the video to youtube but i want the video to be the whole screen not the border. Any fixes??

**Comment by N3WWN** [comment]
Is your project profile the same aspect ratio as your clips?  

If they aren't and can't be the same, perhaps you can remove the borders with one of the Scale properties (Crop, Best Fit, Stretch, None)...

**Comment by mnally8** [comment]
@N3WWN Had the wrong ratio thank you!

**Comment by TurtleDynasty** [comment]
I have the same problem, but the resolution of the project profile and the video clips are identical. 

The project profile says:

Profile: HD Vertical 1080p 30 fps (1080x1920)
Size: 1080x1920
FPS: 30.00
Other: DAR: 9/16, SAR: 1/1, Interlaced: False

I inspected the metadata on the video clips using VLC, They say:

Type: Video
Video Resolution: 1920x1080
Frame rate 30.008230

On each clip inside OpenShot, I can inspect the properties. They all say "Scale X" and "Scale Y" are 1.0. I'm not sure what else to inspect. The video clips were filmed vertically and the project is set to vertical. They do appear in the correct orientation, but they have a black border on all 4 sides in the preview and in the export. When I play the clips in VLC they don't display with black borders.
